### ISSUE TITLE
Can't access after install or update 15.0.4/15.0.5

### ISSUE THREAD

**Issue by vanwelie** [nextcloud/server#14939] opened 2019-04-02 21:45 UTC
### Steps to reproduce
1. Go to https://office.vanwelie.net
2. Log in with my account
3. Get an error with an internal server error

### Expected behaviour
When I logged in, I will redirect to my home-directory on my server install.

### Actual behaviour
I get an error with an internal server error.

### Server configuration

**Operating system**:

**Web server:**

**Database:** 

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.4 and 15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
15.0.4 is fresh install, 15.0.5 is an update from 15.0.1
**Where did you install Nextcloud from:**
.zip from nextcloud.com and install with FileZilla.
**Signing status:**
-- It is not possible to do that =( --

**Nextcloud configuration:**
<details>
<summary>Config File</summary>

$CONFIG = array (
  'instanceid' => 'ocqc7hz52wih',
  'passwordsalt' => '---',
  'secret' => '---',
  'trusted_domains' => 
  array (
    0 => 'office.vanwelie.net',
  ),
  'datadirectory' => '/subdomains/office/data',
  'dbtype' => 'mysql',
  'version' => '15.0.4.0',
  'overwrite.cli.url' => 'https://office.vanwelie.net',
  'dbname' => '---',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '---',
  'dbpassword' => '---',
  'installed' => true,
);
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 66.0.2 (64-bits)
**Operating system:**
Windows 10
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"XKPO3n8AAQEAACgsQnEAAAAN","level":3,"time":"2019-04-02T21:06:38+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"openssl_pkey_export(): cannot get key from parameter 1 at \/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php#298","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
{"reqId":"XKPO3n8AAQEAACgsQnEAAAAN","level":3,"time":"2019-04-02T21:06:38+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":{"Exception":"TypeError","Message":"openssl_pkey_get_details() expects parameter 1 to be resource, boolean given","Code":0,"Trace":[{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":301,"function":"openssl_pkey_get_details","args":[false]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":271,"function":"newToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":["*** sensitive parameter replaced ***","dennisvanwelie","dennisvanwelie","passwordX","Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0",0,0]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/Manager.php","line":131,"function":"convertToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":[{"id":1,"__class__":"OC\\Authentication\\Token\\DefaultToken"},"*** sensitive parameter replaced ***","passwordX"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":735,"function":"getToken","class":"OC\\Authentication\\Token\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":260,"function":"validateToken","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":235,"function":"validateSession","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":346,"function":"getUser","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":113,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/user.php","line":126,"function":"loadApps","class":"OC_App","type":"::","args":[["prelogin"]]},{"file":"\/subdomains\/office\/lib\/base.php","line":721,"function":"setupBackends","class":"OC_User","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/subdomains\/office\/index.php","line":40,"args":["\/subdomains\/office\/lib\/base.php"],"function":"require_once"}],"File":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","Line":301,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
{"reqId":"XKPO338AAQEAACgp3cwAAAEY","level":3,"time":"2019-04-02T21:06:39+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"PHP","method":"GET","url":"\/index.php\/js\/core\/merged-template-prepend.js?v=a6085679-0","message":"openssl_pkey_export(): cannot get key from parameter 1 at \/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php#298","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
{"reqId":"XKPO338AAQEAACgp3cwAAAEY","level":3,"time":"2019-04-02T21:06:39+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"index","method":"GET","url":"\/index.php\/js\/core\/merged-template-prepend.js?v=a6085679-0","message":{"Exception":"TypeError","Message":"openssl_pkey_get_details() expects parameter 1 to be resource, boolean given","Code":0,"Trace":[{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":301,"function":"openssl_pkey_get_details","args":[false]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":271,"function":"newToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":["*** sensitive parameter replaced ***","dennisvanwelie","dennisvanwelie","passwordX","Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0",0,0]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/Manager.php","line":131,"function":"convertToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":[{"id":1,"__class__":"OC\\Authentication\\Token\\DefaultToken"},"*** sensitive parameter replaced ***","passwordX"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":735,"function":"getToken","class":"OC\\Authentication\\Token\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":260,"function":"validateToken","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":235,"function":"validateSession","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":346,"function":"getUser","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":113,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/user.php","line":126,"function":"loadApps","class":"OC_App","type":"::","args":[["prelogin"]]},{"file":"\/subdomains\/office\/lib\/base.php","line":721,"function":"setupBackends","class":"OC_User","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/subdomains\/office\/index.php","line":40,"args":["\/subdomains\/office\/lib\/base.php"],"function":"require_once"}],"File":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","Line":301,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
{"reqId":"XKPPzn8AAQEAAChKttcAAACP","level":3,"time":"2019-04-02T21:10:38+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"PHP","method":"GET","url":"\/","message":"openssl_pkey_export(): cannot get key from parameter 1 at \/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php#298","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
{"reqId":"XKPPzn8AAQEAAChKttcAAACP","level":3,"time":"2019-04-02T21:10:38+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"index","method":"GET","url":"\/","message":{"Exception":"TypeError","Message":"openssl_pkey_get_details() expects parameter 1 to be resource, boolean given","Code":0,"Trace":[{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":301,"function":"openssl_pkey_get_details","args":[false]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":271,"function":"newToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":["*** sensitive parameter replaced ***","dennisvanwelie","dennisvanwelie","passwordX","Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0",0,0]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/Manager.php","line":131,"function":"convertToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":[{"id":1,"__class__":"OC\\Authentication\\Token\\DefaultToken"},"*** sensitive parameter replaced ***","passwordX"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":735,"function":"getToken","class":"OC\\Authentication\\Token\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":260,"function":"validateToken","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":235,"function":"validateSession","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":346,"function":"getUser","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":113,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/user.php","line":126,"function":"loadApps","class":"OC_App","type":"::","args":[["prelogin"]]},{"file":"\/subdomains\/office\/lib\/base.php","line":721,"function":"setupBackends","class":"OC_User","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/subdomains\/office\/index.php","line":40,"args":["\/subdomains\/office\/lib\/base.php"],"function":"require_once"}],"File":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","Line":301,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
{"reqId":"XKPPzn8AAQEAACiPWHMAAABP","level":3,"time":"2019-04-02T21:10:38+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"PHP","method":"GET","url":"\/index.php\/js\/core\/merged-template-prepend.js?v=a6085679-0","message":"openssl_pkey_export(): cannot get key from parameter 1 at \/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php#298","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
{"reqId":"XKPPzn8AAQEAACiPWHMAAABP","level":3,"time":"2019-04-02T21:10:38+00:00","remoteAddr":"77.249.10.123","user":"dennisvanwelie","app":"index","method":"GET","url":"\/index.php\/js\/core\/merged-template-prepend.js?v=a6085679-0","message":{"Exception":"TypeError","Message":"openssl_pkey_get_details() expects parameter 1 to be resource, boolean given","Code":0,"Trace":[{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":301,"function":"openssl_pkey_get_details","args":[false]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","line":271,"function":"newToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":["*** sensitive parameter replaced ***","dennisvanwelie","dennisvanwelie","passwordX","Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0",0,0]},{"file":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/Manager.php","line":131,"function":"convertToken","class":"OC\\Authentication\\Token\\PublicKeyTokenProvider","type":"->","args":[{"id":1,"__class__":"OC\\Authentication\\Token\\DefaultToken"},"*** sensitive parameter replaced ***","passwordX"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":735,"function":"getToken","class":"OC\\Authentication\\Token\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":260,"function":"validateToken","class":"OC\\User\\Session","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/subdomains\/office\/lib\/private\/User\/Session.php","line":235,"function":"validateSession","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":346,"function":"getUser","class":"OC\\User\\Session","type":"->","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/app.php","line":113,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/private\/legacy\/user.php","line":126,"function":"loadApps","class":"OC_App","type":"::","args":[["prelogin"]]},{"file":"\/subdomains\/office\/lib\/base.php","line":721,"function":"setupBackends","class":"OC_User","type":"::","args":[]},{"file":"\/subdomains\/office\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/subdomains\/office\/index.php","line":40,"args":["\/subdomains\/office\/lib\/base.php"],"function":"require_once"}],"File":"\/subdomains\/office\/lib\/private\/Authentication\/Token\/PublicKeyTokenProvider.php","Line":301,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}
</details>

**Comment by kesselb** [comment] 2019-04-03 16:47
@vanwelie the log contained your password ("yWfxxxxxxx") in cleartext. I removed the revision but you might change it just in case.

@nextcloud/security any idea why the password was there in cleartext? Replaced the password with "passwordX".

**Comment by kesselb** [comment] 2019-04-03 17:11
https://github.com/nextcloud/server/issues/11570
https://github.com/nextcloud/server/issues/12890
https://github.com/nextcloud/server/issues/11227

This kind of error is hard to debug. See the issues above.

**Comment by vanwelie** [comment] 2019-04-03 20:48
I have removed the clean installation from office.vanwelie.net. I'm not a developer. I can make Wordpress sites and a little php, mysql, css and html. And I play a little with a Raspberry Pi. But that's it. I host my website by TransIP and they don't support issues with Nextcloud on the webhosting. So, thanks for thinking, but it is to hard for me. 

I will close the ticket and maybe next year I try again to use Nextcloud as my private office instead of outlook.com ;)

Have a nice day!

**Comment by kesselb** [comment] 2019-04-03 20:59
Okay :disappointed: Some people reported that this change https://github.com/nextcloud/server/issues/11227#issuecomment-473904363 could solve the problem for them. For general configuration questions / setup issues you may visit https://help.nextcloud.com.

**Comment by vanwelie** [comment] 2019-04-03 21:29
When I do that, I get the simular issue with a clean install. I get this extra error on the top of the screen (see attachment)

![nextcloud 15 0 5-error](https://user-images.githubusercontent.com/49212758/55514430-5b4ef700-5668-11e9-88a2-960db6bf68b7.png)

**Comment by kesselb** [comment] 2019-04-03 21:45
Hmm. I guess `openssl` is missing on your system (or some bindings).

**Comment by vanwelie** [comment] 2019-04-03 21:46
How can I fixed that?

**Comment by kesselb** [comment] 2019-04-03 21:48
I'm afraid on a shared webhosting there is nothing you can :disappointed:

**Comment by vanwelie** [comment] 2019-04-03 21:50
But it is wired. Because first I can used Nextcloud on this server, but now it isn't possible. The problem is my hosting provider I guess?

**Comment by kesselb** [comment] 2019-04-03 21:54
Yes it's weird. This kind of error is related to some openssl related things. You might try it on your raspi ;)

**Comment by vanwelie** [comment] 2019-04-03 22:04
Alright. But my raspi don't have much disk space ;) I have running there Domoticz and that's all. Thanks for now. I will contacting my hosting provider and ask them why this is changed. 

Have a nice day!

**Comment by vanwelie** [comment] 2019-04-04 18:17
My hosting have repleyed to me and said that OpenSSL is already eneabled to my hosting. So, the problem is not that my hosting provider blocked the OpenSSL-connection. What is then the problem? 

For more information about the phpinfo on my webhosting, see: https://werkplek.vanwelie.net/php-info.php

**Comment by j-ed** [comment] 2019-04-04 18:48
It might be worse to test, if adding the following parameter to your configuration helps. Make sure that the file can be accessed by your web server user. Just my 2ct to the discussion.
```
  'openssl' =>
  array (
    'config' => '/usr/lib/ssl/openssl.cnf',
  ),
```

**Comment by vanwelie** [comment] 2019-04-04 20:09
No, this is not working for me. I have read the hole issue #11227 , but this is not the solution for my problem. The error is now:

`bool(false) string(61) "error:02001002:system library:fopen:No such file or directory" `

Any other ideas?
Thanks for so far guys!

**Comment by j-ed** [comment] 2019-04-05 08:17
I think you should ask aunt G. for some more hints on the root cause I have the impression, that this isn't a Nextcloud specific issue but an OpenSSL specific issue. If you check these postings, you will see that the message can e.g. be caused by a missing **index.txt** or **index.txt.attr** file. 

1. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.2/html/Developer_Guide/Creating_an_SSL_Certificate.html

2. https://mta.openssl.org/pipermail/openssl-users/2015-February/000495.html

**Comment by skjnldsv** [comment] 2020-08-25 09:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:17 UTC
Labels: 0. Needs triage, bug
