### ISSUE TITLE
very slow user interaction after faulty nextcloud share

### ISSUE THREAD

**Issue by saiiman** [nextcloud/server#19685] opened 2020-02-27 21:29 UTC
### Steps to reproduce
1. include a share of another Nextcloud instance in your own instance
2. Shut down nextcloud instance with the shared folder

### Expected behaviour
* log entry about the not available share
* continue normal use of the cloud

### Actual behaviour
after a mounted nextcloud share of another instance was no longer available (this instance lost the network connection) the share folder could not be deleted. (message: an error has occurred).
But the real problem is that the whole interaction with the user who mounted the share became very slow. This was true for the synchronization with a windows client as well as webdav and the access via the web browser. (Page requests via browser had a response time of about 2 minutes).
By deleting the share in the database table 'oc_shares_external' the share could be deleted. The nextcloud behaved immediately afterwards again normally.

### Server configuration
* Ubuntu Server 18.04 LTS
* Apache 2.4.41
* MySQL  Ver 15.1 Distrib 10.1.43-MariaDB
* PHP 7.2.24
* Nextcloud 17.01 (Update to 18.01 did not fix the problem)
* (Last clean install was about version 15)

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
* activity: 2.11.0
* bruteforcesettings: 1.5.0
* calendar: 2.0.1
* cloud_federation_api: 1.1.0
* contacts: 3.1.9
* dav: 1.14.0
* federatedfilesharing: 1.8.0
* files: 1.13.1
* files_antivirus: 2.2.1
* files_pdfviewer: 1.7.0
* files_rightclick: 0.15.2
* files_sharing: 1.10.1
* files_trashbin: 1.8.0
* files_versions: 1.11.0
* logreader: 2.3.0
* lookup_server_connector: 1.6.0
* nextcloud_announcements: 1.7.0
* notifications: 2.6.0
* oauth2: 1.6.0
* password_policy: 1.8.0
* photos: 1.0.0
* privacy: 1.2.0
* provisioning_api: 1.8.0
* ransomware_protection: 1.6.0
* serverinfo: 1.8.0
* settings: 1.0.0
* sharebymail: 1.8.0
* text: 2.0.0
* twofactor_backupcodes: 1.7.0
* twofactor_totp: 4.1.2
* twofactor_u2f: 5.0.2
* updatenotification: 1.8.0
* viewer: 1.2.0
* workflowengine: 2.0.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "LOCAL-IP",
            "EXTERNAL-URL"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/LOCAL-IP\/nextcloud",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "app_install_overwrite": [
            "calendar",
            "bruteforcesettings"
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "983"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.1.9",
            "types": ""
        },
        "core": {
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1568996110.1319",
            "lastcron": "1582837522",
            "lastupdateResult": "[]",
            "lastupdatedat": "1582833489",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_allow_resharing": "yes",
            "shareapi_default_expire_date": "yes",
            "shareapi_enable_link_password_by_default": "yes",
            "shareapi_enforce_expire_date": "no",
            "shareapi_enforce_links_password": "yes",
            "shareapi_expire_after_n_days": "14",
            "theming.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "updater.secret.created": "1582833084",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendInvitations": "yes",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "10 GB",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "only_log",
            "av_max_file_size": "-1",
            "av_mode": "socket",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamav\/clamd.ctl",
            "av_stream_max_length": "26214400",
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem,dav"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Mon, 02 Sep 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.8.0",
            "minLength": "10",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "ransomware_protection": {
            "enabled": "yes",
            "extension_exclusions": "[\".lock\",\".\"]",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.4.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "enforcePasswordProtection": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "last_report": "{\"id\":\"oct4b31pyzv8\",\"items\":[[\"server\",\"version\",\"17.0.1.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"none\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.2.24\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.1.43\"],[\"database\",\"size\",355418112],[\"apps\",\"accessibility\",\"disabled\"],[\"apps\",\"activity\",\"2.10.1\"],[\"apps\",\"bruteforcesettings\",\"1.4.0\"],[\"apps\",\"calendar\",\"1.7.1\"],[\"apps\",\"cloud_federation_api\",\"1.0.0\"],[\"apps\",\"comments\",\"disabled\"],[\"apps\",\"contacts\",\"3.1.6\"],[\"apps\",\"dav\",\"1.13.0\"],[\"apps\",\"federatedfilesharing\",\"1.7.0\"],[\"apps\",\"federation\",\"disabled\"],[\"apps\",\"files\",\"1.12.0\"],[\"apps\",\"files_antivirus\",\"2.2.0\"],[\"apps\",\"files_pdfviewer\",\"1.6.0\"],[\"apps\",\"files_rightclick\",\"0.15.1\"],[\"apps\",\"files_sharing\",\"1.9.0\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.7.0\"],[\"apps\",\"files_versions\",\"1.10.0\"],[\"apps\",\"files_videoplayer\",\"1.6.0\"],[\"apps\",\"firstrunwizard\",\"disabled\"],[\"apps\",\"gallery\",\"18.4.0\"],[\"apps\",\"logreader\",\"2.2.0\"],[\"apps\",\"lookup_server_connector\",\"1.5.0\"],[\"apps\",\"nextcloud_announcements\",\"1.6.0\"],[\"apps\",\"notifications\",\"2.5.0\"],[\"apps\",\"oauth2\",\"1.5.0\"],[\"apps\",\"password_policy\",\"1.7.0\"],[\"apps\",\"privacy\",\"1.1.0\"],[\"apps\",\"provisioning_api\",\"1.7.0\"],[\"apps\",\"ransomware_protection\",\"1.5.1\"],[\"apps\",\"recommendations\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.7.0\"],[\"apps\",\"sharebymail\",\"1.7.0\"],[\"apps\",\"support\",\"disabled\"],[\"apps\",\"survey_client\",\"1.5.0\"],[\"apps\",\"systemtags\",\"disabled\"],[\"apps\",\"text\",\"1.1.1\"],[\"apps\",\"theming\",\"disabled\"],[\"apps\",\"twofactor_backupcodes\",\"1.6.0\"],[\"apps\",\"twofactor_totp\",\"4.0.0\"],[\"apps\",\"twofactor_u2f\",\"5.0.1\"],[\"apps\",\"updatenotification\",\"1.7.0\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"1.7.0\"],[\"stats\",\"num_files\",212674],[\"stats\",\"num_users\",7],[\"stats\",\"num_storages\",9],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",7],[\"stats\",\"num_storages_other\",1],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",7],[\"files_sharing\",\"num_shares_user\",1],[\"files_sharing\",\"num_shares_groups\",1],[\"files_sharing\",\"num_shares_link\",4],[\"files_sharing\",\"num_shares_link_no_password\",4],[\"files_sharing\",\"num_fed_shares_sent\",1],[\"files_sharing\",\"num_fed_shares_received\",1],[\"files_sharing\",\"permissions_3_1\",\"3\"],[\"files_sharing\",\"permissions_0_15\",\"1\"],[\"files_sharing\",\"permissions_1_15\",\"1\"],[\"files_sharing\",\"permissions_3_15\",\"1\"],[\"files_sharing\",\"permissions_6_15\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1582661097",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "4.1.2",
            "types": ""
        },
        "twofactor_u2f": {
            "enabled": "yes",
            "installed_version": "5.0.2",
            "types": ""
        },
        "updatenotification": {
            "contacts": "3.1.6",
            "core": "16.0.5.1",
            "enabled": "yes",
            "files_antivirus": "2.2.0",
            "installed_version": "1.8.0",
            "types": "",
            "update_check_errors": "0"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
* Windows 10
* Mozilla Firefox 73.0.1

#### Web server error log
not given

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available at <<closure>>

0. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 967
   OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath("SHARE_NAME")
1. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
   Sabre\DAV\Server->getPropertiesIteratorForPath("SHARE_NAME", ["{DAV:}getetag"], 0)
2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
   Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
3. <<closure>>
   Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
4. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   call_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
5. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
7. /var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
   Sabre\DAV\Server->exec()
8. /var/www/html/nextcloud/remote.php line 163
   require_once("/var/www/html/n ... p")

PROPFIND /remote.php/webdav/SHARE_NAME/
from IP by USER at 2020-01-31T06:25:09+00:00
</details>

#### Browser log
not given

**Comment by developerfromjokela** [comment] 2020-05-11 02:46
Can confirm, if I share across nextcloud instance, then shutting down the other one causes the first one to work very slowly

**Comment by developerfromjokela** [comment] 2020-05-18 16:12
This is really pain in the ass. I can't access my files when my friend's server goes down, but if I delete the table, then his shares aren't accessible by me. This should be no.1 focus of the dev team

**Comment by szaimen** [comment] 2021-06-02 11:26
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by szaimen** [comment] 2021-06-02 11:42
I think this is a duplicate of https://github.com/nextcloud/server/issues/12175

**Closed by szaimen** 2021-06-02 11:42 UTC
Labels: 0. Needs triage, bug, needs info
