### ISSUE TITLE
Note to recipitent is hidden when download button is hidden

### ISSUE THREAD

**Issue by jhesketh** [nextcloud/server#18320] opened 2019-12-10 10:41 UTC
# Steps to reproduce
1. Create a share link
2. Set a note to recipient
3. Set "Hide download"
4. Open the link, and not able to find the note to recipient

### Expected behaviour
The note to recipient should be visible regardless of the "hide download" setting.

### Actual behaviour
The note to recipient is not shown when downloads are hidden.

(The rest of the bug report template did not appear relevant to this bug. I'm happy to provide more information if required though).

**Comment by wiswedel** [comment] 2020-03-12 08:52
duplicate of https://github.com/nextcloud/server/issues/13617

**Closed by wiswedel** 2020-03-12 08:52 UTC
Labels: 0. Needs triage, bug
