### ISSUE TITLE
occ upgrade fails after accidentally upgrading from 20.0.8 to 21.0.1

### ISSUE THREAD

**Issue by quizilkend** [nextcloud/server#26472] opened 2021-04-09 10:21 UTC
### Steps to reproduce
1. Get notification that a new release (20.0.9) is available
2. initiate the upgrade over cli (updater.phar)
3. Select continue with occ upgrade

### Expected behaviour
1. The upgrade should follow the advertised path (see https://github.com/nextcloud/server/issues/26469)
2. occ upgrade should execute the upgrade steps

### Actual behaviour
There is no output of occ upgrade until it is killed by the kernel (OOM-killer).

### Server configuration

**Operating system:**
up-to-date debian buster

**Web server:**
Apache/2.4.38 (Debian)

**Database:**
mysql Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )

**Nextcloud version:** (Nextcloud admin page not reachable)
Somewhrere between 20.0.8 and 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes from 20.0.8

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
On demand
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
On demand
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
On demand
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
no
```
</details>

### Client configuration
**Browser:**
Firefox

**Operating system:**
Debian buster

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Fri Apr 09 10:57:49.957840 2021] [autoindex:error] [pid 2349] [client 2.206.161.85:37160] AH01276: Cannot serve directory /var/www/nextcloud/apps/news/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Fri Apr 09 11:20:44.557003 2021] [autoindex:error] [pid 1701] [client 2.206.161.85:38816] AH01276: Cannot serve directory /var/www/nextcloud/apps/news/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
There are so many entries which seem to be unrelated to the problem
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
The browser doesn't seem to be the problem here.
```
</details>

**Comment by hubertbanas** [comment] 2021-04-09 14:35
Experiencing identical issue

```
-->sudo -u www-data php updater.phar
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 20.0.8.

Update to Nextcloud 21.0.1 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] Y
Killed

Keep maintenance mode active? [y/N] N
Killed

Maintenance mode is disabled

```

Web shows Maintenance mode

occ no longer works

```
sudo -u www-data php occ
Killed
```

**Comment by caugner** [comment] 2021-04-09 15:26
@quizilkend @hubertbanas Could you share today's lines of the `updater.log` from your Nextcloud data directory?

(Make sure to redact private/secret information, if necessary.)

**Comment by hubertbanas** [comment] 2021-04-09 16:17
Please let me know if you need any other debug data.

```

2021-04-09T14:26:21+0000 redacted  [info] updater cli is executed
2021-04-09T14:26:21+0000 redacted  [info] currentStep()
2021-04-09T14:26:21+0000 redacted  [info] current version: 20.0.8 build time: 2021-02-24T19:11:39+00:00 1ff83111a63e795079d668bb15ffa84c1024596d
2021-04-09T14:26:21+0000 redacted  [info] getUpdateServerResponse()
2021-04-09T14:26:21+0000 redacted  [info] updaterServer: https://updates.nextcloud.com/updater_server/
2021-04-09T14:26:21+0000 redacted  [info] releaseChannel: stable
2021-04-09T14:26:21+0000 redacted  [info] internal version: 20.0.8.1
2021-04-09T14:26:21+0000 redacted  [info] updateURL: https://updates.nextcloud.com/updater_server/?version=20x0x8x1xxxstablexx2021-02-24T19%3A11%3A39%2B00%3A00+1ff83111a63e795079d668bb15ffa84c1024596dx7x3x27
2021-04-09T14:26:22+0000 redacted  [info] getUpdateServerResponse response: Array
(
    [version] => 21.0.1.1
    [versionstring] => Nextcloud 21.0.1
    [url] => https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
    [web] => https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=21.0.1
    [autoupdater] => 1
    [eol] => 0
    [signature] => redacted
)

2021-04-09T14:26:22+0000 redacted  [info] checkForUpdate() Array
(
    [version] => 21.0.1.1
    [versionstring] => Nextcloud 21.0.1
    [url] => https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
    [web] => https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=21.0.1
    [autoupdater] => 1
    [eol] => 0
    [signature] => redacted
)

2021-04-09T14:26:22+0000 redacted  [info] getChangelogURL()
2021-04-09T14:26:22+0000 redacted  [info] end of checkForUpdate() Update to Nextcloud 21.0.1 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip</code><br /><a class="external_link" href="https://nextcloud.com/changelog/#21-0-1" target="_blank" rel="noreferrer noopener">Open changelog ↗</a>
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] request to updater
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] currentStep()
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] show HTML page
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] current version: 20.0.8 build time: 2021-02-24T19:11:39+00:00 1ff83111a63e795079d668bb15ffa84c1024596d
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] getUpdateServerResponse()
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] updaterServer: https://updates.nextcloud.com/updater_server/
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] releaseChannel: stable
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] internal version: 20.0.8.1
2021-04-09T10:26:29-0400 RGG7f9SBA3 [info] updateURL: https://updates.nextcloud.com/updater_server/?version=20x0x8x1xxxstablexx2021-02-24T19%3A11%3A39%2B00%3A00+1ff83111a63e795079d668bb15ffa84c1024596dx7x3x27
2021-04-09T10:26:30-0400 RGG7f9SBA3 [info] getUpdateServerResponse response: Array
(
    [version] => 21.0.1.1
    [versionstring] => Nextcloud 21.0.1
    [url] => https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
    [web] => https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=21.0.1
    [autoupdater] => 1
    [eol] => 0
    [signature] => redacted
)

2021-04-09T10:26:30-0400 redacted [info] checkForUpdate() Array
(
    [version] => 21.0.1.1
    [versionstring] => Nextcloud 21.0.1
    [url] => https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
    [web] => https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=21.0.1
    [autoupdater] => 1
    [eol] => 0
    [signature] => redacted
)

2021-04-09T10:26:30-0400 redacted [info] getChangelogURL()
2021-04-09T10:26:30-0400 redacted [info] end of checkForUpdate() Update to Nextcloud 21.0.1 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip</code><br /><a class="external_link" href="https://nextcloud.com/changelog/#21-0-1" target="_blank" rel="noreferrer noopener">Open changelog ↗</a>
2021-04-09T14:26:59+0000 redacted  [info] updater started
2021-04-09T14:26:59+0000 redacted  [info] executeStep request for step "1"
2021-04-09T14:26:59+0000 redacted  [info] startStep("1")
2021-04-09T14:26:59+0000 redacted  [info] checkForExpectedFilesAndFolders()
2021-04-09T14:26:59+0000 redacted  [info] end of checkForExpectedFilesAndFolders()
2021-04-09T14:26:59+0000 redacted  [info] endStep("1")
2021-04-09T14:26:59+0000 redacted  [info] executeStep request for step "2"
2021-04-09T14:26:59+0000 redacted  [info] startStep("2")
2021-04-09T14:26:59+0000 redacted  [info] checkWritePermissions()
2021-04-09T14:26:59+0000 redacted  [info] end of checkWritePermissions()
2021-04-09T14:26:59+0000 redacted  [info] endStep("2")
2021-04-09T14:26:59+0000 redacted  [info] executeStep request for step "3"
2021-04-09T14:26:59+0000 redacted  [info] startStep("3")
2021-04-09T14:26:59+0000 redacted  [info] createBackup()
2021-04-09T14:26:59+0000 redacted  [info] backup folder location: /var/www/redacted.domain.com/data/updater-redacted /backups/nextcloud-20.0.8.1-1617978419/
2021-04-09T14:27:05+0000 redacted  [info] end of createBackup()
2021-04-09T14:27:05+0000 redacted  [info] endStep("3")
2021-04-09T14:27:05+0000 redacted  [info] executeStep request for step "4"
2021-04-09T14:27:05+0000 redacted  [info] startStep("4")
2021-04-09T14:27:05+0000 redacted  [info] downloadUpdate()
2021-04-09T14:27:05+0000 redacted  [info] getUpdateServerResponse()
2021-04-09T14:27:05+0000 redacted  [info] updaterServer: https://updates.nextcloud.com/updater_server/
2021-04-09T14:27:05+0000 redacted  [info] releaseChannel: stable
2021-04-09T14:27:05+0000 redacted  [info] internal version: 20.0.8.1
2021-04-09T14:27:05+0000 redacted  [info] updateURL: https://updates.nextcloud.com/updater_server/?version=20x0x8x1xxxstablexx2021-02-24T19%3A11%3A39%2B00%3A00+1ff83111a63e795079d668bb15ffa84c1024596dx7x3x27
2021-04-09T14:27:05+0000 redacted  [info] getUpdateServerResponse response: Array
(
    [version] => 21.0.1.1
    [versionstring] => Nextcloud 21.0.1
    [url] => https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
    [web] => https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=21.0.1
    [autoupdater] => 1
    [eol] => 0
    [signature] => redacted
)

2021-04-09T14:27:05+0000 redacted  [info] storage location exists
2021-04-09T14:27:19+0000 redacted  [info] end of downloadUpdate()
2021-04-09T14:27:19+0000 redacted  [info] endStep("4")
2021-04-09T14:27:19+0000 redacted  [info] executeStep request for step "5"
2021-04-09T14:27:19+0000 redacted  [info] startStep("5")
2021-04-09T14:27:19+0000 redacted  [info] verifyIntegrity()
2021-04-09T14:27:19+0000 redacted  [info] getUpdateServerResponse()
2021-04-09T14:27:19+0000 redacted  [info] updaterServer: https://updates.nextcloud.com/updater_server/
2021-04-09T14:27:19+0000 redacted  [info] releaseChannel: stable
2021-04-09T14:27:19+0000 redacted  [info] internal version: 20.0.8.1
2021-04-09T14:27:19+0000 redacted  [info] updateURL: https://updates.nextcloud.com/updater_server/?version=20x0x8x1xxxstablexx2021-02-24T19%3A11%3A39%2B00%3A00+1ff83111a63e795079d668bb15ffa84c1024596dx7x3x27
2021-04-09T14:27:19+0000 redacted  [info] getUpdateServerResponse response: Array
(
    [version] => 21.0.1.1
    [versionstring] => Nextcloud 21.0.1
    [url] => https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
    [web] => https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=21.0.1
    [autoupdater] => 1
    [eol] => 0
    [signature] => redacted
)

2021-04-09T14:27:19+0000 redacted  [info] storage location: /var/www/redacted.domain.com/data/updater-redacted /downloads/
2021-04-09T14:27:19+0000 redacted  [info] end of verifyIntegrity()
2021-04-09T14:27:19+0000 redacted  [info] endStep("5")
2021-04-09T14:27:19+0000 redacted  [info] executeStep request for step "6"
2021-04-09T14:27:19+0000 redacted  [info] startStep("6")
2021-04-09T14:27:19+0000 redacted  [info] extractDownload()
2021-04-09T14:27:19+0000 redacted  [info] storage location: /var/www/redacted.domain.com/data/updater-redacted /downloads/
2021-04-09T14:27:22+0000 redacted  [info] end of extractDownload()
2021-04-09T14:27:22+0000 redacted  [info] endStep("6")
2021-04-09T14:27:22+0000 redacted  [info] executeStep request for step "7"
2021-04-09T14:27:22+0000 redacted  [info] startStep("7")
2021-04-09T14:27:22+0000 redacted  [info] setMaintenanceMode("true")
2021-04-09T14:27:22+0000 redacted  [info] configFileName /var/www/redacted.domain.com/html/updater/../config/config.php
2021-04-09T14:27:22+0000 redacted  [info] end of setMaintenanceMode()
2021-04-09T14:27:22+0000 redacted  [info] endStep("7")
2021-04-09T14:27:22+0000 redacted  [info] executeStep request for step "8"
2021-04-09T14:27:22+0000 redacted  [info] startStep("8")
2021-04-09T14:27:22+0000 redacted  [info] replaceEntryPoints()
2021-04-09T14:27:22+0000 redacted  [info] replace index.php
2021-04-09T14:27:22+0000 redacted  [info] replace status.php
2021-04-09T14:27:22+0000 redacted  [info] replace remote.php
2021-04-09T14:27:22+0000 redacted  [info] replace public.php
2021-04-09T14:27:22+0000 redacted  [info] replace ocs/v1.php
2021-04-09T14:27:22+0000 redacted  [info] replace ocs/v2.php
2021-04-09T14:27:22+0000 redacted  [info] end of replaceEntryPoints()
2021-04-09T14:27:22+0000 redacted  [info] endStep("8")
2021-04-09T14:27:22+0000 redacted  [info] executeStep request for step "9"
2021-04-09T14:27:22+0000 redacted  [info] startStep("9")
2021-04-09T14:27:22+0000 redacted  [info] deleteOldFiles()
2021-04-09T14:27:23+0000 redacted  [info] config sample exists
2021-04-09T14:27:23+0000 redacted  [info] themes README exists
2021-04-09T14:27:23+0000 redacted  [info] end of deleteOldFiles()
2021-04-09T14:27:23+0000 redacted  [info] endStep("9")
2021-04-09T14:27:23+0000 redacted  [info] executeStep request for step "10"
2021-04-09T14:27:23+0000 redacted  [info] startStep("10")
2021-04-09T14:27:23+0000 redacted  [info] moveNewVersionInPlace()
2021-04-09T14:27:23+0000 redacted  [info] storage location: /var/www/redacted.domain.com/data/updater-redacted/downloads/nextcloud/
2021-04-09T14:27:23+0000 redacted  [info] end of moveNewVersionInPlace()
2021-04-09T14:27:23+0000 redacted  [info] endStep("10")
2021-04-09T14:27:23+0000 redacted  [info] executeStep request for step "12"
2021-04-09T14:27:23+0000 redacted  [info] startStep("12")
2021-04-09T14:27:23+0000 redacted  [info] finalize()
2021-04-09T14:27:23+0000 redacted  [info] storage location: /var/www/redacted.domain.com/data/updater-redacted/downloads/nextcloud/
2021-04-09T14:27:23+0000 redacted  [info] call opcache_reset()
2021-04-09T14:27:23+0000 redacted  [info] end of finalize()
2021-04-09T14:27:23+0000 redacted  [info] endStep("12")
2021-04-09T14:27:23+0000 redacted  [info] update of code successful.
2021-04-09T14:29:28+0000 redacted  [info] maintenance mode is disabled - return code: 137
```

**Comment by caugner** [comment] 2021-04-09 16:35
@hubertbanas That's odd, it seems that Nextcloud skipped step 11, which disables the maintenance mode.

```
2021-04-09T14:27:23+0000 redacted  [info] endStep("10")
2021-04-09T14:27:23+0000 redacted  [info] executeStep request for step "12"
2021-04-09T14:27:23+0000 redacted  [info] startStep("12")
```

Could you try disabling the maintenance mode manually by setting `maintenance` to `false` in your `config/config.php`?

(If this doesn't resolve the issue, better set it back to `true` afterwards.)

**Comment by hubertbanas** [comment] 2021-04-09 16:59
After setting to ```false``` the web shows Updater
```
Nextcloud will be updated to version 21.0.1
The following apps will be updated:
list of app here

These incompatible apps will be disabled:
list of app here

Start update
```

occ is still not working
```
sudo -u www-data php occ
Killed
```

**Comment by caugner** [comment] 2021-04-09 17:52
@rullzer Given that the update to 21.0.1 broke the Nextcloud instance for at least 4 users already (on top of the other two issues), would it be possible to have the stable channel point back to 20.0.9?

/cc @AndyScherzinger

**Comment by caugner** [comment] 2021-04-09 18:00
@hubertbanas @fubz What operating system and version of PHP are you running?

**Comment by Fuzzillogic** [comment] 2021-04-09 18:04
@caugner: Ubuntu 20.04.2 LTS here. (same issue) 

```
$ php --version
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
```

**Comment by qinohe** [comment] 2021-04-09 18:18
Though, my Nextcloud instance is running & client is working I cannot add the missing tables using OCC.
It also seems the installer missed no steps like hubertbanas shows, maintainance is off.
Used updater: web.
I have more issues(minor) which shouldn't pollute up this thread.

Debian                                  - Buster 10.9
PHP Apache Version            - Apache/2.4.38 (Debian)
Apache PHP version            - 7.4.16
MariaDB                               - Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

```
$ php -v
PHP 8.0.3 (cli) (built: Mar  5 2021 08:38:30) ( NTS )
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies

**Comment by hubertbanas** [comment] 2021-04-09 18:20
@caugner 

```
Debian 10.9
PHP 7.3.27-1~deb10u1
mariadb-server-10.3
nginx 1.14.2-2+deb10u3
Linux Kernel 4.19.0-16-amd64
```

**Comment by caugner** [comment] 2021-04-09 18:25
> Disabling the cache helped in my case as well.

@Fuzzillogic Do you mean disabling OPcache?

If so, a problem could be that upgrading via the commandline (i.e. `occ`) only resets the OPcache for the CLI context and most likely keeps the OPcache of the webserver php untouched (i.e. outdated). On the other hand, the [corresponding code](https://github.com/nextcloud/updater/blame/e490062a97bfebdf7f9fe90c4d6dbb19a1da0cac/lib/Updater.php#L997-L999) in the Updater is rather old and it would be surprising if this caused problems only now.

> $ php -v
> PHP 8.0.3 (cli)

@qinohe Please try to run `occ` with PHP 7.4, as PHP 8.0 is not yet officially supported, see [System requirements](https://docs.nextcloud.com/server/21/admin_manual/installation/system_requirements.html).

**Comment by Fuzzillogic** [comment] 2021-04-09 18:31
@caugner no, removing `'memcache.local' => '\OC\Memcache\APCu'` from my config, as per #26184.

**Comment by qinohe** [comment] 2021-04-09 18:34
@caugner , no it gets killed too using PHP 7.4.16 (cli)
BTW. using PHP8 for CLI (only) didn't give me anymore trouble, everything works, so you know ;-)

**Comment by caugner** [comment] 2021-04-09 18:38
@hubertbanas @qinohe Do you have Memcache or another cache configured like @Fuzzillogic (good catch!)?

- If yes, could you try if disabling the cache temporarily solves the issue for you, too?
- If not, could you post your *redacted* (see below) `config.php`?

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Comment by qinohe** [comment] 2021-04-09 18:46
I'm using "memcache.local' => '\\OC\\Memcache\\APCu"
And yes disabling it did indeed add the tables, prove:
```Check indices of the share table.
Check indices of the filecache table.
Adding additional size index to the filecache table, this can take some time...
Filecache table updated successfully.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
```

I can safely enable the cache again?

**Comment by BkSouX** [comment] 2021-04-09 18:47
I also have an issue updating. 
Now, when I try to use occ, my server (helios4) blocks and I have to reboot it to get accessed to it. 
PHP 7.3.

**Comment by caugner** [comment] 2021-04-09 18:50
@qinohe Thanks! Enabling the cache again should be safe.

> `Check indices of the filecache table.`

I'm wondering whether Nextcloud iterates over all rows of the filecache table and either checks if they exist in the cache or stores them there. 

@BkSouX Please check if you have `memcache.local` set in your config, see [my comment above](https://github.com/nextcloud/server/issues/26472#issuecomment-816882594).

**Comment by qinohe** [comment] 2021-04-09 18:55
Thanks for the service @caugner & @Fuzzillogic  for finding the culprit.

@caugner, I don't know and since it's after the fact I'm probably unable to check it!

**Comment by Fuzzillogic** [comment] 2021-04-09 19:01
@qinohe and @caugner If I reenable the cache, the problem is back. That is: in another shell I monitor with top, and then even a mere `sudo -u www-data ./occ` (so no options) makes php takes gigabytes within seconds. Which is, given this is a old AMD E-450 machine, quite an accomplishment :) Before things ran out of control (or into OOM, specifically) I aborted with Ctrl+c.

**Comment by qinohe** [comment] 2021-04-09 19:06
@caugner, I did read the cache and it seems to have epoch times atached, though it's to much (for me) to make soup of it ;-)
I could mail you the file.

@Fuzzillogic, not what I'm seeing here with my php version, see previous posts.

**Comment by caugner** [comment] 2021-04-09 19:12
@qinohe and @Fuzzillogic Let's continue the conversation about the Memcache/APCu-related issue in #26154 and/or #26184.

Same for @quizilkend, @hubertbanas and @BkSouX, if you also use Memcache/APCu (`'memcache.local' => '\OC\Memcache\APCu'`).

**Comment by kesselb** [comment] 2021-04-09 19:22
Closing in favour of https://github.com/nextcloud/server/issues/26184

**Closed by kesselb** 2021-04-09 19:22 UTC
Labels: 0. Needs triage, bug

**Comment by b-pfl** [comment] 2021-04-13 02:21
@kesselb One open issue remains: Given the regular upgrade path (https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html), NC should first upgrade from 20.0.8 to 20.0.9 and THEN maybe to 21.x. So why is the upgrade skipping the last point release. 
This is an essential bug, especially as long as it is not clear whether NC21 still supports MySQL 5.7 and if no proper checks for this are implemented.

**Comment by kesselb** [comment] 2021-04-13 08:05
> NC should first upgrade from 20.0.8 to 20.0.9 and THEN maybe to 21.x. So why is the upgrade skipping the last point release.

https://github.com/nextcloud/server/issues/18485


> This is an essential bug, especially as long as it is not clear whether NC21 still supports MySQL 5.7 and if no proper checks for this are implemented.

Technically yes. We do not support it.
