### ISSUE TITLE
Accessibility 1.2.0 incomplete translation

### ISSUE THREAD

**Issue by TP75** [nextcloud/server#17555] opened 2019-10-15 21:18 UTC
### Steps to reproduce

**Accessibility 1.2.0 App** enabled

NC GUI user Personal info settings
1. select & ack. e.g. 'German (Förmlich/Sie)' as Language for the GUI and use this GUI somehow
2. afterwards select e.g. '**English (British-English)**' as Language for the GUI
3. ack. the change with your password if requested

### Expected behaviour
The NC GUI should in completeness honor major the Language and minor the Locale as selected by user Personal info settings.

Langugae 'English (US)' seems to be complete.

> #### Accessibility
>
> Universal access is very important to us. We follow web standards and check to make everything usable also without mouse, and assistive software such as screenreaders. We aim to be compliant with the Web Content Accessibility Guidelines 2.1 on AA level, with the high contrast theme even on AAA level.
>
> If you find any issues, don’t hesitate to report them on our issue tracker. And if you want to get involved, come join our design team!

### Actual behaviour

Mixing text wrongly and incomplete translation.

The behaviour applies to all three Language profiles 
1. 'English (British-English)' 
1. 'Deutsch (Förmlich: Sie)'
1. 'Deutsch (Persönlich: Du)'

#### Mixed text example

Please note independently from the actual Language **all three Language profiles produce the same text** as shown here.  Please find an excerpt of the incomplete translation text for the view 'Barrierefreiheit' i.e. 'Accessibility' below:

> #### Barrierefreiheit
>
> Universal access is very important to us. We follow web standards and check to make everything usable also without mouse, and assistive software such as screenreaders. We aim to be compliant with the **Richtlinien für die Barrierefreiheit von Webinhalten 2.1** on AA level, with the high contrast theme even on AAA level.
>
> If you find any issues, don’t hesitate to report them on **Unser Problemverfolgungssystem**. And if you want to get involved, come join **Unser Design-Team!**

### Server configuration

same as in #17544 and issues may relate

**Comment by kesselb** [comment] 2019-10-16 07:01
Duplicate of https://github.com/nextcloud/server/issues/14607. Will be fixed with one the next releases.

**Closed by kesselb** 2019-10-16 07:01 UTC
Labels: 0. Needs triage, bug
