### ISSUE TITLE
Please remove default video-player or add default audio-player

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#22985] opened 2020-09-21 08:35 UTC
In Nextcloud is a integrated "video player" from Björn Korella.
But there is no integrated "audio player" in Nextcloud.

Please remove video-player or add audio-player.
Why is there a default video player but no default audio player?

**Comment by kesselb** [comment] 2020-09-21 08:46
Duplicate of https://github.com/nextcloud/server/issues/21805

**Closed** 2020-09-21 09:28 UTC
Labels: 0. Needs triage, enhancement
