### ISSUE TITLE
Nextcloud 15. Shared file's version not available.

### ISSUE THREAD

**Issue by freezxp** [nextcloud/server#13173] opened 2018-12-20 11:05 UTC
### Steps to reproduce
1.Open file details on a shared file.
2.Check the versions tab.
3.No available versions.

### Expected behaviour
Should be able to see older version list for that particular files.

### Actual behaviour
 Only owner of the files is able to view the older versions.

### Server configuration
Docker Swarm - Container
Images: Docker Hub:  nextcloud:latest

**Comment by iprok** [comment] 2019-01-20 20:57
Fully confirm the issue with nextcloud 15.0.2. Very disappointed. :(

**Comment by danielkesselberg** [comment] 2019-01-20 21:17
Thank you for reporting this issue :+1: 

I will need your browser console log to investigate this issue. Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread,

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by iprok** [comment] 2019-01-20 22:01
Just one record:
XHR finished loading: PROPFIND "https://cloud.mydomain.com/thecloud/remote.php/dav/versions/iprok/versions/16232081".

Nothing interesting also in nextcloud server logs. I can only see that the request was answered with http code 207.

**Comment by iprok** [comment] 2019-01-20 22:03
If you can't repeat problem on your side, I can give you access to my nextcloud installation and share some folder to you and you will see the problem.

**Comment by iprok** [comment] 2019-01-20 22:09
I have also got the content of the answer to PROPFIND request:
```

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/thecloud/remote.php/dav/versions/iprok/versions/16232081/</d:href><d:propstat><d:prop><d:getcontentlength/><d:getcontenttype/><d:getlastmodified/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
```

But the file surely exists. Can be downloaded or edited (it's txt file).

**Comment by quentinDupont** [comment] 2019-01-23 14:37
Same issue here : https://github.com/nextcloud/server/issues/13750

**Comment by MorrisJobke** [comment] 2019-01-25 10:13
Currently versions are bound to the owner of the file - we are about overhaul this completely to allow shared versions. This has some side effect, because for example you don't want to expose versions from before the share was created and stuff like that.

This is currently a limitation of how versions are implemented. For the "versions 2.0" overview ticket please check out #9445.

Sorry for the bad news here - we are looking into improving this. As of now I will close this ticket here and refer to #9445, because we need this to accomplish shared versions.

**Closed by MorrisJobke** 2019-01-25 10:13 UTC
Labels: 0. Needs triage, bug

**Comment by MorrisJobke** [comment] 2019-01-25 13:31
Sorry - mixed this up. See #13750: it's a regression from #11778.
