### ISSUE TITLE
App Login Error: Undefined offset: 3

### ISSUE THREAD

**Issue by hysci** [nextcloud/server#24087] opened 2020-11-13 04:01 UTC
Everything is OK to login to nextcloud 20.01 (latest release) with a web browser (firefox, chrome). However, when I use nextcloud clients (windows 2.5.3 and 3.0.3), the following errors are caught.
`
Error: Undefined offset: 3 at /share/CACHEDEV1_DATA/Web/nextcloud/lib/private/legacy/OC_Helper.php#548/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/legacy/OC_Helper.php - line 548:OC\Log\ErrorHandler::onError(8, "Undefined offset: 3", "/share/CACH ... p", 548, { path: "/", ... }})/share/CACHEDEV1_DATA/Web/nextcloud/apps/settings/lib/Settings/Personal/PersonalInfo.php - line 108:OC_Helper::getStorageInfo("/")/share/CACHEDEV1_DATA/Web/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 141:OCA\Settings\Settings\Personal\PersonalInfo->getForm()/share/CACHEDEV1_DATA/Web/nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php - line 77:OCA\Settings\Controller\PersonalSettingsController->formatSettings({ 10: [ OCA\ ... ]})/share/CACHEDEV1_DATA/Web/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 152:OCA\Settings\Controller\PersonalSettingsController->getSettings("personal-info")/share/CACHEDEV1_DATA/Web/nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php - line 68:OCA\Settings\Controller\PersonalSettingsController->getIndexResponse("personal", "personal-info")/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:OCA\Settings\Controller\PersonalSettingsController->index("personal-info")/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "index")/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/App.php - line 152:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "index")/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/Route/Router.php - line 308:OC\AppFramework\App::main("OCA\\Settin ... r", "index", OC\AppFramew ... {}, { section: " ... "})/share/CACHEDEV1_DATA/Web/nextcloud/lib/base.php - line 1009:OC\Route\Router->match("/settings/user")/share/CACHEDEV1_DATA/Web/nextcloud/index.php - line 37:OC::handleRequest()`

### Steps to reproduce
1. download nextcloud v3.0.1 zip file on Ubuntu 20.04
2. unzip, chown -R to httpdusr
3. normal setup
4. install cloud clients (windows 2.5.3 and 3.0.3) on Windows 10
5. login with windows app

### Expected behaviour
There should be no error in the nextcloud server

### Actual behaviour
Logs are attathed above

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
PHP 7.3

**Database:**
MariaDB

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
20.01

**Updated from an older Nextcloud/ownCloud or fresh install:**
Clean installation from 20.01

**Where did you install Nextcloud from:**
Unzip 20.01 zip file directly

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP is enabled, but I also tried native accounts, it is the same story.

### Client configuration
**Browser:**
Both Chrome 86.0.4240.183 and Firefox 81.0 for windows 10 are tried

**Operating system:**
Windows 10, 1919

### Logs
See above

**Comment by kesselb** [comment] 2020-11-13 08:51
Duplicate of https://github.com/nextcloud/server/issues/23595

**Closed by kesselb** 2020-11-13 08:51 UTC
Labels: 0. Needs triage, bug
