### ISSUE TITLE
Files: In "Move or copy" dialogue button labels are not updated when creating new folder

### ISSUE THREAD

**Issue by mikini** [nextcloud/server#26317] opened 2021-03-26 12:30 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Select or hover over file(s) in "files" app (/apps/files)
2. Right click, choose "Move or copy"
3. In the "Choose target folder" dialogue, navigate to a subfolder (fx. "Documents")
4. Notice the lower right white/blue buttons changes label to "Copy/Move to <new location>" (fx. "Copy/Move to Documents")
5. Click "+" button to create a new folder
6. Write the name of new folder in popup (fx. "test")
7. Click right pointing arrow "->" to confirm folder creation (<enter> is not accepted as confirmation)
8. "Choose target folder" dialogue will change to show the path and contents of the new folder
9. Notice the lower right white/blue buttons **do not** change label to "Copy/Move to <new folder>" (fx. "Copy/Move to test"), but remains showing "Copy/Move to <parent folder>" (fx. "Copy/Move to Documents")
10. Click the lower right blue button "Move to <parent folder>" (fx. "Move to Documents")
11. The files are effectively moved to the new folder, not the parent folder as the button label indicates

### Expected behaviour
The labels of the lower right white/blue buttons should change according to the actual path of the "Choose target folder" dialogue after creating and navigating into a new folder to indicate where the files are effectively moved.

### Actual behaviour
The labels of the lower right white/blue buttons remains showing the name of the parent folder of the created folder and does not indicate where the files are effectively copied/moved.

Screenshot of "Choose target folder" dialogue showing location "Documents/test" after creating "test" from within "Documents", buttons still being labelled "Copy/Move to Documents":
![Screenshot from 2021-03-26 12-17-45](https://user-images.githubusercontent.com/1330166/112634174-8bd26180-8e3a-11eb-8f79-81841942acc5.png)

### Server configuration

**Operating system:** Debian 10 ([Syncloud 21.01](https://syncloud.org/))
```
root@syncloud:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@syncloud:~# 
```

**Web server:** nginx 1.15.12
```
root@syncloud:~# /snap/platform/210114627/nginx/sbin/nginx -v
nginx version: nginx/1.15.12
root@syncloud:~# 
```
**Database:** postgres 10.10
```
root@syncloud:~# /snap/nextcloud/210214199/postgresql/bin/postgres --version
postgres (PostgreSQL) 10.10
root@syncloud:~#
```
**PHP version:** 7.4.12 
```
root@syncloud:~# LD_LIBRARY_PATH=/snap/nextcloud/210214199/php/lib /snap/nextcloud/210214199/php/bin/php --version
PHP 7.4.12 (cli) (built: Nov  9 2020 07:46:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
root@syncloud:~# 
```
**Nextcloud version:** Nextcloud 20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh Syncloud 21.01

**Where did you install Nextcloud from:** Syncloud 21.01

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Iroot@syncloud:~# snap run nextcloud.occ app:list
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - cookbook: 0.8.3
  - dashboard: 7.0.0
  - dav: 1.16.2
  - ehr: 0.1.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - gpxpod: 4.2.7
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - phonetrack: 0.6.7
  - photos: 1.2.3
  - previewgenerator: 3.1.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
root@syncloud:~# 
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
root@syncloud:~# snap run nextcloud.occ config:list
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "log_type": "syslog",
        "logfile": "\/var\/snap\/nextcloud\/common\/log\/nextcloud.log",
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "dbtype": "pgsql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": "2",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "preview_max_x": "1080",
        "preview_max_y": "1920"
    },
    "apps": {
        "accessibility": {
            "installed_version": "1.6.0",
            "types": "",
            "enabled": "yes"
        },
        "activity": {
            "installed_version": "2.13.4",
            "types": "filesystem",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "3"
        },
        "cloud_federation_api": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "comments": {
            "installed_version": "1.10.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contactsinteraction": {
            "installed_version": "1.1.0",
            "types": "dav",
            "enabled": "yes"
        },
        "cookbook": {
            "installed_version": "0.8.3",
            "types": "",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1614697559.772",
            "lastupdatedat": "1614697559.8259",
            "vendor": "nextcloud",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "backgroundjobs_mode": "cron",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "lastcron": "1616760069"
        },
        "dashboard": {
            "installed_version": "7.0.0",
            "types": "",
            "enabled": "yes"
        },
        "dav": {
            "installed_version": "1.16.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "ehr": {
            "installed_version": "0.1.2",
            "types": "",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "1.10.2",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.10.1",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.15.0",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_pdfviewer": {
            "installed_version": "2.0.1",
            "types": "",
            "enabled": "yes"
        },
        "files_rightclick": {
            "installed_version": "0.17.0",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.12.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "1.10.1",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.13.0",
            "types": "filesystem,dav",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "1.9.0",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "2.9.0",
            "types": "logging",
            "enabled": "yes"
        },
        "gpxpod": {
            "installed_version": "4.2.7",
            "types": "",
            "enabled": "yes",
            "reset304": "1",
            "resetPics404": "1"
        },
        "logreader": {
            "installed_version": "2.5.0",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.8.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "maps": {
            "installed_version": "0.1.8",
            "types": "filesystem",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "installed_version": "1.9.0",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notifications": {
            "installed_version": "2.8.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.8.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.10.1",
            "types": "authentication",
            "enabled": "yes"
        },
        "phonetrack": {
            "installed_version": "0.6.7",
            "types": "",
            "enabled": "yes"
        },
        "photos": {
            "installed_version": "1.2.3",
            "types": "",
            "enabled": "yes"
        },
        "previewgenerator": {
            "installed_version": "3.1.1",
            "squareSizes": "32 64 256 1024 1920",
            "widthSizes": "64 128 1024 1080 2030",
            "heightSizes": "64 256 1024 1080 1920",
            "types": "filesystem",
            "enabled": "yes"
        },
        "privacy": {
            "installed_version": "1.4.0",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "1.10.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "recommendations": {
            "installed_version": "0.8.0",
            "types": "",
            "enabled": "yes"
        },
        "serverinfo": {
            "installed_version": "1.10.0",
            "types": "",
            "enabled": "yes"
        },
        "settings": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.10.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "support": {
            "installed_version": "1.3.0",
            "types": "session",
            "enabled": "yes"
        },
        "survey_client": {
            "installed_version": "1.8.0",
            "types": "",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "1.10.0",
            "types": "logging",
            "enabled": "yes"
        },
        "text": {
            "installed_version": "3.1.0",
            "types": "dav",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "1.11.0",
            "types": "logging",
            "enabled": "yes"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.9.0",
            "types": "",
            "enabled": "yes"
        },
        "user_ldap": {
            "installed_version": "1.10.2",
            "types": "authentication",
            "enabled": "yes",
            "s02ldap_configuration_active": "0",
            "s02_lastChange": "1614697883",
            "s01ldap_configuration_active": "1",
            "s01ldap_host": "ldap:\/\/localhost",
            "s01ldap_port": "389",
            "s01ldap_dn": "dc=syncloud,dc=org",
            "s01ldap_base": "dc=syncloud,dc=org",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01has_memberof_filter_support": "0",
            "s01ldap_login_filter": "(&(|(objectclass=inetOrgPerson))(uid=%uid))",
            "s01ldap_userlist_filter": "(|(objectclass=inetOrgPerson))",
            "s01ldap_userfilter_objectclass": "inetOrgPerson",
            "s01ldap_base_users": "ou=users,dc=syncloud,dc=org",
            "s01ldap_display_name": "cn",
            "s01ldap_expert_username_attr": "cn",
            "s01ldap_groupfilter_objectclass": "posixGroup",
            "s01ldap_group_display_name": "cn",
            "s01ldap_base_groups": "ou=groups,dc=syncloud,dc=org",
            "s01ldap_group_filter": "(&(|(objectclass=posixGroup)))",
            "s01ldap_groupfilter_groups": "syncloud",
            "s01ldap_group_member_assoc_attribute": "memberUid",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "1",
            "s01_lastChange": "1614947845",
            "s01ldap_cache_ttl": "600",
            "background_sync_prefix": "s01",
            "background_sync_offset": "0",
            "background_sync_interval": "1800",
            "s01ldap_email_attr": "mail"
        },
        "user_status": {
            "installed_version": "1.0.1",
            "types": "",
            "enabled": "yes"
        },
        "viewer": {
            "installed_version": "1.4.0",
            "types": "",
            "enabled": "yes"
        },
        "weather_status": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "workflowengine": {
            "installed_version": "2.2.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}
root@syncloud:~# 
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** not in storage, but TLS certificates are in place

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 86.0.1

**Operating system:** Ubuntu 20.04

**Comment by szaimen** [comment] 2021-07-02 10:12
Duplicate of https://github.com/nextcloud/server/issues/19718

**Closed by szaimen** 2021-07-02 10:12 UTC
Labels: 0. Needs triage, bug
