### ISSUE TITLE
"File not found" after login

### ISSUE THREAD

**Issue by fankijo** [nextcloud/server#13223] opened 2018-12-21 16:29 UTC
Hi,

when i log into my nextcloud it says "File not found". I dont miss any files, but would like to know what this message wants to say to me. In my logs i cant find anything saying something like that. My nextcloud instance is completely new installed and works without problems. 

### Server configuration

**Operating system**: Ubuntu Server 16.04.05 LTS

**Web server:** Apache2

**Database:** mysql

**PHP version:** 7

**Nextcloud version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh installed

**Comment by skjnldsv** [comment] 2019-06-04 09:07
Hi, were you opening your nextcloud with a bookmark? It's most likely that the url you were opening had a file/folder indicator in it like `dir=/` or `fileid=437906`. :)
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-04 09:07 UTC
Labels: 0. Needs triage, bug
