### ISSUE TITLE
[Bug]: Can't update to 28.0.0 since migration 28000Date20230906104802 fails

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/server#42173] opened 2023-12-12 12:51 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After update to 28.0.0 and while running `occ upgrade`, we get this output:

```
Setting log level to debug
Updating database schema
Exception: Database error when running migration 28000Date20230906104802 for app core
Index name "nid" for table "oc_social_3_stream" collides with the constraint on table "oc_social_3_cache_actor".
Update failed
Maintenance mode is kept active
Resetting log level
```

### Steps to reproduce

1. Update to 28.0.0
2. Run `occ upgrade`

### Expected behavior

The upgrade should succeed.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jurgenhaas** [comment] 2023-12-12 13:08
As a workaround and since I had not used social a lot other than for testing, I disabled the social app - which didn't resolve the problem yet - so I also deleted all the related tables:

```
drop table oc_social_3_action;
drop table oc_social_3_actor;
drop table oc_social_3_cache_actor;
drop table oc_social_3_cache_doc;
drop table oc_social_3_client;
drop table oc_social_3_follow;
drop table oc_social_3_hashtag;
drop table oc_social_3_instance;
drop table oc_social_3_req_queue;
drop table oc_social_3_stream;
drop table oc_social_3_stream_act;
drop table oc_social_3_stream_dest;
drop table oc_social_3_stream_queue;
drop table oc_social_3_stream_tag;
```

Now I can at least finalize the update and get back to my nextcloud instance.

**Comment by joshtrichards** [comment] 2023-12-12 21:51
That migration doesn't have anything to do with the `social` app though so that's.... weird. :thinking: 

https://github.com/nextcloud/server/blob/c734a18ee83a3537193192f6b97d78575611ba9e/core/Migrations/Version28000Date20230906104802.php#L38

Also, those table names for the `social` app don't look quite right: I'd expect `oc_social_action` not `oc_social_3_action`.

https://github.com/nextcloud/social/blob/master/lib/Migration/Version1000Date20230217000002.php

It also looks like the latest Social version (0.6.1) in the appstore was released back in June so I'm skeptical it's really NC28 ready.

**Comment by joshtrichards** [comment] 2023-12-12 22:06
Also similar to #41253 reported earlier with the beta.

**Comment by joshtrichards** [comment] 2023-12-12 22:12
Duplicate of #41253 

Let's consolidate there.

**Closed by joshtrichards** 2023-12-12 22:12 UTC
Labels: bug, 0. Needs triage, feature: install and update, 28-feedback

**Comment by dewomser** [comment] 2023-12-13 11:13
I have dropped all
tables with  oc_social_3*
After that nextcloud installs and launch.
Funfact:  At Social App no config and toots are lost . It seems working.
