### ISSUE TITLE
Gallery shows wrong photos, different from thumbnails

### ISSUE THREAD

**Issue by carlorodrigues** [nextcloud/server#20866] opened 2020-05-07 19:19 UTC
The problem happens with files from different folders but with the same name . The thumbnails are shown correctly, but, when clicked, show the wrong picture.

Steps to reproduce:

Clean install of nextcloud-18.0.4

Create the folowing structure:

Folder1/image.jpg
Folder2/image.jpg
[FolderN/image.jpg]

Multiple different images, in multiple different folders, but with the same filename.

Clean install of nextcloud 18.0.4.

1. Upload the pictures to nextcloud, or put them in your sync folder
2. Click Photos
3. Click on the second thumbnail. The first photo will appear.

Tested via desktop (Linux and Windows).

I also tried on  https://demo2.nextcloud.com, and the problem is the same.

I tried also with 3 pictures. Clicking on each thumbnail always shows the first picture.

**Comment by kesselb** [comment] 2020-05-07 19:42
cc @skjnldsv

**Comment by skjnldsv** [comment] 2020-05-10 12:35
Duplicate of https://github.com/nextcloud/viewer/issues/484

**Closed by skjnldsv** 2020-05-10 12:35 UTC
Labels: 0. Needs triage, bug
