### ISSUE TITLE
[Bug]: Side menu is almost unusable on small resolution

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/server#34777] opened 2022-10-24 17:18 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My laptop screen has this screen resolution : 1366x768px

Displaying the side menu of a file with a preview on firefox maximized (but not full screen) : 

![image](https://user-images.githubusercontent.com/6248852/197585193-f0c04f2a-098d-4ba0-90bc-faae2cd19cdc.png)

It's very difficult to use the share drop-down list and to access internal link and other informations in side menu in these conditions.

### Steps to reproduce

1. Reduce the height of the browser window or use an old screen
2. Display the side menu of a file with a preview thumbnail
3. Try to share it or to get the internal link

### Expected behavior

UI should be responsive and should propose to minimize/toggle the thumbnail preview or detecting the height of the div, toggle it itself.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "merome.net",
            "cloud.merome.net",
            "192.168.1.100"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/merome.net\/owncloud",
        "dbtype": "mysql",
        "version": "25.0.0.18",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "calendar",
            "onlyoffice",
            "spreed",
            "files_mindmap",
            "files_texteditor",
            "external",
            "deck"
        ],
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "has_rebuilt_cache": true,
        "app.mail.verify-tls-peer": false,
        "default_phone_region": "FR",
        "debut": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.14.0
  - forms: 3.0.0
  - integration_mastodon: 1.0.3
  - integration_twitter: 1.0.3
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.3
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - onlyoffice: 7.6.6
  - password_policy: 1.15.0
  - photos: 2.0.0
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - snappymail: 2.19.2
  - spreed: 15.0.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.2.0
  - deck: 1.7.1
  - duplicatefinder: 0.0.15
  - emlviewer: 1.0.2
  - encryption
  - extract: 1.3.2
  - files_markdown: 2.3.6
  - passwords: 2022.10.10
  - tables: 0.2.0
  - twofactor_totp
  - user_ldap
  - workspace
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Not relevant
```

**Comment by tmllull** [comment] 2022-10-26 09:09
Same with other sections:

Calendar: the input text for the name is "overflow" behind the limits of the calendar.
![imagen](https://user-images.githubusercontent.com/5560652/197984457-09599a58-4700-453e-9655-a5be87979c59.png)

Contacts: the limit space list is "ovreflow" behind the settings button.
![imagen](https://user-images.githubusercontent.com/5560652/197984953-d6695a07-21fa-4978-a2a7-78543f26f4d0.png)

This is very frustrating...

**Comment by PVince81** [comment] 2022-10-28 12:43
it was already difficult before, now with the extra pixels from the border it got worse.

for the files sidebar the issue is mostly when there's a thumbnail, maybe that one should reduce itself further ?

@jancborchardt

**Comment by szaimen** [comment] 2022-11-08 18:06
Needs:
- [ ] backport to vue 7
- [ ] new release of vue 7
- [ ] merge of new vue 7 in master
- [ ] backport of new vue 7 to stable25

**Comment by jancborchardt** [comment] 2022-11-15 19:21
Just to be clear @szaimen, the fix is to make the whole height of the sidebar scrollable right? I think that’s good :)

**Comment by szaimen** [comment] 2022-11-15 19:29
> Just to be clear @szaimen, the fix is to make the whole height of the sidebar scrollable right? I think that’s good :)

Yep and thanks :)

**Comment by szaimen** [comment] 2022-11-15 19:35
Reopening for the last missing step

**Comment by PVince81** [comment] 2022-12-15 08:15
@skjnldsv can you help here ?

**Comment by skjnldsv** [comment] 2022-12-15 08:38
Yep

**Comment by szaimen** [comment] 2022-12-20 16:48
Ping @skjnldsv ? :)

**Comment by szaimen** [comment] 2022-12-20 16:52
This has become more urgent now that vue 7.2.0 was merged into stable25. Otherwise we would need to revert vue 7.2.0 again to not risk re-introducing this regression in 25.0.3

**Comment by PVince81** [comment] 2023-01-03 09:50
@Pytal please have a look, this is also an accessibility topic and is blocking further accessibility improvements in nextcloud-vue as we can't update the library further (see https://github.com/nextcloud/server/pull/35877)

fyi @AndyScherzinger

**Comment by skjnldsv** [comment] 2023-01-03 16:50
I don't remember what the issue was, but [with my comment above](https://github.com/nextcloud/server/issues/34777#issuecomment-1343949383)

> Better fix proposal, use compact mode on low-height screen resolutions.

There is no need for any vue update.
The only fix necessary is on server:
https://github.com/nextcloud/server/blob/628b0d8fc43249e9116421133eda7ff6be72a706/apps/files/src/views/Sidebar.vue#L234

Just add one screen height check here

**Comment by Cwpute** [comment] 2023-01-03 19:32
I can only assume my problem is also one of screen resolution as i do have a similar 1366x768 screen. My gripes although are against the file explorer drop-down menu attached to the three-dots icon on each file: 
![firefox_9nrezsBGfv](https://user-images.githubusercontent.com/80604512/210427762-efaa6fd7-99ed-45ec-89d2-904c7c3cf31a.png)
I've scrolled as much as i could but as you cna see the drop-down menu still isn't visible in its entirety. Moreover you have to scroll in advance as each click out of that drop-down menu makes it disapear. The name of numerous options also copiously overflow the size of the menu.

**Comment by szaimen** [comment] 2023-01-03 19:33
> My gripes although are against the file explorer drop-down menu attached to the three-dots icon on each file:

this is a different issue.

**Comment by Cwpute** [comment] 2023-01-03 19:50
> this is a different issue.

Fair enough; i've created a new issue for this visual bug here: https://github.com/nextcloud/server/issues/35971

**Comment by szaimen** [comment] 2023-01-03 23:18
WIP here: https://github.com/nextcloud/server/pull/35972. @skjnldsv please have a look!

**Comment by szaimen** [comment] 2023-01-04 11:48
Reopening to keep track of the backport

**Comment by szaimen** [comment] 2023-01-04 12:10
- https://github.com/nextcloud/server/pull/35983

**Closed** 2023-01-04 14:52 UTC
Labels: bug, 2. developing, high, regression, 25-feedback, ui-refresh-feedback
