### ISSUE TITLE
remove duplicates from activity stream

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/server#12360] opened 2018-11-08 17:55 UTC
### Steps to reproduce
1. open and edit a note

### Expected behaviour
one entry per minute for the same event. something like "select distinct text, time"

### Actual behaviour
the same activity is repeated multiple times. 
Example
```
you have changed Note/test (Today 16:07)
you have changed Note/test (Today 16:07)
you have changed Note/test (Today 16:07)
you have changed Note/test (Today 16:08)
you have changed Note/test (Today 16:08)
```
### Server configuration
**Nextcloud version:** 14.0.3

**Comment by MorrisJobke** [comment] 2018-11-22 08:56
Duplicate of #11261

**Comment by MorrisJobke** [comment] 2018-11-22 08:56
See https://github.com/nextcloud/server/issues/11261#issuecomment-435829519

**Closed by MorrisJobke** 2018-11-22 08:56 UTC
Labels: enhancement, feature: activity and notification
