### ISSUE TITLE
Updater is asking for updater secret despite being called from admin backend

### ISSUE THREAD

**Issue by hannob** [nextcloud/server#17644] opened 2019-10-22 14:46 UTC
Whenever I run the Nextcloud updater I get asked to create and provide an udpater secret.

It's been poitned out to me by the nextcloud twitter account [1] (and also in a direct conversation with a NC developer) that this is not the intended behavior when I call the updater as an admin user from nextcloud and that this should happen automatically. However it does happen, so there seems to be some bug triggered in my installation.

I'm not sure where to start debugging. This is currently running NC 16.0.5 on a LAMP setup.

[1] https://twitter.com/Nextclouders/status/1165893363893178368

**Comment by kesselb** [comment] 2019-10-22 15:38
https://github.com/nextcloud/server/blob/b9bc2417e7a8dc81feb0abe20359bedaf864f790/apps/updatenotification/src/components/UpdateNotification.vue#L365-L384

Above code runs if you click the open updater button and leads to

https://github.com/nextcloud/server/blob/19f7cc9e9243c8ce4f3a5cba2c6fc286b1e32f38/apps/updatenotification/lib/Controller/AdminController.php#L89-L99

where a token is generated, written to your config.php and sent back as response.

At first I would check if the config.php is writeable by the webserver and check the xhr response from that happens on button click.

**Comment by hannob** [comment] 2019-10-24 10:13
Okay, from all I can tell this looks like a race condition. When I manually copy the password out of the xhr request it's all good. I assume the request directly afterwards will however still read the config before the new value has been written to it. Also I observed that on multiple tries occasionally the updater just opens without asking for a password.

Not sure how this can be fixed, but the whole "let's write a password to a file so we can directly afterwards use that to validate a request" seems like a strange concept to me. Why not handle this normally with a session?

**Comment by kesselb** [comment] 2019-10-24 16:11
>  Why not handle this normally with a session?

I'm not against it. Right now the updater does not use session. Updater and Nextcloud communicate via config.php only they are independet from each other.

**Comment by szaimen** [comment] 2021-05-27 09:30
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 09:30 UTC
Labels: 0. Needs triage, bug
