### ISSUE TITLE
settings/admin/logging shows endless waiting spinner

### ISSUE THREAD

**Issue by RailsViceRoads** [nextcloud/server#15761] opened 2019-05-27 19:39 UTC
### Steps to reproduce
1. Go to settings --> logging
2. Switch filter from Info to Warning
3. Refresh page.
**I'm not sure if you can reproduce this error. I have only one system. On that it is now impossible to show the logging list**

### Expected behaviour
Show filtered logging list

### Actual behaviour
Waiting spinner is shown. Also after logout and logon an after closing and reopening the web browser.

### Server configuration

**Web server:** Apache

**Database:** mysql Version: 5.6.19

**PHP version:** Version: 7.1.15

**Nextcloud version:** Version: 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 16.0.0

**Where did you install Nextcloud from:** tar-ball from nextcloud.com

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no Errors logged in .../data/nextcloud.log
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Unhandled promise rejection 
Object { readyState: 4, getResponseHeader: getResponseHeader(), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(), overrideMimeType: overrideMimeType(), statusCode: statusCode(), abort: abort(), state: state(), always: always(), then: then(), … }
es6.promise.js:110
```
</details>

**Comment by RailsViceRoads** [comment] 2019-05-27 19:50
**The whole Error in Browser Log:**

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:494
New search handler registered search.js:67:12
Unhandled promise rejection 
{…}
​abort: abort()
​​arguments: null
​​caller: null
​​length: 1
​​name: "abort"
​​prototype: Object { … }
​​<prototype>: function ()
​always: always()
​​arguments: null
​​caller: null
​​length: 0
​​name: "always"
​​prototype: Object { … }
​​<prototype>: function ()
​complete: add()
​​arguments: null
​​caller: null
​​length: 0
​​name: "add"
​​prototype: Object { … }
​​<prototype>: function ()
​done: add()
​​arguments: null
​​caller: null
​​length: 0
​​name: "add"
​​prototype: Object { … }
​​<prototype>: function ()
​error: add()
​​arguments: null
​​caller: null
​​length: 0
​​name: "add"
​​prototype: Object { … }
​​<prototype>: function ()
​fail: add()
​​arguments: null
​​caller: null
​​length: 0
​​name: "add"
​​prototype: Object { … }
​​<prototype>: function ()
​getAllResponseHeaders: getAllResponseHeaders()
​​arguments: null
​​caller: null
​​length: 0
​​name: "getAllResponseHeaders"
​​prototype: Object { … }
​​<prototype>: function ()
​getResponseHeader: getResponseHeader()
​​arguments: null
​​caller: null
​​length: 1
​​name: "getResponseHeader"
​​prototype: Object { … }
​​<prototype>: function ()
​overrideMimeType: overrideMimeType()
​​arguments: null
​​caller: null
​​length: 1
​​name: "overrideMimeType"
​​prototype: Object { … }
​​<prototype>: function ()
​pipe: pipe()
​​arguments: null
​​caller: null
​​length: 0
​​name: ""
​​prototype: Object { … }
​​<prototype>: function ()
​progress: add()
​​arguments: null
​​caller: null
​​length: 0
​​name: "add"
​​prototype: Object { … }
​​<prototype>: function ()
​promise: promise()
​​arguments: null
​​caller: null
​​length: 1
​​name: "promise"
​​prototype: Object { … }
​​<prototype>: function ()
​readyState: 4
​responseText: "<html>\n\n<head>\n<meta http-equiv=\"Content-Language\" content=\"de\">\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1252\">\n<meta name=\"GENERATOR\" content=\"Microsoft FrontPage 4.0\">\n<meta name=\"ProgId\" content=\"FrontPage.Editor.Document\">\n<title>Sehr geehrter Besucher</title>\n</head>\n\n<body>\n\n<p><font face=\"Arial, Helvetica, sans-serif\" size=\"2\"><img border=\"0\" src=\"http://www.domainfactory.de/pics/500.gif\" alt=\"500 - Interner Serverfehler\" width=\"198\" height=\"57\"></font></p>\n<p><font color=\"#B5D6B1\" face=\"Arial, Helvetica, sans-serif\" size=\"2\">_________________________________________________________</font><font face=\"Arial, Helvetica, sans-serif\" size=\"2\">&nbsp;<br>\n  </font></p>\n<table border=\"0\" cellspacing=\"0\" width=\"515\">\n  <tr> \n    <td width=\"511\"> \n      <p><font face=\"Arial, Helvetica, sans-serif\" size=\"3\">Sehr geehrter Besucher,</font></p>\n      <p><font face=\"Arial, Helvetica, sans-serif\" size=\"3\">leider ist ein Problem \n        aufgetreten. Die angeforderte Seite hat einen Script-Fehler verursacht.</font></p>\n      <p><font face=\"Arial, Helvetica, sans-serif\" size=\"3\">Haben Sie sich vielleicht \n        vertippt oder eine alte URL aufgerufen? Wenn nicht, informieren Sie bitte \n        den Webmaster dieser Homepage per Email. Um zu der vorherigen Seite zur�ckzukehren, \n        verwenden Sie bitte einfach die &quot;Zur�ck&quot; - Taste \n        Ihres Browsers. </font></p>\n      <p align=\"right\">&nbsp;\n    </td>\n  </tr>\n</table>\n<p align=\"left\"><font color=\"#B5D6B1\" face=\"Arial, Helvetica, sans-serif\" size=\"2\">_________________________________________________________</font></p>\n\n</body>\n\n</html>\n\n"
​setRequestHeader: setRequestHeader()
​​arguments: null
​​caller: null
​​length: 2
​​name: "setRequestHeader"
​​prototype: Object { … }
​​<prototype>: function ()
​state: state()
​​arguments: null
​​caller: null
​​length: 0
​​name: "state"
​​prototype: Object { … }
​​<prototype>: function ()
​status: 500
​statusCode: statusCode()
​​arguments: null
​​caller: null
​​length: 1
​​name: "statusCode"
​​prototype: Object { … }
​​<prototype>: function ()
​statusText: "Internal Server Error"
​success: add()
​​arguments: null
​​caller: null
​​length: 0
​​name: "add"
​​prototype: Object { … }
​​<prototype>: function ()
​then: then()
​​arguments: null
​​caller: null
​​length: 0
​​name: "then"
​​prototype: Object { … }
​​<prototype>: function ()
​<prototype>: {…}
​​__defineGetter__: function __defineGetter__()
​​__defineSetter__: function __defineSetter__()
​​__lookupGetter__: function __lookupGetter__()
​​__lookupSetter__: function __lookupSetter__()
​​__proto__: 
​​constructor: function Object()
​​hasOwnProperty: function hasOwnProperty()
​​isPrototypeOf: function isPrototypeOf()
​​propertyIsEnumerable: function propertyIsEnumerable()
​​toLocaleString: function toLocaleString()
​​toSource: function toSource()
​​toString: function toString()
​​valueOf: function valueOf()
​​<get __proto__()>: function __proto__()
​​<set __proto__()>: function __proto__()
es6.promise.js:110

**Comment by RailsViceRoads** [comment] 2019-05-29 07:42
Additional Note: Trying to show the log with an other computer and differend browsers (same NC Account) does also not work. Therefore I suspect the problem is not on client site.

**Comment by szaimen** [comment] 2021-05-20 13:36
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-20 13:36 UTC
Labels: 0. Needs triage, bug
