### ISSUE TITLE
Accept calendar invitation directly in the invitation email 

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#2338] opened 2016-11-25 15:18 UTC
In [this issue](https://github.com/nextcloud/server/issues/2071) I asked for better design for the emails being sent when inviting anyone to a event. This request is about the possibility to accept the invitation directly in the email, just like you can do with Google Calendar.

Right now you are presented with this (which is pretty nasty):

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 3.5.0//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Africa/Lagos
X-LIC-LOCATION:Africa/Lagos
BEGIN:STANDARD
TZOFFSETFROM:+0100
TZOFFSETTO:+0100
TZNAME:WAT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20161125T140909
DTSTAMP:20161125T140909
LAST-MODIFIED:20161125T140909
UID:1J4UQR666RZKWYABID5AF0QKT92XM3TB6JP2D8K0NIQ2VPZM2T9
SUMMARY:Julfest jobbet
LOCATION:Kontoret
CLASS:PUBLIC
STATUS:CONFIRMED
ORGANIZER;CN=Daniel Hansson:MAILTO:daniel@techandme.se
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUAL;X-NC-
 GROUP-ID=0:MAILTO:daniel.hansson@orestad-linux.se
DTSTART;TZID=Africa/Lagos:20161220T160000
DTEND;TZID=Africa/Lagos:20161220T170000
END:VEVENT
END:VCALENDAR

``` 

I think it's a must have to be able to accept the invitation directly in the email especially when speaking of enterprise, how can we compete with e.g. Google otherwise? 

cc @Espina2 @eppfel @jancborchardt @MorrisJobke

**Comment by joergmschulz** [comment] 2016-11-27 11:36
This is a topic for the MAIL app. We can't even display all invitations, currently-  @ChristophWurst and others (hopefully) are currently rethinking the display of the mails. See topic [https://github.com/nextcloud/mail/issues/160]. Before this isn't done, we can't even think of connecting mail and calendar. 
Maybe a moderator can move this topic to the mail app?

**Comment by enoch85** [comment] 2016-11-27 16:54
@joergmschulz I don't agree that this is a mail app issue. What if you are not using the mail app? This issue is about sending invitations to *anyone* not only people using the mail app.

Try sending an invitation to one with Google Calendar, what will they see? They will see the regular invitation with "Yes" "No" "Maybe". Havenät tried sending an invitation to someone with outlook, but I imagine it's the same. The mail app is just a client to handle the mails.

**Comment by joergmschulz** [comment] 2016-11-27 17:31
Ah, so I misunderstood your issue - because I didn’t have it yet.
All invitations I have sent and tested have been successful for: Thunderbird, Outlook, Outlook on WP8.1 and Apple Mail/iCal.
So, your Google doesn’t swallow the embedded invitation?
Big question: is this reproducible for other Google accounts?

**Comment by enoch85** [comment] 2016-11-28 08:15
@joergmschulz If the reciver have Nextcloud, and using another (domainbased) email that isn't connected to a service like Google e.g. hey@example.com the only thing you the reciver will see is what I posted in my first issue. DAV must be able to somehow generate a nice invitation, or maybe it's PHP that's necesarry, idk really as I'm not a coder.

**Comment by jancborchardt** [comment] 2016-12-16 00:31
cc @nextcloud/calendar as this is probably more relevant for the folks ;)

**Comment by georgehrke** [comment] 2016-12-16 15:06
I'd be happy to implement the server-side logic for accepting/rejecting invitations. Although I'd appreciate help with the mail template / mail design. (cc @eppfel ;))

**Comment by jancborchardt** [comment] 2016-12-16 16:26
@georgehrke do you have any version you like most (like from Google Calendar / Inbox, or iCloud, etc)? Then we could start building it based on that layout, and improve going forward. cc @nextcloud/designers

**Comment by georgehrke** [comment] 2016-12-16 16:27
@enoch85 posted a screenshot in https://github.com/nextcloud/server/issues/2071

**Comment by enoch85** [comment] 2017-02-15 21:07
Ping

**Comment by warnerbryce** [comment] 2017-03-22 16:52
Ping too, having the power to answer to Nextcloud' calendar invitation would be great.
This is the big last feature that miss in this calendar. 

3 companies using nextcloud as a calendar server waiting for it.

I could help for testing this feature.

**Comment by georgehrke** [comment] 2017-03-22 17:04
@warnerbryce Help developing this feature would be even more appreciated ;)

**Comment by enoch85** [comment] 2017-03-22 20:02
@georgehrke Give me some months, I just have to learn PHP. ;)

**Comment by eppfel** [comment] 2017-03-25 18:45
Bountysource would be another option: https://www.bountysource.com/issues/39482696-enhancement-accept-calendar-invitation-directly-in-the-invitation-email

**Comment by enoch85** [comment] 2017-03-25 19:59
Well, let's get this started. Just posted $50.

**Comment by enoch85** [comment] 2017-03-30 12:49
>Just posted $50.

Seems like it doesn't show up :/ I'll contact BountySource and make it happen.

Btw, Hackweek... Mind looking at this issue? *please* :)

**Comment by warnerbryce** [comment] 2017-04-04 13:18
Posted 50$, this enhancement is really important for me.

**Comment by eppfel** [comment] 2017-04-04 18:56
So, for a start...

There is a SabreDav Plugin: http://sabre.io/dav/scheduling/
Based on the both RFCs: 
- https://tools.ietf.org/html/rfc5546
- https://tools.ietf.org/html/rfc6638

So we have to implement this on the servers and than edit the mail template, as far as I understand it @georgehrke ?

**Comment by georgehrke** [comment] 2017-04-04 18:59
The scheduling plugin is already enabled. ;) 

We need to hook into the iTip plugin that sends the email, generate some token and write it to the database, use that token to generate a couple of links for the email.
The email needs:
- Attend
- does not attend
- unsure

and we need one token per attendee

**Comment by enoch85** [comment] 2017-04-16 06:02
Fixed the bountsource issue so now it's $100 instead.

**Comment by warnerbryce** [comment] 2017-07-12 11:00
Any update for this request ? It's a deal-blocking for two clients. I will increase bounty in some days so...

**Comment by georgehrke** [comment] 2017-07-13 15:02
> Any update for this request ?

it's currently planned for Nextcloud 13 and I can assure you it won't come earlier, as we don't back port features to older releases.

**Comment by MorrisJobke** [comment] 2017-09-03 18:56
See also #2149 for some technical ideas.

**Comment by warnerbryce** [comment] 2017-11-15 19:23
S**t it has been postponed again. I’m gonna increase the bounty by 100€ for making thing move and be sure it will be for nextcloud 14

**Comment by MisterY** [comment] 2017-11-15 21:52
Is there any workaround at the moment? My invitations get sent but that's it. A black hole, as nobody can confirm or reject participation. :(

**Comment by georgehrke** [comment] 2017-11-16 13:07
I know, some of you are disappointed that this was postponed, but we made progress on the issue. The task list for this issue is quite long, but with Nextcloud 13 we tackled one of the biggest issues:
Migrating the invitation email to our email templating.

<img width="1392" alt="screen shot 2017-11-16 at 1 56 45 pm" src="https://user-images.githubusercontent.com/1250540/32892559-ea0923b8-cad6-11e7-8453-b35b1e0e5784.png">

This makes adding buttons and links to the email extremely convenient and pretty much only leaves us with adding the server-side logic for the links (generating unique tokens, handling the requests, updating the organizer's event, allow attendee to leave comments and number of guests)

**Comment by warnerbryce** [comment] 2017-11-16 14:05
Great news, i thought it haven't move at all.

**Comment by mikeziri** [comment] 2017-11-17 10:09
awesome. great to hear this is moving forward.
is any help still needed?

**Comment by jospoortvliet** [comment] 2018-01-02 16:33
Nice to know it is now easy, esp as there's a 115 dollar bounty on it - so somebody has an easy way to earn that money 👍

**Comment by immae1** [comment] 2018-01-25 14:02
Hi there, 
I think I  have a similar problem. Internally within the calendar user invites are working as expected. If I want to invite an _external_ googlemail user via email, that works too. Once the external gmail-user confirms the appointment (email), nothing changes in the status of the appointment within the nextcloud calendar entry. (Not accepted / rejected) It seems that the back channel between Google Mail and Nextcloud Calendar has problems. An email is generated that the gmail user have accpeted the invite and is sent to the emailaddress of the user who have created the calendar-entry, but I don't see the updated status in the calendar.  Maybe your discussed workaround could help me out.  @georgehrke When the update will be available? :) Many thanks.

**Comment by MisterY** [comment] 2018-01-25 14:27
@immae1, the email that gets from google can only affect your calendar if the email is somehow linked to the calendar application. In many instances this will not be the case. If the response from google goes to your yahoo email address, there is (currently, afaik) no way for calendar to know anything about it.
One of the proposed solutions is to have an HTML email content in the invite, containing a clickable link, clicking which would trigger a publicly accessible action on your calendar app. This would be a much more valuable solution for anybody with a public email address, I believe.
In any case, both solutions are technically valid and it would be great to have them both at some point in the future, to cover for different calendar/email solutions we are communicating with.

**Comment by labor4** [comment] 2018-01-25 16:27
Speaking for Mac, I say this old roundtrip is doomed beyond help.

Just for the sake of how bad everything is:
;-)

For Mac, I think it looks like this (do correct me if I'm wrong):
1. iCal makes direct http invite-caldav-request to Nextcloud server
2. Nextcloud (Server) sends Mail to invited person
3. Invited person gets mail, and needs to have this address defined as "Thats my address" in Addressbook Mac-App
4. So iCal will understand, and provide the Yes/No Question, sends answer to Apple-Mail for delivery.
5. User sends email back
6. Event-holder gets Email
7. Email address again needs to be defined as "Thats my address" in Addressbook Mac-App
8. iCal edits the Event.

I don't think this has ever worked once, I even think iCal is actually broken at point (4). I tried it for hours ;-). Recently I had a glance at an Apple iCloud mail invitation that uses the approach discussed in this thread.

The elegance with above discussion would be that the badness ends after point (2) AND it can be reversed (recipient changes invitation).

This will make the world better, I promise.

**Comment by enoch85** [comment] 2018-01-25 17:07
@labor4 Sell your Mac, buy a Dell XPS13 and be happy. :)

**Comment by warnerbryce** [comment] 2018-01-25 17:09
@labor4 : 
If you're a mac user the invitation worked like this : 
1- You have an iCloud account, so the invitation is sent via iCloud server, and the reciptiant user get an HTML email with three box Yes - No - Maybe, the user click to this link and your calendar is updated. Google do the same thing and Nextcloud will.

2- You're an old fellow, and you use iCal with OS X Server, you have an account, and an Email account configured in OS X Server for the invitations. You set an appointement with an attendee, OS X Server send an email from the account configured inside. The attendee receive an email, but the answer is sent by email, and OS X Server checks emails from this address and modify the appointement with this answer. I used it a lot some years ago, but it such a pain in the *ss because it's always buggy and use an email address just for invitation.

With the iCloud - Google - Microsoft - Nextcloud method, the box is an URL link, it's so more stable than the method with an email as an answer.

**Comment by Wohlraj** [comment] 2018-01-25 18:45
is this supposed to work when the email used to send invitations is the same as the one in 'reply-to' field (which receives the answers)?

**Comment by labor4** [comment] 2018-01-25 18:54
@warnerbryce 
Yes, I am an old fellow so I will no longer pain my *ss with OSX server.
I'd rather happily spend 2 hours hacking iptables to finally work around crappy Apple 8443/8843 port bugs to be able to use NC! Such is my devotion! cheers

**Comment by warnerbryce** [comment] 2018-01-25 19:27
@labor4 I started on Owncloud from version 6, i've worked with it on aWindows Server with Wamp, an OS X Server with Server.app, an OS X Server with Mamp, and now i'm on Nextcloud on Linux/Debian. 
The best options you could get to have a nice Nextcloud Server working on OS X is : (first is worst then it increase)
1 - Use OS X Server app, modify /Library/Server/Web/Config files to make Apache web server works as you want (ports, ssl, .htaccess, etc...) Use postgresql as a database and php 5.... It's really anoying to make it works but it's possible and it's long.
2 - Use OS X system with MAMP (or MAMP Pro), easier to make it work, you can choose the version of apache you want, the version of php, mysql is there too. With a little bit of practice on software, you can have a good Nextcloud Server
3 - Use a virtualisation software (VirtualBox or Parallels) install a linux distribution, install Apache/Ngnix - Mysql-MariaDB - PHP7 - Certbot(letsencrypt). It's really easy to make snapshots, backups, and support from forum.
We're quite out of topic there, if you want to discuss about that you can join me on the help.nextcloud.com forum, my name is Nemskiller.

**Comment by enoch85** [comment] 2018-01-25 20:01
@warnerbryce 

> The best options you could get to have a nice Nextcloud Server working

...is the [Nextcloud VM](https://github.com/nextcloud/vm). ;)

**Comment by warnerbryce** [comment] 2018-01-25 20:04
@enoch85
It’s my way or the highway. 

Yeah Nextcloud VM could be really the best start for a beginner and more.

**Comment by warnerbryce** [comment] 2018-03-14 17:20
Any news about this issue ? Does everything will be in the startingblocks for NC 14 ?

**Comment by warnerbryce** [comment] 2018-06-18 18:18
Hello @georgehrke and @jospoortvliet

We have no news about this, does it will be ready for NC 14 ?

**Comment by georgehrke** [comment] 2018-06-18 18:23
@warnerbryce I will look into this in the next couple of days, don't worry 😉

**Comment by MorrisJobke** [comment] 2018-06-25 16:55
Fix is in #9942

**Closed** 2018-07-11 17:53 UTC
Labels: 3. to review, enhancement, feature: dav

**Comment by georgehrke** [comment] 2018-07-11 18:00
@warnerbryce Feel free to open a follow up ticket about the enhancements you suggested in the pull-request, so they don't get lost! :)

**Comment by Luncheon3462** [comment] 2024-04-15 16:29
@ChristophWurst @miaulalala @st3iny, please help get this fixed. When Office 365 sends calendar invitations, the snappymail nextcloud app by @the-djmaze handles them perfectly. They appear in the email message and can be added to a nextcloud calendar with one-click. Maybe this code that @the-djmaze mentioned will work? https://github.com/the-djmaze/snappymail/blob/fffc04499875531bd3dd626d01baaf7a86452cd3/plugins/nextcloud/js/message.js#L111-L179
