### ISSUE TITLE
When sharing "Upload Only" link, have theme background

### ISSUE THREAD

**Issue by io-node** [nextcloud/server#5547] opened 2017-06-27 09:52 UTC
With the current implementation of the Upload Only shares, it shows a plain white background. I was wondering if there is a possibility of adding a feature (which can be enabled or disabled in the Admin config) to use the theme background as part of the web-page of the Upload Only option.

Example below:
![image](https://user-images.githubusercontent.com/2435859/27581803-9ec846e2-5b26-11e7-98fa-2d1cb447c552.png)

**Comment by juliushaertl** [comment] 2017-06-27 10:26
Duplicate of https://github.com/nextcloud/server/issues/1360

Quoting @jancborchardt from there:
> Yeah, it would be too distracting to have the full background there. It’s too much crucial text info there.
>
> On the log in and installation page it’s fine because we have lots of big text and white input boxes. But anywhere else all info must be perfectly readable, so we keep it for uploading the same as for the folder view. :)

**Closed by juliushaertl** 2017-06-27 10:26 UTC

**Comment by jancborchardt** [comment] 2017-06-28 22:16
Yep, and to confirm I still completely stand by what I said back then. Thanks for resolving it @juliushaertl. :)
