### ISSUE TITLE
Calendar event invitee emails and links are incorrect as events are deleted and restored from trash.

### ISSUE THREAD

**Issue by brad2014** [nextcloud/server#36051] opened 2023-01-09 14:29 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Invitation/Cancellation emails for events need to occur when an event is deleted into or restored from the Calendar trash folder, but instead cancellation emails are sent both on "event delete" and again (duplicate) on "trash emptied", but are not being sent on "restored from trash to calendar".

## Duplicate Cancellation messages, incorrect token handling of deleted/cancelled event:

1.  In the nextcloud calendar app, create an event, invite an external party, save. (invitee receives invitation email)
2. Delete the event via the calendar app UI - notice that Cancellation email is sent.
3. Notice that URL in the original invitation email "more options" link goes to a page asking this user if they accept/decline, even though the event has been canceled.
4. Open the calendar trash bin and empty the trash - a duplicate Cancellation event is incorrectly sent, invitation token is "dangling" (see #12387). 

## Missing Invitation Message when event restored from trash:

1.  In the nextcloud calendar app, create an event, and invite an external party.
2.  Delete the event via the calendar app UI (notice that Cancelation email is sent, notice that invitation link in recipient).
3.  Open the calendar trash bin and restore the event. (notice no "Invitation" email is sent - invitee thinks the event is still canceled)

### Expected behavior

- When an event is newly added to the calendar, an "Invitation" email is sent, containing a link to accept/decline (unless `config:app:set dav invitation_link_recipients` is turned off).  This is already correct.

- When an event is moved from the calendar to trash, a single "Cancelled" email should be sent to each invitee, and the STATUS of the attached VEVENT should be changed from CONFIRMED to CANCELLED (per RFC).  (The STATUS is optional in the `METHOD: CANCEL` vevent sent to the invitee - it could be set to CANCELLED in this case, but note that removing an invitee from an event properly sends a CANCEL email to that invitee where the invitation is canceled but the event is not).  

- the UI for /apps/dav/invitation/moreOptions/ (and simlilar) should say "This event has been canceled." rather than showing the form for accept/decline a cancelled event.

- When the calendar trash is emptied, no emails should be generated, and as the calendar object is deleted, any calendar_invitation entries that refer to it should be deleted. 

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.2
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_external: 3.1.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - suspicious_login
  - user_ldap
```

**Comment by szaimen** [comment] 2023-01-09 16:44
Hi, which nc version?

**Comment by nextcloud-command** [comment] 2023-02-09 01:12
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by brad2014** [comment] 2023-02-10 06:51
(Apologies for delay @szaimen just noticed your post.)
This is reproducible on NC version 25.0.3.

**Comment by SebastianKrupinski** [comment] 2024-07-18 00:22
Duplicate of #12387

**Closed by SebastianKrupinski** 2024-07-18 00:22 UTC
Labels: bug, 0. Needs triage, feature: caldav, 25-feedback

**Comment by SebastianKrupinski** [comment] 2024-07-18 00:23
Duplicate of #45677
