### ISSUE TITLE
Contacts count limit is too low by 10x at least.  Maxes out at 999+

### ISSUE THREAD

**Issue by gessel** [nextcloud/server#8649] opened 2018-03-05 10:44 UTC
### Steps to reproduce
1.  Add more than 1,000 contacts (I have 7,000)
2.
3.

### Expected behaviour
Count should show number, a count is useful to monitor for changes.  Also, scripts on the contacts page shouldn't be flagged as non-responsive by the browser

### Actual behaviour
shows 999+ rather than actual count, scripts tend to time out.

### Server configuration

**Operating system**: Freebsd 10.3

**Web server:** Apache 24

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** FreeBSD ports tree

**Comment by splitt3r** [comment] 2018-03-05 11:26
Duplicate of https://github.com/nextcloud/contacts/issues/445

**Closed** 2018-03-06 12:35 UTC
