### ISSUE TITLE
NC18.0 Shared links don't show top-description

### ISSUE THREAD

**Issue by Aesculapius** [nextcloud/server#19063] opened 2020-01-21 21:34 UTC
### Steps to reproduce
1. Create a folder to be shared (I've used a photo folder)
2. Create a description of some kind on top of the directory list (or by creating readme.md)
3. Share the folder with link, disallow any of the editing or uploading options
4. use the link to show the folder

### Expected behaviour
I'd expect the shared link to show the folder (or in my case album) including the description on top of the folder.

### Actual behaviour
The share is accessable but doesn't show the added description on top

### Server configuration

**Operating system:**
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
mysql
**PHP version:**
7.2
**Nextcloud versionTell us what happens instead:** (see Nextcloud admin page)
18.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
from 17.x
**Where did you install Nextcloud from:**
onboard updater
**Signing status:**

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - deck: 0.8.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_downloadactivity: 1.7.0
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - keeweb: 0.6.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - ransomware_protection: 1.6.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.1
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

</details>**List of activated apps:**

**Comment by szaimen** [comment] 2021-05-28 11:25
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-28 11:25 UTC
Labels: 0. Needs triage, bug
