### ISSUE TITLE
FileHandler implementation like in a real OS (default, vs. special per File)

### ISSUE THREAD

**Issue by kaystrobach** [nextcloud/server#40346] opened 2023-09-08 09:19 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Some office documents work in OnlyOffice, some in OpenOffice.
This is usually solved in other Operatingsystems by filehandler, which operate either directly on a per file decision or on the file ending.

**Describe the solution you'd like**

I see 2 solutions:

- offer an option to open a file with a different file handler via context menu
- behave like Mac os and let the user decide on file type and based on a single file, which handler should be used

**Describe alternatives you've considered**

- switching office suite

**Additional context**

**Comment by skjnldsv** [comment] 2024-09-17 12:42
Duplicate of https://github.com/nextcloud/viewer/issues/2393

**Closed by skjnldsv** 2024-09-17 12:42 UTC
Labels: enhancement, 0. Needs triage, feature: files
