### ISSUE TITLE
[BUG]Drop to upload

### ISSUE THREAD

**Issue by Pacius** [nextcloud/server#16262] opened 2019-07-06 02:52 UTC
### Expected behaviour
droping files to blank zone Inside a folder ,using Chrome, then upload.

### BUG behaviour
Droping files to blank zone of the folder which is opened ,using Chrome, then it shows 'You don’t have permission to upload or create files here', there is the weird thing, I still can upload files by clicking 'upload files' or droping files directly to the folder which is not opened.

I think i got the right nextcloud file permission and environment configurations.

### Server configuration

**Operating system**: **NEW CentOS 7**

**Web server:** Apache 2.4

**Database:** Mysql 5.7

**PHP version:** 7.2

**Nextcloud version:** 16.02

**fresh install:** YES

**Where did you install Nextcloud from:** wizard

**Comment by gary-kim** [comment] 2019-07-06 03:53
Your issue seems to be a duplicate of #16238

**Closed by gary-kim** 2019-07-06 03:54 UTC
Labels: 0. Needs triage, bug
