### ISSUE TITLE
NC17 - Bug when language is changed

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#18071] opened 2019-11-22 11:04 UTC
### Steps to reproduce
1. Change curent lang into english (for e.g.)
2. Change again into another language
3. Get back into the main page

Main language should be in french.

![NC](https://i.imgur.com/vUcqsYh.png)

Zoom in: 

![ZoomIn](https://i.imgur.com/FwYs54y.png)

### Expected behaviour
Should be translated into french

### Actual behaviour
Is translated in English

### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache/2.4.6

**Database:**
 5.5.64-MariaDB

**PHP version:**
PHP 7.3.11

**Nextcloud version:** (see Nextcloud admin page)
17.0.1.1

**Updated from an older Nextcloud or fresh install:**
Both

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Are you using encryption:** no

### Client configuration
Chrome 78.0.3904.97 (64 bits)
Firefox 70.0.1 (64 bits)
Edge

**Comment by GretaD** [comment] 2019-11-26 13:19
Hey @vipera7 thank you for reporting this. It is a bug indeed and we're trying to solve this. A PR is already open here [14784](https://github.com/nextcloud/server/pull/14784)

**Comment by wiswedel** [comment] 2020-01-02 06:31
duplicate of https://github.com/nextcloud/server/issues/15980

**Closed by wiswedel** 2020-01-02 06:31 UTC
Labels: 2. developing, bug
