### ISSUE TITLE
css issue in welcome email 

### ISSUE THREAD

**Issue by phonon112358** [nextcloud/server#19255] opened 2020-02-01 19:15 UTC
### Steps to reproduce
1. create new user with email address but without password 
2. open the welcome email 
3. Zoom in

### Expected behaviour
All texts are fully readable at all zooming levels and on all devices/email programs.

### Actual behaviour
The text on the left button "Set your password" (in german: "Setze Dein Passwort") is not fully shown but cut off. 
This happens at least in Thunderbird when one zooms in a bit (because then the text is split into two lines and the button doesn't resize enough). The button to download the client resizes correctly, however.

### Server configuration

**Operating system:** Debian 10

**Web server:** nginx 

**Database:** mariadb 10.4

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 17.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from NC 17.0.x

**Where did you install Nextcloud from:** full local install on my home server 
>

### Client configuration
**Browser:** Thunderbird 

**Operating system:** windows 10

**Comment by sbouafif** [comment] 2020-05-06 08:46
There's the same problem when the website name is too long and the user already has a password. The text of the button is "Go to %website_name%", when %website_name% is too long, the white text in the button is on the white background of the email.

The bug is still in 18.0.4

The solution is to change the max-height of the table containing the button

It seems to be fixed in "master" as the max-height is now 60px which will allow a 2 line button https://github.com/nextcloud/server/blob/master/lib/private/Mail/EMailTemplate.php#L235

**Comment by jancborchardt** [comment] 2020-06-11 11:38
This is a duplicate of issue https://github.com/nextcloud/server/issues/13287 and is fixed in the current release Nextcloud 19 through pull request https://github.com/nextcloud/server/issues/13287 by @liamjack :)

**Closed by jancborchardt** 2020-06-11 11:38 UTC
Labels: 0. Needs triage, bug

**Comment by phonon112358** [comment] 2020-06-11 13:10
Thanks! ;) 
and sorry for the duplicate!

**Comment by jancborchardt** [comment] 2020-06-11 16:57
No worries at all. :) Thank you for taking the time to report issues.
