### ISSUE TITLE
[Bug]: Force reload required after upgrade 29 -> 30 

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/server#46976] opened 2024-08-02 06:24 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading from 29.0.4 to 30.0.0 Beta 3 a force reload was required on the users end (multiple apps were affected, like talk, forms,…). Seems that our cachebuster has an issue somewhere?

### Steps to reproduce

1. Upgrade from 29 to 30

### Expected behavior

No force reload required 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by juliushaertl** [comment] 2024-08-02 06:54
Not entirely sure if that is the cause but could contribute to it: https://github.com/nextcloud-libraries/nextcloud-vite-config/pull/267

**Comment by sorbaugh** [comment] 2024-10-01 07:47
Can you please look @susnux 🙏

**Comment by sorbaugh** [comment] 2024-10-09 13:10
Proposed way forward by @nickvergessen if I understood correctly: Check if it's a shipped app and additionaly use the Nextcloud Version to create a new hash.

**Comment by susnux** [comment] 2024-10-09 13:42
So some background:

There was a bug in nextcloud-vite config, this now fixed. All apps that updated to v1.4.2 or later should work correctly.
But there is still a problem for shipped apps like the viewer if their version number does not change -> same cache buster.

**Comment by nickvergessen** [comment] 2024-10-09 19:25
> But there is still a problem for shipped apps like the viewer if their version number does not change -> same cache buster.

That's where:
> Check if it's a shipped app and additionaly use the Nextcloud Version to create a new hash.

would come in :)

**Closed** 2024-10-14 15:22 UTC
Labels: bug, 0. Needs triage, feature: files, feature: install and update, feature: caching, 30-feedback
