### ISSUE TITLE
Change Color of Birthday Calendar

### ISSUE THREAD

**Issue by der-Daniel** [nextcloud/server#2965] opened 2017-01-06 08:55 UTC
Hi,

referencing this issue: https://github.com/nextcloud/calendar/issues/274, I want to suggest a possibility of changing the colors of the birthday calendar.

It neither readable in my browser nor on my android device.

Moreover I would really appreciate a way to change colors of calendars with a convenient color picker. So far I only have like 10 colors to choose from.

Cheers

**Comment by MorrisJobke** [comment] 2017-01-09 13:45
cc @jancborchardt

**Comment by Tarry91** [comment] 2017-02-20 20:29
I just want to add my +1 here :)

**Comment by Luticus** [comment] 2017-03-03 01:32
I'm running the newest version of the calendar as well as the newest nextcloud and I cannot change the color of the birthday calendar.  Mine is stuck on this really bright color which then becomes unreadable on my android calendar widget (which syncs color with nextcloud)

**Comment by linuxpete** [comment] 2017-03-05 11:35
Using Nextcloud 11.0.1 and calendar 1.5.1. Change of color not possible. Would help if color at least is darker then yellow.

**Comment by MariusBluem** [comment] 2017-03-05 12:17
What about giving birthdays no color and indicate them with a 🎁 (for frontend @georgehrke) ... This is what Apple does 😁

**Comment by linuxpete** [comment] 2017-03-05 13:00
Well yes, could be but then a birthday doesn't show OK in your calendar (white background with white font). So the birthday must have a good visible color, which sadly isn't yellow.

**Comment by czernedo** [comment] 2017-05-20 09:31
+1! 
Especially when using Today Calendar on Android it's annoying because there is white Font on Yellow ground then. :/

**Comment by jancborchardt** [comment] 2017-05-22 21:09
Good point by @MariusBluem, so it should be black on white by default? Or can you show a screenshot of how macOS does it?

**Comment by MariusBluem** [comment] 2017-05-22 21:21
![img_4923](https://cloud.githubusercontent.com/assets/19711361/26328960/5ecba36a-3f45-11e7-8a6d-04d23040dab4.JPG)

@jancborchardt

**Comment by fredddii** [comment] 2017-08-14 05:56
I have to install Calendar Color [https://github.com/pascalfree/calendar-color/releases](url) just to change this single birthday calendar colour. I would really appreciate if we could change it ourselves on Nextcloud.

**Comment by jancborchardt** [comment] 2017-08-14 11:33
@georgehrke @tcitworld @Henni @irgendwie can we change this? :) It's a papercut.

**Comment by georgehrke** [comment] 2017-08-14 13:01
I'm fairly sure this was fixed with Nextcloud 12
Will verify that 

Please excuse my brevity and typos.

**Comment by tcitworld** [comment] 2017-08-14 17:55
That's what I thought as well, but this doesn't look like it's fixed yet.

**Comment by jancborchardt** [comment] 2017-08-14 23:42
Let’s simply set another default color for the birthday calendar. For example the rightmost (pink) one, cause that is the last which will be used on creating new calendars.

**Comment by Peque** [comment] 2017-08-14 23:52
@jancborchardt With "will be used" you mean "will be chosen by the user"? I think that is pretty subjective. Also, if that is true, then the fact that people chose it less often probably means they dislike it or they find it uglier, so why would they want an ugly color for their birthday calendar?

I think the problem is not being able to change the color at will, rather than the particular default color.

**Comment by jancborchardt** [comment] 2017-08-15 09:25
The main issue is the default color not being readable, as written in the original issue. Most people don't change the default so our primary goal should be sane defaults.

By "will be used" I mean that new Calendars you create automatically use the next not-yet-used color from the color list from left to right (at least should be @georgehrke @tcitworld) - hence the rightmost color would be used last by this automatic algorithm.

**Comment by Peque** [comment] 2017-08-15 14:51
@jancborchardt Understood, thanks. Would it make sense to split this issue into two? (i.e.: "Better default birthday calendar color" and "Allow changing the birthday calendar color")

I, for instance, am interested in the latter feature, rather than the discussion about the defaults, and the original issue (as well as the referenced https://github.com/nextcloud/calendar/issues/274) both talk about a color picker for the birthday calendar.

**Comment by jancborchardt** [comment] 2017-08-15 15:46
Yes, they are different issues. This one is about the default. :)

**Comment by georgehrke** [comment] 2017-08-15 15:47
Please wait with creating a new issue about changing it.
I will first verify if not being able to change it is a server or a client issue

**Comment by Peque** [comment] 2017-08-28 17:04
@georgehrke Did you verify it? :innocent:

**Comment by pengandy** [comment] 2017-09-19 15:47
Hi @georgehrke, do you have news on that? I experience the same on my Android phone: light yellow color is picked by the calendar app with white font. So it is impossible to read any birthday event. I think it isn't a coincidence that the mobile app picks the same color like within the nextcloud birthday calendar.

This issue is now open for 8 month and it's not really a corner case. Would be great if you could follow that up. Thx Andy

**Comment by j-ed** [comment] 2017-09-19 16:06
At least with Nextcloud **12.0.2** and the Calendar app **1.5.4** it is still not possible to change the color of the birthday calendar.

Beside the discussion if this feature should be implemented or not, I want to point your attention on the fact that many people with handicaps exist who cannot differentiate pastel colors very well. Therefore I would appreciate the possibility to adjust the colors individually.

**Comment by Peque** [comment] 2017-09-27 08:56
@georgehrke Did you verify it?

**Comment by georgehrke** [comment] 2017-09-27 09:04
```
[georgehrke@... (11:02:22) ~] curl 'http://nextcloud.dev/remote.php/dav/calendars/admin/contact_birthdays/' -X PROPPATCH --user admin:admin --data-binary '<d:propertyupdate xmlns:d="DAV:"><d:set><d:prop><a:calendar-color xmlns:a="http://apple.com/ns/ical/">#74cce7</a:calendar-color></d:prop></d:set></d:propertyupdate>'
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/calendars/admin/contact_birthdays</d:href><d:propstat><d:prop><x1:calendar-color xmlns:x1="http://apple.com/ns/ical/"/></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

Sending a prop patch works => most likely a calendar app issue

**Comment by georgehrke** [comment] 2017-09-27 09:08
Like @MariusBluem, I would also suggest changing the default color to white and prepending 🎂 to the events name.

Let's do it?

**Comment by tcitworld** [comment] 2017-09-27 09:13
How would we know the calendar is activated or not in the calendar app if we don't have any events to display ?

**Comment by Peque** [comment] 2017-09-27 09:15
@georgehrke Could you reopen https://github.com/nextcloud/calendar/issues/313 then?

**Comment by juliushaertl** [comment] 2018-01-20 11:24
Changing the color though caldav works. So the rest of the implementation needs to be done on the calendar app: https://github.com/nextcloud/calendar/issues/313

**Closed by juliushaertl** 2018-01-20 11:24 UTC
Labels: bug, design, good first issue, papercut, starter issue

**Comment by monreal** [comment] 2018-04-26 19:38
@juliushaertl which app can change the color through CalDAV? Neither my GNOME Calendar nor Simple Calendar on Android can :/

**Comment by juliushaertl** [comment] 2018-04-27 10:12
@monreal I actually just used curl for it:

```
curl 'https://cloud.example.com/remote.php/dav/calendars/admin/contact_birthdays/' -X PROPPATCH --user admin:password --data-binary '<d:propertyupdate xmlns:d="DAV:"><d:set><d:prop><a:calendar-color xmlns:a="http://apple.com/ns/ical/">#eeeeee</a:calendar-color></d:prop></d:set></d:propertyupdate>
```

**Comment by monreal** [comment] 2018-04-27 15:42
@juliushaertl works great, thanks a lot!
