### ISSUE TITLE
Flickering in Safari when hovering File App's action box

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#877] opened 2016-08-15 12:57 UTC
1. Open https://demo.nextcloud.com/index.php/apps/files/ in Safari / Safari Technology preview
2. Click on the 3 dots (…) for a file. A box will appear.
3. Hover over the links in the box

See this recording:

![bug](https://cloud.githubusercontent.com/assets/5585491/17665011/6aa2f5aa-62f8-11e6-9332-7b25bc2e8cba.gif)

To me this looks like a Safari bug with drop-shadows.
Will try to fix this issue.

**Comment by nickvergessen** [comment] 2016-09-28 12:33
Saw this on franks laptop as well
@jancborchardt any idea?

**Comment by jancborchardt** [comment] 2016-09-28 12:35
Hm, no idea what could cause that. :\ @leonklingele does it appear in Safari stable or only in the tech preview?

Calling the people with Safari: @MorrisJobke @LukasReschke @MariusBluem

**Comment by leonklingele** [comment] 2016-09-28 12:56
@jancborchardt it's reproducible on stable Safari 9.1.2.
I haven’t checked the latest Safari (v10).

**Comment by MorrisJobke** [comment] 2017-01-31 02:21
Still an issue on master. :/

**Comment by MorrisJobke** [comment] 2017-02-02 21:05
Left: Chrome, right: Safari

<img width="769" alt="bildschirmfoto 2017-02-02 um 15 02 21" src="https://cloud.githubusercontent.com/assets/245432/22568263/b7a6126a-e958-11e6-8655-7c10704a03a6.png">


The flickering happens when the bigger shadow appears. @skjnldsv Do you have an idea, why not always this bigger shadow is applied? It can be triggered by setting a `<tr>` element in the file list to the hover state 😕 

Maybe you can help me debug this. I sadly can't find the reason.

**Comment by skjnldsv** [comment] 2017-02-03 06:26
I could reproduce easily.
The css doesn't have specific values for this. It seems to be coming from safari.
I've read some other similar issues over the web 😞

**Comment by MorrisJobke** [comment] 2017-05-17 14:44
Fix is in #4924

**Closed** 2017-05-17 16:21 UTC
Labels: bug, design, feature: files, starter issue
