### ISSUE TITLE
CardDAV REPORT request truncated

### ISSUE THREAD

**Issue by pbek** [nextcloud/server#3740] opened 2017-03-06 21:42 UTC
Thank you for the NC ecosystem!

My only problem is that I still have the same issue I reported here: https://github.com/owncloud/contacts/issues/389
I can't see any contacts in the Nextcloud Contacts app.
Syncing with 3rd party tools via CardDAV works.
No nextcloud.log output, just javascript warnings like this:

```
[xmldom warning]	unclosed xml attribute 
@#[line:2,col:259]
dav.js?v=f0a4689…:5510 [xmldom warning]	unclosed xml attribute 
@#[line:130409,col:13]
dav.js?v=f0a4689…:5510 [xmldom warning]	unclosed xml attribute 
@#[line:130411,col:14]
dav.js?v=f0a4689…:5510 [xmldom warning]	unclosed xml attribute 
@#[line:130412,col:11]
dav.js?v=f0a4689…:5510 [xmldom warning]	unclosed xml attribute 
@#[line:130414,col:23]
```

I narrowed the problem down to a seemingly truncated REPORT request.
The NC Contacts app attempts to download all contact information in one REPORT request as a big XML with VCARDs in the user frontend via JS.
The REPORT request stops receiving data after about 9987364 bytes (it varies a bit depending on the contacts). Changing the PHP memory limit from 256MB to 512MB didn't help. Removing the contacts where the truncating occurs didn't help neither. Is there any limit that can be downloaded with this request?

### Steps to reproduce
1. having a lot of contacts with images
2. downloading the contact information 
```bash
curl --header "Depth:1" --data @data --request REPORT -u "username:password" https://servername/remote.php/dav/addressbooks/users/username/Contacts/ > data.xml
```

content of file `data`:

```
<card:addressbook-query xmlns:card="urn:ietf:params:xml:ns:carddav"
                          xmlns:d="DAV:">
    <d:prop>
      <d:getetag />,<card:address-data />
    </d:prop>
    <!-- According to http://stackoverflow.com/questions/23742568/google-carddav-api-addressbook-multiget-returns-400-bad-request,
         Google's CardDAV server requires a filter element. I don't think all addressbook-query calls need a filter in the spec though? -->
  </card:addressbook-query>
```
3. the data in `data.xml` is truncated, so the xml isn't valid
### Server configuration
**Operating system**:
Debian 7.11

**Web server:**
apache

**Database:**
mysql

**PHP version:**
5.6.30

**Contacts version:**
1.5.3

**Nextcloud version:** 
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated to NC 11

**Where did you install Nextcloud from:**
<https://download.nextcloud.com/server/releases/nextcloud-11.0.2.zip>

**Comment by pbek** [comment] 2017-03-07 07:19
The same 9.5MB truncating appears when using the legacy (v1) CardDAV url.

```
curl --header "Depth:1" --data @data --request REPORT -u "username:password" https://servername/remote.php/carddav/addressbooks/username/Contacts/ > data.xml
```

**Comment by pbek** [comment] 2017-04-19 05:59
One workaround would be to move the contacts to different address books so that each address book stays below 9.5MB.

**Comment by skjnldsv** [comment] 2020-08-20 08:06
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-20 08:06 UTC
Labels: 0. Needs triage, bug, feature: dav
