### ISSUE TITLE
Quota issues 

### ISSUE THREAD

**Issue by whositwhatnow** [nextcloud/server#8050] opened 2018-01-25 18:13 UTC
Is there a way to make an external storage location your primary storage upon login?  I am having issues with quotas. 

I've set a 500MB quota per user locally but Users use primarily use the external storage.

when they transfer files it says no space left.

**Comment by MorrisJobke** [comment] 2018-01-30 14:34
Duplicate of #3343 which was fixed with #3438 in Nextcloud 12.

Just set the folder of the external storage to `/` 😉

**Closed by MorrisJobke** 2018-01-30 14:34 UTC

**Comment by whositwhatnow** [comment] 2018-01-30 15:05
unfortunately this doesnt work for me.  I have SMB share and put / in remote subfolder and log out and log back in, still same result.


________________________________

**Comment by MorrisJobke** [comment] 2018-01-30 15:48
> unfortunately this doesnt work for me.  I have SMB share and put / in remote subfolder and log out and log back in, still same result.

Not in the remote subfolder, but in the mount point ;)

**Comment by whositwhatnow** [comment] 2018-01-30 16:38
problem is i have multiple shares on the fileserver.


________________________________

**Comment by MorrisJobke** [comment] 2018-01-30 16:45
> problem is i have multiple shares on the fileserver.

What does this mean?

**Comment by whositwhatnow** [comment] 2018-01-30 18:56
this is my setup.  We have a smb file server with multiple shares.  if i put / where the share shoudl be its a permissions error.


[cid:4656ffae-ff9f-46f0-b734-76757f78eb95]



________________________________

**Comment by MorrisJobke** [comment] 2018-01-30 20:12
> this is my setup.  We have a smb file server with multiple shares.  if i put / where the share shoudl be its a permissions error.

You should not put the `/` as remote subfolder, but where that external storage should be mounted in your nextcloud. 😉 

Something like this (see the `/` in `Folder name`):

![bildschirmfoto 2018-01-30 um 21 11 46](https://user-images.githubusercontent.com/245432/35588886-4e26b93a-0602-11e8-823c-fb024c4f2409.png)
