### ISSUE TITLE
user is allowed to create folders with quota==0

### ISSUE THREAD

**Issue by hede5562** [nextcloud/server#4577] opened 2017-04-28 08:53 UTC
A user with zero quota is still allowed to create folders. Is there a way to prevent this behaviour? 

I'm thinking of either with checking quota on folder creation or disallow folder creation by user group. 

The problem with this behaviour is: If two users wanna share files and one has quota and the other has not, both cannot fill those shared folder if the user with zero quota has created and shared those folders. Users are typically dump, we have to prevent those zero-quota-users from creating and sharing their non-writeable folders. 

(I'd call this a bug, but maybe it's more like a feature request. Depends on opinion I think.)

### Steps to reproduce
1. set user quota to 0 (zero)
2. login as user
3. create folders

### Expected behaviour
User should not be able to create and share folders. 

### Actual behaviour
User can create and share folders. More than one...

### Server configuration

I don't think this does matter. In case it does, see #4407

**Comment by MorrisJobke** [comment] 2017-04-29 04:09
cc @icewind1991 intended behaviour?

**Comment by enoch85** [comment] 2017-06-21 08:53
I can confirm this issue. @MorrisJobke You told me that setting quota to 0 would disable local storage?

**Comment by MorrisJobke** [comment] 2017-06-21 21:12
> I can confirm this issue. @MorrisJobke You told me that setting quota to 0 would disable local storage?

Disables only upload of new files. A folder is technically 0 bytes in size. cc @icewind1991 for the details.

**Comment by hede5562** [comment] 2017-06-22 07:39
@jasonbayton Do I understand you correctly that nextcloud 12 doesn't even offer the option to set a quota of 0? We're still using Nextcloud 11 and do have many 0 quota users using only shared storage.

((( @MorrisJobke I'm pretty sure _technically_ it's indeed _not_ 0 bytes. Else I could create a Billion folders without touching the backend storage. I think more suitable would be the "logical view" of 0 bytes sized folders in Nextcloud. Sorry for this irrelevant hairsplitting - it's meant humorous - my question above is the relevant part of this comment. )))

**Comment by jasonbayton** [comment] 2017-06-22 14:32
@hede5562 exactly.

**Comment by TomFernandes** [comment] 2017-07-15 06:32
To be able to have read-only users it should be possible somehow to disable uploads **and** disable creation of folders (see #5078). Otherwise a user can indeed DOS the system (by creating billions of folders) even with a quota of 0 or 1 bytes and - from our experience users regularly contact us, being confused because they can create folders but can't upload files (in case they have a quota of 0 or 1 bytes) .
As this issue and #5078 are closely related I think it also makes sense to have a fix for this issue on the milestone-list for 12.0.1.

**Comment by enoch85** [comment] 2018-01-10 20:02
@TomFernandes Is this still and issue?

**Comment by MorrisJobke** [comment] 2018-05-03 07:28
Fix is in #9372

**Closed** 2018-05-07 08:11 UTC
Labels: enhancement, feature: files
