### ISSUE TITLE
[Bug]: Cannot open any file from recommendation header list in Files app

### ISSUE THREAD

**Issue by theosche** [nextcloud/server#43932] opened 2024-03-01 10:16 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A click on any file in the header recommendation list leads to a javascript error and does not open the file.
The problem only occurs using the recommandation list in Files App. It works in the dashboard recommendation list.

It was working in previous versions (but I am not sure with which version the bug came).

### Steps to reproduce

1. Open Files App
2. Click on any recommended file in the header list

### Expected behavior

It should open the file.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.actionculture.ch",
            "cloud.yverdonentransition.ch",
            "vert-e-s-et-solidaires.ch",
            "cloud.alternatyv.ch",
            "cloud.sports-5.ch",
            "srv2.actionculture.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "external",
            "forms",
            "registration",
            "fulltextsearch",
            "drawio",
            "sharingpath",
            "files_readmemd",
            "apporder"
        ],
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "ldapIgnoreNamingRules": false,
        "maintenance_window_start": 1,
        "mail_sendmailmode": "smtp",
        "default_phone_region": "CH",
        "default_language": "fr",
        "defaultapp": "files,dashboard",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - announcementcenter: 6.7.0
  - apporder: 0.15.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.5
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.2
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - drawio: 3.0.2
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - forms: 4.1.1
  - fulltextsearch: 28.0.0
  - fulltextsearch_elasticsearch: 28.0.0
  - groupfolders: 16.0.4
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.7
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.1.6
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - recommendations: 2.0.0
  - registration: 2.3.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.4
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - accessibility: 1.10.0
  - admin_audit: 1.18.0
  - appointments: 1.15.5 (installed 1.15.5)
  - calendar_resource_management: 0.6.0 (installed 0.6.0)
  - carnet: 0.25.4 (installed 0.25.4)
  - encryption: 2.16.0
  - event_update_notification: 2.3.0 (installed 2.3.0)
  - federation: 1.18.0 (installed 1.7.0)
  - files_external: 1.20.0 (installed 1.15.0)
  - files_linkeditor: 1.1.16 (installed 1.1.16)
  - files_rightclick: 1.6.0 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.14.0)
  - group_everyone: 0.1.14 (installed 0.1.14)
  - news: 24.0.0 (installed 24.0.0)
  - quickaccesssorting: 3.0.0 (installed 3.0.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - sharerenamer: 3.2.0 (installed 3.2.0)
  - sharingpath: 0.4.4 (installed 0.4.4)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0 (installed 1.16.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing related
```

### Additional info
Using a Mac (Ventura 13.4.1)
On Chrome (122.0.6261.94): TypeError: Cannot read properties of undefined (reading 'fileList')
On Firefox (123.0): TypeError: OCA.Files.App is undefined

**Comment by joshtrichards** [comment] 2024-03-02 14:31
Duplicate of nextcloud/recommendations#700 (sort of)

However, we may have overlooked backporting the fix (nextcloud/recommendations#702) to v28.

**Closed** 2024-03-13 11:27 UTC
Labels: bug, 4. to release, feature: files, 28-feedback
