### ISSUE TITLE
After Migration: Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.

### ISSUE THREAD

**Issue by stone212** [nextcloud/server#13048] opened 2018-12-13 09:26 UTC
### Steps to reproduce
1. Use nextcloud-snap
2. Migrate database and files in /data to fresh install of NextCloud 13
3. Log in.

### Expected behaviour
User logs in with no error

### Actual behaviour
User sees this error on top of the screen:

` Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.`

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache2

**Database:**
mariaDB

**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Migrated from nextcloud-snap (currently 13)
**Where did you install Nextcloud from:**
https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#ubuntu-installation-label**
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Elfanar** [comment] 2019-01-20 19:20
I am still having this and I am using version 15 :

Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.

**Comment by stone212** [comment] 2019-01-21 03:08
@Effanar I just disabled the "Default Encryption App" and it worked.  I didn't use Encryption on the older version so this worked for me.

**Comment by kesselb** [comment] 2019-06-09 12:02
Duplicate of #8546

**Closed by kesselb** 2019-06-09 12:02 UTC
Labels: 0. Needs triage, bug
