### ISSUE TITLE
Setting up S3 External Storage with open_basedir restriction throws InvalidArgumentException

### ISSUE THREAD

**Issue by benv666** [nextcloud/server#23555] opened 2020-10-19 08:42 UTC
While trying to setup external storage using AWS S3 this error appears:
![image](https://user-images.githubusercontent.com/165034/96418230-b9afdc00-11f2-11eb-82e5-db9fd4a7838d.png)
```
InvalidArgumentException: Invalid configuration value provided for "use_path_style_endpoint". Expected bool, but got string(36) "*** sensitive parameter replaced ***"

use_path_style_endpoint: (bool)

  Set to true to send requests to an S3 path style endpoint by default. Can
  be enabled or disabled on individual operations by setting
  '@use_path_style_endpoint' to true or false.
```

The nextcloud.log entry generated shows that something tries to read the default AWS config/credentials file which is outside of my php's restricted open_basedir setting - as far as I'm concerned only the webroot, temp folder, and data folders should be allowed access.

PS: It seems like the AWS credentials are not marked as sensitive in the nextcloud.log - I filtered these manually in the log below.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set php's open_basedir restriction to `/tmp:/www/yourvhostroot:/www/yourdataroot` and *do not* add `/home/yourwebuser`
2. Go to the settings of the External Storage Plugin, enter S3 bucket info, region, and AWS credentials.
3. Click Save, observe error.

### Expected behaviour
The bucket should be setup correctly without InvalidArgumentExceptions.
Note that the open_basedir restriction works fine for the rest of nextcloud.

### Actual behaviour
The admin interface throws an InvalidArgumentException.

### Server configuration

**Operating system:** Slackware Linux 14.2

**Web server:** Apache HTTPD 2.4.46

**Database:** MariaDB 10.4

**PHP version:** 7.3.23 (fpm)

**Nextcloud version:** 19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 18

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.1.8
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 4.1.5
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 3.0.1
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - bruteforcesettings
  - calendar
  - drawio
  - encryption
  - files_external_gdrive
  - files_frommail
  - gpxpod
  - mail
  - ocsms
  - ojsxc
  - ownnote
  - telephoneprovider
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "appcodechecker": false,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/www\/vhosts\/owl-ict.nl\/cloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "trusted_domains": [
            "cloud.owl-ict.nl"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "trashbin_retention_obligation": "7",
        "appstore.experimental.enabled": true,
        "htaccess.RewriteBase": "\/",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwrite.cli.url": "https:\/\/cloud.owl-ict.nl",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "drawio",
            "contacts",
            "calendar",
            "groupfolders",
            "files_external_gdrive",
            "twofactor_totp"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** local, trying to get S3 working

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Tried both Google Chrome 86.0, incognito tab and without, and Firefox 81.0.2

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>
Nothing
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"X41NTxtND-Fybi99iV8-6gAAVwM","level":3,"time":"2020-10-19T08:24:47+00:00","remoteAddr":"80.123.167.248","user":"myuser","app":"PHP","method":"PUT","url":"/apps/files_external/globalstorages/2","message":{"Exception":"Error","Message":"is_readable(): open_basedir restriction in effect. File(/home/www/.aws/config) is not within the allowed path(s): (/tmp:/www/vhosts/owl-ict.nl/cloud:/dev/urandom:/www/vhosts/owl-ict.nl/cloud-data) at /www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/S3/UseArnRegion/ConfigurationProvider.php#131","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":["*** sensitive parameter replaced ***","is_readable(): open_basedir restriction in effect. File(/home/www/.aws/config) is not within the allowed path(s): (/tmp:/www/vhosts/owl-ict.nl/cloud:/dev/urandom:/www/vhosts/owl-ict.nl/cloud-data)","/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/S3/UseArnRegion/ConfigurationProvider.php",131,{"profile":"default","filename":"/home/www/.aws/config"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/S3/UseArnRegion/ConfigurationProvider.php","line":131,"function":"is_readable","args":["/home/www/.aws/config"]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/guzzlehttp/promises/src/RejectedPromise.php","line":40,"function":"Aws\\S3\\UseArnRegion\\{closure}","class":"Aws\\S3\\UseArnRegion\\ConfigurationProvider","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":47,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\RejectedPromise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":246,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":223,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":267,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":225,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/S3/S3Client.php","line":406,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/ClientResolver.php","line":314,"function":"_apply_use_arn_region","class":"Aws\\S3\\S3Client","type":"::","args":[{"__class__":"GuzzleHttp\\Promise\\Promise"},{"version":"latest","credentials":{"__class__":"Closure"},"endpoint":"https://s3.eu-central-1.amazonaws.com:443/","region":"eu-central-1","use_path_style_endpoint":"*** sensitive parameter replaced ***","signature_provider":{"__class__":"Closure"},"csm":{"__class__":"Aws\\ClientSideMonitoring\\Configuration"},"s3_us_east_1_regional_endpoint":{"__class__":"Closure"},"service":"s3","exception_class":"Aws\\S3\\Exception\\S3Exception","config":{"signature_version":"s3v4","signing_name":"s3","signing_region":"eu-central-1"},"scheme":"https","disable_host_prefix_injection":"*** sensitive parameter replaced ***","api_provider":{"__class__":"Aws\\Api\\ApiProvider"},"api":{"__class__":"Aws\\Api\\Service"},"parser":{"__class__":"Aws\\S3\\GetBucketLocationParser"},"error_parser":{"__class__":"Aws\\Api\\ErrorParser\\XmlErrorParser"},"endpoint_provider":{"__class__":"Aws\\Endpoint\\Partition"},"serializer":{"__class__":"Aws\\Api\\Serializer\\RestXmlSerializer"},"__partition_result":"*** sensitive parameter replaced ***","signature_version":"s3v4","signing_name":"s3","signing_region":"eu-central-1","endpoint_discovery":{"__class__":"Closure"},"stats":{"http":"*** sensitive parameter replaced ***","retries":"*** sensitive parameter replaced ***","timer":"*** sensitive parameter replaced ***"},"retries":3,"validate":"*** sensitive parameter replaced ***","http":"*** sensitive parameter replaced ***","handler":{"__class__":"Aws\\WrappedHttpHandler"},"ua_append":["aws-sdk-php/3.133.27"],"idempotency_auto_fill":"*** sensitive parameter replaced ***","use_arn_region":{"__class__":"Closure"}},{"__class__":"Aws\\HandlerList"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/AwsClient.php","line":187,"function":"resolve","class":"Aws\\ClientResolver","type":"->","args":[{"version":"latest","credentials":{"__class__":"Closure"},"endpoint":"https://s3.eu-central-1.amazonaws.com:443/","region":"eu-central-1","use_path_style_endpoint":"*** sensitive parameter replaced ***","signature_provider":{"__class__":"Closure"},"csm":{"__class__":"Aws\\ClientSideMonitoring\\Configuration"},"s3_us_east_1_regional_endpoint":{"__class__":"Closure"},"service":"s3","exception_class":"Aws\\S3\\Exception\\S3Exception","config":{"signature_version":"s3v4","signing_name":"s3","signing_region":"eu-central-1"},"scheme":"https","disable_host_prefix_injection":"*** sensitive parameter replaced ***","api_provider":{"__class__":"Aws\\Api\\ApiProvider"},"api":{"__class__":"Aws\\Api\\Service"},"parser":{"__class__":"Aws\\S3\\GetBucketLocationParser"},"error_parser":{"__class__":"Aws\\Api\\ErrorParser\\XmlErrorParser"},"endpoint_provider":{"__class__":"Aws\\Endpoint\\Partition"},"serializer":{"__class__":"Aws\\Api\\Serializer\\RestXmlSerializer"},"__partition_result":"*** sensitive parameter replaced ***","signature_version":"s3v4","signing_name":"s3","signing_region":"eu-central-1","endpoint_discovery":{"__class__":"Closure"},"stats":{"http":"*** sensitive parameter replaced ***","retries":"*** sensitive parameter replaced ***","timer":"*** sensitive parameter replaced ***"},"retries":3,"validate":"*** sensitive parameter replaced ***","http":"*** sensitive parameter replaced ***","handler":{"__class__":"Aws\\WrappedHttpHandler"},"ua_append":["aws-sdk-php/3.133.27"],"idempotency_auto_fill":"*** sensitive parameter replaced ***","use_arn_region":{"__class__":"Closure"}},{"__class__":"Aws\\HandlerList"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/S3/S3Client.php","line":325,"function":"__construct","class":"Aws\\AwsClient","type":"->","args":[{"version":"latest","credentials":{"key":"**SENSITIVE VALUE!!!**","secret":"**SENSITIVE VALUE!!!**"},"endpoint":"https://s3.eu-central-1.amazonaws.com:443/","region":"eu-central-1","use_path_style_endpoint":"*** sensitive parameter replaced ***","signature_provider":{"__class__":"Closure"},"csm":"*** sensitive parameter replaced ***","s3_us_east_1_regional_endpoint":{"__class__":"Closure"},"service":"s3","exception_class":"Aws\\S3\\Exception\\S3Exception"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/Files/ObjectStore/S3ConnectionTrait.php","line":111,"function":"__construct","class":"Aws\\S3\\S3Client","type":"->","args":[{"version":"latest","credentials":{"key":"** SENSITIVE VALUE **","secret":"** SENSITIVE VALUE **"},"endpoint":"https://s3.eu-central-1.amazonaws.com:443/","region":"eu-central-1","use_path_style_endpoint":"*** sensitive parameter replaced ***","signature_provider":{"__class__":"Closure"},"csm":"*** sensitive parameter replaced ***","s3_us_east_1_regional_endpoint":{"__class__":"Closure"}}]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/Lib/Storage/AmazonS3.php","line":683,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\AmazonS3","type":"->","args":[]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/config.php","line":262,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\AmazonS3","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/Controller/StoragesController.php","line":257,"function":"getBackendStatus","class":"OC_Mount_Config","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/Controller/GlobalStoragesController.php","line":180,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_External\\Controller\\GlobalStoragesController"},"update"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_External\\Controller\\GlobalStoragesController"},"update"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_External\\Controller\\GlobalStoragesController","update",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"2","_route":"files_external.global_storages.update"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"2","_route":"files_external.global_storages.update"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"2","_route":"files_external.global_storages.update"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files_external/globalstorages/2"]},{"file":"/www/vhosts/owl-ict.nl/cloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/vhosts/owl-ict.nl/cloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","version":"19.0.4.2"}
{"reqId":"X41NTxtND-Fybi99iV8-6gAAVwM","level":3,"time":"2020-10-19T08:24:47+00:00","remoteAddr":"84.107.167.248","user":"myuser","app":"files_external","method":"PUT","url":"/apps/files_external/globalstorages/2","message":{"Exception":"InvalidArgumentException","Message":"Invalid configuration value provided for \"use_path_style_endpoint\". Expected bool, but got string(36) \"*** sensitive parameter replaced ***\"\n\nuse_path_style_endpoint: (bool)\n\n  Set to true to send requests to an S3 path style endpoint by default. Can\n  be enabled or disabled on individual operations by setting\n  '@use_path_style_endpoint' to true or false.","Code":0,"Trace":[{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/ClientResolver.php","line":309,"function":"invalidType","class":"Aws\\ClientResolver","type":"->","args":["use_path_style_endpoint","*** sensitive parameter replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/AwsClient.php","line":187,"function":"resolve","class":"Aws\\ClientResolver","type":"->","args":[{"version":"latest","credentials":{"__class__":"Closure"},"endpoint":"https://s3.eu-central-1.amazonaws.com:443/","region":"eu-central-1","use_path_style_endpoint":"*** sensitive parameter replaced ***","signature_provider":{"__class__":"Closure"},"csm":{"__class__":"Aws\\ClientSideMonitoring\\Configuration"},"s3_us_east_1_regional_endpoint":{"__class__":"Closure"},"service":"s3","exception_class":"Aws\\S3\\Exception\\S3Exception","config":{"signature_version":"s3v4","signing_name":"s3","signing_region":"eu-central-1","use_arn_region":{"__class__":"Aws\\S3\\UseArnRegion\\Configuration"},"use_accelerate_endpoint":"*** sensitive parameter replaced ***","use_dual_stack_endpoint":"*** sensitive parameter replaced ***"},"scheme":"https","disable_host_prefix_injection":"*** sensitive parameter replaced ***","api_provider":{"__class__":"Aws\\Api\\ApiProvider"},"api":{"__class__":"Aws\\Api\\Service"},"parser":{"__class__":"Aws\\S3\\GetBucketLocationParser"},"error_parser":{"__class__":"Aws\\Api\\ErrorParser\\XmlErrorParser"},"endpoint_provider":{"__class__":"Aws\\Endpoint\\Partition"},"serializer":{"__class__":"Aws\\Api\\Serializer\\RestXmlSerializer"},"__partition_result":"*** sensitive parameter replaced ***","signature_version":"s3v4","signing_name":"s3","signing_region":"eu-central-1","endpoint_discovery":{"__class__":"Closure"},"stats":{"http":"*** sensitive parameter replaced ***","retries":"*** sensitive parameter replaced ***","timer":"*** sensitive parameter replaced ***"},"retries":3,"validate":"*** sensitive parameter replaced ***","http":"*** sensitive parameter replaced ***","handler":{"__class__":"Aws\\WrappedHttpHandler"},"ua_append":["aws-sdk-php/3.133.27"],"idempotency_auto_fill":"*** sensitive parameter replaced ***","use_arn_region":{"__class__":"Aws\\S3\\UseArnRegion\\Configuration"},"use_accelerate_endpoint":"*** sensitive parameter replaced ***","use_dual_stack_endpoint":"*** sensitive parameter replaced ***"},{"__class__":"Aws\\HandlerList"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/S3/S3Client.php","line":325,"function":"__construct","class":"Aws\\AwsClient","type":"->","args":[{"version":"latest","credentials":{"key":"** SENSITIVE VALUE **","secret":"** SENSITIVE VALUE **"},"endpoint":"https://s3.eu-central-1.amazonaws.com:443/","region":"eu-central-1","use_path_style_endpoint":"*** sensitive parameter replaced ***","signature_provider":{"__class__":"Closure"},"csm":"*** sensitive parameter replaced ***","s3_us_east_1_regional_endpoint":{"__class__":"Closure"},"service":"s3","exception_class":"Aws\\S3\\Exception\\S3Exception"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/Files/ObjectStore/S3ConnectionTrait.php","line":111,"function":"__construct","class":"Aws\\S3\\S3Client","type":"->","args":[{"version":"latest","credentials":{"key":"** SENSITIVE VALUE **","secret":"** SENSITIVE VALUE **"},"endpoint":"https://s3.eu-central-1.amazonaws.com:443/","region":"eu-central-1","use_path_style_endpoint":"*** sensitive parameter replaced ***","signature_provider":{"__class__":"Closure"},"csm":"*** sensitive parameter replaced ***","s3_us_east_1_regional_endpoint":{"__class__":"Closure"}}]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/Lib/Storage/AmazonS3.php","line":683,"function":"getConnection","class":"OCA\\Files_External\\Lib\\Storage\\AmazonS3","type":"->","args":[]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/config.php","line":262,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\AmazonS3","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/Controller/StoragesController.php","line":257,"function":"getBackendStatus","class":"OC_Mount_Config","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/apps/files_external/lib/Controller/GlobalStoragesController.php","line":180,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"update","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_External\\Controller\\GlobalStoragesController"},"update"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_External\\Controller\\GlobalStoragesController"},"update"]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_External\\Controller\\GlobalStoragesController","update",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"2","_route":"files_external.global_storages.update"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"2","_route":"files_external.global_storages.update"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"2","_route":"files_external.global_storages.update"}]},{"file":"/www/vhosts/owl-ict.nl/cloud/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files_external/globalstorages/2"]},{"file":"/www/vhosts/owl-ict.nl/cloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/www/vhosts/owl-ict.nl/cloud/3rdparty/aws/aws-sdk-php/src/ClientResolver.php","Line":374,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","version":"19.0.4.2"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

![image](https://user-images.githubusercontent.com/165034/96419778-e36a0280-11f4-11eb-88e2-a374bdca4df0.png)

</details>

**Comment by inpakeo** [comment] 2020-12-26 23:29
Same problem, from api got answer 
statusMessage: "InvalidArgumentException: Invalid configuration value provided for "use_path_style_endpoint". Expected bool, but got string(36) "*** sensitive parameter replaced ***"↵↵use_path_style_endpoint: (bool)↵↵  Set to true to send requests to an S3 path style endpoint by default. Can↵  be enabled or disabled on individual operations by setting↵  '@use_path_style_endpoint' to true or false."

**Comment by Skoups** [comment] 2021-05-21 07:27
Ever since the system automatically updated to 21.0.1 SNAP version of nextcloud, this error seem to be back.  Prior to the update the mount was working just fine.

**Comment by szaimen** [comment] 2021-07-06 16:19
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by Brunni** [comment] 2021-08-02 21:06
I'm also having this issue:
`InvalidArgumentException: Invalid configuration value provided for \"use_path_style_endpoint\". Expected bool, but got string(36) `

I'm on a hosted nextcloud solution and therefore don't have access to the underlying file system or log files.

**Comment by acourter27** [comment] 2021-09-07 14:34
I am experiencing this issue with 21.0.4 still. Attached the error message.

![Screen Shot 2021-09-07 at 9 29 12 AM](https://user-images.githubusercontent.com/47721365/132363115-2e0d45d1-4d87-4feb-8783-92f6bf370bfe.png)

**Comment by pmisner** [comment] 2021-10-14 02:01
Getting this error as well. The unusual thing is that the Android app accepts the bucket.

**Comment by szaimen** [comment] 2023-01-23 10:22
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:41 UTC
Labels: bug, needs info, 0. Needs triage, feature: object storage
