### ISSUE TITLE
[Bug]: In the application menu bar, some application hrefs are empty

### ISSUE THREAD

**Issue by callmemagnus** [nextcloud/server#46269] opened 2024-07-03 07:15 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On my Nextcloud 29.0.3, the menu links (href) of some applications are empty.

See the screenshot of the generated menu code:

![image](https://github.com/nextcloud/server/assets/232478/42ddbe40-fa89-41cc-aded-20ca8befc155)

When the user click, it just reloads the page.

### Steps to reproduce

1. Open a nextcloud page
2. Hover on the menu bar icons
3. See the url.

### Expected behavior

The urls should be the one of the respective applications.

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{   
    "system": {
        "maintenance_window_start": 1,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.3.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "cloud.magooweb.com",
            "cloud.home"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "calendar",
            "issuetemplate",
            "files_fulltextsearch_tesseract"
        ],
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "apps_paths": [
            {   
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {   
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "default_phone_region": "CH",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwrite.cli.url": "https:\/\/cloud.magooweb.com",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "cloud.magooweb.com",
        "overwriteprotocol": "https",
        "overwritecondaddr": "^172\\.",
        "trashbin_retention_obligation": "auto, 180",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "memories.db.triggers.fcu": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bookmarks: 14.2.2
  - bruteforcesettings: 2.9.0
  - cloud_federation_api: 1.12.0
  - contacts: 6.0.0
  - dav: 1.30.1
  - duplicatefinder: 1.1.10
  - federatedfilesharing: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_fulltextsearch: 29.0.0
  - files_fulltextsearch_tesseract: 27.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - fulltextsearch: 29.0.0
  - fulltextsearch_elasticsearch: 29.0.1
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - memories: 7.3.1
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - quicknotes: 0.8.23
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - theming_customcss: 1.16.0
  - thesearchpage: 1.2.7
  - timemanager: 0.3.14
  - twofactor_backupcodes: 1.18.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 11.0.0-dev
  - unroundedcorners: 1.1.3
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - apporder: 0.15.0 (installed 0.15.0)
  - calendar: 4.7.8 (installed 4.7.8)
  - circles: 29.0.0-dev (installed 23.0.1)
  - comments: 1.19.0 (installed 1.11.0)
  - contactsinteraction: 1.10.0 (installed 1.3.0)
  - dashboard: 7.9.0 (installed 7.7.0)
  - deck: 1.13.1 (installed 1.13.1)
  - encryption: 2.17.0
  - federation: 1.19.0 (installed 1.1.1)
  - files_automatedtagging: 1.19.0 (installed 1.19.0)
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.18.0 (installed 1.0)
  - issuetemplate: 0.7.0 (installed 0.7.0)
  - nextcloud_announcements: 1.18.0 (installed 1.7.0)
  - password_policy: 1.19.0 (installed 1.12.0)
  - recommendations: 2.1.0 (installed 0.6.0)
  - sharebymail: 1.19.0 (installed 1.8.0)
  - support: 1.12.0 (installed 1.1.0)
  - suspicious_login: 7.0.0
  - updatenotification: 1.19.1 (installed 1.8.0)
  - user_ldap: 1.20.0
  - user_status: 1.9.0 (installed 1.2.0)
  - weather_status: 1.9.0 (installed 1.2.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"kjfqQHt5tZfYsgeScp3S","level":1,"time":"2024-07-03T07:07:44+00:00","remoteAddr":"172.16.1.7","user":"magnus","app":"no app in context","method":"GET","url":"/apps/serverinfo/update","message":"Unable to generate a URL for the named route \"thesearchpage.page.index\" as such route does not exist.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0","version":"29.0.3.4","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"thesearchpage.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Route/Router.php","line":410,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["thesearchpage.page.index",[],1]},{"file":"/var/www/html/lib/private/Route/CachingRouter.php","line":65,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["thesearchpage.page.index",[],false]},{"file":"/var/www/html/lib/private/URLGenerator.php","line":103,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["thesearchpage.page.index",[]]},{"file":"/var/www/html/lib/private/NavigationManager.php","line":371,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["thesearchpage.page.index"]},{"file":"/var/www/html/lib/private/NavigationManager.php","line":97,"function":"init","class":"OC\\NavigationManager","type":"->","args":[]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/AppInfo/Application.php","line":125,"function":"add","class":"OC\\NavigationManager","type":"->","args":[["fulltextsearch",5,"/apps/fulltextsearch/","/custom_apps/fulltextsearch/img/fulltextsearch.svg","Search"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":45,"function":"registerNavigation","class":"OCA\\FullTextSearch\\AppInfo\\Application","type":"->","args":[["OC\\Server"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php","line":50,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->","args":[["Closure"]]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/AppInfo/Application.php","line":88,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->","args":[["Closure"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\FullTextSearch\\AppInfo\\Application","type":"->","args":[["OC\\AppFramework\\Bootstrap\\BootContext"]]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":437,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["fulltextsearch"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->","args":["fulltextsearch"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":128,"function":"loadApps","class":"OC\\App\\AppManager","type":"->","args":[[]]},{"file":"/var/www/html/lib/base.php","line":1030,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":144,"message":"Unable to generate a URL for the named route \"thesearchpage.page.index\" as such route does not exist.","exception":{},"CustomMessage":"Unable to generate a URL for the named route \"thesearchpage.page.index\" as such route does not exist."}}
```

### Additional info

In the log section, I only added one line that is relevant to the issue (and it is my plugin). There is one of those lines per broken link.

I tried to see if the route declaration were different but it is the same data structure.

I noticed this because of a bug on my application (https://github.com/callmemagnus/nextcloud-searchpage/issues/37)

**Comment by callmemagnus** [comment] 2024-07-03 12:43
Some closed issue relates to https://github.com/nextcloud/fulltextsearch/issues/842.

**Comment by joshtrichards** [comment] 2024-07-03 14:52
Yes, it's that FTS matter.

Disable the *Navigation Icon* option in FTS and it'll go away (as a workaround) for the time being until someone can find the time to figure out why FTS is causing this behavior with v29. I can't think of another app off-hand that supports dynamic navigation registering to compare it against.

That stack trace looks quite helpful for tracking this down.

Duplicate of nextcloud/fulltextsearch#842

**Closed by joshtrichards** 2024-07-03 14:52 UTC
Labels: bug, 0. Needs triage
