### ISSUE TITLE
Jump to file in file list after clicking on search results

### ISSUE THREAD

**Issue by AInteriorB** [nextcloud/server#15260] opened 2019-04-27 11:52 UTC
In NC < 14 one was able to jump directly to the chosen file in folder list after clicking on a search result. This is important, if you have lots of files in a folder. Now, only the folder and file inspector is opened. There you are not able to download the file or open the file in the pdf viewer. You have to scroll all the way down to find the file yourself.

### Steps to reproduce
1. search for a file
2. click on a result
3. folder (where file is located) and file inspector is opened

### Expected behaviour
Scroll to the file position in the list

### Actual behaviour
List stays at top

### Server configuration

**Operating system**: Debian 10
**Web server:** Apache/2.4.38
**Database:** MariaDB 10.3.14
**PHP version:** PHP 7.3.4
**Nextcloud version:** 16.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** update
**Where did you install Nextcloud from:** web updater

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - audioplayer: 2.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - user_ldap
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

**Comment by AInteriorB** [comment] 2019-05-16 08:55
cc @skjnldsv @blizzz @MorrisJobke

**Comment by AInteriorB** [comment] 2019-06-14 06:18
Nothing new on that, @skjnldsv @MorrisJobke ? That's really annoying when you have a long list of files in one folder. The search finds your file but you have to scroll all the way down manually to locate it actually.

**Comment by skjnldsv** [comment] 2019-06-14 06:22
@AInteriorB the file list require quite a lot of fixes and we're lacking time to do it :(

**Comment by szaimen** [comment] 2021-05-26 08:41
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-26 08:41 UTC
Labels: 1. to develop, bug, feature: files
