### ISSUE TITLE
9.4.1.2/3.3 In the table, in the "Name" column, there are elements that have been marked as favorites with a star icon. However, the implementation for screen reader users is flawed because the "aria-label" attribute is erroneously used on the "span" element, which is not allowed - <span aria-label="Favorite" class="files-list__row-icon-favorite">.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42230] opened 2023-12-13 14:08 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v3-n3

9.4.1.2/3.3 In the table, in the "Name" column, there are elements that have been marked as favorites with a star icon. However, the implementation for screen reader users is flawed because the "aria-label" attribute is erroneously used on the "span" element, which is not allowed - <span aria-label="Favorite" class="files-list__row-icon-favorite">.

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:49
duplicate of https://github.com/nextcloud/server/issues/41891

**Closed by JuliaKirschenheuter** 2023-12-14 10:49 UTC
Labels: accessibility
