### ISSUE TITLE
Admin User can't change a users mailadress if 'allow_user_to_change_display_name' is set to false

### ISSUE THREAD

**Issue by tsfuchs** [nextcloud/server#8949] opened 2018-03-22 16:44 UTC
### Steps to reproduce
1. Admin User tries to change a users mailadress in the user list
2. Message "E-Mail adress could not be changed" appears
3. Set value for 'allow_user_to_change_display_name' to true
4. Admin can change the mail adress

### Server configuration

**Operating system**:
Ubuntu server 16.04

**Web server:**
Apache 2.4

**Database:**
Mariadb

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated and migrated from owncloud since 6.x

**Comment by skjnldsv** [comment] 2018-03-23 07:10
Duplicate of #642

**Closed by skjnldsv** 2018-03-23 07:10 UTC
