### ISSUE TITLE
[Feature Improvement] Apps section, search, "all"

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/server#9190] opened 2018-04-15 02:45 UTC
When I'm trying to find an app to enable, it's really frustrating when I don't know how it's categorised, so I try to search for it. But then when I try to search, it only searches in the category I have selected.

I really would like it if we could have a "search all" method, whereby anything matching the search terms, in any of the categories, is presented.

Please?

**Comment by MorrisJobke** [comment] 2018-04-16 21:57
Duplicate of https://github.com/nextcloud/server/issues/6868 and https://github.com/nextcloud/server/issues/126

**Closed by MorrisJobke** 2018-04-16 21:57 UTC
