### ISSUE TITLE
[Bug]: Php-fpm processes stay after playing large video files.

### ISSUE THREAD

**Issue by matsushita-shuya** [nextcloud/server#39560] opened 2023-07-25 04:11 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Php-fpm processes stays and don't disappear after specific actions such as playing large video files, moving seek bars and loading a number of photos and that caused request timeouts.
Then I received php error messages saying "server reached pm.max_children setting".

### Steps to reproduce

Playing a large video file like over 1GB, moving seek bar of a large video file or loading a number of thumbnails of photos.

### Expected behavior

I expect php-fpm processes to disappear after playing large video files, moving seek bar of those and loading a number of thumbnails of photos.

### Installation method

None

### Nextcloud Server version

25

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
        "system": {
            "instanceid": "***REMOVED SENSITIVE VALUE***",
            "passwordsalt": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "trusted_domains": [
                "*"
            ],
            "datadirectory": "***REMOVED SENSITIVE VALUE***",
            "default_phone_region": "JP",
            "overwrite.cli.url": "*",
            "overwriteprotocol": "https",
            "overwritehost": "*",
            "overwritewebroot": "*",
            "dbtype": "mysql",
            "version": "25.0.6.1",
            "dbname": "***REMOVED SENSITIVE VALUE***",
            "dbhost": "***REMOVED SENSITIVE VALUE***",
            "dbport": "",
            "dbtableprefix": "oc_",
            "mysql.utf8mb4": true,
            "dbuser": "***REMOVED SENSITIVE VALUE***",
            "dbpassword": "***REMOVED SENSITIVE VALUE***",
            "installed": true,
            "maintenance": false,
            "log_type": "*",
            "logfile": "*",
            "loglevel": 1,
            "logtimezone": "Asia\/Tokyo",
            "logdateformat": "*",
            "memcache.local": "\\OC\\Memcache\\APCu",
            "theme": "",
            "auth.bruteforce.protection.enabled": false,
            "integrity.check.disabled": true,
            "mail_smtpmode": "smtp",
            "mail_from_address": "***REMOVED SENSITIVE VALUE***",
            "mail_domain": "***REMOVED SENSITIVE VALUE***",
            "mail_smtpauthtype": "",
            "mail_smtpauth": 1,
            "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
            "mail_smtpport": "*",
            "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
            "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
            "ldapIgnoreNamingRules": false,
            "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
            "updater.release.channel": "stable",
            "app_install_overwrite": [
                "*"
            ],
            "trashbin_retention_obligation": "auto, 14"
        }
    }
```

### List of activated Apps

```shell
Enabled:
    - activity: 2.17.0
    - admin_audit: 1.15.0
    - cloud_federation_api: 1.8.0
    - comments: 1.15.0
    - contactsinteraction: 1.6.0
    - dav: 1.24.0
    - federatedfilesharing: 1.15.0
    - files: 1.20.1
    - files_external: 1.17.0
    - files_pdfviewer: 2.6.0
    - files_sharing: 1.17.0
    - files_trashbin: 1.15.0
    - files_versions: 1.18.0
    - firstrunwizard: 2.14.0
    - groupfolders: 13.1.2
    - logreader: 2.10.0
    - lookup_server_connector: 1.13.0
    - nextcloud_announcements: 1.14.0
    - notifications: 2.13.1
    - oauth2: 1.13.0
    - photos: 2.0.1
    - privacy: 1.9.0
    - provisioning_api: 1.15.0
    - related_resources: 1.0.4
    - serverinfo: 1.15.0
    - settings: 1.7.0
    - systemtags: 1.15.0
    - text: 3.6.0
    - theming: 2.0.1
    - twofactor_backupcodes: 1.14.0
    - updatenotification: 1.15.0
    - user_ldap: 1.15.0
    - viewer: 1.9.0
    - workflowengine: 2.7.0
  Disabled:
    - bruteforcesettings: 1.0.3
    - circles: 24.0.1
    - dashboard: 7.1.0
    - encryption
    - federation: 1.14.0
    - files_rightclick: 0.15.1
    - password_policy: 1.2.2
    - recommendations: 1.3.0
    - sharebymail: 1.2.0
    - support: 1.4.0
    - survey_client: 1.1.0
    - suspicious_login
    - twofactor_totp
    - user_status: 1.1.1
    - weather_status: 1.1.0
```

**Comment by joshtrichards** [comment] 2023-07-25 14:49
Hi @matsushita-shuya - This is a likely local configuration matter. The rest of that error message typically says a number (often 5 since it's the ancient php-fpm default) and informs the operator to consider raising it. As for the processes sticking around, that is similarly a configuration matter. It'll depend on the settings for pm.max_requests, pm.process_idle_timeout, and pm (among others) for your PHP-FPM pool.

https://www.php.net/manual/en/install.fpm.configuration.php#pm
https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#tune-php-fpm

There's probably some room for improve in the NC Admin Manual on this topic to provide some better general guidance on the matter. Right now there are hints spread around in a few places.

If you're stuck, I suggest searching and/or posting over at the [Nextcloud Help Forum](https://help.nextcloud.com/).

**Comment by kesselb** [comment] 2023-08-01 08:40
Closing as duplicate of https://github.com/nextcloud/server/issues/19567. 

Should be fixed with Nextcloud 28.

**Closed by kesselb** 2023-08-01 08:40 UTC
Labels: bug, 0. Needs triage, 25-feedback
