### ISSUE TITLE
[bug] Interaction between Thunderbird and NC when accepting invites might result in error 80004005.

### ISSUE THREAD

**Issue by madduck** [nextcloud/server#40599] opened 2023-09-23 14:51 UTC
When NC sends out invitations with server-side scheduling, the invitee receives an email with both, an ICS invite, and a link to accept the invitation, which contacts the server.

If the recipient clicks the button, the server marks them as attending (or not).

If the recipient then also tries to accept or decline the event against an NC-hosted calendar, error 80004005 is shown, because the event to be sync'd no longer corresponds to the state at the server, because the button was clicked.

If the recipient manually synchronises the calendar and *then* accepts or declines, no error is produced.

This leads me to believe the two are related. Maybe the server could ignore the previous accept/decline in this case?

Or maybe it should cache any button clicks for e.g. 15 minutes and only apply the effect to the event if the event hasn't changed lately?

**Comment by sascha-wi** [comment] 2023-10-25 08:58
Any news here?

**Comment by ChristophWurst** [comment] 2024-01-16 07:59
Dup of https://github.com/nextcloud/server/issues/17915?

**Comment by joshtrichards** [comment] 2024-09-22 12:45
Duplicate of #17915

**Closed by joshtrichards** 2024-09-22 12:45 UTC
Labels: enhancement, 0. Needs triage, feature: caldav
