### ISSUE TITLE
[Bug]: Workflow for new releases

### ISSUE THREAD

**Issue by csware** [nextcloud/server#45691] opened 2024-06-06 10:38 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I just got notified that a new version of Nextcloud is available (29.0.2).

However, the linked changelog (https://nextcloud.com/changelog/#29-0-2) does not contain an entry for 29.0.2 and also on GitHub there is no release for 29.0.2 available.

Please improve the workflow so that this information is available when the update is pushed.

### Steps to reproduce

1) Open the updater and click on the changelog link.

### Expected behavior

The changelog is available for 29.0.2.

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment] 2024-06-06 10:57
Duplicate of https://github.com/nextcloud/server/issues/31198

**Closed by kesselb** 2024-06-06 10:57 UTC
Labels: bug, 0. Needs triage
