### ISSUE TITLE
Undefined index: redirect_url at /var/www/html/core/templates/twofactorshowchallenge.php#24	

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2376] opened 2016-11-28 14:14 UTC
```
Undefined index: redirect_url at /var/www/html/core/templates/twofactorshowchallenge.php#24	
Undefined index: backup_codes at /var/www/html/lib/private/Authentication/TwoFactorAuth/Manager.php#109	
```

cc @ChristophWurst

**Comment by MorrisJobke** [comment] 2016-11-28 14:19
> Undefined index: backup_codes at /var/www/html/lib/private/Authentication/TwoFactorAuth/Manager.php#109

Fixed in #2361

**Comment by ChristophWurst** [comment] 2016-11-28 15:51
> Undefined index: redirect_url at /var/www/html/core/templates/twofactorshowchallenge.php#24

Any special steps to reproduce this? I visited the u2f challenge page but nothing was logged to nextcloud.log. The 'redirect_url' url parameter was not set.

**Comment by rullzer** [comment] 2016-11-30 13:06
So... fixed?

**Comment by ChristophWurst** [comment] 2016-11-30 14:24
I fixed the second error and could not reproduce the first. Maybe it was fixed too? Not sure.

**Comment by MorrisJobke** [comment] 2016-11-30 15:04
I also can't see the first one anymore -> let's close this then.

**Comment by abysso2** [comment] 2016-12-13 14:26
Still there after an upgrade from 10.0.2 to 11.0.0:

Undefined index: redirect_url at /var/www/nextcloud/core/templates/twofactorshowchallenge.php#24

Server: Trusty Tahr
PHP:     php7.0                               7.0.14-1+deb.sury.org~trusty+1       all 


Thx,
Andreas

**Comment by ChristophWurst** [comment] 2016-12-13 14:28
Hi @abysso2,

could you please tell me when exactly that warning pops up? E.g. which URL was visited?

**Comment by abysso2** [comment] 2016-12-13 14:33
First:
Commenting out the line  'redirect_url' => $_['redirect_url'], in /var/www/nextcloud/core/templates/twofactorshowchallenge.php lets the error disappear ...

**Comment by abysso2** [comment] 2016-12-13 14:38
Second:
When pressing the "Einloggen"-Button at [URL]/index.php/login, the site switches to [URL]/index.php/login/challenge/totp.

Within this cick, the log throws the error:

{"reqId":"XXXXXXXXXXXXXXXXXXXXX","remoteAddr":"MyIP","app":"admin_audit","message":"Login attempt: \"andreas\"","level":1,"time":"2016-12-13T15:35:57+01:00","method":"POST","url":"\/index.php\/login","user":"--","version":"11.0.0.10"}
{"reqId":"XXXXXXXXXXXXXXXXXX","remoteAddr":"MyIP","app":"admin_audit","message":"Login successful: \"andreas\"","level":1,"time":"2016-12-13T15:35:57+01:00","method":"POST","url":"\/index.php\/login","user":"andreas","version":"11.0.0.10"}
{"reqId":"XXXXXXXXXXXXXXXXXXXXXXX","remoteAddr":"MyIP","app":"PHP","message":"Undefined index: redirect_url at \/var\/www\/nextcloud\/core\/templates\/twofactorshowchallenge.php#24","level":3,"time":"2016-12-13T15:35:57+01:00","method":"GET","url":"\/index.php\/login\/challenge\/totp","user":"andreas","version":"11.0.0.10"}


Grettings,
Andreas

**Comment by abysso2** [comment] 2016-12-13 14:40
Do you need any further information?

**Comment by ChristophWurst** [comment] 2016-12-13 14:50
> When pressing the "Einloggen"-Button at [URL]/index.php/login, the site switches to [URL]/index.php/login/challenge/totp.

I think I know why I could not reproduce it. When I tested it I had multiple 2FA providers, therefore I was redirected to the selection screen, not the TOTP provider. Will test this again. Thanks for your quick feedback :-)

**Comment by abysso2** [comment] 2016-12-13 15:16
So, there is no risk / issue to comment out the line 

'redirect_url' => $_['redirect_url'], in /var/www/nextcloud/core/templates/twofactorshowchallenge.php

???

Thx,
Andreas

**Closed** 2016-12-28 15:28 UTC
Labels: bug
