### ISSUE TITLE
[Feature Request] Apps should link to their own Settings-Section

### ISSUE THREAD

**Issue by fwolfst** [nextcloud/server#9753] opened 2018-06-05 15:13 UTC
In form of a user/administrator-Story. Its an UI issue.
Please note that I could not find any guideline on how and where to propose Features best. I hope a github-issue is the right choice

### Steps to experience
1. (As admin) visit the Apps-Section of your nextcloud instance (I have only NC 13.0.2 at hand)
2. Remember that actually you did not want to install an App but configure it
3. Visit on the "Settings" Section instead and find and search the correct Settings-section

### Cool experience would be
1. (As admin) visit the Apps-Section of your nextcloud instance
2. See a "Settings"-link/icon next to each enabled App, which kicks you to the correct Settings-Section on click.

**Nextcloud version:** 13.0.2

I am not familar with App-Development but I assume it would need some further meta-data-like fields or hooks to insert the correct link.

**Comment by MorrisJobke** [comment] 2018-06-06 08:44
Duplicate of #1062

**Closed by MorrisJobke** 2018-06-06 08:44 UTC

**Comment by fwolfst** [comment] 2018-06-06 09:56
@MorrisJobke Thanks for spotting. I searched the issues before, but did not went back to 2016.
