### ISSUE TITLE
Data usage shown in webinterface differs from actual filesystem storage usage

### ISSUE THREAD

**Issue by lug-gh** [nextcloud/server#16255] opened 2019-07-05 13:10 UTC
### Steps to reproduce
1. have a user with data
2. look up data usage under cloud.example.org/settings/users
3. look up data usage under $nextclouddatadir/username
4. compare both values

### Expected behaviour
Data usage should be the same
![image](https://user-images.githubusercontent.com/24546639/60724288-49feda80-9f36-11e9-8223-e4d585c2b6f7.png)

### Actual behaviour
data usage shown in webinterface is different from the actual data usage
![image](https://user-images.githubusercontent.com/24546639/60724332-6438b880-9f36-11e9-8f52-1214e8959f0a.png)

### Server configuration

**Operating system**:  ubuntu 16.04.5

**Web server:** nginx

**Database:** mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

**PHP version:** PHP 7.3.5-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:00:05) ( NTS )

**Nextcloud version:** (see Nextcloud admin page) 16.0 (tried 16.0.2 too but it had the same issue, so i did a rollback)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since nextcloud 13 iirc

**Where did you install Nextcloud from:** zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
no errors
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - drawio: 0.9.3
  - encryption: 2.4.0
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.1
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.3.0
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - end_to_end_encryption
  - federation
  - files_external
  - twofactor_rcdevsopenotp
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** local

### Client configuration
**Browser:** chrome 75

**Operating system:** win10

#### Web server error log
there are no errors

**Comment by lug-gh** [comment] 2019-07-18 15:01
can noone deny nor confirm this?

**Comment by lug-gh** [comment] 2019-11-20 13:08
it's almost half a year now, and not a single reply... :(

**Comment by szaimen** [comment] 2021-05-27 11:38
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by lug-gh** [comment] 2021-05-27 11:52
I checked it just now on two different installations (nc19 manual install + nc20 snap), and yes, still valid.

**Comment by szaimen** [comment] 2021-05-27 11:54
Based on your report aren't you using encryption for your files? Is that correct?

**Comment by lug-gh** [comment] 2021-05-27 12:06
Okay I missed that, but the answer is yes and no :)

NC19 is without encryption (and thats what this report is based onm it was 16 back then) and the nc21 snap is with encryption.
The difference with encryption is way bigger, e.g. 8,5GB on webinterface, 12GB on filesystem. (+40% overhead for encryption?)

On NC19 without encryption the difference is smaller, e.g. 41,3GB on webinterface, 45GB on filesystem. (+9%)

It's all just about the "files" folder, not inlcuding trashbin etc.

**Comment by szaimen** [comment] 2021-05-27 12:09
Yes, it is a known issue for encrypted files.
Based on your report I see that you are using local external storage. Is that corret?

**Comment by szaimen** [comment] 2021-05-27 13:06
I think for encryption will this will be hard to fix because of the used encryption algorithm.
For normal storage it might be fixable, though.

---

cc @nextcloud/server-triage Any ideas what could be wrong here?

**Comment by skjnldsv** [comment] 2021-05-27 13:17
> By issue you mean a fixable error, or something we all have to live with by design?

By design.
Encryption needs to store more space than they really are. You can check the docs :)

**Closed by skjnldsv** 2021-05-27 13:17 UTC
Labels: 0. Needs triage, bug, needs info

**Comment by lug-gh** [comment] 2021-05-28 07:06
@skjnldsv I understand, but this issue is not about encryption, we only came to the subject in passing.

So did you close this on purpose or by mistake?
