### ISSUE TITLE
[Bug]: NC24.0.0 beta2 webupdate error message not markable for copy

### ISSUE THREAD

**Issue by g6094199** [nextcloud/server#31810] opened 2022-04-03 10:10 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

while update to beta2 in ran into an invalidargumentexpection. 
for creating an bug report i tried to copy the error message form the updater status page but the text is NOT markable. this not userfriendly at all. plz make the texts markable.

![Bildschirmfoto vom 2022-04-03 12-07-46](https://user-images.githubusercontent.com/37833326/161422426-431a46ad-0741-4ca8-b913-daf2de0583b8.png)

### Steps to reproduce

1.
2.
3.

### Expected behavior

error messages dhould be markable for copy

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - audioplayer: 3.3.0
  - calendar: 3.2.2
  - circles: 24.0.0-alpha1
  - cloud_federation_api: 1.7.0
  - contacts: 4.1.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - lookup_server_connector: 1.12.0
  - mail: 1.11.7
  - maps: 0.1.10
  - news: 18.0.1-beta2
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - photos: 1.6.0
  - polls: 3.5.4
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - tasks: 0.14.4
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit
  - breezedark: 23.2.1
  - bruteforcesettings: 2.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - encryption: 1.0.0
  - files_antivirus: 3.2.2
  - firstrunwizard: 1.1
  - geoblocker: 0.5.4
  - integration_moodle: 1.0.2
  - logreader: 2.5.0
  - music: 1.5.1
  - ocsms: 2.2.0
  - password_policy: 1.4.0
  - recommendations: 0.8.0
  - serverinfo: 1.9.0
  - sharebymail: 1.10.0
  - spreed: 13.0.4
  - support: 1.3.0
  - survey_client: 1.7.0
  - suspicious_login: 4.1.0
  - systemtags: 1.10.0
  - talk_matterbridge: 1.23.2
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_nextcloud_notification: 3.3.1
  - twofactor_u2f: 6.3.0
  - user_ldap
  - user_status: 1.0.1
```

**Comment by szaimen** [comment] 2022-04-03 10:19
duplicate of https://github.com/nextcloud/server/issues/31810

**Closed by szaimen** 2022-04-03 10:19 UTC
Labels: bug, 0. Needs triage

**Comment by g6094199** [comment] 2022-04-03 10:25
hi

this is NOT a bugreport on the invalidargumentexeption. this is about that the error text is NOT MARKABLE for copying. u didnt read correctly or linked to the wrong bug report. as of now this is NOT a duplicate!

**Comment by noci2012** [comment] 2022-04-03 18:05
Another nice one...

Updating <user_ldap> ...
OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column '4000' in 'where clause'
Update failed
Maintenance mode is kept active
