### ISSUE TITLE
log spam open_basedir

### ISSUE THREAD

**Issue by Tealk** [nextcloud/server#27934] opened 2021-07-13 07:07 UTC
## Server configuration detail

**Operating system:** Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64

**Webserver:** nginx/1.14.2 (fpm-fcgi)

**Database:** mysql 10.5.11

**PHP version:** 

8.0.8
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 22.0.0 - 22.0.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.15.0
 - admin_audit: 1.11.0
 - apporder: 0.13.0
 - approval: 1.0.2
 - calendar: 2.3.0
 - checksum: 1.1.2
 - circles: 22.0.0
 - cloud_federation_api: 1.4.0
 - collectives: 0.9.22
 - comments: 1.11.0
 - contacts: 4.0.0
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.18.0
 - deck: 1.5.0
 - event_update_notification: 1.3.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_markdown: 2.3.4
 - files_pdfviewer: 2.3.0
 - files_rightclick: 1.1.0
 - files_sharing: 1.13.2
 - files_texteditor: 2.14.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - groupfolders: 9.0.2
 - guests: 2.0.0
 - integration_github: 1.0.1
 - integration_gitlab: 1.0.1
 - integration_mastodon: 1.0.1
 - integration_whiteboard: 0.0.14
 - integration_zammad: 1.0.2
 - issuetemplate: 0.7.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.9.0
 - maps: 0.1.9
 - nextcloud_announcements: 1.11.0
 - notifications: 2.10.1
 - oauth2: 1.9.0
 - onlyoffice: 7.0.4
 - password_policy: 1.12.0
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.11.0
 - ransomware_protection: 1.11.0
 - serverinfo: 1.12.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - sociallogin: 4.6.17
 - spreed: 12.0.0
 - survey_client: 1.10.0
 - systemtags: 1.11.0
 - text: 3.3.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.1
 - twofactor_totp: 6.1.0
 - twofactor_u2f: 6.2.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.6.0
 - workflow_script: 1.7.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - files_downloadactivity
 - files_external
 - forms
 - polls
 - previewgenerator
 - quota_warning
 - recommendations
 - support
 - tasks
 - twofactor_nextcloud_notification
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "anzah.cloud"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/anzah.cloud",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "22.0.0.11",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "installed": true,
    "maintenance": false,
    "default_language": "de",
    "default_locale": "de",
    "default_phone_region": "DE",
    "allow_user_to_change_display_name": true,
    "knowledgebaseenabled": false,
    "theme": "",
    "defaultapp": "apporder",
    "skeletondirectory": "\/var\/customers\/webs\/Anzah\/anzah.cloud\/core\/skeleton",
    "trashbin_retention_obligation": "120, auto",
    "versions_retention_obligation": "120, auto",
    "appcodechecker": true,
    "updatechecker": true,
    "updater.release.channel": "stable",
    "check_for_working_webdav": true,
    "loglevel": 3,
    "logdateformat": "d.m.Y H:i:s",
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 10485760,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_filesize_image": 50,
    "preview_max_scale_factor": 10,
    "data-fingerprint": "01b9630d063ba580c331de332a0ab360",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 10,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "apporder",
        "circles",
        "groupfolders",
        "whiteboard",
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
[PHP] Error: is_file(): open_basedir restriction in effect. File(/l10n/en.js) is not within the allowed path(s): (/var/customers/webs/Anzah/anzah.cloud:/var/customers/tmp/Anzah:/usr/share/php:/usr/share/php5:/tmp:/var/customers/webs/Anzah/anzah.cloud_files:/dev/urandom) at /var/customers/webs/Anzah/anzah.cloud/lib/private/Template/ResourceLocator.php#105

GET /index.php/settings/admin/logging
from 212.211.191.216 by Tealk at 2021-07-13T09:00:09+02:00

[PHP] Error: file_exists(): open_basedir restriction in effect. File(/templates/) is not within the allowed path(s): (/var/customers/webs/Anzah/anzah.cloud:/var/customers/tmp/Anzah:/usr/share/php:/usr/share/php5:/tmp:/var/customers/webs/Anzah/anzah.cloud_files:/dev/urandom) at /var/customers/webs/Anzah/anzah.cloud/lib/private/Template/Base.php#68

GET /index.php/login
from 54.161.116.231 at 2021-07-13T09:00:45+02:00
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by kesselb** [comment] 2021-07-13 08:15
Duplicate of https://github.com/nextcloud/server/issues/27759

**Closed by kesselb** 2021-07-13 08:15 UTC
Labels: 0. Needs triage, bug
