### ISSUE TITLE
[Bug]: `occ config:list system` discloses sensitive data

### ISSUE THREAD

**Issue by martin-rueegg** [nextcloud/server#40388] opened 2023-09-12 14:41 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

While `occ config:list system` does mask some senstive data, the at least following keys contain the domain name:

- `system`
  - `trusted_domains`
     - `*`
  - `overwrite.cli.url`

(they have been masked with `***NON-REMOVED SENSITIVE VALUE***` in the output below.)

Given the combination of the domain name and the version information of the installed nextcloud software could inform a malicious party about possible attack vectors. 

### Steps to reproduce

1. Make sure you have the above mentioned keys set in your `config.php`
2. run `occ config:list system`

### Expected behavior

Any domain name should be masked.

The above mentioned keys contain the domain name.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- Default user-backend _(database)_

### Configuration report

```shell
./occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***NON-REMOVED SENSITIVE VALUE***"
        ],
        "overwrite.cli.url": "***NON-REMOVED SENSITIVE VALUE***",
        "default_phone_region": "CH",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Zurich",
        "logfile_audit": "\/var\/log\/nextcloud\/audit.log",
        "dbtype": "mysql",
        "version": "26.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "installed": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "theme": "",
        "appstore.experimental.enabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "app_install_overwrite": [
        ],
        "updater.release.channel": "stable",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false
    }
}
```

**Comment by joshtrichards** [comment] 2023-09-13 19:56
Duplicate of #12925 (among others)

Tracking discussion/progress mostly moved to nextcloud/issuetemplate#27

See https://github.com/nextcloud/issuetemplate/issues/27#issuecomment-542179026 for background/context.

Feel free to subscribe yourself to that open issue.

**Closed by joshtrichards** 2023-09-13 19:56 UTC
Labels: bug, 0. Needs triage, feature: occ, privacy, 26-feedback

**Comment by martin-rueegg** [comment] 2023-09-13 20:12
I see. Thanks, @joshtrichards. I tried to filter for any existing issue but would either get no result, or over 1200, given that the string config:list is existing in so many issues. Sorry for the duplicate.

**Comment by joshtrichards** [comment] 2023-09-13 20:37
No worries. Searching existing issues on some matters is effectively a sport. :-)

Sometimes `in:title <keyword>` is a quick fix. I think that's how I looked up those older issues, using `sensitive` as the keyword (which, in this case, was commonly enough used - it's really hard for ones where different people tend to use different words to describe the request hah).
