### ISSUE TITLE
Background image repeated on share link page

### ISSUE THREAD

**Issue by mvvvmd** [nextcloud/server#24200] opened 2020-11-18 09:16 UTC
# Steps to reproduce
1. Create a share link for a file with password protection
2. Open the link in a different browser or private window

![Screenshot from 2020-11-18 09-32-22](https://user-images.githubusercontent.com/15438922/99509966-c4db6080-2986-11eb-92e4-9e7c4448a985.png)

Tested in several (clean) browsers on Ubuntu, Windows and Android with two Nextcloud instances.

### Expected behaviour

The background image should display once.

### Actual behaviour

The background image is repeated multiple times.

### Server configuration

**Operating system:**

Ubuntu 18.04

**Web server:**

Apache 2.4

**Database:**

Mariadb 10.1

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)

20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

Both

**Where did you install Nextcloud from:**

nextcloud.com

**Comment by kurn77** [comment] 2020-11-18 19:27
Hello, sorry > first I though I can reproduce but not : it was due to Custom CSS I was using.

Removing all in Custom CSS, I don't have a background image repeated multiple times.

**Comment by mvvvmd** [comment] 2020-11-18 21:25
I've tested on a third separately maintained NC instance (20.0.1) just now. Same issue there for me, no custom css in either instance. Note without a theme the issue does not appear, a custom background is required.

**Comment by jeremy13520** [comment] 2020-11-19 09:15
Hello, 
I have the same problem on the NC instance 20.0.1. I didn't customize the CSS, everything is by default on the CSS.

**Comment by kesselb** [comment] 2020-11-24 20:45
cc @juliushaertl @jancborchardt (as you were mentioned on the other issue I closed as duplicate).

**Comment by juliushaertl** [comment] 2020-12-14 06:50
![image](https://user-images.githubusercontent.com/3404133/102049259-d88cb200-3de0-11eb-965a-9606bb3aa95a.png)

Sorry, cannot reproduce this here, maybe there is any other app that overwrites the styles? Could you check the body element for the styles that are applied? 

![image](https://user-images.githubusercontent.com/3404133/102049349-fbb76180-3de0-11eb-972d-510093b16895.png)

**Comment by mvvvmd** [comment] 2020-12-15 14:09
I've disabled all apps and the issue disappeared with only files and theming enabled. When I enable the Talk app the issue reappears, seem to be caused by this app.

**Comment by juliushaertl** [comment] 2020-12-15 14:13
@ma12-co or @danxuliu might know if something gets overwritten there.

**Comment by mvvvmd** [comment] 2020-12-15 14:19
Could be related to this issue [24199](https://github.com/nextcloud/server/issues/24199), something with the video verification feature. That button also always shows up with the background multiplication.

**Comment by JSoko** [comment] 2020-12-16 13:27
I can confirm that the error goes away when I turn off the Talk app.

But: this PR fixes it: https://github.com/nextcloud/spreed/pull/4769

So if you don't wanna wait, just patch  /var/www/nextcloud/apps/spreed/lib/PublicShareAuth/TemplateLoader.php on line 70
with 
```
 	      // Check if "Video verification" option was set
		$share = $event->getShare();
		if (!$share->getSendPasswordByTalk()) {
			return;
		}
```
and anything is working fine again with talk activated...

**Closed by JSoko** 2020-12-16 13:27 UTC
Labels: 1. to develop, bug

**Comment by sergeng** [comment] 2021-08-16 03:06
nano /netxcloud/apps/spreed/css/publicshareauth.scss
                 background-repeat: repeat;
                 **background-repeat: no-repeat !important;**
                 background-size: 275px, contain;
                 **background-size: cover !important;**

**Comment by ressit** [comment] 2022-06-24 17:30
With nc 22.2.9 the background image repetition is still observed in case video-ident is enabled for gaining permission.
Can be fixed by using the custom css app with entry
```css
body.talk-sidebar-enabled #body-login {
    background-position: unset;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: unset;
}
```
