### ISSUE TITLE
Zip related error in the log (a few of them)

### ISSUE THREAD

**Issue by b3nis** [nextcloud/server#25340] opened 2021-01-26 23:11 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Well, I have no idea. The only think I understand is that it got something to do with zip and ODS (vnd.oasis.opendocument.text)? Or maybe I am wrong.

### Expected behaviour
No zip related errors in the log.

### Actual behaviour
A lot of zip related errors in the log.

### Server configuration

**Operating system:**
Ubuntu 20.04.1 Server

**Web server:**
Apache, don't know version

**Database:**
MariaDB 10.4.12

**PHP version:**
7.4.14

**Nextcloud version:** (see Nextcloud admin page)
20.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated, started on 18

**Where did you install Nextcloud from:**
Docker

**Signing status:**
<details>
<summary>Signing status???</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here. 
I get "No errors have been found."
```
</details>

**List of activated apps:**
<details>
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - breezedark: 20.0.3
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - camerarawpreviews: 0.7.10
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - imageconverter: 1.3.1
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - previewgenerator: 3.1.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.11
  - richdocumentscode: 6.4.303
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.5
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.1.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0

```
</details>

**Nextcloud configuration:**
<details>
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "drive.benis.se"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.6.1",
        "poverwrite.cli.url": "https",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "overwrite.cli.url": "https:\/\/drive.benis.se",
        "allow_local_remote_servers": true,
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60"
    }
}

```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Firefox 84.0.2

**Operating system:**
Ubuntu 20.04.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
I don't have access/knowledge.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[PHP] Error: Error: ZipArchive::getStream(): Invalid or uninitialized Zip object at /var/www/html/lib/private/Archive/ZIP.php#155 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "ZipArchive::get ... t", "/var/www/html/l ... p", 155, {path: "Thumbnai ... "})
 1. /var/www/html/lib/private/Archive/ZIP.php line 155
    ZipArchive->getStream("Thumbnails/thumbnail.png")
 2. /var/www/html/lib/private/Preview/Bundled.php line 43
    OC\Archive\ZIP->extractFile("Thumbnails/thumbnail.png", "/tmp/oc_tmp_DIMRcP")
 3. /var/www/html/lib/private/Preview/OpenDocument.php line 45
    OC\Preview\Bundled->extractThumbnail(OC\Files\Node\File {}, "Thumbnails/thumbnail.png")
 4. /var/www/html/lib/private/Preview/GeneratorHelper.php line 63
    OC\Preview\OpenDocument->getThumbnail(OC\Files\Node\File {}, 2048, 2048)
 5. /var/www/html/lib/private/Preview/Generator.php line 244
    OC\Preview\GeneratorHelper->getThumbnail(OC\Preview\OpenDocument {}, OC\Files\Node\File {}, 2048, 2048)
 6. /var/www/html/lib/private/Preview/Generator.php line 140
    OC\Preview\Generator->getMaxPreview(OC\Files\SimpleFS\SimpleFolder {}, OC\Files\Node\File {}, "application/vnd.oasis.opendocument.text", "")
 7. /var/www/html/lib/private/Preview/Generator.php line 109
    OC\Preview\Generator->generatePreviews(OC\Files\Node\File {}, [{width: 313,hei ... }], "application/vnd.oasis.opendocument.text")
 8. /var/www/html/lib/private/PreviewManager.php line 190
    OC\Preview\Generator->getPreview(OC\Files\Node\File {}, 313, 313, true, "fill", null)
 9. /var/www/html/core/Controller/PreviewController.php line 170
    OC\PreviewManager->getPreview(OC\Files\Node\File {}, 313, 313, true, "fill")
10. /var/www/html/core/Controller/PreviewController.php line 143
    OC\Core\Controller\PreviewController->fetchPreview(OC\Files\Node\File {}, 313, 313, false, false, "fill")
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 169
    OC\Core\Controller\PreviewController->getPreviewByFileId(4065724, 313, 313, false, false, "fill")
12. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controller\PreviewController {}, "getPreviewByFileId")
13. /var/www/html/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\PreviewController {}, "getPreviewByFileId")
14. /var/www/html/lib/private/Route/Router.php line 309
    OC\AppFramework\App::main("OC\\Core\\Controller\\PreviewController", "getPreviewByFileId", OC\AppFramework\ ... {}, {_route: "core.P ... "})
15. /var/www/html/lib/base.php line 1008
    OC\Route\Router->match("/core/preview")
16. /var/www/html/index.php line 37
    OC::handleRequest()

GET /core/preview?fileId=4065724&c=f89c3ac0f4fc37510ba38d8879632115&x=313&y=313&forceIcon=0
from 172.18.0.3 by benjamin at 2021-01-26T21:22:03+00:00
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
I don't know how to do that, sorry.
```
</details>

**Comment by systems-levigo** [comment] 2021-03-10 17:51
We got the exact same error.

Did a bit of debugging:
- Where the error occurs

``
        public function extractFile($path, $dest) {
                $fp = $this->zip->getStream($path);
                file_put_contents($dest, $fp);
        }
``

- Seems to appear only while clicking in the menu on the left side (All files/Recent/Favorites/Shares).
- This is the first installation on the same server that causes this log entry.

**Comment by Niemand112233** [comment] 2021-03-12 15:07
I have the same error while generating previews.

**Comment by szaimen** [comment] 2021-06-25 13:29
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by eaggy** [comment] 2021-07-14 11:11
yes, I got the same error with NC21.0.2 as well as with NC21.0.3

**Comment by rarealphacat** [comment] 2021-07-16 11:50
> I have the same error while generating previews.

Same while generating previews NC 21.0.3.

An unhandled exception has been thrown:
ValueError: Invalid or uninitialized Zip object in /var/www/html/nextcloud/lib/private/Archive/ZIP.php:155
Stack trace:
```
#0 /var/www/html/nextcloud/lib/private/Archive/ZIP.php(155): ZipArchive->getStream()
#1 /var/www/html/nextcloud/lib/private/Preview/Bundled.php(43): OC\Archive\ZIP->extractFile()
#2 /var/www/html/nextcloud/lib/private/Preview/OpenDocument.php(45): OC\Preview\Bundled->extractThumbnail()
#3 /var/www/html/nextcloud/lib/private/Preview/GeneratorHelper.php(63): OC\Preview\OpenDocument->getThumbnail()
#4 /var/www/html/nextcloud/lib/private/Preview/Generator.php(244): OC\Preview\GeneratorHelper->getThumbnail()
#5 /var/www/html/nextcloud/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /var/www/html/nextcloud/lib/private/PreviewManager.php(205): OC\Preview\Generator->generatePreviews()
#7 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(217): OC\PreviewManager->generatePreviews()
#8 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(195): OCA\PreviewGenerator\Command\PreGenerate->processFile()
#9 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(163): OCA\PreviewGenerator\Command\PreGenerate->processRow()
#10 /var/www/html/nextcloud/apps/previewgenerator/lib/Command/PreGenerate.php(131): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#11 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\PreGenerate->execute()
#12 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#13 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#14 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#15 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#16 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()

```

**Comment by szaimen** [comment] 2021-07-27 10:37
So Zip files shouldn't get previews at all, no?

**Comment by c-schulz-rd13** [comment] 2022-02-15 07:58
I have the same error with NC 22.2.3

```
2022-02-13T18:10:05+01:00 Generating previews for /xxxxxxxx/files/Documents/xxxxxxxxxxxgraph.otp
An unhandled exception has been thrown:
ValueError: Invalid or uninitialized Zip object in /var/www/html/lib/private/Archive/ZIP.php:154
Stack trace:
#0 /var/www/html/lib/private/Archive/ZIP.php(154): ZipArchive->getStream('Thumbnails/thum...')
#1 /var/www/html/lib/private/Preview/Bundled.php(42): OC\Archive\ZIP->extractFile('Thumbnails/thum...', '/tmp/oc_tmp_h0O...')
#2 /var/www/html/lib/private/Preview/OpenDocument.php(44): OC\Preview\Bundled->extractThumbnail(Object(OC\Files\Node\File), 'Thumbnails/thum...')
#3 /var/www/html/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\OpenDocument->getThumbnail(Object(OC\Files\Node\File), 4096, 4096)
#4 /var/www/html/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\OpenDocument), Object(OC\Files\Node\File), 4096, 4096)
#5 /var/www/html/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'application/vnd...', '')
#6 /var/www/html/lib/private/PreviewManager.php(204): OC\Preview\Generator->generatePreviews(Object(OC\Files\Node\File), Array, 'application/vnd...')
#7 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(243): OC\PreviewManager->generatePreviews(Object(OC\Files\Node\File), Array)
#8 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile(Object(OC\Files\Node\File))
#9 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#10 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#11 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#12 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#13 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(192): OCA\PreviewGenerator\Command\Generate->parseFolder(Object(OC\Files\Node\Folder), Array)
#14 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(138): OCA\PreviewGenerator\Command\Generate->generateUserPreviews(Object(OC\User\User))
#15 /var/www/html/lib/private/User/Manager.php(646): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}(Object(OC\User\User))
#16 /var/www/html/custom_apps/previewgenerator/lib/Command/Generate.php(139): OC\User\Manager->callForSeenUsers(Object(Closure))
#17 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\Generate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/console.php(99): OC\Console\Application->run()
#23 /var/www/html/occ(11): require_once('/var/www/html/c...')
#24 {main}www-data@773c1a113de7:~/html$ 
exit
```

**Comment by amo13** [comment] 2022-02-17 07:58
Still valid on 23.0.2

**Comment by come-nc** [comment] 2022-02-28 11:04
> Still valid on 23.0.2

Hello, can you provide a file allowing to reproduce the error?
The stacktrace points to OpenDocument preview generation, does it happen with any opendocument file?

**Comment by amo13** [comment] 2022-02-28 12:59
Thanks for taking notice!
Currently, the preview generation breaks at the same place each time for me. The stack trace is the following:
```
An unhandled exception has been thrown:
ValueError: Invalid or uninitialized Zip object in /usr/share/webapps/nextcloud/lib/private/Archive/ZIP.php:154
Stack trace:
#0 /usr/share/webapps/nextcloud/lib/private/Archive/ZIP.php(154): ZipArchive->getStream()
#1 /usr/share/webapps/nextcloud/lib/private/Preview/Bundled.php(42): OC\Archive\ZIP->extractFile()
#2 /usr/share/webapps/nextcloud/lib/private/Preview/OpenDocument.php(44): OC\Preview\Bundled->extractThumbnail()
#3 /usr/share/webapps/nextcloud/lib/private/Preview/GeneratorHelper.php(62): OC\Preview\OpenDocument->getThumbnail()
#4 /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php(245): OC\Preview\GeneratorHelper->getThumbnail()
#5 /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php(140): OC\Preview\Generator->getMaxPreview()
#6 /usr/share/webapps/nextcloud/lib/private/PreviewManager.php(227): OC\Preview\Generator->generatePreviews()
#7 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(243): OC\PreviewManager->generatePreviews()
#8 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(214): OCA\PreviewGenerator\Command\Generate->parseFile()
#9 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#10 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(212): OCA\PreviewGenerator\Command\Generate->parseFolder()
#11 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(192): OCA\PreviewGenerator\Command\Generate->parseFolder()
#12 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(138): OCA\PreviewGenerator\Command\Generate->generateUserPreviews()
#13 /usr/share/webapps/nextcloud/lib/private/User/Manager.php(656): OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}()
#14 /usr/share/webapps/nextcloud/apps/previewgenerator/lib/Command/Generate.php(139): OC\User\Manager->callForSeenUsers()
#15 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\Generate->execute()
#16 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#17 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#19 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#20 /usr/share/webapps/nextcloud/console.php(99): OC\Console\Application->run()
#21 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
```
[Here](https://github.com/nextcloud/server/files/8153446/Migrationserfahrung.odt) is the file causing the error. It took me some time to figure out which one it was because I only see which folder is being scanned while the command crashes.

Thank you a lot for investigating!

**Comment by come-nc** [comment] 2022-02-28 14:23
So this is actually not a Zip file at all but a plain XML file, without compression.
Do you use special options from LibreOffice or some other software to produce this?

mimetype is the same as the one for zip odt files, so not much I can do here apart adding a try/catch to hide the error away and skip preview generation.

**Comment by amo13** [comment] 2022-02-28 17:37
Oh, I think I might know now how this came to be. If I remember correctly, I did not create and edit this file with LibreOffice but with Collabora or OnlyOffice inside Nextcloud.

**Comment by come-nc** [comment] 2022-03-01 08:39
> Oh, I think I might know now how this came to be. If I remember correctly, I did not create and edit this file with LibreOffice but with Collabora or OnlyOffice inside Nextcloud.

@juliushaertl Collabora or OnlyOffice might use odt instead of fodt for this format?

**Closed** 2022-03-01 13:10 UTC
Labels: bug, 1. to develop, feature: previews and thumbnails
