### ISSUE TITLE
Theming color/background image/random background image gets ignored

### ISSUE THREAD

**Issue by ltrzcinski** [nextcloud/server#20711] opened 2020-04-29 07:57 UTC
### Steps to reproduce
1. Within Nextcloud, go to Settings --> Admin --> Accessibility
2. Turn on Dark Theme
3. Turn on Light Theme
4. Turn on dyslexia fonts
5. Turn off dyslexia fonta
6. Turn off all options and return to light theme
7. Go to Theming App
8. Enable "Set Random Image as login background"
9. Enable "Set Random Image as header background"
10. Disable "Set Random Image as login background"
11. Disable "Set Random Image as header background"
12. Repeat steps 8-11 few times

### Expected behaviour
Nextcloud UI should remain in light theme with no dyslexia font, and no random images as login and header background

### Actual behaviour
Nextcloud UI remains in light theme, but despite of disable Random Image for Header, the image still appears

See: https://github.com/nextcloud/server/issues/10058

### Server configuration

**Operating system:**
Ubuntu 18.04 LTS
**Web server:**
Nginx
**Database:**
Mysql 10.1.44
**PHP version:**
7.2.24

**Nextcloud version:** (see Nextcloud admin page)
18.0.4 Stable
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Installation: via sudo apt, update via Nextcloud updater

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

### Client configuration
**Browser:**
 Chrome 81.0.4044.122, also on other browser regardless of version and vendor

**Operating system:**
Win10

**Comment by szaimen** [comment] 2021-05-31 13:51
Duplicate of https://github.com/nextcloud/server/issues/14059

**Closed by szaimen** 2021-05-31 13:51 UTC
Labels: 0. Needs triage, bug
