### ISSUE TITLE
New photos on web not properly sorted by modified even when specified

### ISSUE THREAD

**Issue by jarink0** [nextcloud/server#19249] opened 2020-01-31 08:54 UTC
hi, i just noticed that for +- three days my new photos are uploaded ok, but when i go to upload folder in web client and sort them by "edited" as always (to sort them by date) the newest are not showing up, but are somewhere in the middle of the folder... in mobile app its ok

thanks

NC 17.0.3 but problem persits from 17.0.2 (upgraded today)

this is how folder looks in "main view"

![modif](https://user-images.githubusercontent.com/39731673/73526039-a19fee80-4410-11ea-93d3-2268f3f47a01.JPG)

and this is what i get when i click on "modified" to have it sorted by date - new photos are somewhere in the middle to end...

![fold](https://user-images.githubusercontent.com/39731673/73526055-ab295680-4410-11ea-9ad9-dca4530d5efa.JPG)

**Comment by szaimen** [comment] 2021-06-07 17:31
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 17:31 UTC
Labels: 0. Needs triage, bug, feature: files
