### ISSUE TITLE
CardDAV sync error for recently contacted contacts

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/server#24165] opened 2020-11-16 19:11 UTC
### Steps to reproduce
1. Don't know how to reproduce it as it only appears for one of our users
2. It only happens when I'm running an application that tries to synchronize my Nextcloud contacts

### Expected behaviour
No webdav/CardDAV sync errors

### Actual behaviour
Sync errors regarding recently contacted contacts

In the contacts app I can't see a corresponding address book. But I found some code that seems to deal with recent interactions: https://github.com/nextcloud/contacts/blob/23e887b0dbcc4f4dbd4fbd9e1244f1db4a7b055d/src/views/Contacts.vue#L72-L85

## Server configuration detail

**Operating system:** Linux 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** pgsql PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

**PHP version:** 

7.4.12
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.1 - 20.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** official Docker

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.2
 - announcementcenter: 4.0.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.1
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - deck: 1.2.0
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_automatedtagging: 1.10.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.0.4
 - groupfolders: 8.1.1
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.7.0
 - metadata: 0.12.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - occweb: 0.0.7
 - onlyoffice: 6.1.0
 - password_policy: 1.10.1
 - polls: 1.6.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.1
 - survey_client: 1.8.0
 - suspicious_login: 3.2.1
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_nextcloud_notification: 3.0.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflow_pdf_converter: 1.5.0
 - workflow_script: 1.5.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - photos
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.tsmd.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "20.0.1.1",
    "overwrite.cli.url": "https:\/\/cloud.tsmd.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "app_install_overwrite": [
        "occweb",
        "polls"
    ],
    "maintenance": false,
    "loglevel": 2,
    "theme": "",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": {
        "1": "HTTP_X_FORWARDED",
        "2": "HTTP_FORWARDED_FOR",
        "3": "HTTP_FORWARDED",
        "0": "HTTP_X_FORWARDED_FOR"
    },
    "overwritehost": "cloud.tsmd.de",
    "overwriteprotocol": "https",
    "default_language": "de",
    "default_locale": "de_DE",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/var\/www\/html\/data\/skeleton",
    "updater.release.channel": "stable",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "trashbin_retention_obligation": "auto,30",
    "versions_retention_obligation": "auto,30"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0

**Operating system:** Linux

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"M18lk4TWAbjSpGdcE9Lc","level":4,"time":"2020-11-16T19:06:16+00:00","remoteAddr":"x.x.x.x","user":"user.name","app":"webdav","method":"REPORT","url":"/remote.php/dav/addressbooks/users/user.name/z-app-generated--contactsinteraction--recent/","message":{"Exception":"Sabre\\VObject\\ParseException","Message":"This parser only supports VCARD and VCALENDAR files","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/vobject/lib/Parser/MimeDir.php","line":90,"function":"parseDocument","class":"Sabre\\VObject\\Parser\\MimeDir","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/vobject/lib/Reader.php","line":47,"function":"parse","class":"Sabre\\VObject\\Parser\\MimeDir","type":"->","args":["Resource id #20",0]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/CardDAV/Plugin.php","line":820,"function":"read","class":"Sabre\\VObject\\Reader","type":"::","args":["Resource id #20"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/CardDAV/Plugin.php","line":249,"function":"convertVCard","class":"Sabre\\CardDAV\\Plugin","type":"->","args":["Resource id #20","vcard3"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/CardDAV/Plugin.php","line":194,"function":"addressbookMultiGetReport","class":"Sabre\\CardDAV\\Plugin","type":"->","args":[{"properties":["{DAV:}getetag","{urn:ietf:params:xml:ns:carddav}address-data"],"hrefs":["https://cloud.tsmd.de/remote.php/dav/addressbooks/users/user.name/z-app-generated--contactsinteraction--recent/80","https://cloud.tsmd.de/remote.php/dav/addressbooks/users/user.name/z-app-generated--contactsinteraction--recent/81"],"contentType":"text/vcard","version":"3.0","addressDataProperties":[],"__class__":"Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"report","class":"Sabre\\CardDAV\\Plugin","type":"->","args":["{urn:ietf:params:xml:ns:carddav}addressbook-multiget",{"properties":["{DAV:}getetag","{urn:ietf:params:xml:ns:carddav}address-data"],"hrefs":["https://cloud.tsmd.de/remote.php/dav/addressbooks/users/user.name/z-app-generated--contactsinteraction--recent/80","https://cloud.tsmd.de/remote.php/dav/addressbooks/users/user.name/z-app-generated--contactsinteraction--recent/81"],"contentType":"text/vcard","version":"3.0","addressDataProperties":[],"__class__":"Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport"},"addressbooks/users/user.name/z-app-generated--contactsinteraction--recent"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":720,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["report",["{urn:ietf:params:xml:ns:carddav}addressbook-multiget",{"properties":["{DAV:}getetag","{urn:ietf:params:xml:ns:carddav}address-data"],"hrefs":["https://cloud.tsmd.de/remote.php/dav/addressbooks/users/user.name/z-app-generated--contactsinteraction--recent/80","https://cloud.tsmd.de/remote.php/dav/addressbooks/users/user.name/z-app-generated--contactsinteraction--recent/81"],"contentType":"text/vcard","version":"3.0","addressDataProperties":[],"__class__":"Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport"},"addressbooks/users/user.name/z-app-generated--contactsinteraction--recent"]]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpReport","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:REPORT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":167,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/sabre/vobject/lib/Parser/MimeDir.php","Line":163,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) KHTML/5.75.0 (like Gecko) Konqueror/5 KIO/5.75","version":"20.0.1.1","id":"5fb2cda9ae3e5"}
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by Chartman123** [comment] 2020-11-16 19:45
![grafik](https://user-images.githubusercontent.com/16020496/99300100-74f87e80-284c-11eb-82fb-3e081450a165.png)
Here's a screenshot of the corresponding address in the address book selection in Kontact. I didn't select the address book to be synchronized

**Comment by kesselb** [comment] 2020-11-16 21:58
cc @ChristophWurst

**Comment by ChristophWurst** [comment] 2020-11-19 08:35
Duplicate of https://github.com/nextcloud/server/issues/22439

**Closed by ChristophWurst** 2020-11-19 08:35 UTC
Labels: 0. Needs triage, bug
