### ISSUE TITLE
File System Tag is not displaying the complete items for selection 

### ISSUE THREAD

**Issue by kevinkuan1969** [nextcloud/server#36152] opened 2023-01-16 06:55 UTC
To make it possible for us to help you please fill out below information carefully.
-->
1. Add new File Automated Tagging from Adminstration-> Flow
2.The selection of File System Tag is not displaying the complete item for selection. 
3.
![image](https://user-images.githubusercontent.com/80019930/212616050-9bae94e0-17aa-4392-aee7-3a2bf78a47fb.png)

Expected behaviour
The system should display the item when the keyvalue is typed. It worked perferly before upgrade from Nextcloud 24.0.6

Server configuration
Operating system:
Ubuntu 20.14

Web server:
Apache2 2.4.41

Database:8.0.31

PHP version: 8.1.14

Nextcloud version: 25.0.2

**Comment by nickvergessen** [comment] 2023-01-16 08:15
It works fine here, but maybe a certain amount is needed. Does the tag appear when you search with the correct casing, so `Metro`?

**Comment by Io-Qo** [comment] 2023-01-16 19:21
I'm having the same issue after updating to 25.0.2. It seems the search is only working within the 5 options displayed/suggested upon input focus but not within all available system tags. This essentially breaks file access control so to me it seems to be an urgent problem.

Nextcloud 25.0.2, Ubuntu 22.04.1, PHP 8.1.2, MySQL 8.0.31, Apache 2.4.52

**Comment by nickvergessen** [comment] 2023-01-17 08:25
More research in https://github.com/nextcloud/nextcloud-vue/issues/3662

**Comment by twerpyfie** [comment] 2023-01-21 12:56
Hello, I have the same problem. I have already mentioned it here before:
https://github.com/R0Wi/workflow_ocr/issues/175


When i just put the letter D in it, it sorts everything out except the Tags with the letter "d" in, but only from the first 5 entrys.... Is that reproducible for you? It's a bit difficult to explain. 

Without text:
![1](https://user-images.githubusercontent.com/46491831/213824245-59ac69ec-972b-48d6-a793-980f188a608a.png)

With just the letter "d"
![2](https://user-images.githubusercontent.com/46491831/213824247-6943067d-3586-4374-a8db-5f8be007e66f.png)

It says "No results":
![3](https://user-images.githubusercontent.com/46491831/213824249-ce7148fa-b850-49b1-9465-b8fa6a734304.png)

The tag "Document" does exist:
![4](https://user-images.githubusercontent.com/46491831/213824250-a0003702-ea05-43ec-927e-7a00c4283e8d.png)

**Comment by PVince81** [comment] 2023-01-23 10:05
duplicate of https://github.com/nextcloud/server/issues/34395 ?

**Comment by nickvergessen** [comment] 2023-01-23 11:23
Yes.

Duplicate of #34395

**Closed** 2023-01-23 11:24 UTC
Labels: bug, 1. to develop, feature: workflows, 25-feedback
