### ISSUE TITLE
Signature.json not updated in Nextcloud 14.0.1

### ISSUE THREAD

**Issue by Tenivar** [nextcloud/server#11586] opened 2018-10-03 11:25 UTC
### Steps to reproduce
Install a fresh version of Nextcloud
Integrity and configuration check of the server are done automatically after completing the installation.

### Expected behaviour
Basic security hardening issues

### Actual behaviour
Integrity check fail, with a lot of extra files appearing in core. (See signing status for the list of "extra" files).

## Server configuration detail

**Operating system:** Linux 4.9.130-xxxx-std-ipv6-64 #393630 SMP Mon Oct 1 08:31:25 UTC 2018 x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 

7.0.30-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mcrypt, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 14.0.1 - 14.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Nextcloud.com

<details><summary>Signing status</summary>
(Too long for github, see attached file)
[signingstatus.txt](https://github.com/nextcloud/server/files/2441779/signingstatus.txt)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - checksum: 0.4.1
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - groupfolders: 1.3.3
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - richdocuments: 2.0.13
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - spreed: 4.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - federation
 - files_external
 - support
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.example.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.1.1",
    "overwrite.cli.url": "https:\/\/cloud.example.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Memcached",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
}
```
</details>

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** No.

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Operating system:** Windows 10 pro

**Comment by MorrisJobke** [comment] 2018-10-03 13:31
> Integrity check fail, with a lot of extra files appearing in core. (See signing status for the list of "extra" files).

Weird - the signature.json is available in the archives for 14.0.1. Could you check again why it somehow got deleted? Maybe the extraction failed for some reason?

Beside that we could not reproduce the issue at all.

**Comment by Tenivar** [comment] 2018-10-05 08:43
Yes, that's weird. I've tried to reinstall nextcloud server, and reproduced the error. Strange. I've deleted signature.json and replaced it with a new one without results, I'll download an old signature.json to check if that solution works.

**Comment by MorrisJobke** [comment] 2018-11-29 23:05
As there is no feedback since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2018-11-29 23:05 UTC
Labels: needs info
