### ISSUE TITLE
Add a button to delete more than one/all auth tokens

### ISSUE THREAD

**Issue by raid1** [nextcloud/server#28103] opened 2021-07-21 22:22 UTC
Because of https://github.com/nextcloud/server/issues/28102 and https://github.com/nextcloud/server/issues/27603 it would be useful to have a button to delete more than one or all auth tokens

**Comment by kesselb** [comment] 2021-07-22 21:43
Duplicate of https://github.com/nextcloud/server/issues/11655

**Closed by kesselb** 2021-07-22 21:43 UTC
Labels: 0. Needs triage, enhancement
