### ISSUE TITLE
DAV Download big files too slow and hangs up

### ISSUE THREAD

**Issue by mixim-mixim** [nextcloud/server#2773] opened 2016-12-19 22:08 UTC
### Steps to reproduce
1. Download a big file with ex wget http://example.com/remote.php/webdav/big-file.tgz
2. Download a big file with ex wget http://example.com/
3. Compare average download speed, in my comparison the second one was 3x faster
4. The first hangs up after a while, the process does NOT return, seems to be sleeping

### Expected behaviour
The file should be downloaded as fast (or very similar) as normal download

### Actual behaviour
Slow download, hangs up, does NOT return

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** mySQL

**PHP version:** 7.x

**Nextcloud version:** 10.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated ...

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

<b>No errors have been found.</b>
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
``

<b>
<pre>
Enabled:
  - activity: 2.3.2
  - audioplayer: 1.3.1
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.1
  - news: 9.0.4
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - rainloop: 4.26
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - documents
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml
</pre>
</b>`
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
ssl, no data encryption

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu 16.04

**Comment by blizzz** [comment] 2016-12-20 12:20
The first URL  ends up with error code 500,  the second seems incomplete. Specifying what a big file is for you would help. Nextcloud and webserver logs are missing.

**Comment by mixim-mixim** [comment] 2016-12-22 21:47
The URL are only examples :)
A big file is > 1GB
U can easy reproduce that if u upload a big file to the server and download via webDAV-URL
If u place the file in a public server directory u can download with full speed ..
Updated today to 11.0.0 ... there is normal speed  again, 
the error seems to be only in versions < 11.x (or may be only in 10.0.2)

**Comment by MorrisJobke** [comment] 2017-01-24 21:02
> the error seems to be only in versions < 11.x (or may be only in 10.0.2)

Sadly we can't reproduce this in 10.0.x

Please comment if somebody has more details on this. Until then I will close this ticket as it seems to be solved for this specific instance by upgrading to 11.

**Closed by MorrisJobke** 2017-01-24 21:02 UTC
Labels: needs info
