### ISSUE TITLE
Dashboard: hide files from hidden folders

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/server#26740] opened 2021-04-24 12:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Problem

Several apps are using hidden folders in Nextcloud to store their data. 

Examples:
 * Seedvault (AOSP backup)
 * DAVx⁵ (contact book backup)

This means that every time the user logs in to the web interface they see automatically generated and uploaded files:

![Bildschirmfoto von 2021-04-24 14-26-42](https://user-images.githubusercontent.com/1377943/115958945-f0e8a800-a509-11eb-8109-2196e4c838dd.png)

**Describe the solution you'd like**
Do not show files from hidden folders by default in the Dashboard. 

**Describe alternatives you've considered**
Maybe add a toggle or config option, for people that want to see content from their hidden folders.

**Comment by szaimen** [comment] 2021-04-24 12:39
Duplicate of https://github.com/nextcloud/recommendations/issues/78

**Closed by szaimen** 2021-04-24 12:39 UTC
Labels: 0. Needs triage, enhancement
