### ISSUE TITLE
Trashbin error when deleting perm. multiple files

### ISSUE THREAD

**Issue by hul51u** [nextcloud/server#26802] opened 2021-04-27 22:08 UTC
### Steps to reproduce
1. Trashbin with more than 3 files
2. Select multiple files, but leave at least one file unselected
3. Action -> Delete permanently

### Expected behaviour
Selected files should be deleted.

### Actual behaviour
At least one file won't become deleted. I got the error "Error while removing files from trashbin".

### Server configuration
try.nextcloud.com
Also on my personal cloud since I can remember (version 15?) with ubuntu and apache.

**Comment by andyxheli** [comment] 2021-04-28 15:01
@h3ndrik what error are you getting please copy error from your logs.

**Comment by hul51u** [comment] 2021-04-28 18:36
{"reqId":"XXXXXXXXXXXXX","level":4,"time":"2021-04-28T18:30:56+00:00","remoteAddr":"87.xx.xx.xx","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/trashbin/admin/trash/ztzz.md.d1619634593","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files/4d1f8bdc6d1525444a0085af56d60acb\"(\"home::admin::scanner::files_trashbin/versions\") is locked","Code":0,"Trace":[{"file":"/xxx/lib/private/Files/Storage/Common.php","line":752,"function":"acquireLock","class":"OC\\Lock\\DBLockingProvider","type":"->"},{"file":"/xxx/lib/private/Files/Storage/Wrapper/Wrapper.php","line":592,"function":"acquireLock","class":"OC\\Files\\Storage\\Common","type":"->"},{"file":"/xxx/pirmcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":592,"function":"acquireLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/xxx/lib/private/Files/Cache/Scanner.php","line":334,"function":"acquireLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/xxx/apps/files_trashbin/lib/Trashbin.php","line":973,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->"},{"file":"/xxx/apps/files_trashbin/lib/Trashbin.php","line":705,"function":"getVersionsFromTrash","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/xxx/pirmcloud/apps/files_trashbin/lib/Trashbin.php","line":670,"function":"deleteVersions","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/xxx/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php","line":92,"function":"delete","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/xxx/pirmcloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":69,"function":"removeItem","class":"OCA\\Files_Trashbin\\Trash\\LegacyTrashBackend","type":"->"},{"file":"/xxx/apps/files_trashbin/lib/Sabre/AbstractTrash.php","line":90,"function":"removeItem","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->"},{"file":"/xxx/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\Files_Trashbin\\Sabre\\AbstractTrash","type":"->"},{"file":"/xxx/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/xxx/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/xxx/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/xxx/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/xxx/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/xxx/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/xxx/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/xxx/remote.php","line":167,"args":["/xxx/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/xxx/lib/private/Lock/DBLockingProvider.php","Line":210,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"21.0.1.1","id":"6089a9e187d9f"}

**Comment by andyxheli** [comment] 2021-04-28 18:55
Are you using APCU, Redis ?

**Comment by andyxheli** [comment] 2021-04-28 18:59
Same issue as here https://help.nextcloud.com/t/can-not-delete-multiple-files-from-trash-bin-permantly/78887/2

**Comment by andyxheli** [comment] 2021-04-28 19:00
Looks like the same issue as https://github.com/nextcloud/server/issues/16491

**Comment by hul51u** [comment] 2021-04-28 19:05
It's slightly different. The Bug described here only appears when deleting multiple files and leave at least one file unselected in trashbin. File extensions are not concerned.

**Comment by acsfer** [comment] 2021-04-28 19:13
Is there a number of files to reproduce this? I've tried with 4 files, left one unchecked, no error.

**Comment by andyxheli** [comment] 2021-04-28 19:16
I just tired the same thing i had 5 files in the trashbin selected 4 out of the 5 and deleted them

**Comment by hul51u** [comment] 2021-04-28 19:30
I created this video with nextcloud demo server try.nextcloud.com.

https://user-images.githubusercontent.com/78090961/116461757-ec552400-a868-11eb-83ec-b3f61509128d.mp4

**Comment by kesselb** [comment] 2021-04-29 08:14
Duplicate of https://github.com/nextcloud/server/issues/16491

**Closed by kesselb** 2021-04-29 08:14 UTC
Labels: 0. Needs triage, bug, needs info
