### ISSUE TITLE
Hidden space in filename not seen in file listing

### ISSUE THREAD

**Issue by soniok** [nextcloud/server#15788] opened 2019-05-29 09:23 UTC
### Steps to reproduce
1. Create folder, then file. In my case "Name - Subname .gpx", make sure the leave the extra space between the word "Subname" and the ".gpx".
2. Once file is created, reload page. You should see the filename does not have the trailling space anymore if it's not being edited.
3. Once you start editing the file name, the trailling space re-appears.

### Expected behaviour
I expect to see the trailling space in the file name even when not editing the file name but when listing all the files of a folder. I want to be able to see the files in a folder with their correct filename even if it has space in it.

### Actual behaviour
Instead I only see the trailling space in file name when either editing the filename via NextCloud web interface or when another NextCloud app is listing this file. Other wide I would have neven noticed the extra space.

### Server configuration

**Operating system**: Debian 9

**Web server:** Server version: Apache/2.4.25 (Debian)
Server built:   2019-04-02T19:05:13

**Database:**: mysql  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b (cli) (built: May  3 2019 09:38:28) ( NTS )
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b

**Nextcloud version:** Nextcloud 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install via this script https://github.com/criegerde/install-nextcloud

**Where did you install Nextcloud from:** Don't understand the question.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>Antivirus for files
Cookbook
Accessibility
Official Activity
Official Auditing / Logging
Official Bookmarks
Brute-force settings
Official Calendar
Official Camera RAW Previews
Collaborative tags
Official Comments
Official Contacts
Official Deleted files
Official Drawio
DropIt
External sites
Official External storage support
Official Extract
Federation
Official File access control
Official File sharing 
Official Flow Upload
Full text search
Full text search - Files
Full text search - Files - Tesseract OCR
Gallery
Official GpxEdit
GpxMotion
GpxPod
Log Reader
Official Metadata
Monitoring
Official Nextcloud announcements
Official Notes
Official Notifications
Official Password policy
Official PDF viewer
Official PhoneTrack
Photo Sphere Viewer
Preview Generator
Privacy
Recommendations
Registration
Right click
Share by mail
Official Support
Official Suspicious Login
Tasks
Text editor
Official Theming
Official Update notification
Official Versions
Official Video player
Official Viewer
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bookmarks: 1.0.5
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - camerarawpreviews: 0.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - cookbook: 0.1.1
  - dav: 1.9.2
  - drawio: 0.9.3
  - dropit: 0.2.1
  - external: 3.3.0
  - extract: 1.2.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_accesscontrol: 1.6.0
  - files_antivirus: 2.1.0
  - files_external: 1.7.0
  - files_fulltextsearch: 1.3.0
  - files_fulltextsearch_tesseract: 1.3.0
  - files_pdfviewer: 1.5.0
  - files_photospheres: 0.0.3
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - flowupload: 0.1.0
  - fulltextsearch: 1.3.2
  - gallery: 18.3.0
  - gpxedit: 0.0.11
  - gpxmotion: 0.0.9
  - gpxpod: 3.0.3
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notes: 2.6.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - phonetrack: 0.5.1
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - registration: 0.4.6
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - suspicious_login: 1.0.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - firstrunwizard
  - survey_client
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:**  Yes, SMB via local lan.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox 67.0 (64 bit)

**Operating system:** Windows 10 Up to date.

**Comment by szaimen** [comment] 2021-05-20 13:37
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-20 13:37 UTC
Labels: 0. Needs triage, bug
