### ISSUE TITLE
Upload and Read shared folder

### ISSUE THREAD

**Issue by jeyca** [nextcloud/server#10259] opened 2018-07-16 12:30 UTC
Currently we have these three possibilities to share a folder with external people

![](https://user-images.githubusercontent.com/37297730/42758609-5ffb13ba-8904-11e8-864c-e8e3f4881b01.png)

But I am missing an option, to share a folder where people can **upload their stuff and view/read it** (and of all other uploaders), but are not allowed to edit or delete it. 

I personally want members of an event to upload their photos and videos and share them with all other persons who have access using the share link. But they should not be allowed to remove or edit files.

**Comment by jeyca** [comment] 2018-07-16 12:45
not gitmate, you are wrong, none of it is related ;) and I also couldn't find existing issues for that

**Comment by stratege1401** [comment] 2018-07-16 13:44
@jeyca are u feeling alone ?? talking back to a bot, so funny ...

but your right ...

**Comment by MorrisJobke** [comment] 2018-07-16 21:44
Duplicate of #6620

**Closed by MorrisJobke** 2018-07-16 21:44 UTC
Labels: enhancement, feature: occ, feature: sharing
