### ISSUE TITLE
Better visual indication on upload progress bar

### ISSUE THREAD

**Issue by realies** [nextcloud/server#10400] opened 2018-07-26 06:22 UTC
Currently it says *Uploading...* or an estimated time for the upload(s) to finish. Inspecting the progress bar reveals more information such as what the total upload percentage is, what amount of MB out of total upload MB are uploaded and current upload speed. Can this information be present in the UI in some form? Inspecting the element to know this is not the best user experience.

**Comment by MorrisJobke** [comment] 2018-07-26 07:07
Duplicate of #8972

**Closed by MorrisJobke** 2018-07-26 07:07 UTC
Labels: enhancement, feature: files, feature: occ
