### ISSUE TITLE
Upgrade fails from NC11-12

### ISSUE THREAD

**Issue by croessner** [nextcloud/server#5531] opened 2017-06-24 10:48 UTC
### Steps to reproduce
1. I downloaded version 12 from official website
2. I followed the manual upgrade guide on Nextcloud website for version 12
3. When it comes to the occ upgrade, the process fails

### Expected behaviour
A successfull upgrade

### Actual behaviour
Upgrade fails with the following erros:

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <theming> ...
InvalidArgumentException: $absolutePath must be relative to "files"
Update failed
Maintenance mode is kept active
Reset log level
```

After that, neither the maintenance mode is active nor to config.php file containes any more data (it is wiped to zero bytes)

### Server configuration
The server is a KVM VM, having 4 CPUs with native flags from Xeon L5640. 8GB RAM and 100GB storage for /mnt/data

**Operating system**:
Gentoo Linux hardened (but with MMAP prot disabled!) on x86_64

**Web server:**
nginx 1.10.3

**Database:**
MariaDB on OpenBSD

**PHP version:**
7.1.3

**Nextcloud version:** (see Nextcloud admin page)
According to version.php: $OC_Version = array(12,0,0,29);

**Updated from an older Nextcloud/ownCloud or fresh install:**
NC11 stable release

**Where did you install Nextcloud from:**
Official website

**Signing status:**
Can not do this, as upgrade is currently broken.

**List of activated apps:**
Running occ upgrade, all apps had been disabled. Normally I use these:
```
announcementcenter
apporder
audioplayer
bookmarks
calendar
contacts
direct_menu
files_downloadactivity
files_markdown
news
nextant
notes
richdocuments
spreed
```

But as said: Currently they are all disabled as of running occ upgrade for the first time.

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'instanceid' => 'oc6bv5n6btbh',
  'passwordsalt' => '****',
  'secret' => '*****',
  'trusted_domains' =>
  array (
    0 => 'roessner-net.de',
  ),
  'datadirectory' => '/mnt/data/nextcloud',
  'asset-pipeline.enabled' => true,
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'https://roessner-net.de/nextcloud',
  'dbtype' => 'mysql',
  'version' => '11.0.3.2',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'maintenance' => false,
  'dbname' => 'nextcloud',
  'dbhost' => '192.168.0.1',
  'dbuser' => 'nextcloud',
  'dbpassword' => '*****',
  'filesystem_check_changes' => 1,
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 2,
  ),
  'knowledgebaseenabled' => true,
  'enable_avatars' => false,
  'allow_user_to_change_display_name' => false,
  'auth.bruteforce.prevention.enabled' => true,
  'updatechecker' => false,
  'log_type' => 'owncloud',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 2,
  'syslog_tag' => 'Nextcloud',
  'logdateformat' => 'F d, Y H:i:s',
  'cron_log' => true,
  'log_rotate_size' => false,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.roessner-net.de',
  'mail_smtpport' => '587',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'roessner-net.de',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MarkDown',
    6 => 'OC\\Preview\\MP3',
    7 => 'OC\\Preview\\TXT',
    8 => 'OC\\Preview\\Movie',
  ),
  'theme' => '',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'system@srvint.net',
  'mail_smtppassword' => 'ixaKYGNRgmeI',
  'mail_smtpauthtype' => 'PLAIN',
  'singleuser' => false,
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
sudo -u www-data php occ ldap:show-config
Running this command makes the config.php zero bytes! In fact running _any_ occ command wipes the config.

SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
```
user_ldap       cleanUpJobOffset        0
user_ldap       enabled yes
user_ldap       has_memberof_filter_support     1
user_ldap       home_folder_naming_rule
user_ldap       installed_version       1.2.1
user_ldap       last_jpegPhoto_lookup   0
user_ldap       ldap_agent_password     *****
user_ldap       ldap_attributes_for_group_search
user_ldap       ldap_attributes_for_user_search
user_ldap       ldap_backup_host
user_ldap       ldap_backup_port
user_ldap       ldap_base       ou=people,ou=it,dc=roessner-net,dc=de
user_ldap       ldap_base_groups        ou=people,ou=it,dc=roessner-net,dc=de
user_ldap       ldap_base_users ou=people,ou=it,dc=roessner-net,dc=de
user_ldap       ldap_cache_ttl  3600
user_ldap       ldap_configuration_active       1
user_ldap       ldap_display_name       cn
user_ldap       ldap_dn cn=webserver,ou=people,ou=it,dc=roessner-net,dc=de
user_ldap       ldap_dynamic_group_member_url
user_ldap       ldap_email_attr mail
user_ldap       ldap_experienced_admin  0
user_ldap       ldap_expert_username_attr       uniqueIdentifier
user_ldap       ldap_expert_uuid_group_attr     cn
user_ldap       ldap_expert_uuid_user_attr      uniqueIdentifier
user_ldap       ldap_group_display_name cn
user_ldap       ldap_group_filter       (&(|(objectclass=groupOfNames))(|(cn=NextCloudGroup)(cn=NextCloudSys4Group)))
user_ldap       ldap_group_filter_mode  0
user_ldap       ldap_group_member_assoc_attribute       member
user_ldap       ldap_groupfilter_groups NextCloudGroup
NextCloudSys4Group
user_ldap       ldap_groupfilter_objectclass    groupOfNames
user_ldap       ldap_host       localhost
user_ldap       ldap_login_filter       (|(uniqueIdentifier=%uid)(rnsMSRecipientAddress=%uid))
user_ldap       ldap_login_filter_mode  1
user_ldap       ldap_loginfilter_attributes
user_ldap       ldap_loginfilter_email  1
user_ldap       ldap_loginfilter_username       1
user_ldap       ldap_nested_groups      0
user_ldap       ldap_override_main_server
user_ldap       ldap_paging_size        500
user_ldap       ldap_port       389
user_ldap       ldap_quota_attr
user_ldap       ldap_quota_def
user_ldap       ldap_tls        0
user_ldap       ldap_turn_off_cert_check        1
user_ldap       ldap_turn_on_pwd_change 0
user_ldap       ldap_user_display_name_2
user_ldap       ldap_user_filter_mode   1
user_ldap       ldap_userfilter_groups  NextCloudGroup
NextCloudSys4Group
user_ldap       ldap_userfilter_objectclass     inetOrgPerson
user_ldap       ldap_userlist_filter    (&(|(objectclass=inetOrgPerson))(|(memberof=cn=NextCloudGroup,ou=people,ou=it,dc=roessner-net,dc=de)(memberof=cn=NextCloudSys4Group,ou=people,ou=it,dc=roessner-net,dc=de)))
user_ldap       types   authentication
user_ldap       use_memberof_to_detect_membership       1
```

### Logs
Unfortunately the occ command says it _would_ enable debug, but the resulting nextcloud.log is empty. Maybe this is due the fact that the config.php gets always killed by calling occ commands.

#### Web server error log
No log messages for localhost

#### Nextcloud log (data/nextcloud.log)
Does not exist

#### Browser log
-

**Comment by riegercloud** [comment] 2017-06-26 13:05
please provide your webserver and php.log information, if errors exist?!

**Comment by croessner** [comment] 2017-06-26 13:41
The webserver did not log any errors. I did manual upgrade on the command line. Unfortunately there does not exists any php.log on my system

**Comment by jospoortvliet** [comment] 2017-06-26 16:39
Hmmm, considering it complains about `$absolutePath must be relative to "files"` could this be related to https://github.com/nextcloud/server/pull/5507 ??

**Comment by nickvergessen** [comment] 2017-08-10 09:27
@croessner also nothing in data/*.log (maybe owncloud.log when you installed 9.0 or migrated from owncloud)?

Sorry for coming back so late. But it seems to happen more and more on updates.

**Comment by nickvergessen** [comment] 2017-08-10 09:28
Duplicate of #5219

**Closed by nickvergessen** 2017-08-10 09:28 UTC
