### ISSUE TITLE
Download link in versions opens file in OnlyOffice

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#25738] opened 2021-02-22 07:44 UTC
1) Create office type file, make changes
2) in file details, goto versions tab and click download arrow to see a previous version
3) file opens in OnlyOffice instead of downloading
 
While this still gets access to the file, it is not the old version as it has been ingested by OnlyOffice; where the file (for example) is originally in Open Document Format, there's no way to get the actual previous version as File Export As generates a new version.

Workaround and clue to fix: if you copy the link and paste into the URL bar and append `?download` the file then downloads as expected.

NC 20.0.7

**Comment by tomdereub** [comment] 2021-04-28 03:46
Quite the same issue for me, but with other type of files : when I click on download arrow, I get an error message : "format non supporté".
Thanks @putt1ck for the workaround with `?download`, it works.
NC 20.0.7

**Comment by yorados** [comment] 2021-05-27 21:21
same issue for me.
Storage Share 20.0.9
Thanks for the workaround

**Comment by benfrancis** [comment] 2021-06-01 18:28
I'm unable to reproduce this bug with an .odt file in Chromium or Firefox on Ubuntu Desktop. Tested with NextCloud 20.0.7 and 22.0.0 beta 2 (current master). Chromium immediately downloads the file and Firefox prompts the user to ask whether to open it in LibreOffice Writer or to save it.

Which browser and OS are you using?

**Comment by tomdereub** [comment] 2021-06-09 14:52
In my case :
- Nextcloud 20.0.8, installed on yunohost 4.2.5.3
- App nextcloud Onlyoffice 6.4.2
- App yunohost Onlyoffice 6.1.0~ynh1
- Firefox 89.0 on Windows 10

**Comment by yorados** [comment] 2021-06-10 19:49
In my case firefox 89 on ubuntu 20.4.2

**Comment by thmo** [comment] 2021-07-18 21:31
Same issue here, with Nextcloud 22.0.0 (self-hosted via docker), Onlyoffice App 7.0.4, Onlyoffice 6.3.1 (self-hosted via docker).

**Comment by szaimen** [comment] 2021-08-08 15:38
If I understand this issue correctly is this actually a feature of the OnlyOffice connector since 6.4.0:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/releases/tag/v6.4.0
So this needs to be fixed in the onlyoffice connector either way.

**Closed by szaimen** 2021-08-08 15:38 UTC
Labels: bug, good first issue, 0. Needs triage, feature: versions
