### ISSUE TITLE
[Bug]: Directory Name Not Automatically Updated After Renaming Without Browser Refresh

### ISSUE THREAD

**Issue by fhongtao** [nextcloud/server#47608] opened 2024-08-29 12:40 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Description:

Hello Nextcloud Team,

I've encountered an issue where renaming a directory does not automatically update the name in the file view. The new name only appears after manually refreshing the browser.

### Steps to reproduce

Steps to Reproduce:

Log in to Nextcloud as a regular user or admin.
Create a new directory in your file space.
Rename the directory to a different name.
Observe that the old name remains displayed.
Refresh the browser manually to see the updated directory name.

### Expected behavior

Expected Behavior: The directory name should update immediately after renaming without needing to refresh the browser.

Actual Behavior: The old directory name remains visible until the browser is refreshed.

Environment:

Nextcloud version: 29.0.4
PHP version: (please fill in)
Database version: (please fill in)
Web server: (please fill in)
Thank you for your assistance!

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by fhongtao** [comment] 2024-08-30 01:51
thanks

**Comment by joshtrichards** [comment] 2024-08-30 15:56
Duplicate of #46604

Already fixed #46690 in 29.0.5

**Closed by joshtrichards** 2024-08-30 15:56 UTC
Labels: bug, needs info, 0. Needs triage, 29-feedback
