### ISSUE TITLE
Hide contacts to others users in contact form

### ISSUE THREAD

**Issue by jimbowarrior** [nextcloud/server#6259] opened 2017-08-25 09:57 UTC
Hello,

### Steps to reproduce
1. log with user1
2. click contact form
3. user1 see all users

### Expected behaviour
user1+user2 are into group1
user3 must not see user2 and user1 because user3 is into group3
We would like hide contacts from contact search form only for users into differents group.
Users can see all users registered on this server. Users should see only user in the same group.

### Actual behaviour
all user can see all user even if there are in others groups

### Server configuration

**Operating system**: Ubuntu 16.04 last update

**Web server:**

 Apache 2.4.18

**Database:**

 mysql 5.7.19

**PHP version:** 

7

**Nextcloud version:** (see Nextcloud admin page)

12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

update from Nextcloud 10

**Where did you install Nextcloud from:**

from tar.gz

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

collabora online

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

"system": {
        "instanceid": 
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "blabla.com",
              ],
        "datadirectory": "\/nextcloudcloud1\/data",
        "overwrite.cli.url": "https:\/\/blablab.com",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        }

**Are you using external storage, if yes which one:** local/smb/sftp/...

nfs4

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

all

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

Regards,

**Comment by hitam4450** [comment] 2017-08-25 11:47
I agree and support the argument!

**Comment by jimbowarrior** [comment] 2017-08-25 20:17
Same issue on fresh install

**Comment by xraMsamohT** [comment] 2017-08-25 21:08
Duplicate of #5107

**Comment by xraMsamohT** [comment] 2017-08-25 21:09
Duplicate of #5107

**Comment by MorrisJobke** [comment] 2017-08-30 10:56
> Duplicate of #5107

Correct

**Closed by MorrisJobke** 2017-08-30 10:56 UTC
