### ISSUE TITLE
Configuration check - Minor typo: occ db:add-missing-indices

### ISSUE THREAD

**Issue by olliware** [nextcloud/server#10656] opened 2018-08-12 07:26 UTC
After updating to 14.0 Beta 3 I noticed a small typo which shows the given fix:

**ooc db:add-missing-indices**

Of course the line

**occ db:add-missing-indices**

is meant here. Nothing serious, just trying to be a little bit fussy here :-) !

<img width="1096" alt="bildschirmfoto 2018-08-12 um 09 16 22" src="https://user-images.githubusercontent.com/42076599/43999671-6d1e66ce-9e11-11e8-87d8-283fc73fe4ce.png">

**Comment by danielkesselberg** [comment] 2018-08-12 17:30
Duplicate of #10638

**Comment by rullzer** [comment] 2018-08-13 09:35
Already fixed on transifex. Should be synced soon and in beta4

**Closed by rullzer** 2018-08-13 09:35 UTC
Labels: bug, design
