### ISSUE TITLE
Getting 'PDF.js build: 228a591c Invalid PDF structure' only on files in a particular folder

### ISSUE THREAD

**Issue by ttblum** [nextcloud/server#25508] opened 2021-02-05 18:03 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Under one particular publicly shared folder we are unable to view any PDF files, it results in the error:  

Invalid or corrupted PDF file. Less Information 
PDF.js v2.4.456 (build: 228a591c) Message: Invalid PDF structure.

All PDF files in all folders beneath this public share result in the same error message when clicked on. 
Other types of files such as PNG open OK.

So far we are able to view PDF files in every other publicly shared folder, this happening on one folder only and all the folders beneath it.  There are no special characters in the folder name.

2. This has already been reported here: https://ask.linuxmuster.net/t/nextcloud-update-auf-20-0-7-fehler-bei-pdf/6980/3

### Expected behaviour
The PDF should be displayed within the browser

### Actual behaviour
Error message:
Invalid or corrupted PDF file. Less Information 
PDF.js v2.4.456 (build: 228a591c) Message: Invalid PDF structure.

### Server configuration

**Operating system:**
Ubuntu 20.04.1 LTS

**Web server:**
apache2 2.4.41-4ubuntu3

**Database:**
mariadb-server-10.3 1:10.3.22-1ubuntu1

**PHP version:**
2:7.4+75

**Nextcloud version:** (see Nextcloud admin page)
20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
Auto-updated from 20.0.6

**Where did you install Nextcloud from:**
It auto-updated

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Accessibility	1.6.0	Featured	
Activity	2.13.4	Featured	
Collaborative tags	1.10.0	Featured	
Comments	1.10.0	Featured	
Contacts Interaction	1.1.0	Featured	
Dashboard	7.0.0	Featured	
Deleted files	1.10.1	Featured	
Federation	1.10.1	Featured	
File sharing	1.12.2	Featured	
First run wizard	2.9.0	Featured	
LDAP user and group backend	1.10.2	Featured	
Log Reader	2.5.0	Featured	
Monitoring	1.10.0	Featured	
Nextcloud announcements	1.9.0	Featured	
Notifications	2.8.0	Featured	
Password policy	1.10.1	Featured	
PDF viewer	2.0.1	Featured	
Photos	1.2.3	Featured	
Privacy	1.4.0	Featured	
Recommendations	0.8.0	Featured	
Right click	0.17.0	Featured	
Share by mail	1.10.0	Featured	
Support	1.3.0	Featured	
Text	3.1.0	Featured	
Theming	1.11.0	Featured	
Two-Factor Admin Support	3.0.0		
Two-Factor TOTP Provider	5.0.0	Featured	
Two-Factor U2F	6.1.0	Featured	
Usage survey	1.8.0	Featured	
User status	1.0.1	Featured	
Versions	1.13.0	Featured	
Video player	1.9.0	Featured	
Weather status	1.0.0
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
nextcloud.occ app:list
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_admin: 3.0.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.1.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Running on Ubuntu in a Snap container
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

nextcloud.occ config:list system
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "FQDN"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "https:\/\/FQDN",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "NTLM",
        "theme": "",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```


### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

### Logs
apache_access.log and apache_errs.log don't show any errors that I can find

<!--- Reports without logs might be closed as unqualified reports! -->

```

```
</details>

**Comment by kesselb** [comment] 2021-02-05 20:46
Duplicate of https://github.com/nextcloud/files_pdfviewer/issues/286

**Closed by kesselb** 2021-02-05 20:46 UTC
Labels: 0. Needs triage, bug
