### ISSUE TITLE
Apps in header

### ISSUE THREAD

**Issue by hhhppp28** [nextcloud/server#15773] opened 2019-05-28 13:50 UTC
Hi,
it would be good to see all the apps in the header and not only 7 icons and the rest is in more.
Is´s enough pace for all icons.

Thanks
HP

**Comment by georgehrke** [comment] 2019-05-29 16:10
Duplicate of https://github.com/nextcloud/server/issues/13079

Please support us by helping for duplicates before creating new issues. Thx!

**Closed by georgehrke** 2019-05-29 16:10 UTC
Labels: 0. Needs triage, enhancement
