### ISSUE TITLE
spaces in login causes iOS caldav login errors

### ISSUE THREAD

**Issue by cquest** [nextcloud/server#21216] opened 2020-06-03 18:06 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. create a new account with a space in the login name
2. try to create the account on iOS
3.

### Expected behaviour
Login should be accepted on the iPhone

### Actual behaviour
iOS report an SSL connection error
On the server side, a PROPFIND is visible in the server log with a 207 http status code returned.
iOS accountd should then issue an OPTIONS request, but does not in such a case (iOS bug ?)

### Server configuration

**Operating system:** debian 10

**Web server:** apache

**Database:** mysql

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** turnkey

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.1
  - documentserver_community: 0.1.5
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.4.1
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_fulltextsearch_tesseract: 1.4.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trackdownloads: 1.7.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - forms: 1.1.1
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.5
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.ecologie-democratie-solidarite.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "onlyoffice": {
            "DocumentServerUrl --value=\"\/ds-vpath\/\"": "",
            "DocumentServerInternalUrl --value=\"http:\/\/<onlyoffice_documentserver>\/\"": "",
            "StorageUrl --value=\"http:\/\/<nextcloud-web-adress>\/\"": ""
        },
        "overwritehost": "nextcloud.ecologie-democratie-solidarite.fr",
        "overwriteprotocol": "https",
        "default_locale": "fr_FR",
        "default_language": "fr",
        "appstoreenabled": true,
        "forwarded_for_headers": [
            "HTTP_X_REAL_IP",
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "maintenance": false,
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** iOS accountd

**Operating system:** iOS 13.5

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Nils160988** [comment] 2020-06-05 11:45
Thanks for reporting!
Duplicate of https://github.com/nextcloud/server/issues/15641

**Closed by Nils160988** 2020-06-05 11:45 UTC
Labels: 0. Needs triage, bug

**Comment by RafalLukawiecki** [comment] 2020-06-27 17:18
> Edit: Userids should not contain spaces (in contrast to the displayname) as stated in the documentation (https://docs.nextcloud.com/server/19/admin_manual/configuration_user/user_configuration.html) although this is not technically restricted.

I am affected by this issue, however, I cannot see where in the documentation does it state that usernames must not have spaces in them. Perhaps that is missing there? Besides, I did not get any warnings when creating the user.

Is there a procedure, even a very manual one, for renaming the username to remove the space? Many thanks.
