### ISSUE TITLE
some filetype font icons are not rendering in nextcloud 11

### ISSUE THREAD

**Issue by JarbyDev** [nextcloud/server#2857] opened 2016-12-25 14:08 UTC
Some Filetypes font icons are not rendering in nextcloud 11 see pic

![image](https://cloud.githubusercontent.com/assets/11229573/21471399/e5df6b7e-ca7f-11e6-8ce2-56a9e2f83d1d.png)

and the filetype exist in the server. 

Using Ubuntu 16.04 - nextclou 11

Operating system: Ubuntu 16.04

Web server: Apache 2.4.18

Database: Maria DB 10.1.20

PHP version: 7.0.8

Nextcloud version: 11.0.0 (stable)

Updated from an older Nextcloud/ownCloud or fresh install: Fresh

Where did you install Nextcloud from: Nextcloud website.

Signing status: no issues.

List of activated apps:
Default to installation.

The content of config.
Default

Are you using external storage, if yes which one: None

Are you using encryption: no

Browser: Firefox, Edge, chrome latest versions

Operating system: Windows 10
Logs empty
``

**Comment by jojom4n** [comment] 2017-01-06 01:11
Same as me for #2962, but in my case I cannot see **any** icon, while you see the PDF here. I did see them when I installed Nextcloud, then I deleted the default skeleton files, uploaded my real ones and it's all white.

**Comment by MorrisJobke** [comment] 2017-01-20 01:35
Can I ask you to open the web developers tools in your browser(press F12) and refresh the page? Is there anything written in red in the "console" tab? Then switch to the network tab and filter for "Images" (see screenshot there are multiple option - in Chrome it's abbreviated as "Img"):

![bildschirmfoto 2017-01-19 um 19 33 57](https://cloud.githubusercontent.com/assets/245432/22132234/61831660-de7e-11e6-9dd6-260e6d92ce1c.png)

Is there anything in this list not having the status 200 or 30x?

**Comment by MorrisJobke** [comment] 2017-01-31 02:38
I will reopen once the requested information is available.

**Comment by JarbyDev** [comment] 2017-01-31 16:21
console tab have the following error messages

![image](https://cloud.githubusercontent.com/assets/11229573/22473555/444e06b8-e7a7-11e6-925a-6507172fb31b.png)

and in network images  all are status 304

**Comment by MorrisJobke** [comment] 2017-01-31 19:08
The 2 red entries need to come from an browser extension. We ship all our dependencies and don't use any CDN. Also we don't use Material Icons, nor Fontawesome.

<img width="357" alt="bildschirmfoto 2017-01-31 um 13 06 22" src="https://cloud.githubusercontent.com/assets/245432/22480176/15b50982-e7b6-11e6-9c58-729c6b4720ad.png">

That one is suspicious. Could you disable the theming app temporarily? And maybe also try to open the page in private mode of your browser, so that no extensions are loaded.

Thanks

**Comment by MorrisJobke** [comment] 2017-05-11 16:24
Closing because of missing feedback for 3,5 months and we can't reproduce this locally.

**Closed by MorrisJobke** 2017-05-11 16:24 UTC
Labels: needs info

**Comment by cromg** [comment] 2017-08-02 21:04
disable the theming don't solve the problem, but now my menu on the left is crayz =D
