### ISSUE TITLE
[Bug]: NC 25 RC3 Folder icons keep disappearing 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#34455] opened 2022-10-06 17:33 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

NC 25 Folder icons keep disappearing 

### Steps to reproduce

https://user-images.githubusercontent.com/59488153/194379522-44799606-7c09-4658-a9f2-1bc9d1ba883e.mp4

### Expected behavior

Should not do this

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

### Additional info

![image](https://user-images.githubusercontent.com/59488153/194380336-0b261d06-0ee6-4e28-9f31-199dbdd4d1ff.png)
![image](https://user-images.githubusercontent.com/59488153/194380519-5cf646ed-0731-4e41-ab71-b26aabb195b1.png)

**Comment by blizzz** [comment] 2022-10-06 21:20
For it returns 500, there should be related entries in nextcloud.log. I cannot reproduce it though.

**Comment by andyxheli** [comment] 2022-10-06 21:51
Hmmmm let me see if I can find anything in the logs. Just started to happen

**Comment by andyxheli** [comment] 2022-10-07 15:26
Hey @blizzz here the error im getting 
[nextcloud.log](https://github.com/nextcloud/server/files/9735188/nextcloud.log)


![image](https://user-images.githubusercontent.com/59488153/194590899-e2f70107-c461-404d-9f04-f63f8f365441.png)

**Comment by blizzz** [comment] 2022-10-07 17:57
@andyxheli can you double-check that the data dir (and the subfolders) are writable for the web-user (www-data on debian/ubuntu)?

**Comment by andyxheli** [comment] 2022-10-07 18:05
Sure can! Yes, everything looks good permissions wise 

![image](https://user-images.githubusercontent.com/59488153/194621663-61e57213-6105-4ec0-ba4c-cf9d9b694bea.png)

**Comment by CarlSchwan** [comment] 2022-10-11 21:06
Related log from #34259 

```
{"reqId":"OEX9lttuXShOdBBg5khW","level":3,"time":"2022-10-11T14:43:43+00:00","remoteAddr":"10.0.10.90","user":"axheli","app":"PHP","method":"GET","url":"/apps/theming/img/core/filetypes/folder.svg?v=7401","message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7405/icon-core-filetypes_folder.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.15","exception":{"Exception":"Error","Message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7405/icon-core-filetypes_folder.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":303,"function":"file_get_contents"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1181,"function":"file_get_contents","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":600,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":56,"function":"file_get_contents","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/NewSimpleFile.php","line":97,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/FileDisplayResponse.php","line":68,"function":"getContent","class":"OC\\Files\\SimpleFS\\NewSimpleFile","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":229,"function":"callback","class":"OCP\\AppFramework\\Http\\FileDisplayResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6345883c5419c"}
{"reqId":"vmOH7L07XjazACxLGUg9","level":3,"time":"2022-10-11T15:02:17+00:00","remoteAddr":"10.0.10.90","user":"axheli","app":"PHP","method":"GET","url":"/apps/theming/img/core/filetypes/x-office-spreadsheet.svg?v=7924","message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7928/icon-core-filetypes_x-office-spreadsheet.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.15","exception":{"Exception":"Error","Message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7928/icon-core-filetypes_x-office-spreadsheet.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":303,"function":"file_get_contents"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1181,"function":"file_get_contents","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":600,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":56,"function":"file_get_contents","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/NewSimpleFile.php","line":97,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/FileDisplayResponse.php","line":68,"function":"getContent","class":"OC\\Files\\SimpleFS\\NewSimpleFile","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":229,"function":"callback","class":"OCP\\AppFramework\\Http\\FileDisplayResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6345883c53144"}

{"reqId":"h2gc5fDiDPgw1synuck5","level":3,"time":"2022-10-11T15:05:26+00:00","remoteAddr":"10.0.10.90","user":"axheli","app":"PHP","method":"GET","url":"/apps/theming/img/groupfolders/folder-group.svg?v=7976","message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7980/icon-groupfolders-folder-group.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.15","exception":{"Exception":"Error","Message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7980/icon-groupfolders-folder-group.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":303,"function":"file_get_contents"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1181,"function":"file_get_contents","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":600,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":56,"function":"file_get_contents","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/NewSimpleFile.php","line":97,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/FileDisplayResponse.php","line":68,"function":"getContent","class":"OC\\Files\\SimpleFS\\NewSimpleFile","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":229,"function":"callback","class":"OCP\\AppFramework\\Http\\FileDisplayResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6345883c522eb"}

{"reqId":"pkQ0mWhiaVsmoOzBzYRx","level":3,"time":"2022-10-11T14:44:10+00:00","remoteAddr":"10.0.10.90","user":"axheli","app":"PHP","method":"GET","url":"/apps/theming/img/core/filetypes/x-office-spreadsheet.svg?v=7437","message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7441/icon-core-filetypes_x-office-spreadsheet.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.15","exception":{"Exception":"Error","Message":"file_get_contents(/var/data/appdata_ocxs1gtpahaq/theming/7441/icon-core-filetypes_x-office-spreadsheet.svg): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#303","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":303,"function":"file_get_contents"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1181,"function":"file_get_contents","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":600,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":56,"function":"file_get_contents","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/NewSimpleFile.php","line":97,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/FileDisplayResponse.php","line":68,"function":"getContent","class":"OC\\Files\\SimpleFS\\NewSimpleFile","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":229,"function":"callback","class":"OCP\\AppFramework\\Http\\FileDisplayResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6345883c53ef3"}
``

**Comment by come-nc** [comment] 2022-10-13 09:26
> Sure can! Yes, everything looks good permissions wise. Running Ubuntu Server 20.04

What about in `/var/data/appdata_ocxs1gtpahaq/theming/` ?

**Comment by skjnldsv** [comment] 2022-10-13 16:20
https://github.com/nextcloud/server/blob/fb7f65a687ba426188148b3ebbf295ee307c7bc4/apps/theming/lib/ImageManager.php#L178
https://github.com/nextcloud/server/blob/fb7f65a687ba426188148b3ebbf295ee307c7bc4/apps/theming/lib/ImageManager.php#L159

This is linked to the cachebuster issue: https://github.com/nextcloud/server/pull/34543
Fixed in upcoming releases, feel free to apply the patch to try it yourself
https://github.com/nextcloud/server/pull/34543.patch

**Closed by skjnldsv** 2022-10-13 16:20 UTC
Labels: bug, 0. Needs triage, 25-feedback

**Comment by andyxheli** [comment] 2022-10-13 16:24
Working on that now @skjnldsv

**Comment by andyxheli** [comment] 2022-10-13 16:47
Just applied this patch on my NC 25 RC3. As of right now the Icons are back and no longer seeing the below errors. Patch was applied 6 min ago error logs show from 41 min to an hour ago 

![image](https://user-images.githubusercontent.com/59488153/195656754-0f197346-216d-4483-98dd-aca183a4293d.png)
