### ISSUE TITLE
migration from nextcloud 16 to 18 causes all shared mp4 files with a # hashtag character to break

### ISSUE THREAD

**Issue by tuxcrafter** [nextcloud/server#21673] opened 2020-07-03 14:53 UTC
Hello everybody,

I have a lot of files with a # hashtag character and we upgraded our server from nextcloud 16 to nextcloud 18 and all the mp4 videos that where shared with a # hashtag in their name stopped working for the people that received the shared url.

How can we get our files to work again without renaming all the documents?

**Comment by szaimen** [comment] 2021-06-07 18:48
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 18:48 UTC
Labels: 0. Needs triage, bug, feature: files
