### ISSUE TITLE
Name too long for external share

### ISSUE THREAD

**Issue by cedk** [nextcloud/server#21376] opened 2020-06-11 16:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a folder with name with more than 64 chars
2. Add the folder to another Nextcloud instance

### Expected behaviour
The external folder should be mounted on the other instance.

### Actual behaviour
An error is raised "Failed to add the public link to your Nextcloud"

On the remote server, this is logged: 

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_share_external"`
("remote","share_token","password","name","owner","user","mountpoint","mountpoint_hash","accepted","remote_id","share_type") SELECT ?,?,?,?,?,?,?,?,?,?,? FROM "oc_share_external" WHERE "user" = ? AND "mountpoint_hash" = ? HAVING COUNT(*) = 0' with params ["http:\/\/example.com\/", "xxxxxxxxxxx", "", "<long folder name>", "foo@example.com", "bar", "{{TemporaryMountPointName#\/<long folder name>}}", "xxxxxxxxx", 0, 11, 0, "bar", "xxxxxxxxxxxxx"]: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(64)
```

I think the constraint of 64 chars in share_external name is too small. It should be the same as for the folder names.

**Comment by kesselb** [comment] 2020-06-11 19:21
cc @nextcloud/sharing

**Comment by szaimen** [comment] 2021-06-02 12:34
Duplicate of https://github.com/nextcloud/server/issues/19635

**Closed by szaimen** 2021-06-02 12:34 UTC
Labels: 0. Needs triage, bug
