### ISSUE TITLE
Refresh page when using Office does not re-open document

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#31312] opened 2022-02-22 06:31 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Upon pressing reload Nextcloud office at some point does not reload document, but shows only folder listings.

### Steps to reproduce

1. open https://cloud.nextcloud.com/apps/files/?dir=/temp&openfile=5637314
2. press f5 -> https://cloud.nextcloud.com/apps/files/?dir=/temp&fileid=125596
3. press f5 -> https://cloud.nextcloud.com/apps/files/?dir=/temp

### Expected behavior

Even after multiple reloads (no hard refresh) Nextcloud should show document.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
It is our c.nc.c
```

**Comment by szaimen** [comment] 2023-01-23 13:20
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by tobiasKaminsky** [comment] 2023-01-27 13:20
Still on c.nc.c / NC 25.

(as you can see there was no single interaction, how could this be resolved by its own?)

**Comment by szaimen** [comment] 2023-01-27 13:22
Sometimes things get fixed and issues not closed, that is why.

**Comment by skjnldsv** [comment] 2024-08-01 05:24
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-08-01 05:24 UTC
Labels: bug, 0. Needs triage, feature: files, 25-feedback, 26-feedback
