### ISSUE TITLE
update "cancel" button

### ISSUE THREAD

**Issue by fabian727** [nextcloud/server#13686] opened 2019-01-19 11:16 UTC
Hi guys,

I wanted to update my nextcloud today. Seems like your SSL Certificate expired again.

Please fix it.

Thanks,
Fabian

P.s.: I tried updating with the web-gui/-installer. Now that it failed, I only have the option to retry the download. There is no button for canceling and going back to normal business. This would be more easy for not-computer-scientists, than retyping the url to get the settings-web-gui.

**Comment by d3v3l15h** [comment] 2019-01-19 11:38
Hi,

Same here. Thanks in advance for the fix.

Could be great to automate your Letsencrypt certificate renewal, no ?

EM

**Comment by sanmue** [comment] 2019-01-19 12:19
Same problem here.

**Comment by fabian727** [comment] 2019-01-19 22:51
ssl certificate works again. Thanks for that.

Now the only thing I want the next time at an abort of the update is a "cancel" or "undo" or "return" button. Would be of more comfort.

Thanks guys for your great work 'til yet

**Comment by violoncelloCH** [comment] 2019-01-19 23:14
for the certificate renewal: duplicate of #11955
for the suggested cancel/back button: please create a feature request in the corresponding repository for the updater in https://github.com/nextcloud/updater

**Closed by violoncelloCH** 2019-01-19 23:14 UTC
Labels: 0. Needs triage, bug
