### ISSUE TITLE
Can't edit own account settings

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#20231] opened 2020-03-30 14:29 UTC
With the latest version of Nextcloud 18, I can't edit the settings for my own account, see in the screenshot how the option is missing for myself which is there for the other user. We are both admins, of your.  

So I can't change my own group memberships, my own quota or any other settings. The "edit" button is simply not there. See screenshot.

So I have to use occ for any changes... 

![Nextcloud account settings](https://user-images.githubusercontent.com/3313208/77923966-6b151180-72a3-11ea-8abc-594feaac2e21.png)

**Comment by kesselb** [comment] 2020-03-30 15:56
Take "Can't edit own account settings", put it into the search and also look for closed issues.

**Comment by kesselb** [comment] 2020-03-30 15:57
Closing as duplicate of https://github.com/nextcloud/server/issues/19004

**Closed by kesselb** 2020-03-30 15:57 UTC
Labels: 0. Needs triage, bug

**Comment by vasyugan** [comment] 2020-03-30 16:12
> 
> 
> Take "Can't edit own account settings", put it into the search and also look for closed issues.

I did precisesly that. Actually I didn't search closed issues, but I did search issues before submitting.
