### ISSUE TITLE
Files uploaded into a file drop share are not being broken into chunks

### ISSUE THREAD

**Issue by Emi94** [nextcloud/server#12206] opened 2018-11-02 07:10 UTC
### Steps to reproduce
1. Share a folder by link for file drop
2. Upload a file at the link provided by the share

### Expected behaviour
During the upload the file should be broken into chunks of 10MB while the file is being written into the temporary directory

### Actual behaviour
The file is being uploaded entirely into the temporary folder, and just when finished it is being moved into the actual Nextcloud data folder. Since I have the Nextcloud data folder on a separate partition, when uploading a big file the root partition is being filled up and the upload fails. Note: this doesn't happen when uploading directly into my personal folders, just on a file drop share.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** PostgreSQL 9.5

**PHP version:** 7.0

**Nextcloud version:** 14.0.3

**Comment by MorrisJobke** [comment] 2018-11-02 11:13
Duplicate of #4109

**Closed by MorrisJobke** 2018-11-02 11:13 UTC
Labels: bug, feature: files, feature: sharing
