### ISSUE TITLE
[Bug]: Selecting a blank background on theming doesn't work on login screen

### ISSUE THREAD

**Issue by muchahagrande** [nextcloud/server#34968] opened 2022-11-04 13:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the last update from 25.0.0 to 25.0.1 theming blank background doesn't work for login screen.
I use a blank background for the login screen, but now it is showing the default Nextcloud background photo (the cloudy sky).
If I chose an image it works, but it doesn't work with a blank background.
The blank background does show on main user screen once legged in.

### Steps to reproduce

1. Login to admin account
2. Navigate to theming administration configuration
3. Select a background color and remove any existing background image
4. Logout

### Expected behavior

It should show a blank colored background, but it shows the default Nextcloud background photo of the clouds and the sky.

### Installation method

Community VM appliance

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "x.x.x.x",
            "cloud.xxx.com",
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.xxx.com\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto, 180",
        "activity_expire_days": "120",
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "us",
        "logtimezone": "America\/Argentina\/Buenos_Aires",
        "default_language": "es_AR",
        "force_language": "es_AR",
        "default_locale": "es_AR",
        "force_locale": "es_AR",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": false,
        "lost_password_link": "disabled",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Krita",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Epub"
        ],
        "preview_imaginary_url": "http:\/\/127.0.0.1:9001",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "skeletondirectory": "",
        "theme": "",
        "filesystem_check_changes": true,
        "app_install_overwrite": [
            "passwords",
            "backup",
            "extract",
            "keeweb",
            "metadata",
            "phonetrack",
            "socialsharing_email"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bookmarks: 11.0.4
  - bruteforcesettings: 2.5.0
  - calendar: 4.1.0
  - cfg_share_links: 3.0.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - keeweb: 0.6.10
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.0
  - maps: 0.2.1
  - metadata: 0.17.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2022.11.20-build4610
  - phonetrack: 0.7.2
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - qownnotesapi: 22.10.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - socialsharing_email: 2.5.0
  - spreed: 15.0.1
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_nextcloud_notification: 3.5.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - backup: 1.1.3
  - encryption
  - firstrunwizard: 2.13.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
No log lines on this subject
```

### Additional info

Occurred on last update from 25.0.0 to 25.0.1.

**Comment by wuffleton** [comment] 2022-11-06 19:45
Looked into this since can confirm on my instance and was bothered by the default image being much brighter than my solid background - here's what I found in case it helps with this bug or those looking for a quick workaround.

It looks like this CSS rule is winning, which causes the theme's solid background setting to be ignored: https://github.com/nextcloud/server/blob/7f2c21f05658128e5dbefd4d64a6cdbdf9334631/core/css/guest.css#L27 

Unsure how correct this is, since I'm not all that familiar with SCSS and its use in Nextcloud, but changing it to what apps.scss has here from the same commit fixed it for me: https://github.com/nextcloud/server/blob/7f2c21f05658128e5dbefd4d64a6cdbdf9334631/core/css/apps.scss#L50

**Comment by CyberianIce** [comment] 2022-11-07 08:30
Bug confirmed. Instead of solid color default image is displayed on login screen.

**Comment by PVince81** [comment] 2022-11-17 13:37
I've checked in Nextcloud 24 and the database contains a value "backgroundMime=backgroundColor" for the theming app in oc_appconfig.

So in Nextcloud 25 this setting is probably not properly respected any more.

**Closed** 2022-11-19 22:45 UTC
Labels: bug, 3. to review, feature: theming, regression, 25-feedback
