### ISSUE TITLE
Read only share shows option to share and delete files

### ISSUE THREAD

**Issue by Anthrazz** [nextcloud/server#18903] opened 2020-01-15 07:52 UTC
### Steps to reproduce
1. Share a folder per link, make sure "Read only" is active
2. Open Shared Link
3. Right click on a file and select "Share file"
4. Select a file and delete it via right click menu or the file actions at the top of the page

### Expected behaviour
No delete and share option should be visible.

### Actual behaviour
Delete option is visible. A click does delete the file in the webinterface until a page reload occurs. The DELETE API call do return a 404 error.

Share Option does not respond.

### Server configuration

**Operating system:** Ubuntu Server 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** PHP 7.3.13

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Public Nextcloud Docker Image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Delete Call:

client.js:250 DELETE https://example.com/public.php/webdav/Coast.jpg 404
jquery.js:8630 GET https://example.com/index.php/apps/files/ajax/getstoragestats.php 401
```
</details>

**Comment by szaimen** [comment] 2021-05-28 10:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-28 10:17 UTC
Labels: 0. Needs triage, bug, papercut
