### ISSUE TITLE
"Call to a member function getId() on array" in remote.php

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/server#27095] opened 2021-05-25 08:53 UTC
```
{
  "reqId": "abcdef",
  "level": 4,
  "time": "2021-05-25T10:41:39+02:00",
  "remoteAddr": "1.2.3.4",
  "user": "myuser",
  "app": "webdav",
  "method": "DELETE",
  "url": "/remote.php/dav/files/myuser/locks/sync_desktop_4711.json",
  "message": {
    "Exception": "Error",
    "Message": "Call to a member function getId() on array",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Cache/Updater.php",
        "line": 160,
        "function": "remove",
        "class": "OC\\Files\\Cache\\Cache",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/View.php",
        "line": 330,
        "function": "remove",
        "class": "OC\\Files\\Cache\\Updater",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/View.php",
        "line": 1180,
        "function": "removeUpdate",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/View.php",
        "line": 725,
        "function": "basicOperation",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
        "line": 466,
        "function": "unlink",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 179,
        "function": "delete",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 281,
        "function": "delete",
        "class": "Sabre\\DAV\\Tree",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpDelete",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/lib/Server.php",
        "line": 332,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/remote.php",
        "line": 167,
        "args": [
          "/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/nextcloud/lib/private/Files/Cache/Cache.php",
    "Line": 541,
    "CustomMessage": "--"
  },
  "userAgent": "Joplin/1.0",
  "version": "21.0.2.1"
}
```

**Comment by kesselb** [comment] 2021-05-25 09:28
Duplicate of https://github.com/nextcloud/server/issues/26544

**Closed by kesselb** 2021-05-25 09:28 UTC
Labels: 0. Needs triage, bug
