### ISSUE TITLE
File sharing: Drop only (file upload) also for sharing with registered accounts

### ISSUE THREAD

**Issue by msfuture** [nextcloud/server#23604] opened 2020-10-21 09:42 UTC
**Describe the solution you'd like**
When sharing a folder with another registered user, we only want this user to be able to create files, but not view the contents of the folder. This is possible when using sharing via link, but not when sharing with a user.
This feature is really necessary for schools, when you want to collect work from your students. Collecting via Talk or students sharing their solution with the teacher directly ends in chaos, when you have to work with about 200 students in 7+ classes in one week. So blocking the possibility of viewing files in a shared folder (like the one via link) would be a great enhancement for all schools.

- user (teacher) shares "drop"-folder with class-group
- class/student can upload (create) files in the folder but not see the contents (like file drop / upload only via link sharing)
- teacher sees all uploads and can download/edit them

**Describe alternatives you've considered**
Currently we're using the filedrop via link, but this is not very user friendly on the students side. Links have to be published and students cannot upload the files using the nextcloud app (thus sharing from any other app like a camscanner or something). Many students and parents are struggling with this. Collection via talk leads to 200+ conversations with a file chaos in the "Talk" folder.

**Comment by GAS85** [comment] 2020-12-01 11:45
Hey, you can try to use combination of 2 apps:
1. https://apps.nextcloud.com/apps/files_automatedtagging set Tag on a uploaded files
2. here are 2 options:
2.a. https://apps.nextcloud.com/apps/files_accesscontrol setup access based on TAG, that nobody can download or modify a file besides some users (e.g. belongs to group "teachers")
2.b. https://apps.nextcloud.com/apps/workflow_script write s simple script that will move data to the folder that other users have no access to.

**Comment by szaimen** [comment] 2021-06-18 12:05
Duplicate of https://github.com/nextcloud/server/issues/16515

**Closed by szaimen** 2021-06-18 12:05 UTC
Labels: 0. Needs triage, enhancement
