### ISSUE TITLE
Apostrophe in file name breaks playing video in share link

### ISSUE THREAD

**Issue by benqrn** [nextcloud/server#22152] opened 2020-08-08 02:00 UTC
This _should_ be fairly easy to reproduce:

A video filename that contains an apostrophe (example `Bob's Video.mp4`) will play fine using the built in media player while logged in as a user.  However, if said video is in a folder that is shared, and then you visit the share url, and click the same video file name that contains an apostrophe, a black video box is displayed with the message:  "The media could not be loaded, either because the server or network failed or because the format is not supported."

Removing the apostrophe from the file name resolves the issue without re-creating the share link.  Refreshing the page and selecting the updated file that no longer has an apostrophe will play fine in the built in media player.

In the web page debug I can see it constructs a media resource url encoding that file name like this:  `Bob&#039;s%20Video.mp4`

I am using NextCloud 16.0.11 and PHP 7.2

**Comment by szaimen** [comment] 2021-06-08 09:41
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-08 09:41 UTC
Labels: 0. Needs triage, bug
