### ISSUE TITLE
Checkbox select all during a search does not work properly

### ISSUE THREAD

**Issue by Floflobel** [nextcloud/server#7274] opened 2017-11-24 10:19 UTC
### Steps to reproduce

1. search for a file or directory from the search box on the top right
2. select all file and folder by ticking the checkbox located on the left of the "Name" column
3. select all content by ticking the checkbox next to "Name" column.

![step_1](https://user-images.githubusercontent.com/13889750/33204593-5eaccf0c-d104-11e7-860b-3f160f44a422.png)
![step_2](https://user-images.githubusercontent.com/13889750/33205907-d7f7200c-d108-11e7-981e-755d1fb4e674.png)
![step_3](https://user-images.githubusercontent.com/13889750/33204592-5e906dbc-d104-11e7-807c-8d59e674dea1.png)

### Actual behaviour

I browse to a folder named ABC for example.
When I perform a search by typing a name in the search field located on the top right, the search result is displayed.
Then, I select all files and folders by ticking the checkbox “folders and files” (in order to download all files and folders from my search result).
But when clicking on “Download”, instead of downloading all folders and files that appear on the screeen, a download of ALL folders and files from the ABC folder is performed.

### Expected behaviour

When I tick the checkbox “folders and files”, I just want to download all the folders and files displayed on the screen (which correspond to my search).

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** apache2 2.4.18

**Database:** postgresql-9.6

**PHP version:** PHP 7.0.22

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.6
  - password_policy: 1.2.2
  - polls: 0.8.0
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/srv\/nextcloud-data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbport": "5432",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 1.5,
            "dbindex": 0
        },
        "logtimezone": "Europe\/Paris",
        "loglevel": 2,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logdateformat": "Y-m-d H:i:s T",
        "log_query": false,
        "log_authfailip": false,
        "log_rotate_size": 104857600,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "gmail.com",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes with reverse proxy apache

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla Firefox 57

**Operating system:** Fedora 27

**Comment by MorrisJobke** [comment] 2017-11-24 13:27
Duplicate of #2075

**Closed by MorrisJobke** 2017-11-24 13:27 UTC
