### ISSUE TITLE
Supports for temporary URL using Openstack storage & Amazon S3 storage

### ISSUE THREAD

**Issue by julienfastre** [nextcloud/server#17793] opened 2019-11-03 22:10 UTC
**Is your feature request related to a problem? Please describe.**

We are currently running three nextcloud instances which stores [files in Openstack swift storage](https://docs.openstack.org/swift/latest/api/object_api_v1_overview.html). We are using [object storage as primary storage]https://docs.nextcloud.com/server/16/admin_manual/configuration_files/primary_storage.html) without encryption.

This works perfectly well, but currently files are downloaded from the object stores to the server before being downloaded by the client. This causes a little load on the server, and we think we could lower it.

I am thinking about using the [temporary URL feature](https://docs.openstack.org/swift/latest/api/temporary_url_middleware.html) for downloading files directly from the openstack object store. This feature [is also available on Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html).

**Describe the solution you'd like**

When a client downloads a file through webdav, the server will return an HTTP 302 response to a signed URL, where he would download the file.

The [RFC 4918](https://tools.ietf.org/html/rfc4918#section-12) states that:

> Note also that WebDAV servers are known to use 300-level redirect responses (and early interoperability tests found clients unprepared to see those responses).

The request / response would be :

```
GET /remote.php/dav/files/julien/document.pdf HTTP/2
Host: nextcloud.fastre.info
```

would return:

```
HTTP/1.1 302 Found
Location: https://url.openstack.to/container/oc:1?temp_url_sig=da39a3ee5e6b4b0d3255bfef95601890afd80709&temp_url_expires=1323479485&filename=document.pdf
```

I have not prototyped this yet.

**Describe alternatives you've considered**

No alternative were considered yet.

**Additional context**

This was also discussed here: 

* https://help.nextcloud.com/t/s3-external-storage-with-direct-download-option/8385

**Comment by Cinerar** [comment] 2019-11-18 20:07
#14675

**Comment by julienfastre** [comment] 2019-11-25 09:16
Indeed, @Cinerar, it seems to be the same feature in #14675.

**Comment by njfox** [comment] 2020-05-25 21:18
Would this have implications for things like video streaming? For example, would streaming videos from the s3 storage location to Nextcloud client apps work like it does on the internal storage, or does that rely on headers set by the Nextcloud server?

**Comment by julienfastre** [comment] 2020-05-29 07:48
I do not known how is handled the requests for video streaming.

Does those requests use the [Range](https://tools.ietf.org/html/rfc7233#section-3.1) header ?

If yes, I wonder if 302 redirection will force clients to keep this header. If not, will the [307](https://tools.ietf.org/html/rfc7231#section-6.4.7) response code be more appropriate ?

Amazon S3 [does support the `Range` header](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax), and [openstack too](https://docs.openstack.org/api-ref/object-store/?expanded=show-container-details-and-list-objects-detail,get-object-content-and-metadata-detail).

**Comment by szaimen** [comment] 2021-06-02 11:55
Duplicate of https://github.com/nextcloud/server/issues/14675

**Closed by szaimen** 2021-06-02 11:55 UTC
Labels: 0. Needs triage, enhancement, feature: external storage
