### ISSUE TITLE
upgrade fails because user id is invalid for ldap users

### ISSUE THREAD

**Issue by Thaodan** [nextcloud/server#15255] opened 2019-04-26 19:57 UTC
### Steps to reproduce
1. have ldap users
2. upgrade nextcloud
3. see error:

### Expected behaviour
nothing
### Actual behaviour
userid XXX invalid
### Server configuration

**Operating system**:
arch linux
**Web server:**
nginx
**Database:**
postgres
**PHP version:**
7.3.4
**Nextcloud version:** (see Nextcloud admin page) 
16.0
**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade

**Where did you install Nextcloud from:** pkg manager
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - news: 13.1.5
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - grauphel
  - mail
  - occweb

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
  'datadirectory' => '/var/lib/nextcloud/data',
  'appstoreenabled' => false,
  'cache_path' => '/var/lib/nextcloud/cache',
  'dbtype' => 'pgsql',
  'version' => '15.0.7.0',
  'dbhost' => '/run/postgresql',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'ldapIgnoreNamingRules' => true,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'log_type' => 'systemd',
  'loglevel' => 2,
  'maintenance' => false,
  'memcache.local' => 'OC\\Memcache\\Redis',
  'memcache.locking' => 'OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/run/redis/redis.sock',
    'port' => 0,
  ),
  'updater.release.channel' => 'stable',
  'theme' => '',
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
 user_ldap | s01ldap_port                         | 389
 user_ldap | s01ldap_backup_host                  | 
 user_ldap | types                                | authentication
 user_ldap | enabled                              | yes
 user_ldap | s01ldap_backup_port                  | 
 user_ldap | s01ldap_override_main_server         | 
 user_ldap | s01ldap_base_users                   | 
 user_ldap | s01ldap_base_groups                  | 
 user_ldap | s01ldap_user_filter_mode             | 0
 user_ldap | s01ldap_login_filter_mode            | 0
 user_ldap | s01ldap_loginfilter_username         | 1
 user_ldap | s01ldap_dn                           | cn=Directory Manager
 user_ldap | s01ldap_base                         | dc=example,dc=de
 user_ldap | s01ldap_userfilter_objectclass       | posixAccount
 user_ldap | s01ldap_loginfilter_email            | 1
 user_ldap | s01ldap_configuration_active         | 1
 user_ldap | s01ldap_userfilter_groups            | users
 user_ldap | installed_version                    | 1.6.0
 user_ldap | s01ldap_group_filter_mode            | 0
 user_ldap | s01ldap_gid_number                   | gidNumber
 user_ldap | s01ldap_display_name                 | displayName
 user_ldap | s01ldap_group_display_name           | cn
 user_ldap | s01ldap_tls                          | 0
 user_ldap | s01ldap_quota_def                    | 
 user_ldap | s01ldap_quota_attr                   | 
 user_ldap | s01ldap_cache_ttl                    | 600
 user_ldap | s01ldap_turn_off_cert_check          | 0
 user_ldap | s01ldap_attributes_for_user_search   | 
 user_ldap | s01ldap_attributes_for_group_search  | 
 user_ldap | s01ldap_expert_username_attr         | 
 user_ldap | s01use_memberof_to_detect_membership | 1
 user_ldap | s01last_jpegPhoto_lookup             | 0
 user_ldap | s01ldap_nested_groups                | 0
 user_ldap | s01ldap_paging_size                  | 500
 user_ldap | s01ldap_turn_on_pwd_change           | 0
 user_ldap | s01ldap_experienced_admin            | 0
 user_ldap | s01ldap_dynamic_group_member_url     | 
 user_ldap | s01ldap_default_ppolicy_dn           | 
 user_ldap | s01ldap_user_avatar_rule             | default
 user_ldap | s01ldap_host                         | localhost
 user_ldap | s01ldap_agent_password               | Z3IzNHNhcmFoNw==
 user_ldap | s01has_memberof_filter_support       | 1
 user_ldap | s01ldap_userlist_filter              | (&(|(objectclass=posixAccount))(|(memberof=cn=users,ou=groups,dc=thaodan,dc=de)))
 user_ldap | s01ldap_loginfilter_attributes       | 
 user_ldap | s01ldap_login_filter                 | (&(&(|(objectclass=posixAccount))(|(memberof=cn=users,ou=groups,dc=example,dc=de)))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))
 user_ldap | s01ldap_groupfilter_objectclass      | posixGroup
 user_ldap | s01ldap_groupfilter_groups           | users
 user_ldap | s01ldap_group_filter                 | (&(|(objectclass=posixGroup))(|(cn=users)))
 user_ldap | s01ldap_expert_uuid_user_attr        | uidNumber
 user_ldap | s01ldap_expert_uuid_group_attr       | gidNumber
 user_ldap | s01home_folder_naming_rule           | attr:homeDirectory
 user_ldap | s01ldap_email_attr                   | mail
 user_ldap | s01ldap_user_display_name_2          | mail
 user_ldap | s01ldap_group_member_assoc_attribute | gidNumber
 user_ldap | cleanUpJobOffset                     | 0
 user_ldap | s01_lastChange                       | 1555891248

```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
journald log:
```
{core} {"Exception":"InvalidArgumentException","Message":"The given user id is invalid","Code":0,"Trace":[{"file":"\/usr\/share\/webapps\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":199,"function":"setUser","class":"OC\\Notification\\Notification","type":"->","args":[99999]},{"file":"\/usr\/share\/webapps\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":224,"function":"sendNotification","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[]},{"file":"\/usr\/share\/webapps\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":230,"function":"repair","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/usr\/share\/webapps\/nextcloud\/lib\/private\/Repair.php","line":100,"function":"run","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/usr\/share\/webapps\/nextcloud\/lib\/private\/Updater.php","line":272,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/usr\/share\/webapps\/nextcloud\/lib\/private\/Updater.php","line":128,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["16.0.0.9","15.0.7.0"]},{"file":"\/usr\/share\/webapps\/nextcloud\/core\/ajax\/update.php","line":212,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"\/usr\/share\/webapps\/nextcloud\/lib\/private\/Notification\/Notification.php","Line":160,"CustomMessage":"--"}
Apr 26 21:43:47 example.de Nextcloud[31837]: {updater} \OC\Updater::failure: InvalidArgumentException: The given user id is invalid
Apr 26 21:43:47 example.de Nextcloud[31837]: {updater} \OC\Updater::updateEnd: Update failed
```

**Comment by Thaodan** [comment] 2019-04-26 21:05
Found the issue is this line:
https://github.com/nextcloud/server/blob/5382eeccb053ecf17bb8f7aacd57ae3cc4518d27/lib/private/Repair/RemoveLinkShares.php#L218

I lists all users even when the authentication app is disabled.

**Comment by kesselb** [comment] 2020-01-26 14:32
Duplicate of https://github.com/nextcloud/server/issues/15677

**Closed by kesselb** 2020-01-26 14:32 UTC
Labels: 0. Needs triage, 16-feedback, bug
