### ISSUE TITLE
Apache2 + PHP8: .htaccess does not set php_value's neither SetEnv under <IfModule mod_php7.c>

### ISSUE THREAD

**Issue by marcos-guerrero** [nextcloud/server#26657] opened 2021-04-20 15:08 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Run NC21 under APACHE2 and MOD_PHP , PHP8.0

### Expected behaviour
The server should read the .htaccess of nextcloud root site and set php_value's and env variables under the conditional
```
<IfModule mod_php7.c>
  php_value mbstring.func_overload 0
  php_value default_charset 'UTF-8'
  php_value output_buffering 0
<IfModule mod_env.c>
    SetEnv htaccessWorking true
</IfModule>
</IfModule>
```

### Actual behaviour
Due the change of php module name (From mod_php7.c in PHP7.x to mod_php.c in PHP8.0) nothing in the conditional block is set 

### Server configuration

**Operating system:**
Ubuntu 20.04 LTS

**Web server:**
Apache 2.4.46

**Database:**
Mariadb 10.5.8

**PHP version:**
PHP 8.0.3

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
from older nextcloud

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2021-04-20 18:36
Duplicate of https://github.com/nextcloud/server/issues/26569

**Closed by kesselb** 2021-04-20 18:36 UTC
Labels: 0. Needs triage, bug
