### ISSUE TITLE
Public shared links refreshing continuously since v28 upgrade

### ISSUE THREAD

**Issue by psy0rz** [nextcloud/server#42200] opened 2023-12-13 10:02 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Demo url: https://cloud.datux.nl/s/qokf5AXDKN2S4E8

It keeps refreshing, nothing to see in the logs and nextcloud.log.

I'm running the official docker images behind a reverse proxy.  (nextcloud:fpm-alpine)

### Steps to reproduce

1. Share public link
2. Try to open it
3. Browser keeps refreshing.

### Expected behavior

should show the shared folder in the browser, without a reload loop.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.datux.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.datux.nl",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "overwriteprotocol": "https",
        "overwritehost": "cloud.datux.nl",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "app_install_overwrite": [
            "epubreader"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notes: 4.9.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - support: 1.11.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - circles: 28.0.0-dev (installed 27.0.1)
  - comments: 1.18.0 (installed 1.17.0)
  - contactsinteraction: 1.9.0 (installed 1.8.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.17.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - nextcloud_announcements: 1.17.0 (installed 1.16.0)
  - recommendations: 2.0.0 (installed 1.6.0)
  - serverinfo: 1.18.0 (installed 1.17.0)
  - survey_client: 1.16.0 (installed 1.15.0)
  - theming_customcss: 1.15.0 (installed 1.15.0)
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
(empty log, only contained old entries)
```

**Comment by stemod** [comment] 2023-12-13 12:32
We got the same problems with multiple instances after upgrade.

**Comment by psy0rz** [comment] 2023-12-13 13:57
vote it up, people! :)

**Comment by torrentkino** [comment] 2023-12-13 14:34
It does not seem to affect new shared public links but old ones. At least in our case.

**Comment by torrentkino** [comment] 2023-12-13 15:24
Ah. I figured it out. Sharing files still works. Sharing directories result in this refreshing bug.

**Comment by x5355** [comment] 2023-12-13 16:35
I can confirm this bug on Debian Bookworm with Apache and PHP 8.1. I also can confirm that it affects **directories** shared by link or mail. I had to rollback the affected instance.

**Comment by peacepenguin** [comment] 2023-12-13 21:32
Same issue here after v28 upgrade. sharing directories, new and old share links of directories. ubuntu 20.04, php 8.1, apache.

**Comment by peacepenguin** [comment] 2023-12-13 22:05
WORKAROUND FOUND:

Disable this setting under "Administrative Settings" -> "Administration" -> "Sharing"

Allow users on this server to send shares to other servers (this option also allows WebDAV access to public shares)

**Comment by torrentkino** [comment] 2023-12-14 07:18
> WORKAROUND FOUND:
> 
> Disable this setting under "Administrative Settings" -> "Administration" -> "Sharing"
> 
> `Allow users on this server to send shares to other servers (this option also allows WebDAV access to public shares)`

For me, it was the opposite. Enabling this option helped. Hm. Anyway. Thank you!

**Comment by dkmonaghan** [comment] 2023-12-14 08:43
Same issue, however mine was fixed by enabling "Allow users on this server to send shares to other servers".

**Comment by vitormfgoncalves** [comment] 2023-12-14 16:28
> Same issue, however mine was fixed by enabling "Allow users on this server to send shares to other servers".

Same here. I dont like to leave this option enabled...

**Comment by OliJue** [comment] 2023-12-14 21:19
> Same issue, however mine was fixed by enabling "Allow users on this server to send shares to other servers".

Same here. Fixed by above mentioned workaround.

**Comment by psy0rz** [comment] 2023-12-15 08:43
> WORKAROUND FOUND:
> 
> Disable this setting under "Administrative Settings" -> "Administration" -> "Sharing"
> 
> `Allow users on this server to send shares to other servers (this option also allows WebDAV access to public shares)`

can confirm that this works.

**Comment by dorianborovina** [comment] 2023-12-15 13:57
> WORKAROUND FOUND:
> 
> Disable this setting under "Administrative Settings" -> "Administration" -> "Sharing"
> 
> `Allow users on this server to send shares to other servers (this option also allows WebDAV access to public shares)`

This fixed it! 👍

**Comment by joshtrichards** [comment] 2023-12-18 20:08
The underlying cause is documented in #42313.

Either need to figure out where the duplicate `X-Requested-With` is being added or modify the check for it to not look for a single value.

**Comment by joshtrichards** [comment] 2023-12-29 17:03
Possibly a regression introduced via #39924 or #40951 

More reports on the Help Forums too about public shares not working with NC28 like in this issue.

Cc: @nextcloud/files

**Comment by ownedge13** [comment] 2023-12-31 10:02
disabling "Administrative Settings" -> "Administration" -> "Sharing" doesn't work for me, when i access a shared folder it's stuck in a refresh loop, and if i enable it it doesn't loop, but the folder is empty (there is files in it)

**Comment by nfp0** [comment] 2023-12-31 12:32
@ownedge13  Hmm, the empty folder part sounds like it might be a different issue than the one discussed here.

**Comment by ownedge13** [comment] 2023-12-31 13:33
idk, here videos enable and disable : "Administrative Settings" -> "Administration" -> "Sharing" -> "Allow users on this server to send shares to other servers (this option also allows WebDAV access to public shares)"

https://drive.google.com/drive/folders/1VTQCKMLvORB7GdPtpD-koxeMV-OOL4ua?usp=drive_link

**Comment by Aonodensetsu** [comment] 2024-01-02 09:20
Enabling the option fixes it for me, but I disagree that there is nothing in logs. When set to level 0 (DEBUG), a message pops up with every reload:
```
{"reqId":"1c2oNgZPN5qEATKyKdJm","level":0,"time":"December 29, 2023 19:08:05 +0000","remoteAddr":"10.0.0.1","user":"--","app":"webdav","method":"PROPFIND","url":"/public.php/webdav/","message":"Exception thrown: Sabre\\DAV\\Exception\\NotAuthenticated","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0","version":"28.0.1.1","exception":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/ServerFactory.php","line":133,"function":"{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","line":124,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/public.php","line":81,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","Line":81,"message":"","exception":{},"CustomMessage":"Exception thrown: Sabre\\DAV\\Exception\\NotAuthenticated"}}
```

**Comment by Ducknuke** [comment] 2024-01-08 10:26
Hello everybody,
Since update 28 I have the same problem on my Nextcloud instance (container). Unable to have the side panel (endless refresh).
I notice that nextcloud is looking for files in a folder that does not exist :

`[error] 402#402: *197 open() "/app/www/public/js/core/merged-template-prepend.js" failed (2: No such file or directory), client: x.x.x.x, server: domaine.fr, request: "GET /js/core/merged-template-prepend.js?v=9aa19e9a-0 HTTP/1.1", host: "nextcloud.domaine.fr", referrer: "https://nextcloud.domaine.fr/apps/files/"`

I noticed that these files were in /data/appdata_ocmx20us7sn3/js/core/.
I also found a "merged-template-prepend.JSON" (not js) in app/www/public/core/js/ so I have a .../core/js/... but not .../js/core/...

So I copied the files from the /data/appdata_ocmx20us7sn3/js/core/ folder to put them in a new folder /app/www/public/js and the shares and the side panel returned...
I don't understand this sudden change of folder path... I hate copying and pasting without really understanding what's happening. Since update in NC28  I have been fighting against all kinds of new problems :(

**Comment by wabadoo-wabadee** [comment] 2024-01-08 20:28
same problem. allowing share to other servers worked.

**Comment by msklywenn** [comment] 2024-01-09 12:56
Same here. NC28 is the most disastrous update we've hard this far. It really has all kinds of issues... (drag & drop not working, half broken external storage that logs errors constanly, this...) At least it doesn't loose files!

**Comment by skjnldsv** [comment] 2024-01-16 16:47
Fix in https://github.com/nextcloud/server/pull/42853

**Comment by joho1968** [comment] 2024-01-17 06:57
> WORKAROUND FOUND:
> Disable this setting under "Administrative Settings" -> "Administration" -> "Sharing"
> `Allow users on this server to send shares to other servers (this option also allows WebDAV access to public shares)`

We don't have any of that enabled, and we're still seeing the issue(s).

**Comment by sorbaugh** [comment] 2024-01-17 07:56
@ChristophWurst would there be a way to check this during the migration before it fails?

**Comment by FerencIstvan** [comment] 2024-01-17 08:29
> We don't have any of that enabled, and we're still seeing the issue(s).

Toggle this option. In my case, all was off, but when I turned this option on, the issue past. 
So I leave it enabled, till the fix (thanks for that) will be available.

**Closed** 2024-01-17 09:40 UTC
Labels: bug, 3. to review, feature: sharing, feature: files, regression, 28-feedback

**Comment by joshtrichards** [comment] 2024-01-23 00:31
@b-pfl The fix has already been merged into the stable28 code base by way of #42882 (a backport of #42853). It'll be in the final release of v28.0.2. 

> Can you confirm / inform people in this thread once the fix of #42853 is released?

That's what release notes are for. :) 

It's already released in the latest Release Candidate build and listed in the associated RC release notes:

https://help.nextcloud.com/t/rcs-of-28-0-2-27-1-6-and-26-0-11/179353

So probably won't hear any other follow-up here. :-)

**Comment by oculos** [comment] 2024-01-24 13:35
Please test the side panel - I realized that after updating the patch above, the activity panel shows "Unable to load activity list"

**Comment by demlak** [comment] 2024-01-24 13:42
In here, the patch stopped the refreshing.. 
but i still cant open imagesfiles on a public shared folder..

**Comment by susnux** [comment] 2024-01-24 13:51
> I realized that after updating the patch above, the activity panel shows "Unable to load activity list"

Did you just apply the patch or upgrade to RC3? Because there was a bug like this fixed for activity in RC2 / RC3

**Comment by oculos** [comment] 2024-01-24 13:53
We just applied the patch.

**Comment by GHBLoos** [comment] 2024-03-15 07:51
App cfg_share_links does not work anymore on NC28. Is this issue related to the issue that's solved here? In other words, is there a bug in NC28 or is it in the app? I hope someone can dive into that.
https://github.com/jimmyl0l3c/cfg_share_links/issues/182

**Comment by Piceeeeeee** [comment] 2024-03-28 18:34
and chunking with share link? still a no?
