### ISSUE TITLE
Newly created users in the group aren't automatically displayed in the contacts menu list

### ISSUE THREAD

**Issue by RodSeq** [nextcloud/server#45890] opened 2024-03-07 10:40 UTC
### Describe the bug

Using NC 28.0.3, when I click on the contact icon (top-right), newly created users in the group aren't automatically displayed in the list. On the other hand, users that have been created before NC 28.0.3 are always well displayed in the list.

By typing the user in "Search contacts ...", newly created users are well displayed. Also if I click on "Show all contacts", all users in the group are well displayed.

### Steps to reproduce

1. Using NC 28.0.3, create a new group and new users on the "Users" page
2. Login to one User account in the group
3. Click on the contact icon (top-right)
4. See that the newly created users in the group are not automatically displayed in the list

### Expected behavior

When I click on the contact icon (top-right), new users in the group should be automatically displayed in the list.

### Actual behavior

When I click on the contact icon (top-right), new users in the group should be automatically displayed in the list, as NC used to do.

### Contact version

5.5.3

### Operating system

Linux 5.4.140

### PHP engine version

PHP 8.1

### Web server

None

### Database

MySQL

### Additional info

Bug present on latest NC 28.0.3 and Contacts app 5.5.3, only for newly created users on the "Users" admin  page.

**Comment by joshtrichards** [comment] 2024-06-15 23:20
Duplicate of #44058

**Closed by joshtrichards** 2024-06-15 23:20 UTC
Labels: bug, 0. Needs triage, feature: contacts menu, feature: contacts, 28-feedback
