### ISSUE TITLE
Result of PROPFIND request is way to big - 9Mb in my case

### ISSUE THREAD

**Issue by nook24** [nextcloud/server#25233] opened 2021-01-20 13:24 UTC
Hi,

i have annoying performance issues with my Nextcloud installation while the system is almost doing nothing. I traced the issue down to the `PROPFIND`  requests that the Nextcloud interfaces sends to the Server. The server response with a 9MB large XML file. Im impressed that the browser can even parse this large file without crashing. But generating a more than 33k lines file on the server + processing it on the client takes time. 8 seconds in my case. This is the reason why the Nextcloud interface is so unresponsive. At least i think it is.

This happens for my Photos folder which have a LOT of files in one directory.

You can see it in action:
https://youtu.be/xfGll8y12oQ (Yes clicking on an image will also fire the `PROPFIND` query - It is fast if you use the left and right keys)

I also think that this is the root cause why my iOS app freeze for one minute on startup: https://github.com/nextcloud/ios/issues/1514

My post on the Nextcloud Forum: https://help.nextcloud.com/t/gallery-image-browsing-click-on-an-image-very-slow-for-large-folders/102637

### Steps to reproduce

- Put some Files and folders to Nextcloud (~56GB in my case)
- I have a Photos Folder with 30GB images
- Open Nextcloud App
- Get a coffee :)

### Expected behaviour
Do not send a 9 MB XML file

### Actual behaviour
Sends huge XML files to the browser

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache 2.4.29 with php-fpm

**Database:** MySQL 5.7

**PHP version:** 7.2.24

**Nextcloud version:** 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from Nextcloud 19 but this issue exists for many years now

**Where did you install Nextcloud from:** https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - audioplayer: 3.0.0
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - documentserver_community: 0.1.8
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - music: 0.17.3
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - apporder
  - bruteforcesettings
  - encryption
  - previewgenerator
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "defaultapp": "files",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.nook24.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.nook24.eu",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 1,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "mysql.utf8mb4": true,
        "cache_chunk_gc_ttl": 86400,
        "tempdirectory": "\/tmp",
        "app_install_overwrite": [
            "calendar"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Firefox and Chrome

**Operating system:** Linux, macOS, iOS and Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
178.xxx.xxx.xxx - - [20/Jan/2021:14:04:21 +0100] "GET /ocs/v2.php/apps/text/workspace?path=%2FPhotos HTTP/2.0" 404 205 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
178.xxx.xxx.xxx - - [20/Jan/2021:14:04:21 +0100] "POST /index.php/apps/text/session/sync HTTP/2.0" 200 275 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
178.xxx.xxx.xxx - - [20/Jan/2021:14:04:23 +0100] "POST /index.php/apps/text/session/close HTTP/2.0" 200 86 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
178.xxx.xxx.xxx - - [20/Jan/2021:14:04:21 +0100] "PROPFIND /remote.php/dav/files/nook24/Photos HTTP/2.0" 207 523894 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
178.xxx.xxx.xxx - - [20/Jan/2021:14:04:25 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FPhotos HTTP/2.0" 200 273 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
178.xxx.xxx.xxx - - [20/Jan/2021:14:04:25 +0100] "PROPFIND /remote.php/webdav/Enpass/vault.enpassdbsync HTTP/1.1" 401 6387 "-" "Mozilla/5.0"
178.xxx.xxx.xxx - - [20/Jan/2021:14:04:26 +0100] "PROPFIND /remote.php/webdav/Enpass/vault.enpassdbsync HTTP/1.1" 207 1630 "-" "Mozilla/5.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Has no records related to this issue
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
XHRPROPFINDhttps://cloud.nook24.eu/remote.php/dav/files/nook24/Photos
[HTTP/2 207 Multi-Status 2753ms]
```
</details>

**Comment by J0WI** [comment] 2021-03-27 15:09
Nextcloud fetches all files at once and iterates over each file to fetch all metadata for them. This performs very bad on large folders.

**Comment by szaimen** [comment] 2021-07-02 10:29
So it looks like a duplicate of https://github.com/nextcloud/server/issues/11244, no?

**Comment by nook24** [comment] 2021-08-02 14:14
> marked as stale because it has not had recent activity

This issue is not fixed and lets the iOS App freeze and makes the web ui unusable. I don't know why this should be stale now - how ever I no longer use Nextcloud because of this.

**Comment by szaimen** [comment] 2023-01-23 10:39
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by nook24** [comment] 2023-01-23 13:23
Hi @szaimen 
I will setup a test environment and try to reproduce the issue with the latest docker container. I will come back to you with the results.

**Closed** 2023-03-06 13:42 UTC
Labels: bug, needs info, 0. Needs triage, performance 🚀
