### ISSUE TITLE
Color theme (dark/light) should apply to guests, according to prefers-color-scheme CSS

### ISSUE THREAD

**Issue by moviuro** [nextcloud/server#21423] opened 2020-06-15 20:26 UTC
**Is your feature request related to a problem? Please describe.**
When a guest prefers dark theme, they can choose `prefers-color-scheme: dark` in their browser or [operating system](https://support.apple.com/en-us/HT208976). When they visit a Nextcloud instance, their choice should be directly applied.

**Describe the solution you'd like**
Use `prefers-color-scheme`, directly in the main (?) CSS file that defines colors. It's supported by [80%+ of users](https://caniuse.com/#feat=prefers-color-scheme). Additionally, this will make the choice of light/dark theme more portable even for users who will no longer have to navigate to the Accessibility menu.

**Describe alternatives you've considered**
N/A

**Additional context**
There seems to be one CSS file holding the entire definition of colors with variables (`*-css-variables.css`), which might be a good place to add:

```css
@media (prefers-color-scheme: dark) {
  :root{
    --color-main-text=...
    [...]
  }
}
```

**Comment by kesselb** [comment] 2020-06-15 21:24
Duplicate of https://github.com/nextcloud/server/issues/12276

**Closed by kesselb** 2020-06-15 21:24 UTC
Labels: 0. Needs triage, enhancement
