### ISSUE TITLE
Server  says no internet connection while accesing from the internet

### ISSUE THREAD

**Issue by schoenpat** [nextcloud/server#16768] opened 2019-08-16 20:02 UTC
### Steps to reproduce
1. (Upgrade from 16.0.2 to 16.0.3, not sure about that, but i think it appeared at this point)
2. Open /index.php/settings/admin/overview
3. Nextcloud will warn about no internet connection

### Expected behaviour
No warning because the server obviously has an internet connection

### Actual behaviour
Warning because the server thinks he has no internet connection

### Server configuration

**Operating system**: Ubuntu 18.04 server

**Web server:** Apache 2.4

**Database:** mariadb 10.x

**PHP version:** 7.2.19

**Nextcloud version:** 16.0.3 (but also in 16.0.3)

**Updated from an older Nextcloud/ownCloud or fresh install:**  From Nextcloud 16

**Where did you install Nextcloud from:** .tar.gz from website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - audioplayer: 2.7.2
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - groupfolders: 4.0.5
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - richdocuments: 3.3.15
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - deck
  - encryption
  - files_rightclick
  - tasks
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "username": "***REMOVED SENSITIVE VALUE***",
                "password": "***REMOVED SENSITIVE VALUE***",
                "bucket": "nextcloud_root_storage",
                "autocreate": true,
                "region": "DE1",
                "url": "https:\/\/auth.cloud.ovh.net\/v2.0",
                "tenantName": "***REMOVED SENSITIVE VALUE***",
                "serviceName": "swift"
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***MY CLOUD DOMAIN***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "calendar"
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** openstack swift as main storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 68.0.1 64-bit

**Operating system:** Manjaro KDE

#### Web server error log
<details>
<summary>Web server error log</summary>

Nothing relevant

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Nothing

</details>

#### Browser log
<details>
<summary>Browser log</summary>
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:494

The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:30:10
XML-Verarbeitungsfehler: nicht wohlgeformt

Adresse: https://cloud.notvads.ovh/core/fonts/Nunito-Regular.woff2
Zeile Nr. 1, Spalte 5: Nunito-Regular.woff2:1:5

​
</details>

**Comment by kesselb** [comment] 2019-08-16 20:41
There is no change to this code since [16.0.2](https://github.com/nextcloud/server/pull/16146). Any chance that some firewall blocks connections to `www.nextcloud.com`, `www.startpage.com`, `www.eff.org` or `www.edri.org`?

**Comment by schoenpat** [comment] 2019-08-16 20:54
@kesselb 
200 / 301 / 302 Http-Codes from this exact urls with curl.

**Comment by schoenpat** [comment] 2019-08-16 21:00
> There is no change to this code since [16.0.2](https://github.com/nextcloud/server/pull/16146). 

I am not completely sure about the first version it appeared. Not more than 3 months ago.

**Comment by setroot** [comment] 2019-08-18 23:03
It's happening to me too, iOS & win desktop app doesn't connect at all. No firewall

**Comment by szaimen** [comment] 2021-06-07 13:49
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 13:49 UTC
Labels: 0. Needs triage, bug
