### ISSUE TITLE
[Bug]: Duplicate Toast notification on used storage warnings

### ISSUE THREAD

**Issue by meilon** [nextcloud/server#36353] opened 2023-01-25 12:24 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the storage gets over 90% you get a toast notification about this, twice!

![image](https://user-images.githubusercontent.com/510071/214562261-f42d2504-0050-441c-ab4e-87ead1343dcc.png)

### Steps to reproduce

1. Store more than 90% of your quota
2. Open File view
3.

### Expected behavior

Only get the toast once

### Installation method

Community Manual installation with Archive

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "the.host.ip.address",
            "1": "cloud.mydomain.com"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "default_language": "de",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/cloud.mydomain.com\/",
        "trashbin_retention_obligation": "30, auto",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "asset-pipeline.enabled": true,
        "singleuser": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "data-fingerprint": "61c92c7e5d6754191b33145032c3a5e5",
        "check_data_directory_permissions": false,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar",
            "impersonate"
        ],
        "updater.release.channel": "stable",
        "default_phone_region": "de",
        "bulkupload.enabled": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.2
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - dashboard: 7.0.0
  - encryption
  - files_external: 1.5.0
  - firstrunwizard: 1.1
  - suspicious_login
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

Existed at least since Jan 25, 2021 (issue #25317) with Nextcloud 20.0.5. Also tested with fresh manual docker compose setup (using nextcloud:25-apache and mariadb:10.5 image) and happens there, too

**Comment by meilon** [comment] 2023-02-02 06:48
Small update which might help: Currently I get two messages with a different degree of accuracy on the used quota:

![image](https://user-images.githubusercontent.com/510071/216251989-0f8bde8a-f7fa-45eb-88a7-027f94ebfdb7.png)

**Comment by skjnldsv** [comment] 2024-08-01 05:55
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-08-01 05:55 UTC
Labels: bug, 0. Needs triage, feature: files, 25-feedback
