### ISSUE TITLE
[Bug]: Public share dialog does not reload share details if a share password is required

### ISSUE THREAD

**Issue by Commifreak** [nextcloud/server#43844] opened 2024-02-26 13:32 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

**Required**: `enforce_links_password` must be enabled!

If creating apublish share link, NC asks for password confirmation. If confirmed, the notification bar shows a success info "Password created" but nothing else happens. The share details sidebar does not update with the just created link. Hitting F5 shows the link, its copy symbol and properties.

### Steps to reproduce

1. Enable share password enforcement
2. Create public link
3. Confirm password
4. message "Password created" pops up and nothing else happens

### Expected behavior

Confirmation message for password AND created link as well as a update of the share-details-sidebar (like if no password enforcements is enabled.

Video: 

https://github.com/nextcloud/server/assets/87267/f0c73e1a-dc39-41c1-89bf-f09c89f33c53

A example WITHOUT enforced password:

https://github.com/nextcloud/server/assets/87267/4db14ce0-e5a3-41cb-8ee4-349589ef31ee

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "default_language": "de",
        "trusted_domains": [
            "nextcloud.domain.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "trashbin_retention_obligation": "auto, 30",
        "overwrite.cli.url": "http:\/\/nextcloud.domain.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance_window_start": 1,
        "proxy": "1.2.3.4:8000",
        "allow_local_remote_servers": true,
        "proxyexclude": [
            "1.2.3.4",
            "collabora.domain.de",
            "2.3.4.5",
            "nextcloud.domain.de"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "drawio",
            "mindmap_app"
        ],
        "preview_max_x": 512,
        "preview_max_y": 512
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - announcementcenter: 6.7.0
  - calendar: 4.6.5
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - deck: 1.12.2
  - drawio: 3.0.2
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - group_everyone: 0.1.14
  - groupfolders: 16.0.3
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.0.1
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.1
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.3
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0 (installed 2.7.0)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1 (installed 1.0.1)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by LM-vb** [comment] 2024-02-26 17:13
See #43720.

**Comment by Commifreak** [comment] 2024-02-26 17:30
Yep, exactly same issue.

**Comment by Mescuphist** [comment] 2024-03-04 10:39
Common fix it or a leave owncloud

**Comment by LM-vb** [comment] 2024-03-07 13:45
This is solved in NC 28.0.3

**Comment by ElSi-DVT** [comment] 2024-03-13 14:32
This problem exists in Version 27.1.7 too.

**Comment by ElSi-DVT** [comment] 2024-03-25 10:21
@szaimen Do you know if the problem is solved in NC 27.1.8 too?

**Comment by ElSi-DVT** [comment] 2024-04-02 13:19
This problem still exists in 27.1.8

**Comment by c-0815** [comment] 2024-05-06 06:16
same Problem in  27.1.9

**Comment by joshtrichards** [comment] 2024-09-06 21:53
Duplicate of #43720 / #44032

**Closed by joshtrichards** 2024-09-06 21:53 UTC
Labels: bug, feature: sharing, 0. Needs triage, feature: files, 28-feedback
