### ISSUE TITLE
Handling calendar invitations and responses using email

### ISSUE THREAD

**Issue by yanosz** [nextcloud/server#2149] opened 2016-11-16 09:35 UTC
Refs: 

- https://help.nextcloud.com/t/handling-calendar-invitations-using-email/5168
- https://github.com/nextcloud/calendar/issues/186

From what I got, I can add participants to an event and they are invited by mail.
But: When I respond using the MUA, the response is sent to the authors private mailbox. Nextcloud doesn't get the status.

That's bad, since I need nextcloud to reflect the participant status of an event, even if no MUA updating the event using CalDav is present. This should happen without further processing at the site sending the invitation (Eg. logging in into nextcloud or acknowledging the response in nextcloud): In case of shared calendars, the participants status should be updated at once.

**Comment by yanosz** [comment] 2016-11-16 09:57
Thinking about an implemenation, I've no idea on how clients handle https / http addresses in CAL-ADDRESS value types for deeplinks (aka jumping into owncloud).

Refering to RFC 2445 any uri is allowed... http://www.kanzaki.com/docs/ical/calAddress.html .. but most clients may focus on mail.

If a deeplink doesn't work, nextcloud may need to subscribe to imap. Although imap is a very interesting sharing / group ware protocol - imho it's out of scope to have a general imap-backend.

Another idea is to have a mail server piping incoming emails to an adapter-script, posting the email's content .. but this may be nasty from an operations point of view.

**Comment by MorrisJobke** [comment] 2017-09-03 18:56
Duplicate of #2338

**Closed by MorrisJobke** 2017-09-03 18:56 UTC
Labels: 1. to develop, enhancement, feature: dav

**Comment by colans** [comment] 2022-03-10 04:03
@mchobbel I believe that's https://github.com/nextcloud/server/issues/19144.  Please hit the :+1: button over there to show your support.
