### ISSUE TITLE
Video previews are not sized correctly

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#2603] opened 2016-12-10 13:58 UTC
<img width="496" alt="bildschirmfoto 2016-12-10 um 14 55 01" src="https://cloud.githubusercontent.com/assets/19711361/21073789/aca45812-bee8-11e6-932e-a70ef38dbb76.png">

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS
**Web server:**
Apache
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
11.0 RC1

### Client configuration
**Browser:**
Safari 10.0.1
**Operating system:**
macOS Sierra

Dont know, is this handled by files_videoplayer or the Nextcloud server? 😁

**Comment by nickvergessen** [comment] 2016-12-10 15:38
They where already killed, iirc.

**Comment by juliushaertl** [comment] 2016-12-12 08:47
duplicate of https://github.com/nextcloud/server/issues/2557

It has been fixed in https://github.com/nextcloud/files_videoplayer/pull/14

**Closed by juliushaertl** 2016-12-12 08:47 UTC
Labels: 1. to develop, bug, design
