### ISSUE TITLE
bug in progress-indicator for public uploads (multiple files)

### ISSUE THREAD

**Issue by DaCryptor** [nextcloud/server#6060] opened 2017-08-10 05:27 UTC
Hi,

just noticed a bug in the progress-indicator for public uploads (Nextcloud 12.0.1 on a shared-hosting environment, PHP 7):

If you upload multiple files (let's say six), the upload starts showing
the six filenames with a spinning circle in front of each filename.

When the first file is uploaded successfully, the
spinning circle in front of the specific file (in this case the last file in the list)
is replaced by a small picture-icon (if it is a picture).

Even if the upload for the other five files is already completed,
the spinning circles in front of the top 5-filenames never disappear, so
the user does not have a clue if his/her upload has finished successfully or failed.

This should be fixed.

Thank you.

Best regards,
DaCryptor

**Comment by enoch85** [comment] 2017-08-10 16:51
@DaCryptor Do you have a screenshot?

**Comment by DaCryptor** [comment] 2017-08-10 17:41
Sure, here you go. The upload of all files has been successful a long time ago, but the user thinks that the upload is still underway and not proceeding...
![screenshot](https://user-images.githubusercontent.com/9333420/29183696-eddbd1a4-7e03-11e7-8ac6-09921610ca41.jpg)

**Comment by DaCryptor** [comment] 2017-08-10 17:44
![screenshot](https://user-images.githubusercontent.com/9333420/29183831-57ea0200-7e04-11e7-9f65-7d663c6e0ebc.jpg)

**Comment by enoch85** [comment] 2017-08-10 17:46
I think this is expected behavior. Please correct me if I'm wrong @MorrisJobke

**Comment by DaCryptor** [comment] 2017-08-10 19:00
This would be really surprising. I mean: All of the files have already been uploaded successfully, so the spinning circles in front of the top 9-files of the screenshot do not make any sense anymore.
In my opinion the best case would be to have a progress bar for each file.
At least I would expect to have a message like "all files uploaded successfully" or something like that.

**Comment by MorrisJobke** [comment] 2017-08-11 10:26
> I think this is expected behavior. Please correct me if I'm wrong @MorrisJobke

No. The spinner should go away.

**Comment by DaCryptor** [comment] 2017-08-12 08:09
Does anyone have an idea for a quick workaround?

**Comment by MorrisJobke** [comment] 2017-08-14 10:13
cc @nextcloud/javascript

**Comment by k1ngf15h3r** [comment] 2017-08-15 04:58
@MorrisJobke thank you, I did not see this issue. are there any informations when the behavior should be fixed or worked arround? hoping that 12.0.2 fixes the issue but did not found a changelog now for 12.0.2

**Comment by MorrisJobke** [comment] 2017-08-15 05:58
As it is open it is not fixed yet;)

**Comment by k1ngf15h3r** [comment] 2017-08-15 06:13
@MorrisJobke was to early in the morning. Sure it is not fixed yet. But if anyone has a workaround that would be nice. Customers uploading much multiple files if they think that upload does not work ;)

**Comment by k1ngf15h3r** [comment] 2017-08-17 18:20
I think the trick is in this [file](https://github.com/nextcloud/server/blob/master/apps/files_sharing/js/files_drop.js) but I can not find the error in the code :-/

**Comment by danxuliu** [comment] 2017-08-17 21:25
The problem occurs also in master.

> I think the trick is in this [file](https://github.com/nextcloud/server/blob/master/apps/files_sharing/js/files_drop.js) but I can not find the error in the code :-/

Indeed. The problem is the use of the variable `fileName` in the `initialize` function; I will create a pull request to explain and fix it.

**Comment by k1ngf15h3r** [comment] 2017-08-18 04:32
@danxuliu that would be really nice. Thanks a lot.

**Comment by k1ngf15h3r** [comment] 2017-08-18 20:33
@danxuliu thank you for your fast solution and PR. Looking forward to see it fixed in my customers instance :)

**Comment by k1ngf15h3r** [comment] 2017-08-21 16:35
Did a manual patch like you show in https://github.com/nextcloud/server/issues/6182 file drop now works like expected. Hope to see your solution in the official code as soon as possible. Code integrity is now failing for sure on my system.

**Comment by MorrisJobke** [comment] 2017-08-29 12:50
Will be fixed in 12.0.3 and 13.

**Closed by MorrisJobke** 2017-08-29 12:50 UTC
Labels: bug, feature: sharing, medium, papercut
