### ISSUE TITLE
[Bug]: Sub folder shares were broken on ownership transfer

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/server#42407] opened 2023-12-20 18:04 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After an ownership transfer (via the web interface), sub shares can be broken and it's impossible to restore.

### Steps to reproduce

- userA shares a folder D1 with userB
- userB creates and shares a subfolder D2 and shares it with userC
- userA revoke the share of D1 with userB
- userA transfers ownership of D1 to userD

After userD accepts the transfer:
- userC loses access to the folder D2
- if userD tries to share the folder D2 with userC : error message "Node for share not found, fileid: 132472"

### Expected behavior

My suggestion for expected behavior:
Re-share should be deleted if restore failed to not block creating new share for the same user.

### Installation method

Community Docker image

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2023-12-21 15:01
Does `occ sharing:delete-orphan-shares` help here?

**Comment by Gravelbones** [comment] 2024-01-04 14:30
I have the same problem, but coming from a different scenario:

**Steps to reproduce**

    userA shares a folder D1 with userB
    userB creates a subfolder D2 and shares it with userC
    userA transfers ownership of D1 to userD

After userD accepts the transfer:

    userC loses access to the folder D2 (appears empty but visible)
    userB can't see the sharing anymore
    if userB tries to (re)share the folder D2 with userC : error message "Node for share not found, fileid: x

The problem is fixed by updating oc_table/uid_owner to the UID of userD.
Also userB is not present in oc_users table, due to being syncronized via LDAP, if that means something.

**Closed** 2024-11-25 17:20 UTC
Labels: bug, 3. to review, feature: sharing, 29-feedback
