### ISSUE TITLE
The session is not closed after the web browser is closed, the user remains logged in

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/server#11934] opened 2018-10-19 11:25 UTC
Nextcloud server 14.0.3
Ubuntu 16.04.5
php 7.0.32
Apache 2.4.18
PostgreSQL 9.5.14

The session is not closed after the web browser is closed, the user remains logged in

until i solved the problem this way:
'remember_login_cookie_lifetime' => 0,

**Comment by jancborchardt** [comment] 2018-10-19 18:46
If by »session close« you mean »log out«, then this is intentional. Web services don’t log people out unless specifically "Log out" was used. Otherwise people have to log in every time they start up their computer, or close the browser (accidentally or not) and this is annoying.

cc @rullzer @MorrisJobke

**Comment by lvarnava** [comment] 2018-10-19 18:58
In NC13, the behavior was such that when the browser was closed, the user log out.

Then how to understand these settings:

'remember_login_cookie_lifetime' => 60*60*24*15,
Lifetime of the remember login cookie, which is set when the user clicks the remember checkbox on the login screen.

Defaults to 60*60*24*15 seconds (15 days)

'session_lifetime' => 60 * 60 * 24,
The lifetime of a session after inactivity.

Defaults to 60*60*24 seconds (24 hours)

'session_keepalive' => true,
Enable or disable session keep-alive when a user is logged in to the Web UI.

Enabling this sends a “heartbeat” to the server to keep it from timing out.

**Comment by jancborchardt** [comment] 2018-10-22 11:16
> And where did the "remember checkbox"?

We removed it because people will always be remembered. Until you use the "Log out" function. Much simpler.

> In NC13, the behavior was such that when the browser was closed, the user log out.

Ok, but as said above:

> Web services don’t log people out unless specifically "Log out" was used. Otherwise people have to log in every time they start up their computer, or close the browser (accidentally or not) and this is annoying.

Regarding the technical stuff, someone more technical (like @rullzer @MorrisJobke @juliushaertl) will have to comment. :)

**Comment by lvarnava** [comment] 2018-10-22 18:46
thank you for your patience:) and your work!

**Comment by enoch85** [comment] 2018-11-06 19:35
FYI, [added this back](https://github.com/nextcloud/vm/commit/fa659ceaae0dd9657fae6490d294272e79b61282) in the VM as users requested it.

**Comment by JLueke** [comment] 2018-11-29 18:22
No option for automatic logout on browser close becomes problematic if nextcloud is used for another service via OAuth. For example I use my service to login to nextcloud (with help of Social Login App). When I logout from my service, I close the browser, but forgot to logout from Nextcloud.
In this case another person can access my Nextcloud account when he opens the browser again.

If I recall correctly, there is no API to logout the user from nextcloud remotely.

**Comment by enoch85** [comment] 2018-12-26 16:00
@ksmolder Yes that's correct. Though I changed it to 30 minutes in the latest version as I noticed some issues whit uploading in the Web GUI.

You will automatcally be logged out, and if you want to be logged out faster than 30 minutes, then change it to whatever you like in config.php.

**Comment by dahumph** [comment] 2019-04-22 09:33
This thread is a bit old, but still I'm facing the issue described by OP. 

NC Version 15.0.2.0
OS Ubuntu 16.04.6
PHP 7.0.33-0ubuntu0.16.04.3

with this config.php

    'remember_login_cookie_lifetime' => 0,
    'session_lifetime' => 60*5,
    'session_keepalive' => false,

session expires after 5 minutes as intended, but the session is remembered after browser is closed and opened again.

**Comment by skjnldsv** [comment] 2019-06-12 08:50
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-12 08:50 UTC
Labels: 0. Needs triage

**Comment by enoch85** [comment] 2019-06-12 10:05
@skjnldsv The default behavior is to stay logged in unless you click "Logout". This wasn't the behavior before and this ticket addresses that. So unless you will revert to the old behavior or set a sane default IMHO this ticket is still valid.

> If by »session close« you mean »log out«, then this is intentional. Web services don’t log people out unless specifically "Log out" was used.

If you on the other hand don't intend to change it, it can remain closed.

**Comment by skjnldsv** [comment] 2019-06-12 10:07
No, iirc we tend to go the same way others big services are doing it.
Nowadays almost all the website I use keep me logged in (the only I have in mind is medium and it's a pain in the :peach: to login every day) :)

We removed the keep me logged in button for this exact purpose.

**Comment by pielonet** [comment] 2019-09-16 16:00
HI, imagine a laptop got stollen. What can an administrator do to log out the user remotely ?

**Comment by jospoortvliet** [comment] 2020-07-25 12:07
> HI, imagine a laptop got stollen. What can an administrator do to log out the user remotely ?

The user can simply log in on any other device and go to their session overview to close the session. If the laptop has a desktop client with files, the remote wipe function will remove all the files from the laptop. For privacy reasons, the admin can not control individual sessions, only wipe all devices and close all sessions from the user.

Here is a screenshot.
![Screenshot_20200725_140734](https://user-images.githubusercontent.com/551757/88456709-37787b80-ce80-11ea-802d-fafd61ddeb71.png)
