### ISSUE TITLE
Displaying photos no longer work in NC 20

### ISSUE THREAD

**Issue by haziegler** [nextcloud/server#23541] opened 2020-10-17 15:39 UTC
After upgrading to NC 20.0.0, users can no longer display photos.

### Steps to reproduce
1. Upgrade to NC 20.0.0
2. Log in as a user that has photos stored in his/her NC account. Alternatively, upload a new image.
3. Click to the photo (in "Files" or "Photos" app).

### Expected behaviour
The image should be displayed.

### Actual behaviour
The screen is black with an endless-rotating status circle.

### Server configuration

**Operating system:** RHEL 8.2

**Web server:** httpd-2.4.37-21.module+el8.2.0+5008+cca404a3.x86_64

**Database:** sqlite-3.26.0-6.el8.x86_64

**PHP version:** php-7.3.20-1.module+el8.2.0+7373+b272fdef.x86_64

**Nextcloud version:** (see Nextcloud admin page) 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 19.0.3

**Where did you install Nextcloud from:** Source ZIP

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Accessibility 1.6.0
Auditing / Logging 1.10.0
Calendar 2.1.2
Collabora Online 3.7.5
Contacts 3.4.0
File sharing 1.12.0
Log Reader 2.5.0
Photos 1.2.0
Right click 0.17.0
Share by mail 1.10.0
Text 3.1.0
Video Player 1.9.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/srv/www/data/xxx/nextcloud/data',
  'overwrite.cli.url' => 'https://xxx/nc',
  'dbtype' => 'sqlite3',
  'version' => '20.0.0.9',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'logfile' => '/srv/www/data/xxx/nextcloud/log/nextcloud.log',
  'loglevel' => 2,
  'default_language' => 'en',
  'defaultapp' => 'files',
  'appstoreenabled' => true,
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
  ),
  'preview_max_x' => 750,
  'preview_max_y' => 750,
  'preview_max_scale_factor' => 1,
  'forcessl' => true,
  'knowledgebaseenabled' => false,
  'enable_avatars' => false,
  'allow_user_to_change_display_name' => false,
  'skeletondirectory' => '',
  'lost_password_link' => 'disabled',
  'updatechecker' => false,
  'has_internet_connection' => true,
  'theme' => '',
  'auth.bruteforce.protection.enabled' => true,
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'appcodechecker' => true,
  'htaccess.RewriteBase' => '/nc',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'nc',
  'mail_domain' => 'xxx',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxx',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpport' => '465',
  'mail_send_plaintext_only' => true,
  'app_install_overwrite' =>
  array (
    0 => 'occweb',
  ),
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 81.0.1

**Operating system:** Fedora 33

### Logs

No error is logged when you open a photo. Neither in the web server's log nor in the NextCloud log.

#### Browser log
<details>
<summary>Browser log</summary>

```
Uncaught (in promise) TypeError: OCA.Theming is undefined
    updateTitle https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    n https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    c https://xxx/nc/apps/richdocuments/js/viewer.js?v=b96a6def:138
    _invoke https://xxx/nc/apps/richdocuments/js/viewer.js?v=b96a6def:138
    e https://xxx/nc/apps/richdocuments/js/viewer.js?v=b96a6def:138
    ae https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    a https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    se https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    se https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    openFile https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    file https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:403
    run https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:14
    cr https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:14
    tt https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:14
    Xe https://xxx/nc/apps/viewer/js/viewer-main.js?v=b96a6def:14
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://xxx/nc/apps/richdocuments/js/viewer.js?v=b96a6def
Source-Map-Adresse: viewer.js.map
```
</details>

**Comment by kesselb** [comment] 2020-10-17 20:26
Thanks for reporting 👍

Closing as duplicate of https://github.com/nextcloud/viewer/issues/632. Will be fixed with 20.0.1. A workaround is to enable the theming app

**Closed by kesselb** 2020-10-17 20:26 UTC
Labels: 0. Needs triage, bug
