### ISSUE TITLE
Share via public link button not showing

### ISSUE THREAD

**Issue by Notespeak** [nextcloud/server#13521] opened 2019-01-11 19:29 UTC
### Steps to reproduce
1. Login to nextcloud
2. press 3 dots.
3. only share via email is available

### Expected behaviour
A sidebar that allows the user to create links should appear.
### Actual behaviour
The email sharing bar is showing and there is no trace of a link creation button

### Server configuration

**Operating system**:
ubuntu 16.04
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from nextcloud 13.0
**Where did you install Nextcloud from:**
the official website.
**Signing status:**
<details>

No errors have been found.

</details>

**List of activated apps:**
collabora online
audio player
circles
social sharing via email
email 
video player
checksum

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

 "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "arcus.ntshosts.com",
            "10.30.60.96"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/arcus.ntshosts.com",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trashbin_retention_obligation": "7, auto",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>



**Are you using encryption:** no



```

### Client configuration
**Browser:** Chrome on desktop and mobile editions, Edge, Firefox.

**Operating system:**
Windows 10, android.

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

{"reqId":"iroOvufMuWIsmsXj0mqI","level":3,"time":"2018-05-20T16:15:57+00:00","remoteAddr":"54.38.78.51","user":"--","app":"PHP","method":"POST","url$
{"reqId":"iroOvufMuWIsmsXj0mqI","level":3,"time":"2018-05-20T16:15:58+00:00","remoteAddr":"54.38.78.51","user":"administrator","app":"PHP","method":$
{"reqId":"iroOvufMuWIsmsXj0mqI","level":2,"time":"2018-05-20T16:15:58+00:00","remoteAddr":"54.38.78.51","user":"administrator","app":"files","method$



</details>

#### Browser log
<details>
<summary>Browser log</summary>
JQMIGRATE: Migrate is installed, version 1.4.0
VM2036:1 Failed to decode downloaded font: https://arcus.ntshosts.com/core/fonts/Nunito-Bold.woff2
VM2036:1 OTS parsing error: invalid version tag
arcus.ntshosts.com/:1 Failed to decode downloaded font: https://arcus.ntshosts.com/core/fonts/Nunito-Regular.woff2
arcus.ntshosts.com/:1 OTS parsing error: invalid version tag
/core/preview?fileId=532191&c=21ffe0e530024f4aff8d08248306c792&x=250&y=250&forceIcon=0:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/core/preview?fileId=527092&c=dc908e10905a732c95a70d5033c2960e&x=250&y=250&forceIcon=0:1 Failed to load resource: the server responded with a status of 404 (Not Found)
arcus.ntshosts.com/:1 Failed to decode downloaded font: https://arcus.ntshosts.com/core/fonts/Nunito-Bold-latin-ext.woff2
arcus.ntshosts.com/:1 OTS parsing error: invalid version tag
arcus.ntshosts.com/:1 Failed to decode downloaded font: https://arcus.ntshosts.com/core/fonts/Nunito-Regular-latin-ext.woff2
arcus.ntshosts.com/:1 OTS parsing error: invalid version tag
merged-share-backend.js?v=093157bd-11:2521 Uncaught ReferenceError: link is not defined
    at merged-share-backend.js?v=093157bd-11:2521
    at Function.m.each.m.forEach (core.js?v=093157bd-11:18)
    at child.each (core.js?v=093157bd-11:1157)
    at child.render (merged-share-backend.js?v=093157bd-11:2519)
    at child.render (merged-share-backend.js?v=093157bd-11:4455)
    at child.<anonymous> (merged-share-backend.js?v=093157bd-11:3752)
    at triggerEvents (core.js?v=093157bd-11:1441)
    at triggerApi (core.js?v=093157bd-11:1426)
    at eventsApi (core.js?v=093157bd-11:1225)
    at child.Events.trigger (core.js?v=093157bd-11:1416)
</details>

**Comment by violoncelloCH** [comment] 2019-01-11 23:54
are you sure sharing by link is enabled/allowed in the admin sharing settings?

**Comment by s0faking** [comment] 2019-01-12 14:30
same here #13513 . i've seen that it works for images if you open the image and use the controls on the top bar to share the image.

**Comment by jghauser** [comment] 2019-01-12 14:46
for me share links work in chromium but not firefox (on up-to-date arch linux)

**Comment by violoncelloCH** [comment] 2019-01-12 14:57
strange, I can't reproduce this
could it be that there is an adblocker hiding something?

**Comment by jghauser** [comment] 2019-01-12 15:02
indeed, that was it (in my case at least). i thought ublock wasn't filtering anything (because it says 0% filtered). however, disabling cosmetic filtering solved the issue. cheers!

**Comment by PBMacros** [comment] 2019-01-12 15:37
Here disabling ublock did not help (Chromium)
And even if no adblock was installed the error occurred (Firefox).

The Chromium developer console error log: 
```
merged-share-backend.js?v=99cb1149-6:2521 Uncaught ReferenceError: link is not defined  
    at merged-share-backend.js?v=99cb1149-6:2521
    at Function.m.each.m.forEach (core.js?v=99cb1149-6:18)
    at child.each (core.js?v=99cb1149-6:1157)
    at child.render (merged-share-backend.js?v=99cb1149-6:2519)
    at child.render (merged-share-backend.js?v=99cb1149-6:4455)
    at child.<anonymous> (merged-share-backend.js?v=99cb1149-6:3752)
    at triggerEvents (core.js?v=99cb1149-6:1441)
    at triggerApi (core.js?v=99cb1149-6:1426)
    at eventsApi (core.js?v=99cb1149-6:1225)
    at child.Events.trigger (core.js?v=99cb1149-6:1416)
```

**Comment by s0faking** [comment] 2019-01-13 15:46
I was able to resolve the issue on my cloud installations by disabling the "Social sharing via email" App. The Share Link Button works now. i saw that there is also an issue on the app github page for this behaviour

https://github.com/nextcloud/socialsharing/issues/29

**Comment by violoncelloCH** [comment] 2019-01-13 17:58
indeed, thank you @s0faking, I can reproduce it now with activating "socialsharing via email"...

**Comment by DecaTec** [comment] 2019-01-15 16:49
Yes, I can reproduce the issue.
Sharing via link only is shown when the app "social sharing via email" is deactivated.

**Comment by wioxjk** [comment] 2019-01-17 11:13
I have the same issue. Deactivating "social sharing via email" does work as previously stated.

**Comment by Huster-at-github** [comment] 2019-01-20 00:17
In Chrome without any AddOns it worked.
Disabling uBlock Origin (AD blocker) in Firefox: Now working also.

Strange ..... did not tell me that anything was blocked:

![grafik](https://user-images.githubusercontent.com/3857906/51433728-36460d00-1c51-11e9-9ccd-908d6fb6aff9.png)

**Comment by violoncelloCH** [comment] 2019-01-23 15:38
fix is in #13738

**Closed by violoncelloCH** 2019-01-23 15:38 UTC
Labels: bug

**Comment by bcutter** [comment] 2019-02-05 19:15
Hell no this stup** social sharing via eMail app... made me going crazy. Thanks for GitHub and the information here!

**Comment by M4TH76** [comment] 2020-02-25 17:18
This Bug is still in Nextcloud 18.0.1
Had to disable "Share by Email" App to get the sharing tab to show in Files

**Comment by simonai1254** [comment] 2020-06-05 07:33
I have the Bug with 18.0.5 that the Sharing button disappears when I have my Adblocker (Adblock Plus) enabled, even though the ad blocker nor the console tells me that anything has been blocked...

What I can say is that the "Sharing via eMail" app is not the issue
