### ISSUE TITLE
Contacts icon missing in 15.0.6

### ISSUE THREAD

**Issue by hunter-nl** [nextcloud/server#14970] opened 2019-04-05 12:36 UTC
### Steps to reproduce
1. Upgrade to 15.0.6
2. Login
3. Contacts icon is missing in top bar

### Expected behaviour
Show contacts icon

### Actual behaviour
Icon is missing in icon-vars.css file.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
15.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from 15.0.5

**Where did you install Nextcloud from:**
Through updater

#### Browser log
<details>
<summary>Browser log</summary>
In file "icon-vars.css" is the icon (--icon-contacts-fff) missing.
Also --icon-contacts-000 is missing.
The CSS .icon-contacts { background-image: var(--icon-contacts-fff) }
refers to this icon which should be defined in icon-vars.css.
</details>

**Comment by skjnldsv** [comment] 2020-08-25 09:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:17 UTC
Labels: 0. Needs triage, bug
