### ISSUE TITLE
mtime ignored when copying files to Nextcloud via davfs 

### ISSUE THREAD

**Issue by boycott-github** [nextcloud/server#10889] opened 2018-08-27 15:51 UTC
Steps to reproduce:

* create user test password test on a Nextcloud 13.0.5 instance at https://example.com
* Provision a Ubuntu 18.04 from scratch
* sudo apt-get update
* sudo apt-get install davfs
* echo 'https://example.com/remote.php/dav/files/test test test' >> /etc/davfs2/secrets
* mount -t davfs https://example.com/remote.php/dav/files/test /mnt
* ls -l /etc/timezone
    -rw-r--r-- 1 root root 8 Apr 26 05:10 /etc/timezone
* cp -a /etc/timezone /mnt/
* ls -l /mnt/timezone 
    -rw-r--r-- 1 root root 8 Apr 26 05:10 /mnt/timezone
* umount /mnt
* mount -t davfs https://example.com/remote.php/dav/files/test /mnt
* ls -l /mnt/timezone 
    -rw-r--r-- 1 root root 8 Aug 27 15:48 /mnt/timezone

And checking the time via the Nextcloud web interface confirms the mtime is not what it should be.

**Comment by MorrisJobke** [comment] 2018-10-01 18:19
Duplicate of #3572

Currently we only store the upload time if a specific header is not set explicitly. So first we need a way to store it and then we can support the mtime and ctime properly.

**Closed by MorrisJobke** 2018-10-01 18:19 UTC
Labels: bug
