### ISSUE TITLE
[Bug]: No Activities logged when using WebDav API

### ISSUE THREAD

**Issue by grnd-alt** [nextcloud/server#48156] opened 2024-09-18 08:44 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using the WEBDAV API and marking a file as favorite the activity is not logged in the activities.

### Steps to reproduce

1.create file
2.mark as favorite according to https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#settings-favorites
3. look at activities

### Expected behavior

activity listed

### Nextcloud Server version

tested on master

**Comment by joshtrichards** [comment] 2024-09-18 12:47
Duplicate of #26393

**Closed by joshtrichards** 2024-09-18 12:47 UTC
Labels: bug, feature: dav, 0. Needs triage, feature: activity and notification, 31-feedback
