### ISSUE TITLE
error occurs when try to enable "External Storage Support"

### ISSUE THREAD

**Issue by iwzoo** [nextcloud/server#8618] opened 2018-03-02 04:09 UTC
### Steps to reproduce
1. sudo -u www-data php occ app:enable files_external
2.
3.

### Expected behaviour
Enable external storage support 

### Actual behaviour
error occurred with error message
 [Doctrine\DBAL\Exception\TableExistsException]                               
  An exception occurred while executing 'CREATE TABLE `oc_external_mounts` (`  
  mount_id` BIGINT AUTO_INCREMENT NOT NULL, `mount_point` VARCHAR(128) NOT NU  
  LL, `storage_backend` VARCHAR(64) NOT NULL, `auth_backend` VARCHAR(64) NOT   
  NULL, `priority` INT DEFAULT 100 NOT NULL, `type` INT NOT NULL, PRIMARY KEY  
  (`mount_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':  
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_external  
  _mounts' already exists

 [Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_external  
  _mounts' already exists 

[PDOException]                                                               
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_external  
  _mounts' already exists 

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgrade from docker image 12.0.3 to 13.0.0

**Comment by MorrisJobke** [comment] 2018-03-21 12:45
Duplicate of https://github.com/nextcloud/server/issues/5544

**Closed by MorrisJobke** 2018-03-21 12:45 UTC
