### ISSUE TITLE
enhanced shared info  

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#10106] opened 2018-07-04 16:42 UTC
Nextcloud 13.0.2
who can see/edit a file/directory

- if the file / directory is shared - the current info is sufficient

- if a directory above in the hierarchy is shared - no info is available at a lower level.

Hence: 
the shared info should include ALL user / groups (with users) who are entitled to see/edit the document

**Comment by MorrisJobke** [comment] 2018-07-05 08:49
Duplicate of #4281 which aims to show the "Who has access to that file?" for each file and folder.

**Closed by MorrisJobke** 2018-07-05 08:49 UTC
Labels: bug, enhancement, feature: sharing
