### ISSUE TITLE
settings/user/sharing spams the server with requests

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#27564] opened 2021-06-18 20:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open index.php/settings/user/sharing
2. Check network log

### Expected behaviour
"normal" behaviour

### Actual behaviour
100 requests to apps/user_status/api/v1/statuses/...
52 of those go against: apps/user_status/api/v1/statuses/undefined

The requests are from the "New owner" drop down in the "Transfer ownership of a file or folder" section

At least the requests to undefined should not happen. But maybe we can investigate if we return the status only while searching and not in the preload

### Server configuration

**Nextcloud version:** 22.0.0beta5

**Comment by pierreozoux** [comment] 2022-05-10 11:29
@nickvergessen I couldn't reproduce, so I'll close it, but feel free to reopen if you still experience it.

**Closed by pierreozoux** 2022-05-10 11:29 UTC
Labels: bug, 1. to develop, feature: sharing, feature: settings, 22-feedback

**Comment by nickvergessen** [comment] 2022-05-10 14:30
Still happens for me on 24.0.0

**Comment by szaimen** [comment] 2022-11-26 14:09
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by nickvergessen** [comment] 2022-11-26 14:42
Still happening on 25.0.1
