### ISSUE TITLE
Desktop clients fails syncing when server return bad content-type header for folder names ending with common file extension for example .c .pl .exe

### ISSUE THREAD

**Issue by olszeww0** [nextcloud/server#28257] opened 2021-07-30 10:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Open browser.
2. In nextcloud web interface create a folder with name for example "fiszki.pl", "15.exe" or "test.c"
3. Open desktop client settings.
4. Wait for next synchronization or pause and then resume sync.
5. Error message appears in desktop client and synchronization fails with error.

### Expected behaviour
Synchronization without problems.

Server response contains header "Content-Type: application/xml; charset=utf-8" as expected by desktop client.

### Actual behaviour
Desktop synchronization with error: "A HTTP transmission error happened. Server error: PROPFIND reply is not XML formatted!" or
"Server replied with an error while reading directory '****/****/*****/test.c': Server error: PROPFIND reply is not XML  formatted!". 

Server response contains header for example directory fiszki.c  "Content-Type: text/x-csrc" and do not contains header ""Content-Type: application/xml; charset=utf-8" expected by desktop client.

### Server configuration

**Operating system:** Ubunto 20.04.2 LTS

**Web server:** Apache 2.4.48

**Database:** mysql 10.4.12

**PHP version:** 7.4.21

**Nextcloud version:** 20.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older versions.

**Where did you install Nextcloud from:** Server package (zip file) from nextcloud official site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
"No errors have been found."
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 4.0.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.8
  - drawio: 1.0.1
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - news: 16.0.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.1.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.4.2
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 2.0.6
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - tasks: 0.14.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - federation
  - groupfolders
  - survey_client
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.11.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1009": "\/etc\/mysql\/certificates\/mysql-pki-ca2.pem"
        },
        "logtimezone": "UTC",
        "installed": true,
        "cache_path": "\/var\/www\/***REMOVED SENSITIVE VALUE***\/ncl-cache\/",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis.cluster": {
            "seeds": [
                "10.5.X.X:6379",
                "10.5.X.X:6379",
                "10.5.X.X:6379"
            ],
            "timeout": 0,
            "read_timeout": 0,
            "failover_mode": 1,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "log_rotate_size": 1073741824,
        "default_language": "en",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** No issue in browser like Chrome/Firefox/Edge. Only in desktop clients: 3.2.4 (Fedora)/3.2.4 (Windows)/3.1.1 (Macintosh)

**Operating system:** Fedora 34/Windows 10 Pro/MacOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
"-" - - [30/Jul/2021:07:13:29 +0000] "PROPFIND /remote.php/dav/files/***REMOVED SENSITIVE VALUE***/fiszki.c HTTP/2.0" 207 1024 "-" "Mozilla/5.0 (Windows) mirall/3.2.4stable-Win64 (build 20210706) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)"

No issues in web server log. Normal http 207 response.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No issues in nextcloud.log
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No browser log.
```
</details>

**Comment by szaimen** [comment] 2021-08-08 16:37
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-08-08 16:37 UTC
Labels: bug, 0. Needs triage

**Comment by olszeww0** [comment] 2021-08-09 09:53
In latest version 21.0.3 issue also exists.
