### ISSUE TITLE
Submit button on login form does not respect Theme colour on hover

### ISSUE THREAD

**Issue by nooblag** [nextcloud/server#27696] opened 2021-06-28 09:28 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set custom theme colours
2. Visit login page
3. Click login button (hover over)

### Expected behaviour
Theme colour is used, e.g. `#C5309F`

### Actual behaviour
Theme colour is not used.

![Screenshot from 2021-06-28 19-13-55](https://user-images.githubusercontent.com/1122344/123613572-e4086d80-d846-11eb-97ae-c30b0b701ea2.png)

### Server configuration

**Operating system:**
Ubuntu 18.04.5 LTS

**Web server:**
nginx/1.18.0

**Database:**
psql (PostgreSQL) 10.17

**PHP version:**
PHP 7.4.18

**Nextcloud version:** (see Nextcloud admin page)
21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
21.0.1

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - announcementcenter: 5.0.0
  - apporder: 0.12.0
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.2
  - camerarawpreviews: 0.7.11
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - dav: 1.17.1
  - drawio: 1.0.0
  - event_update_notification: 1.2.0
  - external: 3.8.2
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_downloadactivity: 1.10.0
  - files_pdfviewer: 2.1.0
  - files_readmemd: 1.2.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_texteditor: 2.14.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - groupfolders: 9.0.1
  - impersonate: 1.8.0
  - integration_whiteboard: 0.0.14
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - metadata: 0.13.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.0.2
  - password_policy: 1.11.0
  - photos: 1.3.0
  - previewgenerator: 3.1.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - ransomware_protection: 1.10.1
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_retention: 1.4.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - contacts
  - contactsinteraction
  - dashboard
  - encryption
  - federation
  - files_external
  - nextcloud_announcements
  - support
  - survey_client
  - user_ldap
  - user_status
  - weather_status
  - whiteboard
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "***REMOVED SENSITIVE VALUE***",
        "templatedirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Australia\/Melbourne",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": 0,
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 14",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": false,
        "login_form_autocomplete": true,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "dbindex": "0",
            "timeout": "1.5"
        },
        "maintenance": false,
        "default_phone_region": "AU",
        "default_locale": "en_AU",
        "force_locale": "en_AU",
        "default_language": "en",
        "force_language": "en",
        "defaultapp": "activity,files",
        "activity_expire_days": 180,
        "session_lifetime": 14400,
        "session_keepalive": false,
        "auth.webauthn.enabled": false,
        "overwriteprotocol": "https",
        "app_install_overwrite": [
            "activitylog",
            "files_readmemd"
        ],
        "updater.release.channel": "stable",
        "theme": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_CF_CONNECTING_IP"
        ],
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 89.0.2

**Operating system:**
Linux Mint 20

### Logs

No relevant logs.

#### Browser log

No relevant logs.

**Comment by acsfer** [comment] 2021-06-28 15:46
Duplicate of https://github.com/nextcloud/server/issues/27495

**Closed by acsfer** 2021-06-28 15:46 UTC
Labels: 0. Needs triage, bug
