### ISSUE TITLE
Files REPORT verb doesnt return queried custom properties

### ISSUE THREAD

**Issue by jhomola79** [nextcloud/server#11817] opened 2018-10-13 21:09 UTC
### Steps to reproduce
1. PROPPATCH new custom property to some folder for 'someuser'
2. Request webdav REPORT verb against remote.php/dav/files/someuser/ with custom property specified in prop section of request payload

### Expected behaviour
custom property value returns in response similar as it works for PROPFIND on affected resource

### Actual behaviour
custom properties are never returned for files REPORT

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** postgres

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** from downloaded archive

Maybe possible fix:

apps/dav/lib/Connector/Sabre/FilesReportPlugin.phpFilesReportPlugin->getFilesBaseUri

private function getFilesBaseUri($uri, $subPath) {
		$uri = trim($uri, '/');
		$subPath = trim($subPath, '/');
		if (empty($subPath)) {
			$filesUri = $uri;
		} else {
			$filesUri = substr($uri, 0, strlen($uri) - strlen($subPath));
		}
		$filesUri = trim($filesUri, '/');
		if (empty($filesUri)) {
			return '';
		}
		return '/' . $filesUri;
	}

Do not 
return '/' . $filesUri;
but only
return $filesUri;

Custom properties in column propertypath of properties db table are not stored with initial slash.

**Comment by jhomola79** [comment] 2018-10-13 22:00
Sorry, suggested fix above is not that good...
Better it would be to change

$propFind = new PropFind($filesUri . $node->getPath(), $requestedProps);

to 

$propFind = new PropFind(ltrim($filesUri, '/') . $node->getPath(), $requestedProps);

in  apps/dav/lib/Connector/Sabre/FilesReportPlugin.phpFilesReportPlugin->prepareResponses($filesUri, $requestedProps, $nodes)

that only internal propfind is called without initial '/'.

**Comment by MorrisJobke** [comment] 2018-10-15 06:58
@jhomola79 Could I ask you to send in your changes a pull request right here on GitHub? Then we can directly comment on the code changes with the context of the surrounding code. Thanks

**Comment by jhomola79** [comment] 2018-10-17 17:04
Hi, I have spent some time trying to setup and run phpunit tests but no success yet. So I will try to make poll request without test in short time.

**Comment by skjnldsv** [comment] 2020-04-10 07:59
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 07:59 UTC
Labels: 0. Needs triage, bug
