### ISSUE TITLE
Add config option to bypass checkDataDirectoryPermissions

### ISSUE THREAD

**Issue by jarofgreen** [nextcloud/server#3245] opened 2017-01-24 21:57 UTC
During install Nextcloud checks the data directory has permission 0770 and won't let the install proceed without that. 

It seems it might be good to allow this check to be skipped, in the same way that the admin can go to "Additional settings" and turn off the check for common passwords. (But this check should be on by default as is the other check.)

Skipping this has to be configured in config.php and not the admin panel; as you can't finish the install if this check fails you can't get to the admin panel! So you must be able to turn it off in config.php.

To add a feature to skip this check, replace this line:

     $errors = array_merge( $errors, self::checkDataDirectoryPermissions( $CONFIG_DATADIRECTORY ) );

in function checkServer in https://github.com/nextcloud/server/blob/master/lib/private/legacy/util.php#L699 (currently line number 699 and 718) with:

    if ($config->getSystemValue('checkdatadirectorypermissions', true)) {
         $errors = array_merge( $errors, self::checkDataDirectoryPermissions( $CONFIG_DATADIRECTORY ) );
    }

This will run the check by default, but then the admin can add 

    'checkdatadirectorypermissions' => false

to config.php to skip it.

Goggling "please change the permissions to 0770 so that the" shows this is a common problem, with some problems caused by people using external drives with a different file system - http://askubuntu.com/questions/380767/please-change-the-permissions-to-0770-so-that-the-directory Tho it is true some problems seem to be caused by things like bad FTP uploads and there you definitely want file permissions sorted out properly.

I personally ran into this problem as I was running Nextcloud in Vagrant for testing, and my Vagrant mount options meant I couldn't simply use chmod to fix the problem. So I took a deeper look at it.

**Comment by axelmm** [comment] 2017-08-24 17:22
I ran into this problem and googled for this, too. IMHO this is **much more than common problem** (affects people for years), sometimes it's not resolvable making NC(OC) **not installable 'by design'** - in my case: Docker for Windows (v. 10 pro + Hyper-V) - [permissions error](https://www.bountysource.com/issues/44945874-data-directory-permissions-error-message-docker-for-windows) - like many other ntfs, nfs, etc issues.

**This proposal is a great idea** - as a workaround I simply commented out only [line #768](https://github.com/nextcloud/server/blob/master/lib/private/legacy/util.php#L768) - but I would rather **left chmod attempt** and **allow gently bypass failing result** in checkDataDirectoryPermissions(), sth like this ( current line [#980](https://github.com/nextcloud/server/blob/master/lib/private/legacy/util.php#L980) ):

```php
	if ($perms[2] !== '0') {
		$strictly = \OC::$server->getSystemConfig()->getValue('datadirectory.strictly.permissions', true);
		if (!$strictly) {
			return $errors;
		}
		$errors[] = [
			//..
	}
```

Only one place to change and as above - default behaviour not changed but can be simply modified when needed.

**Comment by tobru** [comment] 2017-10-27 08:43
Let me add my vote here as we face issues with installing Nextcloud on OpenShift (see https://github.com/tobru/nextcloud-openshift/issues/4). It's nearly impossible to change mount settings on OpenShift and in my opinion it should work out of the box. So if the directory permission checking can be made optionally by changing the configuration in the configuration file, that would be really great.

**Comment by alexander0042** [comment] 2017-11-07 13:51
This would be a really amazing fix to implement- I run everything on a Windows server 2016 docker install, and this glitch stops everything. I've tried a few ways to change permissions on a volume, but it's definitely not possible. Especially since NextCloud is so storage intensive, I can't save it in the same Moby VM as docker is running in

**Comment by tilosp** [comment] 2017-11-10 14:17
This would make the docker image usable on Docker for Windows (https://github.com/nextcloud/docker/issues/70).

**Comment by alexander0042** [comment] 2017-11-10 14:27
Just in case anyone else is looking at this- a workaround is to make the volume within the MobyVM- it's still treated as a volume, so persists outside of containers, but because it's within the Linux filesystem there aren't the permissions issues. 

However, definitely not an ideal fix, since this forces all the containers + data to be on the same VHD. In my case (probably not uncommon), I'd like to put the container on my SSD and the data on my HDD, but right now everything must be stored on the hard drive. It also introduces issues resizing the VHD if too much data is stored there.

**Comment by MorrisJobke** [comment] 2017-12-01 10:59
Fixed in #7347

**Closed by MorrisJobke** 2017-12-01 10:59 UTC
Labels: 0. Needs triage, enhancement, feature: install and update

**Comment by tangobravo5656** [comment] 2022-03-23 15:25
'checkdatadirectorypermissions' => false,
I added this line to the /var/www/html/nextcloud/config/config.php . But the data folder(/mnt/zfs/share/nextcloud) still being automatically reset to 0770.And ACLs didn't work in my case maybe has something to do with my mounting method since i used 9P virtfs.

**Comment by tangobravo5656** [comment] 2022-03-23 15:26
> Fixed in #7347

Hi can u help me out?
'checkdatadirectorypermissions' => false,
I added this line to the /var/www/html/nextcloud/config/config.php . But the data folder(/mnt/zfs/share/nextcloud) still being automatically reset to 0770.And ACLs didn't work in my case maybe has something to do with my mounting method since i used 9P virtfs.

**Comment by Normand-Nadon** [comment] 2022-12-19 03:56
@tangobravo5656 , if you did not find the answer, here it is:
It is not written the way you did (and many posts have reported on the web)... it has underscores!

'check_data_directory_permissions' => false,

Just found it myself after months with this issue on an Unraid server with shared drives!

**Comment by optimodzhu** [comment] 2024-01-31 09:27
> @tangobravo5656 , if you did not find the answer, here it is: It is not written the way you did (and many posts have reported on the web)... it has underscores!
> 
> 'check_data_directory_permissions' => false,
> 
> Just found it myself after months with this issue on an Unraid server with shared drives!

Thank you very much!

**Comment by joshtrichards** [comment] 2024-01-31 10:57
For further context, the parameter details can be found in the official documentation:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#check-data-directory-permissions
