### ISSUE TITLE
9.2.4.7/3.1 In the "Details" section under the "Activity" tab, it is possible to open a dropdown list when entering "@", ":" or "/" into the textbox, for example, to select from a list of emojis. When navigating through the elements in these lists using the keyboard, the keyboard focus is poorly distinguishable. The contrast ratio between the focused and unfocused states is below 3:1.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42225] opened 2023-12-13 13:59 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-91f2646afa-v3-n1

9.2.4.7/3.1 In the "Details" section under the "Activity" tab, it is possible to open a dropdown list when entering "@", ":" or "/" into the textbox, for example, to select from a list of emojis. When navigating through the elements in these lists using the keyboard, the keyboard focus is poorly distinguishable. The contrast ratio between the focused and unfocused states is below 3:1.

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:37
duplicate of https://github.com/nextcloud/server/issues/41879

**Closed by JuliaKirschenheuter** 2023-12-14 10:37 UTC
Labels: accessibility
