### ISSUE TITLE
XML Interpretation errore: not well-formed. Source: Nunito-Regular.woff2

### ISSUE THREAD

**Issue by thepra** [nextcloud/server#15193] opened 2019-04-22 21:21 UTC
### Steps to reproduce
1. Open any nextcloud webpage and open the console, this error message is displayed. Is there any way to fix it?

### Server configuration

**Operating system**: OpenSUSE Tumbleweed

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.3.4

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** /srv/www/htdocs

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** /media/data(HDD)

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 66

**Operating system:** Windows 10 x64

#### Browser log
<details>
<summary>Browser log</summary>

![immagine](https://user-images.githubusercontent.com/7032509/56530843-5688af00-6553-11e9-983a-a21046e1da68.png)

</details>

**Comment by szaimen** [comment] 2021-05-20 12:18
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-20 12:18 UTC
Labels: 0. Needs triage, bug
