### ISSUE TITLE
Cannot delete group with '#' in a name..

### ISSUE THREAD

**Issue by MacGyver27** [nextcloud/server#18432] opened 2019-12-16 15:12 UTC
Created group `#backups` and cannot be deleted via UI:
![image](https://user-images.githubusercontent.com/6546231/70918064-c4bc3d80-201e-11ea-96a8-a0bd842528ba.png)

**Comment by kesselb** [comment] 2019-12-16 15:27
Duplicate of https://github.com/nextcloud/server/issues/18267

**Closed by kesselb** 2019-12-16 15:27 UTC
Labels: 0. Needs triage, bug
