### ISSUE TITLE
data/.htaccess check reports false positive

### ISSUE THREAD

**Issue by mageroya** [nextcloud/server#1350] opened 2016-09-09 17:00 UTC
The check for data directory protection is broken after the upgrade from NC9 to NC10. 

The `data/.htaccess` file works just fine (== nothing accessible from outside) in my setup, but I still get a warning that 

"Your data directory and your files are probably accessible from the Internet. The .htaccess file is not working. We strongly suggest that you configure your web server in a way that the data directory is no longer accessible or you move the data directory outside the web server document root."

The problem is that the JS code checking for a file `data/htaccesstest.txt` expects a 403, 301, 307 or an empty response text but what i get back is a 302, 200 and the login page. 

Here's the problematic piece of code:
https://github.com/nextcloud/server/blob/master/core/js/setupchecks.js#L201

what i did first: 
`GET /data/htaccesstest.txt HTTP/1.1`

the response (HTTP Live Headers Plugin):
```
HTTP/1.1 302 Found
Location: https://CENSORED.com/login
Content-Length: 0
Content-Type: text/html; charset=UTF-8
```

then i thought, length zero should trigger the last condition in the linked js code. but it does not.
so, i went to my login page and executed this in the firebug console, which is just a little debugging copy of the code in the linked file:

```
var afterCall = function(xhr) {
if (xhr.status !== 403 && xhr.status !== 307 && xhr.status !== 301 && xhr.responseText !== '')
	{
		alert(xhr.status + "\n" + xhr.responseText);
	}
};

$.ajax({
	type: 'GET',
	url: 'https://<mycloud>.com/data/htaccesstest.txt?t=1473436782596',
	complete: afterCall,
	allowAuthErrors: true
});
```

what i get then, is a popup telling me 
```
200
<all the login page html>
```

So it does not suffice to filter for 302 response codes, sorry I cannot give you a quick fix for this.
I thought maybe somebody changed some rewrite rules since NC9, but a diff from my backup to the current installation showed nothing I could link to this behaviour.

Keep up the awesome work!

**Comment by nickvergessen** [comment] 2016-09-12 13:42
Duplicate of https://github.com/nextcloud/server/issues/1364

**Closed by nickvergessen** 2016-09-12 13:42 UTC
