### ISSUE TITLE
Uploading large files fails with nextcloud 20.0.6 on raspberry pi 2 with 32bit cpu

### ISSUE THREAD

**Issue by mrkatzo** [nextcloud/server#25782] opened 2021-02-24 12:40 UTC
### Steps to reproduce
1. install nextcloud with apache2 + mariadb on raspi II
2. upload large file (2.5GB+) via webgui
3. see error messages

### Expected behaviour
Uploading large files via nextcloud-webgui should work.

### Actual behaviour
Uploading a file of 5GB takes some time.
When all data is transfered to the nextcloud server, the server obvioulsy starts assembling the file from chunks.
Assembling fails and the following error is displayed in the browser:
[webdav] Fatal: Sabre\DAV\Exception: Error while copying file to target location (copied bytes: -1, expected filesize: -1 ) at <<closure>>

Messeges from protocol from Nextcloud admin-gui from 2021-02-17T22:58:25+0100:
<details>
[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/html/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/html/n ... p", 691, {string: "X-Hash ... "})
 1. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 691
    header("X-Hash-SHA1: 29 ... b")
 2. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 192
    OCA\DAV\Connector\Sabre\File->header("X-Hash-SHA1: 29 ... b")
 3. <<closure>>
    OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/nextcloud/lib/private/Files/Stream/HashWrapper.php line 71
    call_user_func(Closure {}, "*** sensitive parameter replaced ***")
 5. <<closure>>
    OC\Files\Stream\HashWrapper->stream_close()
 6. /var/www/html/nextcloud/3rdparty/icewind/streams/src/Wrapper.php line 132
    fclose(null)
 7. /var/www/html/nextcloud/lib/private/Files/Stream/HashWrapper.php line 75
    Icewind\Streams\Wrapper->stream_close()
 8. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    OC\Files\Stream\HashWrapper->stream_close()
 9. /var/www/html/nextcloud/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
10. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
11. /var/www/html/nextcloud/remote.php line 167
    require_once("/var/www/html/n ... p")

MOVE /nextcloud/remote.php/dav/uploads/walter/web-file-upload-ac54f9335b65f2f7cdefc613ad2a036a-1613594591360/.file
from 192.168.178.38 by walter at 2021-02-17T21:58:25+00:00

[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/html/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/html/n ... p", 691, {string: "X-Hash ... "})
1. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 691
   header("X-Hash-SHA256:  ... 3")
2. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 195
   OCA\DAV\Connector\Sabre\File->header("X-Hash-SHA256:  ... 3")
3. <<closure>>
   OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
4. /var/www/html/nextcloud/lib/private/Files/Stream/HashWrapper.php line 71
   call_user_func(Closure {}, "*** sensitive parameter replaced ***")
5. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   OC\Files\Stream\HashWrapper->stream_close()
6. /var/www/html/nextcloud/apps/dav/lib/Server.php line 332
   Sabre\DAV\Server->exec()
7. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
8. /var/www/html/nextcloud/remote.php line 167
   require_once("/var/www/html/n ... p")

MOVE /nextcloud/remote.php/dav/uploads/walter/web-file-upload-ac54f9335b65f2f7cdefc613ad2a036a-1613594591360/.file
from 192.168.178.38 by walter at 2021-02-17T21:58:25+00:00

[no app in context] Error: Sabre\DAV\Exception: Error while copying file to target location (copied bytes: -1, expected filesize: -1 ) at <<closure>>

 0. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 155
    OCA\DAV\Connector\Sabre\File->put(null)
 1. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 311
    OCA\DAV\Connector\Sabre\Directory->createFile("pso-niemals_web.720p.mkv", null)
 2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 135
    Sabre\DAV\Tree->copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Connector\Sabre\Directory {}, "pso-niemals_web.720p.mkv")
 3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 167
    Sabre\DAV\Tree->copy("uploads/walter/ ... e", "files/walter/sh ... v")
 4. /var/www/html/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 95
    Sabre\DAV\Tree->move("uploads/walter/ ... e", "files/walter/sh ... v")
 5. /var/www/html/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 77
    OCA\DAV\Upload\ChunkingPlugin->performMove("uploads/walter/ ... e", "files/walter/sh ... v")
 6. /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Upload\ChunkingPlugin->beforeMove("uploads/walter/ ... e", "files/walter/sh ... v")
 7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 632
    Sabre\DAV\Server->emit("beforeMove", ["uploads/walter ... "])
 8. /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 9. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
10. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
11. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
12. /var/www/html/nextcloud/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
13. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
14. /var/www/html/nextcloud/remote.php line 167
    require_once("/var/www/html/n ... p")

MOVE /nextcloud/remote.php/dav/uploads/walter/web-file-upload-ac54f9335b65f2f7cdefc613ad2a036a-1613594591360/.file
from 192.168.178.38 by walter at 2021-02-17T21:58:23+00:00

Prior error-message, but file is ok:

[PHP] Error: Error: file_put_contents(): content truncated from 2539095840 to 2147483647 bytes at /var/www/html/nextcloud/lib/private/Files/Storage/Local.php#559 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "file_put_conten ... s", "/var/www/html/n ... p", 559, {path: "files/sh ... l})
 1. /var/www/html/nextcloud/lib/private/Files/Storage/Local.php line 559
    file_put_contents("/opt/externalhd ... t", null)
 2. /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 631
    OC\Files\Storage\Local->writeStream("files/shared/Un ... t", null, null)
 3. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 207
    OC\Files\Storage\Wrapper\Wrapper->writeStream("files/shared/Un ... t", null)
 4. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 155
    OCA\DAV\Connector\Sabre\File->put(null)
 5. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 311
    OCA\DAV\Connector\Sabre\Directory->createFile("Unser Mann in Amerika 720p.mkv", null)
 6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 135
    Sabre\DAV\Tree->copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Connector\Sabre\Directory {}, "Unser Mann in Amerika 720p.mkv")
 7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 167
    Sabre\DAV\Tree->copy("uploads/walter/ ... e", "files/walter/sh ... v")
 8. /var/www/html/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 95
    Sabre\DAV\Tree->move("uploads/walter/ ... e", "files/walter/sh ... v")
 9. /var/www/html/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 77
    OCA\DAV\Upload\ChunkingPlugin->performMove("uploads/walter/ ... e", "files/walter/sh ... v")
10. /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Upload\ChunkingPlugin->beforeMove("uploads/walter/ ... e", "files/walter/sh ... v")
11. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 632
    Sabre\DAV\Server->emit("beforeMove", ["uploads/walter ... "])
12. /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
13. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
14. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
16. /var/www/html/nextcloud/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
17. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
18. /var/www/html/nextcloud/remote.php line 167
    require_once("/var/www/html/n ... p")

MOVE /nextcloud/remote.php/dav/uploads/walter/web-file-upload-797b68e2e43a4df1289f42da62e01670-1613592337334/.file
from 192.168.178.38 by walter at 2021-02-17T20:41:46+00:00
</details>

### Server configuration

**Operating system:** Raspbian GNU/Linux 10 (buster)

**Web server:**  apache2                        2.4.38-3+deb10u4                    armhf

**Database:**  mariadb-server-10.3            1:10.3.27-0+deb10u1                 armhf

**PHP version:**  php7.3-common                  7.3.19-1~deb10u1                    armhf

**Nextcloud version:**  20.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**  fresh

**Where did you install Nextcloud from:** from nextcloud-20.0.6.zip

**Signing status:** don't know about that

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

**List of activated apps:**
<details>
 Mail
1.8.1

Accessibility
1.6.0

Activity
2.13.4

Brute-force settings
2.0.1

Calendar
2.1.3

Collabora Online
3.7.14

Collaborative tags
1.10.0

Comments
1.10.0

Contacts
3.4.3

Contacts Interaction
1.1.0

Dashboard
7.0.0

Deleted files
1.10.1

Federation
1.10.1

File sharing
1.12.2

First run wizard
2.9.0

Log Reader
2.5.0

Monitoring
1.10.0

Nextcloud announcements
1.9.0

Notifications
2.8.0

Password policy
1.10.1

PDF viewer
2.0.1

Photos
1.2.3

Privacy
1.4.0

Recommendations
0.8.0

Right click
0.17.0

Share by mail
1.10.0

Support
1.3.0

Talk
10.0.5

Text
3.1.0

Theming
1.11.0

Update notification
1.10.0

Usage survey
1.8.0

User status
1.0.1

Versions
1.13.0

Video player
1.9.0

Weather status
1.0.0

<summary>App list</summary>

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.8.1
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.14
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.5
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.host.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.6.1",
        "overwrite.cli.url": "https:\/\/my.host.net\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

pi@homunculus:/var/www/html/nextcloud/config $ sudo cat config.php 
<?php
$CONFIG = array (
  'instanceid' => '12345',
  'passwordsalt' => 'blah',
  'secret' => 'blahblah',
  'trusted_domains' => 
  array (
    0 => 'my.host.net',
  ),
  'datadirectory' => '/opt/externalhd/nextclouddata',
  'dbtype' => 'mysql',
  'version' => '20.0.6.1',
  'overwrite.cli.url' => 'https://my.host.net/nextcloud',
  'dbname' => 'nextclouddb',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextclouduser',
  'dbpassword' => '***************',
  'installed' => true,
);

pi@homunculus:/var/log/apache2 $ cat /etc/php/7.3/apache2/php.ini | grep "^[^;[]"
engine = On
short_open_tag = Off
precision = 14
output_buffering = Off
zlib.output_compression = Off
implicit_flush = Off
unserialize_callback_func =
serialize_precision = -1
disable_functions = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,
disable_classes =
zend.enable_gc = On
expose_php = Off
max_execution_time = 3600
max_input_time = 3600
memory_limit = 512M
error_reporting = E_ALL
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
html_errors = On
error_log = /var/log/php_errors.log
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
post_max_size = 8G
auto_prepend_file =
auto_append_file =
default_mimetype = "text/html"
default_charset = "UTF-8"
doc_root =
user_dir =
enable_dl = Off
file_uploads = On
upload_tmp_dir = /opt/externalhd/tmp
upload_max_filesize = 8G
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60
cli_server.color = On
pdo_mysql.default_socket=
SMTP = localhost
smtp_port = 25
mail.add_x_header = Off
odbc.allow_persistent = On
odbc.check_persistent = On
odbc.max_persistent = -1
odbc.max_links = -1
odbc.defaultlrl = 4096
odbc.defaultbinmode = 1
ibase.allow_persistent = 1
ibase.max_persistent = -1
ibase.max_links = -1
ibase.timestampformat = "%Y-%m-%d %H:%M:%S"
ibase.dateformat = "%Y-%m-%d"
ibase.timeformat = "%H:%M:%S"
mysqli.max_persistent = -1
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.default_port = 3306
mysqli.default_socket =
mysqli.default_host =
mysqli.default_user =
mysqli.default_pw =
mysqli.reconnect = Off
mysqlnd.collect_statistics = On
mysqlnd.collect_memory_statistics = Off
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = Off
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0
bcmath.scale = 0
session.save_handler = files
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly =
session.cookie_samesite =
session.serialize_handler = php
session.gc_probability = 0
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.sid_length = 26
session.trans_sid_tags = "a=href,area=href,frame=src,form="
session.sid_bits_per_character = 5
zend.assertions = -1
tidy.clean_output = Off
soap.wsdl_cache_enabled=1
soap.wsdl_cache_dir="/tmp"
soap.wsdl_cache_ttl=86400
soap.wsdl_cache_limit = 5
ldap.max_links = -1

</details>

**Are you using external storage, if yes which one:** external ext4 harddisk /dev/sda1 for file storage and tmp

**Are you using encryption:** don't think so

**Are you using an external user-backend, if yes which one:**  no

### Client configuration
**Browser:**  Firefox 85.0.1 (64-bit)

**Operating system:**  Ubuntu 20.04.2 LTS

#### Web server error log
<details>
pi@homunculus:/var/log/apache2 $ cat error.log.1
[Wed Feb 17 00:00:05.586786 2021] [ssl:warn] [pid 443] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Feb 17 00:00:05.587050 2021] [ssl:warn] [pid 443] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 17 00:00:05.588040 2021] [mpm_prefork:notice] [pid 443] AH00163: Apache/2.4.38 (Raspbian) SVN/1.10.4 OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Feb 17 00:00:05.588104 2021] [core:notice] [pid 443] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 17 02:00:45.082766 2021] [php7:error] [pid 27115] [client 45.155.205.108:43842] script '/var/www/html/index.php' not found or unable to stat
[Wed Feb 17 02:46:25.989123 2021] [php7:error] [pid 27115] [client 13.90.56.166:41106] script '/var/www/html/wp-login.php' not found or unable to stat
[Wed Feb 17 05:57:53.486314 2021] [php7:error] [pid 27117] [client 45.155.205.108:37744] script '/var/www/html/index.php' not found or unable to stat
[Wed Feb 17 18:51:56.275689 2021] [php7:error] [pid 951] [client 45.155.205.108:44766] script '/var/www/html/index.php' not found or unable to stat
[Wed Feb 17 20:44:46.714097 2021] [php7:error] [pid 951] [client 192.241.219.147:38740] script '/var/www/html/search.php' not found or unable to stat
[Wed Feb 17 20:56:01.312885 2021] [mpm_prefork:notice] [pid 443] AH00169: caught SIGTERM, shutting down
[Wed Feb 17 20:56:17.146575 2021] [ssl:warn] [pid 388] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Feb 17 20:56:17.153820 2021] [ssl:warn] [pid 388] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 17 20:56:17.342573 2021] [so:warn] [pid 388] AH01574: module dav_module is already loaded, skipping
[Wed Feb 17 20:56:23.509566 2021] [ssl:warn] [pid 492] AH01906: 127.0.0.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Wed Feb 17 20:56:23.509792 2021] [ssl:warn] [pid 492] AH01909: 127.0.0.1:443:0 server certificate does NOT include an ID which matches the server name
[Wed Feb 17 20:56:23.547542 2021] [mpm_prefork:notice] [pid 492] AH00163: Apache/2.4.38 (Raspbian) SVN/1.10.4 OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Feb 17 20:56:23.547790 2021] [core:notice] [pid 492] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 17 21:33:33.656530 2021] [php7:error] [pid 995] [client 157.245.120.130:34206] script '/var/www/html/wp-login.php' not found or unable to stat
[Thu Feb 18 00:00:30.010481 2021] [mpm_prefork:notice] [pid 492] AH00171: Graceful restart requested, doing restart
[Thu Feb 18 00:00:31.000732 2021] [so:warn] [pid 492] AH01574: module dav_module is already loaded, skipping
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>

[nextcloud.log.txt](https://github.com/nextcloud/server/files/6035979/nextcloud.log.txt)

</details>

**Comment by kesselb** [comment] 2021-02-24 18:26
Closing as duplicate of https://github.com/nextcloud/server/issues/16431.

**Closed by kesselb** 2021-02-24 18:26 UTC
Labels: 0. Needs triage, bug

**Comment by mrkatzo** [comment] 2021-02-25 19:38
This is not really a duplicate of #16431. The error does not speciffically occures at 2GB+ or 4GB+ files. Nextcloud seems to have a bunch of issues with large files. So have one issue for large-file-problems that can then be fixed sometimes.
