### ISSUE TITLE
share by email improvements: share via email to existing users, add note/expiration date to the sent email

### ISSUE THREAD

**Issue by it-1313** [nextcloud/server#27714] opened 2021-06-29 14:44 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
If I want that users edit files online, or to make sure they immediately find a file, and don't have to look for the synced file on their computer (they just need to click a link), it is very practical to share by link/email (even if they are existing users)

Right now (21.0.2) I cannot share by email to existing users who added their email address to their NC profile: the email address auto-completes, but I can only select the NC user, but there is no "share by email" option to click.

Additionally, it would be great if additional info (e.g. a note, expiration date) is added to the email sent by NC, e.g.: 

> Mr. X shared »New Document.odt« with you
>   
>   Note: Hi Sophie, as we discussed, this is the file I need your input. Could you please add your comments?
>   Mr. X set the expiration date to: 12th of July 2021 (13 days)

**Describe the solution you'd like**
So instead of immediately sharing a link after entering the email, the expiration/password/note options would need to be visible. After adding expiration date/note, etc, there could be a button with "send share" and everything is sent together nicely in one email. 

**Describe alternatives you've considered**

**Additional context**

**Comment by szaimen** [comment] 2021-08-08 13:49
Looks like a duplicate of https://github.com/nextcloud/server/issues/13229

**Closed by szaimen** 2021-08-08 13:49 UTC
Labels: enhancement, 0. Needs triage
