### ISSUE TITLE
Stable13: Adding a second Gauge to the admin page for "all user using xx space of xx total space"

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#8290] opened 2018-02-09 19:51 UTC
All in my title. ( i did this in the pull request by error )

This will give the admin a clear and quick view of the storage usage.
Actually, the gauge is giving the admin usage only.

The quota option is sending warning for specific user reaching their limits.
Would be nice to receive as admin a warning quota when the total storage is reaching 80 % or so

I have a 24 TO total storage, with users having quota from 1TO to unlimited space, and the only way to check the free space is through a ssh and df -h or df -k

**Comment by tflidd** [comment] 2018-02-10 14:17
It was already discussed as a feature of the serverinfo app:
https://github.com/nextcloud/serverinfo/issues/46

**Comment by stratege1401** [comment] 2018-02-10 17:35
how, sorry, but september 2016 was wayyyy to old for me  :)

**Comment by MorrisJobke** [comment] 2018-02-12 09:27
> how, sorry, but september 2016 was wayyyy to old for me :)

Anyways a duplicate of https://github.com/nextcloud/serverinfo/issues/46 ;)

Let's close it and keep it to that repo :)

Thanks for the feedback anyway

**Closed by MorrisJobke** 2018-02-12 09:27 UTC
