### ISSUE TITLE
[Feature Request]: Ability to suppress calendar notifications

### ISSUE THREAD

**Issue by Fjodor42** [nextcloud/server#43509] opened 2024-02-10 10:19 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Using Nextcloud mainly for calendar and files, but actually accessing the former in normal calendar clients as opposed to the browser, I am a bit annoyed that after upgrading to NC 28, I have started getting desktop and phone notifications for calendar events from Nextcloud itself. Whether this is from the browser or from my Nextcloud-client indicator is not entirely clear to me at this point.

**Describe the solution you'd like**
Seeing how some people might actually want that, I don't propose reverting whatever change brought this about, but rather to add an option to suppress this - this would probably go into `settings/user/notifications`.

**Describe alternatives you've considered**
If the notifications are from the android app and the Nextcloud client indicator, options to suppress there could be implemented. Seeing that `settings/user/notifications` actually exists, though, I find this alternative less appealing.

**Additional context**
Don't know what to put here as of now, but please request whatever you need :-)

**Comment by kesselb** [comment] 2024-02-11 19:14
Duplicate of https://github.com/nextcloud/server/issues/42659?

**Comment by Fjodor42** [comment] 2024-02-12 00:00
That would seem to be the case, yes - thank you and closing.

**Closed** 2024-02-12 00:01 UTC
Labels: enhancement, needs info, 0. Needs triage, 28-feedback
