### ISSUE TITLE
[Bug]: Incorrect share notification

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#38352] opened 2023-05-17 19:04 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The display of share notifications is not correct, "Hide Document" appears instead of the file name

### Steps to reproduce

1. Go to file app
2. Share a File with the public link

### Expected behavior

The file name is displayed

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
/
```

### List of activated Apps

```shell
Basic app after a fresh install
```

### Nextcloud Signing status

```shell
/
```

### Nextcloud Logs

```shell
/
```

### Additional info

![image](https://github.com/nextcloud/server/assets/38187648/9a9e79f9-16eb-46cf-a108-5b9c6640e2f0)

**Comment by solracsf** [comment] 2023-05-17 20:35
Duplicate of https://github.com/nextcloud/server/issues/38157

**Closed by solracsf** 2023-05-17 20:35 UTC
Labels: bug, 0. Needs triage, 26-feedback
