### ISSUE TITLE
Checkbox for «Remember password» is broken

### ISSUE THREAD

**Issue by Grawl** [nextcloud/server#3454] opened 2017-02-11 05:06 UTC
### Steps to reproduce

1. Open login screen
2. Fill username and password
3. Press a checkbox under login button

### Expected behaviour

Checkbox changed to checked state.

### Actual behaviour

Username and password are sent to server, I logged in **without** remembered session. Next time I want to use Nextcloud I have to login again.

If I click this checkbox before I fill password, it change own status. If I fill password, it works like login button.

### Server configuration

[Your demo page](//demo.nextcloud.com).

### Client configuration

**Browser:** latest stable Safari, latest stable Chrome

**Operating system:** latest stable macOS

**Comment by LukasReschke** [comment] 2017-02-13 09:40
I cannot really reproduce your issue here. Could you post a step by step comparison between expected behaviour and actual behaviour? Thanks a lot! :)

**Comment by Grawl** [comment] 2017-02-14 03:25
@LukasReschke did you tried to toggle that checkbox **after** typing a password?

https://vimeo.com/203940256

**Comment by MorrisJobke** [comment] 2017-03-04 04:09
cc @ChristophWurst

**Comment by Grawl** [comment] 2017-03-08 04:35
@ChristophWurst so you think submitting the form with checkbox is ok?

**Comment by MorrisJobke** [comment] 2017-03-08 06:35
> @ChristophWurst so you think submitting the form with checkbox is ok?

Yes, because in nearly all cases you will click login after ticking it anyway. cc @jancborchardt

**Comment by jancborchardt** [comment] 2017-03-08 23:17
@Grawl yes, this is intended behavior. If you put in your username, and password, and then check »stay logged in«, your next click will be the log in button anyway.

Closing hence. :)

**Closed by jancborchardt** 2017-03-08 23:17 UTC
Labels: bug, needs info

**Comment by jancborchardt** [comment] 2017-03-08 23:19
@Grawl and I just saw on your profile you are a designer – you are very welcome to get involved in Nextcloud development! :) Just check out some of our design issues at https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Adesign

**Comment by Grawl** [comment] 2017-03-10 03:33
> your next click will be the log in button anyway.

okay I got it. clever idea of UX improvement but it's not clear that checkbox is checked and button is pressed. it's unexpected behaviour, and we have to make it so: show checkbox animation and show button click/hover/active animation, so user of login page will be sure that all is ok.
