### ISSUE TITLE
show version differences

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/server#30382] opened 2021-12-22 19:38 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

When someone else changes a file it would be handy to be able to see exactly what changes they made. I suggest a way to visualize these differences.

Here's an idea for how to roll it out in phases:

1. support for diffs (version delta visualizations) for plain text (.txt, markdown) files
2. support for diffs of calendar events
3. support for diffs of address book contacts
4. support for diffs of tasks

**Describe the solution you'd like**

The initial and easiest UI/UX could just be a new window that pops up whenever you click on a version entry for a file, and this opens a new window with a unified text diff to the previous version.

The next evolution of this UI/UX could follow along the lines of, for example, Google Docs.

**Describe alternatives you've considered**

I've considered delegating the version storage and diff generation to something like git. This would work fine for text files.

**Comment by skjnldsv** [comment] 2023-08-02 15:25
duplicate of https://github.com/nextcloud/server/issues/39140

**Closed by skjnldsv** 2023-08-02 15:25 UTC
Labels: enhancement, 0. Needs triage
