### ISSUE TITLE
[Feature Req] Move multiple selected files

### ISSUE THREAD

**Issue by netro** [nextcloud/server#6215] opened 2017-08-22 10:20 UTC
Hello,

It's a feature request; and I'm quite surprised it's not already in nextcloud 😮 
Currently we can drag and drop selected files to a parent folder but not to a specific folder as the "move" option available when dealing with a single file.

### Step to reproduce
  * Select multiple files in a folder;
  * Move all theses files to a specific (not parent) folder <-- missing step

### Expected behaviour
Add a move button next to download or delete button.

### Actual behaviour
Missing feature

### Server configuration
**Operating system**: Debian 9
**Web server:** As in debian 9 stable
**Database:** As in debian 9 stable
**PHP version:** As in debian 9 stable
**Nextcloud version:** 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** 11.0.3 fresh install, then 12.0.1
**Where did you install Nextcloud from:** wget 

### Client configuration
**Browser:** Firefox 54 32b & 55 32b
**Operating system:** Windows 7

**Comment by MorrisJobke** [comment] 2017-08-22 11:46
Duplicate of #2779

**Closed by MorrisJobke** 2017-08-22 11:46 UTC
