### ISSUE TITLE
Same LAN clients keep signing out

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#20045] opened 2020-03-20 10:02 UTC
### Steps to reproduce
1. Have Nextcloud 18.0.2 installed on a Linux device
2. Have multiple clients installed on different or same machines in the same LAN
3. Wait for being signed out of the clients consistently (maybe not all)

### Expected behaviour
Nextcloud should continue to work as expected

### Actual behaviour
Several Nextcloud clients get blocked (Android, iOS, Windows, Linux)

### Server configuration

**Operating system:** Dietpi

**Web server:**

**Database:** Mysql

**PHP version:** 7.3

**Nextcloud version:** 18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Dietpi software manager

**Are you using encryption:** no

### Client configuration
Clients get asked to re-login... refers to Android, iOS, Windows and Linux clients

#### Web server error log
There is a warning in the Logging section of admin settings saying that a specific use login failed (no other description to why that happened, and no additional clients have been added).

I've tried white-listing the IP address in **bruteforce IP whitelist**, but it seems that section is ignored, as that specific IT has been added to `oc_bruteforce_attempts` anyway...

I've oppened a ticket in [nextcloud/bruteforcesettings](https://github.com/nextcloud/bruteforcesettings/issues/178) for it.

**Comment by sir-skipper** [comment] 2020-06-02 10:46
so it's installed on `DietPi`, my lucky guess is that it hasn't been installed manually, but through `dietpi-software`... could it be that the issue is in how it is configured by dietpi package manager ?

**Comment by szaimen** [comment] 2021-06-02 12:13
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 12:13 UTC
Labels: 0. Needs triage, bug
