### ISSUE TITLE
federation shares with many directories / files slow down navigation

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#26214] opened 2021-03-19 15:24 UTC
NC 20.08 and 20.0.4

federation sharing seems only to perform with a very low number of shares and directories.

once sharing 
find . -type d |wc -l
1342
find . -type f |wc -l
6241

navigation operations become so slow to become "unusable" - response time 4-5 minutes.

"mounting" a federation share remains in state "Pending" for a long time until it displays the size of the mounted share.

I guess that the calculation of the size of a folder is redone every time the folder is accessed and is not performance optimized. 

Example
Trying to move a 1kb file from such a shared folder to a local folder causes a delay of displaying the target directories, 

- the first choice obviously is the the source directory, where the file resides - the size is calculated 
- the second choice is the the parent of the source directory, where the file resides - the size is calculated again
- the 3 choice is a local directory - this works reasonable fast.

**Comment by sunjam** [comment] 2021-03-20 16:38
This has also been by experience as well when mounting Nextcloud or WebDAV shares to external storage.  #8459 could help with this...  being able to optionally keep a copy of the federated share on your local server rather than constantly attempting to access it.

**Comment by szaimen** [comment] 2021-06-25 14:52
Duplicate of https://github.com/nextcloud/server/issues/4339

**Closed by szaimen** 2021-06-25 14:52 UTC
Labels: 0. Needs triage, bug

**Comment by sunjam** [comment] 2021-06-25 15:56
OAuth Scopes Scope is a mechanism in OAuth 2.0 to limit an application's
access to a user's account. An application can request one or more scopes,
this information is then presented to the user in the consent screen, and
the access token issued to the application will be limited to the scopes
granted.

Full details at https://oauth.net/2/scope/
