### ISSUE TITLE
Incoming share email broken

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18380] opened 2019-12-12 15:30 UTC
Since https://github.com/nextcloud/server/pull/16828, when clicking on the file link in the email notification about an incoming share, the user ends up in his Nextcloud profile seeing only

![image](https://user-images.githubusercontent.com/1804221/70725378-89f39600-1cfc-11ea-9068-9d58ae4a9e5e.png)

**Comment by ChristophWurst** [comment] 2019-12-19 08:49
Looks like this has been resolved in the meantime. I tried with current master and both link share for folder as well as for a single file send an email with a link that works.

**Comment by wiswedel** [comment] 2019-12-19 13:36
Nope, not for me. And I think it cannot work after all, since the link under the button in the email points to a file ID (e.g. https://cloud.example.com/f/7), that's not yet existing for the sharee until they *accepted* the incoming share.

**Comment by ChristophWurst** [comment] 2019-12-19 13:42
Okay, can't reproduce then.

**Comment by ChristophWurst** [comment] 2019-12-19 13:42
Is this about guests? Because I just tried a simple share to an email address?

**Comment by wiswedel** [comment] 2019-12-19 13:46
It's about normal users, getting an incoming share email notification.

**Comment by ChristophWurst** [comment] 2019-12-19 13:49
Got it.

**Comment by rullzer** [comment] 2020-01-06 15:09
Just noticed this as well in a mail I got. And I can now also see properly why and how.
Let me prepare a fix.

**Closed** 2020-01-06 19:02 UTC
Labels: 0. Needs triage, 18-feedback, bug, feature: activity and notification, feature: sharing, regression
