### ISSUE TITLE
server version in about pages

### ISSUE THREAD

**Issue by Eothred** [nextcloud/server#21304] opened 2020-06-08 09:53 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The nextcloud version is easily accessible to admins, through the admin settings page. However now I was using an instance where I do not have admin rights and to me it was quite confusing to figure out what version the server was running I just realized. Intuitively I would have expected to find it on the about pages, or perhaps somewhere in the settings. Do note that this could be present somewhere already and I am just being blind. The only thing I found was in the last tab of the about pages, where the documentation url's had the major version included.

I needed to know this because I was trying to use an integration which was only working for certain versions, and I was not sure if it would work/why it did not work on this server.

**Describe the solution you'd like**
I think that in the About pages, a tab with something like "What's new in Nextcloud N" or similar could make sense, summarizing the most important new features as you see it (very brief then), and clearly showing to the user what version the server is running at the same time. Another good spot would be at the top of the (user) settings page, or perhaps somewhere at the bottom of the main page.

**Additional context**
Checked on Nextcloud 17 and 18, to me it seems that this information is not easily/obviously accessible to the non-admin user.

**Comment by kesselb** [comment] 2020-06-08 11:18
> and clearly showing to the user what version the server is running at the same time. 

Sounds good.

> I needed to know this because I was trying to use an integration which was only working for certain versions, and I was not sure if it would work/why it did not work on this server.

The integration should check if the Nextcloud server is compatible from my pov.

**Comment by rullzer** [comment] 2020-06-11 12:06
Fair point.
For now you can also user `SERVER/status.php` to get the version

**Comment by simonspa** [comment] 2020-06-11 12:59
I always use the Nextcloud Security Scan for that as a user... :)

**Comment by juliushaertl** [comment] 2020-06-12 07:16
> and clearly showing to the user what version the server is running at the same time.

Would be https://github.com/nextcloud/firstrunwizard/issues/82 then

**Comment by jancborchardt** [comment] 2020-07-21 12:30
@Eothred do you want to check **Add version number to the first run wizard?** https://github.com/nextcloud/firstrunwizard/issues/82 and submit a pull request to fix that issue? :)

**Comment by juliushaertl** [comment] 2020-07-23 12:02
Let's close this then as a duplicate of https://github.com/nextcloud/firstrunwizard/issues/82

**Closed by juliushaertl** 2020-07-23 12:02 UTC
Labels: 1. to develop, enhancement, good first issue
