### ISSUE TITLE
[Bug]: After NC Upgrade from:  27.1.2.1 to  27.1.3.2 - log will be flooted with messages "user":"--","app":"no app in context" "NOW: register" 

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#41402] opened 2023-11-12 17:22 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Bug]: After NC Upgrade from:  27.1.2.1 to  27.1.3.2 - log will be flooted with messages "user":"--","app":"no app in context" "NOW: register" 

There are about 20 messages  per second
![ScreenShot024](https://github.com/nextcloud/server/assets/32612067/185755db-97f4-45f8-a485-6c2a9a24d09a)

There is no indication, that the warnings are coming from one client. Multiples/many IP's are involved.

### Steps to reproduce

1. tail -f /media/log/nextcloud.log
2. check the Browser's GUI

### Expected behavior

- warnings should indicate, where they come from
- no warnings at all

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"system": {
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***,
            "dbindex": ***REMOVED SENSITIVE VALUE***,
            "timeout": ***REMOVED SENSITIVE VALUE***,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "debug": false,
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "updater.release.channel": "stable",
        "upgrade.disable-web": false,
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "logfile": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 1200,
        "session_keepalive": false,
        "logtimezone": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "CH",
        "knowledgebaseenabled": false,
        "log_rotate_size": ***REMOVED SENSITIVE VALUE***,
        "mail_sendmailmode": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "passman",
            "dicomviewer",
            "radio",
            "cookbook",
            "health",
            "issuetemplate",
            "documentserver_community",
            "imageconverter",
            "epubreader",
            "workflow_pdf_converter",
            "signlive",
            "apporder",
            "rainloop"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - analytics: 4.11.0
  - announcementcenter: 6.7.0
  - audioplayer: 3.4.0
  - bookmarks: 13.1.1
  - breezedark: 27.0.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.3
  - calendar_resource_management: 0.5.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - collectives: 2.9.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - cookbook: 0.10.2
  - cospend: 1.5.10
  - dashboard: 7.7.0
  - data_request: 1.14.0
  - dav: 1.27.0
  - deck: 1.11.0
  - dicomviewer: 1.2.5
  - drawio: 2.1.4
  - drop_account: 2.3.2
  - electronicsignatures: 2.0.5
  - end_to_end_encryption: 1.13.1
  - event_update_notification: 2.2.0
  - extract: 1.3.6
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_antivirus: 5.3.0
  - files_automatedtagging: 1.17.0
  - files_external: 1.19.0
  - files_markdown: 2.4.1
  - files_mindmap: 0.0.29
  - files_pdfviewer: 2.8.0
  - files_photospheres: 1.27.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - flow_notifications: 1.7.0
  - forms: 3.3.1
  - gpxpod: 5.0.13
  - groupfolders: 15.3.1
  - health: 1.6.2
  - imageconverter: 1.3.5
  - impersonate: 1.14.0
  - integration_collaboard: 1.0.6
  - integration_discourse: 2.0.4
  - integration_dropbox: 2.1.0
  - integration_github: 2.0.6
  - integration_gitlab: 1.0.18
  - integration_google: 2.1.0
  - integration_jira: 1.0.6
  - integration_mastodon: 2.0.3
  - integration_openai: 1.1.1
  - integration_openproject: 2.4.6
  - integration_reddit: 2.0.2
  - integration_replicate: 1.0.8
  - integration_twitter: 1.0.7
  - integration_zammad: 2.0.6
  - issuetemplate: 0.7.0
  - keeweb: 0.6.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.4
  - maps: 1.1.1
  - money: 0.23.1
  - news: 24.0.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - passman: 2.4.7
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.4.1
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quicknotes: 0.8.10
  - quota_warning: 1.17.0
  - rainloop: 7.2.6
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.2
  - richdocumentscode: 23.5.503
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.11.1
  - social: 0.6.1
  - socialsharing_diaspora: 3.0.0
  - socialsharing_email: 3.0.0
  - socialsharing_facebook: 3.0.0
  - socialsharing_twitter: 3.0.0
  - spreed: 17.1.2
  - support: 1.10.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tables: 0.6.1
  - tasks: 0.15.0
  - terms_of_service: 2.3.1
  - text: 3.8.0
  - theming: 2.2.0
  - timemanager: 0.3.8
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - video_converter: 1.0.6
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - welcome: 1.0.10
  - workflow_pdf_converter: 1.12.0
  - workflow_script: 1.12.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0 (installed 1.6.0)
  - audioplayer_editor: 0.3.0 (installed 0.3.0)
  - audioplayer_sonos: 1.3.0 (installed 1.3.0)
  - cms_pico: 1.1.0-beta.1 (installed 1.0.20)
  - encryption: 2.15.0
  - epubreader: 1.4.7
  - external: 5.2.1 (installed 5.2.1)
  - files_3d: 0.5.0 (installed 0.5.0)
  - files_accesscontrol: 1.17.1 (installed 1.17.1)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external_onedrive: 1.1.0 (installed 1.1.0)
  - files_fulltextsearch: 27.0.1 (installed 27.0.1)
  - flowupload: 1.1.3 (installed 1.1.3)
  - fulltextsearch: 27.0.2 (installed 27.0.2)
  - fulltextsearch_elasticsearch: 27.0.4 (installed 27.0.4)
  - gpxedit: 0.0.14 (installed 0.0.14)
  - gpxmotion: 0.1.0 (installed 0.1.0)
  - hibp: 0.1.0 (installed 0.1.0)
  - integration_moodle: 1.0.2 (installed 1.0.2)
  - integration_onedrive: 3.1.0 (installed 3.1.0)
  - integration_suitecrm: 1.0.3 (installed 1.0.3)
  - integration_whiteboard: 0.0.14 (installed 0.0.14)
  - joplin: 0.0.25 (installed 0.0.25)
  - libresign: 7.1.1 (installed 7.1.1)
  - ojsxc: 5.0.0 (installed 5.0.0)
  - passwords: 2023.11.30 (installed 2023.11.30)
  - podcast: 0.3.1 (installed 0.3.1)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - registration: 2.2.0 (installed 2.2.0)
  - signlive: 0.9.0 (installed 0.9.0)
  - socialsharing_googleplus: 1.0.4 (installed 1.0.4)
  - survey_client: 1.15.0 (installed 1.3.0)
  - talk_matterbridge: 1.26.0 (installed 1.26.0)
  - talked: 0.5.0 (installed 0.5.0)
  - user_ldap: 1.17.0
  - weather: 1.7.7 (installed 1.7.7)
  - workflow_media_converter: 1.8.4 (installed 1.8.4)
  - workflow_ocr: 1.27.5 (installed 1.26.1)
  - yumisign_nextcloud: 1.0.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"ZVEJBgxSWar1zd7yMTWfjwAAAAo","level":2,"time":"2023-11-12T18:19:02+01:00","remoteAddr":"xxxx","user":"--","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications?format=json","message":"NOW: register","userAgent":"Mozilla/5.0 (Windows) mirall/3.10.1stable-Win64 (build 20231025) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"27.1.3.2","data":[]}
{"reqId":"ZVEJBgxSWar1zd7yMTWfkAAAAAI","level":2,"time":"2023-11-12T18:19:02+01:00","remoteAddr":"xxxx","user":"--","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status?format=json","message":"NOW: register","userAgent":"Mozilla/5.0 (Windows) mirall/3.10.1stable-Win64 (build 20231025) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"27.1.3.2","data":[]}
```

### Additional info

https://help.nextcloud.com/t/nextcloud-log-is-continuously-spammed/173948

Before doing the Upgrade, the Cloud was set to Maintenance Window for about seven minutes before "cutting the line"

**Comment by kesselb** [comment] 2023-11-12 18:40
Thanks!

Closing as duplicate of https://github.com/nextcloud/socialsharing/issues/77

**Closed by kesselb** 2023-11-12 18:40 UTC
Labels: bug, 0. Needs triage
