### ISSUE TITLE
[Bug]: On Log out I always get: "... ignoring session_start() because a session is already active ..."

### ISSUE THREAD

**Issue by ro56** [nextcloud/server#36083] opened 2023-01-11 11:16 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

on every logout from nextcloud server the following error message is being logged:
[PHP] Error: session_start(): Ignoring session_start() because a session is already active at /var/www/nextcloud/lib/private/Session/Internal.php#219

GET /logout?requesttoken=jEq2TSqVpriFh35iGNX5SUyfMTZGqrYLNCX%2FEdjcu9U%3D%3A43r0PhLC8vH8xB0jQZ2TEw7PXHclnuJAB3WvR7Gl3oQ%3D
from 84.118.244.93 at 2023-01-11T10:54:55+00:00 

### Steps to reproduce

1. simply log out from server and watch log

### Expected behavior

no error log

### Installation method

Official All-in-One appliance

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud66.dynv6.net",
            "route66.dynv6.net",
            "cloud66.ddnss.de",
            "route66.ddnss.de",
            "nextcloud.fritz.box",
            "cloud66.spdns.eu",
            "route66.spdns.eu",
            "nextcloud",
            "192.168.178.21",
            "2a02:908:2732:c860:201:2eff:fe70:c744"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.2.3",
        "overwrite.cli.url": "https:\/\/cloud66.dynv6.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\ACPu",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "trashbin_retention_obligation": "auto,180",
        "app_install_overwrite": [
            "radio"
        ],
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    }
}
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"hVwaI6Umwt1IMGDU7AIc","level":3,"time":"2023-01-11T10:54:55+00:00","remoteAddr":"84.118.244.93","user":"--","app":"PHP","method":"GET","url":"/logout?requesttoken=jEq2TSqVpriFh35iGNX5SUyfMTZGqrYLNCX%2FEdjcu9U%3D%3A43r0PhLC8vH8xB0jQZ2TEw7PXHclnuJAB3WvR7Gl3oQ%3D","message":"session_start(): Ignoring session_start() because a session is already active at /var/www/nextcloud/lib/private/Session/Internal.php#219","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","version":"25.0.2.3","data":{"app":"PHP"},"id":"63be9a466401b"}
```

**Comment by solracsf** [comment] 2023-01-11 17:04
An app could be the cause of this. Try the following:

1. Login
2. Disable an app (try 1st those not marked as "Featured" on the Apps list)
3. Logout and see if error is gone.

Repeat until you've tried all apps.

**Comment by ro56** [comment] 2023-01-11 17:32
The bug seemsto be caused by SnappyMail, after disabling it there are no more error messages.

**Comment by solracsf** [comment] 2023-01-11 18:13
Related: https://github.com/the-djmaze/snappymail/issues/813
But please report it or in that topic, or in a new issue on that repository.

**Comment by ro56** [comment] 2023-01-11 18:54
I've seen You've already link the two issues, so I won't generate anymore noise ;-).
Thx

Mit freundlichen Grüßen

Rainer Ophoven
Im Pettches Garten 84
64331 Weiterstadt
+49 178 5495609

**Comment by the-djmaze** [comment] 2023-01-18 15:59
As the owner of SnappyMail, I can't find nor reproduce the problem.

Since session_start() is only called by `lib/base.php` it is likely that this file is included twice and not called with `require_once`.
https://github.com/nextcloud/server/blob/master/lib/base.php

Nextcloud itself does not include twice as my search result is:
```
./index.php:34:	require_once __DIR__ . '/lib/base.php';
./ocs-provider/index.php:22:require_once __DIR__ . '/../lib/base.php';
./ocs/providers.php:27:require_once __DIR__ . '/../lib/base.php';
./ocs/v1.php:31:require_once __DIR__ . '/../lib/base.php';
./remote.php:114:	require_once __DIR__ . '/lib/base.php';
./core/templates/404-profile.php:8:	require_once '../../lib/base.php';
./core/templates/404.php:7:	require_once '../../lib/base.php';
./core/templates/403.php:4:	require_once '../../lib/base.php';
./core/ajax/update.php:40:require_once '../../lib/base.php';
./ocm-provider/index.php:23:require_once __DIR__ . '/../lib/base.php';
./cron.php:43:	require_once __DIR__ . '/lib/base.php';
./console.php:48:	require_once __DIR__ . '/lib/base.php';
./status.php:37:	require_once __DIR__ . '/lib/base.php';
./public.php:36:	require_once __DIR__ . '/lib/base.php';
```

So to find out why Nextcloud `lib/base.php` is included twice, you should protect the file and change the bottom line in something like:
```php
if (OC::$SERVERROOT) {
	error_log('base.php loaded twice: '.print_r(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS), true));
} else {
	OC::init();
}
```

This properly logs into the php error log what goes wrong.

**Comment by the-djmaze** [comment] 2023-01-18 16:43
Found the problem that happens on logout.
There are three session_start requests:

1. OC::initSession
2. OC\Session\CryptoSessionData::reopen
3. OC\Session\CryptoSessionData::clear

```
[18-Jan-2023 16:36:51 UTC] session_start: Array
(
    [0] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/Session/Internal.php
            [line] => 56
            [function] => startSession
            [class] => OC\Session\Internal
            [type] => ->
        )

    [1] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/base.php
            [line] => 434
            [function] => __construct
            [class] => OC\Session\Internal
            [type] => ->
        )

    [2] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/base.php
            [line] => 676
            [function] => initSession
            [class] => OC
            [type] => ::
        )

    [3] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/base.php
            [line] => 1144
            [function] => init
            [class] => OC
            [type] => ::
        )

    [4] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/index.php
            [line] => 34
            [args] => Array
                (
                    [0] => /home/rainloop/public_html/nextcloud/lib/base.php
                )

            [function] => require_once
        )

)

[18-Jan-2023 16:36:51 UTC] session_start: Array
(
    [0] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/Session/Internal.php
            [line] => 181
            [function] => startSession
            [class] => OC\Session\Internal
            [type] => ->
        )

    [1] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/Session/CryptoSessionData.php
            [line] => 166
            [function] => reopen
            [class] => OC\Session\Internal
            [type] => ->
        )

    [2] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/AppFramework/Middleware/SessionMiddleware.php
            [line] => 55
            [function] => reopen
            [class] => OC\Session\CryptoSessionData
            [type] => ->
        )

    [3] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php
            [line] => 97
            [function] => beforeController
            [class] => OC\AppFramework\Middleware\SessionMiddleware
            [type] => ->
        )

    [4] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php
            [line] => 125
            [function] => beforeController
            [class] => OC\AppFramework\Middleware\MiddlewareDispatcher
            [type] => ->
        )

    [5] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/AppFramework/App.php
            [line] => 172
            [function] => dispatch
            [class] => OC\AppFramework\Http\Dispatcher
            [type] => ->
        )

    [6] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/Route/Router.php
            [line] => 298
            [function] => main
            [class] => OC\AppFramework\App
            [type] => ::
        )

    [7] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/base.php
            [line] => 1047
            [function] => match
            [class] => OC\Route\Router
            [type] => ->
        )

    [8] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/index.php
            [line] => 36
            [function] => handleRequest
            [class] => OC
            [type] => ::
        )

)

[18-Jan-2023 16:36:51 UTC] session_start loaded twice: Array
(
    [0] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/Session/Internal.php
            [line] => 110
            [function] => startSession
            [class] => OC\Session\Internal
            [type] => ->
        )

    [1] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/Session/CryptoSessionData.php
            [line] => 162
            [function] => clear
            [class] => OC\Session\Internal
            [type] => ->
        )

    [2] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/User/Session.php
            [line] => 939
            [function] => clear
            [class] => OC\Session\CryptoSessionData
            [type] => ->
        )

    [3] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/core/Controller/LoginController.php
            [line] => 117
            [function] => logout
            [class] => OC\User\Session
            [type] => ->
        )

    [4] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php
            [line] => 225
            [function] => logout
            [class] => OC\Core\Controller\LoginController
            [type] => ->
        )

    [5] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php
            [line] => 133
            [function] => executeController
            [class] => OC\AppFramework\Http\Dispatcher
            [type] => ->
        )

    [6] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/AppFramework/App.php
            [line] => 172
            [function] => dispatch
            [class] => OC\AppFramework\Http\Dispatcher
            [type] => ->
        )

    [7] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/private/Route/Router.php
            [line] => 298
            [function] => main
            [class] => OC\AppFramework\App
            [type] => ::
        )

    [8] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/lib/base.php
            [line] => 1047
            [function] => match
            [class] => OC\Route\Router
            [type] => ->
        )

    [9] => Array
        (
            [file] => /home/rainloop/public_html/nextcloud/index.php
            [line] => 36
            [function] => handleRequest
            [class] => OC
            [type] => ::
        )

)
```

**Comment by joshtrichards** [comment] 2023-07-24 18:26
Isn't this a duplicate of #35930?

**Comment by ro56** [comment] 2023-07-24 18:47
it's almost a duplicate only I never observed that both snappymail and password had to be activated. I only observed it with snappymail activated.
anyway it's gone with 27.0.1

Cheers, Rainer

**Closed** 2023-07-24 20:16 UTC
Labels: bug, 0. Needs triage, 25-feedback
