### ISSUE TITLE
Delete photos from Gallery directly 

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#21784] opened 2020-07-09 20:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
One should be able to delete photos directly from gallery without needing to access "Files" and perform said action there. Currently there is no way of going about deleting photos quickly from gallery.

**Describe the solution you'd like**
I suggest "Delete" action to be added on the top bar in the photo and video viewer - 
![Screenshot_1](https://user-images.githubusercontent.com/36133540/87087875-26026300-c234-11ea-9d8e-ea7d15680f3c.png)

**Comment by kesselb** [comment] 2020-07-10 07:05
Duplicate of https://github.com/nextcloud/viewer/issues/483

**Closed by kesselb** 2020-07-10 07:05 UTC
Labels: 0. Needs triage, enhancement

**Comment by pepa65** [comment] 2022-10-07 02:57
From the included image, you can see that this issue concerns the Photos app, not the Files (Viewer) app. This is not fixed, please reopen!
