### ISSUE TITLE
Can't exit picture viewer and return to folder

### ISSUE THREAD

**Issue by Alt37** [nextcloud/server#28854] opened 2021-09-15 15:40 UTC
Sometimes picture viewer doesn't close. User presses "close" button, picture disappears but user doesn't return to folder and there's still semi-transparent dark background, picture title, menu etc. Menu works: user can download file, open side panel and "delete" file. The only way for a user to exit viewer is to reload browser page. If user remove `div id="viewer"` with a browser "inspector", it would be possible to open other file without reloading a page and this issue might not re-appear.
It's not reproducible each time but easier to trigger if you open picture after search.

### Steps to reproduce
1. Search some folder and open it from a popup
2. Open some picture
3. Try to close picture viewer

### Expected behaviour
User should return to folder with a picture

### Actual behaviour
Viewer doesn't close completely (

![зображення](https://user-images.githubusercontent.com/44649402/133463174-87f7fd3c-aa5c-4c89-8feb-1abf3aac4223.png)

I would like to debug it further but not sure where to look when this happen.

### Server configuration

**Database:** mysql 10.3.31

**PHP version:** 7.4.21

**Nextcloud version:** 21.0.3 at Hetzner, also reproducible with self-configured 22.1.1

**Comment by szaimen** [comment] 2021-09-15 15:42
Duplicate of https://github.com/nextcloud/viewer/issues/893

**Closed by szaimen** 2021-09-15 15:42 UTC
Labels: bug, 0. Needs triage
