### ISSUE TITLE
[Bug]: 28 and 28.0.1 cannot be dragged and uploaded

### ISSUE THREAD

**Issue by smilesxsy** [nextcloud/server#42478] opened 2023-12-25 15:29 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dragging the file directly to the browser will pop up. Dragging the file here will keep flashing, and if it cannot be dragged, it will become a download

### Steps to reproduce

1.Dragging the file directly to the browser will pop up. Dragging the file here will keep flashing, and if it cannot be dragged, it will become a download
2.
3.

### Expected behavior

I can drag and drop and upload it

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by xpfgsyb** [comment] 2023-12-26 12:26
Same here - rolling back to a snapshot with server version 27.1.5 fixes the issue immediately.

Some additional information about my environment:
Affected versions: 28 and 28.0.1
OS: Debian 12.4
PHP version: 8.2.7
Web server: Apache 2.4.57-2
Bug present after an update from 27.1.5 to 28.x
Updating all apps: didn't help
Disable all apps that I could see in Apps, Active Apps: didn't help

**Comment by joshtrichards** [comment] 2023-12-26 22:36
Duplicate of #42136

**Closed by joshtrichards** 2023-12-26 22:36 UTC
Labels: bug, 0. Needs triage
