### ISSUE TITLE
Files - Wrong sort order when file name starts with digits.

### ISSUE THREAD

**Issue by sciurius** [nextcloud/server#19873] opened 2020-03-10 10:27 UTC
### Steps to reproduce

1. In a new. empty folder, create the following files:

007a.txt
00ca.txt
0baa.txt
100a.txt

### Expected behaviour

The files should be listed in the order above (sorted alphabetically).

### Actual behaviour

The files are ordered using natural sort order instead of alphabetically.

00ca.txt
0baa.txt
007a.txt
100a.txt

While this may have advantages in certain situations, natural sort order totally screws up when file names are e.g. date or uuid based.

### Server configuration

**Operating system:** DMS 6.2

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.3

**Nextcloud version:** 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 18.0.0

**Where did you install Nextcloud from:** Nexcloud updater.phar

### Client configuration
**Browser:** Firefox

**Operating system:** Fedora 31

**Comment by Friptick** [comment] 2020-05-08 06:50
Same problem! Many people find so-called natural sort order unintuitive.

This it seems to have been "added" as a feature! #2262 

Is it configurable, or could it be reverted by changing the server locale?

**Comment by Friptick** [comment] 2020-05-18 09:14
Turns out that unnatural-natural sort order is used on the Android app too.

Making it configurable is obviously not going to be a priority. Perhaps close this issue, you have enough to do already.

**Comment by szaimen** [comment] 2021-06-02 11:14
I think this is a duplicate of https://github.com/nextcloud/server/issues/13661

**Closed by szaimen** 2021-06-02 11:14 UTC
Labels: 0. Needs triage, bug
