### ISSUE TITLE
[Bug]: Path resets/changes to root path if iterating through file previews

### ISSUE THREAD

**Issue by JL710** [nextcloud/server#48913] opened 2024-10-27 13:43 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have installed nextcloud via aio on version 29.0.8.

When I am in a folder and view images or audio files, the path goes to the root path when I click to the next preview (the arrows on the left and right).

### Steps to reproduce

1. go into a subfolder with files that can be viewed
2. view a file
3.click to the next file (arrows left and right)
If you exit the viewer you should be in the root directory of your profile.

### Expected behavior

I expect to be in the same folder as the files that I viewed after exiting the viewer.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

**Comment by susnux** [comment] 2024-10-31 15:38
Duplicate of https://github.com/nextcloud/viewer/issues/2567

**Closed by susnux** 2024-10-31 15:38 UTC
Labels: bug, 0. Needs triage, feature: files, 29-feedback, 30-feedback
