### ISSUE TITLE
Some of your Link Shares have been removed - Data lost

### ISSUE THREAD

**Issue by gboisvert** [nextcloud/server#16131] opened 2019-06-27 15:25 UTC
### Steps to reproduce
Message "Some of your link shares has been removed".  I had the message with v15, upgraded to v16, message still there.  Found the missing directories under /var/www/html/nextcloud/data/__groupfolders

### Expected behaviour
- Message with real meaning (with explanation)
- NEVER EVER LOOSE DATA (well not completely lost here but i had almost a heart attack seeing the folders disappeared under my user's account)
- To have some kind of procedure to fix this issue

### Actual behaviour
- Folders just disappeared
- Message with no explanation
- Software took action without acknowledge from the admin resulting in lost of data for user / groups
- Difficult to take action, fear of worsening the situation (like moving / renaming the found folders back to user's directory)
- The missing folders "definitions" seems to hang somewhere, how to fix / stop the annoying message for good

## Server configuration detail

**Operating system:** Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64

**Webserver:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.29 (apache2handler)

**Database:** mysql 5.5.60

**PHP version:** 

7.1.29
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mcrypt, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache

**Nextcloud version:** 16.0.1 - 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated 

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest.tar.bz2 (a while back)

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - bookmarks: 1.0.6
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - keeweb: 0.5.1
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.2
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - groupfolders
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "172.16.1.125",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/172.16.1.225\/nextcloud",
    "dbtype": "mysql",
    "version": "16.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** Files? Communication (https) ? Other?  Blurry question IMHO!

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

**Operating system:** Ubuntu 18.04 LTS

## Logs

<details><summary>Web server error log</summary>

```
N/A
```
</details>

<details><summary>Nextcloud log</summary>

```
Error	index	OCP\Files\NotFoundException: /user1/files/Directory1

    /var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 134:

    OC\Files\Node\Root->get("/boig01/files/Famille")

    /var/www/html/nextcloud/apps/recommendations/lib/Service/RecentlySharedFilesSource.php - line 122:

    OC\Files\Node\Folder->get("/Famille")

    <<closure>>

    OCA\Recommendations\Service\RecentlySharedFilesSource->OCA\Recommendations\Service\{closure}("*** sensiti ... *")

    /var/www/html/nextcloud/apps/recommendations/lib/Service/RecentlySharedFilesSource.php - line 127:

    array_map(Closure {}, [ OC\Share20 ... }])

    /var/www/html/nextcloud/apps/recommendations/lib/Service/RecommendationService.php - line 91:

    OCA\Recommendations\Service\RecentlySharedFilesSource->getMostRecentRecommendation(OC\User\User {}, 6)

    <<closure>>

    OCA\Recommendations\Service\RecommendationService->OCA\Recommendations\Service\{closure}("*** sensiti ... *")

    /var/www/html/nextcloud/apps/recommendations/lib/Service/RecommendationService.php - line 92:

    array_reduce([ OCA\Recomm ... "], Closure {}, [])

    /var/www/html/nextcloud/apps/recommendations/lib/Controller/RecommendationController.php - line 63:

    OCA\Recommendations\Service\RecommendationService->getRecommendations(OC\User\User {})

    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OCA\Recommendations\Controller\RecommendationController->index()

    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Recommen ... {}, "index")

    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 126:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Recommen ... {}, "index")

    /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Recomm ... r", "index", OC\AppFramew ... {}, { _route: "r ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "r ... "})

    /var/www/html/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "r ... "})

    /var/www/html/nextcloud/lib/base.php - line 975:

    OC\Route\Router->match("/apps/recom ... s")

    /var/www/html/nextcloud/index.php - line 42:

    OC::handleRequest()
```
</details>

<details><summary>Browser log</summary>

N/A
</details>

**Comment by kesselb** [comment] 2019-06-27 16:21
> Some of your Link Shares have been removed

Code behind this message does not delete any file. It's about link shares. Is `Famille` your folder or a folder shared to you by another user? Is there something else in the logs?

> "mail_smtpmode": "php",

Not related to your issue: This way of sending emails is not longer supported. Please update your configuration.

**Comment by gboisvert** [comment] 2019-06-27 16:33
@kesselb  Well, i'm a sysadmin with a problem to solve!  I can understand that the code behind doesn't delete or move any file.  I reported the message and what i found around it.  So sorry if the title is misleading but it is what we got.  So what do you suggest?  Thanks for your time / patience.  I'm new to this and i promised you won't have to repeat!!!

**Comment by kesselb** [comment] 2019-06-27 18:00
> Well, i'm a sysadmin with a problem to solve! I can understand that the code behind doesn't delete or move any file. I reported the message and what i found around it. 

That was just a hint. We need to look deeper.

> So what do you suggest? 

 Is Famille your folder or a folder shared to you by another user? Is there something else in the logs?

**Comment by jospoortvliet** [comment] 2019-06-28 09:14
also see https://help.nextcloud.com/t/some-of-your-link-shares-have-been-removed-15-0-8/53522 ;-)

**Comment by skjnldsv** [comment] 2019-08-07 15:36
Duplicate of https://github.com/nextcloud/server/issues/15643

**Closed by skjnldsv** 2019-08-07 15:36 UTC
Labels: 0. Needs triage, bug
