### ISSUE TITLE
File Size Limit

### ISSUE THREAD

**Issue by tobilap** [nextcloud/server#4240] opened 2017-04-06 09:05 UTC
I noticed that I was unable to sync large files using my OdroidXU4.
Uploading to the Server was fine but synchronizing these files to another device failed.
By checking the corresponding line in the source. I made a "small fix"
but I'm not sure if it is a good idea to remove this limit
https://github.com/nextcloud/3rdparty/blob/18adb82bab030a0af41e66e421a90d123a21a8f2/sabre/http/lib/Sapi.php#L78

`stream_copy_to_stream($body, $output);//, $contentLength);`

I would love to have some opinions on this. Is this security critical?

**Comment by MorrisJobke** [comment] 2017-04-06 16:40
Duplicate of #1707

See https://github.com/nextcloud/server/issues/1707#issuecomment-288890497

**Closed by MorrisJobke** 2017-04-06 16:40 UTC
