### ISSUE TITLE
Shared files not shared anymore after occ encryption:decrypt-all username executed

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/server#42849] opened 2024-01-16 12:09 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. On the admin side: execute the nextcloud occ command `encryption:decrypt-all username`
2. Once deencryption is done, on the user side: log into account and open the spreed app.
3. Click on a conversation where some files were shared before.
4. The shared files have disappeared.

### Expected behaviour
Nextcloud deencryption should not remove the shared files from spreed conversations.
Once deencryption is done, files should remain shared within all conversations of a user.
### Actual behaviour
The files shared in conversations are not shared anymore.

**Important notes**: The shared file did not disappear. They are still accessible from the **Files** app in the **Talk/** folder. But these files are not shared anymore within any conversation of Spreed.
Interestingly, the **vocal recordings do not suffer from that issue**! After deencryption they remain shared in all Spreed conversation.

## Talk app

**Talk app version:** 17.1.4

**Custom Signaling server configured:** no
**Custom TURN server configured:** no
**Custom STUN server configured:** no

## Browser

**Microphone available:** no

**Camera available:** no

**Operating system:** all OS

**Browser name:** all browsers

**Browser version:** /

## Server configuration

**Operating system**: Ubuntu 16.04
**Web server:** Nginx

**Database:** MySQL

**PHP version:** PHP 7.4.13 (cli)

**Nextcloud Version:** 27.1.4

**List of activated apps:**

Many apps activated. Among them **Files** and **Talk** are activated.

**Nextcloud configuration:**

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "myserver.com"
        ],
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "app_install_overwrite": [
            "radio",
            "ocsms"
        ],
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        }
    }
```

**Comment by nickvergessen** [comment] 2024-01-16 14:19
Moving to server as Talk is not handling files or reacting to encryption etc. So if there is something wrong it's a server error.

**Comment by YoannPa** [comment] 2024-01-16 22:00
> Moving to server as Talk is not handling files or reacting to encryption etc. So if there is something wrong it's a server error.

I don't understand your comment. Could you elaborate?

The issue I describe here is definitely a server-side issue. But the issue is related to the use of nextcloud tools for de-encryption of data.
Nextcloud offers the possibility to encrypt the files uploaded and shared through it.
When I share a picture through Talk (on my smartphone, or via a web browser on a PC), if I de-encrypt my user data (via command line on the server side), using nextcloud de-encryption tool, the shared files are not shared anymore in conversations.
None of the files are moved. None of the file are deleted. The files are still here, in nextcloud data, in the user folders. But they are not shared in conversations anymore.

The shared files are replaced by this, after de-encryption:
![Screenshot from 2024-01-16 22-56-46](https://github.com/nextcloud/server/assets/12813932/96e29b83-560b-4235-98ff-f59cee5ad987)

These were shared pictures. And the pictures are still available (I can just reshare them from my nextcloud Talk/ folder).

And this issue affects only files that are not voice recording file. Voice records are still shared after de-encryption.

**Comment by joshtrichards** [comment] 2024-01-17 19:48
> The shared file did not disappear. They are still accessible from the Files app in the Talk/ folder.

If I understand the situation correctly, I think this is basically expected behavior. When encrypting all your files for the very first time, existing shares change[1] and need to be re-shared. When decrypting, I'd expect similar behavior, for essentially the same reasons. It would require a much deeper dive to confirm with certainty (and at the moment there are some higher priority areas of encryption so I'm not volunteering to get into this anytime soon). Intuitively though it makes sense to me so I'll go out on a limb and say "it's expected behavior". Fortunately manually encrypting/decrypting all files is generally a one-off (rare) activity.

> I don't understand your comment. Could you elaborate?

Your issue (report) was just transferred to a different code repository since it's likely more about how `server` or the `encryption` app handles sharing in Nextcloud versus `spreed` (Talk).

[1] https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html#sharing-encrypted-files

**Comment by YoannPa** [comment] 2024-01-17 21:20
> > The shared file did not disappear. They are still accessible from the Files app in the Talk/ folder.
> 
> If I understand the situation correctly, I think this is basically expected behavior. When encrypting all your files for the very first time, existing shares change[1] and need to be re-shared. When decrypting, I'd expect similar behavior, for essentially the same reasons. It would require a much deeper dive to confirm with certainty (and at the moment there are some higher priority areas of encryption so I'm not volunteering to get into this anytime soon). Intuitively though it makes sense to me so I'll go out on a limb and say "it's expected behavior". Fortunately manually encrypting/decrypting all files is generally a one-off (rare) activity.
> 
> > I don't understand your comment. Could you elaborate?
> 
> Your issue (report) was just transferred to a different code repository since it's likely more about how `server` or the `encryption` app handles sharing in Nextcloud versus `spreed` (Talk).
> 
> [1] https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html#sharing-encrypted-files

Thank you for the explanation! Yes then, it could definitely be improved.

**Closed** 2024-01-17 21:26 UTC
Labels: enhancement, feature: encryption (server-side), 0. Needs triage, 27-feedback
