### ISSUE TITLE
[Bug]: App page states all apps are up-to-date but there are updates [NC24RC1]

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#32103] opened 2022-04-23 10:18 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I go on the app page, and see this:

![grafik](https://user-images.githubusercontent.com/8111200/164890245-adfd053e-45d1-4670-984d-07817df145a2.png)

### Steps to reproduce

1. Install the NC24RC1 version, update everything
2. wait for app update
3. go on app page

### Expected behavior

It shouldn't say that all apps are up-to-date since there is obviously an update.

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bookmarks: 10.3.1
  - calendar: 3.2.2
  - checksum: 1.1.3
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.0
  - contactsinteraction: 1.5.0
  - cospend: 1.4.6
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.0-beta.1
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_automatedtagging: 1.14.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - gpxpod: 4.3.0
  - integration_discourse: 1.0.2
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mediadc: 0.1.9
  - news: 18.0.1-beta3
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.6.0-beta1
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.3.0-alpha.1
  - updatenotification: 1.14.0
  - user_external: 3.0.0-beta1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
tail on the nextcloud log didn't generate new entries when calling the page.
```

**Comment by tflidd** [comment] 2022-04-25 07:19
It works correctly on a 22.2.6 setup on the same server. Fewer apps are installed:
```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - announcementcenter: 6.1.1
  - apporder: 0.15.0
  - audioplayer: 3.3.0
  - bookmarks: 10.2.1
  - calendar: 3.2.2
  - camerarawpreviews: 0.7.15
  - checksum: 1.1.3
  - circles: 22.3.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.1.0
  - contactsinteraction: 1.3.0
  - dav: 1.20.0
  - deck: 1.5.6
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_automatedtagging: 1.12.0
  - files_external: 1.13.1
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.4.0
  - gpxpod: 4.3.0
  - lookup_server_connector: 1.10.0
  - news: 18.0.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.5.4
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.4
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.4
  - text: 3.3.1
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
```

**Comment by szaimen** [comment] 2022-04-25 08:03
duplicate of https://github.com/nextcloud/server/issues/31915

**Closed by szaimen** 2022-04-25 08:03 UTC
Labels: bug, 0. Needs triage, 24-feedback
