### ISSUE TITLE
User group  membership Drop Down

### ISSUE THREAD

**Issue by benmprojects** [nextcloud/server#40031] opened 2023-08-21 00:10 UTC
### Steps to reproduce
1. Create more than 21 user groups
2. Add a new Blocked flow
3. Try to add a group membership, you will notice not all are there

### Expected behaviour
All user groups should be searchable

### Actual behaviour
You wont be able to see more than 21 groups in the drop down

**Comment by joshtrichards** [comment] 2023-09-15 15:55
Duplicate of #39179

**Closed by joshtrichards** 2023-09-15 15:55 UTC
Labels: bug, 1. to develop, feature: workflows, feature: users and groups, 26-feedback
