### ISSUE TITLE
Config.php empty after admin account creation (NFS mounted directory)

### ISSUE THREAD

**Issue by michele-segata** [nextcloud/server#3840] opened 2017-03-14 10:10 UTC
### Steps to reproduce
1. Install nextcloud on an NFS mounted folder
2. Setup autoconfig.php and config.php as required
3. Open the index page and create the admin account

### Expected behaviour
Nextcloud should write the config.php file and log in with the admin user

### Actual behaviour
The config.php file is empty and nextcloud returns to the setup wizard for creating the admin account

### Server configuration
**Operating system**: Debian stable (container with nextcloud), Ubuntu 16.04 (host)

**Web server:** Apache2

**Database:** MySQL (MariaDB)

**PHP version:** 7.0

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Downloaded from the official website

**Signing status:** NA

**List of activated apps:** NA

**The content of config/config.php:** NA

**Are you using external storage, if yes which one:** NFS

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox and Chrome

**Operating system:** Ubuntu 16.04 and Mac OS X Yosemite

We created a docker container running nextcloud which mounts the configuration folder as an external volume. On container startup this volume is mapped to an NFS-mounted directory. At nextcloud startup, the browser prompts for admin username and password, as expected. However, when clicking on `Finish setup` the browser brings us back to the admin account creation page, and the file `config.php` is empty. By doing some testing, we discovered that the issue is related to file locking and NFS, i.e., if we disable lines 247..249 and 255 in `lib/private/Config.php` (lock acquire and release) the admin account setup wizard works as expected, and `config.php` is correctly written. By googling around, file locking seems a well-known problem of NFS and PHP, but we thought it is important to advertise this problem in case this happens to other users.

Anybody else having this problem and knowing a solution?

**Comment by kgw4it** [comment] 2018-05-23 19:00
I'm having the same issue - I wasn't able to find a solution for that yet besides putting the config into a local volume and copying the config into the nfs mount (to back it up) from time to time.

very annyoing -.-

**Comment by skjnldsv** [comment] 2020-08-20 08:07
Works fine for me :shrug: 
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-20 08:07 UTC
Labels: 0. Needs triage, bug, feature: install and update, help wanted, low
