### ISSUE TITLE
2FA screen on color change from Theming App

### ISSUE THREAD

**Issue by probastaller** [nextcloud/server#19456] opened 2020-02-13 11:11 UTC
### Steps to reproduce
1. Activate two factor authentication
2. On theming settings change color to D7B15F
3. Log out and back in.

### Expected behaviour
After inputting user and password it should get you to the two factor authentication screen witch displays the options available with some description text and icons.
Could be Nextcloud app notification or TOTP for example.

### Actual behaviour
After inputting user and password and getting to the 2FA screen. It is inside a white box with white background in the middle of the screen keeping the rest of the screen in the selected color on the theming app and the problem is the description text and icons are white as well so you cant see them or read all of the indications.

### Server configuration

**Operating system:**
Ubuntu 18.04.4 LTS
**Web server:**
Apache
**Database:**
PostgreSQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
17.0.* 18.0 and 18.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Tested with updated and fresh installations.
**Where did you install Nextcloud from:**
From nextcloud app and with hanssonit script

**Comment by MorrisJobke** [comment] 2020-07-06 11:15
Duplicate of #18077

**Closed by MorrisJobke** 2020-07-06 11:15 UTC
Labels: 0. Needs triage, 17-feedback, bug, feature: theming
