### ISSUE TITLE
[Bug]: Redirect to `/apps/files/files` when navigating to *Group folders* view and back

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38834] opened 2023-06-15 12:17 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I land at the wrong page when navigating to the new *Group folders* section in Files in 27 and back. It goes to `/apps/files/files` and then loads the root directory.

I think there is even a full page reload.

### Steps to reproduce

1. Open your favorite directory in Nextcloud Files
2. Click *Group folders* in the left sidebar
4. Navigate back

### Expected behavior

I'm back at my favorite directory.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment] 2023-06-15 12:23
Cc @skjnldsv

**Comment by JeaNugroho** [comment] 2023-06-27 02:08
@ChristophWurst 

When you mention "favorite directory", you meant the "favorites" tab as pointed in the following screenshot, correct?
![Screen Shot 2023-06-26 at 9 02 42 PM](https://github.com/nextcloud/server/assets/35510082/631d3dad-49d2-45e6-ac29-9dc1c3407e99)

And when you mention "Group folders", I don't see any tab on the left that says that. What counts as "Group folders", or how do I make one?

**Comment by lookup82** [comment] 2023-10-09 09:04
I confirm the issue. I am using Nextcloud Hub 6 (27.1.2) with PHP 8.1.12 and MySQL 10.8.6.
When I click on the "Favorites > MyFolder" option in the left menu, the correct "MyFolder" is loaded successfully.
However, if I click on "Favorites" and then select "MyFolder" in the right panel, the correct folder is initially loaded, but suddenly it exits and brings me back to the root folder. Sometimes, there is also a page reload.

**Comment by skjnldsv** [comment] 2024-07-31 16:37
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-07-31 16:37 UTC
Labels: bug, 1. to develop, feature: files, regression, 27-feedback
