### ISSUE TITLE
CalDAV: Can't add event if it contains VALERT with attached sound

### ISSUE THREAD

**Issue by igorr-stc** [nextcloud/server#12719] opened 2018-11-29 06:23 UTC
Event like this:
```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Moscow
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
TZNAME:MSK
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20181018T142255Z
LAST-MODIFIED:20181102T180327Z
DTSTAMP:20181029T081101Z
UID:A848C048-EECA-4912-9649-43FBFEB3DA2B
SUMMARY:DM HD
RECURRENCE-ID;TZID=Europe/Moscow:20181108T111500
ORGANIZER;CN=XXX XXX:xxx@xxx.com
ATTENDEE;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUAL;EMAIL=xxv@x
xxx.com;SCHEDULE-STATUS=1.2:xxv@xxx.com
ATTENDEE;CN=XXX XXX;PARTSTAT=ACCEPTED;CUTYPE=INDIVIDUAL;ROLE=CHAIR;EMA
IL=xxx@xxx.com:xxx@xxx.com
ATTENDEE;RSVP=TRUE;CN=X1 X1;PARTSTAT=NEEDS-ACTION;CU
TYPE=INDIVIDUAL;EMAIL=x1@xxx.com;SCHEDULE-STATUS=1.2:x1@xxx.com
DTSTART;TZID=Europe/Moscow:20181108T111500
DTEND;TZID=Europe/Moscow:20181108T113000
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
LOCATION:416
SEQUENCE:0
BEGIN:VALARM
ACTION:NONE
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
X-WR-ALARMUID:75CC54B8-3490-4730-9D3E-B33EA959F71C
UID:75CC54B8-3490-4730-9D3E-B33EA959F71C
X-APPLE-DEFAULT-ALARM:TRUE
END:VALARM
BEGIN:VALARM
ACTION:AUDIO
TRIGGER;VALUE=DURATION:-PT5M
ATTACH;VALUE=URI:Chord
X-WR-ALARMUID:37885BCC-9564-483D-B172-2EDF911A065F
UID:37885BCC-9564-483D-B172-2EDF911A065F
ATTACH;VALUE=URI:Chord
END:VALARM
END:VEVENT
END:VCALENDAR
```
cannot be imported to nextCloud calendar. If I try import it using Thunderbird, then I get 
```
192.168.x.x - xxx [29/Nov/2018:08:53:05 +0300] "PUT /remote.php/dav/calendars/igorr/personal/A848C048-EECA-4912-9649-43FBFEB3DA2B.ics HTTP/1.1" 415 294
```
in server log.
If I try import it via web-interface, then I get error message 
```
r.ics | File could not be parsed
```

If I remove `ATTACH;VALUE=URI:Chord` then file can be imported.

### Steps to reproduce
1. Try to import event with VALERT which contains `ATTACH;VALUE=URI:Chord`
2. Receive error message in web interface or Thunderbird.

### Expected behaviour
Event should be imported. All unknown properties should be ignored.

### Actual behaviour
Error message in server log or error message in web interface.

### Server configuration

**Operating system**: FreeBSD 11.2-RELEASE-p4

**Web server:** apache24-2.4.37

**Database:** mariadb103-server-10.3.10_1

**PHP version:** php72-7.2.11

**Nextcloud version:** nextcloud-php72-14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** OC->NC11->NC13->NC14

**Where did you install Nextcloud from:** FreeBSD ports 

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.7
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - richdocuments: 3.0.5
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - gallery
  - spreed
  - survey_client
  - updatenotification
  - user_external

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "14.0.3.0",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "ru",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": true,
        "lost_password_link": "disabled",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***V/",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "proxy": "",
        "proxyuserpwd": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto",
        "appcodechecker": true,
        "updatechecker": false,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "check_data_directory_permissions": true,
        "config_is_read_only": false,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 2,
        "syslog_tag": "nextcloud",
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Moscow",
        "log_query": false,
        "log_rotate_size": false,
        "customclient_desktop": "https:\/\/nextcloud.com\/install\/#install-clients",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.nextcloud.client",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/nextcloud\/id1125420102?mt=8",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps-pkg",
                "url": "\/apps-pkg",
                "writable": false
            }
        ],
        "enable_previews": true,
        "preview_max_x": 4096,
        "preview_max_y": 4096,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "ldapUserCleanupInterval": 51,
        "sort_groups_by_name": false,
        "comments.managerFactory": "\\OC\\Comments\\ManagerFactory",
        "systemtags.managerFactory": "\\OC\\SystemTag\\ManagerFactory",
        "mail_template_class": "\\OC\\Mail\\EMailTemplate",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        },
        "cache_path": "",
        "cache_chunk_gc_ttl": 86400,
        "mysql.utf8mb4": false,
        "tempdirectory": "\/data\/tmp",
        "hashingCost": 10,
        "blacklisted_files": [
            ".htaccess"
        ],
        "share_folder": "\/",
        "theme": "",
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "2.0.0",
        "quota_include_external_storage": false,
        "filesystem_check_changes": 0,
        "part_file_in_storage": true,
        "mount_file": "\/usr\/local\/www\/nextcloud\/data\/mount.json",
        "filesystem_cache_readonly": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "max_filesize_animated_gifs_public_sharing": 5,
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.debug": false,
        "upgrade.disable-web": true,
        "debug": false,
        "data-fingerprint": "",
        "gs.enabled": false,
        "gs.federation": "internal",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------+
| Configuration                 | s01                                                         |
+-------------------------------+-------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                             |
| hasPagedResultSupport         |                                                             |
| homeFolderNamingRule          |                                                             |
| lastJpegPhotoLookup           | 0                                                           |
| ldapAgentName                 |                                                             |
| ldapAgentPassword             | ***                                                         |
| ldapAttributesForGroupSearch  |                                                             |
| ldapAttributesForUserSearch   | DisplayName;sAMAccountName                                  |
| ldapBackupHost                | ldap-proxy2.stc                                             |
| ldapBackupPort                | 389                                                         |
| ldapBase                      | cn=users,dc=speechpro,dc=com                                |
| ldapBaseGroups                | cn=users,***REMOVED SENSITIVE VALUE***                                |
| ldapBaseUsers                 | cn=users,dc=***REMOVED SENSITIVE VALUE***                                |
| ldapCacheTTL                  | 1800                                                        |
| ldapConfigurationActive       | 1                                                           |
| ldapDefaultPPolicyDN          |                                                             |
| ldapDynamicGroupMemberURL     |                                                             |
| ldapEmailAttribute            | mail                                                        |
| ldapExperiencedAdmin          | 1                                                           |
| ldapExpertUUIDGroupAttr       |                                                             |
| ldapExpertUUIDUserAttr        |                                                             |
| ldapExpertUsernameAttr        | sAMAccountName                                              |
| ldapGidNumber                 | gidNumber                                                   |
| ldapGroupDisplayName          | cn                                                          |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=Domain Users)(cn=stc-users))) |
| ldapGroupFilterGroups         | users                                                       |
| ldapGroupFilterMode           | 1                                                           |
| ldapGroupFilterObjectclass    | posixGroup                                                  |
| ldapGroupMemberAssocAttr      | member                                                      |
| ldapHost                      | ldap-proxy.stc                                              |
| ldapIgnoreNamingRules         |                                                             |
| ldapLoginFilter               | (&(|(objectclass=person))(sAMAccountName=%uid))             |
| ldapLoginFilterAttributes     |                                                             |
| ldapLoginFilterEmail          | 0                                                           |
| ldapLoginFilterMode           | 1                                                           |
| ldapLoginFilterUsername       | 1                                                           |
| ldapNestedGroups              | 0                                                           |
| ldapOverrideMainServer        | 0                                                           |
| ldapPagingSize                | 0                                                           |
| ldapPort                      | 389                                                         |
| ldapQuotaAttribute            |                                                             |
| ldapQuotaDefault              |                                                             |
| ldapTLS                       | 0                                                           |
| ldapUserAvatarRule            | default                                                     |
| ldapUserDisplayName           | displayname                                                 |
| ldapUserDisplayName2          |                                                             |
| ldapUserFilter                | (|(objectclass=person))                                     |
| ldapUserFilterGroups          |                                                             |
| ldapUserFilterMode            | 1                                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                                               |
| ldapUuidGroupAttribute        | auto                                                        |
| ldapUuidUserAttribute         | auto                                                        |
| turnOffCertCheck              | 0                                                           |
| turnOnPasswordChange          | 0                                                           |
| useMemberOfToDetectMembership | 1                                                           |
+-------------------------------+-------------------------------------------------------------+

```
</details>

### Client configuration
**Browser:**
Any

**Operating system:**
Any 

#### Web server error log
<details>
<summary>Web server error log</summary>

```
192.168.x.x - xxx  [29/Nov/2018:09:05:57 +0300] "PUT /remote.php/dav/calendars/igorr/personal/A848C048-EECA-4912-9649-43FBFEB3DA2B.ics HTTP/1.1" 415 294
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
None relevant to issue
```
</details>

**Comment by ChristophWurst** [comment] 2018-11-29 22:03
cc @georgehrke

**Comment by georgehrke** [comment] 2018-11-29 22:12
If the server throws an UnsupportedMediaType Exception, there must be a log-entry in Nextcloud.log

Please check

**Comment by georgehrke** [comment] 2018-11-29 22:15
The error message "File could not be parsed" and the exception 415 Unsupported Media type indicates broken calendar data.

**Comment by igorr-stc** [comment] 2018-12-04 06:21
Ok. But why removing "ATTACH;VALUE=URI:Chord" magically makes data correct?
"ATTACH;VALUE=URI:Chord" is for client, and server should just ignore it.
Original event is created by Apple Calendar on Mac OS X Mojave.

**Comment by georgehrke** [comment] 2018-12-04 21:18
> Ok. But why removing "ATTACH;VALUE=URI:Chord" magically makes data correct? 

The answer is pretty easy:
```
BEGIN:VALARM
ACTION:AUDIO
TRIGGER;VALUE=DURATION:-PT5M
ATTACH;VALUE=URI:Chord
X-WR-ALARMUID:37885BCC-9564-483D-B172-2EDF911A065F
UID:37885BCC-9564-483D-B172-2EDF911A065F
ATTACH;VALUE=URI:Chord
END:VALARM
```

Quote from [RFC 5545 3.6.6](https://tools.ietf.org/html/rfc5545#section-3.6.6):
```
 When the action is "AUDIO", the alarm can also include one and
      only one "ATTACH" property, which MUST point to a sound resource,
      which is rendered when the alarm is triggered.
```

The calendar data contains two `ATTACH` properties, which violates the calendar standard.

Please report this bug to the software that created the ics data.
You said it was created by Apple Calendar, but the product id in the calendar data indicates Mozilla Thunderbird Lightning. Did you update the events reminder in Lightning?

I'm closing this issue, because the calendar data is invalid and this error is properly caught.

**Closed by georgehrke** 2018-12-04 21:18 UTC
Labels: 0. Needs triage, bug, needs info

**Comment by igorr-stc** [comment] 2018-12-06 11:32
@georgehrke : this property is for CLIENT, and it points to sound resource. Local for client.
Server should just ignore this property. Server could not enforce alarm anyway. So it needs only to return calendar data to client.

**Comment by georgehrke** [comment] 2018-12-06 12:20
@igorr-stc Sabre/DAV, the CalDAV server used by Nextcloud, is validating addressbook and calendar-data before saving it. This is a precaution made not to serve broken calendar-data to any client. 

If a `VALARM` component with the `ACTION` property set to `AUDIO` contains more than one `ATTACH` property, it is invalid. This is not a bug in Nextcloud but a bug in the software that generated the ics in question. Please report a bug to them.

**Comment by igorr-stc** [comment] 2018-12-07 05:31
@georgehrke : Ok, I have tried to reproduce bug again. The problem is definitely in Thunderbird. Because I can import original ics file via Apple Calendar and via nextCloud web interface. But when I try import it via Thunderbird I get error. 
Thank you.
