### ISSUE TITLE
[Bug]: Web File Upload buggy/not resilient on bigger files (Firefox)

### ISSUE THREAD

**Issue by domdorn** [nextcloud/server#44113] opened 2024-03-10 19:56 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The Web File Uploader is buggy/not resilient enough when uploading larger files (e.g. a 800mb file). Random chunks might fail to upload on the browser side and are not retried. 

Also there seems to be a timing issue which deletes upload directories before the file upload is actually complete. The Move command also seems to be missing. 

Here the first chunk fails, but the file upload continues. The Chunk is never retried:
![grafik](https://github.com/nextcloud/server/assets/100349/e741483b-fdbe-4d1a-9c7a-220d6cbb52a2)
Here we can then see a timing issue where the web upload client deletes the upload directory before the file upload is finished:
![grafik](https://github.com/nextcloud/server/assets/100349/e8326f56-aff0-46e3-8e01-f751c96aee11)

Another try on uploading the same file, here a random later chunk failed, no retry is done. The Move command is not sent but the upload directory is deleted in the end. No error message was displayed in the browser
![grafik](https://github.com/nextcloud/server/assets/100349/63796677-873b-4cdb-9fde-9151c98619f6)

These are the log messages in the web developer console. Apparently the code sees that a chunk failed to upload, but does not retry to upload it. 
![grafik](https://github.com/nextcloud/server/assets/100349/b9fe6e84-00c5-43d0-bf33-bcff9c2f7808)

The NS ERROR NET INTERRUPT seems to be a bug in firefox related to http2/http3 ( https://stackoverflow.com/a/76873402/979507 ) . I will disable http2/http3 in the meantime. While this issue might be related to the bug in firefox, it highlights the underlying issue that the web uploader is not retrying to upload a chunk if it failed for some reason. 

### Steps to reproduce

0. either front nextcloud with a http/2 proxy (e.g. nginx) or enable http/2 in apache
1. Create a folder, e.g. "Test"
2. Drag a larger file (e.g. 800mb) from Finder (I'm on Mac) to the browser (Firefox 123.0.1 (64-Bit))
3. A random chunk might not get uploaded, upload finishes without a error message

### Expected behavior

1. File upload of large files works. 
2. If a chunk is not uploaded, it gets retried at least once. 
3. A success or error message is displayed when the file upload finishes
4. if you decide that retry is not to be implemented, the whole upload should immediately stop if a chunk fails, as there is no point in uploading more chunks. 

### Installation method

Community Docker image

### Nextcloud Server version

28.0.3

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logtimezone": "UTC",
        "loglevel": 1,
        "default_phone_region": "DE",
        "forcessl": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "skeletondirectory": "\/var\/www\/skeleton",
        "language": "de",
        "default_language": "de",
        "default_locale": "de_DE",
        "force_language": "de"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - announcementcenter: 6.8.0
  - calendar: 4.6.6
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - event_update_notification: 2.3.0
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - forms: 4.1.1
  - group_everyone: 0.1.14
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - welcome: 1.0.10
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.18.0)
  - files_external: 1.20.0
  - firstrunwizard: 2.17.0 (installed 2.17.0)
  - nextcloud_announcements: 1.17.0 (installed 1.17.0)
  - polls: 6.1.6 (installed 6.1.6)
  - recommendations: 2.0.0 (installed 2.0.0)
  - support: 1.11.0 (installed 1.11.0)
  - survey_client: 1.16.0 (installed 1.16.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0 (installed 1.18.0)
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.8.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
nextcloud.log is 20mb big, too big for this issue. is there another way to share?
```

### Additional info

I'm fronting the nextcloud installation with nginx on docker:

```
version: "2"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/data/nginx/conf.d:/etc/nginx/conf.d"
      - "./configs/cloud.redacted.de:/etc/nginx/vhost.d/cloud.redacted.de"
      - "/data/nginx/vhost.d:/etc/nginx/vhost.d"
      - "/data/nginx/html:/usr/share/nginx/html"
      - "/data/nginx/certs:/etc/nginx/certs:ro"
      - "./htpasswd:/etc/nginx/htpasswd"
    networks:
      - nginx-front
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    mem_limit: 512m
    restart: always
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - "/data/nginx/conf.d:/etc/nginx/conf.d"
      - "/data/nginx/vhost.d:/etc/nginx/vhost.d"
      - "/data/nginx/html:/usr/share/nginx/html"
      - "/data/nginx/certs:/etc/nginx/certs:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: always
    mem_limit: 192m
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/data/nginx/certs:/etc/nginx/certs:rw"
      - "/data/nginx/html:/usr/share/nginx/html"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
```
      
 with this custom config for the hostname in question:
 ```
 ## Start of configuration add by letsencrypt container
location ^~ /.well-known/acme-challenge/ {
    auth_basic off;
    auth_request off;
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
client_max_body_size 4g;
```

**Comment by susnux** [comment] 2024-03-11 15:26
Probably duplicate of https://github.com/nextcloud-libraries/nextcloud-upload/issues/5

**Comment by tstreibl** [comment] 2024-04-07 22:06
I probably have the same problem using traefik as reverse proxy for the nextcloud docker community version (Nextloud 28.0.4, apache) 

Can't upload 1Gb file with firefox as web-frontend. Chrome works, Nextcloud desktop client works. Android: Nextcloud App and Webbrowser gets stuck at 1% without any error; 

See good summary pointing to http/2 problems: https://help.nextcloud.com/t/problems-when-upload-with-http-2-with-firefox/163810

Log File says:

"BadRequest Erwartete Dateigröße von 40960000 bytes, aber 688128 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein."

Tried all suggestions i found in the forums concerning this bug. 
-setting temp dir correctly and making sure it's not full
-setting environment in docker compose correctly:
PHP_UPLOAD_LIMIT: 100G
PHP_MEMORY_LIMIT: 100G
POST_MAX_SIZE: 100G
MAX_INPUT_TIME: 3600
MAX_EXECUTION_TIME: 3600
APACHE_BODY_LIMIT: 0
- setting LimitRequestBody 0 (which APACHE_BODY_LIMIT does already)

Nothing works for me. 

Never had a problem with big files in earlier nextcloud versions. 

Full Log:
`{"reqId":"6qdfk5LQRndTzzfzFEJn","level":3,"time":"2024-04-07T21:46:45+00:00","remoteAddr":"172.18.0.2","user":"tstreibl","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/tstreibl/5fbe86a574b73438a5766e5c5fcae297/000001","message":"Erwartete Dateigröße von 40960000 bytes, aber 11313152 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.","userAgent":"Mozilla/5.0 (Android) Nextcloud-andro-id/3.28.1","version":"28.0.4.1","exception":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"Erwartete Dateigröße von 40960000 bytes, aber 11313152 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.","Code":0,"Trace":[{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directo-ry.php","line":148,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Upload/UploadFolder.php","line":51,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":373,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":172,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","Line":301,"message":"Erwartete Dateigröße von 40960000 bytes, aber 11313152 bytes gelesen (vom Nextcloud-Client) und ge-schrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.","exception":[],"CustomMessage":"Erwartete Dateigröße von 40960000 bytes, aber 11313152 bytes gelesen (vom Nextcloud-Client) und geschrie-ben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serversei-te sein."},"id":"661316babef9e"}`

**Comment by tstreibl** [comment] 2024-04-20 13:33
seems like this gets fixed in https://github.com/nextcloud/server/issues/43627 ?

**Comment by susnux** [comment] 2024-04-20 15:25
> seems like this gets fixed in #43627 ?

Not fully, failed chunks are still not retried

**Comment by tstreibl** [comment] 2024-05-11 14:51
In my case the probles came from traefik in the 2.11.1 version (so it's not related to this issue because here it seems ngnix is used - sorry for interfering). I downgraded traefik to 2.10.7 and now everything works fine. Before I couldn't upload files greater approx. 50MB. Only the Nextcloud PC Client could do because it failed, and recovered in several iterations until the upload was done... (no retry for failed chuncs from browser upload). Uploaded 8GB this was. Traefik seems to play around with this (not helpful) fix: https://github.com/traefik/traefik/pull/10599. Welcome in configuration hell: https://github.com/traefik/traefik/wiki/respondingTimeouts-for-applications. All this goes beyond by skills. I was not able to configure the latest traefik version to work correctly wih nextcloud. Never had a problem the last 5 years with traefik...

**Comment by skjnldsv** [comment] 2024-05-29 16:22
> Probably duplicate of [nextcloud-libraries/nextcloud-upload#5](https://github.com/nextcloud-libraries/nextcloud-upload/issues/5)

Yes, I agree, let's close this one then :)

**Closed by skjnldsv** 2024-05-29 16:22 UTC
Labels: bug, 0. Needs triage, feature: files, 28-feedback

**Comment by bugsyb** [comment] 2024-07-30 21:14
Could this be the same I did run into? 
Might be related to maybe readTimeout on Traefik, though it would be more likely in case of migration to v3. I've run into this and setting appropriately (or disabling) readTimeout sorted issue.
See this https://github.com/nextcloud/server/issues/37695#issuecomment-2259203772 for example entry for Traefik to fix it, if this is indeed timeout issue - check your logs.
