### ISSUE TITLE
[Bug]: Cannot update apps since version 25 (confirm button issue)

### ISSUE THREAD

**Issue by GuibertLo** [nextcloud/server#34850] opened 2022-10-27 12:29 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since my instance being updated to version 25, I am unable to update any App using the web UI. It gives me continusly generated errors in the browser console (please see additional info section) and an alert message on the UI ("An error occurred during the request. Unable to proceed.").

Updating apps with the occ command does work.

Cheers

Note: for the "Nextcloud Server Encryption module" question, I do not know whether it concerns the home storage encryption or the server-side encryption. My instance only has the first one of activated.

### Steps to reproduce

1. Open the "Apps" page
2. Click on a button to update apps (both "Update all" than individual buttons)
3. Entering admin password when prompted ("Confirm" button stays disactivated)

### Expected behavior

After the steps, the "Confirm" button should be clickable to launch the update process.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": "true",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "app_install_overwrite": [
            "files_external_onedrive",
            "news"
        ],
        "default_phone_region": "CH",
        "mail_sendmailmode": "pipe",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0
  - encryption: 2.13.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.17.0
  - news: 19.0.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - apporder: 0.15.0
  - bruteforcesettings
  - suspicious_login
  - theming: 1.11.0
  - twofactor_totp: 6.3.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"OzwTVSniMOIkWmpbwRmU","level":0,"time":"2022-10-27T12:27:36+00:00","remoteAddr":"194.66.200.1","user":"loic","app":"metadata","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Linux) mirall/3.6.0git (Nextcloud, fedora-5.19.16-200.fc36.x86_64 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.0.18","data":{"app":"metadata"}}
{"reqId":"A1gPArR8OZGZ07bY5vja","level":0,"time":"2022-10-27T12:27:42+00:00","remoteAddr":"194.66.200.1","user":"loic","app":"encryption","method":"GET","url":"/ocs/v2.php/core/navigation/apps?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:106.0) Gecko/20100101 Firefox/106.0","version":"25.0.0.18","data":{"app":"encryption"}}
{"reqId":"A1gPArR8OZGZ07bY5vja","level":0,"time":"2022-10-27T12:27:42+00:00","remoteAddr":"194.66.200.1","user":"loic","app":"metadata","method":"GET","url":"/ocs/v2.php/core/navigation/apps?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:106.0) Gecko/20100101 Firefox/106.0","version":"25.0.0.18","data":{"app":"metadata"}}
{"reqId":"KnXmh2JeWYsqquCysJLC","level":0,"time":"2022-10-27T12:27:42+00:00","remoteAddr":"194.66.200.1","user":"loic","app":"encryption","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:106.0) Gecko/20100101 Firefox/106.0","version":"25.0.0.18","data":{"app":"encryption"}}
{"reqId":"KnXmh2JeWYsqquCysJLC","level":0,"time":"2022-10-27T12:27:42+00:00","remoteAddr":"194.66.200.1","user":"loic","app":"metadata","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:106.0) Gecko/20100101 Firefox/106.0","version":"25.0.0.18","data":{"app":"metadata"}}
```

### Additional info

```
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
JQMIGRATE: Migrate is installed, version 3.4.0 jquery-migrate.min.js:2:698
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:60:15
Proxying an event bus of version 2.1.1 with 3.0.2 ProxyBus.ts:16:20
Proxying an event bus of version 2.1.1 with 3.0.2 ProxyBus.ts:16:20
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:60:15
Registering notifications container as a menu NotificationsApp.vue:217
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:60:15
Notifications permissions granted NotificationsApp.vue:442
Polling interval updated to 30000 NotificationsApp.vue:402
Started background fetcher as session_keepalive is enabled NotificationsApp.vue:264
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
Proxying an event bus of version 2.1.1 with 3.0.0 index.js:19:12
Proxying an event bus of version 2.1.1 with 1.3.0 index.es.js:2337:14
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:60:15
Proxying an event bus of version 2.1.1 with 3.0.2 main.js:19:20239
Proxying an event bus of version 2.1.1 with 1.3.0 main.js:6029:18037
session heartbeat polling started session-heartbeat.js:103:9
Proxying an event bus of version 2.1.1 with 3.0.0 index.js:19:12
[INFO] AppContent: falling back to global nextcloud pane config NcAppContent.js:2:108577
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:52:10
Got notification data NotificationsApp.vue:365
Polling interval updated to 30000 NotificationsApp.vue:402
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:60:15
TypeError: document.querySelector(...) is null
    mounted main.js:6120
    Ut main.js:7
    Nn main.js:7
    insert main.js:7
    E main.js:15
    dr main.js:15
    _update main.js:7
    a main.js:7
    get main.js:7
    e main.js:7
    mount main.js:7
    $mount main.js:7
    confirmPassword main.js:15966
    b api.js:69
    updateApp apps.js:287
    g vuex.esm.js:736
    dispatch vuex.esm.js:490
    dispatch vuex.esm.js:393
    updateAll AppList.vue:240
    e index.js:19
    u runtime.js:286
    _invoke runtime.js:262
    F runtime.js:83
    g index.js:59
    o index.js:15
    b index.js:15
    b index.js:15
    e index.js:22
    u runtime.js:286
    _invoke runtime.js:262
    F runtime.js:83
    g index.js:59
    o index.js:15
    b index.js:15
    b index.js:15
    a index.js:22
    a index.js:19
    u runtime.js:286
    _invoke runtime.js:262
    F runtime.js:83
    g index.js:59
    o index.js:15
main.js:7:2103
    Ht main.js:7
    Gt main.js:7
    Wt main.js:7
    Ut main.js:7
    Nn main.js:7
    insert main.js:7
    E main.js:15
    dr main.js:15
    _update main.js:7
    a main.js:7
    get main.js:7
    e main.js:7
    mount main.js:7
    $mount main.js:7
    confirmPassword main.js:15966
    b api.js:69
    updateApp apps.js:287
    g vuex.esm.js:736
    dispatch vuex.esm.js:490
    dispatch vuex.esm.js:393
    updateAll AppList.vue:240
    e index.js:19
    u runtime.js:286
    _invoke runtime.js:262
    F runtime.js:83
    g index.js:59
    o index.js:15
    b index.js:15
    b index.js:15
    e index.js:22
    u runtime.js:286
    _invoke runtime.js:262
    F runtime.js:83
    g index.js:59
    o index.js:15
    b index.js:15
    b index.js:15
    a index.js:22
    a index.js:19
    u runtime.js:286
    _invoke runtime.js:262
    F runtime.js:83
    g index.js:59
    o index.js:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 136 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 52 globals.js:60:15
Request for font "Roboto Mono" blocked at visibility level 1 (requires 3)
utils.js:100:47
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 52 globals.js:60:15
```

**Comment by bentolor** [comment] 2022-10-28 10:27
Same here: Since v25 i cannot use my logged-in admin account to update apps. The "confirm" button is disabled on the password-window.

![image](https://user-images.githubusercontent.com/588260/198566088-dec5a731-ed57-4cca-9288-f0dc33abb024.png)


One workaround is to logout and relogin, so that the confirmation dialog does not appear at all.

**Comment by GuibertLo** [comment] 2022-10-28 11:21
> Same here: Since v25 i cannot use my logged-in admin account to update apps. The "confirm" button is disabled on the password-window.
> 
> ![image](https://user-images.githubusercontent.com/588260/198566088-dec5a731-ed57-4cca-9288-f0dc33abb024.png)
> ## Workarounds
> 
>     1. One workaround is to logout and relogin, so that the confirmation dialog does not appear at all.
> 
>     2. Another one for the lazy one is do "inspect code" and remove the `disabled="disabled"` property at the button in the HTML

Yeah, I think it truely is a web interface issue, the system does seem to work correctely without any logs.

**Comment by PVince81** [comment] 2022-10-28 12:25
duplicate of https://github.com/nextcloud/server/issues/34217

workaround is to hit the enter key

**Closed by PVince81** 2022-10-28 12:25 UTC
Labels: bug, 0. Needs triage, 25-feedback
