### ISSUE TITLE
Encryption Error while deleting folder

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#24646] opened 2020-12-10 15:18 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a folder then delete it
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Error | PHP | fread(): read of 8192 bytes failed with errno=21 Is a directory at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#861
-- | -- | --

### Server configuration

**Operating system:**
Ubunti 20.0.4
**Web server:**
Apache2
**Database:**
MariaDB 10.3.25
**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
20.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
\\

``
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>
![image](https://user-images.githubusercontent.com/59488153/85640490-89e03580-b651-11ea-9235-0b672653aa26.png)

**Comment by kesselb** [comment] 2020-12-10 16:50
Duplicate of https://github.com/nextcloud/server/issues/21578

**Closed by kesselb** 2020-12-10 16:50 UTC
Labels: 0. Needs triage, bug

**Comment by saddy001** [comment] 2020-12-19 12:18
Same here when uploading some big (25MB) png's. Then tried to share the containing folder with another user (maybe the error occured not till then but I believe not). NC 20.0.4, PHP 7.4.3, just moved from legacy encryption to the new one by changing ...legacy_enc... to false in config.php.

`Error: fread(): read of 8192 bytes failed with errno=21 Is a directory at <nc>/lib/private/Files/Storage/Wrapper/Encryption.php#862`
