### ISSUE TITLE
new releases are announced too early if you use docker

### ISSUE THREAD

**Issue by rubo77** [nextcloud/server#47373] opened 2024-08-21 07:24 UTC
New releases of Nextcloud are often announced in the web interface before they are available on Docker. This causes frustration for Docker users who see the update notification but cannot immediately update their instance via Docker.

**Describe the solution you'd like**
Nextcloud should check if it is an instance that was instaled inside docker and, if so, if  the new release is available on Docker before announcing it in the web interface.

**Describe alternatives you've considered**
An alternative could be to delay the update notification for a set period (e.g., 24 hours) after the release, allowing time for Docker images to be published.  Maybe thorough a new config variable `delay_update_notifications`

Another option could be to include a note in the update notification indicating that Docker users may need to wait until the image is available.

**Additional context**
This would help  reducing confusion and improving the user experience for Docker users by preventing unnecessary update notifications when the release is not yet accessible via Docker.

**Comment by kesselb** [comment] 2024-08-21 11:33
Duplicate of https://github.com/nextcloud/server/issues/45785

**Closed by kesselb** 2024-08-21 11:33 UTC
Labels: enhancement, 0. Needs triage
