### ISSUE TITLE
add directory location column to trashbin

### ISSUE THREAD

**Issue by zwotzie** [nextcloud/server#35611] opened 2022-12-05 17:56 UTC
### Why adding a column directory to trashbin is useful
As an owner of a larger installation (150k files, thousands of directories, several clients) and a lot of file movements and similar looking files I would like to get an easy overview of the deleted files in trashbin.

Unfortunately, it is almost impossible to trace where the deleted files come from.

For this it would be best if there was a sortable column that shows the directory 🙏.

Additional comment: same for "view=shareoverview", may for others too.

**Comment by being-peace** [comment] 2023-03-17 09:06
Duplicate of https://github.com/nextcloud/server/issues/24544.

**Closed** 2024-03-29 16:54 UTC
Labels: enhancement, 0. Needs triage, feature: files, feature: trashbin
