### ISSUE TITLE
[Bug]: when you rename a file you have to wait for the refresh to see the change

### ISSUE THREAD

**Issue by marcodefelice** [nextcloud/server#48321] opened 2024-09-24 13:47 UTC
https://github.com/user-attachments/assets/eddb4067-93f1-4b23-9f25-dd2e613c319b

### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

if you rename a file via the server interface, the file is "apparently" renamed but the interface does not update, and therefore you do not see the renamed file until you refresh the page

### Steps to reproduce

1. Rename a file

### Expected behavior

the functionality should be: when you rename a file, the view should immediately update to show the renamed file

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2024-09-24 14:30
This is fixed in my 28.0.10 or 29.0.7

**Comment by joshtrichards** [comment] 2024-09-24 14:32
Indeed. This was fixed at least maintenance releases ago. Please update your instance before reporting. :)

Duplicate of #46604

Fixed in >=28.0.9

**Closed by joshtrichards** 2024-09-24 14:32 UTC
Labels: bug, needs info, 0. Needs triage
