### ISSUE TITLE
After update to 18.0 cant access webinterface

### ISSUE THREAD

**Issue by Pixxelcrasher** [nextcloud/server#19003] opened 2020-01-19 16:37 UTC
Hello,
after I make the update to the newest version. I cant access nextcloud.. i only get this:

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

I have no logs.. only that:

{"reqId":"fn57ARYC65tpMwdeBcdb","level":3,"time":"2020-01-19T12:01:10+00:00","remoteAddr":"87.123.193.93","user":"--","app":"PHP","method":"GET","url":"/index.php/204","message":"Declaration of OCA\\FilesAutomatedTagging\\Operation::validateOperation($name, array $checks, $operation) must be compatible with OCP\\WorkflowEngine\\IOperation::validateOperation(string $name, array $checks, string $operation$

Please help...
Thanks

**Comment by Henk57** [comment] 2020-01-21 15:07
I had the same error after a manual update from 17 to 18 today.
I solved it by a manual copy of all apps that were in 127, but not in the app folder of 18. I even had to reinstall OnlyOffice. NC starts then with an update message that shows multiple apps are not supported. Then the database is corrected and the NC starts normal without 'internal server error'.
So the cause of this problem is an inconsistency.

The manual update does not work as expected and documented. Do not delete the apps folder, but first make a backup of all files and folders. Restore first all missing apps and then start NC18.

And NC 18 again does not support earlier apps that our clienst use (no third party apps!): 
- contacts
- rainloop
- occweb
- spreed (Talk)

I think we will restore NC 17. This problem occurs with every main release of NC, with 'offical apps'. We are not amused about this.

**Comment by kesselb** [comment] 2020-01-21 15:39
> Declaration of OCA\FilesAutomatedTagging\Operation::validateOperation($name, array $checks, $operation) must be compatible with OCP\WorkflowEngine\IOperation::validateOperation(string $name, array $checks, string $operation$

That means the installed version of https://apps.nextcloud.com/apps/files_automatedtagging is outdated. I guess the fastest way to fix this is to remove the files_automatedtagging folder from apps directory and install it again from the app store.

> manual update does not work as expected and documented

Could you elaborate that? Please tell us what is not clear with the docs and we can improve it.

> no third party apps!

Contacts and Spreed are official apps and have a compatible release with 18.
Rainloop and occweb are third party apps.

**Comment by Henk57** [comment] 2020-01-22 21:53
Installation:
I deleted all files in the nextcloud folder, except data and config folders.
Then I copied all files from the 18.0.0 version to the nextcloud folder (Filezilla).
Nextcloud started, I think normal, no errors. But later that day the user got the message 'internal server error' when trying to log in.
Since the apps folder was deleted and replaced by the 18.0.0 version, and no update routine was intiated, I think that was where it went wrong. The update routine was initiated after putting the missing apps in the apps folder. That part is not described in the manual update documentation. And this is the first time I came accross this. So perhaps some coding issue that should check expected apps. (Nerver had this problem with the web-based-update mechanism)

An other instance of nextcloud for an other domain did not show this issue. So it could be caused by a plugin that was active on the first site and not on the onther instance.

Differences:
On the first site the Calendar app was 2.0.0 and on the second 2.0.1 (1 update)
On the first site are contacts, deck, draw.io, extract, files_mindmap and forms where installed (not all active). These are not in the second site that had no problems.
On the second site where bruteforcesettings and camerarawpreviews in the apps folder. These are not on the first site that had problems.

I used exactly the same manual update procedure for both installations. Both are on the same server with the same security settings (httpd level) and on PHP7.3.

Perhaps this can help.
H

**Comment by Henk57** [comment] 2020-01-22 22:05
PM. I can not find a file or folder 'files_automatedtagging' in the 18.0.0 version. The are only docs in html format that have names like this.
My download is from 20-1-2020 at 01.52 and 103.764 kB size.

**Comment by Pixxelcrasher** [comment] 2020-01-22 22:07
Thanks I will try it...

**Comment by kesselb** [comment] 2020-01-22 22:42
@Henk57 and what error message do you see in nextcloud.log?

**Comment by Henk57** [comment] 2020-01-23 20:28
None. I searched in 70MB log for the ID that was shown. Perhaps this needs an other debug mode to be recorded. But this size is alreaady huge.

**Comment by skjnldsv** [comment] 2020-03-10 07:57
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-03-10 07:57 UTC
Labels: 0. Needs triage, 18-feedback, bug
