### ISSUE TITLE
[Bug]: Focus of the navigation bar switches constantly

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/server#37711] opened 2023-04-13 12:20 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The focus of the navigation bar switches constantly leading to odd flickering.

https://user-images.githubusercontent.com/26026535/231755789-ce41169e-0285-47d8-a7f9-7429b5977b06.mp4

### Steps to reproduce

1. Slowly move the mouse to the border of the navigation bar

### Expected behavior

Navigation bar should be either focused or not focused and not constantly switch between both.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
/
```

### List of activated Apps

```shell
/
```

### Nextcloud Signing status

```shell
/
```

### Nextcloud Logs

```shell
/
```

### Additional info

c.nc.c

**Comment by szaimen** [comment] 2023-04-13 12:23
Duplicate of https://github.com/nextcloud/server/issues/34591

**Closed by szaimen** 2023-04-13 12:23 UTC
Labels: bug, 0. Needs triage

**Comment by provokateurin** [comment] 2023-04-13 12:24
Oops my bad
