### ISSUE TITLE
Contacts menu: with administrator, list is empty and when searching results in no contacts found. 

### ISSUE THREAD

**Issue by hunter-nl** [nextcloud/server#9210] opened 2018-04-17 09:14 UTC
### Steps to reproduce
1. Login as user.
2. Open Contacts menu.
3. List contains visible contacts for the user and is searchable.
4. Login as administrator
5. Open Contacts menu.
6. List is empty and is not searchable.

### Expected behaviour
At step 6 all users (except disabled accounts) should be shown/searchable.

### Actual behaviour
List is empty and none is searchable/found. It only happens for administrator account which is also member of all groups.

### Server configuration

**Operating system**:
CentOS 7.4

**Web server:**
Nginx 1.13.12

**Database:**
Mysql 10.1.32

**PHP version:**
7.1.16

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded from 13.0.0

**Where did you install Nextcloud from:**
website

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - announcementcenter: 3.2.1
  - bruteforcesettings: 1.0.3
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - dav: 1.4.6
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_antivirus: 1.2.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - ransomware_protection: 1.1.0
  - richdocuments: 2.0.5
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - twofactor_u2f: 1.5.1
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - end_to_end_encryption
  - firstrunwizard
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/var\/www\/nextcloud\/tmp",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_libreoffice_path": "\/usr\/bin\/soffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "singleuser": false,
        "maintenance": false,
        "logtimezone": "Europe\/Amsterdam",
        "log_rotate_size": 104857600,
        "activity_expire_days": 30,
        "theme": "",
        "updatechecker": true,
        "appstore.experimental.enabled": true,
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 90",
        "versions_retention_obligation": "auto, 90",
        "auth.bruteforce.protection.enabled": true
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Safari
**Operating system:**
OSX

#### Web server error log
<details>
<summary>Web server error log</summary>
***empty***
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
*** no errors, No additional information added when contacts menu is used. Other info is sensitive info ***
</details>

#### Browser log
<details>
<summary>Browser log</summary>
*** No errors ***
```
</details>

**Comment by Schmuuu** [comment] 2018-04-25 14:10
Exact same issue for me. As a result the admin user doesn't see any users in the JSXC chat app.

## Server configuration

### Operating system:
Arch Linux LTS 

### Web server:
Nginx 1.14

### Database:
MariaDB 10.1.32

### PHP version:
7.2.5

### Nextcloud version: (see Nextcloud admin page)
13.0.1

**Comment by hunter-nl** [comment] 2018-07-05 06:14
Issue still exist in 13.0.4. Please reopen this issue.

**Comment by phiL0co** [comment] 2018-12-17 08:18
Hello!
The issue occured for me too, when I updated to contacts 3.0.0 on my nextcloud, version 15.
Logged in as admin no contacts are shown and I can't create new contacts.
As a regular user, everything works as intended.

Please look into this as the issue seems to be existing for quite some time.

If you need additional info please let me know!

THX a lot in advance!

**Comment by skjnldsv** [comment] 2020-09-09 11:35
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-09-09 11:35 UTC
Labels: 0. Needs triage, bug, feature: contacts menu
