### ISSUE TITLE
[Bug]: Can not set expiration date for new shared links. Date is in the past error

### ISSUE THREAD

**Issue by nook24** [nextcloud/server#43733] opened 2024-02-21 16:51 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to set an expiry date for a shared link, I always get the error: expiry date is in the past.
No matter what date I pick.

![grafik](https://github.com/nextcloud/server/assets/9019992/1219293e-5f60-4365-8986-586c710c1f78)

Nextcloud Hub 7] 28.0.2

I use Firefox on Windows if this matters.

May be relates to https://github.com/nextcloud/server/issues/43720 ?

### Steps to reproduce

1. Select a file and go to Sharing -> Share link
2. Try to set an expiration date for the shared link
3. System will error: Date is in the past

### Expected behavior

Save the Expiry Date

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Dennis1993** [comment] 2024-02-21 16:58
Hey,

Thanks for your bug report!
This is a duplicate of https://github.com/nextcloud/server/issues/43243 and will be fixed.

thanks you very much!

**Closed by Dennis1993** 2024-02-21 16:58 UTC
Labels: bug, 0. Needs triage
