### ISSUE TITLE
No access via Android app.

### ISSUE THREAD

**Issue by xpiotrekx** [nextcloud/server#1718] opened 2016-10-12 09:23 UTC
### Steps to reproduce
1. Install Nextcloud from GitHub 11.0(alpha)
2. Try to login using Android app

### Expected behaviour
Successful login. 

### Actual behaviour
In Android app is message: An unknown error occurred!

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-42-generic x86_64)

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.15

**PHP version:** PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install after removing version 10.0.1

**Where did you install Nextcloud from:** Git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.

```
</details>

**List of activated apps:**
<details>
<summary>All apps that are enabled by default</summary>
Enabled:
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_sharing: 1.1.0
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - provisioning_api: 1.1.0
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
I "system": {
        "instanceid": "ochvcq92bk9w",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xyz.eu"
        ],
        "datadirectory": "\/mnt\/BACKUP\/cloud",
        "overwrite.cli.url": "https:\/\/cloud.xyz.eu",
        "dbtype": "mysql",
        "version": "9.2.0.4",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "updater.release.channel": "production",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Debug	webdav
	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/nextcloud\/server\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/nextcloud\/server\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/nextcloud\/server\/remote.php(165): require_once('\/var\/www\/nextcl...')\n#6 {main}","File":"\/var\/www\/nextcloud\/server\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
no log file inside data folder.
```
</details>

Nextcloud in version 10.0.1 was working OK. After removing it and downloading version 11.0 (alpha)
there is no possibility to login using Android app.

**Comment by MorrisJobke** [comment] 2016-10-12 09:42
This was already discussed with @AndyScherzinger - the app doesn't work with the 11 version of Nextcloud - I guess this is https://github.com/nextcloud/android/issues/259 in the app repo.

It needs to be fixed by the app, because it misused a really old endpoint that was finally removed in 11.

**Comment by AndyScherzinger** [comment] 2016-10-12 10:07
Exactly that is (probably) the issue - The issue is this one since it needs to be fixed in the client library: https://github.com/nextcloud/android-library/issues/18 - @MorrisJobke do we have a NC11 test instance somewhere? :smiley:

**Comment by MorrisJobke** [comment] 2016-10-12 10:15
> @MorrisJobke do we have a NC11 test instance somewhere? 😃

No. Just use git clone and set it up locally 🙈 If you need help with that ping me.

I will close this here then

**Closed by MorrisJobke** 2016-10-12 10:15 UTC
