### ISSUE TITLE
 Integrity check fails for core/js/mimetypelist.js after upgrade to NC 23 

### ISSUE THREAD

**Issue by muffinmaster1024** [nextcloud/server#30732] opened 2022-01-18 10:19 UTC
See issue [#22508](https://github.com/nextcloud/server/issues/22508)

```
$ php occ integrity:check-core
  - INVALID_HASH:
    - core/js/mimetypelist.js:
      - expected: xxx
      - current: yyy
```

Happened after upgrading from 22.2.3 to 23. Where to get a correctly hashed file? Tried all of my existing backups as well as master and above mentioned branches

**Comment by feizhoulv** [comment] 2022-01-19 09:59
Encountered the same problem  today.

`Results
=======
- $
	- EXCEPTION
		- Exception
		- App not found
- previewgenerator:
	- EXCEPTION
		- Exception
		- App not found
- previewgenerator,theming
	- EXCEPTION
		- Exception
		- App not found
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
- previewgenerator
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
`

**Below is my upgrade log ：**

`$ sudo -u www-data php updater/updater.phar
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 22.2.3.

Update to Nextcloud 23.0.0 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-23.0.0.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] Y
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2022-01-19T17:23:01+08:00 Setting log level to debug
2022-01-19T17:23:01+08:00 Repair step: Repair MySQL collation
2022-01-19T17:23:01+08:00 Repair info: All tables already have the correct collation -> nothing to do
2022-01-19T17:23:01+08:00 Repair step: Repair SQLite autoincrement
2022-01-19T17:23:01+08:00 Repair step: Copy data from accounts table when migrating from ownCloud
2022-01-19T17:23:02+08:00 Repair step: Drop account terms table when migrating from ownCloud
2022-01-19T17:23:02+08:00 Updating database schema
2022-01-19T17:23:05+08:00 Updated database
2022-01-19T17:23:05+08:00 Repair step: Uninstall MindMap
2022-01-19T17:23:05+08:00 Disabled incompatible app: files_mindmap
2022-01-19T17:23:05+08:00 Updating <federation> ...
2022-01-19T17:23:05+08:00 Updated <federation> to 1.13.0
2022-01-19T17:23:05+08:00 Updating <lookup_server_connector> ...
2022-01-19T17:23:05+08:00 Updated <lookup_server_connector> to 1.11.0
2022-01-19T17:23:05+08:00 Updating <oauth2> ...
2022-01-19T17:23:05+08:00 Repair step: Update OAuth token expiration times
2022-01-19T17:23:05+08:00 Updated <oauth2> to 1.11.0
2022-01-19T17:23:05+08:00 Updating <password_policy> ...
2022-01-19T17:23:05+08:00 Updated <password_policy> to 1.13.0
2022-01-19T17:23:05+08:00 Updating <files> ...
2022-01-19T17:23:05+08:00 Updated <files> to 1.18.0
2022-01-19T17:23:05+08:00 Updating <circles> ...
2022-01-19T17:23:05+08:00 Repair step: Upgrading Circles App
2022-01-19T17:23:05+08:00 Repair info: (Circles) Migrating to 22
2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00 Upgrading Circles App
2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00  Starting ...
 0/1 [>-]   0%2022-01-19T17:23:05+08:00
 (Circles) Caching memberships for Members of 'admin'
 1/1 [============================] 100%2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00 Repair info: (Circles) Migrating to 22.1.x
2022-01-19T17:23:05+08:00 Upgrading Circles App
2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00  Starting ...
    0/0 [--->]   0%2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00 Updated <circles> to 23.0.0
2022-01-19T17:23:05+08:00 Updating <cloud_federation_api> ...
2022-01-19T17:23:05+08:00 Updated <cloud_federation_api> to 1.6.0
2022-01-19T17:23:05+08:00 Updating <dav> ...
2022-01-19T17:23:05+08:00 Repair step: Fix component of birthday calendars
2022-01-19T17:23:05+08:00 Repair info: 2 birthday calendars updated.
2022-01-19T17:23:05+08:00 Repair step: Regenerating birthday calendars to use new icons and fix old birthday events without year
2022-01-19T17:23:05+08:00 Repair info: Repair step already executed
2022-01-19T17:23:05+08:00 Repair step: Fix broken values of calendar objects
2022-01-19T17:23:05+08:00 Fix broken values of calendar objects
2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00  Starting ...
    0/0 [----->]   0%2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00 Repair step: Registering building of calendar search index as background job
2022-01-19T17:23:05+08:00 Repair info: Repair step already executed
2022-01-19T17:23:05+08:00 Repair step: Register building of social profile search index as background job
2022-01-19T17:23:05+08:00 Repair step: Registering background jobs to update cache for webcal calendars
2022-01-19T17:23:05+08:00 Repair info: Added 0 background jobs to update webcal calendars
2022-01-19T17:23:05+08:00 Repair step: Registering building of calendar reminder index as background job
2022-01-19T17:23:05+08:00 Repair info: Repair step already executed
2022-01-19T17:23:05+08:00 Repair step: Clean up orphan event and contact data
2022-01-19T17:23:05+08:00 Repair info: 0 events without a calendar have been cleaned up
2022-01-19T17:23:05+08:00 Repair info: 0 properties without an events have been cleaned up
2022-01-19T17:23:05+08:00 Repair info: 0 changes without a calendar have been cleaned up
2022-01-19T17:23:05+08:00 Repair info: 0 cached events without a calendar subscription have been cleaned up
2022-01-19T17:23:05+08:00 Repair info: 0 changes without a calendar subscription have been cleaned up
2022-01-19T17:23:05+08:00 Repair info: 0 contacts without an addressbook have been cleaned up
2022-01-19T17:23:05+08:00 Repair info: 0 properties without a contact have been cleaned up
2022-01-19T17:23:05+08:00 Repair info: 0 changes without an addressbook have been cleaned up
2022-01-19T17:23:05+08:00 Repair step: Remove activity entries of private events
2022-01-19T17:23:05+08:00 Repair info: Removed 0 activity entries
2022-01-19T17:23:05+08:00 Repair step: Clean up old calendar subscriptions from deleted users that were not cleaned-up
2022-01-19T17:23:05+08:00 Clean up old calendar subscriptions from deleted users that were not cleaned-up
2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00  Starting ...
    0/0 [------->]   0%2022-01-19T17:23:05+08:00
2022-01-19T17:23:05+08:00 Repair info: 0 calendar subscriptions without an user have been cleaned up
2022-01-19T17:23:05+08:00 Updated <dav> to 1.21.0
2022-01-19T17:23:05+08:00 Updating <files_sharing> ...
2022-01-19T17:23:05+08:00 Repair step: Fix the share type of guest shares when migrating from ownCloud
2022-01-19T17:23:05+08:00 Repair step: Copy the share password into the dedicated column
2022-01-19T17:23:05+08:00 Repair step: Set existing shares as accepted
2022-01-19T17:23:05+08:00 Updated <files_sharing> to 1.15.0
2022-01-19T17:23:05+08:00 Updating <files_trashbin> ...
2022-01-19T17:23:05+08:00 Updated <files_trashbin> to 1.13.0
2022-01-19T17:23:05+08:00 Updating <files_versions> ...
2022-01-19T17:23:05+08:00 Updated <files_versions> to 1.16.0
2022-01-19T17:23:05+08:00 Updating <sharebymail> ...
2022-01-19T17:23:05+08:00 Updated <sharebymail> to 1.13.0
2022-01-19T17:23:05+08:00 Updating <workflowengine> ...
2022-01-19T17:23:05+08:00 Repair step: Populating added database structures for workflows
2022-01-19T17:23:05+08:00 Updated <workflowengine> to 2.5.0
2022-01-19T17:23:05+08:00 Updating <admin_audit> ...
2022-01-19T17:23:05+08:00 Updated <admin_audit> to 1.13.0
2022-01-19T17:23:05+08:00 Updating <comments> ...
2022-01-19T17:23:05+08:00 Updated <comments> to 1.13.0
2022-01-19T17:23:05+08:00 Updating <firstrunwizard> ...
2022-01-19T17:23:05+08:00 Updated <firstrunwizard> to 2.12.0
2022-01-19T17:23:05+08:00 Updating <nextcloud_announcements> ...
2022-01-19T17:23:05+08:00 Updated <nextcloud_announcements> to 1.12.0
2022-01-19T17:23:05+08:00 Updating <notifications> ...
2022-01-19T17:23:06+08:00 Updated <notifications> to 2.11.1
2022-01-19T17:23:06+08:00 Updating <systemtags> ...
2022-01-19T17:23:06+08:00 Updated <systemtags> to 1.13.0
2022-01-19T17:23:06+08:00 Updating <theming> ...
2022-01-19T17:23:06+08:00 Updated <theming> to 1.14.0
2022-01-19T17:23:06+08:00 Updating <contactsinteraction> ...
2022-01-19T17:23:06+08:00 Updated <contactsinteraction> to 1.4.0
2022-01-19T17:23:06+08:00 Updating <dashboard> ...
2022-01-19T17:23:06+08:00 Updated <dashboard> to 7.3.0
2022-01-19T17:23:06+08:00 Updating <federatedfilesharing> ...
2022-01-19T17:23:06+08:00 Updated <federatedfilesharing> to 1.13.0
2022-01-19T17:23:06+08:00 Updating <files_pdfviewer> ...
2022-01-19T17:23:06+08:00 Updated <files_pdfviewer> to 2.4.0
2022-01-19T17:23:06+08:00 Updating <files_rightclick> ...
2022-01-19T17:23:06+08:00 Updated <files_rightclick> to 1.2.0
2022-01-19T17:23:06+08:00 Updating <files_videoplayer> ...
2022-01-19T17:23:06+08:00 Updated <files_videoplayer> to 1.12.0
2022-01-19T17:23:06+08:00 Updating <logreader> ...
2022-01-19T17:23:06+08:00 Updated <logreader> to 2.8.0
2022-01-19T17:23:06+08:00 Updating <photos> ...
2022-01-19T17:23:06+08:00 Updated <photos> to 1.5.0
2022-01-19T17:23:06+08:00 Updating <privacy> ...
2022-01-19T17:23:06+08:00 Updated <privacy> to 1.7.0
2022-01-19T17:23:06+08:00 Updating <provisioning_api> ...
2022-01-19T17:23:06+08:00 Updated <provisioning_api> to 1.13.0
2022-01-19T17:23:06+08:00 Updating <recommendations> ...
2022-01-19T17:23:06+08:00 Updated <recommendations> to 1.2.0
2022-01-19T17:23:06+08:00 Updating <serverinfo> ...
2022-01-19T17:23:06+08:00 Updated <serverinfo> to 1.13.0
2022-01-19T17:23:06+08:00 Updating <settings> ...
2022-01-19T17:23:06+08:00 Updated <settings> to 1.5.0
2022-01-19T17:23:06+08:00 Updating <support> ...
2022-01-19T17:23:06+08:00 Repair step: Switches from default updater server to the customer one if a valid subscription is available
2022-01-19T17:23:06+08:00 Repair info: Repair step already executed
2022-01-19T17:23:06+08:00 Updated <support> to 1.6.0
2022-01-19T17:23:06+08:00 Updating <text> ...
2022-01-19T17:23:06+08:00 Updated <text> to 3.4.0
2022-01-19T17:23:06+08:00 Updating <twofactor_backupcodes> ...
2022-01-19T17:23:06+08:00 Repair step: Add background job to check for backup codes
2022-01-19T17:23:06+08:00 Updated <twofactor_backupcodes> to 1.12.0
2022-01-19T17:23:06+08:00 Updating <updatenotification> ...
2022-01-19T17:23:06+08:00 Updated <updatenotification> to 1.13.0
2022-01-19T17:23:06+08:00 Updating <viewer> ...
2022-01-19T17:23:06+08:00 Updated <viewer> to 1.7.0
2022-01-19T17:23:09+08:00 Update app notes from App Store
2022-01-19T17:23:14+08:00 Repair step: Clean up meta table
2022-01-19T17:23:14+08:00 Update app onlyoffice from App Store
2022-01-19T17:23:24+08:00 Repair step: onlyoffice
2022-01-19T17:23:24+08:00 Repair step: Repair MySQL collation
2022-01-19T17:23:24+08:00 Repair info: All tables already have the correct collation -> nothing to do
2022-01-19T17:23:24+08:00 Repair step: Repair mime types
2022-01-19T17:23:29+08:00 Repair step: Clean tags and favorites
2022-01-19T17:23:29+08:00 Repair info: 0 tags of deleted users have been removed.
2022-01-19T17:23:29+08:00 Repair info: 0 tags for delete files have been removed.
2022-01-19T17:23:29+08:00 Repair info: 0 tag entries for deleted tags have been removed.
2022-01-19T17:23:29+08:00 Repair info: 0 tags with no entries have been removed.
2022-01-19T17:23:29+08:00 Repair step: Repair invalid shares
2022-01-19T17:23:29+08:00 Repair step: Move .step file of updater to backup location
2022-01-19T17:23:29+08:00 Repair info: .step file exists
2022-01-19T17:23:29+08:00 Repair info: .step-previous-update removed
2022-01-19T17:23:29+08:00 Repair info: .step file moved to .step-previous-update
2022-01-19T17:23:29+08:00 Repair step: Add move avatar background job
2022-01-19T17:23:29+08:00 Repair info: Repair step already executed
2022-01-19T17:23:29+08:00 Repair step: Add preview cleanup background jobs
2022-01-19T17:23:29+08:00 Repair step: Fix potential broken mount points
2022-01-19T17:23:29+08:00 Repair info: No mounts updated
2022-01-19T17:23:29+08:00 Repair step: Repair language codes
2022-01-19T17:23:29+08:00 Repair step: Install new core bundle components
2022-01-19T17:23:29+08:00 Repair step: Add log rotate job
2022-01-19T17:23:29+08:00 Repair step: Clear frontend caches
2022-01-19T17:23:29+08:00 Repair info: Image cache cleared
2022-01-19T17:23:30+08:00 Repair info: SCSS cache cleared
2022-01-19T17:23:30+08:00 Repair info: JS cache cleared
2022-01-19T17:23:30+08:00 Repair step: Clear every generated avatar on major updates
2022-01-19T17:23:30+08:00 Repair step: Add preview background cleanup job
2022-01-19T17:23:30+08:00 Repair step: Queue a one-time job to cleanup old backups of the updater
2022-01-19T17:23:30+08:00 Repair step: Cleanup invalid photocache files for carddav
2022-01-19T17:23:30+08:00 Repair step: Add background job to cleanup login flow v2 tokens
2022-01-19T17:23:30+08:00 Repair step: Remove potentially over exposing share links
2022-01-19T17:23:30+08:00 Repair info: No need to remove link shares.
2022-01-19T17:23:30+08:00 Repair step: Clear access cache of projects
2022-01-19T17:23:30+08:00 Repair step: Reset generated avatar flag
2022-01-19T17:23:30+08:00 Repair step: Keep legacy encryption enabled
2022-01-19T17:23:30+08:00 Repair step: Check encryption key format
2022-01-19T17:23:30+08:00 Repair step: Remove old dashboard app config data
2022-01-19T17:23:30+08:00 Repair step: Add job to cleanup the bruteforce entries
2022-01-19T17:23:30+08:00 Repair step: Queue a one-time job to check for user uploaded certificates
2022-01-19T17:23:30+08:00 Repair step: Repair DAV shares
2022-01-19T17:23:30+08:00 Repair step: Add background job to set the lookup server share state for users
2022-01-19T17:23:30+08:00 Starting code integrity check...
2022-01-19T17:23:33+08:00 Finished code integrity check
2022-01-19T17:23:33+08:00 Update successful
2022-01-19T17:23:33+08:00 Maintenance mode is kept active
2022-01-19T17:23:33+08:00 Resetting log level

Keep maintenance mode active? [y/N]
Maintenance mode disabled

Maintenance mode is disabled`

**Comment by DominikWA** [comment] 2022-01-25 10:30
I can confirm the same integrity check error for core/js/mimetypelist.js after upgrading multiple instances from 22.2.3 to 23. The strange thing is in a fresh 23 new instance the integrity check throws no error.

**Comment by mitaka8** [comment] 2022-01-25 21:42
Same error here. I updated from latest 21 to 22.2.3.  I do not see corruption on the file, so I am guessing this file was incorrectly signed.

**Comment by relaxmax68** [comment] 2022-01-26 14:00
absolutely the same effects : 
`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 23a3fa45757b26795f5cf8f94d9e5bce76fc916288a6458679311b312c167adcf4158ccb2c5c3db791fa0b87703b6c5863afb6c9d790b8cbac5ab3ae8c3418fb
                            [current] => 86c1f1b719b65bf02b1dca9b061ef310c8dfface25c9ccfa243c4090665fa6f305d8a4143d7410350af27b1d9e14968c7d999a965d1e110bc674d30ed5dee4e8
                        )

                )

        )

)`

**Comment by afriqs** [comment] 2022-01-31 15:04
Hi,

Same issue here when upgrading from `22.2.3` to `22.2.24` :shrug:

**Comment by sebaxakerhtc** [comment] 2022-01-31 16:35
Same problem after upgrade 23.0.0 => 23.0.1

**Comment by muffinmaster1024** [comment] 2022-02-01 11:56
> Same problem after upgrade 23.0.0 => 23.0.1

Funnily it seems to be fixed for me after 23.0.0 => 23.0.1
(Happened for me at upgrade 22.2.3 => 23.0.0)

**Comment by kevdogg** [comment] 2022-02-17 08:42
Just upgraded to 23.0.2 and receive the same error:

```
root@nextcloud:/usr/local/www/nextcloud # sudo -u www php occ integrity:check-core
  - INVALID_HASH:
    - core/js/mimetypelist.js:
      - expected: 94195a260a005dac543c3f6aa504f1b28e0078297fe94a4f52f012c16c109f0323eecc9f767d6949f860dfe454625fcaf1dc56f87bb8350975d8f006bbbdf14a
      - current: 1b07fb272efa65a10011ed52a6e51260343c5de2a256e1ae49f180173e2b6684ccf90d1af3c19fa97c31d42914866db46e3216883ec0d6a82cec0ad5529e78b1
```

Can I get the correct file?

**Comment by feizhoulv** [comment] 2022-02-18 13:17
It seems to be fixed for me after (23.0.2)

**Comment by afriqs** [comment] 2022-02-18 13:33
> Same issue here when upgrading from `22.2.3` to `22.2.4` shrug

`22.2.5` fixed the issue for me. Thanks.

**Comment by DominikWA** [comment] 2022-02-18 13:48
For me:
23.0.1 -> 23.0.2 The problem still occurs

**Comment by fenvarien** [comment] 2022-02-19 16:31
Same issue with: 22.2.5 --> 23.0.2

**Comment by elmion-hub** [comment] 2022-02-19 18:53
Not wanting to add to the confusion, but

I got this issue when upgrading from 22.2.3 to 22.2.5.

**Comment by lukasmu** [comment] 2022-02-19 19:03
Maybe mimetypelist.js should be excluded from the integrity check as it is automatically generated anyhow?

**Comment by DySprozin** [comment] 2022-02-19 19:10
It looks like this bug appears only for upgrade case. When I did clean install, this error gone.

**Comment by kevdogg** [comment] 2022-02-19 19:56
No..I received error after manual upgrade

**Comment by DySprozin** [comment] 2022-02-19 20:02
Manual upgrade - do you means clean install with new DB ?

**Comment by lukasmu** [comment] 2022-02-20 10:31
@juliushaertl @xh3n1 Do you by chance know what exactly might be going on here?

**Comment by nmaludy** [comment] 2022-02-28 13:17
Same problem here.

**Comment by juliushaertl** [comment] 2022-03-03 11:53
This seems to be caused by the onlyoffice app overwriting the default mimetypelist

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/9806407008ede8f33f904cb4194eff9b8e39f433/lib/Migration/MimeRepair.php#L111

Please report this issue in the app at https://github.com/ONLYOFFICE/onlyoffice-nextcloud.

The best way would be to register the new mime types upstream in Nextcloud in a similar way as this was done in https://github.com/nextcloud/server/pull/29157 but the manual change in the mimetypelist.js is something that needs to be fixed in the ONLYOFFICE app.

**Closed by juliushaertl** 2022-03-03 11:53 UTC
Labels: bug, 0. Needs triage

**Comment by osm-frasch** [comment] 2022-03-26 13:28
> > Same issue here when upgrading from `22.2.3` to `22.2.4` shrug
> 
> `22.2.5` fixed the issue for me. Thanks.

Same Issue updating from 22.2.2 to 22.2.6

**Comment by hohoqq** [comment] 2022-04-08 08:28
Same Issue updating from 22.2.2 to 22.2.6 and then to 23.0.2 with no Onlyoffice app on this server.
