### ISSUE TITLE
Reanimate Imprint app

### ISSUE THREAD

**Issue by hollerauer** [nextcloud/server#5626] opened 2017-07-06 05:47 UTC
for more information see the corresponding discussion on NC-forum:
https://help.nextcloud.com/t/integrate-legal-privacy-info/14293/1

**Comment by hollerauer** [comment] 2017-07-06 11:36
There is an existing solution out there.
But maintenance is necessary
https://github.com/nextcloud/apps/issues/22

**Comment by Schmuuu** [comment] 2017-07-06 15:03
It is pretty easy to fix. If you don't want to wait for a successful reanimation you can download the folder "imprint" place it under nextcloud/apps folder and then edit:
apps/imprint/appinfo/info.xml

Change lines
        <dependencies>
                <owncloud min-version="9" max-version="9" />
                <php min-version="5.3"/>
        </dependencies>


to:
        <dependencies>
                <nextcloud min-version="12" max-version="12" />
                <php min-version="5.3"/>
        </dependencies>

The app can then be enabled on the Web GUI by the admin under "Apps". 

I just tested it and it works.

**Comment by MichaIng** [comment] 2017-07-06 16:05
I opened a pull request, keeping ownCloud support and enabled Nextcloud support down to version 9, since it works with older ownCloud versions as well: https://github.com/nextcloud/apps/pull/36

**Comment by blu-IT** [comment] 2017-07-06 17:48
Well, I can confirm that modifing the app as mentioned above works for a NC 12 installation, **but** the settings made in the administration area (Administration -> Additional settings -> Imprint) are not displayed when returning to that page/settings. 
The imprint section configured with the text is still displayed above, but remains empty in the administrstion area. I think this is confuesing, because you could think that imprint is not configured.

**Comment by MariusBluem** [comment] 2017-07-06 19:11
Closing in favor of https://github.com/nextcloud/apps/pull/36

**Closed by MariusBluem** 2017-07-06 19:11 UTC
