### ISSUE TITLE
Wrong warning / install & update behavior

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/server#26867] opened 2021-05-03 18:56 UTC
i don't get it. Autoinstaller and update install Nextcloud 21. but after install  a warning is prompted:

```
Es wird die MySQL-Version "5.7.Z" verwendet. Nextcloud 21 wird diese Version nicht mehr unterstützen und benötigt MySQL 8 oder höher.
MySQL version “5.7.Z” is used. Nextcloud 21 will no longer support this version and requires MySQL 8 or higher
```
but few lines later the version identifies as
```
Version
Nextcloud 21.0.1
```

i recognised it on different insances. The warning with this version-information makes no sense. May it is a wrong warning or install and update haven't checked the requirements. Which incompabilities needs an mySQL 8?

### Steps to reproduce
1. Install / Update an instance on a server with MySQL 5.7.x 
2. open `settings/admin/overview`
3. compare

### Expected behaviour
Avoid Version 21

### Actual behaviour
uses Version 21

**Comment by kesselb** [comment] 2021-05-04 08:34
Duplicate of https://github.com/nextcloud/server/issues/26470

**Closed by kesselb** 2021-05-04 08:34 UTC
Labels: 0. Needs triage, bug
