### ISSUE TITLE
Files not visible in web interface after upgade to 16

### ISSUE THREAD

**Issue by stone212** [nextcloud/server#15807] opened 2019-05-30 02:43 UTC
### Steps to reproduce
1. Upgrade from 15.x to 16.0.1 using command line updater (`sudo -u www-data php updater.phar`)

2. Choose to disable maintenance mode

3. Return to `nextcloud.mydomain.com` which redirects to `nextcloud.mydomain.com//index.php/apps/files/`

### Expected behaviour

I should see my files waiting for me like always

### Actual behaviour

I See the NC interface but lots of white space where my files should be.  Also I don't have my `Files` etc menu, now it is a "hamburger" menu but that is not important.  It is important that if I choose `Files` in the hamburger menu I do not see my files.

### Server configuration

**Operating system**:  Ubuntu 18.04

**Web server:** apache2

**Database:** mariaDB 15.1

**PHP version:** 7.2.17

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**  Updated from 15.x using https://docs.nextcloud.com/server/15/admin_manual/maintenance/update.html#using-the-command-line-based-updater

**Where did you install Nextcloud from:**  I don't understand.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bookmarks: 1.0.5
  - camerarawpreviews: 0.7.0
  - checksum: 0.4.2
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - deck: 0.6.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_markdown: 2.0.6
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.5.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ojsxc: 3.4.4
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - richdocuments: 3.3.6
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - apporder
  - calendar
  - encryption
  - federation
  - files_rightclick
  - groupfolders
  - spreed
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
root@nextcloud:/var/www/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mydomain.com",
            "files.mydomain.com"
        ],  
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.com",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "debug": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trashbin_retention_obligation": "7, 10",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no
### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu 18.04

#### Web server error log
<details>
<summary>apache2 reports no errors</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
`tail -n 40 data/nextcloud.log` has lots of login information, private information 
```
</details>

**Comment by stone212** [comment] 2019-05-30 03:06
Strange!  I re-booted and the files did not appear.  I waited 20 minutes and re-freshed the page and now they appear.

Also the "hamburger" menu is gone and I have icons at the top of the screen.  

I have no current problem but I do think this is an Issue/bug to be aware of so I will not close but you can.

**Comment by wiswedel** [comment] 2019-05-31 19:31
@stone212 Looks like a caching problem. Is it reproducible? Have you hard-refreshed your browser with ctrl+F5?

**Comment by stone212** [comment] 2019-06-01 06:15
@wiswedel It does sound like a caching problem but I tried that many times, also tried opening in a new browser.  Then later the problem solved itself.  It is very strange.

To re-produce I think I would have to re-install NC 15 and re-upgrade to NC 16.

**Comment by wiswedel** [comment] 2019-06-13 05:47
Since the issue cannot be reliably reproduced, I will close this ticket for now. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by wiswedel** 2019-06-13 05:47 UTC
Labels: 0. Needs triage, bug, needs info
