### ISSUE TITLE
Option to clean up data from an app when disabling it aka. "Uninstall for apps"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#5964] opened 2017-08-03 13:56 UTC
Just came across this in https://github.com/nextcloud/server/issues/5811 again.

The issue is the app was enabled in the past. It's now disabled and not used anymore.
Since the app is not enabled, updates are not executed.
Since updates are not executed, the table can not be migrated to mb4.
Since the repair fails, the update is incomplete.

Depending on when the app was disabled, the available update steps might even be too little (thanks migrations this will hopefully be solved some day). So the update could fail as well.

Also with regards to the new `AppData` stuff I think we should have a `Remove app data` for disabled apps. That would trigger an uninstall script/migration and apps should make sure to:
1. Delete their db tables and columns
2. Remove appconfig, config, preferences, shares, systemtags, comments, ...
3. Remove their data from the data directory

Opinions @MorrisJobke @LukasReschke @rullzer

**Comment by MorrisJobke** [comment] 2017-08-04 06:31
> Also with regards to the new AppData stuff I think we should have a Remove app data for disabled apps. That would trigger an uninstall script/migration and apps should make sure to:

The question is when this should be called. Because we should definitely not call it on app disabling. Because then if an app is incompatible it will kill all it's content.

**Comment by nickvergessen** [comment] 2017-08-04 18:31
No, I would add a new occ for this and add a new button for disabled apps in the ui

**Comment by IzzySoft** [comment] 2018-10-08 16:39
Related: #5539 (where this was requested for when the admin decides to completely remove an app). Which a.o. suggests something like `occ app:remove` (remove the app including its database tables, files, directories etc), `occ app:prune` or `occ app:reset` (reset database (and configuration) to a state as if the app was just installed now).

**Comment by dartcafe** [comment] 2018-12-28 17:36
Please don't forget to clean up the migration table. There are some issues regarding to that, where admins removed the app tables from the database and did not remove the app related migration entries. 

So, after a new install, the tables did not get created or updated. 

i.e. https://github.com/nextcloud/polls/issues/460

**Comment by nickvergessen** [comment] 2019-01-08 15:09
Well there are more things that are related: appconfig, preferences, etc.
Which is why the apps should have an option to take care of it too, but we clean some defined default places.

**Comment by skjnldsv** [comment] 2019-06-12 07:41
Duplicate of https://github.com/nextcloud/server/issues/5964

**Closed by skjnldsv** 2019-06-12 07:41 UTC
Labels: 1. to develop, enhancement, feature: apps management, technical debt
