### ISSUE TITLE
[Bug]: ValueError: str_repeat(): Argument #2 ($times) must be greater than or equal to 0 in /usr/share/webapps/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php:497

### ISSUE THREAD

**Issue by Musikolo** [nextcloud/server#31325] opened 2022-02-23 04:13 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When upgrading to nextcloud from `22.2.3` to `23.0.2` in an ARMv7 device using ArchLinux distro, I'm getting the following error:

```2022-02-22T21:23:15-06:00 Repair info: Removed 0 activity entries
2022-02-22T21:23:15-06:00 Repair step: Clean up old calendar subscriptions from deleted users that were not cleaned-up
2022-02-22T21:23:15-06:00 Clean up old calendar subscriptions from deleted users that were not cleaned-up
2022-02-22T21:23:15-06:00 
An unhandled exception has been thrown:
ValueError: str_repeat(): Argument #2 ($times) must be greater than or equal to 0 in /usr/share/webapps/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php:497
Stack trace:
#0 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php(497): str_repeat('-', -2)
#1 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php(568): Symfony\Component\Console\Helper\ProgressBar::Symfony\Component\Console\Helper\{closure}(Object(Symfony\Component\Console\Helper\ProgressBar), Object(Symfony\Component\Console\Output\StreamOutput))
#2 [internal function]: Symfony\Component\Console\Helper\ProgressBar->Symfony\Component\Console\Helper\{closure}(Array)
#3 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php(581): preg_replace_callback('{%([a-z\\-_]+)(?...', Object(Closure), ' %message%\n %cu...')
#4 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php(393): Symfony\Component\Console\Helper\ProgressBar->buildLine()
#5 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php(302): Symfony\Component\Console\Helper\ProgressBar->display()
#6 /usr/share/webapps/nextcloud/core/Command/Upgrade.php(135): Symfony\Component\Console\Helper\ProgressBar->start(0)
#7 /usr/share/webapps/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\Core\Command\Upgrade->OC\Core\Command\{closure}(Object(OC\EventDispatcher\GenericEventWrapper), '\\OC\\Repair::sta...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 /usr/share/webapps/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OC\\Repair::sta...', Object(OC\EventDispatcher\GenericEventWrapper))
#9 /usr/share/webapps/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, '\\OC\\Repair::sta...', Object(OC\EventDispatcher\GenericEventWrapper))
#10 /usr/share/webapps/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(123): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(OC\EventDispatcher\GenericEventWrapper), '\\OC\\Repair::sta...')
#11 /usr/share/webapps/nextcloud/lib/private/Repair.php(258): OC\EventDispatcher\SymfonyAdapter->dispatch('\\OC\\Repair::sta...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#12 /usr/share/webapps/nextcloud/lib/private/Repair.php(280): OC\Repair->emit('\\OC\\Repair', 'startProgress', Array)
#13 /usr/share/webapps/nextcloud/apps/dav/lib/Migration/RemoveDeletedUsersCalendarSubscriptions.php(67): OC\Repair->startProgress(0)
#14 /usr/share/webapps/nextcloud/lib/private/Repair.php(124): OCA\DAV\Migration\RemoveDeletedUsersCalendarSubscriptions->run(Object(OC\Repair))
#15 /usr/share/webapps/nextcloud/lib/private/legacy/OC_App.php(1071): OC\Repair->run()
#16 /usr/share/webapps/nextcloud/lib/private/legacy/OC_App.php(1013): OC_App::executeRepairSteps('dav', Array)
#17 /usr/share/webapps/nextcloud/lib/private/Updater.php(353): OC_App::updateApp('dav')
#18 /usr/share/webapps/nextcloud/lib/private/Updater.php(265): OC\Updater->doAppUpgrade()
#19 /usr/share/webapps/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade('23.0.2.1', '22.2.3.0')
#20 /usr/share/webapps/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#21 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /usr/share/webapps/nextcloud/console.php(99): OC\Console\Application->run()
#27 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
#28 {main}[root@
```

Code crashing:
```
Line 496: $emptyBars = $bar->getBarWidth() - $completeBars - Helper::strlenWithoutDecoration($output->getFormatter(), $bar->getProgressCharacter());
Line 497: $display .= $bar->getProgressCharacter().str_repeat($bar->getEmptyBarCharacter(), $emptyBars); // Throws an error because $emptyBars is negative
```

I found the following values involved in the operation of line 497 are:
```
bar->getBarWidth()=28
completeBars=3
Helper::strlenWithoutDecoration=27
emptyBars=-2 // This should NEVER be negative
```

### Steps to reproduce

1. Upgrade from nextcloud 22.2.3 to 23.0.2
2. occ upgrade -v

### Expected behavior

Should not crash.

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydevice",
            "mydevice.ddns.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/mydevice",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "logtimezone": "US\/Central",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "theme": "",
        "maintenance": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - bookmarks: 10.0.3
  - calendar: 3.0.6
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.2.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.13.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.5.0
Disabled:
  - activity: 1.2.0
  - admin_audit
  - bruteforcesettings: 2.0.1
  - documents: 0.16.0
  - encryption
  - firstrunwizard: 1.1
  - music: 0.16.0
  - user_ldap
```

**Comment by acsfer** [comment] 2022-02-23 09:43
Duplicate of https://github.com/nextcloud/server/issues/29023

**Closed by acsfer** 2022-02-23 09:43 UTC
Labels: bug, 0. Needs triage
