### ISSUE TITLE
[Feature Improvement] Apps section, larger images/gallery

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/server#9189] opened 2018-04-15 02:16 UTC
When I go check out the Apps I can enable in the Apps section of my dev version of nextCloud, it frustrates me to no end that I can't "expand" the images of the apps. Nor can I see multiple screenshot examples.

Like, why even have images there if I can't even see what's going on?

I really think when I click on an image for an app in this area that it should expand the image to full size, and I think we should also be able to look at a gallery of the same images. Otherwise, the images are completely useless as in most cases you can't even tell what's going on because of how small they are.

Please?

**Comment by MorrisJobke** [comment] 2018-04-16 21:57
Duplicate of #2138

**Closed by MorrisJobke** 2018-04-16 21:57 UTC

**Comment by BloodyIron** [comment] 2018-04-16 22:31
I wouldn't call this a duplicate of that, but okay whatever.
