### ISSUE TITLE
Feature Request: Burn Content Before Removing App Password

### ISSUE THREAD

**Issue by GIJack** [nextcloud/server#9404] opened 2018-05-06 14:47 UTC
I got this idea for a feature:

Give an option in the "App Password/Connected Devices" to not only remove the password, but systematically remove any nextcloud data from the device before removing the password.

So, for example, with Calendars and Contacts, nextcloud would sent a null calendar/contact or push and updated list with no entries, or whatever it takes to trick the device into clearing them out of the local cache. After this is done, the password is revoked.

The use case for this is a lost or stolen phone where not only can access be revoked, all existing remote content like contacts can be as well.

**Comment by MorrisJobke** [comment] 2018-05-07 08:12
Duplicate of #3456

**Closed by MorrisJobke** 2018-05-07 08:12 UTC
