### ISSUE TITLE
Just a question // Feature request // Pretty Share URL

### ISSUE THREAD

**Issue by Christmi** [nextcloud/server#9182] opened 2018-04-14 11:41 UTC
### Question
Is it possible via GUI to customize the share URL?
If I generate a Share URL, there is actually no way to change this URL.

### Workaround
If I really need to change this URL to a pretty URL, I changed the Share URL via Database. (Update Row "token" in table "oc_share")

### Server configuration

**Operating system**: Raspbian GNU/Linux 9

**Web server:** nginx version: nginx/1.10.3

**Database:** 10.1.23-MariaDB-9+deb9u1 Raspbian 9.0

**PHP version:** PHP 7.0.27-0+deb9u1

**Nextcloud version:** 13.0.0.14

**Thank you in advance and If you have further questions, please let me know.**

**Comment by MorrisJobke** [comment] 2018-04-16 22:01
Duplicate of #4536

**Closed by MorrisJobke** 2018-04-16 22:01 UTC
