### ISSUE TITLE
 CalDAV Mail Invitations: Accept/decline buttons missing for added attendees via macOS Calendar app

### ISSUE THREAD

**Issue by xMartin** [nextcloud/server#24467] opened 2020-11-30 21:17 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a new event in Apple Calendar app with an attendee
2. Click "send"
3. Add another attendee to the same event
4. Click "send"

### Expected behaviour
The added attendee should receive an email invitation with buttons to accept/decline.

### Actual behaviour
The added attendee recveives an email invitation without buttons to accept/decline.
(The first attendee does get the buttons in their email.)

### Server configuration

**Operating system:**
Linux

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Quite a history of updates

### Client configuration
**Calendar app:**
Apple macOS Calendar app 11.0 (2760.4.1)

**Operating system:**
macOS 10.15.7

----

macOS Calendar app doesn't seem to add `RSVP:TRUE` for added attendees. It could be a bug on their side, but using Google calendar server with macOS Calendar app does show these buttons so they seem to work around this.

https://github.com/nextcloud/server/blob/0f7fb7cb4e296f6b90d668eb9cd01bcd6ef0c582/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L250 checks for this. Is it really necessary?

**Comment by szaimen** [comment] 2021-06-18 11:51
Duplicate of https://github.com/nextcloud/server/issues/21189

**Closed by szaimen** 2021-06-18 11:51 UTC
Labels: 0. Needs triage, bug, feature: dav
