### ISSUE TITLE
Dark Mode: In User management Options Menu stays blank

### ISSUE THREAD

**Issue by tobyps** [nextcloud/server#21836] opened 2020-07-14 16:22 UTC
When the Windowswidth is small enough that the options are collapsed into the "Burgermenu" opening it just shows a white space where the options should be.

Resizing the window the correct menu appears left of the white space. 

Using Nextcloud 18.06 

I attached 2 images showing the problem.
![Screenshot (63)](https://user-images.githubusercontent.com/52735599/87450554-edc99e80-c5fe-11ea-9270-bcf0c6061d52.png)
![Screenshot (65)](https://user-images.githubusercontent.com/52735599/87450558-ee623500-c5fe-11ea-8fa5-483663ecb67d.png)

**Comment by szaimen** [comment] 2021-06-08 10:59
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-08 10:59 UTC
Labels: 0. Needs triage
