### ISSUE TITLE
No share link menu when using Chromium

### ISSUE THREAD

**Issue by DerDakon** [nextcloud/server#15320] opened 2019-05-01 09:48 UTC
I am unable to create or modify a share link in the webinterface when using Chromium, the '…' icon simply does not show up on the end of the row. Creating shares with accounts works. After I created the link using Firefox the "copy link" icon shows up and works, but the '…' is still only visible in FF.

This is nextcloud 16.0 running on openSUSE 15.0, problem was already there in 15. I can't tell when or if it previously worked as I seldomly use this feature.

**Comment by frbehrens** [comment] 2019-05-02 18:44
I see the same problem - but with a different browser. The dots for the menu do not appear with Firefox 66.0.3 (Windows 10, 64 Bit), I had to use Edge to remove my test share.
Nextcloud with the problem is 16.0.0.9, running with php 7.2.14.

**Comment by kesselb** [comment] 2019-05-02 19:02
Are you using some kind of ad blocker maybe?

**Comment by frbehrens** [comment] 2019-05-02 19:18
> Are you using some kind of ad blocker maybe?

Yes. And therefore I edited already my comment and added the information.

**Comment by Soulsurfering** [comment] 2019-08-04 13:20
I have the same issue using Firefox 68.0.1 with the AdBlock Plus addon.
The dots are visible if the adblock is disabled for my nextcloud server 
or if I uncheck the AdBlock Plus options "Block additional tracking" and "Block social media icon tracking"

**Comment by skjnldsv** [comment] 2020-09-09 11:53
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-09-09 11:53 UTC
Labels: 0. Needs triage, bug

**Comment by DerDakon** [comment] 2020-09-09 18:13
This still happens with 19.0.2, here the menu for the same folder in the 2 browsers
![Chromium 85.0.4183.69](https://user-images.githubusercontent.com/10909049/92637041-9e3ee080-f2d8-11ea-8212-c4f5f59e5960.png)
![Firefox 78.2.0esr](https://user-images.githubusercontent.com/10909049/92637045-9f700d80-f2d8-11ea-96af-a9dc5ab7d000.png)

**Comment by DerDakon** [comment] 2020-09-09 18:17
Other thinks that don't work include e.g the initial page of the about box, the other 3 work fine.

**Comment by skjnldsv** [comment] 2020-09-09 21:21
This is from your ad block.
Disable there is a custom filter around that have crazy wide CSS rules. Don't use this. It breaks nextcloud. You can search for existing issues on nextcloud, this was already discussed :)
