### ISSUE TITLE
browserslist config package

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#13962] opened 2019-01-31 19:36 UTC
While in the process of defining a list of supported browsers. We should create a package out of this so all apps can easily use it as well. See https://github.com/browserslist/browserslist#shareable-configs

I could envision this as follows.

* A basic package version that just defines what we support.
* Packages bound to the nextcloud version. Because NC13 supports different firefox versions than NC16 will.

@nextcloud/javascript

**Comment by ChristophWurst** [comment] 2019-06-18 07:52
I knew there was a package for this …

Anyway, here it is: https://github.com/ChristophWurst/browserslist-config-nextcloud. This is the prototype for #15932. I would eventually release it as `@nextcloud/browserslist-config` once we figured out a stable format.

@nextcloud/javascript can we come up with a finite list of supported browsers? We can take https://github.com/cerner/browserslist-config-terra/blob/master/browserslist.config.js as an example. Which browsers do we support officially and which ones do we want to try to support?

**Comment by skjnldsv** [comment] 2019-06-18 07:56
Duplicate of #13621 ?

**Comment by ChristophWurst** [comment] 2019-06-18 08:02
Kind of :)

**Comment by ChristophWurst** [comment] 2019-06-18 11:41
> Kind of :)

Well not really. This ticket is about the config package, which #15988 tackles. And #13621 is about the actual list. So not a duplicate IMO.

**Closed** 2019-06-19 12:59 UTC
Labels: 4. to release, enhancement, javascript
