### ISSUE TITLE
Nextcloud 20.0.7 with Collabora Online makes the system extremely slow

### ISSUE THREAD

**Issue by Thomas1NC** [nextcloud/server#25637] opened 2021-02-14 17:51 UTC
Hi,
I installed nextcloud 20.0.7 (completely new installation) and found that the system was extremely slow. It was almost impossible to reach the start screen. It took me very long time to found out that the apps "Collabora Online" and „Collabora Online - Built-in CODE Server“ are the reason for my problems. Simply deactivate these two apps solved the problem. 
What do the experts say?
Greetings Thomas

**Comment by kesselb** [comment] 2021-02-14 18:59
Duplicate of https://github.com/nextcloud/richdocuments/issues/1282

**Closed by kesselb** 2021-02-14 18:59 UTC
Labels: 0. Needs triage, bug
