### ISSUE TITLE
[Bug]: Sorting by date deleted in Recycle Bin Incorrect

### ISSUE THREAD

**Issue by ItsMeRitch** [nextcloud/server#41292] opened 2023-11-05 23:42 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sorting by Date Deleted in Recycle Bin on Nextcloud, it does not seem to be able to sort correctly, for instance, sometimes sorting it results in random dates all over the place and other times, it looks like it has sorted it but actually it has random deleted files not correctly sorted as you scroll down 

### Steps to reproduce

1. Have Deleted Items enabled
2. Delete items at various intervals over the course of a month
3. Go to recycle bin on web UI and sort items by "Deleted" 

### Expected behavior

Should sort by date deleted correctly 

### Installation method

Community Docker image

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
root@aefd13bfb5ab:/#sudo -u www-data php occ config:list system
php occ config:list system
./occ config:list system
sudo: unknown user www-data
sudo: error initializing audit plugin sudoers_audit
Could not open input file: occ
bash: ./occ: No such file or directory
```

### List of activated Apps

```shell
sudo -u www-data php occ app:list
php occ app:list
./occ app:list
```

**Comment by XueSheng-GIT** [comment] 2023-11-07 11:41
Duplicate of https://github.com/nextcloud/server/issues/40484

**Closed** 2023-11-07 12:45 UTC
Labels: bug, 0. Needs triage, feature: trashbin, 28-feedback
