### ISSUE TITLE
Trashbin does not open when too many files are deleted

### ISSUE THREAD

**Issue by twatzl** [nextcloud/server#21600] opened 2020-06-26 20:09 UTC
Hi, 

I have the issue that my Nextcloud deleted some important files I still need. However I recently cleaned up lots of files, which lead to the fact that I have about 47 500 files in my trashbin directory.

### Steps to reproduce
1. have many files in nextcloud 
2. delete lots of files 
3. open trashbin

### Expected behaviour
Trashbin shows files that are actually in trashbin. It would probably make sense to organize them in the original folder structure for performance reasons. 

It should be possible to restore or permanentely delete files.

### Actual behaviour

Trashbin says it's empty despite 47500 files summing up to ~200GB are in the folder on my server.

It is not possible to restore or delete files.

I guess this is due to the fact, that NC tries to fetch all files in one go, which obviously fails:
![image](https://user-images.githubusercontent.com/18753370/85896683-36105080-b7f9-11ea-8d81-ddea2fd54911.png)

Regardless of whether this is an insane amount of files, I would expect this to work. Also configuring my reverse proxy with a longer timecould could only be seen as a workaround (and one I will not attempt) as I think 60 seconds should be plenty of time for a request.

Also on the server the database causes a high load. So I think there should be implemented some kind of chunking to reduce the overall load and split it up. Also with that amount of files some filtering would be good, not only for performance reasons, but also beause you otherwise cannot find what you need.

## Server configuration detail

**Operating system:** Linux 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64

**Webserver:** nginx/1.17.10 (fpm-fcgi)

**Database:** mysql 10.4.10

**PHP version:** 7.3.18

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** official docker image

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.10.0
 - bookmarks: 3.0.13
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.3
 - carnet: 0.22.0
 - checksum: 0.4.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - cookbook: 0.6.5
 - cospend: 0.5.4
 - dav: 1.14.0
 - deck: 1.0.1
 - drawio: 0.9.5
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_markdown: 2.2.0
 - files_pdfviewer: 1.7.0
 - files_photospheres: 1.0.8
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - gpxmotion: 0.0.11
 - gpxpod: 4.2.1
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - phonetrack: 0.6.3
 - photos: 1.0.0
 - polls: 1.4.3
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quicknotes: 0.2.4
 - recommendations: 0.6.0
 - richdocuments: 3.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - flowupload
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        *** removed manually ***
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "http:\/\/192.168.255.10:8080",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "overwriteprotocol": "https",
    "loglevel": 2,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "has_rebuilt_cache": true
}
```
</details>

**External storages:** yes

<details><summary>External storage configuration</summary>

```
No mounts configured
```
</details>

**Encryption:** no

**User-backends:** 
 * OC\User\Database

**Comment by Dragon988** [comment] 2020-06-26 20:17
Have you verified this issue exists in 18.06? I noticed you are on 18.04.

Do you have any error logs to help debug this issue?

**Comment by twatzl** [comment] 2020-06-26 20:32
Have you seen any specific notes in the changelog that would suggest that this particular issue has been fixed? I have this issue since using NC 15 or 16. I highly doubt that this minor upgrade has fixed it. 

All the logs I have are in the issue. There are no other log entries in the logging that would suggest an error happens. My guess would be that the database and NC server is simply overwhelmed by the amount of files.

**Comment by twatzl** [comment] 2020-06-26 20:35
So for everyone affected by this bug I have found a workaround to get back the files.
It needs admin access to:
1. the server where the data is located
2. the nextcloud container

Steps:

1. move all the files in /path/to/nc/data/<your username>/files_trashbin/ to a save backup location
2. copy back the files you want to investigate/restore/permanently delete (don't do it for all at once)
3. run occ files:scan --path=/<your username>/files_trashbin

then there is fewer file entries and nextcloud can actually handle them.

**Comment by Dragon988** [comment] 2020-06-26 20:38
I've ripped part of imgur (via rclone mount with webdav) and had no issue with deleting over 250,000 files through the web interface. It has a high load and takes time but it does finish.

So... not a universal issue. Are you sure there are no error logs anywhere? If not it's probably a configuration issue on your end. But I have stupidly high limits on everything in my server configuration.

**Comment by twatzl** [comment] 2020-06-26 20:43
Are you talking about just deleting or about the trashbin? I am talking about the trashbin. Deleting works just fine with the desktop client and other methods, but I want for obvious reasons to have the chance to restore accidentally deleted files. Hence I enabled the trashbin "app" (it is part of core nextcloud). And this app/component has the issue.

![image](https://user-images.githubusercontent.com/18753370/85899419-51318f00-b7fe-11ea-8273-6468aea42f50.png)

**Comment by Dragon988** [comment] 2020-06-26 20:44
Yes. I delete the files through the web interface, go to the trashbin and permanently delete. It takes a LONG TIME but does finish.

**Comment by Dragon988** [comment] 2020-06-29 20:54
Using the following script I generated 20,000 random files then imported through occ and attempted to recreate your issue.

`#! /bin/bash
for n in {1..20000}; do
    dd if=/dev/urandom of=file$( printf %03d "$n" ).bin bs=1 count=$(( RANDOM + 1024 ))
done`

@kesselb While trying to recreate this issue the web browser locks up while scrolling through the directory with 20,000 files which I did not test last time. Both in trashbin and in file explorer. While the server does have a high load this issue appears to be a client side browser issue.

However it's still possible to restore the folder through the trashbin along with individual files if your web browser doesn't lock up so I'm not sure if this would be considered a separate bug report from the OP's issue.

**Comment by twatzl** [comment] 2020-06-30 05:46
Ok so maybe there are some more factors which lead to this. 
1. I had many images in the trash which needed previews
2. I have the extension for previews for raw images installed

From what I see in the browser logs it looks (see above) as if the request times out. This seems to be due to the fact that the current architecture is set to fetch all files in one request. The server takes time for processing and fails.

As far as I can see this issue requires a solution on both sides. Server and UI. The server must provide an api for partially listing folders (i.e. pagination) and the UI must/should support virtual scrolling and be optimized to display large directories.
As a workaround it might be possible to split up the trashbin in multiple directories. 

Also what I realized when opening the trashbin the load on the database is rather high. Using mysql it uses up all the processing power it can get.

I notice the general slow performance/unreliable loading of pages also on other pages in NC, but of course for the trashbin it breaks things completely.

**Comment by Dragon988** [comment] 2020-06-30 15:33
Many images doesn't help us. Are you talking about sub-100 or 1000+ in a single folder in the trashbin?

I had no issues with browsing the trashbin with everything spread between folders. The issue I mentioned is only related to browsing a folder with thousands of files in it, which is why I'm not sure if it's related to your issue or not.

**Comment by twatzl** [comment] 2020-07-02 15:45
There are folders for you in the trashbin? My trashbin just puts everything in a single folder. 
I had about 40000 images in the trashbin. jpg and raw.

**Comment by Dragon988** [comment] 2020-07-02 15:59
Yes.... refer to my first comment in this topic about why you're running version 18.04.

I'm on 19 for the record.

**Comment by twatzl** [comment] 2020-07-02 16:39
Sorry, but I asked if there is a change that could have resolved this issue in the mean time and did not get a response. 
I checked all the changelogs I could find:
- https://nextcloud.com/changelog/#latest19
- https://nextcloud.com/blog/nextcloud-hub-brings-productivity-to-home-office/
- https://github.com/nextcloud/server/milestone/99?closed=1
but could not find anything about a similar issue that has been fixed already.

There are performance improvements stated in the changelogs, however only very vaguely. I hope you understand that I want to wait with an upgrade until 19 has the stable tag.

Anyway just to verify I checked again and tested something more and I found out the following:
- If I delete a folder in the web ui it gets moved to the trashbin as a whole
- However my use case was that I deleted a lot of files using duplicate search on my machine which was then synced via the nextcloud client. Since I only deleted files, but not directories, no directories ended up in the trashbin and all 40000 files were placed in the root directory.

**Comment by szaimen** [comment] 2021-06-07 13:17
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by SpamReceiver** [comment] 2021-06-08 18:44
> Is this Issue `Trashbin does not open when too many files are deleted` still valid in NC21.0.2? If not, please close this issue. Thanks! :)

I can confirm this mis-behaviour for Nextcloud 21.0.2.

**Comment by putt1ck** [comment] 2021-11-04 12:31
We might have something that will alleviate this coming via https://github.com/nextcloud/server/issues/16412

**Comment by putt1ck** [comment] 2022-01-21 10:20
See https://github.com/nextcloud/server/issues/24544#issuecomment-1018349842 for developments so far.

For reference, the issue with the trashbin is around the single load of all the items. As the quantity mounts this makes the load take so long users give up - and eventually it just gets to the point of never loading, somewhere around 500k items.

**Comment by twatzl** [comment] 2022-01-26 17:19
I think the limit is MUCH lower than 500k items if you have lots of images and previews enabled.

**Comment by putt1ck** [comment] 2022-01-26 17:31
The big installation in question does have a lot of images; never noticed previews being enabled within trash, that would seem an an obvious enhancement to turn that off, if removing functionality can be called an enhancement. The last time we still saw trash loading (given 5+ minutes to do so) and also had a count was at about 370k files.

**Comment by szaimen** [comment] 2023-01-09 16:37
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by putt1ck** [comment] 2023-01-10 05:18
We resolved the issues by making some changes in the trash app and in group folders. Trash loads a folder view now.

**Comment by szaimen** [comment] 2023-01-10 08:02
Are these changes merged here already or did you create a fork with your changes?

**Comment by putt1ck** [comment] 2023-01-10 08:11
It was a fork. Internally we discussed making a PR but it wasn't clear whether the changes would be welcomed, and we only had the one client that had enough deleted items/group folders for it to be an issue.

**Comment by szaimen** [comment] 2023-01-10 08:13
I mean of course we would welcome such a PR. :) Sorry if we did not make it clear!

**Comment by SpamReceiver** [comment] 2023-01-11 18:58
I'm on 25.0.2 now, and can confirm that it works a bit better.
Yes, it looks like a folder view, but takes 3 minutes to load the first chunk of 2023 Ordner und 107563 Dateien.
Scrolling feels strange, like it jumps every time another chunk is loaded.

**Closed** 2023-03-06 13:41 UTC
Labels: bug, needs info, 0. Needs triage, feature: trashbin
