### ISSUE TITLE
Nextcloud 21 SMB files_external Windows folder redirection folders show up as read only

### ISSUE THREAD

**Issue by brucealthompson** [nextcloud/server#26557] opened 2021-04-14 14:21 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

It looks like files_external SMB mounts of Windows shares show folders with Windows folder redirection enabled (\Users\username{Documents,Downloads,Pictures,etc} as read-only.

This did not happen in older versions of Nextcloud (I previously ran 16.04) so I assume this is a regression.

### Steps to reproduce
1. mount a Windows user home directory (\Users\username) as a Nextcloud SMB mount

### Expected behaviour
Folders with Windows folder redirection enabled (\Users\username{Documents,Downloads,Pictures,etc} should show up as as read-write.

### Actual behaviour
Folders with Windows folder redirection enabled (\Users\username{Documents,Downloads,Pictures,etc} show up as as read-only.

### Server configuration

**Operating system:**
Debian 10

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
21

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment] 2021-04-14 14:23
Duplicate of #26321

**Closed by szaimen** 2021-04-14 14:23 UTC
Labels: 0. Needs triage, bug
