### ISSUE TITLE
Push\Helper\IPushHelper' not found in 

### ISSUE THREAD

**Issue by bgman111111** [nextcloud/server#19502] opened 2020-02-16 09:58 UTC
hi after upgrade nextcloud 18.01 it comment this: PHP Fatal error:  Interface 'OCP\Push\Helper\IPushHelper' not found in /var/www/nextcloud/apps/push/lib/Helper/PushHelper.php on line 78

**Comment by kesselb** [comment] 2020-02-16 10:17
Uninstall the push app

**Comment by bgman111111** [comment] 2020-02-16 10:39
i unindtsll it... but why ut dint work. wvy nextcloud accept push dont work

**Comment by kesselb** [comment] 2020-02-16 11:13
Closing as duplicate of https://github.com/nextcloud/push/issues/76. Thanks for reporting :+1:

**Closed by kesselb** 2020-02-16 11:13 UTC
Labels: 0. Needs triage, bug
