### ISSUE TITLE
Sharing information is only shown in root folder

### ISSUE THREAD

**Issue by epochal** [nextcloud/server#4281] opened 2017-04-10 15:59 UTC
### Steps to reproduce
1. Try finding the information with what groups and users a subfolder is shared with
2. The information should be given in same way as in the root folder

### Expected behaviour
Information for the logged-in user with whom a subfolder is shared with

### Actual behaviour
There is no information given. A user could assume, that he must share this subfolder. Sharing is possible and the information is displayed then - even when this user or group was already there (invisible).

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Comment by MorrisJobke** [comment] 2017-04-10 18:29
cc @nextcloud/designers for ideas how to solve this

Maybe the stuff @Espina2 proposed helps there already a bit #4273

**Comment by jancborchardt** [comment] 2017-06-04 22:35
@epochal could you sbow with screenshots what you are referring to? I'm not quite sure I understand. Thanks! :)

**Comment by epochal** [comment] 2017-06-05 08:04
Here is an example: We created the root folders with 1 specific users, so that the data is stored with that 1 specific user. Otherwise the data would be spread in many different users-folders. 
Our root folders are Finance, Marketing and Sales for example. Now the finance managers want to be sure, that only the right people can see information in the Finance folder and it subfolders. Currently there is only information in the root folder. In the root folder I miss the function, seeing what persons are in a group! (another important topic for me) And the sharing information is not visible in the sub-folders.

![grafik](https://cloud.githubusercontent.com/assets/11759846/26775201/1c142d3c-49d4-11e7-92b1-11bfafd6e38a.png)

How can I find out (as a normal user) who is member of the group CEO?
![grafik](https://cloud.githubusercontent.com/assets/11759846/26775459/5c062390-49d5-11e7-98fb-7b8b851048b5.png)

In the sub-folders the sharing info is missing:
![grafik](https://cloud.githubusercontent.com/assets/11759846/26775593/d8cb94d2-49d5-11e7-85b7-60d5095d116a.png)

I think those 2 enhancements should be added to the core of nextcloud.

Cheers

Werner

**Comment by jancborchardt** [comment] 2017-06-08 16:04
Aah ok, it’s about the sidebar. Thanks for the clarification! :)

Three enhancements we should make then:

- [ ] In the subfolders, add an entry for »Parent folder **Finance** shared with group **CEOs**«
- [ ] Clicking on the folder name »Finance« should get you to that folder, with the sidebar open
- [ ] Hovering the group name should show the members of that group.

Would that solve the issue @epochal? :)

**Comment by epochal** [comment] 2017-06-08 17:57
My view on the 3 enhancements you suggested:

> In the subfolders, add an entry for »Parent folder Finance shared with group CEOs«
 This is good. And this should look up **all** parent folders (if I go into a subfolder of **Accounting**) and the **current** folder. In general NC should show on any folder, who has got access to it.

> Clicking on the folder name »Finance« should get you to that folder, with the sidebar open
That is maybe nice to have. But in general the navigation in NC is good enough for me.

> Hovering the group name should show the members of that group.
I like that. AND maybe I can also see, what rights each user has got (read, upload, edit, delete)

**Comment by jancborchardt** [comment] 2017-06-09 14:49
@epochal cool, thanks for the feedback.

@schiessle @nextcloud/sharing is this feasible? :)

**Comment by szaimen** [comment] 2021-05-21 12:14
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-21 12:14 UTC
Labels: 1. to develop, enhancement, feature: sharing
