### ISSUE TITLE
Dark theme is not reload when changing administration/theming

### ISSUE THREAD

**Issue by Aeredren** [nextcloud/server#28899] opened 2021-09-20 09:40 UTC
### Steps to reproduce
1. Login as administrator
2. Change to darktheme in settings/personal/accessibility
3. Go to settings/administration/theming and change any fields

### Expected behaviour
The page should stay in dark-theme with a dark backgroud

### Actual behaviour
The page switch to a light background. Global settings is not affect and changing pages or reloading revert to dark theme correctly

### Server configuration

**Operating system:** Arch Linux

**Web server:** Apache/2.4.48

**Database:** SQLite 3.36.0

**PHP version:** 8.0.10

**Nextcloud version:**  23.0.0 alpha

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.8.0
  - calendar: 2.3.3
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.3
  - contactsinteraction: 1.3.0
  - cospend: 1.3.19
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - lookup_server_connector: 1.10.0
  - oauth2: 1.10.0
  - polls: 3.1.0
  - provisioning_api: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.1
Disabled:
  - admin_audit
  - encryption
  - files_external
  - richdocuments
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite",
        "version": "23.0.0.0",
        "overwrite.cli.url": "http:\/\/127.0.0.1\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "app_install_overwrite": [
            "calendar",
            "deck",
            "spreed",
            "polls"
        ],
        "maintenance": false,
        "log_type": "syslog",
        "loglevel": 0,
        "logtimezone": "UTC",
        "default_phone_region": "FR"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla Firefox 92.0

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment] 2021-09-20 10:42
Duplicate of https://github.com/nextcloud/server/issues/14059

**Closed by szaimen** 2021-09-20 10:42 UTC
