### ISSUE TITLE
Groupfolders insufficient storage (Win/Mac Client)

### ISSUE THREAD

**Issue by thammerbacher** [nextcloud/server#7317] opened 2017-11-28 09:15 UTC
I have installed a NextCloud 12.0.2 on Ubuntu 16.04 LTS with up to date Mysql and Apache2.

We use "groupfolders" and have a sync problem with the Windows/Mac Client.

Error transferring https://domain.de/remote.php/dav/files/foldername/subfoldername/filename.suffix - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)
 
Quota of the groupfolder is set to 10 GB. File has size of 1 MB. User has 1 KB quota.

If I set the user quota up to for example 1 GB everything works fine. But the users should not be able to add files to personal root folder.

I have already updated the code from https://github.com/nextcloud/server/pull/5685 but it still doesn't work.

Same error message as before!

**Comment by MorrisJobke** [comment] 2017-12-14 14:34
Duplicate of #6354

**Comment by MorrisJobke** [comment] 2017-12-14 14:35
Fix is in #6483

**Closed by MorrisJobke** 2017-12-14 14:34 UTC
