### ISSUE TITLE
Update problem to 10.0.5 - module File sharing - users do not connect

### ISSUE THREAD

**Issue by jplouvel** [nextcloud/server#4698] opened 2017-05-04 13:52 UTC
### Steps to reproduce
Upgrade from nextcloud-9.0.58 to nextcloud-10.0.5

### Expected behaviour
User should be able to log in

### Actual behaviour
The admin user logs on but users do not connect.
When the share module is deactivated, there is no conection problem anymore.

### Server configuration

**Operating system**:
Debian 

**Web server:**
Apache 2.2

**Database:**
MySQL 5.5

**PHP version:**
PHP 5.6

**Nextcloud version:** (see Nextcloud admin page)
10.0.5 

**Updated from an older Nextcloud/ownCloud or fresh install:**
9.0.58

#### Nextcloud log (data/nextcloud.log)

```
Error	PHP	InvalidArgumentException: at /var/www/nextcloud/lib/private/Share20/Share.php#288

Error	index	InvalidArgumentException: 

    /var/www/nextcloud/lib/private/Share20/DefaultShareProvider.php - line 758: OC\Share20\Share->setSharedBy(NULL)
    /var/www/nextcloud/lib/private/Share20/DefaultShareProvider.php - line 622: OC\Share20\DefaultShareProvider->createShare(Array)
    /var/www/nextcloud/lib/private/Share20/Manager.php - line 957: OC\Share20\DefaultShareProvider->getSharedWith('Bob', 0, NULL, -1, 0)
    /var/www/nextcloud/apps/files_sharing/lib/MountProvider.php - line 71: OC\Share20\Manager->getSharedWith('Bob', 0, NULL, -1)
    /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php - line 77: OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
    [internal function] OC\Files\Config\MountProviderCollection->OC\Files\Config\{closure}(Object(OCA\Files_Sharing\MountProvider))
    /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php - line 78: array_map(Object(Closure), Array)
    /var/www/nextcloud/lib/private/Files/Filesystem.php - line 426: OC\Files\Config\MountProviderCollection->getMountsForUser(Object(OC\User\User))
    /var/www/nextcloud/lib/private/Files/Filesystem.php - line 374: OC\Files\Filesystem initMountPoints('Bob')
    /var/www/nextcloud/lib/private/legacy/util.php - line 227: OC\Files\Filesystem init('Bob', '/Bob/file...')
    /var/www/nextcloud/lib/base.php - line 997: OC_Util setupFS()
    /var/www/nextcloud/index.php - line 48: OC handleRequest()
```

**Comment by MorrisJobke** [comment] 2017-05-04 22:57
cc @rullzer @schiessle

**Comment by MorrisJobke** [comment] 2017-05-04 22:58
Duplicate of #2740

**Closed by MorrisJobke** 2017-05-04 22:58 UTC
Labels: 0. Needs triage, bug, feature: sharing
