### ISSUE TITLE
Calendars invitations for event in shared calendars

### ISSUE THREAD

**Issue by FabioLapolla** [nextcloud/server#4880] opened 2017-05-15 15:51 UTC
### Steps to reproduce
1. Create calendar and share it with other users or groups
2. A user with write permission on shared calendar creates event and invite other users (or email addresses)

### Expected behaviour
The attendees should receive an email notification about the event and/or an invitation containing an .ics file.

### Actual behaviour
No message is sent to the attendees after saving the new event.
Notification email is sent only when the event is deleted.

### Server configuration

**Operating system**: Ubuntu 16.04.2 LTS 64bit

**Web server:** Apache 2.4.18

**Database:** MariaDB 10.0.29

**PHP version:** 7.0.15

**Nextcloud version:** 11.0.3 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-11.0.3.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php", TRIED ALSO WITH smtp
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Any (Firefox, Chrome, Chromium)
Ubuntu and Windows 7
Also with Thunderbird/Lightning

**Comment by tbdt** [comment] 2017-08-29 09:26
I got the same problem.
Nextcloud version: 12.0.2 (stable)

**Comment by MorrisJobke** [comment] 2017-08-31 15:25
cc @georgehrke

**Comment by MorrisJobke** [comment] 2017-09-03 18:55
Noticed that it is a duplicate of #3830

**Closed by MorrisJobke** 2017-09-03 18:55 UTC
Labels: 0. Needs triage, bug, feature: dav

**Comment by xeruf** [comment] 2022-05-03 15:24
@MorrisJobke no it isn't, they explicitly asked to create a separate issue: https://github.com/nextcloud/server/issues/3830#issuecomment-299921863

**Comment by xeruf** [comment] 2022-05-03 15:27
Now tracked in https://github.com/nextcloud/server/issues/26668
