### ISSUE TITLE
File Details Sidebar Tabs Comments/Versions empty

### ISSUE THREAD

**Issue by t0mcat1337** [nextcloud/server#21256] opened 2020-06-05 14:18 UTC
### Steps to reproduce

1. Click on a files three-dot menu, choose "Details"
2. Tab Comment: Completely empty, no possibility to enter / view comments
3. Tab Versions: Completely empty, no versions or any other text is shown. BTW: Folder "files_version" in the user subfolder in NC Datadir has current files
4. Tab Share: Works fine

### Expected behaviour
All tabs should work

### Actual behaviour
Tabs "Comments" and "Versions" are completely empty

## Server configuration detail

**Operating system:** Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.30

**PHP version:** 

7.2.27-1+ubuntu18.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, memcache, msgpack, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.5 - 18.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** Your Website, then updated

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - apporder: 0.10.0
 - bookmarks: 3.1.1
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - cookbook: 0.6.5
 - dav: 1.14.0
 - deck: 1.0.2
 - drawio: 0.9.5
 - extract: 1.2.4
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_clipboard: 0.7.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_readmemd: 1.1.4
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - flowupload: 1.0.0
 - issuetemplate: 0.6.0
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - metadata: 0.11.1
 - mindmaps: 0.1.0
 - news: 14.1.11
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocdownloader: 1.7.8
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - polls: 1.4.3
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - sharerenamer: 2.7.3
 - spreed: 8.0.9
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - twofactor_admin: 2.1.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_nextcloud_notification: 2.3.0
 - twofactor_totp: 4.1.3
 - user_ldap: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - accessibility
 - activity
 - admin_audit
 - audioplayer
 - bruteforcesettings
 - carnet
 - encryption
 - external
 - files_automatedtagging
 - files_mindmap
 - files_videoplayer
 - firstrunwizard
 - gpxedit
 - nextcloud_announcements
 - notes
 - ownnote
 - phonetrack
 - quicknotes
 - recommendations
 - serverinfo
 - support
 - survey_client
 - theming
 - theming_customcss
 - updatenotification
 - uploaddetails

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       ***REMOVED SENSITIVE VALUE***
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.5.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "appstore.experimental.enabled": true,
    "theme": "",
    "loglevel": 0,
    "filesystem_check_changes": 1,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updatechecker": false,
    "maintenance": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "updater.release.channel": "stable",
    "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "mysql.utf8mb4": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "dbindex": 0
    },
    "overwriteprotocol": "https",
    "blacklisted_files": [],
    "htaccess.RewriteBase": "\/",
    "app_install_overwrite": [
        "apporder",
        "calendar",
        "external",
        "files_accesscontrol",
        "files_automatedtagging",
        "spreed",
        "mindmaps",
        "keeweb",
        "sharerenamer",
        "uploaddetails",
        "files_clipboard"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 0background_sync_prefix: s02cleanUpJobOffset: 0enabled: yesinstalled_version: 1.8.0s02_lastChange: 1591364473s02has_memberof_filter_support: 1s02home_folder_naming_rule: attr:uids02last_jpegPhoto_lookup: 0s02ldap_agent_password: cm9vdHZhZGVys02ldap_attributes_for_group_search: cn
description
mailPrimaryAddresss02ldap_attributes_for_user_search: uid
givenName
sn
description
employeeNumber
mailPrimaryAddress
displayNames02ldap_backup_host: s02ldap_backup_port: s02ldap_base: dc=gallien,dc=gals02ldap_base_groups: dc=gallien,dc=gals02ldap_base_users: cn=users,dc=gallien,dc=gals02ldap_cache_ttl: 600s02ldap_configuration_active: 1s02ldap_default_ppolicy_dn: s02ldap_display_name: displaynames02ldap_dn: uid=Administrator,cn=users,dc=gallien,dc=gals02ldap_dynamic_group_member_url: s02ldap_email_attr: mailPrimaryAddresss02ldap_experienced_admin: 0s02ldap_expert_username_attr: uids02ldap_expert_uuid_group_attr: s02ldap_expert_uuid_user_attr: s02ldap_gid_number: gidNumbers02ldap_group_display_name: cns02ldap_group_filter: (|(cn=wolke_app_bookmarks)(cn=wolke_apps_phonetrack)(cn=wolke_apps_rainloop)(cn=wolke_apps_deck)(cn=wolke_apps_keeweb)(cn=wolke_apps_news)(cn=wolke_apps_cookbook)(cn=wolke_apps_polls)(cn=wolke_apps_notes))s02ldap_group_filter_mode: 1s02ldap_group_member_assoc_attribute: gidNumbers02ldap_groupfilter_groups: wolke_app_bookmarks
wolke_apps_phonetrack
wolke_apps_rainloop
wolke_apps_deck
wolke_apps_keeweb
wolke_apps_news
wolke_apps_cookbooks02ldap_groupfilter_objectclass: s02ldap_host: authentix2.gallien.gals02ldap_login_filter: (&(&(|(objectclass=person))(|(memberof=cn=media_wolke,cn=groups,dc=gallien,dc=gal)))(uid=%uid))s02ldap_login_filter_mode: 0s02ldap_loginfilter_attributes: s02ldap_loginfilter_email: 0s02ldap_loginfilter_username: 1s02ldap_nested_groups: 0s02ldap_override_main_server: 0s02ldap_paging_size: 500s02ldap_port: 7389s02ldap_quota_attr: ownCloudQuotas02ldap_quota_def: s02ldap_tls: 0s02ldap_turn_off_cert_check: 0s02ldap_turn_on_pwd_change: 0s02ldap_user_display_name_2: s02ldap_user_filter_mode: 0s02ldap_userfilter_groups: media_wolkes02ldap_userfilter_objectclass: persons02ldap_userlist_filter: (&(|(objectclass=person))(|(memberof=cn=media_wolke,cn=groups,dc=gallien,dc=gal)))s02use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```
No error in Apaches error log
```
</details>

<details><summary>Nextcloud log</summary>

```
No log in NC Log
```
</details>

<details><summary>Browser log</summary>

No error in Browsers DevTools - Console
</details>

**Comment by reiner-text** [comment] 2020-06-05 15:11
Duplicate of #21239

**Closed** 2020-06-05 15:19 UTC
Labels: 0. Needs triage, bug
