### ISSUE TITLE
Fatal: Sabre\DAV\Exception\BadRequest

### ISSUE THREAD

**Issue by mwries** [nextcloud/server#6924] opened 2017-10-24 08:48 UTC
### Steps to reproduce
unknown

### Expected behaviour
no error

### Actual behaviour
I got dozens of Fatal errors.
many of these: Sabre\DAV\Exception\BadRequest: expected filesize 35840 got 16384
some of these: OCA\DAV\Connector\Sabre\Exception\FileLocked: "file_XXXX.xlsx" is locked

**Fata error: Sabre\DAV\Exception\BadRequest: expected filesize 100340 got 16384**

    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 151: OCA\DAV\Connector\Sabre\File->put(Resource id #9)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile('RfP LA Warehous...', Resource id #9)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('files/vdegast/T...', Resource id #9, NULL)
    [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Server.php - line 258: Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 162: require_once('/var/www/nextcl...')
    {main}

### General server configuration

**Operating system:** Linux nextcloud.systemsnavigator.com 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** pgsql PostgreSQL 9.5.9 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - redis
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - pdo_pgsql
 - pgsql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - smbclient
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install. By Daniel from Techandme

**Where did you install Nextcloud from:**  
fresh install. By Daniel from Techandme

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

<details>
        <summary>Content of config/config.php</summary>
available on request
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```

  | Sabre\DAV\Exception\BadRequest: expected filesize 10000000 got 131072/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 151:  OCA\DAV\Connector\Sabre\File->put(Resource id #9)/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 39:  OCA\DAV\Connector\Sabre\Directory->createFile('00000000', Resource id #9)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:  OCA\DAV\Upload\UploadFolder->createFile('00000000', Resource id #9)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525:  Sabre\DAV\Server->createFile('uploads/vdegast...', Resource id #9, NULL)[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method PUT', Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/apps/dav/lib/Server.php - line 258:  Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 33:  OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 162:  require_once('/var/www/nextcl...'){main}
-- | --

</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by mwries** [comment] 2017-10-24 08:48
cc @enoch85

**Comment by enoch85** [comment] 2017-10-24 09:06
@mwries Please Google `Sabre\DAV\Exception\BadRequest` and you will find loads of info. This is not server related nor VM related afaik.

It happens when the clients tries to sync. 

@MorrisJobke for the decision of closing or not.

**Comment by mwries** [comment] 2017-10-24 10:07
So when the client cannot sync, it gives a fatal error? Should that be the response? 
Files which are locked are not synced, but I do not expect an error for those cases.

**Comment by enoch85** [comment] 2017-10-24 18:00
It produces an error, but it's nothing to worry about. The cronjob takes care of the lock, and in the VM we use cron.php which is run every 15 minutes. So the lock should be released by then. 

It's a feature, not a bug. ;)

**Closed** 2017-10-25 14:45 UTC
