### ISSUE TITLE
External Nextcloud logo in html mail - phishing and  design problem - Base64 image directly in html email possible?

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#35418] opened 2022-11-25 07:35 UTC
I think e.g. the registration email is is not optimal from a **visual** and **safety** / **privacy** point of view. Look the picture (red box). Either the image is not loaded for security reasons or if it is loaded, it generates unnecessary log data on the nextcloud server.

https://i.imgur.com/MKnO9Cr.png

Maybe you can delete the external image. Maybe you can instead include a base64-image of the Nextcloud logo.

**Example:**

`<img src="data:image/jpeg;charset=utf-8;base64,<DATA>" alt="Description of the image" />`

**base64-code DATA of the standard Nextcloud logo (https://www.base64-image.de)**
` data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPwAAAB4CAMAAADhVG+bAAAC9FBMVEUAAAD///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////9JxXEjAAAA+3RSTlMAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzk6PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3Byc3R1dnd4eXp7fH1+f4CBgoOEhYaHiImKi4yNjo+QkZKTlJWWl5iZmpucnZ6foKGio6SlpqeoqaqrrK6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/lXTwOsAAAmzSURBVHgB7dsDfGRZwgXwUxW1EbVt2+4etHuM9ti2bduTcTJs20rbitpOx6pKne/b3drObzJJ5d5X9737FlXb/5993rsWzvu3OO88Z8MBk5/8KP73Bes2LJkXH/fa7aPaV8b/gvpjnppxlhUlx93VPwJBzNnjqZ00kDNjci0Epz6fnKRfRQsnVkKwqXHjJirK+Lgrgknsqzk0Y24/BIvopzJp1sqhCAbhj+TQit+aIuAN2UmL8p6qhIAW9RM1JA1AABtymFqK3w5DgAp9yk1dia0QkKKX0wZnRyAAtdpLW7jvRMC5IIN2eScEgeVyF+3zQ2jwf7tcQhgCxxUu2mtmBALFeDft9p0DgaFHDu33LP7tmo6+79N5iTvTDiZvmvf5Y2MbQ0GTY/xXuA4KGo997PN5m5MPpu1cP//T+0Y3hVW1J36RRh+Hv7y6BozV2EFl6emFVFU0BMaqX/3lYfpI+2JibZgWNiahgEJ58SOdMPAt/Stc/tqNg+tXhVdYVLcrH084Tv+OxkLOcVF8HoUKEkaHwozKdx6igb23RkBmKv05/OrwKhWyd7hzhYd+zHVCIvymPTRw8I7KUBV+33H6cWB6CITaZNNQ0bcjQiDW/InDNPYQhJxTUunH8XvCoGTIbirY0BMCIRtoJO+9JjAQcWMSjbg6Q6DLGirYOQj+1YijGver4ajgbhrwfFsPfoTcmk4Da5yCdbOLSjxfVocf3fZT2YZW8NEgi3I7B0NB7Jceyt0CH41XU9neLjB0fT5NSB+O8n6m3IeVoGZ8OqUy6qGc/idoQv40GHiS5rhuQFnDKJV5BZQ1XUupT1DWVYU053HION6gWZ57UMZyyhzrChMi4injboO/THLRrPecEPuQFtyDUiMps785TAn5mDLfodQ0D837AEJP0wrPJJSAYz0lkurCrHcpUdyxtG9w0YonIXAzrSka7K/gj7WAac4fKfENSnTPozU3oIJehbToREOcM4ti2V1hQfhiihWUTPFjDtCigh7wUSuFlq0KgVfzYopNhCWxRyn2KLwcs2hZUk2U9xM1PAyvlyn2OSwa4qbQoVB5I1XzA8q5mDoK2wPhpyi0vwqseoFiY4CG2dRxIcqonEQtC+W/bxQsq5xCoTgggVr2V8JfnqCmCfiEQr9Aw1gKZUQMoqZHUarGWWraHnaCIkXNoGMhhUYvp6Yz1fGnh2nIfXDHjoNuGnqXQl9DyxAK7VLIW0xDD6IEqpyk3MYHekXAK6LXA5toVnE76FlNszbc37Mkb+8HN1PuRGWUuJZS64agjCHraM4MaLqE5qwZhDKGJlLqKpSYR4msqxwox3F1Fs24DJrCz9CEzCt9816TTYnZOKe+m2LJHVFBx2Sqy6gMXR9SXVIHVNAphWKuksXW7RTbHwOBmP1U9hm09aeyvVHCvEkUuxle+JVCWR0h1DaDqq6AttBMKsrsYC5vPLxC0mXzFolLqcgTC30zqWgsJC6j0GkngO4UWgKpZVSzAza4l2oWms7bRX6+1BdSvT1U8jVsMIRKPH1M550I4EV5wWsW/aOwQX3tgpdtrD4n7e9uhIFbqORy2MCRpX96fytFfgawhSItYaAVlXSHHbZQRTMYaE2RjQBSKZABQ5lU0RzqNNtYOgxlUSAJwCkKbIKhzVRRB3aYQQXrLdSekwAK5P2d1BKqqAI7/KDd3wFLKZAPoIgCi2BoIVVUgh2+pYL5MLSIAoUAzlAgEYYSqSIadvidCtbA0HoKnAZwgAInYOgUVTSFHRZTwVEYOk2BVADbKVLXholHJ9hhA1XEwkADimyTnjJdDQMTqWQM7HBafwE5UbrN9Ib5LeffqeRe2CCSShJg4A+KvArgRooUtYBUyyIq+QQ26Eslhc0g1aqIItfL90p+gNSPVLMWNriZar6F1E8U6gcgIpcixb0g0cdDNa4a0Pcj1RT3MJk3Jxxe8ymUFguhqGSqGgltjuNUlBpjLu8cwOshii0Lh0D4cip7Hdo6U9niMFN57we82lFicRQqiFpMdYec0PU81S2MRAXRSyjR2s9kNakLfHRJphnDoMmZRhP2d4KPbin+JsS3U8b9WUOU0fAzN035CpoG0xTXJw1QRqMv3JS5FSWicimV99XIajin2siv82hSfj3o+Y0m5X15cVWcU21UXD6lckqbyJs04tr1x/ff/7HLRSOzKfQqtHT0UOQUjRSdy7vbRSNv4E8NCqjpYM1simRFQsd3FJq6i5ry66PUB9R0E+Ip9A409C6mSEHNK6jpXfwl6hS1bA/FVRRyd4NlzrUU+gOOpdRyOhpl3EAdngFA9VwKrXbCqlsoNhno7KKO6SjLuYoa3oPX53af27TNplBGNQAvUMMKB8ppdpaW7a0Crx4Ucw+EJZW3UewteIVvomXpTeFjgocW5XbFOesodrg+rPiSYp5WJfUikxZ5xqGC12jRRJSYQomttWDe05SYgxJji2nNK9Ib7hrPm8NTKbGsklZnJ1kv3E9LfnBCIHwBLfgIpaZTZmF1mHNbMSUWo9TLtGB+OISqL6JpnzhRKnQfZTbWgQmOZynVF6Ucb9K0hdXMv2qSecuBMq6lVHI3KKv6LaVm6D0L+jECUs63aYbrdpTjXEOp/FuhqNMuShV1QDnTC2nGG04YuTKTyo4Pg48uLsr91ggKwu7No9yL8NH/MJVlXAY/Wm2gojmCdvw6DeQ8GAZ/Bm6ngeTK8BX1CxUltoBfIXdmUMHJKQ5UVO0AjSTfGAEjfWd4aOQiCFx9lAoybg+BinpfuehH/puREBrkpqHDD9SDRPi4RTT2KYRqvppHP1xf1oWqFp8V0kDuh40UZmYS7rmTBO0lYvD7p+nH9sqQaPBeDg0UftocZjR8dA8ldj8YCbmQ5fTLs+PdyX1ql5Z42/GPLcyjX7ntIVf7vl3SvI80hGl9Xkp000fxhhe7w1ij41RzOnnDsgXrdx90Uc1UGOv64oZi+nAnvtQHFtUe+0jcupP59PIcXRf/6Mho+Ncnj/rk6xEjUSMfTUg8xn8qOJkY98jY2tAWVjuyKtRdWkz7xTuhrFpk7TD8p9xH262qjEDxDG22KQqB48EA+PYA+foNkQgsd7pplwU1EWguzKA9PglD4OmYRhu4H0RAiplJbUeGI1BNzqWeX6MRuDpuoYbsGxDQQu/KpFUzmiDQ1Yvz0Ip9FyIY9J1D09JuDkOQ6BrvoRlpd1VCEOn2YSYVeRZeGYYgU+36tR76d+zllghKsZNnFNBI8tvDQxG8qo98ak46BYo2vDe5KYKfo9XI2177ee2ulPR8T/rR5I3zP37oqt6Vcd555/0b/AM7Mg7c8zDu/gAAAABJRU5ErkJggg==`

**Comment by kesselb** [comment] 2022-11-25 21:52
Hi, closing as duplicate of https://github.com/nextcloud/server/issues/13557

**Closed by kesselb** 2022-11-25 21:52 UTC
Labels: enhancement, 0. Needs triage
