### ISSUE TITLE
[Bug]: Sharing Window doesnt close automatically

### ISSUE THREAD

**Issue by sec-consult** [nextcloud/server#46907] opened 2024-07-31 09:59 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In the current version of Nextcloud, it is easy to share information that should not be shared. The settings for the shares of a folder, which are displayed in the right half of the user interface in the web app, are also displayed when another folder is opened. From the user's point of view, it would be more logical for the settings window to close because you are in a different folder structure. 
Screenshots showing this behaviour can be found in the attachment.
The first screenshot shows the details of the ‘customer1’ folder. If you now open the ‘customer2’ folder from here, the share settings from the ‘customer1’ folder are still displayed, as can be seen in the second screenshot. This behaviour can lead to unintentional data protection violations.
![image](https://github.com/user-attachments/assets/257c5d05-881e-42f6-9866-e11e9dbd87dd)
![image](https://github.com/user-attachments/assets/adec785c-ecf1-436c-877c-906044a74faf)

### Steps to reproduce

1. Share a folder
2. open a different folder

### Expected behavior

"Sharing"-Window should close when anything else is clicked in the webapp

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment] 2024-08-02 00:32
Duplicate of https://github.com/nextcloud/server/issues/45061

**Closed by susnux** 2024-08-02 00:32 UTC
Labels: bug, 0. Needs triage, 28-feedback
