### ISSUE TITLE
[stable14.0.4] use the email address configured in Nextcloud as sender instead of the users email address

### ISSUE THREAD

**Issue by sburrey** [nextcloud/server#13211] opened 2018-12-21 10:59 UTC
Seems to be the same problem as #5303 because same issue persists with same steps to reproduce in NC 14.0.4

**Comment by sburrey** [comment] 2019-01-25 19:04
Same in 14.0.6

**Comment by skjnldsv** [comment] 2020-08-25 09:25
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:25 UTC
Labels: 0. Needs triage
