### ISSUE TITLE
Restrict autocompletion within same group not working

### ISSUE THREAD

**Issue by dsec-be** [nextcloud/server#21339] opened 2020-06-09 11:10 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create at least 10 users within a group (strangely in small groups, it seems to work)
2. Activate "Allow username completion in share dialog"
3. Activate "Restrict username autocompletion to users within the same groups"
4. Try autocompletion when sharing a folder (only the group name will be displayed)

### Expected behaviour
It should display a list of users in that group starting with the characters already typed

### Actual behaviour
Only group name is displayed. No users are listed.
Please note that in our configuration, all users of the group start with the name of that group.
i.e. Test (Group)
Users: Test_John, Test_Smith, Test_Joe, etc...

### Server configuration

**Operating system:**
Linux

**Web server:**
Apache 2.4

**Database:**
MariaDB 10

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)
19
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Nextcloud.com Official page & download
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Out of the box

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Out of the box
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
Latest stable Chrome & Firefox

**Operating system:**
Windows10

#### Web server error log
<details>
<summary>Web server error log</summary>
Nothing relevant
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Can be uploaded upon request
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Can be uploaded upon request
</details>

**Comment by dsec-be** [comment] 2020-06-10 10:52
Additionally unchecking "Allow resharing" does not disable the option to the users.

**Comment by szaimen** [comment] 2021-06-02 12:36
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 12:36 UTC
Labels: 0. Needs triage, bug
