### ISSUE TITLE
Clippy icon missing?

### ISSUE THREAD

**Issue by te-online** [nextcloud/server#7990] opened 2018-01-22 14:01 UTC
I'm not sure if this a bug or just a problem with my local set-up. I'm using NC 13 RC2 on a debian vm in Firefox.

### Steps to reproduce (Example)
1. Click on the share button for a folder / file
2. Check the checkbox to create a share link
3. Look at the URL box for the share link

### Expected behaviour
The clippy symbol is in the right corner of the url field, on hover it says “copy” and on click it copies the url into the clipboard and the popover text reads “copied”.

### Actual behaviour
The icon is missing.
![bildschirmfoto 2018-01-22 um 14 42 43](https://user-images.githubusercontent.com/4127167/35224213-8406f512-ff84-11e7-895f-4cefdb107db0.png)

Tried to re-clone (from git) already and also disabled all 3rd party apps.

Also, I would like to use the clipboard-icon in my own app, I simply added the `clipboardButton` class, but I hit several problems:

- In files_sharing: in NC13 RC2 the clipboard button is missing completely.
- In files_sharing: in NC12 everything works as expected.

- In my own app: in NC13 RC2 the pop-over works when clicking, but not when hovering.
- in my own app: in NC12 the pop-over doesn't work altogether

This is so confusing. If I'm the only one having this problem with NC13 RC2, I'll close this issue again, but I'm curious how it looks for you.

**Comment by MorrisJobke** [comment] 2018-01-22 17:13
cc @nextcloud/javascript

**Comment by danxuliu** [comment] 2018-01-23 05:01
The missing clipboard icon is a regression; I will take care of it.

**Comment by te-online** [comment] 2018-01-23 08:19
Thank you! 😊

While you are here, let me ask one question: Is it sufficient to add the .clipboardButton class to a link to add such button to my own app or will I need a separate script or other classes as well?

**Comment by MorrisJobke** [comment] 2018-01-24 11:17
@danxuliu Any ETA? Because this is the only one, that would block the very last RC before the 13.0.0 release and I would like to get the RC out today or tomorrow.

**Comment by danxuliu** [comment] 2018-01-24 16:08
@MorrisJobke
>   Any ETA? Because this is the only one, that would block the very last RC before the 13.0.0 release and I would like to get the RC out today or tomorrow.

Sorry for the delay; it is fixed in #8032 :-)

@te-online 
>  Is it sufficient to add the .clipboardButton class (and also the data-clipboard-target attribute, of course) to a link to add such button to my own app or will I need a separate script or other classes as well?

If I am not mistaken you would need to, at the very least, [create a `Clipboard` object](https://github.com/nextcloud/server/commit/daaa3ded8d73fe3e9eb483cbf1174ed245e6250b#diff-da7df34db49581af77bd59e4f269dc36R132). But you should handle the `success` event too to give feedback to the user ;-)

**Closed** 2018-01-24 16:27 UTC
Labels: bug, regression

**Comment by te-online** [comment] 2018-01-30 09:46
@danxuliu Thank you! It was very hard for me to get the tooltip working, because I couldn't find any documentation (is it Bootstrap-js?). I ended up configuring the tooltip in the render function of my filetabview. Don't know if that's correct, but otherwise the elements were not available in the DOM and it seems you can't configure a tooltip for an element that will be added later.

Aside from that, I can confirm the clipboard icon for sharing works again in RC3. 🎉
