### ISSUE TITLE
[Bug]: open shared folder doesn't work

### ISSUE THREAD

**Issue by David-Rodriguez-cabrera** [nextcloud/server#39565] opened 2023-07-25 07:16 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

First of all, sorry for my English, I'm using a translator.
If I share a folder and try to open it from shared with me, shared with others...
The url fails, investigating on my own I noticed that in the html of that part the data-path was empty, and in the normal menu it has '/' set, which is how I have it configured.
Since f12 I put data-path="/" to a folder and I was able to enter it.
So there is a bug with the path of the shared folders opened from shares.
This does not happen with files.

### Steps to reproduce

1.Share folder.
2.Move to shared.
3.Open shared folder from there.
4.See that the All Files menu opens.

### Expected behavior

Wait for me to open the shared folder.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
root@next04t:~# sudo -u www-data php  /var/www/nextcloud/occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "###################"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.1.2",
        "overwrite.cli.url": "https:\/\/#######\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "htaccess.RewriteBase": "\/",
        "default_phone_region": "ES",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpdebug": true,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpstreamoptions": {
            "ssl": {
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "logtimezone": "Europe\/Madrid",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "logfile_audit": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "tempdirectory": "\/nextcloud-datos\/tmp\/",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "skeletondirectory": "",
        "force_language": "es",
        "force_locale": "es_ES",
        "allow_user_to_change_display_name": false,
        "account_manager.default_property_scope": {
            "displayname": "v2-local",
            "email": "v2-local",
            "avatar": "v2-local",
            "address": "v2-private",
            "website": "v2-private",
            "phone": "v2-private",
            "twitter": "v2-private",
            "fediverse": "v2-private",
            "organisation": "v2-private",
            "role": "v2-private",
            "headline": "v2-private",
            "biography": "v2-private"
        },
        "profile.enabled": false,
        "auth.webauthn.enabled": false,
        "maintenance": false,
        "loglevel": 2,
        "share_folder": "received_shares"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - auto_groups: 1.5.2
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.0
  - files_automatedtagging: 1.17.0
  - files_pdfviewer: 2.8.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - group_default_quota: 0.1.7
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - socialsharing_email: 2.6.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_admin: 4.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_email: 2.7.3
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - encryption: 2.15.0
  - files_external: 1.19.0
  - firstrunwizard: 2.16.0 (installed 2.16.0)
  - suspicious_login: 5.0.0
  - user_ldap: 1.17.0
  - weather_status: 1.7.0 (installed 1.7.0)
```

**Comment by th0rgall** [comment] 2023-09-18 10:13
Hey, I had a problem with a similar reproduction:
1. Log in with account A (`admin`, in my case), open the Files app. In another incognito window, log in with account B; open the Files app.
2. Share a folder from account A with account B.
3. On account B, open "Shared with you".
4. Try to open the shared folder from there.
5. **Problem**: now the All Files menu opens (it looks like it redirected).

I worked around this issue by logging out out of account B, and logging in again. I can now access the shared folder as expected. I'm not sure if a page refresh would have accomplished the same.

**Comment by ZID-TU-Graz** [comment] 2023-09-21 09:09
We noticed the same problem here. V27.1.0

**Comment by Antreesy** [comment] 2023-09-28 15:55
Observed at 26.0.7 by customer after major update, so seems to work fine until v25 inclusively

**Comment by ShGKme** [comment] 2023-09-29 13:11
Cannot reproduce on 27.0.2 (Nextcloud AIO v7.0.0)

**Comment by ShGKme** [comment] 2023-09-29 13:25
UPD: can reproduce, it happens randomly, but more likely when I open the shared directory "fast" after switching from another directory. The shared folder is open, but files are listed from the root.

Sometimes I can see root files for a second before the real shared folder content is shown.

**Comment by ShGKme** [comment] 2023-11-14 13:47
Fixed by https://github.com/nextcloud/server/pull/41206

**Closed by ShGKme** 2023-11-14 13:47 UTC
Labels: bug, feature: sharing, 0. Needs triage, 26-feedback
