### ISSUE TITLE
GUI says "Unlimited" when default quota is actually 0

### ISSUE THREAD

**Issue by paualberto** [nextcloud/server#14740] opened 2019-03-18 16:47 UTC
### Steps to reproduce
1. `occ config:app:set files default_quota --value "0 B"`

### Expected behaviour
New users are created with zero quota.  
Default quota is displayed as "none" or "0B"

### Actual behaviour
New users are created with zero quota.  
Default quota is displayed as "Unlimited"

### Server configuration

**Operating system**: Ubuntu Server 18.04

**Web server:** Apache/2.4.29 (Ubuntu)

**Database:** MariaDB 8.0.13

**PHP version:** PHP 7.2.15-0ubuntu0.18.04.1 (fpm-fcgi)

**Nextcloud version:** 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-15.0.5.zip

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_saml: 2.1.1
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - theming
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwriteprotocol": "https",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "quota_include_external_storage": true,
        "htaccess.RewriteBase": "\/",
        "memcache.distributed": "OC\\Memcache\\Redis",
        "memcache.local": "OC\\Memcache\\Redis",
        "memcache.locking": "OC\\Memcache\\Redis",
        "logfile": "\/var\/log\/nextcloud.log",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "***REMOVED SENSITIVE VALUE***",
                "region": "us-east-2",
                "autocreate": false,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "use_ssl": true
            }
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Gsuite/SAML

**Browser:** Firefox 65.0.1

**Operating system:** Ubuntu 18.04

### Logs
This produces no error.

### Additional details
When setting 0 as default quota, "none" is correctly displayed, but after a page reload, it becomes "Unlimited". 
Having read-only users by default is a really useful feature, so please try to not fix this by enforcing Unlimited, thanks! :smile:

**Comment by skjnldsv** [comment] 2019-04-30 08:23
![Capture d’écran_2019-04-30_10-23-10](https://user-images.githubusercontent.com/14975046/56948962-05b81e00-6b32-11e9-94e6-af06283abe56.png)
![Capture d’écran_2019-04-30_10-23-32](https://user-images.githubusercontent.com/14975046/56948964-05b81e00-6b32-11e9-8208-edfa86b923fe.png)

Cannot reproduce

**Comment by paualberto** [comment] 2019-04-30 08:30
> ![Capture d’écran_2019-04-30_10-23-10](https://user-images.githubusercontent.com/14975046/56948962-05b81e00-6b32-11e9-94e6-af06283abe56.png)
> ![Capture d’écran_2019-04-30_10-23-32](https://user-images.githubusercontent.com/14975046/56948964-05b81e00-6b32-11e9-8208-edfa86b923fe.png)
> 
> Cannot reproduce

Have you refreshed the page? (in the second screenshot)

**Comment by skjnldsv** [comment] 2019-04-30 08:41
@paualberto yes :)
You were talking about the users management, right?

As admin or subadmin?

**Comment by paualberto** [comment] 2019-04-30 08:42
Yes, I'm talking about users management as admin. That's weird...

**Comment by skjnldsv** [comment] 2019-04-30 08:47
@paualberto for you it says 'none'?

**Comment by paualberto** [comment] 2019-04-30 08:50
It said "Unlimited" but the quota was 0B for the user and in the DB. Now I installed NC on another server, so I'll try with the new setup soon. Thanks!

**Comment by skjnldsv** [comment] 2019-04-30 09:01
Then I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-04-30 09:01 UTC
Labels: 0. Needs triage, bug, needs info

**Comment by skjnldsv** [comment] 2019-05-03 11:29
Hey @paualberto 
It seems someone else was able to reproduce your bug!
A fix have been provided here https://github.com/nextcloud/server/pull/15359 :)
