### ISSUE TITLE
Focus on foldername_textbox when creating a new folder

### ISSUE THREAD

**Issue by GHBLoos** [nextcloud/server#44937] opened 2024-04-19 17:26 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I create a new folde by clicking in the menu, and then I have to click the textbox on the pop-up before I can type a foldername. 

**Describe the solution you'd like**
After creating a new folder, the textbox in the pop-up should have the focus, so I can directly type the name of the folder

**Describe alternatives you've considered**
Maybe even better is If you can type the new folder name in the menu-item

**Additional context**
![image](https://github.com/nextcloud/server/assets/16174035/ab83e163-d75f-41d7-a301-8359a2a5cd8b)
Creating a new folder

![image](https://github.com/nextcloud/server/assets/16174035/9c0e2b95-c4a5-432d-b916-f1b9ee2f021c)
Focus should be in the textbox, so you can start typing the folder name directly instead of first clicking the textbox to give it the focus to type.

**Comment by solracsf** [comment] 2024-04-19 17:53
Duplicate of https://github.com/nextcloud/server/issues/43659
If not fixed by that patch, comment on that issue.

**Closed by solracsf** 2024-04-19 17:53 UTC
Labels: enhancement, 0. Needs triage
