### ISSUE TITLE
NC should send out RSVPs to calendar invites from an own mailbox and receive the responses directly

### ISSUE THREAD

**Issue by dphi** [nextcloud/server#10490] opened 2018-08-01 22:40 UTC
Scheduling appointments via NC using the calendar app is not possible today because responses are not reaching NC. This situation will slightly improve in NC14 with the RSVPs buttons in the invitation but this won't work for participants relying on iMip, esp. Exchange+Outlook users.

If NC would send out invitations and receive the responses directly it could manage the participants RSVP status in-depended of external SMTP and CalDav clients.

What should be considered is how RSVPs with comments can be handled best. These should reach CalDav (if possible?) and the mailbox of the inviting user.

**Comment by lopezio** [comment] 2018-08-22 09:32
+1 I second this. At the moment, using NC with Mac/IOS PIMs is very cool for the most part, but when it comes to invitations, it's really a mess. I'm not sure who's fault it is (and I suppose, in doubt, it's Apple's fault), but this idea came to my mind too. NC could monitor an IMAP account and process incoming replies. I'm available to help coding and testing this thoroughly.

**Comment by georgehrke** [comment] 2019-09-11 08:12
Duplicate of https://github.com/nextcloud/server/issues/5080

**Closed by georgehrke** 2019-09-11 08:12 UTC
Labels: 0. Needs triage, enhancement, feature: dav

**Comment by rinurinu** [comment] 2021-09-29 12:13
@georgehrke This does not seem to be a duplicate of #5080. In the mentioned ticket the issue is about invitations being **sent out** by a certain e-mail adress. This issue here is about Nextcloud not handling responses from participants if they are coming back through e-mail.

First of all I appreciate everybodys work on this, and the calendar app is awesome. It's not that intuitive that the Calendar app is able to send out invitations but does not care about responses back. Through the way this feature works in Google Calendar and Outlook/Exchange, one assumes that the calendar app takes care of responses by itself.
Also currently there does not seem to be a way to even manually get the information from response e-mails ("Accepted: [Event Title]" and attached .ics file) from participants back to the server.

So the desired result would be, that Nextcloud server handles the responses via email and refreshes the participants state (accepted / declined) according to the behaviour of similar services like Exchange or Google Calendar. It would be great if you could open the issue again.

Is there any way one can help to advance this issue without being able to develop?

**Comment by marvin-te** [comment] 2023-06-26 07:14
Why is this ticket ignored so heavily?

Like @rinurinu pointed out almost 2 years ago, this ticket is NOT a duplicate of #5080. @georgehrke could you please reevaluate this issue? This is a real thing ppl would like to use. 

Currently I have to explain to every single person I send an invitation to, that they need to use the links instead of the dedicated buttons they are used to by their mail client...

**Comment by abctaylor** [comment] 2025-01-10 16:49
It's a hard problem to solve. I can only think of two ways:

1. the "reply-to" address of the email sent by Nextcloud is not the user's real email, but something like `reply_<uuid>@nextcloud.example.com`. nextcloud.example.com is not the user's top domain, but a special domain whose MX points directly to Nextcloud. The user can continue using whatever mail server they currently have (Dovecot, etc)
2. Nextcloud directly integrates via IMAP to the user's mailbox and polls for .ics attachments, extracting them directly.
3. Someone who cares enough, like me or you, writes a script to fix this.

I wonder if the Nextcloud team realises this is a fairly major shortfall that is no doubt stopping many enterprise users from using the platform more seriously. Exchange is light years ahead on all this stuff and it isn't that hard to make this work. Nobody seems to care enough.

I might make an async Python script that attaches to a Dovecot mail server impersonating the user, and updates Nextcloud with RSVP information because I'm not totally impressed with how this issue has been ignored. But I can't be a FOSS user just moaning without doing anything. Would anyone else like something like this? I'm sure we could make it happen.
