### ISSUE TITLE
Unable to rename read-only folder shared with me

### ISSUE THREAD

**Issue by RobinR1** [nextcloud/server#16458] opened 2019-07-18 13:44 UTC
### Steps to reproduce
1. Make another user share a folder with you, remove al rights to re-share and change
2. Try to rename the shared folder from your own account

### Expected behaviour
As noted in #8628, the user should be able to rename a shared folder to a personalized foldername.

### Actual behaviour
Small notification: Could not rename folder "name"

### Server configuration

**Operating system**: openSuse Leap 15.1

**Web server:** Apache 2.4.33

**Database:** MySQL 14.14

**PHP version:** 7.2.5

**Nextcloud version:** (see Nextcloud admin page) 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**  default opensuse software repositories

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.4.0
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.3
  - cospend: 0.1.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.1
  - metadata: 0.9.0
  - music: 0.9.5
  - nextcloud_announcements: 1.4.0
  - notes: 3.0.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.11.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***PRIVATE***",
            "***PRIVATE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "***PRIVATE***",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mysql.utf8mb4": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```+-------------------------------+---------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                   |
+-------------------------------+---------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                     |
| homeFolderNamingRule          |                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                     |
| ldapAgentName                 | cn=Administrator,dc=***,dc=***                                                    |
| ldapAgentPassword             | ***                                                                                   |
| ldapAttributesForGroupSearch  |                                                                                       |
| ldapAttributesForUserSearch   |                                                                                       |
| ldapBackupHost                |                                                                                       |
| ldapBackupPort                |                                                                                       |
| ldapBase                      | dc=***,dc=***                                                                      |
| ldapBaseGroups                | ou=group,dc=***,dc=***                                                             |
| ldapBaseUsers                 | ou=people,dc=***,dc=***                                                            |
| ldapCacheTTL                  | 600                                                                                   |
| ldapConfigurationActive       | 1                                                                                     |
| ldapDefaultPPolicyDN          |                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                       |
| ldapEmailAttribute            | mail                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                                       |
| ldapExpertUUIDUserAttr        |                                                                                       |
| ldapExpertUsernameAttr        |                                                                                       |
| ldapGidNumber                 | gidNumber                                                                             |
| ldapGroupDisplayName          | cn                                                                                    |
| ldapGroupFilter               |                                                                                       |
| ldapGroupFilterGroups         |                                                                                       |
| ldapGroupFilterMode           | 0                                                                                     |
| ldapGroupFilterObjectclass    |                                                                                       |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                          |
| ldapHost                      | ***                                                                    |
| ldapIgnoreNamingRules         |                                                                                       |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                       |
| ldapLoginFilterEmail          | 1                                                                                     |
| ldapLoginFilterMode           | 0                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                     |
| ldapNestedGroups              | 0                                                                                     |
| ldapOverrideMainServer        |                                                                                       |
| ldapPagingSize                | 500                                                                                   |
| ldapPort                      | 389                                                                                   |
| ldapQuotaAttribute            |                                                                                       |
| ldapQuotaDefault              |                                                                                       |
| ldapTLS                       | 0                                                                                     |
| ldapUserAvatarRule            | default                                                                               |
| ldapUserDisplayName           | cn                                                                                    |
| ldapUserDisplayName2          |                                                                                       |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                        |
| ldapUserFilterGroups          |                                                                                       |
| ldapUserFilterMode            | 0                                                                                     |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                  |
| turnOffCertCheck              | 0                                                                                     |
| turnOnPasswordChange          | 0                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                     |
+-------------------------------+---------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** openSuse Leap 15.0

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing relevant
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing relevant
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing relevant
```
</details>

**Comment by clawoflight** [comment] 2019-09-10 12:16
I concur. This is how e.g. Google Drive does it.
In fact, I should be able to *move* a shared folder somewhere else in the hierarchy in addition to renaming it.

**Comment by karamanolev** [comment] 2020-02-12 19:51
Experiencing the same issue. Moving it, as mentioned by @clawoflight already works, however renaming doesn't.

Since renaming a folder that was shared with you only affects your "copy", it shouldn't require permissions to be given on the share. Only you need to have permissions over the location.

**Comment by skjnldsv** [comment] 2020-04-10 11:35
@kesselb @rullzer @nickvergessen don't we already have an issue about this somewhere? I think I remember a discussion about moving shared folders and editing them?

**Comment by karamanolev** [comment] 2020-05-10 18:55
Hey bot, this is not stale! It's still happening.

**Comment by kesselb** [comment] 2020-05-10 19:14
@skjnldsv https://github.com/nextcloud/server/issues/2063 maybe? But that seems to be the opposite ;)

**Comment by karamanolev** [comment] 2020-06-09 20:12
@nextcloud-bot It continues to not be stale. The steps to reproduce are clear...

**Comment by afics** [comment] 2021-06-15 09:00
This is still relevant. Any news on how to proceed?

**Comment by szaimen** [comment] 2023-01-09 14:54
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:39 UTC
Labels: bug, needs info, 0. Needs triage
