### ISSUE TITLE
nextcloud 16.0.3: Image upload to files: TypeError: Argument 5 passed to OC\Core\Controller\PreviewController::__construct() must be of the type string, null given

### ISSUE THREAD

**Issue by stefan-schilling** [nextcloud/server#16749] opened 2019-08-15 14:03 UTC
Uploading images fails quite often, so users switch to upload just a couple per time. It finally works, but they have to retry several times.

### Steps to reproduce
1. Upload images (say: 20 at a time?) to nextcloud
2. check log file
3.

### Expected behaviour
Images get uploaded without any trouble

### Actual behaviour
Upload gets aborted, log file contains many entries such as:

[index] Error: TypeError: Argument 5 passed to OC\Core\Controller\PreviewController::__construct() must be of the type string, null given at <<closure>>

 0. <<closure>>
    OC\Core\Controller\PreviewController->__construct("core", OC\AppFramework\Http\Request {}, OC\PreviewManager {}, OC\Files\Node\LazyRoot {}, null, OC\AppFramework\Utility\TimeFactory {})
 1. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 81
    ReflectionClass->newInstanceArgs(["core",OC\AppFr ... }])
 2. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 98
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 3. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OC\\Core\\Controller\\PreviewController")
 4. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 409
    OC\AppFramework\Utility\SimpleContainer->query("OC\\Core\\Controller\\PreviewController")
 5. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 382
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OC\\Core\\Controller\\PreviewController")
 6. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/App.php line 113
    OC\AppFramework\DependencyInjection\DIContainer->query("OC\\Core\\Controller\\PreviewController")
 7. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Controller\\PreviewController", "getPreviewByFileId", OC\AppFramework\ ... {}, {_route: "core.P ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.P ... "})
 9. /kunden/153079_80335/webseiten-cloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "core.P ... "})
10. /kunden/153079_80335/webseiten-cloud/lib/base.php line 975
    OC\Route\Router->match("/core/preview")
11. /kunden/153079_80335/webseiten-cloud/index.php line 42
    OC::handleRequest()

GET /index.php/core/preview?fileId=916&x=1440&y=761&a=true
from 2001:a61:2565:6001:e84e:c2fe:746a:9898 at 2019-08-15T13:35:19+00:00

### Server configuration

**Operating system**:
Linux something (shared environment, no root access)

**Web server:**
Apache 2.x

**Database:**
MySQL 5.6.19

**PHP version:**
7.7.2

**Nextcloud version:** (see Nextcloud admin page)
16.0.3 (now updated to 16.0.4)

**Updated from an older Nextcloud/ownCloud or fresh install:**
used to be a fresh 16.0.3 install

**Where did you install Nextcloud from:**
nextcloud?

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - occweb: 0.0.4
  - password_policy: 1.6.0
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_antivirus
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.yyy.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.3.1",
        "overwrite.cli.url": "https:\/\/xxx.yyy.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "tempdirectory": "\/kunden\/153079_80335\/webseiten-cloud-tmp",
        "app_install_overwrite": [
            "occweb"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 68.0.2 (64-Bit), Opera 62.0.3331.116, Chrome 76.0.3809.100 (Offizieller Build) (64-Bit)

**Operating system:**
Windows 10 / MAC

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
[index] Error: TypeError: Argument 5 passed to OC\Core\Controller\PreviewController::__construct() must be of the type string, null given at <<closure>>

 0. <<closure>>
    OC\Core\Controller\PreviewController->__construct("core", OC\AppFramework\Http\Request {}, OC\PreviewManager {}, OC\Files\Node\LazyRoot {}, null, OC\AppFramework\Utility\TimeFactory {})
 1. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 81
    ReflectionClass->newInstanceArgs(["core",OC\AppFr ... }])
 2. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 98
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 3. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
    OC\AppFramework\Utility\SimpleContainer->resolve("OC\\Core\\Controller\\PreviewController")
 4. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 409
    OC\AppFramework\Utility\SimpleContainer->query("OC\\Core\\Controller\\PreviewController")
 5. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 382
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OC\\Core\\Controller\\PreviewController")
 6. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/App.php line 113
    OC\AppFramework\DependencyInjection\DIContainer->query("OC\\Core\\Controller\\PreviewController")
 7. /kunden/153079_80335/webseiten-cloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Controller\\PreviewController", "getPreviewByFileId", OC\AppFramework\ ... {}, {_route: "core.P ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.P ... "})
 9. /kunden/153079_80335/webseiten-cloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "core.P ... "})
10. /kunden/153079_80335/webseiten-cloud/lib/base.php line 975
    OC\Route\Router->match("/core/preview")
11. /kunden/153079_80335/webseiten-cloud/index.php line 42
    OC::handleRequest()

GET /index.php/core/preview?fileId=916&x=1440&y=761&a=true
from 2001:a61:2565:6001:e84e:c2fe:746a:9898 at 2019-08-15T13:35:19+00:00
</details>

#### Browser log
<details>
<summary>Browser log</summary>

sorry, upload was done by another user
</details>

**Comment by kesselb** [comment] 2019-08-15 14:13
@rullzer you fixed this with https://github.com/nextcloud/server/pull/16571?

**Comment by stefan-schilling** [comment] 2019-08-15 14:18
@kesselb @rullzer Please note: the users are logged into the system / navigating to another page within Nextcloud does not require login credentials. I tried it myself, too.

**Comment by kesselb** [comment] 2019-08-15 14:49
> Please note: the users are logged into the system / navigating to another page within Nextcloud does not require login credentials. I tried it myself, too.

The controller is initialized with null as userid. So this error should be fixed with the patch above. The user state is done at a later stage (after initializing the controller but before the action). 

`OC\Core\Controller\PreviewController->__construct("core", OC\AppFramework\Http\Request {}, OC\PreviewManager {}, OC\Files\Node\LazyRoot {}, null, OC\AppFramework\Utility\TimeFactory {})`

Mind to try the patch? We may backport it to 16.0.5.

**Comment by stefan-schilling** [comment] 2019-08-15 15:04
Alright - what do I need to do?

**Comment by kesselb** [comment] 2019-08-15 15:12
https://github.com/nextcloud/server/pull/16571/files change the code like suggested there and check the logs ;)

**Comment by stefan-schilling** [comment] 2019-08-15 15:27
Alright, I renamed the original file and replaced it by the version of PR 16571.

Upload worked for a couple of pictures, but then this message appeared in the upper part of the browser:
Cannot authenticate over ajax calls

Any ideas?
![errorMessage - 2019-08-15](https://user-images.githubusercontent.com/27948730/63105865-f2ff1300-bf81-11e9-8195-75d2f9784883.PNG)

**Comment by rullzer** [comment] 2019-08-15 19:14
If the users are authenticated then something else is going on.
As you can see the message on the top says that authentication fails.

So something else is going on that causes this.
We'll have to figure out why the auth fails for some of the ajax calls...

**Comment by phpbg** [comment] 2019-08-26 14:22
Hi,
I'm experiencing this bug on 16.0.4 too

**Comment by kesselb** [comment] 2019-08-27 10:45
> https://github.com/nextcloud/server/pull/16571/files change the code like suggested there and check the logs ;)

@phpbg Mind to try the patch? We may backport it to 16.0.5.

**Comment by phpbg** [comment] 2019-08-27 18:28
Hi,
I can't reproduce the bug yet.
I only see it happens from times to times in the logs.
I'll test the patch if I can reproduce it.

Anyway, patch looks good, but you forgot to remove `@param ITimeFactory $timeFactory` from PHPDoc: https://github.com/nextcloud/server/blob/caf32d25f8635c86ed9c230dc495a4cf6afbfe3a/core/Controller/PreviewController.php#L59

**Comment by snhrdt** [comment] 2019-10-31 13:37
I experience the same on NC 15, see here: https://help.nextcloud.com/t/no-more-access-via-browser-exception-in-nextcloud-log/63150 . Thanks for any help.

**Comment by Ko-** [comment] 2019-11-26 08:09
I got the same TypeErrors on Nextcloud 16.0.3. PR #16571 fixes it for me. No issues about Ajax calls not being able to authenticate or anything.

**Comment by kesselb** [comment] 2020-02-02 19:45
Should be fixed by #16571

**Closed by kesselb** 2020-02-02 19:45 UTC
Labels: 0. Needs triage, bug
