### ISSUE TITLE
Open chat link on Settings > Support goes directly to Riot.im

### ISSUE THREAD

**Issue by Half-Shot** [nextcloud/server#13419] opened 2019-01-07 21:44 UTC
Hiya, quite a few users get stuck on reaching Nextcloud's Matrix bridged room because the Riot link will not work properly if they are not logged in. We would suggest that projects trying to link to a Matrix room should use `matrix.to` instead because it allows users to pick a client (from a list of suggestions) as well as telling them which room they are actually joining.

### Steps to reproduce
1. Click Support
2. Click "Open chat"

### Expected behaviour
Should take you to https://matrix.to/#/#freenode_#nextcloud:matrix.org

### Actual behaviour
Takes users directly to Riot.im, where they will be prompted to create an account/log in and find themselves unable to remember which room they were joining.

**Comment by MorrisJobke** [comment] 2019-01-07 23:10
cc @jancborchardt

**Comment by jancborchardt** [comment] 2019-01-09 01:46
@Half-Shot hi! First off, thanks a lot for working on Matrix! :rocket: 

The core of this problem seems to be a duplicate of https://github.com/nextcloud/firstrunwizard/issues/87 where @ara4n and @lampholder were involved in the discussion and it was said to be fixed according to @lampholder at https://github.com/nextcloud/firstrunwizard/issues/87#issuecomment-449341675 :slightly_smiling_face: 


Also for the record, an excerpt from this about [my thoughts on linking to matrix.to](https://github.com/nextcloud/firstrunwizard/issues/87#issuecomment-438020042):

>> but I would HIGHLY encourage you to link to both an IRC web chat and then if someone is already a Matrix user they can click a link to be taken to Matrix (probably though a link more like https://matrix.to/#/#freenode_#nextcloud:matrix.org instead of just linking straight to Riot).
>
> Sorry but this is just too convoluted for anyone but programmers. This matrix.to page does not look very inviting and offers a large amount of choice which is not relevant to general users. We want to make this accessible to normal people, and IRC webchat is a huge step down.



(We also had a meeting with some Open Source Design people and @benparsons at 35C3 where we talked about how to improve the UX of Matrix.to among other things. :) Short version: Simplify, and offer 1 good solution depending on whichever platform the site is accessed by.)

**Closed by jancborchardt** 2019-01-09 01:46 UTC
Labels: 0. Needs triage, bug

**Comment by Half-Shot** [comment] 2019-01-09 02:50
Ugh, yes you are totally right. This was reported by someone in our community and I hadn't noticed https://github.com/nextcloud/firstrunwizard/issues/87. There are still some issues so I shall go chase it up Riot-side.

**Comment by jancborchardt** [comment] 2019-01-09 19:00
@Half-Shot no worries! We love Riot (and Matrix too) and like to link people to using that. :slightly_smiling_face: 

Just out of interest: Are you seeing an increase in signups specifically coming referred from Nextcloud domains or installations? Also, we are always interested in more integration like connecting accounts for file picking, sharing, file saving, etc etc. – we could talk at FOSDEM, here, or we have a lot of our developers hanging out in #nextcloud-dev :)
