### ISSUE TITLE
Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#16526] opened 2019-07-24 10:14 UTC
I would like to bring to the attention of programmers bugs found in the various nextcloud versions, and returned to the clean installation of nextcloud 16.0.3.

I hope for a resolution thanks

old disussion url

https://github.com/nextcloud/server/issues/8546

**Comment by kesselb** [comment] 2019-07-24 10:57
Duplicate of #8546

**Closed by kesselb** 2019-07-24 10:57 UTC
Labels: 0. Needs triage, bug
