### ISSUE TITLE
[Bug]: "add group" in user management doesn't work

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#38846] opened 2023-06-15 20:35 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I can't add a new group in the user management

### Steps to reproduce

1. go to the user management
2. click on "add group" on the left sidebar
3. enter a name for the new group
4. press enter or click the "arrow"-button
5. nothing happens

### Expected behavior

I would expect that the new group shows up in the list of groups on the left sidebar

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment] 2023-06-15 20:43
Hi, this should be fixed with 27.0.1

**Comment by AndyScherzinger** [comment] 2023-06-19 13:25
Seems there is no single network call when hitting the submit button, so seems to be a web-frontend issue

**Closed** 2023-06-19 13:34 UTC
Labels: bug, needs info, 0. Needs triage, 27-feedback

**Comment by abdulklf** [comment] 2023-07-09 05:50
Related bug:

Steps to reproduce:
1. go to the “Administration settings”
2. go to the “Group folders”. 

you cannot add a new “shared folder”, when you enter the name of the shared folder, nothing happened..

if you don’t have a "Group folders" in the navigation menu, you can download it from the Apps section…

**Comment by AndyScherzinger** [comment] 2023-07-10 07:49
@abdulklf can you please raise this in a new ticket? I just tested 27.0.0 and it works just fine creating new group folders.
