### ISSUE TITLE
Argument 1 passed to OC\Core\Controller\LoginController::tryLogin() must be of the type string, null given, called in[Bug]: 

### ISSUE THREAD

**Issue by wangjueszu** [nextcloud/server#35532] opened 2022-12-01 07:06 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This problem occurred last night. Some accounts could not be logged in, and error 504 was displayed.
At 12 o'clock this afternoon, I was able to log in again.
I was worried that I would suddenly be unable to log in.
Operating environment: QNH DM7.0
Installation: Apache
Version: 25.0.1

### Steps to reproduce

Exception: Argument 1 passed to OC\Core\Controller\LoginController::tryLogin() must be of the type string, null given, called in /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/volume1/web/nextcloud/core/Controller/LoginController.php' line 298
0. /volume1/web/nextcloud/lib/private/AppFramework/App.php - line 172:OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "tryLogin")
1. /volume1/web/nextcloud/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main("OC\\Core\\C ... r", "tryLogin", OC\AppFramew ... {}, [ "core.login.tryLogin"])
2. /volume1/web/nextcloud/lib/base.php - line 1047:OC\Route\Router->match("/login")
3. /volume1/web/nextcloud/index.php - line 36:OC::handleRequest()

Caused by TypeError: Argument 1 passed to OC\Core\Controller\LoginController::tryLogin() must be of the type string, null given, called in 
0. /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225
1. /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:OC\Core\Controller\LoginController->tryLogin("*** sensiti ... *")
2. /volume1/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Cont ... {}, "tryLogin")
3. /volume1/web/nextcloud/lib/private/AppFramework/App.php - line 172:OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "tryLogin")
4. /volume1/web/nextcloud/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main("OC\\Core\\C ... r", "tryLogin", OC\AppFramew ... {}, [ "core.login.tryLogin"])
5. /volume1/web/nextcloud/lib/base.php - line 1047:OC\Route\Router->match("/login")/volume1/web/nextcloud/index.php - line 36:OC::handleRequest()

### Expected behavior

In order to prevent the problem from happening again, I hope it can be solved.
Or, I'll study how to make an overall backup of nextcloud.

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
You are currently running 7.3.3. Please update your PHP version

Unable to execute, as prompted above.
The prompt is the same when PHP 7.3 is uninstalled and PHP 7.4 is installed.
```

**Comment by solracsf** [comment] 2022-12-02 08:23
Duplicate of https://github.com/nextcloud/server/issues/23063

**Closed by solracsf** 2022-12-02 08:23 UTC
Labels: bug, 0. Needs triage, 25-feedback
