### ISSUE TITLE
ReferenceError: Can't find variable: Files in file picker outside of files app

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#14834] opened 2019-03-25 12:57 UTC
* open personal settings
* choose the "choose from files" for the avatar
* clicking the "->" results in `ReferenceError: Can't find variable: Files`

![Bildschirmfoto 2019-03-22 um 11 45 28](https://user-images.githubusercontent.com/245432/54817790-0ab6c180-4c98-11e9-9117-436960961869.png)

**Comment by MorrisJobke** [comment] 2019-03-25 12:58
@rummatee @nextcloud/javascript

**Comment by rummatee** [comment] 2019-03-26 15:34
The problem is, that in this situation the Files app isn't available. It is used to check that the folder name is valid.
Maybe the best solution would be to hide the new-folder-button for choose-type file picker?
I think in case of copy and/or move, the Files app is needed anyway so it would be sensible to assume that it is available and in the case of choose it doesn't really make sense to create a new folder anyways.
Would it be enough to hide the button, or should it be removed from the html?

**Comment by MorrisJobke** [comment] 2019-03-26 16:45
> Would it be enough to hide the button, or should it be removed from the html?

Hiding should be enough :+1:

**Comment by danxuliu** [comment] 2019-04-02 07:36
Fixed in #14900

**Closed by danxuliu** 2019-04-02 07:36 UTC
Labels: 16-feedback, 3. to review, bug
