### ISSUE TITLE
"Trying to access array offset on value of type bool at /lib/private/Files/Storage/Wrapper/Encryption.php#441" in remote.php, either with PUT and DELETE

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/server#27096] opened 2021-05-25 08:53 UTC
**PUT**
```
{
  "reqId": "abcdef",
  "level": 3,
  "time": "2021-05-25T10:41:11+02:00",
  "remoteAddr": "1.2.3.4",
  "user": "myuser",
  "app": "PHP",
  "method": "PUT",
  "url": "/remote.php/dav/files/myuser/Joplin/locks/sync_desktop_4711.json",
  "message": {
    "Exception": "Error",
    "Message": "Trying to access array offset on value of type bool at /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#441",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 441,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
        "line": 302,
        "function": "fopen",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 753,
        "function": "fopen",
        "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 623,
        "function": "copyBetweenStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/files_trashbin/lib/Storage.php",
        "line": 240,
        "function": "moveFromStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
        "line": 292,
        "function": "moveFromStorage",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 156,
        "function": "put",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1098,
        "function": "createFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 504,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/lib/Server.php",
        "line": 332,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/remote.php",
        "line": 167,
        "args": [
          "/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  },
  "userAgent": "Joplin/1.0",
  "version": "21.0.2.1"
}
```

**DELETE**
```
{
  "reqId": "abcdef",
  "level": 3,
  "time": "2021-05-25T10:41:15+02:00",
  "remoteAddr": "1.2.3.4",
  "user": "myuser",
  "app": "PHP",
  "method": "DELETE",
  "url": "/remote.php/dav/files/myuser/Joplin/locks/sync_desktop_4711.json",
  "message": {
    "Exception": "Error",
    "Message": "Trying to access array offset on value of type bool at /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#441",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 441,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
        "line": 302,
        "function": "fopen",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 753,
        "function": "fopen",
        "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 623,
        "function": "copyBetweenStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/files_trashbin/lib/Storage.php",
        "line": 240,
        "function": "moveFromStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/files_trashbin/lib/Trashbin.php",
        "line": 323,
        "function": "moveFromStorage",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php",
        "line": 108,
        "function": "move2trash",
        "class": "OCA\\Files_Trashbin\\Trashbin",
        "type": "::"
      },
      {
        "file": "/var/www/html/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php",
        "line": 103,
        "function": "moveToTrash",
        "class": "OCA\\Files_Trashbin\\Trash\\LegacyTrashBackend",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/files_trashbin/lib/Storage.php",
        "line": 203,
        "function": "moveToTrash",
        "class": "OCA\\Files_Trashbin\\Trash\\TrashManager",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/files_trashbin/lib/Storage.php",
        "line": 103,
        "function": "doDelete",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/View.php",
        "line": 1168,
        "function": "unlink",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/lib/private/Files/View.php",
        "line": 725,
        "function": "basicOperation",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
        "line": 466,
        "function": "unlink",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 179,
        "function": "delete",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 281,
        "function": "delete",
        "class": "Sabre\\DAV\\Tree",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpDelete",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/lib/Server.php",
        "line": 332,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/html/nextcloud/remote.php",
        "line": 167,
        "args": [
          "/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  },
  "userAgent": "Joplin/1.0",
  "version": "21.0.2.1"
}

```

**Comment by acsfer** [comment] 2021-05-25 10:11
Seems duplicate of https://github.com/nextcloud/server/issues/26473.
Mind to test https://github.com/nextcloud/server/pull/26980?

**Comment by tabp0le** [comment] 2021-05-25 20:17
> 
> 
> Seems duplicate of #26473.
> Mind to test #26980?

I can confirm #26980 fixes issue for me

**Closed** 2021-05-25 20:47 UTC
Labels: 0. Needs triage, bug, needs info

**Comment by Linuxfabrik** [comment] 2021-05-26 06:10
#26980 fixes issue for me, too.
