### ISSUE TITLE
Update to 14.0.4 throws InvalidArgumentException

### ISSUE THREAD

**Issue by Fisheye09** [nextcloud/server#13053] opened 2018-12-13 12:04 UTC
### Steps to reproduce
1. Upload NC 14.0.4 via FTP overwriting 14,0.1
2. go to Domain,de/PathToNextCloud
3. Click on Start the Update

### Expected behaviour
The Update should succede

### Actual behaviour
After updating the Database the following error is thrown: "InvalidArgumentException: Migration step 'OCA\DAV\Migration\Version1006Date20180628111625' is unknown"

### Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySql

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud

**Comment by Savro** [comment] 2018-12-20 03:41
same issue here. did you manage to fix it?

**Comment by PalmaSolutions** [comment] 2018-12-25 07:39
This is probably due to the fact that you extracted 15.0 first and did not clear the files. So your 14.0.4 is trying to use classes that have not been defined yet. The file seems to be only added in 15.0.
Remove the Nextcloud directories, except, obviously, data and config and extract the 14.0.4 pack again. Then run the manual (or browser) updates and it should fix it... Once you've done that and you're running 14.0.4 properly then you can go for 15.0.

Hope it helps.

**Comment by skjnldsv** [comment] 2019-06-04 09:04
As I cannot reproduce the issue, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-04 09:04 UTC
Labels: 0. Needs triage, bug, feature: install and update
