### ISSUE TITLE
Folders and Files containing "%"

### ISSUE THREAD

**Issue by tsueri** [nextcloud/server#11861] opened 2018-10-16 08:47 UTC
### Steps to reproduce
1. Create a file or folder containing the "%" character
2. Reload window
3. Endless endless loading-spinner
4. delete the file or folder (it syncs with the desktop-client)
5. Reload window
6. All the files appear

### Expected behaviour
Nextcloud should show the file or folder containing this character

### Actual behaviour
Nextcloud doesn't show files or folders containing the "%" character. In fact it doesn't show anything but the spinner.
I don't know, if other characters are affected. I just found this one.

### Server configuration

**Operating system**:
Ubuntu 16.04 (also tested to verify this error on the VM from hanssonit.se)

**Web server:**
Apache 2

**Database:**
MariaDB 10.3

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
Issue existing (tested) on Nextcloud 14.0.1 and 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update and fresh install

**Where did you install Nextcloud from:**
doesn't matter
Tested on the VM from hanssonit.se and on my installation which was migrated from owncloud and upgraded to the latest release. 

index.php/settings/integrity/failed:
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - announcementcenter: 3.3.1
  - audioplayer: 2.4.1
  - bookmarks: 0.13.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.2
  - camerarawpreviews: 0.6.1
  - checksum: 0.4.1
  - cloud_federation_api: 0.0.1
  - cms_pico: 0.9.7
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - drawio: 0.9.1
  - drop_account: 0.0.12
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_downloadactivity: 1.3.0
  - files_external: 1.5.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.3.1
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - initialcheck: 1.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - metadata: 0.7.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - ransomware_detection: 0.4.1
  - ransomware_protection: 1.2.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - socialsharing_email: 1.0.4
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_gateway: 0.10.0
  - twofactor_totp: 1.5.0
  - unsplash: 1.1.1
  - updatenotification: 1.4.1
  - user_usage_report: 1.1.0
  - workflowengine: 1.4.0
Disabled:
  - data_request
  - encryption
  - flowupload
  - passman
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'removed',
  'passwordsalt' => 'removed',
  'secret' => 'removed',
  'trusted_domains' => 
  array (
    0 => 'removed',
  ),
  'datadirectory' => 'removed',
  'overwrite.cli.url' => 'https://removed/',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'version' => '14.0.3.0',
  'dbname' => 'nextcloud',
  'dbhost' => '',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'ncuser',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'loglevel' => 0,
  'cron_log' => true,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'filelocking.ttl' => 3600,
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'data-fingerprint' => 'removed',
  'activity_expire_days' => 365,
  'updater.release.channel' => 'stable',
  'simpleSignUpLink.shown' => false,
);
```
</details>

**Are you using external storage, if yes which one:**
SFTP

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
tested on Safari, Chrome and Firefox. Latest versions. Results are the same.

**Operating system:**
MacOS 10.14 (18A391)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
empty

```

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"pUywlP6xpQpcdciEOD77","level":0,"time":"2018-10-16T08:50:07+00:00","remoteAddr":"192.168.1.1","user":"removed","app":"no app in context","method":"GET","url":"\/apps\/gallery\/config?extramediatypes=1","message":"No cache entry found for \/removed\/files\/gallery.cnf (storage: home::removed, internalPath: files\/gallery.cnf)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.0 Safari\/605.1.15","version":"14.0.3.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

javascript console log (chrome):
```
10:37:12.134 client.js?v=032ea793-57:283 Uncaught (in promise) URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Client._parseFileInfo (client.js?v=032ea793-57:283)
    at client.js?v=032ea793-57:407
    at Function._.map._.collect (core.js?v=032ea793-57:185)
    at Client._parseResult (client.js?v=032ea793-57:406)
    at client.js?v=032ea793-57:488
```
</details>

**Comment by MorrisJobke** [comment] 2018-10-16 10:15
> 10:37:12.134 client.js?v=032ea793-57:283 Uncaught (in promise) URIError: URI malformed at decodeURIComponent (<anonymous>) at Client._parseFileInfo (client.js?v=032ea793-57:283) at client.js?v=032ea793-57:407 at Function._.map._.collect (core.js?v=032ea793-57:185) at Client._parseResult (client.js?v=032ea793-57:406) at client.js?v=032ea793-57:488

Duplicate of #11744 and will be solved in 14.0.4 via #11781

**Closed by MorrisJobke** 2018-10-16 10:15 UTC
Labels: bug

**Comment by jokland** [comment] 2018-11-06 10:37
I reproduced the same behaviour with the crahacter ! on filenames.
Thanks

**Comment by MorrisJobke** [comment] 2018-11-06 14:22
> I reproduced the same behaviour with the crahacter ! on filenames.
> Thanks

Fixed by the same code change.
