### ISSUE TITLE
cannot edit shared file

### ISSUE THREAD

**Issue by luntik2012** [nextcloud/server#13857] opened 2019-01-28 06:42 UTC
I've read #5876.

There is "can edit" checkbox, so user should be able to edit file, but he cannot.

**Comment by eminogrande** [comment] 2020-01-24 10:22
I can confirm that, we have the same problem.

**Comment by eminogrande** [comment] 2020-01-24 10:23
> what was that? i didn't add those tags

Those tags are added automatically. "needs triage" means that someone is going to check if this is a valid bug report or not.

**Comment by szaimen** [comment] 2021-05-28 11:31
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-28 11:31 UTC
Labels: 0. Needs triage, bug
