### ISSUE TITLE
User autocreated/connected with module user_saml does not exist with the command occ user:lastseen

### ISSUE THREAD

**Issue by adrienfr44** [nextcloud/server#3925] opened 2017-03-19 19:55 UTC
In Nextcloud directory : 
sudo -u www-data php occ user:lastseen "**uid autocreated/connected with module user_saml**"
the response is always : "User does not exist"

All users are created in the table oc_user_saml_users

### Steps to reproduce
1. Install module user_saml
2. Configuration on this module : **no check the option** "Only allow authentification if an account is existent on other backend (e.g. LDAP)"
3. User connected with module user_saml (in the first connection, this user is created in the table oc_users_saml).
4. Next, a linux user launch the command in Nextcloud directory : sudo -u www-data php occ user:lastseen "**uid autocreated/connected with module user_saml**"

### Expected behaviour
User exist and the command display the last log in of this user

### Actual behaviour
User does not exist

### Server configuration
**Operating system**:
Debian8

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
PHP5

**Nextcloud version:** (see Nextcloud admin page)
11.0.2
user_saml 1.2.2
Mode production

**Updated from an older Nextcloud/ownCloud or fresh install:**
No

**Where did you install Nextcloud from:**
/var/www/nextcloud

**Comment by LukasReschke** [comment] 2017-08-04 10:23
Duplicate of https://github.com/nextcloud/user_saml/issues/103. Will track there.

**Closed by LukasReschke** 2017-08-04 10:23 UTC
Labels: bug
