### ISSUE TITLE
[Bug]: the display does not change when clicking on a favorite in Files

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#38503] opened 2023-05-29 15:48 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

see title

### Steps to reproduce

click on a favorite.
display should show the content of your favorite folder.
nothing happens, but the URL changes.

### Expected behavior

 display should show the content of your favorite folder.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
c.nc.c
```

**Comment by szaimen** [comment] 2023-05-29 15:48
cc @nextcloud/server-frontend

**Comment by skjnldsv** [comment] 2023-05-30 18:34
Clicking where, in the files list? In the navigation?

**Comment by szaimen** [comment] 2023-06-01 07:43
Apparently @Rello can reproduce this as well. 

Possibly caused by https://github.com/nextcloud/server/pull/38441?

**Comment by arnowelzel** [comment] 2023-06-17 18:26
JFTR: Happens here as well with a server I just upgraded from NC 26.0.3 to NC 27.0.0. It does not matter which browser I use and I have to explain nearly 40 users that the favorites are not usable any longer until this I fixed. Wasn't there a E2E test to make sure that works before releasing a new version?

**Comment by arnowelzel** [comment] 2023-06-23 15:43
> > JFTR: I have to explain nearly 40 users that the favorites are not usable any longer until this I fixed.
> 
> Favorites are still usable. Workaround:
> 
> * Click ON Favorites, (not on the expand [>]/[v] button):
> * the Favorites are listed in main window, where you can click and open them.

Thanks for the hint - I also found that out meanwhile ;-)

Maybe I'll add some custom CSS as a tempory fix to hide the favorite list and the expand button until a fix is provided.

**Comment by szaimen** [comment] 2023-06-28 17:16
Cc @eerver-frontend shouod we try to fix this for 27.0.1?

**Comment by YouveGotMeowxy** [comment] 2023-07-01 05:09
Came her just to report this issue on mine as well. Latest NC version in docker. I click any favoring in the menu and the url in the location bar changes, but the page itself doesn't do anything. I have to press the enter button after clicking it so it actually navigates to that page.

**Comment by szaimen** [comment] 2023-07-14 08:55
Fixed with https://github.com/nextcloud/server/pull/39301

**Closed by szaimen** 2023-07-14 08:55 UTC
Labels: bug, 3. to review, regression, 27-feedback

**Comment by samhonarvar** [comment] 2023-10-31 01:15
It seems like this was fixed in July 14, I'm running 27.1.2 and this issue is still happening for me.

**Comment by CuriousHummingbird** [comment] 2023-11-23 10:57
Same here with 27.1.3. Bug ist still there... Our problem is, that the workaround above does not work if you use the favorites for copying and moving files within the NextCloud folders in the popup windows. The folder view is loading and does not show any results after the first click on any favorites Folder in the popup  window, when using the saved favorites. 

https://github.com/nextcloud/server/assets/151830033/01f1e377-24cc-4534-8516-316659d6e533

**Comment by surfrock66** [comment] 2024-08-26 14:49
Following up on this, on Nextcloud Hub 8 (29.0.5) with all apps up to date, the links in my favorites no longer work, and instead I get an error "No Favorites Yet".

If I navigate to my root, and go to my folder, I can see all my contents:

![image](https://github.com/user-attachments/assets/6ddc1d7e-a3c9-4161-b5a3-af2a460c302a)

If I click the link in the favorites on the sidebar, I get the following:

![image](https://github.com/user-attachments/assets/5ab7d760-16fd-41ed-954c-edc26fd785f8)

This was working as recently as last week, and this is the same for all favorites.  Speculating, can it not find the path because the root of "Favorites" isn't tracing properly to the actual root path of the share?

**Comment by hegGK** [comment] 2024-09-10 05:57
Same here! Also 29.0.5 and the Favorite menu entry seems to filter the path:
![image](https://github.com/user-attachments/assets/2d6aa962-ced4-4138-b43a-7d32190cd933)
instead of being a link to a normal folder.
