### ISSUE TITLE
Cron.php execution causes CPU utilization to max out

### ISSUE THREAD

**Issue by dellis87** [nextcloud/server#23335] opened 2020-10-10 15:23 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Deploy Docker Nextcloud instance using "latest" tag.
2. Attempt to execute cron.php using _docker exec nextcloud-app su - www-data -s /bin/bash -c 'php -f /var/www/html/cron.php' > /dev/null 2>&1_ or execute the command directly within the container. 
3. Job will never complete and CPU will be 100%.

### Expected behaviour
Cron.php will complete and will not max out resources. 

### Actual behaviour
Cron.php execution maxes out machine resources. 

### Server configuration

**Operating system:**
Ubuntu 20.04 - Docker

**Web server:**

**Database:**
MySQL
**PHP version:**
7.4.11
**Nextcloud version:** (see Nextcloud admin page)
20.0.0.9
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
docker
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Command will not return.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

$CONFIG = array (
  'instanceid' => 'oceh6b982uux',
  'passwordsalt' => '#####',
  'secret' => '####',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.$$$$-cloud.com',
  ),
  'datadirectory' => '/data/Volumes/Virtual Machines/Containers/Nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '20.0.0.9',
  'overwrite.cli.url' => 'http://nextcloud.$$$$-cloud.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '$$$$$',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpport' => '587 ',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '$$$$$',
  'mail_domain' => 'outlook.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp-mail.outlook.com',
  'mail_smtpname' => '$$$$$@outlook.com',
  'mail_smtppassword' => '$$$$$',
  'overwriteprotocol' => 'https',
  'maintenance' => false,
  'check_data_directory_permissions' => false,
  'loglevel' => 0,
  'app_install_overwrite' => 
  array (
    0 => 'defaultlinkopen',
    1 => 'joplin',
  ),
);
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, local
**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome
**Operating system:**
MacOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"I2HnZYSYlGGwWeWcNbML","level":0,"time":"2020-10-07T19:09:50+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/core/preview?fileId=11&x=32&y=32","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"CEBGaSUUAF95ISH9uZIK","level":0,"time":"2020-10-07T19:09:50+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/core/preview?fileId=9&x=32&y=32","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"xcElwsPaVvbzvyMAXW6J","level":0,"time":"2020-10-07T19:09:50+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/cron.php","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"xcElwsPaVvbzvyMAXW6J","level":0,"time":"2020-10-07T19:09:50+00:00","remoteAddr":"172.18.0.3","user":"--","app":"cron","method":"GET","url":"/cron.php","message":"Run OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 1","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"sDU9SK44Jn9XWvSUN4RC","level":0,"time":"2020-10-07T19:09:50+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/core/preview?fileId=12&x=32&y=32","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"JOziw1FSiQ5hZoHEPTIQ","level":0,"time":"2020-10-07T19:09:50+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/core/preview?fileId=14&x=32&y=32","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"oNRcEgITPbk91mjiYafI","level":0,"time":"2020-10-07T19:09:51+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/core/preview?fileId=10&x=32&y=32","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"xcElwsPaVvbzvyMAXW6J","level":0,"time":"2020-10-07T19:09:51+00:00","remoteAddr":"172.18.0.3","user":"--","app":"cron","method":"GET","url":"/cron.php","message":"Finished OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 1 in 1 seconds","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"eBSTYVF4PU9BANiEfONU","level":0,"time":"2020-10-07T19:09:51+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/apps/theming/img/core/filetypes/application-pdf.svg?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"Fqcgjkiyf5Q2tlnZ8mZn","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"zKdHUPGIp2ERm0zC0lQz","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fsettings%2Fuser","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"ghKlULybd4tyYgE7cX4g","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"PUT","url":"/index.php/apps/user_status/heartbeat","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"uBBZA1ZBiX7xPg1mX9gp","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/cron.php","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"uBBZA1ZBiX7xPg1mX9gp","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"--","app":"cron","method":"GET","url":"/cron.php","message":"Run OCA\\DAV\\BackgroundJob\\CleanupDirectLinksJob job with ID 2","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"uBBZA1ZBiX7xPg1mX9gp","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"--","app":"cron","method":"GET","url":"/cron.php","message":"Finished OCA\\DAV\\BackgroundJob\\CleanupDirectLinksJob job with ID 2 in 0 seconds","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"yf5nzQPVj8pyQj1FLNsw","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/avatar/dustin/145?v=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"OtTGeUx5DeQTCdZfdON1","level":0,"time":"2020-10-07T19:10:30+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"Wjo9XJcYu92lBarE3p84","level":0,"time":"2020-10-07T19:10:42+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"POST","url":"/index.php/avatar/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"Wjo9XJcYu92lBarE3p84","level":0,"time":"2020-10-07T19:10:42+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"core","method":"POST","url":"/index.php/avatar/","message":"OC_Image->fixOrientation() Orientation: 1","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
{"reqId":"LRUA8QsL88sYsA5Q1WLA","level":0,"time":"2020-10-07T19:10:42+00:00","remoteAddr":"172.18.0.3","user":"dustin","app":"files_sharing","method":"GET","url":"/index.php/avatar/tmp?requesttoken=Ppgs9jtVmjPQA3NjIY03nokuLFoSyP%2BA2%2B4VgcT28Kk%3D%3ASq5dmFc7%2FWW%2FbUEWSrt5sb4WRBB7jozuiJ8hsYnOk%2FE%3D","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by acsfer** [comment] 2020-10-11 09:48
Duplicate of https://github.com/nextcloud/docker/issues/1267

**Closed by acsfer** 2020-10-11 09:48 UTC
Labels: 0. Needs triage, bug
