### ISSUE TITLE
[Bug]: ocm-provider validation not working anymore + htaccess entry wrong

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#40794] opened 2023-10-06 03:51 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When updating to 27.1.2 the server says that the ocm-provider paths are incorrect.
I checked the .htaccess shipped with 27.1.2, but the config in there is incorrect.
Deleting the config path from there is leading to a working ocm-provider path (checked in the browser). I do have 2 redirects in the apache-conf:

Redirect 301 /ocm-provider /nextcloud/ocm-provider
Redirect 301 /ocs-provider /nextcloud/ocs-provider

Nevertheless, the nextcloud admin page is still telling me that the ocm-provider path is setup incorrect, why?
The ocs-provider is fully fine. There was no error in the .htaccess and my redirect worked out of the box.

### Steps to reproduce

1. Upgrade from 27.1.1 to 27.1.2
2. Open Admin Page
3.

### Expected behavior

That it is working like on 27.1.1 without any errors

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
not needed for this issue
```

### List of activated Apps

```shell
not needed for this issue
```

### Nextcloud Signing status

```shell
all works fine
```

### Nextcloud Logs

```shell
No relevant erros in the log
```

**Comment by joshtrichards** [comment] 2023-10-06 04:22
Duplicate of #40792.
Fixed in #40745.

See these for manual correctionsoptions: #40705 (Apache) or https://github.com/nextcloud/documentation/pull/11179 (nginx)

**Closed by joshtrichards** 2023-10-06 04:22 UTC
Labels: bug, 0. Needs triage

**Comment by juskglass** [comment] 2023-10-06 16:17
I had the same issue after upgrading to 27.1.2.

My installation is in `domain.tld/nextcloud`. The `.htaccess` changes in #40745 redirect `ocm-provider` to `/index.php`, which doesn't exist.

Changing that line in `.htaccess` from:
`RewriteRule ^ocm-provider/?$ /index.php [QSA,L]`
to:
`RewriteRule ^ocm-provider/?$ index.php [QSA,L]`
resolved the issue for me, and all checks now pass on the admin page.

**Comment by Lawkss** [comment] 2023-10-07 15:15
> I had the same issue after upgrading to 27.1.2.
> 
> My installation is in `domain.tld/nextcloud`. The `.htaccess` changes in #40745 redirect `ocm-provider` to `/index.php`, which doesn't exist.
> 
> Changing that line in `.htaccess` from: `RewriteRule ^ocm-provider/?$ /index.php [QSA,L]` to: `RewriteRule ^ocm-provider/?$ index.php [QSA,L]` resolved the issue for me, and all checks now pass on the admin page.

Thank you so much! worked for me too. I also have nextcloud in a dir called /cloud and not in root directory.

**Comment by ArtificialOwl** [comment] 2023-10-09 09:27
@juskglass Where is located your .htaccess ? in your nextcloud folder, or at the root of your domain name ?

**Comment by REggleston27** [comment] 2023-10-09 10:08
On my set up 
/var/www/html/nextcloud/.htaccess

you can access it via sudo nano /var/www/html/nextcloud/.htaccess BUT make sure you have a back up before you fiddle with it :-D

**Comment by juskglass** [comment] 2023-10-09 12:56
> @juskglass Where is located your .htaccess ? in your nextcloud folder, or at the root of your domain name ?

It's in the nextcloud folder.

**Comment by ElHado** [comment] 2023-10-09 13:42
Anyone know how to solve this issue in nginx?

**Comment by tflidd** [comment] 2023-10-31 07:57
> Anyone know how to solve this issue in nginx?

The NGINX sample configuration in the documentation was updated:
https://github.com/nextcloud/documentation/pull/11179/files

**Comment by LukaszSellmann** [comment] 2023-11-23 20:28
Sorry for refreshing topic but this solution doesn't work for me.
In 
`/var/www/nextcloud/.htaccess`
there is:
`RewriteRule ^ocm-provider/?$ index.php [QSA,L]`
but i stil have this warning about ocm-provider

Same version, but php8.1.

**Comment by joshtrichards** [comment] 2023-11-24 14:22
@LukaszSellmann 

- What happens when you visit `https://YOURDOMAIN/nextcloud/ocm-provider` in you browser?
- What does your web server log show when you visit that URL?

If the above didn't fix it, then you have a different set-up (i.e. not using Apache, not installed in a subdirectory, maybe your Apache is configured to ignore `.htaccess` files, etc.)

Probably best to take further follow-up to the Nextcloud Help Forum where you can get feedback on your specific configuration/situation - https://help.nextcloud.com

**Comment by MooreFoss** [comment] 2024-02-10 04:15
> @LukaszSellmann
> 
> * What happens when you visit `https://YOURDOMAIN/nextcloud/ocm-provider` in you browser?
> * What does your web server log show when you visit that URL?
> 
> If the above didn't fix it, then you have a different set-up (i.e. not using Apache, not installed in a subdirectory, maybe your Apache is configured to ignore `.htaccess` files, etc.)
> 
> Probably best to take further follow-up to the Nextcloud Help Forum where you can get feedback on your specific configuration/situation - https://help.nextcloud.com

I have the same problem now.
`https://YOURDOMAIN/nextcloud/ocm-provider` show "404 not found", and `GET /nextcloud/ocm-provider HTTP/2.0＂ 404 548 ＂-＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36＂` in web server log.

There is `rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|ocs-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;` in my nginx config.

**Comment by joshtrichards** [comment] 2024-02-10 13:29
@MooreFoss:

Please take further follow-up to the Nextcloud Help Forum where you can get feedback on your specific configuration/situation - https://help.nextcloud.com

P.S. Your posted Nginx config isn't for a subdirectory installation:
https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-a-subdir-of-the-nginx-webroot
