### ISSUE TITLE
Search shortcut "Ctrl-F" does not work anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#19001] opened 2020-01-19 13:53 UTC
Pressing Ctrl-F once used to work to focus the search field. Does not anymore on latest master, as it directly opens the browser search.

Still works in Mail for example so it might be something else interfering?

**Comment by eibex** [comment] 2021-01-18 21:41
It works for me on Nextcloud 20.0.5 (I don't think it ever stopped working for me). I'm running Firefox 84.0.2.
I disabled the dashboard app when I installed NC 20, though I doubt that's the root cause.

It works while I'm on any app, tested with: files, contacts, calendar, tasks, maps, photos, activity. settings.

**Comment by skjnldsv** [comment] 2021-04-22 12:30
Fixed with global search.
Press once for NC search, twice for browser search (like lots of other websites)

**Closed** 2021-04-22 12:29 UTC
Labels: 1. to develop, bug, feature: files, feature: search, papercut, regression
