### ISSUE TITLE
[Bug]: TypeError: Return value of OCA\DAV\Connector\Sabre\FilesPlugin::OCA\DAV\Connector\Sabre\{closure}() must be of the type int or null, float returned

### ISSUE THREAD

**Issue by maxicarlos08** [nextcloud/server#34674] opened 2022-10-19 17:30 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to Nextcloud version 25 today, I was unable to view my files getting this error:
```
This directory is unavailable, please check the logs or contact the administrator
```

### Steps to reproduce

1. Upgrade to Nextcloud version 25
2. Try to access files

### Expected behavior

I expect the file app to work normally

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{                                  
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "klapstuhl.maxicarlos.de"
        ],
        "default_phone_region": "ES",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.0.18",
        "overwrite.cli.url": "https:\/\/klapstuhl.maxicarlos.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "enable_previews": true,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }   
}
```

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - previewgenerator: 5.1.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.16.0
  - calendar: 4.0.1
  - circles: 24.0.1
  - dashboard: 7.4.0
  - deck: 1.7.1
  - drawio: 1.0.3
  - encryption
  - federation: 1.14.0
  - files_external
  - files_texteditor: 2.14.0
  - mail: 2.0.3
  - maps: 0.2.1
  - music: 1.6.0
  - nextcloud_announcements: 1.13.0
  - recommendations: 1.3.0
  - spreed: 15.0.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - suspicious_login
  - tasks: 0.14.5
  - user_ldap
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
Does not work, it redirects to /apps/files (which gives me the above error)
```

### Nextcloud Logs

```shell
[webdav] Error: TypeError: Return value of OCA\DAV\Connector\Sabre\FilesPlugin::OCA\DAV\Connector\Sabre\{closure}() must be of the type int or null, float returned at <<closure>>

 0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 1. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 356
    Sabre\DAV\PropFind->handle()
 2. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties()
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit()
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode()
 5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
 8. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
11. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
12. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
13. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
14. /var/www/nextcloud/remote.php line 167
    require_once("/var/www/nextcl ... p")

PROPFIND /remote.php/dav/files/maxi/
from 192.168.1.1 by maxi at 2022-10-19T17:26:42+00:00
```

### Additional info

I'm running Nextcloud on a 64 bit raspberry pi 4b, however `https://server.url/settings/admin/overview` tells me that:
```
It seems like you are running a 32-bit PHP version. Nextcloud needs 64-bit to run well. Please upgrade your OS and PHP to 64-bit! For further details read [the documentation page about this ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-system-requirements).```
And the documentation link is broken (file not found)

**Comment by szaimen** [comment] 2022-10-19 18:33
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by szaimen** [comment] 2022-10-19 18:42
As for the admin link, thanks for reporting! We'll look into it!

**Comment by szaimen** [comment] 2022-10-19 18:47
@blizzz any idea why https://docs.nextcloud.com/server/25/admin_manual/installation/system_requirements.html returns 404? 

But https://docs.nextcloud.com/server/24/admin_manual/installation/system_requirements.html works?

**Comment by maxicarlos08** [comment] 2022-10-19 20:31
> As this seems to be a setup issue

I don't think this is a setup issue, the Nextcloud instance has been running fine for about 3 years until this happened.

I also opened a [question](https://help.nextcloud.com/t/cannot-access-files-after-upgrade-to-nextcloud-25/147823) in the forum as you suggested, and there seem to be more people having this issue on a Raspberry Pi.

Another user found out that users created after the upgrade [are not affected](https://help.nextcloud.com/t/cannot-access-files-after-upgrade-to-nextcloud-25/147823/4) by the issue

**Comment by szaimen** [comment] 2022-10-19 20:37
This is a setup issue and only happening since you are still running some 32bit components.

**Comment by szaimen** [comment] 2022-10-19 20:41
See https://help.nextcloud.com/t/no-file-structure-displayed-after-updating-to-25-0-0rc2/146784/7

**Comment by szaimen** [comment] 2022-10-20 16:05
I agree. Will look into that in the next days.

Just so that you know:

> Re didnt plan to actively remove 32-bit compatibility but it seems like we did for 25 without knowing as we do not test against 32-bit which is why we removed 32-bit support in the first place.

**Comment by iDontWantAUsername** [comment] 2022-10-21 06:58
Could the System Requirements page be updated to reflect that 64bit only is supported:
https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

This currently implies that 64bit is recommended and 32bit will work but not that well - not that it will be totally broken:

[CPU Architecture and OS
A 64bit CPU and 64bit OS is required for Nextcloud to run well.](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html)

**Comment by MichaIng** [comment] 2022-10-21 14:31
I followed the decision to formally drop 32-bit support as of long standing issues with the trashbin and >2 GiB files downloads from web interface on 32-bit systems. But implementing the same limitation the trashbin had (automatic int=>float conversion?) into the files app, so that neither desktop client sync, nor files app in web UI are working, i.e. core functionality, probably wasn't clever without informing users (also not via #32117) sufficiently early to allow hardware migration, and of course blocking the upgrade to the incompatible NC version.

I test the beta on my Raspberry Pi 2 v1.1 (32-bit CPU) production system nearly every time beforehand, sadly not this time, otherwise I could have brought up the topic earlier.

There is a [workaround](https://help.nextcloud.com/t/cannot-access-files-after-upgrade-to-nextcloud-25/147823/6?u=michaing), but such on the trashbin causes other issues (AFAIK >2 GiB overall trashbin data worked with it, but individual >2 GiB files didn't work, or so), which likely is similar here with the DAV connector.

Users created after the upgrade likely don't have the issue because/until they have >2 GiB of files 😉.

**Comment by szaimen** [comment] 2022-10-21 14:33
> We didnt plan to actively remove 32-bit compatibility but it seems like we did for 25 without knowing as we do not test against 32-bit which is why we removed 32-bit support in the first place.

**Comment by MichaIng** [comment] 2022-10-21 15:04
Here btw is the culprit: https://github.com/nextcloud/3rdparty/commit/dd3f5da#diff-15aea57cf25666fcad29ed4fc1ba78e5d8e447c574a877bb4fdc9cb87e5ff4b2

```
sabre/http/CHANGELOG.md

5.1.5 (2022-07-09)
------------------

* #184 Remove 4GB file size workaround for 32bit OS / Stream Videos on IOS (@schoetju)
```
A related `if (PHP_INT_SIZE > 4) {` block in `sabre/http/lib/Sapi.php` has gone which was for 32-bit support. A pain that this breaking change has been introduced with a patch version. So clearly no fold of Nextcloud team, such change in a patch version of a 3rdparty subsubmodule is quickly overseen.

**Comment by MichaIng** [comment] 2022-10-21 15:13
The related PR explicitly mentions Nextcloud and states that this workaround in sabre/http code wouldn't be required anymore: https://github.com/sabre-io/http/pull/184

Would be more than a coincidence if this was right but NC files app+sync still broken in the release this was merged 🤔.

**Comment by adrianog91** [comment] 2022-10-22 06:19
I have the same issue with the same configuration of @maxicarlos08

**Comment by MichaIng** [comment] 2022-10-22 13:24
All expected with every 32-bit system. Please see the linked workaround above or migrate hardware+OS to 64-bit.

**Comment by j-be** [comment] 2022-10-22 18:40
@MichaIng I was just hit by this issue (i.e. `Return value of OCA\DAV\Connector\Sabre\FilesPlugin::OCA\DAV\Connector\Sabre\{closure}() must be of the type int or null, float returned`) after upgrading and I think the version bump linked above is not the culprit.

In detail: I have been running Nextcloud 24.0.6 for quite some time now without any issues (expect for #15117). And after reverting from `$OC_Version = array(25,0,0,18);` back to `$OC_Version = array(24,0,6,1);` and restoring the pre-upgrade backup the issue is gone again.

Now `24.0.6` already depends on `"sabre/dav": "4.4.0"`, same as `25.0.0` does (see https://github.com/nextcloud/server/blob/v24.0.6/build/integration/composer.json).

I am running Nextcloud on an Odroid HC-2 (armv7, so 32 Bit only). I'd be happy to help debugging if needed.

**Comment by MichaIng** [comment] 2022-10-22 19:03
Thanks for the hint, you're right, also the `sabre/http` version with removed 32-bit workaround is present in NC24 already 🤔. Looks like I was on the wrong track, and the sabre guys were right that the workaround isn't required anymore.

So we need to have a deeper look into how `sabre/dav` is used differently by NC25, causing the issue.

**Comment by kesselb** [comment] 2022-10-24 15:13
![image](https://user-images.githubusercontent.com/3902676/197560048-b44c3369-8e38-48b7-9f21-fb44d0b7b98a.png)

24 left, 25 right (apps/dav/lib/Connector/Sabre/FilesPlugin.php). Should work if we drop the return type again. However, there might be more "issues". Every time we add an integer type hint to something with possible values bigger than 32bit int, we run into this situation.

**Comment by MichaIng** [comment] 2022-10-31 15:16
Not sure how I could have overseen it, here the PR which added int type hint: https://github.com/nextcloud/server/commit/829490ab7a02579c6b31573c3f53428e86cbf2e0#diff-1d6ed4804160da213bc58248990a6936622ce53100a23535d207dba153f7e759

**Comment by Slartibartfast27** [comment] 2022-10-31 20:15
I also have this problem and would greatly appreciate a fix for 32bit Operating Systems to avoid unnecessary hardware replacements and to save resources (apart from the time needed to setup everything fresh again, which would cost me days).

**Comment by j-be** [comment] 2022-10-31 21:48
@Slartibartfast27 there is a fix at https://help.nextcloud.com/t/cannot-access-files-after-upgrade-to-nextcloud-25/147823/6?u=michaing

And I hate to be that guy, but imho you really should rethink your backup/rollback strategy. Something like this can happen, all the time. And recovering from it _should_ be not more than a minor inconvenience.

**Comment by j-be** [comment] 2022-10-31 22:02
@MichaIng About dropping 32 bit support: I think that is a bad idea. I agree, that corporate users won't mind: they are all on 64 bit by now. But home users aren't - I for one am not.

I agree, that there is no x86 32 bit machine worth keeping alive - they are at best a waste of energy. But that argument does imho not hold for ARMv7. There are still a lot of ARM 32 bit computers able to run Nextcloud for friends and family.

**Comment by iDontWantAUsername** [comment] 2022-10-31 22:34
If 32bit support is dropped though it should be properly documented not just a vague 64bit is recommended. The commit has actually broken 32bit support so it isn't just recommended it is required.

**Comment by MichaIng** [comment] 2022-11-01 07:24
Most importantly the update to NC25 should then not be offered on 32-bit systems.

Generally on this matter: I agree if there are no strong reasons, at least this core functionally should be preserved on 32-bit. The change was a best practice annotation from lint, not related to any actual issue, AFAIK. However, there were other long standing issues with 32-bit (>2 GiB trashbin, >2 GiB downloads) and the CI/CD pipeline does not contain 32-bit tests (runs on 64-bit), so such issues can slip through any time later, if not someone with 32-bit system tests the beta/RC. Sadly I didn't do it exactly this release while always tested new NC releases beforehand before.

**Comment by j-be** [comment] 2022-11-01 14:27
> Most importantly the update to NC25 should then not be offered on 32-bit systems.

Yes, that would be a good idea indeed. But from how I understand [this piece of code](https://github.com/nextcloud/server/blob/075a87670d4157086974d84972553914078c203b/lib/private/Updater/VersionCheck.php#L76-L85) it is currently not possible to filter specific architectures when fetching updates? So I don't see how we could prevent 32 bit NC24 users to upgrade.

> AFAIK. However, there were other long standing issues with 32-bit (>2 GiB trashbin, >2 GiB downloads)

Never ran into the first one, but I - long time ago - tried to get a fix for large downloads merged (see #15117 and #27562) and it was rejected back then. The patch still applies (including NC25) and still fixes the issue, which is afaik. still (i.e. more than a year after) present on 32 bit. I can't seem to find the proposed "option for specifying the archive format" on my NC 24. So please understand my saltiness on the "32 bit has problems" topic.

> CI/CD pipeline does not contain 32-bit tests (runs on 64-bit)

There may still be the option to have them running inside a Docker container - Debian still offers 32 bit x86 images. I quickly threw together something at https://github.com/j-be/nextcloud-ci/. There are still a couple of test failures even on AMD64 - not sure why. But there are definitely a lot more in the NC25 386 run (see https://github.com/j-be/nextcloud-ci/actions/runs/3369893196).

So even if GitHub does not provide 32 bit runners: there may still ways to get 32 bit CIs with GitHub Actions.

I think the question that needs to be answered is: Will the Nextcloud team put effort into keeping 32 bit supported or not. And imho. this decision then needs to be communicated to the community. "Not recommending" 32 bit is all nice and good, but for people like me, who are running 32 bit hardware that recommendation is of no use.

**Comment by Slartibartfast27** [comment] 2022-11-01 17:30
> And I hate to be that guy, but imho you really should rethink your backup/rollback strategy. Something like this can happen, all the time. And recovering from it _should_ be not more than a minor inconvenience.

Hello @j-be , thanks for the link to the fix  ;-) This worked also for me.
I already have backups (daily tgz-Backup of the database + files to a NAS with Snapshots, mirrored to a remote location), which I could restore within a few minutes, **if I knew there is a problem**. But my zabbix monitoring did not report any problems watching http://nextcloud....com/status.php for expected content `"installed":true,"maintenance":false,"needsDbUpgrade":false`

BUT: I primarly use the calender. Sometimes I don't use files for weeks. So it might happen, that I do not recognize a problem with files for weeks, which makes a rollback barely impossible without loosing potentially weeks of calendar changes.

From my perspective it would be ideal, if nextcloud would not start at all anymore if the system is not compatible. Then it would be easy to rollback.

**Closed** 2022-11-03 12:00 UTC
Labels: bug, 2. developing, regression, 25-feedback

**Comment by yuriry** [comment] 2022-11-18 05:56
> Most importantly the update to NC25 should then not be offered on 32-bit systems.
> 
So true!  My server is armv7l, and it'll be a while before I can upgrade to 64 bit.  Just ran into this problem after upgrading to v25 - v24 is still offering an upgrade for 32 bit systems :(

**Comment by MichaIng** [comment] 2022-11-18 09:22
With next Nextcloud 25.0.2 32-bit will work again, and the upgrade blocker to v26 is already in place: https://github.com/nextcloud/server/commit/c124456

**Comment by rsudev** [comment] 2022-11-24 18:28
I also only today observed that the file sync was broken after recently upgrading to 25.0.1...
Thanks for re-instating the 32bit support on the already rolled out version!

I am looking into an upgrade to 64bit hardware as well, but this will take some more month to happen (I run nextcloud on my NAS)

**Comment by zeekoe** [comment] 2022-11-25 09:45
Thanks a lot for fixing this, it took me some time to find out what the issue was. I don't plan to upgrade my hardware (armv7l, as most of us) any time soon, so really hoping for a 32 bit LTS NC 25... :) If it needs some paid subscription to be viable, let me know and I surely would consider.

**Comment by szaimen** [comment] 2022-11-29 18:26
https://help.nextcloud.com/t/deprecation-of-32-bit-support-ends-completely-with-nextcloud-26/150926

**Comment by lapineige** [comment] 2022-12-15 19:36
Problem still here : https://github.com/nextcloud/server/pull/34905#issuecomment-1345359143

Maybe this should be reopened ?

**Comment by MichaIng** [comment] 2022-12-17 23:39
The issue when using a quota did not exist before NC25?

**Comment by lapineige** [comment] 2022-12-18 09:29
It did not.

**Comment by MichaIng** [comment] 2022-12-20 03:54
PR up: #35832

**Comment by lapineige** [comment] 2022-12-20 10:08
Replaced by https://github.com/nextcloud/server/pull/35734

Thanks a lot !
