### ISSUE TITLE
First run wizard not accessible from knowledgebase

### ISSUE THREAD

**Issue by J0WI** [nextcloud/server#17396] opened 2019-10-03 22:58 UTC
### Steps to reproduce
1. login
2. goto user menu -> help (knowledgebase)
3. goto user menu -> about (first run wizard)

### Expected behaviour
first run wizard should start

### Actual behaviour
page reloads, knowledgebase is shown again

### Server configuration
_doesn't matter, can reproduce in a fresh installation_

**Comment by szaimen** [comment] 2021-05-26 13:22
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-26 13:22 UTC
Labels: 0. Needs triage, bug, low
