### ISSUE TITLE
Drag / Drop Resources to different folders

### ISSUE THREAD

**Issue by compumatter** [nextcloud/server#6404] opened 2017-09-07 15:10 UTC
Using Nextcloud 12

I am desiring to select multiple images and easily move them from one folder to another.

I have not found a way to do this other than by using the Files copy plugin.

However, because the thumbnails as shown here https://compumatter.com/test/nextcloud/tiny-thumbnails.png are so small, it is not a simple matter to identify what images need moving.

So my request is for a built in Drag / Drop interface or increased thumbnails to accomplish this.

Thanks.

Jay

**Comment by MorrisJobke** [comment] 2017-09-08 01:50
Duplicate of #6403 and #2779 (latter one is fixed for 13 in #6273)

**Closed by MorrisJobke** 2017-09-08 01:50 UTC
Labels: feature: files
