### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by thimberwolf** [nextcloud/server#19551] opened 2020-02-19 17:48 UTC
I receive this: 
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `o`.`id` FROM `oc_flow_operations` `o` LEFT JOIN `oc_flow_operations_scope` `s` ON `o`.`id` = `s`.`operation_id` WHERE `s`.`operation_id` IS NULL': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd02e7e71.oc_flow_operations_scope' doesn't exist

Do you have an idea ?

**Comment by kesselb** [comment] 2020-02-19 18:48
Please use the search. There are some reports with solution around.

**Comment by kesselb** [comment] 2020-03-03 21:04
Duplicate of https://github.com/nextcloud/server/issues/18265

**Closed by kesselb** 2020-03-03 21:04 UTC
Labels: 18-feedback, needs info
