### ISSUE TITLE
[Bug]: Uninstall apps

### ISSUE THREAD

**Issue by gabrielbdcxd** [nextcloud/server#49340] opened 2024-11-17 23:47 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating from Nextcloud 30.0.1 to 30.0.2, I am no longer able to delete apps via the web interface.

Additionally, when attempting to remove apps through the terminal, the process doesn't work as expected. If I disable an app first and then try to remove it, the removal fails. However, if the app is still enabled and I run the command to remove it, it successfully disables and removes the app.

### Steps to reproduce

@nextcloud:/var/www/html$ sudo -u www-data php occ app:disable contacts
contacts disabled
@nextcloud:/var/www/html$ sudo -u www-data php occ app:remove contacts
contacts is not installed

if contatos enable
@nextcloud:/var/www/html$ sudo -u www-data php occ app:remove contacts
contacts disabled
contacts 6.1.1 removed

### Expected behavior

@nextcloud:/var/www/html$ sudo -u www-data php occ app:disable contacts
contacts disabled
@nextcloud:/var/www/html$ sudo -u www-data php occ app:remove contacts
contacts 6.1.1 removed

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by joshtrichards** [comment] 2024-11-18 01:14
Duplicate of #49193 

Unless this was really against the current `master` branch as you state in your report?

> Nextcloud Server version
>
> master

**Closed by joshtrichards** 2024-11-18 01:14 UTC
Labels: bug, 0. Needs triage
