### ISSUE TITLE
SameOrganizerForAllComponentsException

### ISSUE THREAD

**Issue by esprit-libre** [nextcloud/server#7530] opened 2017-12-15 09:18 UTC
Linked to [#683](https://github.com/nextcloud/calendar/issues/683)
### Steps to reproduce
Not sure because it comes from a customer
1. Create a recurrent event in a shared calendar, with no end date. User that creates it is not the owner of the calendar
2. Edit the event with another user, also not the owner of the calendar
3. Edit again with any other user

### Expected behaviour
Modification should works without errors.

### Actual behaviour
SameOrganizerForAllComponentsException is thrown

### Server configuration
**Operating system**:
Debian 9
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.0.19
**Server version:** (see your admin page)
12.0.2
**Calendar version:** (see the apps page)
1.5.7

**Are you using encryption:** yes/no
No

### Client configuration
**Browser:**
Any (Thunderbird+Lightning, Firefox)
**Operating system:**
Ubuntu and Windows tested

#### Log file (data/nextcloud.log)
```
{"reqId":"FjOEMcc23SglbJ5bGKvC","level":4,"time":"2017-12-14T16:49:14+01:00","remoteAddr":"109.190.199.43","user":"espritlibre","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/calendars\/espritlibre\/personnel_shared_by_AlterBative\/l1lqont3fu4bosvu7meohnf47o%40google.com.ics","message":"Exception: {\"Exception\":\"Sabre\\\\VObject\\\\ITip\\\\SameOrganizerForAllComponentsException\",\"Message\":\"Every instance of the event must have the same organizer.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/ITip\\\/Broker.php(180): Sabre\\\\VObject\\\\ITip\\\\Broker->parseEventInfo(Object(Sabre\\\\VObject\\\\Component\\\\VCalendar))\\n#1 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Schedule\\\/Plugin.php(427): Sabre\\\\VObject\\\\ITip\\\\Broker->parseEvent(NULL, Array, Object(Sabre\\\\VObject\\\\Component\\\\VCalendar))\\n#2 [internal function]: Sabre\\\\CalDAV\\\\Schedule\\\\Plugin->beforeUnbind('calendars\\\/espri...')\\n#3 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(286): Sabre\\\\Event\\\\EventEmitter->emit('beforeUnbind', Array)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#8 \\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/alterbative\\\/www\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/alterbative\\\/www\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/home\\\/alterbative\\\/www\\\/remote.php(162): require_once('\\\/home\\\/alterbative....')\\n#12 {main}\",\"File\":\"\\\/home\\\/alterbative\\\/www\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/ITip\\\/Broker.php\",\"Line\":871}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Thunderbird\/52.5.0 Lightning\/5.4","version":"12.0.2.0"}
```

#### Database analysis
I notice below extract, which could explain the exception. I only quote some lines.
```
MariaDB [cloud]> select * from oc_calendarobjects_props where objectid=1 and name="ORGANIZER";
| id  | calendarid | objectid | name        | parameter |  value  
|   3 |          2 |        1 | ORGANIZER   | NULL      | mailto:user1@domain.com
...
|   7 |          2 |        1 | ORGANIZER   | NULL      | mailto:user1@domain.com
|   8 |          2 |        1 | ORGANIZER   | CN        | user1@domain.com
...
|  12 |          2 |        1 | ORGANIZER   | NULL      | mailto:user2@domain.com
|  13 |          2 |        1 | ORGANIZER   | CN        | user2@domain.com
...
|  17 |          2 |        1 | ORGANIZER   | NULL      | mailto:user3@domain.com
|  18 |          2 |        1 | ORGANIZER   | CN        | user3@domain.com
...
|  22 |          2 |        1 | ORGANIZER   | NULL      | mailto:user1@domain.com
|  23 |          2 |        1 | ORGANIZER   | CN        | user1@domain.com
...
// all others are with user1 mail and not "CN" line
```

**Comment by MorrisJobke** [comment] 2017-12-15 09:27
cc @georgehrke

**Comment by MorrisJobke** [comment] 2018-06-19 15:30
As we can't reproduce this I will close this for now. If you have further steps on how to trigger it we are happy to assist.

If you wish support with this issue from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Closed by MorrisJobke** 2018-06-19 15:30 UTC
