### ISSUE TITLE
[Bug]: File details don't show / sharing doesn't work

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/server#44128] opened 2024-03-11 15:10 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Files I try to show the file details or share a file. The sidebar loads endlessly:

![Screenshot 2024-03-11 at 15-59-23 Dateien - plan neo cloud](https://github.com/nextcloud/server/assets/367592/f1c8a0aa-65c2-4b2a-b0b5-6b63e2ee65d1)

### Steps to reproduce

1. I click on the three dots next to a folder or files
2. I choose "Details öffnen"
3. Sidebar opens, nothing is displayed

Nextcloud tries to load https://MYDOMAIN.COM/core/js/merged-template-prepend.js which fails with an error 500 - Is seems this files doesn't even exist - there is no merged-template-prepend.js only a .json

When I try to open the sidebar, this error appears in the console:

TypeError: OC.MimeType is undefined
    getIconUrl Sidebar.vue:377
    getPreviewIfAny Sidebar.vue:351
    background Sidebar.vue:242
    VueJS 3
    appSidebar Sidebar.vue:256
    VueJS 3
    dt Sidebar.vue:1
    VueJS 14
    open Sidebar.vue:484
    exec sidebarAction.ts:49
    onActionClick FileEntryActions.vue:171
    click FileEntryActions.vue:4
    VueJS 4
    onClick actionText-bMy_49i8.mjs:118
    handleClick NcActionButton.mjs:113
    VueJS 33

### Expected behavior

Sidebar opens, something is displayed

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Disabled all - problem remains
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by dathbe** [comment] 2024-04-07 15:26
I'm having this same issue.  As far as I recall, it started when I upgraded to the latest major version (28).

**Comment by excedra** [comment] 2024-04-09 14:25
Same issue here. 

If the file has a thumbnail, the sidebar works as usual. 
As most times folders are shared, this isn't really a workaround.

**Comment by joshtrichards** [comment] 2024-04-10 02:11
Hi. This isn't readily reproducible so far.

Please provide further details:

- What installation method?
- What is your config? (`occ config: list system`)
- Please provide your app list? (`occ app:list`)
- The associated Nextcloud log entry? (A 500 error doesn't come from nowhere; if it's coming from Nextcloud it'll be logged)

Also worth checking if any earnings/error visible under *Administration settings -> Overview*.

**Comment by ntltdev** [comment] 2024-04-10 05:55
Here is the systeminfo and app-list. I removed all unnessecary lines.

# Systeminfo
```
occ config:list system
{
    "system": {
        "dbtype": "mysql",
        "version": "28.0.4.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "26",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "default_phone_region": "DE",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "port": 6379,
            "dbindex": 0,
            "timeout": 1.5
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "auth.bruteforce.protection.enabled": false,
        "maintenance_window_start": 1,
        "app_install_overwrite": [
            "files_rightclick"
        ]
    }
}
```
# App-List
## Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - dav: 1.29.1
  - drawio: 3.0.2
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - groupfolders: 16.0.6
  - imageconverter: 2.0.1
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - oauth2: 1.16.3
  - photos: 2.4.0
  - previewgenerator: 5.5.0
  - provisioning_api: 1.18.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
  
## Disabled:
  - bruteforcesettings: 2.8.0 (installed 2.8.0)
  - checksum: 1.2.4 (installed 1.2.4)
  - circles: 28.0.0 (installed 28.0.0)
  - contactsinteraction: 1.9.0 (installed 1.1.0)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0
  - external: 5.3.1 (installed 5.3.1)
  - extract: 1.3.6 (installed 1.3.6)
  - federation: 1.18.0 (installed 1.5.0)
  - files_external: 1.20.0
  - files_reminders: 1.1.0 (installed 1.1.0)
  - firstrunwizard: 2.17.0 (installed 2.5.0)
  - impersonate: 1.15.0 (installed 1.15.0)
  - keeweb: 0.6.17 (installed 0.6.17)
  - metadata: 0.19.0 (installed 0.19.0)
  - nextcloud_announcements: 1.17.0 (installed 1.5.0)
  - notifications: 2.16.0 (installed 2.16.0)
  - passman: 2.4.8 (installed 2.4.8)
  - password_policy: 1.18.0 (installed 1.18.0)
  - privacy: 1.12.0 (installed 1.12.0)
  - quota_warning: 1.19.0 (installed 1.19.0)
  - ransomware_detection: 0.10.0 (installed 0.10.0)
  - recommendations: 2.0.0 (installed 0.4.0)
  - related_resources: 1.3.0 (installed 1.3.0)
  - support: 1.11.1 (installed 1.0.0)
  - survey_client: 1.16.0 (installed 1.3.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.10.0)
  - terms_of_service: 2.4.0 (installed 2.4.0)
  - text: 3.9.1 (installed 3.1.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1 (installed 1.0.1)
  - weather_status: 1.8.0 (installed 1.0.0)

**Comment by ntltdev** [comment] 2024-04-10 14:43
In `js/core/merged-template-prepend.js line 77` OC.MimeTypeList was 'undefined'
The fix: 
```
sudo -u www-data php occ maintenance:mimetype:update-js
sudo -u www-data php occ maintenance:repair
```

**Comment by joshtrichards** [comment] 2024-04-10 20:25
> Nextcloud tries to load https://mydomain.com/core/js/merged-template-prepend.js which fails with an error 500 - Is seems this files doesn't even exist - there is no merged-template-prepend.js only a .json
>
> When I try to open the sidebar, this error appears in the console:
>
> `TypeError: OC.MimeType is undefined`

@kaffeeringe  `merged-templated-prepend.js` generated on-demand. The 500 implies the generation failed for some reason. Please look at your Nextcloud log for hints. Also, your installation and upgrade method are potentially highly relevant here. Any chance you're running a custom version of our Docker image?

@ntltdev A standard update run would have triggered those `maintenance` functions on their own. How did you upgrade?

**Comment by dathbe** [comment] 2024-04-12 17:21
> The fix:
> 
> ```
> sudo -u www-data php occ maintenance:mimetype:update-js
> sudo -u www-data php occ maintenance:repair
> ```

This did not fix my issue.  I'm still getting endless circling when I try to share, and when I try to display info in the sidebar.

**Comment by vafanassieff** [comment] 2024-05-06 13:53
Same thing happening here

```
7store.js:45 TypeError: Cannot read properties of undefined (reading 'getIconUrl')
    at s.data (RecommendedFile.vue:90:1)
    at vue.runtime.esm.js:5484:21
    at vue.runtime.esm.js:5448:42
    at qn (vue.runtime.esm.js:5389:9)
    at t._init (vue.runtime.esm.js:5714:9)
    at new s (vue.runtime.esm.js:5849:18)
    at vue.runtime.esm.js:4564:12
    at init (vue.runtime.esm.js:4426:52)
    at vue.runtime.esm.js:6591:17
    at p (vue.runtime.esm.js:6545:13)
ke @ vue.runtime.esm.js:3065
je @ vue.runtime.esm.js:3057
Pe @ vue.runtime.esm.js:3024
(anonymous) @ vue.runtime.esm.js:5487
(anonymous) @ vue.runtime.esm.js:5448
qn @ vue.runtime.esm.js:5389
t._init @ vue.runtime.esm.js:5714
s @ vue.runtime.esm.js:5849
(anonymous) @ vue.runtime.esm.js:4564
init @ vue.runtime.esm.js:4426
(anonymous) @ vue.runtime.esm.js:6591
p @ vue.runtime.esm.js:6545
g @ vue.runtime.esm.js:6664
p @ vue.runtime.esm.js:6568
g @ vue.runtime.esm.js:6664
p @ vue.runtime.esm.js:6568
g @ vue.runtime.esm.js:6664
p @ vue.runtime.esm.js:6568
(anonymous) @ vue.runtime.esm.js:7133
t._update @ vue.runtime.esm.js:3785
r @ vue.runtime.esm.js:3891
t.get @ vue.runtime.esm.js:3462
t.run @ vue.runtime.esm.js:3538
wn @ vue.runtime.esm.js:4141
(anonymous) @ vue.runtime.esm.js:3159
Ue @ vue.runtime.esm.js:3081
Promise.then (async)
$e @ vue.runtime.esm.js:3106
He @ vue.runtime.esm.js:3171
xn @ vue.runtime.esm.js:4227
t.update @ vue.runtime.esm.js:3529
t.notify @ vue.runtime.esm.js:732
set @ vue.runtime.esm.js:976
loading @ store.js:45
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
ua._withCommit @ vuex.esm.js:624
ua.commit @ vuex.esm.js:464
commit @ vuex.esm.js:409
fetchRecommendations @ store.js:87
await in fetchRecommendations (async)
(anonymous) @ vuex.esm.js:851
ua.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
render @ main.js:43
mounted @ FilesListHeader.vue:41
un @ vue.runtime.esm.js:3033
Zn @ vue.runtime.esm.js:4048
insert @ vue.runtime.esm.js:4443
w @ vue.runtime.esm.js:6966
wi.nodeOps @ vue.runtime.esm.js:7180
e._update @ vue.runtime.esm.js:3785
a @ vue.runtime.esm.js:3891
e.get @ vue.runtime.esm.js:3462
e.run @ vue.runtime.esm.js:3538
na @ vue.runtime.esm.js:4141
(anonymous) @ vue.runtime.esm.js:3159
gn @ vue.runtime.esm.js:3081
Promise.then (async)
hn @ vue.runtime.esm.js:3106
Fn @ vue.runtime.esm.js:3171
aa @ vue.runtime.esm.js:4227
e.update @ vue.runtime.esm.js:3529
e.notify @ vue.runtime.esm.js:732
Re @ vue.runtime.esm.js:1025
setRoot @ files.ts:49
(anonymous) @ pinia.mjs:1380
fetchContent @ FilesList.vue:327
await in fetchContent (async)
mounted @ FilesList.vue:288
un @ vue.runtime.esm.js:3033
Zn @ vue.runtime.esm.js:4048
insert @ vue.runtime.esm.js:4443
w @ vue.runtime.esm.js:6966
wi.nodeOps @ vue.runtime.esm.js:7180
e._update @ vue.runtime.esm.js:3781
a @ vue.runtime.esm.js:3891
e.get @ vue.runtime.esm.js:3462
e @ vue.runtime.esm.js:3452
e @ vue.runtime.esm.js:3908
Ya.$mount @ vue.runtime.esm.js:8797
73348 @ main.ts:33
o @ bootstrap:19
(anonymous) @ files-main.js?v=7177bcd5-10:2
o.O @ chunk loaded:25
(anonymous) @ files-main.js?v=7177bcd5-10:2
(anonymous) @ files-main.js?v=7177bcd5-10:2
Show 71 more frames
Show less
Sidebar.vue:473 TypeError: Cannot read properties of undefined (reading 'getIconUrl')
    at o.getIconUrl (Sidebar.vue:370:1)
    at o.getPreviewIfAny (Sidebar.vue:340:1)
    at o.background (Sidebar.vue:234:1)
    at e.get (vue.runtime.esm.js:3462:33)
    at e.evaluate (vue.runtime.esm.js:3563:27)
    at o.background (vue.runtime.esm.js:5557:25)
    at o.appSidebar (Sidebar.vue:247:1)
    at e.get (vue.runtime.esm.js:3462:33)
    at e.evaluate (vue.runtime.esm.js:3563:27)
    at o.appSidebar (vue.runtime.esm.js:5557:25)
    ```

**Comment by moboter** [comment] 2024-06-12 11:25
sudo -u www-data php occ maintenance:mimetype:update-js
mimetypelist.js is updated

sudo -u www-data php occ maintenance:repair
- Repair MySQL collation
     - All tables already have the correct collation -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Move .step file of updater to backup location
 - Add move avatar background job
     - Repair step already executed
 - Add preview cleanup background jobs
 - Migrate oauth2_clients table to nextcloud schema
     - Update the oauth2_access_tokens table schema.
     - Update the oauth2_clients table schema.
     - Delete clients (and their related access tokens) with the redirect_uri starting with oc:// or ending with *
 - Fix potential broken mount points
     - No mounts updated
 - Repair language codes
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - JS cache cleared
 - Clear every generated avatar
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Cleanup invalid photocache files for carddav
 - Add background job to cleanup login flow v2 tokens
 - Remove potentially over exposing share links
     - No need to remove link shares.
 - Clear access cache of projects
 - Reset generated avatar flag
 - Keep legacy encryption enabled
 - Check encryption key format
 - Remove old dashboard app config data
 - Add job to cleanup the bruteforce entries
 - Queue a one-time job to check for user uploaded certificates
 - Repair DAV shares
 - Add background job to set the lookup server share state for users
 - Add token cleanup job
 - Clean up abandoned apps
 - Add possibly missing system config
 - Add AI tasks cleanup job
 - Queue a job to generate metadata
 - Add read permissions for existing announcements
    0 [->--------------------------]
 - Update hook for Appointments app
     - appointments UpdateHook finished
 - Upgrading Circles App
 - Fix component of birthday calendars
     - 1 birthday calendars updated.
 - Regenerating birthday calendars to use new icons and fix old birthday events without year
     - Repair step already executed
 - Fix broken values of calendar objects
    0 [----->----------------------]
 - Registering building of calendar search index as background job
     - Repair step already executed
 - Register building of social profile search index as background job
     - Add background job
 - Registering background jobs to update cache for webcal calendars
     - Added 0 background jobs to update webcal calendars
 - Registering building of calendar reminder index as background job
     - Repair step already executed
 - Clean up orphan event and contact data
     - 0 events without a calendar have been cleaned up
     - 0 properties without an events have been cleaned up
     - 0 changes without a calendar have been cleaned up
     - 0 cached events without a calendar subscription have been cleaned up
     - 0 changes without a calendar subscription have been cleaned up
     - 0 contacts without an addressbook have been cleaned up
     - 0 properties without a contact have been cleaned up
     - 0 changes without an addressbook have been cleaned up
 - Remove activity entries of private events
     - Removed 0 activity entries
 - Clean up old calendar subscriptions from deleted users that were not cleaned-up
    0 [--------->------------------]
     - 0 calendar subscriptions without an user have been cleaned up
 - Remove invalid object properties
     - 0 invalid object properties removed.
 - Fix the share type of guest shares when migrating from ownCloud
 - Copy the share password into the dedicated column
 - Set existing shares as accepted
 - Update OAuth token expiration times
 - Polls - Drop orphaned tables
     - No orphaned tables found
 - Polls - Drop orphaned columns
     - No orphaned columns found
 - Polls - Create hashes for votes and options
     - Updated 86 option hashes
     - Updated 322 vote hashes
 - Polls - Delete duplicates and orphaned records
 - Polls - Create indices and foreign key constraints
     - Added oc_polls_polls['poll_id'] <- oc_polls_comments['id']
     - Added oc_polls_polls['poll_id'] <- oc_polls_log['id']
     - Added oc_polls_polls['poll_id'] <- oc_polls_notif['id']
     - Added oc_polls_polls['poll_id'] <- oc_polls_options['id']
     - Added oc_polls_polls['poll_id'] <- oc_polls_share['id']
     - Added oc_polls_polls['poll_id'] <- oc_polls_votes['id']
     - Index UNIQ_options already exists in oc_polls_options
     - Index UNIQ_unprocessed already exists in oc_polls_log
     - Index UNIQ_subscription already exists in oc_polls_notif
     - Index UNIQ_shares already exists in oc_polls_share
     - Index UNIQ_votes already exists in oc_polls_votes
     - Index UNIQ_preferences already exists in oc_polls_preferences
     - Index UNIQ_watch already exists in oc_polls_watch
     - Index polls_polls_owners_non_deleted already exists in oc_polls_polls
     - Polls - Foreign key contraints created.
     - Polls - Indices created.
 - Create help command
 - Invalidate access cache for projects conversation provider
     - Invalidation not required
 - Cache the user display names
 - Switches from default updater server to the customer one if a valid subscription is available
     - Repair step already executed
 - Send an admin notification if monthly report is disabled
 - Force-reset all Text sessions before Yjs migration
 - Initialize migration of background images from dashboard to theming app
 - Add background job to check for backup codes
 - Populating added database structures for workflows

Problem ist still there
Nextcloud28.0.6
PHP 8.1.2
Apache 2.4.52
10.6.16-MariaDB-0
ubuntu0.22.04.1 (alle Pakete aktuell )

**Comment by moboter** [comment] 2024-06-12 11:32
Opening the Details of a folder doesnt work  So you cant share opening a file and then details does work .
So sharing doesnt work for a folder but it does work for a single file

**Comment by dathbe** [comment] 2024-06-12 16:24
See also #45584

**Comment by moboter** [comment] 2024-06-13 06:38
Interesting FAct When you change in Chrome to 
![grafik](https://github.com/nextcloud/server/assets/87427090/2c07cabe-713d-4a05-b3e5-93b698486fbe)
sharing suddenly works at least in Chrome

![grafik](https://github.com/nextcloud/server/assets/87427090/3d3701bf-87a1-40d0-8b9f-9ff0587ac4d8)

**Comment by moboter** [comment] 2024-06-13 06:50
In Microsoft Edge I reloaded the Page in IE Kompatibily mode and there it works now as well

**Comment by muribybs** [comment] 2024-06-13 10:38
Same issue in Version Nextcloud Hub 8 29.0.2.

**Comment by dathbe** [comment] 2024-06-13 15:05
> In Microsoft Edge I reloaded the Page in IE Kompatibily mode and there it works now as well

This is not working for me in either Edge or Chrome (previous post).  I'm still getting endless circling with the mobile view in Chrome.  And I can't even get the main page to load in IE Compatibility mode.  It just shows me the link to the Nextcloud corporate website.

**Comment by kaffeeringe** [comment] 2024-06-13 19:35
BTW: I works form me now, since the update to 29.0.0Am 13.06.24, 17:06 schrieb dathbe ***@***.***>:

   
   
   In Microsoft Edge I reloaded the Page in IE Kompatibily mode and there it works now as well 
   
  This is not working for me in either Edge or Chrome (previous post). I'm still getting endless circling with the mobile view in Chrome. And I can't even get the main page to load in IE Compatibility mode. It just shows me the link to the Nextcloud corporate website.

**Comment by moboter** [comment] 2024-06-18 15:11
I updated two apps totay  collectives: 2.12.0 and polls: 7.1.1
Sharing works again via all Browsers again
You now have to save the share then the mail is sent

**Comment by dathbe** [comment] 2024-06-18 15:22
I don't have any apps to update, and I can still only share through the mobile app.

**Comment by muribybs** [comment] 2024-06-19 08:45
> I updated two apps totay collectives: 2.12.0 and polls: 7.1.1 Sharing works again via all Browsers again You now have to save the share then the mail is sent

I also updated both apps (Polls and Collective) but still the same issue with the newer ending loading circle.

**Comment by joshtrichards** [comment] 2024-07-24 20:54
There are likely multiple situations being described here. It's likely not all of you are encountering the same situation.

The inability to pull in these JavaScript files would result in similar errors in the console and browser, but the root cause depends on precisely why you're not getting these files.

In some cases this has been due to a web server misconfiguration. I think those would typically be 404 errors (not the 500).  For example, if you're running Nextcloud via an LSIO Docker image, you may need to refer to their docs and update your Nginx config since there was an issue a bit back there.

For the ones seeing 500 errors, well, error logs from the web server and Nextcloud would be necessary. 

The OP reported their matter fixed: https://github.com/nextcloud/server/issues/44128#issuecomment-2166626830 so anyone experiencing this s should probably take this to the help forum to try to isolate whether this is a bug or a configuration matter in their particular case - https://help.nextcloud.com

**Closed by joshtrichards** 2024-07-24 20:54 UTC
Labels: bug, feature: sharing, 0. Needs triage, feature: files, feature: file sidebar, 28-feedback

**Comment by dathbe** [comment] 2024-07-24 21:21
> if you're running Nextcloud via an LSIO Docker image, you may need to refer to their docs and update your Nginx config since there was an issue a bit back there.

YAY!  This seems to have been my issue.  I deleted `/config/nginx/nginx.conf` and `/config/nginx/site-confs/default.conf` and restarted my container.  New versions of these files were loaded and voila, I had sharing again!

Thanks so much!

**Comment by muribybs** [comment] 2024-07-25 11:29
@joshtrichards and @dathbe thank you so much. It is solves now on my unraid server.
I deleted 
/appdata/nextcloud/nginx/nginx.conf
and /appdata/nextcloud/nginx/site-confs/default.conf
Aftrer that I restarted my dockers and it worked :)

**Comment by LCerebo** [comment] 2024-11-28 18:40
> > if you're running Nextcloud via an LSIO Docker image, you may need to refer to their docs and update your Nginx config since there was an issue a bit back there.
> 
> YAY! This seems to have been my issue. I deleted `/config/nginx/nginx.conf` and `/config/nginx/site-confs/default.conf` and restarted my container. New versions of these files were loaded and voila, I had sharing again!
> 
> Thanks so much!

Thanks! This fixed the issue.
