### ISSUE TITLE
v22.2.0 Error: `dns_get_record()`: A temporary server error occurred

### ISSUE THREAD

**Issue by EduardoOsquel** [nextcloud/server#29076] opened 2021-10-04 22:44 UTC
Im on Nextcloud 22.2.0 and still having this system message:

```
[PHP] Error: dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#57

{
   "reqId":"hrlJNgh8o67DHpSBPW5X",
   "level":3,
   "time":"2021-10-04T22:41:37+00:00",
   "remoteAddr":"10.20.0.99",
   "user":"root",
   "app":"PHP",
   "method":"GET",
   "url":"/index.php/settings/ajax/checksetup",
   "message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#83",
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
   "version":"22.2.0.2",
   "exception":{
      "Exception":"Error",
      "Message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#83",
      "Code":0,
      "Trace":[
         {
            "function":"onError",
            "class":"OC\\Log\\ErrorHandler",
            "type":"::",
            "args":[
               2,
               "dns_get_record(): A temporary server error occurred.",
               "/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php",
               83,
               {
                  "0":"And 2 more entries, set log level to debug to see all entries",
                  "target":"www.nextcloud.com",
                  "recursionCount":1,
                  "targetIps":[
                     
                  ],
                  "soaDnsEntry":null,
                  "dnsNegativeTtl":null
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php",
            "line":83,
            "function":"dns_get_record",
            "args":[
               "www.nextcloud.com",
               1
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php",
            "line":128,
            "function":"dnsResolve",
            "class":"OC\\Http\\Client\\DnsPinMiddleware",
            "type":"->",
            "args":[
               "www.nextcloud.com",
               1
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php",
            "line":35,
            "function":"OC\\Http\\Client\\{closure}",
            "class":"OC\\Http\\Client\\DnsPinMiddleware",
            "type":"->",
            "args":[
               "*** sensitive parameters replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
            "line":31,
            "function":"__invoke",
            "class":"GuzzleHttp\\PrepareBodyMiddleware",
            "type":"->",
            "args":[
               "*** sensitive parameter replaced ***",
               "*** sensitive parameter replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php",
            "line":71,
            "function":"GuzzleHttp\\{closure}",
            "class":"GuzzleHttp\\Middleware",
            "type":"::",
            "args":[
               "*** sensitive parameters replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
            "line":63,
            "function":"__invoke",
            "class":"GuzzleHttp\\RedirectMiddleware",
            "type":"->",
            "args":[
               "*** sensitive parameter replaced ***",
               "*** sensitive parameter replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php",
            "line":75,
            "function":"GuzzleHttp\\{closure}",
            "class":"GuzzleHttp\\Middleware",
            "type":"::",
            "args":[
               "*** sensitive parameters replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php",
            "line":331,
            "function":"__invoke",
            "class":"GuzzleHttp\\HandlerStack",
            "type":"->",
            "args":[
               "*** sensitive parameter replaced ***",
               "*** sensitive parameter replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php",
            "line":168,
            "function":"transfer",
            "class":"GuzzleHttp\\Client",
            "type":"->",
            "args":[
               "*** sensitive parameter replaced ***",
               "*** sensitive parameter replaced ***"
            ]
         },
         {
            "file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php",
            "line":187,
            "function":"requestAsync",
            "class":"GuzzleHttp\\Client",
            "type":"->",
            "args":[
               "get",
               {
                  "__class__":"GuzzleHttp\\Psr7\\Uri"
               },
               {
                  "0":"And 7 more entries, set log level to debug to see all entries",
                  "verify":"/var/www/nextcloud/resources/config/ca-bundle.crt",
                  "timeout":30,
                  "allow_redirects":{
                     "on_redirect":{
                        "__class__":"Closure"
                     }
                  },
                  "proxy":{
                     "http":"sensitive parameter",
                     "https":"sensitive parameter"
                  },
                  "nextcloud":{
                     "allow_local_address":false
                  }
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Http/Client/Client.php",
            "line":223,
            "function":"request",
            "class":"GuzzleHttp\\Client",
            "type":"->",
            "args":[
               "get",
               "https://www.nextcloud.com/",
               {
                  "0":"And 2 more entries, set log level to debug to see all entries",
                  "verify":"/var/www/nextcloud/resources/config/ca-bundle.crt",
                  "timeout":30,
                  "allow_redirects":{
                     "on_redirect":{
                        "__class__":"Closure"
                     }
                  },
                  "proxy":{
                     "http":"sensitive parameter",
                     "https":"sensitive parameter"
                  },
                  "nextcloud":{
                     "allow_local_address":false
                  }
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php",
            "line":180,
            "function":"get",
            "class":"OC\\Http\\Client\\Client",
            "type":"->",
            "args":[
               "https://www.nextcloud.com/"
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php",
            "line":162,
            "function":"isSiteReachable",
            "class":"OCA\\Settings\\Controller\\CheckSetupController",
            "type":"->",
            "args":[
               "www.nextcloud.com"
            ]
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php",
            "line":746,
            "function":"hasInternetConnectivityProblems",
            "class":"OCA\\Settings\\Controller\\CheckSetupController",
            "type":"->",
            "args":[
               
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":217,
            "function":"check",
            "class":"OCA\\Settings\\Controller\\CheckSetupController",
            "type":"->",
            "args":[
               
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":126,
            "function":"executeController",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               {
                  "__class__":"OCA\\Settings\\Controller\\CheckSetupController"
               },
               "check"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/App.php",
            "line":156,
            "function":"dispatch",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->",
            "args":[
               {
                  "__class__":"OCA\\Settings\\Controller\\CheckSetupController"
               },
               "check"
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/private/Route/Router.php",
            "line":301,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::",
            "args":[
               "OCA\\Settings\\Controller\\CheckSetupController",
               "check",
               {
                  "__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"
               },
               {
                  "_route":"settings.CheckSetup.check"
               }
            ]
         },
         {
            "file":"/var/www/nextcloud/lib/base.php",
            "line":1000,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->",
            "args":[
               "/settings/ajax/checksetup"
            ]
         },
         {
            "file":"/var/www/nextcloud/index.php",
            "line":36,
            "function":"handleRequest",
            "class":"OC",
            "type":"::",
            "args":[
               
            ]
         }
      ],
      "File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
      "Line":92,
      "CustomMessage":"--"
   },
   "id":"615b83219d7e0"
}
```

I need to know what is happening here on server... also I see that System and security check never ends on this last version. The previous version works without troubles!

**Comment by acsfer** [comment] 2021-10-05 07:39
Duplicate of https://github.com/nextcloud/server/issues/28105
(yes, this is not completely fixed yet)

**Closed by acsfer** 2021-10-05 07:39 UTC
