### ISSUE TITLE
Enable sharing link creation before the upload has finished

### ISSUE THREAD

**Issue by tobias-lambrecht** [nextcloud/server#14075] opened 2019-02-07 08:54 UTC
Hi!

At least with the Mac OS sync client you have to wait until the file synchronisation is finished, before it is possible to create the sharing link. In Dropbox it is possible to create the link just after you have moved something into the folder.

If you have to share a lot of large files with different clients this can completely disturb your workflow. Imagine.... Upload 1 takes 30 minutes, so you have to remember, to create the link. In between you have started Upload 2 and 3 with also take their time, which  is added to the rest time of upload 1.....

Would be great if you could create these links immediately after moving files into the sync folder.

Thanks,
Tobias

**Comment by MorrisJobke** [comment] 2019-02-26 13:45
Most likely a duplicate of https://github.com/nextcloud/desktop/issues/1061 otherwise we can move this ticket over to the desktop client issue and reopen it.

**Comment by tobias-lambrecht** [comment] 2019-02-27 13:49
@MorrisJobke I would say if you solve this one nextcloud/desktop#1061 is also solved. But not the other way round.

I would like to get the sharing link before any sync is finished.

**Comment by MorrisJobke** [comment] 2019-02-27 14:41
> I would like to get the sharing link before any sync is finished.

Technically harder to accomplish, because this needs also a new API in the server itself. Could you propose this in the nextcloud/server repo: "Allow to get a public link share for a future file".

**Comment by tobias-lambrecht** [comment] 2019-02-27 15:01
Hmm, I thought it is the nextcloud/server repro ..... so what should I do?

**Comment by MorrisJobke** [comment] 2019-02-27 15:09
> Hmm, I thought it is the nextcloud/server repro ..... so what should I do?

🙈 Sorry - my fault. Let's reopen.

**Comment by MorrisJobke** [comment] 2019-02-27 15:09
cc @nextcloud/sharing for opinions on this one.

**Comment by tobias-lambrecht** [comment] 2019-02-27 17:15
Thanks ;)

**Comment by skjnldsv** [comment] 2020-11-07 23:48
Sorry, that is out of scope, that is too far from how our backend works and how we rely on it on the frontend :/

**Closed by skjnldsv** 2020-11-07 23:48 UTC
Labels: 0. Needs triage, client: 💻 desktop, client: 🤖🍏 mobile, enhancement, feature: sharing
