### ISSUE TITLE
[Bug]: Usability issue or Bug with the creation of files and folders.

### ISSUE THREAD

**Issue by daebak74** [nextcloud/server#43651] opened 2024-02-19 11:15 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Before version 28.0.2, the typing of the file or folder name was done from the menu at the time of creation. After the update, the file or folder is first added to the list and then the rename action must be performed.

With folders that include many subfolders and files, this operation of scrolling to the new folder or new document entry becomes very difficult.

Also, always after the update, the multiple actions menu related to the selected files, during the browser scroll, does not remain fixed at the top as it should be. To be able to perform a multiple action with the selected files, you have to scroll the screen to the top.

Also, the use in the search “filter in current view” does not help because it does not allow the use of the right button for the menu to perform the rename.

https://github.com/nextcloud/server/assets/11459528/5c0cb1ba-ad2a-4639-bab1-d9bedcc370f2

### Steps to reproduce

1. New File or Folder

### Expected behavior

New File or Folder with the scroll to the file or folder just created to rename

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2024-02-19 14:27
I belive this is fixed in 28.0.3. Maybe you can try the RC1?

**Comment by solracsf** [comment] 2024-02-19 19:04
Good. Please provide feedback once on v28.0.3. It will be released soon (days).

**Comment by susnux** [comment] 2024-02-24 22:35
Duplicate of #42097 . So resolved with 28.0.3

**Closed by susnux** 2024-02-24 22:35 UTC
Labels: bug, needs info, 0. Needs triage, feature: files, 28-feedback

**Comment by Luncheon3462** [comment] 2024-03-01 16:15
Not fixed in 28.0.3 While I can create a file name, the document does not open.   Correct behavior is creating a file name and then the document should open automatically.   NC27 works fine/appropriately.

**Comment by susnux** [comment] 2024-03-01 17:10
> Not fixed in 28.0.3 While I can create a file name, the document does not open. Correct behavior is creating a file name and then the document should open automatically. NC27 works fine/appropriately.

1. This is unrelated to this issue (allow to enter name before create)
2. This issue is a duplicate
