### ISSUE TITLE
persistent failed login warning

### ISSUE THREAD

**Issue by jelinj8** [nextcloud/server#14158] opened 2019-02-12 11:37 UTC
### Steps to reproduce
1. fail to login sveral times (pwd...) to display the warning
2. login correctly
3. logout, close browser TAB
4. open new tab in browser and open the instance URL

### Expected behaviour
aftere succesful login, the warning should be reset (hidden).

### Actual behaviour
Warning is still shown (even after closing and reopening browser, clearing cookies) and there is no 30s timeout (login works immediately, just a bit slow, probably because of HW limitations - just a VPS hosting).
Right after opening a new tab with instance base URL: 
![2019-02-12 12_31_51-bliksoft cloud](https://user-images.githubusercontent.com/3816495/52632593-48b70d80-2ec2-11e9-93cd-c9299492fb86.png)
The ajax rightclick unauthorized error goes away when I disable the "Files rightclick app", but the failed logins warning remains.

### Server configuration
Debian Stretch, Apache2, LDAP authentication against slapd

**Operating system**:
Win10, Chrome

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 15.0.2

**Where did you install Nextcloud from:**
nextcloud downloads

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - apporder: 0.6.0
  - audioplayer: 2.6.0
  - calendar: 1.6.4
  - circles: 0.16.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - deck: 0.5.2
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_automatedtagging: 1.5.0
  - files_external: 1.6.0
  - files_frommail: 0.2.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_readmemd: 1.0.1
  - files_rightclick: 0.11.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - flowupload: 0.0.9
  - gallery: 18.2.0
  - gpxedit: 0.0.10
  - gpxmotion: 0.0.8
  - gpxpod: 3.0.1
  - groupfolders: 2.0.2
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - music: 0.9.3
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - phonetrack: 0.4.3
  - polls: 0.9.5
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - sensorlogger: 0.0.9
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - socialsharing_facebook: 1.0.4
  - socialsharing_googleplus: 1.0.4
  - spreed: 5.0.2
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - firstrunwizard
  - group_everyone
  - nextcloud_announcements
  - support
  - unsplash
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.bliksoft.cz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "overwrite.cli.url": "https:\/\/cloud.bliksoft.cz",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using an external user-backend, if yes which one:**
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                        |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                          |
| homeFolderNamingRule          |                                                                                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                                                                                          |
| ldapAgentName                 | uid=nextcloud_vps,ou=consumers,dc=bliksoft,dc=cz                                                                                                                           |
| ldapAgentPassword             | ***                                                                                                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                                                                                                            |
| ldapAttributesForUserSearch   | mail;displayName;cn                                                                                                                                                        |
| ldapBackupHost                |                                                                                                                                                                            |
| ldapBackupPort                |                                                                                                                                                                            |
| ldapBase                      | dc=bliksoft,dc=cz                                                                                                                                                          |
| ldapBaseGroups                | ou=cloud,ou=groups,dc=bliksoft,dc=cz;ou=common,ou=groups,dc=bliksoft,dc=cz                                                                                                 |
| ldapBaseUsers                 | ou=users,dc=bliksoft,dc=cz                                                                                                                                                 |
| ldapCacheTTL                  | 600                                                                                                                                                                        |
| ldapConfigurationActive       | 1                                                                                                                                                                          |
| ldapDefaultPPolicyDN          |                                                                                                                                                                            |
| ldapDynamicGroupMemberURL     | member                                                                                                                                                                     |
| ldapEmailAttribute            | mail                                                                                                                                                                       |
| ldapExperiencedAdmin          | 0                                                                                                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                            |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                            |
| ldapExpertUsernameAttr        |                                                                                                                                                                            |
| ldapGidNumber                 | gidNumber                                                                                                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                                                                                         |
| ldapGroupFilter               | (&(|(objectclass=groupOfNames)))                                                                                                                                           |
| ldapGroupFilterGroups         |                                                                                                                                                                            |
| ldapGroupFilterMode           | 0                                                                                                                                                                          |
| ldapGroupFilterObjectclass    | groupOfNames                                                                                                                                                               |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                     |
| ldapHost                      | 127.0.0.1                                                                                                                                                                  |
| ldapIgnoreNamingRules         |                                                                                                                                                                            |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson)(memberof=cn=nextcloudaccount,ou=accounts,ou=groups,dc=bliksoft,dc=cz)))(|(mailPrimaryAddress=%uid)(mail=%uid)(cn=%uid)(entryUUID=%uid))) |
| ldapLoginFilterAttributes     | cn                                                                                                                                                                         |
| ldapLoginFilterEmail          | 1                                                                                                                                                                          |
| ldapLoginFilterMode           | 1                                                                                                                                                                          |
| ldapLoginFilterUsername       | 0                                                                                                                                                                          |
| ldapNestedGroups              | 1                                                                                                                                                                          |
| ldapOverrideMainServer        |                                                                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                                                                        |
| ldapPort                      | 389                                                                                                                                                                        |
| ldapQuotaAttribute            |                                                                                                                                                                            |
| ldapQuotaDefault              |                                                                                                                                                                            |
| ldapTLS                       | 0                                                                                                                                                                          |
| ldapUserAvatarRule            | default                                                                                                                                                                    |
| ldapUserDisplayName           | displayname                                                                                                                                                                |
| ldapUserDisplayName2          | cn                                                                                                                                                                         |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson)(memberof=cn=nextcloudaccount,ou=accounts,ou=groups,dc=bliksoft,dc=cz)))                                                                    |
| ldapUserFilterGroups          |                                                                                                                                                                            |
| ldapUserFilterMode            | 1                                                                                                                                                                          |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                                                                                                       |
| turnOffCertCheck              | 0                                                                                                                                                                          |
| turnOnPasswordChange          | 1                                                                                                                                                                          |
| useMemberOfToDetectMembership | 1                                                                                                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Chrome

**Operating system:**
Win 10

#### Browser log
<details>
<summary>Browser log</summary>

```
Navigated to https://cloud.bliksoft.cz/index.php/apps/files/
VM3549 core.js:7 JQMIGRATE: Migrate is installed, version 1.4.0
5[Violation] Forced reflow while executing JavaScript took <N>ms
(index):1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden">​…​</form>​
VM3557 search.js:67 New search handler registered
VM3549 core.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ VM3549 core.js:3
a.event.add @ VM3549 core.js:7
(anonymous) @ VM3549 core.js:3
each @ VM3549 core.js:2
each @ VM3549 core.js:2
on @ VM3549 core.js:3
initialize @ VM3583 merged-index.js:11361
initialize @ VM3583 merged-index.js:118
(anonymous) @ VM3583 merged-index.js:340
(anonymous) @ VM3549 core.js:18
VM3549 core.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ VM3549 core.js:3
a.event.add @ VM3549 core.js:7
(anonymous) @ VM3549 core.js:3
each @ VM3549 core.js:2
each @ VM3549 core.js:2
on @ VM3549 core.js:3
init @ VM3549 core.js:4983
(anonymous) @ VM3549 core.js:7566
each @ VM3549 core.js:2
each @ VM3549 core.js:2
$.fn.select2 @ VM3549 core.js:7553
render @ VM3634 merged.js:737
render @ VM3636 merged.js:608
setFileInfo @ VM3636 merged.js:577
(anonymous) @ VM3583 merged-index.js:10008
m.each.m.forEach @ VM3549 core.js:18
setFileInfo @ VM3583 merged-index.js:10007
_updateDetailsView @ VM3583 merged-index.js:5160
reload @ VM3583 merged-index.js:6458
changeDirectory @ VM3583 merged-index.js:6306
_onUrlChanged @ VM3583 merged-index.js:5272
dispatch @ VM3549 core.js:3
r.handle @ VM3549 core.js:3
trigger @ VM3549 core.js:3
a.event.trigger @ VM3549 core.js:7
(anonymous) @ VM3549 core.js:3
each @ VM3549 core.js:2
each @ VM3549 core.js:2
trigger @ VM3549 core.js:3
_onPopState @ VM3583 merged-index.js:299
initialize @ VM3583 merged-index.js:128
(anonymous) @ VM3583 merged-index.js:340
(anonymous) @ VM3549 core.js:18
VM3549 core.js:3 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
add @ VM3549 core.js:3
a.event.add @ VM3549 core.js:7
(anonymous) @ VM3549 core.js:3
each @ VM3549 core.js:2
each @ VM3549 core.js:2
on @ VM3549 core.js:3
init @ VM3549 core.js:4983
(anonymous) @ VM3549 core.js:7566
each @ VM3549 core.js:2
each @ VM3549 core.js:2
$.fn.select2 @ VM3549 core.js:7553
render @ VM3634 merged.js:737
render @ VM3636 merged.js:608
setFileInfo @ VM3636 merged.js:577
(anonymous) @ VM3583 merged-index.js:10008
m.each.m.forEach @ VM3549 core.js:18
setFileInfo @ VM3583 merged-index.js:10007
_updateDetailsView @ VM3583 merged-index.js:5160
reload @ VM3583 merged-index.js:6458
changeDirectory @ VM3583 merged-index.js:6306
_onUrlChanged @ VM3583 merged-index.js:5272
dispatch @ VM3549 core.js:3
r.handle @ VM3549 core.js:3
trigger @ VM3549 core.js:3
a.event.trigger @ VM3549 core.js:7
(anonymous) @ VM3549 core.js:3
each @ VM3549 core.js:2
each @ VM3549 core.js:2
trigger @ VM3549 core.js:3
_onPopState @ VM3583 merged-index.js:299
initialize @ VM3583 merged-index.js:128
(anonymous) @ VM3583 merged-index.js:340
(anonymous) @ VM3549 core.js:18
VM3549 core.js:18 [Violation] 'setTimeout' handler took 106ms
VM3549 core.js:18 [Violation] 'setTimeout' handler took 84ms
VM3556 merged-template-prepend.js:4613 querying Whats New data was successful: nocontent
VM3556 merged-template-prepend.js:4614 undefined
/index.php/apps/files/?dir=/&fileid=414:1 Clear-Site-Data header on 'https://cloud.bliksoft.cz/index.php/logout?requesttoken=2czfoD5MLfQB/E5z2pjz4Dl2T0UJ05%2BwcjTTYI4P22o%3D%3Av6/qwnIKXIVihiEf9a2AuG0XIRc7ma/eKwKpKLdkkRs%3D': Unrecognized type: "executionContexts".
/index.php/apps/files/?dir=/&fileid=414:1 Clear-Site-Data header on 'https://cloud.bliksoft.cz/index.php/logout?requesttoken=2czfoD5MLfQB/E5z2pjz4Dl2T0UJ05%2BwcjTTYI4P22o%3D%3Av6/qwnIKXIVihiEf9a2AuG0XIRc7ma/eKwKpKLdkkRs%3D': Cleared data types: "cache", "storage".
Navigated to https://cloud.bliksoft.cz/index.php/login
core.js?v=43d69335-6:7 JQMIGRATE: Migrate is installed, version 1.4.0
[Violation] Forced reflow while executing JavaScript took 53ms
core.js?v=43d69335-6:4 GET https://cloud.bliksoft.cz/index.php/apps/files_rightclick/ajax/applications 401 (Unauthorized)
send @ core.js?v=43d69335-6:4
ajax @ core.js?v=43d69335-6:4
n.(anonymous function) @ core.js?v=43d69335-6:4
(anonymous) @ script.js?v=43d69335-6:8
(anonymous) @ script.js?v=43d69335-6:447
```
</details>

**Comment by kesselb** [comment] 2019-02-25 18:20
Can you reproduce with a demo instance http://demo.nextcloud.com? For me the warning is gone after successful login.

**Comment by jelinj8** [comment] 2019-02-25 18:27
It seems to be working there. My instance is still doing it after 
update.
Thanks.

------ Původní zpráva ------
Od: "Daniel Kesselberg" <notifications@github.com>
Komu: "nextcloud/server" <server@noreply.github.com>
Kopie: "jelinj8" <jakub.jelinek@gmail.com>; "Author" 
<author@noreply.github.com>
Odesláno: 25.02.2019 19:20:57
Předmět: Re: [nextcloud/server] persistent failed login warning (#14158)

**Comment by skjnldsv** [comment] 2019-06-04 10:09
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed** 2019-06-04 10:09 UTC
Labels: 0. Needs triage, bug
