### ISSUE TITLE
disable allow_user_to_change_display_name, admin can't change name in user panel

### ISSUE THREAD

**Issue by focparty** [nextcloud/server#642] opened 2016-07-29 06:06 UTC
### Steps to reproduce
1. allow_user_to_change_display_name=false in config.php
2. user panel: changing name, doesnt save
### Expected behaviour

admin should be able to change user name
### Actual behaviour

see point 2. 
### Server configuration

**Operating system**: OVH shared hosting

**Web server:**  OVH shared hosting

**Database:** mysql

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:** new install

**Where did you install Nextcloud from:** nextcloud

**Comment by nickvergessen** [comment] 2016-08-03 17:31
Well that is the way the config is designed at the moment, however I can see cases where this would not be the intended behaviour.

**Comment by blizzz** [comment] 2016-12-07 09:58
> allow_user_to_change_display_name=false in config.php

> admin should be able to change user name

@focparty  Display Name and Username are two different things. Could you elaborate?

**Comment by GitHubUser4234** [comment] 2016-12-07 10:48
As #1302 has been closed as duplicate of this issue, I'd like to throw in my support for enabling email modification independently from `OC_User::canUserChangeDisplayName`. There are in fact use cases where changing the display name should be disabled while changing email should be enabled.

After some discussion with @blizzz , it might be necessary to consider that user_ldap overwrites the email value in `oc_preferences` in case emails are present in LDAP. So for example the user_ldap  backend could provide the email set-ability depending on whether an LDAP email attribute is set or not.

@MorrisJobke It would be great to know what you have in mind about how to implement this :)

**Comment by githubos1** [comment] 2017-05-17 16:04
I suggest:
'allow_user_to_change_display_name' => false,

should only prevent USERS from changing their DisplayName Settings and not automatically also their e-mail settings, so maybe an additional setting could be implemented like: 
'allow_user_to_change_email_address' => false,   ???

MUCH MORE IMPORTANT: this very important feature (when set to "false" should not impact ADMINS from changing or setting UserScreenName and UserEmail as well as it functions right now (I'm using 12.0.0. beta3 !!)

Regards,

Oliver

**Comment by OutbackMatt** [comment] 2017-05-22 04:33
11.0.3 seems to NOT be working from ./index.php/settings/users
I can't change any details on this screen...

**Comment by MorrisJobke** [comment] 2017-05-22 04:40
> ettings/users
> I can't change any details on this screen...

Have you set `allow_user_to_change_display_name` to `false`? If so: remove this line from the config and it should work again. That's currently a limitation we have.

**Comment by OutbackMatt** [comment] 2017-05-22 05:37
The config that is built automatically doesn't include that line at all.
Specifically when I add that line = true then there is no change.

I can't make changes to user full name or add an email address, all I can do is allocate the user to groups and set them as admin for those groups.

Ideally, I'd like a screen similar to my own ./index.php/settings/personal page that would all of these settings to be changed for each user by the server admin

**Comment by MorrisJobke** [comment] 2017-05-22 06:54
> I can't make changes to user full name or add an email address, all I can do is allocate the user to groups and set them as admin for those groups.

Yes. This is sadly how it is implemented currently. 🙈 Somebody™ needs to fix it, but as this is a rarely  used feature currently other issues are higher priotized. We are happy about contributions that fix this bug.

**Comment by dan-nkl** [comment] 2017-07-05 10:42
I really need this feature to control if the users can change the displayname or e-mail. And this independently.

In my usecase I need to disallow the displaynamechange for the users. The E-Mail should be still changeable.

At the moment I use a workaround that removes the form from the template. But this is only a visual removal!

**Comment by dan-nkl** [comment] 2017-08-04 12:16
This is not a Milestone anymore?

**Comment by sduensin** [comment] 2017-10-08 22:28
Still the behavior in 12.0.3.  :-(

**Comment by t0mcat1337** [comment] 2017-11-12 19:44
Any news about that? Me too stumbled accross this issue... took me hours to figure out, why I suddenly couldn't change / set users mail addresses in ADMIN backend (technically: the request http://<nextcloud.home>/index.php/settings/users/<username>/mailAddress always failed with a HTTP 403)
By chance I removed the previously added "allow_user_to_change_display_name=false" line from config and changing mail addresses in ADMIN works again as it should.
Can't really understand why setting "allow_user_to_change_display_name" to "false" has this impact... 
The variable name indicates USER preventing changing their DISPLAY_NAME, and NOT that also ADMINS may not change users MAIL ADDRESS ... IMHO this config var is wrong implemented or wrong named...

**Comment by KB7777** [comment] 2018-02-26 12:15
Hello.

I need this very badly to deploy my third NC instance for my company.  :(
Is there any news about it?

Regards.

**Comment by nickvergessen** [comment] 2018-05-08 14:38
I don't think so, because it's normally a one-time setting.

**Comment by revolter** [comment] 2018-05-08 14:40
Regardless, it should be in the UI.

In my case, I am an admin and I can access the Admin panel, but I don't have access to the Nextcloud server files on our server. So I could only go to http://our_ip:8080/nextcloud/index.php/settings/admin in the browser and change it there.

**Comment by dan-nkl** [comment] 2018-05-08 14:45
And I hope that the suggestions from @githubos1 has been seen..

'allow_user_to_change_email_address'
'allow_user_to_change_display_name'

really should be two separate settings..

**Closed** 2018-05-22 22:32 UTC
Labels: 3. to review, bug, feature: users and groups

**Comment by GoetheG** [comment] 2019-04-12 09:41
Hi there. @MorrisJobke: Please reopen this ticket.

@dan-nkl, @revolter: I totally agree with you. Same problem with me. I am using a Nextcloud hoster for my company and I dot not have access to the config file. In order to be able to block users from 1. changing their screen name and 2. changing their e-mail address I really need this function to be part of the user interface.

If the company behind Nextcloud really has the goal to be used by many people, then you need to add many more functions to the user interface. Just take a look at Rocket.Chat and the amount of settings it offers for administrators with no access to any config file.

**Comment by MorrisJobke** [comment] 2019-04-12 11:56
@GoetheG Please open a new issue for this. We then can evaluate again if this makes sense or not (also from a maintainability point of view)
