### ISSUE TITLE
password timeout for enable/disable apps too quick to enter password

### ISSUE THREAD

**Issue by Xaldimo** [nextcloud/server#11271] opened 2018-09-18 14:36 UTC
### Steps to reproduce
1. Create new VM and install NC 14.0.0
2. Proceed with installation through web-page
3. Login as Admin, and try to enable additional apps
4. Before I can enter password the pop-up disappears with a message “You did not enter the password in time”

### Expected behaviour
Password confirmation remains open until OK is clicked.

### Actual behaviour
After approx 6 seconds the pop-up disappears and shows “You did not enter the password in time”

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2.4.25

**Database:** Mysql

**PHP version:** 7.0

**Nextcloud version:** 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** ZIP from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - admin_notifications: 1.0.2
  - announcementcenter: 3.3.0
  - bookmarks: 0.13.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_automatedtagging: 1.4.0
  - files_downloadactivity: 1.3.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - polls: 0.8.3
  - provisioning_api: 1.4.0
  - ransomware_protection: 1.2.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - sharerenamer: 2.1.0
  - socialsharing_email: 1.0.4
  - socialsharing_facebook: 1.0.3
  - socialsharing_twitter: 1.0.3
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.7.215:8081"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "14.0.0.19",
        "overwrite.cli.url": "http:\/\/192.168.7.215:8081",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera 55.0.2994.37

**Operating system:** Debian 9

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No error logs available
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No log entries during the password pop-up
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No log entries during the password pop-up
</details>

**Comment by danielkesselberg** [comment] 2018-09-18 14:57
Thank you for reporting this issue :+1: I'm closing this issue because it looks like a duplicate of #11224. Let me know if i am wrong.

**Closed by danielkesselberg** 2018-09-18 14:58 UTC
Labels: bug

**Comment by Xaldimo** [comment] 2018-09-18 15:04
Sorry, I couldn't find the relevant issue. Guess used the wrong search terms. Thank you for pointing me to the correct issue.
