### ISSUE TITLE
After the update from NC 14.06 to 15.04 no emails will be sent via cron

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/server#14136] opened 2019-02-11 06:53 UTC
The dispatch by test mail in the basic settings works and the test mail arrives immediately. Only the cronjob will no longer send emails to all users who have activated their settings in such a way that changes should always be communicated via email. The cronjob is also displayed as successful in the basic settings. This is also done with the right user “crontab -u www-data -e”. A server restart has also brought no success.
If I share a share via email, the recipient will receive it immediately. Test mail in the basic settings works too. Only sending e-mails via cronjob does not work.

Settings are you using: “As soon as possible”
Every hour - same.

There are no hints in the log files. Loglevel 0 and 'mail_smtpdebug' => true,

Anyone else has an idea why could that be? I have just restored a backup with the version 15.02. I upgraded them from NC 14.06. Here was already the problem with the e-mails. So probably the email problem will be caused by the upgrade from 14 to 15. But what could it be?
Thank you.

**Comment by PpaiSanchez** [comment] 2019-02-13 08:00
Have any necessary tables been deleted after the upgrade? Which tables must exist in the database? I can only imagine that the tables are damaged or deleted.
Note: We only use LDAP users

**Comment by skjnldsv** [comment] 2020-08-20 13:51
Sorry, as I cannot reproduce the original issue anymore :shrug:, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-20 13:51 UTC
Labels: 0. Needs triage, bug
