### ISSUE TITLE
Theming cant be reset and Favicon not shown

### ISSUE THREAD

**Issue by FlorianTaut** [nextcloud/server#5033] opened 2017-05-22 12:30 UTC
### Steps to reproduce
1. Change Background Image and Favicon
2. Try to reset Background to default
3. See nothing has changed

### Expected behaviour
The standart-Background image should appear again

### Actual behaviour
No changes are done..

### Server configuration

**Operating system**: Debian 8.7.1

**Web server:** Apache 2.4.25

**Database:** MySQL 15.1

**PHP version:** 7.0.19

**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 12.0.0 from Beta-Channel
**Where did you install Nextcloud from:**
Updater

The logs dont show anything. Only tell me that i have no internet connection..

**Comment by FlorianTaut** [comment] 2017-05-22 12:32
Forgot to tell:

- Favicon not shown in navbar

- Favicon not shown on startpage

- Background image not shown

- Reset doenst work

Thats the short version

**Comment by juliushaertl** [comment] 2017-05-23 09:05
@FlorianTaut I guess you are talking about the theming app not using a custom theme righ? I cannot reproduce this. Can you check your browsers network log if the request sent when click on the reset button is ok? Are there any errors in the browser console?

**Comment by FlorianTaut** [comment] 2017-05-23 18:27
I will try this tomorrow. Yes im talking about the Theming app.

**Comment by FlorianTaut** [comment] 2017-05-24 07:49
@juliushaertl thats my debug.log of chrome. Not sure if it has anything todo with this Problem.
I tried it again today and it didnt work and nothin was added to the debug.log
`[0523/102732.396:ERROR:scoped_process_suspend.cc(30)] NtSuspendProcess: Es wurde versucht, auf einen Prozess zuzugreifen, der gerade beendet wurde.  (0xc000010a)
[0523/102732.440:ERROR:process_info.cc(116)] ReadProcessMemory bool __cdecl crashpad::`anonymous-namespace'::ReadStruct<struct crashpad::process_types::PEB<struct crashpad::process_types::internal::Traits64>>(void *,unsigned __int64,struct crashpad::process_types::PEB<struct crashpad::process_types::internal::Traits64> *): Nur ein Teil der ReadProcessMemory- oder WriteProcessMemory-Anforderung wurde abgeschlossen. (0x12B)
[0523/102732.440:ERROR:process_info.cc(559)] ReadProcessData failed
[0523/102732.440:ERROR:process_reader_win.cc(233)] ReadMemory at 0x7feed552968 of 12 bytes failed: Nur ein Teil der ReadProcessMemory- oder WriteProcessMemory-Anforderung wurde abgeschlossen. (0x12B)
[0523/102732.440:WARNING:process_snapshot_win.cc(68)] ReadMemory ExceptionInformation failed
[0523/102732.440:WARNING:crash_report_exception_handler.cc(60)] ProcessSnapshotWin::Initialize failed`

**Comment by juliushaertl** [comment] 2017-05-24 09:06
@FlorianTaut Can you check the network console as well? There should be a request to /apps/theming/ajax/updateLogo when you upload the logo.

![2017-05-24-110516_1917x664_scrot](https://cloud.githubusercontent.com/assets/3404133/26395641/fbe15312-4070-11e7-8f90-1e5821e9fb4f.png)

**Comment by FlorianTaut** [comment] 2017-05-24 09:18
@juliushaertl Checked that out, probably found the error:
Thats the log when uploading a new Logo
![unbenannt](https://cloud.githubusercontent.com/assets/18403881/26396105/7d1e3476-4072-11e7-96b0-5e5229ea38f3.PNG)

And that while resetting
![unbenan 1nt](https://cloud.githubusercontent.com/assets/18403881/26396168/b265d616-4072-11e7-8806-111bcec2ca98.PNG)

**Comment by juliushaertl** [comment] 2017-05-26 20:21
@FlorianTaut This might be a duplicate of #5085 Are you using multiple trusted domains in your config?

**Comment by FlorianTaut** [comment] 2017-05-28 11:40
Yes, 2 different internal IP's

**Comment by juliushaertl** [comment] 2017-05-28 11:41
OK, let's close in favour of #5085

**Comment by FlorianTaut** [comment] 2017-05-28 11:41
But i didn't change the IP-Adress of my Nextcloud host for this. I changed the ip to be able to upgrade to v12. And then tried to change the theme.

**Closed by juliushaertl** 2017-05-28 11:41 UTC
Labels: 0. Needs triage, bug, feature: theming
