### ISSUE TITLE
[Rich Workspaces] Content remains after browser back button

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#19028] opened 2020-01-20 21:21 UTC
### Steps to reproduce
1. Navigate into a folder with readme content at the top > content is shown
2. Hit browser's _back_ button

### Expected behaviour
Navigate to parent level, show that level's readme content (if set)

### Actual behaviour
Navigating to parent level, readme content from before remains visible until page refresh

**Comment by szaimen** [comment] 2021-06-07 18:07
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 18:07 UTC
Labels: 0. Needs triage, bug
