### ISSUE TITLE
Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/server#19097] opened 2020-01-23 13:11 UTC
After 18.0.0, my log is being flooded with  LDAP logs like these.

```
Info | user_ldap | Cannot determine UUID for cn=W,ou=Z,dc=Y,dc=X. Skipping. 
Error | user_ldap | Could not autodetect the UUID attribute
Info | no app in context | Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null
```
I had no errors like these on 17.0.2.

**Comment by landryb** [comment] 2020-01-24 14:15
also experiencing it on 18.0.0.10, and log is clean once i locally apply #19118.

**Comment by landryb** [comment] 2020-01-30 12:54
@rullzer should this issue (and #18331) be fixed now that #19118 has been merged ? locally deploying `stable18` branch doesnt display the msg in logs anymore. Or issues are closed only when a release is available from the stable branch..

**Comment by patrick1990** [comment] 2020-02-06 18:57
The error "[user_ldap] Error: Could not autodetect the UUID attribute" also floods my logs after upgrading from 17.0.2 to 17.0.3.

There is also a thread in the forum [here](https://help.nextcloud.com/t/nc-17-0-3-could-not-autodetect-the-uuid-attribute/70350)

**Comment by HigH-HawK** [comment] 2020-02-06 19:15
I agree with @patrick1990 - This issue appeared right after upgrading from 17.0.2 to 17.0.3 and is bombarding the log with these entries.

In the mentioned forum thread, a user found that using the old app user_ldap from 17.0.2 fixes the log flooding. I guess this could be used as a workaround but there should be a proper fix.

**Comment by corincorvus** [comment] 2020-03-11 09:52
Could not autodetect the UUID attribute flooding on 18.0.1 too.

**Comment by HigH-HawK** [comment] 2020-04-03 12:52
After upgrading to 18.0.3, it seems that the flooding has stopped.

A user on the forums mentioned, that the log entries keep appearing after upgrading, only for groups being added after the upgrade though.

**Comment by galichenkosemyon** [comment] 2020-04-15 04:42
Upgraded to 18.0.3 from 17.0.2 and still get messages `Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null`.

Nextcloud shows it as DEBUG messages and it can be hidden by setting `'loglevel' => 2` in `config.php`, but the root of the problem is still there, at least in my case.

**Comment by do-d1** [comment] 2020-04-16 11:03
fresh install 18.0.3
log is flooded with this message 
around 500Mb a day 

[https://youtu.be/m23u-16_bt0](https://youtu.be/m23u-16_bt0)

**Comment by mjunghanns** [comment] 2020-04-17 08:06
> 
> 
> After upgrading to 18.0.3, it seems that the flooding has stopped.
> 
> A user on the forums mentioned, that the log entries keep appearing after upgrading, only for groups being added after the upgrade though.

I cannot confirm this. We just performed the upgrade from 17.0.3 to 18.0.3 and are also seeing tons of `Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null.` messages.
We have sort of a mixed user account situation here. Individual user accounts are Active Directory based, thus we're using the LDAP connector. When it comes to "group" accounts (more than one person is using this account, normally with the Windows NextCloud Client) we do not hold these specific accounts in the Active Directory.

As the above mentioned errors are only showing up in conjunction with non-ldap/AD-, yet local nextcloud accounts, I figure, that whatever function is checking whatever (sorry, I haven't really taken a look into the sources yet) and thereby stumbling over the fact, that some accounts are no present in the LDAP-Backend, these messages are being generated.

I have the feeling that there might not be any other side-effects other than flooding and jamming the log file, but it's sure worth fixing :)

**Comment by do-d1** [comment] 2020-04-21 09:44
on my install i have:
1 local user (admin)
1 local group (admins)

**Comment by galichenkosemyon** [comment] 2020-05-04 01:57
Upgraded to 18.0.4. The logs are still there

**Comment by philfry** [comment] 2020-06-02 07:04
upgraded from 17.0.4 to 18.0.4 and (apart from other problems) the flooding began.

**Comment by till** [comment] 2020-06-11 13:57
Not sure who needs to read this, but... debugging becomes extremely hard with messages flooding the log.

Not sure if I am missing something important. Maybe they should be in `TRACE`?

**Comment by joergmschulz** [comment] 2020-06-18 20:35
same here for version 19

**Comment by danimo** [comment] 2020-06-21 22:01
Same here in 19.0. @blizzz: find me for a debugging session if you like.

**Comment by blizzz** [comment] 2020-06-22 21:56
> Same here in 19.0. @blizzz: find me for a debugging session if you like.

Merely a transition, but not sure I make it before vacation.

**Comment by craige1** [comment] 2020-06-24 07:11
Im also seeing a metric tonne of  Deprecated event type for OCA\User_LDAP\User\User::postLDAPBackendAdded: null

[nclog.txt](https://github.com/nextcloud/server/files/4823719/nclog.txt)

**Comment by blizzz** [comment] 2020-08-12 13:31
proposed fix in https://github.com/nextcloud/server/pull/22221

**Comment by kissgyorgy** [comment] 2020-08-13 16:46
Upgraded from 18.0.7 to 19.0.1 and I have this too.

**Closed** 2020-08-14 14:07 UTC
Labels: 2. developing, bug
