### ISSUE TITLE
Tasks integration not working correctly

### ISSUE THREAD

**Issue by drOnygames** [nextcloud/server#23231] opened 2020-10-06 14:03 UTC
Hi there, I did the update to Nextcloud 20.0, and well, tasks is not working correctly.
It runs on docker and I already deleted and reinstalled the task extension.
When i click on an entry on the calender, which is connected to tasks, I'm just getting an buggy site. (https://cloud.dr0ny.games/index.php/s/XnQsWZCdQS4BeMi)
And if I click on the extension (in the navbar) I get the following: https://cloud.dr0ny.games/index.php/s/TyceNAkq33fLHJd (link: https://cloud.dr0ny.games/apps/tasks/).

I hope you got all Information you need

Patrick

**Comment by LouisVallat** [comment] 2020-10-06 14:15
Me and other users just experienced it. I reported it on the tasks repository but after analysis, it seems that it is a server issue and not a tasks one.
cf. https://github.com/nextcloud/tasks/issues/1251
I had 502 too sometimes and after checking the logs when it did a 502 it appears that the server itself crashed.

**Comment by drOnygames** [comment] 2020-10-06 14:25
> Me and other users just experienced it. I reported it on the tasks repository but after analysis, it seems that it is a server issue and not a tasks one.
> cf. [nextcloud/tasks#1251](https://github.com/nextcloud/tasks/issues/1251)
> I had 502 too sometimes and after checking the logs when it did a 502 it appears that the server itself crashed.

What do you mean with 'crash', in my case everything is still working as it should, i can download, upload or view data in the same time in another tab

**Comment by LouisVallat** [comment] 2020-10-06 14:45
> What do you mean with 'crash', in my case everything is still working as it should, i can download, upload or view data in the same time in another tab

I can't reproduce it anymore so it may be an unrelated issue, but at least twice I had it give me a 502, and when I checked the logs, it said that the container crashed/had a segfault so docker-compose restarted the server immediately. I can't get it to crash that way again.

Again, I can't reproduce it so it may be a totally unrelated issue.

**Comment by drOnygames** [comment] 2020-10-06 15:01
Okay, thank you anyways, while going through the generated logs from the docker-compose, five lines caught my attention:
`mariadb             | 2020-10-06 14:58:37 119 [Warning] Aborted connection 119 to db: 'NextCloud' user: 'oc_Patrick Gorei' host: '172.18.0.12' (Got an error reading communication packets)
nginx-proxy         | nginx.1    | 2020/10/06 14:58:37 [error] 141#141: *225 upstream prematurely closed connection while reading response header from upstream, client: 141.101.97.104, server: cloud.dr0ny.games, request: "GET /index.php/apps/tasks/ HTTP/1.1", upstream: "http://172.18.0.12:80/index.php/apps/tasks/", host: "cloud.dr0ny.games"
nginx-proxy         | nginx.1    | cloud.dr0ny.games 141.101.97.104 - - [06/Oct/2020:14:58:37 +0000] "GET /index.php/apps/tasks/ HTTP/1.1" 502 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
nextcloud           | [Tue Oct 06 14:58:38.317228 2020] [core:notice] [pid 1] AH00052: child pid 61 exit signal Segmentation fault (11)`
To be honest, I have no clue what to do with it, but maybe it helps :D

**Comment by LouisVallat** [comment] 2020-10-06 15:03
Yeah that's what I got when my proxy gave me a 502, this is the segfault I was talking about.

**Comment by LouisVallat** [comment] 2020-10-06 15:21
Also @drOnygames I don't know if you did it on purpose, but the share links you provided in your original post are now leading to a bunch of 404.

**Comment by drOnygames** [comment] 2020-10-06 15:26
Yeah, idk why, but the index.php is back in there, I'm going to update the links

**Comment by LouisVallat** [comment] 2020-10-12 07:32
https://github.com/nextcloud/tasks/issues/1251

The origin of the issue has been found and an update is out on the app store, you should be able to upgrade your tasks app with the version 1.13.4 that fixes it. I think this issue can be closed.

**Comment by raimund-schluessler** [comment] 2020-10-12 07:33
Closing as it should be fixed now.

**Closed by raimund-schluessler** 2020-10-12 07:33 UTC
Labels: 0. Needs triage, 20-feedback

**Comment by sgofferj** [comment] 2020-10-14 07:32
Confirmed fixed in my installation.
