### ISSUE TITLE
Can´t open folder shared by link

### ISSUE THREAD

**Issue by controlcde** [nextcloud/server#15011] opened 2019-04-08 20:28 UTC
### Steps to reproduce
1. Create a public share without password but with expiration date and full rights.
2. Open the public share with no logged on user. Upload Files works, create folder works.
3. Try to enter a created folder: Failed. I can´t "click".

### Expected behaviour
I want to enter a folder in a public shared folder.

### Actual behaviour
It seams that the folder is not "clickable".

### Server configuration

**Operating system**: Docker nextcloud:latest
**Database:** mariadb 10.3
**Nextcloud version:** 15.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 15.0.0 to 15.0.6

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** different browser

**Operating system:** macOS, Windows10, mobile

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"0vE3VxmZ3zmOQwzbSwE2","level":3,"time":"2019-04-08T20:23:33+00:00","remoteAddr":"146.52.108.170","user":"--","app":"PHP","method":"POST","url":"\/index.php\/login?redirect_url=\/index.php\/settings\/integrity\/failed","message":"Undefined index: force_caps at \/var\/www\/html\/custom_apps\/user_external\/lib\/imap\/imap_rcube.php#945","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.86 Safari\/537.36","version":"15.0.6.1"}
```
</details>

**Comment by Nils160988** [comment] 2019-04-08 22:13
Duplicate of https://github.com/nextcloud/server/issues/14962, will be fixed in 15.0.7

**Closed** 2019-04-09 06:28 UTC
Labels: 0. Needs triage, bug
