### ISSUE TITLE
Multi-File upload does not work with Firefox for Android

### ISSUE THREAD

**Issue by vallant** [nextcloud/server#20669] opened 2020-04-26 13:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Log in into nextcloud with Firefox for Android
2. Click "+" in Files, click "Upload File"
3. Open System Files Dialog, select multple files
4. Confirm

### Expected behaviour
All selected files should be uploaded

### Actual behaviour
A single jpg file with filesize 0 bytes is uploaded.

### Server configuration

**Operating system:**
Raspbian Buster

**Web server:**
Apache 2.4.38

**Database:**
Mariadb 1:10.3.22-0

**PHP version:**
7.3.17-1

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Manual

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
- activity: 2.11.0
  - admin_audit: 1.8.0
  - audioplayer: 2.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.3
  - metadata: 0.11.1
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - printer: 0.0.2
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_email: 1.0.1
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "nextcloud.vallant.me"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/nextcloud.vallant.me",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "calendar"
        ],
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox for Android 68.7.0

Note that this does *NOT* occur with Chrome for Android, or Firefox for Android Beta 75.0.0!

**Operating system:**
Android 9

#### Web server error log
<details>
<summary>Web server error log</summary>
These are the relevant lines. The first two lines are from uploading two images using Chrome.
The last  line is generated when trying to upload the same two images using Firefox for Android

```
nextcloud.vallant.me:443 ***REMOVED SENSITIVE VALUE***" - - [26/Apr/2020:14:02:53 +0100] "PUT /remote.php/webdav/IMG_20200426_135226.jpg HTTP/2.0" 201 474 "-" "Mozilla/5.0 (Linux; Android 9; Pixel) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.117 Mobile Safari/537.36"
nextcloud.vallant.me:443 ***REMOVED SENSITIVE VALUE***" - - [26/Apr/2020:14:02:53 +0100] "PUT /remote.php/webdav/IMG_20200426_140318.jpg HTTP/2.0" 201 426 "-" "Mozilla/5.0 (Linux; Android 9; Pixel) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.117 Mobile Safari/537.36"
nextcloud.vallant.me:443 ***REMOVED SENSITIVE VALUE***" - - [26/Apr/2020:14:15:44 +0100] "PUT /remote.php/webdav/2020-04-26%2015.15.37.jpg HTTP/2.0" 201 473 "-" "Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No relevant logs are generated.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Unfortunately i wasn't able to capture the logs from Firefox for Android, since i cannot remote debug the Android Browser due to version incompatibilities between my desktop and Android.
```
</details>

**Comment by etieng** [comment] 2020-12-07 10:18
I'm facing this bug too.
Using an _upload only shared folder_, people can only upload a file at a time which prevent a lot of users to upload their batch of files this way...
In Firefox I can pick multiple files but only one will be uploaded. (Firefox 68.0 Android 10)
In Chrome I can only pick a file. (Chrome 85.0.4183.101 Android 10)

**Comment by szaimen** [comment] 2021-06-18 12:43
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-18 12:43 UTC
Labels: 0. Needs triage, bug
