### ISSUE TITLE
18.0.4 - Files in shared folders won't display in browser.

### ISSUE THREAD

**Issue by JoeatMJ** [nextcloud/server#20822] opened 2020-05-04 17:42 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

I had this issue when running 18.0.1 (#19878) and fixed it by going to 18.0.2. The issue wasn't there in 18.0.3. Now, the issue has come back with 18.0.4.

The issue is present in four other systems running 18.0.4.

### Steps to reproduce
1. Upload photo and/or video files to a folder.
2. Share folder.
3. Send link of shared folder to user.

### Expected behaviour
Users can open folder and view files in the browser window.

### Actual behaviour
Spinning icon and the file does not load or play in the browser.
Users have to download the files to view or play them.

### Server configuration

**Operating system:**
Ubuntu 18.04.4 LTS
**Web server:**
Apache/2.4.29 (Ubuntu)
**Database:**
MySQL 5.7.29
**PHP version:**
PHP 7.2.24-0ubuntu0.18.04.4 
**Nextcloud version:** (see Nextcloud admin page)
18.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 18.0.3
**Where did you install Nextcloud from:**
NC Updater app.
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - audioplayer: 2.10.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - files_external
  - recommendations
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>
#19878

**Comment by JoeatMJ** [comment] 2020-05-04 17:54
I spun up another instance of NC on the same basic platform. Here are what my tests have shown:

Sabre\DAV\Exception\NotAuthenticated: 

    /var/www/html/apps/dav/lib/Connector/Sabre/ServerFactory.php - line 148:

    {closure}("*** sensiti ... *")

    <<closure>>

    OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}("*** sensiti ... *")

    /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

    call_user_func_array(Closure {}, [ "*** sensi ... "])

    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:

    Sabre\Event\EventEmitter->emit("beforeMethod", [ "*** sensi ... "])

    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

    Sabre\DAV\Server->invokeMethod("*** sensiti ... *", "*** sensiti ... *")

    /var/www/html/apps/dav/appinfo/v1/publicwebdav.php - line 109:

    Sabre\DAV\Server->exec()

    /var/www/html/public.php - line 81:

    require_once("/var/www/ht ... p")

**Comment by Walterfilms** [comment] 2020-05-05 14:54
it's a known bug for nextcloud 18.0.4, that has been ennoying me as well...

see #20132 and https://github.com/nextcloud/files_videoplayer/pull/152#issuecomment-619622484

the only workaround right now is to do that :

as admin in "settings",

in "sharing" page and then "federated cloud sharing" section

if the option "Allow users on this server to send shares to other servers" is not checked...

than the video player doesn't work on public sharing...

hope that helps you.

**Comment by JoeatMJ** [comment] 2020-05-05 15:26
@Walterfilms , you are awesome! This fixed the issue for me.

I subscribed to those issues you posted to follow the progress.

**Comment by BayaroX** [comment] 2020-05-13 00:50
@Walterfilms - This workaround solved my "video playback problem" after upgrade to 18.0.4 too! Thanks a lot!

**Comment by citlee** [comment] 2020-05-13 20:54
> it's a known bug for nextcloud 18.0.4, that has been ennoying me as well...
> 
> see #20132 and [nextcloud/files_videoplayer#152 (comment)](https://github.com/nextcloud/files_videoplayer/pull/152#issuecomment-619622484)
> 
> the only workaround right now is to do that :
> as admin in "settings",
> in "sharing" page and then "federated cloud sharing" section
> check "Allow users on this server to send shares to other servers"
> hope that helps you.

Unfortunately this did not workaround the issue for me of being able to view images in a shared link visible in the browser - same 401 error as described in #20132 (Nextcloud 18.0.4), even after unsharing and resharing the directory after toggling the above settings.

**Comment by Wikinaut** [comment] 2020-05-18 21:45
When will this be fixed?

**Comment by MartB** [comment] 2020-06-02 11:48
Any status update on this, is this being triaged?

**Comment by skypal** [comment] 2020-06-16 08:13
I updated to 19.0.0, hoping this would fix the problem. It still exists although the workaround by @Walterfilms worked. (Thanks)

**Comment by Walterfilms** [comment] 2020-06-16 10:43
thanks for the report ;) 

i was hoping that it would be solved quickly too, but apparently it's only on the nextcloud 20 milestone :

#20132

I wonder if this issue should be pinned, maybe not the most important but very disturbing.

**Comment by violoncelloCH** [comment] 2020-07-22 14:48
closing as a duplicate of #20132

**Closed by violoncelloCH** 2020-07-22 14:48 UTC
Labels: 0. Needs triage, bug
