### ISSUE TITLE
`occ` command for refreshing Calendar subscriptions

### ISSUE THREAD

**Issue by akhil1508** [nextcloud/server#36849] opened 2023-02-24 10:35 UTC
- Currently calendar subscriptions are  refreshed with `QueuedJob`s from https://github.com/nextcloud/server/blob/master/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php
- Every new subscription has a new `QueuedJob` added to the `JobList`
- For some of the bigger subscriptions, this takes many many hours to run(longest was running for 8 hours :sob:  )
- Would be great to have an occ command to refresh the subscriptions so that we can optionally separate it from the NC cron
  - Something like [ExpireTrash background job](https://docs.nextcloud.com/server/24/admin_manual/configuration_files/trashbin_configuration.html#background-job)  and `occ trashbin:expire`

**Comment by akhil1508** [comment] 2023-02-24 10:48
I'd love to develop the changes for this if someone experienced with dav can tell me if it's feasible/doable. 
My idea is to:
- have a setting to switch it between cron and occ
- If this is set to "occ", just return in the background job class code and
  - Get the arguments from the bg job and execute similarly in a command one by one

**Comment by joshtrichards** [comment] 2024-11-20 20:23
Duplicate of #30294

**Closed** 2024-11-20 20:23 UTC
Labels: enhancement, 0. Needs triage, feature: occ, feature: caldav
