### ISSUE TITLE
deadlocks in oc_calendarchanges when importing events

### ISSUE THREAD

**Issue by flokli** [nextcloud/server#12947] opened 2018-12-09 22:55 UTC
### Steps to reproduce
1. Set up nextcloud, enable calendar app. I used MySQL as database, without memcache and without redis
2. From the calendar view, import some events from ics via Settings & Import -> Import calendar 

### Expected behaviour
Nextcloud should be able to import events

### Actual behaviour
A lot of events failed to import. Logs show some deadlocks occured. 

### Server configuration

**Operating system**: NixOS 18.09

**Web server:** nginx 1.14.1

**Database:** mariadb-10.2.17

**PHP version:** php 7.1.24

**Nextcloud version:** 14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 14.0.3

**Where did you install Nextcloud from:** https://github.com/NixOS/nixpkgs/blob/ee1613aea656119a872c3e75334e8469c27fff44/pkgs/servers/nextcloud/default.nix

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/private/Mail/Mailer.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/private/Mail/Mailer.php] => Array
                        (
                            [expected] => 14863a04a8a9c5ce1ba56a415609a6ef0ecae27810ce7fa1d654f211d7f6c3eb882a022e7053db91e5c2bce2c6de2d4a19289383f7aeacab7686b7af34b1de32
                            [current] => 7ccb23725eabf13e31efe8fc040e4bf49d47563519c8f1a22e9d7a12a8de1f721cce88e3e1eea20f72b74e8a910e80564007192860d41b6645a01222d846aaf6
                        )

                )

        )

)
```

This is expected, we apply https://github.com/nextcloud/server/pull/11404.patch to fix sendmail, which is not backported to 14, but will be shipped in nextcloud 15.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.8
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/store-apps",
                "url": "\/store-apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** yes/no no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

### Client configuration
**Browser:** Google Chrome 70

**Operating system:** NixOS 18.09

#### Web server error log
<details>
<summary>Web server error log</summary>

```
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```json
{
  "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
  "Message": "An exception occurred while executing 'INSERT INTO `oc_calendarchanges` (`uri`, `synctoken`, `calendarid`, `operation`) SELECT ?, `synctoken`, ?, ? FROM `oc_calendars` WHERE `id` = ?' with params [\"Nextcloud-C2FREY26K7OGRSMWFEJ52.ics\", \"3\", 1, \"3\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction",
  "Code": 0,
  "Trace": [
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php",
      "line": 128,
      "function": "convertException",
      "class": "Doctrine\\DBAL\\Driver\\AbstractMySQLDriver",
      "type": "->",
      "args": [
        "An exception occurred while executing 'INSERT INTO `oc_calendarchanges` (`uri`, `synctoken`, `calendarid`, `operation`) SELECT ?, `synctoken`, ?, ? FROM `oc_calendars` WHERE `id` = ?' with params [\"Nextcloud-C2FREY26K7OGRSMWFEJ52.ics\", \"3\", 1, \"3\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction",
        {
          "errorInfo": [
            "40001",
            1213,
            "Deadlock found when trying to get lock; try restarting transaction"
          ],
          "__class__": "Doctrine\\DBAL\\Driver\\PDOException"
        }
      ]
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php",
      "line": 177,
      "function": "driverExceptionDuringQuery",
      "class": "Doctrine\\DBAL\\DBALException",
      "type": "::",
      "args": [
        {
          "__class__": "Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"
        },
        {
          "errorInfo": [
            "40001",
            1213,
            "Deadlock found when trying to get lock; try restarting transaction"
          ],
          "__class__": "Doctrine\\DBAL\\Driver\\PDOException"
        },
        "INSERT INTO `oc_calendarchanges` (`uri`, `synctoken`, `calendarid`, `operation`) SELECT ?, `synctoken`, ?, ? FROM `oc_calendars` WHERE `id` = ?",
        {
          "1": "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          "2": "3",
          "3": 1,
          "4": "3"
        }
      ]
    },
    {
      "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/CalDAV/CalDavBackend.php",
      "line": 2013,
      "function": "execute",
      "class": "Doctrine\\DBAL\\Statement",
      "type": "->",
      "args": [
        [
          "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          "3",
          1,
          "3"
        ]
      ]
    },
    {
      "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/CalDAV/CalDavBackend.php",
      "line": 1020,
      "function": "addChange",
      "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
      "type": "->",
      "args": [
        "3",
        "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
        1
      ]
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/CalDAV/Calendar.php",
      "line": 201,
      "function": "createCalendarObject",
      "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
      "type": "->",
      "args": [
        "3",
        "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
        "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR"
      ]
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 1096,
      "function": "createFile",
      "class": "Sabre\\CalDAV\\Calendar",
      "type": "->",
      "args": [
        "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
        "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR"
      ]
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
      "line": 529,
      "function": "createFile",
      "class": "Sabre\\DAV\\Server",
      "type": "->",
      "args": [
        "calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
        "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR",
        null
      ]
    },
    {
      "function": "httpPut",
      "class": "Sabre\\DAV\\CorePlugin",
      "type": "->",
      "args": [
        {
          "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          "__class__": "Sabre\\HTTP\\Request"
        },
        {
          "__class__": "Sabre\\HTTP\\Response"
        }
      ]
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/event/lib/EventEmitterTrait.php",
      "line": 105,
      "function": "call_user_func_array",
      "args": [
        [
          {
            "__class__": "Sabre\\DAV\\CorePlugin"
          },
          "httpPut"
        ],
        [
          {
            "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      ]
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 479,
      "function": "emit",
      "class": "Sabre\\Event\\EventEmitter",
      "type": "->",
      "args": [
        "method:PUT",
        [
          {
            "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      ]
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
      "line": 254,
      "function": "invokeMethod",
      "class": "Sabre\\DAV\\Server",
      "type": "->",
      "args": [
        {
          "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          "__class__": "Sabre\\HTTP\\Request"
        },
        {
          "__class__": "Sabre\\HTTP\\Response"
        }
      ]
    },
    {
      "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/Server.php",
      "line": 293,
      "function": "exec",
      "class": "Sabre\\DAV\\Server",
      "type": "->",
      "args": []
    },
    {
      "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/appinfo/v2/remote.php",
      "line": 35,
      "function": "exec",
      "class": "OCA\\DAV\\Server",
      "type": "->",
      "args": []
    },
    {
      "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/remote.php",
      "line": 163,
      "args": [
        "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/appinfo/v2/remote.php"
      ],
      "function": "require_once"
    }
  ],
  "File": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php",
  "Line": 115,
  "Previous": {
    "Exception": "Doctrine\\DBAL\\Driver\\PDOException",
    "Message": "SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction",
    "Code": "40001",
    "Trace": [
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php",
        "line": 168,
        "function": "execute",
        "class": "Doctrine\\DBAL\\Driver\\PDOStatement",
        "type": "->",
        "args": [
          [
            "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "3",
            1,
            "3"
          ]
        ]
      },
      {
        "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/CalDAV/CalDavBackend.php",
        "line": 2013,
        "function": "execute",
        "class": "Doctrine\\DBAL\\Statement",
        "type": "->",
        "args": [
          [
            "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "3",
            1,
            "3"
          ]
        ]
      },
      {
        "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/CalDAV/CalDavBackend.php",
        "line": 1020,
        "function": "addChange",
        "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
        "type": "->",
        "args": [
          "3",
          "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          1
        ]
      },
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/CalDAV/Calendar.php",
        "line": 201,
        "function": "createCalendarObject",
        "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
        "type": "->",
        "args": [
          "3",
          "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR"
        ]
      },
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1096,
        "function": "createFile",
        "class": "Sabre\\CalDAV\\Calendar",
        "type": "->",
        "args": [
          "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR"
        ]
      },
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 529,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
          "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR",
          null
        ]
      },
      {
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/event/lib/EventEmitterTrait.php",
        "line": 105,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "Sabre\\DAV\\CorePlugin"
            },
            "httpPut"
          ],
          [
            {
              "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 479,
        "function": "emit",
        "class": "Sabre\\Event\\EventEmitter",
        "type": "->",
        "args": [
          "method:PUT",
          [
            {
              "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 254,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/Server.php",
        "line": 293,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/remote.php",
        "line": 163,
        "args": [
          "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php",
    "Line": 107,
    "Previous": {
      "Exception": "PDOException",
      "Message": "SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction",
      "Code": "40001",
      "Trace": [
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php",
          "line": 105,
          "function": "execute",
          "class": "PDOStatement",
          "type": "->",
          "args": [
            [
              "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
              "3",
              1,
              "3"
            ]
          ]
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php",
          "line": 168,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Driver\\PDOStatement",
          "type": "->",
          "args": [
            [
              "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
              "3",
              1,
              "3"
            ]
          ]
        },
        {
          "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/CalDAV/CalDavBackend.php",
          "line": 2013,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Statement",
          "type": "->",
          "args": [
            [
              "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
              "3",
              1,
              "3"
            ]
          ]
        },
        {
          "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/CalDAV/CalDavBackend.php",
          "line": 1020,
          "function": "addChange",
          "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
          "type": "->",
          "args": [
            "3",
            "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            1
          ]
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/CalDAV/Calendar.php",
          "line": 201,
          "function": "createCalendarObject",
          "class": "OCA\\DAV\\CalDAV\\CalDavBackend",
          "type": "->",
          "args": [
            "3",
            "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR"
          ]
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 1096,
          "function": "createFile",
          "class": "Sabre\\CalDAV\\Calendar",
          "type": "->",
          "args": [
            "Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR"
          ]
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
          "line": 529,
          "function": "createFile",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            "calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
            "BEGIN:VCALENDAR\r\n[...]\r\nEND:VCALENDAR",
            null
          ]
        },
        {
          "function": "httpPut",
          "class": "Sabre\\DAV\\CorePlugin",
          "type": "->",
          "args": [
            {
              "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/event/lib/EventEmitterTrait.php",
          "line": 105,
          "function": "call_user_func_array",
          "args": [
            [
              {
                "__class__": "Sabre\\DAV\\CorePlugin"
              },
              "httpPut"
            ],
            [
              {
                "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
                "__class__": "Sabre\\HTTP\\Request"
              },
              {
                "__class__": "Sabre\\HTTP\\Response"
              }
            ]
          ]
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 479,
          "function": "emit",
          "class": "Sabre\\Event\\EventEmitter",
          "type": "->",
          "args": [
            "method:PUT",
            [
              {
                "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
                "__class__": "Sabre\\HTTP\\Request"
              },
              {
                "__class__": "Sabre\\HTTP\\Response"
              }
            ]
          ]
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/sabre/dav/lib/DAV/Server.php",
          "line": 254,
          "function": "invokeMethod",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": [
            {
              "absoluteUrl": "https://nextcloud/remote.php/dav/calendars/testuser/personal/Nextcloud-C2FREY26K7OGRSMWFEJ52.ics",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        },
        {
          "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/lib/Server.php",
          "line": 293,
          "function": "exec",
          "class": "Sabre\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/appinfo/v2/remote.php",
          "line": 35,
          "function": "exec",
          "class": "OCA\\DAV\\Server",
          "type": "->",
          "args": []
        },
        {
          "file": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/remote.php",
          "line": 163,
          "args": [
            "/nix/store/x9i6jp7d0lmydnxhv3csbklrx93y3pci-nextcloud-14.0.3/apps/dav/appinfo/v2/remote.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/nix/store/h5csnfawxc73w0c0ls41fmj32cmjw2fi-nextcloud-14.0.4/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php",
      "Line": 105
    }
  },
  "CustomMessage": "--"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
I stripped the VCARD payload and json-formatted the log entry.
</details>

Might be related to https://github.com/nextcloud/server/pull/12413.

**Comment by flokli** [comment] 2018-12-15 13:37
cc @MorrisJobke

**Comment by MorrisJobke** [comment] 2019-01-04 22:55
cc @georgehrke @tcitworld for the calendar import

**Comment by georgehrke** [comment] 2019-01-04 23:18
There is this ticket in the calendar repo about limiting the number of import requests at a time: https://github.com/nextcloud/calendar/issues/445 (already fixed in alpha of 2.0)

@MorrisJobke It would probably still be nice to properly catch this in the server, right?

**Comment by MorrisJobke** [comment] 2019-01-05 08:47
How could we? Isn’t this due to a too big query from the calendar app?

**Comment by flokli** [comment] 2019-01-05 08:53
In my case, this was a slow database - moving it to a faster underlying storage did work around the problem, but I'd consider nextcloud just failing randomly with some deadlocks a bug, not the slow storage...

**Comment by georgehrke** [comment] 2019-01-05 12:16
> How could we? Isn’t this due to a too big query from the calendar app?

Ok, so let's close this as a duplicate of nextcloud/calendar#445

**Closed by georgehrke** 2019-01-05 12:16 UTC
Labels: 0. Needs triage, bug
