### ISSUE TITLE
Display more metadata for files in trash

### ISSUE THREAD

**Issue by despens** [nextcloud/server#22474] opened 2020-08-28 15:00 UTC
It is difficult to make sense of files in the trash can (Deleted Files) since the metadata sidebar cannot be brought up for them. In the default list view, even the size of the file is missing. All that can be seen is the file name, its original location, and when it was deleted. In many cases, that does not give enough context to make a decision if a file should be restored or permanently deleted.

The extra information that is currently available to trashcan files should be available _in addition_ to all the information that is usually displayed in the metadata sidebar in regular directories, not _instead_ :wink: 

If it is not possible to examine files in the trash by opening them, it should at least be possible to download them for local examination.

![image](https://user-images.githubusercontent.com/571494/91581813-3f2fb200-e94f-11ea-93b7-e2fdebf0deca.png)
_Which of these config files is the right one to restore and which should be deleted?_

**Comment by EngelPika32** [comment] 2021-04-27 11:34
> If it is not possible to examine files in the trash by opening them, it should at least be possible to download them for local examination.

I don't see any reason why opening (text) files from the trashbin shouldn't be available. 
IMHO, both should be available (opening & downloading).

**Comment by szaimen** [comment] 2021-07-02 15:43
> If it is not possible to examine files in the trash by opening them, it should at least be possible to download them for local examination.

cc @nextcloud/designers I think this makes sense. What is your opinion on that?

**Comment by jancborchardt** [comment] 2021-07-02 16:13
Yes, @tobiasKaminsky and I recently talked about showing entries in the "Shares" subcategories in the same way as in "All files". This is also true for the Deleted files.

**Comment by bes1002t** [comment] 2021-08-02 20:21
In my humble opinion this would make sense. We should use the same way as for not deleted files to show information. Introducing a new way how to show details could lead to confusion.

**Comment by juliushaertl** [comment] 2021-08-02 20:43
@jancborchardt Is there any reference to that or more details about what to show? I guess it should then be moved to "to develop"

**Comment by tobiasKaminsky** [comment] 2021-08-05 06:16
> showing entries in the "Shares" subcategories in the same way as in "All files". This is also true for the Deleted files.

So basically every view listing files/folders is the same. Shares/Deleted files then has one additional/specific button, e.g. "restore".

**Comment by being-peace** [comment] 2023-03-17 09:10
Duplicate of https://github.com/nextcloud/server/issues/24544. There it has been said that there was some developing activity. So I guess, this can be closed.

**Comment by szaimen** [comment] 2023-03-17 09:11
Thanks!

**Closed by szaimen** 2023-03-17 09:11 UTC
Labels: enhancement, 1. to develop, feature: trashbin
