### ISSUE TITLE
Apps of type authentication are loaded to late

### ISSUE THREAD

**Issue by sualko** [nextcloud/server#13868] opened 2019-01-28 15:10 UTC
I maintain two custom authentication backends (app types authentication) and discovered that, I think starting from NC 14, user sessions are killed after 5 minutes. After searching for hours, I saw that there is a check in`OC\User\Session\checkTokenCredentials()` if the password is still valid. After digging some more hours, it looks like the authentication apps are only loaded afterwards. See the log below were I threw an error in `OC\User\Manager\checkPassword()` if the password check fails. `OC_User::setupBackends()` triggers the password recheck in line 721 (`OC::init()`), but apps from type authentication are only loaded after OC is initialized in line 965 (`OC::handleRequest()`);

If I change my app to type session, everything works just fine. I'm still wondering why other authentication apps like LDAP or user_sql are not effected. Did I miss something?

### Steps to reproduce
1. Create an authentication backend (app of type authentication)
2. Login
3. Wait 5 minutes
4. Reload page

### Expected behaviour
Your session is still valid

### Actual behaviour
Your session is invalid

### Server configuration
**Nextcloud version:** 15

**Are you using an external user-backend, if yes which one:** custom

### Log
```
File: /var/www/nextcloud/lib/private/User/Manager.php
Line: 190

Trace
#0 /var/www/nextcloud/lib/private/User/Session.php(714): OC\User\Manager->checkPassword('LOGIN_NAME', 'MY_PASSWORD')
#1 /var/www/nextcloud/lib/private/User/Session.php(748): OC\User\Session->checkTokenCredentials(Object(OC\Authentication\Token\PublicKeyToken), 'to8qab3ukskgah9...')
#2 /var/www/nextcloud/lib/private/User/Session.php(260): OC\User\Session->validateToken('to8qab3ukskgah9...')
#3 /var/www/nextcloud/lib/private/User/Session.php(235): OC\User\Session->validateSession()
#4 /var/www/nextcloud/lib/private/legacy/app.php(351): OC\User\Session->getUser()
#5 /var/www/nextcloud/lib/private/legacy/app.php(116): OC_App::getEnabledApps()
#6 /var/www/nextcloud/lib/private/legacy/user.php(126): OC_App::loadApps(Array)
#7 /var/www/nextcloud/lib/base.php(721): OC_User::setupBackends()
#8 /var/www/nextcloud/lib/base.php(1068): OC::init()
#9 /var/www/nextcloud/index.php(40): require_once('/var/www/nextcl...')
#10 {main}
```

**Comment by skjnldsv** [comment] 2020-03-10 08:05
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-03-10 08:05 UTC
Labels: 0. Needs triage, bug
