### ISSUE TITLE
Rename folder does not work properly

### ISSUE THREAD

**Issue by Mululu** [nextcloud/server#16468] opened 2019-07-13 20:55 UTC
### Actual behaviour
if a folder is created with a name such as "Test 15.06.19" and you then rename it z.b.  without date then this will not be displayed.  Nextcloud thinks it is a file without a file type. Same in the web browser.

It's the same thing the other way round. Rename folder from "Test" to "Test 15.06.19". Then Nextcloud thinks that the 19 is the end of the file type. For a folder Nextcloud should not think that there are file types.

See Windows folder there is no problem to use points.

### Steps to reproduce
1. Create Folder with Name "Test 12.06.19"
2. Rename Folder into "Test"
3. Folder no longer appears as a folder

1. Create Folder with Name "Test"
2. Rename Folder into "Test 15.06.19"
3. Folder no longer appears as a folder

Nextcloud server version:
 
16.0.3 newest App Version 

#### Nextcloud log (data/nextcloud.log

...Nothing...

**Comment by juliushaertl** [comment] 2019-07-30 08:19
Duplicate of https://github.com/nextcloud/groupfolders/issues/518

**Closed** 2019-07-30 08:35 UTC
Labels: bug
