### ISSUE TITLE
Can't open pdf files which are older than the last update

### ISSUE THREAD

**Issue by pthoelken** [nextcloud/server#27699] opened 2021-06-28 11:29 UTC
After the last update I can't open up PDF files which are older than the last update. When I'm uploading a new pdf file (from now for example) all will be shown correctly. The problem occours only at older files. 

I can download the "broken" files as well and all looks fine in my local pdf reader. 

```
PDF.js v2.5.207 (build: 0974d6052)
Message: Missing PDF "https://cloud.foobar.com/remote.php/dav/files/user/Personal%2520Space/Documents/doc-19.pdf".
```
![image](https://user-images.githubusercontent.com/12643853/123629371-822f1000-d814-11eb-8884-5238a1e8c70e.png)

I'm using: 21.0.2
Latest nginx Version, CentOS 8

**Comment by szaimen** [comment] 2021-06-28 13:37
Duplicate of https://github.com/nextcloud/files_pdfviewer/issues/381#issue-892407690

**Closed by szaimen** 2021-06-28 13:37 UTC
Labels: 0. Needs triage, bug

**Comment by pthoelken** [comment] 2021-06-28 13:44
It's not a duplicate. The fix from you're reference didn't work!
