### ISSUE TITLE
Add database encryption for data at rest

### ISSUE THREAD

**Issue by 0x4E4448** [nextcloud/server#46057] opened 2024-06-23 20:38 UTC
**Is your feature request related to a problem? Please describe.**
Data stored in the database is generally stored in plaintext. This is not a big issues for AIO or installs on the same server, but for installs using separate servers for NC and the database, particularly where the database server is not controlled by the NC operator, data can be easily viewed and compromised. In addition to NC server data, calendars, contacts, notes, etc could all be of concern.

**Describe the solution you'd like**
There should be an ability to encrypt data before or as it is written to the database. The key would likely be set in the NC config, but would help limit the exposure of data outside of the NC server itself. 

**Describe alternatives you've considered**
Database-side encryption is a potential solution but would likely require different implementations for different servers. Implementing the encryption in NC itself would be database independent.

**Additional context**
My use case is having primary storage in object storage with server side encryption and a database I host, but a NC front-end my client hosts. I want to minimize the amount of data I control that can be read by myself or an attacker.

---

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joshtrichards** [comment] 2024-06-25 20:26
Duplicate of #13103

**Closed by joshtrichards** 2024-06-25 20:26 UTC
Labels: enhancement, 0. Needs triage
