### ISSUE TITLE
Video keeps playing in background

### ISSUE THREAD

**Issue by fqdb** [nextcloud/server#28195] opened 2021-07-27 13:32 UTC
### Steps to reproduce
1. Open a folder containing images and a video file (with large images and video files it appears easier to replicate)
2. Open the preview view of an image or video
3. Quickly scroll through the previews e.g. by tapping the arrow keys
4. Occasionally the video audio will keep playing in the background
5. Scrolling through the previews again may play a additional instances of the same video in the background
6. The video will only stop playing when reloading the browser tab or by leaving the files app.

### Expected behaviour
Videos cannot  keep playing in the background when switching to another preview

### Actual behaviour
Videos keeps playing in background with no way to stop it other than leaving the files app

Screen recording: https://nextcloud.fqdb.nl/index.php/s/x9qyk96bE2HCSKa

### Server configuration

**Operating system:**
Ubuntu 20.04.2 LTS
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
PHP 7.4.21
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 21.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 20
**Where did you install Nextcloud from:**
Zip install
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - audioplayer: 3.1.0
  - bookmarks: 4.3.0
  - calendar: 2.3.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.9
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - ocdownloader: 1.7.11
  - password_policy: 1.11.0
  - passwords: 2021.7.23
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - support: 1.4.0
  - suspicious_login: 4.0.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - bruteforcesettings
  - dashboard
  - encryption
  - federation
  - files_external_gdrive
  - ransomware_detection
  - sharebymail
  - survey_client
  - systemtags
  - user_ldap
  - user_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.fqdb.nl",
            "nextcloud.fqdb.nl",
            "192.168.0.103",
            "80.112.147.137"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.3.1",
        "overwrite.cli.url": "http:\/\/www.fqdb.nl\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "app_install_overwrite": [
            "files_external_onedrive",
            "ocdownloader"
        ],
        "data-fingerprint": "5b32278d376ad0abaeb201fcfec20bbc",
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 30"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

</details>

### Client configuration
**Browser:**
Microsoft Edge Version 92.0.902.55
**Operating system:**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎17-‎Mar-‎21
OS build	19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

#### Web server error log
<details>
<summary>Web server error log</summary>
no recent log entries
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

no log entries since over a week before I even uploaded these files
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
nextcloud.fqdb.nl/:1 Refused to execute script from 'https://nextcloud.fqdb.nl/index.php/apps/files/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
Viewer.vue:260 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:260
pn.run @ vue.runtime.esm.js:4568
cn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Kt @ vue.runtime.esm.js:1906
Promise.then (async)
Yt @ vue.runtime.esm.js:1933
ee @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
pn.update @ vue.runtime.esm.js:4544
ct.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:81
(anonymous) @ main.js:26
xhr.js:177 GET https://nextcloud.fqdb.nl/ocs/v2.php/apps/text/workspace?path=%2F20202021%2FAP3001+Mathematical+Methods+for+Applied+Physics%2FPartial+Differential+Equations%2FLecture+recordings%2FLecture+1 404 (Not Found)
```
</details>

**Comment by szaimen** [comment] 2021-08-08 16:21
Duplicate of https://github.com/nextcloud/viewer/issues/894

**Closed by szaimen** 2021-08-08 16:21 UTC
Labels: bug, 0. Needs triage
