### ISSUE TITLE
Error thrown after installation

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2218] opened 2016-11-21 17:50 UTC
```
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Icon.getFavicon" as such route does not exist.
/media/psf/nextcloud/lib/private/Route/Router.php - line 339: Symfony\Component\Routing\Generator\UrlGenerator->generate('theming.Icon.ge...', Array, 1)
/media/psf/nextcloud/lib/private/URLGenerator.php - line 70: OC\Route\Router->generate('theming.Icon.ge...', Array)
/media/psf/nextcloud/lib/private/URLGenerator.php - line 165: OC\URLGenerator->linkToRoute('theming.Icon.ge...', Array)
/media/psf/nextcloud/lib/private/legacy/template/functions.php - line 170: OC\URLGenerator->imagePath('core', 'favicon.ico')
/media/psf/nextcloud/core/templates/layout.guest.php - line 13: image_path('', 'favicon.ico')
/media/psf/nextcloud/lib/private/Template/Base.php - line 174: include('/media/psf/next...')
/media/psf/nextcloud/lib/private/Template/Base.php - line 149: OC\Template\Base->load('/media/psf/next...', NULL)
/media/psf/nextcloud/lib/private/legacy/template.php - line 228: OC\Template\Base->fetchPage(NULL)
/media/psf/nextcloud/lib/private/legacy/template.php - line 250: OC_Template->fetchPage()
/media/psf/nextcloud/lib/private/Template/Base.php - line 130: OC_Template->fetchPage()
/media/psf/nextcloud/core/templates/403.php - line 7: OC\Template\Base->printPage()
{main}
```
cc @juliushaertl

**Comment by LukasReschke** [comment] 2016-11-21 17:55
Yeah as well as a big load of other error messages 🙈

**Comment by MorrisJobke** [comment] 2016-11-22 09:30
cc @rullzer

**Comment by juliushaertl** [comment] 2016-11-22 09:39
@LukasReschke I can't reproduce this. Is this occuring on the login page after an installation?

**Comment by rullzer** [comment] 2016-11-22 12:01
Could be this is fixed by https://github.com/nextcloud/server/pull/2212

**Comment by MorrisJobke** [comment] 2016-11-23 17:29
@LukasReschke Please reopen if this still happens

**Closed by MorrisJobke** 2016-11-23 17:29 UTC
Labels: bug
