### ISSUE TITLE
Occ Upgrade forces to run once a day

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/server#10918] opened 2018-08-29 08:50 UTC
### Steps to reproduce
1. Install latest stable version of Nextcloud
2. Visit once a day your nextcloud
3. You need to run an occ upgrade to get back to nextcloud

### Expected behaviour
I should be able to visit my nextcloud without doing an occ upgrade once a day. I don´t know how I can debug it further, since there no unusual logs written etc. At my nextcloud 14 beta it doesn´t happen, but at all 13.0.5 clouds.

### Server configuration

**Operating system**: Debian 9.5

**Web server:** nginx 15.2

**Database:** MariaDB 10.2

**PHP version:** php7.1

**Nextcloud version:** 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** 13.0.4

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - audioplayer: 2.3.2
  - bookmarks: 0.12.1
  - bookmarks_fulltextsearch: 0.99.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - caniupdate: 0.1.3
  - checksum: 0.4.0
  - circles: 0.14.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dashboard: 5.0.1
  - data_request: 1.0.1
  - dav: 1.4.7
  - deck: 0.4.1
  - drop_account: 0.0.11
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_antivirus: 1.3.1
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_fulltextsearch: 0.99.1
  - files_fulltextsearch_tesseract: 0.2.0
  - files_markdown: 2.0.4
  - files_opds: 0.8.8
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_retention: 1.2.0
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - fulltextsearch: 0.99.1
  - fulltextsearch_elasticsearch: 0.99.1
  - gallery: 18.0.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.3
  - metadata: 0.7.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.4.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - ocsms: 1.13.1
  - onlyoffice: 2.0.2
  - ownpad: 0.6.8
  - passman: 2.1.4
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - rainloop: 5.1.0
  - ransomware_protection: 1.1.1
  - richdocuments: 2.0.11
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - sharerenamer: 1.4.1
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - drawio
  - encryption
  - impersonate
  - news
  - sensorlogger
  - spreedme
  - user_external
  - user_ldap
  - workin2gether
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.speibox.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.speibox.de",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "auth.bruteforce.protection.enabled": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "trashbin_retention_obligation": "auto",
        "theme": "",
        "loglevel": 2,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "comments.managerFactory": "\\OC\\Comments\\ManagerFactory",
        "systemtags.managerFactory": "\\OC\\SystemTag\\ManagerFactory",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "cache_path": "",
        "cache_chunk_gc_ttl": 86400,
        "sharing.managerFactory": "\\OC\\Share20\\ProviderFactory",
        "tempdirectory": "\/var\/kunden\/cloud\/tmp",
        "hashingCost": 10,
        "blacklisted_files": [
            ".htaccess"
        ],
        "share_folder": "\/",
        "filesystem_check_changes": 0,
        "part_file_in_storage": true,
        "mount_file": "\/var\/kunden\/cloud\/httpdocs\/nextcloud\/data\/mount.json",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "max_filesize_animated_gifs_public_sharing": 10,
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "cipher": "AES-256-CFB",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "debug": false,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** chrome

**Operating system:**
windows 10
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Cannot modify header information - headers already sent by (output started at /var/kunden/cloud/httpdocs/nextcloud/apps/passman/personal.php:1) at /var/kunden/cloud/httpdocs/nextcloud/lib/private/AppFramework/Http/Output.php#69
```
</details>

**Comment by MorrisJobke** [comment] 2018-10-01 18:40
> I should be able to visit my nextcloud without doing an occ upgrade once a day. I don´t know how I can debug it further, since there no unusual logs written etc. At my nextcloud 14 beta it doesn´t happen, but at all 13.0.5 clouds.

That is super weird. Do you by any chance reset the content of the config.php on a daily basis because this would explain this behavior as we store the currently installed version in there.

**Comment by MorrisJobke** [comment] 2018-11-29 23:00
As there is no feedback since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2018-11-29 23:00 UTC
Labels: feature: install and update, needs info
