### ISSUE TITLE
Generate random password for file sharing

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#3303] opened 2017-01-28 09:17 UTC
Hi
it would be great if there would be a feature to generate a random password for the file sharing link.
Do you already thought about something like that?

**Comment by szaimen** [comment] 2019-05-31 00:49
Any update on this?

**Comment by wiswedel** [comment] 2019-05-31 13:04
@MorrisJobke What do you think?

**Comment by MorrisJobke** [comment] 2019-05-31 15:30
> @MorrisJobke What do you think?

Sounds good 👍

**Comment by wiswedel** [comment] 2019-06-19 09:43
duplicate of https://github.com/nextcloud/server/issues/12171

**Closed by wiswedel** 2019-06-19 09:43 UTC
Labels: 1. to develop, enhancement, feature: sharing
