### ISSUE TITLE
Resharing is not allowed

### ISSUE THREAD

**Issue by Hajo1961** [nextcloud/server#4578] opened 2017-04-28 09:49 UTC
After migration to Nextcloud 11.0.3 folders, that where shared to some users can't continue share with more users. But that effect only some but not all folder that shared before. Other folder can continue share to other users. The affected folder show no input box but the warning "Resharing is not allowed"

I found this generated message in ../core/js/sharedialoglinkshareview.js -  render: function()

What I do not understand is that some already shared folders can be share again and other already shared folders do not. I had a look to tables like oc_share, ect. in the nextcloud database, but I don't find any flag for the concerned folder that generate this warning.

Any idea what the problem is?

**Operating system**: Debian Jessie

**Web server**: Apache

**Database**: Mysql

**PHP version**: PHP 5.6.30

**Nextcloud version**:  11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install**: Update from Owncloud 8.2

**Where did you install Nextcloud from**: Nextcloud.com

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - admin_notifications: 1.0.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_downloadactivity: 1.0.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_antivirus
  - files_automatedtagging
  - firstrunwizard
  - templateeditor
  - theming
  - user_external
  - user_saml
</details>

**Comment by Hajo1961** [comment] 2017-04-28 10:08
![nc01](https://cloud.githubusercontent.com/assets/6784130/25524553/5201607c-2c0b-11e7-894d-e042ba93c83b.JPG)

![nc02](https://cloud.githubusercontent.com/assets/6784130/25524558/5a6bb87a-2c0b-11e7-9f69-104816d854cb.JPG)

![nc03](https://cloud.githubusercontent.com/assets/6784130/25524563/5e8cf16c-2c0b-11e7-858e-6e1db796c03e.JPG)

**Comment by Hajo1961** [comment] 2017-04-28 10:11
![nc01](https://cloud.githubusercontent.com/assets/6784130/25524650/d234a54c-2c0b-11e7-90f0-bb3f21bfc039.JPG)


![nc02](https://cloud.githubusercontent.com/assets/6784130/25524667/d7835020-2c0b-11e7-84d8-5a62b141cd12.JPG)
![nc03](https://cloud.githubusercontent.com/assets/6784130/25524681/db67e9b2-2c0b-11e7-9bc4-3404d3383b02.JPG)

**Comment by MorrisJobke** [comment] 2017-04-29 04:09
cc @schiessle @rullzer

**Comment by Hajo1961** [comment] 2017-05-01 12:13
Any idea :-)

**Comment by MorrisJobke** [comment] 2017-05-01 15:54
> Any idea :-)

Keep calm - it's public holiday in the countries those two are living in ;)

**Comment by rullzer** [comment] 2017-05-03 14:36
Could post the content of your oc_share table?

**Comment by Hajo1961** [comment] 2017-05-04 09:08
Hi Rullzer,

do you need the whole table? The table has more then 1500 records :-) Or do you need only the records of the user and the folder which has the problem with reshare?

Best regards

Hajo

**Comment by rullzer** [comment] 2017-05-04 11:36
@Hajo1961 aaah yes please only the relevant rows :smile:

**Comment by Hajo1961** [comment] 2017-05-04 12:43
@rullzer see the attached file!

I have another shared which I can't reshare. I make a clone of my nextcloud and delete all users for the related share and the input box is active. So I add the users again und the input box will stay active so that I can add more users. But in my production nextcloud I can't remove the users and add them again, because these users have some shares with other users and when I delte these users there shares will move away :-(

So there must a way to repair this issue without delete these users and add them again :-)


[share.zip](https://github.com/nextcloud/server/files/976122/share.zip)

**Comment by Hajo1961** [comment] 2017-05-11 14:06
@rullzer Any idea?

**Comment by Hajo1961** [comment] 2017-05-15 13:23
I found the mistake! It was a share with a deleted AD user. When this user was deleted from the share list, it was possible to share to other user. I think it is a bug!

**Comment by MorrisJobke** [comment] 2017-05-15 14:46
> I found the mistake! It was a share with a deleted AD user. When this user was deleted from the share list, it was possible to share to other user. I think it is a bug!

cc @blizzz Didn't we had this recently?

**Comment by blizzz** [comment] 2017-05-15 22:27
@MorrisJobke mh, maybe, maybe in a different flavour. Sharing should not panic when  a user not available anymore, though.

**Comment by skjnldsv** [comment] 2019-06-06 16:34
Could we have a dive here and wee if we can reproduce?

**Comment by skjnldsv** [comment] 2019-08-07 16:20
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-08-07 16:20 UTC
Labels: 0. Needs triage, bug, feature: ldap, feature: sharing
