### ISSUE TITLE
Server locked 423 error

### ISSUE THREAD

**Issue by utcutr** [nextcloud/server#30651] opened 2022-01-13 16:29 UTC
Server locked 423 error. Not one person has any idea what this is and not one person in the nextcloud community cares enough to fix this issue

**Comment by mohe2015** [comment] 2022-01-13 16:40
Just from reading https://datatracker.ietf.org/doc/html/rfc4918#section-11.3 I think it may be that two clients are accessing the same file concurrently.

**Comment by mohe2015** [comment] 2022-01-13 16:42
Other than that everything here is missing and this issue is extremely unconstructive. At least *try* to add some steps to reproduce / more details about your environment.

**Comment by mohe2015** [comment] 2022-01-13 16:46
Maybe duplicate of https://github.com/nextcloud/server/issues/9001

**Comment by acsfer** [comment] 2022-01-13 17:39
> not one person in the nextcloud community cares enough to fix this issue
Maybe you care? Here: https://github.com/nextcloud/server/pulls

Otherwise, if you don't even take the time to fill out a template issue, or at least detail you environment, don't expect anyone will take the time to debug it...

**Comment by szaimen** [comment] 2022-01-13 17:49
I guess its also a duplicate of https://help.nextcloud.com/t/no-idea-what-to-do/131025/19

**Closed by szaimen** 2022-01-13 17:49 UTC
Labels: needs info
