### ISSUE TITLE
Wrong week start day in personal settings

### ISSUE THREAD

**Issue by thomas-mc-work** [nextcloud/server#22555] opened 2020-09-03 09:04 UTC
### Steps to reproduce
1. Open Settings -> Personal info on Nextcloud 20 beta 2
2. Change language to English (US) and Locale to German (Germany) (or simply to German)

### Expected behaviour

Have `Week starts on Monday` which is the default in Germany (or even continental Europe?)

### Actual behaviour

`Week starts on Sunday`

### Server configuration

    podman run --rm -p 8000:80 nextcloud:20.0.0beta2-apache

**Comment by nickvergessen** [comment] 2020-09-03 11:52
I think this boils down to https://github.com/nextcloud/server/pull/14784

**Comment by Pazu** [comment] 2021-01-07 09:37
I suggest this is a duplicate of the older #21614.

**Closed** 2021-01-07 12:12 UTC
Labels: 0. Needs triage, bug
