### ISSUE TITLE
Appstore: allow search across all categories

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#9898] opened 2018-06-18 11:49 UTC
E.g. I wanted to install "dashboard", but searching (ctrl+f) on "apps" as admin, did not worked.
So I had to go through all categories until I found the desired app.
(especially harder because no category is listed in appstore webpage (https://github.com/nextcloud/appstore/issues/528)

**Comment by MorrisJobke** [comment] 2018-06-18 12:04
Duplicate of #6868
Fixed by #9565

**Closed by MorrisJobke** 2018-06-18 12:04 UTC
