### ISSUE TITLE
WebDAV only: Write-protection message when open Microsoft Word/Excel file that already open

### ISSUE THREAD

**Issue by nobe80** [nextcloud/server#25205] opened 2021-01-19 12:49 UTC
By open a Microsoft Word or Excel file in Windows 10 via WebDAV network drive we need a message if that file is already open by another user. To login into the Nextcloud webinterface, locks every file at any time by hand and unlock it again is absolutley not practicable. We need here the same behavior like by SMB shares: You get a message that the file will open in readonly modus when it is already open. 

Would be great if we can have this, especially for business users.

Thanks & regards

**Comment by szaimen** [comment] 2021-06-22 12:03
duplicate of https://github.com/nextcloud/files_lock/issues/27

**Closed by szaimen** 2021-06-22 12:03 UTC
Labels: 0. Needs triage, enhancement
