### ISSUE TITLE
Upgrade to 14.0.11 fails with getdatetime error

### ISSUE THREAD

**Issue by ChristophGoth** [nextcloud/server#15563] opened 2019-05-16 11:39 UTC
Trying to Upgrade to newest version, coming from 13.2.1 to 14.0.11 in first step.

2019-05-16T11:36:42+00:00 Remove potentially over exposing share links
2019-05-16T11:36:42+00:00 
                                                    2019-05-16T11:36:42+00:00  Done
    0/0 [>-]   0%2019-05-16T11:36:42+00:00 42+00:00 
2019-05-16T11:36:42+00:00 Repair info: Sending notifications to admins and affected users
An unhandled exception has been thrown:
Error: Call to undefined method OC\AppFramework\Utility\TimeFactory::getDateTime() in /srv/www/htdocs/cloud/lib/private/Repair/RemoveLinkShares.php:189
Stack trace:
#0 /srv/www/htdocs/cloud/lib/private/Repair/RemoveLinkShares.php(224): OC\Repair\RemoveLinkShares->sendNotification()
#1 /srv/www/htdocs/cloud/lib/private/Repair/RemoveLinkShares.php(230): OC\Repair\RemoveLinkShares->repair(Object(OC\Repair))
#2 /srv/www/htdocs/cloud/lib/private/Repair.php(91): OC\Repair\RemoveLinkShares->run(Object(OC\Repair))
#3 /srv/www/htdocs/cloud/lib/private/Updater.php(265): OC\Repair->run()
#4 /srv/www/htdocs/cloud/lib/private/Updater.php(121): OC\Updater->doUpgrade('14.0.11.1', '13.0.2.1')
#5 /srv/www/htdocs/cloud/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#6 /srv/www/htdocs/cloud/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /srv/www/htdocs/cloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /srv/www/htdocs/cloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /srv/www/htdocs/cloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /srv/www/htdocs/cloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /srv/www/htdocs/cloud/console.php(96): OC\Console\Application->run()
#12 /srv/www/htdocs/cloud/occ(11): require_once('/srv/www/htdocs...')

Cant Figure out where the problem is.

apollo:/srv/www/htdocs/cloud # php -v
PHP 7.0.7 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by kesselb** [comment] 2019-05-16 12:24
Make sense ;) Regression from https://github.com/nextcloud/server/pull/15140 because `getDateTime`  is Nextcloud 15+https://github.com/nextcloud/server/blob/856a33ec47e169bcfb57eb7abad51e567f8da203/lib/private/AppFramework/Utility/TimeFactory.php#L44-L52

cc @rullzer @nickvergessen

**Comment by nickvergessen** [comment] 2019-05-16 12:27
Yeah, just replace it with `new \DateTime()` in stable14 @kesselb

**Comment by ChristophGoth** [comment] 2019-05-16 12:59
Used 14.0.8 now to Update, worked too.

**Comment by dt64** [comment] 2019-05-16 14:08
same issue while upgrading from 14.0.9 to 14.0.11

**Comment by MorrisJobke** [comment] 2019-05-16 14:20
Let's stop the update for 14.0.11 for now: https://github.com/nextcloud/updater_server/pull/222

**Comment by kyrofa** [comment] 2019-05-17 06:39
This is probably obvious, but I want to mention it because of the title: the upgrade fails from 14.0.10 as well.

**Comment by mnheia** [comment] 2019-05-17 07:57
Same issue appears when updating from 14.0.3 to 14.0.11. Upgrade to a version prior to implementation of "RemoveLinkShares.php" works as expected. 

Update from 14.0.3 to 14.0.10 and then to 15.0.0 works and so on works.

**Comment by MorrisJobke** [comment] 2019-05-17 10:09
Fixed in 14.0.12. We try to release this as soon as possible. #15594

**Closed by MorrisJobke** 2019-05-17 10:09 UTC
Labels: 1. to develop, bug, regression
