### ISSUE TITLE
Blurry Actions Font

### ISSUE THREAD

**Issue by ealmonte32** [nextcloud/server#24918] opened 2020-12-30 19:21 UTC
### Steps to reproduce
1. Log in to account
2. Click on Files tab/app
3. Click on checkbox next to a file
4. Click on the three dots / Actions button

### Expected behaviour
Actions font/text should not be blurry

### Actual behaviour
Actions font/text is blurry compared to other text everywhere else on dashboard/interface

![Screen Shot 2020-12-30 at 2 06 11 PM](https://user-images.githubusercontent.com/24350198/103376120-c3cf4000-4aa9-11eb-855c-aba45c5e06f6.png)

### Server configuration

**Operating system:** Ubuntu Server

**Web server:** Apache?

**Database:** MySQL?

**PHP version:** 7.4

**Nextcloud version:** 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** No, fresh install

**Where did you install Nextcloud from:** snap bundle on ubuntu

```
No errors have been found.
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
![Screen Shot 2020-12-30 at 2 16 58 PM](https://user-images.githubusercontent.com/24350198/103376102-bb770500-4aa9-11eb-8575-823a87d0dc28.png)

```
</details>

### Client configuration
**Browser:** Firefox 84 and Google Chrome 87

**Operating system:**
Mac OS 10.13.6

**Comment by szaimen** [comment] 2021-06-22 09:13
I cannot reproduce the blurry actions font on NC21.0.2 (for me it is as sharp as any other font in Nextcloud) but might it make sense to not use grey but black for the font here? 
cc @nextcloud/designers

**Comment by juliushaertl** [comment] 2021-06-22 16:48
Not the case anymore for 22 where the style is aligned with the vue components already:

![image](https://user-images.githubusercontent.com/3404133/122967026-516d5780-d38a-11eb-9ad7-33932e9e79fa.png)

**Comment by juliushaertl** [comment] 2021-06-22 17:07
Pushed a fix to https://github.com/nextcloud/server/pull/27604

**Comment by szaimen** [comment] 2021-06-22 23:08
Fixed in https://github.com/nextcloud/server/pull/27604

**Closed by szaimen** 2021-06-22 23:08 UTC
Labels: 0. Needs triage, bug, needs info
