### ISSUE TITLE
PHP Fatal error:  require_once(): \xa9}\xf8\x9a@\xfc\x04\xadX\xfc\x04\xad\x06\x06 in /var/www/nextcloud/status.php on line 32

### ISSUE THREAD

**Issue by ckorn** [nextcloud/server#4019] opened 2017-03-23 18:10 UTC
### Steps to reproduce
1. Create a link to a file with the Nextcloud app
2. Choose a password for the file
3.There is a crash in apache2 on the server. Have to restart apache2 then.

### Expected behaviour
No crash should happen. If there is an error it should lead to a message in the app.

### Actual behaviour
The apache2 seems to crash in a way so that I cannot access nextcloud any longer. I can still access other sites however.

### Server configuration
**Operating system**:
System:    Host: cubie Kernel: 3.4.39 armv7l (32 bit) Console: tty 0
           Distro: Ubuntu 16.04 xenial

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)

**Database:**
mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

**PHP version:**
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Did an update once. But it was already the version 11.

**Where did you install Nextcloud from:**
https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "144.76.200.19:22124",
            "ckorn.eu"
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocfjpedxvyjy",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "christoph.korn",
        "mail_domain": "posteo.de",
        "mail_smtphost": "posteo.de",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No external drive.

**Are you using encryption:** yes/no
I use SSL encryption in apache2.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Web server error log
<details>
<summary>Web server error log</summary>
[Thu Mar 23 17:41:57.136234 2017] [:error] [pid 4640] [client xxx:44969] PHP Fatal error:  Couldn't find implementation for method q\xcc\xc6\xb7\xd8e\xfc\xac\xf0e\xfc\xac\x06\x06::__tostring in Unknown on line 0
[Thu Mar 23 17:41:57.136726 2017] [:error] [pid 4640] [client xxx:44969] PHP Fatal error:  Couldn't find implementation for method q\xcc\xc6\xb7\xd8e\xfc\xac\xf0e\xfc\xac\x06\x06::__tostring in Unknown on line 0
*** Error in `/usr/sbin/apache2': munmap_chunk(): invalid pointer: 0xacbf9a10 ***
[Thu Mar 23 17:41:57.443697 2017] [core:notice] [pid 4617] AH00052: child pid 4640 exit signal Aborted (6)
[Thu Mar 23 17:41:57.571261 2017] [:error] [pid 4621] [client xxx:44970] PHP Fatal error:  require_once(): c\xfe\xa7\xff\xc0f\xfb\xac\xd8f\xfb\xac\x06\x06 in /var/www/nextcloud/lib/base.php on line 54
[Thu Mar 23 17:42:01.822654 2017] [:error] [pid 4663] [client xxx:44971] PHP Fatal error:  Class ' c\xfc\xacptio\x06' not found in /var/www/nextcloud/remote.php on line 40
</details>

**Comment by MorrisJobke** [comment] 2017-03-24 05:59
Looks like a duplicate of #3909

**Closed by MorrisJobke** 2017-03-24 05:59 UTC
