### ISSUE TITLE
Missing "None" when displaying smtp auth options

### ISSUE THREAD

**Issue by Harbardr** [nextcloud/server#11218] opened 2018-09-14 12:36 UTC
Hi,

A simple quote was put instead a double quote.

https://github.com/nextcloud/server/blob/6112adfe064afbad17c485954d22e3947fe8ed13/settings/templates/settings/admin/additional-mail.php#L99

KR,

**Comment by MorrisJobke** [comment] 2018-09-27 15:01
Duplicate of #6304 - fix is in #11416

**Closed by MorrisJobke** 2018-09-27 15:01 UTC
Labels: bug
