### ISSUE TITLE
OSX Client uploads fail on NC16

### ISSUE THREAD

**Issue by unused-username** [nextcloud/server#17571] opened 2019-10-17 04:10 UTC
I'm not sure if this is a bug or a KCI fail, but would be very grateful of advice if it appears to be the latter?

Steps to reproduce
1. Install NC16 on RPi4 using NCP image
2. Restore full backup from NC15
3. Connect OSX client
4. Create file on OSX machine

### Expected behaviour
File uploaded to server

### Actual behaviour
File not uploaded. Error reported “Sabre\DAV\Exception\BadRequest”,“Message”:“expected filesize 41151 got 8192”

### Server configuration

**Operating system**:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Web server:**
Server version: Apache/2.4.38 (Raspbian)
Server built:   2019-04-07T18:15:40

**Database:**
mariadb  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2

**PHP version:**
PHP 7.0.33-11+0~20190923.20+debian9~1.gbpd05c7e (cli) (built: Sep 23 2019 12:22:30) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud version | 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
NextCloudPi image

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - admin_notifications
  - calendar
  - contacts
  - encryption
  - files_external
  - gallery
  - news
  - nextcloudpi
  - notes
  - tasks
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "1": "192.168.1.8",
            "2": "domain.tld",
            "4": "domain.tld",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "9": "my ip",
            "20": "domain.tld",
            "21": "192.168.1.6"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/domain.tld\/",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "logfile": "\/media\/USBdrive\/ncdata\/nextcloud.log",
        "loglevel": "2",
        "log_type": "file",
        "jpeg_quality": "60",
        "theme": "",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "trashbin_retention_obligation": "30, 90",
        "data-fingerprint": "2bf3fde15c1fe982ebb03661ba263e24"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
/dev/sda2 /media/ncdb ext4 defaults 0 0
/dev/sda3 /media/USBdrive btrfs defaults  0 0
/dev/sda4 /media/backups btrfs defaults 0 0

**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
I don't know
#### LDAP configuration (delete this part if not used)
Also don't know
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder
There are no commands defined in the "ldap" namespace.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
N/A

**Operating system:**
OSX

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"XaNno-JJhL0oWWqMnoCmRQAAAIc","level":4,"time":"2019-10-13T18:06:27+00:00","remoteAddr":"a.b.c.d","user":"Username","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/Username\/filepathname.ext","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 41151 got 8192","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["filename.ext",null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["files\/filename.ext",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.hrperth.com.au\/remote.php\/dav\/files\/filename.ext","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/domain.tldu\/remote.php\/dav\/files\/filename.ext","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/domain.tld\/remote.php\/dav\/files\/Username\/Cfilepathname.ext","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/domain.tld\/remote.php\/dav\/files\/Username\/Cfilepathname.ext","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":228,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.6.0stable (build 20190927) (Nextcloud)","version":"16.0.5.1"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment] 2021-05-27 09:19
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 09:19 UTC
Labels: 0. Needs triage, bug
