### ISSUE TITLE
Apps page blank with “An error occured during the request. Unable to proceed.” error

### ISSUE THREAD

**Issue by ThornedRose** [nextcloud/server#11300] opened 2018-09-20 05:06 UTC
The admin logging page is also blank with loading spinner.

### Steps to reproduce
1. Installed Nextcloud 14 (fresh install)
2. Logged in
3. Clicked on Apps menu item / Click on Logging

### Expected behaviour
Apps page should load. Should be able to disable/enable apps and browse apps to download and install. Logging page should load.

### Actual behaviour
Apps pages are blank with just the circle loading animation. An error that is repeated three times appears in the notifications at the top of the screen, “An error occured during the request. Unable to proceed.”.
Screenshot: https://help.nextcloud.com/uploads/default/original/2X/0/0534e4916e1c5483ca4900886c043f9e3bffad89.png
The admin Logging page is the same but does not have errors appear. It is just blank with the loading spinner.

### Server configuration

**Operating system**: Shared hosting, I think Cloud Linux (kernel 3.10.0-714.10.2.lve1.4.74.el7.x86_64)

**Web server:** Apache 2.4.34 (nginx service is also running)

**Database:** MySQL 5.6.40

**PHP version:** 7.2.10

**PHP info:** https://intothegarbagechuteflyboy.net/phpinfo.php

**Nextcloud version:** (see Nextcloud admin page) 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** FRESH (I did try upgrading from 13.0.5 but had issues with the calendar and contacts apps being disabled and reset. Installing apps kept failing so I decided to start fresh.

**Where did you install Nextcloud from:** Softaculous (cPanel)

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

```
No errors have been found.
```

**List of activated apps:**
Can't access apps. But all the default ones that are activated on fresh install.

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Don't have access (shared hosting)

**Nextcloud configuration:**
<details>
<summary> config.php</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'passwordsalt' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'secret' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'trusted_domains' => 
  array (
    0 => 'intothegarbagechuteflyboy.net',
  ),
  'datadirectory' => '/home/intothegarbage/nextclouddata',
  'dbtype' => 'mysql',
  'version' => '14.0.0.19',
  'overwrite.cli.url' => 'https://intothegarbagechuteflyboy.net/nextcloud',
  'dbname' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'dbpassword' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'mail_domain' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'mail_smtpport' => '465',
  'mail_smtpname' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'mail_smtppassword' => '▓▓▓▓▓▓▓▓▓▓▓▓▓',
  'memcache.local' => '\OC\Memcache\APCu',
);

```
</details>

**Are you using external storage, if yes which one:** N/A

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** Not yet but would be webdav

### Client configuration
**Browser:** Firefox 62

**Operating system:** Arch Linux

#### Web server error log
I only have access to home/user/logs files. This log also dates back to the 13.0.5 install which had issues with webdav
**Web server error log:** https://intothegarbagechuteflyboy.net/intothegarbagechuteflyboy.net-Sep-2018.log

#### Nextcloud log (data/nextcloud.log)
The only issue in this log is a warning about intl falback which I have fixed by enabling the intl module. Since doing that there is nothing more in the log. Below is the last log entry.
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"W6HuwlSYVdZD449RsLAVdQAAAM0","level":3,"time":"2018-09-19T06:37:55+00:00","remoteAddr":"121.99.121.82","user":"stormrose","app":"PHP","method":"GET","url":"\/nextcloud\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/intothegarbage\/public_html\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.0.19"}
```
</details>

#### Browser log
<details>
<summary>Browser console log</summary>

```
Content Security Policy: The page’s settings blocked the loading of a resource at data:font/woff;base64,d09GRgABAAAAAIw4AB... (“font-src”).
JQMIGRATE: Migrate is installed, version 1.4.0 jquery-migrate.min.js:2:542
New search handler registered search.js:66:4
Shutting down notifications: [500] Internal Server Error App.vue:144
_fetch/<
App.vue:144
Object { users: Getter & Setter, apps: Getter & Setter, settings: Getter & Setter, oc: Getter & Setter, route: Getter & Setter, … }
 Error: "Request failed with status code 500"
exportshttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:13:17293exportshttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:45:1313hhttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:13:16307 index.js:43:2
Object { users: Getter & Setter, apps: Getter & Setter, settings: Getter & Setter, oc: Getter & Setter, route: Getter & Setter, … }
 Error: "Request failed with status code 500"
exportshttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:13:17293exportshttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:45:1313hhttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:13:16307 index.js:43:2
Object { users: Getter & Setter, apps: Getter & Setter, settings: Getter & Setter, oc: Getter & Setter, route: Getter & Setter, … }
 Error: "Request failed with status code 500"
exportshttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:13:17293exportshttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:45:1313hhttps://intothegarbagechuteflyboy.net/nextcloud/settings/js/settings-vue.js:13:16307 index.js:43:2
```
</details>

**Browser network har file:**

[http://intothegarbagechuteflyboy.net/Archive%2018-09-20%2016-31-55.har](http://intothegarbagechuteflyboy.net/Archive%2018-09-20%2016-31-55.har)

**Comment by ThornedRose** [comment] 2018-09-20 05:08
Cross posted here: https://help.nextcloud.com/t/nextcloud-14-flakey-tried-upgrade-and-fresh-apps-page-blank-with-an-error-occured-during-the-request-unable-to-proceed/37145

**Comment by avillafiorita** [comment] 2018-10-07 19:31
if it can help, I had the same issue. I partly solved it by disabling the app store, that is, by setting

    'appstoreenabled' => false,

in `config.php`. 

Now the apps page shows correctly, I can enable and disable installed apps, but I cannot install new apps... an obvious and inconvenient side effect of the "fix".

**Comment by DrEVILish** [comment] 2018-10-19 03:13
I am also having the same issue,

I'm running NextCloud's docker image, arm64-apache-14

I'm running in a docker-swarm with 3 hosts one running DB the other two running the NextCloud docker image. The two Containers share access to the /data and /config folder on an external file share. They each load and store their own /apps folder within the container.

When loading the 
"files" - "Problem loading page, reloading in 2 seconds"
 "apps" - "An error occured during the request. Unable to proceed."

Tested using Chrome 70.0.3538.67 (64bit) - MacOS

**Comment by avillafiorita** [comment] 2018-10-19 13:17
In my case the problem was apparently caused by wrong ownership of the `/usr/local/var/run/nginx/fastcgi_temp/` directory.

More in details: I changed the user running nginx and php-fpm and forgot to change the owner of the `/usr/local/var/run/nginx/fastcgi_temp/` dir. The effect was the impossibility of downloading big files from the server. The ownership mismatch might have also caused the issue with the app store. 

It is "might" and not "definitely" because, in the meantime, I also upgraded Nextcloud from 14.0.0 to 14.0.3 and I can't tell which of the two interventions solved the issue with the app store.

**Comment by DrEVILish** [comment] 2018-10-20 01:12
Found out my issue was because my Docker Swarm wasn't sticking the client to one server.

When I went back to only one node v14 worked fine.

**Comment by Fiech** [comment] 2018-11-11 22:15
I'm experiencing the same behavior like @ThornedRose.

This problem was already present in 14.0.1. Wenn I upgraded to 14.0.3, it was shortly remedied, but returned about an hour later...

**Comment by DJJo14** [comment] 2018-11-22 12:30
I had the same problem. I could not found anything in the log (maybe the log shut be at debug level). at the admin overview i saw, error in server configuration
but i remembered install the "files_external_gdrive"

so disabling the "files_external_gdrive" fixed the issue. 
`php occ app:disable files_external_gdrive` (with portainer bash as user www-data)

running 14.0.3 from the latest docker container (created 21-11-2018)
i have been upgrading from owncloud 8.1->9.0->nextcloud 9-> (with extra steps) 14

**Comment by skjnldsv** [comment] 2020-04-10 07:19
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen

**Closed by skjnldsv** 2020-04-10 07:19 UTC
Labels: 0. Needs triage, bug
