### ISSUE TITLE
PNGs with larger sizes fail to upload

### ISSUE THREAD

**Issue by BlackHoleFox** [nextcloud/server#10345] opened 2018-07-23 02:38 UTC
### Steps to reproduce
1. Install the latest snap on Ubuntu 16 LTS
2. Try to upload a .png with a larger resolution and filesize ( 4.34 MB)
3. Look at the browser console to see error

### Expected behavior
The file should upload to the server

### Actual behavior
An error is thrown in the console and the webpage hangs forever

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1.17

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Ubuntu Snap

**Signing status:**
```
No errors
```
**Browser Log**:
```
core.js?v=960bda7d-8:4 PUT https://domain.domain.com/remote.php/webdav/FirefoxIcon2.png 413 ()
merged-index.js?v=960bda7d-8:1318 Uncaught TypeError: Cannot read property 'message' of undefined
    at HTMLInputElement.fail (merged-index.js?v=960bda7d-8:1318)
    at e.(/index.php/apps/files/anonymous function).(anonymous function)._trigger (https://domain.domain.com/core/vendor/core.js?v=960bda7d-8:13:10075)
    at e.(/index.php/apps/files/anonymous function).(anonymous function)._onFail (https://domain.domain.com/index.php/js/files/merged-index.js?v=960bda7d-8:2672:18)
    at e.(/index.php/apps/files/anonymous function).(anonymous function)._onFail (https://domain.domain.com/core/vendor/core.js?v=960bda7d-8:13:5077)
    at Object.<anonymous> (merged-index.js?v=960bda7d-8:2706)
    at j (core.js?v=960bda7d-8:2)
    at Object.fireWith [as rejectWith] (core.js?v=960bda7d-8:2)
    at x (core.js?v=960bda7d-8:4)
    at XMLHttpRequest.<anonymous> (core.js?v=960bda7d-8:4)
```

**Comment by BlackHoleFox** [comment] 2018-07-23 18:13
The bot is partly right but I have found no actual solutions or talk of a fix being implemented. I have tested with the client and it says the server responds with a file too large error. Does anyone know how to either fix this or to enable a larger upload size with a Snap install?

**Comment by MorrisJobke** [comment] 2018-07-24 11:59
cc @kyrofa for the snap question.

**Comment by skjnldsv** [comment] 2019-06-07 15:59
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-07 15:59 UTC
Labels: bug
