### ISSUE TITLE
[Bug]: TypeError on login with app token in OC\Core\Service\LoginFlowV2Service::flowDoneWithAppPassword

### ISSUE THREAD

**Issue by troethe** [nextcloud/server#34930] opened 2022-11-02 19:44 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Trying to log in with CalDavx5 on Android using an app token, I get an internal server error. I attached the log entry that contains the ReqId given on the error page.

### Steps to reproduce

1. Generate new app token under Personal Settings -> Security
2. Try to log in using some app
3. Get inernal server error

### Expected behavior

I'd expect it to grant access to the app

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### Web server

Nginx

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.myserver.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.0.18",
        "overwrite.cli.url": "https:\/\/cloud.myserver.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - calendar: 4.1.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - richdocuments: 7.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.4.0
  - cospend: 1.4.10
  - deck: 1.7.2
  - encryption
  - files_trashbin: 1.14.0
  - mail: 1.14.1
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"BTOpV8HS2NF2Uj2mg0Vp","level":3,"time":"2022-11-02T18:35:03+00:00","remoteAddr":"my:ipv6::address","user":"--","app":"index","method":"POST","url":"/login/v2/apptoken","message":"OC\\Core\\Service\\LoginFlowV2Service::flowDoneWithAppPassword(): Argument #3 ($loginName) must be of type string, null given, called in /var/www/html/core/Controller/ClientFlowLoginV2Controller.php on line 219 in file '/var/www/html/core/Service/LoginFlowV2Service.php' line 181","userAgent":"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Mobile Safari/537.36","version":"25.0.0.18","exception":{"Exception":"Exception","Message":"OC\\Core\\Service\\LoginFlowV2Service::flowDoneWithAppPassword(): Argument #3 ($loginName) must be of type string, null given, called in /var/www/html/core/Controller/ClientFlowLoginV2Controller.php on line 219 in file '/var/www/html/core/Service/LoginFlowV2Service.php' line 181","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"apptokenRedirect"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\ClientFlowLoginV2Controller","apptokenRedirect",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["core.ClientFlowLoginV2.apptokenRedirect"]]},{"file":"/var/www/html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login/v2/apptoken"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OC\\Core\\Service\\LoginFlowV2Service::flowDoneWithAppPassword(): Argument #3 ($loginName) must be of type string, null given, called in /var/www/html/core/Controller/ClientFlowLoginV2Controller.php on line 219","Code":0,"Trace":[{"file":"/var/www/html/core/Controller/ClientFlowLoginV2Controller.php","line":219,"function":"flowDoneWithAppPassword","class":"OC\\Core\\Service\\LoginFlowV2Service","type":"->","args":["SomeBase64String","https://cloud.myserver.com",null,"to-ke-n1-23"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"apptokenRedirect","class":"OC\\Core\\Controller\\ClientFlowLoginV2Controller","type":"->","args":["SomeOtherBase64String","username123","to-ke-n1-23"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"apptokenRedirect"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"apptokenRedirect"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\ClientFlowLoginV2Controller","apptokenRedirect",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["core.ClientFlowLoginV2.apptokenRedirect"]]},{"file":"/var/www/html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login/v2/apptoken"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/core/Service/LoginFlowV2Service.php","Line":181},"CustomMessage":"--"}}
```

### Additional info

I replaced some potentially sensitive information in the logs, including server domain name, client IP address, the user (now user123), the used token (now to-ke-n1-23) and two strings in Base64 whose purpose I didn't understand (SomeBase64String and SomeOtherBase64String). Please let me know if I missed anything else sensitive.

I was able to log in with the Nextcloud app with an app token and the QR-code just a couple of minutes before I noticed this problem.

I also get a lot of errors of [this kind](https://help.nextcloud.com/t/backends-provided-no-user-object-for-a-deleted-user/54862) in the logs for another deleted user. Not sure if related. This other user was however deleted long before this issue.

**Comment by CarlSchwan** [comment] 2022-11-03 11:28
Could you try the following patch?
[fix-loginName-empty.txt](https://github.com/nextcloud/server/files/9927869/fix-loginName-empty.txt)

To apply, download the file and run patch -p1 < fix-loginName-empty.txt in your nextcloud root folder

**Comment by troethe** [comment] 2022-11-03 12:24
Worked! Thanks, for the quick solution!

**Comment by miccgn** [comment] 2022-11-06 19:14
Had the same problem, patch worked for me as well.

**Comment by kesselb** [comment] 2022-12-02 16:47
Thanks for your bug report :+1: 

Closing as duplicate of https://github.com/nextcloud/server/issues/33187

**Closed by kesselb** 2022-12-02 16:47 UTC
Labels: bug, 0. Needs triage, 25-feedback
