### ISSUE TITLE
Web Update Error from 17.0.10 to 18.0.11: InvalidArgumentException

### ISSUE THREAD

**Issue by harriejean** [nextcloud/server#24415] opened 2020-11-27 13:51 UTC
Hi folks,

while updating via web updater from 17.0.10 to 18.0.11 I got follow error message and protocol:

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
InvalidArgumentException: Column name "yHlzy_flow_operations"."entity" is NotNull, but has empty string or null as default.

What should I do. Can I roll back to 17.0.10 (it worked)? Where are the backed up files mentioned in the web update log?

**Comment by kesselb** [comment] 2020-11-27 14:01
Duplicate of https://github.com/nextcloud/server/issues/23174

**Closed by kesselb** 2020-11-27 14:01 UTC
Labels: 0. Needs triage, bug
