### ISSUE TITLE
Web upgrade with lost+found in data directory does not work

### ISSUE THREAD

**Issue by Belse** [nextcloud/server#6906] opened 2017-10-22 22:19 UTC
### Steps to reproduce
1. Upgrade nextcloud from 11.03 to 12.03 from administrators panel
2. Upgrade fails when making backup due to read error of "lost+found" in nextcloud/data directory

### Expected behaviour
It should ignore lost+found folder

### Actual behaviour
Upgrade stops.
After setting chmod o+rw on lost+found it works (but I shouldn't have to)

### Server configuration
Ubuntu 16.04, apache.. ext4 fs of course :)
The rest shouldn't matter.

**Comment by blizzz** [comment] 2017-10-24 10:44
Lost+Found should not be there. The  data folder is supposed to be controlled by just Nextcloud. I assume you are mounting this. In that case, it is best to not use root level of the mount but create a subdirectory within and use this as data folder. However changing the datadir in Nextcloud's config is not supported, you'd want to keep the path intact.

cc @icewind1991

**Comment by Belse** [comment] 2017-10-24 11:40
I'd say nextcloud should support having a root mount as a data dir, or root installation folder. Since it's for file-sharing and thus might need a large separate filesystem.
Currently it works perfectly and only trouble is with the upgrader, which can easily detect and skip this folder.
I could set the datadir to be elsewhere but my experience with other software says things break especially in upgraders which might not probe for the correct location of dirs (staring at pydio).

**Comment by MorrisJobke** [comment] 2017-12-14 14:18
This is an updater issue and was already reported there.

Duplicate of https://github.com/nextcloud/updater/issues/68

**Closed by MorrisJobke** 2017-12-14 14:18 UTC
Labels: feature: filesystem
