### ISSUE TITLE
17.0.0 Theme changes delay

### ISSUE THREAD

**Issue by tonyhon** [nextcloud/server#17321] opened 2019-09-29 01:22 UTC
Hi

First time using nextcloud.  Just brand new install on Ubuntu 18, at first when I change something in Theme, such as the web link, the whole site's CSS will disappear, no styles apply.  Some other theme setting will do the same thing.  I keep undo my changes but nothing seems to help.

After a while I found out, the styles will come back eventually after like 5 minutes and become normal again.

Also, can anyone tell me why in the Admin->Overview it's showing my nextcloud version is 17.0.0, while the download page's most stable release is 16?  I have the auto update on, but only to stable release.

Thanks.

**Comment by skjnldsv** [comment] 2019-09-30 13:47
Duplicate of #14615

**Closed by skjnldsv** 2019-09-30 13:47 UTC
