### ISSUE TITLE
Add the ability to change the color of folders

### ISSUE THREAD

**Issue by Robert-Clever** [nextcloud/server#34738] opened 2022-10-22 02:00 UTC
In the current files app folders are all one color, blue. It would be cool if you could change the color of the folders like you can in Google Drive.

**Comment by Robert-Clever** [comment] 2023-04-01 12:53
The Nextcloud IOS app added the ability to change the color of folders. It still doesn't seem like you can change the color of folders in Nextcloud Desktop. It would be cool to add this functionality.

**Comment by Robert-Clever** [comment] 2023-08-06 15:01
Any update on this? I don't use Nextcloud anymore and can't check if this feature has been added or not. I can close out this ticket if this is not needed or has already been planned into a future release.

**Comment by joshtrichards** [comment] 2023-09-04 14:38
Duplicate of #33571

**Closed by joshtrichards** 2023-09-04 14:38 UTC
Labels: enhancement, 0. Needs triage, feature: files
