### ISSUE TITLE
Login delay after unsuccessful attempts even if right login password given

### ISSUE THREAD

**Issue by farindk** [nextcloud/server#14142] opened 2019-02-11 11:37 UTC
After a number of unsuccessful login attempts, Nextcloud adds a login delay to further login attempts.
So far so good.

However, NC also imposes this delay when the login data is now entered correctly. I think this is unneeded and annoying to the user. A correct login should succeed immediately.
In fact, one could even remove the login delay after a successful login from this IP. Currently, the login delay is blindly applied even after the user logged in successfully several times.

**Comment by skjnldsv** [comment] 2020-08-20 13:51
cc @MorrisJobke @rullzer ?

**Comment by MorrisJobke** [comment] 2020-08-20 15:09
> However, NC also imposes this delay when the login data is now entered correctly. I think this is unneeded and annoying to the user. A correct login should succeed immediately.

That's the whole point of the delay. If the attacker would know that we succeed immediately on success then the attacker could just fire the requests and doesn't need to wait for the response as they know that it would have succeeded right away if it would be correct.

The delay is also reset for the IP & username combination. Not for other usernames. Because otherwise you could bruteforce other accounts by logging successfully in with your account every few tries to reset the bruteforce attempts. Thus I will close this ticket as "works as intended"

**Closed by MorrisJobke** 2020-08-20 15:09 UTC
Labels: 0. Needs triage, bug
