### ISSUE TITLE
Cant Download log file Nextcloud 15 Error UnexpectedValueException: Log file not available

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#13289] opened 2018-12-29 19:40 UTC
Nextcloud 15
PHP 7.2
Apatche2 
MYSQL

Getting the following error when trying to download log file. 

<img width="1321" alt="screen shot 2018-12-29 at 1 36 23 pm" src="https://user-images.githubusercontent.com/24574019/50541612-24e87400-0b6f-11e9-8b63-8ceb91bb3102.png">

Error | index | UnexpectedValueException: Log file not available/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OC\Settings\Controller\LogSettingsController->download()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "download")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "download")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OC\\Setting ... r", "download", OC\AppFramew ... {}, { _route: "s ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "s ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/settings/admin/log/download")/var/www/nextcloud/index.php - line 42: OC::handleRequest()
-- | -- | --

**Comment by danielkesselberg** [comment] 2018-12-29 20:52
Duplicate of https://github.com/nextcloud/server/issues/13285

**Closed by danielkesselberg** 2018-12-29 20:52 UTC
Labels: 0. Needs triage, bug
