### ISSUE TITLE
Allow upload and editing on sharing results in read only

### ISSUE THREAD

**Issue by lapor-kris** [nextcloud/server#27962] opened 2021-07-14 09:32 UTC
### Steps to reproduce
1. Set share link on a folder you wish to share
2. click read only
3. open in private window of browser to see what you can do with the files
4. change to allow upload and editing
5. open in private window of browser to see what you can do with the files

### Expected behaviour
It should change to edit mode, so one can edit and upload.

### Actual behaviour
It stays the same as on read only mode. One can only download or read the files.

### Server configuration

**Operating system:** Ubuntu 20.04

**Database:** mysql

**PHP version:** 7.4.3

**Nextcloud version:** (see Nextcloud admin page) 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 20.0.8

**Where did you install Nextcloud from:** Docker

**Comment by lamixer** [comment] 2021-07-23 11:47
I think this is same as my bug:

If the Admin setting for 'allow public uploads' is unchecked, and you create a folder, then share the folder, then go back and look at the share details, there is a check box for "Allow editing" which you CAN check! But if you close that and return to it later, the box will be unchecked (and of course, functionally it doesn't work).

If you then switch on 'allow public uploads' in Settings > Admin > Sharing > Allow Users to share via link > Allow public uploads things change.

Go back to the folder you have shared, now it looks different: there are radio buttons to pick from "Read only", "Allow upload and editing", "File drop".

Probably the best UI would be for the latter to be always shown (the three radio button options) but if "Allow public uploads" is not enabled in settings, the options besides 'Read only" are greyed out / not selectable.

**Comment by szaimen** [comment] 2021-08-08 15:58
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Comment by lamixer** [comment] 2021-08-08 16:42
Hello:

I am running 21.0.3 which is the current stable version. Can you please attempt to confirm it?

Let me try to make the steps more concise:

Go to Settings > Admin > Sharing
Ensure "Allow users to share via link" is checked
Ensure "Allow public uploads" is NOT checked
Go to one of your folders in the Files app
Click to open the sharing sidebar
Click + in "Share link"
After it shares the link and auto-copies the link to the clipboard, click the three dot menu
Click "Allow editing"
Visit the link in a new window
No way to upload a file.
Close window in which you opened the link
Refresh the Files list and view the "Share link" options again in the three dot menu
"Allow editing" is no longer checked.

This is a cross between user error and bad UI. Please read the latter portion of my comment above for my thoughts on that. 

Thank you.

**Comment by lamixer** [comment] 2021-08-08 16:46
... if you are saying this has been fixed/changed in 22.1.0 then that's great news and I will go to that when it reaches the stable branch.

**Comment by szaimen** [comment] 2021-08-08 16:47
[This](https://github.com/nextcloud/server/issues/27962#issuecomment-894823550) I can reproduce.
Here is the browser log:
![image](https://user-images.githubusercontent.com/42591237/128639287-583165b9-8ffa-41d7-a972-9155ff9d5afe.png)

**Closed** 2021-12-14 12:06 UTC
Labels: bug, 1. to develop, feature: sharing, feature: settings
