### ISSUE TITLE
occ files:scan - an exception occures if folder or file name contains a '+' character.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#4853] opened 2017-05-13 10:17 UTC
## Expected behavior
The `occ files:scan` command should be able to handle folder and file names correctly which contain a +-character when it scans a mounted WebDAV share.

## Current behavior
An exception occurs if the `occ files:scan` command tries to scan a folder or file with a +-character in its name on a mounted WebDAV share. The following error message is displayed on th console:
```
Exception while scanning: Not Found
#0 /var/www/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Client.php(231): Sabre\HTTP\Client->send(Object(Sabre\HTTP\Request))
#1 /var/www/htdocs/nextcloud/lib/private/Files/Storage/DAV.php(276): Sabre\DAV\Client->propFind('Eigene%20Dokume...', Array)
#2 /var/www/htdocs/nextcloud/lib/private/Files/Storage/DAV.php(708): OC\Files\Storage\DAV->propfind('Eigene Dokument...')
#3 /var/www/htdocs/nextcloud/lib/private/Files/Storage/Common.php(649): OC\Files\Storage\DAV->getPermissions('Eigene Dokument...')
#4 /var/www/htdocs/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(577): OC\Files\Storage\Common->getMetaData('Eigene Dokument...')
#5 /var/www/htdocs/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php(460): OC\Files\Storage\Wrapper\Wrapper->getMetaData('Eigene Dokument...')
#6 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(114): OC\Files\Storage\Wrapper\Availability->getMetaData('Eigene Dokument...')
#7 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(153): OC\Files\Cache\Scanner->getData('Eigene Dokument...')
#8 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(420): OC\Files\Cache\Scanner->scanFile('Eigene Dokument...', 3, '515872', NULL, true)
#9 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('Eigene Dokument...', true, 3, '515872', true, 4096472)
#10 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('Eigene Dokument...', true, 3, 515872, true)
#11 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('Eigene Dokument...', true, 3, 419427, true)
#12 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('Eigene Dokument...', true, 3, 419404, true)
#13 /var/www/htdocs/nextcloud/lib/private/Files/Cache/Scanner.php(322): OC\Files\Cache\Scanner->scanChildren('', true, 3, 419403, true)
#14 /var/www/htdocs/nextcloud/lib/private/Files/Utils/Scanner.php(196): OC\Files\Cache\Scanner->scan('', true, 3)
#15 /var/www/htdocs/nextcloud/apps/files/lib/Command/Scan.php(159): OC\Files\Utils\Scanner->scan('/juergen')
#16 /var/www/htdocs/nextcloud/apps/files/lib/Command/Scan.php(227): OCA\Files\Command\Scan->scanFiles('juergen', '/juergen', true, Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#17 /var/www/htdocs/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/htdocs/nextcloud/core/Command/Base.php(161): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/htdocs/nextcloud/3rdparty/symfony/console/Application.php(818): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/htdocs/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/htdocs/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/htdocs/nextcloud/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(NULL, NULL)
#23 /var/www/htdocs/nextcloud/console.php(90): OC\Console\Application->run()
#24 /var/www/htdocs/nextcloud/occ(11): require_once('/var/www/htdocs...')
#25 {main}
```
In this case a file named ``20070423_schalterdosen-1+3_garage.jpg`` exists ind the folder. Right after I renamed it to ``20070423_schalterdosen-1_und_3_garage.jpg`` the file scan ran without any further problem.

### Steps to reproduce
1. Run the `./occ files:scan -v <username>` command from the command line.
2. Wait until the mentioned exception occurs.

#### Server Configuration
OS: Linux 3.2.87
Web server: Apache2 2.4.25
Database: MariaDB 5.5.54
PHP version: 5.6.23
Nextcloud version: 11.0.3

#### Client Configuration
Browser: Mozilla Firefox 53.0.2
Operating system: Windows 7

**Comment by ChristophWurst** [comment] 2017-05-16 07:16
Is that a local file or one on an external storage? The stack trace looks suspicious.

I cannot reproduce this with a local file (tried with the exact same file name) –> works.

**Comment by j-ed** [comment] 2017-05-16 07:36
As written the files reside are accessed via a mounted WebDAV share. The share has been created using the external_storage App within Nextcloud.

**Comment by pgassmann** [comment] 2017-08-25 13:42
Just hit that same bug too. on WebDAV as External Storage.

Thank you for the hint with the "+" in the Filename. that was the issue here too.

```
Exception while scanning: Not Found
#0 /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Client.php(231): Sabre\HTTP\Client->send(Object(Sabre\HTTP\Request))
#1 /var/www/nextcloud/lib/private/Files/Storage/DAV.php(268): Sabre\DAV\Client->propFind('https://u46424...', Array)
#2 /var/www/nextcloud/lib/private/Files/Storage/DAV.php(708): OC\Files\Storage\DAV->propfind('Tagungsaufnahme...')
#3 /var/www/nextcloud/lib/private/Files/Storage/Common.php(649): OC\Files\Storage\DAV->getPermissions('Tagungsaufnahme...')
#4 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(577): OC\Files\Storage\Common->getMetaData('Tagungsaufnahme...')
#5 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php(460): OC\Files\Storage\Wrapper\Wrapper->getMetaData('Tagungsaufnahme...')
#6 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php(173): OC\Files\Storage\Wrapper\Availability->getMetaData('Tagungsaufnahme...')
#7 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(577): OC\Files\Storage\Wrapper\Encryption->getMetaData('Tagungsaufnahme...')
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(114): OC\Files\Storage\Wrapper\Wrapper->getMetaData('Tagungsaufnahme...')
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(153): OC\Files\Cache\Scanner->getData('Tagungsaufnahme...')
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(420): OC\Files\Cache\Scanner->scanFile('Tagungsaufnahme...', 3, '25005', NULL, true)
#11 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('Tagungsaufnahme...', true, 3, '25005', true, 728260356)
#12 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('Tagungsaufnahme...', true, 3, '25005', true)
#13 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(322): OC\Files\Cache\Scanner->scanChildren('Tagungsaufnahme...', true, 3, '22127', true)
#14 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(196): OC\Files\Cache\Scanner->scan('Tagungsaufnahme...', true, 3)
#15 /var/www/nextcloud/apps/files/lib/Command/Scan.php(159): OC\Files\Utils\Scanner->scan('/files-admin/fi...')
#16 /var/www/nextcloud/apps/files/lib/Command/Scan.php(227): OCA\Files\Command\Scan->scanFiles('files-admin', '/files-admin/fi...', true, Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#17 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(256): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/nextcloud/core/Command/Base.php(161): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/nextcloud/3rdparty/symfony/console/Application.php(818): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/nextcloud/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/nextcloud/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/nextcloud/console.php(98): OC\Console\Application->run()
#24 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#25 {main}
```

**Comment by realies** [comment] 2019-03-30 22:17
Issue still exists in 15.0.5

**Comment by szaimen** [comment] 2021-05-20 11:52
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since over 2 years. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen or create a new issue.

**Closed by szaimen** 2021-05-20 11:52 UTC
Labels: 1. to develop, bug, feature: external storage
