### ISSUE TITLE
%20 and such URI codes are causing problems on a step called URIdecode in parsing the webdav result.

### ISSUE THREAD

**Issue by MparkG** [nextcloud/server#11646] opened 2018-10-05 20:09 UTC
### Steps to reproduce
1. have files named with %20 or %28 in their name in a folder, e.g.
`%28ebook%20-%20german%29%20Gesetzestexte%20-%20Betriebsverfassungsgesetz%20%28.pdf`
2. Try to show that folder in nextcloud
3. no profit.

### Expected behaviour
The File List should be displayed.-
### Actual behaviour
The Loading circle rotates endlessly, whilst in the console this error appears:
Uncaught (in promise) URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Client._parseFileInfo (client.js:283)
    at client.js:407
    at Function._.map._.collect (core.js:185)
    at Client._parseResult (client.js:406)
    at client.js:488

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
14.something, bug appeared with update to 14.

**Comment by kuhnline** [comment] 2018-10-06 01:01
I have user user with 2 folders in his root folder named
_Job 90% CD
Job 100% CD_
so his root folder would not load at all - just a spinning wheel, even if you let it run all day

I renamed the folders to
_Job 90percent CD
Job 100percent CD_
and the problem is solved.
But it wasted 2 hours of my time to figure this out.

These folders have existed since Version 12 so this error is new with Version 14.

**Comment by icewind1991** [comment] 2019-01-08 14:54
I can't reproduce this issue with either nc14.0.4 or 15.0.0, all combination of filenames with '%' in them work as expected

**Comment by juliushaertl** [comment] 2019-01-08 14:59
Yes, should be fixed in >=14.0.4 with https://github.com/nextcloud/server/pull/11744

**Closed by juliushaertl** 2019-01-08 14:59 UTC
Labels: bug, feature: dav, feature: files, feature: filesystem
