### ISSUE TITLE
[Bug]: 3.14.1版本win10会导致任务栏卡死，结束进程重启任务栏就会恢复

### ISSUE THREAD

**Issue by pewjs** [nextcloud/server#48677] opened 2024-10-13 12:41 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Bug]: 3.14.1版本win10会导致任务栏卡死，结束进程重启任务栏就会恢复，在上传很多小文件例如几千个，会导致此类问题

### Steps to reproduce

1.准备几千个小文件
2.3.14.1版本win10
3.

### Expected behavior

任务栏卡死

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-10-13 15:31
Duplicate of nextcloud/desktop#7313

**Closed by joshtrichards** 2024-10-13 15:31 UTC
Labels: bug, 0. Needs triage
