### ISSUE TITLE
webdav no write-protection message when open microsoft word/excel file that already open

### ISSUE THREAD

**Issue by nobe80** [nextcloud/server#25188] opened 2021-01-18 16:06 UTC
Hi!

when i open in Windows 10 a Microsoft Word or Excel file that is already open by another user then i dont get a message in Word/Excel that the file is already in use. Double check with Word/Excel files located in SMB shares it works as expected. 

This is very critical because all changes that the "second user" made are discarded!

**Comment by kesselb** [comment] 2021-01-18 19:36
Closing as duplicate of https://github.com/nextcloud/server/issues/1308

**Closed by kesselb** 2021-01-18 19:36 UTC

**Comment by nobe80** [comment] 2021-01-19 09:04
Hi kesselb,

the Temporarly File Lock App is not a solution for WebDAV Users because they have to lock every time in the webinterface each single file and unlock it again. We switched from Plesk Filesharing where we had a filelock if the file was already open by another user. It is possible to get another way to lock files if they are open by another user?

**Comment by kesselb** [comment] 2021-01-19 09:41
> It is possible to get another way to lock files if they are open by another user?

Feel free to create a feature request https://github.com/nextcloud/server/issues/new?assignees=&labels=enhancement%2C+0.+Needs+triage&template=Feature_request.md (stick to the template!).

https://github.com/nextcloud/server/issues/1308
https://github.com/nextcloud/server/issues/5006
https://github.com/nextcloud/server/issues/9969
https://github.com/nextcloud/server/issues/12442

I don't think the feature is on the roadmap. It seems files_lock is the best we have to offer.
