### ISSUE TITLE
Nextcloud 12.0.4 integrity check fails if base folder name is not "nextcloud"

### ISSUE THREAD

**Issue by palto42** [nextcloud/server#7436] opened 2017-12-09 12:37 UTC
The upgrade from 12.0.3 to 12.0.4 worked in principle, but after the upgrade an integrity check error was shown on the web interface. During the upgrade on CLI with "occ upgrade" there was no error shown.

After some testing I found that the issue is caused by a non-standard base folder name. My Nextcloud installation was in the folder "cloud" instead of standard "nextcloud".
After changing the folder name to "nextcloud" (and updating the nginx config) the integrity check was gone. Changing it back again to "cloud" caused immediately the integrity check error.

### Steps to reproduce
1. Stop web server
2. Rename folder "nextcloud" to "cloud"
3. Update web server config with changed folder name
4. Restart web server
5. Browse to the Nextcloud instance 

### Expected behaviour
A changed folder name should have no impact, all should work as before.

### Actual behaviour
An integrity check error is shown, the list of invalid files seems to list all files

### Server configuration

**Operating system**:
Raspberry Pi 2B with Debian Jessie 

**Web server:**
nginx version: nginx/1.6.2

**Database:**
mysql  Ver 15.1 Distrib 10.0.32-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2

**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Apr 14 2017 16:20:58)

**Nextcloud version:** (see Nextcloud admin page)
12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from 12.0.3

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-12.0.4.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- nextcloud/apps/encryption/appinfo/routes.php
		- nextcloud/apps/encryption/appinfo/app.php
		- nextcloud/apps/encryption/appinfo/info.xml
		- nextcloud/apps/encryption/appinfo/signature.json
		- nextcloud/apps/encryption/img/app.svg

(... >39000 lines)

</details>

**Comment by MorrisJobke** [comment] 2017-12-10 09:44
This looks like you put the whole release additionally into the subfolder "nextcloud" in you nextcloud root directory where also the apps folder and config folder is located for example. You should not have a copy of the whole code there. Just remove it and retrigger the scan. That is also the reason, why it says "EXTRA_FILE".

**Comment by palto42** [comment] 2017-12-10 09:48
No, there is no extra subfolder "nextcloud" and I faced no such issue in previous upgrades (I'm using Nextcloud/Ownloud since years). 
My folder structure which causes the issue is simply `/var/www/cloud/` 
If I rename it to `/var/www/nextcloud`, then the integrity check works.

**Comment by guillaumedsde** [comment] 2017-12-18 09:21
up have the same problem, code integrity check does not pass if nextcloud's root isn't named nextcloud (mine is named web)

**Comment by blizzz** [comment] 2018-11-01 14:13
Maybe run a re-run the integrity check from occ after changing the folder name. On my server it is not nextcloud, either, and never had an issue with that.

**Comment by MorrisJobke** [comment] 2018-11-29 22:05
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2018-11-29 22:05 UTC
Labels: feature: install and update, needs info
