### ISSUE TITLE
[Bug]: Impossible to autoconfigure email in NC Email

### ISSUE THREAD

**Issue by RaitoBezarius** [nextcloud/server#42348] opened 2023-12-18 10:33 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When auto-configuring an email account with NC email, it fails with "autoconfiguration is temporary unavailable".

### Steps to reproduce

1. Setup an email server with `go-autoconfig` for the autoconfiguration component
2. Try to autoconfigure via NC Email
3. Fail.

### Expected behavior

Expected not to crash.

### Installation method

Other Community project

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/store-apps",
                "url": "\/store-apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "loglevel": "2",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "FR",
        "profile.enabled": false,
        "allow_local_remote_servers": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "opcache.interned_strings_buffer": 32,
        "overwrite.cli.url": "https:\/\/cloud.dgnum.eu",
        "overwritehost": "cloud.dgnum.eu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "updatechecker": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "version": "27.1.4.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud-dgnum",
                "verify_bucket_exists": false,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "s3.dgnum.eu",
                "port": 443,
                "use_ssl": true,
                "region": "garage",
                "use_path_style": true
            }
        },
        "objectstore.arguments.signature": "v4",
        "memories.vod.path": "\/var\/lib\/nextcloud\/store-apps\/memories\/bin-ext\/go-vod-amd64",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie"
        ],
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "memories.gis_type": 2,
        "memories.vod.ffmpeg": "\/nix\/store\/4cv4q1k4xlflwaq9vrg5j932xq7hliv2-ffmpeg-headless-6.0-bin\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/nix\/store\/4cv4q1k4xlflwaq9vrg5j932xq7hliv2-ffmpeg-headless-6.0-bin\/bin\/ffprobe",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "memories.exiftool": "\/nix\/store\/wh8hjj88gcws12nyv1nyxx1w722zx4yw-perl5.38.0-Image-ExifTool-12.70\/bin\/exiftool",
        "trusted_domains": [
            "cloud.dgnum.eu"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - calendar: 4.6.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.0
  - contactsinteraction: 1.8.0
  - cospend: 1.5.13
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.2
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - groupfolders: 15.3.1
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.0
  - memories: 6.1.5
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.4.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.3
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - sociallogin: 5.6.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflow_script: 1.12.1
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0 (installed 1.17.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Dec 18 11:25:07 compute01 Nextcloud[353465]: {"reqId":"qMDwsCQWJqr1Z4NjRdVR","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=993","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353465]: {"reqId":"qMDwsCQWJqr1Z4NjRdVR","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=993","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353464]: {"reqId":"ZAB7xbfs391IIxGpLnJa","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=465","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353464]: {"reqId":"ZAB7xbfs391IIxGpLnJa","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=465","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353462]: {"reqId":"uxC61nKXXW7nYoSFbxPu","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=143","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353462]: {"reqId":"uxC61nKXXW7nYoSFbxPu","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=143","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[354145]: {"reqId":"XarjigJXoLy4tOY8hkTY","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=465","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[354145]: {"reqId":"XarjigJXoLy4tOY8hkTY","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=465","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353466]: {"reqId":"iPnf7t1QBtvGNAIcfnpE","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=993","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353466]: {"reqId":"iPnf7t1QBtvGNAIcfnpE","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=993","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353461]: {"reqId":"7pIZyEzUF7t4GallqgQH","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=587","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353461]: {"reqId":"7pIZyEzUF7t4GallqgQH","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=lahfa.xyz&port=587","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353463]: {"reqId":"jmR2jlnnRh2TmnF3ojMh","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=587","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353463]: {"reqId":"jmR2jlnnRh2TmnF3ojMh","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=587","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353981]: {"reqId":"fPtVdnCsSJhwTXjK897z","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=143","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
Dec 18 11:25:07 compute01 Nextcloud[353981]: {"reqId":"fPtVdnCsSJhwTXjK897z","level":3,"time":"2023-12-18T10:25:07+00:00","remoteAddr":"88.174.101.154","user":"dgn_sso-8cc86ff2-fe52-4373-8f57-ddbf6191a528","app":"PHP","method":"GET","url":"/apps/mail/api/autoconfig/test?host=kurisu.lahfa.xyz&port=143","message":"Undefined array key 1 at /nix/store/ay71npxcw8gafabr4vaxsn6pkbdm5xmc-nextcloud-27.1.4/lib/private/AppFramework/Utility/ControllerMethodReflector.php#65","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"}}
^C
```

**Comment by joshtrichards** [comment] 2023-12-18 14:20
Duplicate of nextcloud/mail#9170

**Closed by joshtrichards** 2023-12-18 14:20 UTC
Labels: bug, 0. Needs triage
