### ISSUE TITLE
Share files/folders via multiple links

### ISSUE THREAD

**Issue by AND51** [nextcloud/server#8048] opened 2018-01-25 17:00 UTC
Hey,

this is my first contribution to Nextcloud, so I appreciate any feedback.

I would like to issue this **feature request about sharing something with multiple sharing-links**. Each link should be able to have its own expiration date and read/write/password/expiration rights.

This was already requested ibn #3243, but that issue is closed. @MorrisJobke pointed out that this is partly possible by sharing via e-mail. However, this does not cover this feature request perfectly. He also asked to create a separate ticket for that request – which is what I am doing hereby.

@MorrisJobke also asked to add this idea to #434, but that ticket is also closed with no obvious result.

I hope my activity is useful for you.

**Comment by MorrisJobke** [comment] 2018-01-25 23:35
cc @nextcloud/sharing @nextcloud/designers 

@jancborchardt we talked about this - I guess at the conf. 🤔

**Comment by rullzer** [comment] 2018-01-26 09:02
Yes we discussed this at the conf.

Basically from the sharing backend the limitation is pretty artificial. We would need some work there but it can be done.

However most of the work will go into the frontend (and making all the clients compatible!)

**Comment by AND51** [comment] 2018-01-26 11:02
Hey @MorrisJobke and @rullzer ,

thank you for your feedback. I didn't participiate in "the conf". Do you have a short summary for me and others?

Is there anything I can do to support this feature request, or can I only wait?

**Comment by MorrisJobke** [comment] 2018-01-26 11:25
I thought that we already have a ticket for this and @jancborchardt could link to it.

Let me sum it up:

The idea is to overhaul the sharing interface to not distinguish between user, remote, group, email and link shares anymore. It is basically only one section where you could add more share endpoints (like we have now for user, remote, email and group shares - they are all shown in one list). The link share would be only then an entry in this list and you could create multiple of them.

**Comment by MariusBluem** [comment] 2018-01-26 13:17
> I thought that we already have a ticket for this and @jancborchardt could link to it.

Did you mean: https://github.com/nextcloud/server/issues/5336

**Comment by MorrisJobke** [comment] 2018-01-26 13:30
> Did you mean: #5336

Yes.

**Comment by MorrisJobke** [comment] 2018-01-26 13:30
Closing as duplicate of #5336

**Closed by MorrisJobke** 2018-01-26 13:30 UTC
Labels: 0. Needs triage, enhancement, feature: sharing

**Comment by AND51** [comment] 2018-01-26 20:23
Thank you guys! #5336 sounds great!
