### ISSUE TITLE
Dark Theme | Black icons not visible in image viewer

### ISSUE THREAD

**Issue by lukasradek** [nextcloud/server#13667] opened 2019-01-18 16:05 UTC
### Steps to reproduce
1. Switch to dark theme
2. Open image in image viewer (click on image)
3. Look at the share, delete, download and close icons

### Expected behaviour
Icons should be white and therefore visible

### Actual behaviour
Icons are inverted (from their light theme white color to dark theme black color), but photos still have black bars around them. So black on black, can't be seen.

### Solution
Icons either can have white shadow, but it would make more sense jus to make them white again. No need to change it in dark theme.

Some further info was not relevant -> removed for readability.

**Nextcloud version:** (see Nextcloud admin page)
15.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh 15.0.0, web updated to 15.0.2

**Comment by sgofferj** [comment] 2019-02-03 10:49
Same as https://github.com/nextcloud/gallery/issues/483

**Comment by skjnldsv** [comment] 2019-04-30 10:35
Closing as duplicate of gallery and now we have https://github.com/nextcloud/viewer shipped with nc 16 :)

**Closed by skjnldsv** 2019-04-30 10:35 UTC
Labels: 0. Needs triage, bug
