### ISSUE TITLE
NC18: Sharing Photo-Galleries not working

### ISSUE THREAD

**Issue by janLo** [nextcloud/server#19019] opened 2020-01-20 16:23 UTC
In NC pre-18 it was possible to share a link from the gallery app. 

If I now share from the new Photos app I just get a File-Share-Link. Its not possible to get a gallery-view with this Link. Its also not possible to View the Images in the shared folder without downloading them.

The Issue can easily be reproduced with the demo instance by sharing the Photos folder from the Photos app. The link gives you a File-Listing where you can  only download the items.

**Comment by Lukas-Heiligenbrunner** [comment] 2020-01-29 07:42
a normal link (read-only) share of a folder including jpeg files should allow a preview of the pictures (or also videos) on click. 
In my case on click the files are downloaded instantely and no preview is possible. 
Has this fault something todo with this issue or is it only an operator fault of mine?

Also using NC18 here.

**Comment by neufeind** [comment] 2020-02-07 14:32
According to some search-results if should have been possible to reference the gallery-app (now photos) and append a share-ID? If so the constructed URL would look something like if I assume right?
https://example.com/apps/photos/s/WK4H7sNEkwNi43c
But that only triggers a redirect for me.

**Comment by skjnldsv** [comment] 2020-02-07 15:18
duplicate of nextcloud/photos#128

**Closed by skjnldsv** 2020-02-07 15:18 UTC
Labels: 0. Needs triage, bug
