### ISSUE TITLE
Provide an OS X profile for easier integration

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#2062] opened 2016-11-09 12:53 UTC
It would be nice to more easily integrate CalDAV and CardDAV into OS X. It seems there exists a profile that you can install and then you don't need to figure out all the needed URLs.

See https://posteo.de/hilfe/posteo-in-mac-os-x-einrichten for an example profile.

**Comment by MorrisJobke** [comment] 2016-11-09 12:53
Thanks to @benediktg for pointing this out :)

**Comment by MariusBluem** [comment] 2016-11-11 22:01
duplicate of https://github.com/nextcloud/server/issues/1434

**Closed by MariusBluem** 2016-11-11 22:01 UTC
Labels: enhancement, starter issue
