### ISSUE TITLE
"Updates"-section in apps overview

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/server#2729] opened 2016-12-16 19:28 UTC
This is a feature request.

Whenever there is an update for an installed app available there should be an additional section in the apps overview. In this section all apps should be shown that are updates available for.

When no updates for any app are available this section should not be shown.

![bildschirmfoto vom 2016-12-16 20 25 43](https://cloud.githubusercontent.com/assets/4741199/21275655/1ebff32c-c3ce-11e6-860b-d618d9ee4309.png)

Benefit: You can get a quick overview of the apps that may or may not have to be updated.

cc @jancborchardt

**Comment by MorrisJobke** [comment] 2016-12-16 22:51
Duplicate of #1236

**Closed by MorrisJobke** 2016-12-16 22:51 UTC
