### ISSUE TITLE
Image file stuck "Loading" after successfully downloaded

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#21514] opened 2020-06-21 11:05 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Download an image file from web interface (right click -> download)
2. After it's downloaded, it will be stuck "loading" (see picture)

### Actual behaviour
Refreshing the view or page is needed in order to fix this. The issue doesn't apply to non-image files.
![Screenshot_1](https://user-images.githubusercontent.com/36133540/85223003-c1d04a00-b3bf-11ea-9b43-f9a5bd8041f7.png)

### Server configuration
NC18.0.4snap

**Comment by szaimen** [comment] 2021-06-02 13:14
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 13:14 UTC
Labels: 0. Needs triage, bug
