### ISSUE TITLE
(Bulk) Move files to subfolder

### ISSUE THREAD

**Issue by NicolasGoeddel** [nextcloud/server#14761] opened 2019-03-20 10:09 UTC
### Steps to reproduce
1. Upload some files (100-300 MB) into a folder.
2. Create a subfolder.
3. Select all files and drag'n'drop them to the subfolder.

### Expected behaviour
The files should be moved within seconds and without problems.

### Actual behaviour
Some of the files were moved but always the last ones can not be moved because there are suddenly locked. Also moving requires a lot of I/O as if the files are copied instead of moved.

### Server configuration

**Operating system**: Ubuntu 16.04.5 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL 14.14

**PHP version:** PHP 7.0-fpm

**Nextcloud version:** 15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated many times from earlier versions.

**Where did you install Nextcloud from:** From the nextcloud site using the archive file.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - audioplayer: 2.6.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - music: 0.9.4
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/domain.de\/cloud",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "enable_certificate_management": true,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379"
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox Quantum 65.0.1 (64-Bit)

**Operating system:** Ubuntu 18.10

#### Web server error log
<details>
<summary>Web server error log</summary>
This log is way to big. Please specify what you are looking for and I can grep it for you.

```

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
This log is way to big. Please specify what you are looking for and I can grep it for you. Here you can see one attempt to move a file which could not be moved as bulk.

```
{"reqId":"3vnNsY...Z2P4BAhy3","level":3,"time":"2019-03-20T10:04:32+00:00","remoteAddr":"95.88.x.x","user":"user","app":"no app in context","method":"MOVE","url":"\/remote.php\/dav\/files\/user\/G%C3%B6ddel\/sister\/DSC_5408.MOV","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/7dd869b66e3a7241bfffc458786008a4\" is locked, existing lock on file: 2 shared locks","Code":0,"Trace":[{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":778,"function":"changeLock","class":"OC\\Lock\\MemcacheLockingProvider","type":"->","args":["files\/7dd869b66e3a7241bfffc458786008a4",2]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files\/lastname\/sister\/DSC_5408.MOV",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/lib\/private\/Files\/View.php","line":1970,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/lastname\/sister\/DSC_5408.MOV",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/lib\/private\/Files\/View.php","line":783,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/lastname\/sister\/DSC_5408.MOV",2,true]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":440,"function":"rename","class":"OC\\Files\\View","type":"->","args":["\/lastname\/sister\/DSC_5408.MOV","\/lastname\/sister\/2019-03-19\/DSC_5408.MOV"]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":158,"function":"moveInto","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["DSC_5408.MOV","files\/user\/lastname\/sister\/DSC_5408.MOV",{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":642,"function":"move","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/user\/lastname\/sister\/DSC_5408.MOV","files\/user\/lastname\/sister\/2019-03-19\/DSC_5408.MOV"]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.goeddel.net\/remote.php\/dav\/files\/user\/G%C3%B6ddel\/sister\/DSC_5408.MOV","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https:\/\/cloud.goeddel.net\/remote.php\/dav\/files\/user\/G%C3%B6ddel\/sister\/DSC_5408.MOV","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https:\/\/cloud.goeddel.net\/remote.php\/dav\/files\/user\/G%C3%B6ddel\/sister\/DSC_5408.MOV","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.goeddel.net\/remote.php\/dav\/files\/user\/G%C3%B6ddel\/sister\/DSC_5408.MOV","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/apps\/dav\/lib\/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/remote.php","line":163,"args":["\/home\/nextcloud\/www\/htdocs\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/home\/nextcloud\/www\/htdocs\/nextcloud\/lib\/private\/Lock\/MemcacheLockingProvider.php","Line":129,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
There is nothing relevant here.
```
</details>

**Comment by hcderaad** [comment] 2019-04-04 19:45
A (at least optically) similar issue occurred in my instance. 
Server version: 15.0.5.3

Log message:
`{"reqId":"s6eSOfiJOUAg4l2qBxCR","level":3,"time":"2019-04-02T15:25:38+00:00","remoteAddr":"213.125.16.42","user":"USERNAME","app":"no app in context","method":"DELETE","url":"/nextcloud/remote.php/dav/files/USERNAME/PROBLEMATICROOTDIR/SUBDIR","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files/3d31d9ddb9936ba691c112d62220e4e8\" is locked","Code":0,"Trace":[{"file":"WEBROOT/nextcloud/lib/private/Files/Storage/Common.php","line":778,"function":"changeLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files/3d31d9ddb9936ba691c112d62220e4e8",2]},{"file":"WEBROOT/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files/PROBLEMATICROOTDIR/Windows 10",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"WEBROOT/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/PROBLEMATICROOTDIR/Windows 10",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"WEBROOT/nextcloud/lib/private/Files/View.php","line":1970,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/PROBLEMATICROOTDIR/Windows 10",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"WEBROOT/nextcloud/lib/private/Files/View.php","line":1141,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["/PROBLEMATICROOTDIR/Windows 10",2]},{"file":"WEBROOT/nextcloud/lib/private/Files/View.php","line":347,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["rmdir","/PROBLEMATICROOTDIR/Windows 10",["delete"]]},{"file":"WEBROOT/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":312,"function":"rmdir","class":"OC\\Files\\View","type":"->","args":["/PROBLEMATICROOTDIR/Windows 10"]},{"file":"WEBROOT/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":[]},{"file":"WEBROOT/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":287,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files/USERNAME/PROBLEMATICROOTDIR/Windows 10"]},{"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://SERVERURI/remote.php/dav/files/USERNAME/PROBLEMATICROOTDIR/SUBDIR","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"WEBROOT/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpDelete"],[{"absoluteUrl":"https://SERVERURI/remote.php/dav/files/USERNAME/PROBLEMATICROOTDIR/SUBDIR","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"WEBROOT/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:DELETE",[{"absoluteUrl":"https://SERVERURI/remote.php/dav/files/USERNAME/PROBLEMATICROOTDIR/SUBDIR","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"WEBROOT/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://SERVERURI/remote.php/dav/files/USERNAME/PROBLEMATICROOTDIR/SUBDIR","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"WEBROOT/nextcloud/apps/dav/lib/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"WEBROOT/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"WEBROOT/nextcloud/remote.php","line":163,"args":["WEBROOT/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"WEBROOT/nextcloud/lib/private/Lock/DBLockingProvider.php","Line":271,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)","version":"15.0.5.3","id":"5ca65b3197d6a"}`

When moving several folders containing multiple files each from a recently extracted zip in the root of that folder to a subfolder (I had extracted the zip directly in the root folder instead of in a subfolder), one of the folders got "stuck". It disappeared in my Windows Explorer from the root folder, yet it was still visible in the web interface on its original space in the root folder.

I could delete files from the locked subfolder using the web interface, but not the folder itself. 

After searching the forum running the cli command I found: `sudo -u www-data php occ files:scan --all` was suggested.

Which I did, it ran without issues, yet didn't resolve the locking issue.

After approx 2 days (guessing here) the error message stopped disappearing and the folder appears to have been deleted from the web interface as well.
Could this be a versioning issue in combination with something locking a file/dir shortly after creation (i.e. clamav addon, of which I have no logs in nextcloud indicating that)?

As the issue has now disappeared I have no means of reconstructing the event other then the textual description provided in this comment. Hopefully this helps!

**Comment by NicolasGoeddel** [comment] 2019-06-05 16:24
This issue contains enough information. In fact there is a second user with a similar issue. Also nobody has asked for more information. This issue is not "stale"!

**Comment by kesselb** [comment] 2019-06-05 21:25
Thank you for your report :+1: 

Looks like a duplicate of #9001 to me.

**Closed by kesselb** 2019-06-05 21:25 UTC
Labels: 0. Needs triage, bug
