### ISSUE TITLE
[Bug]: DAV Propfind: Undefined variable $response

### ISSUE THREAD

**Issue by simonspa** [nextcloud/server#42575] opened 2024-01-04 08:31 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On NC 27.1.5, some code seems to be able to trigger an issue with DAV propfind:

```
{"reqId":"v1UAVvIC6fcqsJ6MXg1X","level":3,"time":"2024-01-04T08:35:53+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined variable $response at /var/www/nextcloud/lib/private/Files/Storage/DAV.php#305","userAgent":"--","version":"27.1.5.1","data":{"app":"PHP"},"id":"65966804c36da"}
```

Guessing from the periodicity in the logs this could be triggered by a background job and a federated share. The only federated shares I have run a NC 27.1.2 server on the other end.

I tried to understand the code on question (https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/DAV.php#L299) but I don't fully grasp it - there seem to be too many possibilities of reaching `return $response` without ever setting `$response` - this might be my PHP ignorance though.

This seems to be similar to https://github.com/nextcloud/server/pull/16808 but a different error condition.

### Steps to reproduce

1. Check logs
2. See error

### Expected behavior

No error in logs, or at least clear backttrace/logging of issue

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"v1UAVvIC6fcqsJ6MXg1X","level":3,"time":"2024-01-04T08:35:53+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined variable $response at /var/www/nextcloud/lib/private/Files/Storage/DAV.php#305","userAgent":"--","version":"27.1.5.1","data":{"app":"PHP"},"id":"65966c709f6d5"}
```

**Comment by solracsf** [comment] 2024-01-04 08:56
Duplicate of https://github.com/nextcloud/server/issues/11140 ?

**Comment by simonspa** [comment] 2024-01-04 09:00
Good question - I think it is related but not a duplicate. The linked issue refers to `public function hasUpdated` in [line 855](https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/DAV.php#L855) while this error emanates from `protected function propfind`.

Might still be related since the `hasUpdated` method calls `propfind` [here](https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/DAV.php#L813).

**Comment by solracsf** [comment] 2024-01-04 13:44
After looking at the code, what about:

```
		} else {
			$response = $cachedResponse;
++			return $response;
		}
--		return $response;
++		return false;
```
This would ensure `$response` is retunred either by the `try` block, or if the response is cached.
In other conditions, it would return `false` as the return of the function states.

**Comment by alexeyvolkoff** [comment] 2024-06-25 15:31
Hi everyone,
am I facing the same bug? I'm trying to mount an external WebDAV storage

Undefined variable $response at /var/www/html/lib/private/Files/Storage/DAV.php#305
{"reqId":"3rtm1jUw7HaU4BCTKjhA","level":3,"time":"2024-06-25T15:11:45+00:00","remoteAddr":"193.77.124.122","user":"admin","app":"PHP","method":"PUT","url":"/apps/files_external/userstorages/2","message":"Undefined variable $response at /var/www/html/lib/private/Files/Storage/DAV.php#305","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36","version":"29.0.2.2","data":{"app":"PHP"},"id":"667ae027a81ca"}

**Comment by alexeyvolkoff** [comment] 2024-06-25 16:44
here is the response I send to propfind request:
propfind response "<?xml version=\"1.0\" encoding=UTF-8?>\n<D:multistatus xmlns:D=\"DAV:\">\n<D:response>\n<D:href>/</D:href>\n<D:propstat>\n<D:prop>\n<D:getlastmodified>Tue, 25 Jun 2024 16:34:22 GMT</D:getlastmodified>\n<D:getcontenttype>httpd/unix-directory</D:getcontenttype>\n<D:resourcetype>\n<D:collection/>\n</D:resourcetype>\n<D:getetag>\"f48ec06c4f93001e27543ee0abd65b42\"</D:getetag>\n<D:quota-available-bytes>5160385028845206400</D:quota-available-bytes>\n</D:prop>\n<D:status>HTTP/1.1 200 OK</D:status>\n</D:propstat>\n</D:response>\n</D:multistatus>\n"

Looks OK, but DAV client (lib/private/Files/Storage/DAV.php#305) reports undefined response

**Comment by susnux** [comment] 2024-08-15 01:31
If you experience this bug, please enable debug log level. There should be a log entry with debug level and `app = files_external` directly before this error log message. We need that message to proceed here.

**Comment by skjnldsv** [comment] 2024-11-08 09:06
> Duplicate of [#11140](https://github.com/nextcloud/server/issues/11140) ?

Yes, same errored line

**Closed by skjnldsv** 2024-11-08 09:06 UTC
Labels: bug, feature: dav, 0. Needs triage, 29-feedback
