### ISSUE TITLE
Webdav latest stable build

### ISSUE THREAD

**Issue by ddanielww** [nextcloud/server#3672] opened 2017-03-01 20:58 UTC
Sabre\DAV\Exception: HTTP/1.1 500 No subsystem set a valid HTTP status code. Something must have interrupted the request without providing further detail.

Is this a known issue with webdav and windows as the client ?

Read online upgrading from php 7 to php 7.1 version was a possible fix ?

**Comment by benediktg** [comment] 2017-03-01 23:59
You might want to have a look at #2887 and #3370. 😉

**Comment by nickvergessen** [comment] 2017-03-06 13:12
Or duplicate of https://github.com/nextcloud/server/issues/3628

**Closed by nickvergessen** 2017-03-06 13:12 UTC

**Comment by ddanielww** [comment] 2017-03-06 18:36
This issue has not really been fixed ? Not sure why it worked in nextcloud 10 but not 11.

Can't nextcloud fix this issue in a new patch ?

**Comment by nickvergessen** [comment] 2017-03-07 14:55
The issue is not fixed intentionally yet.
But there are 3 related issues open, no need to have a forth one.
