### ISSUE TITLE
Unsyncing a directory on one PC sometimes deletes it on server and then other PCs

### ISSUE THREAD

**Issue by sealne** [nextcloud/server#5164] opened 2017-05-30 06:36 UTC
Sometimes when un-checking the sync box for a directory in the client on one PC the directory is removed on the server and then from all devices

### Steps to reproduce
1. On one PC untick a directory to be synced
2. Check in web interface or on another PC

### Expected behaviour
The directory should only be removed on the specific PC but still available on the server and any other PC that had it synced

### Actual behaviour
Sometimes the folder is removed on the server and all PCs

### Server configuration

**Operating system**: Linux (Ubuntu xenial)

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.1.5

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since early ownCloud

**Where did you install Nextcloud from:** update

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.3
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - rainloop: 4.28.1
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - apporder
  - direct_menu
  - encryption
  - files_external
  - nextant
  - ocr
  - richdocuments
  - spreed
  - spreedme
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/somewhere\/owncloud-data",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "installed": true,
        "instanceid": "5076a9c7a58d9",
        "version": "12.0.0.29",
        "forcessl": false,
        "theme": "",
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "filelocking.enabled": "true",
        "maintenance": false,
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/example.com"
    }
}
</details>

**Are you using external storage, if yes which one:** no.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox

**Operating system:** Linux (Neon user)

#### Web server error log
<details>
<summary>Web server error log</summary>
2017/05/30 07:25:26 [error] 19025#19025: *82761 open() "/somewhere/nextcloud/favicon.ico" failed (2: No such file or directory), client: 179.43.155.163, server: example.com, request: "GET /favicon.ico HTTP/1.1", host: "example.com"
2017/05/30 07:25:26 [error] 19025#19025: *82761 open() "/somewhere/nextcloud/favicon.ico" failed (2: No such file or directory), client: 179.43.155.163, server: example.com, request: "GET /favicon.ico HTTP/1.1", host: "example.com"

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Too much personal info to sanitise

</details>

**Comment by nickvergessen** [comment] 2017-05-31 09:25
Hmm, there is not enough info to reproduce the issue.
Can you try this again and see if at that time something shows up in your log file?

**Comment by patschi** [comment] 2017-05-31 09:35
Could this be possibily more related to the client?
With which clients (incl. versions) you have encountered this misbehavior?

**Comment by MorrisJobke** [comment] 2017-10-30 16:05
> Could this be possibily more related to the client?

Seems to be related to the client and we can't reproduce. I will close this here and please reopen with more details in the client repo once it happens again. Thanks

**Closed by MorrisJobke** 2017-10-30 16:05 UTC
Labels: needs info
