### ISSUE TITLE
Redirecting bug since 15.0.2

### ISSUE THREAD

**Issue by mrzapp** [nextcloud/server#13713] opened 2019-01-21 11:06 UTC
Whenever a redirect happens, like from the `/apps/` to the `/apps/files/` path, NextCloud now redirects using the server provided hostname and port instead of the one requested by the client.

For instance, if running via Docker on `localhost:8000` and using a proxy pass with `cloud.example.com`, the address `cloud.example.com/apps/` will redirect to `localhost:8000/apps/files/`.

This happens with the `/` to `/login` redirect as well, so this bug completely prevents access to the instance from the web interface, unless you manually correct the URL afterwards.

Also discussed here: https://help.nextcloud.com/t/nextcloud-15-redirect-to-local-ip/45352

**Comment by mrzapp** [comment] 2019-01-21 11:10
Related to #13710

**Comment by RandomMetalhead** [comment] 2019-01-21 18:43
Same problem and same setup:
Apache Proxy -> Docker -> Nexcloud and always redirecting to https://127.0.0.1:8080/login. With 15.0 it worked fine, update to 15.0.2 broke

**Comment by danielkesselberg** [comment] 2019-01-21 18:44
Does this help? https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by RandomMetalhead** [comment] 2019-01-21 18:54
Provided links did not help.
What helped is changing:
`'overwrite.cli.url' => 'XXX',`
to
```
'overwritehost' => 'XXX',
'overwriteprotocol' => 'https',
```

It seems for me 'overwrite.cli.url' in config.php is broken

**Comment by mrzapp** [comment] 2019-01-21 18:59
Yep, @RandomMetalhead's solution works

**Comment by danielkesselberg** [comment] 2019-01-21 19:33
Great :tada: 

![image](https://user-images.githubusercontent.com/3902676/51494147-e6ce2100-1db7-11e9-9ee2-105a87ee5253.png)

> Provided links did not help.

I guess we could improve the documentation here. It's not obvious that the **bold** text are configuration parameters.

@RandomMetalhead you also need `overwrite.cli.url` (https://github.com/nextcloud/server/blob/stable15/config/config.sample.php#L477-L485)

**Comment by RandomMetalhead** [comment] 2019-01-21 20:03
The main issue was, that in 15.0.0 only having 'overwrite.cli.url' was enough. It seems, that for 15.0.2 'overwritehost' and 'overwriteprotocol' is necessary. At least in docker version with Apache-Proxy. I have added 'overwrite.cli.url', too. So my config looks like this now and is working perfectly:

`  'overwritehost' => 'XXX.de',
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'https://XXX.de',`

**Comment by danielkesselberg** [comment] 2019-01-21 20:19
> The main issue was, that in 15.0.0 only having 'overwrite.cli.url' and 'overwriteprotocol' was sufficient for Nextcloud. It seems, that for 15.0.2 'overwritehost' is necessary. 

Thank you for pointing this out :+1: 

@MorrisJobke @rullzer @J0WI they were many reports within the last days about this. I suppose this is related to https://github.com/nextcloud/server/pull/13116 because the docker network is not trusted by default. In this case `HTTP_FORWARDED_HOST` is not longer trusted. What do you suggest? Is it possible to add this for the official docker image?

**Comment by danielkesselberg** [comment] 2019-01-21 20:43
CIDR is possible for `trusted_network` since nextcloud 15. Something like `172.0.0.0/8` as trusted proxy would work (not sure if docker uses 172.x all the time).

@kyrofa @enoch85 (not sure if snap or vm is running into the same. just in case)

**Comment by enoch85** [comment] 2019-01-21 21:03
Thanks for the heads up @danielkesselberg Nothing reported, and nothing I've experienced myself.

**Comment by J0WI** [comment] 2019-01-22 15:51
`172.0.0.0/8` would be a bad idea, only `172.16.0.0/12` is private. If we trust them by default, we should probably trust all RFC 1918 (and RFC 4193?) networks?
However, you can use any other IP for Docker, so I think we need nextcloud/docker#527 anyway.

**Comment by neeral85** [comment] 2019-01-23 09:41
I'm running  https://www.techandme.se/nextcloud-vm/

my ip is 172.18.1.10 and 
'overwritehost' => 'XXX.de', 'overwriteprotocol' => 'https', 'overwrite.cli.url' => 'https://XXX.de',
was not working for me.

**Comment by enoch85** [comment] 2019-01-23 11:32
@neeral85 So you have issues on the Nextcloud VM as described in this issue?

**Comment by neeral85** [comment] 2019-01-23 12:49
actually only lockout-link and webdav-link are using local IP within the url. everything else works fine.

**Comment by J0WI** [comment] 2019-02-10 15:26
We have many reports like this (likely duplicates):
#8244 (no regression of 15.0.2)
#14132
#13450
#13310 
#13710
#13700
https://github.com/nextcloud/docker/pull/644
https://github.com/nextcloud/docker/pull/527
https://github.com/nextcloud/docker/issues/635
https://github.com/nextcloud/docker/issues/577
https://github.com/nextcloud/docker/issues/528
https://github.com/nextcloud/docker/issues/628

We really need to fix this for our Docker setup.
@danielkesselberg is this something we can expect to be fixed here or should we investigate in the docker config/documentation? Should this be fixed in the configuration of the proxies, NextCloud or webserver?

**Comment by danielkesselberg** [comment] 2019-02-10 16:07
Looks like many people do not  set `trusted_proxies`. I know so far:

- Nginx and `truested_proxies`: should work out of the box (https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/ host + proto are set for each forwarded request)
- Apache2 and `truested_proxies`: you need overwriteprotocol (https://httpd.apache.org/docs/current/mod/mod_proxy.html#request-bodies apache2 does not set proto as header).

If you add `trusted_proxies` as env to docker images and set a sensible default (for nextcloud 15 you can whiteliste the whole docker default network, not possible for < nextcloud 15) the situation should relax. Some hint in the readme may help: "you need to tell nextcloud that it runs behind a reverse proxy."

 Let's :ping_pong: @MorrisJobke @rullzer they will know what to do ;-)

**Comment by nesnera** [comment] 2019-02-16 09:29
NC 15.0.4
For only "Log out" menu entry is necessary to set ‘overwritehost’ config.php parameter. All other are correct.
Have a look at attached picture.
![nc_wrong_logout_url](https://user-images.githubusercontent.com/1737463/52897508-a9ea2400-31d5-11e9-9fee-c99fa5872699.png)

**Comment by jmrapin** [comment] 2019-03-26 05:09
Hi All,

New to NC (currently using v15.0.5). I am having the same issue using a reverse proxy as nesnera above. All my links are rewritten properly when setting the overwrite values (overwritehost, overwriteprotocol, ...) in the config file except the logout link which, in my case. does not use the correct protocol (HTTP instead of HTTPS).
Looks like the issues were dismissed as being a duplicate of another bug report, but I disagree (at least for nesnera above). So I did some digging and found out that in file:

user.php (/nextcloud/lib/private/legacy) line 272:
$logoutUrl = $urlGenerator->linkToRouteAbsolute( 
{etc.,..}

should be changed to 
$logoutUrl = $urlGenerator->linkToRoute( 
{etc.,..}

Since all the links in the navigationManager.php use linkToRoute and display properly. So now my logout link has the proper value and works: https://domain.com/index.php/logout?...

Can someone advise what is the reason for the linkToRouteAbsolute vs linkToRoute  in user.php line 272?
If not, can this be fixed please?

Thanks guys for the amazing cloud software.

**Comment by kesselb** [comment] 2019-04-02 17:25
If you run nextcloud behind a reverse proxy usually some headers (like X-Forwarded-For) are present. You should see a setup warning (nextcloud 16) for such cases: https://github.com/nextcloud/server/pull/14261

**Comment by MorrisJobke** [comment] 2019-05-07 20:59
Fix is in #15430

**Closed** 2019-05-08 17:36 UTC
Labels: 15-feedback, 3. to review, bug

**Comment by Darkless012** [comment] 2024-01-29 20:46
> The main issue was, that in 15.0.0 only having 'overwrite.cli.url' and 'overwriteprotocol' was sufficient for Nextcloud. It seems, that for 15.0.2 'overwritehost' is necessary. At least in docker version with Apache-Proxy. I have readded 'overwrite.cli.url', too. So my config looks like this now and is working perfectly:
> 
> ` 'overwritehost' => 'XXX.de', 'overwriteprotocol' => 'https', 'overwrite.cli.url' => 'https://XXX.de',`

I'm running Nextcloud 25 and the login issue redirect was appearing. 
Fixed by adding overwritehost and overwriteprotocol into config.php

Shame that config is JSON, because you can't use simple Ansible to manage line in file.

**Comment by a214218** [comment] 2024-10-24 08:06
hi. I'm just starting to learn Linux. I have NextCloud 30.0.1 set up at home on Debian 12. I am also being redirected to a local IP... I use DDNS on the router for access. 
made the following changes:
'overwritehost' => 'XXX.de', 'overwriteprotocol' => 'https', 'overwrite.cli.url' => 'https://XXX.de ',
the error persists (((

**Comment by elclanrs** [comment] 2024-12-13 09:17
Experiencing the same issue with version 30. Tried setting all those settings mentioned above but no luck. This makes it impossible to login in Android because when you try to grant access to the device it goes to 127.0.0.1/login/flow which produces an ERR_CONNECTION_REFUSED error
