### ISSUE TITLE
Show group restriction in Apps view

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/server#33201] opened 2022-07-11 14:48 UTC
Please allow viewing & editing of group restrictions for apps in the list view. It's tedious to open the details view for every app, just to see this information. 
Eg. when viewing https://example.tld/settings/apps ; settings/apps/enabled ; settings/apps/disabled etc.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

It frustrates not being able to view all group restrictions at once when looking for outdated ones.

**Describe the solution you'd like**

Add a column which shows group restrictions, if they're enabled, and directly allows editing them as well. 

**Describe alternatives you've considered**

A column that only shows existing group restrictions and does not allow modifying them.

**Additional context**

PS: Just noticed, that the structure is made up of divs. Any specific reason for not using table, tr, td etc.? *(I'm on NC 22.2.9; in case it's changed already in NC23, or NC24)*

**Comment by joshtrichards** [comment] 2023-09-03 11:18
Duplicate of #30503

Hi @EngelPika32 - Let's consolidate tracking of this enhancement idea there. Subscribe to that issue and/or give it a :+1:.

**Closed by joshtrichards** 2023-09-03 11:18 UTC
Labels: enhancement, 0. Needs triage, feature: apps management
