### ISSUE TITLE
Sharing Files error version 14.0.3 : Can not read property 'meta' of undefined

### ISSUE THREAD

**Issue by tuananh051693** [nextcloud/server#12380] opened 2018-11-09 14:10 UTC
Nextcloud version 14.0.3, when I search for any user in Sharing, has an error: Can not read property 'meta' of undefined. Can anybody help me, thanks!
<img width="1264" alt="screen shot 2018-11-09 at 9 05 32 pm" src="https://user-images.githubusercontent.com/7877646/48267038-c1da3b00-e463-11e8-80a1-1c363e046969.png">
<img width="815" alt="screen shot 2018-11-09 at 9 07 38 pm" src="https://user-images.githubusercontent.com/7877646/48267039-c272d180-e463-11e8-82c3-3a0aed1bf5db.png">

**Comment by skjnldsv** [comment] 2019-10-30 20:54
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-10-30 20:54 UTC
Labels: 0. Needs triage, bug, design
