### ISSUE TITLE
VCF export contains VERSION:3.0 multiple times

### ISSUE THREAD

**Issue by nblock** [nextcloud/server#187] opened 2016-06-21 11:28 UTC
### Steps to reproduce
1. Open contacts app
2. Export VCF
### Expected behaviour

Each `VCARD` block should contain the `VERSION:3.0` string once.
### Actual behaviour

Found a few `VCARD` blocks that look as follows:

```
BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.4.7//EN
FN:A Name
N:Name;A;;;
TEL:123123123123
TEL:345453543454
UID:13b765a1-302c-4edc-949f-40d99b07c5db
REV:2015-12-13T11:54:36+00:00
END:VCARD
```

See https://tools.ietf.org/html/rfc6350#section-6.7.9
### Server configuration

**Operating system**: Arch Linux

**Web server:** Nginx

**Database:** SQLite

**PHP version:** 7.0.7

**Nextcloud version:** 9.0.50

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated, starting from ownCloud 3.0

**Where did you install Nextcloud from:** archive

**Signing status (Nextcloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notes: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_texteditor
  - user_external
  - user_ldap
```

**Are you using encryption:** no

**Comment by nblock** [comment] 2016-06-21 11:30
cc @evert

**Comment by evert** [comment] 2016-06-21 13:45
Please don't include me in your tickets unless you have a specific question.

**Comment by nblock** [comment] 2016-06-21 14:34
> Please don't include me in your tickets unless you have a specific question.
No problem. I won't do so next time. Hint: it was requested by @BernhardPosselt in IRC.

**Comment by BernhardPosselt** [comment] 2016-06-21 14:54
@evert The specific question was why it's possible to add more than one version attrbitute (looks like its possible from the vcard ouptut)

**Comment by MorrisJobke** [comment] 2016-06-21 15:26
I can't reproduce this. The export works fine here:

```
$ cat 1bb4bc18-0414-4095-a6ba-49dc6f8bf8b2.vcf 
BEGIN:VCARD
VERSION:3.0
FN:A Name
UID:1bb4bc18-0414-4095-a6ba-49dc6f8bf8b2
TEL;TYPE=HOME\,VOICE:0123456789
TEL;TYPE=WORK\,VOICE:012345678
EMAIL;TYPE=WORK:hey@example.org
END:VCARD
```

Could you provide the database entry for this contact? How was the contact added? Was it created via web UI? Or did you import it?

**Comment by evert** [comment] 2016-06-21 16:00
> @evert The specific question was why it's possible to add more than one version attrbitute (looks like its possible from the vcard ouptut)

Thanks, I can work with that =)

So.. vobject would allow you to call $vcard->add('VERSION','3.0') more than once, and you would end up with multiple `VERSION` properties.

However, nothing in the vobject source does this automatically (as far as I know). I do believe therefore that the bug is *outside* of vobject, so either in nextcloud code or generated by a carddav client.

**Comment by nblock** [comment] 2016-06-21 17:32
> Could you provide the database entry for this contact?
```
SELECT * FROM oc_cards WHERE id=384;
384|4|BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.4.7//EN
FN:Name A
N:A;Name;;;
TEL:12345677
TEL:123341351
UID:88b765a1-302c-4edc-949f-40d99b07b5db
REV:2015-12-13T11:54:36+00:00
END:VCARD
|88b765a1-302c-4edc-949f-40d99b07b5db.vcf|1466265077|7b6b9f9ea14f17f477c19c0d50fc9ab1|322
```
> How was the contact added? Was it created via web UI? Or did you import it?
I am not 100% sure but I think it got imported via the web UI.

**Comment by BernhardPosselt** [comment] 2016-06-21 17:34
@evert ah I see. wouldn't it make sense to make it "more typesafe" :)? I'm not super familiar with the spec but I think its a limited vocabulary right?

e.g. $vcard->setVersion('5.0') instead of $vcard->add('version', '5.0')

**Comment by evert** [comment] 2016-06-21 17:45
It's true that we could create separate functions for some properties that help make it easier to not make mistakes, but this already works:

    $vcard->VERSION = '4.0';

Calling it twice overrides the first. It doesn't prevent you from setting something invalid though:

    $vcard->VERSION = 'foo';

And yea doing it with `add()` twice allows you to create syntactically invalid data.

I think you should look at the lib a bit more as the DOM. Even with the DOM you can generate HTML that's not valid, but that's partially because it's a generic API that helps you deal with the underlying xml-like structure. So you can totally add a second `<title>` or a `<td>` outside of a `<tr>`, even if those things are technically invalid.

**Comment by BernhardPosselt** [comment] 2016-06-21 17:52
Ok, so I think this should probably be done using properties then. I mean the root cause is something different ofc which should be fixed, but the API could have avoided it.

As for the DOM argument: I think the main difference here is that the tripple versions actually break clients whereas no browser cares if you feed it invalid markup :)

**Comment by evert** [comment] 2016-06-21 17:59
My point is not about correctness, it's the fact that this is an API for the underlying data structure, not the higher level syntax. I agree that more hand-holding could be added in some situations to make it harder to produce invalid data, but it would be somewhat important to do this based on some empirical evidence. If a mistake is common, it might make sense to add an API.

In this particular case though, I doubt that the error even originated on in a PHP script using sabre/vobject. 

But if I'm wrong, I'd be happy to have a discussion about how we can make it harder to make that mistake.

**Comment by evert** [comment] 2016-06-21 18:01
Plus that there is a `validate()` function that *is* specifically used to do a deep check for correctness, which we will start calling by default in sabre/dav from 3.2 onwards. More details here:

http://sabre.io/blog/2016/validation-changes/

**Comment by BernhardPosselt** [comment] 2016-06-21 18:04
Oh, great :)

The validate stuff will probably solve this issue.

**Comment by MorrisJobke** [comment] 2017-01-24 21:03
@rullzer Didn't we add some validation into the code recently? Could you check that one out?

**Comment by jakobsack** [comment] 2017-08-22 11:56
OK, I just investigated into the issue:
a) If you create/edit a contact the vcard is created just fine
b) if you upload a vcard with just one `VERSION` field it just works fine
c) If you upload a vcard with several `VERSION` fields it fails silently
d) Bad entries that are in the database will be exported without an validation.

So from my point of view no bugs here.

**Closed by jakobsack** 2017-08-22 11:56 UTC
Labels: bug, feature: dav, low
