### ISSUE TITLE
Mention notifications do not open the document on click

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/server#40483] opened 2023-09-13 06:39 UTC
### Steps to reproduce
1.User A mentions User B in a text docment
2.User B sees the notifications and clicks on it

### Expected behaviour
User B is redirected to that text document

### Actual behaviour
Nothing happens

### Server configuration
Company instance

**Comment by nickvergessen** [comment] 2023-09-18 15:02
Moving to server because it's a problem of the comments app

**Comment by nickvergessen** [comment] 2023-09-18 15:03
But actually it should work:
https://github.com/nextcloud/server/blob/master/apps/comments/lib/Notification/Notifier.php#L150-L153

**Comment by nextcloud-command** [comment] 2024-03-03 00:15
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by marcelklehr** [comment] 2024-05-06 10:45
Can not reproduce with latest 28

**Closed by marcelklehr** 2024-05-06 10:45 UTC
Labels: bug, 1. to develop, feature: comments, feature: activity and notification, 28-feedback
