### ISSUE TITLE
adressbook gets deleted automatically

### ISSUE THREAD

**Issue by Jotager** [nextcloud/server#17794] opened 2019-11-04 00:59 UTC
Alright so ive never reported anything on here so this report might look like an absolute mess
Basically i got a friend of mine to set up nextcloud for me and used it to store my contacts. This worked for a bit. Afterwards the whole adressbook isnt visible anymore. Creating a new one works until i refresh the window. After that its gone
Same problem in other browsers.

The contacts are still working on my phone where they are synced using carddav 
My friend was able to extract the adressbook from the server but exactly 50% of these contacts are corrupted.

below i tried my best filling out the requested information

### Steps to reproduce
1.  Create a new adress book
2. add contacts 
3. reload page

### Expected behaviour
Contacts should not be deleted

### Actual behaviour
after reloading all contacts and adressbooks are deleted

### Server configuration

**Ubuntu 18.04**:

**Web server: dont know, friend set it up**

**Database: dont know, friend set it up**

**PHP version: dont know, friend set it up**

**Nextcloud version: Nextcloud 17.0.0** 

**Updated from an older Nextcloud/ownCloud or fresh install: updated after switching to beta**

**Where did you install Nextcloud from: dont know, friend set it up**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>

Accessibility
1.3.0
Official
Activity
2.10.1
Official
Antivirus for files
2.2.0
Brute-force settings
1.4.0
Official
Calendar
1.7.1
Official
Collaborative tags
1.7.0
Official
Comments
1.7.0
Official
Contacts
3.1.6
Official
Deleted files
1.7.0
Official
Federation
1.7.0
Official
File sharing
1.9.0
Official
First run wizard
2.6.0
Official
Gallery
18.4.0
Official
Log Reader
2.2.0
Official
Monitoring
1.7.0
Official
Nextcloud announcements
1.6.0
Official
Notifications
2.5.0
Official
Password policy
1.7.0
Official
PDF viewer
1.6.0
Official
Privacy
1.1.0
Official
Quick notes
0.1.10
Recommendations
0.5.0
Official
Right click
0.15.1
Official
Share by mail
1.7.0
Official
Support
1.0.1
Official
Text
1.1.0
Official
Theming
1.8.0
Official
Update notification
1.7.0
Official
Usage survey
1.5.0
Official
Versions
1.10.0
Official
Video player
1.6.0
Official
Viewer 
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
dont know how to do that
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
no idea how to do that
```
</details>

### Client configuration
**Firefox Nightly**

**Operating system: Windows 10**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment] 2020-10-03 10:00
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-10-03 10:00 UTC
Labels: 0. Needs triage, bug
