### ISSUE TITLE
Files uploaded by WEBDAV are 0 sized in DB

### ISSUE THREAD

**Issue by TorinKR** [nextcloud/server#21414] opened 2020-06-15 13:12 UTC
Nextcloud version : 19.0.0
Operating system and version: UBUNTU 18.04.4 LTS (Bionic Beaver)
Apache: 2.4.29
PHP version: 7.2.24

The issue you are facing:

We used to use webdav client (Raidrive, native Windows) to access files on nextcloud trough drive Letter (eg. Z:). We have updated from 18.0.5 to 19.0.0 and problems occures. All files copied via connected disk drive are 0 size. The 0 appears although in webinterface.
I have opened oc_filecache table and there is also 0 for files copied via webdav. The size was not updated. On nextcloud physical storage the size of files are ok and also the content is ok. The problem probably is in updating of record in oc_filecache if webdav interface is used.
Web interface does not have this bug. There is all ok.

Is there any solution to solve size updating if webdav is used for copying files to nextcloud?
Where is the place in source code to do any change?

Is this the first time you’ve seen this error?: Yes

Steps to replicate it:

Run WebDAV client and create connection to NC instance
Copy some files to NC
Files have zero size, the 0 is in also in oc_filecache
The physical storage show the proper size of files and content is OK
The output of your Nextcloud log in Admin > Logging:
Nothing relevant. Also any errors if log is recreated.

The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!):
Nothing relevant, changes weren’t changed before and after update.

The output of your Apache/nginx/system log in /var/log/____:
Nothing relevant. The webdav properly copies files to server, but after that the oc_filecache is not properly updated.

Any solution?

/ I copied the post from the user forum because the matter is very important to me also, I have the same problem as the author of the post in the forum. /

**Comment by SilentMiner2** [comment] 2020-06-16 12:58
Yes we have noticed the same issue happening with all webdav clients. If you re-open the file again it corrupts it and the file is totally empty.

**Comment by TorinKR** [comment] 2020-06-16 19:30
Is there hope that there will be some improved version soon ... :)

**Comment by barzog** [comment] 2020-06-17 09:26
Dup of https://github.com/nextcloud/server/issues/21315

**Comment by Dragon988** [comment] 2020-06-17 15:49
Is there a PR I can test that fixes this bug?

**Comment by kesselb** [comment] 2020-07-11 12:48
Closing as duplicate of #21315

**Closed by kesselb** 2020-07-11 12:48 UTC
Labels: 0. Needs triage, bug
