### ISSUE TITLE
[Bug]: Two-Factor TOTP Provider not found / install not possible

### ISSUE THREAD

**Issue by haiopaii** [nextcloud/server#32590] opened 2022-05-25 10:07 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Two-Factor TOTP Provider App is not listed in Admin -> Apps and installation via CLI is not possible
Error: Could not download app twofactor_totp

### Steps to reproduce

1. occ app:install twofactor_totp
2. or Admin -> Apps
3.

### Expected behavior

Installation of Two-Factor TOTP Provider 

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "activity_expire_days": 30,
        "allow_local_remote_servers": true,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "default_phone_region": "DE",
        "default_language": "de",
        "default_locale": "de_DE",
        "defaultapp": "files,dashboard",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": "104857600",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "profile.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 1
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Freigaben",
        "sharing.enable_share_accept": false,
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "remember_login_cookie_lifetime": "",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": false,
        "upgrade.disable-web": true,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "SLD_ADMIN"
        ],
        "app_install_overwrite": [
            "documentserver_community"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - breezedark: 24.0.1
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - documentserver_community: 0.1.12
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - groupfolders: 12.0.0
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - onlyoffice: 7.3.4
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_email: 2.4.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - welcome: 1.0.1
  - workflowengine: 2.6.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard: 2.13.0
  - integration_dropbox: 1.0.4
  - ransomware_protection: 1.13.0
  - side_menu: 2.3.5
  - survey_client: 1.12.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"mkhxm7WUU7fiCHmZenuO","level":2,"time":"2022-05-07T09:54:10+00:00","remoteAddr":"88.152.129.99","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0","version":""}
{"reqId":"mkhxm7WUU7fiCHmZenuO","level":2,"time":"2022-05-07T09:54:10+00:00","remoteAddr":"88.152.129.99","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0","version":""}
{"reqId":"9vuyFUdkJgLnAgqUHWhs","level":2,"time":"2022-05-07T09:54:14+00:00","remoteAddr":"65.154.226.171","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.71 Safari/537.36","version":""}
{"reqId":"9vuyFUdkJgLnAgqUHWhs","level":2,"time":"2022-05-07T09:54:14+00:00","remoteAddr":"65.154.226.171","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.71 Safari/537.36","version":""}
{"reqId":"Vjksk7WiHuyLC3nCXJpi","level":2,"time":"2022-05-07T09:54:47+00:00","remoteAddr":"167.248.133.46","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"--","version":""}
{"reqId":"Vjksk7WiHuyLC3nCXJpi","level":2,"time":"2022-05-07T09:54:47+00:00","remoteAddr":"167.248.133.46","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"--","version":""}
{"reqId":"0QCfMkPYcReTz9jKOV6A","level":2,"time":"2022-05-07T09:54:47+00:00","remoteAddr":"167.248.133.46","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)","version":""}
{"reqId":"0QCfMkPYcReTz9jKOV6A","level":2,"time":"2022-05-07T09:54:47+00:00","remoteAddr":"167.248.133.46","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)","version":""}
{"reqId":"U7yb3evX8BiM0lwgXXAx","level":2,"time":"2022-05-07T09:54:47+00:00","remoteAddr":"167.248.133.46","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)","version":""}
{"reqId":"U7yb3evX8BiM0lwgXXAx","level":2,"time":"2022-05-07T09:54:47+00:00","remoteAddr":"167.248.133.46","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)","version":""}
{"reqId":"wR3DEq0cRFVDPn3ecXc3","level":3,"time":"2022-05-07T10:18:10+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"mkdir(): Permission denied at /var/www/nextcloud/lib/private/Setup.php#307","userAgent":"--","version":"","exception":{"Exception":"Error","Message":"mkdir(): Permission denied at /var/www/nextcloud/lib/private/Setup.php#307","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Setup.php","line":307,"function":"mkdir"},{"file":"/var/www/nextcloud/core/Command/Maintenance/Install.php","line":108,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Maintenance\\Install","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/Console/Application.php","line":211,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/console.php","line":99,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/occ","line":11,"args":["/var/www/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
```

**Comment by 0bliss** [comment] 2022-05-29 04:18
I also have experienced this issue.. Is there a known fix?

**Comment by 4001982248998** [comment] 2022-06-02 12:18
I too had this issue. Manually copied the app to the filesystem, and it showed up, but could not activate. But at least it showed an error message: It's not supported for PHP version 8.1.

You can downgrade PHP or try to manually add PHP8.1 “support” to the app by editing a file (not recommended of course).

I wish that the app was visible even with an unsupported PHP version so I know what the issue is. On the other hand, this would clutter the view with old apps.

**Comment by 0bliss** [comment] 2022-06-02 15:36
https://github.com/nextcloud/twofactor_totp/issues/1192 There's a thread open here, I guess it's being worked on. Does it work find with PHP 8? I'm on 8.1

**Comment by eugef66** [comment] 2022-06-07 17:10
@0bliss I found a workaround which works for me and makes TOTP available on NC24 on PHP8.1
I downloaded latest version of TOTP from Nextcloud Store https://apps.nextcloud.com/apps/twofactor_totp and unpacked into /apps folder in my Nextcloud installation folder (e.g. /var/www/nextcloud/apps/). 

Then all you need to do is open **info.xml** file (e.g. /var/www/nextcloud/apps/twofactor_totp/appinfo/info.xml) file and update max-version to **max-version="8.1"**

 TOTP app appeared in my App and is working like a charm

 
![image](https://user-images.githubusercontent.com/11634504/172441949-2ba64122-4c4c-4cd2-b1da-d86c6171f767.png)

![image](https://user-images.githubusercontent.com/11634504/172441974-97665dc9-7379-46e9-8ef1-67a6b7a03d52.png)

**Comment by 0bliss** [comment] 2022-06-07 17:34
Thank you @eugef66 it certainly did work like a charm!

**Comment by mmccollum2** [comment] 2022-06-10 16:58
Thank you @eugef66 this fix worked perfectly. Looks like that app just hasn't been updated with newer versions of PHP even though it works fine. have a good day!!

**Comment by math-GH** [comment] 2022-08-20 17:46
I use NextCloud 24.0.4 on a PHP 7.4.30 machine.

In the app store the 2FA app is marked as depricated (available =< V23)

![grafik](https://user-images.githubusercontent.com/1645099/185759802-e2e9f9a9-643b-4cc3-8dac-28736c4681ff.png)

![grafik](https://user-images.githubusercontent.com/1645099/185759830-9102c2c9-9201-4fb4-917c-63f7ae79303d.png)

**Comment by szaimen** [comment] 2023-01-23 14:17
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:51 UTC
Labels: bug, needs info, 0. Needs triage

**Comment by math-GH** [comment] 2023-03-09 19:24
It looks fine on Nextcloud 25.0 now 
![grafik](https://user-images.githubusercontent.com/1645099/224132745-f2f8c0d8-32f1-43e0-b2d9-2242011be3b0.png)
