### ISSUE TITLE
[Bug]: LDAP Setup Check Error in Nextcloud Docker Version 30.0.0

### ISSUE THREAD

**Issue by prasanthcambridge** [nextcloud/server#48767] opened 2024-10-17 14:24 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello team,

I’m currently running Nextcloud version 29.0.8 in a Docker container, integrated with our LDAP server using the 'LDAP user and group backend' app (version 1.21.0). Everything works fine with this setup.

However, when I attempt to upgrade to Nextcloud 30.0.0 (Docker image: nextcloud:30.0.0), I encounter the error shown in the attached file. The error disappears when I disable the LDAP app.

How can we resolve this issue?

Kind regards,
Prasanth Nair![Image](https://github.com/user-attachments/assets/8dae43aa-6896-45b0-aad7-bf03c280fa35)

### Steps to reproduce

1. This happens when we try to upgrade from version 29 to version 30.
2.
3.

### Expected behavior

This bug needs to be resolved.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-10-17 14:28
Duplicate of #47997

**Closed by joshtrichards** 2024-10-17 14:28 UTC
Labels: bug, 0. Needs triage
