### ISSUE TITLE
External file share: Data too long for column 'name' (max 64 chars filename length despite allowing longer)

### ISSUE THREAD

**Issue by mothlyme** [nextcloud/server#22551] opened 2020-09-02 21:18 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a file with a name longer than 64 characters
2. Share the file with another nextcloud instance running with a MySQL (possibly all SQL variants)

### Expected behaviour
A notification to accept the share should get displayed

### Actual behaviour
An error gets logged that the data is too long for the field `name`  in `oc_share_external`.
As the field is of type `VARCHAR(64)` the longest file name could be 63 chars as the inital `/` gets included in the name.

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 19.0.2**

**Where did you install Nextcloud from:** Manual install (also occurs in fresh Snap install)

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
files_sharing | Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_share_external` (`remote`,`share_token`,`password`,`name`,`owner`,`user`,`mountpoint`,`mountpoint_hash`,`accepted`,`remote_id`,`share_type`) SELECT ?,?,?,?,?,?,?,?,?,?,? FROM `oc_share_external` WHERE `user` = ? AND `mountpoint_hash` = ? HAVING COUNT(*) = 0' with params ["https:\/\/nextcloud.REDACTED.com\/", "REDACTED_ID", "", "\/indeedverylongfilenamejusttotestthenextcloudproblemwhensharinglongfiles.pdf", "REDACTED", "m", "{{TemporaryMountPointName#\/indeedverylongfilenamejusttotestthenextcloudproblemwhensharinglongfiles.pdf}}", "REDACTED_HASH", 0, 9, 0, "max", "REDACTED_HASH"]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'name' at row 1

```
</details>

I have omitted more detailed OS and web browser logs as this is a purely architectural issue in regards to SQL databases.
The simplest solution I could think of would be to change the `name` field to type `VARCHAR(128)` or larger (something that suits the rest of tables).

**Comment by szaimen** [comment] 2021-06-02 12:33
Duplicate of https://github.com/nextcloud/server/issues/19635

**Closed by szaimen** 2021-06-02 12:33 UTC
Labels: 0. Needs triage, bug

**Comment by aignerat** [comment] 2021-06-02 13:18
in v19 it still was, couldnt yet test it in v21/22
