### ISSUE TITLE
Update to 14.02 from 14.01 various error about "Delete old files"

### ISSUE THREAD

**Issue by Lorenzoform** [nextcloud/server#11777] opened 2018-10-11 14:13 UTC
Hi,

I'm trying to update Nextcloud from 14.01 to 14.02 by web, the first error is about permission of config.bkp, I changed the owner from root to apache solving.
After that I had the problem "Could not delete themes README", the theme files are already owned by apache, I removed the theme manually solving.
After that I had the error "Could not rmdir: /var/www/html/nextcloud/updater/../ocs" but in this case I don't know what to do because in updater there aren't subfolder.

Any suggestion?

Regards.

**Comment by MorrisJobke** [comment] 2018-10-12 08:06
> 1 | OCA\NextcloudAnnouncements\Cron\Crawler | null | 1539264142 | 153926
> 4142 | 1539264142 | 20
> 
> Do I need to wait?

Duplicate of #10949

**Closed by MorrisJobke** 2018-10-12 08:06 UTC
Labels: bug

**Comment by MorrisJobke** [comment] 2018-10-12 08:07
Workaround can be found in https://github.com/nextcloud/server/issues/10949#issuecomment-426033160 and the very next comment there.
