### ISSUE TITLE
Invalid argument supplied for foreach()  serverinfo/lib/OperatingSystems/DefaultOs.php - line 158: 

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#23974] opened 2020-11-07 13:45 UTC
Hello,

i get this Error Message, every Time i look at the System information inside Nextcloud.

##Systeminfo:
```

Ubuntu 20.04.1 LTS
Nextcloud 20.1
php 7.4.3
Mysql
```
##Nextcloud Log
```
[PHP] Error: Error: Invalid argument supplied for foreach() at /var/www/nextcloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#158 at <<closure>>

 0. /var/www/nextcloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php line 158
    OC\Log\ErrorHandler::onError(2, "Invalid argument supplied for foreach()", "/var/www/nextcl ... p", 158, {interfaces: false,result: []})
 1. /var/www/nextcloud/apps/serverinfo/lib/Os.php line 132
    OCA\ServerInfo\OperatingSystems\DefaultOs->getNetworkInterfaces()
 2. /var/www/nextcloud/apps/serverinfo/lib/Settings/AdminSettings.php line 111
    OCA\ServerInfo\Os->getNetworkInterfaces()
 3. /var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 141
    OCA\ServerInfo\Settings\AdminSettings->getForm()
 4. /var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php line 83
    OCA\Settings\Controller\AdminSettingsController->formatSettings([[OCA\ServerInfo ... ]])
 5. /var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 152
    OCA\Settings\Controller\AdminSettingsController->getSettings("serverinfo")
 6. /var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php line 68
    OCA\Settings\Controller\AdminSettingsController->getIndexResponse("admin", "serverinfo")
 7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Settings\Controller\AdminSettingsController->index("serverinfo")
 8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "index")
 9. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "index")
10. /var/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "index", OC\AppFramework\ ... {}, {section: "serve ... "})
11. /var/www/nextcloud/lib/base.php line 1009
    OC\Route\Router->match("/settings/admin/serverinfo")
12. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /settings/admin/serverinfo
from 79.231.208.75 by lars at 2020-11-07T13:38:00+00:00

```
##complete Systeminfo

Link: https://cloud.dasnetzundich.de/s/XxaSb4Txf9q4isq
Passwort: TaiJ4h0f5CWk3tuByVMT

**Comment by kesselb** [comment] 2020-11-07 14:10
Duplicate of https://github.com/nextcloud/serverinfo/issues/168

**Closed by kesselb** 2020-11-07 14:10 UTC
Labels: 0. Needs triage, bug
