### ISSUE TITLE
[Bug]: Comments in pictures

### ISSUE THREAD

**Issue by Lawaluga** [nextcloud/server#46836] opened 2024-07-29 07:57 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If there are images in a directory and I write a comment for each image, all comments are saved in the first image.

### Steps to reproduce

1. go to a directory that contains several images
2. select "File Info" for the first image and write a comment under "Activity".
3. Select “File Info” for another image in the same directory and write a comment here too
All comments are saved for the first image only

### Expected behavior

The comments that I wrote for the individual images should also be included with the respective images

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "urltocloud.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.4.1",
        "overwrite.cli.url": "https:\/\/urltocloud.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "default_phone_region": "de",
        "default_locale": "de_DE",
        "skeletondirectory": "\/var\/www\/vhosts\/urltocloud.de\/standartdateien",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 3600,
        "session_keepalive": true,
        "auto_logout": true,
        "simpleSignUpLink.shown": false,
        "maintenance_window_start": 1,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - calendar: 4.7.13
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - money: 0.28.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.3
  - richdocumentscode: 24.4.502
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - spreed: 19.0.7
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.1
  - theming: 2.4.0
  - timemanager: 0.3.15
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - welcome: 1.2.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - deck: 1.13.1 (installed 1.13.1)
  - encryption: 2.17.0
  - files_external: 1.21.0
  - sharebymail: 1.19.0 (installed 1.19.0)
  - stt_whisper: 1.0.8 (installed 1.0.8)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"Zmq@bcY-NkUOjtSUbR5BiwAAAAk","level":3,"time":"2024-06-13T09:39:57+00:00","remoteAddr":"MyIPAdress","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"fopen(/var/www/vhosts/my.Cloud.de/httpdocs/config/config.php): Failed to open stream: No such file or directory at /var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Config.php#225","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0","version":"","data":{"app":"PHP"}}
{"reqId":"Zmq@4R@GYb7e57YX@8HOQAAAAEA","level":3,"time":"2024-06-13T09:41:53+00:00","remoteAddr":"MyIPAdress","user":"MyUserName","app":"index","method":"GET","url":"/index.php/core/preview?x=256&y=256&fileId=46&c=983800e317a0eb59b92190cfd2e0c7d8","message":"Could not get appdata folder for preview","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0","version":"29.0.2.2","exception":{"Exception":"RuntimeException","Message":"Could not get appdata folder for preview","Code":0,"Trace":[{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Files/AppData/AppData.php","line":147,"function":"getAppDataFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Preview/Storage/Root.php","line":74,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Preview/Generator.php","line":607,"function":"newFolder","class":"OC\\Preview\\Storage\\Root","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Preview/Generator.php","line":133,"function":"getPreviewFolder","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Preview/Generator.php","line":110,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/PreviewManager.php","line":187,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/core/Controller/PreviewController.php","line":174,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/my.Cloud.de/httpdocs/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/vhosts/my.Cloud.de/httpdocs/lib/private/Files/AppData/AppData.php","Line":108,"message":"Could not get appdata folder for preview","exception":{},"CustomMessage":"Could not get appdata folder for preview"}}
{"reqId":"ZmrFvmaXBUecfGPtkVHDJwAAAIQ","level":3,"time":"2024-06-13T10:11:29+00:00","remoteAddr":"MyIPAdress","user":"MyUserName","app":"PHP","method":"POST","url":"/remote.php/dav/bulk","message":"PHP Request Startup: POST Content-Length of 19501501 bytes exceeds the limit of 16777216 bytes at Unknown#0","userAgent":"Mozilla/5.0 (Windows) mirall/3.13.0stable-Win64 (build 20240423) (Nextcloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"29.0.2.2","data":{"app":"PHP"}}
```

**Comment by solracsf** [comment] 2024-07-29 09:06
Duplicate of https://github.com/nextcloud/server/issues/43239

**Closed by solracsf** 2024-07-29 09:06 UTC
Labels: bug, 0. Needs triage, 29-feedback
