### ISSUE TITLE
SCSS not working after reboot

### ISSUE THREAD

**Issue by leonidasv** [nextcloud/server#5138] opened 2017-05-26 20:30 UTC
### Steps to reproduce
My system was running well tomorrow, but I had to turn off my system. Today, after reboot, it was issuing a ".ocdata" not found error. I got into the data folder and created an .ocdata file with 0 bytes. Then I proceeded to web files app and found it working but without css. The logos were loaded, but no css. After some nginx and php-fpm restarts, it suddenly stopped working, droping a "Internal Server Error". 

I looked into nextcloud logs and found errors complaining about SCSS and server.css file. Both files are writable by the www-data user. I tried changing themes, but it was useless.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** Google Cloud SQL MySQL

**PHP version:** 7.0 fpm

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** command line + web setup

**Signing status:**
<details>
<summary>Signing status</summary>
"No errors have been found."
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "debug": true,
        "theme": "loopin",
        "instanceid": "oc3ga35yz6rn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/bucket\/nextcloud",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 58 x86-64

**Operating system:** Xubuntu 16.04 LTS

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"NVOAV6aRVd4g648auLDC","level":3,"time":"2017-05-26T20:07:02+00:00","remoteAddr":"191.23.60.42","user":"leonidas","app":"index","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/**\\\\n * @copyrig...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(228): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/**\\\\n * @copyrig...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(112): OC\\\\Template\\\\SCSSCacher->cache('\\\/var\\\/www\\\/nextcl...', 'server.css', 'server.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), 'core\\\/css')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...', 'core')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"NVOAV6aRVd4g648auLDC","level":3,"time":"2017-05-26T20:07:04+00:00","remoteAddr":"191.23.60.42","user":"leonidas","app":"core","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/**\\\\n * @copyrig...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(228): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/**\\\\n * @copyrig...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(112): OC\\\\Template\\\\SCSSCacher->cache('\\\/var\\\/www\\\/nextcl...', 'server.css', 'server.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), 'core\\\/css')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...', 'core')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"NVOAV6aRVd4g648auLDC","level":3,"time":"2017-05-26T20:07:05+00:00","remoteAddr":"191.23.60.42","user":"leonidas","app":"core","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/**\\\\n * @copyrig...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(228): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/**\\\\n * @copyrig...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(112): OC\\\\Template\\\\SCSSCacher->cache('\\\/var\\\/www\\\/nextcl...', 'server.css', 'server.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), 'core\\\/css')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...', 'core')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('error', '')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(342): OC\\\\Template\\\\Base->printPage()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/index.php(59): OC_Template::printExceptionErrorPage(Object(OCP\\\\Files\\\\NotFoundException))\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"ng5OMFcuXjEn5XJF8w3Y","level":3,"time":"2017-05-26T20:07:07+00:00","remoteAddr":"191.23.60.42","user":"leonidas","app":"index","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/**\\\\n * @copyrig...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(228): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/**\\\\n * @copyrig...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(112): OC\\\\Template\\\\SCSSCacher->cache('\\\/var\\\/www\\\/nextcl...', 'server.css', 'server.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), 'core\\\/css')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...', 'core')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"ng5OMFcuXjEn5XJF8w3Y","level":3,"time":"2017-05-26T20:07:09+00:00","remoteAddr":"191.23.60.42","user":"leonidas","app":"core","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/**\\\\n * @copyrig...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(228): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/**\\\\n * @copyrig...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(112): OC\\\\Template\\\\SCSSCacher->cache('\\\/var\\\/www\\\/nextcl...', 'server.css', 'server.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), 'core\\\/css')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...', 'core')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"ng5OMFcuXjEn5XJF8w3Y","level":3,"time":"2017-05-26T20:07:10+00:00","remoteAddr":"191.23.60.42","user":"leonidas","app":"core","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(95): OC\\\\Files\\\\Node\\\\File->putContent('\\\/**\\\\n * @copyrig...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(228): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/**\\\\n * @copyrig...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(112): OC\\\\Template\\\\SCSSCacher->cache('\\\/var\\\/www\\\/nextcl...', 'server.css', 'server.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), 'core\\\/css')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...', 'core')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/server...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(205): OC\\\\TemplateLayout->__construct('error', '')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(342): OC\\\\Template\\\\Base->printPage()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/index.php(59): OC_Template::printExceptionErrorPage(Object(OCP\\\\Files\\\\NotFoundException))\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.81 Safari\/537.36","version":"12.0.0.29"} 

</details>

#### Browser log
<details>
<summary>Browser log</summary>
N/A (server.css and other css files blank, but found by web browser.)
</details>

**Comment by juliushaertl** [comment] 2017-05-28 11:53
Can you check your data directory for a folder called appdata_oc[instanceid] and if that is writable by your webserver?

This is the location where the generated CSS will be stored.

**Comment by leonidasv** [comment] 2017-06-22 23:54
@juliushaertl I reinstalled my instance. As far as I remember, it was a conflict with the theming plugin and my custom theme.

**Comment by MorrisJobke** [comment] 2017-08-31 08:35
We can't reproduce and this does not seem to happen anymore at the reporters instance: closing.

**Closed by MorrisJobke** 2017-08-31 08:35 UTC
Labels: feature: scss, feature: theming, needs info
