### ISSUE TITLE
[Bug]: commenting a file in the activity tab throws an error

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#42260] opened 2023-12-14 09:45 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] nextcloud/server#47556
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

First case:
I create a new file, paste some content including an image, rename rename the file. I open the activity tab, write stg and mention @smb. When pressing enter, loading icon shows, and the error below is thrown (see below the error msg from the console)

![image](https://github.com/nextcloud/server/assets/87175513/37ff8617-bad9-4f79-83a6-068f8d68d380)

On page refresh, the comment appears as many times as I've try to send it.

Second case:
I create a new file, I don't rename it, and go directly to activity tab, write stg and mention @smb. When pressing enter, loading icon shows, and the same error is thrown. The console error message (see below) is different from the first case.

On page refresh, the comment does not appear.

### Steps to reproduce

1.
2.
3.

### Expected behavior

Comment should be posted withut error.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Error msg from console - case 1
```
Object { stack: "r@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3204511\nr@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3209682\nw@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3193474\n", message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…} }
sentry.js:2:63997
    Nt NextJS
    onNewComment CommentMixin.js:116
```

Error msgs from console - case 2
```
XHRPOST
https://cloud.nextcloud.com/remote.php/dav/comments/files/8133962
[HTTP/2 500  15417ms]

Object { stack: "r@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3204511\nr@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3209682\nw@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3193474\nEventHandlerNonNull*6005/A</<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3193643\n6005/A<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3192526\np@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3196854\nrequest@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3200530\n51120/</t/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3200998\n36524/a/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:3213161\nc@https://cloud.nextcloud.com/dist/7255-7255.js?v=ee3155ac7765bb364ab8:2:2492\nonNewComment@https://cloud.nextcloud.com/dist/7255-7255.js?v=ee3155ac7765bb364ab8:2:1433\nonSubmit@https://cloud.nextcloud.com/dist/7255-7255.js?v=ee3155ac7765bb364ab8:2:5242\nTn@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1869943\nn@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1862384\nTn@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1869943\n20144/e.prototype.$emit@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1891084\nonEnter@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:2459073\n98212/O/<.on.keydown<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:2460235\nTn@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1869943\nn@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1862463\n20144/ii/i._wrapper@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1902742\nr@https://cloud.nextcloud.com/apps/sentry/js/sentry.js?v=30874e5d-1764:2:87291\nEventListener.handleEvent*Me/</<@https://cloud.nextcloud.com/apps/sentry/js/sentry.js?v=30874e5d-1764:2:97126\nNt/</</<@https://cloud.nextcloud.com/apps/sentry/js/sentry.js?v=30874e5d-1764:2:64642\nii@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1902768\nBt@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1862671\nsi@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1903149\n_@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1912004\nh@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1911313\n20144/Ji@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1915303\n20144/e.prototype._update@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1891236\na@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1922781\n20144/e.prototype.get@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1873533\ne@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1873446\n20144/sr.prototype.$mount/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1922805\n20144/sr.prototype.$mount@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1923023\ninit@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1878312\n20144/h/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1910908\nh@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1911184\n20144/w/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1914031\nw@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1914215\n20144/w/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1913740\nw@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1914215\n20144/w/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1913740\nw@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1914215\n20144/w/<@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1913740\nw@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1914215\n20144/Ji@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1915351\n20144/e.prototype._update@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1891219\na@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1922781\n20144/e.prototype.get@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1873533\n20144/e.prototype.run@https://cloud.nextcloud.com/dist/core-common.js?v=30874e5d-1764:2:1874266\n", message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…} }
sentry.js:2:63997
```

**Comment by joshtrichards** [comment] 2023-12-18 18:46
Based both provided console logs, there should be associated server side stack traces. You have those by chance?

**Comment by joshtrichards** [comment] 2024-02-26 15:52
Possibly related (at least to the second situation): #43239

**Comment by edward-ly** [comment] 2024-08-28 19:21
I cannot reproduce this issue either, even on 28.0.0.

@maximelehericy If you have any more info you are able to share, you can reopen this issue, but for now, I am closing this.

**Closed by edward-ly** 2024-08-28 19:21 UTC
Labels: bug, 0. Needs triage, feature: files, feature: comments, 28-feedback
