### ISSUE TITLE
@-mentions not working in file comments initially / working during edit comment only

### ISSUE THREAD

**Issue by SLYtiger16** [nextcloud/server#21909] opened 2020-07-18 19:35 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open details field on a file
2. Attempt to use '@' to mention a user in a comment

### Expected behaviour
User list drop down should appear to select mentionable user

### Actual behaviour
Nothing; however, I can edit the comment and this behavior works correctly during the edit just not the initial comment.

### Server configuration

**Operating system:**
Ubuntu server 20.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Official tar

*Note: no log information regarding this error, cannot access config easily

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Any

**Operating system:**
Any

**Comment by jakobroehrl** [comment] 2020-07-20 07:55
Duplicate of https://github.com/nextcloud/server/issues/19523

**Closed by jakobroehrl** 2020-07-20 07:55 UTC
Labels: 0. Needs triage, bug
