### ISSUE TITLE
InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.

### ISSUE THREAD

**Issue by robkalmeijer** [nextcloud/server#24487] opened 2020-12-01 16:54 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Run update after reinstall nextcloud 20 on new server from nextcloud 16 with existing db
2.
3.

### Expected behaviour
Tell us what should happen

Most run but failed with error in title.

Ready for use.

### Actual behaviour
Tell us what happens instead
Most run but failed with error in title.

### Server configuration

**Operating system:**

**Web server:** Apache 2.4

**Database:**Mariadb 10.4

**PHP version:**php 7.4

**Nextcloud version:** (see Nextcloud admin page) 20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older Nextcloud/ownCloud with a fress install of code.

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
Bijwerken App vereist
Deze apps worden bijgewerkt:
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
[root@server4 httpsdocs]# sudo -u apache php occ app:list
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - cloud_federation_api: 1.3.0
  - comments: 1.6.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.5.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.6.0
  - text: 3.1.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
[root@server4 httpsdocs]# sudo -u apache php occ config:list system
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.robkalmeijer.nl",
            "192.168.1.14",
            "[2001:985:395:1::1:4]"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.2.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Not yet
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

not

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**Firefox

**Operating system:**
win10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
[Tue Dec 01 17:35:47.123493 2020] [php7:notice] [pid 31347] [client 2001:985:395:1:3027:569:60e1:53e3:59730] {"reqId":"X8Zw4i3iQDEW8@N8eWVz6gAAABE","level":3,"time":"2020-12-01T16:35:47+00:00","remoteAddr":"2001:985:395:1:3027:569:60e1:53e3","user":"--","app":"PHP","method":"GET","url":"/index.php","message":{"Exception":"Error","Message":"fopen(/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/data/data_dir_writability_test_5fc670e31d715.tmp): failed to open stream: Permission denied at /srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/legacy/OC_Util.php#804","Code":0,"Trace":[{"function":"onError","class":"OC\\\\Log\\\\ErrorHandler","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/legacy/OC_Util.php","line":804,"function":"fopen"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/base.php","line":660,"function":"checkServer","class":"OC_Util","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/index.php","line":35,"args":["/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/base.php"],"function":"require_once"}],"File":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2"}, referer: https://cloud.robkalmeijer.nl/
[Tue Dec 01 17:35:47.300987 2020] [php7:notice] [pid 31347] [client 2001:985:395:1:3027:569:60e1:53e3:59730] {"reqId":"X8Zw4i3iQDEW8@N8eWVz6gAAABE","level":4,"time":"2020-12-01T16:35:47+00:00","remoteAddr":"2001:985:395:1:3027:569:60e1:53e3","user":"--","app":"no app in context","method":"GET","url":"/index.php","message":{"Exception":"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException","Message":"An exception occurred while executing 'SELECT `class`, `entity`, `events` FROM `oc_flow_operations` WHERE `events` <> ? GROUP BY `class`, `entity`, `events`' with params [\\"[]\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'field list'","Code":0,"Trace":[{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":149,"function":"wrapException","class":"Doctrine\\\\DBAL\\\\DBALException","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":914,"function":"driverExceptionDuringQuery","class":"Doctrine\\\\DBAL\\\\DBALException","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/DB/Connection.php","line":202,"function":"executeQuery","class":"Doctrine\\\\DBAL\\\\Connection","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php","line":206,"function":"executeQuery","class":"OC\\\\DB\\\\Connection","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/DB/QueryBuilder/QueryBuilder.php","line":217,"function":"execute","class":"Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/apps/workflowengine/lib/Manager.php","line":155,"function":"execute","class":"OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/apps/workflowengine/lib/AppInfo/Application.php","line":70,"function":"getAllConfiguredEvents","class":"OCA\\\\WorkflowEngine\\\\Manager","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":68,"function":"registerRuleListeners","class":"OCA\\\\WorkflowEngine\\\\AppInfo\\\\Application","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/AppFramework/Bootstrap/BootContext.php","line":52,"function":"injectFn","class":"OC\\\\AppFramework\\\\Bootstrap\\\\FunctionInjector","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/apps/workflowengine/lib/AppInfo/Application.php","line":62,"function":"injectFn","class":"OC\\\\AppFramework\\\\Bootstrap\\\\BootContext","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/AppFramework/Bootstrap/Coordinator.php","line":168,"function":"boot","class":"OCA\\\\WorkflowEngine\\\\AppInfo\\\\Application","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/legacy/OC_App.php","line":191,"function":"bootApp","class":"OC\\\\AppFramework\\\\Bootstrap\\\\Coordinator","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/legacy/OC_Util.php","line":201,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Files/Filesystem.php","line":267,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Server.php","line":376,"function":"getMountManager","class":"OC\\\\Files\\\\Filesystem","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":155,"function":"OC\\\\{closure}","class":"OC\\\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\\\AppFramework\\\\Utility\\\\{closure}","class":"OC\\\\AppFramework\\\\Utility\\\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":122,"function":"offsetGet","class":"Pimple\\\\Container","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/ServerContainer.php","line":156,"function":"query","class":"OC\\\\AppFramework\\\\Utility\\\\SimpleContainer","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Server.php","line":406,"function":"query","class":"OC\\\\ServerContainer","type":"->"},{"function":"OC\\\\{closure}","class":"OC\\\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Files/Node/LazyFolder.php","line":63,"function":"call_user_func"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Files/Node/LazyFolder.php","line":143,"function":"__call","class":"OC\\\\Files\\\\Node\\\\LazyFolder","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Files/AppData/AppData.php","line":142,"function":"get","class":"OC\\\\Files\\\\Node\\\\LazyFolder","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Template/JSCombiner.php","line":97,"function":"getFolder","class":"OC\\\\Files\\\\AppData\\\\AppData","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Template/JSResourceLocator.php","line":116,"function":"process","class":"OC\\\\Template\\\\JSCombiner","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Template/JSResourceLocator.php","line":72,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\\\Template\\\\JSResourceLocator","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Template/ResourceLocator.php","line":79,"function":"doFind","class":"OC\\\\Template\\\\JSResourceLocator","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/TemplateLayout.php","line":364,"function":"find","class":"OC\\\\Template\\\\ResourceLocator","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/TemplateLayout.php","line":194,"function":"findJavascriptFiles","class":"OC\\\\TemplateLayout","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/legacy/OC_Template.php","line":183,"function":"__construct","class":"OC\\\\TemplateLayout","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/legacy/OC_Template.php","line":273,"function":"printPage","class":"OC\\\\Template\\\\Base","type":"->"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/base.php","line":666,"function":"printGuestPage","class":"OC_Template","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/index.php","line":35,"args":["/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/base.php"],"function":"require_once"}],"File":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":60,"Previous":{"Exception":"Doctrine\\\\DBAL\\\\Driver\\\\PDOException","Message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'field list'","Code":"42S22","Trace":[{"file":"/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/3rdparty/doctrine/dbal/lib/Do
[Tue Dec 01 17:35:47.388816 2020] [php7:notice] [pid 31347] [client 2001:985:395:1:3027:569:60e1:53e3:59730] {"reqId":"X8Zw4i3iQDEW8@N8eWVz6gAAABE","level":3,"time":"2020-12-01T16:35:47+00:00","remoteAddr":"2001:985:395:1:3027:569:60e1:53e3","user":"--","app":"PHP","method":"GET","url":"/index.php","message":"fopen(/srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/data/nextcloud.log): failed to open stream: Permission denied at /srv/www/vhosts/cloud.robkalmeijer.nl/httpsdocs/lib/private/Log/File.php#85","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2"}, referer: https://cloud.robkalmeijer.nl/
[
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
To large
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2020-12-01 19:51
Duplicate of https://github.com/nextcloud/server/issues/23174

**Closed by kesselb** 2020-12-01 19:51 UTC
Labels: 0. Needs triage, bug
