### ISSUE TITLE
Disabled users not shown in the Web-UI

### ISSUE THREAD

**Issue by fleesty-bfs** [nextcloud/server#5600] opened 2017-07-04 08:33 UTC
### Steps to reproduce
1. Create a user
2. Disable the user
3. Try to find the user in the Web-UI

### Expected behavior
The disabled user should be shown in the User-Management under "Disabled".

### Actual behavior
The disabled user is not shown in the Web-UI. Nowhere! Its also not possible to search the user. The occ command works as expected.

### Server configuration
**Operating system**: Linux ***REMOVED SENSITIVE VALUE*** 4.1.12-61.1.28.el7uek.x86_64 #2 SMP Thu Feb 23 19:55:12 PST 2017 x86_64

**Web server:** Apache/2.4.6 () OpenSSL/1.0.1e-fips PHP/7.0.5 (apache2handler)

**Database:** mysql 5.6.23

**PHP version:** 7.0.5
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, json, ldap, exif, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-12.0.0.zip

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxpod: 2.1.2
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0

Disabled:
 - admin_audit
 - encryption
 - files_external
 - files_reader
 - user_external
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "updatechecker": false,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/data\/cloud",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "cloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "instanceid": "ocjmmrdrlq92",
    "ldapIgnoreNamingRules": false,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_from_address": "cloud",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
	<summary>LDAP config</summary>

	```
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                                                                                                     |
| hasPagedResultSupport         |                                                                                                                                                                                     |
| homeFolderNamingRule          |                                                                                                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                   |
| ldapAgentName                 |                                                                                                                                                                                     |
| ldapAgentPassword             | ***                                                                                                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                     |
| ldapAttributesForUserSearch   | displayName;uid;sn;mailPrimaryAddress                                                                                                                                               |
| ldapBackupHost                |                                                                                                                                                                                     |
| ldapBackupPort                |                                                                                                                                                                                     |
| ldapBase                      | ***REMOVED SENSITIVE VALUE***                                                                                                                                                                       |
| ldapBaseGroups                | ***REMOVED SENSITIVE VALUE***                                                                                                                                                                        |
| ldapBaseUsers                 | ***REMOVED SENSITIVE VALUE***                                                                                                                                                                        |
| ldapCacheTTL                  | 3600                                                                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                                                                   |
| ldapDefaultPPolicyDN          |                                                                                                                                                                                     |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                     |
| ldapEmailAttribute            | mail                                                                                                                                                                                |
| ldapExperiencedAdmin          | 1                                                                                                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                                     |
| ldapExpertUsernameAttr        | uid                                                                                                                                                                                 |
| ldapGidNumber                 | gidNumber                                                                                                                                                                           |
| ldapGroupDisplayName          | cn                                                                                                                                                                                  |
| ldapGroupFilter               | (|(cn=Domain Users)(cn=ext-doku-bn))                                                                                                                                                |
| ldapGroupFilterGroups         | Domain Users                                                                                                                                                                        |
| ldapGroupFilterMode           | 0                                                                                                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                                                                                                     |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                                        |
| ldapHost                      | ***REMOVED SENSITIVE VALUE***                                                                                                                                                                      |
| ldapIgnoreNamingRules         |                                                                                                                                                                                     |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid))                                                                                                                                         |
| ldapLoginFilterAttributes     |                                                                                                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                   |
| ldapNestedGroups              | 0                                                                                                                                                                                   |
| ldapOverrideMainServer        |                                                                                                                                                                                     |
| ldapPagingSize                | 0                                                                                                                                                                                   |
| ldapPort                      | 7389                                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                                     |
| ldapQuotaDefault              |                                                                                                                                                                                     |
| ldapTLS                       | 0                                                                                                                                                                                   |
| ldapUserDisplayName           | displayname                                                                                                                                                                         |
| ldapUserDisplayName2          |                                                                                                                                                                                     |
| ldapUserFilter                | (|(&(|(uid=*-sz)(uid=*-ber)(uid=*-b)(uid=*-muc)(uid=*-m)(uid=*-rd)(uid=*-bn)(uid=*-fr))(!(uid=*-*-*))(krb5PasswordEnd=*))(uid=adm-*)(uid=ext-ssk-*)(uid=ext-bmu-*)(uid=ext-ag61-*)) |
| ldapUserFilterGroups          |                                                                                                                                                                                     |
| ldapUserFilterMode            | 0                                                                                                                                                                                   |
| ldapUserFilterObjectclass     | sambaSamAccount                                                                                                                                                                     |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                                                                                                |
| turnOffCertCheck              | 0                                                                                                                                                                                   |
| turnOnPasswordChange          | 0                                                                                                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
	```
</details>
### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0

**Operating system:** Ubuntu 17.04 / Windows 7

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	***EMPTY***
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	{"reqId":"WVtG2SEGSs6IISMKmVdtUAAAAAA","level":0,"time":"2017-07-04T07:42:17+00:00","remoteAddr":"10.128.31.98","user":"admin","app":"user_ldap","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=50&gid=&pattern=test123user","message":"getUsers: Options: search test123user limit 50 offset 0 Filter: (&(|(&(|(uid=*-sz)(uid=*-ber)(uid=*-b)(uid=*-muc)(uid=*-m)(uid=*-rd)(uid=*-bn)(uid=*-fr))(!(uid=*-*-*))(krb5PasswordEnd=*))(uid=adm-*)(uid=ext-ssk-*)(uid=ext-bmu-*)(uid=ext-ag61-*))(displayname=*)(|(displayName=test123user*)(uid=test123user*)(sn=test123user*)(mailPrimaryAddress=test123user*)))","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"WVtG2SEGSs6IISMKmVdtUAAAAAA","level":0,"time":"2017-07-04T07:42:17+00:00","remoteAddr":"10.128.31.98","user":"admin","app":"user_ldap","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=50&gid=&pattern=test123user","message":"initializing paged search for  Filter (&(|(&(|(uid=*-sz)(uid=*-ber)(uid=*-b)(uid=*-muc)(uid=*-m)(uid=*-rd)(uid=*-bn)(uid=*-fr))(!(uid=*-*-*))(krb5PasswordEnd=*))(uid=adm-*)(uid=ext-ssk-*)(uid=ext-bmu-*)(uid=ext-ag61-*))(displayname=*)(|(displayName=test123user*)(uid=test123user*)(sn=test123user*)(mailPrimaryAddress=test123user*))) base Array\n(\n    [0] => dc=bfs,dc=de\n)\n attr Array\n(\n    [0] => dn\n    [1] => uid\n    [2] => samaccountname\n    [3] => memberof\n    [4] => \n    [5] => mail\n    [6] => displayname\n    [7] => \n)\n limit 50 offset 0","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"WVtG2SEGSs6IISMKmVdtUAAAAAA","level":0,"time":"2017-07-04T07:42:17+00:00","remoteAddr":"10.128.31.98","user":"admin","app":"user_ldap","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=50&gid=&pattern=test123user","message":"Ready for a paged search","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"WVtG2SEGSs6IISMKmVdtUAAAAAA","level":0,"time":"2017-07-04T07:42:17+00:00","remoteAddr":"10.128.31.98","user":"admin","app":"user_ldap","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=50&gid=&pattern=test123user","message":"getUsers: 0 Users found","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
	```
</details>

**Comment by michag86** [comment] 2017-07-28 09:45
Do you disable the user as group admin or as member of "Admins"? If as group admin, this is a duplicate of #4789

**Comment by MorrisJobke** [comment] 2017-08-30 08:43
Duplicate of #4789

**Closed by MorrisJobke** 2017-08-30 08:43 UTC
