### ISSUE TITLE
 nextcloud AH01797: client denied by server configuration: /var/www/html/config

### ISSUE THREAD

**Issue by mleelion** [nextcloud/server#30110] opened 2021-12-06 09:25 UTC
when upgrade  docker.io/nextcloud:21.0.0 to 22.2.0, then the new users by LDAP can't  login in. the interface displays "wrong user name or password.", the error log is " nextcloud AH01797: client denied by server configuration: /var/www/html/config “. Now, when I attempt upgrade to docker.io/nextcloud:22.2.3-apache,the err log is "AH01797: client denied by server configuration: /var/www/html/data/.ocdata" , and Modify the configuration file  of 'config/config.php' is useless .

But this error don't affect old users who have logged in in the past.

I know my description above is vague, And, This error is caused by changes in the apache version after the upgrade, but there is no way to modify it  .   might anybody have a pointer about what I should look for and where?

**Comment by kesselb** [comment] 2022-06-26 16:33
Duplicate of https://github.com/nextcloud/server/issues/15688. Should be fixed by a desktop client update a while ago.

**Closed by kesselb** 2022-06-26 16:33 UTC
Labels: enhancement, 0. Needs triage
