### ISSUE TITLE
Activity notification loop - an email sent to all every 30 minutes

### ISSUE THREAD

**Issue by wherf** [nextcloud/server#1778] opened 2016-10-18 10:45 UTC
### Steps to reproduce

1.The server is sending the activity email to all users every thirty minutes with the same content
2. This happened after a share to all was set at a top level folder and then a share to all was set on a sub-level folder. This possibly led to a loop
### Expected behaviour

The activety email should only go out for new activities and not be repeated
### Actual behaviour

The server is sending the activity email to all users every thirty minutes with teh same content
### Server configuration

**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
10.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
New install
**Where did you install Nextcloud from:**
Website
**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT \* FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
```

Insert your webserver log here

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```

Insert your Nextcloud log here

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...

```
</details>
```

**Comment by nickvergessen** [comment] 2016-10-18 15:06
Duplicate of https://github.com/nextcloud/server/issues/1716

**Comment by wherf** [comment] 2016-10-18 15:16
Have to disagree, ist differennt to 1716 -

please look at the owncloud link #26369<https://github.com/owncloud/core/issues/26369>

Mine has nothing to do with the cronjob, and I am getting lots of  error with write access

Von: Joas Schilling [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 17:07
An: nextcloud/server
Cc: Wolf Dieter Herf; Author
Betreff: Re: [nextcloud/server] Activity notification loop - an email sent to all every 30 minutes (#1778)


Closed #1778<https://github.com/nextcloud/server/issues/1778>.

**Comment by nickvergessen** [comment] 2016-10-18 15:22
The fix should still work

**Comment by wherf** [comment] 2016-10-19 03:51
I checked the cron job with -l

its reply is
*/15 *   *             *             *             php -f /var/www/nextcloud/cron.php >             /dev/null            2>&1

The log is being filled with this single error all the time, Ist now already 2GB big

{"reqId":"JwPJXq0bbkQM+fadjNvW","remoteAddr":"91.64.60.106","app":"no app in context","message":"Error while trying to create shared mount","level":3,"time":"2016-09-07T16:14:56+00:00","method":"GET","url":"\/index.php\/avatar\/m.kapst\/32","user":"Intranet"} {"reqId":"Xm6ZX2+PMzEzdr5pdsGr","remoteAddr":"91.64.60.106","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(437): OC\\\\Share20\\\\Share->getNode()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(878): OC\\\\Share20\\\\DefaultShareProvider->move(Object(OC\\\\Share20\\\\Share), 'Intranet')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(120): OC\\\\Share20\\\\Manager->moveShare(Object(OC\\\\Share20\\\\Share), 'Intranet')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(102): OCA\\\\Files_Sharing\\\\SharedMount->updateFileTarget('\\\/Klasse 2010 (2...', Object(OC\\\\Share20\\\\Share))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(73): OCA\\\\Files_Sharing\\\\SharedMount->verifyMountPoint(Object(OC\\\\Share20\\\\Share), Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/MountProvider.php(91): OCA\\\\Files_Sharing\\\\SharedMount->__construct('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, Array, Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(77): OCA\\\\Files_Sharing\\\\MountProvider->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#7 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_Sharing\\\\MountProvider))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(78): array_map(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(423): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser(Object(OC\\\\User\\\\User))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(371): OC\\\\Files\\\\Filesystem::initMountPoints('Intranet')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(227): OC\\\\Files\\\\Filesystem::init('Intranet', '\\\/Intranet\\\/files')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/api.php(353): OC_Util::setupFS('Intranet')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/api.php(300): OC_API::loginUser()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/api.php(159): OC_API::isAuthorised(Array)\\n#15 [internal function]: OC_API::call(Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Array, Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/ocs\\\/v1.php(61): OC\\\\Route\\\\Router->match('\\\/ocs\\\/apps\\\/files...')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/ocs\\\/v2.php(23): require_once('\\\/var\\\/www\\\/nextcl...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/Share.php\",\"Line\":163}","level":3,"time":"2016-09-07T16:14:57+00:00","method":"PUT","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/83?format=json","user":"Intranet"} {

Von: Joas Schilling [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 17:22
An: nextcloud/server
Cc: Wolf Dieter Herf; Author
Betreff: Re: [nextcloud/server] Activity notification loop - an email sent to all every 30 minutes (#1778)


The fix should still work

**Comment by nickvergessen** [comment] 2016-10-19 06:54
### Log
```
{
    "reqId": "Xm6ZX2+PMzEzdr5pdsGr",
    "remoteAddr": "91.64.60.106",
    "app": "no app in context",
    "message": {
        "Exception": {
            "Exception": "OCP\Files\NotFoundException",
            "Message": "",
            "Code": 0,
            "Trace": {
                "#0": [
                    "/var/www/nextcloud/lib/private/Share20/DefaultShareProvider.php(437):",
                    "OC\Share20\Share->getNode()"
                ],
                "#1": [
                    "/var/www/nextcloud/lib/private/Share20/Manager.php(878): OC\Share20\DefaultShareProvider->move(Object(OC\Share20\Share), 'Intranet')",
                    null
                ],
                "#2": [
                    "/var/www/nextcloud/apps/files_sharing/lib/SharedMount.php(120): OC\Share20\Manager->moveShare(Object(OC\Share20\Share), 'Intranet')",
                    null
                ],
                "#3": [
                    "/var/www/nextcloud/apps/files_sharing/lib/SharedMount.php(102): OCA\Files_Sharing\SharedMount->updateFileTarget('/Klasse 2010 (2...', Object(OC\Share20\Share))",
                    null
                ],
                "#4": [
                    "/var/www/nextcloud/apps/files_sharing/lib/SharedMount.php(73): OCA\Files_Sharing\SharedMount->verifyMountPoint(Object(OC\Share20\Share), Array)",
                    null
                ],
                "#5": [
                    "/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php(91): OCA\Files_Sharing\SharedMount->__construct('\\OC\\Files\\Stora...', Array, Array, Object(OC\Files\Storage\StorageFactory))",
                    null
                ],
                "#6": [
                    "/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php(77): OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))",
                    null
                ],
                "#7": [
                    "[internal function]: OC\Files\Config\MountProviderCollection->OC\Files\Config\{closure}(Object(OCA\Files_Sharing\MountProvider))",
                    null
                ],
                "#8": [
                    "/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php(78): array_map(Object(Closure), Array)",
                    null
                ],
                "#9": [
                    "/var/www/nextcloud/lib/private/Files/Filesystem.php(423):",
                    "OC\Files\Config\MountProviderCollection->getMountsForUser(Object(OC\User\User))"
                ],
                "#10": [
                    "/var/www/nextcloud/lib/private/Files/Filesystem.php(371):",
                    "OC\Files\Filesystem::initMountPoints('Intranet')"
                ],
                "#11": [
                    "/var/www/nextcloud/lib/private/legacy/util.php(227): OC\Files\Filesystem::init('Intranet', '/Intranet/files')",
                    null
                ],
                "#12": [
                    "/var/www/nextcloud/lib/private/legacy/api.php(353):",
                    "OC_Util::setupFS('Intranet')"
                ],
                "#13": [
                    "/var/www/nextcloud/lib/private/legacy/api.php(300):",
                    "OC_API::loginUser()"
                ],
                "#14": [
                    "/var/www/nextcloud/lib/private/legacy/api.php(159):",
                    "OC_API::isAuthorised(Array)"
                ],
                "#15": [
                    "[internal function]: OC_API::call(Array)",
                    null
                ],
                "#16": [
                    "/var/www/nextcloud/lib/private/Route/Router.php(293): call_user_func(Array, Array)",
                    null
                ],
                "#17": [
                    "/var/www/nextcloud/ocs/v1.php(61):",
                    "OC\Route\Router->match('/ocs/apps/files...')"
                ],
                "#18": [
                    "/var/www/nextcloud/ocs/v2.php(23):",
                    "require_once('/var/www/nextcl...')"
                ],
                "#19": [
                    "{main}",
                    null
                ]
            },
            "File": "/var/www/nextcloud/lib/private/Share20/Share.php",
            "Line": 163
        }
    },
    "level": 3,
    "time": "2016-09-07T16:14:57+00:00",
    "method": "PUT",
    "url": "/ocs/v2.php/apps/files_sharing/api/v1/shares/83?format=json",
    "user": "Intranet"
}
```

**Comment by nickvergessen** [comment] 2016-10-19 06:55
Well the log is certainly unrelated, but also something you should look into.

**Comment by wherf** [comment] 2016-10-19 09:11
I used webmin to clear the activity_mq table, seems that now the email loop has stopped. I have now eneterd a new activity, and will see if the emails only get sent once.

Will make a new issue for the OCP\Files\NotFoundException error

Von: Joas Schilling [mailto:notifications@github.com]
Gesendet: Mittwoch, 19. Oktober 2016 08:55
An: nextcloud/server
Cc: Wolf Dieter Herf; Author
Betreff: Re: [nextcloud/server] Activity notification loop - an email sent to all every 30 minutes (#1778)


Well the log is certainly unrelated, but also something you should look into.

**Comment by nickvergessen** [comment] 2016-12-05 10:32
Closing

**Closed by nickvergessen** 2016-12-05 10:32 UTC
Labels: needs info
