### ISSUE TITLE
[Bug]: After Upgrade to 25.0.5 Side Menu of the files App is not responsive with MacOS Safari

### ISSUE THREAD

**Issue by dirkpape** [nextcloud/server#37420] opened 2023-03-27 08:34 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since Upgrade from 25.0.4 to 25.0.5 the side menu in the files app does not vanish on Safari on MacOS (Desktop/Ventura as well as iOS 16) when the window becomes small.
This is new after the upgrade to 25.0.5.  

### Steps to reproduce

1. Open nextcloud in the most recent version of the Safari Browser on iOS or MacOS
2. Open the files App
3. Resize the window to a small width (on MacOS). On iPhone the problem ist istantly visble

### Expected behavior

below a given width the side menu should vanish and be replaced by the "hamburger icon"

### Installation method

None

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.drdpc.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "25.0.5.1",
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "de_DE",
        "defaultapp": "files",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "overwritehost": "oc.drdpc.de",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/oc.drdpc.de",
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "loglevel": 0,
        "log_rotate_size": 104857600,
        "enable_previews": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mysql.utf8mb4": true,
        "tempdirectory": "\/var\/www\/vhosts\/oc.drdpc.de\/oc.drdpc.de\/cloud-temp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "debug": false,
        "appstore.experimental.enabled": true,
        "asset-pipeline.enabled": false,
        "app_install_overwrite": [
            "issuetemplate",
            "impersonate"
        ],
        "theme": "",
        "default_phone_region": "DE",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "mail_sendmailmode": "pipe",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.5.1
  - auto_groups: 1.5.1
  - bookmarks: 12.1.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - data_request: 1.12.0
  - dav: 1.24.0
  - deck: 1.8.3
  - drawio: 2.1.0
  - drop_account: 2.1.0
  - electronicsignatures: 2.0.3
  - emlviewer: 1.0.7
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_antivirus: 4.0.3
  - files_confidential: 1.0.0
  - files_downloadactivity: 1.16.0
  - files_external: 1.17.0
  - files_fulltextsearch: 25.0.0
  - files_fulltextsearch_tesseract: 25.0.0
  - files_pdfviewer: 2.6.0
  - files_readmemd: 2.0.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.2.0
  - firstrunwizard: 2.14.0
  - forms: 3.2.0
  - fulltextsearch: 25.0.0
  - fulltextsearch_elasticsearch: 25.0.0
  - groupfolders: 13.1.1
  - guests: 2.3.0
  - impersonate: 1.12.0
  - integration_github: 1.0.15
  - issuetemplate: 0.7.0
  - keeweb: 0.6.12
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.5
  - metadata: 0.17.0
  - music: 1.8.1
  - news: 21.1.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.7.2
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.8.0
  - pandoc: 0.4.1
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.1.8
  - previewgenerator: 5.2.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.5
  - support: 1.8.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_admin: 4.1.9
  - twofactor_backupcodes: 1.14.0
  - twofactor_nextcloud_notification: 3.6.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.8
  - workflowengine: 2.7.0
Disabled:
  - encryption: 2.8.1
  - files_markdown: 2.3.6
  - survey_client: 1.7.0
  - suspicious_login
  - user_ldap
```

**Comment by mafjensengithub** [comment] 2023-03-31 20:12
Same issue here, both on files app and settings. Sidepanel takes up 80% of screen on the IOS/safari, and cannot be closed..

**Comment by dirkpape** [comment] 2023-04-09 08:47
for me this issue has vanished. Magically without any update on nextcloud server software.
Maybe this is because of an update of an app or of a Safari-Update? I don't know.

**Comment by ya-d** [comment] 2023-04-17 12:19
I still get this issue with NC 25.0.5 with iOS and Safari on macOS. Brave on macOS collapses the side menu and shows the icon as intended. But #37652 reports this issue for DuckDuckGo on Android as well.

Also reported in #37433 and #37652.

**Comment by sistason** [comment] 2023-04-19 10:10
In my instance running 25.0.5 two users on iOS also reported this issue using Safari.

**Comment by andrewhotlab** [comment] 2023-07-24 08:53
This issue is still present in NC 25.0.9. I just tried NC 26.0.4, which works well instead.

**Comment by joshtrichards** [comment] 2024-07-31 14:06
Closing because:

- OP reports fixed: https://github.com/nextcloud/server/issues/37420#issuecomment-1501078139
- another commenter reported this fixed in 26
- The front-end has been largely re-written as of 28 and <28 is now end-of-life. If this is occurring still, please create a new issue since it's likely different code.

**Closed by joshtrichards** 2024-07-31 14:06 UTC
Labels: bug, design, 0. Needs triage, feature: file sidebar, 25-feedback
