### ISSUE TITLE
Case sensitive username using external_user app

### ISSUE THREAD

**Issue by Thommy1231** [nextcloud/server#20082] opened 2020-03-21 18:42 UTC
Hi,
we're using the Nextcloud Server 17.02 with the external user app, so we get from our API the credentials are ok or not.
Our problem is that the user can login f.e. as thommy1231 and everything is ok
When the loginname is not the original like above such a username like Thommy1231 our API say also ok but Nextcloud needs thommy1231 for show the correct files.   
    User thommy1231 -> no problem 
    Login with Thommy1231 instead of thommy1231 -> can't see the files

Has anybody an idea how we can solve the problem

**Comment by wiswedel** [comment] 2020-03-24 19:54
duplicate of https://github.com/nextcloud/user_external/issues/8

**Closed by wiswedel** 2020-03-24 19:54 UTC
