### ISSUE TITLE
High CPU load when i shared directory

### ISSUE THREAD

**Issue by JyBigBoss** [nextcloud/server#16116] opened 2019-06-27 11:20 UTC
### Steps to reproduce

1. Login with admin user for web
2. Create new directory
3. Shared this directory to other user(like: testuser)
4. Login with testuser  for web
5. Refresh the web page

### Expected behaviour
Nothing happens

### Actual behaviour
Refresh web page was success
But mysql have one process higt cpu load

### Server configuration

**Operating system**: Ubuntu 18.04 lts

**Web server:** openresty/1.15.8.1

**Database:** Mysql 5.7

**PHP version:** PHP 7.3 

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- core/skeleton/Documents/About.odt
		- core/skeleton/Documents/About.txt
		- core/skeleton/Documents/Nextcloud Flyer.pdf
		- core/skeleton/Nextcloud Manual.pdf
		- core/skeleton/Nextcloud.mp4
		- core/skeleton/Nextcloud.png
		- core/skeleton/Photos/Coast.jpg
		- core/skeleton/Photos/Hummingbird.jpg
		- core/skeleton/Photos/Nextcloud Community.jpg
		- core/skeleton/Photos/Nut.jpg
- privacy
	- INVALID_HASH
		- l10n/zh_CN.json

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [core/skeleton/Documents/About.odt] => Array
                        (
                            [expected] => 1cc2eae96696437edac41a8f9bc04a2ce2e8aac132cee19239222ef0f0ed0722a8279d6dae2073c230f9f2015f03559827a4bdd11ac068d2ee31f8bef9ec8b95
                            [current] => 
                        )

                    [core/skeleton/Documents/About.txt] => Array
                        (
                            [expected] => 246d73856029aac8fb5cfda0644c473bcc519017b8284e0b850b67025562170cf4c1afa39f037cff3c9a331f85ab29266353de184c039907a54a680a54c15040
                            [current] => 
                        )

                    [core/skeleton/Documents/Nextcloud Flyer.pdf] => Array
                        (
                            [expected] => 5d290127483c2806b1dfd35b44a67b8481f52568f7005c3a41c6734e78ea7040bb96e8e749d470f371a655e748942ce027d3193020bee4517dc0600f147fd798
                            [current] => 
                        )

                    [core/skeleton/Nextcloud Manual.pdf] => Array
                        (
                            [expected] => cdd8d2cee67200738fc1806d1dece5bfb3c9f774d477c4f5778305eff0949a7d39803867ec3713d680f90103337c2348774840a9f5650990d8a958e3cad78641
                            [current] => 
                        )

                    [core/skeleton/Nextcloud.mp4] => Array
                        (
                            [expected] => 20629a6a9e8750beac07541c77e8e694fb527cc653f2d6626d73c7381070726af4062169010947229e1b904e56308928e4897e31a7809bddd70dd2027ef5471a
                            [current] => 
                        )

                    [core/skeleton/Nextcloud.png] => Array
                        (
                            [expected] => d2e57f96215bda00e76679310745108d7d3911102a03e45f392a0eedb857f00167c824c06d7bce1069048cdbc3756a84466313ba317f311dbefa8ce5b1d6cb0c
                            [current] => 
                        )

                    [core/skeleton/Photos/Coast.jpg] => Array
                        (
                            [expected] => 2bb4fd0ca9fbcb71b3565f1c019233aac9d22d19e25a6c1afe1ba37dbe33a2d282ead22aafd6e5a012bb206c9606f1056d9f83955034a11d2c531d435f097933
                            [current] => 
                        )

                    [core/skeleton/Photos/Hummingbird.jpg] => Array
                        (
                            [expected] => 4c5c440aabadb7bc084502513f34691754ad0cd5b7dc60af5294c5076e17e102d209b2fec4d1a1f38b940887c6f8eb16efa9240944116d17e6c4a36689987d84
                            [current] => 
                        )

                    [core/skeleton/Photos/Nextcloud Community.jpg] => Array
                        (
                            [expected] => 6ce4c89f1798c4c0233aa0701e7fbbaea5606c81e6060076dca3987c025552102a2381802e66a572ab98874dd876ee67758d8c7d5d53c496948ccaec9811031d
                            [current] => 
                        )

                    [core/skeleton/Photos/Nut.jpg] => Array
                        (
                            [expected] => 0a82a718fc89d438c5887bac2b4fe7f32ec39a3cf9aab38e7f544ed8493d328d2247fa4efa85d4caa650550c34f305ba7eb12973d2487e10507cb2ab0f38c122
                            [current] => 
                        )

                )

        )

    [privacy] => Array
        (
            [INVALID_HASH] => Array
                (
                    [l10n/zh_CN.json] => Array
                        (
                            [expected] => 66cc7e57591d8687b9c85566b776c4ea4cad4cad84f9461a0c09400e19e8927bc6590b44afd4ea866770a950d8403622ce8e3af7de38eb01e4b06254ce7cdee1
                            [current] => 3e2a6b3647a5aea8a4b41b5492f5df614761d1470bdd798165f0ff73a475098bf757319fb9445dc76e31b61fdd1bdd004b5e6613a956857416a0f7fa14fc26c9
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - cloud_federation_api: 0.2.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.3.0
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - support: 1.0.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - workflowengine: 1.6.0
Disabled:
  - comments
  - encryption
  - federation
  - files_external
  - gallery
  - sharebymail
  - survey_client
  - systemtags
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'maintenance' => false,
  'dbtype' => 'mysql',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbuser' => 'root',
  'dbpassword' => 'xxxxxxxxxxxxxx',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0.0,
    'password' => 'xxxxxx',
    'dbindex' => 1,
  ),
  'default_language' => 'zh_CN',
  'default_locale' => 'zh_Hans_CN',
  'logtimezone' => 'Asia/Shanghai',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 0,
  'instanceid' => 'ocyxxxxxm',
  'passwordsalt' => 'uWAeakxxxxxxxxxxxxeTxxxxx',
  'secret' => 'UHGGBxxxxxxxxiba0DwNxxxxxxxxxxns',
  'trusted_domains' =>
  array (
    0 => 'xxxxxxxxxxx',
  ),
  'datadirectory' => '/data/www/nextcloud/data',
  'version' => '16.0.1.1',
  'overwrite.cli.url' => 'https://paxxn.xxxxxxxx.cn',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'xxxxxxxxxxxxxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxxxxxxxxx',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'xxxxxxxxxxxxxxx',
  'mail_smtppassword' => 'xxxxxxxxxxxx',
);

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO 

### Client configuration
**Browser:**
Chrome 75 64bit

**Operating system:**
Windows 10 1903

#### Web server error log
<details>
<summary>Web server error log</summary>

```
NONE
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
NONE
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
NONE
```
</details>

### Other message

- All files are stored in admin user

#### run cmd `du`
<details>
<summary>run cmd du</summary>

```
www@server:/data/www/nextcloud/data/admin$ du -sh *
0	cache
3.0T	files
59G	files_trashbin
112M	files_versions
0	uploads
```
</details>

#### count the table `oc_filecache`
<details>
<summary>count table oc_filecache</summary>

```
mysql> select count(1) from oc_filecache;
+----------+
| count(1) |
+----------+
|  1822207 |
+----------+
1 row in set (0.49 sec)
```
</details>

#### When I refresh the page multiple times
<details>
<summary>When I refresh the page multiple times</summary>

```
mysql> show processlist;
+-------+------+-----------+-----------+---------+------+---------------------+------------------------------------------------------------------------------------------------------+
| Id    | User | Host      | db        | Command | Time | State               | Info                                                                                                 |
+-------+------+-----------+-----------+---------+------+---------------------+------------------------------------------------------------------------------------------------------+
| 17722 | root | localhost | NULL      | Query   |    0 | starting            | show processlist                                                                                     |
| 19929 | root | localhost | nextcloud | Sleep   | 2084 |                     | NULL                                                                                                 |
| 19953 | root | localhost | nextcloud | Query   |    4 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 13)) AND ((`f`.`mimetype` <> 2)  |
| 19999 | root | localhost | nextcloud | Query   |    3 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 13)) AND ((`f`.`mimetype` <> 2)  |
| 20047 | root | localhost | nextcloud | Query   |    2 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 13)) AND ((`f`.`mimetype` <> 2)  |
| 21455 | root | localhost | nextcloud | Query   |    3 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
| 21459 | root | localhost | nextcloud | Query   |    1 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
| 21548 | root | localhost | nextcloud | Query   |    5 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
| 22675 | root | localhost | nextcloud | Query   |    3 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
| 22731 | root | localhost | nextcloud | Query   |    3 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
| 22743 | root | localhost | nextcloud | Query   |    1 | Creating sort index | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
| 23225 | root | localhost | nextcloud | Query   |    0 | Sending data        | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
| 23239 | root | localhost | nextcloud | Query   |    1 | Sending data        | SELECT `f`.* FROM `oc_filecache` `f` WHERE (`f`.`storage` IN (2, 2, 12)) AND ((`f`.`mimetype` <> 2)  |
+-------+------+-----------+-----------+---------+------+---------------------+------------------------------------------------------------------------------------------------------+
13 rows in set (0.00 sec)


```
</details>

**Comment by kesselb** [comment] 2019-06-27 12:08
Duplicate of #15995

Thank you for reporting this issue :+1: I'm closing this one in favour of #15995

**Closed by kesselb** 2019-06-27 12:08 UTC
Labels: 0. Needs triage, bug
