### ISSUE TITLE
Please, remove "Alternative Logins" label from login page

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/server#8813] opened 2018-03-13 23:37 UTC
"Alternative Logins" does not like very much users. Could you remove it?

**Comment by blizzz** [comment] 2018-03-14 09:11
Please describe what the issue is.

**Comment by MorrisJobke** [comment] 2018-03-14 09:28
> "Alternative Logins" does not like very much users. Could you remove it?

They only occur once you enable an alternative login - for example the registration app. What apps do you have enabled?

**Comment by danielepercivaldi** [comment] 2018-03-14 09:35
Well, I know. I’ve installed “Registration”.
Users does not like that useless label, someone tried to clic on it and said “It doesn’t work”.
In my opinion, that label does not add any information or value. And I think it does not  get to do nothing with the user interface. Tha’s all.

Thanks


















Daniele Percivaldi
System Administrator

T. +39 039 96.34.700 +39 039 96.34.750 +39 039 28.45.774

[cid:logo1_b1437559-b736-43a6-abb1-6a9828d9cd73.png]
http://www.intre.it <http://www.intre.it>               [cid:facebook_a4864feb-7f42-4a8b-af9e-1846e45b1c5f.png] <https://www.facebook.com/Intre-840041616113021/?fref=ts> [cid:twitter_00946f12-0249-4097-a714-abb643cdb85e.png] <https://twitter.com/intre_it> [cid:linkedin_08088200-cbf7-442c-9517-45623d32c44c.png] <https://www.linkedin.com/company/intr-> [cid:behance_0e52d3de-d61a-4239-afe9-1c323a8965da.png] <https://www.behance.net/thanksdesign>

Nota informativa: In ottemperanza della Legge 196/2003 sulla tutela dei dati personali, le informazioni contenute in questo messaggio sono strettamente riservate e sono esclusivamente indirizzate al destinatario indicato (oppure alla persona responsabile di rimetterlo al destinatario), tenendo presente che qualsiasi uso, riproduzione o divulgazione di questo messaggio e' vietata. Nel caso in cui aveste ricevuto questa e-mail per errore, vogliate avvertire il mittente al piu' presto a mezzo posta elettronica e distruggere il presente messaggio.

Please note: This email transmission including its attachments, are intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any views or opinions are solely those of the author and do not necessarily represent those of Intré S.r.l., unless specifically stated. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this email in error, please contact the sender and delete the email transmission immediately.
Da: Morris Jobke <notifications@github.com>
Inviato: mercoledì 14 marzo 2018 10:29
A: nextcloud/server <server@noreply.github.com>
Cc: Percivaldi Daniele <d.percivaldi@intre.it>; Author <author@noreply.github.com>
Oggetto: Re: [nextcloud/server] Please, remove "Alternative Logins" label from login page (#8813)


"Alternative Logins" does not like very much users. Could you remove it?

They only occur once you enable an alternative login - for example the registration app. What apps do you have enabled?

**Comment by MorrisJobke** [comment] 2018-03-14 09:56
Just that everybody is on the same page: We are talking about the "Alternative Anmeldung" in this screen shot:

![bildschirmfoto 2018-03-14 um 10 55 33](https://user-images.githubusercontent.com/245432/37395325-4a1abc84-2776-11e8-891f-1e613fed931f.png)

And yes it should just be removed.

Other opinions @nextcloud/designers ? Otherwise I would remove the label.

**Comment by MorrisJobke** [comment] 2018-03-14 10:40
Fix is in #8818

**Comment by jancborchardt** [comment] 2018-03-14 11:46
Thanks for this design detail feedback @danielepercivaldi! Keep it coming :)

**Closed** 2018-03-14 12:52 UTC
Labels: design, papercut
