### ISSUE TITLE
Empty (zero-bytes) files when sharing specific files over federation

### ISSUE THREAD

**Issue by SnejPro** [nextcloud/server#24026] opened 2020-11-10 12:04 UTC
### Steps to reproduce
1. Install two clean nextcloud installations
2. Share a Folder via federation between both installations
3. If you download on the other installation via client or webbrowser, some files (Example: [https://cloud.snejp.de/s/xsAb4LTL7g9SA3q](https://cloud.snejp.de/s/xsAb4LTL7g9SA3q)) will be empty.
4. On the "source" installation it is possible to download the file normaly

### Expected behaviour
The correct files should be downloaded.

### Actual behaviour
Zero-byte files will be downloaded

### Server configuration (both Server)

**Operating system:**
Debian 10

**Web server:**
nginx/1.14.2

**Database:**
10.3.25-MariaDB-0+deb10u1 Debian 10

**PHP version:**
PHP 7.3.19-1~deb10u1 (fpm-fcgi) (built: Jul  5 2020 06:46:45)

**Nextcloud version:** (see Nextcloud admin page)
20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
zip via installation wizard

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "88.198.121.103"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "http:\/\/88.198.121.103",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logfile": "nextcloud.log",
        "loglevel": 0,
        "logdateformat": "Y-m-d H-i-s"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox

**Operating system:**
Win10 Pro x64 1909

### Access to test installations
I've set up two test installations. I can grant you access for debugging.

#### Clientlog (from production system - not from the test installations)
[https://cloud.snejp.de/s/LJNgm5RM4s5oaQY](https://cloud.snejp.de/s/LJNgm5RM4s5oaQY)
As you can see the error files are mostly txt or svg files.

#### Web server and nextcloud error log
[https://cloud.snejp.de/s/t27BHN6iQysaXmR](https://cloud.snejp.de/s/t27BHN6iQysaXmR)

**Comment by SnejPro** [comment] 2020-11-19 22:36
Still in NC 20.0.2

**Comment by martink2** [comment] 2020-12-28 15:21
Also have an instance 20.0.4 where this happens. For us it is mostly happening with files endig with .html.

**Comment by SnejPro** [comment] 2020-12-28 15:58
> 
> 
> Also have an instance 20.0.4 where this happens. For us it is mostly happening with files endig with .html.

For me svg-Files are affected mostly. They are also xml.

**Comment by esprit-libre** [comment] 2021-01-13 13:49
> > Also have an instance 20.0.4 where this happens. For us it is mostly happening with files endig with .html.
> 
> For me svg-Files are affected mostly. They are also xml.

Exactly the same for svg and xml with NC20.0.4

The consequence is that block nextcloud-client 3.1.1 sync on user's desktop (the one that receive the share) because of this 0 size but 372ko expected...

**Comment by kartoffelheinz** [comment] 2021-02-15 12:48
Still in NC 20.0.7 for .svg/.xml Files.

**Comment by erikvanoosten** [comment] 2021-03-07 07:48
I have the same problem for a .svg file in 21.0.0.

The file is correctly stored on disk. Size is correctly reported by Nextcloud UI but it shows no preview icon and can not be downloaded. Also syncing reports an error about wrong file size.

**Comment by getle87** [comment] 2021-04-16 10:29
Same issue under 20.0.9 for .svg/.xml files. If the file size is not bigger than 68 bytes, the I can download the files. The content of the file doesn't matter. If I rename the extension to .md for example it works as expected.

**Comment by bjoernv** [comment] 2021-05-13 21:03
The problem seems to be related to server setup.

I see the issue with 0 byte .svg/.xml files on the following setup:
- Ubuntu 18.04.5 LTS
- Apache 2.4.29
- PHP 7.4.18
- PHP/FPM
- SSL

I tested on a more recent setup. The issue is not present there:
- openSUSE Tumbleweed 20210511
- Apache 2.4.46
- PHP 7.4.19
- PHP/FPM
- no SSL

With Wireshark I also watched the communication between the two Nextcloud instances on openSUSE Tumbleweed when downloading the .svg/.xml files. Everything looks good there. To make this work I had to make a small change to allow federation without https:

```
nextcloud1/apps/federatedfilesharing/lib/Notifications.php_
	protected function tryHttpPostToShareEndpoint($remoteDomain, $urlSuffix, array $fields, $action="share") {
		if ($this->addressHandler->urlContainProtocol($remoteDomain) === false) {
			//$remoteDomain = 'https://' . $remoteDomain;
                        $remoteDomain = 'http://' . $remoteDomain;
		}
```

**Comment by enoch85** [comment] 2021-06-17 09:47
We added this in the Nextcloud VM to easily check for 0-byte files: 

https://github.com/nextcloud/vm/pull/2026

**Comment by bjoernv** [comment] 2021-06-18 09:24
As we all wonder, why only certain file types are affected, I looked into my Apache configuration and found:

```
<IfModule mod_deflate.c>
        <IfModule mod_filter.c>
                AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css
                AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
                AddOutputFilterByType DEFLATE application/rss+xml
                AddOutputFilterByType DEFLATE application/xml
        </IfModule>
</IfModule>
```

SVG is not there in the configuration, but Nextcloud delivers .svg files as text/plain.

It is certain, that the Nextclound HTTP Client (or better the "Nextcloud Server Crawler") does not correctly processes files from other federation Nextcloud servers, if they are delivered with Gzip HTTP transport compression. As the Nextcloud HTTP Client requests Gzip compression, this is clearly a bug.

With that information in mind I found some solutions to work-around the problem. All solutions are working for me.

### Disable mod_deflate in Apache
This works, but affects the whole server. Do this at least on the source Nextcloud server (where the files are stored).

### Disable Gzip for Nextcloud section in Apache
It is possible to disable Gzip only for the Nextcloud directory. Do this at least on the source Nextcloud server (where the files are stored). Depending on your setup this works like this:

```
<Directory /path/to/your/nextcloud/>
    SetEnv no-gzip 1
</Directory>
```

### Disable Gzip only for the Nextcloud HTTP Client

With the following patch the Nextcloud HTTP Client does not request Gzip compression anymore. Keep in mind, that you may have to disable Nextcloud signing check by modifying the $OC_Channel variable in version.php. Do this at least on the target Nextcloud server (where the files are requested from another Nextcloud federation server).

```
--- lib/private/Http/Client/Client.php     2021-04-08 15:24:10.000000000 +0200
+++ lib/private/Http/Client/Client.php  2021-06-18 11:15:31.837728698 +0200
@@ -91,7 +91,7 @@
                }
 
                if (!isset($options[RequestOptions::HEADERS]['Accept-Encoding'])) {
-                       $options[RequestOptions::HEADERS]['Accept-Encoding'] = 'gzip';
+                       // $options[RequestOptions::HEADERS]['Accept-Encoding'] = 'gzip';
                }
 
                return $options;
```

**Comment by bjoernv** [comment] 2021-06-19 10:02
Sorry, but we need Http/Client devs here to solve this serious synchronization bug. Could you please take a look at this bug @blizzz @LukasReschke @rullzer @ChristophWurst @acsfer @nickvergessen @MorrisJobke @mlatief @kesselb @danxuliu?

**Comment by SnejPro** [comment] 2021-06-19 14:40
> 
> 
> As we all wonder, why only certain file types are affected, I looked into my Apache configuration and found:
> 
> ```
> <IfModule mod_deflate.c>
>         <IfModule mod_filter.c>
>                 AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css
>                 AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
>                 AddOutputFilterByType DEFLATE application/rss+xml
>                 AddOutputFilterByType DEFLATE application/xml
>         </IfModule>
> </IfModule>
> ```
> 
> SVG is not there in the configuration, but Nextcloud delivers .svg files as text/plain.
> 
> It is certain, that the Nextclound HTTP Client (or better the "Nextcloud Server Crawler") does not correctly processes files from other federation Nextcloud servers, if they are delivered with Gzip HTTP transport compression. As the Nextcloud HTTP Client requests Gzip compression, this is clearly a bug.
> 
> With that information in mind I found some solutions to work-around the problem. All solutions are working for me.
> ### Disable mod_deflate in Apache
> 
> This works, but affects the whole server. Do this at least on the source Nextcloud server (where the files are stored).
> ### Disable Gzip for Nextcloud section in Apache
> 
> It is possible to disable Gzip only for the Nextcloud directory. Do this at least on the source Nextcloud server (where the files are stored). Depending on your setup this works like this:
> 
> ```
> <Directory /path/to/your/nextcloud/>
>     SetEnv no-gzip 1
> </Directory>
> ```
> 
> ### Disable Gzip only for the Nextcloud HTTP Client
> 
> With the following patch the Nextcloud HTTP Client does not request Gzip compression anymore. Keep in mind, that you may have to disable Nextcloud signing check by modifying the $OC_Channel variable in version.php. Do this at least on the target Nextcloud server (where the files are requested from another Nextcloud federation server).
> 
> Alternativ kann man auch diesen Commit [8bcd1c3](https://github.com/nextcloud/server/commit/8bcd1c31da7a02e78435aa49508ed3787b11867d) rückgängig machen.
> 
> ```
> --- lib/private/Http/Client/Client.php     2021-04-08 15:24:10.000000000 +0200
> +++ lib/private/Http/Client/Client.php  2021-06-18 11:15:31.837728698 +0200
> @@ -91,7 +91,7 @@
>                 }
>  
>                 if (!isset($options[RequestOptions::HEADERS]['Accept-Encoding'])) {
> -                       $options[RequestOptions::HEADERS]['Accept-Encoding'] = 'gzip';
> +                       // $options[RequestOptions::HEADERS]['Accept-Encoding'] = 'gzip';
>                 }
>  
>                 return $options;
> ```

Thanks for your replay. Disableing gzip in nginx solved the problem for now.

**Comment by bjoernv** [comment] 2021-06-19 17:03
@SnejPro wrote:
> Thanks for your replay. Disableing gzip in nginx solved the problem for now.

Unfortunately disabling gzip in Apache/Nginx is more a work-around than a solution. There are many use-cases, were this work-around is not possible. Especially if the source NC server (where the origin files are shared to federated users) is not under your control, then you can't disable Gzip there.

That's why we need a patch (e.g. see "Disable Gzip only for the Nextcloud HTTP Client", reverting commit https://github.com/nextcloud/server/commit/8bcd1c31da7a02e78435aa49508ed3787b11867d or a better patch).

**Comment by LukasReschke** [comment] 2021-06-21 11:19
> Sorry, but we need Http/Client devs here to solve this serious synchronization bug. Could you please take a look at this bug 

Please do not mention a ton of random contributors on files to get bugs prioritized or email them directly. This is not the right way to solve things :) - If you believe a specific code path causes issues opening a Pull Request with a descriptive issue description would be a better first step.

That said, my first hunch would be that your cURL/PHP combination probably does not support GZip and thus the response is never decoded. As per https://www.php.net/manual/en/function.curl-setopt.php:

> CURLOPT_ENCODING The contents of the "Accept-Encoding: " header. This enables decoding of the response. Supported encodings are "identity", "deflate", and "gzip". If an empty string, "", is set, a header containing all supported encoding types is sent.       

https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html seems to support this.

So I wonder if setting `CURLOPT_ENCODING` to an empty value would be a more portable solution. I don't have the time to dive into this, but something like this should probably work (ref https://docs.guzzlephp.org/en/stable/faq.html#how-can-i-add-custom-curl-options)"

```diff
- $options[RequestOptions::HEADERS]['Accept-Encoding'] = 'gzip';
+ $options['curl'][CURLOPT_ENCODING] = '';
```

(Pull Request with test plan is welcome 😉 )

**Comment by bjoernv** [comment] 2021-06-22 09:22
> Please do not mention a ton of random contributors on files to get bugs prioritized or email them directly. This is not the right way to solve things :) - If you believe a specific code path causes issues opening a Pull Request with a descriptive issue description would be a better first step.

Right, but there was no developer interest for this serious synchronization bug since ~6 months. I have no Pull Request currently.

> > CURLOPT_ENCODING The contents of the "Accept-Encoding: " header. This enables decoding of the response. Supported encodings are "identity", "deflate", and "gzip". If an empty string, "", is set, a header containing all supported encoding types is sent.
> 
> https://curl.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html seems to support this.

I found in NC source code and in the [docs of the 3rdparty library guzzlehttp](https://docs.guzzlephp.org/en/stable/request-options.html#decode-content) the option `decode_content` which is enabled per default. There is only one place in NC where this option is explicitly disabled (3rdparty/microsoft/azure-storage-common). It's still unclear, why decoding gzip compressed content fails for GETting files in "Nextcloud Server crawler".

**Comment by bjoernv** [comment] 2021-06-30 21:42
BTW, there is a hint in section [Troubleshooting Web server and PHP problems](https://docs.nextcloud.com/server/latest/admin_manual/issues/general_troubleshooting.html#troubleshooting-web-server-and-php-problems) of the admin manual, that Apache modules like mod_deflate and others are known to cause various problems like broken up-/downloads.

**Comment by szaimen** [comment] 2021-08-08 13:59
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

**Comment by bjoernv** [comment] 2021-08-09 19:41
> Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

I tested again with NC 21.0.4 and 22.1.0. NC 21.0.4 still shows the bug. NC 22.1.0 seems to work fine. But which change has fixed the bug? Changelog shows that guzzlehttp library has been updated. But even with downgraded guzzlehttp the bug is gone. May be a Git bisect helps.

**Comment by KGremmer** [comment] 2021-09-02 06:59
Upgraded from 21.0.3 to 21.0.4 same Problem.
I uploaded in the Attachment the Debug-Logs
Next month i will upgrade to 22.1.0 and hopefully the bug is gone


[Logs Sender-Server of TXT-Files.txt](https://github.com/nextcloud/server/files/7096759/Logs.Sender-Server.of.TXT-Files.txt)

[Logs Receiver-Server of TXT-Files.txt](https://github.com/nextcloud/server/files/7096761/Logs.Receiver-Server.of.TXT-Files.txt)

**Comment by becbe** [comment] 2021-11-11 13:16
Has this issue been fixed in NC 22?

@KGremmer 
Did you already install NC 22? If so, what is your experience?

**Comment by KGremmer** [comment] 2021-11-11 13:24
I updated last week to 22.2.0.
This version fixed it for me.
I can now download txt-file from the browser and with the client.

**Comment by szaimen** [comment] 2021-11-12 00:00
So can we close his issue then?

**Comment by bjoernv** [comment] 2021-11-12 08:55
> So can we close his issue then?

Until support for the affected Nextcloud 20 and 21 versions ends, I would not close this bug.

**Comment by szaimen** [comment] 2022-11-26 14:01
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by nextcloud-command** [comment] 2023-01-11 01:11
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Closed** 2023-03-06 13:42 UTC
Labels: bug, needs info, feature: federation, 0. Needs triage
