### ISSUE TITLE
LDAP Searches in Sharing Returning Duplicates and Disabled User Objects

### ISSUE THREAD

**Issue by mac-tech** [nextcloud/server#12229] opened 2018-11-02 20:54 UTC
Nextcloud 14 in production here.

Users are synchronized from AD/LDAP, Groups enabled. Logins work well, sharing to within and outside the domain does as well.

When sharing files and folders, the autocomplete for user/group objects populates with every user and group object both the entire LDAP domain and local users which leads to duplicates in the list. Also, disabled LDAP accounts still show up (we move disabled LDAP accounts under another OU but keep them to prevent recycling of identical usernames and email addresses). 

An LDAP search constraint, either filtering disabled users and/or with a limited search subtree would prevent disabled user accounts from showing up (and admins from receiving calls from irritated users).

**Comment by skjnldsv** [comment] 2020-04-10 08:23
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 08:23 UTC
Labels: 0. Needs triage, bug, feature: ldap
