### ISSUE TITLE
Preview Korean characters

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#28251] opened 2021-07-29 14:55 UTC
https://github.com/nextcloud/ios/issues/1652

![127308065-a59a4cd7-d4f6-4925-80b6-d6b23e2f511c](https://user-images.githubusercontent.com/8616947/127514755-105436be-f72c-4179-83f9-fe099f98f180.png)

**Comment by juliushaertl** [comment] 2021-07-30 05:53
Duplicate of https://github.com/nextcloud/server/issues/4198

https://github.com/nextcloud/server/pull/25529 for additional technical details.

**Closed by juliushaertl** 2021-07-30 05:53 UTC
