### ISSUE TITLE
Starring a "Recent" file triggers a download instead

### ISSUE THREAD

**Issue by zinks-** [nextcloud/server#4568] opened 2017-04-27 20:24 UTC
### Steps to reproduce
1. In the Files app, open the "Recent" files list from the left menu
2. Open the "Details" panel for any file
3. Click the star to add the file to your favorite

### Expected behaviour
The file should be favorited.

### Actual behaviour
The file is not favorited and the browser is prompted to download the file.

### Server configuration

**Operating system**: Debian 8 "Jessie"

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** update from 11.0.2

**Where did you install Nextcloud from:** zip file from nextcloud.com

### Enabled apps
  - activity: 2.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1   
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

### Client configuration
**Browser:** Firefox 52.0.1

**Operating system:** Open Suse Leap 42.2

**Comment by MorrisJobke** [comment] 2017-04-29 04:12
cc @icewind1991

**Comment by MorrisJobke** [comment] 2017-11-14 15:01
cc @nextcloud/javascript

**Comment by danxuliu** [comment] 2018-01-04 03:42
This happens on current master too.

The problem is that [the _Favorite_ file action is added only to some of the file lists](https://github.com/nextcloud/server/blob/c047f32f25a9c1448bf78ef65d5144f5b882b719/apps/files/js/tagsplugin.js#L224-L230), but [the icon in the details view is shown unconditionally](https://github.com/nextcloud/server/blob/599274f5096d04f63b95bd97b521963ef14a4ae1/apps/files/js/mainfileinfodetailview.js#L23-L25) for every file list, so when it is clicked and [the _Favorite_ action is tried to be triggered](https://github.com/nextcloud/server/blob/599274f5096d04f63b95bd97b521963ef14a4ae1/apps/files/js/mainfileinfodetailview.js#L128) it is not found and [the _Download_ action is executed instead](https://github.com/nextcloud/server/blob/c059fbd409b088f65922354149f6d2fd9b5d01b3/apps/files/js/fileactions.js#L481-L483).

This could be fixed by showing the icon in the details view only when there is a _Favorite_ file action available.

Another option would be to add the _Favorite_ action to every file list, although the conditional rendering of the icon should be added anyway to make the behaviour more robust.

**Comment by MorrisJobke** [comment] 2018-01-08 14:43
Fixed by #7716

**Closed by MorrisJobke** 2018-01-08 14:43 UTC
Labels: 1. to develop, bug, feature: files, papercut
