### ISSUE TITLE
Some contact birthdays shown multiple times

### ISSUE THREAD

**Issue by danielbierstedt** [nextcloud/server#1854] opened 2016-10-22 10:34 UTC
Steps to reproduce

I have no idea how to reproduce that. The source is an exported file from Owncloud.

Expected behaviour

One event shown per contact that has a birthday, anniversary or similar filled in the contacts.

Actual behaviour

Some contacts have 3 calendar events for a birthday, some have only one. The contact does not have duplicates, a sync to my mobile using caldav shows only one event for those, that show 3 in the webinterface.

Server configuration

Operating system: Synology: Linux / NAS

Web server: Apache

Database: MariaDB

PHP version: 5.6

Server version: (see your admin page) 10.0.1

Calendar version: (see the apps page) 1.4.0

Updated from an older installed version or fresh install: Fresh install

Signing status (ownCloud/Nextcloud 9.0 and above): No idea what that means...

Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

List of activated apps:
Activity
Collaborative tags
Comments
Deleted files
Federation
File sharing
First run wizard
Gallery
Notifications
Password policy
PDF viewer
Provisioning API
Server info
Text editor
Theming
Update notification
Usage report
Versions
Video player
Calendar
Contacts

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
The content of config/config.php:

<?php
$CONFIG = array (
'instanceid' => '***********_',
'passwordsalt' => '**_***********_',
'secret' => '**_*******_',
'trusted_domains' =>
array (
0 => 'nas.mydomain.de',
),
'datadirectory' => '/path/to/data',
'overwrite.cli.url' => 'https://**_***********_/nextcloud',
'dbtype' => 'mysql',
'version' => '9.1.1.5',
'dbname' => 'dbname',
'dbhost' => 'localhost',
'dbport' => '',
'dbtableprefix' => 'oc_',
'dbuser' => 'dbuser',
'dbpassword' => 'password',
'logtimezone' => 'UTC',
'installed' => true,
'mail_smtpmode' => 'smtp',
'mail_smtpsecure' => 'tls',
'mail_from_address' => '**_***_',
'mail_domain' => 'gmail.com',
'mail_smtpauthtype' => 'LOGIN',
'mail_smtpauth' => 1,
'mail_smtphost' => 'smtp.gmail.com',
'mail_smtpport' => '587',
'mail_smtpname' => '**_*****_',
'mail_smtppassword' => '**_*****',
'defaultapp' => 'calendar',
);

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
Are you using encryption: no

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your instance's installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT \* FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
Client configuration

Browser: Chrome

Operating system: Windows

CalDAV-clients: Windows / Linux -> Thunderbird Inverse SoGo Connector, Android -> EasyDAV

Logs

Web server error log

Insert your webserver log here
Log file (data/owncloud.log)

Insert your ownCloud.log file here
To long to paste:

https://nas.danielbierstedt.de:5001/sharing/8omF2ZDL7

Browser log

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

**Comment by oswolf01** [comment] 2016-11-15 13:32
Same happened to me, maybe i know how to reproduce.
I had a buggy vcf File that i had to imports at least a dozen times b4 it finaly worked.
Sometimes i deleted the whole contacts, sometims i deleted just single entrys.
It seams to me like the entys for the complete delete somehow remain in the calendar, while the ones i deleted one by one dissapeard.

**Comment by matzex** [comment] 2016-12-28 22:43
Same problem here, after deleting the whole addressbook and importing a backup of it all birthdays are shown multiple times.

**Comment by danielbierstedt** [comment] 2016-12-29 11:43
As a workaround, I deleted the contacts birthdays calendar and re-created it. Cannot remember the occ command to do this right now...

**Comment by MorrisJobke** [comment] 2017-01-31 02:29
Sadly this can only be fixed by removing the calendar and add it again as described above. The cause is fixed.

**Closed by MorrisJobke** 2017-01-31 02:29 UTC
Labels: bug, feature: dav
