### ISSUE TITLE
[Bug]: Theming issues due to theming apps not being uninstalled in a clean way

### ISSUE THREAD

**Issue by HannesJo0139** [nextcloud/server#36860] opened 2023-02-25 14:52 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I just switched to light theme and noticed that icons are barely visible now as you can see in the screenshot attached. Strange thing is on a test instance I am not able to reproduce the issue. 

On main instance for some reason it sets `[data-themes*=dark]` and so icons for the dark theme are being loaded. The test instance sets `[data-themes*=light]` what seems to be correct. Any idea how to debug it?

Barely visible icons:
<img width="1267" alt="Bildschirm­foto 2023-02-25 um 15 36 27" src="https://user-images.githubusercontent.com/42114183/221363083-1009e76c-234d-4827-8e07-70c9d752223d.png">

Icons being loaded via `[data-themes*=dark]`:
<img width="1267" alt="Bildschirm­foto 2023-02-25 um 15 39 41" src="https://user-images.githubusercontent.com/42114183/221363093-3333e2d0-e92a-48e7-aaac-5c7994f9343e.png">

Correct icons on test instance, being loaded via `[data-themes*=light]`:
<img width="1267" alt="Bildschirm­foto 2023-02-25 um 15 41 01" src="https://user-images.githubusercontent.com/42114183/221363103-9096ba34-a293-48b9-92da-c776167a3c66.png">

### Steps to reproduce

Unable to reproduce myself..

### Expected behavior

Having correct icons..

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
root@27d93249669e:/# occ app:list
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.2.4
  - checksum: 1.2.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - external: 5.0.2
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.15.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - imageconverter: 1.3.4
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - oidc_login: 2.4.1
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - previewgenerator: 5.2.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - riotchat: 0.14.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_nextcloud_notification: 3.6.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - breezedark: 25.0.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - dashboard: 7.0.0
  - encryption
  - files_external: 1.10.0
  - photos: 2.0.1
  - suspicious_login
  - user_ldap
  - weather_status: 1.0.0
```

**Comment by szaimen** [comment] 2023-02-25 15:30
Hi, which nc version?

**Comment by HannesJo0139** [comment] 2023-02-26 00:34
25.0.4

**Comment by damu-u** [comment] 2023-03-02 03:37
![icon](https://user-images.githubusercontent.com/7370511/222324804-e7764e64-9bfc-4b18-933d-e4920666c3b8.png)

I have the same problem
25.0.4

**Comment by HannesJo0139** [comment] 2023-03-02 22:49
Tried to do some debugging today. All I can say is after setting up a brand new nc instance, everything is fine. As soon as I recover the database (mariadb), the issue occurs.

**Comment by HannesJo0139** [comment] 2023-03-11 13:51
Had time for a few more tests today. Apparently, the problem is related to a deleted theming app (Breeze-Dark). I no longer use the app and have removed it completely from a user / admin perspective. Nevertheless, the body tag is 

`<body id="body-user" data-theme-breezedark data-theme-light  data-themes=breezedark,light>
`

Editing the body tag so that the breezedark stuff is removed corrects the icon colors. Only the folder sizes are still invisible. So it seems to be an issue about how uninstalled apps are handled by nextcloud. 
Maybe kind of related to 
https://github.com/nextcloud/server/issues/5539
https://github.com/nextcloud/recognize/issues/621

Would be glad if someone could tell how to get rid of the breeze-dark leftovers from my nc instance.

@damu-u Did you use breeze dark too?

----
https://github.com/mwalbeck/nextcloud-breeze-dark/issues/330

**Comment by damu-u** [comment] 2023-03-11 14:56
@HannesJo0139 Yes, I installed the breeze dark theme and then deleted it.

**Comment by HannesJo0139** [comment] 2023-03-11 18:28
Quick and dirty workaround is to edit table _oc_preferences_ in the database by hand. Remove entries where _app_id_ is `theming` and _config_key_ is `enabled-themes`. Amazing how Nextcloud clutters up its database.

**Comment by szaimen** [comment] 2023-03-11 18:41
Duplicate of https://github.com/mwalbeck/nextcloud-breeze-dark/issues/330

**Closed by szaimen** 2023-03-11 18:41 UTC
Labels: bug, 0. Needs triage, 25-feedback

**Comment by HannesJo0139** [comment] 2023-03-11 21:09
> Duplicate of [mwalbeck/nextcloud-breeze-dark#330](https://github.com/mwalbeck/nextcloud-breeze-dark/issues/330)

@szaimen I don't think closing as duplicate is appropriate. The issue is clearly not a breeze-dark issue but a nextcloud one. Nextcloud does not handle app uninstall properly. I opened that 2nd issue at breeze-dark package only so the dev becomes aware of the upstream problem.

**Comment by szaimen** [comment] 2023-03-11 23:26
What you are looking for is a not yet implemented feature: https://github.com/nextcloud/server/issues/5539

**Comment by HannesJo0139** [comment] 2023-03-12 09:35
The feature is another topic. But a deactivated app must not affect my nc instance anymore. If it does, its a bug.
