### ISSUE TITLE
After a user unshares himself from a shared folder, there is no good way to add her back

### ISSUE THREAD

**Issue by bitbonk** [nextcloud/server#21107] opened 2020-05-25 21:27 UTC
A folder is shared with a group. One user of that group accidentally unshares that folder (I tell you, this happens all the time because it is so easy to do!) so it disappears for him. In the details of admin view for that folder "Foo removed themselves" is displayed.

Now there is no way to make that folder reappear for that user. The user can't undo the unshare and all the admin can do is to add the single user back explicitly. But this is rather problematic because now that folder is shared with a group *plus* a single person (that is already a member of that group). If this happens frequently (which it does), it is getting very hard to maintain all the shared folders because they are shared with groups *and* an arbitary list of additional users.

I think the proper way to solve this is to allow the user to undo an unshare just like the user can undo a deletion.

**Comment by martin-77** [comment] 2020-05-27 08:44
I'm not completely sure, but I think the user can find the share inside his trash.

**Comment by lmamane** [comment] 2020-05-27 12:18
No, the user cannot find the share inside his trash. Even sending the user an internal URL (of the kind https://server/index.php/f/NUMBER) to the folder, that URL says "file not found" for that user.

A work-around is to share the folder with that user individually additionally to the group.

**Comment by lmamane** [comment] 2020-05-27 12:33
Another work-around is to have the system-wide Nextcloud admin create a group folder for that group, rather than having an user create the folder and share it with the group. Then, people cannot remove themselves.

**Comment by MorrisJobke** [comment] 2020-10-14 14:06
Duplicate of #23240

**Closed by MorrisJobke** 2020-10-14 14:06 UTC
Labels: 0. Needs triage, bug
