### ISSUE TITLE
`occ preview:pre-generate` crashes on non-image files

### ISSUE THREAD

**Issue by bovender** [nextcloud/server#22157] opened 2020-08-09 08:29 UTC
`occ preview:pregenerate` crashes on non-image files with image file name extensions:

```bash
2020-08-09T08:21:01+00:00 Generating previews for /USER/files/Forschung/Zotero/storage/9UQWKUE2/delete-icon-hover.png
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /var/www/html/lib/private/Files/Filesystem.php:715
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_Image.php(624): OC\Files\Filesystem::file_get_contents('/var/www/html/d...')
#1 /var/www/html/lib/private/Preview/Image.php(52): OC_Image->loadFromFile('/var/www/html/d...')
#2 /var/www/html/lib/private/Preview/GeneratorHelper.php(63): OC\Preview\Image->getThumbnail(Object(OC\Files\Node\File), 4096, 4096)
#3 /var/www/html/lib/private/Preview/Generator.php(235): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\PNG), Object(OC\Files\Node\File), 4096, 4096)
#4 /var/www/html/lib/private/Preview/Generator.php(141): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'image/png', '')
#5 /var/www/html/lib/private/Preview/Generator.php(107): OC\Preview\Generator->generatePreviews(Object(OC\Files\Node\File), Array, 'image/png')
#6 /var/www/html/lib/private/PreviewManager.php(190): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', NULL)
#7 /var/www/html/custom_apps/previewgenerator/lib/Command/PreGenerate.php(205): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#8 /var/www/html/custom_apps/previewgenerator/lib/Command/PreGenerate.php(193): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#9 /var/www/html/custom_apps/previewgenerator/lib/Command/PreGenerate.php(164): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#10 /var/www/html/custom_apps/previewgenerator/lib/Command/PreGenerate.php(132): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/console.php(100): OC\Console\Application->run()
#17 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

In my case, I have lots of files that were downloaded from the Internet by my citation managing software, and many of these files are not what they pretend to be:

For example, the `delete-icon-hover.png` that caused the crash here is not a PNG but rather a HTML file:

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /sd/css/images/delete-icon-hover.png was not found on this server.</p>
</body></html>
```

It would be great if `occ preview:pre-generate` could handle these cases more gracefully and continue with the rest of the files.

---

This happens with the Nextcloud Docker image running in a Docker container:

```
www-data@35e0bb873e81:~/html$ ./occ status
  - installed: true
  - version: 19.0.1.1
  - versionstring: 19.0.1
  - edition:
```

**Comment by matiasdelellis** [comment] 2020-08-10 01:19
Hi,
Dup of https://github.com/nextcloud/server/issues/7276

**Comment by szaimen** [comment] 2021-06-08 09:49
Duplicate of  #7276

**Closed by szaimen** 2021-06-08 09:49 UTC
Labels: 0. Needs triage, bug
