### ISSUE TITLE
Timestamps of files in zip are UTC

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#3855] opened 2017-03-15 19:52 UTC
From our forums (https://help.nextcloud.com/t/zip-downloads-create-timestamps-based-on-universal-time-not-local-time/10094):

> Hi,
> 
> I downloaded a zip file from my nexcloud server and I recognized that the extracted files have a different time. E.G.:
> 
> Webdav displays for one file "Di 26 Apr 2016 09:42:59 CEST"
> The same file from the downloaded zip archive: "Di 26 Apr 2016 08:42:58 CEST"
> 
> What you can see is a difference of one hour. It's on all files.
> 
> I suppose this is coused by different handling of universal and local time. I'm here in Germany so it could fit to my guess.
> 
> This behaviour has side effects. In my case somehow the desktop client wants to sync files again. So I compared the with unision, and I found out, that only some meta data changed, but nothing about the content (I did some tests by md5sum). I was hoping to solve that problem by simply downloading content, and recreating folder sync pairs again, but the desktop clients wants to sync all of the files again! In that case its obviously caused by the time stamp difference, because from the server downloaded files must be identical. This is not going to happen, if I download a file one by one. But for a large data zip downloads suit of course much better.
> 
> Nextcloud version: 11.0.2
> Operating system and version: Ubuntu 14.04
> Apache: Apache/2.4.7 (Ubuntu)
> PHP version: 7.0.15
> Is this the first time you've seen this error?: yes
> OS of client: Linux Mint 18.1
> Nextcloud client: 2.2.4

I was able to reproduce this error on a NC 11.0.2 setup.

**Comment by wiswedel** [comment] 2019-06-12 20:36
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by wiswedel** 2019-06-12 20:36 UTC
Labels: 0. Needs triage, bug, feature: files

**Comment by hidxxx** [comment] 2020-01-16 06:14
Timestamps of files in zip are UTC. 

![nc17 0 2_timestamp_utc_in_zip](https://user-images.githubusercontent.com/5299928/72498449-b8700e00-3872-11ea-8b50-54b1c42e1c3e.png)

Nextcloud version: 17.0.2
