### ISSUE TITLE
OnlyOffice encoding problem with Samba external storage after upgrade from 21.0.0 to 21.0.1

### ISSUE THREAD

**Issue by stfast** [nextcloud/server#26576] opened 2021-04-15 17:07 UTC
### Steps to reproduce
1. NC upgrade from 21.0.0 to 21.0.1
2. Opening .docx with OnlyOffice on NC Samba external storage pops with "Choose TXT options" encoding selection and get scrambled text afterwards
3. Opening same copy of .docx document with OnlyOffice on NC local storage works OK. 

### Expected behaviour
Opening .docx with OnlyOffice on NC Samba external storage should open normaly.

### Actual behaviour
Opening .docx with OnlyOffice on NC Samba external storage pops for "Choose TXT options" encoding selection and get scrambled text afterwards

### Server configuration

**Operating system:**
Fedora 33

**Web server:**
Apache httpd /2.4.46 (Fedora)

**Database:**
MariaDB 10.3

**PHP version:**
PHP 7.4.16 (cli) (built: Mar  2 2021 10:35:17) ( NTS )

**Nextcloud version:** 
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 21.0.0

**Where did you install Nextcloud from:**
Online web update.

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**Comment by szaimen** [comment] 2021-04-15 17:20
Duplicate of https://github.com/nextcloud/server/issues/26457

**Closed by szaimen** 2021-04-15 17:20 UTC
Labels: 0. Needs triage, bug
