### ISSUE TITLE
Theming: contrast improvements for certain color combinations

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3146] opened 2017-01-18 19:18 UTC
So I came across this themed Nextcloud the other day:
![cloud fdp de](https://cloud.githubusercontent.com/assets/925062/22079232/60f5107c-ddbb-11e6-9f98-e9fa49e28b2c.png)

- [ ] »Stay logged in« is white, even though the background is very light – so the text should be dark to provide proper contrast. Maybe the contrast algorithm has to be adjusted for yellow, because it’s a generally light color.
- [ ] The text & arrow of the log in button is black, even though the color of the `.primary` button is very dark. Text should be white hence. ;)

cc @nextcloud/theming

**Comment by eppfel** [comment] 2017-01-18 22:46
Can not reproduce the Login Button issue.
<img width="879" alt="bildschirmfoto 2017-01-18 um 23 41 27" src="https://cloud.githubusercontent.com/assets/1899308/22086242/2c2164aa-ddd8-11e6-9163-99b1d44c53b5.png">

**Comment by DJCrashdummy** [comment] 2017-03-13 12:10
i experienced a similar issue (with the top-bar in the main view) and some other inconsistencies with theming:

i use a **theme** since owncloud 8.x with the main **color #909091 (a kind of dark gray)** and everything looks nice with a **much brighter app- & user-name**.

- last month i changed to nextcloud with the same theme installed and everything looks good but checkboxes and radiobuttons still a kind of "nextcloud-blue"!
- so i tried the theming-app and set #909091 as the color... checkboxes & radiobuttons went gray and additional the several nextcloud-favicons, but the **app- & user-name went a kind of black** (which don't looks as good as with the theme).
- and then i tried to combine them - i know it isn't recommended and the theming-app kind of detects it - but then things got "interesting"...
the theming-app isn't accessible any more, although it overrides the theme and still controls the color of checkboxes, radiobuttons, the various nextcloud-favicons and obviously the app- & user-name since it stays black.

beside the bugs which are at least partly mentioned at other issues, **making the theming-app inaccessible isn't a reasonable solution** since it controls the appearance of nextcloud. and beside that in my point of view **the theme should override app-settings, since you must/should have more knowledge of how things work and what you are doing when using a theme**.

_maybe in future some triggers (either via theme or app) to chose which settings should be deciding would be useful, for some maybe use both theming-possibilities combined, sine the colored favicons are nice but only available via theming-app.
--> this will lead to another problem because the colored nextcloud-icon is used by the app for generic sites..._

**Comment by eppfel** [comment] 2017-04-07 11:11
@DJCrashdummy Sry, no one replied, yet. But can you move this to a new issue? The real problem, it seems, is that the theming app interferes with the custom theme, which is a bug and has to be fixed.

**Comment by eppfel** [comment] 2017-04-07 11:24
@DJCrashdummy I just saw there is a similar issue here #3094

**Comment by jonasgarstick** [comment] 2017-04-20 09:19
We see the same behaviour like @jancborchardt with our own Nextcloud and other themed instances. No custom theming, just via the settings in the theming app.

![nextcloud-login](https://cloud.githubusercontent.com/assets/17829368/25223242/25e95090-25bb-11e7-9b99-a537812d2f5c.png)

**Comment by MorrisJobke** [comment] 2017-05-16 15:11
Nothing for 12 -> move to 13.

**Comment by juliushaertl** [comment] 2017-09-02 19:23
Fixed by the new login design, which works far nicer with theming.

**Closed by juliushaertl** 2017-09-02 19:23 UTC
Labels: 1. to develop, bug, design, feature: theming
