### ISSUE TITLE
[Bug]: Cannot view disabled users

### ISSUE THREAD

**Issue by venator42** [nextcloud/server#43658] opened 2024-02-19 14:41 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If I try to view the disabled users I get the following error message: An error occurred during the request. Unable to proceed.

### Steps to reproduce

1. Open "Users"
2. Click on "Disabled users"

### Expected behavior

A list of disabled users should open

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.de",
            "cloud.domain.intranet",
            "nextcloud.domain.intranet"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "updatedirectory": "\/srv\/nextcloud-updater",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/cloud.domain.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "enable_previews": true,
        "defaultapp": "apporder",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "allow_user_to_change_display_name": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "check_for_working_wellknown_setup": false,
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - appointments: 1.15.5
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.4
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - drawio: 3.0.2
  - drop_account: 2.4.0
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - groupfolders: 16.0.3
  - groupquota: 0.1.12
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.1
  - richdocumentscode: 23.5.705
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.3
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - apporder: 0.11.0 (installed 0.11.0)
  - dashboardcharts: 0.1.3 (installed 0.1.3)
  - data_request: 1.14.0 (installed 1.14.0)
  - encryption: 2.16.0
  - extract: 1.3.5 (installed 1.3.5)
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - fulltextsearch: 20.0.0 (installed 20.0.0)
  - fulltextsearch_elasticsearch: 20.0.0 (installed 20.0.0)
  - impersonate: 1.11.0 (installed 1.11.0)
  - mail: 1.9.3 (installed 1.9.3)
  - quicknotes: 0.8.10 (installed 0.8.10)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - registration: 2.2.0 (installed 2.2.0)
  - twofactor_totp: 10.0.0-beta.2
  - weather: 1.7.6 (installed 1.7.6)
  - workflow_pdf_converter: 1.8.0 (installed 1.8.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

Error from developer tools in Firefox:

```
XHR GET https://cloud.domain.de/ocs/v2.php/cloud/users/disabled?offset=0&limit=25  [HTTP/1.1 404 Not Found 102ms]
```

**Comment by susnux** [comment] 2024-02-20 12:45
> XHR GET https://cloud.domain.de/ocs/v2.php/cloud/users/disabled?offset=0&limit=25  [HTTP/1.1 404 Not Found 102ms]

If the domain is correct and you do not use a subdirectory for Nextcloud then the URL is fine and should not return 404.
Can verify that the domain is correct and you can connect to your cloud using the part before `/ocs`?

**Comment by venator42** [comment] 2024-02-20 13:21
> Can verify that the domain is correct and you can connect to your cloud using the part before `/ocs`?

I can connect to the domain before `/ocs`. 

I should also mention that the cloud is behind an apache reverse proxy, but the other sites `Admins` and `Active Users` are working fine.

I have also another error message from developer tools in firefox from `index.js:44:10`. I will attach the file, maybe it helps.
[nextcloud_error_disabled_users.txt](https://github.com/nextcloud/server/files/14344980/nextcloud_error_disabled_users.txt)

**Comment by joshtrichards** [comment] 2024-02-20 15:08
I can't reproduce this in a stock installation of v28.0.2.

**Comment by joshtrichards** [comment] 2024-02-20 15:08
Can you show your Network tab from the browser console/inspector when trying to do look at the disabled users?

**Comment by susnux** [comment] 2024-02-20 15:26
For me this sounds a lot like a configuration issue with the reverse proxy, make sure to follow the guide:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#reverse-proxy

**Comment by venator42** [comment] 2024-02-21 08:56
> Can you show your Network tab from the browser console/inspector when trying to do look at the disabled users?

Here is a HAR-File from firefox developer tools:
[nextcloud_networktab_firefox_devtools.json](https://github.com/nextcloud/server/files/14356709/nextcloud_networktab_firefox_devtools.json)

Somehow the issue is not happening anymore. It just started to working "magically". I don't know what happened as I didn't changed the configuration or restarted the webservers.

I only added another proxy server into the ```trusted_proxies``` array. The additional proxy server is not in production use right now but is working fundamentally. It is planned for migration in the future. I didn't even accessed the nextcloud via this proxy. Could this be related? If I remove the new entry everything is working further on.

**Comment by nextcloud-command** [comment] 2024-03-23 00:14
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by joshtrichards** [comment] 2024-03-23 03:22
> Somehow the issue is not happening anymore. It just started to working "magically". I don't know what happened as I didn't changed the configuration or restarted the webservers.

Not sure either. I guess we'll keep an eye out for similar reports (and this will be here as a record in case someone searches for a similar matter).

> I didn't even accessed the nextcloud via this proxy. Could this be related? If I remove the new entry everything is working further on.

Not in any way that comes to mind.

I'll close this for now, but can always be revisited if it reoccurs.

**Comment by michael-r-elp** [comment] 2024-04-22 12:54
So after a long time I found the cause of the issue.
If a user was deleted from the ldap server but somehow remains in the nextcloud database and is not being picked up by `occ ldap:show-remnants` then when it tries to get one of the users it gets null returned which somewhere seems to cause a "User does not exist" error.

In order for me to figure out which users where causing the issue I had to modifiy https://github.com/nextcloud/server/blob/deac58ab7ee75e0081dd76af3f756ae4c218d207/lib/private/User/Manager.php#L186
to 
```php
\OC::$server->getLogger()->warning('User not found: \''. $uid .'\'', ['app' => 'debug']);
return null;
```
this way when I open the deactivated user list I could actually see which user caused that error in the log.

After making sure the user being shown in the log does actually not properly exist on nextcloud anymore I manually deleted all remaining database entries in mariadb for that user. Then I just repeat these steps until I eventually was able to see the list of deactivated users again.

It would be great here if in a future update there could be some checks to maybe just skip invalid users when accessing that list or maybe offer some way to have the `occ ldap:show-remnants` command also account for these users.

**Comment by susnux** [comment] 2024-04-22 12:58
> It would be great here if in a future update there could be some checks to maybe just skip invalid users when accessing that list or maybe offer some way to have the occ ldap:show-remnants command also account for these users.

I agree!
This looks like our code needs to be more resilient

**Closed** 2024-04-23 10:38 UTC
Labels: bug, 0. Needs triage, feature: users and groups, 28-feedback

**Comment by papamoose** [comment] 2024-05-06 05:52
Getting the same error. No LDAP involved. Nextcloud is handling the users.

I added the line that michael-r-elp recommended and found the two users it detected I thought I had removed a while back. I guess they were not properly deleted in the past.

I found the tables they were in by grepping through a mysqldump and manually removed them like this. This technique is naive and not sure it's recommended... but after doing this I was able to navigate to the disabled accounts page `settings/users/disabled `.

```
MariaDB [owncloud]> delete from oc_accounts where uid='user1';
MariaDB [owncloud]> delete from oc_calendars where principaluri='principals/users/user1';
MariaDB [owncloud]> delete from oc_group_user where uid='user1';
MariaDB [owncloud]> delete from oc_preferences where userid='user1';
MariaDB [owncloud]> delete from oc_accounts where uid='user2';
```
