### ISSUE TITLE
Apps_paths are blocking nextcloud upgrades

### ISSUE THREAD

**Issue by laurentdinclaux** [nextcloud/server#4670] opened 2017-05-03 00:36 UTC
### Steps to reproduce
1. Notice the 11.0.3 update
2. Launch update

### Expected behaviour
It should update Nextcloud

### Actual behaviour
Immediately stops and throws an error:

```
Check for expected files
The following extra files have been found:
apps.manual
apps.installed
```

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx version 1.10.0-0ubuntu0.16.04.4 

**Database:**
Mysql

**PHP version:**
PHP version 7.0.13

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
ZIP downloaded on offcial website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
# occ app:list
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - audioplayer: 1.5.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.3
  - direct_menu: 0.10.1
  - drawio: 0.8.6
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_downloadactivity: 1.0.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.2.0
  - nextant: 1.0.8
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.5
  - provisioning_api: 1.1.0
  - rainloop: 4.28.1
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_automatedtagging
  - user_external
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocxqcnu4i3nc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.io"
        ],
        "datadirectory": "\/srv\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/domain.io\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "cloudnext",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Pacific\/Noumea",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "trusted_proxies": [
            "10.0.8.10"
        ],
        "overwritehost": "domain.io",
        "overwriteprotocol": "https",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 0,
        "log_rotate_size": 52428800,
        "appstore.experimental.enabled": true,
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "domain.io",
        "ldapUserCleanupInterval": 30,
        "maintenance": false,
        "updater.release.channel": "stable",
        "apps_paths": [
            {
                "path": "\/srv\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/srv\/www\/nextcloud\/apps.installed",
                "url": "\/apps.installed",
                "writable": true
            },
            {
                "path": "\/srv\/www\/nextcloud\/apps.manual",
                "url": "\/apps.manual",
                "writable": false
            }
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP.

### Client configuration
**Browser:** Chrome 58.0.3029.81

**Operating system:** Ubuntu Gnome 16.04

#### Nextcloud updater log (data/update.log)
<details>
<summary>Nextcloud updater log</summary>

```
2017-05-03T11:33:36+1100 xp0YlSJikk [info] updaterServer: https://updates.nextcloud.org/updater_server/
2017-05-03T11:33:36+1100 xp0YlSJikk [info] releaseChannel: stable
2017-05-03T11:33:36+1100 xp0YlSJikk [info] internal version: 11.0.2.7
2017-05-03T11:33:38+1100 xp0YlSJikk [info] getUpdateServerResponse response: Array
(
    [version] => 11.0.3.2
    [versionstring] => Nextcloud 11.0.3
    [url] => https://download.nextcloud.com/server/releases/nextcloud-11.0.3.zip
    [web] => https://docs.nextcloud.com/server/11/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [signature] => w0iy1vyJTo33IgQsr+fS9p+SNS8+VK5DLygY/m2lZi4odWrnu1EHw9yY6L0vQZx3
Twu016evAkProWqbiRpOyplAfgiEZtnElRNf6YfqPJFcoSYDGrHronrBrYZr/1xX
g2VxNQavCYZ5xKerWUyx5XfztURZsKRjd8+wy05AdCdS33JRnft6Z9Plt1i8zeZ9
ZsQVCpfOVzrsFJ50SMLlewKl2ddGnIrn1woPicMA6biM7KKu38QU92L/f/Q4HqqK
nUOMeuRVG/iT7nu4Qz0nzY8uE1GM7rfYiBxsRNTXtsjpzEOo3u4zEvC8jvJl136Q
W0N7qv9mCgCHNclh6gPcTQ==
)

2017-05-03T11:33:38+1100 xp0YlSJikk [info] checkForUpdate() Array
(
    [version] => 11.0.3.2
    [versionstring] => Nextcloud 11.0.3
    [url] => https://download.nextcloud.com/server/releases/nextcloud-11.0.3.zip
    [web] => https://docs.nextcloud.com/server/11/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [signature] => w0iy1vyJTo33IgQsr+fS9p+SNS8+VK5DLygY/m2lZi4odWrnu1EHw9yY6L0vQZx3
Twu016evAkProWqbiRpOyplAfgiEZtnElRNf6YfqPJFcoSYDGrHronrBrYZr/1xX
g2VxNQavCYZ5xKerWUyx5XfztURZsKRjd8+wy05AdCdS33JRnft6Z9Plt1i8zeZ9
ZsQVCpfOVzrsFJ50SMLlewKl2ddGnIrn1woPicMA6biM7KKu38QU92L/f/Q4HqqK
nUOMeuRVG/iT7nu4Qz0nzY8uE1GM7rfYiBxsRNTXtsjpzEOo3u4zEvC8jvJl136Q
W0N7qv9mCgCHNclh6gPcTQ==
)

2017-05-03T11:33:38+1100 xp0YlSJikk [info] end of checkForUpdate() Update to Nextcloud 11.0.3 available. (channel: "stable")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/releases/nextcloud-11.0.3.zip</code>
2017-05-03T11:33:44+1100 oYIAZPgHJX [info] request to updater
2017-05-03T11:33:44+1100 oYIAZPgHJX [info] currentStep()
2017-05-03T11:33:44+1100 oYIAZPgHJX [info] POST request for step "1"
2017-05-03T11:33:44+1100 oYIAZPgHJX [info] startStep("1")
2017-05-03T11:33:44+1100 oYIAZPgHJX [info] checkForExpectedFilesAndFolders()
2017-05-03T11:33:44+1100 oYIAZPgHJX [error] POST request failed with UpdateException
2017-05-03T11:33:44+1100 oYIAZPgHJX [error] Exception: UpdateException
Message: 
Code:0
Trace:
#0 /srv/www/nextcloud/updater/index.php(1114): Updater->checkForExpectedFilesAndFolders()
#1 {main}
File:/srv/www/nextcloud/updater/index.php
Line:354
Data:
Array
(
    [0] => apps.manual
    [1] => apps.installed
)


2017-05-03T11:33:44+1100 oYIAZPgHJX [info] rollbackChanges("1")
2017-05-03T11:33:44+1100 oYIAZPgHJX [info] unlink .step
2017-05-03T11:33:44+1100 oYIAZPgHJX [info] end of  rollbackChanges()
```
</details>

**Comment by MorrisJobke** [comment] 2017-05-03 03:09
Duplicate of https://github.com/nextcloud/updater/issues/40

**Closed by MorrisJobke** 2017-05-03 03:09 UTC
