### ISSUE TITLE
Layout of share suggestions is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#13055] opened 2018-12-13 13:03 UTC
> ![bildschirmfoto von 2018-12-13 13-58-38](https://user-images.githubusercontent.com/213943/49940378-97a2ef80-fedf-11e8-8a62-d3c61442b71b.png)

Current master, no idea when this happened, stable15 is fine

@skjnldsv @juliushaertl ?

**Comment by skjnldsv** [comment] 2018-12-13 13:05
Duplicate of #12832

**Closed by skjnldsv** 2018-12-13 13:05 UTC
Labels: bug, design, feature: sharing

**Comment by nickvergessen** [comment] 2018-12-13 13:08
sorry a quick search didnt bring it up
