### ISSUE TITLE
Error while running background job (OCP\AutoloadNot AllowedException): Autoload path not allowed

### ISSUE THREAD

**Issue by samtygier** [nextcloud/server#10658] opened 2018-08-12 14:30 UTC
### Steps to reproduce
1. I get this on every cron background job run

I've been getting these since July with NC 13.0.4.

### Actual behaviour

Error message:

`{"reqId":"bDXzN4IbgNb6j3plbWNR","level":3,"time":"2018-08-12T10:27:24+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Error while running background job (class: OC\\Settings\\RemoveOrphaned, arguments: ): {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/snap\\\/nextcloud\\\/8267\\\/nextcloud\\\/extra-apps\\\/ojsxc\\\/settings\\\/personal.php\",\"Code\":0,\"Trace\":\"#0 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/snap\\\/nextc...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#3 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(95): ReflectionClass->__construct('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#4 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(118): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#5 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#6 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/Settings\\\/Manager.php(201): OC\\\\ServerContainer->query('OCA\\\\\\\\OJSXC\\\\\\\\Setti...')\\n#7 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/Settings\\\/RemoveOrphaned.php(86): OC\\\\Settings\\\\Manager->checkForOrphanedClassNames()\\n#8 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(61): OC\\\\Settings\\\\RemoveOrphaned->run(NULL)\\n#9 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(55): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#10 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/private\\\/Settings\\\/RemoveOrphaned.php(70): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#11 \\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/cron.php(123): OC\\\\Settings\\\\RemoveOrphaned->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#12 {main}\",\"File\":\"\\\/snap\\\/nextcloud\\\/8267\\\/htdocs\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"--","version":"13.0.5.2"}`

No other symptoms, unless it is related to #9001 

### Server configuration

Nextcloud snap on Debian

**Operating system**:
Debian Linux 9.5

**Web server:**
apache

**Database:**
mysql

**PHP version:**
7.1.20

**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Originally install from snap at version 12

**Where did you install Nextcloud from:**
snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - camerarawpreviews: 0.5.5
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - ojsxc
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080",
            "xxxx.ddns.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.6.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "38"
        },
        "bruteForce": {
            "whitelist_1": "192.168.1.5\/0",
            "whitelist_2": "192.168.1.1\/0"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": ""
        },
        "camerarawpreviews": {
            "enabled": "yes",
            "installed_version": "0.5.5",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "2.1.5",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1518285453.2605",
            "lastcron": "1534083176",
            "lastupdatedat": "0",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "84cfcb9d5861e1f5620e38d6f8245843",
            "umgmt_show_storage_location": "true",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.4.7",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "live": "1",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "metadata": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "ojsxc": {
            "apiSecret": "6L3TPOa8CJdBwC4\/HDcoaEn",
            "enabled": "no",
            "installed_version": "3.4.1",
            "ocsid": "162257",
            "types": "prelogin"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "installed_version": "1.3.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "3.2.5",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "last_report": "{\"id\":\"oc8aroz9qcal\",\"items\":[[\"server\",\"version\",\"13.0.4.0\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.1.17\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.7.22\"],[\"database\",\"size\",145612800],[\"apps\",\"activity\",\"2.6.1\"],[\"apps\",\"bruteforcesettings\",\"1.1.0\"],[\"apps\",\"calendar\",\"1.6.1\"],[\"apps\",\"camerarawpreviews\",\"0.5.3\"],[\"apps\",\"comments\",\"1.3.0\"],[\"apps\",\"contacts\",\"2.1.5\"],[\"apps\",\"dav\",\"1.4.7\"],[\"apps\",\"federatedfilesharing\",\"1.3.1\"],[\"apps\",\"federation\",\"1.3.0\"],[\"apps\",\"files\",\"1.8.0\"],[\"apps\",\"files_pdfviewer\",\"1.2.1\"],[\"apps\",\"files_sharing\",\"1.5.0\"],[\"apps\",\"files_texteditor\",\"2.5.1\"],[\"apps\",\"files_trashbin\",\"1.3.0\"],[\"apps\",\"files_versions\",\"1.6.0\"],[\"apps\",\"files_videoplayer\",\"1.2.0\"],[\"apps\",\"firstrunwizard\",\"2.2.1\"],[\"apps\",\"gallery\",\"18.0.0\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.1.0\"],[\"apps\",\"metadata\",\"0.6.0\"],[\"apps\",\"nextcloud_announcements\",\"1.2.0\"],[\"apps\",\"notes\",\"2.3.2\"],[\"apps\",\"notifications\",\"2.1.2\"],[\"apps\",\"oauth2\",\"1.1.1\"],[\"apps\",\"ojsxc\",\"disabled\"],[\"apps\",\"password_policy\",\"1.3.0\"],[\"apps\",\"provisioning_api\",\"1.3.0\"],[\"apps\",\"serverinfo\",\"1.3.0\"],[\"apps\",\"sharebymail\",\"1.3.0\"],[\"apps\",\"spreed\",\"3.2.5\"],[\"apps\",\"survey_client\",\"1.1.0\"],[\"apps\",\"systemtags\",\"1.3.0\"],[\"apps\",\"theming\",\"1.4.5\"],[\"apps\",\"twofactor_backupcodes\",\"1.2.3\"],[\"apps\",\"workflowengine\",\"1.3.0\"],[\"stats\",\"num_files\",266741],[\"stats\",\"num_users\",4],[\"stats\",\"num_storages\",6],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",4],[\"stats\",\"num_storages_other\",0],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",3],[\"files_sharing\",\"num_shares_user\",1],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",2],[\"files_sharing\",\"num_shares_link_no_password\",2],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"2\"],[\"files_sharing\",\"permissions_0_23\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1532806726",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.4.5",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** 

yes local

**Are you using encryption:** 

only https

**Are you using an external user-backend, if yes which one:**

no

### Client configuration
**Browser:**
Firefox

**Operating system:**

Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by samtygier** [comment] 2018-09-08 10:13
This seems to be coming from the XMPP app, nextcloud/jsxc.nextcloud. Removing it prevents the log messages.

**Comment by szaimen** [comment] 2021-05-21 11:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-21 11:45 UTC
Labels: 0. Needs triage, bug
