### ISSUE TITLE
Send Meeting Request by Logged-in User

### ISSUE THREAD

**Issue by Offerel** [nextcloud/server#2778] opened 2016-12-20 10:55 UTC
Could you please add a feature, that Meeting Invites/Requests are send via the E-Mail Address of the logged in User instead of the System User which is defined by the Admin?

**Comment by blizzz** [comment] 2016-12-20 12:38
IIRC it is legally not allowed to send automatic emails in someones name. @georgehrke or is it?

**Comment by georgehrke** [comment] 2016-12-20 12:42
I'm not sure if there are legal reasons.
we could use a combination of `From` and `Sender` headers, but I think one's server would be listed as spamming pretty fast, when sending emails for different people.

**Comment by georgehrke** [comment] 2016-12-20 12:43
What we definitely could do is to add a `Reply-To` header with the user's email address.

**Comment by georgehrke** [comment] 2016-12-20 12:45
@Offerel Can you please describe the problem of the current solution?

**Comment by blizzz** [comment] 2016-12-20 13:47
I thought I overheard something like that. Not sure anymore where, when and by whom 🙊

**Comment by Offerel** [comment] 2016-12-20 13:52
No Problem, i will look deeper at the evening. I add a Mail Header to this issue, how it should be OK for my needings.

**Comment by Offerel** [comment] 2016-12-21 12:52
Ok let me explain a little bit:

As Nextcloud Admin under "Additional Settings" i have entered SMTP Details in the form of "notifications@mydomain.com" including Credentials etc.

Then, as a normal User, i Log-In via a E-Mail Address for example "sweet_little_user@mydomain.com" in NextCloud, go to the Calendar App and add a New Entry. In this new Event i add some attendees and save the Event.

Now i go to the Inbox of one of these attendees. I see that there is a new Mail. This Mail is a Meeting Invitation. But if i look at the sender, to identify how will meet me, i see not "sweet_little_user@mydomain.com". All what i see is "notifications@mydomain.com". As a unexperienced User im a little bit nervous, since i don't know somebody with "notifications@mydomain.com".

It would be better, if the sender is "sweet_little_user@mydomain.com" because i know this person.

**Comment by georgehrke** [comment] 2016-12-21 13:14
I checked Google Calendar and applied to your email addresses it sends an email with:

```
From: sweet_little_user@mydomain.com
Sender: notifications@mydomain.com
Reply-To: sweet_little_user@mydomain.com
```

This should also work for us if user and server use the same domain for their mails.

But I suspect that that some servers might reject a mail when `From` and `Sender` have different domains. Maybe someone with more insights on email server can answer that. (maybe @LukasReschke  🙈 )

**Comment by Offerel** [comment] 2016-12-21 13:20
If a E-Mail is send with both Sender and From Address, i think the Mail is send with "On-Behalf". I have made a test at this moment with Nextcloud and send such a Invite via the current configuration. In this test, the Mail arrives in Inbox of a Outlook 2010 Client with the Sender Address sweet_little_user@mydomain.com as it should. I don't know why, i hadn't expected this. I had the following headers found in the Mail:

```
Subject: TestInvite
From: notifications@mydomain.com
Reply-To: Sweet Little User <sweet_little_user@mydomain.com>
To: "User, Name" <user.name@someotherdomain.com>
```
I'm wondering about this. But its OK for me. I don't know why its happen now and not before, but its OK...

**Comment by nolens** [comment] 2017-02-12 18:21
@Offerel, I fully support your issue. Just had a similar proposal, see the issue that is referenced above.

**Comment by georgehrke** [comment] 2017-02-12 18:24
@nolens Please refrain from commenting when you can't add anything new. Use [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead. Thx!

**Comment by MorrisJobke** [comment] 2017-05-11 16:23
Duplicate of #2345

See https://github.com/nextcloud/server/issues/2345#issuecomment-263228068

**Closed by MorrisJobke** 2017-05-11 16:23 UTC
Labels: feature: dav

**Comment by tuergeist** [comment] 2017-05-23 08:27
I'd like to re-opening the issue. 

It would be great if you leave it to the admin to decide how it shall work. I actually use NextClound+Calendar for **different domains**; in that case it's somehow annoying to have to chose one special email address for everybody (also for users with different domain names).

So, e.g., the NC instance uses nanny@domain-one.com but some user are from different domains, e.g., mike@mikes-stuff.com
That leads to the obvious weird combination of

Subject: TestInvite
From: nanny@domain-one.com
Reply-To: mike@mikes-stuff.com
To: "User, Name" <user.name@someotherdomain.com>

The recipient is asking about the relationship between domain-one.com and mikes-stuff.com as this is not obvious (in every case).

Regard,s
 Christoph
