### ISSUE TITLE
Can't create a user from GUI with simple passwords

### ISSUE THREAD

**Issue by powerriegel** [nextcloud/server#3914] opened 2017-03-18 12:45 UTC
Hallo,
it has been a long time since I added a user. Yesterday, I upgraded to NC11. Today, I tried to add a new user account using my admin account. This is not possible due to JavaScript console errors. 

Steps to reproduce:
1. login as admin
2. go to users
3. enter username and password "123456", select arbitrary group
4. click "create". nothing happens. 

With a more complex password, it works. But there is missing a message which tells me what password chars are needed. 

Console error:
POST https://mydomain.com/index.php/settings/users/users 403 (Forbidden)
send @ jquery.js:8630
ajax @ jquery.js:8166
n.(anonymous function) @ jquery.js:8311
(anonymous) @ users.js?v=42d0b4c…:925
(anonymous) @ jquery.js:3256
j @ jquery.js:3099
add @ jquery.js:3145
(anonymous) @ jquery.js:3255
each @ jquery.js:374
(anonymous) @ jquery.js:3252
a.Deferred @ jquery-migrate.min.js?v=42d0b4c…:2
then @ jquery.js:3251
_submitNewUserForm @ users.js?v=42d0b4c…:923
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
users.js?v=42d0b4c…:953 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.<anonymous> (users.js?v=42d0b4c…:953)
    at j (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at x (jquery.js:8266)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)

Web server is nginx on Debian Jessy. 

Best regards.

**Comment by benediktg** [comment] 2017-03-18 21:33
I think it's kind of not a bug but a feature because the _Password policy_ app is enabled by default. You can "fix" this either by disabling it or by adjusting the settings in the _additional settings_.

**Comment by SeeSpotRun** [comment] 2017-03-19 19:33
Duplicate of https://github.com/nextcloud/server/issues/3847

**Closed** 2017-03-20 10:42 UTC

**Comment by SeeSpotRun** [comment] 2017-03-20 12:31
Possible fix is at https://github.com/nextcloud/server/issues/3847#issuecomment-287740126
