### ISSUE TITLE
Dragging a desktop file into a folder in the browser prompts to overwrite file in root with same name

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#1218] opened 2016-08-31 19:13 UTC
### Steps to reproduce
1. Drag and drop a file from the desktop into the home directory in the browser.
2. Create a new folder in the root directory of the web interface.
3. Make a change to the file on your desktop.
4. While still in the home folder view, drag and drop the updated file from the desktop into the newly created folder in the web interface.
### Expected behaviour

It should drop the file right into the new folder without any issue.
### Actual behaviour

It prompts the user asking if it should overwrite the same named file in the home directory, or keep the existing file. If you choose to keep the existing file, no changes are made and the file is not even written into the folder. If you choose to use the new file, it doesn't overwrite the copy in the home directory, but it does copy the file into the folder as it should.
### Server configuration

**Operating system:** Windows 8.1 x64

**Web server:** Ubuntu 14.04 x64, Ubuntu 16.04 x64

**Database:** MySQL

**PHP version:** 5.5, 7.0

**Nextcloud version:** 9.0.50.0, 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated several times from what was originally ownCloud 8

**Where did you install Nextcloud from:** Downloaded package from Nextcloud

**List of activated apps:**
<details>
<summary>

App list</summary>

Enabled:
- activity: 2.2.1
- activitydefaults: 0.1.0
- admin_audit: 1.0.0
- comments: 0.2
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- user_ldap: 0.8.0
  Disabled:
- encryption
- external
- files_external
- user_external
  </details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

{
    "system": {
        "instanceid": "ocgv430cnr4d",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "theme": "hps",
        "trusted_domains": [
            "localhost",
            "**_REMOVED SENSITIVE VALUE**_"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "**_REMOVED SENSITIVE VALUE**_",
        "dbtype": "mysql",
        "version": "9.0.50.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "check_for_working_htaccess": true,
        "memcache.local": "\OC\Memcache\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_domain": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtpport": "25",
        "mail_from_address": "cloud",
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "appstore.experimental.enabled": true,
        "mail_smtphost": "**_REMOVED SENSITIVE VALUE**_",
        "htaccess.RewriteBase": "\/"
    }
}
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**Comment by mar1u5** [comment] 2016-09-04 10:23
Don't we have a way to handle conflicts inside of the WebUI?! Options should be:

- Keep both, and rename the new file (add a **_1** to filename for example)
- Replace the old file with the new file
- Stop uploading the new file

**Comment by linucksrox** [comment] 2016-09-04 12:29
Sure the WebUI seems to handle conflicts properly. However, the point here is that it acts like there is a conflict when there is no conflict. It should not be prompting but for some reason it does, in the scenario described above.
I don't think there is an option to keep both files by the way, so that might be a nice enhancement but not related to this bug.

**Comment by MorrisJobke** [comment] 2017-01-31 02:28
I can't reproduce this anymore on master.

**Comment by linucksrox** [comment] 2017-02-01 13:06
I'm still able to reproduce this. If I click into the new folder, then drag and drop, it works fine. But if I stay in the home folder, and drag and drop the file into the new folder from there, it asks about the file conflict which is invalid. I'll edit my original steps to be more verbose. Can you please retry?

**Comment by MorrisJobke** [comment] 2017-02-01 16:50
> I'm still able to reproduce this. If I click into the new folder, then drag and drop, it works fine. But if I stay in the home folder, and drag and drop the file into the new folder from there, it asks about the file conflict which is invalid. I'll edit my original steps to be more verbose. Can you please retry?

Ah. Good point. I went into the folder. Yes - this is the same here.

**Comment by MorrisJobke** [comment] 2017-02-01 16:51
As this seems to be related to the JS part: maybe somebody from @nextcloud/javascript wants to look into this.

@linucksrox Thanks for the heads up 👍

**Comment by ChristophWurst** [comment] 2017-02-06 08:30
I could narrow down the problem, it seems like we load the file info of the wrong file when checking for conlicts: https://github.com/nextcloud/server/blob/fa96b9e356cc52207a7a8ea5caf569203157ad1b/apps/files/js/file-upload.js#L651 There, we actually get back the file info model of the existing file in the root folder, therefore a conflict is detected later on.

**Comment by datgb** [comment] 2019-08-14 14:13
Any updates on this? I just tried to move files and it stopped halfway. Now my files are mixed in 2 separate directories and I cant get them back togther.

**Comment by linucksrox** [comment] 2019-08-14 20:08
@datgb I guess it's too late now, but if what happened during your file transfer was caused by this issue, selecting the overwrite option would have actually worked as you expected (although misleading).
I just retried on the latest NC version 16.0.3 and it is still behaving this way, in case anyone is curious.

**Comment by henricazottes** [comment] 2020-10-15 09:36
Coming from https://github.com/nextcloud/server/issues/8908 , is it planned to fix this ?
Dragging existing files in the WebUI is managed very well, but moving or copying files directly from the UI gives the message "Could not copy XXXX. Target exists".

**Comment by PVince81** [comment] 2021-11-09 11:54
This is still reproducible on 21.0.5.

**Comment by PVince81** [comment] 2021-11-09 13:26
fixed by https://github.com/nextcloud/server/pull/28250

**Closed by PVince81** 2021-11-09 13:26 UTC
Labels: bug, 1. to develop, feature: files
