### ISSUE TITLE
Autocomplete should be off for all configuration fields, and config should have confirmation before saving

### ISSUE THREAD

**Issue by XANi** [nextcloud/server#14777] opened 2019-03-21 08:48 UTC
Currently some fields in config like LDAP server address do not have turned off autocomplete.

That causes VERY interesting issues, for example, currently all that is needed to break our instance is for me to navigate to LDAP field

My browser autocompletes old setup, Nextclould "helpfully" auto-saves it (even tho it is informing me that the LDAP setup is wrong....) and LDAP is broken.

Let me reiterate it, just *navigating* to config automatically changes fields and automatically saves values Nextcloud *knows* are wrong (I got LDAP test light go to red).

Also there is no reason for **any** server configuration to auto-complete in the first place.

**Comment by MorrisJobke** [comment] 2019-03-25 08:51
We plan to move the LDAP wizard to a different system which then also will involve proper "save" buttons for this critical setting. See #4097

cc @nextcloud/ldap

**Comment by blizzz** [comment] 2019-03-25 12:23
which browser is it? Currently autocomplete is set to "off", alas this is ignored by all browser. We can set the password's to "new-password", which might work, but there's nothing corresponding to a name. 

And then, which Nextcloud version  do you run? Since, meanwhile we disabled auto-save for DN and password because of this.

**Comment by MorrisJobke** [comment] 2019-04-30 08:54
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-04-30 08:54 UTC
Labels: 0. Needs triage, bug, feature: ldap, needs info
