### ISSUE TITLE
[stable14] sharing options not accessible through WebUI

### ISSUE THREAD

**Issue by hoellen** [nextcloud/server#11105] opened 2018-09-07 08:18 UTC
### Steps to reproduce
1. Go to files app
2. Open sharing menu of a file 
3. Share link as link 

### Expected behaviour
You could be able to share by link, delete sharing and change sharing permission.  

### Actual behaviour
Settings (sharing permissions), delete and share by link are missing (see video).
Sharing itself is working through Nextcloud clients (desktop, android and ios tested)
![nextcloud_sharingbug](https://user-images.githubusercontent.com/11299996/45205898-e52a1380-b283-11e8-8e67-7dbab7d34a48.gif)

### Server configuration

**Operating system**: CentOS 7.5

**Web server:** 1.15.3

**Database:** 10.3.9

**PHP version:** 7.2.9

**Nextcloud version:** 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated (every major nextcloud version since 2016).

**Where did you install Nextcloud from:** docker image

**Signing status:** nothing wrong

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - apporder: 0.5.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - data_request: 1.1.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_downloadactivity: 1.3.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - metadata: 0.7.0
  - news: 12.0.4
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - polls: 0.8.3
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - richdocuments: 2.0.12
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - socialsharing_email: 1.0.4
  - spreed: 4.0.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - announcementcenter
  - checksum
  - encryption
  - end_to_end_encryption
  - files_automatedtagging
  - files_external
  - music
  - support
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 62.0

**Operating system:** ArchLinux

### Logs

Nothing in the server log files.

#### Browser log
<details>
<summary>Browser log</summary>

```
Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames.
JQMIGRATE: Migrate is installed, version 1.4.0                                                                                core.js:7:542
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung.          merged.js:2176
New search handler registered                                                                                                 search.js:66:4
querying Whats New data was successful:                                                                                       nocontent merged-template-prepend.js:4478:4
undefined                                                                                                                     merged-template-prepend.js:4479:4
unreachable code after return statement                                                                                       merged.js:1498:4 
```
</details>

**Comment by hoellen** [comment] 2018-09-07 08:37
#10434 has the same problem. After disabling `uBlock Origin` it is working again. 
@skjnldsv should I let this open? You asked for other users who complains about this.

**Comment by skjnldsv** [comment] 2018-09-07 08:58
@hoellen this is a browser-side issue, so I guess we should close this yes. :)
Thanks for your help!!!

**Closed by skjnldsv** 2018-09-07 08:58 UTC
Labels: bug, feature: sharing

**Comment by hoellen** [comment] 2018-09-07 09:49
If anyone has the same problem. This filterlists are responsible for the blocking:
- Fanboy’s Annoyance List 
- Fanboy’s Social Blocking List 

With the following uBlock Origin rules it can fixed:
```
!! show nextcloud share menu
~nextclud.domain.tld##.share-menu
~nextclud.domain.tld##.shareOption
~nextclud.domain.tld###shareLink
```

**Comment by Tom31100** [comment] 2018-11-19 21:35
Hi, 

adblock plus plugin for chrome, latest version on windows 10 produces the same behavior. 
Disabling ABP for the web site solves the issue

**Comment by dl8bh** [comment] 2018-12-01 14:12
I have the same problem and tried with a fresh browser (chromium) with a fresh profile and with no Adblockers or any other plugins activated. The sharing plugin was enabled, but now buttons are shown in the browser UI. Sharing via client (ios/Linux/Windows) works as intended.

**Comment by dl8bh** [comment] 2018-12-01 14:16
Version here is Stable 14
www@$host $ php occ app:list                                                                                                                          
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - admin_notifications: 1.0.2
  - audioplayer: 2.4.1
  - bookmarks: 0.14.2
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.8
  - dav: 1.6.0
  - deck: 0.5.0
  - encryption: 2.2.0
  - external: 3.1.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_automatedtagging: 1.4.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.1
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.1
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0

**Comment by Draghtnod** [comment] 2019-01-09 09:31
Same issue with Firefox 64.0 and Adblock Plus.
Disable the ABP Option "Block Tracking via Social-Media-Icons" and it works again. Otherwise `<ul id="shareLink" class="shareWithList">` gets disabled.

**Comment by fweng322** [comment] 2019-01-22 13:57
However in my nextcloud server 15 (https://nextcloud.slat.org) the share link icon could not be shown, while at the same time the nextcloud server 15 in The Document Foundation (https://nextcloud.documentfoundation.org) could.  The same browser instance, different behavior.

In my browser, no matter google chrome or firefox, I use ABP only and have put my nextcloud server in the white list.  I didn't use uBlock Origin.

Also in my Android app I couldn't get share link either.

I think there must be something in the server itself blocks the share link icon, not only browser issue.

![screenshot_20190122_215601](https://user-images.githubusercontent.com/1000315/51540118-9e366680-1e90-11e9-851e-314fb9d9af7e.png)

![screenshot_20190122_215630](https://user-images.githubusercontent.com/1000315/51540119-9e366680-1e90-11e9-8c8f-90d9676292d2.png)

**Comment by hoellen** [comment] 2019-01-22 14:05
@fweng322 Did you have the app `socialsharing via email` activated? If yes you are probably affected by this bug: [nextcloud/socialsharing#29](https://github.com/nextcloud/socialsharing/issues/29)
Also see #13656

**Comment by fweng322** [comment] 2019-01-22 14:10
> @fweng322 Did you have the app `socialsharing via email` activated? If yes you are probably affected by this bug: [nextcloud/socialsharing#29](https://github.com/nextcloud/socialsharing/issues/29)
> Also see #13656

Yes, thanks.  It works after disabling that app.
