### ISSUE TITLE
[Bug]: Return value must be of type ?int, float returned

### ISSUE THREAD

**Issue by adrianog91** [nextcloud/server#34734] opened 2022-10-21 19:52 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updated my server to 25.0 on my Raspberry (Rasbian) i can't go to files page. But i can go from iOS app.

`{
    "reqId": "9TVJvMSLFs2ULxxmJj1m",
    "level": 3,
    "time": "2022-10-21T19:42:36+00:00",
    "remoteAddr": "151.74.14.96",
    "user": "adriano22",
    "app": "webdav",
    "method": "PROPFIND",
    "url": "/nextcloud/remote.php/dav/files/adriano22/",
    "message": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin::OCA\\DAV\\Connector\\Sabre\\{closure}(): Return value must be of type ?int, float returned",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47",
    "version": "25.0.0.18",
    "exception": {
        "Exception": "TypeError",
        "Message": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin::OCA\\DAV\\Connector\\Sabre\\{closure}(): Return value must be of type ?int, float returned",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php",
                "line": 95,
                "function": "OCA\\DAV\\Connector\\Sabre\\{closure}",
                "class": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin",
                "type": "->",
                "args": [
                    "*** sensitive parameters replaced ***"
                ]
            },
            {
                "file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php",
                "line": 356,
                "function": "handle",
                "class": "Sabre\\DAV\\PropFind",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
                "line": 89,
                "function": "handleGetProperties",
                "class": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 1052,
                "function": "emit",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 984,
                "function": "getPropertiesByNode",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 1662,
                "function": "getPropertiesIteratorForPath",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 1647,
                "function": "writeMultiStatus",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
                "line": 346,
                "function": "generateMultiStatus",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
                "line": 89,
                "function": "httpPropFind",
                "class": "Sabre\\DAV\\CorePlugin",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 472,
                "function": "emit",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 253,
                "function": "invokeMethod",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
                "line": 321,
                "function": "start",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
                "line": 360,
                "function": "exec",
                "class": "Sabre\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
                "line": 35,
                "function": "exec",
                "class": "OCA\\DAV\\Server",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/remote.php",
                "line": 167,
                "args": [
                    "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
                ],
                "function": "require_once"
            }
        ],
        "File": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php",
        "Line": 355,
        "message": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin::OCA\\DAV\\Connector\\Sabre\\{closure}(): Return value must be of type ?int, float returned",
        "exception": {},
        "CustomMessage": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin::OCA\\DAV\\Connector\\Sabre\\{closure}(): Return value must be of type ?int, float returned"
    }`

### Steps to reproduce

1. Go to "File" section in navbar

### Expected behavior

Show a folder list of files

### PHP engine version

PHP 8.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - previewgenerator: 5.1.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recognize: 3.1.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - richdocuments: 7.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - duplicatefinder: 0.0.15
  - encryption
  - files_external
  - metadata: 0.16.0
  - passwords: 2022.10.20
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - workflow_media_converter: 1.4.0
```

**Comment by szaimen** [comment] 2022-10-21 23:32
Duplicate of https://github.com/nextcloud/server/issues/34674

**Closed** 2022-10-21 23:32 UTC
Labels: bug, 0. Needs triage
