### ISSUE TITLE
[Bug]: POST request on  /nextcloud/login/v2/poll results in 405 Method Not Allowed

### ISSUE THREAD

**Issue by sanfx** [nextcloud/server#34126] opened 2022-09-18 22:45 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Attempting to get flow app password following https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2

However when we reach the last step where we should get the app password It doesn't seem to work as expected.

i.e. getting respoonse code 405 Method Not allowed. 

When example on docs linked above clearly uses POST method.

### Steps to reproduce

1.  generate a token following the url:

```
>>> flow_init_url = "https://self.hosted.com/nextcloud/index.php/login/v2"
>>> headers = {'Content-type': 'application/x-www-form-urlencoded', 'Accept': 'text/plain'}
>>> r = requests.post(flow_init_url, headers=headers)
>>>  r
<Response [200]>
>>> r.text
'{"poll":{"token":"kdDdRsBYsiuwbLukDg7YdPgcbonfPockwmNoltxPMeINP0bgVXCYMt3U71b1HLvOqC8kIaVONnQ0uwgeJvkNr5hyhcnaLJRoSqpN21vEIvaOel5ZV7G38D5z1p7bE1NL","endpoint":"http:\\/\\/self.hosted.com\\/nextcloud\\/index.php\\/login\\/v2\\/poll"},"login":"http:\\/\\/access.devilsan.com\\/nextcloud\\/index.php\\/login\\/v2\\/flow\\/tZnNmJzHcqH0R9vjU7P2uma07aHtTewZ3C1dNyZF5PxOT7OHWLxcD2UR3yLCAbqarMu65NZ0zrqGmxDok9LHAgbZTPRUVDABNM9CJXCyEMVCVQXYH9vYpy1HVlPrY5mb"}'
>>>
```

2. The I use this token  to the poll url

```
>>> data = {"token":"kdDdRsBYsiuwbLukDg7YdPgcbonfPockwmNoltxPMeINP0bgVXCYMt3U71b1HLvOqC8kIaVONnQ0uwgeJvkNr5hyhcnaLJRoSqpN21vEIvaOel5ZV7G38D5z1p7bE1NL"}
>>> r_final = requests.post("https://self.hosted.com/nextcloud/login/v2/poll", data=data)
>>> r_final.status_code
405
```

### Expected behavior

when instead this output is expected:
```

{
    "server":"https:\/\/cloud.example.com",
    "loginName":"username",
    "appPassword":"yKTVA4zgxjfivy52WqD8kW3M2pKGQr6srmUXMipRdunxjPFripJn0GMfmtNOqOolYSuJ6sCN"
}

```

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 7001,
            "timeout": 3,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "trusted_domains": [
            "192.168.1.56",
            "home.local",
            "100.87.218.90",
            "self.hosted.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "has_internet_connection": true,
        "connectivity_check_domains": [
            "self.hosted.com"
        ],
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "logfilemode": 416,
        "loglevel": 2,
        "loglevel_frontend": 2,
        "syslog_tag": "Nextcloud",
        "syslog_tag_audit": "Nextcloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.5.1",
        "overwrite.cli.url": "https:\/\/192.168.1.56\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "has_rebuilt_cache": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "theme": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - apporder: 0.15.0
  - bookmarks: 11.0.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.0
  - cfg_share_links: 2.0.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.15
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - fileslibreofficeedit: 1.0.4
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.8
  - music: 1.6.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - openotp_auth: 1.4.5
  - password_policy: 1.14.0
  - passwords: 2022.9.20
  - phonetrack: 0.7.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - ransomware_protection: 1.13.0
  - recognize: 2.2.1
  - recommendations: 1.3.0
  - richdocuments: 6.2.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.5
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_nextcloud_notification: 3.4.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - w2g2: 3.3.9
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
// provided log message was unrelated.
```

**Comment by kesselb** [comment] 2022-09-19 18:04
Hi, did you try to run the second request with curl?

Wild guess: The content-type header for the second request is missing. `curl -d` = content-type application/x-www-form-urlencoded.

**Comment by sanfx** [comment] 2022-09-19 21:48
Yes, I just tried now:

```
curl -X POST https://self.hosted.com/nextcloud/login/v2/poll -d "token=FL1hV8pc97T3PralYBAQsZbi3ux4B73m9AIgytDWKFOtYl6sUYZjJvMJ7VV36WjvgcSpMpcccIxasNXEqrUktLeOwjlR0fhCRwaHpyuVz3AtOjA3S1NoyxUf6aPt4Qin" -H 'Content-Type: application/json'
```

I do not get anything in return.

**Comment by kesselb** [comment] 2022-09-20 08:11
`curl -X POST https://self.hosted.com/nextcloud/login/v2/poll -d "token=mQUYQdffOSAMJYtm8pVpkOsVqXt5hglnuSpO5EMbgJMNEPFGaiDe8OUjvrJ2WcYcBSLgqynu9jaPFvZHMl83ybMvp6aDIDARjTFIBpRWod6p32fL9LIpIStvc6k8Wrs1"`

Content-Type application/x-www-form-urlencoded

**Comment by sanfx** [comment] 2022-09-20 13:29
Sorry No I tried
```
curl -H "Content-Type:  application/x-www-form-urlencoded" -H "Content-Type: application/json" -X POST https://self.hosted.com/nextcloud/login/v2/poll -d "token=owcKBSE7yNj9zS7JNeLEJjpvTAqXxWlkuORqXVhVO7cba8sW6PUXhdxo0qJteUTs4AcuM3Z2JCGsn8OqrJWiur3YjoRWbdbOl2ZciRdz7gN76oFhEJrQwZAXvKc8awH3"
```
but I still don't get anything.

**Comment by kesselb** [comment] 2022-09-20 14:12
Hi, 

`curl -v -X POST https://self.hosted.com/nextcloud/login/v2/poll -d "token=owcKBSE7yNj9zS7JNeLEJjpvTAqXxWlkuORqXVhVO7cba8sW6PUXhdxo0qJteUTs4AcuM3Z2JCGsn8OqrJWiur3YjoRWbdbOl2ZciRdz7gN76oFhEJrQwZAXvKc8awH3"`

Please use the **exact** command from our documentation. curl -d will use the proper content type by default. 

I recommend to have a closer look at your last comment. You set the content-type header twice. First x-www-form-urlencoded and second json. Likely the latter will overwrite the first one. 

My guess is that the second code example (in the first post) is wrong. The content type is missing and it looks like a json object. You need to adjust it.

Closing your report now. I don't think there is anything broken in Nextcloud. However if you can provide a reproducible test case we can always report.

Please visit https://help.nextcloud.com/c/dev/11 for developer topics. 

Thanks and happy hacking :robot:

**Closed by kesselb** 2022-09-20 14:12 UTC
Labels: bug, 0. Needs triage, pending documentation

**Comment by sanfx** [comment] 2022-09-20 16:46
Before you close and I am unable to comment take a look at this screenshot please.
![error](https://user-images.githubusercontent.com/2231415/191316727-645aec8f-56d9-46d1-a073-6490a29c03b0.png)
I just used only 1 header . I want to get into nextcloud development but that is php and I am only into python.

**Comment by kesselb** [comment] 2022-09-20 17:09
404 is fine. I guess you forgot to use the `login` url from the first response to create an application token.

Please read our documentation https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2 again.

Please visit https://help.nextcloud.com/c/dev/11 for developer topics.

Thanks and happy hacking :robot:
