### ISSUE TITLE
App passwords being set to invalid after some minutes.

### ISSUE THREAD

**Issue by beerlao** [nextcloud/server#26655] opened 2021-04-20 15:07 UTC
App passwords being set to invalid after some minutes.

### Steps to reproduce
1. Set an app password. Works.
2. Wait a minute.
3. “password_invalid” in “oc_authtoken” is set to “1” which leads to access denied.

### Expected behaviour
App password should not be set to invalid.

### Actual behaviour
App password being set to invalid.

### Server configuration

**Operating system:**

Ubuntu 20.04 LTS

**Web server:**

nginx as reverse proxy. nextcloud:fpm running dockerized.

**Database:**

mariadb 1:10.5.9+maria~focal (latest nextcloud:fpm image)

**PHP version:**

7.4.16 (latest nextcloud:fpm image)

**Nextcloud version:** (see Nextcloud admin page)

20.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh install

**Where did you install Nextcloud from:**

Docker hub

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bookmarks: 4.1.0
  - bruteforcesettings: 2.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - sociallogin: 4.4.1
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": false,
        "overwritehost ": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "default_phone_region": "DE",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.14.3",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "118"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "4.1.0",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1618414698.2519",
            "lastcron": "1618930504",
            "lastupdateResult": "[]",
            "lastupdatedat": "1618929004",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.1.0",
            "types": ""
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.17.1",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_path": "\/usr\/bin\/clamscan",
            "enabled": "no",
            "installed_version": "3.2.0",
            "types": "filesystem,dav"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.10.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "no",
            "installed_version": "4.0.4",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem"
        },
        "sociallogin": {
            "allow_login_connect": "",
            "auto_create_groups": "",
            "create_disabled_users": "",
            "custom_providers": "{\"custom_oauth2\":[{\"name\":\"[REMOVED]\",\"title\":\"[REMOVED]\",\"apiBaseUrl\":\"https:\\\/\\\/[REMOVED]\",\"authorizeUrl\":\"https:\\\/\\\/[REMOVED]\\\/oauth\\\/authorize\",\"tokenUrl\":\"https:\\\/\\\/[REMOVED]\\\/oauth\\\/token\",\"profileUrl\":\"https:\\\/\\\/[REMOVED]\\\/oauth\\\/profile\",\"logoutUrl\":\"\",\"clientId\":\"[REMOVED]\",\"clientSecret\":\"[REMOVED]\",\"scope\":\"profile\",\"profileFields\":\"\",\"groupsClaim\":\"\",\"style\":\"\",\"defaultGroup\":\"\"}]}",
            "disable_notify_admins": "1",
            "disable_registration": "",
            "enabled": "yes",
            "hide_default_login": "",
            "installed_version": "4.4.1",
            "no_prune_user_groups": "",
            "oauth_providers": "{\"google\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\",\"auth_params\":{\"hd\":\"\"}},\"amazon\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"},\"facebook\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"},\"twitter\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"},\"GitHub\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\",\"orgs\":\"\"},\"discord\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"},\"QQ\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"},\"slack\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"},\"telegram\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"},\"mailru\":{\"appid\":\"\",\"secret\":\"\",\"defaultGroup\":\"\"}}",
            "prevent_create_email_exists": "1",
            "restrict_users_wo_mapped_groups": "",
            "types": "",
            "update_profile_on_login": "1"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.2.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "6.0.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "filesystem"
        }
    }

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No.

**Are you using encryption:** yes/no

No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Social Login (oauth2).

### Logs

Logs show no errors.

**Comment by szaimen** [comment] 2021-04-20 15:24
Duplicate of https://github.com/nextcloud/server/issues/26502

**Closed by szaimen** 2021-04-20 15:24 UTC
Labels: 0. Needs triage, bug
