### ISSUE TITLE
NotPermittedException: No create permission for folder

### ISSUE THREAD

**Issue by SchroSct** [nextcloud/server#11717] opened 2018-10-09 12:57 UTC
### Steps to reproduce
1.  Have Nextcloud 13
2.  Overwrite with Nextcloud 14.0.1
3.  

### Expected behaviour
Should be able to occ upgrade to 14.0.1

### Actual behaviour
An unhandled exception has been thrown:
OCP\Files\NotPermittedException: No create permission for folder in /var/www/owncloud/lib/private/Files/Node/Folder.php:166

http://paste.ubuntu.com/p/cSr2DtKVqP/

### Server configuration

**Operating system**:
Ubuntu 18.04
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
7.2.10
**Nextcloud version:** (see Nextcloud admin page)
13.0.6.1

**Comment by michidk** [comment] 2018-10-24 17:16
Having a similar error:

```
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: **removed**
Request ID: udgz3pdxiK1vXuznjaTP
Type: OCP\Files\NotPermittedException
Code: 0
Message: No create permission for path
File: /var/www/html/lib/private/Files/Node/Folder.php
Line: 187

Trace
#0 /var/www/html/lib/private/Files/SimpleFS/SimpleFolder.php(83): OC\Files\Node\Folder->newFile('1bf6-67e5-autoc...')
#1 /var/www/html/lib/private/Template/SCSSCacher.php(273): OC\Files\SimpleFS\SimpleFolder->newFile('1bf6-67e5-autoc...')
#2 /var/www/html/lib/private/Template/SCSSCacher.php(153): OC\Template\SCSSCacher->cache('/var/www/html/a...', '1bf6-67e5-autoc...', 'autocomplete.sc...', Object(OC\Files\SimpleFS\SimpleFolder), '/apps/comments/...')
#3 /var/www/html/lib/private/Template/CSSResourceLocator.php(109): OC\Template\SCSSCacher->process('/var/www/html/a...', 'css/autocomplet...', 'comments')
#4 /var/www/html/lib/private/Template/CSSResourceLocator.php(84): OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist('/var/www/html/a...', 'css/autocomplet...', 'comments')
#5 /var/www/html/lib/private/Template/ResourceLocator.php(78): OC\Template\CSSResourceLocator->doFind('css/autocomplet...')
#6 /var/www/html/lib/private/TemplateLayout.php(285): OC\Template\ResourceLocator->find(Array)
#7 /var/www/html/lib/private/TemplateLayout.php(201): OC\TemplateLayout::findStylesheetFiles(Array)
#8 /var/www/html/lib/private/legacy/template.php(210): OC\TemplateLayout->__construct('user', 'files')
#9 /var/www/html/lib/public/AppFramework/Http/TemplateResponse.php(157): OC_Template->fetchPage(Array)
#10 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(119): OCP\AppFramework\Http\TemplateResponse->render()
#11 /var/www/html/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
#12 /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#13 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#14 /var/www/html/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#15 /var/www/html/lib/base.php(987): OC\Route\Router->match('/apps/files/')
#16 /var/www/html/index.php(42): OC::handleRequest()
#17 {main}
```

Using docker. 
Also this guy seems to have the same issue: https://help.nextcloud.com/t/no-create-permission-for-path/39517

Looks like a caching problem?

**Comment by michidk** [comment] 2018-10-24 17:22
Fixed it by removing the whole data/appdata_* folder and following the steps mentioned here: https://github.com/nextcloud/server/issues/10436#issuecomment-408896858

**Comment by eb4x** [comment] 2018-11-07 14:03
I solved a similar problem by commenting out that access check. Nextcloud has the correct permissions. The checkPermissions method is broken, or rather whatever that thing calls.

**Comment by skjnldsv** [comment] 2020-04-10 07:42
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 07:42 UTC
Labels: 0. Needs triage, bug
