### ISSUE TITLE
Empty shared folders in Chromium (PROPFIND returns 401 error on public.php)

### ISSUE THREAD

**Issue by pinhead84** [nextcloud/server#13178] opened 2018-12-20 15:06 UTC
### Steps to reproduce
- Create a folder, that contains some files and subfolders. 
- Share the folder with a link & password.
- Open the link with Chromium and enter the password.

### Expected behaviour
The contents of the folder should be shown.

### Actual behaviour
No files are shown. The user has to click on the home icon (top left) in order to refresh the page and make the folder contents appear.

The problem does not occur with Firefox.

## Server configuration detail

**Operating system:** Linux 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64

**Webserver:** nginx/1.14.0 (fpm-fcgi)

**Database:** mysql 10.3.11

**PHP version:**  7.2.12

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** hosted solution provided by hetzner.de

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - apporder: 0.6.0
 - bookmarks: 0.14.3
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - files: 1.9.0
 - files_markdown: 2.0.5
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - news: 13.0.3
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - federation
 - firstrunwizard
 - mail
 - nextcloud_announcements
 - support
 - survey_client
 - systemtags
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***""
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "timeout": "1.5",
        "dbindex": "0"
    },
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "log_type": "syslog",
    "syslog_tag": "***REMOVED SENSITIVE VALUE***"",
    "simpleSignUpLink.shown": "false",
    "upgrade.disable-web": "true",
    "updatechecker": "true"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

The following Javascript error is shown in the browser console (Chromium), if the page is shown with the empty folder:

```
core.js?v=57bddf21-2:5729 XHR failed loading: PROPFIND "https://MY-NEXT-CLOUD-URL/public.php/webdav/".
request @ core.js?v=57bddf21-2:5729
propFind @ core.js?v=57bddf21-2:5569
getFolderContents @ client.js?v=57bddf21-2:480
reload @ filelist.js?v=57bddf21-2:1774
changeDirectory @ filelist.js?v=57bddf21-2:1630
initialize @ public.js?v=57bddf21-2:263
(anonymous) @ public.js?v=57bddf21-2:435
(anonymous) @ core.js?v=57bddf21-2:781
setTimeout (async)
_.delay @ core.js?v=57bddf21-2:780
executeBound @ core.js?v=57bddf21-2:714
bound @ core.js?v=57bddf21-2:746
(anonymous) @ public.js?v=57bddf21-2:434
j @ core.js?v=57bddf21-2:2
fireWith @ core.js?v=57bddf21-2:2
ready @ core.js?v=57bddf21-2:2
I @ core.js?v=57bddf21-2:2
```
</details>

**Comment by skjnldsv** [comment] 2019-08-15 06:06
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-08-15 06:06 UTC
Labels: 0. Needs triage, bug
