### ISSUE TITLE
Page broken after color changing, requires restart of php7.2

### ISSUE THREAD

**Issue by Niclas-sol** [nextcloud/server#14961] opened 2019-04-04 15:48 UTC
### Steps to reproduce
1. Go to settings, theming
2. Change color in menu
3. Reload or switch page

### Expected behaviour

The page should load properly with new color
### Actual behaviour

The page seems broken after loading. Not loading correct, instead I can only see the text and the icons, but not in the usual Nextcloud Page. After restarting php-fpm or waiting for a few minutes I can access the page normally.

### Server configuration

**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
PHP-7.2 FPM
**Nextcloud version:** (see Nextcloud admin page)
15.0.6
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Manually from official Downloadpage
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
 - accessibility: 1.1.0
  - activity: 2.8.2
  - apporder: 0.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.6
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
  - user_usage_report
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'cloud.mydomain.de',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '15.0.6.1',
  'overwrite.cli.url' => 'https://cloud.mydomain.de',
  'htaccess.RewriteBase' => '/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
  ),
  'onlyoffice' => 
  array (
    'verify_peer_off' => true,
  ),
  'updater.secret' => '',
  'theme' => '',
  'loglevel' => 2,
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari latest version
**Operating system:**
Mac OS Mojave
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Thu Apr 04 15:20:59.506589 2019] [authz_core:error] [pid 13790:tid 139628380124928] [client 185.36.120.110:64424] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Thu Apr 04 15:21:01.789047 2019] [authz_core:error] [pid 13789:tid 139628287805184] [client 185.36.120.110:63471] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Thu Apr 04 15:27:41.029420 2019] [authz_core:error] [pid 13789:tid 139628430481152] [client 185.36.120.110:63742] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) Java

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (f09c-4041-jquery-ui-fixes.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (f09c-4041-server.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (70e2-4041-styles.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (f09c-4041-jquery.ocdialog.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (0d6d-4041-firstrunwizard.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (f09c-4041-results.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (f09c-4041-settings.css, line 0)
b) The network log


c) ...
```
</details>

**Comment by J0WI** [comment] 2019-04-10 09:57
I'm closing this as a duplicate of #14615

**Closed by J0WI** 2019-04-10 09:57 UTC
Labels: 0. Needs triage, bug, feature: theming
