### ISSUE TITLE
Updater in 10.0.1 failed

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#2663] opened 2016-12-14 10:07 UTC
H, 
i tried to update my 10.0.1 by using the built in updater to the proposed version 10.0.2. After pressing
Updater öffnen.. i received the following error message:
Could not start updater, please try the manual update !

Enclosed is a screen shot of the browser network console!

![nextc-updater](https://cloud.githubusercontent.com/assets/9738727/21177817/1c8f5e36-c1ed-11e6-9d0a-617dc5a2ab87.png)
The directory exists, containing a file named index.php
regards, hitam4450

**Comment by nickvergessen** [comment] 2016-12-14 11:20
Is that the IP your instance is installed with, or do you use a different URL to access it?

**Comment by hitam4450** [comment] 2016-12-14 11:21
Yes, that is the IP nextcloud is installed!

**Comment by nickvergessen** [comment] 2016-12-14 11:24
Can you please fill out the information requested by the issue template?

**Comment by hitam4450** [comment] 2016-12-14 14:32
PHP 5.6, DEBIAN Jessie 8.6.....

**Comment by nickvergessen** [comment] 2016-12-15 12:43
https://github.com/nextcloud/server/issues/new

**Comment by hitam4450** [comment] 2017-01-19 14:09
Any progress on this issue ??

**Comment by go2sh** [comment] 2017-01-19 14:33
The Issue is missing some information like the sever log, the nextcloud log. How should anyone know, what is happening with this little information?

**Comment by MorrisJobke** [comment] 2017-05-11 04:55
We are missing information here. I will close this ticket now. We will reopen once we know more about this problem on your side, because we can't reproduce this over here.

**Closed by MorrisJobke** 2017-05-11 04:55 UTC
Labels: feature: install and update, needs info
