### ISSUE TITLE
Problem playing audio files

### ISSUE THREAD

**Issue by framarini02** [nextcloud/server#24840] opened 2020-12-24 16:22 UTC
When I have to play an audio file, when I open it, it always gives me a loading error

**Comment by framarini02** [comment] 2020-12-24 16:23
i have nextcloud 21.0.0 beta 3

**Comment by kesselb** [comment] 2020-12-25 14:29
Thanks for testing Nextcloud 21 :+1: 

We use the html5 audio element to play audio files: https://www.w3schools.com/html/html5_audio.asp

If your browser is able to play a audio file it should work in Nextcloud as well. An easy way to validate that is to download the file and drag it to the browser. **If that works it's a valid bug report for: https://github.com/nextcloud/viewer**

Don't forget to include the Nextcloud version, the browser (os, version, etc) and what kind of audio file. If possible upload the audio file.

Closing the report because the relevant information to reproduce are missing.

**Closed by kesselb** 2020-12-25 14:29 UTC
