### ISSUE TITLE
EXIF information

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/server#5106] opened 2017-05-25 08:23 UTC
EXIF support possible for milestone 13?
I think with this feature, many improvements can be made.

https://github.com/nextcloud/ios/issues/170 by me
https://github.com/nextcloud/maps/issues/4 by @jancborchardt 
https://github.com/nextcloud/android/issues/4501 by @Gatak

**Comment by Spartachetto** [comment] 2017-05-25 09:32
Not sure this is a feature of the server.
You can find some information about this topic here: [MediaMetadata app to extract and store meta data from media files](https://help.nextcloud.com/t/mediametadata-app-to-extract-and-store-meta-data-from-media-files/1601)

**Comment by nickvergessen** [comment] 2017-06-01 10:12
I agree that this should better be done as an app.

**Comment by jancborchardt** [comment] 2017-06-01 18:30
@oparoz is there any app work-in-progress available online which was done by that student?

**Comment by nickvergessen** [comment] 2017-06-01 20:34
Follow the link to the forum posted above:
https://help.nextcloud.com/t/mediametadata-app-to-extract-and-store-meta-data-from-media-files/1601

there is a link in the first post to the wiki of the repo:
https://github.com/interfasys/mediametadata/wiki/Possible-Fields-that-can-be-extracted

Click on code:
https://github.com/interfasys/mediametadata/

**Comment by jancborchardt** [comment] 2017-08-29 08:00
We should discuss doing this in a central way again. There's several apps which could use it:

- Showing photos on the map at their location nextcloud/maps#4 @v1r0x @BatPio
- Showing photos in the Calendar on their respective day @georgehrke @tcitworld
- Displaying more EXIF data in the gallery for more photo details

As pictures are a pretty core file type, this is not something we should simply brush off.

If showing photos in the Calendar for example doesn't need the full EXIF data though, we could say that specifically extracting the GPS data would be a task for the Maps app. But we should avoid some silly dependecy like a specific "EXIF extraction" app.

**Comment by oparoz** [comment] 2017-08-30 07:38
I'm happy to move the app to Nextcloud if it's deemed as a good enough starting point. Lots of work was done to write specs to make sure it's useful, but I understand that the server is also collecting some EXIF data already.

**Comment by Spartachetto** [comment] 2018-02-07 01:14
Some notes:

- 13 was released today!
- an app to _view_  metadata does exist ( https://github.com/gino0631/nextcloud-metadata ). It allows to viene the metadata  in the sidebar 
- the existing app does **not**  allow the advanced functionalities @jancborchardt  was describing (e.g.: showing the proto on a map). Basically you cannot use the data
- several metadata types are missing up to now from the app (e.g. bibliographic metadata)

**Comment by Tyler-2** [comment] 2019-01-15 15:06
This was brought up as a pre-requisite for sorting by EXIF 'taken' date, which someone has developed and submitted a PR for. And yet this portion has gone stale.

Is this anywhere on the roadmap? Viewing a collection of photos without having the ability to sort by when they were taken has both professional and family sharing impacts.

**Comment by jancborchardt** [comment] 2019-04-01 15:13
Here’s some notes I made for the last cycle on Gallery sidebar, EXIF data etc etc. Maybe it’s helpful:

- [Metadata app](https://apps.nextcloud.com/apps/metadata) (by @gino0631) actually shows a lot of EXIF data already: https://github.com/gino0631/nextcloud-metadata (there’s also outdated https://github.com/interfasys/mediametadata/)
- There also is a [PHP EXIF library](https://github.com/pel/pel] (thanks to recommendation by @v1r0x)
- [GpxPod](https://apps.nextcloud.com/apps/gpxpod) (by @eneiluj) displays geotagged pictures: https://gitlab.com/eneiluj/gpxpod-oc
- [RAW previews app](https://apps.nextcloud.com/apps/camerarawpreviews) (by @cowai): https://github.com/cowai/CameraRawPreviews
- Related issues https://github.com/nextcloud/server/issues/5106 and https://github.com/nextcloud/gallery/issues/204
- Previous professional services discussion https://github.com/nextcloud-gmbh/professional_services/issues/73

cc @MorrisJobke @skjnldsv for this cycle.

**Comment by hairlesshobo** [comment] 2020-01-08 15:02
Was just wanting to see if there is any update on this request? I am very much looking forward to seeing the improvements that can be made in the mobile apps once this is implemented. Thanks!

**Comment by gino0631** [comment] 2020-01-08 16:19
If there is anything that can be done in the https://github.com/gino0631/nextcloud-metadata app regarding this, feel free to submit a feature request. Thanks!

**Comment by jancborchardt** [comment] 2020-01-13 22:37
It probably makes sense to integrate @gino0631’s Metadata app into the Photos app: https://github.com/nextcloud/photos

Right @skjnldsv @rullzer @karlitschek?

**Comment by karlitschek** [comment] 2020-01-14 09:29
I agree. This is a good suggestion. I'm currently unsure if it should be in the photos app or more standalone so that other apps like File or Search can also benefit from it.

**Comment by skjnldsv** [comment] 2020-01-14 10:27
> I'm currently unsure if it should be in the photos app or more standalone so that other apps like File or Search can also benefit from it.

I'm guessing it would offer us more flexibility as a standalone app :)

**Comment by jancborchardt** [comment] 2020-01-14 12:18
It is already a stand-alone app in the store :) https://apps.nextcloud.com/apps/metadata

What we could do is integrate it better like via a "Details" tab in the sidebar rather than adding yet another specific tab for an app?

**Comment by szaimen** [comment] 2020-01-14 12:49
> It is already a stand-alone app in the store :) https://apps.nextcloud.com/apps/metadata
> 
> What we could do is integrate it better like via a "Details" tab in the sidebar rather than adding yet another specific tab for an app?

You could make the app official so that it is installed by default.

**Comment by Spartachetto** [comment] 2020-01-14 12:50
I understood that the real issue was to integrate more the EXIF information so that other apps could use the data...

The apps that could use the data are at least:
- Files (display info and also order files by metadata)
- Search
- Photo
- Maps
- Calendar
- ...

In addition the android client developers were interested in this issue to use the metadata in the client

**Comment by gino0631** [comment] 2020-01-14 23:01
Maybe the Metadata App should provide an API that could by used by other apps?

**Comment by Gatak** [comment] 2020-01-15 13:34
I think it makes more sense to provide this in core so that the metadata can be indexed and searched, as well as used by various apps.

**Comment by skjnldsv** [comment] 2020-01-15 21:39
> Maybe the Metadata App should provide an API that could by used by other apps?

Is the app making the properties available as dav attributes?
- In photos what would be great is having the date taken (https://github.com/nextcloud/photos/issues/87)
- The sidebar tab though is a bit too much for the common user and will add up to the other which are already five :)

What do you think about only showing the tab in the photos app sidebar ? :wink:

**Comment by gino0631** [comment] 2020-01-15 22:17
> Is the app making the properties available as dav attributes?

Currently, no, but the idea is quite interesting.

> What do you think about only showing the tab in the photos app sidebar ? 😉

Not sure if I understand - no tab in Files you mean?

**Comment by skjnldsv** [comment] 2020-01-15 22:39
> Not sure if I understand - no tab in Files you mean?

yes
Only in the new gallery

**Comment by gino0631** [comment] 2020-01-15 22:40
The app is not just for pictures.

**Comment by jancborchardt** [comment] 2020-01-15 23:38
Just an adjustment of the last sentence @skjnldsv said: We would show the sidebar tab, but we need a general way for apps to not add the xth tab, but we should have one "Details" tab where the Metadata app can hook into. :)

As the Metadata app would be the first to hook into this, de facto it would be the same as now but properly done. A first step would just be if the metadata app renames the tab title to "Details"?

**Comment by gino0631** [comment] 2020-01-15 23:54
General way for apps to provide additional details sounds good, but I can't see how renaming the tab helps to implement that.

**Comment by skjnldsv** [comment] 2020-03-10 07:54
Closing as this is not related to server in the end.
There is already a talk in photos here: https://github.com/nextcloud/photos/issues/226

**Closed by skjnldsv** 2020-03-10 07:54 UTC
Labels: 1. to develop, enhancement

**Comment by Gatak** [comment] 2020-03-10 10:06
I think it is a shame this issue is closed, because several apps could use exif information. For example the Files app, and sort files based on metadata (date taken, edited, tags). This is something people expect from any filemanager.

**Comment by skjnldsv** [comment] 2020-03-10 10:23
The issue is not closed because it's abandoned, but because now that photos is here, we have a wider discussion (like we had on gallery), we definitely want EXIF implementation on nextcloud, do not worry :)
