### ISSUE TITLE
Sweden locale does not use correct date format

### ISSUE THREAD

**Issue by alxpettit** [nextcloud/server#26597] opened 2021-04-16 16:04 UTC
### Steps to reproduce
1. Go to Personal info
2. Try to change locale to English (Sweden)
3.  watch in awe as Nextcloud interprets this as asking for the strange american date format (MM/DD/YYYY)

### Expected behaviour
Use ISO 8601 or similar date format (YYYY-MM-DD) & 24 hour time
### Actual behaviour
![image](https://user-images.githubusercontent.com/28266167/115051956-3960ef80-9e92-11eb-86b1-5df12b6f9303.png)

### Server configuration

**Operating system:**
Ubuntu 20.04 (docker with standard Debian 10/buster container)
**Web server:**
Standard apache (docker)

**Database:**

 Type: mysql

Version: 10.5.9 

**PHP version:**

Version: 7.4.16

**Nextcloud version:** (see Nextcloud admin page)

21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Docker

**Comment by szaimen** [comment] 2021-04-16 16:18
Did you try to use the swedish locale directly?
I just guess the the `English (Sweden)` isn't the correct Locale.
See those locales: 
![Screenshot_20210416-181703_Brave](https://user-images.githubusercontent.com/42591237/115054060-15c49600-9ee0-11eb-9183-526fb865179c.jpg)

**Comment by alxpettit** [comment] 2021-04-16 17:49
That did actually fix it, but it's more of a workaround. I'd say the bug is still there :P

Thanks for suggesting, tho!

**Comment by szaimen** [comment] 2021-04-16 17:50
Why is that a workaround? The swedish locale is the correct one

**Comment by tflidd** [comment] 2021-04-17 09:22
> Why is that a workaround? The `Swedish` locale is the correct one

They want to have the interface in English but dates etc. in the usual format for Sweden. Why should there be a `English (Sweden)` locale anyway?

**Comment by szaimen** [comment] 2021-04-17 09:26
> Why should there be a `English (Sweden)` locale anyway?

I don't know why but since you can configure the language differently from the locale I'd say the correct way is to use English as language and Sweden as locale.
![image](https://user-images.githubusercontent.com/42591237/115108273-cd54b900-9f6f-11eb-8213-65d895bc0212.png)

**Comment by alxpettit** [comment] 2021-04-17 19:43
Date formats are not 'English', tho.

**Comment by alxpettit** [comment] 2021-04-17 19:46
Date formats aren't really part of language. Having the English (X) locales is sadly a standard I've seen pretty broadly in a lot of applications.

If you just decide to blacklist those locales rather than supporting them, that's fair too. Although I think I _did_ see some things (like notifications) actually displaying in Swedish instead of English... so I'm a little worried that Nextcloud itself doesn't quite understand the difference between locale and language.

**Comment by alxpettit** [comment] 2021-04-17 19:50
Regardless of what you do, I think `English (Sweden)` should _decidedly not_ act like you picked `English (US)`. Whether you chose to alias it or get rid of it or whatever, I don't really know what the best solution is internally. I just think it causes lots of confusion and doesn't behave how it should, as is.

**Comment by szaimen** [comment] 2021-04-17 19:59
cc @nextcloud/designers @nextcloud/server-triage

**Comment by alxpettit** [comment] 2021-04-20 18:25
Turns out there is a pretty big difference, given that locale seems to control all the times words are included in e.g. date format.

![image](https://user-images.githubusercontent.com/28266167/115445774-28361c80-a1cb-11eb-921e-0eaab02aeb6d.png)

**Comment by juliushaertl** [comment] 2021-04-21 08:59
Yep this is actually a duplicate of https://github.com/nextcloud/server/issues/15457

**Closed by juliushaertl** 2021-04-21 08:59 UTC
Labels: 0. Needs triage, bug, needs info
