### ISSUE TITLE
Thunderbird/Lightning: Event invitations cannot be added to a nextcloud CalDAV calendar

### ISSUE THREAD

**Issue by boldt** [nextcloud/server#3464] opened 2017-02-13 10:52 UTC
### Steps to reproduce

* Thunderbird 45.4.0
* Lightning 4.7.4

#### Install/Configure Calendar

* Create a fresh Thunderbird profile
* Add Lightning Extention
* Add a nextcloud calendar via CalDAV

You shoud have a local calendar and a remote (nextcloud calendar) now.

#### Install/Configure E-Mail

* Configure your mail
* Get an event invitation
* Accept the event invitation

### Expected behaviour

Lightning asks the user into which calendar the event invitation should be added.

### Actual behaviour

The event will be added to the local calendar. If you have multiple local/nextcloud calendards, only the local one can be selected by the user to add the event invitation.

Since this works for a calendar from another ownCloud-server, I assume it's a issue with the CalDAV configuration of nextcloud. 

#### Workaround

Downloading the event invitations and drag & drop them to the calendar.

### Server configuration
**Operating system**: Ubuntu 14.04.5 LTS 
**Web server:** Apache/2.4.10
**Database:** 5.5.53
**PHP version:** 7.0.15
**Nextcloud version:** 10.0.3

**Comment by boldt** [comment] 2017-02-24 11:19
I just  did some debugging on that issue, because it is really annoying. Result: The behaviour depends on the mail adress inside the `ATENDEE`-option of the iCal file. 

An example:

```
ATTENDEE;RSVP=TRUE;CN=Dennis;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIP
 ANT:mailto:spam@dennis-boldt.de
```
## Case 1: I get an event intiation to a mailinglist

I.e. **Non** of the `ATENDEE`-options equal to my mail adress.

* I can add the invitation to the nextcloud calender.
* I can add the invitation to the owncloud calender.

##  Case 2: I get an invitation to my mail adress

I.e. One `ATENDEE`-option is equal to my mail adress.

* I **cannot** add the invitation to the nextcloud calender.
* I can add the invitation to the owncloud calender.

## How to reproduce

* Configure Thunderbird/Lightning as descried above
* Create a file `invite.ics` with the following content (It is a modified version of a google calendar invitation):

```
BEGIN:VCALENDAR
PRODID:WHATEVER
VERSION:2.0
METHOD:REQUEST
BEGIN:VEVENT
DTSTART:20170228T100000Z
DTEND:20170228T110000Z
DTSTAMP:20170224T091957Z
UID:n9cg6334cvrubv0p513pa9l25s@google.com
ORGANIZER;CN=Dennis Boldt:mailto:spam@dennis-boldt.de
ATTENDEE;RSVP=TRUE;CN=Dennis;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIP
 ANT:mailto:morespam@dennis-boldt.de
CREATED:20170224T091956Z
DESCRIPTION:TEST
LAST-MODIFIED:20170224T091957Z
LOCATION:TEST
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:FAILS
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

* Change the email inside the `ATENDEE`-option to your adress
* Send this file from a differnet e-mail to the adress configured in the `ATENDEE`-option
* Result: You cannot import the event invitation to the nextcloud calender, but you can import it to the owncloud calendar

**Comment by go2sh** [comment] 2017-02-24 11:51
Same problem here.

**Comment by zoide** [comment] 2017-03-06 18:33
I have the same issue.
I use the "Inverse SoGO Connector 31.0.3" for CalDAV

**Comment by MorrisJobke** [comment] 2017-07-27 12:20
cc @georgehrke

**Comment by mikersa** [comment] 2017-09-16 16:43
Same issue.
Thunderbird 52.3.0
NextCloud 11
Calendar 1.5.4

**Comment by nickvergessen** [comment] 2017-09-18 10:59
I successfully added one just two days ago:
Thunderbird 52.2.1
Lightning 5.4
Nextcloud 12.0.2

**Comment by j-ed** [comment] 2017-09-18 12:02
I successfully added the invite today. It was instantly shown in Nextcloud
but in Thunderbird I had to choose "Calendar sync ..." once to get it displayed.

Thunderbird 52.3.0
Lightning 5.4.3
Nextcloud 12.0.2

***Thunderbird:***
![20170918_tb-invite](https://user-images.githubusercontent.com/2572764/30541019-ce2a0256-9c79-11e7-9dca-b40554d0d9c9.png)
***Nextcloud:***
![20170918_nc-invite](https://user-images.githubusercontent.com/2572764/30541021-d2faedcc-9c79-11e7-88c5-b3a404c38038.png)

**Comment by boldt** [comment] 2017-09-22 19:22
I still cannot import my example from Feb, 24 Feb with the following settings:

* Thunderbird 52.2.1
* Lightning 5.4
* Nextcloud 12.0.2

**Comment by y-ates** [comment] 2017-10-11 20:12
Same here. Very annoying!

- Thunderbird 52.3.0 (64-bit)
- Lightning 5.4.3
- Provider für Google Kalendar 3.3

**Comment by skjnldsv** [comment] 2019-06-12 09:06
Pwet @georgehrke !

**Comment by georgehrke** [comment] 2019-06-12 09:17
There have been many changes to the user principal in recent Nextcloud versions, need to check if this is still reproducible.

**Comment by boldt** [comment] 2019-06-14 13:19
I'll do.

**Comment by svenseeberg** [comment] 2019-06-18 09:34
For me it worked until recently. I do not know if a Thunderbird or Nextcloud update broke it, but now I cannot accept invitations into Nextcloud calendars. Used versions: Thunderbird 60.6.1, Lightning 6.2.6.1, Nextcloud 15.0.8. I am not aware of any changed settings on my side.

**Comment by georgehrke** [comment] 2019-08-08 08:08
@boldt Any update? :)

**Comment by svenseeberg** [comment] 2019-08-08 12:50
FYI: the issue is gone (again?) in my environment.

**Comment by nickvergessen** [comment] 2019-08-20 10:46
So closing

**Closed by nickvergessen** 2019-08-20 10:46 UTC
Labels: 0. Needs triage, enhancement, feature: dav, needs info
