### ISSUE TITLE
[Bug]: Search on Files problem with Filter in Current View 28.0.2

### ISSUE THREAD

**Issue by daebak74** [nextcloud/server#43690] opened 2024-02-20 14:17 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to use the search and to Apply the filter in Current View no any response.

https://github.com/nextcloud/server/assets/11459528/22f088d1-06e8-4395-8375-da154f42435d

### Steps to reproduce

1. Type the name of the folder or files
2. Click Filter on Current View
3. No any filter are applied

### Expected behavior

In the current view should to show me only the Folders or Files type in the search.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by daebak74** [comment] 2024-02-20 16:44
This issue seems already open in this ticket.

https://github.com/nextcloud/server/issues/43365

**Comment by skjnldsv** [comment] 2024-05-23 11:59
duplicate of https://github.com/nextcloud/server/issues/43365
Fixed in recent updates

**Closed** 2024-05-23 11:59 UTC
Labels: bug, 0. Needs triage, 28-feedback
