### ISSUE TITLE
Nextcloud 10 informs about available owncloud 9.1.1 update

### ISSUE THREAD

**Issue by xshadow** [nextcloud/server#1962] opened 2016-10-31 10:36 UTC
### Expected behaviour

After a migration from owncloud 9 to nextcloud 10 a login to Nextcloud a server administrator should not get any update notifications about owncloud server updates. 

### Actual behaviour

After a migration from owncloud 9 to nextcloud 10,  the administrator is informed about owncloud updates. 

In the admin panel the updater suggests to update to owncloud 9.1.1, even if you run on nextcloud 10. 

This may lead to  a broken nextcloud instance, if you do the upgrade. 

### Server configuration

**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** mysql  Ver 14.14 Distrib 5.6.33,

**PHP version:** v7.0.11-1~dotdeb+8.1 ,

**nextCloud version:** 10.0 (former Owncloud Version 9.0.4)

**Updated from an older nextcloud or fresh install:** Updated from an older owncloud version

**Where did you install Nextcloud from:** gz-package from download page 

**Signing status:**  failed

Modifications in lib/imap.php are valid. Not yet merged https://github.com/owncloud/apps/pull/2093

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- user_external
    - INVALID_HASH
        - lib/imap.php

Raw output
==========
Array
(
    [user_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/imap.php] => Array
                        (
                            [expected] => d4ebccdc4a2f2a97456c666ef6f6608ed631ceaee3f605e270df88be08a1c3e2c3b6944f07a271612bc6fa79b708c0d9a2ee54b310e68255c415f46904665efa
                            [current] => 2b57473d0fb8855b1c4d9d24eb033efb8bf4f62cfaabbcfedf7319f282b79b76bca77664d0847b2bd43964b67db3c51c2dfc5291638931e4cc815fc88f4a3a57
                        )

                )

        )

)

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - news: 9.0.4
  - notes: 2.0.2
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - qownnotesapi: 16.09.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

``` php
<?php
$CONFIG = array (
  'forcessl' => true,
  'logdateformat' => 'Y-m-d H:i:s.u',
  'log_type' => 'syslog',
  'syslog_tag' => 'ownCloud',
  'loglevel' => 0,
  'mail_domain' => 'domain.com',
  'mail_from_address' => 'domain-owncloud',
  'mail_smtpmode' => 'php',
  'remember_login_cookie_lifetime' => '1296000',
  'session_keepalive' => true,
  'session_lifetime' => '86400',
  'trashbin_retention_obligation' => 'auto, 15',
  'trusted_proxies' => 
  array (
    0 => '192.168.123.4',
  ),
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.domain.com',
  ),
  'datadirectory' => '/var/www/cloud.domain.com/oc_data',
  'overwrite.cli.url' => 'https://cloud.domain.com',
  'overwriteprotocol' => 'https',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'user',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'user',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'default_language' => 'de',
  'mail_smtpsecure' => 'ssl',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mail.domain.com:993/imap/ssl}',
        1 => 'domain.com',
      ),
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'mail_smtphost' => 'mail.domain.com',
  'mail_smtpport' => '587',
  'theme' => '',
  'maintenance' => false,
  'appstore.experimental.enabled' => false,
  'htaccess.RewriteBase' => '/',
);


```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes , Imap
### Client 

Owncloud Desktop Client: Version 2.2.3. (Linux)

**Comment by LukasReschke** [comment] 2016-10-31 10:37
Dupe of https://github.com/nextcloud/server/issues/1945, see https://github.com/nextcloud/server/issues/1945#issuecomment-256931515

**Closed by LukasReschke** 2016-10-31 10:37 UTC

**Comment by xshadow** [comment] 2016-10-31 10:39
Sorry and  thx
