### ISSUE TITLE
Do not upgrade if PHP version is not supported by new version

### ISSUE THREAD

**Issue by sokai** [nextcloud/server#2506] opened 2016-12-05 13:12 UTC
### Steps to reproduce
1. Installed version: `10.0.1 (beta)`
2. Upgraded to `11.0 beta 2` via web-updater

### Expected behaviour
Disallow the upgrade to a newer version of Nextcloud if that doesn't support current installed but required software.

### Actual behaviour
After the successful upgrade following message is shown:
> This version of Nextcloud requires at least PHP 5.6.0
> You are currently running 5.5.9-1ubuntu4.20. Please update your PHP version.

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS _(yesiknowishouldupgrade)_

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
mysql Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37)

**Nextcloud version:** (see Nextcloud admin page)
10.0.1 (beta)

**Updated from an older Nextcloud/ownCloud or fresh install:**
(can't remember …)

**Where did you install Nextcloud from:**
(can't remember …)

**Signing status:**
<details>
<summary>Signing status</summary>

```
This version of Nextcloud requires at least PHP 5.6.0
You are currently running 5.5.9-1ubuntu4.20. Please update your PHP version.
```
</details>

PS: How can I now roll back to my working `10.0.1 (beta)` …!? :-| *thx!*

**Comment by LukasReschke** [comment] 2016-12-05 13:16
Dupe of https://github.com/nextcloud/updater/issues/53

> PS: How can I now roll back to my working 10.0.1 (beta) …!? :-| thx!

Replace all files except data and config with the 10.0.1 code.

**Closed by LukasReschke** 2016-12-05 13:16 UTC

**Comment by sokai** [comment] 2016-12-05 13:30
@LukasReschke Thx!

**Conc. the restore:** I found the backup in my data folder as `nextcloud-9.1.0.13` and restored that successfully…

**Conc. the dupe:** Sry, I missed that. – Should I close this issue here (and maybe add a comment to nextcloud/updater#53)?
