### ISSUE TITLE
Admin password protected settings not shown correctly

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/server#4259] opened 2017-04-08 13:16 UTC
Just a small bug, but some administrators could be confused:

### Actual behaviour
* Changing a admin password protected setting
* Press "Cancel" at password prompt
* **Nevertheless setting seems to be set**
* Pressing browsers F5: No changes
* Pressing browsers Strg-F5: Loads real settings again

### Expected behaviour
* Show real setting after "Cancel" was pressed

---

![bildschirmfoto vom 2017-04-08 15-09-01](https://cloud.githubusercontent.com/assets/3857906/24829202/e694bdae-1c6d-11e7-8cab-3350d864e081.png)
* Press "Allow sharing with groups"

![bildschirmfoto vom 2017-04-08 15-09-24](https://cloud.githubusercontent.com/assets/3857906/24829203/ffaadf58-1c6d-11e7-8350-c8113d3261ca.png)
* Press "Cancel"

![bildschirmfoto vom 2017-04-08 15-09-59](https://cloud.githubusercontent.com/assets/3857906/24829206/0c6df34c-1c6e-11e7-804c-21d29d9c9886.png)
* Wrong setting is displayed
* F5 does not help
* Strg-F5 displays the correct setting again

----

### Server configuration
**Operating system**: Linux owncloud 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.17

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 11.0.2 (stable) - 11.0.2.7

**Comment by MorrisJobke** [comment] 2017-04-09 01:23
cc @nickvergessen

**Comment by nickvergessen** [comment] 2017-04-10 10:54
Needs help from JS experts. The dialog currently does not have something for when cancel/esc is pressed.

**Comment by skjnldsv** [comment] 2019-10-30 20:52
Ah, duplicate of https://github.com/nextcloud/server/issues/2395

**Closed by skjnldsv** 2019-10-30 20:52 UTC
Labels: 1. to develop, bug, design, feature: settings, feature: sharing, good first issue
