### ISSUE TITLE
[Bug]: Logging page freezing/not showing details

### ISSUE THREAD

**Issue by LM-vb** [nextcloud/server#45553] opened 2024-05-28 16:32 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 29.0.1

After the upgrade from 28.0.5 to 29.0.1 the logging page gets unresponsive/freezes after a certain amount of time (polling?). Additionally, it is no longer possible to show the details (three-dots-menu) of an entry on the logging page. The tab freezes, often crashes. The console gives the following errors (when trying to show details via three-dots-menu):

![image](https://github.com/nextcloud/server/assets/91881322/98db9450-0c8c-4656-86f3-bd7fc336a207)

The bug triggers on different browsers (Chrome, Firefox, Safari).

### Steps to reproduce

1. Upgrade to NC 29.0.1
2. Access Administration -> Logging
3. Wait some time resp. try to access the details of an entry in the three-dots-menu

### Expected behavior

The page should not freeze/details of an entry should be shown. This worked up until NC 28.0.5.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Lawkss** [comment] 2024-05-28 22:09
I have same problem mentioned here:

https://github.com/nextcloud/logreader/issues/1262

**Comment by Ornanovitch** [comment] 2024-05-30 07:55
Confirmed on my side: same NC version, same console errors

**Comment by joshtrichards** [comment] 2024-05-30 22:08
Duplicate of nextcloud/logreader#1262

**Closed by joshtrichards** 2024-05-30 22:08 UTC
Labels: bug, 0. Needs triage, 29-feedback

**Comment by Ornanovitch** [comment] 2024-05-31 08:49
Maybe a duplicate, but just notice that there is no firefox crash on our side, just js console errors

**Comment by mihailaks** [comment] 2024-06-07 10:33
Confirmed on my side: same NC 29.0.2 version, same console errors
