### ISSUE TITLE
Android CalDAV-Sync does not sync after Nextcloud upgraded to 18.0.4

### ISSUE THREAD

**Issue by alars** [nextcloud/server#21099] opened 2020-05-25 18:12 UTC
### Steps to reproduce
1. Add a calender item using the Nextcloud Calendar App
2. Add another item in the Android calendar
3. Await periodic sync or force a manual sync

### Expected behaviour
Item no. 1 should appear in the Android calendar
Item no. 2 should appear in the Nextcloud calendar

### Actual behaviour
Absolutely nothing happens
(CardDAV is not affected and works as expected)

### Analysis
A client access without credentials yields a 404 error from the server.
On Nextcloud 18.0.3 (and before) it yields a 401 error and retries (successfully) with credentials.
I tracked it down to commit ce8f194a2a77a5f5cad62d9de4da033a67b4c927 - reverting this commit restored the previous behaviour and solved the problem.

### Server configuration

**Operating system:**
Ubuntu 18.04.4 LTS

**Web server:**
Apache 2.4.29

**Database:**
MariaDB 10.1.44

**PHP version:**
PHP 7.2.24

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0.3

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.10.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.1
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.4.1
  - files_ebookreader: 0.0.1
  - files_pdfviewer: 1.7.0
  - files_readmemd: 1.1.4
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - gpxpod: 4.2.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - music: 0.14.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.4.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - phonetrack: 0.6.3
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - qownnotesapi: 20.1.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - comments
  - federation
  - files_external
  - files_versions
  - recommendations
  - systemtags
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "hashingCost": 10,
        "trusted_domains": [
            "mads.alarsen.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "18.0.4.2",
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "defaultapp": "apporder",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "default_language": "de",
        "allow_user_to_change_display_name": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "asset-pipeline.enabled": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "trashbin_retention_obligation": "auto, 30",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 10485760,
        "skeletondirectory": "\/var\/www\/nextcloud\/local\/skeleton",
        "overwrite.cli.url": "https:\/\/mads.alarsen.net\/owncloud",
        "htaccess.RewriteBase": "\/owncloud",
        "updatechecker": true,
        "updater.release.channel": "stable",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "forcessl": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "singleuser": false,
        "loglevel": 2,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "calendar",
            "files_ebookreader",
            "files_readmemd"
        ],
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
CalDAV Sync (latest version)

**Operating system:**
Android 8.0

#### Web server error log
<details>
<summary>Web server error log with error occurring (18.0.4) </summary>

```
"OPTIONS /owncloud/remote.php/dav/calendars/<user>/<calendar>/ HTTP/1.1" 404 238
```
</details>
<details>
<summary>Web server error log without error (18.0.3) </summary>

```
"OPTIONS /owncloud/remote.php/dav/calendars/<user>/<calendar>/ HTTP/1.1" 401 450
"OPTIONS /owncloud/remote.php/dav/calendars/<user>/<calendar>/ HTTP/1.1" 200 -
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing reported.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
CalDAV Sync fails silently :-(
```
</details>

**Comment by kesselb** [comment] 2020-05-26 08:27
Duplicate of #20624. Fix is already confirmed for next release.

**Closed by kesselb** 2020-05-26 08:27 UTC
Labels: 0. Needs triage, bug
