### ISSUE TITLE
Adding multiple share links is confusing

### ISSUE THREAD

**Issue by jhesketh** [nextcloud/server#18321] opened 2019-12-10 10:46 UTC
**Is your feature request related to a problem? Please describe.**
When adding multiple share links they all just appear as "Share link" in the list of shares. This is confusing.

**Describe the solution you'd like**
Perhaps by default, after the second share link is added they start to appear as "Share link 1", "share link 2", etc.

**Describe alternatives you've considered**
Also worth considering being able to name share links for personal use. For example, I might use it to note who I've handed the link to. This would need to be worded/set out carefully to not be confused with what might be shown to the recipient.

**Comment by juliushaertl** [comment] 2020-06-25 06:36
Duplicate of https://github.com/nextcloud/server/issues/15500

**Closed by juliushaertl** 2020-06-25 06:36 UTC
Labels: 0. Needs triage, enhancement
