### ISSUE TITLE
Direct opening of files

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#21338] opened 2020-06-09 10:43 UTC
**Is your feature request related to a problem? Please describe.**
Users are used to send each other direct link to the documents stored in Nextcloud. When clicking on them I am addressed to the folder with documents. Though the file is highlighted somehow it is not obvious what to do with it. Some people feel frustration not seeing the file opened.

**Describe the solution you'd like**
The direct links of shared documents should lead to processing these documents by the apps of Nextcloud (if available), and if not available, to show a message about missing apps with suggestions either to install them, open with another app or to download the file locally. This is well implemented in Google Drive. 

**Describe alternatives you've considered**
Now available solution, when the folder is just shown.
Possible easy solution is to open with available apps, if not available to show file in the folder.

**Additional context**
If a user doesn't have access to the file, to show a button to request it.

**Comment by ostasevych** [comment] 2020-06-11 21:51
I may add that it works with OnlyOffice, but not with the Collabora Online.

**Comment by kienanstewart** [comment] 2020-08-14 15:58
This is a change that our team has felt the need for as well, and we've seen others frustrated by the current functionality. I've found that the behaviour isn't always consistent either, for example using NextCloud 18 with Collabora and sharing an "odt" file:

  * Using an internal link: the folder is open and the item is scrolled to with highlight
  * Using a shared link (w/ password set): an logged in or anonymous user is present the file rendered in Collabora

**Comment by lelutin** [comment] 2020-08-14 18:15
to add some details about the second point in @kienanstewart 's comment: I've also seen cases where using a shared link (which is currently the only way to get the files to show directly) caused me to get logged out of NextCloud, which is rather unfortunate when you need to open files all day long.

**Comment by alexanderdd** [comment] 2021-01-04 23:41
@ostasevych I think  this is a duplicate of https://github.com/nextcloud/server/issues/12470
If it is, please close.

**Comment by juliushaertl** [comment] 2021-04-01 13:02
Yep, let's continue in https://github.com/nextcloud/server/issues/22541

**Closed by juliushaertl** 2021-04-01 13:02 UTC
Labels: 0. Needs triage, enhancement
