### ISSUE TITLE
automatic color adjustments should take place based on the selected theme color

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#7441] opened 2017-12-10 17:48 UTC
## Expected behavior
Depending on the selected theme color the notification alert color, and maybe others, should automatically be adjusted to be still visible.

## Current behavior
No automatic color adjustments seems to take place at all.

### Steps to reproduce
1. Open the admin settings.
2. Change the theming color to `FF0000`.
   ![20171210_nc_theming_color](https://user-images.githubusercontent.com/2572764/33807600-9e0704f6-ddd9-11e7-8e9a-06951ca34fbe.png)

3. Check the notification symbol in the menu bar
![20171210_nc_theming_alert_color](https://user-images.githubusercontent.com/2572764/33807601-a297b830-ddd9-11e7-94d7-b9c0119b5b21.png)

4. The notification alert is nearly invisible.

Better visibility could look like this:
![20171210_nc_theming_alert_better_color](https://user-images.githubusercontent.com/2572764/33807680-b1de6ff4-ddda-11e7-8d7e-5d9dbb83a22c.png)

#### Server Configuration
OS: Linux 3.16.50
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.4

#### Client Configuration
Browser: Mozilla Firefox 57.0.2
Operating system: Windows 7

**Comment by MorrisJobke** [comment] 2017-12-11 12:35
@nextcloud/designers @nextcloud/theming I guess that is as of now not easily possible, right?

**Comment by juliushaertl** [comment] 2017-12-11 21:19
I guess the issue is not only #ff0000 but also other red color values as well, so we need a wider check for that. 

@j-ed That issue should be addressed in the notifications app. Can you please open the issue at https://github.com/nextcloud/notifications

**Closed by juliushaertl** 2017-12-11 21:19 UTC
Labels: enhancement, feature: theming
