### ISSUE TITLE
The stop icon gets stuck when switching from the “Tags” tab to “All files”

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#16577] opened 2019-07-27 06:54 UTC
NC 16.0.3 (Docker)

### Steps to reproduce
1. Open "All files" tab
2. Switch to "Tags" tab
3. Go back to "All Files" tab

### Actual behavior
![image](https://user-images.githubusercontent.com/9205230/61991130-73ea7f00-b054-11e9-8058-dfeed36482d9.png)

**Comment by kesselb** [comment] 2019-07-27 16:35
Thank you :+1: 

Duplicate of https://github.com/nextcloud/server/issues/16137. Fix https://github.com/nextcloud/server/pull/16437 is part of Nextcloud 16.0.4.

**Closed** 2019-07-27 16:36 UTC
Labels: 0. Needs triage, bug
