### ISSUE TITLE
Rename folder does not work properly

### ISSUE THREAD

**Issue by Mululu** [nextcloud/server#16393] opened 2019-07-14 12:11 UTC
Actual behaviour
if a folder is created with a name such as "Test 15.06.19" and you then rename it z.b. without date then this will not be displayed. Nextcloud thinks it is a file without a file type. Same in the web browser.

It's the same thing the other way round. Rename folder from "Test" to "Test 15.06.19". Then Nextcloud thinks that the 19 is the end of the file type. For a folder Nextcloud should not think that there are file types.

See Windows folder there is no problem to use points.

Steps to reproduce
Create Folder with Name "Test 12.06.19"

Rename Folder into "Test"

Folder no longer appears as a folder

Create Folder with Name "Test"

Rename Folder into "Test 15.06.19"

Folder no longer appears as a folder

Nextcloud server version:

16.0.3 newest App Version

Nextcloud log (data/nextcloud.log
...Nothing...

**Comment by kesselb** [comment] 2019-07-14 13:51
Please add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).

**Comment by kyhuynhduc** [comment] 2019-07-15 03:49
> Please add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).
same with my issue, please check #16140

**Comment by kyhuynhduc** [comment] 2019-07-15 04:12
FYI
Step1: create group folder with name: "abcd abcd"
step2: go in side /abcd abcd
step3: create folder with name " new folder"
step4: rename " new folder " to " new folder.test"

result: folder "new folder.test" corrupted.

![Jul-15-2019 11-07-42](https://user-images.githubusercontent.com/36893030/61195250-f7b97880-a6f0-11e9-9cc9-3b7705fd9a4c.gif)

**Comment by juliushaertl** [comment] 2019-07-30 08:19
Duplicate of https://github.com/nextcloud/groupfolders/issues/518

**Closed by juliushaertl** 2019-07-30 08:19 UTC
Labels: 0. Needs triage, bug, needs info
