### ISSUE TITLE
Values of filesize are displayed with "." (Dot) instead of "," (comma)

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/server#7837] opened 2018-01-13 06:45 UTC
### Steps to reproduce
1. Open Nextcloud Webinterface
2. Watch the filesize values 

### Expected behaviour
In my case the values are expected to have the "," like 100,8 MB

### Actual behavior
Values of filesize are displayed with "." (Dot), witch is wrong for my locale (German)

![auswahl_20180113_07 34 57](https://user-images.githubusercontent.com/2804301/34903566-57e71d1a-f834-11e7-8fbf-160f8b8a8fb3.png)
See also my old issue @OC repository: https://github.com/owncloud/core/issues/20674#issuecomment-357396942

### Server configuration

**Operating system**: Linux HP-T610 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Web server:** Apache2

**Database:** mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )

**Nextcloud version:** 12.0.4

**Updated from Nextcloud**

```
Alle Überprüfungen bestanden.
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
[/var/www/nextcloud] # sudo -u www-data php occ app:list
Enabled:
  - activity: 2.5.2
  - audioplayer: 2.2.2
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_downloadactivity
  - files_external
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
[/var/www/nextcloud] # sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "ocgv3ctfvkf0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "darkwing.ddns.net",
            "HP-T610"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/darkwing.ddns.net\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logtimezone": "UTC",
        "installed": true,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_from_address": "Darkwing",
        "mail_domain": "Quantentunnel.de",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 57.0.4

**Operating system:** Linux Mint 18.3 Cinnamon

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Fatal | webdav | Sabre\DAV\Exception\Conflict: Parent node does not exist | 2018-01-05T14:51:04+0100
-- | -- | -- | --
Info | updater | \OC\Updater::resetLogLevel: Reset log level to Warning(2) | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::maintenanceDisabled: Turned off maintenance mode | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::updateEnd: Update successful | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::finishedCheckCodeIntegrity: Finished code integrity check | 2017-12-04T12:54:44+0100
Info | updater | \OC\Updater::startCheckCodeIntegrity: Starting code integrity check... | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Rename folder with user specific keys | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair invalid paths in file cache | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Install new core bundle components | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair language codes | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: No mounts updated | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Fix potential broken mount points | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Add preview cleanup background jobs | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: Repair step already executed | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Add move avatar background job | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: .step file moved to .step-previous-update | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: .step-previous-update removed | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: .step file exists | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Move .step file of updater to backup location | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Remove shares of a users root folder | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair invalid shares | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tags with no entries have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tag entries for deleted tags have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tags for delete files have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: 0 tags of deleted users have been removed. | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Clean tags and favorites | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair mime types | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::info: Repair info: All tables already have the correct collation -> nothing to do | 2017-12-04T12:54:35+0100
Info | updater | \OC\Repair::step: Repair step: Repair MySQL collation | 2017-12-04T12:54:35+0100
Info | updater | \OC\Updater::checkAppStoreApp: Checked for update of app "workflowengine" in appstore | 2017-12-04T12:54:35+0100


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2018-01-14 23:04
cc @nextcloud/javascript

**Comment by danxuliu** [comment] 2018-01-15 22:04
The problem is that [`humanFileSize`](https://github.com/nextcloud/server/blob/de5467811a52abcc16d0b536136e09f1b614d79c/core/js/js.js#L1765) does not take into account the current locale. This could be fixed by using something like [`toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString); please note that when fixing this [its unit tests](https://github.com/nextcloud/server/blob/9c22e99331fe7261c575bc26e2381d78c189521d/core/js/tests/specs/coreSpec.js#L563) should be extended if possible ;-)

There is also room for improvement regarding the internationalization of the strings in `humanFileSize`, for example to be able to localize the order of number and units (among other things).

**Comment by blizzz** [comment] 2018-01-16 10:02
related: locale settings #5623

**Comment by dasisdormax** [comment] 2018-02-26 20:57
Hello,

thanks @danxuliu for the suggestions. I also used the `t()`-function to make the units translatable. Didn't update the tests yet.

i've updated the `humanFileSize` javascript function and now it looks like this (german locale):
![screenshot-2018-2-26 bums - dateien - nextcloud_li 2](https://user-images.githubusercontent.com/3714905/36694207-f06f4f40-1b3d-11e8-8b3b-470ee6e97000.jpg)

Two problems I need some help with:
- the `t()` function escapes the 'less than' sign, making it render as &lt;
- the quota usage (bottom left) is rendered in a different way (maybe by a PHP function)

Also, as I was already touching this function, I changed the units from 'KB', 'MB' to 'KiB' to 'MiB' (I'm always confused whether 'KB' means 1000 or 1024). Which way do you all prefer it?

**Comment by dasisdormax** [comment] 2018-02-27 09:46
> Also, as I was already touching this function, I changed the units from 'KB', 'MB' to 'KiB' to 'MiB' (I'm always confused whether 'KB' means 1000 or 1024). Which way do you all prefer it?

Thinking about it again, leaving the units as they are may be the better choice. We'd have to change them in a lot of other places and may create an inconsistent user interface.

**Comment by tflidd** [comment] 2018-03-04 15:58
Back in owncloud times it was decided to keep the wrong naming of file sizes like Windows to avoid confusions:
https://github.com/owncloud/core/issues/13386

**Closed** 2018-10-25 12:05 UTC
Labels: Hacktoberfest, good first issue, papercut
