### ISSUE TITLE
Large external CIFS storage = large DB table oc_filecache

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#20349] opened 2020-04-07 16:37 UTC
Hello,
We have a problem on nextcloud.
The version is 17.0.2.

Our users have access to external storage in CIFS (Windows server). But some users cannot list files present in the CIFS despite the presence of rights.

In order to correct the problem we used the command "sudo -u www-data php/var/www/nextcloud/ occ files: scan --unscanned --all", in this way we wanted to scan all the files which did not had not been, in order to overcome the problem of "display".

After approximately 18 hours of operation the order was at the "Starting scan for user 50 out of 234 (XXXX)" stage.

We checked the size of the database which increased to 11GB.
root @ ServNCloud: ~ # du -h / var / lib / mysql
11G / var / lib / mysql / nextcloud
8.0K / var / lib / mysql / performance_schema
1.5M / var / lib / mysql / mysql
11G / var / lib / mysql

The largest table being:
-rw-rw ---- 1 mysql mysql 11G April 7 09:46 oc_filecache.ibd 

Why Nextcloud store external path inside db instead use SMB connection each time ? 
For Exemple inside table i found 76 time the same path with other id.

For Exemple 1 file on external storage with 10 users mean 10 lines inside database.
20000 files on external storage with 300 users mean : 6000000 lines...

Best regards.

**Comment by acs-ferreira** [comment] 2020-04-07 18:52
Follow https://github.com/nextcloud/server/issues/7312

**Comment by szaimen** [comment] 2021-05-31 11:45
Duplicate of https://github.com/nextcloud/server/issues/7312

**Closed by szaimen** 2021-05-31 11:45 UTC
Labels: 0. Needs triage, bug
