### ISSUE TITLE
Update to 16 fails : calendar update failure

### ISSUE THREAD

**Issue by ericcotelnu** [nextcloud/server#15617] opened 2019-05-19 01:23 UTC
### Steps to reproduce
1. try to update
2.
3.

### Expected behaviour
successful update

### Actual behaviour
error with dav and calendar

index and new column creation fails, instead of checking if they exist, it tries to create the indices, and new columns, which takes down the whole update process.

### Server configuration

**Operating system**:
Debian 10

**Web server:**
NGiNX
**Database:**
MySQL/MariaDB

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
15/16

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
commandline (usually web update, but that failed to above issue)

**Comment by dirigit** [comment] 2019-05-19 04:44
I confirm such behaviour in similar environment.
Debian, PHP 7.2, mySQL, nc 15.0.8 -> 16.0.1

Upgrade had to be performed via occ as well. Afterwards missing indexes (occ db:add-missing-indices fixed it), incompatible Apps  so on.

No entry about errors in any log.

To get rid of those unreliable and therefor very nagging integrity check messages I added   'integrity.check.disabled' => true permanent to config.

**Comment by kesselb** [comment] 2019-05-19 08:21
Mind to share which indicies and columns are the problem?

**Comment by dirigit** [comment] 2019-05-20 05:38
I'm sorry but, I can not find specific entries in any log.

At the time performing the upgrade I've been in hurry and didn't watch terminal window that close. AFAIR there have been five or six repair actions.

**Comment by skjnldsv** [comment] 2020-08-25 09:14
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:14 UTC
Labels: 0. Needs triage, bug
