### ISSUE TITLE
Show apps with available updates first

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#1236] opened 2016-09-01 21:47 UTC
### Expected behaviour

The notification tools says that updates are available for several apps. I go to the app page and expect them on the top.
### Actual behaviour

You have to scroll through the list and must not miss any update. Not a nice user experience.
Was already reported for owncloud: https://github.com/owncloud/core/issues/22892

Would be nice to get it into the NC10-polishing: https://github.com/nextcloud/server/issues/735
### Server configuration

**Nextcloud version:** 10.0

**Comment by mar1u5** [comment] 2016-09-02 05:53
Thank you for your report. I think this is a good idea. Maybe we could do this together with the new appstore 😅 @BernhardPosselt 

> Would be nice to get it into the NC10-polishing: #735

Don't know wether we should/do backports of such enhancements.

cc'ing @jancborchardt @nickvergessen @MorrisJobke because you were commented on https://github.com/owncloud/core/issues/22892 😉

**Comment by nickvergessen** [comment] 2016-09-02 07:35
The problem with the current page is, that the update information is collected in the background, because it takes quite a while to send those 20+ requests to the appstore (one for each app because of the endpoint design of the old app store).
I don't think it's a good idea to resort the apps after a random time frame. The admin might just want to hint a "disable" button and accidently disable a wrong app without noticing.

In the future it will hopefully only be one request, then we can do it better.

**Comment by BernhardPosselt** [comment] 2016-09-02 08:06
New app store will only require one request (with http caching)

**Comment by mar1u5** [comment] 2016-09-02 13:13
- A seperate Site for Apps which can be updated
- An "update all" Button which indicates which apps will be affected

**Comment by MorrisJobke** [comment] 2017-04-30 22:07
Duplicate of #838

**Comment by jancborchardt** [comment] 2017-05-01 15:07
It's an addition to #838 but not a duplicate. The default view should be as useful as possible so apps with updates should be sorted up top without needing to switch the view.

This is similar to favorites in files: There is a specific section for it, but it's much nicer and integrated (and quick to acess these important things) if these items are actually simply sorted up top.
Same for combining Activity+Notifications. ;)

**Comment by juliushaertl** [comment] 2017-10-10 12:58
Fixed with #6740

**Closed by juliushaertl** 2017-10-10 12:58 UTC
Labels: 1. to develop, enhancement, feature: apps management, papercut
