### ISSUE TITLE
Make 'timeout for http requests' a configurable item

### ISSUE THREAD

**Issue by TP75** [nextcloud/server#18103] opened 2019-11-25 12:25 UTC
was https://github.com/nextcloud/server/pull/17807#issuecomment-558101692
> 30 seconds is a reasonable default. If we require a longer timeout on some requests, we should specify them on those requests individually

This may be correct and technically valid from the devs point of view.

However, please make 'timeout for http requests' one or more configurable items in `config.php` or beyond to better meet the real world requirements of server admins and users.

**Comment by TP75** [comment] 2019-11-25 16:04
#17808

**Comment by akoyaxd** [comment] 2020-01-12 17:48
This would be a HUGE improvement for Federated Sharing.
I'm getting a lot of CURL 28 Errors due to too large files, that can't be fetched in 30 seconds.

Is it possible to change the timeout manually right now?

**Comment by psrcek** [comment] 2020-01-20 22:35
How is this STILL not addressed?? Hello?? I can't upload my files or install any decent app due to this!

**Comment by akoyaxd** [comment] 2020-01-21 07:26
Like nickvergessen in #17808 said:

> this value here only affects your nextcloud connecting with other nextclouds, the appstore, .... Not the user-to-nextcloud connection

So, if you have issues with uploading files to your Nextcloud (without federated sharing) you are looking for a different issue. Probably a config issue in your Webserver and / or php.

How much bandwidth does your Nextcloud have, that it gets a timeout during you App installation?

**Comment by Dmry** [comment] 2020-01-27 12:32
Just came here to say that this PR fixed a timeout that made me unable to download the larger apps (e.g. Community Document Server).

**Comment by loxK** [comment] 2020-01-31 00:48
It is crazy to not being able to update apps, like the mail app, because of a hard coded timeout being on a 30  Mbit/s  fiber connection!

**Comment by qgymib** [comment] 2020-02-16 10:43
Why not add a "Cancel" Button and set unlimited timeout?

**Comment by flexibeast** [comment] 2020-02-22 07:29
To provide another data point: my server here in Australia sits on a broadband connection with a reported speed (according to ozspeedtest.com) of 42.92 Mbps, and with each upgrade of Nc, i'm modifying lib/private/Http/Client/Client.php to a higher timeout value.

**Comment by KopfKrieg** [comment] 2020-02-22 13:54
> […] 42.92 Mbps, and with each upgrade of Nc, i'm modifying lib/private/Http/Client/Client.php to a higher timeout value.

Why? With your connection you should be able to download apps with a size of up to 150MB. Nextcloud 18.0.1 also [overwrites the default timeout value with 120 seconds](https://github.com/nextcloud/server/pull/19025), which means you're able to download up to 630MB, which is more than enough right now.

**Comment by flexibeast** [comment] 2020-02-23 00:00
@KopfKrieg: In theory, yes. In practice, in my experience, no. When i reinstalled 18.0.0 from scratch recently, and tried to install basic apps like Calendar and Contacts, the installations failed unless i set a higher timeout value. i just upgraded to 18.0.1 yesterday, so i can't remember what that timeout value was; but after the upgrade, i still needed to set the timeout to a higher value (i ended up setting it to 300s) to get an app update to work. Cf. also https://github.com/janis91/ocr/issues/249#issuecomment-578330599.

**Comment by loxK** [comment] 2020-02-24 08:49
The theoretic bandwidth and the real bandwidth are two different things in some parts of the world to other parts of the world. Latency is also impacted.

**Comment by nooblag** [comment] 2020-03-03 06:40
I'm also in Australia and have problems with extreme network latency with *.nextcloud.com servers. Hacking core files to increase a hardcoded timeout should be considered a bug.

**Comment by Mohammed-Al-Haidary** [comment] 2020-04-09 13:19
Hi there,

I have a 300 Mbps internet speed but I still face this issue. I had to set my cURL timeout as high as 1200 ms to be able to install/update my apps. So I don't think internet speed is the only element causing this issue.


> 
> 
> Why not add a "Cancel" Button and set unlimited timeout?

This seems like a good solution 👍, atleast temporarily until we get to the root(s) of this issue.

**Comment by loxK** [comment] 2020-04-13 21:38
Two days ago I had to increase the curl timeout too because no app was showing in the WebUI. Even the `occ app:update -- all` command wasn't able to update and was showing no output.

**Comment by loxK** [comment] 2020-05-11 01:34
I had to do it again today, as upgrade override the changes.

**Comment by zwets** [comment] 2020-05-15 23:26
Please also note that some users can only dream of speeds above 20Mbps. On a shared line, on an average day, it's more like 2Mbps where I live (and in many other places on the African continent). 

Short timeout values that work in the better-connected parts of the world certainly don't work here.

**Comment by brasofilo** [comment] 2020-05-17 18:37
lol, 2Mbps
I'm in the middle of nowhere with a Hughesnet connection... most of the time it's a dial up modem crap speed from the 90's

**Comment by zwets** [comment] 2020-05-21 08:45
> ... most of the time it's a dial up modem crap speed from the 90's

Malconnected of the world, unite! :-) But on a serious note: the lack of good network connectivity is precisely why I, and I presume others in comparable settings, resort to on-premise solutions. 

Yes, we can use the likes of Google docs, but if 90% of users is in-house, while the 10% outside are on slow connections anyway, it makes perfect sense to invert the architecture: put the cloud in the house and open it to outside. That's why NextCloud is such a blessing.

**Comment by arjan-s** [comment] 2020-07-08 20:30
Like @akoyaxd said, this is still a big problem when using federated shares. I had to manually increase the timeout in Client.php to make uploading/downloading large files on a federated share work. The correct fix there would be to make the federated connection between two servers use chunking, like the official clients do for regular uploads, but that's a big change. Making this timeout configurable would quickly help a lot of people (see all the issues about this problem!), while fixing federated shares in the background for a future release.

**Comment by stellarpower** [comment] 2020-09-30 22:53
I am, like many, running my Nextcloud off low-end hardware, namely a raspberry Pi. In my case the theoretical bandwidth I get from my ISP at my flat isn't as much of an issue, nor the less-than-optimal wireless signal through the incredibly thick walls of 1860s properties in Edinburgh. I'm limited by a small amount of RAM (shared with ZFS) and storage off USB2, with docker for several containers, and not a great deal of processing power. I'm not running a sevrer for a corporation with dedicated rackspace, like lots of people I'm getting sick of having a million online accounts and being space-limited on these unless I hand over a monthly subscription, so I am running a personal server where I have control over my data and access to my appss remotely. In tihi case, low power usage is a must for a home server when energy costs and noise and heat are of relevance if it's on 24/7.

__TL;DR__: A debate on whether or not the default value *should* be enough is a bit of a moot point in my view, if it seems that for multiple people, it isn't. I am drawn to a private cloud so I can configure things on my hardware with my data my way, so by all means having a recommended default is sensible, but I don't see any reason why it shouldn't be advantageous to make some of these options configurable (I have also been hit by the upload timeouts and size limits etc.) as we come here with quite differntt scenarios and hardware/connection speeds, and given the number of bugs filed it seems many people are coming across htis issue and it's not got a root cause anywhere else.

**Comment by wuast94** [comment] 2020-11-30 19:54
never had this problem but now i have, there are some apps im unable to install on a connection with10MB/s download.
Thats horrible, and there seems no activity on this issue, this issue should really be adressed in near future :)

**Comment by PhilippMundhenk** [comment] 2020-12-19 19:31
Since the issue above was closed with reference to this, I will contribute here now:

I have looked into it a little more and I don't think increasing timeouts or making them configurable will help with the problem of installing apps in the long run.
It seems apps are downloaded from GitHub Releases, at least that's where the appstore references them. This is notoriously slow. I am downloading with 2kB/s on a Saturday evening in central Europe.
A server infrastructure with more bandwidth per download is clearly required. Seeing that Nextcloud is heavily advertising it's enterprise usage, maybe they will consider setting something like this up. Although in this case, it will likely come at a premium.

Other workarounds could consider checking out the source code of apps and building them locally, of course with the downside of the build tooling overhead. But at least it would be possible to use apps then.

Otherwise, as unfortunately there seems to be little concern to fix this, as evident by the responses to this issue over more than a year, I fear that's it with Nextcloud for me. Without the option to download any app, the features are limited to less than what my NAS offers out of the box. It looks like it could become some good software, what I have seen looks really good. Maybe I'll try again in a year or two.

**Comment by wuast94** [comment] 2020-12-19 21:06
you are wrong on this, its not their servers, its a problem from your ISP .. in my case Deutsche Telekom. They dont want Peer properly with Github/Amazon and this is causing this issue. Bad ISP that want to get double paid their traffic (from you and from the service)

**Comment by PhilippMundhenk** [comment] 2020-12-19 21:16
Really? I have never seen fast downloads on GitHub for releases on any connection. Though I have to admit my sample set is small, when reducing it to ISPs...

**Comment by wuast94** [comment] 2020-12-19 21:26
just make a wget from a bigger github release file and look at the speeds

**Comment by tlhonmey** [comment] 2021-01-04 20:32
Note that there are two timeouts.  One is 30 seconds for app store updates, and the other is 120 seconds for downloading actual apps.  

That latter one actually seems to be the more common problem as 120 seconds isn't enough to download the larger apps like the Collabora server on a common, 10mbit residential Internet connection.

See:  https://help.nextcloud.com/t/solved-nc-18-0-1-default-timeout-limit-for-app-download-still-too-tight-override-is-being-ignored/70985/7

**Comment by nooblag** [comment] 2021-01-04 23:41
> Note that there are two timeouts. One is 30 seconds for app store updates, and the other is 120 seconds for downloading actual apps.

I'm just wondering what the rationale is for hardcoded timeouts in any event. i.e. Why have a time limit on downloading a file? Surely it's done when it's done and if it fails it fails?

**Comment by szaimen** [comment] 2021-06-22 09:32
Please use the command line to install big apps if your connection is too slow to download apps in 120s as the [timeout is disabled for CLI](https://github.com/nextcloud/server/pull/19430).

Otherwise: as this sounds like a nice feature, currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Closed by szaimen** 2021-06-22 09:32 UTC
Labels: 0. Needs triage, bug

**Comment by nooblag** [comment] 2021-06-22 12:32
Disappointing, but sure.

**Comment by arjan-s** [comment] 2021-06-22 12:37
@szaimen Does that also mean that federated sharing has become an unsupported feature? This timeout has been a big problem for transferring large files over a federated share. To make federated sharing work with large files, we still have to increase this timeout by a lot, because otherwise the upload or download just fails.

**Comment by szaimen** [comment] 2021-06-22 12:39
> Does that also mean that federated sharing has become an unsupported feature?

No.

**Comment by szaimen** [comment] 2021-06-22 12:39
cc @nextcloud/sharing

**Comment by ruedigerkupper** [comment] 2021-09-08 10:21
I ran into this problem using federated sharing, too. Trying to transfer files from my own private Nextcloud instance (slow server, low bandwidth) to company's nextcloud. Very frustrating. Seems I have to carry my files to the company using an external USB-disk. Why has federated sharing this limit? It's massively reducing usability, since I can never be sure if my files will transfer or not.

**Comment by AnsgarKlein** [comment] 2021-10-08 18:46
I have the same problem with federated sharing:
700MB file shared from Nextcloud Server (running 20.0) via Federated Share to Nextcloud Server (running 22.2) will not get downloaded from Nextcloud Client 3.3.3.
German error message still mentions 30 second timeout which makes federated sharing basically unusable for me.

```
Server hat "500 Internal Server Error" auf "GET https://federatedserver/sharedfile" geantwortet
(cURL error 28: Operation timed out after 30000 milliseconds with 11333368 out of 779841919 bytes received)
(see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by Intenos** [comment] 2021-12-28 14:43
I have the same issue with the Federated Share and Nextcloud 23.0.0. Is there an open issue where this problem gets addressed?

**Comment by arjan-s** [comment] 2021-12-28 19:01
@Intenos I'm afraid this is the issue. You're not the only one hit by this bug. Regardless of the comment by @szaimen in June, I think federated sharing is something that's not used by the developers themselves, so they don't hit these kind of bugs and don't care for them.

**Comment by ruedigerkupper** [comment] 2021-12-29 18:08
@arjan-s But then federated sharing is a major advertising point on nextcloud.com:
https://nextcloud.com/federation/
You'd expect the developers to want that work just as advertised?

**Comment by agoeckner** [comment] 2023-07-11 01:21
Has there been any progress on this federation issue? Sorry, late to the party here.

**Comment by Gsam333** [comment] 2023-11-20 06:25
The timeout issue in connecting to Nextcloud on Mac is caused by the network connection configuration, which is set to "Specify proxy manually." To resolve this problem, you simply need to go to the "Proxy Settings" in the "Network" section of the settings and change it to "No Proxy." This will fix the issue and allow you to connect to Nextcloud without any timeout errors.

**Comment by a-0-dev** [comment] 2024-03-22 09:53
I want to emphasize that this is a real and major issue. If Nextcloud Federation is used with larger files, this issue WILL spam your error logs and cause inconsistent folder sync. Also, all nextcloud desktop clients will not show the green sync tick unless you unlink the federated folder with bigger files in it.

I'm not sure how much work it would be to increase the cURL timeout, but this is crucial to one of the major features of nextcloud, federation.

**Comment by aerusso** [comment] 2024-03-25 04:10
I was able to address this for federated sharing by following [these instructions](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_files/big_file_upload_configuration.rst#federated-cloud-sharing).   Specifically:

```
occ config:system:set davstorage.request_timeout --type=int --value 90
```

(this is a 90 second timeout).

If you are using nginx, you should probably also set `client_header_timeout` to a value at least as large as that, since the server is apprently first downloads the file completely from the remote federated server before even starting to streaming it to the client.
