### ISSUE TITLE
Custom login background image upload fails silently

### ISSUE THREAD

**Issue by robinmetral** [nextcloud/server#21174] opened 2020-06-01 11:20 UTC
Related: https://github.com/nextcloud/server/issues/18328

### Steps to reproduce
1. Open Nextcloud
2. Go to Administration Settings > Theming
3. Upload a large login background image (20mb)

### Expected behaviour
It should succeed, but if it doesn't, a user-friendly error should be shown.

### Actual behaviour

- UI: The operation failed silently, and the loading indicator kept animating.
- Network request: a POST request is sent but never resolves. (ran for 5min+ without timing out)
- Browser console output:
  ```
  TypeError: response._response.jqXHR.responseJSON is undefined
  ```

After optimizing the image down to about 500kb, the operation succeeded, therefore I'm assuming that the issue is related to a maximum upload size. However I haven't found any documentation for it.

### Server configuration

**Operating system:** Ubuntu 20.04
**Web server:** nginx
**Database:** MariaDB
**PHP version:** 7.4
**Nextcloud version:** 18.04
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install
**Where did you install Nextcloud from:** latest docker image
**Signing status:** n/a
**List of activated apps:** n/a
**Nextcloud configuration:** n/a
**Are you using external storage, if yes which one:** local
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 76
**Operating system:** OSX Catalina

#### Web server error log

n/a

#### Nextcloud log (data/nextcloud.log)

No relevant logs.

#### Browser log
<details>
<summary>Browser log</summary>

```
TypeError: response._response.jqXHR.responseJSON is undefined
```
</details>

**Comment by szaimen** [comment] 2021-06-02 12:08
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 12:08 UTC
Labels: 0. Needs triage, bug
