### ISSUE TITLE
[Bug]: NC 30.0.1 multimedia viewer changes corrent folder to the top level after viewing more than 1 file

### ISSUE THREAD

**Issue by 2yzal** [nextcloud/server#49010] opened 2024-10-30 12:13 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Example file tree: /images/jpgs/*.jpg, i.e. I have top-level folder named **images**, 2nd-level subfolder named **jpgs**, and some images in it.

When I enter **/images/jpgs**, click on image, and then close it by pressing **Esc**/clicking on "**X**" - all goes ok.
When I enter **/images/jpgs**, click on image and then go to another image in this folder by pressing Left/Right button or clicking on left/right arrows - URL in browser address bar changes from https://cloud.example.com/apps/files/files/896811?dir=/images/jpgs&openfile=true to https://cloud.example.com/apps/files/?openfile=true,
 and when I close image - my current folder changes to top-level directory.

30.0.0 did not have this issue.

### Steps to reproduce

1. Make folder and subfolder in it, place some images there
2. Open the image and then move to next by <-/-> (notice URL change)
3. Then press Esc, and you'll be in top-level. 

### Expected behavior

Folder should not change.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/nextcloud\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "30.0.1.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "default_phone_region": "RU",
        "theme": "",
        "maintenance_window_start": 1
    }
}

### List of activated Apps

Enabled:
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - event_update_notification: 2.5.0
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_accesscontrol: 1.20.1
  - files_downloadlimit: 3.0.0
  - files_linkeditor: 1.1.21
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.2
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - onlyoffice: 9.4.0
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.20.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - theming: 2.5.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - activity: 3.0.0 (installed 2.11.0)
  - admin_audit: 1.20.0
  - apporder: 0.15.0 (installed 0.15.0)
  - audioplayer: 3.4.1 (installed 3.4.1)
  - checksum: 1.2.4 (installed 1.2.4)
  - collectives: 2.14.4 (installed 2.14.4)
  - deck: 1.14.1 (installed 1.14.1)
  - drawio: 3.0.3 (installed 3.0.3)
  - encryption: 2.18.0
  - files_external: 1.22.0
  - files_mindmap: 0.0.30 (installed 0.0.30)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - files_trackdownloads: 1.11.0 (installed 1.11.0)
  - firstrunwizard: 3.0.0 (installed 2.7.0)
  - forms: 4.2.4 (installed 4.2.4)
  - fulltextsearch: 30.0.0 (installed 30.0.0)
  - imageconverter: 2.0.4 (installed 2.0.4)
  - maps: 1.4.0 (installed 1.4.0)
  - music: 2.0.1 (installed 2.0.1)
  - notes: 4.11.0 (installed 4.11.0)
  - passwords: 2024.9.10 (installed 2024.9.10)
  - polls: 7.2.4 (installed 7.2.4)
  - recommendations: 3.0.0 (installed 0.6.0)
  - related_resources: 1.5.0 (installed 1.0.4)
  - richdocuments: 8.5.0 (installed 8.5.0)
  - richdocumentscode: 24.4.702 (installed 24.4.702)
  - scanner: 0.2.3 (installed 0.2.3)
  - sharingpath: 0.4.4 (installed 0.4.4)
  - side_menu: 3.13.1 (installed 3.13.1)
  - spreed: 20.0.0 (installed 20.0.0)
  - text: 4.1.0 (installed 2.0.0)
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
  - video_converter: 1.0.6 (installed 1.0.6)
  - workflow_media_converter: 1.11.7 (installed 1.11.7)

### Nextcloud Signing status

No errors have been found.

**Comment by szaimen** [comment] 2024-10-30 12:25
I can reproduce on c.nc.c

**Comment by joshtrichards** [comment] 2024-10-30 12:35
Same as #48913?

**Comment by 2yzal** [comment] 2024-10-30 15:05
> Same as [#48913](https://github.com/nextcloud/server/issues/48913)?

Seems to. And as far as I remember that this issue was present in 29 and disappeared in 30.0.0, but reappeared in 30.0.1

**Comment by joshtrichards** [comment] 2024-10-30 15:42
Duplicate of #48913

**Closed by joshtrichards** 2024-10-30 15:42 UTC
Labels: bug, 0. Needs triage, 30-feedback
