### ISSUE TITLE
Users in one group can see people in other groups

### ISSUE THREAD

**Issue by ixmann99** [nextcloud/server#5606] opened 2017-07-04 17:42 UTC
### Steps to reproduce
1. Activate "Restrict users to only share with users in their groups".
2. Create a user user1 in group1.
3. Create a user user2 in group2.
4. User "user1" in group1 can now click contacts and see "user2"! No further action is possible, but it is bad enough.

### Expected behaviour
Should not show users from other groups. Often, you want group-isolation and this effectivly removes the option.

### Actual behaviour
Shows all users, from all groups...

Also confirmed by multiple users in the forum. No errors in log.

### Server configuration
cPanel / Centos 7

**Operating system**:

**Web server:**

**Database:**
MariDB 

**PHP version:**
5.4, 7.0, 7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.0.

**Updated from an older Nextcloud/ownCloud or fresh install:**
No.

**Where did you install Nextcloud from:**
cPanel.

**Comment by rotanid** [comment] 2017-07-14 09:12
really bad thing, but this is a duplicate of #5107 (and #5333 is also a duplicate)

**Closed** 2017-07-18 22:30 UTC
