### ISSUE TITLE
Rule based on file hash

### ISSUE THREAD

**Issue by patschi** [nextcloud/server#5330] opened 2017-06-10 17:32 UTC
Currently in the workflowengine there is support for different kind of checks like FileSize, mimeType and more. What's about a check which is based on the file hash? (crc, md5, sha1, sha2) So it would be possible to create rules depending on files, independently of their name, mimeType, location, etc.

**Comment by blizzz** [comment] 2017-06-12 11:36
@nickvergessen

**Comment by nickvergessen** [comment] 2017-06-12 13:13
I wonder if this makes sense at all? The admin would need to know the md5, so I wonder for which use-cases this makes sense?

Technical: the problem is, for uploading a file we don't know the sum until the final file is written, iirc.

**Comment by patschi** [comment] 2017-06-12 14:14
Probably some use-cases would be to prevent sharing any specific documents (e.g. PDF) to the outside. Instead forbidding all PDF files using mimeType it would be possible to just tag specific files.

To make it easier for admins, on the frontend-side there could be a filepicker to pick the files which the rules should be applied to. In the background we just use a filehash. (For marketing it may sound better to use "file-based rules"-term instead of "filehash")

From the technical perspective: When a file gets uploaded, PHP loads the file into the defined temporary location until it's finished. So before Nextcloud actually moves the uploaded file into the Nextcloud data folder we could calculate the hash before. But honestly I'm not yet that fimiliar with the core code.

**Comment by szaimen** [comment] 2021-05-21 12:18
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Closed by szaimen** 2021-05-21 12:18 UTC
Labels: 1. to develop, enhancement, feature: workflows
