### ISSUE TITLE
RFE: an option to install nextcloud via php composer

### ISSUE THREAD

**Issue by muayyad-alsadi** [nextcloud/server#7829] opened 2018-01-12 17:29 UTC
nextcloud already use [composer.json](https://github.com/nextcloud/server/blob/master/composer.json)
so why not use it to distribute nextcloud (just an option beside docker and distros rpm/deb, need not be the option)

# why this is important?

- because users would be able to consume nextcloud directly from upstream without relying on lagging distros packgers
- it would use php's native package manager that is already used.
- allow users to upgrade easily
- more developer friendly
- more OPs options ex. php internal server, apache, nginx, php-fpm, uWSGI, ...etc.
- better for automation
- more 12 factor

# examples
## wordpress

[roots/bedrock](https://github.com/roots/bedrock) have produced a 12 factor wordpress that can be installed up and running with one command

```composer create-project roots/bedrock your-project-folder-name```

## Yii Advanced App Template

[Yii's advanced App](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md) installed using the following command

```
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application
```

# What need to be done ?

- your vendor is configured to be [lib/composer](https://github.com/nextcloud/server/tree/master/lib/composer), I believe it should be empty and git-ignored [like this](https://github.com/roots/bedrock/tree/master/vendor)
- [3rd-party](https://github.com/nextcloud/3rdparty) should not be git sub-mobule, they should be fetched using composer, composer features like version-locked files () and one can easily setup a local mirror for composer using [satis](https://github.com/composer/satis)

**Comment by anassahmed** [comment] 2018-01-13 19:49
The `3rd-party` directory part would also be beneficial for RPM packages as they remove all these libraries because they're packaged elsewhere and not bundled with the official package. 😉

**Comment by MorrisJobke** [comment] 2018-01-30 14:03
Thanks for this request.

We thought a lot about distribution channels in the past and settled on: do only one thing and this properly. So we focused on the way to distribute the release of Nextcloud via archives and built the updater around this concept. Also we have a bit longer build script that does for example the signing process, etc to have a verified package or to fetch in other shipped apps from other repos.

All of this makes it harder to ship it via composer. Also the docker and RPMs are fully community driven. If somebody steps up to provide Nextcloud via composer: feel free to do so, but in my opinion distributing a end user software via a tool that was designed to manage libraries and dependencies feels a bit odd.

I hope this gives some insight. I will close this ticket for now as we have it not on our roadmap to provide this, but as written: if somebody wants to take care of it we are happy to assist.

Thanks

**Closed by MorrisJobke** 2018-01-30 14:03 UTC

**Comment by EvilBMP** [comment] 2018-06-21 13:48
> All of this makes it harder to ship it via composer. Also the docker and RPMs are fully community driven. If somebody steps up to provide Nextcloud via composer: feel free to do so, but in my opinion distributing a end user software via a tool that was designed to manage libraries and dependencies feels a bit odd.

@MorrisJobke 
I think, nextcloud is not only distributed as end user software. If agencies use nextcloud together with other client web software they want to distribute it via shell and put the(ir) stuff under version control.

In my opinion, distributing software only via ZIP files, feels a bit "aged".

**Comment by MorrisJobke** [comment] 2018-06-21 16:01
> In my opinion, distributing software only via ZIP files, feels a bit "aged".

The thing with "providing ways to distribute software" is, that it basically eats resources on our side. We are good in developing software - so we try to spend as much time with this. We want to have a software that just works and solves the problems we want to solve. There are a huge amount of ways to distribute software - just to name a few RPM, DEB, snap, docker, composer, flatpak, appimage, brew, nix packages, ansible cookbook, chef recipes ... I guess you get the idea. We want to provide the basic release and we do this as a zip archive. There is also nothing bad about a zip archive. In this way distributors can pick up this zip and bundle it in a way they want.

**Comment by MorrisJobke** [comment] 2018-11-01 20:59
> but there are so many bad practices that your team to need to give up (ex. like having a copy of dependencies in same git repo)

We do this actually on purpose. And we are also well aware of the 12 factor principles. Also composer.lock files are known. But we also want to accomplish other goals beside that - like total independence from repository failures when packagist or npm is down. It's not that we are uneducated or people that ignore useful techniques. We actually thought a lot about all of this. There are long discussions about this here in the bug tracker if we should drop our 3rdparty repo completely and only depend on composer.lock.

Unfortunately there is not this single way of accomplishing all our requirements and thus we have chosen a way in between. Also this repo is not the only source for building a release. There are other repos fetched in that we actually don't want to have in here as submodules and thus are hard to integrate in the "composer way" of deploying software.

Thus we came to the conclusion to provide exactly one official way of getting our software: releases in the form of an archive on our download servers. Those can be used by many many tools out there to then deploy it in the way the administrator want it - be it vanilla, docker, snap, appliance as VM, chef, puppet, salt, ...


We try to make it better with every release but changing this way completely is out of scope because there are better ways to spend our time: actually fixing bugs and working on the product.

I hope you can understand this.

**Comment by muayyad-alsadi** [comment] 2018-11-04 15:58
>  like total independence from repository failures when packagist or npm is down.

your are not the first one to need this and for sure there are many solutions 

in python they have wheel directory (which serves as a repo)

```
$ pip wheel --wheel-dir=/tmp/wheelhouse SomePackage
$ pip install --no-index --find-links=/tmp/wheelhouse SomePackage
```

`--no-index` tells pip to work offline and `--find-links` tells it to use directory as repo

in node I was told about npm cache and yarn
in php composer they have [satis](https://github.com/composer/satis)

of course there are other methods

> Unfortunately there is not this single way of accomplishing all our requirements and thus we have chosen a way in between.

would you do those hacks in a git submodule or a different git repo? and keep your default git repo "clean" from deployment hacks

quote from [12 factor build release run](https://12factor.net/build-release-run)

> The twelve-factor app uses **strict separation** between the build, release, and run stages.

![code-build-release](https://12factor.net/images/release.png)

currently your git repo holds the build result not the pure code
now you need to work a method to build that code into an re-distributable offline build
my guess [satis](https://github.com/composer/satis) and phar can solve this

**Comment by redtux** [comment] 2022-03-27 14:33
Hi, I have noticed that @szaimen added the 'Nice to have' label on 18 Jun 2021, so I'd like to ask if support for composer finally is on the roadmap now - and if so, when to expect this feature.

An idea might be to just create a new repository called `nextcloud-composer` or sth. In this case nothing needs to be changed for the current repo. 🙂

**Comment by tiropictor** [comment] 2022-11-16 16:17
Will just add my 5 cents. I was recently researching private clouds, found nextcloud, was amazed that it's written on php, and double amazed that it doesn't offer possibility to be installed via composer (especially when composer powers ARE actually used inside nextcloud). Really weird, such automagic just thrown away.. This feature would be greatly welcome by community, I suppose.

`composer require nextcloud/server`

would be real deal!
