### ISSUE TITLE
Nonsensical requirement: "Console has to be executed with the user that owns the file config/config.php"

### ISSUE THREAD

**Issue by regnarg** [nextcloud/server#27510] opened 2021-06-15 13:35 UTC
I am running NextCloud in read-only configuration mode (config_is_read_only set in config.php). Configuration is managed by configuration management (Ansible) and I never ever want NextCloud to overwrite the config. Thus the config file is naturally owned by root and only readable by the NextCloud user. That is all fine and well and NC runs without issues, except for two things: console management commands and cron. When running cron.php under the nextcloud user, I get the error `Console has to be executed with the user that owns the file config/config.php`. Which makes no sense. Cron has no reason to write to the config file and I do not want to give it the permissions. This way, there is a clear security boundary. Configuration is managed by root and NextCloud does only runtime stuff. There is no reason for this artificial restriction. When I remove the condition, everything works just fine.

**Comment by regnarg** [comment] 2021-06-15 13:36
Relevant piece of code in cron.php:

```
           $user = posix_getuid();                                                                    
                $configUser = fileowner(OC::$configDir . 'config.php');
                if ($user !== $configUser) {           
                        echo "Console has to be executed with the user that owns the file config/config.php" . PHP_EOL;       
                        echo "Current user id: " . $user . PHP_EOL;
                        echo "Owner id of config.php: " . $configUser . PHP_EOL;
                        exit(1);                                 
                }          
```

Commenting out the exit solves everything.

**Comment by regnarg** [comment] 2021-06-15 13:39
This is a completely standard Unix practice that you do not want a service to write to its own configuration files. It the same as when you do not allow the nginx user to write to nginx config files...

**Comment by regnarg** [comment] 2021-06-15 14:46
I worked around it using an LD_PRELOAD library:

```
#define _GNU_SOURCE
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <dlfcn.h>
#include <pwd.h>
#include <string.h>



int __xstat(int ver, const char *pathname, struct stat *statbuf) {
    int (*old_stat)(int __ver, const char *__filename, struct stat *__stat_buf);
    old_stat = dlsym(RTLD_NEXT, "__xstat");
    int r = old_stat(ver,pathname, statbuf);
    if (r != 0) return r;
    //fprintf(stderr, "STAT '%s'\n", pathname);
    if (strcmp(pathname, "/usr/local/share/nextcloud/config/config.php") == 0) {
        struct passwd pwd, *res;
        char buf[1024];
        getpwnam_r("nextcloud", &pwd, buf, sizeof(buf), &res);
        if (res) {
            statbuf->st_uid = res->pw_uid;
        }
    }
    return r;
}
```

But it seems quite ugly.

**Comment by kesselb** [comment] 2021-06-15 21:56
Closing as duplicate of https://github.com/nextcloud/server/issues/13277

**Closed by kesselb** 2021-06-15 21:56 UTC
