### ISSUE TITLE
Force NC to only use the classic username/password authentication without Tokens

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/server#21924] opened 2020-07-20 17:19 UTC
I’m looking for a way to configure (force) the server / clients to only use the classic username/password authentication that was used in the past before the token-based mechanism has been invented.

Details can be taken [from here](https://help.nextcloud.com/t/devices-clients-authorization-disrupted-after-disaster-recovery-to-fresh-installed-server/87660), but in short the issue is:

All Devices (Android and Desktop Clients) must re-authorize (logon), after disaster recovering or migrating NC server to a new sever HW/OS, by restoring NC data, config.php and database to a new machine

That way the new NC server works like a clone - with one exception: Device Tokens are not preserved.

This is a serious disruption, that impacts all users. Users will complain and elderly users may even need handhold support to bring their clients back working.

If such a configuration isn’t possible today, I hereby suggest this as a new feature. 
Even better - if at all possible - the software could store tokens in a way so that they can be preserved after restoring to a new machine.

### Steps to reproduce
1. Setup a new Nextcloud Server (I use the VMs provided by Daniel Hansson)
2. Migrate data from original Nextcloud Server to new Server (restoring NC data, config.php and database to a new machine)
3. Switch domain to the new machine

### Expected behaviour
Should work as a clone and Devices (Android, Desktop Sync sync clients) proceed working seamlessly

### Actual behaviour
Work as a clone except of Devices (Android, Desktop Sync sync clients) not proceed working seamlessly. As soon the domain is switched over to the cloned server the clients sign off and ask for re-authorization (logon)

### Server configuration
**Operating system:**
Original Server: Ubuntu 18
Clone Server: Ubuntu 20

**Web server:**
Apache on original as well as cloned machine

**Database:**
Postgres on original as well as cloned machine

**PHP version:**
PHP7.2 on original machine
PHP7.4 on cloned machine

**Nextcloud version:** (see Nextcloud admin page)
18.0.3 on original machine
19.0.1 on cloned machine

**Where did you install Nextcloud from:**
https://www.hanssonit.se/nextcloud-vm/

**Comment by kesselb** [comment] 2020-07-20 18:48
> I’m looking for a way to configure (force) the server / clients to only use the classic username/password authentication that was used in the past before the token-based mechanism has been invented.

I don't think we need such a flag.

> All Devices (Android and Desktop Clients) must re-authorize (logon), after disaster recovering or migrating NC server to a new sever HW/OS, by restoring NC data, config.php and database to a new machine

Have you tried the disaster recovery scenario? As per help.nextcloud you restored the backup to a different vm version?

> with one exception: Device Tokens are not preserved.

You wrote the tokens are restored at help.nextcloud but do not work? So they are preserved but non functional? 

Please:

1. Always use the provided template to report a bug or suggest a feature.
2. It's okay to reference a post at help.nextcloud but include all necessary details to reproduce a bug. 

What you are actually do is a bug report as enhancement request. It might be easier to create a bug report instead. From my point there is no need for such a feature and you are suggesting it as workaround for something broken.

**Comment by steve-s-71** [comment] 2020-07-20 19:13
Thank you @kesselb 

>You wrote the tokens are restored at help.nextcloud but do not work? So they are preserved but non functional?
Yes, that is correct. In the “Settings” menu under “Security” I can see the Devices & sessions have been recovered (name and date is equal to how it is on the original server) but it seems the underlying tokens are not functional. 
Fact is all Android and Windows Desktop clients insisted to get re-authorized (logon again).  

>Have you tried the disaster recovery scenario? As per help.nextcloud you restored the backup to a different vm version?
Yes, I restored to the latest (thus different) VM version. This represents a classic migration/update scenario, but it may also represent a disaster recovery scenario. 

>What you are actually do is a bug report as enhancement request
Sorry – before your response I was not clear if something is broken, or if this is a security feature. Just for the case of the latter I did not want to appear impolite and so decided to post this as new feature / workaround request.

Shall I post it again as a bug?

**Comment by kesselb** [comment] 2020-07-20 19:22
> I post it again as a bug?

No. Add the template for bugs to your first post and we are good. But please try to diasaster recovery secnarion with the same vm before.

**Comment by steve-s-71** [comment] 2020-07-20 20:19
Hi @kesselb I tried it with the same vm. Basically, delete the Nextcloud DB and recover it from the database dump. In this case the problem does not appear. 

So it seems it is not the database content itself that triggers the clients to ask for re-authorization. Is the validity of the token  combined with something that is unique to the (virtual) machine (an certificate, machine MAC address, UUID, etc.)? 

OK, Ill add the template for bugs to my first post. Shall I enter the many details about the source or the target server?

**Comment by eibex** [comment] 2020-07-21 00:45
I moved Nextcloud between different VPS providers and different Ubuntu versions and I never experienced any disruption on my Windows and phone clients. Can you replicate this consistently?

**Comment by steve-s-71** [comment] 2020-07-21 15:11
Hi @eibex, 

Yes, I can replicate this consistently and each time with multiple Android and Windows Desktop Clients. Once I switch over the domain to the cloned server – within 1 second – the desktop sync clients log of and show “connect with your account” thus force users to re-authorize. And the Android clients ask for the same as soon I try to use them.

**Comment by szaimen** [comment] 2021-06-07 19:06
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 19:06 UTC
Labels: 0. Needs triage, bug
