### ISSUE TITLE
send invitee response email with ACCEPTED/DECLINED in the subject

### ISSUE THREAD

**Issue by zsalab** [nextcloud/server#22532] opened 2020-09-01 07:47 UTC
**Is your feature request related to a problem? Please describe.**

Our users reported the previous calendar solution was sending the event updates with info ACCEPTED/DECLINED in the email subject/notification text which sounds really great feature. Would be nice if nextcloud do the same 

**Describe the solution you'd like**

If anybody accepts/declineth the event (or any other reason I think) the organizer/others receive an email/notification about it that should clearly mention the status of the response

**Describe alternatives you've considered**

Would be nice to be able to integrate completely between calendar clients to avoid the email notifications in general, so only Apple Calendar (for example) would notify the person even if an invitee is using G/MS/etc calendar

**Additional context**

currently, the only info is: 'your calendar event has been updated' that should be extended with the response of the participant responsible for the change generated the notification

**Comment by colans** [comment] 2022-03-10 04:04
This looks like a duplicate of https://github.com/nextcloud/server/issues/19144 .  Can someone else confirm?

**Comment by miaulalala** [comment] 2022-07-18 10:01
So we're currently working on accepting email REPLY/REQESTs for Calendar Events.

Is this sufficient for what you would like to see?

I can see why a more verbose subject line would be helpful, but that is merely a text change in the HTML generation of the email. As far as I understand what you'd like to see is a visual like Thunderbird provides for Calaendar Invitations?

**Closed** 2022-08-23 07:59 UTC
Labels: enhancement, 1. to develop, feature: dav, feature: caldav
