### ISSUE TITLE
[Bug]: Hidden folders and files until zoom out

### ISSUE THREAD

**Issue by michel-thomas** [nextcloud/server#46470] opened 2024-07-12 12:41 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When navigating to folder with lots of folders/files, some are missing according to zoom in page.

Example: zoom=100%, I only view 22 folders, so 1 file and 2 folders are missing
![image](https://github.com/user-attachments/assets/37f264e7-3301-40ed-85a7-f94780a7b607)

Then I zoom out to 90%, and 2 more folders appear.

Finally I zoom out again to 80% and last remaining file appears
![image](https://github.com/user-attachments/assets/a15f9f6a-edb7-4e1a-9196-09babaa54063)

This does not occur on another instance, same Nextcloud version…

### Steps to reproduce

1. Go to folder with more than 22 folders/files
2. Only first 22 elements are visible
3. Zoom out to 90% and then to 80%, missing folders and files appears

### Expected behavior

All files and folders are visible when scrolling down, whatever zoom level is.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mydomain.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.3.4",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.net\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "fr",
        "default_locale": "fr_FR",
        "logtimezone": "Europe\/Paris",
        "log_rotate_size": "5242880",
        "loglevel": 2,
        "minimum.supported.desktop.version": "3.5.2",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "trashbin_retention_obligation": "auto, 31",
        "versions_retention_obligation": "auto, 92",
        "activity_expire_days": 365,
        "default_phone_region": "FR",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "maintenance": false,
        "integrity.check.disabled": false,
        "theme": "",
        "app_install_overwrite": [
            "deck",
            "news",
            "files_rightclick"
        ],
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - announcementcenter: 6.8.1
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.10
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.1
  - drawio: 3.0.2
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_readmemd: 3.0.0
  - files_reminders: 1.2.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - groupfolders: 17.0.1
  - impersonate: 1.16.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.2
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - onlyoffice: 9.3.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - polls: 7.1.3
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - quota_warning: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.4
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - encryption: 2.17.0
  - files_external: 1.21.0 (installed 1.13.1)
  - news: 24.0.0 (installed 24.0.0)
  - nextcloud_announcements: 1.18.0 (installed 1.11.0)
  - support: 1.12.0 (installed 1.5.0)
  - survey_client: 1.17.0 (installed 1.10.0)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev (installed 6.4.0)
  - updatenotification: 1.19.1 (installed 1.12.0)
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"Z9r9C5ZfH1t3qJsH0PrN","level":3,"time":"2024-07-12T10:29:19+02:00","remoteAddr":"2a01:cb18:b8f:6000:3f:5ae:19d6:6f56","user":"apml","app":"no app in context","method":"PUT","url":"/remote.php/dav/files/apml/Partenaires%20-%20Ressources/Auvergne%20Estives%20-%20Pastom/PastoM2/Bilan/APML_CD19_PastoM2_2024.ods","message":"\"Partenaires - Ressources/Auvergne Estives - Pastom/PastoM2/Bilan/APML_CD19_PastoM2_2024.ods\" is locked, existing lock on file: 2 shared locks","userAgent":"Mozilla/5.0 (Linux) mirall/3.9.0git (Nextcloud, org.kde.Platform-5.4.0-91-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"29.0.3.4","exception":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Message":"\"Partenaires - Ressources/Auvergne Estives - Pastom/PastoM2/Bilan/APML_CD19_PastoM2_2024.ods\" is locked, existing lock on file: 2 shared locks","Code":0,"Trace":[{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":1137,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":492,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/cloud.domain.net/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Server.php","line":379,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/remote.php","line":172,"args":["/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/srv/cloud.domain.net/apps/dav/lib/Connector/Sabre/File.php","Line":206,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"Partenaires - Ressources/Auvergne Estives - Pastom/PastoM2/Bilan/APML_CD19_PastoM2_2024.ods\" is locked, existing lock on file: 2 shared locks","Code":0,"Trace":[{"file":"/srv/cloud.domain.net/apps/dav/lib/Connector/Sabre/Node.php","line":413,"function":"changeLock","class":"OC\\Files\\View","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Connector/Sabre/File.php","line":193,"function":"changeLock","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":1137,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":492,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/cloud.domain.net/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Server.php","line":379,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/remote.php","line":172,"args":["/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/srv/cloud.domain.net/lib/private/Files/View.php","Line":2004,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files/7bf169d219cd954bb011aad7471f8734\"(\"files/Partenaires - Ressources/Auvergne Estives - Pastom/PastoM2/Bilan/APML_CD19_PastoM2_2024.ods\") is locked, existing lock on file: 2 shared locks","Code":0,"Trace":[{"file":"/srv/cloud.domain.net/lib/private/Files/Storage/Wrapper/Wrapper.php","line":638,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->"},{"file":"/srv/cloud.domain.net/lib/private/Files/Storage/Wrapper/Wrapper.php","line":638,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/srv/cloud.domain.net/lib/private/Files/View.php","line":1995,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Connector/Sabre/Node.php","line":413,"function":"changeLock","class":"OC\\Files\\View","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Connector/Sabre/File.php","line":193,"function":"changeLock","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":1137,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":492,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/cloud.domain.net/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Server.php","line":379,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/remote.php","line":172,"args":["/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/srv/cloud.domain.net/lib/private/Files/Storage/Common.php","Line":840,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files/7bf169d219cd954bb011aad7471f8734\" is locked, existing lock on file: 2 shared locks","Code":0,"Trace":[{"file":"/srv/cloud.domain.net/lib/private/Files/Storage/Common.php","line":838,"function":"changeLock","class":"OC\\Lock\\MemcacheLockingProvider","type":"->"},{"file":"/srv/cloud.domain.net/lib/private/Files/Storage/Wrapper/Wrapper.php","line":638,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->"},{"file":"/srv/cloud.domain.net/lib/private/Files/Storage/Wrapper/Wrapper.php","line":638,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/srv/cloud.domain.net/lib/private/Files/View.php","line":1995,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Connector/Sabre/Node.php","line":413,"function":"changeLock","class":"OC\\Files\\View","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Connector/Sabre/File.php","line":193,"function":"changeLock","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":1137,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":492,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/cloud.domain.net/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/lib/Server.php","line":379,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/srv/cloud.domain.net/remote.php","line":172,"args":["/srv/cloud.domain.net/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/srv/cloud.domain.net/lib/private/Lock/MemcacheLockingProvider.php","Line":145}}},"message":"\"Partenaires - Ressources/Auvergne Estives - Pastom/PastoM2/Bilan/APML_CD19_PastoM2_2024.ods\" is locked, existing lock on file: 2 shared locks","exception":{},"CustomMessage":"\"Partenaires - Ressources/Auvergne Estives - Pastom/PastoM2/Bilan/APML_CD19_PastoM2_2024.ods\" is locked, existing lock on file: 2 shared locks"}}
{"reqId":"q7HPTpHWBVEA7I8l4vJW","level":2,"time":"2024-07-12T10:36:05+02:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Used memory grew by more than 10 MB when executing job OCA\\Activity\\BackgroundJob\\EmailNotification (id: 14, arguments: null): 40.6 MB (before: 31 MB)","userAgent":"--","version":"29.0.3.4","data":{"app":"cron"}}
{"reqId":"BLcrkv3BM0lOtxvMoU8y","level":2,"time":"2024-07-12T13:24:11+02:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Used memory grew by more than 10 MB when executing job OCA\\DAV\\BackgroundJob\\RefreshWebcalJob (id: 27611, arguments: {\"principaluri\":\"principals\\/users\\/decapsuleur\",\"uri\":\"wwwjeancloudreseautelaorg-4\"}): 44.2 MB (before: 34.4 MB)","userAgent":"--","version":"29.0.3.4","data":{"app":"cron"}}
{"reqId":"zxBgtXczfsQVNVfi8Qiv","level":2,"time":"2024-07-12T13:36:31+02:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Used memory grew by more than 10 MB when executing job OCA\\DAV\\BackgroundJob\\RefreshWebcalJob (id: 27609, arguments: {\"principaluri\":\"principals\\/users\\/decapsuleur\",\"uri\":\"wwwjeancloudreseautelaorg\"}): 57.8 MB (before: 42.9 MB)","userAgent":"--","version":"29.0.3.4","data":{"app":"cron"}}
{"reqId":"SpaIfT2oYg4woVr0yQqq","level":2,"time":"2024-07-12T13:51:38+02:00","remoteAddr":"2001:41d0:fe7a:d900:7894:6621:639b:b497","user":"lydra","app":"impersonate","method":"POST","url":"/apps/impersonate/user","message":"User lydra trying to impersonate user liess87","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","version":"29.0.3.4","data":{"app":"impersonate"}}
{"reqId":"SpaIfT2oYg4woVr0yQqq","level":2,"time":"2024-07-12T13:51:38+02:00","remoteAddr":"2001:41d0:fe7a:d900:7894:6621:639b:b497","user":"lydra","app":"impersonate","method":"POST","url":"/apps/impersonate/user","message":"Changing to user liess87","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","version":"29.0.3.4","data":{"app":"impersonate"}}
```

### Additional info

For better readability, I remove from logs "Authentication failed." from `Horde/Imap/Client`.

Not relevant logs when the problem is reproduced, errors in logs are from other components and not at the moment I scroll down.

I also have another instance Nextcloud 29.0.3 on another server, same config (Debian, nginx, php) except MariaDB instead of PostgreSQL. This instance does not have this problem.

I tried to reload : nginx, php-fpm and redis. It does not solve the problem.

**Comment by chuck650** [comment] 2024-07-15 03:51
I just posted about this over in the community topics.  The post is still pending, but should show up soon.  I have the same issue.

After much fiddling around with the browser, I tracked it down to an inline snippet of CSS in the style attribute of the div with attribute data-cy-files-list. there is also a class on the element, but it’s the inline style attribute that seems to be causing the problem. I fiddled with it using the browser developer tools and found if I disabled the ‘overflow: unset’ style, everything worked normally and I could scroll down the page and all the files would start to display as the scroll comes into view. Without disabling the style, I scroll past tons of blank space before I reach the bottom and it the summary row appears saying there are over 1000 files in the folder, but only about 28 of them show up by default. Strangely, if I change the zoom on the viewport from 100% down to 80, 60, or 40 percent, more files show up as the zoom decreases, but never more than what just fills the screen. Same behavior in tile or list mode. I tested this on MSEdge, Firefox, and Chrome on Linux and MacOS and it’s the same behavior on all of them. Disabling the inline style ‘overflow: unset’ fixes the functionality and all the files can be scrolled into view.

Here’s how that looks in the developer tools.

![Screenshot from 2024-07-14 20-09-16](https://github.com/user-attachments/assets/90e6c2a4-877a-4f12-87dc-2b03918176f6)

I tried to implement a style override using the browser developer tools and setting overflow: auto !important in the .files-list class style the element uses, but it has no effect.  I could not find a fix or workaround, so I am using a Webdav mount for the time being.

**Comment by michel-thomas** [comment] 2024-07-15 08:16
> I just posted about this over in the community topics. The post is still pending, but should show up soon. I have the same issue.

Thanks for your feed back, can you ref your post? I want to follow your thread also. Thks

**Comment by chuck650** [comment] 2024-07-15 13:10
[NC29 files app not showing all files/folder in browser](https://help.nextcloud.com/t/nc29-files-app-not-showing-all-files-folder-in-browser/198117?u=nelsonch650)

Was just told to open an issue here on Gthub, but since you had already done that, I just added a comment here.  I first ran into this issue about three days ago when I upgraded to NC29.  I have so far only browsed through the code on my server installation.  I may spend some time tonight looking through the source code here on Github and see if I can figure out where this inline style is coming from.  It seems strange to have an element with both CSS in a class and also an inline style element that seems to me to break the functionality by unsetting and overriding the overflow: auto that is set in the CSS class `.files-list`.

**Comment by connor-lucas** [comment] 2024-07-15 17:07
Wanted to add my voice - we are self-hosting through docker, Version 28.0.3 and experiencing the same issue. Thank you for creating the issue michel-thomas.

**Comment by connor-lucas** [comment] 2024-07-15 17:48
Hey @chuck650 and @michel-thomas,

This isn't a permanent solution but I found using the following CSS cleared up the issue for now.

`.files-list[data-cy-files-list] {
    overflow: auto !important;
}
`

**Comment by joshtrichards** [comment] 2024-07-16 01:59
> This does not occur on another instance, same Nextcloud version…

That is odd. I'm having a hard time reproducing this.

Any differences in installed apps? At least a couple apps you have installed stand out to me due to their interaction with the front-end.

- I see you have `files_rightclick` is installed and force enabled (it should not be installed in >=NC28)
- Though the one that really stands to me is `files_readme` - e.g.
  - See https://github.com/mamatt/files_readmemd/issues/159

**Comment by chuck650** [comment] 2024-07-16 02:00
@michel-thomas 

Yep, that works for sure.  I pulled the git repository and spun up a dev server with the src code.  I made that some change to the `apps/files/src/components/FilesListVirtual.vue` source file then regenerated the webpack using `npn run build` and retested.  It works.  We'll have to wait for a permanent fix from the devs to get that out.  There's no way I know of to get that onto a production server built from an archive or package.

**Comment by chuck650** [comment] 2024-07-16 02:04
@joshtrichards 

Genius!  I just disabled the files_readmemd app, and indeed I can view the full list now.

Thanks

**Comment by michel-thomas** [comment] 2024-07-16 07:17
@joshtrichards @chuck650 I confirm disabling files_readmemd app solves the problem. Thanks a lot!

**Comment by joshtrichards** [comment] 2024-07-16 12:51
Glad the mystery is a bit closer to being solved! I'll close this issue out here since it seems it's being looked into over there with that app.

**Closed by joshtrichards** 2024-07-16 12:51 UTC
Labels: bug, needs info, 0. Needs triage, feature: files, 29-feedback

**Comment by AndyScherzinger** [comment] 2024-08-20 20:57
looping in @juliushaertl since this point towards the richworkspaces / readme.md rendering

**Comment by joshtrichards** [comment] 2024-08-21 14:32
@AndyScherzinger This is the third-party `files_readmemd` app not our integrated richworkspaces / `readme.md` support.
