### ISSUE TITLE
Search on public share pages

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4020] opened 2017-03-23 23:07 UTC
Dont know whether this is caused by technical restrictions 😁 

![new plus](https://cloud.githubusercontent.com/assets/19711361/24273957/adb33456-1025-11e7-8047-2172ade50462.png)

**Comment by js94x** [comment] 2017-09-22 08:34
Any new information/plans about this issue?

**Comment by MorrisJobke** [comment] 2018-04-18 22:44
Duplicate of #1794

**Closed by MorrisJobke** 2018-04-18 22:44 UTC
Labels: enhancement, feature: files, feature: search, feature: sharing
