### ISSUE TITLE
Move files to specific folder

### ISSUE THREAD

**Issue by Xermon** [nextcloud/server#898] opened 2016-08-17 09:47 UTC
It would be great if users could move files (and folders) to a folder anywhere in the installation through the web interface. The function could be added to the following menu and could open a small window which allows picking the destination.
![bildschirmfoto 2016-08-17 um 11 45 18](https://cloud.githubusercontent.com/assets/8172056/17732003/2c6a4aee-6470-11e6-8ff4-5fc3eb3e4c86.png)

**Comment by maclag** [comment] 2016-08-18 14:00
Alternative method:
Have a clipboard in which you can drag&drop as many files as you want, and then back from the clipboard to target directory. This should make batch operations easier.

**Comment by jancborchardt** [comment] 2016-08-29 13:06
cc @icewind1991 since you said you want to work on that.

There should be an entry »Move« added to the menu (use `.icon-confirm` as icon) as @Xermon mentioned. (@maclag we’ll start step-by-step first. A full-blown clipboard will either be to complex or interfere with the desktop clipboard.)

When clicked, the file picker should open to »Choose target folder …« and the button should say »Move file« (of course »Move folder« if it’s a folder).

Anything else needed @icewind1991?

**Comment by Xermon** [comment] 2016-10-08 08:57
@jancborchardt Sound's fine!

**Comment by jancborchardt** [comment] 2016-10-23 13:23
This was implemented with https://github.com/nextcloud/server/pull/1754 and will be part of the upcoming Nextcloud 11 release! :)

Also cc the folks from the original issue like @Bugsbane @eotryx @nona00 @e-alfred @leizh @wmisi @nekohayo @BloodyIron @maclag @Vraana – your requests have been heard. :tada:

**Closed by jancborchardt** 2016-10-23 13:23 UTC
Labels: 1. to develop, design, enhancement, feature: files, medium

**Comment by kiv57** [comment] 2016-11-12 15:13
Useful feature, happy to see that it's assigned in NC11.

It would replace the "Move" app, which is still considered as experimental, and that I left behind after migrating to NC10...

**Comment by jancborchardt** [comment] 2016-11-14 10:06
Yes, it’s done and will be released with Nextcloud 11 soon. :) The popularity of the »Files move« app by @eotryx was a good indicator and motivation for getting this done in the software directly for everyone to benefit. :)

@eotryx if you are interested in getting more involved with core Nextcloud development, you are very welcome! :tada:

**Comment by BloodyIron** [comment] 2016-11-15 01:37
So, when I posted in this, it was for ownCloud. Does that mean that this code isn't going into ownCloud any more then? :/

**Comment by jancborchardt** [comment] 2016-11-17 23:46
@BloodyIron not sure, depends on if they implement it too. Nextcloud is a community-driven fork of ownCloud with lots of other improvements, so we of course recommend you to upgrade. :) And that is as easy as doing a version update.

(We’re also working on making updates painless, something which was often criticized with ownCloud. :)

**Comment by e-alfred** [comment] 2016-11-18 09:08
I really like the fact that NC goes forward not just with big changes, but also the small ones (though basic file manager features are really important anyway). NC 11 seems like the final game changer, is there any due date for it?

**Comment by jancborchardt** [comment] 2016-11-18 10:43
@e-alfred thank you for the kind words! And yeah, all those things are really important to us.
Regarding due date: Feature freeze is this weekend and release in a few weeks. :)

**Comment by evka1410** [comment] 2016-11-25 14:17
Great! And if there is an option to disable drag&drop for moving files then, it would be even better. Sometimes happens that somebody moves a file accidentally to some subfolder... And there is nothing in Activities for this :(

**Comment by jancborchardt** [comment] 2016-11-25 15:07
@evka1410 hm, moves should probably show in activities cc @nickvergessen. And ideally there should be undo for moving as well, as soon as we have file deletion undo too cc @ChristophWurst ref #1610

**Comment by nickvergessen** [comment] 2016-11-25 15:22
> moves should probably show in activities 

Moves show in activity from 11 onwards.

**Comment by juergen963** [comment] 2017-01-15 21:48
@jancborchardt : Please Re-Open. Only works for 1 file, not for serveral selected files.

Why: 
Using "auto upload" e.g. from a mobile phone, all files are uploaded into one upload folder. 
If you want to move those files to their final destination, at present, you can only do it one by one.

**Comment by nickvergessen** [comment] 2017-01-16 10:36
@juergen963 please create a new issue.

**Comment by MQGIT** [comment] 2017-05-31 22:59
I still don't see the move button on NC12?? Help!

**Comment by nickvergessen** [comment] 2017-06-01 06:30
Its in the ... menu on the file row

**Comment by MQGIT** [comment] 2017-06-01 06:32
it only moves one file not all that are selected

**Comment by kiv57** [comment] 2017-06-01 07:03
Yes, it's a regression compared to the previous app "Files Move", which 
also allowed to write the path directly : it was far quicker than 
browsing through large folder lists.

**Comment by jancborchardt** [comment] 2017-06-01 18:27
@MQGIT again, as already said to @juergen963 above: Please open a separate issue for moving with multiselect. :) Then we can look into it for Nextcloud 13.
