### ISSUE TITLE
external_storage doesn't save domain

### ISSUE THREAD

**Issue by markuswochnik** [nextcloud/server#13692] opened 2019-01-20 00:39 UTC
I changed today the domain to which my server connects and now when i add external storage i can't connect to my fileserver. When i connect with smbclient directly from my nextcloud server is everything ok, that means that the server has connection.

Userlogin against my AD server is working also without problems.

I took a look in the database and i think i found the error, the external_storage app doesn't store my "DOMAIN" entry when ich choose "Save credentials in database" in the menu.

`MariaDB [nextcloud]> SELECT * FROM oc_storages WHERE id LIKE '%smb%';
+----------------------------------------+------------+-----------+--------------+
| id                                     | numeric_id | available | last_checked |
+----------------------------------------+------------+-----------+--------------+
| smb::USER@IP-Address//SHARE// |        101 |         0 |   1547944032 |
+----------------------------------------+------------+-----------+--------------+
1 row in set (0.00 sec)
`

I updatede today the whole system:

> Nextcloud Version: 15.0.2
> PHP 7.3.1-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 13 2019 10:19:33) ( NTS )
> Ubuntu 18.04.1 4.15.0-43-generic
> smbclient 2:4.7.6+dfsg~ubuntu-0ubuntu2.6 

Are there any known problems? How can i provied more debug informations?

**Comment by markuswochnik** [comment] 2019-01-31 19:40
am i the only one with this problem?

Is there maybe a problem that my domain ist calles "INTERN" and this is some blocked term?

**Comment by skjnldsv** [comment] 2020-11-08 10:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-11-08 10:45 UTC
Labels: 0. Needs triage
