### ISSUE TITLE
Files: Add a MD5-checking tool to verify the integrity of downloaded files

### ISSUE THREAD

**Issue by PatAuge** [nextcloud/server#1942] opened 2016-10-27 23:44 UTC
To make sure that downloaded files are secure:
- Calculate and display MD5 checksum of multiple files at one time.
- Use MD5 checksum to fleetly verify whether files have been changed.
- Load, save, add, remove and update MD5 checksum conveniently.

**Comment by matunixe** [comment] 2016-10-28 06:46
That would be a very usefull feature! 👍

**Comment by LukasReschke** [comment] 2016-10-28 08:08
Seems like a duplicate of https://github.com/nextcloud/server/issues/1381

**Closed by LukasReschke** 2016-10-28 08:08 UTC
