### ISSUE TITLE
Files not visible in Webbrowser after Login

### ISSUE THREAD

**Issue by wilddeuces** [nextcloud/server#13121] opened 2018-12-17 12:45 UTC
### Steps to reproduce
1. Upgrade from 14 to 15

### Expected behaviour
Files should be visible

### Actual behaviour
Blank Site
![screenshot from 2018-12-17 13-38-20](https://user-images.githubusercontent.com/21983090/50087943-eca57500-0201-11e9-8f2f-bb34c00b6f60.png)

Access through WebDAV actually works and shows all files.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
15

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**
Official

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - audioplayer: 2.5.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.0
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - firstrunwizard: 2.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - registration: 0.4.5
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 0
        },
        "overwrite.cli.url": "https:\/\/example.com",
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "debug": true,
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "beta",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration

**Browser:**
Firefox

**Operating system:**
Ubuntu 18.04

**Comment by giraudeo** [comment] 2018-12-17 22:20
Hello,

How have you done the upgrade?
Via WEB? via CLI?
did you check if all files have correct permissions?
have you clear your browser cache just in case?

If you could attach the last log entries after you refresh the page to see if there is any error.

Regards,

Olivier

**Comment by wilddeuces** [comment] 2018-12-18 00:56
Hello,

I have updated once with CLI via Updater.phar that gave me the blank site once.
Then I have applied a backup of my server and updated with downloading the last branch from git + CLI that also gave me the blank site.

The data files still have the same permission since they are at a other location.
Nextcloud folder also has right permission on owner and group.

Im just curious about why the WebDAV is just working fine. I can download and upload new files without a problem.

Cache was empty too.

Cheers

**Comment by CaptainSifff** [comment] 2018-12-20 17:44
I'm affected, too. This was the upgrade from NC 14 to NC 15 on SuSE 15.0 using the distribution provided rpms...

**Comment by timm2k** [comment] 2018-12-21 07:21
Please run DevTools of your browser (by pressing F12) and have a look at output of Console. This could be related to outdated .css or .js files. Strange console output should indicate this.

Try to run ```occ maintenance:theme:update``` or ```occ maintenance:repair``` to fix view.

**Comment by wilddeuces** [comment] 2018-12-21 10:00
There are errors regarding the .js files where a variable is undefined and a function call got blocked by CSP. Here is the screenshot:

![screenshot from 2018-12-21 10-57-32](https://user-images.githubusercontent.com/21983090/50336865-8d03de00-050f-11e9-9b57-e5aa3e2f61a2.png)

Your statements with  "occ maintenance:theme:update or occ maintenance:repair" did not fix the problem. Same errors.

**Comment by wilddeuces** [comment] 2018-12-21 10:10
There are errors regarding the .js files where a variable is undefined and a function call got blocked by CSP. Here is the screenshot:

![screenshot from 2018-12-21 10-57-32](https://user-images.githubusercontent.com/21983090/50337309-fcc69880-0510-11e9-932f-d4cdb3fb828c.png)

Your statements with "occ maintenance:theme:update or occ maintenance:repair" did not fix the problem. Same errors.

**Comment by wilddeuces** [comment] 2018-12-21 10:11
There are errors regarding the .js files where a variable is undefined and a function call got blocked by CSP. Here is the screenshot:

![screenshot from 2018-12-21 10-57-32](https://user-images.githubusercontent.com/21983090/50337362-28e21980-0511-11e9-895a-86b5b649dbb2.png)

Your statements with "occ maintenance:theme:update or occ maintenance:repair" did not fix the problem. Same errors.

**Comment by wilddeuces** [comment] 2018-12-21 10:36
"occ maintenance:update:htaccess" returns same errors.

"occ integrity:check-core" returns no statements, so seems to be fine.

**Comment by CaptainSifff** [comment] 2018-12-21 13:08
Same here, this is the output that I get from the web console:
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
JQMIGRATE: Migrate is installed, version 1.4.0 jquery-migrate.min.js:2:542
Logging system initialised at Fri Dec 21 2018 14:06:48 GMT+0100 (CET) common.js:206:17
window.controllers/Controllers is deprecated. Do not use it for UA detection. ace.js:1362
[Show/hide message details.] Error: call to Function() blocked by CSP handlebars.min.js:28:26865
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: call to eval() or related function blocked by CSP. handlebars.min.js:28
[Show/hide message details.] TypeError: this.fileList is null[Learn More] app.js:156:5
New search handler registered search.js:66:4
[Show/hide message details.] TypeError: this.fileList is null[Learn More] app.js:156:5

**Comment by CaptainSifff** [comment] 2018-12-21 14:05
Sorry, for the noise...
My nextcloud is working again. First there was an update pushed by opensuse (from the changelog it looked like they only fixed the php requirements) and after that I had to restart a couple of services. The most likely culprits would have been php-fpm and apache2.

**Comment by skjnldsv** [comment] 2019-06-07 15:49
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-07 15:49 UTC
Labels: 0. Needs triage, bug, feature: files
