### ISSUE TITLE
[Bug]: The supplied iCalendar datetime value is incorrect: master

### ISSUE THREAD

**Issue by r2evans** [nextcloud/server#44830] opened 2024-04-15 12:10 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A few (but not all) calendar entries in my private calendar cannot be deleted. They were valid/complete when imported, I can edit them but cannot delete them.

### Steps to reproduce

Some can be deleted, I don't know how to trigger the problem. In troubleshooting this, I would appreciate advice on how better to look at it, perhaps looking for specific things in the database.

### Expected behavior

It allows me to delete it.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{                                       
    "system": {                                  
        "htaccess.RewriteBase": "\/",
        "redis": {            
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },                                         
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "apps_paths": [
            {                 
            {                 
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.mydomain.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritehost": "oc.mydomain.com",
        "overwritewebroot": "\/cloud",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/oc.mydomain.com\/cloud",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "lost_password_link": "disabled",
        "session_timeout": 129600,
        "session_keepalive": false,
        "remember_login_cookie_lifetime": 604800,
        "simpleSignUpLink.shown": false,
        "default_phone_region": "US",
        "allow_local_remote_servers": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "twofactor_admin",
            "impersonate"
        ],
        "check_for_working_wellknown_setup": false,
        "maintenance_window_start": 6
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.7
  - circles: 28.0.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - spreed: 18.0.7
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - dashboard: 7.8.0 (installed 7.7.0)
  - encryption: 2.16.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.2.1)
  - nextcloud_announcements: 1.17.0 (installed 1.5.0)
  - recommendations: 2.0.0 (installed 0.4.0)
  - sharebymail: 1.18.0 (installed 1.5.0)
  - support: 1.11.1 (installed 1.8.0)
  - survey_client: 1.16.0 (installed 1.3.0)
  - suspicious_login: 6.0.0
  - updatenotification: 1.18.0 (installed 1.6.0)
  - user_status: 1.8.1 (installed 1.6.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"eNEFhLCJZ62KbOduri6g","level":3,"time":"2024-04-15T12:00:00+00:00","remoteAddr":"11.11.11.11","user":"me","app":"webdav","method":"DELETE","url":"/cloud/remote.php/dav/calendars/me/default/A79271AD-0F92-4F34-A082-BD726F7C27C5.ics","message":"The supplied iCalendar datetime value is incorrect: master","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0","version":"28.0.4.1","exception":{"Exception":"Sabre\\VObject\\InvalidDataException","Message":"The supplied iCalendar datetime value is incorrect: master","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/vobject/lib/DateTimeParser.php","line":205,"function":"parseDateTime","class":"Sabre\\VObject\\DateTimeParser","type":"::","args":["master",["DateTimeZone"]]},{"file":"/var/www/html/3rdparty/sabre/vobject/lib/ITip/Broker.php","line":737,"function":"parse","class":"Sabre\\VObject\\DateTimeParser","type":"::","args":["master",["DateTimeZone"]]},{"file":"/var/www/html/3rdparty/sabre/vobject/lib/ITip/Broker.php","line":251,"function":"parseEventForAttendee","class":"Sabre\\VObject\\ITip\\Broker","type":"->","args":[["Sabre\\VObject\\Component\\VCalendar",null,"VCALENDAR"],["3blcrvcdnp3bnntclphojjb3o3_R20231214T163000@google.com","mailto:mary.clouse@posit.co",["Sabre\\VObject\\Parameter",null,"CN",false],"SERVER",null,"And 7 more entries, set log level to debug to see all entries"],["3blcrvcdnp3bnntclphojjb3o3_R20231214T163000@google.com","mailto:mary.clouse@posit.co",["Sabre\\VObject\\Parameter",null,"CN",false],"SERVER",null,"And 7 more entries, set log level to debug to see all entries"],["Sabre\\VObject\\Property\\ICalendar\\CalAddress",null,"ATTENDEE",null,[["Sabre\\VObject\\Parameter",null,"PARTSTAT",false],["Sabre\\VObject\\Parameter",null,"CN",false]],""]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php","line":393,"function":"parseEvent","class":"Sabre\\VObject\\ITip\\Broker","type":"->","args":[null,["mailto:me@mydomain.com","/cloud/remote.php/dav/principals/users/me/"],["Sabre\\VObject\\Component\\VCalendar",null,"VCALENDAR"]]},{"file":"/var/www/html/apps/dav/lib/CalDAV/Schedule/Plugin.php","line":180,"function":"beforeUnbind","class":"Sabre\\CalDAV\\Schedule\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeUnbind","class":"OCA\\DAV\\CalDAV\\Schedule\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":278,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeUnbind",["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:DELETE",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":373,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":172,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/sabre/vobject/lib/DateTimeParser.php","Line":40,"message":"The supplied iCalendar datetime value is incorrect: master","exception":{},"CustomMessage":"The supplied iCalendar datetime value is incorrect: master"}}
```

**Comment by xaviercm63** [comment] 2024-05-28 14:16
Same problem here when "CalDavSynchronizer" try to delete some calendar entry.

* Nextcloud 29.0.1
* Mysql  8.0.36
* Apache 2.4.52
* PHP 8.1.2

```json
{
  "reqId": "tODjyVQw6O2eGtD0Tkl0",
  "level": 3,
  "time": "2024-05-28T13:16:11+00:00",
  "remoteAddr": "1.2.3.4",
  "user": "Bob",
  "app": "webdav",
  "method": "DELETE",
  "url": "/remote.php/dav/calendars/Bob/personal/sabredav-b5bf81f5-6fa5-41e2-8fc3-9717350b746b.ics",
  "message": "The supplied iCalendar datetime value is incorrect: master",
  "userAgent": "CalDavSynchronizer/4.4",
  "version": "29.0.1.1",
  "exception": {
    "Exception": "Sabre\\VObject\\InvalidDataException",
    "Message": "The supplied iCalendar datetime value is incorrect: master",
    "Code": 0,
    "Trace": [
      {
        "file": "/nextcloud/3rdparty/sabre/vobject/lib/DateTimeParser.php",
        "line": 205,
        "function": "parseDateTime",
        "class": "Sabre\\VObject\\DateTimeParser",
        "type": "::"
      },
      {
        "file": "/nextcloud/3rdparty/sabre/vobject/lib/ITip/Broker.php",
        "line": 737,
        "function": "parse",
        "class": "Sabre\\VObject\\DateTimeParser",
        "type": "::"
      },
      {
        "file": "/nextcloud/3rdparty/sabre/vobject/lib/ITip/Broker.php",
        "line": 251,
        "function": "parseEventForAttendee",
        "class": "Sabre\\VObject\\ITip\\Broker",
        "type": "->"
      },
      {
        "file": "/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 393,
        "function": "parseEvent",
        "class": "Sabre\\VObject\\ITip\\Broker",
        "type": "->"
      },
      {
        "file": "/nextcloud/apps/dav/lib/CalDAV/Schedule/Plugin.php",
        "line": 187,
        "function": "beforeUnbind",
        "class": "Sabre\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeUnbind",
        "class": "OCA\\DAV\\CalDAV\\Schedule\\Plugin",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 278,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpDelete",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/nextcloud/apps/dav/lib/Server.php",
        "line": 374,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/nextcloud/remote.php",
        "line": 172,
        "args": [
          "/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/nextcloud/3rdparty/sabre/vobject/lib/DateTimeParser.php",
    "Line": 40,
    "message": "The supplied iCalendar datetime value is incorrect: master",
    "exception": {},
    "CustomMessage": "The supplied iCalendar datetime value is incorrect: master"
  }
}
```

**Comment by joshtrichards** [comment] 2024-07-03 19:56
Duplicate of #44940

**Closed by joshtrichards** 2024-07-03 19:56 UTC
Labels: bug, 0. Needs triage, feature: caldav, 28-feedback
