### ISSUE TITLE
wrong color scheme on maintenance-mode info/login-page

### ISSUE THREAD

**Issue by Django-BOfH** [nextcloud/server#9069] opened 2018-04-04 08:59 UTC
### Steps to reproduce
1. Fresh installation of nextcloud 13.0.01
2. On admin-page change color-scheme from default "blue" to your favorite color i.e. "orange"
3. On admin-page change the default claim "footer of the entry-page"
4. Restart websever/php-fpm  and everything in the web-gui works as expected and fine. The color has changed and the right individual claim footer is displayed on the login page!

BUT now:

5. Set up maintenance-mode:
`sudo -u apache /opt/rh/rh-php71/root/usr/bin/php /var/www/html/nextcloud/occ maintenance:mode --on`

6. Goto login-page. Instead of the individual color "orange" the default color "blue" is displayed. The claim (footer) is the default on, not the individual one, witch was modified in "step 3 above". :( 

### Expected behaviour
The individual color-scheme, of my own installation should be used on maintenance.mode-errorpage, too! And the claim "footer" should be the same as on my original login-page.

### Actual behaviour
Wrong color (default blue) and the original claim is used on maintenance-mode-page. So my users a a little bit confused and asked me: Are you compromised or hacked? The page I've seen last day was a different one and has other colors and claim-information on the footer! :( 

### Server configuration

CentOS 7.4
Apache 2.4
Maria-/MySQL-DB 15.1 Distrib 5.5.56
PHP 7.1 (SCLO)
Nextcloud 13.0.0.1 (new fresh installation)
`# sudo -u apache  /opt/rh/rh-php71/root/usr/bin/php
/var/www/html/nextcloud/occ status`
` - installed: true
  - version: 13.0.1.1
  - versionstring: 13.0.1
  - edition: `

**Signing status:**
<details>

`# sudo -u apache  /opt/rh/rh-php71/root/usr/bin/php
/var/www/html/nextcloud/occ integrity:check-core`
`No errors have been found`
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
`# sudo -u apache  /opt/rh/rh-php71/root/usr/bin/php
/var/www/html/nextcloud/occ app:list`
`Enabled:
  - activity: 2.6.1
  - admin_notifications: 1.0.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap`

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
`# sudo -u apache  /opt/rh/rh-php71/root/usr/bin/php
/var/www/html/nextcloud/occ config:list`
`{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "default_language": "de",
        "log_rotate_size": 104857600,
        "loglevel": 2,
        "updatechecker": true,
        "updater.server.url":
"https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.6.1",
            "notify_email_calendar": "0",
            "notify_email_calendar_event": "0",
            "notify_email_calendar_todo": "0",
            "notify_email_comments": "0",
            "notify_email_favorite": "0",
            "notify_email_file_changed": "0",
            "notify_email_file_created": "1",
            "notify_email_file_deleted": "0",
            "notify_email_file_restored": "0",
            "notify_email_public_links": "0",
            "notify_email_remote_share": "0",
            "notify_email_shared": "0",
            "notify_email_systemtags": "0",
            "notify_setting_batchtime": "0",
            "notify_setting_self": "1",
            "notify_setting_selfemail": "0",
            "notify_stream_calendar": "1",
            "notify_stream_calendar_event": "1",
            "notify_stream_calendar_todo": "1",
            "notify_stream_comments": "1",
            "notify_stream_favorite": "1",
            "notify_stream_file_changed": "1",
            "notify_stream_file_created": "1",
            "notify_stream_file_deleted": "1",
            "notify_stream_file_favorite": "0",
            "notify_stream_file_restored": "1",
            "notify_stream_public_links": "1",
            "notify_stream_remote_share": "1",
            "notify_stream_shared": "1",
            "notify_stream_systemtags": "1",
            "types": "filesystem"
        },
        "admin_notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "660"
        },
        "caniupdate": {
            "enabled": "[\"admin\"]",
            "installed_version": "0.1.2",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "core": {
            "installedat": "1520869117.1309",
            "lastcron": "1522830415",
            "lastupdateResult": "[]",
            "lastupdatedat": "1522818794",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "{\"Application to
check\":{\"EXCEPTION\":{\"class\":\"Exception\",\"message\":\"App not
found\"}}}",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "c99c900457ee0a0eebdb1bf08f9649",
            "shareapi_only_share_with_group_members": "yes",
            "umgmt_send_email": "true",
            "umgmt_show_backend": "false",
            "umgmt_show_email": "true",
            "umgmt_show_storage_location": "false",
            "updater.secret.created": "1521711564",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.4.6",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "flowupload": {
            "enabled": "yes",
            "installed_version": "0.0.7",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "[\"admin\"]",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "relativedates": "1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "minLength": "12",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "alert_email": "yes",
            "enabled": "yes",
            "info_email": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem",
            "warning_email": "yes"
        },
        "serverinfo": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "survey_client": {
            "apps": "no",
            "database": "no",
            "enabled": "[\"admin\"]",
            "encryption": "no",
            "files_sharing": "no",
            "installed_version": "1.1.0",
            "php": "no",
            "server": "no",
            "stats": "no",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "theming": {
            "backgroundMime": "backgroundColor",
            "cachebuster": "25",
            "color": "#FFAE00",
            "enabled": "yes",
            "installed_version": "1.4.1",
            "logoMime": "image\/svg+xml",
            "name": "Cloud der geilsten Trupper ever",
            "slogan": "der sichere Datenaustauschraum f\u00fcr Ihre
vertraulichen Daten!",
            "types": "logging",
            "url": "https:\/\/cloud.example.com"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "updatenotification": {
            "core": "13.0.1.1",
            "enabled": "[\"admin\",\"cloudadmin\"]",
            "installed_version": "1.3.0",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        }
    }
}`
</details>

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no external user-backend

### Client configuration
**Browser:** Firefox/Chrome/Konqueror

**Operating system:** Linux/Virdos

**Comment by MorrisJobke** [comment] 2018-04-04 12:00
This is because no app is loaded for this time and thus also the app data and the theming app is not available. Nevertheless there is the idea of a plain maintenance mode page: #5789

Thus closing as duplicate of #5789

**Closed by MorrisJobke** 2018-04-04 12:00 UTC
