### ISSUE TITLE
[Bug]: Files App: Shift + Select to select ranges not working with Firefox

### ISSUE THREAD

**Issue by thgoebel** [nextcloud/server#42202] opened 2023-12-13 11:04 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

According to the [announcement blog post](https://nextcloud.com/blog/nextcloud-hub-7-advanced-search-and-global-out-of-office-features/) for Nextcloud 28, the files app now has "Better selection handling (shift + select to select range)".

However, this is not working for me.

### Steps to reproduce

1. Open the Files app
2. Click on a file's empty check box to select the first file (NOT holding Shift)
3. Click on another file's empty check box to _**while holding Shift**_

### Expected behavior

The file range should be selected.

### Actual behaviour

When clicking on the second file when holding Shift, nothing happens. The second file is not even individually selected.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "filelocking.enabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "cloud.example.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "forcessl": true,
        "default_phone_region": "DE",
        "theme": "",
        "app_install_overwrite": [
            "whiteboard",
            "twofactor_nextcloud_notification",
            "suspicious_login",
            "qownnotesapi",
            "quota_warning",
            "twofactor_admin",
            "groupfolders"
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\BMP",
            "OC\\Preview\\GIF",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\Krita",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PNG",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - cospend: 1.5.12
  - dav: 1.29.1
  - deck: 1.12.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - forms: 4.0.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.0
  - notifications: 2.16.0
  - notify_push: 0.6.5
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.0.1
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - qownnotesapi: 23.12.0
  - quota_warning: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0
  - richdocumentscode: 23.5.602
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - translate: 2.0.0
  - twofactor_admin: 4.4.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - groupfolders: 16.0.0 (installed 16.0.0)
  - integration_deepl: 1.1.1 (installed 1.1.1)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing interesting in there.
```

## Metadata

- Firefox 120.0.1
- Ubuntu 23.10

**Comment by hede5562** [comment] 2023-12-25 16:06
Not only this functionality is gone but also other ways like: https://github.com/nextcloud/server/issues/17313#issuecomment-552958640
I do not find any way to select a file rang in a folder with many files except for individually selecting every single file or all files at once.

**Comment by skjnldsv** [comment] 2023-12-27 15:27
Hmmm, this was working during 28 development, let me have a look

**Comment by skjnldsv** [comment] 2023-12-27 15:31
Ah, broken on firefox. Chrome works! Fix incoming

**Comment by hede5562** [comment] 2023-12-27 16:07
Oh, yes @skjnldsv, you're right, it seems to be specific for Firefox. So my current workaround is to use Chromium. 

Will there be a fix for Firefox? As clicking the name instead of the checkbox worked before with old Nextcloud versions. Nevertheless Mozilla should fix Firefox' behavior also. But if something didn't get fixed within 14 years I don't think they will do so in the near future. ;-)

Btw. do you really think the Mozilla bug is applicable here? The bug is for "shift+click on a label for a checkbox" while here with Nextcloud it's shift-clicking the checkbox itself what's not working in Firefox (but works in chrome as expected).

**Comment by skjnldsv** [comment] 2023-12-27 16:38
> Btw. do you really think the Mozilla bug is applicable here? The bug is for "shift+click on a label for a checkbox" while here with Nextcloud it's shift-clicking the checkbox itself what's not working in Firefox (but works in chrome as expected).

Yeah, this is precisely the issue.
We use a custom checkbox which we spend a lot of time making aria compliant (accessibility)
And that involve using a nested label and input checkbox.

Unfortunately the bug is here since 14 years in Firefox and, having spent a bit of time digging around, we're not the only one being annoyed by this.

We'll try to find a workaround for Firefox as this mus be resolved without breaking accessibility handling.

**Closed** 2024-01-02 08:55 UTC
Labels: bug, 1. to develop, regression, 28-feedback

**Comment by tincanfury** [comment] 2024-09-26 18:13
Is there a way to get range selection from a mobile or tablet  browser without a physical keyboard?

**Comment by damnshaneisthatu** [comment] 2024-10-07 17:40
Is this still working on Chrome? Because I cannot get it to work on any browsers now.

**Comment by hede5562** [comment] 2024-10-21 16:13
Same here. 

Even if it feels like a regression, it's probably a new Bug.

**Comment by skjnldsv** [comment] 2024-10-22 06:29
Please someone open a new issue and fill the template

**Comment by khlschrnk** [comment] 2024-11-02 20:06
FYI: a new issue was opened last week: https://github.com/nextcloud/server/issues/48886
