### ISSUE TITLE
Enhance moving many files UI experience

### ISSUE THREAD

**Issue by tomzo** [nextcloud/server#2960] opened 2017-01-05 19:05 UTC
Moving files and folders via UI works pretty well, except one use case:
1. Create a deep folder structure, e.g. `/a/b/c` and upload many files there.
2. Then lets say we want to move part of them to `/c/d/e`. There is no easy way to do this.

Currently moving files or folders can be done by clicking Move on **single** folder or file.
Another way is by using drag and drop, but that can be moved only up the directory tree.

I see 2 ways this could be implemented:
 * via drag and drop - when hovering over folders, a preview of current folder would show up, kind of like windows explorer
 * make the *Move* operation (in the context menu) possible on multiple files. User would select files to be moved, then context menu would concern all currently selected files.

**Comment by MorrisJobke** [comment] 2017-01-09 13:49
Duplicate of #2779

**Closed by MorrisJobke** 2017-01-09 13:49 UTC
