### ISSUE TITLE
[Bug]: user.ini integrity check error

### ISSUE THREAD

**Issue by nemihome** [nextcloud/server#35124] opened 2022-11-12 21:52 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

user.ini is checked for integrity hash. This should not be the case. User ini does allow e.g. to restrcit php execution only for some folders. This can be different for every folder. 

I had to disable integrity check via:
  ‘integrity.check.disabled’ => true

In my case user.ini is looking like this:
```
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'
output_buffering=0
[PHP]
open_basedir="/usr/share/php/:/var/www/html/URL/nextcloud:/var/nextcloud:/var/www/html/URL/.well-known"

```
The open basedir ans also other setting could be different for other web apps in other folders. Nextcloud seems to expect that only one app is running - Nextcloud - and all PHP settings are only set for Nextcloud requirements. 

### Steps to reproduce

1. change user.ini
2. check security settings and warnings

### Expected behavior

Basically the integrity check should increase the security. But in this case it does the absolute opposite. There should be no check for user.ini. In my case user.ini is looking like this:

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bookmarks: 11.0.4
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.2
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - documentserver_community: 0.1.13
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - gpxpod: 4.3.0
  - keeweb: 0.6.10
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.2.1
  - metadata: 0.17.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - ocdownloader: 1.8.1
  - onlyoffice: 7.5.8
  - password_policy: 1.14.0
  - photos: 1.6.0
  - previewgenerator: 5.1.1
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - rainloop: 7.2.6
  - recommendations: 1.3.0
  - richdocuments: 6.3.1
  - richdocumentscode: 22.5.802
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_email: 2.7.1
  - twofactor_totp: 6.4.1
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - uploaddetails: 0.1.3
  - user_ldap
```

**Comment by szaimen** [comment] 2022-11-13 15:58
Which nc version?

**Comment by solracsf** [comment] 2022-11-13 18:28
Duplicate of https://github.com/nextcloud/server/issues/19935

**Closed by solracsf** 2022-11-13 18:28 UTC
Labels: bug, needs info, 0. Needs triage
