### ISSUE TITLE
[Bug]: Multiple LDAP servers don't work properly

### ISSUE THREAD

**Issue by aknauss** [nextcloud/server#35072] opened 2022-11-10 10:06 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,
I've two active directory server.
When I upgraded to Nexcloud 25.0.1 , It seems the server take only the last of two ldap to check credentials...

Regards

### Steps to reproduce

1.Declare two different LDAP on Ldap/AD integration page.
2.Try to connect through login page with a user on each ldap.
3.

### Expected behavior

User rejected instead of checking on theses two ldap configuration.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.15.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.1
  - drawio: 1.0.3
  - encryption: 2.13.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.0
  - files_automatedtagging: 1.15.0
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.0.0
  - keeweb: 0.6.10
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - picker: 1.0.3
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - user_usage_report: 1.9.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - accessibility
  - activity: 2.13.2
  - analytics: 4.4.0
  - announcementcenter: 6.4.0
  - bruteforcesettings: 2.4.0
  - carnet: 0.24.5
  - contacts: 5.0.1
  - dashboardcharts: 0.1.3
  - data_request: 1.11.0
  - drop_account: 2.1.0
  - duplicatefinder: 0.0.15
  - end_to_end_encryption: 1.10.0
  - epubreader: 1.4.7
  - files_mindmap: 0.0.26
  - files_retention: 1.14.0
  - files_texteditor: 2.14.0
  - files_videoplayer
  - forms: 3.0.1
  - mail: 2.1.0
  - officeonline: 1.1.3
  - ojsxc: 5.0.0
  - quicknotes: 0.8.1
  - terms_of_service: 2.0.0
  - twofactor_totp: 6.4.1
  - twofactor_u2f: 6.4.0-alpha.1
  - user_external: 3.0.0
  - user_saml: 5.0.3
  - workflow_pdf_converter: 1.10.0
```

**Comment by szaimen** [comment] 2022-11-10 10:11
Duplicate of https://github.com/nextcloud/server/issues/34993

**Closed by szaimen** 2022-11-10 10:11 UTC
Labels: bug, 0. Needs triage
