### ISSUE TITLE
Add the ability to change the sort order of the groups from member-based to alphabetically

### ISSUE THREAD

**Issue by ThaDaVos** [nextcloud/server#44435] opened 2024-03-23 09:59 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Yes, currently the groups are ordered by the count of members, but this is really illogical way of sorting so please add the option to sort alphabetically by group name.

**Describe the solution you'd like**

Add the option to sort alphabetically by group name.

**Describe alternatives you've considered**

Doing it myself...

**Additional context**

This is the xth time someone asks for this, just a few below:

https://github.com/nextcloud/contacts/issues/1215
https://github.com/nextcloud/contacts/issues/1212
https://github.com/nextcloud/contacts/issues/522

**Comment by susnux** [comment] 2024-03-23 23:40
The linked issues are from the contacts app,  if you refer to that please open a ticket there. 

But I guess you mean the account management settings.
There is already a feature request,  so duplicate of https://github.com/nextcloud/server/issues/39528

> Doing it myself...

Sure, we really appreciate contributions!

**Closed by susnux** 2024-03-23 23:40 UTC
Labels: enhancement, 0. Needs triage
