### ISSUE TITLE
"Busy" in calendar public is not translated

### ISSUE THREAD

**Issue by fccl-vandoeuvre** [nextcloud/server#22107] opened 2020-08-05 07:56 UTC
Hello,

The entry "Busy" in calendar public version web is not translated in French.
No possibility by Transifex.

Thanks !

### Steps to reproduce

(in French version)
1. Create evenement and select "When shared show only busy"
2. create share link public
3. open url share link, "busy" appearance

![capture_ecran_nextcloud_calendrier_public_2020-08-05](https://user-images.githubusercontent.com/50994238/89386722-bf247c80-d701-11ea-8694-b152930537bf.png)

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.3)

### Client configuration
**Browser:** (e.g. Firefox 78.0.2)

**Operating system:** (e.g. Xubuntu 16.04)

### Server configuration

**Operating system**: (e.g. Debian 10)

**Web server:** (e.g. Nginx,...)

**Database:** (e.g. mysql)

**PHP version:** (e.g. 7.0.2)

**Nextcloud Version:** (see admin page, e.g. 18.0.2)

**Comment by kesselb** [comment] 2020-08-05 09:42
Closing as duplicate of https://github.com/nextcloud/server/issues/18782. Fixed for Nextcloud 19.

**Closed by kesselb** 2020-08-05 09:42 UTC
Labels: 0. Needs triage, bug, feature: dav
