### ISSUE TITLE
Popover doesn´t close in user management

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/server#7617] opened 2017-12-23 14:59 UTC
### Steps to reproduce
1. Open user management
2. Click on the more icon for a user

### Expected behaviour
The menu should close after clicking somewhere else / the popover should be positioned correctly

### Actual behaviour
The menu doesn´t close and the popover isn´t positioned correctly (a bit to high)

## Server configuration detail

**Operating system:** Linux

**Webserver:** Apache (CentOS)

**Database:** sqlite3 3.7.17

**PHP version:** 7.1.12

**Nextcloud version:** 13.0.0 Beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** git

<details><summary>List of activated apps</summary>

```
Enabled:
 - comments: 1.3.0
 - dav: 1.4.5
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_sharing: 1.5.0
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - issuetemplate: 0.3.0
 - lookup_server_connector: 1.1.0
 - oauth2: 1.1.0
 - provisioning_api: 1.3.0
 - sharebymail: 1.3.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - testing
 - user_ldap
```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "13.0.0.8",
    "installed": true
}
```
</details>

![user management](https://user-images.githubusercontent.com/1869584/34320388-9b959f1e-e7f9-11e7-8681-c3089c34e23e.png)

**Comment by MorrisJobke** [comment] 2018-01-02 10:49
cc @nextcloud/javascript

**Comment by splitt3r** [comment] 2018-01-02 11:28
Small correction: It does go away if you click the three dots again. That should be unified with the default popover behaviour.

**Comment by danxuliu** [comment] 2018-01-03 05:06
The fix for not closing the popover menu when clicking outside the menu is in #7668

It does not fix the wrong position of the menu, though. It seems to be caused by [the `margin-top` CSS rule for `.popovermenu` elements](https://github.com/nextcloud/server/blob/bb04e106514f51c056f030ceef2c34cff355ef4b/core/css/apps.scss#L773), but those are generic rules with potentially lots of side effects, so I have not touched them; I left that for someone else with more knowledge about them ;-) @nextcloud/designers

**Comment by MorrisJobke** [comment] 2018-01-03 13:03
Please open a separate ticket for the positioning, because this is mainly about the "not closing" bug which is fixed.

**Closed by MorrisJobke** 2018-01-03 13:03 UTC
Labels: feature: users and groups, papercut
