### ISSUE TITLE
Link in README Broken.

### ISSUE THREAD

**Issue by crydotsnake** [nextcloud/server#18970] opened 2020-01-18 11:27 UTC
Hello Dear Nextclouders! :blush: :cloud:. 
I just want to let you know that the "Set up your local development environment" link in the README is broken.

**Comment by J0WI** [comment] 2020-01-19 14:41
Duplicate of https://github.com/nextcloud/documentation/issues/1782

**Closed by J0WI** 2020-01-19 14:41 UTC
Labels: 0. Needs triage, bug
