### ISSUE TITLE
Favorites bulk actions

### ISSUE THREAD

**Issue by nferrari** [nextcloud/server#14530] opened 2019-03-05 09:10 UTC
Hi,

I'm on the last Nextcloud server version (15.0.5) and can't see a way to download all my favorites once I'm on the "favorites" page. It seems the bulk actions are not available as in a classic directory.

**Comment by szaimen** [comment] 2021-05-21 08:23
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by espuuks** [comment] 2023-02-17 13:11
+1 for this enhancement requests. Since search results when filtering by tags do not support bulk actions either, one might have an idea to use favorites as kind of a staging area to collect files and then download/copy/move by selecting all of them.

**Comment by skjnldsv** [comment] 2023-06-22 16:53
Duplicate of https://github.com/nextcloud/server/issues/7627

**Closed by skjnldsv** 2023-06-22 16:53 UTC
Labels: enhancement, 1. to develop, feature: files
