### ISSUE TITLE
allow_user_to_change_display_name 

### ISSUE THREAD

**Issue by volker-raschek** [nextcloud/server#1302] opened 2016-09-07 09:49 UTC
### Steps to reproduce
1. Set the config value allow_user_to_change_display_name=false; in config.php 
2. Try to change the email address from an user in the admin panel. You can't change the email as admin.
3. Set the config value allow_user_to_change_display_name back to true in config.php
4. You can change the email address as admin in the admin panel.

Pleas fix this bug. If allow_user_to_change_display_name is false, only the admin can change the email and other personal settings.

### Server configuration
**Operating system**:
Raspian

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
5.5

**Nextcloud version:** (see Nextcloud admin page)
10.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
From old Version 9

**Where did you install Nextcloud from:**
From zip-Archive.

**Comment by tflidd** [comment] 2016-09-07 11:07
I can't reproduce this on my system:
Debian 8/maria-db/apache2/php7(dot-deb)/NC 10.0

@volker-raschek Can you provide more details? Used apps, possible error messages in your logfiles, external authentication, ...

**Comment by volker-raschek** [comment] 2016-09-10 06:24
Yes very well.
I dont use an external authentication. 
Here is the config list from the occ socket.
```
{
    "system": {
        "instanceid": "occkwrm2fxo6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "\/mnt\/sda1\/www\/example.local\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/nextcloud.example.local",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "example.local",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "enable_avatars": true,
        "allow_user_to_change_display_name": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "trashbin_retention_obligation": "7,14",
        "versions_retention_obligation": "7,14",
        "logfile": "\/var\/log\/nextcloud.log",
        "log_type": "owncloud",
        "loglevel": 2,
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Berlin",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": false,
        "maintenance": false,
        "tempdirectory": "\/tmp"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "26"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.3.3",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.4.0.0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1468161955.1044",
            "lastcron": "1473488104",
            "lastupdateResult": "[]",
            "lastupdatedat": "1473487792",
            "oc.integritycheck.checker": "[]",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_resharing": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_expire_after_n_days": "14",
            "shareapi_only_share_with_group_members": "yes",
            "umgmt_send_email": "true",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "documents": {
            "converter": "local",
            "enabled": "yes",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "1 GB",
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.0.2",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "owncloud,dropbox,googledrive,swift"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.0.0",
            "minLength": "8",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.3",
            "ocsid": "164356",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "22",
            "color": "#575757",
            "enabled": "yes",
            "installed_version": "1.0.1",
            "name": "Nextcloud - Example Local",
            "slogan": "the encrypted cloud",
            "types": "logging",
            "url": "https:\/\/nextcloud.example.local"
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        }
    }
}
```
If you need more information dont hesitate to ask

Volker

**Comment by volker-raschek** [comment] 2016-09-10 06:29
This is the message, when i want to change the e-mail address about the admin panel with the 
allow_user_to_change_display_name = false.
http://666kb.com/i/dc9v4isvj2xbaz2j6.png
It's German and means, the email address can't be changed.

**Comment by MorrisJobke** [comment] 2016-09-13 16:06
Duplicate of https://github.com/nextcloud/server/issues/642

**Closed by MorrisJobke** 2016-09-13 16:06 UTC
Labels: needs info
