### ISSUE TITLE
Searching users is not intuitive, can't do partial searches without special characters

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/server#14153] opened 2019-02-12 08:20 UTC
### Steps to reproduce
1. Have a user with display name "Martin Rys"
2. Go to https://cloud.example.com/settings/users as an admin and try to search for "Rys"
3. 0 results

### Expected behaviour
"Martin Rys" should pop up because "Rys" is part of the string "Martin Rys"

### Actual behaviour
No results. Doing "*Rys" gets the result but that is far from intuitive.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2.10

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Originally NC 12

**Where did you install Nextcloud from:**
Manually.

### Client configuration
**Browser:** Firefox 65

**Operating system:** Arch Linux

### Logs
N/A, will provide if they're actually needed for the search issue.

**Comment by putt1ck** [comment] 2019-10-01 10:13
NB I think I'm going to remark this a bug as we can show that the results are inconsistent regarding the wildcard/partial match user searches. Scenario:

installation has a user (from LDAP) username john.smith, display name John Smith, the user is a member of several groups;
a search for "john" returns the user regardless of the group searched in;
a search for "smith"returns the user in some groups but not ones with many users (including the "everyone" category, installation has >400 users from LDAP, maybe 10 local to NC database);
a search for "*smith" returns the user from the large groups but not the small ones.

Further:

a search for "a" returns all LDAP users with first letter a - and all NC database users whose username, display name or email address contain "a".

**Comment by putt1ck** [comment] 2019-10-01 10:15
NB that's NC16.04, updated in many steps from ~10. LDAP server is samba, backend DB is postgres.

**Comment by skjnldsv** [comment] 2020-03-10 07:52
Duplicate of #11540

**Closed by skjnldsv** 2020-03-10 07:52 UTC
Labels: 1. to develop, bug, enhancement, feature: users and groups
