### ISSUE TITLE
 [NC 10.0 former OC 9.0.4] Imap backed users can't login to their caldav when using a short user id

### ISSUE THREAD

**Issue by xshadow** [nextcloud/server#1612] opened 2016-10-03 17:03 UTC
### Expected behaviour

After a migration from owncloud 9 to nextcloud 10 a login to Nextcloud via caldav software should accept your credentials.
### Actual behaviour

After a migration from owncloud 9 to nextcloud 10, some users aren't able to access their Nextcloud calendars. Those users where authenticated through imap auth. 

It turns out that a login in via caldav software with "long" (userid1@domain.com) user id is accepted, but a short user ID ( userid1 ) is rejected.  

If you adjust your caldav software settings and change the "short" user id to a "long" one, it works without problems.
### Server configuration

**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** mysql  Ver 14.14 Distrib 5.6.33,

**PHP version:** v7.0.11-1~dotdeb+8.1 ,

**nextCloud version:** 10.0 (former Owncloud Version 9.0.4)

**Updated from an older nextcloud or fresh install:** Updated from an older owncloud version

**Where did you install Nextcloud from:** gz-package from download page 

**Signing status:**  failed

Modifications in lib/imap.php are valid. Not yet merged https://github.com/owncloud/apps/pull/2093

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- user_external
    - INVALID_HASH
        - lib/imap.php

Raw output
==========
Array
(
    [user_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/imap.php] => Array
                        (
                            [expected] => d4ebccdc4a2f2a97456c666ef6f6608ed631ceaee3f605e270df88be08a1c3e2c3b6944f07a271612bc6fa79b708c0d9a2ee54b310e68255c415f46904665efa
                            [current] => 2b57473d0fb8855b1c4d9d24eb033efb8bf4f62cfaabbcfedf7319f282b79b76bca77664d0847b2bd43964b67db3c51c2dfc5291638931e4cc815fc88f4a3a57
                        )

                )

        )

)

```

apps/user_external/lib/imap.php

--> Not merged in OC:   Modifications in lib/imap.php are valid. Not yet merged https://github.com/owncloud/apps/pull/2093

``` php
<?php
/**
 * Copyright (c) 2012 Robin Appelman <icewind@owncloud.com>
 * This file is licensed under the Affero General Public License version 3 or
 * later.
 * See the COPYING-README file.
 */

/**
 * User authentication against an IMAP mail server
 *
 * @category Apps
 * @package  UserExternal
 * @author   Robin Appelman <icewind@owncloud.com>
 * @license  http://www.gnu.org/licenses/agpl AGPL
 * @link     http://github.com/owncloud/apps
 */
class OC_User_IMAP extends \OCA\user_external\Base {
    private $mailbox;
    private $domain;

    /**
     * Create new IMAP authentication provider
     *
     * @param string $mailbox PHP imap_open mailbox definition, e.g.
     *                        {127.0.0.1:143/imap/readonly}
     */
    public function __construct($mailbox, $domain = '') {
        parent::__construct($mailbox);
        $this->mailbox=$mailbox;
        $this->domain=$domain;
    }

    /**
     * Check if the password is correct without logging in the user
     *
     * @param string $uid      The username
     * @param string $password The password
     *
     * @return true/false
     */
    public function checkPassword($uid, $password) {
        if (!function_exists('imap_open')) {
            OCP\Util::writeLog('user_external', 'ERROR: PHP imap extension is not installed', OCP\Util::ERROR);
            return false;
        }

        // Check if we only want logins from ONE domain and strip the domain part from UID      
        if($this->domain != '') {
            $pieces = explode('@', $uid);
            if(count($pieces) == 1) {
                $username = $uid . "@" . $this->domain;
            }elseif((count($pieces) == 2) and ($pieces[1] == $this->domain)) {
                $username = $uid;
                $uid = $pieces[0];
            }else{
                return false;
            }
        }else{
            $username = $uid;
        }

        $mbox = @imap_open($this->mailbox, $username, $password, OP_HALFOPEN, 1);
        imap_errors();
        imap_alerts();
        if($mbox !== FALSE) {
            imap_close($mbox);
            $uid = mb_strtolower($uid);
            $this->storeUser($uid);
            return $uid;
        }else{
            return false;
        }
    }
}

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - news: 9.0.4
  - notes: 2.0.2
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - qownnotesapi: 16.09.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

``` php
<?php
$CONFIG = array (
  'forcessl' => true,
  'logdateformat' => 'Y-m-d H:i:s.u',
  'log_type' => 'syslog',
  'syslog_tag' => 'ownCloud',
  'loglevel' => 0,
  'mail_domain' => 'domain.com',
  'mail_from_address' => 'domain-owncloud',
  'mail_smtpmode' => 'php',
  'remember_login_cookie_lifetime' => '1296000',
  'session_keepalive' => true,
  'session_lifetime' => '86400',
  'trashbin_retention_obligation' => 'auto, 15',
  'trusted_proxies' => 
  array (
    0 => '192.168.123.4',
  ),
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.domain.com',
  ),
  'datadirectory' => '/var/www/cloud.domain.com/oc_data',
  'overwrite.cli.url' => 'https://cloud.domain.com',
  'overwriteprotocol' => 'https',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'user',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'user',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'default_language' => 'de',
  'mail_smtpsecure' => 'ssl',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mail.domain.com:993/imap/ssl}',
        1 => 'domain.com',
      ),
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'mail_smtphost' => 'mail.domain.com',
  'mail_smtpport' => '587',
  'theme' => '',
  'maintenance' => false,
  'appstore.experimental.enabled' => false,
  'htaccess.RewriteBase' => '/',
);


```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes , Imap
### Client configuration

Thunderbird (45.3.0) + Lightning Plugin 4.7

Caldav Sync (0.4.27)

**Comment by nickvergessen** [comment] 2016-10-04 15:21
Well that is something that needs to be fixed in the app, right? 
Nothing we can do on the DAV site, since we can not randomly manipulate the user login.

Or did I misunderstand something here?

**Comment by xshadow** [comment] 2016-10-04 15:58
I think there is a misunderstanding. 

It worked in OC9 and the rejection of the short user id's started directly after the migration to NC10, not after an app update(thunderbird +lightning / caldav app).

So the might is a difference how NC and OC treat dav logins?

**Comment by nickvergessen** [comment] 2016-10-05 06:59
We didn't make any modifications to the IMAP handling, so this should all be the same as with ownCloud.

So does the modification from https://github.com/owncloud/apps/pull/2093/files fix the issue? Or is it not related to this issue? Or are you using this and that is why it breaks?

**Comment by xshadow** [comment] 2016-10-05 15:27
The modfication does not fix the issue. We used this in owncloud and now in Nextcloud to restrict the the imap logins to a specific imap domain. But it could cause the problem.

If you enable IMAP auth for a specific mailserver such as mail.allmydomains.com. Every domain that is hosted on the mail server could access the cloud space. 

If you want to enable just one domain ( cloudusers.com ), you have to apply the mentioned fix, which didn't make it to Owncloud or Nextcloud yet.

>  https://github.com/owncloud/apps/pull/2093/files

**Comment by t2d** [comment] 2016-10-06 07:28
I believe the problem is a different one.  If you apply https://github.com/owncloud/apps/pull/2166 oc/nc put the user in the database only with the username without domain part. So the user can login through the webinterface with t2d@example.org or only t2d.
However, the caldav/carddav/desktop client connector are blind to this.
But, it used to work differently in oc9. So maybe the carddav/caldav connectors used the external_user authentication before and now only query the internal database?

**Comment by Mattyx** [comment] 2017-01-09 10:17
I have the same problem with NC 11.0.0.10.
It seems like the IMAP auth for CalDAV and CardDAV starts only if the username has the domain part.
All our IMAP authenticated users cannot access their CalDAV calendars because our IMAP server only accepts "short ids" without the domain part. There is a way to allow the use of short usernames? This behavior seems related to CalDAV and CardDAV only.

Thanks in advance

**Comment by MorrisJobke** [comment] 2017-08-31 08:22
> It turns out that a login in via caldav software with "long" (userid1@domain.com) user id is accepted, but a short user ID ( userid1 ) is rejected.

This is the indented behaviour AFAIK. The server just queries the user backends. There is only a special case for the login page as of now that also allow different attributes.

**Closed by MorrisJobke** 2017-08-31 08:22 UTC
Labels: needs info
