### ISSUE TITLE
Ability to upgrade between multiple major release

### ISSUE THREAD

**Issue by olahaye74** [nextcloud/server#19011] opened 2020-01-20 10:13 UTC
It would be extremely useful to have the ability to upgrade between multiple major release.
Without this ability, there won't be adoption in bistro repositories.

I have nee able to do so by hand installing and migrating without running (didn't start httpd) the web server.
https://forum.remirepo.net/viewtopic.php?pid=10993#p10993

Can't you keep each major release upgrade steps (code) and run them in sequence?
For example, EPEL has nextcloud v10.0.4.
I've built nextcloud V17.0.2. Package can't be upgraded while the only problem is upgrading the database structure.

Even if all package exists, there is no package manager that will install in sequence all major release between the installed one and the latest available. when you upgrade, the package manager will choose the latest version; no matter is there are available major version in between.

Having the ability to detect installed version and run in sequence all needed migrations between major releases up to current version would greatly help adoption in distro repositories.

**Comment by J0WI** [comment] 2020-01-20 19:36
Duplicate of #2270

**Closed by J0WI** 2020-01-20 19:36 UTC
Labels: 0. Needs triage, enhancement
