### ISSUE TITLE
Please improve user registration

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/server#9299] opened 2018-04-25 13:02 UTC
I wanted to give access to my Nextcloud to a group of 30 people. Only a third of them was able to register properly, because the tokens outdate too soon. Now, I can't even see whose account is activated and whose isn't. That is pretty unsatisfactory to the users and very annoying for me. 

What can I do to see, who has a login and who hasn't? 
What did I do wrong?
How can I improve this user experience?

**Comment by MorrisJobke** [comment] 2018-04-25 13:48
This is a community app which is maintained by @pellaeon - please reach out in that bug tracker: https://github.com/pellaeon/registration

Thanks

**Comment by MorrisJobke** [comment] 2018-04-25 13:48
Maybe @nextcloud/designers can jump in and have a look at the UI/UX part.

**Comment by kaffeeringe** [comment] 2018-05-09 09:18
The registration app is not a solution. I can't open registration to the public. I only want to invite 30 people. And that would work with the core if the tokens didn't outdate so fast.

**Comment by kaffeeringe** [comment] 2018-05-09 09:43
@jancborchardt: I didn't use the registration app.
@juliushaertl: As described here: https://docs.nextcloud.com/server/13/admin_manual/configuration_user/user_configuration.html#creating-a-new-user 
I checked "Send email to new user" and then left the Password field empty, when I added one user after another. They all received the e-mail - but some of them only clicked on the link hours or days later, so their token was outdated.

By the way "Token outdated" is not an error-message that anybody understands, nor does it help to solve the problem. My suggestion:

1. I should be able to set a time for the token, or disable it.
2. The error message should be something like "the link you clicked is outdated - it was only valid for x hours. Please do y to solve the problem.
3. The user management should display which account is confirmed any which isn't.
4. I should be able to resend the token or copy the link to send it on another medium. For example a messenger, if the e-mail gets lost in spam folders etc...

**Comment by jancborchardt** [comment] 2018-05-09 10:04
Absolutely agree. What's the current expiration time and what should it be expanded to?

Regarding wording: Instead of "Token outdated", we should use "Registration link expired".

**Comment by melkon** [comment] 2018-07-10 22:37
The current timeframe is 12 hours and probably best to be expand at least to a day, or better, let it be set by the admin themselves via the settings menu (like a dropdown similar to the quota settings).

**Comment by MorrisJobke** [comment] 2018-07-11 07:00
> The current timeframe is 12 hours and probably best to be expand at least to a day, or better, let it be set by the admin themselves via the settings menu (like a dropdown similar to the quota settings).

Before thinking about adding settings we should think about a good solution first. A good read about this is http://neugierig.org/software/blog/2018/07/options.html and the linked articles.

**Comment by melkon** [comment] 2018-07-11 09:16
I agree that adding the option / increasing the time until the link runs out is just a bandage, the actual question which needs to be answered is what is the workflow then the link runs out? Does it actually make sense that the link runs out? 

Right now the admin has to make sure that the email is reacted upon in less than 12 hours which basically forces admin and user to meet up and register the account together. 

Thinking about it, it actually might be sufficient to let the user itself be able resend the link when the token is expired, basically adding a button "Resend email" or similar. That would just be a shortcut to the "forgot password" workflow with different wording. Letting the user resend the email would be in line what is already possible because the user can already circumvent the expired link by design via the forgot password workflow (well, have to double check in 12 hours).

A second option would be remove the expiration of the registration link.

A third which comes to mind is to remove the expiration date but make it a two step process. After the user created the password, the admin has to activate the account manually or can at least see / share / revoke the registration link via the admin menu.

**Comment by MorrisJobke** [comment] 2018-08-31 11:28
> Letting the user resend the email would be in line what is already possible because the user can already circumvent the expired link by design via the forgot password workflow (well, have to double check in 12 hours).

see #10942 for a fix of the time (12h to 7d) and #10776 as a duplicate of this ticket here in general.

**Closed by MorrisJobke** 2018-08-31 11:28 UTC
Labels: enhancement, feature: users and groups
