### ISSUE TITLE
Notifications for file drop

### ISSUE THREAD

**Issue by Aresss** [nextcloud/server#29229] opened 2021-10-14 08:34 UTC
### Description
We are hosting our company NextcloudPi and are asking our clients to upload documents in a folder that is shared with the settings "upload only". Now it would be nice if it is possible to get a notification if the client uploaded the files that we requested and we wouldnt need to actively check the folder all the time.

### Example
For example we have a client A. We are working together with him and see that we need more information from his side provided to us in a file. Then we will create a folder in our NextcloudPi server where he can upload the files. Unfortunately there is no way to get notified if this actually happened so we have to check the folder daily or hope the client confirms with us via mail.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Send a notification every time a file gets uploaded through Filedrop shared link.

**Describe alternatives you've considered**
Checking the folders daily. Asking the client to send us an email to confirm he uploaded the files.

**Additional context**

**Comment by brendan-pike** [comment] 2022-04-05 10:50
We are needing this feature also, I believe this ticket might be a duplicate of #20565 though

**Comment by pierreozoux** [comment] 2022-05-11 10:31
closing in favor of #20565

**Closed by pierreozoux** 2022-05-11 10:31 UTC
Labels: enhancement, 0. Needs triage
