### ISSUE TITLE
Multi public upload | design issue

### ISSUE THREAD

**Issue by k1ngf15h3r** [nextcloud/server#6110] opened 2017-08-14 18:10 UTC
### Steps to reproduce
1. Go to a public upload link for upload only
2. Drag & Drop multiple files or upload mutilple files at once with the explorer
3. Second icon keeps a spinning cicle instead of mime-type icon

### Expected behaviour
When upload is done all icons have to change to its mime-type symbol.

### Actual behaviour
First mime-type icon changes correctly, second icon stays on spinning cicle.

### Server configuration

**Operating system**: Cent OS 7

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** docker hub

**Comment by MorrisJobke** [comment] 2017-08-14 20:50
Duplicate of #6060

**Closed by MorrisJobke** 2017-08-14 20:50 UTC
