### ISSUE TITLE
Database Errors on Clean installation

### ISSUE THREAD

**Issue by ThorgerJ** [nextcloud/server#20212] opened 2020-03-28 15:40 UTC
### Steps to reproduce
1. Install Raspbian lite on the Raspi b+
2. Install and setup mariadb
3. Install a clean nextcloud installation manually from nextcloud.com

### Expected behaviour
There should be no database errors

### Actual behaviour
I got the following error. After that i restored the SD to before the installation and tried it again with the same error.

The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.

    Missing index "calendarobject_calid_index" in table "oc_calendarobjects_props".
    Missing index "schedulobj_principuri_index" in table "oc_schedulingobjects".
Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.

    mounts.storage_id
    mounts.root_id
    mounts.mount_id

### Server configuration

**Operating system:** raspbian lite

**Web server:** apache

**Database:** mariadb

**PHP version:** 7.*

**Nextcloud version:** 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** nextcloud.com

**Comment by kesselb** [comment] 2020-03-28 17:31
Duplicate of https://github.com/nextcloud/server/issues/19658

**Closed by kesselb** 2020-03-28 17:31 UTC
Labels: 0. Needs triage, bug
