### ISSUE TITLE
Monitoring app shows double amount of RAM assigned

### ISSUE THREAD

**Issue by mwries** [nextcloud/server#5899] opened 2017-07-27 08:17 UTC
**Steps to reproduce**
Open Monitoring app in Admin section, and look at Memory Usage chart. Under the chart there is in grey the "Total" RAM allocated. This is twice what I assigned to the VM (4.2 GB is shown, but only 2.1 GB is assigned to the VM).

**Expected behaviour**
Show correct amount of assigned RAM

**Actual behavior**
It shows twice the amount of RAM.

**Server configuration**
Operating system: Linux nextcloud.systemsnavigator.com 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64
Web server: Apache/2.4.18 (Ubuntu) (apache2handler)
Database: pgsql PostgreSQL 9.5.7 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit
PHP version: 7.0.18-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache
Nextcloud version: 12.0.0 - 12.0.0.29
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Nextcloud VM

**Comment by enoch85** [comment] 2017-07-31 23:00
I can confirm this, the value is not correct.

**Comment by pmarini** [comment] 2017-11-03 21:03
Same issue for me. Details of my local installation on the attached txt file.
[report_nc.txt](https://github.com/nextcloud/server/files/1442470/report_nc.txt)

**Comment by jospoortvliet** [comment] 2018-10-26 12:45
https://github.com/nextcloud/serverinfo/blob/master/lib/SystemStatistics.php#L113 the code is here - I acutally think this is quite readable even if you're not a PHP expert. Tell us what is wrong or even just tell us what to fix. You can try the commands on your server, see what gives the wrong result: the VM or Nextcloud... (it is possible the vm reports it wrong, there's nothing we can do it that case).

**Comment by enoch85** [comment] 2018-10-26 14:07
It's not an issue for me anymore.

**Comment by enoch85** [comment] 2018-10-26 14:09
I'll close this since it's working in the latest version.

**Closed by enoch85** 2018-10-26 14:09 UTC
Labels: bug
