### ISSUE TITLE
Gotify Support

### ISSUE THREAD

**Issue by gthbusrr** [nextcloud/server#25530] opened 2021-02-08 08:12 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I am not able to get Notification without Google Play Service.

**Describe the solution you'd like**
Push notification via HTTP POST with self-hosted services like [Gotify](https://gotify.net/).

**Describe alternatives you've considered**
I could have installed microG, but I am so privacy conscious that I don't think it is an option for me.

**Additional context**

**Comment by kesselb** [comment] 2021-02-08 08:43
Duplicate of https://github.com/nextcloud/server/issues/18261

**Closed by kesselb** 2021-02-08 08:43 UTC
Labels: 0. Needs triage, enhancement
