### ISSUE TITLE
Allow to move several files from one folder to an other. Tree folder structure view on the left sidebar?

### ISSUE THREAD

**Issue by rkkoszewski** [nextcloud/server#4994] opened 2017-05-20 12:01 UTC
### Steps to reproduce
1. Select several files
2. Try to move them to an other folder

### Expected behaviour
There should be an option to to move all the files to an other folder (Right now you can only batch delete files). Eventually a tree view of the file structure would be really handy to have it on the right sidebar, to allow the user drag the files to an other folder, or at least have a "Move" button next to the "Delete" button that could open a dialog where the user can navigate to the target folder and move the files.

### Actual behaviour
It's not possible to move several selected files at once. You have to move each file one by one. Or create a folder, put all files in it, then move the folder to the target folder, and then again move each file one by one out of that folder.

### Server configuration

**Operating system**:
%any
**Web server:**
%any
**Database:**
%any
**PHP version:**
%any
**Nextcloud version:** (see Nextcloud admin page)
11
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2017-08-14 16:06
Duplicate of #2779

**Closed by MorrisJobke** 2017-08-14 16:06 UTC
