### ISSUE TITLE
[Bug]: Problem updating to 28.0.1

### ISSUE THREAD

**Issue by trvrcr** [nextcloud/server#42736] opened 2024-01-12 11:06 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_officeonline_wopi" collides with the constraint on table "oc_richdocuments_wopi".
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_officeonline_wopi" collides with the constraint on table "oc_richdocuments_wopi".

The update was unsuccessful. Please report this issue to the [Nextcloud community](https://github.com/nextcloud/server/issues).

### Steps to reproduce

1. start an update
2.get the error
3. you are stuck

### Expected behavior

Start update
update succesful

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands                                                                                                                                    are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",(was not removed automatically)
            "***REMOVED SENSITIVE VALUE***",(was not removed automatically)
            "***REMOVED SENSITIVE VALUE***",(was not removed automatically)
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.5.1",
        "overwritehost": ""***REMOVED SENSITIVE VALUE***",(was not removed automatically)
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "overwrite.cli.url": ""***REMOVED SENSITIVE VALUE***",(was not removed automatically)
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "default_phone_region": "BE",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Krita"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Brussels",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_x": 512,
        "preview_max_y": 512,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "joplin",
            "cookbook",
            "gpxedit",
            "groupfolders",
            "metadata",
            "files_fulltextsearch",
            "ransomware_protection",
            "files_trackdownloads",
            "bruteforcesettings",
            "health",
            "calendar",
            "scanner",
            "camerarawpreviews",
            "holiday_calendars",
            "maps",
            "news",
            "files_readmemd",
            "transfer",
            "tvshownamer",
            "workflow_ocr",
            "money",
            "pdfdraw"
        ],
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "music.lastfm_api_key": "***REMOVED SENSITIVE VALUE***",(was not removed automatically)
        "music.cover_size": "500",
        "music.podcast_auto_update_interval": "1",
        "data-fingerprint": ""***REMOVED SENSITIVE VALUE***",(was not removed automatically)
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/ex                                                                                                                                   iftool-aarch64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go                                                                                                                                   -vod-aarch64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.gis_type": 1,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.19.0
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.1
  - contactsinteraction: 1.8.0
  - cookbook: 0.10.5
  - cospend: 1.5.14
  - dav: 1.27.0
  - deck: 1.11.2
  - event_update_notification: 2.3.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.1
  - files_automatedtagging: 1.17.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_readmemd: 2.0.0
  - files_reminders: 1.0.0
  - files_sharing: 1.19.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - fileslibreofficeedit: 1.1.0
  - geoblocker: 0.5.13
  - gestion: 2.4.1
  - groupfolders: 15.3.2
  - holiday_calendars: 0.3.0
  - integration_openstreetmap: 1.0.6
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.2
  - maps: 1.2.0
  - memories: 6.2.2
  - metadata: 0.19.0
  - money: 0.24.0
  - music: 1.9.1
  - news: 24.0.0
  - notes: 4.9.2
  - notifications: 2.15.0
  - notify_push: 0.6.6
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - picker: 1.0.7
  - polls: 5.4.2
  - previewgenerator: 5.4.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - qownnotesapi: 23.12.0
  - ransomware_protection: 1.14.0
  - recognize: 5.0.3
  - related_resources: 1.2.0
  - richdocumentscode_arm64: 23.5.604
  - scanner: 0.2.3
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - systemtags: 1.17.0
  - tables: 0.6.5
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - transfer: 0.6.1
  - tvshownamer: 1.0.2
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - workflow_ocr: 1.27.5
  - workflow_pdf_converter: 1.12.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.18.0 (installed 1.11.0)
  - analytics: 4.12.0 (installed 4.12.0)
  - camerarawpreviews: 0.8.4 (installed 0.8.4)
  - collectives: 2.9.2 (installed 2.9.2)
  - dashboard: 7.8.0 (installed 7.6.0)
  - encryption: 2.16.0 (installed 2.7.0)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_fulltextsearch: 27.0.1 (installed 27.0.1)
  - firstrunwizard: 2.17.0 (installed 2.7.0)
  - fulltextsearch: 27.0.3 (installed 27.0.3)
  - gpxedit: 0.0.14 (installed 0.0.14)
  - integration_homeassistant: 0.0.3 (installed 0.0.3)
  - integration_openproject: 2.5.1 (installed 2.5.1)
  - libresign: 7.1.1 (installed 7.1.1)
  - nextcloud_announcements: 1.17.0 (installed 1.9.0)
  - pdfdraw: 0.1.2
  - recommendations: 2.0.0 (installed 0.8.0)
  - richdocuments: 8.2.4 (installed 8.2.4)
  - sharebymail: 1.18.0 (installed 1.10.0)
  - solid: 0.7.2 (installed 0.7.2)
  - support: 1.11.0 (installed 1.3.0)
  - survey_client: 1.16.0 (installed 1.6.0)
  - suspicious_login: 6.0.0 (installed 5.0.0)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.5.0)
  - weather_status: 1.8.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
(stuck in update mode)
```

**Comment by solracsf** [comment] 2024-01-12 11:27
Duplicate of https://github.com/nextcloud/server/issues/41253

**Closed by solracsf** 2024-01-12 11:27 UTC
Labels: bug, 0. Needs triage
