### ISSUE TITLE
[Bug]: RuntimeException image not found: image:apps/whiteboard.svg

### ISSUE THREAD

**Issue by jmechnich** [nextcloud/server#47985] opened 2024-09-14 20:25 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading from NC 29.0.7 to 30.0.0, a Runtime Exception is thrown regularly and continuously:
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/e042c858-0282-493b-8ee1-d48eb60c7749">

The file does not exist in the `apps` directory but is also not expected to be there. The raw log entry at the end of this issue unfortunately does not help a lot to pinpoint the cause for this error.

A file of the same name exists in `core/img/filetypes/whiteboard.svg`.

### Steps to reproduce

1. Upgrade NC to 30.0.0
2. Check logs

### Expected behavior

No errors.

### Nextcloud Server version

30.0.0

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE MANUALLY***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.0.14",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE MANUALLY***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "calendar",
            "groupfolders",
            "ojsxc",
            "richdocuments",
            "richdocumentscode",
            "gpxpod",
            "video_converter",
            "files_markdown",
            "impersonate",
            "drawio"
        ],
        "debug": false,
        "default_phone_region": "de",
        "mail_sendmailmode": "smtp",
        "maintenance_window_start": 1,
        "trashbin_retention_obligation": "auto, 30",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\TIFF"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - bookmarks: 15.0.1
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.0
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - collectives: 2.14.3
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - drawio: 3.0.2
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_markdown: 2.4.1
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - gpxpod: 6.0.0
  - groupfolders: 18.0.1
  - impersonate: 1.17.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notes: 4.10.1
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - polls: 7.2.3
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.0
  - richdocumentscode: 24.4.702
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.0
  - support: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - twofactor_webauthn: 2.0.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - dashboard: 7.10.0 (installed 7.0.0)
  - encryption: 2.18.0 (installed 2.5.0)
  - survey_client: 2.0.0 (installed 2.0.0)
  - suspicious_login: 8.0.0 (installed 4.3.0)
  - twofactor_nextcloud_notification: 4.0.0
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{
  "reqId": "WiKVMilAS20a6T3HdydW",
  "level": 3,
  "time": "2024-09-14T22:28:16+02:00",
  "remoteAddr": "2001:7c0:2900:8024::869b:244a",
  "user": "admin",
  "app": "no app in context",
  "method": "GET",
  "url": "/ocs/v2.php/apps/notifications/api/v2/notifications?format=json",
  "message": "image not found: image:apps/whiteboard.svg webroot: serverroot:/var/www/nextcloud",
  "userAgent": "Mozilla/5.0 (Linux) mirall/3.13.0 (build 22492) (Nextcloud, debian-6.1.0-23-amd64 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
  "version": "30.0.0.14",
  "exception": {
    "Exception": "RuntimeException",
    "Message": "image not found: image:apps/whiteboard.svg webroot: serverroot:/var/www/nextcloud",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/firstrunwizard/lib/Notification/Notifier.php",
        "line": 205,
        "function": "imagePath",
        "class": "OC\\URLGenerator",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/firstrunwizard/lib/Notification/Notifier.php",
        "line": 105,
        "function": "setAppHintDetails",
        "class": "OCA\\FirstRunWizard\\Notification\\Notifier",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Notification/Manager.php",
        "line": 337,
        "function": "prepare",
        "class": "OCA\\FirstRunWizard\\Notification\\Notifier",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/notifications/lib/Controller/EndpointController.php",
        "line": 103,
        "function": "prepare",
        "class": "OC\\Notification\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 208,
        "function": "listNotifications",
        "class": "OCA\\Notifications\\Controller\\EndpointController",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 114,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 161,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/ocs/v1.php",
        "line": 43,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/ocs/v2.php",
        "line": 7,
        "args": [
          "/var/www/nextcloud/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/URLGenerator.php",
    "Line": 242,
    "message": "image not found: image:apps/whiteboard.svg webroot: serverroot:/var/www/nextcloud",
    "exception": {},
    "CustomMessage": "image not found: image:apps/whiteboard.svg webroot: serverroot:/var/www/nextcloud"
  }
}
```

**Comment by jmechnich** [comment] 2024-09-14 20:42
Related forum posts:

- https://help.nextcloud.com/t/lot-of-errors-upgrading-from-29-0-7-to-30-0-0/203893
- https://help.nextcloud.com/t/rc5-of-nextcloud-30-hub-9/203637

Supposedly installing and removing the new whiteboard app removes the error, gonna try this now.

**Comment by melroy89** [comment] 2024-09-15 13:48
I can also confirm this issue. And the error is spamming line crazy (error log pollution!):

![image](https://github.com/user-attachments/assets/f6f41e77-5602-4191-b610-63879217af8f)

**Comment by sorbaugh** [comment] 2024-09-15 14:51
cc @juliushaertl

**Comment by razerrazer** [comment] 2024-09-15 21:49
I can confirmed that i have the exactly same issue.

**Comment by gruberth** [comment] 2024-09-16 05:55
Same on my 30.0.0 installation:

![grafik](https://github.com/user-attachments/assets/8f5a5acc-527d-4ac6-af83-bbba9d60b883)

**Comment by abolfazlbm** [comment] 2024-09-16 07:35
I had the same issue, so I installed the Whiteboard app and then uninstalled it, I haven't reencountered this error.

**Comment by melroy89** [comment] 2024-09-16 13:10
> I had the same issue, so I installed the Whiteboard app and then uninstalled it, I haven't reencountered this error.

This is indeed the same workaround I applied. But I believe this is not the solution.

**Comment by juliushaertl** [comment] 2024-09-16 13:40
Fix is in https://github.com/nextcloud/firstrunwizard/pull/1363

**Comment by nickvergessen** [comment] 2024-09-17 16:14
https://github.com/nextcloud/firstrunwizard/pull/1363

**Closed by nickvergessen** 2024-09-17 16:14 UTC
Labels: bug, 0. Needs triage, 30-feedback

**Comment by charlescurley** [comment] 2024-09-28 20:44
Adding and then disabling the whiteboard app is a partial solution. Doing that got rid of the runtime exception. But I still get this in my log approximately twice a minute:

`Link of notification is not an absolute URL and does not work in mobile and desktop clients [app: survey_client, subject: updated]`

Raw entry is as follows:

`{"reqId":"Qli1NoF3HmKkVFtMScwH","level":2,"time":"2024-09-28T14:43:31-06:00","remoteAddr":"192.168.10.1","user":"charles","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Link of notification is not an absolute URL and does not work in mobile and desktop clients [app: survey_client, subject: updated]","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","version":"30.0.0.14","data":[],"id":"66f86a75e3a5c"}`

**Comment by nickvergessen** [comment] 2024-09-28 21:15
https://github.com/nextcloud/survey_client/pull/317

**Comment by Walter0799** [comment] 2024-10-20 12:18
Same here since an update to V30.

**Comment by nickvergessen** [comment] 2024-10-20 12:33
Update to 30.0.1 from last week, problem solved
