### ISSUE TITLE
Email Footer: Do not reply to this automated message

### ISSUE THREAD

**Issue by christf** [nextcloud/server#29644] opened 2021-11-11 07:41 UTC
When inviting participants to appointments, eMails generated by the calendar app contain a remark to not reply to this automatically generated message.
However the reply-to headers are set up correctly such that a potential response would indeed reach the author of the calendar entry.

As such there is no need for this remark and we can let it go. 

This is nextcloud 20.0.9

**Comment by ChristophWurst** [comment] 2021-11-11 07:43
Transferred because invitations are sent by the server. For any future bug report please closely follow the bug reporting template https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C+0.+Needs+triage&template=Bug_report.md

**Comment by szaimen** [comment] 2023-01-23 12:22
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:46 UTC
Labels: bug, needs info, feature: dav, 0. Needs triage, feature: caldav
