### ISSUE TITLE
Updater App: remove all entry from table oc_share [share_with != NULL]

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/server#8955] opened 2018-03-22 20:27 UTC
### Steps to reproduce
1. remove a app (example apps/files_pdfviewer)
2. reload page - install the update from the application
3. check the file / folder share from yourself

[Youtube Screencast](https://youtu.be/nzO1RxyR7Ig)

### Expected behaviour
Before the update any App, there are 5 entries in the oc_share table.

### Actual behaviour
After the update, all entries are missing.

## Server configuration detail

**Operating system:** Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64

**Webserver:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 10.2.13

**PHP version:** 7.1.15
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, intl, ldap, mcrypt, memcached, mysqli, pcntl, pdo_mysql, pdo_pgsql, pgsql, redis, zip, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1 (also into previouse version)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install 

**Where did you install Nextcloud from:** [docker-compose (nextcloud example)](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache)

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - bookmarks: 0.11.0
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.2
 - dav: 1.4.6
 - deck: 0.3.1
 - drawio: 0.8.9
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "NEXTCLOUD_DOMAIN"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.example.com",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "loglevel": 0,
    "maintenance": false,
    "theme": "",
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Operating system:**

## Logs

<details><summary>Browser log</summary>

```
no error log 
```
</details>

<details><summary>Nextcloud log</summary>

```
no error log
```
</details>

<details><summary>Browser log</summary>

no error log
</details>

**Comment by MorrisJobke** [comment] 2018-03-23 07:09
> Before the update any App, there are 5 entries in the oc_share table.

Looks like the repair steps are running and cleaning up invalid shares. cc @nextcloud/sharing

**Comment by blizzz** [comment] 2018-10-30 10:43
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Comment by mr-bolle** [comment] 2018-12-23 19:19
Hi, i have still this issue. And i wonder why nobody else report such issue.
And now i try to reproduce this Issue, and found a way.

!! **create first a copy of your oc_share table** !!

1. create a share File | Folder with a User | Group
2. check mysql: ``SELECT * FROM `oc_share` ORDER BY `oc_share`.`share_with` DESC`` and the above share exist
3. run `sudo -u www-data php occ maintenance:repair -vvv` and repair the nextcloud instance

> - Repair invalid shares
> - Removed 22 shares where the parent did not exist

4. reload Nextcloud and the share above don't exist anymore
5. check mysql: ``SELECT * FROM `oc_share` ORDER BY `oc_share`.`share_with` DESC`` and ***only entrys share_with == NULL exist***

**Comment by skjnldsv** [comment] 2019-08-15 06:08
Hey @mr-bolle 
We were never been able to reproduce your issue, even with your given steps.
Did you fix this? Is it working now?

**Comment by mr-bolle** [comment] 2019-08-15 06:42
Hi @skjnldsv,

This issue still exist. The workaround for me is, to create a DB Backup from this table, and after every update add the 'share_with' entries manually.

I plan to build a new nextcloud instance, and there i would make it from the scratch. If nobody else have this issue - it makes maybe sense to close this issue.

**Comment by skjnldsv** [comment] 2019-08-15 06:45
Yes, I'm more thinking about a misconfiguration somehow that is breaking all your shares. Maybe the root is not properly defined or something.
Please report back after your new instance it you experience the same issue there, we'll re-open :)

**Closed by skjnldsv** 2019-08-15 06:45 UTC
Labels: 0. Needs triage, bug, feature: install and update, feature: sharing, needs info
