### ISSUE TITLE
9.1.4.1/3.1 Styling menubar - For many elements like "B" and "I", selected styles are visually marked by a pale blue background (1,2:1 to white) and remain below the contrast ratio of 3:1 that is needed to indicate the state visually.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42216] opened 2023-12-13 13:40 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-45ae33ca9f-v3-n1

9.1.4.1/3.1 Styling menubar - For many elements like "B" and "I", selected styles are visually marked by a pale blue background (1,2:1 to white) and remain below the contrast ratio of 3:1 that is needed to indicate the state visually.

![image](https://github.com/nextcloud/server/assets/42591237/b41837a0-2cb4-429d-be28-da1b807bdcb2)

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:12
duplicate of https://github.com/nextcloud/text/issues/5065

**Closed by JuliaKirschenheuter** 2023-12-14 10:12 UTC
Labels: accessibility
