### ISSUE TITLE
RFE: reverse sort order in trash to most recent first

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#25291] opened 2021-01-23 08:03 UTC
Relates to #24544 but quick and easy. Is in user world a bug.

Trash view opens with oldest deleted file first by default. However the most common use of undelete is for items a user just realised shouldn't have been deleted and therefore recent, rather than old. This means the initial opening of the trash view should sort most recent first. 

This minor change would significantly improve UX. The other items in the meta issue are still needed in any large organisation usage.

**Comment by szaimen** [comment] 2021-06-22 13:16
Duplicate of https://github.com/nextcloud/server/issues/16412#issuecomment-586967281

**Closed by szaimen** 2021-06-22 13:16 UTC
Labels: 0. Needs triage, enhancement
