### ISSUE TITLE
Compare to current version - Only one file display instead of two

### ISSUE THREAD

**Issue by kevinkuan1969** [nextcloud/server#42714] opened 2024-01-11 14:28 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Only one file is displayed

### Steps to reproduce

1.
2.
3.

### Expected behavior

Expecting the selected file and current version of file both are open side-by-side.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.analytic360.biz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloud.analytic360.biz",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "MY",
        "profile.enabled": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "allow_local_remote_servers": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "apporder",
            "libresign",
            "dicomviewer",
            "appointments",
            "files_fulltextsearch_tesseract",
            "files_bpm",
            "memories",
            "metadata",
            "login_notes",
            "pdf_downloader",
            "unsplash",
            "gestion",
            "ncdownloader",
            "extract",
            "occweb"
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitMap",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\TIF"
        ],
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "maintenance": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "updater.release.channel": "stable",
        "loglevel": 2,
        "ncd_admin_settings": {
            "disallow_aria2_settings": "0",
            "ncd_yt_binary": "",
            "ncd_aria2_binary": "\/usr\/bin\/aria2c",
            "ncd_aria2_rpc_host": "127.0.01",
            "ncd_aria2_rpc_port": "6800",
            "ncd_aria2_rpc_token": "ncdownloader1"
        },
        "defaultapp": "dashboard,files,spreed,mail",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "Demo Purpose"
        ],
        "twofactor_enforced_excluded_groups": []
    }
}
```

**Comment by joshtrichards** [comment] 2024-01-12 16:05
Hi @kevinkuan1969 - Thanks for the report, but you didn't include any reproduction steps. What type of document?

It is Nextcloud Office?[1] Text/markdown? etc.

[1] If so, a duplicate of this probably: https://github.com/nextcloud/richdocuments/issues/3357

**Comment by kevinkuan1969** [comment] 2024-01-13 14:47
> It is Nextcloud Office?[1] Text/markdown? etc.

It is Nextcloud Office and not working. Try the Text/markdown and it worked. 
Impressed by the Youtube Nextcloud Hub 7 the new feature and thot it works with all files.



> [1] If so, a duplicate of this probably: [nextcloud/richdocuments#3357](https://github.com/nextcloud/richdocuments/issues/3357)

Yes and it is the same issue. Sorry and missed it out.

**Comment by joshtrichards** [comment] 2024-01-13 14:51
Closing in favor of nextcloud/richdocuments#3357. I encourage you to upvote and/or subscribe to that issue to track progress on it.

**Closed by joshtrichards** 2024-01-13 14:51 UTC
Labels: bug, needs info, 0. Needs triage, 28-feedback
