### ISSUE TITLE
Black lines after switching theme from white -> black -> white

### ISSUE THREAD

**Issue by altucor** [nextcloud/server#14963] opened 2019-04-04 19:21 UTC
![bug](https://user-images.githubusercontent.com/31515257/55581436-7fbcd900-5725-11e9-8cc8-97e5a61ef121.png)

![normal](https://user-images.githubusercontent.com/31515257/55582115-58670b80-5727-11e9-8e3f-b99dee909e38.png)

### Steps to reproduce
1. Go to "settings/user/accessibility"
2. Switch to dark theme, save, then switch back to High contrast theme(white), now you have black lines on white interface like on first screen, on the second normal, expected behaviour

### Expected behaviour
Second screenshot

### Actual behaviour
First screenshot

### Server configuration

**Nextcloud version:** 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Yep, updated from 13.* to 14.* and immediatelly to 15.0.5 but i think it isn't that place where problem comes.

**Comment by szaimen** [comment] 2021-05-21 09:52
I  think you must have enabled the High contrast mode:
![image](https://user-images.githubusercontent.com/42591237/119118902-f82ca400-ba2a-11eb-80c8-8694d283f338.png)
Not a bug -> closing.

**Closed by szaimen** 2021-05-21 09:52 UTC
Labels: 0. Needs triage, bug

**Comment by altucor** [comment] 2021-05-21 10:26
@szaimen Yep you right, thanks.
