### ISSUE TITLE
Breadcrumb ellipsizes early in Brave browser and others

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#21263] opened 2020-06-06 09:51 UTC
### Steps to reproduce
Opening: 
**Home -> Folder1 -> Folder2**
will sometimes look like this (good UI):

![Screenshot_1](https://user-images.githubusercontent.com/36133540/83941431-804e7500-a7eb-11ea-9997-6d86153e5b94.png)

and at other times, like this (bad UI):

![Screenshot_2](https://user-images.githubusercontent.com/36133540/83941443-92c8ae80-a7eb-11ea-80a8-65677fb5614c.png)

Clicking the three dots only shows the preceeding folder, thus requiring an extra click to go back one level.

![Screenshot_3](https://user-images.githubusercontent.com/36133540/83941453-ab38c900-a7eb-11ea-88e5-b353c691bcbb.png)

### Expected behaviour
I dont want the three dot to be displayed when browsing through my NC, it makes navigating unnecessarily longer and serves zero purpose. At all times, the navigation bar should look like the 1st picture.

### Server configuration
NC 18.0.4

**Comment by kesselb** [comment] 2020-06-06 12:51
cc @nextcloud/designers

**Comment by stefan-niedermann** [comment] 2020-06-06 13:10
> At all times, the navigation bar should look like the 1st picture.

It should look like in the 1st picture *as long as there is enough free horizontal space available*. Unfortunately one cannot see on this screenshot the browser size. Can you please post another screenshot where the full browser is visible @pilsnerbeer ?

**Comment by pilsnerbeer** [comment] 2020-06-06 13:25
plenty of space in my browser I think
![Screenshot_2](https://user-images.githubusercontent.com/36133540/83945264-e3e79b00-a809-11ea-950b-d97808dacab6.png)

**Comment by stefan-niedermann** [comment] 2020-06-06 13:27
I would consider this as a bug, yes. In my setup (Firefox LTS) this does not happen. Can you share more details about your environment? (Browser, Browser-Version, Operating System etc)

**Comment by pilsnerbeer** [comment] 2020-06-06 13:34
I just found out that I dont have that problem on Firefox either. I use Brave browser, I disabled all plugins and shields that I use and the problem is still there. (Brave version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)); So it does seem to be browser-related but I dont know what's causing it.

**Comment by raimund-schluessler** [comment] 2020-06-06 17:55
I occasionally have this problem on Firefox as well. This was one of the reasons why we created a Breadcrumbs component for the vue-components: https://nextcloud-vue-components.netlify.app/#/Components/Breadcrumbs
The new component shows the correct behaviour and will be used by the Files app at some point. It's just that no one stepped up to integrate the Breadcrumbs component yet.

**Comment by jancborchardt** [comment] 2020-06-07 00:05
@pilsnerbeer since the issue appears in Brave for you, could you test if you can reproduce this in plain Chromium/Chrome?

**Comment by pilsnerbeer** [comment] 2020-06-07 08:39
@jancborchardt weirdly, I can't reproduce it on Chromium. Only Brave seems to be affected.

**Comment by TessyPowder** [comment] 2020-06-18 07:20
I use Brave too and had this issue before, but i can't currently reproduce it.
I never had this issue in Chrome and pure Chromium

**Comment by jancborchardt** [comment] 2020-06-18 23:23
@pilsnerbeer can you still reproduce this with Nextcloud 19, the current version? :)

**Comment by pilsnerbeer** [comment] 2020-06-21 12:48
Sorry - yes, the issue persists on NC19.

**Comment by wiswedel** [comment] 2021-05-03 20:42
I can still reproduce this on NC 21.0.1 with Chrome 89.0.4389.114

**Comment by wiswedel** [comment] 2021-05-03 20:45
related? even duplicate of https://github.com/nextcloud/server/issues/10304?

**Comment by lunarcontrol** [comment] 2021-05-07 00:37
This is also happening to me. Latest Firefox (88.0) and Nexcloud Server (21.0.1).

Display 1440p.

![image](https://user-images.githubusercontent.com/5004460/117381750-a3692500-ae91-11eb-9c54-d4539549d6c3.png)
![image](https://user-images.githubusercontent.com/5004460/117381783-b2e86e00-ae91-11eb-85d0-82404fdfbb44.png)

**Comment by jospoortvliet** [comment] 2021-06-24 12:33
This is with a full screen 1440P chrome using cloud.nextcloud.com, Nextcloud 22 Beta 5:
![ezgif-3-b56214630f0a](https://user-images.githubusercontent.com/551757/122946631-cf753280-d379-11eb-8db0-497769697453.gif)
So it's not limited to firefox at all ;-)

**Comment by szaimen** [comment] 2022-02-25 14:18
I think this was solved with https://github.com/nextcloud/server/pull/27920

**Closed by szaimen** 2022-02-25 14:18 UTC
Labels: bug, help wanted, design, 1. to develop, feature: files
