### ISSUE TITLE
Some content leaks to public from the user profile 

### ISSUE THREAD

**Issue by kaksikanaa** [nextcloud/server#6418] opened 2017-09-08 11:09 UTC
### Steps to reproduce
1. Add a user image to your profile and save it
2. Copy the image location link from the top right corner of  the UI
3. Paste the link to another browser where there is not active session to the server

### Expected behaviour
The user icon should not be shown on the other browser and the link should be redirected to nc login page.

### Actual behaviour
The link opens and it shows the user icon.

### Server configuration etc.
You can test this in your own demo, it happens there also For example:
https://demo.nextcloud.com/ru5ae8ep/avatar/admin/32?v=1

**Comment by leonklingele-work** [comment] 2017-09-08 11:31
The avatar is leaked regardless of the 'Visibility' setting.
![nextcloud-avatar-leak](https://user-images.githubusercontent.com/31063993/30209784-027449dc-949a-11e7-9224-5fe30cc0efe6.png)

**Comment by LukasReschke** [comment] 2017-09-08 11:35
Duplicate of https://github.com/nextcloud/server/issues/5456

**Closed by LukasReschke** 2017-09-08 11:35 UTC

**Comment by kaksikanaa** [comment] 2017-09-08 11:49
Ah, sorry did not found that when searching possible earlier discoveries...
