### ISSUE TITLE
Image preview in sharing page should show the full image

### ISSUE THREAD

**Issue by zylstra** [nextcloud/server#26782] opened 2021-04-27 06:17 UTC
Why was this "[bug](https://github.com/nextcloud/server/issues/7614)" not fixed if it is so simple to implement?

**Edit:** I learned about an excellent work-around (for me) from another user on the Nextcloud forum:  search for [<ins>Sharing Path</ins>](https://apps.nextcloud.com/apps/sharingpath) on your Nextcloud Apps page.  Read more about it on its [<ins>Github page</ins>](https://github.com/rookie0/nextcloud-sharing-path).  I found even the security to be good:  it allow access only if a "Sharing link" was created from the more standard Nextcloud sharing feature.  This [<ins>discussion</ins>](https://help.nextcloud.com/t/can-i-share-a-full-resolution-image-that-is-viewed-online/114873) is on the Nextcloud forum.

**Comment by szaimen** [comment] 2021-07-02 16:21
Duplicate of https://github.com/nextcloud/photos/issues/541#issuecomment-726195712

**Closed by szaimen** 2021-07-02 16:21 UTC
Labels: 0. Needs triage, enhancement
