### ISSUE TITLE
Setting/editing users e-mail address not working.. (Email address could not be changed!) seems to happen as of version upgrade 11.0.1 -> 11.0.2

### ISSUE THREAD

**Issue by githubos1** [nextcloud/server#4370] opened 2017-04-18 09:49 UTC
### Steps to reproduce
1. as ADMIN, created new user (username & Password)
2. as ADMIN tried to enter EMAIL ADDRESS for this just created user
3. also tried editing existing users EMAIL ADDRESSES 

### Expected behaviour
email address should be added or edited

### Actual behaviour
1. fails with message on top of screen: 'EMail Adresse konnte nicht geändert werden"  = EMAIL address could not be changed
2. logged in as the user himself, e-mail field is visible but NOT ACCESSIBLE, so even the user can not set or edit his own email address
3. also other existing users EMAIL ADDRESSES can not be edited anymore 

### Server configuration

**Operating system**: Hosted Server (ALL-INKL)

**Web server:** Hosted Server (ALL-INKL) 

**Database:** MYSQL 5.5.52

**PHP version:** 7.0.14

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 11.0.1

**Where did you install Nextcloud from:** Automatic updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
FUNNY .... never disabled nor found a way to enable/disable integrity checks

MESSAGE: "Integrity checker has been disabled. Integrity cannot be verified."
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - keeweb: 0.3.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - ownpad: 0.5.7
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - registration: 0.2.3
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - agreedisclaimer
  - disclaimer
  - encryption
  - files_automatedtagging
  - files_retention
  - ocsms
  - survey_client
  - twofactor_u2f
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'cloud.xxxxxxxx.de',
  ),
  'datadirectory' => '/www/htdocs/wXXXXXXXc/-DATA/CLOUDDATA/data',
  'tempdirectory' => '/www/htdocs/wXXXXXXXc/-DATA/CLOUD_TEMP',
  'overwrite.cli.url' => 'http://new14102016.xxxxxxx.de',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'xxxxxxxxx',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => 'xxxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'updater.release.channel' => 'beta',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'cloud_server.os',
  'mail_domain' => 'dus-mail.de',
  'singleuser' => false,
  'loglevel' => 2,
  'defaultapp' => 'galleryplus,gallery,files',
  'allow_user_to_change_display_name' => false,
  'check_for_working_htaccess' => true,
  'appcodechecker' => false,
  'maintenance' => false,
  'theme' => '',
);
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**      FIREFOX 52.0.2 (64-Bit)

**Operating system:** LINUX

**Comment by githubos1** [comment] 2017-04-18 11:01
ADD:
1. Just updated to 11.0.3RC2... same issue remains! !
2. when using the REGISTRATION app "
Registration 0.2.3 von Pellaeon Lin (agpl-lizensiert) "  for adding a new user, the for registration necessary e-mail address is beeing used and visible in ADMIN USER Screen... but stated as "No email address set" in users own PERSONAL web page....   
3. also tried as ADMIN adding new users with REGISTRATION APP beeing disabled.. same issue !!

**Comment by MorrisJobke** [comment] 2017-05-17 02:50
>   - keeweb: 0.3.1
>   - notes: 2.2.0
>   - ownpad: 0.5.7
>   - registration: 0.2.3

Could I ask you to disable those apps and try again?

**Comment by githubos1** [comment] 2017-05-17 13:17
Hi Morris,
disabled all mentioned apps... no change..
also upgraded to 12.0.0 beta3... no changes

Oliver

**Comment by MorrisJobke** [comment] 2017-05-17 15:15
> 'allow_user_to_change_display_name' => false,

This setting disables this.

Duplicate of #642

**Closed by MorrisJobke** 2017-05-17 15:15 UTC
Labels: needs info

**Comment by githubos1** [comment] 2017-05-17 15:37
DAMN,

that was it... also solved the e-mail issue. Once disabled the e-mail was also able to be changed and set by admin  !!!

Not really straight forward... should be two different settings... PLUS  not impact an ADMIN from changing those settings for a specific user  !!

**Comment by MorrisJobke** [comment] 2017-05-17 15:45
> Not really straight forward... should be two different settings... PLUS not impact an ADMIN from changing those settings for a specific user !!

Yes - we know. that is what the other issue is for ;)
