### ISSUE TITLE
Quota-field shows wrong value

### ISSUE THREAD

**Issue by JDemmerle** [nextcloud/server#14803] opened 2019-03-22 09:05 UTC
### Steps to reproduce
At the moment it's not clear when the problem occurred for the first time.

### Expected behaviour
The correct memory should be displayed.
79GB / 90GB

### Actual behaviour
Nextcloud displays:
34,7GB / 90GB

### Server configuration

**Operating system**:
Debian 9

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.1.37

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older NC.
The issue was at NC 14.

**Where did you install Nextcloud from:**
NC homepage, archive.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_automatedtagging: 1.5.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.2
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trackdownloads: 1.4.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "share.example.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/share.example.net",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "tempdirectory": "\/data\/example\/tmp",
        "updatechecker": false,
        "filelocking.enabled": true,
        "asset-pipeline.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "skeletondirectory": "",
        "loglevel": 2,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "simpleSignUpLink.shown": false,
        "trashbin_retention_obligation": "auto, 5",
        "integrity.check.disabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
ANY

**Operating system:**
ANY

<details>
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
-> Nothing to see
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
-> Nothing to see, only a trashbin error. Let me know if this could help (have to encode it first)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
-> Nothing to see
a) The javascript console log
b) The network log
c) ...
```
</details>
</details>

**Comment by JDemmerle** [comment] 2019-03-25 07:52
We found out what happened here.
There are some .part files, which are invisible at the NC web interface.

The question is: how were they uploaded to NC? Because normally NC would say:
On the web interface: "*.part is not a permitted file type"
On the client: "The file is listed in the ignore list. *.part"

Was there a older version of NC were it was allowed to upload .part files?
But there are some files just from march.. So there have to be a other possibility to upload .part files.
We tested it with NC 14 and NC 15.

**Comment by MorrisJobke** [comment] 2019-03-25 08:35
> Are the .part files snippets of a big upload? The 'finished' file should be in the same directory as the .part files or?

usually part files are created during upload and then once the upload is done only an atomic move is needed. If the upload somehow fails in the middle those stray files could be laying around. Usually there is a cleanup procedure that removes them.

cc @icewind1991 @rullzer 

It should be safe to remove them from the filesystem and then do an `occ files:scan` for that user/directory. Then the error in the client should be gone and the quota correct again.

Could you verify?

**Comment by JDemmerle** [comment] 2019-03-25 08:51
> It should be safe to remove them from the filesystem and then do an `occ files:scan` for that user/directory. Then the error in the client should be gone and the quota correct again.

I will test it.
Is it normal that the .part files are stored in the share dir and not in the uploads dir?

**Comment by MorrisJobke** [comment] 2019-03-25 08:53
> Is it normal that the .part files are stored in the share dir and not in the uploads dir?

Yes, because those are then the final files.

This is what it does:

1. upload of file to upload dir - this could happen in chunks and would then consist of multiple files
2. transfer from upload dir to part file on real storage (also assembles multiple chunks into one file)
3. rename part file to final file name

**Comment by JDemmerle** [comment] 2019-03-25 09:09
Okey, thanks !

Seems to work. Quota is shown correctly now.
Which job i have to check? There were files from 7.2.2019 ..
Or would it be the easier way to just set up a cron job?

**Comment by MorrisJobke** [comment] 2019-03-25 09:18
> Or would it be the easier way to just set up a cron job?

Usually you should already have a cron job. Of course setting up the system based cron job for better reliability is always better: see https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html#cron

**Comment by JDemmerle** [comment] 2019-03-25 09:23
There is already a cron job running:
`*/15 * * * * /usr/bin/php -d apc.enable_cli=1 -f /var/www/example/nextcloud/cron.php`

**Comment by MorrisJobke** [comment] 2019-03-25 09:52
Then all is fine.

**Comment by JDemmerle** [comment] 2019-03-25 10:13
Then my question is: Why were there so many old one .part files..?

**Comment by MorrisJobke** [comment] 2019-03-25 11:09
> Then my question is: Why were there so many old one .part files..?

I meant the cron job. Sorry - for the other stuff @rullzer and @icewind1991 should have a look.

**Comment by aignerat** [comment] 2019-06-27 12:06
You got an interesting point JDemmerle, thx for sharing. Did you try to upload one 45+ GB-File? Seems like a connection-problem while uploading to me. It could either be a timeout due to script-maxruntime-configuration. Can you tell if the upload was made through webDAV or the web-component and what the max-speed of the connection is?

**Comment by JDemmerle** [comment] 2019-07-19 11:11
Hello @aignerat 
No i didn't try it.
Could be really a connection-problem. But why is there no cronjob to remove old .part files after X days? I think that would be the easiest way.

The upload was made through the web GUI.

**Comment by aignerat** [comment] 2019-07-20 12:17
well, there could be, see the documentation from MorrisJobke to set it up. I think there is some conceptional thinking involved. For admin-issues it would be helpful to get a report if something was auto-deleted.

**Comment by skjnldsv** [comment] 2020-04-10 09:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 09:17 UTC
Labels: 0. Needs triage, bug
