### ISSUE TITLE
Search lost

### ISSUE THREAD

**Issue by SLilgreen** [nextcloud/server#35831] opened 2022-12-19 22:26 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When any user does a search then they select to search for more results the search disappears making it impossible to search

### Steps to reproduce

1.search
2.view results
3. select search for more

### Expected behavior

Search disappears

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
none
```

**Comment by szaimen** [comment] 2022-12-20 00:05
which nc version?

**Comment by SLilgreen** [comment] 2022-12-20 00:10
25.0.2 is the version I am on.

**Comment by XueSheng-GIT** [comment] 2022-12-21 05:11
Duplicate of https://github.com/nextcloud/server/issues/35558?

**Comment by SLilgreen** [comment] 2022-12-21 15:06
It looks like that is the same issue. What is the fix for that issue? Love NextCloud but the search function is bad enough without this happening.

**Comment by solracsf** [comment] 2022-12-23 08:38
Closing as duplicate of https://github.com/nextcloud/server/issues/35558

**Closed by solracsf** 2022-12-23 08:38 UTC
Labels: bug, 0. Needs triage, 25-feedback
