### ISSUE TITLE
Client-side per-app access rights

### ISSUE THREAD

**Issue by Grunthos** [nextcloud/server#24469] opened 2020-12-01 05:29 UTC
**Problem**

I'd like to grant various apps access to apps on my NC server, but not to the whole server.

For example, grant a calendar app on my phone access to CalDav, or Floccus access to the Bookmarks app. I *do not* want them to be able to do anything other than run Calendar or Bookmarks on my behalf. If someone hacked the app on my phone, I do not want those credentials to grant access to Files etc.

**Describe the solution you'd like**

Auth keys (OAuth?) on a per-app basis.

**Describe alternatives you've considered**

A really low-tech solution is to create one account per special app, but it is pretty unsatisfactory in terms of integration!

**Comment by kesselb** [comment] 2020-12-01 10:08
Duplicate of https://github.com/nextcloud/server/issues/9117

**Closed by kesselb** 2020-12-01 10:08 UTC
Labels: 0. Needs triage, enhancement
