### ISSUE TITLE
Nextcloud 23 a lot of 'shared locks' messages

### ISSUE THREAD

**Issue by apg1980** [nextcloud/server#29987] opened 2021-11-30 15:45 UTC
After upgrading to nc 23
```
{"reqId":"xnSn3ShzL2PT2Oz10Xoj","level":3,"time":"2021-11-30T16:40:11+01:00","remoteAddr":"...","user":"...","app":"no app in context","method":"POST","url":"/remote.php/dav/bulk","message":"\"GITARRE/Software/AudacityPortable/Data/Portable Settings/audacity.cfg\" is locked, existing lock on file: 3 shared locks","userAgent":"Mozilla/5.0 (Windows) mirall/3.4.0stable-Win64 (build 20211129) (Nextcloud, windows-10.0.22000 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"23.0.0.10","id":"61a6490d190e5"}
```

no entrys in db table for locks

**Comment by acsfer** [comment] 2021-12-29 11:51
Duplicate of https://github.com/nextcloud/server/issues/29985

**Closed by acsfer** 2021-12-29 11:51 UTC
Labels: bug, 0. Needs triage, 23-feedback
