### ISSUE TITLE
Users disappear from contacts menu after changing e-mail address

### ISSUE THREAD

**Issue by djermann** [nextcloud/server#10266] opened 2018-07-17 08:17 UTC
### Steps to reproduce
1. Click on the contacts menu and take note of the listed users:
![contact_search](https://user-images.githubusercontent.com/20949681/42803620-cc835a90-89a6-11e8-86cf-9641292a8483.png)
2. One of the users changes his e-mail address on the personal settings page.
3. Open the contacts menu again.

### Expected behaviour
All the users should get listed again.

### Actual behaviour
All but the user, who changed his e-mail address, appear.

## Server configuration detail

**Operating system:** Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 10.1.26

**PHP version:** 7.0.30-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.4 - 13.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 
fresh install
**Where did you install Nextcloud from:** 
nextcloud.com website
<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.2
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - onlyoffice: 1.3.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.4
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - files_pdfviewer
 - richdocuments
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbtype": "mysql",
    "version": "13.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "log_rotate_size": "10485760",
    "log_type": "errorlog",
    "loglevel": "0",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "trashbin_retention_obligation": "auto,90",
    "activity_expire_days": 180,
    "logtimezone": "Europe\/Zurich",
    "onlyoffice": {
        "verify_peer_off": true
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36

**Operating system:** 
Debian 9.4
## Logs
I have set the Loglevel to 0 but no entries appear, when I open the contacts menu, neither in the Browsers Console nor in the Nextcloud.log. 
When I change the e-mail address in the profile settings of a user, this entry appears in the Nextcloud.log:

```
2018/07/17 10:10:11 [error] 13517#13517: *57685 FastCGI sent in stderr: "PHP message: [owncloud][core][0] Sent mail to "Array
(
    [***REMOVED SENSITIVE VALUE***] => ***REMOVED SENSITIVE VALUE***
)
" with subject "Email address for ***REMOVED SENSITIVE VALUE*** changed on https://***REMOVED SENSITIVE VALUE***/"" while reading response header from upstream, client: ***REMOVED SENSITIVE VALUE***, server: ***REMOVED SENSITIVE VALUE***, request: "PUT /settings/users/***REMOVED SENSITIVE VALUE***/settings HTTP/2.0", upstream: "fastcgi://unix:/var/run/php7.0-fpm-***REMOVED SENSITIVE VALUE***.sock:", host: "***REMOVED SENSITIVE VALUE***"
```

**Comment by MorrisJobke** [comment] 2018-07-24 12:15
cc @juliushaertl @skjnldsv @georgehrke

**Comment by skjnldsv** [comment] 2019-06-07 15:57
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-07 15:57 UTC
Labels: bug, feature: contacts menu
