### ISSUE TITLE
Document Server not installable - cURL error 28

### ISSUE THREAD

**Issue by christianvw** [nextcloud/server#19008] opened 2020-01-20 02:20 UTC
### Steps to reproduce

1. Use a moderate internet connection (since this is a timeout error)
2. Install a larger app (e.g. Document Server - 300MB) via the "app store"
3. Due to the timeout of 30 seconds it will fail

### Expected behaviour

App should be fully installed.

### Actual behaviour

Download fails with:

> cURL error 28: Operation timed out after 30000 milliseconds with 73837972 out of 305964280 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

This is especially sad since the advertised "Nextcloud and OnlyOffice are pre-installed / ready-to-go" does not work anymore if you have a weak internet connection.

This might be due to a hard-coded timeout as shown in the (whyever closed) issues below:

- https://github.com/nextcloud/server/issues/17685
- https://github.com/nextcloud/documentserver_community/issues/11

### Server configuration

**Operating system: Linux / Debian**

**Web server: Apache**

**Database: MariaDB**

**PHP version: 7**

**Nextcloud version: 18.0.0** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Docker Hub

**Comment by BeNeDeLuX** [comment] 2020-01-20 19:36
I can confirm the same Error here

**Comment by kesselb** [comment] 2020-01-21 13:17
> This might be due to a hard-coded timeout as shown in the (whyever closed) issues below: #17685

At least I can give you an answer to this question: The issue was closed because it's a duplicate but I reference the wrong issue number. That's indeed a bit confusing but fixed now.

**Comment by InfamousUser** [comment] 2020-01-24 17:00
"cURL error 28: Operation timed out after 30000 milliseconds with 130053548 out of 315860148 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

 Remove the timeout, it doesn't make sense to assume that every app will install in same timeframe.

**Comment by christianvw** [comment] 2020-01-25 04:45
Even inside our datacenter with 1Gbit/s the download via app store crashed with a message like "an error occurred" on the front end. Nothing in the logs.

The app was listed in the app list but nothing worked.

**Comment by szaimen** [comment] 2020-01-25 13:42
I found this regarding the timeout:
https://github.com/nextcloud/server/pull/18976

**Comment by kesselb** [comment] 2020-01-25 13:59
Should be fixed by https://github.com/nextcloud/server/pull/19017

**Comment by marshalleq** [comment] 2020-02-09 08:25
I get this error over a Gigabit connection....

**Closed** 2020-02-09 08:30 UTC
Labels: 0. Needs triage, 18-feedback, bug, needs info

**Comment by InfamousUser** [comment] 2020-02-10 03:43
Simply use the fix posted above.

**Comment by marshalleq** [comment] 2020-02-10 03:48
Sorry, I don't see an actual accessible fix, only a fix in source code, which given it needs to be compiled will not work for me.  Nevertheless, I did a manual install and applied it that way.  Unfortunately, there are more issues than just this one when it comes to enabling this '1 click' update.  So it's a work in progress for me :)

**Comment by InfamousUser** [comment] 2020-02-11 04:35
No, you just change the timeout time in config file!

**Comment by klemens-u** [comment] 2020-02-18 13:08
Still an issue with 18.0.1
![grafik](https://user-images.githubusercontent.com/1863743/74738901-15872700-5258-11ea-9440-a0bc7c5bf665.png)

**Comment by InfamousUser** [comment] 2020-02-19 07:53
Ok so your server is too slow for 120s install, which can easily be exceeded on slow connections. I think 2 minutes is too slow for 300MB package download + install, I don't know why they implemented a fixed value for a hhge variety of packages. Change the value yourself. This value should be specified by the app creator, only they can know how long their app is supposed to take to install.

**Comment by prghix** [comment] 2020-03-03 10:37
120 seconds is just not enough:

Error: cURL error 28: Operation timed out after 120000 milliseconds with 231556380 out of 315849196 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by aslmx** [comment] 2020-03-05 09:15
So. Also ran into this issue today. **Can the timeout be adjusted now? Where/how?**

**Comment by prghix** [comment] 2020-03-05 09:21
> So. Also ran into this issue today. **Can the timeout be adjusted now? Where/how?**

of course. Just edit: lib/private/Installer.php, line 274. Change 120 to 300.

$client->get($app['releases'][0]['download'], ['save_to' => $tempFile, 'timeout' => 300]);

**Comment by aslmx** [comment] 2020-03-06 07:14
Thanks. Worked like a charm. Is there any one taking care that this workaround (or fix?) makes it into some place that people find it more easily in the future? Like putting this into the settings UI, or at least in the config? It would also be nice if the error would be handled with additional info for the (administrative)user. Right now it is  just cURL saying "I timed out". No hint that the timeout can be increased. Thanks for considering this!

**Comment by prghix** [comment] 2020-03-06 09:56
There is a suggestech patch SOMEWHERE... to be included in the Nextcloud 19.. as far as I remember.

So with CLI there should be no timeout...

**Comment by b-pfl** [comment] 2020-03-07 22:58
> There is a suggestech patch SOMEWHERE... to be included in the Nextcloud 19.. as far as I remember.
> 
> So with CLI there should be no timeout...

Nope, even with CLI the timeout happened when running php occ app:install documentserver_community!

**Comment by prghix** [comment] 2020-03-08 09:40
> Nope, even with CLI the timeout happened when running php occ app:install documentserver_community!

I did mean the future release of course...

**Comment by ftoral** [comment] 2020-03-31 06:05
For all who ran into this issue and land here : it is no more needed to modify your sources files.

A fix, only valid for CLI mode, was backported into 18: https://github.com/nextcloud/server/pull/19430
So, I've been able to install it with:
```
sudo -u nextcloud php occ app:install documentserver_community
```

@b-pfl you should maybe upgrade and try again.

**Comment by brdobrdo** [comment] 2020-04-20 17:25
> 
> 
> > So. Also ran into this issue today. **Can the timeout be adjusted now? Where/how?**
> 
> of course. Just edit: lib/private/Installer.php, line 274. Change 120 to 300.
> 
> $client->get($app['releases'][0]['download'], ['save_to' => $tempFile, 'timeout' => 300]);

Hi using nextcloud on my hosted domain.

I have this in installer.php

`// Download the release
				$tempFile = $this->tempManager->getTemporaryFile('.tar.gz');
				$timeout = $this->isCLI ? 0 : 120;
				$client = $this->clientService->newClient();
				$client->get($app['releases'][0]['download'], ['save_to' => $tempFile, 'timeout' => $timeout]);`

After I changed 120 to 500 nothing changed when I tried to download from nextclout. Again timeout after 120000 miliseconds.

Any help on this one?

Thanks!

**Comment by prghix** [comment] 2020-04-21 08:59
@brdobrdo  which line is it?

**Comment by brdobrdo** [comment] 2020-04-21 10:00
@prghix 277 

I put in some more hours yesterday... and finally solved it, but I am not sure at which step of all the things I tried. The steps were:
1. Changed timeout to 1200 sec on all php files cpanel allowed me to do it outside of file manager
2. changed installer.php timeout manually to 1200 sec (line 277)
3. changed client.php to timeout  to1200 sec (/nextcloud/lib/private/Http/Client)

After all these changes, I stopped receiving timeout error from nextcloud app installer. Since the file was big (300M) I had some futher problems due to small hosting disk size (2GB). It takes cpanel (or the thing that does these kind of installations) a lot of time to download, extract and install. I left it cook overnight. This morning the document server package was downloaded and enabled in nextcloud. 

thanks @prghix for the tip! It helped.

**Comment by koltaig75** [comment] 2020-05-08 11:08
I cannot follow this step:
> 2.  changed installer.php timeout manually to 1200 sec (line 277)

I find in the nextcloud www documentroot, but cannot found any file wit name 'installer.php'
Please help me, which location could that installer.php file?

**Comment by brdobrdo** [comment] 2020-05-08 12:45
> 
> 
> I cannot follow this step:
> 
> > 1. changed installer.php timeout manually to 1200 sec (line 277)
> 
> I find in the nextcloud www documentroot, but cannot found any file with name 'installer.php'
> Please help me, which location could that installer.php file?

installer.php  I changed is in public_html/nextcloud/lib/private

But...

I think my way of doing things is not really good because I am not educated enough. 

Better way I found is to download whole package from [here](https://github.com/nextcloud/documentserver_community/releases/download/v0.1.5/documentserver_community.tar.gz) and then upload it here: public_html/nextcloud/apps/documentserver_community using your cpanel file manager and then extract in the same folder.

When you log in to http://yourdomain/nextcloud and go to Apps you will see the app there and just enable it. 

This is the most fool proof way if you are a noob like me.  

From what I read, this package doesn't download because default settings are made under assumption that everyone has fast internet connection and this is 300 MB download. 

Good luck!

**Comment by koltaig75** [comment] 2020-05-09 09:08
This workaround with manual download and extract solved the problem! Thank you! 
This is the most clear solution! Don't need to modify timeout parameters in the php or ini files!

**Comment by szaimen** [comment] 2020-05-09 09:19
Probably the best way is 
`occ app:install documentserver_community`

**Comment by brdobrdo** [comment] 2020-05-09 09:34
> Probably the best way is
> `occ app:install documentserver_community`
> Because there is no timeout over CLI.
> 
> On shared webhosters you can use the occweb app for that:
> https://apps.nextcloud.com/apps/occweb

When you install like this, is there timeout issue?

**Comment by szaimen** [comment] 2020-05-09 09:39
> > Probably the best way is
> > `occ app:install documentserver_community`
> > Because there is no timeout over CLI.
> > On shared webhosters you can use the occweb app for that:
> > https://apps.nextcloud.com/apps/occweb
> 
> When you install like this, is there timeout issue?

There is NO timeout issue when you install it like this, afaik.

**Comment by koltaig75** [comment] 2020-05-09 10:48
Yes its a best way to get to the same curl timeout issue! 
I've found this recommendation on many posts, but it not working at all like any timeout modification tips. 
Lets try it, on a clean debian 10 install and a nextcloud on it, u will surely face this problem. 
This problem can be experienced with dockler nextcloud image too.
occ uses php and curl to download and extract. That mechanism has some timeout issue. It's not so important, but occ running uses the /etc/php/<version#>/cli/php.ini, but don't help if the max_execution and max_inpus settings are raised.

The best way is what  [brdobrdo wrote down](https://github.com/nextcloud/server/issues/19008#issuecomment-625798198), 
Any other things simply not working!

Download the [package ](https://github.com/nextcloud/documentserver_community/releases/download/v0.1.5/documentserver_community.tar.gz) manualy and extract to your nextcloud apps dir my is: /var/www/html/nextcloud/apps
After it can be enabled from nextcloud applications panel.

**Comment by koltaig75** [comment] 2020-05-09 18:01
Just an idea to solve this issue,

The documentserver_community package needed by the ONLYOFFICE package which is the part of basic nextcloud 18 install pack. So it could be the part of preinstalled pakages with onlyoffice. 
One more fact near that, it cannot be installed from the apps user panel.

(If the communityserver image would be the part of the nextcloud base install package, then this issue only rises if someone remove it and later try to download it again from the apps panel. I think it no more than a percent of the affected cases. Now everyone faces with it who trying to edit a sheet or document when enable and testing onlyoffice app. features.)

**Comment by vgdh** [comment] 2020-06-12 10:20
i have the same issue with docker instance of NC 19.

**Comment by hansimausisteffiwurstbrot** [comment] 2020-10-28 11:15
I'm having the time out issue with 19.04 right now, trying to install  _Collabora Online - Built-in CODE Serve_

`cURL error 28: Operation timed out after 120000 milliseconds with 183308627 out of 349048294 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

**Comment by hadasApplied** [comment] 2020-11-06 20:43
same. any fix?

**Comment by brdobrdo** [comment] 2020-11-07 13:37
Try to upload the installation files to server via CPanel or whatever you use. See my long post above.
