### ISSUE TITLE
Cannot access after upgrade

### ISSUE THREAD

**Issue by fir3wall** [nextcloud/server#12618] opened 2018-11-23 07:46 UTC
Hey,

Trying to login to the system after upgrade produces the following error. It's 1and1 hosted service so no access via shell or to webserver logs. Was working perfectly before upgrade

### Steps to reproduce
1. Try to access login page after upgrade to 14.0.4 from 13.0.2

### Expected behaviour
Login page is working

### Actual behaviour
Receiving error

Fatal error: require_once(): Failed opening required '/homepages/46/d602203667/htdocs/<myd omain>/lib/autoloader.php' (include_path='.:/usr/lib/php7.2') in /homepages/46/d602203667/htdocs/<my domain>/lib/base.php on line 575

### Server configuration

**Operating system**:
Don't know (Hosted 1and1)
**Web server:**
Don't know (Hosted 1and1)
**Database:**
Mysql 
**PHP version:**
PHP 7.2
**Nextcloud version:** (see Nextcloud admin page)
14.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.2
**Where did you install Nextcloud from:**
Originally zip then used upgrader

**Comment by fir3wall** [comment] 2018-11-23 07:55
Hello,
Done some digging and performed following actions:

1. Grabbed file autoloader.php from nextcloud GIT and dropped it into lib
2. Now getting error:
```
Composer autoloader not found, unable to continue. Check the folder "3rdparty". Running "git submodule update --init" will initialize the git submodule that handles the subfolder "3rdparty".
```
Not sure it was needed but desperate to get to my (encrypted) files!

Thanks
Dariusz

**Comment by danielkesselberg** [comment] 2018-11-24 19:48
Looks like something went wrong during the update process. I would try to use the zip from https://nextcloud.com/install/#instructions-server and upload the files to your webspace. Please backup your current version and also the database.

**Comment by MorrisJobke** [comment] 2019-03-25 12:40
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-03-25 12:40 UTC
Labels: bug, feature: install and update, needs info
