### ISSUE TITLE
curl doesn't work with app-passwords after update

### ISSUE THREAD

**Issue by summerm78** [nextcloud/server#19515] opened 2020-02-17 10:04 UTC
After we updated nextcloud from version 16 to 18.0.1, app-passwords doesn't work with curl. 

### Steps to reproduce
1. Try to upload a file or create a folder via curl and app-password:
`curl -u automationuser:xxxx-yyyy-zzzz-yyyy-yyyyy' -X MKCOL "https://our.nextcloud.com/remote.php/webdav/automationuser/test/"`

### Expected behaviour
Files should be uploaded and folders created. When using the users password instead of the app-password everything works as it should.

### Actual behaviour
Output of the command:
`<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured</s:message>
</d:error>`

Correspondending log:
`{"reqId":"XkpPvzzZ5XJGPFi0C0JcfAAAABw","level":2,"time":"2020-02-17T08:33:03+00:00","remoteAddr":"172.23.128.1","user":"--"
,"app":"user_ldap","method":"MKCOL","url":"/remote.php/webdav/automationuser/test/","message":"Bind failed: 49: Invalid 
credentials","userAgent":"curl/7.66.0","version":"18.0.1.3"}
{"reqId":"XkpPvzzZ5XJGPFi0C0JcfAAAABw","level":2,"time":"2020-02-17T08:33:03+00:00","remoteAddr":"172.23.128.1","user":"--","app":"core","method":"MKCOL","url":"/remote.php/webdav/automationuser/test/","message":"Login failed: 'automationuser' (Remote IP: '172.23.128.1')","userAgent":"curl/7.66.0","version":"18.0.1.3"}`

### Server configuration

**Operating system:**
RHEL 7.7

**Web server:**
Apache 2.4.34-15

**Database:**
mariadb-5.5.64-1

**PHP version:**
php 7.2.24-1

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
From 16.0.8 via 17.0.3

**Where did you install Nextcloud from:**
Nextcloud packages

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.2.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - recommendations
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "xxxxxx.com",
            "hostname-fqdn"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/xxxxxx",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "proxy": "172.168.0.1:8080",
        "htaccess.IgnoreFrontController": false,
        "lost_password_link": "https:\/\/xxxxx.com",
        "trashbin_retention_obligation": "14, 21",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

**Comment by kesselb** [comment] 2020-02-17 10:29
Looks similar to https://github.com/nextcloud/server/issues/19408

**Comment by summerm78** [comment] 2020-02-17 10:57
Looks similar. Two differences I see so far:
- app-passwords were broken directly after the nextcloud upgrade
- creating new app-passwords doesn't solve the issue

**Comment by szaimen** [comment] 2021-06-07 18:19
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 18:19 UTC
Labels: 0. Needs triage, bug, feature: authentication
