### ISSUE TITLE
Update from NC12b4 to NC12RC2 won't start due to unexpected autotest-checkers.sh and other oddities

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#4985] opened 2017-05-19 21:30 UTC
### Steps to reproduce
1. In NC12b4, enter administration page, NC12RC2 is shown as update
2. Start updater app, start update

### Expected behaviour
Update should start (and finish smoothly).

### Actual behaviour
A warning appears:

(!) Check for expected files
    The following extra files have been found:
        autotest-checkers.sh

The update process is interrupted and cannot be continued.

If I delete it (or move it aside), update starts (and finishes) fine.

**Comment by nursoda** [comment] 2017-05-19 21:36
I also got this in the log during that update (right after update started):
file_put_contents(<my_datadir>/.htaccess): failed to open stream: Permission denied at <my_webroot>/lib/private/Setup.php#515

**Comment by nursoda** [comment] 2017-05-19 21:45
Execpt for that, update went fine.

But each time I login, I get two identical log enties in the same second:
> Missing argument 2 for OC\ServerContainer::getAppContainer(), called in <my_webroot>/lib/private/ServerContainer.php on line 124 and defined at <my_webroot>/lib/private/ServerContainer.php#80

**Comment by MorrisJobke** [comment] 2017-05-19 21:57
We know :/ https://help.nextcloud.com/t/earn-a-t-shirt-by-testing-nextcloud-12-beta-2/12374/56?u=morrisjobke

Fixed in RC 2

**Comment by MorrisJobke** [comment] 2017-05-19 21:58
The only way to fix this is to deleted the `autotest-checkers.sh` from the folder - then the update runs fine.

**Closed by MorrisJobke** 2017-05-19 21:57 UTC

**Comment by nursoda** [comment] 2017-05-19 22:03
For me, deleting that file was a non-issue. Might only be problematic without shell access.
But I'm irritated about "Fixed in RC2" - it should read "Will be fixed in RC3" I guess? OK!
What about the other log entry issues? Non-issues? Shall I ask in the forum? Open separate bugs?

**Comment by LukasReschke** [comment] 2017-05-19 22:04
The `.htaccess` one: Open a separate one. Not sure if it is a dupe.
The ServerContainer one: Dupe of https://github.com/nextcloud/server/issues/4979 – will be fixed in tomorrows RC3 :)

**Comment by LukasReschke** [comment] 2017-05-19 22:04
Patch at https://github.com/nextcloud/server/pull/4980 :)

**Comment by nursoda** [comment] 2017-05-19 22:05
T-h-a-n-k-s
Will check if there's a matching bug prior to opening one.

**Comment by LukasReschke** [comment] 2017-05-19 22:05
Awesome. And thanks for testing the RCs and Betas. Much appreciated! 🚀

**Comment by MorrisJobke** [comment] 2017-05-19 22:44
> For me, deleting that file was a non-issue. Might only be problematic without shell access.
> But I'm irritated about "Fixed in RC2" - it should read "Will be fixed in RC3" I guess? OK!

Nope - the file is not there anymore in RC2, but you will notice this only if you have installed RC2, because the checks are run before the code is replaced ;)
