### ISSUE TITLE
Permission menu in share slider not showing properly hence can't change permission

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/server#28906] opened 2021-09-20 17:29 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. You must have a certain amount of elements in your folders in order to scroll
2. Get to the bottom and open the share menu of a file/folder of your choice
3. Share a link for example and click on the "..." to set permission.
4. Observe there's no menu showing and it work eventually if you click again 2 times more.
5. Also once the permission menu is open, scroll and see what happens.

I've made a video, it's easier to understand and reproduce on your side then:

https://user-images.githubusercontent.com/764332/134045929-7fcb0a3a-46df-4958-87b9-69f8b51c0b59.mp4

### Expected behaviour
I should see the menu correctly displayed no matter which element I'm trying to share. And the menu should stay fixed even though I'd need to scroll while having it opened.

### Actual behaviour
The permission menu is not showing properly when it concerns elements at the bottom of the page

### Server configuration

**Nextcloud version:** 
Reproduced on **20.0.12 - 21.0.3 and 22.1.1**. 

### Client configuration
**Browser:** Reproduced on **FF 92, Safari 14.1 and Chrome 93**

**Operating system:**
Mac 10.14.6

**Comment by szaimen** [comment] 2021-09-20 18:07
Duplicate of https://github.com/nextcloud/server/issues/23872

**Closed by szaimen** 2021-09-20 18:07 UTC
Labels: bug, 0. Needs triage
