### ISSUE TITLE
Nextcloud 13 Admin tab in administrater users, where is it?

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/server#8201] opened 2018-02-06 14:27 UTC
I've just done the upgrading of the server from 12.0.4 to 13 without errors. just 3 apps disabled (documments, tasks and other one that i don't remember)

Now when i go to admin user i don't have the admin tab. Is this normal? where do i go to see the version i have installed in the server from the browser (firefox)?

best regards

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Ricardosgeral** [comment] 2018-02-06 14:36
ok I found it, it changed place. It's in settings of the user itself.

Just a few comments: The server seems considerably faster in browser. Noticed several graphical issues (text overlapping and general layout problems in 'apps' that I'm sure it will be fixed in future realeases.

good work

**Comment by MorrisJobke** [comment] 2018-02-06 17:06
> ok I found it, it changed place. It's in settings of the user itself.

We combine personal and admin settings in "settings" ;)



> Just a few comments: The server seems considerably faster in browser. Noticed several graphical issues (text overlapping and general layout problems in 'apps' that I'm sure it will be fixed in future realeases.

We are aware of this: #8043

Try to do this https://github.com/nextcloud/server/issues/8043#issuecomment-360776226:

* rm -r data/appdata_/css/
* occ files:scan-app-data
* reload the page


I will close this as a duplicate of #8043 and we also plan to provide a repair step that fixes it.

cc @nextcloud/theming @juliushaertl  @skjnldsv

**Closed by MorrisJobke** 2018-02-06 17:06 UTC
