### ISSUE TITLE
EXTERNAL STORAGE - SFTP - File not found issue when I open file. 

### ISSUE THREAD

**Issue by Aristide404** [nextcloud/server#26527] opened 2021-04-12 18:30 UTC
Hello !

### DESCRIPTION :

I have a problem for access to SFTP External File Storage with Nextcloud. I explain. 

- I can browse file
- I can open directory without problems.

When you open a file (PDF, Picture), I get error file not found. 

After investigate logs files in Nextcloud, I have see this error : 

Error: fopen(sftpread://home/user//Documents/file.pdf): failed to open stream: &quot;OCA\Files_External\Lib\Storage\SFTPReadStream::stream_open&quot; call failed at /var/www/html/cloud/apps/files_external/lib/Lib/Storage/SFTP.php#379

NOTE 1 : You can see duplicate of // in path. 
NOTE 2 : Only user and file.pdf has changed in this log paste. 

 I use Nextcloud 21.0.1 (Debian Buster). 

### WAY TO REPRODUCE : 

1 : Go to settings
2 : Add a SFTP external storage (I use standard user/password).
3 : Set a path where you want. 
4 : Validate. 
5 : Open your external storage file. 
6 : Open PDF/Picture/Text files. 

### I HAVE TRY :

I have try to add, remove the slash at the end of path.
I have try to update Nextcloud. 
I have try a new installation on a new LXC container : Same problem. 

After lot of searching, I have solve this problem with a small modification in SFTP.php located at /var/www/html/cloud/apps/files_external/lib/Lib/Storage/SFTP.php. 

I publish diff of file in this bug report (I don't know if its a good way for solve problem) : 

```
--- /home/user/SFTP.php      2021-04-12 18:29:21.883095144 +0200
+++ apps/files_external/lib/Lib/Storage/SFTP.php        2021-04-12 18:46:55.624211530 +0200
@@ -371,18 +371,8 @@
                        switch ($mode) {
                                case 'r':
                                case 'rb':
-                                       if (!$this->file_exists($path)) {
-                                               return false;
-                                       }
-                                       SFTPReadStream::register();
-                                       $context = stream_context_create(['sftp' => ['session' => $this->getConnection()]]);
-                                       $handle = fopen('sftpread://' . trim($absPath, '/'), 'r', false, $context);
-                                       return RetryWrapper::wrap($handle);
                                case 'w':
                                case 'wb':
-                                       SFTPWriteStream::register();
-                                       $context = stream_context_create(['sftp' => ['session' => $this->getConnection()]]);
-                                       return fopen('sftpwrite://' . trim($absPath, '/'), 'w', false, $context);
                                case 'a':
                                case 'ab':
                                case 'r+':
```

### DETAILS ABOUT PACKAGE : 

Nextcloud Server : Nextcloud 21.0.1
OS : GNU/Linux Debian Buster (amd64)
Environment : LXC Container (Proxmox)

Packages : 

```php-bcmath/stable,now 2:7.3+69 all  [installé]
php-cli/stable,now 2:7.3+69 all  [installé]
php-common/stable,now 2:69 all  [installé, automatique]
php-curl/stable,now 2:7.3+69 all  [installé]
php-gd/stable,now 2:7.3+69 all  [installé]
php-gmp/stable,now 2:7.3+69 all  [installé]
php-imagick/stable,now 3.4.3-4.1 amd64  [installé]
php-intl/stable,now 2:7.3+69 all  [installé]
php-json/stable,now 2:7.3+69 all  [installé]
php-mbstring/stable,now 2:7.3+69 all  [installé]
php-memcache/stable,now 3.0.9~20170802.e702b5f-2 amd64  [installé]
php-pgsql/stable,now 2:7.3+69 all  [installé]
php-xml/stable,now 2:7.3+69 all  [installé]
php-zip/stable,now 2:7.3+69 all  [installé]
php7.3-bcmath/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-cli/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-common/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-curl/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-gd/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-gmp/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-intl/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-json/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-mbstring/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-opcache/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-pgsql/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-readline/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-xml/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3-zip/stable,stable,now 7.3.27-1~deb10u1 amd64  [installé, automatique]
php7.3/stable,stable,now 7.3.27-1~deb10u1 all  [installé, automatique]
php/stable,now 2:7.3+69 all  [installé]
apache2/stable,stable,now 2.4.38-3+deb10u4 amd64  [installé]
```

### SOURCES : 

https://help.nextcloud.com/t/cant-open-files-on-external-storage/84712
https://github.com/nextcloud/server/issues/21429

Solution has found here : 
https://github.com/nextcloud/server/issues/20979

If you want more information, don't hesitate to ask :) Its my first bug report for NC !

**Comment by szaimen** [comment] 2021-07-02 12:54
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by Aristide404** [comment] 2021-07-03 21:39
> Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

Hello ! 

Nextcloud upgrade to 21.0.3 but bug is not fixed

**Comment by szaimen** [comment] 2021-07-06 08:48
cc @icewind1991

**Comment by szaimen** [comment] 2021-07-06 10:46
Duplicate of https://github.com/nextcloud/server/issues/21429

**Closed by szaimen** 2021-07-06 10:46 UTC
Labels: 1. to develop, bug, feature: external storage
