### ISSUE TITLE
nextcloud 12 upgrade error

### ISSUE THREAD

**Issue by nemesi2017** [nextcloud/server#5056] opened 2017-05-23 07:43 UTC
I tried to upgrade by web interface nextcloud from 11.0.1 to 12. At a certain point, an error appeared:

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'DELETE FROM `oc_reader_bookmarks` b WHERE b.file_id = ?' with params [36]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b WHERE b.file_id = '36'' at line 1

And this is the log:
Preparazione dell'aggiornamento
Imposta il livello del log per il debug
Modalità di manutenzione attivata
Aggiornamento schema database
Database aggiornato
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'DELETE FROM `oc_reader_bookmarks` b WHERE b.file_id = ?' with params [36]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b WHERE b.file_id = '36'' at line 1

Someone had the same problems or know a solution? Now my nextcloud is not working at all.

Thank you for your help :)

**Comment by MorrisJobke** [comment] 2017-08-14 16:08
Duplicate of #5293

**Closed by MorrisJobke** 2017-08-14 16:08 UTC
