### ISSUE TITLE
Authenticate Administrator lasts about 2 seconds

### ISSUE THREAD

**Issue by spx7** [nextcloud/server#14609] opened 2019-03-10 08:35 UTC
**Is your feature request related to a problem? Please describe.**
 
changing a user-thing, like users pw or users emailadr. or sending a welcome-email again always leads to the dialog request for admin pw. (which disappears too quick!)

~~The Dialog "Legitimierung benötigt Dieser Vorgang benötigt eine Passwortbestätigung von Dir"

requests the passwort to authenticat for the requested action. It disappears after about 2 seconds, maybe 3 seconds, that is problematic because my password is complicated and I cannot type THAT fast..

**Describe the solution you'd like**

please make it (pw request) last a little longer, or at least - give users the possibility to chance the option at the settings page.

**Describe alternatives you've considered**

make it last longer (the pw request) when some javascript notices that you've started typing something.. no option at the settings page will bloat more and more options, but more Javascript will maybe slow nextcloud down(?)

**Additional context**

Then nextcloud says: 
Du hast das Passwort nicht rechtzeitig eingegeben
Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.

this  really annoys me and I am wondering if it is only me...getting high blood pressure afterwards..

**Comment by Nils160988** [comment] 2019-03-23 12:10
Which version of Nextcloud are you using? A similar issue was fixed a few months ago (https://github.com/nextcloud/server/issues/11224).
It might be a better idea to fill out the issue template instead of the enhancement.

**Comment by kesselb** [comment] 2019-03-30 20:43
Duplicate of #11224 (fixed with Nextcloud 14.0.4)

**Closed by kesselb** 2019-03-30 20:43 UTC
Labels: 0. Needs triage, enhancement

**Comment by kesselb** [comment] 2019-03-30 20:45
Duplicate of #11224 (fixed with Nextcloud 14.0.4)
