### ISSUE TITLE
permalink / "local link" of files lead to parent folder of file instead to file

### ISSUE THREAD

**Issue by chaos-prevails** [nextcloud/server#2230] opened 2016-11-22 09:35 UTC
Dear NC,

the permalink of files (click on three dots next to file -> Details -> click on link symbol) leads to the parent folder of the file, not to the file directly. This is a big issue if you want to combine NC with other collaboration tools (and add a link to a file stored in NC) and want to rely on the internal user permissions of NC for access control.

### Steps to reproduce
1. copy the local link of a file
2. paste & go it into a new tab (logged in with same user)
3. parent folder of file is shown

### Expected behaviour
the file should be downloaded (e.g. shown in the browser, opened with application or downloaded)

### Actual behaviour
instead the parent folder of the file is shown. It is not clear to which file the link was referring to.

### Server configuration
Ubuntu 16.04 64bit

**Web server:**
apache2, v2.4.18-2ubuntu3.1

**Database:**
mariadb 10.0.27-0ubuntu0.16.04.1

**PHP version:**
7.0.8-0ubuntu0.16.04.3

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
https://nextcloud.com/install/

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - direct_menu: 0.9.2
  - disablerememberlogin: 0.3
  - external: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - nextant: 0.6.0
  - notes: 2.0.2
  - notifications: 0.3.0
  - ownnote: 1.08
  - ownpad: 0.5.5
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - richdocuments: 1.1.9
  - serverinfo: 1.1.1
  - spreedme: 0.3.3
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - bookmarks
  - calendar
  - documents
  - encryption
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocjw1pybmsdb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.XXXX.org"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/XXXX\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "it-robot",
        "mail_domain": "XXXX.org",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.XXXX.org",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 50.0, chromium, opera, ...

**Operating system:**
Ubuntu 14.04 64Bit desktop

#### Web server error log
10.11.1.30 - - [22/Nov/2016:10:25:04 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1101 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
10.11.1.30 - test_guate1 [22/Nov/2016:10:25:05 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4275 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
10.11.1.30 - - [22/Nov/2016:10:25:06 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2488 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:08 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2335 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:23 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2488 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:31 +0100] "GET /index.php/apps/activity/api/v2/activity/filter?format=json&object_type=files&object_id=10 HTTP/1.1" 304 530 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:31 +0100] "PROPFIND /remote.php/dav/systemtags-relations/files/10 HTTP/1.1" 207 1670 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:34 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1101 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
10.11.1.30 - test_guate1 [22/Nov/2016:10:25:35 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4275 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
10.11.1.30 - - [22/Nov/2016:10:25:36 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2488 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:38 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2335 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:48 +0100] "GET /index.php/f/10 HTTP/1.1" 303 1007 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:48 +0100] "GET /index.php/apps/files/?dir=/&scrollto=Nextcloud+Manual.pdf HTTP/1.1" 200 6359 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:49 +0100] "GET /index.php/core/js/oc.js?v=6dfe759513658664c3991784311ca65b HTTP/1.1" 200 3874 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:49 +0100] "GET /cron.php HTTP/1.1" 200 854 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:50 +0100] "GET /index.php/apps/ownpad/ajax/getconfig.php HTTP/1.1" 200 1077 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:50 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2488 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:50 +0100] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 917 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:50 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 8585 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:50 +0100] "GET /index.php/apps/richdocuments/ajax/settings.php HTTP/1.1" 200 1093 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:50 +0100] "GET /index.php/apps/richdocuments/ajax/mimes.php HTTP/1.1" 200 845 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:25:50 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1026 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:26:04 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1101 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
10.11.1.30 - test_guate1 [22/Nov/2016:10:26:05 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4275 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
10.11.1.30 - - [22/Nov/2016:10:26:06 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2488 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
10.11.1.30 - - [22/Nov/2016:10:26:08 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 2335 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"

#### Nextcloud log (data/nextcloud.log)
(I don't think releated, also timestamp not matching) ....
{"reqId":"s69iO344aZn8nebpgcvg","remoteAddr":"10.11.1.30","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T09:19:39+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"iamdpn"}
....
#### Browser log
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
window.controllers is deprecated. Do not use it for UA detection.

**Comment by nickvergessen** [comment] 2016-11-22 15:36
There is a `scrollto=` parameter which should scroll the view to that file and highlight it. Not sure why that is not happening anymore.

**Comment by chaos-prevails** [comment] 2016-11-23 11:28
Hi nickvergessen,
thanks for the update.
Would it not be handier if the permalink directly opens the file? This would make it easier to combine NC with other platforms (e.g. a forum or project management platform where you refer to a file residing on NC). With the scrollto parameter, one would have to click another time to open the file.

thanks!

**Comment by nickvergessen** [comment] 2016-11-23 11:32
Well in the future we want to show the sidebar as well on scrollto, but directly starting a download? that is not what we aim for with these links.

**Comment by chaos-prevails** [comment] 2016-11-23 11:35
ok, thanks for letting me know. 

The sidebar would already be great as users the file more clearly.

**Comment by chaos-prevails** [comment] 2017-01-16 09:46
this is still an issue in NC11. Now opening the local link scrolls to the file if the file list is long enough. However, it only scrolls until the requested file is the 3rd from the top (AFAIK) (which is very confusing if a lot of files are named similarly, e.g. pictures from a digital camera).

The requested file is not highlighted nor is the sidebar shown. Highlighting would be great, so one immediately knows which file is meant. An opened sidebar would be even more clear and saves two clicks when making a comment.

**Comment by MorrisJobke** [comment] 2017-05-09 02:02
Duplicate of #1467

**Closed by MorrisJobke** 2017-05-09 02:02 UTC
Labels: bug, design, feature: files
