### ISSUE TITLE
No app icons overlay when custom color

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#18693] opened 2020-01-06 14:02 UTC
- enable theming app
- change color
--> do not see any app icons overlay

- disable theming app
--> see app icons overlay

Talked with @jancborchardt and it should show app icons

**Comment by rullzer** [comment] 2020-01-06 15:06
Can you post screenshots?

**Comment by rullzer** [comment] 2020-01-06 15:06
Also @juliushaertl

**Comment by tobiasKaminsky** [comment] 2020-01-06 15:56
Theming app enabled:
![image](https://user-images.githubusercontent.com/5836855/71829606-4abf2780-30a5-11ea-85e9-cd9ea07c2c95.png)

Settings:
![image](https://user-images.githubusercontent.com/5836855/71829695-7e01b680-30a5-11ea-9460-d61429d452c8.png)


Theming app disabled:
![image](https://user-images.githubusercontent.com/5836855/71829637-61657e80-30a5-11ea-8631-a9246bfab3bc.png)

**Comment by jancborchardt** [comment] 2020-01-08 13:48
From the screenshot it does seem like you set a login image? Click the "reset" circular arrow in that row, then it probably works. :)

**Comment by tobiasKaminsky** [comment] 2020-01-09 08:15
When reverting everything to default, I indeed see app icons with default blue.
As soon as I switch to a different color, the app icons vanish, though the gradient remains.

**Comment by juliushaertl** [comment] 2020-01-09 13:24
Known issue from the introducing PR https://github.com/nextcloud/server/pull/18082#issuecomment-558193138

**Comment by blizzz** [comment] 2021-11-10 13:56
clearing the milestone.

> Known issue from the introducing PR [#18082 (comment)](https://github.com/nextcloud/server/pull/18082#issuecomment-558193138)

Reading it, this is intended behaviour. Closing therefore, but feel free to reopen if you disagree.

**Closed by blizzz** 2021-11-10 13:56 UTC
Labels: bug, 1. to develop, feature: theming
