### ISSUE TITLE
Dark theme  - Icons poorly visible

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#14473] opened 2019-03-02 16:08 UTC
If you click on more... the icons should be grey...

![image](https://user-images.githubusercontent.com/16019165/53684431-99759580-3d0d-11e9-840e-9c0b701e0cf4.png)

should look like this:

![image](https://user-images.githubusercontent.com/16019165/53684457-e78a9900-3d0d-11e9-9cd7-4352f38e1c9d.png)

**Comment by violoncelloCH** [comment] 2019-03-06 16:21
can't reproduce this with master on firefox 65
![image](https://user-images.githubusercontent.com/22591354/53896397-3e58e100-4034-11e9-972b-14ad4263629c.png)

**Comment by BornToBeRoot** [comment] 2019-03-06 19:13
So it is fixed in the current master / nextcloud 16 ? 

I tried with Chrome and Firefox on Desktop and with Chrome on Mobile. 

Using Nextcloud 15.0.5

**Comment by violoncelloCH** [comment] 2019-03-07 08:57
yes, seems to be fixed in 16 (maybe also 15.0.6)

**Comment by sunjam** [comment] 2019-05-26 22:10
I'm also having issues as of 16.0.1.  Using a grey color, your theme seems to confuse Nextcloud on whether to black or white icons.  The exact shade of grey will come out better or worse.

**Comment by BornToBeRoot** [comment] 2019-05-26 23:00
For me, this issue was fixed with the upgrade to 16.0.1

![image](https://user-images.githubusercontent.com/16019165/58388126-d0acc780-801a-11e9-859c-a3ad9ce18f51.png)

**Comment by violoncelloCH** [comment] 2019-06-03 13:39
@sunjam I guess you're talking about the icons in the topbar and not the ones below "more", right? so that's something different for the theming app if you use grey as a primary / theming color...
this issue here seems to be fixed

**Closed by violoncelloCH** 2019-06-03 13:39 UTC
Labels: 0. Needs triage, bug
