### ISSUE TITLE
can not copy or move directory between different external file storage, but files work fine

### ISSUE THREAD

**Issue by tuxcrafter** [nextcloud/server#14743] opened 2019-03-18 23:21 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

I can not copy or move directory between different external file storage, but normal files work fine. How can I get this working?

`The first argument to copy() function cannot be a directory at
`
```
{"reqId":"XJAjnlYH6@rVQbcVclaXfwAAAAg","level":3,"time":"2019-03-18T23:02:54+00:00","remoteAddr":"80.127.158.83","user":"jdejong","app":"PHP","method":"MOVE","url":"\/nextcloud\/remote.php\/dav\/files\/jdejong\/Communications\/communication-jdejong","message":"rename(): The first argument to copy() function cannot be a directory at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
{"reqId":"XJAjnlYH6@rVQbcVclaXfwAAAAg","level":3,"time":"2019-03-18T23:02:54+00:00","remoteAddr":"80.127.158.83","user":"jdejong","app":"PHP","method":"MOVE","url":"\/nextcloud\/remote.php\/dav\/files\/jdejong\/Communications\/communication-jdejong","message":"rename(\/\/mnt\/nfs\/communications\/communication-jdejong,\/\/mnt\/nfs\/programmes\/communication-jdejong): Invalid cross-device link at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
```

Moving a normal file works but still gives this message:

`{"reqId":"XJAmBLAHf2Bocyt--HDF@gAAAAA","level":3,"time":"2019-03-18T23:13:08+00:00","remoteAddr":"80.127.158.83","user":"jdejong","app":"PHP","method":"MOVE","url":"\/nextcloud\/remote.php\/dav\/files\/jdejong\/Communications\/communication-jdejong\/communicaton-jdejong.txt","message":"rename(\/\/mnt\/nfs\/communications\/communication-jdejong\/communicaton-jdejong.txt,\/\/mnt\/nfs\/programmes\/communicaton-jdejong.txt): Operation not permitted at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.4.0"}
`

The setup:
```
sudo -u apache php occ group:add communications
sudo -u apache php occ group:add generalinformation
sudo -u apache php occ group:add officemanagement
sudo -u apache php occ group:add programmes
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/communications "Communications" local null::null
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/generalinformation "General Information" local null::null
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/officemanagement "Office Management" local null::null
sudo -u apache php occ files_external:create -c datadir=/mnt/nfs/programmes "Programmes" local null::null
sudo -u apache php occ files_external:applicable --add-group communications 11
sudo -u apache php occ files_external:option 11 enable_sharing true
sudo -u apache php occ files_external:option 11 encrypt false
sudo -u apache php occ files_external:applicable --add-group generalinformation 14
sudo -u apache php occ files_external:option 14 enable_sharing true
sudo -u apache php occ files_external:option 14 encrypt false
sudo -u apache php occ files_external:applicable --add-group officemanagement 15
sudo -u apache php occ files_external:option 15 enable_sharing true
sudo -u apache php occ files_external:option 15 encrypt false
sudo -u apache php occ files_external:applicable --add-group programmes 16
sudo -u apache php occ files_external:option 16 enable_sharing true
sudo -u apache php occ files_external:option 16 encrypt false
```

```
# sudo -u apache php occ --version
Nextcloud 15.0.4
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```

**Comment by danaivehr** [comment] 2019-07-07 07:52
Hi! The same issue here. 
Nextcloud 16.0.2 in docker
FIles are movable between External storage and data directory, while folders are not, with the same messages in nextcloud.log

I can provide additional info, but don't to, which.

**Comment by danaivehr** [comment] 2019-07-07 08:13
Perhaps the 'Invalid cross-device link' is the main clue in error message. I have external storage pointing to local directory, which is binded from another /dev/

**Comment by kesselb** [comment] 2019-07-07 09:15
@danaivehr would you mind to share the stacktrace (the log message) from 16.0.2? That makes it easier to locate the error.

**Comment by kesselb** [comment] 2019-07-07 10:05
https://github.com/nextcloud/server/blob/81339c7e23672b7d87e1c6dbaaf586153b260f03/lib/private/Files/Storage/Local.php#L259-L270

There is code to handle this case. Not sure why you reach line 272. Looks like the is_dir does not return true. Could you add before `if ($this->is_dir($path1)) {` and check the logs?

`\OCP\Util::writeLog('core', 'trying to rename: ' . $path1 . ' is_dir: ' . $this->is_dir($path1), ILogger::WARN);`

**Comment by pteriss** [comment] 2020-06-14 20:01
I also experience this same issue.

**Comment by Zegorax** [comment] 2020-08-04 08:29
Same problem here.

**Comment by alderson59** [comment] 2020-09-16 18:44
Same problem. Am using a bind mount on some directories within Nextcloud files and outside.

**Comment by jmlgo** [comment] 2020-10-31 19:40
Same issue here with Nextcloud 20

**Comment by scristall** [comment] 2020-12-14 17:39
Have this issue on Nextcloud 19.0.6 as well.

**Comment by madpipeline** [comment] 2021-01-04 11:37
Detected this issue in `20.0.4` as well, with a local external storage.

**Comment by raleonardo** [comment] 2021-03-07 20:11
Still the same issue in 21.0.0 ( on docker nextcloud:21)

Happens while moving a directory from external storage to my user storage.

When trying to delete the directory from external storage, I get a popup: ' Error deleting file "<folder_name>" '

**Comment by Xalaxis** [comment] 2021-04-17 15:28
I believe this issue causes permanent file deletion in current Nextcloud versions. Attempts to move files to the recycle bin are regarded as a success even though they fail. Without backups _you will lose data_. I ran into this issue attempting to move a directory from a VirtualFiles backed local folder.

![image](https://user-images.githubusercontent.com/12937964/115118144-d65a8000-9f99-11eb-8efa-288fce104f05.png)

**Comment by szaimen** [comment] 2021-07-02 14:37
Seems like is_dir doesn't return true in all cases
e.g. https://www.php.net/manual/de/function.is-dir.php#98338
Does the mentioned workaround help?

**Comment by tuxcrafter** [comment] 2021-08-15 18:15
Please reopen this ticket!

**Comment by raleonardo** [comment] 2021-08-16 08:08
I agree. The issue still exists in 22.1.0

**Comment by NobeKanai** [comment] 2021-09-08 09:49
Same problem. Any solution here?

**Comment by eleminer** [comment] 2021-12-13 12:00
Same here?

**Comment by 63OR63** [comment] 2021-12-19 11:02
The ability to move folders to external folders is crucial, especially considering you can't upload to external storage from official Windows Nextcloud app. The only way to do so currently is through web interface, which isn't optimal in many use cases to say the least.

**Comment by eleminer** [comment] 2021-12-19 14:42
oh, thats bad :/

**Comment by enchained** [comment] 2022-01-27 18:27
Can confirm the issue on 23.0.0. Removing a folder from external storage (local type) gives those errors:
```
Error | PHP | Error: rename(): The first argument to copy() function cannot be a directory at /config/www/nextcloud/lib/private/Files/Storage/Local.php#347
Error | PHP | Error: rename(//ext-data/pathTo/myFolderName,//data/myUser/files_trashbin/files/myFolderName.d1643307398): Cross-device link at /config/www/nextcloud/lib/private/Files/Storage/Local.php#347
```
And leads to permanent removal instead of moving to the trashbin.

**Comment by bendev25689** [comment] 2023-04-11 02:51
Any progress on this issue? I am still having the same issue on nextcloud 26

**Comment by sjash** [comment] 2023-05-12 06:43
> Can confirm the issue on 23.0.0. Removing a folder from external storage (local type) gives those errors:
> 
> ```
> Error | PHP | Error: rename(): The first argument to copy() function cannot be a directory at /config/www/nextcloud/lib/private/Files/Storage/Local.php#347
> Error | PHP | Error: rename(//ext-data/pathTo/myFolderName,//data/myUser/files_trashbin/files/myFolderName.d1643307398): Cross-device link at /config/www/nextcloud/lib/private/Files/Storage/Local.php#347
> ```
> 
> And leads to permanent removal instead of moving to the trashbin.

I'm too facing the same issue on Nextcloud 25.0.6. Any leads will be helpfull

**Comment by kesselb** [comment] 2023-06-02 16:41
@joshtrichards https://github.com/nextcloud/server/pull/19289

**Comment by proofrock** [comment] 2023-06-02 19:13
> weird local underlying filesystem

You bet! I had this issue with the following setup:

- docker image of nextcloud (from linuxservers)
- data dir mounted as a volume
- PUID/PGID set to 1000 (my local user)
- in the volume, the `_data` subdir (the one docker actually uses) has ownership to 1000/1000
- now the tricky part: the `files/` subdir of my nextcloud user subtree is a docker mount to a directory in my home dir

So, I had a docker `-v nextcloud_data:/data` with the volume, and `-v /home/mano/myfiles:/data/mano/files` for the files inside it.

It works, sort of, the only problem is the one described in OP. Keeping everything in the docker volume, removing the second `-v` makes this issue disappear.

Hope this is useful. I can setup a VPS with a reproduction of the problem, if useful, and give you access.

**Comment by bendev25689** [comment] 2023-06-03 11:10
The issue in my case is using the official docker image nextcloud:latest, currently 26.0.2.  
  
The external storage directory (Shared) is mounted to the docker container as /mnt/Shared. File system is zfs.
The data directory is also mounted to the docker container, as /mnt/data.

The Shared directory is and its contents is owned by www-data, which is uid 33 both inside and outside the container.  
  
I am receiving an error when moving a directory, however copying a directory works fine, as does moving files to and from the external storage.
The error in the log is:
```
{"reqId":"clc1937gUFOup8fkbkEb","level":3,"time":"2023-06-03T11:02:53+00:00","remoteAddr":"120.xx.xxx.xx","user":"Benjamin","app":"PHP","method":"MOVE","url":"/cloud/remote.php/dav/files/Benjamin/test_folder_for_move","message":"rename(): The first argument to copy() function cannot be a directory at /var/www/html/lib/private/Files/Storage/Local.php#378","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0","version":"26.0.2.1","data":{"app":"PHP"}}
{"reqId":"clc1937gUFOup8fkbkEb","level":3,"time":"2023-06-03T11:02:53+00:00","remoteAddr":"120.xx.xxx.xx","user":"Benjamin","app":"PHP","method":"MOVE","url":"/cloud/remote.php/dav/files/Benjamin/test_folder_for_move","message":"rename(//mnt/data/Benjamin/files/test_folder_for_move,//mnt/Shared/Documents/test_folder_for_move): Success at /var/www/html/lib/private/Files/Storage/Local.php#378","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0","version":"26.0.2.1","data":{"app":"PHP"}}
```

**Comment by solracsf** [comment] 2023-06-05 13:13
Feel free to try https://github.com/nextcloud/server/pull/38623

**Closed** 2023-07-31 19:04 UTC
Labels: bug, 1. to develop, feature: filesystem, feature: external storage, 25-feedback
