### ISSUE TITLE
"Signature data not found" for official app "theming" (1.4.2) after upgrade 12 -> 13.0.2

### ISSUE THREAD

**Issue by railfox** [nextcloud/server#9571] opened 2018-05-23 21:25 UTC
### Steps to reproduce
1. Upgrade NC 12 --> 13.0.02 (manual download; replace /var/www directory;
   restore config, run "occ upgrade")
2. Open NC's admin gui --> Administration --> integrity / signature checks fails 
for app theming "Signature data not found."

### Expected behaviour
Integrity check for theming should pass

### Actual behaviour
Integrity check for theming fails with "Signature data not found" due to 
non-existing signature.json in $NC_HOME/apps/theming/appdata/.

signature.json exists in downloaded package "nextcloud-13.0.2.zip" but these
package seems to shipped with theming 1.4.1 hence during NC upgrade, theming
app is upgrade to 1.4.2 - but without new (or any) signature.json.

### Server configuration

**Operating system**: Debian 9

**Web server:** Lighttpd

**Database:** Maria DB 15.1

**PHP version:** 7.0

**Nextcloud version:** 13.0.02

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from NC 12

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- theming
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [theming] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - federation
  - files_external
  - files_videoplayer
  - theming
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "loglevel": "2",
        "cron_log": true,
        "log_rotate_size": "104857600",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": false,
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** no external storag

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

**Comment by MorrisJobke** [comment] 2018-05-23 22:10
Duplicate of #9568

**Closed by MorrisJobke** 2018-05-23 22:10 UTC
