### ISSUE TITLE
Convert database to mysql fails - nc11, fresh install

### ISSUE THREAD

**Issue by Oclair** [nextcloud/server#2893] opened 2016-12-30 12:26 UTC
### Steps to reproduce
1. Follow install and normal config for default database install, user www owner of nextcloud directory, admin & normal users created
2. running in nextcloud directory with proper mysql credentials (xxx) 
# sudo -u www php occ db:convert-type --password="XXX" --all-apps mysql xxx localhost xxx

### Expected behaviour
The user should be asked a yes or no question to finalize conversion to mysql and write to config.php 

### Actual behaviour
1. The database seems to be correctly setup on mysql
2. the following error and stop is returned
PHP Fatal error: Allowed memory size of 2634022912 bytes exhausted (tried to allocate 72 bytes) in /xxx/xxx/xxx/xxx/3rdparty/symfony/console/Application.php on line 1073

### Server configuration
**Operating system**:  FreeBSD 11.0-RELEASE-p6 #0 r310492: Sat Dec 24 09:03:31 CET 2016     xxx@xxx.xxxx.xxx:/usr/obj/usr/src/sys/GENERIC  amd64

**Web server:**
Server version: Apache/2.4.25 (FreeBSD)

**Database:**
sqlite3 3.15.1 Size: 58.3 MB
MYSQL: 5.7.15-log Source distribution

**PHP version:**
PHP 5.6.29 (cli) (built: Dec 22 2016 07:27:19) 
Memory Limit: 3512.0 MB (normally set to 512 MB)
Max Execution Time: 3600
Upload max size: 511.0 MB

**Nextcloud version:** (see Nextcloud admin page)
11.0.0 (stable)
Users: 2
Files: 694

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com source

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.4.0
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - encryption: 1.4.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - gpxedit: 0.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.24
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - spreedme: 0.3.5
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - files_automatedtagging
  - files_retention
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocha0opv8gho",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.aventia.pw"
        ],
        "datadirectory": "\/usr\/local\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/xxx.xxx.xxx\/xxx",
        "dbtype": "sqlite3",
        "version": "11.0.0.10",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.          
                                                              
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Console
<details>
<summary>raw returned data</summary>

Creating schema in new database    oc_accounts     3/3 [============================] 100%oc_activity    chunked query, 4 chunks     3210/3210 [============================] 100%oc_activity_mq        0 [&gt;---------------------------]oc_addressbookchanges    chunked query, 3 chunks     2310/2310 [============================] 100%oc_addressbooks     3/3 [============================] 100%oc_admin_sections     8/8 [============================] 100%oc_admin_settings     16/16 [============================] 100%oc_announcements        0 [&gt;---------------------------]oc_announcements_groups        0 [&gt;---------------------------]oc_appconfig     176/176 [============================] 100%oc_audioplayer_album_artists        0 [&gt;---------------------------]oc_audioplayer_albums        0 [&gt;---------------------------]oc_audioplayer_artists        0 [&gt;---------------------------]oc_audioplayer_genre        0 [&gt;---------------------------]oc_audioplayer_playlist_tracks        0 [&gt;---------------------------]oc_audioplayer_playlists        0 [&gt;---------------------------]oc_audioplayer_tracks        0 [&gt;---------------------------]oc_authtoken     6/6 [============================] 100%oc_bookmarks     12/12 [============================] 100%oc_bookmarks_tags     38/38 [============================] 100%oc_bruteforce_attempts        0 [&gt;---------------------------]oc_calendarchanges    chunked query, 3 chunks     2583/2583 [============================] 100%oc_calendarobjects    chunked query, 3 chunks     2568/2568 [============================] 100%oc_calendars     4/4 [============================] 100%oc_calendarsubscriptions        0 [&gt;---------------------------]oc_cards    chunked query, 3 chunks     2269/2269 [============================] 100%oc_cards_properties    chunked query, 10 chunks     9670/9670 [============================] 100%oc_comments        0 [&gt;---------------------------]oc_comments_read_markers        0 [&gt;---------------------------]oc_credentials     2/2 [============================] 100%oc_dav_shares        0 [&gt;---------------------------]oc_external_applicable        0 [&gt;---------------------------]oc_external_config        0 [&gt;---------------------------]oc_external_mounts        0 [&gt;---------------------------]oc_external_options        0 [&gt;---------------------------]oc_federated_reshares        0 [&gt;---------------------------]oc_file_locks     556/556 [============================] 100%oc_filecache     663/663 [============================] 100%oc_files_trash     2/2 [============================] 100%oc_flow_checks        0 [&gt;---------------------------]oc_flow_operations        0 [&gt;---------------------------]oc_gpxedit_options_values        0 [&gt;---------------------------]oc_gpxedit_tile_servers        0 [&gt;---------------------------]oc_group_admin     2/2 [============================] 100%oc_group_user     3/3 [============================] 100%oc_groups     2/2 [============================] 100%oc_jobs     14/14 [============================] 100%oc_mail_accounts     3/3 [============================] 100%    PHP Fatal error:  Allowed memory size of 2634022912 bytes exhausted (tried to allocate 72 bytes) in /xxx/xxx/xxx/xxx/3rdparty/symfony/console/Application.php on line 1073

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"lEB\/+ZdjZ98E1x0yWOeM","remoteAddr":"88.117.64.60","app":"PHP","message":"file_get_contents(\/proc\/meminfo): failed to open stream: No such file or directory at \/xxx\/xxx\/xxx\/xxx\/apps\/serverinfo\/lib\/SystemStatistics.php#71","level":3,"time":"2016-12-29T12:10:15+00:00","method":"GET","url":"\/xxx\/index.php\/apps\/serverinfo\/update","user":"xxx","version":"11.0.0.10"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment] 2017-01-30 14:17
Are that 2GB of memory? Should be enough.
Can you provide details about your number of users, files and shares?

**Comment by Oclair** [comment] 2017-01-30 14:24
@nickvergessen Hi, only two users (a user and an admin), very little data 694 files, it was a bit more than a fresh install made for evaluation.  Using mysql would be preferable but it seemed a little uncertain on FreeBSD once installed (installed originally via download from nextcloud.com not via FreeBSD ports https://www.freshports.org/www/nextcloud/ ) with default (sqlite3) there may not yet be on FreeBSD a clearly functional way to move it to another backend.

**Comment by MorrisJobke** [comment] 2017-08-31 08:31
Sadly we cannot reproduce this. We improve a bit the memory footprint on version 12. So maybe give this another try. I will close this for now. Sorry for the trouble.

**Closed by MorrisJobke** 2017-08-31 08:31 UTC
Labels: bug, feature: install and update, needs info
