### ISSUE TITLE
Upload progress bar disappears PHP 7.2.3

### ISSUE THREAD

**Issue by rsmvdl** [nextcloud/server#8947] opened 2018-03-22 15:30 UTC
### Steps to reproduce
1. Install current NextCloud (v 13.0.1 Stable/Daily channel)
2. (Use NGINX, PHP7.2.3-1 , MariaDB, Redis, PHP-APCu)
3. Upload a file

### Expected behaviour
Upload bar gets displayed till all files have been uploaded.

### Actual behaviour
The Upload progressbar is only displayd while the first item uploads, not the second, third etc... (Simply disappears)

### Server configuration

**Operating system**: Ubuntu 16.04.4 LTS

**Web server**: nginx version: nginx/1.10.3 (Ubuntu)

**Database**: mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version**: PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1

**Nextcloud version**: 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install: Fresh Install

**Where did you install Nextcloud from**: https://download.nextcloud.com/server/releases/nextcloud-13.0.1.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one**: No

**Are you using encryption**: Yes

**Are you using an external user-backend, if yes which one**: No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser**: FireFox, Chrome, Opera, Safari, Chrome on Android

**Operating system: Windows 10, Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No Specific Log about this issue gets written
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Schmuuu** [comment] 2018-03-22 22:26
Hi, this issue was already described here:
https://github.com/nextcloud/server/issues/8106

**Comment by skjnldsv** [comment] 2018-03-23 07:09
Yep, duplicate of #8106

**Closed by skjnldsv** 2018-03-23 07:09 UTC

**Comment by rsmvdl** [comment] 2018-03-23 08:00
Thanks,

please close
