### ISSUE TITLE
Column Modified in Website past tense

### ISSUE THREAD

**Issue by kaumpail** [nextcloud/server#827] opened 2016-08-10 12:58 UTC
![in_ein_paar_sekunden](https://cloud.githubusercontent.com/assets/20948931/17567278/f866a354-5f3e-11e6-9b06-dadb7d40f507.png)
![in a few seconds](https://cloud.githubusercontent.com/assets/20948931/17567279/f86abee4-5f3e-11e6-9c7f-252c508ee8eb.PNG)

 

### Expected behaviour
After loading up a file, column "Modified" in Browser view should state "some seconds ago" (past tense).

### Actual behaviour
States "in a few seconds" (also in German: "In ein paar Sekunden") (->future).
Also have seen this in someone elses Owncloud installation. 
Or should it be like this?

### Server configuration
**Operating system:** Armbian Ubuntu 16.04

**Web server:** nginx 1.10.0

**Database:** Maria DB

**PHP version:** 7.0

**Nextcloud version:** 9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** Nextcloud website

### Client configuration
**Browser:**
Chrome (/any)

**Operating system:**
Windows 10

**Comment by juliushaertl** [comment] 2016-08-14 07:12
This issue is most likely caused by different time on your server/client. The "some seconds ago" is generated comparing the modification date from the server with the current time of your browser using JavaScript. So if one of those is out of sync, you might get wrong values there.

Synchronizing the clock on both machines should fix this, so I'm closing this issue for now. If it doesn't feel free to reopen again.

**Closed by juliushaertl** 2016-08-14 07:12 UTC

**Comment by kaumpail** [comment] 2016-09-10 05:06
ah ok :) Thank you for your response. Makes sense.
Bur wouldn't it be better to only use server time and not to compare the client time to the server time? Or is this not possible?
