### ISSUE TITLE
Feature Request - Disable/Hide "Stay logged in" checkbox

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#5156] opened 2017-05-29 11:03 UTC
I currently hiding the "Stay logged in" checkbox from my users via the custom css-file.

It' would be great if i could disable/hide the checkbox with the config-file, since i don't want my users to stay logged in (Especially when they log in from outside our network).

Maybe there are other users here, for which that might be useful.

**Comment by GitHubUser4234** [comment] 2017-06-16 08:45
This is a duplicate issue of #1358

**Comment by Wikinaut** [comment] 2017-08-31 10:04
👍

**Comment by MorrisJobke** [comment] 2017-09-06 13:32
Duplicate of #1358

**Closed by MorrisJobke** 2017-09-06 13:32 UTC
Labels: 1. to develop, enhancement, feature: authentication
