### ISSUE TITLE
 Local users can not login if LDAP is unavailable

### ISSUE THREAD

**Issue by top-logic** [nextcloud/server#28779] opened 2021-09-10 05:40 UTC
Because the issue https://github.com/nextcloud/server/issues/26094 has been closed because of "the developer has no idea for a solution"(why do you do that?) I do this report to mention this problem again!

The Solution is just:

1. search for local users first
2. if external user service is unavailaible, ignore it and inform the administrator

**Comment by acsfer** [comment] 2021-09-10 07:25
Please don't open issues "just because".
Closing as duplicate of https://github.com/nextcloud/server/issues/26094 an reopen the original.

**Closed by acsfer** 2021-09-10 07:25 UTC
Labels: bug, 0. Needs triage

**Comment by top-logic** [comment] 2021-09-10 14:15
I won't do 

> Please don't open issues "just because".
> Closing as duplicate of #26094 an reopen the original.

I know that and I won't do that, but I had no choice because I can't reopen the original issue by myself and the comments in this issue where just ignored. You should think about this procedure.
