### ISSUE TITLE
3rd party apps disabled after reboot

### ISSUE THREAD

**Issue by manu-p** [nextcloud/server#22012] opened 2020-07-27 08:42 UTC
Nextcloud version: 18.0.7
Operating system and version: Ubuntu 18.04
Apache or nginx version: nginx 1.14
PHP version: PHP 7.4.7

Two previously enabled 3rd party apps are systematically disabled after reboot: Deck and Link editor

All the other activated apps remain enabled after reboot.

I don’t find any information about these deactivation in the nextcloud log, nor in the nginx logs.

On another instance (apache2 instead of nginx, mysql instead of mariadb), Link editor remains enabled after reboot (Deck not being used here).

Here’s a list of enabled apps:
Enabled:
- accessibility: 1.4.0
- activity: 2.11.0
- admin_audit: 1.8.0
- apporder: 0.10.0
- bookmarks: 3.2.2
- breezedark: 18.0.20
- bruteforcesettings: 1.6.0
- calendar: 2.0.3
- cloud_federation_api: 1.1.0
- comments: 1.8.0
- contacts: 3.3.0
- dav: 1.14.0
- deck: 1.0.4
- external: 3.5.0
- extract: 1.2.4
- federatedfilesharing: 1.8.0
- federation: 1.8.0
- files: 1.13.1
- files_accesscontrol: 1.8.1
- files_external: 1.9.0
- files_linkeditor: 1.1.1
- files_lock: 0.8.2
- files_mindmap: 0.0.22
- files_pdfviewer: 1.7.0
- files_rightclick: 0.15.2
- files_sharing: 1.10.1
- files_trashbin: 1.8.0
- files_versions: 1.11.0
- files_videoplayer: 1.7.0
- firstrunwizard: 2.7.0
- forms: 1.1.1
- groupfolders: 6.0.6
- impersonate: 1.5.2
- issuetemplate: 0.6.0
- login_notes: 0.2.1
- logreader: 2.3.0
- lookup_server_connector: 1.6.0
- nextcloud_announcements: 1.7.0
- notifications: 2.6.0
- oauth2: 1.6.0
- ownpad: 0.6.14
- password_policy: 1.8.0
- passwords: 2020.6.0
- photos: 1.0.0
- polls: 1.4.3
- previewgenerator: 2.3.0
- privacy: 1.2.0
- provisioning_api: 1.8.0
- quickaccesssorting: 1.0.3
- quota_warning: 1.7.0
- recommendations: 0.6.0
- richdocuments: 3.7.3
- serverinfo: 1.8.0
- settings: 1.0.0
- sharebymail: 1.8.0
- spreed: 8.0.9
- support: 1.1.1
- survey_client: 1.6.0
- systemtags: 1.8.0
- tasks: 0.13.1
- theming: 1.9.0
- theming_customcss: 1.6.0
- twofactor_backupcodes: 1.7.0
- updatenotification: 1.8.0
- viewer: 1.2.0
- workflow_pdf_converter: 1.3.2
- workflowengine: 2.0.0

The question is: what can I do to get information about these deactivations at reboot?

**Comment by szaimen** [comment] 2021-06-08 08:49
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-08 08:49 UTC
Labels: 0. Needs triage, bug

**Comment by manu-p** [comment] 2021-06-08 08:55
OK thanks.
As a workaround I added this line in www-data's crontab:
`@reboot /bin/sleep 60 ; /usr/bin/php7.4 /var/www/nextcloud/occ app:enable -q deck files_linkeditor theming_customcss`
