### ISSUE TITLE
Folder tree not recreated when drag & drop a folder in a "File drop (upload only)" share

### ISSUE THREAD

**Issue by GetBoz** [nextcloud/server#4163] opened 2017-03-30 14:14 UTC
### Steps to reproduce
1. Create a "File drop (upload only)" shared folder
2. Open the link of the share
3. Drag and drop a folder which contains multiples folders and files in it (with Firefox 52+)
4. The folder tree is not recreated and all the files contained in the folders are uploded in the root folder of the share.

### Expected behaviour
The folder tree is recreated like when we drag and drop the folder in an "Allow upload and editing" share.

### Actual behaviour
The folder tree is not recreated and all the files are uploded in the root folder of the share.

### Server configuration
**Nextcloud:** 11.0.2

### Client configuration
**Browser:** Firefox 52, Chrome 59 

**Operating system:** Windows 10

**Comment by nickvergessen** [comment] 2017-03-30 21:03
Yeah, Firefox does not support uploading folders...
But yeah, we should show the same error as in the normal UI

**Comment by GetBoz** [comment] 2017-03-31 05:58
Firefox support "folder uploading" since Firefox 52, and it works great with Nextcloud 11.0.2

The issue is only when we upload a folder to a "File drop (upload only)" link : the folder tree is not recreated and all the files are uploaded in the root folder of the share.
I suppose the issue is the same with chrome.

**Comment by GetBoz** [comment] 2017-03-31 06:22
I just tested with Chrome, the issue is the same.

**Comment by individual-it** [comment] 2017-04-03 09:28
Just tried with the current master branch and seems to work fine there

**Comment by nickvergessen** [comment] 2017-04-10 09:04
> Firefox support "folder uploading" since Firefox 52, and it works great with Nextcloud 11.0.2

Nice just tested and it works indeed 👍 

Okay now I see what you mean. And the issue still remains in 12 (master). The problem is, that "file drop" (secure drop) only allows to create files, nothing more. So it also does not allow to create folders, etc. This looks very intentional ...

**Comment by szaimen** [comment] 2021-05-21 12:59
I suppose this issue is still valid? If not, please close this issue!

**Comment by GetBoz** [comment] 2021-05-22 07:47
Yes still valid

**Comment by joshtrichards** [comment] 2024-11-22 19:47
Duplicate of #15921

**Closed by joshtrichards** 2024-11-22 19:47 UTC
Labels: enhancement, 1. to develop, feature: sharing, feature: files
