### ISSUE TITLE
Log in fails on some devices due to User-Agent encoding

### ISSUE THREAD

**Issue by nix1g** [nextcloud/server#30377] opened 2021-12-22 15:51 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Put an ASCII-extended character in a client's User-Agent. For example "Loïc's iPad (...". This is the case on Apple devices whose name have an ASCII-extended character.
2. Try to log in (*via* a browser or the app).
3. The server sends a 500 Internal Error.

### Expected behaviour
The user should be able to log in.

### Actual behaviour
The user gets a 500 Internal Error after submitting its credentials.

### Troubleshooting

The error hinted me at an encoding issue (`\xEF` is the ISO/IEC 8859-1 ASCII-extended encoding of "ï").

I checked the database and table encodings:
```
> SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;
+--------------+--------------------+----------------------------+------------------------+----------+----------------+
| CATALOG_NAME | SCHEMA_NAME        | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH | SCHEMA_COMMENT |
+--------------+--------------------+----------------------------+------------------------+----------+----------------+
| def          | information_schema | utf8                       | utf8_general_ci        | NULL     |                |
| def          | performance_schema | utf8                       | utf8_general_ci        | NULL     |                |
| def          | mysql              | utf8mb4                    | utf8mb4_general_ci     | NULL     |                |
| def          | nextcloud          | utf8mb4                    | utf8mb4_general_ci     | NULL     |                |
+--------------+--------------------+----------------------------+------------------------+----------+----------------+

> SHOW TABLE STATUS;                                                                                
+-----------------------------------+--------+---------+------------+---------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-------------+----------+-----------------------+---------+------------------+-----------+                                      
| Name                              | Engine | Version | Row_format | Rows    | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time | Collation   | Checksum | Create_options        | Comment | Max_index_length | Temporary |                                      
+-----------------------------------+--------+---------+------------+---------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+------------+-------------+----------+-----------------------+---------+------------------+-----------+          
| oc_accounts                       | InnoDB |      10 | Compressed |       7 |           1170 |        8192 |               0 |            0 |         0 |           NULL | 2020-08-04 04:53:38 | NULL                | NULL       | utf8mb4_bin |     NULL | row_format=COMPRESSED |         |                0 | N         |                                      
| oc_accounts_data                  | InnoDB |      10 | Compressed |      12 |            682 |        8192 |               0 |        24576 |         0 |             31 | 2021-05-09 05:59:46 | NULL                | NULL       | utf8mb4_bin |     NULL | row_format=COMPRESSED |         |                0 | N         |                                      
| oc_activity                       | InnoDB |      10 | Compressed |  420067 |            273 |   114835456 |               0 |     42704896 | 225968128 |        1377786 | 2020-08-04 04:53:38 | 2021-12-22 16:38:54 | NULL       | utf8mb4_bin |     NULL | row_format=COMPRESSED |         |                0 | N         |                                      
...
```

I also checked nextcloud's configuration, also set to utf-8. I don't know if I am missing something but I managed to get the issue fixed by hacking the code (I am no PHP developer). What I did is to add a `$userAgent = utf8_encode($userAgent);` whenever HTTP_USER_AGENT was read, that is in these files:

- `core/Controller/AppPasswordController.php`
- `core/Controller/ClientFlowLoginController.php`
- `lib/private/User/Session.php`'

I think the issue might be deeper and solved more elegantly but as I said I am no PHP developer. Also there may be a configuration I am missing, please tell me if this is the case.

### Server configuration

**Operating system:** Debian 11 Bullseye

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.4.25

**Nextcloud version:** 22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** From https://download.nextcloud.com/server/releases as a tarball.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:                                                   
  - accessibility: 1.8.0                                   
  - activity: 2.15.0                                       
  - admin_audit: 1.12.0                                    
  - announcementcenter: 6.1.1                              
  - apporder: 0.13.0                                       
  - bruteforcesettings: 2.3.0                              
  - calendar: 3.0.3                                        
  - checksum: 1.1.3                                        
  - circles: 22.1.1                                        
  - cloud_federation_api: 1.5.0                            
  - comments: 1.12.0                                       
  - contacts: 4.0.7                                        
  - contactsinteraction: 1.3.0                             
  - cospend: 1.4.3                                         
  - dav: 1.19.0                                            
  - event_update_notification: 1.4.0                       
  - federatedfilesharing: 1.12.0                           
  - files: 1.17.0                                          
  - files_downloadactivity: 1.12.0                         
  - files_pdfviewer: 2.3.1                                 
  - files_rightclick: 1.1.0                                
  - files_sharing: 1.14.0                                  
  - files_trackdownloads: 1.11.0                           
  - files_trashbin: 1.12.0                                 
  - files_versions: 1.15.0                                 
  - files_videoplayer: 1.11.0                              
  - firstrunwizard: 2.11.0                                 
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupfolders: 10.0.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - metadata: 0.15.0
  - music: 1.5.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.2.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - phonetrack: 0.6.9
  - photos: 1.4.0
  - previewgenerator: 3.4.1
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - video_converter: 1.0.4
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_media_converter: 1.2.23
  - workflowengine: 2.4.0
Disabled:
  - dashboard
  - documentserver_community
  - duplicatefinder
  - encryption
  - end_to_end_encryption
  - federation
  - files_external
  - onlyoffice
  - richdocuments
  - richdocumentscode
  - spreed
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{                                                          
    "system": {                                            
        "instanceid": "***REMOVED SENSITIVE VALUE***",                                                                 
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                                               
        "secret": "***REMOVED SENSITIVE VALUE***",                                                                     
        "trusted_domains": [                               
            "***REMOVED SENSITIVE VALUE***"                                                                                     
        ],                                                                                                             
        "datadirectory": "***REMOVED SENSITIVE VALUE***",                                                              
        "dbtype": "mysql",                                 
        "version": "22.2.3.0",                                                                                         
        "dbname": "***REMOVED SENSITIVE VALUE***",                                                                     
        "dbhost": "***REMOVED SENSITIVE VALUE***",                                                                     
        "dbport": "",                                      
        "dbtableprefix": "oc_",                            
        "mysql.utf8mb4": true,                                                                                         
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                                                     
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                                                 
        "installed": true,                                 
        "maintenance": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\TIFF"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enable": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "default_phone_region": "FR",
        "versions_retention_obligation": "184, auto"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Operating system:** iOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Dec 13 03:25:20 cloud systemd[1]: Starting The Apache HTTP Server...
Dec 13 03:25:20 cloud systemd[1]: Started The Apache HTTP Server.
Dec 14 00:00:22 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 14 00:00:22 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 15 00:00:22 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 15 00:00:22 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 16 00:00:22 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 16 00:00:22 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 17 00:00:22 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 17 00:00:22 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 18 00:00:32 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 18 00:00:32 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 19 00:00:32 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 19 00:00:32 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 20 00:00:32 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 20 00:00:32 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 21 00:00:32 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 21 00:00:32 cloud systemd[1]: Reloaded The Apache HTTP Server.
Dec 22 00:00:22 cloud systemd[1]: Reloading The Apache HTTP Server.
Dec 22 00:00:22 cloud systemd[1]: Reloaded The Apache HTTP Server.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
  "reqId": "cYUalRA8BcQeuuYVb6K2",
  "level": 3,
  "time": "2021-12-21T13:50:45+00:00",
  "remoteAddr": "192.168.8.254",
  "user": "Loic",
  "app": "index",
  "method": "POST",
  "url": "/login/flow",
  "message": "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xEFc (iO...' for column `nextcloud`.`oc_authtoken`.`name` at row 1",
  "userAgent": "Loïc's iPad (iOS Files)",
  "version": "22.2.3.0",
  "exception": {
    "Exception": "OC\\DB\\Exceptions\\DbalException",
    "Message": "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xEFc (iO...' for column `nextcloud`.`oc_authtoken`.`name` at row 1",
    "Code": 1366,
    "Trace": [
      {
        "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 335,
        "function": "wrap",
        "class": "OC\\DB\\Exceptions\\DbalException",
        "type": "::"
      },
      {
        "file": "/var/www/html/lib/public/AppFramework/Db/QBMapper.php",
        "line": 139,
        "function": "executeStatement",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php",
        "line": 88,
        "function": "insert",
        "class": "OCP\\AppFramework\\Db\\QBMapper",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Authentication/Token/Manager.php",
        "line": 70,
        "function": "generateToken",
        "class": "OC\\Authentication\\Token\\PublicKeyTokenProvider",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/core/Controller/ClientFlowLoginController.php",
        "line": 333,
        "function": "generateToken",
        "class": "OC\\Authentication\\Token\\Manager",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "generateAppPassword",
        "class": "OC\\Core\\Controller\\ClientFlowLoginController",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1006,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/html/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/var/www/html/lib/private/DB/Exceptions/DbalException.php",
    "Line": 71,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
      "Message": "An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xEFc (iO...' for column `nextcloud`.`oc_authtoken`.`name` at row 1",
      "Code": 1366,
      "Trace": [
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1780,
          "function": "convert",
          "class": "Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter",
          "type": "->"
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1719,
          "function": "handleDriverException",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1173,
          "function": "convertExceptionDuringQuery",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/DB/Connection.php",
          "line": 267,
          "function": "executeStatement",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
          "line": 354,
          "function": "executeStatement",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 287,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 333,
          "function": "execute",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/public/AppFramework/Db/QBMapper.php",
          "line": 139,
          "function": "executeStatement",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php",
          "line": 88,
          "function": "insert",
          "class": "OCP\\AppFramework\\Db\\QBMapper",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Authentication/Token/Manager.php",
          "line": 70,
          "function": "generateToken",
          "class": "OC\\Authentication\\Token\\PublicKeyTokenProvider",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/core/Controller/ClientFlowLoginController.php",
          "line": 333,
          "function": "generateToken",
          "class": "OC\\Authentication\\Token\\Manager",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 217,
          "function": "generateAppPassword",
          "class": "OC\\Core\\Controller\\ClientFlowLoginController",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 126,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/App.php",
          "line": 156,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Route/Router.php",
          "line": 302,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::"
        },
        {
          "file": "/var/www/html/lib/base.php",
          "line": 1006,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->"
        },
        {
          "file": "/var/www/html/index.php",
          "line": 36,
          "function": "handleRequest",
          "class": "OC",
          "type": "::"
        }
      ],
      "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php",
      "Line": 114,
      "Previous": {
        "Exception": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
        "Message": "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xEFcf (iO...' for column `nextcloud`.`oc_authtoken`.`name` at row 1",
        "Code": 1366,
        "Trace": [
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
            "line": 94,
            "function": "new",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
            "type": "::"
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1163,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/DB/Connection.php",
            "line": 267,
            "function": "executeStatement",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
            "line": 354,
            "function": "executeStatement",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 287,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 333,
            "function": "execute",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/public/AppFramework/Db/QBMapper.php",
            "line": 139,
            "function": "executeStatement",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php",
            "line": 88,
            "function": "insert",
            "class": "OCP\\AppFramework\\Db\\QBMapper",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/Authentication/Token/Manager.php",
            "line": 70,
            "function": "generateToken",
            "class": "OC\\Authentication\\Token\\PublicKeyTokenProvider",
            "type": "->",
            "args": [
              "*** sensitive parameters replaced ***"
            ]
          },
          {
            "file": "/var/www/html/core/Controller/ClientFlowLoginController.php",
            "line": 333,
            "function": "generateToken",
            "class": "OC\\Authentication\\Token\\Manager",
            "type": "->",
            "args": [
              "*** sensitive parameters replaced ***"
            ]
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 217,
            "function": "generateAppPassword",
            "class": "OC\\Core\\Controller\\ClientFlowLoginController",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 126,
            "function": "executeController",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/App.php",
            "line": 156,
            "function": "dispatch",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/Route/Router.php",
            "line": 302,
            "function": "main",
            "class": "OC\\AppFramework\\App",
            "type": "::"
          },
          {
            "file": "/var/www/html/lib/base.php",
            "line": 1006,
            "function": "match",
            "class": "OC\\Route\\Router",
            "type": "->"
          },
          {
            "file": "/var/www/html/index.php",
            "line": 36,
            "function": "handleRequest",
            "class": "OC",
            "type": "::"
          }
        ],
        "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php",
        "Line": 26,
        "Previous": {
          "Exception": "PDOException",
          "Message": "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xEFc (iO...' for column `nextcloud`.`oc_authtoken`.`name` at row 1",
          "Code": "22007",
          "Trace": [
            {
              "file": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
              "line": 92,
              "function": "execute",
              "class": "PDOStatement",
              "type": "->"
            },
            {
              "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
              "line": 1163,
              "function": "execute",
              "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/DB/Connection.php",
              "line": 267,
              "function": "executeStatement",
              "class": "Doctrine\\DBAL\\Connection",
              "type": "->"
            },
            {
              "file": "/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
              "line": 354,
              "function": "executeStatement",
              "class": "OC\\DB\\Connection",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
              "line": 287,
              "function": "execute",
              "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
              "line": 333,
              "function": "execute",
              "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/public/AppFramework/Db/QBMapper.php",
              "line": 139,
              "function": "executeStatement",
              "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/Authentication/Token/PublicKeyTokenProvider.php",
              "line": 88,
              "function": "insert",
              "class": "OCP\\AppFramework\\Db\\QBMapper",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/Authentication/Token/Manager.php",
              "line": 70,
              "function": "generateToken",
              "class": "OC\\Authentication\\Token\\PublicKeyTokenProvider",
              "type": "->",
              "args": [
                "*** sensitive parameters replaced ***"
              ]
            },
            {
              "file": "/var/www/html/core/Controller/ClientFlowLoginController.php",
              "line": 333,
              "function": "generateToken",
              "class": "OC\\Authentication\\Token\\Manager",
              "type": "->",
              "args": [
                "*** sensitive parameters replaced ***"
              ]
            },
            {
              "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
              "line": 217,
              "function": "generateAppPassword",
              "class": "OC\\Core\\Controller\\ClientFlowLoginController",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
              "line": 126,
              "function": "executeController",
              "class": "OC\\AppFramework\\Http\\Dispatcher",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/AppFramework/App.php",
              "line": 156,
              "function": "dispatch",
              "class": "OC\\AppFramework\\Http\\Dispatcher",
              "type": "->"
            },
            {
              "file": "/var/www/html/lib/private/Route/Router.php",
              "line": 302,
              "function": "main",
              "class": "OC\\AppFramework\\App",
              "type": "::"
            },
            {
              "file": "/var/www/html/lib/base.php",
              "line": 1006,
              "function": "match",
              "class": "OC\\Route\\Router",
              "type": "->"
            },
            {
              "file": "/var/www/html/index.php",
              "line": 36,
              "function": "handleRequest",
              "class": "OC",
              "type": "::"
            }
          ],
          "File": "/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
          "Line": 92
        }
      }
    },
    "CustomMessage": "--"
  },
  "id": "61c342dc3c993"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing available
```
</details>

**Comment by szaimen** [comment] 2021-12-22 15:53
Duplicate of https://github.com/nextcloud/ios/issues/1831

**Comment by nix1g** [comment] 2021-12-22 15:55
Not a duplicate, it also affect browsers. The app is not crashing, the server just sends a 500.

**Comment by szaimen** [comment] 2021-12-22 15:56
so you cannot log in using e.g. Safari?

**Comment by nix1g** [comment] 2021-12-22 15:56
No I cannot

**Comment by nix1g** [comment] 2021-12-22 15:57
Please see the Troubleshooting sections for more information

**Comment by szaimen** [comment] 2023-01-23 12:44
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:47 UTC
Labels: bug, needs info, 0. Needs triage
