### ISSUE TITLE
"Actions" menu overlaps file list in NC15 Files web interface

### ISSUE THREAD

**Issue by inducer** [nextcloud/server#13266] opened 2018-12-26 13:42 UTC
### Steps to reproduce
1. Open the files tab in the web interface of a Nextcloud 15 instance 

### Expected behaviour
The "Actions" menu is usable and does not overlap the file list.

### Actual behaviour
![bildschirmfoto von 2018-12-26 14-32-20](https://user-images.githubusercontent.com/352067/50447597-8b298880-091c-11e9-870d-31a024705551.png)

### Server configuration

**Operating system**: Linux

**Web server:** nginx 1.14.1

**Database:** postgres 11

**PHP version:** 7.3

**Nextcloud version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from (originally) owncloud 6-ish

**Where did you install Nextcloud from:** Source

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
* Contacts	2.1.8	Offiziell	 
* Accessibility	1.1.0	Offiziell	
* Activity	2.8.2	Offiziell	
* Auditing / Logging	1.5.0	Offiziell	
* Calendar	1.6.4	Offiziell	
* Collaborative tags	1.5.0	Offiziell	
* Comments	1.5.0	Offiziell	
* Deleted files	1.5.0	Offiziell	
* Federation	1.5.0	Offiziell	
* File sharing	1.7.0	Offiziell	
* First run wizard	2.4.0	Offiziell	
* Gallery	18.2.0	Offiziell	
* Log Reader	2.0.0	Offiziell	
* Monitoring	1.5.0	Offiziell	
* Nextcloud announcements	1.4.0	Offiziell	
* Notifications	2.3.0	Offiziell	
* Password policy	1.5.0	Offiziell	
* PDF viewer	1.4.0	Offiziell	
* Share by mail	1.5.0	Offiziell	
* Support	1.0.0	Offiziell	
* Text editor	2.7.0	Offiziell	
* Theming	1.6.0	Offiziell	
* Update notification	1.5.0	Offiziell	
* Usage survey	1.3.0	Offiziell	
* Versions	1.8.0	Offiziell	
* Video player	1.4.0	Offiziell	
* Default encryption module	2.3.0	Offiziell	
* External storage support	1.6.0	Offiziell
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "15.0.0.10",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/web\/nextcloud\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/web\/nextcloud\/nextcloud\/apps",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "ssl.tiker.net",
            "ssl.cbigman.net"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "\/nextcloud",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "appstore.experimental.enabled": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/nextcloud",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox 64

**Operating system:** Linux

**Comment by skjnldsv** [comment] 2019-06-04 09:03
As I cannot reproduce the issue, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-04 09:03 UTC
Labels: 0. Needs triage, bug
