### ISSUE TITLE
TypeError: Argument 1 passed to OCA\Files_Trashbin\Controller\PreviewController::getPreview() must be of the type int, null given

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#17115] opened 2019-09-12 19:06 UTC
- NC 16.0.4.1
- PHP 7.3

Each time i permanently delete a file from trash, i get this:

```
[index] Error: TypeError: Argument 1 passed to OCA\Files_Trashbin\Controller\PreviewController::getPreview() must be of the type int, null given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 166 at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\Files_Trashbin\Controller\PreviewController->getPreview(null, 128, 128)
1. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Trashb ... {}, "getPreview")
2. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Trashb ... {}, "getPreview")
3. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Files_Tras ... r", "getPreview", OC\AppFramework\ ... {}, {_route: "files_ ... "})
4. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "files_ ... "})
5. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "files_ ... "})
6. /var/www/html/nextcloud/lib/base.php line 975
   OC\Route\Router->match("/apps/files_trashbin/preview")
7. /var/www/html/nextcloud/index.php line 42
   OC::handleRequest()

GET /apps/files_trashbin/preview?fileId=12102&file=Test.docx%2FTest.docx.d1568315040&c=1568315040
```

**Comment by simonspa** [comment] 2019-12-03 06:19
Same here,

NC 17.0.1
PHP 7.3
nginx 1.14.2

Log:
```
[index] Error: Exception: Argument 1 passed to OCA\Files_Trashbin\Controller\PreviewController::getPreview() must be of the type int, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Trashb ... {}, "getPreview")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Files_Tras ... r", "getPreview", OC\AppFramework\ ... {}, {_route: "files_ ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "files_ ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "files_ ... "})
4. /var/www/nextcloud/lib/base.php line 1000
   OC\Route\Router->match("/apps/files_trashbin/preview")
5. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /apps/files_trashbin/preview?fileId=3388061&file=mydirectory%2F.git%2F.COMMIT_EDITMSG.swp%2F.COMMIT_EDITMSG.swp.d1575301114&c=1575301114
from <ip> by <user> at 2019-12-03T07:14:16+01:00
```

**Comment by kesselb** [comment] 2019-12-08 15:13
I'm not able to reproduce with Nextcloud 18 (git) or Nextcloud 17.0.1 (docker). `fileId` is correctly mapped to the controller :confused:

**Comment by simonspa** [comment] 2019-12-08 18:30
What info can we provide that would be helpful for you, @kesselb ?

**Comment by simonspa** [comment] 2020-01-07 19:45
Hi @kesselb is there any way we can debug this and provide you with more information? I see my log flooded with errors whenever any of my users removes a file from trash.

**Comment by kesselb** [comment] 2020-01-07 22:01
`/apps/files_trashbin/preview?fileId=134&file=DADA%2F4k-wallpaper-architecture-bird-s-eye-view-2246476.jpg%2F4k-wallpaper-architecture-bird-s-eye-view-2246476.jpg.d1578432111&c=1578432111`

URL is a bit wrong. &file and &c are not expected from getPreview endpoint. But I'm not able to trigger your exception with the above url. 

`/apps/files_trashbin/preview` will trigger the exception. That seems to be okay. https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/core/Controller/PreviewController.php#L124

https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/core/Controller/PreviewController.php#L131-L133

However the controller for normal previews (files not in the trash) has a default value and will later return bad request if $fileId = default value.

Should be possible to adopt this for the trash preview controller: 
https://github.com/nextcloud/server/blob/master/apps/files_trashbin/lib/Controller/PreviewController.php#L90

Mind to push a pull request? ;)

**Comment by simonspa** [comment] 2020-01-07 22:32
Great @kesselb I tested your suggested fix and it works perfectly fine. Here is the PR: https://github.com/nextcloud/server/pull/18728

Would still be interesting to understand where the root cause lies... :question:

**Comment by kesselb** [comment] 2020-01-07 22:39
> Would still be interesting to understand where the root cause lies...

So do I ;)

**Comment by szaimen** [comment] 2023-01-09 14:59
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by simonspa** [comment] 2023-01-09 15:01
Not sure why you reopened this @szaimen to be honest - this was fixed in NC18 already... I think we can close it.

**Comment by szaimen** [comment] 2023-01-09 15:03
Okay cool!

**Closed by szaimen** 2023-01-09 15:03 UTC
Labels: bug, good first issue, needs info, 0. Needs triage
