### ISSUE TITLE
Download shared link as ZIP sends file with damaged header

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/server#8798] opened 2018-03-13 09:17 UTC
### Steps to reproduce
1. Create a folder and put some files into it
2. Share this folder as a link to download
3. Open the link in a browser (not macOS) and download the folder as a ZIP archive
4. Extract the archive using 7-Zip and the Explorer context menu to extract files to a new folder

### Expected behaviour
The ZIP archive can be downloaded and extracted on the client.

### Actual behaviour
7-Zip reports an error in the header:

![7-Zip error report](https://user-images.githubusercontent.com/6613614/37332699-b795c7e2-26a7-11e8-8656-9920dd14b5bd.png)

Maybe this is also the reason why ZIP is not used for macOS - not because of a bug in macOS but some problem in the created ZIP file.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 12.0.5

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - apporder: 0.4.1
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - deck: 0.3.1
  - defaultlinkopen: 1.0.0
  - drawio: 0.8.9
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - gpxmotion: 0.0.6
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.3
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - onlyoffice
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.0x0c.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.0x0c.de",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "knowledgebaseenabled": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 58.0.2

**Operating system:** Windows 10 Pro x64

**Comment by MorrisJobke** [comment] 2018-03-13 15:25
cc @danxuliu @rullzer

**Comment by Zefling** [comment] 2018-03-17 23:17
For me, it's always this that works.
`$this->streamerInstance = new ZipStreamer(['zip64' => false]);`
in lib/private/Streamer.php

**Comment by AntoineMazuyer** [comment] 2018-04-15 22:00
Even with this fix on Streamer.php, I still have the problem

**Comment by danxuliu** [comment] 2018-04-16 18:52
This should have been fixed in #7972, which will be included in Nextcloud 14. If you could verify if the issue is fixed for you in current _master_ branch (do not forget to update too the 3rdparty repository) it would be great :-) Thanks!

**Comment by MorrisJobke** [comment] 2018-04-16 22:08
> This should have been fixed in #7972, which will be included in Nextcloud 14. If you could verify if the issue is fixed for you in current master branch (do not forget to update too the 3rdparty repository) it would be great :-) Thanks!

Let's close it then. ;)

**Closed by MorrisJobke** 2018-04-16 22:08 UTC
Labels: 0. Needs triage, bug, feature: files

**Comment by alogoc** [comment] 2019-05-03 16:15
Issue is still there on Nextcloud 15.0.7

**Comment by alogoc** [comment] 2019-05-11 22:10
#15367 @danxuliu

**Comment by mikeschdesign** [comment] 2019-09-02 10:19
Issue is still there on Nextcloud 16.0.4

**Comment by arnowelzel** [comment] 2019-09-02 16:29
@mikeschdesign I can't reproduce this problem in 16.0.4 if the total size of the compressed files is less than 4 GiB (tested with 7-Zip 18.01 x64 in Windows 10 1903). ZipStreamer is now also used without 64 bit mode, if 64 bit is not needed, see lib/private/Streamer.php:

```
		if ($size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {
			$this->streamerInstance = new ZipStreamer(['zip64' => false]);
		} else if ($request->isUserAgent($this->preferTarFor)) {
			$this->streamerInstance = new TarStreamer();
		} else {
			$this->streamerInstance = new ZipStreamer(['zip64' => PHP_INT_SIZE !== 4]);
		}
```

So please check, if this happens always or only for big files. As far I understand the fix, the 64 bit mode is causing problems - so downloading smaller archives which contain less then 4 GiB of uncompressed data should not be a problem any longer.

**Comment by MaievJL** [comment] 2019-11-01 04:45
I just hit this issue as well. The archive is 1GB, selecting a few less files still gave me this error (700MB).

**Comment by AbelLykens** [comment] 2020-04-10 17:37
I am hitting this issue, still, on doxc documents (zip files). Also <1MB. 

What I then do is ssh to my nextcloud, get the file from data dir. Not ideal.

**Comment by arnowelzel** [comment] 2020-04-10 19:29
@AbelLykens For me this works without any problem with Nextcloud 18.0.3 and 7-Zip 19.00. And it makes no differnce if you download multiple docx files or some other file type since the result is always a ZIP file.

**Comment by AbelLykens** [comment] 2020-04-10 19:30
Sorry for bumping this thread. 

It appears it is an apache problem.
