### ISSUE TITLE
Filename with Accents break webdav result in empty file

### ISSUE THREAD

**Issue by pomporov** [nextcloud/server#14079] opened 2019-02-07 10:40 UTC
### Steps to reproduce
1. Upload a file name "fichier à toto.doc" via WebDav

### Expected behaviour
File should be there
### Actual behaviour
File uploaded with Zero size

### Server configuration

**Operating system**:
Windows / Osx Webdav clients

**Web server:**

**Nextcloud version:** Nexcloud 15.0.2 

*

**Comment by horstvogel** [comment] 2019-02-07 18:40
The same Problem, but only with active Clam AV
https://github.com/nextcloud/server/issues/13724

**Comment by danielkesselberg** [comment] 2019-02-07 19:02
Does this patch solve your problem? https://github.com/nextcloud/server/pull/13829

**Comment by skjnldsv** [comment] 2019-04-30 10:33
Cannot reproduce.
![Capture d’écran_2019-04-30_12-33-13](https://user-images.githubusercontent.com/14975046/56956338-28533280-6b44-11e9-8a30-953ab35ff9df.png)

@pomporov do you have external storage? S3? Mounts?

**Comment by skjnldsv** [comment] 2020-11-08 10:32
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-11-08 10:32 UTC
Labels: 0. Needs triage, bug
