### ISSUE TITLE
[Bug]: Database error on Update

### ISSUE THREAD

**Issue by Erebus999** [nextcloud/server#42181] opened 2023-12-12 20:29 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Das Datenbankschema wird aktualisiert

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "configkey" for table "oc_preferences" collides with the constraint on table "oc_appconfig".

### Steps to reproduce

1. Update Database on Upate to V28
2.
3.

### Expected behavior

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "configkey" for table "oc_preferences" collides with the constraint on table "oc_appconfig".

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment] 2023-12-12 20:40
Is this really MySQL or Postgres?

**Comment by Erebus999** [comment] 2023-12-12 21:40
'dbtype' => 'mysql',

**Comment by joshtrichards** [comment] 2023-12-12 22:01
That migration also doesn't touch that table.

And the only migration that should even be touching the named tables is a completely different one:

https://github.com/nextcloud/server/blob/c734a18ee83a3537193192f6b97d78575611ba9e/core/Migrations/Version13000Date20170718121200.php#L313

See #42173 for something similar with the same migration but also hitting an unrelated table.

Or do I need more coffee? :coffee:

**Comment by joshtrichards** [comment] 2023-12-12 22:13
Duplicate of #41253

**Closed by joshtrichards** 2023-12-12 22:13 UTC
Labels: bug, 0. Needs triage, feature: install and update, 28-feedback

**Comment by Erebus999** [comment] 2023-12-12 23:45
Could someone help me?
I'm not very good with SQL.
I am admin in myphp and enter the SQL command:
drop index "configkey" from "oc_appconfig"
And I just get an SQL syntax error.
