### ISSUE TITLE
BUG: File/Folder Share Icon not updating in real time when shared, must refresh for it to appear

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/server#28405] opened 2021-08-12 18:06 UTC
When you click share 

![image](https://user-images.githubusercontent.com/1812594/129262223-fcb6dc13-bddf-4c3e-9940-b5a83025c158.png)

then hit share link the share indicator under files does not update in real time. 

![image](https://user-images.githubusercontent.com/1812594/129262346-77626b3c-4e86-4301-8ee1-d45a5f7d0188.png)

But Once you refresh the page in the browser it updates.

![image](https://user-images.githubusercontent.com/1812594/129262495-20075f2e-f6ea-4b02-94e9-a2a67f7b3809.png)

![image](https://user-images.githubusercontent.com/1812594/129262626-949038ca-036c-4317-9b5b-ef221b18deb3.png)

![image](https://user-images.githubusercontent.com/1812594/129262643-6a42f91e-f287-4b18-982e-54f6d0cf2c13.png)

This also happens when you unshare.

I installed many versions of Nextcloud recently to see where the regression happened it looks like the last version that actually worked was Nextcloud 17.

**Comment by szaimen** [comment] 2021-09-15 14:46
duplicate of https://github.com/nextcloud/server/issues/26969

**Closed by szaimen** 2021-09-15 14:46 UTC
Labels: bug, 0. Needs triage
