### ISSUE TITLE
Package Information on login page?

### ISSUE THREAD

**Issue by odo2063** [nextcloud/server#17983] opened 2019-11-18 13:50 UTC
Hi!

This more a Question...

Is it wanted that NC shares information about installed Packages on loginpage?

```
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/js/dist/main.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/js/core/merged-template-prepend.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/search/js/search.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/l10n/de_DE.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/js/dist/share_backend.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/dicomviewer/l10n/de_DE.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/dicomviewer/js/app.bundle.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/three.min.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/controls/OrbitControls.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/libs/inflate.min.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/loaders/LoaderSupport.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/loaders/ColladaLoader.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/loaders/FBXLoader.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/loaders/GLTFLoader.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/loaders/OBJLoader2.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/vendor/loaders/MTLLoader.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_3d/js/loader.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_pdfviewer/js/previewplugin.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/files_videoplayer/js/main.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/apps/gallery/l10n/de_DE.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/search/js/searchprovider.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/js/files/fileinfo.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/js/files/client.js?v=ec5db4b3-11"></script>
<script nonce="THBRNHMyVFlWZjIrRW1DZEdROVF6M29MdU5MdVhSUmVkZVEyY1UyYnl4WT06SGQxdHhBbUtJWlBzUUUvOFhYNW1naFU3N09HN09Wa2RMWkJkRXliMHV6MD0=" defer src="/core/js/dist/login.js?v=ec5db4b3-11"></script>
```

**Comment by szaimen** [comment] 2021-05-27 11:15
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 11:15 UTC
Labels: 0. Needs triage, enhancement
