### ISSUE TITLE
"More apps" out of window

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#10779] opened 2018-08-21 12:57 UTC
After clicking on "more apps", I get a wrong positioned dialog:
![image](https://user-images.githubusercontent.com/5836855/44402478-30d58100-a552-11e8-8450-6243bb35d383.png)

It as happening for me after NC14 upgrade, on Chromium and Firefox on my private and company instance.

**Comment by tobiasKaminsky** [comment] 2018-08-21 12:57
@skjnldsv maybe? :-D

**Comment by skjnldsv** [comment] 2018-08-21 16:11
Duplicate of https://github.com/nextcloud/server/issues/10716

**Closed by skjnldsv** 2018-08-21 16:11 UTC
Labels: 14-beta-feedback, bug, design
