### ISSUE TITLE
Quota: 0/0MB invalid NC12

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#5078] opened 2017-05-23 16:17 UTC
For quite some time it's been possible to set a user quota to 0 in order to prevent uploads, as of 12 this is no longer possible. 

I understand there were issues around the ability to still _do stuff_ (https://github.com/nextcloud/server/issues/4577), however having an account essentially r/o or only able to upload to shared directories was quite useful. 

If this was planned with solutions to both of the above use-cases, feel free to point me to the solutions 👍 

Cheers!

**Comment by enoch85** [comment] 2017-06-21 16:10
This is a bug, I can confirm. Please have a look @icewind1991 

cc @MorrisJobke

**Comment by MorrisJobke** [comment] 2017-06-21 16:58
cc @icewind1991 @nickvergessen @LukasReschke

**Comment by MorrisJobke** [comment] 2017-06-21 16:59
@oparoz because this is one major use case in the recent project

**Comment by enoch85** [comment] 2017-06-21 17:21
@MorrisJobke Thanks for the milestone! Great that this will be fixed in the next release. :+1:

**Comment by MorrisJobke** [comment] 2017-06-21 17:25
> @MorrisJobke Thanks for the milestone! Great that this will be fixed in the next release. 👍

We don't have a fix for this yet. It is planned to be fixed there, but I can't give promises.

**Comment by enoch85** [comment] 2017-06-22 14:57
@MorrisJobke Is it a big change? Maybe I can help if you point me in the right direction?

**Comment by bpcurse** [comment] 2017-06-30 22:32
We have the same problem, as r/o users (referring to personal files) cannot be created any more. This feature is important for us, too. I hope it can be easily fixed without a major code edit.

**Comment by TomFernandes** [comment] 2017-07-15 06:19
Same here. We are also in the need of read-only users. This also implies preventing a user to create folders as described in #4577.

**Comment by MorrisJobke** [comment] 2018-01-10 19:54
I tested this on 12.0.4 and the upcoming 13.0.0 and it works there. Let's close it here and check if it happens again.

**Closed by MorrisJobke** 2018-01-10 19:54 UTC
Labels: bug, feature: filesystem, high
