### ISSUE TITLE
Possibility to delete file versions manually

### ISSUE THREAD

**Issue by Ninos** [nextcloud/server#7285] opened 2017-11-25 09:20 UTC
Hey there,
I'm missing the possibility to delete file versions manually via gui or/and by command:
`php occ files_versions:cleanup`

I could not find a way to delete file versions manually.

**Comment by MorrisJobke** [comment] 2017-11-27 07:07
cc @schiessle @nickvergessen

**Comment by MorrisJobke** [comment] 2018-05-31 14:47
Duplicate of #7687

**Closed by MorrisJobke** 2018-05-31 14:47 UTC
Labels: enhancement, feature: versions
