### ISSUE TITLE
An admin role needed somewhere inbetween the super admin and group admin

### ISSUE THREAD

**Issue by PhilippaKH** [nextcloud/server#13026] opened 2018-12-12 10:13 UTC
Needing an admin role which fits between superadmin and group admin.

They should be able to add users, shares AND groups. Should not have access to apps and system configuration. 

Essentially all the permissions of a group admin + the ability to create groups. 

Thanks!

**Comment by GuiGuiSoft** [comment] 2018-12-20 11:38
Hello,

I totally agree this feature idea, it could be very usefull for important organisations 👍 
Moreover group admin can not see all users to add user to their own group (at least, this is what I see on NextCloud demo available at demo.nextcloud.com/... ). _Is it a bug by the way ?_ 🤔 

Regards.

**Comment by skjnldsv** [comment] 2019-04-30 08:55
Duplicate of #7482

**Closed by skjnldsv** 2019-04-30 08:55 UTC
Labels: 0. Needs triage, enhancement
