### ISSUE TITLE
Client stops syncing due to server error

### ISSUE THREAD

**Issue by ebogaard** [nextcloud/server#3406] opened 2017-02-08 10:10 UTC
### Steps to reproduce
1. Add files to Nextcloud
2. Use Desktop (Mac) client to sync these to local drive. Sometimes this fails, sometimes it doesn't.
3. Syncing of all files stops from now on.

### Expected behaviour
Syncing of the files using the Mac Client should always complete.
Even when an error is encountered, the client should continue syncing the other files.

### Actual behaviour
The client stops syncing when encountering the described error(s).
The webserver talks about "Uncaught Error: Class 'OCP\\Lock\\ILockingProvider' not found" and gives the client a 503. => The file "lib/public/Lock/ILockingProvider.php" is available.
Nextcloud shows an error at the same time about "Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist". => Encryption isn't enabled and has never been enabled. No files in the db are marked as encrypted either.

### Server configuration
**Operating system**: Centos 7 x64

**Web server:** Apache httpd 2.4

**Database:** MariaDB 10.1

**PHP version:** 7.0

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** From 9.x to 10.x to 11.x

**Where did you install Nextcloud from:** Manual tar
**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_markdown: 1.0.0
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.3
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - user_saml: 1.2.2
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - federation
  - files_accesscontrol
  - survey_client
  - user_external
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
  'version' => '11.0.1.2',
  'installed' => true,
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => 'yyy',
  ),
  'datadirectory' => '/opt/repo/nextcloud',
  'overwrite.cli.url' => 'https://xxx',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'dbname' => 'xxx',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'xxx.nl',
  'mail_smtphost' => 'mx1.xxx.nl',
  'mail_smtpport' => '25',
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'ldapIgnoreNamingRules' => false,
  'theme' => 'xxx',
  'maintenance' => false,
  'log_type' => 'owncloud', // syslog ook mogelijk
  'syslog_tag' => 'nextcloud',
  'logfile' => '/var/log/nextcloud.log',
  'log_rotate_size' => '104857600',
  'loglevel' => 2,
  'logtimezone' => 'Europe/Amsterdam',
  'logdateformat' => 'Y-m-d H:i:s',
  'lost_password_link' => 'xxx',
  'trashbin_retention_obligation' => 'D60, D61',
  'versions_retention_obligation' => 'disabled',
  'preview_libreoffice_path' => '/opt/libreoffice5.1',
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP + SAML

#### Web server error log
<details>
<summary>Web server error log</summary>
```
[Tue Feb 07 12:04:47.824891 2017] [:error] [pid 27452] [client xxx:58012] PHP Fatal error:  Uncaught Error: Class 'OCP\\Lock\\ILockingProvider' not found in /var/www/html/nextcloud-11.0.1/lib/private/Files/View.php:1156\nStack trace:\n#0 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#1 /var/www/html/nextcloud-11.0.1/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#2 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#3 {main}\n  thrown in /var/www/html/nextcloud-11.0.1/lib/private/Files/View.php on line 1156
```
</details>

#### Web server error log
<details>
<summary>Web server access log</summary>
```
xxx - xxx [07/Feb/2017:12:04:47 +0100] "GET /remote.php/webdav/XXX%20Product/UX/11.Design/1.%20Identity/7.%20Prints/2.%20Updates/2016_04_14_update.key HTTP/1.1" 503 273 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
```
</details>
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"WJmpz3V7ZghFuuv4DpFN1AAAABQ","remoteAddr":"xxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud-11.0.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud-11.0.1\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud-11.0.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud-11.0.1\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud-11.0.1\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud-11.0.1\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud-11.0.1\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":312,\"User\":\"xxx\"}","level":4,"time":"2017-02-07 12:04:47","method":"GET","url":"\/remote.php\/webdav\/XXX%20Product\/UX\/11.Design\/1.%20Identity\/7.%20Prints\/2.%20Updates\/2016_04_14_update.key","user":"xxx","version":"11.0.1.2"}
```
</details>

**Comment by MorrisJobke** [comment] 2017-07-27 12:26
Duplicate of #5381

**Closed by MorrisJobke** 2017-07-27 12:26 UTC
Labels: feature: encryption, feature: filesystem
