### ISSUE TITLE
After terminating the file transfer, the transfer did not stop immediately

### ISSUE THREAD

**Issue by jack9603301** [nextcloud/server#24790] opened 2020-12-21 07:05 UTC
After terminating the file transfer, the transfer did not stop immediately

### Steps to reproduce
1. Start a large file download
2. Monitoring server load
3. Terminate download task

### Expected behaviour
After the download or upload is complete, the CPU immediately returns to a low load state

### Actual behaviour
It seems that the download process has not stopped and is still transmitting, and the cpu is in a high load environment

Before downloading:

![图片](https://user-images.githubusercontent.com/9047180/102751898-a7dde700-43a3-11eb-868e-0261f70940fa.png)

When downloading:

![图片](https://user-images.githubusercontent.com/9047180/102751920-b1ffe580-43a3-11eb-9f9b-727fec2e3d4f.png)

After the download is terminated:

![图片](https://user-images.githubusercontent.com/9047180/102751942-be843e00-43a3-11eb-9d1b-5be7f124aff9.png)

### Server configuration

**Operating system:debian**

**Web server:nginx**

**Database:mysql**

**PHP version:7.4.12**

**Nextcloud version:20.0.2** (see Nextcloud admin page)

**Comment by kesselb** [comment] 2020-12-21 09:48
Duplicate of https://github.com/nextcloud/server/issues/8161 https://github.com/nextcloud/server/issues/22334

**Closed by kesselb** 2020-12-21 09:48 UTC
Labels: 0. Needs triage, bug

**Comment by jack9603301** [comment] 2020-12-21 09:59
Is there the best way to solve this problem, hope the community can fix this problem

**Comment by jack9603301** [comment] 2020-12-23 06:35
@kesselb Is there the best way to solve this problem, hope the community can fix this problem

**Comment by yevon** [comment] 2022-10-10 19:27
Same problems here, this is still a terrible performance problem. If you have a mechanic HDD you will notice that after downloading files, nextcloud still uses the disk heavily after a while. And downloads don't start after serveral seconds. The download logic is very performnace problematic.
