### ISSUE TITLE
[Bug] NC28.0.3 Files Folder RecommendedFile.vue Files shown, but links inactive

### ISSUE THREAD

**Issue by nhanlx89** [nextcloud/server#43970] opened 2024-03-04 01:52 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After update nc28.0.3
In the files folder menu on the nextcloud webpage the recommendfiles.vue links are show for onlyoffice files, but the link to the file doesnt work
(see example picture: the file New document doesn't open by clicking on it)
![1](https://github.com/nextcloud/server/assets/90684647/7969fc38-4ad4-4767-bcfc-fbd0fc1b4612)

### Steps to reproduce

1. update to nc 28.0.3
2. click on recommended files in file menu (onlyoffice file with onlyofficeapp)
3. share a folder with a user or on you
4. on the recipient user account : if the shared folder is in the recommended file vue, click on it

### Expected behavior

If you click on the shown file "New document" the file should open in Onlyoffice

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.angiang.dcs.vn"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "http:\/\/files.angiang.dcs.vn",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_language": "vi",
        "force_language": "vi",
        "default_locale": "vi_VN",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "default_phone_region": "VN",
        "theme": "",
        "loglevel": 2,
        "skeletondirectory": "",
        "htaccess.RewriteBase": "\/",
        "app_install_overwrite": [
            "files_markdown",
            "ldapcontacts"
        ],
        "maintenance": false,
        "updater.release.channel": "stable",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
Console has to be executed with the user that owns the file config/config.php
Current user id: 0
Owner id of config.php: 33
Try adding 'sudo -u #33' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 33' to the docker command (without the single quotes)
Console has to be executed with the user that owns the file config/config.php
Current user id: 0
Owner id of config.php: 33
Try adding 'sudo -u #33' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 33' to the docker command (without the single quotes)
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - ldapcontacts: 2.0.5
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - snappymail: 2.35.2
  - stt_helper: 1.1.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - theming_customcss: 1.15.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 27.0.1)
  - dashboard: 7.8.0 (installed 7.7.0)
  - encryption: 2.16.0
  - files_external: 1.20.0 (installed 1.19.0)
  - files_reminders: 1.1.0 (installed 1.0.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.16.0)
  - support: 1.11.0 (installed 1.10.0)
  - survey_client: 1.16.0 (installed 1.15.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - weather_status: 1.8.0 (installed 1.7.0)
Console has to be executed with the user that owns the file config/config.php
Current user id: 0
Owner id of config.php: 33
Try adding 'sudo -u #33' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 33' to the docker command (without the single quotes)
Console has to be executed with the user that owns the file config/config.php
Current user id: 0
Owner id of config.php: 33
Try adding 'sudo -u #33' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 33' to the docker command (without the single quotes)
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- ldapcontacts
	- INVALID_HASH
		- img/app.svg

Raw output
==========
Array
(
    [ldapcontacts] => Array
        (
            [INVALID_HASH] => Array
                (
                    [img/app.svg] => Array
                        (
                            [expected] => b1747ed1a5e2bc6826752f2ace142a4ba26dad457b6ea494731651d60823525950716e83d09f8d71795cf4736fd95fc7acfc87525b481a2dc7cd218c08461f32
                            [current] => 8ceeb3f8a3eba7dd9baeed5bd67aafad7e13f6f9a74c1b04f793445ca5a8e308e789d0a091a9e56035e844f7f940f9e46aa7b3c4acd132039155df788a0a0195
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
No response
```

### Additional info

No response

**Comment by XueSheng-GIT** [comment] 2024-03-04 11:27
Seems to be a duplicate of https://github.com/nextcloud/server/issues/43932 and/or https://github.com/nextcloud/recommendations/issues/700
Additional references: https://github.com/nextcloud/server/issues/43932#issuecomment-1974810874

**Comment by joshtrichards** [comment] 2024-03-04 17:09
Duplicate of #43932

**Closed by joshtrichards** 2024-03-04 17:09 UTC
Labels: bug, 0. Needs triage, 28-feedback
