### ISSUE TITLE
Clicking "select all" on a filtered search selects all files in directory, not just those filtered.

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2781] opened 2016-12-20 12:10 UTC
When I filter a directory using the search bar on the top right, it brings up the relevant files lightning quick (thank you!) however, if I think click the select all button, it will select all files in the directory and not just those listed:

![image](https://cloud.githubusercontent.com/assets/3178412/21350046/2cd0849a-c6ad-11e6-9b4f-bbd52f6e57bc.png)

4 files match, 103 files selected.

NC11
Ubuntu 16.04

**Comment by raimund-schluessler** [comment] 2017-01-09 12:51
This is a duplicate of https://github.com/nextcloud/server/issues/2075 --> closing in favor of original one.

**Closed by raimund-schluessler** 2017-01-09 12:51 UTC
Labels: bug, feature: files
