### ISSUE TITLE
User panel does not resize correctly in chrome and firefox

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/server#20171] opened 2020-03-25 21:22 UTC
### Steps to reproduce
1. Open the user panel when your browser window is occupying half the screen (like with the window snapping feature) e.g. 800x832px
2. Click the three bars on the left side to expand the left sidebar
3. Observer the empty space
4. you can now also resize the window repeat step 2. The white space will stay.

### Expected behaviour
The UI should use all available space.

### Actual behaviour
An empty space is created.

### Software versions
Nextcloud version: 18.0.3
#### Tested with
Firefox: 74.0
Chrome: 80.0.3987

### Gif

![nextcloud-user-panel-resize-bug](https://user-images.githubusercontent.com/1377943/77586780-08a8c380-6ee7-11ea-82a2-8dabbd5f722a.gif)

**Comment by szaimen** [comment] 2021-05-31 11:21
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 11:21 UTC
Labels: 0. Needs triage, bug
