### ISSUE TITLE
Activity app broken on daily build for me

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2255] opened 2016-11-22 17:49 UTC
It's loading endless for me and shows the following error:

```
richObjectStringParser.js?v=bc2aae7…:55 Uncaught TypeError: Cannot read property 'type' of null(…)parseParameter @ richObjectStringParser.js?v=bc2aae7…:55(anonymous function) @ richObjectStringParser.js?v=bc2aae7…:39_.each._.forEach @ underscore.js?v=bc2aae7…:153parseMessage @ richObjectStringParser.js?v=bc2aae7…:37addActivity @ script.js?v=bc2aae7…:203appendActivityToContainer @ script.js?v=bc2aae7…:164handleActivitiesCallback @ script.js?v=bc2aae7…:133success @ script.js?v=bc2aae7…:98j @ jquery.js:3099fireWith @ jquery.js:3211x @ jquery.js:8264(anonymous function) @ jquery.js:8605
```

This is what index.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0 gave me:

```json
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":100,
         "message":null
      },
      "data":[
         {
            "activity_id":31,
            "app":"files_sharing",
            "type":"public_links",
            "affecteduser":"test",
            "user":"",
            "subject":" downloaded via public link",
            "subject_rich":[
               "{file} downloaded via public link",
               {
                  "file":null
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":85,
            "object_name":"\/Documents",
            "link":"",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/core\/img\/actions\/download.svg",
            "datetime":"2016-11-22T17:47:13+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents",
                  "source":"\/nextcloud\/core\/img\/filetypes\/folder.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":30,
            "app":"files_sharing",
            "type":"shared",
            "affecteduser":"test",
            "user":"test",
            "subject":"You shared \/Documents as public link",
            "subject_rich":[
               "You shared {file} as public link",
               {
                  "file":{
                     "type":"file",
                     "id":85,
                     "name":"Documents",
                     "path":"\/Documents",
                     "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/f\/85"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":85,
            "object_name":"\/Documents",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/core\/img\/actions\/share.svg",
            "datetime":"2016-11-22T17:46:55+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents",
                  "source":"\/nextcloud\/core\/img\/filetypes\/folder.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":29,
            "app":"dav",
            "type":"calendar",
            "affecteduser":"test",
            "user":"test",
            "subject":"You created calendar Personal",
            "subject_rich":[
               "",
               [

               ]
            ],
            "message":"",
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"calendar",
            "object_id":3,
            "object_name":"",
            "link":"",
            "icon":"",
            "datetime":"2016-11-22T17:42:50+00:00",
            "previews":[

            ]
         },
         {
            "activity_id":28,
            "app":"files",
            "type":"file_created",
            "affecteduser":"test",
            "user":"test",
            "subject":"You created \/Nextcloud Manual.pdf",
            "subject_rich":[
               "You created {file1}",
               {
                  "file1":{
                     "type":"file",
                     "id":89,
                     "name":"Nextcloud Manual.pdf",
                     "path":"\/Nextcloud Manual.pdf"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":89,
            "object_name":"\/Nextcloud Manual.pdf",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/apps\/files\/img\/add-color.svg",
            "datetime":"2016-11-22T17:42:50+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/&scrollto=Nextcloud+Manual.pdf",
                  "source":"\/nextcloud\/core\/img\/filetypes\/application-pdf.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":27,
            "app":"files",
            "type":"file_created",
            "affecteduser":"test",
            "user":"test",
            "subject":"You created \/Nextcloud.mp4",
            "subject_rich":[
               "You created {file1}",
               {
                  "file1":{
                     "type":"file",
                     "id":88,
                     "name":"Nextcloud.mp4",
                     "path":"\/Nextcloud.mp4"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":88,
            "object_name":"\/Nextcloud.mp4",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/apps\/files\/img\/add-color.svg",
            "datetime":"2016-11-22T17:42:50+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/&scrollto=Nextcloud.mp4",
                  "source":"\/nextcloud\/core\/img\/filetypes\/video.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":26,
            "app":"files",
            "type":"file_created",
            "affecteduser":"test",
            "user":"test",
            "subject":"You created \/Documents\/About.odt",
            "subject_rich":[
               "You created {file1}",
               {
                  "file1":{
                     "type":"file",
                     "id":87,
                     "name":"About.odt",
                     "path":"\/Documents\/About.odt"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":87,
            "object_name":"\/Documents\/About.odt",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/apps\/files\/img\/add-color.svg",
            "datetime":"2016-11-22T17:42:50+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents&scrollto=About.odt",
                  "source":"\/nextcloud\/core\/img\/filetypes\/x-office-document.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":25,
            "app":"files",
            "type":"file_created",
            "affecteduser":"test",
            "user":"test",
            "subject":"You created \/Documents\/About.txt",
            "subject_rich":[
               "You created {file1}",
               {
                  "file1":{
                     "type":"file",
                     "id":86,
                     "name":"About.txt",
                     "path":"\/Documents\/About.txt"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":86,
            "object_name":"\/Documents\/About.txt",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/apps\/files\/img\/add-color.svg",
            "datetime":"2016-11-22T17:42:50+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents&scrollto=About.txt",
                  "source":"\/nextcloud\/index.php\/core\/preview.png?file=\/Documents\/About.txt&c=4e66dd29b1bdd34b7224fb743194e274&x=150&y=150",
                  "isMimeTypeIcon":false
               }
            ]
         },
         {
            "activity_id":24,
            "app":"files",
            "type":"file_created",
            "affecteduser":"test",
            "user":"test",
            "subject":"You created \/Documents",
            "subject_rich":[
               "You created {file1}",
               {
                  "file1":{
                     "type":"file",
                     "id":85,
                     "name":"Documents",
                     "path":"\/Documents"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":85,
            "object_name":"\/Documents",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/apps\/files\/img\/add-color.svg",
            "datetime":"2016-11-22T17:42:50+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Documents",
                  "source":"\/nextcloud\/core\/img\/filetypes\/folder.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":23,
            "app":"files",
            "type":"file_created",
            "affecteduser":"test",
            "user":"test",
            "subject":"You created ",
            "subject_rich":[
               "You created {file1}",
               {
                  "file1":{
                     "type":"file",
                     "id":78,
                     "name":"",
                     "path":""
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":78,
            "object_name":"",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/apps\/files\/img\/add-color.svg",
            "datetime":"2016-11-22T17:42:50+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/",
                  "source":"\/nextcloud\/core\/img\/filetypes\/folder.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":21,
            "app":"files_sharing",
            "type":"shared",
            "affecteduser":"test",
            "user":"admin",
            "subject":"admin shared \/Photos with you",
            "subject_rich":[
               "{actor} shared {file} with you",
               {
                  "file":{
                     "type":"file",
                     "id":3,
                     "name":"Photos",
                     "path":"\/Photos",
                     "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/f\/3"
                  },
                  "actor":{
                     "type":"user",
                     "id":"admin",
                     "name":"admin"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":3,
            "object_name":"\/Photos",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/Photos",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/core\/img\/actions\/share.svg",
            "datetime":"2016-11-22T17:42:01+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Photos\/",
                  "source":"\/nextcloud\/core\/img\/filetypes\/folder.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":19,
            "app":"files_sharing",
            "type":"shared",
            "affecteduser":"test",
            "user":"admin",
            "subject":"admin removed you from \/Photos",
            "subject_rich":[
               "{actor} removed you from {file}",
               {
                  "file":{
                     "type":"file",
                     "id":3,
                     "name":"Photos",
                     "path":"\/Photos",
                     "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/f\/3"
                  },
                  "actor":{
                     "type":"user",
                     "id":"admin",
                     "name":"admin"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":3,
            "object_name":"\/Photos",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/Photos",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/core\/img\/actions\/share.svg",
            "datetime":"2016-11-22T17:41:50+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Photos\/",
                  "source":"\/nextcloud\/core\/img\/filetypes\/folder.svg",
                  "isMimeTypeIcon":true
               }
            ]
         },
         {
            "activity_id":17,
            "app":"files_sharing",
            "type":"shared",
            "affecteduser":"test",
            "user":"admin",
            "subject":"admin shared \/Photos with you",
            "subject_rich":[
               "{actor} shared {file} with you",
               {
                  "file":{
                     "type":"file",
                     "id":3,
                     "name":"Photos",
                     "path":"\/Photos",
                     "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/f\/3"
                  },
                  "actor":{
                     "type":"user",
                     "id":"admin",
                     "name":"admin"
                  }
               }
            ],
            "message":null,
            "message_rich":[
               "",
               [

               ]
            ],
            "object_type":"files",
            "object_id":3,
            "object_name":"\/Photos",
            "link":"http:\/\/10.211.55.7\/nextcloud\/index.php\/apps\/files\/?dir=\/Photos",
            "icon":"http:\/\/10.211.55.7\/nextcloud\/core\/img\/actions\/share.svg",
            "datetime":"2016-11-22T17:41:42+00:00",
            "previews":[
               {
                  "link":"\/nextcloud\/index.php\/apps\/files\/?dir=\/Photos\/",
                  "source":"\/nextcloud\/core\/img\/filetypes\/folder.svg",
                  "isMimeTypeIcon":true
               }
            ]
         }
      ]
   }
}
```

**Comment by LukasReschke** [comment] 2016-11-22 17:50
cc @nickvergessen

**Comment by LukasReschke** [comment] 2016-11-22 17:50
Only happens on `filter=by` and `filter=all`. I suppose I have some events that the JS cannot handle :)

**Comment by nickvergessen** [comment] 2016-11-22 19:23
Should be caused by #2257 so I'm closing this. Created an issue in the activity repo for future hardening against malformed parameters: https://github.com/nextcloud/activity/issues/77

**Closed by nickvergessen** 2016-11-22 19:23 UTC
Labels: bug
