### ISSUE TITLE
Admin password box has missing text in mobile view

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#17874] opened 2019-11-09 16:18 UTC
Hello. 
I am running Nextcloud 17.0.1.

There is a small issue with missing text on the admin password popup when enabling or disabling apps from a mobile phone. I think it's been like this on NC 16 too.

![20191109_171736](https://user-images.githubusercontent.com/1469150/68531658-de2de380-0314-11ea-95e4-ffeb90ea7e46.jpg)

**Comment by szaimen** [comment] 2021-06-07 17:40
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 17:40 UTC
Labels: 0. Needs triage, bug
