### ISSUE TITLE
Error: Trying to access array offset on value of type bool at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#669

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#27832] opened 2021-07-06 18:59 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Delete a Folder from External SMB Share
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**
Ubuntu 20.4
**Web server:**
Apache2
**Database:**
MariaDB 10.5.11
**PHP version:**
8.0.8
**Nextcloud version:** (see Nextcloud admin page)
22 & 21

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes SMB
**Are you using encryption:** yes/no
YES
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

</details>

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/nextcloud.log)

```
{
  "reqId": "fDWkAxpdvBjzH6N4h6Ad",
  "level": 3,
  "time": "2021-07-06T18:49:34+00:00",
  "remoteAddr": "10.0.0.1",
  "user": "admin",
  "app": "PHP",
  "method": "DELETE",
  "url": "/remote.php/dav/files/axheli/SMB/Programs/Windows%2010",
  "message": "Trying to access array offset on value of type bool at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#669",
  "userAgent": "Mozilla/5.0 (Windows) mirall/3.2.3stable-Win64 (build 20210624) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
  "version": "22.0.0.11",
  "exception": {
    "Exception": "Error",
    "Message": "Trying to access array offset on value of type bool at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#669",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 669,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 767,
        "function": "updateEncryptedVersion",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 651,
        "function": "copyBetweenStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 747,
        "function": "copyFromStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 651,
        "function": "copyBetweenStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 747,
        "function": "copyFromStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php",
        "line": 623,
        "function": "copyBetweenStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
        "line": 576,
        "function": "moveFromStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Encryption",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/files_trashbin/lib/Storage.php",
        "line": 239,
        "function": "moveFromStorage",
        "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php",
        "line": 322,
        "function": "moveFromStorage",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php",
        "line": 107,
        "function": "move2trash",
        "class": "OCA\\Files_Trashbin\\Trashbin",
        "type": "::"
      },
      {
        "file": "/var/www/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php",
        "line": 102,
        "function": "moveToTrash",
        "class": "OCA\\Files_Trashbin\\Trash\\LegacyTrashBackend",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/files_trashbin/lib/Storage.php",
        "line": 202,
        "function": "moveToTrash",
        "class": "OCA\\Files_Trashbin\\Trash\\TrashManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/files_trashbin/lib/Storage.php",
        "line": 125,
        "function": "doDelete",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/View.php",
        "line": 1171,
        "function": "rmdir",
        "class": "OCA\\Files_Trashbin\\Storage",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/View.php",
        "line": 350,
        "function": "basicOperation",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 309,
        "function": "rmdir",
        "class": "OC\\Files\\View",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 179,
        "function": "delete",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 281,
        "function": "delete",
        "class": "Sabre\\DAV\\Tree",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpDelete",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
        "line": 332,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 166,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  },
  "id": "60e4a7d4160cc"
}
```

![image](https://user-images.githubusercontent.com/59488153/124658078-f303a700-de68-11eb-821e-e54125fc4c34.png)

**Comment by andyxheli** [comment] 2021-07-06 19:45
@juliushaertl any feedback on this.

**Comment by szaimen** [comment] 2021-08-08 14:49
Is this also happening with PHP 7.4?

**Comment by szaimen** [comment] 2021-08-08 14:51
Looks like a duplicate of https://github.com/nextcloud/server/issues/27692, no?

**Comment by andyxheli** [comment] 2021-08-09 00:40
@szaimen not sure im not using php7.4

**Comment by szaimen** [comment] 2021-08-17 11:31
Lets track this in https://github.com/nextcloud/server/issues/27692

**Closed by szaimen** 2021-08-17 11:31 UTC
Labels: bug, needs info, 0. Needs triage
