### ISSUE TITLE
Support file versioning via public api

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5761] opened 2017-07-18 07:39 UTC
We would like to add file versioning to the android app.
It should be shown, just like in web ui, in the detail screen of a file and lists all previous version of a file with the possibility to download/restore.

From the server we then need a proper api for this.

**Comment by MorrisJobke** [comment] 2017-07-18 07:41
Duplicate of #4724

**Closed by MorrisJobke** 2017-07-18 07:41 UTC
