### ISSUE TITLE
Nextcloud freezes when staying on PDF

### ISSUE THREAD

**Issue by clement850** [nextcloud/server#26289] opened 2021-03-25 10:29 UTC
Hello,

I noticed that when I open a PDF (or JPEG) file, and staying on some minutes, the webpage freezes and I can't do anything. 

Tried with different browsers but there's still the problem. 

Thanks

Nextcloud  20.0.8 / Debian 10
Apache/2.4.38 (Debian)
PHP 7.4 (FPM)

**Comment by clement850** [comment] 2021-04-02 09:50
up

**Comment by szaimen** [comment] 2021-07-02 11:50
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-07-02 11:50 UTC
Labels: 0. Needs triage, bug
