### ISSUE TITLE
[Bug]: incorrect display of quota volume

### ISSUE THREAD

**Issue by Revenant-8** [nextcloud/server#39517] opened 2023-07-21 07:04 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Incorrect display of the volume of users and in the admin panel, when specifying a quota of 1 GB, 1.1 is displayed, when specifying 5 GB - 5.4, at 50 GB - 56.9, at 44 GB - 50.5
What is the reason and how to fix it? I tried to specify in bytes, but no - 1 Gibibytes = 1073741824 Bytes , I set the quota "1073741824 B" or "1000000000 B" - 1.1 GB is displayed
 
<img width="151" alt="image" src="https://github.com/nextcloud/server/assets/133635975/5d648a14-7d7c-407c-892b-c19c94663845">

### Steps to reproduce

1. deploy next cloud server
2. set quota to users 

### Expected behavior

correct display of the quota volume

### Installation method

None

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by l3ochan** [comment] 2023-07-21 21:15
I have the same issue here https://github.com/nextcloud/server/issues/39500

**Comment by xbluemonkx** [comment] 2023-08-13 16:52
I tould like to add another problem that I think i related: I am not able to provide individual quota anymore. e.g. If i type "100 MB" the system sets it to "unlimited"

**Comment by l3ochan** [comment] 2023-08-13 20:34
Yes I have that issue too, when I input a quota, it errases my input and displays "unlimited" but the quota I set was in fact set. 
Check my issue https://github.com/nextcloud/server/issues/39500
and the video of it https://youtu.be/tOijtU3AffQ

**Comment by skl256** [comment] 2023-08-14 13:36
https://github.com/nextcloud/server/issues/39830 yes

**Comment by skl256** [comment] 2023-08-19 09:24
When correcting, please check the case showing not only the quota, but also the file sizes in the application files

**Comment by haskelious** [comment] 2023-08-24 22:16
Duplicate of #39500 I believe

**Comment by skjnldsv** [comment] 2024-08-01 05:58
Fixed since https://github.com/nextcloud/server/pull/42186

**Closed by skjnldsv** 2024-08-01 05:58 UTC
Labels: bug, 0. Needs triage, feature: files, feature: users and groups, 27-feedback
