### ISSUE TITLE
GuzzleHttp\Exception\ConnectException: cURL error 7

### ISSUE THREAD

**Issue by sosed213** [nextcloud/server#27582] opened 2021-06-21 05:16 UTC
Nextcloud 21.0.2
and
Nextcloud 22.0.0 beta 5

Ubuntu server 20.04

nginx version: nginx/1.19.3
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --user=nginx --group=nginx --with-cc-opt=-Wno-deprecated-declarations --with-cc-opt=-Wno-ignored-qualifiers --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_mp4_module --with-http_auth_request_module --with-http_slice_module --with-http_stub_status_module --with-http_realip_module --with-http_sub_module --add-module=/usr/local/src/nginx/modules/incubator-pagespeed-ngx-1.13.35.2-stable --add-module=/usr/local/src/nginx/modules/ngx_brotli --add-module=/usr/local/src/nginx/modules/headers-more-nginx-module-0.33 --add-module=/usr/local/src/nginx/modules/ngx_http_geoip2_module-3.3 --with-openssl=/usr/local/src/nginx/modules/openssl-1.1.1g --add-module=/usr/local/src/nginx/modules/ngx_cache_purge --add-module=/usr/local/src/nginx/modules/fancyindex

PHP 7.4.20

PostgreSQL 13.3

app:list
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - circles: 22.0.0-beta.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.18.0
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.1
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.0.4
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - federation
  - sharebymail
  - user_ldap
  - user_status
  - weather_status

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud-test.exemple.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.0.0.8",
        "overwrite.cli.url": "https:\/\/cloud-test.exemple.ru",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "logtimezone": "Asia\/Omsk",
        "logfile": "\/var\/log-cloud\/nextcloud-test.log",
        "log_rotate_size": 52428800,
        "cron_log": true,
        "filesystem_check_changes": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "enable_previews": true,
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\PNG",
            "3": "OC\\Preview\\JPEG",
            "4": "OC\\Preview\\GIF",
            "5": "OC\\Preview\\BMP",
            "6": "OC\\Preview\\Movie"
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "beta",
        "theme": "",
        "app_install_overwrite": [
            "onlyoffice",
            "mail",
            "audioplayer",
            "spreed",
            "calendar",
            "social",
            "files_frommail",
            "printer",
            "event_update_notification",
            "audioplayer_sonos",
            "audioplayer_editor"
        ],
        "default_phone_region": "RU",
        "data-fingerprint": "545d956ea4edad554e05e24358758c2f",
        "mail_sendmailmode": "smtp",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

Error | internet_connection_check | GuzzleHttp\Exception\ConnectException:&nbsp;cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://www.nextcloud.com//var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php&nbsp;- line 158:GuzzleHttp\Handler\CurlFactory::createRejection()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php&nbsp;- line 110:GuzzleHttp\Handler\CurlFactory::finishError()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php&nbsp;- line 47:GuzzleHttp\Handler\CurlFactory::finish()/var/www/cloud-test/lib/private/Http/Client/DnsPinMiddleware.php&nbsp;- line 124:GuzzleHttp\Handler\CurlHandler-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php&nbsp;- line 35:OC\Http\Client\DnsPinMiddleware-&gt;OC\Http\Client\{closure}("*** sensiti ... *")/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Middleware.php&nbsp;- line 31:GuzzleHttp\PrepareBodyMiddleware-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php&nbsp;- line 71:GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Middleware.php&nbsp;- line 63:GuzzleHttp\RedirectMiddleware-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php&nbsp;- line 75:GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Client.php&nbsp;- line 331:GuzzleHttp\HandlerStack-&gt;__invoke()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Client.php&nbsp;- line 168:GuzzleHttp\Client-&gt;transfer()/var/www/cloud-test/3rdparty/guzzlehttp/guzzle/src/Client.php&nbsp;- line 187:GuzzleHttp\Client-&gt;requestAsync()/var/www/cloud-test/lib/private/Http/Client/Client.php&nbsp;- line 223:GuzzleHttp\Client-&gt;request()/var/www/cloud-test/apps/settings/lib/Controller/CheckSetupController.php&nbsp;- line 179:OC\Http\Client\Client-&gt;get()/var/www/cloud-test/apps/settings/lib/Controller/CheckSetupController.php&nbsp;- line 162:OCA\Settings\Controller\CheckSetupController-&gt;isSiteReachable()/var/www/cloud-test/apps/settings/lib/Controller/CheckSetupController.php&nbsp;- line 738:OCA\Settings\Controller\CheckSetupController-&gt;hasInternetConnectivityProblems()/var/www/cloud-test/lib/private/AppFramework/Http/Dispatcher.php&nbsp;- line 217:OCA\Settings\Controller\CheckSetupController-&gt;check()/var/www/cloud-test/lib/private/AppFramework/Http/Dispatcher.php&nbsp;- line 126:OC\AppFramework\Http\Dispatcher-&gt;executeController()/var/www/cloud-test/lib/private/AppFramework/App.php&nbsp;- line 156:OC\AppFramework\Http\Dispatcher-&gt;dispatch()/var/www/cloud-test/lib/private/Route/Router.php&nbsp;- line 303:OC\AppFramework\App::main()/var/www/cloud-test/lib/base.php&nbsp;- line 998:OC\Route\Router-&gt;match()/var/www/cloud-test/index.php&nbsp;- line 36:OC::handleRequest()
-- | -- | --

**Comment by nursoda** [comment] 2021-06-24 12:01
I see a similar issue already described [here](https://help.nextcloud.com/t/nextcloud-22-beta-3-with-changelog/117692/2). I have a 30seconds timeout on each call of /settings/admin/overview and I do not get proper update notifications. I'm on NGINX on Arch. Happens since NC 22b3, now unsure if related to NC server code, or if it is a webserver configuration error. Anyway, the issue seems related to **calling www.nextcloud.com as http instead of https**:

> /settings/ajax/checksetup: Cannot connect to: www.nextcloud.com
> GuzzleHttp\\Exception\\ConnectException: cURL error 28: Connection timed out after 30001 milliseconds

<details>

```json
{
  "reqId": "8G2TbC2HaPuDM4sGWfd0",
  "level": 3,
  "time": "2021-06-24T13:37:08+02:00",
  "remoteAddr": "192.168.X.Y",
  "user": "USER",
  "app": "internet_connection_check",
  "method": "GET",
  "url": "/settings/ajax/checksetup",
  "message": "Cannot connect to: www.nextcloud.com",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
  "version": "22.0.0.8",
  "exception": {
    "Exception": "GuzzleHttp\\Exception\\ConnectException",
    "Message": "cURL error 28: Connection timed out after 30001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://www.nextcloud.com/",
    "Code": 0,
    "Trace": [
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
        "line": 158,
        "function": "createRejection",
        "class": "GuzzleHttp\\Handler\\CurlFactory",
        "type": "::"
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
        "line": 110,
        "function": "finishError",
        "class": "GuzzleHttp\\Handler\\CurlFactory",
        "type": "::"
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php",
        "line": 47,
        "function": "finish",
        "class": "GuzzleHttp\\Handler\\CurlFactory",
        "type": "::"
      },
      {
        "file": "/PATH/lib/private/Http/Client/DnsPinMiddleware.php",
        "line": 124,
        "function": "__invoke",
        "class": "GuzzleHttp\\Handler\\CurlHandler",
        "type": "->"
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php",
        "line": 35,
        "function": "OC\\Http\\Client\\{closure}",
        "class": "OC\\Http\\Client\\DnsPinMiddleware",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
        "line": 31,
        "function": "__invoke",
        "class": "GuzzleHttp\\PrepareBodyMiddleware",
        "type": "->"
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php",
        "line": 71,
        "function": "GuzzleHttp\\{closure}",
        "class": "GuzzleHttp\\Middleware",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Middleware.php",
        "line": 63,
        "function": "__invoke",
        "class": "GuzzleHttp\\RedirectMiddleware",
        "type": "->"
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php",
        "line": 75,
        "function": "GuzzleHttp\\{closure}",
        "class": "GuzzleHttp\\Middleware",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 331,
        "function": "__invoke",
        "class": "GuzzleHttp\\HandlerStack",
        "type": "->"
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 168,
        "function": "transfer",
        "class": "GuzzleHttp\\Client",
        "type": "->"
      },
      {
        "file": "/PATH/3rdparty/guzzlehttp/guzzle/src/Client.php",
        "line": 187,
        "function": "requestAsync",
        "class": "GuzzleHttp\\Client",
        "type": "->"
      },
      {
        "file": "/PATH/lib/private/Http/Client/Client.php",
        "line": 223,
        "function": "request",
        "class": "GuzzleHttp\\Client",
        "type": "->"
      },
      {
        "file": "/PATH/apps/settings/lib/Controller/CheckSetupController.php",
        "line": 179,
        "function": "get",
        "class": "OC\\Http\\Client\\Client",
        "type": "->"
      },
      {
        "file": "/PATH/apps/settings/lib/Controller/CheckSetupController.php",
        "line": 162,
        "function": "isSiteReachable",
        "class": "OCA\\Settings\\Controller\\CheckSetupController",
        "type": "->"
      },
      {
        "file": "/PATH/apps/settings/lib/Controller/CheckSetupController.php",
        "line": 738,
        "function": "hasInternetConnectivityProblems",
        "class": "OCA\\Settings\\Controller\\CheckSetupController",
        "type": "->"
      },
      {
        "file": "/PATH/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "check",
        "class": "OCA\\Settings\\Controller\\CheckSetupController",
        "type": "->"
      },
      {
        "file": "/PATH/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/PATH/lib/private/AppFramework/App.php",
        "line": 156,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/PATH/lib/private/Route/Router.php",
        "line": 303,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/PATH/lib/base.php",
        "line": 998,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/PATH/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/PATH/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
    "Line": 210,
    "CustomMessage": "Cannot connect to: www.nextcloud.com"
  }
}
```

</details>

**Comment by sosed213** [comment] 2021-06-25 02:49
![image](https://user-images.githubusercontent.com/16791649/123361930-b0e98400-d591-11eb-9f9e-c8d01eb7091b.png)


The server does not see new updates. But if forcibly click "Open update window", it successfully installed Nextcloud 22.0.0 RC1.

After the update, the old problem remained:
"Could not connect to the App Store or no updates have been returned at all. Search manually for updates or make sure your server has access to the internet and can connect to the App Store."

And in the magazine there is still the same error.

In parallel, there is another Nextcloud 21.0.2 server, with the same Nginx + PHP 7.4 configuration. And there is no such problem.

**Comment by HammyHavoc** [comment] 2021-06-25 03:31
Seeing the same behaviour. Also having a problem with notifications for NC Talk not working, which seems related with an error 7 in the log.

**Comment by RobertSmits** [comment] 2021-06-25 13:44
Having the same issue, started with beta 1 and still here in RC1.
The issue is related to the changes in /lib/private/Http.
If I take the Http lib from Nextcloud 21.0.2 and place it in Nextcloud 22 the issue goes away.

**Comment by HammyHavoc** [comment] 2021-06-25 14:02
Does doing that appear to break anything for you? I.e. Do you get any further errors in your log as a consequence?
________________________________

**Comment by RobertSmits** [comment] 2021-06-25 15:49
This was working without a problem in the betas, though it seems that this now generates an eror during handling of .well-known routes.

**Comment by HammyHavoc** [comment] 2021-06-25 20:39
I followed what you said on https://github.com/nextcloud/server/issues/27582#issuecomment-868510016 and I can confirm that my Nextcloud's updates and notifications now work again as expected. Thanks buddy!

Hoping this gets resolved.

**Comment by flipreverse** [comment] 2021-06-26 21:11
@RobertSmits, your hint in https://github.com/nextcloud/server/issues/27582#issuecomment-868510016 also solved my issue: I wasn't able to install any app update. cURL complained about not finding a matching subject alternative name for github.com. Reverting lib http back to NC21.0 did the trick.

**Comment by nursoda** [comment] 2021-07-01 14:33
I just installed manually and tested: 22RC2 doesn't fix this. How to raise attention that this should be fixed prior to releasing 22?

**Comment by HammyHavoc** [comment] 2021-07-01 19:34
I tweeted them regarding it: https://twitter.com/hammyhavoc/status/1410682904783564801?s=19
________________________________

**Comment by nursoda** [comment] 2021-07-01 22:20
> If I take the Http lib from Nextcloud 21.0.2 and place it in Nextcloud 22 the issue goes away.

Doesn't work for me in RC2: If I do that, I can update apps again, but `occ update:check` still yields beta 3 as available update.

**Comment by nullspoon** [comment] 2021-07-02 01:08
I did some troubleshooting on this just now and I think found a "workaround" that resolves the issue, though it does remove some of the new functionality recently added (namely `addDnsPinning`). I am still troubleshooting to figure out _why_ exactly this is broken, but nonetheless, the commit / line that breaks this is in `lib/private/Http/Client/ClientService.php`, updated in this commit: https://github.com/nextcloud/server/commit/5f3abffe6f37b4f8639fde8bcaf35d873a17636c#diff-984dc9729dacad7651dd6c2fe456dae9a7a86edef0f2619e952ea2d33f06d6eeR74

If you comment out that line, `$stack->push($this->dnsPinMiddleware->addDnsPinning());`, the errors go away and you should begin to see apps that need updates.

**Comment by nullspoon** [comment] 2021-07-02 02:45
Found the issue and have an actual fix in locally. Just getting up to speed on contributing to nextcloud and I'll have a PR in shortly.

**Comment by nullspoon** [comment] 2021-07-02 02:57
Tested these changes on my local nextcloud and it resolves the issues. https://github.com/nextcloud/server/pull/27758

**Comment by sosed213** [comment] 2021-07-02 02:59
> I did some troubleshooting on this just now and I think found a "workaround" that resolves the issue, though it does remove some of the new functionality recently added (namely `addDnsPinning`). I am still troubleshooting to figure out _why_ exactly this is broken, but nonetheless, the commit / line that breaks this is in `lib/private/Http/Client/ClientService.php`, updated in this commit: [5f3abff#diff-984dc9729dacad7651dd6c2fe456dae9a7a86edef0f2619e952ea2d33f06d6eeR74](https://github.com/nextcloud/server/commit/5f3abffe6f37b4f8639fde8bcaf35d873a17636c#diff-984dc9729dacad7651dd6c2fe456dae9a7a86edef0f2619e952ea2d33f06d6eeR74)
> 
> If you comment out that line, `$stack->push($this->dnsPinMiddleware->addDnsPinning());`, the errors go away and you should begin to see apps that need updates.

Thank you! It worked for me.

**Comment by nursoda** [comment] 2021-07-02 13:24
> Tested these changes on my local nextcloud and it resolves the issues. #27758

That solved all my check/update/download-related issues on my NC22 test instances. Perfect. Thanks!!

**Closed** 2021-07-05 15:37 UTC
Labels: 0. Needs triage, bug
