### ISSUE TITLE
[Bug]: Footer in middle of Editor when sharing

### ISSUE THREAD

**Issue by maurerle** [nextcloud/server#39258] opened 2023-07-10 07:36 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sharing a txt file with standard nextcloud text editor, the footer is placed weird in the middle.

This is because of:

https://github.com/nextcloud/server/blob/3fb8aad35bcaff25df7fbd521d4f7fd1f15fdf9e/apps/files_sharing/css/public.scss#L91-L93

which overwrites the

```
#app-content footer {
	position: relative;
}
```
from publicshare.css from apps_spreed which overwrites the correct value which should be `position: fixed` as given here:

https://github.com/nextcloud/server/blob/ba2e243ed18488f85475523d97ffc7f9dd93903c/core/css/public.scss#L65-L66

### Steps to reproduce

1. Write a text file which is more than one mobile page long
2. Share the file editable through a public link
3. See that the footer (MyCloud - LegalNotice - Holen Sie sich ihr eigenes Konto) is in the middle of the view

### Expected behavior

The footer should be at the bottom. But actually I would much better have it invisible when editing a text file..
Usability should be the higher good than self-promotion.
I would like to have it only at the bottom of the file, not floating with the view.

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - bookmarks: 13.0.1
  - calendar: 4.4.3
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.3.2
  - contactsinteraction: 1.7.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_mindmap: 0.0.28
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - forms: 3.3.1
  - spreed: 16.0.4
  - support: 1.9.0
  - systemtags: 1.16.0
  - tasks: 0.15.0
  - text: 3.7.2
```

**Comment by szaimen** [comment] 2023-07-10 09:56
cc @juliushaertl

**Comment by juliushaertl** [comment] 2023-07-10 10:26
Duplicate of https://github.com/nextcloud/text/issues/4064 will be fixed with the next maintenance releases

**Closed by juliushaertl** 2023-07-10 10:26 UTC
Labels: bug, 0. Needs triage, 26-feedback
