### ISSUE TITLE
12.0.3RC2 fails to upgrade from 12.0.2

### ISSUE THREAD

**Issue by croessner** [nextcloud/server#6551] opened 2017-09-18 11:38 UTC
### Steps to reproduce
1. Change to beta channel
2. Start upgrade in the web ui
3. after all finished, press the no link, which brings you to a dialog that tells to upgrade on command line with ./occ upgrade
4. Got to command line and do it.

### Expected behaviour
Finishing successfully

### Actual behaviour
```
rns root@web  /var/www/localhost/htdocs/nextcloud # sudo -u system php7.0 occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
PHP Fatal error:  Class OCA\User_SAML\UserBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Authentication\IApacheBackend::getLogoutUrl) in /var/www/localhost/htdocs/nextcloud/apps/user_saml/lib/userbackend.php on line 34
```

### Server configuration

**Operating system**:
Gentoo Linux

**Web server:**
nginx 1.13.5

**Database:**
MariaDB 10.1.26

**PHP version:**
7.0.22

**Nextcloud version:** (see Nextcloud admin page)
12.0.2 (old)
12.0.3RC2 (wanted)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 12.0.2

**Where did you install Nextcloud from:**
Official web site (beta channel)

**Signing status:**
Not possible at the moment, due upgrade failed

**List of activated apps:**
```
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - announcementcenter: 3.1.0
  - apporder: 0.4.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - checksum: 0.3.5
  - circles: 0.12.4
  - comments: 1.2.0
  - dashboard: 4.0.5
  - dav: 1.3.0
  - deck: 0.2.2
  - drawio: 0.8.8
  - encryption: 1.6.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_automatedtagging: 1.2.2
  - files_clipboard: 0.6.4
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_snapshots: 0.1.1
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - flowupload: 0.0.5
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - metadata: 0.5.0
  - music: 0.5.1
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownbackup: 17.5.0
  - passman: 2.1.4
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.0
  - radio: 0.6.0
  - ransomware_protection: 1.0.3
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_diaspora: 1.0.1
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - spreed: 2.0.1
  - spreedme: 0.3.11
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - user_ldap: 1.2.1
  - user_saml: 1.3.2
  - weather: 1.5.0
  - workflowengine: 1.2.0
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "oc6bv5n6btbh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.roessner-net.de"
        ],
        "datadirectory": "\/mnt\/btrfs\/nextcloud",
        "asset-pipeline.enabled": true,
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.roessner-net.de",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "maintenance": true,
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 1,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 2
        },
        "knowledgebaseenabled": true,
        "enable_avatars": false,
        "allow_user_to_change_display_name": false,
        "auth.bruteforce.prevention.enabled": true,
        "updatechecker": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "cron_log": true,
        "log_rotate_size": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mail.roessner-net.de",
        "mail_smtpport": "587",
        "mail_from_address": "nextcloud",
        "mail_domain": "roessner-net.de",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Movie"
        ],
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "singleuser": false,
        "mysql.utf8mb4": true,
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox and another NC server

**Are you using encryption:** yes/no
No, not actively

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes

#### LDAP configuration (delete this part if not used)
```
user_ldap	cleanUpJobOffset	0
user_ldap	enabled	yes
user_ldap	has_memberof_filter_support	1
user_ldap	home_folder_naming_rule
user_ldap	installed_version	1.2.1
user_ldap	last_jpegPhoto_lookup	0
user_ldap	ldap_agent_password	***HIDDEN***
user_ldap	ldap_attributes_for_group_search
user_ldap	ldap_attributes_for_user_search
user_ldap	ldap_backup_host
user_ldap	ldap_backup_port
user_ldap	ldap_base	ou=people,ou=it,dc=roessner-net,dc=de
user_ldap	ldap_base_groups	ou=people,ou=it,dc=roessner-net,dc=de
user_ldap	ldap_base_users	ou=people,ou=it,dc=roessner-net,dc=de
user_ldap	ldap_cache_ttl	3600
user_ldap	ldap_configuration_active	1
user_ldap	ldap_default_ppolicy_dn
user_ldap	ldap_display_name	cn
user_ldap	ldap_dn	cn=webserver,ou=people,ou=it,dc=roessner-net,dc=de
user_ldap	ldap_dynamic_group_member_url
user_ldap	ldap_email_attr	mail
user_ldap	ldap_experienced_admin	0
user_ldap	ldap_expert_username_attr	uniqueIdentifier
user_ldap	ldap_expert_uuid_group_attr	cn
user_ldap	ldap_expert_uuid_user_attr	uniqueIdentifier
user_ldap	ldap_gid_number	gidNumber
user_ldap	ldap_group_display_name	cn
user_ldap	ldap_group_filter	(&(|(objectclass=groupOfNames))(|(cn=NextCloudGroup)))
user_ldap	ldap_group_filter_mode	0
user_ldap	ldap_group_member_assoc_attribute	member
user_ldap	ldap_groupfilter_groups	NextCloudGroup
user_ldap	ldap_groupfilter_objectclass	groupOfNames
user_ldap	ldap_host	localhost
user_ldap	ldap_login_filter	(|(uniqueIdentifier=%uid)(rnsMSRecipientAddress=%uid))
user_ldap	ldap_login_filter_mode	1
user_ldap	ldap_loginfilter_attributes
user_ldap	ldap_loginfilter_email	1
user_ldap	ldap_loginfilter_username	1
user_ldap	ldap_nested_groups	0
user_ldap	ldap_override_main_server
user_ldap	ldap_paging_size	500
user_ldap	ldap_port	389
user_ldap	ldap_quota_attr
user_ldap	ldap_quota_def
user_ldap	ldap_tls	0
user_ldap	ldap_turn_off_cert_check	1
user_ldap	ldap_turn_on_pwd_change	0
user_ldap	ldap_user_display_name_2
user_ldap	ldap_user_filter_mode	1
user_ldap	ldap_userfilter_groups	NextCloudGroup
user_ldap	ldap_userfilter_objectclass	inetOrgPerson
user_ldap	ldap_userlist_filter	(&(|(objectclass=inetOrgPerson))(|(memberof=cn=NextCloudGroup,ou=people,ou=it,dc=roessner-net,dc=de)))
user_ldap	types	authentication
user_ldap	use_memberof_to_detect_membership	1
```

### Client configuration
**Browser:**
Safari

**Operating system:**
macOS Sierra

### Logs
```
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] request to updater
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] currentStep()
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] show HTML page
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] current version: 12.0.2 build time: 2017-08-13T10:45:55+00:00 4a140398a93af53f36eb3c7aa659d09fe7f62f26
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] getUpdateServerResponse()
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] updaterServer: https://updates.nextcloud.org/updater_server/
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] releaseChannel: beta
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] internal version: 12.0.2.0
2017-09-18T13:04:28+0200 ZULFNpmsdM [info] updateURL: https://updates.nextcloud.org/updater_server/?version=12x0x2x0xxxbetaxx2017-08-13T10%3A45%3A55%2B00%3A00+4a140398a93af53f36eb3c7aa659d09fe7f62f26x7x0x22
2017-09-18T13:04:29+0200 ZULFNpmsdM [info] getUpdateServerResponse response: Array
(
    [version] => 12.0.3.1
    [versionstring] => Nextcloud 12.0.3 RC2
    [url] => https://download.nextcloud.com/server/prereleases/nextcloud-12.0.3RC2.zip
    [web] => https://docs.nextcloud.com/server/12/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [signature] => iHTGKqaPhVYw1sxRtaCxUCQms8v5pYaJOfkY5IB/vrDqiFj2FozbNEKbIKt3z2Y0
pDVXh1XYIU74aVq/ktV1NgUczFLyLMYKT7Sn+grd7i2eGL7UQphdqyFgfRALQBuG
J6WCYcEYlzsRRxfYMkcaN3v1bQvBjhsSG5FvsQ4MUwI2MlkfRYyk5+558mhNgdAo
5X/4uBm+29lOWq1YFae6TzQkQjDWln4IOb3LmL6gg/3+5iNV84UhCukEwugHjoCA
nw5jRam2CYrsw5IWfIXVPqLKJckLN1zP3QIrOwLvtjiiWird/SEesWVs/Aefef75
e6hCvGvWtiNUEsJz4h1CiA==
)

2017-09-18T13:04:29+0200 ZULFNpmsdM [info] checkForUpdate() Array
(
    [version] => 12.0.3.1
    [versionstring] => Nextcloud 12.0.3 RC2
    [url] => https://download.nextcloud.com/server/prereleases/nextcloud-12.0.3RC2.zip
    [web] => https://docs.nextcloud.com/server/12/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [signature] => iHTGKqaPhVYw1sxRtaCxUCQms8v5pYaJOfkY5IB/vrDqiFj2FozbNEKbIKt3z2Y0
pDVXh1XYIU74aVq/ktV1NgUczFLyLMYKT7Sn+grd7i2eGL7UQphdqyFgfRALQBuG
J6WCYcEYlzsRRxfYMkcaN3v1bQvBjhsSG5FvsQ4MUwI2MlkfRYyk5+558mhNgdAo
5X/4uBm+29lOWq1YFae6TzQkQjDWln4IOb3LmL6gg/3+5iNV84UhCukEwugHjoCA
nw5jRam2CYrsw5IWfIXVPqLKJckLN1zP3QIrOwLvtjiiWird/SEesWVs/Aefef75
e6hCvGvWtiNUEsJz4h1CiA==
)

2017-09-18T13:04:29+0200 ZULFNpmsdM [info] end of checkForUpdate() Update to Nextcloud 12.0.3 RC2 available. (channel: "beta")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://download.nextcloud.com/server/prereleases/nextcloud-12.0.3RC2.zip</code>
2017-09-18T13:04:33+0200 sxMmMrBihh [info] request to updater
2017-09-18T13:04:33+0200 sxMmMrBihh [info] currentStep()
2017-09-18T13:04:33+0200 sxMmMrBihh [info] POST request for step "1"
2017-09-18T13:04:34+0200 sxMmMrBihh [info] startStep("1")
2017-09-18T13:04:34+0200 sxMmMrBihh [info] checkForExpectedFilesAndFolders()
2017-09-18T13:04:34+0200 sxMmMrBihh [info] end of checkForExpectedFilesAndFolders()
2017-09-18T13:04:34+0200 sxMmMrBihh [info] endStep("1")
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] request to updater
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] currentStep()
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] Step 1 is in state "end".
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] POST request for step "2"
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] startStep("2")
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] checkWritePermissions()
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] end of checkWritePermissions()
2017-09-18T13:04:34+0200 sZVo5CdHP3 [info] endStep("2")
2017-09-18T13:04:34+0200 R8fyigW0zU [info] request to updater
2017-09-18T13:04:34+0200 R8fyigW0zU [info] currentStep()
2017-09-18T13:04:34+0200 R8fyigW0zU [info] Step 2 is in state "end".
2017-09-18T13:04:34+0200 R8fyigW0zU [info] POST request for step "3"
2017-09-18T13:04:34+0200 R8fyigW0zU [info] startStep("3")
2017-09-18T13:04:34+0200 R8fyigW0zU [info] setMaintenanceMode("true")
2017-09-18T13:04:34+0200 R8fyigW0zU [info] configFileName /var/www/localhost/htdocs/nextcloud/updater/../config/config.php
2017-09-18T13:04:34+0200 R8fyigW0zU [info] end of setMaintenanceMode()
2017-09-18T13:04:34+0200 R8fyigW0zU [info] endStep("3")
2017-09-18T13:04:34+0200 bhWl3U8oEo [info] request to updater
2017-09-18T13:04:34+0200 bhWl3U8oEo [info] currentStep()
2017-09-18T13:04:34+0200 bhWl3U8oEo [info] Step 3 is in state "end".
2017-09-18T13:04:34+0200 bhWl3U8oEo [info] POST request for step "4"
2017-09-18T13:04:34+0200 bhWl3U8oEo [info] startStep("4")
2017-09-18T13:04:34+0200 bhWl3U8oEo [info] createBackup()
2017-09-18T13:05:13+0200 bhWl3U8oEo [info] end of createBackup()
2017-09-18T13:05:13+0200 bhWl3U8oEo [info] endStep("4")
2017-09-18T13:05:13+0200 6x3te6iekp [info] request to updater
2017-09-18T13:05:13+0200 6x3te6iekp [info] currentStep()
2017-09-18T13:05:13+0200 6x3te6iekp [info] Step 4 is in state "end".
2017-09-18T13:05:13+0200 6x3te6iekp [info] POST request for step "5"
2017-09-18T13:05:13+0200 6x3te6iekp [info] startStep("5")
2017-09-18T13:05:13+0200 6x3te6iekp [info] downloadUpdate()
2017-09-18T13:05:13+0200 6x3te6iekp [info] getUpdateServerResponse()
2017-09-18T13:05:13+0200 6x3te6iekp [info] updaterServer: https://updates.nextcloud.org/updater_server/
2017-09-18T13:05:13+0200 6x3te6iekp [info] releaseChannel: beta
2017-09-18T13:05:13+0200 6x3te6iekp [info] internal version: 12.0.2.0
2017-09-18T13:05:13+0200 6x3te6iekp [info] updateURL: https://updates.nextcloud.org/updater_server/?version=12x0x2x0xxxbetaxx2017-08-13T10%3A45%3A55%2B00%3A00+4a140398a93af53f36eb3c7aa659d09fe7f62f26x7x0x22
2017-09-18T13:05:13+0200 6x3te6iekp [info] getUpdateServerResponse response: Array
(
    [version] => 12.0.3.1
    [versionstring] => Nextcloud 12.0.3 RC2
    [url] => https://download.nextcloud.com/server/prereleases/nextcloud-12.0.3RC2.zip
    [web] => https://docs.nextcloud.com/server/12/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [signature] => iHTGKqaPhVYw1sxRtaCxUCQms8v5pYaJOfkY5IB/vrDqiFj2FozbNEKbIKt3z2Y0
pDVXh1XYIU74aVq/ktV1NgUczFLyLMYKT7Sn+grd7i2eGL7UQphdqyFgfRALQBuG
J6WCYcEYlzsRRxfYMkcaN3v1bQvBjhsSG5FvsQ4MUwI2MlkfRYyk5+558mhNgdAo
5X/4uBm+29lOWq1YFae6TzQkQjDWln4IOb3LmL6gg/3+5iNV84UhCukEwugHjoCA
nw5jRam2CYrsw5IWfIXVPqLKJckLN1zP3QIrOwLvtjiiWird/SEesWVs/Aefef75
e6hCvGvWtiNUEsJz4h1CiA==
)

2017-09-18T13:05:13+0200 6x3te6iekp [info] storage location exists
2017-09-18T13:05:18+0200 6x3te6iekp [info] end of downloadUpdate()
2017-09-18T13:05:18+0200 6x3te6iekp [info] endStep("5")
2017-09-18T13:05:18+0200 jhhVlEfOs3 [info] request to updater
2017-09-18T13:05:18+0200 jhhVlEfOs3 [info] currentStep()
2017-09-18T13:05:18+0200 jhhVlEfOs3 [info] Step 5 is in state "end".
2017-09-18T13:05:18+0200 jhhVlEfOs3 [info] POST request for step "6"
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] startStep("6")
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] verifyIntegrity()
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] getUpdateServerResponse()
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] updaterServer: https://updates.nextcloud.org/updater_server/
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] releaseChannel: beta
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] internal version: 12.0.2.0
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] updateURL: https://updates.nextcloud.org/updater_server/?version=12x0x2x0xxxbetaxx2017-08-13T10%3A45%3A55%2B00%3A00+4a140398a93af53f36eb3c7aa659d09fe7f62f26x7x0x22
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] getUpdateServerResponse response: Array
(
    [version] => 12.0.3.1
    [versionstring] => Nextcloud 12.0.3 RC2
    [url] => https://download.nextcloud.com/server/prereleases/nextcloud-12.0.3RC2.zip
    [web] => https://docs.nextcloud.com/server/12/admin_manual/maintenance/upgrade.html
    [autoupdater] => 1
    [signature] => iHTGKqaPhVYw1sxRtaCxUCQms8v5pYaJOfkY5IB/vrDqiFj2FozbNEKbIKt3z2Y0
pDVXh1XYIU74aVq/ktV1NgUczFLyLMYKT7Sn+grd7i2eGL7UQphdqyFgfRALQBuG
J6WCYcEYlzsRRxfYMkcaN3v1bQvBjhsSG5FvsQ4MUwI2MlkfRYyk5+558mhNgdAo
5X/4uBm+29lOWq1YFae6TzQkQjDWln4IOb3LmL6gg/3+5iNV84UhCukEwugHjoCA
nw5jRam2CYrsw5IWfIXVPqLKJckLN1zP3QIrOwLvtjiiWird/SEesWVs/Aefef75
e6hCvGvWtiNUEsJz4h1CiA==
)

2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] storage location: /mnt/btrfs/nextcloud/updater-oc6bv5n6btbh/downloads/
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] end of verifyIntegrity()
2017-09-18T13:05:19+0200 jhhVlEfOs3 [info] endStep("6")
2017-09-18T13:05:19+0200 zq1BIx59gb [info] request to updater
2017-09-18T13:05:19+0200 zq1BIx59gb [info] currentStep()
2017-09-18T13:05:19+0200 zq1BIx59gb [info] Step 6 is in state "end".
2017-09-18T13:05:19+0200 zq1BIx59gb [info] POST request for step "7"
2017-09-18T13:05:19+0200 zq1BIx59gb [info] startStep("7")
2017-09-18T13:05:19+0200 zq1BIx59gb [info] extractDownload()
2017-09-18T13:05:19+0200 zq1BIx59gb [info] storage location: /mnt/btrfs/nextcloud/updater-oc6bv5n6btbh/downloads/
2017-09-18T13:05:23+0200 zq1BIx59gb [info] end of extractDownload()
2017-09-18T13:05:23+0200 zq1BIx59gb [info] endStep("7")
2017-09-18T13:05:23+0200 ampqrLwZFn [info] request to updater
2017-09-18T13:05:23+0200 ampqrLwZFn [info] currentStep()
2017-09-18T13:05:23+0200 ampqrLwZFn [info] Step 7 is in state "end".
2017-09-18T13:05:23+0200 ampqrLwZFn [info] POST request for step "8"
2017-09-18T13:05:23+0200 ampqrLwZFn [info] startStep("8")
2017-09-18T13:05:23+0200 ampqrLwZFn [info] replaceEntryPoints()
2017-09-18T13:05:23+0200 ampqrLwZFn [info] replace index.php
2017-09-18T13:05:23+0200 ampqrLwZFn [info] replace status.php
2017-09-18T13:05:23+0200 ampqrLwZFn [info] replace remote.php
2017-09-18T13:05:23+0200 ampqrLwZFn [info] replace public.php
2017-09-18T13:05:23+0200 ampqrLwZFn [info] replace ocs/v1.php
2017-09-18T13:05:23+0200 ampqrLwZFn [info] replace ocs/v2.php
2017-09-18T13:05:23+0200 ampqrLwZFn [info] end of replaceEntryPoints()
2017-09-18T13:05:23+0200 ampqrLwZFn [info] endStep("8")
2017-09-18T13:05:23+0200 qX5fMd5qog [info] request to updater
2017-09-18T13:05:23+0200 qX5fMd5qog [info] currentStep()
2017-09-18T13:05:23+0200 qX5fMd5qog [info] Step 8 is in state "end".
2017-09-18T13:05:23+0200 qX5fMd5qog [info] POST request for step "9"
2017-09-18T13:05:23+0200 qX5fMd5qog [info] startStep("9")
2017-09-18T13:05:23+0200 qX5fMd5qog [info] deleteOldFiles()
2017-09-18T13:05:24+0200 qX5fMd5qog [info] config sample exists
2017-09-18T13:05:24+0200 qX5fMd5qog [info] thmes README exists
2017-09-18T13:05:26+0200 qX5fMd5qog [info] end of deleteOldFiles()
2017-09-18T13:05:26+0200 qX5fMd5qog [info] endStep("9")
2017-09-18T13:05:26+0200 3PVarhDLUh [info] request to updater
2017-09-18T13:05:26+0200 3PVarhDLUh [info] currentStep()
2017-09-18T13:05:26+0200 3PVarhDLUh [info] Step 9 is in state "end".
2017-09-18T13:05:26+0200 3PVarhDLUh [info] POST request for step "10"
2017-09-18T13:05:26+0200 3PVarhDLUh [info] startStep("10")
2017-09-18T13:05:26+0200 3PVarhDLUh [info] moveNewVersionInPlace()
2017-09-18T13:05:26+0200 3PVarhDLUh [info] storage location: /mnt/btrfs/nextcloud/updater-oc6bv5n6btbh/downloads/nextcloud/
2017-09-18T13:05:30+0200 3PVarhDLUh [info] end of moveNewVersionInPlace()
2017-09-18T13:05:30+0200 3PVarhDLUh [info] endStep("10")
2017-09-18T13:05:42+0200 ErbpdOztHz [info] request to updater
2017-09-18T13:05:42+0200 ErbpdOztHz [info] currentStep()
2017-09-18T13:05:42+0200 ErbpdOztHz [info] Step 10 is in state "end".
2017-09-18T13:05:42+0200 ErbpdOztHz [info] POST request for step "11"
2017-09-18T13:05:42+0200 ErbpdOztHz [info] startStep("11")
2017-09-18T13:05:42+0200 ErbpdOztHz [info] setMaintenanceMode("false")
2017-09-18T13:05:42+0200 ErbpdOztHz [info] configFileName /var/www/localhost/htdocs/nextcloud/updater/../config/config.php
2017-09-18T13:05:42+0200 ErbpdOztHz [info] end of setMaintenanceMode()
2017-09-18T13:05:42+0200 ErbpdOztHz [info] endStep("11")
2017-09-18T13:05:42+0200 4IQe47qmTr [info] request to updater
2017-09-18T13:05:42+0200 4IQe47qmTr [info] currentStep()
2017-09-18T13:05:42+0200 4IQe47qmTr [info] Step 11 is in state "end".
2017-09-18T13:05:42+0200 4IQe47qmTr [info] POST request for step "12"
2017-09-18T13:05:42+0200 4IQe47qmTr [info] startStep("12")
2017-09-18T13:05:42+0200 4IQe47qmTr [info] finalize()
2017-09-18T13:05:42+0200 4IQe47qmTr [info] storage location: /mnt/btrfs/nextcloud/updater-oc6bv5n6btbh/downloads/nextcloud/
2017-09-18T13:05:42+0200 4IQe47qmTr [info] call opcache_reset()
2017-09-18T13:05:42+0200 4IQe47qmTr [info] end of finalize()
2017-09-18T13:05:42+0200 4IQe47qmTr [info] endStep("12")
```

#### Web server error log
not applicable, because using command line

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"cli","method":"--","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"cli","method":"--","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Updater::setDebugLogLevel: Set log level to debug","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":0,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 12.0.2.0 to 12.0.3.1","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::info: Repair info: All tables already have the correct collation -> nothing to do","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:35","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::step: Repair step: Copy data from accounts table when migrating from ownCloud","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:36","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::step: Repair step: Drop account terms table when migrating from ownCloud","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:36","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":1,"time":"September 18, 2017 13:27:36","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Updater::dbUpgrade: Updated database","userAgent":"--","version":"12.0.2.0"}
{"reqId":"IoIH3Gh4QxQxtI5DvjQP","level":3,"time":"September 18, 2017 13:27:36","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Class OCA\\User_SAML\\UserBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\\Authentication\\IApacheBackend::getLogoutUrl) at \/var\/www\/localhost\/htdocs\/nextcloud\/apps\/user_saml\/lib\/userbackend.php#34","userAgent":"--","version":"12.0.2.0"}
```

#### Browser log
not applicable, because using command line

**Comment by rullzer** [comment] 2017-09-18 12:11
@LukasReschke fix is in the making right?

**Comment by croessner** [comment] 2017-09-18 12:14
A workaround is to disable the app user_saml (which I did not use so far)

**Comment by LukasReschke** [comment] 2017-09-18 12:15
Duplicate of https://github.com/nextcloud/server/issues/6501

**Closed by LukasReschke** 2017-09-18 12:15 UTC
