### ISSUE TITLE
NC 12 Stable can't revoke app passwords

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#5470] opened 2017-06-19 17:45 UTC
### Steps to reproduce
1. Go to the personal page, and see that the popover menu for revoking app passwords appears in the upper right corner of the screen, right under the avatar. It's not clear which app password this corresponds to.

### Expected behaviour
The popover menu used to appear to the right of the app password when you mouse over it.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:**Apache

**Database:**MariaDB

**PHP version:**7.0

**Nextcloud version:** (see Nextcloud admin page)12.0.0

![image](https://user-images.githubusercontent.com/5169868/27298311-1c1eb928-54f6-11e7-9749-c1422545e3c6.png)

**Comment by patschi** [comment] 2017-06-20 23:36
Can't reproduce this on my NC 12.0.0.29 installation. Could it be a caching problem? Which browser did you use? And did you tired clearing your browser cache (CTRL + F5) or tried any other browser?

**Comment by linucksrox** [comment] 2017-06-21 10:08
I don't think it's related to caching because I've cleared cache multiple times. I've tested in Firefox under Linux, chrome under Windows, and chrome in Android. All of them do this.
I'll download the template file from NC 12 and compare that with mine, maybe I changed something in there accidentally.

**Comment by benbrummer** [comment] 2017-06-21 10:53
I guess if you fail to login several times you will be banned by nextcloud for bruteforce-attack. If you then get an link for new password the user may be still banned?

**Comment by MorrisJobke** [comment] 2017-08-30 09:48
Please run the code integrity check. (it's an occ command)

This returns the changed files. I can't reproduce as well (tested on Firefox, Safari and Chrome).

I will close this for now. Also check what apps you have enabled. Maybe one of them interferes with the popup.

If this is still a problem we can have a dedicated look. Please keep in mind: If you change the code (code integrity check returns some changed files) those needs to be reverted first and then you should have a look if this already fixes the issue.

**Closed by MorrisJobke** 2017-08-30 09:48 UTC
