### ISSUE TITLE
LDAPS shows Password wrong?

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/server#12551] opened 2018-11-20 12:33 UTC
_Originally posted by @ExaconAT in https://github.com/nextcloud/server/issues/11670#issuecomment-440248482_

**Comment by ExaconAT** [comment] 2018-11-20 12:50
Nope

**Comment by danielkesselberg** [comment] 2018-11-20 14:58
Hmm. A new issue as reference to a comment in a another issue is bad. Could you at least update the entry post with all information from the issue template? 

Are u sure that this is a software issue at all? Looks like a configuration issue to me. For those we recommend help.nextcloud.com.

**Comment by ExaconAT** [comment] 2018-11-21 07:20
LDAPS Login should work with the following settings:

Apparently, set ldapExpertUsernameAttr to "cn" and ldapExpertUUIDUserAttr to "uid" makes it work. Close duplicate.

But i get always password wrong when i set this Attributes.

My CNF:

+-------------------------------+----------------------------------------------------+
| Configuration | |
+-------------------------------+----------------------------------------------------+
| hasMemberOfFilterSupport | 1 |
| hasPagedResultSupport | |
| homeFolderNamingRule | |
| lastJpegPhotoLookup | 0 |
| ldapAgentName | rh@dev.local |
| ldapAgentPassword | *** |
| ldapAttributesForGroupSearch | |
| ldapAttributesForUserSearch | |
| ldapBackupHost | |
| ldapBackupPort | |
| ldapBase | dc=dev,dc=local |
| ldapBaseGroups | ou=nc,dc=dev,dc=local |
| ldapBaseUsers | ou=nc,dc=dev,dc=local |
| ldapCacheTTL | 10 |
| ldapConfigurationActive | 1 |
| ldapDefaultPPolicyDN | |
| ldapDynamicGroupMemberURL | |
| ldapEmailAttribute | mail |
| ldapExperiencedAdmin | 0 |
| ldapExpertUUIDGroupAttr | |
| ldapExpertUUIDUserAttr | uid |
| ldapExpertUsernameAttr | cn |
| ldapGidNumber | gidNumber |
| ldapGroupDisplayName | cn |
| ldapGroupFilter | (&(|(objectclass=group))) |
| ldapGroupFilterGroups | |
| ldapGroupFilterMode | 0 |
| ldapGroupFilterObjectclass | group |
| ldapGroupMemberAssocAttr | member |
| ldapHost | ldaps://dev01.dev.local |
| ldapIgnoreNamingRules | |
| ldapLoginFilter | (&(&(|(objectclass=person)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes | |
| ldapLoginFilterEmail | 0 |
| ldapLoginFilterMode | 0 |
| ldapLoginFilterUsername | 1 |
| ldapNestedGroups | 0 |
| ldapOverrideMainServer | |
| ldapPagingSize | 500 |
| ldapPort | 636 |
| ldapQuotaAttribute | |
| ldapQuotaDefault | |
| ldapTLS | 0 |
| ldapUserAvatarRule | default |
| ldapUserDisplayName | displayname |
| ldapUserDisplayName2 | |
| ldapUserFilter | (&(|(objectclass=person))) |
| ldapUserFilterGroups | |
| ldapUserFilterMode | 0 |
| ldapUserFilterObjectclass | person |
| ldapUuidGroupAttribute | auto |
| ldapUuidUserAttribute | auto |
| turnOffCertCheck | 0 |
| turnOnPasswordChange | 1 |
| useMemberOfToDetectMembership | 1 |
+-------------------------------+----------------------------------------------------+

**Comment by MorrisJobke** [comment] 2019-03-25 12:41
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-03-25 12:41 UTC
Labels: bug, needs info
