### ISSUE TITLE
[Bug]: Error: `exif_read_data(): File not supported at /var/www/html/lib/private/Metadata/Provider/ExifProvider.php#59`

### ISSUE THREAD

**Issue by JuanRodenas** [nextcloud/server#35725] opened 2022-12-10 22:54 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating the nextcloud:production-fpm image, it throws an error:

Error: exif_read_data(): File not supported at /var/www/html/lib/private/Metadata/Provider/ExifProvider.php#59

### Steps to reproduce

1. When uploading files.

### Expected behavior

Nextcloud crashes.

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "htaccess.RewriteBase": "\/",
        "default_phone_region": "ES",
        "force_language": "es",
        "default_locale": "es_ES",
        "force_locale": "es_ES",
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto",
        "auth.bruteforce.protection.enabled": true,
        "bulkupload.enabled": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.1.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - deck: 1.8.2
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - music: 1.7.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - circles: 25.0.0
  - dashboard: 7.5.0
  - encryption
  - federation: 1.15.0
  - files_external
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login
  - systemtags: 1.15.0
  - user_ldap
  - user_status: 1.5.0
  - weather_status: 1.5.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Error: exif_read_data(): File not supported at /var/www/html/lib/private/Metadata/Provider/ExifProvider.php#59

    <<closure>>

    OC\Log\ErrorHandler::onError(2, "exif_read_d ... d", "/var/www/ht ... p", 59)

    /var/www/html/lib/private/Metadata/Provider/ExifProvider.php - line 59:

    exif_read_data(null, "ANY_TAG", true)

    /var/www/html/lib/private/Metadata/MetadataManager.php - line 68:

    OC\Metadata\Provider\ExifProvider->execute(OC\Files\Node\File {})

    /var/www/html/lib/private/Metadata/FileEventListener.php - line 101:

    OC\Metadata\MetadataManager->generateMetadata(OC\Files\Node\File {}, false)

    /var/www/html/lib/private/EventDispatcher/ServiceEventListener.php - line 87:

    OC\Metadata\FileEventListener->handle(OCP\Files\Ev ... {})

    /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 251:

    OC\EventDispatcher\ServiceEventListener->__invoke(OCP\Files\Ev ... {}, "OCP\\Files\ ... t", Symfony\Comp ... {})

    /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:

    Symfony\Component\EventDispatcher\EventDispatcher->callListeners([ Closure {}], "OCP\\Files\ ... t", OCP\Files\Ev ... {})

    /var/www/html/lib/private/EventDispatcher/EventDispatcher.php - line 88:

    Symfony\Component\EventDispatcher\EventDispatcher->dispatch(OCP\Files\Ev ... {}, "OCP\\Files\ ... t")

    /var/www/html/lib/private/EventDispatcher/EventDispatcher.php - line 100:

    OC\EventDispatcher\EventDispatcher->dispatch("OCP\\Files\ ... t", OCP\Files\Ev ... {})

    /var/www/html/lib/private/Files/Node/HookConnector.php - line 118:

    OC\EventDispatcher\EventDispatcher->dispatchTyped(OCP\Files\Ev ... {})

    /var/www/html/lib/private/legacy/OC_Hook.php - line 106:

    OC\Files\Node\HookConnector->postWrite([ "/Photos/I ... "])

    /var/www/html/apps/dav/lib/Connector/Sabre/File.php - line 471:

    OC_Hook::emit("OC_Filesystem", "post_write", [ "/Photos/I ... "])

    /var/www/html/apps/dav/lib/Connector/Sabre/File.php - line 398:

    OCA\DAV\Connector\Sabre\File->emitPostHooks(false)

    /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php - line 151:

    OCA\DAV\Connector\Sabre\File->put(null)

    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1098:

    OCA\DAV\Connector\Sabre\Directory->createFile("kisspng-ras ... g", null)

    /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 504:

    Sabre\DAV\Server->createFile("Photos/Imag ... g", null, null)

    /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

    Sabre\DAV\Server->emit("method:PUT", [ Sabre\HTTP ... }])

    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

    /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

    Sabre\DAV\Server->start()

    /var/www/html/apps/dav/appinfo/v1/webdav.php - line 85:

    Sabre\DAV\Server->exec()

    /var/www/html/remote.php - line 171:

    require_once("/var/www/ht ... p")
```

### Additional info

We want the image: nextcloud:production-fpm
Back to 24.0.8. We had no problems with it.

**Comment by solracsf** [comment] 2022-12-12 09:52
Duplicate of https://github.com/nextcloud/server/issues/34958

**Closed by solracsf** 2022-12-12 09:52 UTC
Labels: bug, 0. Needs triage, 25-feedback
