### ISSUE TITLE
Nextcloud 13: Can't bundle-select (shift-select) files

### ISSUE THREAD

**Issue by smirkybg** [nextcloud/server#8323] opened 2018-02-13 09:16 UTC
### Steps to reproduce
1. Go to a list of files
2. Select one file
3. Try to shift-select (bundle select) a couple of files

### Expected behaviour
I expect to select multiple files, which was actually working on previous versions, prior to Nextcloud 13

### Actual behaviour
When selecting with shift is just like selecting without it.

### Server configuration

**Operating system**:
Archlinux

**Web server:**
Nginx 1.13.7

**Database:**
MariaDB 10.1.31

**PHP version:**
php-fpm 7.2.2

**Nextcloud version:**
13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 12

**Where did you install Nextcloud from:**
Distro package

```
http://example.com/index.php/settings/integrity/failed 

No errors have been found.
```
</details>

**List of activated apps:**
Reproducible with enabled and fully disabled apps.

**Nextcloud configuration:**
not applicable

### Client configuration
**Browser:**
Firefox, Chromium

**Operating system:**
Linux

### Logs
Irrelevant

#### Web server error log
Irrelevant

#### Nextcloud log (data/nextcloud.log)
Irrelevant

#### Browser log
Not sure, I guess irrelevant.

**Comment by MorrisJobke** [comment] 2018-02-13 10:12
Yes - this was not yet implemented and we got already a similar request.

I will close this as duplicate of #3484

**Closed by MorrisJobke** 2018-02-13 10:12 UTC

**Comment by smirkybg** [comment] 2018-02-13 10:13
Apologies for the duplication.

**Comment by MorrisJobke** [comment] 2018-02-13 10:33
> Apologies for the duplication.

Don't worry - that's what we are for ;)
