### ISSUE TITLE
[Feature request] Add admin function to clear all pending database password throttling entries

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#14163] opened 2019-02-12 15:36 UTC
I propose to have an additional admin tool, 

- in the Admin Web panel ; and/or
- at least as a new "occ" function

with which an admin would be able to delete all pending password-login throttling entries in the database.

**Comment by MorrisJobke** [comment] 2019-02-12 22:22
Duplicate of #3058

**Closed by MorrisJobke** 2019-02-12 22:22 UTC
Labels: 0. Needs triage, enhancement, feature: admin audit, feature: occ, good first issue
