### ISSUE TITLE
Error: A session had already been started - ignoring at

### ISSUE THREAD

**Issue by LHollyfeld** [nextcloud/server#20770] opened 2020-05-01 12:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. after logout 19.0.0Beta6
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
MySql
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
19.0.0.Beta6
**Updated from an older Nextcloud/ownCloud or fresh install:**
18.0.4
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
{"reqId":"ByVzFPeKqNDOnuue0yyA","level":3,"time":"2020-05-01T14:49:58+02:00","remoteAddr":"192.168.10.180","user":"--","app":"PHP","method":"GET","url":"/nextcloud/index.php/logout?requesttoken=q82stA6CUHQqLEFs8p7M5OEUxVfpf8jbmWjp4saeVO0%3D%3AwqmZ7T%2FJEg1%2FRhNVx8eWj9BOnyOsLJ30yF3ClbOsAZ8%3D","message":"session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"19.0.0.7"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LHollyfeld** [comment] 2020-05-07 09:18
Again error by logout in NC 19.0.0.RC1

{"reqId":"MnUwaHgxg7w5omKecATO","level":3,"time":"2020-05-07T11:11:02+02:00","remoteAddr":"192.168.10.180","user":"--","app":"PHP","method":"GET","url":"/nextcloud/index.php/logout?requesttoken=YNe1ZySKtuYjviG0HMzMLBSXe%2FdwMxcJaBUPoqFRnrU%3D%3AUJDnLFH44JNzxwrcZYb9ByziFsAYA3Y4Hls62%2FFo5vM%3D","message":"session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0","version":"19.0.0.9"}

**Comment by LHollyfeld** [comment] 2020-05-14 16:25
Again error by logout in NC 19.0.0.RC2

**Comment by LHollyfeld** [comment] 2020-05-21 08:45
Again error by logout in NC 19.0.0.RC3

{"reqId":"KuxDqeDxmGodYQMDvzC1","level":3,"time":"2020-05-21T10:42:29+02:00","remoteAddr":"192.168.10.180","user":"--","app":"PHP","method":"GET","url":"/nextcloud/index.php/logout?requesttoken=715wRovrKhkQtK%2BbA2T6Ns9y%2FH%2F6Va2chFfUroJ2L4o%3D%3AiAc9HryuG15WwuPLWyepfo0gqyajNsury2XjmMcSY7M%3D","message":"session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0","version":"19.0.0.11","id":"5ec63f1861884"}

**Comment by kesselb** [comment] 2020-05-22 12:55
Thanks :+1: 

Closing as duplicate of https://github.com/nextcloud/server/issues/20490.

**Closed by kesselb** 2020-05-22 12:55 UTC
Labels: 0. Needs triage, bug
