### ISSUE TITLE
[Bug]: Filepicker not loading in legacy view for public link shares

### ISSUE THREAD

**Issue by Fenn-CS** [nextcloud/server#46961] opened 2024-08-01 16:30 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Filepicker not loading in legacy view for public link shares

![filepicker-not-loading](https://github.com/user-attachments/assets/a76edafd-7ad8-4fde-9ff3-a3c22548a01c)

### Steps to reproduce

1. Create folder and inside create a markdown file
2. Share as link with edit permissions
3. Open the share link in private tab or other browser
4. Select the file and go to "…" menu and select "Move or copy"
5. See "loading file picker" being shown all the time

In the browser network log there is a PROPFIND /public.php/dav/files/TOKEN/ instead of PROPFIND /public.php/webdav/ and the token being used in authentication.

### Expected behavior

File picker should load relative (public) root

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment] 2024-08-02 00:24
Duplicate of https://github.com/nextcloud/server/issues/45888

**Closed by susnux** 2024-08-02 00:24 UTC
Labels: bug, 2. developing, 28-feedback
