### ISSUE TITLE
Update from 12.0.0 to 12.0.1 failed to enable notifications app

### ISSUE THREAD

**Issue by amo13** [nextcloud/server#6055] opened 2017-08-09 19:39 UTC
### Steps to reproduce
1. Hit update in the integrated updater app
2. continue to finish the update with web interface (fails because of notifications app)
3. actually finish the update using occ command (mentions problem with notifications app but finishes the update)
4. notifications app was listed as enabled in the apps menu. Had to click disable twice to disable it. First click on enable did nothing, second gave me the error pasted in the log part below. 

### Server configuration

**Operating system**: archlinux armv7

**Web server:** apache

**Database:** sqlite

**PHP version:** latest

**Nextcloud version:** now 12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 12.0.0

**Where did you install Nextcloud from:** package manager (now set nextcloud to be ignored by pacman as it might be better (is it?) to use internal updater app)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - oauth2: 1.0.5
  - ocsms: 1.12.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - firstrunwizard
  - notifications
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "occvnayusxpv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/usr\/share\/webapps\/nextcloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***\/nextcloud",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "dbtype": "sqlite3",
        "version": "12.0.1.5",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "amaury",
        "mail_domain": "mailbox.org",
        "mail_smtphost": "smtp.mailbox.org",
        "mail_smtpport": "465",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no, only a HDD partition directly mounted into nextcloud/data

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** firefox 55.0

**Operating system:** archlinux 

#### Web server error log
<details>
<summary>Web server error log</summary>

```
An exception occurred while executing 'CREATE TABLE "oc_notifications" ("notification_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "app" VARCHAR(32) NOT NULL, "user" VARCHAR(64) NOT NULL, "timestamp" INTEGER DEFAULT 0 NOT NULL, "object_type" VARCHAR(64) NOT NULL, "object_id" VARCHAR(64) NOT NULL, "subject" VARCHAR(64) NOT NULL, "subject_parameters" CLOB DEFAULT NULL, "message" VARCHAR(64) DEFAULT NULL, "message_parameters" CLOB DEFAULT NULL, "link" VARCHAR(4000) DEFAULT NULL, "icon" VARCHAR(4000) DEFAULT NULL, "actions" CLOB DEFAULT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_notifications" already exists
```
No other logs appear on the admin page under logging (warning, error, fatal).
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XyFRfO1jJUnSoXbQp2P5","level":3,"time":"2017-08-09T19:01:12+00:00","remoteAddr":"141.51.21.138","user":"amo","app":"core","method":"POST","url":"\/cloud\/index.php\/settings\/ajax\/enableapp.php","message":"An exception occurred while executing 'CREATE TABLE \"oc_notifications\" (\"notification_id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, \"app\" VARCHAR(32) NOT NULL, \"user\" VARCHAR(64) NOT NULL, \"timestamp\" INTEGER DEFAULT 0 NOT NULL, \"object_type\" VARCHAR(64) NOT NULL, \"object_id\" VARCHAR(64) NOT NULL, \"subject\" VARCHAR(64) NOT NULL, \"subject_parameters\" CLOB DEFAULT NULL, \"message\" VARCHAR(64) DEFAULT NULL, \"message_parameters\" CLOB DEFAULT NULL, \"link\" VARCHAR(4000) DEFAULT NULL, \"icon\" VARCHAR(4000) DEFAULT NULL, \"actions\" CLOB DEFAULT NULL)':\n\nSQLSTATE[HY000]: General error: 1 table \"oc_notifications\" already exists","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.1.5"}
{"reqId":"tdUZOXVXViN3S6D31go7","level":0,"time":"2017-08-09T19:05:11+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Finished OC\\Command\\CommandJob job with ID 1502 in 835 seconds","userAgent":"--","version":"12.0.1.5"}
```
</details>

I might have to mention:
- just set up redis and activated it before update (everything went fine according to the logging page)
- just changed from ajax to cron (using systemd) before update (everything went fine)
- updater was unhappy with some missing write permissions, therefore I did a radical chown -R http:http /usr/share/webapps/nextcloud (and kept it that way for now - I was unable to find a guidance on how the file permissions have to be set for the nextcloud installation directory)

**Comment by MorrisJobke** [comment] 2017-09-03 17:10
cc @nickvergessen

**Comment by nickvergessen** [comment] 2017-09-06 14:33
Hmm one more major version, then we have migrations and this will not happen anymore,.... finally ...

**Comment by MorrisJobke** [comment] 2017-12-18 19:33
The root cause will be fixed with 13+ by using migrations.

**Closed by MorrisJobke** 2017-12-18 19:33 UTC
Labels: bug, feature: install and update
