### ISSUE TITLE
Add UPS state to the system state page

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#39408] opened 2023-07-15 13:09 UTC
Hi! The System state page gives quite comprehensive data on current state of the server serving the cloud.
Would that be possible to add the section on current state of UPS there, if it is used? 
The data can be pipelined from apcups daemon eg. For admins this may be quite useful and helpful.

Many thanks!

**Comment by joshtrichards** [comment] 2023-07-15 16:09
Duplicate of https://github.com/nextcloud/serverinfo/issues/290

Alternative: `apcupsd` and `NUT` already have their own (optional) web interfaces for status monitoring.

**Comment by ostasevych** [comment] 2023-07-15 17:07
> Duplicate of [nextcloud/serverinfo#290](https://github.com/nextcloud/serverinfo/issues/290)
> 
> Alternative: `apcupsd` and `NUT` already have their own (optional) web interfaces for status monitoring.

Well, on a serverinfo you are also duplicating, let's say, webmin interface, if installed. The matter is to place on one page the most reasonable data which relate to the functionality of hardware serving the instance. In my opinion, UPS state may be useful for that. 

Alternatively I suggest to add API layers to the serverinfo page, so it will be possible to have some plugins or extensions, which may allow to place all the necessary data there upon the need of an admin, and provide notifications when the state of hardware changes.

**Closed** 2023-07-15 20:31 UTC
Labels: enhancement, 0. Needs triage

**Comment by kesselb** [comment] 2023-07-15 20:32
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
