### ISSUE TITLE
Error in Code Integrity Check: direct_menu

### ISSUE THREAD

**Issue by Naspyy** [nextcloud/server#5146] opened 2017-05-28 12:06 UTC
### Steps to reproduce
1. Upgrade Nextcloud 11.0.0 to 12.0.0 using the upgrade function in /upgrade
2. Login to /index.php/settings/admin

### Expected behaviour
Fine upgrade without any errors.

### Actual behaviour
Error in Code Integrity Check

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- direct_menu
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [direct_menu] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)
```

### Server configuration

**Operating system**: Debian 8

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.5.6

**Nextcloud version:** (see Nextcloud admin page) 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Yes, 11.0.0 as stated above

**Where did you install Nextcloud from:** SSH

**Signing status:**
<details>
<summary>Signing status</summary>

```
see above
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - bruteforcesettings: 1.0.2
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - workflowengine: 1.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '******',
  'passwordsalt' => '******',
  'secret' => '******',
  'trusted_domains' => 
  array (
    0 => 'cloud.******',
  ),
  'datadirectory' => '/opt/******',
  'overwrite.cli.url' => 'https://******',
  'dbtype' => 'mysql',
  'version' => '12.0.0.29',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => '******',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '******',
  'mail_domain' => '******',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.mailgun.org',
  'mail_smtpport' => '587',
  'mail_smtpname' => '******',
  'mail_smtppassword' => '******',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'loglevel' => 0,
);

```
</details>

**Are you using external storage, if yes which one:** Dropbox

**Are you using encryption:** Yes?

**Are you using an external user-backend, if yes which one:** No?

```
                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.          
                                                            
```
</details>

### Client configuration
**Browser:** latest Chrome

**Operating system:** Win7

#### Web server error log
<details>
<summary>Web server error log</summary>

```
-- too many private informations --
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"F5VYpNUniIM9on0L5H\/N","remoteAddr":"162.158.88.77","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_Naspyy\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'cloud'@'localhost' for table 'user'","level":3,"time":"2017-03-13T21:16:23+00:00","method":"POST","url":"\/index.php","user":"--","version":"11.0.0.10"}
{"reqId":"F5VYpNUniIM9on0L5H\/N","remoteAddr":"162.158.88.77","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given object name is invalid\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(892): OC\\\\Activity\\\\Event->setObject('files', 2, false)\\n#1 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(184): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('Naspyy', 'created_self', Array, 2, false, true, true, 0, 'file_created')\\n#2 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(111): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/', 'file_created', 'created_self', 'created_by')\\n#3 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(45): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Files\\\/View.php(1237): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#7 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Files\\\/View.php(1163): OC\\\\Files\\\\View->runHooks(Array, '\\\/Naspyy\\\/files', true)\\n#8 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Files\\\/View.php(266): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/Naspyy\\\/files', Array)\\n#9 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(149): OC\\\\Files\\\\View->mkdir('\\\/Naspyy\\\/files')\\n#10 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(380): OC\\\\Files\\\\Node\\\\Folder->newFolder('\\\/Naspyy\\\/files')\\n#11 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('Naspyy')\\n#12 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#14 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Server.php(948): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('Naspyy')\\n#15 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/User\\\/Session.php(411): OC\\\\Server->getUserFolder('Naspyy')\\n#16 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/User\\\/Session.php(479): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#17 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/User\\\/Session.php(299): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#18 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Setup.php(393): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#19 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/core\\\/Controller\\\/SetupController.php(65): OC\\\\Setup->install(Array)\\n#20 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/base.php(957): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#21 \\\/var\\\/www\\\/naspyy\\\/cloud\\\/index.php(40): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/naspyy\\\/cloud\\\/lib\\\/private\\\/Activity\\\/Event.php\",\"Line\":401}","level":3,"time":"2017-03-13T21:16:32+00:00","method":"POST","url":"\/index.php","user":"Naspyy","version":"11.0.0.10"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.0
```
</details>

**Comment by juliushaertl** [comment] 2017-05-28 12:15
Duplicate of https://github.com/nextcloud/server/issues/4679

Just remove the direct_menu app since it is not compatible with 12.
See: https://github.com/juliushaertl/direct_menu#known-issues

**Closed by juliushaertl** 2017-05-28 12:15 UTC
