### ISSUE TITLE
error by mounting hidden samba directories

### ISSUE THREAD

**Issue by pgollor** [nextcloud/server#16182] opened 2019-07-01 20:48 UTC
### Steps to reproduce

We are mounting samba shares from a windows server. The access via the web ui works for normal folder.
But the access for hidden shares with a `$` at the end doesn't work any more via the web ui (for older Versions it worked). The error message is `Mount configuration incomplete. Do you want to review mount point config in admin settings page?`.
The synchronisation by the nextcloud clients for windows, linux and android works pretty good for hidden folders. So there is no login issue or so.

I give you an example for better understanding
In our configuration we hide all user shares by naming the user folders like `username$`. I add a external storage like with:

| option | value |
|---------|---------|
| Foldername | Home |
| Host | servername |
| Share | firstname.lastname$ |

After that I get an folder named `Home` and the access to this folder via the clients working good, but not via the web ui.
**BUT** if I type `https://cloud.servername.com/apps/files/?dir=/Home` it works too.
So I think this is a link bug by clicking on `Home` via the web gui.

### Expected behaviour

Opening the share folder by clicking it in the web front end produce the following error message:
`Mount configuration incomplete.`

### Actual behaviour

The folder should open and should showing the content.

### Server configuration

**Operating system**:
debian

**Web server:**
docker based nginx-alpine

**Database:**
docker based mariadb 10.3

**PHP version:**
docker based nextcloud:fpm

**Nextcloud version:**
docker based 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated via stable path

**Where did you install Nextcloud from:**
docker

**List of activated apps:**
- External storage support 1.7.0

**Are you using external storage, if yes which one:**
smb

### Client configuration

**Browser:** firefox, opera

**Operating system:** windows, linux

**Comment by kesselb** [comment] 2019-07-01 20:52
Thank you for reporting this issue :+1: 

Duplicate of #15567. Patch is already under review: https://github.com/nextcloud/server/pull/15637.

**Closed by kesselb** 2019-07-01 20:52 UTC

**Comment by pgollor** [comment] 2019-07-01 20:55
thanks and sorry

**Comment by kesselb** [comment] 2019-07-01 21:00
No need to apologize :smile: Thank you for your detailed bug report :+1:
