### ISSUE TITLE
External user support is not supported for nextcloud15. How to update it manually

### ISSUE THREAD

**Issue by 330201818** [nextcloud/server#13259] opened 2018-12-25 15:54 UTC
External user support is not supported for nextcloud15. How to update it manually
![cw](https://user-images.githubusercontent.com/15013924/50424529-74dde700-08a0-11e9-8bf6-4e0614004d85.png)

**Comment by violoncelloCH** [comment] 2018-12-25 20:44
duplicate of #12506
will be fixed with 15.0.1 or maybe earlier if we will update it over the appstore in the future (see nextcloud/user_external#22)

**Closed** 2018-12-25 20:44 UTC
Labels: 0. Needs triage, bug
