### ISSUE TITLE
[Bug]: NC 29.0.3 - Renaming a files results in unintentionally opening it

### ISSUE THREAD

**Issue by resoli** [nextcloud/server#46200] opened 2024-06-28 17:30 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to rename a file, clicking in the name field opens the file instead of positioning the cursor.

Video: https://video.resolutions.it/w/pNns138AppAUCQknVXRU9A 

### Steps to reproduce

Open contextual menu, click on rename item, click on the edit field. The file suddenly opens.

### Expected behavior

I should be able to edit the name.

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by MartinSfromB** [comment] 2024-06-28 17:55
Same here.

**Comment by solracsf** [comment] 2024-06-28 19:43
Duplicate of https://github.com/nextcloud/server/issues/46132

**Closed by solracsf** 2024-06-28 19:43 UTC
Labels: bug, 0. Needs triage, 29-feedback
