### ISSUE TITLE
Resharing a password protected folder by e-mail leads to an error and incorrect notifications

### ISSUE THREAD

**Issue by AndrinS** [nextcloud/server#8523] opened 2018-02-23 12:08 UTC
### Steps to reproduce
1. Setup and share a folder to a group.
2. Switch to a user who receives the share.
3. Reshare a sub folder by e-mail.
4. Protect the folder with a password by showing more options.

Make sure the default sharing configuration is set:

**Share by mail:** 
```
Checked: Send password by mail
Unchecked: enforce password protection
```

### Expected behaviour

- Password will be accepted and the recipient will get another email with the password.
- The folder will be password protected

### Actual behaviour

- Password will not be rejected: `"The given object name is invalid"`
- Multiple emails with the defined password are sent out.
- Folder is still unprotected.

### Server configuration

**Operating system:** Debian 8

**Web server:** apache2

**Database:** MariaDB 10.1.26

**PHP version:** 7.0.27-1

**Nextcloud version:** 13.0.0, same on multiple 12.x.x versions

**Updated from an older Nextcloud/ownCloud or fresh install:** both

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - workflowengine: 1.3.0
</details>

### Client configuration
**Browser:** Chrome / Firefox

### Logs
As far as I see, nothing is written in the logs.

**Comment by blizzz** [comment] 2018-02-26 16:25
@nextcloud/sharing

**Comment by jospoortvliet** [comment] 2018-07-04 12:55
Possibly related to https://github.com/nextcloud/server/issues/7469

**Comment by skjnldsv** [comment] 2020-08-25 09:27
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:27 UTC
Labels: 0. Needs triage, bug, feature: sharing
