### ISSUE TITLE
File versioning function not working

### ISSUE THREAD

**Issue by tleydxdy** [nextcloud/server#13773] opened 2019-01-23 22:22 UTC
### Steps to reproduce
1. open details for a file
2. select versions, nothing appears
3. select something else, works normally
4. select versions, the panel gets cleared, but nothing appears

### Expected behaviour
right panel lists versions

### Actual behaviour
right panel is empty

### Server configuration

**Operating system**: debian 9

**Web server:** nginx

**Database:**postgesql

**PHP version:** php7.0

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** almost fresh install/perhaps upgraded from 15.0

**Where did you install Nextcloud from:** zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - contacts: 3.0.2
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.1
  - serverinfo: 1.5.0
  - spreed: 5.0.1
  - survey_client: 1.3.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - sharebymail
  - support
  - systemtags
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MANUAL REMOVE"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "15.0.2.0",
        "overwrite.cli.url": "MANUAL REMOVE",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "data-fingerprint": "c3532717c928edf4031883aef24bc1b0",
        "theme": "",
        "loglevel": 2
    }
}

</details>

**Are you using external storage, if yes which one:** Nope

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Nope

### Client configuration
**Browser:** firefox 64.0.2

**Operating system:** Arch GNU/Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
2019/01/23 07:28:59 [error] 29583#29583: *2923606 access forbidden by rule, client: IP, server: domain.com, request: "GET /data/.ocdata?t=1548246539027 HTTP/2.0", host: "domain.com"
2019/01/23 07:29:28 [error] 29583#29583: *2923606 access forbidden by rule, client: IP, server: domain.com, request: "GET /data/.ocdata?t=1548246567475 HTTP/2.0", host: "domain.com"
2019/01/23 12:13:33 [error] 29583#29583: *3060877 access forbidden by rule, client: IP, server: domain.com, request: "GET /data/.ocdata?t=1548263612471 HTTP/2.0", host: "domain.com"
2019/01/23 12:13:34 [error] 29583#29583: *3060877 access forbidden by rule, client: IP, server: domain.com, request: "GET /.well-known/dnt-policy.txt HTTP/2.0", host: "domain.com"
2019/01/23 17:04:37 [error] 29583#29583: *3243647 access forbidden by rule, client: IP, server: domain.com, request: "GET /data/.ocdata?t=1548281077289 HTTP/2.0", host: "domain.com"
2019/01/23 17:04:45 [error] 29583#29583: *3243647 access forbidden by rule, client: IP, server: domain.com, request: "GET /data/.ocdata?t=1548281085415 HTTP/2.0", host: "domain.com"
2019/01/23 17:07:31 [error] 29583#29583: *3243647 access forbidden by rule, client: IP, server: domain.com, request: "GET /data/.ocdata?t=1548281251588 HTTP/2.0", host: "domain.com"

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>

#### Browser log
<details>
<summary>Browser log</summary>
No error related to this. 
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
TypeError: this.sync is not a function[Learn More] core.js:2101:14
	fetch https://domain.com/core/vendor/core.js:2101:14
	nextPage https://domain.com/js/files_versions/merged.js:270:4
	setFileInfo https://domain.com/js/files_versions/merged.js:360:5
	selectTab https://domain.com/js/files/merged-index.js:9972:4
	_onClickTab https://domain.com/js/files/merged-index.js:9876:4
	_onClickTab self-hosted:974:17
	dispatch https://domain.com/core/vendor/core.js:3:6414
	add/r.handle https://domain.com/core/vendor/core.js:3:3224

</details>

**Comment by DriverXX** [comment] 2019-01-25 22:07
I also have this issue!

**Comment by skjnldsv** [comment] 2019-06-04 10:28
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-04 10:28 UTC
Labels: 0. Needs triage, bug
