### ISSUE TITLE
[Bug]: Delete folder or delete file not translated anymore in 27.1.7

### ISSUE THREAD

**Issue by arno4000** [nextcloud/server#44159] opened 2024-03-12 12:53 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Nextcloud 27.1.7 the button "delete folder" or "delete file" is not translated anymore. I have tested this with both "Deutsch (Sie)" und "Deutsch (Du)". I don't know if any other languages are affected.

![image](https://github.com/nextcloud/server/assets/50365065/d7ab3037-e210-4bd4-a988-1069008ee914)

### Steps to reproduce

1. Install Nextcloud 27.1.7
2. Set it to German
3. Open the context menu of a file or of a folder
4. See that everything is in German except the delete button

### Expected behavior

The delete button is also translated to German.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Fresh install (docker run --rm -p 8080:80 nextcloud:27.1.7-apache)
```

### List of activated Apps

```shell
Fresh install (docker run --rm -p 8080:80 nextcloud:27.1.7-apache)
```

### Nextcloud Signing status

```shell
Fresh install (docker run --rm -p 8080:80 nextcloud:27.1.7-apache)
```

### Nextcloud Logs

```shell
Fresh install (docker run --rm -p 8080:80 nextcloud:27.1.7-apache)
```

**Comment by solracsf** [comment] 2024-03-12 23:14
Duplicate of https://github.com/nextcloud/server/issues/43947

**Closed by solracsf** 2024-03-12 23:14 UTC
Labels: bug, 0. Needs triage, 27-feedback
