### ISSUE TITLE
[Bug]: no mail received for external domain

### ISSUE THREAD

**Issue by Sicoval31** [nextcloud/server#32156] opened 2022-04-26 09:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Afet entering a valid email (mine for exple) and vlic on the mail icon, share is validate but, no mail received !
I try with my mails (yahoo, goole or outlook)  : no mail
I try with my pro mail (my nextcloud account) : it's works.

since the last updates, no mail seems sent to external mail.

I use the **snap** nextcloud with auto update (nextcloud hub II V23.0.3)
Cron is active and works
Try to deactive and reactive plugin  :no more effect

### Steps to reproduce

1. enter valid mail and validate (myemail@yahoo.fr ou myemail@google.com or myemail@outlook.fr)
2. check in my inbox : no mail
3. verify our altospam : no mail sent
4. verify log (snap log ...) : see no error

### Expected behavior

after share by mail, à mail with the share link must be received.
Works in previuosly nextcloud version (V21 or 22)

### Installation method

Official SNAP package

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "default_phone_region": "FR",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "onlyoffice": {
            "verify_peer_off": true
        },
        "allow_local_remote_servers": true,
        "data-fingerprint": "c109c934d73c793c206abfd5733fdeab",
        "theming": {
            "color": "#F78E1E"
        },
        "theming:color": {
            "F78E1E": ""
        },
        "theming:color=F78E1E": ""
    }
}
```

### List of activated Apps

```shell
- accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - announcementcenter: 6.1.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - collectives: 1.0.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - documentserver_community: 0.1.12
  - drawio: 1.0.2
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_automatedtagging: 1.13.0
  - files_downloadactivity: 1.13.0
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.4.0
  - files_retention: 1.12.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - forms: 2.5.0
  - groupfolders: 11.1.2
  - groupquota: 0.1.8
  - guests: 2.2.0
  - libresign: 4.0.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.3.2
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.6.1
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.14.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - user_usage_report: 1.7.0
  - viewer: 1.7.0
  - w2g2: 3.3.8
  - weather_status: 1.3.0
  - workflow_pdf_converter: 1.8.0
  - workflow_script: 1.8.0
  - workflowengine: 2.5.0
Disabled:
  - encryption
  - federation: 1.9.0
  - files_external: 1.13.0
  - firstrunwizard: 2.7.0
  - richdocuments: 5.0.3
  - richdocumentscode: 21.11.306
  - socialsharing_email: 2.5.0
  - survey_client: 1.5.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

Try to disable "share_by_mail" plugin  : no mail received

**Comment by szaimen** [comment] 2022-04-26 09:34
hello, what is your `mail_smtphost`?

**Comment by Sicoval31** [comment] 2022-04-26 09:37
the SMTP works, **test email received**.
It's our own exchange server on our lan.
The nextcloud server is on our lan too. Same network. No problem with that unfortunately.

**Comment by szaimen** [comment] 2022-04-26 09:39
then probably your mail server is simply marked as spam on the big mail providers because I cannot reproduce the problem.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by Sicoval31** [comment] 2022-04-26 09:39
I just received a mail from our nextcloud on my nextcloud users's bind email. SO, it's works.
Just external email doesn't received email.
Try to add my ext. email in a circle : no more mail received :(

**Closed by szaimen** 2022-04-26 09:39 UTC
Labels: bug, needs info, 0. Needs triage

**Comment by Sicoval31** [comment] 2022-04-26 10:18
No support exist for a server install, only by users ... huge price doesn't reflect the necessity for entreprise.

**Comment by Sicoval31** [comment] 2022-04-26 14:56
Works  ! 
I just add a noreply@mondomaine.fr as sender in the mail parameters instead of the empty fields by default.
