### ISSUE TITLE
PHP Error: session_start(): A session had already been started /nextcloud/lib/private/Session/Internal.php#209

### ISSUE THREAD

**Issue by nooblag** [nextcloud/server#21742] opened 2020-07-08 04:50 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Not sure; though errors are appearing in log.

### Actual behaviour
Following errors in Nextcloud log:

![Capture](https://user-images.githubusercontent.com/1122344/86877497-5bbb2500-c12a-11ea-9c57-6be5f5b7a496.PNG)

### Server configuration

**Operating system:**
Ubuntu 18.0.4 LTS

**Web server:**
nginx 1.16.1

**Database:**
psql (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

**PHP version:**
PHP 7.4.7-fpm

**Nextcloud version:**
19.0.0.12

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0.6

**Where did you install Nextcloud from:**
nextcloud.com

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - announcementcenter: 3.8.1
  - apporder: 0.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - camerarawpreviews: 0.7.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - event_update_notification: 1.0.2
  - external: 3.6.0
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_automatedtagging: 1.9.0
  - files_downloadactivity: 1.8.0
  - files_pdfviewer: 1.8.0
  - files_readmemd: 1.1.4
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 6.0.6
  - impersonate: 1.6.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - metadata: 0.11.1
  - notes: 3.6.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.3.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - suspicious_login: 3.1.0
  - systemtags: 1.9.0
  - tasks: 0.13.1
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_retention: 1.2.0
  - user_usage_report: 1.3.2
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - checksum
  - encryption
  - federation
  - files_external
  - nextcloud_announcements
  - socialsharing_email
  - support
  - survey_client
  - terms_of_service
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/mnt\/ncdata\/__skeleton",
        "dbtype": "pgsql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": 0,
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 14",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": false,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "dbindex": "0",
            "timeout": "1.5"
        },
        "logtimezone": "Australia\/Melbourne",
        "maintenance": false,
        "default_locale": "en_AU",
        "force_locale": "en_AU",
        "default_language": "en",
        "force_language": "en",
        "defaultapp": "activity,files",
        "activity_expire_days": 180,
        "session_lifetime": 14400,
        "session_keepalive": false,
        "lost_password_link": "disabled",
        "overwriteprotocol": "https",
        "app_install_overwrite": [
            "activitylog",
            "uploaddetails",
            "drop_account",
            "files_readmemd",
            "afterlogic"
        ],
        "updater.release.channel": "stable",
        "theme": ""
    }
}
```
</details>

**Are you using encryption:**
No

**Are you using an external user-backend, if yes which one:**
No

### Client configuration
**Browser:**
Firefox 77.0.1
Vivaldi 3.1.1929.45 (Stable channel) (64-bit)

**Operating system:**
Linux Mint 19
Windows 10

#### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/onlyoffice/[FILENAME].docx
from xxx.xxx.xxx.xxx at 2020-07-08T13:28:04+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /s/qnrodMLQSXjb46Z
from xxx.xxx.xxx.xxx at 2020-07-08T12:09:52+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/files/?dir=/[FILENAME]&fileid=7148
from xxx.xxx.xxx.xxx at 2020-07-08T10:50:38+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/files_readmemd/config
from xxx.xxx.xxx.xxx at 2020-07-08T10:34:06+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/theming/img/core/filetypes/folder.svg?v=39
from xxx.xxx.xxx.xxx at 2020-07-08T10:18:49+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/onlyoffice/s/QP9RTXD9R5FnCWz
from xxx.xxx.xxx.xxx at 2020-07-08T10:05:37+10:00
```
</details>

**Comment by Nils160988** [comment] 2020-07-08 07:36
Duplicate of https://github.com/nextcloud/server/issues/20490?

**Closed** 2020-07-08 09:01 UTC
Labels: 0. Needs triage, bug

**Comment by nooblag** [comment] 2020-07-08 10:11
Hi @Nils160988, thank you for your note. However, I don't believe it's a duplicate. If you look at the log file reported for this bug, it is different to the reporting in 20490, and I have a suspicion it is triggered from actions whilst a user is logged in, not triggered on logout, but I cannot confirm this yet as I am unsure of the steps to reproduce.

Please reopen this bug report?

**Comment by nooblag** [comment] 2020-07-08 10:13
As you can see from the Nextcloud log above, the error fires off when the user is accessing files:

```
[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/onlyoffice/[FILENAME].docx
from xxx.xxx.xxx.xxx at 2020-07-08T13:28:04+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /s/qnrodMLQSXjb46Z
from xxx.xxx.xxx.xxx at 2020-07-08T12:09:52+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/files/?dir=/[FILENAME]&fileid=7148
from xxx.xxx.xxx.xxx at 2020-07-08T10:50:38+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/files_readmemd/config
from xxx.xxx.xxx.xxx at 2020-07-08T10:34:06+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/theming/img/core/filetypes/folder.svg?v=39
from xxx.xxx.xxx.xxx at 2020-07-08T10:18:49+10:00

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

GET /apps/onlyoffice/s/QP9RTXD9R5FnCWz
from xxx.xxx.xxx.xxx at 2020-07-08T10:05:37+10:00
```

**Comment by acsfer** [comment] 2020-07-08 10:30
Not the same error but the cause is the same. Please check the Kesselberg comment on the PR attached to the other issue.

**Comment by PushpendraMaurya** [comment] 2021-02-04 17:05
i am facing this error anyone solve this  



Notice: session_start(): A session had already been started - ignoring in C:\xampp\htdocs\GreyWhite\includes\common.inc.php on line 1
