### ISSUE TITLE
paste clipboard content

### ISSUE THREAD

**Issue by ratermir** [nextcloud/server#16362] opened 2019-07-11 10:35 UTC
I would appreciate ability to be able to paste clipboard content directly into files application. This functionality would really simplify moving content between local device (computer, tablet) and nextcloud. 

Based on clibboard content type, the behavior may be like this:
* in case of text, grid, document or image, new file of corresponding file type will be created. Dialog for file saving (with the pre-generated name of the new file) will be shown. 
* In case file (or multiple files), they would be stored similarly to drag/drop functionality.

Corresponding menu item ("paste from clipboard") would be added.

**Comment by Gatak** [comment] 2019-10-28 23:12
I second this. Being able to simple copy paste operations from clipboard would be very useful. There was an app for this but it isn't working after NC12 https://github.com/leizh/owncloud-files_clipboard

**Comment by beccon4** [comment] 2020-12-01 12:11
> I second this. Being able to simple copy paste operations from clipboard would be very useful. There was an app for this but it isn't working after NC12 https://github.com/leizh/owncloud-files_clipboard

I opened an issue in the app's repo: https://github.com/felixrupp/owncloud-files_clipboard/issues/56 to extend compatibility. I'm not sure if this is a compatibility flag issue only or the way NC > 12 implements the file manager has changed in a way rendering it impossible to implement a function like that.

**Comment by ratermir** [comment] 2020-12-01 13:13
I guess purpose of the mentioned application (https://github.com/leizh/owncloud-files_clipboard) was a bit different - as I remember, it worked INSIDE nextcloud (you were able to copy / paste or move inside the NC installation). I don't aware that it allows to paste generic content - it manipulated only files (and only files from NC).
But I mean generic clipboard that would allow to move any type of content mainly from outside of NC (as described above). So not only files, but also different types of content (text clips, image contents, content of grid ... etc; but of course also files as such - i.e. pasting files from clipboard in addition to current drag and drop). The behaviour could be similas to most of e-mail web clients (gmail, web outlook ... etc)
Actually, also here (on  github) it works similar way :) 
It could work botn on CTRL + C, or on new menu item event (see example bellow).

![image](https://user-images.githubusercontent.com/52619304/100745177-2d8ef800-33df-11eb-946a-83aae8b6598a.png)

**Comment by szaimen** [comment] 2021-06-18 12:18
Duplicate of https://github.com/nextcloud/server/issues/27427

**Closed by szaimen** 2021-06-18 12:18 UTC
Labels: 0. Needs triage, enhancement
