### ISSUE TITLE
NC13 (and likely versions below) misreport available space with atypical configurations

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [nextcloud/server#9424] opened 2018-05-08 15:40 UTC
I keep getting the "Your storage is full, files can not be updated or synced anymore!" message, and it's impossible to turn it off.

My user account has several samba/cifs shares mounted in data/user. These directories have several terabytes of capacity left, more than enough for me for quite awhile yet. But since Nextcloud checks the data/user directory itself and finds a more modest amount available, I continue to get this error message.

Would it be possible to add as a feature a configuration setting where I could point it to a subdirectory in my user's root folder to check availability, rather than the user root folder itself? 

Is there some other method by which this error message could be selectively suppressed? I can't modify NC's core code without it complaining about that, nor do I believe an app can modify this behavior considering how deep in the codebase it is.

**Comment by MorrisJobke** [comment] 2018-05-08 21:04
> Would it be possible to add as a feature a configuration setting where I could point it to a subdirectory in my user's root folder to check availability, rather than the user root folder itself?

Try the option "quota_include_external_storage" in config.php.



This is also a duplicate of https://github.com/nextcloud/server/issues/3471 - closing therefore.

**Closed by MorrisJobke** 2018-05-08 21:04 UTC
