### ISSUE TITLE
[Bug]: Move or copy file on link share does not work

### ISSUE THREAD

**Issue by andrey18106** [nextcloud/server#42009] opened 2023-12-04 13:22 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is a bug when you're trying to move files inside of a full access link share. The modal "Choose target files" not getting directory listing for move or copy target, because the `userid` and  `path` for DAV request is missing in the context of link share.

### Steps to reproduce

1. Create directory `d1`
2. Create directory `d2` inside of `d1`
3. Create file `f1.txt` inside of `d1`
4. Create link share of `d1` with full access (`Can edit`)
5. Open link share in other browser (does not matter if you are being logged in to Nextcloud)
6. Select `f1.txt`
7. Try to move `f1.txt` into `d2` via  `actions -> move or copy`
8. See error: "Choose target folder" modal list is not loading

### Expected behavior

The files in "Choose target folder" modal displayed correctly with only shared items to perform operations allowed with "Full access link share", and these operations are successfully made.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
From browser console:

`PROPFIND https://stable27.local/remote.php/dav/files/undefined/`
```

### Additional info

![image](https://github.com/nextcloud/server/assets/29692256/34f5b8a0-e8fc-465c-8c18-77bc06ebbc8d)

**Comment by paulijar** [comment] 2023-12-10 14:21
I see a similar problem on all the file dialogs launched by the Music app on NC28 RC4 (and also RC2). On NC 27.1.2, these dialogs worked fine. Is the legacy wrapper for the file dialogs broken again?

**Comment by susnux** [comment] 2023-12-14 15:05
> I see a similar problem on all the file dialogs launched by the Music app on NC28.0.0 RC4 (and also RC2). On NC 27.1.2, these dialogs worked fine.

Sounds unrelated, this one is caused by the wrong endpoint (`webdav` vs `dav`) because of anonymous users. This did not even work with 27.1.x.
So @paulijar feel free to report a separate issue for that one with some information about it (browser console errors?).

**Comment by susnux** [comment] 2023-12-14 15:06
> Cc susnux

I can have a look on this one.

**Comment by paulijar** [comment] 2023-12-14 22:22
@susnux  Okay, thanks for the info. I now created the report https://github.com/nextcloud/server/issues/42291.

**Comment by timm2k** [comment] 2024-01-18 13:43
Any news on this?

**Comment by andrey18106** [comment] 2024-01-18 13:59
@susnux is there any update on this?

**Comment by timm2k** [comment] 2024-02-07 11:07
Also Nextcloud 28.2 is showing same error
```
[...]/remote.php/dav/files/undefined/ 401 (Unauthorized)
```

**Comment by susnux** [comment] 2024-05-27 16:58
> Issue is still reproducible on master (Nextcloud 30)

Unrelated / other issue that caused this. The current issue is a regression in the files library and already fixed with:
https://github.com/nextcloud-libraries/nextcloud-files/pull/959

**Closed by susnux** 2024-05-27 16:58 UTC
Labels: bug, feature: sharing, 0. Needs triage, feature: files, regression, 27-feedback, 🍁 2023-Autumn
