### ISSUE TITLE
upload progress bar gone ... multiple browser test

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9040] opened 2018-03-30 23:33 UTC
Tested against a nextcloud 13.0.1 with apache and php7 setting to allow unlimited size and time for upload.

test folder size doesn't matter. drag and drop in browser.
 
Test 1: 
CHROME Version 65.0.3325.181 (Build officiel) (64 bits)
Progress bar start,
X minutes upload progress shown
As soon as uploaded folder tree is finish progress bar disappear
Files are uploading in "blind" mode.
Browsing forth and back on any pre-existing or uploaded folder is possible.
Doesnt break the upload process.
Files appears as soon upload is done, but need browser refresh.
Test folder was 8,86 Go (9 516 379 890 octets).329 Files, 126 Folders
I will also open another issues, because those informations are not shown nowhere. #9041
Seem's upload broke after sometimes, need to be confirm.

Test 2:
EDGE Version 41.16299.248.0
NO Progress bar,
Files are uploading in "blind" mode.
Browsing forth and back on any pre-existing or uploaded folder is possible.
Break the upload process.
Files appears as soon upload is done, but need browser refresh.
Test folder was 8,86 Go (9 516 379 890 octets).329 Files, 126 Folders
I will also open another issues, because those informations are not shown nowhere. #9041

Test 3:
Firefox Version 59.0.2 (64 bits)
Progress bar start,
Progress bar disappear after a very short seconds, no information at all.
Files are uploading in "blind" mode.
Browsing forth and back on any pre-existing or uploaded folder is possible.
Break the upload process.
Files appears as soon upload is done, but need browser refresh.
Test folder was 8,86 Go (9 516 379 890 octets).329 Files, 126 Folders
I will also open another issues, because those informations are not shown nowhere #9041
Seem's upload broke after sometimes, need to be confirm.

Test 4:
Opera Version 52.0.2871.40
Progress bar start,
Progress bar disappear after a very short seconds, no information at all.
Files are uploading in "blind" mode.
Browsing forth and back on any pre-existing or uploaded folder is possible.
Doesnt break the upload process.
Files appears as soon upload is done, but need browser refresh.
Test folder was 8,86 Go (9 516 379 890 octets).329 Files, 126 Folders
I will also open another issues, because those informations are not shown nowhere. #9041
Seem's upload broke after sometimes, need to be confirm.

Doesnt need to go further.

Progress bar need fixing, enhancement.

**Comment by stratege1401** [comment] 2018-03-30 23:34
same behaviors on official nextcloud 13 test server: https://demo13.nextcloud.bayton.org

**Comment by tflidd** [comment] 2018-03-31 11:00
Related, or even duplicate of https://github.com/nextcloud/server/issues/8106

**Comment by stratege1401** [comment] 2018-06-08 21:39
Hello again... 

- Maybe you could close this ticket as i have enable the app Flow Update ( https://apps.nextcloud.com/apps/flowupload ) witch is just perfectly handling the uploads...
- Or, you could simply use Flow Update as native functionality. This could save some times.

Thank you.

**Closed** 2018-07-03 08:53 UTC
