### ISSUE TITLE
UX: Add Link to "What's new" on update page

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#9596] opened 2018-05-25 04:55 UTC
![missing-link](https://user-images.githubusercontent.com/24833757/40526681-667c6e72-5fe8-11e8-8bfa-b9e1ed453c2e.png)

**Comment by MorrisJobke** [comment] 2018-05-25 11:36
We planned this in #9165 and #2138 - Let's close this ticket as duplicate of those two then.

**Closed by MorrisJobke** 2018-05-25 11:36 UTC
