### ISSUE TITLE
JSON file preview shows [object Object]

### ISSUE THREAD

**Issue by sisou** [nextcloud/server#17354] opened 2019-10-01 11:09 UTC
### Steps to reproduce
1. Upload a `.json` file, e.g. a `package.json` to NextCloud
2. Click on it in the browser client to preview it
3. Not the JSON is displayed, but simply `[object Object]`

### Expected behaviour
The JSON is correctly displayed, e.g. a `package.json` file.

### Actual behaviour
Instead of the JSON, `[object Object]` is shown.

**Comment by kesselb** [comment] 2019-10-01 12:44
Ref #17346

**Comment by gary-kim** [comment] 2019-10-07 11:56
Are you referring to the "text" app?

**Comment by sisou** [comment] 2019-10-07 14:14
@gary-kim possibly. I'm not an admin in our instance and can't find the nextcloud version from the UI, but I just saw that what I called preview is actually an editor :D

It doesn't have the editor button at the top, but then again I don't know if those only show up for markdown in the new editor in Version 17?

But if you say it's been fixed, then I'll just bug our admin with updating nextcloud when it's available! :+1:

**Comment by szaimen** [comment] 2021-05-26 13:29
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-26 13:29 UTC
Labels: 0. Needs triage, bug

**Comment by sisou** [comment] 2021-05-26 13:38
I don't know which versions we are on (can I see that somewhere in the deployed version?), but it works now, JSON files are displayed as text :+1:

**Comment by QkiZMR** [comment] 2026-08-25 12:24
I have the same problem. A text file on the Nextcloud server, when opened in a browser removes all content with `[object Object]`. The worst part is that the file is changed on the server, and all other devices download a corrupted version of that text file. Nextcloud version is 34.0.3.
