### ISSUE TITLE
Nextcloud always generates two shared links instead of one

### ISSUE THREAD

**Issue by mail-nextcloud** [nextcloud/server#25256] opened 2021-01-21 17:21 UTC
### Steps to reproduce

1. Select folder or file for sharing
2. Go to the tab "Sharing" in the right menu
3. Click plus icon for "Create a new share link" next to the label "Share link"
4. Use the predefined password and click enter
5. The shared link is visible
6. Refresh site

### Expected behaviour
Only one shared link is available

### Actual behaviour
Two different shared links are available

### Server configuration

**Operating system:** Ubuntu 20.04.1 LTS

**Database:** MySQL 5.7.32

**PHP version:** 7.4.14

**Nextcloud version:** 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Snap version of nextcloud

**Comment by RSLak1** [comment] 2021-01-21 18:01
Same for me.

**Comment by h-schwanbeck** [comment] 2021-02-22 16:36
Still an issue in 20.0.7 - Web interface sends two requests to create a share link instead of one.

**Comment by szaimen** [comment] 2021-06-23 14:51
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-23 14:51 UTC
Labels: 0. Needs triage, bug
