### ISSUE TITLE
Hidden files visible in Grid View mode

### ISSUE THREAD

**Issue by TheManchineel** [nextcloud/server#14478] opened 2019-03-02 23:14 UTC
### Steps to reproduce
1. Open the Nextcloud Files web app
2. Create a folder or upload a file with a name starting in "." and ensure that "Show hidden files" is disabled
2. Click on the "Toggle grid view button"

### Expected behaviour
Hidden files or directories should not be visible at all in Grid View, just like in List View

### Actual behaviour
Files or folders having names that start in "." (e.g. ".sync") which are normally hidden appear in Grid View, albeit without their name displayed below the icon. They can be selected and interacted with, just like any other file.

### Server configuration

**Operating system**: Ubuntu Server 18.04 LTS

**Web server:** NGINX

**Database:** PostgreSQL

**PHP version:** 7.2

**Nextcloud version:** 15.0.5, issue has been present since 15.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated through Nextcloud stable releases over time

**Where did you install Nextcloud from:** downloaded Nextcloud from nextcloud.com and installed dependencies from the default Ubuntu repositories, always updated using web-based installer

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - apporder: 0.6.0
  - audioplayer: 2.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - deck: 0.5.2
  - drawio: 0.9.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.2
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - sharerenamer: 2.3.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.1
  - unsplash: 1.1.3
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "logfile": "\/var\/log\/nextcloud.log",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "onlyoffice": {
            "verify_peer_off": true
        },
        "mail_smtpsecure": "ssl",
        "simpleSignUpLink.shown": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Firefox 65

**Operating system:** tested on Windows 10, macOS 10.13.6 and Ubuntu Desktop 18.04 LTS

No errors seem to appear

**Comment by skjnldsv** [comment] 2019-06-04 10:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
![Capture d’écran_2019-06-04_12-12-22](https://user-images.githubusercontent.com/14975046/58871619-add97d80-86c2-11e9-83c9-19f47c95ead0.png)

**Closed by skjnldsv** 2019-06-04 10:17 UTC
Labels: 0. Needs triage, bug

**Comment by DaniJohni** [comment] 2022-10-21 12:56
I have the same problem after upgrading to Nextcloud 25, how did this get resolved?

**Comment by DomiiBunn** [comment] 2022-11-12 22:05
Happening here...
![image](https://user-images.githubusercontent.com/51760394/201496343-45d396c4-8c5f-4e79-90fe-437c4080f6b6.png)

**Comment by mattdev44** [comment] 2022-11-14 04:43
> As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen. ![Capture d’écran_2019-06-04_12-12-22](https://user-images.githubusercontent.com/14975046/58871619-add97d80-86c2-11e9-83c9-19f47c95ead0.png)

@skjnldsv 
I am having this same issue on Hub 3 (25.0.1) - Can you reopen this issue?
Operating System: Linux 3.10.0-962.3.2.lve1.5.68.el7.x86_64 x86_64
CPU: Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz (64 cores)
Memory: 251.06 GB
PHP Version: 7.4.33

**Comment by DomiiBunn** [comment] 2022-12-07 13:58
It might be worthy opening a new issue as it seams no one will notice/re-open this one

**Comment by Joedmin** [comment] 2023-01-21 15:13
Same here 25.0.3
![image](https://user-images.githubusercontent.com/73015399/213873327-aeb80c96-002b-4bb6-8599-48279a024f89.png)

**Comment by chenasraf** [comment] 2023-01-23 08:09
Same, any fix for this?

**Comment by azcn2503** [comment] 2023-01-24 12:06
I am seeing the same error in Nextcloud 25.0.3. The hidden folders incorrectly show in Grid view when "Show hidden files" is unchecked, but are correctly hidden in the List view.

**Comment by razzie** [comment] 2023-02-14 22:21
If anyone is wondering, there is a new ticket and a workaround here: https://github.com/nextcloud/server/issues/35885#issuecomment-1372619096
