### ISSUE TITLE
Deleted files are not considered by the quota

### ISSUE THREAD

**Issue by MeCias** [nextcloud/server#23670] opened 2020-10-24 16:34 UTC
I am using NC 20, but I am pretty sure that this behaviour was already in the previous versions. Maybe it is a feature not a bug.

As soon you are deleting files the quota reduces by the size of the files that you moved to the bin.
But I think the quota should be still the same as long those files are in the bin, just as soon they get finally removed there as well the quota should be adjusted. 
At the moment you have unlimited space in the deleted files folder (at least for 30 days or so - depending on the presets).

**Comment by kesselb** [comment] 2020-10-24 17:31
Closing as duplicate of https://github.com/nextcloud/server/issues/15661

Please use the search. For example: https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aopen+trash+quota

**Closed by kesselb** 2020-10-24 17:31 UTC
