### ISSUE TITLE
Feature Request: allow Showing description in app lists

### ISSUE THREAD

**Issue by My1** [nextcloud/server#8193] opened 2018-02-06 10:54 UTC
in the list-style app lists you have no way to see the descriptions which seems kinda annoying, especially when you have plugins with names like "versions" (versions of WHAT? files, nextcloud itself, whatever) that seem kkinda ambiguous, or you just want to know what this thing exactly can do, and as a "show description" link does exist for example in the thumbnail-style category lists, it's kinda sad to see that isnt in the normal lists.

**Comment by MorrisJobke** [comment] 2018-02-06 11:22
Duplicate of #4827 which was closed in favour of #2138

**Closed by MorrisJobke** 2018-02-06 11:22 UTC
