### ISSUE TITLE
make gradient optional

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#19040] opened 2020-01-21 09:59 UTC
When applying a defined corporate color in theming, the automatically applied gradient on login page and menu bar undercuts that CD.
It should at least be optional to have the set color be transformed into a gradient.

**Comment by markuman** [comment] 2020-01-24 05:56
![Screenshot_2020-01-24 Settings - Nextcloud](https://user-images.githubusercontent.com/3920157/73047618-aeec3480-3e76-11ea-944a-62e1f3702406.png)

yes, it looks absolutely terrible

**Comment by Octopus2** [comment] 2020-01-24 09:43
I also use "Theming" and also had this problem with the blue part in this headerbar.

Only occ maintenance: repair and the deletion of all data in the browser cache solved the problem and led to a different appearance.

Considerable: After every web upgrade from Nextcloud, these steps must be carried out to achieve the functionality. Also important: Ad blockers must be deactivated.

**Comment by juliushaertl** [comment] 2020-01-24 10:16
@wiswedel For the login page removing the background image will do the trick, maybe we should also not apply the gradient in general then. However I don't think we should add another setting for this. cc @jancborchardt

**Comment by jancborchardt** [comment] 2020-01-27 06:52
Yup, agree with your solution @juliushaertl 

@markuman @Octopus2 what you ran into is of course not intended. We did have an issue for this but should be resolved … @juliushaertl is this something in theming?

**Comment by juliushaertl** [comment] 2020-01-27 07:08
We had this, but there was a fix for it in beta or rx phase, so if it still occurs, please open a new issue with the steps to reproduce.

**Comment by wiswedel** [comment] 2020-01-27 08:40
> For the login page removing the background image will do the trick, maybe we should also not apply the gradient in general then. However I don't think we should add another setting for this.

I think causing implicit consequences (remove default background image = change top bar color) is worse UX and worse to explain than having just another setting.

**Comment by Weasy666** [comment] 2020-01-27 22:06
For me, removing the default background image did not remove the gradient in the top bar.

For me it looks like this:
![image](https://user-images.githubusercontent.com/11967542/73218022-5f00bc80-4159-11ea-9570-a9f7e891fdfb.png)
And with the icons on the right nearly not visible because of the gradient, i would really appreciate an option the deactivate it.

**Comment by Baggypants** [comment] 2020-02-25 14:56
![Screenshot_2020-02-25 Settings - Nextcloud](https://user-images.githubusercontent.com/4421419/75258712-cfddd780-57de-11ea-8026-aba0630faff0.png)
Brilliant, who wouldn't want a website that now looks literally like faeces has been smeared over it.

**Comment by Baggypants** [comment] 2020-02-25 15:08
Also:
```
I spent a long time picking this colour                                    Bleugh
 |                                                                             |
\|/                                                                           \|/
```
![Screenshot_2020-02-25 Files - Nextcloud](https://user-images.githubusercontent.com/4421419/75259689-50510800-57e0-11ea-9206-c876d6b61fd4.png)

**Comment by earboxer** [comment] 2020-02-27 02:32
Solution for users (since it will be a while before we make a patch ad get it merged in). With the custom CSS App.

```css
#header{background-image:initial  !important;}
```

**Comment by AlexanderBalson** [comment] 2020-03-13 04:45
This is a case of where knowing your users (and their desire for endless customisability) is important, don't make these kinds of decisions without an option to control them please.

**Comment by jancborchardt** [comment] 2020-03-13 08:15
@AlexanderBalson people who desire endless customizability are not our target audience, sorry. We have clear [design guidelines](https://nextcloud.com/design/) and adding preferences for everything will make the software unmaintainable, see "[Choosing our Preferences](https://ometer.com/preferences.html)".

Besides it is not necessary to comment further on this thread as there is a pull request open to fix this which everyone is welcome to review: https://github.com/nextcloud/server/pull/19669

**Comment by redtux** [comment] 2020-03-20 16:26
> Solution for users (since it will be a while before we make a patch and get it merged in). With the custom CSS App.
> 
> ```css
> #header{background-image:initial  !important;}
> ```

@earboxer, thank you for this fix! It perfectly works with the menu bar. :+1:

Could anyone provide a similar fix for the login page, please? :pray:

**Comment by earboxer** [comment] 2020-03-20 22:28
> Could anyone provide a similar fix for the login page, please?

Same rule, but apply it to #body-login.

```diff
-#header{background-image:initial  !important;}
+#body-login, #header{background-image:initial  !important;}
```

**Comment by redtux** [comment] 2020-03-21 16:05
> -#header{background-image:initial  !important;}
> +#body-login, #header{background-image:initial  !important;}

This makes the login page blue. But thanks, I will try some CSS rules and report back what worked.

**Closed** 2020-06-08 11:44 UTC
Labels: 0. Needs triage, 18-feedback, enhancement, feature: theming
