### ISSUE TITLE
[Bug]: No Email Notifications Sent for Folder Shares in Nextcloud Hub 9 (30.0.1)

### ISSUE THREAD

**Issue by ace02000** [nextcloud/server#49074] opened 2024-11-04 13:12 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since updating to Nextcloud Hub 9 (30.0.1), email notifications are no longer sent when I share folders via email. The SMTP configuration is correct, as test emails are sent successfully. I’ve also tried deleting and reconfiguring the SMTP settings without any improvement. However, on my mail server, I can see that no emails are sent whenever a share with email notification is created.

### Steps to reproduce

	1.	Update to Nextcloud Hub 9 (30.0.1).
	2.	Set up SMTP email configuration (confirmed working by sending test emails).
	3.	Attempt to share a folder and select the option to send an email notification.
	4.	Check the mail server logs for any outgoing emails.

### Expected behavior

Email notifications should be sent to recipients when a folder is shared via email.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",

### List of activated Apps

Enabled:
  - activity: 3.0.0
  - app_api: 4.0.0
  - bookmarks: 15.0.2
  - calendar: 5.0.1
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - news: 25.0.0-alpha12
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recognize: 8.1.1
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.1
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0

### Nextcloud Signing status

No errors have been found.

### Additional info

	•	SMTP Configuration Status: Verified, successfully sending test emails
	•	Nextcloud Version: Hub 9 (30.0.1)
	•	Server Environment: [Your server environment details, e.g., OS, PHP version]
	•	Logs: No errors in the Nextcloud logs related to email sending.

Let me know if additional details are needed. Thank you for your support in resolving this issue!

**Comment by joshtrichards** [comment] 2024-11-05 12:59
Duplicate of #48012

**Closed by joshtrichards** 2024-11-05 12:59 UTC
Labels: bug, 0. Needs triage
