### ISSUE TITLE
[Bug]: Video not playing in full sceen when shared via link in NextCloud 25.01

### ISSUE THREAD

**Issue by reaSharp** [nextcloud/server#35504] opened 2022-11-29 21:17 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sharing a link to only one video file (not a folder) and setting the option to disable download the shared video cannot be played in full screen. The full screen button is there but the video is not rendered to full screen. This was working in NextCloud 24 but is not working with NextCloud 25 anymore. 

### Steps to reproduce

1. Go to any video (with a lower resolution than the screen). 
2. Click the share button
3. Disable the download option
4. Copy the generated link into any browser (Firefox, Safari, Chrome, Edge)
5. Click on the fullscreen button
6. Video does not scale to fullscreen (lot of black space around)

### Expected behavior

Video should be scaled to full screen as in NextCloud 24.

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.1.0
  - cloud_federation_api: 1.8.0
  - contacts: 5.0.1
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - support: 1.8.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - video_converter: 1.0.5
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.0.1
  - circles: 24.0.1
  - comments: 1.10.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.0.0
  - encryption: 2.6.0
  - federation: 1.14.0
  - files_external
  - nextcloud_announcements: 1.13.0
  - recommendations: 0.8.0
  - sharebymail: 1.14.0
  - survey_client: 1.8.0
  - suspicious_login
  - systemtags: 1.10.0
  - twofactor_totp
  - user_ldap
  - user_status: 1.0.1
  - weather_status: 1.0.0
```

**Comment by rm-dr** [comment] 2022-12-12 22:21
This seems to be the case with any share link directly to a video, even if downloads are enabled.

I saw the same thing, with 25.0.2.

**Comment by labor4** [comment] 2022-12-21 16:48
Above is also for iOS Safari and Brave.
But additionally also fails on **iOS** Safari + Brave, even if the starting point was the parent directory.

Macos Desktop works from parent directory starting point.

It seems the preview app doesn't let the iOS browsers grab the source, to display it in their native fullscreen player. everything is still framed in HTML, which is often problematic on iOS.

**Comment by labor4** [comment] 2022-12-21 16:54
See above mention. The department for this issue seems to belong to "viewer", correct?

**Comment by szaimen** [comment] 2022-12-27 15:29
Duplicate of https://github.com/nextcloud/viewer/issues/1441

**Closed by szaimen** 2022-12-27 15:29 UTC
Labels: bug, 0. Needs triage, 25-feedback
