### ISSUE TITLE
Share Link Error

### ISSUE THREAD

**Issue by s0faking** [nextcloud/server#13513] opened 2019-01-11 12:37 UTC
### Steps to reproduce
1. Login with any User
2. Select details on a random file
3. Share the File with a private Link

### Expected behaviour
I should see the Share Link Checkbox to share the link to a file without using an email or username

### Actual behaviour
Only the textinput for email or username is visible. I get an JS Error with Chrome "Uncaught ReferenceError: link is not defined"

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql 5.7

**PHP version:**

**Nextcloud version:** 15.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 14

**Where did you install Nextcloud from:** Web Updater

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
 - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.1
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_external: 0.5.0
  - workflowengine: 1.5.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "storage.lowfidelity.at",
            "cloud.lowfidelity.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.1.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "mail_smtptimeout": 30,
        "mail_smtpdebug": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "loglevel": 0,
        "updatechecker": true,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "overwrite.cli.url": "https:\/\/cloud.lowfidelity.at",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 71.0.3578.98

**Operating system:** Windows 10

#### Browser log
<details>
<summary>Browser log</summary>

Uncaught ReferenceError: link is not defined
at merged-share-backend.js?v=28f5c443-9:2521
    at Function.m.each.m.forEach (core.js?v=28f5c443-9:18)
    at child.each (core.js?v=28f5c443-9:1157)
    at child.render (merged-share-backend.js?v=28f5c443-9:2519)
    at child.render (merged-share-backend.js?v=28f5c443-9:4455)
    at child.<anonymous> (merged-share-backend.js?v=28f5c443-9:3752)
    at triggerEvents (core.js?v=28f5c443-9:1441)
    at triggerApi (core.js?v=28f5c443-9:1426)
    at eventsApi (core.js?v=28f5c443-9:1225)
    at child.Events.trigger (core.js?v=28f5c443-9:1416)

</details>

**Comment by violoncelloCH** [comment] 2019-01-12 14:40
thank you for reporting!
closing as duplicate of #13521

**Closed by violoncelloCH** 2019-01-12 14:40 UTC
Labels: 0. Needs triage, bug
