### ISSUE TITLE
Wrong Modified Date

### ISSUE THREAD

**Issue by guinhas** [nextcloud/server#11025] opened 2018-09-03 11:50 UTC
### Steps to reproduce
I uploaded 2 pdf files to nextcloud and 1 of them has the modified date wrong, in the modified column. When i check the file details, in the activity separator I only see the file creation time and it is right. In the file details, the file was created a few seconds ago and in the modified column the file was modified 2 days ago. Is this right? Am I doing something wrong? Thank you.

### Expected behaviour
Modified (date/time) column should display correct date/time.

### Actual behaviour
Modified (date/time) column displays incorrect date/time.

### Server configuration

**Operating system:** Ubuntu 16.04.5 (armv7l) running in an LXC container

**Web server:** Apache 2.4.18

**Database:** Mysql 10.0.36

**PHP version:** PHP 7.0.30

**Nextcloud version:** 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 13.0.5

**Where did you install Nextcloud from:** Downloaded from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.lan"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.lan",
        "dbtype": "mysql",
        "version": "13.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 61.0.1

**Operating system:** Ubuntu 18.04.1

![nextcloud](https://user-images.githubusercontent.com/18296718/44985212-6711f800-af77-11e8-9e0b-7d797408bb5f.png)

**Comment by nickvergessen** [comment] 2018-09-04 13:29
Duplicate of #3572

**Closed by nickvergessen** 2018-09-04 13:29 UTC
Labels: bug
