### ISSUE TITLE
IE11: check boxes invisible

### ISSUE THREAD

**Issue by bobblkabb** [nextcloud/server#11881] opened 2018-10-17 11:10 UTC
### Steps to reproduce
Mark folders or files by activating check boxes.

### Expected behaviour
You should see 'unchecked' check boxes.

### Actual behaviour
The check boxes on **Internet Explorer 11** are invisible as long as they are not activated.
Fine under **Firefox 62.0.3**.
Might be related to #11141.

### Server configuration

**Operating system**: Ubuntu 18.04.1

**Web server:** Apache 2.4.29

**Database:** mysql Ver 14.14 Distrib 5.7.23

**PHP version:** php 7.2

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** cli

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>

<summary>Config report</summary>
{         
    "system": {            
        "instanceid": "***REMOVED SENSITIVE VALUE***",   
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",    
        "trusted_domains": [
            "[internal ipv4 address]",
            "vmserver",          
            "[ipv4 adress]",
            "cloud.mycloud.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --noLOgo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "skeletondirectory": "\/var\/www\/nextcloud\/core\/skeleton\/",
        "maintenance": false,
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/data\/nextcloud.log",
        "log_rotate_size": 104857600,
        "log_authfailip": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "NTLM",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "auto",
        "default_language": "en_GB",
        "overwrite.cli.url": "https:\/\/cloud.mycloud.de",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
There are no commands defined in the "ldap" namespace.
</details>

### Client configuration
**Browser:** Internet Explorer 11 and Firefox 62.0.3 (64Bit)

**Operating system:** Solus 3.9999, Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

![screenshot](https://user-images.githubusercontent.com/7815101/47082447-da14bc80-d20d-11e8-80f7-441e03bb85d4.jpg)

**Comment by WillixJ** [comment] 2018-11-14 15:58
Hi, I came across the same issue and eventually managed to fix this by creating a custom Theme for Nextcloud. 
In the [custom theme directory]\core\css\server.css I added the following lines:

`:root{
    --color-checkbox-radio-disabled: #bababa;
    --color-checkbox-radio-border: #878787;
}`

You can add all the CSS vars you need or want to add or override.  
IE11 misses a few more I believe. 
Other browsers don't seem to have this issue. 

Good luck.

**Comment by mritzmann** [comment] 2018-12-12 11:13
I can reproduce the same problem in version 15.0.0.

**Comment by Yomark1** [comment] 2019-01-16 15:37
We have the same issue. 
Most annoying place this is happening is the missing checkbox to enable 2FA/TOTP. Users that have enforced 2FA policy and are provided with admin password are unable to enable it because the checkbox is invisible.

**Comment by skjnldsv** [comment] 2019-04-30 08:07
I cannot reproduce.
![Capture d’écran_2019-04-30_10-02-32](https://user-images.githubusercontent.com/14975046/56948025-229f2200-6b2f-11e9-85a3-19c57d963253.png)

I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by mritzmann** [comment] 2019-04-30 09:24
> I will need your browser console log to investigate this issue.

With Nextcloud version 15.0.7 and Interner Explorer 11.590.xx I can't reproduce it anymore. Seems to have been fixed in the meantime...

**Closed** 2019-04-30 09:43 UTC
Labels: bug, needs info
