### ISSUE TITLE
Documentation too vague for occ encryption:scan:legacy-format

### ISSUE THREAD

**Issue by mark-orion** [nextcloud/server#24412] opened 2020-11-27 10:37 UTC
https://docs.nextcloud.com/server/20/admin_manual/configuration_files/encryption_migration.html

The documentation on this page says:
Checking for old files
On the command line run:
    occ encryption:scan:legacy-format
The command will tell you if you can remove the legacy encryption mode. If so remove the encryption.legacy_format_support from your config.php or set it to false.

This is far too vague. I need to know exactly what type of output can be expected so that legacy encryption format can be disabled safely.

In my situation the command tells me nothing apart from a few files  being listed as "....does not have a proper header" and I could not find any information if this error message is related to encryption or can be fixed etc.

**Comment by kesselb** [comment] 2020-11-27 11:02
Duplicate of https://github.com/nextcloud/server/issues/24240

**Closed by kesselb** 2020-11-27 11:02 UTC
Labels: 0. Needs triage, bug
