### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by Scrat80** [nextcloud/server#11656] opened 2018-10-07 05:40 UTC
### Steps to reproduce
1. I updated from 14.01 to 14.02 RC1
2. Went to the accessibility page, clicked the light and then the dark them
3. Held down shift while refreshing to force refresh

### Expected behaviour
It should've switched to the dark them

### Actual behaviour
The lil "Enabled" indicator just switches back n forth, or disappears if you click on a theme twice

### Server configuration

**Operating system**: FreeNAS 11.2 beta 3

**Web server:** Apache v2.4.34 (FreeBSD)

**Database:** MySQL v10.1.35

**PHP version:** PHP v7.2.10

**Nextcloud version:** 14.02 RC1

**Updated from an older Nextcloud or fresh install:** 14.01

**Where did you install Nextcloud from:** Followed instrutions from https://github.com/danb35/freenas-iocage-nextcloud. Database and files are located outside the jail. Try to install through the FreeNAS plugin page only gets me 
"This page isn’t working
IP ADDRESS redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS"

**Signing status:**
<details>
<summary>wtf is this "signing status?</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
Accessibility	1.0.1	Official	
Activity	2.7.0	Official	
Auditing / Logging	1.4.0	Official	
Brute-force settings	1.1.0	Official	
Calendar	1.6.2	Official	
Camera RAW Previews	0.5.6		
Collaborative tags	1.4.0	Official	
Comments	1.4.0	Official	
Contacts	2.1.6	Official	
Deck	0.4.1		
Default encryption module	2.2.0	Official	
Deleted files	1.4.1	Official	
DICOM Viewer	1.0.2		
Federation	1.4.0	Official	
File access control	1.4.0	Official	
File sharing	1.6.2	Official	
Files automated tagging	1.4.0	Official	
First run wizard	2.3.0	Official	
Gallery	18.1.0	Official	
Log Reader	2.0.0	Official	
Mail	0.10.0	Official	
Monitoring	1.4.0	Official	
Nextcloud announcements	1.3.0	Official	
Notes	2.4.2	Official	
Notifications	2.2.1	Official	
Password policy	1.4.0	Official	
Passwords	2018.9.1		
PDF viewer	1.3.2	Official	
PhoneTrack	0.3.1		
Preview Generator	1.1.0		
Share by mail	1.4.0	Official	
Social sharing via email	1.0.4	Official	
Social sharing via Twitter	1.0.3	Official	
Support	1.0.0	Official	
Talk	4.0.0	Official	
Text editor	2.6.0	Official	
Theming	1.5.0	Official	
Update notification	1.4.1	Official	
Usage survey	1.2.0	Official	
Versions	1.7.1	Official	
Video player  1.3.0	Official
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:** Wher can in find this from shell?
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** /mnt/databank01/(db/files)(outside jail)

**Are you using encryption:** yes.. within FreeNAS 11.2

**Are you using an external user-backend, if yes which one:** huh?
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Mac OS X 10.14

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Scrat80** [comment] 2018-10-07 05:55
PHP v7.2.10
MySQL v10.1.35

**Comment by MorrisJobke** [comment] 2018-10-09 07:57
cc @skjnldsv

**Comment by skjnldsv** [comment] 2018-10-25 16:06
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by skjnldsv** [comment] 2018-11-08 07:43
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Comment by Scrat80** [comment] 2018-11-08 11:42
Open sesame!

No wonder I thought the log request was from a tweet towards me by John M. His name is listed as the sender. I showered Twitter looking for this log file request, and since I never found it, I thought ya'll gave up.

I'll have a look when I get home in 12hrs.
Kthxbai

**Comment by Scrat80** [comment] 2018-11-09 04:09
Firefox:

[code]Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
accessibility:1:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
Loading failed for the <script> with source “https://s3.amazonaws.com/js-static/183f6c00aeaf5a41fe.js”. accessibility:1:1
Content Security Policy: The page’s settings blocked the loading of a resource at https://s3.amazonaws.com/js-static/183f6c00aeaf5a41fe.js (“script-src”).[/code]

* I never observed any attempts to connect to s3.amazonaws.com

Safari

[code]Failed to load resource: the server responded with a status of 404 () https://ip-hidden/apps/accessibility/css/user-f484570d7cf557020e11ace406901b10.css[/code]

Chrome

[code]GET https://ip-hidden/apps/accessibility/css/user-f484570d7cf557020e11ace406901b10.css net::ERR_ABORTED 404
DevTools failed to parse SourceMap: https://ip-hidden/apps/dicomviewer/js/app.bundle.js.map
DevTools failed to parse SourceMap: https://ip-hidden/apps/accessibility/js/accessibility.js.map
DevTools failed to parse SourceMap: https://ip-hidden/apps/notifications/js/notifications.js.map[/code]

**Comment by skjnldsv** [comment] 2018-11-09 07:09
> Failed to load resource: the server responded with a status of 404 () https://ip-hidden/apps/accessibility/css/user-f484570d7cf557020e11ace406901b10.css

This is the cause of your issue.
Are you using index.php in your urls?

**Comment by Scrat80** [comment] 2018-11-09 12:14
When I access NextCloud, the initial screen has index.php, but anything after I never see it.

**Comment by Scrat80** [comment] 2018-11-09 12:16
Those logs, are the different results I got from each.

**Comment by skjnldsv** [comment] 2018-11-09 12:18
If you try to get https://ip-hidden/index.php/apps/accessibility/css/user-f484570d7cf557020e11ace406901b10.css what does it do?

**Comment by Scrat80** [comment] 2018-11-11 06:08
They all load the CSS file

**Comment by Scrat80** [comment] 2018-11-26 01:32
It's broken.. but not by your hand from what I can tell. I made a new iocage with Nextcloud and there it works perfectly.

The script I used was made by DanB35.

**Comment by MorrisJobke** [comment] 2018-11-26 10:01
> It's broken.. but not by your hand from what I can tell. I made a new iocage with Nextcloud and there it works perfectly.

That means this ticket can be closed?

**Comment by Scrat80** [comment] 2018-11-26 18:19
It sure does!

**Closed** 2018-11-26 19:21 UTC
Labels: 14-feedback, needs info
