### ISSUE TITLE
avatar.imageplaceholder is not a function

### ISSUE THREAD

**Issue by watermark** [nextcloud/server#4034] opened 2017-03-24 18:03 UTC
When avatars are disabled, the sharing component breaks with a "avatar.imageplaceholder is not a function" javascript error.

### Steps to reproduce
1. set "'enable_avatars' => false," in config
2. Create a group
3. Try to share a folder

### Expected behaviour
The group is listed

### Actual behaviour
The share autocomplete dropdown no longer works.  Nothing is listed no matter what is typed.  If the developer window is open, a "avatar.imageplaceholder is not a function" error appers.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.0.14

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from owncloud

**Where did you install Nextcloud from:** zip file from site

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_videoplayer: 1.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - activity
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - files_trashbin
  - files_versions
  - firstrunwizard
  - gallery
  - theming
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc2izapx4wwm",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cr.files.company.com",
            "cloud.company.com"
        ],
        "datadirectory": "\/home\/cr\/owncloud_data",
        "overwrite.cli.url": "https:\/\/cloud.company.com\/",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "cr",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "companyname",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "dbindex": 2
        },
        "skeletondirectory": "",
        "updatechecker": false,
        "log_rotate_size": 104857600,
        "appstoreenabled": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": false,
        "filesystem_check_changes": 0,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "maintenance": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "php",
        "mail_smtphost": "relay.company.com",
        "mail_smtpport": "25",
        "mail_domain": "company.com",
        "mail_from_address": "no-reply"
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "2.1.3",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "31"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "incoming_server2server_share_enabled": "no",
            "installedat": "1457450392.4254",
            "lastcron": "1490377503",
            "lastupdateResult": "[]",
            "lastupdatedat": "1490377525",
            "oc.integritycheck.checker": "[]",
            "outgoing_server2server_share_enabled": "no",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "0 B",
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.1.2",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "smb,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.1.1",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "14.2.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "0.4",
            "ocsid": "166060",
            "types": "authentication,prelogin"
        },
        "user_ldap": {
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "has_memberof_filter_support": "1",
            "home_folder_naming_rule": "",
            "installed_version": "1.1.2",
            "last_jpegPhoto_lookup": "0",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_attributes_for_group_search": "",
            "ldap_attributes_for_user_search": "",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_base": "OU=Company,DC=Domain,DC=local",
            "ldap_base_groups": "OU=Groups,OU=Company,DC=Domain,DC=local",
            "ldap_base_users": "OU=Users,OU=Company,DC=Domain,DC=local",
            "ldap_cache_ttl": "600",
            "ldap_configuration_active": "1",
            "ldap_display_name": "displayname",
            "ldap_dn": "CN=Tech,OU=VM Horizons,DC=Domain,DC=Local",
            "ldap_dynamic_group_member_url": "",
            "ldap_email_attr": "",
            "ldap_experienced_admin": "0",
            "ldap_expert_username_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "ldap_expert_uuid_user_attr": "",
            "ldap_group_display_name": "cn",
            "ldap_group_filter": "(&(|(objectclass=group)))",
            "ldap_group_filter_mode": "0",
            "ldap_group_member_assoc_attribute": "member",
            "ldap_groupfilter_groups": "",
            "ldap_groupfilter_objectclass": "group",
            "ldap_host": "192.168.3.20",
            "ldap_login_filter": "(&(|(objectclass=person))(samaccountname=%uid))",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_attributes": "",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_nested_groups": "0",
            "ldap_override_main_server": "",
            "ldap_paging_size": "500",
            "ldap_port": "389",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_turn_on_pwd_change": "0",
            "ldap_user_display_name_2": "",
            "ldap_user_filter_mode": "0",
            "ldap_userfilter_groups": "Company-OwnCloud",
            "ldap_userfilter_objectclass": "person",
            "ldap_userlist_filter": "(&(|(objectclass=person))(|(|(memberof=CN=Company-OwnCloud,OU=Groups,OU=Company,DC=Domain,DC=local)(primaryGroupID=1174))))",
            "types": "authentication",
            "use_memberof_to_detect_membership": "1"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                |
| hasPagedResultSupport         |                                                                                                                                  |
| homeFolderNamingRule          |                                                                                                                                  |
| lastJpegPhotoLookup           | 0                                                                                                                                |
| ldapAgentName                 | CN=Tech,OU=VM Horizons,DC=Domain,DC=Local                                                                               |
| ldapAgentPassword             | ***                                                                                                                              |
| ldapAttributesForGroupSearch  |                                                                                                                                  |
| ldapAttributesForUserSearch   |                                                                                                                                  |
| ldapBackupHost                |                                                                                                                                  |
| ldapBackupPort                |                                                                                                                                  |
| ldapBase                      | OU=Company,DC=Domain,DC=local                                                                                               |
| ldapBaseGroups                | OU=Groups,OU=Company,DC=Domain,DC=local                                                                                     |
| ldapBaseUsers                 | OU=Users,OU=Company,DC=Domain,DC=local                                                                                      |
| ldapCacheTTL                  | 600                                                                                                                              |
| ldapConfigurationActive       | 1                                                                                                                                |
| ldapDynamicGroupMemberURL     |                                                                                                                                  |
| ldapEmailAttribute            |                                                                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                                                                |
| ldapExpertUUIDGroupAttr       |                                                                                                                                  |
| ldapExpertUUIDUserAttr        |                                                                                                                                  |
| ldapExpertUsernameAttr        |                                                                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                                               |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                                                        |
| ldapGroupFilterGroups         |                                                                                                                                  |
| ldapGroupFilterMode           | 0                                                                                                                                |
| ldapGroupFilterObjectclass    | group                                                                                                                            |
| ldapGroupMemberAssocAttr      | member                                                                                                                           |
| ldapHost                      | 192.168.3.20                                                                                                                     |
| ldapIgnoreNamingRules         |                                                                                                                                  |
| ldapLoginFilter               | (&(|(objectclass=person))(samaccountname=%uid))                                                                                  |
| ldapLoginFilterAttributes     |                                                                                                                                  |
| ldapLoginFilterEmail          | 0                                                                                                                                |
| ldapLoginFilterMode           | 0                                                                                                                                |
| ldapLoginFilterUsername       | 1                                                                                                                                |
| ldapNestedGroups              | 0                                                                                                                                |
| ldapOverrideMainServer        |                                                                                                                                  |
| ldapPagingSize                | 500                                                                                                                              |
| ldapPort                      | 389                                                                                                                              |
| ldapQuotaAttribute            |                                                                                                                                  |
| ldapQuotaDefault              |                                                                                                                                  |
| ldapTLS                       | 0                                                                                                                                |
| ldapUserDisplayName           | displayname                                                                                                                      |
| ldapUserDisplayName2          |                                                                                                                                  |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=Company-OwnCloud,OU=Groups,OU=Company,DC=Domain,DC=local)(primaryGroupID=1174)))) |
| ldapUserFilterGroups          | Company-OwnCloud                                                                                                                 |
| ldapUserFilterMode            | 0                                                                                                                                |
| ldapUserFilterObjectclass     | person                                                                                                                           |
| ldapUuidGroupAttribute        | auto                                                                                                                             |
| ldapUuidUserAttribute         | auto                                                                                                                             |
| turnOffCertCheck              | 0                                                                                                                                |
| turnOnPasswordChange          | 0                                                                                                                                |
| useMemberOfToDetectMembership | 1                                                                                                                                |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------+

```
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Linux Mint

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
...repeats a bunch
{"reqId":"JMQCNX9uuQ3cg6qGKu3l","remoteAddr":"8.8.8.8","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/home\/cr\/public_html\/lib\/private\/Files\/Filesystem.php:806\nStack trace:\n#0 \/home\/cr\/public_html\/lib\/private\/Files\/View.php(2018): OC\\Files\\Filesystem::normalizePath('\/sscstech\/files...')\n#1 \/home\/cr\/public_html\/lib\/private\/Files\/View.php(1156): OC\\Files\\View->unlockFile('\/OC-Storage\/Sca...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/home\/cr\/public_html\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/home\/cr\/public_html\/lib\/private\/Files\/Filesystem.php#806","level":3,"time":"2017-03-24T17:36:08+00:00","method":"GET","url":"\/index.php\/s\/yFxbec8m5xMVgTL\/download?path=%2F&files=Research%20-%20Scalp%20-%20FINAL.mp4","user":"--","version":"11.0.2.7"}
.....repeats a bunch
{"reqId":"JAZaSgQKS2ZUZ5n9GqOa","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/cr\/public_html\/lib\/private\/AppConfig.php#292","level":3,"time":"2017-03-24T17:47:52+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
avatar.imageplaceholder is not a function
```
</details>

**Comment by MorrisJobke** [comment] 2017-03-27 04:13
Duplicate of #3451

**Closed by MorrisJobke** 2017-03-27 04:13 UTC
