### ISSUE TITLE
No invitation mail is send to the attendees of an appointment of a shared calendar (but cancel mail is)

### ISSUE THREAD

**Issue by mxlse** [nextcloud/server#4870] opened 2017-05-15 11:01 UTC
### Steps to reproduce
1. Create a shared calendar
2. Create an appointment with one of the users the calendar is shared with (in Nextcloud or via Thunderbird)
3. Invite an attendee to the appointment

### Expected behaviour
An invitation should be send to the attendees. This is working fine if I send an invitation from the personal (not shared) calendar - with Thunderbird and the Nextcloud interface. 

### Actual behaviour
No invitation mail is send. The more or less annoying thing is that a cancel mail IS send, when the appointment gets deleted, although the invitation mail was missing.

### Server configuration

**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** Apache 2.4.18 behind nginx 1.11.12 reverse proxy

**Database:** mysql 5.7.18

**PHP version:** php 7.1.2-3 (oracle)

**Nextcloud version:** 11.0.2 / 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from owncloud / nextcloud 10

**Where did you install Nextcloud from:** https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' =>
  array (
    0 => 'A',
    1 => 'B',
    2 => 'C',
    3 => 'D',
  ),
  'trusted_proxies' =>
  array (
    0 => 'xxx.xxx.xxx.xxx',
  ),
  'forwarded_for_headers' =>
  array (
    0 => 'HTTP_X_FORWARDED',
    1 => 'HTTP_FORWARDED_FOR',
  ),
  'datadirectory' => '/home/nextcloud',
  'overwrite.cli.url' => 'https://my.url.com',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'loglevel' => 4,
  'theme' => '',
  'mail_from_address' => '***',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '***',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '***',
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
  'mail_smtpport' => '25',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** Chrome/Opera/Vivaldi/Firefox

**Operating system:** Windows (7, 8, 10), Linux (Ubuntu, Mint,...)

**Comment by mxlse** [comment] 2017-05-30 08:42
I just did the update to Nextcloud 12.0.0 - still the same.

**Comment by MorrisJobke** [comment] 2017-08-30 08:56
cc @georgehrke

**Comment by tobiasv** [comment] 2017-08-30 13:20
We have exactly the same issue. We still use version 11.

**Comment by MorrisJobke** [comment] 2017-09-03 18:57
Duplicate of #3830

**Closed by MorrisJobke** 2017-09-03 18:57 UTC
Labels: 0. Needs triage, bug, feature: dav
