### ISSUE TITLE
Current user cannot edit groups (18RC2)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#18964] opened 2020-01-17 19:59 UTC
### Steps to reproduce
1. Open user management, all users except logged-in user have "Edit"-pencil icons
2. Try to add the current (in my case admin) user to another group

### Expected behaviour
As logged-in (admin) user, I should be able to add myself to extra groups.

### Actual behaviour
As logged-in (admin) user, I cannot edit my group memberships.

### relevant Server configuration
**Nextcloud version:** 18.0.0 RC2, updated from 17.0.2, originally installed from nextcloud.com/install
**Signing status:**: No errors have been found.

**Comment by kesselb** [comment] 2020-01-17 20:41
Duplicate of https://github.com/nextcloud/server/issues/18530?

**Comment by nursoda** [comment] 2020-01-17 20:52
Another use case (group membership instead of quota), but: Yes.

**Closed** 2020-03-10 15:16 UTC
Labels: 0. Needs triage, bug

**Comment by helgator** [comment] 2020-03-28 12:57
I am running Nextcloud 18.0.3 and still cant edit my own account in index.php/settings/users, meaning I cannot add myself to existing groups. Or did the workflow change? Thanks

**Comment by nursoda** [comment] 2020-03-28 17:00
Will be fixed in 18.0.4 due end of April.

**Comment by nursoda** [comment] 2020-04-10 00:02
@rullzer / @juliushaertl : https://github.com/nextcloud/server/pull/19882 is NOT present in 19.0 beta 2 – there, still the admin user cannot modify himself.
