### ISSUE TITLE
Contacts menu doesn't list users

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#28039] opened 2021-07-19 00:48 UTC
Currently running Nextcloud 21.0.3 I have 7 users but I can only see one under my contacts menu I don't recall this being an issues before. 

ran the following command but no luck. 

root@nextcloud:/var/www/nextcloud# sudo -u www-data php occ dav:sync-system-addressbook
Syncing users ...
    7 [============================]
 

![image](https://user-images.githubusercontent.com/59488153/126087991-2f82f24a-4154-4c0e-bc84-6490be6811cd.png)

**Comment by szaimen** [comment] 2021-08-08 15:39
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-08-08 15:39 UTC
Labels: bug, 0. Needs triage

**Comment by andyxheli** [comment] 2021-08-09 13:30
@szaimen Thank you! Once i get the update release i will update the server still 21.0.4 still not showing up under the servers available update.

**Comment by andyxheli** [comment] 2021-08-14 12:29
@szaimen I just updated to 21.0.4 and still the same issue i can only see one user under the contacts

**Comment by szaimen** [comment] 2021-08-14 13:05
Sounds like https://github.com/nextcloud/server/issues/10317

**Comment by andyxheli** [comment] 2021-08-14 13:22
@szaimen Thank you for the quick update.
