### ISSUE TITLE
NC 13 Server side Encryption breaks few things

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#8410] opened 2018-02-17 14:07 UTC
Hello, 
i tried few things on my Testinstallation with Nextcloud 13 and the Encryptionmodule with enabled Master Key,

### Steps to reproduce
1. enable the encryption with php occ encryption:enable
2. enable the module
3. run php occ encryption:encrypt --all
4. Upload an file or create one.

### Actual behaviour
You cant delete or move files.

### Server configuration

**Operating system**: 

ubuntu 16.04.3 LTS
**Web server:** 

Apache2.4

**Database:** 

mysql Server version: 5.7.21-0ubuntu0.16.04.1 (Ubuntu)

**PHP version:** 

**Nextcloud version:** (see Nextcloud admin page) 

Nextcloud 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

updated from 12.0.4

**Where did you install Nextcloud from:** 

from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - drop_account: 0.0.6
  - dropit: 0.1.0
  - encryption: 2.0.0
  - end_to_end_encryption: 1.0.2
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_frommail: 0.1.0
  - files_fulltextsearch: 0.6.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - fulltextsearch_elasticsearch: 0.5.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - mood: 0.3.3
  - music: 0.5.5
  - nextant: 1.0.8
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocdownloader: 1.5.6
  - ojsxc: 3.3.2
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - ransomware_protection: 1.1.0
  - registration: 0.3.1
  - richdocuments: 2.0.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - spreed: 3.0.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_usage_report: 1.0.1
  - workflowengine: 1.3.0
Disabled:
  - audioplayer
  - cms_pico
  - defaultgroup
  - files_clipboard
  - fulltextsearch
  - phonetrack
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dasnetzundich.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.dasnetzundich.de",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** 

local folder

**Are you using encryption:** 
yes

### Client configuration
**Browser:**

Opera Desktop and mobile

**Operating system:**

Ubuntu Edge

#### Web server error log
<details>
<summary>Web server error log</summary>

```

2018-02-17 14:36:50 | Error | 151.252.220.149 |   | [core:crit] (13)Permission denied: AH00529: /var/www/vhosts/domain.tld/cloud.domain.tld/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/dasnetzundich.de/cloud.dasnetzundich.de/data/' is executable
-- | -- | -- | -- | --
2018-02-17 14:36:56 | Error | 151.252.220.149 | 404 | GET /index.php/core/preview.png?file=%2Ftest.txt&c=8b5ed7cbda64a801c80d4518b3a5e858&x=32&y=32&forceIcon=0 HTTP/1.1 |   |   | 981 | SSL/TLS-Zugriff für Apache
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-02-17 14:36:59 | Error | 151.252.220.149 | 403 | DELETE /remote.php/webdav/testencryption.odt HTTP/1.1 |   |   | 1.19 K | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:04 | Error | 151.252.220.149 | 403 | DELETE /remote.php/webdav/test.txt HTTP/1.1 |   |   | 1.19 K | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:18 | Error | 151.252.220.149 | 404 | GET /index.php/core/preview.png?file=%2Ftest.txt&c=8b5ed7cbda64a801c80d4518b3a5e858&x=32&y=32&forceIcon=0 HTTP/1.1 |   |   | 1.11 K | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:28 | Error | 151.252.220.149 | 404 | GET /index.php/core/preview.png?file=%2Ftest.txt&c=8b5ed7cbda64a801c80d4518b3a5e858&x=32&y=32&forceIcon=0 HTTP/1.1 |   |   | 981 | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:28 | Error | 151.252.220.149 | 403 | MOVE /remote.php/webdav/test.txt HTTP/1.1 |   |   | 1.19 K | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:29 | Error | 151.252.220.149 | 404 | GET /index.php/core/preview.png?file=%2Ftestencryption.odt&c=e7cfe353f49d0881e12b86417834ad55&x=32&y=32&forceIcon=0 HTTP/1.1 |   |   | 981 | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:29 | Error | 151.252.220.149 | 404 | GET /index.php/core/preview.png?file=%2Ftest.txt&c=8b5ed7cbda64a801c80d4518b3a5e858&x=32&y=32&forceIcon=0 HTTP/1.1 |   |   | 981 | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:30 | Error | 151.252.220.149 | 403 | MOVE /remote.php/webdav/test.txt HTTP/1.1 |   |   | 1.19 K | SSL/TLS-Zugriff für Apache
2018-02-17 14:37:30 | Error | 151.252.220.149 | 403 | MOVE /remote.php/webdav/testencryption.odtHTTP/1.1 |   |   | 1.19 K | SSL/TLS-Zugriff für Apache
2018-02-17 14:41:01 | Error | 151.252.220.149 | 403 | PROPFIND /remote.php/webdav/docs/error401.png HTTP/1.1 |   |   | 1.19 K | SSL/TLS-Zugriff für Apache
2018-02-17 14:44:19 | Error | 151.252.220.149 | 404 | GET /index.php/core/preview.png?file=%2Fdocs%2Ftest.txt&c=c312e5d08bacb15450f6535653623b86&x=32&y=32&forceIcon=0 HTTP/1.1 |   |   | 981 | SSL/TLS-Zugriff für Apache
2018-02-17 14:44:22 | Error | 151.252.220.149 | 404 | GET /index.php/core/preview.png?file=%2Fdocs%2Ftest.txt&c=1518877275&x=32&y=32&forceIcon=0 HTTP/1.1


```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

	no app in context	OCP\AppFramework\QueryException: Could not resolve filesService! Class filesService does not exist
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/AppFramework/Utility/SimpleContainer.php - line 118: OC\AppFramework\Utility\SimpleContainer->resolve('filesService')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/ServerContainer.php - line 132: OC\AppFramework\Utility\SimpleContainer->query('filesService')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 441: OC\ServerContainer->query('filesService')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/AppFramework/Utility/SimpleContainer.php - line 74: OC\AppFramework\DependencyInjection\DIContainer->query('filesService')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/AppFramework/Utility/SimpleContainer.php - line 97: OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/AppFramework/Utility/SimpleContainer.php - line 118: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Files_FullT...')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 467: OC\AppFramework\Utility\SimpleContainer->query('OCA\\Files_FullT...')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 438: OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Files_FullT...')
/var/www/vhosts/domain.tld/cloud.domain.tld/apps/files_fulltextsearch/lib/Hooks/FilesHooks.php - line 52: OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Files_FullT...')
/var/www/vhosts/domain.tld/cloud.domain.tld/apps/files_fulltextsearch/lib/Hooks/FilesHooks.php - line 96: OCA\Files_FullTextSearch\Hooks\FilesHooks getController()
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/legacy/hook.php - line 106: OCA\Files_FullTextSearch\Hooks\FilesHooks onFileRename(Array)
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/Files/View.php - line 841: OC_Hook emit('OC_Filesystem', 'post_rename', Array)
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/Encryption/DecryptAll.php - line 260: OC\Files\View->rename('/Admin/files/te...', '/Admin/files/te...')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/Encryption/DecryptAll.php - line 230: OC\Encryption\DecryptAll->decryptFile('/Admin/files/te...')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/Encryption/DecryptAll.php - line 187: OC\Encryption\DecryptAll->decryptUsersFiles('Admin', Object(Symfony\Component\Console\Helper\ProgressBar), 'Admin (1 of 7)')
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/Encryption/DecryptAll.php - line 99: OC\Encryption\DecryptAll->decryptAllUsersFiles('Testme')
/var/www/vhosts/domain.tld/cloud.domain.tld/core/Command/Encryption/DecryptAll.php - line 154: OC\Encryption\DecryptAll->decryptAll(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), '')
/var/www/vhosts/domain.tld/cloud.domain.tld/3rdparty/symfony/console/Command/Command.php - line 264: OC\Core\Command\Encryption\DecryptAll->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
/var/www/vhosts/domain.tld/cloud.domain.tld/3rdparty/symfony/console/Application.php - line 874: Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
/var/www/vhosts/domain.tld/cloud.domain.tld/3rdparty/symfony/console/Application.php - line 228: Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Encryption\DecryptAll), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
/var/www/vhosts/domain.tld/cloud.domain.tld/3rdparty/symfony/console/Application.php - line 130: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
/var/www/vhosts/domain.tld/cloud.domain.tld/lib/private/Console/Application.php - line 173: Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
/var/www/vhosts/domain.tld/cloud.domain.tld/console.php - line 90: OC\Console\Application->run()
/var/www/vhosts/domain.tld/cloud.domain.tld/occ - line 11: require_once('/var/www/vhosts...')
{main}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2018-02-27 09:48
cc @nextcloud/encryption

**Comment by skjnldsv** [comment] 2020-08-25 09:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Comment by skjnldsv** [comment] 2020-08-25 09:18
I also suggest waiting for 20 as encryption is changed a lot there iirc

**Closed by skjnldsv** 2020-08-25 09:17 UTC
Labels: 0. Needs triage, bug, feature: encryption (server-side)
