### ISSUE TITLE
Password reset text not visible against light background

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#17498] opened 2019-10-09 21:30 UTC
1. Use the theming app to change the background. Choose a light photograph   
2. The Password reset text is white and may become invisible. 

Make a blue background field around the reset password, just like the other login fields.

**Comment by szaimen** [comment] 2021-05-26 13:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-26 13:45 UTC
Labels: 0. Needs triage, enhancement
