### ISSUE TITLE
files_external:notify Invalid Login

### ISSUE THREAD

**Issue by philippe-opendsi** [nextcloud/server#10401] opened 2018-07-26 08:12 UTC
Steps to reproduce
Configure external storage with login and password store in database.
Go to your nexctloud 
Execute 
sudo -u www-data php occ   files_external:notify [ID]
or
sudo -u www-data php occ   files_external:notify [ID] -u user -p password

Expected behaviour
  [Icewind\SMB\Exception\AuthenticationException]  
  Invalid login                                    
                  

Yes i'm unsing good credential ;) 

Server configuration

Operating system: Debian 9 

Web server: Nginx 1.15.0

Database: MariaDB (mysql Ver 15.1 Distrib 10.3.7-MariaDB,)

PHP version: 7.2

Nextcloud version: (see Nextcloud admin page) 13.0.4

Updated from an older Nextcloud/ownCloud or fresh install: fresh install

List of activated apps:
App list : 
External storage
Ldap

Nextcloud configuration:
Config report

Are you using encryption: no

Client configuration

Browser: Mozilla Firefox 

Operating system: Debian9

**Comment by MorrisJobke** [comment] 2018-07-26 14:08
cc @icewind1991

**Comment by MorrisJobke** [comment] 2018-11-01 22:28
Duplicate of #6765

**Closed by MorrisJobke** 2018-11-01 22:28 UTC
Labels: bug, feature: external storage
