### ISSUE TITLE
Cannot delete a folder on external storage Amazon S3 when it has a similar name to another folder

### ISSUE THREAD

**Issue by Peterede** [nextcloud/server#25370] opened 2021-01-29 01:27 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Create a folder in an external storage on Amazon S3 called Test
2.Create another folder in external storage on Amazon S3 called Test EU
3.Try to delete or rename the Test folder and it will not rename.  Deleting the folder will cause it to reappear on refreshing the page.

### Expected behaviour
The folder should be renamed or deleted.

### Actual behaviour
The folder cannot be renamed or deleted.  Upon deleted and a refresh the folder is still there.

### Server configuration

**Operating system:**
Ubuntu
**Web server:**
Apache
**Database:**
 PostgreSQL 12.5
**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
20.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
snap
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** yes

**Comment by szaimen** [comment] 2021-06-22 14:37
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by avinash-singhSF** [comment] 2021-08-05 06:38
I am also getting same issue, in external storage Amazon S3.

**Steps to reproduce**
1. Create a folder named test1
2. Again try to create new folder named test (Error: Could not create folder "test" because it already exists)
3. Or try to rename test1 to test (Error: The name "test" is already used in the folder "/aws-path/". Please choose a different name.)

While this is working properly on other folders except external storage Amazon S3

Server configuration
Operating system:  Linux 5.4.0-1039-aws x86_64
Database: MySql 8.0.20
PHP version: 7.4.16
Nextcloud version: 20.0.8

**Comment by szaimen** [comment] 2021-08-08 13:20
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

**Comment by avinash-singhSF** [comment] 2021-08-10 13:27
> Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

After updating the NC version to 21.0.4 still I am getting same issue in external storage Amazon S3.

**Comment by szaimen** [comment] 2023-01-23 10:46
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:42 UTC
Labels: bug, needs info, 0. Needs triage, feature: object storage
