### ISSUE TITLE
Error could not find resource marked.min.js 

### ISSUE THREAD

**Issue by qoaa** [nextcloud/server#15897] opened 2019-06-07 19:37 UTC
### Steps to reproduce
1. On any file setting it to shared
2. Anyone going to the shared link for said file causes error in log 
3. Could not find resource core/vendor/marked/marked.min.js to load

### Expected behaviour
Tell us what should happen

I would suspect the log shouldn't throw errors for loading a shared link for a file. 

### Actual behaviour
Tell us what happens instead

The shared file link works, it allows person going to link to download file but each time that link is accessed by anyone it causes same errors. Plus the marked.min.js file doesn't even exist, the directory /marked doesn't exist either. 

### Server configuration

**Operating system**:
Debian 9.9

**Web server:**
Apache 2.4.25

**Database:**
MariaDB 10.1.38

**PHP version:**
php 7.3.3-1
**Nextcloud version:** (see Nextcloud admin page)
16.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updates from previous nextcloud version

**Where did you install Nextcloud from:**
Official site

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dashboard: 6.0.0
  - dav: 1.9.2
  - extract: 1.2.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_retention: 1.5.1
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trackdownloads: 1.5.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - groupfolders: 4.0.2
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - music: 0.9.5
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ocdownloader: 1.7.0
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - radio: 0.6.5
  - ransomware_protection: 1.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - socialsharing_email: 1.0.5
  - support: 1.0.0
  - survey_client: 1.4.0
  - suspicious_login: 1.0.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - external
  - files_clipboard
  - quota_warning
  - recommendations
  - socialsharing_facebook
  - spreed
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dude-suit.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cloud.dude-suit.net",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "simpleSignUpLink.shown": false,
        "loglevel": 2,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "enabled_PreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MP4",
            "OC\\Preview\\MKV",
            "OC\\Preview\\Movie"
        ],
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Error	Could not find resource core/vendor/marked/marked.min.js to load	41 minutes ago
Error	Could not find resource core/vendor/marked/marked.min.js to load	
7 hours ago
Error	Could not find resource core/vendor/marked/marked.min.js to load	
7 hours ago
Error	Could not find resource core/vendor/marked/marked.min.js to load	
7 hours ago
Error	Could not find resource core/vendor/marked/marked.min.js to load	
15 hours ago
```
</details>

**Comment by ChristophWurst** [comment] 2019-06-11 11:56
This is most likely caused by an app. Could you temporarily try disabling all non-core apps and try to reproduce the problem. The `marked` library is shipped in the js bundle since Nextcloud 16 (https://github.com/nextcloud/server/pull/13474) and therefore it shouldn't be included directly anymore. I suspect an app still tries to include it.

**Comment by rkaraba** [comment] 2019-06-11 12:40
The most likely caused by Text editor app.

I made some tests on demo.nextcloud.com
I made shared link for file \Documents\About.odt

Each time that link is accessed by anyone it causes this error
[jsresourceloader] Error: Could not find resource core/vendor/marked/marked.min.js to load

GET /ab5eekum/index.phppEDg9QbS
from 193.187.63.2 at 2019-06-11T14:34:53+02:00

It stoped when i disabled Text editor app

**Comment by ChristophWurst** [comment] 2019-06-11 12:47
> It stoped when i disabled Text editor app

Strange, that apps actually got a fix for this: https://github.com/nextcloud/files_texteditor/pull/155

**Comment by rkaraba** [comment] 2019-06-11 12:51
I dont understand why Text editor affects files like odt or zip

**Comment by enoch85** [comment] 2019-06-11 13:57
> Strange, that apps actually got a fix for this: nextcloud/files_texteditor#155

Not merged?

**Comment by ChristophWurst** [comment] 2019-06-11 14:30
Ah yes :see_no_evil:

**Comment by qoaa** [comment] 2019-06-12 02:10
Okay, I haven't had the time to go through each app, but I'll do that, I'll disable non core apps and check to single out which app may be causing the error in the log.

I was confused since I have previous nextcloud versions which the updater auto backs up and I noticed they have the marked directory and js file but this current version didn't have that directory and file.

**Comment by qoaa** [comment] 2019-06-22 19:03
The problem is the text editor app. Disabling fixes it as rkaraba posted. I forgot to update thread, should I go ahead and close this thread or leave it?

**Comment by kesselb** [comment] 2019-06-23 19:53
Hmm. The fix is not published yet but the code is merged. I think we can close it and hope that a new version of `files_texteditor` is published soon.

**Closed by kesselb** 2019-06-23 19:53 UTC
Labels: 0. Needs triage, bug

**Comment by warnerbryce** [comment] 2019-09-09 16:33
I had this problem with Nextcloud 16.0.3, so i upgraded to 16.0.4.
I still have the same problem but it doesn't appear on the logs. 
Before i got : Could not find resource core/vendor/marked/marked.min.js to load when somebody want to put a large file on the shared folder. After the upgrade i have no log, but i still cannot put the file in the shared folder...

**Comment by DevDorrejo** [comment] 2019-12-04 20:20
hello, have the error: **Could not find resource core/js/oc-backbone-webdav.js to load**

**NextCloud: 17.0.1.1**

**Comment by ChristophWurst** [comment] 2019-12-05 09:39
Please use the ticket search to find *open* tickets. Otherwise please file a new bug report by filling out the issue template. Thanks :v:
