### ISSUE TITLE
[Bug]: Exception during update to 28.0.2: Database error when running migration 28000Date20230906104802 for app core Index name "nid" for table "oc_social_3_stream" collides with the constraint on table "oc_social_3_cache_actor".

### ISSUE THREAD

**Issue by zaferad** [nextcloud/server#43266] opened 2024-02-01 17:24 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

During upgrade from latest Nextloud 27 to 28.0.2 I get the following bug:

Aktualisierung auf 28.0.2
Exception: Database error when running migration 28000Date20230906104802 for app core Index name "nid" for table "oc_social_3_stream" collides with the constraint on table "oc_social_3_cache_actor".

If I drop the index 'nid' on the table oc_social_3_cache_actor, update runs through.

### Steps to reproduce

1. Upgrade to major 28
2.
3.

### Expected behavior

Smooth update process

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
## Server configuration detail

**Operating system:** Linux 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 8.0.33

**PHP version:** 8\.2.15

Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, gmp, json, iconv, SPL, session, mbstring, pcntl, standard, posix, random, Reflection, imap, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, zip, mysqlnd, cgi-fcgi, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, sodium, ldap, tidy, pdo_pgsql, pdo_sqlite, igbinary, redis, Zend OPcache

**Nextcloud version:** 28\.0.2 - 28.0.2.5

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

\[\]
</details>



<details><summary>Configuration (config/config.php)</summary>


{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.alrahman.ch"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.alrahman.ch",
    "dbtype": "mysql",
    "version": "28.0.2.5",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 0,
    "default_phone_region": "CH",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "mysql.utf8mb4": true,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb",
        "social"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```

</details>

**Cron Configuration:** Array
(
[backgroundjobs_mode] => cron
[lastcron] => 1706807402
)

**External storages:** files_external is disabled

**Encryption:** no

**User-backends:**

* OC\\User\\Database

**Talk configuration:**

STUN servers

* stun.nextcloud.com:443

TURN servers

* no custom server configured

Signaling servers (mode: default):

* SIP dialin is disabled
* SIP dialout is disabled
* no custom server configured

Recording servers:

* Recording is enabled
* Recording consent is set to "default"
* no recording server configured

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
```


### List of activated Apps

```shell
<details><summary>List of activated apps</summary>


Enabled:
 - activity: 2.20.0
 - admin_audit: 1.18.0
 - bruteforcesettings: 2.8.0
 - calendar: 4.6.4
 - circles: 28.0.0-dev
 - cloud_federation_api: 1.11.0
 - comments: 1.18.0
 - contacts: 5.5.1
 - contactsinteraction: 1.9.0
 - dashboard: 7.8.0
 - dav: 1.29.1
 - deck: 1.12.1
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - firstrunwizard: 2.17.0
 - forms: 4.0.0
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - mail: 3.5.5
 - nextcloud_announcements: 1.17.0
 - notes: 4.9.2
 - notifications: 2.16.0
 - oauth2: 1.16.3
 - password_policy: 1.18.0
 - photos: 2.4.0
 - polls: 6.0.1
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - spreed: 18.0.3
 - support: 1.11.0
 - survey_client: 1.16.0
 - systemtags: 1.18.0
 - text: 3.9.1
 - theming: 2.3.0
 - twofactor_backupcodes: 1.17.0
 - twofactor_totp: 10.0.0-beta.2
 - updatenotification: 1.18.0
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - workflowengine: 2.10.0
Disabled:
 - checksum: 1.2.3
 - encryption: 2.16.0
 - files_external
 - files_markdown: 2.4.1
 - files_mindmap: 0.0.30
 - files_rightclick: 1.6.0
 - occweb: 0.1.1
 - socialsharing_email: 3.0.1
 - suspicious_login
 - user_ldap
```

</details>
```


### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Fehler	no app in context	
Exception
Database error when running migration 28000Date20230906104802 for app core Index name "nid" for table "oc_social_3_stream" collides with the constraint on table "oc_social_3_cache_actor".

01.02.2024, 17:59:38	

Information	updater	
\OC\Updater::dbUpgradeBefore: Updating database schema

01.02.2024, 17:59:38	

Information	updater	
OC\Repair\Events\RepairStepEvent: Repair step: Drop account terms table when migrating from ownCloud

01.02.2024, 17:59:38	

Information	updater	
OC\Repair\Events\RepairStepEvent: Repair step: Copy data from accounts table when migrating from ownCloud

01.02.2024, 17:59:37	

Information	updater	
OC\Repair\Events\RepairInfoEvent: Repair info: All tables already have the correct collation -> nothing to do

01.02.2024, 17:59:37	

Information	updater	
OC\Repair\Events\RepairStepEvent: Repair step: Repair MySQL collation

01.02.2024, 17:59:37	

Fehlersuche	core	
starting upgrade from 27.1.6.2 to 28.0.2.5

01.02.2024, 17:59:37	

Information	updater	
\OC\Updater::maintenanceEnabled: Turned on maintenance mode

01.02.2024, 17:59:37	

Information	updater	
\OC\Updater::setDebugLogLevel: Set log level to debug

01.02.2024, 17:59:37	

Information	no app in context	
RouteNotFoundException
Unable to generate a URL for the named route "polls.page.index" as such route does not exist.

01.02.2024, 17:59:35
```

**Comment by joshtrichards** [comment] 2024-02-01 17:29
Duplicate of #41253

**Closed by joshtrichards** 2024-02-01 17:29 UTC
Labels: bug, 0. Needs triage
