### ISSUE TITLE
External storage without relaying all traffic

### ISSUE THREAD

**Issue by eortegaz** [nextcloud/server#37693] opened 2023-04-12 18:36 UTC
**The problem:** With the external storage app, we still relay all the traffic from cloud storage, through our instance and to the client. This means incurring significant bandwidth and processing power at our NextCloud server.

Since most cloud storage providers (Wasabi, Backblaze, Hetzner, etc) already offer a S3-compatible API to create a signed URL, or some form of auth token our client can include in the header to request the file directly from the cloud storage provider, this seems like a logical thing to do.

Our NextCloud installation would ideally be used as the frontend/authentication server that maintains assets for the UI (filenames, metadata, cached thumbnails, etc.) without serving large transfers.

*Note: instead of getting cloud storage with NextCloud preinstalled, managing authentication locally would be preferred and more secure.

**Comment by joshtrichards** [comment] 2023-08-07 21:44
Duplicate of #14675. 

@eortegaz If you agree this is the same request for enhancement, give that other issue a thumbs up and close this Issue out to avoid confusion. Thanks!

**Comment by joshtrichards** [comment] 2023-08-20 20:19
Closing in favor of #14675.

**Closed** 2023-08-20 20:26 UTC
Labels: enhancement, 0. Needs triage
