### ISSUE TITLE
Comments system text goes outside text box [Bug]: 

### ISSUE THREAD

**Issue by mb0x88** [nextcloud/server#38916] opened 2023-06-20 22:48 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The default greyed out test inside comments go outside of the comments box

<img width="305" alt="Screenshot 2023-06-21 at 10 13 55 am" src="https://github.com/nextcloud/server/assets/106029773/280df547-0c30-4993-9dfd-809c7f9f1af9">
<img width="324" alt="Screenshot 2023-06-21 at 10 19 58 am" src="https://github.com/nextcloud/server/assets/106029773/69760c43-a9c7-4170-b5c2-793021e40e82">

### Steps to reproduce

1. Update to Nextcloud 26.0.2 from 24.* using command line

### Expected behavior

I expect the default system text to remain inside the text box

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.2.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "default_phone_region": "NZ",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "2525",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "theme": "",
        "loglevel": 2,
        "data-fingerprint": "b3b1077175b79312576b1c4c546b0174"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - calendar: 4.4.2
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - external: 5.1.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_accesscontrol: 1.16.0
  - files_automatedtagging: 1.16.1
  - files_lock: 27.0.0
  - files_pdfviewer: 2.7.0
  - files_retention: 1.15.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - groupfolders: 14.0.2
  - impersonate: 1.13.1
  - login_notes: 1.2.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - password_policy: 1.16.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - quota_warning: 1.17.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - sharepoint: 1.14.0
  - side_menu: 3.8.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - terms_of_service: 2.2.0
  - text: 3.7.2
  - theming: 2.1.1
  - theming_customcss: 1.14.0
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - welcome: 1.0.9
  - workflowengine: 2.8.0
Disabled:
  - announcementcenter: 6.3.1 (installed 6.3.1)
  - cms_pico: 1.0.20 (installed 1.0.20)
  - collectives: 1.5.0 (installed 1.5.0)
  - contacts: 4.2.2 (installed 4.2.2)
  - deck: 1.7.2 (installed 1.7.2)
  - encryption: 2.14.0
  - end_to_end_encryption: 1.10.0 (installed 1.10.0)
  - files_external: 1.18.0
  - firstrunwizard: 2.15.0 (installed 2.12.0)
  - forms: 2.5.1 (installed 2.5.1)
  - mail: 1.14.1 (installed 1.14.1)
  - mail_roundcube: 1.0.1 (installed 1.0.1)
  - maps: 0.2.1 (installed 0.2.1)
  - metadata: 0.17.0 (installed 0.17.0)
  - news: 19.0.0 (installed 19.0.0)
  - notes: 4.5.1 (installed 4.5.1)
  - passwords: 2022.10.20 (installed 2022.10.20)
  - photos: 2.2.0 (installed 1.5.0)
  - richdocuments: 6.3.1 (installed 6.3.1)
  - richdocumentscode: 22.5.702 (installed 22.5.702)
  - spreed: 14.0.5 (installed 14.0.5)
  - suspicious_login: 4.4.0
  - tasks: 0.14.5 (installed 0.14.5)
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.3.1)
  - weather_status: 1.6.0 (installed 1.3.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by solracsf** [comment] 2023-06-21 06:44
Duplicate of https://github.com/nextcloud/nextcloud-vue/issues/2027

**Closed by solracsf** 2023-06-21 06:44 UTC
Labels: bug, 0. Needs triage, 26-feedback
