### ISSUE TITLE
Recommended ownerships and permissions

### ISSUE THREAD

**Issue by tiiiecherle** [nextcloud/server#19462] opened 2020-02-13 18:22 UTC
Hey,

according to [this commit ](https://github.com/nextcloud/documentation/pull/431) the recommendation to change permissions was removed.

I add a few people from the the discussion as they should hopefully know the answer ;)
@LukasReschke 
@nachoparker 

After searching on the web I am confused what the recommended permissions are right now.

How do the following ones look? What should be changed to match the currently recommended and secure ones?

```
# directories on archlinux
NEXTCLOUD_INSTALL_DIR="/usr/share/webapps/nextcloud"
NEXTCLOUD_CONFIG_DIR="/etc/webapps/nextcloud"
if [[ -f "$NEXTCLOUD_INSTALL_DIR"/config/config.php ]]
then
    NEXTCLOUD_DATA_DIR="$(grep 'datadir' "$NEXTCLOUD_INSTALL_DIR"/config/config.php | awk '{print $3}' | cut -d "'" -f2)"
    #echo "$NEXTCLOUD_DATA_DIR"
fi

# nextcloud data
find "$NEXTCLOUD_DATA_DIR"/ -type f -print0 | xargs --no-run-if-empty -0 chmod 0640
find "$NEXTCLOUD_DATA_DIR"/ -type d -print0 | xargs --no-run-if-empty -0 chmod 0750
chown -R http:http "$NEXTCLOUD_DATA_DIR"

# nextcloud install
find "$NEXTCLOUD_INSTALL_DIR"/ -type f -print0 | xargs --no-run-if-empty -0 chmod 0640
find "$NEXTCLOUD_INSTALL_DIR"/ -type d -print0 | xargs --no-run-if-empty -0 chmod 0750
chmod ug+x "$NEXTCLOUD_INSTALL_DIR"/occ
chown -R http:http "$NEXTCLOUD_INSTALL_DIR"
find "$NEXTCLOUD_INSTALL_DIR"/ -type f -print0 | xargs --no-run-if-empty -0 chown root:http

# nextcloud config
find "$NEXTCLOUD_CONFIG_DIR"/ -type f -print0 | xargs --no-run-if-empty -0 chmod 0640
find "$NEXTCLOUD_CONFIG_DIR"/ -type d -print0 | xargs --no-run-if-empty -0 chmod 0750
chown -R http:http "$NEXTCLOUD_CONFIG_DIR"
```

Thanks in advance for the help.

**Comment by kesselb** [comment] 2020-02-13 20:52
I guess https://github.com/nextcloud/documentation/issues/1353 is also about that. Nextcloud needs to be able to alter `config.php` (until you disable it), data directory, and the `apps` folder (until you add another one and set the default one to read only). Anything else should be fine to be read only. 

Closing this report as duplicate of https://github.com/nextcloud/documentation/issues/1353.

**Closed by kesselb** 2020-02-13 20:52 UTC
Labels: 0. Needs triage, bug
