### ISSUE TITLE
[Bug]: Activity Report - Administrator removed you from group XXX

### ISSUE THREAD

**Issue by kcastner** [nextcloud/server#43272] opened 2024-02-01 19:57 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After a login, I'll get a email notification:
Administrator removed you from group XXX

If I open the web ui and login as administrator, the user is still in this group.

### Steps to reproduce

1.Use LDAP user to login
2.wait round about 30 min to get the email

### Expected behavior

Login without this email spam.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "*"
        ],
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false,
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "updater.release.channel": "stable"
    }
}

```

### List of activated Apps

```shell

Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.1
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0 (installed 2.13.0)
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - richdocumentscode: 23.5.604 (installed 23.5.604)
  - suspicious_login: 6.0.0
  - user_saml: 6.0.1 (installed 6.0.1)

```

### Nextcloud Signing status

```shell

No errors have been found.

```

### Nextcloud Logs

[nextcloud.log](https://github.com/nextcloud/server/files/14132595/nextcloud.log)

### Additional info
![image](https://github.com/nextcloud/server/assets/34087750/81b1d295-14f3-499b-88a0-58e57eb27a09)

![Screenshot_2024-02-01-18-07-05-345_com fsck k9](https://github.com/nextcloud/server/assets/34087750/80baafca-75c1-4cd6-8e89-505f2e2aea0f)

**Comment by kcastner** [comment] 2024-02-02 01:01
the missing content has been added

**Comment by koelle25** [comment] 2024-02-02 11:26
Same problem here, just the other way round:
> An Administrator has added you to the group XXXXXXXX

**Comment by avatar1024** [comment] 2024-02-02 22:24
Same problem here, I get the exact same notifications since the upgrade to NC28. In my case the user does not remain in the group though (or not added at all). In my case it is an LDAP group.

**Comment by avatar1024** [comment] 2024-02-03 08:58
Actually I've solved the problem on my end. I had to refresh the NC LDAP config as such:

1. Go NC LDAP Setting and to Advanced > Directory settings
2. Change Group-Member association from uid to something else
3. Test the config there, then click on "Verify setting settings and count users" in the Users tab, then on "Verify settings and count groups" in the Groups tab
4. Go back to the Group-Member association and change back to uid, then Test config and Verify/count users/groups and again, and then all users appear in the correct groups.

BTW for users to sync properly in LDAP groups I had to had uid as a login Attribute (in the Login Attribute tab in NC LDAP settings), but I did that before NC28 and my users and groups were synced correctly before the upgrade.

So solved but I should not have to do that after the upgrade though (and I'm wary of upgrading on my bigger Nextcloud instance)!

**Comment by susnux** [comment] 2024-02-03 13:18
cc @nextcloud/ldap

**Comment by avatar1024** [comment] 2024-02-03 21:28
And I'm getting all those weird notifications again :(

**Comment by ArneFallisch** [comment] 2024-02-21 08:44
I have the same problem getting the notification multiple times during the day, that an administrator removed from group or added you to group. However, the groupfolders can be used without any problems.

We run a NextCloud Server on Ubuntu 22.04 (no docker). I also open a topic in the Nextcloud help forum:
https://help.nextcloud.com/t/attempt-for-paging-and-dbalexception/181047

**Comment by pongraczi** [comment] 2024-04-12 13:27
Same in All-in-one:  
* Upgrade the master container and NC (27->28).
* These notifications arrive periodically for every user.

The LDAP backend is Univention, was working perfectly with NC 27.x.  
For reference, here is the directory settings of NC, which was working before.

![kep-23](https://github.com/nextcloud/server/assets/5891983/45a873d3-c45c-420e-892f-8b9c65891a15)

I changed Group-Member association to `memberUid`, there is no immediate results.  

The relevant ldap entry of the **IT** group is the following:   
```ldap
dn: cn=IT,cn=groups,dc=xxxx,dc=yyyyyyy,dc=zz
cn: IT
gidNumber: 5088
memberUid: pongi
uniqueMember: uid=pongi,cn=users,dc=xxxxxx,dc=yyyyyy,dc=zz
....
```

The relevant ldap entry of the user is the following:  
```ldap
dn: uid=pongi,cn=users,dc=xx,dc=yy,dc=zz
uid: pongi
uidNumber: 2015
memberOf: cn=TTTTT,cn=groups,dc=xx,dc=yy,dc=zz
memberOf: cn=DDDD,cn=groups,dc=xx,dc=yy,dc=zz
memberOf: cn=HHHH,cn=Builtin,dc=xx,dc=yy,dc=zz
memberOf: cn=GGGG,cn=groups,dc=xx,dc=yy,dc=zz
memberOf: cn=IT,cn=groups,dc=xx,dc=yy,dc=zz
....
```

The table `public.oc_ldap_user_mapping` is populated with all the ldap users (and some remnants, too) as expected.  
The table `public.oc_ldap_group_mapping` also populated with all the groups I wanted to import to NC from the Univention, so, this is also correct.  
The table `public.oc_ldap_group_membership` is populated with valid data, it seems only for those, who logged in.

So, I assume, with changing the group-member associtaion from gidNumber to memberUid now it should work. Until now (1 hour) I got no activity email, but I will wait to report it as a possible solution.

I did not read the sourcecode of the NC app (ldap) to confirm my theory, maybe later.

**Comment by pongraczi** [comment] 2024-04-12 14:03
Well, it seems now the public.oc_ldap_group_membership is populated with much more users and groups than before.  

Notice: even I have an LDAP filter for groups and the verify confirmed only 7 groups are exists, the ldap group table contains more (14, which is valid, but supposed to filtered out) and the group_membership table contains all relevant mappings, too.  
Even, the NC UI shows the expected groups only and memberships under Settings/Users, which seems correct.

So, **maybe I solved it** in my specific case. If not, I will report it.

I recommend to everybody to check your own ldap schema and entries and modify LDAP settings accordingly.  
You can dump your ldap like shown below and you can check your entries and correct names:  

```bash 
slapcat -f /etc/ldap/slapd.conf > /root/ldapdata.txt
```

**Comment by koelle25** [comment] 2024-05-29 06:51
I just solved my case of it! ✅ 
In our LDAP the Group had the `uniqueMember=<user-DN>`, but the User was missing the `memberOf=<group-DN>`.

**Comment by joshtrichards** [comment] 2024-09-06 17:41
Duplicate of #42195

**Closed by joshtrichards** 2024-09-06 17:41 UTC
Labels: bug, feature: ldap, 0. Needs triage, 28-feedback
