### ISSUE TITLE
Array to string conversion at /var/www/nextcloud/apps/dav/lib/CalDAV/Activity/Backend.php#561

### ISSUE THREAD

**Issue by olegchensky** [nextcloud/server#46601] opened 2024-07-18 05:56 UTC
### Steps to reproduce

1. It is enough to create a new event, and we receive 7–15 entries in log.
2.
3.

### Expected behavior

no errors

### Actual behaviour

errors in log

### Calendar app version

last, today updated

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment] 2024-07-18 08:07
Please post your Nextcloud version

**Comment by olegchensky** [comment] 2024-07-19 12:26
29.0.4

**Comment by dwaxweiler** [comment] 2024-07-30 06:03
This might be a duplicate of https://github.com/nextcloud/server/issues/37025.

**Comment by joshtrichards** [comment] 2024-08-02 15:50
Duplicate of #37025

**Closed by joshtrichards** 2024-08-02 15:50 UTC
Labels: bug, needs info, 0. Needs triage, feature: caldav
