### ISSUE TITLE
Update notification only shows [object Object]

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/server#21266] opened 2020-06-06 13:32 UTC
### Steps to reproduce
1. Update notification is enabled
2. Update is available
3. Update notification only shows [object Object]

### Expected behaviour
Update notification should show something like "New Update available"

### Actual behaviour
Update notification only shows [object Object]
![update-notification](https://user-images.githubusercontent.com/34797349/83945444-eb5b7400-a80a-11ea-8464-7ac45dfb86cc.png)

### Server configuration
**Operating system:**
Linux
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.3.11
**Nextcloud version:** (see Nextcloud admin page)
18.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Comment by nicolass67** [comment] 2020-06-11 15:33
Hello, 

I have this problem too. 
I use nextcloud since a while (version 14). 
Each time after an upgrade the error disappears ... a little bit time, till a new version is available, it reapperas 
I had this is all version 14 -> 18.0.3 (actual I use). 
It seems that when you disable the Update Notification Application it disappears too. So it' s a good clue to investigate this app. 

Regards,

**Comment by 9pr19** [comment] 2020-07-07 14:34
Hello, 
Seems that I have the same problem since a long time.

**Comment by danielmorlock** [comment] 2020-08-28 09:01
Same here

**Comment by andrewborell** [comment] 2020-08-31 14:15
nextcloud 18.07 I have the same problem since two versions back.  It went away after I installed version 18 for about two months then it came back. I observe this notification does not pop up on the calendar page but does on every other page.  Not sure if there is any correlation.

**Comment by husisusi** [comment] 2020-09-01 08:10
I had the same issue. After disabling and re-enabling the "Update Notification" and "Notifications" apps, the problem is resolved.

**Comment by szaimen** [comment] 2021-06-09 13:55
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by 9pr19** [comment] 2021-06-09 14:10
> 
> 
> Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

No more problem with  NC v21.0.1 and a few version before.
Actually I’ve reactivated an application like Notification or something like that and no more strange notifications since.

**Closed** 2021-06-09 14:11 UTC
Labels: 0. Needs triage, bug, needs info
