### ISSUE TITLE
When setting custom theme (outside of Theme app) it isn't taken

### ISSUE THREAD

**Issue by io-node** [nextcloud/server#5036] opened 2017-05-22 13:52 UTC
### Steps to reproduce
1. Create theme folder
2. create '/core/img/background.jpg' file
3.

### Expected behaviour
Expect background on login page to change

### Actual behaviour
Default NC background is shown
Also original core/css file structure has changed. The example theme folder is also not consistent as the file /themes/example/core/css/styles.css is not equal to /core/css/styles.scss

### Server configuration

**Operating system**: Debian 16.04
**Web server:** Apache 2.4.18
**Database:** MySQL 5.5.53
**PHP version:** 7.0.15
**Nextcloud version:** 12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from 12.0.0RC3
**Where did you install Nextcloud from:** NC website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - announcementcenter: 3.1.0
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - deck: 0.1.4
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.3
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.2
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.27
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - spreedme: 0.3.8
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - theming
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
       "instanceid": "occ3bgzu13dp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.tld",
            "192.168.7.245"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "\/media\/nextcloud",
        "overwrite.cli.url": "https:\/\/cloud.domain.tld",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "192.168.7.244",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "trusted_proxies": [
            "192.168.7.241",
            "127.0.0.1"
        ],
        "overwriteprotocol": "https",
        "overwritehost": "cloud.domain.tld",
        "overwritewebroot": "\/",
        "overwritecondaddr": "^192\\.168\\.7\\.[1-254]$",
        "mail_from_address": "cloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "domain.tld",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "maintenance": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "2",
        "log_rotate_size": "104857600",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "filesystem_check_changes": 1,
        "enable_previews": true,
        "preview_max_x": 800,
        "preview_max_y": 800,
        "preview_max_scale_factor": 4,
        "skeletondirectory": "\/media\/nextcloud\/skeleton",
        "session_keepalive": true,
        "activity_expire_days": 365,
        "theme": "***theme name***",
        "mail_smtpsecure": "tls",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "asset-pipeline.enabled": true,
        "share_folder": "\/Shares"
    }
}
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Google Chrome 58.0.3029.96

**Operating system:** Debian 8

### Logs

Logs don't show any issues regarding theming.

**Comment by juliushaertl** [comment] 2017-05-22 14:03
Please make sure you disable the theming app when using custom themes.

Why should /core/css/styles.scss and /themes/example/core/css/styles.css be equal?

**Comment by io-node** [comment] 2017-05-22 14:12
Sorry should have mentioned that I also disabled the theming app.

You would expect that an example would follow the same structure as the original theme. How else can somebody make changes to a theme, without having a similar file structure.

I have had 'styles.css' (as pre NC12) but this isn't loaded in the browser.

**Comment by io-node** [comment] 2017-05-22 15:23
Been able to have my own background working (which is located in /themes/[theme name]/core/img/background.jpg) by copying the /core/css/guests.scss to /themes/[theme name]/core/css

**Comment by phatair** [comment] 2017-05-22 18:55
Same problem here.
I have a custom theme since the first nextcloud version and until now no problems with that.

i have a folder in /themes and a logo in /themes/mytheme/core/img and some css changes in /themes/mytheme/core/css

In the config file i have my theme activated but no logo and no custom login background is shown.
The favicon will be displayed if i disable the theme app.

I didnt have this behavior in the past.

**Comment by juliushaertl** [comment] 2017-05-23 09:11
Looks like the styles.css inside the theme folder is not applied because of the newly added guest.css.

**Comment by juliushaertl** [comment] 2017-05-23 09:13
We should add a guest.css to the example theme and update the documentation on that. cc @nextcloud/documentation

**Comment by io-node** [comment] 2017-05-23 09:26
But isn't the guest.css only used for guest and login views? it wouldn't seem obvious that to change the logo on the top left corner once you are logged in, you will need to add that to the guest.css file.

**Comment by io-node** [comment] 2017-05-23 09:28
I just tried to add the logo-icon css section to the guest.css file, without success. Looking at the browser details it shows that the .logo-icon css details comes from server.css (which is still the default one)

**Comment by juliushaertl** [comment] 2017-05-23 09:29
Ah those are two issues. So styles.css will not be loaded anymore since Nextcloud 12 has a merged css file called server.css. Can you test if it will be fixed when you rename that file in your theme?

**Comment by blackcrack** [comment] 2017-05-23 09:30
but is should work, because if a factory or a private person want have his own theme, where he have long time developed .. :\ should work again ..
thank you ...
if my theme so far finish, then i want make different others, also with small pictures instead background-colour only.. ;) so, should it already again working :)
best regards
Blacky

**Comment by io-node** [comment] 2017-05-23 09:35
I can confirm that the logo-icon in the server.css file now works.

So I had to do the following to change the logos:
- login logo - copy guest.css to theme and change the "#header .logo" section
- upper-left logo - create server.css and add the "#header .logo-icon" section (or rename styles.css to server.css

The only thing that doesn't get updates at this moment is the fav-icon

**Comment by blackcrack** [comment] 2017-05-23 09:37
i am confirm it soo, this works..

io-node, if you whant test my theme, there 
http://www.blackysgate.de/files/folder-root/nextcloud/

best regards
Blacky

**Comment by juliushaertl** [comment] 2017-05-23 09:44
> The only thing that doesn't get updates at this moment is the fav-icon 

Works fine here with the example theme from #5061. Can you check what files are loaded in the `<head>` section of your Nextcloud?

**Comment by io-node** [comment] 2017-05-23 10:00
In the head section it only shows:

<link rel="icon" href="/core/img/favicon.ico">

not the source file it comes from. I assume this is from the template files layout.guest.php and layout.user.php. The problem is that "print_unescaped(image_path('', 'favicon.ico'));" doesn't translate to the theme folder when setting the theme in config.php.

Only work around I can think of is copying both the layout.guest.php and layout.user.php to the theme folder and set a static path to the favicon.

**Comment by phatair** [comment] 2017-05-23 10:00
Works for me, too. I renamed the styles.css in server.css and now the theme is working.

But there is one thing i dont understand. Is the guest.css necessary? My theme looks good without the guest.css.

**Comment by io-node** [comment] 2017-05-23 10:04
True, you can do it with server.css only. Also just removed the guest.css and have all details in server.css and all looks fine (excl the favicon)

**Comment by blackcrack** [comment] 2017-05-23 10:07
please read ^^ : https://github.com/nextcloud/server/issues/5036#issuecomment-303345395

because overwrite the custom css code ..

best regards
Blacky

**Comment by phatair** [comment] 2017-05-23 10:07
Thanks io-node.

Thats strange because i see my favicon ...

**Comment by io-node** [comment] 2017-05-23 10:12
When I check the code it states `<link rel="icon" href="/core/img/favicon.ico">` which goes to the link `https://cloud.domain.tld/core/img/favicon.ico` and not `https://cloud.domain.tld/themes/<theme>/img/favicon.ico`

**Comment by juliushaertl** [comment] 2017-05-23 10:13
> True, you can do it with server.css only. Also just removed the guest.css and have all details in server.css and all looks fine (excl the favicon)

Good catch. I've adjusted the pull request to that.

@io-node I cannot reproduce that. Maybe the url is cached somewhere.

**Comment by io-node** [comment] 2017-05-23 10:17
It is strange, I done a "Emtpy Cache and Hard Reload" in Chrome, and still goes to the default favicon. Not giving up yet :)

**Comment by blackcrack** [comment] 2017-05-23 10:20
```css
#body-login { background-image:;} /* this is to owerwriting , i have color if you see at bottom, but the picture it is over all, and this is bad !*/

#header .logo {
    background-image: url('../img/logo.png');
   }

#body-login { 
/* Permalink - use to edit and share this gradient: 
http://colorzilla.com/gradient-editor/#001659+0,7a7a7a+72,aaaaaa+100 */
/* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#0079c4+0,353535+39,000000+100 */
background: rgb(0,121,196); /* Old browsers */
background: -moz-linear-gradient(top,  rgba(0,121,196,1) 0%, rgba(53,53,53,1) 39%, rgba(0,0,0,1) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top,  rgba(0,121,196,1) 0%,rgba(53,53,53,1) 39%,rgba(0,0,0,1) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom,  rgba(0,121,196,1) 0%,rgba(53,53,53,1) 39%,rgba(0,0,0,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#0079c4', endColorstr='#000000',GradientType=0 ); /* IE6-9 */

} ```

**Comment by io-node** [comment] 2017-05-23 10:23
That doesn't change the favicon of the browser-tab. I have now been able to fix it. It seems, during testing, I disabled the Theming app. Once I enabled the Theming app it did generate the correct favicon link.

**Comment by phatair** [comment] 2017-05-23 10:27
if i have the theming app enabled i got this:
<link rel="icon" href="/index.php/apps/theming/favicon/files?v=15">

if i disable the theming app i got this:
<link rel="icon" href="/themes/mytheme/core/img/favicon.ico">

**Comment by blackcrack** [comment] 2017-05-23 10:28
oky, i have disable the themeingapp too, and the backgroundpicture it is away,
but this must at first knowing.. :\ !!

so 2 things, disable theme-app (woh it exist a theme app?!)  and rename the style.css to server.css ..
humm this is bad..

**Comment by io-node** [comment] 2017-05-23 10:29
For me to get my theme to work again was:

- Rename styles.css to server.css (to change colours, login logo and menu logo)
- Make sure Theming app is enabled (to get favicon to work)

**Comment by blackcrack** [comment] 2017-05-23 10:32
+1

and this is really bad ! because no one know it, only we are there..

and what it is with the icons.. i have custom upload png and something.. like it looks ..
moment.. 
works this also nomore ..

**Comment by io-node** [comment] 2017-05-23 10:35
It would have been good to have known this in advance of this change, so people could have prepared this better and incorporate it into the upgrade process, so they don't loose their own theming.

**Comment by blackcrack** [comment] 2017-05-23 10:36
++1

**Comment by juliushaertl** [comment] 2017-05-23 10:37
> It would have been good to have known this in advance of this change, so people could have prepared this better and incorporate it into the upgrade process, so they don't loose their own theming.

The theming app has been created for a reason. Custom themes were breaking on update since ages :wink: But yes, this should be states somewhere in the changelog so people are aware of this before upgrading.

**Comment by blackcrack** [comment] 2017-05-23 10:39
Julius, kannst du das vielleicht gleich im theme verzeichniss die README beschreiben und updaten sowie die style.css auch gleich umbenennen ?
ulius, you can perhaps the same in the theme directory describe the README and update as well as the style.css synonymous rename?

best regards
Blacky

**Comment by BenS89** [comment] 2017-05-23 10:46
I also noticed a problem with custom mail notification templates for the activity app. I have a custom theme and a custom mail templates for the activity app under /themes/<custom_theme>/apps/activity/templates/email.notification.php

This templates was correctly used with NC11. After the upgrade to NC12, I get the default mail notifications.

**Comment by blackcrack** [comment] 2017-05-23 12:08
imho should it reedit the line where it is fixed as server.css back to style.css 
and try to make all compatible to the standart theme names and files,
because the icons.css works also no more in 12 ! and this is bad, if all must be renamed 
and change for 12 !

Ben you right, i say +1

also should programmed in, if setting up a theme in config.php, should the theme-app automatical disable !
what maybe a possible be ..

best regards
blacky

**Comment by juliushaertl** [comment] 2017-05-23 13:36
@BenS89 Can you open a separate issue for that?

@blackcrack This is because the number of css files requested with Nc12 has been reduced by using a combined server.css file. I see no change for adding a fallback to old files, but you can basically add a server.css file to your theme that just includes all your old css files.

**Comment by blackcrack** [comment] 2017-05-23 13:50
i have see the scss files and the "@include" the files, i have try it with 
the server.css and there include the style.css .
The problem it is, if you all use in one file, like the icons too (like i whant make) gives a huge file and really
heavy to find the right entry.. so it is (imho) bescheuert /not really okey .. if at all changes
and makes extra .. look you have all included in server.scss but you have extra files for 
icons and the other one, and this should be removed as possible in the theme-folder ?
and the user should all squeeze /mash in one file  ??  wow, this is user/designer support ! :\
hmmm.. imho is this crap.. if i can speak open with you :) would really nice if exist a possible 
for hold all apart like in the core/css folder !

best regards
Blacky

**Comment by io-node** [comment] 2017-05-25 10:33
I have now also noticed that the favicon only works on the login page, not when a user is logged in:

Scenario 1:

- Theming app disabled
- Custom theme set
- User not logged in

Result = favicon comes from themes folder

Scenario 2:

- Theming app disabled
- Custom theme set
- User logged in

Result = favicon comes from default core folder

**Comment by phatair** [comment] 2017-05-26 10:12
Hi,

there is just another problem on my NC12 installation. In my mail template is the default icon used, not my custom icon i use in the custom theme. Where can i change this? Is this the same problem? Is it necessary to rename the css file in the mail template too? Where can i find the mail template?

**Comment by juliushaertl** [comment] 2017-05-26 20:18
@phatair See https://github.com/nextcloud/activity/issues/160

@io-node I cannot reproduce the wrong favicon here. In case it still exists, can you open a separate bug report for that?

**Comment by io-node** [comment] 2017-05-27 18:01
@juliushaertl  it seems I am unable to reproduce the issue with the favicon. I assume it had something to do with caching. At least I have tried it few times and as for now the favicon is working as expected.

**Comment by phatair** [comment] 2017-05-29 14:49
Hi,

thats funny - juliushaertl linked me to [nextcloud/activity#160](https://github.com/nextcloud/activity/issues/160) and nickvergessen linked me back to this issue :-)

The problem is still the same - in my mail notification is used the default "custom cloud" logo and not my own logo. How can i change the logo in the mail notification?

Thanks for your help.

**Comment by juliushaertl** [comment] 2017-06-06 20:33
@phatair This issue is about themes css files. 

I think the mail issue has been fixed with https://github.com/nextcloud/server/pull/5268

**Comment by MorrisJobke** [comment] 2017-06-13 22:48
Fixed in #5061

**Closed** 2017-06-13 22:48 UTC
Labels: 1. to develop, bug, feature: theming, regression

**Comment by minimalic** [comment] 2017-06-20 14:01
So what about 12.0.1? :)

**Comment by gcommit** [comment] 2018-04-17 09:43
I have the same issue on 13.0.1
As a workaround you can install the app "Unsplash" and deactivate it. For some reason this triggers a update of the login screen (do it that way, if you don't want to do changes on system itself)
