### ISSUE TITLE
[Bug]: InvalidArgumentException: Index name "share_id_index" for table "CyP6k_onlyoffice_permissions"

### ISSUE THREAD

**Issue by pilus1234** [nextcloud/server#47689] opened 2024-09-02 19:17 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
InvalidArgumentException: Index name "share_id_index" for table "CyP6k_onlyoffice_permissions" collides with the constraint on table "CyP6k_federated_reshares".
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

InvalidArgumentException: Index name "share_id_index" for table "CyP6k_onlyoffice_permissions" collides with the constraint on table "CyP6k_federated_reshares".

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die [Nextcloud Community](https://github.com/nextcloud/server/issues).
```
### Steps to reproduce

1. Update from 29.0.0 through web updater 20.0.5
2.Installation ok, config maintanance mode is false
3.can not login, error message above

### Expected behavior

awaiting login page

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by pilus1234** [comment] 2024-09-02 20:31
can be reproduced. I played back a backup from 31.08.2004 - Nextcloud 28.0.8 is working fine.
Update to NextCloud 28.0.9 - Nextcloud is working fine
Update to Nextcloud 29.0.5 - same message.

I repruced the problem with webupdater as well as with manual installation.

**Comment by joshtrichards** [comment] 2024-09-03 13:11
Duplicate of #45271

**Closed by joshtrichards** 2024-09-03 13:11 UTC
Labels: bug, 0. Needs triage, 29-feedback
