### ISSUE TITLE
Login page blank

### ISSUE THREAD

**Issue by alecsdc** [nextcloud/server#14382] opened 2019-02-26 07:43 UTC
Hi all, use nextcloud on an Oracle Virtual box virtual machine. Nextcloud has always worked properly, until the machine has unexpectedly restarted causing a blank page on login.
The data I checked there are, launching systemctl I noticed that postgresql service is ok but postgresql@10-main.service is “loaded” but not “active and running”. How can I solve the problem?
Thanks
Support intro

Nextcloud version 13.0.4:
Operating system and version Ubuntu 18.04
Apache or nginx version eg, Apache 2.4.29
PHP version eg, 7.1

The issue you are facing:

Is this the first time you’ve seen this error? (Y/N): Y

### Steps to reproduce
1. start oracle VM virtual box
2. launch nextcloud/login
3. BLANK page

### Expected behaviour
Login page

### Actual behaviour
Blank page

### Server configuration

**Operating system**: Ubuntu 18.0.4

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** oracle virtual box with preconfigurated machine

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment] 2020-08-20 15:18
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-20 15:18 UTC
Labels: 0. Needs triage, bug
