### ISSUE TITLE
When opening the trashbin it doesn't show the most recently deleted files first.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#16412] opened 2019-07-15 22:32 UTC
### Steps to reproduce
1. create some files/folders
2. delete one file
3. delete another file
4. open the trashbin/deleted files app

### Expected behaviour
it should show the most recently deleted files first

### Actual behaviour
It shows the least recently deleted files first
Just when clicking twice on the "deleted"-section it show the most recently deleted files first.

I am running Nextcloud 16.0.3 on Ubuntu 18.04.2 LTS and using a Chromium-75-based browser.

**Comment by szaimen** [comment] 2019-08-27 17:00
@kesselb Please could you have a look at this?

**Comment by szaimen** [comment] 2019-10-05 16:37
Any update here?
I am now on 16.0.5. and it isn't fixed yet.
I don't know, if that is a configuration error or is it also happening to other people?
Shall I fill out the bug-template?
Maybe it is a browser-issue?
![image](https://user-images.githubusercontent.com/42591237/66257911-23ec0f00-e79f-11e9-9c42-eab34e38bb4d.png)

**Comment by szaimen** [comment] 2019-12-31 17:05
Maybe this helps jn understanding the bug: (still existing on 17.0.2)
When opening the trashbin first:
![20191231_180333](https://user-images.githubusercontent.com/42591237/71628414-1c9a9d00-2bf8-11ea-9923-b2609012ccb6.png)
![20191231_180240](https://user-images.githubusercontent.com/42591237/71628415-215f5100-2bf8-11ea-92e9-b11cdec7b32a.png)
![20191231_180052](https://user-images.githubusercontent.com/42591237/71628424-2c19e600-2bf8-11ea-98ab-4cb7bef6dec7.png)

**Comment by szaimen** [comment] 2019-12-31 17:16
@jancborchardt do you maybe have some thoughts to share on this?
Maybe it is meant to be this way?

**Comment by jancborchardt** [comment] 2020-01-01 03:06
Yep, this absolutely is an issue, the default sorting for deleted files should be by most recently deleted first.

If someone points out where to change this in the code, it would make for a nice good first issue. :)

cc @rullzer

**Comment by JuanFarias1** [comment] 2020-01-17 07:14
I’ll take a stab at this, if the issue is isn’t soon to be closed?

**Comment by szaimen** [comment] 2020-01-17 11:20
> I’ll take a stab at this, if the issue is isn’t soon to be closed?

Of course, just do it! 
I don't think, that this will be addressed by the Nextcloud team any time soon.

**Comment by sndrr** [comment] 2020-02-17 12:15
> If someone points out where to change this in the code, it would make for a nice good first issue. :)

And I'd be happy to help. I did some preliminary searching in the code, and the default ```files_trashbin``` view does not have a setting to enforce order. Only when you click on the "Deleted" column **twice**, it updates the file order based on ```mtime``` by doing a POST.

**Comment by szaimen** [comment] 2020-03-21 01:58
@sndrr how would I implement this setting to enforce ordering based on the mtime descending by default?
BTW: I don't understand, why the files don't get listed based on their mtime, descending, since this should have been always the default setting. What am I missing here?

**Comment by nina-py** [comment] 2020-12-20 04:09
This issue has been partially fixed on the `master` branch (not the `stable20` branch though) by https://github.com/nextcloud/server/pull/23286, however it only fixed the need to click on the column header twice to sort it in descending order - just once is enough now. The deleted file list is still stubbornly sorted the wrong way by default though.

**Closed** 2021-11-10 12:55 UTC
Labels: bug, good first issue, 2. developing, feature: trashbin, papercut
