### ISSUE TITLE
File list is truncated in (Samsung) SmartTV browser

### ISSUE THREAD

**Issue by McPringle** [nextcloud/server#11330] opened 2018-09-23 12:28 UTC
### Steps to reproduce
1. Share a folder as a link
2. Open the link with the Samsung Smart TV browser
3. Look at the filenames

### Expected behaviour
See more of the filename

### Actual behaviour
Only the three first characters of the filenames are displayed followed by a huge white space. Please take a look at the attached photo:
![nextcloud_on_samsung_smarttv](https://user-images.githubusercontent.com/1254039/45927998-ce024b80-bf3c-11e8-81a1-84ae41a857ce.jpg)

### Server configuration

**Operating system**:
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64)

**Web server:**
nginx/1.15.3

**Database:**
mysql  Ver 15.1 Distrib 10.3.9-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
Zend Engine v3.2.0 with Zend OPcache v7.2.10-0ubuntu0.18.04.1

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Download from Nextcloud Website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Activity
AppOrder	
Bookmarks
Brute-force settings
Calendar
Checksum
Collabora Online
Collaborative tags
Comments
Contacts
Deck
Deleted files
Federation
File sharing
First run wizard
Full text search
Full text search - Bookmarks
Full text search - Files
Gallery
Log Reader
Mail
Markdown Editor
Monitoring
News
Nextcloud announcements
Notifications
ocDownloader
Password policy
PDF viewer
Polls	
Reader (ebook reader)
Share by mail
Social sharing via email
Social sharing via Facebook
Social sharing via Google+
Social sharing via Twitter
Talk
Tasks
Text editor
Theming
Update notification
Usage survey
Versions
Video player
Weather
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => 'XXXXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXX,
  'secret' => 'XXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'XXXXXXXXXX',
    1 => 'XXXXXXXXXX',
    2 => 'XXXXXXXXXX',
    3 => 'XXXXXXXXXX',
  ),
  'datadirectory' => '/var/nextcloud_data',
  'overwrite.cli.url' => 'XXXXXXXXXX',
  'overwriteprotocol' => 'https',
  'dbtype' => 'mysql',
  'version' => '13.0.6.1',
  'dbname' => 'XXXXXXXXXX',
  'dbhost' => 'XXXXXXXXXX',
  'dbport' => 'XXXXXXXXXX',
  'dbtableprefix' => 'XXXXXXXXXX',
  'mysql.utf8mb4' => true,
  'dbuser' => 'XXXXXXXXXX',
  'dbpassword' => 'XXXXXXXXXX',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'logtimezone' => 'Europe/Berlin',
  'maintenance' => false,
  'auth.bruteforce.protection.enabled' => true,
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis-server.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'XXXXXXXXXX',
  'mail_domain' => 'XXXXXXXXXX',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'XXXXXXXXXX',
  'mail_smtpport' => 'XXXXXXXXXX',
  'mail_smtpname' => 'XXXXXXXXXX',
  'mail_smtppassword' => 'XXXXXXXXXX',
);
```
</details>

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.1 TV Safari/538.1

**Operating system:**
Linux; Tizen 2.4.0

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors in logfile
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
The log is 66M. Please be more specific, if you need data from the log.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
no access to browser log
```
</details>

**Comment by MorrisJobke** [comment] 2018-09-26 08:07
> Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.1 TV Safari/538.1

We fixed some stuff like this for Safari in Nextcloud 14. I guess this is the best approach to move this forward, because I think that debugging on a SmartTV is out of scope and not really something we will invest much time in it :/

cc @skjnldsv didn't you fixed this truncating issues some months ago?

**Comment by skjnldsv** [comment] 2018-09-26 08:16
@MorrisJobke I remember stuff like that, but nothing that terrible :/

**Comment by MorrisJobke** [comment] 2018-10-02 20:14
> I am the organizer of the monthly Hackergarten in Lucerne where we work for open source projects. If you tag this issue with the "hackergarten" tag, it will automatically show up in our list of potential topics for the next event on http://hackergarten.net

I would rather close this one here for now. Feel free to track it on your side, but we are clearly lacking a way to properly reproduce and debug this and also TVs are not the main interface we are building our web UI for. Sorry for the inconvenience here.

**Closed by MorrisJobke** 2018-10-02 20:14 UTC
Labels: bug, needs info

**Comment by MorrisJobke** [comment] 2018-10-02 20:17
maybe https://github.com/nextcloud/server/pull/11508 fixes the problem for your
