### ISSUE TITLE
Integration with Mattermost

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3202] opened 2017-01-23 07:36 UTC
Reopening here since we who switched to Nextcloud are still very interested in Mattermost integration. :)

Original issue opened by @menelic:

> I requested owncloud integration over at mattermost (free and open self hosted slack alternative - with more features than slack itself) - this became one of their most popular feature requests. https://mattermost.uservoice.com/forums/306457-general/suggestions/9950943-integration-with-owncloud#comments .Now they have responded - they want to do it and are asking for support from the oc community:
> 
>   
> 
> >   Thanks to everyone who upvoted this, can we have the community’s help breaking this feature into smaller parts that can be written into tickets?
> > 
> >     It seems there’s:
> > 
> >         Ability to “Choose a file” from OwnCloud instead of hard drive.
> >         Add a preview of files referenced in conversations with hyperlinks to files hosted on OwnCloud
> >         Something about webhooks, we’re not sure we understand
> > 
> >     Can we have help from the OwnCloud community understanding what’s the first step?
> 
> @jancborchardt @coreyhulen @it33 maybe you could get together on this?

cc @LukasReschke @karlitschek @JakobReiter since you were active on the original issue.

-------------------

:money_with_wings: Donate to help make this happen! :smiley:
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41230034)](https://www.bountysource.com/issues/41230034-integration-with-mattermost?utm_source=41230034&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jancborchardt** [comment] 2017-01-23 07:38
The first task would be [Link Previews similar to Dropbox link preview](https://mattermost.atlassian.net/browse/PLT-2233). For anyone who wants to make a start. :) cc @nextcloud/javascript

**Comment by jancborchardt** [comment] 2017-01-23 07:50
cc @furai @schiessle from the other Mattermost issue :)

**Comment by harcesz** [comment] 2017-05-11 11:29
if this is done I'd be able to move my NGO from Slack, is there a way I could help kickstart it? (other than coding)

**Comment by Laykou** [comment] 2017-07-31 08:57
👍

**Comment by JakobReiter** [comment] 2017-07-31 10:54
+1

**Comment by jancborchardt** [comment] 2017-08-02 13:38
You can support this either by
- :computer: coding (you’re welcome in the IRC channel #nextcloud-dev)
- :money_with_wings: donating towards the bounty:
https://www.bountysource.com/issues/41230034-integration-with-mattermost

Please consider donating to support! :) @harcesz @Laykou @JakobReiter everyone :heart:

**Comment by siteleas** [comment] 2017-08-18 00:33
Any word on this?

**Comment by hubearth** [comment] 2017-10-14 16:59
This integration is a must, but I think it covers two project. 
1) to use nextcloud as a backend for mattermost file storage
2) to enable mattermost user to easyly get a link a file/folder that is stored on nextcloud.

In my own opinion, the second one is more useful, since most of the file that we share on mattermost are already on nextcloud. The logic would be
  1. add a field to users so that mattermost user would have nextcloud (or owncloud) credentials
  2. allow connection/browsing through webdav
  3. add a button in messages so that you can open a webdav connection instead of a simple file browser.
  4. generate the link depending on the nextcloud credentials.

**Comment by jancborchardt** [comment] 2017-10-14 18:50
@hubearth since no one picked this up yet and you are a developer interested in the project, would you be interested getting this started? :) We are happy to help you in case of any questions, either here on in our IRC channel #nextcloud-dev. :tada:

**Comment by ShamimIslam** [comment] 2017-10-17 13:13
I believe both projects are useful. If nextcloud is the backend for mattermost, it allows for synchronization to all parties based on a folder where the mattermost content would be stored. You could conceivably share your mattermost folder for your project to your team and they would all automatically receive updates if they were synchronizing.  We are hobbling ourselves with just thinking of mattermost as being the vehicle for sending the files. For users that use mattermost, we would send a link that is internal to the backend. For users that are external, we would send a shortcut link like we do when sending email. When uploading the files, mattermost would auto-sync between users as needed based on folders used. While I do agree that item 2 is easier to do, adapting for item 1 is harder i item 1 is not defined - where would the files be stored in the nextcloud account? Who would own them? Where would we go? I think we could do it in either order. I'm just concerned it might be lead to more issues to do the backend storage second. Open to other thoughts.

Along these lines - are there any class diagrams yet for nextCloud? I can't get into helping without understanding what we have and there are so many different entry points, that without reading all the code (long process) it's hard to navigate.

Thanks.

**Comment by natrius** [comment] 2018-02-22 12:26
Any updates on this? 
This sounds really interesting as i have to suggest something for my company. I am looking at Mattermost and matrix / riot.im with a nextcloud and a integration so nextcloud is easy to reach - it would be great.

**Comment by lapineige** [comment] 2018-02-26 12:01
Indeed adding Nextcloud as the backend storage would be great and ease a lot users' experience while sharing files (while not adding an extra layer of complexity ("Is that file on mattermost or nextcloud ?") and maybe storage doubles).
It would be much appreciated ! 🙂

> While I do agree that item 2 is easier to do, adapting for item 1 is harder i item 1 is not defined

Can you recap which one correspond to which idea ? (I'm not sure to understand)

> where would the files be stored in the nextcloud account? Who would own them? Where would we go? I think we could do it in either order. I'm just concerned it might be lead to more issues to do the backend storage second. Open to other thoughts.

I have a solution in mind, to me _(note: I don't know anything about Nextcloud code & so on_) it seems to be the simplest to put in place :
- A new account is created (automatically or not), let's call it `Mattermost File Sync` during this example.
It's purpose is to be Mattermost's "backend storage", so it could be reduced as its minimum purpose (storing file, no other apps, no other rights)
- On Matterside, when a file is uploaded, it connects to Nextcloud using `Mattermost File Sync` account (via WebDAV ?). Then it uploads the file here.
- _[Extra feature, not sure if it's doable] : any link to a Nextcloud file that is in `Mattermost File Sync` directory (and thus owned by user `Mattermost File Sync`) can have a preview (imported from Nextcloud's preview ?) and a direct link the file in Nextcloud_
- Mattermost's files repositories are shared with Nextcloud users (with the internal nextcloud function).
I suppose it would be easier to let Nextcloud's admin(s) set up the group(s) that have the right to access to a `[Channel storage repository]`, and then configuring the integration tool to share the directory with those groups.
For instance, you have a Mattermost channel called `Project 1`. You create a Nextcloud group called `Project 1 team`. Then any file uploaded in Mattermost channel `Project 1` is stored in `Mattermost File Sync` account, in the folder `Project 1`. And this folder is shared with any user in `Project 1 team` group.

This make the storage part + sharing kind of simple and mainly automatised (except user's integration in groups, but well, there is no cross account creation in Mattermost and Nextcloud so it's a manual step anyway).

What do you think ?

**Comment by lapineige** [comment] 2018-02-26 12:05
Note: as far as I understand (by reading [this](https://docs.mattermost.com/install/config-mattermost-server.html), point 6) this is partly doable right now by configuring file storage to [Some location] and mounting [Some location] as an external storage in Nextcloud.

**Comment by marinpurgar** [comment] 2018-03-21 17:45
Going to take a look at this since my customers requested it and it is tagged as "good first issue", stay tuned ...

**Comment by MozzieAU** [comment] 2018-08-27 00:07
Hi Folks, 

Im still keen to see Nextcloud integration with Mattermost. As an extra thought, I wonder also if it would be possible to integrate Collabora into Mattermost and Nextcloud. This would permit seamless editing of documents being worked upon by teams.

Happy to pitch in a bounty but I ned to know what kind of sum would be required to actually eliver the complete solution. 

Ray

**Comment by hanzei** [comment] 2018-12-16 20:39
Hey guys,

I might work on this feature as I'm interested in both Nextcloud and Mattermost.
But for me the use cases aren't quite clear. Could some please create a list of use cases/user stories for this? Please don't consider the technical difficulties while creating these.

**Comment by MozzieAU** [comment] 2018-12-21 00:57
Hello Hanzei

In our organisation, we are looking for two key functionalities from Nextcloud integration.

1/ The ability to provide a searchable online library of documents for access by employees.
The Nextcloud backend to be used as the doc store, and the ability to share documents to anyone using Nextcloud’s sharing facility.

2/ NExtcloud/Collabora inline editing of documents being worked on by channel members.
For example, a channel member uploads a worksheet or document for the team to work on.
Once uploaded the members can access said document and edit it inline within a popup window or tab from the channel post.

Hope this helps.
Happy to discuss a bounty.

Regards
Ray

**Comment by lapineige** [comment] 2018-12-21 08:57
For my part I'd like to be able to share the storage between Mattermost and Nextcloud (for instance, a specific folder in Nextcloud that store the files that people put in Mattermost) to avoid doubles and the need to search for a file in Nextcloud and Mattermost (for instance to get the latest version).

Having the ability in Mattermost to link to a Nextcloud file, or to search for it, would be a great addition.

**Comment by lapineige** [comment] 2018-12-21 10:31
> if the file is already stored in a nextcloud synced directory (with nextcloud client), mattermost should be able to get the shared link created by nextcloud.
thanks !

I've a proposal : if you mention "@YourNextcloudSiteName", then you can get the list of directories and find a file to "mention" (=link).

**Comment by vpecinka** [comment] 2019-01-03 15:42
> Hey guys,
> 
> I might work on this feature as I'm interested in both Nextcloud and Mattermost.
> But for me the use cases aren't quite clear. Could some please create a list of use cases/user stories for this? Please don't consider the technical difficulties while creating these.

Hi @hanzei 

I appreciate your interest!

 It would be great if users of the Mattermost can select a file from their nextcloud account (e.g. linked through personal token) and post it to the channel. Technically it can be achieved by creating public link for the file and posting it to the channel. This is probably more Mattermost related (plugin?)

On the other side, in the Nextcloud gui it would be great to select a file / view its properties and create post message in the Mattermost channel (technically: create public link and call mattermost webhook to post the link in the selected channel).

VP

**Comment by biva** [comment] 2019-02-13 16:27
Hello, I use Slack, and the main feature I use is the chat organized in chatrooms. Not very different from what "Nextcloud Talk" is providing at the end. 

Instead of integrating Mattermost to Nextcloud, wouldn't it be easier to make Talk evolve to integrate the capabilities of Mattermost?

**Comment by vpecinka** [comment] 2019-02-15 12:00
I think it is better to remove Talk and integrate open sourced Mattermost. It is not easy to keep up with folks focusing on one product...

**Comment by Serkan-devel** [comment] 2019-02-16 10:02
Why not integrate [Zulip](https://zulip.org) instead?

**Comment by hanzei** [comment] 2019-02-16 13:51
This issue is about an Integration with Mattermost. For integrations with other software, please open a new ticket.

**Comment by PackElend** [comment] 2019-03-07 19:38
There are so many good comments but is actual some coding on it?
What about dropping talk and integrate mattermost fully, so moving capacity from talk to mattermost.
As both parties have a commercial branch some official agreement would be necessary avoid major changes dump the other party

**Comment by miguelsan** [comment] 2019-04-18 15:17
@hanzei I don't agree with you. As an example, @harcesz and @biva need to replace Slack, and integrating Mattermost is just one possible way for them to achieve it. Mattermost is indeed the first solution that most of us think about for this case, since it is well known as *the* FOSS version of Slack, which in itself comprises and describes the main usecase here. My usecase, for instance, would be to enjoy a *slackish* app in a new Nextcloud instance for a startup.

This again aligns with the following thoughts:

1. Such an app is most needed in Nextcloud, I hope that we all agree on that.
2. This issue #3202 should be about the feature set of that app, be it integration with Mattermost itself, extending the capabilities of Nextcloud Talk, or *whatever*.

I vote for either changing the title of this issue or opening another one as "Define feature set of a full fledged discussion app", which would as a result supersede this one.

Once in there, we *should* also talk about alternatives like integrating Zulip, whose features are more appealing as Mattermost's (take a look at it, guys!), or even about [Discourse](https://www.discourse.org/).

**Comment by ShamimIslam** [comment] 2019-04-18 16:05
So here's the problem. Defining a featureset is great. But the brass tacks
end up costing more. It's a lot easier to see where you are going when the
destination is clearly defined. We can always expand to additional
platforms. But until you have the first one, you're still shooting in the
dark.

**Comment by miguelsan** [comment] 2019-05-02 16:07
Ok, here is my point: I can see that it would be more effective to just define an MVP than agreeing on each and every detail of the app, but:
I am afraid that this MVP will be a half-backed integration of [fill the blank with Your random solution] and afterwards having to point out to people asking for deal-breaker improvements that those aren't technically possible without a complete new and expensive app, which won't be done because the existing one is "enough for me". That's something I'd like to avoid.

A bit of exploration and some kind of poll about the main direction of the app that you mention should be somehow doable and gather enough impulse to push this issue forward, which it obviously needs.

**Comment by miguelsan** [comment] 2019-05-02 16:22
My suggestion from this point on would be to either integrate _Zulip_ or extend _Nextcloud Talk_ with some kind of first-class channels, markdown, history search and notifications for an "easy" first go.

I just don't currently know the internals of each one and the actual feasibility of each proposal, so that must be it from me for now.

**Comment by PackElend** [comment] 2019-05-06 20:02
Hello,
may I comment this too? 
As there are so many open source chat apps out there with different commercial models or completely free, I would suggest that Nextcloud concentrates to create bridges to the other apps such as Mattermost or Zulip and continue the story what was begun with the rocket.chat intergration.
The folks behind those projects are doing only this and Nextcloud has too many other things on the to-do list.

**Comment by miguelsan** [comment] 2019-05-08 09:49
@PackElend Nice, I hadn't seen that Rocket.Chat is working with Nextcloud. That might be a game changer and put this issue under a very different perspective.

But only if the collaboration goes further. Because [until now this](https://nextcloud.com/blog/rocket.chat-and-nextcloud-announce-partnership-and-integration/) is all there is:

> The integration is now ready and is public from today. [It] allows users to post files from Nextcloud directly into a chat channel, enabling seamless integration between chat and file handling. [...] More integrations, that go even further than this latest iteration, are in development.

Let's wait and see, right?

**Comment by tech348712013870132** [comment] 2019-11-20 18:10
Is there any easy to deploy integration available yet to connect nextcloud folder updates with a mattermost channel via a plugin/webhooks?

**Comment by biva** [comment] 2020-01-23 17:11
Hello, I propose a very specific integration Nextcloud Deck / Mattermost in https://github.com/nextcloud/deck/issues/1474. Do you think it could be a good idea @jancborchardt ? Would anybody be ready to help? Indeed, I don’t have a lot of skills in this matter :frowning:
Thanks!

**Comment by PackElend** [comment] 2020-01-23 17:24
I reckon they wil apply for GSoC 2020, as in 2019:
https://developers.mattermost.com/contribute/google-summer-of-code/ .
You can propose as project and volunteer as mentor.
Orgs are announced by Google mid Feb, wait for the right announcement a go
ahaed

**Comment by orbnetde** [comment] 2020-07-20 12:27
We added some bounty to this. Let's hope this will speed up the integration.

**Comment by theshades** [comment] 2020-08-02 03:22
Lemme know if I can provide some help... I have a few use cases for this :)

**Comment by Salatfreak** [comment] 2020-08-16 10:06
I've started developing a Nextcloud app to integrate Mattermost into the Nextcloud interface and I'm looking for developers to join me. The integration is supposed to synchronize users and groups from Nextcloud to Mattermost and automatically login users to Mattermost when the app is opened.
![Integration preview](https://salatfreak.github.io/images/integration.png)
I've shared some further details in the [Nextcloud forum](https://help.nextcloud.com/t/integrate-mattermost-as-a-nextcloud-app/89796).
Here is my first version of a [Mattermost plugin](https://github.com/Salatfreak/mattermost-plugin-nextcloud) that allows for the automatic login and a [bash script](https://gist.github.com/Salatfreak/977fa60b0bd052e809ca7b20880c6dd8) that demonstrates how Nextcloud would use it.

**Comment by jancborchardt** [comment] 2020-10-13 09:37
@Salatfreak very cool! Do you want to publish that app on https://apps.nextcloud.com ? :)

Also, not sure if everyone saw the new Matterbridge integration? https://nextcloud.com/blog/bridging-chat-services-in-talk/

cc @gary-kim @eneiluj

**Comment by miguelsan** [comment] 2020-10-13 11:16
Hey, thanks for the tip, @jancborchardt, Matterbridge is hot!

I can foresee this issue being closed soon. And afterwards Talk feature set getting extended for more awesomeness...

**Comment by Salatfreak** [comment] 2020-10-21 15:50
> @Salatfreak very cool! Do you want to publish that app on https://apps.nextcloud.com ?

I would be open to do so but currently the integration can only work when tampering with Mattermosts response headers and ideally blocking some API requests too in a reverse proxy. This would be confusing for people installing the App and expecting it to work out of the box.

**Comment by kinkycat91** [comment] 2021-07-01 09:53
Duplicate of #

**Comment by biva** [comment] 2021-07-01 10:05
Of what @kinkycat91 ?

@Salatfreak your idea is cool: did you make any progress?

We use Mattermost a lot and the integration with Nextcloud would definitely make sense. I think Nextcloud cannot do everything and Mattermost is already a very good open-source solution, which already integrates a Kanban board (Focalboard https://github.com/mattermost/focalboard and https://mattermost.com/blog/project-management-with-mattermost-and-focalboard/). 

I don't understand every consequence of such a strategic decision, but does it really make sense to develop Talk and/or Deck while Mattermost is already very advanced?

In the same logic as partnering/integrating Office solutions (notably OnlyOffice), I really think that users would benefit from a better integration of Mattermost and Nextcloud.

**Comment by kp3nguinz** [comment] 2021-07-06 18:46
Yes... but they make money from Talk, so that is why they are less likely
imho.

**Comment by p-jo** [comment] 2021-09-02 19:00
Hi @Salatfreak this sounds great, would a donation help or do we need to find a new developer to make your plug-ins production ready?

**Comment by kp3nguinz** [comment] 2021-09-02 22:32
My company would also be willing to throw a donation to help get this done.
---
Thanks,

Justin Bowen, GCIH, GPEN, GCWN, GCFA
Sr. Security Engineer
Enterprise Security

**Comment by leoniscsem** [comment] 2021-09-19 07:30
I could also donate to this effort, as operating Mattermost is critical for our business. I can imagine, if we bring this topic up over at the Mattermost forum, there might be more people willing to contribute.

**Comment by Salatfreak** [comment] 2021-11-02 09:13
Unfortunately I won't be able to work on this in the near future. I might start working on it again in a couple of months, as my organization could still use it though.

**Comment by kp3nguinz** [comment] 2021-11-09 18:47
If it is not done by February, I have added it to my team's February sprint
to make this!

---
Thanks,

Justin Bowen, GCIH, GPEN, GCWN, GCFA
Owner
Penguinz Media Group LLC

**Comment by biva** [comment] 2022-01-19 22:37
@kp3nguinz May I suggest to check YunoHost as well, who is looking for a solution as well to integrate LDAP and Mattermost? https://github.com/YunoHost-Apps/mattermost_ynh/issues/58

**Comment by PenguinzPlays** [comment] 2022-07-05 15:50
Nothing yet, it is on my company's roadmap to make it happen in Q4 this
year in the worst case, part of our bot project. Matterbridge has already
released support for Nextcloud Talk, so the capability is mostly there
already.
---
Thanks,

Justin Bowen, GCIH, GPEN, GCWN, GCFA
Sr. Security Engineer
Network Security & Automation
Enterprise Security

**Comment by CarlSchwan** [comment] 2022-09-01 12:38
Closing since this is not related to the core product and can be developed as a separate app similarly to https://apps.nextcloud.com/apps/riotchat

**Closed by CarlSchwan** 2022-09-01 12:38 UTC
Labels: enhancement, 1. to develop, integration

**Comment by biva** [comment] 2022-11-10 09:00
For the record, see https://github.com/julien-nc/integration_mattermost
