### ISSUE TITLE
Consideration: Move from php dependency and utilize TS/JS, Electron, other web framework

### ISSUE THREAD

**Issue by WSLUser** [nextcloud/server#21070] opened 2020-05-22 13:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

There is no good way to automate updates for NextCloud, even in a container environment. It will cause breakages. A manually process is requires, especially due to php dependencies.

**Describe the solution you'd like**

Get rid of the php dependency and use something more friendly such as TypeScript/JavaScript, Electron, or some other web framework.

**Describe alternatives you've considered**

The alternative is to not update until a CVE comes out that requires a manual migration. This is always so much fun.

**Additional context**

Module incompatibilities tend to happen with upgrades so this feature request will only mitigate, not remove the problem. But it's the first step to resolving it. I realize this is likely not a trivial effort but please consider this for the good of the community.

**Comment by dirigit** [comment] 2020-05-23 06:49
If you really want some kind of long term consistency you don't want to use any additional framework. With high probability you will run into same trouble using any framework like with PHP and it's massive incompatilities from (sub-)version to (sub-)version. I.e. this is a special feature of PHP since day 1. I have to fight with it since 1990s due to PHP's popularity and know very well what I writing about.

A very stable base for long term compatibility especially when it's web related is only one language: Perl.

Have a look at how much you really have to change when using a Perl script written in year 2000. Using PHP or any (JS or other) framework you had to rewrite it multiple times.

Ah - problem with Windows ... Which reliable admin runs a webserver on Windows?
Cygwin might be of help for those people. It's compatibility to *x systems is very high.

cu, diri

**Comment by kesselb** [comment] 2020-05-23 17:41
Duplicate of https://github.com/nextcloud/server/issues/16726 with different stack?

> There is no good way to automate updates for NextCloud, even in a container environment. It will cause breakages. A manually process is requires, especially due to php dependencies.

Mind to elaborate? I don't see why a switch to a node based service would solve that issue. We just have other dependencies then (node / ts / whatever). 

> Electron

Isn't Electron that framework to build desktop applications with web technologies? Is this feature request actually for https://github.com/nextcloud/desktop? Why would anyone rewrite a server component with a desktop application framework?

**Comment by WSLUser** [comment] 2020-05-23 18:25
So as I said it can be other web framework.  Everything is behind a firewall with mirrors, including a docker hub mirror. Currently we require a manual update process. Whenever a cve comes out for php (the most common) or other component such as the db (which we use also as container) we need to update the entire stack to ensure breakage doesn't occur. We have some modules installed that don't always play nice during this process, so we have to very carefully choose which versions to go to during the update process that ensure all modules work as intended. I really don't care the backend to server but since this is accessed via browser, we need to retain a web framework. Php has far more CVEs appear than nodejs but again, it could use perl or some really elaborate html with css. I just want a consistent framework that is easy to upgrade to that is easier to automate. If it can also have less security findings appear as well (which I think anything not php would be the case) that would be ideal. In fact if talking security, Django would be the best bet for a web framework.

**Comment by WSLUser** [comment] 2020-05-23 18:36
I wouldn't consider this ticket a duplicate of the other simply due to pushing for Golang only. I personally don't care but if you want to ensure a familiarity for contributions, python using Django would be the best way forward. Its well known and used across any number of projects, both FOSS and commercial. My own shop writes everything in python for most part and bash when we need something specific to a distro.

**Comment by kesselb** [comment] 2020-05-23 18:46
I don't think that will happen anytime soon but one enhancement request more or less doesn't matter anyway ;)

**Comment by MorrisJobke** [comment] 2020-05-29 19:28
Changing the stack will not happen, because it means we start a new project. Also just dropping random tech terms doesn't make this look well thought. Running a server within electron makes exactly 0 sense. Electron is meant for desktop apps as pointed out above. So that would at most affect the desktop client, but not the server at all.

Let's close this then.

**Closed by MorrisJobke** 2020-05-29 19:28 UTC
Labels: 0. Needs triage, enhancement

**Comment by blizzz** [comment] 2020-05-29 20:08
> Isn't Electron that framework to build desktop applications with web technologies?

It's not a framework, it's a browser in sheepskin.

**Comment by WSLUser** [comment] 2020-05-29 21:29
I never said adopt Electron. Did you even bother reading other comments? Because it seems like you didn't. "Throwing tech terms around", I'm just specifying some web frameworks. I don't pretend to know everything there is in the web dev field

**Comment by WSLUser** [comment] 2020-05-29 21:30
closing this just means you don't care about some of your users and even though its used in production by government agencies and large businesses , you don't care. Thanks for such an exclusion

**Comment by blizzz** [comment] 2020-05-29 21:57
You mentioned Electron in the title. But it does not matter. We read your input, and we replied. Sorry that it does not satisfy you.

**Comment by stefan-niedermann** [comment] 2020-05-30 05:29
Every language and framework has advantages and disadvantages. Moving to another stack would mean unknown terrain for developers (who will have to learn another language), no new features for a very long time and loosing other users for other reasons.

One advantage of PHP is that for many small community members cheap (or even completely free) hosters are available. This is an extremely low entry barrier for new community members. And while this tech stack might be "unusual" for large companies, the fact that it runs on each and every hoster out there made me and many other people start contributing to the ecosystem in the first place.

IMHO nextcloud *is* listening well, and it compares the arguments and tries to make decisions which are the best for the majority of the users. It's a pitty that you aren't satisfied with the decision, but many other people out there will be glad to hear that they can keep running their instances without any additional effort and costs and keep contribute.
