### ISSUE TITLE
Previews for password protected Shares cannot be accessed even if the right password is sent via basicauth

### ISSUE THREAD

**Issue by waffshappen** [nextcloud/server#15031] opened 2019-04-10 08:47 UTC
### Steps to reproduce
1. Create an image behind a password protected share from any user account
2. Try to access its preview using just httpie by making a request  "${HOST}index.php/apps/files_sharing/publicpreview/SHARE_TOKEN" \ and sending -a "SHARE_TOKEN":"password" as the correct credentials for the share itself (downloading the file itself using webdav works this way)

### Expected behaviour
The preview should be generated and sent, since the correct share credentials are present

### Actual behaviour
The Server only attempts to verify a temporary token issued when the webgui is in use.
The behaviour occurs in /lib/public/AppFramework/PublicShareController.php:119
where final public function isAuthenticated(): bool { only compares against a temporary session token. By replacing it with return true the preview loads perfectly fine so its definitely just that function that needs a patch. I dont know if this is in the scope of the shares app, but since i have given correct credentials and can access the very same file using webdav i should be able to generate a preview for it as well. Thus the isAuthenticated function likely needs to be extended to also check if the request is authenticated via the share password itself.

### Server configuration

**Operating system**:
Fedora 29 Server
**Web server:**
Httpd
**Database:**
mariadb/postgres
**PHP version:**
7.3.4
**Nextcloud version:** (see Nextcloud admin page)
15.0.7
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "http:\/\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

</details>

### Client configuration
**Browser:**
httpie
**Operating system:**
Fedora 29 Workstation

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
N/A
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N/A


```
</details>

**Comment by waffshappen** [comment] 2019-04-10 09:28
I have outline the Issue and a very rough, not-mergeable awful "Solution" in
 https://github.com/waffshappen/server/commit/b017e1ac2e5f08405867ae275a46473977d19df1

**Comment by skjnldsv** [comment] 2020-11-07 23:33
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-11-07 23:33 UTC
Labels: 0. Needs triage, bug
