### ISSUE TITLE
upload file is broken

### ISSUE THREAD

**Issue by ccjeaty** [nextcloud/server#12134] opened 2018-10-30 08:20 UTC
### Steps to reproduce
1. upload a **large file(size > 1G)** from web client(Chrome/edge), or  from webdav(windows, copy file to mapping network disk.) 
2. run `sha256sum XXX` shell script from server in data dir on the upload file, and get checksum from localfile.

### Expected behaviour
the server file checksum equivalent local file checksum.

### Actual behaviour
checksum not equivalent.

### Server configuration
```php
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => '*,
  'passwordsalt' => '*',
  'secret' => '*',
  'trusted_domains' =>   array (
    0 => '*',
    1 => '*',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://*:9000',
  'dbtype' => 'mysql',
  'version' => '13.0.7.2',
  'dbname' => 'nextcloud',
  'dbhost' => '172.17.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '*',
  'installed' => true,
  'loglevel' => 2,
  'maintenance' => false,
);
```

**Operating system**:
server run on centos7, client is win10

**Web server:**
apache

**Database:**
mysql

**PHP version:**
```
PHP 7.2.11 (cli) (built: Oct 16 2018 00:40:40) ( NTS )
```
**Nextcloud version:** (see Nextcloud admin page)
nextcloud:13-apache (Docker)

**Updated from an older Nextcloud/ownCloud or fresh install:**
 fresh install

**Where did you install Nextcloud from:**
Docker

but IE11 is work ok.

**Comment by skjnldsv** [comment] 2020-09-09 11:51
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-09-09 11:51 UTC
Labels: 0. Needs triage, bug
