### ISSUE TITLE
[Bug]: Deleting a document does not automatically update the list

### ISSUE THREAD

**Issue by hongtring** [nextcloud/server#37616] opened 2023-04-06 07:12 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Deleting a document does not automatically update the list

### Steps to reproduce

1. Upload invoices to the system
2. Click on the document details
3. Click to expand
4. Click delete document
5. Move to MH list, do not automatically update the list

### Expected behavior

Move to MH list, automatically update the list

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

**Comment by skjnldsv** [comment] 2024-08-01 05:54
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-08-01 05:54 UTC
Labels: bug, 1. to develop, feature: files, 25-feedback
