### ISSUE TITLE
[Bug]: update from 28 to 29.0.1 fails due to index conflicts

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#45617] opened 2024-06-01 09:19 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

error message:
Updated database
InvalidArgumentException: Index name "f_storage_size" for table
"oc_oc_filecache_9yu3vb8mm1t9v" collides with the constraint on table
"oc_oc_filecache_38te42giu87qb".
The update was unsuccessful.

### Steps to reproduce

1. upgrade 28 to 29
2.
3.

### Expected behavior

I had to remove all indexes (but PRIMARY) manually from the following tables
- oc_lucene_status_old
- oc_oc_filecache_38te42giu87qb
- oc_oc_filecache_9yu3vb8mm1t9v
to finish the upgrade and get the db working again

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
config:list system                      
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "default_phone_region": "AT",
        "installed": true,
        "enable_previews": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "maintenance_window_start": 1,
        "knowledgebaseenabled": true,
        "session_lifetime": 3600,
        "session_keepalive": true,
        "auto_logout": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtptimeout": 10,
        "loglevel": 0,
        "allow_local_remote_servers": true,
        "share_folder": "\/Shared",
        "trusted_domains": [
            "service2.chricar.at",
            "service.chricar.at"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "filesystem_check_changes": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": true,
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/service2.chricar.at\/owncloud",
        "apc.enable_cli": 1,
        "opcache.save_comments": 1,
        "opcache.revalidate_freq": 60,
        "opcache.validate_timestamps": 0,
        "opcache.memory_consumption": 512,
        "opcache.interned_strings_buffer": 64,
        "opcache.max_accelerated_files": 50000,
        "opcache.max_wasted_percentage": 15,
        "activity_use_cached_mountpoints": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "filelocking.enabled": "true",
        "preview_max_x": 512,
        "preview_max_y": 512,
        "preview_max_scale_factor": 1,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\OpenDocument"
        ],
        "has_rebuilt_cache": true,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "files_clipboard",
            "files_accesscontrol",
            "issuetemplate",
            "dashboard",
            "files_external_gdrive",
            "ojsxc",
            "quickaccesssorting",
            "ocr",
            "files_fulltextsearch_tesseract",
            "documentserver_community"
        ],
        "0": {
            "verify_peer_off": true
        },
        "data-fingerprint": "ae3877dea6ec102abcc8189aefcf8fcc",
        "mail_sendmailmode": "smtp",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - analytics: 4.13.0
  - announcementcenter: 6.8.1
  - audioplayer: 3.4.1
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.4
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.0
  - drawio: 3.0.2
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_antivirus: 5.5.3
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_fulltextsearch: 29.0.0
  - files_fulltextsearch_tesseract: 27.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - fulltextsearch: 29.0.0
  - fulltextsearch_elasticsearch: 29.0.1
  - groupfolders: 17.0.0
  - integration_google: 2.2.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - phonetrack: 0.8.1
  - photos: 2.5.0
  - previewgenerator: 5.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - quickaccesssorting: 3.0.0
  - quota_warning: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.2
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - cadviewer: 9.50.1 (installed 9.50.1)
  - carnet: 0.25.4 (installed 0.25.4)
  - emlviewer: 1.0.9 (installed 1.0.9)
  - encryption: 2.17.0
  - files_photospheres: 1.28.1 (installed 1.28.1)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.18.0 (installed 2.7.0)
  - googledocsredirect: 1.0.7 (installed 1.0.7)
  - metadata: 0.20.0 (installed 0.20.0)
  - onlyoffice: 9.2.2 (installed 9.2.2)
  - spreed: 19.0.1 (installed 19.0.1)
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
no errors
```

**Comment by kesselb** [comment] 2024-06-01 12:28
Duplicate of https://github.com/nextcloud/server/issues/41253

**Closed by kesselb** 2024-06-01 12:28 UTC
Labels: bug, 0. Needs triage, 29-feedback
