### ISSUE TITLE
[Bug]: wrong quota used (2GB), but is set at 10GB ?!

### ISSUE THREAD

**Issue by mrAceT** [nextcloud/server#33263] opened 2022-07-18 14:01 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The updating of the quota wasn't working for some time, but updating via 'occ' worked fine, do I hadn't taken the time to write up a bug report just yet.

But now things have taken a turn for the worst. My (admin) account is set 20 20Gb, it uses 8.7Gb and when I check via 'occ' all is well, but I can no longer add data to my account. Upon logging in to the web interface I saw that the web interface thinks I only am allowed to use 2Gb. More over, an other users shows my quota! But that user has a default quota of 200MB?

This I have tried to fix it:
- Alter all default quota to hard set quota of 200MB (changing  'occ usage-report:generate' that quota record from '200 MB' to '209715200' (bytes) => no effect
- altering various quota's
 that of me (the admin), even larger, smaler, keeps saying 2Gb
 that of the (new) client, larger, smaller, keeps showing my usage and that 2Gb quota..
 that of the only other user who has a 2Gb quota, changed it to 3Gb, that does take affect (as intended, just for that user..)
- removing all shares to other accounts => no effect
- as a last resort I have even tried to remove the account of the new client (was a demo account, it will become live after the holiday)  showing my quota info => no effect

I have read of some quota problems with S3, might that be it? Is S3 not good enough built into Nextcloud to use?
Or is there something wrong with my admin account?

![Image](https://help.nextcloud.com/uploads/default/original/3X/2/2/224a6555861376828640349b6be15af8e712460e.png)

### Steps to reproduce

1. log in as admin on the web interface
2. click users
3. try and alter the quota of a user..

### Expected behavior

1. show the correct quota previously set
2. show the correct quota at the correct user
3. show the correct used quota

### Installation method

Web installer on a VPS or web space

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "nl",
        "default_phone_region": "NL",
        "maintenance": false,
        "loglevel": 1,
        "log_type": "syslog",
        "syslog_tag": "Nextcloud",
        "logfile": "",
        "theme": "",
        "versions_retention_obligation": "7, auto",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 31,
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "***REMOVED SENSITIVE VALUE***",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": 443,
                "use_ssl": true,
                "region": "***REMOVED SENSITIVE VALUE***",
                "use_path_style": false
            }
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - apporder: 0.15.0
  - calendar: 3.4.2
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - groupquota: 0.1.8
  - keeweb: 0.6.9
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.6
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quota_warning: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.1.1
  - richdocumentscode: 22.5.301
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.3
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - user_usage_report: 1.8.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
both do not exist?
```

**Comment by mrAceT** [comment] 2022-07-18 15:33
There was an update to 24.0.3 and I have installed that update, hoping it might fix my problem.

I am not completely sure, but the web interface does now update the quota (checked via 'occ user:setting [user name] files quota')
But still the front end (and everywhere else that counts)  keeps using that darn 2Gb (website, windows sync client) OCC does give the quota set by website/occ :-/

**Comment by mrAceT** [comment] 2022-08-01 19:27
An update,

This issue recently surfaced again. I think it has to doe with:
`'memcache.local' => '\\OC\\Memcache\\APCu', `
I had originally set the opcache.revalidate_freq to quite an high value. I think this plays havoc with this account setting?

Default is 2, I have now set it to 1 and it still shows the old setting, but let it be and after a few minutes it now picks up the right value..

AD: I also have the impression it is more troublesome with the (first) admin/main account?

**Comment by CarlSchwan** [comment] 2022-10-17 14:31
Duplicate of #34422

**Closed by CarlSchwan** 2022-10-17 14:31 UTC
Labels: bug, 0. Needs triage
