### ISSUE TITLE
Search for files in trashbin

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#23194] opened 2020-10-05 14:07 UTC
For restoring files in the trashbin (especially in groupfolders) it would make sense to perform a search inside of the trashbin if the user has currently opened the trash file list.

**Comment by being-peace** [comment] 2023-03-17 09:07
Mostly a duplicate of https://github.com/nextcloud/server/issues/24544.

**Comment by susnux** [comment] 2024-08-07 18:10
This is now possible with #45708

**Closed by susnux** 2024-08-07 18:10 UTC
Labels: enhancement, 1. to develop, feature: trashbin
