### ISSUE TITLE
When uploading photos via mobile app the activity emails show it as download

### ISSUE THREAD

**Issue by io-node** [nextcloud/server#6073] opened 2017-08-10 15:43 UTC
### Steps to reproduce
1. Open (Android) app
2. Upload files (photos) to sub-folder on NC server
3. Receive activity email stating files have been downloaded

### Expected behaviour
Activity email should show the files were uploaded/added

### Actual behaviour
Activity email shows the files as have been downloaded

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** mysql 5.5.53

**PHP version:** php 7.0.18

**Nextcloud version:** 12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from NC 12.0.0

**Where did you install Nextcloud from:** Official NC website

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - announcementcenter: 3.1.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - deck: 0.2.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.3
  - passman: 2.1.4
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - spreedme: 0.3.11
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "occ3bgzu13dp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR",
            "X-Forwarded-For"
        ],
        "datadirectory": "\/media\/nextcloud",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.1.5",
        "dbname": "nextcloud_stable",
        "dbhost": "192.168.7.244",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "trusted_proxies": [
            "192.168.7.241",
            "192.168.7.245"
        ],
        "overwriteprotocol": "https",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwritewebroot": "\/",
        "mail_from_address": "cloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "wijman.net",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "maintenance": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud-stable.log",
        "loglevel": "0",
        "log_rotate_size": "104857600",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "filesystem_check_changes": 1,
        "enable_previews": true,
        "preview_max_x": 800,
        "preview_max_y": 800,
        "preview_max_scale_factor": 4,
        "skeletondirectory": "\/media\/nextcloud\/skeleton",
        "session_keepalive": true,
        "activity_expire_days": 365,
        "theme": "wijman",
        "mail_smtpsecure": "tls",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "asset-pipeline.enabled": true,
        "share_folder": "\/Shares"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

#### Web server error log
<details>
<summary>Web server error log</summary>
none
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
none
</details>

**Comment by MorrisJobke** [comment] 2017-08-10 16:08
I also have seen, that after an upload the Android app re-downloads the file (at least there was a GET request in the access log).

cc @AndyScherzinger @tobiasKaminsky @mario

**Comment by rullzer** [comment] 2017-08-10 20:09
Does the android app maybe not set the timestamp? So the app think ah newer file lets fetch that?

**Comment by tobiasKaminsky** [comment] 2017-08-11 05:52
As a simplest answer: during upload you can specify if you want to 
- keep the file in the source directory
- move the file to the nextcloud directory
- upload and delete the source file

maybe the wrong option was chosen?

I tested it with the second option and could immediately open the file within the app, so no download was necessary.

And yes, we set the timestamp.

**Comment by AndyScherzinger** [comment] 2017-08-11 09:34
@tobiasKaminsky to me it reads, the issue is that the activity app on the Nc server says that the image has been downloaded right after it has been uploaded which is wrong in any way I guess...

**Comment by tobiasKaminsky** [comment] 2017-08-11 12:14
Hmm cannot reproduce it with NC 2.0.0-rc2.

**Comment by AndyScherzinger** [comment] 2017-08-11 13:05
Then I guess we are fine. Since 2.0.0-rc2 ships a rewritten auto upload this might well have been fixed by accident.

**Comment by tobiasKaminsky** [comment] 2017-08-11 13:32
> fixed by accident

:tada: :rofl: :tada:

**Comment by io-node** [comment] 2017-08-13 18:04
In regards to  NC 2.0.0-rc2. Is that a specific all/module? Just asking since we are on NC 12.0.1 now and bit confused about the numbering :-)

**Comment by AndyScherzinger** [comment] 2017-08-13 21:07
2.0.0 is the version number of the upcoming Android client release. Sorry for the confusion :)

**Closed** 2017-09-03 17:09 UTC
