### ISSUE TITLE
NC 20.0.5.2 CompareVersion.php is broken

### ISSUE THREAD

**Issue by TP75** [nextcloud/server#25211] opened 2021-01-19 14:11 UTC
Nextcloud version _(eg, 18.0.2)_: 20.0.5.2
Operating system and version _(eg, Ubuntu 20.04)_: Debian 10.7 Buster
Apache or nginx version _(eg, Apache 2.4.25)_: Apache/2.4.38 (Debian)
PHP version _(eg, 7.1)_: PHP 7.3.19-1~deb10u1 (cli)

The issue we are facing:

After upgrade from 20.0.4 to 20.0.5.2 the logging gets flooded by 1.5 GB of junk on a daily basis. Presumably, the Nextcloud *CompareVersion.php* and/or the *BackgroundJob.php* are broken.

For details see:

  * https://help.nextcloud.com/t/nc-20-0-5-2-floods-logging/104859

**Comment by MegaV0lt** [comment] 2021-01-19 15:06
Log floods here too. Nc 20.0.5.2 on Debian 10.7

**Comment by N3m3515** [comment] 2021-01-19 19:08
Should be fixed by: https://github.com/nextcloud/server/pull/25138

**Comment by TP75** [comment] 2021-01-19 20:52
Looks good and may reflect on:
  * https://github.com/nextcloud/server/issues/25137
  * https://help.nextcloud.com/t/nextcloud-20-0-5-2-getcutofftimestamp-must-be-of-the-type-int-bool-returned/104597

**Comment by kesselb** [comment] 2021-01-19 21:23
Duplicate of #25202

**Closed by kesselb** 2021-01-19 21:23 UTC
Labels: 0. Needs triage, bug
