### ISSUE TITLE
[Bug]: Image/video online previews may not be turned off

### ISSUE THREAD

**Issue by mrzkj** [nextcloud/server#31760] opened 2022-03-30 13:48 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When we click the image/video online preview, preview after can be in the top right corner of the close button to close, but if we at the time of quick double-click the image/video files, also can undertake online preview, but unable to get in the top right corner of the close button to close the preview screen, unless you refresh the page. This caused some new users to double click on the file preview, so they were bothered by this BUG
The following link is for the BUG replay video
[https://youtu.be/Jhg2tz7Uoe8](url)

### Steps to reproduce

1.Quick double click on picture/video file for online preview
2.the upper right corner to close the preview
3.Then there was the BUG, the inability to close the preview page

### Expected behavior

Fix the bug of the online preview of this picture / video, so that users can close the preview page normally even if they double-click the preview

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Could not open input file: occ
```

**Comment by szaimen** [comment] 2022-03-30 13:59
Duplicate of https://github.com/nextcloud/viewer/issues/893

**Closed by szaimen** 2022-03-30 13:59 UTC
Labels: bug, 0. Needs triage
