### ISSUE TITLE
[Bug]: core/js/mimetypelist.js fails with integrity check

### ISSUE THREAD

**Issue by socialize-IT** [nextcloud/server#32252] opened 2022-05-03 12:37 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The configuration overview with an error that the integrity check fails with "core/js/mimetypelist.js / invalid hash" after updating to nc 24.

### Steps to reproduce

1. Update to NC 24.
2. Open the overview in settings.
3. There is an error about failed integrity check (core/js/mimetypelist.js / invalid hash)

### Expected behavior

No error

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "yyy.xxx.zz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "overwrite.cli.url": "https:\/\/yyy.xxx.zz",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "force_language": "de",
        "force_locale": "de_DE",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": false,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "simpleSignUpLink.shown": false,
        "auth.webauthn.enabled": false,
        "default_phone_region": "DE",
        "skeletondirectory": "",
        "templatedirectory": "",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "polls",
            "onlyoffice",
            "keeweb",
            "sendent",
            "eidlogin",
            "bruteforcesettings",
            "hidesidebars",
            "groupfolders"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
- accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - collectives: 1.0.0
  - comments: 1.14.0
  - contacts: 4.1.0
  - dav: 1.22.0
  - deck: 1.7.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - forms: 2.5.0
  - groupfolders: 11.1.2
  - guests: 2.2.0
  - keeweb: 0.6.8
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - onlyoffice: 7.3.2
  - password_policy: 1.14.0
  - polls: 3.6.1
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 94195a260a005dac543c3f6aa504f1b28e0078297fe94a4f52f012c16c109f0323eecc9f767d6949f860dfe454625fcaf1dc56f87bb8350975d8f006bbbdf14a
                            [current] => 1b07fb272efa65a10011ed52a6e51260343c5de2a256e1ae49f180173e2b6684ccf90d1af3c19fa97c31d42914866db46e3216883ec0d6a82cec0ad5529e78b1
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
Fehler	PHP	Error: Uninitialized string offset: 0 at /var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39	
2022-05-03T14:22:06+0200
Fehler	PHP	Error: Uninitialized string offset: 0 at /var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39	
2022-05-03T14:21:51+0200
Fehler	PHP	Error: Uninitialized string offset: 0 at /var/www/nextcloud/core/Command/Maintenance/Mimetype/GenerateMimetypeFileBuilder.php#39	
2022-05-03T14:19:59+0200
```

### Additional info

Rewriting mymetype.js via occ didn't change anything.

**Comment by szaimen** [comment] 2022-05-03 12:39
Duplicate of https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/600

**Closed by szaimen** 2022-05-03 12:39 UTC
Labels: bug, 0. Needs triage
