### ISSUE TITLE
Custom Theme doesn't allow to change the folder icon (and maybe other icons as well)

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#21634] opened 2020-06-30 10:22 UTC
I tested it with Nextcloud 19 by reusing the "example" theme.

The Theming app was disabled and I created following file `themes/example/core/img/filetypes/folder.svg` to replace the folder icon. After enabling the thema all settings from the example theme, including Nextcloud icon ad favicon (which are also located in "themes/example/core/img/" where replaced but not the folder icon. I didn't tested other icons but replacing them might fail as well.

I also cleared the browser cache and restarted apache to avoid caching issues.

**Comment by szaimen** [comment] 2021-06-07 13:07
I suppose this is a duplicate of https://github.com/nextcloud/server/issues/20631?

**Closed** 2021-06-07 13:07 UTC
Labels: 0. Needs triage, bug, needs info
