### ISSUE TITLE
App Favicons loading with bad resolution

### ISSUE THREAD

**Issue by florianwgnr** [nextcloud/server#35584] opened 2022-12-04 11:37 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With Nextcloud 25, every app-related favicon shows a very low resolution, while the favicon-file itself has a high resolution. 

This problem occurs both with old installations after the update and with new installations.

For example with Nextcloud-Deck: Nextcloud uses the URL on the right to load favicons and it provides a 128x128 favicon with a bad resolution. On the left is the original "favicon.ico"-file from /apps/deck/img, also with 128x128 pixels. The issue must be inbetween. 

![grafik](https://user-images.githubusercontent.com/39341393/205488407-c89622f0-406e-4a77-a77a-a0387b8a9e14.png)

### Steps to reproduce

1. Open any Nextcloud-App (Dashboard, Files, Deck, ...) with Nextcloud 25 
2. Look at the favicon (might need to clear the cache)
3. => Low resolution

(Nextcloud instant trial doesn´t show any app-related favicon btw.) 

### Expected behavior

Favicons should have the highest possible resolution. 

### Installation method

None

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Fresh installation: 
Enabled:
  - activity: 2.17.0
  - approval: 1.0.10
  - cfg_share_links: 3.0.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - facerecognition: 0.9.5
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 0.2.1
  - memories: 4.8.2
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - firstrunwizard: 2.14.0
  - recognize: 3.2.3
  - recommendations: 1.4.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

**Comment by florianwgnr** [comment] 2022-12-04 11:45
This also affects the icon-generation for 512x512 icons. 

On the left is the original image with (512x512) while the url generates a 512x512 image with a very bad resolution. 

![grafik](https://user-images.githubusercontent.com/39341393/205488494-8ecaa2c0-5df3-4e84-88a8-1a352ad7141e.png)

**Comment by joshtrichards** [comment] 2023-08-29 20:23
Duplicate of #27502

**Closed by joshtrichards** 2023-08-29 20:23 UTC
Labels: bug, 0. Needs triage, feature: theming, 25-feedback
