### ISSUE TITLE
Memory and CPU usage on desktop web when vue.js is installed

### ISSUE THREAD

**Issue by kwisatz** [nextcloud/server#19364] opened 2020-02-08 13:29 UTC
### Steps to reproduce
1. Install Vue Developer Tools extension for Chromium
2. Open Nextcloud Web interface and access the files app (issue will not occur e.g. on the admin interface)
3. Observe CPU usage reach 150%+ and memory leak increasingly

### Expected behaviour
No memory leakage, no extensive to no CPU usage once the page has been rendered.

### Actual behaviour
The Vue.js devtools use 130%+ of CPU and after a short while already 3GB (sic!) of memory.
The browser tab hosting the Nextcloud web UI is using 160% CPU, and a high, but not extreme amount of memory with 400MB.

Please note that this behavior was existent even before enabling the Collabora extension.

### Server configuration

**Operating system:** Debian 10.2

**Web server:** Apache 2.4

**Database:** Postgres

**PHP version:** 7.3.11

**Nextcloud version:** 18.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** jurisic.org

<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 5.0.8
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.2
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.2
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - keeweb
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tentwentyfour.lu"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "htaccess.RewriteBase": "\/",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "https:\/\/cloud.tentwentyfour.lu",
        "overwritehost": "cloud.tentwentyfour.lu",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "upgrade.disable-web": "true",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                       |
+-------------------------------+-------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                         |
| homeFolderNamingRule          |                                                                                           |
| lastJpegPhotoLookup           | 0                                                                                         |
| ldapAgentName                 |                                                                                           |
| ldapAgentPassword             | ***                                                                                       |
| ldapAttributesForGroupSearch  |                                                                                           |
| ldapAttributesForUserSearch   |                                                                                           |
| ldapBackupHost                |                                                                                           |
| ldapBackupPort                |                                                                                           |
| ldapBaseGroups                | ou=people,dc=hostname,dc=tld                                                              |
| ldapBase                      | ou=people,dc=hostname,dc=tld                                                              |
| ldapBaseUsers                 | ou=people,dc=hostname,dc=tld                                                              |
| ldapCacheTTL                  | 600                                                                                       |
| ldapConfigurationActive       | 1                                                                                         |
| ldapDefaultPPolicyDN          |                                                                                           |
| ldapDynamicGroupMemberURL     |                                                                                           |
| ldapEmailAttribute            | mail                                                                                      |
| ldapExperiencedAdmin          | 0                                                                                         |
| ldapExpertUUIDGroupAttr       |                                                                                           |
| ldapExpertUUIDUserAttr        |                                                                                           |
| ldapExpertUsernameAttr        |                                                                                           |
| ldapExtStorageHomeAttribute   |                                                                                           |
| ldapGidNumber                 | gidNumber                                                                                 |
| ldapGroupDisplayName          | cn                                                                                        |
| ldapGroupFilter               | (&(|(objectclass=companyNameUser)))                                                       |
| ldapGroupFilterGroups         |                                                                                           |
| ldapGroupFilterMode           | 0                                                                                         |
| ldapGroupFilterObjectclass    | companyNameUser                                                                           |
| ldapGroupMemberAssocAttr      |                                                                                           |
| ldapHost                      | ldap.svc.hostname.tld                                                                     |
| ldapIgnoreNamingRules         |                                                                                           |
| ldapLoginFilter               | (&(|(objectclass=companyNameUser))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))   |
| ldapLoginFilterAttributes     |                                                                                           |
| ldapLoginFilterEmail          | 1                                                                                         |
| ldapLoginFilterMode           | 0                                                                                         |
| ldapLoginFilterUsername       | 1                                                                                         |
| ldapNestedGroups              | 0                                                                                         |
| ldapOverrideMainServer        |                                                                                           |
| ldapPagingSize                | 500                                                                                       |
| ldapPort                      | 389                                                                                       |
| ldapQuotaAttribute            |                                                                                           |
| ldapQuotaDefault              |                                                                                           |
| ldapTLS                       | 0                                                                                         |
| ldapUserAvatarRule            | default                                                                                   |
| ldapUserDisplayName           | displayname                                                                               |
| ldapUserDisplayName2          |                                                                                           |
| ldapUserFilter                | (|(objectclass=companyNameUser))                                                          |
| ldapUserFilterGroups          |                                                                                           |
| ldapUserFilterMode            | 0                                                                                         |
| ldapUserFilterObjectclass     | companyNameUser                                                                           |
| ldapUuidGroupAttribute        | auto                                                                                      |
| ldapUuidUserAttribute         | auto                                                                                      |
| turnOffCertCheck              | 0                                                                                         |
| turnOnPasswordChange          | 0                                                                                         |
| useMemberOfToDetectMembership | 1                                                                                         |
+-------------------------------+-------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Chromium Version 79.0.3945.130 (Developer Build) built on Debian 10.2, running on Debian 10.2 (64-bit)

**Operating system:** Debian 10.2

### Logs

Web and Nextcloud server logs are not IMHO not relevant in this case and contain no related errors or messages.

#### Browser log
<details>
<summary>Browser log</summary>

```
DevTools failed to parse SourceMap: https://cloud.companyname.tld/apps/spreed/js/talk-files-sidebar.js.map
DevTools failed to parse SourceMap: https://cloud.companyname.tld/apps/spreed/js/collections.js.map
DevTools failed to parse SourceMap: https://cloud.companyname.tld/apps/spreed/js/talk-files-sidebar-loader.js.map
```
</details>

**Comment by kevinley** [comment] 2020-02-08 13:33
Reproduced on:

Browser: Version 79.0.3945.130 (Official Build) (64-bit)
Operating system: macOS 10.15.3 (19D76)

**Comment by kwisatz** [comment] 2020-02-08 13:40
Setting the dev console to verbose, I can see thousands of previously hidden log entries:

```
[viewer] Received post message {msgId: {…}, args: undefined, deprecated: undefined}
msgId:
devtoolsEnabled: false
vueDetected: true
status: "reject"
data: "TypeError: {(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)(intermediate value)}[t.action] is not a function"
```

**Comment by kesselb** [comment] 2020-02-08 14:04
cc @skjnldsv :fearful:

**Comment by kwisatz** [comment] 2020-02-08 14:08
I didn't realize there was a nextcloud/nextcloud-vue repository, or I might have posted this issue ticket over there.

**Comment by janis91** [comment] 2020-02-09 15:05
@kwisatz I think the issue is right in this repo. nextcloud-vue only provides some common vue components

**Comment by szaimen** [comment] 2021-06-07 18:15
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by skjnldsv** [comment] 2021-06-09 12:43
Yeah, it's weird.We don't ship dev builds and the vue devtools are disabled on prod builds

**Closed by skjnldsv** 2021-06-09 12:43 UTC
Labels: 0. Needs triage, bug, needs info
