### ISSUE TITLE
[Bug]: User list context menu on mobile devices closes after touch without executing commands

### ISSUE THREAD

**Issue by Rhobil** [nextcloud/server#36635] opened 2023-02-09 13:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As long as i know Nextcloud (i guess v9+) the **contextmenu on the user list** on **mobile devices** that opens by clicking (or touching) on a field on the right side of a user in the list does open, but if anything is touched on the context menu it **closes without starting any action**.

Context menu on mobile devices of the users in the user list not working properly.

Seems to be a css/javascript problem.

### Steps to reproduce

1. log in as user with user administrative rights
2. go to the user list in the settings menu
3. click (touch) on the context menu button
4. click (touch) on any element of the context menu

### Expected behavior

Actions of the context menu are executed.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.fireserver.net",
            "fireserver.net\/roundcube"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "https:\/\/nextcloud.fireserver.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "defaultapp": "apporder, activity, files",
        "allow_user_to_change_display_name": true,
        "skeletondirectory": "",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "appcodechecker": true,
        "updater.release.channel": "stable",
        "activity_expire_days": 14,
        "maintenance": false,
        "filesystem_check_changes": 1,
        "theme": "",
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud.log",
        "app_install_overwrite": [
            "keeweb",
            "radio",
            "documentserver_community",
            "files_trackdownloads",
            "impersonate",
            "apporder"
        ],
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - apporder: 0.15.0
  - bookmarks: 12.0.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.2
  - checksum: 1.2.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - cookbook: 0.10.1
  - dav: 1.24.0
  - documentserver_community: 0.1.13
  - encryption: 2.13.0
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_antivirus: 4.0.2
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.0
  - impersonate: 1.11.0
  - keeweb: 0.6.10
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - music: 1.8.1
  - news: 20.0.1
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - rainloop: 7.2.6
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - circles: 0.18.9
  - dashboard: 7.0.0
  - recommendations: 0.6.0
  - twofactor_totp
  - user_ldap: 1.10.2
  - user_saml: 5.1.2
  - user_status: 1.3.1
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by joshtrichards** [comment] 2023-08-30 11:43
Duplicate of #21260.

Hi @Rhobil - Thanks for the report. 

Appears to be similar to #21260. Consolidating tracking there. Feel free to subscribe to that issue or give it a :+1:.

**Closed by joshtrichards** 2023-08-30 11:43 UTC
Labels: bug, design, 0. Needs triage, feature: users and groups, 25-feedback
