### ISSUE TITLE
Contacts List Issue Not Resolved Sensibly

### ISSUE THREAD

**Issue by ttbek** [nextcloud/server#7233] opened 2017-11-21 09:33 UTC
### Steps to reproduce
1. Run Nextcloud 12.3 normally
2. Set share settings to only allow sharing within groups
3. Click on the contacts menu in the upper right

### Expected behaviour
Contact autocomplete and initial shown contacts show only those within the users groups and/or gathered from federation and their contacts app, but not users that do not have a common group, are not in their contacts app list, and do not have their info published for federation, are not on LDAP, etc..  

### Actual behaviour
Shows these other individuals in the contact list anyway.  

### Server configuration

I'm happy to give more details but the don't seem relevant as the issue is largely decision based rather 
than technical.  

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes, from 12.0

The issue exists in both versions, see issue #4656, the most upvoted comment states "Why doesn't it just use the sharing setting we have that can limits sharing to users within the own groups. That was what I would expect to apply there too."  This is also my expected behaviour, but I wouldn't mind having a second set of options if people want to control this independent of the sharing setting.  This was closed with  #4757 cited as resolution.  Turning on/off autocomplete entirely is not a satisfactory resolution because you then cannot use the perfectly functional sharing autocomplete that respects the within group restriction as one would expect.   #5096  Was actually closed in favor of #4656 .... but maybe giving admins the option to remove the contacts menu entirely is a potential bandaid option for my particular use case, but it has drawbacks that also don't make it a real solution for all admins (e.g., they won't want to remove it entirely if they are using the contacts app, LDAP, etc...).

**Comment by cornouws** [comment] 2017-11-22 21:33
I confirm this problem. NC 12.03
Adding groups to "Exclude groups from sharing" does not work.

All that has been said by many others in #4556, #5131, #5333, #5606 and #5107 about the privacy problem is just true. Having multiple groups on one NCserver just is not possible.

I do not understand why all other issues are closed as dupes of #5107 "Privacy *enhancements* for contacts menu"

**Comment by MorrisJobke** [comment] 2017-11-23 14:47
> I do not understand why the issues are closed as dupes of #5107 "Privacy enhancements for contacts menu". I would not see "Respecting privacy" as enhancement.

We backported it to stable12: #6554

It will be released with the upcoming 12.0.4. You could test the 12.0.4 RC1.

Duplicate of #5107

**Closed by MorrisJobke** 2017-11-23 14:47 UTC

**Comment by cornouws** [comment] 2017-11-23 15:53
> We backported it to stable12: #6554
> It will be released with the upcoming 12.0.4. You could test the 12.0.4 RC1.

Thanks for explaining this. Sorry I missed that in what I did read.

**Comment by jj-uk** [comment] 2018-08-07 22:52
If "Allow username autocompletion in share dialog" is checked, and "Allow apps to use share API" is UNCHECKED, then username autocompletion still occurs, even though the "Allow username autocompletion in share dialog" option is hidden when "Allow apps to use share API" is unclicked.

To reproduce:

CHECK Allow apps to use share API

CHECK Allow username autocompletion in share dialog

Now UNCHECK Allow apps to use share API

Allow username autocompletion in share dialog is hidden, but still enabled, and hence all users on the system can be seen when clicking the contacts button..

**Comment by GuyPaddock** [comment] 2019-03-05 21:14
@jj-uk have you filed a separate report about this? IMO this is a pretty bad bug. What you described was exactly the problem -- we couldn't see the option because we had turned off the share API even though the hidden option _still has an effect on the contact menu_.
