### ISSUE TITLE
Thumbnails of 32px Way To Small 

### ISSUE THREAD

**Issue by compumatter** [nextcloud/server#6403] opened 2017-09-07 15:08 UTC
Using Nextcloud 12:

This post sums it up: https://help.nextcloud.com/t/thumbnail-size-too-small/20557/7

Need a admin level way of increasing the size of thumbnails in lists.  32px is just too small to even tell what it is a picture of.

For example: https://compumatter.com/test/nextcloud/tiny-thumbnails.png

Really need those to be in the order of 100px

Thanks

**Comment by MorrisJobke** [comment] 2017-09-07 16:56
cc @nextcloud/designers

**Comment by rullzer** [comment] 2017-09-07 18:24
IMO we should add a proper srcset so that depending on your DPI etc a proper thumbnail is chosen by the browser

**Comment by jancborchardt** [comment] 2017-09-08 10:31
The list view is designed to be proper for browsing files quickly but also with some indication as to what the file is, if it's a picture.

Increasing the thumbnail to 100px or more won't make it a list view anymore.
Hence I would say this is a duplicate of: Add a thumbnail/grid view to the Files app #6

**Closed by jancborchardt** 2017-09-08 10:31 UTC
Labels: 0. Needs triage, design, enhancement, feature: files

**Comment by skjnldsv** [comment] 2018-12-08 19:34
This has been increased for 15

**Comment by jancborchardt** [comment] 2018-12-10 18:11
> 2017, you'd think this would have been implemented by now

@oneilonline you are welcome to support development through donations at [Bountysource](https://www.bountysource.com/teams/nextcloud).

If you use Nextcloud at a company, do you already have a [Nextcloud enterprise subscription](https://nextcloud.com/enterprise/)? In that case you could use the support channel offered so we can prioritize your requests in the future.

Thank you! :slightly_smiling_face:
