### ISSUE TITLE
Add app installation and update capabilities to occ

### ISSUE THREAD

**Issue by DevCybran** [nextcloud/server#1947] opened 2016-10-28 14:01 UTC
It would be great to have an option to install and update apps from an appstore using the command line via `occ`. Currently, only apps already installed from the webinterface can be enabled or disabled. This is a problem if app installation or updating should be automated.

 
### Steps to reproduce
e.g. Executing `php $NEXTCLOUD_DIR/occ app:enable calendar` when the calendar app is not installed.

### Expected behaviour
The app should be downloaded and installed or updated from the appstore. Not necessarily by the `app:enable` command, it would be also possible or even better to have a separate command like `app:install` for this purpose.

### Actual behaviour
`occ` prints `calendar not found` and exits without installing or enabling the app.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Comment by DevCybran** [comment] 2016-10-28 14:05
See also the following forum thread: https://help.nextcloud.com/t/installing-and-updating-apps-from-the-command-line-occ/4622

**Comment by nickvergessen** [comment] 2016-10-28 14:13
Duplicate of https://github.com/nextcloud/server/issues/1599

**Closed by nickvergessen** 2016-10-28 14:13 UTC
