### ISSUE TITLE
event in editable shared calendar with visibility "busy" looses data when updated by a user shared to

### ISSUE THREAD

**Issue by simonbuehler** [nextcloud/server#11273] opened 2018-09-18 22:15 UTC
### Steps to reproduce
1. user a shares calendar writable to user b, creates event "doctor" with visibility "busy"
2. user b sees event with title "busy"
3. any updates user b does do destroy the original title, content or location

### Expected behaviour
events with visibility "busy" should not be editable in a shared calendar

### Actual behaviour
title can be overwritten with "busy"and location/description become empty

### Server configuration

**PHP version:** 7

**Nextcloud version:** 14

**Comment by maksemuz** [comment] 2018-12-12 11:24
> ### Expected behaviour
> events with visibility "busy" should not be editable in a shared calendar
I'd prefer such events should be shown as public for editors and as "only busy" for readonly users.

**Comment by georgehrke** [comment] 2019-09-14 14:39
Duplicate of https://github.com/nextcloud/server/issues/5551

**Closed by georgehrke** 2019-09-14 14:39 UTC
Labels: 0. Needs triage, bug, feature: dav
