### ISSUE TITLE
Exception: in_array() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by yucheng119** [nextcloud/server#28462] opened 2021-08-17 08:07 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

{"reqId":"byZarKrnTjWsDCzlTRkL","level":3,"time":"2021-08-17T08:01:40+00:00","remoteAddr":"172.17.36.211","user":"yucheng119","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&search=%E6%B5%8B%E8%AF%95&page=1&perPage=50&lookup=false","message":"in_array() expects parameter 2 to be array, null given","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.17.0 RC3","version":"22.1.0.1","exception":{"Exception":"Exception","Message":"in_array() expects parameter 2 to be array, null given","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareesAPIController","search",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareesAPI.search"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/sharees"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"in_array() expects parameter 2 to be array, null given","Code":0,"Trace":[{"file":"/var/www/html/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php","line":101,"function":"in_array","args":[10,null]},{"file":"/var/www/html/lib/private/Collaboration/Collaborators/Search.php","line":72,"function":"search","class":"OCA\\Circles\\Collaboration\\v2\\CollaboratorSearchPlugin","type":"->","args":["测试",25,0,{"__class__":"OC\\Collaboration\\Collaborators\\SearchResult"}]},{"file":"/var/www/html/apps/files_sharing/lib/Controller/ShareesAPIController.php","line":228,"function":"search","class":"OC\\Collaboration\\Collaborators\\Search","type":"->","args":["测试",[0,1,4,6,7],false,25,0]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"search","class":"OCA\\Files_Sharing\\Controller\\ShareesAPIController","type":"->","args":["测试","file",1,25,null,false]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareesAPIController"},"search"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareesAPIController","search",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareesAPI.search"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/sharees"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/apps/circles/lib/Collaboration/v2/CollaboratorSearchPlugin.php","Line":101},"CustomMessage":"--"},"id":"611b6cea14fdf"}

**Comment by acsfer** [comment] 2021-08-17 08:16
Duplicate of https://github.com/nextcloud/server/issues/28412

**Closed by acsfer** 2021-08-17 08:16 UTC
Labels: bug, 0. Needs triage
