### ISSUE TITLE
Error while enabling Mariadb 4-byte support

### ISSUE THREAD

**Issue by KyungWonPark** [nextcloud/server#15940] opened 2019-06-12 15:19 UTC
### Steps to reproduce
1. Was using nextCloud 16
2. Tried to enable Mariadb 4-byte support by following:
https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html

Everything was working fine, but I faced problem at
```bash
$ sudo -u www-data php occ maintenance:repair
```
### Expected behaviour
Nothing pops out

### Actual behaviour
```bash
Nextcloud is in maintenance mode - no apps have been loaded

 - Repair MySQL collation
     - Change row format for oc_addressbooks ...
     - Change collation for oc_addressbooks ...

In AbstractMySQLDriver.php line 125:
                                                                                                                                
  An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':  
                                                                                                                                
  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.                       
                                                                                                                                

In PDOStatement.php line 143:
                                                                                                           
  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.  
                                                                                                           

In PDOStatement.php line 141:
                                                                                                           
  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.  
```

Also, before I executed that maintenance command,
all file formats in output of command
```sql
MariaDB> SELECT NAME, SPACE, FILE_FORMAT FROM INFORMATION_SCHEMA.INNODB_SYS_TABLES WHERE NAME like "nextcloud%";
```
was “Barracuda” as desired.

But after executing maintenance command
`oc_addressbooks` entry which appeared in error output, has
file format of "Antelope”. (Changed from "Barracuda")

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache2

**Database:**
Mariadb

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 15.0.8

**Where did you install Nextcloud from:**
https://nextcloud.com/install/#

**Signing status:**
<details>
<summary>Signing status</summary>

```
Maintenance mode
This Nextcloud instance is currently in maintenance mode, which may take a while. This page will refresh itself when the instance is available again.

Contact your system administrator if this message persists or appeared unexpectedly.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Nextcloud is in maintenance mode - no apps have been loaded

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - audioplayer: 2.7.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - deck: 0.6.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - registration: 0.4.6
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - quota_warning
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Nextcloud is in maintenance mode - no apps have been loaded

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nas.dgist.cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "http:\/\/nas.dgist.cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": true,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"ZPvrApqAWZ20XZDQefwM","level":3,"time":"2019-06-12T15:03:53+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':\n\nSQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.","Code":0,"Trace":[{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":184,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':\n\nSQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.",{"errorInfo":["HY000",1709,"Index column size too large. The maximum column size is 767 bytes."],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":158,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY000",1709,"Index column size too large. The maximum column size is 767 bytes."],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':\n\nSQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes."]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php","line":178,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY000",1709,"Index column size too large. The maximum column size is 767 bytes."],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;",[]]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Repair\/Collation.php","line":100,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Repair.php","line":100,"function":"run","class":"OC\\Repair\\Collation","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/var\/www\/html\/nextcloud\/core\/Command\/Maintenance\/Repair.php","line":123,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Maintenance\\Repair","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":901,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":262,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OC\\Core\\Command\\Maintenance\\Repair"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":145,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Console\/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/console.php","line":97,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/occ","line":11,"args":["\/var\/www\/html\/nextcloud\/console.php"],"function":"require_once"}],"File":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":125,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.","Code":"HY000","Trace":[{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php","line":169,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[null]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Repair\/Collation.php","line":100,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Repair.php","line":100,"function":"run","class":"OC\\Repair\\Collation","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/var\/www\/html\/nextcloud\/core\/Command\/Maintenance\/Repair.php","line":123,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Maintenance\\Repair","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":901,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":262,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OC\\Core\\Command\\Maintenance\\Repair"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":145,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Console\/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/console.php","line":97,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/occ","line":11,"args":["\/var\/www\/html\/nextcloud\/console.php"],"function":"require_once"}],"File":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":143,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.","Code":"HY000","Trace":[{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","line":141,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php","line":169,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[null]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Repair\/Collation.php","line":100,"function":"execute","class":"Doctrine\\DBAL\\Statement","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Repair.php","line":100,"function":"run","class":"OC\\Repair\\Collation","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/var\/www\/html\/nextcloud\/core\/Command\/Maintenance\/Repair.php","line":123,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Maintenance\\Repair","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":901,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":262,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OC\\Core\\Command\\Maintenance\\Repair"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":145,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Console\/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/var\/www\/html\/nextcloud\/console.php","line":97,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"\/var\/www\/html\/nextcloud\/occ","line":11,"args":["\/var\/www\/html\/nextcloud\/console.php"],"function":"require_once"}],"File":"\/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":141}},"CustomMessage":"--"},"userAgent":"--","version":"16.0.1.1"}
```
</details>

**Comment by kesselb** [comment] 2019-06-12 15:31
Duplicate of #15648

Thank you for reporting :+1: Please check the other issue.

**Closed by kesselb** 2019-06-12 15:31 UTC
Labels: 0. Needs triage, bug

**Comment by KyungWonPark** [comment] 2019-06-13 06:42
@kesselb
@kesselb  

Hello
I've checked that issue and it looks very similar one
He/she got error log on 'oc_activity' and "1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"

while I got one with 'oc_addressbooks' and "1709 Index column size too large. The maximum column size is 767 bytes."

I'm not sure how should I apply solutions there

**Comment by kesselb** [comment] 2019-06-13 07:04
> I've fixed it...

Mind to share your solution?

**Comment by KyungWonPark** [comment] 2019-06-13 07:39
First I tried to manually change varchar field to text but it didnt work 
Since my error was about "Index column size too large",
I added following in the mariadb configuration file

```
[mysqld]
character-set-server = utf8mb4
collation-server = utf8mb4_general_ci
transaction_isolation = READ-COMMITTED
binlog_format = ROW
innodb_file_per_table = 1
innodb_large_prefix=true
innodb_file_format=barracuda
```
And it worked

**Comment by kesselb** [comment] 2019-06-13 07:43
Thank you :+1: 

https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html so the documentation looks correct.

**Comment by KyungWonPark** [comment] 2019-06-13 07:46
But no

I started from "MariaDB support" part and followed that guide

```
[mysqld]
innodb_file_per_table=1
```

I've configured cnf file as above but I got the error on original post
I'm not sure which line removed the error but I had to paste

```
[mysqld]
character-set-server = utf8mb4
collation-server = utf8mb4_general_ci
transaction_isolation = READ-COMMITTED
binlog_format = ROW
innodb_file_per_table = 1
innodb_large_prefix=true
innodb_file_format=barracuda
```
In order to make it work

**Comment by kesselb** [comment] 2019-06-13 09:20
Which version of MariaDB are you using?

**Comment by xuancong84** [comment] 2019-11-14 07:31
For me, it is not because of the extra lines below [mysqld], it is that I need to restart mariadb service before running the maintenance:repair, i.e.,
`systemctl restart mariadb`
