### ISSUE TITLE
Contact menu reload loop - IE11

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#6664] opened 2017-09-27 08:59 UTC
Contact menu reloads permanently in IE11

### Steps to reproduce
1. Login with IE 11
2. Open contacts menu

### Expected behaviour
Load once like in chrome/firefox

### Actual behaviour
![ie11_contact_menu_refresh](https://user-images.githubusercontent.com/16019165/30904535-8c990a80-a372-11e7-8bc9-e389d16d15c2.gif)

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MySQL/MariaDB

**PHP version:** 7.0 (webtatic)

**Nextcloud version:** 12.0.3 (daily via web updater)

**Updated from an older Nextcloud/ownCloud or fresh install:** OC 8.0 --> .. --> NC 11.0.5 --> NC 12.0.3

**Where did you install Nextcloud from:** tar.bz2 file from nextcloud.com

### Client configuration
**Browser:** IE 11

**Operating system:** Windows 7

**Comment by MorrisJobke** [comment] 2017-09-27 09:52
cc @georgehrke @ChristophWurst

**Comment by j-ed** [comment] 2017-09-27 09:54
It looks like this is a duplicate of https://github.com/nextcloud/server/issues/5281, isn't it?

**Comment by MorrisJobke** [comment] 2017-09-27 10:01
> It looks like this is a duplicate of #5281, isn't it?

You are right.

Duplicate of #5281

**Closed by MorrisJobke** 2017-09-27 10:01 UTC
Labels: bug, feature: contacts menu
