### ISSUE TITLE
Federated share notification is blank

### ISSUE THREAD

**Issue by rev138** [nextcloud/server#13228] opened 2018-12-21 22:29 UTC
### Steps to reproduce
1. Get a notification
2. Click on the notification icon

### Expected behaviour
This should display the notifications in a pop-up dialog

### Actual behaviour
The pop-up is blank if there are notifications. If there are no notifications a message is displayed saying "No notifications"

### Server configuration

**Operating system**: debian 9

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.2

**Nextcloud version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14.0.4

**Where did you install Nextcloud from:** tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.1.0
  - calendar: 1.6.4
  - circles: 0.15.1
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.0
  - data_request: 1.2.0
  - dav: 1.8.0
  - deck: 0.5.1
  - drop_account: 0.0.13
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.0.0
  - files_automatedtagging: 1.5.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ojsxc: 3.4.3
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.0.6
  - serverinfo: 1.5.0
  - spreed: 5.0.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - terms_of_service: 1.1.1
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - workflowengine: 1.5.0
Disabled:
  - activity
  - admin_audit
  - files_external
  - firstrunwizard
  - sharebymail
  - survey_client
  - theming
  - updatenotification
  - user_external
  - user_ldap
```
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx",
            "xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": 0,
        "theme": "gibberfish",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/opt\/nextcloud-data\/skeleton_files",
        "enable_previews": true,
        "token_auth_enforced": true,
        "filelocking.enabled": true,
        "updatechecker": false,
        "upgrade.disable-web": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image"
        ],
        "default_language": "en",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "log_rotate_size": 104857600,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": false,
        "maintenance": false,
        "defaultapp": "dashboard,files",
        "knowledgebaseenabled": false,
        "overwriteprotocol": "http",
        "remember_login_cookie_lifetime": 86400
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox or Vivaldi

**Operating system:** Fedora 29

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No logs
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"K0Ajkhkyuv0FQxjtcgqp","level":3,"time":"2018-12-21T14:59:23+00:00","remoteAddr":"172.18.0.11","user":"xxx","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/opt\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.0.10"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Content Security Policy: Ignoring duplicate source 'unsafe-inline'
Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
State changed to INITIATING jsxc.min.js:1:2054
Try to relogin jsxc.min.js:1:2054
I am not able to relogin jsxc.min.js:1:2054
State changed to SUSPEND jsxc.min.js:1:2054
TypeError: "this.userRemoteTemplate is not a function"
	parseParameter https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:89179
	parseMessage https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:88921
	forEach https://inc.gibber.fish/core/vendor/core.js?v=71e1b20b:18:2350
	parseMessage https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:88866
	renderedSubject https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:14:23425
	get https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:15827
	evaluate https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:16984
	Re https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:18879
	s https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:14:20633
	_render https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:32580
	r https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:63966
	get https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:15827
	Me https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:15752
	mount https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:63982
	mount https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:63844
	mount https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:86637
	init https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:22357
	f https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:52459
	f https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:52348
	$/< https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:55533
	$ https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:55108
	$/< https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:55258
	$ https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:55108
	$/< https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:55258
	$ https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:55108
	i https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:56860
	_update https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:31552
	r https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:63956
	get https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:15827
	run https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:16718
	Ee https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:14856
	te https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:11328
	Xt https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b:7:10834
notifications.js:7:10714
New search handler registered search.js:67:4
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://inc.gibber.fish/apps/ojsxc/js/jsxc/jsxc.min.js?v=71e1b20b
Source Map URL: jsxc.min.js.map[Learn More]
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://inc.gibber.fish/apps/notifications/js/notifications.js?v=71e1b20b
Source Map URL: notifications.js.map[Learn More]
```
</details>

**Comment by rev138** [comment] 2018-12-23 13:51
This belongs under the notifications app.

**Comment by r3pek** [comment] 2018-12-27 22:31
@rev138 not so sure this is a notifications app error. Wasn't the notification related to a share you received? Can you actually see the received share?

**Comment by victordariovera** [comment] 2018-12-28 03:47
@rev138 In my case, yes same issue... but only with sharing folder or files via federation.

**Comment by Lartza** [comment] 2018-12-28 09:35
I'm not convinced this is a notifications app issue, it could be either at this point.
The notifications app issue is at https://github.com/nextcloud/notifications/issues/232

Notifications not related to shares work just fine for me, like notification:generate ones.

On IRC @r3pek said the federated shares are also inaccessible without the notification even though they are shown in the Activity app as created and removed. Is this also the case for you @victordariovera and the shares are not shown?

I have to admit to not having used federation myself but it sounds like they shouldn't be tied to a single notification to be accessible since it can as shown here break. (Also notifications can be dismissed?)

**Comment by rubdevton** [comment] 2018-12-28 23:42
Agreed with @Lartza above. I could not find any mention of shares or alternatives to accepting or rejecting them other than through a notification. This means that if the notification is somehow dismissed without action, the share request might get stuck in limbo.

The notifications work fine in both the desktop client and the Android app, meaning the bug is only present in the web interface itself. I do not know enough about the inner workings of the notifications app to know if the fault lies within it.

My browser output is the same as https://github.com/nextcloud/notifications/issues/232. There is no server-side error whatsoever.

**Comment by victordariovera** [comment] 2018-12-29 15:36
@Lartza yes! exactly. I can't access federated resources at all (I'm using a fresh NC v.15 installation). I try to share from another NC installation, receive the notification (I only see them via web browser native notification) but when I click over the notification bell on NC Web there's not notification at all. Well, the bell shows a tiny red circle (like it showing pendent notifications).

**Comment by victordariovera** [comment] 2018-12-29 15:59
I try to accept the federated item in NC App (iOS) but notification does not appear. In activity there is a register for that sharing, but I cant accept it!

**Comment by brknkfr** [comment] 2019-01-01 17:06
As a workaround: Use the android app to see the notification an to accept or refuse the shared federated resource.

**Comment by victordariovera** [comment] 2019-01-02 00:12
Hi @brknkfr! I tried to accept federated resource from android..but I can't access it. Notifications appears in Android, and I can accept it, but the resource doesn't appear. 

The "sender" instance is running in a home server on port 8088 (https). This is because my ISP blocks port 80. The "receiving instance" is running in AWS at port 443 (https). It can be a problem?

By other hand, I can't configure same NC instance (sender) as an external storage (nextcloud type). It seems that NC search the connection in port 80/443 and I don't have any option to configure a non standard port (8088 in this case).

**Comment by benhartwich** [comment] 2019-01-03 19:43
Same problem here.

**Comment by violoncelloCH** [comment] 2019-01-03 23:54
just stumbled upon the same... to summarize and conclude what I could reproduce myself:
1. receive a federated share notification (see the notification pop up (if browser notifications are allowed) with the text)
2. switch to your nextcloud browser tab and click on the notification icon with the red dot indicating there is something new
3. see an empty popover (if there were no other notifications)(but no "no notification text")(if there are other notifications, they are shown, but not the federated share request)
![image](https://user-images.githubusercontent.com/22591354/50666485-35587e80-0fb5-11e9-9a14-f9959384ade3.png)
```
<div class="notification-wrapper"><!----> <!----></div>
```

The notification is shown in nc-android and from there I can accept the share successfully.

the console shows `this.userRemoteTemplate is not a function`:
<details>

```
TypeError: "this.userRemoteTemplate is not a function"
	parseParameter https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:89179
	parseMessage https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:88921
	forEach https://nc.violoncello.ch/core/vendor/core.js?v=999c80fa-34:18:2350
	parseMessage https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:88866
	renderedSubject https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:14:23425
	get https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:15827
	evaluate https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:16984
	Re https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:18879
	s https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:14:20633
	_render https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:32580
	r https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:63966
	get https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:15827
	Me https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:15752
	mount https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:63982
	mount https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:63844
	mount https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:86637
	init https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:22357
	f https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:52459
	f https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:52348
	$/< https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:55533
	$ https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:55108
	$/< https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:55258
	$ https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:55108
	$/< https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:55258
	$ https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:55108
	i https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:56860
	_update https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:31552
	r https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:63956
	get https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:15827
	run https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:16718
	Ee https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:14856
	te https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:11328
	Xt https://nc.violoncello.ch/apps/notifications/js/notifications.js?v=999c80fa-34:7:10834
notifications.js:7:10714 
```

</details>

cc @nextcloud/server-triage @nextcloud/sharing

**Comment by nickvergessen** [comment] 2019-01-04 00:06
Duplicate of the above issue

**Closed by nickvergessen** 2019-01-04 00:06 UTC
Labels: 0. Needs triage, bug, feature: activity and notification, feature: federation, regression

**Comment by violoncelloCH** [comment] 2019-01-04 00:21
of nextcloud/notifications#232 or which above one?
