### ISSUE TITLE
Shared by link: Items missing

### ISSUE THREAD

**Issue by nc0815** [nextcloud/server#6234] opened 2017-08-23 12:32 UTC
### Steps to reproduce
1. go to files app then file or folder, options: "Share"
2. set new share to email-address
3. set new share also as link
4. go to "Share by link" menu

### Expected behaviour
new created share should be shown there

### Actual behaviour
- no item shown
- only item is shown when created as link only

**possible solution:**
- share token is written to database table "share" for both types (shared with link and email-shares)
- adapt select for "Share by link" (...where token is not null) ? to show all shares which has token to access from external

### Server configuration
**Operating system**: Ubuntu 16.04
**Web server:** Apache 2.4.x
**Database:** MySQL
**PHP version:** 7.0.22
**Nextcloud version:** 12.0.2.
**Updated from an older Nextcloud/ownCloud or fresh install:** no / update from 12.0.1
**Where did you install Nextcloud from:** WebUpdater
**Signing status:** Integrity check: No errors have been found.
**Nextcloud configuration:** nothing special
**Are you using external storage, if yes which one:** local
**Are you using encryption:** no

### Client configuration
**Browser:** Firefox, Chrome, IE11
**Operating system:** Windows 7, Ubunutu 16.04, 

#### Nextcloud log (data/nextcloud.log)
set loglevel to "debug" but no dedicated action logged for this event

**Comment by rullzer** [comment] 2017-08-31 19:24
@schiessle what is you take on this?

**Comment by DJCrashdummy** [comment] 2018-01-31 11:53
i can't reproduce this with nextcloud 12.0.5...

**Comment by MorrisJobke** [comment] 2018-05-31 14:13
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2018-05-31 14:13 UTC
Labels: feature: sharing
