### ISSUE TITLE
Javascript errors while upgrading

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/server#9315] opened 2018-04-26 14:30 UTC
### Expected behaviour
After the update screen it should be possible to press the `Start update` button.

### Actual behaviour
A javascript file is missing and so the OC / OCA namespace is missing and the `Start update` button does not work.

I experienced this issue on every Nc update since the beginning but forgot to submit an issue before. Finishing the update via shell works very well.

The updater log has no errors only info log entries.

### Server configuration

**Operating system**: CentOS

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Official page

```

{"reqId":"...","level":1,"time":"2018-04-26T14:01:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::step: Repair step: Clear frontend caches","userAgent":"--","version":"13.0.1.1"}
{"reqId":"...","level":1,"time":"2018-04-26T14:01:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::info: Repair info: Image cache cleared","userAgent":"--","version":"13.0.1.1"}
{"reqId":"...","level":1,"time":"2018-04-26T14:01:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::info: Repair info: SCSS cache cleared","userAgent":"--","version":"13.0.1.1"}
{"reqId":"...","level":1,"time":"2018-04-26T14:01:21+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::info: Repair info: JS cache cleared","userAgent":"--","version":"13.0.1.1"}
```

![nextcloud-update](https://user-images.githubusercontent.com/1869584/39312041-c79f2572-496e-11e8-835c-c15a68d3c48b.png)

**Comment by MorrisJobke** [comment] 2018-04-27 07:28
@juliushaertl Might this be related to the "can't load theming data"? Because those things are also defined in the combined JS and thus also stored in the code that is served from the app data dir?

cc @rullzer 

Maybe worth to port the update page to purely self contained JS.

**Comment by juliushaertl** [comment] 2018-04-27 10:03
> @juliushaertl Might this be related to the "can't load theming data"? Because those things are also defined in the combined JS and thus also stored in the code that is served from the app data dir?

@MorrisJobke Not sure what you a re refering to with the "can't load theming data" here. 

> Maybe worth to port the update page to purely self contained JS.

That would make sense, we don't need any of those included js code on then update page.

@splitt3r When is the log output triggered for you? When you load the maintenance page? Can you also post your config?

**Comment by splitt3r** [comment] 2018-04-27 10:17
The update page with all the steps like download, backup etc. works great but then after pressing the button "Continue with web updater.." this page loads with the js erros.

**Config**:

````php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' =>
  array (
    0 => '***',
  ),
  'datadirectory' => '***',
  'dbtype' => 'mysql',
  'version' => '13.0.2.1',
  'dbname' => '***',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => '***',
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_from_address' => '***',
  'mail_smtpmode' => 'php',
  'mail_domain' => '***',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '***',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'updater.release.channel' => 'stable',
  'overwrite.cli.url' => '***',
  'overwriteprotocol' => 'https',
  'htaccess.RewriteBase' => '/',
  'htaccess.IgnoreFrontController' => true,
  'updater.secret' => '***',
);
```

**Comment by MorrisJobke** [comment] 2018-04-27 11:52
> @MorrisJobke Not sure what you a re refering to with the "can't load theming data" here.

That the maintenance page is not themed, because the app data is not accessible - #5789

The problem here is that we also combine the JS and this is stored in the app data folder and this is not available during upgrade.

**Comment by splitt3r** [comment] 2018-06-07 12:07
The issue is still present in 13.0.3 😀

**Comment by juliushaertl** [comment] 2018-06-12 09:53
The repair steps should actually be executed after the button is clicked, so I see no reason the file is not available at that state.

@splitt3r I assume you have a dev env for Nextcloud, can you reproduce the issue locally? YOu can trigger the update page by bumping the last integer value of `$OC_version` in version.php.

**Comment by splitt3r** [comment] 2018-06-12 10:20
Yes i will try to reproduce it and give further information.

**Comment by splitt3r** [comment] 2018-06-22 17:27
Raising the version number shows the upgrade page without any problems.

**Comment by MorrisJobke** [comment] 2018-06-25 09:20
> Raising the version number shows the upgrade page without any problems.

Okay - then let's close this for now and reopen once it happens again and we can look at the exact files and why it happens then.

**Closed by MorrisJobke** 2018-06-25 09:20 UTC
Labels: bug, feature: install and update
