### ISSUE TITLE
Cannot set user quota with uneven values using locales that use a comma as decimal separator

### ISSUE THREAD

**Issue by Anthrazz** [nextcloud/server#18468] opened 2019-12-18 12:34 UTC
It is not possible to set a decimal user quota with a German locale. The frontend does change the wanted value of e.g "1.5 TB" in the API request to "1,5 TB" which is not correctly interpreted by the backend but still accepted and returns a 200 OK message.

If you try to set "1,5 TB" then is the API request not even sent.

There is no problem if the English locale is activated for the user and it is tried to set "1.5 TB".

### Steps to reproduce
1. Go to User Overview
2. Try to set a Quota of "1.5 TB" for a user

### Expected behaviour
User gets a quota of 1.5 TB quota.

### Actual behaviour
Frontend shows "Unlimited" quota and after reload of the page "1 TB".

### Server configuration

**Operating system:** Ubuntu Server 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** PHP 7.3.11

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from Nextcloud version 16

**Where did you install Nextcloud from:** Public Nextcloud Docker Image

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chromium and Firefox

**Operating system:** Fedora

#### Web server error log
<details>
<summary>Web server error log</summary>
No errors
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
No errors
</details>

#### Browser log
<details>
<summary>Browser log</summary>

##### Client Request:
Path: `example.org/ocs/v2.php/cloud/users/Admin`
Payload: `{key: "quota", value: "1,5 TB"}`

##### Answer:
```json
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":[]}}
```
</details>

**Comment by rubo77** [comment] 2019-12-22 09:26
Confirmed.

There is a workaround for value below 1 GB though: instead of 0.5 GB use 500 MB

**Comment by Anthrazz** [comment] 2020-01-03 10:33
> Did you try this?
> occ user:setting USERNAME files quota "1.5 GB"

This workaround does set the quota correct to `1.5 GB`.

**Comment by medcloud** [comment] 2020-04-23 14:34
Hello, I confirm I reproduce also on **French local also** > same issue.
The workaround works for setting quota below 1 GB (ex : 750 MB)
But no solution above 1 GB > 1,5 GB impossible, neither 1500 MB... must be setted 1 GB or 2 GB

**Comment by szaimen** [comment] 2021-05-31 13:18
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by Anthrazz** [comment] 2021-06-01 05:57
I can still reproduce this issue with a Nextcloud 20.0.9.

**Comment by go2sh** [comment] 2021-06-01 09:08
I can reproduce it as well. Will have a look.

**Comment by go2sh** [comment] 2021-06-01 09:51
Two things happen:
- It looks like none of the javascript parsing code can handle "," as decimal seperator and validation will fail
- The php code takes a string of "1,5 GB" and converts it to float as "1.0" 🙈 
- formatFileSize returns a locale dependend file size

Server and javascript code should handle both decimal seperators or it should be clear, that only frontend numbers use the locale dependend decimal seperator. @skjnldsv Any preference?

**Comment by skjnldsv** [comment] 2021-06-01 12:11
> @skjnldsv Any preference?

The more versatile the better

**Comment by RedFoxPi** [comment] 2021-09-01 20:26
https://github.com/nextcloud/server/issues/24002 is a duplicate of this issue and it still exists with 22.1.1.
I am using firefox and US local - though my user local was configured in nextcloud to German.

Workaround which worked for me: Set local in nextcloud user settings to US and then enter e.g. "1.5 TB" worked.

**Comment by GAS85** [comment] 2021-09-20 08:43
> Did you try this?
> 
> ```
>  occ user:setting USERNAME files quota "1.5 GB"
> ```

Somehow didn't work, but this works instead:

```bash
occ user:setting USERNAME files quota 1.5GB
```

**Comment by rubo77** [comment] 2022-10-04 08:09
This is still a valid bug in NC 24.0.5

**Comment by rubo77** [comment] 2022-10-04 08:39
If you point me to the PHP file, that computers the value, I could create a pr

**Comment by szaimen** [comment] 2023-01-09 15:47
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by GAS85** [comment] 2023-01-20 09:24
Nextcloud 24.0.9 set via UI:
- `1,5 GB` does not work
- `1.5 GB` was accepted, but in UI I see now "Unlimited", because of PUT Request did't deliver any data:
```json
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":[]}}
```
After page renewal Limit was back to the `1 GB` - initial = does not work too.

Check via CLI:
```bash
occ user:setting USER
...
  - files:
    - quota: 1 GB
...
```
Quota was not set.

**Comment by szaimen** [comment] 2023-05-22 09:34
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by rubo77** [comment] 2023-09-03 19:10
the problem got worse in 27.0.2:

Now with german Locale, you still cannot set it to broken values, but there is another issue now:

All users seem to have some extra fraction: Users that had 1GB Quota now all have 1.1 GB Quota, users that had 10GB now have 10.7GB. This is the same with english Locale. there the fractioning setting works kind of, although there is also added a few fractions each time, you change it

**Closed** 2023-12-07 13:21 UTC
Labels: bug, 0. Needs triage, feature: occ, 27-feedback
