### ISSUE TITLE
Files-external - check-code not compliant

### ISSUE THREAD

**Issue by nscheuner** [nextcloud/server#12680] opened 2018-11-27 11:12 UTC
Hello,
I'm running nextcloud on a CentOS 7 server, having the issue with latest v.13 , v. 14.0.3 and 14.04, PHP 7.0.32 and now PHP 7.2.12
Files_external gives --> Exception: HMAC does not match.
Topic is also open on NC community:
[](https://help.nextcloud.com/t/external-storage-configuration-page-crashes/24982/6)
OCC check-code shouts also error for the app, it's fresh files_external got from 14.04 update
```
Analysing /var/www/cissync/apps/files_external/list.php
 2 errors
    line   24: OCP\User - Static method of deprecated class must not be called
    line   24: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Analysing /var/www/cissync/apps/files_external/ajax/applicable.php
 4 errors
    line   24: OC_JSON - Static method of deprecated class must not be called
    line   25: OC_JSON - Static method of deprecated class must not be called
    line   27: OC_JSON - Static method of deprecated class must not be called
    line   54: OC_JSON - Static method of deprecated class must not be called
Analysing /var/www/cissync/apps/files_external/ajax/oauth2.php
 3 errors
    line   25: OC_JSON - Static method of deprecated class must not be called
    line   26: OC_JSON - Static method of deprecated class must not be called
    line   27: OC_JSON - Static method of deprecated class must not be called
Analysing /var/www/cissync/apps/files_external/lib/config.php
 2 errors
    line  232: OCP\User - Static method of deprecated class must not be called
    line  232: OCP\User::getUser - Method of deprecated class must not be called
Analysing /var/www/cissync/apps/files_external/lib/Lib/Storage/SMB.php
 1 errors
    line  566: OC_Helper - Static method of private class must not be called
Analysing /var/www/cissync/apps/files_external/lib/Lib/Storage/SFTP.php
 2 errors
    line  214: OCP\Files - Static method of deprecated class must not be called
    line  214: OCP\Files::getStorage - Method of deprecated class must not be called
App is not compliant
```

Don't know where to search, if it's a datable issues?

**Comment by ChristophWurst** [comment] 2018-11-29 22:34
> Files_external gives --> Exception: HMAC does not match.

Did you restore a backup or old instance?

Anyway, please fill out the full [issue template](https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE.md). Thanks!

**Comment by MorrisJobke** [comment] 2019-03-25 12:39
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-03-25 12:39 UTC
Labels: bug, feature: external storage, needs info

**Comment by WaaromZoMoeilijk** [comment] 2021-09-15 19:18
> > Files_external gives --> Exception: HMAC does not match.
> 
> Did you restore a backup or old instance?
> 
> Anyway, please fill out the full [issue template](https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE.md). Thanks!

I have this on a restored backup on a new server, your specific question makes me believe you know more about this? :P 
I will open a current issue but it would be nice if you have a possible fix for a restore.

Thanks
