### ISSUE TITLE
Versioning Collabora Office

### ISSUE THREAD

**Issue by timbim15** [nextcloud/server#3900] opened 2017-03-17 13:07 UTC
We have no versioning when we use online Collabora Office. Versioning generally work.
We have Nextcloud 11.0.2 on  Ubuntu 16.04 with docker collabora Image

**Comment by LukasReschke** [comment] 2017-03-17 14:25
Duplicate of https://github.com/nextcloud/richdocuments/pull/27

**Closed by LukasReschke** 2017-03-17 14:25 UTC
