### ISSUE TITLE
9.1.3.1h/9.1 Modal dialog "User Management Setting": The input field "Default quota" has a visual label. However, this label has been overridden by the use of the "aria-label" attribute, resulting in incorrect screen reader output, which is "Search for options."  A similar issue also affects the combo boxes in the table, which also use the "aria-label" attribute with the value "Search for options."

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42213] opened 2023-12-13 13:34 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-fa5c8d46f9-v9-n1

9.1.3.1h/9.1 Modal dialog "User Management Setting": The input field "Default quota" has a visual label. However, this label has been overridden by the use of the "aria-label" attribute, resulting in incorrect screen reader output, which is "Search for options."  A similar issue also affects the combo boxes in the table, which also use the "aria-label" attribute with the value "Search for options."

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:14
duplicate of https://github.com/nextcloud/server/issues/41838

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:17
duplicate of https://github.com/nextcloud/server/issues/41838

**Closed by JuliaKirschenheuter** 2023-12-14 10:17 UTC
Labels: accessibility
