### ISSUE TITLE
New tabs opened by right click on app icon do not load

### ISSUE THREAD

**Issue by godfuture** [nextcloud/server#20327] opened 2020-04-06 09:58 UTC
If I right click on an app icon and open it in new tab, the new tab does not load the page. All I get is the browser showing the URL and white page with no processing going on. Unfortunately this does not happen with all apps, and sometimes the second attempt to open new tab works.

Strg + left click always works!

NC 18.0.3
Firefox 74.0.1
Win10 x64 (latest update)

**Comment by szaimen** [comment] 2021-06-08 11:16
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-08 11:16 UTC
Labels: 0. Needs triage
