### ISSUE TITLE
File cache error when uploading over desktop client

### ISSUE THREAD

**Issue by Niclas-sol** [nextcloud/server#22835] opened 2020-09-13 14:16 UTC
### Steps to reproduce
Create some data i.e. photos from Lightroom
Save them in your Nextcloud folder and organize it with subfolders

### Expected behaviour
Instant sync of all photos and data

### Actual behaviour
Fatal error from caching? or mysql

## Server configuration detail

**Operating system:** Linux 5.4.41-1-pve #1 SMP PVE 5.4.41-1 (Fri, 15 May 2020 15:06:08 +0200) x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.4.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 19.0.3 - 19.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Web archive

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - apporder: 0.11.0
 - bruteforcesettings: 2.0.1
 - camerarawpreviews: 0.7.8
 - cloud_federation_api: 1.2.0
 - dav: 1.15.0
 - documentserver_community: 0.1.7
 - external: 3.6.0
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_accesscontrol: 1.9.1
 - files_downloadactivity: 1.8.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - maps: 0.1.6
 - music: 0.16.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - occweb: 0.0.7
 - onlyoffice: 5.0.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - support: 1.2.1
 - survey_client: 1.7.0
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - accessibility
 - calendar
 - comments
 - contactsinteraction
 - deck
 - encryption
 - files_external
 - firstrunwizard
 - nextcloud_announcements
 - sharebymail
 - spreed
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "removed",
        "removed",
        "removed"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "tempdirectory": "\/var\/www\/html\/nextcloud\/data\/tmp",
    "dbtype": "mysql",
    "version": "19.0.3.1",
    "overwrite.cli.url": "removed,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "default_language": "de",
    "force_locale": "de_DE",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "app_install_overwrite": [
        "files_reader",
        "occweb",
        "files_external_gdrive"
    ],
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\HEIC",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "quota_include_external_storage": true,
    "theme": "",
    "loglevel": 2,
    "mail_smtpsecure": "tls",
    "data-fingerprint": "38cf46f187e9cbed0904ced4e800492d"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
From Nginx error.log

2020/09/13 14:01:15 [error] 2041#2041: *28582 access forbidden by rule, client: 79.242.54.234, server: *removed*, request: "GET /data/.ocdata?t=1600005675187 HTTP/2.0", host: "*removed*"
```
</details>

<details><summary>Nextcloud log</summary>

```
[webdav] Fatal: Doctrine\DBAL\Exception\DeadlockException: An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = GREATEST(`mtime`, ?), `etag` = ? WHERE (`storage` = ?) AND (`path_hash` IN ('d41d8cd98f00b204e9800998ecf8427e', '45b963397aa40d4a0063e0d85e4fe7a1', '972a71d1680f779b18a1a21c95b367ab', 'bcca000a5042ab492700aac02a6c9f23', 'bac31d9c9df9fc6098cdc348a11ab29b', '0feed60b30c880bfbf461eab046dae31'))' with params [1600005563, "5f5e25bbcfc92", 1]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at <<closure>>

 0. /var/www/html/*removed*/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... n", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/*removed*/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... n")
 2. /var/www/html/*removed*/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "UPDATE `oc_file ... )", {1: 1600005563,2: "5f5e25bbcfc92",3: 1})
 3. /var/www/html/*removed*/nextcloud/lib/private/DB/Connection.php line 214
    Doctrine\DBAL\Connection->executeUpdate("UPDATE `oc_file ... )", [1600005563,"5f5e25bbcfc92",1], [1,2,1])
 4. /var/www/html/*removed*/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 203
    OC\DB\Connection->executeUpdate("UPDATE `oc_file ... )", {dcValue1: 16000 ... 1}, {dcValue1: 1,dcValue2: 2,dcValue3: 1})
 5. /var/www/html/*removed*/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 216
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/*removed*/nextcloud/lib/private/Files/Cache/Propagator.php line 101
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/*removed*/nextcloud/lib/private/Files/Cache/HomePropagator.php line 49
    OC\Files\Cache\Propagator->propagateChange("files/02 Privat ... G", 1600005563, 0)
 8. /var/www/html/*removed*/nextcloud/lib/private/Files/Cache/Updater.php line 166
    OC\Files\Cache\HomePropagator->propagateChange("files/02 Privat ... G", 1600005563)
 9. /var/www/html/*removed*/nextcloud/lib/private/Files/View.php line 329
    OC\Files\Cache\Updater->remove("files/02 Privat ... G")
10. /var/www/html/*removed*/nextcloud/lib/private/Files/View.php line 1173
    OC\Files\View->removeUpdate(OCA\FilesAccessC ... }}, "files/02 Privat ... G")
11. /var/www/html/*removed*/nextcloud/lib/private/Files/View.php line 718
    OC\Files\View->basicOperation("unlink", "/02 Privatleben ... G", ["delete"])
12. /var/www/html/*removed*/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 458
    OC\Files\View->unlink("/02 Privat ... G")
13. /var/www/html/*removed*/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 183
    OCA\DAV\Connector\Sabre\File->delete()
14. /var/www/html/*removed*/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 295
    Sabre\DAV\Tree->delete("files/Niclas/02 ... G")
15. /var/www/html/*removed*/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
16. /var/www/html/*removed*/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:DELETE", [Sabre\HTTP\Requ ... }])
17. /var/www/html/*removed*/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
18. /var/www/html/*removed*/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
19. /var/www/html/*removed*/nextcloud/apps/dav/lib/Server.php line 320
    Sabre\DAV\Server->exec()
20. /var/www/html/*removed*/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
21. /var/www/html/*removed*/nextcloud/remote.php line 167
    require_once("/var/www/html/s ... p")

DELETE /remote.php/dav/files/Niclas/*removed*/IMG_8755.JPG
from 79.242.54.234 by Niclas at 2020-09-13T13:59:23+00:00
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by go2sh** [comment] 2020-09-13 16:14
Looks like a duplicate of #22482.

**Comment by acsfer** [comment] 2020-09-14 16:19
@Niclas-sol follow #22482. Thanks.

**Closed by acsfer** 2020-09-14 16:19 UTC
Labels: 0. Needs triage, bug
