### ISSUE TITLE
Quotas for groups (Individually)

### ISSUE THREAD

**Issue by Tomoli75** [nextcloud/server#7830] opened 2018-01-12 18:09 UTC
I want to be able to add people to a group, and have their personal quota set whilst they are in the group.

Possible via app or core, i don't know, but couldn't find anything that lets me do that.

**Comment by tflidd** [comment] 2018-01-13 15:34
Can you specify? Do you mean that users of a group have a common total quota:
https://github.com/nextcloud/server/issues/4275

Or do you just want to set default quotas for users depending on the group?

**Comment by MorrisJobke** [comment] 2018-04-05 07:34
Closing as duplicate of #4275

**Closed by MorrisJobke** 2018-04-05 07:34 UTC
Labels: enhancement, feature: users and groups, needs info
