### ISSUE TITLE
Please check CHMOD 0770 with a new installation

### ISSUE THREAD

**Issue by GentleRV** [nextcloud/server#19226] opened 2020-01-31 06:04 UTC
Sorry to repeat this error, see the bug report I wrote earlier but got no answers on it and nobody is assigned to solve this 

Thanks for helping me out.

**Comment by kesselb** [comment] 2020-01-31 07:01
Closing as duplicate of https://github.com/nextcloud/server/issues/18951

**Closed by kesselb** 2020-01-31 07:01 UTC
Labels: 0. Needs triage, bug

**Comment by GentleRV** [comment] 2020-03-16 12:57
Hi Kesselb,

Please explain to me why the error 0770 still exist in the latest version,
or how to solve the problem for so I can use, on my own risk, the samba
link to the shared folder on my local system.

With friendly regards
Ronald

**Comment by kesselb** [comment] 2020-03-16 14:42
The answer to your question is part of the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md): 


> Nextcloud is an open source project backed by Nextcloud GmbH. Most of our volunteers are home users and thus primarily care about issues that affect home users. Our paid engineers prioritize issues of our customers. If you are neither a home user nor a customer, consider paying somebody to fix your issue, do it yourself or become a customer.

I closed this issue because it's a duplicate of the other issue you created. Getting no answer is no reason to create a second issue.

**Comment by GentleRV** [comment] 2020-03-17 03:54
Thanks for the explanation.

I am home user too, with my own server in Holland.
I understand the way it is handled.
Being only a hardware guy is it difficult to do the program work.

I will find a solution or wait until the problem is solved, not only for me
but for many as seen on the internet.
This problem is mentioned in all previous releases and never handled.

Thanks again for the answer.
