### ISSUE TITLE
File picker interface broken

### ISSUE THREAD

**Issue by pschopen** [nextcloud/server#40637] opened 2023-09-26 10:28 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![grafik](https://github.com/nextcloud/server/assets/65334274/8a7b9cc0-2848-494b-a42c-4f34d2519640)

This is how the file picker looks on NC 27.1 when trying to attach a file in deck. I guess that's not a deck issue?

### Steps to reproduce

Update every app to the newest available version

### Expected behavior

Everything like in the mockup

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment] 2023-09-26 14:44
Duplicate of https://github.com/nextcloud/server/issues/40580

Already fixed and will be released with 27.1.2

**Closed by susnux** 2023-09-26 14:44 UTC
Labels: bug, 0. Needs triage, 27-feedback
