### ISSUE TITLE
Left sidebar in settings/apps and settings/user not usable on mobile

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/server#14732] opened 2019-03-17 21:18 UTC
### Steps to reproduce
1. Open `/index.php/settings/apps` or `/index.php/settings/users` in your browser
2. Reduce browser width to <= 768px or use a mobile device
3. Try to use the left sidebar (swiping does not work and there is no toggle button)

### Expected behaviour
Sidebar should be usable via swiping. Also there should definitely be a toggle button in the top left corner like on other apps

### Actual behaviour
Swiping does nothing, toggle button is not there

### Server configuration

**Operating system**: Some linux

**Web server:** Apache 

**Database:** MySQL

**PHP version:** 7.2.12

**Nextcloud version:** 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Used .zip-package from nextcloud.org

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox 60 (on desktop) and latest Firefox on mobile, latest Chrome on mobile

**Operating system:** LMDE

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
@babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
ncvuecomponents.js:33:58705
New search handler registered
search.js:67:4
New search handler registered
```
</details>

Confirmed by @desperateCoder

**Comment by MorrisJobke** [comment] 2019-03-25 09:26
Duplicate of #14252

**Closed by MorrisJobke** 2019-03-25 09:26 UTC
Labels: 0. Needs triage, bug
