### ISSUE TITLE
[Bug]: [jsresourceloader] Fehler: Could not find resource files_pdfviewer/js/files_pdfviewer-main.js

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/server#49131] opened 2024-11-07 16:11 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Using the files app the following error is thrown:
[jsresourceloader] Fehler: Could not find resource files_pdfviewer/js/files_pdfviewer-main.js to load 	GET /apps/files/
Additionally I can't open pdf docs anymore.
And yes the mentioned file is missing.

### Steps to reproduce

1. upgraded nextcloud server from 29.0.8 to 29.0.9

### Expected behavior

No error is thrown and pdf docs can be opened.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mritzmann** [comment] 2024-11-07 17:50
Duplicate of https://github.com/nextcloud/files_pdfviewer/issues/1080

(But maybe the bug is better placed in this repo, I don't know.)

**Comment by solracsf** [comment] 2024-11-07 20:43
Closing as duplicate of https://github.com/nextcloud/files_pdfviewer/issues/1080
Let's following it there 👍

**Closed by solracsf** 2024-11-07 20:43 UTC
Labels: bug, 0. Needs triage, 29-feedback
