### ISSUE TITLE
20.0.2RC2, message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead."

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/server#24176] opened 2020-11-17 10:07 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to 20.0.2RC2
2.
3.

### Actual behaviour
log is flooded by messages as follows for all apps:
message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead."

### Server configuration

**Operating system:**
Ubuntu18.04

**Web server:**
apache-2.4.46

**Database:**
mariadb-10.4.17

**PHP version:**
php-7.4.12

**Nextcloud version:** (see Nextcloud admin page)
20.0.2RC2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.2RC1

**Comment by kesselb** [comment] 2020-11-17 12:05
Duplicate of https://github.com/nextcloud/server/issues/23046

**Closed by kesselb** 2020-11-17 12:05 UTC
Labels: 0. Needs triage, bug
