### ISSUE TITLE
LDAP admin group mapping

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#4635] opened 2017-05-01 19:39 UTC
Hello,

it seems like it's not possible yet to make an LDAP group part of the Nextcloud admin group. I think this would be a valid feature.

At the moment, all LDAP users who should be Nextcloud admins need to be added to the local Nextcloud group 'admin' manually. Instead, it should be possible to define an LDAP group as an extension to the Nextcloud admin group. In other words, all members of this LDAP group should automatically be regarded as admins by Nextcloud.

I don't think that replacing the local admin group by a LDAP group would be a good idea, as it would cause severe issues in case of broken LDAP setups.

See the [ownCloud issue #3577](https://github.com/owncloud/core/issues/3577) for more information. Unfortunately, it was closed recently.

**Comment by MorrisJobke** [comment] 2017-07-18 22:45
Duplicate of #3877

**Closed by MorrisJobke** 2017-07-18 22:45 UTC
