### ISSUE TITLE
[Bug]: Nextcloud 28.0.2 File Sharing App doesnt refresh after sharing Data

### ISSUE THREAD

**Issue by Deni987** [nextcloud/server#43356] opened 2024-02-05 13:35 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If i try to share a data or directory the website wont refresh. It doesnt show a Button to copy a URL/Link. It shows the URL only if i close the menu and open it again.
![Screenshot 2024-02-05 142326](https://github.com/nextcloud/server/assets/159030822/040fc28d-b9ce-40d3-b644-cec9efa74422)
![Screenshot 2024-02-05 142408](https://github.com/nextcloud/server/assets/159030822/6634ab52-7b8c-4290-ad59-bb4288dc8b3d)

### Steps to reproduce

1. Open the Share Menu
2. Click + to create a new URL
3. Sett the properties and accept

### Expected behavior

After sharing a file the menu should refresh itself. Worked on NC25.0.8 and other Versions. 

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_antivirus: 5.4.1
  - files_external: 1.20.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - guests: 3.0.1
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - suspicious_login: 6.0.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
```

### Additional info

Is this issue known or is there a fix already? It worked flawless on NC25 and now it doesnt.

**Comment by cearap01** [comment] 2024-02-05 15:30
same issue here since upgrade to 28.0.2 over the weekend users cannot share files.

App: File Sharing 1.20.0 - no response

**Comment by cearap01** [comment] 2024-02-05 19:28
just to confirm - the sharing does not work at all and the UI is not refreshing accordingly

**Comment by cearap01** [comment] 2024-02-05 20:13
> just to confirm - the sharing does not work at all and the UI is not refreshing accordingly

15h11 found the issue ... missing php module raphf - updated and ran sudo -u www-data php occ maintenance:repair

Sharing is now working again

**Comment by joshtrichards** [comment] 2024-02-05 21:55
@Deni987 & @muelli  I can't reproduce this, but I'm also confused because the screenshots aren't v28. Are they screenshots of what you're seeing in v28 or what you see in your older environment?

@cearap01:

> just to confirm - the sharing does not work at all and the UI is not refreshing accordingly

Your situation sounds different than the original reporter's.

> 15h11 found the issue ... missing php module raphf - updated and ran sudo -u www-data php occ maintenance:repair

Not sure what environment you're in, but that doesn't sound quite right. Maybe you were missing something else - like curl - and installing raphf added that due to a package dependency or something? If you were missing curl you would indeed have problems. But we do not have a dependency on raphf.

**Comment by cearap01** [comment] 2024-02-05 22:01
> @Deni987 & @muelli I can't reproduce this, but I'm also confused because the screenshots aren't v28. Are they screenshots of what you're seeing in v28 or what you see in your older environment?
> 
> @cearap01:
> 
> > just to confirm - the sharing does not work at all and the UI is not refreshing accordingly
> 
> Your situation sounds different than the original reporter's.
> 
> > 15h11 found the issue ... missing php module raphf - updated and ran sudo -u www-data php occ maintenance:repair
> 
> Not sure what environment you're in, but that doesn't sound quite right. Maybe you were missing something else - like curl - and installing raphf added that due to a package dependency or something? If you were missing curl you would indeed have problems. But we do not have a dependency on raphf.

---
Not sure but 'curl' was already installed - I checked all the modules and everything was there - when I ran 'repair' it told me i was missing 'raphf' - once I installed 'raphf' and ran repair again - the problem resolved itself.

I must have missed that message when I ran repair over the weekend.

This is on a Debian 12 server running Nextcloud Hub 7 (28.0.2)

**Comment by joshtrichards** [comment] 2024-02-05 22:19
@cearap01 Well it's not from us. :-) We don't have any references to it anywhere and it's not even installed on any of my test or production instances. Including Debian 12. Was the message maybe something like the below:

> `PHP Warning: Cannot load module "http" because required module "raphf" is not loaded in Unknown on line 0`

If so it was because of the `http` module being installed and we also don't use that.

Either way, glad you got it figured out, but pretty confident it's unrelated to this bug report.

**Comment by cearap01** [comment] 2024-02-05 22:22
> @cearap01 Well it's not from us. :-) We don't have any references to it anywhere and it's not even installed on any of my test or production instances. Including Debian 12. Was the message maybe something like the below:
> 
> > `PHP Warning: Cannot load module "http" because required module "raphf" is not loaded in Unknown on line 0`
> 
> If so it was because of the `http` module being installed and we also don't use that. :)
> 
> Either way, glad you got it figured out, but pretty confident it's unrelated to this bug report.

Thank you anyway

Guess when I searched for the issue it seemed to be a similar issue [big shrugs]

Have a good one!

**Comment by mrbupu** [comment] 2024-02-06 02:20
I think this issue is duplcicate with 
https://github.com/nextcloud/server/issues/43224

**Comment by skjnldsv** [comment] 2024-02-06 09:31
Duplicate of https://github.com/nextcloud/server/issues/41725

**Closed by skjnldsv** 2024-02-06 09:31 UTC
Labels: bug, needs info, feature: sharing, 0. Needs triage, feature: files, 28-feedback
