### ISSUE TITLE
Antivirus Error (NC11)

### ISSUE THREAD

**Issue by tx7** [nextcloud/server#2717] opened 2016-12-16 13:27 UTC
Hi,

I just updated my NC11 from NC10.0.2, and the antivirus giving me this error.
I tried many searches on the web, but no solution can be found.
I had tried the NC10-stable.zip and the files-antivirus-master.zip; same issue.

Server's Info:
Debian Jessie
PHP 5.6
MySQL 5.5
Nginx

`Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - audioplayer: 1.3.1
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_antivirus
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - folderplayer: 0.0.7
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - documents
  - encryption
  - files_automatedtagging
  - spreedme
  - survey_client
  - user_external
  - user_ldap
  - user_saml`

`Error	files_antivirus	OCA\Files_Antivirus\BackgroundScanner::run, exception: File with id "6" has not been found`

**Comment by MariusBluem** [comment] 2016-12-16 15:54
Could you please use our issue template (https://github.com/nextcloud/server/blob/master/issue_template.md) in the future 👊 THX!

**Comment by NiTRoeSE** [comment] 2016-12-17 10:32
Steps to reproduce

```
1. Install NC 11
2. Download the nextcloud files_antivirus app, chown -R webserveruser:webserveruser /path/to/your/instanz/apps/files_antivirus
3. Activate the app in your admin panel
4. Configure the app in daemon socket mode

```

Expected behaviour
`
Expecting that antivirus app works correct when a user are uploading some files so that these files are scanned for viruses.
`
Actual behaviour

`Scan for fresh uploaded files works fine, but the background job throws some errors in the log files .`

Server configuration

Operating system:
`CentOS 7 x64`
Web server:
`Server version: Apache/2.4.6`

Database:
`MariaDB 5.5.52`

PHP version:
`7.0.14`
Nextcloud version: (see Nextcloud admin page)
`11.0`
Updated from an older Nextcloud/ownCloud or fresh install:
`Updated from NC 10.0.2`
Where did you install Nextcloud from:
`Built in updater app`
Signing status:

Signing status

List of activated apps:


` 
- activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - audioplayer: 1.4.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_antivirus: 1.0.0.0
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreedme: 0.3.5
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
`

The content of config/config.php:
```

 "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***"",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"",
            "***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "\/clouddata",
        "overwrite.cli.url": "https://***REMOVED SENSITIVE VALUE***"",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***"",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "127.0.0.1",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "theme": "nitro",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "log_type": "owncloud",
        "logfile": "\/clouddata\/owncloud.log",
        "log_authfailip": true,
        "log_query": false,
        "log_rotate_size": 52428800,
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable"
```

Are you using external storage, if yes which one: local/smb/sftp/...

`no`

Are you using encryption: yes/no

`no`

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

`no`


Browser:
`Safari 10.0.2`

Operating system:
`OSX 10.12.1`

Logs


Nextcloud log (data/nextcloud.log)

`{"reqId":"G\/xAYp1E37ugkXsdmbcB","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"17285\" has not been found.","level":3,"time":"2016-12-17T00:00:07+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"3yyGxPa0VCAaq\/ACcP8q","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T01:00:01+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"DwvaS0YZy9hQiFQ9qnA2","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T01:15:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"sbcvkF56A5u+SetL0XJZ","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T01:30:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"fWJHGOPypNDjkF9EjPcM","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T02:00:05+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"WiWVXqrQ41+7OE2R8r9F","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T02:30:05+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"JVT0\/pogj8cP1BXrxBxv","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T03:00:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"yzYLteU0HXOAiiYWiFaE","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T03:30:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"7W7+F7BauD+JowaPht58","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T04:00:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"3UFwP4CqMgJkqs32Dw+3","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T04:30:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"\/\/peYoFsGpdMBVnKQDCk","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T05:00:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"jpVkewyL+k0ZdP7WDHFa","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T05:30:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"F\/EWkqcUYyOSKBR2E7+L","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T06:00:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"kPqSPuUkVLtvSUpT3fQP","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T06:30:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"qmA8xkz46vBC0r83aNV2","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T07:00:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"CDPZIkC2RzchtK6CWw38","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T07:30:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"48Ktnb4DkbJi07NxvfDe","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T08:00:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"tOmjTCkFsfIKLQl8fX4o","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T08:30:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"KOJN2ditwMyhplOD95a3","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T09:00:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"LUey1NFvo1UxBlMnZpLZ","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T09:30:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"vZogjANR7KgoIzgmXx70","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T09:45:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"zOvht1qZgoV8m4V8xIVF","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T10:15:02+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"3bdQhcN7KRa405OCVHds","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T10:30:03+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"Zlhk\/vYSKXYuBBwRxihO","remoteAddr":"","app":"files_antivirus","message":"OCA\\Files_Antivirus\\BackgroundScanner::run, exception: File with id \"513\" has not been found.","level":3,"time":"2016-12-17T11:00:04+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
`
Browser log

`empty`

**Comment by nickvergessen** [comment] 2016-12-19 14:16
Duplicate of https://github.com/nextcloud/files_antivirus/issues/12

**Closed by nickvergessen** 2016-12-19 14:16 UTC
