### ISSUE TITLE
[Bug]: Switching between files breaks tags input field

### ISSUE THREAD

**Issue by Io-Qo** [nextcloud/server#41503] opened 2023-11-15 14:29 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When viewing a PDF file with the pdf viewer I can open the sidebar and assign a tag. When I then close the pdf viewer (sidebar stays open) and then switch to another pdf file it's not possible to assign tags to the newly opened file (input stays inactive, cannot be focused but assigned tags can be removed). 

### Steps to reproduce

1. open a PDF file (pdf viewer)
2. open sidebar and assign tag
3. close pdf file (sidebar stays open)
4. open another PDF file
5. assigning tags is not possible

### Expected behavior

Should be possible to assign tags when changing the file.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - announcementcenter: 6.6.2
  - approval: 1.1.0
  - bookmarks: 13.1.1
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.3
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.1
  - files_antivirus: 5.3.0
  - files_archive: 1.1.3
  - files_automatedtagging: 1.17.0
  - files_external: 1.19.0
  - files_fulltextsearch: 27.0.1
  - files_fulltextsearch_tesseract: 27.0.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_scripts: 3.0.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - flow_notifications: 1.7.0
  - fulltextsearch: 27.0.2
  - fulltextsearch_elasticsearch: 27.0.4
  - groupfolders: 15.3.1
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.4
  - news: 24.0.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - oidc_login: 2.6.0
  - password_policy: 1.17.0
  - passwords: 2023.10.30
  - polls: 5.4.1
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.2
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - snappymail: 2.29.1
  - spreed: 17.1.2
  - support: 1.10.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - timetracker: 0.0.80
  - twofactor_admin: 4.3.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.2.0
  - unroundedcorners: 1.1.2
  - updatenotification: 1.17.0
  - user_saml: 5.2.4
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflow_ocr: 1.27.5
  - workflow_pdf_converter: 1.12.0
  - workflow_script: 1.12.0
  - workflowengine: 2.9.0
```

**Comment by solracsf** [comment] 2023-12-08 23:14
I've tried to reproduce this but I couldn't.
A screencast could help.

**Comment by skjnldsv** [comment] 2024-06-11 09:26
Same

**Comment by skjnldsv** [comment] 2024-06-11 09:26
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-06-11 09:26 UTC
Labels: bug, 0. Needs triage, 27-feedback
