### ISSUE TITLE
Feature-Policy has been renamed to Permissions Policy

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/server#23228] opened 2020-10-06 12:41 UTC
NC sets
`Feature-Policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'`

Because `Feature-Policy` has been renamed to `Permissions-Policy` I suggest to use that also in NC

`Permissions-Policy: autoplay=(self); camera=(none); fullscreen=(self); geolocation=(none); microphone=(none); payment=(none)`

If someone points out where to change that in the code, I can bring in a PR.

**Comment by kesselb** [comment] 2020-10-06 15:53
Duplicate of https://github.com/nextcloud/server/issues/22792

**Closed by kesselb** 2020-10-06 15:53 UTC
Labels: 0. Needs triage, enhancement
