### ISSUE TITLE
share link settings of folder are reset when adding an extra share link or changing another share link

### ISSUE THREAD

**Issue by alexbijma** [nextcloud/server#20488] opened 2020-04-14 20:01 UTC
### Steps to reproduce
1. add 1 share link to a folder
2. share link is set to readonly by default, keep this
3. add a 2nd share link to the same folder
4. set 2nd share link to allow upload and edit
5. now the 1st share link settings are reset(all gone)
6. set 1st share link again to readonly
7. now the 2nd share link settings are reset
8. this goes on and on each time you change the settings of the share links

### Expected behaviour
share links should have each it's own individual settings

### Server configuration
this happens in Nextcloud 17.0.2
in Nextcloud 18 it's working as expected!! so it seems to be fixed in Nextcloud 18 already

it only happens on web, the apps are working fine

**Comment by szaimen** [comment] 2021-06-07 17:25
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 17:25 UTC
Labels: 0. Needs triage, bug
