### ISSUE TITLE
iOS breaks BDAY in Contacts

### ISSUE THREAD

**Issue by loeffelpan** [nextcloud/server#16086] opened 2019-06-26 06:22 UTC
### Steps to reproduce
1. Import some VCARD with birthday working for Apple **and** Nextcloud
Example:
BEGIN:VCARD
VERSION:3.0
FN:John Doe
N:Doe;John;;;
TEL;TYPE=CELL:0123456789
BDAY;X-APPLE-OMID-YEAR=1604:16040626
END:VCARD

2. Modify this VCARD via CardDAV with an iOS device.
3. Exported VCARD looks like this. "VOICE" and "pref" seems to be ok for nextcloud, but birthday without year still not working.
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 12.3.1//EN
N:Doe;John;;;
FN:John Doe
TEL;type=CELL;type=VOICE;type=pref:0160 91396475
BDAY;value=date:1604-06-26
REV:2019-06-26T05:58:35Z
UID:070da8c4-6133-43d5-a88e-00404e913563
END:VCARD

### Expected behaviour
Modified BDAY in VCARD should work with nextcloud.

### Actual behaviour
Nextcloud shows 1604 as birthyear in contact and in birthday calendar.
Shouldn't this be fixed with #11832?

### Server configuration

**Operating system**: Ubuntu Server 19.04

**Web server:** Apache 

**Database:** MySQL

**PHP version:** 7.2 FPM

**Nextcloud version:** (see Nextcloud admin page) 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Not available at the moment.
I can add this, when needed.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Not available at the moment.
I can add this, when needed.
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** card/calDAV for sync with iOS

**Comment by skjnldsv** [comment] 2020-08-25 09:28
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:28 UTC
Labels: 0. Needs triage, bug
