### ISSUE TITLE
Request to bring back number of files selected (Nextcloud 28)

### ISSUE THREAD

**Issue by SayantanRC** [nextcloud/server#43441] opened 2024-02-08 07:14 UTC
On Nextcloud 27.x.x we could see the number of files selected on top.

<img src=https://github.com/nextcloud/server/assets/25128924/85287ca5-bffc-4223-b762-e761c4b7d8cc width=250/>

On Nextcloud 28.0.2, they are replaced with some suggestion.

<img src=https://github.com/nextcloud/server/assets/25128924/b23f64c6-a144-45cd-b781-e7c8cbdde81a width=250/>

Kindly bring back this feature as it is very useful.

**Comment by susnux** [comment] 2024-02-09 00:49
cc @nextcloud/designers

**Comment by szaimen** [comment] 2024-02-09 11:07
Yes, agree that we should show the amount of selected files. @susnux would you need a mockup?

**Comment by susnux** [comment] 2024-02-09 13:01
@szaimen it you have something different in mind than in the initial post (screenshot of 27) then yes. if it should be like 27 then no :)

**Comment by szaimen** [comment] 2024-02-19 11:34
I'd say the 27 variant looks good :)

**Comment by jancborchardt** [comment] 2024-02-28 12:43
Marking it as bug and regression since we had this functionality before. Would indeed be good to bring it back. :)

**Closed** 2024-04-17 23:23 UTC
Labels: bug, 0. Needs triage, feature: files, regression, 28-feedback
