### ISSUE TITLE
Public link exposes full name from profile

### ISSUE THREAD

**Issue by AND51** [nextcloud/server#9972] opened 2018-06-23 15:55 UTC
### Steps to reproduce
1. Fill out your profil under Settings→Personal Info
2. Create a folder
3. Create shared link
4. Open shared link in a new window

### Expected behaviour
Sometimes I use a (write protected) shared link to share a folder with files. I post this shared link on various untrusted websites or places.

When I recently tested such a link in icognito mode, I noticed that my full name is written in the upper left corner: "FOLDER_NAME geteilt von MY_NAME"

I've set visibility of "full name" to "contacts". The description says, "Visible to local users and to trusted servers." However, an anonymous user is not a "local user". My name is even displayed when choosing "local", which states, "Only visible to local users."

I expected that no name is written, just the folder name.

### Actual behaviour

My name is displayed in the upper left corner, no matter which privacy setting is chosen.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from older versions

**Comment by AND51** [comment] 2018-06-23 16:13
@nextcloud-bot From your suggestions, only #6418 (Some content leaks to public from the user profile ) seems to match my issue roughly.

**Comment by MorrisJobke** [comment] 2018-06-25 05:44
This is a duplicate of #9789

See also the answer by Julius: https://github.com/nextcloud/server/issues/9789#issuecomment-396245745

**Closed by MorrisJobke** 2018-06-25 05:44 UTC
Labels: bug, feature: sharing
