### ISSUE TITLE
9.1.3.1e/11.2 When a file is selected, the table changes - the column headers at the top disappear and are replaced by buttons. You get a table with 5 columns but only two column headers. When a data cell in column 2 is focused with the screen reader, the names of all buttons like "Remove from favorites" are read out together as column header. It is recommended to place the buttons outside the table and keep the correct column headers instead of replacing them.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42211] opened 2023-12-13 13:29 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-3f0ff0bc0e-v11-n2

9.1.3.1e/11.2 When a file is selected, the table changes - the column headers at the top disappear and are replaced by buttons. You get a table with 5 columns but only two column headers. When a data cell in column 2 is focused with the screen reader, the names of all buttons like "Remove from favorites" are read out together as column header. It is recommended to place the buttons outside the table and keep the correct column headers instead of replacing them.
![image](https://github.com/nextcloud/server/assets/42591237/77db056c-5d67-46d4-8295-d365329880d2)

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:09
duplicate of https://github.com/nextcloud/server/issues/41834

**Closed by JuliaKirschenheuter** 2023-12-14 10:09 UTC
Labels: accessibility
