### ISSUE TITLE
9.4.1.2/4.4 In the "Save image as" dialog, the combobox for file type selection has not been implemented as such, either with an HTML "select" element or with ARIA roles. You can refer to https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/ for guidance on how to implement it properly.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42234] opened 2023-12-13 14:15 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-bfbf07e5c3-v4-n4

9.4.1.2/4.4 In the "Save image as" dialog, the combobox for file type selection has not been implemented as such, either with an HTML "select" element or with ARIA roles. You can refer to https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/ for guidance on how to implement it properly.

![image](https://github.com/nextcloud/server/assets/42591237/f7d72134-b2c5-43cd-a8dd-c913f4ab43e8)

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:41
duplicate of https://github.com/nextcloud/server/issues/41899

**Closed by JuliaKirschenheuter** 2023-12-14 10:41 UTC
Labels: accessibility
