### ISSUE TITLE
[Bug]: DAV "Unknown error while seeking content" upload error when empty file is synchronized

### ISSUE THREAD

**Issue by adeverteuil** [nextcloud/server#49976] opened 2024-12-27 03:32 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

I was tracking down an "Sabre\DAV\Exception" "Unknown error while seeking content" upload error in my `nextcloudcmd` cron job. I found that the presence of a new **empty** file was causing a sync error. I created the new empty file myself to test the sync, and after noticing consistent failure to sync the test file, I tried a few other things. Creating a **non-empty** file resolved the issue. However, I believe **empty** files should be synchronized without error.

Similar issues found, but I think the root cause is different.
* https://github.com/nextcloud/server/issues/30424
* https://github.com/nextcloud/server/issues/30626

### Steps to reproduce

1. Run `nextcloudcmd` on an existing or a new empty directory.
2. It should finish with a `0` exit code.
3. Create a new **empty** file.
4. Run `nextcloudcmd` again.
5. It should **fail** with a `1` exit code. There should be a bulk upload API call error about "error while seeking content". The file should not be created on the Nextcloud server.
6. Edit the file and write content in it. It should have a >0 bytes size.
7. Run `nextcloudcmd`.
8. It should finish with a `0` exit code.
9. The file should be successfully created on the Nextcloud server.

### Expected behavior

Empty files (0 bytes size) are synced without error.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json
{"reqId":"TrVqI7xE8DL1knVqTuvZ","level":3,"time":"2024-12-27T03:10:47+00:00","remoteAddr":"192.168.21.1","user":"alex","app":"webdav","method":"POST","url":"/remote.php/dav/bulk","message":"Unknown error while seeking content","userAgent":"Mozilla/5.0 (Linux) mirall/3.7.3git (nextcloudcmd, debian-6.6.32-production+truenas ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"30.0.4.1","exception":{"Exception":"Sabre\\DAV\\Exception","Message":"Unknown error while seeking content","Code":500,"Trace":[{"file":"/var/www/html/apps/dav/lib/BulkUpload/MultipartRequestParser.php","line":117,"function":"isAt","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->","args":["--boundary_.oOo._QSiYzC6Iw006wjrL0WNgSITErTHiX67f--\r\n"]},{"file":"/var/www/html/apps/dav/lib/BulkUpload/BulkUploadPlugin.php","line":54,"function":"isAtLastBoundary","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPost","class":"OCA\\DAV\\BulkUpload\\BulkUploadPlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:POST",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Server.php","line":43,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":371,"function":"start","class":"OCA\\DAV\\Connector\\Sabre\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":19,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":146,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/BulkUpload/MultipartRequestParser.php","Line":99,"message":"Unknown error while seeking content","exception":[],"CustomMessage":"Unknown error while seeking content"},"id":"676e1ab9d6228"}
```

### Additional info

Here is what the `nextcloudcmd` logs look like:

```plaintext
11-28 15:23:02:392 [ warning nextcloud.sync.propagator.directory ]:     Useless task found for file "test-new-file-2024-11-28.txt" instruction CSyncEnums::CSYNC_INSTRUCTION_NEW
11-28 15:23:02:392 [ info nextcloud.sync.propagator.root.directory ]:   OCC::SyncFileItem::Success slotSubJobsFinished OCC::PropagatorJob::Running pending uploads 1 subjobs state OCC::PropagatorJob::Finished
11-28 15:23:02:392 [ info nextcloud.sync.propagator ]:  PropagateRootDirectory::scheduleDelayedJobs
11-28 15:23:02:392 [ info nextcloud.sync.checksums ]:   Computing "MD5" checksum of "/home/alex/Deep archive/test-new-file-2024-11-28.txt" in a thread
11-28 15:23:02:419 [ info nextcloud.sync.propagator.bulkupload ]:       "Deep archive/test-new-file-2024-11-28.txt" transmission checksum "d41d8cd98f00b204e9800998ecf8427e" "/home/alex/Deep archive/test-new-file-2024-11-28.txt"
11-28 15:23:02:419 [ info nextcloud.sync.accessmanager ]:       4 "" "https://nextcloud.mydomain.net/remote.php/dav/bulk" has X-Request-ID "2e712463-b293-4d27-bfdc-2b53a88e41a7"
11-28 15:23:02:419 [ info nextcloud.sync.networkjob ]:  OCC::PutMultiFileJob created for "https://nextcloud.mydomain.net" + "" "OCC::BulkPropagatorJob"
11-28 15:23:02:420 [ warning nextcloud.sync.networkjob ]:       QNetworkReply::UnknownNetworkError "Unknown error" QVariant(Invalid)
11-28 15:23:02:420 [ info nextcloud.sync.networkjob.put.multi ]:        POST of "https://nextcloud.mydomain.net/remote.php/dav/bulk" "" FINISHED WITH STATUS "UnknownNetworkError Unknown error" QVariant(Invalid) QVariant(Invalid)
11-28 15:23:02:420 [ info nextcloud.sync.propagator.bulkupload ]:       Item completed "test-new-file-2024-11-28.txt" OCC::SyncFileItem::NormalError CSyncEnums::CSYNC_INSTRUCTION_NEW "Network error: 99"
11-28 15:23:02:420 [ warning nextcloud.sync.propagator ]:       Could not complete propagation of "test-new-file-2024-11-28.txt" by OCC::BulkPropagatorJob(0x55cb40b8d1d0) with status OCC::SyncFileItem::NormalError and error: "Network error: 99"
11-28 15:23:02:420 [ info nextcloud.sync.propagator.bulkupload ]:       modify final status NormalError OCC::SyncFileItem::NormalError OCC::SyncFileItem::NormalError
11-28 15:23:02:420 [ info nextcloud.sync.propagator.bulkupload ]:       final status OCC::SyncFileItem::NormalError
11-28 15:23:02:420 [ info nextcloud.sync.propagator.root.directory ]:   OCC::SyncFileItem::NormalError slotSubJobsFinished OCC::PropagatorJob::Running pending uploads 0 subjobs state OCC::PropagatorJob::Finished
11-28 15:23:02:420 [ info nextcloud.sync.propagator ]:  PropagateRootDirectory::slotSubJobsFinished emit finished OCC::SyncFileItem::NormalError
```

**Comment by adeverteuil** [comment] 2024-12-27 03:36
Adding the `nextcloudcmd --version` output:

```plaintext
Nextcloud version 3.7.3git
Using Qt 5.15.8, built against Qt 5.15.8
Using 'OpenSSL 3.0.15 3 Sep 2024'
Running on Debian GNU/Linux 12 (bookworm), x86_64
```

**Comment by joshtrichards** [comment] 2024-12-27 19:09
Duplicate of #nextcloud/desktop#5824

> Nextcloud version 3.7.3git

Fixed long ago. Please upgrade to a supported version of the Desktop client. (https://docs.nextcloud.com/)

**Closed by joshtrichards** 2024-12-27 19:09 UTC
Labels: bug, 0. Needs triage
