### ISSUE TITLE
Error while upgrading auf NextCloud 13.0.4

### ISSUE THREAD

**Issue by Kunibert-007** [nextcloud/server#9858] opened 2018-06-13 19:05 UTC
Please help! My NextCloud doesn't work anymore but I need it!
Get this error after starting "upgrade" in the front-end-gui:

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_appconfig` SET `configvalue` = ? WHERE (`appid` = ?) AND (`configkey` = ?) AND (`configvalue` <> ?)' with params [0, "core", "lastupdatedat", 0]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Reperaturwarnung:Unable to clear the frontend cache
```

**Operating system**: NextcloudPi Version 0.56.21 // Debian Linux 9
Hardware: Rock 64 with 4 GB RAM

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:**  Rock64-Image

Here the Summary from NextcloudPi:

NextCloudPi version | v0.56.21
-- | --
NextCloudPi image | NextCloudPlus_05-10-18
distribution | Debian GNU/Linux 9 \n \l
automount | yes
USB devices | sda
datadir | /media/USBdrive/ncdata
data in SD | no
data filesystem | btrfs
data disk usage | 120G/932G
rootfs usage | 4.0G/57G
swapfile | /var/swap
Nextcloud check | ok
Nextcloud version | 13.0.4.0
HTTPD service | up
PHP service | up
MariaDB service | up
Redis service | up
Postfix service | up
internet check | ok
port check 80 | open
port check 443 | open
IP | 192.168.0.4
gateway | 192.168.0.1
interface | eth0
certificates | nextcloud.XXX.com
NAT loopback | no
uptime | 1min

**Comment by MorrisJobke** [comment] 2018-06-13 20:55
Duplicate of #8863

**Comment by MorrisJobke** [comment] 2018-06-13 20:55
We are working on improving this. It could also be that the mysql server somehow stopped and caused this then.

**Closed by MorrisJobke** 2018-06-13 20:55 UTC

**Comment by Kunibert-007** [comment] 2018-06-13 21:16
Thank you for the link but my system is still down and in your linked issue I can't find a solution to recover it. What can I do now, do you have a hint for me?

**Comment by MorrisJobke** [comment] 2018-06-13 21:20
> What can I do now, do you have a hint for me?

Re-run `occ upgrade` and check the mysql logs.

Beside that: As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
