### ISSUE TITLE
Button to create a new group.

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/server#10945] opened 2018-08-31 10:58 UTC
It might be a duplicate or is addressed already, but anyway...

In NC 14.0.0 RC1 I have a button saying `New user` in the users panel.
Maybe it would make sense to add a `New group` button?

**Comment by rollanders** [comment] 2018-09-11 16:57
I am unable to create new groups. There is no button for that in the add new user page.

**Comment by TomTurnschuh** [comment] 2018-09-12 09:26
#11182

**Comment by skjnldsv** [comment] 2018-09-12 13:13
Duplicate of #11182

**Closed by skjnldsv** 2018-09-12 13:13 UTC
Labels: enhancement, feature: occ
