### ISSUE TITLE
No scrolling in list of Groups when selecting "Limit to Groups" in App-Management

### ISSUE THREAD

**Issue by Pit-Storm** [nextcloud/server#14869] opened 2019-03-26 17:59 UTC
Similar to #11543 there is no Scrollbar when selecting an group in App-Management "Limit to group". The Field is the size like in User-Management Group-Selection.

### Steps to reproduce
1. Select an App and check the Box "Limit to groups"
2. Click in the Field "Limit App usage to groups"
3. List with User-Grourps opens

### Expected behaviour
The list schould be scrollabale like in User-Management. So Groups which are not in the first entrys can be nselected and unselected whithout typing in the search field.

### Actual behaviour
List ist not scrollable. Entries wich are not in the first entries of the list, are not unselectable, even if useing the search field. When click in entry after typing it's not getting unselected.

### Server configuration

I can not say anything about my server version, because it is hosted.

**Nextcloud version:** 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**: Fresh install, maybe from docker.

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

No access to command line.

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 60.6.1esr (64-Bit)

**Operating system:** Windows 10 Pro x64 latest updates

#### Web server error log
<details>
<summary>Web server error log</summary>

no acces to that
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

no access
</details>

#### Browser log
<details>
<summary>Browser log</summary>

no access
</details>

**Comment by skjnldsv** [comment] 2020-09-09 11:49
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-09-09 11:49 UTC
Labels: 0. Needs triage, bug
