### ISSUE TITLE
Comments are no longer working (NC 18.0.5)

### ISSUE THREAD

**Issue by andreasgremm** [nextcloud/server#21271] opened 2020-06-06 14:50 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Select ...
2. Select "Details"
3. Click on "Comment"

### Expected behaviour
Tell us what should happen
I should see the comments and should be able to write comments
### Actual behaviour
Tell us what happens instead
Comments is selected .. but no comments are seen and comments can't be written.
### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
18.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 18.0.3 
**Where did you install Nextcloud from:**
Stable Channel
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - appointments: 1.5.0
  - apporder: 0.10.0
  - bookmarks: 3.1.1
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - customproperties: 1.0.1
  - dav: 1.14.0
  - deck: 1.0.2
  - documentserver_community: 0.1.5
  - dropit: 0.4.0
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_antivirus: 2.4.1
  - files_automatedtagging: 1.8.3
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_markdown: 2.3.0
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_texteditor: 2.11.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - groupfolders: 6.0.6
  - keeweb: 0.6.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.5.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.2.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - piwik: 0.5.4
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - ransomware_detection: 0.7.1
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.2
  - workflow_script: 1.3.2
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - files_frommail
  - mail
  - support
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.4",
            "innovation.mettmann.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/innovation.mettmann.de\/nextcloud",
        "dbtype": "mysql",
        "version": "18.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "de",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "lost_password_link": "http:\/\/innovation.mettmann.de\/ssp\/?action=sendtoken",
        "maintenance": false,
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDav

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

+-------------------------------+-------------------------------------------------------+
| Configuration                 |                                                       |
+-------------------------------+-------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                       |
| homeFolderNamingRule          |                                                       |
| lastJpegPhotoLookup           | 0                                                     |
| ldapAgentName                 | cn=browseuser,ou=manage,o=feuerwehr,dc=mettmann,dc=de |
| ldapAgentPassword             | ***                                                   |
| ldapAttributesForGroupSearch  |                                                       |
| ldapAttributesForUserSearch   |                                                       |
| ldapBackupHost                |                                                       |
| ldapBackupPort                |                                                       |
| ldapBase                      | dc=mettmann,dc=de                                     |
| ldapBaseGroups                | dc=mettmann,dc=de                                     |
| ldapBaseUsers                 | dc=mettmann,dc=de                                     |
| ldapCacheTTL                  | 600                                                   |
| ldapConfigurationActive       | 1                                                     |
| ldapDefaultPPolicyDN          |                                                       |
| ldapDynamicGroupMemberURL     |                                                       |
| ldapEmailAttribute            | mail                                                  |
| ldapExperiencedAdmin          | 0                                                     |
| ldapExpertUUIDGroupAttr       | entryUUID                                             |
| ldapExpertUUIDUserAttr        | entryUUID                                             |
| ldapExpertUsernameAttr        |                                                       |
| ldapExtStorageHomeAttribute   |                                                       |
| ldapGidNumber                 | gidNumber                                             |
| ldapGroupDisplayName          | cn                                                    |
| ldapGroupFilter               | (&(|(objectclass=groupOfUniqueNames)))                |
| ldapGroupFilterGroups         |                                                       |
| ldapGroupFilterMode           | 0                                                     |
| ldapGroupFilterObjectclass    | groupOfUniqueNames                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                          |
| ldapHost                      | localhost                                             |
| ldapIgnoreNamingRules         |                                                       |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid))           |
| ldapLoginFilterAttributes     |                                                       |
| ldapLoginFilterEmail          | 0                                                     |
| ldapLoginFilterMode           | 0                                                     |
| ldapLoginFilterUsername       | 1                                                     |
| ldapNestedGroups              | 0                                                     |
| ldapOverrideMainServer        |                                                       |
| ldapPagingSize                | 500                                                   |
| ldapPort                      | 389                                                   |
| ldapQuotaAttribute            |                                                       |
| ldapQuotaDefault              |                                                       |
| ldapTLS                       | 0                                                     |
| ldapUserAvatarRule            | default                                               |
| ldapUserDisplayName           | cn                                                    |
| ldapUserDisplayName2          | mail                                                  |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                        |
| ldapUserFilterGroups          |                                                       |
| ldapUserFilterMode            | 0                                                     |
| ldapUserFilterObjectclass     | inetOrgPerson                                         |
| ldapUuidGroupAttribute        | auto                                                  |
| ldapUuidUserAttribute         | auto                                                  |
| turnOffCertCheck              | 0                                                     |
| turnOnPasswordChange          | 0                                                     |
| useMemberOfToDetectMembership | 1                                                     |
+-------------------------------+-------------------------------------------------------+

</details>

### Client configuration
**Browser:**
Chrome / Safari
**Operating system:**
RHEL 7
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2020-06-06 15:04
Closing as duplicate of https://github.com/nextcloud/server/issues/21239

**Closed by kesselb** 2020-06-06 15:04 UTC
Labels: 0. Needs triage, bug
