### ISSUE TITLE
Custom theme favicon does not show up everywhere

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#5284] opened 2017-06-07 12:37 UTC
There are lots of custom-theme-related issues around here, so please be patient in case I did not find the one about favicons.

Since I managed to re-setup a custom theme ( #5276 ) in v12.0.0, I have set `'theme' => 'mytheme'` in `config.php` and favicon files placed in the right folder:

    $ ls -la themes/mytheme/core/img/favicon*
    -rw-r--r--. 1 e4f9m e4f9m  3209 Jun  7 14:01 themes/mytheme/core/img/favicon-mask.svg
    -rw-r--r--. 1 e4f9m e4f9m  3722 Jun  7 14:01 themes/mytheme/core/img/favicon-touch.png
    -rw-r--r--. 1 e4f9m e4f9m  3209 Jun  7 14:01 themes/mytheme/core/img/favicon-touch.svg
    -rw-r--r--. 1 e4f9m e4f9m 32038 Jun  7 14:01 themes/mytheme/core/img/favicon.ico
    -rw-r--r--. 1 e4f9m e4f9m   939 Jun  7 14:01 themes/mytheme/core/img/favicon.png
    -rw-r--r--. 1 e4f9m e4f9m  3209 Jun  7 14:01 themes/mytheme/core/img/favicon.svg

The favicon does show up on:

* the login page
* activity app
* calendar app
* contacts app
* mail app
* gallery app

It does **NOT** show up on:

* the files app
* the personal settings
* the users settings
* the apps page
* the admin page

I did run `php ./occ maintenance:mimetype:update-js` which is known from #3094 to do magic on some theme-related issues, but I can't tell whether it did anything to this issue.

**Comment by blizzz** [comment] 2017-06-12 11:13
did you try  to clear your browser cache? might be also cached on server side, not sure.

**Comment by mcnesium** [comment] 2017-06-12 11:41
Yes, and I also tried different browsers including one with a brand newly created profile.

**Comment by juliushaertl** [comment] 2017-06-13 17:52
Can you check which url is loaded for the favicon on pages that don't show up the themed icon?

**Comment by mcnesium** [comment] 2017-06-14 07:29
from Files source:

    <link rel="icon" href="/core/img/favicon.ico">
    <link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
    <link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#aa0000">
    <link rel="manifest" href="/core/img/manifest.json">

**Comment by juliushaertl** [comment] 2017-06-14 11:46
Debugged this a bit with @mcnesium today. The issue was that favicon paths were still cached in redis cache. After manually deleting those cache entries it works fine.

Is there any mechanism that is able to invalidate the cache from IUrlGenerator->imagePath()? I remember this issue coming up more than once. 

Any idea @blizzz or @MorrisJobke maybe?

**Comment by blizzz** [comment] 2017-06-14 12:18
So https://github.com/nextcloud/server/issues/5329 is essentially a duplicate of this one?

**Comment by juliushaertl** [comment] 2017-06-15 10:26
@blizzz Not exactly. Both happen because the cache doesn't get invalidated. This one because something in theming changes, #5329 because the protocol changes.

**Comment by juliushaertl** [comment] 2017-06-15 10:31
The problem here is that we don't have any mechanism to detect if a custom theme has changed. Maybe we should add some occ command to clear the image cache and document that in the theme documentation.

**Comment by blizzz** [comment] 2017-06-15 11:21
Sounds like a plan

**Comment by juliushaertl** [comment] 2017-09-01 21:00
Fixed with #5441

**Closed by juliushaertl** 2017-09-01 21:00 UTC
Labels: bug, feature: theming

**Comment by jaymerts** [comment] 2024-07-19 18:51
Thank you @juliushaertl and @mcnesium!! It was a nightmare to solve this.
