### ISSUE TITLE
Multiple 'InvalidArgumentException: Invalid settings setting registered' in log after update to 15.0.0 Beta1

### ISSUE THREAD

**Issue by rso42** [nextcloud/server#12394] opened 2018-11-10 12:57 UTC
### Steps to reproduce
1. Update Server from 14.0.3 to 15.0.0 Beta 1
2. Login as admin
3. Open logging section in administration area

### Actual behaviour
Log file shows many 'InvalidArgumentException' lines each time I access nextcloud web interface.

### Server configuration

**Operating system**:
Ubuntu 18.04.1

**Web server:**
nginx 1.15.4

**Database:**
MariaDB 10.3.9

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.0 Beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.0.3

**Where did you install Nextcloud from:**
nextcloud.com download

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.7.2
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - admin_audit
  - federation
  - files_external
  - files_versions
  - firstrunwizard
  - support
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

``` json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.REMOVED.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/var\/www\/sites\/nextcloud\/tmp",
        "overwrite.cli.url": "https:\/\/www.REMOED.com",
        "overwriteprotocol": "https",
        "overwritehost": "www.REMOVED.com",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "15.0.0.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "loglevel": 1,
        "check_for_working_webdav": true,
        "has_internet_connection": true,
        "check_for_working_wellknown_setup": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 7776000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "trashbin_retention_obligation": "auto, 2",
        "activity_expire_days": "180",
        "defaultapp": "files",
        "enable_avatars": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF"
        ],
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 1,
        "updater.release.channel": "beta",
        "theme": "",
        "skeletondirectory": "",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
<details>
<summary>Web server error log</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

``` json
{
	"reqId": "XaSihmXlWsmqeNtFGiRO",
	"level": 1,
	"time": "2018-11-10T13:40:55+01:00",
	"remoteAddr": "xxx.xxx.xxx.xxx",
	"user": "ADMINUSER",
	"app": "no app in context",
	"method": "GET",
	"url": "/settings/admin/logging",
	"message": {
		"Exception": "InvalidArgumentException",
		"Message": "Invalid settings setting registered",
		"Code": 0,
		"Trace": [
			{
				"file": "/var/www/sites/nextcloud/web/lib/private/Settings/Manager.php",
				"line": 283,
				"function": "getSettings",
				"class":"OC\Settings\Manager",
				"type": "->",
				"args": [
					"admin",
					"logging"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/settings/Controller/CommonSettingsTrait.php",
				"line": 65,
				"function": "getAdminSettings",
				"class":"OC\Settings\Manager",
				"type": "->",
				"args": [
					"logging"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/settings/Controller/CommonSettingsTrait.php",
				"line": 101,
				"function": "formatSections",
				"class":"OC\Settings\Controller\AdminSettingsController",
				"type": "->",
				"args": [
					{
						"0": [
							{
								"class":"OC\Settings\Section"
							}
						],
						"1": [
							{
								"class":"OC\Settings\Section"
							},
							{
								"class":"OCA\ServerInfo\Settings\AdminSection"
							}
						],
						"5": [
							{
								"class":"OC\Settings\Section"
							}
						],
						"10": [
							{
								"class":"OC\Settings\Section"
							}
						],
						"30": [
							{
								"class":"OCA\Theming\Settings\Section"
							}
						],
						"50": [
							{
								"class":"OC\Settings\Section"
							}
						],
						"55": [
							{
								"class":"OCA\Activity\Settings\AdminSection"
							},
							{
								"class":"OCA\WorkflowEngine\Settings\Section"
							}
						],
						"90": [
							{
								"class":"OCA\LogReader\Settings\Section"
							}
						],
						"98": [
							{
								"class":"OC\Settings\Section"
							}
						]
					},
					"logging",
					"admin",
					"admin"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/settings/Controller/CommonSettingsTrait.php",
				"line": 51,
				"function": "formatAdminSections",
				"class":"OC\Settings\Controller\AdminSettingsController",
				"type": "->",
				"args": [
					"admin",
					"logging"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/settings/Controller/CommonSettingsTrait.php",
				"line": 125,
				"function": "getNavigationParameters",
				"class":"OC\Settings\Controller\AdminSettingsController",
				"type": "->",
				"args": [
					"admin",
					"logging"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/settings/Controller/AdminSettingsController.php",
				"line": 65,
				"function": "getIndexResponse",
				"class":"OC\Settings\Controller\AdminSettingsController",
				"type": "->",
				"args": [
					"admin",
					"logging"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/lib/private/AppFramework/Http/Dispatcher.php",
				"line": 166,
				"function": "index",
				"class":"OC\Settings\Controller\AdminSettingsController",
				"type": "->",
				"args": [
					"logging"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/lib/private/AppFramework/Http/Dispatcher.php",
				"line": 99,
				"function": "executeController",
				"class":"OC\AppFramework\Http\Dispatcher",
				"type": "->",
				"args": [
					{
						"class":"OC\Settings\Controller\AdminSettingsController"
					},
					"index"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/lib/private/AppFramework/App.php",
				"line": 118,
				"function": "dispatch",
				"class":"OC\AppFramework\Http\Dispatcher",
				"type": "->",
				"args": [
					{
						"class":"OC\Settings\Controller\AdminSettingsController"
					},
					"index"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/lib/private/AppFramework/Routing/RouteActionHandler.php",
				"line": 47,
				"function": "main",
				"class":"OC\AppFramework\App",
				"type": "::",
				"args": ["OC\Settings\Controller\AdminSettingsController",
					"index",
					{
						"class":"OC\AppFramework\DependencyInjection\DIContainer"
					},
					{
						"section": "logging",
						"_route": "settings.AdminSettings.index"
					}
				]
			},
			{
				"function": "__invoke",
				"class":"OC\AppFramework\Routing\RouteActionHandler",
				"type": "->",
				"args": [
					{
						"section": "logging",
						"_route": "settings.AdminSettings.index"
					}
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/lib/private/Route/Router.php",
				"line": 297,
				"function": "call_user_func",
				"args": [
					{
						"class":"OC\AppFramework\Routing\RouteActionHandler"
					},
					{
						"section": "logging",
						"_route": "settings.AdminSettings.index"
					}
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/lib/base.php",
				"line": 987,
				"function": "match",
				"class":"OC\Route\Router",
				"type": "->",
				"args": [
					"/settings/admin/logging"
				]
			},
			{
				"file": "/var/www/sites/nextcloud/web/index.php",
				"line": 42,
				"function": "handleRequest",
				"class": "OC",
				"type": "::",
				"args": []
			}
		],
		"File": "/var/www/sites/nextcloud/web/lib/private/Settings/Manager.php",
		"Line": 170,
		"CustomMessage": "--"
	},
	"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36",
	"version": "15.0.0.5"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
logging:1 Failed to decode downloaded font: https://www.REMOVED.com/core/fonts/Nunito-Regular.woff2
13:53:18.025 logging:1 OTS parsing error: invalid version tag
13:53:18.269 logging:1 Failed to decode downloaded font: https://www.REMOVED.com/core/fonts/Nunito-Bold.woff2
13:53:18.269 logging:1 OTS parsing error: invalid version tag
13:53:21.178 logging:1 Failed to decode downloaded font: https://www.REMOVED.com/core/fonts/Nunito-Regular.woff2
13:53:21.178 logging:1 OTS parsing error: invalid version tag
13:53:21.178 logging:1 Failed to decode downloaded font: https://www.REMOVED.com/core/fonts/Nunito-Bold.woff2
13:53:21.178 logging:1 OTS parsing error: invalid version tag
13:53:21.585 DevTools failed to parse SourceMap: https://www.REMOVED.com/apps/notifications/js/notifications.js.map
13:53:21.588 DevTools failed to parse SourceMap: https://www.REMOVED.com/apps/logreader/build/main.js.map
13:53:21.590 DevTools failed to parse SourceMap: https://www.REMOVED.com/apps/logreader/build/main.css.map
</details>

**Comment by skjnldsv** [comment] 2019-06-14 06:26
Was coming from https://github.com/nextcloud/logreader/

As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-14 06:26 UTC
Labels: 0. Needs triage, 15-feedback, bug
