### ISSUE TITLE
Dashboard greeter does not unescape html entities

### ISSUE THREAD

**Issue by RoryO** [nextcloud/server#25308] opened 2021-01-25 00:46 UTC
### Steps to reproduce
1. Create a user with html unsafe entities like `< > ' "`
2. Log into instance
3. The greeter does not un-escape the entities properly

### Expected behaviour
Vue component should unescape the html entities

### Actual behaviour
Greeter displays escaped entities

### Server configuration

**Nextcloud version:** 20.4

Probably best done in the displayName here https://github.com/nextcloud/server/blob/801c69168490b67bdc9f4a4554513bebbbd2e9f3/apps/dashboard/src/App.vue#L140 I don't know Vue at all so I don't know the best way to handle it

example:

Real world name

![Screenshot_20210124_163548](https://user-images.githubusercontent.com/19547/105649105-ab153880-5e63-11eb-9470-db8a7bb842b2.png)

Display name as `test ' " < > chars`

![Screenshot_20210124_164340](https://user-images.githubusercontent.com/19547/105649109-aea8bf80-5e63-11eb-92c5-fb1a6bdf9654.png)

**Comment by jeanguyomarch** [comment] 2021-05-12 16:34
Having a family name with [an apostrophe](https://en.wikipedia.org/wiki/Apostrophe) I'd love to see this fixed too :)

**Comment by szaimen** [comment] 2021-07-06 09:35
Duplicate of https://github.com/nextcloud/server/issues/26113

**Closed by szaimen** 2021-07-06 09:35 UTC
Labels: 0. Needs triage, bug, feature: dashboard
