### ISSUE TITLE
weather widget doesn't use correct degree unit without changing locales and language for some users

### ISSUE THREAD

**Issue by salfter** [nextcloud/server#23653] opened 2020-10-23 20:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I just upgraded my home Nextcloud server to v20 and noticed it has a weather widget.  Cool...but it only appears to display temperature in °C, and I can't find an option to set it to °F.  Unless I'm just blind and missing a settings page somewhere, this should be added.

**Describe the solution you'd like**
A setting to toggle between °C and °F.  If there are other areas beyond the dashboard widget where temperatures are displayed, this toggle should ideally control them as well.

**Describe alternatives you've considered**
Hmm...not sure that there would be an alternative.

**Additional context**

**Comment by j-ed** [comment] 2020-10-24 12:01
Please have a look on the following [implementation comment](https://github.com/nextcloud/server/pull/22124#issuecomment-676524049), which describes for which locales the unit Fahrenheit (°F) is used.

**Comment by LuckierDodge** [comment] 2020-10-27 17:23
In the interest of helping others who might run into this: if your options are set to one of the listed locales, and the dashboard widget is still showing Celsius, try changing both the Language and Locale options in Settings->Personal->Personal Info from the correct value to a different value and back. This resolved the issue for me.

**Comment by axheli** [comment] 2020-11-05 18:54
I agree but for me it was showing C i was already in the USA so i have to recheck it and then it started working wish you didnt have to unselect and reselect for it to work.

**Comment by salfter** [comment] 2020-11-05 23:09
> In the interest of helping others who might run into this: if your options are set to one of the listed locales, and the dashboard widget is still showing Celsius, try changing both the Language and Locale options in Settings->Personal->Personal Info from the correct value to a different value and back. This resolved the issue for me.

That got it working right...thanks!

**Comment by mmccarn** [comment] 2020-11-09 11:11
The weather_status app does not recognize the default locale.

Most of my users have no locale listed in oc_preferences.  The rest of nextcloud recognizes and uses the locale set in the user's browser.

The procedure described here (change your locale, then change it back) creates an entry in oc_preferences for your user account with "configkey" set to "locale", at which point the temperature (for me, with locale en_US) changes to fahrenheit.

**Comment by LuckierDodge** [comment] 2020-11-09 14:32
@mmccarn I think you nailed it. Seems like adding respect for browser locale to the weather_status app would resolve this issue for most users.

**Comment by blkqi** [comment] 2021-01-12 18:22
My user previously had preferences _Language_ set to "English (US)" and _Locale_ set to "English (United States)". Still the value returned by `OC.getLocale()` was "en" and the weather widget displayed temperature in units of Celsius. After going into my user settings  and resetting the _Language_ and _Locale_ preferences to the **exact same values**, now `OC.getLocale()` returns "en_US" and the weather widget displays temperatures in Fahrenheit.

**Comment by axheli** [comment] 2021-01-12 19:30
@blkqi Yes i agree with you even if you have everything set to English it will still show Celsius and if you go back and reset it like you said it defaults to Fahrenheit frustrating.

**Comment by ahyattdev** [comment] 2021-02-08 16:41
> In the interest of helping others who might run into this: if your options are set to one of the listed locales, and the dashboard widget is still showing Celsius, try changing both the Language and Locale options in Settings->Personal->Personal Info from the correct value to a different value and back. This resolved the issue for me.

This worked for me!

**Comment by szaimen** [comment] 2021-06-23 13:13
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by ahyattdev** [comment] 2021-07-24 02:13
Don't think it works without that workaround.

**Comment by andyxheli** [comment] 2021-08-23 02:25
Still an issue

**Comment by mjmccarn** [comment] 2023-07-29 13:15
This issue still exists.

My solution has been to disable the dashboard on all servers...

**Comment by joshtrichards** [comment] 2023-09-07 20:36
Duplicate of #23486 

Let's consolidate tracking progress there.

**Closed by joshtrichards** 2023-09-07 20:36 UTC
Labels: enhancement, 1. to develop, feature: dashboard
