### ISSUE TITLE
Default root SHARES folder naming

### ISSUE THREAD

**Issue by Troublicious** [nextcloud/server#11758] opened 2018-10-11 09:55 UTC
### Steps to reproduce
1. UserA shares File1 with UserB
2. UserB renames the "Shares" folder which contains File1 to "Partage"
3. UserA shares File2 with UserB

### Expected behaviour
File2 should appear in "Partage" folder, not in a new "Shares" folder

### Actual behaviour
A new folder "Shares" is created for UserB, so UserB has two folders: "Shares" containing File2, and "Partage" containing File1

### Server configuration

**Operating system**: Debian

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 

**Nextcloud version:** (see Nextcloud admin page) 14

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

### Question:
What is the proper way to rename this default directory forever ?
Might it be possible to add an option to choose its name ?
Where is it possible in the source code to change this default name ?

Thanking you in advance !

**Comment by MorrisJobke** [comment] 2018-10-11 10:09
> ###
> File2 should appear in "Partage" folder, not in a new "Shares" folder

This is not how it works right now, because it was build as a server config (it's called share_folder in config.php).

What you basically want is #4471

Let's close this one here as duplicate of #4471 (I know the one is also closed, but there is more context why we closed it).

**Closed by MorrisJobke** 2018-10-11 10:09 UTC
Labels: feature: sharing

**Comment by Troublicious** [comment] 2018-10-11 11:51
Thank you MorrisJobke ! I canot believe i missed this share_folder parameter ... shame on me !
