### ISSUE TITLE
[Bug]: App description is not translated (but in Transifex there is an translation)

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#33979] opened 2022-09-08 14:19 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

under the menu item Apps | Your Apps | the description of the apps is not translated, the other parts of the interface are translated. It is like this for all apps, not only for single ones.
Same behavior for the menu items that show the app descriptions.

### Steps to reproduce

1. Open under the menu item Apps  and then Your Apps 
2. Click on an app
3. See in the right sidbar the description, which is not translated

![nc_tr1](https://user-images.githubusercontent.com/34692335/189145046-a4d61587-01c0-4738-a47f-24e9111fb842.png)

### Expected behavior

3. In the right sidbar the description is translated

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
???
```

### Additional info

Nextcloud 24

**Comment by cloud2018** [comment] 2022-09-12 12:51
@rakekniven  
sorry for reporting, i didn't find an issue with the filter "is:issue translation in:title is:open"

**Comment by szaimen** [comment] 2023-01-23 15:21
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by cloud2018** [comment] 2023-01-23 15:38
Version of my Nextcloud is  "24.0.9.2"; same :

![grafik](https://user-images.githubusercontent.com/34692335/214081388-6a8f10b2-5e7c-4aa5-bf4d-efb4bcb250f6.png)

**Comment by cloud2018** [comment] 2023-01-23 16:08
Same in nextcloud version 25.0.3.2:

![grafik](https://user-images.githubusercontent.com/34692335/214088904-a1f7a34b-0a4a-449c-8087-cd7ba5146daf.png)

**Comment by joshtrichards** [comment] 2023-08-28 20:44
Duplicate of nextcloud/appstore#691
Consolidating there to track progress/reports. Subscribe to that issue (and give it a :+1: ) if desired.

**Closed by joshtrichards** 2023-08-28 20:44 UTC
Labels: bug, 0. Needs triage, feature: apps management, feature: language l10n and translations, 25-feedback
