### ISSUE TITLE
	fclose(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by tyler-public** [nextcloud/server#18874] opened 2020-01-13 22:34 UTC
### Steps to reproduce
1. Add S3 external storage
2. Copy files into storage
3. View errors in log

### Expected behaviour
No errors

### Actual behaviour
Error spam in log: `fclose(): supplied resource is not a valid stream resource at /config/www/nextcloud/apps/files_external/lib/Lib/Storage/AmazonS3.php#688`

### Server configuration

**Operating system:** Docker

**Web server:** nginx

**Database:** mariadb (mysql)

**PHP version:** 7.3.13

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Docker (lsio/nextcloud-docker)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_audit: 1.7.0
  - calendar: 1.7.2
  - cloud_federation_api: 1.0.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_versions: 1.10.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - notes: 3.1.1
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - phonetrack: 0.5.11
  - previewgenerator: 2.2.0
  - provisioning_api: 1.7.0
  - richdocuments: 3.5.1
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.7.0
  - workflowengine: 1.7.0
Disabled:
  - accessibility
  - activity
  - comments
  - encryption
  - federation
  - files_pdfviewer
  - files_trashbin
  - files_videoplayer
  - nextcloud_announcements
  - privacy
  - recommendations
  - support
  - survey_client
  - systemtags
  - user_ldap
  - viewer
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwrite.cli.url": "https:\/\/cloud.tpage.io",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "mysql.utf8mb4": true,
        "twofactor_enforced": false,
        "mail_sendmailmode": "smtp",
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"xJBorF1AWjR61ryMBMU2","level":3,"time":"2020-01-13T22:15:08+00:00","remoteAddr":"192.168.10.55","user":"tyler","app":"PHP","method":"COPY","url":"\/remote.php\/dav\/files\/tyler\/PhoneTrack_export\/tyler-phone_weekly_2019-11-25.gpx","message":"fclose(): supplied resource is not a valid stream resource at \/config\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#688","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
{"reqId":"TWfUNvkfwS36OaKWOrS8","level":3,"time":"2020-01-13T22:15:08+00:00","remoteAddr":"192.168.10.55","user":"tyler","app":"PHP","method":"COPY","url":"\/remote.php\/dav\/files\/tyler\/PhoneTrack_export\/tyler-phone_weekly_2019-12-09.gpx","message":"fclose(): supplied resource is not a valid stream resource at \/config\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#688","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
{"reqId":"FXYmgkO6QJpAiOKrBfUy","level":3,"time":"2020-01-13T22:15:09+00:00","remoteAddr":"192.168.10.55","user":"tyler","app":"PHP","method":"COPY","url":"\/remote.php\/dav\/files\/tyler\/PhoneTrack_export\/tyler-phone_weekly_2019-11-11.gpx","message":"fclose(): supplied resource is not a valid stream resource at \/config\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#688","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
{"reqId":"LM1mF6UV8FgizG37iFpU","level":3,"time":"2020-01-13T22:15:10+00:00","remoteAddr":"192.168.10.55","user":"tyler","app":"PHP","method":"COPY","url":"\/remote.php\/dav\/files\/tyler\/PhoneTrack_export\/tyler-phone_weekly_2019-12-23.gpx","message":"fclose(): supplied resource is not a valid stream resource at \/config\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#688","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
{"reqId":"gRrsKgeA9bdU7mG3WD7R","level":3,"time":"2020-01-13T22:15:10+00:00","remoteAddr":"192.168.10.55","user":"tyler","app":"PHP","method":"COPY","url":"\/remote.php\/dav\/files\/tyler\/PhoneTrack_export\/tyler-phone_weekly_2019-12-16.gpx","message":"fclose(): supplied resource is not a valid stream resource at \/config\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#688","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
{"reqId":"9mbbcHI2goj8xWR5B60b","level":3,"time":"2020-01-13T22:15:12+00:00","remoteAddr":"192.168.10.55","user":"tyler","app":"PHP","method":"COPY","url":"\/remote.php\/dav\/files\/tyler\/PhoneTrack_export\/tyler-phone_weekly_2019-12-30.gpx","message":"fclose(): supplied resource is not a valid stream resource at \/config\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#688","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
{"reqId":"kLC6wfVNHDl4hwk0aUo2","level":3,"time":"2020-01-13T22:26:06+00:00","remoteAddr":"192.168.10.55","user":"tyler","app":"PHP","method":"COPY","url":"\/remote.php\/dav\/files\/tyler\/Notes\/Business%20Idea.txt","message":"fclose(): supplied resource is not a valid stream resource at \/config\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php#688","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"17.0.2.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Empty
```
</details>

**Comment by tyler-public** [comment] 2020-01-13 22:37
This seems similar to #18851 and #15486 but the difference here being I'm on version 17.0.2

**Comment by kesselb** [comment] 2020-01-14 10:38
Duplicate of https://github.com/nextcloud/server/issues/15486

**Closed by kesselb** 2020-01-14 10:38 UTC
Labels: 0. Needs triage, bug
