### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 4nanook** [nextcloud/server#31999] opened 2022-04-17 09:07 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to 23.0.3, code integrity check fails with extra files, files with wrong hash, and missing files.

### Steps to reproduce

1 Since I could not get the web based updater to work, timed out during backup, I.
2.initiated php occ upgrade from command line, but it told me I was already at the latest but I wasn't, so
3. I then typed php updater/php.phar and let it go through it's process.
4. When it finished, I ran a check from the settings panel and it fails code integrity check with extra file, a file with bad hash, and missing files.
5. I don't know how to recover and your documentation was less than helpful.

### Expected behavior

Expect to start from web based updater and have it finish for  once without trashing the entire system.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.eskimo.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "https:\/\/nextcloud.eskimo.com\/",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "mail.eskimo.com",
                    143
                ]
            }
        ],
        "maintenance": false,
        "data-fingerprint": "15c5e08aba95f4a9f58603c46b0bedc9",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "auto_mail_accounts",
            "caniupdate",
            "whiteboard",
            "ojsxc"
        ],
        "ldapIgnoreNamingRules": false,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "ISO 3166-2:US",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - afterlogic: 2.0.3
  - analytics: 4.2.1
  - announcementcenter: 6.1.1
  - appointments: 1.12.3
  - apporder: 0.15.0
  - approval: 1.0.9
  - audioplayer: 3.3.0
  - audioplayer_sonos: 1.3.0
  - bbb: 2.2.0
  - bookmarks: 10.3.0
  - breezedark: 23.2.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - camerarawpreviews: 0.7.15
  - carnet: 0.24.4
  - cas: 0.2.7
  - checksum: 1.1.3
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - cms_pico: 1.0.18
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - cookbook: 0.9.11
  - dav: 1.21.0
  - deck: 1.6.1
  - diary: 0.0.3
  - dicomviewer: 1.2.3
  - documentserver_community: 0.1.12
  - drawio: 1.0.2
  - duplicatefinder: 0.0.13
  - eidlogin: 1.0.7
  - electronicsignatures: 1.10.1
  - emlviewer: 1.0.1
  - encryption: 2.11.0
  - end_to_end_encryption: 1.9.1
  - epubreader: 1.4.7
  - event_update_notification: 1.5.0
  - external: 3.10.2
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_antivirus: 3.2.2
  - files_automatedtagging: 1.13.0
  - files_downloadactivity: 1.13.0
  - files_downloadlimit: 1.0.0
  - files_external: 1.15.0
  - files_fulltextsearch: 23.0.1
  - files_fulltextsearch_tesseract: 22.0.0
  - files_inotify: 0.1.12
  - files_linkeditor: 1.1.9
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.4.0
  - files_photospheres: 1.23.0
  - files_readmemd: 1.2.2
  - files_retention: 1.12.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_versions_s3: 0.1.8
  - files_videoplayer: 1.12.0
  - fileslibreofficeedit: 1.0.4
  - firstrunwizard: 2.12.0
  - forms: 2.5.0
  - fulltextsearch: 23.0.0
  - fulltextsearch_elasticsearch: 23.0.0
  - geoblocker: 0.5.4
  - gestion: 2.0.9
  - gpgmailer: 0.0.4
  - gpoddersync: 3.2.0
  - gpxedit: 0.0.14
  - gpxpod: 4.3.0
  - grauphel: 1.0.7
  - group_default_quota: 0.1.4
  - groupfolders: 11.1.2
  - groupquota: 0.1.8
  - guests: 2.2.0
  - health: 1.5.0
  - imageconverter: 1.3.2
  - impersonate: 1.10.0
  - integration_discourse: 1.0.2
  - integration_dropbox: 1.0.4
  - integration_github: 1.0.2
  - integration_gitlab: 1.0.3
  - integration_google: 1.0.6
  - integration_jira: 1.0.2
  - integration_mastodon: 1.0.2
  - integration_moodle: 1.0.2
  - integration_onedrive: 1.1.2
  - integration_openproject: 1.0.6
  - integration_reddit: 1.0.3
  - integration_suitecrm: 1.0.3
  - integration_twitter: 1.0.2
  - integration_zammad: 1.0.3
  - jitsi: 0.14.0
  - keeweb: 0.6.8
  - libresign: 2.4.5
  - listman: 20.1.1
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - maps: 0.1.10
  - mediadc: 0.1.9
  - messagevault: 1.0.0
  - metadata: 0.15.0
  - music: 1.5.1
  - news: 18.0.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - officeonline: 1.1.3
  - oidc: 0.1.0
  - oidc_login: 2.3.1
  - ojsxc: 5.0.0
  - onlyoffice: 7.3.2
  - openotp_auth: 1.4.2
  - openotp_sign: 1.3.0
  - ownpad: 0.6.17
  - password_policy: 1.13.0
  - passwords: 2022.4.10
  - phonetrack: 0.7.0
  - photos: 1.5.0
  - polls: 3.5.4
  - previewgenerator: 4.0.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - qownnotesapi: 21.12.0
  - quicknotes: 0.7.3
  - quota_warning: 1.14.0
  - rainloop: 7.2.2
  - ransomware_protection: 1.13.0
  - recognize: 1.12.0
  - recommendations: 1.2.0
  - registration: 1.4.0
  - richdocuments: 5.0.3
  - richdocumentscode: 21.11.306
  - riotchat: 0.11.3
  - rocketchat_nextcloud: 0.9.6
  - sendent: 1.2.11
  - sentry: 8.0.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - sharepoint: 1.11.0
  - sharingpath: 0.4.4
  - shifts: 1.8.6
  - side_menu: 2.3.5
  - signlive: 0.1.11
  - sociallogin: 4.14.0
  - socialsharing_diaspora: 2.5.0
  - socialsharing_email: 2.5.0
  - socialsharing_facebook: 2.5.0
  - socialsharing_twitter: 2.5.0
  - souvenirs: 1.3.0
  - spgverein: 0.11.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - suspicious_login: 4.1.0
  - systemtags: 1.13.0
  - tables: 0.1.1
  - talk_matterbridge: 1.23.2
  - talked: 0.3.0
  - tasks: 0.14.4
  - terms_of_service: 1.9.3
  - text: 3.4.1
  - theming: 1.14.0
  - theming_customcss: 1.11.0
  - tvshownamer: 0.1.2
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - unsplash: 1.2.4
  - updatenotification: 1.13.0
  - uppush: 1.0.0
  - user_ldap: 1.13.1
  - user_oidc: 1.1.0
  - user_status: 1.3.1
  - user_usage_report: 1.7.0
  - video_converter: 1.0.4
  - viewer: 1.7.0
  - w2g2: 3.3.8
  - weather_status: 1.3.0
  - webhooks: 0.2.0
  - welcome: 1.0.1
  - whiteboard: 0.0.3
  - wopi: 3.5.10
  - workflow_media_converter: 1.3.6
  - workflow_ocr: 1.23.2
  - workflow_pdf_converter: 1.8.0
  - workflow_script: 1.8.0
  - workflowengine: 2.5.0
  - wrikesync: 1.2.9
Disabled:
  - customproperties: 2.0.4
  - dashboard: 7.2.0
  - discoursesso: 1.22.0
  - facerecognition
  - files_trackdownloads: 1.11.0
  - integration_restya: 1.0.1
  - integration_whiteboard: 0.0.14
  - openhab: 0.9.5
  - richdocumentscode_arm64
  - user_external: 2.1.0
  - user_saml: 4.1.1
  - vibeetoee: 1.2.1
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- secsignid
	- EXTRA_FILE
		- docker-compose.yml
		- screenshots/screenshot_access_pass_thumb.png
		- screenshots/screenshot_access_pass.png
		- screenshots/screenshot_user_permissions.png
		- screenshots/screenshot_personal_settings.png
		- screenshots/screenshot_configuration.png
		- screenshots/screenshot_user_management.png
		- screenshots/screenshot_onboarding.png
- oidc
	- FILE_MISSING
		- .eslintrc.js
		- .git/FETCH_HEAD
		- .git/HEAD
		- .git/config
		- .git/description
		- .git/hooks/README.sample
		- .git/index
		- .git/info/exclude
		- .git/logs/HEAD
		- .git/objects/pack/pack-aa976c001fa7b2a8da827ed916d5e60550320b26.idx
		- .git/objects/pack/pack-aa976c001fa7b2a8da827ed916d5e60550320b26.pack
		- .gitattributes
		- .github/workflows/appstore-build-publish.yaml
		- .github/workflows/build-test.yaml
		- .gitignore
		- .php_cs.dist
		- Makefile
		- babel.config.js
		- composer.json
		- composer.lock
		- composer/composer.json
		- composer/composer.lock
		- docs/oidc-app.png
		- l10n/.gitkeep
		- package-lock.json
		- package.json
		- phpunit.integration.xml
		- phpunit.xml
		- src/App.vue
		- src/Redirect.vue
		- src/components/OIDCItem.vue
		- src/main.js
		- src/redirect.js
		- stylelint.config.js
		- tests/Integration/AppTest.php
		- tests/Unit/Controller/DiscoveryControllerTest.php
		- tests/Unit/Controller/JwksControllerTest.php
		- tests/bootstrap.php
		- translationfiles/de/oidc.po
		- translationfiles/en/oidc.po
		- translationfiles/pt/oidc.po
		- translationfiles/templates/oidc.pot
		- webpack.config.js
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [secsignid] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [docker-compose.yml] => Array
                        (
                            [expected] => 
                            [current] => f0595c25bc35d955ff9ac8835d84bc3ee815fcbbc6173f2984d0a39dee012dd0491b1eeffb12dd5cf28df2cdf01d4a54e1b90796459773c7716b0984d4caec2e
                        )

                    [screenshots/screenshot_access_pass_thumb.png] => Array
                        (
                            [expected] => 
                            [current] => 914b2a7c4043ab7d4448247d89a69d08c089e9e5cc1a2a1ca278dacf6e7920fc9e625c0dfa92f84de404106c9f971a78f5f18cd96e5b43c2afcfce32827541e5
                        )

                    [screenshots/screenshot_access_pass.png] => Array
                        (
                            [expected] => 
                            [current] => cdce3d7aa8105cf8453ecd9d197785b48798eeda286cd86d2fe2cdfa8b69e2ac7e2d4dcecbc273e4558b556e93ff93d44fd662b8eb8f34e34dd0b811f156d559
                        )

                    [screenshots/screenshot_user_permissions.png] => Array
                        (
                            [expected] => 
                            [current] => acac3f15009247dca1237448e45bc1c7d5780282eddbd4d80ebc175d2492635f9f823c6294f075350e729cfb5ccccedf888d60bdf795c984a3cdd4e05d55d681
                        )

                    [screenshots/screenshot_personal_settings.png] => Array
                        (
                            [expected] => 
                            [current] => 98ac27cc433c66fcdffc8e7192fa09956524f5dc08e3b222dd4009bb90680aca27fb51b5564ac09ebb76786796f3a6a72e9dcfae35689c87e1e5e4d1c00f036a
                        )

                    [screenshots/screenshot_configuration.png] => Array
                        (
                            [expected] => 
                            [current] => 0d1d0af23a4442f500b0b3e27958fc86233673346c951c8ee8681ccab7fc9672ac0d89ac8b6a510348253537c288b954ea4d319ed0d6b652fd5c2464919727f1
                        )

                    [screenshots/screenshot_user_management.png] => Array
                        (
                            [expected] => 
                            [current] => faece1a28a7692c08676a72d8e1d49c7bf938ed044769e454d24b50a384bfc833937d08b60e2c8b66c14f9c8620f0bd5d0bcbaa8d501b3dede35e891a3c0d879
                        )

                    [screenshots/screenshot_onboarding.png] => Array
                        (
                            [expected] => 
                            [current] => 6b238ed855580bb32218f11bd275ea1a33a07aaf5b5477bb3cff79c7dfea6cb2d6f7661f7b16bbe26339ed3e057eadc935e83c134b300df4cc2dea15035edfbd
                        )

                )

        )

    [oidc] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.eslintrc.js] => Array
                        (
                            [expected] => 061b7c886204c18ad4cb79c67da0442b8705cf72a065b2c7cd3acaf0caca777b113565a0146cb4fa85c5fcaef2957f563848d82f9145819bbcc8278f6e4056d3
                            [current] => 
                        )

                    [.git/FETCH_HEAD] => Array
                        (
                            [expected] => 7542604cd03a76b18d2896ecb4ec8ffa046f7465d3628b1d9ea8fa060cc49c78eee0fb3aae7152ecc4c607267c52cc1a1496cc6861fbb432bcaca98b6443da4a
                            [current] => 
                        )

                    [.git/HEAD] => Array
                        (
                            [expected] => f21a9bc6d2d28bad85c5f9306af781153d506e73c01041a8197be9e974e07ca2558bb058d2f34bb70c1917ba24c8d614eb10f363e78230d9dad0a0728df64095
                            [current] => 
                        )

                    [.git/config] => Array
                        (
                            [expected] => b8320a722fdb92535297015c4269260da6da626c7e68513933c645e1bbe4e1b5b0c91a572cd5223c3fcf7f60961b198ee41da57251bae996bb9c616a548cfe02
                            [current] => 
                        )

                    [.git/description] => Array
                        (
                            [expected] => f7e152f75b124c3e1c5d12f00427729d9eec4e2c1bf70d7606440a6600d003367eb178331e75ab976a61496e79c2c822020849d28ffd170946397b934611b471
                            [current] => 
                        )

                    [.git/hooks/README.sample] => Array
                        (
                            [expected] => c41c0c3da9c4b03922690ec294901f1748ffd094789c7f2566738a1fd03e9b0623adbcb873a3318c3c4b586b8d8525c5e6785d94d62423bd66f6ca414388a7d8
                            [current] => 
                        )

                    [.git/index] => Array
                        (
                            [expected] => 9914527402cb275c33fdec508127fbd48aff2bd68ade9a1dd4270f64dc9bbf5a52c8bf2902bbd8839bd033af866d2e2e5e475ddd7434c8f159972f7d54f3629f
                            [current] => 
                        )

                    [.git/info/exclude] => Array
                        (
                            [expected] => 745dfcc65abfe31b588111975057c0d593939183790ef24e3f6071a5f9e47ec35f884fa77a816e8930545bdadc00095663070c035c73eab54314e09084f9f95b
                            [current] => 
                        )

                    [.git/logs/HEAD] => Array
                        (
                            [expected] => 00c92a2a24231116747a558d298c962265ecffa46437fdb013681a56001acc52408ac2d38494827063a69e7fc834d7e427030fb6bc3a9293e1ceac0a2ece0d8d
                            [current] => 
                        )

                    [.git/objects/pack/pack-aa976c001fa7b2a8da827ed916d5e60550320b26.idx] => Array
                        (
                            [expected] => fe3f72d07ea3597c51d2b06d4e9d93f29a278562c0e52fb53bd8d7f8ee993472a5f46c5e6c0620f8eac2e66709659300846f35b5d695f8df1f249d29824afeb3
                            [current] => 
                        )

                    [.git/objects/pack/pack-aa976c001fa7b2a8da827ed916d5e60550320b26.pack] => Array
                        (
                            [expected] => 6d89a7e753e158eab777b0c33ff4f7addfa9cf18715701f75ff68d0489dd9093d28f388ade6954b77fcb775a90e50caaff7b1f4a7acbc58c7689d0083d2a0ec1
                            [current] => 
                        )

                    [.gitattributes] => Array
                        (
                            [expected] => 831c25ed73e6eaa1a5807392219c1b47bb1146796fc54ae58293b036695cd340e0b7cf2617b6a55ce64cb94e3dcfb1b7f630dd858b411c3e2b3f169925994270
                            [current] => 
                        )

                    [.github/workflows/appstore-build-publish.yaml] => Array
                        (
                            [expected] => 03c8adb92828aac0446e5d414cafe1b807405126eee63616c3993350a124175658ffc79fb0e12ab1e2cae57efc39fa552f210a7ff435f1612c4488be169b2809
                            [current] => 
                        )

                    [.github/workflows/build-test.yaml] => Array
                        (
                            [expected] => 174e304b6c9660492131e4e066210041e7b832df6197d31c29c5ecf0a94ff33b13e4dd8b3e74ba915a600120bc1da60c5ffa75a888eb06ef1fe061ab32185495
                            [current] => 
                        )

                    [.gitignore] => Array
                        (
                            [expected] => bb6e73a2631414824706efb40389b1aaa7f4c813b05b14b73330de4a78ce69c588e75ca203e1ea63ba44d54108495d607bfa1354dd7eadd26a853d29f439c549
                            [current] => 
                        )

                    [.php_cs.dist] => Array
                        (
                            [expected] => a768a02ed4d9c9dfc8686d94cb3d921c851afb5598d9dd0b3b2abf9097e25a0276fc5eb53b1ec4fd1ff79583b24ed5fc09ad379e17068fd74bf2a2522c388248
                            [current] => 
                        )

                    [Makefile] => Array
                        (
                            [expected] => 8b153652f578ec72d2521e58211dd00d4bad0086d94ac2211482a726b4a04a060808225d9c04f77db1a15918acf2289fe23dad22595e246ab1bc887959e69399
                            [current] => 
                        )

                    [babel.config.js] => Array
                        (
                            [expected] => 52255f2deac6eac69bf864935fabed674ea69807c7ac578bbd58e7a9d3c2e06fd1dc93a512f1422c436e9086cf40ce4c106a7ba8f49ef65c03260c7261c47f25
                            [current] => 
                        )

                    [composer.json] => Array
                        (
                            [expected] => 6be1370df8880e9fa20091ca7094078241a7515832ec34d587d6423795a19a2a3ff11f59252a0825495b375983b145fba056ffbd81160669074796fd254d9348
                            [current] => 
                        )

                    [composer.lock] => Array
                        (
                            [expected] => 9fe5d7fe8256922bfe847d5323b0c224413250c761970b75e678d8f01f7ddddbcb7a4e2512f2d2d341f3ffc0db98885ae9be8880f96fa85d3db01121b1fac564
                            [current] => 
                        )

                    [composer/composer.json] => Array
                        (
                            [expected] => a84c8b9e6464563dae85f5d8264e714cb13264e2c38b4f0ab17d2a75f683a81eeff0146f0c8b1bf74b81d895a8bb5ed81f89216c311a6bc6477f38563492eb7c
                            [current] => 
                        )

                    [composer/composer.lock] => Array
                        (
                            [expected] => aba0413aa705be0d0570c496a43249c551836824e7a2b4673b51838fe0d9f425ddd07b6c4b95aa74ca549f58e90f2a7d78b51a2a3080749a5dc2e4a46d04fd1e
                            [current] => 
                        )

                    [docs/oidc-app.png] => Array
                        (
                            [expected] => 3e47639a1c0d893857cc8bc63795dbdf0565382c299917554ae2ae77cbf29701a0ace571d907b932e96b6d1f56d501dbe36da33575f0242c139d7c1f793a27cf
                            [current] => 
                        )

                    [l10n/.gitkeep] => Array
                        (
                            [expected] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                            [current] => 
                        )

                    [package-lock.json] => Array
                        (
                            [expected] => fb3468fa48c9c586e26f330f108fa18ba620598da4912369fe8fd3b0a59ab3e64beb84e222708ab475c8760b028870c07931da1d7259e046653c73ea0bd5b817
                            [current] => 
                        )

                    [package.json] => Array
                        (
                            [expected] => 15506d3244fc2c65040ea8475931b454ad88d85bf79e70f64072a343a623b0d880f350d9b68f7eb2b70f4d62a77b737d5f37bd3ac46a4455d458c4fb5b9f05de
                            [current] => 
                        )

                    [phpunit.integration.xml] => Array
                        (
                            [expected] => ec94923d03a922a799b234c0f5aca3a99377722395a2f8725787325d4e8c1e19cc692c53e6ea8b6678caa8cc70f0cdb32e8dcae500189012961bb38c22ce66d9
                            [current] => 
                        )

                    [phpunit.xml] => Array
                        (
                            [expected] => 5224b6d8c68f54f1bba06d61472f0c1fe1a5e3b20c1e8d58e2c5658684441fbc6c39289807ca1ebb6f850632715de450cf54970b774faccc457aa3141056679d
                            [current] => 
                        )

                    [src/App.vue] => Array
                        (
                            [expected] => 29084aa4260d6371da2d9141c513398a397f5bcae5f183dc0399eb3d0606dbfcbcd35f5c6bd5c39ea790a96aed858fa9714c9ef478a32260369808be48f6f3ad
                            [current] => 
                        )

                    [src/Redirect.vue] => Array
                        (
                            [expected] => 429c07df4fb33a0c00e7f749bbd3b7053ef34ab96c3404ce5d70a45360f72f37845a9b51a6e1281f86c49ce00b936c978a3e77b1a8341b89cf8156a145d37672
                            [current] => 
                        )

                    [src/components/OIDCItem.vue] => Array
                        (
                            [expected] => a13996b7b42c83498e9a4d44056072dec16e1c38130d5017d7e610d95d443f29ca692cf42ec0cfef933b364509719090c18471ebf610522a6dd54a6caf3c13e9
                            [current] => 
                        )

                    [src/main.js] => Array
                        (
                            [expected] => 71cc7a562298a580a7d6754e90c1559015883c4b57871f224fa5b98d7a723a534544588221a6aaf2e3f529cb4c6a7207d53062998a258eae38dbcab9f3a13fc8
                            [current] => 
                        )

                    [src/redirect.js] => Array
                        (
                            [expected] => 46491f94172a8eab3a0e060900dee47df3d1c09a1ae0c88be5a6ebaf6a9c82429bbcf8a04fa74c97f515eb7bbcadbdb5de4532673a7559d7ca515957cd5a04a9
                            [current] => 
                        )

                    [stylelint.config.js] => Array
                        (
                            [expected] => 1b0c21fcb497dd0396b318d813e149aec91c335fedbfd0193bdad0fb76e9d23070aa60f57b3f990f8ff0103447524bccafe06708d24f995f3aae37f3e337e753
                            [current] => 
                        )

                    [tests/Integration/AppTest.php] => Array
                        (
                            [expected] => 08808ea8b6060311e885726c8903d494c2cbd4ecd2d003272c2d95b59b84b016db861c722becec085222901c56e0a75808836ae6c175fde5166f0a7352bacfec
                            [current] => 
                        )

                    [tests/Unit/Controller/DiscoveryControllerTest.php] => Array
                        (
                            [expected] => 099a38051fa21c547b8e755b559a63cf2d5d17d33a1efb351bcf1b7d60f6c2d6129f56f038ea6379d16e647b19fac24a67a6d6a44252fdf5b8c66597f5817a5b
                            [current] => 
                        )

                    [tests/Unit/Controller/JwksControllerTest.php] => Array
                        (
                            [expected] => 1ad2541e8c7635fa1948c1c9687d79ea982b8613daf1c7904b4f92d5270d849feffb39f78d4dffd29eea89fe303d6369d0279dd4719cab3e9bfac1b67d75e654
                            [current] => 
                        )

                    [tests/bootstrap.php] => Array
                        (
                            [expected] => 3535a6a948c6cf75cc1fbb44fed36476e7243094c9f5336244b3d395fe1dfed7ab1bdc0d19fd23ca8b5c9eb63f500734379fcef8ea6828a9fed9d68ee7ef8ab1
                            [current] => 
                        )

                    [translationfiles/de/oidc.po] => Array
                        (
                            [expected] => 4fb5d1bc5788d71848cc827a5924cffb44fd413c49ab3fb27b7e8e3014d8a35b37fc69035e342269360b10cc035ce2a0ba3dde86c42bae5d7464940459c6f9c2
                            [current] => 
                        )

                    [translationfiles/en/oidc.po] => Array
                        (
                            [expected] => c70658ddd874cfa39f9aa76eb682014fe8ad3d3b4ba83f8ae6413d877c985dc4ab183e72751bdfe9e3564624772ed06a3f59ec9cdbb6f771f07cadb4f51cbb82
                            [current] => 
                        )

                    [translationfiles/pt/oidc.po] => Array
                        (
                            [expected] => a6a0d41051f81fea2a2559679ac916146d4597136b255909e0b96fcdb5fbbbc4118eabe377e5f9f7e715181718db89c2feb26845d651d03b6ef5145cc2445f33
                            [current] => 
                        )

                    [translationfiles/templates/oidc.pot] => Array
                        (
                            [expected] => e261ae8e8a2d454ce45fabc2df8f11460584ec4dfdec90c70dfbd2de34a1984ac6dad998a1b1bf28a7a19d304756cc78aea43e5460c2cbc918c1f5f1f8cfc01b
                            [current] => 
                        )

                    [webpack.config.js] => Array
                        (
                            [expected] => 04b63cbafeb550e94988fcdd285d34cfa4a203e26673334ccf038268074c6dc8a2c01f67800f890cf5124c19f9fd759a5bdb1dd912b4ab88886331ef3699a034
                            [current] => 
                        )

                )

        )

    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 94195a260a005dac543c3f6aa504f1b28e0078297fe94a4f52f012c16c109f0323eecc9f767d6949f860dfe454625fcaf1dc56f87bb8350975d8f006bbbdf14a
                            [current] => 1b07fb272efa65a10011ed52a6e51260343c5de2a256e1ae49f180173e2b6684ccf90d1af3c19fa97c31d42914866db46e3216883ec0d6a82cec0ad5529e78b1
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
This is 20MB, I don't know how you expect me to copy and paste 20MB.
```

**Comment by szaimen** [comment] 2022-04-17 09:20
Duplicate of https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/600

**Closed by szaimen** 2022-04-17 09:20 UTC
Labels: bug, 0. Needs triage
