### ISSUE TITLE
[Bug]: The files are simply overwritten when dragging and dropping via the web interface. 

### ISSUE THREAD

**Issue by camouflage81** [nextcloud/server#44567] opened 2024-03-29 09:35 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello everyone,

With Nextcloud version 28.0.3 and 28.0.4, when dragging and dropping via the web interface, the file is simply overwritten if it already exists. The query whether the file should be overwritten or both should be kept is no longer displayed. I have not tested earlier versions.

### Steps to reproduce

1. Drag and drop a file into the drag and drop field of the web interface if the folder already contains a file with the same name.

### Expected behavior

A query window should appear

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.***REMOVED SENSITIVE VALUE***.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.4.1",
        "overwrite.cli.url": "https:\/\/cloud.***REMOVED SENSITIVE VALUE***.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "trashbin_retention_obligation": "auto, 7",
        "activity_expire_days": 7,
        "maintenance": false,
        "log_rotate_size": 1048576,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2,
        "maintenance_window_start": 1,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bookmarks: 13.1.3
  - calendar: 4.6.7
  - circles: 28.0.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - deck: 1.12.2
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - geoblocker: 0.5.13
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - dashboard: 7.8.0 (installed 7.8.0)
  - encryption: 2.16.0 (installed 2.16.0)
  - files_external: 1.20.0 (installed 1.20.0)
  - photos: 2.4.0 (installed 2.4.0)
  - support: 1.11.1 (installed 1.11.0)
  - survey_client: 1.16.0 (installed 1.16.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.8.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
n/a
```

### Additional info

Thanks for Help

**Comment by camouflage81** [comment] 2024-04-18 14:16
Hello everyone,

What are the next steps (I can't interpret what the labels mean). I see it as very critical when files are simply overwritten without being queried. Can anyone reproduce and confirm this problem?

Thank you

**Comment by ilpssun** [comment] 2024-04-28 07:39
I wanted to write “I can confirm the behavior in Nextcloud 28.0.4.“, but I just found out that it seems to be fixed in 28.0.5.  At least for my recently updated 28.0.5 instance, dragging an existing file into the drop zone prompts me for keep/replace options.

**Comment by ilpssun** [comment] 2024-04-28 07:47
… and I have to revise that statement: It is not fixed.

Dropping a plain-text file named `PIN` or a `.pdf` file leads to a prompt whether to keep/replace the file. However, when I drop a `.kdbx` file (KeePass DB) into the same folder, the prompt does not appear.  I have not investigated further but it seems that the behavior is inconsistent dependent on the file type/extension.

**Comment by camouflage81** [comment] 2024-05-02 13:07
I can confirm that the query appears again in version 28.0.5.
I also receive a notification for *.kdbx files.
![Unbenannt](https://github.com/nextcloud/server/assets/43865081/1650f51b-5c41-4eee-b291-82a9b2651cfd)

**Comment by camouflage81** [comment] 2024-05-03 12:34
In my opinion, we can close this thread.

**Closed** 2024-05-07 06:31 UTC
Labels: bug, 0. Needs triage, feature: files, 28-feedback
