### ISSUE TITLE
Accessing Nextcloud over browser crashes php process

### ISSUE THREAD

**Issue by aaruni96** [nextcloud/server#30330] opened 2021-12-18 13:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

After updating to Nextcloud 23, trying to open nextcloud on browser crashes the PHP process for the entire server.

### Steps to reproduce
1. Open browser
2. Attempt to login

### Expected behaviour
Nextcloud dashboard loads without issue

### Actual behaviour
Browser gets stuck at "waiting for URL", eventually fails with "504 Gateway Timeout", and the php process is crashed for the entire server (unrelated websites also based on PHP stop working, and require a php service restart).

### Server configuration

**Operating system:**
Debian 11 Bullseye

**Web server:**
nginx
**Database:**
postgresql
**PHP version:**
7.4-fpm
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 23
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from nextcloud 22.2.3
**Where did you install Nextcloud from:**
Tarball from nextcloud website
**Signing status:**
<details>
<summary>Signing status</summary>

Logging in to server fails

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - calendar: 3.0.2
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.7
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_external: 1.15.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.4.0
  - groupfolders: 11.1.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.4
  - metadata: 0.15.0
  - music: 1.5.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.4.2
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quicknotes: 0.7.3
  - quota_warning: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.0
  - richdocumentscode: 21.11.6
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - side_menu: 2.1.0
  - spreed: 13.0.1
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - unsplash: 1.2.4
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - apporder
  - data_request
  - encryption
  - files_texteditor
  - flow_notifications
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.edufor.me"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.edufor.me",
        "dbtype": "pgsql",
        "version": "23.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "simpleSignUpLink.shown": false,
        "default_phone_region": "DE",
        "data-fingerprint": "75908b8012a9eca7791c8e19dc56aa34",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}


```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
 Firefox 95
**Operating system:**
Pop!_OS 21.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2021/12/18 14:31:35 [error] 3197#3197: *847 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <redacted>, server: <redacted>, request: "GET /css/settings/35c3-7fa5-settings.css?v=b92d206521717ac032f8aa58d3c7ff2f-35c36e89-0 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock", host: "<redacted>"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
$ sudo -u www-data php ./occ log:tail
 ------- ------------------- ---------------------------------------------------------------------------------------------------- --------------------------- 
  Level   App                 Message                                                                                              Time                       
 ------- ------------------- ---------------------------------------------------------------------------------------------------- --------------------------- 
  Info    updater             \OC\Repair::step: Repair step: Queue a one-time job to check for user uploaded certificates          2021-12-18T12:56:04+00:00  
                                                                                                                                                              
  Info    no app in context   Deprecated event type for \OC\Repair::step: Symfony\Component\EventDispatcher\GenericEvent is used   2021-12-18T12:56:04+00:00  
                                                                                                                                                              
  Info    updater             \OC\Repair::step: Repair step: Repair DAV shares                                                     2021-12-18T12:56:04+00:00  
                                                                                                                                                              
  Info    no app in context   Deprecated event type for \OC\Repair::step: Symfony\Component\EventDispatcher\GenericEvent is used   2021-12-18T12:56:04+00:00  
                                                                                                                                                              
  Info    updater             \OC\Repair::step: Repair step: Add background job to set the lookup server share state for users     2021-12-18T12:56:04+00:00  
                                                                                                                                                              
  Info    updater             \OC\Updater::startCheckCodeIntegrity: Starting code integrity check...                               2021-12-18T12:56:04+00:00  
                                                                                                                                                              
  Info    updater             \OC\Updater::finishedCheckCodeIntegrity: Finished code integrity check                               2021-12-18T12:56:21+00:00  
                                                                                                                                                              
  Info    updater             \OC\Updater::updateEnd: Update successful                                                            2021-12-18T12:56:21+00:00  
                                                                                                                                                              
  Info    updater             \OC\Updater::maintenanceDisabled: Turned off maintenance mode                                        2021-12-18T12:56:21+00:00  
                                                                                                                                                              
  Info    updater             \OC\Updater::resetLogLevel: Reset log level to Warning(2)                                            2021-12-18T12:56:21+00:00  
                                                                                                                                                              
 ------- ------------------- ---------------------------------------------------------------------------------------------------- ---------------------------
```
</details>

**Comment by jsargent8789** [comment] 2021-12-19 00:27
I am running into the same issue.

**Comment by szaimen** [comment] 2021-12-19 00:33
Duplicate of https://github.com/nextcloud/richdocuments/issues/1887

**Comment by jsargent8789** [comment] 2021-12-19 00:33
@aaruni96 Just disable Collabora Online as temporary work around.

**Closed by szaimen** 2021-12-19 00:33 UTC
Labels: bug, 0. Needs triage

**Comment by aaruni96** [comment] 2021-12-19 15:51
@jsargent8789 thanks, that works for now.
