### ISSUE TITLE
Unsupported VALUE parameter for DTEND property

### ISSUE THREAD

**Issue by avanc** [nextcloud/server#3350] opened 2017-02-01 13:28 UTC
### Steps to reproduce
1. Update from Nextcloud 10.x
2. See error logs in administration screen

### Expected behaviour
No error logs

### Actual behaviour
Following error is repeated several times:

    Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied ""

This seems to be related to #2249.
However, a fix of the database should be available: #2807. 
I don't know if the database was not repaired, or if this is another issue. Is there a way to manually trigger the database repair?
Unfortunately, the error message does not give any hint, what entry makes the problem.
I created an vcf export of my calendar, but I don't know for what pattern I have to look?
DTEND without VALUE, or without DATE?

### Server configuration
**Operating system**:
Arch Linux

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
PHP 7

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Comment by nickvergessen** [comment] 2017-02-01 14:12
Duplicate of #2741

**Closed by nickvergessen** 2017-02-01 14:12 UTC

**Comment by michauk** [comment] 2017-02-07 23:41
sorry I commented on issue 2807, but it seems to be closed. And I, too, think the bug isn't totally corrected. Here was my message mon issue 2807 :


I think the live repair of incorrect cal entries isn't correct (complete?).

I switched from OC 9.1.3 to NC 10.0.x, no problem
Then I upgraded from 10.x to 11.0, calendar broken with this "Unsupported VALUE parameter for DTEND property" in the logs. After some googling, I found all these github issues 2741, this one, 2273 and so on.

I've done again the upgrade (restored to oc 9 and so on) several times, to be sure (I wasn't sure if I had to have the calendar plugin reactivated while in transition NC 10, before upgrading to 11.0.1). Same problem, every time.

I mass-edited some cal entries with this bad DTEND property. Now the logs (logging menu in NC adminitration) don't show any error (all debug levels enabled) but I have even more calendars loading endlessly. I don't think I have bad entries because of the mass-editing. But in any case, the upgrade from 10 to 11 doesn't correct the entries that make NC 11 load endlessly.

Can't move to NC with this bug. I switched back to OC 9.1.3
I can help find the incorrect entries if needed. My different calendars are many years old, a looooong time ago in google calendars, moved to owncloud (7 if I'm not wrong, some years ago) and upgraded little by little to 9.1.3. My cal entries have been created with different tools (thunderbird, some android apps, directly in the OC web interface...), I might have some entries NC 11.0.1 doesn't like any more.

Regards,

JAcques M.
