### ISSUE TITLE
Collabora Downs Server Completely

### ISSUE THREAD

**Issue by circlenaut** [nextcloud/server#13437] opened 2019-01-09 08:59 UTC
### Steps to reproduce
1. Installed/Setup Collabora server correctly
2. Installed and configured Collabora app

### Expected behaviour
Collabora opens documents correctly

### Actual behaviour
Server is completely down!

### Server configuration

**Operating system**:
Ubuntu 16.04.5

**Web server:**
Apache 2.4.18
**Database:**
Mariadb 10.1
**PHP version:**
7.2.13-1
**Nextcloud version:** (see Nextcloud admin page)
15
**Updated from an older Nextcloud/ownCloud or fresh install:**
14

I'm getting a bunch of 
`[Wed Jan 09 08:36:34.735221 2019] [core:notice] [pid 3268] AH00051: child pid 4642 exit signal Segmentation fault (11), possible coredump in /etc/apache2`
in my apache logs

Also I don't see collabora when I run occ apps:list. How do I disable it to get my instance back up and running!?

**Comment by buttle** [comment] 2019-01-09 11:52
I've found that if the collabora server is not running, NC becomes unusable. It takes various minutes to login or change between apps.

To disable collabora app (and get the NC web interface working again).

`sudo -u www-data php occ app:disable richdocuments`

**Comment by juliushaertl** [comment] 2019-01-09 12:32
Duplicate of https://github.com/nextcloud/server/issues/13434 will be fixed in the next richdocuments version

**Closed by juliushaertl** 2019-01-09 12:32 UTC
Labels: 0. Needs triage, bug

**Comment by circlenaut** [comment] 2019-01-09 19:49
Thanks! That's it! Turns out I forgot to setup the internal reverse proxy on the collabora server itself.
