### ISSUE TITLE
[Bug]: dark mode: apps > Cicles and Suspicious Login apps shows with black icon instead of light grey

### ISSUE THREAD

**Issue by foss-** [nextcloud/server#40094] opened 2023-08-29 10:32 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Bug]: dark mode: apps > Cicles app shows with black icon instead of light grey

### Steps to reproduce

1. open apps
2. search for Circles app
3. look at icon

### Expected behavior

Icon should use light grey color when dark mode is used.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![1](https://github.com/nextcloud/server/assets/5708172/e1f05559-f29a-4e04-ac09-75a543893780)

![2](https://github.com/nextcloud/server/assets/5708172/f0012321-2253-49a0-b100-1d8387e341f4)

**Comment by joshtrichards** [comment] 2023-09-07 14:57
Duplicate of nextcloud/circles#1232 (and nextcloud/suspicious_login#752)

**Closed by joshtrichards** 2023-09-07 14:57 UTC
Labels: bug, 0. Needs triage, feature: theming, feature: circles, 26-feedback
