### ISSUE TITLE
Upload via web  interface of file with same name in different subfolders

### ISSUE THREAD

**Issue by danielecarrazza** [nextcloud/server#10527] opened 2018-08-03 14:51 UTC
### Steps to reproduce
1. Create a folder structure like that: 
   +subfolder001 (contain the file: filename.txt)
   +subfolder002 (contain the file: filename.txt)
   +subfolder003 (contain the file: filename.txt)
   +subfolder004 (contain the file: filename.txt)
   +subfolder005 (contain the file: filename.txt)

2.  Drag and drop the five folders at the same time into the nextcloud file area. 

### Expected behaviour
The five folder with the same structure copied without errors. 

### Actual behaviour
The files are not copied and the web interface remain blocked. It appens quite always also with just two folders. 
NOTE: I have also tryed the same procedure in the official demo of nextcloud.com and it have the same behaviour. 

### Server configuration

**Operating system**: Debian 9 

**Web server:** Nginx 

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:**  13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**  Fresh install 

**Where did you install Nextcloud from:** from git repository

**Signing status:**
<details>
<summary>Signing status</summary>

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Tested also disabling all apps. 
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Default unmodified config 
</details>

**Are you using external storage, if yes which one:**  no external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
no ldap
</details>

### Client configuration
**Browser:** Tested with multiple browser chrome, firefox (not possible with edge because do not support folder upload)

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

Nothing appears in system logs.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Nothing appears in nextcloud logs also in debug
</details>

#### Browser log
<details>
<summary>Browser log</summary>

</details>

**Comment by vincentbab** [comment] 2018-08-07 11:48
I have the same bug. Chrome's console shows a javascript error:

Uncaught TypeError: Cannot read property 'done' of null
    at HTMLInputElement.<anonymous> (merged-index.js?v=2d8458b8-3:1521)
    at HTMLInputElement.dispatch (core.js?v=2d8458b8-3:3)
    at HTMLInputElement.r.handle (core.js?v=2d8458b8-3:3)
    at Object.trigger (core.js?v=2d8458b8-3:3)
    at Object.a.event.trigger (core.js?v=2d8458b8-3:7)
    at HTMLInputElement.<anonymous> (core.js?v=2d8458b8-3:3)
    at Function.each (core.js?v=2d8458b8-3:2)
    at a.fn.init.each (core.js?v=2d8458b8-3:2)
    at a.fn.init.trigger (core.js?v=2d8458b8-3:3)
    at e.(/apps/files/anonymous function).(anonymous function)._trigger (https://xxx/core/vendor/core.js?v=2d8458b8-3:13:10041)

**Comment by danielkesselberg** [comment] 2018-08-08 14:25
Issue is coming from https://github.com/nextcloud/server/blob/4eafae4178fcbd99627d9e9625b0b1f1ebe46dd5/apps/files/js/file-upload.js#L43

Id of upload is generated from file name (without the folder) and getTime().

FolderA/test.txt => web-file-upload-1111-timestamp
FolderB/test.txt => web-file-upload-1111-timestamp

In some cases getTime() is the same which results in identical ids for files in FolderA and FolderB. When i replace getTime with Math.random i cannot reproduce the issue anymore. 

Owncloud had a [similar issue](https://github.com/owncloud/core/pull/29393/files). Is this true for nextcloud too?


![image](https://user-images.githubusercontent.com/3902676/43843162-2b3cd912-9b27-11e8-9899-762fb817cd18.png)

I think relativePath + fileName + Math.random should prevent the identical ids.

**Comment by claushviid** [comment] 2018-08-08 21:01
hello danielkesselberg

I tried to change the line to Math.random() i still got the same error again, but only with a lot more identical files not with a few identical files.
Regards claus Hviid

**Comment by danielkesselberg** [comment] 2018-08-08 21:11
Does it work when you change to code like in the picture? I added this.getFile().relativePath before this.getFile().name

**Comment by claushviid** [comment] 2018-08-08 21:41
no, it still does not work.
Here's a link with the files I'm trying with.

https://nextcloud1.claushviid.dk/s/jqekqbqq6R2ZC5y

The only way I could get the files copied into Nextcloud is via Flowupload

**Comment by claushviid** [comment] 2018-08-10 15:29
Hmmm... today it is working with the changes made by danielkesselberg ????

**Comment by danielecarrazza** [comment] 2018-08-15 18:36
I have just tried to swap the function with the one of NC twin brother and it work perfectly. I have no time now investigate better but this could be the way to check the origin  of the bug.

**Comment by Marc-Whiteman** [comment] 2018-10-18 14:06
> I have the same bug. Chrome's console shows a javascript error:
> 
> Uncaught TypeError: Cannot read property 'done' of null
> at HTMLInputElement. (merged-index.js?v=2d8458b8-3:1521)
> at HTMLInputElement.dispatch (core.js?v=2d8458b8-3:3)
> at HTMLInputElement.r.handle (core.js?v=2d8458b8-3:3)
> at Object.trigger (core.js?v=2d8458b8-3:3)
> at Object.a.event.trigger (core.js?v=2d8458b8-3:7)
> at HTMLInputElement. (core.js?v=2d8458b8-3:3)
> at Function.each (core.js?v=2d8458b8-3:2)
> at a.fn.init.each (core.js?v=2d8458b8-3:2)
> at a.fn.init.trigger (core.js?v=2d8458b8-3:3)
> at e.(/apps/files/anonymous function).(anonymous function)._trigger (https://xxx/core/vendor/core.js?v=2d8458b8-3:13:10041)

I'm seeing this error as well, but only with Windows clients if that helps any.

**Comment by Lartza** [comment] 2019-01-02 18:50
This issue is still happening on 15.0.0, regardless of browser

**Comment by danielkesselberg** [comment] 2019-01-02 19:31
@Lartza i was unsure about my solution and never setup a pull request for it. there were reports that this fix for owncloud (https://github.com/owncloud/core/pull/29393/files) solve the issue as well. had troubles to adopt the fix from owncloud for nextcloud. I guess we could as @skjnldsv @juliushaertl for some advice.

**Comment by hottwister** [comment] 2019-03-13 06:01
Seems this changes in /apps/files/js/file-upload.js works for me 


`OC.FileUpload = function(uploader, data) {
        this.uploader = uploader;
        this.data = data;
//      var path = '';
        var basePath = '';
        if (this.uploader.fileList) {
//              path = OC.joinPaths(this.uploader.fileList.getCurrentDirectory(), this.getFile().name);
//      } else {
//              path = this.getFile().name;
                basePath = this.uploader.fileList.getCurrentDirectory();
        }
        var path = OC.joinPaths(basePath, this.getFile().relativePath || '', this.getFile().name);
        this.id = 'web-file-upload-' + md5(path) + '-' + (new Date()).getTime();
};`

Need more tests)

**Closed** 2019-03-20 10:20 UTC
Labels: 0. Needs triage, bug, feature: files
