### ISSUE TITLE
Word spacing broken in Firefox since Nextcloud 20.0.5

### ISSUE THREAD

**Issue by ringe** [nextcloud/server#29616] opened 2021-11-09 21:39 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade Nextcloud
2. Word spacing is off the charts
3. Not a problem in Chrome, only Firefox
4. Forget website, to reload styles and all - wierd word spacing still

### Expected behaviour
Nextcloud UI should have similar word spacing in Chrome and Firefox

### Actual behaviour
Nextcloud UI in Firefox has wide word spacing.

### Server configuration

**Operating system:**
Ubuntu

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
7.4.3

**Nextcloud version:** (see Nextcloud admin page)
20.0.5
21.0.4
22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated.

**Where did you install Nextcloud from:**
Latest tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupfolders: 10.0.0
  - guests: 2.0.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.narvikbygg.no"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "overwrite.cli.url": "https:\/\/cloud.narvikbygg.no",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "587",
        "mail_smtpauth": "1",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "nb",
        "default_locale": "nb_NO",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_phone_reqion": "NO",
        "default_phone_region": "NO",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

```
***empty***
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
62.101.200.183 - - [09/Nov/2021:22:35:44 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
109.247.151.58 - lasse [09/Nov/2021:22:35:45 +0100] "PROPFIND /remote.php/dav/files/lasse/ HTTP/1.1" 207 260 "-" "Mozilla/5.0 (Windows) mirall/3.3.5stable-Win64 (build 20210930) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
62.101.200.183 - - [09/Nov/2021:22:35:57 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
109.247.151.58 - torgrim [09/Nov/2021:22:36:00 +0100] "PROPFIND /remote.php/dav/files/torgrim/ HTTP/1.1" 207 263 "-" "Mozilla/5.0 (Windows) mirall/3.3.1stable-Win64 (build 20210812) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
62.101.200.183 - - [09/Nov/2021:22:36:14 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
109.247.151.58 - lasse [09/Nov/2021:22:36:15 +0100] "PROPFIND /remote.php/dav/files/lasse/ HTTP/1.1" 207 260 "-" "Mozilla/5.0 (Windows) mirall/3.3.5stable-Win64 (build 20210930) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
62.101.200.183 - - [09/Nov/2021:22:36:27 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
109.247.151.58 - torgrim [09/Nov/2021:22:36:30 +0100] "PROPFIND /remote.php/dav/files/torgrim/ HTTP/1.1" 207 263 "-" "Mozilla/5.0 (Windows) mirall/3.3.1stable-Win64 (build 20210812) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
62.101.200.183 - - [09/Nov/2021:22:36:44 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
109.247.151.58 - lasse [09/Nov/2021:22:36:45 +0100] "PROPFIND /remote.php/dav/files/lasse/ HTTP/1.1" 207 260 "-" "Mozilla/5.0 (Windows) mirall/3.3.5stable-Win64 (build 20210930) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)"

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
[PollingBackend:fetchSteps] Network error when fetching steps, retry 1 PollingBackend.js:171:13
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på inline ("script-src"). moz-extension:71:795990
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src").
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på inline ("script-src"). moz-extension:35:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src").
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:708
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:62:15
[DEBUG] files: Templates providers 
Object { 0: {…}, app: "files", uid: "admin" }
ConsoleLogger.js:42:18
[DEBUG] files: Templates folder 
Object { app: "files", uid: "admin", templatesPath: false }
ConsoleLogger.js:42:18
Proxying an event bus of version 1.3.0 with 2.0.0 talk-collections.js:1:346970
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 2 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Proxying an event bus of version 1.3.0 with 2.0.0 ProxyBus.js:72:14
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
OCA.Files.Sidebar initialized Sidebar.js:36:10
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:62:15
OCA.Comments.View initialized comments-app.js:32:8
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 4 globals.js:62:15
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). index.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). index.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). index.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). GetIntrinsic.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). GetIntrinsic.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). GetIntrinsic.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). GetIntrinsic.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). GetIntrinsic.js:21:9
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). GetIntrinsic.js:21:9
Proxying an event bus of version 1.3.0 with 2.0.0 talk-files-sidebar.js:1:1640323
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
OCA.Sharing.ExternalShareActions initialized ExternalShareActions.js:33:10
Proxying an event bus of version 1.3.0 with 2.0.0 ProxyBus.ts:17:12
OCA.Viewer initialized Viewer.js:49:10
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 1.3.0 with 2.0.0 ProxyBus.ts:17:12
Loading theming data for notification bell styling App.vue:138
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Registering notifications container as a menu App.vue:148
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Notifications permissions not yet requested App.vue:381
Polling interval updated to 30000 App.vue:325
Started background fetcher as session_keepalive is enabled App.vue:204
OCA.Files.Settings initialized Settings.js:29:10
Content Security Policy: Nettsidens innstillinger blokkerte lasting av en ressurs på eval ("script-src"). global.js:10:10
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 96 globals.js:62:15
session heartbeat polling started session-heartbeat.js:101:9
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
[DEBUG] files: Templates folder not initialized 
Object { app: "files", uid: "admin" }
ConsoleLogger.js:42:18
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 1.3.0 with 2.0.0 ProxyBus.js:72:14
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:263
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 5 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 196 globals.js:62:15
Got notification data App.vue:288
Polling interval updated to 30000 App.vue:325
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
New notification, animating the bell icon App.vue:179
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:42:18
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 40 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 22 globals.js:62:15
Clipboard is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 18 globals.js:62:15
registerDetailView is deprecated! It will be removed in nextcloud 20. merged-index.js:7840:12
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
registerTabView is deprecated! It will be removed in nextcloud 20. merged-index.js:7814:12
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 32 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 20 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 6 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 172 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 26 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 23 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 3 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 7 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 13 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 5 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 18 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 23 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 23 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 24 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 25 globals.js:62:15
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:123:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment util.js:135:11
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 23 globals.js:62:15
GEThttps://cloud.narvikbygg.no/core/preview?fileId=119122&c=890238679d11f1647d110c3c59bd6a87&x=500&y=500&forceIcon=0&a=0
[HTTP/2 404 Not Found 93ms]

jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 7 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 30 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 14 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 12 globals.js:62:15
No new notification data received App.vue:293
Polling interval updated to 30000 App.vue:325
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 9 util.js:135:11
No new notification data received App.vue:293
Polling interval updated to 30000 App.vue:325
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 9 util.js:135:11

```
</details>

**Comment by ringe** [comment] 2021-11-09 21:42
I fixed this issue by installing the Custom CSS app and placing this CSS there:

```
:root {
 --font-face: Segoe UI, Roboto, Oxygen-Sans, Cantarell, Ubuntu, Helvetica Neue, Arial;
}
```

This was to **override** the original CSS:
```
:root {
  --font-face: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen-Sans, Cantarell, Ubuntu, Helvetica Neue, Arial, Noto Color Emoji, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;
}
```

**Comment by acsfer** [comment] 2021-11-10 09:33
Can you share a screenshot?

**Comment by alecz** [comment] 2021-12-03 15:43
I have the same issue. It is caused by the fact that the emoji font (_Noto Emoji_ in my case) is picked up before any regular font. And this font also contains the space and digits characters but at an increased width. I believe none of the emoji fonts should be part of the _font-family_ attribute
![image](https://user-images.githubusercontent.com/8507642/144629480-c01f702f-98ca-4cd8-bbe0-af18e0254817.png)

**Comment by alecz** [comment] 2022-04-13 02:13
Fixed in version _23.0.1_ commit [896d83fcd6aa7111ff233083558d2b2a046423fa](https://github.com/nextcloud/server/commit/896d83fcd6aa7111ff233083558d2b2a046423fa)

**Closed** 2023-01-23 12:21 UTC
Labels: bug, 0. Needs triage
