### ISSUE TITLE
UI/fonts issue when copy/move files (Firefox, Linux)

### ISSUE THREAD

**Issue by Eothred** [nextcloud/server#15383] opened 2019-05-06 08:18 UTC
There seem to be some graphical glitches in the move/copy window in the web client. Since it is the web client I assume this is related to server rather than the desktop client so I decided to report here.

### Steps to reproduce
1. Have one folder with many sub-folders
2. Select a file to copy/move to that destination
3. The last folder in the list is not selectable
4. First letter of each folder seem to be overshadowed by the folder icon?

### Expected behaviour
Expected to have no graphical glitches

### Actual behaviour
This is how it looks for me
![image](https://user-images.githubusercontent.com/187567/57213723-f92b3e00-6fe7-11e9-84e2-49824abfdfb2.png)

### Server configuration

I apologise, I am not an admin of this server, but I can ask the admin for any information you may need. I asked for the basic configuration details and I got this answer:

"It is installed from the official Docker image, NextCloud 15.0.7 (image with Apache), and postgres as database"

On the client side I observe this on my laptop running Manjaro Linux with Firefox 66.0.4

I do not observe the same using Chrome on the same computer.

**Comment by skjnldsv** [comment] 2020-04-10 11:48
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 11:48 UTC
Labels: 0. Needs triage, 15-feedback, bug
