### ISSUE TITLE
[Bug]: setting expiration date on internal share is not working

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#43457] opened 2024-02-08 13:42 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi team,
I just created an internal share to Fabien, I am trying to set an expiration date, but as soon as I've ticked the box, the tick disappear. If I click the cross to exit the share properties, the attached msg is displayed

![image](https://github.com/nextcloud/server/assets/5836855/8dbe5585-8edd-463a-90f9-135554795df3)

### Steps to reproduce

1. create an internal share from the desktop client.
2. enter the options, and try to set an expiration date.
3. the tick disappear, and if you close the share options, a msg is displayed : expiration date is in the past.

### Expected behavior

I should be able to set an expiration date. a date picker should open, or a default value in the future should be set.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

This was first reported here: https://github.com/nextcloud-gmbh/desktop/issues/22

**Comment by tobiasKaminsky** [comment] 2024-02-08 13:42
> reproducible by web UI
most likely a regression of https://github.com/nextcloud/server/pull/42660
I tested using v26.0.11 and can reproduce (desktop client and web UI)
I then reverted the backport to stable26 (i.e. a31b1c731b9185926ca6c38b71aba29f2d6f4d98) and it fixes the bug

from @mgallien

**Comment by Dennis1993** [comment] 2024-02-21 17:03
It seems to be a duplicate of https://github.com/nextcloud/server/issues/43243

**Closed by Dennis1993** 2024-02-21 17:03 UTC
Labels: bug, 3. to review, 28-feedback
