### ISSUE TITLE
Locale is ignored and set to language code

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#15980] opened 2019-06-17 05:38 UTC
NC16.0.1

* It seems, that the locale setting is ignored and falls back to the language setting
![grafik](https://user-images.githubusercontent.com/26707476/59580649-34825780-90d2-11e9-838b-af883ccdf7aa.png)
* Also in the HTML header, the locale is always equal to the language code 
![grafik](https://user-images.githubusercontent.com/26707476/59580670-4f54cc00-90d2-11e9-915a-4a7da8dfee5c.png)
* (As a result?!) OC.locale returns always the language code

Maybe something in relation to #14784 ?

**Comment by wiswedel** [comment] 2020-01-02 06:35
duplicate of https://github.com/nextcloud/server/issues/15457

**Closed by wiswedel** 2020-01-02 06:35 UTC
Labels: 0. Needs triage, bug
