### ISSUE TITLE
9.2.4.3/11.2 When the "New folder" menu item is activated, a new row is created in the table with the "New folder" input field. However, the keyboard focus is not moved to the input field; it remains on the menu item. To change the folder name, a user has to navigate through all the other elements on the page.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42224] opened 2023-12-13 13:57 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-89806fe784-v11-n2

9.2.4.3/11.2 When the "New folder" menu item is activated, a new row is created in the table with the "New folder" input field. However, the keyboard focus is not moved to the input field; it remains on the menu item. To change the folder name, a user has to navigate through all the other elements on the page.

![image](https://github.com/nextcloud/server/assets/42591237/5b892690-d20b-4d6c-8bef-56b2ad9d3c2e)

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:33
duplicate of https://github.com/nextcloud/server/issues/41876

**Closed by JuliaKirschenheuter** 2023-12-14 10:33 UTC
Labels: accessibility
