### ISSUE TITLE
update 19.0.3> 20.0.7 was unsuccessful. 

### ISSUE THREAD

**Issue by perina** [nextcloud/server#26157] opened 2021-03-17 03:36 UTC
Doctrine\DBAL\Schema\SchemaException: The table with name 'perinane_nc2.nc_user_status' already exists.

**Comment by j-ed** [comment] 2021-03-17 08:53
Duplicate of https://github.com/nextcloud/server/issues/24217

BTW, this is the bug and feature tracker of the developers only. The [Nextcloud help forum](https://help.nextcloud.com/) exists to help you getting general problems solved. Next time please raise this kind of question in the forum first 😉

**Closed by j-ed** 2021-03-17 08:53 UTC
Labels: 0. Needs triage, bug
