### ISSUE TITLE
Showing trashbin and versions file use in the quota

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#14645] opened 2019-03-12 15:20 UTC
It could be nice to have an overview of the total size used by the trashbin and the versions so we can know when these files will be deleted once the total user quota is used.

We could show it directly in the quota bar by adding two more colours and showing a tooltip detailing what is what?

![Capture d’écran_2019-03-12_16-19-30](https://user-images.githubusercontent.com/14975046/54212049-a3a04c80-44e2-11e9-9c7c-e5fb60e4e93e.png)

@nextcloud/designers @jancborchardt

**Comment by jancborchardt** [comment] 2019-03-12 16:47
Not sure if that information is important? It’s entirely under the hood and automatic, so I don’t think we necessarily need to communicate that. Versions and trash is not your actual data.

Other platforms e.g. differentiate, but between actual data, like Files, Photos, Mails, Videos, etc.

**Comment by MorrisJobke** [comment] 2019-03-12 17:24
> Not sure if that information is important? It’s entirely under the hood and automatic, so I don’t think we necessarily need to communicate that. Versions and trash is not your actual data.

Yep - I had the same thoughts 👍

**Comment by Maurotb** [comment] 2019-07-12 06:58
I'm also looking for a solution to this problem, it would be useful for us to have the data on the space used, the trash and the versions per user and for the server in total.
It would also be useful to be able to decide whether these values ​​are included in the quota calculation.
It is true that the trash and the versions are managed automatically, but it is a request that is continually made to me to be able to see them to plan for possible upgrades.

**Comment by enoch85** [comment] 2019-07-12 07:29
I would argue that it is important to get feedback in the UI how much space is used in total. If the space on the physical disk reaches max and fills out, that could lead to that it won't boot if you restart the server. Showing the *total* used space inside Nextcloud would mean one step less for the sysadmin. In other words, it would be convinient not having to check the backend system it's run on to see that actual space used by Nextcloud. 

Then on the other hand, you shouldn't setup your system in such a way that the main drive fills up and could cause the above error. It's sorted in the VM, but I'm not sure about the snap?

**Comment by jancborchardt** [comment] 2019-07-15 15:37
> It would also be useful to be able to decide whether these values ​​are included in the quota calculation.

They are not. :)

>  It is true that the trash and the versions are managed automatically, but it is a request that is continually made to me to be able to see them to plan for possible upgrades.

Right, so you mean for admins, and not for users.

> Gdrive and all other system, calculate this data...

Can you show screenshots of how Gdrive and other systems do this?

**Comment by Maurotb** [comment] 2019-07-15 15:49
> They are not. :)
It depends on your point of view ;)
Until you work with little data and small files ok, but if you work with big files or lots of files it's useful 
i think. 
Furthermore, by not calculating this data in the quota, a user has the possibility of block the system due to space exhaustion if he wants...

>Right, so you mean for admins, and not for users.
Yes, i think it is enough to make sure that we can decide whether to include the trash and the versions in the space calculation (and consequently in the quota)

>@Maurotb Can you show screenshots of how Gdrive and other systems do this?

See this link
https://support.google.com/drive/answer/6374270?hl=en

If you have a full space in gdrive,
OPTION 1: Clear space
Put files you don't want in your trash, then permanently delete them. Learn how to delete files.

Trash is calculated in gdrive quota...

**Comment by Maurotb** [comment] 2019-10-05 16:01
Hi, any news for this?

**Comment by jancborchardt** [comment] 2019-10-14 21:11
No, currently no plans for this.

> Trash is calculated in gdrive quota

This is the crucial point. Trash is calculated in the quota of Google Drive, so they need to put it into this quota bar. And they calculate it cause they want to sell more storage space to you. ;)

We don’t calculate the trash into the quota, so we don’t need to visualize it.


-------


As also confirmed by @MorrisJobke above, I would close this.

**Closed by jancborchardt** 2019-10-14 21:11 UTC
Labels: 0. Needs triage, enhancement, feature: trashbin, feature: versions
