### ISSUE TITLE
Nextcloud 17.0.1 Login Loop

### ISSUE THREAD

**Issue by CountOmega** [nextcloud/server#17970] opened 2019-11-16 22:13 UTC
### Steps to reproduce
1. Fresh install of NC 17 with php-7.3 amd Apache 2.4.41 on Ubuntu 18.04
2. Intial setup worked
3. Logging in today resulted in the login loop

```
sudo -u www-data php occ app:list

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.8.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - maps: 0.1.2
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - unsplash: 1.1.4
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.68:880"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwritehost": "192.168.178.68:880",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwriteprotocol": "http",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable"
```

### Client configuration
**Browser:**
Firefox 70.0.1
**Operating system:**
Windows 10

**Comment by kesselb** [comment] 2019-11-16 22:56
Logs? Is your session directory writeable?

**Comment by CountOmega** [comment] 2019-11-17 13:21
Strangely, my nextcloud.log is completely empty.

**Comment by CountOmega** [comment] 2019-11-20 12:10
`ls -fl /var/www/nextcloud/
total 164
-rw-r--r--  1 www-data www-data 12063 Nov  7 12:04 AUTHORS
-rw-r--r--  1 www-data www-data   362 Nov  7 12:08 version.php
-rw-r--r--  1 www-data www-data  5139 Nov  7 12:04 remote.php
-rw-r--r--  1 www-data www-data   156 Nov  7 12:04 index.html
-rw-r--r--  1 www-data www-data   101 Nov  7 12:04 .user.ini
drwxr-xr-x 15 www-data www-data  4096 Nov 16 21:43 .
drwxr-xr-x 33 www-data www-data  4096 Nov  7 12:08 3rdparty
drwxr-xr-x 23 www-data www-data  4096 Nov  7 12:08 core
-rw-r--r--  1 www-data www-data   283 Nov  7 12:04 occ
-rw-r--r--  1 www-data www-data  2951 Nov  7 12:04 public.php
drwxr-xr-x  4 root     root      4096 Nov 10 20:49 ..
-rw-r--r--  1 www-data www-data  2287 Nov  7 12:04 status.php
drwxr-xr-x 13 www-data www-data  4096 Nov  7 12:08 settings
drwxr-xr-x  2 www-data www-data  4096 Nov  7 12:04 ocm-provider
drwxr-xr-x  4 www-data www-data  4096 Nov  7 12:04 resources
drwxr-xr-x  6 www-data www-data  4096 Nov  7 12:04 lib
drwxr-xr-x  2 www-data www-data  4096 Nov 16 22:12 data
drwxr-xr-x  2 www-data www-data  4096 Nov  7 12:04 ocs
-rw-r--r--  1 www-data www-data 34520 Nov  7 12:04 COPYING
-rw-r--r--  1 www-data www-data    26 Nov  7 12:04 robots.txt
-rw-r--r--  1 www-data www-data  3805 Nov  7 12:04 console.php
drwxr-xr-x 47 www-data www-data  4096 Nov 11 13:14 apps
drwxr-xr-x  2 www-data www-data  4096 Nov 16 22:08 config
drwxr-xr-x  2 www-data www-data  4096 Nov  7 12:04 ocs-provider
drwxr-xr-x  2 www-data www-data  4096 Nov  7 12:05 updater
-rw-r--r--  1 www-data www-data  3737 Nov 11 20:04 .htaccess
drwxr-xr-x  3 www-data www-data  4096 Nov  7 12:04 themes
-rw-r--r--  1 www-data www-data  3172 Nov  7 12:04 index.php
-rw-r--r--  1 www-data www-data  4993 Nov  7 12:04 cron.php`

hope this helps.

**Comment by j-ed** [comment] 2019-11-20 12:36
Have you tried to enable the debug logging by setting "`'loglevel' => 0,`"?

**Comment by CountOmega** [comment] 2019-11-20 15:56
No, I haven't. I'll give it a look as soon as I can.

**Comment by A1pen** [comment] 2019-11-28 17:13
Hi @ all,
i have the same issue after upgrade to NC 17.01
Running NC on CentOS-7, php-7.2, Nginx, and Postres.

I`ve  already tryed out the whole maintenance stuff:
```
maintenance:mimetype:update-db
maintenance:mimetype:update-js
maintenance:repair
maintenance:theme:update
```

Log says ('loglevel' => '0'):
```
{"reqId":"6WAboQ4jVR7Z0roWP20q","level":0,"time":"November 28, 2019 16:30:45","remoteAddr":"94.134.88.123","user":"--","app":"core","method":"GET","url":"\/apps\/files\/","message":{"Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotLoggedInException","Message":"Current user is not logged in","Code":401,"Trace":[{"file":"\/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/Middleware\/MiddlewareDispatcher.php","line":95,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":98,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\ViewController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files.view.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"files.view.index"}]},{"file":"\/var\/www\/nextcloud\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"files.view.index"}]},{"file":"\/var\/www\/nextcloud\/html\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/"]},{"file":"\/var\/www\/nextcloud\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/html\/lib\/private\/AppFramework\/Middleware\/Security\/SecurityMiddleware.php","Line":135,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
{"reqId":"DSGDYwHSYkaHuCm5aOuU","level":0,"time":"November 28, 2019 16:30:45","remoteAddr":"94.134.88.123","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OCA\\DAV\\BackgroundJob\\UploadCleanup job with ID 936","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
{"reqId":"DSGDYwHSYkaHuCm5aOuU","level":0,"time":"November 28, 2019 16:30:46","remoteAddr":"94.134.88.123","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\DAV\\BackgroundJob\\UploadCleanup job with ID 936 in 1 seconds","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
```
Webconsole says:
```
JQMIGRATE: Migrate is installed, version 1.4.1 (jquery-migrate.min.js:2:551)
Could not find initial state loginErrors of core (initialstate.js:31:10)
Could not find initial state loginMessages of core (initialstate.js:31:10)
Could not find initial state resetPasswordTarget of core (initialstate.js:31:10)
Could not find initial state resetPasswordUser of core (initialstate.js:31:10)
```

**Comment by kesselb** [comment] 2019-11-28 17:26
@A1pen https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by A1pen** [comment] 2019-11-28 18:07
Sorry didn't see this nice little template, I've updated my post.

**Comment by j-ed** [comment] 2019-11-28 18:29
I would assume that the problem is most likely caused by a configuration issue. Have you checked the Nextcloud help forum for any solution? Similar problems have been addressed and answered there in the past:

https://help.nextcloud.com/search?q=login%20loop

**Comment by A1pen** [comment] 2019-11-29 11:22
Hi @j-ed ,
thanks for the link, this [post](https://help.nextcloud.com/t/nextcloud-16-0-1-login-loop-on-install/53959) solved my issue. After php upgrade some folders had group set to apache rather than nginx.
I figured out this directories by firing up a find to the whole system:
`find / -group apache -type d -name "*"`

In my case, the group on `/var/opt/rh/rh-php72/lib/php/session` was incorrectly assigned.

Thanks again! =)

**Comment by j-ed** [comment] 2019-11-29 11:25
@A1pen Fine, please don't forget to close this issue ticket 😉

**Comment by A1pen** [comment] 2019-11-29 11:28
I can't close this issue, the original author was @CountOmega.
Maybe this will also solve the problem for @CountOmega?

BR

**Comment by CountOmega** [comment] 2019-11-29 20:00
For me, the command had to be altered to `find / -group www-data -type d -name "*". What permission do the php directories need?

**Comment by A1pen** [comment] 2019-12-01 22:26
If you are using Apache the directories should have the group www-data, for nginx it should be nginx

**Comment by CountOmega** [comment] 2019-12-02 08:18
Sorry if if didn't express this right. The command above shows me the desired directories. The question is which need www-data ownership and which not. 

Maybe this should also be included in the nextcloud docs for better debugging.

**Comment by kesselb** [comment] 2019-12-02 10:49
> Is your session directory writeable?

This one needs to be writeable by the webserver / php user. Check `session.save_path` with your php configuration (php.ini most likely).

**Closed** 2019-12-06 19:54 UTC
Labels: 0. Needs triage, bug, needs info
