### ISSUE TITLE
Missing flow options "File is uploaded" and "File is located"

### ISSUE THREAD

**Issue by loxK** [nextcloud/server#24426] opened 2020-11-28 03:20 UTC
### Steps to reproduce
1. create a new flow
2. look for "File is uploaded" and "File is located" options as per [the official NexCloud page about the flow feature](https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/)
3. keep searching the options are missing

### Expected behaviour
A screenshot from [the official NexCloud page about the flow feature]

![image](https://user-images.githubusercontent.com/136687/100492797-f53fad80-3183-11eb-855b-55f4816837ac.png)

### Actual behaviour
The options are missing

### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud version:**
19.0.5
**Updated from an older Nextcloud**

**Comment by kesselb** [comment] 2020-11-28 10:53
Duplicate of https://github.com/nextcloud/server/issues/19810

**Closed by kesselb** 2020-11-28 10:53 UTC
Labels: 0. Needs triage, bug
