### ISSUE TITLE
Upgrade from 19.0.4.2 to 20.0.1.1 fails with unhandled exception

### ISSUE THREAD

**Issue by ntlspck** [nextcloud/server#23793] opened 2020-10-30 11:53 UTC
### Steps to reproduce
1. Update docker nextcloud:19 to nextcloud:20
2. Update fails with unhandled exception for mail app
3. Disabled mail app via terminal: "php occ app:disable mail"
4. Disalbled maintenance mode via terminal: php occ maintenance:mode --off
5. Successfully proceed with Update process.

### Expected behaviour
Upgrade from 19 to 20 should not fail with unhandled exception for mail app. Unfortunately I don't know if the error is caused by mail app itself or by the server's upgrade process.

### Actual behaviour
Upgrade failed with unhandled exception
```
Update app mail from appstore
An unhandled exception has been thrown:
Error: Class 'OCA\Mail\AppInfo\BootstrapSingleton' not found in /var/www/html/custom_apps/mail/lib/AppInfo/Application.php:35
Stack trace:
#0 /var/www/html/lib/private/ServerContainer.php(108): OCA\Mail\AppInfo\Application->__construct()
#1 /var/www/html/lib/private/ServerContainer.php(171): OC\ServerContainer->getAppContainer('mail', 'Mail')
#2 /var/www/html/lib/private/ServerContainer.php(138): OC\ServerContainer->getAppContainerForService('OCA\\Mail\\Migrat...')
#3 /var/www/html/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query('OCA\\Mail\\Migrat...')
#4 /var/www/html/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance('1050Date2020062...')
#5 /var/www/html/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('1050Date2020062...', false)
#6 /var/www/html/lib/private/legacy/OC_App.php(976): OC\DB\MigrationService->migrate()
#7 /var/www/html/lib/private/Installer.php(206): OC_App::updateApp('mail')
#8 /var/www/html/lib/private/Updater.php(452): OC\Installer->updateAppstoreApp('mail')
#9 /var/www/html/lib/private/Updater.php(260): OC\Updater->upgradeAppStoreApps(Array)
#10 /var/www/html/lib/private/Updater.php(130): OC\Updater->doUpgrade('20.0.1.1', '19.0.4.2')
#11 /var/www/html/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#12 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/console.php(100): OC\Console\Application->run()
#18 /var/www/html/occ(11): require_once('/var/www/html/c...')
#19 {main}    0/0 [->--------------------------]   0%2020-10-30 10:35:30,319 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.

```

### Server configuration

**Operating system:**
Linux 4.19.97-v7l+ armv7l

**Web server:**
Apache

**Database:**
Type: pgsql
Version: PostgreSQL 12.4 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 9.3.0) 9.3.0, 32-bit
Size: 108,4 MB

**PHP version:**
Version: 7.4.12
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 2 MB

**Nextcloud version:** 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**  from 19.0.4.2 to 20.0.1.1

**Where did you install Nextcloud from:** docker image nextcloud:19 / nextcloud:20

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - carnet: 0.22.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - deck: 1.1.2
  - event_update_notification: 1.1.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - news: 15.0.6
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.5
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - unsplash: 1.1.7
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - mail
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true,
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "calendar"
        ]
    }
}

```
</details>

**Are you using external storage: no

**Are you using encryption:** no

**Are you using an external user-backend: no

### Client configuration
**Browser:** Firefox 82.0.2

**Operating system:** Manjaro Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment] 2020-10-30 15:33
Duplicate of https://github.com/nextcloud/mail/issues/3727

**Closed by ChristophWurst** 2020-10-30 15:33 UTC
Labels: 0. Needs triage, bug
