### ISSUE TITLE
clicking on an event in activity view does not load event in sidebar

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#23879] opened 2020-11-03 22:23 UTC
### Steps to reproduce
1. have a shared calendar (shared by user A)
2. user B creates event in that calendar
3. user C sees this change via activity app, clicks on the title of the event in activity app, gets redirected to calendar

### Expected behaviour
the event gets opened in sidebar
(this works when I click on an event name of an event that I created in my own personal calendar, but not in the situation described above)

### Actual behaviour
the sidebar shows loading icons forever

### Server configuration
**Nextcloud version:** 19.0.4

I am not hosting this server myself so I don't know most of the things from the template. But if you need something specific I can find out.

**Comment by szaimen** [comment] 2021-06-17 17:25
I can reproduce this on NC21.0.2
and get this error mesage in the browser log:
![image](https://user-images.githubusercontent.com/42591237/122445288-b3504a80-cfa1-11eb-8467-94fe54edb120.png)

---

cc @nextcloud/calendar does this need to be fixed in the server or calendar repository?

**Comment by tcitworld** [comment] 2021-06-17 17:49
I'd say server, because the URLs to the event might not be properly constructed when shared.

That's happening in https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Activity/Provider/Event.php#L99

**Comment by szaimen** [comment] 2023-01-23 10:26
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by alexanderdd** [comment] 2023-02-01 01:17
works as expected in 24.0.7

thanks!

**Comment by hrenard** [comment] 2023-08-03 12:18
We're still observing this issue in **25.0.9** for shared calendars.

The base64 encoded URI is not same in the link of the activity or when actually navigating to the event.

In the activity the link is :
`/remote.php/dav/calendars/<CAL_OWNER>/<CAL_NAME>/<CAL_ID>.ics`

But in the calendar app the URI is :
`/remote.php/dav/calendars/<USER>/<CAL_NAME>_shared_by_<CAL_OWNER>/<CAL_ID>.ics`

I'm not sure if both are intended to work or if the first one is obsolete.

Can someone re-open this issue ? Or should I open a new one ?

**Comment by SebastianKrupinski** [comment] 2024-07-02 10:23
Tested in version 30. Works Correctly.

Was able to open event from activity app created by User B as User C. Tested with User C having read only and read/write permissions.

**Closed by SebastianKrupinski** 2024-07-02 10:23 UTC
Labels: bug, feature: dav, 0. Needs triage, feature: activity and notification, feature: caldav, 25-feedback
