### ISSUE TITLE
back button doesn't work in browser

### ISSUE THREAD

**Issue by justasomeone** [nextcloud/server#17769] opened 2019-10-31 22:18 UTC
Hey sorry if this has been posted already..

Steps to reproduce
Log in Nextcloud using Chrome/Firefox
Go into any folder in the server, and then press 'Back' to go back to the previous folder
Nothing happens unless you reload the page.

Actual behaviour
Link changes, but page doesn't

Nextcloud 17.

**Comment by szaimen** [comment] 2021-06-07 16:57
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 16:57 UTC
Labels: 0. Needs triage, bug
