### ISSUE TITLE
Thumbnail view doesn't work when filtering with a tag

### ISSUE THREAD

**Issue by mattdev44** [nextcloud/server#20491] opened 2020-04-15 03:38 UTC
### Steps to reproduce
1. Filter by a Tag
2. Try to click on the "Toggle Grid View" icon
3. View doesn't change like it does when you are looking in a folder.

### Expected behaviour
Same behavior as when looking in a folder

### Actual behaviour
View does not change

### Server configuration

**Operating system:**
Raspbian

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
No Idea.

**Nextcloud version:** (see Nextcloud admin page)
16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
NextCloudPi version	v1.24.2

**Comment by szaimen** [comment] 2021-06-07 16:40
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 16:40 UTC
Labels: 0. Needs triage, bug
