### ISSUE TITLE
Lose Admin icon on Top Line

### ISSUE THREAD

**Issue by reset12** [nextcloud/server#7535] opened 2017-12-15 15:03 UTC
Hello,
i lose the Icon to come into Admin from the top line after upgrade from 12.0.3 to 13.0 beta3.

I must make the update with sudo -u www-data php updater.phar, because the online-Updater
never worked for me.

I use ubuntu 16.04 on Odroid XU3, with nginx as webserver
PHP 7.0.22-0ubuntu0.16.04.1
mysql  Ver 14.14 Distrib 5.7.20, for Linux (armv7l) using  EditLine wrapper

Another problem i have is that the date-format is wrong, but this was also in  version before, the date is displayed in US-Format and i use German format on my computer, but not all dates in contacts have this wrong format, most are in german-date format.

I have only contact and calendar additional active.

with regards
Bruno

![date](https://user-images.githubusercontent.com/14790813/34047673-4abbb748-e1b1-11e7-9262-d7faebd5bb4a.png)
![screenshot](https://user-images.githubusercontent.com/14790813/34047685-4fdd0902-e1b1-11e7-9dc8-7f80c4ae07b9.png)

**Comment by MorrisJobke** [comment] 2017-12-15 15:07
> i lose the Icon to come into Admin from the top line after upgrade from 12.0.3 to 13.0 beta3.

Press the little avatar in the top right to reveal the menu. cc @nextcloud/designers for UX problems ;)



> Another problem i have is that the date-format is wrong, but this was also in version before, the date is displayed in US-Format and i use German format on my computer, but not all dates in contacts have this wrong format, most are in german-date format.

This one is a duplicate of #1781 with a potential fix in #5623.

**Comment by jancborchardt** [comment] 2017-12-15 15:39
@MorrisJobke @nextcloud/designers there you go – this was one of the reasons I preferred having the icon-settings on the top right initially. For people who just set up their Nextcloud, it is unmistakeably »Settings«. If it’s the avatar placeholder, it needs some thinking.

I’ll reopen this cause this is a problem I didn’t consider when commenting at https://github.com/nextcloud/server/pull/6876#issuecomment-350883918

**Comment by joekerna** [comment] 2017-12-18 09:36
Is this a duplicate of #7508 ?

**Comment by reset12** [comment] 2017-12-18 12:01
Yes.

with regards
Bruno

On Mon, 18 Dec 2017 09:36:55 +0000 (UTC)
joekerna <notifications@github.com> wrote:

> Is this a duplicate of #7508 ?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nextcloud/server/issues/7535#issuecomment-352373325


-- 
reset12@gmx.net <reset12@gmx.net>

**Comment by pixelipo** [comment] 2017-12-18 12:48
Doesn't seem to be a duplicate. That issue is about avatar not generating. This is about avatar not being understood as a "gear" (settings) icon.

**Comment by jancborchardt** [comment] 2018-01-05 17:19
So @rullzer could we roll back that part of #6876 so it's a gear again in the top right when no avatar is set?

**Comment by skjnldsv** [comment] 2018-01-05 17:58
I'll suggest adding a quick triangle down instead. I'm not for the return of the gear! :)

**Comment by rullzer** [comment] 2018-01-05 18:19
@jancborchardt it is all or nothing here. Either we generate avatars for everything. Or we only show avatars when users upload them.

But note that if we revert that:
* You won't always have avatars on
  - Android
  - IOS
  - Desktop
* You won't have avatars in comments in Collabora
  - or other apps that just request the avatar

Also I argue... (as @MariusBluem pointed out). If people can figure it out at dropbox and Microsoft. They can probably also figure it out here.. But maybe the triangle is a good compromise.

**Comment by jancborchardt** [comment] 2018-01-05 22:33
Well I'm not for the return of the triangle. ;D

So let's close this. If there are issues in the future, we could handle this in the frontend via CSS so that the avatar placeholder is replaced by the gear icon.

**Closed** 2018-01-05 22:33 UTC
Labels: 1. to develop, bug, design, papercut, regression
