### ISSUE TITLE
Organizer in email invitation is an email address instead of full name when created on Android

### ISSUE THREAD

**Issue by dgsiegel** [nextcloud/server#17399] opened 2019-10-03 21:27 UTC
### Steps to reproduce
1. Create a new event on Android, invite other contacts to that event
2. Sync it with DAVx5
3. Invite Email will be sent, but organizer is only an email address instead of full name

### Expected behaviour

When creating a new event inside Nextcloud and inviting other people to it, the email will show the full name instead of just the email address.

### Actual behaviour

Email address instead of full name will be shown.

### Server configuration

**Operating system**: Android

**Web server:** lighttpd/1.4.53 (cgi-fcgi)

**Database:** sqlite3 3.27.2

**PHP version:** 7.3.9-1~deb10u1

**Server version:** (see your admin page) 16.0.5 - 16.0.5.1

**Calendar version:** (see the apps page)  1.7.1

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

``` Enabled: - accessibility: 1.2.0 - activity: 2.9.1 - admin_audit: 1.6.0 - bookmarks: 2.1.1 - bruteforcesettings: 1.4.0 - calendar: 1.7.1 - cloud_federation_api: 0.2.0 - comments: 1.6.0 - contacts: 3.1.3 - dav: 1.9.2 - federatedfilesharing: 1.6.0 - federation: 1.6.0 - files: 1.11.0 - files_pdfviewer: 1.5.0 - files_rightclick: 0.15.1 - files_sharing: 1.8.0 - files_texteditor: 2.8.0 - files_trashbin: 1.6.0 - files_versions: 1.9.0 - firstrunwizard: 2.5.0 - gallery: 18.3.0 - issuetemplate: 0.5.0 - logreader: 2.1.0 - lookup_server_connector: 1.4.0 - nextcloud_announcements: 1.5.0 - notes: 3.0.3 - notifications: 2.4.1 - oauth2: 1.4.2 - password_policy: 1.6.0 - privacy: 1.0.0 - provisioning_api: 1.6.0 - serverinfo: 1.6.0 - sharebymail: 1.6.0 - text: 1.0.2 - theming: 1.7.0 - twofactor_backupcodes: 1.5.0 - updatenotification: 1.6.0 - viewer: 1.1.0 - workflowengine: 1.6.0 Disabled: - encryption - files_external - files_videoplayer - recommendations - support - survey_client - systemtags - user_ldap ```

**Nextcloud configuration:**

``` { "instanceid": "***REMOVED SENSITIVE VALUE***", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "datadirectory": "***REMOVED SENSITIVE VALUE***", "dbtype": "sqlite3", "version": "16.0.5.1", "installed": true, "forcessl": true, "theme": "", "loglevel": 2, "maintenance": false, "trusted_domains": [ "cloud.nopln.org" ], "mail_smtpmode": "smtp", "secret": "***REMOVED SENSITIVE VALUE***", "trashbin_retention_obligation": "auto, 45", "appstore.experimental.enabled": false, "updater.release.channel": "stable", "mail_from_address": "***REMOVED SENSITIVE VALUE***", "mail_domain": "***REMOVED SENSITIVE VALUE***", "overwrite.cli.url": "https:\/\/cloud.nopln.org", "mail_smtphost": "***REMOVED SENSITIVE VALUE***", "app_install_overwrite": [ "calendar" ], "updater.secret": "***REMOVED SENSITIVE VALUE***" } ```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

### Client configuration
**Browser:** None

**Operating system:** Android

**CalDAV-clients:** DAVx5

**Comment by tcitworld** [comment] 2019-10-04 07:16
Beginning with Nextcloud 9 the CalDAV server became part of Nextcloud's server and the calendar app is just a CalDAV client running in your browser.

I moved the issue to the server repo.

The senderName is defined this way: https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L166

So I'm guessing the Android Calendar only gives an email for the `ORGANIZER` value. Maybe we should match against Nextcloud user database to get the user's name in case we only have the email through IMip. @georgehrke ?

**Comment by georgehrke** [comment] 2019-10-04 08:17
Duplicate of https://github.com/nextcloud/server/issues/13896

**Comment by georgehrke** [comment] 2019-10-04 08:17
> Maybe we should match against Nextcloud user database to get the user's name in case we only have the email through IMip.

Yes, that's exactly what we should do :)

**Closed by georgehrke** 2019-10-04 08:17 UTC
Labels: bug, feature: dav

**Comment by tcitworld** [comment] 2019-10-04 08:50
Ha ha I felt like my idea was somehow not so original. 😛
