### ISSUE TITLE
Migration instruction fools admins to upgrade to incompatible owncloud before migration

### ISSUE THREAD

**Issue by Morganlej** [nextcloud/server#5426] opened 2017-06-15 13:23 UTC
This issue below is cloned from closed nextcloud/nextcloud.com#496 , so for a couple comments see there first.

It have happened with earlier versions and now happen again [1]. In short:
Instruction say latest pint releases should be used, so admin upgrades ownCloud 9.1.5 to 9.1.6.
Then he tries to migrate to Nextcloud 10.0.5, which fails with:
"Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.6.2 to 9.1.5.2)" [2]

That is what happens when we follow the instruction. https://nextcloud.com/migration/
The needed Nextcloud 10.0.6 is available "when it is done", so what the admin should have done was NOT upgrade ownCloud to last point release, but instead upgrade ownCloud to the point release that corresponds to the last point release of available Nextcloud, before migrating to Nextcloud.
 
[1] https://help.nextcloud.com/t/migration-from-owncloud-9-1-6-to-nextcloud-10-0-5-fails/13523
[2] That error message could use a bit more text to explain that it cryptically express itself (10.0.5) like owncloud numbering as "9.1.5.2" but that is a sidenote here...

**Comment by MorrisJobke** [comment] 2017-07-18 08:32
cc @nickvergessen

**Comment by jospoortvliet** [comment] 2017-07-18 08:41
This needs https://github.com/nextcloud/owncloud-web-migrator/pull/2 to be finished and merged.

**Comment by nickvergessen** [comment] 2017-07-18 08:57
Duplicate of https://github.com/nextcloud/server/issues/5425#issuecomment-315995759

**Closed by nickvergessen** 2017-07-18 08:57 UTC
Labels: 0. Needs triage, feature: owncloud migration
