### ISSUE TITLE
Cannot change permissions for second circle if folder is shared with two circles

### ISSUE THREAD

**Issue by c4539** [nextcloud/server#7623] opened 2017-12-25 12:47 UTC
### Steps to reproduce
1. Share a folder with a circle
2. Share the same folder with another cirle
3. Change the permission for the second circle (i.e. remove the tick from the "can edit" checkbox)

### Expected behaviour
The checkbox for the second circle gets unchecked.

### Actual behaviour
The checkbox for the first circle gets unchecked.

## Server configuration detail

**Operating system:** Linux 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 5.7.20

**PHP version:** 7.0.22-0ubuntu0.17.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older ownCloud

**Where did you install Nextcloud from:** zip from nextcloud.com

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - checksum: 0.3.5
 - circles: 0.13.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.3
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - user_external: 0.4
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - keeweb
 - notes
 - survey_client

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Operating system:** Windows 10

**Comment by MorrisJobke** [comment] 2018-01-02 08:31
cc @nextcloud/sharing @daita

**Comment by daita** [comment] 2018-01-02 10:14
were not able to reproduce; can you provide more information related to the Circles you're creating ? (types, names, ...)

**Comment by c4539** [comment] 2018-01-02 16:39
Hi @daita , both circles are secret circles, one is called "Familie P***" and the other "Familie M***".
I just realized that the tooltip is equal (both sharees show "Familie" when I hover them), which made me looking into the HTML source: both checkboxes have the same id
`<input id="canEdit-view25-Familie" type="checkbox" name="edit" class="permissions checkbox" checked="checked">`

**Comment by daita** [comment] 2018-01-02 19:11
[It is a known bug](https://github.com/nextcloud/circles/issues/78)
Written as fixed in NC13, but I don't think the PR was included before the feature freeze.

**Closed by daita** 2018-01-02 19:11 UTC
Labels: bug, feature: sharing, needs info
