### ISSUE TITLE
413 Error only on public folder when uploading >100MB file and using Cloudflare Proxy

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [nextcloud/server#29992] opened 2021-11-30 19:19 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Summary
While researching this issue I came to understand that Nextcloud will chunk files to the correct size when needed. This is why you can use Nextcloud when logged in and the domain is behind a Cloudflare proxy. 

However, it appears that this may not be happening on public shared links as any file larger than 100 MB ([the Cloudflare Free plan size limit for uploads](https://developers.cloudflare.com/cache/about/default-cache-behavior#customization-options-and-limitations)) will fail. 

These same files will upload just find behind the same domain when logged in and uploading to the same shared folder.

### Steps to reproduce
1. Use domain behind Cloudflare proxy free plan (this enforces 100 MB upload limit)
2. Create shared folder to upload to (either File Drop or Allow Upload/Editing)
3. Attempt to upload a file 100 MB or smaller leads to success
4. Attempt to upload a file larger than 100 MB leads to 413 error
5. File larger than 100 MB can be successfully uploaded to Nextcloud folder when logged in (aka not using public link)

### Expected behaviour
Nextcloud to successfully upload files to public shared folders if it will let me upload them to that same folder when logged in

### Actual behaviour
A 413 error is thrown by Cloudflare when uploading files larger than 100 MB. Seemingly a result of the file not being chunked by Nextcloud.

### Server configuration

**Operating system:** Linux 5.10.28-Unraid x86_64

**Web server:**

**Database:** mysql

**PHP version:** 7.4.26

**Nextcloud version:** 23.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** [LSIO Docker Container](https://hub.docker.com/r/linuxserver/nextcloud)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - calendar: 3.0.0
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.6
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Replaced domain name with '**DOMAIN**'

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.10:446",
            "data.**DOMAIN**.com"
        ],
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "overwrite.cli.url": "https:\/\/data.**DOMAIN**.com",
        "overwritehost": "data.**DOMAIN**.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 96.0.4664.45

**Operating system:** Windows 10

**Comment by acsfer** [comment] 2021-12-01 08:16
Duplicate of https://github.com/nextcloud/server/issues/4109

**Closed by acsfer** 2021-12-01 08:16 UTC
Labels: bug, 0. Needs triage

**Comment by nooblag** [comment] 2022-12-13 13:53
Just a friendly bump on this, as the issue prevents a core use of my instance: public uploads of large data files and rendered video sets.

**Comment by qaqland** [comment] 2023-12-12 06:56
> To fix the “413 Request Entity Too Large” issue when uploading a 140MB file via Cloudflare API, you need to upgrade your plan. Free and Pro plans support a maximum file upload size of 100MB. Business plans support up to 200MB, and Enterprise plans support up to 500MB by default. For a higher limit, Enterprise customers can contact Cloudflare Customer Support.

https://community.cloudflare.com/t/request-entity-too-large-413/509332

**Comment by nooblag** [comment] 2023-12-17 02:18
Thanks, would love to pay for the higher limit in the [absence of chunked file upload being available inside Nextcloud](https://github.com/nextcloud/server/issues/4109) (that would make this issue redundant), but I can't afford those plans, hence why running own server and using open source software like Nextcloud. ;)
