### ISSUE TITLE
[others with access] Sharee can click link to unaccessible level

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18716] opened 2020-01-07 13:09 UTC
![image](https://user-images.githubusercontent.com/1804221/71895986-cf1bb400-3152-11ea-87d5-38a9af017a6f.png)

### Steps to reproduce
1. Henri is the owner of _Clubs_
2. Henri shares _Clubs_ with Peter (with resharing permissions)
3. Henri shares _Kreuzberg_ with Simon (with resharing permissions)
4. Peter and Simon accept the shares
5. Folder _Clubs_ appears on Peter's root level
6. Folder _Kreuzberg_ appears on Simon's root level
7. Peter opens the list of _others with access_ on _Lido_
8. Peter sees Simon in the list
9. Peter clicks on "Via folder" in the ... menu behind Simon
10. Folder _Kreuzberg_ opens
11. Simon opens the list of _others with access_ on _Lido_
12. Simon sees Peter in the list

### Expected behaviour
- Simon sees Peter in the list of _others with access_
- In the ... menu behind Peter, Simon sees only "Added by Henri"

### Actual behaviour
- In the ... menu behind Peter, Simon also sees "Via folder"
- Click on "Via folder" navigates Simon to a folder ID Simon has no access rights to

![image](https://user-images.githubusercontent.com/1804221/71897386-bad9b600-3156-11ea-9981-5bbd82d00a30.png)

**Comment by rullzer** [comment] 2020-01-09 19:23
Yeah well. This is not so trivial to fix. Because it is very costly to check for every other user that has access if you have access to that folder.

**Comment by daita** [comment] 2020-01-10 08:59
Can't we just generate the link only to the owner of the file/share ?
I mean, if you can't interact with the shares' right, why would you need to navigate in the folders ?

**Comment by rullzer** [comment] 2020-01-10 09:04
The problem is that we need to find out for each of the entries if we can reach it. But lets see.

**Comment by wiswedel** [comment] 2020-01-10 09:06
>  I mean, if you can't interact with the shares' right, why would you need to navigate in the folders ?

Good point. I like the suggestion.

> The problem is that we need to find out for each of the entries if we can reach it. But lets see.

The owner _can_ reach it. We'll just have to find out if the one looking at it is the owner or not - and if yes show the link.

**Comment by rullzer** [comment] 2020-01-10 09:08
So only the owner of the share has to be able to navigate? That is easy.

Note that the owner of the share is the owner of the root node. Not the one that initiated the share.

In the case you describe only `Henri` will then be able to navigate.

**Comment by wiswedel** [comment] 2020-01-10 09:25
It's basically the same condition that shows or hides the _unshare_ button in the same context menu.

**Comment by wiswedel** [comment] 2020-01-10 10:11
> It's basically the same condition that shows or hides the _unshare_ button in the same context menu.

https://github.com/nextcloud/server/blob/4b28da1dd9a6acf4f04b69474f18ce883323caa3/apps/files_sharing/src/components/SharingEntryInherited.vue#L38-L47

**Comment by rullzer** [comment] 2020-01-10 10:22
> > It's basically the same condition that shows or hides the _unshare_ button in the same context menu.
> 
> https://github.com/nextcloud/server/blob/4b28da1dd9a6acf4f04b69474f18ce883323caa3/apps/files_sharing/src/components/SharingEntryInherited.vue#L38-L47

Ok that I can do.
I was under the impression you still wanted the button but to only lead to folders you had access to.

PR will be incomming.

**Closed** 2020-01-15 08:11 UTC
Labels: 0. Needs triage, 18-feedback, bug
