### ISSUE TITLE
Move multiple files to another folder (feature request)

### ISSUE THREAD

**Issue by scus1** [nextcloud/server#6330] opened 2017-09-01 08:44 UTC
### Steps to reproduce
1. Select multiple files in a folder, say /photos

### Expected behaviour
There should be a button to move all selected files. This button should have the same behavior as the move command for a single file: a pop-up to select the destination. Optimally, there should be a possibility to create a new folder in this pop-up.

### Actual behaviour
There is only a button to download or to delete all the selected files.

I'am aware that I can drag and drop multiple files, but I didn't manage to move files from /photos to /pictures in one step.

I think the server and client specs aren't necessary, as this is not a bug, but a feature request. However, I am happy to post them if needed.

**Comment by MorrisJobke** [comment] 2017-09-01 13:49
Duplicate of #2779

Fixed for 13 in #6273

**Closed by MorrisJobke** 2017-09-01 13:49 UTC
