### ISSUE TITLE
Server can't handle Hash (#) in username

### ISSUE THREAD

**Issue by joendres** [nextcloud/server#30355] opened 2021-12-20 21:52 UTC
### Steps to reproduce
1. Activate App "SSO & SAML authentication" (but the bug seems to be in the server)
2. Configure AzureAD as the auth backend
3. Log into Nextcloud with an external (guest) account of your AzureAD tenant (This will put #EXT# in the user principal name)

### Expected behaviour
Everything should work as normal:
* The files app should show the users default files
* The admin should be able to remove/disable this account

### Actual behaviour
* The files app show no files in the Home folder. Files are in "Recent Files", but "Details" does not work and "Open folder" leads to a endless loop of redirects
* The admin can't edit/disable/remove the user

## Server configuration detail

**Operating system:** Linux 5.10.54 #1 SMP Thu Jul 29 11:09:02 CEST 2021 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.5.10

**PHP version:** 7.4.25

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, sodium, exif, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, apache2handler, apcu, imagick, memcached, redis, Zend OPcache

**Nextcloud version:** 22.2.3 - 22.2.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - admin_audit: 1.12.0
 - bruteforcesettings: 2.3.0
 - cloud_federation_api: 1.5.0
 - comments: 1.12.0
 - dav: 1.19.0
 - encryption: 2.10.0
 - federatedfilesharing: 1.12.0
 - files: 1.17.0
 - files_sharing: 1.14.0
 - files_trashbin: 1.12.0
 - files_versions: 1.15.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.10.0
 - oauth2: 1.10.0
 - password_policy: 1.12.0
 - polls: 3.4.2
 - privacy: 1.6.0
 - provisioning_api: 1.12.0
 - settings: 1.4.0
 - support: 1.5.0
 - text: 3.3.0
 - theming: 1.13.0
 - twofactor_backupcodes: 1.11.0
 - twofactor_totp: 6.2.0
 - updatenotification: 1.12.0
 - user_saml: 4.1.1
 - viewer: 1.6.0
 - workflowengine: 2.4.0
Disabled:
 - accessibility
 - activity
 - circles
 - contactsinteraction
 - dashboard
 - federation
 - files_external
 - files_pdfviewer
 - files_rightclick
 - files_videoplayer
 - firstrunwizard
 - limit_login_to_ip
 - nextcloud_announcements
 - notifications
 - occweb
 - photos
 - recommendations
 - serverinfo
 - sharebymail
 - spreed
 - survey_client
 - systemtags
 - user_ldap
 - user_status
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.johannes-endres.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "22.2.3.0",
    "integrity.check.disabled": true,
    "default_language": "de",
    "default_locale": "de",
    "trashbin_retention_obligation": "auto, 30",
    "version_retention_obligation": "auto, 30",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "overwrite.cli.url": "https:\/\/cloud.johannes-endres.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "nc_6068_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "occweb"
    ],
    "updater.release.channel": "stable",
    "encryption.legacy_format_support": false,
    "encryption.key_storage_migrated": false,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "default_phone_region": "DE",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**External storages:** files_external is disabled

**Encryption:** yes

**User-backends:** 
 * OC\User\Database
 * OCA\User_SAML\UserBackend

### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

**Operating system:** Ubuntu 20.04.3 LTS

### Logs

I can't see anything related to theses problems in any of the logs.

**Comment by acsfer** [comment] 2021-12-22 09:23
Confirm this, but if you try to (manually) create user with username 'test#tag' it will be denied even before save it.

![image](https://user-images.githubusercontent.com/12234510/147068811-40bae766-1610-4e0e-8c17-cff5044f8c57.png)

**Comment by szaimen** [comment] 2021-12-22 10:05
> 1. why `#` is not allowed

It is not allowed because it breaks logic in many places as you just discovered.

Also so the discussion in https://github.com/nextcloud/server/issues/21313

2. if not allowed, why users are created (from user_saml)

I suppose because `#` is a generallly allowed character for userid's in saml and not allowing those would block some accounts frrom login/user creation which would be another issue as well. So there is probably no good solution to this than fixing it everywhere where issues with currently not allowed characters come up manually which is probably a lot of work...

**Comment by acsfer** [comment] 2021-12-22 10:26
@szaimen let's move this to https://github.com/nextcloud/server/issues/21313 then as it is the same issue 👍 
And to answer 2, https://github.com/nextcloud/server/issues/21313#issuecomment-809227729

Duplicate of https://github.com/nextcloud/server/issues/21313

**Closed by acsfer** 2021-12-22 10:26 UTC
Labels: bug, 0. Needs triage
