### ISSUE TITLE
[FR] Return proper error message if updating a shared link fails

### ISSUE THREAD

**Issue by 3c7** [nextcloud/server#19675] opened 2020-02-27 12:38 UTC
**Is your feature request related to a problem? Please describe.**
If updating a share fails (e.g. password does not meet the requirements), just a generic error message will be printed.

**Describe the solution you'd like**
If updating the share link fails, the backend returns a HTTP 400 with an ocs object that contains further info in the meta key. It would be great to display the according (error) message.

**Describe alternatives you've considered**
None

**Additional context**
![Screenshot from 2020-02-27 13-37-44](https://user-images.githubusercontent.com/2846609/75445782-65f03a00-5966-11ea-96d2-64ab14605475.png)
![Screenshot from 2020-02-27 13-29-28](https://user-images.githubusercontent.com/2846609/75445646-23c6f880-5966-11ea-96db-2aa29bc4ae69.png)

**Comment by kesselb** [comment] 2020-02-27 14:27
Thanks for taking the time to report a problem :+1: 

I'm closing this report as duplicate of https://github.com/nextcloud/server/issues/19525

**Closed by kesselb** 2020-02-27 14:27 UTC
Labels: 0. Needs triage, enhancement

**Comment by 3c7** [comment] 2020-02-28 08:45
Oops, sorry for creating a duplicate.
