### ISSUE TITLE
Do not show users in the search contact menu

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#20507] opened 2020-04-15 21:12 UTC
### Steps to reproduce
1. Have active LDAP users.
2. Have shared addressbook.
2. Click on the upper icon search contacts, see the mixture of the contacts from shared addressbook and the LDAP users

### Expected behaviour
Do not show LDAP and local users, if not mentioned explicitly, but to show contacts from addressbooks.

### Actual behaviour
Mix of contact data shown in the search contacts.

**Nextcloud version:** 18.0.3

**Comment by kesselb** [comment] 2020-04-16 06:50
Duplicate of https://github.com/nextcloud/server/issues/5097?

**Comment by ostasevych** [comment] 2020-04-16 08:25
> Duplicate of #5097?

Not so, though may be merged somehow. In that issue its author wants to let collect contact details from different sources. My idea is to add some option to the Settings not to show users in the contact list called by clicking the button in the top right.

**Comment by skjnldsv** [comment] 2020-11-07 22:52
Definitely overlap :)

**Closed by skjnldsv** 2020-11-07 22:52 UTC
Labels: 0. Needs triage, bug, feature: contacts menu
