### ISSUE TITLE
No connection with Nextcloud

### ISSUE THREAD

**Issue by siroezka** [nextcloud/server#10798] opened 2018-08-22 10:35 UTC
### Server configuration

**Operating system**:
Debian 9.4
**Web server:**
Apache/2.4.25
**Database:**
10.1.26-MariaDB-0+deb9u1
**PHP version:**
7.0.27-0+deb9u1
**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Nextcloud version client:**
2.3.3 (build 1)

Hello! An error appears on the client "there is no connection with Nextcloud .." The error is repeated every 9 minutes.

![error_nc](https://user-images.githubusercontent.com/42605444/44458856-2e396100-a610-11e8-8e90-aa1c0c12cacf.png)

**Comment by szaimen** [comment] 2021-05-21 11:53
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-21 11:53 UTC
Labels: 0. Needs triage, bug
