### ISSUE TITLE
Placeholders visible

### ISSUE THREAD

**Issue by markusschweitzer** [nextcloud/server#16672] opened 2019-08-07 08:29 UTC
### Steps to reproduce
1. Try to enable a disabled app
2. Password dialog appears
3. Placeholders are visible

### Expected behaviour
The placholders should be replace with localized strings

### Actual behaviour
Placeholders like {title} are visible

This also happens on the try nextcloud instances (tried it on an instant instance there)

![image](https://user-images.githubusercontent.com/18368530/62607340-37ddd680-b8fe-11e9-9cf3-11635169edda.png)

### Server configuration

**Operating system**: Ubuntu Server 19.04

**Web server:** Apache

**Database:** Maria DB

**PHP version:** 7.3

**Nextcloud version:** 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Official Page, ZIP download

**Signing status:**
<details>
<summary>Signing status</summary>

All checks passed.
</details>

### Client configuration
**Browser:** Chrome 75

**Operating system:** Win 10

**Comment by markusschweitzer** [comment] 2019-08-07 08:49
Update: This only happens if chrome://flags/#enable-experimental-web-platform-features is enabled.
Disabling resolves this. maybe it is related to [Group chat "Cannot read property 'label' of undefined" (Chromium only) #1977](https://github.com/nextcloud/spreed/issues/1977)

**Comment by ChristophWurst** [comment] 2019-08-07 13:36
Anything in your browser log that tells us more about the error?

**Comment by markusschweitzer** [comment] 2019-08-08 07:16
Unfortunately not, chrome console is empty when i click on "Activate"

**Comment by skjnldsv** [comment] 2020-08-25 09:31
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:31 UTC
Labels: 0. Needs triage, bug
