### ISSUE TITLE
[Bug]: After the token expires, the user must log in twice.

### ISSUE THREAD

**Issue by vishnu-n23** [nextcloud/server#40503] opened 2023-09-19 13:15 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the token expires and the user is automatically logged out, the user must login twice. After the logout (after the token expires), when the user tries to login for the first time, the login process won't complete, the page refreshes and brings the user back to the same login page, where the user has to enter the login credentials again and press the login button to complete the login process (for successfully login).

### Steps to reproduce

1. Login to the Nextcloud
2. Logout from the Nextcloud (manually or auto logout after the token expires)
3. After waiting a few hours( preferably >1hrs), try to login again (if it was auto logout you can try to login immediately)

### Expected behavior

If the entered login credentials are valid, users should be able to complete the log in on their first try.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-10-29 15:37
Duplicate of #32538

**Closed by joshtrichards** 2024-10-29 15:37 UTC
Labels: bug, 0. Needs triage, feature: authentication, 27-feedback
