### ISSUE TITLE
Nextcloud 14.0.11 integrity check fails on .user.ini

### ISSUE THREAD

**Issue by dt64** [nextcloud/server#15569] opened 2019-05-16 14:06 UTC
just upgraded from NC14.0.9 to 14.0.11.
beside being hit by bug #15563 during upgrade, the integrity check now isn't happy with .user.ini file.
This is the same file as it was always used in this installation, up to 14.0.9 this was accepted.
This is the documented way to change these values: https://docs.nextcloud.com/server/14/admin_manual/configuration_files/big_file_upload_configuration.html

the .user.ini:
upload_max_filesize=1G
post_max_size=1G
memory_limit=2G
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'
output_buffering=0

https://domain.tld/settings/integrity/failed:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 467d4f028c447895716a2b7859ed6e569f8ee34b87b51d73dab2e6a9ca4fbe63172c7be3e365ae864a60408286afcce852dd38ee544b61685ed4ee5e021fecb0
                            [current] => f5f72f20dc9ba13f2accbbed8d13aab71178c3a6bf60a360929f59c75726929353a1695eba9fc6dd35652cba128acd22abdfd3af6aef6c741d7d42537fda8b8e
                        )

                )

        )

)

### Steps to reproduce
1. have NC14.0.9 installed and working fine
2. upgrade to NC14.0.11 using auto-updater
3. run integrity check tool

### Expected behaviour
Tell us what should happen

integrity tool should confirm all is fine

### Actual behaviour
Tell us what happens instead

integrity check tool isn't happy with .user.ini file

### Server configuration

**Operating system**:
Ubuntu 18.04
**Web server:**
nginx
**Database:**
mariaDB
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14.0.11
**Updated from an older Nextcloud/ownCloud or fresh install:**
14.0.9
**Where did you install Nextcloud from:**
official production channel
**Signing status:**
<details>Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 467d4f028c447895716a2b7859ed6e569f8ee34b87b51d73dab2e6a9ca4fbe63172c7be3e365ae864a60408286afcce852dd38ee544b61685ed4ee5e021fecb0
                            [current] => f5f72f20dc9ba13f2accbbed8d13aab71178c3a6bf60a360929f59c75726929353a1695eba9fc6dd35652cba128acd22abdfd3af6aef6c741d7d42537fda8b8e
                        )

                )

        )

)
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.5
  - checksum: 0.4.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.8
  - dashboard: 5.0.1
  - dav: 1.6.1
  - dicomviewer: 1.2.0
  - extract: 1.2.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_antivirus: 1.4.2
  - files_fulltextsearch: 1.1.3
  - files_fulltextsearch_tesseract: 1.0.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.13.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - fulltextsearch: 1.1.1
  - fulltextsearch_elasticsearch: 1.0.3
  - gallery: 18.1.0
  - groupfolders: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - metadata: 0.9.0
  - music: 0.9.5
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - previewgenerator: 2.1.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - ransomware_detection: 0.5.0
  - ransomware_protection: 1.2.0
  - richdocuments: 3.2.4
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - unsplash: 1.1.3
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/domain.tld",
        "dbtype": "mysql",
        "version": "14.0.11.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.release.channel": "production",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
n/a
</details>

**Comment by AlfredSK** [comment] 2019-05-18 08:42
Same thing happens with Nextcloud 16.0.1. I don't think the `.user.ini` file should be included in the code integrity check. The error message did not appear with Nextcloud 16.0.0 and Nextcloud 15.0.x.

**Comment by maanloper** [comment] 2019-07-10 18:03
Same problem in 16.0.3 after upgrading from 16.0.1:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 4843b3217e91f8536cb9b52700efb20300290292cf6286f92794d4cec99df286afeb7dd6c91b1be20bc55eda541eef230a5c5e7dcd46c189edd0ed1e80c6d3f5
                            [current] => 452bebf8004b8cfa8ba212436f6d28521bee343d9ed76666384c635046a1e607ea33d01cd2bdd061cb55a1909f3fc4b734cc3b5cb779d0362dccae6c678216f5
                        )

                )

        )

)



I've seen multiple reports on this problem. I tried replacing .user.ini by using:
wget https://raw.githubusercontent.com/nextcloud/server/master/.user.ini

However, I still get the error. Any hints on how to (structurally) solve this problem?

**Comment by kesselb** [comment] 2019-07-10 18:07
try `wget https://github.com/nextcloud/server/blob/stable14/.user.ini`

**Comment by maanloper** [comment] 2019-07-10 18:33
It actually worked with my own solution just a second ago; it seemed Ubuntu saved it as .user.ini.1 and I didn't notice -_-, removed .user.ini, used wget again and pronto!
But thanks for trying to help, appreciated!

**Comment by skjnldsv** [comment] 2020-08-25 09:29
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:29 UTC
Labels: 0. Needs triage, bug
