### ISSUE TITLE
Misaligned ... meny in Android browers

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#10805] opened 2018-08-22 14:29 UTC
I use NC 14.0.0 beta 4.
When I access  my site in my Andreoid telephone and want to access the menu through the ... icon I get this
![email_attached_b15e863deb0ea3d0663ea88cb925b398](https://user-images.githubusercontent.com/36486009/44469718-69478e80-a628-11e8-8de0-53e2b0a08bc6.png)
Only half of the menu alternatives are visible.

**Comment by MorrisJobke** [comment] 2018-08-22 15:17
Duplicate of #10722 and it will be fixed in RC1

**Closed by MorrisJobke** 2018-08-22 15:17 UTC
Labels: bug, design

**Comment by MorrisJobke** [comment] 2018-08-23 10:30
> Maybe a duplicate of #10722 but it is not the same menu. And this is seen in Android phone.

Could you check if the fix from https://github.com/nextcloud/server/pull/10723 solves it for you?
