### ISSUE TITLE
Trashbin: More than 1000 expressions in a list are not allowed on Oracle.

### ISSUE THREAD

**Issue by jabdoa2** [nextcloud/server#28793] opened 2021-09-10 20:26 UTC
### Steps to reproduce
Unclear. Upgrade 20.0.12 to 21.0.4.

### Expected behaviour
Crons should succeed cleaning up files. This worked in 20.0.

### Actual behaviour
Cron crashes when trying to cleanup trashbin. This seems to create high load to the Maria database for some reason (might be unrelated). User cannot login. 

Similar as the comment here: https://github.com/nextcloud/server/issues/27380#issuecomment-877054731. Seems not to be fixed in 21.0.4 yet.

Not the same as https://github.com/nextcloud/server/issues/27932 (different call trace and different query).

### Server configuration

**Operating system:** Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** PHP 7.4.23

**Nextcloud version:** 21.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 20.0.12

**Where did you install Nextcloud from:** Helm + Docker

**Signing status:**
```
No errors have been found.
```

```
# kubectl exec nextcloud-6fbf9ccdd-ntwzj -n nextcloud -- su www-data -s /usr/local/bin/php occ app:list
Defaulted container "nextcloud" out of: nextcloud, mariadb-isalive (init)
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.3
  - cloud_federation_api: 1.4.0
  - contacts: 4.0.2
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_texteditor: 2.14.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - comments
  - encryption
  - federation
  - files_external
  - joplin
  - systemtags
  - user_ldap

```

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.kantert.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.4.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "overwriteprotocol": "https",
        "trustedproxies": [
            "10.1.0.0\/16"
        ],
        "trashbin_retention_obligation": "auto, 30"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.14.3",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "425071"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "168710",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.3.3",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.0.2",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "dav"
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "global_cache_gc_lastrun": "1465988201",
            "incoming_server2server_share_enabled": "no",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1420846236.187",
            "lastcron": "1631305205",
            "lastupdateResult": "[]",
            "lastupdatedat": "1631302204",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "outgoing_server2server_share_enabled": "no",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_mozilla_sync": "mozilla_sync\/appinfo\/remote.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "shareapi_default_expire_date": "yes",
            "shareapi_expire_after_n_days": "180",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "updater.secret.created": "1588189620",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.1.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.17.1",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.9.0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "filesystem"
        },
        "files_external": {
            "user_certificate_scan": "not-run-yet"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.13.1",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.14.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.10.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "joplin": {
            "enabled": "no",
            "installed_version": "0.0.25",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "authentication"
        },
        "mozilla_sync": {
            "enabled": "no",
            "installed_version": "1.4",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.2.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "1.6.0",
            "calendar": "1.6.6",
            "contacts": "3.1.6",
            "core": "16.0.10.2",
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "filesystem"
        }
    }
}
```

**Are you using external storage, if yes which one:** local/

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox/Chrome/Nextcloud App

**Operating system:** Linux/Windows/Android

### Logs

```
Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.

    /var/www/html/lib/private/Files/Cache/Cache.php - line 606:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/html/lib/private/Files/Cache/Cache.php - line 550:

    OC\Files\Cache\Cache->removeChildren(OC\Files\Cache\CacheEntry {})

    /var/www/html/lib/private/Files/Cache/Updater.php - line 160:

    OC\Files\Cache\Cache->remove("files_trash ... 7")

    /var/www/html/lib/private/Files/View.php - line 330:

    OC\Files\Cache\Updater->remove("files_trash ... 7")

    /var/www/html/lib/private/Files/View.php - line 1184:

    OC\Files\View->removeUpdate(OCA\Files_Tr ... }}, "files_trash ... 7")

    /var/www/html/lib/private/Files/View.php - line 351:

    OC\Files\View->basicOperation("rmdir", "/xxx/files_ ... 7", [ "delete"])

    /var/www/html/lib/private/Files/Node/Folder.php - line 468:

    OC\Files\View->rmdir("/xxx/files_ ... 7")

    /var/www/html/apps/files_trashbin/lib/Trashbin.php - line 685:

    OC\Files\Node\Folder->delete()

    /var/www/html/apps/files_trashbin/lib/Trashbin.php - line 902:

    OCA\Files_Trashbin\Trashbin::delete("yyyy", "xxx", 1591479527)

    /var/www/html/apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php - line 89:

    OCA\Files_Trashbin\Trashbin::deleteExpiredFiles([ OC\Files\F ... "], "xxx")

    /var/www/html/lib/private/User/Manager.php - line 646:

    OCA\Files_Trashbin\BackgroundJob\ExpireTrash->OCA\Files_Trashbin\BackgroundJob\{closure}("*** sensiti ... *")

    /var/www/html/apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php - line 90:

    OC\User\Manager->callForSeenUsers(Closure {})

    /var/www/html/lib/private/BackgroundJob/Job.php - line 52:

    OCA\Files_Trashbin\BackgroundJob\ExpireTrash->run(null)

    /var/www/html/lib/private/BackgroundJob/TimedJob.php - line 59:

    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/html/cron.php - line 128:

    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

#### Web server error log
None

#### Nextcloud log (data/nextcloud.log)
None relevant

#### Browser log
Not relevant.

**Comment by acsfer** [comment] 2021-09-14 15:32
Duplicate of (many) https://github.com/nextcloud/server/search?q=More+than+1000+expressions&type=issues
There is already a PR for this (not yet merged) for v21.

Fixed on v22.

**Comment by szaimen** [comment] 2021-09-15 13:29
Duplicate of https://github.com/nextcloud/server/issues/27932#issuecomment-880984335

**Closed by szaimen** 2021-09-15 13:29 UTC
Labels: bug, 0. Needs triage
