### ISSUE TITLE
[Bug]: App Admin frozen in Nextcloud 28 (on Safari)

### ISSUE THREAD

**Issue by EmOneHundred** [nextcloud/server#44572] opened 2024-03-29 14:55 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi, since upgrading to Nextcloud 28.0.3 (and now in 28.0.4) when we visit the Apps Admin page we cannot scroll through or select apps in list view. If we need to update one of them in list view, the only way to update an app is to use the “update all” button at the top. Selecting an app to view changelog does not work. On my screen whatever app I select displays a different app in the window on the right. We are running Nextcloud via CloudAmo. I have tested this only with Safari and Duck Duck Go browser. In forum, there is another user having this problem who said it did not exist in Mozilla.   I remember in Nextcloud 25, there was a similar issue and a user on the forum posted that there was an error in the file at "/public_html/lib/private/App/PlatformRepository.php". The user's recommendation (in October 2022) was this: _anon78853765, Oct 2022  -  Had the same problem, app page not accessible… Solution: Change PlatformRepository.php line 148 from "public function normalizeVersion(string $version, ?string $fullVersion = null): string {" to "public function normalizeVersion($version, $fullVersion = null) {"_ https://help.nextcloud.com/t/help-apps-page-doesnt-work-after-update-to-25/147937/4.   I tried this solution in the new file - I think that string is at 155 in this version.  But it did not correct the problem this time.

### Steps to reproduce

1. In Safari, go to server address, select my own user avatar and choose "+ Apps"
2. Apps admin page appears, and I cannot scroll or select apps in any of the list views. Grid view is better.

### Expected behavior

Expected to be able to scroll through the list view of apps.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Sorry about the blanks. I am not skilled enough for some of these questions. We use Nextcloud via the CloudAmo provider. So for the installation method, I usually ask CloudAmo to upgrade for us. Sometimes I do it through the updatr in the Admin Settings page - if there are no hangups.

**Comment by susnux** [comment] 2024-03-29 15:01
Please look at the open issues first (use the search) in this case this is a duplicate of the latest (!) issue reported.

Duplicate of https://github.com/nextcloud/server/issues/44568

**Closed by susnux** 2024-03-29 15:01 UTC
Labels: bug, 0. Needs triage
