### ISSUE TITLE
[FEATURE REQUEST] Improve dropbox upload

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8586] opened 2018-02-28 15:22 UTC
Currently if you set a folder to function like a dropbox the current upload mechanism is very simple and does not provide any sort of information as to the status of the files and if one errors one which one and what happened. This is a pretty big problem, I have Nextcloud v13 installed and if it succeeds or not is a mystery to the end user.

Dropbox solves this pretty well:

https://i.imgur.com/BZFzBNI.png

**Comment by MorrisJobke** [comment] 2018-03-01 08:05
The status for the current progress is already tracked in #4164 - for failures we give a little message with the reason and otherwise a checkmark IRC.

Let's close this here then as duplicate of #4164

**Closed by MorrisJobke** 2018-03-01 08:05 UTC
