### ISSUE TITLE
Share link is missing on 14.0.4

### ISSUE THREAD

**Issue by JB1985** [nextcloud/server#13001] opened 2018-12-11 07:06 UTC
### Steps to reproduce
1. Upload a .m4v File
2. Try to share with a link
3.

### Expected behaviour
See the 3 points to get the share link.

### Actual behaviour
The 3 Points are missing.

### Server configuration

**Operating system**: debian 9

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** PHP 7.2

**Nextcloud version:** 14.0.4

If I want to share a .m4v Video by a link It does not work. The three points are missing.

That seems to be just a Bug in NC14. In NC15 it works.

![image](https://user-images.githubusercontent.com/9932751/49783854-85785400-fd1b-11e8-9521-38a965681b2c.png)

With .MOV works but not with .m4v files.

**Comment by AmonBune** [comment] 2018-12-12 12:36
If you have plugins (especially ad blockers) in your browser installed, see that thread:

https://help.nextcloud.com/t/removing-a-shared-resource-not-possible-in-nc-15-0-0/43056/8

**Comment by juliushaertl** [comment] 2019-02-19 11:06
@AmonBune Does the issue still exist for you on 14.0.7, as I cannot reproduce it. I'll close this for now, in case it still exists, please check your browser console for errors and feel free to reopen it.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Closed by juliushaertl** 2019-02-19 11:06 UTC
Labels: 0. Needs triage, bug, feature: sharing, regression
