### ISSUE TITLE
[Bug]: dashboard app - class RegisterWidgetEvent not found after upgrade to 29 followed by downgrade to 28

### ISSUE THREAD

**Issue by goulabf9** [nextcloud/server#45142] opened 2024-05-01 18:43 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I am running Nextcloud in Docker - version 28.0.1
I pulled a new docker image (v29) to upgrade but it simply didn't work - server was not available at all
I run occ upgrade without any success - and to be honest I had no time to investigate too much
The issue was that it was continiously writing that the files of any app are not correct and the only way to get rid of the message was to copy from the tarball the apps into the docker instead of the ones pulled before.
But no chance that was still not working - server not reachable.
So I went back to the old docker image thinking I would deal with the upgrade another day
And then the following:

I can again reach the server but I get the following message:
Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

Looking into the log file, it turned out that the issue is with the dashboard app
","remoteAddr":"192.168.1.11","user":"Fabien","app":"index","method":"GET","url":"/index.php/apps/dashboard/","message":"Class \"OCP\\Dashboard\\RegisterWidgetEvent\" not found in file '/var/www/html/apps/dashboard/lib/Controller/DashboardController.php' line 93"

### Steps to reproduce

1. Pull new docker image v29 and recreate container (previously v28)
2. Server is not reachable anymore
3. occ upgrade states that the following : UnexpectedValueException: The files of the app XXXX were not correctly replaced before running the update - XXXX is all the apps
4. replacing the apps directory by the one delivered with the tarball found on linuxserver.io
5. no error anymore - occ upgrade states "everything ok"
6. but still can not reach the server
7. recreate the docker with v28
8. repeat steps 3, 4, 5
9. the server is now reachable but delivers an internal server error
10. the dashboard app appears to be the issue

### Expected behavior

I would have expected that the upgrade in Docker simply works

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "upgrade.disable-web": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.xxx",
            "192.168.1.227"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "http:\/\/nextcloud.xxx",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 3,
        "theme": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_automatedtagging: 1.18.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.4
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.3
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflow_script: 1.13.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - suspicious_login: 6.0.0
  - user_ldap: 1.19.0
```

### Nextcloud Logs

```shell
{"reqId":"UsubPJUiDU0du6DbAH9G","level":3,"time":"2024-05-01T17:42:39+00:00","remoteAddr":"192.168.1.11","user":"Fabien","app":"index","method":"GET","url":"/index.php/apps/dashboard/","message":"Class \"OCP\\Dashboard\\RegisterWidgetEvent\" not found in file '/var/www/html/apps/dashboard/lib/Controller/DashboardController.php' line 93","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"28.0.1.1","exception":{"Exception":"Exception","Message":"Class \"OCP\\Dashboard\\RegisterWidgetEvent\" not found in file '/var/www/html/apps/dashboard/lib/Controller/DashboardController.php' line 93","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Dashboard\\Controller\\DashboardController"],"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Dashboard\\Controller\\DashboardController","index",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["dashboard.dashboard.index"]]},{"file":"/var/www/html/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/dashboard/"]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":170,"Previous":{"Exception":"Error","Message":"Class \"OCP\\Dashboard\\RegisterWidgetEvent\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"index","class":"OCA\\Dashboard\\Controller\\DashboardController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Dashboard\\Controller\\DashboardController"],"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Dashboard\\Controller\\DashboardController"],"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Dashboard\\Controller\\DashboardController","index",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["dashboard.dashboard.index"]]},{"file":"/var/www/html/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/dashboard/"]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/dashboard/lib/Controller/DashboardController.php","Line":93},"message":"Class \"OCP\\Dashboard\\RegisterWidgetEvent\" not found in file '/var/www/html/apps/dashboard/lib/Controller/DashboardController.php' line 93","exception":{},"CustomMessage":"Class \"OCP\\Dashboard\\RegisterWidgetEvent\" not found in file '/var/www/html/apps/dashboard/lib/Controller/DashboardController.php' line 93"}}
{"reqId":"UsubPJUiDU0du6DbAH9G","level":3,"time":"2024-05-01T17:42:39+00:00","remoteAddr":"192.168.1.11","user":"Fabien","app":"jsresourceloader","method":"GET","url":"/index.php/apps/dashboard/","message":"Could not find resource comments/js/comments.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"28.0.1.1","data":{"app":"jsresourceloader"}}
```

### Additional info

I can reach the server from mobile phone
the error is only on the web server

**Comment by joshtrichards** [comment] 2024-05-02 17:11
What Docker image, precisely, are you using? Also please share your Compose file.

> Pull new docker image v29 and recreate container (previously v28)

You just mean this sequence correct?

```
(Adjust label in Compose file to point at newer image version)
docker compose pull 
docker compose up -d
```

**Comment by kesselb** [comment] 2024-05-02 18:22
> "OCP\\Dashboard\\RegisterWidgetEvent\" not found in file

RegisterWidgetEvent was removed in 29. 
It looks like the dashboard app is incompatible with the server version.

**Comment by goulabf9** [comment] 2024-05-02 20:14
> > "OCP\Dashboard\RegisterWidgetEvent" not found in file
> 
> RegisterWidgetEvent was removed in 29. It looks like the dashboard app is incompatible with the server version.

Ok I see but actually I went back to 28 so I am a little lost ...
I don't get what I did wrong
do you mean disable the app so at least it is not called

**Comment by goulabf9** [comment] 2024-05-02 20:18
Oh yes that was really so simple ... I disabled dashboard and it is working now as expected
of course without dashboard bu V28 runnning like before
I have no clue how I manage to come into this situation ...
I do not dare to try to upgrade again

**Comment by joshtrichards** [comment] 2024-05-03 13:03
> Ok I see but actually I went back to 28 so I am a little lost ...
> I don't get what I did wrong
>
> So I went back to the old docker image thinking I would deal with the upgrade another day
And then the following:
> [...]
> replacing the apps directory by the one delivered with the tarball found on linuxserver.io

I don't know what the cause of your original upgrade problem was, but the cause of your current situation likely is related to a mixture of your attempt to downgrade (downgrading isn't supported) plus the manual intervention you took above with the tarball (P.S. We're not associated with linuxserver.io and there image is completely different from the one you appear to be running).

> I pulled a new docker image (v29) to upgrade but it simply didn't work - server was not available at all
I run occ upgrade without any success - and to be honest I had no time to investigate too much
The issue was that it was continiously writing that the files of any app are not correct and the only way to get rid of the message was to copy from the tarball the apps into the docker instead of the ones pulled before.

I'm unable to reproduce any problems upgrading from our v28 images to our v29 images. 

```
test-nc28-to-nc29-upgrade-app-1  | Configuring Redis as session handler
test-nc28-to-nc29-upgrade-app-1  | Initializing nextcloud 29.0.0.19 ...
test-nc28-to-nc29-upgrade-app-1  | Upgrading nextcloud from 28.0.5.1 ...
test-nc28-to-nc29-upgrade-app-1  | => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/pre-upgrade
test-nc28-to-nc29-upgrade-app-1  | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
test-nc28-to-nc29-upgrade-app-1  | You may use your browser or the occ upgrade command to do the upgrade
test-nc28-to-nc29-upgrade-app-1  | Setting log level to debug
test-nc28-to-nc29-upgrade-app-1  | Turned on maintenance mode
test-nc28-to-nc29-upgrade-app-1  | Updating database schema
test-nc28-to-nc29-upgrade-app-1  | Updated database
test-nc28-to-nc29-upgrade-app-1  | Updating <federation> ...
test-nc28-to-nc29-upgrade-app-1  | Updated <federation> to 1.19.0
[...]
```

Unless you can provide the exact output you were seeing during the initial upgrade attempt there's not a lot here for us to go on. This may be a config/environment matter. You might try posting at the Help Forum (https://help.nextcloud.com).

**Comment by kesselb** [comment] 2024-05-03 14:53
> We're not associated with linuxserver.io and their image is completely different from the one you appear to be running).

Well spotted. 

I'm closing the issue. There is nothing we can do with the provided information.

**Closed by kesselb** 2024-05-03 14:53 UTC
Labels: bug, needs info, 0. Needs triage, 29-feedback
