### ISSUE TITLE
Limit 2FA enforcement to ip ranges

### ISSUE THREAD

**Issue by mkofahl** [nextcloud/server#20857] opened 2020-05-07 13:25 UTC
Currently it's possible to force 2FA for certain groups. In the same way, 2FA could be limited to certain IP ranges in order to protect internal and external logins differently.

**Comment by ChristophWurst** [comment] 2020-05-19 07:54
Duplicate of https://github.com/nextcloud/server/issues/2035

**Closed by ChristophWurst** 2020-05-19 07:54 UTC
Labels: 0. Needs triage, enhancement
