### ISSUE TITLE
Folder icon color should be the same as the main owncloud theme colour

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#1492] opened 2016-09-22 12:23 UTC
A small idea I had after changing my main theme colour.
What do you think?

For now I used css masks, but I need to check all browsers for compatibility. If not, a simple svg as img with a fill value could do the trick.

![files](https://cloud.githubusercontent.com/assets/14975046/18747911/0c96025e-80d0-11e6-9677-4171d5cdcf22.gif)

@nextcloud/theming @nextcloud/designers

**Comment by eppfel** [comment] 2016-09-22 12:26
This is part of the theming app and is currently worked on.

**Comment by eppfel** [comment] 2016-09-22 12:35
#840

**Comment by MorrisJobke** [comment] 2016-09-22 13:56
> #840

It's not merged yet -> reopen

**Comment by nickvergessen** [comment] 2016-09-22 14:52
Duplicate of https://github.com/nextcloud/server/issues/378

**Closed by nickvergessen** 2016-09-22 14:52 UTC
Labels: design, enhancement, feature: files, feature: theming

**Comment by skjnldsv** [comment] 2016-09-23 03:43
Ehehe, My bad guys :)

**Comment by jancborchardt** [comment] 2016-09-26 14:34
@skjnldsv no worries ;D good to see you back again, hope to see more design improvements from you! :)

**Comment by skjnldsv** [comment] 2016-09-26 14:47
Will think of it ;)
