### ISSUE TITLE
[stable20] Custom Background image of login screen for shared files is tiled. Standard login screen is ok

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#24356] opened 2020-11-24 17:13 UTC
### Steps to reproduce
When I´m using a custom background image that has been defined via web GUI “Settings --> Theming --> Login Image” the login screen looks fine for the default login page.

But when it comes to an password protected shared file link, the image of the login screen will be displayed in tiles. Until now I didn´t found a solution to get rid of this issue.

### Expected behaviour
The picture shuldn't be shown tiled

### Actual behaviour
The picture ist shown tiled
see also https://help.nextcloud.com/t/nc-20-custom-background-image-of-login-screen-is-tiled-for-shared-file-links/98838

## Server configuration detail

**Operating system:** Linux 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.2.16

**PHP version:** 

7.4.8
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** necxtcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.13.3
 - admin_audit: 1.10.0
 - announcementcenter: 4.0.0
 - apporder: 0.11.0
 - audioplayer: 3.0.0
 - bookmarks: 4.0.5
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.2
 - contactsinteraction: 1.1.0
 - data_request: 1.7.0
 - dav: 1.16.1
 - deck: 1.2.1
 - event_update_notification: 1.1.0
 - external: 3.7.1
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_downloadactivity: 1.9.0
 - files_linkeditor: 1.1.2
 - files_markdown: 2.3.1
 - files_pdfviewer: 2.0.1
 - files_readmemd: 1.2.0
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_texteditor: 2.14.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - forms: 2.0.4
 - guests: 1.6.1
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - news: 15.0.6
 - nextbackup: 20.9.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - ocsms: 2.1.8
 - password_policy: 1.10.1
 - photos: 1.2.0
 - piwik: 0.7.0
 - polls: 1.6.2
 - previewgenerator: 3.0.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quota_warning: 1.9.1
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.3
 - support: 1.3.0
 - suspicious_login: 3.2.1
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_usage_report: 1.4.2
 - viewer: 1.4.0
 - w2g2: 3.0.3
 - workflowengine: 2.2.0
Disabled:
 - accessibility
 - analytics
 - appointments
 - cms_pico
 - dashboard
 - drop_account
 - encryption
 - files_accesscontrol
 - files_external
 - files_trackdownloads
 - firstrunwizard
 - gpxedit
 - gpxmotion
 - gpxpod
 - phonetrack
 - quickaccesssorting
 - ransomware_detection
 - richdocuments
 - socialsharing_email
 - survey_client
 - telephoneprovider
 - timemanager
 - user_external
 - user_ldap
 - user_status
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "loglevel": 0,
    "maintenance": false,
    "theme": "",
    "integrity.check.disabled": false,
    "overwrite.cli.url": "https:\/\/of99.net\/",
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "simpleSignUpLink.shown": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "log_rotate_size": "10485760",
    "activity_expire_days": 33,
    "trusted_domains": [
        "localhost.localdomain",
        "192.168.1.234",
        "***.net",
        "office.***.net",
        "localhost"
    ],
    "htaccess.RewriteBase": "\/",
    "trashbin_retention_obligation": "auto, 10",
    "versions_retention_obligation": "auto, 21",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "preview_max_x": 1000,
    "preview_max_y": 1000,
    "preview_max_scale_factor": 10,
    "dbtype": "mysql",
    "version": "20.0.2.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "tasks",
        "w2g2",
        "apporder",
        "piwik",
        "ownbackup",
        "radio",
        "carnet",
        "theming",
        "workin2gether",
        "files_linkeditor",
        "socialsharing_email",
        "files_readmemd",
        "spreed",
        "telephoneprovider",
        "drop_account",
        "issuetemplate",
        "polls",
        "ocsms",
        "quickaccesssorting",
        "cms_pico",
        "ransomware_detection",
        "impersonate",
        "gpxmotion",
        "gpxedit",
        "sharerenamer",
        "uploaddetails",
        "external",
        "files_downloadactivity",
        "user_usage_report",
        "files_trackdownloads",
        "audioplayer"
    ],
    "has_rebuilt_cache": true,
    "mail_sendmailmode": "smtp",
    "mail_smtpport": "587"
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** none

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

**Operating system:** Ubuntu 20.04.1 LTS

**Comment by kesselb** [comment] 2020-11-24 20:44
Duplicate of https://github.com/nextcloud/server/issues/24200

**Closed by kesselb** 2020-11-24 20:44 UTC
Labels: 0. Needs triage, bug
