### ISSUE TITLE
RuntimeException: Storage could neither be inserted nor be selected from the database

### ISSUE THREAD

**Issue by o---** [nextcloud/server#15369] opened 2019-05-04 08:53 UTC
### Steps to reproduce
1. Enter username into Username followed by space (autopopulate feature on android adds it automatically)
2. Enter password
3. Login

### Expected behaviour
Spaces should be trimmed

### Actual behaviour
Space is passed to the server and results in 
![image](https://user-images.githubusercontent.com/5457048/57176499-17166880-6e59-11e9-8e95-10cfce925c2d.png)

### Server configuration

**Operating system**:
Ubuntu 16.04.2
**Web server:**
Apache 2
**Database:**
mySQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
15.0.7 (same issue was also on 15.0.2 and I did not try other versions)

### Client configuration

Any. Impacts also Android Apps such as Nextcloud Talk

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Check line 9 - the space is passed to Path causing the issue

[index] Error: RuntimeException: Storage could neither be inserted nor be selected from the database at <<closure>>

 0. /var/www/nextcloud.domain.com/lib/private/Files/Cache/Cache.php line 104
    __construct(OCA\Files_Trashb ... l})
 1. /var/www/nextcloud.domain.com/lib/private/Files/Storage/Home.php line 71
    __construct(OCA\Files_Trashb ... l})
 2. /var/www/nextcloud.domain.com/lib/private/Files/Storage/Wrapper/Wrapper.php line 393
    getCache("", OCA\Files_Trashb ... l})
 3. /var/www/nextcloud.domain.com/lib/private/Files/Config/UserMountCache.php line 92
    getCache()
 4. <<closure>>
    OC\Files\Config\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/nextcloud.domain.com/lib/private/Files/Config/UserMountCache.php line 93
    array_filter(["*** sensitive parameter replaced ***"], Closure {})
 6. /var/www/nextcloud.domain.com/lib/private/Files/Config/MountProviderCollection.php line 188
    registerMounts(OC\User\User {}, ["*** sensitive parameter replaced ***"])
 7. /var/www/nextcloud.domain.com/lib/private/Files/Filesystem.php line 449
    registerMounts(OC\User\User {}, ["*** sensitive parameter replaced ***"])
 8. /var/www/nextcloud.domain.com/lib/private/Files/Filesystem.php line 376
    initMountPoints("user.name@domain.com ")
 9. /var/www/nextcloud.domain.com/lib/private/legacy/util.php line 308
    init("user.name@domain.com ", "/user.name@domain.com /files")
10. /var/www/nextcloud.domain.com/lib/base.php line 986
    setupFS()
11. /var/www/nextcloud.domain.com/index.php line 42
    handleRequest()

GET /undefined/img/notifications.svg
from 192.168.88.789 by user.name@domain.com  at 2019-05-04T08:41:24+00:00
```
</details>

**Comment by alx-tuilmenau** [comment] 2020-01-10 15:54
Maybe the same like my #15167, got the same error, caused by spaces at the end of the username.

**Comment by szaimen** [comment] 2021-05-28 09:53
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Closed** 2021-06-22 21:54 UTC
Labels: 0. Needs triage, bug, needs info
