### ISSUE TITLE
Dark Theme broken on Audio Player app

### ISSUE THREAD

**Issue by jupiterbjy** [nextcloud/server#21013] opened 2020-05-17 07:23 UTC
![image](https://user-images.githubusercontent.com/26041217/82138282-49bfb300-985a-11ea-855c-19671996b655.png)

Only primarily visible area is darkened on Audio Player app. As soon as main list section scrolls down, white background scrolls up. Someone issued about scroll bar in dark mode already, I'll pass that. Similar effect 

Nextcloud 18.0.4
Chrome 81.0.4044.138

**Comment by Dragon988** [comment] 2020-05-17 09:57
Well, I can tell you it's fixed in NC 19 RC2. I'm not sure if those fixes have been backported.

To add to this bug report can you verify disabling all local cache (redis, nginx/haproxy, etc) doesn't fix this? Cloudflare can be problematic as well.

Any errors in either the nextcloud log or the web browsers (firefox/chrome) console?

**Comment by jupiterbjy** [comment] 2020-05-17 13:52
If NC 19 already fxed this, I'll close this issue soon. Only searched for open issues;

Just to add few more details I can provide right away - I have no access to this home server for now, and this nas stays behind Nginx reverse proxy. No Errors on chrome.

Below shows which section is having issue.

![image](https://user-images.githubusercontent.com/26041217/82148889-f23c3a00-988f-11ea-97e8-8e8700608ad4.png)

![image](https://user-images.githubusercontent.com/26041217/82148984-91613180-9890-11ea-8d76-8fc3f091889d.png)

**Comment by Dragon988** [comment] 2020-05-17 14:58
Is there anything needed to replicate this other then enabling the dark theme and using the audio player?

**Comment by jupiterbjy** [comment] 2020-05-18 13:55
Long list of music so you can scroll down. Without scrolling It looks completely normal at glance. Background starts scrolling upward as user scrolls down. Tried to show that on image, might be better explained with [gif](https://gyazo.com/bcd7944e8767144489fa156e91ccce78).

Those 'touch-action = pan-y' on 'app-content' section looks suspicious, but sadly I have no knowledge in javascript.

**Comment by szaimen** [comment] 2021-06-02 11:18
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 11:18 UTC
Labels: 0. Needs triage, bug

**Comment by jupiterbjy** [comment] 2021-06-02 15:33
Yes this was indeed fixed after numerous updates, sorry I forgot to close this. Thanks!
