### ISSUE TITLE
Public Upload folder does not work

### ISSUE THREAD

**Issue by fool15982** [nextcloud/server#27589] opened 2021-06-21 16:53 UTC
Hello,

I am expierencing an issues since a few days with public uploads. I can use upload via WI when I am logged in as a user and sync via NC client is working properly but if I share a folder (with or without password) with write access only (like drop in only) the upload fails.

From the logs I can see:
[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /snap/nextcloud/28088/htdocs/3rdparty/sabre/http/lib/Sapi.php:132) at /snap/nextcloud/28088/htdocs/apps/dav/lib/Connector/Sabre/File.php#691 at <>

<>
OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/snap/nextcloud ... p", 691, {string: "X-Hash ... "})
/snap/nextcloud/28088/htdocs/apps/dav/lib/Connector/Sabre/File.php line 691
header("X-Hash-MD5: c8e ... f")
/snap/nextcloud/28088/htdocs/apps/dav/lib/Connector/Sabre/File.php line 189
OCA\DAV\Connector\Sabre\File->header("X-Hash-MD5: c8e ... f")
<>
OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre{closure}("*** sensitive parameters replaced ***")
/snap/nextcloud/28088/htdocs/lib/private/Files/Stream/HashWrapper.php line 71
call_user_func(Closure {}, "*** sensitive parameter replaced ***")
<>
OC\Files\Stream\HashWrapper->stream_close()
/snap/nextcloud/28088/htdocs/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php line 95
fclose(null)
/snap/nextcloud/28088/htdocs/lib/private/Files/Stream/HashWrapper.php line 75
Icewind\Streams\Wrapper->stream_close()
<>
OC\Files\Stream\HashWrapper->stream_close()
/snap/nextcloud/28088/htdocs/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php line 95
fclose(null)
/snap/nextcloud/28088/htdocs/lib/private/Files/Stream/HashWrapper.php line 75
Icewind\Streams\Wrapper->stream_close()
/snap/nextcloud/28088/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php line 321
OC\Files\Stream\HashWrapper->stream_close()
/snap/nextcloud/28088/htdocs/apps/dav/appinfo/v1/publicwebdav.php line 113
Sabre\DAV\Server->exec()
/snap/nextcloud/28088/htdocs/public.php line 81
require_once("/snap/nextcloud ... p")
PUT /public.php/webdav/Profilfoto.JPG
from 176.199.24.5 at 2021-06-20T21:18:03+00:00

The lastest updates are installed (OS & snap). Does anyone run into the same issue? Maybe some hints for a solution?

BR
Andre

UPDATE
The issue seem to occure only when "upload only" is selected. If the sharing permission is set to upload and edit, it works as expected!

**Comment by szaimen** [comment] 2021-06-21 23:14
Duplicate of https://github.com/nextcloud/server/issues/22509

**Closed by szaimen** 2021-06-21 23:14 UTC
