### ISSUE TITLE
TypeError: this._reloadCall.abort

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10407] opened 2018-07-26 13:13 UTC
Having no favorites and open the favorite overview:

TypeError: this._reloadCall.abort is not a function. (In 'this._reloadCall.abort()', 'this._reloadCall.abort' is undefined)

It's there: https://github.com/nextcloud/server/blob/5445b1ff172d5186530ab0352ac35cb028127312/apps/files/js/favoritesfilelist.js#L71

![bildschirmfoto 2018-07-26 um 15 11 45](https://user-images.githubusercontent.com/245432/43264413-5e129868-90e6-11e8-8f62-14e4f1347c1e.png)

cc @newhinton @skjnldsv @nextcloud/javascript

**Comment by weeman1337** [comment] 2018-08-14 18:54
@MorrisJobke for me it looks like this issue doesn't appear any more..

**Comment by juliushaertl** [comment] 2018-08-16 07:53
I also cannot reproduce it anymore. Let's close this for now.

**Closed by juliushaertl** 2018-08-16 07:53 UTC
Labels: 14-beta-feedback, bug
