### ISSUE TITLE
Broken images in emails when the instance is behind the tunnel

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#39841] opened 2023-08-12 10:55 UTC
Quite often nextcloud instances are located in local networks without any access outside or with the access through VPN. 
In this case all emails send by nextcloud instance through pubic gateways come to mailboxes with stripped images inside (eg logos, icons etc), which are normally linked with the instance, which is not accessible. In general the style of emails might be broken due to that.

![image](https://github.com/nextcloud/server/assets/5199030/40b4208a-a1a1-4617-9b62-176308e75628)

I suggest embedding the images/icons/pictures to the body of emails themselves by default or allow that option as alternative through configuration.

**Comment by joshtrichards** [comment] 2023-08-12 11:44
Duplicate of #13557 

Unfortunately, major web email providers (e.g. Gmail) have issues with embedded images AFAIK.

**Closed** 2023-08-12 16:40 UTC
Labels: enhancement, 0. Needs triage
