### ISSUE TITLE
eTag support for /ocs/v2.php/apps/user_status/api/v1/predefined_statuses endpoint

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#23640] opened 2020-10-23 05:02 UTC
While developing status on client side, I noticed that there is no eTag for above endpoint.
While eTag will not help on server side, they reduce download, processing time, etc. on client side.

Can you add this? 💙

**Comment by joshtrichards** [comment] 2024-07-30 16:15
Duplicate of #22847

**Closed by joshtrichards** 2024-07-30 16:15 UTC
Labels: enhancement, 1. to develop, feature: status
