### ISSUE TITLE
Detect unused db tables (e.g. disabled apps, no longer installed apps, not created by any app) + possibly permit admin selective removal of them

### ISSUE THREAD

**Issue by FahrJo** [nextcloud/server#42753] opened 2024-01-13 10:10 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Since the issue #41253 seems to affect many users and the manual approach to drop obsolet tables seems to be uncomfortable or even unsettling for many, it would be nice to have an automation for that or at least an automatic check.

**Describe the solution you'd like**
Would it be an option to create an occ-command to list all db-tables, not used by any installed app (e.g. `occ db:list-unused-tables` and `occ db:drop-unused-tables`? This check could even be included in the upgrade routine with the option to drop these tables (on the risk of the user). Since more and more apps appear in the app store and then get deprecated over time again, this would be really a useful option to avoid "database-wasting". 

**Describe alternatives you've considered**
For me it seems to be the easiest solution to introduce this central check. Another option would be to only rely on proper db clean-up by the app developers. But possible that there are better options out there that didn't came to my mind.

If there are good reasons against this issue, feel free to close it directly. It was only an idea how to provide a fix for #41253. 💙

**Comment by joshtrichards** [comment] 2024-01-13 14:36
I think this is an interesting approach. Simple and gets the job done. 

While #41253 isn't a bug (the check is intended to prevent problems in the future), people will continue to trigger this new proactive check through at least a full upgrade cycle. And even after that it'll come up on occasion since the origins will still be something we cannot entirely eliminate (old apps, misbehaving apps, multiple Nextcloud installations pointed at same db but with different prefixes configured even though we don't recommend that, remnants from partial restore attempts and debugging sessions, table prefix changes where old tables are orphaned outright, past Nextcloud Server bugs, etc.)

> [Alternatives] Another option would be to only rely on proper db clean-up by the app developers. 

That alternative won't be sufficient since not all of the orphans are due to disabled apps (and I believe we basically have a de facto policy of not removing app data when apps are disabled in order to avoid data loss). 

Your idea to look at all tables not associated with the currently installed core (server) + any currently installed apps would catch everything regardless of origin (good) and most currently mirrors the check that is currently being triggered (rightfully).

Related: #5539

**Comment by FahrJo** [comment] 2024-01-13 15:04
I'know that the #41253 was intended to solve problems but actually starting the upgrade and then throwing the error in the middle of the upgrade has potential to cause issues to many users. And I'm aware that my proposed solution can not catch all cases due to false positives (indeed a good reason to only list and not directly drop "obsolete" tables), but it would be a helpful tool to keep the database tidy.
Another Idea just came to my mind is to do the check for possible conflicts before the existing installation is touched instead of in a later stage where you have to roll back from a backup or do manual fixes in your db. Maybe in the pre-upgrade step `Verify integrity`?
This will probably not solve the problem of manual investigation and resolving the conflicts but can avoid unnecessary unexpected long downtime.

**Comment by solracsf** [comment] 2024-01-13 21:24
See also https://github.com/nextcloud/server/issues/5539

**Comment by joshtrichards** [comment] 2024-02-07 19:06
We might want to consider a setup check (the Admin->Overview ones) for detection of orphan tables. I'm not sure how much logic we already have for this though and it's a little hairy (I suspect) to handle no longer installed apps (versus merely disabled apps).

This also comes up when sometimes someone wants to re-install an app they removed long ago and they also want to clear the data associated with it before re-enabling rather than pulling in the old data.

**Comment by joshtrichards** [comment] 2024-02-07 19:08
I think we can safely consolidate this with #5539 to avoid duplicate discussions. So I'm going to close this as a duplicate of that. I encourage you to subscribe to that issue, @FahrJo. Thanks!

**Closed by joshtrichards** 2024-02-07 19:08 UTC
Labels: enhancement, 0. Needs triage, feature: install and update, feature: apps management
