### ISSUE TITLE
Nextcloud 21.0.1 Upgrade failed

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#26499] opened 2021-04-10 19:39 UTC
While trying to update from NC 20.0.8 to NC 21.0.1, it got to the below step and failed.

![image](https://user-images.githubusercontent.com/59488153/114418626-5044d080-9b78-11eb-8de5-fab7f765f023.png)

> Update app "spreed" from appstore
Repair step: Fix the namespace in database tables
An error occurred.

```
TypeError: Argument 2 passed to OC\\Comments\\Manager::__construct() must implement interface Psr\\Log\\LoggerInterface, instance of OC\\AppFramework\\Logger given, called in /apps/spreed/lib/Chat/CommentsManager.php on line 46 at /lib/private/Comments/Manager.php#77
```

**Comment by acsfer** [comment] 2021-04-11 12:29
@nickvergessen duplicate of https://github.com/nextcloud/spreed/issues/4752 ?

**Comment by axheli** [comment] 2021-04-12 15:18
@acsfer do you know if this will be fixed soon?

**Comment by axheli** [comment] 2021-04-13 00:28
> @nickvergessen duplicate of [nextcloud/spreed#4752](https://github.com/nextcloud/spreed/issues/4752) ?

@acsfer  Thanks :) I think Nick Vegessen has blocked me for some reason because i can see his page but i hope we have a resolutions on this Thanks.

**Comment by axheli** [comment] 2021-04-13 00:37
@acsfer how did you tag nick vergessen? i cant. Maybe he restricted me not use why but hopefully we have some feedback.

**Comment by acsfer** [comment] 2021-04-13 08:37
Please don't tag people randomly just because you have an issue. It is frustrating, i know, but remember one thing; this is an **open-source project**, people give their time for free when they can, if they can. That being said, you have 3 options:

1. Wait for it to be fixed by someone else, or
2. Fix it yourself, or hire someone to do it,
3. Subscribe to https://nextcloud.com/enterprise/

Thanks for understanding 👍

**Comment by axheli** [comment] 2021-04-13 12:35
Completely understand but just trying to help like the rest of us I understand it's a open project that's the reason why I submit these request so Nextcloud can fix and make it a better system as intended personally I don't care too much about being on the newest system but just want to share any feed back with dev and hope to get it fixed I'm not asking for a quick resolution I understand that so no issue at all.

**Closed** 2021-04-20 12:28 UTC
Labels: 0. Needs triage, bug
