### ISSUE TITLE
GUI Bug - Write Proteced Shares (read only)

### ISSUE THREAD

**Issue by dennis-eisen** [nextcloud/server#8501] opened 2018-02-22 12:31 UTC
### Steps to reproduce
1. Share a file as write protected link (read only)
2. Follow share link

### Expected behaviour
There should be no upload sign (+) visible.

### Actual behaviour
There is the normal upload button (+) in the upper left corner. So you mean you can upload, but acually you can't. The button should simply be not there...

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
13.0.0

**Comment by MorrisJobke** [comment] 2018-02-22 13:04
Duplicate of #8343

**Closed by MorrisJobke** 2018-02-22 13:04 UTC
