### ISSUE TITLE
Calendar group sharing not persisted (20.0.5)

### ISSUE THREAD

**Issue by derBobby** [nextcloud/server#25164] opened 2021-01-16 12:08 UTC
### Steps to reproduce
1.) Open calendar app
2.) Select calendar
3.) Share calendar with group
4.) Reload page

### Expected behaviour
Sharing of calendar should have been saved and calendar should be shown as shared

### Actual behaviour
Calendar is not shared

## Server configuration detail

**Operating system:** Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** hub.docker.com: mariadb:10.4.10-bionic

**PHP version:** 

7.4.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.5 - 20.0.5.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 20.0.4

**Where did you install Nextcloud from:** hub.docker.com: nextcloud:20.0.5

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.3
 - documentserver_community: 0.1.8
 - drawio: 0.9.8
 - event_update_notification: 1.2.0
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.1.0
 - groupfolders: 8.2.0
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - keeweb: 0.6.4
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.2.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - previewgenerator: 3.1.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - registration: 0.6.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.5
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "removed",
        "removed"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.5.2",
    "overwrite.cli.url": "https:\/\/removed",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 0,
    "mail_sendmailmode": "smtp",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpdebug": false,
    "mail_smtptimeout": 10,
    "maintenance": false,
    "allow_user_to_change_display_name": false,
    "auth.bruteforce.protection.enabled": true,
    "trashbin_retention_obligation": "730, auto",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR",
        "X-Real-IP"
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "app_install_overwrite": [
        "keeweb"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"isYUJAROrHMOLGVBEXD1","level":0,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"contacts","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":0,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"groupfolders","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":0,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"documentserver_community","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":0,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"drawio","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":0,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"files_sharing","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":0,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"onlyoffice","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":1,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"no app in context","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"Deprecated event type for \\OCA\\DAV\\CalDAV\\CalDavBackend::updateShares: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":1,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"no app in context","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"Deprecated event type for \\OCA\\DAV\\CalDAV\\CalDavBackend::updateShares: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":1,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"no app in context","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"Deprecated event type for \\OCA\\DAV\\CalDAV\\CalDavBackend::updateShares: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":1,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"no app in context","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"Deprecated event type for \\OCA\\DAV\\CalDAV\\CalDavBackend::updateShares: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}
{"reqId":"isYUJAROrHMOLGVBEXD1","level":1,"time":"2021-01-16T12:02:02+00:00","remoteAddr":"93.237.106.122","user":"User name","app":"no app in context","method":"POST","url":"/remote.php/dav/calendars/User%20name/testcal/","message":"Deprecated event type for \\OCA\\DAV\\CalDAV\\CalDavBackend::updateShares: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2"}

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by derBobby** [comment] 2021-01-16 12:11
Additional hint: sharing a calendar for users works fine.

**Comment by jmechnich** [comment] 2021-01-16 17:59
I can confirm this issue for group names containing a whitespace character, e.g. "NC Test". Names consisting of one word seem to work fine, e.g. "Family".

The NC and web server logs don't show any warnings or errors related to this.

**Comment by tims-adb** [comment] 2021-01-18 09:28
The problem also occurs when the group name contains an **umlaut**. We have experienced the problem since the upgrade from Nextcloud 20.0.4 → 20.0.5 on Friday. Members of the group "Geschäftsstelle" don't see the calendar, yet a test group "Geschaeftsstelle" works.

**Comment by jmechnich** [comment] 2021-01-18 12:36
Duplicate of #25165

**Comment by ChristophWurst** [comment] 2021-06-17 15:51
> Duplicate of #25165

Indeed. Let's keep just one.

**Closed by ChristophWurst** 2021-06-17 15:51 UTC
Labels: 0. Needs triage, bug
