### ISSUE TITLE
[Bug]: files index load indefinitely -> `Uncaught (in promise) TypeError: e.vm is null`

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/server#32582] opened 2022-05-24 19:06 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Randomly (it seems), my files index (root folder) hangs on loading and I'm forced to click on the file app again to get it loaded. When it hangs, it doesn't help to just reload the page, as if I had to recall the home URL to get threw the full redirection steps.

No error into NC logs, but FF console shows this:

```js
Uncaught (in promise) TypeError: e.vm is null
    attach files.js:173
    _parseFileInfo client.js:431
    He Underscore
    _parseFileInfo client.js:430
    _parseResult client.js:445
    qe Underscore
    _parseResult client.js:444
    getFolderContents client.js:529
    promise callback*getFolderContents client.js:527
    reload merged-index.js:6249
    changeDirectory merged-index.js:6103
    _onUrlChanged merged-index.js:4828
    Underscore 3
    jQuery 7
    _onPopState merged-index.js:362
    initialize merged-index.js:143
    <anonymous> merged-index.js:405
    Underscore 5
    <anonymous> merged-index.js:404
    EventListener.handleEvent* merged-index.js:401
files.js:173:6
```

### Steps to reproduce

I don't know... just navigate :/ (see also https://github.com/nextcloud/server/issues/32582#issuecomment-1137091626)

### Expected behavior

My folder should load consistently.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version: 23.0.5 -> 24.0.1

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.1.1",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "\/etc\/nextcloud\/skeleton",
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "groupfolders"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - apporder: 0.15.0
  - audioplayer: 3.3.0
  - bookmarks: 10.3.1
  - calendar: 3.3.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - dav: 1.22.0
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - groupfolders: 12.0.0
  - integration_gitlab: 1.0.3
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - richdocuments: 6.1.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - side_menu: 2.3.5
  - support: 1.7.0
  - survey_client: 1.12.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_saml: 5.0.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
None
```

**Comment by cetcondor** [comment] 2022-05-29 23:07
Have the same issue on several instances. Different from @Ornanovitch in our deployments it's Apache instead of Nginx, and regarding the user-backends, SSO-SAML is not activated.

**Comment by effatee** [comment] 2022-05-31 08:04
Yes same issue here as well. 
No specific error caught or raised in the logging.
Just indefinite loading logo, and a click on the "house" breadcrumb is required to load files.

**Comment by danger89** [comment] 2022-06-06 21:03
I can confirm this issue as well. Page will not load, until refresh and trying again from scratch.

```
Uncaught (in promise) TypeError: e.vm is null
    attach files.js:173
    _parseFileInfo client.js:431
    He Underscore
    _parseFileInfo client.js:430
    _parseResult client.js:445
    qe Underscore
    _parseResult client.js:444
    getFolderContents client.js:529
files.js:173:6
```

**Comment by Mer0me** [comment] 2022-06-07 07:58
Some of our users have the very same problem here since v24 : 
- Clicking on Files app shows infinite spinner very often but not systematically
- Clicking on the home button works immediately
- Uncaught (in promise) TypeError: e.vm is null in the console log

We are all using Firefox 91.8.0 ESR on the same network and the same instance of Nextcloud, but only some users have this behavior. Using the impersonate app to reproduce the bug on a non-affected computer doesn't work : bug is not related to user profile, it seems to be browser-related. We cannot reproduce the bug under Chrome.
Maybe a cache issue ?

**Comment by effatee** [comment] 2022-06-07 09:09
But... Just installed Firefox and Chrome to check.
Can't reproduce the issue on any of both after fresh install... login, main files page loads correctly...
Indeed might be a cache issue between v23 and v24...
Will clear cache on Safari and check.

**Comment by Ornanovitch** [comment] 2022-06-07 09:11
OK, so maybe this is somehow a reproducible bug only for a daily/normal use of NC with the same browser.

**Comment by Ornanovitch** [comment] 2022-06-07 09:25
OK thanks! I just cleared my browser's cache, I'll let you know if it works durably :crossed_fingers: 

If it does, I agree with @Mer0me that this is still a problematic behavior

**Comment by danger89** [comment] 2022-06-07 11:59
> > We are all using Firefox 91.8.0 ESR [...] We cannot reproduce the bug under Chrome. [...] Maybe a cache issue ?
> 
> Thanks, nice catch. I'm on Firefox>100. I'll try with Chromium to see if I can reproduce or not.
> 
> @danger89 @effatee @cetcondor are you also using Firefox?

Yes. Firefox 101.0

**Comment by Ornanovitch** [comment] 2022-06-07 22:28
> OK thanks! I just cleared my browser's cache, I'll let you know if it works durably crossed_fingers
> 
> If it does, I agree with @Mer0me that this is still a problematic behavior and that we should let this issue opened.

No luck for me, the bug keeps happening :/

**Comment by Ornanovitch** [comment] 2022-06-15 08:09
No idea sorry

**Comment by MGousseff** [comment] 2022-06-29 13:46
Still happening for me too.

**Comment by bassplayer404** [comment] 2022-07-08 13:53
I have the same problem with firefox and safari. No problems with chrome. NC 24.0.2

**Comment by Mer0me** [comment] 2022-07-14 14:40
The files.js:173:6 seems to refer to /var/www/nextcloud/apps/text/js/text-files.js so I tried to disable "Text" app, and it seems to work. Could you test that on your instances ?

**Comment by Ornanovitch** [comment] 2022-07-14 14:43
I disabled it in order to test, I'll let you know. Good catch!

**Comment by Ornanovitch** [comment] 2022-07-14 15:11
@juliushaertl does it worth moving this issue to the Text App repo or should it remain here?

**Comment by Mer0me** [comment] 2022-07-14 15:28
It takes me some time to find out but I'm proud of me !
I think the issue should be in the Text App repo, or at least there should be a link to this post in the Text repo.

**Comment by juliushaertl** [comment] 2022-07-14 20:09
This is actually a regression caused by a timing issue where the response of the propound was hitting to early with https://github.com/nextcloud/text/pull/2193/files#diff-7b59ac385a5893f449345a411c1f98c8efc6735bab45bed8de4b354a12dc275cR172. 

This got addressed by https://github.com/nextcloud/text/pull/2677 and will be available with the next maintenance release.

**Closed by juliushaertl** 2022-07-14 20:09 UTC
Labels: bug, 0. Needs triage, 24-feedback

**Comment by Ornanovitch** [comment] 2022-07-15 07:39
Awesome, thanks a lot!
