### ISSUE TITLE
[Bug]:  appication menu empty after upgrade to nextcloud 25

### ISSUE THREAD

**Issue by ecy77** [nextcloud/server#34690] opened 2022-10-20 09:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the update from version 24 to 25, the application menu is empty as well as the toolbar

### Steps to reproduce

1. upgrade from 24 to 25 with web updater
2. Go to application menu

### Expected behavior

I was expecting to see the application menu

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "debug": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nuages.achelem.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "25.0.0.18",
        "overwrite.cli.url": "http:\/\/nuages.achelem.org",
        "installed": true,
        "theme": "",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 0,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "app_install_overwrite": [
            "calendar",
            "passwords"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "default_phone_region": "FR",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2022.10.10
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.4.0
  - calendar.8.1
  - calendar.old
  - comments: 1.8.0
  - documentserver_community: 0.1.12
  - encryption
  - federation: 1.8.0
  - files_external: 1.9.0
  - music: 1.6.0
  - ocsms: 2.2.0
  - polls: 3.8.2
  - suspicious_login
  - text: 2.0.0
  - twofactor_totp
  - user_ldap
```

**Comment by cetcondor** [comment] 2022-10-20 11:18
I encountered the problem also in one of my instances, but after executing "occ maintenance:repair" the problem was gone. All other instances did not have the problem.

**Comment by ecy77** [comment] 2022-10-20 14:14
This command doesn't change anything and now I'm not logged in anymore and my main page is empty.
 I have the wallpaper with the clouds, the nextcloud logo, but no more login and password prompt and no menu...

**Comment by szaimen** [comment] 2022-10-25 22:32
Duplicate of https://github.com/nextcloud/server/issues/34716

**Closed by szaimen** 2022-10-25 22:32 UTC
Labels: bug, 0. Needs triage, 25-feedback

**Comment by ecy77** [comment] 2022-10-26 19:54
My bug is not the same as #34716. My PlatformRepository.php file is already fixed.
Can you reopen the bug report?
