### ISSUE TITLE
Cycling redirect with totp enabled

### ISSUE THREAD

**Issue by Loki3000** [nextcloud/server#3702] opened 2017-03-03 22:22 UTC
### Steps to reproduce
1. go to https://domain.tld/ (two factor auth enabled)
2. enter correct login and password (second factor form appears)
3. again go to https://domain.tld/

### Expected behaviour
Expected login form or second factor form

### Actual behaviour
Cycling redirect to https://domain.tld/

### Server configuration
**Operating system**: Linux 4.4.0-65-generic #86-Ubuntu SMP Thu Feb 23 17:49:18 UTC 2017 i686

**Web server:** nginx/1.10.3 (fpm-fcgi)

**Database:** mysql 5.7.17

**PHP version:** 7.1.2-4+deb.sury.org~xenial+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, json, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 11.0.2 (stable) - 11.0.2.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
update

**Where did you install Nextcloud from:** 
from source

**Signing status:**
<details>
	<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>

```
Enabled:
 - activity: 2.4.1
 - calendar: 1.5.1
 - contacts: 1.5.3
 - dav: 1.1.1
 - direct_menu: 0.10.0
 - federatedfilesharing: 1.1.1
 - files: 1.6.1
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 10.1.0
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - previewgenerator: 1.0.1
 - provisioning_api: 1.1.0
 - rainloop: 4.27
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - tasks: 0.9.5
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - twofactor_totp: 1.1.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - comments
 - encryption
 - external
 - federation
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - systemtags
 - user_external
 - user_ldap
 - user_saml
```

</details>

**The content of config/config.php:**

<details>
	<summary>Config report</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/home\/cloud\/data",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "logfile": "\/var\/log\/nextcloud.log",
    "dbtype": "mysql",
    "version": "11.0.2.7",
    "dbname": "db_cloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "theme": "",
    "maintenance": false,
    "mail_from_address": "root",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "forcessl": true,
    "trashbin_retention_obligation": "auto",
    "appstore.experimental.enabled": true,
    "defaultapp": "rainloop",
    "filesystem_check_changes": 0,
    "asset-pipeline.enabled": true,
    "updatechecker": true,
    "logtimezone": "UTC",
    "log_query": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Memcached",
    "memcached_servers": [
        [
            "127.0.0.1",
            11211
        ]
    ],
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "enable_previews": true,
    "preview_max_scale_factor": 1,
    "enabledPreviewProviders": {
        "0": "OC\\Preview\\PNG",
        "1": "OC\\Preview\\JPEG",
        "2": "OC\\Preview\\GIF",
        "11": "OC\\Preview\\Illustrator",
        "12": "OC\\Preview\\Postscript",
        "13": "OC\\Preview\\Photoshop",
        "14": "OC\\Preview\\TIFF"
    },
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** 
Dropbox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Operating system:**
windows

#### Browser log
<details>
	<summary>Browser log</summary>

```
302 GET /
302 GET /apps/rainloop/
302 GET /
302 GET /apps/rainloop/
...
```
</details>

**Comment by nickvergessen** [comment] 2017-03-06 12:42
@ChristophWurst

**Comment by ChristophWurst** [comment] 2017-03-06 12:53
> again go to https://domain.tld/

You manually visited that page or you were redirected to it?

**Comment by Loki3000** [comment] 2017-03-06 14:01
Manually. Or by link at bottom of page.

**Comment by ChristophWurst** [comment] 2017-03-13 13:27
Can't reproduce.

My steps/requests against the server:
* GET /login (manually)
* POST /login (submit form manually)
* GET /login/selectchallenge (redirected to)
* GET / (manually)
* GET / login/selectchallenge?redirect_url=%252Fapps%252Ffiles%252F (redirected to)

**Comment by Loki3000** [comment] 2017-03-13 13:40
* GET /login (manually)
* POST /login (submit form manually)
* GET /login/challenge/totp (redirected to)
* GET / (manually)
* GET /apps/rainloop/ (redirected to default app)
* GET / (redirected to)
* GET /apps/rainloop/ (redirected to)
last two in infinite cycle

**Comment by ChristophWurst** [comment] 2017-03-13 15:20
I've tried again, but I cannot reproduce this, even with a fresh NC11 (stable), Windows and FF: https://saucelabs.com/beta/tests/b0d7ee3132de46349a579dc2ededa5b0/watch

Could you please try to disable third-party apps and see if the problem remains?

**Comment by Loki3000** [comment] 2017-03-13 18:15
You right: if I set rainloop as a default app - I get cycling reload. If I set some else app as default - all works well.
So it seems that's rainloop error.

**Comment by ChristophWurst** [comment] 2017-03-13 18:18
Okay, cool. Might be worth filing a bug report in their repo :-)

**Comment by Loki3000** [comment] 2017-03-13 18:19
Now I know where to dig. So maybe it will be PR:)

**Comment by ChristophWurst** [comment] 2017-03-13 18:30
Even better ;-)

**Comment by Loki3000** [comment] 2017-03-13 20:51
Hmm... seems that the reason is
```
OCP\User::checkLoggedIn();
```
it's almost first string in rainloop app.
I'm add same call in files app and get same error with redirects.
So question: is it method deprecated now?
Some base apps uses it. You can set files_trashbin, files_sharing or systemtags as a default app and you will get infinite refresh with second factor.

**Comment by ChristophWurst** [comment] 2017-03-13 21:05
See https://github.com/nextcloud/server/pull/3682 -> it's deprecated and apps using it will break with NC12+. Would be great if you could warn the developers of the apps where you saw it being used!

**Comment by ChristophWurst** [comment] 2017-03-13 21:08
Still there:

https://github.com/nextcloud/server/blob/af16416de51a40e3fbb1e8499bbe8bf3b77ab5af/lib/public/User.php#L149-L156, which invokes https://github.com/nextcloud/server/blob/af16416de51a40e3fbb1e8499bbe8bf3b77ab5af/lib/private/legacy/util.php#L966-L989

**Comment by Loki3000** [comment] 2017-03-14 06:16
Well... It's needs to add reproduce step:
0.  Set 'defaultapp' in config.php to files_trashbin, files_sharing or systemtags.

**Comment by ChristophWurst** [comment] 2017-04-03 09:47
> Well... It's needs to add reproduce step:
> 0. Set 'defaultapp' in config.php to files_trashbin, files_sharing or systemtags.

Those are apps that cannot really be used as default app it seems. Did you file the issue in the roundcube repo? :-)

**Comment by Loki3000** [comment] 2017-04-03 11:26
No, i'm not. I'm no understand whats wrong with rainloop app? You said that used code isn't deprecated and it's using in native apps. So thirdpart apps could be use it too?

**Comment by ChristophWurst** [comment] 2017-04-03 11:45
Then please point me the mentioned code. Where does the app call `OCP\User::checkLoggedIn();`?

**Comment by Loki3000** [comment] 2017-04-03 12:02
https://github.com/pierre-alain-b/rainloop-nextcloud/tree/master/rainloop
app.php,  	index.php and personal.php has ```OCP\User::checkLoggedIn();``` as a first command.

**Comment by ChristophWurst** [comment] 2017-04-03 12:33
Fix is in https://github.com/nextcloud/server/pull/4192

**Closed** 2017-04-04 20:47 UTC
Labels: 3. to review, bug, feature: authentication
