### ISSUE TITLE
Share directory Upload + Read only

### ISSUE THREAD

**Issue by jee-r** [nextcloud/server#6620] opened 2017-09-22 21:22 UTC
Hello,

Would it be possible to add an upload + read-only option for a shared folder.

![capture d ecran_2017-09-22_22-29-35](https://user-images.githubusercontent.com/10530469/30764402-0f93ab56-9feb-11e7-98b5-9196f0db10ed.png)

Use case
This would allow sharing photos (read-only) with a friend who does not have a nextcloud account, but also to upload his own.

Problem with read and write is that my friend can modify or delete files that i have uploaded. 

Thank's

**Comment by blizzz** [comment] 2017-09-25 12:54
iirc upload requires write. @nextcloud/sharing

**Comment by rullzer** [comment] 2017-09-25 14:13
Yes upload requires write. But delete and update are separate permissions. I think this is more about how do we show yet another use case to the user. I'm sure @jancborchardt would kill me if we just extend that list with every possible option.

**Comment by jancborchardt** [comment] 2017-09-25 14:40
I mean, it _is_ a good point cause we also have files drop. The current workaround would be to share your own pictures with a read-only link and give the friend a files drop, or fully editable folder link.

This would be the options, with the new one in bold:
- Editing – default
- Read-only
- Upload-only (no reading)
- **Read-only with upload**

In this new mode, uploaded files with the same name would automatically need to have a " (2)" appended.

We _could_ change it from radio buttons to a dropdown instead … what do @nextcloud/designers think?

**Comment by rullzer** [comment] 2017-09-25 14:47
@jancborchardt your solution currently won't work as we don't have multiple link shares as an option.

**Comment by pixelipo** [comment] 2017-10-19 11:02
What about simply having 3 independent (checkbox) items:

- view (read)
- upload
- edit

**Comment by Schmuuu** [comment] 2018-04-30 21:46
I'm glad somebody opened an issue for this already. I haven't noticed this until a user of mine (family member) informed me about an "accident". When he shared photos via a public link to his friends, he wanted to allow his friends to view the photos and upload additional photos. One person who accessed the public link deleted the photos however. 
At first I was confused why he would allow the deletion of files via a **public link**, but when I checked, I saw that there are not the same options for public sharing like for internal sharing.

To be protected against further accidents, it would be nice if this feature request could be implemented soon. I really like the idea of @pixelipo

**Comment by jeyca** [comment] 2018-07-16 22:31
> What about simply having 3 independent (checkbox) items:
> 
>     view (read)
>     upload
>     edit

I wonder why this hasn't already been in the first place, kind of this has been established already decades ago in linux filesystems.

**Comment by billetj** [comment] 2018-07-19 13:43
Does anyone know if something has been done for that ?

**Comment by jwillmer** [comment] 2018-07-19 14:50
I found a tutorial on the internet a couple of months ago of a guy who edited the database in order to get this functionality - can't find the link anymore. 

Basically there is a table with all shared folders and there permission levels. The permission level is a number and if u calculate the number for upload + view permission and set this number for a folder you get a folder that people can upload to and view the uploaded files. I did this for my Nextcloud instance as well and it works without a problem. 

So this feature contains really not much work. There is basically only the GUI missing to make this wok for all people. For me it is too much of a hassle to setup the development environment only to add this feature and make a pull request - sorry.

**Comment by jancborchardt** [comment] 2018-07-19 15:57
As you can see from the set milestone, it’s currently planned to probably have it in Nextcloud 15 (which is the release after the one we are currently finishing up).

> So this feature contains really not much work. There is basically only the GUI missing to make this wok for all people. For me it is too much of a hassle to setup the development environment only to add this feature and make a pull request - sorry.

@jwillmer That’s really a bummer, we would be very happy to help you set it up. Just saw you are in Stuttgart – we regularly have hackweeks there and you are very welcome to join us. :)

**Comment by algakzru** [comment] 2019-10-04 02:30
> As you can see from the set milestone, it’s currently planned to probably have it in Nextcloud 15 (which is the release after the one we are currently finishing up).
> 
> > So this feature contains really not much work. There is basically only the GUI missing to make this wok for all people. For me it is too much of a hassle to setup the development environment only to add this feature and make a pull request - sorry.
> 
> @jwillmer That’s really a bummer, we would be very happy to help you set it up. Just saw you are in Stuttgart – we regularly have hackweeks there and you are very welcome to join us. :)

It's been more than one year since the last comment, is there any progress on adding this functionality ?

**Comment by muellerlukas** [comment] 2019-10-04 02:52
Fun fact: It's already possible wehen you set the "permissions"-value in "oc_share", only a option in the GUI is missing. :(

Available options can be found in lib/public/Constants.php

**Comment by algakzru** [comment] 2019-10-04 08:20
> Fun fact: It's already possible wehen you set the "permissions"-value in "oc_share", only a option in the GUI is missing. :(
> 
> Available options can be found in lib/public/Constants.php

Thank you, that's exactly what I was looking for :)
Changing permission value from 15 to 5 manually in the database did the trick.

**Comment by skjnldsv** [comment] 2019-10-30 20:33
Duplicate of https://github.com/nextcloud/server/issues/8479#issuecomment-368878425

**Comment by najtin** [comment] 2020-03-09 10:32
> Duplicate of [#8479 (comment)](https://github.com/nextcloud/server/issues/8479#issuecomment-368878425)

this is not a duplicate
this issue is about having the option to upload + read-only
and if i understand it correctly the referenced issue does not solve this. as pointed out before this is only a gui issue.

**Comment by szaimen** [comment] 2020-03-09 10:35
@najtin you are right!
@skjnldsv please reopen the issue :)

**Comment by huuub** [comment] 2020-04-05 09:52
Giving nextcloud a serious chance, pretty disappointed 1 day after installation that this is not possible. Really weird

**Comment by skjnldsv** [comment] 2020-04-05 10:15
Ah no, still a duplicate of https://github.com/nextcloud/server/issues/8479#issuecomment-368878425

**Closed by skjnldsv** 2020-04-05 10:15 UTC
Labels: 1. to develop, design, enhancement, feature: sharing

**Comment by szaimen** [comment] 2020-04-05 10:37
@skjnldsv why shouls this be a duplicate of https://github.com/nextcloud/server/issues/8479#issuecomment-368878425?
There is nothing written about "filedrop and seeing already uploaded files" at the same time....

**Comment by szaimen** [comment] 2020-04-05 10:40
This option here is about files drop (can add **and** list files but not edit them)

**Comment by skjnldsv** [comment] 2020-04-05 10:59
> There is nothing written about "filedrop and seeing already uploaded files" at the same time....

Yes, this is just about wording here.
The underlying issues is the available permissions on link shares.
This is covered by #8479

**Comment by gloomytree** [comment] 2020-08-12 13:53
> 
> 
> Fun fact: It's already possible when you set the "permissions"-value in "oc_share", only a option in the GUI is missing. :(
> 
> Available options can be found in lib/public/Constants.php

Came here via https://help.nextcloud.com/t/allow-public-upload-and-show-but-not-delete/2874/22 and this page should be indexed higher by google. Permission 5 is neccessary for a lot of usecases and i hope to see a GUI option in the future.

**Comment by jee-r** [comment] 2020-08-15 13:53
> Ah no, still a duplicate of [#8479 (comment)](https://github.com/nextcloud/server/issues/8479#issuecomment-368878425)

I don't understand your reasoning, why you're closing this issue when it's older. If indeed the two issue are similar then the other one is a duplicate of this one.

**Comment by marvinjuette** [comment] 2020-10-13 11:33
I like the options you get offered when sharing internally. Why don't use them for public link sharing?

**Comment by JanKerbl** [comment] 2020-12-10 22:30
> 
> 
> Fun fact: It's already possible when you set the "permissions"-value in "oc_share", only a option in the GUI is missing. :(
> 
> Available options can be found in lib/public/Constants.php

Is there a guide how to do this?

**Comment by muellerlukas** [comment] 2020-12-12 11:31
> Is there a guide how to do this?

First create a link share, you shoudl get sth like "https://NEXTCLOUDDOMAIN/s/TOKEN". You'll need the token later.

In Constants.php you can find the permissions
```
public const PERMISSION_CREATE = 4;
public const PERMISSION_READ = 1;
public const PERMISSION_UPDATE = 2;
public const PERMISSION_DELETE = 8;
public const PERMISSION_SHARE = 16;
public const PERMISSION_ALL = 31;
```

Just sum the values to "build" your permission. E.g: Create + read -> 4 + 1 -> 5

Then open your database with phpmyadmin or sth, open the table "oc_share" and search for the row where the token-column matches your token.
Then set the column "permissions" for the row to the persmission you calculated in the step before.

Hope this helps.

**Comment by VChernenkoRT** [comment] 2021-04-10 16:23
> > Is there a guide how to do this?
> 
> First create a link share, you shoudl get sth like "https://NEXTCLOUDDOMAIN/s/TOKEN". You'll need the token later.
> 
> In Constants.php you can find the permissions
> 
> ```
> public const PERMISSION_CREATE = 4;
> public const PERMISSION_READ = 1;
> public const PERMISSION_UPDATE = 2;
> public const PERMISSION_DELETE = 8;
> public const PERMISSION_SHARE = 16;
> public const PERMISSION_ALL = 31;
> ```
> 
> Just sum the values to "build" your permission. E.g: Create + read -> 4 + 1 -> 5
> 
> Then open your database with phpmyadmin or sth, open the table "oc_share" and search for the row where the token-column matches your token.
> Then set the column "permissions" for the row to the persmission you calculated in the step before.
> 
> Hope this helps.

how fluent, user-friendly is this solution for generic issue noted **5 or more years ago**.
disappointed 1 day after installation by this too

**Comment by VChernenkoRT** [comment] 2021-04-10 19:20
I have changed files_sharing_tab.js* files for PUT /ocs/v2.php/apps/files_sharing/api/v1/shares/10 with permissions: "23" or "7" payload, but server still response with permissions: 31. Where the permissions value is filtered before putting it into DB?

**Comment by Ashu11-A** [comment] 2022-01-13 03:36
É incrivelmente decepcionante como isso não foi implementado ainda, era pra ter saído no Nextcloud 15? Mas se passaram anos e ainda não foi implementado por pura preguiça.
