### ISSUE TITLE
Contacts menu handle scrolls on mobile

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#47741] opened 2024-09-04 13:41 UTC
> - [ ] Contacts menu handle scrolls on mobile
> 
> 
> 
> [Bildschirmaufzeichnung vom 2024-08-06 07-44-57.webm](https://github.com/user-attachments/assets/fb94e450-5347-4777-af79-3a00f2986d7a)
> 
>  

 _Originally posted by @ChristophWurst in [#46016](https://github.com/nextcloud/server/issues/46016#issuecomment-2270432581)_

**Comment by susnux** [comment] 2024-09-04 14:20
Duplicate of https://github.com/nextcloud/server/issues/46997

**Closed** 2024-09-04 14:20 UTC
