### ISSUE TITLE
Migration from oc 10.0.3 to nc 12 fails.

### ISSUE THREAD

**Issue by tuxmaster** [nextcloud/server#6532] opened 2017-09-16 08:43 UTC
Using the updater from:

> https://nextcloud.com/migration/

fails with:

> Current version is 10.0.3.
> Could not determine migration path to Nextcloud.

**Comment by blizzz** [comment] 2017-09-18 10:28
As of now and upcoming 12.0.3, from 10.0.3 cannot be upgraded, yet. 

https://github.com/nextcloud/server/blob/48372f9108e10aed97639fa21e87d65d13fabea3/version.php#L39-L42

**Comment by spaprzycki** [comment] 2017-09-24 11:46
Hello,

Are there any timeframes for support of migration from OC 10.0.3 to NC?

I have been running latest OC 9.1 and could not get it to migrate to any latest bugfix release of main NC versions - tried 10, 11 & 12 - most of the time my attempts were ended with:

```
Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed
```
I have decided to jump to latest OC, so ended up with 10.0.3 only to learn that this is also unsupported - with the familiar message again. I have tried latest NC11 & NC12.

Nextcloud looks to be the way to go, but so far I could check that myself :(

Regards,
Sergiusz

**Comment by blizzz** [comment] 2017-09-24 13:35
@jospoortvliet can you give a pointer?

**Comment by Pka78** [comment] 2017-09-25 06:41
I'm waiting this upgrade path too.

**Comment by jospoortvliet** [comment] 2017-09-25 07:32
Count on 12.0.4 being able to do this upgrade at the soonest. It needs some real testing as ownCloud has been backporting a lot of features to 10.0.x which impacts stability and might make upgrading harder. So this will take some 4-6 weeks, depending on how long it takes us to do 12.0.4.

**Comment by drackg** [comment] 2017-11-02 14:57
hi guys. any news on this upgrade from oc 10.0.0.x to nextcloud?

**Comment by shaneonabike** [comment] 2017-11-02 18:36
I was also just wondering when you would expect to release 12.0.4 so I can mark it on my calendar and then migrate. I like what you are doing and would prefer to move over but missed all the right moments - and when I tried before it didn't go.

**Comment by jospoortvliet** [comment] 2017-11-02 19:30
Support for upgrading from oC 10.0.3.3 is already in Master. When 12.0.4 comes out I don't know but I guess it won't take too much longer...

* https://github.com/nextcloud/server/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+12.0.4%22 ➡️ 12.0.4 progress
* https://github.com/nextcloud/server/pull/6878 ➡️ support for migration

**Comment by jospoortvliet** [comment] 2017-11-02 19:31
Let's close this issue, it will be fixed in 12.0.4 ;-)

**Closed by jospoortvliet** 2017-11-02 19:31 UTC
Labels: enhancement, feature: owncloud migration

**Comment by mdeweerd** [comment] 2017-12-10 21:50
I upgraded to OC 10.0.3.3 and tried migration to NC 12.0.4.
No success.

This is in the updater.log:

```
2017-12-10T11:51:53+0000 dfrDcVnWCx [info] end of checkForUpdate() Could not determine migration path to Nextcloud.
2017-12-10T21:37:01+0000 dqMqE3F1Hx [info] request to updater
2017-12-10T21:37:01+0000 dqMqE3F1Hx [info] currentStep()
2017-12-10T21:37:01+0000 dqMqE3F1Hx [info] show HTML page
2017-12-10T21:37:01+0000 dqMqE3F1Hx [info] current version: 10.0.3 build time: 2017-09-15T14:47:05+00:00 5ae38448f1f98a5a9a1a629a5094a34bb64550e6
2017-12-10T21:38:21+0000 qUdMzOiksp [info] request to updater
2017-12-10T21:38:21+0000 qUdMzOiksp [info] currentStep()
2017-12-10T21:38:21+0000 qUdMzOiksp [info] show HTML page
2017-12-10T21:38:21+0000 qUdMzOiksp [info] current version: 10.0.3 build time: 2017-09-15T14:47:05+00:00 5ae38448f1f98a5a9a1a629a5094a34bb64550e6
2017-12-10T21:38:21+0000 qUdMzOiksp [info] getUpdateServerResponse()
2017-12-10T21:38:21+0000 qUdMzOiksp [info] updaterServer: https://updates.nextcloud.org/updater_server/
2017-12-10T21:38:21+0000 qUdMzOiksp [info] releaseChannel: stable
2017-12-10T21:38:21+0000 qUdMzOiksp [info] internal version: 10.0.3.3
2017-12-10T21:38:21+0000 qUdMzOiksp [info] updateURL: https://updates.nextcloud.org/updater_server/?version=10x0x3x3xxxstablexx2017-09-15T14%3A47%3A05%2B00%3A00+5ae38448f1f98a5a9a1a629a5094a34bb64550e6x5x6x30
2017-12-10T21:38:21+0000 qUdMzOiksp [info] checkForUpdate() Array
(
)

2017-12-10T21:38:21+0000 qUdMzOiksp [info] end of checkForUpdate() No update available.
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] request to updater
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] currentStep()
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] show HTML page
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] current version: 10.0.3 build time: 2017-09-15T14:47:05+00:00 5ae38448f1f98a5a9a1a629a5094a34bb64550e6
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] getUpdateServerResponse()
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] updaterServer: https://updates.nextcloud.org/owncloud-migration/
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] releaseChannel: stable
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] internal version: 10.0.3.3
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] updateURL: https://updates.nextcloud.org/owncloud-migration/?version=10x0x3x3xxxstablexx2017-09-15T14%3A47%3A05%2B00%3A00+5ae38448f1f98a5a9a1a629a5094a34bb64550e6x5x6x30
2017-12-10T21:39:07+0000 G2HnG59hwQ [info] checkForUpdate() Array
(
)

2017-12-10T21:39:07+0000 G2HnG59hwQ [info] end of checkForUpdate() Could not determine migration path to Nextcloud.
2017-12-10T21:39:43+0000 UEcjVOfQg0 [info] request to updater
2017-12-10T21:39:43+0000 UEcjVOfQg0 [info] currentStep()
2017-12-10T21:39:43+0000 UEcjVOfQg0 [info] show HTML page
2017-12-10T21:39:43+0000 UEcjVOfQg0 [info] current version: 10.0.3 build time: 2017-09-15T14:47:05+00:00 5ae38448f1f98a5a9a1a629a5094a34bb64550e6
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] request to updater
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] currentStep()
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] show HTML page
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] current version: 10.0.3 build time: 2017-09-15T14:47:05+00:00 5ae38448f1f98a5a9a1a629a5094a34bb64550e6
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] getUpdateServerResponse()
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] updaterServer: https://updates.nextcloud.org/updater_server/
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] releaseChannel: stable
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] internal version: 10.0.3.3
2017-12-10T21:41:52+0000 WSYDM5CuNS [info] checkForUpdate() Array
(
)

2017-12-10T21:41:52+0000 WSYDM5CuNS [info] end of checkForUpdate() No update available.
```

**Comment by blizzz** [comment] 2017-12-11 10:17
@mdeweerd please create a new issue

**Comment by jospoortvliet** [comment] 2017-12-11 13:37
@blizzz @mdeweerd see here https://github.com/nextcloud/owncloud-web-migrator/issues/7
I don't think the problem is in the core but in the updater or updater-server. I've tried to find where the available update/upgrades are defined but couldn't find it 😢

**Comment by mdeweerd** [comment] 2017-12-11 18:05
I decided to upgrade from the CLI which worked.

**Comment by CliffMitchell** [comment] 2017-12-13 16:30
Is anyone looki9ng into this problem please?
Thanks,
Cliff

**Comment by shaneonabike** [comment] 2017-12-13 17:35
@mdeweerd by CLI you mean from the command line?

**Comment by mdeweerd** [comment] 2017-12-14 10:11
Yes.  CLI = Command Line Interface.  I put the service in maintenance mode (using the config file), moved the old sources to another directory, extracted the Nextcloud source in the original location, copied the original configuration file and proceeded with the upgrade, and disabled maintenance mode.

**Comment by shaneonabike** [comment] 2017-12-15 14:29
What a brainblock of course CLI means that... Thanks for the info! I'll give it a shot and report back

**Comment by CliffMitchell** [comment] 2017-12-19 15:32
Is anyone looking into this problem please?
Thanks,
Cliff

**Comment by chriscroome** [comment] 2018-02-13 12:06
I just hit this issue with ownCloud 10.0.6.1 &mdash; I had to edit `config/config.php` to set:

```
'version' => '10.0.5',
```

Before the migration could proceed.

**Comment by bcutter** [comment] 2018-02-17 20:40
@chriscroome: I´m in the same situation now. Your "hack" didn´t work for me, occ upgrade still gives the same error message. Did you restart the whole migration process or only edit config.php and performec occ upgrade again?

**Comment by chriscroome** [comment] 2018-02-18 11:41
@bcutter sorry but I only set the `www-data` user to record a `~/.bash_history` file after I completed the migration so I don't have a record of all the `occ` commands I ran, from memory [setting the `core:vendor` variable](https://help.nextcloud.com/t/migration-from-owncloud-9-1-6-to-nextcloud-10-0-5-fails/13523/15
) might have helped:

```
occ config:app:set --value "owncloud" core vendor
```

I also had an issue with the fact that the ownCloud server was running Debian Jessie and the new Nxtcloud server was running Debian Stretch and I had to fix the caching settings in the `config.php` file.

I haven't noticed any side effects, everything seems to be working now. Good luck :-)

**Comment by bcutter** [comment] 2018-02-18 12:57
@chriscroome: core:vendor variable is set correctly (owncloud). Migration in my case is happening on the same server (Raspbian Jessie). I have no idea how you managed to get over the https://github.com/nextcloud/server/issues/8256 (maybe you don´t use OAuth?) but i think I simply should wait until there is a proven, reliable and therefore tested migration path from OC v10.0.6.1 to NC.

**Comment by chriscroome** [comment] 2018-02-18 13:48
@bcutter I guess I'm not using OAuth, I didn't hit that issue,

**Comment by bcutter** [comment] 2018-02-18 13:52
OK. Maybe that would be a (ugly) workaround... remove OAuth before migrating the way you managed to.

**Comment by bcutter** [comment] 2018-03-04 02:32
See https://github.com/nextcloud/server/issues/8256#issuecomment-370196722 for OAuth database upgrade error "workaround".
