### ISSUE TITLE
filenames are shortened and not visible on narrow displays after an upgrade to NC17

### ISSUE THREAD

**Issue by elpraga** [nextcloud/server#17428] opened 2019-10-06 12:14 UTC
### Steps to reproduce
1. open the Files app on a phone (Redmi Note 7 in my case)
2.modified time is fully visible (two monts ago)
3. only the first letter of a filename or a folder name is visible

### Expected behaviour
Filenames are visible instead of modified time / the view is scrolable

### Actual behaviour
1. open the Files app on a phone (Redmi Note 7 in my case)
2.modified time is fully visible (two monts ago)
3. only the first letter of a filename or a folder name is visible

![Screenshot_2019-10-06-05-32-05-887_com android chrome](https://user-images.githubusercontent.com/13814570/66269015-9dd5d400-e843-11e9-9a81-8beeafcf2874.png)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
17.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.5
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2019-10-06 12:27
Duplicate of https://github.com/nextcloud/server/issues/17428

**Closed by kesselb** 2019-10-06 12:27 UTC
Labels: 0. Needs triage, bug

**Comment by elpraga** [comment] 2019-10-06 12:42
@kesselb this issue is #17428 it can hardly be a duplicate of itself.

Dud you have a different issue in mind?

**Comment by elpraga** [comment] 2019-10-06 14:12
It is a duplicate of https://github.com/nextcloud/server/issues/17364

**Comment by kesselb** [comment] 2019-10-06 14:31
@elpraga :see_no_evil:
