### ISSUE TITLE
Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi"[Bug]: 

### ISSUE THREAD

**Issue by zuck3r** [nextcloud/server#42256] opened 2023-12-14 02:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Aktualisierung auf 28.0.0

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die [Nextcloud Community](https://github.com/nextcloud/server/issues).

### Steps to reproduce

1. Tried upgrade by cli
_php occ app:update --all_
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
**Exception: Database error when running migration 28000Date20230906104802 for app core
Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".**
Update failed
Maintenance mode is kept active
Resetting log level

2. Tried updater:
cd updater/

php updater.phar
Nextcloud Updater - version: v27.1.0rc3-34-g94c444b dirty

Current version is 28.0.0.

Update to Nextcloud 28.0.0 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-28.0.0.zip
Open changelog ↗

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] Y
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
**Exception: Database error when running migration 28000Date20230906104802 for app core
Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".**
Update failed
Maintenance mode is kept active
Resetting log level

Keep maintenance mode active? [y/N] N
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Maintenance mode disabled

Maintenance mode is disabled

3. Tried Web Updater: told me to inform community :)

### Expected behavior

upgrade to Nextcloud 28

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            removed
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "removed",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "debug": "\u2018false\u2019",
        "loglevel": 0,
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "quickaccesssorting",
            "defaultlinkopen",
            "admin_notifications",
            "files_ebookreader",
            "files_external_gdrive",
            "mindmap_app",
            "files_reader",
            "whiteboard",
            "apporder",
            "keeweb",
            "breezedark",
            "unroundedcorners",
            "unsplash",
            "podcast",
            "news"
        ],
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "htaccess.RewriteBase": "\/",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0",
            "timeout": "1.5"
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "enforce_theme": "breezedark"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - apporder: 0.15.0
  - bookmarks: 13.1.1
  - breezedark: 27.0.0
  - calendar: 4.6.0
  - cloud_federation_api: 1.10.0
  - contacts: 5.5.0
  - dav: 1.27.0
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_versions: 1.20.0
  - keeweb: 0.6.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.6
  - news: 24.0.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quickaccesssorting: 3.0.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - side_menu: 3.11.2
  - spreed: 17.1.3
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.15.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - whiteboard: 0.0.3
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.18.0
  - admin_notifications: 1.0.2 (installed 1.0.2)
  - bruteforcesettings: 2.8.0 (installed 2.4.0)
  - circles: 28.0.0-dev (installed 27.0.0)
  - comments: 1.18.0 (installed 1.13.0)
  - contactsinteraction: 1.9.0 (installed 1.1.0)
  - dashboard: 7.8.0 (installed 7.3.0)
  - drawio: 2.1.4 (installed 2.1.4)
  - duplicatefinder: 1.1.4 (installed 1.1.4)
  - encryption: 2.16.0 (installed 2.8.1)
  - event_update_notification: 2.3.0 (installed 2.3.0)
  - federation: 1.18.0 (installed 1.6.0)
  - files_automatedtagging: 1.17.0 (installed 1.17.0)
  - files_ebookreader: 0.0.1 (installed 0.0.1)
  - files_external: 1.20.0 (installed 1.10.0)
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_mindmap: 0.0.30 (installed 0.0.30)
  - files_sharing: 1.20.0 (installed 1.15.0)
  - files_trashbin: 1.18.0 (installed 1.11.0)
  - firstrunwizard: 2.17.0 (installed 2.5.0)
  - fulltextsearch: 27.0.3 (installed 27.0.3)
  - fulltextsearch_elasticsearch: 27.0.5 (installed 27.0.5)
  - ncdownloader: 1.0.20 (installed 1.0.20)
  - password_policy: 1.18.0 (installed 1.13.0)
  - podcast: 0.3.1 (installed 0.3.1)
  - quicknotes: 0.8.10 (installed 0.8.10)
  - sharebymail: 1.18.0 (installed 1.6.0)
  - support: 1.11.0 (installed 1.3.0)
  - survey_client: 1.16.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.0.1)
  - weather_status: 1.8.0 (installed 1.0.0)
```

**Comment by solracsf** [comment] 2023-12-14 09:24
Duplicate of https://github.com/nextcloud/server/issues/41253

**Closed** 2023-12-14 09:26 UTC
Labels: bug, 0. Needs triage, 28-feedback
