### ISSUE TITLE
CSS folder highlight issue in dark theme

### ISSUE THREAD

**Issue by STaRDoGG** [nextcloud/server#24805] opened 2020-12-22 01:48 UTC
Using NC version 20.04 Stable in Docker

When  loading a list of folders, i.e. when first logging in, there're bright white 'highlight' boxes that look like it's not meant to look that way in a dark theme. It doesn't match the theme, is a bit blinding, and you can't see the image or text for those folders while lit up.

I could change them just for my own instance using something like the chrome Stylus addon, but it seems it should be  baked right into the theme itself.

![image](https://user-images.githubusercontent.com/1524526/102839143-7544e600-43c5-11eb-9271-222e7307c2f4.png)

**Comment by szaimen** [comment] 2021-06-18 14:13
Duplicate of https://github.com/nextcloud/server/issues/18685

**Closed by szaimen** 2021-06-18 14:13 UTC
Labels: 0. Needs triage, bug
