### ISSUE TITLE
Decouple share link password complexity settings

### ISSUE THREAD

**Issue by jficz** [nextcloud/server#43823] opened 2024-02-25 13:38 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When sharing a link (folder), password complexity is enforced with the same rules as User (auth) passwords. This makes choosing simple passwords for short-term or less-sensitive content challenging and/or requires either setting unnecessarily complex passwords for sharing or relaxing auth passwords complexity requirements - both is bad.

**Describe the solution you'd like**
Decouple share password complexity settings from User (auth) passwords. That is, have two separate password rules, one for auth passwords and one for share passwords. Maybe add and option to link the rules to keep continuity and compatibility with current situation.

**Describe alternatives you've considered**
N/A

**Additional context**
There is a (slightly dated) [discussion](https://help.nextcloud.com/t/allow-simple-password-for-folder-sharing/115318) on Nextcloud Discourse about this topic presenting a couple of valid use cases.

Another valid use case might be preventing privacy-invading services like Gmail or Facebook from indexing and caching the content of the share (if the link is shared via them) while still keeping the share's simplicity.

**Comment by susnux** [comment] 2024-03-01 18:21
Duplicate of https://github.com/nextcloud/password_policy/issues/117

**Closed by susnux** 2024-03-01 18:21 UTC
Labels: enhancement, 0. Needs triage
