### ISSUE TITLE
Nextcloud 18 notes, lists or links

### ISSUE THREAD

**Issue by janarzz** [nextcloud/server#19088] opened 2020-01-23 06:50 UTC
Hey, i have problem with Nextcloud 18 notes, lists and links spacing. Its to big. Why ?
Pic link is here...
https://www.upload.ee/image/11018372/nextcloud.png

**Comment by Beeez** [comment] 2020-02-07 14:59
I get this as well.

**Comment by simmstein** [comment] 2020-03-03 08:06
Remove the file `Readme.md`.

**Comment by kesselb** [comment] 2020-03-03 18:02
Sounds like a duplicate of https://github.com/nextcloud/text/issues/586

**Closed by kesselb** 2020-03-03 18:02 UTC
Labels: 0. Needs triage, bug
