### ISSUE TITLE
Nextcloud 16.0.1 RC1 Some files have not passed the integrity check (Passman/Right Click)

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#15559] opened 2019-05-15 22:43 UTC
### Steps to reproduce
1. Upgrade Nextcloud from version 15.0.2 to 16.0.1 RC1
2. Start GUI > Integrity Check

### Expected behaviour

Integrity check should be ok.

### Actual behaviour

Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)

Even by completely de-installing/removing the both apps, the errors will not disappear !
(APPS: "passman" & "rightclick")

Check the app list at the bottom - those apps are not installed anymore.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md
- passman
	- EXCEPTION
		- Exception
		- App not found

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

    [passman] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => Exception
                    [message] => App not found
                )

        )

)

### Server configuration

Operating System: System Linux 3.10.0-957.1.3.el7.x86_64

Webserver: Apache/2.4.6 (CentOS) OpenSSL1.0.2k-fips

Database: mysql 5.5.60-MariaDB,

PHP version: PHP Version => 7.2.10

[PHP Modules] apcu bcmath bz2 calendar Core ctype curl date dba dom enchant exif fileinfo filter ftp gd gettext hash iconv imagick intl json ldap libxml mbstring mysqli mysqlnd odbc openssl pcntl pcre PDO pdo_mysql PDO_ODBC pdo_pgsql pdo_sqlite pgsql Phar posix pspell readline recode Reflection session shmop SimpleXML snmp soap sockets SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl Zend OPcache zip zlib [Zend Modules] Zend OPcache

Nextcloud: - version: 16.0.1.0

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            xxxx
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "knowledgebaseenabled": false,
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "16.0.1.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/media\/log\/nextcloud.log",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "onlyoffice": {
            "verify_peer_off": true
        },
        "updater.release.channel": "beta",
        "mysql.utf8mb4": true
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.9.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "logging"

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - audioplayer: 2.7.0
  - bookmarks: 1.0.4
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - deck: 0.6.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.5.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 2.6.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.1.10
  - password_policy: 1.6.0
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quicknotes: 0.1.7
  - radio: 0.6.5
  - rainloop: 6.0.2
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_notifications
  - apporder
  - calendar
  - circles
  - encryption
  - files_external
  - mindmaps
  - mood
  - quota_warning
  - ransomware_protection
  - richdocuments
  - spreed
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Mozilla

**Operating system:**

Windows 10

**Comment by Githopp192** [comment] 2019-05-15 22:54
Got some Doctrine Errors, too -->

[core] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` `u` LEFT JOIN `oc_preferences` `p` ON (`userid` = `uid`) AND (`appid` = 'settings') AND (`configkey` = 'email') WHERE (`uid`  COLLATE utf8mb4_general_ci LIKE ?) OR (`displayname`  COLLATE utf8mb4_general_ci LIKE ?) OR (`configvalue`  COLLATE utf8mb4_general_ci LIKE ?) ORDER BY `uid_lower` ASC LIMIT 500 OFFSET 500' with params ["%%", "%%", "%%"]:

SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8' at <<closure>>

 0. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 184
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... '", Doctrine\DBAL\Dr ... ]})
 1. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 158
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... '")
 2. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 938
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT `uid`, ` ... 0", {1: "%%",2: "%%",3: "%%"})
 3. /var/www/html/nextcloud/lib/private/DB/Connection.php line 195
    Doctrine\DBAL\Connection->executeQuery("SELECT `uid`, ` ... 0", {1: "%%",2: "%%",3: "%%"}, {1: 2,2: 2,3: 2}, null)
 4. /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 219
    OC\DB\Connection->executeQuery("SELECT `uid`, ` ... 0", {1: "%%",2: "%%",3: "%%"}, {1: 2,2: 2,3: 2})
 5. /var/www/html/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 214
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/html/nextcloud/lib/private/User/Database.php line 280
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/html/nextcloud/lib/private/User/Database.php line 381
    OC\User\Database->getDisplayNames("", 500, "500")
 8. /var/www/html/nextcloud/lib/private/User/Manager.php line 228
    OC\User\Database->getUsers("", 500, "500")
 9. /var/www/html/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 101
    OC\User\Manager->search("", 500, "500")
10. /var/www/html/nextcloud/lib/private/BackgroundJob/Job.php line 61
    OCA\Files\BackgroundJob\ScanFiles->run(null)
11. /var/www/html/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
12. /var/www/html/nextcloud/cron.php line 123
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-05-16T00:45:03+02:00

**Comment by Githopp192** [comment] 2019-05-15 23:04
(Before Database was not "utf8mb4" compatible .. so i did ) -->

	# sudo mysql -u root
	> ALTER DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
	# sudo -u www-data php occ config:system:set mysql.utf8mb4 --type boolean --value="true"
	# sudo -u www-data php occ maintenance:repair

**Comment by MorrisJobke** [comment] 2019-05-16 07:27
Duplicate of #15078

**Closed by MorrisJobke** 2019-05-16 07:27 UTC
Labels: 0. Needs triage, bug
