### ISSUE TITLE
Provide option for automatic app updates

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#16918] opened 2019-08-29 01:56 UTC
https://help.nextcloud.com/t/which-missing-apps-and-features-do-you-want-in-nextcloud/28200/91

**Comment by jmattt** [comment] 2019-08-29 15:12
Duplicate of https://github.com/nextcloud/server/issues/11918

OP:  See that issue for some details on how this is currently possible through the occ command line tool.

**Closed by jmattt** 2019-08-29 15:12 UTC
Labels: 0. Needs triage, enhancement
