### ISSUE TITLE
wrong warnings after upgrade to 14.0.2 (and 14.0.3)

### ISSUE THREAD

**Issue by flower1024** [nextcloud/server#11825] opened 2018-10-14 12:35 UTC
i recently installed nc 14.0.1 without any warnings.
after the update to 14.0.2 and 14.0.3 is see this:
Es gibt einige Warnungen bei Ihrer Systemkonfiguration.
Ihr Webserver ist nicht richtig konfiguriert um "/.well-known/caldav" aufzulösen. Weitere Informationen hierzu finden Sie in der Dokumentation.
Ihr Webserver ist nicht richtig konfiguriert um "/.well-known/carddav" aufzulösen. Weitere Informationen hierzu finden Sie in der Dokumentation.

i use carddav on android without any problems and my nginx-server redirects this locations correctly.

### Expected behaviour
dont show warnings for working things :)

### Actual behaviour
i see a warning although everthing works as expected

### Server configuration

relevant part of my nginx conf (please ask if you need more details)
    location = /.well-known/carddav {
                return 301 $scheme://$host/remote.php/dav;
        }

    location = /.well-known/caldav {
                return 301 $scheme://$host/remote.php/dav;
        }

**Operating system**:
Ubuntu 18.04

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 14.0.1 -> 14.0.2

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
Result: No errors have been found.

**Comment by MorrisJobke** [comment] 2018-10-15 06:48
See https://github.com/nextcloud/server/issues/11787#issuecomment-429239543

**Comment by MorrisJobke** [comment] 2018-10-15 06:48
Duplicate of #11787

**Closed by MorrisJobke** 2018-10-15 06:48 UTC
Labels: bug
