### ISSUE TITLE
Starting multiple app upgrades does not work

### ISSUE THREAD

**Issue by MarcelWaldvogel** [nextcloud/server#8389] opened 2018-02-16 08:20 UTC
### Steps to reproduce
1. Go to the apps settings when there are multiple updates available
2. Click on "Update to x.y.z" for one app
3. Click on "Update to a.b.c." for other apps (one or multiple) before the first update ends

### Expected behaviour
All the apps should be updated in (some) sequence

### Actual behaviour
Only the second update is processed. The other app(s) remain as "Upgrading…" without anything happening. One has to reload the app list to be able to click "Update to a.b.c" again.

BTW: There is a small language inconsistency: The button first says "*Update* to …" but is then changed to "*Upgrading*…". Please use the same verb for both.

### Server configuration

**Operating system**: Ubuntu 17.04

**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 13.0.0 (but also before)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Signing status:** No errors have been found.

**List of activated apps:**
<details>
<summary>Config report</summary>
```
Enabled:
  - activity: 2.6.1
  - audioplayer: 2.2.5
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_fulltextsearch: 0.6.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - fulltextsearch: 0.6.0
  - fulltextsearch_elasticsearch: 0.6.0
  - gallery: 18.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - ocsms: 1.12.2
  - ojsxc: 3.3.2
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - richdocuments: 1.12.40
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.ch",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production",
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 58

**Operating system:** Ubuntu 17.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
192.0.2.99 - - [16/Feb/2018:08:36:00 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1033 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:04 +0100] "GET /core/img/actions/checkbox-mark.svg HTTP/1.1" 200 834 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:12 +0100] "POST /index.php/settings/ajax/updateapp.php HTTP/1.1" 200 1188 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:12 +0100] "POST /index.php/settings/ajax/updateapp.php HTTP/1.1" 503 8964 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - marcel [16/Feb/2018:08:36:19 +0100] "PROPFIND /remote.php/dav/files/marcel/ HTTP/1.1" 207 1653 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
192.0.2.99 - - [16/Feb/2018:08:36:21 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 876 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:30 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1033 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/settings/apps HTTP/1.1" 200 7497 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/vendor/select2/select2.css?v=d66ab451-9 HTTP/1.1" 200 3772 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=d66ab451-9 HTTP/1.1" 200 6649 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/css/settings/15be08c0-settings.css?v=d66ab451-9 HTTP/1.1" 200 5722 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/css/core/15be08c0-jquery-ui-fixes.css?v=d66ab451-9 HTTP/1.1" 200 2390 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/css/core/15be08c0-server.css?v=d66ab451-9 HTTP/1.1" 200 17409 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/css/core/15be08c0-jquery.ocdialog.css?v=d66ab451-9 HTTP/1.1" 200 2100 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/css/core/15be08c0-share.css?v=d66ab451-9 HTTP/1.1" 200 2487 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/search/js/search.js?v=d66ab451-9 HTTP/1.1" 200 4185 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/files_pdfviewer/js/previewplugin.js?v=d66ab451-9 HTTP/1.1" 200 2571 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/files_videoplayer/js/viewer.js?v=d66ab451-9 HTTP/1.1" 200 2089 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/vendor/core.js?v=d66ab451-9 HTTP/1.1" 200 279984 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/js/jquery-ui-fixes.js?v=d66ab451-9 HTTP/1.1" 200 869 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/js/files/fileinfo.js?v=d66ab451-9 HTTP/1.1" 200 1533 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/js/core/merged-template-prepend.js?v=d66ab451-9 HTTP/1.1" 200 42028 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/js/files/client.js?v=d66ab451-9 HTTP/1.1" 200 6187 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/js/contactsmenu.js?v=d66ab451-9 HTTP/1.1" 200 4355 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /settings/js/settings.js?v=d66ab451-9 HTTP/1.1" 200 1799 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/vendor/marked/marked.min.js?v=d66ab451-9 HTTP/1.1" 200 6349 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /settings/js/apps.js?v=d66ab451-9 HTTP/1.1" 200 8186 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/files/img/app.svg?v=d66ab451 HTTP/1.1" 200 832 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/mail/img/mail.svg?v=d66ab451 HTTP/1.1" 200 988 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/gallery/img/app.svg?v=d66ab451 HTTP/1.1" 200 1030 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/activity/img/activity.svg?v=d66ab451 HTTP/1.1" 200 839 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/calendar/img/calendar.svg?v=d66ab451 HTTP/1.1" 200 1070 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/contacts/img/app.svg?v=d66ab451 HTTP/1.1" 200 2036 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/audioplayer/img/app.svg?v=d66ab451 HTTP/1.1" 200 1308 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/bookmarks/img/bookmarks.svg?v=d66ab451 HTTP/1.1" 200 1517 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /apps/ocsms/img/app.svg?v=d66ab451 HTTP/1.1" 200 1904 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /settings/img/admin.svg?v=d66ab451 HTTP/1.1" 200 821 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /settings/img/users.svg?v=d66ab451 HTTP/1.1" 200 1083 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /settings/img/apps.svg?v=d66ab451 HTTP/1.1" 200 804 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /settings/img/help.svg?v=d66ab451 HTTP/1.1" 200 996 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /core/img/actions/logout.svg?v=d66ab451 HTTP/1.1" 200 879 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/js/core/merged-share-backend.js?v=d66ab451-9 HTTP/1.1" 200 24186 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:41 +0100] "GET /index.php/js/notifications/merged.js?v=d66ab451-9 HTTP/1.1" 200 6619 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:42 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 876 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:42 +0100] "GET /index.php/settings/apps/categories HTTP/1.1" 200 1602 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:42 +0100] "GET /index.php/settings/apps/list?category=installed HTTP/1.1" 200 19100 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:42 +0100] "GET /index.php/settings/apps/list?category=updates HTTP/1.1" 200 2832 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - - [16/Feb/2018:08:36:43 +0100] "POST /index.php/settings/ajax/updateapp.php HTTP/1.1" 200 1017 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
192.0.2.99 - marcel [16/Feb/2018:08:36:49 +0100] "PROPFIND /remote.php/dav/files/marcel/ HTTP/1.1" 207 1653 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
192.0.2.99 - - [16/Feb/2018:08:36:51 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 876 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"```
</details>

**Comment by MorrisJobke** [comment] 2018-02-16 13:45
Thanks for the report - We already have a report like that. Let's close it as duplicate of #7581

**Closed by MorrisJobke** 2018-02-16 13:45 UTC

**Comment by MarcelWaldvogel** [comment] 2018-02-16 15:09
Indeed. Must have missed the existing issue. Great to see there has been thought going into that already.
