### ISSUE TITLE
Use SPDX license identifier

### ISSUE THREAD

**Issue by J0WI** [nextcloud/server#18138] opened 2019-11-27 14:50 UTC
Some software projects start using [SPDX license identifier](https://spdx.org/). This could simplify the mess with the included license header in every file.

**Comment by J0WI** [comment] 2020-05-20 21:41
@nextcloud/server-triage not sure who's in charge to make a decision on this. This probably affects other repos as well.

**Comment by kesselb** [comment] 2020-05-21 19:53
cc @ChristophWurst as you run the update script the last time ;)

**Comment by ChristophWurst** [comment] 2020-05-26 07:08
What would this look like? Could you link to the docs of the things we have to change specifically?

**Comment by kesselb** [comment] 2020-05-26 13:57
Details: https://spdx.dev/ids/#how

Example: https://github.com/picocms/Pico/blob/master/index.php

**Comment by skjnldsv** [comment] 2020-07-21 07:15
I'm fine with it as well, but our js files and vue files use the same format than php, and we currently have no script for this :(

**Comment by joshtrichards** [comment] 2023-09-03 11:59
Duplicate of #29723

This was the original issue, but the other one has had more recent activity. Let's consolidate discussion/tracking there.

**Closed by joshtrichards** 2023-09-03 11:59 UTC
Labels: enhancement, 1. to develop
