### ISSUE TITLE
Error Message "undefined offset" with comments

### ISSUE THREAD

**Issue by phatair** [nextcloud/server#5684] opened 2017-07-11 15:07 UTC
### Steps to reproduce
In the Log file i got a lot of error messages if i create a comment. They appear not immediately after the comment is created. 
The error looks like this: 
`

Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T17:00:01+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T17:00:01+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T17:00:01+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:02+0200
Error | PHP | Undefined offset: 0 at /var/www/cloud/apps/comments/lib/Activity/Provider.php#172 | 2017-07-11T16:30:01+0200
`

Also in the mails that inform about activities on nextcloud, there is just a information like this

> Today at 14:00
> "add_comment_subject"

### Expected behaviour
There should no error message in the log file
and there should be a detailed information in the activity mail

### Server configuration

**Operating system**: Ubuntu 16.04.2

**Web server:** apache 2.4.18

**Database:** mariadb 10.0.29

**PHP version:** 7.0.18

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Comment by phatair** [comment] 2017-07-21 07:35
I'm the only one who has this problem? 
Every email notification about a comment has only the "add_comment_subject".

**Comment by MorrisJobke** [comment] 2017-08-30 10:32
cc @nickvergessen

**Comment by nickvergessen** [comment] 2017-09-06 11:01
Duplicate of #6211

PR fixing it is in #6369

**Closed** 2017-09-07 07:47 UTC
Labels: bug, feature: activity and notification, feature: comments
