### ISSUE TITLE
updating spreed.Me to 0.3.4

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#2269] opened 2016-11-23 08:05 UTC
### Expected behaviour
Spreed.me should update
I didn't configure the nextcloud app-store updates are coming from the owncloud store. The last updates all worked fine.

See also:
https://help.nextcloud.com/t/update-to-0-3-4-fails/5364
https://github.com/strukturag/nextcloud-spreedme/issues/61
### Actual behaviour
Nextcloud shows "A update to spreed.Me 0.3.4 is available"
Under apps, no Update is available
Log shows:
Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate

web-rtc has bin updated:
```
Preparing to unpack .../spreed-webrtc-bin_0.29.3-1~trusty2_armhf.deb ...
Unpacking spreed-webrtc-bin (0.29.3-1~trusty2) over (0.29.3-1~trusty1) ...
Preparing to unpack .../spreed-webrtc_0.29.3-1~trusty2_all.deb ...
Unpacking spreed-webrtc (0.29.3-1~trusty2) over (0.29.3-1~trusty1) ...
Preparing to unpack .../spreed-webrtc-assets_0.29.3-1~trusty2_all.deb ...
Unpacking spreed-webrtc-assets (0.29.3-1~trusty2) over (0.29.3-1~trusty1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up spreed-webrtc-bin (0.29.3-1~trusty2) ...
Setting up spreed-webrtc-assets (0.29.3-1~trusty2) ...
Setting up spreed-webrtc (0.29.3-1~trusty2) ...
```

### Server configuration
**Operating system**: Linux OdOc 3.10.96 #1 SMP PREEMPT Mon May 23 01:50:06 BRT 2016 armv7l

**Web server:**  apache2handler

**Database:** mysql
MariaDB
**PHP version:** 7.0.8-0ubuntu0.16.04.3

**Nextcloud version:** 9.1.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**List of activated apps:**
<details>
	<summary>App list</summary>

	```
	Enabled:
	 - activity: 2.3.2
	 - admin_audit: 1.0.0
	 - bookmarks: 0.9.0
	 - calendar: 1.4.0
	 - comments: 1.0.0
	 - contacts: 1.4.0.0
	 - dav: 1.0.1
	 - direct_menu: 0.9.2
	 - federatedfilesharing: 1.0.1
	 - files: 1.5.2
	 - files_pdfviewer: 0.8.1
	 - files_sharing: 1.0.0
	 - files_texteditor: 2.1
	 - files_trashbin: 1.0.0
	 - files_versions: 1.3.0
	 - files_videoplayer: 0.9.8
	 - flowupload: 0.3
	 - html5_videoplayer: 1.0
	 - issuetemplate: 0.0.1
	 - keeweb: 0.2.9
	 - logreader: 1.1.5
	 - news: 9.0.4
	 - nextnotes: 0.9.1
	 - notifications: 0.3.0
	 - ocsms: 1.10.1
	 - ownbackup: 0.3.8
	 - password_policy: 1.0.0
	 - provisioning_api: 1.0.0
	 - serverinfo: 1.1.1
	 - shorten: 0.0.15
	 - spreedme: 0.3.3
	 - survey_client: 0.1.5
	 - tasks: 0.9.3
	 - templateeditor: 0.1
	 - theming: 1.0.1
	 - updatenotification: 1.0.1
	 - workflowengine: 1.0.1

	Disabled:
	 - encryption
	 - external
	 - federation
	 - files_accesscontrol
	 - files_automatedtagging
	 - files_external
	 - files_retention
	 - firstrunwizard
	 - gallery
	 - qownnotesapi
	 - systemtags
	 - user_external
	 - user_ldap
	 - user_saml
	```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/owncloud\/data",
    "tempdirectory": "\/media\/ssd\/phptemp\/",
    "dbtype": "mysql",
    "version": "9.1.1.5",
    "theme": "",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "integrity.check.disabled": false,
    "dbname": "owncloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 2,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "cron_log": true,
    "asset-pipeline.enabled": false,
    "assetdirectory": "\/var\/www\/owncloud",
    "maxZipInputSize": 2147483648,
    "overwritewebroot": "\/",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "allowZipDownload": true,
    "versions": "true",
    "versions_retention_obligation": "1,3",
    "instanceid": "5072f7e9eec7e",
    "knowledgebaseenabled": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "has_internet_connection": true,
    "forcessl": true,
    "activity_expire_days": 8,
    "appcodechecker": false,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto,15",
    "appstore.experimental.enabled": true,
    "trusted_domains": [
        "***.net",
        "***.net",
        "192.168.1.234"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.***.de",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "***.de",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
{"reqId":"5QjPhA2ZDQkf\/oX1XKh5","remoteAddr":"192.168.1.**","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T08:49:33+01:00","method":"GET","url":"\/index.phpapps\/list?category=enabled&includeUpdateInfo=1","user":"******"}
(END)

	Insert your Nextcloud log here
	```
</details>

**Comment by MorrisJobke** [comment] 2016-11-23 09:06
@leonklingele Please update the app with a link to a properly hosted file 🙈

**Comment by MorrisJobke** [comment] 2016-11-23 09:06
cc @karlitschek ;)

**Comment by LukasReschke** [comment] 2016-11-23 09:08
Not a bug on our side. OwnCloud has incorrectly configured their SSL (incomplete chain) 

=> nothing we can do, except not hosting apps from apps.owncloud.com ;)

**Comment by MorrisJobke** [comment] 2016-11-23 09:12
> => nothing we can do, except not hosting apps from apps.owncloud.com ;)

I would like to get the spreed guys to properly upload the file in our app store or host it on github releases or something like that.

**Comment by MorrisJobke** [comment] 2016-11-23 09:13
> => nothing we can do, except not hosting apps from apps.owncloud.com ;)

And it's a blocker for the release because spreed is kind of one of the apps we really want to have out there ;)

**Comment by MorrisJobke** [comment] 2016-11-23 09:18
> And it's a blocker for the release because spreed is kind of one of the apps we really want to have out there ;)

Ah - I mixed that one up with our spreed app. This is the spreed.me app that requires the additional spreed server to run.

As this is not part of our release -> closing

@JSoko Sorry for this back and forth, but this is actually an issue with the environment where the archive of this app is hosted. The SSL cert of this server is not fully trusted and we can do very little there. Sorry for the inconvenience. The app author needs to place the app on a properly hosted platform.

**Comment by leonklingele** [comment] 2016-11-23 09:19
What's the problem with an incomplete chain? Just download the intermediate — The URL to it is included in the leaf after all..

**Closed** 2016-11-23 09:19 UTC
Labels: bug, high

**Comment by LukasReschke** [comment] 2016-11-23 09:24
@leonklingele Because we're using openssl with PHP and we're not going to implement some more magic certificate detection that isn't done by default. ;)

**Comment by aronovgj** [comment] 2016-11-23 14:37
For me Apps is not working at all due to that issue. Will I have to keep my apps updated by installing all of them manually until NC11 is out?
