### ISSUE TITLE
Add a danger message when deleting a user about files deletion

### ISSUE THREAD

**Issue by numahell** [nextcloud/server#17811] opened 2019-11-04 23:48 UTC
**Is your feature request related to a problem? Please describe.**
When a user is deleted, its files, calendar and others are also deleted, even when they are shared with other users or groups. There is no information warning us about that, and we are more and more weekend admin sys using Nextcloud and not reading documentation :smirk:

**Describe the solution you'd like**
When I delete a user, a confirmation dialog warning me that all files, calendars, contacts and other apps data owned by this user will be deleted, even the ones shared with other groups and users.

**Describe alternatives you've considered**
This question is not clear for me.

**Additional context**
N/A

**Comment by kesselb** [comment] 2019-11-05 10:16
Thanks for reporting this issue :+1: 

Duplicate of https://github.com/nextcloud/server/issues/17261

**Closed by kesselb** 2019-11-05 10:16 UTC
Labels: 0. Needs triage, enhancement
