### ISSUE TITLE
Can't migrate from ownCloud 10.0.4

### ISSUE THREAD

**Issue by Quintasan** [nextcloud/server#7671] opened 2018-01-03 09:29 UTC
### Steps to reproduce
1. Upgrade ownCloud to 10.0.4
2. Download and install the updater as outlined in the migration instructions
3. Go to https://your.domain.com/updater/index.php

### Expected behaviour
I should be offered a way to perform the migration

### Actual behaviour
```
Current version is 10.0.4.
Could not determine migration path to Nextcloud.
```

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** nginx/1.13.8

**Database:** PostgreSQL 9.3

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Nextcloud updater log (data/updater.log)
<details>
<summary>Nextcloud log</summary>

```
2018-01-03T10:16:55+0100 xKwNApNuqN [info] request to updater
2018-01-03T10:16:55+0100 xKwNApNuqN [info] currentStep()
2018-01-03T10:16:55+0100 xKwNApNuqN [info] show HTML page
2018-01-03T10:16:55+0100 xKwNApNuqN [info] current version: 10.0.4 build time: 2017-12-05T16:16:34+00:00 56b43bf1eeef330b163108c149bbc5c9dfcbf9d7
2018-01-03T10:16:55+0100 xKwNApNuqN [info] getUpdateServerResponse()
2018-01-03T10:16:55+0100 xKwNApNuqN [info] updaterServer: https://updates.nextcloud.org/owncloud-migration/
2018-01-03T10:16:55+0100 xKwNApNuqN [info] releaseChannel: stable
2018-01-03T10:16:55+0100 xKwNApNuqN [info] internal version: 10.0.4.4
2018-01-03T10:16:55+0100 xKwNApNuqN [info] updateURL: https://updates.nextcloud.org/owncloud-migration/?version=10x0x4x4xxxstablexx2017-12-05T16%3A16%3A34%2B00%3A00+56b43bf1eeef330b163108c149bbc5c9dfcbf9d7x7x0x22
2018-01-03T10:16:55+0100 xKwNApNuqN [info] checkForUpdate() Array
(
)

2018-01-03T10:16:55+0100 xKwNApNuqN [info] end of checkForUpdate() Could not determine migration path to Nextcloud.
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] request to updater
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] currentStep()
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] show HTML page
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] current version: 10.0.4 build time: 2017-12-05T16:16:34+00:00 56b43bf1eeef330b163108c149bbc5c9dfcbf9d7
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] getUpdateServerResponse()
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] updaterServer: https://updates.nextcloud.org/owncloud-migration/
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] releaseChannel: stable
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] internal version: 10.0.4.4
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] updateURL: https://updates.nextcloud.org/owncloud-migration/?version=10x0x4x4xxxstablexx2017-12-05T16%3A16%3A34%2B00%3A00+56b43bf1eeef330b163108c149bbc5c9dfcbf9d7x7x0x22
2018-01-03T10:21:12+0100 unOTrMIIG8 [info] checkForUpdate() Array
(
)

2018-01-03T10:21:12+0100 unOTrMIIG8 [info] end of checkForUpdate() Could not determine migration path to Nextcloud.
```
</details>

**Comment by MorrisJobke** [comment] 2018-01-03 15:47
Duplicate of https://github.com/nextcloud/owncloud-web-migrator/issues/7

**Closed by MorrisJobke** 2018-01-03 15:47 UTC
