### ISSUE TITLE
Color not changing - Theming

### ISSUE THREAD

**Issue by Niclas-sol** [nextcloud/server#11983] opened 2018-10-22 16:21 UTC
### Steps to reproduce
1. Go to settings.
2. Select Theming.
3. Change Hex-Code to prefered color.  

### Expected behaviour
Color change to the new selected.

### Actual behaviour
Saveprocess never finish. Color can not be changed.

## Server configuration detail

**Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.22

**PHP version:** 7.2.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, SPL, iconv, mbstring, session, standard, memcached, pcntl, Phar, posix, Reflection, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, mysqlnd, PDO, apcu, curl, gd, gettext, imagick, imap, intl, json, mysqli, pdo_mysql, pdo_pgsql, pgsql, redis, sqlite3, xmlrpc, xsl, ionCube Loader, Zend OPcache

**Nextcloud version:** 14.0.3 - 14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Directly as Webinstaller

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - impersonate
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "mydomain"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.3.0",
    "overwrite.cli.url": "https:\/\/mydomain\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "Testtheme"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

[Error] Failed to load resource: the server responded with a status of 402 () (updateStylesheet, line 0)

[Error] Failed to load resource: the server responded with a status of 403 () (.ocdata, line 0)

[Error] TypeError: undefined is not an object (evaluating 'response.data.message')
	finishedAction (merged-template-prepend.js:2325)
	finishedSaving (merged-template-prepend.js:2308)
	(anonyme Funktion) (settings-admin.js:35)
	j (core.js:2:26931)
	fireWith (core.js:2:27740)
	x (core.js:4:11289)
	(anonyme Funktion) (core.js:4:14767)


	b) The network log


</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/lib/php/20170718/mcrypt.so (/usr/lib/php/20170718/mcrypt.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mcrypt.so.so (/usr/lib/php/20170718/mcrypt.so.so: cannot open shared object file: No such file or directory)) at Unknown#0
	

Undefined index: log-detail at /data/web/e98783/html/nextcloud/apps/issuetemplate/lib/Detail.php#59


Insert your browser log here, this could for example include:

	a) [Error] Failed to load resource: the server responded with a status of 402 () (updateStylesheet, line 0)

[Error] Failed to load resource: the server responded with a status of 403 () (.ocdata, line 0)

[Error] TypeError: undefined is not an object (evaluating 'response.data.message')
	finishedAction (merged-template-prepend.js:2325)
	finishedSaving (merged-template-prepend.js:2308)
	(anonyme Funktion) (settings-admin.js:35)
	j (core.js:2:26931)
	fireWith (core.js:2:27740)
	x (core.js:4:11289)
	(anonyme Funktion) (core.js:4:14767)


	b) The network log
	c) ...
</details>

**Comment by juliushaertl** [comment] 2018-10-23 07:53
> 	a) [Error] Failed to load resource: the server responded with a status of 402 () (updateStylesheet, line 0)

This looks strange, I have no idea how a 402 status could land there.

@Niclas-sol Can you check the Nextcloud log file for errors that happen when you try to change the color?

**Comment by Niclas-sol** [comment] 2018-10-23 09:06
The only error in the log is this:

PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/lib/php/20170718/mcrypt.so (/usr/lib/php/20170718/mcrypt.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mcrypt.so.so (/usr/lib/php/20170718/mcrypt.so.so: cannot open shared object file: No such file or directory)) at Unknown#0

This error occurs almost every minute and there are no other errors in the log file.
I tried to change the color but the saving process never end and no error is logged

Thanks for helping

**Comment by juliushaertl** [comment] 2018-10-23 09:15
The log file looks more like the one from your webserver. Can you check the file nextcloud.log in your installations data directory?

**Comment by Niclas-sol** [comment] 2018-10-23 09:30
[nextcloud.log](https://github.com/nextcloud/server/files/2505463/nextcloud.log)
 I copied one line from the online logfile from nextcloud. After research i fixed this error with using php 7.1 instead of 7.2. But the theming is still not changing

**Comment by Niclas-sol** [comment] 2018-10-24 16:29
Thats all I have: 
Error | PHP | openssl_pkey_new(): unable to write random state at /data/web/e98783/html/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php#296 | 2018-10-24T18:22:15+0200

Error | PHP | openssl_pkey_new(): unable to write random state at /data/web/e98783/html/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php#296 | 2018-10-24T14:23:37+0200

Error | PHP | openssl_pkey_new(): unable to write random state at /data/web/e98783/html/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php#296 | 2018-10-24T14:23:30+0200

Error | cron | Error: Call to undefined method OCP\AppFramework\Http\DataResponse::succeeded() | 2018-10-24T14:00:54+0200

Error | PHP | openssl_pkey_new(): unable to write random state at /data/web/e98783/html/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php#296 | 2018-10-24T14:00:33+0200

Error | index | TypeError: Argument 5 passed to OC\Core\Controller\PreviewController::__construct() must be of the type string, null given | 2018-10-24T13:59:45+0200

Error | index | TypeError: Argument 5 passed to OC\Core\Controller\PreviewController::__construct() must be of the type string, null given | 2018-10-24T13:59:44+0200

Error | PHP | openssl_pkey_new(): unable to write random state at /data/web/e98783/html/nextcloud/lib/private/Security/IdentityProof/Manager.php#70 | 2018-10-24T13:50:36+0200

Error | PHP | openssl_pkey_new(): unable to write random state at /data/web/e98783/html/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php#296 | 2018-10-24T13:50:28+0200

Error | PHP | openssl_pkey_new(): unable to write random state at /data/web/e98783/html/nextcloud/lib/private/Authentication/Token/PublicKeyTokenProvider.php#296

I think these errors show only a problem with the SSL certificate but I'm not sure...

**Comment by MorrisJobke** [comment] 2018-11-29 23:03
As there is no feedback since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2018-11-29 23:03 UTC
Labels: bug, feature: theming, needs info
