### ISSUE TITLE
12.0.2 integrity check

### ISSUE THREAD

**Issue by raudraido** [nextcloud/server#6134] opened 2017-08-15 14:08 UTC
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- music
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [music] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)

**Comment by LukasReschke** [comment] 2017-08-15 15:38
Duplicate of https://github.com/owncloud/music/issues/574

**Closed by LukasReschke** 2017-08-15 15:38 UTC
