### ISSUE TITLE
[Bug]: Multiselect on files does not work

### ISSUE THREAD

**Issue by Tschoepler** [nextcloud/server#43819] opened 2024-02-24 20:49 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

i am trying to select multiple files at once but it just wont work. i tried shit+click and cmd+click and ctrl+click patterns > no luck. i saw that https://github.com/nextcloud/server/issues/167 was closed. can not seem to find any other issue nor documentation on how to do multi-file-selection in nextcloud. after finding https://github.com/nextcloud/server/issues/167 though i wonder if this is rather a feature request 🤯

### Steps to reproduce

1. go into files app
2. choose a folder that has multiple files inside
3. select the first file in the list by clicking on the checkbox
4. shift+click the checkbox of any other file in the list

### Expected behavior

select one file and shit+click another file in the list selects the two files AND all files in between them. just as in finder/explorer etc.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-02-24 21:04
Duplicate of #42202

**Closed by joshtrichards** 2024-02-24 21:04 UTC
Labels: bug, 0. Needs triage
