### ISSUE TITLE
"Unknown error" after canceling the upload .docx, .zip, .exe files

### ISSUE THREAD

**Issue by Serrous** [nextcloud/server#18217] opened 2019-12-03 19:42 UTC
### Steps to reproduce
1. Open nextcloud in browser (mozilla, chrome)
2. Move folder with some word doc files from local computer (drug and drop)
3. Then click to "cancel upload

### Expected behaviour
Tell us what should happen

Pop-up "Upload cancel". File transfer should stop

### Actual behaviour
Tell us what happens instead

The progress bar does not disappear, after a few seconds the error “unknown error” pops up. It was experimentally established that their number is equal to the number of transferred files .docx or .zip or .exe types

### Server configuration

**Operating system:**
Arch-linux
5.3.12-arch1-1 

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
PHP 7.3.12

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install 

**Where did you install Nextcloud from:**
Official repo with use pacman

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

 There are no commands defined in the "ldap" namespace.

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
68.1.0esr (64-bit)
**Operating system:**

OpenSUSE 15.1 Leap

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>



```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"tsu7luJhlqvP3CZJbk5u","level":4,"time":"2019-12-03T19:38:31+00:00","remoteAddr":"46.138.14.150","user":"USERNAME","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/uploads\/USERNAME\/web-file-upload-fbb9f75e7e6c12fd8b56722f5f6d5607-1575401896189\/0","message":{"Exception":"Sabre\\DAV\\Exception","Message":"Could not rename part file to final file","Code":0,"Trace":[{"file":"\/usr\/share\/webapps\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/usr\/share\/webapps\/nextcloud\/apps\/dav\/lib\/Upload\/UploadFolder.php","line":45,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["0",null]},{"file":"\/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["0",null]},{"file":"\/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads\/USERNAME\/web-file-upload-fbb9f75e7e6c12fd8b56722f5f6d5607-1575401896189\/0",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"http:\/\/SERVERHOST\/remote.php\/dav\/uploads\/USERNAME\/web-file-upload-fbb9f75e7e6c12fd8b56722f5f6d5607-1575401896189\/0","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"http:\/\/SERVERHOST\/remote.php\/dav\/uploads\/USERNAME\/web-file-upload-fbb9f75e7e6c12fd8b56722f5f6d5607-1575401896189\/0","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"http:\/\/SERVERHOST\/remote.php\/dav\/uploads\/USERNAME\/web-file-upload-fbb9f75e7e6c12fd8b56722f5f6d5607-1575401896189\/0","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/usr\/share\/webapps\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/SERVERHOST\/remote.php\/dav\/uploads\/USERNAME\/web-file-upload-fbb9f75e7e6c12fd8b56722f5f6d5607-1575401896189\/0","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/usr\/share\/webapps\/nextcloud\/apps\/dav\/lib\/Server.php","line":317,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/usr\/share\/webapps\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/usr\/share\/webapps\/nextcloud\/remote.php","line":163,"args":["\/usr\/share\/webapps\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/usr\/share\/webapps\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":267,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"17.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by harveytj03** [comment] 2020-07-22 10:02
I've been having this issue as well. I've been uploading large video files and it seems if its over 10mb, it errors out and is worst the more large files there are. I get this in the log viewer.

Here in my cloud
![error1](https://user-images.githubusercontent.com/25831542/88163284-0e35c200-cbd8-11ea-8a9d-fe3841dc00f8.PNG)

And here in the logging setting
![error2](https://user-images.githubusercontent.com/25831542/88163317-1a218400-cbd8-11ea-85dc-559ae35b7236.PNG)

Here is the log from my log file, this is repeated for every large file cancelled
<details>
  <summary>Spoiler!</summary>
  {"reqId":"d8t7H9Qr8ljjgYcCubE4","level":3,"time":"2020-07-22T08:34:42+00:00","remoteAddr":"127.0.0.1","user":"harveytj03","app":"core","method":"PUT","url":"/remote.php/dav/uploads/harveytj03/web-file-upload-1b8c00550e49a445b835b0e93017fe66-1595406861465/0","message":"unable to rename, source directory is not writable : uploads/web-file-upload-1b8c00550e49a445b835b0e93017fe66-1595406861465","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"19.0.1.1"}
{"reqId":"d8t7H9Qr8ljjgYcCubE4","level":3,"time":"2020-07-22T08:34:42+00:00","remoteAddr":"127.0.0.1","user":"harveytj03","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/harveytj03/web-file-upload-1b8c00550e49a445b835b0e93017fe66-1595406861465/0","message":"renaming part file to final file failed $renameOkay: false, $fileExists: false)","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"19.0.1.1"}
{"reqId":"d8t7H9Qr8ljjgYcCubE4","level":4,"time":"2020-07-22T08:34:42+00:00","remoteAddr":"127.0.0.1","user":"harveytj03","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/harveytj03/web-file-upload-1b8c00550e49a445b835b0e93017fe66-1595406861465/0","message":{"Exception":"Sabre\\DAV\\Exception","Message":"Could not rename part file to final file","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":154,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":46,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1104,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":527,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":288,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"19.0.1.1"}
</details>

**Comment by szaimen** [comment] 2021-06-08 08:36
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-08 08:36 UTC
Labels: 0. Needs triage, bug
