### ISSUE TITLE
NC 21 Error: Required parameter $tagManager follows optional parameter $fileIdentifier at /var/www/nextcloud/apps/files/lib/Helper.php#220

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#25814] opened 2021-02-26 19:23 UTC
Getting below error ever since updated to NC 21 from NC 20

Apache 2.4
PHP 7.4.15
MySQL 8.0.23

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"vhRFK5UVllzAxP1j4FBE","level":3,"time":"2021-02-26T15:51:51+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Required parameter $tagManager follows optional parameter $fileIdentifier at /var/www/nextcloud/apps/files/lib/Helper.php#220","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":476,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":476,"function":"include"},{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":344,"function":"Composer\\Autoload\\includeFile"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Helper.php","line":109,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php","line":831,"function":"getTrashFiles","class":"OCA\\Files_Trashbin\\Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Command/Expire.php","line":58,"function":"expire","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/var/www/nextcloud/lib/private/Command/CommandJob.php","line":36,"function":"handle","class":"OCA\\Files_Trashbin\\Command\\Expire","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OC\\Command\\CommandJob","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/QueuedJob.php","line":46,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.0.18","id":"60394a646b68a"}
```
</details>

**Comment by kesselb** [comment] 2021-02-26 21:21
Duplicate of https://github.com/nextcloud/server/issues/25806

**Closed by kesselb** 2021-02-26 21:21 UTC
Labels: 0. Needs triage, bug
