### ISSUE TITLE
[18.0.0 Beta1] Renaming folder issues on S3/Redis

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#18335] opened 2019-12-10 14:11 UTC
### Steps to reproduce
1. Rename folder
2. Rename fails (webdav errors in attachment, portal says busy or not possible)
3. Come back 40-90 minutes later and the folder is renamed on it's own, no user input.

### Expected behaviour
Rename happens instantly

### Actual behaviour
Rename fails, restarting all running services doesn't do anything, flushdb/flushall on redis does nothing, clearing mysql file locks does nothing, running cron does nothing.

Checking 40-90 minutes later and it's renamed on it's own.

### Server configuration

**Operating system:**
Debian 10 Buster

**Web server:**
Nginx

**Database:**
Mariadb

**PHP version:**
PHP-FPM 7.3

**Nextcloud version:** (see Nextcloud admin page)
18.0.0 Beta1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes, 17.

**Where did you install Nextcloud from:**
Source

***S3 Backend***
Ceph w/RadosGW

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, S3 as both primary and some externals.

**Are you using encryption:** yes/no
No
[error.txt](https://github.com/nextcloud/server/files/3945210/error.txt)

**Comment by tsalwierz** [comment] 2019-12-12 03:31
Turns out it's only on folders with thousands of files. Not sure what the problem is here.

**Comment by damarges** [comment] 2020-11-11 09:39
> 
> 
> Turns out it's only on folders with thousands of files. Not sure what the problem is here.

The issue seems to be that S3 natively does not support rename of folders or even files. It actually creates a new copy of the file with the new filename and then deletes the old one. If that happens to a folder with a lot of files in it it just takes time.

**Comment by SimplyCorbett** [comment] 2020-11-11 16:16
> > Turns out it's only on folders with thousands of files. Not sure what the problem is here.
> 
> The issue seems to be that S3 natively does not support rename of folders or even files. It actually creates a new copy of the file with the new filename and then deletes the old one. If that happens to a folder with a lot of files in it it just takes time.

Nextcloud uses urn:oid for the files on the S3 backend so no renaming takes place other then in the database.

**Comment by szaimen** [comment] 2021-06-17 17:54
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by SimplyCorbett** [comment] 2021-07-17 20:24
> 
> 
> This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

So is it still an issue?

**Comment by damarges** [comment] 2021-07-17 23:41
No its solved.Am 17.07.2021 22:24 schrieb SimplyCorbett ***@***.***>:

This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

So is it still an issue?

**Closed** 2021-07-17 23:44 UTC
Labels: 0. Needs triage, bug, feature: object storage, needs info
