### ISSUE TITLE
External storage does not count towards users quota

### ISSUE THREAD

**Issue by JacobErnst98** [nextcloud/server#7017] opened 2017-10-30 21:08 UTC
### Steps to reproduce
1. Set up external SFTP storage
2. add 'quota_include_external_storage' => true, to config.php
3. upload file to SFTP external storage
4. Storage quota is not used.

### Expected behaviour
The storage quota should be used.

### Actual behaviour
External storage does not count towards users quota
### Server configuration

[Nextcloud install vm](https://github.com/nextcloud/vm
)
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

Activity	2.5.2	Official		Disable
Collaborative tags	1.2.0	Official		Disable
Comments	1.2.0	Official		Disable
Deleted files	1.2.0	Official		Disable
External storage support	1.3.0	Official		Disable
Federation	1.2.0	Official		Disable
File sharing	1.4.0	Official		Disable
First run wizard	2.1	Official		Disable
Gallery	17.0.0	Official	
Limit to groups
Disable
Log Reader	2.0.0	Official	
Limit to groups
Disable
Monitoring	1.2.0	Official	
Limit to groups
Disable
Nextcloud announcements	1.1	Official		Disable
Notifications	2.0.0	Official		Disable
Password policy	1.2.2	Official	
Limit to groups
Disable
PDF viewer	1.1.1	Official	
Limit to groups
Disable
Share by mail	1.2.0	Official		Disable
Text editor	2.4.1	Official	
Limit to groups
Disable
Theming	1.3.0	Official		Disable
Update notification	1.2.0	Official	
Limit to groups
Disable
Usage survey	1.0.0	Official	
Limit to groups
Disable
Versions	1.5.0	Official		Disable
Video player	1.1.0	Official	
Limit to groups
Disable
Calendar	1.5.4	View in store ↗	
Limit to groups
This app has an update available.
Update to 1.5.6  Disable
Contacts	1.5.3	View in store ↗	
Limit to groups
This app has an update available.
Update to 2.0.1  Disable
Passman	2.1.4	View in store ↗	
Limit to groups
Disable
Preview Generator	1.0.6	View in store ↗		
This app has an update available.
Update to 1.0.7  Disable
Auditing / Logging	1.2.0	Official		Enable
Default encryption module	1.6.0	Official		Enable
External user support	0.4	Official		Enable
LDAP user and group backend

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

****** for sanitation

<?php
$CONFIG = array (
  'passwordsalt' => '********',
  'secret' => '********',
  'trusted_domains' => 
  array (
    0 => '******',
    1 => '******',
    2 => '******',
    3 => '******',
  ),
  'datadirectory' => '/var/ncdata',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_ncadmin',
  'dbpassword' => '******',
  'installed' => true,
  'instanceid' => '******',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'log_rotate_size' => '10485760',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
    'password' => '******',
  ),
  'htaccess.RewriteBase' => '/',
  'overwrite.cli.url' => '******',
  'quota_include_external_storage' => true,
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
#### LDAP configuration (delete this part if not used)
<details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
all

**Comment by pradeepasubha** [comment] 2017-10-31 16:04
Warnings on Admin Page
Your Nextcloud server has a built-in configuration checker, and it reports its findings at the top of your Admin page. These are some of the warnings you might see, and what to do about them.

../_images/security-setup-warning-1.png
You can use the Nextcloud Security Scan to see if your system is up to date and well secured. We have ran this scan over public IP addresses in the past to try and reach out to extremely outdated systems and might again in the future. Please, protect your privacy and keep your server up to date! Privacy means little without security.

Cache Warnings
“No memory cache has been configured. To enhance your performance please configure a memcache if available.” Nextcloud supports multiple php caching extensions:

APCu (minimum required PHP extension version 4.0.6)
Memcached
Redis (minimum required PHP extension version: 2.2.6)
You will see this warning if you have no caches installed and enabled, or if your cache does not have the required minimum version installed; older versions are disabled because of performance problems.

If you see “{Cache} below version {Version} is installed. for stability and performance reasons we recommend to update to a newer {Cache} version” then you need to upgrade, or, if you’re not using it, remove it.

You are not required to use any caches, but caches improve server performance. See Configuring Memory Caching.

Transactional file locking is disabled
“Transactional file locking is disabled, this might lead to issues with race conditions.”

Please see Transactional File Locking on how to correctly configure your environment for transactional file locking.

You are accessing this site via HTTP
“You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead.” Please take this warning seriously; using HTTPS is a fundamental security measure. You must configure your Web server to support it, and then there are some settings in the Security section of your Nextcloud Admin page to enable. The following pages describe how to enable HTTPS on the Apache and Nginx Web servers.

Enabling SSL (on Apache)

Use HTTPS

Nginx Example Configurations

The test with getenv(“PATH”) only returns an empty response
Some environments are not passing a valid PATH variable to Nextcloud. The php-fpm Configuration Notes provides the information about how to configure your environment.

The “Strict-Transport-Security” HTTP header is not configured
“The “Strict-Transport-Security” HTTP header is not configured to least “15552000” seconds. For enhanced security we recommend enabling HSTS as described in our security tips.”

The HSTS header needs to be configured within your Web server by following the Enable HTTP Strict Transport Security documentation

/dev/urandom is not readable by PHP
“/dev/urandom is not readable by PHP which is highly discouraged for security reasons. Further information can be found in our documentation.”

This message is another one which needs to be taken seriously. Please have a look at the Give PHP read access to /dev/urandom documentation.

Your Web server is not yet set up properly to allow file synchronization
“Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.”

At the ownCloud community forums a larger FAQ is maintained containing various information and debugging hints.

Outdated NSS / OpenSSL version
“cURL is using an outdated OpenSSL version (OpenSSL/$version). Please update your operating system or features such as installing and updating apps via the app store or Federated Cloud Sharing will not work reliably.”

“cURL is using an outdated NSS version (NSS/$version). Please update your operating system or features such as installing and updating apps via the app store or Federated Cloud Sharing will not work reliably.”

There are known bugs in older OpenSSL and NSS versions leading to misbehaviour in combination with remote hosts using SNI. A technology used by most of the HTTPS websites. To ensure that Nextcloud will work properly you need to update OpenSSL to at least 1.0.2b or 1.0.1d. For NSS the patch version depends on your distribution and an heuristic is running the test which actually reproduces the bug. There are distributions such as RHEL/CentOS which have this backport still pending.

Your Web server is not set up properly to resolve /.well-known/caldav/ or /.well-known/carddav/
Both URLs need to be correctly redirected to the DAV endpoint of Nextcloud. Please refer to Service discovery for more info.

Some files have not passed the integrity check
Please refer to the Fixing Invalid Code Integrity Messages documentation how to debug this issue.

Your database does not run with “READ COMMITED” transaction isolation level
“Your database does not run with “READ COMMITED” transaction isolation level. This can cause problems when multiple actions are executed in parallel.”

Please refer to Database “READ COMMITTED” transaction isolation level how to configure your database for this requirement.

**Comment by JacobErnst98** [comment] 2018-01-18 21:06
I found mounting with / shows the correct storage quota. mounting to a sub folder shows only the storage available on the local disk mounted to /data in nextcloud. https://github.com/nextcloud/server/pull/3438

**Comment by szaimen** [comment] 2023-01-09 11:16
Hi, see https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_configuration.html#setting-storage-quotas
![image](https://user-images.githubusercontent.com/42591237/211296164-a884d369-8c2f-4ca3-8a7b-d226ae21c1ae.png)

**Closed by szaimen** 2023-01-09 11:16 UTC
Labels: bug, 1. to develop, feature: external storage
