### ISSUE TITLE
NC 19 Create new User with E-Mail - E-Mail Address disappear, no email sent with Password

### ISSUE THREAD

**Issue by apg1980** [nextcloud/server#21312] opened 2020-06-08 13:05 UTC
Hello,

i am using NC 19 stable release on Ubuntu 18.04 LTS with PHP 7.3 FPM, Apache2 and Postgresql.
With NC 18.04 everything was fine, but if i am creating an new User (Username, Displayname, Password Empty, E-Mail Adress) and clicking on the Hook, User is creating without the added E-Mail Address an so no initial Mail is sent with the auto created Password. Sending the Welcome Message via the options after adding the E-Mail again works, but User did not receive the initial Password which NC is creating for him.

Best regards.

**Comment by dsec-be** [comment] 2020-06-10 06:56
Not creating my users as described by apg1980.
But I can confirm that creating new users in NC19 with username/password/email send the "Welcome aboard" email without the password (neither the one that I set or a new generated one).

**Comment by apg1980** [comment] 2020-07-28 17:39
Problem is still present in 19.01

**Comment by szaimen** [comment] 2021-06-08 10:56
did you activate this setting before creating the new user?
![image](https://user-images.githubusercontent.com/42591237/121173234-d9b30f00-c858-11eb-8357-a7430e0235ba.png)

As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-08 10:56 UTC
Labels: 0. Needs triage
