### ISSUE TITLE
error 500 web-based update nextcloud 17

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#17378] opened 2019-10-02 21:13 UTC
I have several installations nextcloud 16.0.5 and every time I tried to upgrade to version 17.0.0 choosing the beta channel.  after the first step dive it asks me if I want to continue the upgrade with the Web-based option, by clicking on it I receive a browser error 500, it does not continue with the update.  I am forced via terminal to continue manually with occ upgrade command.  having a site in shared hosting and not being able to continue via cli.  I wonder if I can fix this bug.  thanks

**Comment by inthreedee** [comment] 2019-10-02 22:52
Are you able to provide the logs as requested in the issue template?
Do you have the GroupFolders app installed on the affected instances?

**Comment by tigernero79** [comment] 2019-10-03 06:08
I find on log error


Level
Warningno app in context2019-10-03T03:06:16+0200
["2EY9XmeqrbEaLHN",{"type":"Person","name":"Tiger"},{"type":"Person","name":"Tiger@www.pensierando.it\/nx"},"Delete","2019-09-06T00:35:19+00:00",{"type":"Document","name":"\/IPTV Pro v5.1.4_arm64.apk"},[],[]]
Warningno app in context2019-10-03T02:06:12+0200
["2EY9XmeqrbEaLHN",{"type":"Person","name":"Tiger"},{"type":"Person","name":"Tiger@www.pensierando.it\/nx"},"Delete","2019-09-06T00:35:09+00:00",{"type":"Document","name":"\/IPTV Pro v5.1.4_arm64.apk"},[],[]]
Warningno app in context2019-10-02T23:06:11+0200
["2EY9XmeqrbEaLHN",{"type":"Person","name":"Tiger"},{"type":"Person","name":"Tiger@www.pensierando.it\/nx"},"Delete","2019-09-05T22:34:57+00:00",{"type":"Document","name":"\/IPTV Pro v5.1.4_arm64.apk"},[],[]]
Infoupdater2019-10-02T22:55:57+0200
\OC\Updater::resetLogLevel: Reset log level to Warning(2)
Infoupdater2019-10-02T22:55:57+0200
\OC\Updater::maintenanceDisabled: Turned off maintenance mode
Infoupdater2019-10-02T22:55:57+0200
\OC\Updater::updateEnd: Update successful
Infoupdater2019-10-02T22:55:57+0200
\OC\Updater::finishedCheckCodeIntegrity: Finished code integrity check
Infoupdater2019-10-02T22:55:44+0200
\OC\Updater::startCheckCodeIntegrity: Starting code integrity check...
Infoupdater2019-10-02T22:55:44+0200
\OC\Repair::step: Repair step: Sets the enterprise logo
Infoupdater2019-10-02T22:55:44+0200
\OC\Repair::step: Repair step: Switches from deprecated "production" to "stable" update channel
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Cleanup cypress files from viewer app
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Clear access cache of projects
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::info: Repair info: No need to remove link shares.
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Remove potentially over exposing share links
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Add background job to cleanup login flow v2 tokens
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Cleanup invalid photocache files for carddav
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Queue a one-time job to cleanup old backups of the updater
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Add preview background cleanup job
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::step: Repair step: Clear every generated avatar on major updates
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::info: Repair info: JS cache cleared
Debugmusic2019-10-02T22:55:31+0200
deleted file 6565 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6565
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6565
Debugmusic2019-10-02T22:55:31+0200
deleted file 6564 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6564
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6564
Debugmusic2019-10-02T22:55:31+0200
deleted file 6563 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6563
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6563
Debugmusic2019-10-02T22:55:31+0200
deleted file 6562 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6562
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6562
Debugmusic2019-10-02T22:55:31+0200
deleted file 6561 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6561
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6561
Debugmusic2019-10-02T22:55:31+0200
deleted file 6560 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6560
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6560
Debugmusic2019-10-02T22:55:31+0200
deleted file 6556 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6556
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6556
Debugmusic2019-10-02T22:55:31+0200
deleted file 6555 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6555
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6555
Debugmusic2019-10-02T22:55:31+0200
deleted file 6554 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6554
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6554
Debugmusic2019-10-02T22:55:31+0200
deleted file 6553 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6553
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6553
Debugmusic2019-10-02T22:55:31+0200
deleted file 6552 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6552
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6552
Debugmusic2019-10-02T22:55:31+0200
deleted file 6551 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6551
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6551
Debugmusic2019-10-02T22:55:31+0200
deleted file 6597 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6597
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6597
Debugmusic2019-10-02T22:55:31+0200
deleted file 6596 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6596
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6596
Debugmusic2019-10-02T22:55:31+0200
deleted file 6595 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6595
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6595
Debugmusic2019-10-02T22:55:31+0200
deleted file 6559 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6559
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6559
Debugmusic2019-10-02T22:55:31+0200
deleted file 6558 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6558
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6558
Debugmusic2019-10-02T22:55:31+0200
deleted file 6557 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 6557
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 6557
Infoupdater2019-10-02T22:55:31+0200
\OC\Repair::info: Repair info: SCSS cache cleared
Debugno app in context2019-10-02T22:55:31+0200
SCSSCacher: css cache cleared!
Debugmusic2019-10-02T22:55:31+0200
deleted file 67555 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 67555
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 67555
Debugmusic2019-10-02T22:55:31+0200
deleted file 67554 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 67554
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 67554
Debugmusic2019-10-02T22:55:31+0200
deleted file 67553 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 67553
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 67553
Debugmusic2019-10-02T22:55:31+0200
deleted file 67552 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 67552
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 67552
Debugmusic2019-10-02T22:55:31+0200
deleted file 67551 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 67551
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 67551
Debugmusic2019-10-02T22:55:31+0200
deleted file 67550 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:31+0200
deleteImage - 67550
Debugmusic2019-10-02T22:55:31+0200
deleteAudio - 67550
Debugmusic2019-10-02T22:55:30+0200
deleted file 67559 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67559
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67559
Debugmusic2019-10-02T22:55:30+0200
deleted file 67558 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67558
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67558
Debugmusic2019-10-02T22:55:30+0200
deleted file 67557 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67557
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67557
Debugmusic2019-10-02T22:55:30+0200
deleted file 67537 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67537
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67537
Debugmusic2019-10-02T22:55:30+0200
deleted file 67536 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67536
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67536
Debugmusic2019-10-02T22:55:30+0200
deleted file 67535 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67535
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67535
Debugmusic2019-10-02T22:55:30+0200
deleted file 67530 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67530
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67530
Debugmusic2019-10-02T22:55:30+0200
deleted file 67529 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67529
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67529
Debugmusic2019-10-02T22:55:30+0200
deleted file 67549 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67549
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67549
Debugmusic2019-10-02T22:55:30+0200
deleted file 67548 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67548
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67548
Debugmusic2019-10-02T22:55:30+0200
deleted file 67547 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67547
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67547
Debugmusic2019-10-02T22:55:30+0200
deleted file 67543 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67543
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67543
Debugmusic2019-10-02T22:55:30+0200
deleted file 67542 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67542
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67542
Debugmusic2019-10-02T22:55:30+0200
deleted file 67541 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67541
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67541
Debugmusic2019-10-02T22:55:30+0200
deleted file 67531 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67531
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67531
Debugmusic2019-10-02T22:55:30+0200
deleted file 67528 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67528
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67528
Debugmusic2019-10-02T22:55:30+0200
deleted file 67527 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67527
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67527
Debugmusic2019-10-02T22:55:30+0200
deleted file 67540 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67540
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67540
Debugmusic2019-10-02T22:55:30+0200
deleted file 67539 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67539
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67539
Debugmusic2019-10-02T22:55:30+0200
deleted file 67538 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67538
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67538
Debugmusic2019-10-02T22:55:30+0200
deleted file 67534 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67534
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67534
Debugmusic2019-10-02T22:55:30+0200
deleted file 67533 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67533
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67533
Debugmusic2019-10-02T22:55:30+0200
deleted file 67532 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67532
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67532
Debugmusic2019-10-02T22:55:30+0200
deleted file 67546 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67546
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67546
Debugmusic2019-10-02T22:55:30+0200
deleted file 67545 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67545
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67545
Debugmusic2019-10-02T22:55:30+0200
deleted file 67544 was not an indexed audio file or a cover image
Debugmusic2019-10-02T22:55:30+0200
deleteImage - 67544
Debugmusic2019-10-02T22:55:30+0200
deleteAudio - 67544
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: Image cache cleared
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Clear frontend caches
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Add log rotate job
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: No mounts updated
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Fix potential broken mount points
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: .step file moved to .step-previous-update
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: .step-previous-update removed
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: .step file exists
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Move .step file of updater to backup location
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Repair invalid shares
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: 0 tags with no entries have been removed.
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: 0 tag entries for deleted tags have been removed.
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: 0 tags for delete files have been removed.
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: 0 tags of deleted users have been removed.
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Clean tags and favorites
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Repair mime types
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::info: Repair info: All tables already have the correct collation -> nothing to do
Infoupdater2019-10-02T22:55:30+0200
\OC\Repair::step: Repair step: Repair MySQL collation
Infoupdater2019-10-02T22:55:28+0200
\OC\Repair::step: Repair step: Create help command
Infoupdater2019-10-02T22:55:28+0200
\OC\Repair::info: Repair info: Invalidation not required
Infoupdater2019-10-02T22:55:28+0200
\OC\Repair::step: Repair step: Invalidate access cache for projects conversation provider
Infoupdater2019-10-02T22:55:28+0200
\OC\Repair::step: Repair step: Create help command
Infoupdater2019-10-02T22:55:27+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "spreed" in appstore
Infoupdater2019-10-02T22:55:27+0200
\OC\Repair::step: Repair step: Invalidate access cache for projects conversation provider
Infoupdater2019-10-02T22:55:27+0200
\OC\Repair::step: Repair step: Create help command
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::upgradeAppStoreApp: Update app "spreed" from appstore
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "spreed" in appstore
Errorcore2019-10-02T22:55:18+0200
Exception: App "Social sharing via Twitter" cannot be installed because it is not compatible with this version of the server.
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "socialsharing_twitter" in appstore
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "socialsharing_twitter" in appstore
Errorcore2019-10-02T22:55:18+0200
Exception: App "Social sharing via Facebook" cannot be installed because it is not compatible with this version of the server.
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "socialsharing_facebook" in appstore
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "socialsharing_facebook" in appstore
Errorcore2019-10-02T22:55:18+0200
Exception: App "Social sharing via email" cannot be installed because it is not compatible with this version of the server.
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "socialsharing_email" in appstore
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "socialsharing_email" in appstore
Errorcore2019-10-02T22:55:18+0200
Exception: App "Social sharing via Diaspora" cannot be installed because it is not compatible with this version of the server.
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "socialsharing_diaspora" in appstore
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "socialsharing_diaspora" in appstore
Infoupdater2019-10-02T22:55:18+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "sharepoint" in appstore
Infoupdater2019-10-02T22:55:15+0200
\OC\Updater::upgradeAppStoreApp: Update app "sharepoint" from appstore
Infoupdater2019-10-02T22:55:15+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "sharepoint" in appstore
Infoupdater2019-10-02T22:55:15+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "ransomware_protection" in appstore
Infoupdater2019-10-02T22:55:12+0200
\OC\Updater::upgradeAppStoreApp: Update app "ransomware_protection" from appstore
Infoupdater2019-10-02T22:55:12+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "ransomware_protection" in appstore
Errorcore2019-10-02T22:55:12+0200
Exception: App "Ransomware recovery" cannot be installed because it is not compatible with this version of the server.
Infoupdater2019-10-02T22:55:12+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "ransomware_detection" in appstore
Infoupdater2019-10-02T22:55:12+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "ransomware_detection" in appstore
Infoupdater2019-10-02T22:55:12+0200
\OC\Repair::finishProgress
Infoupdater2019-10-02T22:55:12+0200
\OC\Repair::advance: (1)
ErrorPHP2019-10-02T22:55:12+0200
str_repeat(): Second argument has to be greater than or equal to 0 at /var/www/Pensierando/nx/3rdparty/symfony/console/Helper/ProgressBar.php#425
Infoupdater2019-10-02T22:55:12+0200
\OC\Repair::advance: (1)
ErrorPHP2019-10-02T22:55:12+0200
str_repeat(): Second argument has to be greater than or equal to 0 at /var/www/Pensierando/nx/3rdparty/symfony/console/Helper/ProgressBar.php#425
Infoupdater2019-10-02T22:55:12+0200
\OC\Repair::advance: (1)
Infoupdater2019-10-02T22:55:12+0200
\OC\Repair::startProgress: Starting ... Add background jobs for existing users (0)
Infoupdater2019-10-02T22:55:12+0200
\OC\Repair::step: Repair step: Add background jobs for existing users
Infoupdater2019-10-02T22:55:12+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "quota_warning" in appstore
Infoupdater2019-10-02T22:55:10+0200
\OC\Updater::upgradeAppStoreApp: Update app "quota_warning" from appstore
Infoupdater2019-10-02T22:55:10+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "quota_warning" in appstore
Infoupdater2019-10-02T22:55:09+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "impersonate" in appstore
Infoupdater2019-10-02T22:55:07+0200
\OC\Updater::upgradeAppStoreApp: Update app "impersonate" from appstore
Infoupdater2019-10-02T22:55:07+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "impersonate" in appstore
Infoupdater2019-10-02T22:55:07+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "groupfolders" in appstore
Debugcron2019-10-02T22:55:01+0200
Update required, skipping cron
Infoupdater2019-10-02T22:55:00+0200
\OC\Updater::upgradeAppStoreApp: Update app "groupfolders" from appstore
Infoupdater2019-10-02T22:55:00+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "groupfolders" in appstore
Infoupdater2019-10-02T22:54:59+0200
\OC\Updater::checkAppStoreApp: Checked for update of app "files_trackdownloads" in appstore
Infoupdater2019-10-02T22:54:57+0200
\OC\Updater::upgradeAppStoreApp: Update app "files_trackdownloads" from appstore
Infoupdater2019-10-02T22:54:57+0200
\OC\Updater::checkAppStoreAppBefore: Checking for update of app "files_trackdownloads" in appstore
Errorcore2019-10-02T22:54:57+0200
Exception: Could not download app files_texteditor
/var/www/Pensierando/nx/lib/private/legacy/app.php - line 393:

OC\Installer->downloadApp("files_texteditor")

/var/www/Pensierando/nx/lib/private/Updater.php - line 456:

OC_App->enable("files_texteditor")

/var/www/Pensierando/nx/lib/private/Updater.php - line 260:

OC\Updater->upgradeAppStoreApps([ "announcem ... "], true)

/var/www/Pensierando/nx/lib/private/Updater.php - line 128:

OC\Updater->doUpgrade("17.0.0.9", "16.0.5.1")

/var/www/Pensierando/nx/core/Command/Upgrade.php - line 258:

OC\Updater->upgrade()

/var/www/Pensierando/nx/3rdparty/symfony/console/Command/Command.php - line 255:

OC\Core\Command\Upgrade->execute(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/Pensierando/nx/3rdparty/symfony/console/Application.php - line 908:

Symfony\Component\Console\Command\Command->run(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/Pensierando/nx/3rdparty/symfony/console/Application.php - line 269:

Symfony\Component\Console\Application->doRunCommand(OC\Core\Comm ... }}, Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/Pensierando/nx/3rdparty/symfony/console/Application.php - line 145:

Symfony\Component\Console\Application->doRun(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/Pensierando/nx/lib/private/Console/Application.php - line 213:

Symfony\Component\Console\Application->run(Symfony\Comp ... {}, Symfony\Comp ... {})

/var/www/Pensierando/nx/console.php - line 97:

OC\Console\Application->run()

/var/www/Pensierando/nx/occ - line 11:

require_once("/var/www/Pe ... p")

**Comment by tigernero79** [comment] 2019-10-03 06:08
ErrorPHP2019-10-02T22:55:12+0200
str_repeat(): Second argument has to be greater than or equal to 0 at /var/www/Pensierando/nx/3rdparty/symfony/console/Helper/ProgressBar.php#425

**Comment by tigernero79** [comment] 2019-10-03 06:11
I then managed to complete the update to version 17, typing "sudo -u www-data php occ upgrade" but I have a nextcloud on a hosting I share and I'm afraid to update via the web, since I don't have access to them.

**Comment by inthreedee** [comment] 2019-10-03 06:39
Take a look over at #17338, do you have that same php error in your logs?

**Comment by tigernero79** [comment] 2019-10-03 07:20
YES 

"[PHP] Error: Declaration of OCA\GroupFolders\Versions\VersionsBackend::getVersionFile(OCP\IUser $user, OCP\Files\FileInfo $sourceFile, int $revision): OCP\Files\File must be compatible with OCA\Files_Versions\Versions\IVersionBackend::getVersionFile(OCP\IUser $user, OCP\Files\FileInfo $sourceFile, $revision): OCP\Files\File at /var/www/Pensierando/nx/apps/groupfolders/lib/Versions/VersionsBackend.php#38

GET /index.php/avatar/Tiger/448
from 192.168.6.1 at 2019-10-02T20:52:35+00:00"

I also had this error in the logs. so how can I find a place without running into the group folder error on a shared hosting installation? without ssh access? do I have to deactivate the group folder?

**Comment by inthreedee** [comment] 2019-10-03 15:03
Yes, according to some other users, if you disable the groupfolders app first the update might work fine.  The other option is to wait until a fix is released.  See more info here, and in the issue referenced above:
https://help.nextcloud.com/t/nc17-update-disable-group-folders-app-before-performing-the-update-of-your-server/61112

Closing as duplicate of #17338

**Closed by inthreedee** 2019-10-03 15:03 UTC
Labels: 0. Needs triage, bug

**Comment by bazsodombiandras** [comment] 2019-12-20 16:11
I've also updated from 16.x to 17.0.2 and ater the web updater finished, I got HTTP error 500 and NextCloud became inaccessible. Gave me a scare...

The solution was to run this from the NextCloud installation folder:
`sudo -u www-data php occ upgrade`

I've started using NextCloud at version 13. I can't remember any major update ever since which went flawlessly and had no error afterwards... just saying...
