### ISSUE TITLE
Request: show share settings to users who have permission to access

### ISSUE THREAD

**Issue by Germs2004** [nextcloud/server#10307] opened 2018-07-20 02:35 UTC
Folders currently tell users who they are shared with, but their child folders do not.

1) Create a folder structure like this:  Root > Folder1 > Folder2
2) Share Folder1 with Group1, which contains User1.
3) Log on as User1.
4) Notice that Folder1 has the shared icon and its details say the folder is shared with you and Group1.
5) Notice that Folder2 has the shared icon but its details don't say the folder is shared and doesn't tell you who it's shared with, or the fact that it is only shared because of inheritance.  It only says "Resharing is not allowed."

Expected behavior:
Any folder or file that is shared and has the shared icon should tell the user who the file is shared with.

Nextcloud 13.0.4

**Comment by MorrisJobke** [comment] 2018-07-20 14:55
Duplicate of #4281

**Closed by MorrisJobke** 2018-07-20 14:55 UTC
