### ISSUE TITLE
Exhaustive memory consumption with NC and Debian (buster)

### ISSUE THREAD

**Issue by mitscherdinger** [nextcloud/server#19051] opened 2020-01-21 14:12 UTC
Dear Developers!

My NC-machine is a QNAP TS-212. It's a little NAS with a MIPS-CPU and 246MB RAM. I configured 1GB swap. Using this since years, now, for hosting a NC-(formerly OC-)instance in my LAN-area along with NFS-Filesharing and - lately - a Wifi-AP.
Regarding NC, I'm primerly interested in the WebDAV features using the calendar and the addressbook as a sync server for 2 smartphones used by the parents of the family.
Yes, this isn't a high-end-setup and yes, it's a really slow machine. Sometimes I couldn't log into the web-interface or I had to wait for minutes… But the main feature, the syncing was working generally reliable, along with the other two services that have nothing to do with NC. From time to time I had to restart the machine because the wifi-service was down - that's it.

Upgrading to Debian Buster and therefore PHP 7.3, recently, seems to change the minimal memory consumption, drastically, especially the nextclouds cronjobs or PHP sessioncleans.

### Steps to reproduce
Start a clean reboot on the described machine, no matter if NC 15.x, 16.0.6 or 17.0.2 is installed. Make sure, all possible clients (smartphones, thunderbird on a laptop's desktop) will not trigger the sync process. MariaDB, Apache2 and the PHP-main process are occupying the overwhelming amount of memory, now. The used memory is about 140MB RAM + 12MB swap.
Wait for NC to start a cron-job. RAM is occupied by 95%, the rest is cache. Swap goes up to 350MB. Wait a few minutes.
Start any NC-task, in my example, thunderbird with TBsync addon. Start the sync. Swap goes up to 480MB.
Machine is getting very unresponsive. Syncing fails: Timeout. Trying to login via ssh fails. Wait a few minutes, trying to login to the web-interface, waiting…, waiting…, waiting… I got a login-screen after probably half an hour.
In this state, on the NC-side nothing really works except for internal processes as nextcloud cron-jobs. RAM is occupied by 90% + 10% cache, swap-space is getting smaller and smaller. The CPU on the other hand keeps working on ~20% - maybe the system's busy managing swap and the sata-controller is working independently from the CPU.
It takes docents of minutes for the system to calm down. Best scenario. Worst case - and that's what I experienced more than once the last days - is a "out-of-memory"-error kernel-wise, killing some processes.
All in all: A minimum of 128MB can't be claimed for NC's preferences. Even the recommended 512MB doesn't seem to be realistic to me.

### Server configuration

**Operating system: Debain Buster**

**Web server: Apache2**

**Database: MariaDB**

**PHP version: 7.3**

**Nextcloud version: 15.0.14, 16.0.7 or 17.02 - doesn't matter, tried them all**

**Updated from an older Nextcloud/ownCloud or fresh install: Migrated from Own- to Nextcloud manually, after that: Internal upgrade machanism**

**Where did you install Nextcloud from: tarball**

**List of activated apps:**

<details>
<summary>  - accessibility: 1.3.0
  - activity: 2.10.1
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - support: 1.0.1
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - files_external
  - files_pdfviewer
  - files_videoplayer
  - sharebymail
  - survey_client
  - systemtags
  - user_ldap
</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.0.6",
            "rappelkiste"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
</summary>
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Comment by kesselb** [comment] 2020-01-21 19:14
https://github.com/nextcloud/server/issues/17241 a change by php to use higher default values for password hashing. There is no way to change those values without touching the code but a patch to make those values configurable is prepared and will be released to 16 / 17 / 18.

I see the actual behaviour. What is the expected behaviour or the reason for this bug report? Should we update the documentation and make 512 MB a minimum requirement?

Probably you can replace Apache2 with nginx or lighttpd to save some resources. Nextcloud is not optimized for such low-power setups. This NAS has less power than a RPi :turtle: 

> WebDAV features using the calendar and the addressbook as a sync server for 2 smartphones

https://radicale.org perhaps? ;)

**Comment by mitscherdinger** [comment] 2020-01-22 08:25
Wow, that was a bunch of alternatives…
But, to get to the root of the problem and to save migrating time:
https://github.com/nextcloud/server/issues/17241#issuecomment-567199911
Rasos' patch did the trick and I have a nice working nextcloud instance, again. My thoughts about it: If you from nextcloud care about scalability - make this the default!
By the way: Don't know, how to compare an ARM core with a MIPS one. https://www.7-cpu.com/cpu/Kirkwood.html says, my CPU's running with 1200MHz, that would about twice as fast as a Classic RPi. And, yes, nextcloud is working on such an old crap, if the settings are right - something you can certainly be proud of…

**Comment by kesselb** [comment] 2020-01-22 14:23
> Wow, that was a bunch of alternatives…

... what do you mean?

> make this the default!

No. Next release of 16 / 17 / 18 will have a way to change those values without touching the code. If those values are a sensible default or not is a topic to be discussed with the php engineers. I'm sure there is a good reason for this default.

> Classic RPi.

I had a device like RPi 3 in mind ;) Anyway okay with you to close this issue?

**Comment by mitscherdinger** [comment] 2020-01-22 14:33
> > Wow, that was a bunch of alternatives…
> 
> ... what do you mean?
nginx, lighttpd, radicale…
Thanks for pointing to radicale - this can certainly be an alternative if NC's getting too fat, one day…


> Anyway okay with you to close this issue?
Absolutely! Thanks!

**Comment by mitscherdinger** [comment] 2020-04-28 14:06
Sorry, have to reopen it:
Although using Rasos' patch, my NAS is getting unresponsive, again, and I think, it's because of an upgrade to NC 18.0.4. I don't know, what to do, now.
If that's the future of nextcloud and there is no way to fix it as easily as Rasos' patch, I guess, I'd better go for radicale. Unfortunately, I can't use nextcloud to save the calendar and adressbooks. Is there a kind of a manual how to extract NC's WebDAV-data to use it elsewhere?

**Comment by kesselb** [comment] 2020-04-28 14:31
For questions / support: https://help.nextcloud.com

I'm not sure if the patch you mentioned still works. You can now changes those values in `config.php`. No need to patch the source.

**Closed by kesselb** 2020-04-28 14:31 UTC
Labels: 0. Needs triage, bug
