### ISSUE TITLE
Logs flooded by error: "InvalidArgumentException: server version is invalid"

### ISSUE THREAD

**Issue by fpoulain** [nextcloud/server#25336] opened 2021-01-26 16:14 UTC
### Actual behaviour

Logs are flooded with:
```
[appstoreFetcher] Warning: InvalidArgumentException: server version is invalid at <<closure>>

0. www/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php line 119
   OC\App\CompareVersion->isCompatible("7.3.19-1~deb10u1", "5.6", ">=")
1. www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php line 187
   OC\App\AppStore\Fetcher\AppFetcher->fetch("", "", false)
2. www/nextcloud/apps/updatenotification/lib/Controller/APIController.php line 103
   OC\App\AppStore\Fetcher\Fetcher->get()
3. www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\UpdateNotification\Controller\APIController->getAppList("20.0.6.1")
4. www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\UpdateNotifi ... {}, "getAppList")
5. www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\UpdateNotifi ... {}, "getAppList")
6. www/nextcloud/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\UpdateNoti ... r", "getAppList", OC\AppFramework\ ... {}, {apiVersion: "v1 ... "})
7. www/nextcloud/ocs/v1.php line 88
   OC\Route\Router->match("/ocsapp/apps/up ... 1")
8. www/nextcloud/ocs/v2.php line 24
   require_once("/srv/web/www-in ... p")

GET /nextcloud/ocs/v2.php/apps/updatenotification/api/v1/applist/20.0.6.1
from xx.xx.xx.xx by xxx at 2021-01-26T15:50:09+00:00
```

### Server configuration

**Operating system:** Debian 10

**Web server:** NginX

**Database:** MariaDB

**PHP version:** 7.3.19-1~deb10u1

**Nextcloud version:** 20.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Maybe 13

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by kesselb** [comment] 2021-01-26 17:27
Duplicate of https://github.com/nextcloud/server/issues/25137

**Comment by kesselb** [comment] 2021-01-26 17:28
Please check the [FAQ issue](https://github.com/nextcloud/server/issues/25137) and use the search before posting an issue the next time.

**Closed** 2021-01-26 17:28 UTC
Labels: 0. Needs triage, bug

**Comment by fpoulain** [comment] 2021-01-26 17:57
I searched for this. I have been answered by thousands issues and no one in few first pages appeared to duplicate this issue.

Sorry for the mess.
