### ISSUE TITLE
[Bug]: Files in editable public link shared folder cannot be moved by anonymous viewers

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#43288] opened 2024-02-02 12:35 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sharing a folder via editable public link, anonymous viewers cannot move files, because the file move dialog doesn't load.

![image](https://github.com/nextcloud/server/assets/986878/9d06e16b-0779-4dbf-a486-be7894bf9095)

### Steps to reproduce

1. Share a folder with public link and enable editing
2. As an anonymous user access public link and select "Move or Copy" menu item of a file
3. File move dialog doesn't load files due to HTTP 401 status codes on webdav

### Expected behavior

The file move dialog should load and allow selecting a folder to move/copy the files into.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment] 2024-02-02 13:06
Duplicate of https://github.com/nextcloud/server/issues/42009

**Closed by susnux** 2024-02-02 13:06 UTC
Labels: bug, 0. Needs triage, 28-feedback
