### ISSUE TITLE
[Bug]: Your web server is not properly set up to resolve .well-known URLs, failed on: /.well-known/webfinger

### ISSUE THREAD

**Issue by Lawkss** [nextcloud/server#45505] opened 2024-05-25 11:54 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When upgrading from NC28 to NC29 the following error appeared:

Your web server is not properly set up to resolve `.well-known` URLs, failed on: `/.well-known/webfinger` 

However going to `mydomain.tld.com/.wellknown/webfinger` correctly redirects to `/myNCsubdir/.wellknown/webfinger`

```
{
    "message": "webfinger not supported"
}
```

My config has not changed from NC28 and worked for many main releases of NC:

```
Redirect 301 /.well-known/carddav /MYSUBDIR/remote.php/dav
Redirect 301 /.well-known/caldav /MYSUBDIR/remote.php/dav
Redirect 301 /.well-known/webfinger /MYSUBDIR/index.php/.well-known/webfinger
Redirect 301 /.well-known/nodeinfo /MYSUBDIR/index.php/.well-known/nodeinfo
```

This what I have been using in the apache conf. 
Only webfinger is reported as failed. 

Using RewriteRule in .htaccess as per documentation does not solve the problem. 
Using RewriteRule in vhost as per documentation with additional  ^/\ does not solve the problem. 

### Steps to reproduce

1. Upgrade NC28 to 29 with a subdirectory install.
2. Go to config check page/update page.

### Expected behavior

I would expect it to detect it is working. 

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vom-bruch.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.1.1",
        "overwrite.cli.url": "https:\/\/vom-bruch.com\/cloud",
        "htaccess.RewriteBase": "\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "default_phone_region": "AT",
        "simpleSignUpLink.shown": false,
        "app_install_overwrite": [
            "unsplash"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "maintenance_window_start": 1,
        "updater.release.channel": "stable"
```

### List of activated Apps

```
Enabled:
  - activity: 2.21.1
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.4
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.6.1
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - passman: 2.4.9
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.2
  - richdocumentscode: 24.4.201
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.1
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - encryption: 2.17.0
  - files_external: 1.21.0
  - user_ldap: 1.20.0
```

**Comment by joshtrichards** [comment] 2024-05-25 13:40
You did not fill out the issue template. Any chance you have the optional `social` app installed?

**Comment by kesselb** [comment] 2024-05-25 14:38
Most likely the same as https://github.com/nextcloud/server/issues/45033

**Comment by Lawkss** [comment] 2024-05-25 16:08
I added apps and config.

**Comment by BernieO** [comment] 2024-05-25 16:39
Since your nextcloud resides in a subdirectory:
additionally to adding trailing slashes to the redirects, did you also patch `apps/settings/lib/SetupChecks/CheckServerResponseTrait.php` as well?
https://github.com/nextcloud/server/issues/45033#issuecomment-2095742325

**Comment by Lawkss** [comment] 2024-05-25 17:25
The patch fixes the webfinger error but introduces two new errors for CalDAV and CarDAV

changing the redirect from `remote.php/dav` to `remote.php/dav/` with a / at the end fixes all errors. 

The documentation does not mention / at the end only at the beginning for vhost configs. 

Can the patch be changed so it works without / at the end? Or is that a bad thing?

**Comment by Lawkss** [comment] 2024-06-06 19:51
This is no fixed in NC 29.0.2

You still need to apply this patch after updating:

https://github.com/nextcloud/server/issues/45033#issuecomment-2095742325

**Comment by drankinatty** [comment] 2024-09-07 01:50
I can confirm this issue exactly, **Nextcloud Hub 8 (29.0.6)** on Archlinux:

```none
  kernel:   6.10.8-arch1-1
  Apache:   2.4.62 (Unix)
  OpenSSL:  3.3.1
  PHP:      8.2.23 
```

This issue appeared some time ago with upgrade to Nextcloud 28 if I recall correctly. It was never there before from at least Nextcloud 25 - 27.

Browsing to `https://my.domain.tld/.well-known/webfinger` redirects to `https://my.domain.tld/nextcloud/index.php/.well-known/webfinger` with the raw output being:

```none
{"message":"webfinger not supported"}
```

I'm not sure the [Closed] tag is warranted.

**Comment by adhoc-post** [comment] 2024-09-19 02:02
I had the exact same issue here: NC>=28 reported that my "web server is not properly set up to resolve .well-known URLs", in particular webfinger

Background:
- In Apache, I have correctly setup rewrite rules (since OC ages BTW)
- In particular, `https://my.domain.tld/.well-known/webfinger` correctly resolves to `https://my.domain.tld/nextcloud/index.php/.well-known/webfinger` resulting, however, in "webfinger not supported" messages

Solution (in my configuration): In `config.php` set parameter `overwrite.cli.url` to a meaningful value:
```
'overwrite.cli.url' => 'https://my.domain.tld',
```

Solution found here: https://github.com/nextcloud/server/issues/45033#issuecomment-2077737758

Hope it helps.

**Comment by joshtrichards** [comment] 2024-09-20 14:52
> This issue appeared some time ago with upgrade to Nextcloud 28 if I recall correctly. It was never there before from at least Nextcloud 25 - 27.

@drankinatty That's because the checks ran very differently <28. See https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_28.html#setup-checks

**Comment by joshtrichards** [comment] 2024-09-20 14:55
We've made some further refinements to cover some more edge cases. Will be in upcoming maintenance releases. See #45033

**Closed by joshtrichards** 2024-09-20 14:55 UTC
Labels: bug, 0. Needs triage, feature: settings, 29-feedback

**Comment by oliver4bsb** [comment] 2025-02-11 06:35
yup greetings. in 2025 the bu it is still there . 
apparently the link works fine because i get *This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.*    however in the admin panel i still get the warning message 
"Your web server is not properly set up to resolve `.well-known` URLs, failed on: `/.well-known/webfinger` "
and if i try opening https://myserver/index.php/.well-known/webfinger   i get an internal server error. not big deal tho because apparently all works fine now. this warning appeared after i stalled a few new apps. i will try disable all and see where is the issue. cheers.
