### ISSUE TITLE
Allow upload but no edit permission when sharing link

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#21776] opened 2020-07-09 13:07 UTC
Steps to reproduce: 

1 - Go on vacation;
2 - Send a link to friends to upload the pictures they took;

Expected behavior:
They can upload their pics but they can not delete anything from the shared folder;

Actual behavior:  
They can actually accidentally delete files and you have to warn them not to do so and hope that they read it :) 

![Screenshot from 2020-07-09 15-02-01](https://user-images.githubusercontent.com/26852655/87043572-82925d80-c1f5-11ea-865c-f32279a35c71.png)

**Comment by ma12-co** [comment] 2020-07-09 13:20
Currently these are the options: 

![Screenshot from 2020-07-09 15-15-55](https://user-images.githubusercontent.com/26852655/87044654-26c8d400-c1f7-11ea-92fc-770f490b666a.png)

I suggest we caption it and do: 

Allow recipients to:
o View
o Upload
o View and upload
o View, upload and edit

**Comment by nickvergessen** [comment] 2020-07-09 14:26
cc @jancborchardt

**Comment by nickvergessen** [comment] 2020-07-10 09:59
Duplicate of #15656

**Comment by jancborchardt** [comment] 2020-07-10 12:14
I would say if we do this, @ma12-co’s proposal is better than the one in #15656, so we could close that in favor of this one.

@rullzer what do you think about adding another specific option "View and upload"?

**Comment by rullzer** [comment] 2020-07-10 15:54
Fine by me.

**Comment by kesselb** [comment] 2020-07-10 18:59
> They can actually accidentally delete files and you have to warn them not to do so and hope that they read it :)

I always create a file drop share and a read only share for such a use case.

**Comment by ma12-co** [comment] 2020-07-14 08:44
So? reopen or wat?

**Comment by ma12-co** [comment] 2020-07-14 11:05
I see that in the other issue the reshare permission is also mentioned. Does it even make sense to include this given that we're talking about a public link?

**Comment by nickvergessen** [comment] 2020-07-14 13:17
Resharing is considered when you "mount the link" as federated share on your instance.

**Comment by ma12-co** [comment] 2020-07-15 05:00
Ok, so I think that we should allow to mount the link always but when you're only allowed to upload.

o View `implicit allow re-share`
o Upload
o View and upload `implicit allow re-share`
o View, upload and edit `implicit allow re share`

Would there be any significant drawback to that?

**Comment by aouuwoe** [comment] 2020-07-19 10:08
Hi, 
I got the same problem. It would also be helpful to have a option that for every file drop a folder can be created.
For example I share one single file drop link and every user that uploads needs to specify a name and a folder is created with this name. 
So you can share one link for upload and one for viewing, for example: Holiday photos is shared and inside that folder folders get created for the user that uploads (Holiday photos/user1... Holiday photos/user2, ....
I also made a feature request some time ago #16279

**Comment by tobiasKaminsky** [comment] 2020-07-20 11:08
Upload is "file drop (upload only"?

**Comment by tobiasKaminsky** [comment] 2020-07-20 11:09
> Ok, so I think that we should allow to mount the link always but when you're only allowed to upload.
> 
> o View `implicit allow re-share`
> o Upload
> o View and upload `implicit allow re-share`
> o View, upload and edit `implicit allow re share`
> 
> Would there be any significant drawback to that?

Upload is "file drop (upload only"?

**Comment by jancborchardt** [comment] 2020-07-20 11:16
> Ok, so I think that we should allow to mount the link always but when you're only allowed to upload.
> 
> o View `implicit allow re-share`
> o Upload
> o View and upload `implicit allow re-share`
> o View, upload and edit `implicit allow re share`
> 
> Would there be any significant drawback to that?

@rullzer can you comment on that?

@tobiasKaminsky and yes, to clarify "Upload" here is the current "File drop (upload only)".

**Comment by szaimen** [comment] 2020-10-22 21:58
Any news on this? Would be a great feature e.g. for NC21 ;)

**Comment by toas-koas** [comment] 2022-04-25 11:54
Is there any Update?

**Comment by szaimen** [comment] 2022-04-25 11:56
I think this will be possible with NC24. So closing.

**Closed by szaimen** 2022-04-25 11:56 UTC
Labels: enhancement, 1. to develop, feature: sharing
