### ISSUE TITLE
Resource Intensive File Upload Behavior

### ISSUE THREAD

**Issue by hsand** [nextcloud/server#5227] opened 2017-06-02 09:48 UTC
When uploading files, the data is simultaneously copied to the PHP temp folder (defaults to /tmp) in addition to the user's data folder (and appended a *.part extension until the transfer is complete).

This functionality seems reasonable in a situation where the destination is external storage. Files are first stored on the local machine before being uploaded elsewhere. However, this seems rather resource intensive when simply copying a file to local storage.

I've checked this behavior with lsof, and grepping for my upload and temp directories. Both files are open and actively written to at the same time. My upload and temp directories are on the same file system.

**Comment by sf-janz** [comment] 2017-06-08 15:12
@hsand are you using nginx?

**Comment by hsand** [comment] 2017-08-16 20:55
Very delayed response on my end... but I'm using Apache.

**Comment by MorrisJobke** [comment] 2017-08-31 12:34
This is the intended behaviour. As of now we try to make our quite complex filesystem layer as uniform as possible. This also includes how uploads are handled. We haven't seen any big performance issues with that way of dealing with uploads. If there is a significant performance decrease in your setup I would ask you to seek for help in the forums: https://help.nextcloud.com

Maintaining a dedicated upload behaviour depending on the used file backend is quite resource intensive from our point of view and has minimal impact on the tested setups in our case.

cc @icewind1991 for correctness.


I will close this here and would ask you to do some tests with the help of the people in the forums. Thanks

**Closed by MorrisJobke** 2017-08-31 12:34 UTC
Labels: needs info
