### ISSUE TITLE
[Bug]: search stays active even when using main folder list, and lead to empty folder display which is very misleading

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#32126] opened 2022-04-25 12:36 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Regression from NC 24 ?

I have a folder with 2 subfolders
![image](https://user-images.githubusercontent.com/87175513/165088941-4486a905-d442-478a-b18e-dee057e979f7.png)

In the search, I type the name of one of them "JeanJean"
Only that folder appears in the folder list
I click on it, from the folder list
![image](https://user-images.githubusercontent.com/87175513/165087530-cfd6dd47-81aa-4332-88c4-c83ee812b833.png)

It appears empty, however, it is not.
![image](https://user-images.githubusercontent.com/87175513/165087431-82be003d-25f9-4841-80bc-bfc2b55dac48.png)

We can see that the search is still active and filters the content...
![image](https://user-images.githubusercontent.com/87175513/165087472-05ac86bc-0021-4829-aa42-5896aceb1dfb.png)

When search is cleared, content appears.
![image](https://user-images.githubusercontent.com/87175513/165089310-1cbe3871-5c79-4c78-8fd7-69b5f8d4463d.png)

### Steps to reproduce

Let's consider the following folder structure:
- homedir
  - Folder 1
    - subfolder AA
    - subfolder AB
    - subfolder AC
  - Folder 2
    - subfolder BA
    - subfolder BB
    - subfolder BC

1. In homedir, TYPE the name of "Folder 1" in the search field
2. On the main screen (folder list), CLICK on the "Folder 1" entry

The main screen (folder list), displaying the content of Folder 1 is empty.

### Expected behavior

Either:
- the search field stays open, so the user understand that the filter still apply.

Or:
- clicking any folder in the folder list opens the folder and clears the search.

I'd prefer the latter.

### Operating system

Debian/Ubuntu

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
ask c.nc.com
```

**Comment by CarlSchwan** [comment] 2022-04-25 12:42
Confirmed on NC 24 RC 1

**Comment by szaimen** [comment] 2022-04-25 12:42
I think this is not new in 24 though...

**Comment by PVince81** [comment] 2022-04-25 12:47
I've seen this in 23 already as I remember being annoyed by it.

I'm not sure if this is by design, so either:

1) when closing the search the filter must reset, but this makes it impossible to operate

2) when closing the search, an indicator of sorts should be displayed to make it clear that the list is currently still filtered

@jancborchardt thoughts ?

**Comment by jancborchardt** [comment] 2022-04-25 21:21
Yeah, there's another option:
- When navigating, the search should be cleared.

This would keep the list still filtered when you open files and close the viewer, but it would ensure an expected view when you go into a folder or anywhere else using the breadcrumbs.

**Closed** 2023-05-17 07:14 UTC
Labels: bug, 1. to develop, 24-feedback
