### ISSUE TITLE
unlinked events after sharing Calendar app caldav

### ISSUE THREAD

**Issue by PittRo** [nextcloud/server#17284] opened 2019-09-26 14:55 UTC
### Steps to reproduce
1. user A invites today 3pm internal user B to an event
2. user B has some other event conflicts and moves the events to 4pm
3. it creates to seperatly unlinked events :-1: 

### Expected behaviour
1. action of user B should change time to 4pm in calendar event of user A
2. email should be sent to user A, that user B has changed the event
OR
1. action of user B should delete the event of user A
2. a new invitation should be sent to user A 

### Actual behaviour
both events are unlinked

Usecase if user A changes time
here everything works fine, the event of user b moves to new time

### Server configuration
Ubuntu
Apache
MySQL
PHP 7.2
Nextcloud v16

**List of activated apps:**
<details>
<summary>Accessibility	1.2.0	Offiziell	
Announcement Center H H	0.0.7		
Brute-force settings	1.4.0	Offiziell	
Calendar	1.7.1	Offiziell	
Collaborative tags	1.6.0	Offiziell	
Comments	1.6.0	Offiziell	
Custom CSS	1.3.0		
Deleted files	1.6.0	Offiziell	
External storage support	1.7.0	Offiziell	
Federation	1.6.0	Offiziell	
File sharing	1.8.0	Offiziell	
Files automated tagging	1.6.0	Offiziell	
First run wizard	2.5.0	Offiziell	
Log Reader	2.1.0	Offiziell	
Monitoring	1.6.0	Offiziell	
Nextcloud announcements	1.5.0	Offiziell	
Notifications	2.4.1	Offiziell	
Notifications for calendar event updates	0.3.4		
Password policy	1.6.0	Offiziell	
PDF viewer	1.5.0	Offiziell	
Privacy	1.0.0		
Recommendations	0.4.0		
Retention	1.5.1	Offiziell	
Right click	0.15.1		
Share by mail	1.6.0	Offiziell	
Support	1.0.0	Offiziell	
Talk	6.0.4	Offiziell	
Text editor	2.8.0	Offiziell	
Theming	1.7.0	Offiziell	
Unsplash	1.1.3		
Update notification	1.6.0	Offiziell	
Usage survey	1.4.0	Offiziell	
Video player	1.5.0	Offiziell	
Viewer	1.0.0	</summary>
</details>

**Comment by georgehrke** [comment] 2019-09-30 09:22
> action of user B should change time to 4pm in calendar event of user A

The behaviour that you suggest is definitely not the expected behaviour. Simple attendees are not supposed to alter the event.

Duplicate of https://github.com/nextcloud/calendar/issues/489

**Comment by georgehrke** [comment] 2019-09-30 09:23
Please note that the events are not unlinked. If User a modifies the event, the changes will apply to the event of user B.
It's simply that user A is the organiser and has the right to update it and user B is a simple attendee.

**Closed by georgehrke** 2019-09-30 09:22 UTC
Labels: 0. Needs triage, bug

**Comment by PittRo** [comment] 2019-09-30 12:50
@georgehrke yes I understand the considered logic but there is unfortunately no possibility to find out for user A or user B, who is the owner if the orginal event.
So my is issue is very well justified!! You can't build a logic rely on it to remember the event-fact.

**Comment by georgehrke** [comment] 2019-09-30 12:51
There is an issue for that as well: https://github.com/nextcloud/calendar/issues/486
