### ISSUE TITLE
Nextcloud Windows-Client  does not sync folders with a space " " in the end

### ISSUE THREAD

**Issue by BBoSec** [nextcloud/server#7869] opened 2018-01-15 12:58 UTC
### Steps to reproduce
1. create an folder like "bug-folder"
2. add an space " " to the foldername: "bug-folder "
3. now the nextcloud client will not sync this folder anymore

### Expected behaviour
client should sync folder

### Actual behaviour
client does not ync folder

### Server configuration

**Operating system**: N.N.

**Web server:** N.N.
 
**Database:** N.N.

**PHP version:** N.N.

**Nextcloud version:** (see Nextcloud admin page)N.N.

**Updated from an older Nextcloud/ownCloud or fresh install:**N.N.

**Where did you install Nextcloud from:**N.N.

**Signing status:** N.N.

### Client configuration
**Browser:** Firefox 57.0.4 (64Bit)

**Operating system:** Win10

**Client Software:** Version 2.3.3 (build 1) - Gebaut von der GIT-Revision 57bc79 auf Nov 20 2017, 09:32:15 verwendet Qt 5.6.2, OpenSSL 1.0.2h 3 May 2016

**Comment by MorrisJobke** [comment] 2018-01-15 16:25
Duplicate of #5843

**Closed by MorrisJobke** 2018-01-15 16:25 UTC
