### ISSUE TITLE
Upgrade 11.0.0->11.0.1 disables apps

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#3123] opened 2017-01-17 16:27 UTC
Title says it all:
After upgrading smoothly from 11.0.0 to 11.0.1 using the updater and running occ upgrade, my private apps (having nextcloud min-version="10" max-version="11") were disabled again. According to https://github.com/nextcloud/server/pull/1527#issuecomment-249549406 , this shouldn't happen any more.

Checking again, the mail app is disabled as well, so apparently not only my private apps are affected.

**Comment by wahlis** [comment] 2017-01-17 19:08
I had the same issue. After upgrade 11.0.0 -> 11.0.1 all apps were disabled

**Comment by MorrisJobke** [comment] 2017-01-18 00:47
> According to #1527 (comment) , this shouldn't happen any more.

Sadly not. We plan to fix this. This is a duplicate of #239

**Closed by MorrisJobke** 2017-01-18 00:47 UTC
