### ISSUE TITLE
Improvement in update process: Check for expected files bypass needed !!

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#8831] opened 2018-03-15 11:54 UTC
big annoying files check is done when updating.

Check for expected files !
The following extra files have been found:
filer
ioncube
info.php
abuseipdb-verification.html
susperseed.sh
tobackup.sh
ovh-security.html

followed by red blocking point ! 
Yes i perfectly know those files are here because their mine, their needed, 

Every time i need to update, i have to tweak my needed files to match what you need !!!

I NEED MY FILES to be accepted/bypassed instead of having to comply to the files check ( and i am pretty sure i am not the only one )

I can understand you perform a file check, but  as i server admin, i should have a way to bypass this without digging in my set-up, ssh-ing or ftp-ing my files away !!!

Why dont you add some check box to bypass those files ? or else ?

**Comment by MorrisJobke** [comment] 2018-03-15 15:19
Duplicate of https://github.com/nextcloud/updater/issues/68

**Closed by MorrisJobke** 2018-03-15 15:19 UTC
