### ISSUE TITLE
External Storage error deleting folder

### ISSUE THREAD

**Issue by vgdh** [nextcloud/server#15577] opened 2019-05-16 17:58 UTC
### Steps to reproduce
1. Install next cloud with docker-compose
................
 image: nextcloud
    networks:
      - nextcloud_net
    volumes:
      - /media/data_1/nextcloud/nc_data:/var/www/html
      - /media/data_1/nextcloud_ext:/media/nextcloud_ext
......................
2. Add external folder /media/nextcloud_ext
3. Сreate a directory through nextcloud and delete it. A pop-up delete error message will appear **but the directory will be deleted.**
4.Through long trial and error, I found out that the error is only when the external folder is in the same direction as the nextcloud files, and if you move the directories in a different folder, for example
      - /nc/nc_data:/var/www/html
      - /media/data_1/nextcloud_external_storage:/media/nextcloud_external_storage
then the error does not appear

**Comment by szaimen** [comment] 2021-05-20 13:05
I suppose this is due to incorrect unix permissions but as I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-20 13:05 UTC
Labels: 0. Needs triage, bug
