### ISSUE TITLE
Login Failed despite the fact that the password is correct

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#20173] opened 2020-03-26 07:40 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Head to my nextcloud
2. type password and username
3. Click login

### Expected behaviour
It should login in successfully

### Actual behaviour
Password error

### Server configuration

**Operating system:**
Centos 7

**Web server:**
nginx version: nginx/1.16.1

**Database:**
mysql  Ver 15.1 Distrib 5.5.64-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.1.33 (cli) (built: Oct 26 2019 10:16:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
  - installed: true
  - version: 16.0.4.1
  - versionstring: 16.0.4
  - edition: 

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - audioplayer: 2.8.4
  - audioplayer_sonos: 1.0.1
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.2
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - encryption: 2.4.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.5.0
  - files_readmemd: 1.1.3
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - flowupload: 0.1.7
  - gallery: 18.3.0
  - keeweb: 0.5.1
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - music: 0.12.1
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ocdownloader: 1.7.5
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.3
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - unsplash: 1.1.4
  - updatenotification: 1.6.0
  - uploaddetails: 0.1.2
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxx.xxxxx.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "https:\/\/192.168.50.197",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "owncloud",
        "logfile": "\/usr\/share\/nginx\/nextcloud\/data\/nextcloud.log",
        "loglevel": "0",
        "logdateformat": "F d, Y H:i:s",
        "mysql.utf8mb4": true,
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

Vivaldi

**Operating system:**

macOS Catalina 10.15.3

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"implode(): Invalid arguments passed at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"implode(): Invalid arguments passed at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: class at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#52","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: type at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#52","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:20:39","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"implode(): Invalid arguments passed at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"V9QoyUddunhoU5ZJdNDq","level":2,"time":"March 26, 2020 07:21:29","remoteAddr":"","user":"--","app":"core","method":"POST","url":"\/login?redirect_url=\/apps\/files\/","message":"Login failed: 'xxxx' (Remote IP: '')","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.158 Safari\/537.36","version":"16.0.4.1"}
{"reqId":"V9QoyUddunhoU5ZJdNDq","level":1,"time":"March 26, 2020 07:21:29","remoteAddr":"","user":"--","app":"core","method":"POST","url":"\/login?redirect_url=\/apps\/files\/","message":"Bruteforce attempt from \"\" detected for action \"login\".","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.158 Safari\/537.36","version":"16.0.4.1"}
{"reqId":"32s99fVBXu6UucrFJTH2","level":0,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"core","method":"GET","url":"\/apps\/files\/","message":{"Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotLoggedInException","Message":"Current user is not logged in","Code":401,"Trace":[{"file":"\/usr\/share\/nginx\/nextcloud\/lib\/private\/AppFramework\/Middleware\/MiddlewareDispatcher.php","line":95,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/usr\/share\/nginx\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":98,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/usr\/share\/nginx\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"index"]},{"file":"\/usr\/share\/nginx\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["ViewController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"files.view.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"files.view.index"}]},{"file":"\/usr\/share\/nginx\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"files.view.index"}]},{"file":"\/usr\/share\/nginx\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/files\/"]},{"file":"\/usr\/share\/nginx\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/usr\/share\/nginx\/nextcloud\/lib\/private\/AppFramework\/Middleware\/Security\/SecurityMiddleware.php","Line":143,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/80.0.3987.158 Safari\/537.36","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"implode(): Invalid arguments passed at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"implode(): Invalid arguments passed at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: class at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#52","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined index: type at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#52","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Array to string conversion at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"Nbc3RC0Bibqt3ALOZH2D","level":3,"time":"March 26, 2020 07:21:43","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"implode(): Invalid arguments passed at \/usr\/share\/nginx\/nextcloud\/apps\/logreader\/lib\/Log\/Formatter.php#93","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Files\\BackgroundJob\\ScanFiles job with ID 15","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files\\BackgroundJob\\ScanFiles job with ID 15 in 0 seconds","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 17","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 17 in 0 seconds","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Support\\BackgroundJobs\\CheckSubscription job with ID 18","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Support\\BackgroundJobs\\CheckSubscription job with ID 18 in 0 seconds","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 19","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating session tokens older than 2020-03-25T07:30:02+00:00","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating remembered session tokens older than 2020-03-11T07:30:02+00:00","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating session tokens older than 2020-03-25T07:30:02+00:00","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Invalidating remembered session tokens older than 2020-03-11T07:30:02+00:00","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 19 in 0 seconds","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Log\\Rotate job with ID 20","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Log\\Rotate job with ID 20 in 0 seconds","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 28","userAgent":"--","version":"16.0.4.1"}
{"reqId":"FAGU58UlDiip0753KgJf","level":0,"time":"March 26, 2020 07:30:02","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 28 in 0 seconds","userAgent":"--","version":"16.0.4.1"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rubo77** [comment] 2020-09-17 11:37
What is the actual error message?

**Comment by szaimen** [comment] 2021-06-11 10:08
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-11 10:08 UTC
Labels: 0. Needs triage, bug
