### ISSUE TITLE
Previews for single shared files is not updated 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#702] opened 2016-08-02 09:56 UTC
- upload a file abc.png
- share this file
- overwrite the file abc.png with another image via WebDAV
- check the shared link
## expected
- preview is updated
## actual
- preview is not updated

**Comment by MorrisJobke** [comment] 2016-08-02 10:13
This is only stable9

**Comment by rullzer** [comment] 2016-08-03 08:28
The issue is non-shared previews:

* Share a folder with a group
* Upload a file a.png to that folder as owner
* As recipient overwrite a.png
* See that the owners preview is not updated

**Comment by rullzer** [comment] 2016-08-08 07:00
As discussed in person last week. This boils down to the shared preview issue.

In the current state all previews are bound to the user. Which means that if N people have access to a file N previews will be generated (well N*M since you can have multiple preview sizes). We have no (scaleable) way to clean this up properly.

The solution is we should share previews. This saves time (generation) and space (deduplication) of previews. I'm working on a PR to make this happen.

**Comment by adsworth** [comment] 2016-10-18 10:23
I just ran into this as well. There is also no way of fixing this. The owner either has to touch the images so they are resynced and his previews get regenerated or the admin has to delete the users thumbnails directory.

**Comment by rullzer** [comment] 2016-11-03 20:09
Fixed with https://github.com/nextcloud/server/pull/1741

**Closed by rullzer** 2016-11-03 20:09 UTC
Labels: bug
