### ISSUE TITLE
imagettftext(): Could not read font at 

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#8684] opened 2018-03-06 10:49 UTC
On my distribution nextcloud avatar default does not bear initial user name in the logs I noticed this error how can I fix?
![immagine2](https://user-images.githubusercontent.com/35575744/37028392-689b67dc-2134-11e8-84c6-a4a8c5ecb623.png)

Keeping in mind that the site is hosted on a shared web space

![immagine](https://user-images.githubusercontent.com/35575744/37028305-31c265b2-2134-11e8-809c-d0bc1e29edc0.png)

I receive error

`Undefined index: loginForm at /web/htdocs/www.pensierando.it/home/Nextcloud/apps/ojsxc/settings/personal.php#22`

`imagettftext (): Could not read font at /web/htdocs/www.pensierando.it/home/Nextcloud/lib/private/Avatar.php#266`

**Comment by tigernero79** [comment] 2018-03-06 11:16
I used this url your to fix error
https://github.com/nextcloud/server/pull/8428
but I had to manually edit the avatar.php file and insert the 2 ttf in the font folder

Should you always use this fix?

**Comment by MorrisJobke** [comment] 2018-03-06 12:31
Duplicate of #8189

**Comment by MorrisJobke** [comment] 2018-03-06 12:31
Fixed with #8428 and will be released in 13.0.1

**Closed by MorrisJobke** 2018-03-06 12:31 UTC
