### ISSUE TITLE
Bookmarks and Calendar views empty, when Files was not visited previously

### ISSUE THREAD

**Issue by dgsiegel** [nextcloud/server#10108] opened 2018-07-04 19:10 UTC
### Steps to reproduce
1. Start a new browser session
2. Directly navigate to either the bookmarks or calendar app URL
3. Content is empty

### Expected behaviour

Both bookmarks or calendar should display their normal content.

### Actual behaviour

Instead I get this Javascript error

```
bookmarks.js?v=3c923dd2-0:151 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.success (bookmarks.js?v=3c923dd2-0:151)
    at j (core.js?v=3c923dd2-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=3c923dd2-0:2)
    at x (core.js?v=3c923dd2-0:4)
    at XMLHttpRequest.<anonymous> (core.js?v=3c923dd2-0:4)
```

Loading the files app first and then navigating to bookmarks or calendar circumvents this error.

### Server configuration

**Operating system**: Debian 9

**Web server:** Lighttpd

**Database:** SQLite

**PHP version:** 7.1

**Nextcloud version:** 13.0.2, but this error exists since 10 at least

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated continiously from Owncloud 6

**Where did you install Nextcloud from:** Upgrade via occ

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "13.0.2.1",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trusted_domains": [
            "cloud.nopln.org"
        ],
        "mail_smtpmode": "php",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 60",
        "appstore.experimental.enabled": false,
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.nopln.org"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome, Firefox

**Operating system:** Linux, Android, Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors found
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors found
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
bookmarks.js?v=3c923dd2-0:151 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.success (bookmarks.js?v=3c923dd2-0:151)
    at j (core.js?v=3c923dd2-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=3c923dd2-0:2)
    at x (core.js?v=3c923dd2-0:4)
    at XMLHttpRequest.<anonymous> (core.js?v=3c923dd2-0:4)
```
</details>

**Comment by MorrisJobke** [comment] 2018-07-05 08:50
@rullzer @blizzz @nickvergessen Any idea what could cause this? Is there some special hook triggered in the files app?

**Comment by marcelklehr** [comment] 2018-08-08 19:13
Just saw this by chance.

@dgsiegel I couldn't replicate this with my setup. The error probably means there was a problem fetching the bookmarks. Do you need to sign into nextcloud when starting such a new browser session? (Do your cookies persist across sessions?)

**Comment by dgsiegel** [comment] 2018-08-11 23:24
> Do you need to sign into nextcloud when starting such a new browser session? (Do your cookies persist across sessions?)

No, I am logged in and several cookies persist.

**Comment by skjnldsv** [comment] 2020-08-25 09:18
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:18 UTC
Labels: 0. Needs triage, bug
