### ISSUE TITLE
Custom Logo in IE doubled

### ISSUE THREAD

**Issue by Speedysurf** [nextcloud/server#4861] opened 2017-05-14 17:44 UTC
### Steps to reproduce
1. Upload custom Logo
2. Open public share link in browser -> Logo double
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Debian Jessie

**Web server:** Apache

**Database:** mysql 5.5.55

**PHP version:** 5.6

**Nextcloud version:** 12 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** nextcloud.com

**Comment by MorrisJobke** [comment] 2017-05-14 23:13
What browser do you use? Anything the web developer console?

**Comment by Speedysurf** [comment] 2017-05-15 07:05
Hi,
Chrome, Firefox, Safari.
The "problem" is on Guest-Share-Page. The normal login Page is OK.

**Comment by MorrisJobke** [comment] 2017-05-15 14:56
> The "problem" is on Guest-Share-Page. The normal login Page is OK.

Ah - okay 👍

**Comment by MorrisJobke** [comment] 2017-05-15 14:56
cc @icewind1991 @juliushaertl

**Comment by juliushaertl** [comment] 2017-05-17 08:04
I cannot reproduce. Public sharing pages look as expected here on beta2 and master.

![2017-05-17-100308_960x467_scrot](https://cloud.githubusercontent.com/assets/3404133/26144198/30744154-3ae8-11e7-85d7-225253461a93.png)


@Speedysurf Can you post a screenshot?

**Comment by Speedysurf** [comment] 2017-05-17 08:18
On the guest-login-page is the problem.

**Comment by icewind1991** [comment] 2017-05-17 13:37
I believe this was fixed with https://github.com/nextcloud/server/pull/4771/files, @Speedysurf can you see if that fixes it for you

**Comment by Speedysurf** [comment] 2017-05-17 13:41
Yes! Now it's ok!

**Comment by Speedysurf** [comment] 2017-05-17 13:46
Sorry, to fast. In Chrome, Firefox ok, but in IE is now no logo.

**Comment by MorrisJobke** [comment] 2017-05-22 05:27
Tested with IE 11 and Edge and this is not a problem anymore. We recently changed some things there, so this should be also fixed for you in the 12 release

**Closed by MorrisJobke** 2017-05-22 05:27 UTC
Labels: feature: sharing, feature: theming, regression
