### ISSUE TITLE
Low priority for preview generation

### ISSUE THREAD

**Issue by PaulLereverend** [nextcloud/server#17966] opened 2019-11-16 13:50 UTC
Hi ! 
I would like to share a feature request. 

**Is your feature request related to a problem? Please describe.**

Low hardware like raspberry pi or other ARM based cpu become unresponsive when generating previews. When we upload multiple images in a folder, the server has to generate the previews. This uses all the CPU power so the web interface becomes very slow and unresponsive. It is a bigger issue when you have 2 users on the same server. 

**Describe the solution you'd like**

The idea would be to generate previews with a low priority on the CPU, so the interface remains usable.

**Comment by kesselb** [comment] 2019-11-16 15:09
Hey ;) 

Sounds like a duplicate of https://github.com/nextcloud/server/issues/1732 to me. From a technical point it's not possible

**Comment by go2sh** [comment] 2019-11-16 15:09
I'am not 100% sure. But the previews should be generated by the cron script. So you should run it from cron (crontab setting and not per ajax or request) and then control either the nice level or cpulimit and/or place it in a cgroup handling it.

**Comment by kesselb** [comment] 2019-11-16 15:11
@go2sh it depends ;) By default previews are requested via http and generated on demand.  Some people are using the previewgenerator app to generate the previews by cron.

**Comment by sunjam** [comment] 2019-11-16 15:22
[See this PR](https://github.com/nextcloud/server/pull/16158), related to the above link.

**Comment by PaulLereverend** [comment] 2019-11-16 17:06
@kesselb I'm using the previewgenerator app from cron at night and it works pretty well. But when we upload images, the previews are generated immediately (due to on demand) which make the server unresponsive. 

I already did the recommendations from ownyourbits which improved the situation but I think it can still be improved. 

if I'm not mistaken the php request start a few ffmpeg processes to generate thoses previews. Isn't it possible to decrease the priority of thoses processes ?

**Comment by dgtlmoon** [comment] 2019-11-16 18:18
In my opinion this is the wrong way to go forwards, as a systems engineer I can see that when a process (even if it's "low" priority) is going to attempt to read all the data from the disk file to generate a set of thumbnails.

Most NAS/storage systems that nextcloud run on contain spinning disks, you cannot make a spinning disk any faster, you cannot say 'oh well its on low CPU priority', that disk header is doing stuff, it's busy, it's going to affect the whole system no matter what

you need to look at 

- creating less thumbnails
- creating smaller thumbnails
- dont create the huge preview even when you might just want to see that jpeg once a year
- using existing EXIF metadata thumbnails, that will save you from scanning the whole file (my $200 smartphone now creates photos of 12 megabytes!)

**Comment by kesselb** [comment] 2019-11-16 19:35
> if I'm not mistaken the php request start a few ffmpeg processes to generate thoses previews. Isn't it possible to decrease the priority of thoses processes ?

Afaik ffmpeg is only involved for movie thumbnails. If you decrease ffmpeg priority I would expect even more lag because with lower priority generation takes more time and the process will block.

**Comment by go2sh** [comment] 2019-11-16 22:38
Ok, so ultimalty this is a feature request for a preview generation architecture, that can be constrained by cgroups.

**Comment by kesselb** [comment] 2019-11-16 22:54
@go2sh https://github.com/nextcloud/server/issues/7855

**Comment by kesselb** [comment] 2019-11-16 22:55
@PaulLereverend okay with you to close this issue? https://github.com/nextcloud/server/labels/feature%3A%20previews%20and%20thumbnails we have plenty of issues tagged for preview generation. I'm not sure if we need another one ;)

**Comment by dgtlmoon** [comment] 2019-11-17 13:43
please closet his issue, it only exists as someone's guess as to the symptoms of existing problems

**Closed** 2019-11-17 18:10 UTC
Labels: 0. Needs triage, enhancement, feature: previews and thumbnails, needs info
