### ISSUE TITLE
Allowed memory size of 256MB bytes exhausted (tried to allocate 4096 bytes) ..Doctrine/DBAL/Driver/PDOStatement.php#104

### ISSUE THREAD

**Issue by greenorca** [nextcloud/server#3659] opened 2017-02-28 17:30 UTC
### Steps to reproduce
1. recursively deleted big folder containing tons of html/php files (backup of xtcommerce project) on client file system while NC11.02 server is up an running (nextcloud client Version 2.2.4. )
3. same error occurs if I try to delete this folder using the nextcloud web interface

### Expected behaviour
Tell us what should happen
NC should silently delete folder from server too :)

### Actual behaviour
Tell us what happens instead
* Series of errors according to NextCloud Logging (WebFrontend): Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) at /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#104
* files seem to remain on server 

### Server configuration
**Operating system**:
Linux odroid 3.10.103 #1 SMP PREEMPT Sat Sep 10 14:43:59 UTC 2016 armv7l
(Debian Jessie)
**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
5.7.17-0ubuntu0.16.04.1 - (Ubuntu)
**PHP version:**
PHP 7.0.15-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.2, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from 11.0.1, from 10, from 9...
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list
Calendar, MarkdownEditor + usual (default) suspects 
</summary>

sudo -u www-data php occ app:list
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.0
  - comments: 1.1.0
  - dav: 1.1.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - gallery
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
$CONFIG = array (
  'instanceid' => 'oco31zt449xm',
  'passwordsalt' => '4aMGSKpMEDC3kzpnLcRes+pkBfKy31',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'odroid',
    1 => 'green-orca.hopto.org',
    2 => '192.168.0.50',
  ),
  'datadirectory' => '/mnt/usb_store/nextcloud',
  'overwrite.cli.url' => 'https://odroid',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud9',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_sven',
  'dbpassword' => '****',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'updater.secret' => '****',

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
/mnt/usb_store (attached HDD)
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder
                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.          
                                                                  

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**
Xubuntu 1604
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
`[Tue Feb 28 17:14:18.892830 2017] [:error] [pid 2261] [client 192.168.0.1:60226] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 104
[Tue Feb 28 17:14:25.079181 2017] [:error] [pid 2229] [client 192.168.0.1:60234] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 104
[Tue Feb 28 17:14:25.083294 2017] [:error] [pid 2229] [client 192.168.0.1:60234] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 77
[Tue Feb 28 17:14:25.488961 2017] [:error] [pid 2236] [client 192.168.0.1:60232] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 104
[Tue Feb 28 17:14:27.846140 2017] [:error] [pid 2347] [client 192.168.0.1:60230] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 104
[Tue Feb 28 17:14:27.864861 2017] [:error] [pid 2347] [client 192.168.0.1:60230] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 67
``
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
empty
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

Thanks a lot for looking into this, feel free to contact me

**Comment by greenorca** [comment] 2017-03-01 05:24
The issue was fixed by removing the folder using ssh, further running the occ files:clear and files:scan commands.

**Comment by KekcuHa** [comment] 2017-03-01 09:01
Dupe of https://github.com/nextcloud/server/issues/3340

**Closed** 2017-03-04 04:07 UTC
