### ISSUE TITLE
Mac OS 10.7.5 - the client does not even start

### ISSUE THREAD

**Issue by plrunner** [nextcloud/server#1240] opened 2016-09-02 07:13 UTC
The client does not start even if considered compatibile to 10.7.+
Launching it from terminal returns "illegal instruction 4".
I upgrade to El Capitan and it got solved.

**Comment by LukasReschke** [comment] 2016-09-02 08:44
Please reopen at https://github.com/nextcloud/client_theming/issues, seems like a dupe of https://github.com/nextcloud/client_theming/issues/14 though.

Did you try with 10.8 by any chance?

**Closed by LukasReschke** 2016-09-02 08:44 UTC

**Comment by plrunner** [comment] 2016-09-02 08:47
Ops, sorry, I was on my mobile and did not figured out I was on the wrong project.

No, I didn't try with 10.8 because it got upgraded directly to 10.11.
