### ISSUE TITLE
How to get the App Token out of the database?

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#16915] opened 2019-08-28 14:04 UTC
Hey guys,

when you enable 2FA the "clear" passwords for CalDAV and CardDAV don't work anymore (logically...).
I'm developing this library: https://github.com/alve89/PHPMobileConfig

Since all the password fields are filled out automatically I need the App/Device specific password to be filled into the .mobileconfig file. None of the tokens in the database (oc_authtoken) match the generated ones - so how can I get the used password/token?

Nextcloud version: 16.0.4

**Comment by kesselb** [comment] 2019-08-28 14:24
cc @rullzer @ChristophWurst

**Comment by ChristophWurst** [comment] 2019-08-28 14:30
You can't. They are encrypted by the user password. Where would your lib run? As part of a Nextcloud app?

**Comment by alve89** [comment] 2019-08-28 19:57
Actually there was a plan to implement this in Nextcloud default settings, but I never heard about this again. Maybe I make this my own. 
But right now this is a standalone library everyone can use. So there’s no way to handle this? I have the individual user passwords (plain text) as they come from a login form and are stored in the IMAP database of my host. So I could decrypt the tokens if possible...?

**Comment by rullzer** [comment] 2019-08-29 05:56
No. the issue is that the tokens are hashed in the database. the reason for this is that the app tokens are also are able to unlock the user password (for things like external storage etc).

What would probably be the way to go here is to create an apptoken on demand.
Now the issue is that this is isn't public API, for well obvious reasons.

Let me discuss with @ChristophWurst

**Comment by rullzer** [comment] 2019-08-29 05:57
And btw theer already is some OSX profile stuff in Nextcloud. Maybe integrating better would be nice indeed. As long as it is in the settings app we could make sure that you get your apptoken generated.

**Comment by szaimen** [comment] 2021-05-31 08:57
As the initial request was answered, I am going to close this issue.

**Closed by szaimen** 2021-05-31 08:57 UTC
Labels: 0. Needs triage, bug, help wanted
