### ISSUE TITLE
NC12b2: opening "additional admin settings" yields internal server error

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#4823] opened 2017-05-11 22:30 UTC
### Steps to reproduce
1. Upgrade to NC 12 beta 2
2. Open Administration
3. Select "additional settings" in left pane

### Expected behaviour
additional settings tab should open

### Actual behaviour
internal server error is displayed (in NC designed page):
![settings-admin-additional_internal-server-error](https://cloud.githubusercontent.com/assets/8425483/25974554/09fdadcc-36aa-11e7-907a-d386771302d7.png)
Note: The logo (SVG) is displayed scrambled here, too.

### Server configuration
OS: debian 8.8, up-to-date
Web server: Apache 2.4
Database: mySQL 5.5
PHP version: 5.6
Nextcloud version: 12.0 beta 2, updated from NC 11.0.3
Where did you install Nextcloud from: NC updater app (beta channel)
Signing status: "No errors have been found."

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.2
  - checksum: 0.3.4
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - groupfolders: 1.0.2
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - notifications: 2.0.0
  - ownbackup: 17.3.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - survey_client
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto,90",
        "versions_retention_obligation": "90,auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/mydomain.de\/cloud",
        "dbtype": "mysql",
        "version": "12.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "mydomain.de",
        "defaultapp": "calendar",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.release.channel": "beta"
    }
}

**Are you using external storage:** no
**Are you using encryption:** no
**Are you using an external user-backend:** no

### Client configuration
**Browser:** Firefox 53.0
**Operating system:** Linux Mint 18.1

#### Web server ACCESS log
127.0.0.1 - - [12/May/2017:00:22:15 +0200] "GET /cloud/index.php/settings/admin/additional HTTP/1.1" 500 9689 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:15 +0200] "GET /cloud/index.php/css/core/styles.css?v=cc7c9d2bd759cd2152537075a603e13d-7 HTTP/1.1" 304 442 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:15 +0200] "GET /cloud/index.php/css/core/header.css?v=cc7c9d2bd759cd2152537075a603e13d-7 HTTP/1.1" 304 442 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:16 +0200] "GET /cloud/index.php/settings/admin/undefined/img/notifications.svg HTTP/1.1" 302 1061 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:16 +0200] "GET /cloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 821 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:16 +0200] "GET /cloud/index.php/settings/admin/undefined/img/notifications.svg HTTP/1.1" 302 1061 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:16 +0200] "GET /cloud/index.php/apps/calendar/ HTTP/1.1" 200 13309 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:19 +0200] "GET /cloud/index.php/settings/admin HTTP/1.1" 200 7666 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:20 +0200] "GET /cloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 821 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:20 +0200] "GET /cloud/index.php/heartbeat HTTP/1.1" 200 1119 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
127.0.0.1 - - [12/May/2017:00:22:20 +0200] "PROPFIND /cloud/remote.php/webdav HTTP/1.1" 207 4794 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"

#### Web server ERROR log
(nothing)

#### Nextcloud log (data/nextcloud.log)
{"reqId":"fExaRLxkFFKuytbhiMcQ","level":3,"time":"2017-05-12T00:25:17+02:00","remoteAddr":"127.0.0.1","user":"user.name","app":"index","method":"GET","url":"\/cloud\/index.php\/settings\/admin\/additional","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve AppName! Class AppName does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('AppName')\\n#1 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AppName')\\n#2 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(66): OC\\\\ServerContainer->query('AppName')\\n#3 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(96): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->buildClass(Object(ReflectionClass))\\n#4 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\OwnBackup\\\\\\\\C...')\\n#5 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/ServerContainer.php(116): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\OwnBackup\\\\\\\\C...')\\n#6 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(410): OC\\\\ServerContainer->query('\\\\\\\\OCA\\\\\\\\OwnBackup\\\\\\\\...')\\n#7 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/apps\\\/ownbackup\\\/admin.php(19): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('\\\\\\\\OCA\\\\\\\\OwnBackup\\\\\\\\...')\\n#8 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/legacy\\\/app.php(727): include('\\\/server\\\/www\\\/dat...')\\n#9 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(102): OC_App::getForms('admin')\\n#10 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(93): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getLegacyForms()\\n#11 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(73): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getSettings('additional')\\n#12 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('additional')\\n#13 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#14 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#15 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#16 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('AdminSettingsCo...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#17 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#18 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#19 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/base.php(975): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin...')\\n#20 \\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/index.php(40): OC::handleRequest()\\n#21 {main}\",\"File\":\"\\\/server\\\/www\\\/mydomain.de\\\/htdocs\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":102}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko\/20100101 Firefox\/53.0","version":"12.0.0.18"}

#### Browser log
Omitted since it cannot be a client issue.

**Comment by LukasReschke** [comment] 2017-05-11 22:37
As per your stacktrace this is caused by the ownBackup app. This should be fixed thus once https://github.com/pbek/ownbackup/issues/17 is released.

**Closed by LukasReschke** 2017-05-11 22:37 UTC
