### ISSUE TITLE
Error 404 for CalDAV in Evolution on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by marbetschar** [nextcloud/server#20732] opened 2020-04-29 19:47 UTC
The Synchronization of Calendar Events and Tasks stopped working in Evolution on Ubuntu 18.04 LTS - this used to work a few weeks ago.

### Software used

- Ubuntu `18.04 LTS`
- Evolution `3.28.5-0ubuntu0.18.04.2`
- Nextcloud `18.0.4.2`
- 2FA Enabled

### Steps to reproduce

1. Download Ubuntu 18.04 LTS iso image: http://releases.ubuntu.com/18.04/
2. Create bootable drive and boot from it
3. Execute `sudo add-apt-repository universe && sudo apt update && sudo apt install evolution` in Terminal
4. Start Evolution
5. Add a new "Collection Account" entering your Username and Nextcloud server URL
6. Enter your password when requested
7. Once the account is added, disable and re-enable it
8. Evolution throws a 404 error for each task list and calendar (see screenshot below)

![Evolution 404 in Ubuntu 18.04 LTS for Nextcloud Backend](https://user-images.githubusercontent.com/392542/80639154-e401b780-8a61-11ea-83a5-633568498234.png)

**Comment by kesselb** [comment] 2020-04-29 20:21
Duplicate of #20624. Fix is already confirmed for next release.

**Closed** 2020-04-29 20:24 UTC
Labels: 0. Needs triage, 18-feedback, bug, feature: dav
