### ISSUE TITLE
Trashbin: cannot permanently delete files with partial unselection

### ISSUE THREAD

**Issue by skimpax** [nextcloud/server#5579] opened 2017-07-01 10:18 UTC
### Steps to reproduce
1. create at least 2 files
2. delete these files
3. go in trashbin
4. click select all button to select these deleted files
5. unclick (unselect) one of these files at least (but not all!)
6. click Delete to definitely delete all the selected files

### Expected behaviour
All the selected files should be deleted.

### Actual behaviour
None of the files are deleted.

### Server configuration

**Operating system**: Linux (Debian 9 Stretch)

**Web server:** nginx 1.10.3

**Database:** MariaDB 10.1.23

**PHP version:** 7.0.19

**Nextcloud version:** Nextcloud 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** manual install

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by MorrisJobke** [comment] 2017-08-30 10:02
JS console error

```
 TypeError: Cannot read property 'attr' of null
    at FileList._removeCallback (filelist.js:152)
    at Object.success (filelist.js:248)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

maybe somebody from @nextcloud/javascript want to look into this. cc @danxuliu

**Comment by Peac** [comment] 2018-03-22 11:50
Any chance this will get fixed? It's pretty annoying to delete a lot of files from the recycle bin if there are some I don't want to delete.

**Comment by supermanlinux** [comment] 2018-04-12 00:52
@MorrisJobke @skjnldsv
 Similarly:
1.Have files in the trashbin
2.Use the top checkbox to "select all"
3.Uncheck some individual file(s)
4.**Click "Restore"** to try and restore all the files that are still selected.
Error dialog pops up with **Couldn't restore**

**Comment by michag86** [comment] 2018-08-22 12:03
Details for undelete request:
Parameters:
```
dir: /
files: ["test1.pdf","test2.pdf"]
```
Response:
```
{"data":{"message":"Couldn't restore ","success":[],"error":["",""]},"status":"error"}
```

### Workaround
Select the two files instead of select all and unselect.
Details for undelete request:
Parameters:
```
dir: /
files: ["test1.pdf.d1534933006","test2.pdf.d1534933007"]
```
Response:
```
{"data":{"success":[{"filename":"test1.pdf.d1534933006","timestamp":"1534933006"},{"filename":"test2.pdf.d1534933007","timestamp":"1534933007"}]},"status":"success"}
```

**Comment by MorrisJobke** [comment] 2018-08-22 14:11
@skjnldsv @danxuliu Any idea?

**Comment by szaimen** [comment] 2021-05-20 09:33
I couldn't reproduce this on c.nc.com hence closing.

**Closed by szaimen** 2021-05-20 09:33 UTC
Labels: 1. to develop, bug, feature: trashbin
