### ISSUE TITLE
Share links not working from SMB storage

### ISSUE THREAD

**Issue by chrisbeardy** [nextcloud/server#4673] opened 2017-05-03 12:30 UTC
When issuing a share link from a file or folder that is located on a SMB external storage, a user is presented with the following error message when following the link:

File not found
The specified document has not been found on the server.
You can click here to return to Nextcloud.

The error only occurs when sharing a file located on SMB storage, share link can be created if the file is located locally on server.

### Steps to reproduce
1. Share a file that is located on a SMB share using 'Share Link'. 
2. Follow link and enter password if required
3.See error message

### Expected behaviour
When following link, should see page to download file.

### Actual behaviour
Error Message 

File not found
The specified document has not been found on the server.
You can click here to return to Nextcloud.

### Server configuration

**Operating system**:
Ubuntu VM

**Nextcloud version:** (see Nextcloud admin page)
11

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
techandme VM

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
NO

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win 10

**Comment by MorrisJobke** [comment] 2017-05-03 14:40
@chrisbeardy How is the SMB storage mounted?

**Comment by chrisbeardy** [comment] 2017-05-03 15:16
I used the browser to add the storage as the picture below. 

![image](https://cloud.githubusercontent.com/assets/20585410/25667458/6f2ecd9c-301b-11e7-935b-d731d1d5703b.png)

It appears in the files as seen below
![image](https://cloud.githubusercontent.com/assets/20585410/25667559/c2932460-301b-11e7-89fc-051c6fcee2ca.png)

Is this what you meant?

**Comment by MorrisJobke** [comment] 2017-05-03 15:21
> Is this what you meant?

Yes. Just wanted to be sure, that the username and password is actually configured and not the sessions username and password feature is used (because then the above behaviour would be the only possible).


@icewind1991 @schiessle @rullzer Ideas?

**Comment by github-tomster** [comment] 2017-05-05 16:58
unfortunately i have to confirm this error on my setup.
smb share to a folder not the root of a drive. i have seen that issue.
i jumped on the nextcloud train with a fresh install fro techandme.se
before i had an owncloud 8 with the very same share and no issues like this. :-(

**Comment by MorrisJobke** [comment] 2017-05-17 02:55
cc @schiessle @rullzer @icewind1991 sharing issue with external storage, any idea?

**Comment by MorrisJobke** [comment] 2017-05-17 02:55
@chrisbeardy @github-tomster Do you have any chance to test the Nextcloud 12 beta 3 for this issue?

**Comment by rullzer** [comment] 2017-05-17 11:24
Let me see if this happens for me as well

**Comment by rullzer** [comment] 2017-05-17 11:40
Doesn't happen for me...
@chrisbeardy do you logs show anything?

**Comment by chrisbeardy** [comment] 2017-05-17 21:06
I attempted again to share a link from SMB and can still see the problem, after generating the link and then trying to access it, the log does not register any event after the error.

I have practical work around at minute, involving copying the file to a location not stored on SMB but this is not ideal. 

Still on V11, trying 12 beta 3 as developer is not a good idea for me, I am not able to get involved with this really, not my programming area. (I know that does not seem helpful).

**Comment by github-tomster** [comment] 2017-05-22 10:31
actually it is not possible to reproduce the error: 'storage not available' or 'File not found'.
though the machine NC is installed on had several updates the last days.
among these updates there was: apache2-data:amd64 (2.4.18-2ubuntu3.1, 2.4.18-2ubuntu3.2)
maybe that was relevant?

**Comment by github-tomster** [comment] 2017-05-24 10:08
ok. as right now i tried again.
and it seems more than strange i try to describe
logged in with admin accound,
checked the external smb storage
it states green so i guess it is mounted correctly.
calling the share-link
site builds up and says: file not found.
went back on the admin-login to check the file.
calling files home,
clicking the name of the external storage
an it tells me i dont have permission to upload files here.
since i just clicked the folder i expected to see the content. confusing.
right after that i checked the logs,
guess what: no entry!
checking the apache2 log just reveals a 404

on the machine holding the share i can see an successful security eventlog entry.

refreshing the browser-window with the admin login leads to
correct acces to the files again. and refreshing the link window
on the testing remote machine accessing the shared link can access it now.

**Comment by github-tomster** [comment] 2017-05-26 08:38
ok, here i am again.
i have found: https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/smb.html
there it states:
`The SMB/CIFS backend requires smbclient or the PHP smbclient module to be installed on the Nextcloud server. The PHP smbclient module is preferred, but either will work. These should be included in any Linux distribution. (See PECL smbclient if your distro does not include them.)`
to me this reads either smbclient OR and not AND php-smbclient-module.
on the machine was no smbclient package installed. now it is.
as expected the errors: `"Can't find smbclient binary in path\"` are gone now.
i will report back if the shares are always available from now on.

**Comment by github-tomster** [comment] 2017-05-27 10:06
well not working here on my setup!

what i did:
shared a folder yesterday.
went on a remote machine
inserted the link
entered the password
see the folder
marked one file (6.2GB)
klicked 'download'
waiting for data
save as window pops up showing 5kb file download
i clicked ok anyways
i am being presentet the error: file not found!
F5 no help
Ctrl+F5 also no help
here is the syslog:
`May 27 11:23:03 nc pound: 10.0.0.1 GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.248 sec
May 27 11:23:07 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V/authenticate HTTP/1.1 - HTTP/1.1 303 See Other (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.091 sec
May 27 11:23:07 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V HTTP/1.1 - HTTP/1.1 404 Not Found (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.133 sec
May 27 11:23:08 nc pound: 212.xxx.xxx.xxx GET /core/js/oc.js?v=c6d086c7d5535b358d2b0f6646de27eb HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.074 sec
May 27 11:23:09 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V/authenticate HTTP/1.1 - HTTP/1.1 303 See Other (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.100 sec
May 27 11:23:10 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V HTTP/1.1 - HTTP/1.1 404 Not Found (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.124 sec
May 27 11:23:10 nc pound: 212.xxx.xxx.xxx GET /core/js/oc.js?v=c6d086c7d5535b358d2b0f6646de27eb HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.073 sec
May 27 11:23:11 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V/authenticate HTTP/1.1 - HTTP/1.1 303 See Other (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.091 sec
May 27 11:23:11 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V HTTP/1.1 - HTTP/1.1 404 Not Found (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.144 sec
May 27 11:23:11 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V/authenticate HTTP/1.1 - HTTP/1.1 303 See Other (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.101 sec
May 27 11:23:11 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V HTTP/1.1 - HTTP/1.1 404 Not Found (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.103 sec
May 27 11:23:11 nc pound: 212.xxx.xxx.xxx GET /core/js/oc.js?v=c6d086c7d5535b358d2b0f6646de27eb HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.071 sec
May 27 11:23:14 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V HTTP/1.1 - HTTP/1.1 404 Not Found (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.138 sec
May 27 11:23:14 nc pound: 212.xxx.xxx.xxx GET /core/vendor/select2/select2.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.003 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /apps/files_pdfviewer/css/style.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/css/jquery-ui-fixes.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /apps/files_versions/css/versions.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.003 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.004 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /apps/files_videoplayer/css/style.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.006 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/css/jquery.ocdialog.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/search/js/search.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.003 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /css/core/server.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.130 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/js/oc.js?v=c6d086c7d5535b358d2b0f6646de27eb HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.122 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/vendor/core.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.166 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /apps/files_pdfviewer/js/previewplugin.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /apps/files_videoplayer/js/viewer.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.011 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/js/jquery-ui-fixes.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /js/core/merged-template-prepend.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.253 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /css/core/share.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.307 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/js/files/fileinfo.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/js/files/client.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /js/core/merged-share-backend.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.284 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/js/contactsmenu.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /apps/theming/styles?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.067 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /apps/theming/js/theming?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.089 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/fonts/OpenSans-Regular.woff HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/fonts/OpenSans-Semibold.woff HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.027 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/img/logo.svg?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:15 nc pound: 212.xxx.xxx.xxx GET /core/img/background.jpg?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.099 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V HTTP/1.1 - HTTP/1.1 303 See Other (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.107 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V/authenticate HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.100 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/vendor/select2/select2.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /apps/files_pdfviewer/css/style.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/vendor/jquery-ui/themes/base/jquery-ui.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/css/jquery-ui-fixes.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.003 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /apps/files_versions/css/versions.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /apps/files_videoplayer/css/style.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/css/jquery.ocdialog.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /apps/files_sharing/css/authenticate.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/search/js/search.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /css/core/server.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.112 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /apps/files_pdfviewer/js/previewplugin.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /css/core/share.css?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.157 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /apps/files_videoplayer/js/viewer.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/js/jquery-ui-fixes.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/js/files/fileinfo.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:28 nc pound: 212.xxx.xxx.xxx GET /core/js/files/client.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/js/contactsmenu.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /apps/files_sharing/js/authenticate.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /js/core/merged-template-prepend.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.193 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/img/favicon.ico HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /js/core/merged-share-backend.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.213 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/js/oc.js?v=c6d086c7d5535b358d2b0f6646de27eb HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.325 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /apps/theming/styles?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.145 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /apps/theming/js/theming?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.172 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/vendor/core.js?v=c6d086c7d5535b358d2b0f6646de27eb-4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.506 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/fonts/OpenSans-Regular.woff HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.003 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/img/logo.svg?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.002 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/img/actions/confirm.svg?v=2 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.001 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/fonts/OpenSans-Light.woff HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.056 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/img/background.jpg?v=4 HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.076 sec
May 27 11:23:29 nc pound: 212.xxx.xxx.xxx GET /core/fonts/OpenSans-Semibold.woff HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.147 sec
May 27 11:23:33 nc pound: 10.0.0.1 GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.105 sec
May 27 11:23:39 nc pound: 212.xxx.xxx.xxx POST /s/8CPRpRGS0se5o2V/authenticate HTTP/1.1 - HTTP/1.1 303 See Other (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.374 sec
May 27 11:23:39 nc pound: 212.xxx.xxx.xxx GET /s/8CPRpRGS0se5o2V HTTP/1.1 - HTTP/1.1 404 Not Found (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.099 sec
May 27 11:23:39 nc pound: 212.xxx.xxx.xxx GET /core/js/oc.js?v=c6d086c7d5535b358d2b0f6646de27eb HTTP/1.1 - HTTP/1.1 200 OK (mynextcloud.domain/nextCloud -> 127.0.0.1:80) 0.072 sec
`

that is the nextcloud.log
`{"reqId":"kJQKoYJMss6r2DDonpBW","level":3,"time":"2017-05-27T09:21:49+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"\/s\/8CPRpRGS0se5o2V\/download?path=%2F&files=file.datv&downloadStartSecret=0nhjorl4x7f","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"\\\/_SMBSHARE\\\/file.dat\",\"Code\":110,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(294): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->fopen('_SMBSHARE\\\/file.dat', 'r')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(318): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('_SMBSHARE\\\/file.dat', 'r')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(294): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('_SMBSHARE\\\/file.dat', 'r')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_accesscontrol\\\/lib\\\/StorageWrapper.php(308): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('_SMBSHARE\\\/file.dat', 'r')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1130): OCA\\\\FilesAccessControl\\\\StorageWrapper->fopen('_SMBSHARE\\\/file.dat', 'r')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(971): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/_SMBSHARE\\\/file.dat', Array, 'r')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(432): OC\\\\Files\\\\View->fopen('\\\/_SMBSHARE\\\/file.dat', 'r')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(308): OC\\\\Files\\\\View->readfile('\\\/_SMBSHARE\\\/file.dat')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(120): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/_SMBSHARE\\\/file.dat', 'file.dat', Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php(530): OC_Files::get('\\\/_SMBSHARE\\\/file.dat', 'file.dat', Array)\\n#10 [internal function]: OCA\\\\Files_Sharing\\\\Controller\\\\ShareController->downloadShare('8CPRpRGS0se5o2V', 'file.dat', '\\\/', '0nhjorl4x7f')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controller\\\\ShareController), 'downloadShare')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/App.php(136): OC\\\\AppFramework\\\\App::main('ShareController', 'downloadShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#15 \\\/var\\\/www\\\/nextcloud\\\/core\\\/routes.php(129): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'downloadShare')\\n#16 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/s\\\/8CPRpRGS0se5...')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php\",\"Line\":359}","userAgent":"Mozilla\/5.0","version":"12.0.0.29"}
`
what logs would be helpful also?

**Comment by chrisbeardy** [comment] 2017-11-15 15:12
Update to this, been a while, I seem to be able to share now but I too get a lot of php errors constantly forming:

fread(): \Icewind\SMB\NativeStream::stream_read - read -8193 bytes more data than requested (-1 read, 8192 max) - excess data will be lost at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#83

**Comment by skjnldsv** [comment] 2019-06-06 16:35
> Update to this, been a while, I seem to be able to share now but I too get a lot of php errors constantly forming:

It's been a bigger while now, do you still have those errors? :)

**Comment by chrisbeardy** [comment] 2019-06-06 20:53
> It's been a bigger while now, do you still have those errors? :)

This problem seems have disappeared for me, I'm now working on Nextcloud 15 upgraded after installing a techandme.se VM. Currently **touches wood** flawless NC install...

**Comment by kesselb** [comment] 2019-06-06 21:09
Thanks for your feedback :+1:

**Closed by kesselb** 2019-06-06 21:09 UTC
Labels: 0. Needs triage, bug, feature: external storage, feature: sharing, needs info
