### ISSUE TITLE
List of incompatible user agents opted out from Same Site Cookie Protection.

### ISSUE THREAD

**Issue by staler** [nextcloud/server#14104] opened 2019-02-08 00:29 UTC
what is the right way to opt-out safari browsers on ios devices?
i can't find a list or information how to do that.

reason i want this is because i get a error in safari on macbook with too many redirects

**Comment by MorrisJobke** [comment] 2019-02-26 13:48
Looks like a duplicate of #14017 which is AFAIK fixed in 15.0.4

**Closed by MorrisJobke** 2019-02-26 13:48 UTC
