### ISSUE TITLE
Occ files:scan --all works but --unscanned doesn't

### ISSUE THREAD

**Issue by henriquebs12** [nextcloud/server#21886] opened 2020-07-17 04:40 UTC
Why the occ `files:scan --unscanned` command doesn't work for external drives and `files:scan --all` does? It turns out to be impossible to run a cron to always rescan the whole folder, considering me or one that has terabytes of files. Isn't there any alternatives to scan only new files in mounted drives? 

I love using rclone syncing the data folder but this really breaks the deal.

When trying to scan only new files I always get 0 new files:

```
Starting scan for user 1 out of 1 (user)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
```
I really consider it a bug since the `scan --all` works.

**Comment by wiswedel** [comment] 2020-10-07 07:37
confirmed for NC 20

**Comment by wiswedel** [comment] 2020-10-07 07:37
cc @nextcloud/server-triage

**Comment by MorrisJobke** [comment] 2020-10-07 11:23
cc @icewind1991

**Comment by szaimen** [comment] 2020-10-07 17:10
As far as I understand it: the --unscanned flag cannot work as long as no folder was marked as unscanned. And it can only automatically be marked as unscanned if you are running the files_external:notify command in the background to detect externally changed files/folders.

**Comment by henriquebs12** [comment] 2020-10-07 18:31
@szaimen should `files_external:notify` be run only once? How to keep it always running? Is it safe to run 2 `files:scan --unscanned` commands at the same time?

I'm thinking about running the command once per minute, and sometimes it will run fast  and sometimes it will still be reading for news files when the next command is run. Is there any possibility of corrupting anything?

**Comment by szaimen** [comment] 2020-10-07 18:35
> should `files_external:notify` be run only once?

No, this has to run for everyexternal_storage mount continuosly in the background

**Comment by szaimen** [comment] 2020-10-07 18:37
BTW: if you are using local external storage, please have a look at this:
https://github.com/icewind1991/files_inotify#usage
(there are instructions how to configure your instance to make use of that.)

**Comment by henriquebs12** [comment] 2020-10-07 22:04
> >  you need a working background job like cron configured. Otherwise it won't work.

Thanks for the reply. What frequency exactly does this command need to be run in the cron? Every second? I didn't find that information.

**Comment by szaimen** [comment] 2020-10-07 22:10
> Thanks for the reply. What frequency exactly does this command need to be run in the cron? Every second? I didn't find that information.

Which one? cronjobs? I am refering to normal nextcloud cronjobs: there is a build-in feature to automatically scan all unscanned files without having to execute an extra cronjob with the `files:scan --unscanned` command. But as I said: you need to have the files_external:notify command configured to run in the background. (it just starts one time and doesn't exit; so you need to start it after the boot process.)

**Comment by DaniloMussolini** [comment] 2021-03-11 15:44
Looks like files_external:notify doesn't support Local storage anymore, despite we have it mentioned in this [link](https://github.com/icewind1991/files_inotify).

**Comment by sanfx** [comment] 2021-08-22 19:46
This is broken in version 21.0.4  as well

**Comment by szaimen** [comment] 2023-01-23 10:04
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:41 UTC
Labels: bug, needs info, feature: filesystem, 0. Needs triage
