### ISSUE TITLE
[19 beta 2] Video sharing not working correctly

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#20435] opened 2020-04-11 11:34 UTC
Take for example sharing a video directly. Works fine. But if you share the entire directory and try loading a video it gets stuck in a indefinite loading loop.

Direct:

<img width="803" alt="firefox_MAd33TFHLH" src="https://user-images.githubusercontent.com/7935624/79042558-a241c780-7bad-11ea-93d1-c49d1fb421fa.png">

Shared folder:

<img width="706" alt="firefox_ZoI19G3fZF" src="https://user-images.githubusercontent.com/7935624/79042564-af5eb680-7bad-11ea-9193-084665d0764b.png">

Note that while there are errors I don't see anything specifically related to this. If you can't replicate this let me know and I will try to hunt for the specific error.

**Configuration:**
19 beta 2
Primary S3 multibucket storage | path style false
Debian 10
PHP 7.4-FPM
HAProxy + Nginx
Postgresql

**Comment by liamjack** [comment] 2020-04-13 14:01
Hi @Dragon988 
I'm unable to reproduce the problem on my end, my Nextcloud instance doesn't show a video preview in the interface, the only available option is to download the file (tried with MP4 and WEBM and multiple browsers):

![preview](https://user-images.githubusercontent.com/821228/79126262-2606da00-7d8f-11ea-88ec-7036ce38a707.png)

Are you using a specific plugin to display the video inside Nextcloud ?

**Comment by Dragon988** [comment] 2020-04-13 22:02
No, there is no specific plugin. Sometimes videos work and sometimes they don't. Depends on how they were encoded.

Attached is the working video file on my end (rename the .jpeg to mp4)

![2017-01-02_21-57-52](https://user-images.githubusercontent.com/7935624/79165365-d4af1880-7d97-11ea-8d21-169453842dc7.jpeg)

**Comment by Dragon988** [comment] 2020-04-13 22:04
Additionally even HEVC videos work properly on mobile devices and the edge browser (with hevc installed from windows store).

**Comment by Dragon988** [comment] 2020-04-14 01:22
Also if you haven't already @liamjack make sure you have your previews configured to allow videos. I'm not sure how relevant that is to this instance but it's possible it won't work without it. I'm also not sure if ffmpeg (which needs to be installed) generates an actual video or just the thumbnail.
`
OC\\Preview\\Movie`

**Comment by szaimen** [comment] 2021-05-31 12:27
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 12:27 UTC
Labels: 0. Needs triage, bug
