### ISSUE TITLE
css margin-left: 300px; Nextcloud 14 Feedback

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#11189] opened 2018-09-12 11:12 UTC
Hi,

i have download the Orginal Pack Nextcloud14 from nextcloud.com and have a feedback
to the css-design.

by customizing the nextcloud via css with my own theme, have i found this line : 

at
https://www.blackysgate.net/nextcloud/index.php/css/core/3eb1-1e76-server.css?v=d41d8cd98f00b204e9800998ecf8427e?v=8a57058b

so
```
#app-navigation:not(.hidden) + #app-content {
    margin-left: 300px;
}
```
![screen 00003](https://user-images.githubusercontent.com/7925717/45421152-80f4be80-b68c-11e8-8d9b-d2b2f0c3d7e3.jpg)

i have it not added on my custom css
and can it only fixing by me,
but you know where it is in the code, the Size must be 250px and not 300px .
there was goes something wrong in the github code setting up..

[you can download the theme what i have make ](http://www.blackysgate.de/files/folder-root/nextcloud/)
neXtrealTime-v1-NC14 2018-09-12 13-08-03.zip 
appnavbuttons.css line 1

edit: uppss, i have see to be a change by the loading and 
the "normal" standarttheme have/need the 300px, so i guess, no bug ..

best regards
Blacky

**Comment by danielkesselberg** [comment] 2018-09-12 12:00
I guess its safe to close this issue since @blackcrack wrote that its not a bug.

**Closed by danielkesselberg** 2018-09-12 12:00 UTC
Labels: design

**Comment by MariusBluem** [comment] 2018-09-12 12:03
As this seems to be a setup issue I would like to ask you to raise your question in the forums: [https://help.nextcloud.com](https://help.nextcloud.com)

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at [https://nextcloud.com/enterprise/](https://nextcloud.com/enterprise/)

**Comment by blackcrack** [comment] 2018-09-12 16:03
Thank you Marius :+1:
