### ISSUE TITLE
the three dots file and folder sharing not managed well in the mobile version.

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#17629] opened 2019-10-21 21:05 UTC
In the mobile version of nextcloud the three balls for managing file and folder sharing are hidden by the wording of the internal capacity.  as per attachment, this when the folder is shared.

![Screenshot_20191021-230018](https://user-images.githubusercontent.com/35575744/67243181-4ba5cd00-f457-11e9-8cbc-9b1067b04add.png)

**Comment by ToughLama** [comment] 2019-10-22 01:43
me too

**Comment by wiswedel** [comment] 2019-10-22 04:26
@nextcloud/designers 
confirmed with 17.0.0
not happening on 16.0.5

**Comment by wiswedel** [comment] 2019-10-22 04:27
@tigernero79 Thanks for reporting. Please make sure however to include some more server info - at least the version number - with any issue.
Thx.

**Comment by tigernero79** [comment] 2019-10-22 05:37
I apologize for not having entered it, the problem is on nextcloud 17.0.0 and I don't know if the problem reported here is in common with this.  not being url-centered in the application, on s10 maybe because of the HD resolution?  

"Https://github.com/nextcloud/android/issues/4437"

**Comment by juliushaertl** [comment] 2019-10-22 07:01
duplicate of #17364

Fix is in https://github.com/nextcloud/server/pull/17469

**Closed by juliushaertl** 2019-10-22 07:01 UTC
Labels: 0. Needs triage, 17-feedback, bug, design
