### ISSUE TITLE
Slow file upload with HTTP/2

### ISSUE THREAD

**Issue by ZWC-father** [nextcloud/server#30464] opened 2022-01-02 05:26 UTC
Slow file upload when I enable HTTP/2.

Only 2 mb/s,
When I disable http/2, it will be much faster than before (25mb/s).
It seems that many people face the same problem. 
Both apache and nginx are very slow with http/2.
I have tried NC19 , NC22 and NC23, but it makes no changes at all.

Operating system: Ubuntu20.04
Web server: Nginx1.21.5 or apache 2.4.43
Database: mysql8.0
PHP version: php7.4.3 with opcache and APCu
Nextcloud version: 23.0.0
Updated from an older Nextcloud/ownCloud or fresh install: fresh install

Nginx configuration:

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name cloud.example.com;

    ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    client_max_body_size 10240M;
    client_body_timeout 3600s;
    fastcgi_buffers 64 4K;
  
    ......

**Comment by acsfer** [comment] 2022-01-02 15:06
Duplicate of https://github.com/nextcloud/server/issues/25297

**Closed by acsfer** 2022-01-02 15:06 UTC
Labels: bug, 0. Needs triage
