### ISSUE TITLE
open, don't just display the file linked with a file ID

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#4378] opened 2017-04-18 17:31 UTC
I believe [this commit](https://github.com/nextcloud/server/commit/093e9dd4225e6681140523c75bfc20809cd6d651) adds that when a file ID is part of the URL, the Files app scrolls to the file, wherever it is.

It'd be great if it would open the file right away, if it is open-able ;-)

So you would share such a link to a doc or odt file and it would open right away rather than still requiring a click. But when you link to, say, a zip file it doesn't download it but just display. There's a check in the API for that, if I understood @LukasReschke correctly, 

@nextcloud/designers what do you think, makes sense? Also, I think this is relatively easy to do, retracing the steps that implemented the scroll-to, so I'll make it a starter issue... :ballot_box_with_check:

**Comment by MorrisJobke** [comment] 2017-04-26 02:02
Duplicate of #1467

**Closed by MorrisJobke** 2017-04-26 02:02 UTC
Labels: feature: files, help wanted, papercut, starter issue
