### ISSUE TITLE
[Bug]: Calendar Subscriptions not shown in calendar view.

### ISSUE THREAD

**Issue by tobias-groeger** [nextcloud/server#42257] opened 2023-12-14 04:10 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I am adding a calendar subscription (custom link or public holidays, doesn't matter) no events from the calendar are shown.
Using a client like ICSx5 on a phone works properly.

The internal calendar works as expected and also syncs properly to devices.

The calendar also syncs properly to the internal database.
I checked the `oc_calendarobjects` table and I can find all the events from the subscribed calendar with a `calendartype` of `1`, as expected.

Now when I access my calendar view of the nextcloud instance the calendars are obtained by making `REPORT` calls to `/remote.php/dav/calendars/<user>/<calendar>/`.
This returns the proper calendar data for all internal calendars but **not** for subscribed calendars, even though the events are present in the database.

As far as I could gather the query is executed with `calendarType` set to `0` when making these requests unrelated to whether the calendar is actually internal or a subscription.

### Steps to reproduce

1. Add a new calendar subscription
2. Wait until new calendar was synced
3. No events from the new calendar are shown

### Expected behavior

The events are shown properly.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "htaccess.RewriteBase": "\/",
        "maintenance_window_start": 1,
        "loglevel": 0
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - calendar: 4.6.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by tobias-groeger** [comment] 2023-12-15 13:29
I did some more digging into why the cached events are not properly returned.

I found that this `if` [CalendarHome.php:186](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalendarHome.php#L186) does not execute (so `$this->returnCachedSubscriptions` is `false`) for a subscribed calendar and a regular (e.g. not `Cached`) `Subscription` is returned from this function call.
But sometimes `enableCachedSubscriptionsForThisRequest` was called on a `CalendarHome` after `getChild` was called and already returned a regular `Subscription` instead of a `CachedSubscription` so this might be a problem?.

When forcing the return of a `CachedSubscription` (so basically commenting out the `if`) I was able to display the events of a subscribed calendar but was no longer able to enable/disable the calendar from being shown.


As subscribed calendars are quite important to me and I wasn't able to debug this issue any further I reinstalled my nextcloud instance to version `27.1.4`. Subscribed calendars are now working for me again.
I also did a clean install of version `28.0.0` before trying the older version but had the same problem which leads me to believe that this is a new problem of version `28.0.0`.

**Comment by saschabrockel** [comment] 2023-12-18 02:01
Same here after updating from 27.1.4 to 28.0.0. But I'm wondering that @tobias-groeger said you reinstalled to 27.1.4. I thought downgrading it not possible?

**Comment by tobias-groeger** [comment] 2023-12-18 12:23
> Same here after updating from 27.1.4 to 28.0.0. But I'm wondering that @tobias-groeger said you reinstalled to 27.1.4. I thought downgrading it not possible?

I didn't downgrade but did a full reinstall of the older version. As I was just setting up a new instance it wasn't a big problem for me.

**Comment by tobias-groeger** [comment] 2023-12-18 12:29
> Duplicate of #42143 ?

Yes it seems that is the same problem and they came to a similar conclusion [here](https://github.com/nextcloud/server/issues/42143#issuecomment-1854226605) that the `CalendarHome` is not aware of the caching support when the subscription is returned.

**Comment by miaulalala** [comment] 2023-12-18 14:29
Duplicate of https://github.com/nextcloud/server/issues/42143

**Closed by miaulalala** 2023-12-18 14:29 UTC
Labels: bug, 0. Needs triage, 28-feedback

**Comment by Juergen-Vollmer** [comment] 2023-12-18 16:37
I removed that "if" in line 186  and leave only the 
   return new CachedSubscription($this->caldavBackend, $subscription);
statement.
The subscribed calender is shown again!
Ok - it seems that the it is not possible to hide again it and the color can not be changend, but the calender ist shown
( nextcloud 28.0.1 RC1). 
The problem occured when I upgraded to 28.0 (-> https://github.com/nextcloud/server/issues/42143)

**Merci** for that first "fix", the display of subbscribed calendars is essential for my working set up!
Hopefully the problem ist fixed soon in the right way.

Jürgen

**Comment by miaulalala** [comment] 2023-12-18 19:16
> I did some more digging into why the cached events are not properly returned.
> 
> I found that this `if` [CalendarHome.php:186](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalendarHome.php?rgh-link-date=2023-12-15T13%3A29%3A20Z#L186) does not execute (so `$this->returnCachedSubscriptions` is `false`) for a subscribed calendar and a regular (e.g. not `Cached`) `Subscription` is returned from this function call. But sometimes `enableCachedSubscriptionsForThisRequest` was called on a `CalendarHome` after `getChild` was called and already returned a regular `Subscription` instead of a `CachedSubscription` so this might be a problem?.
> 
> When forcing the return of a `CachedSubscription` (so basically commenting out the `if`) I was able to display the events of a subscribed calendar but was no longer able to enable/disable the calendar from being shown.
> 
> As subscribed calendars are quite important to me and I wasn't able to debug this issue any further I reinstalled my nextcloud instance to version `27.1.4`. Subscribed calendars are now working for me again. I also did a clean install of version `28.0.0` before trying the older version but had the same problem which leads me to believe that this is a new problem of version `28.0.0`.

Thanks for digging into this, I came to the same conclusion.

The WebCal plugin isn't loaded properly at time of fetching the subtree.

I think we can get rid of the Dav Subscription class and use the CachedSubscription class everywhere as I don't see the purpose of using it - we always cache the calendars.

**Comment by tcitworld** [comment] 2023-12-25 08:54
> I think we can get rid of the Dav Subscription class and use the CachedSubscription class everywhere as I don't see the purpose of using it - we always cache the calendars.

Nope, only for the Calendar app (`X-NC-CalDAV-Webcal-Caching`) and a few allow-listed user-agents (`ENABLE_FOR_CLIENTS`).

**Comment by Dragonzfire** [comment] 2024-01-13 22:22
Any update on a resolution for this issue? I commented out the if statement as mentioned. That does however break renaming, showing, etc for all subscribed cal.

**Comment by ebagnaschi** [comment] 2024-01-16 09:04
> I did some more digging into why the cached events are not properly returned.
> 
> I found that this `if` [CalendarHome.php:186](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalendarHome.php#L186) does not execute (so `$this->returnCachedSubscriptions` is `false`) for a subscribed calendar and a regular (e.g. not `Cached`) `Subscription` is returned from this function call. But sometimes `enableCachedSubscriptionsForThisRequest` was called on a `CalendarHome` after `getChild` was called and already returned a regular `Subscription` instead of a `CachedSubscription` so this might be a problem?.
> 
> When forcing the return of a `CachedSubscription` (so basically commenting out the `if`) I was able to display the events of a subscribed calendar but was no longer able to enable/disable the calendar from being shown.
> 
> As subscribed calendars are quite important to me and I wasn't able to debug this issue any further I reinstalled my nextcloud instance to version `27.1.4`. Subscribed calendars are now working for me again. I also did a clean install of version `28.0.0` before trying the older version but had the same problem which leads me to believe that this is a new problem of version `28.0.0`.

Another side effect of this (temporary) fix is that I am noticing now is that I can not "discover" the calendars anymore using a remote client (vdirsyncer in my case).

**Comment by Keeper-of-the-Keys** [comment] 2024-01-30 22:28
Instead of removing the `if` on [CalendarHome.php:186](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalendarHome.php#L186) you can also set `$returnCachedSubscriptions` to be true on [CalendarHome.php:57](https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalendarHome.php#L57) as far as I can tell there is no interface/constructor etc. that ever interacts with that private variable.

I have not tested how this affects other things, for my very simple setup it seems to work.

**Comment by adverserath** [comment] 2024-01-31 00:42
Just had a quick look, instantly has the data brought back after a restart but the calendar can then not be disabled.
![image](https://github.com/nextcloud/server/assets/37800482/081ca719-431a-4b2e-806d-865dbfebe297)
