### ISSUE TITLE
Upgrade 19.0.3 to 19.0.4 via cli-updater: occ upgrade failed

### ISSUE THREAD

**Issue by LicoMonch** [nextcloud/server#23289] opened 2020-10-08 13:54 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. run v19.0.3
2. use updater.phar to update to 19.0.4

### Expected behaviour
occ upgrade after update should succeed

### Actual behaviour
occ upgrade did initially not succeed

### Server configuration

**Operating system:**
Debian 10

**Web server:**
Apache 2.4

**Database:**
PostgreSQL

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
19.0.3
Nextcloud Updater - version: v18.0.6-11-g50bdca3 dirty

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

No errors have been found.
```
</details>

**List of activated apps:**
<details>
This is after a follow up occ upgrade which succeded (see output below)
<summary>App list</summary>

```
$ sudo -u www-data php occ app:list
Enabled:
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - announcementcenter: 3.8.1
  - audioplayer: 2.12.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - event_update_notification: 1.0.2
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - flowupload: 1.0.0
  - impersonate: 1.6.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - metadata: 0.12.0
  - music: 0.16.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - passwords: 2020.10.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quicknotes: 0.6.1
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - user_usage_report: 1.3.3
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - accessibility
  - checksum
  - circles
  - deck
  - encryption
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_mindmap
  - forms
  - groupfolders
  - issuetemplate
  - news
  - ocr
  - onlyoffice
  - recommendations
  - serverinfo
  - spreed
  - systemtags
  - tasks
  - user_ldap
  - weather

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report aufter Update</summary>

```
$ sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "wolke.licomonch.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/MYDOMAIN",
        "dbtype": "pgsql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0,
        "updater.release.channel": "stable",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "ocr"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Logs

There are no corresponding log entries for the time stamps provider by updater.phar

### Console Output of updater.phar
<details>
root@$ sudo -u www-data php occ maintenance:mode --on && bash ../lazy_permissions_to_docs.sh && cd updater/ && sudo -u www-data php updater.phar && cd ..
Maintenance mode enabled
Nextcloud Updater - version: v18.0.6-11-g50bdca3 dirty

Current version is 19.0.3.

Update to Nextcloud 19.0.4 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-19.0.4.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] 
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2020-10-08T13:13:07+00:00 Set log level to debug
2020-10-08T13:13:07+00:00 Repair step: Repair MySQL collation
2020-10-08T13:13:07+00:00 Repair info: Not a mysql database -> nothing to do
2020-10-08T13:13:07+00:00 Repair step: Repair SQLite autoincrement
2020-10-08T13:13:07+00:00 Repair step: Copy data from accounts table when migrating from ownCloud
2020-10-08T13:13:07+00:00 Repair step: Drop account terms table when migrating from ownCloud
2020-10-08T13:13:07+00:00 Updating database schema
2020-10-08T13:13:08+00:00 Updated database
2020-10-08T13:13:08+00:00 Repair step: Cleanup ocr app data folder.
2020-10-08T13:13:08+00:00 Cleanup ocr app data folder.
2020-10-08T13:13:08+00:00 
2020-10-08T13:13:08+00:00  Starting ...
 0/1 [>-]   0%An unhandled exception has been thrown:
TypeError: Argument 1 passed to Symfony\Component\Console\Helper\ProgressBar::advance() must be of the type int, string given, called in /var/www/virtual_hosts/MYDOMAIN/docs/core/Command/Upgrade.php on line 144 and defined in /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/console/Helper/ProgressBar.php:310
Stack trace:
#0 /var/www/virtual_hosts/MYDOMAIN/docs/core/Command/Upgrade.php(144): Symfony\Component\Console\Helper\ProgressBar->advance('Deleted tessdat...')
#1 /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\Core\Command\Upgrade->OC\Core\Command\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#3 /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, '\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#4 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\EventDispatcher\GenericEvent), Object(Symfony\Component\EventDispatcher\GenericEvent))
#5 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/Repair.php(201): OC\EventDispatcher\SymfonyAdapter->dispatch('\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#6 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/Repair.php(232): OC\Repair->emit('\\OC\\Repair', 'advance', Array)
#7 /var/www/virtual_hosts/MYDOMAIN/docs/apps/ocr/lib/Migration/CleanupTessdata.php(48): OC\Repair->advance('Deleted tessdat...')
#8 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/Repair.php(103): OCA\Ocr\Migration\CleanupTessdata->run(Object(OC\Repair))
#9 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/legacy/OC_App.php(976): OC\Repair->run()
#10 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/App/AppManager.php(412): OC_App::executeRepairSteps('ocr', Array)
#11 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/Updater.php(410): OC\App\AppManager->disableApp('ocr', true)
#12 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/Updater.php(253): OC\Updater->checkAppsRequirements()
#13 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/Updater.php(130): OC\Updater->doUpgrade('19.0.4.2', '19.0.3.1')
#14 /var/www/virtual_hosts/MYDOMAIN/docs/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#15 /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/virtual_hosts/MYDOMAIN/docs/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/virtual_hosts/MYDOMAIN/docs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/virtual_hosts/MYDOMAIN/docs/console.php(100): OC\Console\Application->run()
#21 /var/www/virtual_hosts/MYDOMAIN/docs/occ(11): require_once('/var/www/virtua...')
#22 {main}
Keep maintenance mode active? [y/N] y
Maintenance mode kept active
</details>

### Console Output of a follow up occ upgrade
<details>
```

root@$ sudo -u www-data php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <activity> ...
Updated <activity> to 2.12.1
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app admin_audit in appstore
Checked for update of app "admin_audit" in appstore 
Checking for update of app announcementcenter in appstore
Checked for update of app "announcementcenter" in appstore 
Checking for update of app audioplayer in appstore
Checked for update of app "audioplayer" in appstore 
Checking for update of app bruteforcesettings in appstore
Checked for update of app "bruteforcesettings" in appstore 
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore 
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app contacts in appstore
Checked for update of app "contacts" in appstore 
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app event_update_notification in appstore
Checked for update of app "event_update_notification" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_retention in appstore
Checked for update of app "files_retention" in appstore 
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore 
Checking for update of app flowupload in appstore
Checked for update of app "flowupload" in appstore 
Checking for update of app impersonate in appstore
Checked for update of app "impersonate" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app mail in appstore
Checked for update of app "mail" in appstore 
Checking for update of app maps in appstore
Checked for update of app "maps" in appstore 
Checking for update of app metadata in appstore
Checked for update of app "metadata" in appstore 
Checking for update of app music in appstore
Checked for update of app "music" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app notes in appstore
Checked for update of app "notes" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app passwords in appstore
Checked for update of app "passwords" in appstore 
Checking for update of app photos in appstore
Checked for update of app "photos" in appstore 
Checking for update of app privacy in appstore
Checked for update of app "privacy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app quicknotes in appstore
Checked for update of app "quicknotes" in appstore 
Checking for update of app settings in appstore
Checked for update of app "settings" in appstore 
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore 
Checking for update of app support in appstore
Checked for update of app "support" in appstore 
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore 
Checking for update of app text in appstore
Checked for update of app "text" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app unsplash in appstore
Checked for update of app "unsplash" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app user_usage_report in appstore
Checked for update of app "user_usage_report" in appstore 
Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level

```
</details>

**Comment by acsfer** [comment] 2020-10-08 16:03
Possibly duplicate of https://github.com/nextcloud/server/issues/21067
(see last comment of the issue)

**Comment by kesselb** [comment] 2020-10-08 17:16
Thanks for reporting :+1: 

> /var/www/virtual_hosts/MYDOMAIN/docs/apps/ocr/lib/Migration/CleanupTessdata.php(48): OC\Repair->advance('Deleted tessdat...')

Closing in favour of https://github.com/janis91/ocr/issues/281. The issue is caused by OCR app calling a function the wrong way.

**Closed by kesselb** 2020-10-08 17:16 UTC
Labels: 0. Needs triage, needs info
