### ISSUE TITLE
attach logo directly to notification mail

### ISSUE THREAD

**Issue by mokkin** [nextcloud/server#20056] opened 2020-03-20 16:32 UTC
**Is your feature request related to a problem? Please describe.**
Privacy aware mail clients usually block loading of content inside mails from the internet such as pixel counters or pictures. Unfortunately therefore they are block the nextcloud logo too.

**Describe the solution you'd like**
The logo should be attached to the email to not getting blocked.

![grafik](https://user-images.githubusercontent.com/2938748/77184650-65177780-6ad0-11ea-8889-e57b2520c441.png)

**Comment by kesselb** [comment] 2020-03-20 17:53
Sounds like https://github.com/nextcloud/server/issues/13557

**Comment by jancborchardt** [comment] 2020-04-09 09:51
Yep, closing as duplicate of https://github.com/nextcloud/server/issues/13557 :)

**Closed by jancborchardt** 2020-04-09 09:51 UTC
Labels: 0. Needs triage, enhancement

**Comment by behrouzamiri** [comment] 2021-01-18 10:43
Why is this feature request closed without any schedule or even a NO answer?
@jancborchardt you've closed this as a duplicate of the thread that actually results in a feature request (which is exactly this) and closed by linking to this thread. and here, we get a link to there again, which creates a loop for someone like me who wants to follow this.
I'm a Mail Server guy.. It's very important from the security perspective for us to receive these emails with resources inline.
I'm aware that this cause inefficiency, but let's let the admins make the call.

**Comment by kesselb** [comment] 2021-01-18 17:21
> Why is this feature request closed without any schedule or even a NO answer?

Because it's a duplicate of #13557.

> you've closed this as a duplicate of the thread that actually results in a feature request (which is exactly this) and closed by linking to this thread. and here, we get a link to there again, which creates a loop for someone like me who wants to follow this.

I don't see a loop as #13557 is still open. 
> I'm aware that this cause inefficiency, but let's let the admins make the call.

Unfortunately the described feature is not really high on our priority list. But this doesn't mean that we don't like the idea or that we are against this feature per se. Quite the opposite! 

There are many way to get new features in Nextcloud:

1.  The easiest and most straight forward way (especially here at Github): pull request. Nextcloud is completely Free Software, this means that everyone is welcome to join and to contribute. If you or anyone else want to work on this feature, this would be great! We appreciate every pull request, and we are definitely able to help in case of questions, reviews, etc.
2. We have a category for [Freelancers in our forum](https://help.nextcloud.com/c/nextcloud-freelancing/48). Another option would be to post an offer there and try to find a freelancer who want to work on it.
3. The most direct way for a company or organization to get the issue addressed is to get a [Enterprise Subscription](https://nextcloud.com/pricing/). This includes everything to enable you to run Nextcloud in a productive environment with guaranteed SLA's and more. The Enterprise Subscription also includes optional professional services such as custom development. [Feel free to reach out to us](https://nextcloud.com/contact/). We are happy to explore the possibilities how to make Nextcloud fit your needs.
