### ISSUE TITLE
[Bug]: Nextcloud Favorite icon is not generating properly 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#35559] opened 2022-12-02 16:25 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I noticed that the Nextcloud fav icon automatically is generated like the below image only way to go around this is to upload a different fav icon into these then it will show properly like the nextclud logo 

![image](https://user-images.githubusercontent.com/59488153/205338586-b1b7ccd2-0dea-4cd1-a762-bbca1274f4cd.png)

### Steps to reproduce

1. Go to cloud.nextcloud.com
2. Add website to bookmarks and show on toolbar
3. go to website
4. see toolbar

### Expected behavior

Should auto generate the below image 

![image](https://user-images.githubusercontent.com/59488153/205338746-73b093ee-4898-462b-b01c-ab6722b2e6ff.png)

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

**Comment by andyxheli** [comment] 2022-12-06 13:08
Can you link the issues together please

**Comment by szaimen** [comment] 2023-01-23 15:08
Duplicate of https://github.com/nextcloud/server/issues/27502

**Closed by szaimen** 2023-01-23 15:08 UTC
Labels: bug, 0. Needs triage, 25-feedback
