### ISSUE TITLE
Unable to preview PDFs with a space in the path

### ISSUE THREAD

**Issue by plinss** [nextcloud/server#27642] opened 2021-06-23 21:23 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. In the files app, click a .pdf file that contains a space in the filename or a space in a containing folder

### Expected behaviour
Preview of PDF file

### Actual behaviour
Empty box with error message "Missing PDF file", clicking "More information" reveals: 
```
PDF.js v2.5.207 (build: 0974d6052)
Message: Missing PDF "https://cloud.****.com/remote.php/dav/files/peter/Nextcloud%2520Manual.pdf".
```

This appears to be a regression of #14384, the spaces in the path are double URL encoded

### Server configuration

**Operating system:**
Debian 10.10

**Web server:**
Nginx 1.21.0

**Database:**
MariaDB 10.3.29

**PHP version:**
7.3.27

**Nextcloud version:** (see Nextcloud admin page)
21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Both

**Where did you install Nextcloud from:**
download.nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - apporder: 0.12.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.2.2
  - camerarawpreviews: 0.7.11
  - checksum: 1.1.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.2
  - drawio: 1.0.0
  - encryption: 2.9.0
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_antivirus: 3.2.1
  - files_automatedtagging: 1.11.0
  - files_downloadactivity: 1.10.0
  - files_external: 1.12.0
  - files_fulltextsearch: 21.0.2
  - files_fulltextsearch_tesseract: 20.0.1
  - files_linkeditor: 1.1.5
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trackdownloads: 1.10.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - fulltextsearch: 21.0.1
  - fulltextsearch_elasticsearch: 21.0.1
  - group_everyone: 0.1.7
  - groupfolders: 9.0.2
  - integration_whiteboard: 0.0.14
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.9.5
  - metadata: 0.13.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - notify_push: 0.2.0
  - oauth2: 1.9.0
  - onlyoffice: 7.0.2
  - password_policy: 1.11.0
  - photos: 1.3.0
  - previewgenerator: 3.1.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - rainloop: 7.1.2
  - recommendations: 1.0.0
  - riotchat: 0.7.12
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.2.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - twofactor_u2f: 6.1.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_saml: 4.1.1
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.linss.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "defaultapp": "apporder",
        "default_phone_region": "US",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.*****.com",
        "overwritehost": "cloud..*****..com",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "htaccess.RewriteBase": "\/",
        "app.mail.accounts.default": {
            "email": "%EMAIL%",
            "imapHost": "mail..*****..com",
            "imapPort": 993,
            "imapUser": "%EMAIL%",
            "imapSslMode": "ssl",
            "smtpHost": "smtp..*****..com",
            "smtpPort": 465,
            "smtpUser": "%EMAIL%",
            "smtpSslMode": "ssl"
        },
        "app.mail.imap.timeout": 30,
        "app.mail.smtp.timeout": 30,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "allow_user_to_change_display_name": false,
        "simpleSignUpLink.shown": false,
        "app_install_overwrite": [
            "bruteforcesettings",
            "user_saml",
            "files_fulltextsearch_tesseract"
        ]
    }
}


```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
FIrefox

**Operating system:**
macOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing relevant
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing relevant
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing relevant, just the 404 error
```
</details>

**Comment by acsfer** [comment] 2021-06-23 21:36
Duplicate of https://github.com/nextcloud/files_pdfviewer/issues/381

**Closed by acsfer** 2021-06-23 21:36 UTC
Labels: 0. Needs triage, bug
