### ISSUE TITLE
[RFE] Optionally disable filesystem ownership permissions check in console.php

### ISSUE THREAD

**Issue by e-minguez** [nextcloud/server#24914] opened 2020-12-30 17:38 UTC
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/nextcloud/docker/issues/1344

The console.php file has a check to ensure the ownership... that fails if using nextcloud in containers with NFS as backend storage for /var/www/html with proper `all_squash,anonuid=82,anongid=0` to match www-data:root ownership.

https://github.com/nextcloud/server/blob/47b4efca542b70e015ff5f16ff9f4d2f3b9ac5bb/console.php#L68-L75

**Describe the solution you'd like**
Some config.php setting to disable the check would be nice.

**Describe alternatives you've considered**
As a workaround, I've just modified the file to skip the `exit(1)` call

**Additional context**

**Comment by szaimen** [comment] 2021-06-22 08:49
Closing as duplicate of #13277

**Closed by szaimen** 2021-06-22 08:49 UTC
Labels: 0. Needs triage, enhancement
