### ISSUE TITLE
Upgrade from 12.0.3 to 12.0.4 failed

### ISSUE THREAD

**Issue by TimoStolz** [nextcloud/server#7979] opened 2018-01-21 17:38 UTC
Error message in web-based update

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_storages_numeric_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_storages_numeric_id_... ^
Detaillierte Protokollmeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_storages_numeric_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_storages_numeric_id_...

**Comment by tflidd** [comment] 2018-01-22 10:26
Can you fill out the issue template? E.g. we don't know which database you are using...

**Comment by icebal** [comment] 2018-01-28 23:14
I also am having the same error after the upgrade. Below is the template.
 
### Steps to reproduce
1.use postgresql db
2. hit update weather button at login
3. get the error

### Expected behaviour
Tell us what should happen
weather updates and prceeds as normal
### Actual behaviour
Tell us what happens instead
update fails and error occurs
### Server configuration

**Operating system**: linuxserver.io docker container

**Web server:** nginx

**Database:**postgresql

**PHP version:**default in nextcloud container

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**update

**Where did you install Nextcloud from:** official docker container

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``` unable to access until update is completed
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - metadata: 0.6.0
  - music: 0.5.4
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.1
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - weather: 1.5.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
- activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - metadata: 0.6.0
  - music: 0.5.4
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.1
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.icebal.com:443"
        ],
        "overwrite.cli.url": "https:\/\/nextcloud.icebal.com:443",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "atomic.icebal.com",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.icebal.com:443"
        ],
        "overwrite.cli.url": "https:\/\/nextcloud.icebal.com:443",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "atomic.icebal.com",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "nextcloud",
        "mail_domain": "icebal.com",
        "mail_smtphost": "atomic.icebal.com",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local and nfs
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by icebal** [comment] 2018-02-11 23:05
Any update on this? I really dont want to loose my nextcloud setup :/

**Comment by celvin** [comment] 2018-02-12 00:02
Seems to be a compatibility issue between doctrine and postgresql 10.1, you can try to decrease the postgresql version or patch doctrine

**Comment by MorrisJobke** [comment] 2018-02-16 21:45
Postgres 10 support was added to 13: #7210

The error also looks like the one described in #5930

I will close this, because it seems to be the upgrade of Postgres from 9.x to 10 to be the cause for this issue. Either upgrade to 13 or downgrade postgres to 9.x again.

**Closed by MorrisJobke** 2018-02-16 21:45 UTC
Labels: needs info
