### ISSUE TITLE
Nextcloud 19 not working in IE11

### ISSUE THREAD

**Issue by Yomark1** [nextcloud/server#21410] opened 2020-06-15 09:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Start IE11
2. Go to Nextcloud URL
3. 

### Expected behaviour
NextCloud somehwat usable for IE11 users

### Actual behaviour
Nextcloud page loads, but even the login form isn't usable. 

### Server configuration

**Operating system:**
Ubuntu 18  server LTS

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
PHP 7.2.24-0ubuntu0.18.04.6

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0.5 or .6 Using default theming settings from(logo's, color) https://docs.nextcloud.com/server/19/admin_manual/configuration_server/theming.html

**Where did you install Nextcloud from:**
Manual install/upgrade from command line. 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.0.2
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_antivirus: 2.4.1
  - files_downloadactivity: 1.8.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.2.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - firstrunwizard
  - support
  - survey_client

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB(some shared folders) 
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP and or SAML ( multiple environments have the same issue) 
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

If relevant, I can post this here. But it's a lot of text.

</details>

### Client configuration
**Browser:**
IE11 , other browsers like Firefox or Opera work fine.

**Operating system:**
Windows 10 1909

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>
Don't think this is relevant. 
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
DOM7011: Zowel terug als vooruit in cache opslaan is door de code op deze pagina uitgeschakeld. Zie http://go.microsoft.com/fwlink/?LinkID=291337 voor meer informatie
login
HTML1300: Er heeft navigatie plaatsgevonden.
login
SCRIPT1014: Ongeldig teken
main.js (791,21360)
SCRIPT5009: OC is niet gedefinieerd
merged-template-prepend.js (26,1)
SCRIPT5009: OCA is niet gedefinieerd
search.js (196,2)
SCRIPT5009: OC is niet gedefinieerd
nl.js (1,1)
SCRIPT5009: OC is niet gedefinieerd
nl.js (1,1)
SCRIPT5009: OC is niet gedefinieerd
main.js (23,1)
SCRIPT5009: OCA is niet gedefinieerd
previewplugin.js (15,2)
SCRIPT5009: OC is niet gedefinieerd
main.js (22,1)
SCRIPT5009: OCA is niet gedefinieerd
searchprovider.js (410,2)
SCRIPT5009: OC is niet gedefinieerd
fileinfo.js (11,2)
SCRIPT5009: OC is niet gedefinieerd
client.js (13,2)
SCRIPT5009: dav is niet gedefinieerd
iedavclient.js (12,2)
SCRIPT5009: OCA is niet gedefinieerd
login.js (318,26387)
SCRIPT5009: OCA is niet gedefinieerd
theming (2,2)
SCRIPT5009: OCA is niet gedefinieerd
accessibility (2,2)

</details>

**Comment by kesselb** [comment] 2020-06-16 06:53
cc @nextcloud/javascript

**Comment by juliushaertl** [comment] 2020-06-16 07:06
duplicate of #21316

**Closed by juliushaertl** 2020-06-16 07:06 UTC
Labels: 0. Needs triage, 19-feedback, bug
