### ISSUE TITLE
CSP not playing nice with opcache. Login image not displayed

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/server#5664] opened 2017-07-09 22:41 UTC
This was reported and reproduced in NextCloudPi. 

### Steps to reproduce
1. Enable local DNS with `dnsmasq`, and establish `mycloud.ownyourbits.com` to resolve to local IP
2. Fresh firefox instance, private mode: access through IP (accept security exceptions). Login image shows
3. Access now through domain name (accept security exceptions): No login images are shown, only solid background. 

### Expected behaviour
Background image is shown

### Actual behaviour
Only solid background is shown. Console complains about CSP not allowing the IP, instead of using the domain.

It seems that opcache cached code and is not able to detect that it has changed. It is using the IP from the first call instead of the URL that we are actually using in the second call.

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://192.168.0.131/core/img/background.jpg?v=0 (“img-src https://mycloud.ownyourbits.com data: blob:”)
```
Restarting PHP7.0-fpm clears PHP cache and makes it work fine.

If we now go back to the first tab and try to use the IP again, the same error happens (but complains about the resource coming from the `mycloud.ownyourbits.com`). Clearing cache makes it work fine again and so on.

Quick testing showed that the issue is not present if we use `letsencrypt` ( CA signed certificates )

I understand that said code could be blacklisted from caching by using the `opcache.blacklist_filename` directive ([docs](http://www.php.net/manual/en/opcache.configuration.php#ini.opcache.blacklist-filename)).

AFAIK there is nothing that can be done from PHP code to avoid this behaviour, other than totally cleaning cache. Correct me if I am wrong.

With that in mind, I have not seen in the admin documentation any blacklist or configuration guidelines for opcache. 

What would be the recommended configuration for `opcache` in this regard? What files should we blacklist?

ContentSecurityPolicy.php ?
./lib/public/AppFramework/Http/Response.php ?
./lib/private/Security/CSP/ContentSecurityPolicyManager.php ?
Server.php ?

### Server configuration

**Operating system**: Raspbian Jessie

**Web server:** Apache

**Database:** MariaDB 10

**PHP version:** 7

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** latest NextCloudPi image

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.0.131"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocah3xtdazof",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

### Client configuration
**Browser:** Firefox 54

**Operating system:** Linux

**Comment by nachoparker** [comment] 2017-07-09 22:47
This is the original issue from NextCloudPi, at least three users have reported this already

https://github.com/nextcloud/nextcloudpi/issues/35

**Comment by nachoparker** [comment] 2017-07-14 14:00
added screenshot 

![opcache_issue](https://user-images.githubusercontent.com/21343324/28215241-8f3d251e-68ad-11e7-8b26-6ae183606dd9.jpg)

**Comment by juliushaertl** [comment] 2017-07-14 18:00
This is a duplicate of #5085 

A fix has been merged with https://github.com/nextcloud/server/pull/5429 and is already backported, so it should be fine, once 12.0.1 is released.

**Closed by juliushaertl** 2017-07-14 18:00 UTC

**Comment by nachoparker** [comment] 2017-07-14 18:04
Thank you. 

I did read that but did not think it was necessarily the same as it does not mention that PHP cache is involved.

Sorry for duplicating, good job!
