### ISSUE TITLE
Configuration of sender mail address for invitations

### ISSUE THREAD

**Issue by loibpet** [nextcloud/server#19145] opened 2020-01-26 15:46 UTC
**Is your feature request related to a problem? Please describe.**

When Nextcloud sends invitations, then Nextcloud uses the email address as defined by the administrators in the settings menu. This has the positive effect that every user can send invitations, even if the personal mail settings are not yet configured (correctly).

The downside is that there are spam filters around which have the tendency to classify mails as spam if too many mails are coming from the very same sender address within certain time frames. Just think about a Nexcloud installation with lots of users and in wich many of them are collaborating with people from other organistations and which send invitations ...

**Describe the solution you'd like**

It would be very helpful if there would be a switch that allows the administrators to choose between the current behaviour or to use a setup which uses the personal email address of the user, as configured in the personal settings of the Nextcloud user.

**Describe alternatives you've considered**

There is none, execpt the plain hope that no spam filter will interact and drop mails ...

**Comment by georgehrke** [comment] 2020-01-26 16:03
Duplicate of https://github.com/nextcloud/server/issues/5080

**Closed by georgehrke** 2020-01-26 16:03 UTC
Labels: 0. Needs triage, enhancement
