### ISSUE TITLE
Password change behavior

### ISSUE THREAD

**Issue by AykutCevik** [nextcloud/server#5181] opened 2017-05-30 20:03 UTC
As mentioned by @eppfel in #4839 I would like to suggest a modification in the password change process.
It would be great to add one more field to verify the newly entered password (repeat new password). I have file encryption enabled and recovery set to false which means if I make a mistake while entering the password once, all my data will be lost unrecoverable.
Or do I miss something here?
Also viewing the plain text of the password to review it is not always a suitable solution.

Thank you guys for your awesome work!

**Comment by MorrisJobke** [comment] 2017-08-15 20:21
cc @jancborchardt for this

**Comment by jancborchardt** [comment] 2017-09-17 17:09
Viewing the password in plain text is the best solution to quickly absolutely make sure that your password is correct. The attack vector of being able to check your screen or keyboard is even amplified in the case where you would repeat your password, as there people can check out the screen/keyboard twice.

**Comment by AykutCevik** [comment] 2017-09-20 09:19
Can't confirm this actually. Had a colleague sitting next to me and couldn't check my password in this case. Also I can't view my entered password entirely:

![image](https://user-images.githubusercontent.com/1965251/30636333-6baad006-9df5-11e7-91c6-945f917de9f7.png)

**Comment by J0WI** [comment] 2019-01-07 15:33
Seems to be a duplicate of #3565

**Comment by MorrisJobke** [comment] 2019-01-07 22:08
> Seems to be a duplicate of #3565

Correct -> let's close this here.

**Closed by MorrisJobke** 2019-01-07 22:08 UTC
Labels: enhancement, feature: settings, feature: users and groups
