### ISSUE TITLE
Add relative/real date switch config in Files

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/server#37759] opened 2023-04-17 06:25 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 
________________________

**Is your feature request related to a problem? Please describe.**
Searching a file with a specific date in a long ist of files is difficult, because it's always displayed as "x months ago". The real date is in the "title", but this doesn't help much.

**Describe the solution you'd like**
Add an option to the menu in the lower left corner to switch between a "x days ago" and a date display according to users selected locale.

**Describe alternatives you've considered**
Using the client or WebDAV and an other file manager on the client, but this is not always a possibility.

**Comment by susnux** [comment] 2024-08-07 15:55
Duplicate of https://github.com/nextcloud/server/issues/29807

**Closed by susnux** 2024-08-07 15:55 UTC
Labels: enhancement, 1. to develop, feature: files
