### ISSUE TITLE
Nextcloud 17: Notification API dies after causing an LDAP search storm

### ISSUE THREAD

**Issue by ananace** [nextcloud/server#17386] opened 2019-10-03 12:26 UTC
### Steps to reproduce
1. Update Nextcloud to 17.0.0.9
2. Browse the page long enough for multiple notification checks to run

### Expected behaviour
Notifications keep working

### Actual behaviour
The notification check causes a massive spam of errors until the request times out, temporarily freezing the system for at least that user

### Server configuration

**Operating system**: CentOS 7.7

**Web server:** nginx/1.17.4

**Database:** PostgreSQL 11.4

**PHP version:** 7.3.10

**Nextcloud version:** 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 16.0.5

**Where did you install Nextcloud from:** Docker nextcloud:17-fpm-alpine

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - apporder: 0.7.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - circles: 0.17.7
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.5
  - dav: 1.13.0
  - external: 3.4.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_accesscontrol: 1.7.0
  - files_automatedtagging: 1.7.0
  - files_external: 1.8.0
  - files_frommail: 0.3.0
  - files_pdfviewer: 1.6.0
  - files_retention: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.3
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 0.17.0
  - news: 14.0.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - ransomware_protection: 1.5.0
  - recommendations: 0.5.0
  - sentry: 5.1.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - user_saml: 2.4.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_external_gdrive
  - metadata
  - polls
  - socialsharing_diaspora
  - socialsharing_email
  - socialsharing_facebook
  - socialsharing_googleplus
  - socialsharing_twitter
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.ctrl-c.liu.se"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.ctrl-c.liu.se",
        "dbtype": "pgsql",
        "version": "17.0.0.9",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "updater.release.channel": "stable",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "app_install_overwrite": [
            "apporder",
            "files_automatedtagging"
        ],
        "sentry.dsn": "...",
        "sentry.public-dsn": "..."
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP + SAML

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                   |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                     |
| homeFolderNamingRule          |                                                                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                                                                     |
| ldapAgentName                 | uid=nextcloud,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se                                                                             |
| ldapAgentPassword             | ***                                                                                                                                   |
| ldapAttributesForGroupSearch  |                                                                                                                                       |
| ldapAttributesForUserSearch   |                                                                                                                                       |
| ldapBackupHost                | ldap2.svc.cluster.local                                                                                                               |
| ldapBackupPort                | 389                                                                                                                                   |
| ldapBase                      | dc=ctrl-c,dc=liu,dc=se                                                                                                                |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=ctrl-c,dc=liu,dc=se                                                                                          |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se                                                                                           |
| ldapCacheTTL                  | 600                                                                                                                                   |
| ldapConfigurationActive       | 1                                                                                                                                     |
| ldapDefaultPPolicyDN          |                                                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                                                                                       |
| ldapExpertUUIDUserAttr        |                                                                                                                                       |
| ldapExpertUsernameAttr        |                                                                                                                                       |
| ldapExtStorageHomeAttribute   |                                                                                                                                       |
| ldapGidNumber                 | gidNumber                                                                                                                             |
| ldapGroupDisplayName          | cn                                                                                                                                    |
| ldapGroupFilter               | (&(|(objectclass=groupofnames))(|(cn=admins)(cn=ctrl-c)(cn=ipausers)(cn=medlemmar)(cn=osdg)(cn=staff-members)(cn=styret)(cn=vmseng))) |
| ldapGroupFilterGroups         | admins;ctrl-c;ipausers;medlemmar;osdg;staff-members;styret;vmseng                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                     |
| ldapGroupFilterObjectclass    | groupofnames                                                                                                                          |
| ldapGroupMemberAssocAttr      | member                                                                                                                                |
| ldapHost                      | ldap.svc.cluster.local                                                                                                                |
| ldapIgnoreNamingRules         |                                                                                                                                       |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(entryUUID=%uid))))                               |
| ldapLoginFilterAttributes     |                                                                                                                                       |
| ldapLoginFilterEmail          | 0                                                                                                                                     |
| ldapLoginFilterMode           | 0                                                                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                                                                     |
| ldapNestedGroups              | 1                                                                                                                                     |
| ldapOverrideMainServer        | 0                                                                                                                                     |
| ldapPagingSize                | 500                                                                                                                                   |
| ldapPort                      | 389                                                                                                                                   |
| ldapQuotaAttribute            |                                                                                                                                       |
| ldapQuotaDefault              |                                                                                                                                       |
| ldapTLS                       | 0                                                                                                                                     |
| ldapUserAvatarRule            | default                                                                                                                               |
| ldapUserDisplayName           | gecos                                                                                                                                 |
| ldapUserDisplayName2          |                                                                                                                                       |
| ldapUserFilter                | (&(|(objectclass=inetorgperson)))                                                                                                     |
| ldapUserFilterGroups          |                                                                                                                                       |
| ldapUserFilterMode            | 0                                                                                                                                     |
| ldapUserFilterObjectclass     | inetorgperson                                                                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                                                                  |
| turnOffCertCheck              | 0                                                                                                                                     |
| turnOnPasswordChange          | 0                                                                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                                                                     |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
At least two clients have run into the issue, so listing both;

**Browser:**
Firefox 60
Firefox 69

**Operating system:**
Debian 10
Gentoo

#### Web server error log
<details>
<summary>Web server error log</summary>

```
10.26.252.23 - - [03/Oct/2019:11:59:51 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "https://nextcloud.ctrl-c.liu.se/apps/files/?dir=/&fileid=173" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0" "10.26.252.23"
2019/10/03 12:00:40 [error] 14#14: *617 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.26.252.23, server: , request: "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1", upstream: "fastcgi://unix:/var/run/fpm/nextcloud.sock:", host: "nextcloud.ctrl-c.liu.se", referrer: "https://nextcloud.ctrl-c.liu.se/apps/files/?dir=/&fileid=173"
10.26.252.23 - - [03/Oct/2019:12:00:40 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 502 157 "https://nextcloud.ctrl-c.liu.se/apps/files/?dir=/&fileid=173" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0" "10.26.252.23"
2019/10/03 12:00:59 [error] 14#14: *774 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.26.252.23, server: , request: "GET /core/js/dist/main.js.map HTTP/1.1", upstream: "fastcgi://unix:/var/run/fpm/nextcloud.sock:", host: "nextcloud.ctrl-c.liu.se"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"2TnJuOogHnUdNm5xMBKQ","level":0,"time":"2019-10-03T11:45:09+00:00","remoteAddr":"10.26.252.21","user":"0e021fbe-5417-11e6-bed7-00237ddcbd4f","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"17.0.0.9"}
{"reqId":"2TnJuOogHnUdNm5xMBKQ","level":0,"time":"2019-10-03T11:45:09+00:00","remoteAddr":"10.26.252.21","user":"0e021fbe-5417-11e6-bed7-00237ddcbd4f","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"17.0.0.9"}
{"reqId":"2TnJuOogHnUdNm5xMBKQ","level":0,"time":"2019-10-03T11:45:09+00:00","remoteAddr":"10.26.252.21","user":"0e021fbe-5417-11e6-bed7-00237ddcbd4f","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"17.0.0.9"}
{"reqId":"2TnJuOogHnUdNm5xMBKQ","level":0,"time":"2019-10-03T11:45:09+00:00","remoteAddr":"10.26.252.21","user":"0e021fbe-5417-11e6-bed7-00237ddcbd4f","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"17.0.0.9"}
{"reqId":"2TnJuOogHnUdNm5xMBKQ","level":0,"time":"2019-10-03T11:45:09+00:00","remoteAddr":"10.26.252.21","user":"0e021fbe-5417-11e6-bed7-00237ddcbd4f","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"17.0.0.9"}
{"reqId":"2TnJuOogHnUdNm5xMBKQ","level":0,"time":"2019-10-03T11:45:09+00:00","remoteAddr":"10.26.252.21","user":"0e021fbe-5417-11e6-bed7-00237ddcbd4f","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"17.0.0.9"}
{"reqId":"2TnJuOogHnUdNm5xMBKQ","level":0,"time":"2019-10-03T11:45:09+00:00","remoteAddr":"10.26.252.21","user":"0e021fbe-5417-11e6-bed7-00237ddcbd4f","app":"user_ldap","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"17.0.0.9"}
...
```

Repeating to around 16k lines before the request times out
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Shutting down notifications: [502] Bad Gateway sentry.js:30:16678
```
</details>

**Comment by kesselb** [comment] 2019-10-03 21:22
> spam of errors until the request times out,

Could you increase the loglevel to 1? 

> initializing paged search for  Filter (&(|(objectclass=inetorgperson))) base Array\n(\n    [0] => uid=magnus,cn=users,cn=accounts,dc=ctrl-c,dc=liu,dc=se\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0

It's a debug statment. I hope with less log entries it's easier to find the error.

**Comment by ananace** [comment] 2019-10-23 06:58
I switched loglevel to 1 as requested, the only output I see now is;
```
[23-Oct-2019 06:52:41] WARNING: [pool www] child 32 exited on signal 11 (SIGSEGV) after 267.579787 seconds from start
[23-Oct-2019 06:52:41] NOTICE: [pool www] child 279 started
[23-Oct-2019 06:53:02] WARNING: [pool www] child 58 exited on signal 11 (SIGSEGV) after 288.666754 seconds from start
[23-Oct-2019 06:53:02] NOTICE: [pool www] child 294 started
[23-Oct-2019 06:53:25] WARNING: [pool www] child 35 exited on signal 11 (SIGSEGV) after 311.376416 seconds from start
[23-Oct-2019 06:53:25] NOTICE: [pool www] child 316 started
[23-Oct-2019 06:53:47] WARNING: [pool www] child 44 exited on signal 11 (SIGSEGV) after 333.397286 seconds from start
[23-Oct-2019 06:53:47] NOTICE: [pool www] child 332 started
[23-Oct-2019 06:54:09] WARNING: [pool www] child 51 exited on signal 11 (SIGSEGV) after 355.658224 seconds from start
[23-Oct-2019 06:54:09] NOTICE: [pool www] child 348 started
```

(Nothing in `nextcloud.log`, nothing in `updater.log`, `audit.log` only includes logins and preview rendering messages)

Each segfault lining up with one `GET /ocs/v2.php/apps/notifications/api/v2/notifications` request - which time out with 502 errors.

**Comment by kesselb** [comment] 2019-10-23 07:05
cc @nextcloud/ldap

**Comment by blizzz** [comment] 2019-10-23 09:05
With that many log lines at the same request, it looks like an infinite loop. There must be something specific to your setup though, as I cannot reproduce it.

**Comment by kesselb** [comment] 2020-01-24 16:02
Probably related: https://github.com/nextcloud/notifications/issues/491

**Comment by szaimen** [comment] 2021-06-07 16:50
Based on blizzzs comment I am closing this issue.
If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 16:50 UTC
Labels: 0. Needs triage, bug
