### ISSUE TITLE
Can not delete local remote shares

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#11160] opened 2018-09-11 08:10 UTC
I accidentally shared something with "Ivan (remote)" on our company instance. Now when trying to delete the share, I get this error:

![bildschirmfoto von 2018-09-11 10-06-26](https://user-images.githubusercontent.com/213943/45346775-824dba80-b5aa-11e8-998d-24711f2edba3.png)

> Error removing share
> 
> Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.

```
InvalidArgumentException: Invalid cloud id
#12 /var/www/html/lib/private/Federation/CloudIdManager.php(41): resolveCloudId
#11 federatedfilesharing/lib/AddressHandler.php(73): splitUserRemote
#10 federatedfilesharing/lib/FederatedShareProvider.php(569): revokeShare
#9 federatedfilesharing/lib/FederatedShareProvider.php(544): delete
#8 /var/www/html/lib/private/Share20/Manager.php(968): deleteShare
#7 files_sharing/lib/Controller/ShareAPIController.php(341): deleteShare
#6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(166): executeController
#5 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(99): dispatch
#4 /var/www/html/lib/private/AppFramework/App.php(118): main
#3 /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php(47): __invoke
#2 /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php(0): call_user_func
#1 /var/www/html/lib/private/Route/Router.php(297): match
#0 /var/www/html/ocs/v1.php(82): null
```

cc @schiessle

**Comment by chrsch** [comment] 2018-10-25 07:09
Same Problem here with a cloud migrated vom oc 9.1.8 to nc 10 to 11 to 12.0.7

**Comment by mcnesium** [comment] 2018-11-24 17:50
If you want to remove the broken rest of a share (e.g. because you want to re-share it with the same remote ID, but can't because it thinks it is there already) here is a quick workaround, if you have access to the database: you can just remove the entry in the `oc_shares` table.

**Comment by mcnesium** [comment] 2019-03-15 15:13
It is also impossible to unshare something, if the remote Federated Cloud ID actually ***is*** invalid (e.g. the remote instance is no longer online).  Log says:

    {
        "reqId": "q1CC70zAP0OVw6vNG96Y",
        "level": 3,
        "time": "2019-03-15T15:10:08+00:00",
        "remoteAddr": "172.20.0.1",
        "user": "mcnesium",
        "app": "no app in context",
        "method": "DELETE",
        "url": "\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/193?format=json",
        "message": {
            "Exception": "OC\\HintException",
            "Message": "Invalid Federated Cloud ID",
            "Code": 0,
            "Trace": [{
                "file": "\/var\/www\/html\/apps\/federatedfilesharing\/lib\/FederatedShareProvider.php",
                "line": 569,
                "function": "splitUserRemote",
                "class": "OCA\\FederatedFileSharing\\AddressHandler",
                "type": "->",
                "args": ["mcnesium"]
            }, {
                "file": "\/var\/www\/html\/apps\/federatedfilesharing\/lib\/FederatedShareProvider.php",
                "line": 544,
                "function": "revokeShare",
                "class": "OCA\\FederatedFileSharing\\FederatedShareProvider",
                "type": "->",
                "args": [{
                    "__class__": "OC\\Share20\\Share"
                }, true]
            }, {
                "file": "\/var\/www\/html\/lib\/private\/Share20\/Manager.php",
                "line": 979,
                "function": "delete",
                "class": "OCA\\FederatedFileSharing\\FederatedShareProvider",
                "type": "->",
                "args": [{
                    "__class__": "OC\\Share20\\Share"
                }]
            }, {
                "file": "\/var\/www\/html\/apps\/files_sharing\/lib\/Controller\/ShareAPIController.php",
                "line": 351,
                "function": "deleteShare",
                "class": "OC\\Share20\\Manager",
                "type": "->",
                "args": [{
                    "__class__": "OC\\Share20\\Share"
                }]
            }, {
                "file": "\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
                "line": 166,
                "function": "deleteShare",
                "class": "OCA\\Files_Sharing\\Controller\\ShareAPIController",
                "type": "->",
                "args": ["193"]
            }, {
                "file": "\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
                "line": 99,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [{
                    "__class__": "OCA\\Files_Sharing\\Controller\\ShareAPIController"
                }, "deleteShare"]
            }, {
                "file": "\/var\/www\/html\/lib\/private\/AppFramework\/App.php",
                "line": 118,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [{
                    "__class__": "OCA\\Files_Sharing\\Controller\\ShareAPIController"
                }, "deleteShare"]
            }, {
                "file": "\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php",
                "line": 47,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": ["OCA\\Files_Sharing\\Controller\\ShareAPIController", "deleteShare", {
                    "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                }, {
                    "id": "193",
                    "_route": "ocs.files_sharing.ShareAPI.deleteShare"
                }]
            }, {
                "function": "__invoke",
                "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
                "type": "->",
                "args": [{
                    "id": "193",
                    "_route": "ocs.files_sharing.ShareAPI.deleteShare"
                }]
            }, {
                "file": "\/var\/www\/html\/lib\/private\/Route\/Router.php",
                "line": 297,
                "function": "call_user_func",
                "args": [{
                    "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
                }, {
                    "id": "193",
                    "_route": "ocs.files_sharing.ShareAPI.deleteShare"
                }]
            }, {
                "file": "\/var\/www\/html\/ocs\/v1.php",
                "line": 82,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": ["\/ocsapp\/apps\/files_sharing\/api\/v1\/shares\/193"]
            }, {
                "file": "\/var\/www\/html\/ocs\/v2.php",
                "line": 24,
                "args": ["\/var\/www\/html\/ocs\/v1.php"],
                "function": "require_once"
            }],
            "File": "\/var\/www\/html\/apps\/federatedfilesharing\/lib\/AddressHandler.php",
            "Line": 77,
            "Hint": "Invalid Federated Cloud ID",
            "Previous": {
                "Exception": "InvalidArgumentException",
                "Message": "Invalid cloud id",
                "Code": 0,
                "Trace": [{
                    "file": "\/var\/www\/html\/apps\/federatedfilesharing\/lib\/AddressHandler.php",
                    "line": 73,
                    "function": "resolveCloudId",
                    "class": "OC\\Federation\\CloudIdManager",
                    "type": "->",
                    "args": ["mcnesium"]
                }, {
                    "file": "\/var\/www\/html\/apps\/federatedfilesharing\/lib\/FederatedShareProvider.php",
                    "line": 569,
                    "function": "splitUserRemote",
                    "class": "OCA\\FederatedFileSharing\\AddressHandler",
                    "type": "->",
                    "args": ["mcnesium"]
                }, {
                    "file": "\/var\/www\/html\/apps\/federatedfilesharing\/lib\/FederatedShareProvider.php",
                    "line": 544,
                    "function": "revokeShare",
                    "class": "OCA\\FederatedFileSharing\\FederatedShareProvider",
                    "type": "->",
                    "args": [{
                        "__class__": "OC\\Share20\\Share"
                    }, true]
                }, {
                    "file": "\/var\/www\/html\/lib\/private\/Share20\/Manager.php",
                    "line": 979,
                    "function": "delete",
                    "class": "OCA\\FederatedFileSharing\\FederatedShareProvider",
                    "type": "->",
                    "args": [{
                        "__class__": "OC\\Share20\\Share"
                    }]
                }, {
                    "file": "\/var\/www\/html\/apps\/files_sharing\/lib\/Controller\/ShareAPIController.php",
                    "line": 351,
                    "function": "deleteShare",
                    "class": "OC\\Share20\\Manager",
                    "type": "->",
                    "args": [{
                        "__class__": "OC\\Share20\\Share"
                    }]
                }, {
                    "file": "\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
                    "line": 166,
                    "function": "deleteShare",
                    "class": "OCA\\Files_Sharing\\Controller\\ShareAPIController",
                    "type": "->",
                    "args": ["193"]
                }, {
                    "file": "\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
                    "line": 99,
                    "function": "executeController",
                    "class": "OC\\AppFramework\\Http\\Dispatcher",
                    "type": "->",
                    "args": [{
                        "__class__": "OCA\\Files_Sharing\\Controller\\ShareAPIController"
                    }, "deleteShare"]
                }, {
                    "file": "\/var\/www\/html\/lib\/private\/AppFramework\/App.php",
                    "line": 118,
                    "function": "dispatch",
                    "class": "OC\\AppFramework\\Http\\Dispatcher",
                    "type": "->",
                    "args": [{
                        "__class__": "OCA\\Files_Sharing\\Controller\\ShareAPIController"
                    }, "deleteShare"]
                }, {
                    "file": "\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php",
                    "line": 47,
                    "function": "main",
                    "class": "OC\\AppFramework\\App",
                    "type": "::",
                    "args": ["OCA\\Files_Sharing\\Controller\\ShareAPIController", "deleteShare", {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    }, {
                        "id": "193",
                        "_route": "ocs.files_sharing.ShareAPI.deleteShare"
                    }]
                }, {
                    "function": "__invoke",
                    "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
                    "type": "->",
                    "args": [{
                        "id": "193",
                        "_route": "ocs.files_sharing.ShareAPI.deleteShare"
                    }]
                }, {
                    "file": "\/var\/www\/html\/lib\/private\/Route\/Router.php",
                    "line": 297,
                    "function": "call_user_func",
                    "args": [{
                        "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
                    }, {
                        "id": "193",
                        "_route": "ocs.files_sharing.ShareAPI.deleteShare"
                    }]
                }, {
                    "file": "\/var\/www\/html\/ocs\/v1.php",
                    "line": 82,
                    "function": "match",
                    "class": "OC\\Route\\Router",
                    "type": "->",
                    "args": ["\/ocsapp\/apps\/files_sharing\/api\/v1\/shares\/193"]
                }, {
                    "file": "\/var\/www\/html\/ocs\/v2.php",
                    "line": 24,
                    "args": ["\/var\/www\/html\/ocs\/v1.php"],
                    "function": "require_once"
                }],
                "File": "\/var\/www\/html\/lib\/private\/Federation\/CloudIdManager.php",
                "Line": 41
            },
            "CustomMessage": "--"
        },
        "userAgent": "Mozilla\/5.0 (X11; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0",
        "version": "15.0.5.3"
    }

**Comment by christian1211** [comment] 2020-02-18 08:10
facing the same issue on nextcloud 17.0.3

**Comment by StCyr** [comment] 2020-07-14 12:27
I think I get the same issue on nextcloud 19.0.

Here's my log:

```
{
  "reqId": "aCLKByYyIOOvkFhqdH7q",
  "level": 4,
  "time": "2020-07-14T12:24:22+00:00",
  "remoteAddr": "94.104.124.217",
  "user": "cyrille",
  "app": "webdav",
  "method": "DELETE",
  "url": "/remote.php/dav/files/cyrille/external",
  "message": "{\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"\",\"Code\":0,\"Trace\":[{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php\",\"line\":80,\"function\":\"getChild\",\"class\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php\",\"line\":182,\"function\":\"getNodeForPath\",\"class\":\"Sabre\\\\DAV\\\\Tree\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php\",\"line\":295,\"function\":\"delete\",\"class\":\"Sabre\\\\DAV\\\\Tree\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php\",\"line\":89,\"function\":\"httpDelete\",\"class\":\"Sabre\\\\DAV\\\\CorePlugin\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":474,\"function\":\"emit\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":251,\"function\":\"invokeMethod\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"line\":319,\"function\":\"start\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/apps/dav/lib/Server.php\",\"line\":320,\"function\":\"exec\",\"class\":\"Sabre\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php\",\"line\":35,\"function\":\"exec\",\"class\":\"OCA\\\\DAV\\\\Server\",\"type\":\"->\"},{\"file\":\"/var/www/nextcloud/remote.php\",\"line\":167,\"args\":[\"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php\"],\"function\":\"require_once\"}],\"File\":\"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php\",\"Line\":223,\"CustomMessage\":\"--\"}",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:78.0) Gecko/20100101 Firefox/78.0",
  "version": "19.0.0.12"
}
```

I'm getting this log line when trying to unshare a federated storage when the remote shared storage is not accessible anymore

**Comment by szaimen** [comment] 2021-06-07 18:58
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by StCyr** [comment] 2021-06-08 07:43
I don't know. I don't use this functionality anymore

**Comment by mcnesium** [comment] 2021-06-08 09:40
Checking on two instances running NC v21.0.2 I can not reproduce this error anymore. LGTM
Thank you for asking, @szaimen :)

**Closed** 2021-06-08 09:42 UTC
Labels: 0. Needs triage, bug, feature: federation, feature: sharing, needs info, regression
