### ISSUE TITLE
Error creating user: The username *** is queued for deletion

### ISSUE THREAD

**Issue by rschitz** [nextcloud/server#10297] opened 2018-07-19 11:10 UTC
when trying to recreate a deleted user for some email tests
version 13.0.4
<img width="948" alt="screen shot 2018-07-19 at 13 10 16" src="https://user-images.githubusercontent.com/8385646/42939202-20dcbd52-8b55-11e8-8b55-53c45efd309a.png">

**Comment by rschitz** [comment] 2018-07-19 11:19
https://git.mdns.eu/nextcloud/passwords/commit/13621debac30a2e19c60a935120cb2092e482052?view=inline
is this related?

**Comment by MorrisJobke** [comment] 2018-07-24 12:12
> when trying to recreate a deleted user for some email tests

Yes - this comes from the passwords app and thus we can't do much. Closing this and I would ask you to report it to the maintainer of the passwords app. Thanks

**Closed by MorrisJobke** 2018-07-24 12:12 UTC
Labels: bug, design

**Comment by rschitz** [comment] 2018-07-24 12:36
ok thx

**Comment by VincentSC** [comment] 2022-06-09 18:33
Still a problem caused by the `passwords` app. The simple solution is to disable the `passwords` app, let the person log in via oauth or recreate the user in the config, then enable that app again.
