### ISSUE TITLE
occ prime-caches

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#14463] opened 2019-03-01 22:37 UTC
Would be nice to have a CLI command, or perhaps several, that prime/s caches. This/these could be invoked at the end of an install/upgrade/restart process, and would do whatever necessary so that when the first user hits Nextcloud with the browser, it doesn't take an eternity:
1) for the front page with the login to come up.
2) for a new user to be successfully logged on.

As I am not entirely certain what is cached and what is not -- and perhaps there are some things that take a long time on the first time, too, that aren't strictly cache related -- this feature request is intentionally vague and requires somebody who understands the internals to turn into something actionable.

Sure we'd like to have this feature for out-of-the-box experience for [UBOSboxes](https://indiecomputing.com/products/). Related [issue](https://github.com/uboslinux/ubos-nextcloud/issues/32).

**Comment by skjnldsv** [comment] 2020-11-07 23:46
What would this function do? Flush all cashes?

**Comment by jernst** [comment] 2020-11-09 20:17
I'm confused what you are asking beyond what I already described in the issue.

**Comment by skjnldsv** [comment] 2020-11-10 05:53
Sorry for the confusion, not a native Eng speaker, I misunderstood "to prime". 
Duplicate of https://github.com/nextcloud/server/issues/7984

**Closed by skjnldsv** 2020-11-10 05:53 UTC
Labels: 0. Needs triage, enhancement, needs info
