### ISSUE TITLE
Status does not allow some emojis

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#23412] opened 2020-10-13 12:11 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set your status emoji to :toolbox:

### Expected behaviour
Status updated.

### Server configuration

**Operating system:**
![Bildschirmfoto von 2020-10-13 14-06-47](https://user-images.githubusercontent.com/1374172/95858796-ecbf1f00-0d5d-11eb-988d-f6b5e933b6ef.png)
![Bildschirmfoto von 2020-10-13 14-06-35](https://user-images.githubusercontent.com/1374172/95858799-ed57b580-0d5d-11eb-80f4-aa6d9083843a.png)

**Web server:**
n/a

**Database:**
n/a

**PHP version:**
n/a

**Nextcloud version:** (see Nextcloud admin page)
20.0.0

**Comment by nickvergessen** [comment] 2020-10-13 12:23
Duplicate of #23304

**Closed** 2020-10-13 12:22 UTC
Labels: 1. to develop, 20-feedback, bug
