### ISSUE TITLE
After upgrade from 20.0.4 to 20.0.5 all apps are gone (not disabled, vanished)

### ISSUE THREAD

**Issue by amiga23** [nextcloud/server#25242] opened 2021-01-20 23:27 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
I did not try to reproduce this. I simply updated from 20.0.4 to 20.0.5

### Expected behaviour
All apps should still be there or deactivated if not compatible

### Actual behaviour
All apps but the default ones are gone.

### Server configuration

**Nextcloud version:** 20.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from 20.0.4

**Where did you install Nextcloud from:** Official Docker repo

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - files_external
  - password_policy
  - theming
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ""***REMOVED SENSITIVE VALUE***""
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": ""***REMOVED SENSITIVE VALUE***"",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/nextcloud",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/"***REMOVED SENSITIVE VALUE***"\/nextcloud",
        "dbtype": "mysql",
        "version": "20.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "joplin",
            "social",
            "cookbook",
            "music",
            "scanner"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
2021-01-19T22:51:21Z Initializing nextcloud 20.0.5.2 ...
2021-01-19T22:51:21Z Upgrading nextcloud from 20.0.4.0 ...
2021-01-19T22:51:59Z Initializing finished
2021-01-19T22:52:01Z Nextcloud or one of the apps require upgrade - only a limited number of commands are available
2021-01-19T22:52:01Z You may use your browser or the occ upgrade command to do the upgrade
2021-01-19T22:52:01Z Setting log level to debug
2021-01-19T22:52:01Z Turned on maintenance mode
2021-01-19T22:52:03Z Updating database schema
2021-01-19T22:52:03Z Updated database
2021-01-19T22:52:03Z Disabled incompatible app: appointments
2021-01-19T22:52:03Z Disabled incompatible app: audioplayer
2021-01-19T22:52:03Z Disabled incompatible app: audioplayer_editor
2021-01-19T22:52:03Z Disabled incompatible app: bookmarks
2021-01-19T22:52:03Z Disabled incompatible app: bruteforcesettings
2021-01-19T22:52:03Z Disabled incompatible app: calendar
2021-01-19T22:52:03Z Disabled incompatible app: cms_pico
2021-01-19T22:52:03Z Disabled incompatible app: contacts
2021-01-19T22:52:03Z Disabled incompatible app: cookbook
2021-01-19T22:52:03Z Disabled incompatible app: deck
2021-01-19T22:52:03Z Disabled incompatible app: files_markdown
2021-01-19T22:52:03Z Disabled incompatible app: mail
2021-01-19T22:52:03Z Disabled incompatible app: music
2021-01-19T22:52:03Z Disabled incompatible app: notes
2021-01-19T22:52:03Z Disabled incompatible app: qownnotesapi
2021-01-19T22:52:03Z Disabled incompatible app: radio
2021-01-19T22:52:03Z Disabled incompatible app: scanner
2021-01-19T22:52:03Z Disabled incompatible app: spreed
2021-01-19T22:52:03Z Disabled incompatible app: tasks
2021-01-19T22:52:03Z Disabled incompatible app: whiteboard
2021-01-19T22:52:03Z Updating <photos> ...
2021-01-19T22:52:03Z Updated <photos> to 1.2.3
2021-01-19T22:52:03Z Updating <files_sharing> ...
2021-01-19T22:52:05Z Updated <files_sharing> to 1.12.2
2021-01-19T22:52:06Z Checking for update of app accessibility in appstore
2021-01-19T22:52:26Z Checked for update of app "accessibility" in appstore
2021-01-19T22:52:26Z Checking for update of app activity in appstore
2021-01-19T22:52:26Z Checked for update of app "activity" in appstore
2021-01-19T22:52:26Z Checking for update of app cloud_federation_api in appstore
2021-01-19T22:52:26Z Checked for update of app "cloud_federation_api" in appstore
2021-01-19T22:52:26Z Checking for update of app comments in appstore
2021-01-19T22:52:26Z Checked for update of app "comments" in appstore
2021-01-19T22:52:26Z Checking for update of app contactsinteraction in appstore
2021-01-19T22:52:26Z Checked for update of app "contactsinteraction" in appstore
2021-01-19T22:52:26Z Checking for update of app dav in appstore
2021-01-19T22:52:26Z Checked for update of app "dav" in appstore
2021-01-19T22:52:26Z Checking for update of app federatedfilesharing in appstore
2021-01-19T22:52:26Z Checked for update of app "federatedfilesharing" in appstore
2021-01-19T22:52:26Z Checking for update of app federation in appstore
2021-01-19T22:52:26Z Checked for update of app "federation" in appstore
2021-01-19T22:52:26Z Checking for update of app files in appstore
2021-01-19T22:52:26Z Checked for update of app "files" in appstore
2021-01-19T22:52:26Z Checking for update of app files_pdfviewer in appstore
2021-01-19T22:52:26Z Checked for update of app "files_pdfviewer" in appstore
2021-01-19T22:52:26Z Checking for update of app files_rightclick in appstore
2021-01-19T22:52:26Z Checked for update of app "files_rightclick" in appstore
2021-01-19T22:52:26Z Checking for update of app files_sharing in appstore
2021-01-19T22:52:26Z Checked for update of app "files_sharing" in appstore
2021-01-19T22:52:26Z Checking for update of app files_trashbin in appstore
2021-01-19T22:52:26Z Checked for update of app "files_trashbin" in appstore
2021-01-19T22:52:26Z Checking for update of app files_versions in appstore
2021-01-19T22:52:26Z Checked for update of app "files_versions" in appstore
2021-01-19T22:52:26Z Checking for update of app files_videoplayer in appstore
2021-01-19T22:52:26Z Checked for update of app "files_videoplayer" in appstore
2021-01-19T22:52:26Z Checking for update of app firstrunwizard in appstore
2021-01-19T22:52:26Z Checked for update of app "firstrunwizard" in appstore
2021-01-19T22:52:26Z Checking for update of app logreader in appstore
2021-01-19T22:52:26Z Checked for update of app "logreader" in appstore
2021-01-19T22:52:26Z Checking for update of app lookup_server_connector in appstore
2021-01-19T22:52:26Z Checked for update of app "lookup_server_connector" in appstore
2021-01-19T22:52:26Z Checking for update of app nextcloud_announcements in appstore
2021-01-19T22:52:26Z Checked for update of app "nextcloud_announcements" in appstore
2021-01-19T22:52:26Z Checking for update of app notifications in appstore
2021-01-19T22:52:26Z Checked for update of app "notifications" in appstore
2021-01-19T22:52:26Z Checking for update of app oauth2 in appstore
2021-01-19T22:52:26Z Checked for update of app "oauth2" in appstore
2021-01-19T22:52:26Z Checking for update of app photos in appstore
2021-01-19T22:52:26Z Checked for update of app "photos" in appstore
2021-01-19T22:52:26Z Checking for update of app privacy in appstore
2021-01-19T22:52:26Z Checked for update of app "privacy" in appstore
2021-01-19T22:52:26Z Checking for update of app provisioning_api in appstore
2021-01-19T22:52:26Z Checked for update of app "provisioning_api" in appstore
2021-01-19T22:52:26Z Checking for update of app recommendations in appstore
2021-01-19T22:52:26Z Checked for update of app "recommendations" in appstore
2021-01-19T22:52:26Z Checking for update of app serverinfo in appstore
2021-01-19T22:52:26Z Checked for update of app "serverinfo" in appstore
2021-01-19T22:52:26Z Checking for update of app settings in appstore
2021-01-19T22:52:26Z Checked for update of app "settings" in appstore
2021-01-19T22:52:26Z Checking for update of app sharebymail in appstore
2021-01-19T22:52:26Z Checked for update of app "sharebymail" in appstore
2021-01-19T22:52:26Z Checking for update of app support in appstore
2021-01-19T22:52:26Z Checked for update of app "support" in appstore
2021-01-19T22:52:26Z Checking for update of app survey_client in appstore
2021-01-19T22:52:26Z Checked for update of app "survey_client" in appstore
2021-01-19T22:52:26Z Checking for update of app systemtags in appstore
2021-01-19T22:52:26Z Checked for update of app "systemtags" in appstore
2021-01-19T22:52:26Z Checking for update of app text in appstore
2021-01-19T22:52:26Z Checked for update of app "text" in appstore
2021-01-19T22:52:26Z Checking for update of app twofactor_backupcodes in appstore
2021-01-19T22:52:26Z Checked for update of app "twofactor_backupcodes" in appstore
2021-01-19T22:52:26Z Checking for update of app updatenotification in appstore
2021-01-19T22:52:26Z Checked for update of app "updatenotification" in appstore
2021-01-19T22:52:26Z Checking for update of app user_status in appstore
2021-01-19T22:52:26Z Checked for update of app "user_status" in appstore
2021-01-19T22:52:26Z Checking for update of app viewer in appstore
2021-01-19T22:52:26Z Checked for update of app "viewer" in appstore
2021-01-19T22:52:26Z Checking for update of app weather_status in appstore
2021-01-19T22:52:26Z Checked for update of app "weather_status" in appstore
2021-01-19T22:52:26Z Checking for update of app workflowengine in appstore
2021-01-19T22:52:26Z Checked for update of app "workflowengine" in appstore
2021-01-19T22:52:26Z Checking for update of app appointments in appstore
2021-01-19T22:52:26Z Checked for update of app "appointments" in appstore
2021-01-19T22:52:27Z Checking for update of app audioplayer in appstore
2021-01-19T22:52:27Z Checked for update of app "audioplayer" in appstore
2021-01-19T22:52:27Z Checking for update of app audioplayer_editor in appstore
2021-01-19T22:52:27Z Checked for update of app "audioplayer_editor" in appstore
2021-01-19T22:52:27Z Checking for update of app bookmarks in appstore
2021-01-19T22:52:27Z Checked for update of app "bookmarks" in appstore
2021-01-19T22:52:27Z Checking for update of app bruteforcesettings in appstore
2021-01-19T22:52:27Z Checked for update of app "bruteforcesettings" in appstore
2021-01-19T22:52:27Z Checking for update of app calendar in appstore
2021-01-19T22:52:27Z Checked for update of app "calendar" in appstore
2021-01-19T22:52:27Z Checking for update of app cms_pico in appstore
2021-01-19T22:52:27Z Checked for update of app "cms_pico" in appstore
2021-01-19T22:52:27Z Checking for update of app contacts in appstore
2021-01-19T22:52:27Z Checked for update of app "contacts" in appstore
2021-01-19T22:52:27Z Checking for update of app cookbook in appstore
2021-01-19T22:52:27Z Checked for update of app "cookbook" in appstore
2021-01-19T22:52:27Z Checking for update of app deck in appstore
2021-01-19T22:52:27Z Checked for update of app "deck" in appstore
2021-01-19T22:52:27Z Checking for update of app files_markdown in appstore
2021-01-19T22:52:27Z Checked for update of app "files_markdown" in appstore
2021-01-19T22:52:27Z Checking for update of app mail in appstore
2021-01-19T22:52:27Z Checked for update of app "mail" in appstore
2021-01-19T22:52:27Z Checking for update of app music in appstore
2021-01-19T22:52:27Z Checked for update of app "music" in appstore
2021-01-19T22:52:27Z Checking for update of app notes in appstore
2021-01-19T22:52:27Z Checked for update of app "notes" in appstore
2021-01-19T22:52:27Z Checking for update of app qownnotesapi in appstore
2021-01-19T22:52:27Z Checked for update of app "qownnotesapi" in appstore
2021-01-19T22:52:27Z Checking for update of app radio in appstore
2021-01-19T22:52:27Z Checked for update of app "radio" in appstore
2021-01-19T22:52:27Z Checking for update of app scanner in appstore
2021-01-19T22:52:27Z Checked for update of app "scanner" in appstore
2021-01-19T22:52:27Z Checking for update of app spreed in appstore
2021-01-19T22:52:27Z Checked for update of app "spreed" in appstore
2021-01-19T22:52:27Z Checking for update of app tasks in appstore
2021-01-19T22:52:27Z Checked for update of app "tasks" in appstore
2021-01-19T22:52:27Z Checking for update of app whiteboard in appstore
2021-01-19T22:52:27Z Checked for update of app "whiteboard" in appstore
2021-01-19T22:52:30Z Starting code integrity check...
2021-01-19T22:52:51Z Finished code integrity check
2021-01-19T22:52:51Z Update successful
2021-01-19T22:52:51Z Turned off maintenance mode
2021-01-19T22:52:51Z Resetting log level
2021-01-19T22:52:52Z The following apps have been disabled:
2021-01-19T22:52:52Z appointments
2021-01-19T22:52:52Z audioplayer
2021-01-19T22:52:52Z audioplayer_editor
2021-01-19T22:52:52Z bookmarks
2021-01-19T22:52:52Z bruteforcesettings
2021-01-19T22:52:52Z calendar
2021-01-19T22:52:52Z cms_pico
2021-01-19T22:52:52Z contacts
2021-01-19T22:52:52Z cookbook
2021-01-19T22:52:52Z deck
2021-01-19T22:52:52Z files_markdown
2021-01-19T22:52:52Z files_sharing
2021-01-19T22:52:52Z mail
2021-01-19T22:52:52Z music
2021-01-19T22:52:52Z notes
2021-01-19T22:52:52Z photos
2021-01-19T22:52:52Z qownnotesapi
2021-01-19T22:52:52Z radio
2021-01-19T22:52:52Z scanner
2021-01-19T22:52:52Z spreed
2021-01-19T22:52:52Z tasks
2021-01-19T22:52:52Z whiteboard
2021-01-19T22:52:52Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.32.0.2. Set the 'ServerName' directive globally to suppress this message
2021-01-19T22:52:52Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.32.0.2. Set the 'ServerName' directive globally to suppress this message
2021-01-19T22:52:52Z [Tue Jan 19 22:52:52.805952 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.14 configured -- resuming normal operations
2021-01-19T22:52:52Z [Tue Jan 19 22:52:52.806094 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
2021-01-19T22:57:49Z 10.42.128.1 - - [19/Jan/2021:22:57:48 +0000] "GET /cron.php HTTP/1.1" 200 1568 "-" "curl/7.74.0"
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by amiga23** [comment] 2021-01-21 01:35
After adding the apps back manually again, it seems that no data was lost.

**Comment by kesselb** [comment] 2021-01-21 14:42
Duplicate of https://github.com/nextcloud/server/issues/25137

**Closed by kesselb** 2021-01-21 14:42 UTC
Labels: 0. Needs triage, bug
