### ISSUE TITLE
Share directory/File a new LDAP group member is not taken in account 

### ISSUE THREAD

**Issue by jb-cd** [nextcloud/server#24642] opened 2020-12-10 14:27 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Share a File /Directory to a LDAP group
2. Add de new member to LDAP and the group
3. The new member doesn't see the shared file/directory

### Expected behaviour
Tell us what should happen
The new group member should see the shared file/directory

### Actual behaviour
Tell us what happens instead
The new group member doesn't see the shared file/directory

### Server configuration

**Operating system:**
Debian Buster

**Web server:**
Nginx / php-fpm 

**Database:**
Postgresql 11

**PHP version:**
7.3 

**Nextcloud version:** (see Nextcloud admin page)
19.0.6 , 19.0.4 had the same issue

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated, we don't know if this is a new issue or if it has always existed.

**Where did you install Nextcloud from:**
Official nextcloud zip file and web updates

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - cloud_federation_api: 1.2.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.2.2
  - documentserver_community: 0.1.8
  - drawio: 0.9.8
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.2
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - oidc_login: 1.6.1
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.11
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sharerenamer: 2.7.3
  - spreed: 9.0.6
  - support: 1.2.1
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - bruteforcesettings
  - comments
  - encryption
  - federation
  - files_external
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - onlyoffice
  - survey_client

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud*",
            "*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 7",
        "overwrite.cli.url": "https:\/\/nextcloud.credativ.com",
        "dbtype": "pgsql",
        "version": "19.0.6.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "simpleSignUpLink.shown": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "lost_password_link": "disabled",
        "oidc_login_provider_url": "https:\/\/auth.*\/",
        "oidc_login_client_id": "*",
        "oidc_login_client_secret": "*",
        "oidc_login_auto_redirect": false,
        "oidc_login_logout_url": "https:\/\/nextcloud.*",
        "oidc_login_button_text": "Single Sign On",
        "oidc_login_proxy_ldap": true,
        "oidc_login_attributes": {
            "id": "entryuuid",
            "name": "cn",
            "mail": "mail",
            "ldap_uid": "sub"
        },
        "oidc_login_scope": "openid nextcloud",
        "oidc_login_disable_registration": true,
        "oidc_login_redir_fallback": false,
        "app_install_overwrite": [
            "files_accesscontrol",
            "sharerenamer",
            "discoursesso"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no only https

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
+-------------------------------+--------------------------------------------------------------------------+
| Configuration                 |                                                                          |
+-------------------------------+--------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                          |
| homeFolderNamingRule          |                                                                          |
| lastJpegPhotoLookup           | 0                                                                        |
| ldapAgentName                 |                                                                          |
| ldapAgentPassword             | ***                                                                      |
| ldapAttributesForGroupSearch  |                                                                          |
| ldapAttributesForUserSearch   |                                                                          |
| ldapBackupHost                |                                                                          |
| ldapBackupPort                |                                                                          |
| ldapBase                      | dc=*                                                       |
| ldapBaseGroups                | dc=*                                                       |
| ldapBaseUsers                 | dc=*                                                       |
| ldapCacheTTL                  | 600                                                                      |
| ldapConfigurationActive       | 1                                                                        |
| ldapDefaultPPolicyDN          |                                                                          |
| ldapDynamicGroupMemberURL     |                                                                          |
| ldapEmailAttribute            | mail                                                                     |
| ldapExperiencedAdmin          | 0                                                                        |
| ldapExpertUUIDGroupAttr       |                                                                          |
| ldapExpertUUIDUserAttr        |                                                                          |
| ldapExpertUsernameAttr        |                                                                          |
| ldapExtStorageHomeAttribute   |                                                                          |
| ldapGidNumber                 | gidNumber                                                                |
| ldapGroupDisplayName          | cn                                                                       |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                                           |
| ldapGroupFilterGroups         |                                                                          |
| ldapGroupFilterMode           | 0                                                                        |
| ldapGroupFilterObjectclass    | posixGroup                                                               |
| ldapGroupMemberAssocAttr      | memberUid                                                                |
| ldapHost                      | ldaps://ldap*                                            |
| ldapIgnoreNamingRules         |                                                                          |
| ldapLoginFilter               | (&(&(objectclass=posixAccount)(mail=*)(loginShell=/bin/bash))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                          |
| ldapLoginFilterEmail          | 0                                                                        |
| ldapLoginFilterMode           | 0                                                                        |
| ldapLoginFilterUsername       | 1                                                                        |
| ldapMatchingRuleInChainState  | unknown                                                                  |
| ldapNestedGroups              | 0                                                                        |
| ldapOverrideMainServer        |                                                                          |
| ldapPagingSize                | 500                                                                      |
| ldapPort                      | 636                                                                      |
| ldapQuotaAttribute            |                                                                          |
| ldapQuotaDefault              |                                                                          |
| ldapTLS                       | 0                                                                        |
| ldapUserAvatarRule            | default                                                                  |
| ldapUserDisplayName           | cn                                                                       |
| ldapUserDisplayName2          |                                                                          |
| ldapUserFilter                | (&(objectclass=posixAccount)(mail=*@*)(loginShell=/bin/bash))  |
| ldapUserFilterGroups          |                                                                          |
| ldapUserFilterMode            | 1                                                                        |
| ldapUserFilterObjectclass     | posixAccount                                                             |
| ldapUuidGroupAttribute        | auto                                                                     |
| ldapUuidUserAttribute         | auto                                                                     |
| turnOffCertCheck              | 0                                                                        |
| turnOnPasswordChange          | 0                                                                        |
| useMemberOfToDetectMembership | 1                                                                        |
+-------------------------------+--------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by bwurst** [comment] 2020-12-13 06:12
Also affects other source of user groups, in my case it's user_sql backend. Also affects users that are defined in the external database but never logged into nextcloud.

**Comment by christianvw** [comment] 2020-12-22 21:55
There is a similar issue regarding this, maybe they are related: https://github.com/nextcloud/server/issues/19520

For me this issue only appears when the user got created after the share got created.

**Comment by szaimen** [comment] 2021-06-18 14:28
Duplicate of https://github.com/nextcloud/server/issues/25062

**Closed by szaimen** 2021-06-18 14:28 UTC
Labels: 0. Needs triage, bug
