### ISSUE TITLE
NC17 - Close icon in detail

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#18059] opened 2019-11-21 12:51 UTC
### Actual behaviour
The "X" button is laping when it's a text file. It's hard to see it.
![NC](https://i.imgur.com/FTZ77CF.png)

Zoom: 
![ZOOM](https://i.imgur.com/Ex7Z4Te.png)

### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache/2.4.6

**Database:**
 5.5.64-MariaDB

**PHP version:**
PHP 7.3.11

**Nextcloud version:** (see Nextcloud admin page)
17.0.1.1

**Updated from an older Nextcloud or fresh install:**
Both

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Are you using encryption:** no

### Client configuration
Chrome 78.0.3904.97 (64 bits)
Firefox 70.0.1 (64 bits)
Edge

**Comment by szaimen** [comment] 2021-06-07 17:18
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

---

See 
![image](https://user-images.githubusercontent.com/42591237/121062241-20efc000-c7c5-11eb-9a6e-5c7589707f2f.png)

**Closed by szaimen** 2021-06-07 17:18 UTC
Labels: 0. Needs triage, bug
