### ISSUE TITLE
Trash on external files

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/server#18396] opened 2019-12-13 10:01 UTC
**Is your feature request related to a problem? Please describe.**
I have a big external storage with a huge amount of videos. Now remove such a big file (using NC).
According to my research the to-be-removed file will be moved to the trash folder of my current user and the file will be removed on the external storage. This has some draw-backs:
1. The trash gets full quite quickly as the NC data partition is not too big.
2. As a result all other trashed files get removed to free up space. This can cause other problems.
3. The file needs to be copied from one partition to another. This might take significant time causing PHP to time out in worst case scenario.

**Describe the solution you'd like**
There could be a set of additional setting in the config of the external storage. Using these I can define how the trash in the external storage should be managed. Suggestions:
- Keep the old behavior
- Remove without trashing
- Use a separate folder (on the external storage partition) as trash folder. This renders the copy/removal much more quick as it is a simple rename.
- Use a dot folder in the root of the external storage to keep track of the files (but hide it from the NC UI of course)

**Comment by joshtrichards** [comment] 2024-07-12 19:09
Duplicate of #14436

**Closed by joshtrichards** 2024-07-12 19:09 UTC
Labels: enhancement, 1. to develop, feature: external storage, feature: trashbin
