### ISSUE TITLE
Public share download button is using theme color

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33811] opened 2022-09-01 16:56 UTC
@jancborchardt Maybe you can clarify how this should look:

![](https://user-images.githubusercontent.com/277525/187649199-3778de85-c28a-43fe-8ffc-478272354f51.png)

**Comment by jancborchardt** [comment] 2022-09-01 17:26
Hmm I mean the folder icons for example would also use this primary theme color, right? So I’d say until we do the clearly out-of-scope thing and generate the primary color based on the background (like Material Design: https://m3.material.io/theme-builder ), we have to live with this.

The key thing is the default looks nice.

**Comment by nickvergessen** [comment] 2022-09-01 18:07
The problem is, this will also be the case e.g. for talks button to open the sidebar.
We implemented [`'tertiary-on-primary'`](https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcButton/NcButton.vue#L247) for the topbar. Maybe there is still time to rename it to say "topbar" as I suggested back then instead of "on primary", so it can always pick up the color of the header section instead of primary.

**Comment by skjnldsv** [comment] 2022-09-28 14:34
Primary should be dictated by the background
so, unless the admin disabled the background (see https://github.com/nextcloud/server/issues/33797), then the primary on public should be `#0082c9`, or the admin-custom-primary if background is disabled

**Comment by szaimen** [comment] 2022-09-28 22:51
Should get addressed in https://github.com/nextcloud/server/issues/33925

**Closed by szaimen** 2022-09-28 22:51 UTC
Labels: 25-feedback, ui-refresh-feedback
