### ISSUE TITLE
Logs flooded with "sem_get(): Failed for key 0xa11: Function not implemented at ..."

### ISSUE THREAD

**Issue by jan0sch** [nextcloud/server#46503] opened 2024-07-13 08:05 UTC
Hi,

my logs are flooded with the following messages and also it seems that I no longer see image or video previews.

```
sem_get(): Failed for key 0xa11: Function not implemented at .../nextcloud/lib/private/Preview/Generator.php#230
```

Nextcloud: 29.0.3
OS: FreeBSD 14.1
PHP: 8.2.18

Kind regards

**Comment by solracsf** [comment] 2024-07-14 09:17
This can have different causes 
One of them https://lists.freebsd.org/archives/freebsd-questions/2023-August/004067.html

**Comment by jan0sch** [comment] 2024-07-14 10:14
I already did research and the `sysvmsg = new` flag for the jail is set but does have no effect. The error/behaviour stays the same.

**Comment by joshtrichards** [comment] 2024-07-14 14:43
Duplicate of #44578

**Closed by joshtrichards** 2024-07-14 14:43 UTC
Labels: bug, 0. Needs triage, feature: previews and thumbnails, 29-feedback
