### ISSUE TITLE
Enhancement: Notification disabled when storage is set to read only

### ISSUE THREAD

**Issue by KiritoStudio** [nextcloud/server#14545] opened 2019-03-05 14:47 UTC
Hi, I have several external storages and all of them is set to read only. So I don't want the notification warning like "Your storage is full, files can not be updated or synced anymore!" to disturb all the users. I think it is an improvement to the users.

**Comment by joshtrichards** [comment] 2023-07-08 13:31
Hi @KiritoStudio - It appears #18552 is a duplicate of your original enhancement request. Since #18552 appears to be where most people are voting, let's close your Issue in favor of #18552. If you agree the other Issue is the same as yours, I encourage you to close this Issue and subscribe yourself to #18552 to track progress.

**Closed** 2023-09-14 14:01 UTC
Labels: enhancement, 1. to develop
