### ISSUE TITLE
Weakness in function getAppTemplateDirs

### ISSUE THREAD

**Issue by quenenni** [nextcloud/server#23037] opened 2020-09-24 14:10 UTC
Hello,

The line "if (file_exists($app_dir.'/templates/')) {" in the file function getAppTemplateDirs from the file lib/private/Template/Base.php can lead to template problems (internal server problem).

I explained the problem and gave a solution here https://help.nextcloud.com/t/suddenly-internal-server-error/91029

I'm using Nc 19.0.1.1

**Comment by kesselb** [comment] 2020-09-24 16:15
Thanks for reporting :+1: 

Closing as duplicate of https://github.com/nextcloud/server/issues/14115.

**Closed by kesselb** 2020-09-24 16:15 UTC
Labels: 0. Needs triage, bug
