### ISSUE TITLE
shared link access check

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#16210] opened 2019-07-03 10:54 UTC
version 16.0.1
![shared link](https://user-images.githubusercontent.com/6248560/60585801-d7082f00-9d90-11e9-8781-bfa351d410e5.png)

the information is correct but not very useful as the user would have to know the access permission of the complete tree.

I strongly suggest to implement a function showing who has access to a directory or a file and show the result here (instead of the help message) and on every item everywhere clicking on the      share symbol.
currently it is not clear for me, if defining access will add to or override access grants given on higher levels.

**Comment by ferdiga** [comment] 2019-07-03 11:04
If  a user accesses a file vie "Recent" he will probably not even have an idea in which directory the file is stored.

**Comment by MorrisJobke** [comment] 2019-07-03 11:48
The feature of the link was discussed in https://github.com/nextcloud/server/issues/12877#issuecomment-449227473

And the list of share recipients is also already worked on in  https://github.com/nextcloud/server/pull/15952

Thus I would close this ticket here as duplicate of the two mentioned above.

**Closed by MorrisJobke** 2019-07-03 11:48 UTC
Labels: 0. Needs triage, enhancement

**Comment by ferdiga** [comment] 2019-07-03 15:35
I am not sure if this answers my question/suggestion:

I (and others in my organisation) would like to see who has access to an item independently of sharing

**Comment by MorrisJobke** [comment] 2019-07-03 16:06
> I (and others in my organisation) would like to see who has access to an item independently of sharing

How should they have access to an item except via sharing?

**Comment by ferdiga** [comment] 2019-07-03 16:14
Sorry I mean sharing of a parent

**Comment by MorrisJobke** [comment] 2019-07-03 16:24
> Sorry I mean sharing of a parent

This is what #15952 aims for. Show all people that have access to a file, based on shared parents.

**Comment by ferdiga** [comment] 2019-07-03 16:25
thanks
