### ISSUE TITLE
[Bug]: NC 28.0.2 RC5 When drag and drop multiple files, only one is loaded 

### ISSUE THREAD

**Issue by Rem559** [nextcloud/server#43240] opened 2024-01-31 17:04 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When drag and drop multiple files from PC , only one is loaded

### Steps to reproduce

1. Select multiple files on PC
2. Drop to drag and drop field 
3. only one will be loaded

### Expected behavior

1. Select multiple files on PC
2. Drop to drag and drop field 
3. all files are uploaded

### Installation method

manual

### Nextcloud Server version

28.0.2 RC5

### Operating system

Ubuntu 18.04 5.4.0-169

### PHP engine version

8.2

### Web server

apache 2.4

### Database engine version

maria db

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell

```

### Additional info
PC, windows 10, Google Chrome
_No response_

**Comment by drebs** [comment] 2024-02-01 14:01
I think this should be labelled https://github.com/nextcloud/server/labels/regression, as the feature used to work and is now broken.

Also, FTR, the problem is still occurring in 28.0.2.

**Comment by bravedave** [comment] 2024-02-02 01:55
This seems also to be reported here #43074 

28.02 has progressed from 28.0.1 where drag and drop was totally broken

If I upload using the New > Upload files method - no issue
If I upload via Drag & Drop, only the first file is uploaded

I'm using Brave, and have checked in Chrome - same result
Brave is Version 1.62.156 (latest) on Win 11

**Comment by skjnldsv** [comment] 2024-02-02 07:34
Duplicate of https://github.com/nextcloud/server/issues/43074

**Closed** 2024-02-02 07:33 UTC
Labels: bug, 0. Needs triage, feature: files, 28-feedback
