### ISSUE TITLE
[Bug]: New folder set focus to input field? 

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#44841] opened 2024-04-16 08:55 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The new folder dialog has the wrong focus. 

[Screencast from 2024-04-16 10-51-52.webm](https://github.com/nextcloud/server/assets/3902676/d9e67af5-2f89-4fcc-b4f3-b6e4816f6edc)

### Steps to reproduce

1. Files
2. New folder
3. Start typing

### Expected behavior

Input should go to input field.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment] 2024-04-16 08:55
cc @nextcloud/server-frontend

**Comment by susnux** [comment] 2024-04-16 10:37
Duplicate of https://github.com/nextcloud/server/issues/43659

**Closed by susnux** 2024-04-16 10:37 UTC
Labels: bug, 0. Needs triage, 30-feedback
