### ISSUE TITLE
Please ignore editor backup files if possible

### ISSUE THREAD

**Issue by ingoj** [nextcloud/server#8839] opened 2018-03-15 18:40 UTC
When upgrading from NC 13.0.0 to NC 13.0.1 (but this is also valid for other upgrades), NC updater is a little picky about backup files from some editors (!=vim), like this one: 

Create backup
Could not copy "/var/www/html/nextcloud/config/config.php~" to "/var/lib/nextcloud/data/updater-oc9eitss4uan/backups/nextcloud-13.0.0.14/config/config.php~"

So, NC should only consider non-backup files ending in "*~" and ignore these when creating the backup. This was also a problem with .users.ini~ in stage "check for expected files"

**Comment by MorrisJobke** [comment] 2018-03-16 10:52
Duplicate of https://github.com/nextcloud/updater/issues/68

**Closed by MorrisJobke** 2018-03-16 10:52 UTC
