### ISSUE TITLE
Cannot see share information for folder

### ISSUE THREAD

**Issue by solick** [nextcloud/server#9495] opened 2018-05-16 17:05 UTC
Nextcloud 12. 

User A has shared with external users a folder.
User B cannot see any information in Folder details that this folder is shared or the link or with whom.

**Comment by MorrisJobke** [comment] 2018-05-31 12:54
Duplicate of #3392 and #6480

Also #4281 will help to make this more easily discoverable.

**Closed by MorrisJobke** 2018-05-31 12:54 UTC
