### ISSUE TITLE
ERROR because of disabled opcache_get_status at hosted-servers/shared-hosting-servers

### ISSUE THREAD

**Issue by r34ldude** [nextcloud/server#26268] opened 2021-03-24 00:41 UTC
Hello,
I have a fresh install on a hosted-Server. When I try to open the System /serverinfo tab I got a error.
At hosted-servers/shared-hosting-servers is opcache_get_status() commonly disabled. 

LOG: https://help.nextcloud.com/t/solved-error-while-trying-to-open-system-serverinfo-error-beim-versuch-system-serverinfo-aufzurufen/111672

Now I changed the lines 82-88; https://help.nextcloud.com/t/20-0-1-errors-phpstatistics-opcache-get-status-has-been-disabled-for-security-reasons/97231/4
With this solution it works;

```

$status = (function_exists('opcache_get_status')) ? opcache_get_status(false) : false;
if ($status === false OR $status === NULL) {
// no array, returning back empty array to prevent any errors on JS side.
$status = [];
}
```

;)

**Comment by kesselb** [comment] 2021-03-30 13:37
Duplicate of https://github.com/nextcloud/serverinfo/issues/268

**Closed by kesselb** 2021-03-30 13:37 UTC
Labels: 0. Needs triage, bug
