### ISSUE TITLE
Problem with long and clipped comments in the "Comments" tab

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#31252] opened 2022-02-18 09:26 UTC
Hello !

**Is your feature request related to a problem? Please describe.**
In the "Comments" tab of the files, when a relatively long comment has been written, the text is simply cut off... and "visually", nobody can intuitively imagine that the text is longer than that (and that it has been cut off)... some users might even think that this is a bug (whereas it is a small UX design issue).  Also, as there is no change in the appearance of the cut text when the cursor passes over it (even the cursor does not turn into a "hand"), nobody can guess that the text is cut, unless one reads it carefully... and then the user says that there is a bug and that the person did not write his comment to the end.

**Describe the solution you'd like**
At the end of the "cut" text, we should simply add this "[...]" or "Read more" ... with perhaps a slight colour difference to indicate that it should be clicked. In addition to this indicator, when the text is cut, the whole of the cut text block should change colour slightly when the cursor is hovered over it.

What do you think of this? ... and of the improvement I propose ?

Thank you in advance!

Jérôme

![2022-02-18_10-12](https://user-images.githubusercontent.com/33763786/154654985-1f509a05-b4d2-47e6-a731-1b52d793c961.jpg)
![2022-02-18_10-12b](https://user-images.githubusercontent.com/33763786/154654989-93c66d56-d171-4f75-b520-710c17975022.jpg)
![2022-02-18_10-13](https://user-images.githubusercontent.com/33763786/154654991-b3376b3c-06b0-4370-b698-6c086b66c89c.jpg)

**Comment by Jerome-Herbinet** [comment] 2023-08-29 07:43
To illustrate the described problem :
[Capture vidéo du 29-08-2023 09:42:07.webm](https://github.com/nextcloud/server/assets/33763786/99a0005c-9f71-4b94-82e8-7ba7e8b62e1b)

**Comment by joshtrichards** [comment] 2024-01-27 03:22
Duplicate of #26429

**Comment by joshtrichards** [comment] 2024-01-27 03:22
I think these are great ideas - maybe pop over that other issue and add to the discussion.

**Closed by joshtrichards** 2024-01-27 03:22 UTC
Labels: enhancement, design, 0. Needs triage, feature: comments, ux
