### ISSUE TITLE
2FA and passwordless should be mutually exclusive options

### ISSUE THREAD

**Issue by michaelfliegner** [nextcloud/server#49796] opened 2024-12-11 09:07 UTC
Having both on is contradictory and may lead to login accepting the same passkey twice, which is not risky, but confusing.
Moreover should backup codes not be offered as an additional factor, but as an authentication method on its own, because it can replace other methods.

**Comment by kesselb** [comment] 2024-12-11 09:33
Duplicate of https://github.com/nextcloud/server/issues/21215

**Closed by kesselb** 2024-12-11 09:33 UTC
