### ISSUE TITLE
Used space / free space not automatically refreshing (webinterface)

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/server#7157] opened 2017-11-13 10:27 UTC
Steps to reproduce

 
### Steps to reproduce
1. Upload File in webinterface
2. Look on the used / free space in the webinterface (down left)

### Expected behaviour
1. Direct refresh after File Upload / Delete

### Actual behaviour
1. The used space won't change
2. The bar won't change
3. After site reload, it works

### Server configuration

**Operating system**: 16.04 LTS

**Web server:** Apache2 2.4.18

**Database:** MariaDB 10.0.31

**PHP version:** PHP 7.0.22

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocm2546lszfb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "++++++",
            "++++++"
        ],
        "datadirectory": "\/data\/data",
        "overwrite.cli.url": "https:\/\/+++++++",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "+++++",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": "0",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "mail_from_address": "+++++",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "+++++.net",
        "mail_smtphost": "+++.e++++.net",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</details>

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+-------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                     |
| hasPagedResultSupport         |                                                                                                       |
| homeFolderNamingRule          |                                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                                     |
| ldapAgentName                 | +++++                                                                     |
| ldapAgentPassword             | ++++++++++                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                       |
| ldapAttributesForUserSearch   |                                                                                                       |
| ldapBackupHost                |                                                                                                       |
| ldapBackupPort                |                                                                                                       |
| ldapBase                      | dc=++++=+++++                                                                                   |
| ldapBaseGroups                | ou=++,dc=+++,dc=+++;ou=+++++,dc=+++,dc=++++l                                                  |
| ldapBaseUsers                 | dc=++++++=local                                                                                    |
| ldapCacheTTL                  | 600                                                                                                   |
| ldapConfigurationActive       | 1                                                                                                     |
| ldapDefaultPPolicyDN          |                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                                                       |
| ldapExpertUUIDUserAttr        | samAccountName                                                                                        |
| ldapExpertUsernameAttr        |                                                                                                       |
| ldapGidNumber                 | gidNumber                                                                                             |
| ldapGroupDisplayName          | cn                                                                                                    |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                             |
| ldapGroupFilterGroups         |                                                                                                       |
| ldapGroupFilterMode           | 0                                                                                                     |
| ldapGroupFilterObjectclass    | group                                                                                                 |
| ldapGroupMemberAssocAttr      | member                                                                                                |
| ldapHost                      | ++++++++                                                                  |
| ldapIgnoreNamingRules         |                                                                                                       |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(|(samaccountname=%uid)(|(userPrincipalName=%uid)(mail=%uid))(|(cn=%uid)))) |
| ldapLoginFilterAttributes     | cn                                                                                                    |
| ldapLoginFilterEmail          | 1                                                                                                     |
| ldapLoginFilterMode           | 1                                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                                     |
| ldapNestedGroups              | 0                                                                                                     |
| ldapOverrideMainServer        |                                                                                                       |
| ldapPagingSize                | 500                                                                                                   |
| ldapPort                      | 389                                                                                                   |
| ldapQuotaAttribute            |                                                                                                       |
| ldapQuotaDefault              |                                                                                                       |
| ldapTLS                       | 0                                                                                                     |
| ldapUserDisplayName           | displayname                                                                                           |
| ldapUserDisplayName2          |                                                                                                       |
| ldapUserFilter                | (&(|(objectclass=user)))                                                                              |
| ldapUserFilterGroups          |                                                                                                       |
| ldapUserFilterMode            | 0                                                                                                     |
| ldapUserFilterObjectclass     | user                                                                                                  |
| ldapUuidGroupAttribute        | auto                                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                                  |
| turnOffCertCheck              | 0                                                                                                     |
| turnOnPasswordChange          | 1                                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                                     |
+-------------------------------+-------------------------------------------------------------------------------------------------------+
</details>

**Comment by MorrisJobke** [comment] 2017-11-13 11:26
Duplicate of #6690

**Closed by MorrisJobke** 2017-11-13 11:26 UTC
