### ISSUE TITLE
"stay logged in" not working 

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/server#1266] opened 2016-09-05 06:32 UTC
### Steps to reproduce
1. Open your Nextcloud server in the browser
2. Enter username and password
3. tick the "stay logged in" box (it'll log in after this)
4. close browser
5. Open Nextcloud in browser
6. Login screen shown (didn't remember login)

### Expected behaviour
After logging in with the "stay logged in" option, I shouldn't have to log back in 

### Actual behaviour
You are logged out. 

### Server configuration
Ubuntu 16.04

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
Type: mysql [MARIADB]
Version: 10.0.25
Size: 8.8 MB

**PHP version:**
Version: 7.0.8

**Nextcloud version:** (see Nextcloud admin page)
10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
From Nextcloud site

**Signing status:**
N/A

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
NOT FOUND error page 

**List of activated apps:**
 - Notes
 - news 
 - Files
 - Calendar
 - Tasks

**Comment by coderkun** [comment] 2016-09-05 07:17
Duplicate of #1067.

**Closed** 2016-09-05 08:36 UTC
