### ISSUE TITLE
Logging flooded with User disabled

### ISSUE THREAD

**Issue by patricksebastien** [nextcloud/server#28050] opened 2021-07-19 17:25 UTC
Hi,
All version of Nextcloud I think, when looking at the Logging page _/settings/admin/logging_ I see a lots of  Fatal and Error for User disabled.
```
Fatal | webdav | Sabre\DAV\Exception\ServiceUnavailable: OC\User\LoginException: User disabled 
Error | no app in context | OC\User\LoginException: User disabled
```

1- is it possible to know the username so I can contact him / her to ask them to remove the connection (from the desktop client)
2- is it possible to not show those error / fatal so that I can see the other logs

Thanks

**Comment by szaimen** [comment] 2021-08-08 15:47
Duplicate of https://github.com/nextcloud/server/issues/22758

**Closed by szaimen** 2021-08-08 15:47 UTC
Labels: enhancement, 0. Needs triage
