### ISSUE TITLE
Add Support for Link headers

### ISSUE THREAD

**Issue by tbe** [nextcloud/server#9316] opened 2018-04-26 14:36 UTC
To make use of the server push feature of HTTP/2, there is needed some kinds of mechanism to tell the webserver which files should be pushed.

The common method is to use the `Link` header.

The `addStyle`, `addScript`, ... functions may do this.

Example of a Link header:
```
Link </xxx.css>;rel=preload, </xxx.js>; rel=preload
```

https://httpd.apache.org/docs/current/howto/http2.html#push

**Comment by Glandos** [comment] 2018-06-04 08:58
Duplicate of #6214.

**Comment by szaimen** [comment] 2021-05-21 12:35
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Closed by szaimen** 2021-05-21 12:35 UTC
Labels: 1. to develop, enhancement
