### ISSUE TITLE
Versions of files only visible for creator of shared folder

### ISSUE THREAD

**Issue by FerronN** [nextcloud/server#13750] opened 2019-01-22 18:35 UTC
### Steps to reproduce
1. Create a folder and put files in it
2. Share the folder with other users or groups 
3. Change the file
4. Get the details of a shared file
5. look at the versions tab "No other versions available"

### Expected behaviour
I would expect that the version of the files are shown

### Actual behaviour
it says "No other versions available".
Only the user who created the folder can see the versions.

### Server configuration

**Operating system**:
Docker 15.02 Image

**Nextcloud version:** (see Nextcloud admin page)
15.02

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
docker repository

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

**Are you using external storage, if yes which one:** local/smb/sftp/...
nfs

**Are you using encryption:** yes/no
no
```

**Comment by maghog** [comment] 2019-01-25 08:03
Same problem in Nextcloud 15.0.2

**Comment by MorrisJobke** [comment] 2019-01-25 10:12
Currently versions are bound to the owner of the file - we are about overhaul this completely to allow shared versions. This has some side effect, because for example you don't want to expose versions from before the share was created and stuff like that.

This is currently a limitation of how versions are implemented. For the "versions 2.0" overview ticket please check out #9445.

Sorry for the bad news here - we are looking into improving this. As of now I will close this ticket here and refer to #9445, because we need this to accomplish shared versions.

**Comment by MorrisJobke** [comment] 2019-01-25 13:30
Sorry mixed this up. I just tested and this is a regression from #11778.


cc @icewind1991 @rullzer

**Comment by MorrisJobke** [comment] 2019-01-25 13:49
The problem here is that the versions are user specific:

I have `user1` (owner) and `admin` (share recipient):

For the owner the files are visible via `/remote.php/dav/versions/test1/versions/94/` but admin requests this via `/remote.php/dav/versions/admin/versions/94/` which leads to an empty collection. (manually requesting the first URL as `admin` results in a 403)

Potential solutions:

* requesting `/remote.php/dav/versions/test1/versions/94/` as `admin` and return the versions properly (requires permission checks on the backend and a slightly adjusted frontend)
* requesting `/remote.php/dav/versions/admin/versions/94/` as `admin` and mapping in the backend the versions of the other user (requires permission checks on the backend)

**Comment by MorrisJobke** [comment] 2019-01-25 13:49
<img width="1236" alt="bildschirmfoto 2019-01-25 um 14 45 38" src="https://user-images.githubusercontent.com/245432/51749712-660d6e80-20b0-11e9-977f-18b86dd57dba.png">

**Comment by FerronN** [comment] 2019-01-25 16:45
@MorrisJobke thanks you for the response!

> requesting /remote.php/dav/versions/test1/versions/94/ as admin and return the versions properly (requires permission checks on the backend and a slightly adjusted frontend)

This makes more sense looking at how the files are stored on the server.

**Closed** 2019-01-30 08:21 UTC
Labels: 1. to develop, bug, feature: sharing, feature: versions, regression
