### ISSUE TITLE
Opera not compatible : Bug in share icon.

### ISSUE THREAD

**Issue by ishlovenko** [nextcloud/server#16948] opened 2019-08-31 19:11 UTC
### Steps to reproduce
1. Download Latest Opera Browser
2. Install nextcloud 16,17 or any version 16+ or create new demo in nextcloud
3. 
**In Opera:**
![image](https://user-images.githubusercontent.com/34350936/64068104-f983c080-cbf8-11e9-994e-10ff67a9048b.png)
The icon not shows only in this browser.
This is the reason why don't upload any more info, opera is not compatible with share.

**In Chrome :** 
![image](https://user-images.githubusercontent.com/34350936/64068121-3a7bd500-cbf9-11e9-89a3-456e6a3f4e03.png)

**Comment by kesselb** [comment] 2019-08-31 19:22
Thanks for reporting this issue :+1: 

Looks like a duplicate of https://github.com/nextcloud/server/issues/16337.

**Closed by kesselb** 2019-08-31 19:22 UTC
Labels: 0. Needs triage, bug
