### ISSUE TITLE
[Feature Request] Search in link-shared directories

### ISSUE THREAD

**Issue by kaysond** [nextcloud/server#10750] opened 2018-08-19 22:54 UTC
Currently if a directory is shared via link, there is not an easy way to search the folder. Ctrl+F doesn't work well because the full contents are not loaded until you scroll to the bottom.

The search bar exists when logged in, it would be nice to extend that functionality to non logged-in users.

**Comment by MorrisJobke** [comment] 2018-08-20 13:00
Duplicate of #1794

**Closed by MorrisJobke** 2018-08-20 13:00 UTC
Labels: enhancement, feature: occ, feature: search, feature: sharing
