### ISSUE TITLE
Icons in Activity view ignore theming settings

### ISSUE THREAD

**Issue by despens** [nextcloud/server#15809] opened 2019-05-30 07:49 UTC
### Steps to reproduce
1. In admin settings under "Theming", change "Color" value to something not default nextcloud blue.
2. Enjoy navigation and all default icons in the new color. 
3. Access Activity view.
4. See icons for folders, archive files, etc displayed in default nextcloud blue.

### Expected behaviour

The icons in Activity view should look like all the other icons in nextcloud and respect the theming settings.

### Actual behaviour

Th icons in Activity view keep the default nextcloud blue look when that color is changed in Theming settings.

### Server configuration

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 15.0.7

**Where did you install Nextcloud from:** Docker

**Comment by skjnldsv** [comment] 2019-06-05 07:13
Duplicate of https://github.com/nextcloud/activity/issues/296

**Closed by skjnldsv** 2019-06-05 07:13 UTC
Labels: 0. Needs triage, bug, design, feature: activity and notification, feature: theming
