### ISSUE TITLE
Please enable sorting of the photos in the Photos section! Right now they cannot be sorted by date modified.

### ISSUE THREAD

**Issue by huzibizi** [nextcloud/server#24256] opened 2020-11-20 18:42 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When using the Nextcloud photos tab/app, there is no option to sort the files, like there is in the files section. So when viewing a large amount of photos it's impossible to find what you need. 

**Describe the solution you'd like**
Please add in an option so that you can sort the photos in the same way you would be able to sort files. Specifically please let the user sort by 'date modified'

**Describe alternatives you've considered**
Tried to edit the source code myself and ended up breaking everything, and had to reinstall my entire ubuntu server lol

**Comment by kesselb** [comment] 2020-11-20 18:52
Duplicate of https://github.com/nextcloud/photos/issues/397

**Closed by kesselb** 2020-11-20 18:52 UTC
Labels: 0. Needs triage, enhancement
