### ISSUE TITLE
error in uploading a file to smb shared folder

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#26547] opened 2021-04-13 18:30 UTC
I have several nextcloud 21.0.1 distributions and I have noticed that from android when I try to upload a file to a smb folder located on an external USB HD, the file does not load completely. for example a file of 69 megs is loaded 3 megs. if, on the other hand, I load in a non-external folder it smb the whole file is loaded completely.

**Comment by tigernero79** [comment] 2021-04-13 18:33
the problem is I have it with all synchronization applications, even if uplodo from the web. any uploaded file never turns out to be the right size. especially for zipped rar files. a 10 mega file becomes 1 mega once auplodado and therefore damaged

**Comment by j-ed** [comment] 2021-04-13 18:34
Duplicate of https://github.com/nextcloud/server/issues/26457

**Closed by j-ed** 2021-04-13 18:34 UTC
Labels: 0. Needs triage, bug
