### ISSUE TITLE
update fails 

### ISSUE THREAD

**Issue by tomkhlr** [nextcloud/server#28926] opened 2021-09-22 10:19 UTC
Update from 21.0.1 to 21.0.4 fails with the following exception:
Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.
Hardware raspberry pi 3b+

**Comment by szaimen** [comment] 2021-09-22 10:24
Duplicate of https://github.com/nextcloud/news/issues/1481

**Closed by szaimen** 2021-09-22 10:24 UTC

**Comment by cClaude** [comment] 2021-11-16 13:21
This is not really a duplicate.

Nextcloud server should not start migration at all or disable "news" application.
