### ISSUE TITLE
Deleted file expiry date

### ISSUE THREAD

**Issue by williambargent** [nextcloud/server#107] opened 2016-06-15 10:24 UTC
### Steps to reproduce
1. Deleted a file
2. View recycle bin
### Expected behaviour

Many installations have the ''trashbin_retention_obligation' => 30,'
In the bin it should show when the file will be automatically deleted; have a timer;
### Actual behaviour

Doesn't notify users the bin will be cleared.

Thoughts @nextcloud/designers 

![capture](https://cloud.githubusercontent.com/assets/11518756/16076520/982916fe-32eb-11e6-9c30-149c7fbbeee7.PNG)

**Comment by BernhardPosselt** [comment] 2016-06-15 10:28
Please don't use nextcloud/developers

**Comment by janklostermann** [comment] 2016-06-15 11:35
Very cool. Should be there!


Von unterwegs gesendet. Sent from my phone. 

-------- Ursprüngliche Nachricht --------
Von: William Bargent <notifications@github.com> 
Datum:15.06.2016  12:24  (GMT+01:00) 
An: nextcloud/server <server@noreply.github.com> 
Cc: janklostermann <jk@janklostermann.de>,Team mention <team_mention@noreply.github.com> 
Betreff: [nextcloud/server] Feature Request: Deleted file expiry date (#107) 

Steps to reproduce

Deleted a file
View recycle bin
Expected behaviour

Many installations have the ''trashbin_retention_obligation' => 30,'
In the bin it should show when the file will be automatically deleted; have a timer;

Actual behaviour

Doesn't notify users the bin will be cleared.

Thoughts @nextcloud/designers 
cc @nextcloud/developers

**Comment by jancborchardt** [comment] 2016-06-15 12:51
@janklostermann Github since recently has a »reaction« feature (in the top right behind the smilie face). If you want to express agreement, please use that one for »thumbs-up« like comments instead of leaving an actual comment which results in notifying everyone involved. Thanks! :)

**Comment by zinks-** [comment] 2016-06-15 16:32
I'm not a fan of this feature, because if you see something in the trash that shouldn't be there, you should take it out immediately.

I can't think of any scenario that would make me think "I still have 2 days to decide if I really want to lose this file". Having that timer implies that it's somehow "safe" to trash files.

**Comment by jancborchardt** [comment] 2016-06-16 08:51
@zinks- good point. I am also hesitant of adding another column there if it’s not absolutely necessary. The list view should not be a database dump. :)

**Comment by MorrisJobke** [comment] 2016-06-16 09:08
I second the argument of @zinks-. @williambargent What is the exact use case of this column for you?

**Comment by janklostermann** [comment] 2016-06-16 09:50
Transparency of what is going on (including an implicit warning, that 
this data will automatically be deleted soon - different to your Windows 
trash bin that seems to have ethernal life...)


Am 2016-06-16 um 11:08 schrieb Morris Jobke:
>
> I second the argument of @zinks- <https://github.com/zinks->. 
> @williambargent <https://github.com/williambargent> What is the exact 
> use case of this column for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nextcloud/server/issues/107#issuecomment-226429953>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ALEnw5RqqlUHOVWTB2r0emWg5rSi3kM3ks5qMRJ1gaJpZM4I2Nd->.
>

-- 
Jan Klostermann
- The Agile Management Sounding-Board -
Systems Engineer & Mediator
Am Isarkanal 24/15
81379 München

Tel.: +49-89/74563382
Mobil: +49-179/4628819
Sip: +49-89/21551663 <sip:08921551663@sipgate.de>
Skype: jan.klostermann <callto://jan.klostermann/>
Threema: P58VSJUY <threema://add?id=P58VSJUY>
Email: jk@janklostermann.de <mailto:jk@janklostermann.de>
Netzwerke: Xing <https://www.xing.com/profile/Jan_Klostermann>, LinkedIn 
<http://de.linkedin.com/in/janklostermann>

**Comment by williambargent** [comment] 2016-06-16 10:34
Users are unaware they won't be able to recover a file, I understand that they deleted it but its nice to know when the recycle bin will be automatically emptied.

**Comment by jakobsack** [comment] 2016-06-16 11:00
Well, we could add a text at the top of the page stating "Files in the trash bin will be unrecoverable deleted after -x- days." Combined with the "deleted"-column the user is able to see which files are near expiration. In my opinion this is a good compromise because it warns the user but does not clutter the interface too much.

**Comment by jancborchardt** [comment] 2016-06-16 12:07
Well, this is only the case for certain setups. The assumption in the original post says:

> Many installations have the ''trashbin_retention_obligation' => 30,'

But since this is not the default setting, it’s unlikely to be »many« and more likely to be »some« or even »a few«.

**Comment by jakobsack** [comment] 2016-06-16 12:12
> Well, this is only the case for certain setups

Of course there should be no text if there is no expiration date.

**Comment by MorrisJobke** [comment] 2016-06-16 12:13
> Of course there should be no text if there is no expiration date.

Then the expiration is also calculated on how much storage is used (in relation to the quota). If this is reached the files are removed from the trashbin that are in there for the longest time.

**Comment by jakobsack** [comment] 2016-06-16 12:14
ok, in this case my proposal is pointless

**Comment by janklostermann** [comment] 2016-06-16 12:27
In these cases the column could disappear...


Von unterwegs gesendet. Sent from my phone. 

-------- Ursprüngliche Nachricht --------
Von: Jan-Christoph Borchardt <notifications@github.com> 
Datum:16.06.2016  14:07  (GMT+01:00) 
An: nextcloud/server <server@noreply.github.com> 
Cc: janklostermann <jk@janklostermann.de>,Mention <mention@noreply.github.com> 
Betreff: Re: [nextcloud/server] Feature Request: Deleted file expiry date
  (#107) 

Well, this is only the case for certain setups. The assumption in the original post says:

Many installations have the ''trashbin_retention_obligation' => 30,'

But since this is not the default setting, it’s unlikely to be »many« and more likely to be »some« or even »a few«.

**Comment by williambargent** [comment] 2016-06-16 13:36
I wasn't area of that so yeah seems silly having it, if the value is set I still think it is worth it being mentioned somewhere on the page.

**Comment by coderkun** [comment] 2017-05-14 13:37
If there are other triggers that might delete files in the trash permanently (e. g. storage exceeded), showing the expiration date will be misleading because it is only one of several triggers. A user might think that a file will not be deleted before that date—which is not true if one of the other triggers take effect.

But a message telling the user that there are triggers that might delete files permanently—which ones and in case of the expiration date the max. days—would be great. Especially since the administrator is setting and controlling these settings and not the user itself.

**Comment by szaimen** [comment] 2021-05-21 12:25
I'm closing this issue due to inactivity. Please reopen if you still want to implement this.

**Comment by enoch85** [comment] 2021-05-21 14:36
Cool feature!

**Comment by CarlSchwan** [comment] 2022-09-01 12:19
Closing since this is a feature request and there is doubt about its entire usability of it. Also, this is not trivial to implement.

If someone want to implement it, PR welcome and we can discuss details there

**Closed by CarlSchwan** 2022-09-01 12:19 UTC
Labels: enhancement, 1. to develop, feature: trashbin
