### ISSUE TITLE
[Bug]: Share link not displayed after creation when end date is enforced

### ISSUE THREAD

**Issue by lencell** [nextcloud/server#43720] opened 2024-02-21 10:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you create a share link for a file or folder and creation date is enforced, the UI do not refresh to show you the sharing link, you still have the share link option displayed:
![image](https://github.com/nextcloud/server/assets/42672244/4856e449-cd3c-4e42-a151-ab6f93aa3b24)

If you refresh the page then it will show up properly:
![image](https://github.com/nextcloud/server/assets/42672244/1b411578-8449-4a39-8758-87c8f87bb92b)

### Steps to reproduce

1. Set up an expiration date for shared link
![image](https://github.com/nextcloud/server/assets/42672244/41c284b3-47df-4a95-a8cc-a17ea1331de1)

3. Enforce it
4. Try to share a file or folder via share link

### Expected behavior

Share link UI should refresh and show the option to copy the link right away

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "record1.domain.tld",
            "record2.domain.tld."
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/172.16.100.157",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "record2.domain.tld",
        "overwritewebroot": "\/",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "default_phone_region": "FR",
        "skeletondirectory": "\/home\/default",
        "activity_expire_days": 30,
        "app_install_overwrite": [
            "activitylog",
            "flowupload"
        ],
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "enable_previews": true,
        "share_folder": "\/partages\/"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - activitylog: 0.0.1
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - forms: 4.1.1
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - registration: 2.3.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - user_usage_report: 1.12.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 6.0.0
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment] 2024-02-21 12:24
cc @Fenn-CS

**Comment by LM-vb** [comment] 2024-02-23 08:38
This happens also if usage of a password is enforced. (NC 28.0.2)

**Comment by LM-vb** [comment] 2024-03-07 13:41
This is solved in NC 28.0.3 if usage of a password is enforced.

@lencell: can you check if this is also solved in your case?

**Comment by ElSi-DVT** [comment] 2024-03-13 14:33
This problem still exists in NC 27.1.7

**Comment by ElSi-DVT** [comment] 2024-04-02 13:11
This problem still exists in NC 27.1.8

**Comment by Fenn-CS** [comment] 2024-04-02 14:56
Duplicate of : https://github.com/nextcloud/server/issues/44032

**Closed by Fenn-CS** 2024-04-02 14:56 UTC
Labels: bug, 0. Needs triage, 28-feedback
