### ISSUE TITLE
occ files:scan --all throws an exeption for one user

### ISSUE THREAD

**Issue by guzi42** [nextcloud/server#15149] opened 2019-04-18 07:11 UTC
### Steps to reproduce
1.occ files:scan --all  (or scan only the user with this issue)
2.
3.

### Expected behaviour
finishing without any exeption

### Actual behaviour
"Exception during scan" at one user

Starting scan for user 72 out of 362 (Didiot)
Exception during scan: 
#0 [internal function]: OCA\Files_Sharing\External\Storage->checkStorageAvailability()
#1 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)                                                          
#2 [internal function]: OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)                                                                        
#3 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)                                                          
#4 /var/www/owncloud/apps/files_sharing/lib/External/Scanner.php(89): OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)                          
#5 /var/www/owncloud/apps/files_sharing/lib/External/Scanner.php(44): OCA\Files_Sharing\External\Scanner->scanAll()                                                  
#6 /var/www/owncloud/lib/private/Files/Utils/Scanner.php(245): OCA\Files_Sharing\External\Scanner->scan('', true, 3)                                                 
#7 /var/www/owncloud/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/Didiot', true, NULL)                                                       
#8 /var/www/owncloud/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('Didiot', '/Didiot', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)                                                                                                                                             
#9 /var/www/owncloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                        
#10 /var/www/owncloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                               
#11 /var/www/owncloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                 
#12 /var/www/owncloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                       
#13 /var/www/owncloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                              
#14 /var/www/owncloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                     
#15 /var/www/owncloud/console.php(96): OC\Console\Application->run()                                                                                                 
#16 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')                                                                                                    
#17 {main}                                                                                                                                                           
Starting scan for user 73 out of 362 (Drabant)

### Server configuration
VMWare image, 6 GB memory, 2vCPUs
**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
apache2     2.4.29-1ubuntu4.6
**Database:**
mysql    5.8+1.0.4
**PHP version:**
php7.2    7.2.15-0ubuntu0.18.04.2
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.7
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from owncloud
**Where did you install Nextcloud from:**
Downloaded the migrator, upgrated via admin page / occ upgrade
**Signing status:**

<summary>All checks passed.</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.0
  - dav: 1.8.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.2
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.4
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - user_usage_report: 1.1.1
  - workflowengine: 1.5.0
Disabled:
  - announcementcenter
  - circles
  - encryption
  - external2
  - external_old
  - files_external
  - files_fulltextsearch
  - files_mv
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - ojsxc
  - support
  - tasks

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloudde.treofan.com",
            "owncloud.treofan.com",
            "owncloudus.treofan.com",
            "owncloudmx.treofan.com",
            "10.3.2.191"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/owncloudde.treofan.com",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 2,
        "debug": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "ldapUserCleanupInterval": 51,
        "enable_certificate_management": true,
        "appstore.experimental.enabled": true,
        "3rdpartyroot": "\/var\/www\/owncloud\/3rdparty",
        "3rdpartyurl": "\/3rdparty",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mysql.utf8mb4": true
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
</details>

#### Nextcloud log (data/nextcloud.log)
no relevant data
<details>
<summary>Nextcloud log</summary>

**Comment by alexhorn** [comment] 2019-04-19 13:35
I have the same problem with the newest NextCloud docker container:

	Starting scan for user 1 out of 5 (redacted)
	Starting scan for user 2 out of 5 (redacted)
	Starting scan for user 3 out of 5 (redacted)
	Starting scan for user 4 out of 5 (redacted)
	Exception during scan:
	#0 [internal function]: OCA\Files_Sharing\External\Storage->checkStorageAvailability()
	#1 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)
	#2 [internal function]: OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
	#3 /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php(506): call_user_func_array(Array, Array)
	#4 /var/www/html/apps/files_sharing/lib/External/Scanner.php(89): OC\Files\Storage\Wrapper\Wrapper->__call('checkStorageAva...', Array)
	#5 /var/www/html/apps/files_sharing/lib/External/Scanner.php(44): OCA\Files_Sharing\External\Scanner->scanAll()
	#6 /var/www/html/lib/private/Files/Utils/Scanner.php(245): OCA\Files_Sharing\External\Scanner->scan('', true, 3)
	#7 /var/www/html/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/redacted', true, NULL)
	#8 /var/www/html/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('redacted', '/redacted', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
	#9 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#10 /var/www/html/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#11 /var/www/html/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#12 /var/www/html/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#13 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#14 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#15 /var/www/html/console.php(96): OC\Console\Application->run()
	#16 /var/www/html/occ(11): require_once('/var/www/html/c...')
	#17 {main}
	Starting scan for user 5 out of 5 (redacted)
	+---------+-------+--------------+
	| Folders | Files | Elapsed time |
	+---------+-------+--------------+
	| 595     | 3858  | 00:00:21     |
	+---------+-------+--------------+

**Comment by guzi42** [comment] 2019-05-29 11:57
still the same issue with 16.0.1

**Comment by skjnldsv** [comment] 2019-06-03 10:45
cc @blizzz

**Comment by j-ed** [comment] 2019-06-03 11:17
@guzi42 I had a similar problem a while ago and found out, that a file name which contained a '+'-sign was causing problems. To identify the file I executed `./occ files:scan -vvv --path=<PATH> <USER>` until I identified the directory the command stopped working and checked the file names for some non-standard characters. I might be possible that this will help you identifying the root cause of the problem.

**Comment by syntron** [comment] 2019-08-07 19:32
I have the same problem on uploading files via webdav - the error (nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php#506) seems to occure for each uploaded file.

**Comment by skjnldsv** [comment] 2020-08-25 09:31
Make sure the direct full path to user exists `appdata/{USER}/files`

As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:31 UTC
Labels: 0. Needs triage, bug
