### ISSUE TITLE
Shares don't appear in destination account and duplicate destination users listed

### ISSUE THREAD

**Issue by salavursa** [nextcloud/server#37056] opened 2023-03-06 13:26 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My application supports NextCloud storage with its features. I login users with authFlowV2, simply get appPassword and use it in next requests via basicAuth. But whenever I try to share file with other account something veird happens: I can see share appearing in native NextCloud UI (proper username, permissions, everything is ok), but file doesnt appear in collaborators account. Further more I can share tjis file from native UI and then you see 2 same users in collaborators tab. See attached screenshot

![image](https://user-images.githubusercontent.com/67692229/223122213-fbb67d4f-5ccd-4c91-826a-676d9131017e.png)

In my application I send all the same data as the native client, but result is different (the only differ is that i use appPassword for fileowner)

### Steps to reproduce

1. login user with login flow v2, get appPassword (artemTest01)
2. share file to other user (artemTest02)
`curl --location --request POST 'http://nextcloud.com/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json' --header 'OCS-APIREQUEST: true' --header 'Authorization: Basic YXJ0ZW1UZXN0MDM6NXkyR0VGNFhnR0ozODNPZk01cE1MSzFRUHRNbDdGUE84U2JJMk9YdERBOWVudjBTOUpqWk5ya3BKa1dTQ01hNXlybjVnUW9B' --header 'Content-Type: application/json' --data-raw '{"attributes":"[]","password":null,"path":"/new dwg test (copy 2).dwg","permissions":19,"shareType":0,"shareWith":"artemtest02"}'`
3. After you will see user in collaborators, but he wont get the file
![image](https://user-images.githubusercontent.com/67692229/223122496-26864f4c-d693-420e-ac7a-3dc2c8808922.png)
5. Untill you add him manually, and see 2 same users 
![image](https://user-images.githubusercontent.com/67692229/223122597-9b569aa0-8ef6-4692-8e4f-5a98bf757f02.png)

### Expected behavior

Object should be shared properly

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

**Comment by szaimen** [comment] 2023-03-06 13:32
Hi, which nc version?

**Comment by salavursa** [comment] 2023-03-10 10:21
@szaimen 25 fresh

**Comment by szaimen** [comment] 2023-03-10 10:22
which 25 version?

**Comment by salavursa** [comment] 2023-03-10 11:40
@szaimen Sorry i've mistaken 24.0.4

**Comment by szaimen** [comment] 2023-03-10 11:44
Can you try to upgrade to the latest patch version and check if thst improves things?

**Comment by salavursa** [comment] 2023-03-10 12:08
@szaimen the version is 25.03, sorry I checked wrong instance.

**Comment by salavursa** [comment] 2023-06-20 07:47
@szaimen Did anyone look into this issue?

**Comment by joshtrichards** [comment] 2023-08-30 14:05
I think the lack of a title the issue may have caused it to be overlooked. Fixed. :)

**Comment by joshtrichards** [comment] 2023-08-30 18:23
Duplicate of #36088

**Closed by joshtrichards** 2023-08-30 18:23 UTC
Labels: bug, feature: sharing, 0. Needs triage, 25-feedback
