### ISSUE TITLE
Folders don't load, files can't be download files after update to NC14

### ISSUE THREAD

**Issue by Elektronenhirn108** [nextcloud/server#11207] opened 2018-09-13 17:56 UTC
### Steps to reproduce
1. Login 
2. Open a folder
3. Download a file

### Expected behaviour
File should download
Folder should load
### Actual behaviour
Folders doesn't load
Error when I am trying to download a file
Wierd data path shown  next to the house
remote.php/dav/files/USERNAME/myfolder

But syncing with my macOS client works fine. 
Only the web interface is broken.

On my admin-user, there isn't any problem with loading folders or downloading a file.
But the scss and no cache error also happens in the admin-user
Updated by changing the version in Wonderfall/nextcloud Dockerfile and rebuilt it.
### Server configuration

**Operating system**:
Debian 9
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
14.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
13.0.6
**Where did you install Nextcloud from:**
docker image from wonderfall

### Client configuration
**Browser:**
Safari, Edge, Chrome
**Operating system:**
macOS, Windows 10
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
,"message":"Scss is disabled for \/nextcloud\/core\/css

,"message":"No cache entry found for

</details>

**Comment by Elektronenhirn108** [comment] 2018-09-13 19:58
Small update, but still no solution found!

Link of my home folder:
https://mydomain.com/apps/files/?dir=/&fileid=29

If I go into my testfolder, this is the new link:
https://mydomain.com/apps/files/?dir=/remote.php/dav/files/MYUSER/testfolder&fileid=119337

Now, I remove the webdav-part of the link
https://mydomain.com/apps/files/?dir=/testfolder&fileid=119337

It works. So something with the links go wrong.
So I believe that is the same issue, when I am trying do download a file.

**Comment by sebas891** [comment] 2018-11-21 13:41
I also have the same problem on a NC (14) installation.  It doesn't happen to all the users on the instance. 

@Elektronenhirn108 do you have a federation activated for your installation?

**Comment by Elektronenhirn108** [comment] 2018-11-21 13:51
No, federation ist completly disabled in my cloud.

On which version are you at the moment?
The update to 14.0.1 (or 2, not sure) solved my issue.

**Comment by sebas891** [comment] 2018-11-21 13:57
ok.

I'm on Nextcloud 14.0.0, I see if I can upgrade to 14.0.3 soon and comment here about the situation.

Many thanks for your fast response.

**Comment by Elektronenhirn108** [comment] 2018-11-21 14:02
No problem, good luck with your update.

**Comment by sebas891** [comment] 2018-11-22 14:06
I confirm that upgrading to the latest version (14.0.3 as of now), has solved the issue for us.

**Comment by skjnldsv** [comment] 2020-04-10 07:23
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 07:23 UTC
Labels: 0. Needs triage, bug
