### ISSUE TITLE
nextcloud upgrade to 16.01

### ISSUE THREAD

**Issue by bluecrocodile** [nextcloud/server#15695] opened 2019-05-22 22:09 UTC
This is the returned error message:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp BIGINT UNSIGNED NOT NULL, started SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll_token VARCHAR(255) NOT NULL, login_token VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, private_key TEXT NOT NULL, client_name VARCHAR(255) NOT NULL, login_name VARCHAR(255) DEFAULT NULL, server VARCHAR(255) DEFAULT NULL, app_password VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX poll_token (poll_token), UNIQUE INDEX login_token (login_token), INDEX timestamp (timestamp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by kesselb** [comment] 2019-05-23 09:48
Looks like a duplicate of https://github.com/nextcloud/server/issues/15058 to me. Would you mind to try the suggested solution?

**Closed** 2019-05-29 22:41 UTC
Labels: 0. Needs triage, bug, needs info
