### ISSUE TITLE
NC21.01 | error PHP for /var/www/nextcloud/lib/public/Log/RotationTrait.php

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/server#26744] opened 2021-04-25 11:01 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
no logged error

### Actual behaviour
Log full of combination of following  **error PHP**

**Error**: filesize(): stat failed for /var/data/nextcloud/flow.log at /var/www/nextcloud/lib/public/Log/RotationTrait.php#62

1. `*<<closure>>*`
   OC\Log\ErrorHandler::onError()

2. */var/www/nextcloud/lib/public/Log/RotationTrait.php* *- line 62:*
   filesize()

3. */var/www/nextcloud/apps/workflowengine/lib/BackgroundJobs/Rotate.php* *- line 49:*
   OCA\WorkflowEngine\BackgroundJobs\Rotate->shouldRotateBySize()

4. */var/www/nextcloud/lib/private/BackgroundJob/Job.php* *- line 52:*
   OCA\WorkflowEngine\BackgroundJobs\Rotate->run()

5. */var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php* *- line 59:*
   OC\BackgroundJob\Job->execute()

6. */var/www/nextcloud/cron.php* *- line 128:*
   OC\BackgroundJob\TimedJob->execute()

### Server configuration
see #26743

**Comment by acsfer** [comment] 2021-04-25 11:57
Duplicate of https://github.com/nextcloud/server/issues/25813

**Closed by acsfer** 2021-04-25 11:57 UTC
Labels: 0. Needs triage, bug
