### ISSUE TITLE
[Bug]: Rightclick with many files scrolls to top of the page

### ISSUE THREAD

**Issue by nc-fkl** [nextcloud/server#43974] opened 2024-03-04 10:09 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When scrolled down in the file list a right click scrolls the list up completely whenever the fileslist got multiple files and is scrollable

### Steps to reproduce

1. Open files where multiple files are located and is scrollable on y axis
2. Scroll to the bottom of the filelist
3. Right click
4. Scrolls automatically to the top of the page and right-click menu disappears

### Expected behavior

Right click should just display the right-click menu instead of scrolling up

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

[screenrec.webm](https://github.com/nextcloud/server/assets/149385388/9c8e2d65-e073-485c-a02f-8472670113ed)

**Comment by SystemKeeper** [comment] 2024-03-04 10:13
Duplicate of 
- https://github.com/nextcloud/server/issues/43300

**Closed by SystemKeeper** 2024-03-04 10:13 UTC
Labels: bug, 0. Needs triage, feature: files, ux
