### ISSUE TITLE
updater does not work on FreeBSD

### ISSUE THREAD

**Issue by jiml8** [nextcloud/server#3147] opened 2017-01-18 22:34 UTC
### Steps to reproduce
1. Install on FreeBSD.  I use Nas4Free.
2. Run updater
3. 

### Expected behaviour
Tell us what should happen
Should give some display then update to latest version
### Actual behaviour
Tell us what happens instead
screen says "updater initializing" and nothing else.

### Server configuration
**Operating system**:
Nas4Free (FreeBSD 11)
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11.0.0 to 11.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
attempted update

According to the log (which I have to access from a shell on the Nas4Free instance due to bug in the PHP web UI...see my next post) the updater is trying to access /proc/meminfo which is a linux-only thing and not supported on FreeBSD.

There are a variety of ways to get memory info on FreeBSD.  sysctl -a | grep mem will very roughly equate with cat /proc/meminfo

**Comment by josh4trunks** [comment] 2017-01-19 01:10
I can confirm I was having an issue with the updater app as well on my FreeBSD system.

**Comment by nickvergessen** [comment] 2017-01-19 15:20
This should be caused by https://github.com/nextcloud/serverinfo/pull/76/files and will be fixed with 11.0.2

**Closed by nickvergessen** 2017-01-19 15:20 UTC

**Comment by josh4trunks** [comment] 2017-01-19 16:22
why is this closed before the fix is merged?
