### ISSUE TITLE
Redirect root favicon.ico requests

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#24821] opened 2020-12-22 18:30 UTC
Browsers are very chatty and tend to always lookup for `/favicon.ico`.
In the webserver, this logs a 404 for each request.

### Solution
Insert a line like 

`RewriteRule ^favicon\.ico$ /core/img/favicon.ico [L,R=301]`

in the `.htaccess`

**Comment by kesselb** [comment] 2020-12-22 19:32
> Browsers are very chatty and tend to always lookup for /favicon.ico

I disagree. Just tested it with Firefox and Chrome. If `<link rel="icon" href="/core/img/favicon.ico"> ` is present they don't request `/favicon.ico`.

**Comment by acsfer** [comment] 2020-12-22 20:41
Request any file like a CSS or a JS directly:

![image](https://user-images.githubusercontent.com/12234510/102930965-c0cac300-449d-11eb-8dc1-971ae5ae830b.png)

Apache log:

> [Sun Dec 20 15:42:36 2020] [core:info] [pid 61562:tid 139881967769344] [client x.x.x.x:50908] AH00128: File does not exist: /usr/www/users/czd/favicon.ico

https://webdesign.tutsplus.com/tutorials/prevent-automatic-favicon-requests--cms-34762
https://www.cisco.com/c/en/us/support/docs/security/web-security-appliance/117995-qna-wsa-00.html
https://bugzilla.mozilla.org/show_bug.cgi?id=260500
https://bugs.chromium.org/p/chromium/issues/detail?id=39402
Etc...

**Comment by kesselb** [comment] 2020-12-22 21:06
> Request any file like a CSS or a JS directly:

Because `<link rel="icon">` is not set. Usually those requests are not requested directly.

**Comment by acsfer** [comment] 2020-12-23 09:39
Well, something is, as the Apache logs are full of it without that rule 🤔

**Comment by elsiehupp** [comment] 2021-01-24 22:59
@acsfer I figured it might be easy to add a redirect to the default `.htaccess` file, so I threw something together. If you want you could checkout the [branch](https://github.com/elsiehupp/server/tree/redirect-301-favicon-ico) and test it, then leave feedback on the [pull request](https://github.com/nextcloud/server/pull/25307).

**Comment by elsiehupp** [comment] 2021-01-25 21:59
@kesselb I checked to see if root-directory `favicon.ico` worked on my Nextcloud installation, and it returns a 404 error for me, too. (I don't know if browsers are are actually calling it, though.)
```
% curl -I https://cloud.elsiehupp.com/favicon.ico
HTTP/1.1 404 Not Found
```
The thing is, I'm running [`nextcloud-snap`](https://github.com/nextcloud/nextcloud-snap), so almost all of the server configuration is fully encapsulated. That is, the default Apache configuration for `nextcloud-snap` is part of the `snap` package, so even if it's not in scope here, it's in-scope there.

@acsfer if, per chance, you're running `nextcloud-snap`, could you consider [opening a new issue over there](https://github.com/nextcloud/nextcloud-snap/issues/new/choose) and referencing this issue? Thanks!

**Comment by acsfer** [comment] 2021-01-26 07:37
Not running snap.

**Comment by elsiehupp** [comment] 2021-01-26 11:45
Hrm! Well, I did run into something interesting in the `nextcloud-snap` issues: apparently `.htaccess` issues are kind of, like, a thing there, due to the fact that `.htaccess` is strictly read-only (and I think just vanilla, from Apache).

https://github.com/nextcloud/nextcloud-snap/issues/52
https://github.com/nextcloud/nextcloud-snap/issues/86
https://github.com/nextcloud/nextcloud-snap/issues/412

`.htaccess` is imported by `httpd.conf` here:

https://github.com/nextcloud/nextcloud-snap/blob/6e501950328184d1b7f6297f540f0cf3c6774956/src/apache/conf/httpd.conf#L118

Perhaps plausibly additional directives could be added to `httpd.conf` itself, but I'm not 100% sure. I don't have a lot of experience with Apache. One thing that seems to be the case is that `nextcloud-snap` doesn't like sharing a server with other websites, as in [Apache Virtual Hosts](https://httpd.apache.org/docs/current/vhosts/index.html), which I think traces back to `.htaccess` being vanilla and read-only.

**Comment by szaimen** [comment] 2021-06-22 14:02
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-22 14:02 UTC
Labels: 0. Needs triage, bug
