### ISSUE TITLE
HTML files are downloaded as txt files in Safari

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#1833] opened 2016-10-20 17:11 UTC
I did not have a closer look into it, yet. Maybe something happing to the mime types. The error in the last line of the browser console log, occurs when clicking `download`.
Could reproduce on two different Macs.
- [x] @ccoenen Can you add the Server configuration?
### Steps to reproduce
1. Download a html file in the files app while using Safari
2. Look for the downloaded file / open it
### Expected behaviour

File should be downlaod as it is stored on the Nextcloud  
`exmaple.html`
### Actual behaviour

File is downloaded, but has the extension .txt added at the end  
`example.html.txt`
### Client configuration

**Browser:** Safari 10.0

**Operating system:** OSX El Capitan 10.11.6
#### Browser log

<details>
<summary>

Browser log</summary>

```
[Warning] Invalid CSS property declaration at: ; (styles.css, line 20)
[Warning] Unexpected CSS token: : (comments.css, line 73)
[Warning] Invalid CSS property declaration at: * (select2.css, line 10)
[Warning] Unexpected CSS token: : (select2.css, line 55)
[Warning] Unexpected CSS token: : (select2.css, line 67)
[Warning] Unexpected CSS token: : (select2.css, line 195)
[Warning] Unexpected CSS token: : (select2.css, line 277)
[Warning] Unexpected CSS token: : (select2.css, line 289)
[Warning] Unexpected CSS token: : (select2.css, line 532)
[Log] JQMIGRATE: Migrate is installed, version 1.4.0 (jquery-migrate.min.js, line 2)
[Error] Failed to load resource: Das Laden des Frames wurde unterbrochen (P3_161012_Aufgabe01-HTML.html, line 0)
```

</details>

**Comment by ccoenen** [comment] 2016-10-20 20:54
## Server configuration

Operating system: Ubuntu 16.04
Web server: apache from packages (2.4)
Database: MySQL / Mariadb
PHP version: 7
Nextcloud version: 10.0(.0)
Updated from an older Nextcloud/ownCloud or fresh install: Fresh Install
Where did you install Nextcloud from: Zipfile
Signing status: ?
List of activated apps:
- regular complement plus calendar (no contacts)

The content of config/config.php:

```
<?php
$CONFIG = array (
  'instanceid' => 'redacted',
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' =>
  array (
    0 => 'redacted',
    1 => 'redacted',
  ),
  'datadirectory' => '/var/www/nextcloud-data',
  'overwrite.cli.url' => 'https://redacted',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'nextcloud_media',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'redacted',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'allow_user_to_change_display_name' => true,
  'remember_login_cookie_lifetime' => 2592000,
  'session_lifetime' => 604800,
  'skeletondirectory' => '',
  'loglevel' => 0,
);
```

Are you using external storage: nope
Are you using encryption: no
Are you using an external user-backend: no

**Comment by jakehobbs** [comment] 2019-07-25 20:03
I submitted PR #16546 for this.

**Comment by jakehobbs** [comment] 2019-07-26 01:06
Please disregard the last PR. 

See [#16546] for new PR.

**Comment by onehappycat** [comment] 2019-12-03 18:10
With Nextcloud versions 17.0.1 and 18.0.0 Alpha and Safari 13.0.3, I am unable to reproduce this issue.

If other people confirms this, perhaps it is no longer an issue and can be closed?

**Comment by jneplokh** [comment] 2020-09-11 22:00
Yeah this doesn't seem to be an issue anymore, closing.

**Closed by jneplokh** 2020-09-11 22:00 UTC
Labels: 1. to develop, bug, feature: files, good first issue

**Comment by teledyn** [comment] 2024-11-26 18:24
This has started happening again with the upgrade to 29.0.6, my html files are spontaneously back to downloading as text.
