### ISSUE TITLE
Preview Gallery not working on some TIF and TIFF

### ISSUE THREAD

**Issue by vindic** [nextcloud/server#12876] opened 2018-12-06 09:45 UTC
After i have migrated a previous installation of Nextcloud 14.0.2 from Ubuntu 16.04 to Ubuntu 18.04 and then NC 14.0.4 the preview for some TIF images wasn't working.

-----------------------------------------------------------

NextCloud version : 14.0.4
Operating system and version : Ubuntu 18.04
Apache : 2.4
PHP version : 7.2
ImageMagick : 6.9.7-4

-----------------------------------------------------------

I have first posted the issue in Support Section : https://help.nextcloud.com/t/nc14-problems-with-preview-tif-ai-raw-images-on-new-installation/42445 

Files having issues :

1) the TIF images containing .tiff extension 

2) The TIF images having a MimeType recognized as image/x -dcraw

I don't know if the causes of this malfunctions is the 14.0.4 NC update or the new Imagick Library installed by default on Ubuntu 18.04

---------------------------------

The first fix was to modify the PreviewManager.php  line 368

adding an image magick provider for the TIFF files =>

`'TIFF'	=> ['mimetype' => '/image\/tif/', 'class' => Preview\TIFF::class]`

The second fix was to add a provider for the mimetype 'image/x-dcraw'

`$this->registerCoreProvider(Preview\TIF::class, '/image\/x-dcraw/');`

I have to add it as a a registerCoreProvider because the imagickProviders is using only one extension by mimetype.

**Comment by ChristophWurst** [comment] 2019-04-30 08:04
Could you submit a PR if that is a bugfix?

**Comment by vindic** [comment] 2019-05-06 06:00
I will not submit a PR because this is a quick and dirty fix.

I don't understand why the extension *.tiff is not working anymore, it was working before and if this bug is generic or if it's only on my server.

**Comment by james-cook** [comment] 2019-06-12 21:46
I can at least confirm the error with NC15.
PDF file work when enabled as described (config.php from sample config) AND policy.xml changes for PDF for ImageMagick etc. etc.
But unclear how to get tiff to work.

 'enabledPreviewProviders' => array(
        'OC\Preview\PNG',
        :
        :
        'OC\Preview\MarkDown',
        'OC\Preview\SVG',
        'OC\Preview\TIFF',

**Comment by schniepp** [comment] 2019-09-05 16:23
I also have a problem viewing TIFF files in nextcloud now (v16), when it was not a problem in earlier versions. 
Problem #1: when I click on them, TIFFs are now downloaded instead of watched in the viewer.
Problem #2: no thumbnails are being created in either "file" or "grid" viewing modes.

Interestingly, the previews of TIFFs that appear to have been created by earlier nc versions are still shown. Also, if I use the (old) gallery app to view pictures, I can browse through the old folders with existing previews. From the gallery app, I can even get the TIFFs to be displayed in a window-filling manner by clicking on them. However, if I go to a newer folder with no previews, this files don't even show up in the gallery app. 

In some respects I liked the old gallery app better. But currently there is quite a confusion between gallery app and the other two view modes (list/grid). I am also not sure what we call "preview" — is it the thumbnail that's displayed in grid/list modes, or is it what I get when I click on an image so that it's displayed in window size? (I am not calling it full-size, as I am not sure whether these are actually down-scaled versions of the pictures.)

In general, I find matter quite messy in this respect at present.

**Comment by vindic** [comment] 2019-11-21 08:02
Just made the migration from Nc 16.01 to Nc 17.01  and the bug is still present.

The fix seems the same.

**Comment by d--j** [comment] 2019-11-22 17:54
I think the root cause is that something wrongly detects the MIME type of a .TIF file as `image/x-dcraw` instead of `image/tiff`.
If I upload the same file with file extension `.TIF` I get the MIME type `image/x-dcraw`. If I change the file extension to `.tiff` the MIME type is the correct `image/tiff`.

Here is a test file: [test-tiffs.zip](https://github.com/nextcloud/server/files/3880760/test-tiffs.zip)

**Comment by kesselb** [comment] 2019-12-27 23:02
Hey. I'm not sure how to reproduce this issue. Do you still see this issue?

1. I've uploaded the test files provided by @d--j to my nextcloud (18) instance. The mime type was correct for both files. Nextcloud contains the mapping by default (since 2015) that will assign `image/tiff` to files with `.tif` or `.tiff` extension.

https://github.com/nextcloud/server/blob/b7f93cc56bb1f7d9383165ebf29111fbd2bd6ab1/resources/config/mimetypemapping.dist.json#L174-L175

2. By default previews are not enabled for `image/tiff`. To enable previews add `'OC\Preview\TIFF'` to `enabledPreviewProviders` in `config.php` (imagick extension for php is enabled on my system).
3. I see previews for both files.
![image](https://user-images.githubusercontent.com/3902676/71535226-b0bce980-2904-11ea-837e-110dfa0b8da8.png)

Opening the files with viewer (default app for viewing files since Nextcloud 17) do not work. Files are downloaded. This seems to work for a png file. A enhancement issue is already filled over here: https://github.com/nextcloud/viewer/issues/229

**Comment by d--j** [comment] 2020-01-02 18:42
Hi @kesselb 

while compiling the data for the issue template I stumbled upon the active app [Camera RAW Previews](https://apps.nextcloud.com/apps/camerarawpreviews).  Deactivating this app fixes TIF-previews for me.

I have opened an issue there: ariselseng/camerarawpreviews#39

For me at least TIF preview is working as it should now (of course after adding `OC\Preview\TIFF` as a preview provider. @schniepp @vindic @james-cook do you also have the app `camerarawpreviews` active? Does deactivating it helps?

We have a little app that registers TIFF files handling for the `viewer` app (via the nextcloud previews). Somehow that is necessary despite nextcloud/viewer#33 being merged.

**Comment by schniepp** [comment] 2020-01-04 19:52
@d--j: Yes, I had `Camera RAW Previews` installed, and disabling it changes the behavior.

**Comment by mbc0** [comment] 2020-01-11 02:25
Hi,

I have a fresh install and have the problem where thumbnails for tiff's are not being displayed (jpeg's are fine) I do not have any apps installed, can anyone please point a "noob" in the right direction to get this working, even if it is a dirty fix?

Many Thanks in advance!

**Comment by d--j** [comment] 2020-01-11 05:29
@kesselb I think you can close this issue.

@mbc0 Just install the **[Camera RAW Previews](https://apps.nextcloud.com/apps/camerarawpreviews)** App – in its newest version it will give you TIFF thumbnails without any configuration changes (only if your server has the Imagick PHP extension installed).

If your server does not have PHP's Imagick extension installed you are out of luck.

Anyways, you should probably move your question over to https://help.nextcloud.com/ – this here is the wrong place to ask questions.

**Comment by kesselb** [comment] 2020-01-11 10:31
Thanks @d--j :+1:

**Closed by kesselb** 2020-01-11 10:31 UTC
Labels: 0. Needs triage, needs info

**Comment by james-cook** [comment] 2020-01-11 20:01
My problem still exists - but I think it could be a wider issue with MY system - some kind of clash between gd and imagemagick. 

I am getting strange errors even trying to debug the issue in ./lib/private/Preview/Bitmap.php
In particular errors like:

> php ImagickException:
> JPEG parameter struct mismatch: library thinks size is 520, caller expects 512

And in other tests a memory allocation errors...
As the original system is full of legacy websites that are all very fragile I've decided to move my testing of this issue to a new droplet and using docker for more effective control of the testing environment.

Currently using https://github.com/ReinerNippes/nextcloud_on_docker on a 16.04 ubuntu droplet.
So far TIFFs are still not converted... but I'm just starting to test.

I'll comment here if I find anything relevant.

**Comment by james-cook** [comment] 2020-02-06 10:46
My current impression is that my problems are a "special case" due to how I compiled pdlib/dlib into the system (to use the facerecognition app). Changing the compile parameters solved the problem.

See my investigation at: https://github.com/matiasdelellis/facerecognition/issues/216#issuecomment-577173083 -

**Comment by chrissi5120** [comment] 2024-11-27 18:58
Hi Guys, this problem is still very much relevant!

I scanned thousands of old pictures from my family and decided to save them as .tif because the scanner offered to do so.

Nextcloud is not really happy about them, for example you can not change the orientation:

![Image](https://github.com/user-attachments/assets/59894c14-9280-4d55-b130-78f78b33888d)

This does not really make sense for me as 

exiftool states the following:

`MIME Type                       : image/tiff
`

My mime-configuration:

`{
    "maps": [
        "application/x-nextcloud-maps"
    ],
    "noindex": [
        "application/x-nextcloud-noindex"
    ],
    "nomedia": [
        "application/x-nextcloud-nomedia"
    ],
    "noimage": [
        "application/x-nextcloud-noimage"
    ],
    "notrack": [
        "application/x-nextcloud-maps-notrack"
    ],
    "tiff": [
        "image/tiff"
    ],
    "raw": [
        "image/x-dcraw"
    ]
}`

I even ran the update command:

`occ maintenance:mimetype:update-js
mimetypelist.js is updated`

previews are working though:

  'enabledPreviewProviders' => 
  array (
    1 => 'OC\\Preview\\PDF',
    2 => 'OC\\Preview\\Image',
    3 => 'OC\\Preview\\Photoshop',
    4 => 'OC\\Preview\\TIFF',
    5 => 'OC\\Preview\\SVG',
    6 => 'OC\\Preview\\Movie',
    7 => 'OC\\Preview\\MKV',
    8 => 'OC\\Preview\\MP4',
    9 => 'OC\\Preview\\AVI',
    10 => 'OC\\Preview\\HEIC',
  ),

Any idea how to fully support them? 

It would be a real bummer to not be able to turn them
