### ISSUE TITLE
LDAP & application passwords should play nicer toghether

### ISSUE THREAD

**Issue by deajan** [nextcloud/server#10026] opened 2018-06-27 14:07 UTC
Hello,

Of what I am understanding, an application password is supposed to help gain access to NextCloud Server without having to specify the real password.

When a LDAP user changes its password, the application password dissappears.
Since the LDAP user is not desactivated (only password has been changed), I think it would be much better to keep the application password working so the client application still can sync, without having to change that application password on every "password change".

There could be an option to make application passwords "permanent" until manual revocation, unless an admin policy forbids to.

Any thoughts ?

**Comment by deajan** [comment] 2018-06-27 14:56
Well GitMate.io bot is wrong, none of these issues are related :)

**Comment by MorrisJobke** [comment] 2018-06-27 15:37
Duplicate of #2581

See especially https://github.com/nextcloud/server/issues/2581#issuecomment-394684452

**Closed by MorrisJobke** 2018-06-27 15:37 UTC
Labels: enhancement, feature: occ

**Comment by deajan** [comment] 2018-06-27 17:35
Thank you for the hint, sorry for the noise.
