### ISSUE TITLE
Calendar Invite Mails are displayed wrongly

### ISSUE THREAD

**Issue by DavidDohmen** [nextcloud/server#24214] opened 2020-11-18 23:06 UTC
I hope this belongs here - if not, please excuse me and let me know where to report this instead! Thanks in advance!

### Steps to reproduce
1. Create a calendar event in nextcloud with an external recipient (e.g. gmail adress)
2. Invitation mail has several displaying issues

### Expected behaviour
The logo should be aligned vertically within the circle and the icons next to titel and time shouldn't be visible.

### Actual behaviour
Default Logo and all other Logos are aligned to the top of the circle and the icons are broken. See screenshot.
![image](https://user-images.githubusercontent.com/6106225/99597619-8aaaa700-29f8-11eb-945b-a3d4ad0c9d7a.png)

### Calendar app
**Calendar app version:**  2.1.2

### Client configuration
Latest Firefox and Chrome
Ubuntu, Linux and MacOS

### Server configuration
Ubuntu 18.04
Apache
MariaDB
**Nextcloud Version:** 20.0.1
**Updated from an older installed version**

**Comment by szaimen** [comment] 2021-06-17 18:26
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-17 18:26 UTC
Labels: 0. Needs triage, bug, feature: dav
