### ISSUE TITLE
PHP 7.4: LazyFolder - Trying to access array offset on value of type int at lib/private/Files/Node/Node.php#327

### ISSUE THREAD

**Issue by robertoschwald** [nextcloud/server#21236] opened 2020-06-04 11:37 UTC
### Steps to reproduce
1. Enable Group Folders and define group folders 
2.Sync the group folders using the NextCloud client (macOS in my case)
3. Error log occurs

### Expected behaviour
No errors are logged

### Actual behaviour
Error log:

","message":"Trying to access array offset on value of type int at xxx/lib/private/Files/Node/Node.php#327",,"version":"18.0.5.1","id":"..."}

### Server configuration

**Operating system:**
CentOS8, 8.1.1911

**Web server:**
Apache HTTPD 2.4.37 (centos)

**Database:**
MariaDB 10.3.17

**PHP version:**
PHP 7.4.6 (cli) (built: May 12 2020 08:09:15) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
18.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from former minor release.

**Where did you install Nextcloud from:**
Official

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - browser_warning: 0.2.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.2
  - encryption: 2.6.0
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_antivirus: 2.4.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.5
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - files_external
  - onlyoffice
  - spreed
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
All sensitive data was removed.
{
    "system": {
        "dbtype": "mysql",
        "version": "18.0.5.1",
        "mysql.utf8mb4": true,
        "installed": true,
       
		"filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "...",
            "port": 6379
        },
		
        "blacklisted_files": [],
		
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            ....
        ],
        "twofactor_enforced_excluded_groups": [],
		
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
    }
}
```
</details>

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
NC client app (MacOS)

**Operating system:**
macOS 10.15.5

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Original error log see above.
Here is the one with enhanced logging from #19010 

```
LogicException: $path is a integer: 5
/var/www/html/lib/private/Files/Node/Folder.php - line 59:
OC\Files\Node\Node->isValidPath()
/var/www/html/lib/private/Files/Node/Folder.php - line 137:
OC\Files\Node\Folder->getFullPath()
<<closure>>
OC\Files\Node\Folder->get()
/var/www/html/apps/groupfolders/lib/Helper/LazyFolder.php - line 72:
call_user_func_array()
/var/www/html/apps/groupfolders/lib/Helper/LazyFolder.php - line 144:
OCA\GroupFolders\Helper\LazyFolder->__call()
/var/www/html/apps/groupfolders/lib/Mount/MountProvider.php - line 184:
OCA\GroupFolders\Helper\LazyFolder->get()
/var/www/html/apps/groupfolders/lib/Mount/MountProvider.php - line 124:
OCA\GroupFolders\Mount\MountProvider->getFolder()
/var/www/html/apps/groupfolders/lib/Versions/VersionsBackend.php - line 160:
OCA\GroupFolders\Mount\MountProvider->getMount()
/var/www/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 62:
OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()
/var/www/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 57:
OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
/var/www/html/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php - line 40:
OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
/var/www/html/lib/private/BackgroundJob/Job.php - line 61:
OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
/var/www/html/lib/private/BackgroundJob/TimedJob.php - line 55:
OC\BackgroundJob\Job->execute()
/var/www/html/cron.php - line 125:
OC\BackgroundJob\TimedJob->execute()
```
</details>

**Comment by kesselb** [comment] 2020-06-04 12:04
Closing as duplicate of https://github.com/nextcloud/groupfolders/issues/907

**Closed by kesselb** 2020-06-04 12:04 UTC
Labels: 0. Needs triage, bug

**Comment by robertoschwald** [comment] 2020-06-04 12:19
@kesselb Thanks. Didn't know that there exists a separate repo for it.
