### ISSUE TITLE
Nextcloud 14 RC 2 Installer::isUpdateAvailable() should not be called statically at /var/www/nextcloud/apps/serverinfo/lib/SystemStatistics.php#169

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#10950] opened 2018-08-31 15:50 UTC
Getting this error after NC14 RC2 update. 

![image](https://user-images.githubusercontent.com/24574019/44922675-a1775d00-ad0b-11e8-8c08-1bf096581f18.png)

C\Installer::isUpdateAvailable() should not be called statically at /var/www/nextcloud/apps/serverinfo/lib/SystemStatistics.php#169

**Comment by splitt3r** [comment] 2018-08-31 18:32
This seems to be the reason for #10951. Duplicate of #10951

**Comment by danielkesselberg** [comment] 2018-09-01 20:59
Thank you for reporting this issue :+1: 

This problem is related to serverinfo app (https://github.com/nextcloud/serverinfo) and fix is on the road :construction:

**Comment by andyxh** [comment] 2018-09-01 21:00
Anytime!! Thank you!!! 😁😁

Sent from my iPhone

On Sep 1, 2018, at 3:59 PM, Daniel Kesselberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for reporting this issue 👍

This problem is related to serverinfo app (https://github.com/nextcloud/serverinfo<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextcloud%2Fserverinfo&data=02%7C01%7C%7C3acb5c6bc77b4fdfba2608d6104ddff3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636714323978619245&sdata=kCDDJnQ%2BD3atU8BBRMWRmKMj%2F7c4jDWn4dymEYJdlcs%3D&reserved=0>) and fix is on the road 🚧

**Closed** 2018-09-03 10:59 UTC
