### ISSUE TITLE
Login form IE11 on NC19

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#21623] opened 2020-06-29 12:51 UTC
The issue you are facing: Nextcloud web login page is not working anymore with Internet Explorer, showing lots of errors related to some variables not declared, I suppose that is related to incompatiblity with the new nextcloud version.

### Steps to reproduce
1. Install nextcloud to version 19
2. Open internet explorer in the nc login page
3. Open the dev console of internet explorer and look at console window

### Expected behaviour
Should be able to login with IE11

### Actual behaviour
Login form doesn't show

### Server configuration

**Operating system:**
CentOS 7

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
NC19

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install and upgrade

Here below the Internet Explorer console output:

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
login
HTML1300: Navigation occurred.
login
SCRIPT1014: Invalid character
main.js (791,21360)
SCRIPT5009: 'OC' is undefined
merged-template-prepend.js (26,1)
SCRIPT5009: 'OCA' is undefined
search.js (196,2)
SCRIPT5009: 'OC' is undefined
it.js (1,1)
SCRIPT5009: 'OC' is undefined
it.js (1,1)
SCRIPT5009: 'OC' is undefined
main.js (23,1)
SCRIPT5009: 'OCA' is undefined
previewplugin.js (15,2)
SCRIPT5009: 'OC' is undefined
main.js (22,1)
SCRIPT5009: 'OCA' is undefined
searchprovider.js (410,2)
SCRIPT5009: 'OC' is undefined
fileinfo.js (11,2)
SCRIPT5009: 'OC' is undefined
client.js (13,2)
SCRIPT5009: 'dav' is undefined
iedavclient.js (12,2)
SCRIPT5009: 'OCA' is undefined
login.js (318,26387)
SCRIPT5009: 'OCA' is undefined
theming (2,2)
SCRIPT5009: 'OCA' is undefined
accessibility (2,2)
```

**Comment by mp-itconsulting** [comment] 2020-06-29 13:48
Same issue here. After update to NC 11 login form is not shown in IE 11

**Comment by kesselb** [comment] 2020-06-29 16:49
Closing as duplicate of https://github.com/nextcloud/server/issues/21316. Please use the search before creating new issues.

**Closed by kesselb** 2020-06-29 16:49 UTC
Labels: 0. Needs triage, bug
