### ISSUE TITLE
snap Update to 13.01 beta

### ISSUE THREAD

**Issue by slate56** [nextcloud/server#9366] opened 2018-05-02 15:10 UTC
got error
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table`	FROM INFORMATION_SCHEMA . COLUMNS	WHERE TABLE_SCHEMA = ?	AND (COLLATION_NAME <> 'utf8mb4_bin' OR CHARACTER_SET_NAME <> 'utf8mb4')	AND TABLE_NAME LIKE 'oc_%'' with params ["nextcloud"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by MorrisJobke** [comment] 2018-05-03 07:30
Looks like a duplicate of #8863

**Closed by MorrisJobke** 2018-05-03 07:30 UTC
