### ISSUE TITLE
[Feature request]: Select View Option:  Hide / Unhide of left-side panel in NC

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#3291] opened 2017-01-27 08:42 UTC
Hi to All,

It could be very advantageous to introduce  / implement  a GENERAL Option as a  toggle switch to hide / unhide the left side panel for EVERY app to maximize the screen usage - especially on small (e.g. mobile) screens.

regards, hitam4450

**Comment by MorrisJobke** [comment] 2017-01-28 01:06
On mobile screens the left menu is hidden by default.

cc @jancborchardt

**Comment by nickvergessen** [comment] 2017-01-30 11:55
Duplicate of https://github.com/nextcloud/server/issues/3049

**Closed by nickvergessen** 2017-01-30 11:55 UTC

**Comment by profihost** [comment] 2017-09-20 06:01
+1 for desktop
