### ISSUE TITLE
can't show local in External storages

### ISSUE THREAD

**Issue by o-water-o** [nextcloud/server#11121] opened 2018-09-08 17:19 UTC
there is not showing local storges in External storages.
vision 13.0.6 database mysql

**Comment by szaimen** [comment] 2021-05-21 11:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-21 11:45 UTC
Labels: 0. Needs triage, bug, feature: external storage
