### ISSUE TITLE
Profile picture selection: Extra scrollbar due to long path

### ISSUE THREAD

**Issue by dennorske** [nextcloud/server#17495] opened 2019-10-09 17:03 UTC
### Steps to reproduce
1. Go in and change your picture from files on the server
2. Browse in to a long path that will fill up your path on top
3. Scroll and see that you have two scrollbars, and the bottom blur is pushed up from the bottom

### Expected behaviour
I would expect the window to expand, or the path to be cut off in the start with `".../current folder"` to avoid this.

### Actual behaviour
Uploaded GIF:
![Nextcloud-profile-image-selection.gif](https://pics.ducky.rocks/images/2019/10/09/Nextcloud-profile-image-selection.gif)

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2

**Database:** Mysql

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded

**Where did you install Nextcloud from:** Official download of web directory

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - announcementcenter: 3.6.0
  - audioplayer: 2.8.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - deck: 0.7.0
  - external: 3.4.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_readmemd: 1.1.1
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trackdownloads: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocsms: 2.1.3
  - password_policy: 1.7.0
  - previewgenerator: 2.1.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - ransomware_protection: 1.5.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - socialsharing_email: 1.0.5
  - spreed: 7.0.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - suspicious_login: 2.3.0
  - systemtags: 1.7.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_nextcloud_notification: 2.1.1
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - afterlogic
  - encryption
  - mail
  - music
  - onlyoffice
  - rainloop
  - user_ldap
```
</details>

**Will provide more info if needed, but I don't see the need for this in this bug report, as it is GUI based.**

**Comment by dennorske** [comment] 2019-10-19 14:36
Are there anyone else that manages to re-produce this issue?

**Comment by szaimen** [comment] 2021-05-27 09:20
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 09:20 UTC
Labels: 0. Needs triage, bug
