### ISSUE TITLE
Anonymous upload folder documentation incorrect

### ISSUE THREAD

**Issue by detly** [nextcloud/server#15231] opened 2019-04-25 13:41 UTC
I would like a folder that can be anonymously uploaded to. The documentation for "making anonymous uploads" says:

> Check Share Link, Allow editing, Hide file listing.

With this picture:

![ncdoc](https://user-images.githubusercontent.com/311239/56739672-d906ae00-67a1-11e9-90ba-4f9a164c9354.png)

My 15.0.7 server has no such option (as admin or regular user):

![ncdrops](https://user-images.githubusercontent.com/311239/56739687-e91e8d80-67a1-11e9-8763-172ff929a8ce.png)

Indeed, there seems to be no way to create an anonymous upload ("drop") folder. If this feature was removed, it should be removed from the documentation. If it has changed, the documentation should be changed.

### Server configuration

**Operating system**: Some Linux distro on shared hosting.

**Web server:** Don't know.

**Database:** MySQL.

**PHP version:** 7.2

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated.

**Where did you install Nextcloud from:** The Nextcloud site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - drawio: 0.9.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - flowupload: 0.1.0
  - gallery: 18.2.0
  - groupfolders: 3.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - previewgenerator: 2.1.0
  - privatedata: 1.0.1
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** No.

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Google Chrome 73

**Operating system:** Ubuntu 18.04.1

**Comment by detly** [comment] 2019-04-25 13:47
There is also [this page/video](https://nextcloud.com/file-drop/) — definitely seems to be out of date.

**Comment by kesselb** [comment] 2019-04-25 13:56
![image](https://user-images.githubusercontent.com/3902676/56741122-8661cd80-6772-11e9-90b4-bd3113d04d52.png)

I see the filedrop with nextcloud 16. cc @nextcloud/documentation @jospoortvliet

**Comment by j-ed** [comment] 2019-04-25 14:06
@kesselb I can confirm that it works with Nextcloud 16, although there is a small glitch when the system recommends a person to share with. In this case the "Share link" menu point cannot be seen because it is overlayed by the recommendation window:

![grafik](https://user-images.githubusercontent.com/2572764/56741754-bc538180-6773-11e9-92f4-03e999a76f77.png)
1. click on the share button.
2. the select box and a recommendation is shown but not the "Share link" button.
3. click on an empty area in that window.

![grafik](https://user-images.githubusercontent.com/2572764/56741772-c37a8f80-6773-11e9-96cf-e68d0b747f15.png)
4. now the "Share link" button can be seen again.

**Comment by j-ed** [comment] 2019-04-25 14:16
@detly Can you please provide a screenshot of your share settings under **Settings > Administration > Sharing** please. I’m especially interested in if the parameter “`Allow public uploads`” is checked.

**Comment by kesselb** [comment] 2019-04-25 18:20
cc @nextcloud/designers

**Comment by detly** [comment] 2019-04-25 23:03
Aha...

![Uploading Screenshot_20190426_065518.jpg…]()

After checking this box I see the option for file drops now. I must have disabled this a few releases ago and forgotten about it. I will still suggest putting something in the documentation, because I must have looked at several sources of information and nothing mentioned this. 

One other question — can I restrict this to a single group of users? I see the ability to *prevent* specific groups from sharing altogether, but is it possible to explicitly allow who can allow public uploads?

**Comment by detly** [comment] 2019-04-25 23:53
I spoke too soon. I can create the drop folders as admin, but as a regular user this setting completely removes the ability to create share links. When I click on the `+` to create a new share link, I see this in the sidebar:

![ncdrop2](https://user-images.githubusercontent.com/311239/56775013-ba330680-67f7-11e9-95c2-9c8929758ef9.png)

...and an "Unable to create link share" error up the top:

![share](https://user-images.githubusercontent.com/311239/56775056-ebabd200-67f7-11e9-80b2-f75a7f0b5207.png)

There is nothing in the logs that appears related to this.

**Comment by detly** [comment] 2019-04-25 23:58
I tried again with a random folder name `C4rgea2` so I could narrow down searching a bit more. I found four of these log entries:

```text
[no app in context] Debug: No cache entry found for /jason/files/C4rgea2 (storage: home::jason, internalPath: files/C4rgea2)

MKCOL /remote.php/dav/files/jason/C4rgea2
from 61.245.140.31 by jason at 2019-04-25T23:55:34+00:00
```

This is after:

1. Creating the folder (as user `jason`)
2. Clicking on the share icon in its row
3. Clicking on the `+` button to create a share link
4. Logging out and back in as admin

**Comment by detly** [comment] 2019-04-26 00:18
Okay, seems to have suddenly come good for regular users too. Mysterious...

**Comment by jospoortvliet** [comment] 2019-09-26 13:30
I guess we can then close this issue?!?

**Closed by jospoortvliet** 2019-09-26 13:30 UTC
Labels: 0. Needs triage, bug
