### ISSUE TITLE
External Storage Dropbox OAuth2

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/server#6697] opened 2017-09-29 09:27 UTC
Refered to #3039

https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/

The problem is, that OAuth1 was shutdowned by Dropbox. The good point is that Dropbox has created a migration guide:
https://www.dropbox.com/developers/reference/migration-guide

Maybe I find time and skill to do that, but don´t count on me, I´m very busy atm. ;)

**Comment by juliushaertl** [comment] 2017-09-29 21:14
Duplicate of https://github.com/nextcloud/server/issues/991

**Closed by juliushaertl** 2017-09-29 21:14 UTC
Labels: feature: external storage
