### ISSUE TITLE
NC12 Beta 3 - Cannot Close Video preview

### ISSUE THREAD

**Issue by tilllt** [nextcloud/server#4933] opened 2017-05-18 07:16 UTC
### Steps to reproduce
1. Upload video thats playable by NC video Preview
2. Open it and play it
3. It plays fine but you cannot close the Preview anymore

### Expected behaviour
It should be possible to close the preview

### Actual behaviour
You cannot close the preview

There is one error in the console which is probably related:

```
Uncaught ReferenceError: videojs is not defined
    at Object.show (viewer.js:39)
    at Object.<anonymous> (viewer.js:82)
    at Object.<anonymous> (core.js:2)
    at j (core.js:2)
    at Object.fireWith [as resolveWith] (core.js:2)
    at x (core.js:4)
    at XMLHttpRequest.<anonymous> (core.js:4)
```

**Comment by schiessle** [comment] 2017-05-18 16:16
duplicate of https://github.com/nextcloud/files_videoplayer/issues/25

**Closed by schiessle** 2017-05-18 16:16 UTC
