### ISSUE TITLE
Downloading a file version should have a different name

### ISSUE THREAD

**Issue by biva** [nextcloud/server#19358] opened 2020-02-07 21:51 UTC
When I download an older version of a file (for example 'document.txt'), I would like that this downloaded file has a different name, for example including the timestamp. For example `document-20200207-2248.txt`. But any other difference would work for me.

Use case:
- I work on a Word document **Analysis.docx**
- I want to recover a paragraph that I accidentally deleted
- I download a previous version and the file has also the name **Analysis.docx**
- If I open it directly, Word refuses to open it because another file with the same name is already open

NC 17.0.3

**Comment by biva** [comment] 2020-03-24 17:06
Any update on this? I have the feeling that this was the case in a previous version of Nextcloud, wasn't it?

**Comment by szaimen** [comment] 2021-05-31 11:19
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 11:19 UTC
Labels: 0. Needs triage, enhancement

**Comment by biva** [comment] 2021-05-31 13:28
@szaimen I have the latest version (21.0.2) and the issue is still there:
1. Download a previous version of the file **document.txt**
2. The downloaded file has the name **document.doc** as well, while it should have a name indicating that it's a previous version (for example **document-20200207-2248.txt**)

**Comment by biva** [comment] 2021-05-31 13:28
I can't reopen it: could you please reopen it?

**Comment by szaimen** [comment] 2021-05-31 13:31
What I cannot reproduce is this:

> * I work on a Word document **Analysis.docx**
> * I want to recover a paragraph that I accidentally deleted
> * I download a previous version and the file has also the name **Analysis.docx**
> * If I open it directly, Word refuses to open it because another file with the same name is already open

That's why I don't think that this needs to be fixed because the date doesn't get appended to the downloaded file version by design.

**Comment by biva** [comment] 2021-06-01 20:56
I don't understand: any Office application (Excel, Word, ...) refuses to open a document with the same name as a document already opened. If you keep **Analysis.docx** open, you can't open the downloaded previous version.

Are you sure you can't reproduce?

**Comment by szaimen** [comment] 2021-06-01 21:53
Yes
![image](https://user-images.githubusercontent.com/42591237/120394926-71ce6700-c334-11eb-8e22-1e077d0dbb8f.png)

**Comment by biva** [comment] 2021-06-01 23:04
Sorry, my mistake :( I took the example of Word to be clearer, but indeed, Word can do it. My problem is with Excel: Excel can't open 2 documents with the same name.

![image](https://user-images.githubusercontent.com/9964305/120400543-5cf6d100-c33e-11eb-968d-2db5edc9b1a9.png)

Sorry for the confusion.

Anyway, in addition to this Excel issue, I think it makes sense, to avoid confusion, that older versions have a different name. Don't you think?

**Comment by szaimen** [comment] 2021-06-02 13:18
> Excel can't open 2 documents with the same name.

I'd recomend to open a ticket in Microsofts issue tracker for this.

---

As I said, the date is not appended to the files version when downloaded by design and this will not be changed.

**Comment by biva** [comment] 2021-06-02 19:56
@szaimen: I'm pretty sure that a previous version of Nextcloud did that (I don't remember if it was the date, but a kind of version number was added to the name). Am I wrong? Why is it different now?
