### ISSUE TITLE
name conflict of 'group folder' and 'normal folder'

### ISSUE THREAD

**Issue by feichtinger** [nextcloud/server#20985] opened 2020-05-15 06:16 UTC
Hi

As it turns out you can create a group folder that has the same name as a normal folder. The result is that only one folder (with quite strange behaviour) is visible in the 'Files' view.

### Steps to reproduce
1. create a normal folder (and maybe put some files in it)
2. create a group folder with exactly the same name in the admin panel
3. switch back to "Files" and watch the result

### Expected behaviour
It should be impossible to create a group folder with an existing name.

### Actual behaviour
It is possible to create a group folder with an existing name and it results in strange behaviour.

### Server configuration

**Operating system:** Ubuntu Server 18.04

**Web server:** ???

**Database:** PostgreSQL 9.6.17

**PHP version:** 7.3.17

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Comment by kesselb** [comment] 2020-05-15 06:40
Thanks for reporting 👍

I'm closing this report as duplicate of https://github.com/nextcloud/groupfolders/issues/648.

**Closed by kesselb** 2020-05-15 06:40 UTC
Labels: 0. Needs triage, bug
