### ISSUE TITLE
[Bug]: [stable27] Navigation entry for "All files" does not show the root folder

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#43700] opened 2024-02-20 16:34 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On Nextcloud 27, when clicking on "All files" nothing happen.

### Steps to reproduce

1. Create a folder
2. Navigate to that folder
3. Click on "All files"
4. No navigation to the root folder.

### Expected behavior

The view should display the content of the root folder.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2024-02-20 16:42
Confirmed. But also, link works if on a subfolder:

1. Create a folder
2. Create a sub-folder
3. Go to the subfolder, click on "All files" => Works

**Comment by solracsf** [comment] 2024-02-20 16:44
Link also works if:

1. Create a folder
2. Go to that folder
3. Click on the little "house icon" on breadcrumbs
4. Got to the folder again, click on "All files" => Works

**Comment by Beleggrodion** [comment] 2024-02-21 08:41
I think i also have this issue here too, but i use here nextcloud 28.0.2. A user mentioned today, that he had it since around 2 or 3 weeks. I updated on the 6th february my nextcloud 27 installation to the lastest 27 and then on the 8th february to the latest nextcloud 28 version.

He ony see an empty root folder when he login via webui. I currently can reproduce it with an admin account, so multiple user are affected. when i connect via a webdav client, he see all his folders and files.  Also when i try to access a subfolder directly in the browser via `https://nextcloud.dummy/index.php/apps/files/files?dir=/Subfolder` this works and all content is displayed as expected.

First i tried to re-index all files via `occ files:scan --path="/<user>/files"` -v but without sucess.
Also `occ maintenance:repair` had no success.

**Comment by artonge** [comment] 2024-02-21 16:10
@skjnldsv would this be easily fixable?

**Comment by skjnldsv** [comment] 2024-02-21 16:50
For me it's fine on 29.0.0 alpha and 28.0.3 too.
So it's 27 only. I guess this has to do with the legacy files :shrug: 
Some event to catch somewhere and update, considering this is fixed for 28 and above already, I would close as wontfix for 27

**Comment by skjnldsv** [comment] 2024-02-22 18:34
@solracsf sure, but there are issues worth fixing and unfortunately some harder than others.
This one might be complicated :thinking: 
Seems like this issue haven't gained that much traction despite being released for 6 months. So People seem to have managed the regression :)

**Comment by solracsf** [comment] 2024-02-22 21:36
Sure, I get your point :)

**Comment by alepesiy** [comment] 2024-02-28 17:06
is it possible to find out which files can be transferred from 28/29 to 27 for fixing this issue?
We also use 27.0.2 and this bug is reproducing
But we can't just upgrade to 28 or 29.

**Comment by skjnldsv** [comment] 2024-02-28 17:13
@alepesiy the Files app changed completely for 28. So there is no files to be transferred

**Comment by Beleggrodion** [comment] 2024-02-28 17:26
a short reminder, i also have this issue on 28.0.2 as mentioned: https://github.com/nextcloud/server/issues/43700#issuecomment-1956146208 . so for me it's not a bug in 27.x only ;-)

**Comment by skjnldsv** [comment] 2024-02-28 17:27
> For me it's fine on 29.0.0 alpha and 28.0.3 too.

**Comment by Beleggrodion** [comment] 2024-03-03 20:47
I updated now to 28.0.3 but the problem still exists.

**Comment by skjnldsv** [comment] 2024-03-14 07:29
@Beleggrodion are you sure we're talking about the same issue?

**Comment by Beleggrodion** [comment] 2024-03-14 07:46
I can give you some screenshots (german interface), what i mean. If it's a similar bug in your eyes i can open a seperate case for it, for me it looks like the same.

the root folder over nextcloud:
![nc_screen_root](https://github.com/nextcloud/server/assets/5476969/d84f8162-90f5-43c8-9655-36e823dd0ee4)
the root folder when i'm on the server:
![on_server_ll](https://github.com/nextcloud/server/assets/5476969/a98f2a04-ec12-4a03-b511-2de218f999a3)
and a sub folder when i add the path to the url.
![nc_screen_subfolder](https://github.com/nextcloud/server/assets/5476969/ace58e51-7803-451f-af71-9814ab46da74)

**Comment by skjnldsv** [comment] 2024-03-14 12:58
I will need a screenshot of your network requests @Beleggrodion.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

Please xroll until you find a PROPFIND request listed, the url is usually something like `remote.php/dav/USER/files`

**Comment by Beleggrodion** [comment] 2024-03-15 13:09
Ok. here the corresponding output of one of the affected users: (my user vor ex. is not affected)

![error_chrome_nc](https://github.com/nextcloud/server/assets/5476969/e84fb881-47a4-4424-b70a-89e12cc2dc25)

On the server i don't see anything in logfiles of the webserver in the error log, only something like:

`127.0.0.1 - - [15/Mar/2024:13:48:58 +0100] "PROPFIND /remote.php/dav/files/redacted/ HTTP/1.1" 500 215 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/`

and here the corresponding log entry of nextcloud:

```
{
   "reqId":"ZfRDur-UH5bYX6q7aZn_TAAAAIU",
   "level":3,
   "time":"2024-03-15T12:48:58+00:00",
   "remoteAddr":"46.xxx.xxx.xxx",
   "user":"redacted",
   "app":"webdav",
   "method":"PROPFIND",
   "url":"/remote.php/dav/files/redacted/",
   "message":"Could not decrypt key",
   "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
   "version":"28.0.3.2",
   "exception":{
      "Exception":"OC\\ServerNotAvailableException",
      "Message":"Could not decrypt key",
      "Code":0,
      "Trace":[
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Encryption/Keys/Storage.php",
            "line":102,
            "function":"getKey",
            "class":"OC\\Encryption\\Keys\\Storage",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/apps/encryption/lib/KeyManager.php",
            "line":382,
            "function":"getFileKey",
            "class":"OC\\Encryption\\Keys\\Storage",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/apps/encryption/lib/Crypto/Encryption.php",
            "line":166,
            "function":"getFileKey",
            "class":"OCA\\Encryption\\KeyManager",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/Stream/Encryption.php",
            "line":284,
            "function":"begin",
            "class":"OCA\\Encryption\\Crypto\\Encryption",
            "type":"->"
         },
         {
            "function":"stream_open",
            "class":"OC\\Files\\Stream\\Encryption",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/Stream/Encryption.php",
            "line":212,
            "function":"fopen"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/Stream/Encryption.php",
            "line":187,
            "function":"wrapSource",
            "class":"OC\\Files\\Stream\\Encryption",
            "type":"::"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/Storage/Wrapper/Encryption.php",
            "line":489,
            "function":"wrap",
            "class":"OC\\Files\\Stream\\Encryption",
            "type":"::"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/Storage/Wrapper/Encryption.php",
            "line":236,
            "function":"fopen",
            "class":"OC\\Files\\Storage\\Wrapper\\Encryption",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/Storage/Wrapper/Wrapper.php",
            "line":244,
            "function":"file_get_contents",
            "class":"OC\\Files\\Storage\\Wrapper\\Encryption",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/apps/files_accesscontrol/lib/StorageWrapper.php",
            "line":169,
            "function":"file_get_contents",
            "class":"OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/View.php",
            "line":1161,
            "function":"file_get_contents",
            "class":"OCA\\FilesAccessControl\\StorageWrapper",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/View.php",
            "line":581,
            "function":"basicOperation",
            "class":"OC\\Files\\View",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/lib/private/Files/Node/File.php",
            "line":54,
            "function":"file_get_contents",
            "class":"OC\\Files\\View",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/apps/text/lib/DAV/WorkspacePlugin.php",
            "line":119,
            "function":"getContent",
            "class":"OC\\Files\\Node\\File",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/PropFind.php",
            "line":95,
            "function":"OCA\\Text\\DAV\\{closure}",
            "class":"OCA\\Text\\DAV\\WorkspacePlugin",
            "type":"->",
            "args":[
               "*** sensitive parameters replaced ***"
            ]
         },
         {
            "file":"/www/redacted/nextcloud/www/apps/text/lib/DAV/WorkspacePlugin.php",
            "line":117,
            "function":"handle",
            "class":"Sabre\\DAV\\PropFind",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line":89,
            "function":"propFind",
            "class":"OCA\\Text\\DAV\\WorkspacePlugin",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":1052,
            "function":"emit",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":984,
            "function":"getPropertiesByNode",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":1662,
            "function":"getPropertiesIteratorForPath",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":1647,
            "function":"writeMultiStatus",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
            "line":346,
            "function":"generateMultiStatus",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line":89,
            "function":"httpPropFind",
            "class":"Sabre\\DAV\\CorePlugin",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":472,
            "function":"emit",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":253,
            "function":"invokeMethod",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":321,
            "function":"start",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/apps/dav/lib/Server.php",
            "line":373,
            "function":"exec",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/apps/dav/appinfo/v2/remote.php",
            "line":35,
            "function":"exec",
            "class":"OCA\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/www/redacted/nextcloud/www/remote.php",
            "line":172,
            "args":[
               "/www/redacted/nextcloud/www/apps/dav/appinfo/v2/remote.php"
            ],
            "function":"require_once"
         }
      ],
      "File":"/www/redacted/nextcloud/www/lib/private/Encryption/Keys/Storage.php",
      "Line":285,
      "Previous":{
         "Exception":"Exception",
         "Message":"Authenticated ciphertext could not be decoded.",
         "Code":0,
         "Trace":[
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Security/Crypto.php",
               "line":123,
               "function":"decryptWithoutSecret",
               "class":"OC\\Security\\Crypto",
               "type":"->",
               "args":[
                  "*** sensitive parameters replaced ***"
               ]
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Encryption/Keys/Storage.php",
               "line":283,
               "function":"decrypt",
               "class":"OC\\Security\\Crypto",
               "type":"->",
               "args":[
                  "*** sensitive parameters replaced ***"
               ]
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Encryption/Keys/Storage.php",
               "line":102,
               "function":"getKey",
               "class":"OC\\Encryption\\Keys\\Storage",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/apps/encryption/lib/KeyManager.php",
               "line":382,
               "function":"getFileKey",
               "class":"OC\\Encryption\\Keys\\Storage",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/apps/encryption/lib/Crypto/Encryption.php",
               "line":166,
               "function":"getFileKey",
               "class":"OCA\\Encryption\\KeyManager",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/Stream/Encryption.php",
               "line":284,
               "function":"begin",
               "class":"OCA\\Encryption\\Crypto\\Encryption",
               "type":"->"
            },
            {
               "function":"stream_open",
               "class":"OC\\Files\\Stream\\Encryption",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/Stream/Encryption.php",
               "line":212,
               "function":"fopen"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/Stream/Encryption.php",
               "line":187,
               "function":"wrapSource",
               "class":"OC\\Files\\Stream\\Encryption",
               "type":"::"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/Storage/Wrapper/Encryption.php",
               "line":489,
               "function":"wrap",
               "class":"OC\\Files\\Stream\\Encryption",
               "type":"::"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/Storage/Wrapper/Encryption.php",
               "line":236,
               "function":"fopen",
               "class":"OC\\Files\\Storage\\Wrapper\\Encryption",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/Storage/Wrapper/Wrapper.php",
               "line":244,
               "function":"file_get_contents",
               "class":"OC\\Files\\Storage\\Wrapper\\Encryption",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/apps/files_accesscontrol/lib/StorageWrapper.php",
               "line":169,
               "function":"file_get_contents",
               "class":"OC\\Files\\Storage\\Wrapper\\Wrapper",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/View.php",
               "line":1161,
               "function":"file_get_contents",
               "class":"OCA\\FilesAccessControl\\StorageWrapper",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/View.php",
               "line":581,
               "function":"basicOperation",
               "class":"OC\\Files\\View",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/lib/private/Files/Node/File.php",
               "line":54,
               "function":"file_get_contents",
               "class":"OC\\Files\\View",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/apps/text/lib/DAV/WorkspacePlugin.php",
               "line":119,
               "function":"getContent",
               "class":"OC\\Files\\Node\\File",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/PropFind.php",
               "line":95,
               "function":"OCA\\Text\\DAV\\{closure}",
               "class":"OCA\\Text\\DAV\\WorkspacePlugin",
               "type":"->",
               "args":[
                  "*** sensitive parameters replaced ***"
               ]
            },
            {
               "file":"/www/redacted/nextcloud/www/apps/text/lib/DAV/WorkspacePlugin.php",
               "line":117,
               "function":"handle",
               "class":"Sabre\\DAV\\PropFind",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
               "line":89,
               "function":"propFind",
               "class":"OCA\\Text\\DAV\\WorkspacePlugin",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
               "line":1052,
               "function":"emit",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
               "line":984,
               "function":"getPropertiesByNode",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
               "line":1662,
               "function":"getPropertiesIteratorForPath",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
               "line":1647,
               "function":"writeMultiStatus",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
               "line":346,
               "function":"generateMultiStatus",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
               "line":89,
               "function":"httpPropFind",
               "class":"Sabre\\DAV\\CorePlugin",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
               "line":472,
               "function":"emit",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
               "line":253,
               "function":"invokeMethod",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/3rdparty/sabre/dav/lib/DAV/Server.php",
               "line":321,
               "function":"start",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/apps/dav/lib/Server.php",
               "line":373,
               "function":"exec",
               "class":"Sabre\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/apps/dav/appinfo/v2/remote.php",
               "line":35,
               "function":"exec",
               "class":"OCA\\DAV\\Server",
               "type":"->"
            },
            {
               "file":"/www/redacted/nextcloud/www/remote.php",
               "line":172,
               "args":[
                  "/www/redacted/nextcloud/www/apps/dav/appinfo/v2/remote.php"
               ],
               "function":"require_once"
            }
         ],
         "File":"/www/redacted/nextcloud/www/lib/private/Security/Crypto.php",
         "Line":135
      },
      "message":"Could not decrypt key",
      "exception":{
         
      },
      "CustomMessage":"Could not decrypt key"
   }
}
```

I don't have enabled server side encryption at the moment (had an issue 2-3 years ago on which had an issue with new generation of keys and lost of data and needed to be restored with some decrypt scripts)

**Comment by ivoruetsche** [comment] 2024-03-30 01:17
![image](https://github.com/nextcloud/server/assets/20657383/3a5efd14-9ec2-482a-815e-a56c26c69484)

I host on the sever from @Beleggrodion and if I disable the "Show folder description", all the files and directories are listed now.

**Comment by joshtrichards** [comment] 2024-04-04 16:28
We have some similar open issues all tied to when rich workspaces is on (i.e. "Show folder description") and fails to load its file at login (aross both v27 and v28). Different behind the scenes triggers (based on stack traces) for the `Readme.md` failing to load, but Files showing no files in all cases:

* #44549 
* #42663 
* #43315

Not sure what we should be doing here, since there are (apparent) underlying causes for the file to not be available. 

On the one hand, Files should maybe not prevent file access completely if the Readme is unavailable, but under normal circumstances I'd say the current behavior is fine because: when this happens it's probable that the rest of the user's files won't be accessible either (i.e. there all stored in the same place). But that doesn't seem to be the case in these cases (since turning on workspaces fixes this in most cases).

So I think we may have multiple things going on here:

1. Files refuses to show files if there is any error condition surrounding loading the `Readme.me`
2. Why the `Readme.md` isn't loading when the `text` app tries to load it? (particularly since files are otherwise accessible once workspaces are turned off)


Item one might be something to consider as a future enhancement, but technically item two is the root cause here. I think we need to figure out why the `text` app is failing in all these weird ways to load workspaces files right at login time.

**Comment by joshtrichards** [comment] 2024-04-04 16:32
Technically I guess that makes these issues all part of a `text` app bug.

I looked at this a couple months back briefly from that perspective (before I was aware of these other reports) here: https://github.com/nextcloud/server/issues/42663#issuecomment-1885271634

**Comment by skjnldsv** [comment] 2024-04-04 17:13
Yeah, that doesn't seem related to this issue @Beleggrodion :/

**Comment by didierm** [comment] 2024-05-31 10:24
This issue also occurs on the latest **NC v29.0.1**, and is mitigated by https://github.com/nextcloud/server/issues/42663#issuecomment-1884075217.
Remarks : 
* emitted eror is not `GenericFileException` , but `ForbiddenException`
* the request is not for `Readme.md` , but for `/Desktop/Readme.md`
[trace.json](https://github.com/user-attachments/files/15512185/trace.json)

**Comment by skjnldsv** [comment] 2024-11-08 10:23
Alright, let's close.
last supported is 28 and it doesn't happen there.

If anyone experience this, please upgrade to latest versions (28 or above, 29 recommended)

**Closed by skjnldsv** 2024-11-08 10:23 UTC
Labels: bug, 0. Needs triage, feature: files, 27-feedback
