### ISSUE TITLE
NC proxy exception setting

### ISSUE THREAD

**Issue by ralfi** [nextcloud/server#15395] opened 2019-05-06 14:39 UTC
Hi nextcloudies,
i don't know this a bug or a feature request ...

For better and simply configuration with LOOL and / docker it would be helpfull to set a proxy exception string in config/config.php. I don't know if there another way to do this.

Thanks a lot.

**Comment by kesselb** [comment] 2020-01-24 22:50
Closing as duplicate of https://github.com/nextcloud/server/issues/12402

**Closed by kesselb** 2020-01-24 22:50 UTC
Labels: 0. Needs triage, bug
