### ISSUE TITLE
Update all button in the apps management

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#7364] opened 2017-12-01 16:33 UTC
I really like the new "Updates" category in the apps management where you can see directly all apps which can be updated. The only think I miss now is a "Update all" button, so that I don't have to click on ever "update"-button manually.

cc @nextcloud/designers for ideas how such a button could be integrated

**Comment by splitt3r** [comment] 2017-12-01 23:18
Duplicate of #6989

**Closed** 2017-12-02 07:41 UTC
Labels: enhancement, feature: apps management
