### ISSUE TITLE
[Bug]: NC 28 - Directories with "#" in their names: can no longer open files

### ISSUE THREAD

**Issue by kirides** [nextcloud/server#42247] opened 2023-12-13 19:08 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Directories with "#" in their name no longer work properly. Files can no longer be downloaded / uploaded.

### Steps to reproduce

1. Have a directory with name like "C# Scripts"
2. Try to open/download a file from it
3. See that the request goes to `/remote.php/dav/files/USER/C`
4. File can not be downloaded as the "#" gets sanitized away instead of being percent-encoded

### Expected behavior

Directories with # in their name should be working just as before.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment] 2023-12-14 14:52
Duplicate of https://github.com/nextcloud/server/issues/42171

**Closed by skjnldsv** 2023-12-14 14:52 UTC
Labels: bug, 0. Needs triage, 28-feedback
