### ISSUE TITLE
Contacts Not Syncing in MacOS Mojave

### ISSUE THREAD

**Issue by nickian** [nextcloud/server#10318] opened 2018-07-20 21:17 UTC
I'm running NextCloud 13.04 with the contacts app. Syncing to MacOS High Sierra was working fine, but since updating to the beta of Mojave, contacts aren't syncing. I'm able to add the account just fine, but no contacts end up showing up in the Contacts app. Calendar works just fine, just no contacts.

I'm not sure if this is a MacOS issue or something that will need to be updated in NextCloud to accommodate Mojave. Anyone else experiencing this issue on the beta?

**Comment by creolis** [comment] 2018-10-20 19:20
I had exactly the same problem and kept debugging for several hours until I found out that there is ONE way to get the contacts syncing on my fresh and vanilla macOS 10.14 Mojave installation:

I removed all traces from earlier tries and used the following settings:

Contacts App > Add Account > Other Contacts Account:

CardDAV
**Account Type:** Advanced
**Username:** redacted
**Password:** redacted
**Server Address:** nextcloud.ser..........com
**Server Path:** /remote.php/dav/principals/users/testuser/
**Port:** 443
**Use SSL:** checked


As you can see, I used the server path usually expected to be dedicated to CalDAV,
not CardDAV, but since I ran out of sane options, I tried it anyway. To my surprise,
with success.

Still not sure what's going on there, but at least my contacts are now syncing again.
Can anybody else double check and confirm this?

**Comment by sebk-666** [comment] 2018-10-20 19:57
I just tried this with 10.14 and this works for me too!
Unbelievable!

**Comment by georgehrke** [comment] 2018-10-23 21:12
> As you can see, I used the server path usually expected to be dedicated to CalDAV,
not CardDAV,

@creolis What part of the UI / documentation made you think that this is url is dedicated for CalDAV?
(Because that assumption is wrong, it's for both CalDAV and CardDAV and actually the solution i described in #7519)

**Comment by georgehrke** [comment] 2018-10-23 21:15
I will close this as a duplicate of #7519

@nickian Please take note that there was a security hardening in macOS Mojave and CalDAV/CardDAV with password protection are no longer supported via http.

**Comment by georgehrke** [comment] 2018-10-23 21:15
Duplicate of #7519

**Closed by georgehrke** 2018-10-23 21:15 UTC
Labels: bug, feature: dav

**Comment by bencomp** [comment] 2019-01-08 09:52
@georgehrke Please don't take this personal, but if I may answer 'what part of the UI/documentation made you think that this url is dedicated for CalDAV?', for me it was the following.

The user documentation at [Synchronizing with macOS](https://docs.nextcloud.com/server/15/user_manual/pim/sync_osx.html) says nothing about CardDAV, so I tried to apply the logic of finding the CardDAV URL the same way as you find the CalDAV URL: by going in the Contacts app to the settings to find the correct URL for iOS/macOS. But it wasn't there; there is only a link to the individual address book.

Maybe it doesn't help that macOS (Mojave) requires users to add separate CalDAV and CardDAV accounts. If the accounts need to be separate, why should I expect the settings to be exactly the same?

Also, IMHO, the solution to this problem may have been found in #7519, but the problem descriptions are different. I would not consider this a duplicate issue. I will propose an update to the user documentation, as promised in <https://github.com/nextcloud/documentation/issues/127#issuecomment-452231744>.

**Comment by pcoorie** [comment] 2019-04-01 00:37
Thanks @creolis you are a lifesaver mate, worked instantly for me on  **Mojave 10.14.3** with **NextCloud 15.05** on **Ubuntu 18:40** LXC Container using Amazon S3 primary Storage.
