### ISSUE TITLE
Special characters are allowed for naming >> not good

### ISSUE THREAD

**Issue by Mululu** [nextcloud/server#23878] opened 2020-11-03 22:11 UTC
### Steps to reproduce
1. create folder with Folder name:  "test1 | test2"
2. Try to syncronize this folder with the desktop client
3. Does not work because the following character is in the Name folder: "|" and this character can not use in Windows Folder/files names

### Expected behaviour
You shouldn't be able to use the following special characters to name files or folders:
\  : * ? " <> |

### Actual behaviour
The following characters can currently be used as a file or folder name
\  : * ? " <> |

### Server configuration

**Operating system:**
Windows 64bit
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
20.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
update from older Version 
**Where did you install Nextcloud from:**
Server

**Comment by wiswedel** [comment] 2020-11-06 12:17
duplicate of https://github.com/nextcloud/server/issues/20482

**Closed by wiswedel** 2020-11-06 12:17 UTC
Labels: 0. Needs triage, bug
