### ISSUE TITLE
Unnessesary menu in files

### ISSUE THREAD

**Issue by dafitt** [nextcloud/server#31909] opened 2022-04-08 18:01 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I was browsing my uploaded photos in the file app (a very large collection of photos). But after a time I was very annoyed. You have to click a minimum of three times in order to apply a tag to a file (or a picture).
1. click the three dots
2. select the *single available* item "tags"
![Bildschirmfoto_2022-04-08_19-37-22](https://user-images.githubusercontent.com/50248238/162496523-218997f0-dcbe-4f78-99fc-6c4b66af75e2.png)

3. apply your tag
4. *I also found a small bug:* When you slide to the next picture with the arrow keys on your keyboard, the tag-list appears again. Therefor you have to click another time to click it away.
![Bildschirmfoto_2022-04-08_19-38-48](https://user-images.githubusercontent.com/50248238/162496496-daaac6f2-762c-4d8c-b91e-cf3ca070c6cb.png)

**Describe the solution you'd like**
Because of that I want to suggest to remove the unnessesary menu (the three dots) and just show the tag-box.

**Comment by joshtrichards** [comment] 2023-07-11 21:53
Hi @Digital-Robot - Thanks for the feedback. I agree there's probably some room for improvement in this area.

In the mean time, are you aware of the multiselect->tags work flow? It can streamline tagging multiple files considerably.

![image](https://github.com/nextcloud/server/assets/1731941/1e9f2d8b-bdc2-44d4-b875-fa2b92bac85f)

**Comment by skjnldsv** [comment] 2024-09-17 12:39
Duplicate of https://github.com/nextcloud/server/issues/29903

**Closed by skjnldsv** 2024-09-17 12:39 UTC
Labels: enhancement, design, 0. Needs triage, feature: tags
