### ISSUE TITLE
Show changelog when proposing app updates

### ISSUE THREAD

**Issue by dacoex** [nextcloud/server#20828] opened 2020-05-05 13:55 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Login into my admin page, Nectcloud suggest that I update some apps.
$NEXTCLOUD/index.php/settings/apps/updates

Sometimes, apps can cause problems.
This can happen when apps do not fully support latest version of nextcloud or are not fully stable.
Example from the past: groufolders blocked upgrades

**Describe the solution you'd like**
The page 
$NEXTCLOUD/index.php/settings/apps/updates
should have a link button or even an overlay 
this button would link to the changes log of the app version that shall be installed/upgraded to.
This link information is already available under:
$NEXTCLOUD/index.php/settings/apps
under the page generated for each app (details page)

In addition, it would be great to have some testing framework that checks apps for possible conflicts.

**Describe alternatives you've considered**
Alternative is manually opening the various & scattered github pages of the individula apps.

**Additional context**

**Comment by kesselb** [comment] 2020-05-05 14:28
Sounds like https://github.com/nextcloud/server/issues/9165

**Comment by dacoex** [comment] 2020-05-05 14:35
Yes, thanks.

Can you mark as duplicate?

**Comment by kesselb** [comment] 2020-05-05 14:43
Duplicate of #9165

**Closed by kesselb** 2020-05-05 14:43 UTC
Labels: 0. Needs triage, enhancement, feature: apps management, needs info
