### ISSUE TITLE
Group admin can not add users to their groups

### ISSUE THREAD

**Issue by GuiGuiSoft** [nextcloud/server#13174] opened 2018-12-20 11:54 UTC
### Steps to reproduce
1. Create following users  
![capture](https://user-images.githubusercontent.com/8069239/50283352-f58e8480-0455-11e9-8986-1574f5ddad09.png)
2. Log as CP1 user and go to the users' page

### Expected behaviour
CP1 can see Dev1 and add it to the Projet1 group.

### Actual behaviour
CP1 can not see Dev1 and can not add it to Projet1 group.

### Server configuration

**Operating system**:  
Demo.nextcloud.com (version of 20/12/2018)

**Comment by Nils160988** [comment] 2018-12-20 14:51
This seems to be a duplicate of https://github.com/nextcloud/server/issues/11334

**Comment by GuiGuiSoft** [comment] 2018-12-20 17:01
Documentation says:
![image](https://user-images.githubusercontent.com/8069239/50298961-af9ae600-0480-11e9-884b-b0181f82da9d.png)

How can a group admin add users to his group if he does not see other users ?
Maybe I don't understand how works the group admin role 😫

**Comment by wiswedel** [comment] 2019-08-14 09:06
> This seems to be a duplicate of #11334

correct. Closing this one.

**Closed by wiswedel** 2019-08-14 09:06 UTC
Labels: 0. Needs triage, bug
