### ISSUE TITLE
Upgrade Problem 17.0.10 to 18.0.10

### ISSUE THREAD

**Issue by JuergenLC** [nextcloud/server#24068] opened 2020-11-12 09:43 UTC
Upon updating I get the message:
InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.
and I am asked to post this as a potential bug. How shall I proceed?

**Comment by kesselb** [comment] 2020-11-12 10:34
Duplicate of https://github.com/nextcloud/server/issues/23174

**Closed by kesselb** 2020-11-12 10:34 UTC
Labels: 0. Needs triage, bug
