### ISSUE TITLE
[Bug]: reopen: https://github.com/nextcloud/server/issues/42612 THIS IS BUG after 28 file program denied to show uploaded fles and they are like new DONT UPDATE

### ISSUE THREAD

**Issue by Jordibgzashtita** [nextcloud/server#42616] opened 2024-01-08 02:07 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

after update nextcloud to beta as in past nextcloud peoples comment run beta update and dont wait. NOw it broke entire nextcloud debian.... and no file are displayed look logs and you will see there is file program bug

### Steps to reproduce

1.WAS updateding from stable to beta 
2.
3.

### Expected behavior

to make it work and have latest version. as official .zip is much hard to make it on hand.... but in feature will take precaution. and nextcloud need to make much more manuals.... chatgpt has helped me install this modules sudo apt install -y php php-curl php-cli php-mysql php-gd php-common php-xml php-json php-intl php-pear php-imagick php-dev php-common php-mbstring php-zip php-soap php-bz2 php-bcmath php-gmp php-apcu libmagickcore-dev that nextcloud only comment what they name is and NOT they install names. on internet they dont specify they name for debian and they throw missing module. after install them same no file is showing.... just like new is showing.... on deleted files it show all files... there is bug in file progam

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
{"reqId":"ZZtWOgSlYZGrGu4PhMnj3QAAAAI","level":3,"time":"2024-01-08T01:56:10+00:00","remoteAddr":"192.168.0.1","user":"root","app":"no app in context","method":"PUT","url":"/nextcloud/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Exception thrown: Exception","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"28.0.1.1","exception":{"Exception":"Exception","Message":"Call to a member function getTimestamp() on array in file '/var/www/nextcloud/apps/dav/lib/CalDAV/Status/StatusService.php' line 105","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Call to a member function getTimestamp() on array","Code":0,"Trace":[{"function":"OCA\\DAV\\CalDAV\\Status\\{closure}","class":"OCA\\DAV\\CalDAV\\Status\\StatusService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/Status/StatusService.php","line":97,"function":"array_filter"},{"file":"/var/www/nextcloud/apps/user_status/lib/Listener/UserLiveStatusListener.php","line":70,"function":"processCalendarStatus","class":"OCA\\DAV\\CalDAV\\Status\\StatusService","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":86,"function":"handle","class":"OCA\\UserStatus\\Listener\\UserLiveStatusListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":230,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":59,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":94,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":106,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/user_status/lib/Controller/HeartbeatController.php","line":100,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"heartbeat","class":"OCA\\UserStatus\\Controller\\HeartbeatController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/CalDAV/Status/StatusService.php","Line":105},"CustomMessage":"Exception thrown: Exception"},"id":"659b56437daf3"}
```

**Comment by Jordibgzashtita** [comment] 2024-01-08 02:33
![Untitled](https://github.com/nextcloud/server/assets/149943717/f22061de-1b4b-4214-bb65-f6de489ffce1)

**Comment by joshtrichards** [comment] 2024-01-08 02:44
> nextcloud need to make much more manuals.... chatgpt has helped me install this modules sudo apt install -y php php-curl php-cli php-mysql

https://docs.nextcloud.com/server/latest/admin_manual/installation/example_ubuntu.html

The Photospheres isn't part of Server:

https://github.com/nextcloud/files_photospheres

Duplicate of #42612

**Closed** 2024-01-08 02:44 UTC
Labels: bug, 0. Needs triage

**Comment by Jordibgzashtita** [comment] 2024-01-08 02:53
YESSSS after removeing phottoshere file star twork.... nextlcoud need to scan is there is plugins who make nextcloud uselsess and isable them
