### ISSUE TITLE
Files replaced by empty files

### ISSUE THREAD

**Issue by m1cm1c** [nextcloud/server#15489] opened 2019-05-09 20:42 UTC
### Steps to reproduce
I have no idea how to reproduce this. 

### Expected behaviour
Files that are added via an external app like FolderSync should appear just like that on the computers where the respective directories are synced.

### Actual behaviour
I use FolderSync on my Android phone to add pictures to my Nextcloud instance. Most of the time, this works. But sometimes, pictures of size 0 appear on my computers. When I search for them in Nextcloud's web interface, they are also shown as having size 0. But there always is an older version from the date where the file was created that is of the correct size. I can download these images and they actually are the images they should be. The web interface also lets me revert to that "previous version". However, this change is not synced to my computers, so they always remain with the empty files even after reverting.

### Server configuration

**Operating system**:
Kubuntu 18.04 running the `4.15.0-48-generic` kernel.

**Web server:**
Apache 2

**Database:**
MariaDB

**PHP version:**
7.2.17

**Nextcloud version:** (see Nextcloud admin page)
15.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
I'm not entirely sure.

**Where did you install Nextcloud from:**
It's the GitHub version.

**Signing status:**
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**
I did not install any additional apps.

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ""***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.6.1",
        "overwrite.cli.url": "https:\/\/"***REMOVED SENSITIVE VALUE***\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:**
Mozilla Firefox 66.0.4

**Operating system:**
Kubuntu 18.04 (kernel `4.15.0-48-generic`)

#### Web server error log
<details>
<summary>Web server error log</summary>

I'm sorry but I'm not sure which log to look for here as Apache 2 has several.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
< nextcloud.log | grep "name of some affected image" | wc
      0       0       0
```
</details>

#### Browser log
<details>
I don't think any browser log is relevant for this.
</details>

**Comment by m1cm1c** [comment] 2019-05-10 11:31
Before you close this as possibly being caused by FolderSync: There still definitely is a bug in Nextcloud as the web interface shows something that's different from what's on any of the connected computers as the files remain empty on them. The Android app displays the images correctly (after reversion via the web interface).

**Comment by szaimen** [comment] 2021-05-20 12:59
I think this is a duplicate of https://github.com/nextcloud/server/issues/21315

**Closed by szaimen** 2021-05-20 12:59 UTC
Labels: 0. Needs triage, bug
