### ISSUE TITLE
Update Failure 

### ISSUE THREAD

**Issue by bensocket** [nextcloud/server#7434] opened 2017-12-09 01:03 UTC
Update to 12.0.3

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_storages_numeric_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_storages_numeric_id_... ^
Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_storages_numeric_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_storages_numeric_id_... ^
The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by abcbuzhiming** [comment] 2017-12-09 03:45
I hava same issue when I want to update 12.0.3 to 12.0.4。After testing, I found this issue only display on database postgresql；If I Use MySQL，this issue does not display

**Comment by abcbuzhiming** [comment] 2017-12-09 05:35
Added: The reason of this, because the SEQUENCE name "oc_storages_numeric_id_seq" does not have min_value, increment_by

**Comment by MrHat2010** [comment] 2017-12-10 16:19
@abcbuzhiming Did you find a solution for this?

**Comment by MorrisJobke** [comment] 2017-12-11 14:14
Duplicate of #5930

**Closed by MorrisJobke** 2017-12-11 14:14 UTC

**Comment by abcbuzhiming** [comment] 2017-12-13 13:59
@MrHat2010 no solution ，the reason is nextcloud not support postgresql 10.1
