### ISSUE TITLE
Internal / private link

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12877] opened 2018-12-06 10:11 UTC
- [x] Android @tobiasKaminsky 
- [x] Desktop @camilasan 
- [x] iOS @marinofaggiana 
- [x] Server @nextcloud/server-triage 

There is a feature request to have the internal/private link (clipboard on the right) also on android.

![image](https://user-images.githubusercontent.com/5836855/49577223-3f9c4400-f947-11e8-9edc-a0fe6ec12676.png)

I discussed this with Jan and he is not very satisfied about the current situation.
Also Marie mentioned that she by accident copied this link to another person and this  one could not open the file (as not shared and not even on server).

So, how could this get improved? Once we have a decision, this can also be done the same on all clients.

@nextcloud/designers 
@marinofaggiana 
@camilasan: newest 2.5.0 has this in option menu: "copy private link" / "copy public link"

**Comment by jancborchardt** [comment] 2018-12-21 03:15
I remember having commented something like this in an issue:
- We should get rid of the extra "internal link", especially because the icon is being confused for being an actual link
- The link in "Sharing" could just be enabled when you click "Copy" for the first time or open the 3-dot menu, no distinction needed for the first one you create.
- When you share any link to a file or folder with someone who has an account on that instance, they will see their general logged-in view instead of the share link view.

What do you think?

**Comment by jancborchardt** [comment] 2018-12-21 03:16
Also ref issue on Android: https://github.com/nextcloud/android/issues/795

**Comment by juliushaertl** [comment] 2018-12-22 21:44
> We should get rid of the extra "internal link", especially because the icon is being confused for being an actual link
> The link in "Sharing" could just be enabled when you click "Copy" for the first time or open the 3-dot menu, no distinction needed for the first one you create.

There is still a use-case for the internal link. Users want to share a file with a user (not via a share link) and then use the internal link as a reference in emails/chat/any other communication.

> When you share any link to a file or folder with someone who has an account on that instance, they will see their general logged-in view instead of the share link view.

:+1: That would be a nice improvement. You should not end up on a public page for a file if you are logged in and can access it though the regular files app.

**Comment by jancborchardt** [comment] 2018-12-22 22:34
> There is still a use-case for the internal link. Users want to share a file with a user (not via a share link) and then use the internal link as a reference in emails/chat/any other communication.

Yes, I get the use-case of the internal link. But doing it via a share link which automatically detects if the user viewing it has an account fulfills the case much more seamlessly, while not messing with the overall UX.

**Comment by tobiasKaminsky** [comment] 2018-12-23 09:40
The only downside with this is that you have to create a new share link, explicitly for this user. You cannot "randomly" use the same link for many users:
- I write a mail to whole company and want to show my cool xmas tree
- I now can put it in a company-wide shared folder and link to the file

How would I do this then?

(overall I really like the idea that server is smart and handles sharing for you, like it is now with sharing, where you get one contact and not 3-4x the same contact, but with different sharing methods)

**Comment by jancborchardt** [comment] 2018-12-23 14:32
@tobiasKaminsky I'm not sure I understand it –why wouldn't you be able to use the same link for many people, whether they are on the Nextcloud or not?

**Comment by jancborchardt** [comment] 2018-12-23 16:06
> You might want to share a private link without creating a public share link.

Yes, but my point is that a "Share link" is not "Public" as it’s not guessable.

If that’s not the case, then I have another proposal:

![internal link](https://user-images.githubusercontent.com/925062/50385348-722e9680-06d4-11e9-8827-b730507ef850.png)

Yes I know it adds yet another entry there, but it’s way better than having the "copy" icon so present on the top as it is right now. Also we have **Share menu cleanup #12178** to rework the menu entries.

And the idea is that if you send the link to someone who has an account (or maybe even who via a different link has different permissions), they will be presented with the "highest" view possible to them. So if you paste an internal link on a forum, no one will see anything. But at the same time, if one of the collaborators on a folder opens a "Read-only" link, they will see their logged in view where they have all permissions.

**Comment by tobiasKaminsky** [comment] 2018-12-23 17:52
> why wouldn't you be able to use the same link for many people, whether they are on the Nextcloud or not?

Hm. This might work, so I can just create a "public share link" and if someone on the same cloud is following the link, then he would not see the "public share page", but instead the regular cloud view with the desired file.

Then I guess, people might get confused. Especially if you create this link as readonly, but users on the same cloud can edit it (as their share is editable).

(maybe I am thinking too complicated)

(( merry xmas ))

**Comment by jospoortvliet** [comment] 2018-12-27 11:42
People can essentially already just copy the url in the browser to get the 'private' link, right?

Now we can have multiple links (and hopefully soon name them) it might make sense to have a 'internal' link on top of the list... It is annoying that it takes a spot but it is less confusing for users.

Of course, at the same time, we should let public links work smarter - as in, automatically become interal share links for logged in users if a file is already shared or allow users to make it a share in one click.

**Comment by jancborchardt** [comment] 2018-12-27 14:33
Alright, so who is up for working on the implementation? @juliushaertl @skjnldsv @violoncelloCH @kevgathuku maybe? ;) No rush, we could also set it to 17.

**Comment by MorrisJobke** [comment] 2019-01-03 13:06
Another idea for the private link and public link confusion: how about a way to request access to this non-available resource. So once you click the link there is on the "forbidden" page also the option to request permission from the owner in whatever way (leaving your account or email address as contact details).

**Comment by tobiasKaminsky** [comment] 2019-01-04 07:57
> request permission from the owner in whatever way

This then requires again interaction from the share owner, so I would rather avoid this.

**Comment by MorrisJobke** [comment] 2019-01-04 13:42
> > request permission from the owner in whatever way
> 
> This then requires again interaction from the share owner, so I would rather avoid this.

That was more meant as an additional way of accessing files (because other platforms do it the same way if it is a valid link, but you are missing the permission). Also this is not fully related to this issue here.

**Comment by tobiasKaminsky** [comment] 2019-02-12 07:21
So what is the conclusion here? @jancborchardt can you make a mockup, so that we all know what we want to have?

**Comment by jancborchardt** [comment] 2019-02-13 16:06
The proposal and mockup at https://github.com/nextcloud/server/issues/12877#issuecomment-449645998 still stands. :)

**Comment by tobiasKaminsky** [comment] 2019-03-13 14:01
Conclusion: move it into share list next to "add to collections", etc. and name it "Share internal".

**Comment by jancborchardt** [comment] 2019-03-13 14:05
What @tobiasKaminsky said but with the wording "Copy internal link". :)

**Comment by tobiasKaminsky** [comment] 2019-03-13 14:06
…and on mobile you also need to have a possibility to share ;-)

**Comment by tobiasKaminsky** [comment] 2019-03-13 16:46
same like "link creation" on android:
- copy to clipboard
- possibility to send link to any other app

**Comment by juliushaertl** [comment] 2019-04-08 12:26
> When you share any link to a file or folder with someone who has an account on that instance, they will see their general logged-in view instead of the share link view.

Related issues to this https://github.com/nextcloud/server/issues/721 https://github.com/nextcloud/server/issues/6462

**Comment by jospoortvliet** [comment] 2019-04-09 19:01
Yeah, this is confusing the heck out of people. Problem with https://github.com/nextcloud/server/issues/12877#issuecomment-449645998 is that it only starts to work when you already made a sharing link (and you don't NEED to create a shared link at all if you want to share a file that is already shared) and that it seems link-specific, but it isn't (there's no difference in access rights for example).

The problem is really the fundamental difference between sharing internally and externally, and how to refer to a file that is already shared internally.

As I said, copy-pasting the URL actually works (as it includes the share link) but that is on modern browsers becoming hard to discover.

Sorry to be difficult, but this solution doesn't work and I do think this is a real issue. @shironextcloud brought up she used the internal link for quite a while after being hired, mistakenly... We should at least look for a quick fix. I think having an item in the list of shares called 'internal share' or so (or the 'only for collaborators' would work - it makes the shared link list longer, but at least it is clear and better than the little copy icon we now use in two places.

**Comment by jancborchardt** [comment] 2019-04-18 15:08
> Problem with #12877 (comment) is that it only starts to work when you already made a sharing link

No. ;) It’s one of the options of creating a link. There’s simply 4 different types, and an internal link is one type of link.

**Comment by tobiasKaminsky** [comment] 2019-04-29 08:07
> > Problem with #12877 (comment) is that it only starts to work when you already made a sharing link
> 
> No. ;) It’s one of the options of creating a link. There’s simply 4 different types, and an internal link is one type of link.

I tried it on latest master and as soon as you click on "+" next to "share link" it creates a read-only public link.
If one would now change the option to "internal link" the public link needs to be removed, leading to unnecessary server calls.
On the other hand postponing link creation is also somehow tricky, as we do not have/want a "confirm/save" button.


![image](https://user-images.githubusercontent.com/5836855/56883324-9aede080-6a66-11e9-84f7-b4093920bc5f.png)

(if one selects "internal link" all other option needs to be hidden, as they all are unrelated)

**Comment by jancborchardt** [comment] 2019-05-21 16:45
So @skjnldsv had a call and also talked about this. We decided the above proposal was a bit too confusing too, and a simpler and quicker solution would be this. Basically we just move the icon from being so present and being the main "Copy" action just down in the sharing tab, with explanation visible.

Before & after:
![internal link](https://user-images.githubusercontent.com/925062/58114636-7796fb00-7bf8-11e9-8b27-16fd4c89918f.png)

**Comment by jospoortvliet** [comment] 2019-05-29 07:54
For what it's worth, I think that that is the perfect solution.

**Comment by shironextcloud** [comment] 2019-05-29 17:05
I agree with @jospoortvliet , this is really great, love it :D

**Comment by tobiasKaminsky** [comment] 2019-05-29 18:13
This is how it looks on Android :-)

![](https://user-images.githubusercontent.com/5836855/58566559-2955ad80-8231-11e9-9882-09c3bcb9e347.png)

**Comment by skjnldsv** [comment] 2019-05-30 06:23
@tobiasKaminsky on a side note, the share link could use a revamp to fit the current website design :thinking: 
We don't use the check box anymore :wink:

**Comment by tobiasKaminsky** [comment] 2019-05-31 06:16
Hehe, true. 
This is my plan for the next version after this one, to have it 1:1 to new share flow on web ui: with projects, multiple links, etc.

**Comment by jancborchardt** [comment] 2019-05-31 11:25
@tobiasKaminsky looks good! Only 2 details:
- The "Copy internal link" text color should be black / normal text color too. Sorry this was messed up in my mockup. :) The subline is fine.
- The entry should be very last in the list (yes even after all the sharees) because otherwise it’s going to call undue attention again. Just like projects are also below sharees in the web interface.

**Comment by skjnldsv** [comment] 2019-10-29 13:56
#15719 is merged, go go go Clients :D

**Comment by tobiasKaminsky** [comment] 2019-11-01 11:07
@skjnldsv on Android I have it this way:
![image](https://user-images.githubusercontent.com/5836855/68020877-2196ab00-fca0-11e9-8a24-6964e537adb6.png)

You can click on the whole area for copying.
Is there a reason one have to click on the tiny icon on the right?

**Comment by skjnldsv** [comment] 2019-11-01 11:14
@tobiasKaminsky unity on the whole column.
All the other entries have this button on the right. Clicking the whole entry is also not discoverable as it doesn't have any feedback nor does look like a button.

**Comment by tobiasKaminsky** [comment] 2019-11-01 11:15
Thanks for explanation.
I guess that this can be a bit different between our platforms.

**Comment by skjnldsv** [comment] 2019-11-01 11:16
> I guess that this can be a bit different between our platforms.

I would say no :p
Let's be consistent.

**Comment by skjnldsv** [comment] 2019-11-01 11:22
> I'll suggest you do the same as it's weird to have some entries with the action on the right and then one where the full row is clickable :)

Actually, let me backpedal here ^^
I'm confused because your sidebar (screenshot from may) look like our old sidebar, so it really have this "website" vibe. I'm guessing if you go with proper material design, the full entry is expected to be clickable.

Is there an opened issue for how the other entries differs from what we currently have? (like new link share... )
Also, your internal link button does not copy to clipboard but open the sharing menu of android, we should be clear about what it does.

Opening the sharing is good I'd say, but then I would not have the row called "copy internal link", but "Share internal link" cc @jancborchardt

**Comment by tobiasKaminsky** [comment] 2019-11-01 11:25
> Is there an opened issue for how the other entries differs from what we currently have? (like new link share... )

Yes, https://github.com/nextcloud/server/issues/16228 and https://github.com/nextcloud/server/issues/15752

**Comment by tobiasKaminsky** [comment] 2019-11-01 11:25
> "Share internal link" cc @jancborchardt

This is a good idea!

**Comment by tobiasKaminsky** [comment] 2020-01-16 14:09
@marinofaggiana on iOS this is missing completely, please add it on bottom just like on server.

**Comment by marinofaggiana** [comment] 2020-08-09 14:29
done.

**Closed** 2020-08-17 05:31 UTC
Labels: client: 💻 desktop, client: 🤖🍏 mobile, design, feature: sharing, high, overview
