### ISSUE TITLE
Duplicate contact found in 'search contacts' list

### ISSUE THREAD

**Issue by diplodata** [nextcloud/server#9379] opened 2018-05-03 10:41 UTC
When a user is added and removed, their entry may persist under 'search contacts' under certain conditions.  I'm unclear exactly how this manifests, but can describe the steps I've taken with respect to a particular user:

### Steps to reproduce
1. Admin to add a user e.g. username 'Test', email 'fred@test.com'
2. Maybe necessary for another user to interact with the Test user - e.g. in Talk
3. Admin to remove Test user
4. Admin to add new user e.g. 'Fred', with same email 'fred@test.com'
5. Admin/someone to search for "fred" in Contacts.

### Expected behaviour

Only user 'Fred' should appear in search results, because 'Test' has been removed.

### Actual behaviour

I now see 2 entries showing - 'Test' as well as 'Fred'.  Hovering over email icons shows the same email address for both.

When Admin can switch back to Users and reconfirm that 'Test' does not officially exist, yet the entry will continue to appear under 'search contacts'.

### Server configuration
**Operating system**: Ubuntu 16.04
**Web server:** . Apache 2.4.33
**Database:** .  MariaDB
**PHP version:** . 7.2
**Nextcloud version:** 13.0.2 RC 1
**Where did you install Nextcloud from: a daily build

**Comment by gohrner** [comment] 2018-06-30 15:36
Probably / possibly the last remaining problem described in https://help.nextcloud.com/t/ldap-user-cleanup-doesnt-work/14707/6 could stem from the same issue.

(Summary: The mentioned user uses LDAP auth and used "Clear Username-LDAP User Mapping" without really knowing what it does. As suggested in the related thread, he then re-created identical local users with the same names and deleted those to get rid of remains of the inconsistent LDAP users. This fixed most stuff for him, but the contact suggestions keep displaying duplicates, with one invalid / unusable entry.)

I basically did the same (I think knowing what I do when I used "Clear Username-LDAP User Mapping") but also did not expect the duplicate user suggestion.

The problem is that after deleting a user, entries pointing to it stay left over in the table "oc_cards_properties". Manually deleting the appropriate cardids seems to fix this, but most likely is no recommended fix...

**Comment by osscombat** [comment] 2018-08-22 08:28
exactly the same issue as @gohrner - after switching off the LDAP backend back to local user accounts some LDAP accounts remains in the 'search contacts'. What is the proper way to get rid of them?

**Comment by gohrner** [comment] 2018-08-22 08:49
> What is the proper way to get rid of them?

Not sure if it's the "proper" way, but, guessing from the lack of replies from developers also fear that there currently may not be a proper way - I deleted the stale entries from oc_cards_properties using manually written SQL queries. This solved the issue for me.

I first identified the stale "card ids" with the help of the UID field and then deleted all entries referencing those card ids.

**Comment by osscombat** [comment] 2018-08-22 10:08
yes, doubt there could be other solution. Maybe my workaround would be useful here:
1. select your Nextcloud DB in mysql client.
2. `select * from oc_cards_properties;` and find your stale accounts from the whole table.
3. `select * from oc_cards_properties where addressbookid='your_id';` you can narrow your list if you have more that one addressbookid value.
4. `delete from oc_cards_properties where addressbookid='your_id' and cardid='your_id';` that does the trick.
5. exit mysql client.

**Comment by ChristophWurst** [comment] 2019-04-30 07:58
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.

**Closed by ChristophWurst** 2019-04-30 07:58 UTC

**Comment by Antairez** [comment] 2019-08-21 13:04
I found a possible solution here:
https://forum.owncloud.org/viewtopic.php?t=34465

**Comment by Antairez** [comment] 2019-08-21 13:13
Seems like owncloud implemented a fix for this:
https://central.owncloud.org/t/duplicate-users/18601
