### ISSUE TITLE
default sharing permission not working?

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#22173] opened 2020-08-10 14:18 UTC
See also https://help.nextcloud.com/t/standard-share-settings-by-admin-doesnt-work/89312
(e.g. discussion and screenshots)

I think the default sharing permissions set in Settings -> Administration -> Sharing are not working.
Unset to blank:
Create [] 
Change  []
Delete []
Reshare []

changes the database seemingly correct to:

```
|core|shareapi_default_permission_cancreate |no|
|core|shareapi_default_permission_candelete |no|
|core|shareapi_default_permission_canshare |no|
|core|shareapi_default_permission_canupdate |no|
|core|shareapi_default_permissions |1|
```
But in file sharing Files -> Sharing -> Username 
set it to 

Allow editing [x]
Allow creating [x]
Allow deleting [x}
Allow resharing [x]

### Steps to reproduce
set link of sharing
get default all set but it is unset.

### Expected behaviour
correct default setting for sharing folders and files

### Actual behaviour
wrong default setting for sharing folders and files

Problem on my server and on the server of the other person in nextcloudforum-discussion.

### Server configuration
default for Nextcloud 19.0.1
**Operating system:**
CentOS
**Web server:**
nginx
**Database:**
MariaDB
**PHP version:**
default
**Nextcloud version:** (see Nextcloud admin page)
19.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
oder versions seems to work (see link at top)
**Where did you install Nextcloud from:**
standard download

**Comment by g4ndy** [comment] 2020-08-12 13:16
I can confirm that default user permissions really doesn't work since i updated to nextcloud 19.0.1  (snap2)

**Comment by msfuture** [comment] 2020-08-13 08:44
Not working here as well. Broken since update to 19.0.1!

**Comment by kevstewa** [comment] 2020-08-24 20:56
Also affected here since a version 18 minor point release. Was hoping the upgrade to 19.0.1 fixed the issue but it still exists.

**Comment by jolly-jump** [comment] 2020-09-07 16:55
Same problem here. We still use 18.x.
Is there some fix in sight?

**Comment by msfuture** [comment] 2020-09-07 18:47
Fixed in 19.0.2 here...

**Comment by jolly-jump** [comment] 2020-09-07 20:47
To be more precise: #21967 fixed it for 19, and as in #22073 mentioned, it is "only" a fix in the files_sharing_tab.js https://github.com/nextcloud/server/pull/21967/files.
I might try to backport this into 18, if my upgrade to 19 fails (e.g. since ubuntu 18.04 is not suitable....grrrr.)

**Comment by MorrisJobke** [comment] 2020-11-29 20:30
https://github.com/nextcloud/server/pull/21963#issuecomment-735449431

**Comment by MorrisJobke** [comment] 2020-11-29 20:30
So it might be fixed once the backport is in.

**Comment by MorrisJobke** [comment] 2020-11-30 09:34
Backport is done.

**Closed by MorrisJobke** 2020-11-30 09:34 UTC
Labels: 0. Needs triage, bug

**Comment by pasith3e** [comment] 2021-11-15 12:40
Hi,

the Problem persist for me in Version  22.2.1 for external Shares, internal Shares have the Correct Permission set.
This User may have the same Problem:
https://help.nextcloud.com/t/standard-share-settings-by-admin-doesnt-work/89312/16

**Comment by timololipop** [comment] 2022-05-26 09:22
Problem still persists
