### ISSUE TITLE
Sharing a file via a password protected link kind of broken

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/server#2355] opened 2016-11-27 18:53 UTC
### Steps to reproduce
1. upload a file
2. tick the box to share it via link
3. tick the box to password protect the shared file
4. choose a password that does not conforms with the password policy ( one big Letter one number eg)
5. try the link it will open the file without the password no error message or are you sure.

### Expected behavior
I would expect that the nextcloud instance warns me or even aborts the process of sharing when the user ticked the password protect box and did choose a not conform password.

### Actual behavior
The link will get shared without a password. The Password protect box will have a redlining around it but will not warn or abort the share which will me completely password free.

### Server configuration
**Operating system**:
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 15 2016 20:44:43
Server's Module Magic Number: 20120211:37
Server loaded:  APR 1.5.1, APR-UTIL 1.5.4
Compiled using: APR 1.5.1, APR-UTIL 1.5.4
Architecture:   64-bit

**Database:**
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 7.0.13-1 dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-1 dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
version: 11.0.0.4
versionstring: 11.0 beta
edition:

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated nextcloud from 9 > 10 > 11beta

**Where did you install Nextcloud from:**
official website download signed tar.gz

```


**List of activated apps:**
<details>
<summary>Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.3.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 1.3.1
  - lookup_server_connector: 1.0.0
  - news: 10.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.0
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: true
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
</summary>
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
    "system": {
        "instanceid": "ocdwzxwi729i",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.magicbroccoli.de"
        ],
        "datadirectory": "\/var\/www\/magicbroccoli.de\/data",
        "version": "11.0.0.4",
        "installed": true,
        "cipher": "AES-256-CFB",
        "dbtype": "mysql",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "defaultapp": "files",
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "magicbroccoli.de",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "mail.server-speed.net",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/server\/",
        "upgrade.disable-web": false,
        "has_internet_connection": true,
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "logdateformat": "d.m.Y - H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 52428800,
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "appstore.experimental.enabled": true,
        "appcodechecker": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/magicbroccoli.de\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_filesize_image": 25,
        "overwrite.cli.url": "https:\/\/cloud.magicbroccoli.de",
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto",
        "activity_expire_days": 80,
        "filesystem_check_changes": 0,
        "theme": "",
        "maintenance": false,
        "singleuser": false,
        "updater.release.channel": "beta"
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes local,nextcloud,Google,Dropbox,nfs

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by MorrisJobke** [comment] 2016-11-28 09:52
cc @schiessle

**Comment by nickvergessen** [comment] 2016-11-28 11:30
Shows a clear warning for me on current master:
> ![bildschirmfoto vom 2016-11-28 12-27-34](https://cloud.githubusercontent.com/assets/213943/20666773/3028a8fa-b566-11e6-9fc2-a6ba2d423a2a.png)

The problem is, you can also fail to add a password later on, in which case we shouldn't kill the existing link share, because that breaks the URL you sent people already.

So nothing to fix from my pov, but let's wait for @schiessle

**Comment by mightyBroccoli** [comment] 2016-11-28 11:51
Yes that could be the case that somebody adds a password afterwards. But that little red box around is not a warning it is just displaying nothing more, because the link gets published right away with out any conformation if the user even wants that, because the actively ticked the password protect box. That's my train of taught.
I get the idea that when somebody afterwards changed the password or even adds a password and its not conform with the settings that the link couldnt be deleted or something but could there be another "Yes I do want to share WITHOUT a password" window to alert the user he is not sharing with a password? Or something like that.

**Comment by schiessle** [comment] 2016-11-28 13:48
I'm with @nickvergessen. Setting the password failed, the user gets a clear indicator that it failed and why, if the user doesn't perform any additional action the file is shared without a password. I would assume that most people will retry to set a password if they really need it.

> But that little red box around is not a warning it is just displaying nothing more

@mightyBroccoli it should look like the screenshot here https://github.com/nextcloud/server/issues/2355#issuecomment-263248542. If this is not the case for you we should try to find out why? Anything in your browsers java script console?

> "Yes I do want to share WITHOUT a password" window to alert the user he is not sharing with a password?

I'm quite sure our UX experts don't like the "do you really want to do what you do" type dialogs and I have to agree with it.

> Or something like that.

In the admin settings you can enforce that every link share needs to have a password. Would this be a option for you?

**Comment by mightyBroccoli** [comment] 2016-11-28 14:26
> it should look like the screenshot here #2355 (comment). If this is not the case for you we should try to find out why? Anything in your browsers java script console?
@schiessle yes it does look like that for me. I now enabled the option to enforce password protection to get around this. Perhaps my standpoint is just off, I taught when the user ticks the box nextcloud should make that tick count and kind of "enforce" the user to choose a valid password. 

> I would assume that most people will retry to set a password if they really want to.
i hope that most of my users will get used to the password protect enforcement, I would like to lift that force to not password protect that one picture of a dog. 
I guess I will test the enforce option then.

**Comment by nickvergessen** [comment] 2016-11-28 15:05
Closing as per above

**Closed by nickvergessen** 2016-11-28 15:05 UTC
Labels: bug, feature: sharing
