### ISSUE TITLE
External storage support - SMB - cannot access files

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/server#26549] opened 2021-04-13 20:04 UTC
Hi,

I have a folder "scans" from my scanner mounted via SMB/CIFS (localhost)
Since my upgrade to 21.0.1, I cannot download / open files from that folder.

Usually I'm scanning a doc, the PDF appears in NC, and I can read the PDF.
That's no long working...

**Comment by szaimen** [comment] 2021-04-13 20:10
Duplicate of https://github.com/nextcloud/server/issues/26457

**Closed by szaimen** 2021-04-13 20:10 UTC
Labels: 0. Needs triage, bug
