### ISSUE TITLE
Uploading 0kb jpg fails

### ISSUE THREAD

**Issue by ReinerNippes** [nextcloud/server#13596] opened 2019-01-14 22:57 UTC
Upload a 0kb (empty) jpg to NC 15.0.2 fails.

{"reqId":"vo3IvVGJQriT4qQZHj6s","level":3,"time":"2019-01-14T22:49:11+00:00","remoteAddr":"xxxxx","user":"yyyy","app":"PHP","method":"PUT","url":"\/remote.php\/webdav\/Share\/Leeres%20Bild.jpg","message":"feof(): supplied resource is not a valid stream resource at \/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/File.php#172","userAgent":"Go-http-client\/1.1","version":"15.0.2.0"}

**Comment by danielkesselberg** [comment] 2019-01-15 14:21
Thank you for reporting this issue :+1: 

Duplicate of https://github.com/nextcloud/server/issues/13276
Fix in https://github.com/nextcloud/server/pull/13468 (should be released with 15.0.3 currently planned for 2019-02-21)

**Closed by danielkesselberg** 2019-01-15 14:21 UTC
