### ISSUE TITLE
Large directories not downloading in 18.0.6

### ISSUE THREAD

**Issue by dd5fz** [nextcloud/server#21470] opened 2020-06-18 13:15 UTC
When I try to download a large directory (4.3 GB), I get the following error:

=======================================

TypeError: Argument 2 passed to OC\Streamer::__construct() must be of the type int, float given, called in /var/www/html/nextcloud/lib/private/legacy/files.php on line 167

/var/www/html/nextcloud/lib/private/legacy/files.php - line 167:
OC\Streamer->__construct(OC\AppFramework\Http\Request {}, 4576540812, 32)

/var/www/html/nextcloud/apps/files/ajax/download.php - line 64:
OC_Files::get("/gggreen/Da ... r", "Ausstellung ... g", { head: false})

/var/www/html/nextcloud/lib/private/Route/Route.php - line 155:
require_once("/var/www/ht ... p")

<<closure>>
OC\Route\Route->OC\Route\{closure}("*** sensiti ... *")

/var/www/html/nextcloud/lib/private/Route/Router.php - line 299:
call_user_func(Closure {}, { _route: "f ... "})

/var/www/html/nextcloud/lib/base.php - line 1008:
OC\Route\Router->match("/apps/files/ajax/download.php")

/var/www/html/nextcloud/index.php - line 38:
OC::handleRequest()

=======================================

I am running NextCloud on a Raspberry Pi 3 b+

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

Linux raspberrypi3 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux

Hardware: BCM2835
Revision: a020d3
Serial: 0000000014fc683c
Model: Raspberry Pi 3 Model B Plus Rev 1.3

Nextcloud Version is 18.0.6

PHP Version: 7.3.14
Memory Limit: 1 GB
Max Execution Time: 3600
Upload max size: 1 GB

Database Type: mysql
Version: 10.3.22
Size: 38,3 MB

Web server: Apache/2.4.38 (Raspbian)

**Comment by kesselb** [comment] 2020-06-18 14:10
Duplicate of https://github.com/nextcloud/server/issues/12422

**Closed by kesselb** 2020-06-18 14:10 UTC
Labels: 0. Needs triage, bug
