### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getLogo" as such route does not exist

### ISSUE THREAD

**Issue by mwries** [nextcloud/server#5838] opened 2017-07-22 16:53 UTC
### Steps to reproduce
Not known.

Got the error twice, and both times the error was preceded by this warning at exactly the same time:
Warning - core - Trusted domain error. "103.18.108.89" tried to access using "***REMOVED SENSITIVE VALUE***" as host.

### Expected behaviour
No error

### Actual behaviour
Error

### Server configuration
**Operating system**: Linux nextcloud.systemsnavigator.com 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** pgsql PostgreSQL 9.5.7 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.18-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:** 
Nextcloud VM

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0

Disabled:
 - admin_audit
 - encryption
 - federation
 - files_external
 - files_pdfviewer
 - files_videoplayer
 - firstrunwizard
 - issuetemplate-master
 - previewgenerator
 - survey_client
 - user_external
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.11.131",
        "nextcloud.systemsnavigator.com"
    ],
    "datadirectory": "\/var\/ncdatamnt",
    "overwrite.cli.url": "https:\/\/nextcloud.systemsnavigator.com\/",
    "dbtype": "pgsql",
    "version": "12.0.0.29",
    "dbname": "nextcloud_db",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "oc6fxph0akpf",
    "mail_smtpmode": "smtp",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "loglevel": "2",
    "log_type": "file",
    "logfile": "\/var\/ncdatamnt\/nextcloud.log",
    "logtimezone": "Europe\/Amsterdam",
    "maintenance": false,
    "mail_from_address": "martijn.riesenkamp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "systemsnavigator.com",
    "mail_smtpauth": 1,
    "mail_smtphost": "smtp.office365.com",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpsecure": "tls",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "skeletondirectory": ""
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
	<summary>LDAP config</summary>

	```
	With access to your command line run e.g.:
	sudo -u www-data php occ ldap:show-config
	from within your Nextcloud installation folder

	Without access to your command line download the data/owncloud.db to your local
	computer or access your SQL server remotely and run the select query:
	SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


	Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
	```
</details>
### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getLogo" as such route does not exist.
/var/www/nextcloud/lib/private/Route/Router.php - line 339: Symfony\Component\Routing\Generator\UrlGenerator->generate('theming.Theming...', Array, 1)
/var/www/nextcloud/lib/private/Route/CachingRouter.php - line 60: OC\Route\Router->generate('theming.Theming...', Array, false)
/var/www/nextcloud/lib/private/URLGenerator.php - line 70: OC\Route\CachingRouter->generate('theming.Theming...', Array)
/var/www/nextcloud/apps/theming/lib/ThemingDefaults.php - line 156: OC\URLGenerator->linkToRoute('theming.Theming...')
/var/www/nextcloud/lib/public/Defaults.php - line 186: OCA\Theming\ThemingDefaults->getLogo(true)
/var/www/nextcloud/core/templates/layout.guest.php - line 45: OCP\Defaults->getLogo()
/var/www/nextcloud/lib/private/Template/Base.php - line 176: include('/var/www/nextcl...')
/var/www/nextcloud/lib/private/Template/Base.php - line 151: OC\Template\Base->load('/var/www/nextcl...', NULL)
/var/www/nextcloud/lib/private/legacy/template.php - line 202: OC\Template\Base->fetchPage(NULL)
/var/www/nextcloud/lib/private/legacy/template.php - line 224: OC_Template->fetchPage()
/var/www/nextcloud/lib/private/Template/Base.php - line 132: OC_Template->fetchPage()
/var/www/nextcloud/lib/base.php - line 809: OC\Template\Base->printPage()
/var/www/nextcloud/lib/base.php - line 1082: OC init()
/var/www/nextcloud/index.php - line 38: require_once('/var/www/nextcl...')
{main}
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by mwries** [comment] 2017-07-22 16:54
cc @enoch85

**Comment by enoch85** [comment] 2017-07-22 16:59
https://github.com/nextcloud/server/issues/5838#issuecomment-317196001 related?

**Comment by MorrisJobke** [comment] 2017-07-23 19:12
> #5347 Already fixed?

Correct - fixed in #5840 

Duplicate of #5347

**Comment by MorrisJobke** [comment] 2017-07-23 20:40
> Correct - fixed in #5840

Wrong - it is fixed in #5821

**Comment by dimamergel** [comment] 2017-08-17 07:42
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getLogo" as such route does not exist.

    /kunden/422580_33719/dropbox/lib/private/Route/Router.php - line 339: Symfony\Component\Routing\Generator\UrlGenerator->generate('theming.Theming...', Array, 1)
    /kunden/422580_33719/dropbox/lib/private/URLGenerator.php - line 77: OC\Route\Router->generate('theming.Theming...', Array)
    /kunden/422580_33719/dropbox/apps/theming/lib/ThemingDefaults.php - line 165: OC\URLGenerator->linkToRoute('theming.Theming...')
    /kunden/422580_33719/dropbox/lib/public/Defaults.php - line 186: OCA\Theming\ThemingDefaults->getLogo(true)
    /kunden/422580_33719/dropbox/core/templates/layout.guest.php - line 45: OCP\Defaults->getLogo()
    /kunden/422580_33719/dropbox/lib/private/Template/Base.php - line 176: include('/kunden/422580_...')
    /kunden/422580_33719/dropbox/lib/private/Template/Base.php - line 151: OC\Template\Base->load('/kunden/422580_...', NULL)
    /kunden/422580_33719/dropbox/lib/private/legacy/template.php - line 202: OC\Template\Base->fetchPage(NULL)
    /kunden/422580_33719/dropbox/lib/private/legacy/template.php - line 224: OC_Template->fetchPage()
    /kunden/422580_33719/dropbox/lib/private/Template/Base.php - line 132: OC_Template->fetchPage()
    /kunden/422580_33719/dropbox/core/templates/403.php - line 7: OC\Template\Base->printPage()
    {main}

**Comment by brentrealbt** [comment] 2017-10-23 01:12
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getLogo" as such route does not exist.

```Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getLogo" as such route does not exist.
/var/www/fs.e-cred.co/html/lib/private/Route/Router.php - line 339: Symfony\Component\Routing\Generator\UrlGenerator->generate('theming.Theming...', Array, 1)
/var/www/fs.e-cred.co/html/lib/private/URLGenerator.php - line 77: OC\Route\Router->generate('theming.Theming...', Array)
/var/www/fs.e-cred.co/html/apps/theming/lib/ThemingDefaults.php - line 165: OC\URLGenerator->linkToRoute('theming.Theming...')
/var/www/fs.e-cred.co/html/lib/public/Defaults.php - line 186: OCA\Theming\ThemingDefaults->getLogo(true)
/var/www/fs.e-cred.co/html/core/templates/layout.guest.php - line 45: OCP\Defaults->getLogo()
/var/www/fs.e-cred.co/html/lib/private/Template/Base.php - line 176: include('/var/www/fs.e-c...')
/var/www/fs.e-cred.co/html/lib/private/Template/Base.php - line 151: OC\Template\Base->load('/var/www/fs.e-c...', NULL)
/var/www/fs.e-cred.co/html/lib/private/legacy/template.php - line 202: OC\Template\Base->fetchPage(NULL)
/var/www/fs.e-cred.co/html/lib/private/legacy/template.php - line 224: OC_Template->fetchPage()
/var/www/fs.e-cred.co/html/lib/private/Template/Base.php - line 132: OC_Template->fetchPage()
/var/www/fs.e-cred.co/html/core/templates/403.php - line 7: OC\Template\Base->printPage()
{main}

**Comment by Haidafraid** [comment] 2018-01-26 22:22
Same problem, same error under 12.0.5 here... (still)... It started under 12.0.3 when I tried to establish a logo with transparent elements.... I suppose this was to much for the favicon generator...

I see this error whenever I load my NC Instance. The favicon does not show the defined logo anymore - it shows the standard logo instead. I tried reinstalling the theming app - but no help there...
What can I do to solve this?

`Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getLogo" as such route does not exist.

    .../lib/private/Route/Router.php - line 339: Symfony\Component\Routing\Generator\UrlGenerator->generate('theming.Theming...', Array, 1)
    .../lib/private/URLGenerator.php - line 77: OC\Route\Router->generate('theming.Theming...', Array)
    .../apps/theming/lib/ThemingDefaults.php - line 165: OC\URLGenerator->linkToRoute('theming.Theming...')
    .../lib/public/Defaults.php - line 186: OCA\Theming\ThemingDefaults->getLogo(true)
    .../core/templates/layout.guest.php - line 45: OCP\Defaults->getLogo()
    .../lib/private/Template/Base.php - line 176: include('/home/marxnimb/...')
    .../lib/private/Template/Base.php - line 151: OC\Template\Base->load('/home/marxnimb/...', NULL)
    .../lib/private/legacy/template.php - line 202: OC\Template\Base->fetchPage(NULL)
    .../lib/private/legacy/template.php - line 224: OC_Template->fetchPage()
    .../lib/private/Template/Base.php - line 132: OC_Template->fetchPage()
    .../core/templates/403.php - line 7: OC\Template\Base->printPage()
    {main}`

**Comment by MorrisJobke** [comment] 2018-01-27 12:49
@nextcloud/theming Do you have an idea?

**Comment by azazel75** [comment] 2018-01-29 04:31
I got hit by this as well

**Comment by azazel75** [comment] 2018-01-29 06:05
it's strange. On the login, the client has downloaded the right logo, but it has opacity:0 and the containing div (class=logo) has the standard nextcloud logo as bg, and that is what is shown

**Comment by enoch85** [comment] 2018-01-29 10:57
Works for me on Firefox 57.

**Comment by physio** [comment] 2018-01-29 12:31
same problem for me, i use the standard image of aws marketplace. I have only upgraded from 12.0.2.0 to 12.0.5.3

**Comment by juliushaertl** [comment] 2018-01-29 17:37
All the error messages seem to be caused by the 403.php template. Please check your webserver config and make sure the redirects to those files are removed according to the docs: https://github.com/nextcloud/documentation/pull/392/files

Apps are not loaded when calling that page directly and therefore the theming app routes cannot be found.

**Closed by juliushaertl** 2018-01-29 17:37 UTC
Labels: bug

**Comment by Haidafraid** [comment] 2018-01-30 20:29
Please excuse my slow-wittedness... but I just can not find any hints in the documentation concerning my server configuration. 
My Nextcloud installation works under WHM/cpanel  that is CENTOS 7.4. I do not use nginx - it is an apache 2.4.29. Could you please spell it out for me, where I should change anything in my apache configuration, because everything looks just like a standard configuration. There are no special Error Documents defined IMHO. Could you please provide the link to the necessary apache config changes in the docs? Thank you so very much for your help.
Cheers

**Comment by juliushaertl** [comment] 2018-02-01 09:07
Ah sorry, I didn't check how it is used on NC12. It has been fixed for Nextcloud 13 but not backported to stable12. https://github.com/nextcloud/server/pull/5890
