### ISSUE TITLE
Clicking a blocked folder sends user back to root folder

### ISSUE THREAD

**Issue by Germs2004** [nextcloud/server#10306] opened 2018-07-20 02:26 UTC
Nextcloud 13.0.4

1) Create a folder called "Folder1"
2) In Folder1, create a folder called "Folder2".  Now you have Root > Folder1 > Folder2.
3) On Folder2, add a Tag and create a Rule Group that blocks access to that folder.
4) With a user that is blocked from Folder2, click Folder1.  All is well.  You are now in Folder1.
5) Click Folder2.  Notice that you get the error on top about the operation being denied, and the system takes you all the way back to the root folder, so you are looking at the outside of Folder1 again.

Expected behavior:
It should pop up the Operation Denied message but should not take me back to the root folder.  It should leave me right where I was, Folder1.  (It would also be nice if that popup message were more helpful like "You do not have permission to access this folder.")

**Comment by MorrisJobke** [comment] 2018-07-20 14:58
cc @nickvergessen regarding the access control app

**Comment by nickvergessen** [comment] 2018-07-20 15:00
Known issue: We propably should check the permissions in the web UI and just not allow navigating into such folders

**Comment by nickvergessen** [comment] 2018-07-20 15:01
Duplicate of https://github.com/nextcloud/files_accesscontrol/issues/84

**Closed by nickvergessen** 2018-07-20 15:01 UTC
Labels: bug
