### ISSUE TITLE
Can't modify (delete, unlink, etc) shared files

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#11223] opened 2018-09-14 16:10 UTC
### Steps to reproduce

Difficult to say.  I can only tell what I experience now.

A user shared a file.  When I click at this file (foto) the response is: Error can not generate a preview.

Files details can't be fetched, nor can the file be removed.

Perhaps the following was the cause:
I emptied oc_filecache to make the upgrade from 13.0.5 to 13.0.6 possible (#11221) possible.

There are more files that show this problem.

### Expected behaviour
The file should be unshared, removed or whatever, for example with an override possibility.

### Actual behaviour
At this moment I just can't process the file.

Is there any way I can get rid of the files (database query?)

### Server configuration

**Operating system**: linux 4.4

**Web server:**  2.4.23

**Database:** sqlite3 3.8.10

**PHP version:** 7.0.7

**Nextcloud version:** 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** nextcloud.com

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
?php
$CONFIG = array (
  'datadirectory' => '/srv/owncloud',
  'dbtype' => 'sqlite3',
  'defaultapp' => 'bookmarks',
  'version' => '13.0.6.1',
  'installed' => true,
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'log_rotate_size' => 1048576,
  'loglevel' => 1,
  'theme' => '',
  'trusted_domains' => 
  array (
  ),
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'htaccess.RewriteBase' => '/',
  'trashbin_retention_obligation' => 'auto, 30',
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

error_log: nothing

acces_log:
```
 - - [14/Sep/2018:18:05:26 +0200] "DELETE /remote.php/webdav/DiaNaarFoto HTTP/1.1" 503 238```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"1zxoJJtdksLZGYFywdyq","level":4,"time":"2018-09-14T18:07:06+02:00","remoteAddr":"83.162.232.159","user":"george","app":"webdav","method":"DELETE","url":"\/remote.php\/webdav\/DiaNaarFoto","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Storage is temporarily not available\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/vhosts\\\/<fqdn>\\\/nextcloud-13.0.6\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(178): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('DiaNaarFoto')\\n#1 \\\/srv\\\/www\\\/vhosts\\\/<fqdn>\\\/nextcloud-13.0.6\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(291): Sabre\\\\DAV\\\\Tree->delete('DiaNaarFoto')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/srv\\\/www\\\/vhosts\\\/<fqdn>\\\/nextcloud-13.0.6\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/srv\\\/www\\\/vhosts\\\/<fqdn>\\\/nextcloud-13.0.6\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/srv\\\/www\\\/vhosts\\\<fqdn>\\\/nextcloud-13.0.6\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/srv\\\/www\\\/vhosts\\\<fqdn>\\\/nextcloud-13.0.6\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/srv\\\/www\\\/vhosts\\\<fqdn>\\\/nextcloud-13.0.6\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/vhosts...')\\n#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/vhosts\\\<fqdn>\\\/nextcloud-13.0.6\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":163}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.81 Safari\/537.36","version":"13.0.6.1"}
```
</details>

Can this be fixed, how further?

**Comment by jcklpe** [comment] 2018-10-29 19:45
I'm have a similar problem with a federated share that went offline. I can see in some of the other issue pages that it is possible to fix this using a SQL query to delete the share, but seems like there should be a more robust fallback for dealing with this issue.

**Comment by skjnldsv** [comment] 2019-10-30 20:57
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-10-30 20:57 UTC
Labels: 0. Needs triage, bug
