### ISSUE TITLE
Caldav after Opt out of IMip still advertising auto-scheduling

### ISSUE THREAD

**Issue by dugite-code** [nextcloud/server#8572] opened 2018-02-28 02:31 UTC
Using Thunderbird with nextcloud caldav event invites cannot be sent even if the `Send invitations to attendees` option is unset.

As commented by @zyro23 on #6811 in order to allow clients to know the server won't send event invites the line `$server->addPlugin(new \OCA\DAV\CalDAV\Schedule\Plugin());` in `apps/dav/lib/Server.php` needs to be commented out.

@georgehrke Stated that moving this line into the `if ($sendInvitations)` section would not be advisable as this might break free busy.

As I don't use Free/busy I have moved that line and will report any other issues I encounter with this.

**Comment by georgehrke** [comment] 2018-02-28 07:57
Duplicate of https://github.com/nextcloud/server/issues/8423

Please comment there in the future

**Closed by georgehrke** 2018-02-28 07:57 UTC

**Comment by dugite-code** [comment] 2018-03-01 01:02
Opps sorry, apparently user name searches don't work so I missed that
