### ISSUE TITLE
Theming app doesn't work when pretty URLs is enabled

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#359] opened 2016-07-10 19:28 UTC
### Steps to reproduce
1. Setup NC without pretty URLs
2. Build a theme
3. Switch to using pretty URLs

### Expected behaviour

The theme should still work

### Actual behaviour

The default theme is used

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:** 7.0.8

**Nextcloud version:** (see Nextcloud admin page) 9.0.52

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** zip

#### Browser log
<details>
<summary>Browser log</summary>
```
Failed to load resource: the server responded with a status of 404 (https://projectx.gchq.gov.uk/apps/theming/styles.css?v=21 Failed to load resource)
```
</details>

-----
@jancborchardt @LukasReschke

**Comment by LukasReschke** [comment] 2016-07-11 07:16
This seems like a duplicate of https://github.com/nextcloud/server/issues/315, that said: I can't reproduce this in any of my environments.

Can you let me know what kind of server environment you are running? It works fine on all of mine … even including some freshly setup Docker containers.

**Closed by LukasReschke** 2016-07-11 07:16 UTC
Labels: bug, feature: theming

**Comment by oparoz** [comment] 2016-07-11 09:30
FreeBSD with hand-compiled web stack.
Apache 2.4.23
PHP 7.0.8 PHP-FPM
mod_security 2.9.1

There must be 2 rewrite configs since the path `apps/theming/styles.css` doesn't exist on the server.

**Comment by oparoz** [comment] 2016-07-11 09:37
Ah, no, it reaches the controller...
So, looking at the curl response, it seems we're getting the data, but a 404 is sent anyway, so must be a bug in `DataDownloadResponse`
