### ISSUE TITLE
Duplicate Contacts in Nextcloud 13

### ISSUE THREAD

**Issue by Hardy4next** [nextcloud/server#8562] opened 2018-02-27 11:29 UTC
We have duplicate Contacts in Nextcloud 13

**Steps to reproduce**
Nothing to reproduce

Using LDAP/AD-Integration

Steps to reproduce

Nothing to reproduce

Expected behaviour

Actual behaviour

Using LDAP/AD-Integration

**Server configuration**
nothing changed

**Operating system:**
Ubuntu Linux 16.04.3
**Web server:**
Apache
**Database:**
MySQL version 5.7.21
**PHP version:**
PHP 7.0.25
**Nextcloud version: (see Nextcloud admin page)**
13.0.0
Updated from an older Nextcloud/ownCloud or fresh install:
Updated from an older Nextcloud 
Where did you install Nextcloud from:
Updater

When I log in as Administrator I see under User-Administration only one user
![grafik](https://user-images.githubusercontent.com/36501132/36726261-6ab89b8c-1bb9-11e8-85d2-7679f0f84836.png)

When i click in the status bar on the User-Icon I see duplicate contacts
![grafik](https://user-images.githubusercontent.com/36501132/36726361-cb178e48-1bb9-11e8-82f6-38dc84aac8c0.png)

How can  I fix it?

**Comment by MorrisJobke** [comment] 2018-02-27 12:30
Duplicate of #4643

**Closed by MorrisJobke** 2018-02-27 12:30 UTC
