### ISSUE TITLE
Default language only applies to first created user

### ISSUE THREAD

**Issue by Fr4meR** [nextcloud/server#14817] opened 2019-03-23 11:16 UTC
### Steps to reproduce
1. Set `'default_language' => 'de_DE'`
2. Create new User via admin section
3. Create another new User

### Expected behaviour
Both new users should have `de_DE` as language.

### Actual behaviour
The first user has `de_DE` as language, the second one has `en`.

### Server configuration

**Operating system**:
Debian 9

**Web server:**
Apache/2.4.25 

**Database:**
10.1.37-MariaDB-0+deb9u1 Debian 9.6

**PHP version:**
PHP 7.3.3

**Nextcloud version:** (see Nextcloud admin page)
15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_fulltextsearch: 1.2.6
  - files_fulltextsearch_tesseract: 1.2.0
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.11.1
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - fulltextsearch: 1.2.5
  - fulltextsearch_elasticsearch: 1.2.4
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - serverinfo: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - gallery
  - passwords
  - sharebymail
  - support
  - survey_client
  - systemtags
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de_DE",
        "default_locale": "de_DE",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filesystem_check_changes": 1,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distribute": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 3,
        "logtimezone": "Europe\/Berlin"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox 65.0.2 (64-Bit) / Google Chrome 73.0.3683.86 (Official Build) (64-bit)

**Operating system:**
Windows 10

**Comment by j-ed** [comment] 2019-03-23 11:49
Unfortunately I cannot replicated your issue. The `default_language` setting works fine for the first and every additional user. I've just double-checked it on my server.

Are you sure that you've read the [**Nextcloud documenation**](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/language_configuration.html?highlight=language#language-locale) which points out that the parameter is only used if the used web browser doesn't send any language?
Additional it might be of interest that a specific [**Nextcloud help forum**](https://help.nextcloud.com)  exists to address program related questions. There you would have found another possible [**explanation**](https://help.nextcloud.com/t/cannot-change-language-on-personal-info-page/49313)  why the language isn't set as expected.

**Comment by MorrisJobke** [comment] 2019-03-25 08:28
Let's close this ticket for now. Thanks @j-ed for the explanation. If this turns out to be reproducible we can reopen the ticket.

**Closed by MorrisJobke** 2019-03-25 08:28 UTC
Labels: 0. Needs triage, bug
