### ISSUE TITLE
make links (in at least text app) better visible under dark theme

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/server#36464] opened 2023-01-31 22:03 UTC
**Is your feature request related to a problem? Please describe.**
using NC25 dark mode, links in e.g. the text app are black on a black background which makes them unreadable.

**Describe the solution you'd like**
link with a different colour than the background

**Describe alternatives you've considered**
not using dark theme

**Additional context**
as per https://github.com/nextcloud/text/issues/3559, this related to both links and the background both using the same primary color, which goes to black under the dark theme:

![text app showing near invisible link](https://user-images.githubusercontent.com/59349105/206904117-754ccece-ea12-4dab-9c33-4e51ffbd0a5a.png)

**Comment by susnux** [comment] 2023-02-01 20:26
This is only the case if you set the primary color to black (appearance settings -> background -> custom color).

So I think this is about making the background setting independent to the primary color.

**Comment by joshtrichards** [comment] 2023-09-07 15:13
This appears fixed in NC27 even with black set as a custom black background color. I can't find the relevant PR, but I'm not able to reproduce it.

**Closed by joshtrichards** 2023-09-07 15:13 UTC
Labels: enhancement, 0. Needs triage, feature: theming
