### ISSUE TITLE
[Bug]: Problems Spaming Activity Notification Emails (AD Group added or removed)

### ISSUE THREAD

**Issue by sincomil** [nextcloud/server#33193] opened 2022-07-11 11:52 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

At unknown conditions Nextcluod Users are receiving email messages about activity that was never happened:
About that administrator added some one to “Domain Users” group or was removed from the same group. Messages can be received by the same user multiple times per day. E.g. at morning users getting notification about they was added to Domain Users, then 15min later get another message that they were removed, and one hour later again was added.

We have more that 50000 users in Active Direcotry, so users can be very angry about this messages. Our current "workaround" is to disable any SMTP activity from Nextcloud servers, so no notification at all can be sent by it.

### Steps to reproduce

This is an issue produced on many other users, associated topic in NC forum is [here](https://help.nextcloud.com/t/problems-spaming-activity-mails-after-update-ad-group-added-or-removed)

### Expected behavior

Users should never receive messages about false or non-existent operations

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

PostgreSQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.com\/nextcloud",
        "dbtype": "pgsql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Moscow",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filesystem_check_changes": 1,
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 15,
        "log_rotate_size": 104857600,
        "maintenance": false,
        "trashbin_retention_obligation": "auto,1",
        "theme": "",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mysql.utf8mb4": true,
        "default_phone_region": "RU"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupfolders: 10.0.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.1
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - dashboard
  - encryption
  - files_texteditor
  - recommendations
```

**Comment by szaimen** [comment] 2023-01-23 14:43
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by junsve** [comment] 2023-02-28 10:33
Problem exist on 25.0.3
I disabled e-mals for activity but adding removing still occurs which mean users can't always log in.

**Comment by junsve** [comment] 2023-03-08 10:17
Also in 25.0.4. 
Anyone understanding the cause and can propose a workaround (e-mails already deactivated)?

**Comment by junsve** [comment] 2023-03-20 14:44
I think this is same bug as https://github.com/nextcloud/server/issues/29832 
I am using PHP 8.0.27 and AlmaLinux 9.1

**Comment by junsve** [comment] 2023-06-13 09:24
Bug still present in NC 27.0.0 RC3, now PHP 8.2.

**Comment by Keridos** [comment] 2024-03-06 02:03
Still happening on 28.0.3

**Comment by joshtrichards** [comment] 2024-09-06 17:35
Duplicate of #29832

**Closed by joshtrichards** 2024-09-06 17:35 UTC
Labels: bug, feature: ldap, 0. Needs triage, feature: activity and notification, 25-feedback
