### ISSUE TITLE
add option to disable check for imagick SVG support, or remove the check completely

### ISSUE THREAD

**Issue by sebalis** [nextcloud/server#25866] opened 2021-03-02 04:51 UTC
Nextcloud 21 includes a new check for SVG support in the php-imagick module on the /settings/admin/overview page, but apparently there are security concerns against installing the required packages as mentioned in https://docs.nextcloud.com/server/21/admin_manual/configuration_files/previews_configuration.html?highlight=svg#previews-configuration so I do not want to enable this feature. I would however still like to be able to see an “all clear” status in the settings overview. I would therefore propose that an option be added to config.php that can disable this check. In any case it seems strange to have Nextcloud generate a warnng about a missing feature when the Nextcloud documentation warns against using that same feature. So maybe the check should be removed completely.

**Comment by awaw9** [comment] 2021-03-02 05:24
مرسل من هاتف Samsung Galaxy الذكي.
-------- الرسالة الأصلية --------من: sebalis <notifications@github.com> التاريخ: ٢‏/٣‏/٢٠٢١  ٧:٥٢ ص  (GMT+03:00) إلى: nextcloud/server <server@noreply.github.com> نسخة: Subscribed <subscribed@noreply.github.com> الموضوع: [nextcloud/server] add option to disable check for imagick SVG support, or remove the check completely (#25866) 

Nextcloud 21 includes a new check for SVG support in the php-imagick module on the /settings/admin/overview page, but apparently there are security concerns against installing the required packages as mentioned in https://docs.nextcloud.com/server/21/admin_manual/configuration_files/previews_configuration.html?highlight=svg#previews-configuration so I do not want to enable this feature. I would however still like to be able to see an “all clear” status in the settings overview. I would therefore propose that an option be added to config.php that can disable this check. In any case it seems strange to have Nextcloud generate a warnng about a missing feature when the Nextcloud documentation warns against using that same feature. So maybe the check should be removed completely.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/nextcloud/server/issues/25866",

"url": "https://github.com/nextcloud/server/issues/25866",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by awaw9** [comment] 2021-03-02 05:24
Cمرسل من هاتف Samsung Galaxy الذكي.
-------- الرسالة الأصلية --------من: sebalis <notifications@github.com> التاريخ: ٢‏/٣‏/٢٠٢١  ٧:٥٢ ص  (GMT+03:00) إلى: nextcloud/server <server@noreply.github.com> نسخة: Subscribed <subscribed@noreply.github.com> الموضوع: [nextcloud/server] add option to disable check for imagick SVG support, or remove the check completely (#25866) 

Nextcloud 21 includes a new check for SVG support in the php-imagick module on the /settings/admin/overview page, but apparently there are security concerns against installing the required packages as mentioned in https://docs.nextcloud.com/server/21/admin_manual/configuration_files/previews_configuration.html?highlight=svg#previews-configuration so I do not want to enable this feature. I would however still like to be able to see an “all clear” status in the settings overview. I would therefore propose that an option be added to config.php that can disable this check. In any case it seems strange to have Nextcloud generate a warnng about a missing feature when the Nextcloud documentation warns against using that same feature. So maybe the check should be removed completely.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/nextcloud/server/issues/25866",

"url": "https://github.com/nextcloud/server/issues/25866",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by kesselb** [comment] 2021-03-02 08:21
Duplicate of https://github.com/nextcloud/server/issues/13099

**Closed by kesselb** 2021-03-02 08:21 UTC
Labels: 0. Needs triage, enhancement
