### ISSUE TITLE
Can't view pdf file with character `#`

### ISSUE THREAD

**Issue by shunlir** [nextcloud/server#23546] opened 2020-10-18 01:44 UTC
### Steps to reproduce
1. Upload a pdf file with it's name containing character `#`
2. Click the uploaded pdf file in nextcloud Web UI to view it

### Expected behaviour
Should be able to view the content of the pdf file

### Actual behaviour
The message ' Missing PDF file. ' in a red box is showing, with following details:
> PDF.js v2.4.456 (build: 228a591c)
> Message: Missing PDF "http://<ip-removed>/remote.php/dav/files/admin/Documents/CLR%20via%20C#,%20Fourth%20Editionpdf".

### Server configuration
docker image `nextcloud` (id `5ab9b95de2ca`) + `mariadb`
**Operating system:**
Debian GNU/Linux 10 (buster)
**Web server:**
apache2 2.4.38-3+deb10u4
**Database:**
mariadb
**PHP version:**
Not sure
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nextcloud     | 192.168.0.14 - - [18/Oct/2020:09:39:36 +0800] "GET /apps/files_pdfviewer/js/pdfjs/build/pdf.worker.js?v=2.0.1 HTTP/1.1" 200 57344 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
nextcloud     | 192.168.0.14 - - [18/Oct/2020:09:39:36 +0800] "GET /remote.php/dav/files/admin/Documents/CLR%20via%20C HTTP/1.1" 404 12514 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2020-10-18 07:50
May related to https://github.com/nextcloud/server/issues/22912

**Comment by ste1n** [comment] 2020-10-23 07:47
I have the same issue. Can't view PDF's with a "#" character in the file name.

**Comment by skjnldsv** [comment] 2020-11-07 22:35
Duplicate of https://github.com/nextcloud/viewer/issues/415

**Closed by skjnldsv** 2020-11-07 22:35 UTC
Labels: 0. Needs triage, bug
