### ISSUE TITLE
Files containing "%" breaks File list NC 14-01-14.03

### ISSUE THREAD

**Issue by panspectron2017** [nextcloud/server#11829] opened 2018-10-14 16:24 UTC
### Steps to reproduce
1. Copy a file containing a "%" in the filename to any directory in the files section of a user
2. Do a files:scan on that users files 
3. Viewing the files via the web-interface won't work

### Expected behaviour
File list should appear. 

### Actual behaviour
Empty directory.

### Server configuration

** OS:** Debian

**Apache 2.4.18**

**Database:** mysql 5.7

**PHP version:** 7.0

**Nextcloud version:**  14.01 bis 14.03

**Updated from an older Nextcloud/:** 12.x ...13...

**Where did you install Nextcloud from:** Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.2
  - circles: 0.15.1
  - cloud_federation_api: 0.0.1
  - cms_pico: 0.9.7
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - gpxedit: 0.0.9
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - music: 0.9.2
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "aud.ixls.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/aud.ixls.eu\/nextcloud",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "version_retention_obligation": "auto, 100",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "notify_email_calendar": "1",
            "notify_email_calendar_event": "1",
            "notify_email_calendar_todo": "1",
            "notify_email_comments": "1",
            "notify_email_favorite": "1",
            "notify_email_file_changed": "1",
            "notify_email_file_created": "1",
            "notify_email_file_deleted": "1",
            "notify_email_file_restored": "1",
            "notify_email_public_links": "1",
            "notify_email_remote_share": "1",
            "notify_email_shared": "1",
            "notify_email_systemtags": "1",
            "notify_setting_batchtime": "3600",
            "notify_setting_self": "1",
            "notify_setting_selfemail": "1",
            "notify_stream_calendar": "1",
            "notify_stream_calendar_event": "1",
            "notify_stream_calendar_todo": "1",
            "notify_stream_comments": "1",
            "notify_stream_favorite": "1",
            "notify_stream_file_changed": "1",
            "notify_stream_file_created": "1",
            "notify_stream_file_deleted": "1",
            "notify_stream_file_favorite": "0",
            "notify_stream_file_restored": "1",
            "notify_stream_public_links": "1",
            "notify_stream_remote_share": "1",
            "notify_stream_shared": "1",
            "notify_stream_systemtags": "1",
            "types": "filesystem"
        },
        "admin_notifications": {
            "enabled": "no",
            "installed_version": "1.0.2",
            "types": "logging"
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "1929"
        },
        "bruteforcesettings": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.2",
            "types": ""
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "0.15.1",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "0.0.1",
            "types": "filesystem"
        },
        "cms_pico": {
            "enabled": "yes",
            "installed_version": "0.9.7",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "2.1.6",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "ajax",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1517141825.2024",
            "lastcron": "1539533305",
            "lastupdateResult": "[]",
            "lastupdatedat": "1539533220",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "shareapi_allow_group_sharing": "yes",
            "shareapi_allow_links": "yes",
            "shareapi_allow_resharing": "no",
            "shareapi_allow_share_dialog_user_enumeration": "no",
            "shareapi_enabled": "yes",
            "updater.secret.created": "1539532910",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_markdown": {
            "enabled": "yes",
            "installed_version": "2.0.4",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.3.2",
            "types": ""
        },
        "files_reader": {
            "enabled": "no",
            "installed_version": "1.2.3",
            "types": "filesystem"
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.6.2",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": ""
        },
        "files_trackdownloads": {
            "enabled": "no",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.7.1",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.1.0",
            "types": ""
        },
        "gpxedit": {
            "enabled": "yes",
            "installed_version": "0.0.9",
            "types": ""
        },
        "groupfolders": {
            "enabled": "no",
            "installed_version": "1.3.3",
            "types": "filesystem"
        },
        "logreader": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "types": ""
        },
        "mindmaps": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": ""
        },
        "music": {
            "enabled": "yes",
            "installed_version": "0.9.2",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.4.2",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": "authentication"
        },
        "ojsxc": {
            "apiSecret": "bSFm6pUKfriSC25U2FkvjXJ",
            "enabled": "no",
            "installed_version": "3.4.2",
            "types": "prelogin"
        },
        "onlyoffice": {
            "enabled": "no",
            "installed_version": "2.0.4",
            "skey": "1538809068819",
            "types": "filesystem"
        },
        "ownpad": {
            "enabled": "no",
            "installed_version": "0.6.8",
            "ocsid": "174679",
            "ownpad_etherpad_enable": "no",
            "types": ""
        },
        "password_policy": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "2.0.13",
            "types": "prevent_group_restriction",
            "wopi_url": "https:\/\/collabora.ixls.eu"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "socialsharing_email": {
            "enabled": "no",
            "installed_version": "1.0.4",
            "types": ""
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "4.0.0",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.7",
            "types": ""
        },
        "theming": {
            "enabled": "no",
            "installed_version": "1.4.5",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "updatenotification": {
            "core": "13.0.4.0",
            "enabled": "yes",
            "installed_version": "1.4.1",
            "mail": "0.8.1",
            "spreed": "3.2.2",
            "types": "",
            "update_check_errors": "0"
        },
        "user_external": {
            "enabled": "no",
            "installed_version": "0.4",
            "types": "authentication,prelogin"
        },
        "user_usage_report": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        }
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** any

**Operating system:** any

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
nothing important there
```
</details>

**Comment by MorrisJobke** [comment] 2018-10-15 06:50
Duplicate of #11744 - fixed in 14.0.4

**Closed by MorrisJobke** 2018-10-15 06:50 UTC
Labels: bug, feature: dav
