### ISSUE TITLE
"your storage is almost full" notification spam

### ISSUE THREAD

**Issue by J0WI** [nextcloud/server#25293] opened 2021-01-23 13:26 UTC
### Steps to reproduce
From a new installation:
1. limit the storage quota of a user to something
2. upload content with this user using the web interface, so that >90% of storage limit is used
3. reload the page and click the home icon in breadcrumb menu multiple times

### Expected behaviour
Display a single decent notification that your storage is almost full or use the notifications app/api if available.

### Actual behaviour
"your storage is almost full" notification is spamed for every click and you can't even see the main menu anymore to access user settings.

![nextcloud-storage-almost-full-bug](https://user-images.githubusercontent.com/5710638/105579430-79767180-5d7e-11eb-93b6-b7d89512a99e.png)

**Comment by much-doge** [comment] 2021-01-28 12:32
Same issue https://github.com/nextcloud/server/issues/24847#issuecomment-752411192

**Comment by jkufner** [comment] 2021-02-23 15:49
I think, this should not be a notification. The available space should be a widget in the first row, next to the folder path. If there is a plenty of space, it may disappear, when there is a little space remaining, it could be in red (see top right corner):

![Screenshot_20210223_164731](https://user-images.githubusercontent.com/16572/108868886-ed629e80-75f6-11eb-8fe3-9e3d5e59448b.png)

**Comment by seblu** [comment] 2021-05-12 02:38
Same mass messages when real filesystem is almost full.

**Comment by szaimen** [comment] 2023-01-23 10:40
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by newhinton** [comment] 2023-02-08 18:06
Also, it shows the percentage to the second decimal place. It could also be shortened to a "rough" estimate so that we dont have a decimal point at all.

**Comment by skjnldsv** [comment] 2024-08-01 05:23
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-08-01 05:23 UTC
Labels: bug, 1. to develop, feature: files, 25-feedback
