### ISSUE TITLE
Cant sync - Precondition failed after upgrade from 11.0.2 to 12.0

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/server#5238] opened 2017-06-02 23:10 UTC
After upgrade the server from 11.0.2 to 12.0, a few users are reporting the client is not being able to sync anymore. I got the client log from one of them and it shows:
```
6/2/17 7:47:31 PM, Programas/mendeleydesktop_1.17.9-stable_amd64.deb,           Documents/nextCloud,Error downloading https://server.fqn/remote.php/dav/files/ana/Programas/mendeleydesktop_1.17.9-stable_amd64.deb-chunking-3534620524-14-0 - server replied: Precondition failed (An If-Match header was specified and the resource did not exist)
6/2/17 7:47:27 PM, Programas/ChemDoodle-linux-8.1.0.bin,           Documents/nextCloud,Error downloading https://server.fqn/remote.php/dav/files/ana/Programas/ChemDoodle-linux-8.1.0.bin-chunking-1120403321-13-1 - server replied: Precondition failed (An If-Match header was specified and the resource did not exist)
```

I have checked her directory directly in the server file system, and  the file mendeleydesktop_1.17.9-stable_amd64.deb already exists and it is there. The same for the ChemDoodle-linux-8.1.0.bin file.

The client is 2.3.1-20170514.194620~xenial1

I also tried to run a rescan on the server, but it didn't help;

### Server configuration

**Operating system**:
Debian Jessie

**Web server:**
Apache 2.4.10-10+deb8u8

**Database:**
mysql 5.5.55-0+deb8u1

**PHP version:**
5.6.30+dfsg-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 11.0.2

**Where did you install Nextcloud from:**
download.nextcloud.com/server/releases/nextcloud-12.0.0.tar.bz2

**Comment by cyablo** [comment] 2017-06-03 13:11
Same for me, Error came with Client update to 2.3.1,

**Comment by pafcioooo** [comment] 2017-06-05 18:50
Same error, windows client 2.3.1

I diid some testes and noticed strange behavior:
- I had downloaded 14MB zip file that did not get synced (file1)
- I copied the 14MB zip file and renamed its extension to pdf (file2) - this file got synced.
- small files (100kB) get synced no matter what extension is.
- I copied above pdf (file2) to another file (file3) with zip extension and file3 got synced.
- I changed an extension of original file1 to exe extnsion - it got synced
- I changed file1 extension from exe to zip and it stayed synced.
Crazy:-)

**Comment by fanff** [comment] 2017-06-06 19:50
Hey  dudes

Same error here with a linux client 2.3.1 ubuntu, server version 12

I tried to reproduce @pafcioooo steps but my results are a bit different as I noticed the tests are not that very reproducible. I guess it might depends of wether your "replace" the file or "make a new one", timing of creation/change while upload is not done yet. Also i notice the bigger the file, the harder to sync.

**Comment by 1manprojects** [comment] 2017-06-09 16:52
I have the Same Problem wenn downlaoding files directly into the nextcloud directory to sync and can reproduce it quite often running with

Nextcloud 12 on raspbian (raspberry pi 3) updated from version 11.0.3
MySql - 5.5.54
PhP -5.6.30

Windows 10 - Client Version 2.3.1 (build 8)

If i download a file directly into the nextcloud folder locally and the download takes some time i get the error

server replied: Precondition failed (An If-Match header was specified and the resource did not exist).

Logging into my Nextcloud instance an empty file is listed with the same name as the file downloaded. This file was created before the download was completed. It appears that the file cannot be updated for some reason after this point. If the empty file is deleted the client will sync the file correctly.

**Comment by blizzz** [comment] 2017-06-12 10:29
@icewind1991 @rullzer perhaps u've got an idea?

**Comment by janvlug** [comment] 2017-06-17 10:12
I can confirm this error also on Nextcloud 11.0.3 with the Linux Nextcloud client version 2.3.2-1.fc25.
The error occurred when downloading via Firefox directly in a Nextcloud shared directory.

**Comment by franz-strebel** [comment] 2017-06-19 09:22
We are also getting this error with NextCloud 12.  Downloading a file directly into NC causes it and the solution is to either move it out and put it back, or logon to the web interface and delete the empty file from there.

**Comment by rwilliamsit** [comment] 2017-06-19 12:57
I also experienced this error when downloading an .exe file using Firefox 53.0.3 (32-bit) on Win7 SP1 (updated fully) with Nextcloud client 2.3.1 (build 8)
Backend:
Nextcloud 11.0.3
PHP 5.6.30
MariaDB/Mysql 5.5.52
CentOS 7.3.1611

**Comment by kwint** [comment] 2017-06-19 19:25
Users of my server are also having this issue, running the newest client. Server is a docker image from rootlogin. I'm not sure how, but if you need logs or anything I'm happy to help.

**Comment by urbenlegend** [comment] 2017-06-21 09:29
Getting the same issue here. Seemed to happen with new client upgrade.

**Comment by thejulian** [comment] 2017-06-21 12:56
Same here. Users have same problem on the Windows Client. Can't reproduce on Linux. User just created a Folder in ah shared Folder from another user. Also happened in a notshared folder.

Want to geht Notifactions. Hi Guys.

**Comment by umgfoin** [comment] 2017-06-22 13:10
I confirm the problem with desktop-client 2.3.2beta (build 1)/ server 12.0.0
` 
22.06.2017 15:03:29,       InstantUpload/2017/06/2017-06-17 17-38-12 3036_stitch.jpg,                     Nextcloud,Error transferring https://<fqdn>/remote.php/dav/files/hias/InstantUpload/2017/06/2017-06-17 17-38-12 3036_stich.jpg-chunking-3292803479-2-0 - server replied: Precondition failed (An If-Match header was specified and the resource did not exist).
`

++umgfoin

**Comment by umgfoin** [comment] 2017-06-26 11:37
OK, materialized as being a [client-issue #5855](https://github.com/owncloud/client/issues/5855).

**Comment by jocarren** [comment] 2017-07-10 18:39
Same issue

Server:
Nextcloud 12.0.0
PHP 7.0.18
Mysql 5.7.18
Ubuntu Server 16.04.2

Client: 
Windows 10
Nextcloud-client 2.3.1.8

**Comment by cyablo** [comment] 2017-08-10 13:04
Issue still seems to persist in newest Server 11.0.4 and Client 2.3.2, at least for me.

**Comment by thejulian** [comment] 2017-08-10 13:06
Same

**Comment by kroko** [comment] 2017-08-11 08:19
Same (`An If-Match header was specified and the resource did not exist`) with NC 12.0.1 and latest public stable clients (2.3.2. build 1) on MSW10.

**Comment by nroach44** [comment] 2017-08-17 02:06
Ditto the above, I /literally/ just build the client to ensure it wasn't fixed in a commit recently, but Debian 9 (PHP 7.0+49, mysql 5.5.9999 (mariadb really) apache2 2.4.25-3+deb9u2)

**Comment by Gizmokid2005** [comment] 2017-08-20 21:13
I just started running into this late yesterday afternoon. I've been running NextCloud 11.0.4 on CentOS 7.3 using windows client 2.3.2(build 1). This setup has been working well until last night, and the only change was to bump PHP versions. Previously I was running php5.6 with NC, but upgraded to php7.0 yesterday, which is the only change that happened prior to this issue cropping up.

**Comment by skepticatgit** [comment] 2017-08-23 21:54
+1 here: Client Version 2.3.2 (build 1), Server is 12.0.1 via docker container on 16.04 LTS host.

**Comment by MissingNoIOI** [comment] 2017-08-30 21:17
I have the same problem with version 2.3.2 on OpenSUSE Tumbleweed.

**Comment by zerocoolb** [comment] 2017-09-13 12:33
is there a timeline for the fix?

**Comment by tsmith512** [comment] 2017-09-14 05:41
I can also reproduce this error:

- Saving two Adobe Illustrator documents, each ~16MB. The first save of the file synced successfully. Subsequent saves have reported the error described in this report:

![image](https://user-images.githubusercontent.com/1486573/30413255-a12b7fa4-98e2-11e7-91d0-473309d7e616.png)

Also happened with a 11MB PDF on a different computer. Moving the file out of the synced folder, allowing Nextcloud time to recognize the "deletion", then moving it back in is the workaround.

Updating smaller files doesn't appear to cause this error. (Use case: frequently updated KeePass database, ~330KB)

**Client Computer 1** (from screenshot):
- Windows 10 Home with latest OS updates applied, including the Fall Creators Update
- Nextcloud client "Version 2.3.2 (build 1)" built from git revision [820899](https://github.com/owncloud/client/commit/820899d07102b990b19e8b02121221e41f7fbf06)

**Client Computer 2** (the PDF case):
- Windows 10 Home with latest critical updates applied, but not the Creators Update
- Same client

**Server:**

An AWS EC2 instance running Ubuntu 16.04 and PHP7, with Nextcloud, latest stable, installed via apt using the https://repo.morph027.de/nextcloud package repo. New build, 1 user.

Long-winded details:
```
→  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial


→  apt-cache show nextcloud-files
Package: nextcloud-files
Priority: extra
Section: default
Installed-Size: 136902
Maintainer: Stefan Heitmüller <***@***.com>
Architecture: all
Version: 12.0.2
Filename: pool/main/n/nextcloud-files/nextcloud-files_12.0.2_all.deb
Size: 48329332
MD5sum: 8676f82f5824559240b68e1a72eb1f37
SHA1: b3fed39119d410828512f0322566f12fca16f30e
SHA256: e3a8f973973a36db5bc12580548973b6200922e791ac498f77e812ba27bd2a70
SHA512: 650f27f896dd776e9e875b7158e5df25ef324761aceae464d275247ff1d0120ce5061726b08d0ea01b39d782c578e6e1209e133fb9ba11e415a941b0b0ffca5a
Description: Nextcloud server: a safe home for all your data - community-driven, free & open source
Description-md5: 8b28f596887af20f991dfdfa23234e1a
Homepage: https://nextcloud.com/
License: unknown
Vendor: Nextcloud

→  mysqld --version; apache2 -v; php -v; sudo apache2ctl -M
mysqld  Ver 5.7.19-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))

Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-07-27T14:34:01

PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
```

**Comment by umgfoin** [comment] 2017-09-14 08:16
already fixed upstream, but nextcloud-client-release is not up-to-date:
https://github.com/nextcloud/client_theming/issues/202

**Comment by bloukrans** [comment] 2017-09-26 04:44
Hi, this problem still exists on server 12.03 (16.04 LTS host, latest updates applied) with client 2.3.2.1

any updates on this issue?
thanks!

**Comment by zerocoolb** [comment] 2017-09-26 07:51
same here...any news?

**Comment by jm009** [comment] 2017-09-26 09:35
I am working on running Nextcloud in a Tomcat web server.
If I remember correctly, I got "Precondition failed" (HTTP RESPONSE CODE 412), when the webserver did not forward the REQUESTTOKEN http header to the PHP script.

**Comment by snowball77** [comment] 2017-10-17 05:31
This issue is really bad as it may cause data loss. We use it for shared PPT editing and here, when A uploads a file, B gets it corrupted, repairs it and uploads the file again. Now only broken version of the file are around. Please provide an updated nextcloud client.

**Comment by jospoortvliet** [comment] 2017-10-18 15:16
There is an updated version of the client ready for testing: https://download.nextcloud.com/desktop/prereleases/
If it works for you, let us know, so we can release it quickly!

**Comment by dennis-eisen** [comment] 2017-10-18 18:17
@jospoortvliet Within **macOS High Sierra** _17A362a_ it works just fine!

**Comment by kmycode** [comment] 2017-10-19 01:22
@jospoortvliet It works for me, thank you!

my environment:
client: windows 10 pro 1709 (FCU)
server os: centos 7
nextcloud ver: 12.0.3)

**Comment by jsalatiel** [comment] 2017-10-19 01:27
For linux , the beta version is asking for another app password! Why ? Every user will have to reconfigure it ? This is not good...

**Comment by blizzz** [comment] 2017-10-19 08:39
> For linux , the beta version is asking for another app password! Why ? Every user will have to reconfigure it ? This is not good...

Cannot confirm, worked for me. Did you change anything on the server, or perhaps deleted the app password? However, this is not in the scope of this issue, please don't hijack. Instead [open a new issue here](https://github.com/nextcloud/client_theming/issues).

**Comment by jsalatiel** [comment] 2017-10-19 09:39
Hi, @blizzz , nothing has been changed. 
Actually i just closed the installed nextcloud client instance and executed Nextcloud-2.3.3-beta-x86_64.AppImage from the url above. If i close this new version, and reopen the installed version again  it will sync just fine. Anyway, i was just reporting the results i got, not trying to "hijack" anything.

**Comment by snowball77** [comment] 2017-10-19 13:14
As it happened random here, I cannot tell 100% for sure. But when i tried to trigger the issue, I was unable to. So I conclude that this beta client seems to work on MacOS Sierra (not yet High Sierra).

**Comment by dennis-eisen** [comment] 2017-10-19 13:19
@snowball77 As i said _earlier_ it works with **High Sierra** as well:
> @jospoortvliet Within macOS High Sierra 17A362a it works just fine!

**Comment by AndrewBucklin** [comment] 2017-10-23 21:56
Beta version 2.3.3.1 also fixed the issue for me on Windows 10. Thanks.

**Comment by blizzz** [comment] 2017-10-23 23:58
Given the positive reports, I'll close the issue as fixed.

**Closed by blizzz** 2017-10-23 23:58 UTC
Labels: bug, feature: dav

**Comment by snowball77** [comment] 2017-10-24 08:05
When will the 2.3.3 client officially become available? Any estimate? Because only then the issue is fixed for the normal user.

**Comment by blizzz** [comment] 2017-10-24 08:52
> When will the 2.3.3 client officially become available? Any estimate? Because only then the issue is fixed for the normal user.

Sure, nevertheless bugs are getting closed when they are fixed, not when the releases are out. Common standard procedure.

There is not a fixed date, yet.  Perhaps @rullzer can give an update at some point.

**Comment by MadsJakobsen** [comment] 2017-11-14 15:54
Hi, I tested client 2.3.3Beta (build 1) on macOS High Sierra with the nc server 12.0.3 docker image and it worked fine.

However I then tested the same client with nc 11.0.2, and while the error is gone when syncing files above 10mb they are still just triggering initial creation-event and no update-events as described in: https://github.com/owncloud/client/issues/5854#issuecomment-310693325

**Comment by zian92** [comment] 2018-09-05 17:10
Did a lot of reasearch.. upgrading to 2.3.3 fixed it for me. Sadly my client (nearly one year old) did not offer any updates. Manual installation did the trick.

**Comment by asheroto** [comment] 2023-09-19 17:49
I'm getting this issue now after upgrading to 27.1.0.
