### ISSUE TITLE
[Bug]: List of users gets warbled

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#35284] opened 2022-11-19 18:20 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When opening list of users they gets warbled when users belongs to many Groups.  These lines belongs to 3 users.

![image](https://user-images.githubusercontent.com/36486009/202717471-ecd370e1-d8c5-4736-ad68-1297d9d38ced.png)

### Steps to reproduce

1. Open NC 25.0.1
2.Go to Users
3.Look at list of users

### Expected behavior

Every user should have a section which adapt the height to the number of groups. 

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
v
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.1.0
  - cloud_federation_api: 1.8.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - groupfolders: 13.0.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.1
  - oauth2: 1.13.0
  - provisioning_api: 1.15.0
  - registration: 2.0.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - apporder: 0.15.0
  - bruteforcesettings
  - circles: 23.1.1
  - comments: 1.8.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - encryption
  - federation: 1.6.0
  - files_external: 1.11.1
  - files_rightclick: 0.16.0
  - firstrunwizard: 2.5.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.11.1
  - onlyoffice: 7.6.8
  - password_policy: 1.10.1
  - photos: 1.5.0
  - privacy: 1.0.0
  - recommendations: 0.4.0
  - richdocumentscode: 22.5.802
  - sharebymail: 1.12.0
  - support: 1.0.0
  - survey_client: 1.7.0
  - suspicious_login: 3.2.1
  - systemtags: 1.6.0
  - twofactor_totp
  - user_ldap
  - user_status: 1.0.1
```

### Nextcloud Signing status

```shell
v
```

### Nextcloud Logs

```shell
v
```

### Additional info

v

**Comment by rollanders** [comment] 2022-11-21 16:59
I further note that the groups associated with a user is shown but when adding groups none is marked.

**Comment by PVince81** [comment] 2022-11-23 10:47
possibly similar to https://github.com/nextcloud/server/issues/34148

https://github.com/nextcloud/server/pull/35350 will likely fix this

**Comment by PVince81** [comment] 2022-11-23 10:50
I've tested https://github.com/nextcloud/server/pull/35350 and can confirm that it fixes the overlapped wrapping

**Comment by PVince81** [comment] 2022-11-23 10:56
closing as duplicate of https://github.com/nextcloud/server/issues/34784

**Closed by PVince81** 2022-11-23 10:56 UTC
Labels: bug, 0. Needs triage, 25-feedback
