### ISSUE TITLE
Display error when changing the locale

### ISSUE THREAD

**Issue by CLOVIS-AI** [nextcloud/server#29440] opened 2021-10-26 08:11 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a normal user account
2. Set your language and your locale to English
3. Go to another page, go back to the settings and set your locale to French but keep your language to English

### Expected behaviour
The example underneath the 'locale' dialog should have the time in the French locale, and the sentence "Week starts on Monday"

### Actual behaviour
The example underneath the 'locale' dialog has the time in the French locale, however the next sentence is "Week starts on Sunday".

This is only a display bug: when navigating other apps (eg Calendar) the start of the week is correctly set to Monday.

### Server configuration

I doubt this is important for this issue, but here I go:

**Operating system:**
ArchLinux

**Web server:**
Caddy

**Database:**
MariaDB

**PHP version:**
I don't have access to that info at the moment, but I can send that later if needed.

**Nextcloud version:** (see Nextcloud admin page)
22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install.

**Where did you install Nextcloud from:**
https://archlinux.org/packages/community/any/nextcloud/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by lindhe** [comment] 2022-07-02 13:31
Duplicate of #21614

**Comment by szaimen** [comment] 2023-01-23 12:13
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by CLOVIS-AI** [comment] 2023-01-26 09:18
Hi, sorry, but I'm not a NextCloud user anymore, so I will not be able to try to attempt this. Have a good day

**Closed** 2023-03-06 13:46 UTC
Labels: bug, needs info, 0. Needs triage
