### ISSUE TITLE
Information for users about expire date trashbin

### ISSUE THREAD

**Issue by LloydS42** [nextcloud/server#20890] opened 2020-05-09 12:37 UTC
Hello

I am looking for a display of the expiration time in the Recycle Bin: "Deleted Files" when it is set. For example, I have set the following in the config.php:
'trashbin_retention_obligation' => 'auto, 90',

In my example you want to delete all files older than 90 days from the Recycle Bin. Here in installation 18.0.4 . However, the user does not get any information about it.
So my suggestion is to inform the user, at least in general. Better with one date (when the file will be deleted) column per file - not all files are deleted on the same date..

bye.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by szaimen** [comment] 2021-06-02 10:38
Duplicate of https://github.com/nextcloud/server/issues/107

**Closed by szaimen** 2021-06-02 10:38 UTC
Labels: 0. Needs triage, enhancement
