### ISSUE TITLE
Contacts app doesn't honor the user enumeration prevention settings

### ISSUE THREAD

**Issue by doobry-systemli** [nextcloud/server#17481] opened 2019-10-08 21:34 UTC
Apparently, the contacts app doesn't respect the "allow user autocompletion in share dialog" setting. Despite user autocompletion being turned off, user autocompletion still works in the contacts share dialog.

### Steps to reproduce
1. Go to Settings -> Administration -> Sharing and disable "Allow user autocompletion in share dialog. If this is disabled the full username or e-mail address needs to be entered."
2. Go to the contacts app and try to share an addressbook
3. Start typing the username and watch the matching user enumeration

### Expected behaviour
When user autocompletion is turned off, the contacts app should honor this.

### Actual behaviour
It enumerates all matching users and that way leaks all user accounts on this Nextcloud instance.

### Server configuration

**Server version:** 15.0.12
**Contacts version:** 3.1.6

**Comment by raimund-schluessler** [comment] 2019-10-09 07:20
Duplicate of https://github.com/nextcloud/server/issues/11087.

**Closed by raimund-schluessler** 2019-10-09 07:20 UTC
