### ISSUE TITLE
Enable sabre/dav's locking feature [feature request]

### ISSUE THREAD

**Issue by jdinkel** [nextcloud/server#9969] opened 2018-06-22 23:44 UTC
sabre/dav already supports webdav file locking, with instructions for enabling it here: http://sabre.io/dav/locks/

I would like for this to be enabled in Nextcloud, so webdav clients can make use of file locking.

Other than getting overwritten by the next update, would there be any unforeseen consequences if I just added the lines from that webpage to /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php ?

**Comment by MorrisJobke** [comment] 2018-07-03 08:49
Related to https://github.com/owncloud/core/pull/31651

**Comment by MorrisJobke** [comment] 2018-07-03 08:49
@rullzer @icewind1991 Opinions?

**Comment by rullzer** [comment] 2018-07-03 09:49
I'm not a fan of locking like this. For several reasons.

1. Not all webdav clients support locking. Sure we should fall back to a read only state then but still.
2. You always have the question when to break the lock? If you turn of your laptop and you still have a lock on some file/folder. Then when do you break this lock?

**Comment by rullzer** [comment] 2018-07-03 09:50
@jdinkel as to answer your question. There are still endpoints that do not use webdav. So then this locking won't be obeyed. Or in that case if you use the new endpoint.

**Comment by icewind1991** [comment] 2018-07-03 11:41
Also note that sabre's built in locking implementation wont work properly since it doesn't take things like shares into account

**Comment by MorrisJobke** [comment] 2018-07-05 14:51
Let's close this as duplicate of #1308

**Closed by MorrisJobke** 2018-07-05 14:51 UTC
Labels: 0. Needs triage, enhancement, feature: dav, feature: filesystem

**Comment by jdinkel** [comment] 2018-07-05 17:18
Oh sorry I missed that open #1308.  I think I was searching specific to sabredav.

Also I was aware it wouldn't be a completely proper working licking solution, but would at least be better than nothing.  As it is, people using webdav can overwrite each other's work, and people using other endpoints can overwrite each other's work.  With sabredav's locking enabled then at least webdav clients are protected from each other and other endpoints still risk overwriting work but that is just the same situation as before.

So the webdav situation would be improved and the other endpoints would be a problem but that is the same problem we have anyway, if I understand correctly.

**Comment by nobe80** [comment] 2021-01-19 11:42
I completly agress with jdinkel

> 
> 
> Oh sorry I missed that open #1308. I think I was searching specific to sabredav.
> 
> Also I was aware it wouldn't be a completely proper working licking solution, but would at least be better than nothing. As it is, people using webdav can overwrite each other's work, and people using other endpoints can overwrite each other's work. With sabredav's locking enabled then at least webdav clients are protected from each other and other endpoints still risk overwriting work but that is just the same situation as before.
> 
> So the webdav situation would be improved and the other endpoints would be a problem but that is the same problem we have anyway, if I understand correctly.

i completly agress with you for WebDAV User and Apps like temporary file lock is not a solution for Users that are not using the Webinterface. To log in, set a lock in webinterface and unlock it again is absolutly not practicable!
Can you tell me if it works with modifying the sabre config?
