### ISSUE TITLE
Usernames in comments not available

### ISSUE THREAD

**Issue by an-schall** [nextcloud/server#22457] opened 2020-08-27 10:21 UTC
Although the comments app is active, whenever I want to address another user within a comment (by starting to type @ followed by the username), the validated username does not pop up. There are no error messages in the log and the only place where it works is within the talk app, which I believe is unrelated.

This issue is existent in 19.0.1 and 19.0.2.

**Comment by jakobroehrl** [comment] 2020-08-27 11:54
duplicate of https://github.com/nextcloud/server/issues/19523

**Closed by jakobroehrl** 2020-08-27 11:54 UTC
