### ISSUE TITLE
Automatically delete old calendar events

### ISSUE THREAD

**Issue by Dreamsorcerer** [nextcloud/server#10864] opened 2018-08-26 13:22 UTC
It would be good to have a setting to automatically delete old calendar events (e.g. events older than 3 months).

This both helps clean up the calendar by reducing the amount of (unneeded) data stored, and improves privacy in the circumstance that a server or account is compromised, ensuring that the user's long-term history is cleared.

**Comment by skjnldsv** [comment] 2019-06-12 17:38
@georgehrke does it make sense?
Feels like a not-so-useful feature :see_no_evil:

**Comment by georgehrke** [comment] 2019-06-12 17:40
It would be okish with having an occ command that does this job that you can call like once a month via cron to cleanup, but a very big 👎 for automatic deleting by default.

**Comment by georgehrke** [comment] 2019-06-12 17:50
### Feature not on roadmap

As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Closed by georgehrke** 2019-06-12 17:50 UTC
Labels: 0. Needs triage, enhancement, feature: dav, feature: occ, needs info

**Comment by Dreamsorcerer** [comment] 2019-06-15 16:40
@georgehrke Nobody said by default, I suggested an optional feature for the user to enable if they want to have old events automatically cleaned up.

As I mentioned it can improve privacy, and it can reduce the amount of data that needs to be synced between devices.

**Comment by Mululu** [comment] 2021-01-08 20:20
Is there any news on this yet?

It would be a good feature because with a large calendar over several years, the data to be synchronized is increasing.

**Comment by NeoTheThird** [comment] 2021-12-01 11:36
Could we get this re-opened? This should definitely be a feature. Not everyone wants to keep ten years worth of calendar history.

**Comment by Coernel82** [comment] 2021-12-12 15:00
👍

**Comment by frenkert3243** [comment] 2022-09-07 09:09
I would like to request this to be re-opened, I really could use such a feature.

**Comment by Pakbon** [comment] 2022-10-04 12:58
I can also definitely use such a feature, especially if it's an occ

**Comment by readonly24** [comment] 2023-01-13 07:53
Please reopen, my calendars are growing and the MySQL database size is limited by my hoster.

**Comment by Coernel82** [comment] 2023-01-13 08:53
I would be happy with a reopen too however as a work around:
What about a bash script selecting old entries from the database and deleting them? There are drafts for those command lines on Stackoverflow.
Other option: In Thunderbird or your other handy calendar display program select and delete and then sync again?

**Comment by p5n** [comment] 2023-02-27 21:30
Does anybody know is it enough to clear
- oc_schedulingobjects
- oc_calendarobjects_props
- oc_calendarobjects
tables which are connected by etag and objectid?

Probably I want to implement such feature in shell script.

I see many queries `SELECT "uri", "calendardata", "lastmodified", "etag", "size" FROM "oc_schedulingobjects" WHERE "principaluri" = $1`
is it expected behaviour?

DB contains 400+ users and 1 600 000+ scheduling objects.

**Comment by p5n** [comment] 2023-02-27 21:36
```
$ time echo "select * from oc_schedulingobjects where principaluri='principals/users/USERNAME';" | psql -U nextcloud nextcloud >/dev/null
real	0m2.795s
user	0m2.586s
sys	0m0.090s
```
probably something goes wrong

**Comment by manuelkamp** [comment] 2023-12-10 16:16
I would also like to have this feature (occ is fine)

**Comment by horga83** [comment] 2024-02-09 04:30
No occ is not fine, there should be a way to purge old calendar events via the UI.
Normal users have no access to occ.

**Comment by viisauksena** [comment] 2024-02-28 06:17
many use calendar in (semi)work environment - therefore it is not apropiate to save event data over the years. Would be nice to have an option like 'delete all (not still repeating) events older than xy'
