### ISSUE TITLE
Impossible to send emails with some configs from version 14

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#11632] opened 2018-10-05 08:57 UTC
### Steps to reproduce

1. Go to admin settings
2. In the email server section, pick sendmail or SMTP and fill in the details
3. Send test email

### Expected behaviour

I should get an email

### Actual behaviour

>Beim Senden der E-Mail ist ein Problem aufgetreten. Bitte überprüfe Deine Einstellungen. (Fehler: Address in mailbox given [admin@] does not comply with RFC 2822, 3.6.2.)

2 issues:

1. The "address in mailbox" is missing a domain
2. The "address in mailbox" seems to want to use the wrong email address. admin@ is the account of the admin, not the email address filled-in in the "email server" 

### Server configuration

**Operating system**:

**Web server:** Apache

**Database:**

**PHP version:** 7.1 PHP-FPM

**Nextcloud version:** (see Nextcloud admin page) 14.0.2 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2018-11-12 22:38
@oparoz Could this be a duplicate of #11281? Maybe the fix #12278 helps here, or is this completely unrelated?

**Comment by oparoz** [comment] 2018-12-10 21:11
So, it's still a problem on 15.

I've tried with sendmail and both options fail.
There is something very wrong as it's not trying to us the correct email address.

I set the sender to "admin@domain.com"

The message says:
Beim Senden der E-Mail ist ein Problem aufgetreten. Bitte überprüfe Deine Einstellungen. (Fehler: Address in mailbox given [olivier@] does not comply with RFC 2822, 3.6.2.)

**Comment by danielkesselberg** [comment] 2018-12-10 21:19
Could you post the email address for your user?

**Comment by oparoz** [comment] 2019-01-01 13:32
So, I've compiled a new version of PHP 7.1 now things work as expected when using sendmail.

**Comment by MorrisJobke** [comment] 2019-01-03 13:22
> So, I've compiled a new version of PHP 7.1 now things work as expected when using sendmail.

Okay - then let's close this as we can't reproduce this and it seem to be setup specific that is non-reproducible easily.

**Closed by MorrisJobke** 2019-01-03 13:22 UTC
Labels: bug, needs info
