### ISSUE TITLE
[harmless] Suppress the php error message in logs about an empty template.

### ISSUE THREAD

**Issue by SEsternO** [nextcloud/server#26438] opened 2021-04-07 12:04 UTC
### Steps to reproduce
Create a document (.md, .odt, etc.) inside the NC instance using an empty template.

### Expected behaviour
No error messages in logs, just like when you create a document using a template.

### Actual behaviour
Log tells me about the undefined variable "template" at /var/www/nextcloud/lib/private/Files/Template/TemplateManager.php#171, which (i guess) is really undefined when you create a document without a template. No actual issues when creating a document though.

### Server configuration

**Operating system:**
Linux cloud 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Web server:**
nginx/1.14.2

**Database:**
mariadb  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
21.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Comment by juliushaertl** [comment] 2021-05-12 14:13
Closing as a duplicate of https://github.com/nextcloud/server/issues/26817

A fix is pending in https://github.com/nextcloud/server/pull/26963

**Closed by juliushaertl** 2021-05-12 14:13 UTC
Labels: 0. Needs triage, bug
