### ISSUE TITLE
Change locale settings

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#21450] opened 2020-06-17 09:05 UTC
**Is your feature request related to a problem? Please describe.**
Nextcloud allows to change the language settings and locale settings separately. 
When changing the language I am expecting that all strings will be shown in the selected language. At the same time human locales are shown in the language of the country it originates.

Case:
I am selecting English as the language of the UI, however I live in Germany and would like to see the date settings in European standard DD.MM.YYYY. I am naturally selecting German.

![image](https://user-images.githubusercontent.com/5199030/84877988-e495f200-b091-11ea-8c65-bc5bfcf9a46a.png)

What I see: the UI is in English, but not the settings of the time.

![image](https://user-images.githubusercontent.com/5199030/84878098-098a6500-b092-11ea-88fd-bff2c60564e8.png)

**Describe the solution you'd like**
To let explicitly define the format of the date using the codes, eg 
![image](https://user-images.githubusercontent.com/5199030/84878494-9503f600-b092-11ea-9bba-31bf3f2496e9.png)

and

![image](https://user-images.githubusercontent.com/5199030/84878522-9cc39a80-b092-11ea-88a4-d8e155037217.png)

**Describe alternatives you've considered**
As a simplified solution to make locales dependent on the language selected, that means, that means, that the strings are translated fine, and/or add switcher between human way of representing date (xxx seconds/minutes/hours/days/months/weeks/years ago) to the exact one: timestamp according to the selected locale.

**Comment by kesselb** [comment] 2020-06-17 10:02
cc @nickvergessen I think you worked on that but could not find the PR / Issue anymore :see_no_evil:

**Comment by nickvergessen** [comment] 2020-06-17 10:14
https://github.com/nextcloud/server/pull/14784

So duplicate of https://github.com/nextcloud/server/issues/15457

**Closed by nickvergessen** 2020-06-17 10:14 UTC
Labels: 0. Needs triage, enhancement
