### ISSUE TITLE
Nextcloud 13.0.0 b1 occ mnt:repair error/ updater error

### ISSUE THREAD

**Issue by stefanjay** [nextcloud/server#7495] opened 2017-12-13 16:34 UTC
### Steps to reproduce
1. nginx/php72/centos 6.9 final/
2. nextcloud 13.0.0 beta1-> ~/cloud (owned by nginx); -> ./occ upgrade says already newest version -> but update to 13.0.0 beta3 is available as shown when logged in
3. nextcloud 13.0.0 beta1-> ~/cloud (owned by nginx); -> ./occ maintenance:repair -> error

### Expected behaviour
`./occ upgrade should download and upgrade to the newest available version`
and
`maintenance:repair should repair my nextloud installation to be able to update to the newest version`

### Actual behaviour
upgrade error

php updater/updater.phar
Nextcloud Updater - version: v13.0.0beta1

Current version is 13.0.0 Beta 1.

Update to Nextcloud daily available. (channel: "daily")
Following file will be downloaded automatically: https://download.nextcloud.com/server/daily/latest-master.zip

Steps that will be executed:
[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Continue update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Replace entry points
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] y
Nextcloud is already latest version

Keep maintenance mode active? [y/N] n

Maintenance mode is disabled

########################
maintenance:repair error

```
Error: Call to a member function isEnabledForUser() on null in /var/www/html/cloud/core/Command/Maintenance/Repair.php:89
Stack trace:
#0 /var/www/html/cloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\Maintenance\Repair->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/cloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/cloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Repair), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/cloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/cloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/cloud/console.php(96): OC\Console\Application->run()
#6 /var/www/html/cloud/occ(11): require_once('/var/www/html/c...')
```

### Server configuration

**Operating system**:
CentOS 6.9 final

**Web server:**
nginx/1.10.2

**Database:**
percona xdb 5.7

**PHP version:**
php7.2 /fpm

**Nextcloud version:** (see Nextcloud admin page)
13.0.0 beta1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
`No errors have been found.`

</details>

**List of activated apps:**
<details>
<summary>external storage, talk and all other default apps</summary>

```
If you have access to your command line run e.g.:
php occ app:list
from within your Nextcloud installation folder
```Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.5
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 2.9.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** `webdav`

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** /

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by enoch85** [comment] 2017-12-17 12:09
Duplicate of #7309

**Closed by enoch85** 2017-12-17 12:09 UTC
