### ISSUE TITLE
"Downloaded via public link" spam on video files

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#18104] opened 2019-11-25 12:36 UTC
### Steps to reproduce
1. Share a public link to a playable video file on NC
2. Open the public link and play the video. Seek throughout the video to load different timestamps
3. Go to Activity tab of the particular file or visit the "global" activity on top of the bar.

### Expected behaviour
There should be one event that the video file was downloaded when it was played.

### Actual behaviour
A spam of "downloaded via public link" events can be observed, like so:

![Screenshot_20191125_133207](https://user-images.githubusercontent.com/36133540/69540988-5be62600-0f88-11ea-9015-4e49cfe50e47.png)

### Server configuration

**Operating system**: ubuntu 19

**Web server:** apache

**Database:** mysql

**Nextcloud version:** (see Nextcloud admin page) 16.0.5snap3

**Comment by Bellusterra** [comment] 2019-12-03 13:04
Same here, running the docker image.

**Comment by melyux** [comment] 2021-05-24 07:35
Still a big annoying issue.

**Comment by szaimen** [comment] 2021-06-07 13:46
Duplicate of https://github.com/nextcloud/server/issues/10726

**Closed by szaimen** 2021-06-07 13:46 UTC
Labels: 0. Needs triage, bug
