### ISSUE TITLE
Missing logo after Nextcloud 25 update

### ISSUE THREAD

**Issue by apobrt** [nextcloud/server#35920] opened 2022-12-30 14:33 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. update the instance to NC 25.0.2 (NC AIO 4.0.1)
2. done 😉

### Expected behavior 
It should show the logo, the header logo and the favicon as set in the previous versions.

### Actual behavior 
It shows nothing

### Host OS 
Ubuntu 22.04

#### Nextcloud AIO version 
4.0.1

#### Current channel 
latest

#### Other valuable info 
It's a very non-critical bug. It just needs to re-set the info above manually from the admin settings, and everything works again. But it's surely a bug.

**Comment by solracsf** [comment] 2022-12-30 17:10
Duplicate of https://github.com/nextcloud/server/issues/35871

**Closed by solracsf** 2022-12-30 17:10 UTC
Labels: bug, 0. Needs triage, 25-feedback
