### ISSUE TITLE
Sticky file comments 

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#11367] opened 2018-09-25 08:31 UTC
### Steps to reproduce
1. open the details view of a file
2. add a comment to the file
3. open the details view of another file

### Expected behaviour
the comment of the first file should not be shown in the comments list

### Actual behaviour
the comment of the first file is shown in the comments list

4. reload the page
5. each comment is only shown at their file as expected

### Server configuration

Docker image: nextcloud:latest (14.0.0)

**Comment by mcnesium** [comment] 2018-09-25 13:56
another observation:

1. open details view of a file that has a comment
    - comment of first file is shown
2. open details view of another file
    - comment of first file is still shown
3. open details view of a third file
    - comment of first file is gone
4. goto 1.

this even works cascading, when the file in 2. or 3. step has comments as well

**Comment by nickvergessen** [comment] 2018-09-25 20:40
Duplicate of https://github.com/nextcloud/server/issues/10934

**Closed by nickvergessen** 2018-09-25 20:40 UTC
Labels: bug, feature: comments, feature: files
