### ISSUE TITLE
White screen issue after upgrade to 12 b 2 (php cache problem!?)

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/server#4763] opened 2017-05-09 13:56 UTC
### Steps to reproduce
1. Update from 11.0.3 to 12 beta 2. I did this manually by exchanging files and then running the updater.
2. Wait a while.

### Expected behaviour
The installation works permanently ;-)

### Actual behaviour
By some reason the installation worked after the upgrade to 12 beta 2 for some time. I was able to activate some apps and even upload/download some files.

I do not really understand why, but after a while - maybe 5 to 10 minutes - things stopped to work. I only was able to load an entirely white page.

Some mostly aimless "debugging": 

- I googled a little and found following bug report: https://github.com/nextcloud/server/issues/180
- I checked if the config.php is readable by the server -> yes. 
- I tried what happens if I remove config.php. --> Reloading Nextcloud now showed the installation screen to my big surprise!?
- I restored config.php --> Again the white screen was shown.
- I had the vague idea that this might be some kind of php caching problem and rebooted the server. I do not know if this was really the cache, but Nextcloud was loaded now.

### Server configuration

**Operating system**:

Debian 8

**Web server:**

Apache 2.2

**Database:**

Mysql 5.5

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

12 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:**

From 11.0.3

**Where did you install Nextcloud from:**

?

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.2
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - comments
  - files_external
  - files_versions
  - files_videoplayer
  - systemtags
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oct67191dgn6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "holgercloud.tk"
        ],
        "datadirectory": "\/var\/www\/ownclouddata",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "12.0.0.18",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "nextcloud",
        "mail_domain": "xxx",
        "versions_retention_obligation": "5",
        "maintenance": false,
        "log_type": "syslog",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "5",
        "trashbin_retention_obligation": "7, 28",
        "activity_expire_days": 14,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": ""
    }
}
</details>

**Comment by MorrisJobke** [comment] 2017-05-09 16:24
> I tried what happens if I remove config.php. --> Reloading Nextcloud now showed the installation screen to my big surprise!?

This is intentional, because the config.php has an "installed" flag. 😉 



> I had the vague idea that this might be some kind of php caching problem and rebooted the server. I do not know if this was really the cache, but Nextcloud was loaded now.

This sounds weird. Do you have PHP opcache enabled?

**Comment by ho1ger** [comment] 2017-05-09 17:14
Hi Morris,

to clarify why I was surprised: I was surprised that that the installation was still somehow alive as no white screen appeared. I know about the installed flag ;-)

Yes, I have enabled OPcache. This morning I installed a test instance besides my production instance to play a little with the new version. In the admin menu I got some suggestions what to change in php.ini.

I post my settings below. 

<code>
[opcache]
opcache.enable=On
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
;opcache.max_wasted_percentage=5
;opcache.use_cwd=1
;opcache.validate_timestamps=1
opcache.revalidate_freq=1
;opcache.revalidate_path=0
opcache.save_comments=1
;opcache.load_comments=1
;opcache.fast_shutdown=0
;opcache.enable_file_override=0
;opcache.optimization_level=0xffffffff
;opcache.dups_fix=0
;opcache.blacklist_filename=
;opcache.max_file_size=0
;opcache.consistency_checks=0
;opcache.force_restart_timeout=180
;opcache.error_log=
;opcache.log_verbosity_level=1
;opcache.preferred_memory_model=
;opcache.protect_memory=0
</code>

However, I remember that I had the same issue some month ago after upgrading von 11.0.0 to 11.0.1 (or 11.0.1 to 11.0.2). Let me know if I can do some more tests to figure out what is going on.

**Comment by MorrisJobke** [comment] 2017-05-09 17:20
The weird thing here is that it worked for some minutes then broke and after a clean start worked again. This is really like looking into the 🔮 ... not much I can help with if it is not reproducible ... sadly :/

**Comment by benediktg** [comment] 2017-05-11 12:22
What does your webserver error log (or the one of the appropriate virtual host) say? Is there a stack trace?

**Comment by ho1ger** [comment] 2017-05-21 12:28
Hi,
my odd issue just appeared again with the latest version RC 3. All other versions / betas I tested in the meantime did not show that odd behavior.

I now had the opportunity to look into the log files. The webserver error.log does not show anything related to my nextcloud vhost. In access.log I can see various connections attempts that seem to be ok:

<code>
127.0.0.1 - xx [21/May/2017:14:25:51 +0200] "PROPFIND /remote.php/webdav/Photos/2017/05/2017-05-21%2014-13-00%201167.jpg HTTP/1.1" 200 433 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.17.3"
127.0.0.1 - xx [21/May/2017:14:25:51 +0200] "PROPFIND /remote.php/webdav/Photos/2017/05/2017-05-21%2014-13-00%201168.jpg HTTP/1.1" 200 433 "-" "Mozilla/5.0 (iOS) Nextcloud-iOS/2.17.3"
127.0.0.1 - xx [21/May/2017:14:25:51 +0200] "GET /status.php HTTP/1.1" 200 3488 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 2) (Nextcloud)"
127.0.0.1 - xx [21/May/2017:14:26:00 +0200] "GET /status.php HTTP/1.1" 200 3928 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
127.0.0.1 - xx [21/May/2017:14:26:19 +0200] "GET /status.php HTTP/1.1" 200 3488 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 2) (Nextcloud)"
127.0.0.1 - xx [21/May/2017:14:26:33 +0200] "GET /status.php HTTP/1.1" 200 3928 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
</code>

The last entries of the nextcloud log look like that: 

<code>
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 13","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"no app in context","message":"Invalidating session tokens older than 2017-04-04T21:15:02+00:00","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"no app in context","message":"Invalidating remembered session tokens older than 2017-03-21T21:15:02+00:00","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 13","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Run OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 409","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Finished OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 409","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Run OCA\\DAV\\CardDAV\\SyncJob job with ID 411","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Finished OCA\\DAV\\CardDAV\\SyncJob job with ID 411","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Run OCA\\NextcloudAnnouncements\\Cron\\Crawler job with ID 429","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"uRn8NyPcW9KQnf+l8vR0","remoteAddr":"","app":"cron","message":"Finished OCA\\NextcloudAnnouncements\\Cron\\Crawler job with ID 429","level":0,"time":"April 05, 2017 21:15:02","method":"--","url":"--","user":"--","version":"11.0.2.7"}
</code>

Also nothing useful.

**Comment by mr-bolle** [comment] 2017-06-04 22:22
Hi, i upgrade my Nextcloud (via Update.App and manual over the Terminal) and every time if i have get the Version 12.0 i have a white Page. And after fiew hours i found a solution.

Into the log File i found follow entrys **"message":"Memcache \\OC\\Memcache\\APC not available for local cache"** and i remove into the config/config.php **'memcache.local' => '\\OC\\Memcache\\APC',**

```
{"reqId":"vQXnEyOXjjBToe6lgCJW","level":4,"time":"2017-06-05T00:08:27+02:00","remoteAddr":"80.xxx.xx.xx","user":"--","app":"remote","method":"GET","url":"\/status.php","message":"Memcache \\OC\\Memcache\\APC not available for local cache","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.1 (build 8) (Nextcloud)","version":"12.0.0.29"}
{"reqId":"DMBOIjVJbj8IJrPbX5Du","level":4,"time":"2017-06-05T00:08:59+02:00","remoteAddr":"80.xxx.xx.xx","user":"--","app":"remote","method":"GET","url":"\/status.php","message":"Memcache \\OC\\Memcache\\APC not available for local cache","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.1 (build 8) (Nextcloud)","version":"12.0.0.29"}
```

**Comment by MorrisJobke** [comment] 2017-08-31 15:35
The opcache should be cleared with https://github.com/nextcloud/server/pull/5016 starting in Nextcloud 12.

And after the restart it worked again? This is really odd. Maybe we should also clear the memcaches, but usually they should be fine, because they often don't hold stuff, that breaks that hard like described here 😕

**Comment by Rocologo** [comment] 2017-12-25 14:54
This one "and if the login into the Nextcloud is sucessfull, you have to add this entry again 'memcache.local' => '\OC\Memcache\APCu',"  fixed my white screen as well...

**Comment by MorrisJobke** [comment] 2018-02-27 09:57
Closing as there was no further feedback since then and we can't reproduce :/

**Closed by MorrisJobke** 2018-02-27 09:57 UTC
Labels: needs info
