### ISSUE TITLE
[Bug]: German - EN translation

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#41240] opened 2023-11-02 10:37 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Recognized a mix between English an German words when sharing documents or folders within Nextcloud (see screenshot). Regarding our clients/users we need all this options in German again, as it was before the update.

We have installed Version Nextcloud Hub 6 (27.1.2 Enterprise).

### Steps to reproduce

look the image: 

![Attachment file 1 Denglisch](https://github.com/nextcloud/server/assets/8616947/01308fe8-75b9-4062-8f05-8f8d4c6a9834)

### Expected behavior

All in German language 

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment] 2023-11-02 13:05
cc @Fenn-CS

**Comment by Fenn-CS** [comment] 2023-11-02 13:20
Duplicate of https://github.com/nextcloud/server/issues/40801

**Closed by Fenn-CS** 2023-11-02 13:20 UTC
Labels: bug, 0. Needs triage, feature: language l10n and translations, 27-feedback
