### ISSUE TITLE
Can’t see file names on mobile; needs to hide columns

### ISSUE THREAD

**Issue by mjknowle** [nextcloud/server#17710] opened 2019-10-27 18:11 UTC
On Safari iOS or Chrome iOS, the file name column isn’t long enough to be visible (iPhone 8 Plus) in NC17.0. This makes it difficult to actually select files unless you rotate the screen to landscape mode. See enclosed screenshot. Previous Nextcloud versions worked fine.

![3C7A5051-3CA4-4CC7-B335-2BE14769CD64](https://user-images.githubusercontent.com/13839277/67639187-04ca3400-f8aa-11e9-87c1-1935da63ddaf.png)

### Steps to reproduce
1. Open an NC17.0 file view on Safari iOS on and iPhone and look. 
2.
3.

### Expected behaviour
Should be able to see file names, as in the NC mobile client. Date/sharing info should be accessible if necessary but not prominent.

### Actual behaviour
Everything but the file name shows.

### Server configuration

**Operating system**: Debian Linux

**Web server:**. Nginx 

**Database:** MySQL

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser: Safari or Chrome

**Operating system:** iOS 12.4.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2019-10-27 18:17
https://github.com/nextcloud/server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mobile+view+nc17

**Comment by kesselb** [comment] 2019-10-27 18:23
Duplicate of https://github.com/nextcloud/server/issues/17364 (just to set the reference)

**Comment by wiswedel** [comment] 2019-10-28 20:13
> Duplicate of #17364 (just to set the reference)

**Closed by wiswedel** 2019-10-28 20:13 UTC
Labels: 0. Needs triage, bug
