### ISSUE TITLE
Change "Modified" to show actual date and time in web interface

### ISSUE THREAD

**Issue by ericloyd** [nextcloud/server#42477] opened 2023-12-25 15:28 UTC
I could not find this, but I'm horrible with GitHub so please move it if it needs to be moved.

I would like to be able to see the "modified" time as an actual date and time in the web interface.  If I'm looking for a specific file that I know was modified "December 2," I don't want to have to figure out that that was 23 days ago.  I just want it to show "December 2" in the list.  This is consistent with how Windows shows files in the Details view, for instance, and I expect that it would save a marginal amount of compute time to just show the date, rather than figure out how many days, weeks, or months ago it was.

Version: Nextcloud Hub 6 (27.1.4)

**Comment by joshtrichards** [comment] 2023-12-26 17:14
Duplicate of #29807

**Closed by joshtrichards** 2023-12-26 17:14 UTC
Labels: enhancement, 0. Needs triage, feature: files, 27-feedback
