### ISSUE TITLE
Error 400 - WebSockets for Bad Request

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/server#4199] opened 2017-04-04 05:58 UTC
Hi,

I am getting this error, what is the cause of this error?
Can you help me with this?

192.168.1.99 : Server
192.168.1.101 : OnlyOffice

_vHost file for ofis.domain.com_
```
# vhost_start ofis.domain.com
<VirtualHost 192.168.1.99:443>
 ServerName ofis.domain.com
 ServerAdmin hello@domain.com
 SSLEngine on
 SSLProxyEngine On
 SSLCertificateFile /etc/letsencrypt/live/ofis.domain.com/cert.pem
 SSLCertificateKeyFile /etc/letsencrypt/live/ofis.domain.com/privkey.pem
 SSLCertificateChainFile /etc/letsencrypt/live/ofis.domain.com/fullchain.pem
 SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown
<IfModule mod_suexec.c>
    SuexecUserGroup domain domain
</IfModule>

<IfModule mod_suphp.c>
    suPHP_UserGroup domain domain
    suPHP_ConfigPath /home/domain
</IfModule>

# OnlyOffice
	RequestHeader unset Accept-Encoding
	ProxyPass / http://192.168.1.101/
	ProxyPassReverse / http://192.168.1.101/
	
ProxyPass "/websocket" "wss://192.168.1.101/websocket"
ProxyPassReverse "/websocket" "wss://192.168.1.101/websocket"

</VirtualHost>
# vhost_end ofis.domain.com
```

![cloudhatasi](https://cloud.githubusercontent.com/assets/297968/24642814/bc5d0ce8-1912-11e7-8c41-d70efa3f6a04.png)

And.. Also I getting this error together from Nextcloud Admin Logging page:

> Error 	core	     unable to open image `/tmp/oc_tmp_DMWpT0-.pdf': No such file or directory @ error/blob.c/OpenBlob/2643

Nextcloud 11.0.2 (stable) - OnlyOffice Document Server 

**Server configuration**

**Operating system:**
CentOS 7.3
**Web server:**
Apache 2.4

**Comment by MorrisJobke** [comment] 2017-04-04 21:39
Duplicate of https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/35

**Closed by MorrisJobke** 2017-04-04 21:39 UTC
