### ISSUE TITLE
scrolling bar in the "quick acces\new items" with dyslexia font

### ISSUE THREAD

**Issue by Jackthegr8at** [nextcloud/server#19772] opened 2020-03-03 22:22 UTC
### Steps to reproduce
1. enable dyslexia font
2. go to the home page
3. look at the new items

![image](https://user-images.githubusercontent.com/61761661/75824947-6e83ae80-5d72-11ea-9188-f97e89579a9b.png)

![image](https://user-images.githubusercontent.com/61761661/75825077-b30f4a00-5d72-11ea-858b-aeccec774050.png)

browser : Vivaldi or edge

things I tried :
-Same thing if I change the language of nextcloud
-Changed the theme (white, dark, dark breeze)
-resizing the webpage

**Comment by szaimen** [comment] 2021-05-31 09:50
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 09:50 UTC
Labels: 0. Needs triage, bug
