### ISSUE TITLE
Selecting search results

### ISSUE THREAD

**Issue by loeffelpan** [nextcloud/server#15087] opened 2019-04-13 21:10 UTC
### Steps to reproduce
1. Go into a folder
2. Search for any keyword
3. Select all of your search results with the checkbox in the upper right corner
4. Move, Copy, Delete your selection

### Expected behaviour
Nextcloud should only move/copy/delete the selected files.

### Actual behaviour
Nextcloud moves/copys/deletes all files in the folder, while showing only to have the right number of files select.

This should have been fixes with #2075.
With nextcloud 14 the number of selected items was correct. But as I said above in some cased all files have been processed anyway.

**Comment by violoncelloCH** [comment] 2019-04-18 21:43
looks like a duplicate of #14016

**Closed** 2019-04-18 21:45 UTC
Labels: 0. Needs triage, bug

**Comment by foocp** [comment] 2019-05-21 06:30
This should be reopened. I lost a lot of data because of this.

**Comment by kesselb** [comment] 2019-05-21 08:41
@foocp follow #14016 for more details. A fix for #14016 is already released for 14.0.11, 15.0.8, 16.0.1. If you still encounter this case please open a new issue, file the issue template and reference #14016. Thank you :+1:
