### ISSUE TITLE
Some permissions are not exposed on the interface (eg. allow read and upload without modification)

### ISSUE THREAD

**Issue by Alwaysin** [nextcloud/server#31004] opened 2022-02-04 09:24 UTC
As per the documentation, permissions can be set:

1 = read; 2 = update; 4 = create; 8 = delete; 16 = share; 31 = all (default: 31, for public shares: 1)

In the database, when I change or example permissions to 5, it is working (only read + update without possibility to modify files).
But then on the interface it looks like no option is checked:
<img width="147" alt="chrome_2022-02-04_10-19-15" src="https://user-images.githubusercontent.com/7189936/152503721-1ac6036c-c0c5-4a60-a42d-5c0f745848f3.png">

The interface should allow for that type of share. **Currently, if you want someone to be able to see the files and upload new files, you are obligated to let them be able to modify the files present in the share.**

**Comment by szaimen** [comment] 2022-02-04 09:29
Duplicate of https://github.com/nextcloud/server/issues/30227

**Closed by szaimen** 2022-02-04 09:29 UTC
Labels: enhancement, 0. Needs triage
