### ISSUE TITLE
[Bug NC25]: Adding an expiration date to a share does not work

### ISSUE THREAD

**Issue by cetcondor** [nextcloud/server#34695] opened 2022-10-20 11:14 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It is not possible to set an expiration date to a share, because no date picker or date input field appears. The problem only exists for sharing to users. (Setting an expiry date for public links is still possible.)
![Bildschirmfoto vom 2022-10-20 12-54-32](https://user-images.githubusercontent.com/40753639/196932481-19f73ab8-7bce-40d6-a12f-66e3eff62ac0.png)

### Steps to reproduce

1. Create share to a NC user
2. Try to add expiration date (DE: „Ablaufdatum setzen“)
3. No date picker appears

### Expected behavior

As step 3. the date picker or date input field should appear.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.0.18",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "minimum.supported.desktop.version": "3.3.5",
        "activity_expire_days": 90,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "app_install_overwrite": [
            "drawio",
            "files_mindmap",
            "apporder",
            "integration_whiteboard",
            "deck"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - apporder: 0.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0
  - drawio: 1.0.3
  - externalpassword: 1.0.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.0.0
  - groupfolders: 13.0.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.3
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - polls: 4.0.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - richdocuments: 7.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - terms_of_service: 2.0.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - encryption
  - federation: 1.14.0
  - files_antivirus: 3.3.1
  - files_external
  - firstrunwizard: 2.8.0
  - nextcloud_announcements: 1.13.0
  - privacy: 1.8.0
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment] 2022-10-20 12:22
cc @nextcloud/server-frontend @GretaD @ChristophWurst

**Comment by PVince81** [comment] 2022-10-20 12:58
confirmed also on master, there's no JS error

might be a visibility bug that prevents the date picker row to appear

**Comment by PVince81** [comment] 2022-10-28 16:58
:warning: while fixing the visibility issue I noticed that whatever expiration date was saved, it doesn't populate the date field, neither for link shares not internal shares.

so there's more trouble ahead.

I wonder if this was fixed in more recent nextcloud/vue versions since master is still on v7.0.0-beta.4.

**Comment by PVince81** [comment] 2022-10-28 17:03
nope, I updated to nextcloud/vue v7.0.1 locally and the problem persists

perhaps the ":value" field doesn't work with the date from the DB in the format "2022-10-31 00:00:00"

**Comment by PVince81** [comment] 2022-10-28 17:12
Raised https://github.com/nextcloud/nextcloud-vue/issues/3403 for the ActionInput date picker regression

**Closed** 2022-11-02 11:58 UTC
Labels: bug, 1. to develop, high, regression, 25-feedback
