### ISSUE TITLE
Nextcloud deleted users and database

### ISSUE THREAD

**Issue by SunDancerGE** [nextcloud/server#11944] opened 2018-10-19 15:01 UTC
### Steps to reproduce

Can't reproduce since it happened after an upgrade and nextcloud is now upgraded.

### Expected behaviour

After upgrade from Nextcloud 14.0.2 to Nextcloud 14.0.3 it should have just worked as it did 5 Minutes after the upgrade

### Actual behaviour

Some time after the update was finished and I was using it again something has reset the database or killed all users. Datafolders itself are still on the server

### Server configuration

**Operating system**: 

Linux

**Web server:**

apache (?)

**Database:** 

Art: sqlite3
Version: 3.14.2
Größe: 32.3 MB

**PHP version:**

Version: 7.0.32
Arbeitspeicher-Grenzwert: 512 MB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 4 GB

**Nextcloud version:** (see Nextcloud admin page)

Version: 14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

Update from 14.0.2.2

**Where did you install Nextcloud from:**

webupdate via updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary> Auditing / Logging
1.4.0
Offiziell
Default encryption module
2.2.0
Offiziell
External storage support
1.5.0
Offiziell
External user support
0.4
Offiziell
LDAP user and group backend </summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/home/www/doc/15877/koreshop.de/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '14.0.3.0',
  'overwrite.cli.url' => '',
  'installed' => true,
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '25',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
    /**
    * Whether the bruteforce protection shipped with Nextcloud should be enabled or not.
    *
    * Disabling this is discouraged for security reasons.
    */
    'auth.bruteforce.protection.enabled' => true,

);

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 62.0.3

**Operating system:** Windows 7 pro 64 bit


### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>


</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment] 2020-04-10 08:08
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 08:08 UTC
Labels: 0. Needs triage, bug, feature: install and update
