### ISSUE TITLE
Change thumbnails format to potentially speed-up Load time

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#28761] opened 2021-09-08 14:24 UTC
Feature Request: 
All Icons and pictures used in the ui should be AVIF or WEBP for faster loading time.
Support for those formats for the splash screen would be nice.

**Comment by acsfer** [comment] 2021-09-09 09:16
A lot, if not all, icons, are SVG.
Can you detail how an AVIF or WEBP hould load faster than SVG (and preserve it as a vector graphics file)?

**Comment by MrLoverLoverMMMM** [comment] 2021-09-09 09:43
I think you missunderstand my idea.
I talk about automatically converting the non-vectore graphics from the preview generator or the splash-screen or the icon from the users to that format.

**Comment by baozi510** [comment] 2021-09-09 14:43
I agree.
i vote webp.
avif too radical

**Comment by kowalski7cc** [comment] 2021-09-12 09:52
@baozi510 I think you can define both and let the browser decide

**Comment by szaimen** [comment] 2021-09-17 09:08
Duplicate of https://github.com/nextcloud/server/issues/13552

**Closed by szaimen** 2021-09-17 09:08 UTC
Labels: enhancement, 0. Needs triage
