### ISSUE TITLE
Upgrade problems due to lost+found folder

### ISSUE THREAD

**Issue by bdrayer** [nextcloud/server#10072] opened 2018-07-02 08:06 UTC
Hi,

I am actually using many version of the version 13 of Nextcloud (from beta 3 to the latest version of it) on my Linux Debian server.

For each nextcloud instance I use a separate hard disk but when I try to upgrade I get an error : 

[✘] Check for expected files failed
The following extra files have been found:
    lost+found

I can obviously remove it manually every time but it would be great to add it to the list of files or give the possibility to add, via the command line, a list of files that would not be tested, ...

Thanks a lot for your wonderful software

**Comment by bdrayer** [comment] 2018-07-02 08:22
Yes, it's related to issue #4908 but not exactly the same issue. I don't think I am the only one to use a dedicated mounted folder for nextcloud and lost+found is a standard linux system folder so it's more an enhancement request that a bug in my case.

**Comment by MorrisJobke** [comment] 2018-07-02 08:51
Duplicate of https://github.com/nextcloud/updater/issues/68 - we are working on it.

**Closed by MorrisJobke** 2018-07-02 08:51 UTC
