### ISSUE TITLE
Respond to server's inbox

### ISSUE THREAD

**Issue by thibaultamartin** [nextcloud/server#17496] opened 2019-10-09 17:02 UTC
### Steps to reproduce
1. Send an invitation from either the Apple Calendar app or from Nextcloud Calendar web app
2. Invited person responds
3. Response is sent to actual organizer instead of Nextcloud's internal inbox

### Expected behaviour
The response to the RSVP should be sent to Nextcloud server's inbox, so it can take into account responses from calendar clients server-side and display it in the agenda. It could also be forwarded to the actual organizer by nextcloud server.

### Actual behaviour
The invitation contains a "Respond to" field pointing to the actual organizer address. The RSVP response is sent to the actual organizer of the event. The RSVP response is not taken into account by the client.

or

It should be possible for the Nextcloud Calendar app to have the credentials of the organizer, to browse his mailbox and parse the RSVP response accordingly.

### Server configuration

**Operating system**: whichever runs in Nextcloud's official docker images

**Web server:** Apache latest from Nextcloud's official docker image

**Database:** MariaDB latest from MariaDB official docker image

**PHP version:** latest, from Nextcloud's official docker image

**Server version:** 17.0.0.9

**Calendar version:** Latest at the time of the report (will edit with actual version once I have a stable connexion)

**Updated from an older installed version or fresh install:** Fresh install

**Signing status (ownCloud/Nextcloud 9.0 and above):** Ehrm, what?

```
No errors have been found.
```

**List of activated apps:**

```

$ ./occ config:list system
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "theme": ""
    }
}
```

**Nextcloud configuration:**

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Safari Version 12.1.1 (14607.2.6.1.1)

**Operating system:** macOS Mojave Version 10.14.5 (18F132)

**CalDAV-clients:** Apple Calendar Version 11.0 (2245.5.2)

**Comment by georgehrke** [comment] 2019-10-09 17:11
> The response to the RSVP should be sent to Nextcloud server's inbox, so it can take into account responses from calendar clients server-side and display it in the agenda. It could also be forwarded to the actual organizer by nextcloud server.

The problem here is that Nextcloud, unlike other groupware solutions, does not have it's own email system, so Nextcloud can only send emails from one account that was configured by the admin. It can not generate virtual email addresses for each organiser.

Nevertheless, there are plans to integrate better with the Nextcloud mail app. If there is an email account configured for the organizer address, it should send out emails via that account (see https://github.com/nextcloud/server/issues/5080#issuecomment-501158303) and the mail app should forward iTIP messages to the Scheduling inbox.

**Comment by thibaultamartin** [comment] 2019-10-09 17:21
That would be a neater solution indeed! Any public roadmap, pending PR or anything I can quietly follow?

**Comment by ChristophWurst** [comment] 2021-09-17 13:07
I guess this is then pretty much a duplicate of https://github.com/nextcloud/server/issues/2345 and related to https://github.com/nextcloud/server/issues/5080.

**Closed** 2021-12-17 10:29 UTC
Labels: 1. to develop, feature: dav
