### ISSUE TITLE
No login image and logo on NC accessed using web

### ISSUE THREAD

**Issue by ahendre2010** [nextcloud/server#5564] opened 2017-06-29 18:20 UTC
### Steps to reproduce
1.change theme color, add login image and logo using local network
2.now try login using DNS images aren't there
3.try restoring image and logo and color. 

### Expected behaviour
It should be visible using dns

### Actual behaviour
Only color change reflected still no image and logo

### Server configuration

**Operating system**:
Raspbian 21-6-2017
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
Ph 5 latest version
**Nextcloud version:** (see Nextcloud admin page)
12.0.0 stable
**Updated from an older Nextcloud/ownCloud or fresh install:**
From 11.0.0
**Where did you install Nextcloud from:**
From installation script (php)
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
Android 6.0
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by antxDotDe** [comment] 2017-06-30 16:50
Logo works for me, but the background image stays the default one.
I tried a png and jpg of 1920x1050 / 800x438.

Paspberry PI 2 Model B with nextcloudPi on it.

**Comment by juliushaertl** [comment] 2017-06-30 16:57
Duplicate of https://github.com/nextcloud/server/issues/5085

**Closed by juliushaertl** 2017-06-30 16:57 UTC
