### ISSUE TITLE
One time share / "self destroying" share

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/server#13135] opened 2018-12-18 10:20 UTC
Hello,

what about public share (share link), that "destroyes" itself after it has been accessed for one time and files have been downloaded with the option that the share link is deactivated immediately and optionally the share content gets also deleted?

Regards

**Comment by wiswedel** [comment] 2019-06-13 04:25
duplicate of #15757

**Closed by wiswedel** 2019-06-13 04:25 UTC
Labels: 0. Needs triage, enhancement, feature: sharing
