### ISSUE TITLE
[Bug]: Expiration date differs from date configured by one day

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/server#44177] opened 2024-03-13 14:57 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a link share with expiration date of 30 days enforced, at creation it automatically sets the todays date + 30 days (as far correct).
![grafik](https://github.com/nextcloud/server/assets/142410285/877f2bb0-3324-4c32-9e15-00e77b6e02b9)

After saving and customizing the link share, the expiration date is set to a value one day lower than the originally displayed date (29 days).
![grafik](https://github.com/nextcloud/server/assets/142410285/ae74bb87-e138-4bc2-a470-c67cb977b922)

### Steps to reproduce

1. Configure the "Sharing" options like this:
    - [x] Allow users to share via link and emails
    - [x] Always ask for password
    - [x] Enforce password protection
    - [x] Set default expiry date -> Expire after 30 day(s)
    - [x] Enforce expiry date 
2. Create a link share for a folder or file and remember the date
3. Click on "customize link"

### Expected behavior

The expiration date when clicking "customize share" should have the same value as shown when creating the link.

### Nextcloud Server version

27.1.7

**Comment by ElSi-DVT** [comment] 2024-03-13 15:02
Note: when trying to update the date manually to 12.04.2024 by customizing link, the same behavior happens again: It saves the changes but when customizing link again, there is 11.04.2024.

**Comment by susnux** [comment] 2024-03-15 00:32
CC @Fenn-CS for the sharing flow

**Comment by Fenn-CS** [comment] 2024-03-15 07:29
Not able to reproduce on `27.1.7` or  `master` @Altahrim do you know this could happen?

**Comment by ElSi-DVT** [comment] 2024-03-15 08:49
https://github.com/nextcloud/server/assets/142410285/e707e8da-224f-44a6-8c7a-c868c75b6f24

**Comment by Altahrim** [comment] 2024-03-15 09:23
I think the fix will be in the next stable27 (27.1.8): https://github.com/nextcloud/server/pull/43832

**Comment by susnux** [comment] 2024-03-15 10:55
Yes https://github.com/nextcloud/server/pull/43832 seems to fix this!

**Closed by susnux** 2024-03-15 10:55 UTC
Labels: bug, 0. Needs triage, 27-feedback
