### ISSUE TITLE
NC 20 - search for contact results in error 404

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/server#23651] opened 2020-10-23 17:19 UTC
**How to use GitHub**
- Please use the 👍 reaction to show that you are affected by the same issue.
- Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
- Subscribe to receive notifications on status change and new comments.

8<--------------------

Within NC 20 search for an contact - click in a contact result and face a 404 error. Other results will be displayed as usual.

CrossPost from https://help.nextcloud.com/t/nc-20-search-for-contact-results-in-error-404-bug/

### Steps to reproduce
1. Have NC20.0.0 or NC20.0.1 installed ;-)
2. Search for any contact
3. Select the contact from search result and click on the contact item
4. see a 404 result (tested with Apache & nginx)

### Expected behaviour
found contact should be loaded

### Actual behaviour
contact is found in search but result in 404 error if selected/clicked from search results

### Server configuration

**Operating system:**
Ubuntu 18.04.5 LTS

**Web server:**
nginx | 1.18.0-v.ubuntu.18.04+p18.0.30.0+t200826.0942

**Database:**
mysql | 10.1.44-0ubuntu0.18.04.1

**PHP version:**
php74 | 7.4.11-ubuntu.18.04.201002.1145

**Nextcloud version:** (see Nextcloud admin page)
20.0.1 (until 2020-10-16 it was 20.0.0)

**Updated from an older Nextcloud/ownCloud or fresh install:**
19.0.4

**Where did you install Nextcloud from:**
Updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
	- EXTRA_FILE
		- .well-known/acme-challenge/.htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 23a3fa45757b26795f5cf8f94d9e5bce76fc916288a6458679311b312c167adcf4158ccb2c5c3db791fa0b87703b6c5863afb6c9d790b8cbac5ab3ae8c3418fb
                            [current] => 248b1c46827f16075a92457d368b5f8c1c6d39c8dc8569e248b35443ac035501b86b8f46785cc6fb3f12fc8445284829c1e27aa82097a53d2688040b1de7da26
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.well-known/acme-challenge/.htaccess] => Array
                        (
                            [expected] => 
                            [current] => b5fab078eda7da59f768ed5342ee3df121c65df4aceabca7a238f4973dc16ca3d1cb864cb110ab4f8e0f7cdb70365f4b2938683cb4f9633b0605e734d15642d9
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
occ $ app:list
--
Enabled:
- accessibility: 1.6.0
- activity: 2.13.1
- announcementcenter: 4.0.0
- apporder: 0.11.0
- browser_warning: 1.0.0
- bruteforcesettings: 2.0.1
- calendar: 2.1.2
- camerarawpreviews: 0.7.8
- carnet: 0.22.3
- checksum: 0.4.5
- cloud_federation_api: 1.3.0
- comments: 1.10.0
- contacts: 3.4.1
- contactsinteraction: 1.1.0
- cospend: 1.1.4
- dashboard: 7.0.0
- data_request: 1.7.0
- dav: 1.16.0
- deck: 1.1.2
- drawio: 0.9.7
- drop_account: 0.2.1
- duplicatefinder: 0.0.4
- emlviewer: 0.0.18
- federatedfilesharing: 1.10.1
- federation: 1.10.1
- files: 1.15.0
- files_antivirus: 3.0.0
- files_downloadactivity: 1.9.0
- files_external: 1.11.1
- files_linkeditor: 1.1.2
- files_mindmap: 0.0.23
- files_pdfviewer: 2.0.1
- files_rightclick: 0.17.0
- files_sharing: 1.12.0
- files_trashbin: 1.10.1
- files_versions: 1.13.0
- files_videoplayer: 1.9.0
- firstrunwizard: 2.9.0
- forms: 2.0.4
- group_everyone: 0.1.6
- groupfolders: 8.1.0
- groupquota: 0.1.4
- guests: 1.6.0
- integration_github: 0.0.8
- logreader: 2.5.0
- lookup_server_connector: 1.8.0
- maps: 0.1.8
- metadata: 0.12.0
- nextcloud_announcements: 1.9.0
- notes: 4.0.0
- notifications: 2.8.0
- oauth2: 1.8.0
- occweb: 0.0.7
- oidc_login: 1.6.0
- password_policy: 1.10.1
- passwords: 2020.10.0
- phonetrack: 0.6.5
- photos: 1.2.0
- polls: 1.5.4
- previewgenerator: 3.0.1
- privacy: 1.4.0
- provisioning_api: 1.10.0
- quota_warning: 1.9.1
- rainloop: 7.0.3
- recommendations: 0.8.0
- richdocuments: 3.7.5
- richdocumentscode: 4.2.800
- serverinfo: 1.10.0
- settings: 1.2.0
- sharebymail: 1.10.0
- sharerenamer: 2.7.3
- sharingpath: 0.2.5
- social: 0.4.1
- socialsharing_email: 2.1.0
- spreed: 10.0.0
- support: 1.3.0
- suspicious_login: 3.2.1
- systemtags: 1.10.0
- talk_simple_poll: 1.2.0
- tasks: 0.13.5
- telephoneprovider: 1.0.3
- terms_of_service: 1.6.1
- text: 3.1.0
- theming: 1.11.0
- twofactor_admin: 3.0.0
- twofactor_backupcodes: 1.9.0
- twofactor_gateway: 0.17.0
- twofactor_totp: 5.0.0
- unsplash: 1.1.7
- updatenotification: 1.10.0
- uploaddetails: 0.1.3
- user_ldap: 1.10.2
- user_status: 1.0.0
- video_converter: 0.1.5
- viewer: 1.4.0
- weather_status: 1.0.0
- workflowengine: 2.2.0
Disabled:
- admin_audit
- afterlogic
- analytics
- encryption
- extract
- files_external_onedrive
- files_photospheres
- files_retention
- mail
- roundcube
- survey_client
- twofactor_yubikey
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
occ $ config:list system
--
{
"system": {
"instanceid": "***REMOVED SENSITIVE VALUE***",
"passwordsalt": "***REMOVED SENSITIVE VALUE***",
"secret": "***REMOVED SENSITIVE VALUE***",
"trusted_domains": [
"***REMOVED SENSITIVE VALUE***"
],
"datadirectory": "***REMOVED SENSITIVE VALUE***",
"filesystem_check_changes": 1,
"overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
"dbtype": "mysql",
"version": "20.0.0.9",
"dbname": "***REMOVED SENSITIVE VALUE***",
"dbhost": "***REMOVED SENSITIVE VALUE***",
"dbtableprefix": "oc_",
"dbuser": "***REMOVED SENSITIVE VALUE***",
"dbpassword": "***REMOVED SENSITIVE VALUE***",
"logtimezone": "UTC",
"installed": true,
"mail_from_address": "***REMOVED SENSITIVE VALUE***",
"mail_smtpmode": "smtp",
"mail_domain": "***REMOVED SENSITIVE VALUE***",
"appstore.experimental.enabled": true,
"forcessl": true,
"xframe_restriction": true,
"maintenance": false,
"theme": "",
"loglevel": 2,
"updater.release.channel": "beta",
"updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
"auth.bruteforce.protection.enabled": true,
"updatechecker": true,
"mail_smtpauthtype": "LOGIN",
"allowNightlyUpdates": [],
"mail_smtpsecure": "ssl",
"mail_smtpauth": 1,
"mail_smtphost": "***REMOVED SENSITIVE VALUE***",
"mail_smtpport": "465",
"mail_smtpname": "***REMOVED SENSITIVE VALUE***",
"mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
"twofactor_enforced": "false",
"twofactor_enforced_groups": [
"2FactorAuth"
],
"twofactor_enforced_excluded_groups": [],
"app_install_overwrite": [
"files_downloadactivity",
"apporder",
"carnet",
"data_request",
"drawio",
"photosphereviewer",
"tasks",
"occweb",
"twofactor_yubikey",
"ocsms",
"forms",
"files_photospheres",
"telephoneprovider",
"drop_account",
"files_external_onedrive",
"afterlogic",
"admin_notifications",
"browser_warning",
"checksum",
"files_mindmap",
"rainloop",
"sharerenamer",
"socialsharing_email",
"unsplash",
"uploaddetails",
"polls",
"contacts",
"social",
"sharingpath",
"bruteforcesettings",
"files_retention",
"roundcube",
"camerarawpreviews",
"groupquota",
"quota_warning",
"terms_of_service",
"calendar",
"emlviewer"
],
"has_rebuilt_cache": true,
"ldapIgnoreNamingRules": false,
"ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
}
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
other NC instance

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google Chrome 86.0.4240.75
MS Edge 86.0.622.51

**Operating system:**
MS Win10 Enterprise 18363.1016

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nginx logs:
|2020-10-23 12:24:27|Access|CLIENT-IP|GET /index.php/apps/contacts/direct/UIDofCONTACT~kontakte HTTP/2.0|nginx SSL/TLS access|
|2020-10-23 12:24:27|Error|CLIENT-IP|GET /apps/contacts/Alle%20Kontakte/UIDofCONTACT~kontakte HTTP/2.0|nginx SSL/TLS access|
|2020-10-23 12:24:27|Error|CLIENT-IP|14654#0: *1838024 open() “/var/www/vhosts/VPD-Name/DOMAIN-Name/apps/contacts/Alle Kontakte/UIDofCONTACT~kontakte” failed (2: No such file or directory)|
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
there is no output generated when error occured
```
</details>

**Comment by Kariton** [comment] 2020-10-24 16:09
This also happen if you jump from the 'Maps' app to contacts by clicking on the 'open in contacts'

- Contact with location information, displayed in 'Maps' and then "jump" to the contact vie link on the contact location on 'Maps'

**Comment by nextgen-networks** [comment] 2020-10-26 09:04
fresh updated NC 20.0.1 is affected too :-/

Result:
![image](https://user-images.githubusercontent.com/21206978/97153302-8d580a80-1772-11eb-9146-ee5cba96146c.png)

**Comment by dmp1ce** [comment] 2020-10-26 11:08
I notice the `index.php` part of the URL is missing on my instance. By adding `index.php` to the search result, the contact shows up.

**Comment by skjnldsv** [comment] 2020-11-07 22:18
Duplicate of https://github.com/nextcloud/contacts/issues/1852

**Closed by skjnldsv** 2020-11-07 22:18 UTC
Labels: 0. Needs triage, bug
