### ISSUE TITLE
Files: show favorites column in Shared views as well

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2193] opened 2016-11-17 22:23 UTC
Currently the Favorites stars are only shown in the Files and Favorites view. They should be shown in the other views as well.

cc @nextcloud/javascript

**Comment by MorrisJobke** [comment] 2016-11-28 10:44
Duplicate of #2347 (there is more activity

**Comment by jancborchardt** [comment] 2016-11-30 11:13
@MorrisJobke this has a clear plan though. ;) Reopening hence

**Comment by MorrisJobke** [comment] 2017-05-04 13:51
Only the "Recent" view is missing - out of scope for 12. Moved to 13: #4697

**Closed by MorrisJobke** 2017-05-04 13:51 UTC
Labels: 1. to develop, bug, design, feature: files, high
