### ISSUE TITLE
Filter tags through Boolean searches

### ISSUE THREAD

**Issue by earendil1** [nextcloud/server#35283] opened 2022-11-19 17:20 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Collaborative tags are a great way to organize files and the current offer on NC could be certainly be improved, as #33046 and #4699 show.

A feature that would go in this direction would be the possibility of **searching for files which are missing a certain tag** or better still **Boolean searches**.

I will concentrate on the NOT syntax. Currently, organizations with large files, would assign several tags to their documents to be able to find them according to those criteria. Lets say that out of 3000 documents 300 share a combination of tags: (A, B, C, F, Y, T, Z, H). Some tags are missing because some work has not been done on them for example. It could be the case of the tag signed or reviewed or openaccess or doiassigned. 

**Describe the solution you'd like**
Search on tags should allow for boolean searches: AND, OR, NOT, (). There could be symbols helping with speeding up the search. Space ( ) could mean AND, Slash (/) OR, a minus (-) could mean NOT. Parenthesis would be for grouping. For ex. (A OR Y) AND T NOT Z

**Describe alternatives you've considered**
Presently, if I look for a subset of documents and want to know what work needs to be done on the subset, since there is no visual way of telling which documents have which tags, I will have to open them one by one to find which one is missing one of the above tags.

An alternative would be to double the tags used creating not-signed or not-reviewed or not-openaccess or not-doiassigned.

**Comment by joshtrichards** [comment] 2023-09-15 16:04
Duplicate of #4851

Please subscribe to that issue to monitor progress and give it a thumbs up to express your interest.

**Closed by joshtrichards** 2023-09-15 16:04 UTC
Labels: enhancement, 0. Needs triage, feature: tags, feature: search
