### ISSUE TITLE
[Bug]: Repeating notifications for video shares

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/server#47800] opened 2024-09-06 09:45 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have notifications on for 'A file or folder shared by mail or by public link was downloaded'
If the share contains a video and people stream it, I receive plenty notifications for one single stream.

![grafik](https://github.com/user-attachments/assets/cf2114e8-1d36-4f5d-bb79-194084647127)

### Steps to reproduce

1. share a video or folder, containing a video
2. open the share, stream video
3. check notifications

### Expected behavior

only one notification per click

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-09-06 19:54
Duplicate of #36875

**Closed by joshtrichards** 2024-09-06 19:54 UTC
Labels: bug, 0. Needs triage, 29-feedback
