### ISSUE TITLE
File Download CSP Error

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [nextcloud/server#10254] opened 2018-07-16 03:09 UTC
When downloading a MP3, MP4, webM or other media file a CSP error is thrown.

Console Errors:
`[filename].mp3:1 Refused to load media from 'https://192.168.0.12/drive/remote.php/webdav/[filename].mp3?downloadStartSecret=[redacted]' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.`

`Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-jXP1MhzXJiZm3bKqqhaSoVGlgtNu8Zl7WG/WjeAssXY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/12146099/42741868-3d092734-8873-11e8-9eac-0b617118ebd3.png)

**Comment by Engineer-of-Stuff** [comment] 2018-07-16 19:09
I'm not trying to view it, I want to download it.

**Comment by stratege1401** [comment] 2018-07-16 21:47
understood, so in that case, as your browser normal behaviors is to "play" the files, you need to use the 3 dots columns in order to reach the "download" options. 
OR
modify the chrome option for the mpx file This feature was in "Advanced" -> Click "Clear Auto-opening settings"

**Comment by Engineer-of-Stuff** [comment] 2018-07-17 04:32
I do click the "Download" button, which then opens the file in the browser.

I don't see the setting. Is it in Flags?

**Comment by stratege1401** [comment] 2018-07-17 15:02
in chrome 67 it is located at:  chrome://settings/content/pdfDocuments

in my nextcloud i have the followings apps witch can have some link to pdf:
Files Right Click
Metadata
PDF viewer

left click on the three dot, drop list, deownload ... and it works...

**Comment by fdelapena** [comment] 2018-09-22 02:34
Also happens with FLAC files. The media-src is used for main site when logging in, but not in the share view for anonymous users, the CSP header there is not the same and lacks the media-src 'self'.

**Comment by szaimen** [comment] 2021-05-21 11:44
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-21 11:44 UTC
Labels: 0. Needs triage, bug
