### ISSUE TITLE
I moved one directory to another and I can't download anymore 

### ISSUE THREAD

**Issue by mateusfmello** [nextcloud/server#27666] opened 2021-06-25 03:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. In the browser select two folders 
2. Use the menu option to move them 
3. choose destination and move 

### Expected behaviour
That both folders are moved correctly 

### Actual behaviour
Folder 1 was moved correctly.
An error occurred while moving Folder 2 and when trying to download from any Nextcloud client an error occurs and the logs show "Bad Signature" 

### Server configuration

**Operating system:** CentOS Linux 7

**Web server:** Apache/2.4.6 (CentOS)

**Database:** psql (PostgreSQL) 9.6.22

**PHP version:** PHP 7.4.20

**Nextcloud version:** 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** ZIP from official site and following the official documentation 

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - encryption: 2.9.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "storage.mfmello.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/storage.mfmello.com",
        "dbtype": "pgsql",
        "version": "21.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trashbin_retention_obligation": "10, 30",
        "versions_retention_obligation": "15, 30",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF"
        ],
        "allow_user_to_change_display_name": true,
        "preview_max_x": 500,
        "preview_max_y": 500,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "blacklisted_files": [],
        "auth.bruteforce.protection.enabled": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "tasks"
        ],
        "data-fingerprint": "323a87cae4839f37e784357223f623c4",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "BR"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 89.0.1 (64 bits)

**Operating system:** Linux Mint 19.1 (Tessa)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 0,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "encryption",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 0,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "files_external",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 0,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "files_sharing",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 1,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "no app in context",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*logger\":null,\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[]}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 4,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "webdav",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": {
        "Exception": "OCP\\Encryption\\Exceptions\\GenericEncryptionException",
        "Message": "Bad Signature",
        "Code": 0,
        "Trace": [
            { "file": "/var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php", "line": 480, "function": "checkSignature", "class": "OCA\\Encryption\\Crypto\\Crypt", "type": "->", "args": ["*** sensitive parameters replaced ***"] },
            { "file": "/var/www/nextcloud/apps/encryption/lib/Crypto/Encryption.php", "line": 376, "function": "symmetricDecryptFileContent", "class": "OCA\\Encryption\\Crypto\\Crypt", "type": "->" },
            { "file": "/var/www/nextcloud/lib/private/Files/Stream/Encryption.php", "line": 520, "function": "decrypt", "class": "OCA\\Encryption\\Crypto\\Encryption", "type": "->", "args": ["*** sensitive parameters replaced ***"] },
            { "file": "/var/www/nextcloud/lib/private/Files/Stream/Encryption.php", "line": 318, "function": "readCache", "class": "OC\\Files\\Stream\\Encryption", "type": "->" },
            { "function": "stream_read", "class": "OC\\Files\\Stream\\Encryption", "type": "->" },
            { "file": "/var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php", "line": 55, "function": "fread" },
            { "file": "/var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php", "line": 96, "function": "stream_read", "class": "Icewind\\Streams\\Wrapper", "type": "->" },
            { "function": "stream_read", "class": "Icewind\\Streams\\CallbackWrapper", "type": "->" },
            { "file": "/var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php", "line": 112, "function": "stream_copy_to_stream" },
            { "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php", "line": 490, "function": "sendResponse", "class": "Sabre\\HTTP\\Sapi", "type": "::" },
            { "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php", "line": 253, "function": "invokeMethod", "class": "Sabre\\DAV\\Server", "type": "->" },
            { "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php", "line": 321, "function": "start", "class": "Sabre\\DAV\\Server", "type": "->" },
            { "file": "/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php", "line": 84, "function": "exec", "class": "Sabre\\DAV\\Server", "type": "->" },
            { "file": "/var/www/nextcloud/remote.php", "line": 167, "args": ["/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php"], "function": "require_once" }
        ],
        "File": "/var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php",
        "Line": 505,
        "Hint": "Assinatura ruim",
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 0,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "scss_cacher",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "SCSSCacher::process ordinary check follows",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 0,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "scss_cacher",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "SCSSCacher::process ordinary check follows",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 0,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "scss_cacher",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "SCSSCacher::process ordinary check follows",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3UtePyXe63Q5B9MjlwAAABQ",
    "level": 0,
    "time": "2021-06-25T03:26:21+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "scss_cacher",
    "method": "GET",
    "url": "/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=th3x5o7eozl",
    "message": "SCSSCacher::process ordinary check follows",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3u0y5hkUYvcg4K4FeAAAABM",
    "level": 0,
    "time": "2021-06-25T03:26:22+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "encryption",
    "method": "GET",
    "url": "/apps/photos/service-worker.js",
    "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3u0y5hkUYvcg4K4FeAAAABM",
    "level": 0,
    "time": "2021-06-25T03:26:22+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "files_external",
    "method": "GET",
    "url": "/apps/photos/service-worker.js",
    "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}
{
    "reqId": "YNVM3u0y5hkUYvcg4K4FeAAAABM",
    "level": 0,
    "time": "2021-06-25T03:26:22+00:00",
    "remoteAddr": "10.0.0.10",
    "user": "mateus",
    "app": "files_sharing",
    "method": "GET",
    "url": "/apps/photos/service-worker.js",
    "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
    "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0",
    "version": "21.0.2.1"
}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
**Console Log**

$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 6 globals.js:60:15

GET https://storage.mfmello.com/remote.php/webdav/Trabalhos/Ana%20Carolina%20Bartokoski/Background%20para%20Celular/Arte.ai?downloadStartSecret=u9phxsgqgsm
[HTTP/1.1 500 Internal Server Error 273ms]

O cookie "ocDownloadStarted" será rejeitado em breve, pois possui o atributo "SameSite" definido como "None" ou um valor inválido, sem o atributo "secure". Para saber mais sobre o atributo "SameSite", leia https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```
</details>

**Comment by szaimen** [comment] 2021-08-08 13:33
Looks like a duplicate of https://github.com/nextcloud/server/issues/16419

**Closed by szaimen** 2021-08-08 13:33 UTC
Labels: bug, 0. Needs triage
