### ISSUE TITLE
Video playback with interruptions

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#19263] opened 2020-02-02 18:55 UTC
### Steps to reproduce
1. Play a video in NC video viewer (default)

### Expected behaviour
Tell us what should happen

The video loads normally and plays without interruptions.

### Actual behaviour
Tell us what happens instead

On a 95MB 30second FullHD video, the playback is interrupted many times when playing due to slow loading/buffering. On top of that, loading animation can be seen all throughout the video, even though majority of the video is already loaded:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/73613380-411dd680-45f5-11ea-88af-98d30e0a305a.png)

Playing lower bitrate videos doesn't cause problems this big, but it isnt too good either. The spinning circle can be observed at every video which becomes really annoying.

### Server configuration

**Operating system:** ubuntu 19.10

**Web server:** apache

**Nextcloud version:** 16.0.7snap

Video player version 1.5.0

**Comment by szaimen** [comment] 2021-06-07 16:34
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 16:34 UTC
Labels: 0. Needs triage, bug
