### ISSUE TITLE
Code integrity check failed after update to Nextcloud 12 (caused by direct_menu)

### ISSUE THREAD

**Issue by stweil** [nextcloud/server#5535] opened 2017-06-25 07:36 UTC
I upgraded an installation which had the [Direct Menu](https://apps.nextcloud.com/apps/direct_menu) app installed to Nextcloud 12 and got an error message from the code integrity check ("Bei der Code-Integritätsprüfung ..."). Here is the full error report:

    Technical information
    =====================
    The following list covers which files have failed the integrity check. Please read
    the previous linked documentation to learn more about the errors and how to fix
    them.

    Results
    =======
    - direct_menu
            - EXCEPTION
                    - OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    - Certificate is not valid.

    Raw output
    ==========
    Array
    (
        [direct_menu] => Array
            (
                [EXCEPTION] => Array
                    (
                        [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                        [message] => Certificate is not valid.
                    )

            )

    )

As the features of `direct_menu` are now part of Nextcloud 12, I removed the `apps/direct_menu` directory from the installation and repeated the integrity check. That fixed the integrity error message.

The update to Nextcloud 12 should handle that case on its own.

A code of the removed directory which had caused the problem is available [online](https://bibserv24.bib.uni-mannheim.de/tmp/direct_menu.tar).

**Comment by stweil** [comment] 2017-06-25 07:54
CC`ing @juliushaertl, the author of Direct Menu.

**Comment by juliushaertl** [comment] 2017-06-27 07:28
Duplicate of #4679

Just remove the direct_menu app since it is not compatible with 12.
See: https://github.com/juliushaertl/direct_menu#known-issues

**Closed by juliushaertl** 2017-06-27 07:28 UTC
