### ISSUE TITLE
Argument 2 passed to OCA\Provisioning_API\Controller\UsersController::removeFromGroup() must be of the type string, null given

### ISSUE THREAD

**Issue by GuidoDr** [nextcloud/server#23681] opened 2020-10-25 18:33 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Login into Nextcloud with admin login, go to the user list, click the edit button for the user.
2. click on the group the user is currently in and that you want to remove
3. error shown in the upper right corner

### Expected behaviour
user should have been removed from the group

### Actual behaviour
user is not removed from the group, error message is shown instead

### Server configuration

**Operating system:** Ubuntu 18.04.5 LTS

**Web server:** nginx

**Database:** PostgreSQL 12.4

**PHP version:** 7.4.11

**Nextcloud version:**  20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from latest 19 version

**Where did you install Nextcloud from:** official docker image

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - admin_audit: 1.10.0
  - announcementcenter: 4.0.0
  - apporder: 0.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dav: 1.16.0
  - deck: 1.1.2
  - external: 3.7.1
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.0
  - files_automatedtagging: 1.10.0
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.1.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.5.0
  - metadata: 0.12.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.1.0
  - ownpad: 0.6.15
  - passman: 2.3.6
  - password_policy: 1.10.1
  - photos: 1.2.0
  - piwik: 0.7.0
  - polls: 1.5.4
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.5
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - dashboard
  - encryption
  - federation
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "wolke.bewegung.jetzt"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/wolke.bewegung.jetzt",
        "dbtype": "pgsql",
        "version": "20.0.0.9",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 30,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "updater.release.channel": "stable",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "passman",
            "tasks",
            "documents",
            "onlyoffice",
            "polls",
            "piwik",
            "files_mindmap",
            "ownpad"
        ],
        "mail_sendmailmode": "smtp"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[no app in context] Error: Exception: Argument 2 passed to OCA\Provisioning_API\Controller\UsersController::removeFromGroup() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 169 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Provisioning ... {}, "removeFromGroup")
1. /var/www/html/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Provisioni ... r", "removeFromGroup", OC\AppFramework\ ... {}, {action: null,us ... "})
2. /var/www/html/ocs/v1.php line 88
   OC\Route\Router->match("/ocsapp/cloud/users/franka/groups")
3. /var/www/html/ocs/v2.php line 24
   require_once("/var/www/html/ocs/v1.php")

DELETE /ocs/v2.php/cloud/users/<user name>/groups
from xxx.xxx.xxx.xxx by <admin user> at 2020-10-25T17:10:53+00:00
```
</details>

**Comment by kesselb** [comment] 2020-10-25 19:44
Thanks for reporting :+1: 

Closing as duplicate of https://github.com/nextcloud/server/issues/23237. Also check the FAQ issue and/or use the search for the next report.

**Closed by kesselb** 2020-10-25 19:44 UTC
Labels: 0. Needs triage, bug
