### ISSUE TITLE
Canceling upload of big file leads to "Internal Server error"

### ISSUE THREAD

**Issue by TheNickSkater** [nextcloud/server#11339] opened 2018-09-23 20:37 UTC
### Steps to reproduce
1. Start an upload of a big file (i tested with 80 MB)
2. Cancel the upload at any given time

### Expected behaviour
Upload should get canceled with "Upload canceled" message (or whatever in english)

### Actual behaviour
Progress bar wont disappear instantly but will still gain progress for a few seconds till an "Internal server error" appears

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:**7.0

**Nextcloud version:** (see Nextcloud admin page) 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Official nextcloud page

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```https://pastebin.com/Vc4ucDh2
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```https://pastebin.com/QQ2m5SKZ
</details>

**Are you using external storage, if yes which one:** Enabled yes, using no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera/Edge/Chrome tested

**Operating system:** Win10

### Logs

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
https://pleasureuhc.eu/nextcloud/index.php/s/ntQzaKE5XrBbT2n
</details>

**Comment by skjnldsv** [comment] 2020-04-10 07:18
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 07:18 UTC
Labels: 0. Needs triage, bug
