### ISSUE TITLE
[BUG] Share a Share (NC 14.0.0.19)

### ISSUE THREAD

**Issue by Ramalama2** [nextcloud/server#11226] opened 2018-09-14 17:36 UTC
### Steps to reproduce
1. `Another user share you a File`
2. `you make a folder and move that shared file into that folder`
3. `Try to share the Folder with the (shared file) inside to any user, you get an error.
If you share the shared file instead, its working perfect, but the folder where the file is inside, doesnt.`

### Expected behaviour
`Should be possible to share`

### Actual behaviour
`You get an "Error" without any logs at all`

### Server configuration

**Operating system**:
-> CentOS 7.5 (kernel 4.18.7)

**Web server:**
-> nginx 1.15.3

**Database:**
-> MariaDB 10.3

**PHP version:**
-> php-fpm 7.2.9

**Nextcloud version:** (see Nextcloud admin page)
-> 14.0.0.19

**Updated from an older Nextcloud/ownCloud or fresh install:**
-> YES! (Started with NC 10)

**Where did you install Nextcloud from:**
-> Downloaded the zip from nextcloud homepage and installed/updated/etc...

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity check is disabled....

**List of activated apps:**
<details><summary>Enabled:
  - accessibility: 1.0.1
  - calendar: 1.6.2
  - camerarawpreviews: 0.5.6
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - federation
  - files_versions
  - firstrunwizard
  - nextcloud_announcements
  - notifications
  - password_policy
  - serverinfo
  - sharebymail
  - support
  - survey_client
  - systemtags
  - theming
  - user_external
  - user_ldap</summary></details>

**Nextcloud configuration:**
<details><summary>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "integrity.check.disabled": true,
        "auth.bruteforce.protection.enabled": false,
        "dbtype": "mysql",
        "version": "14.0.0.19",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "logtimezone": "UTC",
        "installed": true,
        "default_language": "de",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "25",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtptimeout": 5,
        "mail_smtpdebug": false,
        "asset-pipeline.enabled": true,
        "filelocking.enabled": "true",
        "loglevel": 1,
        "log_rotate_size": 16000,
        "maintenance": false,
        "onlyoffice": {
            "jwt_secret": "***REMOVED SENSITIVE VALUE***",
            "jwt_header": "Authorization"
        },
        "theme": "golima",
        "activity_expire_days": 90,
        "appstore.experimental.enabled": true,
        "htaccess.RewriteBase": "\/",
        "data-fingerprint": "010d0b4cacf3c931dee2422389e338e2",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "skeletondirectory": "",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}</summary></details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 62

**Comment by Ramalama2** [comment] 2018-09-17 19:19
The bot is stupid :-)

**Comment by skjnldsv** [comment] 2019-08-07 15:59
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-08-07 15:59 UTC
Labels: 0. Needs triage, bug, feature: sharing
