### ISSUE TITLE
[Bug]: Unable to open Logging Page in Nextcloud 28

### ISSUE THREAD

**Issue by drudgede** [nextcloud/server#42254] opened 2023-12-13 22:12 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I open the logging page after upgrade to Nextcloud 28 in the admin backend, I get a server error and cannot see any logs

### Steps to reproduce

1. Login to Nextcloud as an admin
2. Go to the admin settings (in German: Verwaltungseinstellungen)
3. Go to the logging page (in German: Protokollierung)
4. An internal server error appears and log entries are not shown anymore

### Expected behavior

I expect to see the log entries of Nextcloud

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.1.4",
            "10.0.1.5",
            "***REMOVED SENSITIVE VALUE BY HAND FOR GITHUB***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "http:\/\/10.0.1.4",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": "false",
        "mysql.utf8mb4": true,
        "skeletondirectory": "",
        "updater.release.channel": "stable",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "htaccess.RewriteBase": "\/",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "allow_user_to_change_display_name": true,
        "app_install_overwrite": [
            "onlyoffice",
            "documentserver_community"
        ],
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "user": "default",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
sudo -u www-data php ./occ app:list
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_antivirus: 5.4.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 22.1.1)
  - contactsinteraction: 1.9.0 (installed 1.4.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - firstrunwizard: 2.17.0 (installed 2.4.0)
  - passwords: 2023.12.30 (installed 2023.12.30)
  - privacy: 1.12.0 (installed 1.3.0)
  - recommendations: 2.0.0 (installed 1.2.0)
  - support: 1.11.0 (installed 1.0.0)
  - survey_client: 1.16.0 (installed 1.4.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.9.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0 (installed 1.11.0)
  - user_status: 1.8.1 (installed 1.0.1)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
This is the bug I report. It does not work to open the URL.
Here is the latest error that occurs when I try to access the page
It's taken from the nextcloud.log in the Nextcloud App directory. The error always looks like this. formatted JSON:


{
   "reqId":"Al6wIKPOs1SKtDmQkRqX",
   "level":3,
   "time":"2023-12-13T21:50:18+00:00",
   "remoteAddr":"10.0.1.79",
   "user":"***REMOVED SENSITIVE VALUE BY HAND FOR GITHUB***",
   "app":"index",
   "method":"GET",
   "url":"/settings/admin/logging",
   "message":"Syntax error",
   "userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15",
   "version":"28.0.0.11",
   "exception":{
      "Exception":"JsonException",
      "Message":"Syntax error",
      "Code":4,
      "Trace":[
         {
            "file":"/var/www/nextcloud/apps/logreader/lib/Service/SettingsService.php",
            "line":52,
            "function":"json_decode"
         },
         {
            "file":"/var/www/nextcloud/apps/logreader/lib/Service/SettingsService.php",
            "line":69,
            "function":"getRelativeDates",
            "class":"OCA\\LogReader\\Service\\SettingsService",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/logreader/lib/Settings/Admin.php",
            "line":46,
            "function":"getAppSettings",
            "class":"OCA\\LogReader\\Service\\SettingsService",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
            "line":129,
            "function":"getForm",
            "class":"OCA\\LogReader\\Settings\\Admin",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php",
            "line":86,
            "function":"formatSettings",
            "class":"OCA\\Settings\\Controller\\AdminSettingsController",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php",
            "line":149,
            "function":"getSettings",
            "class":"OCA\\Settings\\Controller\\AdminSettingsController",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php",
            "line":71,
            "function":"getIndexResponse",
            "class":"OCA\\Settings\\Controller\\AdminSettingsController",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":230,
            "function":"index",
            "class":"OCA\\Settings\\Controller\\AdminSettingsController",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
            "line":137,
            "function":"executeController",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/AppFramework/App.php",
            "line":184,
            "function":"dispatch",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Route/Router.php",
            "line":315,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::"
         },
         {
            "file":"/var/www/nextcloud/lib/base.php",
            "line":1069,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/index.php",
            "line":39,
            "function":"handleRequest",
            "class":"OC",
            "type":"::"
         }
      ],
      "File":"/var/www/nextcloud/apps/logreader/lib/Service/SettingsService.php",
      "Line":52,
      "message":"Syntax error",
      "exception":{
         
      },
      "CustomMessage":"Syntax error"
   }
}
```
```


### Additional info

_No response_

**Comment by joshtrichards** [comment] 2023-12-13 22:32
Duplicate of nextcloud/logreader#1073
Possible fix pending in nextcloud/logreader#1075

**Closed by joshtrichards** 2023-12-13 22:32 UTC
Labels: bug, 0. Needs triage
