### ISSUE TITLE
Infinite list of users

### ISSUE THREAD

**Issue by Yatulchik** [nextcloud/server#21847] opened 2020-07-15 08:53 UTC
### Steps to reproduce
1. Go to https://nextcloud.your.site/settings/users
2. In the left corner tap on "All"
3. Scroll down the list of users, at the end of the list it will be updated and all users will be added to the displayed list again, and will be added until you scroll the list to the end

### Server configuration

**Operating system:** CentOS 8.2.2004

**Web server:** nginx-1.18.0-1

**Database:** MariaDB-server-10.4.13-1

**PHP version:** php-7.3.20-1

**Nextcloud version:**  19.0.0

**Updated from an older Nextcloud:** 18.0.6

**Where did you install Nextcloud from:**  /var/www/nextcloud

**List of activated apps:**
<details>
<summary>List of activated apps</summary>
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - audioplayer: 2.10.1
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - contactsinteraction: 1.0.0
  - customproperties: 1.0.1
  - dav: 1.15.0
  - deck: 1.0.4
  - drawio: 0.9.6
  - encryption: 2.7.0
  - epubreader: 1.4.2
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_antivirus: 2.4.1
  - files_automatedtagging: 1.9.0
  - files_clipboard: 0.7.1
  - files_external: 1.10.0
  - files_markdown: 2.3.0
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - forms: 1.1.1
  - groupfolders: 6.0.6
  - ldapcontacts: 2.0.3
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - notes: 3.6.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.3.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - recommendations: 0.7.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sharingpath: 0.2.4
  - spreed: 9.0.1
  - systemtags: 1.9.0
  - tasks: 0.13.2
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflow_pdf_converter: 1.4.0
  - workflow_script: 1.4.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - browser_warning
  - comments
  - federation
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - ocr
  - serverinfo
  - support
  - survey_client
  - whiteboard
</details>

**Nextcloud configuration:**
<details>
<summary>configuration</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.primocollect.com.ua"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/nextcloud.primocollect.com.ua",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "files_external_onedrive",
            "files_external_gdrive",
            "files_clipboard"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25"
    }
}
</summary>
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP.

#### LDAP configuration
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s05                                                                                                                                                                          |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                                                                            |
| homeFolderNamingRule          |                                                                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                                                                            |
| ldapAgentName                 | CN=LDAPBind,CN=Users,DC=primocollect,DC=ua                                                                                                                                   |
| ldapAgentPassword             | ***                                                                                                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                                                                                                              |
| ldapAttributesForUserSearch   |                                                                                                                                                                              |
| ldapBackupHost                | ldap://192.168.110.5                                                                                                                                                         |
| ldapBackupPort                | 389                                                                                                                                                                          |
| ldapBase                      | CN=Users,DC=primocollect,DC=ua                                                                                                                                               |
| ldapBaseGroups                | CN=Users,DC=primocollect,DC=ua                                                                                                                                               |
| ldapBaseUsers                 | CN=Users,DC=primocollect,DC=ua                                                                                                                                               |
| ldapCacheTTL                  | 600                                                                                                                                                                          |
| ldapConfigurationActive       | 1                                                                                                                                                                            |
| ldapDefaultPPolicyDN          |                                                                                                                                                                              |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                              |
| ldapEmailAttribute            | mail                                                                                                                                                                         |
| ldapExperiencedAdmin          | 0                                                                                                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                              |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                                               |
| ldapExtStorageHomeAttribute   |                                                                                                                                                                              |
| ldapGidNumber                 | gidNumber                                                                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                                                                           |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=NextCloud)))                                                                                                                                   |
| ldapGroupFilterGroups         | NextCloud                                                                                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                                                                                            |
| ldapGroupFilterObjectclass    | group                                                                                                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                       |
| ldapHost                      | ldap://10.0.1.102                                                                                                                                                            |
| ldapIgnoreNamingRules         |                                                                                                                                                                              |
| ldapLoginFilter               | (&(|(|(memberOf:1.2.840.113556.1.4.1941:=CN=NextCloud,CN=Users,DC=primocollect,DC=ua)(primaryGroupID=1316)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                                                              |
| ldapLoginFilterEmail          | 1                                                                                                                                                                            |
| ldapLoginFilterMode           | 1                                                                                                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                                                                                                            |
| ldapNestedGroups              | 1                                                                                                                                                                            |
| ldapOverrideMainServer        |                                                                                                                                                                              |
| ldapPagingSize                | 500                                                                                                                                                                          |
| ldapPort                      | 389                                                                                                                                                                          |
| ldapQuotaAttribute            |                                                                                                                                                                              |
| ldapQuotaDefault              | 3G                                                                                                                                                                           |
| ldapTLS                       | 0                                                                                                                                                                            |
| ldapUserAvatarRule            | default                                                                                                                                                                      |
| ldapUserDisplayName           | displayname                                                                                                                                                                  |
| ldapUserDisplayName2          |                                                                                                                                                                              |
| ldapUserFilter                | (|(|(memberOf:1.2.840.113556.1.4.1941:=CN=NextCloud,CN=Users,DC=primocollect,DC=ua)(primaryGroupID=1316)))                                                                   |
| ldapUserFilterGroups          |                                                                                                                                                                              |
| ldapUserFilterMode            | 1                                                                                                                                                                            |
| ldapUserFilterObjectclass     |                                                                                                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                                                                                                         |
| turnOffCertCheck              | 1                                                                                                                                                                            |
| turnOnPasswordChange          | 0                                                                                                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                                                                                                            |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
r</details>

### Client configuration
**Browser:** Google Chrome (latest)

**Operating system:** Win10 pro v.2004

**Comment by kesselb** [comment] 2020-07-15 12:00
Closing as duplicate of https://github.com/nextcloud/server/issues/21250 and/or https://github.com/nextcloud/server/issues/21301.

**Closed by kesselb** 2020-07-15 12:00 UTC
Labels: 0. Needs triage, bug
