### ISSUE TITLE
App Data - Dark Mode

### ISSUE THREAD

**Issue by tobi614** [nextcloud/server#22737] opened 2020-09-08 16:17 UTC
### Steps to reproduce
1. Enable Dark Mode under settings -> accesibility
2. Go to App "Data"
3. Enable Listed View

### Expected behaviour
Data Settings are partly in black font.

### Actual behaviour
Font colour should be white

![Error4](https://user-images.githubusercontent.com/64694684/92501899-6ca61680-f1ff-11ea-9f11-47a335d4e5d8.JPG)

### Server configuration

**Operating system: Ubuntu 20.04.1-LTS (Linux 5.4.34-1-pve x86_64)

**Web server: apache

**Database: mysql 8.0.21

**PHP version: 7.4.3

**Nextcloud version: 19.0.1.1

**Comment by szaimen** [comment] 2020-09-08 16:29
Hi @tobi614, have you seen this?
https://github.com/nextcloud/server/issues/21069#issuecomment-632705652

**Comment by splitt3r** [comment] 2020-09-08 16:32
> 
> 
> Hi @tobi614, have you seen this?
> [#21069 (comment)](https://github.com/nextcloud/server/issues/21069#issuecomment-632705652)
> I guess this potentially fixes all your issues.

If not `ctrl + f5` should help.

**Comment by tobi614** [comment] 2020-09-08 16:50
> 
> 
> > Hi @tobi614, have you seen this?
> > [#21069 (comment)](https://github.com/nextcloud/server/issues/21069#issuecomment-632705652)
> > I guess this potentially fixes all your issues.
> 
> If not `ctrl + f5` should help.

Hi, 

thanks to your reply.
`crtl + f5` helps for the time of logged in. But it I log out and log in again the problem is still the same.
 
Is ist possible to refresh the variable `OCA.Accessibility.theme` automatically?

> 
> 
> At least the variable `OCA.Accessibility.theme` is not updated after changing between light/dark modes, until the user makes a manual refresh.
> 
> On Firefox, it is enough to hit the 'Refresh' button to fix the situation, but on Chrome/Chromium, the default behavior of the 'Refresh' button is to make a "milder refresh". There, the situation can be fixed be making the "forced refresh" by holding shift while pressing the 'Refresh' button. On the mobile Chrome, on the other hand, I haven't figured out any other way to do this except manually clearing the cached data via the History view.

**Comment by skjnldsv** [comment] 2020-09-09 10:58
Please do the following steps:
1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server

Thanks :wink:

**Comment by skjnldsv** [comment] 2020-09-09 11:12
Also duplicate of https://github.com/nextcloud/server/issues/22377

**Closed by skjnldsv** 2020-09-09 11:12 UTC
Labels: 0. Needs triage, bug

**Comment by tobi614** [comment] 2020-09-09 12:57
> 
> 
> Please do the following steps:
> 
>     1. [clear your browser's cache](https://www.refreshyourcache.com/)
> 
>     2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server
> 
> 
> Thanks 😉

I have done that and cleared my Firefox Cache. But nothing was to repair. The font is after log out and log in still black.

**Comment by tobi614** [comment] 2020-09-09 12:59
![Occ](https://user-images.githubusercontent.com/64694684/92601454-1becf700-f2ad-11ea-91bc-c007c40034a3.png)
