### ISSUE TITLE
personal sharing settings empty

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#15802] opened 2019-05-29 20:15 UTC
I just discovered that under some circumstanced the personal "sharing" settings is empty.

In a normal setup it looks like this:

![image](https://user-images.githubusercontent.com/1589737/58587912-ca0e9200-825e-11e9-8617-6aa4094a27f2.png)

But if you go to the admin sharing settings and disable "Allow users on this server to send shares to other servers" under "Federated Cloud Sharing", the personal sharing setting is empty.

First, this doesn't make sense, because as a admin I only forbid *outgoing* shares, not incoming, so it still makes sense to show me my federated cloud ID so that others can share with me. We should hide it if "Allow users on this server to receive shares from other servers" is disabled, which we don't do at the moment.

Second a complete empty share setting looks broken. If possible we should remove the menu entry on the left. If not we should at least show a nice looking placeholder, which says "You administrator disabled federated sharing" or something similar.

cc  @nextcloud/designers

**Comment by jancborchardt** [comment] 2019-05-31 11:26
> Second a complete empty share setting looks broken. If possible we should remove the menu entry on the left.

Yup, good call. The logic should be adjusted like you mentioned, and if it’s disabled the menu entry should be removed as people don’t need to know that an admin disabled anything.

**Comment by jancborchardt** [comment] 2019-05-31 11:27
@schiessle if you describe which file and roughly what would need to be changed, this would be a great "good first issue". :)

**Comment by MorrisJobke** [comment] 2019-05-31 12:01
> Yup, good call. The logic should be adjusted like you mentioned, and if it’s disabled the menu entry should be removed as people don’t need to know that an admin disabled anything.

Fix for this is already in #15804 😉

**Comment by MorrisJobke** [comment] 2019-05-31 12:02
I was wrong - it was already fixed by #15638 and is a duplicate of #7965

**Comment by schiessle** [comment] 2019-05-31 15:23
@MorrisJobke I think the fix is incomplete. Compare it with my PR.

1. we can remove the if in the personal settings https://github.com/nextcloud/server/pull/15804/commits/85f232443f37d56be1c77bf96f860d79c4e55c52
2. we should not hide it if outgoing shares are disabled but wen incoming shares are disabled. If only outgoing shares are disabled it still makes sense to share my federated cloud ID as I can receive shares

**Comment by MorrisJobke** [comment] 2019-05-31 15:31
> 2\. we should not hide the setting if outgoing shares are disabled but when incoming shares are disabled. If only outgoing shares are disabled it still makes sense to share my federated cloud ID because I can receive shares

That also confused me, but this is when the setting is also hidden. It's the same logic. Maybe there was already a bug. Let me try to fix that.

**Comment by MorrisJobke** [comment] 2019-05-31 15:41
> That also confused me, but this is when the setting is also hidden. It's the same logic. Maybe there was already a bug. Let me try to fix that.

#15830

**Closed** 2019-06-11 16:31 UTC
Labels: 3. to review, bug, feature: settings, feature: sharing, papercut
