### ISSUE TITLE
Feature request - Add option to mount external storage directly into a user's root directory

### ISSUE THREAD

**Issue by tharris5109** [nextcloud/server#7807] opened 2018-01-12 08:16 UTC
When trying to use NextCloud as a dedicated server with storage on another server, it would be useful to be able to mount external storage directly into a user's root directory rather than in a subdirectory.

I have seen workarounds where you mount the SMB storage directly to the machine (which also yields higher performance) but the way everything is set up, I want to sign in to the samba share using NextCloud credentials for the session.

Expected behaviour
Have an option to mount directly into the user's root directory.

Actual behaviour
The external storage is always mounted in a subdirectory of the user's root directory.

I'm sure I'm not the only one who would like this, right?

**Comment by MorrisJobke** [comment] 2018-01-30 13:53
Fixed in Nextcloud 12 via #3438

Duplicate of #3343

**Closed by MorrisJobke** 2018-01-30 13:53 UTC

**Comment by jj-uk** [comment] 2018-08-14 21:07
This doesn't quite work. 

If you have 3 users, userA, userB, userAdmin

userA external files are in /data/userA, mounted as / available to userA and userAdmin
userB external files are in /data/userB, mounted as / available to userB and userAdmin

Create these:
/data/userA/folder/file.txt
/data/userB/folder/different-file.txt


When userAdmin logs in and goes to external storage, he will see either "folder" containing "different-file"

userAdmin doesn't see all the files from both users, which i think is wrong. 

The only was userAdmin will see all folders for all users is if "folder name" is unique for each user.
