### ISSUE TITLE
[Bug]: Calendar dav sync iCal with Google stopped to work after the NextCloud and Calendar update

### ISSUE THREAD

**Issue by PeopleInside** [nextcloud/server#47544] opened 2024-08-27 17:14 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the recent august Nextcloud and Calendar update my Google Calendar sync with iCal has stopped to work.
Now is also impossible re-add it and see it working.
I tested also in a new installation.
I discussed this here (without a staff reply and I'm pretty sure the recent update caused issue) https://help.nextcloud.com/t/calendar-dav-sync-with-google-stopped-to-work
For another issue some staff of the forum suggested to report the issue on GitHub so I'm doing also for this issue

### Steps to reproduce

1. Open Calendar (version 4.7.16 Nextcloud version [Hub 8] (29.0.5)) 
2. Add a new calendar and insert the iCal Google url
3. An error message say is not possible add the calendar
Server error log: 
```
Error 403 MKCOL
remote.php/dav/calendars/username/calendargooglecom-1 HTTP/1.0
```

### Expected behavior

Calendar should work and be synch with Google.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

I use Firefox 129
I discussed this issue here: https://help.nextcloud.com/t/calendar-dav-sync-with-google-stopped-to-work

**Comment by PeopleInside** [comment] 2024-09-03 12:59
Issue still present with
[Nextcloud Hub 8] (29.0.6)

**Comment by PeopleInside** [comment] 2024-09-06 15:26
This has helped me to resolve the issue for me: https://github.com/nextcloud/calendar/issues/6323#issuecomment-2332565533
I don't know if keep this issue open as I never had issue with nextcloud 28, the issue is burn after nextcloud and / or calendar upgrade.

**Comment by joshtrichards** [comment] 2024-09-25 15:23
Duplicate of nextcloud/calendar#6323

**Closed by joshtrichards** 2024-09-25 15:23 UTC
Labels: bug, 0. Needs triage, 29-feedback
