### ISSUE TITLE
Shared Templates

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/server#48924] opened 2024-10-28 08:58 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I would like to have a shared folder for company-wide templates. Everybody should use the same templates for presentations and texts or whiteboards. And they should always be up to date.

**Describe the solution you'd like**
I set up an account that shares company ressources - some folders, a calendar, a deck, an addressbook and so on. It also shared its' template folder. It would be cool if users could set this folder as their template folder. But you can't set an existing folder als template folder.

It would be even better, if I could set the template folder for every user to this template folder, so I don't have to guide every new user through this setup process.

**Describe alternatives you've considered**
I know, that I can place templates in the skeleton folder. But that means that I can't update them centrally.

**Additional context**
I hope I didn't miss an existing issue for this idea. There were plenty of issues concerning templates.

**Comment by joshtrichards** [comment] 2024-11-05 13:26
Duplicate of #38198

**Closed by joshtrichards** 2024-11-05 13:26 UTC
Labels: enhancement, 0. Needs triage, feature: templates
