### ISSUE TITLE
Simplify sharing permissions for folders

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#8479] opened 2018-02-21 14:23 UTC
We currently have:
- Can reshare
- Can add
- Can edit
- Can delete

Now "can delete" does not really make much sense. If you can edit, you can delete all content of a file.

"Can add": We added this cause we originally had CRUD permissions, but do we really need it / do people use it? Usually you can either edit or not.

**Comment by MorrisJobke** [comment] 2018-02-21 14:30
> "Can add": We added this cause we originally had CRUD permissions, but do we really need it / do people use it? Usually you can either edit or not.

I think "can add" is used for the files drop stuff, isn't it? cc @nextcloud/sharing

**Comment by rullzer** [comment] 2018-02-27 12:04
Yes it is. But as long as wel keep the files drop as a separte option users don't have to care ;)

**Comment by MorrisJobke** [comment] 2018-02-27 13:41
I still think that we can slim it down to:

for internal shares:

* can reshare
* can edit

for public links

* can edit
* files drop (can add without listing files)

**Comment by MorrisJobke** [comment] 2018-03-08 09:11
Maybe should also be combined with the general overhaul of the sharing interface: #5336

**Comment by MorrisJobke** [comment] 2018-06-26 17:54
A similar request came in via #10012

**Comment by jancborchardt** [comment] 2018-06-27 15:51
@MorrisJobke something for the hackweek in July?

**Comment by MorrisJobke** [comment] 2018-07-16 21:44
Related to #6620

**Comment by skjnldsv** [comment] 2019-10-30 20:32
Fixed for internal shares ![Capture d’écran_2019-10-30_21-30-44](https://user-images.githubusercontent.com/14975046/67896392-8e089180-fb5c-11e9-8eb8-91fe91bcdca7.png)

Still the public sharing to do
![Capture d’écran_2019-10-30_21-32-30](https://user-images.githubusercontent.com/14975046/67896511-cad48880-fb5c-11e9-89fa-199a64d77ba1.png)

**Comment by skjnldsv** [comment] 2020-04-05 10:16
@jancborchardt so, do we really want this or not in the end?

**Comment by trommegutten** [comment] 2020-05-21 20:21
Hi, I'm trying to make a share link. If someone have the link, they should be able to see the folder content, upload files, but not be able to delete/edit the files. From the thread it seems like this is something you have removed from the code? Why? :)
Best regards, Jarle

**Comment by jancborchardt** [comment] 2020-05-22 19:21
> @jancborchardt so, do we really want this or not in the end?

It’s @rullzer’s call I’d say.

**Comment by trommegutten** [comment] 2020-05-23 15:27
I don't like accidents like this https://github.com/nextcloud/server/issues/6620#issuecomment-385538641

@pixelipo got some thumbs up for this suggestion:

> What about simply having 3 independent (checkbox) items:
> view (read)
> upload
> edit/delete

https://github.com/nextcloud/server/issues/6620#issuecomment-337874318 


That could be a nice way to do it, what do You think?

**Comment by marvinjuette** [comment] 2020-09-19 22:10
Hey, I am facing the same problem. And if I am correct the problem is only a front-end one because as others already pointed out one can simply change the permission to 5 in the database.

[Linkt to post that shows working solution](https://github.com/nextcloud/server/issues/6620#issuecomment-538298248)

So basically it should be easy to "add" (display) this option.

**Comment by Mannshoch** [comment] 2020-10-13 11:02
> I don't like accidents like this [#6620 (comment)](https://github.com/nextcloud/server/issues/6620#issuecomment-385538641)
> 
> @pixelipo got some thumbs up for this suggestion:
> 
> > What about simply having 3 independent (checkbox) items:
> > view (read)
> > upload
> > edit/delete
> 
> [#6620 (comment)](https://github.com/nextcloud/server/issues/6620#issuecomment-337874318)
> 
> That could be a nice way to do it, what do You think?

I personally vote for  #10012

**Comment by marvinjuette** [comment] 2020-10-13 11:34
I like the options you get offered when sharing internally. Why don't use them for public link sharing?

**Comment by pred2k** [comment] 2021-01-31 09:56
I think is this THE use case for a file exchange tool like nextcloud.
We have an event and attendees want to share photo or something else. They probably dont want/need an account. Host  dont have all their email addreses.
They can easily upload items via webui, but are not allowed to to delete everything.

Please offer public link sharing setting "upload + read only"!

**Comment by kaiserls** [comment] 2021-07-10 22:47
Dear everyone,
I would like to point out that this issue is linked to many issues which seem to be important to the nextcloud community and some of them are nearly 3 or even 4 years old (#6620, #8479). Couldn't the "upload + read only" feature get decoupled from the complete overhaul of the sharing gui and therefore be quickly published?

**Comment by kaiserls** [comment] 2021-08-30 14:45
Is this: https://github.com/nextcloud/server/pull/28635 the rework of the sharing permissions https://github.com/nextcloud/server/issues/26691 and completely ignoring this issue and all the duplicates? Or am I wrong?

**Comment by kongomongo** [comment] 2022-02-10 09:51
I have skimmed through many of those issues like @kaiserls wrote, but I have yet to see any objection to the "upload and not delete" and/or finger-grain control of the https://github.com/nextcloud/server/blob/master/lib/public/Constants.php permissions.

What is the root cause for no progress?

**Comment by skjnldsv** [comment] 2024-01-19 16:30
Done no? @artonge @jancborchardt

**Comment by sweenu** [comment] 2024-01-19 18:04
If you close this issue, please re-open https://github.com/nextcloud/server/issues/6620 because it was closed as duplicate of this issue even though it definitely does seem to be fixed: we still don't have a way to have File Upload + Read on a folder.

**Comment by skjnldsv** [comment] 2024-01-20 11:52
> we still don't have a way to have File Upload + Read on a folder.

Hmm, yes you can?
![image](https://github.com/nextcloud/server/assets/14975046/c45a2864-dfc7-4189-ba5a-d928a95da6c5)

**Comment by sweenu** [comment] 2024-01-20 15:38
Oh great news! I had tried on the android app, assuming permissions would be the same on every platforms. But indeed, I should have tried on the web before commenting 👍🏽 Great job.

**Closed** 2024-01-20 16:24 UTC
Labels: enhancement, design, 4. to release, feature: sharing, client: 💻 desktop, client: 🤖🍏 mobile
