### ISSUE TITLE
occ-cli: Allow checking "twofactorauth:state" for list of users

### ISSUE THREAD

**Issue by neufeind** [nextcloud/server#34047] opened 2022-09-13 09:31 UTC
Currently you can check the state for just one uid. It would be nice to be able to also use "--all-users" or something as to not check each user individually.

**Comment by solracsf** [comment] 2022-09-13 12:04
Duplicate of https://github.com/nextcloud/twofactor_totp/issues/1210

**Closed by solracsf** 2022-09-13 12:04 UTC
Labels: enhancement, 0. Needs triage
