### ISSUE TITLE
[Bug]: Desktop Client not synchronizing after upgrade from 24 to 25

### ISSUE THREAD

**Issue by d-sko** [nextcloud/server#34719] opened 2022-10-21 07:25 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the upgrade from 24 to 25 desktop clients are not synchronizing anymore. They  show an sychronization error:
> Server responded with an error while reading directory "" : Error transferring https://domain/remote.php/dav/files/username/ - server replied: Internal Server Error

(maybe not the original english message, translated from client in german)

The server shows an Class `\"OCP\\App\" not found` error, see full error message below.

### Steps to reproduce

1. [if not already done] install desktop client
2. [if not already done] add account
3. client tries to sync files and fails

### Expected behavior

Client should synchronize the files like before the upgrade.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<redacted>"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "<redacted>",
        "htaccess.RewriteBase": "\/",
        "overwritehost": "<redacted>",
        "dbtype": "mysql",
        "version": "25.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_smtpmode": "smtp",
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "check_for_working_htaccess": true,
        "updater.release.channel": "stable",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "config_is_read_only": false,
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "default_phone_region": "DE",
        "force_language": "de",
        "simpleSignUpLink.shown": false,
        "has_rebuilt_cache": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - dav: 1.24.0
  - deck: 1.8.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.0.0
  - guests: 2.3.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - richdocuments: 7.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{
	"reqId": "DWnIFU9CJO2qE6kMrbzE",
	"level": 3,
	"time": "2022-10-21T06:42:15+00:00",
	"remoteAddr": "<redacted>",
	"user": "<redacted>",
	"app": "webdav",
	"method": "PROPFIND",
	"url": "/remote.php/dav/files/<redacted>/",
	"message": "Class \"OCP\\App\" not found",
	"userAgent": "Mozilla/5.0 (Windows) mirall/3.6.0stable-Win64 (build 20220906) (Nextcloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
	"version": "25.0.0.18",
	"exception": {
		"Exception": "Error",
		"Message": "Class \"OCP\\App\" not found",
		"Code": 0,
		"Trace": [
			{
				"file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php",
				"line": 387,
				"function": "getDirectDownload",
				"class": "OCA\\DAV\\Connector\\Sabre\\File",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php",
				"line": 95,
				"function": "OCA\\DAV\\Connector\\Sabre\\{closure}",
				"class": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin",
				"type": "->",
				"args": [
					"*** sensitive parameters replaced ***"
				]
			},
			{
				"file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php",
				"line": 397,
				"function": "handle",
				"class": "Sabre\\DAV\\PropFind",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
				"line": 89,
				"function": "handleGetProperties",
				"class": "OCA\\DAV\\Connector\\Sabre\\FilesPlugin",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 1052,
				"function": "emit",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 984,
				"function": "getPropertiesByNode",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 1662,
				"function": "getPropertiesIteratorForPath",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 1647,
				"function": "writeMultiStatus",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
				"line": 346,
				"function": "generateMultiStatus",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
				"line": 89,
				"function": "httpPropFind",
				"class": "Sabre\\DAV\\CorePlugin",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 472,
				"function": "emit",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 253,
				"function": "invokeMethod",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
				"line": 321,
				"function": "start",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/apps/dav/lib/Server.php",
				"line": 360,
				"function": "exec",
				"class": "Sabre\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
				"line": 35,
				"function": "exec",
				"class": "OCA\\DAV\\Server",
				"type": "->"
			},
			{
				"file": "/var/www/nextcloud/remote.php",
				"line": 167,
				"args": [
					"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
				],
				"function": "require_once"
			}
		],
		"File": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
		"Line": 500,
		"message": "Class \"OCP\\App\" not found",
		"exception": {

		},
		"CustomMessage": "Class \"OCP\\App\" not found"
	}
}
```

### Additional info

I've tested with Client 3.6.0 and 3.6.1 on Windows 10 64bit and Linux Mint 21 Cinnamon, same error.

**Comment by pggj** [comment] 2022-10-22 08:15
Have the same issue, wirth a linux server, during update this night, with this error message :
## error log (server)
```
{
  "reqId": "***REMOVED SENSITIVE VALUE***",
  "level": 3,
  "time": "2022-10-22T07:56:08+00:00",
  "remoteAddr": "***REMOVED SENSITIVE VALUE***",
  "user": "***REMOVED SENSITIVE VALUE***",
  "app": "webdav",
  "method": "PROPFIND",
  "url": "/remote.php/dav/files/***REMOVED SENSITIVE VALUE***",
  "message": "No read permissions",
  "userAgent": "Mozilla/5.0 (Linux) mirall/3.5.1 (build 10305) (Nextcloud, ubuntu-5.15.0-50-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)",
  "version": "25.0.0.18",
  "exception": {
    "Exception": "OCA\\DAV\\Connector\\Sabre\\Exception\\Forbidden",
    "Message": "No read permissions",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php",
        "line": 200,
        "function": "getChildren",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 900,
        "function": "getChildren",
        "class": "Sabre\\DAV\\Tree",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 982,
        "function": "generatePathNodes",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1662,
        "function": "getPropertiesIteratorForPath",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1647,
        "function": "writeMultiStatus",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 346,
        "function": "generateMultiStatus",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPropFind",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
        "line": 360,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 167,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
    "Line": 258,
    "message": "No read permissions",
    "exception": {},
    "CustomMessage": "No read permissions"
  }
}
```

## List of activated Apps
```
Enabled:
  - activity: 2.17.0
  - appointments: 1.12.8
  - bruteforcesettings: 2.5.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0
  - end_to_end_encryption: 1.10.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_automatedtagging: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.3
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_gateway: 0.20.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
```

## Configuration report
```{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.0.18",
        "overwrite.cli.url": "https:\/\/cloud.mathsimo.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_locale": "fr",
        "default_language": "fr",
        "force_locale": "fr",
        "force_language": "fr",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": "1",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "loglevel": 0,
        "app_install_overwrite": [
            "spreed",
            "ransomware_protection",
            "twofactor_gateway",
            "end_to_end_encryption",
            "appointments",
            "richdocumentscode"
        ],
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "FR"
    }
}
```

**Comment by pggj** [comment] 2022-10-22 08:57
So, i had 2 WebDav external storage that where not working, i delete them, and lanch a ```occ files:scan --all```, and it work well now !

For information, when i proceed to an udpdate of nextcloud, i always procced to a file scan, who had this error before deleting external storage :

```
Exception during scan: Sabre\HTTP\ClientHttpException: Unauthorized
#0 /var/www/nextcloud/lib/private/Files/Storage/DAV.php(287): OC\Files\Storage\DAV->convertException()
#1 /var/www/nextcloud/lib/private/Files/Storage/DAV.php(715): OC\Files\Storage\DAV->propfind()
#2 /var/www/nextcloud/lib/private/Files/Storage/Common.php(715): OC\Files\Storage\DAV->getPermissions()
#3 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(599): OC\Files\Storage\Common->getMetaData()
#4 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php(140): OC\Files\Storage\Wrapper\Wrapper->getMetaData()
#5 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(599): OC\Files\Storage\Wrapper\PermissionsMask->getMetaData()
#6 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php(447): OC\Files\Storage\Wrapper\Wrapper->getMetaData()
#7 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(599): OC\Files\Storage\Wrapper\Availability->getMetaData()
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(116): OC\Files\Storage\Wrapper\Wrapper->getMetaData()
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(154): OC\Files\Cache\Scanner->getData()
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanFile()
#11 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(256): OC\Files\Cache\Scanner->scan()
#12 /var/www/nextcloud/apps/files/lib/Command/Scan.php(144): OC\Files\Utils\Scanner->scan()
#13 /var/www/nextcloud/apps/files/lib/Command/Scan.php(200): OCA\Files\Command\Scan->scanFiles()
#14 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()
#15 /var/www/nextcloud/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#19 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#20 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#21 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#22 {main}

```
Still experimenting some issues with end-to-end encryption so ...

**Comment by phwoomp** [comment] 2022-10-22 10:59
I am getting a similar error message from the NC desktop client when trying to sync to my server:
"Server replied with an error while reading directory "": Error transferring https://my.server.net/remote.php/dav/files/username/ - server replied: Internal Server Error
Error while loading the list of folders from the server."

Deleting the data on the server and then running "scan --all" will let the folder sync again. Re-uploading the data via the desktop client to the empty folder on the server seemed to work correctly for a while, but at some point the same error returned.

Here is an error log from the server:
```
[webdav] Error: TypeError: OCA\DAV\Connector\Sabre\FilesPlugin::OCA\DAV\Connector\Sabre\{closure}(): Return value must be of type ?int, float returned at <<closure>>

 0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 1. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 356
    Sabre\DAV\PropFind->handle()
 2. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties()
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit()
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode()
 5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
 8. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
11. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
12. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
13. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
14. /var/www/nextcloud/remote.php line 167
    require_once("/var/www/nextcl ... p")
```

**Comment by d-sko** [comment] 2022-10-24 07:34
I could fix the issue by replacing the dav app with the one in the latest archive from https://download.nextcloud.com/server/releases/latest.tar.bz2

**Comment by PVince81** [comment] 2022-10-28 10:56
if the latest archive works already, you might want to try with 25.0.1 RC1 as it was probably fixed already

however I was not able to quickly find which PR it was

**Comment by MichaIng** [comment] 2022-10-31 15:20
I just tested NC25 RC1 and it does not solve the issue. Not sure how `latest.tar.bz2` could have solved it, unless some cache layer still has it pointing to NC24. In my case, it's NC25 with the issue present.

Here the PR which caused the underlying type hint: https://github.com/nextcloud/server/commit/829490ab7a02579c6b31573c3f53428e86cbf2e0#diff-1d6ed4804160da213bc58248990a6936622ce53100a23535d207dba153f7e759

**Comment by szaimen** [comment] 2022-11-01 23:24
Duplicate of https://github.com/nextcloud/server/issues/34674

**Closed by szaimen** 2022-11-01 23:24 UTC
Labels: bug, 0. Needs triage, 25-feedback

**Comment by d-sko** [comment] 2022-11-04 08:03
The same error happened again after updating to 25.0.1 by command line update (`class "OCP\App" not found`). Could fix again by replacing the dav app with the one from the latest archive.
