### ISSUE TITLE
[Bug]: Files -> Deleted files: sorted by deleted leads to a "display bug"?

### ISSUE THREAD

**Issue by AmatorPhasma** [nextcloud/server#40484] opened 2023-09-18 15:08 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello, when you switch to the "Deleted files" section in the Files app and sort them by deletion date (ascending or descending doesn't matter), and you have several files (in my case, 120), and you can scroll, it causes the sorting by date to suddenly become mixed up. BUT, only the date, the file names remain in the correct order.

### Steps to reproduce

1. have ~120 deleted files
2. go to files -> deleted files
3. sort by date (deleted)
4. scroll down (really you have to scroll down a bit ~4 sites)
5. you can spot dates out of order
6. scroll back up, an even here you can see dates out of order.

Example GIF (not a loop):
![sorting_002](https://github.com/nextcloud/server/assets/49910825/376df437-e2fb-4924-83b3-07083e70fb68)

### Expected behavior

Dates not out of order

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "activity_use_cached_mountpoints": true,
        "config_is_read_only": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxx.xx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "lost_password_link": "https:\/\/atlantis.xxx.xx\/password",
        "dbtype": "mysql",
        "version": "27.1.0.7",
        "overwrite.cli.url": "https:\/\/cloud.xxx.xx",
        "overwritehost": "cloud.xxx.xx",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "x-http-forwarded-for"
        ],
        "upgrade.disable-web": true,
        "activity_expire_days": 30,
        "auth.bruteforce.protection.enabled": false,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "default_phone_region": "DE",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc"
        ],
        "profile.enabled": false,
        "defaultapp": "dashboard",
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "default_language": "de_DE",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_memory": 256,
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 1
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Freigaben",
        "skeletondirectory": "\/var\/nc_data\/skeleton",
        "theme": "",
        "trashbin_retention_obligation": "auto, 90",
        "versions_retention_obligation": "auto, 60",
        "updater.release.channel": "stable",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpport": "587",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.6.2
  - calendar: 4.5.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - group_default_quota: 0.1.7
  - groupfolders: 15.3.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.3.2
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.10.3
  - spreed: 17.1.0
  - support: 1.10.0
  - systemtags: 1.17.0
  - tables: 0.6.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_nextcloud_notification: 3.7.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - firstrunwizard: 2.16.0 (installed 2.10.0)
  - survey_client: 1.15.0 (installed 1.9.0)
  - suspicious_login: 5.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
No errors, only some "Login failed" :)
```

### Additional info

Had one confimation from an other user about this: https://help.nextcloud.com/t/files-sorting-issue-in-deleted-files/170327

**Comment by szaimen** [comment] 2023-11-07 11:50
cc @skjnldsv

**Comment by skjnldsv** [comment] 2023-11-07 11:55
[`27.1.0.7`](https://github.com/nextcloud/server/compare/v27.1.0...v27.1.3)
Please upgrade to latest 27

**Comment by ItsMeRitch** [comment] 2023-11-07 12:46
@skjnldsv 

Still having issues even with latest version 

https://github.com/nextcloud/server/issues/41292

Thanks

**Comment by ItsMeRitch** [comment] 2023-11-07 12:50
Hi @skjnldsv 

I'm on the latest version and still having issues. 

Please see my now closed ticket (didn't realise it was a dupe) 

https://github.com/nextcloud/server/issues/41292

Thanks

**Comment by XueSheng-GIT** [comment] 2023-11-07 16:08
I'm also on 27.1.3 and clicking on sort again doesn't solve the issue.

**Comment by skjnldsv** [comment] 2023-11-07 16:31
I can reproduce the issue. It's about the re-render of the custom columns, but not on 28.

**Comment by NikolausDemmel** [comment] 2024-01-03 10:54
I also just ran into this on NC 27.

> It's about the re-render of the custom columns, but not on 28.

Are you saying the issue is fixed with NC 28?

**Comment by skjnldsv** [comment] 2024-01-10 16:28
Yes @NikolausDemmel ! Fixed on 28

**Comment by joshtrichards** [comment] 2024-09-06 20:00
> Fixed on 28

<28 is eol so closing this as fixed.

**Closed by joshtrichards** 2024-09-06 20:00 UTC
Labels: bug, 1. to develop, feature: files, feature: trashbin, regression, 27-feedback
