### ISSUE TITLE
Hundreds of "web-file-upload" directories

### ISSUE THREAD

**Issue by christianreiss** [nextcloud/server#12773] opened 2018-12-02 10:17 UTC
Hey folks,

very quick question. Running NC14 (updating way back from OwnCloud single-digit versions) on Linux. Everything is fine, functionality is awesome. Only one issue. There seem to be amassing hundreds of directories in the data dir "${user}/uploads/web-file-upload-*" ranging in the three-digit GBs.

Timestamps are rather old. Is is safe to expunge those directories?

-Christian.

**Comment by j-ed** [comment] 2018-12-02 12:42
I seems that you've ignored the recommendation to search for similar issue tickets before opening a new one. Otherwise you should have stumbled over these issue tickets : https://github.com/nextcloud/server/issues/8753, https://github.com/nextcloud/server/issues/8759 😉

**Comment by christianreiss** [comment] 2018-12-02 13:33
I did see those. Those are in the flavor of "How to fix NextCloud". This question is more to "How to workaround for now". User Login et all did not work; hence the hundreds of GB of wasted space.
Also this is why this is a pretty bool question: Directories safe to delete?

**Comment by christianreiss** [comment] 2018-12-06 19:50
Seems this issue is not as trivial as everyone wants it to be :)

**Comment by skjnldsv** [comment] 2018-12-08 11:06
@christianreiss Yes, this is a duplicate of #8753
And a feature request is opened on #8759

**Comment by skjnldsv** [comment] 2018-12-08 11:07
Duplicate of #8753
And a feature request is opened on #8759

**Closed by skjnldsv** 2018-12-08 11:06 UTC
