### ISSUE TITLE
Share: Cannot check the checkbox "Can Edit" 

### ISSUE THREAD

**Issue by Recretix** [nextcloud/server#6374] opened 2017-09-06 08:09 UTC
### Steps to reproduce
1. Updated Nextcloud from 11 to 12
2. Create a share and share it with a group which was already there before the update.
3.Check or uncheck the "Can edit" box 

### Expected behaviour
The box should be getting checked or unchecked.

### Actual behaviour
When you click on the the box it stays at the default value until you refresh the website.
It changes the value in the backgroud but it doesn't update the box until you refresh the website.
With a new created group it's working fine.

### General server configuration

**Operating system:** Linux RB00SRV061 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.31

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - gmp
 - iconv
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.4

**Where did you install Nextcloud from:**  tar.bz2 from Webpage

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No
(LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_notifications: 1.0.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - dav: 1.3.0
 - deck: 0.2.1
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - onlyoffice: 1.1.3
 - ownbackup: 17.5.0
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - weather: 1.5.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - activitylog
 - admin_audit
 - contacts
 - encryption
 - federation
 - files_external
 - systemtags
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocgdaki4wkwv",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "127.0.0.1",
        "nextcloud.recretix.ch"
    ],
    "datadirectory": "\/sdb_data\/owncloud\/data\/",
    "overwrite.cli.url": "https:\/\/nextcloud.recretix.ch\/",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "ocdb",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "maintenance": false,
    "loglevel": 0,
    "theme": "",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "notifications",
    "mail_domain": "recretix.ch",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "mail.cyon.ch",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "session_lifetime": 5400,
    "updater.release.channel": "beta"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2017-09-06 08:18
Looks like a duplicate of #5916

**Closed by MorrisJobke** 2017-09-06 08:18 UTC
