### ISSUE TITLE
[Bug]: files_external SMB/CIFS save login credentials in session broken

### ISSUE THREAD

**Issue by chris-se** [nextcloud/server#39097] opened 2023-07-01 05:24 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Commit https://github.com/nextcloud/server/commit/2466724b018f07753cb694e313149b09a2afa643 appears to have broken authentication to external storage in some circumstances, the logs contain the following error message:

    Call to a member function getUID() on null in file '[...]/apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php' line 61

If I change

    if ($credentials->getUID() !== $user->getUID()) {

to

    if ($user !== null && $credentials->getUID() !== $user->getUID()) {

in `apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php` (line 61), then it appears to solve the problem for me. (But I haven't had the time to completely understand the entire class structure of the project, so I don't know if this fix is actually correct.)

### Steps to reproduce

1. Configure nextcloud to use AD/LDAP authentication
2. Activate the files_external app and attempt to configure a SMB/CIFS share using the setting *Log-in credentials, save in session*
3. The share can't be configured properly (the icon on the left side of the list is always red).

### Expected behavior

The share can be configured without issues.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED***",
            "***REMOVED***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.0.8",
        "overwrite.cli.url": "***REMOVED***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_phone_region": "de",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "skeletondirectory": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.10.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.0
  - password_policy: 1.17.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - survey_client: 1.15.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - activity: 2.19.0 (installed 2.19.0)
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.4.3 (installed 4.4.3)
  - circles: 27.0.0 (installed 27.0.0)
  - comments: 1.17.0 (installed 1.17.0)
  - contacts: 5.3.2 (installed 5.3.2)
  - contactsinteraction: 1.8.0 (installed 1.8.0)
  - dashboard: 7.7.0 (installed 7.7.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.17.0)
  - mail: 3.2.3 (installed 3.2.3)
  - notes: 4.8.0 (installed 4.8.0)
  - photos: 2.3.0 (installed 2.3.0)
  - richdocuments: 8.1.0 (installed 8.1.0)
  - spreed: 17.0.1 (installed 17.0.1)
  - support: 1.10.0 (installed 1.10.0)
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0 (installed 1.17.0)
  - text: 3.8.0 (installed 3.8.0)
  - twofactor_totp: 9.0.0
  - weather_status: 1.7.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"2290lJTDTzu8nG0PKtah","level":3,"time":"2023-06-30T16:29:46+00:00","remoteAddr":"[REMOVED]","user":"[REMOVED]","app":"index","method":"GET","url":"/index.php/apps/files_external/globalstorages/2?testOnly=true","message":"Call to a member function getUID() on null in file '[...]/apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php' line 61","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"27.0.0.8","exception":{"Exception":"Exception","Message":"Call to a member function getUID() on null in file '[...]/apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php' line 61","Code":0,"Trace":[{"file":"[...]/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"[...]/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"[...]/lib/base.php","line":1064,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"[...]/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"[...]/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"file":"[...]/apps/files_external/lib/Controller/StoragesController.php","line":264,"function":"manipulateStorageConfig","class":"OCA\\Files_External\\Lib\\Auth\\Password\\SessionCredentials","type":"->"},{"file":"[...]/apps/files_external/lib/Controller/StoragesController.php","line":281,"function":"manipulateStorageConfig","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->"},{"file":"[...]/apps/files_external/lib/Controller/StoragesController.php","line":363,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"[...]/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"show","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->"},{"file":"[...]/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"[...]/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"[...]/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"[...]/lib/base.php","line":1064,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"[...]/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"[...]/apps/files_external/lib/Lib/Auth/Password/SessionCredentials.php","Line":61},"CustomMessage":"--"}}
```

**Comment by joshtrichards** [comment] 2023-07-01 15:39
Hi @chris-se. Good catch!

I think the root cause is here:

https://github.com/nextcloud/server/blob/914cb809b407e13914f2dbafe8c2fd686838f228/apps/files_external/lib/Controller/StoragesController.php#L261-L281


Probably need a few`$this->userSession->getUser()` parameters slipped in there so that `$user` doesn't end up defaulting to null.

**Comment by violethaze74** [comment] 2023-07-01 16:41
@dependabot-bot

**Comment by chris-se** [comment] 2023-07-01 19:45
@joshtrichards I've grepped a bit through the source code, and from reading it with your reply in mind, you'll probably also need to edit `Command/Verify.php`, and that command also needs to get passed the current user session to access that information.

Plus, if the `$user` parameter should never be `null` in that method, shouldn't you remove the default value in the method declaration in that case?

I don't think I grok the details of the rest of the source enough to also add the changes to the `Verify` command, but if you do come up with a patch for this, I'll happily test that (without the `!== null` check I have currently in there on my system).

**Comment by szaimen** [comment] 2023-07-10 09:49
cc @icewind1991 @nextcloud/server-backend

**Comment by icewind1991** [comment] 2023-09-21 14:37
I believe that this is resolved with https://github.com/nextcloud/server/commit/38480fda3cd1f10652bc1e854207b074921e66b8#diff-30825d27d95b73e4907f827f96b4f3fe8c470450583c2d7040a60bf62f401369

**Closed by icewind1991** 2023-09-21 14:37 UTC
Labels: bug, feature: external storage, 0. Needs triage, 27-feedback
