### ISSUE TITLE
Group Restricted or Folder Restricted Tags

### ISSUE THREAD

**Issue by compumatter** [nextcloud/server#6405] opened 2017-09-07 15:53 UTC
I am using Nextcloud 12.

I am not looking for an automatic method but a way for me to restrict the scope of where tags appear.

For instance, I am a website developer.  if I have 2 folders which I have shared with 2 different clients and I wish to create some tags to identify which page their photos should appear on.  So when they add a photo to the shared folder they can tag it appropriately

Client one is a Doctor
Doctor Page Tags:  Home, Contact, About, Procedures, Appointments

Client two is an Indian Chief
Chief Page Tags: Home, Contact, Feather styles, Buffalo related, Wampums 4 sale, Pow wow events

I would want some of them to be visible on another, but clearly not others.

I have seen evidence in previous posts that Restricted Tags was available for 12 but have not seen this working.

Your thoughts are appreciated.

Jay #6392 
![tags-restricted](https://user-images.githubusercontent.com/121611/30174061-a39a6608-93ae-11e7-9af7-7234eac405c7.png)

**Comment by blizzz** [comment] 2017-09-07 22:25
These tags are system wide, it's not possible to restrict them to users or groups as of now.

**Comment by compumatter** [comment] 2017-09-07 22:35
Hello,

I was confused by this because of the reference to "restrict" tags in 
the Admin > Workflow area.

It appears this feature is in some kind of a hold pattern.  It would be 
helpful if that screen made mention that his was 'future feature' or 
some other thing.  I personally have spent 1/2 of a day trying to figure 
out why I wasn't seeing the restricted criteria.

Also, I have reference to a bounty ?   If I put a few hundred into this 
is there any possibility it would come quickly ?

Thanks.

Jay
CompuMatter

**Comment by blizzz** [comment] 2017-09-07 22:43
@nickvergessen ^

**Comment by nickvergessen** [comment] 2017-09-08 10:10
Well "Restricted" means that users can see, but not (un)assign the tags.

For "hiding" tags, see:
https://github.com/nextcloud/server/issues/4699 for a greater plan
https://github.com/nextcloud/server/issues/621 for group based tags

**Comment by nickvergessen** [comment] 2017-09-08 10:11
So I think this one is a duplicate of #621 and I'm closing this.

**Closed by nickvergessen** 2017-09-08 10:11 UTC
Labels: feature: tags

**Comment by JamesWaldron** [comment] 2018-01-04 09:35
Is the 'Restricted' tags working as expected? The only way i can get a user to see any restricted tags is to make them an 'admin'?
