### ISSUE TITLE
Feature Request | Sort user by last logon time

### ISSUE THREAD

**Issue by k1ngf15h3r** [nextcloud/server#6209] opened 2017-08-21 18:16 UTC
To check inactive users in a big environment it would be very helpful to be possible to sort users by last logon time

### Steps to reproduce
1. As admin go to users management 
2. In settings on the left bottom corner select "show last logon"
3. try to sort users by last logon time by clicking the row title

### Expected behaviour
sorting by last logon time

### Actual behaviour
users only sorted only by name

### Server configuration

**Operating system**: Cent OS 7

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** PHP7

**Nextcloud version:** (see Nextcloud admin page) 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** docker hub

**Signing status:** ok

**Comment by MorrisJobke** [comment] 2017-08-21 20:12
Duplicate of #3230

**Closed by MorrisJobke** 2017-08-21 20:12 UTC
