### ISSUE TITLE
File specific versioning settings

### ISSUE THREAD

**Issue by FlyingKawasaki74** [nextcloud/server#22456] opened 2020-08-27 09:59 UTC
As of now file versioning settings are controlled globally in the config.php according to the following documentation: https://docs.nextcloud.com/server/14/admin_manual/configuration_files/file_versioning.html

I would like to request a feature to override this global config on a per-file-case. For example I might set the global setting to 'auto, D', while setting it to 'auto' for a small file (e.g. a KeePass DB file). 

Right now I don't see how to add tags to this, so I recommend: "enhancement" and "feature: files"

**Comment by jospoortvliet** [comment] 2020-09-14 16:09
Interesting idea, indeed. I wouldn't hold my breath, but perhaps somebody wants to pick this up some day ;-)

**Comment by joshtrichards** [comment] 2024-11-19 18:35
Duplicate of #17566

**Closed by joshtrichards** 2024-11-19 18:35 UTC
Labels: enhancement, 1. to develop, feature: files, feature: versions
