### ISSUE TITLE
occ tool to export/import calendars and addressbooks

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#564] opened 2016-07-26 09:12 UTC
Would be good to have a occ tool to export all calendars and addressbook into a standard format and import them again, either for the whole system or on a per user basis. Especially for large installations this helps to avoid running into timeouts, etc.

**Comment by Faldon** [comment] 2016-07-29 08:50
For export/import calendar events of a single user, we could export a single .ics file. Drawback is, we would have to specify the calendar to import to. 
For migrations of a user or whole systems, we need to export the current structure too, so we can import the events into the right calendar (or create it, if it not exists yet).

**Comment by klawdhfzasjhaa** [comment] 2019-07-07 20:43
Would be a great feature. Can't access my Nextcloud through the browser, but OCC stills works.

**Comment by georgehrke** [comment] 2019-09-14 13:35
Some common work with: https://github.com/nextcloud/server/issues/2864

**Comment by skorpions2000** [comment] 2022-04-24 13:18
Do you have any solution for this problem?

**Comment by szaimen** [comment] 2022-04-24 13:33
I guess it will be handled in https://github.com/nextcloud/user_migration/issues/94

**Comment by Pytal** [comment] 2022-06-01 01:13
Closed by https://github.com/nextcloud/user_migration/pull/167

**Closed by Pytal** 2022-06-01 01:13 UTC
Labels: enhancement, 1. to develop, feature: dav, feature: caldav, feature: carddav

**Comment by c33s** [comment] 2024-02-06 01:17
@Pytal can we reopen this please? mass/batch import is not solved by the linked ticket https://github.com/nextcloud/user_migration/pull/167

we need a bridge to the existing gui import tool from the cli so we can automate things.

i just imported 10 calendars to new calendars only to notice that all imported calendars result in a calendar name in the url prefixed by `imported-` `https://localhost/remote.php/dav/calendars/username/imported-personalics/` 

so delete all again and first create 10 empty calendars and then import the right calendar file in the right calendar. this is really a terrible UX.

**Comment by Pytal** [comment] 2024-02-06 02:18
The linked PR imports each ics file into a new calendar by design to avoid data loss if overwritten by accident when importing to the same calendar URI

If more granular control over the way data is imported is desired please open a new issue @c33s

**Comment by c33s** [comment] 2024-02-06 02:33
@Pytal i am not sure i understand, the linked PR is only about export and is not related to import. so i don't understand that it can close a ticket that is about import AND export

i am looking for something like:
```
ncc dav:create-calendar username calendarname --import my-file.ics --color=ffff00
```

should i open a new ticket or can we reopen this, so the subscribed persons don't have to resubscribe the issue again?

**Comment by Pytal** [comment] 2024-02-06 02:58
Right, sorry @c33s I misremembered and thought that selective import was already possible

This would indeed be a new feature so please open a new issue for import and more granular control
