### ISSUE TITLE
Chuncked upload on public upload

### ISSUE THREAD

**Issue by smd0709** [nextcloud/server#24676] opened 2020-12-12 14:50 UTC
Hi.
My site is behind Cloudflare and it limits the maximum file upload size (100MB).
When a logged in user uploads files there is no problem because by the chunk size I limit it to below 100MB, but in public uploads (link created to upload files without having to have an account on the site) these uploads are not segmented and it only allows me upload to a maximum of 100MB due to Cloudflare.
Is it possible to segment (chunk) uploads through public links? In the same way that a logged in user would do to avoid this problem.
Thank you.

**Comment by kesselb** [comment] 2020-12-12 16:03
Duplicate of https://github.com/nextcloud/server/issues/12321

**Closed by kesselb** 2020-12-12 16:03 UTC
Labels: 0. Needs triage, enhancement
