### ISSUE TITLE
[BITV] 9.1.4.12/2.2 - When text spacing is increased, the contents of the "Recent activity" tile become inaccessible (unreadable). (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36978] opened 2023-03-01 19:30 UTC
<img width="354" alt="e21d287f05e27f206ef40774af70c8df" src="https://user-images.githubusercontent.com/1315170/222244565-9be0db73-6916-4fe7-a4ff-3fdf18258e86.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-873c7fa715-v2-n2

</details>

**Comment by JuliaKirschenheuter** [comment] 2023-06-16 08:29
I guess this criteria have to be filled out https://www.w3.org/TR/WCAG21/#text-spacing
for testing i'm using https://chrome.google.com/webstore/detail/text-spacing-editor/amnelgbfbdlfjeaobejkfmjjnmeddaoj/related

**Comment by JuliaKirschenheuter** [comment] 2023-06-16 08:36
I'm testing but can't reproduce this issue

![Screenshot from 2023-06-16 10-35-06](https://github.com/nextcloud/server/assets/6078378/356aa1a4-3bb5-43d9-af70-b9c4c5cbbe5a)

**Comment by JuliaKirschenheuter** [comment] 2023-06-16 08:40
@michaelnissenbaum have i missed something to configure or check? 
Thank you!

**Comment by JuliaKirschenheuter** [comment] 2023-06-21 13:10
Ok, I've checked this issue with second tool: ARC Toolkit and seems to be fine ;)

![Screenshot from 2023-06-21 15-10-01](https://github.com/nextcloud/server/assets/6078378/00221609-9da1-43c0-b2ba-f234ea6c5173)

closing issue

**Comment by AndyScherzinger** [comment] 2023-06-26 11:23
- [ ] Check Dashboard widgets

**Comment by JuliaKirschenheuter** [comment] 2023-06-26 12:48
still looks ok: 
![Screenshot from 2023-06-26 14-46-47](https://github.com/nextcloud/server/assets/6078378/b40cf96a-4658-477a-9d0c-47ba126679be)

**Comment by JuliaKirschenheuter** [comment] 2023-06-26 12:52
looks not ok with Text spacing editor: 

![Screenshot from 2023-06-26 14-51-57](https://github.com/nextcloud/server/assets/6078378/fe1d7bcc-ea60-4885-a089-ba1d1da7831d)

**Closed** 2023-07-04 11:15 UTC
Labels: 2. developing, accessibility
