### ISSUE TITLE
[NC17] Broken update notification

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#17346] opened 2019-10-01 03:03 UTC
When nextcloud update is avail, folowing notification showed on every page

![изображение](https://user-images.githubusercontent.com/12619075/65931118-b6ad4680-e44b-11e9-9db2-362be90b586b.png)

**Comment by dohlin** [comment] 2020-02-13 17:06
I too am getting this using the linuxserver docker container, caused by the update notifications app.  If I disable that app all prompts go away, but with it enabled I see if every time there is an update available.  Latest version of NC currently (18.0.1).

**Comment by szaimen** [comment] 2021-05-31 08:54
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by mrtnmtth** [comment] 2021-05-31 11:53
Should be fixed via https://github.com/nextcloud/server/pull/23175

**Closed** 2021-05-31 11:53 UTC
Labels: 0. Needs triage, bug, needs info
