### ISSUE TITLE
Nextcloud Dashboard v7.3.0 - Internal Server Error

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/server#32525] opened 2022-05-21 00:04 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I have the following NC version installed:
- Nextcloud Hub II (23.0.4)
- OS: Ubuntu 20.04.4 LTS (64bit)

### Steps to reproduce

1. Update Nextcloud Dashboard to version 7.3.0
2. Open Dashboard
3. Internal Server Error appears

### Expected behavior

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - announcementcenter: 6.3.0
  - apporder: 0.15.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.1
  - camerarawpreviews: 0.7.15
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.1
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - extract: 1.3.5
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - gestion: 2.1.1
  - groupfolders: 11.1.4
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.12.0
  - metadata: 0.16.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - previewgenerator: 5.0.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.14.0
  - richdocuments: 5.0.5
  - richdocumentscode: 21.11.402
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - video_converter: 1.0.5
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflow_pdf_converter: 1.8.0
  - workflowengine: 2.5.0
Disabled:
  - encryption
  - federation: 1.9.0
  - nextcloud_announcements: 1.9.0
  - recommendations: 0.7.0
  - support: 1.2.1
  - text: 3.1.0
  - user_ldap
```

### Nextcloud Logs

```shell
{"reqId":"Os6Wb6bTeeq942opgnel","level":3,"time":"2022-05-20T23:51:44+00:00","remoteAddr":"192.168.20.177","user":"admin","app":"core","method":"GET","url":"/apps/dashboard/","message":"plainMessage is not a valid attribute","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15","version":"23.0.4.1","exception":{"Exception":"BadFunctionCallException","Message":"plainMessage is not a valid attribute","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/Entity.php","line":158,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/Entity.php","line":73,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":320,"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::"},{"file":"/var/www/next/lib/public/AppFramework/Db/QBMapper.php","line":339,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/announcementcenter/lib/Model/AnnouncementMapper.php","line":113,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/nextcloud/apps/announcementcenter/lib/Manager.php","line":216,"function":"getAnnouncements","class":"OCA\\AnnouncementCenter\\Model\\AnnouncementMapper","type":"->"},{"file":"/var/www/nextcloud/apps/announcementcenter/lib/Dashboard/Widget.php","line":106,"function":"getAnnouncements","class":"OCA\\AnnouncementCenter\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/InitialStateService.php","line":89,"function":"OCA\\AnnouncementCenter\\Dashboard\\{closure}","class":"OCA\\AnnouncementCenter\\Dashboard\\Widget","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/InitialStateService.php","line":140,"function":"invokeLazyStateCallbacks","class":"OC\\InitialStateService","type":"->"},{"file":"/var/www/nextcloud/lib/private/TemplateLayout.php","line":289,"function":"getInitialStates","class":"OC\\InitialStateService","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":182,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":331,"function":"printPage","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/index.php","line":74,"function":"printExceptionErrorPage","class":"OC_Template","type":"::"}],"File":"/var/www/nextcloud/lib/public/AppFramework/Db/Entity.php","Line":129,"CustomMessage":"--"}}
```

**Comment by kesselb** [comment] 2022-05-21 10:01
Duplicate of https://github.com/nextcloud/announcementcenter/issues/471

**Closed by kesselb** 2022-05-21 10:01 UTC
Labels: bug, 0. Needs triage
