### ISSUE TITLE
Share Link Option is unavailable in Web-App of NC 16.0.3

### ISSUE THREAD

**Issue by simon-gaugler** [nextcloud/server#16678] opened 2019-08-07 12:28 UTC
### Steps to reproduce
In the Web-App of v16.0.3 (Docker), if i click on the share-icon of a file or folder, i can see the option to share a link - but there are no options to it. i can neither click it, nor do i have an options menu. It's impossible to create/delete links.

### Expected behaviour
Share link is clickable or gives an options menu

### Actual behaviour
Nothing happens

## Server configuration detail

**Operating system:** Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.4.6

**PHP version:** 

7.3.8
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** pulled new docker image

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - drawio: 0.9.3
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_downloadactivity: 1.5.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.2
 - metadata: 0.9.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.1
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - occweb: 0.0.4
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.0
 - text: 1.0.1
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc.smagcloud.de",
        "smagcloud.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "overwrite.cli.url": "http:\/\/nc.smagcloud.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "occweb"
    ],
    "updater.release.channel": "stable",
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.99

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

POST https://***cloud.de/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json 403
</details>

**Comment by simon-gaugler** [comment] 2019-08-07 12:46
Just been playing around a bit - and it actually seems to be the related to the adblocker of the browser - i'm using operas built in adblocker, but if i disable it for the site, the plus icon and options menu is shown again!
Is there still a way to get around this since most users will actually have their blockers activated normally?

**Comment by ChristophWurst** [comment] 2019-08-07 13:09
Could you check if this is reproducible with any other of your browsers?

**Comment by simon-gaugler** [comment] 2019-08-07 13:23
Hi,

Well i checked it with the major ones:
Google Chrome and uBlock: Works as intended
Firefox with uBlock and ABP: Works!
Microsoft Edge and uBlock: Works!

But Opera's integrated one: It's gone!

Well, it doesn't seem as dramatic then - i'll keep my adblocker off for my cloud then - but it is weird then. Is there something you could do about that regarding opera?

**Comment by ChristophWurst** [comment] 2019-08-07 13:35
Yep, this is very unfortunate. I do not think we can do anything about that.

What *might* help if you could find out if the ad blocker reacts on a certain keyword or similar, then we could rephrase or restructure. But in general this is very hard to fix. I'd consider this a bug in their ad blocker.

**Comment by simon-gaugler** [comment] 2019-08-07 13:53
I understand. Alright, i'll see if i'm able to find sth out once i've got the time!
Thanks so far!

**Comment by skjnldsv** [comment] 2019-08-07 14:46
Hey, please try disabling ad blockers or the dark reader extension if you have this and report back if it changed something :)

**Comment by ChristophWurst** [comment] 2019-08-07 15:27
Turns out to be a duplicate of https://github.com/nextcloud/server/issues/16337. Please see https://github.com/nextcloud/server/issues/16337#issuecomment-513815845

**Closed by ChristophWurst** 2019-08-07 15:27 UTC
Labels: 0. Needs triage, bug, needs info
