### ISSUE TITLE
Nextcloud 29 and 30 : Allow app search in the app store even when in "Discover" section

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#47029] opened 2024-08-05 09:49 UTC
Everything is in the title. Go to the store and click on the search magnifier and search for an app. Nothing happens, unless, for example, you click on "Your apps". "Discover" is an interesting new feature, but in many cases, an administrator has a precise idea of the app he or she is looking for (with a view to installing, uninstalling or even updating it), and this prior obligation to click on "Your apps" breaks the fluidity of the user experience. We need to be able to search for an app as soon as we arrive in the store, even if we're in "Discover".

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jerome-Herbinet** [comment] 2024-08-05 09:49
@nextcloud/designers

**Comment by joshtrichards** [comment] 2024-08-05 12:53
Duplicate of #45558

**Closed by joshtrichards** 2024-08-05 12:53 UTC
Labels: enhancement, design, 0. Needs triage, feature: apps management, feature: search, 29-feedback, 30-feedback
