### ISSUE TITLE
WebDAV locks

### ISSUE THREAD

**Issue by AndreasSchantl** [nextcloud/server#12442] opened 2018-11-14 02:47 UTC
Related to #9969

Feature Request: Ability to activate WebDAV locking (deactivated by default) via a config file. 

Reason: Even though the locking mechanism is not the greatest, it would definitely be a huge enhancement for business clients and should definitely be re-added as an optional feature. 

Question to the devs/community: Is it possible to add this functinoality with an extension?

**Comment by BUG-reporter** [comment] 2019-01-15 01:37
It would be great.

**Comment by HAVP** [comment] 2019-03-04 22:32
I also need that feature.

**Comment by skynick11** [comment] 2019-09-22 12:40
OwnCloud released WebDAV locks in v. 10.1.0 - 2019-02-06

Nextcloud's #1308 shows both the lack of progress and the real desire to make this feature, and is marked as "This conversation has been locked as too heated and limited to collaborators."

Maybe someone knows if at least something will be done in the foreseeable future? ..

**Comment by skjnldsv** [comment] 2019-12-09 08:22
So this one is a duplicate of https://github.com/nextcloud/server/issues/1308

> Nextcloud's #1308 shows both the lack of progress and the real desire to make this feature

Definitely! It's not in our priorities for now!
This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Closed by skjnldsv** 2019-12-09 08:22 UTC
Labels: 1. to develop, enhancement, feature: dav

**Comment by MayeulC** [comment] 2020-08-17 14:17
Wow unfortunately issues are locked everywhere. I am going to use this one to write a pointer I wanted to put on https://github.com/owncloud/core/issues/9176:
As indicated in  https://github.com/nextcloud/server/issues/1308, there is now a [Nextcloud file lock app](https://apps.nextcloud.com/apps/files_lock) that seems to work fine for this purpose.

Thank you for leaving this issue open to comments. Github mention will likely get trough on these issues.

**Comment by nobe80** [comment] 2021-01-19 12:31
Hi!

the file lock app is not a solution for user that only work with WebDAV network shares, especially in Windows. They dont work with the nextcloud webinterface, to login every time to set a lock on every file they want to modify and unlock it again is absolutely not practicable!
So we need the same behavior like on SMB file shares where we get a message if a Microsoft word or excel file is already open by another user. 
I know that the WebDAV Protocol supports this so would it be possible to implement or activate this?

Thanky you
