### ISSUE TITLE
Settings Menu does not stretch the background

### ISSUE THREAD

**Issue by daniel-wtd** [nextcloud/server#11843] opened 2018-10-15 10:27 UTC
### Steps to reproduce
In combination with extensions/apps which are using the Seetings Menu, you can reproduce the below steps:

- Install a fitting app (example: External Sites)
- Setup some external sites to be displayed in the settings menu

### Expected behaviour
- with more entries in the settings menu, the background should stretch properly

### Actual behaviour
- with more entries in the settings menu, the background is not stretched and you will see text below the frame

## Server configuration detail

**Operating system:** Linux 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64

**Webserver:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.0.32 (apache2handler)

**Database:** mysql 5.5.60

**PHP version:** 

7.0.32
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, json, exif, mcrypt, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 14.0.3 - 14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - announcementcenter: 3.3.1
 - audioplayer: 2.4.1
 - bookmarks: 0.13.1
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.2
 - camerarawpreviews: 0.6.0
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - data_request: 1.1.0
 - dav: 1.6.0
 - deck: 0.4.1
 - drawio: 0.9.1
 - federatedfilesharing: 1.4.0
 - files: 1.9.0
 - files_antivirus: 1.3.2
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - groupfolders: 1.3.3
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.10.0
 - news: 13.0.2
 - nextcloud_announcements: 1.3.0
 - notes: 2.4.2
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - quota_warning: 1.3.0
 - socialsharing_diaspora: 1.0.3
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - socialsharing_googleplus: 1.0.3
 - socialsharing_twitter: 1.0.3
 - spreed: 4.0.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - telephoneprovider: 1.0.1
 - theming: 1.5.0
 - theming_customcss: 1.1.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - encryption
 - external
 - federation
 - files_external
 - serverinfo
 - sharebymail
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc.while-true-do.org",
        "nc01.while-true-do.org",
        "localhost"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nc.while-true-do.org",
    "dbtype": "mysql",
    "version": "14.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "maintenance": false,
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mysql.utf8mb4": true,
    "theme": "",
    "loglevel": 2,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Comment by daniel-wtd** [comment] 2018-11-01 10:13
Same Issue:
- https://github.com/nextcloud/external/issues/122
- https://github.com/nextcloud/server/issues/11791

**Comment by skjnldsv** [comment] 2018-11-01 10:53
Then duplicate of #11791

**Closed by skjnldsv** 2018-11-01 10:53 UTC
Labels: bug, papercut, regression
