### ISSUE TITLE
Individual (user defined) Landing Page at Login

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#336] opened 2016-07-07 11:31 UTC
Up to now, there is only the possibility of defining a unique landing page at login for **ALL** users.

In a large corporate environment, users in different departments wish to have a more individual approach. E.g. sales people like to have the calendar app, others might like to have the contact app and others like to have some other app in front at login.

regards, hiatm4450

**Comment by MorrisJobke** [comment] 2016-07-07 12:05
Duplicate of #128

**Closed by MorrisJobke** 2016-07-07 12:05 UTC

**Comment by hitam4450** [comment] 2016-07-07 12:30
Ok & Thanks for your advice!

regads, hitam4450
