### ISSUE TITLE
Selecting range of files in search results also selects hidden files

### ISSUE THREAD

**Issue by willvousden** [nextcloud/server#6162] opened 2017-08-17 08:52 UTC
### Steps to reproduce
1. Search for a pattern that produces results that wouldn't be next to each other in the unfiltered list of files.  For example, in a folder with `a.txt`, `b.jpb`, `c.txt`, and `d.txt`, search for `.txt`.
2. Select all of the files in the results using the tickbox above.  Alternatively, select the top-most file and then shift-click the bottom one to select all of them.

### Expected behaviour
The summary at the top should tell me that the correct number of files have been selected (in the example above, there would be 3).  Doing any sort of operation on the selection should affect only on the files that appeared in the search results.

### Actual behaviour
In fact, **all** of the files in the folder have been selected; even those that haven't shown up in the search results.

As a result, if I try to delete the selected search results, I lose **everything** in the folder!

![nc-bug-2](https://user-images.githubusercontent.com/152388/29404003-d057667e-8331-11e7-9916-b25361971446.png)

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7

**Nextcloud version:** 12.01

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11

**Where did you install Nextcloud from:** From source.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "occ3df1jfn7e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "(removed)"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "(removed)",
        "dbtype": "mysql",
        "version": "12.0.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "(removed)",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```


```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Lots of entries like this in the JavaScript log.  Seemingly unrelated to the actual search results.

/index.php/core/preview.png?file=%2FDocuments%2Fmisc%2Fcoffee%2Fpaper-1.pdf&x=32&y=32&forceIcon=0:1 GET https://(removed)/index.php/core/preview.png?file=%2FDocuments%2Fmisc%2Fcoffee%2Fpaper-1.pdf&x=32&y=32&forceIcon=0 404 (Not Found)
Image (async)
lazyLoadPreview @ merged-index.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:5813
renderFileResult @ merged-index.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:7191
(anonymous) @ search.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:200
each @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:2
addResults @ search.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:185
showResults @ search.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:181
(anonymous) @ search.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:138
j @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:2
fireWith @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:2
x @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:4
(anonymous) @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:4
XMLHttpRequest.send (async)
send @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:4
ajax @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:4
n.(anonymous function) @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:4
getJSON @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:4
(anonymous) @ search.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:135
setTimeout (async)
search @ search.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:123
(anonymous) @ search.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:327
dispatch @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:3
r.handle @ core.js?v=96e3bdabf3b6437eedce819310ea8bc5-12:3
```
</details>

**Comment by MorrisJobke** [comment] 2017-11-24 13:27
Duplicate of #2075

**Closed by MorrisJobke** 2017-11-24 13:27 UTC
Labels: bug, feature: files, Hacktoberfest, papercut, starter issue
