### ISSUE TITLE
Upgrading to 15.0.7 failed. occ is missing from in the nextcloud folder

### ISSUE THREAD

**Issue by chortya** [nextcloud/server#15133] opened 2019-04-16 14:14 UTC
I have tried to upgrade the Nextcloud from 15.0.16 to 15.0.17 using webinterface and it seemed to work but then it stuck showing "Update in process". Occ is missing in the nextcloud folder. Upgrading using php updater.phar shows also that upgrade succeeds but then an error with occ is also shown. Nextcloud folder looks very empty... Where do I find the backup? My files are stored on separate nfs share.

I am ussing VmWare appliance base on Ubuntu.

**Comment by violoncelloCH** [comment] 2019-04-18 22:57
possibly related to #14976

**Comment by skjnldsv** [comment] 2019-06-17 09:28
Yes, duplicate of #14976

**Closed by skjnldsv** 2019-06-17 09:28 UTC
Labels: feature: install and update
