### ISSUE TITLE
Nextcloud 16.0.6 listed as available update after upgrading to 17.0.1

### ISSUE THREAD

**Issue by jwstolk** [nextcloud/server#18099] opened 2019-11-25 08:48 UTC
### Steps to reproduce
1. upgrade from NextCloud 16.x to 17.0.1 (don't remember the exact 16.x version) (Dutch)
2. login as admin
3. go to administratie -> overview
4. (rebooting the server does not resolve this)

### Expected behaviour
not see any available new upgrades

### Actual behaviour
It shows: current version: "17.0.1" there is a new update available: "Nextcloud 16.0.6"
all apps have an update for this version
(update channel: stable)

### Server configuration
Ubuntu 18.04.3 LTS
PHP 7.2.24-0ubuntu0.18.04.1
nginx 1.14.0 (Ubuntu)

Maybe this is coused by skipping "17.0.0"? I expect issues with future updates.
Please let me know if more information is needed.

**Comment by jwstolk** [comment] 2019-11-25 08:57
UPDATE: I switched language for the admin account from Dutch to English, and the overview now correctly shows: "Your version is up to date"
Switching the language back, or lohging in again does not reproduce the error, so it looks like a temporal problem. I bit strange since I did a hardware reboot of the server after the upgrade.

If someone knows how the overview page could show outdated updates information they may be something to look into, else please close this report.

**Comment by b3** [comment] 2019-11-25 15:49
I got almost the same trouble but **before** upgrading to 17.0.1.

I was in 16.0.5.
The 16.0.6 was said to be the last stable available version.
I open the updater and launch the upgrade which update to ... 17.0.1.

**Comment by kesselb** [comment] 2019-11-25 19:21
https://help.nextcloud.com/t/updatechecker-permanently-breaks-the-overview-panel-after-upgrade/63683 sounds like. We probably need some job to clear the updater cache.

**Comment by szaimen** [comment] 2021-05-27 11:44
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 11:44 UTC
Labels: 0. Needs triage, bug
