### ISSUE TITLE
[Bug]: Update to 27.1.1 screwed file move/copy dialog

### ISSUE THREAD

**Issue by jacotec** [nextcloud/server#40580] opened 2023-09-22 10:34 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating from 27.1.0 to 27.1.1 the file move/copy dialog is completely messed. This happens on 3 instances. Dialog looked fine in 27.1.0.

![image](https://github.com/nextcloud/server/assets/3321655/4609724f-4ad9-42f0-9672-9155e2f82ecb)

### Steps to reproduce

1. Select to move / copy a file and see the mess

### Expected behavior

The dialog should be fine as seen in 27.1.0

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "x.x.x.x",
            "xxx.de"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_FORWARDED_FOR"
        ],
        "overwrite.cli.url": "https:\/\/xxx.de",
        "overwritehost": "xxx.de",
        "overwriteprotocol": "https",
        "allow_local_remote_servers": true,
        "htaccess.RewriteBase": "\/",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.1.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "enable_avatars": true,
        "filesystem_check_changes": 1,
        "theme": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "defaultapp": "files",
        "skeletondirectory": "\/var\/www\/skeleton",
        "share_folder": "\/Shared",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": 2592000,
        "session_lifetime": 604800,
        "session_keepalive": true,
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "30, 60",
        "versions_retention_obligation": "auto, 365",
        "check_for_working_webdav": true,
        "simpleSignUpLink.shown": false,
        "auth.webauthn.enabled": false,
        "music.lastfm_api_key": "2897d80221740bce55bd257a138705d1",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0
        },
        "logtimezone": "Europe\/Berlin",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MOV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\Image",
            "OC\\Preview\\PPT",
            "OC\\Preview\\PPTX"
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 51,
        "app_install_overwrite": [
            "files_external_dropbox",
            "bookmarks_fulltextsearch",
            "files_inotify",
            "files_fulltextsearch_tesseract",
            "previewgenerator",
            "quickaccesssorting",
            "bbb",
            "fulltextsearch",
            "fulltextsearch_elasticsearch",
            "files_fulltextsearch",
            "socialsharing_email",
            "extract",
            "drawio",
            "quicknotes",
            "video_converter",
            "oidc_login",
            "facerecognition",
            "files_linkeditor",
            "metadata",
            "cfg_share_links",
            "ncdownloader"
        ],
        "updater.release.channel": "stable",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "oidc_login_provider_url": "https:\/\/xxx.de\/realms\/cloud",
        "oidc_login_client_id": "xxx",
        "oidc_login_client_secret": "wAHp73Wj5veVPHOGxwFBT17ek8EE2VhS",
        "oidc_login_end_session_redirect": true,
        "oidc_login_logout_url": "https:\/\/xxx.de\/apps\/oidc_login\/oidc",
        "oidc_login_auto_redirect": false,
        "oidc_login_hide_password_form": false,
        "oidc_login_attributes": {
            "id": "preferred_username",
            "name": "name",
            "mail": "email",
            "quota": "nextcloudquota",
            "groups": "groups"
        },
        "oidc_login_scope": "openid profile",
        "oidc_login_disable_registration": false,
        "oidc_login_redir_fallback": true,
        "oidc_login_password_authentication": true,
        "oidc_login_button_text": "Mit xxx anmelden",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/lib\/..\/exiftool-bin\/exiftool-amd64-glibc",
        "memories.gis_type": 1,
        "enabledFaceRecognitionMimetype": [
            "image\/jpeg",
            "image\/png",
            "image\/heic",
            "image\/tiff",
            "image\/webp"
        ],
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/exiftool-bin\/go-vod-amd64",
        "memories.vod.disable": false,
        "memories.vod.tempdir": "\/tmp\/memories_cache"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - appointments: 1.15.3
  - bbb: 2.5.0
  - bookmarks: 13.1.1
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.0
  - camerarawpreviews: 0.8.2
  - cfg_share_links: 4.1.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.1
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - drawio: 2.1.2
  - extract: 1.3.6
  - facerecognition: 0.9.31
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.1
  - files_automatedtagging: 1.17.0
  - files_external: 1.19.0
  - files_fulltextsearch: 27.0.1
  - files_fulltextsearch_tesseract: 27.0.0
  - files_inotify: 0.1.15
  - files_linkeditor: 1.1.16
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.3.1
  - fulltextsearch: 27.0.1
  - fulltextsearch_elasticsearch: 27.0.2
  - groupfolders: 15.3.1
  - guests: 2.5.0
  - integration_openai: 1.0.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.1.1
  - memories: 5.4.1
  - metadata: 0.19.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.1
  - oidc_login: 2.6.0
  - photos: 2.3.0
  - polls: 5.3.2
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - qownnotesapi: 23.6.0
  - quickaccesssorting: 3.0.0
  - quicknotes: 0.8.10
  - quota_warning: 1.17.0
  - recommendations: 1.6.0
  - richdocuments: 8.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.10.3
  - socialsharing_email: 2.6.0
  - spreed: 17.1.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - translate: 1.1.6
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - video_converter: 1.0.6
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflow_pdf_converter: 1.12.0
  - workflowengine: 2.9.0
Disabled:
  - audioplayer: 3.4.0 (installed 3.4.0)
  - encryption: 2.15.0
  - music: 1.8.4 (installed 1.8.4)
  - ncdownloader: 1.0.20 (installed 1.0.20)
  - news: 23.0.0 (installed 23.0.0)
  - password_policy: 1.17.0 (installed 1.15.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - related_resources: 1.2.0 (installed 1.1.0-alpha1)
  - suspicious_login: 5.0.0
  - talk_matterbridge: 1.26.0-0 (installed 1.26.0-0)
  - workflow_script: 1.12.0 (installed 1.12.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment] 2023-09-22 10:42
cc @susnux

**Comment by brievenbusalex** [comment] 2023-09-23 10:57
Same issue here since update to 27.1.1 from 27.1.0. See below the browser console errors when opening the move/copy dialog.

![image](https://github.com/nextcloud/server/assets/10253686/ff527b7a-23a1-47b8-bf82-5a99fba36872)

When clicking on folder in the Files-App there is also always as <404 Not Found> error in the browser console each time I change to another folder. I don't know if that is related and if that is new behaviour since 27.1.1.

![image](https://github.com/nextcloud/server/assets/10253686/63279646-d17d-4570-9ed8-d66201bb7e17)

**Comment by susnux** [comment] 2023-09-23 15:30
The 404 is front the text app (rich workspaces).

But I really do not know why this breaks on 27.1.1 as there were no changes to the filepicker. Nevertheless I tested https://github.com/nextcloud/server/pull/40557 and it works there. So will be fixed with 27.1.2

**Closed** 2023-09-24 10:13 UTC
Labels: bug, 0. Needs triage, 27-feedback

**Comment by Mer0me** [comment] 2023-10-09 09:09
File picker interface is now good on 27.1.2, but the (french but maye others language ?) translation is missing. I cannot see the missing translation on transifex. 
"Copy" and "Move" buttons, and the popup title are in english.
I have an old instance on 25.0.5 where these elements are well translated (on the old file picker). So it's some sort of regression with the new file picker.

**Comment by jacotec** [comment] 2023-10-09 09:45
Same here for German.

@Mer0me I'd open a new issue for that

**Comment by susnux** [comment] 2023-10-09 23:19
You can translate the file picker as part of the dialogs library:
https://app.transifex.com/nextcloud/nextcloud-dialogs-library/dashboard/

**Comment by Mer0me** [comment] 2023-10-10 06:13
> You can translate the file picker as part of the dialogs library: https://app.transifex.com/nextcloud/nextcloud-dialogs-library/dashboard/

Ok, but it is already translated on transifex. Maybe related to https://github.com/nextcloud/server/issues/40801 ?
