### ISSUE TITLE
 Error when downloading files from android device via WEB

### ISSUE THREAD

**Issue by thfree** [nextcloud/server#1587] opened 2016-09-30 09:11 UTC
### Steps to reproduce
1. Create share link 
2. Android 5.1.1 + Chrome 54.0
3. Try to download something inside

### Expected behaviour
It should happen downloads, file / archive

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/13134495/18984559/0290dfe0-86fc-11e6-8e0e-e83657665204.png)

### Server configuration
**Operating system**:
FreeBSD 10.3-RELEASE-p3 amd64

**Web server:**
Apache/2.4.23

**Database:**
 PostgreSQL 9.4.9

**PHP version:**
7.0.11

**Nextcloud version:**
Nextcloud 10.0.1 (production)

**Updated from an older Nextcloud/ownCloud or fresh install:**
The old installation since 7 OC

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - activity: 2.3.2
  - announcementcenter: 2.0.0
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - encryption: 1.3.1
  - external: 1.2
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - logreader: 1.1.5
  - news: 9.0.4
  - notes: 2.0.2
  - notifications: 0.3.0
  - ocsms: 1.9.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - qownnotesapi: 16.09.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - files_automatedtagging
  - files_retention
  - firstrunwizard
  - user_external
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***.***.***',
  'trusted_domains' => 
  array (
    0 => 'cloud.thfree.ru',
  ),
  'datadirectory' => '***',
  'dbtype' => 'pgsql',
  'version' => '9.1.1.5',
  'dbname' => '***',
  'dbhost' => '***',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpport' => '25',
  'mail_smtphost' => '***',
  'mail_domain' => 'thfree.ru',
  'mail_from_address' => 'no-reply',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => false,
  'skeletondirectory' => '',
  'trashbin_retention_obligation' => '30, auto',
  'loglevel' => 1,
  'logdateformat' => 'd F Y H:i:s',
  'logtimezone' => 'UTC',
  'log_rotate_size' => false,
  'enable_avatars' => true,
  'enable_previews' => true,
  'appstoreenabled' => true,
  'appstore.experimental.enabled' => true,
  'filelocking.enabled' => 'true',
  'filesystem_check_changes' => 1,
  'htaccess.RewriteBase' => '/',
  'customclient_android' => 'https://f-droid.org/repository/browse/?fdid=com.nextcloud.client',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => 
  array (
    'host' => '***',
    'port' => 6379,
    'password' => '***',
    'dbindex' => 1,
  ),
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'maintenance' => false,
  'singleuser' => false,
);

```
</details>

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:**
LDAP

### Client configuration
**Browser:**
Chrome 54.0

**Operating system:**
Android 5.1.1

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /usr/home/clients/thfree-ru/cloud/lib/private/Files/Filesystem.php:773 Stack trace: #0 /usr/home/clients/thfree-ru/cloud/lib/private/Files/View.php(2034): OC\Files\Filesystem::normalizePath('/admin/files/Fi...') #1 /usr/home/clients/thfree-ru/cloud/lib/private/Files/View.php(1152): OC\Files\View->unlockFile('/Files/GUAP/_Te...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /usr/home/clients/thfree-ru/cloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /usr/home/clients/thfree-ru/cloud/lib/private/Files/Filesystem.php#773
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

```
</details>

**Comment by nickvergessen** [comment] 2016-09-30 09:22
@MorrisJobke didn't we backport this?

**Comment by LukasReschke** [comment] 2016-09-30 09:29
Dupe of https://github.com/nextcloud/server/pull/1456

**Closed by LukasReschke** 2016-09-30 09:29 UTC
Labels: bug, feature: files, needs info
