### ISSUE TITLE
Shared folder icons and text is showed inconsistently

### ISSUE THREAD

**Issue by Germs2004** [nextcloud/server#10308] opened 2018-07-20 02:51 UTC
The user who shares a folder structure only sees the "Shared" icon and text on the root folder that they shared, but all the other users see the icon and text on every child folder in the shared tree.

1) Log on as User1.
2) Create Folder1 and, inside that, Folder2.
3) Share Folder1 with User2.
4) Notice that Folder1 says "Shared" next to it and has the shared icon, but Folder2 does not.
5) Log on as User2.
5) Notice that Folder1 and Folder2 both have the shared icon and say "Shared" next to them.

Expected behavior:
User1 and User2 should see the same.  Either both should see Folder1 and Folder2 with the "Shared" text, or both should only see Folder1 with the "Shared" text.  I think I prefer that everyone only see the Shared icon and text on the root folder that is shared, not all of its subfolders.

Nextcloud 13.0.4

**Comment by MorrisJobke** [comment] 2018-07-24 12:08
Duplicate of #4281

**Closed by MorrisJobke** 2018-07-24 12:08 UTC
Labels: bug, feature: sharing
