### ISSUE TITLE
Add option to install unstable apps from Nextcloud store

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/server#10487] opened 2018-08-01 13:02 UTC
### Steps to reproduce
1. Try to install nightly unstable app from Nextcloud store through Nextcloud web interface.

### Expected behaviour
Install unstable nightly app from Nextcloud app store. There is an option to install Nextcloud from a different channel (stable, daily beta, production) but no corresponding setting for apps.

### Actual behaviour
No possibility to install nightly app through app store web UI inside Nextcloud. Package has to be downloaded manually, copied to server, extracted to apps folder and then activated.

**Comment by tacruc** [comment] 2020-04-23 08:23
I think this could improve the update to beta versions. 
Usally if you update to an beta version of the server most/all apps gets disabled, because there final NC 19 version is not published yet.

**Comment by nazar-pc** [comment] 2021-02-11 00:02
Duplicate of older #7417

**Comment by szaimen** [comment] 2021-02-11 00:28
This is already possible via occ:
https://github.com/nextcloud/server/pull/20741

**Comment by nazar-pc** [comment] 2021-02-11 00:36
It is about updating, installation doesn't seem to support that flag, so I can't install spreed on 21RC1 currently

**Comment by szaimen** [comment] 2021-02-11 08:05
The flag was changed to --allow-unstable. Did you try that?

**Comment by nazar-pc** [comment] 2021-02-11 08:18
Yes, it only affects updates, not installation.
And I'm not feeling lucky to install incompatible version first and then update it to unstable :slightly_smiling_face:

**Comment by szaimen** [comment] 2021-05-12 13:30
This is implemented with https://github.com/nextcloud/server/pull/26252

**Closed by szaimen** 2021-05-12 13:30 UTC
Labels: 1. to develop, enhancement
