### ISSUE TITLE
`php occ maintenance:install`: pass passwords with stdin

### ISSUE THREAD

**Issue by WilliamDEdwards** [nextcloud/server#45742] opened 2024-06-09 20:44 UTC
Using `php occ maintenance:install`, NextCloud can be installed non-interactively. 

This command takes the `--database-pass` and `--admin-pass` parameter.

It should be possible to fill these from stdin, to prevent leaking them by passing them on CLI.

**Comment by joshtrichards** [comment] 2024-06-10 00:41
Duplicate of #6185

**Closed by joshtrichards** 2024-06-10 00:41 UTC
Labels: enhancement, 0. Needs triage
