### ISSUE TITLE
Video streaming results in multiple "file downloaded" activity records

### ISSUE THREAD

**Issue by fyah** [nextcloud/server#10726] opened 2018-08-16 22:24 UTC
### Steps to reproduce
1. share a video using public link
2. open the link and play the video from the browser
3. you will then see in the activity pannel of owncloud many file was downloaded by public link items

### Expected behaviour
There shall be only one "file was watched" by public link item

### Actual behaviour
There are multiple "fie was downloaded" by public link items

### Server configuration

**Operating system**: Synology DSM 6.2

**Web server:** apache 2.4

**Database:** maria 10

**PHP version:** 7.0.30

**Nextcloud version:** (see Nextcloud admin page) 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated 

**Where did you install Nextcloud from:** official site

**Comment by iGamerHD** [comment] 2019-05-04 12:25
Still a big problem in Nextcloud 15.0.7.
Especially when you skip forward or go back a bit, it always creates a new activity and really spams the activity tab.
It would be really helpful to
- differentiate between video streaming  and video download (although it may look mostly the same for the backend)
- group video streaming activities by IP / Session so that a click on the timeline doesn't create a new activity

**Comment by wivaku** [comment] 2019-09-05 07:34
Still a problem in 16.0.4. I have hundreds of activity notifications after sharing a video with 4 people.

**Comment by szaimen** [comment] 2021-06-07 13:47
I can reproduce this on NC21.0.2

---

@nickvergessen @kesselb any idea why this happens and how to fix it?

**Comment by nickvergessen** [comment] 2021-06-07 14:59
Duplicate of https://github.com/nextcloud/files_downloadactivity/issues/47

**Closed by nickvergessen** 2021-06-07 14:59 UTC
Labels: 0. Needs triage, bug, feature: activity and notification, feature: sharing, needs info
