### ISSUE TITLE
Update to NC22 fails "Exception: Database error when running migration latest for app core"

### ISSUE THREAD

**Issue by supermar1010** [nextcloud/server#28745] opened 2021-09-07 10:01 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have nextcloud 21.0.2.1
2. Update docker container to 22.1.1.2
3. Update fails

### Expected behaviour
The update shoudl work

### Actual behaviour
Update fails with this error message:

```
Initializing nextcloud 22.1.1.2 ...
Upgrading nextcloud from 21.0.2.1 ...
Initializing finished
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Exception: Database error when running migration latest for app core
Update failed
Maintenance mode is kept active
Resetting log level
```

When doing the same over the browser I get a similiar error message:

```Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Repair MySQL collation

All tables already have the correct collation -> nothing to do

Repair SQLite autoincrement

Copy data from accounts table when migrating from ownCloud

Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Exception: Database error when running migration latest for app core

```

### Server configuration

**Operating system:** nextcloud docker image

**Web server:** nextcloud docker image

**Database:** mariadb

**PHP version:** nextcloud docker image

**Nextcloud version:** I was on 21.0.2.1 now on 22.1.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** docker

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.supermar10.tk"
        ],
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "bucketName",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "region": "",
                "hostname": "s3.eu-central-003.backblazeb2.com",
                "port": "",
                "use_ssl": true,
                "use_path_style": false
            }
        },
        "loglevel": 2,
        "maintenance": true,
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Arch

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Initializing nextcloud 22.1.1.2 ...
Upgrading nextcloud from 21.0.2.1 ...
Initializing finished
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Exception: Database error when running migration latest for app core
Update failed
Maintenance mode is kept active
Resetting log level
```
</details>

**Comment by szaimen** [comment] 2021-09-07 10:06
Looks like a duplicate of #25436 but not sure without knowing your mariadb version

**Comment by supermar1010** [comment] 2021-09-07 10:13
You're the MVP that was the problem locking my mariadb version to 10.5 did the trick. Thanks a lot!

**Closed** 2021-09-07 10:13 UTC
Labels: bug, needs info, 0. Needs triage
