### ISSUE TITLE
[Bug]: 28.0.3 Drag and drop file feature only uploads one file of all dragged files

### ISSUE THREAD

**Issue by mxmurawski** [nextcloud/server#47632] opened 2024-08-30 10:54 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

as in the tile

### Steps to reproduce

1.enter any directory
2.drag and drop files to be uploaded
3.watch the bug in action

### Expected behavior

all dragged and dropped files should be uploaded instead of only one of them

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2024-08-30 11:05
Upgrade to latest v28.0.9.

**Comment by joshtrichards** [comment] 2024-08-30 15:45
Duplicate of #43074

**Closed by joshtrichards** 2024-08-30 15:45 UTC
Labels: bug, needs info, 0. Needs triage, 28-feedback
