### ISSUE TITLE
DAV Error in Nextcloud 14

### ISSUE THREAD

**Issue by Co0p3r21** [nextcloud/server#10665] opened 2018-08-13 08:31 UTC
Hello, 
I have an Issue with the webdav Service. I can´t use any sync feature and can´t detect my Folders. 
If have done anything wrong, the error Message isn´t very informative.
It worked well on nextcloud 13, so I would say it is a Bug in 14.
Here is my Nextcloud error message: 
`

  | LogicException: This is not supposed to happen/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 345: OCA\DAV\CalDAV\Plugin->getCalendarHomeForPrincipal("principals/groups/admin")/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php - line 98: Sabre\CalDAV\Plugin->Sabre\CalDAV\{closure}("*** sensiti ... *")/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 349: Sabre\DAV\PropFind->handle("{urn:ietf:p ... t", Closure {})Sabre\CalDAV\Plugin->propFind(Sabre\DAV\PropFind {}, OCA\DAV\CalD ... {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ OCA\DAV\Ca ... "], [ Sabre\DAV\ ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1059: Sabre\Event\EventEmitter->emit("propFind", [ Sabre\DAV\ ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 981: Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\DAV\CalD ... {})/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666: Sabre\DAV\Server->getPropertiesIteratorForPath("principals/groups/admin", [ "{urn:ietf ... "], 0)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 359: Sabre\DAV\Server->generateMultiStatus(Generator {}, false)Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:PROPFIND", [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/apps/dav/lib/Server.php - line 293: Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 163: require_once("/var/www/ne ... p")
-- | --

`
And my Debug.txt from the DAV android App [debug.txt](https://github.com/nextcloud/server/files/2282253/debug.txt)

**Comment by MorrisJobke** [comment] 2018-08-31 12:51
cc @georgehrke @rullzer

**Comment by georgehrke** [comment] 2018-08-31 12:52
Duplicate of #10727

**Closed** 2018-08-31 12:52 UTC
Labels: 14-beta-feedback, bug, feature: dav
