### ISSUE TITLE
Missing index on oc_flow_operations

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#20731] opened 2020-04-29 19:45 UTC
I see a lot of 

```sql
SELECT DISTINCT `class`, `entity`, `events` FROM `oc_flow_operations` WHERE `events` <> '[]';
```

In the slow query log.

Should be added.

**Comment by joshtrichards** [comment] 2023-09-15 15:47
Duplicate of #25342

**Closed by joshtrichards** 2023-09-15 15:47 UTC
Labels: enhancement, 1. to develop, feature: workflows, performance 🚀
