### ISSUE TITLE
9.2.5.3/11.1 In the breadcrumb navigation, the directory name is being overridden by the use of "aria-label" attributes. This could cause issues when using voice control programs.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42266] opened 2023-12-14 11:27 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-c6347c127a-v11-n1

9.2.5.3/11.1 In the breadcrumb navigation, the directory name is being overridden by the use of "aria-label" attributes. This could cause issues when using voice control programs.

![image](https://github.com/nextcloud/server/assets/42591237/a459ba87-a756-434f-b76f-5b59e825dc00)

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 14:29
duplicate of https://github.com/nextcloud/server/issues/42265

**Closed by JuliaKirschenheuter** 2023-12-14 14:29 UTC
Labels: accessibility
