### ISSUE TITLE
Empty Group select in Workflow rule

### ISSUE THREAD

**Issue by ClCfe** [nextcloud/server#24912] opened 2020-12-30 15:20 UTC
Hello

If you edit an existing workflow with group rules, and that you have more than 20 groups in database, group selects  are not properly initialized 

https://github.com/nextcloud/server/blob/f9b4084f522f9112f69d672e25e5545302f2341c/apps/workflowengine/src/components/Checks/RequestUserGroup.vue#L73-L75

initialization should be done without `limit=20` parameter here

https://github.com/nextcloud/server/blob/f9b4084f522f9112f69d672e25e5545302f2341c/apps/workflowengine/src/components/Checks/RequestUserGroup.vue#L87

otherwise, some fields are empty instead of dispalying group names (because this.groups contains only 20 entries, and not all the groups possibly involved in the rules)

I think a good way to resolve this is adding a limit parameter to `searchAsync(searchQuery, limit=20)`
if limit is null, no limit parameter should be added to the axios query

```
if (this.groups.length === 0) {
	await this.searchAsync('', null)
}
```

Of course the best way to solve this should be that you pass to the axios query an array of groups IDs already involved in the rules of the edited workflow, but this implies changes on the backend

**Comment by kesselb** [comment] 2020-12-30 17:09
Duplicate of https://github.com/nextcloud/server/issues/24547

**Closed by kesselb** 2020-12-30 17:09 UTC
