### ISSUE TITLE
missing translation in app accessibility

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#15623] opened 2019-05-20 06:27 UTC
tested with NC 16, Accessibility  1.2.0

The first paragraph in ...nextcloud/settings/user/accessibility is not translated:

![accessibility](https://user-images.githubusercontent.com/34692335/58000397-f563e500-7ad8-11e9-9f69-bf0b199ca67c.png)

I did'nt find the strings in Transifex, so I suspect that they are not translatable in the source

**Comment by wiswedel** [comment] 2019-06-12 18:27
related? https://github.com/nextcloud/server/issues/15627

**Comment by kesselb** [comment] 2019-06-12 19:51
Duplicate of #14607

**Closed by kesselb** 2019-06-12 19:51 UTC
Labels: 0. Needs triage, bug
