### ISSUE TITLE
Folders ending in .php will not sync their contents

### ISSUE THREAD

**Issue by figureone** [nextcloud/server#13063] opened 2018-12-13 19:44 UTC
### Steps to reproduce
1. On a client device, create a folder in Nextcloud called `index.php`
2. Inside that folder, create any file or folder (e.g., a folder called `something`)
3. Files in folder will fail to sync.

### Expected behaviour
Files in folder should sync.

### Actual behaviour
Files in folder fail to sync.

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** nginx/1.10.3 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64)

**PHP version:** PHP 7.0.28-0ubuntu0.16.04.1

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.6.1
  - announcementcenter: 3.2.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_external
  - spreed
  - user_external
```
</details>

### Client configuration
**Browser:** Chrome 70.0.3538.110

**Operating system:** MacOS Mojave 10.14.2

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2018/12/13 09:13:29 [error] 1508#1508: *11010974 upstream sent invalid status "0" while reading response header from upstream, client: 172.16.5.10, server: nextcloud.example.edu, request: "MKCOL /remote.php/dav/files/testuser/index.php/something HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "nextcloud.example.edu"
2018/12/13 09:13:29 [error] 1508#1508: *11010978 upstream sent invalid status "0" while reading response header from upstream, client: 172.16.5.10, server: nextcloud.example.edu, request: "PUT /remote.php/dav/files/testuser/index.php/something HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "nextcloud.example.edu"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"lGQS33kKPFwtLrOgI10L","level":3,"time":"2018-12-13T19:14:20+00:00","remoteAddr":"172.17.5.159","user":"testuser","app":"remote","method":"MKCOL","url":"\/remote.php\/dav\/files\/testuser\/index.php\/something","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/remote.php\\\/dav\\\/files\\\/testuser\\\/index.php\\\/something) cannot be processed by the script '\\\/something')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php(755): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(126): OC\\\\AppFramework\\\\Http\\\\Request->getPathInfo()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":733}","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.3.3 (build 84) (Nextcloud)","version":"13.0.2.1"}
{"reqId":"lGQS33kKPFwtLrOgI10L","level":3,"time":"2018-12-13T19:14:20+00:00","remoteAddr":"172.16.5.10","user":"testuser","app":"no app in context","method":"MKCOL","url":"\/remote.php\/dav\/files\/testuser\/index.php\/something","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/URLGenerator.php(80): OC\\\\Route\\\\Router->generate('theming.Theming...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(190): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/public\\\/Defaults.php(187): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/core\\\/templates\\\/layout.guest.php(34): OCP\\\\Defaults->getLogo()\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/var\\\/www\\\/html\\\/n...')\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/var\\\/www\\\/html\\\/n...', NULL)\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(204): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC_Template->fetchPage()\\n#9 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#10 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/template.php(351): OC\\\\Template\\\\Base->printPage()\\n#11 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(85): OC_Template::printExceptionErrorPage(Object(Exception))\\n#12 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(167): handleException(Object(Exception))\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.3.3 (build 84) (Nextcloud)","version":"13.0.2.1"}
```
</details>

#### Nextcloud client log
<details>
<summary>Nextcloud client log (__Not Synced__ tab)</summary>

```
The item is not synced because of previous errors. Error transferring https://nextcloud.example.edu/remote.php/dav/files/testuser/index.php/something - server replied: Bad Gateway
```
</details>

**Comment by zoc** [comment] 2019-01-06 16:44
I have actually the same issue trying to sync .php **files**.

Using Nextcloud 15.0.0 with nginx.

**Comment by skjnldsv** [comment] 2019-06-04 08:51
You also cannot upload a file to the folder.
The PUT request returns the homepage

**Comment by szaimen** [comment] 2021-05-20 13:49
> You also cannot upload a file to the folder.
> The PUT request returns the homepage

As I cannot reproduce this issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-20 13:49 UTC
Labels: 1. to develop, bug, client: 💻 desktop, feature: filesystem
