### ISSUE TITLE
Ability to search on shared link page

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#7129] opened 2017-11-10 11:09 UTC
### Steps to reproduce
1. Receive a shared link to a folder with lots of files & folders
2. Try to find what you are looking for
3. See if there is a search function

### Expected behaviour
A search function is in the top right, like there is in other parts of Nextcloud.

### Actual behaviour
There isn’t.

**Comment by MorrisJobke** [comment] 2017-12-18 19:17
Duplicate of #1794

**Closed by MorrisJobke** 2017-12-18 19:17 UTC
Labels: 1. to develop, design, enhancement, feature: sharing
