### ISSUE TITLE
Disabling app store in config.php does not work as expected

### ISSUE THREAD

**Issue by kaosdrachen** [nextcloud/server#3581] opened 2017-02-22 14:30 UTC
### Steps to reproduce
1. In config.php, set `appstoreenabled` to `false`, but have valid values in `apps_paths`
2. In admin panel, open the app store
3. Attempt to install an app via the store

### Expected behaviour
Three possibles:
 1. The app store should not even be available (as it was explicitly not enabled in config.php)
 2. The app store shows up, but all 'enable app' buttons greyed out (because the app store is not enabled)
 3. Failing 1 and 2, clicking the 'enable' button should install the app.

### Actual behaviour
The app store shows up and you are allowed to click 'enable app' buttons. However, the installation attempt fails, with the slightly vague log message as I described in issue #3577 . 

What turned out to be the case was that the config parser saw that 'appstoreenabled' was set to false, so didn't bother to parse the `apps_paths` part of the config, and as a result the getInstallPath() function returns an empty string during the install process, which causes Installer.php to attempt to install the app to the filesystem root (which *should* fail unless you've got a spectacularly bad setup)

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Apache 2.4

**Database:** PostgreSQL 9.4

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated/migrated from Owncloud.

**Where did you install Nextcloud from:** Deb repository at  https://repo.morph027.de/nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - user_external
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oca50314be0c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mijndata.systemeccloud.nl",
            "nctest.systemec.nl"
        ],
        "datadirectory": "\/cloud",
        "overwrite.cli.url": "http:\/\/nctest.systemec.nl",
        "dbtype": "pgsql",
        "version": "11.0.1.2",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "dbname": "nextcloud",
        "dbhost": "feynman.systemec.private",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "support",
        "mail_domain": "systemec.nl",
        "mail_smtphost": "smtp.systemec.nl",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "token_auth_enforced": true,
        "ldapIgnoreNamingRules": false,
        "log_type": "file",
        "logfile": "\/cloud\/nextcloud.log",
        "loglevel": "0",
        "theme": "",
        "maintenance": false,
        "debug": true,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```
</details>

**Are you using external storage, if yes which one:** LDAP

**Are you using encryption:** No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+----------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                    |
+-------------------------------+----------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                  |
| hasPagedResultSupport         |                                                                                                    |
| homeFolderNamingRule          |                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                  |
| ldapAgentName                 | CN=owncloudservice,CN=Users,DC=systemeccloud,DC=nl                                                 |
| ldapAgentPassword             | ***                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                    |
| ldapBackupHost                | cloud-dc02.systemeccloud.nl                                                                        |
| ldapBackupPort                |                                                                                                    |
| ldapBase                      | DC=systemeccloud,DC=nl                                                                             |
| ldapBaseGroups                | DC=systemeccloud,DC=nl                                                                             |
| ldapBaseUsers                 | DC=systemeccloud,DC=nl                                                                             |
| ldapCacheTTL                  | 300                                                                                                |
| ldapConfigurationActive       | 1                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                    |
| ldapEmailAttribute            | mail                                                                                               |
| ldapExperiencedAdmin          | 0                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                    |
| ldapExpertUsernameAttr        | UserPrincipalName                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                 |
| ldapGroupFilter               |                                                                                                    |
| ldapGroupFilterGroups         |                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                       |
| ldapHost                      | 172.16.66.2                                                                                        |
| ldapIgnoreNamingRules         |                                                                                                    |
| ldapLoginFilter               | (&(|(memberof=CN=OCUsers,CN=Users,DC=systemeccloud,DC=nl))(|(mailPrimaryAddress=%uid)(mail=%uid))) |
| ldapLoginFilterAttributes     |                                                                                                    |
| ldapLoginFilterEmail          | 1                                                                                                  |
| ldapLoginFilterMode           | 0                                                                                                  |
| ldapLoginFilterUsername       | 0                                                                                                  |
| ldapNestedGroups              | 0                                                                                                  |
| ldapOverrideMainServer        | 0                                                                                                  |
| ldapPagingSize                | 500                                                                                                |
| ldapPort                      | 389                                                                                                |
| ldapQuotaAttribute            |                                                                                                    |
| ldapQuotaDefault              |                                                                                                    |
| ldapTLS                       | 1                                                                                                  |
| ldapUserDisplayName           | displayname                                                                                        |
| ldapUserDisplayName2          |                                                                                                    |
| ldapUserFilter                | (|(memberof=CN=OCUsers,CN=Users,DC=systemeccloud,DC=nl))                                           |
| ldapUserFilterGroups          | OCUsers                                                                                            |
| ldapUserFilterMode            | 0                                                                                                  |
| ldapUserFilterObjectclass     |                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                               |
| turnOffCertCheck              | 1                                                                                                  |
| turnOnPasswordChange          | 0                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------------+


```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** Debian sid

**Comment by MorrisJobke** [comment] 2017-02-22 22:58
> The app store should not even be available (as it was explicitly not enabled in config.php)

The App Store is apps.nextcloud.com and fetching information from there. The "app store" you mean is the apps management and should work. So enabling and disabling apps that are in the apps folders should work :)

**Comment by kaosdrachen** [comment] 2017-02-23 10:04
In that case, the bug is that while "appstoreenabled" is set to false,
Installer.php fails to read the config entry that tells it where to install
apps to.

**Comment by nickvergessen** [comment] 2017-02-23 12:40
Duplicate of https://github.com/nextcloud/server/issues/2959

**Comment by nickvergessen** [comment] 2017-02-23 12:41
Work in progress for a fix is in https://github.com/nextcloud/server/pull/3287

**Closed by nickvergessen** 2017-02-23 12:40 UTC
