### ISSUE TITLE
[Bug]: Only 20 groups selectable in workflow group membership check

### ISSUE THREAD

**Issue by nwinkelstraeter** [nextcloud/server#40949] opened 2023-10-17 13:18 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When there are more than 20 groups, not all of them can be selected. The list is only populated with 20 seemingly arbitrary, yet consistent, groups and searching for groups other than that does not yield any results.

![4a018f4d29cb2c0dd2c38caf7ce46290b415b281](https://github.com/nextcloud/server/assets/81554102/85e6bec4-10a0-4a8c-b812-9ceb40550ab9)
(In the example from the gif i created the groups 1 through to 25.  The groups 5,6,7,8 and 9 are not selectable)

I am pretty sure this is an interface bug as I can change the group in the oc_flow_checks table and the Workflow functions as expected.  

This is basically the same as https://github.com/nextcloud/server/issues/24547 but this is occuring again.
(I also posted this on the forum a week ago because i thought maybe I am just using the interface incorrectly, but i do not think that is the case https://help.nextcloud.com/t/workflow-group-selection-limited-to-20-groups/171626/3)

### Steps to reproduce

I reproduced this with a fresh install using the 27.1.2 docker image from dockerhub.

1. Create more than 20 groups
2. Create a workflow and add a group membership check
3. Observe that not all groups are selectable

### Expected behavior

Searching for a group that is not part of the 20 prepopulated groups should allow me to select the desired group.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by abruening-iwt** [comment] 2023-11-15 17:08
As a (bad) workaround, I have edited `dist/workflowengine-workflowengine.js` on our instance, changing

`cloud/groups/details?limit=20&search={searchQuery}`

to

`cloud/groups/details?limit=200&search={searchQuery}`

Not great, but that makes it usable.

**Comment by Nils160988** [comment] 2023-11-17 07:55
Duplicate of #39179 ?

**Comment by blizzz** [comment] 2024-03-18 12:37
Closing as duplicate ^

**Closed by blizzz** 2024-03-18 12:37 UTC
Labels: bug, 0. Needs triage, feature: workflows, feature: users and groups, 27-feedback
