### ISSUE TITLE
"Secure view" for internal users

### ISSUE THREAD

**Issue by ediazcomellas** [nextcloud/server#25611] opened 2021-02-12 15:11 UTC
Secure View is an excellent feature. It is great to be able to limit downloads. 

What I find annoying, though. is that only works with public links. You can't share with an internal user iwht that level of control. 

Please consider adding the "secure view" functionality to regular shares for internal users.

**Comment by wiswedel** [comment] 2021-02-18 06:31
Duplicate of https://github.com/nextcloud/server/issues/16413

**Closed by wiswedel** 2021-02-18 06:31 UTC
Labels: 0. Needs triage, enhancement
