### ISSUE TITLE
pdfs with whitespaces in path or filename won't open

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#27541] opened 2021-06-17 13:03 UTC
### Steps to reproduce
1. Add a pdf with white spaces in the name into a directory structure which contains whitespaces in the name as well.
2. Delete all previews from filesystem and database
2. Regenerate Previews and rescan Filesystem
3. Try to open a pdf

### Expected behaviour
PDF should open

### Actual behaviour
As soon as there are whitespaces in the path and the name of the pdf instead of opening you receive the following error:

PDF.js v2.4.456 (build: 228a591c)
Message: Missing PDF "https://domain/nextcloud/remote.php/dav/files/user/Dokumente/Test%2520Test/18.5.2021/test%2520test.pdf".

### Server configuration

**Operating system:Ubuntu LTS 20.04

**Web server:Apache

**Database:Maria SWL

**PHP version:7.4

**Nextcloud version: 20.0.10

**Comment by acsfer** [comment] 2021-06-17 15:44
Duplicate of https://github.com/nextcloud/files_pdfviewer/issues/381

**Closed by acsfer** 2021-06-17 15:44 UTC
Labels: 0. Needs triage, bug
