### ISSUE TITLE
contact import

### ISSUE THREAD

**Issue by awdrfunk** [nextcloud/server#1168] opened 2016-08-29 16:01 UTC
importet contacts with "umalute" äöü dosnt supportet, they are wrong
(imoprt from thunderbird adress-book)
here a exemple for "Schärer", it called "Sch=C3=A4rer"

nexcloud version 10
mysql
php 7.0.9

**Comment by nickvergessen** [comment] 2016-09-12 13:59
How did you import the contacts?

**Comment by awdrfunk** [comment] 2016-09-12 14:22
with the web-frontend from nc.
is there another way to import?

**Comment by enaut** [comment] 2016-09-12 14:52
I can confirm that.

1.  can be reproduced by creating a contact in Android contacts
2. export it (to vcf)
3. import it to NC/contacts

The imported file that I used is directly exported by android see the attachment:
[inAndOut.zip](https://github.com/nextcloud/server/files/467557/inAndOut.zip)

I also added the file output.vcf that is created by:

1. import given input.vcf to nc 
2. press the download button in nc

The issue was once reported here: #541
and also here: owncloud/contacts#399

**Comment by nickvergessen** [comment] 2016-09-12 14:54
Works quite well here. I'd guess that the character set.

Edit: `;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:` exactly what I guessed.

**Comment by nickvergessen** [comment] 2016-09-14 14:10
Closing as duplicate of https://github.com/nextcloud/server/issues/541

**Closed by nickvergessen** 2016-09-14 14:10 UTC
Labels: bug, feature: dav, needs info
