### ISSUE TITLE
Files App UI Bug

### ISSUE THREAD

**Issue by yward** [nextcloud/server#16620] opened 2019-07-31 11:03 UTC
https://i.postimg.cc/DyyThZNS/Screenshot-2019-07-31-Files-Art4-Mart-Team.png

### Steps to reproduce
1. Go to Files App, you should be in "All files" tab by default.
2. Click on any other tab, for example "Tags"
3. Switch Back to "All Files" Tab.

### Expected behaviour
Should be able to go back to "All Files" without UI glitches.

### Actual behaviour
A Close/Cancel "X" Button appears out of place in the top of the files App near the "Home" Icon

Check the picture:
https://i.postimg.cc/DyyThZNS/Screenshot-2019-07-31-Files-Art4-Mart-Team.png

### Server configuration

**Operating system**:
Linux  CentOS

**Web server:**
Apache 2.4.39

**Database:**
10.1.40-MariaDB-cll-lve

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)

Latest 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 15, however, the error was also in the previous version as well.

**Where did you install Nextcloud from:**
Official Website
**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .well-known/pki-validation/0C43838576113352E23BCA232CDCDAC7.txt

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.well-known/pki-validation/0C43838576113352E23BCA232CDCDAC7.txt] => Array
                        (
                            [expected] => 
                            [current] => 7e1ae005c4040093e0ca42b985f816b4d1ff7ad34ee5ea8c723eb718073b35e26e7242e3f83e937b02bfe8e2312c67b47ad4ea4b943131dd7ae23bb32a099525
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App List</summary>

```
Only the default "Official" Apps
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'somenumber',
  'passwordsalt' => 'somesalt',
  'secret' => 'somesecret',
  'trusted_domains' => 
  array (
    0 => 'somedomain',
  ),
  'datadirectory' => 'somedirectory',
  'dbtype' => 'mysql',
  'version' => '16.0.3.0',
  'overwrite.cli.url' => 'anotherdomain',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'dbpassword' => 'somepassword',
  'installed' => true,
  'skeletondirectory' => 'somedirectory',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'support',
  'mail_domain' => 'domain',
  'mail_smtphost' => 'host',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '465',
  'mail_smtpname' => 'email',
  'mail_smtppassword' => 'pass',
  'knowledgebaseenabled' => false,
  'maintenance' => false,
  'simpleSignUpLink.shown' => false,
  'updater.secret' => 'sensitivestuff',
  'theme' => '',
  'loglevel' => 2,
);


```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes, this app: https://apps.nextcloud.com/apps/user_sql connected to MySQL database.
### Client configuration
**Browser:**
Firefox (Latest)
**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors related to Nextcloud
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Contains sensitive data and is too large to remove them manually.

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:30:10
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:30:10
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:30:10
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:30:10
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 6 globals.js:30:10
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:30:10
The humanFileSize library is deprecated! It will be removed in nextcloud 19.

```
</details>

**Comment by kesselb** [comment] 2019-08-05 09:35
Thank you :+1: 

Duplicate of https://github.com/nextcloud/server/issues/16137. Fix https://github.com/nextcloud/server/pull/16437 is part of Nextcloud 16.0.4.

**Closed by kesselb** 2019-08-05 09:35 UTC
Labels: 0. Needs triage, bug
