### ISSUE TITLE
FilesTable: "Shared by" vs. "Changed by"

### ISSUE THREAD

**Issue by FDVCZ** [nextcloud/server#21175] opened 2020-06-01 13:44 UTC
I am wondering why is always shown "**Shared by [username]**" for each file/folder in the FilesTable.

_Example: After years of working with some folders, an information "Shared by" is completely useless. Nobody cares who shared it long time ago._

Note: This information is shown only to "regular users". User who shared a folder sees only "Shared" (and the share icon).
 
On the other hand, I miss information "**Changed by**" ("Last change by") for each file (folder) in   FilesTable. 
By this I mean information who made **last** change (this information is available only in options -> details -> activity).
This information is quite important for bigger projects considering you need to know which folders/files were recently changed while you browsing through the storage (Note: I refuse to use the "Activities" section for this purpose, because there are listed thousands of changes which I do not need to know at the moment and therefore for regular daily use is this method quite impractical, slow and complicated).
 
And what I consider completely missleading and wrong is this result of current NextCloud behavior: When "User A" shares a folder and "User B" creates a file in this folder, then every other user (Users C-Z) see this file with an avatatar of the "User A" and information "Shared by User A". **But this is not true!!!** "User A" did not share the file! "User A" only shared an empty folder! The file itself was uploaded (and therefore shared) by "User B"!!! 
**This behaviour makes no sence and we do have user reports claiming this behaviour as absurd on our project!**
 
**Describe the solution you'd like**
- In a "FilesTable", for **folders** there should be shown information "Changed by", instead of "Shared by".
- In a "FilesTable", for **files** the "Shared by" parameter should give an information about who really shared the file, not who shared a superior folder in which this file is located.

**Comment by szaimen** [comment] 2021-06-02 12:11
Duplicate of https://github.com/nextcloud/server/issues/19860

**Closed by szaimen** 2021-06-02 12:11 UTC
Labels: 0. Needs triage, enhancement
