### ISSUE TITLE
existing file name containing a # sign causes directory browsing to hang up

### ISSUE THREAD

**Issue by klerai** [nextcloud/server#12845] opened 2018-12-05 10:28 UTC
### Steps to reproduce
1. drop an existing file such as 'test#1.txt' into a user folder or in an external folder
2. within the web interface, click on  the folder to enter
3. 

### Expected behaviour
 to see a list of files within that folder

### Actual behaviour
the user is left with and empty display area and the timer animation running indefinitely...

### Server configuration

**Operating system**: Debian GNU/Linux 9

**Web server:**  Apache/2.4.25 (Debian)

**Database:**     MariaDB 10.1.26-MariaDB-0+deb9u1 Debian 9.1

**PHP version:** PHP 7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215

**Nextcloud version:** 14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** NextCloudPi_docker_11-04-18

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
Cannot load Zend OPcache - it was already loaded
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_notifications: 1.0.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.8
  - dav: 1.6.0
  - deck: 0.5.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mindmaps: 0.1.0
  - news: 13.0.3
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.1
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "172.17.0.2",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "6": "192.168.201.225"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>
   {"reqId":"XAV2rawRAAIAAABrqb4AAA4M","level":3,"time":"2018-12-03T18:32:14+00:00","remoteAddr":"192.168.201.213","user":"ncp","app":"PHP","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages\/1?testOnly=true","message":"filesize(): stat failed for shared\/ at \/data\/app\/lib\/private\/LargeFileHelper.php#171","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"14.0.3.0"}

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2019-03-25 14:04
I can't reproduce this anymore. I remember some fixes related to this that went into a recent version. Could you try again with a more up to date version? If this is still happening we can investigate further. For now I would close this ticket.

**Closed by MorrisJobke** 2019-03-25 14:04 UTC
