### ISSUE TITLE
[no app in context] Debug: Deprecated event type for...

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/server#21925] opened 2020-07-20 18:48 UTC
My logging is showing debugs of the same deprecated event re-occuring, noting `no app in context`.

### Steps to reproduce
1. Open the settings - system logs
2. Verify many debug messages are occurring

### Expected behaviour
These messages should not be continuously occurring

### Server configuration

**Operating system:**
Hosted at hostiso.host

**Web server:**
Hosted at hostiso.host

**Database:**
Hosted at hostiso.host

**PHP version:**
Hosted at hostiso.host

**Nextcloud version:** (see Nextcloud admin page)
19.0.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 19.0.0

**Where did you install Nextcloud from:**
Softaculous, hostiso installer

**Are you using encryption:** yes

### Client configuration
**Browser:**
Firefox 78.0.2

**Operating system:**
Pop!_OS 20.04

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[no app in context] Debug: Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null

PROPFIND /remote.php/webdav/Pictures/2011%20-%202015/2011/Weekend%20Londen%20Rugby/2011%20London/

from x.x.x.x by arnomuhren at 2020-07-20T18:19:17+00:00

[no app in context] Debug: Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null

PROPFIND /remote.php/webdav/.Joplin//

from x.x.x.x by arnomuhren at 2020-07-20T18:30:25+00:00

[no app in context] Debug: Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null

GET /remote.php/webdav/.Joplin/62e834a4660745c4a40c44bc325b0a98.md

from x.x.x.x by arnomuhren at 2020-07-20T18:32:29+00:00
```
</details>

**Comment by kesselb** [comment] 2020-07-20 19:53
Thanks for reporting :+1: 

Closing as not a bug. You see debug messages if the loglevel is 0. Change it to anything bigger than 0 (default is 2) and you won't see them. 

Please use https://help.nextcloud.com for configuration issues and/or questions next time.

**Closed by kesselb** 2020-07-20 19:53 UTC
Labels: 0. Needs triage, bug
