### ISSUE TITLE
Untrusted domain for FQDN urls (domain name ending with a dot)

### ISSUE THREAD

**Issue by cernekj** [nextcloud/server#26800] opened 2021-04-27 18:16 UTC
### Steps to reproduce

1. open web browser with FQDN address of your domain = ending with full stop (dot, .), for example: `https://example.net./`

### Expected behaviour

Domain name with a dot on the end should work the same way as without the dot.

### Actual behaviour

Page „Access through untrusted domain“ is shown. CSS, JS, etc is not loaded.

### Server configuration

**Nextcloud version:** tested on versions 15.0.8.1 and 21.0.0.18

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "trusted_domains": [
            "example.net"
        ],
        "dbtype": "mysql",
        "version": "15.0.8.1",
        "overwrite.cli.url": "https:\/\/example.net",
        "installed": true,
        "config_is_read_only": true,
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

### Client configuration
**Browser:** not affecting server behaviour

**Operating system:** not affecting server behaviour

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Log is empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No records from time of the bug.
```
</details>

**Comment by andyxheli** [comment] 2021-04-27 19:36
Just add another line under under the trusted domains with the domain but with a . at the end 

![image](https://user-images.githubusercontent.com/59488153/116301705-f2aea780-a765-11eb-90a3-af62863f4659.png)

**Comment by cernekj** [comment] 2021-04-27 20:04
@andyxheli As I did as a workaround. I think it is against RFC 1035, because it is still the same domain, so no different behaviour is expected. And there should not be a need to specify the same domain twice in the configuration. Or at least it should be documented. 
BTW, it helps with "Access through untrusted domain" message only. It doesn't solve problem with not loading of included files (CSS, JS, images) – could be in conjunction with address rewriting.

**Comment by andyxheli** [comment] 2021-04-27 20:50
Well as far as i seen on any other website even if you type in for example google.com. it will redirect you too google.com and i dont see that happening in nextcloud if you type in cloud.example.com. it will keep you on that dot Based on the RFC 1035 i didnt see anything against but i could be wrong.

**Comment by cernekj** [comment] 2021-04-27 21:47
@andyxheli Redirection from `example.com.` to `example.com` would be a solution. Even preferred, because url `https://example.com./login` doesn't look good.

**Comment by andyxheli** [comment] 2021-04-27 23:49
@cernekj check think link out you might be able to modify the .htaccess file could be a solution https://webmasters.stackexchange.com/questions/102221/redirect-url-with-multiple-trailing-dots-and-trailing-slashes-using-htaccess

**Comment by szaimen** [comment] 2021-05-23 19:57
Hi,

Thanks for your report, but this is more of a support request. If you are an enterprise user, please report the problem through https://portal.nextcloud.com and we will help you debug the issue with priority. If you are a home user, you can ask for help on our private user forums on help.nextcloud.com.

Note that a bug report is a clear description of a bug in Nextcloud, including the steps to reproduce it on a fresh Nextcloud developer instance. In simple terms, you have to do the work to identify the root cause so our developers can fix it right away. Example code, curl examples or example apps are good ways of showing what is wrong, and we very much welcome patches and links to the relevant code. Also, please make sure you have tested if the issue also happens on the latest daily build of Nextcloud. You can learn how to set up a developer instance here: https://docs.nextcloud.com/server/latest/developer_manual/

Of course, if you can't do this debugging, help.nextcloud.com has other home users who might be willing to help or give pointers. If your business need this issue fixed, we're happy to do the debugging for you as part of our subscription services.

I will close this now, feel free to re-open if you have debugged the problem and can provide more information.

**Comment by szaimen** [comment] 2021-05-23 19:58
Hi, as this is a support request, please open a new thread on https://help.nextcloud.com
Thanks!

**Closed by szaimen** 2021-05-23 19:58 UTC
Labels: 0. Needs triage

**Comment by cernekj** [comment] 2021-05-25 18:28
This is a bug. Nextcloud Server Security library doesn't handle valid HTTP_HOST value correctly.

It can be solved by mod_rewrite redirection and/or using this path:
```diff
--- lib/private/Security/TrustedDomainHelper.php	2021-02-19 09:49:36.000000000 +0100
+++ lib/private/Security/TrustedDomainHelper.php	2021-04-27 17:33:31.000000000 +0200
@@ -100,7 +100,7 @@
 			}
 			$regex = '/^' . implode('[-\.a-zA-Z0-9]*', array_map(function ($v) {
 				return preg_quote($v, '/');
-			}, explode('*', $trusted))) . '$/i';
+			}, explode('*', $trusted))) . '\.?$/i';
 			if (preg_match($regex, $domain) || preg_match($regex, $domainWithPort)) {
 				return true;
 			}
```


I have solved the bug for myself even before I have reported it here. This ticket was just a contribution to the project. I didn't consider myself as a right person to even suggest correct solution… And I can not provide unit tests, etc.

**Comment by andyxheli** [comment] 2021-05-25 19:17
@cernekj nice job!! I think you should create a PR and have them approve it I think is a awesome idea well done!
