### ISSUE TITLE
MySQL failure/ Automatic update failing

### ISSUE THREAD

**Issue by dboneham** [nextcloud/server#15635] opened 2019-05-20 13:42 UTC
An automatic update failed, but this may have been prompted by a MySQL failure.

The log relating to My SQL was as follows:

$ sudo snap logs nextcloud
2019-05-20T13:28:54Z nextcloud.mysql[31976]: 2019-05-20T13:28:54.135473Z 0
2019-05-20T13:28:54Z nextcloud.mysql[31976]: 2019-05-20T13:28:54.136018Z 0 explicit_defaults_for_timestamp server option (see documentation for more d
2019-05-20T13:28:54Z nextcloud.mysql[31976]: 2019-05-20T13:28:54.140570Z 0 ing.
2019-05-20T13:28:54Z nextcloud.mysql[31976]: 2019-05-20T13:28:54.140713Z 0
2019-05-20T13:28:54Z nextcloud.mysql[31976]: Starting MySQL
2019-05-20T13:28:54Z nextcloud.mysql[31976]: *
2019-05-20T13:28:54Z nextcloud.mysql[31976]: Checking/upgrading mysql table
2019-05-20T13:28:54Z nextcloud.mysql[31976]: mysql_upgrade: Got error: 2002k’ (111) while connecting to the MySQL server
2019-05-20T13:28:54Z nextcloud.mysql[31976]: Upgrade process encountered er
2019-05-20T13:28:54Z nextcloud.mysql[32045]: * MySQL server process #31918

The error message shown when I tried to log in to NC, and an update was started, was this:

Update to 15.0.8
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing ‘INSERT INTO oc_appconfig (appid,configkey,configvalue) SELECT ?,?,? FROM oc_appconfig WHERE appid = ? AND configkey = ? HAVING COUNT(*) = 0’ with params [“core”, “oc.integritycheck.checker”, “[]”, “core”, “oc.integritycheck.checker”]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Detailed logs

The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by kesselb** [comment] 2020-01-26 21:02
Closing this report as duplicate of https://github.com/nextcloud/server/issues/8863. MySQL died during the upgrade. Some people suspect that it's related to Nextcloud. Probably a weird query or something like that.

**Closed by kesselb** 2020-01-26 21:02 UTC
Labels: 0. Needs triage, 15-feedback, bug
