### ISSUE TITLE
Is it possible to get the Google Drive support back?

### ISSUE THREAD

**Issue by jeffli678** [nextcloud/server#10303] opened 2018-07-19 22:22 UTC
I understand that changes on the Google side made the previous code broken. And the functionality is removed in the latest version. However, it is a very useful feature for me. Because I host my nextcloud on a VPS with 80GB storage, it is natural to have some other storage backend. And I have a 2TB plan of google drive. I think it is an ideal combination. Furthermore, I think a lot of people are using nextcloud on VPS, so having the convenience of putting files on google drive is really good. 

It is a pity that I cannot update the code myself to provide the functionality, and I do hope the development team can consider this option.

**Comment by MorrisJobke** [comment] 2018-07-20 15:19
Duplicate of #7810

**Closed by MorrisJobke** 2018-07-20 15:19 UTC
Labels: enhancement, feature: occ
