### ISSUE TITLE
[Bug]: Usage survey automatic sending enabling not possible

### ISSUE THREAD

**Issue by EchedeyLR** [nextcloud/server#39124] opened 2023-07-03 13:12 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It is not possible to enable usage survey by pressing the checkbox in the administration config.

Once you reload the page, it is not saved.

Additionally, it doesn't appear the saved changes confirmation notification like in other configurations.

### Steps to reproduce

1. Login with an admin account
2. Go to administrations settings
3. Go to usage survey panel
4. Press the checkbox to enable automatic send
5. Wait a bit and reload the page
6. See how the checkbox is unmarked
7. After a while (some months) you can confirm this is even not a rendering issue as it is not working

### Expected behavior

Being able to enable automatic sending of usage survey.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
No logs.
```

### Additional info

I have tested it with any web browser family in its latest and LTS versions to ensure it is not a web browser issue.

I have checked the network requests and it is sent properly, receiving even a 200 OK HTTP status code.

In addition, there is no confirmation dialog asking for admin password as in other settings in the same panel section for the survey.

**Comment by joshtrichards** [comment] 2023-07-03 13:48
Duplicate of nextcloud/survey_client#166

**Closed** 2023-07-03 14:37 UTC
Labels: bug, 0. Needs triage
