### ISSUE TITLE
Cannot upload files using webdav extension.

### ISSUE THREAD

**Issue by abpostelnicu** [nextcloud/server#3628] opened 2017-02-26 08:31 UTC
Hello,

I've installed recently nexcloud, and i'm trying to upload files using the webdav extension. But it fails with the message:
<img width="404" alt="screen shot 2017-02-26 at 10 22 25" src="https://cloud.githubusercontent.com/assets/11473159/23338227/84ac9a42-fc0d-11e6-801b-77c9524d8e9e.png">
Although the upload fails it still creates the file on the webdav server but with a length of 0 bytes.

The server error log that i get is:

Sabre\DAV\Exception: HTTP/1.1 500 No subsystem set a valid HTTP status code. Something must have interrupted the request without providing further detail.
/media/588c3a53-edd3-4f27-bcc1-7d2281ed8aec/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/media/588c3a53-edd3-4f27-bcc1-7d2281ed8aec/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
/media/588c3a53-edd3-4f27-bcc1-7d2281ed8aec/www/nextcloud/remote.php - line 165: require_once('/media/588c3a53...')
{main}

The configuration of my server is as follows:

OS: Debian 8
Web Server: Nginx 1.6.2
PHP-FPM: 5.6.30-0+deb8u1
MySQL: 5.6.35

Any advise is well appreciated.

**Comment by Domoel** [comment] 2017-02-28 19:46
I have the same problem.

**Comment by nickvergessen** [comment] 2017-03-07 16:28
Can you please have a look at the access log of your server with the same timestamp and check what page was requested with which user agent?
Like in https://github.com/nextcloud/server/issues/2887#issuecomment-284764532

**Comment by abpostelnicu** [comment] 2017-03-08 13:10
Here are the logs, for example i'm trying to copy and paste Test2.cpp, the output is:

`"PROPFIND /remote.php/webdav/._Test2.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._. HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/Test2.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5692 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._.DS_Store HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Home%20Assistant HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Apps HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Documents HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Downloads HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Home%20Clips HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Movies HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Music HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Photos HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Projects HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._TV%20Shows HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5692 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/Test2.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PUT /remote.php/webdav/Test2.cpp HTTP/1.1" 201 0 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Test2.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"LOCK /remote.php/webdav/Test2.cpp HTTP/1.1" 500 315 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._. HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/Test2.cpp HTTP/1.1" 207 624 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/Test2.cpp HTTP/1.1" 207 624 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/ HTTP/1.1" 207 6132 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._.DS_Store HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Home%20Assistant HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Test2.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Apps HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Documents HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Downloads HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Home%20Clips HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Movies HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Music HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Photos HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._Projects HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/._TV%20Shows HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"`

No logs are present in the nginx error log

**Comment by nickvergessen** [comment] 2017-03-13 08:08
Can you try to make the first change of https://github.com/nextcloud/server/pull/3757/files#diff-3ff2701e44d19445918d5340e29e53a3
Shoud help

**Comment by abpostelnicu** [comment] 2017-03-13 11:33
Unfortunately the result is the same:

"PROPFIND /remote.php/webdav/Apps/clang-format-test.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/Apps/clang-format-test.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PUT /remote.php/webdav/Apps/clang-format-test.cpp HTTP/1.1" 201 0 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"PROPFIND /remote.php/webdav/Apps/._clang-format-test.cpp HTTP/1.1" 404 11562 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"
"LOCK /remote.php/webdav/Apps/clang-format-test.cpp HTTP/1.1" 500 315 "-" "WebDAVFS/3.0.0 (03008000) Darwin/16.4.0 (x86_64)"

A 0 byte file is created.

**Comment by vivorbv** [comment] 2017-03-15 11:13
Exactly the same here. Tested with Apache 2.4 + PHP 7.0 and nginx + PHP 7.0 and nginx + PHP 7.1. After applying the patch from #3757 I don't get the "can't be read or written" error anymore, but file uploads result in extremely long waiting times (+60s for a 10KB file) and eventually fail (after the 60s+ wait a 0KB file is created).

**Comment by OverByThere** [comment] 2017-03-16 13:52
Just to add to this, I am getting the same issue as @vivorbv, does transfer, but takes over a minute to do 200kb.

**Comment by Yamakasi** [comment] 2017-03-22 00:59
I see the same issue at the moment, I hope we can this fixed as I finally have webdav mounted again :)

**Comment by JonathanSchndr** [comment] 2017-03-22 08:46
What is the status? @nickvergessen

**Comment by Yamakasi** [comment] 2017-03-22 13:46
I can mount WebDav using NET USE but can indeed not upload using it.

**Comment by paolomeraviglia** [comment] 2017-04-03 17:26
problem mounting webdav with OSX and windows only: What is the status? How can I solve this?

**Comment by vivorbv** [comment] 2017-04-11 14:13
Is there any news on this? It's been almost a month and this issue heavily affects what we regard as the core of nextcloud's functionality (file storage). Is it possible to give this issue a higher priority?

**Comment by paolomeraviglia** [comment] 2017-04-28 01:08
news about this problem?

**Comment by LLynx** [comment] 2017-05-04 22:10
After updating to „Nextcloud 11.0.3 (stable)“ there were no error messages anymore (Goodbye to „Error code -36“). Nevertheless I still can't upload any files via OSX Finder to a mounted „nextCloud“ folder ;-( Just mentioned not to forget this ... well ... not insignificant little slutty bug.

**Comment by abpostelnicu** [comment] 2017-05-05 09:07
I can confirm that updating to 11.0.3 fixed the issue on macOS.

**Comment by LLynx** [comment] 2017-05-05 09:56
Dear abpostelnicu, 11.0.3 does NOT fixed the problem: Still UNABLE to upload files via OSX Finder to a mounted „nextCloud“ folder. Just to be sure this thread should stay open.

**Comment by skitter-anton** [comment] 2017-07-17 09:07
Is there any update on this? I just did a complete clean install and experience the same problems on OSX (Sierra).

**Comment by JonathanSchndr** [comment] 2017-07-17 09:09
Solved: Delete Nextcloud.

**Comment by skitter-anton** [comment] 2017-07-17 09:20
@JonathanSchndr , I don't understand. You mean from the client? I checked and indeed had Nextcloud app installed on the client. I stopped the process, deleted the app, restarted and tried again. I get the same error (0kb files).

**Comment by JonathanSchndr** [comment] 2017-07-17 09:23
@skitter-anton No, sorry. iam frustrated about the missing support and patches.. i deleted nextcloud completely and use a another solution.

**Comment by skitter-anton** [comment] 2017-07-17 09:26
@JonathanSchndr Ah :-) Thank you for your reply. Any way you want to share your solution?

**Comment by OverByThere** [comment] 2017-07-17 09:30
Hi there,

I've just tested this on macOS 10.12.5 and Nextcloud 11.0.3 and it uploaded very quickly, see attached.
[Untitled.mov.zip](https://github.com/nextcloud/server/files/1152100/Untitled.mov.zip)

**Comment by skitter-anton** [comment] 2017-07-17 09:34
I am using Nextcloud version 12.0.0. I also have OSX Sierra 10.12.5 installed.

**Comment by JonathanSchndr** [comment] 2017-07-17 09:35
@OverByThere Not working :/
@skitter-anton Yes, Dropbox. :P

**Comment by tflidd** [comment] 2017-07-19 09:27
@nickvergessen Are there still infos missing? Quite a few people are interested, so it would be great to tag if it is considered as a bug or feature enhancement ;-)

**Comment by Schmuuu** [comment] 2017-07-19 10:07
So far everything else works normal, or are general downloads slow as well?

I read about the "TCP window scaling problem" recently and thought it is maybe worth looking into that, while it seems hard to find a solution currently:
https://wiki.archlinux.org/index.php/Network_configuration#The_TCP_window_scaling_problem
(see the part "How to diagnose the problem")

Especially when older OS are used, this could still be a problem today I guess.

**Comment by okoeroo** [comment] 2017-09-02 20:59
Hi, I've read all similar issues related to WebDAV usage and the -36 error from Finder.app (macOS). I have applied the two available patches, both are non-functional. Are there any developers with macOS available to fix it? This problem seem to linger since February without a resolution.

**Comment by MorrisJobke** [comment] 2017-09-04 07:44
ref #4197

**Comment by MorrisJobke** [comment] 2017-09-04 07:44
ref #6152

**Comment by okoeroo** [comment] 2017-09-08 18:28
Ok, so we've cross linked all the similar bugs on WebDAV's functionality in multiple versions. The problem seems to be pretty persistent as it seems to emerge in 11.x and is now also in 12.x. As I see it the Sabre DAV part is acting up. Sabre seems to have implemented the proper sequences for file locking. In the code I see fake locks, perhaps the Sabre 3rd party code requires updating.

**Comment by carlu93** [comment] 2017-11-23 20:59
I'm having a similar problem. Uploading files via Windows Explorer Share works as expected. Files get created with the expected filesize. Using Mountainduck or Expandrive for Windows results in 0 byte files. Nothing is logged unfortunately. Is there any fix in the pipeline? Thanks guys!

**Comment by dnwk** [comment] 2018-02-09 23:14
I have similar problem that I can't upload using webdav. I am using S3 as primary storage.
Here are logs.
Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "https://nyc3.digitaloceanspaces.com/{reducted}?uploadId=2~Zooq{reducted}NVYqo6ladIlk3oK"; AWS HTTP error: Client error response [url] https://nyc3.digitaloceanspaces.com/{reducted}?uploadId=2~Zooq{reducted}NVYqo6ladIlk3oK [status code] 400 [reason phrase] Bad Request MalformedXML (client): - <?xml version="1.0" encoding="UTF-8"?><Error><Code>MalformedXML</Code><BucketName>{reducted}</BucketName><RequestId>tx00000000000000005d8d8-005a7e2a6b-106ed5-nyc3a</RequestId><HostId>106ed5-nyc3a-nyc</HostId></Error>
/var/www/html/apps/dav/lib/Connector/Sabre/File.php - line 186: OCA\DAV\Connector\Sabre\File->convertToSabreException(Object(Aws\S3\Exception\S3MultipartUploadException))
/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php - line 151: OCA\DAV\Connector\Sabre\File->put(Resource id #8)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile('chandleroleary_...', Resource id #8)
/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('files/dnwk/imag...', Resource id #8, NULL)
[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
/var/www/html/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
/var/www/html/remote.php - line 164: require_once('/var/www/html/a...')
{main}

**Comment by jamierocks** [comment] 2018-07-11 20:54
I have the same issue running 13.0.4. :(

**Comment by LLynx** [comment] 2018-07-23 22:31
Careful reason for bright joy: I think they finally made it!

I just had 13.0.5. installed and – it worked: Since the beginnings of the old "owncloud" versions I was just able to conjure a file directly from the macOS Finder into the Nextcloud for the first time!

Simply drag and drop from a (local) folder to a (remote) folder!

21st Century: We are coming! ;-)

THX guys!

macOS High Sierra
Version 10.13.6

**Comment by jamierocks** [comment] 2018-07-23 22:51
I'll update and give it a go, hoping it works :D

**Comment by LLynx** [comment] 2018-07-23 23:48
Bad news. I was too euphoric. They did NOT make it ;-( ... only continue that zero byte file thing.

A small consolation: What I can faithfully reproduce is this:

When I look at a local file in a browser (file: //), I can drag and drop the file from the browser window to a (remote) folder. Then the file arrives in Nextcloud.

Strange, but go. Is this that "locking thing"?

**Comment by steffen-moser** [comment] 2018-08-31 23:58
I run into the same problem with Apple's Finder (macOS High Sierra 10.13.6) as a WebDav client and the following Nextcloud installation:

Nextcloud: 13.0.5
Server OS: Oracle Solaris 11.3 SRU 34 (11.3.34.4.0)
Web Server: Apache 2.4.33
PHP-FPM: 7.1.17
MySQL: 5.7.17

The problem only occurs when using PHP-FPM. When switching back to "mod_php7", it is gone. I'm  am very sure that the problem is documented [here in the section "Chunked encoding"](http://sabre.io/dav/clients/finder/). There is also an [Apache bug](https://bz.apache.org/bugzilla/show_bug.cgi?id=53332) which seems to be related to this one. For this moment, the only work-around, which seems to help, is to use mod_php instead of FPM...

**Comment by caesarcxiv** [comment] 2020-07-08 15:20
Having this issue - running a file:scan corrects the files however this is causing our organizations rollout of Next to fail since all of our mount drives report 0KB files until rescanned. Also modifying files in the GUI / openoffice does not update the file meta data causing files not to open via webdav until file:scan is rerun.

**Comment by okoeroo** [comment] 2020-07-08 19:39
This is the most silly bug ever. It's ultimately a problem in an underlying library implementing DAV and how it handles the locking mechanism. But both Owncloud and Nextcloud don't seem to be interested to apply sufficient support for over 3 years. If you intend to use Nextcloud from Finder mounts I would not consider this product for it. What could be done, assuming deployment fits other criteria on how you deal with the accounts, is to integrate a normal Samba tool that looks at the same user database, for example LDAP and have Nextcloud to look at that LDAP too. This bypasses this issue as you skip the WebDAV option and shift to CIFS/SMB on the same storage block.

**Comment by deadmanIsARabbit** [comment] 2020-12-22 14:31
I ran into this issue as well.
Turns out nginx + php-fpm over a socket file is the main cause of this issue.
After switching from socket to an IP connection everything works as expected.
Props and thanks go to @Temesta:
https://central.owncloud.org/t/nginx-connection-refused-for-webdav-requests-from-osx-client-app/17432/7

Can anybody confirm workaround as a solution for Apache aswell?

**Comment by skjnldsv** [comment] 2021-02-19 07:25
Well done @deadmanIsARabbit 
Yeah, we're all relying on a very popular dav backend implementation. 
It all works fine on the recommended setups we test against (see docs)

Closing then.

**Closed by skjnldsv** 2021-02-19 07:25 UTC
Labels: 1. to develop, bug, feature: dav
