### ISSUE TITLE
Changing password with read-only IMAP duplicates user. (OC_user_IMAP)

### ISSUE THREAD

**Issue by ShadowPhrogg32642342** [nextcloud/server#13356] opened 2019-01-04 15:39 UTC
### Steps to reproduce
1. Set up nextcloud to use IMAP as authentication backend by adding
```
    'user_backends' =>
    array (
      0 =>
      array (
        'class' => 'OC_User_IMAP',
        'arguments' =>
        array (
          0 => '{cpanel.example.com:993/imap4/ssl/readonly}',
          1 => 'my.example.com',
        ),
      ),
    ),
```
to config.php 
2. Create user on IMAP server.
3. Login using IMAP thus testing IMAP auth functionality.
4. Change account password in Users.

### Expected behaviour
I get an error message notifying me that the IMAP connection is one-way/read only.

### Actual behaviour
User got duplicated (user name -> User Name; email got copied), leading to further complications. After disabling the dupe (nextcloud-db authenticated) user, the IMAP-authenticated one pertained its display name.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
14.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocdn2xvpangu',
  'passwordsalt' => '[REDACTED]',
  'secret' => '[REDACTED]',
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{cpanel.example.com:993/imap4/ssl/readonly}',
        1 => 'my.example.com',
      ),
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\Memcached',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 51872,
    ),
  ),
  'trusted_domains' =>
  array (
    0 => 'my.example.com',
  ),
  'datadirectory' => '/home/examplec/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '14.0.1.1',
  'overwrite.cli.url' => 'http://my.example.com',
  'dbname' => 'examplec_nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'examplec_nextcloud',
  'dbpassword' => '[REDACTED]',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'example.com',
  'mail_smtphost' => 'cpanel.example.com',
  'maintenance' => false,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'updater.secret' => '',
);
```
</details>

**Comment by kesselb** [comment] 2019-02-21 12:05
I can't reproduce your problem anymore with nextcloud 16. `user_external` app is reporting to nextcloud core that password chance is not supported for this backend.

**Comment by skjnldsv** [comment] 2020-04-10 08:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 08:45 UTC
Labels: 0. Needs triage, bug
