### ISSUE TITLE
Clicking on shared folder reloads current page instead of navigating to the shared folder

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/server#13028] opened 2018-12-12 12:28 UTC
Nextcloud 15.0.0
PHP 7.2

1. When you're in the "Shares" menu where you see all your shared folders and files,
2. and you click on a folder there,
3. You'll see that it redirects to an URL like `https://cloud.asdf.com/apps/files/?dir=/SomeSharedFolder&view=shareoverview`

Instead, it should redirect to `https://cloud.asdf.com/apps/files/?dir=/SomeSharedFolder`

It simply reloads the same page right now.

**Comment by Schmuuu** [comment] 2018-12-12 17:53
Hi, I can confirm this issue. This issue only occurs, however, if you're directly on "Shares".
As soon as you click on any subcategory ("Shared with you" or "Shared by you"), it works.

**Comment by MorrisJobke** [comment] 2019-02-20 13:47
cc @nextcloud/javascript

**Comment by juliushaertl** [comment] 2019-04-11 12:42
The issue is still not solved in all cases, looks like it worked when testing due to a timing issue, but it is still happening when browsing files from the quickaccess sub-entries.

**Comment by juliushaertl** [comment] 2019-04-11 12:44
Possible fix is in https://github.com/nextcloud/server/commit/f4a9ee3db4279a77dcf842a28041a4a5ec27d922 but I still need to reproduce it reliably. :disappointed:

**Comment by MorrisJobke** [comment] 2019-04-15 09:47
Fixed by #15057

**Closed by MorrisJobke** 2019-04-15 09:47 UTC
Labels: 1. to develop, bug, feature: files, regression
