### ISSUE TITLE
Uncaught Error: Class 'OC\\Log\\ExceptionSerializer' not found in /var/www/html/lib/private/Log.php

### ISSUE THREAD

**Issue by abma** [nextcloud/server#24928] opened 2020-12-31 21:54 UTC
### Steps to reproduce
1. setup seedfault backup on a lineageos device with nextcloud client configured
2.  start the backup
3. see the error spam in the log appear, i.e.:

{"reqId":"1rNz3gyQIonZ5E50kCnW","level":3,"time":"2020-12-31T21:49:32+00:00","remoteAddr":"192.168.1.48","user":"handy","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav/.SeedVaultAndroidBackup/1607173920628/kv/com.android.calllogbackup/MzE5","message":"Uncaught Error: Class 'OC\\Log\\ExceptionSerializer' not found in /var/www/html/lib/private/Log.php:318\nStack trace:\n#0 /var/www/html/lib/private/Log/ErrorHandler.php(99): OC\\Log->logException(Object(Error), Array)\n#1 [internal function]: OC\\Log\\ErrorHandler::onAll(2, 'hash_final(): s...', '/var/www/html/l...', 71, Array)\n#2 /var/www/html/lib/private/Files/Stream/HashWrapper.php(71): hash_final(Object(HashContext))\n#3 [internal function]: OC\\Files\\Stream\\HashWrapper->stream_close()\n#4 /var/www/html/3rdparty/icewind/streams/src/Wrapper.php(132): fclose(Resource id #55)\n#5 /var/www/html/3rdparty/icewind/streams/src/CallbackWrapper.php(119): Icewind\\Streams\\Wrapper->stream_close()\n#6 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#7 {main}\n  thrown at /var/www/html/lib/private/Log.php#318","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.14.1","version":"20.0.4.0"}

### Server configuration

**Operating system:** debian 10 buster
**Web server:** apache 2.4
**Database:** mariadb 10
**PHP version:** 7.3
**Nextcloud version:** 20.0.4

**Comment by kesselb** [comment] 2021-01-01 18:43
Duplicate of https://github.com/nextcloud/server/issues/24558

**Closed by kesselb** 2021-01-01 18:43 UTC
Labels: 0. Needs triage, bug
