### ISSUE TITLE
Ldap users shows in cycle

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#21290] opened 2020-06-07 15:49 UTC
### Steps to reproduce
1. Have users in ldap
2. Have set up ldap integration
3. Proceed to the user management at /index.php/settings/users
4. In the section All users or Disabled users to see the neverending repeating of the user names (multiplication)

### Expected behaviour
Tell us what should happen
To show the users once

### Actual behaviour
Tell us what happens instead
Multiple showing of user records observed

### Server configuration

**Operating system:** CentOS 6.10

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 19.0.0.12

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from older Nextcloud 18.0.5 version

**Where did you install Nextcloud from:**

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                             |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                                                                                 |
| homeFolderNamingRule          |                                                                                                                                                                 |
| lastJpegPhotoLookup           | 0                                                                                                                                                               |
| ldapAgentName                 | cn=sysadm,dc=name1,dc=name2,dc=ua                                                                                                                                  |
| ldapAgentPassword             | ***                                                                                                                                                             |
| ldapAttributesForGroupSearch  | cn;displayName                                                                                                                                                  |
| ldapAttributesForUserSearch   | uid;sn;givenName;mail                                                                                                                                           |
| ldapBackupHost                |                                                                                                                                                                 |
| ldapBackupPort                |                                                                                                                                                                 |
| ldapBase                      | ou=people,dc=name1,dc=name2,dc=ua                                                                                                                                  |
| ldapBaseGroups                | ou=group,dc=name1,dc=name2,dc=ua                                                                                                                                   |
| ldapBaseUsers                 | ou=People,dc=name1,dc=name2,dc=ua                                                                                                                                  |
| ldapCacheTTL                  | 600                                                                                                                                                             |
| ldapConfigurationActive       | 1                                                                                                                                                               |
| ldapDefaultPPolicyDN          |                                                                                                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                 |
| ldapEmailAttribute            | mail                                                                                                                                                            |
| ldapExperiencedAdmin          | 0                                                                                                                                                               |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                                                              |
| ldapExpertUUIDUserAttr        | uid                                                                                                                                                             |
| ldapExpertUsernameAttr        | uid                                                                                                                                                             |
| ldapExtStorageHomeAttribute   |                                                                                                                                                                 |
| ldapGidNumber                 | gidNumber                                                                                                                                                       |
| ldapGroupDisplayName          | cn                                                                                                                                                              |
| ldapGroupFilter               | (|(cn=staff))                                                                                                                                                   |
| ldapGroupFilterGroups         | staff                                                                                                                                                           |
| ldapGroupFilterMode           | 0                                                                                                                                                               |
| ldapGroupFilterObjectclass    |                                                                                                                                                                 |
| ldapGroupMemberAssocAttr      | memberUid                                                                                                                                                       |
| ldapHost                      | localhost                                                                                                                                                       |
| ldapIgnoreNamingRules         |                                                                                                                                                                 |
| ldapLoginFilter               | (uid=%uid)                                                                                                                                                      |
| ldapLoginFilterAttributes     | uid                                                                                                                                                             |
| ldapLoginFilterEmail          | 0                                                                                                                                                               |
| ldapLoginFilterMode           | 1                                                                                                                                                               |
| ldapLoginFilterUsername       | 1                                                                                                                                                               |
| ldapNestedGroups              | 0                                                                                                                                                               |
| ldapOverrideMainServer        |                                                                                                                                                                 |
| ldapPagingSize                | 500                                                                                                                                                             |
| ldapPort                      | 389                                                                                                                                                             |
| ldapQuotaAttribute            |                                                                                                                                                                 |
| ldapQuotaDefault              |                                                                                                                                                                 |
| ldapTLS                       | 0                                                                                                                                                               |
| ldapUserAvatarRule            | default                                                                                                                                                         |
| ldapUserDisplayName           | displayname                                                                                                                                                     |
| ldapUserDisplayName2          | uid                                                                                                                                                             |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(objectclass=mozillaOrgPerson)(objectclass=organizationalPerson)(objectclass=qmailUser)(objectclass=person)(accountStatus=active)) |
| ldapUserFilterGroups          |                                                                                                                                                                 |
| ldapUserFilterMode            | 1                                                                                                                                                               |
| ldapUserFilterObjectclass     | inetOrgPerson;mozillaOrgPerson;organizationalPerson;person                                                                                                      |
| ldapUuidGroupAttribute        | auto                                                                                                                                                            |
| ldapUuidUserAttribute         | auto                                                                                                                                                            |
| turnOffCertCheck              | 1                                                                                                                                                               |
| turnOnPasswordChange          | 0                                                                                                                                                               |
| useMemberOfToDetectMembership | 1                                                                                                                                                               |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Chrome 83

**Operating system:** Win10 x64

![image](https://user-images.githubusercontent.com/5199030/83974738-2e474580-a8f8-11ea-8056-34620969b40a.png)

**Comment by kesselb** [comment] 2020-06-08 07:03
Similar to #21250?

**Comment by ostasevych** [comment] 2020-06-08 12:16
> Similar to #21250? Please use the search next time or at least scroll down the issue list a bit.

Sorry. Yes, the same, though I found that this bug is reproduced with LDAP users only.

**Comment by kesselb** [comment] 2020-06-08 12:45
Ok. Closing as duplicate of #21250 then.

**Closed by kesselb** 2020-06-08 12:45 UTC
Labels: 0. Needs triage, 19-feedback, bug, needs info
