### ISSUE TITLE
pictures in RAW format no showing in gallery

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#8305] opened 2018-02-12 01:20 UTC
I MAY HAVE POST THIS ISSUES IN THE WRONG PLACES, AND PUT IT ALSO HERE: https://github.com/cowai/camerarawpreviews/issues/14

PLEASE, DISREGARD IF NEEDED, Sorry....

Sorry, i found this later so i rewritte my message.

found: https://github.com/cowai/camerarawpreviews

was able to install under /nextcloud/apps

in gui, under apps/disabled apps, i can find camerapreview and hit the activate button but get : 
Could not download app camerarawpreviews
and in logging i get:
Error | PHP | Invalid argument supplied for foreach() at /var/www/html/lib/private/Installer.php#406
Error | core | Could not download app camerarawpreviews | 2018-02-12T02:45:48+0100
....

**Comment by MorrisJobke** [comment] 2018-02-12 09:20
Duplicate of #3088 because once we can do the previews the gallery app simply uses it.

**Closed by MorrisJobke** 2018-02-12 09:20 UTC
