### ISSUE TITLE
Reintroducte informations about selected documents in UI

### ISSUE THREAD

**Issue by nc-fkl** [nextcloud/server#43933] opened 2024-03-01 10:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Not a direct problem, its a feature request for a behaviour which was available in v27.x
When several documents are selected in version 28.0.3, the information at the top is missing:
How many documents are marked, How many folders, in which size are marked. - This was still available in version 27.
Please reintroduce it, was very handy.

**Describe the solution you'd like**
When several documents are selected in version 28.0.3, the information at the top should be shown like in v27

**Comment by XueSheng-GIT** [comment] 2024-03-01 11:12
Duplicate of https://github.com/nextcloud/server/issues/43441?

**Comment by nc-fkl** [comment] 2024-03-01 11:50
Hi @XueSheng-GIT , yes you are right, its a duplicate, i'll close this one, thanks!

**Closed** 2024-03-01 11:50 UTC
Labels: enhancement, 0. Needs triage, feature: files
