### ISSUE TITLE
Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle.

### ISSUE THREAD

**Issue by siimaarmaa** [nextcloud/server#28737] opened 2021-09-07 06:56 UTC
This error funny with that, my server not using Oracle. I use MariaDB.

This error comes if anyone wanna upload file with webdav. Our database admin says MariaDB log is clean and MariaDB cant to this.

Server Info
OS: CentOS Linux 8
Web Server: Apache/2.4.37 (centos)
DB: MariaDB 10.2.32
PHP: PHP 7.4.22 (cli) (built: Jul 27 2021 18:08:31) ( NTS )
NC version: 21.0.4
NC updated from older version.

App list
Enabled:
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_automatedtagging: 1.11.0
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.2
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_videoplayer: 1.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - terms_of_service: 1.7.1
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - accessibility
  - activity
  - comments
  - contactsinteraction
  - dashboard
  - encryption
  - federation
  - files_external
  - files_versions
  - firstrunwizard
  - impersonate
  - photos
  - support
  - survey_client
  - text
  - user_status
  - weather_status

External user backend is LDAP

Nextcloud log
`
[core] Error: Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle. at <<closure>>

 0. /var/www/html/nextcloud/lib/private/Files/Cache/Cache.php line 591
    OC\DB\QueryBuilder\QueryBuilder->execute()
 1. /var/www/html/nextcloud/lib/private/Files/Cache/Cache.php line 550
    OC\Files\Cache\Cache->removeChildren(OC\Files\Cache\CacheEntry {})
 2. /var/www/html/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php line 180
    OC\Files\Cache\Cache->remove("uploads/web-fil ... 6")
 3. /var/www/html/nextcloud/lib/private/Files/Cache/Updater.php line 160
    OC\Files\Cache\Wrapper\CacheWrapper->remove("uploads/web-fil ... 6")
 4. /var/www/html/nextcloud/lib/private/Files/View.php line 330
    OC\Files\Cache\Updater->remove("uploads/web-fil ... 6")
 5. /var/www/html/nextcloud/lib/private/Files/View.php line 1184
    OC\Files\View->removeUpdate(OCA\TermsOfServi ... }}, "uploads/web-fil ... 6")
 6. /var/www/html/nextcloud/lib/private/Files/View.php line 351
    OC\Files\View->basicOperation("rmdir", "/web-file-uploa ... 6", ["delete"])
 7. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 310
    OC\Files\View->rmdir("/web-file-uploa ... 6")
 8. /var/www/html/nextcloud/apps/dav/lib/Upload/FutureFile.php line 102
    OCA\DAV\Connector\Sabre\Directory->delete()
 9. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 164
    OCA\DAV\Upload\FutureFile->delete()
10. /var/www/html/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 95
    Sabre\DAV\Tree->move("uploads/USERNAME ... e", "files/USERNAME ... o")
11. /var/www/html/nextcloud/apps/dav/lib/Upload/ChunkingPlugin.php line 77
    OCA\DAV\Upload\ChunkingPlugin->performMove("uploads/USERNAME ... e", "files/USERNAME ... o")
12. /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Upload\ChunkingPlugin->beforeMove("uploads/USERNAME ... e", "files/USERNAME ... o")
13. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 603
    Sabre\DAV\Server->emit("beforeMove", ["uploads/USERNAME. ... "])
14. /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
16. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
17. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
18. /var/www/html/nextcloud/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
19. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
20. /var/www/html/nextcloud/remote.php line 167
    require_once("/var/www/html/n ... p")

MOVE /remote.php/dav/uploads/USERNAME/web-file-upload-3c5b3cf567b45c85b3c1b6c35b319562-1630921584586/.file
from IP by USERNAME at 2021-09-06T13:14:01+03:00
`

**Comment by acsfer** [comment] 2021-09-09 09:29
Duplicate of (many) https://github.com/nextcloud/server/search?q=More+than+1000+expressions&type=issues
There is already a PR for this (not yet merged).

**Closed by acsfer** 2021-09-09 09:29 UTC
Labels: bug, 0. Needs triage
