### ISSUE TITLE
[Bug]: Log Reader page out of memory crash

### ISSUE THREAD

**Issue by rlss555** [nextcloud/server#49077] opened 2024-11-04 13:44 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Navigate to /settings/admin/logging, wait for a while, the page will freeze and become unresponsive. After some time, clicking anywhere on the page will cause the browser to report "unresponsive", and eventually, the page will crash with a browser error stating "out of memory".
https://github.com/user-attachments/assets/caa2c54c-c240-4f1f-9774-137a2763a15a

### Steps to reproduce

1. Log in with an administrator account.
2. Open /settings/admin/logging.
3. Wait, the tab will crash after about 2 minutes.

### Expected behavior

The tab should not crash due to memory overflow; logs can be loaded and viewed normally.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "192.168.1.10",
            "server",
            "mydomain.tld",
            "local.mydomain.tld",
            "server-ds.mydomain.tld",
            "pub.mydomain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.8.1",
        "overwrite.cli.url": "https:\/\/server-ds.mydomain.tld:60443\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "overwriteprotocol": "https",
        "forcessl": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "log_rotate_size": 0,
        "maintenance": false,
        "mail_sendmailmode": "smtp",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0.5,
            "read_timeout": 0.5,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 2
        },
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/localhost.mydomain.tld\/server-stat\/ncapps",
        "allow_local_remote_servers": true,
        "login_from_autocomplete": false,
        "trashbin_retention_obligation": "disabled",
        "versions_retention_obligation": "366, auto",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "music",
            "files_rightclick"
        ],
        "maintenance_window_start": 17,
        "music.cover_size": 800
    }
}

### List of activated Apps

Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.16
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - music: 2.0.1
  - nextcloud_announcements: 1.18.0
  - notes: 4.11.0
  - notifications: 2.17.0
  - oauth2: 1.17.1
  - otpmanager: 0.5.4
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.10
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tasks: 0.16.1
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - twofactor_webauthn: 1.4.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - circles: 29.0.0-dev (installed 27.0.1)
  - encryption: 2.17.0
  - files_external: 1.21.0
  - talk_matterbridge: 1.26.0
  - user_ldap: 1.20.0

### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs

The issue is about the /settings/admin/logging page itself, no relevant logs are logged.

### Additional info

Google Chrome version: 130.0.6723.92

**Comment by joshtrichards** [comment] 2024-11-04 15:48
Duplicate of nextcloud/logreader#1262

**Closed by joshtrichards** 2024-11-04 15:48 UTC
Labels: bug, 0. Needs triage, 29-feedback

**Comment by punxxx-me** [comment] 2024-11-08 12:43
Same issue in Version 30.0.2 !!
Test with Chrome  130.0.6723.117 and Firefox 132.0.1

**Comment by piiskop** [comment] 2024-12-24 18:51
I confirm that the issue still exists. You demand log for each issue reporting and it is impossible to get that log. It is not a duplicate of 1262 as I do not see that error message. The tab just becomes unresponsive. I use _Opera_.
