### ISSUE TITLE
TypeError: Argument 3 passed to OCA\Files\Service\TagService::__construct() must be an instance of OCP\ITags, null given, called in /var/www/nextcloud/apps/files/lib/AppInfo/Application.php on line 108

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#26816] opened 2021-04-28 20:03 UTC
### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**

**Database:**
Maria DB 10.3
**PHP version:**
PHP 7.4
**Nextcloud version:** (see Nextcloud admin page)
21.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
20
*
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"q7sjn1RmxxLvyynishIA","level":3,"time":"2021-04-28T16:47:25+00:00","remoteAddr":"52.43.138.223","user":"--","app":"index","method":"GET","url":"/apps/files/api/v1/recent","message":{"Exception":"TypeError","Message":"Argument 3 passed to OCA\\Files\\Service\\TagService::__construct() must be an instance of OCP\\ITags, null given, called in /var/www/nextcloud/apps/files/lib/AppInfo/Application.php on line 108","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files/lib/AppInfo/Application.php","line":108,"function":"__construct","class":"OCA\\Files\\Service\\TagService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":155,"function":"OCA\\Files\\AppInfo\\{closure}","class":"OCA\\Files\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":122,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":453,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":431,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/apps/files/lib/AppInfo/Application.php","line":88,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":155,"function":"OCA\\Files\\AppInfo\\{closure}","class":"OCA\\Files\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":122,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":453,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":431,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":130,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/files/lib/Service/TagService.php","Line":61,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36","version":"21.0.1.1","id":"6089bed1d07b1"}
```
</details>

**Comment by acsfer** [comment] 2021-04-29 08:35
Duplicate of https://github.com/nextcloud/server/issues/3376

**Closed by acsfer** 2021-04-29 08:35 UTC
Labels: 0. Needs triage, bug
