### ISSUE TITLE
occ upgrade complains about missing field name on sequences with postgres 10

### ISSUE THREAD

**Issue by subzero01** [nextcloud/server#6559] opened 2017-09-18 20:51 UTC
### Steps to reproduce
1. install postgresql 10 beta 4
2. update nextcloud to version 12.0.2
3. occ upgrade

### Expected behaviour
upgrade should not complain about missing fields.

select should be rewritten as "select ... from pg_sequences where sequencename = '<sequencename>'

### Actual behaviour
upgrade tries to read min_value and increment by of sequences by using a select ... from seqencename

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_addressbookchanges_id_seq"':

SQLSTATE[42703]: Undefined column: 7 FEHLER:  Spalte »min_value« existiert nicht
LINE 1: SELECT min_value, increment_by FROM "oc_addressbookchanges_i...

### Server configuration

**Operating system**: gentoo linux

**Web server:** apache 2.4

**Database:** postgresql 10

**PHP version:** 5.6

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 10.0.1

**Where did you install Nextcloud from:** gentoo portage tree

**Comment by blizzz** [comment] 2017-09-18 21:43
Duplicate of https://github.com/nextcloud/server/issues/5930

**Closed by blizzz** 2017-09-18 21:43 UTC
