### ISSUE TITLE
Birthday without birthyear

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#9849] opened 2018-06-13 07:05 UTC
From https://github.com/nextcloud/calendar/issues/842: should be opened on server.

Some apps, e.g. contacts on samsung allow to store the birthday without birthyear (in case you do not know how old somebody is).
These contacts are synced fine to NC, but the dates are not shown in the birthday calendar.
Those dates should be shown, e.g. with in a given date range (1970-2030).

**Comment by MorrisJobke** [comment] 2018-06-13 10:17
Duplicate of #4287 - please read what others write 😉

**Comment by MorrisJobke** [comment] 2018-06-13 10:20
Also ref #3084

**Comment by tobiasKaminsky** [comment] 2018-06-13 10:29
Well, #4287 states that these dates are not synced, which in my case is not true, as they are synced.
#3084 says that they are shown with *1604, which is also not true in my case.

In my case those fields get synced to NC server, but the "birthday calendar" does not use the date and thus no calendar event is shown.

**Comment by georgehrke** [comment] 2018-06-13 11:38
I'm not aware that #4287 was fixed yet.

@tobiasKaminsky Can you please create a dummy contact, add a birthday without year, export it and post it here? :)

**Comment by tessus** [comment] 2018-06-13 15:29
@tobiasKaminsky 

> Well, #4287 states that these dates are not synced, which in my case is not true, as they are synced.

The problem is that these dates are synced but removed (or removed and synced) and lost forever.
The operative keyword here is **lost forever**.

@georgehrke unfortunately it still hasn't been fixed. I lost all my bithdays w/o a year and I then started to use the notes field for birthdays w/o a year.

**Comment by tobiasKaminsky** [comment] 2018-06-14 05:59
@georgehrke this is a contact synced from Samsung S9 (with their default contacts app) via davdroid to a NC server (server & contacs on master branch):

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.2//EN
UID:8ccc7b7f-19ee-4f9c-9a70-ab78cfc9ac0c
FN:Test
N:;Test;;;
EMAIL;TYPE=home:dummy@test.de
BDAY;X-APPLE-OMIT-YEAR=1604:1604-03-31
REV:20180614T054800Z
END:VCARD
```

The corresponding birthday calendar is this
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20180614T054802Z
DTSTART;VALUE=DATE:19000331
DTEND;VALUE=DATE:19000401
UID:8ccc7b7f-19ee-4f9c-9a70-ab78cfc9ac0c
RRULE:FREQ=YEARLY
SUMMARY:Test *
TRANSP:TRANSPARENT
BEGIN:VALARM
TRIGGER;VALUE=DURATION:-PT0M
ACTION:DISPLAY
DESCRIPTION:Test *
END:VALARM
END:VEVENT
END:VCALENDAR
```

This is shown correctly on Thunderbird, but not on Samsung S9 nor on OnePlus3.

**Comment by rfc2822** [comment] 2018-06-14 07:44
@tobiasKaminsky [Android can't process recurring events starting before 1902](https://forums.bitfire.at/topic/1227/recurring-events-before-year-1902-are-not-shown-in-calendar) because of 32-bit limitations. The given event starts in 1900.

**Comment by georgehrke** [comment] 2018-06-14 08:10
Ok, so one work around I can imagine here:
Inside the BirthdayEventGenerator, check if the property `X-APPLE-OMIT-YEAR` equals the actually used year, if yes generate events without a year starting in 1970.

**Comment by tobiasKaminsky** [comment] 2018-06-14 09:21
@georgehrke 
I would assume that always 1604 is used, so it should be checked agaist 1604 and not  against the actually used year.
And then it should be sufficient to use something after 1902 as starting year.

If you can create a patch, I am happy to test it :-)

**Comment by tessus** [comment] 2018-06-14 10:37
@georgehrke I might have been wrong with my last comment that it hasn't been fixed yet.

Well, at least the data loss has been fixed. I just entered a birthday without a year (June, 20th) on my Google Pixel and it was synced to my nextcloud as:

```
BDAY:--0620
```

Behold, even after a few times syncing, the field is still there. Yippiiee!!!!!!

The Contacts app shows this birthday `1604-06-20`, which is a bit weird, since the vcard does not contain `X-APPLE-OMIT-YEAR`.

I believe this now has to be followed up in the contacts issue tracker to

- correctly show vcard fields that look like `BDAY:--0620` and `BDAY;X-APPLE-OMIT-YEAR=1604:1604-06-20`
- allow to enter a birthday without a year in the date picker

**Comment by tobiasKaminsky** [comment] 2018-07-05 11:37
@georgehrke any news here? Can I help you with something?

**Comment by tobiasKaminsky** [comment] 2018-08-24 09:12
@georgehrke maybe we can talk about this on hackweek? :-)

**Comment by MorrisJobke** [comment] 2018-08-24 14:56
Move to 15

**Comment by georgehrke** [comment] 2018-08-24 15:00
bug, not a  feature -> 14.0.1

**Closed** 2019-02-20 09:16 UTC
Labels: 2. developing, bug, feature: dav, high
