### ISSUE TITLE
Problem with calendar and contacts

### ISSUE THREAD

**Issue by gbi39** [nextcloud/server#12918] opened 2018-12-07 18:19 UTC
I’m running a private Nextcloud installation on a Raspi-2, under Raspbian. On the client side I have 2 boxes with Debian, Thunderbird with the Lightning and Cardbook plugins. This setup has worked for years.

Starting with 14.0.1 I faced a strange problem:

Calendar and contacts only worked with one of the Debian boxes. On this one without problems, on the other one I always got an error when starting Thunderbird:
An error occured when writing to the calender job.
Error code: MODIFICATION_FAILED

Editing the calendar thru the nextcloud-webgui worked always as it should. After I lot of checking the setups without finding something I decided to do some debugging/logging. I changed the line

‘debug’ => false,

in nextcloud/config/config.php from false to true, and was very astonished that the problem went away. Now the contacts and calender also worked on the Debian box where it hasn’t worked before.

Meanwhile I have updated to 14.0.4, but the problem stays. As far as I can remember I had the same problem with 14.0.3, but not with 13.0.7 or older nextcloud versions.

At the moment the “‘debug’ => true,” with “‘loglevel’ => ‘4’,” is an acceptable workaround for me. But there must be a bug somewhere, it is illogical that I have to activate logging to get the calendar and contacts working on one of my 2 boxes.

**Comment by violoncelloch** [comment] 2018-12-07 19:38
related to caching? cc @nextcloud/server-triage

**Comment by gbi39** [comment] 2018-12-08 19:59
Hi,

I have 2 PC's, both Debian stable fully up to date, no testing or unstable components (maybe from backports). Thunderbird is 60.3.0 64bit from the official Debian repo, Lightning is also 60.3.0 from the official Debian repo. Cardbook is from Mozilla's repo. By the way, calender is also not working from a third testing box running recent Devuan.

My nextcloud is running on a Raspi 2B (the one with a 900MHz quadcore CPU and 1GB RAM), under recent RaspBian light/server, fully updated, all from stable, nothing from testing or unstable. The raspi is running a LEMP stack, means nginx-light 1.10.3, PHP 7.0.30, MariaDB 10.1.37. PHP is integrated into nginx with FPM, ZEND engine is enabled and there is APCu as local opcode cache (and it works according to it's state page, about 93-95% hit rate). I have worked thru all recommendations at Settings/Admin/Overview), but ..

On one PC calender and cardbook works, on the other not (only with activated logging in nextcloud). This problem exists since nc 14.0.1, and also with 14.0.3 and with 14.0.4. When running 14.0.1 I had an "!" besides the calender not working, which disappeared when I enabled logging ! With 14.0.4 there is no "!" besides the calender, but the calendar only sync's when logging is actived (means 'debug' => true, in config.php). This behaviour (sync only works when logging is active) is with 14.0.1, 14.0.3 (only a short test) and 14.0.4. I have not seen such a prob with earlier versions of nc (13.x.y, 12.x.y, ..,  down to several versions of owncloud before nextcloud ever existed, no offense, I'm using nextcloud since the fork).

Further details needed ?

**Comment by danielkesselberg** [comment] 2018-12-08 21:17
> CalDav access to some servers not working. Workaround: Set preference network.cookie.same-site.enabled to false.

https://www.thunderbird.net/en-US/thunderbird/60.0/releasenotes/#known-issues

> > By disabling the newly introduced parameter network.cookie.same-site.enabled the problem can be solved. So it seems to be a kind of cookie handling problem?!
> 
> Yes, there is an issue with the cookie handling. I'm talking to the person at Mozilla who implemented it to see what causes this issue and how we can resolve it.
> ### As a workaround:
> 
> (as described in Thunderbird's [release notes](https://www.thunderbird.net/en-US/thunderbird/60.0/releasenotes/#known-issues)):
> 
>     * go to the config editor (Settings -> Advanced -> General -> Config Editor)
> 
>     * search for `network.cookie.same-site.enabled`
> 
>     * set it to false
> 
> 
> For your own security you should set it back to true once this issue is resolved.

https://github.com/nextcloud/server/issues/10134#issuecomment-411322692

**Comment by gbi39** [comment] 2018-12-14 08:46
Maybe this is the same error as 10134.

First: remember: I have 2 PC's that are 99,99% identical. On one the caldav/carddav works (without my 'workaround'), on the other not. On both the setting of network.cookie.same-site.enabled is the same: TRUE

Caldav/carddav works on both with network.cookie.same-site.enabled=true when I activate logging on the NC server:

  'debug' => true,
  'loglevel' => '4',

For me this is a strong indication that the problem lies within Nextcloud. I also do not want to degrade the overall security of my mailclients as I would do when setting network.cookie.same-site.enabled to FALSE.
So far I can live with my workaround and do the next check if it works when I have done the next update of Nextcloud. I'm happy that I have brought this topic to your attention.

Thanks in advance.

**Comment by danielkesselberg** [comment] 2018-12-14 11:43
@nextcloud/calendar @nextcloud/contacts

**Comment by georgehrke** [comment] 2018-12-14 11:46
> Caldav/carddav works on both with network.cookie.same-site.enabled=true when I activate logging on the NC server:

Are you saying it only works when you activate logging? oO 

Otherwise if setting `network.cookie.same-site.enabled=true` this is definitely a duplicate of #10134

**Comment by georgehrke** [comment] 2018-12-14 11:56
> in nextcloud/config/config.php from false to true, and was very astonished that the problem went away. Now the contacts and calender also worked on the Debian box where it hasn’t worked before.

That's because the same site cookie check is not as strict in debug mode: https://github.com/nextcloud/server/blob/master/lib/base.php#L555L563

That's why you should never run productive instances in debug mode.

=> Same site cookie issue -> Duplicate of #10134

**Closed by georgehrke** 2018-12-14 11:56 UTC
Labels: 0. Needs triage, bug, feature: dav

**Comment by danielkesselberg** [comment] 2018-12-14 12:01
> That's because the same site cookie check is not as strict in debug mode: https://github.com/nextcloud/server/blob/master/lib/base.php#L555L563

I was looking for something like that but couldn't find it. Thank you @georgehrke
