### ISSUE TITLE
File Search shows old query results (race problem)

### ISSUE THREAD

**Issue by andreasdeschka** [nextcloud/server#21084] opened 2020-05-24 17:47 UTC
The search box for files automatically searches for files, while typing. There seems to be a racing problem, when the results for requests in the past take a long time.

### Steps to reproduce
1. Type in the file search a query that takes a long time for the server to answer (this depends on the server and the files on the server), for example "cod".
2. Then without a pause type in the file search a query which resolves fast, for example "xxxxx".
3. You get first the results for "xxxxx" shown
4. After some time the results for "cod" appear.

### Expected behaviour
One should only see the results for the "xxxxx" query. The old results for "cod" should not be shown any more.

**Nextcloud version:**
Nextcloud 18.0.4

### Client configuration
**Browser:**
Chrome 81, Firefox 76

**Operating system:**
Mac OS Mojave 10.14.6

**Comment by andreasdeschka** [comment] 2020-06-16 12:21
A similar problem also appears when you start a search and then click on a folder before the search results appear.

Then the content of the folder gets displayed and the search results appear below. 

I confirmed the behaviour on another Nextcloud instance, also version 18.0.4.

**Comment by szaimen** [comment] 2021-06-02 13:00
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 13:00 UTC
Labels: 0. Needs triage, bug

**Comment by andreasdeschka** [comment] 2021-06-02 13:05
Yes, I also cannot reproduce it anymore in the current version 20.0.10.
