### ISSUE TITLE
Show Battery Status on Battery Powered Devices in Monitoring

### ISSUE THREAD

**Issue by HouraisanNEET** [nextcloud/server#26456] opened 2021-04-08 08:38 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It seems that serverinfo repo is not active so I submit it here.
I host my NC on a battery powered device. I have to mind the battery level for fear that it may go poweroff.
However, to make it more durable, it's headless and the X11 is not enabled by default, which means I need another solution to check the battery status.

**Describe the solution you'd like**
- [x] Display the battery capacity by reading ``/sys/class/power_supply/*/capacity``.
- - [ ] Multi battery support? I have only mono battery devices so I cannot debug it.
- [x] Detect charging status by reading ``/sys/class/power_supply/*/status``.
- [ ] BSD support?
- [x] Monitor the battery usage by displaying a chart. 
- - [x] Cron background jobs.
- - [x] Migration and creation of the new table ``oc_serverinfo_battery``. 
- [x] API support.
- - [ ] What sort of useful data should the API respond?
- [x] Warn admin when battery low.
- - [ ] How low? 25%? 50%?
- - [x] Drop ``app.php`` and use new ``Application.php``. 
- [x] L10N support.
- [ ] UI Improvements.
- - [ ] Make the chart pretty.
- - [ ] Draw new battery icons or grab some free assets.
- - [ ] Add a live battery icon that changes with the battery capacity.

## Screenshot
![0](https://user-images.githubusercontent.com/75371007/113994645-25acfc00-9888-11eb-93b4-4d3e26ae1c7c.png)
![1](https://user-images.githubusercontent.com/75371007/113994654-2776bf80-9888-11eb-95e4-3916e6907788.png)
![2](https://user-images.githubusercontent.com/75371007/113994656-2776bf80-9888-11eb-9ffb-34bf2da85a8a.png)

**Comment by kesselb** [comment] 2021-04-09 09:21
Duplicate of https://github.com/nextcloud/serverinfo/issues/290

**Closed by kesselb** 2021-04-09 09:21 UTC
Labels: 0. Needs triage, enhancement
