### ISSUE TITLE
[GUI] Second LDAP group only shows the first member

### ISSUE THREAD

**Issue by tohn** [nextcloud/server#5440] opened 2017-06-16 13:27 UTC
### Steps to reproduce
1. Configure LDAP / AD integration
2. Create one LDAP group and share stuff with this group in Nextcloud
3. Create a second LDAP group with the same members and share a different folder with this group in Nextcloud

### Expected behaviour
The user list of the second list should be the same as of the first one.

### Actual behaviour
Only one member is shown in the GUI. But on the command line, both groups are listed in the `user:info` of all users:

```
# sudo -u apache ./occ user:info XXX-XXX-XXX
  - user_id: XXX-XXX-XXX
  - display_name: Jane Doe
  - email: j.doe@example.org
  - cloud_id: XXX-XXX-XXX@nextcloud.example.org
  - enabled: true
  - groups:
    - group1
    - group2
  - quota: 1 GB
  - last_seen: 2017-06-13T18:15:58+02:00
  - user_directory: /opt/nextcloud.example.org/data/XXX-XXX-XXX
  - backend: LDAP
```

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache/2.4.6

**Database:** mysql 5.7.18

**PHP version:** 7.1.5

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** manual from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bookmarks
  - comments
  - federation
  - files_external
  - survey_client
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "xxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.example.org",
            "nextcloud.example.net",
            "nextcloud.example.de"
        ],
        "datadirectory": "\/opt\/nextcloud.example.org\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "trusted_proxies": [
            "127.0.0.1"
        ],
        "overwriteprotocol": "https",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/nextcloud.example.org",
        "overwritecondaddr": "^127\\.0\\.0\\.1$",
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                          |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                            |
| hasPagedResultSupport         |                                                                                                                              |
| homeFolderNamingRule          |                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                            |
| ldapAgentName                 | CN=Ldap Read-Only,CN=Users,DC=xxx,DC=org                                                                                     |
| ldapAgentPassword             | ***                                                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                                                              |
| ldapAttributesForUserSearch   |                                                                                                                              |
| ldapBackupHost                |                                                                                                                              |
| ldapBackupPort                |                                                                                                                              |
| ldapBase                      | DC=xxx,DC=org                                                                                                                |
| ldapBaseGroups                | OU=Groups,DC=xxx,DC=org                                                                                                      |
| ldapBaseUsers                 | OU=User,DC=xxx,DC=org                                                                                                        |
| ldapCacheTTL                  | 600                                                                                                                          |
| ldapConfigurationActive       | 1                                                                                                                            |
| ldapDefaultPPolicyDN          |                                                                                                                              |
| ldapDynamicGroupMemberURL     |                                                                                                                              |
| ldapEmailAttribute            | mail                                                                                                                         |
| ldapExperiencedAdmin          | 1                                                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                                                              |
| ldapExpertUsernameAttr        |                                                                                                                              |
| ldapGidNumber                 | gidNumber                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                           |
| ldapGroupFilter               | (&(objectclass=group)(memberof=CN=nextcloud,OU=res,OU=Groups,DC=xxx,DC=org))                                                 |
| ldapGroupFilterGroups         | nextcloud                                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                                            |
| ldapGroupFilterObjectclass    | group                                                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                                                       |
| ldapHost                      | ldaps://xxx                                                                                                                  |
| ldapIgnoreNamingRules         |                                                                                                                              |
| ldapLoginFilter               | (&(&(objectclass=user)(memberof=CN=nextcloud,OU=res,OU=Groups,DC=xxx,DC=org))(samaccountname=%uid))                          |
| ldapLoginFilterAttributes     |                                                                                                                              |
| ldapLoginFilterEmail          | 0                                                                                                                            |
| ldapLoginFilterMode           | 0                                                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                                                            |
| ldapNestedGroups              | 0                                                                                                                            |
| ldapOverrideMainServer        |                                                                                                                              |
| ldapPagingSize                | 500                                                                                                                          |
| ldapPort                      | 9636                                                                                                                         |
| ldapQuotaAttribute            |                                                                                                                              |
| ldapQuotaDefault              |                                                                                                                              |
| ldapTLS                       | 0                                                                                                                            |
| ldapUserDisplayName           | displayname                                                                                                                  |
| ldapUserDisplayName2          |                                                                                                                              |
| ldapUserFilter                | (&(&(objectclass=user)(memberof=CN=nextcloud,OU=res,OU=Groups,DC=xxx,DC=org))(!(userAccountControl=514)))                    |
| ldapUserFilterGroups          |                                                                                                                              |
| ldapUserFilterMode            | 0                                                                                                                            |
| ldapUserFilterObjectclass     |                                                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                                                         |
| turnOffCertCheck              | 0                                                                                                                            |
| turnOnPasswordChange          | 0                                                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                                                            |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Chromium 59, Firefox 53

**Operating system:** Arch Linux

#### Browser log
<details>
<summary>Browser log</summary>

```
a) The javascript console log

Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification
```
</details>

**Comment by MorrisJobke** [comment] 2017-08-30 09:02
cc @nextcloud/ldap

**Comment by MorrisJobke** [comment] 2017-09-03 18:43
Looks like a duplicate of #2950

**Closed by MorrisJobke** 2017-09-03 18:43 UTC
Labels: 0. Needs triage, bug, feature: ldap
