### ISSUE TITLE
The selected language is not displayed when creating or editing a user

### ISSUE THREAD

**Issue by Baptistou** [nextcloud/server#20688] opened 2020-04-27 13:19 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to User panel and click new user
2. Click language field
3. Select a language in the dropdown list
4. The language name is not displayed in the field
5. Same behavior when editing an existing user

### Expected behaviour

The language name should be displayed when creating or editing a user.

### Actual behaviour

After the fix in #19912  the language name is not displayed in the field.

![image](https://user-images.githubusercontent.com/16428197/80374951-c41e9800-8897-11ea-85cd-a9a2b62c5416.png)

### Server configuration

**Operating system:** Debian

**Web server:** Nginx

**Database:** MySQL 5.7

**PHP version:** 7.3

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 18.0.3

**Where did you install Nextcloud from:** ZIP archive from https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:  
- accessibility: 1.4.0  
- activity: 2.11.0  
- admin_audit: 1.8.0  
- announcementcenter: 3.7.0  
- apporder: 0.9.0  
- bruteforcesettings: 1.6.0  
- calendar: 2.0.3  
- cloud_federation_api: 1.1.0  
- comments: 1.8.0  
- dav: 1.14.0  
- documentserver_community: 0.1.5  
- federatedfilesharing: 1.8.0  
- files: 1.13.1  
- files_downloadactivity: 1.7.0  
- files_pdfviewer: 1.7.0  
- files_rightclick: 0.15.2  
- files_sharing: 1.10.1  
- files_trashbin: 1.8.0  
- files_versions: 1.11.0  
- files_videoplayer: 1.7.0  
- firstrunwizard: 2.7.0  
- groupfolders: 6.0.6  
- logreader: 2.3.0  
- lookup_server_connector: 1.6.0  
- mail: 1.3.3  
- metadata: 0.11.1  
- music: 0.14.0  
- nextcloud_announcements: 1.7.0  
- notes: 3.2.0  
- notifications: 2.6.0  
- oauth2: 1.6.0  
- occweb: 0.0.7  
- onlyoffice: 4.1.4  
- password_policy: 1.8.0  
- photos: 1.0.0  
- provisioning_api: 1.8.0  
- recommendations: 0.6.0  
- serverinfo: 1.8.0  
- settings: 1.0.0  
- spreed: 8.0.8  
- support: 1.1.0  
- systemtags: 1.8.0  
- text: 2.0.0  
- theming: 1.9.0  
- twofactor_backupcodes: 1.7.0  
- updatenotification: 1.8.0  
- viewer: 1.2.0  
- workflowengine: 2.0.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
	"system": {
		"instanceid": "***REMOVED SENSITIVE VALUE***",
		"passwordsalt": "***REMOVED SENSITIVE VALUE***",
		"secret": "***REMOVED SENSITIVE VALUE***",
		"trusted_domains": [
			"***REMOVED SENSITIVE VALUE***"
		],
		"datadirectory": "***REMOVED SENSITIVE VALUE***",
		"dbtype": "mysql",
		"version": "18.0.2.2",
		"overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
		"dbname": "***REMOVED SENSITIVE VALUE***",
		"dbhost": "***REMOVED SENSITIVE VALUE***",
		"dbport": "",
		"dbtableprefix": "oc_",
		"mysql.utf8mb4": true,
		"dbuser": "***REMOVED SENSITIVE VALUE***",
		"dbpassword": "***REMOVED SENSITIVE VALUE***",
		"installed": true,
		"mail_smtpmode": "smtp",
		"mail_sendmailmode": "smtp",
		"mail_from_address": "***REMOVED SENSITIVE VALUE***",
		"mail_domain": "***REMOVED SENSITIVE VALUE***",
		"mail_smtpsecure": "ssl",
		"mail_smtphost": "***REMOVED SENSITIVE VALUE***",
		"mail_smtpport": "465",
		"mail_smtpauthtype": "LOGIN",
		"mail_smtpauth": 1,
		"mail_smtpname": "***REMOVED SENSITIVE VALUE***",
		"mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
		"allow_user_to_change_display_name": false,
		"loglevel": 1,
		"skeletondirectory": "",
		"defaultapp": "apporder",
		"updater.secret": "***REMOVED SENSITIVE VALUE***",
		"maintenance": false,
		"theme": ""
	}
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Tested on Chrome 80, Firefox 56 and Opera 67

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
N/A
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

**Comment by szaimen** [comment] 2021-05-31 13:33
I actually don't see the language field at all.
![image](https://user-images.githubusercontent.com/42591237/120201244-840daf80-c225-11eb-87b5-ad9ee3b249a0.png)

cc @nextcloud/server-triage is this a regression?

**Comment by Baptistou** [comment] 2021-06-02 06:34
> I actually don't see the language field at all.

The language field might be hidden by the settings at bottom left.

**Comment by szaimen** [comment] 2023-01-09 16:21
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Baptistou** [comment] 2023-01-14 09:42
Hello ! I just updated to 24.0.8, the problem is still present.

**Comment by szaimen** [comment] 2023-05-22 09:35
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Baptistou** [comment] 2023-05-24 21:13
Hello, I have not yet upgraded to the latest version but I can confirm that the issue is still present on Nextcloud 25.0.6.

**Comment by joshtrichards** [comment] 2024-01-01 15:23
I cannot reproduce this across NC25 (>NC25.0.6 that you last reported this) thru NC28. Closing as presumed fixed, but don't hesitate to re-open if you're still seeing this behavior.

**Closed by joshtrichards** 2024-01-01 15:23 UTC
Labels: bug, 0. Needs triage, feature: users and groups, 25-feedback
