### ISSUE TITLE
[Bug]: The side menu is not responsive

### ISSUE THREAD

**Issue by papa-boni** [nextcloud/server#37433] opened 2023-03-27 20:24 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

the side menu is not responsive. On smaller screens it stays big. You are not able to see the content of the page.

### Steps to reproduce

1. use a phone (iPhone 12 Mini)
2. open a browser
3. open nextcloud administrator
4. open personal info

### Expected behavior

i expected a thinner menu on the left side, or collapsed

### Installation method

Community Docker image

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
where should i do this?
```

**Comment by dirkpape** [comment] 2023-03-28 10:13
related to (or duplicate of) [](https://github.com/nextcloud/server/issues/37420) ?

**Comment by joshtrichards** [comment] 2023-08-30 13:56
Duplicate of #37420

Follow that issue for tracking progress. Thanks for your report, @papa-boni

**Closed by joshtrichards** 2023-08-30 13:56 UTC
Labels: bug, design, 0. Needs triage, feature: file sidebar, 25-feedback
