### ISSUE TITLE
[Bug]: Upgrade fails - app user_ldap update failed `SQLSTATE[23000]: Integrity constraint violation`

### ISSUE THREAD

**Issue by stbieri** [nextcloud/server#42232] opened 2023-12-13 14:11 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Upgrade from 27.1.4 to 28.0.0 fails:

Exception: Database error when running migration 1190Date20230706134108 for app user_ldap
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Garaventa_ownCloud-abov' for key 'user_ldap_membership_unique'
Update failed

### Steps to reproduce

upgrade the docker image

### Expected behavior

upgrade success.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [x] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2023-12-13 14:50
Duplicate of #41253

**Comment by stbieri** [comment] 2023-12-14 14:51
It seems for me, that this fails:
https://github.com/nextcloud/server/blob/v28.0.0/apps/user_ldap/lib/Migration/Version1190Date20230706134108.php

**Comment by joshtrichards** [comment] 2023-12-14 16:25
That's not what's happening. It's basically old stale database tables around. See #41253 for details :)

**Comment by joshtrichards** [comment] 2023-12-20 17:01
This is different then #41253 (as noted at https://github.com/nextcloud/server/issues/41253#issuecomment-1864824616) and is specific to `user_ldap`.

**Comment by joshtrichards** [comment] 2023-12-20 17:01
Cc: @come-nc

**Comment by come-nc** [comment] 2023-12-21 15:42
@stbieri Does that fixes it?
```
diff --git a/apps/user_ldap/lib/Migration/Version1190Date20230706134108.php b/apps/user_ldap/lib/Migration/Version1190Date20230706134108.php
index 3f554f56e64..cc69c1e0ec5 100644
--- a/apps/user_ldap/lib/Migration/Version1190Date20230706134108.php
+++ b/apps/user_ldap/lib/Migration/Version1190Date20230706134108.php
@@ -99,6 +99,7 @@ class Version1190Date20230706134108 extends SimpleMigrationStep {
                $result = $query->executeQuery();
                while ($row = $result->fetch()) {
                        $knownUsers = unserialize($row['owncloudusers']);
+                       $knownUsers = array_unique($knownUsers);
                        foreach ($knownUsers as $knownUser) {
                                $insert
                                        ->setParameter('groupid', $row['owncloudname'])
```

**Comment by joshtrichards** [comment] 2023-12-21 16:38
Cc: @pebkacs @jangatzke Able to test the possible fix in https://github.com/nextcloud/server/issues/42232#issuecomment-1866519775?

**Comment by pebkacs** [comment] 2023-12-21 16:46
@come-nc, I'll have to create a copy of my environment to test with, but it will likely be a while.

After the failed upgrade, I reverted my server back but upgraded to php8.1 afterwards.  I still have some configuration changes I need to fix with that so that the office isn't down before I can get back around to this test.  I'll let you know if I get the opportunity.

**Comment by aoster** [comment] 2023-12-22 11:40
@come-nc 

I have made the proposed changes to Version1190Date20230706134108.php but unfortunately this did not resolve the issue. I still get the same error which jangatzke, stbieri and pebkacs have reported.

best regards
Andreas

**Comment by kcastner** [comment] 2023-12-25 22:00
I have the same error - I use community docker version too.

<img width="856" alt="image" src="https://github.com/nextcloud/server/assets/34087750/690fc465-8ff1-4944-9ea7-763f38f76028">

Is there something i can provide/test?

**Comment by 3n1gmus** [comment] 2023-12-30 19:01
I am running into this issue as well.  I did try the 'Version1190Date20230706134108.php' modification suggested and it did not resolve the issue.

I have rolled back to 27.1.5.1 successfully, but i would like to do a clean upgrade in the near future.

**Comment by kommtzeitkonrad** [comment] 2023-12-31 19:52
Ran into the same issue. After disabling LDAP it was possible to finish the update to 28. Reenabling LDAP then failed with the above error.

I found a bunch of duplicates in the `oc_ldap_group_members` table and after a long chat with ChatGPT I was able to remove these duplicates with the following query in the `MariaDB` shell:

```
CREATE TEMPORARY TABLE temp_table AS
SELECT owncloudname, GROUP_CONCAT(DISTINCT user) AS owncloudusers
FROM (
  SELECT owncloudname, SUBSTRING_INDEX(SUBSTRING_INDEX(owncloudusers, '";', n.n), ':"', -1) AS user
  FROM oc_ldap_group_members
  CROSS JOIN (
    SELECT a.N + b.N * 10 AS n
    FROM (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a
    CROSS JOIN (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b
  ) n
  WHERE n.n <= (LENGTH(owncloudusers) - LENGTH(REPLACE(owncloudusers, ':"', ''))) / LENGTH(':"')
) AS users
GROUP BY owncloudname;
```
After this query the following steps were executed
```
TRUNCATE TABLE oc_ldap_group_members;
INSERT INTO oc_ldap_group_members SELECT * FROM temp_table;
DROP TEMPORARY TABLE IF EXISTS temp_table;
```
Afterwards it was possible to reenable LDAP and everything seems to work flawlessly again. YEET!

Happy new year everybody!! <3

**Comment by come-nc** [comment] 2024-01-02 15:57
> Ran into the same issue. After disabling LDAP it was possible to finish the update to 28. Reenabling LDAP then failed with the above error.
> 
> I found a bunch of duplicates in the `oc_ldap_group_members` table and after a long chat with ChatGPT I was able to remove these duplicates with the following query in the `MariaDB` shell:

My fix was supposed to get rid of duplicates.
Where these complete duplicate or was it with a case change or something?

**Comment by spanguel** [comment] 2024-01-02 17:16
> > Ran into the same issue. After disabling LDAP it was possible to finish the update to 28. Reenabling LDAP then failed with the above error.
> > I found a bunch of duplicates in the `oc_ldap_group_members` table and after a long chat with ChatGPT I was able to remove these duplicates with the following query in the `MariaDB` shell:
> 
> My fix was supposed to get rid of duplicates. Where these complete duplicate or was it with a case change or something?

I had the same error and ive seen the exact same copy in my table. i converted it as @kommtzeitkonrad mentioned and seems to work fine.

I am using the active directory id's so it was exactly the same.
I was wondering if it was cause i had 2 LDAP servers in my config for the same domain. even after deleting one server the duplicates where still there.

**Comment by kommtzeitkonrad** [comment] 2024-01-02 20:36
> > Ran into the same issue. After disabling LDAP it was possible to finish the update to 28. Reenabling LDAP then failed with the above error.
> > I found a bunch of duplicates in the `oc_ldap_group_members` table and after a long chat with ChatGPT I was able to remove these duplicates with the following query in the `MariaDB` shell:
> 
> My fix was supposed to get rid of duplicates. Where these complete duplicate or was it with a case change or something?

They've been complete duplicates.

**Comment by jangatzke** [comment] 2024-01-04 09:29
> Ran into the same issue. After disabling LDAP it was possible to finish the update to 28. Reenabling LDAP then failed with the above error.
> 
> I found a bunch of duplicates in the `oc_ldap_group_members` table and after a long chat with ChatGPT I was able to remove these duplicates with the following query in the `MariaDB` shell:
> 
> ```
> CREATE TEMPORARY TABLE temp_table AS
> SELECT owncloudname, GROUP_CONCAT(DISTINCT user) AS owncloudusers
> FROM (
>   SELECT owncloudname, SUBSTRING_INDEX(SUBSTRING_INDEX(owncloudusers, '";', n.n), ':"', -1) AS user
>   FROM oc_ldap_group_members
>   CROSS JOIN (
>     SELECT a.N + b.N * 10 AS n
>     FROM (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a
>     CROSS JOIN (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b
>   ) n
>   WHERE n.n <= (LENGTH(owncloudusers) - LENGTH(REPLACE(owncloudusers, ':"', ''))) / LENGTH(':"')
> ) AS users
> GROUP BY owncloudname;
> ```
> 
> This query utilizes a numeric series (n) along with SUBSTRING_INDEX to extract individual usernames. It then employs GROUP_CONCAT with DISTINCT to ensure that the usernames are unique.
> 
> Afterwards the following steps were executed:
> 
> ```
> TRUNCATE TABLE oc_ldap_group_members;
> INSERT INTO oc_ldap_group_members SELECT * FROM temp_table;
> DROP TEMPORARY TABLE IF EXISTS temp_table;
> ```
> 
> It was then possible to reenable LDAP and everything seems to work flawlessly again. YEET!
> 
> Happy new year everybody!! <3

I used ChatGPT to adapt your scripts for Postgres SQL:

`CREATE TEMPORARY TABLE temp_table AS
SELECT owncloudname, STRING_AGG(DISTINCT user, ',' ORDER BY user) AS owncloudusers
FROM (
  SELECT owncloudname, 
         SPLIT_PART(SPLIT_PART(owncloudusers, '";', n.n + 1), ':"', 2) AS user
  FROM oc_ldap_group_members
  CROSS JOIN (
    SELECT a.N + b.N * 10 AS n
    FROM generate_series(0, 99) a(N)
    CROSS JOIN generate_series(0, 9) b(N)
  ) n
  WHERE n.n <= (LENGTH(owncloudusers) - LENGTH(REPLACE(owncloudusers, ':"', ''))) / LENGTH(':"')
) AS users
GROUP BY owncloudname;
`
`-- Truncate the table
TRUNCATE TABLE oc_ldap_group_members;

-- Insert into the table from the temporary table
INSERT INTO oc_ldap_group_members
SELECT * FROM temp_table;

-- Drop the temporary table
DROP TABLE IF EXISTS temp_table;
`

After this I was able to enable the LDAP app. Thanks!

**Closed** 2024-01-04 13:17 UTC
Labels: bug, 1. to develop, feature: ldap, regression, 28-feedback

**Comment by kcastner** [comment] 2024-01-06 00:44
@come-nc sorry for "reopening" but my problem is still not fixed. maybe i miss something?

@joshtrichards as long as you closed my ticket as duplicate, this following fix should help me out, right?

> Ran into the same issue. After disabling LDAP it was possible to finish the update to 28. Reenabling LDAP then failed with the above error.
> 
> I found a bunch of duplicates in the `oc_ldap_group_members` table and after a long chat with ChatGPT I was able to remove these duplicates with the following query in the `MariaDB` shell:
> 
> ```
> CREATE TEMPORARY TABLE temp_table AS
> SELECT owncloudname, GROUP_CONCAT(DISTINCT user) AS owncloudusers
> FROM (
>   SELECT owncloudname, SUBSTRING_INDEX(SUBSTRING_INDEX(owncloudusers, '";', n.n), ':"', -1) AS user
>   FROM oc_ldap_group_members
>   CROSS JOIN (
>     SELECT a.N + b.N * 10 AS n
>     FROM (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a
>     CROSS JOIN (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b
>   ) n
>   WHERE n.n <= (LENGTH(owncloudusers) - LENGTH(REPLACE(owncloudusers, ':"', ''))) / LENGTH(':"')
> ) AS users
> GROUP BY owncloudname;
> ```
> 
> This query utilizes a numeric series (n) along with SUBSTRING_INDEX to extract individual usernames. It then employs GROUP_CONCAT with DISTINCT to ensure that the usernames are unique.
> 
> Afterwards the following steps were executed:
> 
> ```
> TRUNCATE TABLE oc_ldap_group_members;
> INSERT INTO oc_ldap_group_members SELECT * FROM temp_table;
> DROP TEMPORARY TABLE IF EXISTS temp_table;
> ```
> 
> It was then possible to reenable LDAP and everything seems to work flawlessly again. YEET!
> 
> Happy new year everybody!! <3

as i noticed, i dont have any table called ```oc_ldap_group_members```. did i miss something? 
i have a ```oc_ldap_group_membership``` according to my screenshot.
<img width="230" alt="image" src="https://github.com/nextcloud/server/assets/34087750/9339de52-948f-4811-8bd9-0c57679fb397">
<img width="327" alt="image" src="https://github.com/nextcloud/server/assets/34087750/a4d20d60-419c-4805-9555-5dcb2b4942ba">
<img width="580" alt="image" src="https://github.com/nextcloud/server/assets/34087750/f47da55e-8ac5-484e-b050-9b4b46af7021">
till now, i dont understand the problem due to no duplicates in my table ```oc_ldap_group_membership```

maybe im wrong, i think this is another problem? if you think too, please reopen my issue, otherwise im still looking for a fix.

other screenshots according to tables containing "ldap" in its name:
<img width="287" alt="image" src="https://github.com/nextcloud/server/assets/34087750/270fca42-d73e-49a1-9de1-0f071bf92b04">
<img width="486" alt="image" src="https://github.com/nextcloud/server/assets/34087750/d4a35e12-cc31-41d8-a5e4-bcdc4347be25">

<img width="278" alt="image" src="https://github.com/nextcloud/server/assets/34087750/c9c25e84-cb6a-4dda-9215-b4c09c2a0ac1">
<img width="494" alt="image" src="https://github.com/nextcloud/server/assets/34087750/89ec1cab-d956-4a42-a5ef-f5048274a891">
