### ISSUE TITLE
Version 21 Upgrade Error 

### ISSUE THREAD

**Issue by NextFreak** [nextcloud/server#25907] opened 2021-03-03 08:34 UTC
When starting the Updater, it says:
OC\DB\Exceptions\DbalException: Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027
Platform may not support it.

**Comment by NextFreak** [comment] 2021-03-03 09:47
Her is the detailled message:

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

OC\DB\Exceptions\DbalException: Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.

**Comment by kesselb** [comment] 2021-03-03 21:11
Duplicate of https://github.com/nextcloud/server/issues/25748

**Closed by kesselb** 2021-03-03 21:11 UTC
Labels: 0. Needs triage, bug
