### ISSUE TITLE
[Bug]: Dashboard different sizes of tiles

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#38199] opened 2023-05-11 13:02 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If a tile in the dashboard view doesn't have an entry ('no message' , 'no appointement today' etc.) it is larger than a tile containing entries.

### Steps to reproduce

Look the dashboard

### Expected behavior

All boxes must be equal.

### Installation method

None

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Dashboard
```

### List of activated Apps

```shell
Dashboard
```

### Additional info
![Attachment file 1 capture-for-jira-screenshot-20230417-141146-295](https://github.com/nextcloud/server/assets/8616947/1ef52917-de10-4bff-ab7c-510ec9534d10)

_No response_

**Comment by joshtrichards** [comment] 2023-09-19 14:16
Duplicate of #35282 

Please subscribe yourself to that issue and/or give it a :+1: to help prioritize it. Thanks for reporting!

**Closed by joshtrichards** 2023-09-19 14:16 UTC
Labels: bug, 0. Needs triage, feature: dashboard, 25-feedback
