### ISSUE TITLE
Re-share with group: No read permissions

### ISSUE THREAD

**Issue by dacoex** [nextcloud/server#11246] opened 2018-09-16 22:34 UTC
### Steps to reproduce
1. admin user receives a external federated share
2. admin user re-shares is with a group Members
3. normal User who is a member of Members logs in and sees the share
4.User tries to enter shared folder
5. Entering folder cannot enter the re-shared folder but receives the message: “This Operation is not allowed”

### Expected behaviour
User can access the re-shared folder as per original permissions

### Actual behaviour
Under the admin user’s protocol, the error message shows:

```OCA\DAV\Connector\Sabre\Exception\Forbidden: No read permissions```

### Server configuration

**Operating system**:
?
Shared host somewhere

**Web server:**
?

**Database:**
MySQL

**PHP version:**
5

**Nextcloud version:** (see Nextcloud admin page)
14

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Server admin panel of webhoster

Reference:
https://help.nextcloud.com/t/re-share-with-group-no-read-permissions/36703

**Comment by dacoex** [comment] 2018-09-23 17:47
@nextcloud-bot 
Sorry but this issue is different.

**Comment by MorrisJobke** [comment] 2018-09-27 14:39
cc @nextcloud/sharing

**Comment by skjnldsv** [comment] 2020-04-10 07:20
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 07:20 UTC
Labels: 0. Needs triage, bug, feature: sharing
