### ISSUE TITLE
oc_filecache: cache invalidation fail after multiple MOVE operations

### ISSUE THREAD

**Issue by klada** [nextcloud/server#5561] opened 2017-06-29 12:15 UTC
From time to time the `oc_filecache` tables becomes inconsistent on my local Nextcloud instance. It sometimes contains entries for files, which have been deleted or moved. The only way to fix this is calling `occ files:scan` manually.

In my setup the files can only be modified through Nextcloud, no other file access is possible for users.

The last time I was able to reproduce this issue was in the following scenario:

1. User **A** shares a folder with multiple users
1. User **B** `PUT`s a file **X** to this shared folder
1. User **B** updates the file **X** a couple of times
1. User **C** also syncs the share from **A** and gets all the updates of file **X** which user **B** writes
1. User **B** moves the file to **Y** → This `MOVE` operation works as expected
1. User **B** again `PUT`s a file **X** to the original folder (same name as original **X**)
1. User **B** `MOVE`s file **X** to **Y** again → **cache invalidation fail** in `oc_filecache`

Now since this might not be too easy to understand I'll post a shortened log output with the relevant information:

<details>
<summary>Relevant log contents</summary>

```
[INFO] -- 2017-06-29 10:27:40+02:00 --
[INFO] PUT /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File updated: "/Shared/Folder/sample_file.pdf"
[INFO] -- 2017-06-29 10:27:40+02:00 --
[INFO] PUT /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File written to: "/Shared/Folder/sample_file.pdf"

[INFO] 10:28:01+02:00
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File accessed: "/Shared/Folder/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:01+02:00 --
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File created: "/Shared/Folder/tmp/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:01+02:00 --
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File written to: "/Shared/Folder/tmp/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:01+02:00 --
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File deleted: "/Shared/Folder/sample_file.pdf"

[INFO] -- 2017-06-29 10:28:18+02:00 --
[INFO] PUT /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File created: "/Shared/Folder/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:18+02:00 --
[INFO] PUT /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File written to: "/Shared/Folder/sample_file.pdf"

// The share owner and any other user may also access the file at any time
[INFO] -- 2017-06-29 10:28:43+02:00 --
[INFO] GET /remote.php/dav/files/OWNER/Shared/Folder/sample_file.pdf
[INFO] User: 'OWNER'@'otherhost.local'
[INFO] File accessed: "/Shared/Folder/sample_file.pdf"

[INFO] -- 2017-06-29 10:28:46+02:00 --
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File accessed: "/Shared/Folder/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:46+02:00 --
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File created: "/Shared/Folder/tmp/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:46+02:00 --
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File written to: "/Shared/Folder/tmp/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:46+02:00 --
[INFO] MOVE /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File deleted: "/Shared/Folder/sample_file.pdf"
[INFO] -- 2017-06-29 10:28:53+02:00 --
[INFO] GET /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[INFO] User: 'USERNAME'@'hostname.local'
[INFO] File accessed: "/Shared/Folder/sample_file.pdf"
[ERROR] -- 2017-06-29 10:28:53+02:00 --
[ERROR] GET /remote.php/dav/files/USERNAME/Shared/Folder/sample_file.pdf
[ERROR] User: 'USERNAME'@'hostname.local'
[ERROR] fopen(/nextcloud/userhomes/OWNER/files/Shared/Folder/sample_file.pdf): failed to open stream: No such file or directory at /var/www/html/nextcloud/lib/private/Files/Storage/Local.php#287
```

</details>

The reason why the error in the log pops up is that `/Shared/Folder/sample_file.pdf` is still in `oc_filecache`. So there must be a cache invalidation issue in this access scenario. Both `mtime` and `storage_mtime` of the cache record are set to `1498724890`, which equals `2017-06-29 10:28:10` in my local timezone.

This big question is: why has the cache entry not been removed from `oc_filecache` after the second `MOVE` operation...

### Expected behaviour

`oc_filecache` should be consistent

### Actual behaviour

`oc_filecache` inconsistent

### Server configuration

**Operating system**: CentOS 7.3

**Web server:** Apache 2.4.6

**Database:** PostgreSQL 9.2.18

**PHP version:** 7.0.20

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** RPM

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - user_serverauth: 0.2.0
  - workflowengine: 1.1.1
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.local",
        ],
        "datadirectory": "\/nextcloud",
        "overwrite.cli.url": "https:\/\/mydomain.local",
        "dbtype": "pgsql",
        "version": "11.0.3.2",
        "dbname": "owncloud",
        "dbhost": "ownclouddb.mydomain.local",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 1,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "theme": "custom",
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "redis.mydomain.local",
            "port": 6379
        },
        "filelocking.enabled": true,
        "trashbin_retention_obligation": "auto",
        "singleuser": false,
        "activity_expire_days": 30,
        "mail_from_address": "support",
        "mail_smtpmode": "php",
        "mail_domain": "mydomain.local",
    }
}
```
</details>

**Are you using external storage, if yes which one:** no, local storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** custom apacheauth backend (user_serverauth) -> https://github.com/klada/nextcloud-user-serverauth

**Comment by MorrisJobke** [comment] 2017-08-30 09:56
cc @icewind1991

**Comment by MorrisJobke** [comment] 2019-02-27 13:05
@klada There is a similar case to what you experienced in https://github.com/nextcloud/server/issues/3524 - maybe https://github.com/nextcloud/server/issues/3524#issuecomment-467851069 helps to resolve the issues you are facing?

**Comment by klada** [comment] 2019-03-04 09:19
@klada The patch does an `ORDER BY` on a field without DB index. I don't think this is a good idea - we'd need a schema change which adds an index first.

**Comment by cowai** [comment] 2019-03-19 21:49
@klada If you check latest master now. This was merged som days ago: https://github.com/nextcloud/server/pull/14425
It avoids using the order by. This should only fix background scan. So if your problem is caused by other bugs, it won't help.

Before this PR a background scan (cron or occ files:scan --unscanned) was needed between each change to be certain it got in the filecache. In other words, a race condition.

**Comment by MorrisJobke** [comment] 2019-03-20 07:41
This one was most likely caused by „normal“ usage and then fixed with a files scan.

**Comment by cowai** [comment] 2019-03-20 08:36
@MorrisJobke Could be, but doing a files scan is not something people do every day necessarily.

**Comment by MorrisJobke** [comment] 2019-03-20 10:28
> @MorrisJobke Could be, but doing a files scan is not something people do every day necessarily.

Actually I talked with @klada here in person and on this specific instance it is the case.

**Comment by szaimen** [comment] 2022-11-26 14:26
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:35 UTC
Labels: bug, needs info, feature: filesystem, 0. Needs triage
