### ISSUE TITLE
Repeated dashboard icon in the top panel

### ISSUE THREAD

**Issue by andrzej-r** [nextcloud/server#25691] opened 2021-02-17 10:51 UTC
**Problem:** Clicking on either the Nextcloud logo or the dashboard app icon next to it open up the same dashboard page. Two icons serving the same purpose are confusing and waste space in narrow screens (mobile).

**Proposed solution:** I'd prefer if the dashboard was accessible via the Nextcloud logo/menu only and the dashboard app icon was removed from the top menu.

**Comment by andrzej-r** [comment] 2021-02-17 10:58
This is intended for a label:design tag.

**Comment by kesselb** [comment] 2021-02-17 20:18
Duplicate of https://github.com/nextcloud/server/issues/24362

**Closed by kesselb** 2021-02-17 20:18 UTC
Labels: 0. Needs triage, bug
