### ISSUE TITLE
Allow Uploading with Dynamic IP Adresses

### ISSUE THREAD

**Issue by Putzlappeneimer** [nextcloud/server#2181] opened 2016-11-17 14:36 UTC
### Steps to reproduce
1. Upload a file with an Account or on a shared link
2. Reset your Router that you get a new IP
3. Continue with Uploading the file

### Expected behaviour
Tell us what should happen
Even if the router disconnects for a few seconds and u get a new IP, the browser upload should be able to continue where it stopped. This is very important to us, because we need nextcloud to upload big files with their browser.

### Actual behaviour
Tell us what happens instead
The Browser shows an error and reloads the website in the next 5 seconds. The Upload disappeared and doesnt finish. The problem here is not the short time without connection, the problem is the changed IP. If the router resets and has the same IP afterwards, the upload continues. For your Information: The server itself is installed behind a static IP.

I really dont know much about it, but wouldnt it be possible to do uploads in chunks and give a session id to the upload? So after the reconnect with new IP, the servers still knows who is uploading because of the session id and he maybe continues with the upload, because he knows how far the upload went? I guess the whole thing would mean a large amount of work, but it is possible. I tried the same thing with an upload with my browser using the software ftapi and after a minute of doing nothing he continued with the upload. Or maybe it is even possible now with nextcloud and i have something configured wrong?? That would be the best :)

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache2
**Database:**
mariadb
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
10.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
10.1
**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

**Browser:**I think i tested with Edge, Opera and Mozilla

**Operating system:**Windows 10

**Comment by MorrisJobke** [comment] 2016-12-21 05:55
@rullzer this seems to be a duplicate of the "use chunked upload on web UI" issue but sadly I can't find it anymore. Do you know if I just remind this wrongly or if I'm too dumb to find it. (and is it at all related?)

**Comment by rullzer** [comment] 2016-12-22 19:29
@MorrisJobke well the latter could still be true :wink: By any chance you remember https://github.com/owncloud/core/issues/8955 ?

Anyway, I don't see this happening any time soon. It is a big beast and lots of things can go wrong.

**Comment by szaimen** [comment] 2021-05-21 12:52
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Closed by szaimen** 2021-05-21 12:52 UTC
Labels: 1. to develop, enhancement
