### ISSUE TITLE
NC 16.0.3-05 Adding new folder within file picker when moving/copying results in endless spinner 

### ISSUE THREAD

**Issue by patrick-stickler-csc-fi** [nextcloud/server#17410] opened 2019-10-04 17:03 UTC
### Steps to reproduce
1. Attempt to move or copy a file or folder
2. In file picker, click "+" to create new folder
3. Give folder a name and submit
4. Folder is created but get endless spinner

### Expected behaviour

File picker should fill with new empty folder

### Actual behaviour

Endless spinner (though folder is created)

### Server configuration

**Operating system**:

**Web server:**

**Database:**

Postgres

**PHP version:**

7.3

**Nextcloud version:** (see Nextcloud admin page)

16.0.3 but problem also exists in 16.0.5

The fix I have applied is as follows:

```  
/nextcloud/core/js/oc-dialogs.js:
333c333
< 						self._fillFilePicker(self.$filePicker.data('path') + newname );
---
> 						self._fillFilePicker(self.$filePicker.data('path') + '/' + newname );
```

</details>

**Comment by kesselb** [comment] 2019-10-04 18:10
Thank you :+1: 

I hope it's okay with you to close this issue as duplicate of: https://github.com/nextcloud/server/issues/17283
Here is the patch https://github.com/nextcloud/server/pull/17285 and it's already on the way to 17.0.1 and 16.0.6.

**Closed by kesselb** 2019-10-04 18:10 UTC
Labels: 0. Needs triage, bug
