### ISSUE TITLE
🖼️ Displaying iOS Live Photos

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40244] opened 2023-09-04 15:06 UTC
- [x] Keep both file in the WebDAV responses
- [x] Expose the `livephotos` property in the WebDAV responses
- [x] In file lists, hide the `.mov` file, and play the `.mov` file on hover or long press
    - [x] File web UI
    - [x] Photos web UI
    - Android https://github.com/nextcloud/android/issues/12124
    - iOS https://github.com/nextcloud/ios/issues/2652
- [ ] In the viewer, play the `.mov` file when it's opened, and add a button to allow the user to replay it

**Comment by sorbaugh** [comment] 2023-09-19 14:31
subtask to #40242

**Comment by AndyXheli** [comment] 2023-12-26 16:02
Files are still being displayed as two different items, its my understand that file should only show one file but as live is this not correct?  

<img width="162" alt="image" src="https://github.com/nextcloud/server/assets/59488153/88e191ce-2a65-46ef-a98a-8320586a8f9e">

**Comment by artonge** [comment] 2024-01-02 11:01
> Files are still being displayed as two different items, its my understand that file should only show one file but as live is this not correct?

It should not, indeed. Do you have "Display hidden files" enabled?

**Comment by AndyXheli** [comment] 2024-01-04 22:17
@artonge no i do not have Display hidden files but i noticed that some file that are showing up correctly  i just uploaded some new photos and .mov file are not showing they are hidden but all of my older file that where upload before nc 28 server upgrade they are showing both .mov and .jpg. Seems like anything new that i upload works as it should

**Comment by AndyScherzinger** [comment] 2024-01-05 12:11
@AndyXheli that is by design. The ios app needs tell the server during upload which files belong together. So files before latest ios client and v28 server will always show up as 2 distinct files in the UI.

**Comment by AndyXheli** [comment] 2024-01-05 14:08
@AndyScherzinger Thanks for the information but i think there should be a way to merge all the existing live photos together. The server should not only relay on the ios client to handle that.

**Comment by artonge** [comment] 2024-02-14 11:48
Closing as I think everything is implemented now.

**Closed by artonge** 2024-02-14 11:48 UTC
Labels: enhancement, 1. to develop, ❄️ 2023-Winter

**Comment by HannesJo0139** [comment] 2024-04-23 17:18
> @AndyXheli that is by design. The ios app needs tell the server during upload which files belong together. So files before latest ios client and v28 server will always show up as 2 distinct files in the UI.

No offense but if this is by design then the design is bullshit.

**Comment by artonge** [comment] 2024-04-23 18:45
> No offense but if this is by design then the design is bullshit.

Please bring some constructive arguments, else your comment is actually offensive.

**Comment by HannesJo0139** [comment] 2024-04-23 19:10
Bro really? After crashing your car, do you ask for constructive arguments? Should be quite obvious. Sometimes one must wonder if you guys actually use the software yourself you are developing.
