### ISSUE TITLE
[Bug]: Error: Using ${var} in strings is deprecated (fixed on v27, not on v26)

### ISSUE THREAD

**Issue by BJKle** [nextcloud/server#37362] opened 2023-03-23 09:03 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to PHP 8.2, the error log throws following error:

PHP] Error: Using ${var} in strings is deprecated, use {$var} instead at /var/www/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php#3491
GET /apps/theming/theme/dark.css?plain=0&v=3832917f
from xxx.xxx.xxx.xxx by xxx at 2023-03-22T22:05:57+01:00

### Steps to reproduce

restart Nextcloud

### Expected behavior

no error

update Compiler.php to the latest version

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
irrelevant
```

**Comment by szaimen** [comment] 2023-03-23 09:05
Hi, which nc version?

**Comment by BJKle** [comment] 2023-03-23 09:53
> Hi, which nc version?

Latest Version 26 (Hub 4)

**Comment by szaimen** [comment] 2023-03-23 09:54
cc @come-nc

**Comment by BJKle** [comment] 2023-03-23 10:05
change is quite easy in Compiler.php

--- 8< --- actual implementation begin

   $fn = "op${ucOpName}${ucLType}${ucRType}";

                if (
                    \is_callable([$this, $fn]) ||
                    (($fn = "op${ucLType}${ucRType}") &&
                        \is_callable([$this, $fn]) &&
                        $passOp = true) ||
                    (($fn = "op${ucOpName}") &&
                        \is_callable([$this, $fn]) &&
                        $genOp = true)
 )               
--- >8 --- actual implementation end
                
                

--- to be replaced by begin
                    
   $fn = "op{$ucOpName}{$ucLType}{$ucRType}";
                   if (
                    \is_callable([$this, $fn]) ||
                    (($fn = "op{$ucLType}{$ucRType}") &&
                        \is_callable([$this, $fn]) &&
                        $passOp = true) ||
                    (($fn = "op{$ucOpName}") &&
                        \is_callable([$this, $fn]) &&
                        $genOp = true)
)
--- to be replaced by end

**Comment by solracsf** [comment] 2023-03-23 12:58
This is already fixed upstream.
https://github.com/scssphp/scssphp/blob/master/src/Compiler.php

Merging (and backporting) https://github.com/nextcloud/3rdparty/pull/1330 would fix it.

**Comment by chrissi55** [comment] 2023-03-27 05:56
Have a question

i downloaded the scssphp 1.11.0 from here https://github.com/scssphp/scssphp
and unpacked all to ../3rdparty/scssphp/scssphp

after restart NC + PHP i got errors like this
Exception: Class "ScssPhp\ScssPhp\Block\DirectiveBlock" not found in file '/var/www/nextcloud/3rdparty/scssphp/scssphp/src/Parser.php' line 855

i see the message

GET /apps/theming/theme/opendyslexic.css?plain=0&v=c0202fbc
from MY.LOCAL.IP by USERNAME at 2023-03-27T07:35:31+02:00

so i downloaded the "opendyslexic,css from here https://gist.github.com/mvilrokx/4536584
and created the folder ../apps/theming/theme and placed the css into it.

With that the error ..855 is gone but my style looks like .... better not decribe it.

Can anyone give me e hint how to get rif of the ..855 errors without this css file?
Thanks

**Comment by BJKle** [comment] 2023-03-27 06:56
> This is already fixed upstream. https://github.com/scssphp/scssphp/blob/master/src/Compiler.php
> 
> Merging (and backporting) [nextcloud/3rdparty#1330](https://github.com/nextcloud/3rdparty/pull/1330) would fix it.

Thanks for the information. But it is labelled for NC24 and nobody is working on it.

I'll "patch" my NC instances with the code above ;-)

**Comment by solracsf** [comment] 2023-03-27 16:30
Hey, this is not an error, in the way it causes troubles! It is just a deprecation warning, nothing else (even if it is labled "error").

**Comment by solracsf** [comment] 2023-04-20 22:09
`master` branch is v27 only.
https://github.com/nextcloud/3rdparty/pull/1357

**Comment by gehkah** [comment] 2023-04-24 06:17
> @solracsf I updated NC to 26.0.1 today and the error is still there :-(

confirmed, same here on multiple instances

**Comment by solracsf** [comment] 2023-04-24 06:33
https://github.com/nextcloud/server/issues/37362#issuecomment-1519450598

**Comment by gehkah** [comment] 2023-04-24 06:37
> [#37444 (comment)](https://github.com/nextcloud/server/pull/37444#issuecomment-1516380695)

If someone see the folling error in logfiles

Fehler index Exception: Class "ScssPhp\ScssPhp\Block\DirectiveBlock" not found in file '/var/www/nextcloud/3rdparty/scssphp/scssphp/src/Parser.php' line 855

that affects the missing

GET /apps/theming/theme/opendyslexic.css?plain=

I can get rid of those messages by symlinking my default.css to this place.
So i mkdir /var/www/nextcloud/apps/theming/theme
make it owned by www-data by

chown -R www-data:www-data /var/www/nextcloud/apps/theming/theme

Then symlinking

ln -s /var/www/nextcloud/apps/theming/css/default.css /var/www/nextcloud/apps/theming/theme/opendyslexic.css

After that the errors 855 are gone so far.

sauce: https://help.nextcloud.com/t/update-26-0-0-to-26-0-1-delivers-again-using-var-in-strings-is-deprecated-use-var-instead-3rdparty-scssphp-scssphp-src-compiler-php-3491/160587/2

**Comment by thstyl2000** [comment] 2023-06-16 09:15
Still happening on v27:

[nextcloud/mail/issues/8556](https://github.com/nextcloud/mail/issues/8556)

**Comment by AndyXheli** [comment] 2023-07-17 02:15
Hi all just seen this error on NC 26.0.3 running PHP 8.2 

{"reqId":"NO2mQVFco7tLtCQjCjKf","level":3,"time":"2023-07-16T21:13:14-05:00","remoteAddr":"1.1.1.1","user":"ad","app":"PHP","method":"GET","url":"/apps/theming/theme/light-highcontrast.css?plain=0&v=fc564fc5","message":"Using ${var} in strings is deprecated, use {$var} instead at /var/www/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php#3491","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"26.0.3.2","data":{"app":"PHP"},"id":"64b4a3c5dd830"}

**Comment by solracsf** [comment] 2023-08-17 10:14
Closing as per https://github.com/nextcloud/server/pull/37444#issuecomment-1682008933
This is **fixed in v27+ only**, will **not** be backported.

**Closed by solracsf** 2023-08-17 10:14 UTC
Labels: bug, 0. Needs triage, 26-feedback
