### ISSUE TITLE
Filepicker for "Move file" should remember the last directory.

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3313] opened 2017-01-30 08:48 UTC
It should automatically reopen the last chosen directory, like browsers do for uploads.
This allows easier moving of multiple files in a row.

Agreed? @jancborchardt @icewind1991

**Comment by ChristophWurst** [comment] 2017-01-30 10:30
Makes sense. We have the same problem in Mail where it is cumbersome to add multiple attachments.

**Comment by jancborchardt** [comment] 2017-01-31 18:27
I agree, and this is a duplicate of https://github.com/nextcloud/server/issues/644 ;)

**Closed by jancborchardt** 2017-01-31 18:27 UTC
Labels: bug, feature: filepicker, papercut
