### ISSUE TITLE
Unable to set quota when adding a new user

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#10916] opened 2018-08-29 06:40 UTC
### Steps to reproduce
1. Go to Users
2. Click on "New user" button in the left menu
3. Fill all user fields except quota
4. Set "100 MB" in quota field
5. (don't click Enter) Click on add icon

### Expected behaviour
Add user with 100 MB quota

### Actual behaviour
Add user with default quota

### Server configuration
**Nextcloud version:** 14.0.0 RC1

### Client configuration
**Browser:** 61.0.2 (64-bit)

**Operating system:** Debian Stretch

**Comment by MorrisJobke** [comment] 2018-10-01 18:52
I could not reproduce this anymore on current master as well as on 14.0.1. I guess @skjnldsv fixed it in one of the later versions after the RC1. I will close this for now.

**Comment by R0maNNN** [comment] 2018-10-02 18:17
@MorrisJobke, reproduced on 14.0.1

**Comment by skjnldsv** [comment] 2018-10-02 19:42
yes this is fixed now, should be in 14.0.2

**Comment by R0maNNN** [comment] 2018-10-05 09:49
@MorrisJobke @skjnldsv reproduced on 14.0.2 RC 1

**Comment by R0maNNN** [comment] 2018-10-11 10:28
@MorrisJobke @skjnldsv reproduced on 14.0.2

**Comment by skjnldsv** [comment] 2018-10-16 08:18
Nope, I can again say this is fixed in 14.0.2.
Enter any quota you want in the new user quota dropdown and validate by pressing enter or clicking on it. Then confirm your contact creation.

![peek 16-10-2018 09-55](https://user-images.githubusercontent.com/14975046/47002294-e248fb00-d12c-11e8-8548-431104827638.gif)

**Closed by skjnldsv** 2018-10-16 08:18 UTC
Labels: bug

**Comment by R0maNNN** [comment] 2018-10-16 19:56
@skjnldsv, I wrote in my first message: “don't click Enter.” In my STR, I forgot to note to skip a click on an item in a combobox. This is bug?

**Comment by skjnldsv** [comment] 2018-10-16 21:01
@R0maNNN I do not understand your message. Could you ellaborate a bit more please?
You can either click the quota or press enter to validate. As long as you did not clicked the custom quota, it won't be selected :)

**Comment by R0maNNN** [comment] 2018-10-18 21:31
> As long as you did not clicked the custom quota, it won't be selected :)
Ok, this is not a bug. Thanks.
