### ISSUE TITLE
OCC fails to start on fresh 23.0.0

### ISSUE THREAD

**Issue by gorankav** [nextcloud/server#30493] opened 2022-01-05 09:10 UTC
### Steps to reproduce
1. sudo -u www-data php ./occ --help
2.
3.

### Expected behaviour
Expected to show help text.
Actually wanted to rescan files after large direct copy

### Actual behaviour
reports error:
PHP Fatal error:  Cannot use OCP\Constants as Constants because the name is already in use in /var/www/html/nextcloud/apps/groupfolders/lib/Command/ACL.php on line 35

### Server configuration

**Operating system:** Debian 11

**Web server:** Apache2 2.4.52

**Database:** MariaDB 10.5.12

**PHP version:** PHP 8.0.14 + Zend 4.0.14

**Nextcloud version:** 23.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** plain fresh

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:** 
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
_can not execute occ_
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => 'z',
  'passwordsalt' => 'x',
  'secret' => 'y',
  'trusted_domains' =>
  array (
    0 => 'cloud.indea.si',
    1 => '3.3.3.3',
    2 => '4.4.4.4',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '23.0.0.10',
  'overwrite.cli.url' => 'http://1.1.1.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '*db_pass*',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '2.2.2.2',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'cloud',
  'mail_domain' => 'indea.si',
  'maintenance' => false,
);
</details>

**Are you using external storage, if yes which one:** NFS

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

**Comment by szaimen** [comment] 2022-01-05 09:32
Duplicate of https://github.com/nextcloud/groupfolders/issues/1854

**Closed by szaimen** 2022-01-05 09:32 UTC
Labels: bug, 0. Needs triage
