### ISSUE TITLE
Deleting multiple pictures in folder fails partially due to database lock error

### ISSUE THREAD

**Issue by erikfdev** [nextcloud/server#23253] opened 2020-10-07 09:15 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have a Nextcloud folder in which the smartphone app automatically uploads the pictures taken with the smartphone
2. Using the nextcloud web interface select a set of at least 6 pictures in that folder
3. Use the menu above the file list to request the deletion of these files

### Expected behaviour
All the files should get deleted

### Actual behaviour
Some files are deleted, others not and  several popup error messages appear telling that a file could not be deleted

### Server configuration

**Operating system:**
Linux Mint 19.3 Tricia

**Web server:**
Apache 2.4.29
**Database:**
Sqlite

**PHP version:**
PHP 7.2

**Nextcloud version:** (see Nextcloud admin page)
19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC 18.x

**Where did you install Nextcloud from:**
Using the web based upgrade

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - audioplayer: 2.12.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - documentserver_community: 0.1.8
  - drawio: 0.9.7
  - emlviewer: 0.0.18
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.1
  - files_downloadactivity: 1.8.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - gallery: 18.5.0
  - groupfolders: 7.0.0
  - guests: 1.5.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - metadata: 0.12.0
  - music: 0.16.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.0.2
  - password_policy: 1.9.1
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.4
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - video_converter: 0.1.4
  - viewer: 1.3.0
  - workflowengine: 2.1.0

Disabled:
  - calendar
  - contacts
  - dropit
  - encryption
  - keeweb
  - ocr
  - photos
  - radio
  - ransomware_detection
  - user_ldap
  - user_pwauth

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.0.*",
            "invara-erde.freeddns.org",
            "homeserver.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "19.0.3.1",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
        "installed": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\Image",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpdebug": true,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "keeweb",
            "gallery"
        ],
        "updater.release.channel": "stable"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, 'local' for the folder mentioned above, and SMB for other folders.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Firefox 81.0
**Operating system:**
Linux Mint 19.3 Tricia

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"Pa0e61nntk65zTNpiYzR","level":4,"time":"2020-10-06T07:38:49+00:00","remoteAddr":"165.225.73.44","user":"theuser","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/theuser/InstantUpload/Camera/2020/10/20201004_133532.jpg","message":{"Exception":"Doctrine\\DBAL\\Exception\\LockWaitTimeoutException","Message":"An exception occurred while executing 'UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1' with params [\"files\\/518127be62d1b503fbb0b9e8602868ed\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractSQLiteDriver","type":"->","args":["An exception occurred while executing 'UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1' with params [\"files\\/518127be62d1b503fbb0b9e8602868ed\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked",{"errorInfo":["HY000",5,"database is locked"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":145,"function":"wrapException","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver"},{"errorInfo":["HY000",5,"database is locked"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"An exception occurred while executing 'UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1' with params [\"files\\/518127be62d1b503fbb0b9e8602868ed\"]:\n\nSQLSTATE[HY000]: General error: 5 database is locked"]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1063,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver"},{"errorInfo":["HY000",5,"database is locked"],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1",{"1":"files/518127be62d1b503fbb0b9e8602868ed"}]},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1",["files/518127be62d1b503fbb0b9e8602868ed"],[]]},{"file":"/var/www/nextcloud/lib/private/Lock/DBLockingProvider.php","line":229,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1",["files/518127be62d1b503fbb0b9e8602868ed"]]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":784,"function":"releaseLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files/518127be62d1b503fbb0b9e8602868ed",2]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":2036,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":2088,"function":"unlockPath","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,false]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1165,"function":"unlockFile","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg",2]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":718,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["unlink","/InstantUpload/Camera/2020/10/20201004_133532.jpg",["delete"]]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":458,"function":"unlink","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":183,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":295,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files/theuser/InstantUpload/Camera/2020/10/20201004_133532.jpg"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:DELETE",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php","Line":25,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[HY000]: General error: 5 database is locked","Code":"HY000","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1056,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["files/518127be62d1b503fbb0b9e8602868ed"]]},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1",["files/518127be62d1b503fbb0b9e8602868ed"],[]]},{"file":"/var/www/nextcloud/lib/private/Lock/DBLockingProvider.php","line":229,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1",["files/518127be62d1b503fbb0b9e8602868ed"]]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":784,"function":"releaseLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files/518127be62d1b503fbb0b9e8602868ed",2]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":2036,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":2088,"function":"unlockPath","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,false]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1165,"function":"unlockFile","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg",2]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":718,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["unlink","/InstantUpload/Camera/2020/10/20201004_133532.jpg",["delete"]]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":458,"function":"unlink","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":183,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":295,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files/theuser/InstantUpload/Camera/2020/10/20201004_133532.jpg"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:DELETE",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":119,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY000]: General error: 5 database is locked","Code":"HY000","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","line":117,"function":"execute","class":"PDOStatement","type":"->","args":[["files/518127be62d1b503fbb0b9e8602868ed"]]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php","line":1056,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["files/518127be62d1b503fbb0b9e8602868ed"]]},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":214,"function":"executeUpdate","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1",["files/518127be62d1b503fbb0b9e8602868ed"],[]]},{"file":"/var/www/nextcloud/lib/private/Lock/DBLockingProvider.php","line":229,"function":"executeUpdate","class":"OC\\DB\\Connection","type":"->","args":["UPDATE \"oc_file_locks\" SET \"lock\" = 0 WHERE \"key\" = ? AND \"lock\" = -1",["files/518127be62d1b503fbb0b9e8602868ed"]]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":784,"function":"releaseLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files/518127be62d1b503fbb0b9e8602868ed",2]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":605,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":2036,"function":"releaseLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":2088,"function":"unlockPath","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg",2,false]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1165,"function":"unlockFile","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg",2]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":718,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["unlink","/InstantUpload/Camera/2020/10/20201004_133532.jpg",["delete"]]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":458,"function":"unlink","class":"OC\\Files\\View","type":"->","args":["/InstantUpload/Camera/2020/10/20201004_133532.jpg"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":183,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":295,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files/theuser/InstantUpload/Camera/2020/10/20201004_133532.jpg"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:DELETE",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php","Line":117}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"19.0.3.1"}
</details>

**Comment by acsfer** [comment] 2020-10-07 09:18
Duplicate of https://github.com/nextcloud/server/issues/22482

**Comment by erikfdev** [comment] 2020-10-07 18:19
@acsfer are you sure this is a duplicate? The reported exception is Doctrine\DBAL\Exception\LockWaitTimeoutException while in the other issue report it is Doctrine\DBAL\Exception\DeadlockException.
Furthermore, the sql statement in my case is for the oc_file_locks table while in the other issue it is the oc_filecache table.

**Comment by acsfer** [comment] 2020-10-07 18:50
You're right, probably not related. Let's reopen it.

**Comment by kesselb** [comment] 2020-10-07 21:31
Please take a look at https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems to have a brief understanding how SQLite is different to MySQL and PostgreSQL.

I'm not sure if we accept bug reports for concurrency issues with SQLite as database backend. If you use at least one sync client your setup is not a minimal installation anymore.

**Comment by nickvergessen** [comment] 2020-10-07 22:46
Closing as per above

**Comment by nickvergessen** [comment] 2020-10-07 22:47
Although the error message is different, it might be fixed by the same issue.
If not, please migrate to another database

**Closed by nickvergessen** 2020-10-07 22:46 UTC
Labels: 0. Needs triage, bug
