### ISSUE TITLE
[Bug]: Shared folders/files icons not showing up instantly, need to reload the page

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [nextcloud/server#43494] opened 2024-02-09 21:40 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [ ] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

So I recently moved my setup from snap to docker to be up to date. I had to use the data migration app since I was moving from snap to docker with postgres. It was a nightmare but now that it is done and I am on Nextcloud Hub 7(28.0.2) 

The issue may be a regression of a bug that was reported and fixed last year. https://github.com/nextcloud/server/issues/26969 https://github.com/nextcloud/server/pull/38420

We use the share feature all the time and the only way to get the link for a folder is to refresh the page and for a file you can select a different file and then go back to the one you just shared.

### Steps to reproduce

1. In the Nextcloud web interface click show sharing options on any synced file or folder.
2. In the options menu click the + and then click create share

### Expected behavior

A) A share to be created and an icon to appear so you can click it and copy the share.
or
B) A share to be created and automatically copied and ready to paste as well as the link to be shown. (This was the behaviour of our snap install)

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trused_proxies": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "dbtype": "pgsql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/"***REMOVED SENSITIVE VALUE***"",
        "overwriteprotocol": "https",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "default_phone_region": "CA",
        "default_locale": "en_CA",
        "default_language": "en",
        "filelocking.enabled": true,
        "memories.exiftool": "\/config\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-musl",
        "memories.vod.path": "\/config\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "enabledPreviewProviders": [
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Image",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie"
        ],
        "preview_max_x": 512,
        "preview_max_y": 512,
        "app_install_overwrite": [
            "facerecognition",
            "breezedark"
        ],
        "upgrade.disable-web": true,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "data-fingerprint": "58bb666a1d9a97a019d9d8135fc4efd6"
    }
}
```

### List of activated Apps

```shell
- calendar: 4.6.4
  - cloud_federation_api: 1.11.0
  - cloud_py_api: 0.1.9
  - contacts: 5.5.1
  - dav: 1.29.1
  - deck: 1.12.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_3dmodelviewer: 0.0.12
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - fileslibreofficeedit: 1.1.0
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mediadc: 0.3.8
  - memories: 6.2.2
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - photos: 2.4.0
  - previewgenerator: 5.4.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - activity: 2.20.0 (installed 2.20.0)
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - comments: 1.18.0 (installed 1.18.0)
  - contactsinteraction: 1.9.0 (installed 1.9.0)
  - dashboard: 7.8.0 (installed 7.8.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.18.0)
  - files_reminders: 1.1.0 (installed 1.1.0)
  - firstrunwizard: 2.17.0 (installed 2.17.0)
  - nextcloud_announcements: 1.17.0 (installed 1.17.0)
  - password_policy: 1.18.0 (installed 1.18.0)
  - privacy: 1.12.0 (installed 1.12.0)
  - recommendations: 2.0.0 (installed 2.0.0)
  - related_resources: 1.3.0 (installed 1.3.0)
  - sharebymail: 1.18.0 (installed 1.18.0)
  - support: 1.11.0 (installed 1.11.0)
  - survey_client: 1.16.0 (installed 1.16.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.18.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_migration: 5.0.0 (installed 5.0.0)
  - user_status: 1.8.1 (installed 1.8.1)
  - weather_status: 1.8.0 (installed 1.8.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by storrington** [comment] 2024-02-12 15:25
I run two instances of Nextcloud, one in snap and one in Docker, and I've been able to replicate the error on both. I noticed it first on the server in which expiry date was enforced. When I turn expiry off for shares in the admin panel the problem goes away. When I add expiry option on the server that didn't have the problem the issue appears.

Since it's been confusing my users I'll be disabling enforced expiry until this is fixed.

**Comment by Intrinsically-Sublime** [comment] 2024-02-13 06:32
Thank you for the hint. Enforcing expiry is actually something I only turned on since updating to the Docker install.

I can also confirm that disabling enforce returns the expected behaviour or creating and coping the link as soon as you click the +

**Comment by keros** [comment] 2024-02-15 16:10
Same problem here.
If password is enforced or expiry date then the UI will not update until you relaod the page (also you can not see the share link until page reload).

**Comment by cloudy3000** [comment] 2024-02-16 12:36
I have the same problem.

After a number of attempts, I think I have found the decisive factor. It has something to do with the context menu during creation.

When I create a share and no context menu is displayed during creation, the correct display occurs immediately. If, for example, the share settings recommend setting a password or an expiration date is used, the context menu appears while the share is being created.

**Comment by koopmann** [comment] 2024-02-21 09:08
Same problem at our instance running 28.0.2, if password enforce is off (no dialogs) the icon for copy the shared link appears without reloading the page.

**Comment by keros** [comment] 2024-03-04 09:07
I just updated to version 28.0.3.
It looks like the bug got half fixed. If I create now a password protected share the context menu on the right side gets updated.
A button to copy the link appears and it says that the share was created.

In the file list in the middle of the screen nothing gets updated. The view of the folder stays the same until you reload the page or enter a folder and go back.
I'm not entirely sure if this is the same behaviour as before the 28.x update. But if "easily" possible it would be nice that also the file list gets updated if a share gets created/removed.

**Comment by Fenn-CS** [comment] 2024-04-15 14:47
Duplicate of : https://github.com/nextcloud/server/issues/44032

**Closed** 2024-04-15 14:48 UTC
Labels: bug, feature: sharing, 0. Needs triage, feature: files, 28-feedback
