### ISSUE TITLE
Files from partially restored folder are missing version history 

### ISSUE THREAD

**Issue by jonny08152** [nextcloud/server#21567] opened 2020-06-24 17:00 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to https://try.nextcloud.com
2. Edit a file in a folder (e.g. /Documents/Example.md) to create a new version
3. See that new version in the version history in the file details
4. Delete the whole folder (e.g. /Documents)
5. Go to trash, restore only the edited file (e.g. /Trash/Documents/Example.md), not the folder
6. File gets restored in the root directory (e.g. /Example.md)
7. See that there is no additional version visible in the file details of the restored file
8. Restore the rest of the folder as whole (e.g. /Trash/Documents)
9. See that there are still no old versions of the single restored file (e.g. /Example.md)
10. Move the single file to the original location in the restored folder (e.g. /Example.md -> /Documents/Example.md)
11. See that there are all the old versions now available for the moved file

### Expected behaviour
Old versions of the restored file should be present, even if restored to a different location (which cannot be chosen anyway)

### Actual behaviour
Restored file has no old versions available until whole parent folder is also restored and file is manually moved back to its original location

### Server configuration
Tried on Nextcloud 19.0.0 official Docker image (Image ID: 6375cff75f7b)
Also reproducible on https://try.nextcloud.com

**Operating system:**
-
**Web server:**
apache
**Database:**
postgres
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
19.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
official Docker image nextcloud:19.0.0 (Image ID: 6375cff75f7b)

### Client configuration
**Browser:**
Firefox 77.0.1
**Operating system:**
Arch Linux

**Comment by kesselb** [comment] 2020-06-24 20:54
cc @icewind1991 @rullzer

**Comment by szaimen** [comment] 2021-06-02 13:35
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 13:35 UTC
Labels: 0. Needs triage, 19-feedback, bug, feature: versions
