### ISSUE TITLE
[Bug]: `NoUserException` `Backends provided no user object Backends provided no user object for X`

### ISSUE THREAD

**Issue by amitash** [nextcloud/server#47244] opened 2024-08-14 19:22 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have combed through other GitHub issues with a similar error that is related to the `groupfolders` app. I, however, have never installed the app and the error I see is, I think, with the `files` app instead. I am unable to find what could reproduce this error but following is a log (there are >3000 of these accumulating every 15 minutes).

**NoUserException** Backends provided no user object Backends provided no user object for 1
```
{
  "reqId": "IoKquxdANeD6VE9b8klD",
  "level": 3,
  "time": "2024-08-14T18:52:03+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "files",
  "method": "",
  "url": "--",
  "message": "Backends provided no user object for 1",
  "userAgent": "--",
  "version": "29.0.4.1",
  "exception": {
    "Exception": "OC\\User\\NoUserException",
    "Message": "Backends provided no user object",
    "Code": 0,
    "Trace": [
      {
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\Root",
        "type": "->",
        "args": [
          "1"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Node/LazyFolder.php",
        "line": 84,
        "function": "call_user_func_array",
        "args": [
          [
            [
              "OC\\Files\\Node\\Root"
            ],
            "getUserFolder"
          ],
          [
            "1"
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Node/LazyRoot.php",
        "line": 53,
        "function": "__call",
        "class": "OC\\Files\\Node\\LazyFolder",
        "type": "->",
        "args": [
          "getUserFolder",
          [
            "1"
          ]
        ]
      },
      {
        "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php",
        "line": 558,
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\LazyRoot",
        "type": "->",
        "args": [
          "1"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php",
        "line": 577,
        "function": "getFileFromId",
        "class": "OCA\\Files_FullTextSearch\\Service\\FilesService",
        "type": "->",
        "args": [
          "1",
          151716
        ]
      },
      {
        "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php",
        "line": 1288,
        "function": "getFileFromIndex",
        "class": "OCA\\Files_FullTextSearch\\Service\\FilesService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php",
        "line": 707,
        "function": "updateDirectoryContentIndex",
        "class": "OCA\\Files_FullTextSearch\\Service\\FilesService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Provider/FilesProvider.php",
        "line": 314,
        "function": "updateDocument",
        "class": "OCA\\Files_FullTextSearch\\Service\\FilesService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/fulltextsearch/lib/Service/IndexService.php",
        "line": 409,
        "function": "updateDocument",
        "class": "OCA\\Files_FullTextSearch\\Provider\\FilesProvider",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php",
        "line": 109,
        "function": "updateDocument",
        "class": "OCA\\FullTextSearch\\Service\\IndexService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php",
        "line": 77,
        "function": "liveCycle",
        "class": "OCA\\FullTextSearch\\Cron\\Index",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/Job.php",
        "line": 80,
        "function": "run",
        "class": "OCA\\FullTextSearch\\Cron\\Index",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 102,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 92,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 177,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      }
    ],
    "File": "/var/www/html/lib/private/Files/Node/Root.php",
    "Line": 370,
    "message": "Backends provided no user object for 1",
    "exception": [],
    "CustomMessage": "Backends provided no user object for 1"
  },
  "id": "66bcfe6aa36fa"
}
```

I can suppress this error if I disable the `Full text search` app.

To my knowledge, other than filling up the log files, this error has not caused any other problems.

A strange this I noticed was when I run a `php occ user:list`, I get the following:

```
- username1: User  1 Full Name
- username2: User 2 Full Name
``` 

However, when I run a `php occ user:report`, I get that there are 3 active users. 

```
+------------------+---+
| Account Report   |   |
+------------------+---+
| Database         | 2 |
|                  |   |
| total users      | 2 |
|                  |   |
| user directories | 1 |
| active users     | 3 |
| disabled users   | 0 |
+------------------+---+

```

I have no clue how this third user has been created. I have, in the recent past, created and deleted an `oauth client`.

While trying to get more info for this error, I noticed that there were 3 directories in the files folder (the directories created for each user by nextcloud). As expected, two of these were `username1` and `username2`, but there was a third one called `1` which I deleted but that hasn't suppressed the error. Please note that the error was already occurring for multiple days before I deleted that stray user directory.

### Steps to reproduce

Unfortunately, I do not know how to reproduce this error.

### Expected behavior

There should be no NoUserException error.

### Installation method

Other Community project

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "cloud.amitash.in",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.amitash.in"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.4.1",
        "overwrite.cli.url": "https:\/\/cloud.amitash.in\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 3,
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": 10485760,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "jpeg_quality": 60,
        "enabledPreviewProviders": [
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Krita",
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF"
        ],
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": 30,
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "updatedirectory": "\/nc-updater",
        "maintenance_window_start": 100,
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 3600,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_key": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "",
        "memories.db.triggers.fcu": true,
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-musl",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "default_phone_region": "\u201cDK\u201d",
        "memories.gis_type": 2,
        "memories.vod.disable": false,
        "memories.vod.connect": "nextcloud-memories-go-vod:47788",
        "memories.vod.bind": "nextcloud-memories-go-vod:47788",
        "memories.vod.external": true,
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.nvenc": true,
        "memories.vod.nvenc.temporal_aq": true,
        "memories.vod.use_gop_size": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.19.0
  - app_api: 3.0.1
  - assistant: 1.1.0
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.15
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - files: 2.1.0
  - files_antivirus: 5.5.7
  - files_downloadlimit: 2.0.0
  - files_fulltextsearch: 29.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - fulltextsearch: 29.0.0
  - fulltextsearch_elasticsearch: 29.0.1
  - integration_openai: 2.0.3
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.7
  - memories: 7.3.1
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - notify_push: 0.7.0
  - oauth2: 1.17.0
  - oidc: 0.9.2
  - password_policy: 1.19.0
  - previewgenerator: 5.6.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recognize: 7.1.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.4
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.7
  - support: 1.12.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - user_status: 1.9.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - activity: 2.21.1 (installed 2.21.1)
  - circles: 29.0.0-dev (installed 29.0.0-dev)
  - contactsinteraction: 1.10.0 (installed 1.10.0)
  - encryption: 2.17.0
  - federation: 1.19.0 (installed 1.19.0)
  - files_external: 1.21.0 (installed 1.21.0)
  - photos: 2.5.0 (installed 2.5.0)
  - survey_client: 1.17.0 (installed 1.17.0)
  - user_ldap: 1.20.0
  - weather_status: 1.9.0 (installed 1.9.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"pdMPROXa4U1ezux2JjD5","level":3,"time":"2024-08-14T19:22:04+00:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"Backends provided no user object for 1","userAgent":"--","version":"29.0.4.1","exception":{"Exception":"OC\\User\\NoUserException","Message":"Backends provided no user object","Code":0,"Trace":[{"function":"getUserFolder","class":"OC\\Files\\Node\\Root","type":"->","args":["1"]},{"file":"/var/www/html/lib/private/Files/Node/LazyFolder.php","line":84,"function":"call_user_func_array","args":[[["OC\\Files\\Node\\Root"],"getUserFolder"],["1"]]},{"file":"/var/www/html/lib/private/Files/Node/LazyRoot.php","line":53,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->","args":["getUserFolder",["1"]]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":558,"function":"getUserFolder","class":"OC\\Files\\Node\\LazyRoot","type":"->","args":["1"]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":577,"function":"getFileFromId","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["1",151716]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":1288,"function":"getFileFromIndex","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php","line":707,"function":"updateDirectoryContentIndex","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/files_fulltextsearch/lib/Provider/FilesProvider.php","line":314,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Service\\FilesService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/Service/IndexService.php","line":409,"function":"updateDocument","class":"OCA\\Files_FullTextSearch\\Provider\\FilesProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php","line":109,"function":"updateDocument","class":"OCA\\FullTextSearch\\Service\\IndexService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php","line":77,"function":"liveCycle","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->","args":[]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\FullTextSearch\\Cron\\Index","type":"->","args":[null]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/cron.php","line":177,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]}],"File":"/var/www/html/lib/private/Files/Node/Root.php","Line":370,"message":"Backends provided no user object for 1","exception":[],"CustomMessage":"Backends provided no user object for 1"},"id":"66bd03e937a9f"}
```

**Comment by msullivan-lc** [comment] 2024-08-22 15:12
I'm seeing the same/similar error message on my installation of AIO. I recently deleted a user but transferred all their files to another user before removing them. The error only exists for the deleted user. I concur, it looks like it is a background job.

Here's a copy of the raw log entry.

```
{
 "reqId": "FsimdfJzMJCT58wFLNfq",
 "level": 3,
 "time": "2024-08-22T15:02:41+00:00",
 "remoteAddr": "",
 "user": "--",
 "app": "files",
 "method": "",
 "url": "--",
 "message": "Backends provided no user object for <<DELETED USERNAME>>",
 "userAgent": "--",
 "version": "29.0.4.1",
 "exception": {
 "Exception": "OC\\User\\NoUserException",
 "Message": "Backends provided no user object",
 "Code": 0,
 "Trace": [{ "function": "getUserFolder", "class": "OC\\Files\\Node\\Root", "type": "->", "args": ["<<DELETED USERNAME>>"] }, {
 "file": "/var/www/html/lib/private/Files/Node/LazyFolder.php",
 "line": 84,
 "function": "call_user_func_array",
 "args": [
 [
 ["OC\\Files\\Node\\Root"], "getUserFolder"
 ],
 ["<<DELETED USERNAME>>"]
 ]
 }, { "file": "/var/www/html/lib/private/Files/Node/LazyRoot.php", "line": 53, "function": "__call", "class": "OC\\Files\\Node\\LazyFolder", "type": "->", "args": ["getUserFolder", ["<<DELETED USERNAME>>"]] }, { "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php", "line": 558, "function": "getUserFolder", "class": "OC\\Files\\Node\\LazyRoot", "type": "->", "args": ["<<DELETED USERNAME>>"] }, { "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php", "line": 577, "function": "getFileFromId", "class": "OCA\\Files_FullTextSearch\\Service\\FilesService", "type": "->", "args": ["<<DELETED USERNAME>>", 5832] }, { "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php", "line": 1288, "function": "getFileFromIndex", "class": "OCA\\Files_FullTextSearch\\Service\\FilesService", "type": "->", "args": ["*** sensitive parameters replaced ***"] }, { "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Service/FilesService.php", "line": 707, "function": "updateDirectoryContentIndex", "class": "OCA\\Files_FullTextSearch\\Service\\FilesService", "type": "->", "args": ["*** sensitive parameters replaced ***"] }, { "file": "/var/www/html/custom_apps/files_fulltextsearch/lib/Provider/FilesProvider.php", "line": 314, "function": "updateDocument", "class": "OCA\\Files_FullTextSearch\\Service\\FilesService", "type": "->", "args": ["*** sensitive parameters replaced ***"] }, { "file": "/var/www/html/custom_apps/fulltextsearch/lib/Service/IndexService.php", "line": 409, "function": "updateDocument", "class": "OCA\\Files_FullTextSearch\\Provider\\FilesProvider", "type": "->", "args": ["*** sensitive parameters replaced ***"] }, { "file": "/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php", "line": 109, "function": "updateDocument", "class": "OCA\\FullTextSearch\\Service\\IndexService", "type": "->", "args": ["*** sensitive parameters replaced ***"] }, { "file": "/var/www/html/custom_apps/fulltextsearch/lib/Cron/Index.php", "line": 77, "function": "liveCycle", "class": "OCA\\FullTextSearch\\Cron\\Index", "type": "->", "args": [] }, { "file": "/var/www/html/lib/public/BackgroundJob/Job.php", "line": 80, "function": "run", "class": "OCA\\FullTextSearch\\Cron\\Index", "type": "->", "args": [null] }, {
 "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
 "line": 102,
 "function": "start",
 "class": "OCP\\BackgroundJob\\Job",
 "type": "->",
 "args": [
 ["OC\\BackgroundJob\\JobList"]
 ]
 }, {
 "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
 "line": 92,
 "function": "start",
 "class": "OCP\\BackgroundJob\\TimedJob",
 "type": "->",
 "args": [
 ["OC\\BackgroundJob\\JobList"]
 ]
 }, {
 "file": "/var/www/html/cron.php",
 "line": 177,
 "function": "execute",
 "class": "OCP\\BackgroundJob\\TimedJob",
 "type": "->",
 "args": [
 ["OC\\BackgroundJob\\JobList"]
 ]
 }],
 "File": "/var/www/html/lib/private/Files/Node/Root.php",
 "Line": 370,
 "message": "Backends provided no user object for <<DELETED USERNAME>>",
 "exception": [],
 "CustomMessage": "Backends provided no user object for <<DELETED USERNAME>>"
 },
 "id": "66c7532f24c6f"
}
```

Let me know if I can help in any other way.

**Comment by DonZalmrol** [comment] 2024-09-06 08:12
I'm experiencing the exact same issue, however on my instance its for MS LDAP and an existing user (my user)
https://www.reddit.com/r/NextCloud/comments/1fa6w4w/comment/llr52bc/?context=3

**Comment by thompol** [comment] 2024-09-15 15:20
Experiencing exactly the same problem here. User was logged in through OAuth2 with the `nextcloud-social-login` app.

**Comment by thompol** [comment] 2024-09-15 15:21
Seems to be a duplicate of #46664.

**Comment by amitash** [comment] 2024-09-21 07:41
I have upgraded my AIO to NC30 and this issue disappeared.

**Comment by joshtrichards** [comment] 2024-09-25 15:56
Duplicate of #46664

**Closed by joshtrichards** 2024-09-25 15:56 UTC
Labels: bug, 0. Needs triage, feature: users and groups, 29-feedback

**Comment by gork-us** [comment] 2024-12-31 18:20
Having the same issue, Nextcloud 30.0.4

**Comment by hcderaad** [comment] 2025-02-03 14:39
I have the same issue, but without having full text search enabled in 30.0.5, following other apps:

php occ app:list
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 4.0.5
  - approval: 2.1.0
  - bruteforcesettings: 3.0.0
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_accesscontrol: 1.20.1
  - files_automatedtagging: 1.20.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - groupfolders: 18.0.9
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - encryption: 2.18.0
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
  - weather_status: 1.10.0 (installed 1.9.0)

One log entry of such an event:

Feb 3, 2025, 11:12:01 AM

Copy raw entry

Copy formatted entry

Hide exception details
NoUserException
Backends provided no user object
OC\Files\Node\Root->getUserFolder(
  null
)
/var/www/html/lib/private/Files/Node/LazyFolder.php
Line 64
undefinedundefinedcall_user_func_array(
  [
    {
      "_class_": "OC\\Files\\Node\\Root"
    },
    "getUserFolder"
  ],
  [
    null
  ]
)
/var/www/html/lib/private/Files/Node/LazyRoot.php
Line 38
OC\Files\Node\LazyFolder->__call(
  "getUserFolder",
  [
    null
  ]
)
/var/www/html/custom_apps/approval/lib/Activity/ApprovalProvider.php
Line 125
OC\Files\Node\LazyRoot->getUserFolder(
  null
)
/var/www/html/apps/activity/lib/GroupHelper.php
Line 59
OCA\Approval\Activity\ApprovalProvider->parse(
  "en_GB",
  {
    "_class_": "OC\\Activity\\Event"
  },
  {
    "_class_": "OC\\Activity\\Event"
  }
)
/var/www/html/apps/activity/lib/MailQueueHandler.php
Line 289
OCA\Activity\GroupHelper->addEvent(
  456,
  {
    "_class_": "OC\\Activity\\Event"
  }
)
/var/www/html/apps/activity/lib/MailQueueHandler.php
Line 106
OCA\Activity\MailQueueHandler->sendEmailToUser(
  "XXXXXXXXXXXX",
  "XXXXXXXXXXXXXXX",
  "en_GB",
  "Europe/London",
  1738577520
)
/var/www/html/apps/activity/lib/BackgroundJob/EmailNotification.php
Line 41
OCA\Activity\MailQueueHandler->sendEmails(
  500,
  1738577520
)
/var/www/html/lib/public/BackgroundJob/Job.php
Line 61
OCA\Activity\BackgroundJob\EmailNotification->run(
  null
)
/var/www/html/lib/public/BackgroundJob/TimedJob.php
Line 88
OCP\BackgroundJob\Job->start(
  {
    "_class_": "OC\\BackgroundJob\\JobList"
  }
)
/var/www/html/lib/public/BackgroundJob/TimedJob.php
Line 75
OCP\BackgroundJob\TimedJob->start(
  {
    "_class_": "OC\\BackgroundJob\\JobList"
  }
)
/var/www/html/cron.php
Line 162
OCP\BackgroundJob\TimedJob->execute(
  {
    "_class_": "OC\\BackgroundJob\\JobList"
  }
)
Raw log entry
{
  "reqId": "2WzDEAP3eS8uw0mNeleE",
  "level": 3,
  "time": "2025-02-03T10:12:01+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "activity",
  "method": "",
  "url": "--",
  "message": "Error while parsing activity event",
  "userAgent": "--",
  "version": "30.0.5.1",
  "exception": {
    "Exception": "OC\\User\\NoUserException",
    "Message": "Backends provided no user object",
    "Code": 0,
    "Trace": [
      {
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\Root",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Node/LazyFolder.php",
        "line": 64,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "_class_": "OC\\Files\\Node\\Root"
            },
            "getUserFolder"
          ],
          [
            null
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/private/Files/Node/LazyRoot.php",
        "line": 38,
        "function": "__call",
        "class": "OC\\Files\\Node\\LazyFolder",
        "type": "->",
        "args": [
          "getUserFolder",
          [
            null
          ]
        ]
      },
      {
        "file": "/var/www/html/custom_apps/approval/lib/Activity/ApprovalProvider.php",
        "line": 125,
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\LazyRoot",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/html/apps/activity/lib/GroupHelper.php",
        "line": 59,
        "function": "parse",
        "class": "OCA\\Approval\\Activity\\ApprovalProvider",
        "type": "->",
        "args": [
          "en_GB",
          {
            "_class_": "OC\\Activity\\Event"
          },
          {
            "_class_": "OC\\Activity\\Event"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/activity/lib/MailQueueHandler.php",
        "line": 289,
        "function": "addEvent",
        "class": "OCA\\Activity\\GroupHelper",
        "type": "->",
        "args": [
          456,
          {
            "_class_": "OC\\Activity\\Event"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/activity/lib/MailQueueHandler.php",
        "line": 106,
        "function": "sendEmailToUser",
        "class": "OCA\\Activity\\MailQueueHandler",
        "type": "->",
        "args": [
          "luke.gymer",
          "luke.gymer@tetratech.com",
          "en_GB",
          "Europe/London",
          1738577520
        ]
      },
      {
        "file": "/var/www/html/apps/activity/lib/BackgroundJob/EmailNotification.php",
        "line": 41,
        "function": "sendEmails",
        "class": "OCA\\Activity\\MailQueueHandler",
        "type": "->",
        "args": [
          500,
          1738577520
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/Job.php",
        "line": 61,
        "function": "run",
        "class": "OCA\\Activity\\BackgroundJob\\EmailNotification",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 88,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          {
            "_class_": "OC\\BackgroundJob\\JobList"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/TimedJob.php",
        "line": 75,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "_class_": "OC\\BackgroundJob\\JobList"
          }
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 162,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "_class_": "OC\\BackgroundJob\\JobList"
          }
        ]
      }
    ],
    "File": "/var/www/html/lib/private/Files/Node/Root.php",
    "Line": 345,
    "message": "Error while parsing activity event",
    "exception": [],
    "CustomMessage": "Error while parsing activity event"
  },
  "id": "67a0d459cd1a4"
}

**Comment by joshtrichards** [comment] 2025-02-03 16:20
@hcderaad Your issue appears unrelated; it's associated with the `approval` app. Likely similar underlying cause as nextcloud/approval#29
