### ISSUE TITLE
[IMPROVEMENT] Add Space Used/Free Information to Monitoring

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8722] opened 2018-03-07 20:31 UTC
I find the Monitoring page of Nextcloud pretty helpful but I am a bit confused as to why I cannot see how much space I have used and how much total space that there is and free space remaining. I would like to suggest adding this information below "Users" and "Files" in the "Storage" section. This would be a tremendous help.

**Comment by MorrisJobke** [comment] 2018-03-07 22:11
Duplicate of https://github.com/nextcloud/serverinfo/issues/11

**Comment by MorrisJobke** [comment] 2018-03-07 22:11
See also https://github.com/nextcloud/serverinfo/issues/46

**Closed by MorrisJobke** 2018-03-07 22:11 UTC
