### ISSUE TITLE
Optional setting to add extended user personal info as admin

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#16908] opened 2019-08-28 07:01 UTC
**Is your feature request related to a problem? Please describe.**
When an organisation is deploying NC it may want to deploy 2FA - at which point it needs to ensure the required 2FA information is present in the user's "personal info" section when the user is created; as it stands you can enable 2FA but not add the information required to make it work.

**Describe the solution you'd like**
The ability to extend user account information from the admin side to include 2FA type information. This might be controlled/activated by admins deploying and configuring a 2FA app (i.e. will require the app to be modified to take account of the functionality).

**Describe alternatives you've considered**
Obviously one option is just to create users as normal and then add the additional information (and change when required) via SQL.

**Comment by szaimen** [comment] 2021-05-26 11:26
If I read correctly is this a duplicate of https://github.com/nextcloud/server/issues/13395 -> closing.

**Closed by szaimen** 2021-05-26 11:26 UTC
Labels: 0. Needs triage, enhancement

**Comment by putt1ck** [comment] 2021-05-26 11:33
Not sure that ticket currently provides for adding the information required as an admin (which is necessary in a corporate environment). We solved the particular client's issue by introducing SSO (CAS) with 2FA so it's dealt with outside of NC.
