### ISSUE TITLE
When coping file larger than 1MB to NextCloud's WebDAV using Finder in MacOS, it prompt Error Code -36.

### ISSUE THREAD

**Issue by gjj2828** [nextcloud/server#13999] opened 2019-02-03 02:48 UTC
Can't copy file larger than 1MB to NextCloud's WebDAV using Finder in MacOS. It will prompt:

> The Finder can’t complete the operation because some data in “bin.zip” can’t be read or written.
(Error code -36)

But if the file size is smaller than 1MB, It will be OK.

And I can copy file larger than 1MB to NextCloud's WebDAV using Cyberduck with no problem.

I have searched the logs of NextCloud, php-fom and Nginx, but found nothing for that.

Further more, I can copy file larger than 1MB to NextCloud's WebDAV using Explorer in Windows.

NextCloud Version: 15.0.2
php-fpm Version: 7.2.10
Nginx Version: 1.14.0
OS: Ubuntu 18.04

**Comment by shiquan-gh** [comment] 2019-04-05 13:29
Same issue here with 15.0.5.3, seems a very old issue inherited form [owncloud 5.0](https://forum.owncloud.org/viewtopic.php?t=11633)

**Comment by skjnldsv** [comment] 2020-03-10 08:37
https://github.com/owncloud/core/issues/2010
https://github.com/owncloud/core/pull/11053/files

As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-03-10 08:37 UTC
Labels: 0. Needs triage, bug

**Comment by waylenwasywas** [comment] 2023-03-20 23:24
I am currently having this issue within my installation
