### ISSUE TITLE
Make links to image/file preview portable between tabs or users

### ISSUE THREAD

**Issue by mahnunchik** [nextcloud/server#6463] opened 2017-09-12 11:18 UTC
Make links to image/file preview portable between tabs or users.

### Steps to reproduce
1. Open image in shared folder. Url will be like following: `http://example.com/index.php/apps/files/?dir=/test&fileid=100#/test/Layout.png`
2. Copy link.
3. Open in different tab or under another user that has access to the folder.

### Expected behaviour
Image preview opens.

### Actual behaviour
File listing opens.

### Server configuration

**Operating system**: Ubuntu (Docker image `nextcloud:12.0.2`)

**Web server:** Apache

**Database:** mariadb

**PHP version:** `php:7.1-apache`

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** Docker hub

**Comment by MorrisJobke** [comment] 2017-09-12 14:49
Duplicate of #5475

**Closed by MorrisJobke** 2017-09-12 14:49 UTC

**Comment by mahnunchik** [comment] 2017-09-12 15:47
Hi @MorrisJobke it is not duplicate because I mean not a sharing link. I mean usual URL in the browser `http://example.com/index.php/apps/files/?dir=/test&fileid=100#/test/Layout.png`.

**Comment by MorrisJobke** [comment] 2017-09-13 08:44
> Hi @MorrisJobke it is not duplicate because I mean not a sharing link. I mean usual URL in the browser http://example.com/index.php/apps/files/?dir=/test&fileid=100#/test/Layout.png.

We should add this to all links. And once we do it, it will be in place for share links as well as internal links 😉

**Comment by mahnunchik** [comment] 2017-09-13 08:51
@MorrisJobke Great! Thank you for the clarification :+1:
