### ISSUE TITLE
[Bug]: Cannot search for apps on discover page

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#45451] opened 2024-05-22 13:13 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On the discover page of apps, which is the default page, it is not possible to search for apps. You have to first jump to e.g. "Your apps"

### Steps to reproduce

1. Via the upper right menu, got to "Apps"
2. Open the search
3. Search for an app

### Expected behavior

Matching apps are found and shown

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-07-29 16:54
Duplicate of #45558

(this one came first but that one has the more active discussion)

**Closed by joshtrichards** 2024-07-29 16:54 UTC
Labels: bug, 0. Needs triage, feature: apps management, feature: search, 30-feedback
