### ISSUE TITLE
Video Playback - White Screen

### ISSUE THREAD

**Issue by benyanke** [nextcloud/server#3015] opened 2017-01-10 15:41 UTC
### Steps to reproduce
1. Upload Video
2. Play Video
3. Video playback is white. Audio still plays.
![image](https://cloud.githubusercontent.com/assets/4274911/21812460/a429ecfe-d718-11e6-9efa-0f395c5e5195.png)

### Expected behaviour
Video window should contain the video content.

### Actual behaviour
Video playback is white.

### Server configuration
**Operating system**: Ubuntu 16.04.1

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.x

**Nextcloud version:** (see Nextcloud admin page) 
**Where did you install Nextcloud from:** Nextcloud Site

```
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.1
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oczmq41kthi1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.publicserver.xyz"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.publicserver.xyz",
        "dbtype": "mysql",
        "version": "9.1.2.2",
        "dbname": "NextCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome
**Operating system:** Ubuntu 16.04.1

**Comment by nickvergessen** [comment] 2017-01-11 11:44
Can you please report your issue in https://github.com/nextcloud/files_videoplayer ?
Thanks

**Comment by benyanke** [comment] 2017-01-11 13:35
Thanks, opened a ticket here:

https://github.com/nextcloud/files_videoplayer/issues/16

**Comment by Instagit** [comment] 2017-01-12 08:44
@nickvergessen The files_videoplayer extension isn't used when playing videos via share links (that page uses the default HTML5 player), but I've seen similar problems and will try to find what's wrong :)

**Comment by nickvergessen** [comment] 2017-01-12 09:24
Ah okay

**Comment by juliushaertl** [comment] 2018-01-20 11:13
Closing as a duplicate of https://github.com/nextcloud/server/issues/604 since it most likely is an issue with the browser not supporting the video codec there.

Please check https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility for supported videofiles on your browser version.

**Closed by juliushaertl** 2018-01-20 11:13 UTC
Labels: bug, feature: files, feature: sharing
