### ISSUE TITLE
Show app details in apps management via right sidebar

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2138] opened 2016-11-15 13:43 UTC
Idea to improve the apps handling:

Add a right hand sidebar to the apps menu. This could have a similar structure as the right hand sidebar for the files app. If you click on a app it could show a screenshot at the top. Followed by the description and allow users to rate and comment on the app.

**Edit:** And it could show the changelog #6684/#6984

Cc @jancborchardt  @nextcloud/designers

**Comment by jancborchardt** [comment] 2016-11-15 13:55
As discussed you convinced me it makes a lot of sense. The layout is very similar, with comments and all.

What do you think @nextcloud/appstore @nextcloud/designers?

**Comment by MorrisJobke** [comment] 2016-11-15 14:07
The only issue I see here is that this could cause some strange layout re-renderings when the sidebar is opened and closed.

**Comment by skjnldsv** [comment] 2016-11-15 14:42
I don't fully understand, could you do a simple sketch or mockup? :)

**Comment by claell** [comment] 2017-01-23 20:24
I don't know, whether a sidebar is good for that (width, position) or whether a popup or new page handles the details page of an app better.

**Comment by BernhardPosselt** [comment] 2017-01-23 20:38
Personally strongly in favour of a non pop-up, non modal solution :)

**Comment by stefan-niedermann** [comment] 2017-01-23 20:56
👎 for a pop-up solution. What about the layout that is used in the mail app? 3-column-based, but with more horizontal place for the details?

**Comment by jancborchardt** [comment] 2017-01-23 22:47
@stefan-niedermann the layout of the Mail app doesn’t really make sense here, as the list is more important than the details. Similar to Files for example. So that’s why the layout could be similar.

**Comment by eppfel** [comment] 2017-01-24 09:21
I think, if we introduce this  – and it looks like a strong contender – the grid view with large screenshots would not fit anymore. I guess we need visualizations to compare the layout between grid with screenshots and tabular #3195. 

I have proposal for restructuring apps management in the overview #3194 , which might influence our decision.

**Comment by jancborchardt** [comment] 2017-05-18 11:50
More concrete plan at https://github.com/nextcloud/server/issues/4827#issuecomment-302381528 since we have a slight regression of not being able to view the description for local apps.

**Comment by BloodyIron** [comment] 2018-04-16 22:32
In reference to #9189 ...

I would like it if we could click on the images already in the apps section, so they can go bigger, and then scroll through images outlining each app. As it is now, the images are so small you can't really tell what the app actually does.

Any chance we can get this going? This ticket has been open for quite a long time...

**Comment by MorrisJobke** [comment] 2018-06-06 16:05
Fixed with #9565

**Closed by MorrisJobke** 2018-06-06 16:05 UTC
Labels: 1. to develop, design, enhancement, feature: apps management
