### ISSUE TITLE
Default layout of 13.0.0 not as 12.0.5, displaced and unorganised

### ISSUE THREAD

**Issue by io-node** [nextcloud/server#8192] opened 2018-02-06 08:56 UTC
### Steps to reproduce
1. Existing NC on 12.0.5
2. Upgrade to 13.0.0
3. Disable any theme

### Expected behaviour
Layout of folder page should be the same

![image](https://user-images.githubusercontent.com/2435859/35849583-082de8b4-0b1a-11e8-9f16-e732afcdac97.png)

### Actual behaviour
- Gallery icon moved to the left and not in line with the "+" icon
- Extra spacing on each folder line
- Folder name below Icon
- Rows not in line with row-headers

![image](https://user-images.githubusercontent.com/2435859/35849656-43f2e084-0b1a-11e8-8a53-5267a5690244.png)

### Server configuration

**Operating system**: Debian 8

**Web server:** Apache2

**Database:** Mysql

**PHP version:** 7.0.22

**Nextcloud version:** 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from 12.0.5

**Where did you install Nextcloud from:** Command line

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - announcementcenter: 3.1.1
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.1
  - deck: 0.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.2.0
  - passman: 2.1.4
  - password_policy: 1.2.2
  - previewgenerator: 1.0.9
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.wijman.net"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR",
            "X-Forwarded-For"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.domain.ltd",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritehost": "cloud.wijman.net",
        "overwritewebroot": "\/",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud-stable.log",
        "loglevel": 0,
        "log_rotate_size": "104857600",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "filesystem_check_changes": 1,
        "enable_previews": true,
        "preview_max_x": 800,
        "preview_max_y": 800,
        "preview_max_scale_factor": 4,
        "skeletondirectory": "\/media\/nextcloud\/skeleton",
        "session_keepalive": true,
        "activity_expire_days": 365,
        "mail_smtpsecure": "tls",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "asset-pipeline.enabled": true,
        "share_folder": "\/Shares",
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Chrome

**Operating system:** Debian 8

**Comment by MorrisJobke** [comment] 2018-02-06 11:24
Looks like another CSS cache issue: 

Try to do this https://github.com/nextcloud/server/issues/8043#issuecomment-360776226:

* rm -r data/appdata_/css/
* occ files:scan-app-data
* reload the page


I will close this as a duplicate of #8043 and we also plan to provide a repair step that fixes it.

cc @nextcloud/theming @juliushaertl  @skjnldsv

**Closed by MorrisJobke** 2018-02-06 11:24 UTC

**Comment by juliushaertl** [comment] 2018-02-06 11:30
Yes, looks like the same. But could also be the merged JS cache that causes that, so make sure to also `rm -r data/appdata_*/js/` when doing the steps @MorrisJobke mentioned.

**Comment by io-node** [comment] 2018-02-06 12:11
Thanks yes that solved the issue.
