### ISSUE TITLE
Vue apps issues

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#9767] opened 2018-06-06 16:17 UTC
Following #9565 

- [x] Disabled apps contains all the disabled apps even the ones that are not installed
- [x] I have an error on load saying: `An error occured during the request. Unable to proceed.` on a xhr request `/ocs/v2.php/cloud/groups?offset=0&limit=-1&search=`
- [x] The script has been shipped as development and not production
- [x] Clicking the categories does not load anything on my instance (no does create a xhr request)
- [x] Missing a key in https://github.com/nextcloud/server/blob/59b086eae387e641d645e0e9af82f1a843958855/settings/src/components/appList.vue#L29 
- [x] clicking the remove/disable button open the sidebar 
- [x] removing an app still leave the app displayed on the list

**Comment by juliushaertl** [comment] 2018-06-09 10:10
Fixes are included in #9810, except for:

> I have an error on load saying: `An error occured during the request. Unable to proceed.` on a xhr request `/ocs/v2.php/cloud/groups?offset=0&limit=-1&search=`

@skjnldsv I cannot reproduce the error, can you check that again?

**Comment by skjnldsv** [comment] 2018-06-09 18:03
> @skjnldsv I cannot reproduce the error, can you check that again?

Apparently we're loading the getGroups function beforeMount
`this.$store.dispatch('getGroups', {offset: 0, limit: -1});`

The limit is somehow breaking my instance:
Error: `/ocs/v2.php/cloud/groups?offset=0&limit=-1&search=`
Ok: `/ocs/v2.php/cloud/groups?offset=0&limit=1&search=`

**Comment by MorrisJobke** [comment] 2018-07-05 08:42
Remaining items were fixed in #10103

**Closed by MorrisJobke** 2018-07-05 08:42 UTC
Labels: 1. to develop, bug, feature: apps management, high, regression
