### ISSUE TITLE
[Bug]: accepted share lands in root instead of default folder defined in personal settings when the share is made to a group

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#40375] opened 2023-09-12 07:57 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Under Personal settings > Sharing, it is possible to configure a default share folder
![image](https://github.com/nextcloud/server/assets/87175513/30a7d1ab-75d0-48cf-b341-f7b668863c19)

It works perfectly when the incoming share has been made to me specifically. However, it the incoming share has been made to a group I am part of, then the share lands in my root folder.

### Steps to reproduce

1. Set a default share folder in your personal settings
2. With another user, share something to you directly. File will land as expected in the default share folder
3. With another user, share something to a group you're part of. File will land in your root dir

### Expected behavior

File shared to a group I am part of should land in the default share folder I've configured.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2023-09-19 14:34
Duplicate of #40069

Go give that issue a :+1: :-)

**Closed by joshtrichards** 2023-09-19 14:34 UTC
Labels: bug, feature: sharing, 0. Needs triage, 27-feedback
