### ISSUE TITLE
Errors: "This parser only supports VCARD and VCALENDAR files" & "Undefined index: {http://owncloud.org/ns}owner-principal"

### ISSUE THREAD

**Issue by eibex** [nextcloud/server#25555] opened 2021-02-10 00:15 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to 20.0.7
2. Load contacts app from the web OR refresh contacts on phone

### Expected behaviour
No errors

### Actual behaviour
The errors are produced but everything seems to be working fine.
The following error is ALWAYS reported:
```
Sabre\VObject\ParseException: This parser only supports VCARD and VCALENDAR files

    /var/www/nextcloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 90:
    Sabre\VObject\Parser\MimeDir->parseDocument()
    /var/www/nextcloud/3rdparty/sabre/vobject/lib/Reader.php - line 47:
    Sabre\VObject\Parser\MimeDir->parse()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php - line 820:
    Sabre\VObject\Reader::read()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php - line 466:
    Sabre\CardDAV\Plugin->convertVCard()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php - line 199:
    Sabre\CardDAV\Plugin->addressbookQueryReport()
    /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:
    Sabre\CardDAV\Plugin->report()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 720:
    Sabre\DAV\Server->emit()
    /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:
    Sabre\DAV\CorePlugin->httpReport()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:
    Sabre\DAV\Server->emit()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:
    Sabre\DAV\Server->invokeMethod()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:
    Sabre\DAV\Server->start()
    /var/www/nextcloud/apps/dav/lib/Server.php - line 332:
    Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:
    OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 167:
    require_once("/var/www/ne ... p")
```

Sometime this error is also spammed too:
```
Error: Undefined index: {http://owncloud.org/ns}owner-principal at /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php#1789
    /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 1789:
    OC\Log\ErrorHandler::onError()
    /var/www/nextcloud/apps/dav/lib/Search/TasksSearchProvider.php - line 108:
    OCA\DAV\CalDAV\CalDavBackend->searchPrincipalUri()
    /var/www/nextcloud/lib/private/Search/SearchComposer.php - line 162:
    OCA\DAV\Search\TasksSearchProvider->search()
    /var/www/nextcloud/core/Controller/UnifiedSearchController.php - line 110:
    OC\Search\SearchComposer->search()
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:
    OC\Core\Controller\UnifiedSearchController->search()
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:
    OC\AppFramework\Http\Dispatcher->executeController()
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:
    OC\AppFramework\Http\Dispatcher->dispatch()
    /var/www/nextcloud/lib/private/Route/Router.php - line 309:
    OC\AppFramework\App::main()
    /var/www/nextcloud/ocs/v1.php - line 88:
    OC\Route\Router->match()
    /var/www/nextcloud/ocs/v2.php - line 24:
    require_once("/var/www/nextcloud/ocs/v1.php")
```

### Server configuration

**Operating system:** Ubuntu 20.4

**Web server:** Apache 2.4.46

**Database:** PostgreSQL 12

**PHP version:** 7.4

**Nextcloud version:** 20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 20.0.6

**Where did you install Nextcloud from:** From nextcloud.com when the release was 17

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Accessibility
Activity
AppOrder
Audio Player
Brute-force settings
Calendar
Collaborative tags
Comments
Contacts
Contacts interaction
Deleted files
End-to-end encryption
File sharing
First run wizard
Log reader
Maps
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Photos
Preview generator
Privacy
Recommendations
Right click
Share by mail
Support
Suspicious login
Tasks
Text
Theming
Two-factor TOTP provider
Update notification
User status
Versions
Video converter
Video player
```
</details>

**Nextcloud configuration:**
I can add it if needed, not relevant though.
<details>
<summary>Config report</summary>
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes, e2e not server-side

**Are you using an external user-backend, if yes which one:** no

**Comment by eibex** [comment] 2021-02-10 08:37
I noticed that a new, empty, CardDAV account was created: "Recently Contacted"

This seems to be the source of the error also here: https://help.nextcloud.com/t/nc20-cant-synchronize-contact-this-parser-only-supports-vcard-and-vcalendar-files/107328

I never created that contact group, yet it popped up now.

**Comment by Chartman123** [comment] 2021-03-23 07:12
Possible duplicate of #22439

**Closed** 2021-04-08 20:17 UTC
Labels: 0. Needs triage, bug
