### ISSUE TITLE
Last change date wrong

### ISSUE THREAD

**Issue by kroerig** [nextcloud/server#20862] opened 2020-05-07 16:12 UTC
When uploading an old file, NC displays a wrong "last changed" date.

### Steps to reproduce
1. Upload a file from your PC, that was create in e.g. 2007
2. Look at the "Changed" colum.

### Expected behaviour
NC schould display " now"

### Actual behaviour
NC displays "before 13 years"

### Server configuration

**Operating system:** Debian 9.7

**Web server:** NGINX

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade

**Where did you install Nextcloud from:** source

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - audioplayer: 2.10.0
  - bookmarks: 3.0.11
  - bruteforcesettings: 1.6.0
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_antivirus: 2.3.0
  - files_downloadactivity: 1.7.0
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trackdownloads: 1.7.0
  - files_videoplayer: 1.7.0
  - groupfolders: 6.0.6
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.3.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - user_usage_report: 1.2.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 4,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 30,
        "skeletondirectory": "",
        "preview_max_x": 100,
        "preview_max_y": 100,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trashbin_retention_obligation": "auto, 7",
        "versions_retention_obligation": "auto, 14",
        "updater.release.channel": "stable",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "mail_smtpauthtype": "LOGIN",
        "sharing.enable_share_accept": false,
        "sharing.force_share_accept": false,
        "app_install_overwrite": [
            "circles",
            "spreed",
            "twofactor_admin",
            "quota_warning",
            "impersonate",
            "ransomware_detection",
            "activitylog"
        ],
        "mysql.utf8mb4": true
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** any

**Operating system:** any

**Comment by kesselb** [comment] 2020-05-07 17:30
I don't think so. Last changed is always a reference to the last change of the content.

See also https://github.com/nextcloud/server/issues/15192.

**Comment by kesselb** [comment] 2020-05-07 17:31
cc @nextcloud/server-triage won't fix from my pov.

**Comment by kroerig** [comment] 2020-05-07 18:46
The problem is that users can't see, when new content has been uploaded, because NC displays the creation date of the file instead of the upload date. Teatchers have many files that are very old, but still use them.
Because of this you can't see "what's new" in a folder because the lastest uploaded file was changed "13 years ago".

For me there's no problem to show when the file has originally created, but NC should show when it has been uploaded.

**Comment by MorrisJobke** [comment] 2020-05-08 07:55
It is correct for now. We want to keep the original time. There is also the plan to store the upload time and somehow add them to the UI. But this is working as intended.

**Closed** 2020-05-11 12:59 UTC
Labels: bug, feature: filesystem, wontfix
