### ISSUE TITLE
[sharebymail] force expiration date

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#14536] opened 2019-03-05 10:53 UTC
As an admin, I want to be able to force a default expiration period on mail-shares, just like I can do it for link-shares, so I have a consistent forcing-behaviour among the two external-sharing-methods.

**Comment by nickvergessen** [comment] 2019-03-05 12:11
Duplicate of https://github.com/nextcloud/server/issues/6603 I'd say

**Closed** 2019-03-05 12:12 UTC
Labels: enhancement, feature: sharing

**Comment by wiswedel** [comment] 2019-03-05 12:22
> Duplicate of #6603 I'd say

@nickvergessen Not really duplicate, rather successor (see https://github.com/nextcloud/server/issues/6603#issuecomment-469638793)
