### ISSUE TITLE
Allow to setup number of visible application icons

### ISSUE THREAD

**Issue by ewidance** [nextcloud/server#17365] opened 2019-10-02 06:29 UTC
Nextcloud show icon apps  in a directly available / more scheme. 
Number of directly visible icon is dependant of /core/js/js.js:
var usePercentualAppMenuLimit = 0.33;

It would be interresting to allow to parameter this settings for having a larger zone for icons allowing to directly pick more applications. 

For example, 0.50 allow to see 13 apps.

**Comment by kesselb** [comment] 2019-10-03 14:01
I hope it's okay with you to close this issue as duplicate of https://github.com/nextcloud/server/issues/13079

**Closed by kesselb** 2019-10-03 14:01 UTC
Labels: 0. Needs triage, enhancement

**Comment by teotikalki** [comment] 2020-01-02 21:52
How about 'it's ok if doing so acknowledges that this is a highly requested feature wanted by MANY' and not 'we hear this all the time and still don't care'?

**Comment by kesselb** [comment] 2020-01-03 00:30
> doing so acknowledges that this is a highly requested feature wanted by MANY

Yes.

> we hear this all the time and still don't care

We are closing issues as duplicates to keep all information / discussion at one place.
