### ISSUE TITLE
Add upload button to shared upload-links

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/server#5439] opened 2017-06-16 12:22 UTC
When you share a folder so that third parties (without nc account or nc experience) can upload **and** download files, then you will run into some issues. In my use case a user of one of our nextcloud instances shared a link with older computer-illiterate people.  That user had to include a lengthy (2 or 3 paragraphs) explanation how to upload files. 

For users that have no nextcloud experience it can be hard to find the drop down menu item "upload" behind the plus button.

Two obvious solutions i thought of are:

 * add description/label to plus button
 * add upload button (more explicit, less steps)

Here a mockup. The button is in the top bar, as there are already two buttons that are for users that are not registered at the local nextcloud. IMHO it also makes sense to use the same element / position for uploading as for downloading

![bildschirmfoto von 2017-06-16 14-03-50](https://user-images.githubusercontent.com/1377943/27226292-89b152e8-529e-11e7-9783-36bd1f44b18a.png)

**Comment by MorrisJobke** [comment] 2017-07-18 08:40
Duplicate of #4011

**Closed by MorrisJobke** 2017-07-18 08:40 UTC
