### ISSUE TITLE
Plugins not working on Shared Folders

### ISSUE THREAD

**Issue by compumatter** [nextcloud/server#7125] opened 2017-11-10 01:42 UTC
### Steps to reproduce
1. Create a text file using the [+] icon on top and type a few characters to save it.
2. Share the folder that text file is contained in while giving Edit rights to the user
3. textfile plugin does not open when the user whom this file was shared with clicks on it.  Instead it offers to download it.
4. I have also experienced this same thing with the draw.io plugin which is not activated on shared folders even with edit rights.

### Expected behaviour
I would expect the end user to experience the same thing the person sharing it with them provided - or a config allowing / disallowing this behavior.

### Actual behaviour
It downloads the file

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Installed on our server
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - activity: 2.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_clipboard: 0.6.4
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - onlyoffice
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder
+-------------------------------+-----------------------------------------------------+
| Configuration                 |                                                     |
+-------------------------------+-----------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                   |
| hasPagedResultSupport         |                                                     |
| homeFolderNamingRule          |                                                     |
| lastJpegPhotoLookup           | 0                                                   |
| ldapAgentName                 | CN= ,CN=users,DC=DC= |
| ldapAgentPassword             | ***                                                 |
| ldapAttributesForGroupSearch  |                                                     |
| ldapAttributesForUserSearch   |                                                     |
| ldapBackupHost                |                                                     |
| ldapBackupPort                |                                                     |
| ldapBase                      | DC=,DC=|
| ldapBaseGroups                | DC=,DC=|
| ldapBaseUsers                 | DC=,DC=|
| ldapCacheTTL                  | 600                                                 |
| ldapConfigurationActive       | 1                                                   |
| ldapDefaultPPolicyDN          |                                                     |
| ldapDynamicGroupMemberURL     |                                                     |
| ldapEmailAttribute            | mail                                                |
| ldapExperiencedAdmin          | 0                                                   |
| ldapExpertUUIDGroupAttr       |                                                     |
| ldapExpertUUIDUserAttr        |                                                     |
| ldapExpertUsernameAttr        |                                                     |
| ldapGidNumber                 | gidNumber                                           |
| ldapGroupDisplayName          | cn                                                  |
| ldapGroupFilter               |                                                     |
| ldapGroupFilterGroups         |                                                     |
| ldapGroupFilterMode           | 0                                                   |
| ldapGroupFilterObjectclass    |                                                     |
| ldapGroupMemberAssocAttr      | uniqueMember                                        |
| ldapHost                      | ldap://localhost                                    |
| ldapIgnoreNamingRules         |                                                     |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(samaccountname=%uid))    |
| ldapLoginFilterAttributes     |                                                     |
| ldapLoginFilterEmail          | 0                                                   |
| ldapLoginFilterMode           | 0                                                   |
| ldapLoginFilterUsername       | 1                                                   |
| ldapNestedGroups              | 0                                                   |
| ldapOverrideMainServer        |                                                     |
| ldapPagingSize                | 500                                                 |
| ldapPort                      | 389                                                 |
| ldapQuotaAttribute            |                                                     |
| ldapQuotaDefault              |                                                     |
| ldapTLS                       | 0                                                   |
| ldapUserDisplayName           | displayName                                         |
| ldapUserDisplayName2          |                                                     |
| ldapUserFilter                | (&(|(objectclass=user)))                            |
| ldapUserFilterGroups          |                                                     |
| ldapUserFilterMode            | 0                                                   |
| ldapUserFilterObjectclass     | user                                                |
| ldapUuidGroupAttribute        | auto                                                |
| ldapUuidUserAttribute         | auto                                                |
| turnOffCertCheck              | 0                                                   |
| turnOnPasswordChange          | 0                                                   |
| useMemberOfToDetectMembership | 1                                                   |
+-------------------------------+-----------------------------------------------------+

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chrome / Firefox

**Operating system:** Windows

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2017-11-24 14:29
Duplicate of #1571

**Closed by MorrisJobke** 2017-11-24 14:29 UTC
