### ISSUE TITLE
[Bug]: In Nextcloud 27.1.3 random background images not working

### ISSUE THREAD

**Issue by AliAsgerSaify** [nextcloud/server#41595] opened 2023-11-18 03:39 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Nextcloud 27.1.3 random background images not working while in version 27.1.0 its fully functional, it shows a message of failed in the latest (27.1.3) version. 

Here is the log:
[PHP] Error: include(): Failed opening '/var/www/html/custom_apps/unsplash/templates/partials/license.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/lib/private/Template/Base.php#180

GET /settings/admin/theming
from 172.17.0.1 by admin at 2023-11-18T03:32:32+00:00

### Steps to reproduce

1. Go to Administration Settings
2. Go to Theming Tab
3. Go to Splash: Random background section
4. Whatever changes we make there, it just show failed. [While in 27.1.0 it displayed saved]
5.

### Expected behavior

It must display saved instead its showing failed

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Signing status

```shell
No error has been found
```

### Nextcloud Logs

```shell
[PHP] Error: include(): Failed opening '/var/www/html/custom_apps/unsplash/templates/partials/license.php' for inclusion (include_path='/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at /var/www/html/lib/private/Template/Base.php#180

GET /settings/admin/theming
from 172.17.0.1 by admin at 2023-11-18T03:32:32+00:00
```

### Additional info

Nextcloud 27.1.3

**Comment by joshtrichards** [comment] 2023-11-18 21:00
This looks like an issue with the Unplash app not Server:

https://github.com/nextcloud/unsplash/issues/123

Closing here as a duplicate of that issue. I suggest you follow-up / upvote / try to troubleshoot there.

**Closed by joshtrichards** 2023-11-18 21:00 UTC
Labels: bug, 0. Needs triage, 27-feedback
