### ISSUE TITLE
[Bug]: Push notifications might be unreliable shown to normal users

### ISSUE THREAD

**Issue by svenseeberg** [nextcloud/server#38086] opened 2023-05-04 16:24 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Unsupported Nextcloud installations show the following message to regular users:

1 "This community release of Nextcloud is unsupported and push notifications are limited." on the login screen
2. "Push notifications might be unreliable" in the notification area with a link to contact the Nextcloud support
3. "This community release of Nextcloud is unsupported and instant notifications are unavailable." in the user profile

While I have no problem with Nextcloud asking for a fee for a functionality which is running on their infrastructure. But there is nothing users can do about it. In the best case it is only confusing them. Most users don't even know what "unsupported" means. I also don't think that Nextcloud GmbH actually wants users of random community Nextcloud servers to contact the sales department.

For us the unsupported state is no problem at the moment, only the message is not helping everyday users. Deactivating the Notifications app is also totally viable. However, at least in the profile area the notification cannot be turned off.

In different contexts I'm also operating Nextclouds for communities with very high demands on privacy. In such cases I would nowadays deactivate the notifications app anyways. The messages in the login screen and profile would then become obsolete but is shown anyways.

### Steps to reproduce

1. Setup a Nextcloud 
2. Create more accounts than supported
3. Look into the User Profile and Notifcation area

### Expected behavior

1. Only admins should see notifications about the unsupported status of a Nextcloud server.
2. When the notifcations app is disabled, the login screen and profile area should not display warnings.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 0,
        "debug": false,
        "overwrite.cli.url": "https:\/\/nextcloud.example.com",
        "dbtype": "mysql",
        "version": "25.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "theme": "",
        "filelocking.ttl": 3600,
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_readmemd",
        ],
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "data-fingerprint": "490ffc7bacdce6eb676bcbc2013215ca",
        "integrity.check.disabled": false,
        "simpleSignUpLink.shown": false,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "maintenance_window_start": 1,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.3
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_antivirus: 5.0.0
  - files_pdfviewer: 2.6.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.2
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2023.4.30
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
```

### Nextcloud Signing status

```shell
Dies ist der nicht unterstützte Community-Build von Nextcloud. Angesichts der Größe dieser Instanz können Leistung, Zuverlässigkeit und Skalierbarkeit nicht garantiert werden. Push-Benachrichtigungen wurden beschränkt, um eine Überlastung unseres kostenlosen Dienstes zu vermeiden. Erfahren Sie mehr über die Vorteile von Nextcloud Enterprise unter https://nextcloud.com/enterprise.
```

### Nextcloud Logs

```shell
None
```

**Comment by solracsf** [comment] 2023-05-04 17:31
Let's close as duplicate of https://github.com/nextcloud/server/issues/37322 and keep track of this inside one single issue 👍 
(I've copied you inputs there)

**Closed by solracsf** 2023-05-04 17:31 UTC
Labels: enhancement, 0. Needs triage

**Comment by svenseeberg** [comment] 2023-05-08 08:46
> Let's close as duplicate of #37322 and keep track of this inside one single issue +1

Thanks, I missed this issue in my search.
