### ISSUE TITLE
blank page and scan failed : Error: Call to a member function instanceOfStorage() on null

### ISSUE THREAD

**Issue by centredecalcul** [nextcloud/server#12017] opened 2018-10-24 14:39 UTC
### Steps to reproduce
Open Nextcloud web interface, desktop client (owncloud or nextcloud) or scan all folder of user with occ :

$ su apache --shell=/bin/bash -c /opt/rh/rh-php71/root/bin/php  /var/www/cloud-ccub/nextcloud/occ 
files:scan dginhac

### Expected behaviour
Files and folders should be listed, scan should pass.

### Actual behaviour
Blank page (working cursor), or this error in scan :+1: 

<details>
<summary>occ log</summary>
Starting scan for user 1 out of 1 (dginhac)
An unhandled exception has been thrown:
Error: Call to a member function instanceOfStorage() on null in /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/View.php:1919
Stack trace:
#0 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/View.php(2033): OC\Files\View->lockPath('/Partages re\xC3\xA7u...', 1, false)
#1 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/View.php(1132): OC\Files\View->lockFile('/Partages re\xC3\xA7u...', 1)
#2 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/View.php(268): OC\Files\View->basicOperation('mkdir', '/Partages re\xC3\xA7u...', Array)
#3 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files_sharing/lib/Helper.php(87): OC\Files\View->mkdir('//Partages re\xC3\xA7...')
#4 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files_sharing/lib/SharedMount.php(101): OCA\Files_Sharing\Helper::getShareFolder(Object(OC\Files\View))
#5 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files_sharing/lib/SharedMount.php(77): OCA\Files_Sharing\SharedMount->verifyMountPoint(Object(OC\Share20\Share), Array, Object(OC\Cache\CappedMemoryCache))
#6 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files_sharing/lib/MountProvider.php(115): OCA\Files_Sharing\SharedMount->__construct('\\OCA\\Files_Shar...', Array, Array, Object(OC\Files\Storage\StorageFactory), Object(OC\Files\View), Object(OC\Cache\CappedMemoryCache))
#7 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/Config/MountProviderCollection.php(113): OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
#8 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/Filesystem.php(446): OC\Files\Config\MountProviderCollection->addMountForUser(Object(OC\User\User), Object(OC\Files\Mount\Manager))
#9 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files_sharing/lib/SharedStorage.php(126): OC\Files\Filesystem::initMountPoints('mu7320bo')
#10 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files_sharing/lib/SharedStorage.php(479): OCA\Files_Sharing\SharedStorage->init()
#11 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/Storage/Wrapper/Wrapper.php(494): OCA\Files_Sharing\SharedStorage->getWrapperStorage()
#12 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files_sharing/lib/SharedStorage.php(165): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('OC\\Files\\Storag...')
#13 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/Storage/Wrapper/Wrapper.php(494): OCA\Files_Sharing\SharedStorage->instanceOfStorage('OC\\Files\\Storag...')
#14 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Files/Utils/Scanner.php(200): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('OC\\Files\\Storag...')
#15 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files/lib/Command/Scan.php(172): OC\Files\Utils\Scanner->scan('/dginhac', true, NULL)
#16 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/apps/files/lib/Command/Scan.php(249): OCA\Files\Command\Scan->scanFiles('dginhac', '/dginhac', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#17 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/3rdparty/symfony/console/Command/Command.php(251): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/core/Command/Base.php(162): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/console.php(96): OC\Console\Application->run()
#24 /var/www/cloud-ccub/nextcloud-14.0.3-20181017/occ(11): require_once('/var/www/cloud-...')
#25 {main}
</details>

### Server configuration

**Operating system**:
CentOS 7 : 7.5.1804

**Web server:**
httpd : 2.4.6-80

**Database:**
Galera MariaDB : 5.5

**PHP version:**
PHP 7.1.8 with php-fpm (software collection)

**Nextcloud version:** (see Nextcloud admin page)
14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Migrated from ownCloud 8.2.11 to Nextcloud 9 => 10 => 11 => 12 => 13 => 14.0.3

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - admin_audit: 1.4.0
  - cloud_federation_api: 0.0.1
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_antivirus: 1.3.2
  - files_external: 1.5.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_cas: 1.5.5
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
Disabled:
  - activity
  - comments
  - encryption
  - files_pdfviewer
  - support
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.u-bourgogne.fr",
            "cloud-ccub.u-bourgogne.fr"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.u-bourgogne.fr",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "trashbin_retention_obligation": "60, 60",
        "versions_retention_obligation": "60, 60",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "allow_user_to_change_display_name": false,
        "session_keepalive": true,
        "loglevel": 0,
        "log_type": "syslog",
        "syslog_tag": "cloud-ccub",
        "logfile": "",
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Partages re\u00e7us",
        "maintenance": false,
        "singleuser": true,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

</details>

**Are you using external storage, if yes which one:** 
sftp for some users

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
ldap
user_cas

### Client configuration
**Browser:**

**Operating system:**

**Comment by MorrisJobke** [comment] 2018-10-24 16:05
Seems to be a duplicate of #10316

**Closed by MorrisJobke** 2018-10-24 16:05 UTC
Labels: bug
