### ISSUE TITLE
Can't sync directories with a question mark (?) in their name.

### ISSUE THREAD

**Issue by magiruuvelvet** [nextcloud/server#16506] opened 2019-07-22 16:52 UTC
Regular files with a question mark in their name are ok, just directories are failing. The server confuses it with a query string. Are question marks escaped properly? I can remember I couldn't access directories with a question mark in any web browser some versions older before 16, it seems to work now, but the client still can't sync them. My guess is a confusion with a query string.

### Server configuration

**Operating system**: Linux (ext4 filesystem)

**Web server:** Caddy

**Database:** MariaDB

**PHP version:** 7.3.7

**Nextcloud version:** 16.0.3

### Client configuration

**Browser:** nope, Nextcloud native client (C++)

**Operating system:** Linux (ext4 filesystem)

### Logs

Interesting error message from the client

```plain
Server is unable to maintain the header compression context for the connection
```

Sample for reproduction: `this is a dir with ?/filename with ?.txt`

The server log shows that the character is escaped correctly (`%3F`) from the client, but it still fails with no error message, which is weird.

**Comment by cooppor** [comment] 2019-08-19 17:00
Can you share your caddyfile ? I got lots of problems with caddyserver and nextcloud 16.0.3. Thanks.

**Comment by magiruuvelvet** [comment] 2019-08-20 05:28
sure here is my working Caddyfile for Nextcloud

```caddyfile
root /data/nextcloud/nextcloud

fastcgi / unix:/run/php-fpm/php-fpm.sock php {
    env PATH /usr/local/sbin:/usr/local/bin:/usr/bin:/bin
}

index index.php

# checks for static assets
rewrite {
    ext .svg .gif .png .html .ttf .woff .ico .jpg .jpeg
    r ^/index.php/(.+)$
    to /{1} /index.php?{1}
}

# well-known rewrites
rewrite {
    r ^/\.well-known/host-meta$
    to /public.php?service=host-meta&{query}
}
rewrite {
    r ^/\.well-known/host-meta\.json$
    to /public.php?service=host-meta-json&{query}
}
rewrite {
    r ^/\.well-known/webfinger$
    to /public.php?service=webfinger&{query}
}

# global rewrite
rewrite {
    r ^/index.php/.*$
    to /index.php?{query}
}

# client support
redir /.well-known/carddav /remote.php/carddav 301
redir /.well-known/caldav /remote.php/caldav 301

# remove trailing / as it causes errors with php-fpm
rewrite {
    r ^/remote.php/(webdav|caldav|carddav|dav)(\/?)(\/?)$
    to /remote.php/{1}
}

rewrite {
    r ^/remote.php/(webdav|caldav|carddav|dav)/(.+?)(\/?)(\/?)$
    to /remote.php/{1}/{2}
}

rewrite {
    r ^/public.php/(dav|webdav|caldav|carddav)(\/?)(\/?)$
    to /public.php/{1}
}

rewrite {
    r ^/public.php/(dav|webdav|caldav|carddav)/(.+)(\/?)(\/?)$
    to /public.php/{1}/{2}
}

# forbid access to those files and directories
internal /.htaccess
internal /.user.ini
internal /data
internal /config
internal /db_structure
internal /.xml
internal /occ
internal /README

# set http headers
header / {
    Strict-Transport-Security "max-age=15768000;"
    -Server
    -X-Powered-By
    -Content-Security-Policy
}

```

**Comment by wiswedel** [comment] 2020-11-06 12:21
duplicate of (newer but more detailed explained) https://github.com/nextcloud/server/issues/20482

**Closed by wiswedel** 2020-11-06 12:21 UTC
Labels: 0. Needs triage, bug
