### ISSUE TITLE
13.0.0 beta 3: white page after upgrade

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/server#7532] opened 2017-12-15 11:11 UTC
### Steps to reproduce
1. Update from 12.0.4 to 13.0.0 beta3 using webupdater

### Expected behaviour
occ upgrade should be run, redirect to default page afterwards.

### Actual behaviour
occ upgrade does not start leading to a blank page.
The issue is caused by missing execute permissions on occ. Fixing the permissions manually and running occ upgrade afterwards solves the issue.

**Comment by MorrisJobke** [comment] 2017-12-15 12:44
> Update from 12.0.4 to 13.0.0 beta3 using webupdater

You used the web page to update (white page with "updater" in the top right) and then also used the web based upgrade (blue page with the button in the middle to start it)? What does this have to do with occ upgrade (which is the counterpart to the blue page). Either you used the web based upgrader (blue page) or occ upgrade. Could you explain this a bit more?

**Comment by RainerEmrich** [comment] 2017-12-15 13:15
Sorry for being unclear. I updated from 12.0.4 using the updater on the admin page beta channel selected.

![updater](https://user-images.githubusercontent.com/26002841/34043360-011dcf6e-e1a1-11e7-856e-840d2d860593.png)

Pushing "Start update"

![updater2](https://user-images.githubusercontent.com/26002841/34043444-7087915a-e1a1-11e7-8743-1b9410b4889c.png)

Now using the web based updater pressing the "No ..." button.

![updater3](https://user-images.githubusercontent.com/26002841/34043505-b88a93ee-e1a1-11e7-99eb-688724882a3c.png)

Finally Pressing the "Go back to your Nextcloud instance to finish the update" button gives a blank page.
Looking in my document root shows that occ has no execute permissions!
ll occ
-rw-r--r-- 1 www-data www-data 283 Dec 15 13:06 occ

Changing permissions with chmod +x and running "occ upgrade" manually gives me a working nextcloud instance again. So, the only issue are the missing execute permissions on occ.

I hope this helps.

**Comment by MorrisJobke** [comment] 2017-12-15 13:18
> Looking in my document root shows that occ has no execute permissions!

Okay - this has nothing to do with the white page.



> Changing permissions with chmod +x and running "occ upgrade" manually gives me a working nextcloud instance again. So, the only issue are the missing execute permissions on occ.

You don't need the executable flag for the occ command to run - you could also run `php occ upgrade` - the executable flag here is for convenience.

The white page is the real problem. Is there anything in the nextcloud.log or the web server error log? Because the white page indicates, that there was a problem.

**Comment by masaki-iwata** [comment] 2017-12-15 14:10
I too suffering from the same error 500.
Upgraded via web interface from NC12.0.4 to NC13 beta3.

I found this error in apache error log.

`PHP Fatal error:  Declaration of OCA\\FilesAccessControl\\StorageWrapper::copyFromStorage(OCP\\Files\\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OCP\\Files\\Storage::copyFromStorage(OCP\\Files\\Storage\\IStorage $sourceStorage, $sourceInternalPath, $targetInternalPath) in /virtual/htdocs/nextcloud/apps/files_accesscontrol/lib/StorageWrapper.php on line 628`

Operating system: CentOS 6.2
Web server: Apache 2.2
PHP version: 7.1.2

**Comment by RainerEmrich** [comment] 2017-12-15 14:18
>     Looking in my document root shows that occ has no execute permissions!
> 
> Okay - this has nothing to do with the white page.
> 
>     Changing permissions with chmod +x and running "occ upgrade"
>     manually gives me a working nextcloud instance again. So, the only
>     issue are the missing execute permissions on occ.
> 
> You don't need the executable flag for the occ command to run - you
> could also run |php occ upgrade| - the executable flag here is for
> convenience.
You're right, sorry.

> 
> The white page is the real problem. Is there anything in the
> nextcloud.log or the web server error log? Because the white page
> indicates, that there was a problem.
I try to reproduce. For sure the upgrade isn't started.
I roll back and retry.

**Comment by RainerEmrich** [comment] 2017-12-15 14:19
>> The white page is the real problem. Is there anything in the
>> nextcloud.log or the web server error log? Because the white page
>> indicates, that there was a problem.
> I try to reproduce. For sure the upgrade isn't started.
> I roll back and retry.
Yeah, got it.

nextcloud.log:
{"reqId":"I76Rx37T3t6gby8zyNxc","level":3,"time":"2017-12-15T14:06:16+00:00","remoteAddr":"24.134.13.209","user":"--","app":"PHP","method":"GET","url":"\/","message":"Declaration
of
OCA\\FilesAccessControl\\StorageWrapper::copyFromStorage(OCP\\Files\\Storage
$sourceStorage, $sourceInternalPath, $targetInternalPath) must be
compatible with
OCP\\Files\\Storage::copyFromStorage(OCP\\Files\\Storage\\IStorage
$sourceStorage, $sourceInternalPath, $targetInternalPath) at
\/var\/www\/nc_01\/nextcloud\/apps\/files_accesscontrol\/lib\/StorageWrapper.php#628","userAgent":"Mozilla\/5.0
(Windows NT 6.1; Win64; x64; rv:57.0) Gecko\/20100101
Firefox\/57.0","version":"12.0.4.3"}

Apache error.log:
[Fri Dec 15 14:06:16.550444 2017] [proxy_fcgi:error] [pid 1185:tid
140167169410816] [client 24.134.13.209:55026] AH01071: Got error 'PHP
message: PHP Fatal error:  Declaration of
OCA\\FilesAccessControl\\StorageWrapper::copyFromStorage(OCP\\Files\\Storage
$sourceStorage, $sourceInternalPath, $targetInternalPath) must be
compatible with
OCP\\Files\\Storage::copyFromStorage(OCP\\Files\\Storage\\IStorage
$sourceStorage, $sourceInternalPath, $targetInternalPath) in
/var/www/nc_01/nextcloud/apps/files_accesscontrol/lib/StorageWrapper.php
on line 628\n'

**Comment by MorrisJobke** [comment] 2017-12-15 14:55
Gotcha - the files_accesscontrol caused this.

**Comment by RainerEmrich** [comment] 2017-12-15 15:03
Am 15.12.2017 um 15:55 schrieb Morris Jobke:
> Gotcha - the files_accesscontrol caused this.
Does this qualify for a T-Shirt. I would be really proud of a Nextcloud
T-Shirt.

**Comment by MorrisJobke** [comment] 2017-12-15 15:05
> Does this qualify for a T-Shirt. I would be really proud of a Nextcloud
> T-Shirt.

It was already fixed in 1.3.0 🙈 . But maybe @jospoortvliet can help you with that 😉 Just drop him and me an email with this thread as an reference (our emails are our first name <at> nextcloud <dot> com)

**Comment by RainerEmrich** [comment] 2017-12-15 15:13
Am 15.12.2017 um 16:00 schrieb Morris Jobke:
> This was already fixed by that app: nextcloud/files_accesscontrol#75
> <https://github.com/nextcloud/files_accesscontrol/pull/75>
> 
> Could you check that you have installed the version 1.3.0 of
> files_accesscontrol? Because that version fixes the issue with the error
> message and should also avoid the white page.
This isn't going to work, because there is no 1.3.0 version of the app
for NC 12.0.x.

**Comment by RainerEmrich** [comment] 2017-12-15 15:23
Am 15.12.2017 um 16:13 schrieb Rainer Emrich:
> Am 15.12.2017 um 16:00 schrieb Morris Jobke:
>> This was already fixed by that app: nextcloud/files_accesscontrol#75
>> <https://github.com/nextcloud/files_accesscontrol/pull/75>
>>
>> Could you check that you have installed the version 1.3.0 of
>> files_accesscontrol? Because that version fixes the issue with the error
>> message and should also avoid the white page.
> This isn't going to work, because there is no 1.3.0 version of the app
> for NC 12.0.x.
I just rechecked, last supported version for NC 12 is version 1.2.5 of
the app. So you would need a version 1.2.6 which works for NC 12.

**Comment by MorrisJobke** [comment] 2017-12-16 07:19
Mmmmh ... need to check this again and will write here again, but this seems to be the only way.

**Comment by ToeiRei** [comment] 2017-12-20 16:47
Could reproduce the behavior described - files_accesscontrol disabled and it worked again for now until I can update the app itself

**Comment by masaki-iwata** [comment] 2017-12-22 15:24
I tried update with files_accesscontrol disabled.
so then I could update !

**Comment by anjoer** [comment] 2017-12-26 07:21
Thanks, disabling files_accesscontrol worked for me too.

**Comment by jospoortvliet** [comment] 2018-01-02 12:32
Can we close this issue then?

**Closed** 2018-01-02 14:13 UTC
Labels: bug

**Comment by fethomm** [comment] 2018-01-12 13:45
I had the same issue today upgrading from 12.04 to 13 RC1, using the auto updater in the admin backend. After going back to my frontend, I was greeted with a HTTP ERROR 500. Running occ updater manualy through SSH fixed the issue for me. I could see that it disabled files_accesscontrol during the upgrade.

**Comment by jospoortvliet** [comment] 2018-01-16 21:37
Ah so the web interface can't deal with apps breaking but the command line can, is that correct @MorrisJobke ?

**Comment by RainerEmrich** [comment] 2018-01-16 22:41
Yeah, It looks like that's the case. You can work around this issue by disabling the app before the upgrade, but it would really be better, if the upgrade process would take care of this.

**Comment by MorrisJobke** [comment] 2018-01-17 04:29
> Ah so the web interface can't deal with apps breaking but the command line can, is that correct @MorrisJobke ?

Not really. The web UI only has the disadvantage that if a app breaks it can't launch itself, while the command line interface still can launch, because it doesn't load everything right away.

**Comment by xXSTrikeXx** [comment] 2018-02-08 02:12
I also got a blank page after php update :S

**Comment by nomoresecrets** [comment] 2018-02-12 16:52
Same error here when upgrading to current stable v13

**Comment by Terrox** [comment] 2018-02-15 20:16
I had this issue to. All my _enabled_ addons were up to date.

**Comment by tomck** [comment] 2018-03-01 06:13
I was on 12.0.4, updated all my apps, had WSOD. After renaming the apps/files_accesscontrol to files_accesscontrol-disabled, I was able to see the upgrade screen and actually run the upgrade. [This page](https://help.nextcloud.com/t/declaration-of-storagewrapper-error/26953/2) really helped because I did see the storagewrapper error in the logs.

**Comment by lalmat** [comment] 2018-04-10 11:03
Thanks @tomck !
