### ISSUE TITLE
[Bug]: Database error when running migration 28000Date20230906104802

### ISSUE THREAD

**Issue by fbnts** [nextcloud/server#41763] opened 2023-11-27 10:16 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

While upgrading to 28.0.0 RC1 I get the error "Exception: Database error when running migration 28000Date20230906104802 for app core Index name "last_checked" for table "oc_storages" collides with the constraint on table "oc_jobs"."

### Steps to reproduce

1. Open the web updater from version 27.1.4
2. Click "Continue Update"
3. Then continue with web based updater

When trying to update the DB schema the above error is displayed

### Expected behavior

Update the DB schema and Nextcloud server to V28.0.0 RC1

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "allowSymlinks": true,
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "default_phone_region": "GB",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trashbin_retention_obligation": "20, 40",
        "updatechecker": true,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "logtimezone": "Europe\/London",
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud.log",
        "theme": "",
        "updater.release.channel": "beta",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "files_downloadactivity",
            "audioplayer",
            "ocsms",
            "radio",
            "spreed",
            "calendar",
            "admin_notifications",
            "workflow_pdf_converter",
            "files_automatedtagging",
            "event_update_notification",
            "forms",
            "announcementcenter",
            "metadata",
            "files_inotify",
            "impersonate",
            "dropit",
            "checksum",
            "phonetrack",
            "circles",
            "tasks"
        ],
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - admin_notifications: 1.0.2
  - calendar: 4.6.0-beta.1
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.1
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_automatedtagging: 1.17.0
  - files_downloadactivity: 1.16.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - forms: 3.3.1
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - metadata: 0.19.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - provisioning_api: 1.17.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.3
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0 (installed 2.3.0)
  - contactsinteraction: 1.8.0 (installed 1.1.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.10.1)
  - firstrunwizard: 2.16.0 (installed 2.9.0)
  - nextcloud_announcements: 1.16.0 (installed 1.9.0)
  - photos: 2.3.0 (installed 1.2.3)
  - privacy: 1.11.0 (installed 1.4.0)
  - recommendations: 1.6.0 (installed 0.8.0)
  - support: 1.10.0 (installed 1.3.0)
  - survey_client: 1.15.0 (installed 1.8.0)
  - text: 3.8.0 (installed 3.1.0)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - weather_status: 1.7.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by cscholz** [comment] 2023-11-27 10:34
Same issue on my side.

```
Aktualisierung auf 28.0.0 RC1
Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".

Detaillierte Protokollmeldungen 
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".
```

**Comment by solracsf** [comment] 2023-11-27 13:43
Duplicate of https://github.com/nextcloud/server/issues/41253 (same migration).

**Comment by susnux** [comment] 2023-12-02 02:56
Duplicate of https://github.com/nextcloud/server/issues/41253

**Closed by susnux** 2023-12-02 02:56 UTC
Labels: bug, 0. Needs triage, 28-feedback

**Comment by bmcbm** [comment] 2024-02-01 18:38
Similar issue:
`Exception: Database error when running migration 28000Date20230906104802 for app core
Index name "card_value_index" for table "oc_cards_properties" collides with the constraint on table "cards_properties".
Update failed
`
