### ISSUE TITLE
Share number in stats is not decremented when shared file/folder is deleted

### ISSUE THREAD

**Issue by GillesMocellin** [nextcloud/server#20377] opened 2020-04-09 08:10 UTC
I have wrong numbers when trying to follow shares from my users.

I also have open an issue on the app I use to gather stats : 
https://github.com/nextcloud/user_usage_report/issues/32

### Steps to reproduce
1. Create a test folder and share it (via link to be quick)
2. Use usage-report:generate from user_usage_report app, or select in oc_shares table to see the number of share for the user
3. Delete the test folder without removing the share
4. Use usage-report:generate from user_usage_report app, or select in oc_shares table to see the number of share for the user
5. See that the share is still there and counted
6. To be sure, remove the folder from the Trash and it's still there

### Expected behaviour
The share should be removed, or marked deleted (to be restored with data from Trash).
The share should not be counted in the statistics.

### Actual behaviour
The number of shares for that user is still the same, not decremented.

### Server configuration

**Nextcloud version:** 17.0.5 from 17.0.5-fpm docker image

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**List of activated apps:**
user_usage_report

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

**Comment by szaimen** [comment] 2021-05-31 11:56
Duplicate of https://github.com/nextcloud/user_usage_report/issues/32

**Closed by szaimen** 2021-05-31 11:56 UTC
Labels: 0. Needs triage, bug
