### ISSUE TITLE
SMB/CIFS External Storage App - cannot mount directories with spaces

### ISSUE THREAD

**Issue by jcbdg18** [nextcloud/server#11265] opened 2018-09-18 07:01 UTC
### Steps to reproduce
1. Create a link with External Storage APP connect with SMB/CIFS
2. Mount a Windows network share
3. with a subdirectory with spaces as 'installasjon/10 - Prosjekter'

### Expected behaviour
If i mount a Windows share with a subdirectory that has spaces, i get an error:
Share name: lagring
Subdir name: 'installasjon/10 - Prosjekter'

I have tested it with several variations as '\040', or '%20'. Always i get an error. If i mount the share with sub-dir manual on my ubuntu client with smb://.../lagring/installasjon/10%20-%20Prosjekter, it works, but not in the External Storage App.

### Actual behaviour
Tell us what happens instead
Cannot mount external directory, I get the error message: 'Some of the configured external mount points are not connected. Please click on the red row(s) for more information' 
I get no error in the logs.

### Server configuration

**Operating system**:
Ubuntu 18.04
**Web server:**
nginx/1.14.0
**Database:**
psql (PostgreSQL) 10.5
**PHP version:**
PHP 7.2
**Nextcloud version:** (see Nextcloud admin page)
13.06
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.05
**Where did you install Nextcloud from:**
Installed from nextcloud download
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - admin_notifications: 1.0.1
  - apporder: 0.5.0
  - bruteforcesettings: 1.1.0
  - comments: 1.3.0
  - dav: 1.4.7
  - defaultlinkopen: 1.1.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - onlyoffice: 2.0.2
  - password_policy: 1.3.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - theming_customcss: 1.1.0
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - activity
  - admin_audit
  - circles
  - encryption
  - firstrunwizard
  - groupfolders
  - registration
  - survey_client
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dogi.no"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.dogi.no",
        "dbtype": "pgsql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "no",
        "check_for_working_htaccess": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcached_servers": [
            "localhost",
            11211
        ],
        "0": {
            "verify_peer_off": true
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "lost_password_link": "disabled",
        "skeletondirectory": "\/local\/app\/nextcloud\/mycloud.dogi.no\/skeleton"
    }
}

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jcbdg18** [comment] 2018-09-19 05:01
I can't find any help in one of the other threads. No one som had the same problem?

**Comment by the-essay** [comment] 2018-12-04 11:14
Hi,

I'm facing the exact same behavior with a share called "Management - open Projects"
I would be very appreciated for any help.

**Comment by szaimen** [comment] 2021-05-21 11:35
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-21 11:35 UTC
Labels: 0. Needs triage, bug, feature: external storage
