### ISSUE TITLE
[Freature Request] Refresh directory content

### ISSUE THREAD

**Issue by Grimeton** [nextcloud/server#5581] opened 2017-07-01 19:07 UTC
Hi,

everytime I upload something via the client and wait for it in the Web UI to appear I'd be happy to have a refresh button that refreshes the directory's content. Reloading the whole page is an option of course, but takes much longer, especially on slow connection, than just updating the directory's content should take.

KR,

G.

**Comment by MorrisJobke** [comment] 2017-08-15 20:27
Duplicate of #2742

**Closed by MorrisJobke** 2017-08-15 20:27 UTC
