### ISSUE TITLE
Updated to 16.0.4 - Favourites don't seem to work anymore

### ISSUE THREAD

**Issue by markdix-zimbo** [nextcloud/server#17063] opened 2019-09-09 13:13 UTC
### Steps to reproduce
1. Update to 16.0.4
2. Add a file e.g. an excel file to the favourites. Go to favourites, the file will probably open the first time in preview and then won't open. When you click on the file the left-hand menu disappears and nothing happens. 
3. If you add a file and then a folder same thing happens i.e. the file in the favorites root won't open. 

If I don't use favorites and go through the folders to find the file it opens fine. It is just when trying to access via the favourites. 

### Expected behaviour
The file should open in preview and allow you to make modifications should you want to when accessing it via favourites. 

### Actual behaviour
When selecting the file instead of a preview the left-hand menu disappears and the file/folder list shift to the left. 

### Server configuration

**Operating system**:
Ubuntu 16.04.4 LTS‬

**Web server:**
Yes

**Database:**
MySQL

**PHP version:**
7.1.24

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
from 16.0.1 to 16.0.4

**Where did you install Nextcloud from:**
Your site

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
Accessibility
 Activity 
 Collabora Online 
 Collaborative tags 
 Comments 
 Custom CSS 
 Deck 
 Deleted files 
 Draw.io 
 Federation 
 File sharing 
 First run wizard 
 Log Reader 
 Monitoring 
 Nextcloud announcements 
 Notifications 
 Password policy 
 PDF viewer 
 Plain text editor 
 Preview Generator 
Privacy
 Recommendations 
 Right click 
 Share by mail 
 Support 
 Tasks 
 Theming 
 Update notification 
 Usage survey 
 Versions 
 Video player 
 Viewer 
 Auditing / Logging 
 Default encryption module 
 Default encryption module 
 External storage support 
 Gallery 
 LDAP user and group backend 
 Notes 
 Talk 
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome

**Operating system:**
Mac

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
Uncaught TypeError: Cannot read property 'shareOwnerId' of null
    at viewer.js:106
    at Object.onEdit [as actionHandler] (viewer.js:120)
    at action (merged-index.js?v=cbff6c2c-12:10547)
    at FavoritesFileList._onClickFile (merged-index.js?v=cbff6c2c-12:5468)
    at P (underscore.js:762)
    at HTMLAnchorElement.<anonymous> (underscore.js:775)
    at HTMLAnchorElement.<anonymous> (underscore.js:122)
    at HTMLTableSectionElement.dispatch (jquery.js:4435)
    at HTMLTableSectionElement._.handle (jquery.js:4121)

b) The network log
c) ...
```
</details>

**Comment by acs-ferreira** [comment] 2019-09-11 09:00
Can't reproduce with a PDF. File opens every single time (more than 20 times tried).

**Comment by markdix-zimbo** [comment] 2019-09-11 14:28
Could it be my server setup? 

The only thing that has changed is the update from 16.0.1 to 16.0.4. 

Are there different requirements for 16.0.4?

**Comment by thrdroom** [comment] 2019-09-19 16:13
Same problem over here. Also after updating from 16.0.1 to 16.0.4.

**Comment by kesselb** [comment] 2019-09-26 20:35
Does this happen with every file? 
Is the file shared to you or shared by you to someone?

**Comment by markdix-zimbo** [comment] 2019-09-27 06:44
Hi @kesselb 

It happens when I make a file a favourite not when sharing. Yes it happens to all files. 

What is strange is when I first make it a favourite and try open the file, it works. When I try after navigating elsewhere it then won't open when I come back to favourites. 

The console shows this error: Uncaught TypeError: Cannot read property 'shareOwnerId' of null

If I make a folder a favourite with the file in that folder it works fine. The issue is only present when making the actual file a favourite.

**Comment by szaimen** [comment] 2021-06-07 15:52
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 15:52 UTC
Labels: 0. Needs triage, bug
