### ISSUE TITLE
Uploading existing file with UI doesn’t provide options to replace

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/server#27127] opened 2021-05-26 19:52 UTC
main.js?v=64864097-27:1 TypeError: Cannot read property 'replace' of undefined
    at Object._build (main.js?v=64864097-27:1)
    at Object.init (main.js?v=64864097-27:1)
    at e.fn.init.o.a.fn.octemplate (main.js?v=64864097-27:1)
    at Object.<anonymous> (main.js?v=64864097-27:1)
    at Object.<anonymous> (main.js?v=64864097-27:1)
    at l (main.js?v=64864097-27:1)
    at Object.fireWith [as resolveWith] (main.js?v=64864097-27:1)
    at Object.Deferred.m.each.r.<computed> [as resolve] (main.js?v=64864097-27:1)
    at Object.success (main.js?v=64864097-27:1)
    at l (main.js?v=64864097-27:1) "data:" undefined

**Comment by stefan-niedermann** [comment] 2021-05-27 14:09
Looks like a duplicate of #27128 - i'll close this in favor of the other issue therefore.

**Closed by stefan-niedermann** 2021-05-27 14:09 UTC
Labels: 0. Needs triage, bug
