### ISSUE TITLE
Update 13.0.4 to 14.0.3 via web interface results in Internal Server Error

### ISSUE THREAD

**Issue by tester1230980582340923-409** [nextcloud/server#12211] opened 2018-11-02 10:21 UTC
### Steps to reproduce
1. Update from 13.0.4 to 14.0.3 via web interface with data dir on external storage via symlink

### Expected behaviour
When applying the update, all the internal checks seem to pass and the upgrade installs successfully.

### Actual behaviour
After the upgrade, the nextcloud instance returns an internal server error. I resolved this by using the occ upgrade command via terminal `sudo -u www-data php /var/www/nextcloud/occ upgrade`. The only error messages whilst performing the upgrade were related to disabling incompatible apps. I believe this may be permissions related, but it seems clear that the web interface updater is not robust enough.

### Server configuration

**Operating system**:
Ubuntu 16 LTS
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
13.0.4
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - apporder: 0.5.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - checksum: 0.4.1
  - cloud_federation_api: 0.0.1
  - cms_pico: 0.9.7
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - drawio: 0.9.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mindmaps: 0.1.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - polls: 0.8.3
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - w2g2: 2.2.3
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - admin_notifications
  - announcementcenter
  - circles
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_reader
  - mail
  - ojsxc
  - passman
  - quota_warning
  - rainloop
  - ransomware_protection
  - richdocuments
  - spreed
  - unsplashlogin
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.wgsair.com",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, local
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome
**Operating system:**
windows 7

**Comment by MorrisJobke** [comment] 2018-11-02 11:01
@tester1230980582340923-409 Could you check the nextcloud.log for the stack trace of this internal server error?

**Comment by tester1230980582340923-409** [comment] 2018-11-02 12:16
What should I search for in the log?

It looks like it might be an error with the calendar app because it's got mountains of errors about calendar app upgrade and permissions, but I can't see a specific reference to the 500 error.

**Comment by MorrisJobke** [comment] 2018-11-02 12:48
> What should I search for in the log?
> 
> It looks like it might be an error with the calendar app because it's got mountains of errors about calendar app upgrade and permissions, but I can't see a specific reference to the 500 error.

On the page with the internal server error there was a reference - that would be the one we need. Maybe you can look into the logs and check the first one that is on log level 3 or 4 (error and fatal) that happened after the upgrade.

**Comment by tester1230980582340923-409** [comment] 2018-11-02 14:52
Ah. I didn't log it, apologies. I did notice the location of the request for these two logs which was for my local IP address so I imagine it was when I double checked it was broken over the LAN.

```
{"reqId":"IPFwkvyWtJ1t8TOEXedH","level":3,"time":"2018-11-02T08:55:16+00:00","remoteAddr":"***","user":"--","app":"index","method":"GET","url":"\/cloud\/index.php\/login","message":{"Exception":"Error","Message":"Class 'OCP\\Config' not found","Code":0,"Trace":[{"file":"\/var\/www\/cloud\/apps\/files_reader\/lib\/Hooks.php","line":41,"function":"get","class":"OCA\\Files_Reader\\Config","type":"::","args":["epub_enable","true"]},{"file":"\/var\/www\/cloud\/lib\/private\/legacy\/hook.php","line":106,"function":"announce_settings","class":"OCA\\Files_Reader\\Hooks","type":"::","args":[{"array":{"oc_debug":"false","oc_isadmin":"false","backendAllowsPasswordConfirmation":"true","oc_dataURL":"false","oc_webroot":"\"\/cloud\"","oc_appswebroots":"{\"activity\":\"\/cloud\/apps\/activity\",\"admin_notifications\":\"\/cloud\/apps\/admin_notifications\",\"announcementcenter\":\"\/cloud\/apps\/announcementcenter\",\"apporder\":\"\/cloud\/apps\/apporder\",\"bruteforcesettings\":\"\/cloud\/apps\/bruteforcesettings\",\"calendar\":\"\/cloud\/apps\/calendar\",\"checksum\":\"\/cloud\/apps\/checksum\",\"circles\":\"\/cloud\/apps\/circles\",\"cloud_federation_api\":\"\/cloud\/apps\/cloud_federation_api\",\"cms_pico\":\"\/cloud\/apps\/cms_pico\",\"comments\":\"\/cloud\/apps\/comments\",\"contacts\":\"\/cloud\/apps\/contacts\",\"dav\":\"\/cloud\/apps\/dav\",\"deck\":\"\/cloud\/apps\/deck\",\"drawio\":\"\/cloud\/apps\/drawio\",\"federatedfilesharing\":\"\/cloud\/apps\/federatedfilesharing\",\"federation\":\"\/cloud\/apps\/federation\",\"files\":\"\/cloud\/apps\/files\",\"files_accesscontrol\":\"\/cloud\/apps\/files_accesscontrol\",\"files_automatedtagging\":\"\/cloud\/apps\/files_automatedtagging\",\"files_external\":\"\/cloud\/apps\/files_external\",\"files_markdown\":\"\/cloud\/apps\/files_markdown\",\"files_pdfviewer\":\"\/cloud\/apps\/files_pdfviewer\",\"files_reader\":\"\/cloud\/apps\/files_reader\",\"files_sharing\":\"\/cloud\/apps\/files_sharing\",\"files_texteditor\":\"\/cloud\/apps\/files_texteditor\",\"files_trashbin\":\"\/cloud\/apps\/files_trashbin\",\"files_versions\":\"\/cloud\/apps\/files_versions\",\"files_videoplayer\":\"\/cloud\/apps\/files_videoplayer\",\"firstrunwizard\":\"\/cloud\/apps\/firstrunwizard\",\"gallery\":\"\/cloud\/apps\/gallery\",\"groupfolders\":\"\/cloud\/apps\/groupfolders\",\"logreader\":\"\/cloud\/apps\/logreader\",\"lookup_server_connector\":\"\/cloud\/apps\/lookup_server_connector\",\"mindmaps\":\"\/cloud\/apps\/mindmaps\",\"nextcloud_announcements\":\"\/cloud\/apps\/nextcloud_announcements\",\"notes\":\"\/cloud\/apps\/notes\",\"notifications\":\"\/cloud\/apps\/notifications\",\"oauth2\":\"\/cloud\/apps\/oauth2\",\"passman\":\"\/cloud\/apps\/passman\",\"password_policy\":\"\/cloud\/apps\/password_policy\",\"polls\":\"\/cloud\/apps\/polls\",\"provisioning_api\":\"\/cloud\/apps\/provisioning_api\",\"quota_warning\":\"\/cloud\/apps\/quota_warning\",\"rainloop\":\"\/cloud\/apps\/rainloop\",\"ransomware_protection\":\"\/cloud\/apps\/ransomware_protection\",\"serverinfo\":\"\/cloud\/apps\/serverinfo\",\"sharebymail\":\"\/cloud\/apps\/sharebymail\",\"survey_client\":\"\/cloud\/apps\/survey_client\",\"systemtags\":\"\/cloud\/apps\/systemtags\",\"tasks\":\"\/cloud\/apps\/tasks\",\"theming\":\"\/cloud\/apps\/theming\",\"twofactor_backupcodes\":\"\/cloud\/apps\/twofactor_backupcodes\",\"updatenotification\":\"\/cloud\/apps\/updatenotification\",\"w2g2\":\"\/cloud\/apps\/w2g2\",\"workflowengine\":\"\/cloud\/apps\/workflowengine\"}","datepickerFormatDate":"\"M\\\/d\\\/yy\"","nc_lastLogin":0,"nc_pageLoad":1541148916,"dayNames":"[\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"]","dayNamesShort":"[\"Sun.\",\"Mon.\",\"Tue.\",\"Wed.\",\"Thu.\",\"Fri.\",\"Sat.\"]","dayNamesMin":"[\"Su\",\"Mo\",\"Tu\",\"We\",\"Th\",\"Fr\",\"Sa\"]","monthNames":"[\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"]","monthNamesShort":"[\"Jan.\",\"Feb.\",\"Mar.\",\"Apr.\",\"May.\",\"Jun.\",\"Jul.\",\"Aug.\",\"Sep.\",\"Oct.\",\"Nov.\",\"Dec.\"]","firstDay":"0","oc_config":"{\"session_lifetime\":1440,\"session_keepalive\":true,\"version\":\"14.0.3.0\",\"versionstring\":\"14.0.3\",\"enable_avatars\":true,\"lost_password_link\":null,\"modRewriteWorking\":false,\"sharing.maxAutocompleteResults\":0,\"sharing.minSearchStringLength\":0,\"blacklist_files_regex\":\"\\\\.(part|filepart)$\"}","oc_appconfig":"{\"core\":{\"defaultExpireDateEnabled\":false,\"defaultExpireDate\":null,\"defaultExpireDateEnforced\":null,\"enforcePasswordForPublicLink\":false,\"enableLinkPasswordByDefault\":false,\"sharingDisabledForUser\":false,\"resharingAllowed\":true,\"remoteShareAllowed\":true,\"federatedCloudShareDoc\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=user-sharing-federated\",\"allowGroupSharing\":true},\"files\":{\"max_chunk_size\":10485760}}","oc_defaults":"{\"entity\":\"WGS Cloud\",\"name\":\"WGS Cloud\",\"title\":\"WGS Cloud\",\"baseUrl\":\"https:\\\/\\\/www.wgsair.com\",\"syncClientUrl\":\"https:\\\/\\\/nextcloud.com\\\/install\\\/#install-clients\",\"docBaseUrl\":\"https:\\\/\\\/docs.nextcloud.com\",\"docPlaceholderUrl\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=PLACEHOLDER\",\"slogan\":\"Accessible Data Storage\",\"logoClaim\":\"\",\"shortFooter\":\"<a href=\\\"https:\\\/\\\/www.wgsair.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">WGS Cloud<\\\/a> \\u2013 Accessible Data Storage\",\"longFooter\":\"<a href=\\\"https:\\\/\\\/www.wgsair.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">WGS Cloud<\\\/a> \\u2013 Accessible Data Storage\",\"folder\":\"\"}","oc_capabilities":"{\"core\":{\"pollinterval\":60,\"webdav-root\":\"remote.php\\\/webdav\"},\"bruteforce\":{\"delay\":0},\"activity\":{\"apiv2\":[\"filters\",\"filters-api\",\"previews\",\"rich-strings\"]},\"dav\":{\"chunking\":\"1.0\"},\"files_sharing\":{\"api_enabled\":true,\"public\":{\"enabled\":true,\"password\":{\"enforced\":false},\"expire_date\":{\"enabled\":false},\"send_mail\":false,\"upload\":true,\"upload_files_drop\":true},\"resharing\":true,\"user\":{\"send_mail\":false,\"expire_date\":{\"enabled\":true}},\"group_sharing\":true,\"group\":{\"enabled\":true,\"expire_date\":{\"enabled\":true}},\"default_permissions\":31,\"federation\":{\"outgoing\":true,\"incoming\":true,\"expire_date\":{\"enabled\":true}},\"sharebymail\":{\"enabled\":true,\"upload_files_drop\":{\"enabled\":true},\"password\":{\"enabled\":true},\"expire_date\":{\"enabled\":true}}},\"files\":{\"bigfilechunking\":true,\"blacklisted_files\":[\".htaccess\"],\"undelete\":true,\"versioning\":true}}"}}]},{"file":"\/var\/www\/cloud\/lib\/private\/Template\/JSConfigHelper.php","line":277,"function":"emit","class":"OC_Hook","type":"::","args":["\\OCP\\Config","js",{"array":{"oc_debug":"false","oc_isadmin":"false","backendAllowsPasswordConfirmation":"true","oc_dataURL":"false","oc_webroot":"\"\/cloud\"","oc_appswebroots":"{\"activity\":\"\/cloud\/apps\/activity\",\"admin_notifications\":\"\/cloud\/apps\/admin_notifications\",\"announcementcenter\":\"\/cloud\/apps\/announcementcenter\",\"apporder\":\"\/cloud\/apps\/apporder\",\"bruteforcesettings\":\"\/cloud\/apps\/bruteforcesettings\",\"calendar\":\"\/cloud\/apps\/calendar\",\"checksum\":\"\/cloud\/apps\/checksum\",\"circles\":\"\/cloud\/apps\/circles\",\"cloud_federation_api\":\"\/cloud\/apps\/cloud_federation_api\",\"cms_pico\":\"\/cloud\/apps\/cms_pico\",\"comments\":\"\/cloud\/apps\/comments\",\"contacts\":\"\/cloud\/apps\/contacts\",\"dav\":\"\/cloud\/apps\/dav\",\"deck\":\"\/cloud\/apps\/deck\",\"drawio\":\"\/cloud\/apps\/drawio\",\"federatedfilesharing\":\"\/cloud\/apps\/federatedfilesharing\",\"federation\":\"\/cloud\/apps\/federation\",\"files\":\"\/cloud\/apps\/files\",\"files_accesscontrol\":\"\/cloud\/apps\/files_accesscontrol\",\"files_automatedtagging\":\"\/cloud\/apps\/files_automatedtagging\",\"files_external\":\"\/cloud\/apps\/files_external\",\"files_markdown\":\"\/cloud\/apps\/files_markdown\",\"files_pdfviewer\":\"\/cloud\/apps\/files_pdfviewer\",\"files_reader\":\"\/cloud\/apps\/files_reader\",\"files_sharing\":\"\/cloud\/apps\/files_sharing\",\"files_texteditor\":\"\/cloud\/apps\/files_texteditor\",\"files_trashbin\":\"\/cloud\/apps\/files_trashbin\",\"files_versions\":\"\/cloud\/apps\/files_versions\",\"files_videoplayer\":\"\/cloud\/apps\/files_videoplayer\",\"firstrunwizard\":\"\/cloud\/apps\/firstrunwizard\",\"gallery\":\"\/cloud\/apps\/gallery\",\"groupfolders\":\"\/cloud\/apps\/groupfolders\",\"logreader\":\"\/cloud\/apps\/logreader\",\"lookup_server_connector\":\"\/cloud\/apps\/lookup_server_connector\",\"mindmaps\":\"\/cloud\/apps\/mindmaps\",\"nextcloud_announcements\":\"\/cloud\/apps\/nextcloud_announcements\",\"notes\":\"\/cloud\/apps\/notes\",\"notifications\":\"\/cloud\/apps\/notifications\",\"oauth2\":\"\/cloud\/apps\/oauth2\",\"passman\":\"\/cloud\/apps\/passman\",\"password_policy\":\"\/cloud\/apps\/password_policy\",\"polls\":\"\/cloud\/apps\/polls\",\"provisioning_api\":\"\/cloud\/apps\/provisioning_api\",\"quota_warning\":\"\/cloud\/apps\/quota_warning\",\"rainloop\":\"\/cloud\/apps\/rainloop\",\"ransomware_protection\":\"\/cloud\/apps\/ransomware_protection\",\"serverinfo\":\"\/cloud\/apps\/serverinfo\",\"sharebymail\":\"\/cloud\/apps\/sharebymail\",\"survey_client\":\"\/cloud\/apps\/survey_client\",\"systemtags\":\"\/cloud\/apps\/systemtags\",\"tasks\":\"\/cloud\/apps\/tasks\",\"theming\":\"\/cloud\/apps\/theming\",\"twofactor_backupcodes\":\"\/cloud\/apps\/twofactor_backupcodes\",\"updatenotification\":\"\/cloud\/apps\/updatenotification\",\"w2g2\":\"\/cloud\/apps\/w2g2\",\"workflowengine\":\"\/cloud\/apps\/workflowengine\"}","datepickerFormatDate":"\"M\\\/d\\\/yy\"","nc_lastLogin":0,"nc_pageLoad":1541148916,"dayNames":"[\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"]","dayNamesShort":"[\"Sun.\",\"Mon.\",\"Tue.\",\"Wed.\",\"Thu.\",\"Fri.\",\"Sat.\"]","dayNamesMin":"[\"Su\",\"Mo\",\"Tu\",\"We\",\"Th\",\"Fr\",\"Sa\"]","monthNames":"[\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"]","monthNamesShort":"[\"Jan.\",\"Feb.\",\"Mar.\",\"Apr.\",\"May.\",\"Jun.\",\"Jul.\",\"Aug.\",\"Sep.\",\"Oct.\",\"Nov.\",\"Dec.\"]","firstDay":"0","oc_config":"{\"session_lifetime\":1440,\"session_keepalive\":true,\"version\":\"14.0.3.0\",\"versionstring\":\"14.0.3\",\"enable_avatars\":true,\"lost_password_link\":null,\"modRewriteWorking\":false,\"sharing.maxAutocompleteResults\":0,\"sharing.minSearchStringLength\":0,\"blacklist_files_regex\":\"\\\\.(part|filepart)$\"}","oc_appconfig":"{\"core\":{\"defaultExpireDateEnabled\":false,\"defaultExpireDate\":null,\"defaultExpireDateEnforced\":null,\"enforcePasswordForPublicLink\":false,\"enableLinkPasswordByDefault\":false,\"sharingDisabledForUser\":false,\"resharingAllowed\":true,\"remoteShareAllowed\":true,\"federatedCloudShareDoc\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=user-sharing-federated\",\"allowGroupSharing\":true},\"files\":{\"max_chunk_size\":10485760}}","oc_defaults":"{\"entity\":\"WGS Cloud\",\"name\":\"WGS Cloud\",\"title\":\"WGS Cloud\",\"baseUrl\":\"https:\\\/\\\/www.wgsair.com\",\"syncClientUrl\":\"https:\\\/\\\/nextcloud.com\\\/install\\\/#install-clients\",\"docBaseUrl\":\"https:\\\/\\\/docs.nextcloud.com\",\"docPlaceholderUrl\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=PLACEHOLDER\",\"slogan\":\"Accessible Data Storage\",\"logoClaim\":\"\",\"shortFooter\":\"<a href=\\\"https:\\\/\\\/www.wgsair.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">WGS Cloud<\\\/a> \\u2013 Accessible Data Storage\",\"longFooter\":\"<a href=\\\"https:\\\/\\\/www.wgsair.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">WGS Cloud<\\\/a> \\u2013 Accessible Data Storage\",\"folder\":\"\"}","oc_capabilities":"{\"core\":{\"pollinterval\":60,\"webdav-root\":\"remote.php\\\/webdav\"},\"bruteforce\":{\"delay\":0},\"activity\":{\"apiv2\":[\"filters\",\"filters-api\",\"previews\",\"rich-strings\"]},\"dav\":{\"chunking\":\"1.0\"},\"files_sharing\":{\"api_enabled\":true,\"public\":{\"enabled\":true,\"password\":{\"enforced\":false},\"expire_date\":{\"enabled\":false},\"send_mail\":false,\"upload\":true,\"upload_files_drop\":true},\"resharing\":true,\"user\":{\"send_mail\":false,\"expire_date\":{\"enabled\":true}},\"group_sharing\":true,\"group\":{\"enabled\":true,\"expire_date\":{\"enabled\":true}},\"default_permissions\":31,\"federation\":{\"outgoing\":true,\"incoming\":true,\"expire_date\":{\"enabled\":true}},\"sharebymail\":{\"enabled\":true,\"upload_files_drop\":{\"enabled\":true},\"password\":{\"enabled\":true},\"expire_date\":{\"enabled\":true}}},\"files\":{\"bigfilechunking\":true,\"blacklisted_files\":[\".htaccess\"],\"undelete\":true,\"versioning\":true}}"}}]},{"file":"\/var\/www\/cloud\/lib\/private\/TemplateLayout.php","line":176,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->","args":[]},{"file":"\/var\/www\/cloud\/lib\/private\/legacy\/template.php","line":210,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["guest",""]},{"file":"\/var\/www\/cloud\/lib\/private\/Template\/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/cloud\/lib\/base.php","line":399,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/cloud\/lib\/base.php","line":942,"function":"printUpgradePage","class":"OC","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"\/var\/www\/cloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/cloud\/apps\/files_reader\/lib\/config.php","Line":28,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/70.0.3538.77 Safari\/537.36","version":"13.0.4.0"}
{"reqId":"IPFwkvyWtJ1t8TOEXedH","level":3,"time":"2018-11-02T08:55:16+00:00","remoteAddr":"***","user":"--","app":"no app in context","method":"GET","url":"\/cloud\/index.php\/login","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"theming.Theming.getImage\" as such route does not exist.","Code":0,"Trace":[{"file":"\/var\/www\/cloud\/lib\/private\/Route\/Router.php","line":337,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"10"},1]},{"file":"\/var\/www\/cloud\/lib\/private\/Route\/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"10"},false]},{"file":"\/var\/www\/cloud\/lib\/private\/URLGenerator.php","line":79,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"10"}]},{"file":"\/var\/www\/cloud\/apps\/theming\/lib\/ThemingDefaults.php","line":227,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"10"}]},{"file":"\/var\/www\/cloud\/lib\/public\/Defaults.php","line":187,"function":"getLogo","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[true]},{"file":"\/var\/www\/cloud\/core\/templates\/layout.guest.php","line":34,"function":"getLogo","class":"OCP\\Defaults","type":"->","args":[]},{"file":"\/var\/www\/cloud\/lib\/private\/Template\/Base.php","line":179,"args":["\/var\/www\/cloud\/core\/templates\/layout.guest.php"],"function":"include"},{"file":"\/var\/www\/cloud\/lib\/private\/Template\/Base.php","line":151,"function":"load","class":"OC\\Template\\Base","type":"->","args":["\/var\/www\/cloud\/core\/templates\/layout.guest.php",null]},{"file":"\/var\/www\/cloud\/lib\/private\/legacy\/template.php","line":207,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[null]},{"file":"\/var\/www\/cloud\/lib\/private\/legacy\/template.php","line":238,"function":"fetchPage","class":"OC_Template","type":"->","args":[null]},{"file":"\/var\/www\/cloud\/lib\/private\/Template\/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/cloud\/lib\/private\/legacy\/template.php","line":359,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/cloud\/index.php","line":83,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[{"__class__":"Error"},500]}],"File":"\/var\/www\/cloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":113,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/70.0.3538.77 Safari\/537.36","version":"13.0.4.0"}
```

**Comment by MorrisJobke** [comment] 2018-11-02 22:49
This seems to be a problem with `files_reader` -> duplicate of #11572

**Closed by MorrisJobke** 2018-11-02 22:49 UTC
Labels: feature: install and update, needs info

**Comment by MorrisJobke** [comment] 2018-11-02 22:50
Solution until the app is fixed: disable it before updating (removing it from the apps folder or removing the DB entry in oc_appconfig with the appid and the configkey enabled is both a valid approach to disable it if the instance is broken).
