### ISSUE TITLE
Allow ordering of user lists

### ISSUE THREAD

**Issue by OverByThere** [nextcloud/server#4114] opened 2017-03-28 11:03 UTC
Allow admins to click on column titles in the /settings/users area to re-order the lists.

Very helpful with large lists.

See attached screenshot for example of where it would be helpful.
<img width="1766" alt="screen shot 2017-03-28 at 12 02 10" src="https://cloud.githubusercontent.com/assets/6248551/24401988/90f17346-13ae-11e7-943b-823849a779c7.png">

**Comment by MorrisJobke** [comment] 2017-03-28 15:34
@OverByThere Just as a sidenote: If you look for a specific user also the search in the top right works 😉

**Comment by MorrisJobke** [comment] 2017-04-05 00:31
Just found that this is a duplicate of #3230

**Closed by MorrisJobke** 2017-04-05 00:31 UTC
Labels: enhancement, feature: users and groups
