### ISSUE TITLE
can not add federated share to my nextcloud due to slash in URL

### ISSUE THREAD

**Issue by vojeroen** [nextcloud/server#5256] opened 2017-06-05 19:41 UTC
Me and a friend are both running our own Nextcloud server. He shared a directory with me using a link, which I want to add to my Nextcloud as a federated share. Important to note is that in both cases, our Nextclouds are not installed in the root of the URL but in mydomain.com/nextcloud. When I enter this URL to add the directory to my Nextcloud, it complains that the address may not contain a slash. We are both running NC 12.

We have used federated shares without any problems in the past. At that point I was running NC 12 and he was running ownCloud 9.1.

### Steps to reproduce
1. Share a link of a directory from NC server 1.
2. Open the link in your browser.
3. Click on "Add to my Nextcloud" in the top right.
4. Enter the address of NC server 2 with the format user@mydomain/nextcloud.

### Expected behaviour
A federated share should be created between NC server 1 and NC server 2.

### Actual behaviour
Nextcloud complains that a slash is not allowed in the part after the "@".

### Server configuration

**Operating system**: Raspbian

**Web server:** Apache 2.4

**Database:** PostgreSQL 9.4

**PHP version:** 5.6

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from ownCloud 9.1 -> NC 10 -> NC 11 -> NC 12

**Where did you install Nextcloud from:** tar files

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
```
</details>

Please let me know if any other information is required.

**Comment by blizzz** [comment] 2017-06-12 10:55
Does it work if you share the file/dir directly to your friend?

@schiessle

**Comment by vojeroen** [comment] 2017-06-12 11:29
What do you mean exactly with sharing directly?

**Comment by blizzz** [comment] 2017-06-12 11:54
@vojeroen being logged in, Files → Sidebar → Sharing → enter the federation id

**Comment by vojeroen** [comment] 2017-06-12 12:27
@blizzz we tried this and I can confirm that direct sharing works as expected.

**Comment by skjnldsv** [comment] 2019-06-06 17:00
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

![Capture d’écran_2019-06-06_18-59-50](https://user-images.githubusercontent.com/14975046/59051523-60f5d280-888d-11e9-8112-15ac07d21474.png)

**Closed** 2019-06-06 17:01 UTC
Labels: bug, feature: federation, feature: sharing
