### ISSUE TITLE
Statistics for group members

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4155] opened 2017-03-30 06:37 UTC
It should be possible as admin/subadmin to get following information of all group members via API:

* [x] assigned quota, used quota
* [x] is it an active user?
* [x] number of shared links by week, month, 6 month
* [x] date of invitation (user creation)
* [x] date of last login

cc @oparoz @daita @icewind1991 

Should we add this to the provisioning API? Maybe @rullzer and @schiessle have some feedback for this? Go would also be to collect this information for a whole group with one request, otherwise it could be the case that we need to send 100 requests if the group has 100 members, or what do you think?

**Comment by rullzer** [comment] 2017-03-30 08:17
> number of shared links by week, month, 6 month

Currently there is no API to efficiently fetch this.

**Comment by icewind1991** [comment] 2017-03-30 13:01
@rullzer can we add a "share time" collumn for 12?

**Comment by icewind1991** [comment] 2017-03-30 13:13
> date of invitation (user creation)

Do we know what system will be used for user managements? (internal db, ldap, ...)

**Comment by rullzer** [comment] 2017-03-30 13:33
@icewind1991 we have a share time already. But the issue is also what do you want

1. A current shapshot of the state
2. a real list of all the shares in the last X days/months/years/millenia because then we also need to keep the old shares around.

**Comment by MorrisJobke** [comment] 2017-03-30 14:41
It looks like internal db as user system

**Comment by icewind1991** [comment] 2017-03-30 15:52
@rullzer audit log maybe?

**Comment by icewind1991** [comment] 2017-04-12 14:28
WIP app with the api is here: https://github.com/icewind1991/userinfo

**Comment by oparoz** [comment] 2017-04-26 13:48
@daita - Are you taking care of the last 2 items?

**Comment by daita** [comment] 2017-04-26 15:14
for the Shares, yes. But it will be integrated to the Apswhisperer app. 
Also, haven't seen anything about Date Of Invitation, but I guess I can take care of it too.

**Comment by MorrisJobke** [comment] 2017-04-26 15:36
> is it an active user?

I guess we mixed something up here: Currently we use the enabled/disabled flag, but I guess it is more like "Was the user active in the last 30 days". I guess this should not be too hard to extract.

**Comment by icewind1991** [comment] 2017-04-26 15:52
We have a last login, so we could just base it of that

**Comment by MorrisJobke** [comment] 2017-04-26 16:10
> We have a last login, so we could just base it of that

Exactly - this was also my idea.

**Comment by MorrisJobke** [comment] 2017-05-04 14:22
> number of shared links by week, month, 6 month
>  date of invitation (user creation)

Ping @icewind1991 @daita

**Closed** 2017-05-08 16:57 UTC
Labels: 4. to release, enhancement
