### ISSUE TITLE
Login won't stay logged in when checked.

### ISSUE THREAD

**Issue by ram0042** [nextcloud/server#1203] opened 2016-08-31 07:36 UTC
### Steps to reproduce
1. Log in with the "Stay logged in" box checked.
2. Close entire web browser.
3. Open the Nextcloud instance.

### Expected behaviour
The login page should not be displayed when checking "Stay logged in"

### Actual behaviour
The login page appears

### Server configuration
**Operating system**: GNU/linux

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.0.10

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Manually upgraded from a fresh install

**Where did you install Nextcloud from:** I downloaded a tar.gz archive

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment] 2016-08-31 08:42
Duplicate of https://github.com/nextcloud/server/issues/1067

**Closed by LukasReschke** 2016-08-31 08:42 UTC
