### ISSUE TITLE
[Bug]: Translation comment instead of translation

### ISSUE THREAD

**Issue by nuokh** [nextcloud/server#33192] opened 2022-07-11 07:32 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The dialog for creating a new markdown document shows what seems to be a comment relating to the translation instead of an actual translation.

![grafik](https://user-images.githubusercontent.com/9081831/178208645-5dc7b6de-d14d-4ead-ac60-ab0187038528.png)

Language is set to "Deutsch (Persönlich: Du)"

![grafik](https://user-images.githubusercontent.com/9081831/178209587-06b2c22e-747c-4a0a-b26a-fd782ae26d71.png)

Isse is fixed by setting the language to "Deutsch (Förmlich: Sie)"

### Steps to reproduce

1. Set language to "Deutsch (Persönlich: Du)"
2. Click on the "+" to create a new file
3. Button for "Neue Textdatei" shows "Benötigt keine Übersetzung. Für iOS wird nur die formelle Übersetzung verwendet (de_DE).

### Expected behavior

Comments on how to translate fields are not shown instead of the translation.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_antivirus: 3.3.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.1.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_ldap: 1.14.1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
```

**Comment by susnux** [comment] 2022-08-10 10:17
This is a duplicate of https://github.com/nextcloud/text/issues/2613

**Closed** 2022-08-10 10:20 UTC
Labels: bug, 0. Needs triage
