### ISSUE TITLE
both inline and occ upgrade of nextcloud to 21.0.1 cause OOM on Linux

### ISSUE THREAD

**Issue by jejb** [nextcloud/server#26497] opened 2021-04-10 16:36 UTC
This was on a 16GB server (upgrading from 20.0.8).  top shows the php process consuming all of memory until the oom killer destroys it.  There's no helpful error message because it's simply 'Killed'

Following the advice in 

https://help.nextcloud.com/t/nextcloud-21-update-needed/108714/34

Removing the line

'memcache.local' => '\\OC\\Memcache\\APCu'

From config/config.php allows the upgrade to proceed.

**Comment by suprovsky** [comment] 2021-04-11 07:59
Same goes in my case. Removing the aformentioned line helped me out, otherwise I was able to see my RAM usage growing up from 3 to 23 GB in htop and process kill after reaching a physical limit.

**Comment by kesselb** [comment] 2021-04-11 16:32
Duplicate of https://github.com/nextcloud/server/issues/25742.

**Closed by kesselb** 2021-04-11 16:32 UTC
Labels: 0. Needs triage, bug
