### ISSUE TITLE
Allow Flows naming

### ISSUE THREAD

**Issue by gonzalo** [nextcloud/server#38512] opened 2023-05-30 10:34 UTC
Sorry if I'm not doing it in the proper place.

As we are doing an extensive use of FAC with this app with similar notation, something I would like to have is a name filed to easily identify every flow (around 20 rules defined in our prd instance)

Nothing much to add as is a self-descriptive feature.

Thanks for your amazing work.

**Comment by joshtrichards** [comment] 2023-09-15 15:44
Duplicate of #38183

**Closed by joshtrichards** 2023-09-15 15:44 UTC
Labels: enhancement, feature: workflows
