### ISSUE TITLE
File rename does not propagate to shares

### ISSUE THREAD

**Issue by joeltheukranian** [nextcloud/server#20755] opened 2020-04-30 21:33 UTC
V18 on Ubuntu

1. User1(admin): Create Folder F1.
2. User1: Upload Text File in Folder (a.txt)
3, User1: Give access (r/w) to a.txt to another user2
4. User1: Rename text file (a.txt => a2.txt)
5. User2: View Same Folder (F1)

Result: User2 will see a.txt, not a2.txt

Expected: Rename should propagate. Or NC should provide a configuration to do this.
Note folder rename acts the same.

18.0.4 should be providing something similar for propagating contents of folders (Perhaps this setting could also be applicable to rename)

**Comment by jospoortvliet** [comment] 2020-05-03 19:59
I can not reproduce this, it worked just fine for me.

Note that we DO indeed not sync renames etc on the folder itself, or on files that are shared. So this scenario does NOT sync the rename:
1. User 1 creates file and names it a.txt
2. User 1 shares a.txt with user 2
3. User 2 renames a.txt to amazing.txt
4. User 1 still sees a.txt

But files in a shared folder are the same for all ppl who have that view - at least, that is how it works here on Nextcloud 18.0.1...
![Screenshot_20200503_215834](https://user-images.githubusercontent.com/551757/80924439-3d7f2480-8d89-11ea-931f-f4d2246068b7.png)

**Comment by joeltheukranian** [comment] 2020-05-03 20:50
Ok. But if you share, then everyone gets one copy to name as they like

If you rename the original, it doesn't rename everyone previously shared to

At least that was my understanding

Yes? This is as of 18.0.0 I thought.

There was a fix related, but I don't believe it addressed renaming. I'll
find it.

Joel

**Comment by joeltheukranian** [comment] 2020-05-03 22:09
Rats. I got the steps wrong. Sorry

User 1 renames. User 2 doesn't see it

My apologies. Long week.

I will update.

Joel

**Comment by martin-77** [comment] 2020-05-24 16:34
Got a similar issue.
I have a shared folder, renamed it from a to b.
On my side, everything works as expected. On web and on sync-client the folder is named b.
But my partner still has a folder named a - on web and on sync-client.
The folder is lying in to "root-folder". Subfolders are no problem at all. Remove share and resync is a workaround, but not a real option.

Version is 18.0.4 running on a Synology (yeah, I know, not the way it should be..., but it works)
Infrastructure: Synology is the LDAP server for the nextcloud, works rock solid.
I'll try to do further testings, don't know when I can spend time on this issue.

Greatings and thanks for this incredible work!

Martin

**Comment by szaimen** [comment] 2021-06-02 11:42
Duplicate of https://github.com/nextcloud/server/issues/2063

**Closed by szaimen** 2021-06-02 11:42 UTC
Labels: 0. Needs triage, bug
