### ISSUE TITLE
Trash got emptied unexpectedly when deleting item matching search string

### ISSUE THREAD

**Issue by chen-ky** [nextcloud/server#22275] opened 2020-08-18 02:50 UTC
### Steps to reproduce
1. Navigate to `Deleted files`.
2. Enter desired string into search box.
3. **Select all** files that matches search string.
4. Select `Delete permanently`

### Expected behaviour
Permanently delete selected files (`11.md` and `111.md` in video), matching search result (`11`), without emptying the whole trash bin.

### Actual behaviour
The whole trash bin got emptied. (`11.md`, `111.md`, `22.md`, `222.md`)

[Deleted file bug video](https://siasky.net/_AwoKA2dZeKL7rmsimbNYeGGB5RVP3kJw_bEc40h_ue4OQ)

### Server configuration

**Operating system: Ubuntu Server 20.04.1 LTS**

**Web server: Apache2 2.4.41**

**Database: mariadb v10.3.22**

**PHP version: php7.4.3**

**Nextcloud version: 19.0.1** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install: Updated from an older Nextcloud**

**Where did you install Nextcloud from: nextcloud.com archive file**

### Client configuration
**Browser: Firefox 79.0**

**Operating system: Fedora 32**

**Comment by borekon** [comment] 2020-09-10 10:07
Almost the same happens to me; the trash got emptied when new deleted files come in

**Comment by borekon** [comment] 2020-09-16 07:25
It seems fixed on the last update

**Comment by chen-ky** [comment] 2020-09-16 13:34
I can still reproduce this issue on my installation on 19.0.3

**Comment by szaimen** [comment] 2021-06-11 10:07
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-11 10:07 UTC
Labels: 0. Needs triage, bug
