### ISSUE TITLE
Cannot call user "index.html" or ".ocdata" or ".htaccess" or "nextcloud.log"

### ISSUE THREAD

**Issue by felixvf** [nextcloud/server#7003] opened 2017-10-29 15:40 UTC
### Steps to reproduce
1. Create a new user with username ".ocdata".
2. Try to login using with username ".ocdata".

### Expected behaviour
The login procedure should succeed

### Actual behaviour
The login procedure fails with an error message claiming an internal server error has happened.

### Server configuration

**Nextcloud version:** 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Docker image "nextcloud"

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

## Analysis
The Nextcloud filesystem namespace is currently ill-designed. It overlays directory entries named equal to the user names (one directory per user) with other directory entries (such as "index.html", ".ocdata", ".htaccess", "nextcloud.log").

## Suggested solution
Directory entries named equal to the user names should be placed into a directory whose only purpose is to store such directory entries and no files or directories. For example, instead of storing data of user "admin" in "/var/www/html/data/admin", store data of user "admin" in "/var/www/html/data/home/admin". Then, no name collission happens with other directory entries of "/var/www/html/data".

**Comment by MorrisJobke** [comment] 2017-10-30 08:37
I guess moving all user directories is quite hard to accomplish and the only way to work on this is to disallow those usernames from the beginning.

cc @icewind1991 @rullzer

**Comment by rullzer** [comment] 2017-10-30 15:38
Yeah just don't allow them seems the best way

**Comment by szaimen** [comment] 2021-05-21 08:59
Those userids now get already blogged during the user creation.
Hence, as I cannot reproduce the original issue anymore, I will close this ticket.

**Closed by szaimen** 2021-05-21 08:59 UTC
Labels: 1. to develop, bug, feature: users and groups, low
