### ISSUE TITLE
Noisy notifications on updating elements in a series of repeated events

### ISSUE THREAD

**Issue by soletan** [nextcloud/server#13663] opened 2019-01-18 11:04 UTC
### Steps to reproduce
1. Create a series of events by configuring some event to be repeated e.g. every day.
2. Introduce a member to this series of events.
3. Check the inbox of that user for having received some desired notification regarding the invititation.
4. Use some calendar client such as Thunderbird to adjust any single event in this series of events, e.g. to move it to a later time of day.

### Expected behaviour
* Best Case: send update notification regarding the actual change of a single event so recipients can actually benefit from it
* Least Case: do not send invitation notifications over and over again just because of some team leader keeps fixing future elements of the series e.g. to prevent interferences with additional appointments.

### Actual behaviour
Notifications regarding the invitation to the whole series of events are sent on every adjustment to any part of the series w/o visibly providing any detailed information on the actual adjustment.

### Server configuration

Mail-In-A-Box Setup

**Operating system**: Ubuntu 18.04 LTS

**Web server:** nginx

**Database:** sqlite3

**PHP version:** 7.2.10

**Nextcloud version:** 13.0.6.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated if any

**Where did you install Nextcloud from:** via MailInABox setup script

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** e.g. Firefox for WebUI, Thunderbird via CalDAV

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment] 2020-03-10 08:05
cc @georgehrke

**Comment by skjnldsv** [comment] 2020-03-10 08:08
duplicate of https://github.com/nextcloud/server/issues/13919

**Closed by skjnldsv** 2020-03-10 08:08 UTC
Labels: 0. Needs triage, bug, needs info
