### ISSUE TITLE
The weather app needs to respect the user's browser locale

### ISSUE THREAD

**Issue by mjmccarn** [nextcloud/server#42208] opened 2023-12-13 12:35 UTC
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

_Originally posted by @szaimen in https://github.com/nextcloud/server/issues/27908#issuecomment-894810618_

**Comment by mjmccarn** [comment] 2023-12-13 12:37
The lack of complaints about this issue does not mean it is not important.

For myself, I keep the nextcloud dashboard disabled solely because I don't want to deal with the requirement of teaching my users (some in the US, some in the UK) how to manually set their locale in order to get the temperature setting to display correctly.

**Comment by joshtrichards** [comment] 2023-12-13 13:12
Duplicate of #23486

I encourage you to upvote and subscribe to that issue.

**Closed by joshtrichards** 2023-12-13 13:12 UTC
