### ISSUE TITLE
Ability to disable file versioning for certain paths, extensions, filesizes, etc.

### ISSUE THREAD

**Issue by Sergio-Muriel** [nextcloud/server#49385] opened 2024-11-19 16:33 UTC
It would be great to have some kind of configuration for file versioning.

As far as i understood, once activated, currently  the file versioning works for every file dropped in the nextcloud server.
It would be awesome to avoid having some kind of files to be versioned at all.

Examples of useful options that could be used:

- Avoid or include versions for a specific path
- Avoid or include versions for a specific file extension
- Avoid or include versions depending on a filesize (Example: do not version files greater than X Mo?)

**Comment by joshtrichards** [comment] 2024-11-19 18:36
Duplicate of #17566

**Closed by joshtrichards** 2024-11-19 18:36 UTC
Labels: enhancement, 0. Needs triage, feature: versions
