### ISSUE TITLE
Theming on light color

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7401] opened 2017-12-05 17:46 UTC
On a very light color, the icons are white, but I think they should be black, or?

![image](https://user-images.githubusercontent.com/5836855/33621717-094dce80-d9ec-11e7-8b30-5b729975cd05.png)
@juliushaertl @nextcloud/theming 

Color is: F9FF00

**Comment by sunjam** [comment] 2017-12-08 04:28
Allowing clients to optionally set their own custom color from a hex color wheel would be ideal.  This is also exactly what is already done for the background color itself.

**Comment by juliushaertl** [comment] 2018-01-04 16:59
@sunjam Setting color will not work, since we just invert the icons we have. Changing to custom colors would be a quite big adjustment. Besides that the theming app should provide great default theming without having to mess with many settings.

**Comment by tobiasKaminsky** [comment] 2018-01-10 06:38
I tested it with latest master and color #F9FF00.
The top left icons are still white, but top right (search, contacts) are black.

Is it also possible that the default logo is turned to black if needed?
![image](https://user-images.githubusercontent.com/5836855/34758867-1e9f9558-f5d9-11e7-841e-04169d0d2c27.png)

**Comment by MorrisJobke** [comment] 2018-01-10 07:43
Nope the logo is the logo and will not be adjusted magically. If you theme your Nextcloud you should also adjust the logo to match.

**Comment by juliushaertl** [comment] 2018-01-10 07:51
> I tested it with latest master and color #F9FF00.
> The top left icons are still white, but top right (search, contacts) are black.

That's actually an regression. I wonder why this didn't happend to me when testing. Let me have a look.

**Comment by MorrisJobke** [comment] 2018-01-10 08:05
A - I mixed up the top left icons (app icons) with the actual logo (also in the top left) - sorry

**Comment by tobiasKaminsky** [comment] 2018-01-10 10:24
> Nope the logo is the logo and will not be adjusted magically

This is fine for me. It was just an idea :-)

**Comment by juliushaertl** [comment] 2018-01-10 12:22
Finally fixed with #7767

**Closed by juliushaertl** 2018-01-10 12:22 UTC
Labels: design, enhancement, feature: theming
