### ISSUE TITLE
Update 12.0.4 -> 12.0.5 brakes "share_folder" config.php option

### ISSUE THREAD

**Issue by magentaco** [nextcloud/server#8081] opened 2018-01-27 06:17 UTC
### Steps to reproduce
1. Have existing Nextcloud 12.0.4 (and previous versions) running using "share_foler" in config.php
2. Use the webupdater to update to v12.0.5
3. Recognize that all user's "share_foler" is not accessible. 
The message "This directory is unavailable, please check the logs or contact the administrator" is shown on the webclient. PC-clients don't sync that directory any more.

### Expected behaviour
The directory named by "shared_folder" should show all files that have been with myself.

### Actual behaviour
Directory is inaccessible by browser and does not sync by PC-clients, iOS-client shows "request failed: internal server error (500)"
I did not recognize any related information in the logs (standard log level).

### Server configuration

**Operating system**:
Debian 9

**Web server:**
apache

**Database:**
mariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
see above

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update via browser

**Comment by juliushaertl** [comment] 2018-01-30 09:19
Please provide a more detailed bug report with a complete issue template filled out, especially logs are interesting, as stated in the message you've posted: 

> The message "This directory is unavailable, please check the logs or contact the administrator" is shown on the webclient. PC-clients don't sync that directory any more.

**Comment by magentaco** [comment] 2018-02-06 09:16
I did not find associated information in the logs, however, after applying #8177 it works as expected and the share_folder contains .
In my environment this helped on v12.0.5 and v13.0.0

Changes to  lib/private/Files/Cache/Wrapper/CacheJail.php
	 */
 	public function getPathById($id) {
 		$path = $this->getCache()->getPathById($id);
 *+		if ($path === null) { 
 *+			return null; 
 *+		}
 *+
 		return $this->getJailedPath($path);
 	}

**Comment by MorrisJobke** [comment] 2018-02-06 10:19
Duplicate of #8047

**Closed by MorrisJobke** 2018-02-06 10:19 UTC
Labels: needs info
