### ISSUE TITLE
[Bug]: Cannot rename files from Recent list

### ISSUE THREAD

**Issue by mahoneyr** [nextcloud/server#42985] opened 2024-01-20 14:30 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Clicking on the Recent sidebar button displays a list of recently added files. When attempting to use the ... pulldown to rename a file on this list, an error is displayed ("Could not rename [filename])". 

### Steps to reproduce

1. Click the Recent sidebar button to display the list of recently added files
2. Click the ... pulldown menu for one of the items on the list
3. Select Rename
4. Type a new name and press enter

### Expected behavior

The file is renamed without an error

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kangaroo72** [comment] 2024-01-29 12:58
Same issue, when copying/moving the files to a recent or "favorite" marked folder - maybe related

**Comment by mahoneyr** [comment] 2024-02-02 19:03
No longer seeing this issue after upgrade to 28.0.2.

**Comment by kangaroo72** [comment] 2024-02-02 20:19
I can confirm, that the issue is solved - also with folders marked as "favorites". Nice!! - Thx

**Closed** 2024-02-09 03:04 UTC
Labels: bug, 0. Needs triage, feature: files, 28-feedback
