### ISSUE TITLE
Error: imagecreatefromstring(): /var/www/nextcloud/lib/private/legacy/OC_Image.php#645

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#26838] opened 2021-04-29 19:11 UTC
Server configuration
Operating system:
Ubuntu 20.04
Web server:

Database:
Maria DB 10.3
PHP version:
PHP 7.4
Nextcloud version: (see Nextcloud admin page)
21.0.1
Updated from an older Nextcloud/ownCloud or fresh install:
20

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"B5HQkoyBmxIq0fXvec87","level":3,"time":"2021-04-29T19:08:25+00:00","remoteAddr":"IP","user":"admin","app":"PHP","method":"GET","url":"/core/preview?fileId=233897&x=256&y=256&a=true&v=&quot;703baca742857beb5a4132fe416c59ff&quot;","message":{"Exception":"Error","Message":"imagecreatefromstring(): Couldn't create GD Image Stream out of Data at /var/www/nextcloud/lib/private/legacy/OC_Image.php#645","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Image.php","line":645,"function":"imagecreatefromstring","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Preview/Image.php","line":52,"function":"loadFromFile","class":"OC_Image","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php","line":63,"function":"getThumbnail","class":"OC\\Preview\\Image","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":244,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"21.0.1.1","id":"608b043478e5f"}

{"reqId":"B5HQkoyBmxIq0fXvec87","level":3,"time":"2021-04-29T19:08:25+00:00","remoteAddr":"ip","user":"admin","app":"PHP","method":"GET","url":"/core/preview?fileId=233897&x=256&y=256&a=true&v=&quot;703baca742857beb5a4132fe416c59ff&quot;","message":{"Exception":"Error","Message":"imagecreatefromstring(): Passed data is not in 'WBMP' format at /var/www/nextcloud/lib/private/legacy/OC_Image.php#645","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Image.php","line":645,"function":"imagecreatefromstring","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Preview/Image.php","line":52,"function":"loadFromFile","class":"OC_Image","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php","line":63,"function":"getThumbnail","class":"OC\\Preview\\Image","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":244,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"21.0.1.1","id":"608b043478efc"}

{"reqId":"B5HQkoyBmxIq0fXvec87","level":3,"time":"2021-04-29T19:08:25+00:00","remoteAddr":"ip","user":"admin","app":"PHP","method":"GET","url":"/core/preview?fileId=233897&x=256&y=256&a=true&v=&quot;703baca742857beb5a4132fe416c59ff&quot;","message":{"Exception":"Error","Message":"imagecreatefromstring(): one parameter to a memory allocation multiplication is negative or zero, failing operation gracefully\n at /var/www/nextcloud/lib/private/legacy/OC_Image.php#645","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Image.php","line":645,"function":"imagecreatefromstring","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Preview/Image.php","line":52,"function":"loadFromFile","class":"OC_Image","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php","line":63,"function":"getThumbnail","class":"OC\\Preview\\Image","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":244,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"21.0.1.1","id":"608b047087230"}
```
</details>

**Comment by acsfer** [comment] 2021-04-30 08:07
Duplicate of https://github.com/nextcloud/server/issues/24575

**Closed by acsfer** 2021-04-30 08:07 UTC
Labels: 0. Needs triage, bug
