### ISSUE TITLE
in "Personal" email visible by default

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/server#6578] opened 2017-09-20 04:56 UTC
![_2017-09-20_07-18-56](https://user-images.githubusercontent.com/32108411/30627491-320a564e-9dd9-11e7-86cd-b06be7f4113c.png)
You can make the default "Private"?

**Comment by MorrisJobke** [comment] 2017-09-20 09:27
cc @schiessle @nickvergessen

**Comment by MorrisJobke** [comment] 2018-04-04 12:36
Duplicate of #6582

**Closed by MorrisJobke** 2018-04-04 12:36 UTC
Labels: enhancement, feature: federation, feature: settings
