### ISSUE TITLE
Add Quick-Access to favorite folder in left sidepanel in files-app

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#9714] opened 2018-06-01 19:54 UTC
It would be a good feature to add a quick way to access favorite folders on the "main" view of the file app. Most Fileexplorer have such a feature to access often used directories quickly.

I have already started implementing this in the files-app, i am creating this Issue mostly to gather feedback and to check if the files-app is the right place to implement this (in opposition to an additional app wich extends the original app ( I dont know how to do this)).

This feature is going to be toggleable.
![u14qxz0h](https://user-images.githubusercontent.com/25279821/41111587-ad767432-6a7c-11e8-87c6-2eef2f61ec72.png)

**Comment by c0fe** [comment] 2018-06-01 20:55
This looks like a pretty useful feature to be honest.

@MorrisJobke @rullzer any thoughts?

**Comment by MorrisJobke** [comment] 2018-06-02 06:14
Cc @nextcloud/designers

**Comment by enoch85** [comment] 2018-06-02 08:53
:+1:

**Comment by newhinton** [comment] 2018-06-02 19:09
I have added a pull request.

The only thing which does not properly work, is the initial State of the checkbox which enables this functionality. It is properly set, but the initial state is always unchecked, regardless of the true value.

**Comment by newhinton** [comment] 2018-06-03 15:12
The trashbin and quota-indicator are list-elements which are pushed down to "dock" on the settings button. If the folderlist exceeds the size of the sidebar, it gets a scrollbar, which is fine. 
The problem: Quota and Trashbin are listelements and therefore they are pushed "under" the settingsbutton. Should they stay over that button, or is it acceptable to let them slide down?

**Comment by skjnldsv** [comment] 2018-06-03 16:48
@newhinton no, it is the expected behaviour :) 
This is intended for better accessibility on small height views which reduced the total height and show too few of the first navigations items.

**Comment by juliushaertl** [comment] 2018-06-04 16:04
While I like the idea of having favorite folders directly accessible, I fear that this will clutter the UI too much once you have more folders marked as favorite. Maybe we could just limit it to first level favorite folders or have a hard limit of 3-4 entries? Anyhow having a limit would only make sense if we could show the most recently used folders or something similar.

cc @jancborchardt

**Comment by skjnldsv** [comment] 2018-06-04 16:23
We also supports collapsible entries, we could go for this?

**Comment by newhinton** [comment] 2018-06-04 16:43
Also a stylechange could help differentiate between menuentries and favorites. Making favorites smaller could clean up the ui, but i'll need to try that out and see if it works

**Comment by c0fe** [comment] 2018-06-04 16:45
@juliushaertl what about making this into an accordion style menu where if you click you will get the full list? or perhaps show a number of items then a button "show more"?

**Comment by newhinton** [comment] 2018-06-04 16:49
Also, this is not enabled in default, so the user needs to actively decide to "clutter" his UI, so it would be an active decision by the user

**Comment by skjnldsv** [comment] 2018-06-04 16:59
> Also, this is not enabled in default, so the user needs to actively decide to "clutter" his UI, so it would be an active decision by the user

Yeah, in the end, maybe it's not that big of a deal! :)

**Comment by newhinton** [comment] 2018-06-06 17:11
@juliushaertl
After rethinking the problem, another way to solve this, would be another attribute, like quickaccess or something. We could set it in the folder contextmenu, and only show those items

The upsides:
reduces cluttering for existing users with many favorites
seperates those two features

The downsides:
adds complexity
has the ability to make favorites obsolete, because often you dont need both
wouldn't really solve the sidebar cluttering

**Comment by jancborchardt** [comment] 2018-06-07 09:30
Some design feedback:
- There should be no setting for this, it's good to be enabled
- As @skjnldsv says it should be collapsible
- It should be subentries of the "Favorites" navigation entry instead of a separate list

**Comment by skjnldsv** [comment] 2018-06-07 09:38
> No additional attribute for this, as this is unnecessarily complex and confusing.

What do you mean @jancborchardt ? :)

> There should be no setting for this, it's good to be enabled

I agree, let simplify this! :)

**Comment by jancborchardt** [comment] 2018-06-07 09:48
@skjnldsv what @newhinton said above:

> After rethinking the problem, another way to solve this, would be another attribute, like quickaccess or something. We could set it in the folder contextmenu, and only show those items

We shouldn't do that – not another separate attribute.

**Comment by c0fe** [comment] 2018-06-07 12:13
@skjnldsv is it possible to make that scrollbar much thinner? That current state, it is pretty ugly.

**Comment by skjnldsv** [comment] 2018-06-07 12:14
@c0fe it depends on browsers mostly :)
But yes, we can try to override that. iirc we already have some fixes for that!

**Comment by skjnldsv** [comment] 2018-06-07 12:27
@c0fe please suggest pr and screenshots :D

**Comment by newhinton** [comment] 2018-06-07 12:30
@skjnldsv
If you tell me where an example is, i'll try to include it in the next changes

**Comment by skjnldsv** [comment] 2018-06-07 12:31
@newhinton about the scrollbar?
No, it's better to split pull requests :)

**Comment by newhinton** [comment] 2018-06-07 12:32
Okay :)

**Comment by c0fe** [comment] 2018-06-07 12:35
@skjnldsv ok will do

@newhinton i will just create an PR once I see your PR

**Comment by newhinton** [comment] 2018-06-07 14:50
i have updated the style and disabled the ability to turn this feature off.

This is the current style:

<a href="https://www.imagebanana.com/s/1081/C6aNZs4u.html" target="_blank"><img src="https://s2.imagebanana.com/file/180607/thb/C6aNZs4u.png" title="Bild auf ImageBanana anzeigen"></a>

@jancborchardt I am really not quiet fond of that whole collapsible idea. It stands in conflict to my "one-click-to-destination"-approach most common desktop-fileexplorers use. There is already a way to access the whole list with an additional click, so i would try to minimize it to the bare minimum. Also, since there is no preselection of the first n elements of that collapsed list, it wouldn't really help the user, since the only sensible way of sorting is to sort by alphabet or most recent, which are not quiet right for this feature. And it will take considerable time to change the code to be able to collapse in this navbar.

**Comment by newhinton** [comment] 2018-06-07 15:59
I have experimented with this idea, and while the Content of those links are placeholder, i think the rest looks quiet good

![2018-06-07 17_55_04-window](https://user-images.githubusercontent.com/25279821/41111469-59246fba-6a7c-11e8-84a7-858338cf5f39.jpg)

**Comment by c0fe** [comment] 2018-06-07 16:12
@newhinton my suggestions are:

- Remove the exclamation point (!)
- Make "Expand/Collapse" subscripts next to Favorites and color gray

@skjnldsv what do you think?

**Comment by skjnldsv** [comment] 2018-06-07 17:21
@newhinton Did you edit the style of the subitems?
It is not supposed to look like that at all! :thinking:

**Comment by newhinton** [comment] 2018-06-07 22:03
@skjnldsv I added some new ones to experiment with different styles.
None of the styles before solved the cluttering problem, or even made this problem smaller. 
While the latest approach does not solve it fully, and introduces some organizational problems, it takes a clean and simple approach, which has a really small footprint.
It also creates a clear distinction between two different elements of the navbar, the "main"-elements, like Favorites, Recent orAll Files, and a second type of element, which has a completely different function, in this case directly hardlinking to a specific folder.
I think those elements should be clearly visually seperated, which i achieved with this.

**Comment by skjnldsv** [comment] 2018-06-08 04:40
Aside from the new caption items, you should not use anything else than what's in the docs, or we'll lose all the unification work we did :)

**Comment by newhinton** [comment] 2018-06-13 07:55
Those are my two versions. I dont think that the big one is really what we want, it just does not look "clean", in my opinion it's bulky and unnessessary obtrusive

![2018-06-13 09_06_22-](https://user-images.githubusercontent.com/25279821/41337518-b568e0a4-6eef-11e8-8f12-c6b6933b149c.jpg)

**Comment by skjnldsv** [comment] 2018-06-13 08:06
@newhinton See https://github.com/nextcloud/server/pull/9720#pullrequestreview-126879625

> `.app-navigation-subelement`
> Okay, I get it now! :)
> There is already a standard for this:
> Look at our documentation : https://docs.nextcloud.com/server/13/developer_manual/design/navigation.html

**Comment by newhinton** [comment] 2018-06-13 08:52
@skjnldsv 
Yes, i have seen it, but that's not the point i wanted to make. I dont think that the Quickaccess is a feature we should introduce, because it would create more ui-clutter and would be highly unorganized with the current stlyeguide. Which is not what we want, and as a result of that, we should not include it until a good solution can be found.

**Comment by newhinton** [comment] 2018-06-17 14:12
![2018-06-17 16_11_32-window](https://user-images.githubusercontent.com/25279821/41508710-336008fa-7249-11e8-9f4d-ddc814bd23cc.png)

**Comment by newhinton** [comment] 2018-06-17 19:12
@skjnldsv I have changed the design, with the styleguide in mind. I have also added sorting to this list, this should make custom ordering easier to implement in the future.

**Comment by newhinton** [comment] 2018-07-20 23:13
@skjnldsv Can i close this issue, and if yes, how do you handle successful issue-closing? Is there a tag to mark it as successfully closed other than the label '4. to release' ?

**Comment by newhinton** [comment] 2018-07-20 23:16
@skjnldsv Oh, and i have seen that the star-icon was removed for the Navbarelement, what was the design desicion behind that? To me it looks a little bit strange that there is only blank space, it seems so empty :)

**Comment by skjnldsv** [comment] 2018-07-21 12:57
@newhinton, no descision, just an error, we'll add it back :)

**Closed by skjnldsv** 2018-07-21 12:57 UTC
Labels: 3. to review, enhancement, feature: files
