### ISSUE TITLE
PHP 500 error in 14072 and 14099

### ISSUE THREAD

**Issue by jameslao** [nextcloud/server#16039] opened 2019-06-21 18:40 UTC
Installed snap --edge on Ubuntu 19.10. It worked fine on 6/18 (version 14062) but then the auto-updated snap begins to break the following day (14072 and 14099). Apache log shows repeated error every few seconds

[21-Jun-2019 18:35:31 UTC] PHP Fatal error:  Class OCA\Support\Subscription\SubscriptionAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Support\Subscription\ISubscription::hasExtendedSupport) in /snap/nextcloud/14099/htdocs/apps/support/lib/Subscription/SubscriptionAdapter.php on line 30
[21-Jun-2019 18:35:32 UTC] PHP Fatal error:  Class OCA\Support\Subscription\SubscriptionAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Support\Subscription\ISubscription::hasExtendedSupport) in /snap/nextcloud/14099/htdocs/apps/support/lib/Subscription/SubscriptionAdapter.php on line 30
[21-Jun-2019 18:35:34 UTC] PHP Fatal error:  Class OCA\Support\Subscription\SubscriptionAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Support\Subscription\ISubscription::hasExtendedSupport) in /snap/nextcloud/14099/htdocs/apps/support/lib/Subscription/SubscriptionAdapter.php on line 30
[21-Jun-2019 18:35:36 UTC] PHP Fatal error:  Class OCA\Support\Subscription\SubscriptionAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Support\Subscription\ISubscription::hasExtendedSupport) in /snap/nextcloud/14099/htdocs/apps/support/lib/Subscription/SubscriptionAdapter.php on line 30
[21-Jun-2019 18:35:37 UTC] PHP Fatal error:  Class OCA\Support\Subscription\SubscriptionAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Support\Subscription\ISubscription::hasExtendedSupport) in /snap/nextcloud/14099/htdocs/apps/support/lib/Subscription/SubscriptionAdapter.php on line 30
[21-Jun-2019 18:35:39 UTC] PHP Fatal error:  Class OCA\Support\Subscription\SubscriptionAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Support\Subscription\ISubscription::hasExtendedSupport) in /snap/nextcloud/14099/htdocs/apps/support/lib/Subscription/SubscriptionAdapter.php on line 30
[21-Jun-2019 18:35:41 UTC] PHP Fatal error:  Class OCA\Support\Subscription\SubscriptionAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Support\Subscription\ISubscription::hasExtendedSupport) in /snap/nextcloud/14099/htdocs/apps/support/lib/Subscription/SubscriptionAdapter.php on line 30

**Comment by kesselb** [comment] 2019-06-21 21:43
cc @juliushaertl

**Comment by jameslao** [comment] 2019-06-22 04:29
`diff 14062/htdocs/lib/public/Support/Subscription/ISubscription.php 14118/htdocs/
lib/public/Support/Subscription/ISubscription.php`

36a37,43
>
>       /**
>        * Indicates if the subscription has extended support
>        *
>        * @since 17.0.0
>        */
>       public function hasExtendedSupport(): bool;`

Seems this is causing the problem.

**Comment by juliushaertl** [comment] 2019-06-22 08:03
Ah yes, we need to implement the method so it keeps working with older versions of the support app. I'll have a look

**Comment by jameslao** [comment] 2019-06-24 06:33
Hi @juliushaertl, thanks for the reply. A quick fix (comment out this line for now?) would be appreciated - the snap auto update brings the service down everyday.

**Comment by juliushaertl** [comment] 2019-06-24 07:40
A quick fix would be to disable the support app for now :wink:

**Comment by kesselb** [comment] 2019-06-25 19:57
@rullzer can we close this issue or do you have another fix in mind? I guess `snap --edge` can be broken from time to time because its build from master. Not sure why someone would use this in prod.

@kyrofa fyi

**Comment by juliushaertl** [comment] 2019-06-25 20:00
Yes, the support app should be fixed now with the next nightly build.

**Closed by juliushaertl** 2019-06-25 20:00 UTC
Labels: 1. to develop, bug

**Comment by kyrofa** [comment] 2019-06-25 20:04
@kesselb thanks for the heads up. Indeed, the `edge` snap is based on daily master, breakage there should never be desired, but also never be surprising-- definitely not for use in any sort of production case. We typically use it for a daily CI job to make sure we don't see any regressions coming down the pipe. It's also helpful for these types of bug reports though, thanks @jameslao!

**Comment by jameslao** [comment] 2019-06-25 20:13
It was a test server - I just started using Nextcloud, and was a bit surprised that it broke down the second day I installed it. Thank you all for the help!

**Comment by kyrofa** [comment] 2019-06-25 20:15
Yeah if you want something more stable, get off of the development trunk. Try just `snap install nextcloud` instead.
