### ISSUE TITLE
Error opening pdf file with spaces in path after updating to version 21.0.2 and 20.0.10

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/server#27082] opened 2021-05-23 18:35 UTC
### Steps to reproduce
Click on a pdf file that has got spaces in its own path.

### Expected behaviour
PDF viewer opens and show the file.

### Actual behaviour
PDF viewer opens and show the error below:
Missing PDF file.
PDF.js v2.5.207 (build: 0974d6052)
Message: Missing PDF "https://xxx.xxxxxxxx.xx/remote.php/dav/files/<username>/xxx%2520xxxxxx/xxxxxxx%2520xxxxxx/xxxxx/xxxxx/xxxxxxxxxxxxxxxxxx.pdf".

In my opinion %2520 is wrong. It should be %20

## Server configuration detail

**Operating system:** Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 8.0.25

**PHP version:** 

7.4.18
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 21.0.2 - 21.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 21.0.1

**Where did you install Nextcloud from:** From nextcloud website

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - auto_groups: 1.3.1
 - bruteforcesettings: 2.1.0
 - camerarawpreviews: 0.7.11
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contactsinteraction: 1.2.0
 - data_request: 1.8.0
 - dav: 1.17.1
 - drawio: 1.0.0
 - drop_account: 1.0.2
 - extract: 1.3.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_antivirus: 3.2.0
 - files_automatedtagging: 1.11.0
 - files_downloadactivity: 1.10.0
 - files_external: 1.12.0
 - files_pdfviewer: 2.1.0
 - files_retention: 1.10.1
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_texteditor: 2.14.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - flowupload: 1.1.2
 - groupfolders: 9.0.1
 - guests: 2.0.0
 - impersonate: 1.8.0
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - metadata: 0.13.0
 - music: 1.2.0
 - nextbackup: 21.1.0
 - nextcloud_announcements: 1.10.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.0.2
 - password_policy: 1.11.0
 - photos: 1.3.0
 - piwik: 0.8.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.10.0
 - registration: 1.2.1
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - sociallogin: 4.6.0
 - socialsharing_email: 2.2.0
 - socialsharing_facebook: 2.2.0
 - spreed: 11.2.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - suspicious_login: 4.0.0
 - systemtags: 1.11.0
 - terms_of_service: 1.7.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - unsplash: 1.2.2
 - updatenotification: 1.11.0
 - user_retention: 1.4.0
 - user_status: 1.1.1
 - video_converter: 1.0.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - whiteboard: 0.0.3
 - workflow_pdf_converter: 1.6.0
 - workflow_script: 1.6.0
 - workflowengine: 2.3.0
Disabled:
 - dashboard
 - encryption
 - recommendations
 - text
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "box.percivaldi.it"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.2.1",
    "overwrite.cli.url": "https:\/\/box.percivaldi.it",
    "overwritehost": "box.percivaldi.it",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "htaccess.RewriteBase": "\/",
    "logdateformat": "r",
    "logtimezone": "Europe\/Rome",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "session_keepalive": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "trashbin_retention_obligation": "auto",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\PDF",
        "OC\\Preview\\Epub",
        "OC\\Preview\\FB2",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\Postscript",
        "OC\\Preview\\SVG",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\Font"
    ],
    "updatechecker": false,
    "updater.release.channel": "stable",
    "auth.bruteforce.protection.enabled": true,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "onlyoffice": {
        "jwt_header": "AuthorizationJwt"
    },
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "social_login_auto_redirect": false,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "drop_account",
        "radio",
        "spreed",
        "impersonate",
        "whiteboard",
        "terms_of_service",
        "socialsharing_facebook",
        "socialsharing_email",
        "nextbackup",
        "issuetemplate",
        "flowupload",
        "bruteforcesettings"
    ],
    "default_phone_region": "IT",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```
xxx.xxx.xxx.xxx- - [23/May/2021:20:29:29 +0200] "GET /remote.php/dav/files/<username>/xx%2520xxxxx/xxxxxxx%2520xxxxxxx/xxxxx/xxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxx.pdf HTTP/1.1" 404 16906 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
```
</details>

<details><summary>Nextcloud log</summary>

```
No logs when you clic on PDF file
```
</details>

<details><summary>Browser log</summary>

fetch_stream.js:128 GET https://xxx.xxxxxxxx.xxx/remote.php/dav/files/<username>/xx%2520xxxxxxx/xxxxxxx%2520xxxxxxx/xxxxx/xxxxx/xxxxxxxxxxxxxxx.pdf 404 (Not Found)

xxx.xxxxxxxxxx.xx/:1 Uncaught (in promise) MissingPDFException {message: "Missing PDF "https://xxx.xxxxxxxx.xxx/remote.php/dav/files/<username>/xx%2520xxxxxxx/xxxxxxx%2520xxxxxxx/xxxxx/xxxxx/xxxxxxxxxxxxxxx.pdf".", name: "MissingPDFException"}
</details>

**Comment by szaimen** [comment] 2021-05-23 19:03
Duplicate of https://github.com/nextcloud/files_pdfviewer/issues/381

**Closed by szaimen** 2021-05-23 19:03 UTC
Labels: 0. Needs triage, bug
