### ISSUE TITLE
Shared folders with Group Folders do  not allow deletion

### ISSUE THREAD

**Issue by jaschrock** [nextcloud/server#14815] opened 2019-03-22 20:07 UTC
### Steps to reproduce
1. Create a group folder and assign a group
2. Under that shared folder, create another folder
3. Share that folder with additional individuals (that are not a member of the group folder's group). 

### Expected behaviour
The group folder group should be able to see/write/delete (whatever their permissions are) to the folders that are under that group folder. 
Individuals within the "shared" folder under this group folder should have access as granted by the share (create/delete/etc. )
### Actual behaviour
The shared user is able to upload the document OK to the shared folder (under the group folder) but they can't delete anything from the folder (even though the share rights allow them to). The log file shows "unable to rename, source directory is not writable :"

### Server configuration

**Operating system**:
ubuntu 16.04.2 LTS
**Web server:**
apache
**Database:**
mysql 5.7.25
**PHP version:**
7.0.33
**Nextcloud version:** (see Nextcloud admin page)
15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated Nextcloud
**Where did you install Nextcloud from:**
git 
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
NOTE: This is a fix I manually applied since userCAS has an issue with the theming app. 
Results
=======
- user_cas
	- INVALID_HASH
		- lib/User/Backend.php

Raw output
==========
Array
(
    [user_cas] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/User/Backend.php] => Array
                        (
                            [expected] => 906e9cbfa16cef48a4fb52b1036a660ab9ded3154a9fd3b216e1b2837ac71eff2111f9bfb209a273f588a212e327d20aede6446c6f48fa8fb41bd5a88004c8c2
                            [current] => 17da66a520b3e68be1ab706c98bcccc567031f5c3d71a32cdc9435709f995fb0fc98f4556f6ee8c1bca3ba93aec92b2e2a41b7a30dd52e418c190ffeb86fa37a
                        )

                )

        )

)
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.11.1
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.2
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_cas: 1.6.1
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - gallery


**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
openLDAP
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2019-03-25 08:31
There were some fixes for a similar case lately: #14689, #14690 and #14691. The latter two will be available in the upcoming 15.0.6. Could I ask you to try it by then again or apply the patches on your system and test again. If this still happens then we can reopen the ticket and have another look into this.

**Comment by jaschrock** [comment] 2019-04-05 13:14
Greetings,

Here is the update. I just went ahead and applied the 15.0.6 update to my test server and the behaviour is still happening. 
Thanks

Alan

**Comment by jaschrock** [comment] 2019-04-09 15:50
FYI - also true in 15.0.7

**Comment by putt1ck** [comment] 2019-04-15 10:03
Can confirm we have the same issue, although the users may all have access to the group folder (and the sharing was done for other reasons, possibly just a user looking to have a sub (sub sub...) folder easily visible for those it was shared to)

**Comment by putt1ck** [comment] 2019-04-15 16:12
Additional:

if the user has appropriate access to the group folder, and navigates to the shared folder via that path, they can delete files - but not if they go via the share.

**Comment by GuidoDr** [comment] 2019-04-15 17:43
I can also confirm the same issue with 15.0.7, see here : https://github.com/nextcloud/groupfolders/issues/387

**Comment by waazdakka** [comment] 2019-04-26 12:00
Same issue here in 16.0.0 beta. 
Any way to delete these missing folders from database (while we're waiting for the patch) ?

**Comment by GuidoDr** [comment] 2019-04-26 13:44
> Any way to delete these missing folders from database (while we're waiting for the patch) ?

well someone who has access to the upper groupfolder(s) can delete these folders. So I could delete the folders that a normal users who only had access to the shared folders could not delete. Of course all users would have to contact then someone who has access to the upper groupfolder(s).
So not really a good workaround ...

**Comment by waazdakka** [comment] 2019-04-29 13:27
> well someone who has access to the upper groupfolder(s) can delete these folders. So I could delete the folders that a normal users who only had access to the shared folders could not delete. Of course all users would have to contact then someone who has access to the upper groupfolder(s).
> So not really a good workaround ...

The shared folders are on the root of my files manager :/

**Comment by juliushaertl** [comment] 2019-05-02 11:18
Closing as a duplicate of https://github.com/nextcloud/groupfolders/issues/387

**Closed by juliushaertl** 2019-05-02 11:18 UTC
Labels: 0. Needs triage, bug
