### ISSUE TITLE
Share link for deleted shared folders persists

### ISSUE THREAD

**Issue by loac54** [nextcloud/server#8353] opened 2018-02-14 10:41 UTC
If you delete a shared folder without first deleting the share, an empty item remains visible in the "shared with others" menu.
It is not possible to delete this share.
### Steps to reproduce
1. Share a folder
2. Delete the folder
3. Go to "shared with other" and see the first folder blank

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system : ubuntu 16.04.2** 

**Web server : apache2**

**Database : sqlite3**

**PHP version : *7.0*

**Nextcloud version: 13.0.0** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install: updated from owncloud 9**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - theming
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "192.168.1.50",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.1.50\/owncloud",
        "dbtype": "sqlite3",
        "version": "13.0.0.14",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one: no** local/smb/sftp/...

**Are you using encryption: no** yes/no

**Are you using an external user-backend, if yes which one: Webdav** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:Firefox / IE**

**Operating system: Windows 10**

**Comment by MorrisJobke** [comment] 2018-02-14 21:46
Looks like #4652 - @loac54 could you confirm, that this looks similar?

**Comment by MorrisJobke** [comment] 2018-02-14 21:46
cc @nextcloud/sharing

**Comment by loac54** [comment] 2018-02-15 09:47
Yes @MorrisJobke , #4652 is similar
![capture](https://user-images.githubusercontent.com/36473867/36250249-28dc313e-1235-11e8-95d7-ba7a74cd8c53.PNG)

**Comment by MorrisJobke** [comment] 2018-02-15 10:30
@loac54 I copied your steps over and we should continue over there. Let's close it as duplicate of #4652

Thanks for the report

**Closed by MorrisJobke** 2018-02-15 10:30 UTC
Labels: bug, feature: sharing
