### ISSUE TITLE
Filepicker in files appears but is empty

### ISSUE THREAD

**Issue by digitalrevisor** [nextcloud/server#25344] opened 2021-01-27 09:16 UTC
### Steps to reproduce
1. Open files in Nextcloud.
2. Tick the select box to the left for any file, or multiple files.
3. Click on "actions" in the top and select "copy/move"

### Expected behaviour
Filepicker appears showing the folders and allow you to navigate

### Actual behaviour
Filepicker modal appears but no folder is shown

### Server configuration

**Operating system:** Ubuntu 18.04.4

**Web server:** Apache2 2.4.29

**Database:** Mysql

**PHP version:** 7.4.7

**Nextcloud version:** (see Nextcloud admin page) 20.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** Nextcloud homepage https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- timetracker
	- FILE_MISSING
		- vendor/phpunit/php-file-iterator/.gitattributes

Raw output
==========
Array
(
    [timetracker] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/phpunit/php-file-iterator/.gitattributes] => Array
                        (
                            [expected] => 66ca641a348a43ff13dc52eb690674319332d7eef2fc3dd03a3e1dad66c6375a2c6146e964591dd557d880cf89bedb10c4dd188b43582de7e96108028a541f54
                            [current] => 
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

  - accessibility: 1.6.0
  - accountflow: 0.0.1
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - announcementcenter: 4.0.0
  - appointments: 1.7.15
  - apporder: 0.11.0
  - audioplayer: 3.0.0
  - bbb: 1.1.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - carnet: 0.23.7
  - circles: 0.20.6
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - conta: 0.0.1
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.3
  - descartes: 0.0.1
  - dibkunnskap: 0.0.1
  - digitalrevisorboard: 0.0.1
  - drawio: 0.9.8
  - duett: 0.0.1
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - fiken: 0.0.1
  - files: 1.15.0
  - files_antivirus: 3.1.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - fortnox: 0.0.1
  - freshbooks: 0.0.1
  - groupfolders: 8.2.0
  - hogia: 0.0.1
  - integration_dropbox: 0.0.17
  - integration_google: 0.1.5
  - integration_onedrive: 0.0.5
  - jointlytools: 0.0.1
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maestrosoft: 0.0.1
  - mail: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - officeonline: 0.0.2
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.6.3
  - powerofficego: 0.0.1
  - prisolve: 0.0.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quickbooks: 0.0.1
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - rettsdata: 0.0.1
  - sage: 0.0.1
  - savefiledestination: 0.0.1
  - sentry: 7.0.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - signer: 4.1.4
  - spreed: 10.0.5
  - sticos: 0.0.1
  - systemtags: 1.10.0
  - talk_simple_poll: 1.2.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - theming_customcss: 1.8.0
  - timemanager: 0.1.6
  - timetracker: 0.0.50
  - tripletex: 0.0.1
  - twentyfoursevenoffice: 0.0.1
  - twofactor_backupcodes: 1.9.0
  - unieconomy: 0.0.1
  - user_status: 1.0.1
  - useroidc: 0.0.1
  - videochatbbb: 0.0.1
  - viewer: 1.4.0
  - vismaeaccounting: 0.0.1
  - weather_status: 1.0.0
  - whiteboard: 0.0.3
  - workflow_pdf_converter: 1.5.0
  - workflowengine: 2.2.0
  - xero: 0.0.1
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

{
    "system": {
        "debug": false,
        "log_type": "file",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.5.2",
        "overwrite.cli.url": "https:\/\/my.domain.eu",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logfile": "\/var\/log\/nextcloud-log\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "defaultapp": "apporder",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "nb",
        "has_rebuilt_cache": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** Custom GLUU-based

### Client configuration
**Browser:**Chrome (newest as of 27.01)

**Operating system:**Windows 10 (all updates as of 27.01)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Cannot provide just yet. Which logs in specific should be provided for apache2?
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No logs just yet, also, nothing happens in nextcloud log while reproducing this issue.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Console.log is empty while running this, cannot provide network log
```
</details>

This started happening a long time ago, so we aren't sure excatly why it is happening. No errors are shown in any logs as far as I've been told (I'm working on getting the logs but I can't fetch them immediately). Our other servers with same versions of Nextcloud/Apache/PHP/Ubuntu doesn't have this issue.

Which logs should I provide regarding webserver/apache2? /var/log/error.log?

![Fildeling-Digital-Revisor (1)](https://user-images.githubusercontent.com/59980626/105969599-b9906980-6088-11eb-8db1-1ede0b95796f.png)

**Comment by szaimen** [comment] 2021-06-22 14:16
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-22 14:16 UTC
Labels: 0. Needs triage, bug

**Comment by wargreen** [comment] 2023-11-07 00:23
Hi, i comment this old issue because it seem to be the same here with 27.1.3.2.
The returned PROPFIND _seem_ to be OK.

Additionaly, when i try to go to my home from the file picker, it display an infinite loading placeholder and i got in the firefox's console `Error: Missing or invalid mandatory mime`

[Screencast.webm](https://github.com/nextcloud/server/assets/5098493/1b8c4cab-8e6e-4cfd-8358-a00a7b30f6dc)

**Comment by matiasdelellis** [comment] 2023-11-30 17:06
👍🏻

**Comment by wargreen** [comment] 2023-11-30 17:37
I think that i find the issue on my situation : 
It was an old federated share in my root folder, with a broken federation (the original server don't exist anymore).
So this file havn't any mime.
So the file picker broke.
