### ISSUE TITLE
Allow zooming of full size view in gallery app

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#10105] opened 2018-07-04 16:06 UTC
![screenshot_20180704-175513_opera touch](https://user-images.githubusercontent.com/1469150/42287011-0efe5452-7fb5-11e8-9d41-fb5514ff8881.jpg)
 
### Steps to reproduce
1. Go to gallery with a mobile device
2. Click on a picture
3. Try to pinch zoom. 

### Expected behaviour
Picture should be zoomed in. 

### Actual behaviour
Nothing, picture size and viewport remain fixed size. 

I have tried Opera and Opera Flow on Android 8.

### Server configuration

**Operating system**: Gentoo Linux 

**Web server:** Apache 2.4

**Database:** MariaDB 10.1

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Gentoo portage

**Signing status:**
<details>
<summary>No errors have been found.
</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2018-07-05 07:00
Duplicate of https://github.com/nextcloud/gallery/issues/66

**Closed by MorrisJobke** 2018-07-05 07:00 UTC
