### ISSUE TITLE
Enabling pretty links still breaks htaccess

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2941] opened 2017-01-04 16:51 UTC
Brand new, fresh install, essentially the same is happening as here: 

https://github.com/owncloud/core/issues/25964

Prior to enabling pretty links everything works fine, after enabling it everything above the 

`#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####`

Is gone, and I get a directory listing on page load instead.

NC 11.0
Ubuntu server 16.04
PHP 7.0.8
Apache 2.4.18

**Comment by nickvergessen** [comment] 2017-01-05 14:37
Which is your web user, which user owns config.php and .htaccess and how exactly are you executing the occ command (as which user)

**Comment by jasonbayton** [comment] 2017-01-05 14:47
Sure: 

Web: www-data
Owner: www-data

From within the nextcloud install directory after adding the `'htaccess.RewriteBase' => '/',` to the config file for my web-root installation: 

`sudo -u www-data php occ maintenance:update:htaccess`

To be extra sure, I completely blatted the whole server and reinstalled Ubuntu fresh. Then it happened again.

**Comment by MorrisJobke** [comment] 2017-04-04 23:49
I can't reproduce. Could the www-data user read the existing .htaccess file? Because we read the file just before and then write this plus the additional content back: https://github.com/nextcloud/server/blob/edd55b0ea9c13273695bf95d913f4dfc03e08c95/lib/private/Setup.php#L428-L428

Could you check on the permissions and if the file is actually there?

**Comment by jasonbayton** [comment] 2017-04-04 23:54
I can't reproduce it reliably, but it still occurs when I'm installing; most recently on one of my demo servers.

All installs are the same - 

* wget the latest zip
* inflate to www or html
* chown -r everything to www-data from the directory above NC root
* Carry on with install

**Comment by MorrisJobke** [comment] 2017-04-05 00:45
Mmmmh ... could you somehow brute force this? It's super hard to debug if we don't have a reliable way to reproduce this. And then maybe look into what is written to the variable in the above linked line of code. Is there anything in the logs when this happens?

**Comment by jasonbayton** [comment] 2017-04-05 06:19
I'll do a few installs and see what happens :)

**Comment by MorrisJobke** [comment] 2017-05-11 06:20
@jasonbayton Any news here?

**Comment by jasonbayton** [comment] 2017-05-11 07:39
Oh damn. I replicated it on the demo servers while I was working on them but in the rush forgot to report back.

Let me spin up some servers today and I'll let you know.

**Comment by jasonbayton** [comment] 2017-05-16 14:47
I couldn't replicate this on a few server builds recently, but it's so intermittent that doesn't really prove anything. Hmm...

**Comment by MorrisJobke** [comment] 2017-05-16 20:34
> I couldn't replicate this on a few server builds recently, but it's so intermittent that doesn't really prove anything. Hmm...

Let's close this here for now and once it occurs again we can look into it, okay?

**Closed by MorrisJobke** 2017-05-16 20:34 UTC
Labels: needs info
