### ISSUE TITLE
nextcloud20 is not supposed to upgrade to nextcloud21 when mysql56 is present

### ISSUE THREAD

**Issue by ivr588** [nextcloud/server#26742] opened 2021-04-24 17:44 UTC
Hi,

From the viewpoint of nextcloud it is a standalone instance which has apache24,php74 and mysql56-server in its environment.

My concern is that nextcloud detected the mysql environment as 56, and upgraded itself from nextcloud20 to nextcloud21 anyway. It's good that it's still working, but I'm worried right now that it's not working as it should and I'm just not noticing it.

www@cloud:/usr/local/www/nextcloud % php occ nextcloud.mysql-client --version
Nextcloud 21.0.1
www@cloud:/usr/local/www/nextcloud % 

### Steps to reproduce
1. observe warning that nextcloud21 will require mysql8
2. update nextcloud20 via its web interface
3.

### Expected behaviour
Tell us what should happen
nextcloud remaining on nextcloud20.x as there is a mysql56 environment

### Actual behaviour
Tell us what happens instead
nextcloud upgrades to nextcloud21.x which was unexpected

### Server configuration
**Operating system:**
freebsd-12.2-p6
**Web server:**
apache24-2.4.46_2
**Database:**
mysql56-server-5.6.51
mysql56-client-5.6.51
**PHP version:**
php74-7.4.16
**Nextcloud version:** (see Nextcloud admin page)
21.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
from 20.0
**Where did you install Nextcloud from:**
its upgrade page, initially with git
**Signing status:**

<summary>Signing status</summary>
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
**No errors have been found.**

![image](https://user-images.githubusercontent.com/15389379/115967899-b3454880-a524-11eb-9af5-97fd224509e3.png)

**Comment by acsfer** [comment] 2021-04-25 07:53
Duplicate of https://github.com/nextcloud/server/issues/26470

**Closed by acsfer** 2021-04-25 07:53 UTC
Labels: 0. Needs triage, bug
