### ISSUE TITLE
Groupadmin can delete Nextcloud Users

### ISSUE THREAD

**Issue by ltsavar** [nextcloud/server#13288] opened 2018-12-29 13:07 UTC
### Steps to reproduce
1. User authenticated via imap backend is a group admin
2. User deletes an user in Grouplistview 

### Expected behaviour
Should not be possible to delete user authenticated from external user Backends
User should set Quota and maybe password for internal users but not delete not created by them.

### Actual behaviour
User delete an external Backend User.

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page)13

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** zip file

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** imap

**Comment by georgehrke** [comment] 2018-12-29 13:10
It should probabaly be possible to define a group admins rights more granular.

Things like:
- should not be able to edit users of groups like „admin“ ...
- should not delete users from external backends
- ...

**Comment by blackfireburn** [comment] 2018-12-29 14:30
Logically an admin should be able to manage users otherwise what is the point of an administrator.

**Comment by TomTurnschuh** [comment] 2018-12-30 13:44
Duplicate of #3630, #11335 and others.

**Comment by TomTurnschuh** [comment] 2018-12-30 13:46
This seems to be correct by design, even though apparently many users don't understand that this behaviour might be requested.

**Comment by skjnldsv** [comment] 2019-08-15 06:09
Yep, clocing, see 3630

**Closed by skjnldsv** 2019-08-15 06:09 UTC
Labels: 0. Needs triage, bug
