### ISSUE TITLE
Display version in About

### ISSUE THREAD

**Issue by pH142857** [nextcloud/server#26117] opened 2021-03-15 13:33 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
In order to be a power user, I need to know the version of the NC server I'm using. I am not an admin of this server. The only way for me seems to use scan.nextcloud.com which is unconvenient because of 1) the need to use an external tool for such a simple feature 2) I spend time to look for the version where it should be, i.e. in the About section as in every software ever.

**Describe the solution you'd like**
When clicking *User name > About*, I should see the server version rather than only "Nextcloud Hub".

**Describe alternatives you've considered**
The only way to display the server version without using scan.nextcloud.com is to be an administrator. I don't see why.

**Comment by kesselb** [comment] 2021-03-15 16:47
Duplicate of https://github.com/nextcloud/server/issues/21304

**Closed by kesselb** 2021-03-15 16:47 UTC
Labels: 0. Needs triage, enhancement
