### ISSUE TITLE
[Files sharing] Log message: "/appinfo/app.php is deprecated"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#23046] opened 2020-09-25 12:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

I keep getting the following message in my logs:
```
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:30+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
Debug	files_sharing	/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.	
2020-09-25T14:36:29+0200
```

### Server configuration

**Database:**
phpMyAdmin

**PHP version:**
7.3.16

**Nextcloud version:** (see Nextcloud admin page)
20.0.0 RC2

App:
Files sharing
1.12.0

**Comment by kesselb** [comment] 2020-09-26 08:41
Increase the log level to 1 or higher. It's expected for level debug to log deprecated calls.

**Comment by Qinxz1414** [comment] 2020-10-11 14:31
I had the same problem.

**Comment by ChristophWurst** [comment] 2020-10-14 13:56
Debug message -> expected.

**Comment by andreas-p** [comment] 2020-11-04 14:44
Core apps really shouldn't trigger deprecation messages, but get fixed (arguably prior to a release).
Or other way round: if the implementation of files_sharing is considered stable and future proof, NC shouldn't mark it as deprecated.

**Comment by ChristophWurst** [comment] 2020-11-04 14:58
@andreas-p could you check if this green button is blocked for you?

![Bildschirmfoto von 2020-11-04 15-57-22](https://user-images.githubusercontent.com/1374172/98127040-876ed180-1eb6-11eb-8321-6f4ad2175135.png)

/s

**Comment by andreas-p** [comment] 2020-11-04 15:08
@ChristophWurst No it's not. If you're suggesting I should create a PR for this (officially closed!) issue: For my debugging purposes, I commented out the deprecation message in lib/private/legacy/OC_App.php. files_sharing/appinfo/app.php looks different from what I'm familiar with, so I refrained from digging there.

**Comment by working-name** [comment] 2020-11-15 20:23
As a user my pull request would simply be disabling the message altogether. But that might be useful for developers. Idea is.. if your "expected debug message" takes a dump on the UI which is user-facing then your "feature" is as useful as this guy's facial tattoo:
![useful facial tattoo](https://i.pinimg.com/736x/11/8f/e6/118fe6cec3fbfc8ead6eea47f7dc15cc--worlds-worst-tattoos-the-ojays.jpg)

Maybe another solution would be to keep deprecation messages away from the UI. Or give the user a way to use filters?

Otherwise this is how much fun you can have as a user trying to debug why the email app chokes on ssl connections:
![much fun - 37MB gif](https://bugout.regex.cf/dumbestdesignaward2020.gif)

**Comment by ChristophWurst** [comment] 2020-11-16 08:05
> As a user

So as a user you're complaining about a *debug log output*. Seriously, why do you worry about this so much? You enable debug mode for a few secs to gather some info, then you disable it again.

Now tell me: would you rather have a silent log where we, the maintainers, can't help you solve an issue due to the lack of information?

**Comment by working-name** [comment] 2020-11-16 15:04
> you're complaining about a _debug log output_

No, actually I'm not complaining about a debug log output, and I've already conceded that deprecation notices might be useful for developers. What I'm specifically stating is that **deprecation notices** at a rate of 3/second is a **useless thing in the UI**.

> Now tell me: would you rather have a silent log where we, the maintainers, can't help you solve an issue due to the lack of information?

I thought deprecation notices are more of a reminder to later tackle the phased out code. Am I wrong?

**Comment by ChristophWurst** [comment] 2020-11-16 15:17
With the stateless nature of php it's hard to debounce this. Every request will trigger it.

**Comment by working-name** [comment] 2020-11-16 15:18
Okay, understood. Thank you.

**Comment by strugee** [comment] 2020-11-17 04:45
In particular, if you're using the Logging app with the auto-refresh option checked in the web UI, the requests generated by the auto-refresh itself will trigger this very frequently. I ran into this myself recently and if you turn that off and then tail the actual log file on the command line, you'll see it settles down.

**Comment by working-name** [comment] 2020-11-17 05:24
TBH I saw no harm in commenting out that line and that's how I managed to get a usable UI. But it's a good tip, thank you.

**Comment by bcutter** [comment] 2020-11-24 18:30
FYI: Updated from NC 19.0.5.2 to 20.0.2.2 and loglevel was set from 1 to 0 in config.php during update. Machine went totally crazy having Nextcloud.log rotated (cut and moved at 100 MB size) automatically few times. I guess update isn´t reliable yet...

**Comment by christianlupus** [comment] 2020-12-14 13:34
I do not want to continue this hate-thread but I fear during development for the cookbook app this issue caused a regression as we were not able to test accordingly. Currently, we are recovering but the main issue can be brought down to this issue.
In fact, I was not able to see the live error logs during testing/debugging the app. So I missed the warning of PHP that a certain set of functions/fields are undefined (typos) and other similar effects. The log was just cluttered with these deprecation warnings (which are good in general). But as these are generated on each invocation (also the update of the logs) this ends in an infinite recursion.

For now, I am able to see some useful information by disabling the `files_sharing` app but this is no permanent solution, especially as we are planning to allow for the sharing of recipes in the app. At most that moment in time, we need to allow the sharing again, which will clutter the logs again.

I tried to create a patch in [this PR](https://github.com/nextcloud/server/pull/24689) but I am not able to get things right, I am missing the knowledge of the internal structure of the NC core.

I am asking @ChristophWurst to reconsider closing this issue as I can only second the general statement/issue here: *A component uses a deprecated method and that should be replaced by a newer structure.* The fact that it is a core component just makes it hard for other contributors to contribute a "quick fix".

If this is on the agenda for a near-future update, perfect, just give a short statement and I am going to keep waiting.

**Comment by Valdnet** [comment] 2020-12-14 14:12
@ChristophWurst and @kesselb I am opening an issue to discuss the problem again.

**Comment by dartcafe** [comment] 2020-12-19 08:17
It would be nice to get a solution here fast. I just wanted to track some debug messages while continuing development and this situation still exist. 

The problem is not, that a lot of debugging messages are generated because of this deprecation message, the problem is that debugging is impossible ATM. There are something about 45 deprecations messages **per second**. See the log file snippet in #23351.

**Comment by ChristophWurst** [comment] 2020-12-21 13:12
So what would you suggest as a solution?

**Comment by dartcafe** [comment] 2020-12-21 22:50
It seems, that the logger itself is responisble for the endless production of deprication warnings in the logfile. If this could be avoided the problem would be smaller and acceptable. 

As I am not familiar with the core development, I have no real proposal for a solution.

**Comment by dartcafe** [comment] 2020-12-21 22:53
Correction: seems that the files_sharing and contacts are my problem here.

**Comment by strugee** [comment] 2020-12-22 00:27
@dartcafe I mentioned this up-thread; see https://github.com/nextcloud/server/issues/23046#issuecomment-728682934. You can get a vaguely reasonable log output with `tail -f data/nextcloud.log | jq '.time + " " + .reqId + " " + if (.message | type) == "object" then .message.Exception else .message end'` (though you will of course need to install `jq` on your system first).

**Comment by bjo81** [comment] 2021-01-22 08:35
We have loglevel 1 and the log is spammed with deprecation warnings, 25GB log in the last days.

**Comment by geep33** [comment] 2021-01-22 09:18
Wth are you talking about

**Comment by bjo81** [comment] 2021-01-22 09:27
> Wth are you talking about

Some entries above @ChristophWurst says users should not complain about debug output when setting loglevel to `debug`. I changed loglevel 0 to 1 expecting `info` messages, but no deprecation warnings. And the logfile grew from 2GB to 25 GB in 4 days, full of deprecation warnings.

**Comment by ChristophWurst** [comment] 2021-01-22 09:31
Great now that we have all people combined that complained about the problem, here's the PR that fixes it: https://github.com/nextcloud/server/pull/25267

you're welcome

**Comment by aidanharris** [comment] 2021-01-22 15:23
Why aren't repeated duplicate log messages rate limited (the approach the Linux kernel takes is good where if a message is repeated a lot of times in `dmesg` it'll just stop showing it and print a message saying the previous message was repeated X times)?

![Screenshot_2021-01-22 Settings - Nextcloud](https://user-images.githubusercontent.com/3309784/105509550-85eac380-5cc5-11eb-8666-77f5d66a4039.png)

**Comment by kesselb** [comment] 2021-01-22 16:18
@aidanharris read https://github.com/nextcloud/server/issues/23046#issuecomment-728119588 and the response.

**Comment by Schmidtjanroman** [comment] 2021-01-23 15:18
Same problem here with alot of reports and logs:

`[previewgenerator] Debug: /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.`

also
```
[no app in context] Info: Deprecated event type for OCA\Files::loadAdditionalScripts: Symfony\Component\EventDispatcher\GenericEvent is used
GET /index.php/apps/files/
```

like every few seconds those appear

**Comment by ChristophWurst** [comment] 2021-02-12 17:33
One step closer to a more reasonable debug log: https://github.com/nextcloud/server/pull/25497 :v:

**Comment by Valdnet** [comment] 2021-02-13 13:26
@ChristophWurst Cool 👍. I hope it will be much clearer now and will not take up as much space.

**Comment by dartcafe** [comment] 2021-07-06 20:55
The logfile flooding still exists in NC22. 

Wouldn't it be a good idea to remove the deprecation at least for the core apps? 

I list the following apps in my NC22 installation: 
* files_sharing
* contacts
* suspicious_login

**Comment by ChristophWurst** [comment] 2021-07-07 05:43
> files_sharing

Be my guest and help finish what I was unable to finish https://github.com/nextcloud/server/pull/25267 :wink: 

> contacts

https://github.com/nextcloud/contacts/issues/1831

> suspicious_login

https://github.com/nextcloud/suspicious_login/issues/499

**Comment by dartcafe** [comment] 2021-07-07 05:54
> > files_sharing
> 
> Be my guest and help finish what I was unable to finish #25267 😉

I would, if I would have the time and the knowledge. Polls alone takes more time, as I normaly could afford.

**Comment by ChristophWurst** [comment] 2021-07-07 05:58
No worries :v:

We'll have to wait for someone more knowledgeable then because the sharing stuff was also out of my area of expertise and thus got stuck.

**Comment by nickvergessen** [comment] 2022-04-25 14:08
File sharing is migrated, so closing this.
Other apps can be added here: https://github.com/nextcloud/server/issues/32132

**Closed by nickvergessen** 2022-04-25 14:08 UTC
Labels: 1. to develop, technical debt
