### ISSUE TITLE
Update to NC 22 failed

### ISSUE THREAD

**Issue by bolet** [nextcloud/server#28315] opened 2021-08-04 23:21 UTC
To reproduce
1. start with an instance running a NC21 image in docker
2. stop the instance and replace with a NC22 image
3. restart instance
4. enter the app container as user 82 and type `./occ upgrade`

Expected result: upgrade success

Actual result
```
/var/www/html $ ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Exception: Database error when running migration latest for app core
Update failed
Maintenance mode is kept active
Resetting log level
```

Maybe unrelated, in mariadb container I get:
```
...
nextcloud_db.1.s79vbngjn1qe@ursule    | 2021-08-04 22:40:57 0 [ERROR] Incorrect definition of table mysql.event: expected column 'definer' at position 3 to have type varchar(, found type char(141).
nextcloud_db.1.s79vbngjn1qe@ursule    | 2021-08-04 22:40:57 0 [ERROR] mysqld: Event Scheduler: An error occurred when initializing system tables. Disabling the Event Scheduler.
...
```

**Comment by schneidersteve** [comment] 2021-08-05 07:39
I have the same problem when i try to update from NC 20 to 21 with the docker image and MariaDB.

**Comment by dr-br** [comment] 2021-08-05 07:48
Maybe helpful:
When I upgraded to 22 I had to pin the MariaDB version to 10.5.
```
catdocker-compose.yml 
version: '3'

services:
  db:
    image: mariadb:10.5
    …
```

**Comment by szaimen** [comment] 2021-08-06 10:01
Seems to be a duplicate of https://github.com/nextcloud/server/issues/25436

**Closed by szaimen** 2021-08-06 10:01 UTC
Labels: bug, 0. Needs triage
