### ISSUE TITLE
[FEATURE REQUEST]: Add support for Discord embeds

### ISSUE THREAD

**Issue by JustRed23** [nextcloud/server#32979] opened 2022-06-22 13:16 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I would like to share pictures with my friends on Discord but when i upload the link people still have to click on the link to get the picture.

**Describe the solution you'd like**
I would love it if Nextcloud had support for Discord embeds

**Additional context**
The old way of sharing pictures on Discord:
![image](https://user-images.githubusercontent.com/21986809/175037750-b9f19d52-b8ca-4b3b-b4fd-7a3e69fb7285.png)

A newer better way of sharing would look something like:
![image](https://user-images.githubusercontent.com/21986809/175038063-cb5adbcb-8b0f-42c2-9480-1c807461f8e3.png)

**Comment by meonkeys** [comment] 2022-06-25 16:04
Sounds like https://github.com/nextcloud/spreed/issues/3156

**Comment by JustRed23** [comment] 2022-06-25 18:18
Seems to be yea, did not see that one

**Comment by szaimen** [comment] 2022-06-25 18:23
Duplicate of https://github.com/nextcloud/spreed/issues/3156

**Closed by szaimen** 2022-06-25 18:23 UTC
Labels: enhancement, 0. Needs triage
