### ISSUE TITLE
improve the timeout value for CURL

### ISSUE THREAD

**Issue by TP75** [nextcloud/server#17808] opened 2019-11-04 21:16 UTC
Quick and dirty issue report:

Please consider a value like '120' (as in the b.m. example) or a more reasonable value **to avoid download drop-outs** as reported by several users in recent times.

see https://github.com/nextcloud/server/commit/ca2623e6ad4f7d838a61c71ba828b44b3b7331ab#commitcomment-35800035

Have a look at the NC forum and certainly:

* https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603/11

> I’ve solved the Problem by manually Setting the Value for
" `RequestOptions::TIMEOUT` "
to `120` or a higher value ...

* https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603

> The problem is, i’cant install certain apps out of the appstore. Some are downloadable, e.g. the W2G app, but others are failing with the error: “_cURL error 28: Operation timed out after 30000 milliseconds with 1113682 out of 3112147 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)_”, for example the deck app.

Please note I took the liberty to just copy & paste from 'padwa' - Dwayne Parker

Hope this helps.

**Comment by TP75** [comment] 2019-11-11 17:42
have a look at:

[Create backup failed when updating from 16.0.3 to 16.0.5 via Updater - no 8](https://help.nextcloud.com/t/create-backup-failed-when-updating-from-16-0-3-to-16-0-5-via-updater/61728/8?u=tp75)

**Comment by kesselb** [comment] 2019-11-11 17:46
> have a look at:
> 
> [Create backup failed when updating from 16.0.3 to 16.0.5 via Updater - no 8](https://help.nextcloud.com/t/create-backup-failed-when-updating-from-16-0-3-to-16-0-5-via-updater/61728/8?u=tp75)

Not related to the curl timeout.

**Comment by TP75** [comment] 2019-11-11 17:56
> Not related to the curl timeout.

You are correct. My fault.

 `max_execution_time` was addressed somewhere else and I made a false connection in my mind, wishful thinking apparently

**Comment by kesselb** [comment] 2020-03-03 10:49
Closing as duplicate of https://github.com/nextcloud/server/issues/18103. Also fixed for CLI requests with #19430.

**Closed by kesselb** 2020-03-03 10:49 UTC
Labels: 0. Needs triage, 17-feedback, bug
