### ISSUE TITLE
Edge with scrollbar in Header

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#10696] opened 2018-08-15 10:35 UTC
At the right side of the header there is some edge space for the scrollbar which is not needed there.
Tested with Safari on Nextcloud 14 beta ...

![aug-15-2018 12-32-41](https://user-images.githubusercontent.com/19711361/44144363-75f0a1e0-a087-11e8-8aaa-95dd27c61cc0.gif)

@nextcloud/designers @skjnldsv

**Comment by skjnldsv** [comment] 2018-08-15 10:38
This is not a bug, this is because the whole page is being scrolled.
This is like that everywhere. Look at twitter for example :)

**Comment by MariusBluem** [comment] 2018-08-15 10:47
**Facebook:**
![aug-15-2018 12-45-44](https://user-images.githubusercontent.com/19711361/44144783-26e7e93a-a089-11e8-8994-716f8246538b.gif)

**Office 365:**
![aug-15-2018 12-46-53](https://user-images.githubusercontent.com/19711361/44144828-55ba11ac-a089-11e8-8b22-0eb0411996b0.gif)

**Comment by skjnldsv** [comment] 2018-08-15 10:54
Office is a bad example since it uses a scrollbar within content.
Facebook on safari on 11.1.2

What os are you on?

**Comment by MariusBluem** [comment] 2018-08-15 12:37
macOS Mojave

**Comment by skjnldsv** [comment] 2018-08-15 12:58
This is a browser's issue.
We cannot tweak how the sidebar looks unless we use a custom javascript plugin. :/

Can you screenshot twitter then @MariusBluem please ? :)

**Comment by MariusBluem** [comment] 2018-08-18 17:47
> Can you screenshot twitter then @MariusBluem please ? :)

![aug-18-2018 19-46-40](https://user-images.githubusercontent.com/19711361/44301907-94c43380-a31f-11e8-9a8f-464ef7a09901.gif)

**Comment by skjnldsv** [comment] 2018-08-19 08:26
Well, let's leave this opened to check later if safari have some specific tweaks or custom css, but the current behaviour is OK. This is just an enhancement for safari in your os. The older safari behave the same as Firefox or chrome on win/lin/macos11

**Comment by MorrisJobke** [comment] 2019-02-25 17:02
What is the status of this?

**Comment by juliushaertl** [comment] 2019-02-26 19:11
I just tested with Safari 12 on browserstack and it behaves the same as with the other browsers. There is https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property as a draft which seems to have involved out of webkit browsers implementing `overflow: overlay;` but neither one of those seem to be supported by current Safari. Let's close this.

**Closed** 2019-02-26 19:11 UTC
Labels: 1. to develop, design, papercut
