### ISSUE TITLE
External Storage  ...SMB FTP

### ISSUE THREAD

**Issue by robcop2000** [nextcloud/server#37298] opened 2023-03-19 20:54 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm trying to work on a Storage in a Windows Server 2019 via Nextcloud.
Enabled external storage application configurate SMB storage but I get the red dot an doesn't connect.
I have tryed to mount a FTP Server, it connects but no file is displayed.

### Steps to reproduce

1.Enabled external share
2.Configurated in settings
3.No connection and red dot dislayed.

### Expected behavior

I expect to see the file on server. It worked on version 22 of nexcloudpi

### Installation method

Community NextcloudPi appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Activity 2.17.0
Auditing / Logging 1.15.0
Automated PDF conversion 1.10.1
Brute-force settings 2.5.0
CADViewer
8.52.4
Calendar
4.2.4
In evidenza
Circles
25.0.0
In evidenza
Client Push
0.6.0
Collaborative tags
1.15.0
In evidenza
Comments
1.15.0
In evidenza
Contacts
5.2.0
In evidenza
Contacts Interaction
1.6.0
In evidenza
Dashboard
7.5.0
In evidenza
Deck
1.8.3
In evidenza
Deleted files
1.15.0
In evidenza
Electronic Signatures
2.0.3
External storage support
1.17.0
In evidenza
Federation
1.15.0
In evidenza
File sharing
1.17.0
In evidenza
First run wizard
2.14.0
In evidenza
Full text search
25.0.0
Group folders
13.1.1
In evidenza
LDAP user and group backend
1.15.0
In evidenza
Log Reader
2.10.0
In evidenza
Maps
0.2.4
In evidenza
Mind Map
0.0.27
Monitoring
1.15.0
In evidenza
News
21.0.0
In evidenza
Nextcloud announcements
1.14.0
In evidenza
NextCloudPi
0.0.1
Notes
4.6.0
In evidenza
Notifications
2.13.1
In evidenza
Password policy
1.15.0
In evidenza
PDF viewer
2.6.0
In evidenza
Photo Sphere Viewer
1.25.2
Photos
2.0.1
In evidenza
Preview Generator
99.99.99
Privacy
1.9.0
In evidenza
Recommendations
1.4.0
In evidenza
Related Resources
1.0.3
In evidenza
Right click
1.4.0
In evidenza
Share by mail
1.15.0
In evidenza
Support
1.8.0
In evidenza
Talked
0.5.0
```

### Additional info

I have published support help to comunity at this link
https://help.nextcloud.com/t/best-share-windows-serve/158073/2
But noo help

**Comment by szaimen** [comment] 2023-03-19 23:03
Hi, which nc version?

**Comment by robcop2000** [comment] 2023-03-20 08:15
The last one ... 25.0.3.
I would have wanted to install  the first versione that worked and ipdate it but is not more available the the image.
Was about 22

**Comment by robcop2000** [comment] 2023-03-21 20:21
I found this error s
Any solution?

[no app in context] Avviso: Icewind\SMB\Exception\Exception: Unknown error (NT_STATUS_OBJECT_NAME_INVALID) for / at <<closure>>

 0. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Exception/Exception.php line 49
    Icewind\SMB\Exception\Exception::unknown()
 1. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Wrapped/Parser.php line 92
    Icewind\SMB\Exception\Exception::fromMap()
 2. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php line 479
    Icewind\SMB\Wrapped\Parser->checkForError()
 3. /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php line 215
    Icewind\SMB\Wrapped\Share->parseOutput()
 4. /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 191
    Icewind\SMB\Wrapped\Share->stat()
 5. /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 348
    OCA\Files_External\Lib\Storage\SMB->getFileInfo()
 6. /var/www/nextcloud/lib/private/Files/Storage/Common.php line 462
    OCA\Files_External\Lib\Storage\SMB->stat()
 7. /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 729
    OC\Files\Storage\Common->test()
 8. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 474
    OCA\Files_External\Lib\Storage\SMB->test()
 9. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 474
    OC\Files\Storage\Wrapper\Wrapper->test()
10. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 69
    OC\Files\Storage\Wrapper\Wrapper->test()
11. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 83
    OC\Files\Storage\Wrapper\Availability->updateAvailability("*** sensitive parameters replaced ***")
12. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 92
    OC\Files\Storage\Wrapper\Availability->isAvailable()
13. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 445
    OC\Files\Storage\Wrapper\Availability->checkAvailability()
14. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 599
    OC\Files\Storage\Wrapper\Availability->getMetaData()
15. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 116
    OC\Files\Storage\Wrapper\Wrapper->getMetaData()
16. /var/www/nextcloud/lib/private/Files/Cache/Scanner.php line 154
    OC\Files\Cache\Scanner->getData()
17. /var/www/nextcloud/lib/private/Files/View.php line 1502
    OC\Files\Cache\Scanner->scanFile()
18. /var/www/nextcloud/lib/private/Files/Node/Folder.php line 101
    OC\Files\View->getDirectoryContent()
19. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 260
    OC\Files\Node\Folder->getDirectoryListing()
20. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 200
    OCA\DAV\Connector\Sabre\Directory->getChildren()
21. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 900
    Sabre\DAV\Tree->getChildren()
22. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 982
    Sabre\DAV\Server->generatePathNodes()
23. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
24. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
25. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
26. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
27. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
28. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
29. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
30. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
31. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
32. /var/www/nextcloud/remote.php line 171
    require_once("/var/www/nextcl ... p")

**Comment by joshtrichards** [comment] 2023-06-16 00:13
Duplicate of #30751

**Comment by joshtrichards** [comment] 2023-08-30 13:26
Duplicate of #30751 

Consolidating tracking there. Feel free to subscribe to that issue.

**Closed by joshtrichards** 2023-08-30 13:26 UTC
Labels: bug, feature: external storage, 0. Needs triage, 25-feedback
