### ISSUE TITLE
maintenance mode reverts to default theme

### ISSUE THREAD

**Issue by tessus** [nextcloud/server#12644] opened 2018-11-24 04:04 UTC
I tried to find the repository for the theming app (admin interface), but maybe it was merged into the server code base.

Every time one sets the maintenance mode, the original default theme is used.

While I do understand why this might be, it kind of defies corporate identity and doesn't look very nice.

I did not fill out the template, because none of the information is relevant to this issue.

**Comment by danielkesselberg** [comment] 2018-11-24 20:42
Yeah. Makes sense somehow because `theming` is an app.

**Comment by tessus** [comment] 2018-11-24 20:52
Still, the fact that the default background and slogan (`Nextcloud - a safe home for all your data`) is used, looks a bit unprofessional.

I undertand that apps should not be active during an upgrade, but I'm sure there's some sort of workaround. e.g.: create a tmp dir with a static themed maintenance page and redirect to or show that.

In the meantime I guess I will have to create my own maintenance page and redirect to that during an upgrade.

**Comment by MorrisJobke** [comment] 2018-11-29 22:36
Duplicate of #12727 - there is also a way to work around this.

**Closed by MorrisJobke** 2018-11-29 22:36 UTC
Labels: enhancement, feature: theming

**Comment by tessus** [comment] 2018-12-01 11:20
@MorrisJobke this is not a duplicate. #12727 is about the problem that the theme is removed and stays removed after the upgraded has been concluded.

This issue is about the fact that when one activates the maintenance mode the theme is removed (thus the maintenance information page is always the default theme). After turning off maintenance mode, everything is ok again.

**Comment by MorrisJobke** [comment] 2018-12-03 09:04
> This issue is about the fact that when one activates the maintenance mode the theme is removed (thus the maintenance information page is always the default theme). After turning off maintenance mode, everything is ok again.

The maintenance mode does not remove the theme. The maintenance mode is simply not themed. I guess I missed something here - this is a duplicate of #5789.
