### ISSUE TITLE
File grid view icon too large

### ISSUE THREAD

**Issue by potato1992** [nextcloud/server#33179] opened 2022-07-08 20:40 UTC
Currently, the default icon size in grid view is too big, as it is refereed in https://github.com/nextcloud/server/issues/11902, and to change the icon size in the grid view, I can only modify the `$grid-size: 160px;` in apps/files/css/files.scss:
```
#filestable.view-grid:not(.hidden) {
          $grid-size: 160px;
          $grid-pad: 14px;
```
It's still not perfect solution, as it will be changed back as soon as I upgrade.

Hope to give an option to change the icon size as 'Large icons' 'Medium icons' 'Small icons' like the windows explorer does, another php nas system [kodexplorer](https://github.com/kalcaddle/KodExplorer) also supports this function.

Also, please move the menu botton from the bottom to the top, to avoid occupying the limited space to show file name, as demonstrated in this [pic](https://drive.google.com/file/d/1qcIHs-fO9a66QvyZnB6I1RU6IOWRzjGY/view?usp=sharing).

**Comment by joshtrichards** [comment] 2023-09-19 15:04
Duplicate of #11902

@potato1992 Feel free to contribute your ideas to the discussion in #11902 if desired. Maybe we can move that forward rather than soon with some renewed energy in the thread.

**Closed by joshtrichards** 2023-09-19 15:04 UTC
Labels: enhancement, design, 0. Needs triage, feature: files
