### ISSUE TITLE
CalDav Server: Make calendars' event/task functionality configurable

### ISSUE THREAD

**Issue by daCaPo** [nextcloud/server#8625] opened 2018-03-02 11:25 UTC
### Steps to reproduce
1. Create a calendar
2. Sync with  OSX/macOS/iOS calendar

### Expected behaviour
Calendars (especially those intended for sharing) don't neccessarily require a corrsponding TODO/task list. And there are use cases where users want just a task list, without a corresponding calendar being visible anywhere.

In the NC "calendars" table, a calendar's functionality is controlled via the values "VEVENT" and/or "VTODO". This setting should be made accessible.

### Actual behaviour
For every calendar synced with iOS/macOS calendar app, a corresponding task list is made available.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
13.0.0

**Comment by blizzz** [comment] 2018-03-14 10:08
@georgehrke

**Comment by georgehrke** [comment] 2018-03-14 10:37
cc @nextcloud/designers Usability question: Should a new calendar be both a calendar and a task list or simply a calendar?

https://github.com/nextcloud/calendar/blob/master/js/app/service/calendarService.js#L289
https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalDavBackend.php#L665

**Comment by pixelipo** [comment] 2018-03-14 10:48
I don't know how to answer the question, but let's try with some use cases and a lot of questions:

- let's say you want to share a task list with a team member: if the attached calendar is shared, the list is also automatically shared, if I'm not mistaken
- apart from that, there is no way to share a Task list, right? That means New calendar must be a task list as well
- at this moment, there is no real integration between Tasks and Calendar; in the future, if you set a date on a task, it should appear in the Calendar, should it not? If so, each task list must have a related Calendar, right? Same goes for future integration with Deck app

**Comment by georgehrke** [comment] 2018-03-14 10:56
> let's say you want to share a task list with a team member: if the attached calendar is shared, the list is also automatically shared, if I'm not mistaken

Yes, if you share a calendar in the calendar app, it will also share all tasks in that calendar

> apart from that, there is no way to share a Task list, right? That means New calendar must be a task list as well

Ah, yes. I just double checked and the task app doesnt offer sharing as of yet. The only way to share is  via the calendar app. cc @raimund-schluessler 

> at this moment, there is no real integration between Tasks and Calendar; in the future, if you set a date on a task, it should appear in the Calendar, should it not? If so, each task list must have a related Calendar, right?

Both are storing their data on the CalDAV server. And yes, that's planned :)
https://github.com/nextcloud/calendar/issues/28

**Comment by daCaPo** [comment] 2018-03-14 11:04
Apple's designers decided to create calendars and reminders seperately via their respective apps. As a Mac user, I would prefer to see NC behaving accordingly.

Many users will come educated accordingly, especially as Apple decided to remove their "Darvin Calendar and Contacts Server" from macOS server, leaving users looking for alternatives.

**Comment by daCaPo** [comment] 2018-03-14 11:23
Apple's designers decided to create calendars and reminders seperately via their respective apps. As a Mac user, I would prefer to see NC behaving accordingly.

Many users might come educated accordingly, especially as Apple decided to remove their "Darvin Calendar and Contacts Server" from macOS server, leaving admins looking for alternatives.

**Comment by pixelipo** [comment] 2018-03-14 11:29
The way I see it, until Tasks is able to share we must keep current status.

As soon as that obstacle is solved, we could migrate to separated calendars for each. Right now, such a weird thing can happen in the Tasks app (one of these is imported and the other one a web calendar):
![image](https://user-images.githubusercontent.com/4129927/37399767-00aa2726-2783-11e8-9ba2-bdbba3b4c202.png)

 However, I would still like us to retain the possibility to have a single collection fo both.

Calendar is used for time-dependant tasks that must be done at a certain determined time. Tasks is for more flexible tasks that should be done some time in the future. But as soon as you decide to commit to a certain task - you add a time/date to it - it becomes a time-dependant task.
You should be able to go the other way, too - if you fail to perform a time-dependant task at a predetermined time, you can remove date from it. This means task is not visible in the Calendar, but is still in Tasks, without time.

**Comment by daCaPo** [comment] 2018-03-14 11:39
Right now, the difference are just the values in the "component" column of the "calendars" table. Wouldn't it at least be a feasible quick-fix to let the user switch the task list functionality on and off via an option button in the calendar's configuration dialogue?

**Comment by georgehrke** [comment] 2018-03-14 11:44
> Wouldn't it at least be a feasible quick-fix to let the user switch the task list functionality on and off via an option button in the calendar's configuration dialogue?

The caldav standard doesnt allow changing that property after the calendar was created. So changing it will lead to unexpected behavior (possibly even) breaking clients.

**Comment by jancborchardt** [comment] 2018-03-14 11:45
One thing we definitely need to catch is the problem that due to the current connection, people removing a calendar don't necessarily know that it means removing the tasks too (or vice versa). So we need to:
- Have a notice about that when removing (little work but also still dangerous)
- Check when removing the calendar if there are tasks – if so block removal, or make sure it's double-checked
- Have a "trashbin" equivalent as has been discussed (lots of work though)

**Comment by terenc3** [comment] 2018-03-21 08:49
Just to seperate the issue here. What @jancborchardt mentioned is right, but what @daCaPo wants is a configuration to enable/disable tasks. If the standard doesn't allow to change this after the creation, the easiest solution whould be asking the user on the creation of the calendar if he also wants to enable the tasks.

**Comment by skjnldsv** [comment] 2019-06-12 17:36
Still on @georgehrke ?

**Comment by georgehrke** [comment] 2019-06-12 17:41
Back then we only kept this behavior, because the Task app could not share tasks lists yet. So you needed to share the corresponding calendar to share the tasks.

@raimund-schluessler Does the task app support sharing tasks lists already? 

In that case we can close and the calendar should only create calendar with supported component type VEVENT.

**Comment by raimund-schluessler** [comment] 2019-06-12 18:15
@georgehrke The next version v0.11.0 of the Tasks app will support sharing lists, PR was https://github.com/nextcloud/tasks/pull/410.

As long as the next release of Calendar comes after the next release of Tasks (ETA approx. 3 weeks), we can go for `VEVENT` only 😉

**Comment by georgehrke** [comment] 2019-06-12 18:32
Closing in favour of https://github.com/nextcloud/calendar/issues/1316 then

**Closed by georgehrke** 2019-06-12 18:32 UTC
Labels: enhancement, feature: dav, needs info

**Comment by Thaodan** [comment] 2022-10-18 01:39
> Closing in favour of [nextcloud/calendar#1316](https://github.com/nextcloud/calendar/issues/1316) then

The PR doesn't address the underlying issue just but only works around which leaves users expecting to use a calendar for todos and event stranded. Should this bug be reopened or be recreated?
