### ISSUE TITLE
Misleading message under users account tab

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#27047] opened 2021-05-20 19:49 UTC
I think if there users this message should not state no users in here. 
![image](https://user-images.githubusercontent.com/59488153/119039774-3cac3700-b97a-11eb-8e65-c5a1b2451e69.png)

**Comment by PanCakeConnaisseur** [comment] 2021-06-09 00:04
What is the source of the users? An external user backend? if yes, what kind of?

**Comment by andyxheli** [comment] 2021-06-09 00:44
> What is the source of the users? An external user backend? If yes, what kind of?

Internal database MariaDB

**Comment by szaimen** [comment] 2021-07-27 12:52
Duplicate of https://github.com/nextcloud/server/issues/25133

**Closed by szaimen** 2021-07-27 12:52 UTC
Labels: 0. Needs triage, bug
