### ISSUE TITLE
Multiple selected files deletion on SMB-share failing

### ISSUE THREAD

**Issue by lkakas** [nextcloud/server#26850] opened 2021-05-01 11:26 UTC
### Steps to reproduce
1. Using SMB share as external storage 
2. Browse to the SMB folder.
3. try delete multiple selected files in the subfolder of SMB share.

### Expected behaviour
Deleting multiple selected files without issues. 

### Actual behaviour
Deletion of multiple selected files failing on the SMB share. Error message shown:
Error deleting file "filename shown here".

### Server configuration

**Operating system:**
CentOS Linux release 8.2.2004 (Core)

(I was able to reproduce the issue with the Ubuntu appliance version as well: https://download.nextcloud.com/vm/Official-Nextcloud-VM.zip)

**Web server:**
httpd-2.4.37-21.module_el8.2.0+494+1df74eae.x86_64
php-fpm-7.4.12-1.el8.remi.x86_64

**Database:**
mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.4.12 (cli) (built: Oct 27 2020 15:01:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies

**PHP Modules:**
<details>
<summary>Loaded PHP modules</summary>

```
# php -m
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
libsmbclient
libxml
mbstring
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
smbclient
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
</details>

**Nextcloud version:** 
Nextcloud 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.1

**Where did you install Nextcloud from:**
Official: https://download.nextcloud.com/server/releases/nextcloud-21.0.1.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
# sudo -u apache php occ app:list
Enabled:
  - activity: 2.14.3
  - bruteforcesettings: 2.1.0
  - cloud_federation_api: 1.4.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - keeweb: 0.6.5
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - ransomware_protection: 1.10.0
  - richdocuments: 4.0.4
  - richdocumentscode: 6.4.705
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - accessibility
  - admin_audit
  - comments
  - dashboard
  - encryption
  - nextcloud_announcements
  - recommendations
  - support
  - survey_client
  - user_ldap
  - user_status
  - weather_status

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
# sudo -u apache php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.X.XXX"
        ],
        "allow_local_remote_servers": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "http:\/\/192.168.X.XXX",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "twofactor_yubikey",
            "twofactor_webauthn",
            "twofactor_rcdevsopenotp",
            "keeweb"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "users"
        ],
        "twofactor_enforced_excluded_groups": [
            "admin"
        ],
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "config_is_read_only": false,
        "default_phone_region": "HU",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** yes, SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

**Operating system:** 
Microsoft Windows [Version 10.0.18363.836]

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"YI0yVQiJR6Am95ogIo774gAAAEI","level":3,"time":"2021-05-01T10:49:58+00:00","remoteAddr":"192.168.1.5","user":"admin","app":"no app in context","method":"DELETE","url":"/remote.php/dav/files/admin/PhoneBackup/Test/Screenshot_20210325-182804.jpg","message":{"Exception":"Icewind\\SMB\\Exception\\ConnectionAbortedException","Message":"/PhoneBackup/Test/Screenshot_20210325-182804.jpg","Code":103,"Trace":[{"file":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php","line":67,"function":"fromMap","class":"Icewind\\SMB\\Exception\\Exception","type":"::"},{"file":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php","line":84,"function":"handleError","class":"Icewind\\SMB\\Native\\NativeState","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php","line":338,"function":"testResult","class":"Icewind\\SMB\\Native\\NativeState","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php","line":305,"function":"getxattr","class":"Icewind\\SMB\\Native\\NativeState","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php","line":43,"function":"getAttribute","class":"Icewind\\SMB\\Native\\NativeShare","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php","line":69,"function":"stat","class":"Icewind\\SMB\\Native\\NativeFileInfo","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php","line":114,"function":"getSize","class":"Icewind\\SMB\\Native\\NativeFileInfo","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php","line":193,"function":"stat","class":"Icewind\\SMB\\Native\\NativeShare","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php","line":636,"function":"getFileInfo","class":"OCA\\Files_External\\Lib\\Storage\\SMB","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Common.php","line":114,"function":"filetype","class":"OCA\\Files_External\\Lib\\Storage\\SMB","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":115,"function":"is_dir","class":"OC\\Files\\Storage\\Common","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":115,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php","line":132,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":115,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":115,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/View.php","line":1168,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/View.php","line":380,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/View.php","line":722,"function":"is_dir","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":466,"function":"unlink","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":167,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Exception/Exception.php","Line":44,"CustomMessage":"Error while getting file info"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"21.0.1.1","id":"608d38bc7182a"}
{"reqId":"YI0yVQiJR6Am95ogIo774gAAAEI","level":4,"time":"2021-05-01T10:49:58+00:00","remoteAddr":"192.168.1.5","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/admin/PhoneBackup/Test/Screenshot_20210325-182804.jpg","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Failed to unlink: Storage unauthorized. /PhoneBackup/Test/Screenshot_20210325-182804.jpg","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":167,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":471,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"21.0.1.1","id":"608d38bc71766"}
{"reqId":"YI0yVgiJR6Am95ogIo774wAAAEY","level":4,"time":"2021-05-01T10:49:58+00:00","remoteAddr":"192.168.1.5","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/admin/PhoneBackup/Test/Screenshot_20210402-004608.jpg","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Storage with mount id 5 is not available","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":78,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":601,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":199,"function":"getCurrentUserPrivilegeSet","class":"Sabre\\DAVACL\\Plugin","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php","line":53,"function":"checkPrivileges","class":"Sabre\\DAVACL\\Plugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":913,"function":"checkPrivileges","class":"OCA\\DAV\\Connector\\Sabre\\DavAclPlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeUnbind","class":"Sabre\\DAVACL\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":278,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":167,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":225,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"21.0.1.1","id":"608d38bc71715"}
{"reqId":"YI0yVqPTJwfXfUAhU4tnNwAAAMs","level":4,"time":"2021-05-01T10:49:58+00:00","remoteAddr":"192.168.1.5","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/admin/PhoneBackup/Test/Screenshot_20210411-130107.jpg","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Storage with mount id 5 is not available","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":78,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":601,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":199,"function":"getCurrentUserPrivilegeSet","class":"Sabre\\DAVACL\\Plugin","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php","line":53,"function":"checkPrivileges","class":"Sabre\\DAVACL\\Plugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":913,"function":"checkPrivileges","class":"OCA\\DAV\\Connector\\Sabre\\DavAclPlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeUnbind","class":"Sabre\\DAVACL\\Plugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":278,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":167,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":225,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"21.0.1.1","id":"608d38bc71689"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

![kép](https://user-images.githubusercontent.com/81051249/116780974-29dfca00-aa80-11eb-9a64-9384e179eb10.png)

**Comment by szaimen** [comment] 2021-05-01 14:55
Could be due to #26457

**Comment by lkakas** [comment] 2021-05-01 15:00
> 
> 
> Could be due to #26457

I already applied the referenced fix (https://blog.nuvotex.de/nextcloud-smb-stringbuffer) but still the same.

**Comment by szaimen** [comment] 2021-05-01 15:23
Are the ACL on the SMB-server set correctly?

**Comment by lkakas** [comment] 2021-05-01 15:26
> 
> 
> Are the ACL on the SMB-server set correctly?

I can upload files and delete if I select one. But if I select multiple then getting errors randomly. And from the selection random number is deleted only. The rest are kept and getting error message. Then retrying one by one it works...very strange.

No specific ACLs on SMB server. Just owned by the same user.

**Comment by szaimen** [comment] 2021-07-02 16:38
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by lkakas** [comment] 2021-07-02 17:16
> 
> 
> Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

Yes it is. Just updated to 21.0.3.

![kép](https://user-images.githubusercontent.com/81051249/124308675-eaaa2400-db69-11eb-89c1-015a0809c3de.png)

**Comment by szaimen** [comment] 2021-07-06 09:00
cc @icewind1991

**Comment by GuyPaddock** [comment] 2022-02-25 23:34
Could also be #17980 which was NOT fixed upstream.

**Comment by szaimen** [comment] 2023-01-23 11:06
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:42 UTC
Labels: bug, needs info, feature: external storage, 0. Needs triage
