### ISSUE TITLE
Still no Fahrenheit Setting

### ISSUE THREAD

**Issue by tgwaste** [nextcloud/server#40336] opened 2023-09-07 18:37 UTC
I don't understand how after all this time there is still no obvious setting to switch the weather to Fahrenheit.
Am I just missing it?

**Comment by joshtrichards** [comment] 2023-09-07 20:38
Duplicate of #23486

There are a couple of workarounds - e.g.

https://github.com/nextcloud/server/issues/23486#issuecomment-869143025

**Closed by joshtrichards** 2023-09-07 20:38 UTC
Labels: bug, 0. Needs triage, feature: dashboard
