### ISSUE TITLE
Office File cannot create from template

### ISSUE THREAD

**Issue by anilsson97** [nextcloud/server#27313] opened 2021-05-31 21:46 UTC
![image](https://user-images.githubusercontent.com/74618677/120244381-526b0780-c26a-11eb-8924-9dc8891efa98.png)
![image](https://user-images.githubusercontent.com/74618677/120244389-572fbb80-c26a-11eb-838e-ca08c8d5ee66.png)

**Comment by szaimen** [comment] 2021-05-31 22:48
Looks to me like a duplicate of https://github.com/nextcloud/server/issues/26672

**Closed by szaimen** 2021-05-31 22:48 UTC
