### ISSUE TITLE
Gallery apps can't be accessed from "link share" page. Class UserId does not exist

### ISSUE THREAD

**Issue by Sesivany** [nextcloud/server#256] opened 2016-06-30 09:46 UTC
### Steps to reproduce
1. Share a folder with pictures via link
2. Open the link in another browser
3. Click the gallery view icon

### Expected behaviour
Users I share the folder with via link should be able to view is as a picture gallery and view individual pictures without having to download them.

### Actual behaviour
If the share link is created from within Gallery or Gallery+ apps it doesn't load at all and goes to "internal server error" page. If the link is created from Files the user I shared it with can open the link and see the folder, but if they want to switch to the gallery view, it goes to the "internal server error" page, too. Individual pictures need to be downloaded to view them.

### Server configuration
**Operating system**:
Fedora 24, 64 bit

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.1.14

**PHP version:**
php-5.6.22

**Nextcloud version:** (see Nextcloud admin page)
9.0.51

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Zip file from nextcloud.com

**Signing status (Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 8.8.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc8dql9cs9ex",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVEDIP***",
            "***REMOVEDDOMAIN***"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/***REMOVEDIP***\/nextcloud",
        "dbtype": "mysql",
        "version": "9.0.51.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVEDDOMAIN***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "enable_previews": "true",
        "asset-pipeline.enabled": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Any browser (Firefox, Chrome, Epiphany)

**Operating system:**
Tested on Fedora and Android

#### Web server error log
For Gallery+ app:
Exception: {"Exception":"OCP\AppFramework\QueryException","Message":"Could not resolve UserId! Class UserId does not exist","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('UserId')\n#1 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(150): OC\AppFramework\Utility\SimpleContainer->query('UserId')\n#2 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))\n#3 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(102): Pimple\Container->offsetGet('userId')\n#4 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64): OC\AppFramework\Utility\SimpleContainer->query('userId')\n#5 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#6 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\GalleryPlus...')\n#7 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GalleryPlus...')\n#8 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#9 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\GalleryPlus...')\n#10 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/app.php(97): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GalleryPlus...')\n#11 \/var\/www\/html\/nextcloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\AppFramework\App::main('PageController', 'publicIndex', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#12 [internal function]: OC\AppFramework\routing\RouteActionHandler->_invoke(Array)\n#13 \/var\/www\/html\/nextcloud\/lib\/private\/route\/router.php(276): calluser_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#14 \/var\/www\/html\/nextcloud\/lib\/base.php(950): OC\Route\Router->match('\/apps\/gallerypl...')\n#15 \/var\/www\/html\/nextcloud\/index.php(39): OC::handleRequest()\n#16 {main}","File":"\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":89}

For Gallery app:
Exception:
{"Exception":"OCP\AppFramework\QueryException","Message":"Could not
resolve UserId! Class UserId does not exist","Code":0,"Trace":"#0
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104):
OC\AppFramework\Utility\SimpleContainer->resolve('UserId')\n#1
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(150):
OC\AppFramework\Utility\SimpleContainer->query('UserId')\n#2
[internal function]:
OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))\n#3

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(102):
Pimple\Container->offsetGet('userId')\n#4
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64):
OC\AppFramework\Utility\SimpleContainer->query('userId')\n#5
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83):

OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#6

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104):

OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Gallery\\Env...')\n#7

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(64):

OC\AppFramework\Utility\SimpleContainer->query('OCA\\Gallery\\Env...')\n#8

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(83):

OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))\n#9

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php(104):

OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Gallery\\Con...')\n#10
\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/app.php(97):
OC\AppFramework\Utility\SimpleContainer->query('OCA\\Gallery\\Con...')\n#11

\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45):
OC\AppFramework\App::main('PageController', 'publicIndex',
Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#12
[internal function]:
OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#13
\/var\/www\/html\/nextcloud\/lib\/private\/route\/router.php(276):
call_user_func(Object(OC\AppFramework\routing\RouteActionHandler),
Array)\n#14 \/var\/www\/html\/nextcloud\/lib\/base.php(950):
OC\Route\Router->match('\/apps\/gallery\/s...')\n#15
\/var\/www\/html\/nextcloud\/index.php(39): OC::handleRequest()\n#16
{main}","File":"\/var\/www\/html\/nextcloud\/lib\/private\/appframework\/utility\/simplecontainer.php","Line":89}

#### Nextcloud log (data/owncloud.log)
Same error messages as in server error log.

#### Browser log
This is probably relevant:
Content Security Policy: Page settings blocked loading source on self ("script-src https://***REMOVEDDOMAIN*** 'unsafe-eval'").

**Comment by schiessle** [comment] 2016-06-30 18:47
sounds like a gallery bug, can you open a issue here: https://github.com/owncloud/gallery ? Thanks!

cc @oparoz fyi

**Comment by schiessle** [comment] 2016-06-30 18:47
I close this for now, if you come to the conclusion that it is a server error, feel free to re-open it.

**Comment by schiessle** [comment] 2016-06-30 18:51
I already copied the issue over to the gallery app: https://github.com/owncloud/gallery/issues/683

**Comment by oparoz** [comment] 2016-06-30 19:39
I'm re-opening since this problem doesn't seem to occur on ownCloud.

What happened to `UserId` in 9.0.50?

**Comment by LukasReschke** [comment] 2016-06-30 19:53
> I'm re-opening since this problem doesn't seem to occur on ownCloud.

Neither occurs in Nextcloud here. Can't reproduce locally.

**Comment by oparoz** [comment] 2016-06-30 21:00
@LukasReschke - Thanks for testing

@Sesivany - In the browser debug window, network tab, could you tell me which call hangs? Also, could you try without any other app enabled? I see you have installed news and documents per example.

**Comment by Sesivany** [comment] 2016-07-01 09:43
I switched off all other apps, no difference.
What hangs is this:
GET https://***REMOVEDDOMAIN***/nextcloud/index.php/apps/gallery/config.public?extramediatypes=1&token=G3vBYTXooIL7wG4 500 (Internal Server Error)

What may also be relevant is that I've set directory permissions according to this: https://docs.nextcloud.org/server/9/admin_manual/installation/installation_wizard.html#strong-perms-label
And I've also enabled JS and CSS asset management according to this: https://docs.nextcloud.org/server/9/admin_manual/configuration_server/js_css_asset_management_configuration.html

**Comment by oparoz** [comment] 2016-07-01 10:05
Thanks. The only thing I can suggest is to relax your file permissions to see if that solves it, but other parts of NC should be affected if a file can't be read. Maybe your installation is corrupt? Try to re-unpack NC?

**Comment by Sesivany** [comment] 2016-07-01 10:17
I disabled asset management, but no difference.
I also get this error: "shareconfigmodel.js?v=b5fb6a9…:24 Uncaught ReferenceError: oc_appconfig is not defined" in the browser debug mode.

**Comment by Sesivany** [comment] 2016-07-01 15:20
Is there a way to override the installation of NC and not to lose the settings like overriding just read-only files?

**Comment by Sesivany** [comment] 2016-07-09 12:34
I upgraded manually to 9.0.52. That involves rewriting all files except for config.php and /data. I also relaxed permissions and all files in /nextcloud have apache:apache owner now. The problem remains though.

**Comment by Sesivany** [comment] 2016-07-13 20:36
Just found out it works with PHP 7.0, but doesn't with 5.6.23.

**Comment by oparoz** [comment] 2016-07-21 11:44
Could not reproduce.

**Closed by oparoz** 2016-07-21 11:44 UTC
