### ISSUE TITLE
File / folder sizes are illegible in dark theme using 18.0.0 RC1.

### ISSUE THREAD

**Issue by cole8888** [nextcloud/server#18682] opened 2020-01-05 22:00 UTC
### Steps to reproduce
1.Update to 18.0.0 RC1 beta
2.Launch the web UI
3.File and folder sizes are illegible.

### Expected behaviour

To be able to read the file sizes in dark theme.

### Actual behaviour

The file sizes of various items are illegibly dark. This did not happen in 17.0.1.

### Server configuration

**Operating system:** Ubuntu 19.04

**Web server:** NGINX

**Database:** MariaDB

**PHP version:** 7.3.4-1

**Nextcloud version:** 18.0.0 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** Older Nextcloud (17.0.1)

**Where did you install Nextcloud from:** CLI Updater

**Signing status:**
<details>
<summary>Signing status</summary>
```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**

<details>
<summary>App list</summary>
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - dav: 1.14.0
  - extract: 1.2.2
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - groupfolders: 6.0.0
  - keeweb: 0.5.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.10.0
  - oauth2: 1.6.0
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.1
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - audioplayer
  - bruteforcesettings
  - checksum
  - comments
  - deck
  - drawio
  - encryption
  - federation
  - files_external
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - notifications
  - onlyoffice
  - password_policy
  - privacy
  - qownnotesapi
  - recommendations
  - sharebymail
  - support
  - survey_client
  - systemtags
  - tasks
  - text
  - updatenotification
  - user_ldap
  - video_converter
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***removed***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.8",
        "overwrite.cli.url": "***removed***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "installed": true,
        "auth.bruteforce.protection.enabled": true,
        "trashbin_retention_obligation": "1, 3,",
        "versions_retention_obligation": "disabled",
        "updater.release.channel": "beta",
        "enable_previews": true,
        "maintenance": false,
        "filelocking.enabled": true,
        "integrity.check.disabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "onlyoffice": {
            "verify_peer_off": true
        },
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "keeweb",
            "files_clipboard",
            "occweb",
            "group_everyone",
            "issuetemplate",
            "files_reader",
            "groupfolders",
            "ocsms",
            "video_converter",
            "files_photospheres",
            "audioplayer",
            "extract",
            "metadata",
            "richdocuments",
            "discoursesso"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

</details>

### Client configuration
**Browser:** Firefox 72.0b11

**Operating system:** Kubuntu 19.10

![image](https://user-images.githubusercontent.com/32819560/71786664-31a27200-2fe4-11ea-8e4d-1506fb5b89a5.png)

This issue has been fixed before in previous releases [11441](https://github.com/nextcloud/server/issues/11441) and [11823](https://github.com/nextcloud/server/pull/11823)

**Comment by Bielecki** [comment] 2020-01-28 12:40
Also same issue with orphaned external storages. Looks good on default theme:  
![obraz](https://user-images.githubusercontent.com/12011545/73263200-526b7b00-41d0-11ea-9854-ce95508a26ba.png)
but doesn't on dark one:
![obraz](https://user-images.githubusercontent.com/12011545/73263324-9bbbca80-41d0-11ea-8179-a2a12f3f7220.png)

**Operating system**: Debian 10, kernel 4.9.160-armada375  
**Web server**: NGINX  
**Database**: MariaDB  
**PHP version**: 7.3.14-1  
**Nextcloud version**: 18.0.0.10  
**Updated from an older Nextcloud/ownCloud or fresh install**: All the way up from ownCloud X (to NC12 and then upgraded one major version at a time)

**Comment by sndrr** [comment] 2020-02-22 21:40
Seems the texts have different colors, this one being all black (RGB 000000):
![image](https://user-images.githubusercontent.com/5821198/75099563-6afa6580-55c3-11ea-8559-643129969a98.png)
And this one being slightly grey-ish (RGB 6D6D6D):
![image](https://user-images.githubusercontent.com/5821198/75099593-a8f78980-55c3-11ea-8f5c-8f4c3f52f4c2.png)
And a third one being another shade of grey (RGB 767676)
![image](https://user-images.githubusercontent.com/5821198/75099614-e9570780-55c3-11ea-843f-af08aae9fc70.png)


See them all three below each other, slightly different shade:
![image](https://user-images.githubusercontent.com/5821198/75099635-23280e00-55c4-11ea-94fc-cb616b46d9b1.png)

**Comment by cole8888** [comment] 2020-02-23 22:54
For anyone interested I ended up simply installing the [Breeze Dark theme](https://apps.nextcloud.com/apps/breezedark) which accomplished the same effect as the Dark Theme for me.

**Comment by skjnldsv** [comment] 2020-09-09 11:19
Duplicate of https://github.com/nextcloud/server/issues/21069

**Closed by skjnldsv** 2020-09-09 11:19 UTC
Labels: 0. Needs triage, bug, design
