### ISSUE TITLE
Figure out why resolver cannot resolve OCA\Theming\Template but OCA\Theming\Foobar

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#849] opened 2016-08-12 14:09 UTC
When working on #796 we encountered the issue that when OCA\Theming\ThemingDefaults was still called OCA\Theming\Template the class resolver (`\OC::$server->resolve($className)`)) was not able to find and instantiate the class. 

It seems strange, because no other Whatever/Template is registered in either Server.php nor DIContainer.php. 

@schiessle 's assumption is that it resolving could crash because of \OCP\Template. I don't think so, because the autoloader caches always the whole namespace with the class name. But I have no better idea so far.

No urge to have it fixed for Nc 10.

cc @nickvergessen

**Comment by rullzer** [comment] 2016-08-13 12:51
Are you sure that the app was enabled? Because I just tried here with a simple test app and it all works...

**Comment by rullzer** [comment] 2016-08-13 13:13
Ok I got it now... lets see why

**Comment by rullzer** [comment] 2016-08-13 17:58
Ah no. This all works for me. It was because the theming app is enabled by default but the theming stuff is not inserted into the db then.

Anyway. Can't reproduce this :(
Do you have detailed steps @blizzz ?

**Comment by blizzz** [comment] 2016-08-15 08:38
I'd give you more detailed steps once i have some more air. For now, what described as last point here https://github.com/nextcloud/server/pull/796#issuecomment-239583271 might be related.

**Comment by rullzer** [comment] 2016-08-15 09:16
Yep air is important!

**Comment by rullzer** [comment] 2016-09-03 18:21
I bet this is basically the same thing we had with the autoloader magic.

**Comment by MorrisJobke** [comment] 2016-11-25 01:22
@blizzz is this still valid?

**Comment by rullzer** [comment] 2016-11-25 06:01
Yes

**Comment by blizzz** [comment] 2016-11-28 11:36
Now I don't know (fail) to reproduce it properly. Perhaps I should have used query() instead of resolve() directly.

**Comment by nickvergessen** [comment] 2016-11-28 15:31
When you use resolve directly, it should be looking into the wrong container, because the query() method takes care of that:
https://github.com/nextcloud/server/blob/94432c089f0a598ed2e96d086731b44dc2897918/lib/private/ServerContainer.php#L76-L87

I guess we could also do this on the resolve method, since it it public API https://github.com/owncloud/core/pull/18991

**Comment by blizzz** [comment] 2016-11-29 15:53
Perhaps it was just wrong  use. I guess we can leave it like it is, why should both methods do the same? ``query`` is invoking ``resolve`` if necessary.

**Comment by MorrisJobke** [comment] 2016-11-29 15:57
> Perhaps it was just wrong use. I guess we can leave it like it is, why should both methods do the same? query is invoking resolve if necessary.

Then close this ticket or not?

**Closed** 2016-11-29 21:44 UTC
Labels: bug
