### ISSUE TITLE
Upgrade from 14.0.1 to 14.0.2 RC1 waiting for cron to finish

### ISSUE THREAD

**Issue by Emi94** [nextcloud/server#11630] opened 2018-10-05 06:31 UTC
### Steps to reproduce
1.Start upgrade on web interface from NC 14.0.1 to 14.0.2 RC 1
2.Continue with the `occ upgrade`

### Expected behaviour
Upgrade should finish successfully

### Actual behaviour
After running `occ upgrade` I get "Waiting for cron to finish (checks again in 5 seconds)" over and over

### Server configuration

**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** postgresql 9.5

**PHP version:** php 7.0

**Nextcloud version:** 14.0.1 -> 14.0.2 RC 1

I managed to make the upgrade continue by running `UPDATE oc_jobs SET reserved_at=0` as specified here: #9992

This is the job that had a reserved_at > 0:
`6 | OCA\Files\BackgroundJob\ScanFiles                               | null     | 1538701211 |   1538701211 |  1538701211 |                884`

**Comment by Co0p3r21** [comment] 2018-10-05 16:54
The workaround #10949 still works. But for me there is a problem with Code integrity. It is possible to fix it but keep that in mind.

**Comment by enzolis** [comment] 2018-10-11 12:35
Same issue during update to final version:  14.0.1 -> 14.0.2
Workaround fixes the hang.
The offending job in my case was:
226 | OCA\Survey_Client\BackgroundJobs\MonthlyReport | null | 1539258472 | 1539258472 | 1539258472  | 0

Best regards,
 Thimo

**Comment by MorrisJobke** [comment] 2018-10-12 08:06
Duplicate of #10949

**Closed by MorrisJobke** 2018-10-12 08:06 UTC
Labels: bug

**Comment by MorrisJobke** [comment] 2018-10-12 08:07
Workaround can be found in https://github.com/nextcloud/server/issues/10949#issuecomment-426033160 and the very next comment there.
