### ISSUE TITLE
Updating through web interface unsets theme

### ISSUE THREAD

**Issue by TheLastProject** [nextcloud/server#13731] opened 2019-01-22 10:11 UTC
### Steps to reproduce
1. Notice there's an update
2. Open the web updater
3. Click start

### Expected behaviour
Theme is not unset without warning the user in advance, or at least put back after the update completes

### Actual behaviour
Theme is unset unexpectedly and needs manual configuration change to restore

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** 14.0.4 -> 14.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official website .tar.gz

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.8
  - dav: 1.6.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.2
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.6.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": "True",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "log_type": "syslog",
        "syslog_tag": "nextcloud",
        "logtimezone": "UTC",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "app.mail.accounts.default": {
            "email": "***REMOVED SENSITIVE VALUE***",
            "imapHost": "***REMOVED SENSITIVE VALUE***",
            "imapPorts": 993,
            "imapUser": "%USERID%",
            "imapSslMode": "ssl",
            "smtpHost": "s***REMOVED SENSITIVE VALUE***",
            "smtpPort": 587,
            "smtpUser": "%USERID%",
            "smtpSslMode": "tls"
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "my_custom_theme",
        "loglevel": "0",
        "auth.bruteforce.protection.enabled": true,
        "skeletondirectory": "\/var\/www\/nextcloud\/skeleton",
        "force_language": "en",
        "mail_smtpdebug": true,
        "updatechecker": true,
        "has_internet_connection": true,
        "check_for_working_webdav": false,
        "connectivity_check_domains": [],
        "mail_smtptimeout": "10",
        "data-fingerprint": "aa65dc344c255b5bf294216792bae7ae",
        "updater.release.channel": "production",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox

**Operating system:** macOS Mojave

**Comment by skjnldsv** [comment] 2019-03-03 19:02
@juliushaertl

**Comment by kesselb** [comment] 2020-01-26 20:48
Closing as duplicate of https://github.com/nextcloud/server/issues/2785

**Closed by kesselb** 2020-01-26 20:48 UTC
Labels: 0. Needs triage, bug
