### ISSUE TITLE
No access to trash via browser interface

### ISSUE THREAD

**Issue by DocKDE** [nextcloud/server#17200] opened 2019-09-18 16:37 UTC
Hello,
I realize this has been an issue before but it seems the previous fixes have already been applied and the problem still persists. Interestingly only one user is affected.
The log shows this:

`
[remote] Error: TypeError: Return value of OCA\Files_Trashbin\Sabre\AbstractTrash::getSize() must be of the type int, float returned at <<closure>>

 0. /var/www/html/nextcloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php line 78
    OCA\Files_Trashbin\Sabre\AbstractTrash->getSize()
 1. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 98
    OCA\Files_Trashbin\Sabre\PropfindPlugin->OCA\Files_Trashbin\Sabre\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/html/nextcloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php line 79
    Sabre\DAV\PropFind->handle("{http://owncloud.org/ns}size", Closure {})
 3. <<closure>>
    OCA\Files_Trashbin\Sabre\PropfindPlugin->propFind(Sabre\DAV\PropFind {}, OCA\Files_Trashbin\Sabre\TrashFile {})
 4. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\Files_Trash ... "], [Sabre\DAV\PropF ... }])
 5. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1059
    Sabre\Event\EventEmitter->emit("propFind", [Sabre\DAV\PropF ... }])
 6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 981
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\Files_Trashbin\Sabre\TrashFile {})
 7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("trashbin/benedikt/trash", ["{http://nextcl ... "], 1)
 8. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
 9. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
10. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
11. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
12. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
13. /var/www/html/nextcloud/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
14. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
15. /var/www/html/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/html/n ... p")

PROPFIND /nextcloud/remote.php/dav/trashbin/benedikt/trash
from 185.62.205.145 by benedikt at 2019-09-18T16:20:11+00:00
`

**Comment by kesselb** [comment] 2019-09-19 20:37
Looks like a duplicate of https://github.com/nextcloud/server/issues/13160

**Closed by kesselb** 2019-09-19 20:37 UTC
