### ISSUE TITLE
Dashboard widgets with no content have a different height

### ISSUE THREAD

**Issue by ppfeufer** [nextcloud/server#35282] opened 2022-11-19 16:43 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On the dashboard page, cars with no content are higher than cards with content.

### Steps to reproduce

1. Open the Dashboard page
2. Add some cards (with and without content)
3. Have a closer look

### Expected behavior

All cards should have the same height, no matter if they have content or not

### Installation method

Community Manual installation with Archive

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.ppfeufer.de"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "nextcloud.ppfeufer.de",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloud.ppfeufer.de",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "check_data_directory_permissions": false,
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "preview_max_x": 1920,
        "preview_max_y": 1080,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MKV",
            "OC\\Preview\\AVI",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\OpenDocument"
        ],
        "trashbin_retention_obligation": "5, 7",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_language": "en",
        "default_phone_region": "DE",
        "appcodechecker": true,
        "connectivity_check_domains": [
            "www.nextcloud.com"
        ],
        "enable_file_metadata": true,
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "cron_log": true,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "filesystem_check_changes": 0,
        "filelocking.enabled": true,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_antivirus"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
    - activity: 2.17.0
    - admin_audit: 1.15.0
    - bookmarks: 11.0.4
    - bruteforcesettings: 2.5.0
    - calendar: 4.1.0
    - circles: 25.0.0
    - cloud_federation_api: 1.8.0
    - contacts: 5.0.1
    - contactsinteraction: 1.6.0
    - dashboard: 7.5.0
    - dav: 1.24.0
    - deck: 1.8.2
    - encryption: 2.13.0
    - federatedfilesharing: 1.15.0
    - federation: 1.15.0
    - files: 1.20.1
    - files_antivirus: 3.3.1
    - files_external: 1.17.0
    - files_pdfviewer: 2.6.0
    - files_rightclick: 1.4.0
    - files_sharing: 1.17.0
    - files_trashbin: 1.15.0
    - files_versions: 1.18.0
    - fileslibreofficeedit: 1.1.0
    - integration_github: 1.0.12
    - logreader: 2.10.0
    - lookup_server_connector: 1.13.0
    - maps: 0.2.1
    - metadata: 0.17.0
    - notes: 4.6.0
    - notifications: 2.13.1
    - oauth2: 1.13.0
    - password_policy: 1.15.0
    - photos: 2.0.0
    - privacy: 1.9.0
    - provisioning_api: 1.15.0
    - quota_warning: 1.15.0
    - ransomware_protection: 1.14.0
    - recognize: 3.2.2
    - related_resources: 1.0.3
    - serverinfo: 1.15.0
    - settings: 1.7.0
    - sharebymail: 1.15.0
    - suspicious_login: 4.3.0
    - systemtags: 1.15.0
    - tasks: 0.14.5
    - text: 3.6.0
    - theming: 2.0.1
    - twofactor_backupcodes: 1.14.0
    - twofactor_totp: 7.0.0
    - updatenotification: 1.15.0
    - user_status: 1.5.0
    - viewer: 1.9.0
    - weather_status: 1.5.0
    - workflowengine: 2.7.0
Disabled:
    - comments: 1.15.0
    - firstrunwizard: 2.13.0
    - nextcloud_announcements: 1.14.0
    - recommendations: 1.3.0
    - support: 1.8.0
    - survey_client: 1.12.0
    - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
It's a graphical bug, no logs needed here :-)
```

**Comment by ppfeufer** [comment] 2022-11-19 16:45
And as a little visual help of what I'm talking about ...

![image](https://user-images.githubusercontent.com/2989985/202862027-7c04581d-8968-4412-91f8-abe8b56872ef.png)

**Comment by JojoBr0** [comment] 2022-12-20 14:56
I have recognized the same problem.

It also seems that the icons are not in line with the card headers.

**Comment by joshtrichards** [comment] 2023-09-19 14:09
Related (potentially even the same issue): #39646

**Comment by joshtrichards** [comment] 2024-09-13 17:15
Duplicate of #34582

**Closed by joshtrichards** 2024-09-13 17:15 UTC
Labels: bug, design, 0. Needs triage, feature: dashboard, 25-feedback, needs review
