### ISSUE TITLE
Could not connect to appstore: cURL error 7: Failed to connect to apps.nextcloud.com 

### ISSUE THREAD

**Issue by FlorianJSa** [nextcloud/server#23354] opened 2020-10-11 14:19 UTC
Currently it seems impossible Apps from apps.nextcloud.com the web server seems to be unreachable

**Comment by acsfer** [comment] 2020-10-11 14:32
Duplicate of...many. Use search next times before posting and refer to https://github.com/nextcloud/server/issues/23334 thanks 👍

**Closed by acsfer** 2020-10-11 14:32 UTC

**Comment by FlorianJSa** [comment] 2020-10-11 14:52
Thank you very much for your answer. Do you have any information if the error will be fixed soon?
