### ISSUE TITLE
[18.0.12] PHP deprecated warning 3rdparty vobject

### ISSUE THREAD

**Issue by tuxmaster5000** [nextcloud/server#24673] opened 2020-12-12 09:05 UTC
After update to php 7.4 the crontab will report this php warning:
```
PHP Deprecated:  The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /var/www/html/owncloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php on line 357
PHP Deprecated:  The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /var/www/html/owncloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php on line 423
```

**Comment by kesselb** [comment] 2020-12-12 15:54
Duplicate of https://github.com/nextcloud/server/issues/16574

**Closed by kesselb** 2020-12-12 15:54 UTC
Labels: 0. Needs triage, bug
