### ISSUE TITLE
Federated cloud share icons overlap in button

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#30819] opened 2022-01-23 18:33 UTC
See screenshot (22.2.3 here)

![image](https://user-images.githubusercontent.com/12234510/150692735-b6380b03-473c-4f57-954a-4fd2e2cba667.png)

**Comment by shubham2o** [comment] 2022-02-17 14:22
I would like to work on this, can you please assign me this issue?

**Comment by acsfer** [comment] 2022-02-18 21:53
Go to /settings/user/sharing

**Comment by Lucarnosky** [comment] 2022-03-16 16:14
Hello, I see that is some time the issue is not been worked. I've fixed it, if you wanna you can assign this problem to me and I can send the pull request.

**Closed** 2022-03-17 11:34 UTC
Labels: bug, design, good first issue, 0. Needs triage
