### ISSUE TITLE
where can I change the  Nextcloud below?

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/server#10126] opened 2018-07-06 06:19 UTC
Excuse me, if I open the maintenance mode, where can I change the  Nextcloud below ( and ''keep your data'')?

**Comment by chiyi4488** [comment] 2018-07-06 06:34
No, I mean, if I turn on maintenance mode, the text inside doesn't become the name I wrote in the theme, I want to change it (direct file change)

**Comment by MorrisJobke** [comment] 2018-07-06 07:40
This is a know limitation:

The the app data and the theming app is not available. Nevertheless there is the idea of a plain maintenance mode page: #5789

Thus closing as duplicate of #5789 (see also #9069)

**Closed by MorrisJobke** 2018-07-06 07:40 UTC
Labels: bug

**Comment by chiyi4488** [comment] 2018-07-06 11:39
Okay, but where is the maintenance mode html file? I want to modify it directly.

**Comment by MorrisJobke** [comment] 2018-07-06 12:55
https://github.com/nextcloud/server/blob/master/core/templates/update.user.php

**Comment by MorrisJobke** [comment] 2018-07-06 12:55
And the normal layout is at https://github.com/nextcloud/server/blob/master/core/templates/layout.guest.php

**Comment by chiyi4488** [comment] 2018-07-06 17:10
Um.....I read the file, but I didn't see any strings that would allow me to modify Nextcloud and keep your data... (sorry, poor understanding)

**Comment by chiyi4488** [comment] 2018-07-06 17:19
Or do I have to go to themes folder to make changes?

**Comment by MorrisJobke** [comment] 2018-07-09 07:40
> Or do I have to go to themes folder to make changes?
The "Keep your data ..." is the slogan in the layout file. Best is to overwrite that file in a theme. For themes read the docs, but be aware, that it very likely need to be updated on every major version upgrade to not break the system. Thus we tend to avoid using themes, because they have a high maintenance cost and high risk of breakage.
