### ISSUE TITLE
No Activity App File Icons when using https

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#4960] opened 2017-05-19 10:43 UTC
### Steps to reproduce
1. use your site with https://...
2. open Activity App
3. no icons show up in sidebar/workarea
>>> checking page html shows that icons are referenced with "http" instead of "https" - should be the http/https prefix that is used when accessing the site

### Expected behaviour
icons should be visible

### Actual behaviour
no icons / broken icon

### Server configuration
Using webhoster.

**Operating system**:
ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6.30

**Nextcloud version:** (see Nextcloud admin page)
11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
fromdownloaded zipfile

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment] 2017-05-19 11:07
Please post your Nextcloud config.

**Comment by MorrisJobke** [comment] 2017-10-30 16:04
Owner deletes his github account and we can't reproduce -> closing

**Closed by MorrisJobke** 2017-10-30 16:04 UTC
Labels: 0. Needs triage, bug, needs info
