### ISSUE TITLE
Changing Backgroundimages is reverting 

### ISSUE THREAD

**Issue by hotschmaster23** [nextcloud/server#5494] opened 2017-06-21 05:04 UTC
### Steps to reproduce
1. Change the background and icon in admin page under theming from the inside network
2.logout and access the server from the outside public address
3.now you recognize that the theming is only changed with the colour i set but no icon and background is set
4.the change is only displayed on inside but not from the outside network
5.login from outside to the server and change the background and icon on theming app
6.logout and access the server from the inside address
7.theming is now not changed no background and icon is set
8.the change is only displayed on outside network but not when you access it from inside address

### Expected behaviour
Changing the theming internally and externally. theming should be the same for both directions

### Actual behaviour
When I change the background from my internal Network to a custom wallpaper it is not displaying this when you login from outside to this server.
After changing the background from outside the change is not displayed when i open the site from my internal network.
no logging in the apache log and in nextcloud log

### Server configuration

**Operating system**:Ubuntu 16.04.4

**Web server:**Apache 2.4.18

**Database:** 10.0.29-MariaDB

**PHP version:**7.0.15

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** upate via Beta Change from 11.03

**Where did you install Nextcloud from:**nextcloud website repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**opera, firefox, chrome

**Operating system:**macos, ios, linux ubuntu mate, linux ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by juliushaertl** [comment] 2017-06-22 19:57
Duplicate of https://github.com/nextcloud/server/issues/5085.

**Closed by juliushaertl** 2017-06-22 19:57 UTC
