### ISSUE TITLE
If you create a new file by entering"%" in the file name or folder name, the list of the folder can not be read.

### ISSUE THREAD

**Issue by enpela** [nextcloud/server#11452] opened 2018-09-29 10:49 UTC
### Steps to reproduce
1. create a new file by entering"%" in the file name or folder name.

### Expected behavior
File list is displayed

### Actual behavior
Folder will be loading forever.
However, it does not occur in applications such as Android.

### Server configuration

**Operating system**: CentOS Linux release 7.5.1804 (Core)

**Web server:** Apache/2.4.6

**Database:** MariaDB/10.2.18

**PHP version:** php/7.1.22

**Nextcloud version:** Nextcloud 14.0.1

#### Browser log
<summary>Browser log</summary>

```
Uncaught (in promise) URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Client._parseFileInfo (client.js:283)
    at client.js:407
    at Function._.map._.collect (core.js:185)
    at Client._parseResult (client.js:406)
    at client.js:488
```

**Comment by MorrisJobke** [comment] 2018-09-30 10:01
cc @skjnldsv @rullzer 🙈

**Comment by skjnldsv** [comment] 2018-09-30 13:01
@MorrisJobke this is a duplicate of #11405
Let me find Caused by a pr of Robin. :)

**Comment by MorrisJobke** [comment] 2018-10-01 09:41
> @MorrisJobke this is a duplicate of #11405

Then close it as duplicate 😉

**Closed by MorrisJobke** 2018-10-01 09:41 UTC
Labels: bug

**Comment by skjnldsv** [comment] 2018-10-01 09:51
@MorrisJobke damn, I thought I pressed it :see_no_evil:
