### ISSUE TITLE
Improve "there was an error updating your attendance"

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#15230] opened 2019-04-24 19:16 UTC
This post sums it up quite well: https://help.nextcloud.com/t/solved-cannot-accept-calendar-invitation/50154/3

Basically, if two users are using the same email address for different users, the attendance when sending invitations can't be accepted. To solve it all the users email addresses in Nextcloud have to be unique.

@georgehrke I think this could/should be improved. Or at least write out the reason "Your attendance could not be updated due to that the same email address is used for multiple users" or similar.

Is it possible?

**Comment by georgehrke** [comment] 2019-04-25 13:26
Moving to server, since the dav app is responsible for handling responses.

**Comment by georgehrke** [comment] 2019-04-25 13:28
Closely related to https://github.com/nextcloud/server/issues/6235

**Comment by georgehrke** [comment] 2019-09-14 14:59
Closing as Duplicate of #6235, because the root cause is the same.

**Closed by georgehrke** 2019-09-14 14:59 UTC
Labels: 0. Needs triage, enhancement, feature: dav
