### ISSUE TITLE
[Bug]: Calendar notifications sent to all clients

### ISSUE THREAD

**Issue by davidchisnall** [nextcloud/server#44267] opened 2024-03-18 09:52 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

For the last one or two major upgrades, I've started getting calendar notifications delivered to all of the Nextcloud clients connected to my server.  Calendars are sync'd via CalDAV to all of the same client devices that run the Nextcloud client and so I end up with two notifications for every event.  I can turn off all notifications, but then I don't get notifications for things like failed uploads (which I actually want from the clients).

I have looked for an option on the server to not deliver calendar events to clients, but I can't find one, so it either doesn't exist or is not readily discoverable.

### Steps to reproduce

1. Create calendar event with reminder.
2. Sync calendar with CalDAV to client device with Nextcloud client installed.
3. Observe two notifications.

### Expected behavior

Calendar notifications should (optionally?) not be sent to Nextcloud clients.  

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by majewsky** [comment] 2024-06-07 22:44
Can reproduce. I have my CalDAV added to the regular iOS calendar app on my phone. Since upgrading NextCloud from 27 -> 28 -> 29 last week, I am now getting duplicate calendar notifications from the NextCloud app, but I only want the ones from the iOS Calendar app.

**Comment by majewsky** [comment] 2024-06-07 22:53
Sorry for the noise. I looked a bit more and saw that this is a duplicate of #42659. A workaround is provided over there.

**Comment by joshtrichards** [comment] 2024-06-09 17:17
*Administration settings->Groupware->Calendar*

Pish notifications toggle is the last option listed there.

**Closed** 2024-06-09 17:18 UTC
Labels: bug, 0. Needs triage, 29-feedback
