### ISSUE TITLE
NC29 Files app not showing all files/folder

### ISSUE THREAD

**Issue by chsleemsi** [nextcloud/server#46730] opened 2024-07-25 05:34 UTC
upgrade to NC29.  The Files app not showing all files/folders.  The footer shows 23 files and 54 folders but it only lists few folders.

**Comment by joshtrichards** [comment] 2024-07-25 11:54
You didn't fill out the Issue template, so not much we can do. 

But are you using the `files_readmemd` app by chance? If so, duplicate of #46470. See mamatt/files_readmemd#159

**Closed by joshtrichards** 2024-07-25 11:54 UTC
