### ISSUE TITLE
Updater won't work in 12.0 beta 2

### ISSUE THREAD

**Issue by hkistemaker** [nextcloud/server#4901] opened 2017-05-16 12:59 UTC
### Steps to reproduce
1. Update 12.0 beta 2 to beta 3
2. Click Start update button.
3. Nothing happens

### Expected behaviour
Web updater checks should run.

### Actual behaviour
Nothing, only the Start update button is pressed.

### Server configuration

**Operating system**:
Ubuntu 16.0.4.2
**Web server:**

**Database:**
MariaDB 10.1.23
**PHP version:**
7.0.15
**Nextcloud version:** (see Nextcloud admin page)
12.0 beta 2
**Updated from an older Nextcloud/ownCloud or fresh install:**
update from 10 to 11 and then 12

**Comment by ChristophWurst** [comment] 2017-05-16 13:44
Duplicate of https://github.com/nextcloud/updater/issues/108

**Closed** 2017-05-16 13:47 UTC
