### ISSUE TITLE
Error: Method not allowed (Move)

### ISSUE THREAD

**Issue by Codingroller** [nextcloud/server#15683] opened 2019-05-22 09:38 UTC
### Steps to reproduce
1. Move a random file from one folder to another.

### Expected behaviour
File should be moved to the destination folder

### Actual behaviour
Error message on screen: Could not move "_file x_"

### Server configuration

**Operating system**: Shared host server, not visible

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 16

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11 onwards.

**Where did you install Nextcloud from:** downloaded from Git.

**Apps:**
<details>

Enabled:  - accessibility: 1.2.0  - bruteforcesettings: 1.3.0  - cloud_federation_api: 0.2.0  - comments: 1.6.0  - contacts: 3.1.1  - dav: 1.9.2  - federatedfilesharing: 1.6.0  - files: 1.11.0  - files_external: 1.7.0  - files_pdfviewer: 1.5.0  - files_rightclick: 0.13.0  - files_sharing: 1.8.0  - files_texteditor: 2.8.0  - files_trashbin: 1.6.0  - files_versions: 1.9.0  - files_videoplayer: 1.5.0  - firstrunwizard: 2.5.0  - gallery: 18.3.0  - keeporsweep: 0.2.1  - logreader: 2.1.0  - lookup_server_connector: 1.4.0  - nextcloud_announcements: 1.5.0  - notifications: 2.4.1  - oauth2: 1.4.2  - occweb: 0.0.4  - password_policy: 1.6.0  - passwords: 2019.5.0  - previewgenerator: 2.1.0  - privacy: 1.0.0  - provisioning_api: 1.6.0  - rainloop: 6.0.2  - recommendations: 0.4.0  - serverinfo: 1.6.0  - sharebymail: 1.6.0  - support: 1.0.0  - systemtags: 1.6.0  - tasks: 0.10.1  - theming: 1.7.0  - twofactor_backupcodes: 1.5.0  - twofactor_totp: 2.1.2  - unsplash: 1.1.3  - updatenotification: 1.6.0  - viewer: 1.0.0  - workflowengine: 1.6.0Disabled:  - activity  - admin_audit  - calendar  - encryption  - federation  - files_frommail  - mindmaps  - ocr  - survey_client  - user_ldap
</details>

### Client configuration
**Browser:**Chrome 74.0.3729.157 

**Operating system:** Win 10

#### Web server error log
```
[Wed May 22 10:41:37.406487 2019] [allowmethods:error] [pid 141262:tid 139651713062656] [client 185.46.213.75:32053] AH01623: client method denied by server configuration: 'MOVE' to /home/u1335p238/domains/domain/private_html/nextcloud/remote.php
</details>


#### Browser log
<details>
<summary>Browser log</summary>

```
Browser console:
client.js:250 MOVE https://domain/nextcloud/remote.php/dav/files/user/folder/picture.PNG 405 (Method Not Allowed)
```
</details>

**Comment by muisit** [comment] 2019-09-13 09:19
+1
It seems MOVE is not an allowed method in the server configuration. Nextcloud client could perform a POST-DELETE combination to work around this issue as long as the server is not reconfigured properly. Some hosted providers do not easily allow such reconfiguration.

**Comment by szaimen** [comment] 2021-05-26 11:59
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-26 11:59 UTC
Labels: 0. Needs triage, bug

**Comment by zhang-win** [comment] 2022-12-01 15:30
It reproduce in version after 24.0，and now i cannot find out path to resolve it
