### ISSUE TITLE
personal calendar for newly created users has no calendar color set

### ISSUE THREAD

**Issue by mbiebl** [nextcloud/server#11256] opened 2018-09-17 01:53 UTC
Nextcloud: 13.0.6

When creating a new user, it by default gets a personal addressbook and calendar. Unfortunately, the calendar has not color set by default. Looking at the db dump, I see
```
INSERT INTO `sgnDV_calendars` (`id`, `principaluri`, `displayname`, `uri`, `synctoken`, `description`, `calendarorder`, `calendarcolor`, `timezone`, `components`, `transparent`) VALUES

(5, 'principals/users/test', 'Personal', 'personal', 1, NULL, 0, NULL, NULL, 'VEVENT,VTODO', 0);
```
Notice how calendarcolor is set to ```NULL```.
Please pick a reasonable default instead of ```NULL```

**Comment by MorrisJobke** [comment] 2018-09-27 14:39
cc @georgehrke

**Comment by szaimen** [comment] 2021-05-21 11:47
I'm closing this issue due to inactivity. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Comment by mbiebl** [comment] 2021-05-21 21:17
Unfortunately, I can't reopen it seems. Please do so. Afaics his has not been fixed yet.

**Comment by szaimen** [comment] 2021-05-21 21:21
So you can still reproduce this on NC21.0.2?

**Comment by mbiebl** [comment] 2021-05-21 21:25
It seems I still have user calendars where color is set to NULL

**Comment by mbiebl** [comment] 2021-05-21 21:30
Just create a new use, log in as that user, notice how the "Personal" calendar for that user is set to NULL.
If you think this was fixed, a reference to a commit would be appreciated (or asking before closing bug reports. Simply closing them  I find not particularly friendly, tbh).

**Comment by szaimen** [comment] 2021-05-21 21:30
I'll try to reproduce this in a monent

**Comment by szaimen** [comment] 2021-05-21 22:00
I am actually not able to reproduce this: this user is fresh and the personal calendar has a valid color:
![image](https://user-images.githubusercontent.com/42591237/119202096-6c4d6300-ba90-11eb-94ad-8f4f561fa975.png)
Or what do you mean with calendarcolor is set to NULL?

**Comment by szaimen** [comment] 2021-05-21 22:12
> or asking before closing bug reports. Simply closing them I find not particularly friendly, tbh

That's why I've asked to reopen the issue if it should still be valid. 
But now that I've tried to reproduce this and failed, I think it was correct to close it.

**Comment by mbiebl** [comment] 2021-05-21 22:17
sigh, please check the database dump

**Comment by mbiebl** [comment] 2021-05-21 22:20
I'll just dump it again for your convenience
```
INSERT INTO `n3Lul_calendars` (`id`, `principaluri`, `displayname`, `uri`, `synctoken`, `description`, `calendarorder`, `calendarcolor`, `timezone`, `components`, `transparent`) VALUES
...
(9, 'principals/users/test1', 'Personal', 'personal', 1, NULL, 0, NULL, NULL, 'VEVENT,VTODO', 0),
```

**Comment by szaimen** [comment] 2021-05-21 22:33
I don't understand why this is imprtant to you but I guess it should be technically filles with a value, yes.
=> reopen.
Sry for the trouble and thanks for your patience!

**Comment by szaimen** [comment] 2021-05-21 22:34
cc @nextcloud/calendar

**Comment by ChristophWurst** [comment] 2021-06-25 12:24
PR is at https://github.com/nextcloud/server/pull/17148

**Closed** 2021-07-02 14:29 UTC
Labels: 1. to develop, bug, feature: dav
