### ISSUE TITLE
[Bug]: Cannot import calendar event (Invalid Mimedir file)

### ISSUE THREAD

**Issue by duburcqa** [nextcloud/server#48566] opened 2024-10-04 10:16 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I was unable to accept a calendar event that I received by email. While trying to go back to the root cause, I realised that importing manually in Nextcloud calendar app the `ics` file attached to the email was failing with the same traceback. I think this is a bug that should be solved, no matter if the event is "slightly broken", eventually relying on some fallback mechanism to "repair" the content. It is not acceptable to not be able to add to the calendar an event received by email that is working properly with other services such as google calendar.

### Steps to reproduce

1. Save the provided file content locally as a ".ics" extension file.
2. Open to calendar app
3. Select "Import calendar" in "Calendar settings"
4. Drop the ".ics" that was just previously created
5. Enjoy the error message related to import failure

```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Microsoft Corporation//Outlook for Mac MIMEDIR//EN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Romance Standard Time
X-ENTOURAGE-CFTIMEZONE:Europe/Brussels
X-ENTOURAGE-TZID:11
BEGIN:STANDARD
RRULE:FREQ=YEARLY;INTERVAL=1;BYSECOND=0;BYMINUTE=0;BYHOUR=3;BYDAY=-1SU;BYM
 ONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:16011001T030000
END:STANDARD
BEGIN:DAYLIGHT
RRULE:FREQ=YEARLY;INTERVAL=1;BYSECOND=0;BYMINUTE=0;BYHOUR=2;BYDAY=-1SU;BYM
 ONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:16010301T020000
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:20241003T203032Z-85858301942@fe80:0:0:0:43a:40ff:fedd:b3bdeth0
X-ENTOURAGE_UUID:A5712978-0598-441C-AFE7-138675498E13
CATEGORIES:
DTSTAMP:20241003T203032Z
DTSTART;TZID="Romance Standard Time":20241007T090000
DTEND;TZID="Romance Standard Time":20241007T103000
LAST-MODIFIED:20241003T203228Z
SUMMARY: OBFUSCATED
DESCRIPTION:OBFUSCATED
LOCATION:https://us02web.zoom.us/j/000000000
 FN0X490.1
ORGANIZER:MAILTO:noname@obfuscated.fr
SEQUENCE:0
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;CN=no.name;PARTSTAT=NEEDS-AC
 TION:MAILTO:no.name@obfuscated.io
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-DISALLOW-COUNTER:TRUE
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-CDO-INSTTYPE:0
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT00H10M00S
END:VALARM
END:VEVENT
END:VCALENDAR
```

### Expected behavior

It should be possible to add the event to my calendar without issue.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "installed": true,
        "maintenance": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.local.tplusone.io",
            "vm-nextcloud.local.tplusone.io"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "overwritehost": "cloud.local.tplusone.io",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.local.tplusone.io",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.7.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "default_phone_region": "FR",
        "theme": "",
        "loglevel": 0,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 20,
        "maintenance_window_start": 1,
        "skeletondirectory": "",
        "defaultapp": "files",
        "allow_user_to_change_display_name": false,
        "auth.bruteforce.protection.enabled": true,
        "trashbin_retention_obligation": "auto, 14",
        "mail_smtpsecure": "ssl",
        "auth.storeCryptedPassword": false,
        "allow_local_remote_servers": true
    }
}

### List of activated Apps

  - calendar: 4.7.16
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - files: 2.1.1
  - files_accesscontrol: 1.19.1
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - notifications: 2.17.0
  - oauth2: 1.17.1
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.7
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharelisting: 1.2.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - activity: 2.21.1 (installed 2.21.1)
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - contacts: 6.0.0 (installed 6.0.0)
  - dashboard: 7.9.0 (installed 7.5.0)
  - encryption: 2.17.0 (installed 2.13.0)
  - federation: 1.19.0 (installed 1.15.0)
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.18.0 (installed 2.14.0)
  - mail: 3.7.8 (installed 3.7.8)
  - nextcloud_announcements: 1.18.0 (installed 1.18.0)
  - password_policy: 1.19.0 (installed 1.15.0)
  - photos: 2.5.0 (installed 2.3.0)
  - sharebymail: 1.19.0 (installed 1.15.0)
  - spreed: 19.0.9 (installed 19.0.9)
  - support: 1.12.0 (installed 1.8.0)
  - survey_client: 1.17.0 (installed 1.13.0)
  - suspicious_login: 7.0.0
  - user_status: 1.9.0 (installed 1.5.0)
  - weather_status: 1.9.0 (installed 1.5.0)

### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs

{"reqId":"XVMHedvrfjE9TAlC6skY","level":3,"time":"2024-10-04T09:59:00+00:00","remoteAddr":"195.154.25.54","user":"alexis.duburcq","app":"webdav","method":"PUT","url":"/remote.php/dav/calendars/alexis.duburcq/personal-1/AB98FED5-B954-4F67-AE74-C153128B9238.ics","message":"This resource only supports valid iCalendar 2.0 data. Parse error: Invalid Mimedir file. Line starting at 24 did not follow iCalendar/vCard conventions","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15","version":"29.0.7.1","exception":{"Exception":"Sabre\\DAV\\Exception\\UnsupportedMediaType","Message":"This resource only supports valid iCalendar 2.0 data. Parse error: Invalid Mimedir file. Line starting at 24 did not follow iCalendar/vCard conventions","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php","line":766,"function":"validateICalendar","class":"Sabre\\CalDAV\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeCreateFile","class":"Sabre\\CalDAV\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1094,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":383,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":172,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php","Line":806,"message":"This resource only supports valid iCalendar 2.0 data. Parse error: Invalid Mimedir file. Line starting at 24 did not follow iCalendar/vCard conventions","exception":[],"CustomMessage":"This resource only supports valid iCalendar 2.0 data. Parse error: Invalid Mimedir file. Line starting at 24 did not follow iCalendar/vCard conventions"},"id":"66ffbc932c6bd"}

**Comment by joshtrichards** [comment] 2024-10-04 16:20
Duplicate of #45574

**Closed by joshtrichards** 2024-10-04 16:20 UTC
Labels: bug, 0. Needs triage, 29-feedback

**Comment by duburcqa** [comment] 2024-10-04 16:45
Sorry for the duplicate. I saw the issue but failed to see it was the same issue before reading the part about "_" issue.
