### ISSUE TITLE
webp thumbnails

### ISSUE THREAD

**Issue by jjisnow** [nextcloud/server#28804] opened 2021-09-11 09:18 UTC
### Is your feature request related to a problem? Please describe.
 I'm always frustrated when trying to view webp images that have been uploaded via InstantUpload, that the nextcloud android app cannot render thumbnails to preview the images without downloading the entire image

### Describe the solution you'd like
fast, scalable creation of thumbnails of selectable sizes in thumbnail view on the nextcloud android app

### Describe alternatives you've considered
thumbnails of any size in the nextcloud android app for webp images

**Comment by AndyScherzinger** [comment] 2021-09-12 16:37
@jjisnow this is a server-side issue since the Android app fetches the previews form the server.

**Comment by szaimen** [comment] 2021-09-12 21:26
duplicate of https://github.com/nextcloud/server/issues/28761

**Closed by szaimen** 2021-09-12 21:26 UTC
Labels: 0. Needs triage
