### ISSUE TITLE
Upload big file consumes all of RAM (WebDAV fail to upload, HTTPS upload very long time)

### ISSUE THREAD

**Issue by ZorgeR** [nextcloud/server#802] opened 2016-08-09 20:31 UTC
### Steps to reproduce
1. Set upload max size to 10GB
2. Set RAM of LXC instance less than 10GB
3. Upload BIG file (more than RAM), via WebDAV - > FAIL
4. Upload BIG file (more than RAM), via https - > Take a looooooong time (go to swap?) but _success uploaded_
### Expected behaviour

Uploading start at blazing fast speed and quickly done.
### Actual behaviour

Uploading start at blazing fast speed, but when all RAM consumes, it go insanely slow on https, and fail on WebDAV.
### Server configuration

**Operating system**: CentOS 7.2 LXC
**Web server**: nginx
**Database**: Maria DB
**PHP version**: 5.5 or 7.0
**Nextcloud version**: 9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install**: Updated
**Where did you install Nextcloud from**: website
**Signing status:**
<details>
<summary>

Signing status</summary>

```
No errors have been found.
```

</details>

**Are you using encryption**: no
### Client configuration

**Browser:** Any

**Operating system:** Any
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 3047809024 got 629211136
Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 4073515008 got 659783680
</details>
```

**Comment by phsc** [comment] 2016-08-10 05:09
Related to the following Owncloud issue: https://github.com/owncloud/core/issues/25181

And as far as I understand, to resolve this issue, the following pull request had to be merged in advance: https://github.com/owncloud/core/pull/21237

**Comment by Spacefish** [comment] 2016-08-10 06:16
I think this depends on the PHP and webserver implementation. Some
webservers might cache the full request in ram before it is passed to
fcgi.. same with proxies or av software..

phsc <notifications@github.com> schrieb am Mi., 10. Aug. 2016, 07:09:

**Comment by derkostka** [comment] 2016-08-18 10:38
I volunteer for testing the WebDav PUT once it is in Nextcloud, as i also suffer from this issue (small ARM device with only 2 GB RAM, WebDav fails for big files). For now i need a big swapfile that slows down the upload speed for LAN devices (won´t be visible on the net, because normally the upload is slow anyways)

**Comment by petre2dor** [comment] 2016-09-23 06:24
This issue affects me too. I volunteer for testing too.

**Comment by joernroeder** [comment] 2016-12-25 10:46
affects me too, volunteering as well.

**Comment by skjnldsv** [comment] 2020-08-20 07:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

I'm using nc19 with php7.4 on very slow mem (4GB) and can upload files of >8GB

**Closed by skjnldsv** 2020-08-20 07:45 UTC
Labels: 0. Needs triage, bug, feature: dav
