### ISSUE TITLE
Upgrade error to 19 RC3

### ISSUE THREAD

**Issue by OsiMood** [nextcloud/server#21067] opened 2020-05-22 10:32 UTC
When upgrading from 19RC2 to RC3 I used the command line and end-up with this message
` Set log level to debug
Updating database schema
Updated database
Disabled incompatible app: breezedark
Disabled incompatible app: impersonate
Disabled incompatible app: keeweb
Cleanup ocr app data folder.

 Starting ...
 0/1 [>---------------------------]   0%An unhandled exception has been thrown:
TypeError: Argument 1 passed to Symfony\Component\Console\Helper\ProgressBar::advance() must be of the type int, string given, called in /var/www/html/nextcloud/core/Command/Upgrade.php on line 144 and defined in /var/www/html/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php:310
Stack trace:
#0 /var/www/html/nextcloud/core/Command/Upgrade.php(144): Symfony\Component\Console\Helper\ProgressBar->advance()
#1 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\Core\Command\Upgrade->OC\Core\Command\{closure}()
#2 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
#3 /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#4 /var/www/html/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#5 /var/www/html/nextcloud/lib/private/Repair.php(201): OC\EventDispatcher\SymfonyAdapter->dispatch()
#6 /var/www/html/nextcloud/lib/private/Repair.php(232): OC\Repair->emit()
#7 /var/www/html/nextcloud/apps/ocr/lib/Migration/CleanupTessdata.php(48): OC\Repair->advance()
#8 /var/www/html/nextcloud/lib/private/Repair.php(103): OCA\Ocr\Migration\CleanupTessdata->run()
#9 /var/www/html/nextcloud/lib/private/legacy/OC_App.php(976): OC\Repair->run()
#10 /var/www/html/nextcloud/lib/private/App/AppManager.php(412): OC_App::executeRepairSteps()
#11 /var/www/html/nextcloud/lib/private/Updater.php(410): OC\App\AppManager->disableApp()
#12 /var/www/html/nextcloud/lib/private/Updater.php(253): OC\Updater->checkAppsRequirements()
#13 /var/www/html/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#14 /var/www/html/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#15 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#16 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#17 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#19 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#20 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#21 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')`

When running the upgrade for a second time, it went through but, when I launch my next cloud, this page is welcoming me:

![image](https://user-images.githubusercontent.com/4088985/82659013-45174800-9c28-11ea-8800-3c1b72756144.png)

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - appointments: 1.4.16
  - apporder: 0.10.0
  - audioplayer: 2.10.0
  - bookmarks: 3.0.13
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - groupfolders: 6.0.6
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - maps: 0.1.6
  - nextcloud_announcements: 1.8.0
  - notes: 3.3.1
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - passman: 2.3.5
  - password_policy: 1.9.1
  - phonetrack: 0.6.3
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - radio: 0.6.6
  - recommendations: 0.7.0
  - richdocuments: 3.6.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - side_menu: 1.7.0
  - spreed: 9.0.0-rc.1
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - unsplash: 1.1.5
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - breezedark
  - event_update_notification
  - firstrunwizard
  - flowupload
  - impersonate
  - keeweb
  - occweb
  - ocr
  - user_ldap

**Comment by jecal22** [comment] 2020-06-05 04:12
I have been working on upgrading my environment this evening from 18.0.4 to the new 19.0.0 release.

I ran into the exact error described by OsiMood.  

After the first failed attempt, I rolled my ZFS snapshots back and performed the upgrade to 18.0.5 thinking maybe a subsequent update to 19.0.0 would succeed.  I had no issues updating to 18.0.5, however, got the same error again when attempting upgrade to 19.0.0 again.

As described by OsiMood, re-running the upgrade seems to complete with no further errors, but having issues after the upgrade.  In my case, I use SSO SAML with Microsoft Azure AD.  After upgrading and logging in via SSO, I am just getting redirected to the saml page in nextcloud that displays the text "null".  Disabled the user_saml app and was able to login with username/password, but not sure why the user_saml app broke.

I rolled back to 18.0.5 again and tried the upgrade once more, but same errors.  I'm sticking with 18.0.5 for now until there are any updates with this issue.

I'm happy to provide any information that will be helpful for identifying the problem.

**Comment by Bubu** [comment] 2020-06-05 14:36
Had the same crash when updating to 19 final through archlinux package. subsequent incovation of occ upgrade worked and everything seems working normally now.

**Comment by jecal22** [comment] 2020-06-05 23:06
So I tried again and removed the OCR app prior to upgrading. I had no errors, however the SAML integration still broke. Seems to be some issues with the individual apps and likely not the core Nextcloud software.

**Comment by kesselb** [comment] 2020-10-08 17:15
> /var/www/html/nextcloud/apps/ocr/lib/Migration/CleanupTessdata.php(48): OC\Repair->advance()

Closing in favour of https://github.com/janis91/ocr/issues/281. The issue is caused by OCR app calling a function the wrong way.

**Closed by kesselb** 2020-10-08 17:15 UTC
Labels: 0. Needs triage, bug
