### ISSUE TITLE
[12.0.3RC2] Avatars in Activities tab are rendered kaput

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#6526] opened 2017-09-15 15:04 UTC
![spectacle c29893](https://user-images.githubusercontent.com/2184312/30489535-bcce33ea-9a37-11e7-8f55-16ca5766cafe.png)

In the image source, the username is missing, e.g. ``/avatar//69`` is shown instead of ``/avatar/johndoe/69``

**Comment by MorrisJobke** [comment] 2017-09-19 12:06
Let's move this over to 12.0.4

**Comment by blizzz** [comment] 2017-09-19 13:26
Saw it also working again today on our instance.

**Comment by MorrisJobke** [comment] 2017-09-19 15:10
Let's close it for now, because I can't reproduce here.

**Closed by MorrisJobke** 2017-09-19 15:10 UTC
Labels: bug, feature: activity and notification, regression
