### ISSUE TITLE
Nextcloud / direct_menu

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#5405] opened 2017-06-14 10:45 UTC
Tell us what should happen
no possible to configuring the menu, to less icons on menu
or enough space into the menu..

icon-configuration should possible, 
arrange in a particular order of icons, 
and all icons of only one icon and single menu.. or both like it was before include
direct_menu .. and by the way, to make possible how big the icons in menu be..

so a possible to fully configuration behave of menu icons and the size
in the control menu of the user.

### Actual behaviour
4-6 icons and the rest make as pull-down
not configurable .

### Server configuration

Apache/2.4.25 (OpenMandriva Lx/PREFORK-1) OpenSSL/1.0.2k PHP/7.0.17 mod_perl/2.0.9dev Perl/v5.20.3 
**Nextcloud version:** (see Nextcloud admin page)
last official version 12

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated/fresh install both

**Where did you install Nextcloud from:**
offiziall

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

best regards
Blacky

**Comment by juliushaertl** [comment] 2017-06-14 11:30
This is a duplicate of https://github.com/nextcloud/server/pull/5135 and https://github.com/nextcloud/server/issues/4917.

**Closed by juliushaertl** 2017-06-14 11:30 UTC
