### ISSUE TITLE
Open files directly from "search result in another folder" instead of using scrollto=

### ISSUE THREAD

**Issue by raicool** [nextcloud/server#7874] opened 2018-01-15 22:54 UTC
When trying to open a file located in a folder with thousands of files Nextcloud hangs for several minutes on all browsers. Using Nextant helps but is being decommissioned and I don't have any need for searching the contents of the files.

System has plenty of resources available and I have done many MariaDB enhancements but I believe the issue is occurring because of "scrollto" function having to page down to the file before displaying the appropriate file instead of a database problem, as the further down the filelist the file is, the longer it takes to load.

**Comment by MorrisJobke** [comment] 2018-01-30 14:33
cc @nextcloud/designers

**Comment by cyril2018** [comment] 2019-03-05 11:05
any updates on this when it will and if it will be implemented?

**Comment by skjnldsv** [comment] 2019-03-06 07:08
This will be fixed by #9917

**Comment by 0x41mmarVM** [comment] 2019-10-02 15:25
Can anyone recommend any hack to get around this in the mean time?
I'm dealing with a case where a folder must have 8000 files, and waiting for all of them to be loaded is difficult.

**Comment by skjnldsv** [comment] 2020-08-20 13:24
Fixed nc20

**Closed by skjnldsv** 2020-08-20 13:24 UTC
Labels: 1. to develop, bug, design, enhancement, feature: search

**Comment by CSchmidtDD** [comment] 2021-05-12 12:02
@skjnldsv how is this exactly fixed with nc20, can you elaborate?
Currently using nc20 and it does not open the file from the search function directly.

We do have a similar usecase to the one @0x41mmarVM described, so any info is appreciated.

**Comment by germainm** [comment] 2022-07-20 23:03
@skjnldsv the issue is still not solved in the latest nextcloud

normal search open automatically the file (pdf for me)  BUT a background scrollto is used (can see in the URL) and sometimes I can't scroll the document (pdf in my case) until it ends. Need to wait the background scrollto to end. Another symptom is that I can't close the document if the scrollto is not done processing

elastic search still don't automatically open the file. it opens the directory and use scrollto to show the file.

so, a feacture to disable scrollto would be greatly appreciated ( or optimization is really needed 5-10x speed would be probably OK for 5000 files directory )

It's really annoying and hang browser and there's nothing about unoptimized server (my vm has 32 gb, I setup redis, increased elastic memory, given more memory to php process)

**Comment by brendan-pike** [comment] 2022-07-29 04:37
For some context 99% of the time we just want to download a file from search but can't any longer and are forced to edit the file to then figure out where it is so we can download it.  Very poor.

**Comment by jonas556440** [comment] 2024-01-06 12:52
I have the latest version, and the same problem here, in the search it does not select or open the file

**Comment by joshtrichards** [comment] 2024-01-07 02:07
Folks - You're posting on an Issue that has been closed for several years. If you're seeing something in current versions it's perhaps a different issue so I suggest opening a dedicated issue for it. No one sees these when they're closed other than by accident (like I just did).
