### ISSUE TITLE
external storages can not be moved

### ISSUE THREAD

**Issue by cuthulino** [nextcloud/server#3717] opened 2017-03-05 15:32 UTC
Hello,

Running ver. 11.0.2 on Ubuntu 16.04.
I added External storages via SFTP.
Works great. Thanks for that.

But i can not move the displayed external-share-folder.
An error gets displayed "can not move xyz".

I can reproduce the error with all Users, no matter if admin or user or sth else.

Other files can be moved without problems.
Adminlog does not show anything related!?

German error message in the atachment.

![grafik](https://cloud.githubusercontent.com/assets/4634522/23588644/d724dbf0-01c0-11e7-89b0-9b1b8100dbf2.png)

**Comment by nickvergessen** [comment] 2017-03-06 12:08
External storage mount points can not be moved currently, that's correct and intended.
@icewind1991 we shouldn't change this, should we?

**Comment by icewind1991** [comment] 2017-03-06 14:36
Is the external storage configured by an admin or user?

**Comment by cuthulino** [comment] 2017-03-13 20:12
its done by an admin.
but admin cant move them too.

Maybe this makes my problem a bit more clear:
I got an external server (owned by a friend) named "elvis".
I mount different folders (music, videos, etc.).
I want them all in one cloud-folder like this:
elvis (folder)
  |-- music (mount)
  |-- videos (mount)
  |-- etc. (mount)

without the abillity to move them,
i only have some folders in the mainscreen of my files app.

**Comment by icewind1991** [comment] 2017-03-15 14:42
you can set `elvis/music` as a mountpoint when configuring the store.

Not being able to move admin configured shares from the files ui is expected behaviour -> closing

**Closed by icewind1991** 2017-03-15 14:42 UTC
Labels: feature: external storage, help wanted
