### ISSUE TITLE
NC 12.0.1RC1 table bruteforce_attempts no longer records userid as metadata

### ISSUE THREAD

**Issue by umgfoin** [nextcloud/server#5891] opened 2017-07-26 15:16 UTC
### Steps to reproduce
1. Provocate login failures
2. login to nc_database
3. select * from oc_bruteforce_attempts;

### Expected behaviour
column metadata shows userid of failed login-attempt

 id | action |  occurred  |             ip             |             subnet             |          metadata
----+--------+------------+----------------------------+--------------------------------+----------------------------
 24 | login  | 1491998075 | 111.222.333.444              | 111.222.333.444/32               | {"user":"bepperl"}
 25 | login  | 1492621114 | 111.222.333.444              | 111.222.333.444/32               | {"user":"giagl"}
 26 | login  | 1492621216 | 111.222.333.444              | 111.222.333.444/32               | {"user":"philomenal"}

### Actual behaviour
login-info is omitted in column metadata
 
id | action |  occurred  |             ip             |             subnet             |          metadata
----+--------+------------+----------------------------+--------------------------------+----------------------------
 24 | login  | 1491998075 | 111.222.333.444              | 111.222.333.444/32               | []
 25 | login  | 1492621114 | 111.222.333.444              | 111.222.333.444/32               | []
 26 | login  | 1492621216 | 111.222.333.444              | 111.222.333.444/32               | []

### Server configuration
**Operating system**: Linux FQDN 2.6.32-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64

**Web server:** nginx/1.11.10 (fpm-fcgi)
                                 
**Database:** pgsql PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18), 64-bit

**PHP version:** 7.1.7

**Nextcloud version:** 12.0.1 RC1 - 12.0.1.0

**Where did you install Nextcloud from:** 
download.nextcloud.com/server/prerelease

**Comment by MorrisJobke** [comment] 2017-07-27 05:51
cc @LukasReschke

**Comment by LukasReschke** [comment] 2017-07-27 11:49
Can reproduce. Let me see what broke this.

**Comment by LukasReschke** [comment] 2017-07-27 12:10
This is already broken since 12.0.0 and thus I'm moving this to 13.0 since the function isn't advertised as a feature in the UI or so. (and has been solely added for future purposes such as potential filtering)

**Comment by umgfoin** [comment] 2017-07-27 12:14
> This is already broken since 12.0.0

Not exactly, here it appeared with upgrade from 12.0.0 to 12.0.1 RC1.

**Comment by LukasReschke** [comment] 2017-07-27 12:18
@umgfoin Metadata for logins via the web login are also not tracked with Nextcloud 12.0.0, but they are for logins via DAV etc.

**Closed** 2017-08-01 12:43 UTC
Labels: bug
