### ISSUE TITLE
secure-drop: Link sent to email address does not work.

### ISSUE THREAD

**Issue by himbeere** [nextcloud/server#4677] opened 2017-05-03 14:56 UTC
Nextcloud 12.0 beta1

Hello Devs.

I just tried the secure-drop feature. First observation is:

1. Link shown in nextcloud interface works.
2. Link sent to email address does not work.

The attached screen shows how it looks:

![bildschirmfoto 2017-05-03 um 16 53 40](https://cloud.githubusercontent.com/assets/631865/25666541/1a6abaf4-3021-11e7-91b3-8a3b8a6c2178.png)

So the emailed user is not able to upload anything.

Using the link shown in nextcloud everything works as expected.

**Comment by MorrisJobke** [comment] 2017-05-03 15:22
@himbeere Could you post those two links? (it's fine to remove the domain part and maybe also just remove the link from your instance by unsharing to be super-save)

**Comment by michag86** [comment] 2017-05-03 17:48
@MorrisJobke Link share for email only works for files at the moment. Folders are always shown as empty. It makes no difference if you select "can edit" or "secure drop". 

Every upload attempt results in:
`<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Username or password was incorrect</s:message>
</d:error>
`

**Comment by MorrisJobke** [comment] 2017-05-03 19:20
cc @schiessle @icewind1991 @rullzer

**Comment by himbeere** [comment] 2017-05-04 06:39
Is the information from @MorrisJobke sufficiant or do you need more debug info from me?

**Comment by schiessle** [comment] 2017-05-04 08:17
I just tried it with the Nextcloud 12 beta1 but can't reproduce it. Do you see any additional error messages in your nextcloud.log? What did you do exactly?

I tried following:

1. setup a fresh Nextcloud 12 beta 1
2. configured my mail server, I didn't changed any other setting 
3. share a folder by entering a email address in the share dialog
4. go to my mails and open the link -> folder is shown just fine and I can upload new files
5. go back to my Nextcloud and check "Secure drop (upload only)"
6. access the public link from my emails again -> file listing is hidden and upload using the "select or drop a file button" worked.

(I did the upload both times with the file picker, no drag&drop)

Did you do the same? Something different?

**Comment by schiessle** [comment] 2017-05-04 08:21
I think I could reproduce it, you also set a password for the mail share, right?

I will look into it...

**Comment by himbeere** [comment] 2017-05-04 08:27
No. I did not set a password.

![bildschirmfoto 2017-05-04 um 10 24 43](https://cloud.githubusercontent.com/assets/631865/25695562/f131a68c-30b3-11e7-8d42-eb4b21752f66.png)

Nothing in the logs either.  When i use the link in the screenshot everything works. When using the link from the mail it does not.  This is the link from the mail.

https://nextcloud.dev.lordcritical.de/index.php/s/dpa5hbrdWnZws58

(i will remove the link in one hour from now.)

**Comment by rullzer** [comment] 2017-05-04 08:36
@himbeere aaaah! I see. Click the three dots next to Can edit.

The link share is a personalized link. I guess this means the UX is not ideal. @nextcloud/designers any suggestion?

**Comment by rullzer** [comment] 2017-05-04 08:38
I guess it would make sense to have link shares in that list as well. Then we can also more easily have multiple. We can name them. And since normal shares have most of the functionality of link shares anyways.

**Comment by schiessle** [comment] 2017-05-04 08:39
@himbeere I tried your link. I could upload a file and after reload I still saw the file. So upload and showing the file listing seems to work

**Comment by himbeere** [comment] 2017-05-04 08:46
Ahhh! I see too. :-) I have to click secure drop twice.

**Comment by schiessle** [comment] 2017-05-04 09:23
The problem in case of a password is fixed here: https://github.com/nextcloud/server/pull/4689

@himbeere so what's the status from your side? Is it still a issue or do you consider it solved?

**Comment by himbeere** [comment] 2017-05-04 09:24
It's solved. Thanks.

**Comment by michag86** [comment] 2017-05-04 09:25
@schiessle @rullzer 
Why is this closed? The problem occurs if there is a password for mail share set.

**Comment by schiessle** [comment] 2017-05-04 09:28
@michag86 This case should be fixed here: https://github.com/nextcloud/server/pull/4689
But I agree, let's close it once the PR is merged. Feel free to test the PR and report back. (In order to test it you just need to adjust this one line https://github.com/nextcloud/server/pull/4689/files#diff-b1bd1f055af08fe99fe362657f0664bdR99 (ignore all the tests))

**Comment by michag86** [comment] 2017-05-04 09:28
I overlooked your comment, sorry :wink:

**Closed** 2017-05-04 09:28 UTC
