### ISSUE TITLE
Share keys not being recreated when updating shared file

### ISSUE THREAD

**Issue by brdubson** [nextcloud/server#11051] opened 2018-09-04 15:48 UTC
### Steps to reproduce
1. Add file to your root directory
2. Share file with other users
3. When looking in the files_encryption/keys/files/<file>/ directory at this point, owner's sharekey and other user's sharekeys are here and they can open file.
4. Change and update file
5.  When looking in the files_encryption/keys/files/<file>/ directory at this point, owner's sharekey is there, but all others have been deleted
6. Other user's cannot open file due to encryption error unless owner re-shares the file after every update.

### Expected behaviour
Tell us what should happen
Other user's sharekeys should be re-created after file is upated
### Actual behaviour
Tell us what happens instead
Only the owner's sharekey gets re-created
### Server configuration

**Operating system**:
RedHat Enterprise Linux 7.5
**Web server:**
Apache 2.4
**Database:**
PostgreSQL 9.2
**PHP version:**
PHP 7.1.8
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.01
**Updated from an older Nextcloud/ownCloud or fresh install:**
Same environment/files through the following upgrades
ownCloud 8.0.6
ownCloud 8.0.13
ownCloud 8.0.16
ownCloud 8.1.11
ownCloud 8.2.10
Nextcloud 9.0.57
Nextcloud 10.0.6
Nextcloud 11.0.8
Nextcloud 12.0.6
Nextcloud 13.0.1
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-13.0.1.tar.bz2
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.1.0
  - comments: 1.3.0
  - dav: 1.4.6
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'datadirectory' => '/mnt/extdata/nextcloud',
  'theme' => '',
  'dbtype' => 'pgsql',
  'version' => '13.0.1.1',
  'dbname' => 'nextcloud',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapUserCleanupInterval' => 10,
  'trashbin_retention_obligation' => '20, auto',
  'session_lifetime' => 3600,
  'log_type' => 'owncloud',
  'logfile' => '/mnt/extdata/nextcloud/nextcloud.log',
  'logtimezone' => 'America/New_York',
  'log_rotate_size' => '104857600',
  'loglevel' => 3,
  'logdateformat' => 'F d, Y H:i:s',
  'forcessl' => true,
  'maintenance' => false,
  'updatechecker' => false,
  'trusted_domains' =>
  array (
    0 => 'owncloud.coastal.edu',
    1 => 'nextcloud.coastal.edu',
  ),
  'secret' => '8b487901a6e57a0c223cd87ecc430cfef4d29a9b7b70eaf543fb4700984a64d8d4c4b58578b9096fd1dc0842aff4d070',
  'share_folder' => '/Shared',
  'default_language' => 'en',
  'knowledgebaseenabled' => true,
  'enable_avatars' => true,
  'enable_previews' => true,
  'singleuser' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'overwrite.cli.url' => 'https://owncloud.coastal.edu',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'data-fingerprint' => '9e3f6c4f29d33a717bb569f7b267ff5c',
);
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                       |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                     |
| hasPagedResultSupport         |                                                                                                                       |
| homeFolderNamingRule          |                                                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                                                     |
| ldapAgentName                 | cn=***,ou=***,dc=coastal,dc=edu                                                                                      |
| ldapAgentPassword             | ***                                                                                                                   |
| ldapAttributesForGroupSearch  | cn                                                                                                                    |
| ldapAttributesForUserSearch   | displayName;cn;loginName;mail                                                                                         |
| ldapBackupHost                |                                                                                                                       |
| ldapBackupPort                | 389                                                                                                                   |
| ldapBase                      | dc=***,dc=***                                                                                                     |
| ldapBaseGroups                | ou=***,dc=***,dc=***                                                                                           |
| ldapBaseUsers                 | DC=***,DC=***                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                   |
| ldapConfigurationActive       | 1                                                                                                                     |
| ldapDefaultPPolicyDN          |                                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                                                                       |
| ldapExpertUUIDUserAttr        |                                                                                                                       |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                        |
| ldapGidNumber                 | gidNumber                                                                                                             |
| ldapGroupDisplayName          | cn                                                                                                                    |
| ldapGroupFilter               | (&(objectClass=group)(memberOf=CN=***,OU=***,DC=***,DC=***))                                              |
| ldapGroupFilterGroups         |                                                                                                                       |
| ldapGroupFilterMode           | 1                                                                                                                     |
| ldapGroupFilterObjectclass    |                                                                                                                       |
| ldapGroupMemberAssocAttr      | member                                                                                                                |
| ldapHost                      | ldaps://***                                                                                              |
| ldapIgnoreNamingRules         |                                                                                                                       |
| ldapLoginFilter               | (&(|(mail=%uid)(sAMAccountName=%uid)(cn=%uid))(objectClass=person)(memberOf=CN=***,OU=***,DC=***,DC=***)) |
| ldapLoginFilterAttributes     |                                                                                                                       |
| ldapLoginFilterEmail          | 0                                                                                                                     |
| ldapLoginFilterMode           | 1                                                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                                                     |
| ldapNestedGroups              | 0                                                                                                                     |
| ldapOverrideMainServer        | 0                                                                                                                     |
| ldapPagingSize                | 500                                                                                                                   |
| ldapPort                      | 636                                                                                                                   |
| ldapQuotaAttribute            | ccuOwnCloudQuota                                                                                                      |
| ldapQuotaDefault              | 1 B                                                                                                                   |
| ldapTLS                       |                                                                                                                       |
| ldapUserDisplayName           | displayname                                                                                                           |
| ldapUserDisplayName2          |                                                                                                                       |
| ldapUserFilter                | (&(objectClass=person)(memberOf=CN=***,OU=***,DC=***,DC=***))                                             |
| ldapUserFilterGroups          |                                                                                                                       |
| ldapUserFilterMode            | 1                                                                                                                     |
| ldapUserFilterObjectclass     |                                                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                                                  |
| turnOffCertCheck              | 0                                                                                                                     |
| turnOnPasswordChange          | 0                                                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                                                     |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:**
Chromium Version 68.0.3440.106 (Official Build) Arch Linux (64-bit)
**Operating system:**
Arch Linux
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"W4kwNhmKLbAjIikFGlxwFQAAAAg","level":3,"time":"August 31, 2018 08:10:30","remoteAddr":"192.168.130.162","user":"76D5DDD3-66F8-4065-9A9A-63A31591A39F","app":"no app in context","method":"GET","url":"\/remote.php\/dav\/files\/76D5DDD3-66F8-4065-9A9A-63A31591A39F\/Shared\/test.txt","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.1.1"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by J0WI** [comment] 2020-03-24 18:37
I was not able to reproduce this, but I found #20146

**Comment by szaimen** [comment] 2021-05-31 11:21
As J0WI wasn't able to reproduce this, I am closing this issue. 
If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 11:21 UTC
Labels: 0. Needs triage, bug, feature: encryption (server-side), feature: sharing
