### ISSUE TITLE
Select All not limited to search results

### ISSUE THREAD

**Issue by stevenhorner** [nextcloud/server#5769] opened 2017-07-18 10:39 UTC
### Steps to reproduce
1. filter files list by typing in search box
2. press Select all check box and it selects every file in folder not just those that are filtered

### Expected behaviour
When you press the select all button I would expect it to select all the files that were returned from the search results. 

### Actual behaviour
It selects every file in the current folder including those that do not match your current search, which almost in my case led to me deleting a large number of files that I did not intend to.

### Server configuration

**Operating system**: Ubuntu Server 16.04

**Web server:** Apache 2

**Database:** MySQL 10.0.29

**PHP version:** 7.0.18

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud or fresh install:** Installed fresh but did manually copy pictures over and re-index

**Where did you install Nextcloud from: latest download from website

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>GPXEdit, GPXPod, Calendar</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one: No

**Comment by MorrisJobke** [comment] 2017-08-31 11:41
Duplicate of #6162

**Comment by MorrisJobke** [comment] 2017-08-31 11:41
Closing because the other ticket has nicer screenshots ;)

**Closed by MorrisJobke** 2017-08-31 11:41 UTC
Labels: bug, feature: files, papercut, starter issue
