### ISSUE TITLE
[Bug]: Nextcloud 29 - limit downloads need one for view (e.g. pdfviewer) and one for download

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#45023] opened 2024-04-25 05:49 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Nextcloud 29 there is a new nice function "limit downloads". The problem is the fact that with showing the file e.g. PDF the counter is decrease and then the downloads is set from "1" to "0" and then i can not download the file with the download button. 

**problem with viewer:** e.g. PDF
**no problem with viewer:** Markdown e.g. CSV-file, picture e.g. JPG

I think the pdfviewer uses the download link. Maybe there are other viewers, too.
```
https://cloud.server.tld/index.php/apps/files_pdfviewer/?file=%2Findex.php%2Fs%2Fiy83XfXHj9PpcbJ%2Fdownload%3Fpath%3D%26files%3D&canDownload=1
[...]
https://cloud.server.tld/index.php/s/iy83XfXHj9PpcbJ/download?path=&files=
```

### Steps to reproduce

1. install Nextcloud 29
2. share a file e.g. PDF with "limit downloads" to "1"
3. open the share
4. the pdf is viewed, limit goes to "0", no share anymore
5. the download button on the top does not work

### Expected behavior

If i set "download limit" to "1" i expected that a user (e.g. cookie user) can see the file e.g. PDF and also download the file with the download button on the top.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Other

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Same problem on two systems, installation on webserver from a hoster.

**Comment by lhsei** [comment] 2024-04-25 08:25
We have also problems with the pdfviewer after upgrade to Nextcloud 29.

If a folder/file is shared with other users and the users have only view-rights, the pdf doesn't open. In the log, the following error occurs:

`TypeError: Cannot assign null to property OCA\Files_Sharing\Controller\ShareAPIController::$currentUser of type string at /var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php#124 `

**Comment by skjnldsv** [comment] 2024-05-24 12:05
Pretty sure we have an issue about this already.
There is currently no way to differentiate a download from a view, they are the same thing.

**Comment by skjnldsv** [comment] 2024-05-24 12:06
duplicate of https://github.com/nextcloud/server/issues/41686

**Closed by skjnldsv** 2024-05-24 12:06 UTC
Labels: bug, 0. Needs triage, 29-feedback
