### ISSUE TITLE
BadMethodCallException on FTP external storage

### ISSUE THREAD

**Issue by amo13** [nextcloud/server#19296] opened 2020-02-04 14:44 UTC
### Steps to reproduce
Happened when I tried to download (using the dots and clicking on download) a Cover.jpg image from a FTP external share

### Expected behaviour
preview and/or download the image

### Actual behaviour
 I get redirected to a blank page only showing an internal server error. Just clicking on the image file presents a preview view saying "Error loading Cover.jpg".

## Server configuration detail

**Operating system:** Linux 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.4.10

**PHP version:** 

7.3.12
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, Phar, curl, exif, ftp, gd, gmp, iconv, intl, mysqli, pdo_mysql, pdo_sqlite, sqlite3, xmlrpc, zip, igbinary, imagick, redis, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 17.0.3 - 17.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated all the way from owncloud times

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - bookmarks: 2.3.4
 - calendar: 2.0.1
 - camerarawpreviews: 0.7.3
 - carnet: 0.19.2
 - checksum: 0.4.4
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.8
 - dav: 1.13.0
 - deck: 0.8.0
 - drawio: 0.9.4
 - extract: 1.2.3
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_linkeditor: 1.0.11
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.6.0
 - files_readmemd: 1.1.3
 - files_retention: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - gallery: 18.4.0
 - impersonate: 1.4.0
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 1.1.2
 - maps: 0.1.4
 - metadata: 0.11.1
 - music: 0.12.1
 - news: 14.1.2
 - nextcloud_announcements: 1.6.0
 - notes: 3.1.2
 - oauth2: 1.5.0
 - ocdownloader: 1.7.5
 - password_policy: 1.7.0
 - passwords: 2020.2.0
 - phonetrack: 0.6.1
 - polls: 1.1.6
 - previewgenerator: 2.2.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - ransomware_protection: 1.5.1
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - sharerenamer: 2.7.3
 - socialsharing_email: 1.0.6
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_admin: 2.0.0
 - twofactor_backupcodes: 1.6.0
 - twofactor_gateway: 0.15.1
 - twofactor_nextcloud_notification: 2.2.0
 - twofactor_totp: 4.1.2
 - updatenotification: 1.7.0
 - video_converter: 0.1.3
 - viewer: 1.2.0
 - workflow_script: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - firstrunwizard
 - notifications
 - ocsms
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       "***REMOVED SENSITIVE VALUE***",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "dbtype": "mysql",
    "version": "17.0.3.1",
    "logtimezone": "UTC",
    "installed": true,
    "theme": "",
    "loglevel": 0,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** local/ftp

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

**Operating system:** archlinux

## Logs

<details><summary>Web server error log</summary>

```
did not find anything suspicious
```
</details>

<details><summary>Nextcloud log</summary>

```
[index] Error: BadMethodCallException:  at <<closure>>

 0. /usr/share/webapps/nextcloud/apps/files_external/3rdparty/icewind/streams/src/RetryWrapper.php line 27
    Icewind\Streams\Wrapper::wrapSource(false, null, "retry", "\\Icewind\\Streams\\RetryWrapper")
 1. /usr/share/webapps/nextcloud/apps/files_external/lib/Lib/Storage/FTP.php line 114
    Icewind\Streams\RetryWrapper::wrap(false)
 2. /usr/share/webapps/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 299
    OCA\Files_External\Lib\Storage\FTP->fopen("my & folder... 3", "r")
 3. /usr/share/webapps/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php line 311
    OC\Files\Storage\Wrapper\Wrapper->fopen("my & folder... 3", "r")
 4. /usr/share/webapps/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 299
    OC\Files\Storage\Wrapper\Availability->fopen("my & folder... 3", "r")
 5. /usr/share/webapps/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php line 122
    OC\Files\Storage\Wrapper\Wrapper->fopen("my & folder... 3", "r")
 6. /usr/share/webapps/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 299
    OC\Files\Storage\Wrapper\PermissionsMask->fopen("my & folder... 3", "r")
 7. /usr/share/webapps/nextcloud/apps/ransomware_protection/lib/StorageWrapper.php line 317
    OC\Files\Storage\Wrapper\Wrapper->fopen("my & folder... 3", "r")
 8. /usr/share/webapps/nextcloud/lib/private/Files/View.php line 1158
    OCA\RansomwareProtection\StorageWrapper->fopen("my & folder... 3", "r")
 9. /usr/share/webapps/nextcloud/lib/private/Files/View.php line 994
    OC\Files\View->basicOperation("fopen", "/amo/files/smth ... 3", ["read"], "r")
10. /usr/share/webapps/nextcloud/lib/private/Files/Node/File.php line 108
    OC\Files\View->fopen("/amo/files/smth ... 3", "r")
11. /usr/share/webapps/nextcloud/lib/private/Preview/ProviderV2.php line 81
    OC\Files\Node\File->fopen("r")
12. /usr/share/webapps/nextcloud/lib/private/Preview/MP3.php line 48
    OC\Preview\ProviderV2->getLocalFile(OC\Files\Node\File {})
13. /usr/share/webapps/nextcloud/lib/private/Preview/GeneratorHelper.php line 59
    OC\Preview\MP3->getThumbnail(OC\Files\Node\File {}, 4096, 4096)
14. /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php line 204
    OC\Preview\GeneratorHelper->getThumbnail(OC\Preview\MP3 {}, OC\Files\Node\File {}, 4096, 4096)
15. /usr/share/webapps/nextcloud/lib/private/Preview/Generator.php line 126
    OC\Preview\Generator->getMaxPreview(OC\Files\SimpleFS\SimpleFolder {}, OC\Files\Node\File {}, "audio/mpeg", "")
16. /usr/share/webapps/nextcloud/lib/private/PreviewManager.php line 210
    OC\Preview\Generator->getPreview(OC\Files\Node\File {}, 250, 250, true, "fill", "audio/mpeg")
17. /usr/share/webapps/nextcloud/core/Controller/PreviewController.php line 170
    OC\PreviewManager->getPreview(OC\Files\Node\File {}, 250, 250, true, "fill")
18. /usr/share/webapps/nextcloud/core/Controller/PreviewController.php line 142
    OC\Core\Controller\PreviewController->fetchPreview(OC\Files\Node\File {}, 250, 250, false, false, "fill")
19. /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OC\Core\Controller\PreviewController->getPreviewByFileId(9311563, 250, 250, false, false, "fill")
20. /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controller\PreviewController {}, "getPreviewByFileId")
21. /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\PreviewController {}, "getPreviewByFileId")
22. /usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Controller\\PreviewController", "getPreviewByFileId", OC\AppFramework\ ... {}, {_route: "core.P ... "})
23. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.P ... "})
24. /usr/share/webapps/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "core.P ... "})
25. /usr/share/webapps/nextcloud/lib/base.php line 997
    OC\Route\Router->match("/core/preview")
26. /usr/share/webapps/nextcloud/index.php line 42
    OC::handleRequest()

GET /core/preview?fileId=9311563&c=5cd45d276b35a&x=250&y=250&forceIcon=0
from 87.142.111.71 by amo at 2020-02-04T14:24:37+00:00
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by amo13** [comment] 2020-02-04 15:23
Looks like I tried to fetch stuff that was not there any more on the FTP server. This explains the unexpected behavior.

I suggest to catch this type of exception and to rescan the FTP tree. Why aren't the files and folders on the FTP server not rescanned anyway, since my settings say "check for changes: once every direct access"? The FTP external storage definitely is showing to me directories and files that are not on the server any more (as checked with filezilla).

**Comment by szaimen** [comment] 2021-05-28 12:06
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-28 12:06 UTC
Labels: 0. Needs triage, bug
