### ISSUE TITLE
Share calender with user group with umlaut fails

### ISSUE THREAD

**Issue by tagru** [nextcloud/server#19609] opened 2020-02-23 15:03 UTC
### Steps to reproduce
1. Create user group with umlaut e.g. testgröp
2.Try to share calendar with this group
3. Looks succesful, but after reload of page the share is not saved and no user of the group sees the calendar

### Expected behaviour
Share calendar with group. All group members should see calendar.

### Actual behaviour
Share calendar with group is not saved. After reopening calendar in browser, the share is not visible. No group member sees the share

## Server configuration detail

**Operating system:** Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.4.12

**PHP version:** 

7.3.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** docker image `nextcloud:latest`

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - polls: 1.3.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - sharerenamer: 2.7.3
 - spreed: 8.0.4
 - support: 1.1.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - firstrunwizard
 - metadata
 - photos
 - survey_client
 - theming
 - user_ldap

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** 
Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
Googe Chrome  80.0.3987.116 

**Operating system:** Manjaro Linux Gnome 18.1.5

**Comment by tagru** [comment] 2020-02-23 15:03
Maybe related to old issue [#544](https://github.com/nextcloud/calendar/issues/544)

**Comment by kesselb** [comment] 2020-02-23 15:06
Please always use the search before reporting a issue: https://github.com/nextcloud/server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+calendar+umlaut

Duplicate of https://github.com/nextcloud/server/issues/17610

**Closed by kesselb** 2020-02-23 15:06 UTC
Labels: 0. Needs triage, bug

**Comment by tagru** [comment] 2020-02-23 15:53
Sorry, i thought I did. Turns out I searched in the calender repo, not in the server repo :see_no_evil:

**Comment by kesselb** [comment] 2020-02-23 16:03
All right. We should probably add some hints how to search on GitHub. If you use the search box (top left) at https://github.com/nextcloud it will search the whole organization (all repositories).
