### ISSUE TITLE
Link sharing via photo viewer broken

### ISSUE THREAD

**Issue by jtackaberry** [nextcloud/server#5839] opened 2017-07-22 18:01 UTC
### Steps to reproduce
1. Click a photo to view it.
2. Click the share button in the top right corner of the photo viewer.
3. Click share link
4. The result link looks like $SERVERNAME/apps/undefined/s/[....] and it doesn't work.

Meanwhile, going back to the file list (closing the photo viewer), the link there shows $SERVERNAME/s/[...] which works.  So the photo viewer is incorrectly inserting /apps/undefined in the link.

### Server configuration

**Operating system**: Ubuntu 16.04.2

**Web server:** nginx 1.10.3

**Database:** MySQL 14.14 Distrib 5.7.19

**PHP version:** 7.0.18-0ubuntu0.16.04.1

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Official tarball

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oc2xm85bgc3v",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

</details>

**Are you using external storage, if yes which one:** N/A (local storage)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Firefox 54 or Chrome 58

**Operating system:** Windows 10 x64

**Comment by enoch85** [comment] 2017-07-22 18:56
cc @oparoz

**Comment by MorrisJobke** [comment] 2017-07-26 06:57
Duplicate of nextcloud/gallery#268

**Closed by MorrisJobke** 2017-07-26 06:57 UTC
