### ISSUE TITLE
Upgrade 17.x to 18.0.10 = KO

### ISSUE THREAD

**Issue by nimeops** [nextcloud/server#23331] opened 2020-10-10 08:04 UTC
Hi,
Upgrade 17.x to 18.0.10 = KO

Error:
`InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.`

**Comment by nimeops** [comment] 2020-10-10 08:07
running php occ maintenance:repair

In AbstractMySQLDriver.php line 42:

  An exception occurred while executing 'SELECT `o`.`id` FROM `oc_flow_operations` `o` LEFT JOIN `oc_flow_operations_scope` `s` ON `o`.`id` = `s`.`operation_id
  ` WHERE `s`.`operation_id` IS NULL':

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_flow_operations_scope' doesn't exist


In PDOConnection.php line 90:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_flow_operations_scope' doesn't exist


In PDOConnection.php line 88:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_flow_operations_scope' doesn't exist


maintenance:repair [--include-expensive]

**Comment by nimeops** [comment] 2020-10-10 08:13
Seems to solve this issue:
`alter table oc_flow_operations add column entity character varying(256) not null;`

**Comment by acsfer** [comment] 2020-10-10 08:16
Duplicate of https://github.com/nextcloud/server/issues/23174

**Closed by acsfer** 2020-10-10 08:16 UTC

**Comment by nimeops** [comment] 2020-10-10 08:17
not the same DB Server and version....

**Comment by acsfer** [comment] 2020-10-10 08:53
It has nothing to do with versions but with code that triggers this and is shared between versions.
