### ISSUE TITLE
Ios11 iPhone 8p APP Recycle Bin Can't See File Android App Normal

### ISSUE THREAD

**Issue by 330201818** [nextcloud/server#12958] opened 2018-12-10 05:32 UTC
Ios11 iPhone 8p APP Recycle Bin Can't See File Android App Normal

**Comment by MorrisJobke** [comment] 2019-03-25 13:46
Closing due to missing information what is broken and how to reproduce - most likely this should also go to https://github.com/nextcloud/ios

**Comment by MorrisJobke** [comment] 2019-03-25 13:47
ref nextcloud/ios#762

**Closed by MorrisJobke** 2019-03-25 13:46 UTC
