### ISSUE TITLE
Display size of deleted files

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#16862] opened 2019-08-25 20:21 UTC
## Problem:
When I go through my list of deleted files, it's for me to remove some and  free some space. But when you don't know the size of your files, it's tough to decide which ones to keep and which to remove.

## Solution:
Simply add a column with "Size" to display the size of each deleted item.

![Screenshot_2](https://user-images.githubusercontent.com/36133540/63655300-aa680680-c786-11e9-9d7e-ff87824cf73d.png)

**Comment by alexanderdd** [comment] 2020-02-05 02:25
Duplicate of #14138 (but nothing is happening over there either)

**Comment by alexanderdd** [comment] 2020-02-14 00:32
@pilsnerbeer can you close this? (duplicate)

**Closed** 2020-02-14 10:05 UTC
Labels: 0. Needs triage, enhancement
