### ISSUE TITLE
Update to 10.0.2 fails [Check for expected files]

### ISSUE THREAD

**Issue by pejakm** [nextcloud/server#3045] opened 2017-01-12 13:42 UTC
I started with paid NextCloud hosting, and from the admin panel I see there's version 10.0.2 available (current version is 10.0.1). However, when I start upgrade, it fails at the first step:

![snimak_20170112_143838](https://cloud.githubusercontent.com/assets/913292/21891867/ff6fe4e8-d8d4-11e6-8b4a-ddb471382097.png)

Don't know how to proceed here, since I don't have access to filesystem. Should I open a ticket at my hosting service or there is a way to override this?

```
PHP
Version: 5.6.21
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 513.0 MB

Database
Type: mysql
Version: 5.6.30
Size: 8.8 MB
```

**Comment by nickvergessen** [comment] 2017-01-12 13:51
@MorrisJobke

**Comment by MorrisJobke** [comment] 2017-01-13 09:55
> Don't know how to proceed here, since I don't have access to filesystem. Should I open a ticket at my hosting service or there is a way to override this?

There is no way to override this. We do this check because in the past there were files in the nextcloud directory causing the update to break, because they are loaded by the autoloader.

Best would be to let this fix by your host. @LukasReschke Do we want to allow to continue an update on your own risk?

**Comment by thejulian** [comment] 2017-01-17 08:26
:+1: for "continue an update on your own risk"

**Comment by LukasReschke** [comment] 2017-01-17 09:33
> Best would be to let this fix by your host. @LukasReschke Do we want to allow to continue an update on your own risk?

There are some other implications of that, we would also need to have a list of shipped folders that are safe to delete etc… (in case a folder gets removed in an update)

Kinda error-prone.

**Comment by MorrisJobke** [comment] 2017-05-04 23:02
Duplicate of https://github.com/nextcloud/updater/issues/68

**Closed by MorrisJobke** 2017-05-04 23:02 UTC
Labels: feature: install and update
