### ISSUE TITLE
filenames containing # get stripped when uploading via public "File drop" share

### ISSUE THREAD

**Issue by brrrrrrrt** [nextcloud/server#9175] opened 2018-04-13 12:20 UTC
### Steps to reproduce
1. share a folder via link and set "File drop (upload only)"
2. visit the share link
3. upload a file like "Test#123.txt"
4. the filename of the uploaded file is "Test"

### Expected behaviour

the filename should be "Test#123.txt"

### Actual behaviour
the filename gets stripped at the # character

this happens only when the permissions on the public share are set to "File drop (upload only)", it does not happen when it is set to "Allow upload and editing", see also browserlog

### Server configuration
typical LAMP using mod_php

**Operating system**:
Debian jessie, stretch
**Web server:**
Apache
**Database:**
Maria
**PHP version:**
5,6, 7.0
**Nextcloud version:** (see Nextcloud admin page)
13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh / upgraded from NC/OC
**Where did you install Nextcloud from:**
wget nextcloud.com/...
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - audioplayer: 2.2.5
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - circles: 0.13.6
  - comments: 1.3.0
  - contacts: 2.1.3
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.10
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - weather: 1.5.1
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "bla.bla.info"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/bla.bla.info",
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```
</details>

**Are you using encryption:** No

### Client configuration
**Browser:** latest Firefox, Chrome

**Operating system:**
Windows 7, Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no error logged.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no error logged.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Request URL: https://cloud.effet.info/public.php/webdav/Test

When i do the same on a public share with "Allow upload and editing" permissions, it looks like:
Request URL: https://cloud.effet.info/public.php/webdav/Test%23123.txt

```
</details>

**Comment by brrrrrrrt** [comment] 2018-07-05 09:52
the problem is not fixed, just tested with version 13.0.4

**Comment by szaimen** [comment] 2021-05-21 09:18
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by szaimen** [comment] 2021-06-18 15:47
I could reproduce this on NC21.0.2

**Comment by szaimen** [comment] 2023-01-09 11:26
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:36 UTC
Labels: bug, needs info, feature: sharing, 0. Needs triage
