### ISSUE TITLE
Unable to delete users in External Storage -> Available for

### ISSUE THREAD

**Issue by 48kRAM** [nextcloud/server#9153] opened 2018-04-11 21:05 UTC
Hi,

It appears that the GUI is unable to remove users from the "Available for" box when configuring external storage as an administrator.

### Steps to reproduce
1. Log in as administrator user
2. Open settings
3. Select "External Storages" under "Administration"
4. Configure an external storage of any kind
5. Click the "Available for" box and add a user for whom the storage should be available
6. Attempt to delete the user you just added - there's no way to do it

### Expected behaviour
I expect to be able to click on a user and have to option to delete said user

### Actual behaviour
User box does not respond to interaction at all

### Server configuration

**Operating system**:

RHEL7

**Web server:**

Apache HTTPd 2.4.x

**Database:**

Mysql 5.5.x (Percona)

**PHP version:**

7.1.15

**Nextcloud version:**

13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

Upgraded from 12.x

**Where did you install Nextcloud from:**
tar ball installation, I think.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
External storage support v 1.4.1
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - audioplayer: 2.2.5
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - dav: 1.4.6
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_external: 1.4.1
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - polls: 0.8.1
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - twofactor_u2f: 1.5.1
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
    "system": {
        "trusted_domains": [
            "astrocloud.nrao.edu"
        ],
        "dbtype": "mysql",
        "version": "13.0.1.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "remember_login_cookie_lifetime": 2592000,
        "session_lifetime": 259200,
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto, 31",
        "mail_smtpsecure": "tls"
    }
```
</details>

**Are you using external storage, if yes which one:**
Issue occurs with any/all types of external storage

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**

Active Directory

### Client configuration
**Browser:**

Chrome latest, Firefox ESR 52.7

**Operating system:**

macOS 10.12

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors logged
```
</details>

<summary>Browser log</summary>

```
DevTools failed to parse SourceMap: https://astrocloud.nrao.edu/core/vendor/purify.min.js.map
```
</details>

**Comment by MorrisJobke** [comment] 2018-06-19 16:14
> Click the "Available for" box and add a user for whom the storage should be available
> Attempt to delete the user you just added - there's no way to do it

I just tested this and it works just fine. Pressing backspace to remove elements works here.

If this is still an issue for you then please describe in detail what you tried to remove the user.

**Comment by 48kRAM** [comment] 2018-06-19 18:17
This works if you want to delete the last user in the list. There's no way to delete a user who isn't last in the list though, as cursor keys don't appear to work.

**Comment by 48kRAM** [comment] 2018-06-19 18:18
![screen shot 2018-06-19 at 2 18 00 pm](https://user-images.githubusercontent.com/8203971/41616275-9a851d08-73cb-11e8-8a65-9d7dc3185945.png)
In this case, how can I delete the user "John Effland"?

**Comment by MorrisJobke** [comment] 2018-06-19 19:14
> This works if you want to delete the last user in the list. There's no way to delete a user who isn't last in the list though, as cursor keys don't appear to work.

Nice catch 👍 

@nextcloud/javascript Anybody who wants to look into this?

**Comment by szaimen** [comment] 2021-05-21 11:34
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-21 11:34 UTC
Labels: 0. Needs triage, bug, feature: external storage, good first issue
