### ISSUE TITLE
[Bug]: No Permissions on nested folders when using S3 storage.

### ISSUE THREAD

**Issue by shawnlocal** [nextcloud/server#35195] opened 2022-11-16 05:16 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I recently added the External Storage app to my nextcloud instance. I was able to connect to a bucket in my S3 storage however although I can create new folders and files in Nextcloud, I can only access at the root level only. If I attempt to go further than root I get the following:

"You don't have permission to upload or create files here."

Other external devices and WebDav locations are fine. I am able to create nested folders and files directly in the S3 browser without any issues.

### Steps to reproduce

1. Add Extra Storage App 
2. Connect your S3 
3. Create a folder within S3 root folder on NC

### Expected behavior

Add and remove file in nested folders

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Extra Storage and other default apps
```

**Comment by szaimen** [comment] 2022-11-16 06:30
Which nc version?

**Comment by shawnlocal** [comment] 2022-11-17 00:34
Version  25.0.1

**Comment by shawnlocal** [comment] 2022-11-17 00:35
> Which nc version?

Version 25.0.1

**Comment by PVince81** [comment] 2022-11-17 12:53
what kind of S3 storage ? (Minio, AWS, etc)

am not aware of any regressions there and our CI tests S3 with Minio

**Comment by shawnlocal** [comment] 2022-11-17 19:50
> what kind of S3 storage ? (Minio, AWS, etc)
> 
> am not aware of any regressions there and our CI tests S3 with Minio

I tried AWS and idrive E2

**Comment by PVince81** [comment] 2022-11-18 15:38
My steps with Minio (S3 compatiable) and Nextcloud 25.0.1:
1. Run `docker run -p 9000:9000 minio/minio server /data`
2. Login into the minio web UI (credentials are minioadmin/minioadmin)
3. Enable external storage
4. Go to the external storage panel
5. Add an S3 external storage of type "Amazon S3" to a mount point "/s3"
6. As bucket name type "mybucket"
7. Hostname "localhost", Port 9000
8. Authenticate with access key: minioadmin/minioadmin
9. Tick "Use path style"
10. Click save and see green check
11. Go to the files app
12. Create a folder "/s3/test"
13. Upload some files into "/s3/test"
14. Create a folder "/s3/test/nested"
15. Upload some files into "/s3/test/nested"
16. Navigate back and forth through the folders => works fine
17. Check the Minio console, this is what I see:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/277525/202741911-1f2b8ee9-35d5-4099-accb-22ba12170b13.png">

18. Reset Nextcloud, keeping the bucket with the data
19. Reconfigure the external storage as before
20. Enter "/s3/test/nested"
21. See the files are there
<img width="255" alt="image" src="https://user-images.githubusercontent.com/277525/202742579-d4492cd3-d509-42e5-a034-2cba11e6f47e.png">

So there is no regression.

Please check how you configured the nested folders in S3 directly to make sure Nextcloud has access there with the given access credentials.

**Comment by PVince81** [comment] 2022-11-18 15:39
you can also try to `occ files:scan --all`
it is possible that if you originally didn't set permissions right in S3 and fixed them, maybe Nextcloud didn't detect this, so rescanning might fix that

**Comment by shawnlocal** [comment] 2022-11-20 01:13
I would appreciate if someone from nextcloud team take a look at this and fix the issue because without actual S3 support this app is useless. Thank you

**Comment by NSOLONAR** [comment] 2022-11-20 18:20
Could it be that there is a problem with the idrive e2 implementation? I have also been struggling with idrive e2, but I was able to use minio without any trouble. 
I have noticed that the permissions in the oc_filecache table are strange when using e2. I have not been able to track down the cause for this yet. 
I am happy to share some access keys to test buckets on e2 if somebody wants to have a closer look.

**Comment by PVince81** [comment] 2022-11-21 08:52
thanks for confirming that more people are having this issue

@juliushaertl @icewind1991 can you confirm ?

would be good to see also if it's a regression in Nextcloud 25 or if the issue exists in earlier versions also

**Comment by NSOLONAR** [comment] 2022-11-21 08:56
I have had this issue at already in NC 23. I had hoped upgrades would resolve this. I also eeplicated it on a completely fresh docker Nextcloud instance.

**Comment by shawnlocal** [comment] 2022-12-05 03:17
is it going to get fixed in the next version 25.0.2?

**Comment by shawnlocal** [comment] 2023-01-16 03:46
It seems nothing get fixed on NC. I am in process of moving to OC. 90% of apps do not work with NC 25. You can close this if you want. Thanks for the effort tho.

**Comment by joshtrichards** [comment] 2023-08-22 18:41
@shawnlocal Sorry to hear you ran into difficulty. I wish I'd seen your report earlier. NC works fine with genuine AWS S3 as either Primary Storage or External Storage across all of my test instances. And numerous people are using it. Typically the issues that arise are with third-party (non-AWS) implementations which aren't fully S3 compatible (we use the AWS S3 SDK) or they use different parameter names so people mix up which ones go where.

We've recently extensively rewritten the S3 related docs for External Storage to try to help a bit with this:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/amazons3.html

It seems like it's too late in your case, but just in case it's not, I'd be interested in:

- the actual Nextcloud log entries around the time period you got/get the `You do not have permission to upload or create files here` message (which isn't even an S3 error message; it's from Files so that's weird)
- the output of `occ files_external:list -a --output=json_pretty` (Redact anything you deem sensitive and feel free to exclude any non-S3 mount entries if desired)

**Comment by joshtrichards** [comment] 2023-08-22 18:45
> Create a folder within S3 root folder on NC

@shawnlocal - I just reread and saw the above. Are you saying you mounted this S3 bucket as your root folder in NC?

If so, that's likely the problem.

If you want to use S3 Object Store as your Primary Storage, that's not what External Storage is for. There's a dedicated means for using Object Storage as Primary Storage:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html

**Comment by joshtrichards** [comment] 2023-08-23 11:28
Another common scenario that might cause this is entering a hostname (when using AWS) containing the bucket name.

Unfortunately your report and reproductive steps didn't include much detail about your actual configuration. 

@NSOLONAR: Please provide your config details if you're having the same symptom as the original report.

**Comment by joshtrichards** [comment] 2024-08-04 16:15
Closing since the follow-up information needed has not been provided after nearly a year.

**Closed by joshtrichards** 2024-08-04 16:15 UTC
Labels: bug, needs info, 1. to develop, feature: external storage, regression, feature: object storage, 25-feedback
