### ISSUE TITLE
[Bug]: Editing an image does not work

### ISSUE THREAD

**Issue by Ducknuke** [nextcloud/server#45484] opened 2024-05-23 15:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I click on files and select an image, then click on edit, i.e. on the pen. Then it reloads and then the message appears. “Il n'y a pas d'extension disponible pour afficher ce type de fichier.”
![image](https://github.com/nextcloud/server/assets/89637250/f099b08f-f2bf-4684-a841-cfda1536df06)

when I get this error I have a lot of errors messages in the log :
![image](https://github.com/nextcloud/server/assets/89637250/742b6746-2f22-4f7d-a673-f1d05ce79b87)

I have to reload the browser so that I can select any files again and then everything works again except for editing an image

### Steps to reproduce

1. Open an image (.jpg...)
2. Select the pen at the top right

### Expected behavior

1. Open an image
2. Select the pen at the top right
3. Edit your image
4. Save and close

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "https:\/\/nextcloud.********.fr\/"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "29.0.0.19",
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "fr",
        "force_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "force_locale": "fr_FR",
        "default_timezone": "Europe\/Paris",
        "knowledgebaseenabled": true,
        "knowledgebase.embedded": false,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "davstorage.request_timeout": 30,
        "session_relaxed_expiry": false,
        "session_keepalive": true,
        "auto_logout": false,
        "token_auth_enforced": false,
        "token_auth_activity_update": 60,
        "auth.bruteforce.protection.enabled": true,
        "auth.bruteforce.protection.testing": false,
        "ratelimit.protection.enabled": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 465,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": true,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_send_plaintext_only": false,
        "mail_smtpstreamoptions": [],
        "mail_sendmailmode": "smtp",
        "overwritehost": "nextcloud.********.fr",
        "overwriteprotocol": "https",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "https:\/\/nextcloud.***********.fr\/",
        "proxy": "",
        "proxyuserpwd": "***REMOVED SENSITIVE VALUE***",
        "proxyexclude": [],
        "allow_local_remote_servers": false,
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto",
        "appcodechecker": true,
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "has_internet_connection": true,
        "connectivity_check_domains": [
            "www.nextcloud.com",
            "www.startpage.com",
            "www.eff.org",
            "www.edri.org"
        ],
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "check_data_directory_permissions": true,
        "config_is_read_only": false,
        "log_type": "file",
        "log_type_audit": "file",
        "logfile": "\/data\/nextcloud.log",
        "logfile_audit": "\/data\/audit.log",
        "logfilemode": 416,
        "loglevel": 2,
        "loglevel_frontend": 2,
        "syslog_tag": "Nextcloud",
        "syslog_tag_audit": "Nextcloud",
        "log.condition": {
            "shared_secret": "***REMOVED SENSITIVE VALUE***",
            "users": [
                "sample-user"
            ],
            "apps": [
                "files"
            ]
        },
        "log.backtrace": false,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Paris",
        "log_query": false,
        "log_rotate_size": 104857600,
        "profiler": false,
        "customclient_desktop": "https:\/\/nextcloud.com\/install\/#install-clients",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.nextcloud.client",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/nextcloud\/id1125420102?mt=8",
        "customclient_ios_appid": "1125420102",
        "defaultapp": "dashboard,files",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v1",
        "appsallowlist": [],
        "apps_paths": [
            {
                "path": "\/app\/www\/public\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "preview_concurrency_all": 8,
        "preview_concurrency_new": 4,
        "preview_max_x": 4096,
        "preview_max_y": 4096,
        "preview_max_filesize_image": 50,
        "preview_max_memory": 512,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\BMP",
            "OC\\Preview\\GIF",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\Krita",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PNG",
            "OC\\Preview\\PDF",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap"
        ],
        "maintenance": false,
        "maintenance_window_start": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "supportedDatabases": [
            "sqlite",
            "mysql",
            "pgsql",
            "oci"
        ],
        "forbidden_chars": [
            "?",
            "<",
            ">",
            ":",
            "*",
            "|",
            "\""
        ],
        "theme": "",
        "enforce_theme": "",
        "minimum.supported.desktop.version": "2.3.0",
        "external_storage.auth_availability_delay": 1800,
        "files_external_allow_create_new_local": true,
        "filesystem_check_changes": 0,
        "part_file_in_storage": true,
        "filesystem_cache_readonly": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "max_filesize_animated_gifs_public_sharing": 10,
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "filelocking.debug": false,
        "upgrade.disable-web": false,
        "upgrade.cli-upgrade-link": "",
        "debug": false,
        "data-fingerprint": "",
        "lookup_server": "https:\/\/lookup.nextcloud.com",
        "gs.enabled": false,
        "gs.federation": "internal",
        "simpleSignUpLink.shown": true,
        "login_form_autocomplete": true,
        "no_unsupported_browser_warning": false,
        "files_no_background_scan": false,
        "diagnostics.logging": true,
        "diagnostics.logging.threshold": 0,
        "profile.enabled": true,
        "enable_file_metadata": true,
        "account_manager.default_property_scope": [],
        "projects.enabled": false,
        "bulkupload.enabled": true,
        "reference_opengraph": true,
        "unified_search.enabled": false,
        "enable_non-accessible_features": true,
        "mail_smtpauthtype": "LOGIN",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "admin",
            "utilisateur"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - maps: 1.4.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.2
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - circles: 29.0.0-dev (installed 29.0.0-dev)
  - encryption: 2.17.0
  - text: 3.10.0 (installed 3.9.1)
  - updatenotification: 1.19.1 (installed 1.17.0)
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"HB0PHtBWL7JEDksakiM7","level":3,"time":"2024-05-23T16:40:38+02:00","remoteAddr":"192.168.1.254","user":"Romain","app":"no app in context","method":"GET","url":"/ocs/v2.php/teams/resources/files/718799","message":"No provider found for id files","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","version":"29.0.0.19","exception":{"Exception":"RuntimeException","Message":"No provider found for id files","Code":0,"Trace":[{"file":"/app/www/public/lib/private/Teams/TeamManager.php","line":95,"function":"getProvider","class":"OC\\Teams\\TeamManager","type":"->"},{"file":"/app/www/public/core/Controller/TeamsApiController.php","line":84,"function":"getTeamsForResource","class":"OC\\Teams\\TeamManager","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"listTeams","class":"OC\\Core\\Controller\\TeamsApiController","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/app/www/public/ocs/v1.php","line":66,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/app/www/public/ocs/v2.php","line":23,"args":["/app/www/public/ocs/v1.php"],"function":"require_once"}],"File":"/app/www/public/lib/private/Teams/TeamManager.php","Line":77,"message":"No provider found for id files","exception":[],"CustomMessage":"No provider found for id files"},"id":"664f58dd89c32"}
```

**Comment by joshtrichards** [comment] 2024-05-23 15:50
Looks related to Teams (formerly Circles) shared files. Moving to that repository since it doesn't appear to be a general matter.

**Comment by joshtrichards** [comment] 2024-05-23 15:56
Although looking closer, we might had a dependency matter here since we're in the middle of a transition. And the newer Teams stuff wraps some of the former Circles stuff, but we're still permitting the Circles app to be disabled (which you appear to have done).

**Comment by Ducknuke** [comment] 2024-05-23 17:22
Thank you @joshtrichards. 
The problem is that even if I activate the Teams application I still have the problem. 
There should no longer be any dependency problems?

**Comment by skjnldsv** [comment] 2024-05-24 08:23
We would need some data before the reload (after you click the edit button)
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by h4fnp** [comment] 2024-05-24 08:52
I am affected by this bug, too. Here is my console log:
![2024-05-24-103042_1276x484_scrot](https://github.com/nextcloud/server/assets/138957113/db13e46b-6fac-4388-a157-fb893a930cd7)

**Comment by skjnldsv** [comment] 2024-05-24 11:33
@h4fnp you look like you haven't enabled the appropriate mimes in your config.php
That seems a bit different from @Ducknuke

**Comment by Ducknuke** [comment] 2024-05-24 12:40
![image](https://github.com/nextcloud/server/assets/89637250/d6adabe9-e7f2-474c-b404-b3015285bb0f)
I notice that I also have this mime warning with a lot of warnings in the middle :
![image](https://github.com/nextcloud/server/assets/89637250/85f2c432-eaa7-4e45-860e-34121937b582)

**Comment by Ducknuke** [comment] 2024-05-24 12:48
I executed this command `occ maintenance:mimetype:update-db --repair-filecache` thinking that my mimes were not up to date and apparently he made quite a few Add but still the same problem.

Added mimetype "application/msaccess" to database
Added mimetype "application/illustrator" to database
Added mimetype "text/x-shellscript" to database
Added mimetype "application/x-blender" to database
Added mimetype "image/bpg" to database
Added mimetype "application/x-bzip2" to database
Added mimetype "text/x-c" to database
Added mimetype "text/x-c++src" to database
Added mimetype "application/comicbook+7z" to database
Added mimetype "application/comicbook+ace" to database
Added mimetype "application/comicbook+tar" to database
Added mimetype "application/comicbook+truecrypt" to database
Added mimetype "application/coreldraw" to database
Added mimetype "application/java" to database
Added mimetype "application/x-cbr" to database
Added mimetype "application/x-deb" to database
Added mimetype "application/vnd.ms-word.document.macroEnabled.12" to database
Added mimetype "application/vnd.openxmlformats-officedocument.wordprocessingml.template" to database
Added mimetype "video/dv" to database
Added mimetype "application/vnd.ms-fontobject" to database
Added mimetype "application/postscript" to database
Added mimetype "application/x-fictionbook+xml" to database
Added mimetype "video/x-flv" to database
Added mimetype "text/x-h" to database
Added mimetype "text/calendar" to database
Updated 4 filecache rows for mimetype "image/x-icon"
Added mimetype "text/impress" to database
Added mimetype "text/x-java-source" to database
Added mimetype "image/jp2" to database
Added mimetype "application/x-kdbx" to database
Added mimetype "application/x-iwork-keynote-sffkey" to database
Added mimetype "application/km" to database
Added mimetype "application/vnd.google-earth.kml+xml" to database
Added mimetype "application/vnd.google-earth.kmz" to database
Added mimetype "application/x-krita" to database
Added mimetype "text/x-ldif" to database
Added mimetype "application/vnd.lotus-wordpro" to database
Added mimetype "video/mp2t" to database
Added mimetype "audio/m4b" to database
Added mimetype "application/x-freemind" to database
Added mimetype "application/x-mobipocket-ebook" to database
Added mimetype "application/x-iwork-numbers-sffnumbers" to database
Added mimetype "application/vnd.oasis.opendocument.formula" to database
Added mimetype "application/msonenote" to database
Added mimetype "text/org" to database
Added mimetype "application/x-iwork-pages-sffpages" to database
Updated 1 filecache rows for mimetype "application/pdf"
Added mimetype "application/x-font" to database
Added mimetype "application/x-php" to database
Added mimetype "application/x-perl" to database
Added mimetype "audio/x-scpls" to database
Added mimetype "application/vnd.ms-powerpoint" to database
Added mimetype "application/vnd.ms-powerpoint.template.macroEnabled.12" to database
Added mimetype "application/vnd.openxmlformats-officedocument.presentationml.template" to database
Added mimetype "application/vnd.ms-powerpoint.addin.macroEnabled.12" to database
Added mimetype "application/vnd.ms-powerpoint.slideshow.macroEnabled.12" to database
Added mimetype "application/vnd.openxmlformats-officedocument.presentationml.slideshow" to database
Added mimetype "application/vnd.ms-powerpoint.presentation.macroEnabled.12" to database
Added mimetype "text/reveal" to database
Added mimetype "application/rss+xml" to database
Added mimetype "application/sgf" to database
Added mimetype "image/sgi" to database
Added mimetype "application/x-shockwave-flash" to database
Added mimetype "application/x-compressed" to database
Added mimetype "application/x-tar" to database
Added mimetype "application/vnd.garmin.tcx+xml" to database
Added mimetype "application/x-tex" to database
Added mimetype "image/tga" to database
Added mimetype "text/vcard" to database
Added mimetype "video/dvd" to database
Added mimetype "application/vnd.visio" to database
Added mimetype "application/vnd.ms-visio.drawing.macroEnabled.12" to database
Added mimetype "application/vnd.ms-visio.drawing" to database
Added mimetype "application/vnd.ms-visio.stencil.macroEnabled.12" to database
Added mimetype "application/vnd.ms-visio.stencil" to database
Added mimetype "application/vnd.ms-visio.template.macroEnabled.12" to database
Added mimetype "application/vnd.ms-visio.template" to database
Added mimetype "audio/webm" to database
Added mimetype "application/font-woff" to database
Added mimetype "application/vnd.wordperfect" to database
Added mimetype "application/x-gimp" to database
Added mimetype "application/vnd.ms-excel.addin.macroEnabled.12" to database
Added mimetype "application/vnd.ms-excel.sheet.binary.macroEnabled.12" to database
Added mimetype "application/vnd.ms-excel.sheet.macroEnabled.12" to database
Added mimetype "application/vnd.ms-excel.template.macroEnabled.12" to database
Added mimetype "application/vnd.openxmlformats-officedocument.spreadsheetml.template" to database
Added mimetype "application/vnd.xmind.workbook" to database
Added mimetype "application/yaml" to database
Added 86 new mimetypes
Updated 5 filecache rows

**Comment by h4fnp** [comment] 2024-05-24 12:51
It would be nice, if this was only a misconfiguration on my site. Here is my (redacted) config.php:
```
<?php
$CONFIG = array (
  'instanceid' => '**SNIP**',
  'passwordsalt' => '**SNIP**',
  'secret' => '**SNIP**'
  'trusted_domains' => 
  array (
    0 => 'cloud.**SNIP**.com',
  ),
  'datadirectory' => '/www/htdocs/**SNIP**/data/cloud.**SNIP**.com',
  'dbtype' => 'mysql',
  'version' => '29.0.1.1',
  'overwrite.cli.url' => 'https://cloud.**SNIP**.com',
  'dbname' => '**SNIP**',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '**SNIP**',
  'dbpassword' => '**SNIP**',
  'installed' => true,
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'cloud',
  'mail_domain' => '**SNIP**.com',
  'htaccess.RewriteBase' => '/',
  'tempdirectory' => '/www/htdocs/**SNIP**/tmp/cloud.**SNIP**.com',
  'simpleSignUpLink.shown' => false,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'filelocking.enabled' => false,
  'maintenance_window_start' => 2,
  'default_phone_region' => 'DE',
);
```
Can you @skjnldsv please point me to some documentation how to "enabled the appropriate mimes"?

**Comment by h4fnp** [comment] 2024-05-24 12:55
> I executed this command `occ maintenance:mimetype:update-db --repair-filecache` thinking that my mimes were not up to date and apparently he made quite a few Add but still the same problem.

Same over here:
```
$ php83 occ maintenance:mimetype:update-db --repair-filecache
Added mimetype "application/vnd.openxmlformats-officedocument.wordprocessingml.document.docxf" to database
Added mimetype "application/vnd.openxmlformats-officedocument.wordprocessingml.document.oform" to database
Added 2 new mimetypes
Updated 0 filecache rows
```

**Comment by Ducknuke** [comment] 2024-05-24 13:12
I don't know if it's related to the problem but I see these "Teams" errors appear when I open the sidebar and the Chrome console is launched. I specify that the sidebar works even with these errors
![image](https://github.com/nextcloud/server/assets/89637250/5948bf9f-e12d-400b-93ed-7d7f69483cb3)

**Comment by Ch3ck3rM0n** [comment] 2024-05-31 08:37
Have the same issue like you reported. Can not figure out to fix it.

**Comment by Ador-able** [comment] 2024-06-03 02:34
Same issue here after update.

**Comment by h4fnp** [comment] 2024-06-06 18:40
For the record: Upgrade from 29.0.1 to 29.0.2 did not solve the issue for me.

**Comment by Infamousbugg** [comment] 2024-06-06 19:46
> For the record: Upgrade from 29.0.1 to 29.0.2 did not solve the issue for me.

Yeah, it's not working for me either after the update.

**Comment by ernolf** [comment] 2024-06-10 10:35
@joshtrichards:
Ain't this a duplicate of nextcloud/viewer/issues/2323 ?

**Comment by h4fnp** [comment] 2024-06-26 05:41
@EXT-OWL I switched back to [gThumb](https://gitlab.gnome.org/GNOME/gthumb) 🥲

**Comment by skjnldsv** [comment] 2024-07-05 06:01
Duplicate of https://github.com/nextcloud/viewer/issues/2323

**Closed by skjnldsv** 2024-07-05 06:01 UTC
Labels: bug, 0. Needs triage, feature: circles, 29-feedback
