### ISSUE TITLE
AppStoreChecker generates 1.5G log file

### ISSUE THREAD

**Issue by albatros69** [nextcloud/server#25202] opened 2021-01-19 11:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Since this morning, the AppStoreChecker dumps a huge quantity of data into the nextcloud.log file. Based on some exchanges with others on social media, I assume I'm not the only one facing this issue.

### Steps to reproduce
1. Nothing really: just let NextCloud run and finally launch the appstorechecker at some point

### Expected behaviour
A reasonable log should be written to log (or nothing maybe)

### Actual behaviour
A 1.5GB amount of data is dumped into the nextcloud.log file

### Server configuration

**Operating system:**
Debian 10.7
**Web server:**
nginx/1.14.2
**Database:**
PostgreSQL 11.9 (Debian 11.9-0+deb10u1)
**PHP version:**
7.3.19
**Nextcloud version:** (see Nextcloud admin page)
20.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Github release
**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - keeweb: 0.6.4
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - news: 15.1.1
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.6.3
  - previewgenerator: 3.1.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_photospheres
  - maps
  - spreed
  - survey_client

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "dbtype": "pgsql",
        "version": "20.0.5.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.release.channel": "stable",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "logtimezone": "Europe\/Paris",
        "log_rotate_size": 10485760,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "keeweb",
            "calendar"
        ]
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### Web server error log
Not relevant

#### Nextcloud log (data/nextcloud.log)
This is the 4092 first characters of the last line of the nextcloud.log file.
```
$ tail -1 nextcloud.log.1 | wc          
      1   77326 1723906
$ grep appstoreFetcher nextcloud.log.1 | wc 
    894 69129444 1541171798
```

{"reqId":"tBpHRmpatiHANyr4dMBL","level":2,"time":"2021-01-19T11:40:26+01:00","remoteAddr":"[..]","user":"[..]","app":"appstoreFetcher","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"InvalidArgumentException","Message":"server version is invalid","Code":0,"Trace":[{"file":"/[..]/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php","line":119,"function":"isCompatible","class":"OC\\App\\CompareVersion","type":"->","args":["7.3.19-1~deb10u1","5.6",">="]},{"file":"/[...]/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php","line":187,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\AppFetcher","type":"->","args":["W/\"2021-01-18 21:55:09.829540+00:00\"","[{\"id\":\"defaultlinkopen\",\"categories\":[\"customization\",\"tools\"],\"userDocs\":\"\",\"adminDocs\":\"\",\"developerDocs\":\"\",\"issueTracker\":\"https:\\/\\/github.com\\/blizzz\\/DefaultLinkOpen\\/issues\",\"website\":\"\",\"created\":\"2018-01-11T22:23:44.709327Z\",\"lastModified\":\"2018-11-30T23:07:35.466423Z\",\"releases\":[{\"version\":\"1.2.0\",\"phpExtensions\":[],\"databases\":[],\"shellCommands\":[],\"phpVersionSpec\":\"*\",\"platformVersionSpec\":\">=13.0.0 <16.0.0\",\"minIntSize\":32,\"download\":\"https:\\/\\/github.com\\/blizzz\\/DefaultLinkOpen\\/releases\\/download\\/v1.2.0\\/defaultlinkopen.tar.gz\",\"created\":\"2018-11-30T23:07:35.457036Z\",\"licenses\":[\"agpl\"],\"lastModified\":\"2018-11-30T23:07:35.567657Z\",\"isNightly\":false,\"rawPhpVersionSpec\":\"*\",\"rawPlatformVersionSpec\":\">=13 <=15\",\"signature\":\"HmfMojsU7rIEe0+NJbZdSO5NRBNQiXqaZFgOw29v5hUIu1\\/RcaAFlIcb7noWJJdIjOtEDVGB6D+Xj+CX89fPNUPliNTFGbn4GMnw8FPx29btlCLPak3CjN9qi7cWcQJHk4dpVEDB8CO90AE1VS4jKqNJhZVU7O4oKQLkJTVpcTd3SxKlKHQ\\/2UU7fQVhGbTJQVBS\\/PrH5262rT35bF\\/H1J\\/WCdqX\\/DuF1ydPeZDbWzvd1\\/gG2xN\\/6UxF\\/MAiHRDt6XyH1gw8jVJURR06VNlr2Hr43dl\\/0V5viOAr\\/McBM0os7X9YSxZp\\/ffIAS9RKVjXwrHwvAVte2gw4J7WiLHMBZjd65TDjfok0FVZgMoVjLhuDgu+1YU8JLeQ8uuqMKr6rh8EExReTXviqm3ASNkIawup3jOzZk4smdnEDxvyum\\/LHPoZNqFsGgGykuqf16a2PwNhoNeyw2og\\/OwEUF2EBpYS6BqMPfA7jd8Ag4bn4rFQxeRm4UazU2J\\/wPOd\\/2GhPywTFMegqNV7wApJtXVoZJ1lLlrINxZxjk7cyJHv+RhHu9sXOSDGySjFIArtFbQZVa\\/XUmofyqwSavoTCo\\/bkDPV4LMpLjzVDhizdEVLqas52VFePN2XMsxjz\\/tH8GZqS1dFyjikkWHXSDkXxpXuvpbtlgVN2oZRHM78mRU5btk=\",\"translations\":{\"en\":{\"changelog\":\"\"}},\"signatureDigest\":\"sha512\"}],\"screenshots\":[],\"translations\":{\"en\":{\"name\":\"Default Link Open\",\"summary\":\"Restores browser default behaviour in opening links in comments\",\"description\":\"Since Nextcloud 13, links written in comments are formatted and thus clickable. However, they will open in a new Tab\\/Window, instead of following browser default.\\n\\nThis app restores default behaviour, which the user has to assume either way \\u00af\\\\\\\\_(\\u30c4)_\\/\\u00af\"}},\"isFeatured\":false,\"authors\":[{\"name\":\"Arthur Schiwon\",\"mail\":\"blizzz@arthur-schiwon.de\",\"homepage\":\"\"}],\"ratingRecent\":0.5,\"ratingOverall\":0.5,\"ratingNumRecent\":0,\"ratingNumOverall\":0,\"certificate\":\"-----BEGIN CERTIFICATE-----\\nMIIECjCCAvICAhCGMA0GCSqGSIb3DQEBCwUAMHsxCzAJBgNVBAYTAkRFMRswGQYD\\nVQQIDBJCYWRlbi1XdWVydHRlbWJlcmcxFzAVBgNVBAoMDk5leHRjbG91ZCBHbWJI\\nMTYwNAYDVQQDDC1OZXh0Y2xvdWQgQ29kZSBTaWduaW5nIEludGVybWVkaWF0ZSBB\\ndXRob3JpdHkwHhcNMTgwMTA5MjIxMDM0WhcNMjgwNDE2MjIxMDM0WjAaMRgwFgYD\\nVQQDDA9kZWZhdWx0bGlua29wZW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK\\nAoICAQDcBQJ4B\\/sXox+\\/wFeokjG5dINEhvGuHpycbrwsGjCQpSP7ZDcG6CzboRAH\\nWXQ1KmcnBd6zdJEmPZG2OELNdC9BU6o8nM9Yn1Q\\/gVsBCyMGYVIh57n6dDKWGg4j\\n7\\/EiTGkrTebpLbKeAS2zg\\/aZDn+hc0pkUT5aF+G0C30a+8EwmsiXClvWsyyzy1iy\\nw0cD0kjUt3NlwCgtJgTXLiqS6dBR6nWcuJdmPAVJItkrRawkyCz8GtD6624abWOT\\nU\\/8LULlbdyplIfctS9jxj9qksInNAAo\\/Mnf\\/5jZdtlDPvRWivlM01q5qla9L1NyF\\njNFCir82YSM2aPa3paUyCxCVm6DdS1CoBFzDV6BuvxD2HqxcvtxvoGfDBLiz+XXX\\nH+fXTX3ilI7v5kH9bxGHLEB+1RJmQvW7f\\/9fVfxmTu7w9EE0UTjcqP4XszOpC05C\\nHnmb7Qx2HWQKgTg4+dlymi4u1f7S7s0KlQXOMnkHKl4IGvAaPrdRtNIP1vPOEB0W\\ns5LZYd6aXlCtCz1e83twuYjOGMCuuD90m\\/IRs8wPZAmy\\/UkpgBpJpqOhN\\/YFDnn

#### Browser log
Not relevant

**Comment by ad2012** [comment] 2021-01-19 12:08
Hi @albatros69,
had that, too. The problem was fixed for me by #25152

**Comment by albatros69** [comment] 2021-01-19 12:15
> had that, too. The problem was fixed for me by #25152

Thanks for the hint (not obvious at first glance that this could be related)
Seems to be included in 20.0.6. Not sure if it's best to patch this manually or wait for a release. I would prefer the later provided that the release date is very close...

**Comment by ad2012** [comment] 2021-01-19 12:17
I've fixed it manually - works fine so far :)

**Comment by albatros69** [comment] 2021-01-19 13:06
> That one drove me crazy and bumped up nextcloud.log to 90GiB in a couple of seconds eyes

That's a nice one 😅 but I can't do that as that will eat potentially 180GB on the data partition where the user data sit and... tha'ts problematic!

**Comment by ad2012** [comment] 2021-01-19 14:51
To be a little bit more specific: **The bug took 90GiB in total (in+out)**. Nevertheless nextcloud.log will be renamed after growing to 128MB and will be gzipped.

--> After applying the bugfix logging returned to normal.

**Comment by kesselb** [comment] 2021-01-20 09:17
Closing as duplicate of https://github.com/nextcloud/server/issues/25137

**Closed by kesselb** 2021-01-20 09:17 UTC
Labels: 0. Needs triage, bug
