### ISSUE TITLE
http proxy support should allow no_proxy settings

### ISSUE THREAD

**Issue by luizluca** [nextcloud/server#20300] opened 2020-04-03 21:20 UTC
**Is your feature request related to a problem? Please describe.**
Currently, nextcloud will use proxy for every request it does, even for local domain

**Describe the solution you'd like**
It should allow to set no_proxy

**Describe alternatives you've considered**
Editing code

**Additional context**

**Comment by kesselb** [comment] 2020-04-04 08:16
Closing as duplicate of https://github.com/nextcloud/server/issues/12402.

https://github.com/nextcloud/server/pull/17684 for more details.

**Closed by kesselb** 2020-04-04 08:16 UTC
Labels: 0. Needs triage, enhancement
