### ISSUE TITLE
[Bug]: Incorrect text and icon color since Nextcloud 28

### ISSUE THREAD

**Issue by stephanedupont** [nextcloud/server#44709] opened 2024-04-07 14:47 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm using `#607d8b` as the background color for a Nextcloud instance.

Up until Nextcloud 27.x included, the text and icon color was some kind of white (as expected with such a background color). See this screenshot from a Nextcloud 27 instance:

![image](https://github.com/nextcloud/server/assets/5102441/5dc9035a-a56c-472b-9a9a-41605c98e779)

... but since Nextcloud 28.x, the color is incorrect, it uses some kind of black instead of some kind of white. See this screenshot from a Nextcloud 28.0.4 instance:

![image](https://github.com/nextcloud/server/assets/5102441/597a08a3-0a1e-4a90-b11e-9e9daec60cde)

### Steps to reproduce

1. Go to Administration Settings, Theming
2. Use `#607d8b` as Color

### Expected behavior

The color should be as it was in Nextcloud 27.x.

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by newhinton** [comment] 2024-04-07 18:54
I had the same, it used turquoise instead of the configured red.

It also only occured on firefox, but not on chromium.
I replaced my server files with the zip from the homepage, and that seems to have it fixed.

**Comment by stephanedupont** [comment] 2024-04-08 08:46
@newhinton: I don't think that's the same problem. The problem I describe is not about the color being incorrect, it's about the text and icon color that goes with the background color set in theming.

**Comment by susnux** [comment] 2024-04-10 03:54
> Use `#607d8b` as Color

The icon and text color is chosen to have enough contrast on your background color, thus for accessibility the contrast has to be at least 4.5:1. For your color and white as icon color it would only be 4.37:1
So black is chosen (4.8:1).

This is by design, but will be fixed with #42977 which allows you then to choose a primary color independent from the background color / image.

**Closed by susnux** 2024-04-10 03:54 UTC
Labels: bug, 0. Needs triage, 28-feedback

**Comment by stephanedupont** [comment] 2024-04-10 07:25
Thank you, looking forward to the release of #42977 then.

**Comment by stephanedupont** [comment] 2024-09-19 06:51
@susnux Hi, is it supposed to be released and working in version 30.0.0?

I can see background color and primary color, but I don't understand how to set them to fix this so it uses white icons:

![image](https://github.com/user-attachments/assets/b10d256b-69b0-440e-9799-af980f0f55d2)
