### ISSUE TITLE
Integrity check failed on Nextcloud 16.0.1

### ISSUE THREAD

**Issue by pixel8383** [nextcloud/server#15681] opened 2019-05-22 09:29 UTC
### Steps to reproduce
1. Update freeBSD installation to 16.0.1 using pkg upgrade
2. Check for file integrity using "occ integrity:check-app accessibility"

### Expected behaviour
No integrity fails

### Actual behaviour
 - FILE_MISSING:
    - l10n/mk.js:
      - expected: a2e44f768bc467705616e73de781c611c290a9aa58f8d48d1076cb2e4403894c68a6c613a7cd67ce39016213307171f02afd8a4206cd308c002a14ee1f8f9ad4
      - current:
    - l10n/mk.json:
      - expected: d291395d459185fa98398792a5598f1b27c1cfb5d227b6999f88caefde4455acd2785a23b8e80a7e430be38eba7556545b24b59bff72f053189a560f9564f476
      - current:

### Server configuration

**Web server:** FreeBSD 11.2-RELEASE-p9

**Database:** mysql 5.6.44

**PHP version:** 7.1.28

**Nextcloud version:** 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 16.0

**Where did you install Nextcloud from:** pkg

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- accessibility
	- FILE_MISSING
		- l10n/mk.js
		- l10n/mk.json

Raw output
==========
Array
(
    [accessibility] => Array
        (
            [FILE_MISSING] => Array
                (
                    [l10n/mk.js] => Array
                        (
                            [expected] => a2e44f768bc467705616e73de781c611c290a9aa58f8d48d1076cb2e4403894c68a6c613a7cd67ce39016213307171f02afd8a4206cd308c002a14ee1f8f9ad4
                            [current] => 
                        )

                    [l10n/mk.json] => Array
                        (
                            [expected] => d291395d459185fa98398792a5598f1b27c1cfb5d227b6999f88caefde4455acd2785a23b8e80a7e430be38eba7556545b24b59bff72f053189a560f9564f476
                            [current] => 
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - support
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps-pkg",
                "url": "\/apps-pkg",
                "writable": true
            }
        ],
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.100",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "http:\/\/192.168.1.100",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by pixel8383** [comment] 2019-05-22 09:41
I added those files manually (actually the entire l10n folder was missing under /apps/accessibility/) and run a new integrity check but it failed anyway.

**Comment by deprecated7** [comment] 2019-05-24 07:48
I can confirm this issue on FreeBSD 11.2-STABLE (FreeNAS custom jail). Installing the files manually and setting permissions didn't help.

**Comment by salsugair** [comment] 2019-05-27 02:03
i encountered the same issue following the same steps

**Comment by CarterJimmy** [comment] 2019-05-30 02:54
Same issue on FreeNas11.2-U4.1 (FreeBSD 11.2-STABLE).
I installed Nextcloud via official plugins manager.

**Comment by pixel8383** [comment] 2019-06-19 14:38
Any news on it? Seems like the scan is expecting something more thant what actually exists.

**Comment by skjnldsv** [comment] 2019-08-07 15:57
Can't reproduce after upgrade to latest 16.0.x :)

**Comment by skjnldsv** [comment] 2019-08-07 15:57
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-08-07 15:57 UTC
Labels: 0. Needs triage, bug

**Comment by pixel8383** [comment] 2019-08-07 21:18
I do confirm, seems like it is OK with the latest release.
