### ISSUE TITLE
Doctrine\DBAL\Schema\SchemaException: An index with name 'idx_e98f2ec48b26c2e9' was already defined on table 'oc_cards'.

### ISSUE THREAD

**Issue by ottiff** [nextcloud/server#13602] opened 2019-01-15 10:29 UTC
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Doctrine\DBAL\Schema\SchemaException: An index with name 'idx_e98f2ec48b26c2e9' was already defined on table 'oc_cards'.

**Comment by skjnldsv** [comment] 2020-08-20 13:35
You have to manually change the index. No idea how that happened, but I cannot reproduce the error :man_shrugging: 
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-20 13:35 UTC
Labels: 0. Needs triage, bug
