### ISSUE TITLE
Webdav access fails with "Folder not found" when trailing space in folder name,

### ISSUE THREAD

**Issue by bodangren** [nextcloud/server#6980] opened 2017-10-27 05:37 UTC
### Steps to reproduce
1. Create a folder in the web interface with a trailing space
2. Connect to WebDAV via a file browser (both Linux Mint and Windows 7 tested) 
3. Navigate to the folder, and be given an error that the folder doesn't exist

### Expected behaviour
Tell us what should happen
The contents of the folder should be displayed

### Actual behaviour
Tell us what happens instead
An error is thrown on Linux file browsers. On Windows 7, it fails silently, and the folder is shown as empty.

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12.03
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 11
**Where did you install Nextcloud from:**
From the main site
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.0
  - apporder: 0.4.0
  - audioplayer: 2.1.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - circles: 0.13.3
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.4
  - drawio: 0.8.8
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: true
  - onlyoffice: 1.1.5
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - admin_migrate
  - apptemplate
  - dashboard
  - django_auth
  - emoji
  - encryption
  - encryption_dummy
  - federation
  - files_archive
  - files_markdown
  - files_odfviewer
  - files_reader
  - files_sgfviewer
  - files_svgedit
  - fluxx_compensator
  - impress
  - issuetemplate
  - nextant
  - ownpad_lite
  - pong
  - pushnotifications
  - reader
  - search
  - tattoo
  - user_ldap
  - user_migrate
  - user_oauth
  - user_openid_provider
  - user_persona
  - user_vd
  - user_webfinger

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

{
    "system": {
        "instanceid": "oc1y0cpneqx9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "doc.echoenglish.org",
            "101.37.149.41"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "http:\/\/doc.echoenglish.org\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "session_lifetime": 86400,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{imap.exmail.qq.com:993\/imap\/ssl}"
                ]
            }
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "no-reply",
        "mail_domain": "echoenglish.org",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.exmail.qq.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "versions_retention_obligation": "auto,30",
        "activity_expire_days": 60
    }
}

```
</details>

**Are you using external storage, if yes which one:** Yes. Mounted OSSFS from AliCloud. Errors occur in normal data partition, though.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

</details>

### Client configuration
**Browser:**
Chrome or Firefox
**Operating system:**
Windows XP, 7, 10, Linux Mint 18.2
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2017-10-27 08:24
Duplicate of #5843

**Closed by MorrisJobke** 2017-10-27 08:24 UTC

**Comment by bodangren** [comment] 2017-11-10 07:23
For reference, my report includes information on Linux for browsers. Just a
first guess ... This means it's a bug in the PhP implementation.
