### ISSUE TITLE
A session had already been started - after update to v19

### ISSUE THREAD

**Issue by d0niek** [nextcloud/server#21270] opened 2020-06-06 14:33 UTC
Hi,
after success upgrade from version **18.0.5** to version **19.0.0** I see in my logs a lot of messages: `[PHP] Error: session_start(): A session had already been started`

raw message:

```json
{
  "reqId":"Su2ptJ4S2VT85BUsar96",
  "level":3,
  "time":"2020-06-06T13:53:57+00:00",
  "remoteAddr":"my_ip_address",
  "user":"--",
  "app":"PHP",
  "method":"GET",
  "url":"/index.php/apps/notes/api/v0.2/notes?pruneBefore=1591390232",
  "message":"session_start(): A session had already been started - ignoring at /var/www/html/lib/private/Session/Internal.php#209",
  "userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.11.1",
  "version":"19.0.0.12",
  "id":"5edba5b071ef0"
}
```

The list of that error is really long... In version **18.0.5** my logs was really clean.

I don't know how can I get more details about it so please give me some info to provide more debug information to find a problem/solution.

**Comment by kesselb** [comment] 2020-06-06 15:08
Duplicate of #20490

Please use the search. It's easy to find the existing issue if you search for "A session had already been started".

**Closed by kesselb** 2020-06-06 15:08 UTC
Labels: 0. Needs triage, bug
