### ISSUE TITLE
Viewing image from shared link shows a share button

### ISSUE THREAD

**Issue by jhesketh** [nextcloud/server#18323] opened 2019-12-10 10:56 UTC
### Steps to reproduce
1. Share a folder of images as a link
2. Set Hide Download on folder
3. Open the link
4. View an image (with the gallery/image preview UI)
5. The share button is visible
6. Clicking it does not immediately do anything
7. When closing the image preview, you will see "Error while retrieving shares"

### Expected behaviour
The share link should not be visible.

### Actual behaviour
The share link is visible on image previews.

**Comment by szaimen** [comment] 2021-05-27 12:56
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 12:56 UTC
Labels: 0. Needs triage, bug
