### ISSUE TITLE
Sharing: Members are not shown

### ISSUE THREAD

**Issue by fschloegl** [nextcloud/server#5485] opened 2017-06-20 12:19 UTC
### Steps to reproduce
As you can see, at the "Sharing" tab of my file, there is only the group "devteam" shown.
![image](https://user-images.githubusercontent.com/13234252/27332641-ecb986ea-55c2-11e7-9889-ef1175fc53a3.png)

But in the "Activities" tab you see, that I added much more members
![image](https://user-images.githubusercontent.com/13234252/27332661-141796c8-55c3-11e7-87e4-f468c391ece8.png)

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** PostgresSQL 9.5.7

**PHP version:** 7 

**Nextcloud version:** 12.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 11.x

**Where did you install Nextcloud from:** https://nextcloud.com/install/#instructions-server

**Comment by MorrisJobke** [comment] 2017-08-30 09:50
@nextcloud/sharing Any idea why this happens? 

@fschloegl I can't reproduce this sadly :/

**Comment by JaredBoone** [comment] 2017-09-19 00:23
I'm having a similar issue after upgrading from 11.0.3 to 12.0.2. In my case, a user is sharing a folder with about 25 sharees, however none of the sharees are visible to the user in the browser (in ShareDialogShareeListView). 

Operating system: CentOS release 6.6 (Final)
Web server: Apache2
Database: PostgresSQL 9.5.3
PHP version: 7.0.14
Nextcloud version: 12.0.2
Updated from an older Nextcloud/ownCloud or fresh install: updated from 11.x

**Comment by JaredBoone** [comment] 2017-09-19 22:27
This issue is not browser-specific (I reproduced it in Chrome 60, Safari, and Firefox). Also, the server is returning a JSON array with the right number of rows in the response to "shares?format=json&path=...". Only one of my users has reported this issue so far and I've confirmed that not all users are affected.

@MorrisJobke @nextcloud/sharing Please let me what additional info you would like me to provide.

**Comment by JaredBoone** [comment] 2017-09-20 01:37
OK, I believe I have tracked it down to this code in the ShareAPIController:
`		if ($include_tags) {
			$formatted = Helper::populateTags($formatted, 'file_source');
		}`
The issue only occurs for folders that have been marked as a favorite, using the yellow star icon (aka tagged). If the folder is favorited, then the JSON array data from the AJAX "shares" response is invalid - it contains multiple copies of the same row data. I'm not sure if this is the correct fix, but it worked for me in my initial test:
`		if ($include_tags) {
			$formatted = Helper::populateTags($formatted, 'id');
		}`

**Comment by rullzer** [comment] 2017-09-20 19:53
This is fixed in the latest release

**Comment by JaredBoone** [comment] 2017-09-20 20:30
@rullzer I upgraded from 12.0.2 to 12.0.3 and that fixed the problem for me. Thanks!

**Comment by rullzer** [comment] 2017-09-21 15:19
@JaredBoone good to hear!

**Closed by rullzer** 2017-09-21 15:19 UTC
Labels: bug, feature: sharing
