### ISSUE TITLE
Issues with public shares with a plus in sub folders

### ISSUE THREAD

**Issue by dceee** [nextcloud/server#20671] opened 2020-04-26 16:02 UTC
I noticed this when I tried to share some pictures and users were complaining that they could not open the files. If a public share has a folder containing a '+', pictures cannot be opened. 
![image](https://user-images.githubusercontent.com/9974336/80312668-aa714800-87e6-11ea-8603-a48e4f80ba28.png)

Other files like text files seem to open fine.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a folder you want to share by a public link
2. Create a sub folder with a name containing a plus eg. my+folder
3. Place a picture in the sub folder
4. Open shared link and try to open the picture

### Expected behaviour
The picture is opened and displayed.

### Actual behaviour
Instead of the picture an error message is displayed "Error loading IMG_xyz.jpg"

### Server configuration

**Operating system:**
CentOS 7.7.1908

**Web server:**
Apache 2.4.6

**Database:**
mysql 5.5.64

**PHP version:**
7.2.27

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0.3

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - audioplayer
  - bookmarks_fulltextsearch
  - calendar
  - encryption
  - files_inotify
  - gallery
  - mail
  - maps
  - notes

</details>

**Comment by skjnldsv** [comment] 2020-04-27 06:02
Duplicate of https://github.com/nextcloud/viewer/issues/415

**Closed by skjnldsv** 2020-04-27 06:02 UTC
Labels: 0. Needs triage, bug
