### ISSUE TITLE
Nextcloud 22.0.1 - Mobile menu

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#28613] opened 2021-08-27 11:45 UTC
### Steps to reproduce
1. Click on the #app-navigation-toggle element

### Expected behaviour
App navigation should open

### Actual behaviour
Doesn't show, or open when clicked several times

### Server configuration

**Operating system:**
CentOS 7
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
22.1.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install and update
**Where did you install Nextcloud from:**
Official Nextcloud website

### Client configuration
**Browser:**
Safari, Brave
**Operating system:**
MAC OS Big SUR and iOS 14.7.1

![alt text](https://i.imgur.com/lGncNrt.png)

**Comment by szaimen** [comment] 2021-09-15 14:38
I can reproduce this on NC22.1.1 and NC21.0.4

**Comment by TomerPacific** [comment] 2021-10-01 06:30
Hi @vipera7 , I'd like to help out.

**Comment by szaimen** [comment] 2021-10-31 14:34
Hi @TomerPacific, feel free to go ahead and create a PR with a fix :)

**Comment by Aman-Mandal** [comment] 2022-01-20 11:26
Is this issue still there ?.. and if yes, can anybody please guide me .. bc this one is my very first!

**Comment by szaimen** [comment] 2022-01-20 13:41
I fear I am not able to guide you. Maybe @skjnldsv does?

**Comment by Ayushbajpai19** [comment] 2022-10-04 15:03
I would like to take this issue for hacktoberfest

**Comment by skjnldsv** [comment] 2022-10-25 12:05
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2022-10-25 12:05 UTC
Labels: bug, design, good first issue, 1. to develop
