### ISSUE TITLE
Admin password confirmation popup timeout is too short

### ISSUE THREAD

**Issue by baldurmen** [nextcloud/server#11448] opened 2018-09-28 21:30 UTC
### Steps to reproduce
1. Log in with an admin account
2. Open the user management page
3. Add a new user
4. Try to type a long password in the 'Authentication required' popup

### Expected behaviour

The 'Authentication required' popup lets you type the password and does not timeout after 5 seconds.

### Actual behaviour

The 'Authentication required' popup timeouts after 5 seconds, thus not letting you type in long passwords.

Afterwards, an error message is shown:

    You did not enter the password
    An error occured during the request. Unable to proceed.

### Server configuration

**Operating system**: Debian Stretch

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.26

**PHP version:** 7.0.30

**Nextcloud version:** 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** The website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - firstrunwizard: 2.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_u2f: 1.6.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_videoplayer
  - gallery
  - serverinfo
  - survey_client
  - systemtags
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.agebdeb.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/New_York",
        "log_rotate_size": "1048576",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "auth.bruteforce.protection.enabled": false,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "lost_password_link": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": false,
        "default_language": "fr",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** Firefox 60.1.0

**Operating system:** Debian

**Comment by danielkesselberg** [comment] 2018-09-28 22:07
Looks for me like a duplicate of #11224. Could you close this issue if it is? Thank you :+1:

**Closed** 2018-09-29 19:45 UTC
Labels: bug

**Comment by miradam** [comment] 2018-10-04 21:12
Folks did you manage to resolve this? I can't add new users manually via admin panel /index.php/settings/users
