### ISSUE TITLE
Only highlight currently hovered app-navigation element

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#13268] opened 2018-12-26 15:53 UTC
With nextcloud 15, the app-navigation gets a new highlight, which adds the appname to the bar when the menu is beeing hovered. 

Sometimes, the appname overlaps the next app or gets cut off because it is too long.
An improvement could be to only highlight the hovered app, and show the rest of the bar "un-highlighted".

**Comment by newhinton** [comment] 2018-12-26 15:56
cc @nextcloud/designers

**Comment by jancborchardt** [comment] 2018-12-27 15:02
With "highlight" do you mean showing the name? The design intetionally shows the names of all apps because people don’t necessarily know what the different icons mean – especially if they are not so deep in Nextcloud as we are. ;)

Regarding the overlapping and cut-off, see https://github.com/nextcloud/server/issues/13047

**Comment by newhinton** [comment] 2018-12-28 00:46
Yeah, i meant that

Just thought that only showing the "currently hovered app" would "clean up" the ui while keeping the benefit of that new feature :) but i don't know if it is better or not

**Comment by jancborchardt** [comment] 2019-01-01 14:53
See design reasoning and discussion on why we introduced this at: https://github.com/nextcloud/server/pull/12153

And this here is basically a duplicate of https://github.com/nextcloud/server/issues/12778 – see reasoning there. :)

@raneon you mention different issues – please open separate issues for that. Thanks!

**Closed by jancborchardt** 2019-01-01 14:53 UTC
Labels: 0. Needs triage, enhancement
