### ISSUE TITLE
Show file tags in files app

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/server#10675] opened 2018-08-13 15:49 UTC
I would like to see what tags are assigned to a file when viewing in Details View

![image](https://user-images.githubusercontent.com/8312560/44042631-97b7b38a-9ed5-11e8-85f1-edcfae13393e.png)

There's lots of white space that can be used to see tags.

**Comment by MorrisJobke** [comment] 2018-08-20 13:02
cc @nextcloud/designers

**Comment by skjnldsv** [comment] 2018-08-20 13:04
Wasn't this removed a few years back? @jancborchardt

**Comment by juliushaertl** [comment] 2018-08-20 13:09
Seems to be a duplicate of https://github.com/nextcloud/server/issues/6424

**Comment by MorrisJobke** [comment] 2018-08-21 06:49
> Seems to be a duplicate of #6424

Correct 👍

**Closed by MorrisJobke** 2018-08-21 06:49 UTC
Labels: 0. Needs triage, design, enhancement, feature: files, feature: tags
