### ISSUE TITLE
[Bug]: Icon of menu entry "Dashboard" in Apps section remains black in dark mode

### ISSUE THREAD

**Issue by luddinho** [nextcloud/server#42803] opened 2024-01-15 14:12 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Inside the Apps menu the icon of entry "Dashboard" remains black when switching to dark mode.

![SCR-20240115-nfjr](https://github.com/nextcloud/server/assets/76713238/1e989df9-66d6-4bc7-9617-d71d373ef998) ![SCR-20240115-nfrj](https://github.com/nextcloud/server/assets/76713238/343748f2-44ae-413b-ae25-cfa636ee8861)

Nextcloud Sever: 27.1.5
Apache 2.4
PHP 8.2

### Steps to reproduce

1. Open Apps section
2. The icon of menu item "Dashboard" is always black
3. Switch between light and dark mode, icon of Dashboard remains black

### Expected behavior

The icon shall switch its color to white when dark mode is enabled.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - calendar: 4.6.3
  - checksum: 1.2.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.1
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.4.4
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - polls: 5.4.2
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.18.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.11.2
  - spreed: 17.1.4
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by theTyster** [comment] 2024-03-07 22:40
Can this be closed? I am not seeing this issue in 28.0.3. or on the master branch anymore.

![dark theme](https://github.com/nextcloud/server/assets/136642464/3eb78399-de2c-46ac-a082-9b47e394eabb) ![image](https://github.com/nextcloud/server/assets/136642464/63ab8328-32ac-4fc9-99e4-d51305df4d7f)

**Comment by luddinho** [comment] 2024-03-08 14:39
I have updated my Test Instance to 28.0.3, but the issue still exists on my side.
From my point of view the issue cannot be closed.


https://github.com/nextcloud/server/assets/76713238/c90c32e5-72cf-43e8-ab9b-1fdb7eb98599

**Comment by theTyster** [comment] 2024-03-08 18:01
hmm tricky...

@luddinho  What browser are you using?

**Comment by luddinho** [comment] 2024-03-08 19:29
I'm using Microsoft Edge as default browser on my system.

The dark Theme is set to follow the system standard.
<img width="864" alt="image" src="https://github.com/nextcloud/server/assets/76713238/477e2783-cbde-4b7a-aef8-1794e670ea7e">

And for switching the system standard I'm using Nightfall on Mac OS with an keyboard shortcut. Therefore you are not able to see any action from the screen record.

But now I can confirm that with a different browser than MS Edge the icon appears correct in whilte color when using dark mode.

Please take a look on the new screen record.
Browsers that have been used (from left to the right): MS Edge, Chrome, Safari

https://github.com/nextcloud/server/assets/76713238/ac504433-e719-46c4-b584-b8dc60dd187f

Uhh yeah very crazy. It seems that only MS Edge behaves wrong!
I will additionally do the same comparison with another Nextcloud instance on 27.1.7 to check if also MS Edge will be responsible for that issue.

I will inform you about the result.

**Comment by luddinho** [comment] 2024-03-08 19:40
The result with Nextcloud 27.1.7
All browsers (MS Edge, Chrome, Safari) behaves wrong on dark mode on that version.

https://github.com/nextcloud/server/assets/76713238/39d5b9be-4fda-462f-bb51-428e299646e4

**Comment by susnux** [comment] 2024-03-10 20:25
Probably duplicate of https://github.com/nextcloud/server/issues/42998

**Closed** 2024-03-11 15:21 UTC
Labels: bug, 0. Needs triage, feature: apps management, 27-feedback
