### ISSUE TITLE
OCP\RichObjectStrings\InvalidObjectExeption

### ISSUE THREAD

**Issue by aleadco** [nextcloud/server#24403] opened 2020-11-27 01:15 UTC
**Describe the bug**
I have reported this issue https://github.com/nextcloud/deck/issues/2616#issue-750404193 in the Deck application section considering it could be an application issue. After checking another nextcloud server you may assume that this problem occurred after upgrading to nextcloud version 20.0.2.

**To Reproduce**
1. Go to 'Access the timeline'

**Expected behavior**
View the project timeline

**Screenshots**
![image](https://user-images.githubusercontent.com/35962168/100182736-524d1200-2eab-11eb-9102-ad89fa2d374f.png)

**Server details**

**Operating system**:

**Web server:** : Apache2

**Database:** : MySQL

**PHP version:** : 7.4

**Nextcloud version:** (20.0.2)

**Where did you install Nextcloud from:** : tar

**Signing status:** 👍

**Logs**

#### Nextcloud log (data/nextcloud.log)
`
{"reqId":"3gUMqK8LcBKgCY67GPXt","level":3,"time":"2020-11-24T23:05:37-05:00","remoteAddr":"152.206.198.194","user":"alejandrod","app":"activity","method":"GET","url":"/ocs/v1.php/apps/activity/api/v2/activity/deck?format=json&type=deck&since=0&object_type=deck&object_id=39&limit=50","message":{"Exception":"OCP\\RichObjectStrings\\InvalidObjectExeption","Message":"Parameter is undefined","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/activity/lib/GroupHelper.php","line":91,"function":"validate","class":"OC\\RichObjectStrings\\Validator","type":"->"},{"file":"/var/www/nextcloud/apps/activity/lib/Data.php","line":244,"function":"addActivity","class":"OCA\\Activity\\GroupHelper","type":"->"},{"file":"/var/www/nextcloud/apps/activity/lib/Controller/APIv2Controller.php","line":273,"function":"get","class":"OCA\\Activity\\Data","type":"->"},{"file":"/var/www/nextcloud/apps/activity/lib/Controller/APIv2Controller.php","line":209,"function":"get","class":"OCA\\Activity\\Controller\\APIv2Controller","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getFilter","class":"OCA\\Activity\\Controller\\APIv2Controller","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"}],"File":"/var/www/nextcloud/lib/private/RichObjectStrings/Validator.php","Line":72,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36","version":"20.0.2.2","id":"5fbdd94404ac8"}
`
</details>

**Comment by radoeka** [comment] 2021-05-13 09:36
I've a similar issue.  At least the back trace is very much the same (same line numbers), but my url is:

"url": "/ocs/v2.php/apps/activity/api/v2/activity?since=0&limit=50&format=json"

Here there is no app mentioned....

Due to the userAgetnt string, I've a slight idea who is calling the url, but for now I've now clue how to get rid of this message.

**Comment by szaimen** [comment] 2021-07-06 09:38
Duplicate of https://github.com/nextcloud/deck/issues/2616

**Closed by szaimen** 2021-07-06 09:38 UTC
Labels: 0. Needs triage, bug
