### ISSUE TITLE
blank screen during upgrade to 17.0.1 from 16.0.1 due to Group Folders app.

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/server#17988] opened 2019-11-18 15:51 UTC
This seems to be holding my upgrade to 17.0.1

there was no message to upgrade group folders before I upgraded. there was no message of an not yet compatible group folder app.
upgrade resulted in a blank page till I fixed according to:

https://github.com/nextcloud/groupfolders/commit/fa87c7164d01fa4732fcbbc4b498cb4b2926b42e

found in https://github.com/nextcloud/groupfolders/issues/565 related issue.

**Comment by kesselb** [comment] 2019-11-18 15:56
Duplicate of https://github.com/nextcloud/server/issues/17338

**Closed by kesselb** 2019-11-18 15:56 UTC
Labels: 0. Needs triage, bug
