### ISSUE TITLE
[Bug]: New style drag-and-drop upload box broken, uploads themselves broken on firefox, and admin logging page broken on latest version

### ISSUE THREAD

**Issue by BartAgterbosch** [nextcloud/server#42567] opened 2024-01-03 20:07 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

So, essentially what the title says, when trying to upload anything on the latest version of nextcloud via Chromium or Brave (all shields+adblockers disabled), the now smaller new style upload box where you have to drag and drop the files starts glitching out, appearing and disappearing 10 times a second, making it impossible to drag and drop files using one of those two browsers (haven't yet tried other chromium based browsers, at the very least however here the uploads complete.
On Firefox, this does not happen, the drag-and-drop box stays in place, though it's still an annoying design choice, but the files will simply disappear right before the upload is complete, no error message, no status bar, no completed file, nothing.
On all 3 browsers, the logging page no longer works, which is now blank, I've tried pointing it to the proper log file in config.json as was suggested in an older forumthread I found, but that didn't seem to do anything, again with all adblockers and/or shields disabled.
It was working fine literally right up until I updated the nextcloud container about half an hour ago, which immediately broke it, I haven't changed or tinkered with anything else within that timeframe.

Nextcloud version: 28.0.1.
Running on up to date Ubuntu server in docker.
Client platform: Windows 10 22h2.
All used browsers were up to date.

### Steps to reproduce

Update to the latest 28.0.1 version and try to upload anything larger than 1gb

### Expected behavior

For it to not be broken

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by BartAgterbosch** [comment] 2024-01-03 20:23
Edit: I would like to add a slight annoyance to that, which is less critical but still very annoying, and that is that renaming files has become very frustrating, clicking "rename" on a file will not select the text of the filename anymore, meaning if you have to rename a bunch of files you now have to manually select it from start to end, or do ctrl+a and write the extension on the end for every single file you rename.
I'm pretty sure this is also a UI bug though, just like the drag-and-drop box, because for a slight split-second after you click "rename", the text is highlighted, only to immediately deselect by itself

**Comment by tigernero79** [comment] 2024-01-03 21:34
https://github.com/nextcloud/server/issues/42561

**Comment by joshtrichards** [comment] 2024-01-03 21:54
Drag & drop:
- Duplicate of...various.
- Already fixed in #42366 / #42409 (and possibly others)
- It'll be in v28.0.2

Logging:
- Check your browser console. Likely a configuration issue on your web server. That's why it impacted all your browsers. Chances are your web server is not setup properly to handle `.mjs` files. The NC27 release notes document this, but many overlooked it and it became a bigger problem when they moved to NC28. 

Naming:
- Duplicate of #42097

In the future please limit each Issue to only one matter. Otherwise it's impossible to manage independent matters which may be closed at different times or be handled by different people, etc. Thanks!

**Closed by joshtrichards** 2024-01-03 21:54 UTC
Labels: bug, 0. Needs triage, feature: files, 28-feedback

**Comment by BartAgterbosch** [comment] 2024-01-04 21:30
Hmm, but the drag and drop behavior between Firefox and chromium based browsers is different, the Firefox behavior does not match what is described in the duplicate.
But I will keep my eye out for 28.0.2 then, and I will have a look into handling .mjs files, thanks

**Comment by tigernero79** [comment] 2024-01-18 21:23
I installed 28.0.2 RC and noticed that drag and drop works.  but the bug remains when applications need to be updated and nextcloud asks for password because perhaps the user was previously logged in.  updates disappear before entering the password.  and after inserting it you just have to go to the application to be updated to see if it is updating

**Comment by BartAgterbosch** [comment] 2024-04-05 20:00
Just wanted to drop back in and say that as of 18.0.4 everything seems to have been fixed, the drag and drop uploads have been fixed, as well as uploading on firefox, the visual glitching, and multiple file uploads. Also the UI navigation has been fixed, I can set a folder name upon creation in a popup box instead of having to scroll through hundreds of folders to find the newly created folder named "new folder", and the right click menu has now also been fixed and appears next to the mouse instead of all the way to the right of the screen.
Awesome guys, everything working smoothly again
