### ISSUE TITLE
failed to set external Storage with Internal Server Error

### ISSUE THREAD

**Issue by sweetlazyboy** [nextcloud/server#14459] opened 2019-03-01 14:51 UTC
### Steps to reproduce
1. Go Accout > Settings
2. Select External Storage from left pane.

### Expected behaviour
Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

### log info
"url":"\/settings\/user\/externalstorages","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"","Code":0,"Trace":[{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Files\/SimpleFS\/SimpleFile.php","line":104,"function":"putContent","class":"OC\\Files\\Node\\File"

### Server configuration
**Operating system**:
CentOS Linux release 7.6.1810 (Core)
**Web server:**
nginx/1.12.2
**Database:**
5.5.60-MariaDB
**PHP version:**
PHP 7.0.33
**Nextcloud version:** (see Nextcloud admin page)
nextcloud-15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
nextcloud.com

### Client configuration
**Browser:**
Chrome, IE
**Operating system:**
Windows 10

**Comment by skjnldsv** [comment] 2020-11-08 10:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-11-08 10:45 UTC
Labels: 0. Needs triage
