### ISSUE TITLE
System Information document includes S3 key and secret in plain text.

### ISSUE THREAD

**Issue by Chris-Leeworthy** [nextcloud/server#18074] opened 2019-11-22 13:00 UTC
Generate the system information document.

### Expected behaviour
Produce a system information document including config.php with sensitive data replaced by the string "***REMOVED SENSITIVE VALUE***"

I would expect the key and secret for my S3 primary storage to be treated as sensitive values.

### Actual behaviour
The key and secret for my S3 primary storage are included in plain text in the document.  This would give the recipient the keys to my S3 buckets. 

### Server configuration

**Operating system**:
CentOS Linux release 7.7.1908 (Core)

**Web server:**
nginx/1.16.1 (fpm-fcgi)

**Database:**
 pgsql PostgreSQL 12.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

**PHP version:**
7.3.12

**Nextcloud version:** (see Nextcloud admin page)
17.0.1 - 17.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Nextcloud Download site.

```

**Comment by kesselb** [comment] 2019-11-22 13:26
Thanks for reporting :+1: 

Duplicate of https://github.com/nextcloud/server/issues/17659

**Closed by kesselb** 2019-11-22 13:26 UTC
Labels: 0. Needs triage, bug
