### ISSUE TITLE
Feature request: Email update notification for admins

### ISSUE THREAD

**Issue by gituser789** [nextcloud/server#25536] opened 2021-02-08 19:16 UTC
**Is your feature request related to a problem? Please describe.**
Nextcloud web interface provides update notifications for admins. Keeping systems up to date is very important in it-security. But not all admins are regulary logged in the web interface. Nextcloud provides email notifications on events. The option to send a notification in case of update available is not given.

**Describe the solution you'd like**
Add an option under settings -> activity to send an email notification if nextcloud update is available.

**Comment by kesselb** [comment] 2021-02-08 20:58
Duplicate of https://github.com/nextcloud/server/issues/3596

**Closed by kesselb** 2021-02-08 20:58 UTC
Labels: 0. Needs triage, enhancement
