### ISSUE TITLE
Group Admin can delete users from server

### ISSUE THREAD

**Issue by carboneater** [nextcloud/server#7293] opened 2017-11-27 01:04 UTC
### Steps to reproduce
0. Delegate Group Admin Permissions to a user (GA) for a given Group (G1).
0.1. Said Group has some users (U2) with rights in some other groups (G2, ...) on the same server
0.2. Group Admin wants to revoke authorizations to his group
1. Group Admin Clicks "Delete User" on user with multiple accesses (U2) in order to remove said user from G1. (Instead of using the dropdown menu to that end.)

### Expected behaviour
- If the user pressing the delete button is a server admin, delete the user.
- If the user pressing the delete button is a group admin:
-- If U2 belongs to other groups: remove U2 from the group;
-- If U2 belongs to no other groups: Either remove U2 from group or delete it from server.

### Actual behaviour
Group Admin deletes user from server, disregarding all the user's access.

### Server configuration

**Operating system**:
Linux sleipnir 4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux

**Web server:**
nginx/1.13.6

**Database:**
mariadb  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.0.22-3 (cli) (built: Aug 23 2017 05:51:41) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-3, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Nextcloud tarball

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dashboard: 4.0.5
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - systemtags
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc6n6tqq77xl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "tsunami.ageg.ca",
            "nextcloud.ageg.ca"
        ],
        "datadirectory": "\/srv\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/tsunami.ageg.ca",
        "dbhost": "localhost",
        "dbname": "nextcloud",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "version": "12.0.3.3",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "openssl": {
            "config": "\/etc\/ssl\/openssl.cnf"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "serveur",
        "mail_domain": "ageg.ca",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "sleipnir.ageg.ca",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Nope

**Are you using encryption:** yes/no
Full Disk Encrytion

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------+
| Configuration                 | s01                                                        |
+-------------------------------+------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                            |
| hasPagedResultSupport         |                                                            |
| homeFolderNamingRule          |                                                            |
| lastJpegPhotoLookup           | 0                                                          |
| ldapAgentName                 | cn=nextcloud,ou=services,dc=ageg,dc=ca                     |
| ldapAgentPassword             | ***                                                        |
| ldapAttributesForGroupSearch  |                                                            |
| ldapAttributesForUserSearch   |                                                            |
| ldapBackupHost                |                                                            |
| ldapBackupPort                |                                                            |
| ldapBase                      | dc=ageg,dc=ca                                              |
| ldapBaseGroups                | dc=ageg,dc=ca                                              |
| ldapBaseUsers                 | dc=ageg,dc=ca                                              |
| ldapCacheTTL                  | 600                                                        |
| ldapConfigurationActive       | 1                                                          |
| ldapDefaultPPolicyDN          |                                                            |
| ldapDynamicGroupMemberURL     |                                                            |
| ldapEmailAttribute            | mail                                                       |
| ldapExperiencedAdmin          | 0                                                          |
| ldapExpertUUIDGroupAttr       |                                                            |
| ldapExpertUUIDUserAttr        |                                                            |
| ldapExpertUsernameAttr        |                                                            |
| ldapGidNumber                 | gidNumber                                                  |
| ldapGroupDisplayName          | cn                                                         |
| ldapGroupFilter               |                                                            |
| ldapGroupFilterGroups         |                                                            |
| ldapGroupFilterMode           | 0                                                          |
| ldapGroupFilterObjectclass    |                                                            |
| ldapGroupMemberAssocAttr      | uniqueMember                                               |
| ldapHost                      | ldapi:///                                                  |
| ldapIgnoreNamingRules         |                                                            |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(cn=%uid)))) |
| ldapLoginFilterAttributes     | cn                                                         |
| ldapLoginFilterEmail          | 0                                                          |
| ldapLoginFilterMode           | 0                                                          |
| ldapLoginFilterUsername       | 1                                                          |
| ldapNestedGroups              | 0                                                          |
| ldapOverrideMainServer        |                                                            |
| ldapPagingSize                | 500                                                        |
| ldapPort                      | 389                                                        |
| ldapQuotaAttribute            |                                                            |
| ldapQuotaDefault              |                                                            |
| ldapTLS                       | 0                                                          |
| ldapUserDisplayName           | displayname                                                |
| ldapUserDisplayName2          |                                                            |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                             |
| ldapUserFilterGroups          |                                                            |
| ldapUserFilterMode            | 0                                                          |
| ldapUserFilterObjectclass     | inetOrgPerson                                              |
| ldapUuidGroupAttribute        | auto                                                       |
| ldapUuidUserAttribute         | auto                                                       |
| turnOffCertCheck              | 0                                                          |
| turnOnPasswordChange          | 0                                                          |
| useMemberOfToDetectMembership | 1                                                          |
+-------------------------------+------------------------------------------------------------+

</details>

### Client configuration
**Browser:**
Any

**Operating system:**
Any

#### Web server error log
<details>
<summary>Web server error log</summary>
No Webserver Error
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Could not find relevant entry...
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

No Error
</details>

**Comment by carboneater** [comment] 2017-11-27 01:10
The reason I make a distinction between Server Admins and Group admins is there's an expectation that server admins actually know what they are doing.
As for Group Admins, I host a setup for a student union where group admins change on a yearly basis, hence they're basically clueless about how to manage users and delete users instead of revoking their rights on a regular basis...

**Comment by MorrisJobke** [comment] 2017-11-27 06:39
Duplicate of #3630

**Closed by MorrisJobke** 2017-11-27 06:39 UTC
