### ISSUE TITLE
[Bug]: toolbar/actions scroll out of view in files app

### ISSUE THREAD

**Issue by Tschoepler** [nextcloud/server#43818] opened 2024-02-24 20:32 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

the toolbar with the actions scrolls out of view. hence, if i have multiple files selected i have to scroll all the way back up to apply batch actions. this even made me wonder if such a feature is really missing until i realized it was simply out of view.
<img width="927" alt="image" src="https://github.com/nextcloud/server/assets/2727803/f5b8f5c6-85ca-4fb4-8709-41d51794d737">
<img width="976" alt="image" src="https://github.com/nextcloud/server/assets/2727803/998d725b-a459-4327-be2d-1c8e766056c5">

### Steps to reproduce

1. open files app
2. select any file(s)/folder(s)
3. scroll the list of files by >30px

### Expected behavior

the actions/toolbar should always be visible when one or more files are selected

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "share.tschoepler.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/share.tschoepler.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0",
            "timeout": "1.5"
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "default_phone_region": "DE",
        "htaccess.RewriteBase": "\/",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "maintenance": false,
        "loglevel": 2,
        "app_install_overwrite": [
            "breezedark",
            "news"
        ],
        "preview_max_x": 256,
        "preview_max_y": 256,
        "trashbin_retention_obligation": "30, auto"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - groupfolders: 16.0.3
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - maps: 1.3.1
  - news: 24.0.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.3
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - calendar: 4.6.4 (installed 4.6.4)
  - circles: 28.0.0-dev (installed 26.0.0)
  - contacts: 5.5.1 (installed 5.5.1)
  - deck: 1.12.1 (installed 1.12.1)
  - encryption: 2.16.0
  - files_external: 1.20.0 (installed 1.18.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - forms: 4.0.0 (installed 4.0.0)
  - tasks: 0.15.0 (installed 0.15.0)
  - theming_customcss: 1.15.0 (installed 1.15.0)
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.5.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"Y4FHZmfPqMWzJuHmDs8fNgAAABc","level":2,"time":"2022-11-25T22:53:26+00:00","remoteAddr":"5.180.209.43","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0","version":"","data":[]}
{"reqId":"Y4FHZmfPqMWzJuHmDs8fNgAAABc","level":2,"time":"2022-11-25T22:53:26+00:00","remoteAddr":"5.180.209.43","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:106.0) Gecko/20100101 Firefox/106.0","version":"","data":[]}
{"reqId":"Y4FIsWfPqMWzJuHmDs8hEAAAABc","level":2,"time":"2022-11-25T22:58:57+00:00","remoteAddr":"198.235.24.6","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Expanse, a Palo Alto Networks company, searches across the global IPv4 space multiple times per day to identify customers&#39; presences on the Internet. If you would like to be excluded from our scans, please send IP addresses/domains to: scaninfo@paloaltonetworks.com","version":"","data":[]}
{"reqId":"Y4FIsWfPqMWzJuHmDs8hEAAAABc","level":2,"time":"2022-11-25T22:58:57+00:00","remoteAddr":"198.235.24.6","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Expanse, a Palo Alto Networks company, searches across the global IPv4 space multiple times per day to identify customers&#39; presences on the Internet. If you would like to be excluded from our scans, please send IP addresses/domains to: scaninfo@paloaltonetworks.com","version":"","data":[]}
{"reqId":"AGysKGG6OQWf5FTeu8iV","level":3,"time":"2022-11-25T23:01:45+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Table \"oc_photos_collaborators\" has no primary key and therefor will not behave sane in clustered setups. This will throw an exception and not be installable in a future version of Nextcloud.","userAgent":"--","version":"25.0.1.1","data":[]}
```

**Comment by susnux** [comment] 2024-02-24 22:37
Resolved with 28.0.3, as this is a duplicate of  #43149

**Closed by susnux** 2024-02-24 22:37 UTC
Labels: bug, 0. Needs triage, 28-feedback
