### ISSUE TITLE
Nextcloud 20.0.1 - user manual displayed with a few centimeters height only instead of full window height

### ISSUE THREAD

**Issue by goligo** [nextcloud/server#23986] opened 2020-11-08 15:34 UTC
### Steps to reproduce
1. Open https://try.nextcloud.com , start "Instant trial"
2. Click on your user icon in the top right corner, then select "Help"
3. Nextcloud navigates to "/settings/help"

### Expected behaviour
User manual should be shown 

### Actual behaviour
User manual is shown in an iframe about 3cm high and is unusable, like this
![nextcloudhelp](https://user-images.githubusercontent.com/1894593/98469464-185bea80-21e0-11eb-8e50-192e65af8a26.png)

### Server configuration
Official nextcloud demo servers

**Comment by goligo** [comment] 2020-11-08 15:45
This issue is caused by setting the body height to "auto" in this commit:

https://github.com/nextcloud/server/commit/92ab659a87755a223aa27e963e4a6317a5c979c6

**Comment by kesselb** [comment] 2020-11-08 17:02
Duplicate of https://github.com/nextcloud/server/issues/23236

**Closed by kesselb** 2020-11-08 17:02 UTC
Labels: 0. Needs triage, bug
