### ISSUE TITLE
[Bug]: Modified Date only shows in Minutes

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#47361] opened 2024-08-20 20:13 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Noticed this on NC 30 it no longer goes to hours after 60 min. 

![image](https://github.com/user-attachments/assets/2b941972-df07-4cf7-9c44-d440eba7e0ab)

### Steps to reproduce

Upgrade to Nc 30 RC1

### Expected behavior

Should show 1 hours etc after 60 min 

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2024-08-20 22:42
Duplicate of https://github.com/nextcloud/server/issues/46537

**Closed** 2024-08-20 22:42 UTC
Labels: bug, 0. Needs triage
