### ISSUE TITLE
[Bug]: updater.phar running too long

### ISSUE THREAD

**Issue by msviba** [nextcloud/server#43940] opened 2024-03-01 16:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Update server procedure needs soo much time. The time is increased when i have stored more files on server.

### Steps to reproduce

1. host 300GB files
2. try make update to newer NC version
3. steps backup and delete old files is too long (hours)

### Expected behavior

Update procedure will take minutes and not hours. Update procedure MUST NOT be depend on how many files is hosted. But now update time is increased by amount of hosted files.

Problem is in getRecursiveDirectoryIterator RecursiveIteratorIterator

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-03-02 14:14
Agreed but:

Duplicate of nextcloud/updater#507
And further covered in nextcloud/updater#519

:)

**Closed by joshtrichards** 2024-03-02 14:14 UTC
Labels: bug, 0. Needs triage, 28-feedback
