### ISSUE TITLE
Download a shared folder via actions -> download not working

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#16864] opened 2019-08-26 06:04 UTC
### Steps to reproduce
1. Create a folder in nextcloud and put some pdfs in this folder.
2. Share the folder read-only via share link
3. Open the share link and hit the checkbox before the folder. Than select actions and download.
![ActionsAndDownload](https://user-images.githubusercontent.com/15264981/63668517-a7e1cd00-c7d7-11e9-8b48-f9040f62adeb.PNG)

4. A file not found message displayed.
![grafik](https://user-images.githubusercontent.com/15264981/63668524-afa17180-c7d7-11e9-8c62-6306f8a5555a.png)

### Expected behaviour
Folder should be downloaded like using the "download all files" button.

### Actual behaviour
File not found message displayed.

### Server configuration

**Operating system**: Ubuntu 18.04.2 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:**  7.2.19

**Nextcloud version:**16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** official page

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - federation
  - files_automatedtagging
  - files_pdfviewer
  - files_retention
  - files_texteditor
  - nextcloud_announcements
  - sharepoint
  - survey_client
  - systemtags

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.COMPANYNAME.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.COMPANYNAME.de",
        "dbtype": "mysql",
        "version": "16.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "proxy": "http:\/\/192.168.1.19:8080",
        "skeletondirectory": "\/var\/www\/html\/nextcloud\/core\/COMPANYNAME",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "trashbin_retention_obligation": "auto,1",
        "versions_retention_obligation": "disabled",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                  |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                |
| homeFolderNamingRule          | attr:sAMAccountName                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                                                |
| ldapAgentName                 | CN=Empagent\, Empirum,OU=IT,OU=Benutzer,OU=HKG,OU=COMPANY,DC=COMPANYad,DC=de                                                                       |
| ldapAgentPassword             | ***                                                                                                                                              |
| ldapAttributesForGroupSearch  |                                                                                                                                                  |
| ldapAttributesForUserSearch   |                                                                                                                                                  |
| ldapBackupHost                |                                                                                                                                                  |
| ldapBackupPort                |                                                                                                                                                  |
| ldapBase                      | DC=COMPANYad,DC=de                                                                                                                                |
| ldapBaseGroups                | DC=COMPANYad,DC=de                                                                                                                                |
| ldapBaseUsers                 | DC=COMPANYad,DC=de                                                                                                                                |
| ldapCacheTTL                  | 600                                                                                                                                              |
| ldapConfigurationActive       | 1                                                                                                                                                |
| ldapDefaultPPolicyDN          |                                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                                  |
| ldapEmailAttribute            | mail                                                                                                                                             |
| ldapExperiencedAdmin          | 0                                                                                                                                                |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                  |
| ldapExpertUUIDUserAttr        |                                                                                                                                                  |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                   |
| ldapExtStorageHomeAttribute   |                                                                                                                                                  |
| ldapGidNumber                 | gidNumber                                                                                                                                        |
| ldapGroupDisplayName          | cn                                                                                                                                               |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                                                                        |
| ldapGroupFilterGroups         |                                                                                                                                                  |
| ldapGroupFilterMode           | 0                                                                                                                                                |
| ldapGroupFilterObjectclass    | group                                                                                                                                            |
| ldapGroupMemberAssocAttr      | member                                                                                                                                           |
| ldapHost                      | 192.168.1.186                                                                                                                                    |
| ldapIgnoreNamingRules         |                                                                                                                                                  |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=owncloud,OU=Gruppen,OU=HKG,OU=COMPANY,DC=COMPANYad,DC=de)(primaryGroupID=10334))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                  |
| ldapLoginFilterEmail          | 0                                                                                                                                                |
| ldapLoginFilterMode           | 0                                                                                                                                                |
| ldapLoginFilterUsername       | 1                                                                                                                                                |
| ldapNestedGroups              | 0                                                                                                                                                |
| ldapOverrideMainServer        |                                                                                                                                                  |
| ldapPagingSize                | 500                                                                                                                                              |
| ldapPort                      | 389                                                                                                                                              |
| ldapQuotaAttribute            |                                                                                                                                                  |
| ldapQuotaDefault              |                                                                                                                                                  |
| ldapTLS                       | 0                                                                                                                                                |
| ldapUserAvatarRule            | default                                                                                                                                          |
| ldapUserDisplayName           | sAMAccountName                                                                                                                                   |
| ldapUserDisplayName2          |                                                                                                                                                  |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=owncloud,OU=Gruppen,OU=HKG,OU=COMPANY,DC=COMPANYad,DC=de)(primaryGroupID=10334))))                         |
| ldapUserFilterGroups          | owncloud                                                                                                                                         |
| ldapUserFilterMode            | 0                                                                                                                                                |
| ldapUserFilterObjectclass     | user                                                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                                                             |
| ldapUuidUserAttribute         | auto                                                                                                                                             |
| turnOffCertCheck              | 0                                                                                                                                                |
| turnOnPasswordChange          | 0                                                                                                                                                |
| useMemberOfToDetectMembership | 1                                                                                                                                                |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Mozilla Firefox 68.0.1

**Operating system:** Windows 10 Build 1903

**Comment by szaimen** [comment] 2021-05-26 11:03
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-26 11:03 UTC
Labels: 0. Needs triage, bug
