### ISSUE TITLE
[Bug]: Order of file list not reflected by paging actions in viewer

### ISSUE THREAD

**Issue by pspitzli** [nextcloud/server#33089] opened 2022-07-01 20:34 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The currently configured sort order of a file list is not being reflected by an opened viewer, when paging through the next or previous files using the according arrow buttons.

### Steps to reproduce

In the files app
1. Create a folder containing 3 images
2. Change the sort order to: Name, Descending
3. Open the viewer by clicking on the 2nd image in the list
4. Go to the next image by using the arrow-button on the right in the viewer.
=> The next image according to sort order (Name, Ascending) will be displayed instead of the next image according to the currently configured sort order.

This can be reproduced using any other sort order than (Name, Ascending).

### Expected behavior

The next / previous button in an open viewer respects the sort order of the file list it was opened from.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.16.0
  - calendar: 3.4.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - duplicatefinder: 0.0.14
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_photospheres: 1.24.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - integration_google: 1.0.6
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.1.10
  - metadata: 0.16.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - previewgenerator: 5.0.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quota_warning: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - accessibility: 1.9.0
  - admin_audit
  - circles: 23.0.0
  - encryption: 2.11.0
  - files_external: 1.15.0
  - firstrunwizard: 2.13.0
  - recommendations: 1.3.0
  - user_ldap
  - weather_status: 1.3.0
```

**Comment by szaimen** [comment] 2022-07-01 21:21
Duplicate of https://github.com/nextcloud/viewer/issues/390

**Closed by szaimen** 2022-07-01 21:21 UTC
Labels: bug, 0. Needs triage

**Comment by pspitzli** [comment] 2022-07-02 05:26
Ah sorry. I wasn't aware of the separate repo for the viewer.
