### ISSUE TITLE
Wrong "toggle grid button" on share via link

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12403] opened 2018-11-11 07:34 UTC
- share a video via link
- set "hide download"
- open link: https://nextcloud.kaminsky.me/index.php/s/rAfBKcEnNGSiAwd
- see button on top left

**Comment by violoncelloch** [comment] 2018-11-11 08:03
duplicate of #12356 ?

**Comment by MorrisJobke** [comment] 2018-11-11 22:29
> duplicate of #12356 ?

Yep

**Closed by MorrisJobke** 2018-11-11 22:29 UTC
Labels: 15-feedback, bug, feature: sharing
