### ISSUE TITLE
"Hide download" option of public shares causes reload

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#19348] opened 2020-02-07 11:35 UTC
### Steps to reproduce
1. Create a folder
2. Upload a few images
3. Share the folder as public link  with "Hide download" (see https://nextcloud.com/blog/secure-view-prevent-your-shared-files-from-getting-downloaded/ for description)
4. Visit the public link

### Expected
You can view the files but there is no download button in the top bar or in the `…` menu.

### Actually
When you click on an item the page is reloaded

**Comment by nickvergessen** [comment] 2020-02-07 11:37
PS: since this works rather decent with pdfs e.g. I think it's caused by the viewer/photos app? There is also a webdav propfind taking place before the reload

cc @skjnldsv

**Comment by skjnldsv** [comment] 2020-02-07 12:30
photos and viewer are not in public pages :woman_shrugging:

**Comment by neufeind** [comment] 2020-02-07 14:11
I think #19019 is related, which also assumes it is (was?) possible to share a gallery of photos.

**Comment by helmo** [comment] 2020-04-20 19:08
@nickvergessen Can I assume you were talking about sharing a single pdf in your comment above? 

When sharing a folder that contains a pdf it opens the pdf viewer but fails to load the file when clicked (Firefox 75, Ubuntu). This seems similar to the video issue. 

I noticed this in 18.0.3 (the video fix seems to have been backported to be included in 18.0.2)

**Comment by szaimen** [comment] 2021-05-31 13:00
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 13:00 UTC
Labels: 0. Needs triage, bug
