### ISSUE TITLE
LDAP Groups on Nextcloud 18 : buggy ?

### ISSUE THREAD

**Issue by dea-75** [nextcloud/server#20122] opened 2020-03-23 20:48 UTC
Hi All !!

I use on Debian 10 two Nextcloud servers (Apache 2.4 Debian 10, PHP 7.3 FPM, PostgreSQL).
When Nextcloud runs on 17.0.2-17.0.3 LDAP users and groups works correctly, now I've upgraded to Nextcloud 18.0.2 (and today 18.0.3), I show old LDAP users and groups, but, If I try to add an AD group, correctly I show it in LDAP filter, with the same metod used in the old Nextcloud version, when I list groups, the new LDAP group is not visible (in the users and group lists, not in the LDAP configuration).

There are problems on Nextcloud 18 and LDAP groups ?

Very thanks
Luca

**Comment by N4IR0** [comment] 2020-03-24 06:04
Could be the same issue as in #19970, the fix should be available in 18.0.4

**Comment by kesselb** [comment] 2020-03-24 08:43
Closing as duplicate of #19970

**Closed by kesselb** 2020-03-24 08:43 UTC
Labels: 0. Needs triage, bug
