### ISSUE TITLE
Meatballs menu for sharing

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#26981] opened 2021-05-14 13:05 UTC
### Steps to reproduce

1. Upload multiple files to the "Files" application.
2. Scroll the window with the files, e.g. to the last file.
3. Share the file with the user.
4. Select file details.
5. Select the "Sharing" tab.
6. Click on the Meatballs menu.

The menu for Meatballs appears partially hidden, which follows as you scroll through the file window.

![obraz](https://user-images.githubusercontent.com/47037905/118274119-09266400-b4c5-11eb-91d7-e5908cd6ccfc.png)

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

### Client configuration
**Browser:**
Firefox 88.0.1

**Comment by pascalbrax** [comment] 2021-05-19 09:07
Hi, I want to add to this issue with this video: https://streamable.com/xbf16w

It shows that when you have plenty of files or folders, the sharing menu is hidden way up the screen.

**Nextcloud:** 
Version 21.0.1

**Browser:**
Google Chrome 90

**Comment by szaimen** [comment] 2021-07-06 15:35
Duplicate of https://github.com/nextcloud/server/issues/23872

**Closed by szaimen** 2021-07-06 15:35 UTC
Labels: 0. Needs triage, bug
