### ISSUE TITLE
user:delete doesn't delete ([OC\User\NoUserException] .. is not a valid user anymore)

### ISSUE THREAD

**Issue by tohn** [nextcloud/server#5292] opened 2017-06-07 16:51 UTC
### Steps to reproduce
1. Configure LDAP / AD integration
2. Import all users (even disabled ones) in the LDAP tree
3. Change the user query in the settings and only allow/import 1/3 of the users in the LDAP tree
4. Try to cleanup the LDAP users as described [here](https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_auth_ldap_cleanup.html)

### Expected behaviour
With `sudo -u apache ./occ ldap:show-remnants` I can list all users to cleanup. Then I use `sudo -u apache ./occ ldap:show-remnants | while read pipe user line ; do echo $user ; sudo -u apache ./occ user:delete $user ; done` to clean up all users in a single command.
The users should then be deleted.

### Actual behaviour
I get this error:
```sudo -u apache ./occ user:delete 8D1A13BA-EF1B-4D1D-82A6-C55E7C2F5BF4
                                                                    
  [OC\User\NoUserException]                                         
  8D1A13BA-EF1B-4D1D-82A6-C55E7C2F5BF4 is not a valid user anymore  

```
If I check the user first with `sudo -u apache ./occ ldap:check-user` I get this output:
```
The user does not exists on LDAP anymore.
Clean up the user's remnants by: ./occ user:delete "8D1A13BA-EF1B-4D1D-82A6-C55E7C2F5BF4"
```
and then use the exact syntax with `"`, I still get the error above.

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache/2.4.6

**Database:** mysql 5.7.18

**PHP version:** 7.1.5

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** manual from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bookmarks
  - comments
  - federation
  - files_external
  - survey_client
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "xxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx",
            "xxx",
            "xxx"
        ],
        "datadirectory": "\/var\/www\/vhosts\/xxx\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "xxx",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "trusted_proxies": [
            "127.0.0.1"
        ],
        "overwriteprotocol": "https",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/xxx",
        "overwritecondaddr": "^127\\.0\\.0\\.1$"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                          |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                            |
| hasPagedResultSupport         |                                                                                                                              |
| homeFolderNamingRule          |                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                            |
| ldapAgentName                 | CN=Ldap Read-Only,CN=Users,DC=xxx,DC=org                                                                                     |
| ldapAgentPassword             | ***                                                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                                                              |
| ldapAttributesForUserSearch   |                                                                                                                              |
| ldapBackupHost                |                                                                                                                              |
| ldapBackupPort                |                                                                                                                              |
| ldapBase                      | DC=xxx,DC=org                                                                                                                |
| ldapBaseGroups                | OU=Groups,DC=xxx,DC=org                                                                                                      |
| ldapBaseUsers                 | OU=User,DC=xxx,DC=org                                                                                                        |
| ldapCacheTTL                  | 600                                                                                                                          |
| ldapConfigurationActive       | 1                                                                                                                            |
| ldapDefaultPPolicyDN          |                                                                                                                              |
| ldapDynamicGroupMemberURL     |                                                                                                                              |
| ldapEmailAttribute            | mail                                                                                                                         |
| ldapExperiencedAdmin          | 1                                                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                                                              |
| ldapExpertUsernameAttr        |                                                                                                                              |
| ldapGidNumber                 | gidNumber                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                           |
| ldapGroupFilter               | (&(objectclass=group)(memberof=CN=nextcloud,OU=res,OU=Groups,DC=xxx,DC=org))                                                 |
| ldapGroupFilterGroups         | nextcloud                                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                                            |
| ldapGroupFilterObjectclass    | group                                                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                                                       |
| ldapHost                      | ldaps://xxx                                                                                                                  |
| ldapIgnoreNamingRules         |                                                                                                                              |
| ldapLoginFilter               | (&(&(objectclass=user)(memberof=CN=nextcloud,OU=res,OU=Groups,DC=xxx,DC=org))(samaccountname=%uid))                          |
| ldapLoginFilterAttributes     |                                                                                                                              |
| ldapLoginFilterEmail          | 0                                                                                                                            |
| ldapLoginFilterMode           | 0                                                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                                                            |
| ldapNestedGroups              | 0                                                                                                                            |
| ldapOverrideMainServer        |                                                                                                                              |
| ldapPagingSize                | 500                                                                                                                          |
| ldapPort                      | 9636                                                                                                                         |
| ldapQuotaAttribute            |                                                                                                                              |
| ldapQuotaDefault              |                                                                                                                              |
| ldapTLS                       | 0                                                                                                                            |
| ldapUserDisplayName           | displayname                                                                                                                  |
| ldapUserDisplayName2          |                                                                                                                              |
| ldapUserFilter                | (&(&(objectclass=user)(memberof=CN=nextcloud,OU=res,OU=Groups,DC=xxx,DC=org))(!(userAccountControl=514)))                    |
| ldapUserFilterGroups          |                                                                                                                              |
| ldapUserFilterMode            | 0                                                                                                                            |
| ldapUserFilterObjectclass     |                                                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                                                         |
| turnOffCertCheck              | 0                                                                                                                            |
| turnOnPasswordChange          | 0                                                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                                                            |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------+
```
</details>

**Comment by blizzz** [comment] 2017-06-12 11:19
Duplicate of https://github.com/nextcloud/server/issues/4117

**Closed by blizzz** 2017-06-12 11:19 UTC
