### ISSUE TITLE
NC21 WEB UI files clicking on unread comment icon leads to "Feler beim laden der Daten"

### ISSUE THREAD

**Issue by roadrunnerjb** [nextcloud/server#26374] opened 2021-03-30 11:34 UTC
### Steps to reproduce
if a file or folder has one or more unread comments an icon is shown. Clicking on this "unread comment" icon does show "Error loading data".

### Expected behaviour
comments should be shown. Via details -> comments the comments are shown.

### Server configuration

**Operating system:**
debain 10.9

**Web server:**
apache 2.4
 
**Database:**
mariadba
**PHP version:**
php 7.4
**Nextcloud version:** (see Nextcloud admin page)
21.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
update from 20

**Comment by osm-frasch** [comment] 2021-05-31 13:32
I have exactly the same problem. This worked up to NC 21.0.1

**When a user comments on a file or folder in the Files app, people who have the share and see the comment icon can no longer click on it. See screenshot. Does anyone have the same problem or a clue about this?** 

If you click on the "Details", the right column opens correctly and the comment can be read. 
The comment icon was still clickable under 21.0.1

[/details]

Nextcloud version _(eg, 20.0.5)_: `21.0.2`
Operating system and version _(eg, Ubuntu 20.04)_: ` 	Linux 4.15.0-142-generic x86_64`
Apache or nginx version _(eg, Apache 2.4.25)_:  `KVM RHEL 7.6.0 PC `
PHP version _(eg, 7.4)_: `7.3.16`

Is this the first time you've seen this error? _(Y/N)_: Yes, since NC Version 21.0.2

Steps to replicate it:

1. Create a comment on a shared file
2. The user with whom the file was shared cannot click on the icon.


The output of your Nextcloud log in **Admin > Logging**:

No real idea about this. This was the last issue of the admin logger
```
	Error: sys_getloadavg() has been disabled for security reasons at /data/www/dummy.de/apps/serverinfo/lib/SystemStatistics.php#212
    <<closure>>
    OC\Log\ErrorHandler::onError(2, "sys_getload ... s", "/data/www/h ... p", 212, [])
    /data/www/dummy.de/apps/serverinfo/lib/SystemStatistics.php - line 212:
    sys_getloadavg()
    /data/www/dummy.de/apps/serverinfo/lib/SystemStatistics.php - line 68:
    OCA\ServerInfo\SystemStatistics->getProcessorUsage()
    /data/www/dummy.de/apps/serverinfo/lib/Controller/PageController.php - line 57:
    OCA\ServerInfo\SystemStatistics->getSystemStatistics()
    /data/www/dummy.de/lib/private/AppFramework/Http/Dispatcher.php - line 218:
    OCA\ServerInfo\Controller\PageController->update("*** sensiti ... *")
    /data/www/dummy.de/lib/private/AppFramework/Http/Dispatcher.php - line 127:
    OC\AppFramework\Http\Dispatcher->executeController(OCA\ServerIn ... {}, "update")
    /data/www/dummy.de/lib/private/AppFramework/App.php - line 157:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\ServerIn ... {}, "update")
    /data/www/dummy.de/lib/private/Route/Router.php - line 302:
    OC\AppFramework\App::main("OCA\\Server ... r", "update", OC\AppFramew ... {}, { _route: "s ... "})
    /data/www/dummy.de/lib/base.php - line 993:
    OC\Route\Router->match("/apps/serverinfo/update")
    /data/www/dummy.de/index.php - line 37:
    OC::handleRequest() 

```
The output from the Firefox console:

Uncaught (in promise) Error: Error: Request failed with status code 404
    r Sidebar.vue:411
    l ncvuecomponents.js:320
    _invoke ncvuecomponents.js:320
    e ncvuecomponents.js:320
    j sidebar.js:1
    a sidebar.js:1
    promise callback*j sidebar.js:1
    s sidebar.js:1
    P sidebar.js:1
    P sidebar.js:1
    open Sidebar.vue:382
    actionHandler filesplugin.js:106
    action merged-index.js:2961
    _renderInlineAction merged-index.js:3264
    jQuery 2
        dispatch
        handle
Sidebar.vue:411
    j sidebar.js:1
    a sidebar.js:1
    (Async: promise callback)
    j sidebar.js:1
    s sidebar.js:1
    P sidebar.js:1
    P sidebar.js:1
    open Sidebar.vue:382
    open self-hosted:1179
    actionHandler filesplugin.js:106
    action merged-index.js:2961
    _renderInlineAction merged-index.js:3264
    jQuery 2

![screenshot-comments-bug|690x315](upload://nUsugHuC4NQXmJRuIpOAhgWNhPH.png)

**Comment by szaimen** [comment] 2021-07-07 10:11
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-07-07 10:11 UTC
Labels: 0. Needs triage, bug

**Comment by osm-frasch** [comment] 2021-07-07 11:34
We have just tested it again under our new NC version 21.0.3. The error is still exactly the same. 
If you click on the comment icon, the right column opens and the following message is displayed: "Error loading file data". Everything is the same as described above.

We will not upgrade to NC 22. After the last unintentional upgrade to version 21, we have had to deal with a whole series of bugs...some of which still exist today. I will wait until NC 22.0.3 is out. Before then, it's too risky for me.
