### ISSUE TITLE
Contacts synchronized to MacOS or iPhone generate error unserialize(): Error at offset 40 of 43 bytes at /var/www/html/apps/dav/lib/DAV/CustomPropertiesBackend.php#458

### ISSUE THREAD

**Issue by northben** [nextcloud/server#42798] opened 2023-12-14 01:14 UTC
### Describe the bug

Any time a contact is created or modified on Mac or iPhone it generates the following error in the Nextcloud Log

```
{
    "reqId": "Ukr9CYzhhICV2cgZxVii",
    "level": 3,
    "time": "2023-12-14T01:03:50+00:00",
    "remoteAddr": "172.27.0.3",
    "user": "northben",
    "app": "PHP",
    "method": "PROPFIND",
    "url": "/remote.php/dav/addressbooks/users/my_username/",
    "message": "unserialize(): Error at offset 40 of 43 bytes at /var/www/html/apps/dav/lib/DAV/CustomPropertiesBackend.php#458",
    "userAgent": "iOS/17.1.2 (21B101) dataaccessd/1.0",
    "version": "27.1.4.1",
    "data": {
        "app": "PHP"
    },
    "id": "657a549186010"
}
```

### Steps to reproduce

1. Create a contact on Nextcloud web interface, or in MacOS/iPhone
2. Wait a moment for the contact to sync
3. See the error in the Nextcloud log

### Expected behavior

the error should not be generated. I haven't seen any other effect of this error.

### Actual behavior

the error is generated

### Contact version

5.5.0

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Nextcloud AIO v7.8.1

**Comment by solracsf** [comment] 2024-02-06 09:02
Closing as duplicate of https://github.com/nextcloud/server/issues/37754#issuecomment-1613361252
See also https://help.nextcloud.com/t/unserialize-error-at-offset-40-of-43-bytes-at-config-www-nextcloud-apps-dav-lib-dav-custompropertiesbackend-php-403/166240

**Closed by solracsf** 2024-02-06 09:02 UTC
Labels: bug, feature: dav, 0. Needs triage, feature: carddav, feature: contacts, 27-feedback
