### ISSUE TITLE
slow trashbin expire run

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#18960] opened 2020-01-17 15:36 UTC
The database in use has some 2 million files, and had 66000 files in the trashbin which had piled up since expiry was disabled for a long time (purposefully).

After expiry was enabled ('trashbin_retention_obligation' => "7,30"), the manual run took a very long time. In parallel, the cron job tried to expire the files as well, but took too long, so the next run would try the same and so on.

I fixed this by starting the expiry manually (occ trashbin:expire), and disabled the automatic expiry in config.php in the meantime to prevent cron from intervening. This ultimately succeeded, but took about 30 hours on decent machines. Whilst running, the PostgreSQL12 database showed constant high CPU load, resulting from many "SELECT ... FROM oc_filecache WHERE storage=$ AND name ILIKE $"

I had a look at files_trashbin Commands/ExpireTrash.php, but couldn't see the reason why this query should be issued all over again. The PostgreSQL Activity view won't show the parameters, so I can't tell if the name parameter is better than '%'. If it starts with characters, the Cache::select method, which seems to be called by trashbin:expire, could be improved by using lower(name) LIKE lower($) and creating an index on (storage, lower(name)). Still, I couldn't spot why expiry should use this method at all.

NC17 on Debian10/Apache2.4, PostgreSQL12 with plenty of RAM on dedicated server, no encryption or other file related apps.

**Comment by Dragon988** [comment] 2020-01-18 15:57
This is likely a database configuration issue. If I recall correctly binlog_commit_wait_use in particular can speed things up when set lower but will increase disk I/O significantly.

It has to do with how nextcloud polls the database.

Depending on how nextcloud processes deletions you may need to increase your PHP-FPM children/servers to speed things up as well.

**Comment by andreas-p** [comment] 2020-01-19 09:21
That binlog_commit_wait_use seems to be some MySQL stuff, I'm on PostgreSQL. No php-fpm instances shortages.
The issue seems to be NC code to hammer the server with full table scans again and again (maybe trying to update its cache?). This can't be fixed with database server configuration.

**Comment by Dragon988** [comment] 2020-01-19 18:30
Yes, it's a polling issue with the database iirc. Setting that setting among other things speeds up processing time.

There is a GitHub issue a bout slow preview generations which was also caused by the polling. You're likely looking at the same issue.
On Sunday, January 19, 2020 01:21 PST, andreas-p <notifications@github.com> wrote:
 
That binlog_commit_wait_use seems to be some MySQL stuff, I'm on PostgreSQL. No php-fpm instances shortages.
The issue seems to be NC code to hammer the server with full table scans again and again (maybe trying to update its cache?). This can't be fixed with database server configuration.

**Comment by fladi** [comment] 2020-12-08 23:49
I think i'm seeing the same issue on MariaDB. Our NC 19.0.5 installation has ~36 million records in `oc_filecache` and the query use in the trashbin expiration process is like this:

```
SELECT
	`filecache`.`fileid`,
	`storage`,
	`path`,
	`path_hash`,
	`filecache`.`parent`,
	`name`,
	`mimetype`,
	`mimepart`,
	`size`,
	`mtime`,
	`storage_mtime`,
	`encrypted`,
	`etag`,
	`permissions`,
	`checksum`,
	`metadata_etag`,
	`creation_time`,
	`upload_time`
FROM
	`oc_filecache` `filecache`
LEFT JOIN `oc_filecache_extended` `fe` ON
	`filecache`.`fileid` = `fe`.`fileid`
WHERE
	(`storage` = 170)
	AND (`name` COLLATE utf8mb4_general_ci LIKE 'Axin1_1844.pdb.v%.d1604930897')
```

The `LIKE` causes a full table scan for each query which takes around 20 seconds for 36 million records. I had to disable `trashbin_retention_obligation` and `versions_retention_obligation` in `config.php` to get the cronjob to finish. But this is not feasible for our installation.

**Comment by szaimen** [comment] 2021-06-18 12:54
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by diroots** [comment] 2021-10-05 14:20
@szaimen since one month, we are also facing this on the latest nc 20.0.12 version, with 27 millions entries in the filecache table

**Comment by szaimen** [comment] 2023-01-09 15:57
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:39 UTC
Labels: bug, needs info, 0. Needs triage, feature: trashbin
