### ISSUE TITLE
Create Group Managed By list that only is able to manage the membership of that group

### ISSUE THREAD

**Issue by WingsLikeEagles** [nextcloud/server#20399] opened 2020-04-09 21:41 UTC
It seems there is a lot of confusion with the words "group admin".  I have seen threads posted which imply they are sub-admins for the server.  I would like to suggest that we have a tag for groups name "managed by" which can have the users who have authority to change group membership.  This would allow people to move people in and out of their group without affecting the rest of the system and user accounts.

Thank you,
Justin

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skjnldsv** [comment] 2020-08-25 08:33
Also duplicate of https://github.com/nextcloud/server/issues/3630 :)

**Closed by skjnldsv** 2020-08-25 08:33 UTC
Labels: 0. Needs triage, enhancement
