### ISSUE TITLE
No calendar export possible, internal server error

### ISSUE THREAD

**Issue by valentingc** [nextcloud/server#3734] opened 2017-03-06 17:58 UTC
### Steps to reproduce
1. Go to Calendar
2. Try to export Calendar (a big one)

### Expected behaviour
A ics file should be downloaded.

### Actual behaviour
In the new tab that opens there is a error message, saying "Internal Server Error", followed by the local IP Adress and a request token.

In the log, I am getting the following exception:
<details>

```
Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied ""
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 453: Sabre\VObject\Document->createProperty('DTEND', NULL, Array)
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 234: Sabre\VObject\Parser\MimeDir->readProperty('DTEND;VALUE=;TZ...')
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 217: Sabre\VObject\Parser\MimeDir->parseLine('DTEND;VALUE=;TZ...')
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 181: Sabre\VObject\Parser\MimeDir->parseLine('DTEND;VALUE=;TZ...')
/volume1/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 89: Sabre\VObject\Parser\MimeDir->parseDocument()
/volume1/cloud/3rdparty/sabre/vobject/lib/Reader.php - line 46: Sabre\VObject\Parser\MimeDir->parse('BEGIN VCALENDAR...', 0)
/volume1/cloud/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 307: Sabre\VObject\Reader read('BEGIN VCALENDAR...')
/volume1/cloud/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 222: Sabre\CalDAV\ICSExportPlugin->mergeObjects(Array, Array)
/volume1/cloud/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php - line 151: Sabre\CalDAV\ICSExportPlugin->generateResponse('calendars/valen...', NULL, NULL, false, false, 'text/calendar', Array, Object(Sabre\HTTP\Response))
[internal function] Sabre\CalDAV\ICSExportPlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/volume1/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/volume1/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method GET', Array)
/volume1/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/volume1/cloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
/volume1/cloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
/volume1/cloud/remote.php - line 165: require_once('/volume1/cl...')
{main}
```
</details>
URL is: 
"/cloud/remote.php/dav/calendars/***USER***/kalender?export"

Something must be broken in this particular calendar. When I try it with a different user (with a mostly empty calendar) it works.

It is related to this error:
https://help.nextcloud.com/t/no-calendar-export-possible-11-0-0/7293/2

Maybe this issue report can help you guys somehow to fix this in a next NC release!

### Server configuration
**Operating system**:
Synology DSM 6.0.2

**Web server:**
Apache 2.2.31

**Database:**
MariaDB 5.5.53

**PHP version:** 7.0.15

**Nextcloud version:** (see Nextcloud admin page)
11.0.2 stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
update

**Where did you install Nextcloud from:** 
from your source

**Signing status:**
<details>
<summary>Signing status</summary>

`No errors have been found.`

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
  - user_saml
```

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        [shortened]
        "dbtype": "mysql",
        "version": "11.0.2.7",
        [shortened]
        "logtimezone": "UTC",
        "installed": true,
        "filesystem_check_changes": "0",
         [shortened]
        "theme": "",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:**
local

**Are you using encryption:** 
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
</details>

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing relevant found.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
See the exception above, nothing else.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
The only log the console shows is a Stylesheet error (multiple times Refused to load the script [...] because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

I don't think this matters in this case!
```
</details>

**Comment by nickvergessen** [comment] 2017-03-08 09:02
@rullzer another DTEND case, didn't you have a patch started for that somewhere?

**Comment by rullzer** [comment] 2017-03-10 07:29
Could you check your database and post the content of the oc_jobs table?

**Comment by valentingc** [comment] 2017-03-10 08:48
Sure: 
![image](https://cloud.githubusercontent.com/assets/26229513/23788429/a9bb6fd0-0576-11e7-84d3-79e991d8bacf.png)

**Comment by koebi001** [comment] 2017-03-17 15:40
I do get the same error. Is there anything I could provide to help solving this?

**Comment by tribut** [comment] 2017-03-18 07:43
Seeing the same thing ("Internal server error" when exporting one calendar - others work fine). Sync apparently is not affected (Android, Gnome). Let me know if you need any input.

**Comment by valentingc** [comment] 2017-03-18 11:18
I can confirm that sync is not affected. Only the export function in the browser.

**Comment by tribut** [comment] 2017-03-19 10:31
Possible duplicate of https://github.com/nextcloud/server/issues/2741

**Closed** 2017-03-20 11:21 UTC
Labels: feature: dav
