### ISSUE TITLE
Share calendars-from-links to caldav and make it shareable to other users.

### ISSUE THREAD

**Issue by Eric-Sparks** [nextcloud/server#24787] opened 2020-12-21 01:53 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Calendars imported using a link aren't shared on caldav and aren't shareable to other users on Nextcloud.

**Describe the solution you'd like**
These imported calendars should be seen on caldav and should also be shareable to other users on Nextcloud.

**Describe alternatives you've considered**
One could subscribe to these external calendars in numerous places.

**Comment by szaimen** [comment] 2021-06-18 14:04
I think this is a duplicate of https://github.com/nextcloud/server/issues/17754

**Closed by szaimen** 2021-06-18 14:04 UTC
Labels: 0. Needs triage, enhancement
