### ISSUE TITLE
OCP\Files\NotFoundException: 

### ISSUE THREAD

**Issue by andreasjacobsen93** [nextcloud/server#5204] opened 2017-05-31 21:56 UTC
### Steps to reproduce
Setup a new install of NextCloud and saw the error in the log.

### Server configuration

**Operating system**: Ubuntu 17.04

**Web server:** Apache 2.4.25

**Database:** MySQL 5.7.18

**PHP version:** PHP 7.0

**Nextcloud version:** 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** nextcloud.com download

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.1.4
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "occuxv52jfv8",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "ldap" namespace.
```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
/var/www/cloud/lib/private/Files/Node/Node.php - line 217: OC\Files\Node\Node->getFileInfo()
/var/www/cloud/lib/private/Files/Node/Node.php - line 117: OC\Files\Node\Node->getPermissions()
/var/www/cloud/lib/private/Files/Node/Folder.php - line 336: OC\Files\Node\Node->checkPermissions(8)
/var/www/cloud/lib/private/Files/SimpleFS/SimpleFolder.php - line 65: OC\Files\Node\Folder->delete()
/var/www/cloud/apps/dav/lib/CardDAV/PhotoCache.php - line 244: OC\Files\SimpleFS\SimpleFolder->delete()
/var/www/cloud/apps/dav/lib/AppInfo/Application.php - line 121: OCA\DAV\CardDAV\PhotoCache->delete('1', 'Database andrea...')
[internal function] OCA\DAV\AppInfo\Application->OCA\DAV\AppInfo\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
/var/www/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 174: call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
/var/www/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 43: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\GenericEvent))
/var/www/cloud/apps/dav/lib/CardDAV/CardDavBackend.php - line 669: Symfony\Component\EventDispatcher\EventDispatcher->dispatch('\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\GenericEvent))
/var/www/cloud/apps/dav/lib/CardDAV/SyncService.php - line 284: OCA\DAV\CardDAV\CardDavBackend->updateCard('1', 'Database andrea...', 'BEGIN VCARD\r\nVE...')
/var/www/cloud/apps/dav/lib/AppInfo/Application.php - line 131: OCA\DAV\CardDAV\SyncService->updateUser(Object(OC\User\User))
[internal function] OCA\DAV\AppInfo\Application->OCA\DAV\AppInfo\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), 'OC\\AccountManag...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
/var/www/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 174: call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\GenericEvent), 'OC\\AccountManag...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
/var/www/cloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 43: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OC\\AccountManag...', Object(Symfony\Component\EventDispatcher\GenericEvent))
/var/www/cloud/lib/private/Accounts/AccountManager.php - line 111: Symfony\Component\EventDispatcher\EventDispatcher->dispatch('OC\\AccountManag...', Object(Symfony\Component\EventDispatcher\GenericEvent))
/var/www/cloud/settings/Controller/UsersController.php - line 801: OC\Accounts\AccountManager->updateUser(Object(OC\User\User), Array)
/var/www/cloud/settings/Controller/UsersController.php - line 734: OC\Settings\Controller\UsersController->saveUserSettings(Object(OC\User\User), Array)
[internal function] OC\Settings\Controller\UsersController->setUserSettings('contacts', 'andreas', 'contacts', '', 'private', 'andreasjacobsen...', 'contacts', '', 'private', '', 'private', '', 'private')
/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\UsersController), 'setUserSettings')
/var/www/cloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\UsersController), 'setUserSettings')
/var/www/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'setUserSettings', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/cloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/cloud/lib/base.php - line 1000: OC\Route\Router->match('/settings/users...')
/var/www/cloud/index.php - line 40: OC handleRequest()
{main}
```
</details>

**Comment by patschi** [comment] 2017-06-01 07:26
Hi, please take some time providing more info by filling out the [issue template](https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md) when creating an new issue. Else no one will likely be able to reproduce or understand your exact problem and it may never get fixed.

**Comment by andreasjacobsen93** [comment] 2017-06-01 07:35
After setting up a completely new fresh instance of NC, I got the above error in the log.

Running Ubuntu 17.04, with LAMP and Redis.

**Comment by luclis** [comment] 2017-09-06 21:01
Got the same thing : in short ; when I create an new user, he can't logging cause the directory /var/www/data/<USER>/files isn't create. 

### Steps to reproduce
1. Fresh install 
2. Configure ldap (don't know if it's matter)
3. Login with an new account on the LDAP

### Expected behaviour
The account should open the <DOMAIN>/apps/files/ page.

### Actual behaviour
An error page say internal error.

### Server configuration

**Operating system**: Debian 9.1 
**Web server:** nginx 1.13.4-1 
**Database:** MariaDB 10.1.26
**PHP version:** php7.0-fpm 7.0.19-1
**Nextcloud version:** 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**Fresh installl
**Where did you install Nextcloud from:** source
**Signing status:**
<details>
<summary>Signing status</summary>
```No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_snapshots: 0.1.1
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.5.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.1
  - ownbackup: 17.5.0
  - ownpad: 0.5.10
  - password_policy: 1.2.2
  - phonetrack: 0.0.1
  - provisioning_api: 1.2.0
  - ransomware_protection: 1.0.3
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
  "system": {
        "instanceid": "ID",
        "passwordsalt": ,
        "secret": ,
        "trusted_domains": [
            "DOMAIN.NAME",
            "NAME",
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "https:\/\/DOMAIN.NAME",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "DB",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": ,
        "dbpassword": ,
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
)
</details>

**Are you using external storage, if yes which one:** local 
**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP on samba4

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                         |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                       |
| hasPagedResultSupport         |                                                                                                                                                         |
| homeFolderNamingRule          |                                                                                                                                                         |
| lastJpegPhotoLookup           | 0                                                                                                                                                       |
| ldapAgentName                 | <ADMIN>                                                                                                              |
| ldapAgentPassword             | ****                                                                                                                                                     |
| ldapAttributesForGroupSearch  |                                                                                                                                                         |
| ldapAttributesForUserSearch   |                                                                                                                                                         |
| ldapBackupHost                |                                                                                                                                                         |
| ldapBackupPort                |                                                                                                                                                         |
| ldapBase                      | DC=luclis,DC=xyz                                                                                                                                        |
| ldapBaseGroups                | <ldapBase>                                                                                                                                        |
| ldapBaseUsers                 | <ldapBase>                                                                                                                                        |
| ldapCacheTTL                  | 5                                                                                                                                                       |
| ldapConfigurationActive       | 1                                                                                                                                                       |
| ldapDefaultPPolicyDN          |                                                                                                                                                         |
| ldapDynamicGroupMemberURL     |                                                                                                                                                         |
| ldapEmailAttribute            | mail                                                                                                                                                    |
| ldapExperiencedAdmin          | 0                                                                                                                                                       |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                         |
| ldapExpertUUIDUserAttr        |                                                                                                                                                         |
| ldapExpertUsernameAttr        | samaccountname                                                                                                                                          |
| ldapGidNumber                 | gidNumber                                                                                                                                               |
| ldapGroupDisplayName          | cn                                                                                                                                                      |
| ldapGroupFilter               |                                                                                                                                                         |
| ldapGroupFilterGroups         |                                                                                                                                                         |
| ldapGroupFilterMode           | 0                                                                                                                                                       |
| ldapGroupFilterObjectclass    |                                                                                                                                                         |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                  |
| ldapHost                      | ldaps://localhost                                                                                                                                       |
| ldapIgnoreNamingRules         |                                                                                                                                                         |
| ldapLoginFilter               | <FILTER> |
| ldapLoginFilterAttributes     |                                                                                                                                                         |
| ldapLoginFilterEmail          | 0                                                                                                                                                       |
| ldapLoginFilterMode           | 1                                                                                                                                                       |
| ldapLoginFilterUsername       | 1                                                                                                                                                       |
| ldapNestedGroups              | 0                                                                                                                                                       |
| ldapOverrideMainServer        |                                                                                                                                                         |
| ldapPagingSize                | 500                                                                                                                                                     |
| ldapPort                      | <PORT>                                                                                                                                                     |
| ldapQuotaAttribute            |                                                                                                                                                         |
| ldapQuotaDefault              |                                                                                                                                                         |
| ldapTLS                       | 0                                                                                                                                                       |
| ldapUserDisplayName           | cn                                                                                                                                                      |
| ldapUserDisplayName2          |                                                                                                                                                         |
| ldapUserFilter                | <FILTER>
| ldapUserFilterGroups          | <GROUP FILTER>                                                                                                                                      |
| ldapUserFilterMode            | 0                                                                                                                                                       |
| ldapUserFilterObjectclass     | user                                                                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                                                                    |
| ldapUuidUserAttribute         | auto                                                                                                                                                    |
| turnOffCertCheck              | 0                                                                                                                                                       |
| turnOnPasswordChange          | 0                                                                                                                                                       |
| useMemberOfToDetectMembership | 1                                                                                                                                                       |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:** Firefox 55.0.3

**Operating system:** WIN 10 15063.540

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"t4qficfJTARjzaQW6uyR","level":3,"time":"2017-09-06T20:45:15+00:00","remoteAddr":"<IP>","user":"<USER>","app":"index","method":"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(131): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.2.0"}
</details>

**Comment by bes1002t** [comment] 2018-01-06 23:05
Hi, 

I have the exact same issue. Installed Nextcloud and created the first user (admin). Everything was working well and I decided to create a normal user without admin permissions. Afterwards I tried to login as this new user and I got the same error like the issue creator. 

Got this issue in my nextcloud log file: 
{"reqId":"1hSTWZHd9R7IO8NbuwYU","level":3,"time":"2018-01-07T00:03:51+01:00","remoteAddr":"192.168.178.28","user":"Ben","app":"index","method":"GET","url":"\/belial\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nginx\\\/www\\\/belial\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(131): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/home\\\/nginx\\\/www\\\/belial\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/base.php(990): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/home\\\/nginx\\\/www\\\/belial\\\/index.php(37): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":544}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"13.0.0.8"}
{"reqId":"kFKS9QNdczmKThTZMKjp","level":3,"time":"2018-01-07T00:04:02+01:00","remoteAddr":"192.168.178.28","user":"Ben","app":"index","method":"GET","url":"\/belial\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nginx\\\/www\\\/belial\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(131): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/home\\\/nginx\\\/www\\\/belial\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/base.php(990): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/home\\\/nginx\\\/www\\\/belial\\\/index.php(37): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/home\\\/nginx\\\/www\\\/belial\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":544}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"13.0.0.8"}

If there is a better way to format this error message please let me know.

**Comment by blizzz** [comment] 2018-03-01 22:11
Could be a duplicate of https://github.com/nextcloud/server/issues/5204

**Comment by blizzz** [comment] 2018-03-01 22:34
can you confirm that for the failing user, a folder in data/ exists, but a subfolder "files" is missing?

**Comment by blizzz** [comment] 2018-03-01 22:59
cc @icewind1991

**Comment by blizzz** [comment] 2018-03-02 11:27
@andreasjacobsen93 @luclis @bes1002t also, is the data folder located on the native filesystem, a mount, or something else?

**Comment by cogliostro** [comment] 2018-10-24 12:01
Any news on this issue. Same experience on nextcloud 13.0.7. createUser creates the user folder and the subfolder cache. The folders files, uploads, files_trashbin are missing.

**Comment by andreasjacobsen93** [comment] 2018-10-24 15:02
> is the data folder located on the native filesystem, a mount, or something else?

On a mounted hdd

**Comment by mirokymac** [comment] 2018-11-26 07:19
enconter this issue today.
cd to `/path/to/nextcloud` could not found `./files`.
after mkdir and chown issue fixed.

**Comment by cyBea** [comment] 2019-01-15 23:04
I can cofirm this bug: Fresh install, admin-user works fine, next (non-admin-user) cannot login. data-directory is not under docroot but on same level:

    /var/www/nextcloud/htdocs
    /var/www/nextcloud/data

The latter has already `<admin>`, `appdata_ocXXXXXX`, `files_external`, `<username>`, `__groupfolder`, `index.html`, `nextcloud.log`. After creating

    /var/www/nextcloud/data/files

login works.

# Server configuration
**Operating system:** Debian 9.6
**Web server:** nginx 1.10.3-1+deb9u2
**Database:** MariaDB 10.1.37-0+deb9u1
**PHP version:** php7.0-fpm 7.0.33-0+deb9u1
**Nextcloud version:** 15.0.2

## apps
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - announcementcenter: 3.4.0
  - apporder: 0.6.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - user_ldap

**Comment by stone212** [comment] 2019-01-16 03:33
@cyBea I confirm this fix.  So strange!

**Comment by blizzz** [comment] 2019-05-17 11:15
The initial bug with the photo cache (`/var/www/cloud/apps/dav/lib/CardDAV/PhotoCache.php - line 244: OC\Files\SimpleFS\SimpleFolder->delete()` on the stack trace) was resolved and is shipped with the latest maintenance releases.

NotFoundException is quite generic and may have different causes. There are  a couple of other issues open.

What was added by @bes1002t has a different cause, but did not reply back.

@luclis, @cyBea's  and likely @stone212's issue's root cause was that an empty user id was generated. This is also fixed for some time now, but also reveals a misconfiguration of LDAP.

**Closed by blizzz** 2019-05-17 11:15 UTC
Labels: bug, feature: filesystem

**Comment by cyBea** [comment] 2019-06-18 01:12
I can confirm this bug is resolved. Tested nextcloud version: 15.0.8
