### ISSUE TITLE
[Bug]: Phone number is no longer saved

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41760] opened 2023-11-27 09:18 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Entering a phone number in the personal settings should trigger a save operation, either automaticlaly or when I click <kbd>Enter</kbd>

![image](https://github.com/nextcloud/server/assets/1374172/0f410027-1ad6-4da5-9cb1-ad712a3550d4)

### Steps to reproduce

1. Open personal settings
2. Enter a phone number
3. Wait a minute
4. Reload the page

### Expected behavior

The phone number is saved.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment] 2023-11-27 09:20
Other fields, like location or organization behave strange too:

1) I see an error toast
2) My modifications are discarded, the previous state is restored

![image](https://github.com/nextcloud/server/assets/1374172/e26d8ece-06d5-4b69-bbde-8a8dedc79902)

**Comment by ChristophWurst** [comment] 2023-11-27 09:23
@Pytal @ShGKme could you have a look?

https://github.com/nextcloud/server/commits/stable28/apps/settings/src/components/PersonalInfo

**Comment by ShGKme** [comment] 2023-11-27 11:32
```
Password confirmation dialog already mounted
```

**Comment by ShGKme** [comment] 2023-11-27 12:39
I'm able to reproduce on c.nc.c, but unable to reproduce locally. Neither on `master`, nor on `28.0.0-rc.1`...

**Comment by ShGKme** [comment] 2023-11-27 13:16
> Could it depend on the apps installed and loaded?

Kind of.

It is a conflict between `@nextcloud/password-confirmation` and new `GlobalSearchModal`.

After https://github.com/nextcloud/server/pull/41669/ the `GlobalSearchModal` is always rendered, even if it was not opened. So initially there is a hidden `GlobalSearchModal` on the page.

At the same time, when `@nextcloud/password-confirmation` is rendered, it search for a modal, and if there is a modal, it renders inside the last one opened modal.

See: https://github.com/nextcloud-libraries/nextcloud-password-confirmation/pull/387

As the result - `@nextcloud/password-confirmation` modal is rendered inside hidden `GlobalSearchModal`.

**Comment by Pytal** [comment] 2023-11-28 01:16
> After #41669 the `GlobalSearchModal` is always rendered, even if it was not opened. So initially there is a hidden `GlobalSearchModal` on the page.

Could we revert back to `v-if` @Fenn-CS?

**Comment by Pytal** [comment] 2023-11-28 01:34
Please ignore the hidden outdated comment above @Fenn-CS as @ShGKme found an alternative solutions :)

**Comment by Pytal** [comment] 2023-11-28 23:20
Fixed by https://github.com/nextcloud/server/pull/41809

**Closed by Pytal** 2023-11-28 23:20 UTC
Labels: bug, 1. to develop, regression, 28-feedback
