### ISSUE TITLE
No profile image upload possible

### ISSUE THREAD

**Issue by jgrete** [nextcloud/server#8984] opened 2018-03-26 11:19 UTC
### Steps to reproduce
1. Upload a profile image (jpg, 100-500kb, or png)
2.
3.

### Expected behaviour
Upload should be sucessfull

### Actual behaviour
Unsucessfull! Message apears:"Invalid image provided"

## Server configuration detail

**Operating system:** Linux 4.4.114-42-default #1 SMP Tue Feb 6 10:58:10 UTC 2018 (b6ee9ae) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.2.13

**PHP version:** 7.0.7
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, exif, mcrypt, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, posix, shmop, sockets, sqlite3, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, zlib, Zend OPcache

**Nextcloud version:** 13.0.1 - 13.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Fresh
**Where did you install Nextcloud from:** unknown
Official download site
<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - announcementcenter: 3.2.1
 - apporder: 0.4.1
 - bookmarks: 0.11.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - checksum: 0.3.5
 - circles: 0.13.6
 - cms_pico: 0.9.7
 - comments: 1.3.0
 - contacts: 2.1.2
 - dav: 1.4.6
 - drawio: 0.8.9
 - end_to_end_encryption: 1.0.5
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_external: 1.4.1
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_reader: 1.2.3
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - groupfolders: 1.2.0
 - impersonate: 1.0.3
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.10
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ownbackup: 17.5.0
 - ownpad: 0.6.6
 - password_policy: 1.3.0
 - polls: 0.8.1
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - radio: 0.6.1
 - ransomware_protection: 1.1.0
 - registration: 0.4.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_diaspora: 1.0.2
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - socialsharing_googleplus: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_usage_report: 1.0.1
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "grete.dedyn.io",
        "cloud-server.fritz.box"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/grete.dedyn.io\/nextcloud",
    "dbtype": "mysql",
    "version": "13.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "thema1",
    "memcache.locking": "OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
<details><summary>LDAP configuration (delete this part if not used)</summary>

</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Operating system:** 
Windows/Linux
## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
not useful information inside. Will provide if necessary
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

all browsers 

</details>

**Comment by jgrete** [comment] 2018-03-29 06:42
Am I really the only one?? I tried to upload the same picture into the contacts app - no problem.
But this picture uploaded to the profile of my nextcloud account - no way.

**Comment by AlexMaj** [comment] 2018-03-30 13:30
exactly same issue with my nextcloud install

**Comment by jgrete** [comment] 2018-03-30 13:57
To make things worse, after my unsuccessful trials the image is gone! On the right upper corner I saw a capitalized character of my name. Now I see nothing - only the menus background...

**Comment by Nils160988** [comment] 2018-03-31 13:55
I can not confirm the issue. Nextcloud 13.0.1 here as well.

**Comment by jgrete** [comment] 2018-03-31 17:58
@Nils160988 
Are there any obvious differences between your setup and mine (see above) ?

**Comment by Nils160988** [comment] 2018-04-07 13:28
My setup is: Linux 4.4.0, php 7.0.28, mariadb 10.0.34 but I have no idea whether is has to do with some of these differences...

**Comment by MorrisJobke** [comment] 2018-07-04 07:45
> I was playing with a complete different thing (authentication by application token) and noticed that my default profile picture was back again ("J"). I decided to do another test and uploaded the profile picture again. This time I uploaded it into the cloud first and was using the directory symbol (located just below the profile picture on the personal settings page). Et voilà ... the picture editor appears and I was able to cut and save.
> This is no solution of course. But hopefully helps until the responsible programmer has time to fix it

Do you have by any chance the picture that fails? Because it seems to be related to what image you are using.

**Comment by jgrete** [comment] 2018-07-04 08:47
This picture cannot be uploaded via upload button, but without any problems via file dialogbox:
![pacoprofil_jgrete](https://user-images.githubusercontent.com/14105933/42266744-91728310-7f77-11e8-8fb3-51c731e14947.jpg)

**Comment by skjnldsv** [comment] 2019-04-30 08:36
Cannot reproduce
![Capture d’écran_2019-04-30_10-36-10](https://user-images.githubusercontent.com/14975046/56949677-cd194400-6b33-11e9-9055-be8e65c5863a.png)


As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Closed by skjnldsv** 2019-04-30 08:36 UTC
Labels: bug, feature: settings

**Comment by CountOmega** [comment] 2020-10-15 18:24
Having this issue with a fresh install of 19.0.4. I can select a picture, but it keeps on loading but to no avial. Any ideas here?
LOG:
`[PHP] Error: Error: file_put_contents(/mnt/sda1/nextcloud/nc_data/appdata_ocu3klcbsqe5/avatar/Matthias/avatar.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#276 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "file_put_conten ... y", "/var/www/nextcl ... p", 276, {path: "appdata_ ... l})
 1. /var/www/nextcloud/lib/private/Files/Storage/Local.php line 276
    file_put_contents("/mnt/sda1/nextc ... g", null)
 2. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 257
    OC\Files\Storage\Local->file_put_contents("appdata_ocu3klc ... g", null)
 3. /var/www/nextcloud/lib/private/Files/View.php line 1159
    OC\Files\Storage\Wrapper\Wrapper->file_put_contents("appdata_ocu3klc ... g", null)
 4. /var/www/nextcloud/lib/private/Files/View.php line 696
    OC\Files\View->basicOperation("file_put_contents", "/appdata_ocu3kl ... g", ["create","write"], null)
 5. /var/www/nextcloud/lib/private/Files/Node/Folder.php line 187
    OC\Files\View->file_put_contents("/appdata_ocu3kl ... g", null)
 6. /var/www/nextcloud/lib/private/Files/SimpleFS/NewSimpleFile.php line 133
    OC\Files\Node\Folder->newFile("avatar.jpg", null)
 7. /var/www/nextcloud/lib/private/Avatar/UserAvatar.php line 109
    OC\Files\SimpleFS\NewSimpleFile->putContent(null)
 8. /var/www/nextcloud/core/Controller/AvatarController.php line 334
    OC\Avatar\UserAvatar->set(null)
 9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OC\Core\Controller\AvatarController->postCroppedAvatar({x: "302.08",y:  ... "})
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controller\AvatarController {}, "postCroppedAvatar")
11. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\AvatarController {}, "postCroppedAvatar")
12. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Core\\Controller\\AvatarController", "postCroppedAvatar", OC\AppFramework\ ... {}, {_route: "core.avatar.postCroppedAvatar"})
13. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.avatar.postCroppedAvatar"})
14. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "core.avatar.postCroppedAvatar"})
15. /var/www/nextcloud/lib/base.php line 1011
    OC\Route\Router->match("/avatar/cropped")
16. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

POST /index.php/avatar/cropped
from 192.168.178.38 by Matthias at 2020-10-15T18:20:30+00:00`

**Comment by fredericrous** [comment] 2021-02-18 12:25
I don't see error logs but I have the same issue. The image doesn't get uploaded, instead I get this:
![image](https://user-images.githubusercontent.com/702227/108356595-3cb66280-71e4-11eb-9f9f-658f2e2c2617.png)

**Comment by CountOmega** [comment] 2021-02-18 14:17
I fixed this by manually creating the /Avatar directory and then it magically worked.

**Comment by pinpox** [comment] 2021-07-19 15:07
I have this issue as well. Creating the /Avatar directory for every user is not a real solution. Any help?

**Comment by gillesF78** [comment] 2021-12-02 13:37
Same issue here. 

I cannot customize my profile photo, neither with the "upload" button, nor with the "Choose file" button.

My running nextcloud version is 22.2.2.0

**Comment by arielnmz** [comment] 2022-02-19 11:02
This happens in a docker container with nextcloud version 21.0.22

```
Request URL: http://cloud.crowbarworks.com/avatar/cropped
Request Method: POST
Status Code: 400 Bad request
Remote Address: 192.168.0.13:80
Referrer Policy: no-referrer
```

```json
{"data":{"message":"An error occurred. Please contact your admin."}}
```

**Comment by arielnmz** [comment] 2022-02-19 21:51
Just upgraded to version 22.2.5 and now it fails with a 500 error:

```
Request URL: http://cloud.crowbarworks.com/avatar/cropped
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 192.168.0.13:80
Referrer Policy: no-referrer
```

**Comment by CountOmega** [comment] 2022-02-19 22:38
> I fixed this by manually creating the /Avatar directory and then it magically worked.

Did you try that workaround?

**Comment by arielnmz** [comment] 2022-02-19 22:40
No it doesn't work for me

**Comment by arielnmz** [comment] 2022-02-19 23:28
The problem is the Jcrop jquery plugin. It seems to be bugged and thinks images are 0x0. I tweaked the JS on the fly and injected the actual image dimensions before POSTing it and it works:

![image](https://user-images.githubusercontent.com/24735547/154822495-052e4aa8-c0aa-467e-86ea-f9ee3c01a873.png)
