### ISSUE TITLE
Recent file list layout adjustment

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#2347] opened 2016-11-26 15:44 UTC
I think the icons of folders and files should be displayed **behind** the (imaginary) red line - as we do it in all the other categories 😉 ...what do you think 🤔 @nextcloud/designers @jancborchardt 

<img width="318" alt="recent" src="https://cloud.githubusercontent.com/assets/19711361/20641407/4f7c6d74-b3f7-11e6-9540-16b04061a0b7.png">

**Comment by Espina2** [comment] 2016-11-26 18:37
@MariusBluem 
I don't get what you are trying to say.

**Comment by MariusBluem** [comment] 2016-11-26 19:48
The icon-positions should be after the red line in my Screenshot 😅🙈 @Espina2

**Comment by skjnldsv** [comment] 2016-11-27 13:00
Could you provide an example of somewhere else where we do that?

**Comment by eppfel** [comment] 2016-11-27 16:13
In the files app, there is the fav button, before the thumbnail..
<img width="274" alt="bildschirmfoto 2016-11-27 um 17 12 54" src="https://cloud.githubusercontent.com/assets/1899308/20649672/c3d88d42-b4c4-11e6-8ab0-8b386cac0202.png">
But is that reason enough?

**Comment by skjnldsv** [comment] 2016-11-27 17:07
Yeah, I don't like this empty space before. Could we reverse this pr? 😝 
Like unify the design but without a white padding before 😆

**Comment by phsc** [comment] 2016-11-27 18:05
Why not move the fav star to the left side of the icon and make it behave the same as the mark/unmark checkbox (filled with yellow if active, otherwise invisible; displayed empty on hover)?
This would allow to consistently remove the whitespace before the icons.

**Comment by nickvergessen** [comment] 2016-11-28 10:26
Duplicate of https://github.com/nextcloud/server/issues/2193

**Comment by MorrisJobke** [comment] 2016-11-28 10:44
Reopen and close the other ticket with less activity ;)

**Comment by eppfel** [comment] 2016-11-28 16:33
@phsc But to select items, you actually click anywhere on the thumbnail, so moving the icon directly to the thumbnail would decreases usability.

I mean I don't use the favorites feature anyway. Might just an option to disable it?

**Comment by phsc** [comment] 2016-11-28 21:40
My idea was, that you had to click directly on the fav star to activate it. The rest of the icon should select the item, but not activate the fav star.
But you're right, it would decrease usability a bit, because you had to click more precisely.

**Comment by jancborchardt** [comment] 2016-11-30 11:13
@MorrisJobke this might have more activity, but the description is confusing. ;) Closing this in favor of the original plan https://github.com/nextcloud/server/issues/2193

**Closed by jancborchardt** 2016-11-30 11:13 UTC
Labels: 1. to develop, bug, design, feature: files, high
