### ISSUE TITLE
[Bug]: Nextcloud 30 beta 5 shows PHP stacktrace in LDAP config check

### ISSUE THREAD

**Issue by wom-bat** [nextcloud/server#47144] opened 2024-08-09 04:13 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to NExtcloud 30.0.0 beta 5 I see:
```
An exception occured while running the setup check: ValueError: The arguments array must contain 2 items, 1 given in /var/www/nextcloud/lib/private/L10N/L10NString.php:68 Stack trace: #0 /var/www/nextcloud/lib/private/L10N/L10NString.php(68): vsprintf() #1 /var/www/nextcloud/lib/private/L10N/L10N.php(107): OC\L10N\L10NString->__toString() #2 /var/www/nextcloud/lib/private/L10N/LazyL10N.php(38): OC\L10N\L10N->n() #3 /var/www/nextcloud/apps/user_ldap/lib/SetupChecks/LdapConnection.php(87): OC\L10N\LazyL10N->n() #4 /var/www/nextcloud/lib/private/SetupCheck/SetupCheckManager.php(34): OCA\User_LDAP\SetupChecks\LdapConnection->run() #5 /var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php(145): OC\SetupCheck\SetupCheckManager->runAll() #6 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\Settings\Controller\CheckSetupController->check() #7 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController() #8 /var/www/nextcloud/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch() #9 /var/www/nextcloud/lib/private/Route/Router.php(309): OC\AppFramework\App::main() #10 /var/www/nextcloud/lib/base.php(996): OC\Route\Router->match() #11 /var/www/nextcloud/index.php(24): OC::handleRequest() #12 {main}
```
in red on teh Administration page under 
Security & setup warnings

### Steps to reproduce

Use the web updater to upgrade from Nextcloud 29 to 3.0.0 beta 5; use `php occ upgrade` when it says 'continue in web based updater'; when that has finished, run `php occ db:add-missing-indices` and`pgp occ maintenance:repair --expensive`

Then visit the Admin page.

### Expected behavior

I don't expect a PHP backtrace.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": false,
        "blacklisted_files": [
            ".htaccess"
        ],
        "overwritehost": "nextcloud.chubb.wattle.id.au",
        "overwriteprotocol": "https",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "https:\/\/nextcloud.chubb.wattle.id.au\/",
        "theme": "",
        "default_language": "en",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "web",
        "knowledgebaseenabled": true,
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "",
        "trashbin_retention_obligation": "180, auto",
        "allow_user_to_change_display_name": true,
        "appcodechecker": "",
        "updatechecker": false,
        "log_type": "file",
        "log_query": true,
        "logfile": "\/var\/nextcloud\/data\/owncloud.log",
        "loglevel": 3,
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***"
        },
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "xframe_restriction": true,
        "customclient_desktop": "",
        "customclient_android": "",
        "customclient_ios": "",
        "logdateformat": "F d, Y H:i:s",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "30.0.0.7",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "chubb.wattle.id.au",
            "nextcloud.chubb.wattle.id.au"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita"
        ],
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v1",
        "apps-paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": "false"
            },
            {
                "path": "\/var\/www\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": "true"
            }
        ],
        "maintenance": false,
        "maintenance_window_start": 1,
        "web.baseUrl": "https:\/\/nextcloud.chubb.wattle.id.au\/",
        "web.rewriteLinks": false,
        "htaccess.rewriteBase": "\/",
        "allow_user_to_change_mail_address": true,
        "token_auth_enforced": false,
        "files_external_allow_create_new_local": true,
        "ldapIgnoreNamingRules": false,
        "default_phone_region": "AU",
        "updater.server.url": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "mysql.utf8mb4": true,
        "enable_file_metadata": true,
        "app_install_overwrite": [
            "impersonate",
            "duplicatefinder",
            "dropit"
        ]
    }
}
```

### List of activated Apps

```shell
- cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0-alpha.2
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.0-beta.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - impersonate: 1.17.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.0
  - password_policy: 2.0.0
  - photos: 3.0.1
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recognize: 8.0.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - bruteforcesettings: 3.0.0
  - duplicatefinder: 1.1.10 (installed 0.0.15)
  - encryption: 2.18.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 3.0.0 (installed 1.1)
  - music: 1.11.0 (installed 1.11.0)
  - twofactor_totp: 12.0.0-dev
  - webhook_listeners: 1.1.0-dev
```

### Nextcloud Signing status

```shell
no errors have been found
```

### Nextcloud Logs

```shell
,{"file":"/var/www/nextcloud/lib/private/L10N/LazyL10N.php","line":38,"function":"n","class":"OC\\L10N\\L10N","type":"->"},{"file":"/var/www/nextcloud/apps/user_ldap/lib/SetupChecks/LdapConnection.php","line":87,"function":"n","class":"OC\\L10N\\LazyL10N","type":"->"},{"file":"/var/www/nextcloud/lib/private/SetupCheck/SetupCheckManager.php","line":34,"function":"run","class":"OCA\\User_LDAP\\SetupChecks\\LdapConnection","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CheckSetupController.php","line":145,"function":"runAll","class":"OC\\SetupCheck\\SetupCheckManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"check","class":"OCA\\Settings\\Controller\\CheckSetupController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":996,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/L10N/L10NString.php","Line":68,"message":"Exception running check OCA\\User_LDAP\\SetupChecks\\LdapConnection: The arguments array must contain 2 items, 1 given","exception":{},"CustomMessage":"Exception running check OCA\\User_LDAP\\SetupChecks\\LdapConnection: The arguments array must contain 2 items, 1 given"}}
```

**Comment by AndyFx12** [comment] 2024-08-16 12:43
It's the same on 30rc1

**Comment by AndyFx12** [comment] 2024-08-29 19:44
... and on 30 rc2, too.

**Comment by AndyFx12** [comment] 2024-09-08 09:20
... even on 30rc4. It's gone, if personal language is set to "English (US)". So it seems to be a localization-problem.

**Comment by devsamt** [comment] 2024-09-15 06:04
We are encountering the same issue with version 30.0.0.14.

**Comment by BuzzITUK** [comment] 2024-09-15 10:21
Yep, 30.0.0.14 same issue. @AndyFx12 change worked for me too.

**Comment by DerP4si** [comment] 2024-09-15 14:25
> Yep, 30.0.0.14 same issue. @AndyFx12 change worked for me too.

I get the same error... What did you do to fix it? The newest release i can find on github is 30.rc5? 🤔

**Comment by BuzzITUK** [comment] 2024-09-15 14:35
I changed the locale language from the account to English (US) and the error disappears. Not fixed, but to me, equally not an major issue.

 [A picture containing graphics, screenshot, symbol, logo  Description automatically generated]
Daimian Williams
Technical Director

Office: 01473 855244
Mobile: 07584 322109
Email: ***@***.******@***.***>

**Comment by ThomasBahn** [comment] 2024-09-15 15:42
Same here. UI in German: Error, UI in English (US): No error.
Version 30.0.0 on Debian.

**Comment by adriangalbincea** [comment] 2024-09-16 06:56
same error here in UK English, once changed the personal GUI language to US, the error is not there anymore

**Comment by chrissi55** [comment] 2024-09-17 07:34
changing the 
[apps/user_ldap/lib/SetupChecks/LdapConnection.php]

worked for me after restart of NC Server 
👍 

https://github.com/nextcloud/server/pull/48061/files

**Comment by adriangalbincea** [comment] 2024-09-17 07:45
> changing the [apps/user_ldap/lib/SetupChecks/LdapConnection.php]
> 
> worked for me after restart of NC Server 👍
> 
> https://github.com/nextcloud/server/pull/48061/files

This fixed the issue for me. Easy fix.

**Comment by AndyFx12** [comment] 2024-09-18 06:22
Worked for me after restart, too.

**Comment by ArnaudL75** [comment] 2024-09-19 09:13
Same as ThomasBahn. UI in French: Error, UI in English (US): No error.
Version 30.0.0.14 on Debian.

**Comment by ibaraki-douji** [comment] 2024-09-20 07:39
I also have a very similar error after the 30.0.0 upgrade :
`An exception occured while running the setup check: ValueError: The arguments array must contain 3 items, 1 given in /var/www/html/lib/private/L10N/L10NString.php:68 Stack trace: #0 /var/www/html/lib/private/L10N/L10NString.php(68): vsprintf('La liaison et l...', Array) #1 /var/www/html/lib/private/L10N/L10N.php(107): OC\L10N\L10NString->__toString() #2 /var/www/html/lib/private/L10N/LazyL10N.php(38): OC\L10N\L10N->n('Binding and sea...', 'Binding and sea...', 1, Array) #3 /var/www/html/apps/user_ldap/lib/SetupChecks/LdapConnection.php(87): OC\L10N\LazyL10N->n('Binding and sea...', 'Binding and sea...', 1, Array) #4 /var/www/html/lib/private/SetupCheck/SetupCheckManager.php(34): OCA\User_LDAP\SetupChecks\LdapConnection->run() #5 /var/www/html/apps/settings/lib/Controller/CheckSetupController.php(147): OC\SetupCheck\SetupCheckManager->runAll() #6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\Settings\Controller\CheckSetupController->check() #7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Settings\Controller\CheckSetupController), 'check') #8 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Settings\Controller\CheckSetupController), 'check') #9 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('OCA\\Settings\\Co...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #10 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/settings/ajax/...') #11 /var/www/html/index.php(24): OC::handleRequest() #12 {main}`

looking at this part of the error `vsprintf('La liaison et l...', Array)` i do think it's the French part that cause the issue

**Comment by fdbailes** [comment] 2024-09-20 10:22
> I also have a very similar error after the 30.0.0 upgrade : `An exception occured while running the setup check: ValueError: The arguments array must contain 3 items, 1 given in /var/www/html/lib/private/L10N/L10NString.php:68 Stack trace: #0 /var/www/html/lib/private/L10N/L10NString.php(68): vsprintf('La liaison et l...', Array) #1 /var/www/html/lib/private/L10N/L10N.php(107): OC\L10N\L10NString->__toString() #2 /var/www/html/lib/private/L10N/LazyL10N.php(38): OC\L10N\L10N->n('Binding and sea...', 'Binding and sea...', 1, Array) #3 /var/www/html/apps/user_ldap/lib/SetupChecks/LdapConnection.php(87): OC\L10N\LazyL10N->n('Binding and sea...', 'Binding and sea...', 1, Array) #4 /var/www/html/lib/private/SetupCheck/SetupCheckManager.php(34): OCA\User_LDAP\SetupChecks\LdapConnection->run() #5 /var/www/html/apps/settings/lib/Controller/CheckSetupController.php(147): OC\SetupCheck\SetupCheckManager->runAll() #6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(208): OCA\Settings\Controller\CheckSetupController->check() #7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(114): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Settings\Controller\CheckSetupController), 'check') #8 /var/www/html/lib/private/AppFramework/App.php(161): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Settings\Controller\CheckSetupController), 'check') #9 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('OCA\\Settings\\Co...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #10 /var/www/html/lib/base.php(1001): OC\Route\Router->match('/settings/ajax/...') #11 /var/www/html/index.php(24): OC::handleRequest() #12 {main}`
> 
> looking at this part of the error `vsprintf('La liaison et l...', Array)` i do think it's the French part that cause the issue (yes i do have my UI in French as well)

same error here, fix above solved the problem.

**Comment by joshtrichards** [comment] 2024-09-22 14:40
Duplicate of #47997

**Closed by joshtrichards** 2024-09-22 14:40 UTC
Labels: bug, feature: ldap, 0. Needs triage, 30-feedback
