### ISSUE TITLE
[Bug]: iphone display error - empty content

### ISSUE THREAD

**Issue by punkyard** [nextcloud/server#46525] opened 2024-07-15 08:36 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

text app, dashboard show blank space on iphone through NC mobile app and Safari web pages

### Steps to reproduce

1. activate iPhone 
3. open Nc app
5. open md file - no display
6. open the same md file with safari
7. same result
8. try to open dashboard - no display

### Expected behavior

display content

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "domain.net",
            "sub.domain.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/var\/lib\/docker\/volumes\/nextcloud_aio_nextcloud\/_data\/skeleton",
        "dbtype": "pgsql",
        "version": "29.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "check_data_directory_permissions": true,
        "maintenance": false,
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "htaccess.RewriteBase": "\/",
        "files_external_allow_create_new_local": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "updatedirectory": "\/nc-updater",
        "overwritehost": "domain.net",
        "overwrite.cli.url": "https:\/\/domain.net\/",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "davstorage.request_timeout": 3600,
        "dbpersistent": false,
        "appsallowlist": false,
        "maintenance_window_start": 100,
        "preview_imaginary_key": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "",
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true
    }
}

```

### List of activated Apps

```
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - announcementcenter: 6.8.1
  - auto_groups: 1.5.3
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.13
  - cfg_share_links: 5.1.0
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - collectives: 2.13.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.1
  - event_update_notification: 2.4.0
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - files: 2.1.0
  - files_antivirus: 5.5.7
  - files_downloadlimit: 2.0.0
  - files_lock: 29.0.1
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - forms: 4.2.4
  - group_default_quota: 0.1.9
  - groupfolders: 17.0.1
  - impersonate: 1.16.0
  - integration_excalidraw: 2.2.0
  - integration_youtube: 0.3.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.7.5
  - money: 0.28.0
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.1
  - notifications: 2.17.0
  - notify_push: 0.6.12
  - oauth2: 1.17.0
  - onlyoffice: 9.3.0
  - password_policy: 1.19.0
  - polls: 7.1.3
  - provisioning_api: 1.19.0
  - quota_warning: 1.19.0
  - registration: 2.4.0
  - related_resources: 1.4.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - side_menu: 3.13.1
  - spreed: 19.0.7
  - support: 1.12.0
  - suspicious_login: 7.0.0
  - tasks: 0.16.0
  - terms_of_service: 2.4.0
  - text: 3.10.1
  - theming: 2.4.0
  - timemanager: 0.3.15
  - twofactor_backupcodes: 1.18.0
  - unroundedcorners: 1.1.3
  - user_status: 1.9.0
  - viewer: 2.3.0
  - welcome: 1.2.0
  - workflowengine: 2.11.0
Disabled:
  - contactsinteraction: 1.10.0 (installed 1.6.0)
  - cospend: 1.6.1 (installed 1.6.1)
  - encryption: 2.17.0
  - federation: 1.19.0 (installed 1.17.0)
  - files_external: 1.21.0
  - files_mindmap: 0.0.30 (installed 0.0.30)
  - firstrunwizard: 2.18.0 (installed 2.14.0)
  - gestion: 2.5.1 (installed 2.4.3)
  - health: 2.2.2 (installed 2.2.2)
  - maps: 1.4.0 (installed 1.4.0)
  - photos: 2.5.0 (installed 2.3.0)
  - privacy: 1.13.0 (installed 1.10.0)
  - recommendations: 2.1.0 (installed 1.4.0)
  - serverinfo: 1.19.0 (installed 1.16.0)
  - survey_client: 1.17.0 (installed 1.13.0)
  - systemtags: 1.19.0 (installed 1.18.0)
  - timetracker: 0.0.83 (installed 0.0.83)
  - transfer: 0.6.3 (installed 0.6.3)
  - twofactor_totp: 11.0.0-dev (installed 7.0.0)
  - user_ldap: 1.20.0
  - weather_status: 1.9.0 (installed 1.5.0)

```

### Additional info

dashboard in safari
![9EBE83C8-ABAD-4CFD-AA54-1B1F85757840](https://github.com/user-attachments/assets/ebc8554c-fbb8-4d59-bd0d-6a9f5a0bc927)

md file in NC mobile client
![1E78568F-536D-4CE3-BB0A-04BAC6BF1871](https://github.com/user-attachments/assets/fa811851-75db-40f8-96ab-11dee227da5c)

**Comment by joshtrichards** [comment] 2024-07-15 21:54
Did this by chance start just after you first updated to v28?

Do you have any warnings under *Administration settings->Overview*?

**Comment by susnux** [comment] 2024-07-19 22:29
Which version of Safari are you using?

**Comment by punkyard** [comment] 2024-07-19 23:03
hi
i cant find the version but iOs is 15.8.2.
and its the same for Brave too which is up to date.
and its the same with nextcloud editor. yeah

**Comment by punkyard** [comment] 2024-07-19 23:05
yes it MIGHT have started with v28
i'm not 100% sure

overview in brave
![2EA80543-98E1-415B-9D8E-A04FD4D2CF9B](https://github.com/user-attachments/assets/9585cc8c-31ce-4bb6-b5f1-1db294d8283c)


overview in safari
![D37D273D-A394-4906-B6B6-065805AAC9C2](https://github.com/user-attachments/assets/006e0afb-d78c-47c1-8223-b6a6aec073bd)

**Comment by joshtrichards** [comment] 2024-07-20 01:22
> overview in brave

I was referring to you checking in your web browser (not on mobile) whether you have any warnings or errors. Though I now see you're using AIO so that's less of a concern. Are you using Cloudflare or doing any theming/customization?

Also, can you provide the output of `occ config:list system` (or equivalent) and `occ app:list` (or equivalent), as requested in the bug report template?

**Comment by punkyard** [comment] 2024-07-27 13:03
hi @joshtrichards 
and thank you for your concern

no, i'm not using cloudflare or done any customization.
I have updated my request with the occ commands as you mentioned.
Regards

**Comment by joshtrichards** [comment] 2024-08-02 20:47
Please disable the following apps and retest:

side_menu
unroundedcorners

>  i cant find the version but iOs is 15.8.2.

It's an older browser, but in theory should still work.

**Comment by susnux** [comment] 2024-08-02 21:33
I think it is caused by this issue: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5589

So iOS < 16.4 will not work as Safari can not handle that regex.

**Comment by punkyard** [comment] 2024-08-02 22:17
Hi 
thank you @joshtrichards and @susnux for your messaging

after disabling the two apps mentioned neither can Brave nor the Nextcloud mobile app open and show .md files: blanck

same for the other pages in my browers: there is no content. 
I'm going to have a look to the 5589 issue :)

**Comment by susnux** [comment] 2024-08-28 02:38
> Is vue v8.17 something we feel comfortable adding in a backport to v29?

Sure non breaking release so this is possible

**Comment by joshtrichards** [comment] 2024-08-29 13:07
Fixed in #47566 (we think).

@punkyard Let us know how things look after the next maintenance release.

**Closed by joshtrichards** 2024-08-29 13:07 UTC
Labels: bug, 0. Needs triage, 28-feedback

**Comment by punkyard** [comment] 2024-10-02 18:13
Hi, 
here is a feed back as demanded

recent released of AiO 960 has brought a tiny evolution in the display of .MD files in safari browser of my iphone: there is a spinning wheel in the middle of the screen and I can see the title of the document.

![Image](https://github.com/user-attachments/assets/ccf7f3f9-cfaa-44af-a0d7-195d3658f673)

Exactly the same behavior in Brave.

In general, I still can't access Talk Discussions, Collectives (but I can see the list of the Collectives in the left panel), Notes, Forms.
I can access Task, Deck, Agenda, Contacts, Files list, Photos, Polls, Announcement.

Which logs would be relevant to this issue?

**Comment by punkyard** [comment] 2024-10-02 18:16
_I want to add that -unfortunately- users have left our instance because of too regular issues - after nicely accepting to test our Nextcloud for about a year now._

**Comment by susnux** [comment] 2024-10-11 11:41
> In general, I still can't access Talk Discussions, Collectives (but I can see the list of the Collectives in the left panel), Notes, Forms.

This are external apps and need to be fixed separately, so please report this on the respective github page of those apps.
This should be fixed with updating nextcloud-vue to the latest version for those apps.

**Comment by punkyard** [comment] 2024-10-11 15:49
> This are external apps and need to be fixed separately, so please report this on the respective github page of those apps. This should be fixed with updating nextcloud-vue to the latest version for those apps.

@susnux thanks for your advice
I will do it in a second step - i think i will focus on the text app first and see after the text app is displayed correctly
