### ISSUE TITLE
Nextcloud Upgrade 11.0.2 to 11.0.3 not possible

### ISSUE THREAD

**Issue by hotschmaster23** [nextcloud/server#6757] opened 2017-10-04 13:31 UTC
### Steps to reproduce
1. start update from 11.0.2 everything is working smoothly until you come to the updatepart
2. webupdate and commandline update with occ update not possible
3. after running the command for occ update and disabling the maintenance mode on commandline
i receive this after clicking the updatebutten, which is not freezing now
Preparing update
Set log level to debug
Updating database schema
Updated database
An error occurred.

### Expected behaviour
The update should run successfully

### Actual behaviour
- Update via Browser in Chrome and Safari freezes when clicking on the update button
-after doing it manually in occ folder with update commands i receive this error

PHP Fatal error:  Class OCA\User_SAML\UserBackend contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Authentication\IApacheBackend::getLogoutUrl) in /var/www/html/nextcloud/apps/user_saml/lib/userbackend.php on line 467

### Server configuration

**Operating system**:
raspbian
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Web server:**
Server version: Apache/2.4.10 (Raspbian)
Server built:   Sep 20 2017 10:24:25

**Database:**
SQLite version 2.8.17

**PHP version:**PHP 5.6.30-0+deb8u1 (cli) (built: Apr 14 2017 16:20:58)

**Nextcloud version:** (see Nextcloud admin page)
11.0.3 update
You may use your browser or the occ upgrade command to do the upgrade
  - installed: true
  - version: 12.0.3.3
  - versionstring: 12.0.3
  - edition:

**Updated from an older Nextcloud/ownCloud or fresh install:**
from 11.0.2

**Where did you install Nextcloud from:**
webupdater and commandline not working

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment] 2017-10-04 13:43
Can you update the user_saml app code before running the update?

**Comment by nickvergessen** [comment] 2017-10-04 14:01
Actually it's a duplicate of #6749

**Closed by nickvergessen** 2017-10-04 14:01 UTC
Labels: feature: install and update, needs info

**Comment by hotschmaster23** [comment] 2017-10-04 16:00
could this also be done when the update is running. because then i have to use the backup

**Comment by hotschmaster23** [comment] 2017-10-04 16:03
because in my point of view this is a bug in the implementation, when someone is doing a backup and apps are not up to date and the whole installation is crashing. you should get a notification that you have update all apps otherwise your installation crashed

**Comment by hotschmaster23** [comment] 2017-10-04 16:53
as i am not getting any solution for that. here is my solution. if you have started the upgrade to 12.0.3 via webupdate and you are landing to the updatepage where you can choose the updatebutten, make sure you disable the user_saml app with this command.
sudo -u www-data php occ app:disable user_saml
after that click on the update button and start the update to 12.0.3
update is running without problems.
login with your account and update all apps which have to be updated and enable them.
when i want to udpate now the user_saml app with this command
sudo -u www-data php occ app:enable user_saml
i receive this error
  [Exception]                                                                  
  App "SSO & SAML authentication" cannot be installed because the following d  
  ependencies are not fulfilled: The library mcrypt is not available.          
                                                                               

app:enable [-g|--groups GROUPS] [--] <app-id>

**Comment by hotschmaster23** [comment] 2017-10-04 16:59
this issue can be closed after these workarounds.
next after you getting this error that tells you that the library libmcrypt4 is missing so you have to install it with this command.
apt-get install php5-mcrypt
these packages will be also installed libmcrypt4 php5-mcrypt
after that user_saml can be activated without error
sudo -u www-data php occ app:enable user_saml
user_saml enabled
