### ISSUE TITLE
Update notification via email

### ISSUE THREAD

**Issue by ilippert** [nextcloud/server#17960] opened 2019-11-15 12:21 UTC
Nextcloud 16.0.4

At base URL /index.php/settings/admin/overview I find information about updates and I can add a group of which the members should be notified when updates exist. 
It seems that any update is only signalled within the server's user interface. no email is sent out. it would be helpful if the users of that group also get an email notification (activated via check box).

Thank you for considering.

**Comment by kesselb** [comment] 2019-11-15 15:00
Duplicate of https://github.com/nextcloud/server/issues/3596

**Closed by kesselb** 2019-11-15 15:00 UTC
Labels: 0. Needs triage, enhancement
