### ISSUE TITLE
Error: Call to a member function getUID() on null in when Removing a NC User via OCC cmd

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#12011] opened 2018-10-24 10:11 UTC
### Steps to reproduce
Remove User by OCC command

### Expected behaviour
User should be remove without any error 

### Actual behaviour
User will be removed, but there a Trace errors coming from CIRCLE

## Server configuration detail

**Operating system:** Linux 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64

**Webserver:** Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.22 (apache2handler)

**Database:** mysql 5.5.60

**PHP version:** 

7.1.22
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache

**Nextcloud version:** 13.0.7 - 13.0.7.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older NC Install

**Where did you install Nextcloud from:** Origin NC Source

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - announcementcenter: 3.2.1
 - apporder: 0.5.0
 - bookmarks: 0.12.2
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.1
 - circles: 0.14.2
 - comments: 1.3.0
 - contacts: 2.1.5
 - data_request: 1.0.1
 - dav: 1.4.7
 - deck: 0.4.1
 - drop_account: 0.0.12
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_antivirus: 1.3.2
 - files_external: 1.4.1
 - files_fulltextsearch: 1.0.3
 - files_pdfviewer: 1.2.1
 - files_rightclick: 0.8.4
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.8
 - fulltextsearch: 1.0.3
 - gallery: 18.0.0
 - impersonate: 1.0.4
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mindmaps: 0.1.0
 - mood: 0.4.0
 - music: 0.9.2
 - nextcloud_announcements: 1.2.0
 - notes: 2.4.2
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - ownbackup: 18.8.1
 - passman: 2.1.4
 - password_policy: 1.3.0
 - polls: 0.8.3
 - provisioning_api: 1.3.0
 - quicknotes: 0.1.4
 - quota_warning: 1.2.0
 - radio: 0.6.1
 - rainloop: 5.1.0
 - ransomware_protection: 1.1.2
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - sharepoint: 1.1.0
 - sharerenamer: 1.6.0
 - socialsharing_diaspora: 1.0.3
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - socialsharing_googleplus: 1.0.3
 - socialsharing_twitter: 1.0.3
 - spreed: 3.2.6
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.7
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - appvncsafe
 - audioplayer
 - carnet
 - cms_pico
 - encryption
 - external
 - files_markdown
 - lsd
 - phonetrack
 - ransomware_detection
 - richdocuments
 - spreedme
 - user_external
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxxxx",
        "xxxx"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxxxxxxx",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "13.0.7.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "updater.release.channel": "production",
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "data-fingerprint": "xxxxxxxxxx",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "xxxx",
    "session_lifetime": xxxx,
    "session_keepalive": false,
    "logtimezone": "xxxxxx",
    "logfile": "\/media\/log\/nextcloud.log",
    "knowledgebaseenabled": false,
    "log_rotate_size": 3145728
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** none

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Browser log</summary>

```
no browser issue; user was removed / delete via OCC command from the Linux CLI
```
</details>

<details><summary>Nextcloud log</summary>

```
Error: Call to a member function getUID() on null in /var/www/html/nextcloud/apps/circles/lib/Api/v1/Circles.php:185
Stack trace:
#0 /var/www/html/nextcloud/apps/mindmaps/lib/Db/MindmapMapper.php(131): OCA\Circles\Api\v1\Circles::listCircles(15)
#1 /var/www/html/nextcloud/apps/mindmaps/lib/AppInfo/Application.php(69): OCA\Mindmaps\Db\MindmapMapper->findAll('test123')
#2 [internal function]: OCA\Mindmaps\AppInfo\Application->OCA\Mindmaps\AppInfo\{closure}(Object(OC\User\User))
#3 /var/www/html/nextcloud/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/nextcloud/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postDelete', Array)
#5 /var/www/html/nextcloud/lib/private/User/User.php(247): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postDelete', Array)
#6 /var/www/html/nextcloud/core/Command/User/Delete.php(64): OC\User\User->delete()
#7 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\User\Delete->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\User\Delete), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/nextcloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/nextcloud/console.php(90): OC\Console\Application->run()
#13 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#14 {main}

```
</details>

<details><summary>Browser log</summary>

no browser issue; user was removed / delete via OCC command from the Linux CLI
</details>

**Comment by skjnldsv** [comment] 2020-04-10 08:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 08:17 UTC
Labels: 0. Needs triage, bug
