### ISSUE TITLE
[Bug]: `OC\User\NoUserException: Backends provided no user object` when background job expires groupfolders versions

### ISSUE THREAD

**Issue by alphasixtyfive** [nextcloud/server#40469] opened 2023-09-18 07:48 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
[files] Error: OC\User\NoUserException: Backends provided no user object at <<closure>>

 0. <<closure>>
    OC\Files\Node\Root->getUserFolder()
 1. /srv/nextcloud/lib/private/Files/Node/LazyFolder.php line 74
    call_user_func_array()
 2. /srv/nextcloud/lib/private/Files/Node/LazyRoot.php line 40
    OC\Files\Node\LazyFolder->__call()
 3. /srv/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php line 73
    OC\Files\Node\LazyRoot->getUserFolder()
 4. /srv/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
 5. /srv/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
 6. /srv/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
 7. /srv/nextcloud/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
 8. /srv/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
 9. /srv/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
10. /srv/nextcloud/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

at 2023-09-18T07:40:02+00:00
```

### Steps to reproduce

After updating to version 27.1, above error started appearing

### Expected behavior

Error should not occur

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "storage.unimor.com.ua"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.0.7",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "overwrite.cli.url": "https:\/\/storage.unimor.com.ua",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "GB",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "activity_use_cached_mountpoints": true,
        "app_install_overwrite": [
            "breezedark",
            "files_trackdownloads",
            "webhooks",
            "extract"
        ],
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
```


### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bookmarks: 13.1.1
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.0
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - deck: 1.11.0
  - extract: 1.3.6
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_versions: 1.20.0
  - groupfolders: 15.3.0
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - spreed: 17.1.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tables: 0.6.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - unroundedcorners: 1.1.1
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - circles: 27.0.1 (installed 26.0.0)
  - dashboard: 7.7.0 (installed 7.6.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.16.0)
  - files_external: 1.19.0 (installed 1.18.0)
  - files_trashbin: 1.17.0 (installed 1.17.0)
  - firstrunwizard: 2.16.0 (installed 2.15.0)
  - hibp: 0.1.0 (installed 0.1.0)
  - nextcloud_announcements: 1.16.0 (installed 1.15.0)
  - photos: 2.3.0 (installed 2.3.0)
  - recommendations: 1.6.0 (installed 1.5.0)
  - related_resources: 1.2.0 (installed 1.1.0-alpha1)
  - sharebymail: 1.17.0 (installed 1.16.0)
  - support: 1.10.0 (installed 1.9.0)
  - survey_client: 1.15.0 (installed 1.14.0)
  - user_ldap: 1.17.0
  - weather_status: 1.7.0 (installed 1.6.0)
```
```


### Nextcloud Signing status

_No response_

### Nextcloud Logs

_No response_

### Additional info

_No response_

**Comment by solracsf** [comment] 2023-09-18 09:57
Duplicate of https://github.com/nextcloud/groupfolders/issues/2559

**Closed by solracsf** 2023-09-18 09:57 UTC
Labels: bug, 0. Needs triage, feature: versions, 27-feedback

**Comment by Bouli911** [comment] 2023-11-02 00:43
Disable music app …
