### ISSUE TITLE
redirect_url does not respect the 'overwritewebroot' => '/nc' configuration after a session timeout

### ISSUE THREAD

**Issue by flurischt** [nextcloud/server#4571] opened 2017-04-27 22:15 UTC
Hi,

My users access nextcloud under the url https://server/nc/ via nginx reverse proxy. Nextcloud itself runs under /nextcloud/ on a Apache server. To make this work I use the 'overwritewebroot' => '/nc' setting in config.php. Everything works as expected until the user gets a session timeout. After the timeout they are redirected to the login and in the login url ?redirect_url=/**nextcloud**/... is used. This should be ?redirect_url=/**nc**/ according to my overwritewebroot configuration. Due to this a user gets a 404 everytime after the login. By manually removing the wrong /nextcloud/ in the url everything works again.

### Steps to reproduce
1. run nextcloud behind a reverse proxy in a different subdirectory
2. use overwritewebroot in config.php
3. login
4. wait for session timeout
5. refresh
6. the login form is shown

### Expected behaviour
7. redirect_url in the url should use the webroot specified in 'overwritewebroot'

### Actual behaviour
7. redirect_url uses the actual webroot in which nextcloud was installed. Users that access nextcloud via reverse proxy will get a 404 after login.

### Server configuration

**Operating system**: Ubuntu Xenial

**Web server:** Apache behind nginx reverse proxy

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Comment by MorrisJobke** [comment] 2017-04-29 04:15
cc @lukasreschke @rullzer @nickvergessen

**Comment by skjnldsv** [comment] 2020-08-20 08:10
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-20 08:10 UTC
Labels: 0. Needs triage, bug
