### ISSUE TITLE
OAuth 2.0: ClientNotFoundException

### ISSUE THREAD

**Issue by gruessung** [nextcloud/server#11056] opened 2018-09-05 06:24 UTC
### Steps to reproduce
1. Add OAuth 2.0 Client in Backend
2. Create OAuth 2.0 Client in PHP 
3. Go

### Expected behaviour
I want to login via Nextcloud and redirect to my application.

### Actual behaviour
An error occures:
`Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 91.53.243.43
Anfragekennung: W492DFUNg7YAABXLFvEAAAAB
Typ: OCA\OAuth2\Exceptions\ClientNotFoundException
Code: 0
Nachricht:
Datei: /www/htdocs/***/cloud.gruessung.eu/apps/oauth2/lib/Db/ClientMapper.php
Zeile: 53

Trace
#0 /www/htdocs/***/cloud.gruessung.eu/apps/oauth2/lib/Controller/LoginRedirectorController.php(70): OCA\OAuth2\Db\ClientMapper->getByIdentifier(NULL)
#1 /www/htdocs/***/cloud.gruessung.eu/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\OAuth2\Controller\LoginRedirectorController->authorize(NULL, NULL, NULL)
#2 /www/htdocs/***/cloud.gruessung.eu/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\OAuth2\Controller\LoginRedirectorController), 'authorize')
#3 /www/htdocs/***/cloud.gruessung.eu/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\OAuth2\Controller\LoginRedirectorController), 'authorize')
#4 /www/htdocs/***/cloud.gruessung.eu/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\OAuth2\\Cont...', 'authorize', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#5 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#6 /www/htdocs/***/cloud.gruessung.eu/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#7 /www/htdocs/***/cloud.gruessung.eu/lib/base.php(989): OC\Route\Router->match('/apps/oauth2/au...')
#8 /www/htdocs/***/cloud.gruessung.eu/index.php(42): OC::handleRequest()
#9 {main}`

### Server configuration

**Operating system**: Linux dd7120 3.13.0-157-generic #207-Ubuntu SMP Mon Aug 20 16:44:59 UTC 2018 x86_64

**Web server:** Apache

**Database:** mySQL

**PHP version:** 7.2

**Nextcloud version:** 14.0.0 RC 2 (also tested with NC 13 last patch level)

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from NC 13

**Where did you install Nextcloud from:**  Self installed

**Signing status:** 
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - apporder: 0.5.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - encryption: 2.2.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.2
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_notifications
  - caniupdate
  - checksum
  - contracts
  - data_request
  - files_automatedtagging
  - metadata
  - notes
  - passwords
  - quota_warning
  - rainloop
  - ransomware_protection
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.gruessung.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cloud.gruessung.eu",
        "dbtype": "mysql",
        "version": "14.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "Lc6s0_",
        "mysql.utf8mb4": false,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "tempdirectory": "\/www\/htdocs\/*****\/cloud.gruessung.eu\/tmp\/",
        "maintenance": false,
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 0,
        "debug": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
One Local storage

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Google Chrome Latest

**Operating system:** Win10

#### Web server error log
<details>
<summary>Web server error log</summary>

No access to this file -> web hoster
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"W4919lUNg7YAABMDDb0AAAAF","level":2,"time":"2018-09-05T06:21:42+00:00","remoteAddr":"37.120.184.34","user":"--","app":"no app in context","method":"GET","url":"\/\/ocs-provider\/","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Nextcloud Server Crawler","version":"14.0.0.18"}
{"reqId":"W49191UNg7YAACmmRIgAAAAJ","level":2,"time":"2018-09-05T06:21:43+00:00","remoteAddr":"37.120.184.34","user":"--","app":"no app in context","method":"GET","url":"\/\/ocs-provider\/","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Nextcloud Server Crawler","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":2,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":3,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"index","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":{"Exception":"OCA\\OAuth2\\Exceptions\\ClientNotFoundException","Message":"","Code":0,"Trace":[{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/apps\/oauth2\/lib\/Controller\/LoginRedirectorController.php","line":70,"function":"getByIdentifier","class":"OCA\\OAuth2\\Db\\ClientMapper","type":"->","args":[null]},{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"authorize","class":"OCA\\OAuth2\\Controller\\LoginRedirectorController","type":"->","args":[null,null,null]},{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OAuth2\\Controller\\LoginRedirectorController"},"authorize"]},{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OAuth2\\Controller\\LoginRedirectorController"},"authorize"]},{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\OAuth2\\Controller\\LoginRedirectorController","authorize",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"oauth2.LoginRedirector.authorize"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"oauth2.LoginRedirector.authorize"}]},{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"oauth2.LoginRedirector.authorize"}]},{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/lib\/base.php","line":989,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/oauth2\/authorize"]},{"file":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/apps\/oauth2\/lib\/Db\/ClientMapper.php","Line":53,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/core\/css\/css-variables.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/apps\/firstrunwizard\/css\/firstrunwizard.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/apps\/notifications\/css\/styles.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/core\/search\/css\/results.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/core\/css\/styles.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@FUNg7YAADRKaBEAAAAZ","level":0,"time":"2018-09-05T06:21:44+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"core","method":"GET","url":"\/apps\/oauth2\/authorize?state=12c618e9a86bacc603d52b4357f8e655&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fkamera.gruessung.eu&client_id=6nUMH5Zu8hwVydLEqsUY5uYUFZkw9erIVHa0aPy79E9hCP89JiVl3wxU6qPUlJtA","message":"Scss is disabled for \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/core\/css\/header.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@VUNg7YAABXLFusAAAAB","level":2,"time":"2018-09-05T06:21:45+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/apps\/oauth2\/undefined\/img\/notifications.svg","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@VUNg7YAACnrR14AAAAP","level":2,"time":"2018-09-05T06:21:45+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/apps\/oauth2\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@VUNg7YAABXLFuwAAAAB","level":2,"time":"2018-09-05T06:21:46+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@VUNg7YAABXLFuwAAAAB","level":0,"time":"2018-09-05T06:21:46+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"No cache entry found for \/appdata_ocdacbt2bz6m\/theming\/images\/background (storage: local::\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/data\/, internalPath: appdata_ocdacbt2bz6m\/theming\/images\/background)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@lUNg7YAACnrR18AAAAP","level":2,"time":"2018-09-05T06:21:46+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@lUNg7YAADRKaBIAAAAZ","level":2,"time":"2018-09-05T06:21:46+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/index.php\/apps\/theming\/favicon?v=6","message":"Temporary directory \/www\/htdocs\/w0098483\/cloud.gruessung.eu\/tmp\/ is not present or writable","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}
{"reqId":"W491@lUNg7YAACnrR18AAAAP","level":0,"time":"2018-09-05T06:21:46+00:00","remoteAddr":"91.53.243.43","user":"agruessung","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files\/","message":"No cache entry found for \/appdata_ocdacbt2bz6m\/theming\/images\/background (storage: local::\/www\/htdocs\/w0098483\/cloud.gruessung.eu\/data\/, internalPath: appdata_ocdacbt2bz6m\/theming\/images\/background)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.106 Safari\/537.36","version":"14.0.0.18"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
shareconfigmodel.js:24 Uncaught ReferenceError: oc_appconfig is not defined
    at shareconfigmodel.js:24
    at shareconfigmodel.js:80
(anonymous) @ shareconfigmodel.js:24
(anonymous) @ shareconfigmodel.js:80
js.js:202 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (js.js:202)
    at viewer.js:15
```
</details>

**Comment by gruessung** [comment] 2018-09-14 13:52
Noone with an idea?

**Comment by leonklingele-work** [comment] 2018-09-18 11:01
Same issue occurred to me with 14.0.0 (stable).

@fancycode FYI

**Comment by gruessung** [comment] 2018-10-08 10:40
Error occurred only after updating from NC13 to NC14.
I tried a fresh install (with docker) and it works.
Which files i have to overwrite? ^^

**Comment by iKoze** [comment] 2019-10-11 13:14
Hi,

i just had the same issue. The problem for me was that I requested the url like this:
`https://cloud.example.com/apps/oauth2/authorize` (without the `/index.php/`).
`https://cloud.example.com/index.php/apps/oauth2/authorize` worked.

Without `/index.php/` this should have worked as well, because I already had configured mod_rewrite and mod_env properly.

The problem is that you also have to tell nextcloud to use [pretty urls](https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#pretty-urls).

Eg. add the following lines to your `config.php` and run `sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess`

```
'overwrite.cli.url' => 'https://cloud.perspicuous-computing.science/',
'htaccess.RewriteBase' => '/',

```

**Comment by skjnldsv** [comment] 2020-04-10 07:28
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 07:28 UTC
Labels: 0. Needs triage, bug
