### ISSUE TITLE
Missing default Address Book (Contacts)

### ISSUE THREAD

**Issue by macmedia** [nextcloud/server#4830] opened 2017-05-12 04:48 UTC
Running Nextcloud with Mail-In-a-box v0.22

After updated each version, making sure not to skip a major, I have no default address book. If I stop at Nextcloud v10.0.4 I have one. 

The process is, I have a clean install of owncloud 8.2.3. The user logged in to create an account. Nothing else is done. Simply login and logout. Then run each upgrade to the new version. If I stop at 10.0.4 and login, select contacts, I have a default (empty) "contacts" address book. Everything works fine. If I skip that step, do not login at 10.0.4, and continue to upgrade I don't get a address book. When I click the contacts tab on either 11 or 12 I just get a spinning circle (loading icon).

If I click the settings in the lower left corner, I have nothing. After I create a new address book name, the spinning circle goes away. At this point everything seems to work fine.

### Steps to reproduce
1. Upgraded from 8.2.3
2. Upgraded from 9.0.2
3. Upgraded from 9.1.4
4. Upgraded from 10.0.4
5. Upgraded from 11.0.3
6. Upgraded to 12beta2

### Expected behavior
Default "contacts" address book. Like I get in version 10.0.4

### Actual behavior
Spinning circle. No address book.

### Server configuration

**Operating system**: Ubuntu 14.05tls

**Web server**: nginx/1.4.6 (Ubuntu)

**Database**: Sqlite 3.8.2

**PHP version**: PHP 7.0.19-1+deb.sury.org~trusty+1

**Nextcloud version**: Nextcloud 12.0 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded see above

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/prereleases

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.2
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "\/home\/user-data\/owncloud",
        "instanceid": "oc57d9580d0c",
        "forcessl": true,
        "overwritewebroot": "\/cloud",
        "overwrite.cli.url": "\/cloud",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{127.0.0.1:993\/imap\/ssl\/novalidate-cert}"
                ]
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcached_servers": [
            [
                "127.0.0.1",
                11211
            ]
        ],
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": false,
        "mail_smtphost": "",
        "mail_smtpport": "",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "administrator",
        "mail_domain": "ubuntu-linux20.localdomain",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ubuntu-linux20.localdomain"
        ],
        "dbtype": "sqlite3",
        "version": "12.0.0.18",
        "logtimezone": "America\/Phoenix",
        "installed": true,
        "logdateformat": "Y-m-d H:i:s",
        "loglevel": 0,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** carddav.

### Client configuration
**Browser:** Version 10.1 (12603.1.30.0.34)

**Operating system:** OS X 12.12.4

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2017/05/11 21:19:15 [error] 16698#0: *1 open() "/usr/local/lib/owncloud/core/vendor/dist/purify.min.js.m$
2017/05/11 21:19:28 [error] 16698#0: *5 open() "/usr/local/lib/owncloud/core/vendor/dist/purify.min.js.m$
2017/05/11 21:21:11 [error] 16698#0: *5 open() "/usr/local/lib/owncloud/core/vendor/dist/purify.min.js.m$
2017/05/11 21:21:35 [error] 16698#0: *5 open() "/usr/local/lib/owncloud/core/vendor/dist/purify.min.js.m$
2017/05/11 21:21:50 [error] 16698#0: *5 open() "/usr/local/lib/owncloud/core/vendor/dist/purify.min.js.m$
2017/05/11 21:21:51 [error] 16698#0: *5 open() "/usr/local/lib/owncloud/apps/contacts/js/vendor/angular-$
2017/05/11 21:26:36 [error] 16698#0: *5 open() "/usr/local/lib/owncloud/core/vendor/dist/purify.min.js.m$
2017/05/11 21:27:41 [error] 16698#0: *91 open() "/usr/local/lib/owncloud/core/vendor/dist/purify.min.js.$

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Tre3PimNYgxhLQpRE2ux","level":0,"time":"2017-05-11 21:31:07","remoteAddr":"10.211.55.2","user":"--","app":"core","method":"GET","url":"\/cloud\/index.php\/login","message":"Scss is disabled for \/usr\/local\/lib\/owncloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/603.1.30 (KHTML, like Gecko) Version\/10.1 Safari\/603.1.30","version":"12.0.0.18"}
{"reqId":"Tre3PimNYgxhLQpRE2ux","level":0,"time":"2017-05-11 21:31:07","remoteAddr":"10.211.55.2","user":"--","app":"core","method":"GET","url":"\/cloud\/index.php\/login","message":"Scss is disabled for \/usr\/local\/lib\/owncloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/603.1.30 (KHTML, like Gecko) Version\/10.1 Safari\/603.1.30","version":"12.0.0.18"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
[Error] Error: undefined is not an object (evaluating 'addressBook.displayName')
Contact@https://ubuntu-linux20.localdomain/cloud/apps/contacts/js/public/script.js?v=0160392b24803031e3d73f34647aba8c-0:1079:30
create@https://ubuntu-linux20.localdomain/cloud/apps/contacts/js/public/script.js?v=0160392b24803031e3d73f34647aba8c-0:1708:41
createContact@https://ubuntu-linux20.localdomain/cloud/apps/contacts/js/public/script.js?v=0160392b24803031e3d73f34647aba8c-0:954:24
fn
expensiveCheckFn@https://ubuntu-linux20.localdomain/cloud/apps/contacts/js/vendor/angular/angular.js?v=0160392b24803031e3d73f34647aba8c-0:15906:20
callback@https://ubuntu-linux20.localdomain/cloud/apps/contacts/js/vendor/angular/angular.js?v=0160392b24803031e3d73f34647aba8c-0:25885:19
$apply@https://ubuntu-linux20.localdomain/cloud/apps/contacts/js/vendor/angular/angular.js?v=0160392b24803031e3d73f34647aba8c-0:17782:30
https://ubuntu-linux20.localdomain/cloud/apps/contacts/js/vendor/angular/angular.js?v=0160392b24803031e3d73f34647aba8c-0:25890:29
dispatch@https://ubuntu-linux20.localdomain/cloud/core/vendor/core.js?v=0160392b24803031e3d73f34647aba8c-0:3:6471
handle@https://ubuntu-linux20.localdomain/cloud/core/vendor/core.js?v=0160392b24803031e3d73f34647aba8c-0:3:3246
	(anonymous function) (angular.js:10467)
	$apply (angular.js:17787)
	(anonymous function) (angular.js:25890)
	dispatch (core.js:3:6472)
	handle (core.js:3:3247)
```
</details>

**Comment by MorrisJobke** [comment] 2017-05-12 05:04
cc @nickvergessen @georgehrke

**Comment by nickvergessen** [comment] 2017-05-12 06:39
Odd, but yeah I think the hook was changed to first login only

**Comment by nickvergessen** [comment] 2017-05-12 08:12
Regression from https://github.com/nextcloud/server/commit/506ccdbd8dd7a9438fa69fe09bc9307ca5f346e3

I'm okay with reverting the dav related change in there.

**Comment by macmedia** [comment] 2017-05-12 15:11
First login didn't fix the issue either. After logging in, both 11.0.3 and 12beta2, I still didn't get a default "contacts" address book.

**Comment by nickvergessen** [comment] 2017-05-15 11:41
Okay, second idea, add something like "first login after last update"?

That would help a bit better, since first login may be too restrictive and on login to broad

**Comment by MorrisJobke** [comment] 2017-05-15 15:04
cc @ChristophWurst because he works on something similar in another ticket.

**Comment by macmedia** [comment] 2017-05-15 15:24
In my use case, Nextcloud is part of a Mail-In-a-Box install. This also uses Roundcube webmail with a carddav plugin that hooks into Nextcloud for address support. After a Nextcloud update you can not login to Roundcube as its trying to connect to the Nextcloud address book. 

I know Roundcube is outside the scope of your project, but waiting until a Nextlcoud login to generate a default address book also causes a problem.

**Comment by MorrisJobke** [comment] 2017-05-15 15:48
> cc @ChristophWurst because he works on something similar in another ticket.

#4797

**Comment by nickvergessen** [comment] 2017-05-16 09:53
It can be easily worked around by manually reseting the last login date for all users after the update:
```sql
UPDATE `oc_preferences`
SET `configvalue` = '0'
WHERE `appid` = 'login'
    AND `configkey` = 'lastLogin';
```

**Comment by MorrisJobke** [comment] 2018-01-05 10:13
@nickvergessen let's move this to 14 - okay?

**Comment by fermat2a** [comment] 2018-02-28 11:05
Hi, I have the same problem after updating from Nextcloud 11 to 12. I did the update on oc_preferences in mysql but also thereafter I did not get my adressbook back. Is there a way to connect again? Shall I upload any logs?

**Comment by skjnldsv** [comment] 2018-03-25 11:18
Just so you know, the contacts app create one if none available. :(

**Comment by MorrisJobke** [comment] 2018-07-03 12:15
> Just so you know, the contacts app create one if none available. :)

So this is not needed anymore?

**Comment by skjnldsv** [comment] 2018-07-03 12:18
I have no idea @MorrisJobke

**Comment by MorrisJobke** [comment] 2018-08-24 14:30
We fixed some stuff in this area and haven't noticed since a while. Let's close it for now. If somebody still experience this we can look at this again.

**Closed by MorrisJobke** 2018-08-24 14:30 UTC
Labels: bug, feature: dav, good first issue, medium, regression
