### ISSUE TITLE
upgrade .htaccess error

### ISSUE THREAD

**Issue by dewomser** [nextcloud/server#3124] opened 2017-01-17 16:27 UTC
After update nextcloud. to new version   
Apache server can't show any nextcloud website.
that happend 3 times while every uptdate.

Workaround:
1. delete .htaccess in the nextcloud root.
2. manually edit config/config.php  fro true to 'maintenance' => false,
3. nextcloud completes update

apache error:
500
apache error file:
[Tue Jan 17 11:36:35.418032 2017] [core:alert] [pid 32349] [client 88.68.20.128:48946] /var/www/html/nextcloud/.htaccess: php_value not allowed here

PHP
Version: 7.0.14
Memory Limit: 128.0 MB
Max Execution Time: 3600
Upload max size: 2.0 MB

Database
Type: mysq
Version: 10.0.28
Size: 32.1 MB

Apache 2.4.10

**Comment by MorrisJobke** [comment] 2017-01-18 00:46
cc @LukasReschke

**Comment by nickvergessen** [comment] 2017-01-18 08:12
@dewomser can you post the file you have to delete? Looks like it contains a syntax error, in which case it would be nice to see the file.

**Comment by dewomser** [comment] 2017-01-18 11:25
Hallo @nickvergessen !
Here is  requested post

 Info: My nextcloud installation works without need of .htaccess
1.file named  htaccess-old seemed to be autogenerated as I deleted .htaccess yesterday.
2 corrupted .htaccess saved after update from 20.12.2016 

screenshot  update:
![nextcloud_update_11001_screenshot_20170117_113744](https://cloud.githubusercontent.com/assets/5160282/22062188/c46ccb38-dd78-11e6-9c68-88e7082cd85c.png)


[htaccess-old1.txt](https://github.com/nextcloud/server/files/713719/htaccess-old1.txt)
[htaccess-old2.txt](https://github.com/nextcloud/server/files/713720/htaccess-old2.txt)

**Comment by MorrisJobke** [comment] 2017-05-16 02:00
I can't see anything suspicious and also can't reproduce this :/

I will close this ticket, because there is a workaround available.

**Closed by MorrisJobke** 2017-05-16 02:00 UTC
Labels: needs info

**Comment by Zagur** [comment] 2018-03-03 13:24
Where is the workaround available?
