### ISSUE TITLE
older share links are affected by creating new ones

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#17461] opened 2019-10-08 11:17 UTC
Nextcloud 17.

When you create a link with a number of permissions and then create a new link, the older link(s) are affected - and lose at least editing permissions.

Issue in action:
https://cloud.nextcloud.com/s/mZWsTrLTmyQFzat

**Comment by szaimen** [comment] 2021-05-26 13:33
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-26 13:33 UTC
Labels: 0. Needs triage, bug
