### ISSUE TITLE
Code integrity check shows extra .htaccess file in not existing folder

### ISSUE THREAD

**Issue by rw71** [nextcloud/server#13842] opened 2019-01-26 11:43 UTC
I updated from 14.0.4 to 14.0.6.

Everything worked fine except the integrity check. It shows a file and folder that is not existing:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- lib/private/oc_tmp_FAHB9a-folder/.htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/private/oc_tmp_FAHB9a-folder/.htaccess] => Array
                        (
                            [expected] => 
                            [current] => ff1ee47ac653d0aff2f201ba15b3d98e84701d3608c7dc4300a0c73d8a5ab36a0d12cf79d60ecef34403fa35248c23fa22b9d354941cc8b1314ef43181dc90f1
                        )

                )

        )

)

I checked with root access the file system. There is no folder in lib/private named like oc*

I also did the update on a test system before. There I saw the same problem. But after some time and running occ integrity:check-core in command line it disappeared.
Therefore I decided to continue with the production system.

On my production system I still have the problem after running occ integrity:check-core several times.

I also made a test to copy an additional file (e.g. phpinfo.php) to the Nextcloud file structure. It was detected immediately. Also it disappeared after deleting and rescanning via web page.

It seems that the rescan is not working will. Where is this information stored to reset it and start a working rescan of the current existing files?

Edit: A reboot of the web server did not help.

**Comment by MorrisJobke** [comment] 2019-03-25 13:55
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-03-25 13:55 UTC
