### ISSUE TITLE
Changing password invalidates all app passwords

### ISSUE THREAD

**Issue by paulstewartis** [nextcloud/server#7872] opened 2018-01-15 18:46 UTC
### Steps to reproduce
1. Set up application specific passwords.
2. Change account password
* Notice that all of your app passwords are invalidated yet they still show in the list of sessions/app passwords.

### Expected behaviour
Changing the account password should have no effect on the app passwords.

### Actual behaviour
Changing the account password requires me to revoke, recreate, reconnect all my apps.

### Server configuration

**Operating system**: openSUSE Leap 42.3

**Web server:** Apache 2

**Database:** mariadb

**PHP version:** 7

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
all good

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "515dfc4320244",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/owncloud_data",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "installed": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "maintenance": false,
        "singleuser": false,
        "forcessl": true,
        "theme": "",
        "trusted_domains": [
            "enos.modernsubject.com"
        ],
        "mail_smtpmode": "php",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "paul",
        "mail_domain": "enos.modernsubject.com",
        "overwrite.cli.url": "https:\/\/enos.modernsubject.com\/owncloud",
        "appstore.experimental.enabled": true,
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud",
        "dbtableprefix": "oc_",
        "logtimezone": "UTC",
        "dbport": ""
    }
}
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium

**Operating system:** openSUSE Leap 42.3

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

</details>

#### Browser log
<details>
<summary>Browser log</summary>

</details>

**Comment by MorrisJobke** [comment] 2018-01-16 08:34
cc @ChristophWurst Wasn't this the idea behind this? Maybe we should change it nowadays.


cc @rullzer @jancborchardt @tobiasKaminsky

**Comment by rullzer** [comment] 2018-01-16 08:50
The idea was that your password is never exposed directly on devices ;) And that you can revoke access to devices without changing your password.

The problem here is that we would have to update all tokens since they encrypt store the password encrypted. (Else for example encryption etc would not work). So this is a very non trivial thing to do.

**Comment by ChristophWurst** [comment] 2018-01-16 09:39
Duplicate of https://github.com/nextcloud/server/issues/2581#issuecomment-266452286

**Closed by ChristophWurst** 2018-01-16 09:39 UTC
Labels: enhancement
