### ISSUE TITLE
Follow symbolic links

### ISSUE THREAD

**Issue by cgrima** [nextcloud/server#1927] opened 2016-10-26 16:00 UTC
Allow NC to follow symbolic links would provide Unix admins an extra way to oragnize their storage and link them to NC. Some usage examples are available on the forum:
https://help.nextcloud.com/t/symlinks-in-external-storages/4149
https://help.nextcloud.com/t/symbolic-link-support/220

Similar issues were opened for OC, but not solved:
https://github.com/owncloud/core/issues/17669
https://github.com/owncloud/core/issues/8976

### Steps to reproduce
1. On a Unix-like system, symlink (ln -s) a non-empty folder to a storage accessible to your NC server.
2. Optionally, tell NC to re-scan the storage.
3. From within NC web portal, enter the symlinked folder.

### Expected behaviour
The folder content should appear

### Actual behaviour
The Folder is empty

### Server configuration
**Nextcloud version:** 10.0.1

**Comment by nickvergessen** [comment] 2016-10-27 14:31
Duplicate of https://github.com/nextcloud/server/issues/1257#issuecomment-245314285

Please comment in there, if you disagree.

**Closed by nickvergessen** 2016-10-27 14:31 UTC
