### ISSUE TITLE
[NC20] The old server-side-encryption format is enabled

### ISSUE THREAD

**Issue by StealUrKill** [nextcloud/server#24925] opened 2020-12-31 00:11 UTC
### Steps to reproduce
1. run command occ encryption:scan:legacy-format

### Expected behaviour
It should scan and tell me if I am good.

### Actual behaviour
  There are no commands defined in the "encryption:scan" namespace.  
                                                                     
  Did you mean this?                                                 
      encryption                                                     
                      

### Server configuration

**Operating system:**
CentOs
**Web server:**
Apache
**Database:**
MySql
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
20.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
From 19
**Where did you install Nextcloud from:**

![NC20](https://user-images.githubusercontent.com/35749471/103387622-57186d80-4aca-11eb-87c5-917c7b719a66.jpg)

**Comment by kesselb** [comment] 2020-12-31 11:16
Duplicate of https://github.com/nextcloud/server/issues/24681

**Closed by kesselb** 2020-12-31 11:16 UTC
Labels: 0. Needs triage, bug
