### ISSUE TITLE
Missing "data" directory causes error

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8580] opened 2018-02-28 13:28 UTC
### Steps to reproduce
1. Download and unzip nextcloud server file (https://download.nextcloud.com/server/releases/nextcloud-13.0.0.zip)
2. configure web server to point to the directory
3. give permissions to the directory

### Expected behaviour
Tell us what should happen

Nextcloud should either already have the data folder or create the data folder on its own or allow the user to set the storage directory manually from browser.

### Actual behaviour
Tell us what happens instead

Nextcloud throws out a generic error message that gives no clues as to what the actual issue is well before any installation options are allowed.

### Server configuration

**Operating system**:
Ubuntu: 
*Web server:**
Nginx
**Database:**
MariaDB 10.2.3
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
not possible to login or do anything.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
N/A
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
None, this is a fresh install that never started because of the error message.
```
</details>

**Access Log (NGiNX):**

https://hastebin.com/ekabenuyox.log

**Error Log (NGiNX):**

https://hastebin.com/oyujuguqon.log

**PHP 7.2 FPM Log:**

https://hastebin.com/equdehehur.log

**Nextcloud Error Page:**

https://i.imgur.com/ivAXG49.png

**Comment by MorrisJobke** [comment] 2018-03-01 08:10
Thanks for the feedback. Yes - we should make this more obvious and also check it during update (and show proper error messages in the UI).

**Comment by c0fe** [comment] 2018-03-01 14:31
@MorrisJobke perhaps include it by default and if the user sets a different directory, delete the "data" directory?

**Comment by MorrisJobke** [comment] 2018-03-05 09:52
> @MorrisJobke perhaps include it by default and if the user sets a different directory, delete the "data" directory?

Sadly not that easy, because then there could be other side effect during extraction. Better have it available as separate check in the code.

**Comment by arunikayadav42** [comment] 2018-03-05 09:59
Is anybody working on this issue or can I get started with it please?

**Comment by MorrisJobke** [comment] 2018-03-05 15:03
> Is anybody working on this issue or can I get started with it please?

Sure - go ahead. If you need help or a pointer at code part, then just ask. We are happy to help.

**Comment by arunikayadav42** [comment] 2018-03-11 08:40
@MorrisJobke can you please tell me what language do I need to know in order to solve the issue and also please point to the code which will be changed to solve the issue. :)

**Comment by liamdennehy** [comment] 2018-06-30 11:17
@arunikayadav42 I downloaded the same source you linked, and 13.0.4, but I find the data dir is created and populated just fine. Do you have more specific instructions to replicate the error (the hastebin links are now empty)?

**Comment by burned42** [comment] 2018-10-07 10:29
I just found this issue due to the 'Hacktoberfest' label and tried to reproduce the error. I couldn't reproduce it for the 'data' directory, but for the 'config' directory. If the config directory is not writable and the config.php can't be created such a generic error message is displayed. So maybe that was also the case here?
Anyhow, since nobody seems to be working on this right now, I'd like to give it a try to display a more helpful error message in this case :)

**Comment by skjnldsv** [comment] 2020-09-09 11:37
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-09-09 11:37 UTC
Labels: 0. Needs triage, bug, feature: install and update, good first issue, papercut

**Comment by benmordecai** [comment] 2021-09-07 02:05
I am having the same issue on 22.1.1. 

I simply extracted the tar.bz to `/var/www/nextcloud` and chmod the ownership and there is no data folder. When I try to login from my-url.com/nextcloud I get a generic error telling me to check my logs, but there are no logs because they are supposed to be stored in the data directory.
