### ISSUE TITLE
Upon invitations, calendar "personal" is created although there is a valid calender

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#5040] opened 2017-05-22 14:46 UTC
Calendar 1.5.3 on NC12.0 (release)

**Steps to reproduce**
1. create a second calendar, name it (say "MyCalendar"), and delete the default calendar "personal"
2. let someone else invite you to a meeting

**Expected behaviour**
The invitation should be processed in MyCalendar

**Actual behaviour**
If calendar "personal" doesn't exist, it's silently created on-the-fly and the invitation is processed there.

Problem is, that if you - like me - only use e.g. Thunderbird Calendar and more or less only use the web interface to maintain the NC server and apps, you don't notice that you have a new calendar, and appointments therein.

I reported this as https://github.com/nextcloud/calendar/issues/466 first but Georg wrote that "If you have another calendar in place, no new calendar should be created."

**Comment by ethanopp** [comment] 2017-07-30 22:00
+1

**Comment by MorrisJobke** [comment] 2017-09-03 18:56
cc @georgehrke

**Comment by palegrand** [comment] 2017-09-05 19:34
+1  
is there any known work-around?

**Comment by georgehrke** [comment] 2017-09-05 19:36
Please don't comment with +1, 👍 etc. when you can't add anything new. It's only spamming contributors' mail inboxes for no reason.  Use [Github Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead.

If there was a known workaround, it would have been posted here.

Thx! :)

**Comment by deusama** [comment] 2018-08-30 09:39
Sorry to ask one year later, but is there anything that can be done?
We would love to fix it ourselves, just getting some advice where to start searching for this bug would be helpful.

Thanks! :)

**Comment by nursoda** [comment] 2018-08-30 18:50
Took me a while, too, to reproduce NOW ;-) Bug is still there in NC 13 with current Calendar app. To reproduce, you can do everything within Nextcloud web interface. I was missing that when I tried first.

1a) create a dummy user
1b) create a second calender
1c) delete the default calendar
2a) log in as an existing user on the SAME cloud instance
2b) Create a new meeting, invite the dummy USER (selecting it!)
1d) For dummy, the default calendar is re-created and the meeting was created within that.

Oddly enough, I am shown TWO identical dummy users in step 2b.

**Comment by mokkin** [comment] 2019-03-05 16:09
I have realized the issue since NC 14 and reproduced it like @nursoda just yet with NC 15.0.5

To avoid problems in our team I moved my custom named calendar to the auto created "pesonal" one as a workaround.

**Comment by biva** [comment] 2019-03-28 14:02
Any update? Still the same problem with NC15 :(

**Comment by palegrand** [comment] 2019-05-23 14:00
Still the same problem on NC16 :-(

**Comment by georgehrke** [comment] 2019-09-14 13:51
This is done on purpose right now: https://github.com/nextcloud/server/pull/2274

We should introduce an option to define a default calendar (like most other calendar applications outside) and store it in there. If there is no default calendar, take the first writable one (based on calendar order). If there is none, create one.

https://tools.ietf.org/html/rfc6638#section-9.2

**Comment by tcitworld** [comment] 2021-06-25 16:10
Note: We now have the setting in server since https://github.com/nextcloud/server/pull/19852 so even though it's not selectable right now (see https://github.com/nextcloud/calendar/pull/2331) we can still use it straight away.

**Comment by tcitworld** [comment] 2022-10-03 07:12
Closed by https://github.com/nextcloud/server/pull/32361

**Closed by tcitworld** 2022-10-03 07:12 UTC
Labels: enhancement, 1. to develop, feature: dav, feature: caldav
