### ISSUE TITLE
Tagging multiple items at once

### ISSUE THREAD

**Issue by docwhite** [nextcloud/server#26226] opened 2021-03-20 09:53 UTC
When you multiple-select items, an Actions menu shows. It would be nice to have a menu option that opens a modal where you can specify what tags do you want to apply to your selected items. Or any other way of batch tagging would be very useful!

**Comment by Spartachetto** [comment] 2021-03-20 18:57
Duplicate of #10674

**Closed** 2021-03-22 05:26 UTC
Labels: 0. Needs triage, enhancement
