### ISSUE TITLE
Nextcloud 21.0.1 Encryption Errors 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#26489] opened 2021-04-10 02:46 UTC
When you delete a file and restore it it will not go back into the original location shows up in the main location and erros in the log file I never had this issue before after updating to 21.0.1 from 20.0.8 it came up

<details>
<summary>  trash bin database inconsistent! ($user: axheli $filename: officialgooglecloudcertifiedassociatecloudengineerstudyguide.pdf, $timestamp: 1618022190) </summary>

```
{"reqId":6tqvLQotjcAg0MghPBeJ","level":3,"time":"2021-04-10T02:36:36+00:00","remoteAddr":"","user":"","app":"files_trashbin","method":"MOVE","url":"/remote.php/dav/trashbin/axheli/trash/officialgooglecloudcertifiedassociatecloudengineerstudyguide.pdf.d1618022190","message":"trash bin database inconsistent! ($user: axheli $filename: officialgooglecloudcertifiedassociatecloudengineerstudyguide.pdf, $timestamp: 1618022190)","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36","version":"21.0.1.1","id":"60710f70c9977"}
```
</details>

**Comment by axheli** [comment] 2021-04-12 16:07
Once you restore the files looks like they are corrupts then when trying to delete get errors looks like the encryption brakes

 
<details>
<summary>Errors/summary>

```
{"reqId":"70B6Kbet9EosEckPbpyN","level":3,"time":"2021-04-12T16:00:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"Required parameter $tagManager follows optional parameter $fileIdentifier at /var/www/nextcloud/apps/files/lib/Helper.php#220","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":478,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":478,"function":"include"},{"file":"/var/www/nextcloud/lib/composer/composer/ClassLoader.php","line":346,"function":"Composer\\Autoload\\includeFile"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Helper.php","line":109,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php","line":831,"function":"getTrashFiles","class":"OCA\\Files_Trashbin\\Helper","type":"::"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Command/Expire.php","line":58,"function":"expire","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/var/www/nextcloud/lib/private/Command/CommandJob.php","line":36,"function":"handle","class":"OCA\\Files_Trashbin\\Command\\Expire","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OC\\Command\\CommandJob","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/QueuedJob.php","line":46,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.1.1","id":"60746eb513f7a"}

{"reqId":"3Qk8OZnHs76ZjM18V79q","level":4,"time":"2021-04-12T15:58:21+00:00","remoteAddr":"66.158.36.34","user":"axheli","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/axheli/officialgooglecloudcertifiedassociatecloudengineerstudyguide.pdf","message":{"Exception":"Error","Message":"Call to a member function getId() on array","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Cache/Updater.php","line":160,"function":"remove","class":"OC\\Files\\Cache\\Cache","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":330,"function":"remove","class":"OC\\Files\\Cache\\Updater","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1180,"function":"removeUpdate","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":725,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":466,"function":"unlink","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/Cache/Cache.php","Line":541,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36","version":"21.0.1.1","id":"60746eb53559c"}

{"reqId":"3Qk8OZnHs76ZjM18V79q","level":3,"time":"2021-04-12T15:58:21+00:00","remoteAddr":"66.158.36.34","user":"axheli","app":"PHP","method":"DELETE","url":"/remote.php/dav/files/axheli/officialgooglecloudcertifiedassociatecloudengineerstudyguide.pdf","message":{"Exception":"Error","Message":"Trying to access array offset on value of type bool at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#669","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":669,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":767,"function":"updateEncryptedVersion","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":623,"function":"copyBetweenStorage","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Storage.php","line":240,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php","line":323,"function":"moveFromStorage","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php","line":108,"function":"move2trash","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":103,"function":"moveToTrash","class":"OCA\\Files_Trashbin\\Trash\\LegacyTrashBackend","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Storage.php","line":203,"function":"moveToTrash","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Storage.php","line":103,"function":"doDelete","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1168,"function":"unlink","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":725,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":466,"function":"unlink","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36","version":"21.0.1.1","id":"60746eb53565e"}
```
</details>

**Comment by jknockaert** [comment] 2021-04-13 15:12
@axheli The 3rd error is a duplicate of #26473

**Comment by axheli** [comment] 2021-04-13 15:15
@jknockaert do you want me to remove the third error from this ticket?

**Comment by jknockaert** [comment] 2021-04-13 15:16
@axheli wait a moment; am still triaging the other issues

**Comment by axheli** [comment] 2021-04-13 15:17
@jknockaert Okay sounds good let me know! Happy to help :)

**Comment by jknockaert** [comment] 2021-04-13 15:35
@axheli The second error is a duplicate of #26544 (I opened a separate ticket for that)
I'll have a look at the other three errors another time

**Comment by axheli** [comment] 2021-04-13 15:47
@jknockaert Thank you so much!

**Comment by andyxheli** [comment] 2021-06-09 02:12
#26980

**Closed** 2021-06-09 02:15 UTC
Labels: 0. Needs triage, bug
