### ISSUE TITLE
Move file dialog is broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2333] opened 2016-11-25 14:29 UTC
Move file dialog is broken on master, tested with Firefox 50

![move](https://cloud.githubusercontent.com/assets/1589737/20628038/2b8265e6-b324-11e6-9bc2-3863b9cb6632.png)

cc @icewind1991

**Comment by LukasReschke** [comment] 2016-11-25 14:32
Dupe of https://github.com/nextcloud/server/issues/2252. Affects all filepicker dialogs.

**Closed by LukasReschke** 2016-11-25 14:32 UTC
Labels: bug, feature: files
