### ISSUE TITLE
OpenID official app activation failed

### ISSUE THREAD

**Issue by kabrana** [nextcloud/server#24338] opened 2020-11-24 10:57 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Log into Nextcloud server as an admin
2. Go to apps, and enable **OpenID Connect user backend**

### Expected behaviour
Application should be enabled successfully and made available through new entry in settings

### Actual behaviour
App's activation fails with following error : **Column name "oc_user_oidc"."display_name" is NotNull, but has empty string or null as default.**
<img width="1677" alt="Screen Shot 2020-11-24 at 2 20 59 AM" src="https://user-images.githubusercontent.com/23243607/100084219-7d3a5600-2e18-11eb-8b83-6a4cef24ccc1.png">

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** tried both, dockerhub and snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'oc2xr2z2g9pp',
  'passwordsalt' => '/mqj',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mariadb',
  'version' => '20.0.2',
  'overwrite.cli.url' => '',
  'installed' => true,
  'allow_local_remote_servers' => true,
);

```
</details>

**Are you using encryption:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[settings] Error: InvalidArgumentException: Column name "oc_user_oidc"."display_name" is NotNull, but has empty string or null as default. at <<closure>>

 0. /var/www/html/lib/private/DB/MigrationService.php line 484
    OC\DB\MigrationService->ensureOracleIdentifierLengthLimit(Doctrine\DBAL\Schema\Schema {}, Doctrine\DBAL\Schema\Schema {}, 3)
 1. /var/www/html/lib/private/DB/MigrationService.php line 414
    OC\DB\MigrationService->executeStep("00005Date20200428123958", false)
 2. /var/www/html/lib/private/Installer.php line 157
    OC\DB\MigrationService->migrate()
 3. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 447
    OC\Installer->installApp("user_oidc")
 4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->enableApps(["user_oidc"], [])
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
 6. /var/www/html/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
 7. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
 9. /var/www/html/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
10. /var/www/html/lib/base.php line 1010
    OC\Route\Router->match("/settings/apps/enable")
11. /var/www/html/index.php line 37
    OC::handleRequest()

POST /settings/apps/enable
from 172.23.0.1 by nextcloud at 2020-11-24T10:36:39+00:00
```
</details>

#### Browser log
<details>

</details>

**Comment by kesselb** [comment] 2020-11-24 20:48
Duplicate of https://github.com/nextcloud/user_oidc/issues/90

**Closed by kesselb** 2020-11-24 20:48 UTC
Labels: 0. Needs triage, bug
