### ISSUE TITLE
while close the image view from favourite/share/recent; the navigation will be change.

### ISSUE THREAD

**Issue by HelloLemon1992** [nextcloud/server#12842] opened 2018-12-05 03:58 UTC
open the image from favourite tab or share/recent, and open an image to view. when click the close, the navigation will change to allFiles.

![image](https://user-images.githubusercontent.com/10297287/49493670-e923fc80-f897-11e8-9704-8527b5753aef.png)

![image](https://user-images.githubusercontent.com/10297287/49489219-f71c5200-f884-11e8-9000-de1ea981d031.png)

when close, the navigation will change to allFiles,  but the navigation should be stay in which is open the image.
![image](https://user-images.githubusercontent.com/10297287/49493537-7450c280-f897-11e8-9516-927f1c0b2be4.png)

**Comment by HelloLemon1992** [comment] 2018-12-13 06:13
apps/gallery/js/slideshowcontrols.js
```
		_exit: function () {
			if (Gallery.Share){
				Gallery.Share.hideDropDown();
			}

			// Only modern browsers can manipulate history
			if (history && history.replaceState) {
				// We simulate a click on the back button in order to be consistent
				//window.history.back();
				this.stop();
			} else {
				// For ancient browsers supported in core
				this.stop();
			}
		},
```

in chrome, if window.history.back(), it will change the current nav;

**Comment by skjnldsv** [comment] 2020-08-25 09:25
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-08-25 09:25 UTC
Labels: 0. Needs triage
