### ISSUE TITLE
Dav URL ..vcf?photo does not resolve if photo is a URI

### ISSUE THREAD

**Issue by myrho** [nextcloud/server#20705] opened 2020-04-28 14:57 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Assume having Nextcloud running at http://nextcloud with an addressbook `testbook`.
2. Run
```php
$curl = curl_init();
curl_setopt($curl, CURLOPT_HEADER, true);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
curl_setopt($curl, CURLOPT_USERPWD, "username:password");
curl_setopt($curl, CURLOPT_URL, "http://nextcloud/remote.php/dav/addressbooks/users/username/testbook/xyz.vcf");
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_POSTFIELDS,<<<VCARD
BEGIN:VCARD
VERSION:3.0
UID:xyz
FN:Humming Bird
PHOTO;TYPE=JPEG;VALUE=URI:http://nextcloud/remote.php/webdav/Photos/Hummingbird.jpg
END:VCARD
VCARD
); 
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-type: text/vcard'));
echo curl_exec($curl);
```
3. Try to fetch `http://nextcloud/remote.php/dav/addressbooks/users/username/testbook/xyz.vcf?photo`

### Expected behaviour
The image should be loaded.

### Actual behaviour
404 HTTP Status code is returned.

### Server configuration

From the latest nextcloud docker image:

**Operating system:** Debian Buster

**Web server:** Apache

**Database:** Sqlite 

**PHP version:** PHP 7.3

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Docker

**List of activated apps:** Contacts

### Client configuration
**Browser:** Latest Chrome/Firefox

### Logs

No error messages appear related to the `...vcf?photo` request in the nextcloud logs (loglevel 0).

**Comment by skjnldsv** [comment] 2020-04-28 19:52
duplicate of https://github.com/nextcloud/server/issues/20143

**Comment by myrho** [comment] 2020-04-28 20:19
Why do you think this issue is a duplicate #20143?

**Comment by kesselb** [comment] 2020-04-28 21:43
I don't think it's a duplicate of #20143 either :)

But using a file as photo that stored in a users Nextcloud account is also not supported. Actually only embedded images as base64 or binary possible: https://github.com/nextcloud/server/blob/192cf12440cdca9f5c044b84a9187605a58d7707/apps/dav/lib/CardDAV/PhotoCache.php#L207

**Comment by skjnldsv** [comment] 2020-04-29 06:29
Ah, I think it was because I was very tired and it was very late for me :grin: :see_no_evil:

**Comment by kesselb** [comment] 2020-04-29 06:40
Just to add: I'm fine with the current implementation. Adding the opportunity to embed external or internal resources by uri adds a lot of complexity. Think about all those security checks for such a feature.

**Comment by myrho** [comment] 2020-04-29 10:42
It is already possible to create vcards with photo URIs and the Contacts app already displays the referenced image (at least in the contact view).

Maybe redirecting a vcf?photo url to the referenced uri would be the easiest solution? So not handling the external resource on the server at all.

**Comment by skjnldsv** [comment] 2020-04-29 10:47
> Maybe redirecting a vcf?photo url to the referenced uri would be the easiest solution? So not handling the external resource on the server at all.

That's a fair idea actually!
Can you open a pr for it? :)

**Comment by szaimen** [comment] 2023-01-09 16:22
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:40 UTC
Labels: bug, needs info, 0. Needs triage
