### ISSUE TITLE
Transfer ownership should check quota

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#15664] opened 2019-05-21 18:27 UTC
When issuing a transfer ownership from userA to userB. The command should check if the quota of userB is sufficient.

If not the command should not even be started and a message should be shown.

**Comment by milux** [comment] 2019-06-17 13:51
This turns out to be the most likely root cause for the issue reported here:
https://help.nextcloud.com/t/occ-files-transfer-ownership-does-not-move-anything/33848/6

It took me 3 hours of investigation until I finally found out that `files:transfer-ownership` does not even check the return value of `$view->rename($this->sourcePath, $this->finalTarget)` and instead proceeds with it's operation, causing silent failure and numerous misleading "Share with id XYZ points at deleted file, skipping" messages.

An abort on failed `rename()` with a message like _"Files could not be transferred. There might be an issue with the file system or the space quota of the target user."_ should absolutely be implemented ASAP.

**Comment by ChristophWurst** [comment] 2019-11-12 14:38
See #17913 :)

**Closed** 2019-11-13 14:05 UTC
Labels: 1. to develop, bug, medium
