### ISSUE TITLE
Webdav openning Microsoft Excel document very slow!!!

### ISSUE THREAD

**Issue by gerardjm** [nextcloud/server#25180] opened 2021-01-18 12:11 UTC
Hi, I have nextcloud 20.0.5 and windows webdav client mapping the nextcloud, all works more or lees fine, but opening Excel files are to much slow, any clue?

Thanks a lot!!!

**Comment by kesselb** [comment] 2021-01-18 19:32
Hi,

Thanks for your report, but this is more of a support request. If you are an enterprise user, please report the problem through https://portal.nextcloud.com and we will help you debug the issue with priority. If you are a home user, you can ask for help on our private user forums on https://help.nextcloud.com.

Note that a bug report is a clear description of a bug in Nextcloud, including the steps to reproduce it on a fresh Nextcloud developer instance. In simple terms, you have to do the work to identify the root cause so our developers can fix it right away. Example code, curl examples or example apps are good ways of showing what is wrong, and we very much welcome patches and links to the relevant code. Also, please make sure you have tested if the issue also happens on the latest daily build of Nextcloud. You can learn how to set up a developer instance here: https://docs.nextcloud.com/server/latest/developer_manual/

Of course, if you can't do this debugging, help.nextcloud.com has other home users who might be willing to help or give pointers. If your business need this issue fixed, we're happy to do the debugging for you as part of our subscription services.

I will close this now, feel free to re-open if you have debugged the problem and can provide more information.

**Closed by kesselb** 2021-01-18 19:32 UTC
Labels: 0. Needs triage, bug

**Comment by hsudbrock** [comment] 2023-04-16 19:19
Hi @gerardjm; could you solve your issue that you had? I am asking since I have the very same issue; accessing nextcloud via WebDav in Windows Explorer works completely fine, except when opening flles with MS Office, where opening the file can take minutes. If you solved the issue, I would be happy about any hints :)

**Comment by gerardjm** [comment] 2023-04-17 06:49
Hello, @hsudbrock the truth is that it was not solved, due to this problem I lost the client and I have no longer implemented webdav with Nextcloud, I'm sorry I can't help you.
