### ISSUE TITLE
NC 13.0.1 Theming not working

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/server#8980] opened 2018-03-26 09:06 UTC
### Steps to reproduce
1. Change Login Picture
2. Logout
3. Same picture
4. Delete Cache
5. Same Picture

### Expected behaviour
New Logo

### Actual behaviour
Old Nextcloud Logo

### Server configuration

**Operating system**: 16.04 LTS

**Web server:** Apache Updated

**Database:** Mysql Updated

**PHP version:** 7.x Actual

**Nextcloud version:** 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Web Installer

<details>
Old Logo overlays the new one in CSS **background-image: url('../img/logo.svg?v=1'** and new one is hidden?

</details>

![1](https://user-images.githubusercontent.com/33482537/37897128-b9c5076a-30e5-11e8-9359-f1adf3bdbe79.PNG)
![2](https://user-images.githubusercontent.com/33482537/37897132-bb3006ea-30e5-11e8-8244-9797409d6b1e.png)

**Comment by JorgeGNL** [comment] 2018-03-26 09:21
#8888

**Comment by juliushaertl** [comment] 2018-03-26 19:07
Duplicate of #8888 Fix is in #8983

**Closed by juliushaertl** 2018-03-26 19:07 UTC
