### ISSUE TITLE
9.1.3.2/4.1 When the image viewer is open, in some cases, not only the alternative text of the visible image is read aloud but also that of a previous one. Additionally, in some case, visually hidden elements of the video player are announced, such as sliders.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42215] opened 2023-12-13 13:38 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-1782286125-v4-n1

9.1.3.2/4.1 When the image viewer is open, in some cases, not only the alternative text of the visible image is read aloud but also that of a previous one. Additionally, in some case, visually hidden elements of the video player are announced, such as sliders.

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:19
duplicate of https://github.com/nextcloud/server/issues/41840

**Closed by JuliaKirschenheuter** 2023-12-14 10:19 UTC
Labels: accessibility
