### ISSUE TITLE
Nextcloud requires to much memory for uploading a large file

### ISSUE THREAD

**Issue by loxK** [nextcloud/server#12792] opened 2018-12-03 15:05 UTC
### Steps to reproduce
1. Set memory limit to 1500Mo
2. Add a 512Mo file
3. Let the nextcloud client try and fail with empty server response
4. Look at webserver logs and notice the memory exhausted error
5. Look at the data folder on the server and notice the .part file is kept, filling the server disk space over time

### Expected behaviour
It shouldn't fail, or should tell what the error is. In case of such an error, the .part files shouldn't be kept

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.2 FPM

**Nextcloud version:** 14

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Comment by MorrisJobke** [comment] 2019-03-25 12:45
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-03-25 12:45 UTC
Labels: 0. Needs triage, bug, needs info
