### ISSUE TITLE
Suggestion:  Anonymous comments on shared URL’s

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#9281] opened 2018-04-23 17:50 UTC
Similar to filedrop #2019, but for any shared nextcloud url.  Anonymous comments could be useful for:
- shared public url’s in general, such as a picture you’ve embedded here on github from your Nextcloud
- #6841 one time downloads, so recipient can confirm they did get the file
  - if link expires after one time download, recipient would have *X* minutes to comment before url expiration.
  - perhaps nextcloud user could write comments as well for anonymous users to read ala: *Please confirm you successfully downloaded the file.  Link expires at 9:50am PST.  Thanks*

**Comment by MorrisJobke** [comment] 2018-04-23 20:00
> Similar to filedrop #2019, but for any shared nextcloud url. Anonymous comments could be useful for:

I would say, that #2019 should be for all public shares. Let's close this then as duplicate of #2019

**Closed by MorrisJobke** 2018-04-23 20:00 UTC
