### ISSUE TITLE
Info on upgrade too wide

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#17921] opened 2019-11-13 07:10 UTC
![image](https://user-images.githubusercontent.com/5836855/68741048-e0ca5a80-05ec-11ea-9275-c50b5233f26e.png)

Branch: master 

I think it was not that wide on previous updates.
Further screens are also auto resizing, but maybe it would be good to have a max-width? E.g. 60% of screen?

@nextcloud/designers

**Comment by ma12-co** [comment] 2019-11-13 08:32
I would go with a fixed width as opposed to a % of the page width

**Comment by skjnldsv** [comment] 2019-11-13 08:40
That what was originally, and we reverted it back by mistake. :/

**Comment by ChristophWurst** [comment] 2019-11-13 14:50
This looks also ugly on the 2fa pages :cry:

**Comment by jancborchardt** [comment] 2019-11-18 07:04
This is a duplicate of **Container on update screen is too wide #17556** ;)

And yes, totally agree. This should have the fixed width like before – as said in that issue.

**Closed by jancborchardt** 2019-11-18 07:04 UTC
Labels: 1. to develop, bug, design, good first issue
