### ISSUE TITLE
Renaming a shared folder fails with error "permission denied"

### ISSUE THREAD

**Issue by mstilkerich** [nextcloud/server#17819] opened 2019-11-05 14:09 UTC
### Steps to reproduce
1. Share a folder to another user
2. Login as the other user
3. Attempt to rename the shared folder

### Expected behaviour
The folder should be renamed (in the namespace of the user the folder was shared to).

### Actual behaviour
The rename operation is rejected by the server with error message "permission denied". (in the web interface, the message simply states the operation failed without more detailed error message).

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache 2.4.29

**Database:**
MySQL 5.7.27

**PHP version:**
7.2.24

**Nextcloud version:** (see Nextcloud admin page)
17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.5 and previous versions. The issue existed in 16.0.5 already, but I don't know when it appeared. 

**Where did you install Nextcloud from:**
Tarball

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_inotify: 0.1.6
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - previewgenerator: 2.1.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.0.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - survey_client
  - systemtags
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

Yes (local), but the issue does occur with folders on internal storage.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 70.0.1

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"lDElDpuYhOhUSFMuaTBu","level":0,"time":"2019-11-05T13:40:06+00:00","remoteAddr":"2003:f8:718:300:71f0:d60b:3601:fa82","user":"myuser","app":"webdav","method":"MOVE","url":"\/nextcloud\/remote.php\/dav\/files\/myuser\/shared\/Documents","message":{"Exception":"Sabre\\DAV\\Exception\\Forbidden","Message":"","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":151,"function":"setName","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":["Documents2"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":642,"function":"move","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/myuser\/shared\/Documents","files\/myuser\/shared\/Documents2"]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/www.example.de\/nextcloud\/remote.php\/dav\/files\/myuser\/shared\/Documents","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https:\/\/www.example.de\/nextcloud\/remote.php\/dav\/files\/myuser\/shared\/Documents","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https:\/\/www.example.de\/nextcloud\/remote.php\/dav\/files\/myuser\/shared\/Documents","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/www.example.de\/nextcloud\/remote.php\/dav\/files\/myuser\/shared\/Documents","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Server.php","line":317,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Node.php","Line":130,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.0.9"}

</details>

**Comment by Dagefoerde** [comment] 2019-11-07 09:19
Which permissions do/did you give to the recipient when you create the share?

I can reproduce this on Nextcloud 16.0.5 if(!) the recipient does not get any kind of permission. If I give all permissions, the recipient is able to rename. Is that the same for you?

In any case, regardless of permissions, the recipient should be able to organise their personal folder structure, so they should be allowed to rename the share.

**Comment by Dagefoerde** [comment] 2019-11-07 09:21
Also, I suppose that #16458  and this issue are duplicates, but there is no progress in either.

**Comment by mstilkerich** [comment] 2019-11-07 10:00
You are right, it is a read-only share and giving the permission "can change" enables the recipient to rename the folder. ("Can reshare"and "Can create" did not enable the recipient to rename it).

**Comment by Dagefoerde** [comment] 2019-11-07 10:02
Okay, so they are in fact duplicates and we observe the same behaviour. @rullzer would you mind having a look or forwarding this to a colleague? Thank you!

**Comment by kesselb** [comment] 2020-01-25 09:40
Closing as duplicate of #16458

**Closed by kesselb** 2020-01-25 09:40 UTC
Labels: 0. Needs triage, bug
