### ISSUE TITLE
Encrypted files are saved as base64 and this is wasting space (roughly 35%)

### ISSUE THREAD

**Issue by dhcgn** [nextcloud/server#30960] opened 2022-02-01 18:02 UTC
**Is your feature request related to a problem? Please describe.**
Encrypted files increases their size by roughly 35%, because they are stored base64 encoded.

> Encrypting files increases their size by roughly 35%, so you must take this into account when you are > > provisioning storage and setting storage quotas. User’s quotas are based on the unencrypted file size, > and not the encrypted file size.
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html

The function openssl_encrypt is used: 

https://github.com/nextcloud/server/blob/89d109a4d9a9c471f9dde7d5bd12a60ca91fe1f9/apps/encryption/lib/Crypto/Crypt.php#L237-L241

Which can return the cipher text in base64 or raw data.

https://www.php.net/manual/en/function.openssl-encrypt.php

**Describe the solution you'd like**

Encrypting files doesn't increases their size by this large factor, because space is not wasted because the final file is not encoded in base64.

With the flag `OPENSSL_RAW_DATA` by calling the funtion openssl-encrypt the raw data is returned.
https://github.com/php/php-src/blob/PHP-7.1.5/ext/openssl/openssl.c#L6409

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by PVince81** [comment] 2022-02-02 09:36
duplicate of https://github.com/nextcloud/server/issues/22156

**Closed by PVince81** 2022-02-02 09:36 UTC
Labels: enhancement, 0. Needs triage
