### ISSUE TITLE
After upgrading to 14.0.9, subfolders do not open in external shares.

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/server#14977] opened 2019-04-05 20:40 UTC
After upgrading to 14.0.9, subfolders do not open in external shares.
Nextcloud 14.0.8.2 - 14.0.9
ubuntu 18.04.1
postgresql 10.6
apache 2.4.29
php 7.2.15

**Comment by lvarnava** [comment] 2019-04-06 05:43
same problem here #14962

**Comment by kesselb** [comment] 2019-04-06 17:36
Thank you! Duplicate of #14962

**Closed by kesselb** 2019-04-06 17:36 UTC
Labels: 0. Needs triage, bug
