### ISSUE TITLE
Can't upload images in "Theming" app

### ISSUE THREAD

**Issue by tuxmaster5000** [nextcloud/server#30410] opened 2021-12-27 09:04 UTC
### Steps to reproduce
1. Try to change the log or login image

### Expected behaviour
That my picture will be used as the new logo/ login image 

### Actual behaviour
Only the error is showing: "no file uploaded"

### Server configuration

**Operating system:* CentOS 7.9*

**Web server:* Apache*

**Database:* MariaDB*

**PHP version:* 8.0.14*

**Nextcloud version:* 22.2.3*

**Updated from an older Nextcloud/ownCloud or fresh install:* Update from version to version*

**Where did you install Nextcloud from:* official tar ball at the first time, then using the updater*

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - admin_audit: 1.12.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.3
  - camerarawpreviews: 0.7.15
  - checksum: 1.1.3
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.7
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - dicomviewer: 1.2.3
  - drawio: 1.0.2
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_videoplayer: 1.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - socialsharing_email: 2.4.0
  - survey_client: 1.10.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.12.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - accessibility
  - activity
  - dashboard
  - encryption
  - federation
  - files_external
  - files_trashbin
  - files_versions
  - firstrunwizard
  - support
  - systemtags
  - user_ldap
  - user_status
  - weather_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "foo.foo.foo"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 83886080,
        "allowZipDownload": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "log_type": "file",
        "loglevel": "1",
        "logfile": "data\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_authfailip": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/foo.foo.foo",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "dicomviewer",
            "socialsharing_email"
        ],
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu"
    },
    "apps": {
        "accessibility": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "activity": {
            "enabled": "no",
            "installed_version": "2.15.0",
            "notify_email_calendar": "0",
            "notify_email_calendar_event": "0",
            "notify_email_calendar_todo": "0",
            "notify_email_comments": "0",
            "notify_email_favorite": "0",
            "notify_email_file_changed": "0",
            "notify_email_file_created": "1",
            "notify_email_file_deleted": "0",
            "notify_email_file_restored": "0",
            "notify_email_public_links": "0",
            "notify_email_remote_share": "0",
            "notify_email_shared": "1",
            "notify_email_systemtags": "0",
            "notify_setting_batchtime": "0",
            "notify_setting_self": "1",
            "notify_setting_selfemail": "1",
            "notify_stream_calendar": "1",
            "notify_stream_calendar_event": "1",
            "notify_stream_calendar_todo": "1",
            "notify_stream_comments": "1",
            "notify_stream_favorite": "1",
            "notify_stream_file_changed": "1",
            "notify_stream_file_created": "1",
            "notify_stream_file_deleted": "1",
            "notify_stream_file_favorite": "0",
            "notify_stream_file_restored": "1",
            "notify_stream_public_links": "1",
            "notify_stream_remote_share": "1",
            "notify_stream_shared": "1",
            "notify_stream_systemtags": "1",
            "signed": "true",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "486"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "3.0.3",
            "types": ""
        },
        "camerarawpreviews": {
            "enabled": "yes",
            "installed_version": "0.7.15",
            "types": "filesystem"
        },
        "checksum": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "filesystem"
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "22.1.1",
            "loopback_tmp_scheme": "https",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1640593202,\"2\":1640595303,\"1\":1640595303,\"4\":1640570403,\"5\":1640401203}",
            "migration_22": "1",
            "migration_22_1": "1",
            "migration_run": "0",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "no",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.0.7",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enable_external_storage": "yes",
            "enterpriseLogoChecked": "yes",
            "global_cache_gc_lastrun": "1436274902",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1399568975.9594",
            "lastcron": "1640595303",
            "lastupdateResult": "[]",
            "lastupdatedat": "1640594703",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "shareapi_allow_links": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_default_permission_cancreate": "no",
            "shareapi_default_permission_candelete": "no",
            "shareapi_default_permission_canshare": "no",
            "shareapi_default_permission_canupdate": "no",
            "shareapi_default_permissions": "1",
            "shareapi_enable_link_password_by_default": "no",
            "shareapi_enforce_expire_date": "yes",
            "shareapi_enforce_internal_expire_date": "yes",
            "shareapi_enforce_links_password": "yes",
            "shareapi_exclude_groups": "no",
            "shareapi_exclude_groups_list": "[\"\"]",
            "shareapi_only_share_with_group_members": "yes",
            "shareapi_only_share_with_membership_groups": "yes",
            "shareapi_share_policy": "groups_only",
            "theming.variables": "e8d257871d8477ae95f3ea8b7fdf909e",
            "umgmt_show_backend": "false",
            "umgmt_show_email": "true",
            "umgmt_show_storage_location": "false",
            "updater.secret.created": "1637077363",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "no",
            "installed_version": "7.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.19.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventReminders": "yes",
            "sendEventRemindersPush": "no",
            "types": "filesystem"
        },
        "dicomviewer": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.8.1",
            "types": ""
        },
        "drawio": {
            "DrawioAutosave": "yes",
            "DrawioLang": "auto",
            "DrawioOffline": "no",
            "DrawioTheme": "kennedy",
            "DrawioUrl": "https:\/\/embed.diagrams.net",
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "52",
            "backgroundwatcher_previous_folder": "18",
            "cronjob_scan_files": "500",
            "default_quota": "100 MB",
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "no",
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,dropbox,googledrive,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.3.1",
            "signed": "true",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.14.0",
            "lookupServerEnabled": "no",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "0.3",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "no",
            "installed_version": "1.10.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "no",
            "installed_version": "1.0.3",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": ""
        },
        "forms": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "signed": "true",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "relativedates": "",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "market": {
            "enabled": "no",
            "installed_version": "0.2.3",
            "market": "0.2.3",
            "signed": "true",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "piwik": {
            "enabled": "no",
            "installed_version": "0.8.0",
            "siteId": "8",
            "trackDir": "true",
            "trackUser": "true",
            "types": "",
            "url": "https:\/\/foo.foo.foo\/"
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "readableLocation": "de",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.2",
            "types": "filesystem"
        },
        "serverinfo": {
            "cached_count_filecache": "13348",
            "cached_count_storages": "40",
            "enabled": "[\"admin\"]",
            "installed_version": "1.12.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "enforcePasswordProtection": "no",
            "installed_version": "1.12.0",
            "sendpasswordmail": "no",
            "types": "filesystem"
        },
        "socialsharing_email": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": ""
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "no",
            "installed_version": "1.5.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "encryption": "yes",
            "installed_version": "1.10.0",
            "last_report": "{\"id\":\"oced6c1c3c6e\",\"items\":[[\"server\",\"version\",\"22.2.3.0\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"yes\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"8.0.14\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.6.5\"],[\"database\",\"size\",20807680],[\"apps\",\"accessibility\",\"disabled\"],[\"apps\",\"activity\",\"disabled\"],[\"apps\",\"admin_audit\",\"1.12.0\"],[\"apps\",\"admin_dependencies_chk\",\"disabled\"],[\"apps\",\"bruteforcesettings\",\"2.3.0\"],[\"apps\",\"calendar\",\"3.0.2\"],[\"apps\",\"camerarawpreviews\",\"0.7.15\"],[\"apps\",\"checksum\",\"1.1.3\"],[\"apps\",\"circles\",\"22.1.1\"],[\"apps\",\"cloud_federation_api\",\"1.5.0\"],[\"apps\",\"comments\",\"1.12.0\"],[\"apps\",\"configreport\",\"disabled\"],[\"apps\",\"contacts\",\"4.0.6\"],[\"apps\",\"contactsinteraction\",\"1.3.0\"],[\"apps\",\"dashboard\",\"disabled\"],[\"apps\",\"dav\",\"1.19.0\"],[\"apps\",\"dicomviewer\",\"1.2.3\"],[\"apps\",\"documents\",\"disabled\"],[\"apps\",\"drawio\",\"1.0.2\"],[\"apps\",\"federatedfilesharing\",\"1.12.0\"],[\"apps\",\"federation\",\"disabled\"],[\"apps\",\"files\",\"1.17.0\"],[\"apps\",\"files_external\",\"disabled\"],[\"apps\",\"files_locking\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"2.3.1\"],[\"apps\",\"files_rightclick\",\"1.1.0\"],[\"apps\",\"files_sharing\",\"1.14.0\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"disabled\"],[\"apps\",\"files_versions\",\"disabled\"],[\"apps\",\"files_videoplayer\",\"1.11.0\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"disabled\"],[\"apps\",\"forms\",\"disabled\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"logreader\",\"2.7.0\"],[\"apps\",\"lookup_server_connector\",\"1.10.0\"],[\"apps\",\"market\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.11.0\"],[\"apps\",\"notifications\",\"2.10.1\"],[\"apps\",\"oauth2\",\"1.10.0\"],[\"apps\",\"password_policy\",\"1.12.0\"],[\"apps\",\"photos\",\"1.4.0\"],[\"apps\",\"piwik\",\"disabled\"],[\"apps\",\"privacy\",\"1.6.0\"],[\"apps\",\"provisioning_api\",\"1.12.0\"],[\"apps\",\"quota_warning\",\"1.13.0\"],[\"apps\",\"recommendations\",\"1.1.0\"],[\"apps\",\"search_lucene\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.12.0\"],[\"apps\",\"settings\",\"1.4.0\"],[\"apps\",\"sharebymail\",\"1.12.0\"],[\"apps\",\"socialsharing_email\",\"2.4.0\"],[\"apps\",\"support\",\"disabled\"],[\"apps\",\"survey_client\",\"1.10.0\"],[\"apps\",\"systemtags\",\"disabled\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"text\",\"3.3.0\"],[\"apps\",\"theming\",\"1.13.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.11.0\"],[\"apps\",\"twofactor_u2f\",\"6.3.0\"],[\"apps\",\"updatenotification\",\"1.12.0\"],[\"apps\",\"updater\",\"disabled\"],[\"apps\",\"user_saml\",\"disabled\"],[\"apps\",\"user_status\",\"disabled\"],[\"apps\",\"viewer\",\"1.6.0\"],[\"apps\",\"weather_status\",\"disabled\"],[\"apps\",\"workflowengine\",\"2.4.0\"],[\"stats\",\"num_files\",13342],[\"stats\",\"num_users\",19],[\"stats\",\"num_storages\",40],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",20],[\"stats\",\"num_storages_other\",19],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",48],[\"files_sharing\",\"num_shares_user\",30],[\"files_sharing\",\"num_shares_groups\",7],[\"files_sharing\",\"num_shares_link\",6],[\"files_sharing\",\"num_shares_link_no_password\",6],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_1\",\"24\"],[\"files_sharing\",\"permissions_1_1\",\"6\"],[\"files_sharing\",\"permissions_2_1\",\"5\"],[\"files_sharing\",\"permissions_3_1\",\"6\"],[\"files_sharing\",\"permissions_0_3\",\"2\"],[\"files_sharing\",\"permissions_1_5\",\"1\"],[\"files_sharing\",\"permissions_0_15\",\"3\"],[\"files_sharing\",\"permissions_0_19\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1639738204",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "3",
            "color": "#00387b",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "name": "Frank's Speicher",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "twofactor_u2f": {
            "enabled": "yes",
            "installed_version": "6.3.0",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "2.2.0",
            "calendar": "3.0.2",
            "checksum": "1.1.3",
            "contacts": "4.0.6",
            "core": "22.2.3.0",
            "dicomviewer": "1.2.2",
            "enabled": "[\"admin\"]",
            "files_pdfviewer": "1.2.1",
            "files_rightclick": "0.15.1",
            "installed_version": "1.12.0",
            "notify_groups": "[\"admin\"]",
            "piwik": "0.8.0",
            "quota_warning": "1.13.0",
            "socialsharing_email": "2.4.0",
            "theming": "1.4.5",
            "twofactor_u2f": "6.2.0",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": ""
        },
        "user_saml": {
            "enabled": "no",
            "general-allow_multiple_user_back_ends": "1",
            "general-idp0_display_name": "Test Login",
            "general-require_provisioned_account": "1",
            "general-uid_mapping": "sAMAccountName",
            "idp-entityId": "http:\/\/foo.foo.foo\/adfs\/services\/trust",
            "idp-singleLogoutService.url": "https:\/\/foo.foo.foo\/adfs\/ls\/?wa=wsignout1.0",
            "idp-singleSignOnService.url": "https:\/\/foo.foo.foo\/adfs\/ls\/IdpInitiatedSignon.aspx",
            "idp-x509cert": "FOO",
            "installed_version": "3.1.3",
            "providerIds": "1,2",
            "type": "saml",
            "types": "authentication"
        },
        "user_status": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "filesystem"
        }
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no.

### Client configuration
**Browser:* Firefox 95*

**Operating system:* Fedora 34*

#### Web server error log
<details>
<summary>Web server error log</summary>

```
XXXX - - [27/Dec/2021:10:01:56 +0100] "POST /apps/theming/ajax/uploadImage HTTP/1.1" 422 65 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No line was logged
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
XHRPOST https://fooo/apps/theming/ajax/uploadImage [HTTP/1.1 422 Unprocessable Entity 171ms]

```
</details>

**Comment by acsfer** [comment] 2022-01-03 22:51
Duplicate of https://github.com/nextcloud/server/issues/18328
Continue discussion there if needed.

**Closed by acsfer** 2022-01-03 22:51 UTC
Labels: bug, 0. Needs triage
