### ISSUE TITLE
[Bug]: After upgrade 27.0.x->27.1.0 public-type shares (web link) with self-generated password don't work

### ISSUE THREAD

**Issue by dea-75** [nextcloud/server#40493] opened 2023-09-19 08:50 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi all,
I just upgraded to version 27.1.0 from the previous last version of 27.0.x and a problem came up (upgrade all ok).
When I generate a public share (web link) having set up forced password usage a random password is (correctly) generated.
Process that has always worked correctly on version 27.0.x.
However, the automatic password appears to have expired a few seconds ago.
If I set a password by typing it in, it works correctly.

PLEASE NOTE: 

the problem occurs ONLY on links with automatically generated password on version 27.1.0.
If the link was previously generated (27.0.x or 26.0.x) there is no problem.
The same behavior has been verified on two different servers.

### Steps to reproduce

1.I create a public share
2.An automatic password is assigned (because it is forced)
3.Sharing appears to have expired a few seconds ago

If I set a password manually (overwriting the automatic one) it works correctly.

### Expected behavior

That the link is working properly

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment] 2023-09-19 08:58
cc @Fenn-CS @sorbaugh

**Comment by sorbaugh** [comment] 2023-09-19 12:51
Hi!

Thanks for reporting this issue and for providing detailed steps. We've attempted to reproduce the issue following your steps, but we're encountering some difficulty in replicating it on our end. Can you provide us some additional information that could help us further diagnose the problem? For example, are you getting any specific error messages (screenshots are awesome)? What Browser/Version are you using?

**Comment by dea-75** [comment] 2023-09-19 14:08
> Hi!
> 
> Thanks for reporting this issue and for providing detailed steps. We've attempted to reproduce the issue following your steps, but we're encountering some difficulty in replicating it on our end. Can you provide us some additional information that could help us further diagnose the problem? For example, are you getting any specific error messages (screenshots are awesome)? What Browser/Version are you using?

Hi !

![Screenshot_20230919_150151](https://github.com/nextcloud/server/assets/62520276/f9d6c54f-9777-45a7-a38e-960717da3d5a)

this is the screenshot with the error display.
Sorry for the mixed language (ita/eng).

"scadenza password alcuni secondi fa " => "password expiration a few seconds ago "

Keep in mind that the problem was verified on both edge and chrome, on two different servers.

**Comment by dea-75** [comment] 2023-09-19 18:41
> Hi!
> 
> Thanks for reporting this issue and for providing detailed steps. We've attempted to reproduce the issue following your steps, but we're encountering some difficulty in replicating it on our end. Can you provide us some additional information that could help us further diagnose the problem? For example, are you getting any specific error messages (screenshots are awesome)? What Browser/Version are you using?

A clarification:
-) the problem occurs only during mail link sharing (during the generation of sharing with mail link sending)
-) as shown in the screenshot above, going to the advanced options
-) the automatically generated password turns out to be expired, so if you directly press the "proceed" button you will be notified that the random password you just created has expired
-) If you edit by hand, everything works smoothly

**Comment by xprntb3** [comment] 2023-09-20 10:47
> > Hi!
> > Thanks for reporting this issue and for providing detailed steps. We've attempted to reproduce the issue following your steps, but we're encountering some difficulty in replicating it on our end. Can you provide us some additional information that could help us further diagnose the problem? For example, are you getting any specific error messages (screenshots are awesome)? What Browser/Version are you using?
> 
> A clarification: -) the problem occurs only during mail link sharing (during the generation of sharing with mail link sending) -) as shown in the screenshot above, going to the advanced options -) the automatically generated password turns out to be expired, so if you directly press the "proceed" button you will be notified that the random password you just created has expired -) If you edit by hand, everything works smoothly

I am having the exact same Issue as described in this post with the current version.
Also like OP i am using another language than english

**Comment by Fenn-CS** [comment] 2023-09-20 11:12
> A clarification:
> -) the problem occurs only during mail link sharing (during the generation of sharing with mail link sending)
> -) as shown in the screenshot above, going to the advanced options
> -) the automatically generated password turns out to be expired, so if you directly press the "proceed" button you will be notified that the random password you just created has expired
> -) If you edit by hand, everything works smoothly

Thanks for the additional context. Looking at it.

**Comment by dea-75** [comment] 2023-09-21 07:35
> > A clarification:
> > -) the problem occurs only during mail link sharing (during the generation of sharing with mail link sending)
> > -) as shown in the screenshot above, going to the advanced options
> > -) the automatically generated password turns out to be expired, so if you directly press the "proceed" button you will be notified that the random password you just created has expired
> > -) If you edit by hand, everything works smoothly
> 
> Thanks for the additional context. Looking at it.

I understand that the problem has been identified and solved.
How do I download the modified files (or diffs) to apply to version 27.1.0 in production ?

Very thanks

**Comment by Fenn-CS** [comment] 2023-09-21 07:53
> I understand that the problem has been identified and solved.
> How do I download the modified files (or diffs) to apply to version 27.1.0 in production ?
> 
> Very thanks

It would get released in [27.1.1](https://github.com/nextcloud/server/pull/40525) which should be available for download/update early next week, worst case. :)

**Comment by dea-75** [comment] 2023-09-21 12:43
> > I understand that the problem has been identified and solved.
> > How do I download the modified files (or diffs) to apply to version 27.1.0 in production ?
> > Very thanks
> 
> It would get released in [27.1.1](https://github.com/nextcloud/server/pull/40525) which should be available for download/update early next week, worst case. :)

OK, 27.1.1 now works but:
![immagine](https://github.com/nextcloud/server/assets/62520276/a8bb7ad6-b52e-48fa-99ae-8253543fa9ee)

Show again ""password expired a few seconds ago ""
but unlike before it works correctly without manually resetting the password.

Only the warning appears that the pre set random password + expired.

**Comment by Fenn-CS** [comment] 2023-09-21 16:11
> Only the warning appears that the pre set random password + expired.

While I would confirm this later, please @dea-75 clear you cache (if enabled) and report if anything changes.

Thanks for the follow up.

**Comment by Fenn-CS** [comment] 2023-09-21 16:26
@dea-75, Right, would be sorted out.

**Comment by Fenn-CS** [comment] 2023-09-21 16:31
Since this commit has already been back-ported this last been would be shipped in with https://github.com/nextcloud/server/issues/40438.

**Comment by dea-75** [comment] 2023-09-21 16:42
> Since this commit has already been back-ported this last been would be shipped in with #40438.

I can confirm. 

Browser chrome,  reset cache, same problem on 27.1.1.
There isn't problem and the password works but the alert persist... 
"password expired a few seconds ago "

**Closed** 2023-09-26 07:05 UTC
Labels: bug, 1. to develop, feature: sharing, regression, 27-feedback
