### ISSUE TITLE
Users having insufficient space to store a file isn't a server-specific warning

### ISSUE THREAD

**Issue by Justinzobel** [nextcloud/server#49586] opened 2024-12-02 07:08 UTC
This is an error in the server log:
```
InsufficientStorage Insufficient space in /InstantUpload/Camera/IMG_20241202_104554.jpg, 4614206 required, 0 available
```

This isn't an issue the server admin needs to be concerned about, this error shouldn't be presented to the admin, it should be presented to the user. It can go in the log but it should not be at the Error level.

**Comment by joshtrichards** [comment] 2024-12-02 16:02
Duplicate of #20514

**Closed by joshtrichards** 2024-12-02 16:02 UTC
Labels: enhancement, 0. Needs triage
