### ISSUE TITLE
Avoid webdav prompt for credentials

### ISSUE THREAD

**Issue by Herz3h** [nextcloud/server#5610] opened 2017-07-05 09:16 UTC
Hello,

First of all, this is not really a bug. 

Currently using nextcloud and i'm trying to open docx(Word documents) files that are stored on nextcloud, using Microsoft Word, but it prompts for a username and password every time i open a file from nextcloud. 

Is there a workaround so that credentials are remembered and prompt stops showing up all time, as it is ruining user experience ?

Thanks in advance.

**Comment by MorrisJobke** [comment] 2017-08-30 10:26
We noticed this as well in the past and did some changes. Could I ask you to test the latest maintenance releases for this? 12.0.2+ for example. Until then I will close this one here.

**Closed by MorrisJobke** 2017-08-30 10:26 UTC

**Comment by carlu93** [comment] 2017-08-30 10:49
@MorrisJobke tested 12.0.2. Or do I need to try a daily build? Word / Excel etc. still ask for a password. But I think this behaviour can't be fixed, because Office always opens a new connection to the webdav endpoint. So it needs credentials in my understanding. Weird thing is, that Word etc. fill out the credentials. I just need to click OK in the dialogue. Maybe this will help! :)
I'm using Windows 10 Build 15063 and latest Office 2016.

**Comment by MorrisJobke** [comment] 2017-08-30 11:01
Ummm ... this sounds weird. But we both talk about the web UI, right? Or do you use a Windows Explorer mount? (as in having a network drive within Windows, that mounts Nextcloud)

In the latter one we can't do much, I think. If the Explorer forgets the credentials, that is totally out of scope for us. But we tested this and the mount properly worked in our scenarios without a re-prompt for the password. See https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html#accessing-files-using-microsoft-windows for details on how to mount Nextcloud within Windows.

**Comment by carlu93** [comment] 2017-08-30 11:16
I think there might be a little misunderstanding. @Herz3h and me are talking about WebDav meaning 
the Windows Explorer mount. In that case the bug is not really fixed imho. Mounting is no problem. Opening the files i mentioned is ruining the experience a little. Maybe someone can elaborate on this, as the manual is not helping in that special case. Basically it's working, but opening files (especially Office / PDFs) is the problem here.

**Comment by MorrisJobke** [comment] 2017-08-30 12:07
> Another case i don't understand is why the Webinterface tells me to use /remote.php/webdav and the manual tells me to use /remote.php/dav/files/USERNAME. I'm a little bit confused :D

We just moved the endpoints. The /webdav/ still works and is the old way, because it isn't unique from a URL point of view. The other one now incorporates the userid, that is then unique per server and has some other nice advantages. It isn't fully updated everywhere, but we will keep both up and running as long as possible.

**Comment by Herz3h** [comment] 2018-01-02 09:29
Same problem with latest version of Nextcloud. The issue I mentioned in OP is that when I open a link to a nextcloud file from my browser (through my webapp, using the ms-word: protocol), the document opens fine in Microsoft Word, but there is a prompt everytime I open.

Just to be clear, I've not mounted Nextcloud on any drive, I'm just trying to open documents hosted on Nextcloud in Microsoft Word in order to use the direct editing feature (not having to download, and reupload the document every time).

As a progress in my research I found this [ithit ajax library](https://www.webdavsystem.com/ajax/) but it requires webdav server to support cookies authentication. Is this a supported feature ?

**Comment by roedie** [comment] 2018-03-27 07:54
Hi,

I think the reason why this doesn't work is described here: https://support.microsoft.com/en-us/help/943280/prompt-for-credentials-when-you-access-webdav-based-fqdn-sites-in-wind

Word and Excel give password prompts because this is by design. Somewhere halfway in this page it is mentioned:

> If you have added the AuthForwardServerList registry entry, be aware that if Basic authentication or Digest authentication is implemented in the network, using the registry entry cannot prevent the prompt for credentials. This behavior is by design for Basic authentication and Digest authentication.

So, the issue is not really a Nextcloud issue which is a bit of a pity. Using something like NTLMAuth might fix this, but I haven't tested it.

**Comment by Herz3h** [comment] 2018-03-27 16:04
I ended up using ITHit WebDav to have cookies authentication. Its a limitation on Windows anyway. It sucks but it is how it is.

Thanks for the infos.
