### ISSUE TITLE
After updating to NC16.0.2 no apps and no users visible

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#16235] opened 2019-07-04 15:47 UTC
After updating from 16.0.1 to 16.02 I cannot see my apps and users. 

Nothing special in the log. 

I get a message about many files not passing the integrity check. It seems they relate to the viewer which I never installed but updated recently. As I cannot see the apps I tried to remove the viewer app by rm -rf /apps/viewer/  It did not work. 
I have deleted the files but still get the same error, and no apps visible

I restarted the server - the integrity check is now OK. Nothing seen in the log - BUT still no apps visible... 

I tried occ maintenance:repair - same result. Cannot use the issue template as it is not accessible

Ubuntu 18.04, nginx

1. Update NC
2. Clique on the right upper letter indicating your name. 
3. Clique on Apps or Users
4. You get a blank page - no apps or no users shown

**Comment by MeCias** [comment] 2019-07-04 16:13
can confirm both issues

All of those viewer files failing the check:

Results
=======
- viewer
	- EXTRA_FILE
		- cypress.json
		- cypress/plugins/index.js
		- cypress/fixtures/image-small.png
		- cypress/fixtures/video.ogv
		- cypress/fixtures/video.mkv
		- cypress/fixtures/image.bmp
		- cypress/fixtures/image.png
		- cypress/fixtures/image4.jpg
		- cypress/fixtures/video2.mp4
		- cypress/fixtures/image.gif
		- cypress/fixtures/image1.jpg
		- cypress/fixtures/image.svg
		- cypress/fixtures/video.webm
		- cypress/fixtures/video1.mp4
		- cypress/fixtures/image2.jpg
		- cypress/fixtures/image3.jpg
		- cypress/utils/index.js
		- cypress/integration/image-small.png.spec.js
		- cypress/integration/images.spec.js
		- cypress/integration/files.spec.js
		- cypress/integration/video.mp4.spec.js
		- cypress/integration/image.png.spec.js
		- cypress/integration/video.webm.spec.js
		- cypress/integration/videos.spec.js
		- cypress/integration/video.ogv.spec.js
		- cypress/integration/image.svg.spec.js
		- cypress/integration/image.gif.spec.js
		- cypress/integration/video.mkv.spec.js
		- cypress/stop.sh
		- cypress/support/index.js
		- cypress/support/commands.js
		- cypress/start.sh

**Comment by kesselb** [comment] 2019-07-04 16:37
Duplicate of https://github.com/nextcloud/server/issues/16229

**Closed by kesselb** 2019-07-04 16:37 UTC
Labels: 0. Needs triage, bug

**Comment by rollanders** [comment] 2019-07-04 21:40
Sorry. Deleting the cypress-files solves the integrity check error, but not the blank app and users. 
I deleted the files, used the newest updater (it was not available for a moment but reappeared). 
Update with no problems. BUT there is no apps and no users visible.

**Comment by AaronADev** [comment] 2019-07-05 05:03
@rollanders  I had the same exact issue. It appears to have something to do with retaining the web session information from before the upgrade (though I am not entirely sure). I had to log out of my instance and log back in and all of the apps and users became visible again. Everything started working and appearing as normal after signing back in to the Web UI with the except of file permission problems regarding dragging and dropping files into the blank space under folders. Let us know if that simple trick worked for you as well.
