### ISSUE TITLE
Automatically login the user via browser link

### ISSUE THREAD

**Issue by ngohuytrieu** [nextcloud/server#33634] opened 2022-08-22 03:43 UTC
Hi guys, Is there any way to login into nextcloud server via url on the browser?

**Like:** https://nextcloud.example/login?token=<token> or https://nextcloud.example/login?user=<user>&password=<app_password>

In this document only show you to call APIs to get an app password
https://docs.nextcloud.com/server/19/developer_manual/client_apis/LoginFlow/index.html#login-in-the-user

**Comment by joshtrichards** [comment] 2024-01-31 23:27
Duplicate of #9342

**Closed by joshtrichards** 2024-01-31 23:27 UTC
Labels: enhancement, 0. Needs triage, feature: authentication
