### ISSUE TITLE
Wrong encryption status in NC19?

### ISSUE THREAD

**Issue by OliverPifferi** [nextcloud/server#21320] opened 2020-06-08 16:25 UTC
Hey everyone,

with NC18, I used the default encryption module and the privacy screen showed by that my files are protection by the default encryption module.

With NC19, it seems as if the files aren’t encrypted anymore and I may just check the state of “Disk Encryption” - is this just a wrong kind of displaying the status? When looking via command line / shell, files are indeed encrypted so it seems as if this is just a wrong kind of displaying the encryption status.

This error could be reproduced with an instance of NC 19 which was updated from 18.0.4 and a fresh installation as well, both founded by Debian and Ubuntu running Apache and PHP with MariaDB-database backend. The default encryption module is activated and the contents of the saved files are indeed... well, encrypted ;-) !

<img width="1127" alt="Bildschirmfoto 2020-06-08 um 18 22 05" src="https://user-images.githubusercontent.com/42076599/84055451-24374c80-a9b5-11ea-9b1b-38346e0bd102.png">

<img width="463" alt="Bildschirmfoto 2020-06-08 um 18 21 50" src="https://user-images.githubusercontent.com/42076599/84055448-23061f80-a9b5-11ea-8999-57ee5269d59a.png">
<img width="420" alt="Bildschirmfoto 2020-06-08 um 18 21 54" src="https://user-images.githubusercontent.com/42076599/84055450-239eb600-a9b5-11ea-8f12-a001fd05830f.png">

Thanks and best regards,

Oliver

**Comment by kesselb** [comment] 2020-06-08 17:28
Closing as duplicate of https://github.com/nextcloud/privacy/issues/427

Thanks for reporting :+1: Seems the checkbox is broken.

**Closed by kesselb** 2020-06-08 17:28 UTC
Labels: 0. Needs triage, bug
