### ISSUE TITLE
[Bug]: Your storage is full

### ISSUE THREAD

**Issue by mmcg180** [nextcloud/server#43362] opened 2024-02-05 17:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Recently upgraded to NC28.0.2. One user is getting error message "Your storage is full, files cannot be uploaded or synced!". We use AWS S3 for files storage. Server storage is at 48%. We don't use quotas, all users are unlimited. Running on Ubuntu 18 64-bit. Message does not appear in nextcloud.log, even with level set to 0 (debug).

### Steps to reproduce

1. Message appears anytime user refreshes page
2.
3.

### Expected behavior

Message should not appear

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "bmh-nextcloud-rd-prime-store",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "region": "eu-west-2",
                "use_ssl": true,
                "use_path_style": false
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "raven.biomech.us"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "https:\/\/raven.biomech.us",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "logfile": "nextcloud.log",
        "loglevel": 0,
        "default_phone_region": "US",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "Non-MFA"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 14
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - unsplash: 2.2.1 (installed 2.2.1)
  - user_ldap: 1.19.0
```

### Nextcloud Logs

```shell
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpModules","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOpcacheSetup","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOutdated","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\PhpOutputBuffering","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\RandomnessSecure","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\ReadOnlyConfig","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\SupportedDatabase","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\SystemIs64bit","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Settings\\SetupChecks\\TransactionIsolation","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"9JSvLLH9ciqR5dFxdr7j","level":0,"time":"2024-02-05T17:20:10+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Running check OCA\\Theming\\SetupChecks\\PhpImagickModule","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":[]}
{"reqId":"EyHugIBqI3ZED4QXPqaF","level":0,"time":"2024-02-05T17:20:20+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"logreader","method":"PUT","url":"/index.php/apps/logreader/api/settings","message":"Updating AppConfig: shownLevels => [1,2,3,4]","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":{"app":"logreader"}}
{"reqId":"sb5gMykije6bGVoeO29T","level":0,"time":"2024-02-05T17:21:03+00:00","remoteAddr":"96.248.5.247","user":"mike7171","app":"logreader","method":"PUT","url":"/index.php/apps/logreader/api/settings","message":"Updating AppConfig: dateTimeFormat => raw","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0","version":"28.0.2.5","data":{"app":"logreader"}}
```

**Comment by solracsf** [comment] 2024-02-05 18:02
Duplicate of https://github.com/nextcloud/server/issues/43280

**Closed by solracsf** 2024-02-05 18:02 UTC
Labels: bug, 0. Needs triage
