### ISSUE TITLE
Ghost files in cache due to fast operations

### ISSUE THREAD

**Issue by faulix** [nextcloud/server#5622] opened 2017-07-05 15:15 UTC
### Steps to reproduce
0. Use the client app for synchronization
1. Copy a synchronized folder locally (gets copied with prefix "copy of" or similar)
2. Rename the folder quickly

### Expected behaviour
The final folder should be synchronized, the interim versions should be deleted.

### Actual behaviour
Ghost files occur, as the interim files are created in the filecache, but no files exist on the harddisk.

### Server configuration

**PHP version:** 7

**Nextcloud version:** 12.0.0

### Problem tracking

I think the problem occurs when a file gets updated locally while the file synchronization runs. The upload of the file seems to abort, but there is no cache rollback as the entry is already created (assumption).

**Comment by LukasReschke** [comment] 2017-07-20 09:56
cc @icewind1991

**Comment by faulix** [comment] 2017-07-22 19:40
I should also mention that neither `occ files:cleanup` nor `occ files:scan` delete the ghost files

**Comment by MorrisJobke** [comment] 2017-08-31 08:18
Looks like a duplicate of #741 

Let's continue there.

**Closed by MorrisJobke** 2017-08-31 08:18 UTC
Labels: bug, feature: filesystem
