### ISSUE TITLE
Group Folders additional rights setting shows every now and then

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/server#19132] opened 2020-01-25 12:55 UTC
Create a group folder, setup group permissions and additional rights.
Go to your files - Open your group folder - click share button:

![Bildschirmfoto_2020-01-25_13-17-12](https://user-images.githubusercontent.com/12480617/73121315-23a79780-3f79-11ea-90f1-f25c0fadd40b.png)

So far so good...
Navigate to settings, apps, user etc.
Go back to your group folder - click share button:

![Bildschirmfoto_2020-01-25_13-52-00](https://user-images.githubusercontent.com/12480617/73121393-e263b780-3f79-11ea-885b-215253936799.png)

Setting is gone!
Reload your browser, setting reappears, but only every now and then, sometimes you have to reload 3-4 times...sometimes it doesn't work at all...setting is gone.

**Comment by kesselb** [comment] 2020-01-25 14:41
Please use the issue template to report bugs. To triage this add Nextcloud and Group Folders version to your report.

cc @wiswedel server or group folders repository?

**Comment by axel-rank** [comment] 2020-01-25 14:46
Nextcloud 18.0.0, Groupfolders 6.0.0

**Comment by axel-rank** [comment] 2020-01-25 18:08
Seems to be related only to Firefox (72.0.2).
Other Browsers (Chromium, Falkon) working.

**Comment by fschrempf** [comment] 2021-04-09 09:13
Closing this as duplicate of https://github.com/nextcloud/groupfolders/issues/894.

**Closed by fschrempf** 2021-04-09 09:13 UTC
Labels: 0. Needs triage, bug
