### ISSUE TITLE
RuntimeException: File entry could not be inserted but could also not be selected with getId() in order to perform an update

### ISSUE THREAD

**Issue by Silv4n** [nextcloud/server#21811] opened 2020-07-13 11:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open folder on Web or try to sync it
2. On the top right corner an error appears and on Sync Client it stops syncing
3.

### Expected behaviour
The folder should open and the content should be accessible

### Actual behaviour
- An error occurs and the users gets thrown back to the main page
- On the sync client the user gets an error message, that the file is not accessible
- This doesn't happen on every file or folder, only on a few (I couldn't make out a pattern)

### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
Apache 2.4.29
**Database:**
PostgreSQL 12.2
**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
19.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
No
**Where did you install Nextcloud from:**
Nextcloud Hansson VM
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_inotify: 0.1.8
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 6.0.6
  - impersonate: 1.6.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - calendar
  - contacts
  - deck
  - encryption
  - mail
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "xxx.xxx.xxx.xxx",
            "nc.example.com",
            "nc.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/nc.example.com\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": "true",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": "false",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "logtimezone": "Europe\/Zurich",
        "htaccess.RewriteBase": "\/",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "\/var\/www\/nextcloud\/core\/skeleton"
    }
}
```
</details>

**Are you using external storage, if yes which one:** SMB external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
{
    "apps": {
        "user_ldap": {
            "background_sync_prefix": "s01",
            "installed_version": "1.9.0",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_user_display_name_2": "",
            "s01ldap_group_display_name": "cn",
            "s01ldap_tls": "0",
            "s01ldap_quota_def": "",
            "s01ldap_quota_attr": "",
            "s01ldap_email_attr": "",
            "s01ldap_cache_ttl": "600",
            "s01home_folder_naming_rule": "",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01use_memberof_to_detect_membership": "1",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_nested_groups": "0",
            "s01ldap_paging_size": "500",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_experienced_admin": "0",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_user_avatar_rule": "default",
            "s01ldap_ext_storage_home_attribute": "",
            "s01ldap_userlist_filter": "(&(|(objectclass=user))(|(|(memberof=CN=example.sg_nextcloud_test,OU=example,OU=example,OU=example,OU=example,DC=example,DC=local)(primaryGroupID=3867))))",
            "s01ldap_base_users": "DC=example,DC=local",
            "s01ldap_dn": "CN=Nextcloud LDAP,OU=example,DC=example,DC=local",
            "s01ldap_groupfilter_objectclass": "group",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_port": "389",
            "s01ldap_loginfilter_attributes": "sAMAccountName",
            "s01ldap_host": "ldap:\/\/example.example.local",
            "s01ldap_base_groups": "DC=example,DC=local",
            "s01ldap_groupfilter_groups": "example.sg_nextcloud_test",
            "s01has_memberof_filter_support": "1",
            "s01ldap_loginfilter_email": "1",
            "s01ldap_login_filter": "(&(&(|(objectclass=user))(|(|(memberof=CN=example.sg_nextcloud_test,OU=example,OU=example,OU=example,OU=example,DC=example,DC=local)(primaryGroupID=3867))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(sAMAccountName=%uid))))",
            "s01ldap_configuration_active": "1",
            "s01ldap_userfilter_groups": "example.sg_nextcloud_test",
            "s01ldap_group_filter": "(&(|(objectclass=group))(|(cn=example.sg_nextcloud_test)))",
            "s01ldap_group_member_assoc_attribute": "member",
            "s01ldap_display_name": "displayname",
            "types": "authentication",
            "enabled": "yes",
            "s01ldap_userfilter_objectclass": "user",
            "background_sync_offset": "0",
            "background_sync_interval": "43200",
            "s01ldap_user_filter_mode": "1",
            "s01ldap_base": "DC=example,DC=local",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_override_main_server": "",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_expert_uuid_user_attr": "samAccountName",
            "cleanUpJobOffset": "0",
            "s01_lastChange": "1594639533"
        }
    }
}

```
</details>

### Client configuration
**Browser:**
Firefox 78.0.2 / Sync Client Windows Version 2.6.2 stable
**Operating system:**
Windows 10 1909
#### Web server error log
<details>
<summary>Web server error log</summary>

```
No directly related Apache errors, only this:
[Mon Jul 13 13:24:01.932280 2020] [access_compat:error] [pid 1144859:tid 139691719460608] [client xxx.xxx.xxx.xxx:52032] AH01797: client denied by server configuration: /var/www/nextcloud/config
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
   "reqId":"HYuCZrMDXF1h6dlMxIou",
   "level":4,
   "time":"2020-07-13T13:35:36+02:00",
   "remoteAddr":"195.65.36.7",
   "user":"cba.testhesi",
   "app":"webdav",
   "method":"PROPFIND",
   "url":"/remote.php/dav/files/USER/FOLDER/PATH",
   "message":{
      "Exception":"RuntimeException",
      "Message":"File entry could not be inserted but could also not be selected with getId() in order to perform an update. Please try again.",
      "Code":0,
      "Trace":[
         {
            "file":"/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php",
            "line":131,
            "function":"insert",
            "class":"OC\\Files\\Cache\\Cache",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php",
            "line":294,
            "function":"insert",
            "class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php",
            "line":224,
            "function":"addToCache",
            "class":"OC\\Files\\Cache\\Scanner",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php",
            "line":423,
            "function":"scanFile",
            "class":"OC\\Files\\Cache\\Scanner",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php",
            "line":388,
            "function":"handleChildren",
            "class":"OC\\Files\\Cache\\Scanner",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php",
            "line":340,
            "function":"scanChildren",
            "class":"OC\\Files\\Cache\\Scanner",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Files/View.php",
            "line":1339,
            "function":"scan",
            "class":"OC\\Files\\Cache\\Scanner",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/lib/private/Files/View.php",
            "line":1383,
            "function":"getCacheEntry",
            "class":"OC\\Files\\View",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
            "line":221,
            "function":"getFileInfo",
            "class":"OC\\Files\\View",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php",
            "line":80,
            "function":"getChild",
            "class":"OCA\\DAV\\Connector\\Sabre\\Directory",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":976,
            "function":"getNodeForPath",
            "class":"Sabre\\DAV\\Tree",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":1678,
            "function":"getPropertiesIteratorForPath",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":1661,
            "function":"writeMultiStatus",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
            "line":363,
            "function":"generateMultiStatus",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
            "line":89,
            "function":"httpPropFind",
            "class":"Sabre\\DAV\\CorePlugin",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":474,
            "function":"emit",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":251,
            "function":"invokeMethod",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
            "line":319,
            "function":"start",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/dav/lib/Server.php",
            "line":320,
            "function":"exec",
            "class":"Sabre\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
            "line":35,
            "function":"exec",
            "class":"OCA\\DAV\\Server",
            "type":"->"
         },
         {
            "file":"/var/www/nextcloud/remote.php",
            "line":167,
            "args":[
               "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
            ],
            "function":"require_once"
         }
      ],
      "File":"/var/www/nextcloud/lib/private/Files/Cache/Cache.php",
      "Line":324,
      "CustomMessage":"--"
   },
   "userAgent":"Mozilla/5.0 (Windows) mirall/2.6.2stable-Win64 (build 20191224) (Nextcloud)",
   "version":"19.0.0.12",
   "id":"5f0c47095f5de"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:


scheme | https
-- | --
host | nc.example.com
filename | /ocs/v2.php/apps/text/workspace
 
path | FOLDER/PATH
 
Adresse | xxx.xxx.xxx.xxx:443


```
</details>

**Comment by Silv4n** [comment] 2020-07-26 09:07
bump

**Comment by yewkay** [comment] 2020-10-13 04:10
I am seeing this when I run occ file:scan --all , on 1 of the user account.

**Comment by semisenex** [comment] 2021-04-21 23:52
I had this issue, too.
Nextcloud Docker (tag 21.0.1-fpm).
ActiveDirectory and some SMB Storage.
Only one SMB Share could not be opened, same behaviour as @Silv4n described.
Error Log: "RuntimeException: File entry could not be inserted but could also not be selected with getId() in order to perform an update"
I set the nextcloud [log level to 0](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html).
Futher Log entry; "OC\Files\Cache\Cache->insert("FOLDER/SUBFOLDER", { mimetype: ... "})"
I checked the "FOLDER" folder on the Windows file server.
The folder "SUBFOLDER" was available twice (two folders had exactly the same name).
After I copied one of the SUBFOLDER to another location I was able to access the external storage in Nextcloud.
Maybe there is an issue adding two equal named folders (in the same directory) to cache?

**Comment by szaimen** [comment] 2021-07-02 15:20
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by acsfer** [comment] 2021-10-17 09:53
This can be produced in 22.2.0.0.

```
{
  "reqId": "QzNtFz3rxMqRYwmuqVKn",
  "level": 3,
  "time": "2021-10-17T11:46:47+02:00",
  "app": "no app in context",
  "method": "PUT",
  "url": "/remote.php/dav/files/cloudeezy/TestSync2/20210726_Commande_N%C2%B03517048.pdf",
  "message": "File entry could not be inserted but could also not be selected with getId() in order to perform an update. Please try again.",
  "userAgent": "Mozilla/5.0 (Windows) mirall/3.3.5stable-Win64 (build 20210930) (Nextcloud, windows-10.0.19043 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
  "version": "22.2.0.0",
  "exception": {
    "Exception": "RuntimeException",
    "Message": "File entry could not be inserted but could also not be selected with getId() in order to perform an update. Please try again.",
    "Code": 0,
    "Trace": [
      {
        "file": "/lib/private/Files/Cache/Scanner.php",
        "line": 294,
        "function": "insert",
        "class": "OC\\Files\\Cache\\Cache",
        "type": "->",
        "args": [
          "files/TestSync2/20210726_Commande_N°3517048.pdf",
          {
            "0": "And 5 more entries, set log level to debug to see all entries",
            "mimetype": "application/pdf",
            "mtime": 1627292947,
            "size": 207082,
            "etag": "bc121475fb0b06f32e7b6fcaea88f0ce",
            "storage_mtime": 1627292947
          }
        ]
      },
      {
        "file": "/lib/private/Files/Cache/Scanner.php",
        "line": 224,
        "function": "addToCache",
        "class": "OC\\Files\\Cache\\Scanner",
        "type": "->",
        "args": [
          "files/TestSync2/20210726_Commande_N°3517048.pdf",
          {
            "0": "And 4 more entries, set log level to debug to see all entries",
            "mimetype": "application/pdf",
            "mtime": 1627292947,
            "size": 207082,
            "etag": "bc121475fb0b06f32e7b6fcaea88f0ce",
            "storage_mtime": 1627292947
          },
          -1
        ]
      },
      {
        "file": "/lib/private/Files/Cache/Scanner.php",
        "line": 338,
        "function": "scanFile",
        "class": "OC\\Files\\Cache\\Scanner",
        "type": "->",
        "args": [
          "files/TestSync2/20210726_Commande_N°3517048.pdf",
          3,
          19981,
          false,
          true
        ]
      },
      {
        "file": "/lib/private/Files/View.php",
        "line": 1349,
        "function": "scan",
        "class": "OC\\Files\\Cache\\Scanner",
        "type": "->",
        "args": [
          "files/TestSync2/20210726_Commande_N°3517048.pdf",
          false
        ]
      },
      {
        "file": "/lib/private/Files/View.php",
        "line": 1393,
        "function": "getCacheEntry",
        "class": "OC\\Files\\View",
        "type": "->",
        "args": [
          {
            "cache": null,
            "scanner": {
              "__class__": "OC\\Files\\Cache\\Scanner"
            },
            "watcher": null,
            "propagator": null,
            "updater": {
              "__class__": "OC\\Files\\Cache\\Updater"
            },
            "__class__": "OCA\\Files_Trashbin\\Storage"
          },
          "files/TestSync2/20210726_Commande_N°3517048.pdf",
          "/TestSync2/20210726_Commande_N°3517048.pdf"
        ]
      },
      {
        "file": "/lib/private/Files/View.php",
        "line": 1696,
        "function": "getFileInfo",
        "class": "OC\\Files\\View",
        "type": "->",
        "args": [
          "/cloudeezy/files/TestSync2/20210726_Commande_N°3517048.pdf"
        ]
      },
      {
        "file": "/apps/activity/lib/FilesHooks.php",
        "line": 668,
        "function": "getOwner",
        "class": "OC\\Files\\View",
        "type": "->",
        "args": [
          "/TestSync2/20210726_Commande_N°3517048.pdf"
        ]
      },
      {
        "file": "/apps/activity/lib/FilesHooks.php",
        "line": 224,
        "function": "getSourcePathAndOwner",
        "class": "OCA\\Activity\\FilesHooks",
        "type": "->",
        "args": [
          "/TestSync2/20210726_Commande_N°3517048.pdf"
        ]
      },
      {
        "file": "/apps/activity/lib/FilesHooks.php",
        "line": 160,
        "function": "addNotificationsForFileAction",
        "class": "OCA\\Activity\\FilesHooks",
        "type": "->",
        "args": [
          "/TestSync2/20210726_Commande_N°3517048.pdf",
          "file_created",
          "created_self",
          "created_by"
        ]
      },
      {
        "file": "/apps/activity/lib/FilesHooksStatic.php",
        "line": 47,
        "function": "fileCreate",
        "class": "OCA\\Activity\\FilesHooks",
        "type": "->",
        "args": [
          "/TestSync2/20210726_Commande_N°3517048.pdf"
        ]
      },
      {
        "file": "/lib/private/legacy/OC_Hook.php",
        "line": 106,
        "function": "fileCreate",
        "class": "OCA\\Activity\\FilesHooksStatic",
        "type": "::",
        "args": [
          {
            "path": "/TestSync2/20210726_Commande_N°3517048.pdf"
          }
        ]
      },
      {
        "file": "/apps/dav/lib/Connector/Sabre/File.php",
        "line": 406,
        "function": "emit",
        "class": "OC_Hook",
        "type": "::",
        "args": [
          "OC_Filesystem",
          "post_create",
          {
            "path": "/TestSync2/20210726_Commande_N°3517048.pdf"
          }
        ]
      },
      {
        "file": "/apps/dav/lib/Connector/Sabre/File.php",
        "line": 339,
        "function": "emitPostHooks",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          false
        ]
      },
      {
        "file": "/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 155,
        "function": "put",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1098,
        "function": "createFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->",
        "args": [
          "20210726_Commande_N°3517048.pdf",
          null
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 504,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "files/cloudeezy/TestSync2/20210726_Commande_N°3517048.pdf",
          null,
          null
        ]
      },
      {
        "file": "/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 472,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "method:PUT",
          [
            {
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/apps/dav/lib/Server.php",
        "line": 333,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/remote.php",
        "line": 166,
        "args": [
          "/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/lib/private/Files/Cache/Cache.php",
    "Line": 340,
    "CustomMessage": "--"
  },
  "id": "616bf166757c8"
}
```

**Comment by slater0013** [comment] 2021-11-12 14:11
Same issue here when uploading large files via the web Interface.

NC 21.0.5

**Comment by szaimen** [comment] 2023-01-23 10:04
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by slater0013** [comment] 2023-01-23 14:02
This problem stopped when we switched back from SQL Load balancing (MaxScale+Galera) to "monolithic" database.

We had this issue when INSERT SQL Statement was executed on "node-1" and SELECT statement, looking for the freshly inserted line, was executed shortly after on "node-2", returning 0 results since the Galera replication is not 100% synchronous.

Would be great if Nextcloud could provide more precise guidelines about scaling a multinode replicated Database ! Even the documentations in customer portal are not very helpfull.

GS.

**Comment by szaimen** [comment] 2023-01-23 14:08
> Would be great if Nextcloud could provide more precise guidelines about scaling a multinode replicated Database ! Even the documentations in customer portal are not very helpfull.

Please open a ticket about this on support.nextcloud.com. Thanks!

**Closed by szaimen** 2023-01-23 14:08 UTC
Labels: bug, needs info, 0. Needs triage
