### ISSUE TITLE
Disable external_user app when upgrading from 12 to 13

### ISSUE THREAD

**Issue by FrankyB** [nextcloud/server#7201] opened 2017-11-17 07:22 UTC
### Steps to reproduce
1. Have nextcloud 12.0.3 with postgresql on linux / apache installed
2. Have external users app activated (is it by default?)
3. Upgrade to nextcloud13beta1

### Expected behaviour
Setup should run through

### Actual behaviour
Upgrade won't finish as it complains about files of external user app not correctly replaced. After disabling the external_user app via cli the setup ran through.

### Server configuration

**Operating system**:
Linux

**Web server:**
Apache 

**Database:**
postgresql

**PHP version:**
php7

**Nextcloud version:** (see Nextcloud admin page)
nextcloud 12.0.3 to nextcloud 13beta1

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from 12.0.3

**Where did you install Nextcloud from:**
wget from https://download.nextcloud.com/server/prereleases/nextcloud-13.0.0beta1.zip then filesystem

**Signing status:**
<details>
<summary>Signing status</summary>
Does not apply
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap but not configured

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

</details>

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 7 / Arch Linxu 

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
</details>

#### Browser log
<details>
<summary>Browser log</summary>

</details>

**Comment by LukasReschke** [comment] 2017-11-23 09:58
Duplicate of https://github.com/nextcloud/server/issues/7237, will be fixed with the next RC.

**Closed by LukasReschke** 2017-11-23 09:58 UTC
