### ISSUE TITLE
[Bug]: Nexctloud 28.0.3 share by mail (folder or file) with a forced password: password is not auto-generated

### ISSUE THREAD

**Issue by dea-75** [nextcloud/server#43935] opened 2024-03-01 11:36 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

(use a password to share is forced)

- Create a folder
- Share by email
- Save share: error, password is not set

Password autocomplete is missing

Note: share by link works correctly in password autocomplete

### Steps to reproduce

1.Create a folder
2. Share by email
3. Save share: error, password is not set

### Expected behavior

Password autocomplete (randomly)

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by LM-vb** [comment] 2024-03-04 09:13
duplicate of #43919

**Comment by Fenn-CS** [comment] 2024-03-15 09:42
@mgallien it does :)

**Closed by Fenn-CS** 2024-03-15 09:42 UTC
Labels: bug, 0. Needs triage, 28-feedback

**Comment by dea-75** [comment] 2024-03-22 09:01
> @mgallien it does :)

I can confirm, in 28.0.4.rc1 the problem persist.

**Comment by marnoe** [comment] 2024-03-25 09:17
i can confirm the issue in 28.0.3
