### ISSUE TITLE
Cannot mass upload folders with files (upload share)

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/server#6339] opened 2017-09-02 10:06 UTC
### Steps to reproduce
1. Create a new folder
2. Share with someone public and allow upload of files
3. Open the shared link
4. Drag and drop 3 files
5. After 10 minutes waiting you still see the loading cicle (a check on the server shows the files on the share)

![2017-09-02_120138](https://user-images.githubusercontent.com/4450722/29994729-9f8aab8a-8fd6-11e7-9ea2-b9126103bd19.png)

6. Now select a folder with subfolders and files and drag and drop
7. Drag and drop does not work at all.

### Expected behaviour
Drag and drop of folders with files does not work. Uploading a few files in a row shows loading for ever (one file complete)

### Actual behaviour
Mass uploads need to work (also with folders)

### Server configuration

**Operating system**: Debian 9.1

**Web server:** Apache 2.4

**Database:** MaraiDB

**PHP version:** 7.0.20 (x64)

**Nextcloud version:** (see Nextcloud admin page) 12.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 12.1

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** IE 11

**Operating system:** Windows 10

**Comment by MorrisJobke** [comment] 2017-09-02 14:25
Duplicate of #6060

Fixed in #6182

Will be released in 12.0.3.

**Closed by MorrisJobke** 2017-09-02 14:25 UTC

**Comment by yamlfd** [comment] 2017-09-02 15:48
Notes are only about multiple files, but about drag and drop a folder with files. Has this really fixed?

**Comment by MorrisJobke** [comment] 2017-09-03 11:47
> Notes are only about multiple files, but NOT about drag and drop a folder with files. Has this really fixed?

I guess this is fixed as a side effect. Could you test this with the daily tar ball? https://download.nextcloud.com/server/daily/latest-stable12.zip

Thanks
