### ISSUE TITLE
Sharing link error: can't set expiration date more than...

### ISSUE THREAD

**Issue by SkyWheel** [nextcloud/server#16204] opened 2019-07-03 00:52 UTC
### Steps to reproduce
1. Shared link's expiration date and password protection are enforced
2. Trying to share a folder or file via link.
3. Enter password

### Expected behaviour
Shred link is created

### Actual behaviour
Error appears "Can't set expiration date more than x days in the future"

Workaround is to set up different expiration date, remove enforcement. Repeat this number of times, then return everything back to default settings (expiration enforced after x days), and the issue is gone.

### Server configuration

**Operating system:** Ubuntu Server 18.04

**Web server:** Apache 2.4

**Database:** MySQL 5.7

**PHP version:** PHP 7.2

**Nextcloud version:** Latest stable Nextcloud-snap 15.0.8snap3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** Snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
- accessibility: 1.1.0
- activity: 2.8.2
- admin_audit: 1.5.0
- announcementcenter: 3.4.1
- bruteforcesettings: 1.3.0
- calendar: 1.6.5
- checksum: 0.4.3
- cloud_federation_api: 0.1.0
- comments: 1.5.0
- contacts: 3.1.3
- dav: 1.8.2
- encryption: 2.3.0
- federatedfilesharing: 1.5.0
- files: 1.10.0
- files_accesscontrol: 1.5.0
- files_automatedtagging: 1.5.0
- files_pdfviewer: 1.4.0
- files_retention: 1.4.2
- files_rightclick: 0.13.0
- files_sharing: 1.7.0
- files_texteditor: 2.7.
- files_trashbin: 1.5.0
- files_versions: 1.8.0
- files_videoplayer: 1.4.0
- firstrunwizard: 2.4.0
- gallery: 18.2.0
- logreader: 2.0.0
- lookup_server_connector: 1.3.0
- nextcloud_announcenents: 1.4.0
- notes: 3.0.0
- notifications: 2.3.0
- oauth2: 1.3.0
- password_policy: 1.5.0
- provisioning_api: 1.5.0
- qownnotesapi: 19.4.0
- serverinfo: 1.5.0
- spreed: 5.0.4
- support: 1.0.0
- systemtags: 1.5.0
- tasks: 0.11.0
- theming: 1.6.0
- twofactor_admin: 0.2.1
- twofactor_backupcodes: 1.4.1
- twofactor_totp: 2.1.2
- twofactor_u2f: 2.1.3
- workf lovengine: 1.5.0

Disabled:

- federation
- files_external
- sharebymail
- survey_client
- user_ldap
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox a few latest versions, Chromium a few latest versions.

**Operating system:** Linux Mint 19, Windows 10

**Comment by SkyWheel** [comment] 2019-07-03 00:54
![image](https://user-images.githubusercontent.com/10903432/60555574-debfd780-9d80-11e9-889f-28c37c1627ec.png)

**Comment by tbuytaer** [comment] 2019-07-10 22:21
I also get this (on 15.0.8) without password protection.

Steps to reproduce:

1. Shared link's expiration date is set by default and password expiration is enforced

2. Refresh the page

3. Try to share a folder or file via link.

4. I get an error. In the Console I see the error message "Can't set expiration date more than x days in the future"

If I unset "enforce expiration date" it works as expected.
So this seems to be linked to the option to "**enforce expiration date**".

**Comment by kesselb** [comment] 2020-01-30 17:24
@skjnldsv fixed with the new sidebar?

**Comment by skjnldsv** [comment] 2020-01-31 07:11
Most likely yes :)

**Closed by skjnldsv** 2020-01-31 07:11 UTC
Labels: 0. Needs triage, bug
