### ISSUE TITLE
[Bug]: Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".

### ISSUE THREAD

**Issue by AI-ien** [nextcloud/server#42792] opened 2024-01-15 10:50 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Got this error when upgrading to 28.0.1

`Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".`

**Detailed logs**
```
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Exception: Database error when running migration 28000Date20230906104802 for app core Index name "rd_wopi_token_idx" for table "oc_richdocuments_wopi" collides with the constraint on table "oc_officeonline_wopi".
```

### Steps to reproduce

Run server web upgrade from 27 to 28

### Expected behavior

Upgrade completed

### Installation method

None

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2024-01-15 10:51
Duplicate of https://github.com/nextcloud/server/issues/41253

**Closed by solracsf** 2024-01-15 10:51 UTC
Labels: bug, 0. Needs triage
