### ISSUE TITLE
Incorrect integer value: '' for column 'password_invalid' while migrating from pg to mysql

### ISSUE THREAD

**Issue by avestnik** [nextcloud/server#14920] opened 2019-03-31 21:13 UTC
### Steps to reproduce
1. create an empty mysql 8.0.15 database
2. run occ db:convert-type

### Expected behaviour
converted mysql database

### Actual behaviour
conversion fails on oc_authtoken 
An exception occurred while executing 'INSERT INTO `oc_authtoken` (`id`, `uid`, `login_name`, `password`, `name`, `token`, `type`, `remember`, `last_activity`, `last_check`, `scope`, `expires`, `private_key`, `public_key`, `version`, `password_invalid`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [33, "...", "...", "...", 2, false]:

  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'password_invalid' at row 1

I guess it is trying to insert false value into mysql tinyint column, false should be translated to 0b0, true to 0b1 for the statement to be correct 

### Server configuration

**Operating system**: centos7

**Web server:** apache

**Database:** postgres

**PHP version:** 7.2.10

**Nextcloud version:** (see Nextcloud admin page) 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 13

**Where did you install Nextcloud from:** nextcloud web site

**Signing status:** No errors have been found.

**List of activated apps:**

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** openldap

**Comment by JHirte** [comment] 2019-06-22 17:06
I have the same problem with migrating from postgres to mariadb. It seems the migration tool fails on boolean fields. I've seen this with oc_authtoken, oc_calendarobjects_props and oc_share. For oc_authtoken and oc_calendarobjects_props I simply dropped the entries. But for oc_share this isn't an option. 

Happened with nc-15.07 and nc-16.0.1.

**Comment by kesselb** [comment] 2019-06-22 17:42
@JHirte mind to share the broken queries? The password_invalid column looks fine for me on mysql.

**Comment by JHirte** [comment] 2019-06-22 19:45
> @JHirte mind to share the broken queries? The password_invalid column looks fine for me on mysql.

As I dropped the problematic content from oc_authtkoken, I don't have anything in password_invalid. At moment I have two entries in oc_authtkoken, and password_invalid is empty for both of them. I'm just running the migration script again. Should fail in oc_share. I can provide a cleaned up query of this then.

**Comment by JHirte** [comment] 2019-06-23 07:49
broken query from oc_authtkoken (some data stripped out):

An exception occurred while executing 'INSERT INTO `oc_authtoken` (`id`, `uid`, `login_name`, `password`, `name`, `token`, `type`, `remember`, `last_activity`, `last_check`, `scope`, `expires`, `private_key`, `public_key`, `version`, `password_invalid`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [726, "johannes.hirte", "johannes.hirte", "STRIPPED", "Mozilla\/5.0 (Android) ownCloud-android\/3.6.2", "STRIPPED", 0, 0, 1561227173, 1561227173, null, null, "", "-----BEGIN PUBLIC KEY----- STRIPPED -----END PUBLIC KEY-----\n", 2, false]:                                              
                                                                                                                                                                                                                      
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `khaoscloud`.`oc_authtoken`.`password_invalid` at row 1

So the last value is a boolean, and this seems to be handled wrong in the php code.

**Comment by digrouz** [comment] 2019-09-07 12:21
I have the same issue.

Any idea how to fix ? Or a workaround ?

**Comment by kesselb** [comment] 2019-09-07 20:45
Do you have a stack trace?

cc @nickvergessen @rullzer I can guess the issue from the migration code. `password_invalid` is a boolean column on pqsql and a tinyint on mysql. 

https://github.com/nextcloud/server/blob/bb352fb667e87ea0829f1da5f9e85c34bdefe9fa/core/Command/Db/ConvertType.php#L352-L354

Data from pqsql is copied to mysql without conversion because the column type is not set. There is a method `getColumnType` but no way to do a special conversion from pqsql to mysql for int columns.

**Comment by digrouz** [comment] 2019-09-08 04:38
here is the stripped output:

`# php occ  db:convert-type --all-apps mysql nextcloud-user mysql-host nextcloud-db --clear-schema
What is the database password?
Clearing schema in new database
Creating schema in new database
The following tables will not be converted:
oc_users_external
oc_privatedata
Continue with the conversion (y/n)? [n] y
oc_accounts
 2/2 [============================] 100%oc_activity
chunked query, 18 chunks
 17662/17662 [============================] 100%oc_activity_mq
    0 [>---------------------------]oc_addressbookchanges
 13/13 [============================] 100%oc_addressbooks
 2/2 [============================] 100%oc_appconfig
 182/182 [============================] 100%oc_audioplayer_albums
    0 [>---------------------------]oc_audioplayer_artists
    0 [>---------------------------]oc_audioplayer_genre
    0 [>---------------------------]oc_audioplayer_playlist_tracks
    0 [>---------------------------]oc_audioplayer_playlists
    0 [>---------------------------]oc_audioplayer_stats
    0 [>---------------------------]oc_audioplayer_streams
    0 [>---------------------------]oc_audioplayer_tracks
    0 [>---------------------------]oc_authtoken
 1/7 [====>-----------------------]  14%
In AbstractMySQLDriver.php line 125:

  An exception occurred while executing 'INSERT INTO `oc_authtoken` (`id`, `uid`, `login_name`, `password`, `name`, `
  token`, `type`, `remember`, `last_activity`, `last_check`, `scope`, `expires`, `private_key`, `public_key`, `versio
  n`, `password_invalid`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [3072, "jeanjacques", "jeanjacques", "<STRIPPED>", "Oneplus GM1913", "<STRIPPED>", 1, 0, 1567847336, 1567847336, null, null, "<STRIPPED>", "-----BEGIN
   PUBLIC KEY-----\n<STRIPPED>\n-----END PUBLIC KEY-----\n", 2,
  false]:

  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'password_invalid' at row 1


In PDOStatement.php line 143:

  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'password_invalid' at row 1


In PDOStatement.php line 141:

  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'password_invalid' at row 1


db:convert-type [--port PORT] [--password PASSWORD] [--clear-schema] [--all-apps] [--chunk-size CHUNK-SIZE] [--] <type> <username> <hostname> <database>
`

**Comment by bstegmaier75** [comment] 2019-09-08 16:07
Just to confirm, I have exactly the same issue converting postgres DB to MariaDB.

**Comment by milkomeda** [comment] 2019-09-28 15:48
Same problem here.

**Comment by muhviehstah** [comment] 2019-10-18 20:51
same here , oc_share and oc_authtoken and some tables from apps (richtext , talk etc) with the same issue

a dirty workaround after lot try and error :

i have exported oc_share and oc_authtoken and converted it to mysql manualy (just took the inserts and let convert-type create the empty table)

i have dropped the app tables cause they are not important for me.

insert oc_authtoken and oc_share after the convert was successful . shares and auths working fine 

http://www.lightbox.ca/pg2mysql.php  was helpful

**Comment by LostInWeb** [comment] 2019-11-16 23:58
I have the same problem. And I compared the table "oc_authtoken" of the databases postgresql and mysql.
The problem is the column "_password_invalid_" in "_oc_authtoken_" of postgresql which is the type "**BOOLEAN**".
And the column "_password_invalid_" in "_oc_authtoken_" of mysql which is the type "**TINYINT**".

I checked the migration-script if I can manipulate the type during the migration step but my skill is too low for finding the right segment of the right file.

**Comment by kesselb** [comment] 2020-01-09 13:18
Fixed by https://github.com/nextcloud/server/pull/18027

Thanks @str0g :tada:

**Closed by kesselb** 2020-01-09 13:18 UTC
Labels: 0. Needs triage, bug

**Comment by digrouz** [comment] 2020-01-09 13:22
worked for me, thanks!
