### ISSUE TITLE
error google chrome menus aplications ans users not working

### ISSUE THREAD

**Issue by tpafe** [nextcloud/server#16359] opened 2019-07-11 06:13 UTC
<!--in version 16.0.3 with the browser google chrome the menus applications and users do not work, they redirect to the main domain and they do not open, in the browser edge if it works correctly.

**Comment by tpafe** [comment] 2019-07-11 06:13
in version 16.0.3 with the browser google chrome the menus applications and users do not work, they redirect to the main domain and they do not open, in the browser edge if it works correctly.

**Comment by pdelange** [comment] 2019-07-11 07:22
Same for me. Chrome Version 75.0.3770.100 (Official Build) (64-bit), NextCloud 16.03

**Comment by grogowar** [comment] 2019-07-11 14:46
Same for me. After update to 15.0.10 apps and users pages becomes blank.

**Comment by kesselb** [comment] 2019-07-11 14:48
Duplicate of #16252

**Closed by kesselb** 2019-07-11 14:48 UTC
Labels: 0. Needs triage, bug
