### ISSUE TITLE
OC.dialogs doesn't trigger callback if dialog is closed through "X" or ESC

### ISSUE THREAD

**Issue by fancycode** [nextcloud/server#2578] opened 2016-12-09 07:55 UTC
### Steps to reproduce
1. Open a dialog using `OC.dialogs.confirm` and pass a callback function.
2. Close the dialog by clicking the `X` in the top-right corner or press ESC.

### Expected behaviour
The callback should be executed with `false` as argument (because the user didn't confirm the dialog). This would be necessary to perform some cleanup code.

### Actual behaviour
The callback is not executed.

**Comment by nickvergessen** [comment] 2016-12-09 08:47
Jup, noticed that as well with the password-confirm dialog.

**Comment by nickvergessen** [comment] 2016-12-09 08:52
@nextcloud/javascript

**Comment by nickvergessen** [comment] 2016-12-09 08:55
On the other hand this would e.g. cancel a federated share if you accidently press ESC, so maybe we should use a different return code for that?

**Comment by MorrisJobke** [comment] 2016-12-09 09:19
is this fixed with https://github.com/nextcloud/files_videoplayer/pull/13 for you?

Is this maybe a duplicate of #2256

**Comment by MorrisJobke** [comment] 2016-12-09 09:20
Because the files_videoplayer crashed the JS while hitting ESC causing no callback to trigger anymore ;)

**Comment by MorrisJobke** [comment] 2016-12-09 09:21
For me for example the "choose an avatar file from Nextcloud" popup works fine.

**Comment by fancycode** [comment] 2016-12-09 09:22
I don't see how nextcloud/files_videoplayer#13 changes anything in "OC.dialogs". The problem is not that `X` is not working (it is), but that the callback is not triggered in that case.

**Comment by MorrisJobke** [comment] 2016-12-09 09:30
> I don't see how nextcloud/files_videoplayer#13 changes anything in "OC.dialogs". The problem is not that X is not working (it is), but that the callback is not triggered in that case.

It doesn't, but it registered to a global event and crashed. Then all following callbacks are also not executed ;) Do you see something in the JS console when hitting the "X"?

**Comment by nickvergessen** [comment] 2016-12-09 09:31
@MorrisJobke just look at the code, there is no function registered to the "close" button.

**Comment by MorrisJobke** [comment] 2016-12-09 09:48
Fix is in #2582

**Closed** 2016-12-09 12:44 UTC
Labels: bug
