### ISSUE TITLE
nextcloud admin  logging is my nextcloud was hacked:Error internet_connection_check GuzzleHttp\Exception\RequestException: cURL error 51: SSL: no alternative certificate subject name matches target host name '165.227.162.232' Who is this ip:165.227.162.232

### ISSUE THREAD

**Issue by gurussia** [nextcloud/server#8352] opened 2018-02-14 09:28 UTC
Strange, what this mean nextcloud.com port 80, nextcloud developers what data nextcloud send you when it connect to nextcloud server, if i remember nextcloud is for private cloud and no data is send to nextcloud.com

> Error	internet_connection_check	GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to www.nextcloud.com port 80: No route to host
> 
>     /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
>     /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
>     /var/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
>     /var/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
>     /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
>     /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
>     /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
>     /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
>     /var/www/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('http //www.next...', Array)
>     /var/www/nextcloud/settings/Controller/CheckSetupController.php - line 129: OC\Http\Client\Client->get('http //www.next...')
>     /var/www/nextcloud/settings/Controller/CheckSetupController.php - line 112: OC\Settings\Controller\CheckSetupController->isSiteReachable('www.nextcloud.c...')
>     /var/www/nextcloud/settings/Controller/CheckSetupController.php - line 426: OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()
>     [internal function] OC\Settings\Controller\CheckSetupController->check()
>     /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
>     /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\CheckSetupController), 'check')
>     /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\CheckSetupController), 'check')
>     /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
>     [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
>     /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
>     /var/www/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/settings/ajax/...')
>     /var/www/nextcloud/index.php - line 37: OC handleRequest()
>     {main}

**Comment by gurussia** [comment] 2018-02-14 09:40
Error	internet_connection_check	GuzzleHttp\Exception\RequestException: cURL error 51: SSL: no alternative certificate subject name matches target host name '165.227.162.232'

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
    /var/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
    /var/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
    /var/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
    /var/www/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('http //www.next...', Array)
    /var/www/nextcloud/settings/Controller/CheckSetupController.php - line 129: OC\Http\Client\Client->get('http //www.next...')
    /var/www/nextcloud/settings/Controller/CheckSetupController.php - line 112: OC\Settings\Controller\CheckSetupController->isSiteReachable('www.nextcloud.c...')
    /var/www/nextcloud/settings/Controller/CheckSetupController.php - line 426: OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()
    [internal function] OC\Settings\Controller\CheckSetupController->check()
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\CheckSetupController), 'check')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\CheckSetupController), 'check')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/settings/ajax/...')
    /var/www/nextcloud/index.php - line 37: OC handleRequest()
    {main}

	a few seconds ago
Error	PHP

**Comment by marmeladema** [comment] 2018-02-14 09:43
From the admin logs panel you can see the app name is internet_connection. It must to check whether or not the server has internet connectivity. I also wonder what kind of request is made.
And how the whole thing is configurable ?

**Comment by gurussia** [comment] 2018-02-14 09:53
nextcloud.com is normal, but this ip: 165.227.162.232, who is this ip, is this ip of nextcloud and if, then why it don't write nextcloud, does cloud has been hacked.  Yes im in alarm, becouse in production server i disable anonymous send data log to nextcloud and on developer 2 server it has send anonymous data only to nextcloud. So what data is send when it make connection to nextcloud, when explicity it has been SAID: it don't accept " don't send anonymous log and is dissabled " and why there is internet connetion app, i din't install it, what i read is that nextcloud is your, this mean it only install what you want

**Comment by d0tfile** [comment] 2018-02-14 10:04
@gurussia 
`host 165.227.162.232`: `232.162.227.165.in-addr.arpa domain name pointer nextcloud.com.`
and
`dig +noall +answer nextcloud.com`: `nextcloud.com.		3423	IN	A	165.227.162.232`

**Comment by gurussia** [comment] 2018-02-14 10:10
i get this:
This is a public HTTP proxy located in United States(New York) 
  | 165.227.161.203                                  :                                     80

Provider | DigitalOcean, LLC

if

**Comment by d0tfile** [comment] 2018-02-14 10:12
@gurussia how do you get this? Server is hosted in DE.
`geoiplookup 165.227.161.203`: `GeoIP Country Edition: DE, Germany`

**Comment by gurussia** [comment] 2018-02-14 10:15
geoiplookup 165.227.161.203
GeoIP Country Edition: US, United States

**Comment by gurussia** [comment] 2018-02-14 10:19
d0tfile i call friend and ask him to comment me if he know something for the ip after some seconds he comment me this what it write: 165.227.161.203  public HTTP proxy located in United States(New York)
after that he comment me: geoiplookup 165.227.161.203 is in united state of america so someone need to be transparency part of nextcloud.com in the moment im gonna shut down nextcloud server, becouse or someone could breach nextcloud server or nextcloud.com is not transparency of peoples humankind rights.

**Comment by d0tfile** [comment] 2018-02-14 10:28
Maxmind's geoip and `geoiplookup` from Arch Linux say it hosted in DE. Some sites from google say US. Interesting. Maybe outdated bases.

**Comment by gurussia** [comment] 2018-02-14 10:39
strange:

i enable in /etc/php/7.1/cli/php.ini:
in the beggining:

> 
> ;extension="apcu.so"
> ;extension="redis.so"

in the last of the message:

> ; Nextcloud Opcache settings
> opcache.enable=1
> opcache.enable_cli=1
> opcache.interned_strings_buffer=8
> opcache.max_accelerated_files=10000
> opcache.memory_consumption=128
> opcache.save_comments=1
> opcache.revalidate_freq=1

And now nextcloud private server is working very slow maybe more than 5 minute to load every web page, and again when i disable the upper in nextcloud it continue slow, what is happening.

**Comment by MorrisJobke** [comment] 2018-02-14 21:36
It is not hacked - this was due to a server migration to a temporarily digital ocean instance - the IP was correct but the Let's Encrypt cert was only correct after some minutes and thus created those valid error messages. We were not hacked, but only had a kernel issue in one of our servers.

**Comment by MorrisJobke** [comment] 2018-02-14 21:37
So this is actual the correct behaviour and should be logged - or am I wrong @rullzer @nickvergessen - just to properly analyse why stuff didn't work. I would keep it like that as it was an interruption.

I would focus on the ticket #8351 and close this one here as "works as it should".

**Comment by gurussia** [comment] 2018-02-14 23:59
comment us why nextcloud.com wants our data or why our private clouds are connecting with nextcloud.com when in production it has disabled send anonymous data. What kind of data is send to nextcloud when anonumous data is disabled, becouse in this case it send something.

**Comment by MorrisJobke** [comment] 2018-02-15 07:42
We don’t collect anything here - this is just a request to a website (in this case ours) to check if the internet connection is working at all to determine if a given feature is usable. We don’t collect anything there.

**Comment by Escubaer** [comment] 2018-02-15 08:11
You do collect IP addresses, automatically - when you have every server connect to nextcloud.com ... this can be fine and make sense, but you should not say that you don't collect ...

**Comment by marmeladema** [comment] 2018-02-15 08:19
Is there a way to override this feature by specifying in the configuration that the server *has* internet connectivity ? I know some requests will still be made, for update status for example but it still an improvement.

**Comment by MorrisJobke** [comment] 2018-02-15 08:46
> You do collect IP addresses, automatically - when you have every server connect to nextcloud.com ... this can be fine and make sense, but you should not say that you don't collect ...

That's what I meant. There is nothing actively transferred that is not needed for the purpose of the transfer (like IP address, which is mandatory for the actual transfer). Sorry to be a bit unclear here.



> Is there a way to override this feature by specifying in the configuration that the server has internet connectivity ? I know some requests will still be made, for update status for example but it still an improvement.

Currently there is no option for this and it is also not planned to be added, because it is an self check that is only made if you go to the general section of the admin settings.

See https://github.com/nextcloud/server/blob/7618473a443aaa42d06391a134525d51a6912f39/settings/Controller/CheckSetupController.php#L102-L117 for the actual code.

**Comment by MorrisJobke** [comment] 2018-02-15 08:46
> Currently there is no option for this and it is also not planned to be added, because it is an self check that is only made if you go to the general section of the admin settings.

To be clear: this self check should enable the admin to properly diagnose what goes wrong.

**Comment by rullzer** [comment] 2018-02-15 08:49
As pointed out this is expected behavior. We check for this to ensure the internet connection is working. And since you already try to obtain information from our servers (for example for the updates) anyway we don't consider this an issue.

If you really don't want this then please setup your firewall or local DNS to point our domains somewhere else.

**Closed by rullzer** 2018-02-15 08:49 UTC
