### ISSUE TITLE
Can't remove users from group after update to NC 20

### ISSUE THREAD

**Issue by JanBoehme** [nextcloud/server#23435] opened 2020-10-14 11:02 UTC
### Steps to reproduce
1. got to settings/users
2. click "edit" for a user with one or more groups assigned
3. try to remove a group by unchecking the item in the group list

### Expected behaviour
The item should be unchecked and the user removed from that group.

### Actual behaviour
the check mark remains, the user is not removed from the group and an error message apears:
"An error occured during the request. Unable to proceed."

### Server configuration
I checked this on two different systems, so I included the details for both. They don't seem to make a difference, the error occurs on both of them.

**Operating system:**
Ubuntu 16.04.6 / Ubuntu 20.04.1

**Web server:**
Apache  / nginx/1.18.0

**Database:**
MariaDB 10.2.31 / MariaDB 10.5.6

**PHP version:**
PHP 7.3 / PHP 7.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 19.0.4

**Where did you install Nextcloud from:**
tarball downloaded from download.nextcloud.com, update via internal updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - deck: 1.1.1
  - documentserver_community: 0.1.8
  - end_to_end_encryption: 1.6.2
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.1.0
  - integration_gitlab: 0.0.5
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - polls: 1.5.4
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.4
  - richdocumentscode: 4.2.800
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - talk_matterbridge: 1.18.3
  - tasks: 0.13.4
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sub.domain.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "share_folder": "\/Shared",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/sub.domain.de\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no on one system, ldap/ad on the other, doesn't affect outcome

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
omitted since it happens with and without ldap
```
</details>

### Client configuration
**Browser:**
Chrome 86.0.4240.75 / Firefox 81.0.1

**Operating system:**
MacOS 10.14.6

#### Web server error log
<details>
<summary>Web server access log</summary>
when trying to uncheck the group:
```
MYIP - - [14/Oct/2020:12:54:00 +0200] "DELETE /ocs/v2.php/cloud/users/USERNAME/groups HTTP/2.0" 404 286 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
```
Error log is empty.

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"UNMKTj7rZu2RH56pF1Me","level":3,"time":"2020-10-14T10:57:35+00:00","remoteAddr":"93.242.135.24","user":"USERNAME","app":"no app in context","method":"DELETE","url":"/ocs/v2.php/cloud/users/USERNAME/groups","message":{"Exception":"Exception","Message":"Argument 2 passed to OCA\\Provisioning_API\\Controller\\UsersController::removeFromGroup() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Provisioning_API\\Controller\\UsersController::removeFromGroup() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"removeFromGroup","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/UsersController.php","Line":802},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","version":"20.0.0.9"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
/ocs/v2.php/cloud/users/USERNAME/groups:1 Failed to load resource: the server responded with a status of 404 (Not Found)

b) The network log
Name
https://cloud.avhsw.de/ocs/v2.php/cloud/users/USERNAME/groups 
Status
404
Type
xhr
Initiator
xhr.js:184

c) Server Response
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.
</message>
 </meta>
 <data/>
</ocs>


```
</details>

**Comment by kaoschris** [comment] 2020-10-14 12:03
Same here since update

**Comment by kesselb** [comment] 2020-10-14 13:18
Duplicate of https://github.com/nextcloud/server/issues/23237

**Closed by kesselb** 2020-10-14 13:18 UTC
Labels: 0. Needs triage, bug

**Comment by kesselb** [comment] 2020-10-14 13:20
Please keep the "How to use GitHub section" the next time. The idea is to keep people from posting those same here comments.

**Comment by JanBoehme** [comment] 2020-10-14 13:22
ok. sry for the duplicate report, should have been looking a little longer, obviously..

**Comment by kesselb** [comment] 2020-10-14 13:42
No problem. The original report is hard to find because the related patch is already merged.
