### ISSUE TITLE
Random Spaces Missing in Move/Copy Dialogue

### ISSUE THREAD

**Issue by 42CF11059F2F** [nextcloud/server#18768] opened 2020-01-09 09:08 UTC
### Steps to reproduce
1. Choose a file / folder.
2. Select to move / copy it.
3. Look through various folders in the  pop-up menu to locate some with missing spaces - note this is almost random in occurence, but always the same folders have the issue.

### Expected behaviour
Folder names should display correctly, as they do in the normal file viewer.

### Actual behaviour
Spaces are missing from the folder names:

![Example 1](https://user-images.githubusercontent.com/665111/72053322-b0d2c700-32be-11ea-9792-1dd5077b449b.png)
![Example 2](https://user-images.githubusercontent.com/665111/72053323-b0d2c700-32be-11ea-9ed0-01ca6a7b77a9.png)
![Example 4](https://user-images.githubusercontent.com/665111/72053324-b0d2c700-32be-11ea-8c1e-b118ff630b45.png)

This is completely random in terms of which folders exhibity the problem, but it's always the same folders. It affects around 5% of content.

I assumed it may be related to the ampersand, but I have other folders not exhibiting the behaviour:

![Example 3](https://user-images.githubusercontent.com/665111/72053366-c7791e00-32be-11ea-96c9-bb84daafa58b.png)

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2.4

**Database:** MariaDB 10

**PHP version:** PHP 7.3

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update and fresh install.

**Where did you install Nextcloud from:** Nextcloud website.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - apporder: 0.9.0
  - breezedark: 17.0.2
  - bruteforcesettings: 1.4.0
  - camerarawpreviews: 0.7.3
  - cloud_federation_api: 1.0.0
  - dav: 1.13.0
  - extract: 1.2.2
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - jsloader: 1.0.2
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocr: 4.4.30
  - onlyoffice: 4.0.0
  - password_policy: 1.7.0
  - previewgenerator: 2.2.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - uploaddetails: 0.1.2
  - video_converter: 0.1.2
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - activity
  - admin_audit
  - comments
  - deck
  - encryption
  - federation
  - files_versions
  - gallery
  - privacy
  - recommendations
  - richdocuments
  - support
  - survey_client
  - systemtags
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "jsloader"
        ]
    }
}
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome / Firefox (latest)

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
No related errors shown.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
No related errors shown.
</details>

#### Browser log
<details>
<summary>Browser log</summary>
No related errors shown.
</details>

**Comment by a1pilot** [comment] 2020-01-09 10:19
Looking in the page source I can see the filename is broken down into "first" and "last" components:
![image](https://user-images.githubusercontent.com/665111/72058794-a74e5c80-32c8-11ea-9dd7-b9265bb46978.png)

For some reason it's split randomly, but the space is included (as you can see in the above image) and gets stripped out.

If I edit the source to put another letter in there, so you have:
![image](https://user-images.githubusercontent.com/665111/72059021-12982e80-32c9-11ea-8b93-d8e55367c70f.png)

You then get the space reappearing:
![image](https://user-images.githubusercontent.com/665111/72059040-1d52c380-32c9-11ea-8913-11b4f49f51fd.png)


Another example of the split point:
![image](https://user-images.githubusercontent.com/665111/72058928-e7154400-32c8-11ea-9aa7-8784af0507b0.png)

I'm assuming this is based on a 50/50 split of the name into first and last.

It appears this split is the cause of the issue. It doesn't happen in the main file list.

**Comment by gary-kim** [comment] 2020-01-09 10:38
Fixed by #17670 for NC 18. We never backported it. Maybe we should.

**Comment by szaimen** [comment] 2021-05-28 09:50
Based on gary-kim's comment was this fixed by #17670 -> closing.

**Closed by szaimen** 2021-05-28 09:50 UTC
Labels: 0. Needs triage, bug
