### ISSUE TITLE
Duplicate email can still add new users

### ISSUE THREAD

**Issue by hongtring** [nextcloud/server#37659] opened 2023-04-10 11:02 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Duplicate email can still add new users

### Steps to reproduce

1. Sign in
2. Profile Admin > Users
3. Add new user
4. Duplicate email already on the system
5. Save

### Expected behavior

One Email can only register 1 account

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

**Comment by solracsf** [comment] 2023-04-10 13:24
Nextcloud allows one unique username, not one unique email. To accomplish that, set the username == email.

**Comment by pierreozoux** [comment] 2023-04-21 10:16
I just spent several hours to debug a cal issue due to a duplicate email. I think Nextcloud should enforce unique email, or at least this could be an option.

**Comment by joshtrichards** [comment] 2024-09-22 12:48
Duplicate of #17146

**Closed by joshtrichards** 2024-09-22 12:48 UTC
Labels: enhancement, 0. Needs triage, feature: users and groups, 25-feedback

**Comment by kortom23** [comment] 2024-09-25 17:51
Hello :) 
Is there any solution to this yet?

**Comment by pierreozoux** [comment] 2024-09-26 06:45
@kortom23 this issue is a duplicate of https://github.com/nextcloud/server/issues/17146

If you have questions, go there instead. Thanks!
