### ISSUE TITLE
Failed to login desktop/mobile app

### ISSUE THREAD

**Issue by hysci** [nextcloud/server#24067] opened 2020-11-12 07:14 UTC
* Environment: The latest nextcloud 20.01 was installed, php 7.3 was used, MariaDB worked correctly
* Using nginx to proxy https://xxx.com to http://ip:8080, settings in the nextcloud/config/config.php
  'overwrite.cli.url' => 'https://xxx.com',
  'overwriteprotocol' => 'https', 
   'trusted_domains' =>                                                               
array (                                                                              
0 => '10.10.8.4:8080',                                                          
1 => 'xxx.com', 
2 => 'xxx.com:8080', 
3 => '0.0.0.0:8080', 
 ),
*  I can login with chrome/firefox without error: https://xxx.com, so I believe nginx setting should be OK.

* However, I failed to login with desktop 3.0.3 (windows 10) and android app (samsung glaxy s10). 
When I trided to login the domain: https://xxx.com, it redirected to the login UI, and then I succedded to login. After that, I clicked the button "Grant Access". It told me account was connected and the web link could be closed. However, when I returned back to the desktop/app, the same error showed:

`Access forbidden by server. To verify that you have proper access, "click here" to access the service with your browser.`

When I clicked the link "click here", I **can access** the files in the web browser. 

I attached the logs below:
```
Exception: Argument 1 passed to OC\Core\Controller\ClientFlowLoginV2Controller::grantPage() must be of the type string, null given, called in /share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169
/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "grantPage")

/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main("OC\\Core\\C ... r", "grantPage", OC\AppFramew ... {}, { action: nu ... "})

/share/CACHEDEV1_DATA/Web/nextcloud/lib/base.php - line 1009:

OC\Route\Router->match("/login/v2/grant")

/share/CACHEDEV1_DATA/Web/nextcloud/index.php - line 37:

OC::handleRequest()

TypeError: Argument 1 passed to OC\Core\Controller\ClientFlowLoginV2Controller::grantPage() must be of the type string, null given, called in /share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169
/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

OC\Core\Controller\ClientFlowLoginV2Controller->grantPage(null)

/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Cont ... {}, "grantPage")

/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/AppFramework/App.php - line 152:

OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "grantPage")

/share/CACHEDEV1_DATA/Web/nextcloud/lib/private/Route/Router.php - line 308:

OC\AppFramework\App::main("OC\\Core\\C ... r", "grantPage", OC\AppFramew ... {}, { action: nu ... "})

/share/CACHEDEV1_DATA/Web/nextcloud/lib/base.php - line 1009:

OC\Route\Router->match("/login/v2/grant")

/share/CACHEDEV1_DATA/Web/nextcloud/index.php - line 37:

OC::handleRequest()
```

**Comment by kesselb** [comment] 2020-11-12 10:35
Duplicate of https://github.com/nextcloud/server/issues/23117

**Closed by kesselb** 2020-11-12 10:35 UTC

**Comment by hysci** [comment] 2020-11-13 01:53
I don't think it is a duplicate of  #23117
The difference is:
- 'overwriteprotocol' => 'https', this flag was set to https in my case. 
- I can correctly login via browser in my case

**Comment by hysci** [comment] 2020-11-13 02:02
https://help.nextcloud.com/t/cannot-grant-access/64566/27
Lots of people still have this problem remained even they set overwriteprotocol to https.
