### ISSUE TITLE
Links in shared .md files are unreadable, displayed black on dark background

### ISSUE THREAD

**Issue by cloo** [nextcloud/server#25461] opened 2021-02-03 11:15 UTC
### Steps to reproduce
1. Create .md
2. Add any link
3. Share file

### Expected behaviour
shared .md files are rendered on dark background, so white text color is expected

### Actual behaviour
links are rendered black on almost black background

![TS8CHZyUXv](https://user-images.githubusercontent.com/651760/106739269-9da93c80-6621-11eb-89ec-38ed2cd2d3b9.gif)

 
**Nextcloud version:** 
20.07

**Comment by szaimen** [comment] 2021-06-23 12:36
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-23 12:36 UTC
Labels: 0. Needs triage, bug
