### ISSUE TITLE
[Bug]: 25.0.3 fresh install fails integrity check

### ISSUE THREAD

**Issue by 4nanook** [nextcloud/server#36368] opened 2023-01-25 21:55 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Freshly installed 25.0.3 no local modifications, fails integrity check:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
	- EXTRA_FILE
		- core/img/filetypes/drawio.svg
		- core/img/filetypes/dwb.svg

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 4b0a99fbab7bc4824176101150bd0ab2b553e128a390e0f872580db4541462b31aad13099fd41533b6695d1b185dabca26a45e9a78227cfb9479eafa439c7bff
                            [current] => 277ae695af1c4997b9bad3c8263b871c1efbccc2ff8a0e536987bcce37dddf0727a096ca11e890c143048d845315624f419f4915afa88d08e20ae89b90e24444
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [core/img/filetypes/drawio.svg] => Array
                        (
                            [expected] => 
                            [current] => 92e0974cf869bf8ab969c3442dc2b80d55fde36441d22924db74916a06b407520aa2a9dc39336f9157195ebede697ffac0e639360879255ab91932d406e1897d
                        )

                    [core/img/filetypes/dwb.svg] => Array
                        (
                            [expected] => 
                            [current] => 43731dd5f17a048112ea5109b40b02ec019b3ee2324385a0f448e3bd2264cb13dc160ab018d893f92f8e2f168fd09009b51578c8c6b97a02a1617c67ac087701
                        )

                )

        )

)

### Steps to reproduce

1. Manually install 25.0.3
2. Run integrity check
3.

### Expected behavior

Pass with all files having correct hashsums.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.eskimo.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "https:\/\/nextcloud.eskimo.com\/",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "user_backends": [
            {
                "class": "\\OCA\\UserExternal\\IMAP",
                "arguments": [
                    "204.122.16.222",
                    143,
                    "none",
                    "",
                    false,
                    false
                ]
            }
        ],
        "data-fingerprint": "15c5e08aba95f4a9f58603c46b0bedc9",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "theme": "",
        "log_type": "file",
        "logfile": "\/misc\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "updater.release.channel": "stable",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "auto_mail_accounts",
            "caniupdate",
            "whiteboard",
            "ojsxc",
            "user_ispconfig",
            "integration_moodle"
        ],
        "ldapIgnoreNamingRules": false,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": true,
        "default_phone_region": "ISO 3166-2:US",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
php occ app:list
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - afterlogic: 2.0.5
  - analytics: 4.6.0
  - announcementcenter: 6.4.0
  - appointments: 1.14.10
  - approval: 1.0.12
  - audioplayer: 3.3.1
  - bookmarks: 12.0.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - camerarawpreviews: 0.8.0
  - cfg_share_links: 3.0.2
  - checksum: 1.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - cms_pico: 1.0.21
  - comments: 1.15.0
  - contacts: 5.0.3
  - contactsinteraction: 1.6.0
  - cookbook: 0.10.1
  - cospend: 1.5.5
  - cpanelmailsync: 0.1.7
  - csp_editor: 1.1.0
  - dav: 1.24.0
  - deck: 1.8.3
  - drawio: 2.1.0
  - drop_account: 2.1.0
  - eidlogin: 1.0.11
  - encryption: 2.13.0
  - event_update_notification: 2.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_automatedtagging: 1.15.0
  - files_downloadactivity: 1.15.0
  - files_downloadlimit: 1.0.1
  - files_external: 1.17.0
  - files_inotify: 0.1.13
  - files_linkeditor: 1.1.13
  - files_lock: 24.0.1
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_photospheres: 1.25.2
  - files_retention: 1.14.1
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_snapshots: 1.0.5
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_versions_s3: 0.1.9
  - files_zip: 1.1.2
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.3
  - geoblocker: 0.5.7
  - gestion: 2.2.2
  - gpoddersync: 3.7.1
  - gpxpod: 5.0.4
  - grauphel: 1.0.18
  - group_everyone: 0.1.11
  - groupfolders: 13.1.0
  - groupquota: 0.1.9
  - guests: 2.3.0
  - integration_discourse: 1.0.4
  - integration_dropbox: 1.0.6
  - integration_github: 1.0.14
  - integration_gitlab: 1.0.12
  - integration_google: 1.0.9
  - integration_jira: 1.0.4
  - integration_mastodon: 1.0.3
  - integration_moodle: 1.0.2
  - integration_onedrive: 1.1.4
  - integration_openproject: 2.1.0
  - integration_reddit: 1.0.5
  - integration_twitter: 1.0.3
  - integration_zammad: 2.0.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - maps: 0.2.4
  - mediadc: 0.3.3
  - metadata: 0.17.0
  - music: 1.8.1
  - ncdownloader: 1.0.2
  - news: 20.0.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - notify_push: 0.5.2
  - oauth2: 1.13.0
  - oidc: 0.2.9
  - onlyoffice: 7.6.8
  - ownpad: 0.7.1
  - passman: 2.4.3
  - password_policy: 1.15.0
  - passwords: 2023.1.13
  - pax_fax: 1.0.9
  - phonetrack: 0.7.4
  - photos: 2.0.1
  - polls: 4.1.2
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - qownnotesapi: 22.10.0
  - quicknotes: 0.8.5
  - quota_warning: 1.15.0
  - rainloop: 7.2.6
  - ransomware_protection: 1.14.0
  - recognize: 3.3.6
  - recommendations: 1.4.0
  - registration: 2.0.0
  - related_resources: 1.0.3
  - richdocuments: 7.1.0
  - richdocumentscode: 22.5.802
  - root_cache_cleaner: 0.1.3
  - sendent: 1.3.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - sharerenamer: 3.1.0
  - sip_trip_phone: 1.0.9
  - smb_test: 0.3.5
  - sms_relentless: 1.1.4
  - sociallogin: 5.3.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - timemanager: 0.3.4
  - timetracker: 0.0.77
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.1
  - twofactor_nextcloud_notification: 3.5.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - unsplash: 2.1.1
  - updatenotification: 1.15.0
  - uppush: 1.1.3
  - user_external: 3.1.0
  - user_ldap: 1.15.0
  - user_migration: 2.0.1
  - user_oidc: 1.2.1
  - user_retention: 1.8.1
  - user_status: 1.5.0
  - user_usage_report: 1.9.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - webapppassword: 23.1.0
  - welcome: 1.0.6
  - workflow_ocr: 1.25.2
  - workflowengine: 2.7.0
Disabled:
  - dashboard: 7.5.0
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
	- EXTRA_FILE
		- core/img/filetypes/drawio.svg
		- core/img/filetypes/dwb.svg

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 4b0a99fbab7bc4824176101150bd0ab2b553e128a390e0f872580db4541462b31aad13099fd41533b6695d1b185dabca26a45e9a78227cfb9479eafa439c7bff
                            [current] => 277ae695af1c4997b9bad3c8263b871c1efbccc2ff8a0e536987bcce37dddf0727a096ca11e890c143048d845315624f419f4915afa88d08e20ae89b90e24444
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [core/img/filetypes/drawio.svg] => Array
                        (
                            [expected] => 
                            [current] => 92e0974cf869bf8ab969c3442dc2b80d55fde36441d22924db74916a06b407520aa2a9dc39336f9157195ebede697ffac0e639360879255ab91932d406e1897d
                        )

                    [core/img/filetypes/dwb.svg] => Array
                        (
                            [expected] => 
                            [current] => 43731dd5f17a048112ea5109b40b02ec019b3ee2324385a0f448e3bd2264cb13dc160ab018d893f92f8e2f168fd09009b51578c8c6b97a02a1617c67ac087701
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
There are 41360 lines in the log file, not practical to cut-n-paste.
```

### Additional info

I have data in a separate directory.  Prior to upgrading nextcloud itself, I upgraded all the apps so they were all current.  I moved the old nextcloud directory to nextcloud.old, unpacked the new tar.bz2 archive in place with tar -xvjf nextcloud-25.0.3.tar.bz2, which created a new nextcloud directory.  I then chown -R nextcloud.nextcloud nextcloud to give nextcloud ownership to all the files since I unpacked as root.  On my server, it is modified so that it runs all applications under the user ID of the files owner provided it's above uid 300 and not root.  This way nextcloud doesn't have access to friendica or other web app files, etc.  Then I did php occ upgrade.  It completed successfully, but when I go to administrative settings it fails the integrity check.

**Comment by szaimen** [comment] 2023-01-25 22:34
At least one seems to come from the drawio app.the other not sure. However I cannot reproduce the issue so one of your additionally installed apps is triggering this.

**Comment by kesselb** [comment] 2023-01-25 22:34
Thanks :+1: 

Closing in favor of https://github.com/jgraph/drawio-nextcloud/issues/26

**Closed by szaimen** 2023-01-25 22:34 UTC
Labels: bug, 0. Needs triage

**Comment by 4nanook** [comment] 2023-01-25 23:03
This was closed prematurely, surely drawio was PART of the problem, but I've removed that and I'm still getting this failure:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 4b0a99fbab7bc4824176101150bd0ab2b553e128a390e0f872580db4541462b31aad13099fd41533b6695d1b185dabca26a45e9a78227cfb9479eafa439c7bff
                            [current] => 277ae695af1c4997b9bad3c8263b871c1efbccc2ff8a0e536987bcce37dddf0727a096ca11e890c143048d845315624f419f4915afa88d08e20ae89b90e24444
                        )

                )

        )

)

**Comment by kesselb** [comment] 2023-01-25 23:15
Removing the drawio app does not revert the changes done by the drawio app to core/js/mimetypelist. The drawio app developer already working on a solution. 

I guess it should work to replace core/js/mimetypelist.js with the file from the release.zip to fix the integrity check. Don't forget to trigger a rescan.

When you have further questions/issues with Nextcloud please visit our friendly community at:  https://help.nextcloud.com. GitHub is our channel to report bugs and not for end-user support.

**Comment by 4nanook** [comment] 2023-01-25 23:39
I re-installed a second time, this time without drawio and now everything is copacetic.
