### ISSUE TITLE
[Bug]: Drag and drop of multiple files, uploads just one file

### ISSUE THREAD

**Issue by SMH17** [nextcloud/server#44115] opened 2024-03-10 23:48 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you attempt to upload multiple files with drag and drop from web interface, only one of the files is uploaded.

The new drag and drop interface that previously was affected by [this bug](https://github.com/nextcloud/server/issues/42136) introduced with Nextcloud 28.0.0 that prevented drag and drop use completely, hasn't drag and drop functionality properly working and latest stable 28.0.3 is affected by this other bug with multiple files drag and drop.

### Steps to reproduce

1. Select more than one file
2. Drag and drop them in web interface

### Expected behavior

All dropped files must be uploaded

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2024-03-11 08:27
Duplicate of https://github.com/nextcloud/server/issues/43074

**Closed by solracsf** 2024-03-11 08:27 UTC
Labels: bug, 0. Needs triage, 28-feedback
