### ISSUE TITLE
[NC20] Disabled accessibility app breaks dashboard

### ISSUE THREAD

**Issue by dasfreak** [nextcloud/server#23246] opened 2020-10-07 07:37 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. disable accessibility app
2. look at dashboard
3. activate accessibility app
2. look at dashboard

### Expected behaviour
Dashboard should still work without the  accessibility app

### Actual behaviour
Dashboard will not load properly. (See Browser Log)

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** apache and traefik

**Database:** MariaDB 10

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** update from latest NC19

**Where did you install Nextcloud from:** docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.6.0
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.5.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - previewgenerator: 3.0.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.4
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.arcdev.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "overwrite.cli.url": "http:\/\/cloud.arcdev.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwriteprotocol": "https",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 86.0.4240.75 (64-bit)

**Operating system:** Manjaro

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
versionstabview.js:18 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.<anonymous> (versionstabview.js:18)
    at n (bootstrap:19)
    at bootstrap:83
    at files_versions.js?v=47368890-0:1
(anonymous) @ versionstabview.js:18
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_versions.js?v=47368890-0:1
vue.runtime.esm.js:1888 TypeError: Cannot read property 'theme' of undefined
    at a.data (App.vue:144)
    at a.<anonymous> (vue.runtime.esm.js:1219)
    at a.<anonymous> (vue.runtime.esm.js:1230)
    at vue.runtime.esm.js:4748
    at vue.runtime.esm.js:4705
    at hn (vue.runtime.esm.js:4642)
    at a.e._init (vue.runtime.esm.js:5006)
    at new a (vue.runtime.esm.js:5154)
    at Module.<anonymous> (main.js:21)
    at n (bootstrap:19)
Ye @ vue.runtime.esm.js:1888
Ve @ vue.runtime.esm.js:1879
$e @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:4750
(anonymous) @ vue.runtime.esm.js:4705
hn @ vue.runtime.esm.js:4642
e._init @ vue.runtime.esm.js:5006
a @ vue.runtime.esm.js:5154
(anonymous) @ main.js:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ dashboard.js?v=47368890-0:1
vue.runtime.esm.js:1888 TypeError: Cannot read property 'match' of undefined
    at a.backgroundStyle (App.vue:152)
    at pn.get (vue.runtime.esm.js:4479)
    at pn.evaluate (vue.runtime.esm.js:4584)
    at a.backgroundStyle (vue.runtime.esm.js:4836)
    at a.<anonymous> (App.vue?6cbf:1)
    at a.e._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
    at pn.get (vue.runtime.esm.js:4479)
    at new pn (vue.runtime.esm.js:4468)
    at e (vue.runtime.esm.js:4073)
Ye @ vue.runtime.esm.js:1888
Ve @ vue.runtime.esm.js:1879
$e @ vue.runtime.esm.js:1839
e._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
pn.get @ vue.runtime.esm.js:4479
pn @ vue.runtime.esm.js:4468
e @ vue.runtime.esm.js:4073
_n.$mount @ vue.runtime.esm.js:8415
(anonymous) @ main.js:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ dashboard.js?v=47368890-0:1
Viewer.vue:214 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:214
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
Viewer.vue:508 The following mime is already registered text/csv {__ob__: De}
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
Viewer.vue:508 The following mime is already registered image/svg+xml {__ob__: De}
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
Viewer.vue:508 The following mime is already registered text/plain {__ob__: De}
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ viewer.js:15
vue.runtime.esm.js:1076 Uncaught TypeError: Cannot use 'in' operator to search for 'weather' in undefined
    at Function.Ce [as set] (vue.runtime.esm.js:1076)
    at a.registerStatus (App.vue:244)
    at Object.registerStatus (main.js:25)
    at HTMLDocument.<anonymous> (weather-status.js:20)
Ce @ vue.runtime.esm.js:1076
registerStatus @ App.vue:244
registerStatus @ main.js:25
(anonymous) @ weather-status.js:20
vue.runtime.esm.js:1076 Uncaught TypeError: Cannot use 'in' operator to search for 'calendar' in undefined
    at Function.Ce [as set] (vue.runtime.esm.js:1076)
    at a.register (App.vue:240)
    at Object.register (main.js:24)
    at HTMLDocument.<anonymous> (dashboard.js:42)
Ce @ vue.runtime.esm.js:1076
register @ App.vue:240
register @ main.js:24
(anonymous) @ dashboard.js:42
vue.runtime.esm.js:1076 Uncaught TypeError: Cannot use 'in' operator to search for 'mail' in undefined
    at Function.Ce [as set] (vue.runtime.esm.js:1076)
    at a.register (App.vue:240)
    at register (main.js:24)
    at HTMLDocument.<anonymous> (main-dashboard.js:38)
Ce @ vue.runtime.esm.js:1076
register @ App.vue:240
register @ main.js:24
(anonymous) @ main-dashboard.js:38
vue.runtime.esm.js:1076 Uncaught TypeError: Cannot use 'in' operator to search for 'recommendations' in undefined
    at Function.Ce [as set] (vue.runtime.esm.js:1076)
    at a.register (App.vue:240)
    at Object.register (main.js:24)
    at HTMLDocument.<anonymous> (dashboard.js:37)
Ce @ vue.runtime.esm.js:1076
register @ App.vue:240
register @ main.js:24
(anonymous) @ dashboard.js:37
vue.runtime.esm.js:1076 Uncaught TypeError: Cannot use 'in' operator to search for 'user_status' in undefined
    at Function.Ce [as set] (vue.runtime.esm.js:1076)
    at a.register (App.vue:240)
    at Object.register (main.js:24)
    at HTMLDocument.<anonymous> (dashboard.js:41)
Ce @ vue.runtime.esm.js:1076
register @ App.vue:240
register @ main.js:24
(anonymous) @ dashboard.js:41
vue.runtime.esm.js:1076 Uncaught TypeError: Cannot use 'in' operator to search for 'status' in undefined
    at Function.Ce [as set] (vue.runtime.esm.js:1076)
    at a.registerStatus (App.vue:244)
    at Object.registerStatus (main.js:25)
    at HTMLDocument.<anonymous> (main-user-status-menu.js:54)
Ce @ vue.runtime.esm.js:1076
registerStatus @ App.vue:244
registerStatus @ main.js:25
(anonymous) @ main-user-status-menu.js:54
Viewer.vue:214 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:214
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ main.js:26
Viewer.vue:508 The following mime is already registered application/pdf {__ob__: De}
(anonymous) @ Viewer.vue:508
registerHandler @ Viewer.vue:505
handlers @ Viewer.vue:217
fr.run @ vue.runtime.esm.js:4568
cr @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
Xe @ vue.runtime.esm.js:1906
Promise.then (async)
Ye @ vue.runtime.esm.js:1933
tt @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
fr.update @ vue.runtime.esm.js:4544
le.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:78
(anonymous) @ main.js:26

```
</details>

**Comment by CaptainSifff** [comment] 2020-10-07 12:49
My installation was OpenSUSE with official rpm packages. Browser was firefox 68.10.0esr.

**Comment by splitt3r** [comment] 2020-10-10 08:45
I think this shouldbe fixed with https://github.com/nextcloud/server/pull/23179. Maybe you could give it a try.

**Comment by kesselb** [comment] 2020-11-09 11:47
Duplicate of https://github.com/nextcloud/server/issues/22966

**Closed by kesselb** 2020-11-09 11:47 UTC
Labels: 0. Needs triage, 20-feedback, bug, feature: dashboard
