### ISSUE TITLE
CalDav/Card is broken after snap upgrade/downgrade.

### ISSUE THREAD

**Issue by aquatic7** [nextcloud/server#13579] opened 2019-01-14 12:17 UTC
I updated my nextcloud from 12 to 15 by doing $ sudo snap refresh nextcloud --channel=15/candidate

It resulted in that i could not log in, but was stuck with the maintenance screen. I therefore downgraded again with $ sudo snap refresh nextcloud --channel=stable

Now my CalDav and CardDav won't sync with any of my devices/apps anymore. It is like it can't make any connection. I have a log from DavDroid if that's of any help: https://pastebin.com/YJzd4MPU

It says "Couldn't find CalDAV or CardDAV service.

I assume that the upgrade/downgrade has broken something, but I can not find out what.

# EDIT
I have upgraded to v15 again and didn't encounter the maintance screen. Everything works perfectly, except for the calendar and contact sync. :(

**Comment by phish108** [comment] 2019-01-15 06:01
Had a similar problem recently. It seems that the locations for CardDAV and CalDAV changed since 12. 

After re-configuring the clients using the auto configuration feature via .well-known/* URLs everything works nicely.

**Comment by aquatic7** [comment] 2019-01-15 11:39
> Had a similar problem recently. It seems that the locations for CardDAV and CalDAV changed since 12.
> 
> After re-configuring the clients using the auto configuration feature via .well-known/* URLs everything works nicely.

is it possible you can tell me how to re-configure the client using the auto configuration feature via well-known/* URLs ? How do I do that?

**Comment by phish108** [comment] 2019-01-15 12:16
It helped reading this part of the docu https://docs.nextcloud.com/server/14/admin_manual/issues/general_troubleshooting.html#service-discovery

After the redicrection is setup, at least iOS clients just need the root-Url of your instance (eg. example.com/nc) and the user name and password. If that is not working, I you need to enter the referred url instead.

**Comment by skjnldsv** [comment] 2019-03-03 19:04
Any news? Is it ficed @aquatic7 ?

**Comment by MorrisJobke** [comment] 2019-03-25 12:50
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-03-25 12:50 UTC
Labels: needs info
