### ISSUE TITLE
Caldav sync stops syncing after upgrade to nextcloud 18.0.4

### ISSUE THREAD

**Issue by sonologic** [nextcloud/server#20684] opened 2020-04-27 10:54 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install nextcloud 18.0.4 (i'm using the docker 18.0.4-fpm variant)
2. Create user
3. Create calendars as user, create some tasks
4. On android install caldav sync
5. Connect caldav sync with nextcloud
6. Install OpenTasks
7. Create task in nextcloud web interface
8. Create task in opentasks
9. Sync (in android go to settins -> accounts -> choose caldav account -> account sync -> 3 dots -> sync now

### Expected behaviour

opentasks should show task created on nextcloud, nextcloud should show task created in opentasks

### Actual behaviour
opentasks does not show task created on nextcloud, nextcloud does not show task created in opentasks. Log will show various errors:

```
{"reqId":"sNxhju62FTVbHkfD0GD7","level":0,"time":"2020-04-27T10:18:21+00:00","remoteAddr":"1.2.3.4","user":"--","app":"webdav","method":"OPTIONS","url":"/remote.php/dav/calendars/username/calendarname/","message":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name /calendars could not be located","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":68,"function":"getChild","class":"Sabre\\DAV\\FS\\Directory","type":"->","args":["calendars"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":71,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["calendars"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php","line":76,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["calendars/username"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":535,"function":"getHTTPMethods","class":"Sabre\\CalDAV\\Plugin","type":"->","args":["calendars/username/calendarname"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":212,"function":"getAllowedMethods","class":"Sabre\\DAV\\Server","type":"->","args":["calendars/username/calendarname"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php","line":75,"function":"httpOptions","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://example.com/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"function":"handleAnonymousOptions","class":"OCA\\DAV\\Connector\\Sabre\\AnonymousOptionsPlugin","type":"->","args":[{"absoluteUrl":"https://cloud.metro.cx/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\AnonymousOptionsPlugin"},"handleAnonymousOptions"],[{"absoluteUrl":"https://cloud.metro.cx/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",[{"absoluteUrl":"https://example.com/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://example.com/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":165,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/sabre/dav/lib/DAV/FS/Directory.php","Line":76,"CustomMessage":"--"},"userAgent":"CalDAV-Sync/0.4.32 (Sony; H3113; Android 9; en_NL; org.dmfs.caldav.lib/748; like iOS/5.0.1 (9A405) dataaccessd/1.0)","version":"18.0.4.2"}
```

### Server configuration

**Operating system:**

Linux odroid 4.14.170-odroidxu4 #7 SMP PREEMPT Mon Feb 17 07:48:53 CET 2020 armv7l GNU/Linux

**Web server:**

nginx version: nginx/1.17.10

**Database:**

mysql  Ver 15.1 Distrib 10.0.38-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2

**PHP version:**

PHP 7.3.17 (cli) (built: Apr 17 2020 12:59:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from 18.0.3

**Where did you install Nextcloud from:**

https://github.com/nextcloud/docker.git

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.6.0 
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - news: 14.1.4
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - issuetemplate
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com",
            "4.5.6.7"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "app_install_overwrite": [
            "calendar"
        ],
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

n/a

**Operating system:**

Android

#### Web server error log
<details>
<summary>Web server error log</summary>

```
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:19 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:20 +0000 "OPTIONS /remote.php" 404
172.20.0.6 -  27/Apr/2020:10:18:20 +0000 "OPTIONS /remote.php" 404
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"sNxhju62FTVbHkfD0GD7","level":0,"time":"2020-04-27T10:18:21+00:00","remoteAddr":"1.2.3.4","user":"--","app":"webdav","method":"OPTIONS","url":"/remote.php/dav/calendars/username/calendarname/","message":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name /calendars could not be located","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":68,"function":"getChild","class":"Sabre\\DAV\\FS\\Directory","type":"->","args":["calendars"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":71,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["calendars"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php","line":76,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["calendars/username"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":535,"function":"getHTTPMethods","class":"Sabre\\CalDAV\\Plugin","type":"->","args":["calendars/username/calendarname"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":212,"function":"getAllowedMethods","class":"Sabre\\DAV\\Server","type":"->","args":["calendars/username/calendarname"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php","line":75,"function":"httpOptions","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://example.com/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"function":"handleAnonymousOptions","class":"OCA\\DAV\\Connector\\Sabre\\AnonymousOptionsPlugin","type":"->","args":[{"absoluteUrl":"https://cloud.metro.cx/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\AnonymousOptionsPlugin"},"handleAnonymousOptions"],[{"absoluteUrl":"https://cloud.metro.cx/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",[{"absoluteUrl":"https://example.com/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://example.com/remote.php/dav/calendars/username/calendarname/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":165,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/sabre/dav/lib/DAV/FS/Directory.php","Line":76,"CustomMessage":"--"},"userAgent":"CalDAV-Sync/0.4.32 (Sony; H3113; Android 9; en_NL; org.dmfs.caldav.lib/748; like iOS/5.0.1 (9A405) dataaccessd/1.0)","version":"18.0.4.2"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n/a
```
</details>

**Comment by sonologic** [comment] 2020-04-27 10:56
As a work-around, I can enable the potentially unsafe workaround in caldav sync 'Use preemptive authentication' to make it work again. This was not necessary with 18.0.3.

Feels like a regression of https://github.com/nextcloud/server/pull/13354

**Comment by lvwouwe** [comment] 2020-04-27 11:39
Same problem here after upgrading to 18.0.4

**Comment by zwoggel** [comment] 2020-04-27 16:53
I'm using z-push with nextcloud as caldav backend and since updating to 18.04 I can't sync anymore as well. Z-push just says that the user couldn't be authenticated.

**Comment by jum** [comment] 2020-04-27 16:54
I have a similar problem with carddav and MacOS, smells like a similar problem:

`{"reqId":"zHXRcXr8gVlld3SwjBAU","level":0,"time":"2020-04-27T16:48:28+00:00","re
moteAddr":"2003:ea:af16:bb00:9831:c4b0:c50f:56ff","user":"--","app":"webdav","me
thod":"OPTIONS","url":"/nextcloud/remote.php/dav/principals/users/jum/","message
":{"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"File with name /prin
cipals could not be located","Code":0,"Trace":[{"file":"/usr/local/var/www/nextc
loud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":68,"function":"getChild","class
":"Sabre\\DAV\\FS\\Directory","type":"->","args":["principals"]},{"file":"/usr/l
ocal/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":71,"function"
:"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["principals"]},
{"file":"/usr/local/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php",
"line":76,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","ar
gs":["principals/users"]},{"file":"/usr/local/var/www/nextcloud/3rdparty/sabre/d
av/lib/DAV/Server.php","line":535,"function":"getHTTPMethods","class":"Sabre\\CalDAV\\Plugin","type":"->","args":["principals/users/jum"]},{"file":"/usr/local/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":212,"function":"getAllowedMethods","class":"Sabre\\DAV\\Server","type":"->","args":["principals/users/jum"]},{"file":"/usr/local/var/www/nextcloud/apps/dav/lib/Connector/Sabre/AnonymousOptionsPlugin.php","line":75,"function":"httpOptions","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://anubis.mager.org/nextcloud/remote.php/dav/principals/users/jum/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"function":"handleAnonymousOptions","class":"OCA\\DAV\\Connector\\Sabre\\AnonymousOptionsPlugin","type":"->","args":[{"absoluteUrl":"https://anubis.mager.org/nextcloud/remote.php/dav/principals/users/jum/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/usr/local/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\AnonymousOptionsPlugin"},"handleAnonymousOptions"],[{"absoluteUrl":"https://anubis.mager.org/nextcloud/remote.php/dav/principals/users/jum/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/usr/local/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",[{"absoluteUrl":"https://anubis.mager.org/nextcloud/remote.php/dav/principals/users/jum/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/usr/local/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://anubis.mager.org/nextcloud/remote.php/dav/principals/users/jum/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/usr/local/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/usr/local/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/usr/local/var/www/nextcloud/remote.php","line":165,"args":["/usr/local/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/usr/local/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/FS/Directory.php","Line":76,"CustomMessage":"--"},"userAgent":"Mac OS X/10.15.4 (19E287) AddressBookCore/1","version":"18.0.4.2"}`

**Comment by kesselb** [comment] 2020-04-27 17:00
Duplicate of #20624. Fix is already confirmed for next release.

**Closed** 2020-04-29 20:24 UTC
Labels: 0. Needs triage, 18-feedback, bug, feature: dav
