### ISSUE TITLE
Download takes a long time to start, but download speed is then very fast

### ISSUE THREAD

**Issue by gitnxcl** [nextcloud/server#17651] opened 2019-10-23 06:15 UTC
Hello everybody,

i run Nextcloud 16.0.5 on Ubuntu 18.04 LTS with Apache2 and Php7.3-fpm.
Works great so far, but there are problems downloading large files.

If I click on “download” for a larger file, starting at approx. 100mb, it curls on the file for a while, the browser reports “Wait for…” and at some point the actual download starts. Funnily enough, the actually download is extremely fast.

![image](https://user-images.githubusercontent.com/56908346/67363190-1d1a1600-f56d-11e9-8dee-a6325730993e.png)

Did anyone had a similar problem?
**Which configuration / log files do you need?**

Similar with starting a video from a shared link…
![image](https://user-images.githubusercontent.com/56908346/67363222-2d31f580-f56d-11e9-8fbd-2c70aaa2be18.png)
loading … and loading … and loading

Please help…

**Comment by kesselb** [comment] 2020-02-02 18:52
Do you still see this issue?

**Comment by szaimen** [comment] 2021-06-07 16:05
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 16:05 UTC
Labels: 0. Needs triage, bug, feature: files
