### ISSUE TITLE
Loading bar by multiple upload on SecureDrop

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#5048] opened 2017-05-22 18:47 UTC
If you share a folder with SecureDrop (opload only) and select more than one file, the loading bar is shown all the time. The first file-icon is correct changed to an image but all other files are still have a loading bar.
If I look into the folder, the files are complete uploaded. The icon is here not correct :)

![image](https://cloud.githubusercontent.com/assets/1473674/26323588/c5359dec-3f2f-11e7-8f4b-dfd0bf6079ae.png)

NextCloud 12.0.0 on Ubuntu 17.04 (PHP7.1) with Firefox 53.0.3

**Comment by GetBoz** [comment] 2017-05-24 09:48
Same problem on my server (12.0.0) and on demo.nextcloud.com (12.0.0.1)

**Comment by lx-s** [comment] 2017-06-12 11:02
Same problem also on multiple installations shared webhoster AllInkl.

No Error-logs or Javascript browser console warnings are generated :/

**Comment by GetBoz** [comment] 2017-08-10 09:18
Same issue in 12.0.1

**Comment by DaCryptor** [comment] 2017-08-12 08:07
See issue #6060 

Does anyone have an idea for a quick workaround?

**Comment by MorrisJobke** [comment] 2017-08-14 16:07
Duplicate of #6060

**Closed by MorrisJobke** 2017-08-14 16:07 UTC
