### ISSUE TITLE
[Swiftmailer] SMTP settings/Sent Test Mail do not work

### ISSUE THREAD

**Issue by christophfroehlich** [nextcloud/server#13279] opened 2018-12-27 21:02 UTC
### Steps to reproduce

1. Login to Nextcloud
2. Goto Settings/Basic Settings
3. Insert Mail settings
4. Push "Send Mail"

### Expected behaviour
Receiving an email at the users mail address.

### Actual behaviour

No mail is sent, directly beneath the Send Mail button following error appears instead:
> A problem occurred while sending the email. Please revise your settings. (Error: Expected response code 220 but got an empty response)

In the logging section the following errors are shown:
>  [PHP] Error: stream_set_timeout() expects parameter 1 to be resource, null given at /data/web/ftpuser/html/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php#279
> POST /index.php/settings/admin/mailtest

> [PHP] Error: stream_set_blocking() expects parameter 1 to be resource, null given at /data/web/ftpuser/html/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php#275
> POST /index.php/settings/admin/mailtest

### Server configuration

**Operating system**:
Linux 4.9.110-3+deb9u4 (hosted server)

**Web server:**
Apache 2.4

**Database:**
Percona Server 5.7.22

**PHP version:**
7.1.23

**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
https://nextcloud.com/install/#instructions-server

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
no sudo rights on server

```
Accessibility	1.1.0	Official	
Activity	2.8.2	Official	
Calendar	1.6.4	Official	
Collaborative tags	1.5.0	Official	
Comments	1.5.0	Official	
Deleted files	1.5.0	Official	
External sites	3.2.0	Official	
Federation	1.5.0	Official	
File sharing	1.7.0	Official	
First run wizard	2.4.0	Official	
Gallery	18.2.0	Official	
Log Reader	2.0.0	Official	
Monitoring	1.5.0	Official	
Nextcloud announcements	1.4.0	Official	
Notifications	2.3.0	Official	
Password policy	1.5.0	Official	
PDF viewer	1.4.0	Official	
Share by mail	1.5.0	Official	
Support	1.0.0	Official	
Text editor	2.7.0	Official	
Theming	1.6.0	Official	
Update notification	1.5.0	Official	
Usage survey	1.3.0	Official	
Versions	1.8.0	Official	
Video player	1.4.0	Official	
Auditing / Logging	1.5.0	Official	
Default encryption module	2.3.0	Official	
External storage support	1.6.0	Official	
External user support	0.4	Official	
Full text search	1.2.3		 
Full text search - Elasticsearch Platform	1.2.2		 
Full text search - Files	1.2.3		 
Group folders	2.0.2	Official	 
LDAP user and group backend	1.5.0	Official	
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
 'mail_from_address' => 'admin',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'anydomain.at',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'admin@anydomain.at',
  'mail_smtppassword' => 'somepassword',
  'mail_smtpport' => '465',
  'mail_sendmailmode' => 'smtp',
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 71

**Operating system:**
macOS 10.12.6

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XCUxHI7cswpZewimbC0eNAAAAI0","level":3,"time":"2018-12-27T20:07:57+00:00","remoteAddr":"80.110.109.176","user":"christoph.froehlich","app":"PHP","method":"POST","url":"\/index.php\/settings\/admin\/mailtest","message":"stream_set_blocking() expects parameter 1 to be resource, null given at \/data\/web\/e67967\/html\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Transport\/StreamBuffer.php#275","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"15.0.0.10"}
{"reqId":"XCUxHI7cswpZewimbC0eNAAAAI0","level":3,"time":"2018-12-27T20:07:57+00:00","remoteAddr":"80.110.109.176","user":"christoph.froehlich","app":"PHP","method":"POST","url":"\/index.php\/settings\/admin\/mailtest","message":"stream_set_timeout() expects parameter 1 to be resource, null given at \/data\/web\/e67967\/html\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Transport\/StreamBuffer.php#279","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.98 Safari\/537.36","version":"15.0.0.10"}
```
</details>

**Comment by Freshdouble** [comment] 2018-12-28 11:48
This is linked to an issue in swiftmailer that is addressed here:
https://github.com/octobercms/october/issues/3423

The error is created in these lines:
https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/StreamBuffer.php#L266-L273

These lines only check for a false return value of stream_socket_client which is ok if this plugin or function is allowed in php. If this function is disabled or it doesn't exists it would return null.

**Comment by christophfroehlich** [comment] 2018-12-28 15:43
according to the documentation of swiftmailer: https://swiftmailer.symfony.com/docs/introduction.html
> (proc_* functions must be available)
which seems not to be the case on our hosted server.

Maybe there could be some error handling implemented to get an idea why the mail feature is not working properly.

**Comment by skjnldsv** [comment] 2020-03-10 08:17
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-03-10 08:17 UTC
Labels: 0. Needs triage, bug, feature: emails
