### ISSUE TITLE
Keep opened the side panel and tags

### ISSUE THREAD

**Issue by plyaskin** [nextcloud/server#12066] opened 2018-10-26 13:26 UTC
Hi!

Could you add the checkbox to keep always open the right side panel with properties also tags always expanded?

**Comment by violoncelloch** [comment] 2018-10-26 15:28
relatet to (/duplicate of) #7138

**Comment by MorrisJobke** [comment] 2018-10-28 21:40
Duplicate of #7138

**Closed by MorrisJobke** 2018-10-28 21:40 UTC
Labels: design, enhancement, feature: files, feature: tags
