### ISSUE TITLE
[Bug]:  update to 28.0.0 beta 1 / Database error when running migration 2800

### ISSUE THREAD

**Issue by Juergen-Vollmer** [nextcloud/server#41284] opened 2023-11-04 16:22 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Doing an update to 28.0.0 beta 1
I get the followig message

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "ts_session" for table "oc_text_steps" collides with the constraint on table "oc_talk_sessions".
Detaillierte Protokollmeldungen

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "ts_session" for table "oc_text_steps" collides with the constraint on table "oc_talk_sessions".

### Steps to reproduce

1.  Web-Update as Admin
2.
3.

### Expected behavior

the update should complete without an error

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
"system": {
"instanceid": "***REMOVED SENSITIVE VALUE***",
"passwordsalt": "***REMOVED SENSITIVE VALUE***",
"secret": "***REMOVED SENSITIVE VALUE***",
"trusted_domains": [
"nextcloud.vollmer.computer",
"nextcloud.vollmer.homelinux.net",
"nextcloud.vollmer.home"
],
"enable_previews": true,
"datadirectory": "***REMOVED SENSITIVE VALUE***",
"dbtype": "mysql",
"version": "27.1.3.1",
"overwrite.cli.url": "https:\/\/nextcloud.vollmer.computer",
"htaccess.RewriteBase": "\/",
"dbname": "***REMOVED SENSITIVE VALUE***",
"dbhost": "***REMOVED SENSITIVE VALUE***",
"dbport": "",
"dbtableprefix": "oc_",
"mysql.utf8mb4": true,
"dbuser": "***REMOVED SENSITIVE VALUE***",
"dbpassword": "***REMOVED SENSITIVE VALUE***",
"installed": true,
"mail_from_address": "***REMOVED SENSITIVE VALUE***",
"mail_smtpmode": "smtp",
"mail_sendmailmode": "smtp",
"mail_domain": "***REMOVED SENSITIVE VALUE***",
"mail_smtpauthtype": "LOGIN",
"mail_smtphost": "***REMOVED SENSITIVE VALUE***",
"mail_smtpport": "25",
"loglevel": 0,
"log_type": "file",
"log_rotate_size": 104857600,
"maintenance": false,
"memcache.local": "\\OC\\Memcache\\APCu",
"onlyoffice": {
"verify_peer_off": true
},
"theme": "",
"simpleSignUpLink.shown": false,
"app_install_overwrite": [
"calendar",
"keeweb",
"files_readmemd",
"twofactor_email",
"keeporsweep",
"twofactor_rcdevsopenotp",
"whiteboard",
"twofactor_u2f",
"nextbackup",
"polls",
"twofactor_admin",
"richdocuments",
"previewgenerator",
"forms",
"groupfolders",
"files_markdown",
"files_mindmap",
"tasks",
"spreed",
"afterlogic",
"mindmap_app",
"richdocumentscode",
"twofactor_totp",
"pdfdraw",
"customproperties",
"cookbook",
"imageconverter",
"files_videoplayer"
],
"twofactor_enforced": "true",
"twofactor_enforced_groups": [
"u2f"
],
"twofactor_enforced_excluded_groups": [],
"default_language": "de_DE",
"default_locale": "de_DE",
"default_phone_region": "DE",
"force_language": "de_DE",
"skeletondirectory": "",
"updater.release.channel": "beta",
"mail_smtpname": "***REMOVED SENSITIVE VALUE***",
"mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
"updater.secret": "***REMOVED SENSITIVE VALUE***"
}
}
```

### List of activated Apps

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
- activity: 2.19.0
- admin_audit: 1.17.0
- calendar: 4.6.0-beta.1
- circles: 27.0.1
- cloud_federation_api: 1.10.0
- comments: 1.17.0
- contacts: 5.5.0-beta.3
- cookbook: 0.10.2
- dav: 1.27.0
- deck: 1.11.0
- drawio: 2.1.4
- federatedfilesharing: 1.17.0
- federation: 1.17.0
- files: 1.22.0
- files_external: 1.19.0
- files_markdown: 2.4.1
- files_mindmap: 0.0.29
- files_pdfviewer: 2.8.0
- files_reminders: 1.0.0
- files_sharing: 1.19.0
- files_trashbin: 1.17.0
- files_versions: 1.20.0
- firstrunwizard: 2.16.0
- forms: 3.3.1
- groupfolders: 15.3.1
- integration_collaboard: 1.0.6
- keeweb: 0.6.13
- logreader: 2.12.0
- lookup_server_connector: 1.15.0
- mail: 3.5.0-beta.1
- nextcloud_announcements: 1.16.0
- notes: 4.8.1
- notifications: 2.15.0
- oauth2: 1.15.1
- password_policy: 1.17.0
- phonetrack: 0.7.6
- photos: 2.3.0
- polls: 5.4.1
- previewgenerator: 5.3.0
- privacy: 1.11.0
- provisioning_api: 1.17.0
- recommendations: 1.6.0
- related_resources: 1.2.0
- richdocuments: 8.2.2
- richdocumentscode: 23.5.503
- serverinfo: 1.17.0
- settings: 1.9.0
- sharebymail: 1.17.0
- spreed: 17.1.2
- support: 1.10.0
- survey_client: 1.15.0
- suspicious_login: 5.0.0
- systemtags: 1.17.0
- tasks: 0.15.0
- text: 3.8.0
- theming: 2.2.0
- twofactor_admin: 4.3.0
- twofactor_backupcodes: 1.16.0
- twofactor_email: 2.7.3
- twofactor_totp: 9.0.0
- updatenotification: 1.17.0
- user_status: 1.7.0
- viewer: 2.1.0
- weather_status: 1.7.0
- workflowengine: 2.9.0
Disabled:
- afterlogic: 2.0.8 (installed 2.0.8)
- audioplayer: 3.4.0 (installed 3.4.0)
- bruteforcesettings: 2.8.0
- calendar_resource_management: 0.5.0 (installed 0.5.0)
- contactsinteraction: 1.9.0 (installed 1.2.0)
- customproperties: 2.0.4 (installed 2.0.4)
- dashboard: 7.8.0 (installed 7.6.0)
- encryption: 2.16.0
- files_readmemd: 2.0.0 (installed 2.0.0)
- files_videoplayer: 1.14.0
- user_ldap: 1.19.0
```

**Comment by joshtrichards** [comment] 2023-11-04 17:51
Duplicate of #41253

**Closed by joshtrichards** 2023-11-04 17:51 UTC
Labels: bug, 0. Needs triage, 28-feedback
