### ISSUE TITLE
/settings/users context menu unusable in mobile browsers

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#21260] opened 2020-06-05 22:41 UTC
### Steps to reproduce
(0. have multiple users in your nextcloud)
1. in a MOBILE browser navigate to /settings/users
2. click on the three-dot-menu on the right hand side, select "Deactivate user"

### Expected behaviour
In DESKTOP browser, the mouse hover is (slightly) visible in the context menu. When klicked on the menu entry, the user is deactivated.

### Actual behaviour
In MOBILE browser, there is no mouse hover. Tapping the menu entry opens up what was UNDER the menu, the user is NOT deactivated.

### Client configuration
Faulty behaviour (regression) confirmed on Brave(Chrome) and Firefox on Android 10 (all current), and on Safari on iOS 13.5.1.

### Server configuration
NC19.0.0 on NGINX/PHP-FPM on Arch (all current).

**Comment by szaimen** [comment] 2021-06-02 12:24
I can reproduce this on NC21.0.2

---

cc @nextcloud/javascript Maybe there is a simple fix to this?

**Comment by nursoda** [comment] 2021-06-02 14:04
Just re-tested on NC 21.0.2, cannot reproduce this exact workflow issue either. But…

1. in a MOBILE browser (current Brave on Android 10), deactivate a user
2. switch to "Deactivated users" and try to re-"Activate" it – doesn't work for me (just stays as it is, reloading doesn't reflect any change made)

**Comment by nursoda** [comment] 2021-06-02 14:07
![Uploading Screenshot_20210602-160057.jpg…]()

**Comment by lars-sh** [comment] 2022-08-08 23:13
A similar ticket to this one was open in the Impersonate app's issues (see link above).

I just had one more look at this one. To me it seems as if the touch event is fired just a little bit after the popup was closed. Sadly I've really no experience with Vue, which seems to be used to open and hide these popups, but I was able to set up a workaround, which keeps the menu open for 100ms prior hiding it - enough time for the touch event to be fired.

Things work out well if I replace line https://github.com/nextcloud/server/blob/d9e4e48868a3ae207562693cc7505120d31b385a/apps/settings/src/components/UserList/UserRowSimple.vue#L180 with `setTimeout(() => { this.$emit('update:openedMenu', false); }, 100)`.

In a production system you can edit `dist/settings-users-****.js` and replace `hideMenu:function(){this.$emit("update:openedMenu",!1)}` with `hideMenu:function(){setTimeout(()=>{this.$emit("update:openedMenu",!1)},100)}`.

Maybe this helps someone.

**Comment by szaimen** [comment] 2023-01-09 16:33
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Ark74** [comment] 2023-05-11 00:23
Hello guys this issue is still present on 26.0.1
Have tested Firefox and Chrome on Android, none of the options in the Users menu works.

That includes the impersonate button.
Cheers

**Comment by lars-sh** [comment] 2023-05-12 00:46
Since I gave a rough workaround in https://github.com/nextcloud/server/issues/21260#issuecomment-1208712609 already one could expect the problem might be easier to identify and fix.

Is there anything we can do to support on fixing this?

@Ark74, @nursoda, I don't know how Nextcloud issues are prioritized, but maybe it helps to give the initial request a thumbs-up.

**Comment by Columbus240** [comment] 2023-12-03 11:29
I can reproduce this with NextCloud version 27.1.2.

**Comment by eX00r** [comment] 2023-12-09 11:04
Hello guys this issue is still present on 27.0.2
Have tested Firefox and Chrome on Android, none of the options in the Users menu works.

**Comment by nursoda** [comment] 2023-12-09 12:00
I confirm that /settings/users is in large parts unusable on NC 27.1.4 on Firefox/Android 14 (GrapheneOS).

However on **NC28** RC4 on FX/A14 the issue seems to be **resolved**. Not perfectly (I may create a screencast for the devs if that helps), but usable and good enough for me.

**Comment by lars-sh** [comment] 2023-12-16 13:02
I confirm, the issue is fixed with Nextcloud 28 on iPhone as well.

**Closed** 2024-07-29 15:04 UTC
Labels: bug, design, 0. Needs triage, feature: users and groups, 25-feedback
