### ISSUE TITLE
Make navigating on the admin page feel more responsive (either by faster page loads or by SPA)

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#953] opened 2016-08-18 21:57 UTC
The new **admin page split** (#796) reloads the whole page if you click on another element at the sidebar, which looks quit strange 😁 

cc @nextcloud/designers @blizzz

**Comment by LukasReschke** [comment] 2016-08-18 22:03
That's not a bug but a new feature ;)

**Comment by mar1u5** [comment] 2016-08-18 22:04
Well... Then we should move to Nextcloud 11, right 😁

**Comment by LukasReschke** [comment] 2016-08-18 22:09
Yep. See also https://github.com/nextcloud/server/pull/796#issuecomment-240068532 for why this wasn't done. This requires quite a bit of work :)

**Comment by jancborchardt** [comment] 2016-08-25 08:37
Putting to high priority and assigning @blizzz since this is a UX regression. :\ cc @karlitschek in the future we should really not do last minute stuff like this, it always has unexpected impact.

**Comment by skjnldsv** [comment] 2017-09-28 17:01
Is this still an issue? :)

**Comment by MorrisJobke** [comment] 2017-09-28 20:10
> Is this still an issue? :)

Yes, but I don't see an easy way to solve this and I also think that it is not that critical at all.

**Comment by skjnldsv** [comment] 2017-09-28 20:26
My opinion as well!

**Comment by skjnldsv** [comment] 2018-02-25 10:58
We should decide on this. Do we really need to implement a js Ajax request to only not reload everything? I'm not sure it's such a great idea. Especially on mobile where the browser can't state where the request is currently in xhr requests but handle a full reload natively and displays a nice loading progress bar.

**Comment by jancborchardt** [comment] 2018-02-25 13:11
So the issue here is that before it was actually better, as we loaded everything and just moved between sections. While putting together, the performance regressed to full refresh.

**Comment by skjnldsv** [comment] 2018-02-25 14:58
To my view:
pros:
 - Performances
cons:
 - usability
 - lack of feedback (a spinning loader show very little of what's really going on)
 - heavy on the client side (especially mobiles)

**Comment by MorrisJobke** [comment] 2018-02-26 09:10
> So the issue here is that before it was actually better, as we loaded everything and just moved between sections. While putting together, the performance regressed to full refresh.

I still don't see this point here. So do we really want to reimplement the whole server side another time on client side? This just makes so little sense and a page load should not take ages. if it does we should look into why it takes so long. Just dumping everything in a SPA (single page application) just to make it fast has an enormous drawback: maintenance. We are currently not in a position where we easily can handle to implement everything in PHP and JS just because we want to have no page reload (making pages load fast also feels like "no page reload" and usually all assets are already loaded like the styles and only the pure content is fetched).

I vote for closing this and focus on making Nextcloud faster on the PHP side (if this really is a problem).

**Comment by jancborchardt** [comment] 2018-02-26 09:40
> a page load should not take ages. if it does we should look into why it takes so long.

Sure, let's improve that. However a big factor here is actually network connection of users, and we shouldn't assume everyone has the perfectly good wi-fi most of us work with.

**Comment by MorrisJobke** [comment] 2018-02-26 10:51
> Sure, let's improve that. However a big factor here is actually network connection of users, and we shouldn't assume everyone has the perfectly good wi-fi most of us work with.

But this is like optimising at the wrong end. Because then we should focus on improving the files app for example for failing network connection and stuff like that that is used on a daily basis (comments comes to my mind) instead of putting a lot of effort (because doing the JS stuff on a single page instead of many small pages, could also cause some headaches, and did reveal some weird issues in the past) into the admin pages.

**Comment by jancborchardt** [comment] 2018-02-26 16:54
Ok well, but this is about the settings, not files. ;) Sure it’s not as important comparatively. But the point is: Switching settings is slow, and it used to be quicker. I’m not expecting us to fix it very quickly or so, but let’s keep it open?

**Comment by szaimen** [comment] 2021-05-21 10:23
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Closed by szaimen** 2021-05-21 10:23 UTC
Labels: 1. to develop, enhancement
