### ISSUE TITLE
Apps icon are missing

### ISSUE THREAD

**Issue by biva** [nextcloud/server#4784] opened 2017-05-10 08:14 UTC
### Steps to reproduce
1. Open Nextcloud Web UI
2. Look at the Apps bar

### Expected behaviour
Icons are present

### Actual behaviour
No icons are present. 

![image](https://cloud.githubusercontent.com/assets/9964305/25888460/8e68b290-3566-11e7-8a0a-2c499954585e.png)

The icons were present before I put in place memory caching (following instructions here: https://docs.nextcloud.com/server/11/admin_manual/configuration_server/caching_configuration.html): APCu and Redis

May be related to https://github.com/nextcloud/server/issues/2632

### Browser Inspection on Contact Icon

<code>
a href="/index.php/apps/contacts/" tabindex="3">

svg width="32" height="32" viewBox="0 0 32 32">

defs><filter id="invert">

feColorMatrix in="SourceGraphic" type="matrix" values="-1 0 0 0 1 0 -1 0 0 1 0 0 -1 0 1 0 0 0 1 0"></feColorMatrix>

/filter>

/defs>

image x="0" y="0" width="32" height="32" preserveAspectRatio="xMinYMin meet" filter="url(#invert)" xlink:href="/nextcloud/apps/contacts/img/app.svg?v=c04fa91f8b347202dd2bbff6f0d6844f" class="app-icon">

/image>

/svg>

div class="icon-loading-dark" style="display:none;"></div>

span>

Contacts</span>

</code>

### Client configuration

Browser: Firefox on WIndows 10

### Server configuration
Ubuntu 16.04.2 LTS
Server version: Apache/2.4.18 (Ubuntu)
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
Nextcloud version 11.0.3.2

**Updated from an older Nextcloud/ownCloud : yes

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.```
</details>


**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.4
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.2.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - spreedme: 0.3.8
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - announcementcenter
  - audioplayer
  - direct_menu
  - documents
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_reader
  - mail
  - nextant
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

```
</details>

**Comment by biva** [comment] 2017-05-10 08:24
My config file:

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
          "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2,
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}

**Comment by biva** [comment] 2017-05-10 08:32
Posting my config.php makes me realize that puting in place Redis deleted the APCu config line (<code>'memcache.local' => '\OC\Memcache\APCu'</code>). Configuring this line again, and commenting out the lines regarding Redis gave me the apps icon back. I'll remain like that for now, 

I may have misunderstood the documentation, regarding this sentence: "You may use both a local and a distributed cache. Recommended caches are APCu and Redis." As APCu is described above as a "local cache" and Redis "for distributed caching", I thought I shoud use both. Apparently not. Or was there a misconfiguration of Redis?

**Comment by MorrisJobke** [comment] 2017-05-10 20:06
cc @juliushaertl @skjnldsv @rullzer This looks like cached paths for those icons.

**Comment by juliushaertl** [comment] 2017-05-11 12:48
@MorrisJobke Yes, looks like a caching issue. But I'm not too familiar with the caching code. Works fine here on a setup with Redis as local memcache.

**Comment by MorrisJobke** [comment] 2017-05-11 15:48
> I may have misunderstood the documentation, regarding this sentence: "You may use both a local and a distributed cache. Recommended caches are APCu and Redis." As APCu is described above as a "local cache" and Redis "for distributed caching", I thought I shoud use both. Apparently not. Or was there a misconfiguration of Redis?

You could do it like that. I personally only use redis (both as local and distributed cache configured). I reminded that there was an issue in 11 and I thought we fixed in in 11.0.3, but you say, that you already run this. 😕 

But you can't reproduce this anymore, right? I guess then it's super hard to fix it, because it works here in multiple instances with Redis as cache without any problem.

**Comment by MorrisJobke** [comment] 2017-05-12 17:16
> "memcache.local": "\OC\Memcache\Redis") or should I replace "\OC" by my specific nextcloud path ("\var\www\html\nextcloud")?

No ... this is a PHP namespace. It needs to be \OC.

**Comment by MorrisJobke** [comment] 2017-05-12 17:17
Let's close this here then and see if this can be reproduced in the future

**Closed by MorrisJobke** 2017-05-12 17:17 UTC
Labels: bug, design, feature: theming
