### ISSUE TITLE
Odd behaviour when creating private event in shared calendar

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#13703] opened 2019-01-20 21:48 UTC
Events which can only be displayed in the source calendar can be created in a shared version of this calendar with "private" visibility setting without warning and therefore go missing in the shared copy.

**Steps to reproduce**
1) Create a calendar as user a
2) Share this calendar to user b with write privileges
3) Connect to this calendar as user b via caldav (e.g thunderbird lightning, android davx<sup>5</sup> and aCalendar or even nextcloud calendar app)
4) Create a new event with visibility "private" as user b
5) Appointment doesn't seem to be created or is visible for a moment and then vanishes
6) Open the calendar of user a
7) Find the new appointment here

Although I understand the logic behind this, I don't think it should be this way. Took me quite a while to find out what's happening and why the appointments created on my mobile and thunderbird were vanishing without notice (with standard visibility setting "private")

**Possible solutions**
Not sure what a good solution would look like.
1) What about adding an additional sharing option like "can see private events" or "full access"?
2) Do not create event and return a distinct error code? (Maybe not possible at all via CalDAV protocol as I do not know it)
3) Display a hint in a kind of first run wizard for calendar app?

**Comment by georgehrke** [comment] 2019-09-11 08:18
Duplicate of https://github.com/nextcloud/server/issues/5551

**Closed by georgehrke** 2019-09-11 08:18 UTC
Labels: 0. Needs triage, enhancement, feature: dav
