### ISSUE TITLE
'Your storage is almost full' blocks access to menuitems

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#26518] opened 2021-04-12 12:06 UTC
This particular notification is on top of everything, and it blocks access to the settings menu. It's z-index should be lower, i found
`z-index: 1900;` working rather well.

![grafik](https://user-images.githubusercontent.com/25279821/114391790-37e4ae00-9b98-11eb-922c-3e5a557bc5bd.png)

Edit: it seems the developer made a typo. The current z-index is 10100, but with 1100 the issue disappears.

**Comment by acsfer** [comment] 2021-04-12 12:28
cc @nextcloud/designers

**Comment by szaimen** [comment] 2021-07-02 12:53
Hi @newhinton do you mind creating a PR with a patch for discussion?
Thank you!

**Comment by juliushaertl** [comment] 2021-07-02 15:52
We probably should start adding css variables for those kind of z-indexes so that we can easily check for conflicting/overlapping by the code already. Anyways a pull request would indeed be very welcome.

**Comment by bes1002t** [comment] 2021-09-01 11:49
I think the message that important messages should be shown above all other elements. A "storage is nearly full" notification is very important. But we should show this message just once at a time, imho.

**Comment by newhinton** [comment] 2021-09-03 10:25
@bes1002t This message is important, true, but not enough to warrant blocking access to the underlying menu. It completely removes access to the settings. That is not a good idea, especially since the storage-quota is rather prominently displayed on the bottom left

**Comment by szaimen** [comment] 2021-09-03 10:54
See the discussion in https://github.com/nextcloud/nextcloud-dialogs/pull/423

**Comment by newhinton** [comment] 2022-10-02 20:03
Just a heads up because i tested this, this is still an issue with nextcloud 25 ;)

**Comment by szaimen** [comment] 2023-01-23 11:04
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by newhinton** [comment] 2023-01-23 12:10
This is still an issue with 25.0.3.

**Comment by newhinton** [comment] 2023-01-23 12:33
Additional info:

The z-index of toastify.dialogs is set to 10100 as stated by my browser. Setting this to 1100 works.

The same z-index in core/css/toast.css is set to 9000 (which is also to high for the menu)

I have not been able to find the 10100-value. If anyone could help me out, i can prepare a PR.

**Comment by szaimen** [comment] 2023-01-23 12:35
See the discussion in https://github.com/nextcloud/nextcloud-dialogs/pull/423

**Comment by newhinton** [comment] 2023-01-23 12:36
Yes i just read it and wanted to make an edit. So it will have to stay open anyway.

**Comment by skjnldsv** [comment] 2023-10-20 17:23
Duplicate of https://github.com/nextcloud/server/issues/25293

**Closed by skjnldsv** 2023-10-20 17:23 UTC
Labels: bug, design, 0. Needs triage, feature: files, feature: activity and notification, 25-feedback
