### ISSUE TITLE
Cronjob didn’t work

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#19032] opened 2020-01-21 06:04 UTC
Hello,

I made an manual update from NC 17 > 18. After that I see that the Cronjob didn’t work.
I checked the Crontab file and run this command manually, but no changes. 

### Steps to reproduce
1. Open Nextcloud and go the System information. 
2. Run manually php -f /path/to/cloud/cron.php
3. Look at the sys information at the cloud.

### Expected behaviour
The cron runs every 15 Minutes 

### Actual behaviour
No cron since the Update

### Server configuration
All needed Information here:
Link: https://cloud.larsmueller.net/s/J2q4MgLLm32iMbD
Passwort: OlsQRPoJr/7Ld5A2dUQa

Nextcloud Log:

```

Errorcron2020-01-21T07:01:54+0100
Error: Call to a member function getUserFolder() on null
/var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 79:
OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({ fileId: 25 ... "})
/var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php - line 48:
OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
/var/www/nextcloud/cron.php - line 125:
OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

**Comment by Happyfeet01** [comment] 2020-01-21 06:07
Maybe an error from Maps? https://github.com/nextcloud/maps/issues/247#issue-551877518

**Comment by e-alfred** [comment] 2020-01-23 14:57
Can confirm, this seems to be a problem with the Maps app.

**Comment by aproposnix** [comment] 2020-02-01 20:04
### Steps to reproduce
* Make sure cron job is activated and working 
* Install the map app from the store
* Let it run for a while 
* Check your cron job settings and you'll see an error telling you that cron hasn't run in X amount of time 

To fix the situation, just disable maps. Eventually it starts working again. 



### Expected behaviour
Cron jobs should not crash and continues working. 
I should not see error messages like this in my error log: 

[cron] Error: Error: Call to a member function getUserFolder() on null at <<closure>>

0. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 79
   OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({fileId: 2130,userId: "rimez"})
1. /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php line 48
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
2. /var/www/nextcloud/cron.php line 125
   OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-02-01T18:30:02+00:00

### Actual behaviour
In the settings (Admin>Basic Settings) the cron status will throw an error (red icon plus message) eventually. 


## Server configuration detail

**Operating system:** Linux 5.4.0-12-generic #15-Ubuntu SMP Tue Jan 21 15:12:29 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.3.11-0ubuntu2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 18.0.0 - 18.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Manual from Git releases

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - apporder: 0.9.0
 - audioplayer: 2.9.0
 - bookmarks: 2.3.4
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - drawio: 0.9.4
 - event_update_notification: 1.0.1
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_markdown: 2.2.0
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.4
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.6
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - phonetrack: 0.6.1
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - rainloop: 6.0.6
 - ransomware_protection: 1.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.1
 - survey_client: 1.6.0
 - suspicious_login: 3.0.1
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - breezedark
 - encryption
 - files_external
 - firstrunwizard
 - gpxpod
 - recommendations
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "aproposnix.dlinkddns.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.0.10",
    "overwrite.cli.url": "https:\/\/aproposnix.dlinkddns.com\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "app_install_overwrite": [
        "occweb",
        "drawio"
    ],
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls"
}
```
</details>

**Are you using external storage, if yes which one:** N/A

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** N/A

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0

**Operating system:** Ubuntu 20.04 Development

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
Error	cron	Error: Call to a member function getUserFolder() on null

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 79:

    OCA\Maps\BackgroundJob\UpdatePhotoByFileJob->run({ fileId: 1884,userId: "rimez"})

    /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php - line 48:

    OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

    /var/www/nextcloud/cron.php - line 125:

    OCP\BackgroundJob\QueuedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

	
an hour ago
Error	PHP	Undefined property: OCA\Maps\BackgroundJob\UpdatePhotoByFileJob::$root at /var/www/nextcloud/apps/maps/lib/BackgroundJob/UpdatePhotoByFileJob.php#43	
an hour ago
```
</details>

<details><summary>Browser log</summary>


</details>

**Comment by kesselb** [comment] 2020-02-01 20:32
Thanks for reporting everyone :+1: 

Closed as duplicate of https://github.com/nextcloud/maps/issues/247

**Closed by kesselb** 2020-02-01 20:32 UTC
Labels: 0. Needs triage, bug
