### ISSUE TITLE
Scanning of 'broken' symlink stops scanning abruptly

### ISSUE THREAD

**Issue by Airell** [nextcloud/server#22270] opened 2020-08-17 11:52 UTC
### Steps to reproduce
1. Have a working symlink on an external file-server
2. Mount the 'higher' location with a 'lower' symlink of the file-server onto the nextcloud-server, but the original file to where the symlink pints is 'outside' this path
3. On the nextcloud-server the 'seemingly local' symlink is broken (as expected, this is not the issue that is should) `lrwxr-x--- 1 backuprw backup       14 Jan 15  2019 dupes.sh -> /home/backuprw/dupes.sh` (this symlink on the file-server works).
4. Scanning with `nextcloud.occ files:scan --all` results in a 'Exception during scan: Undefined index: permissions' when scanning the `dupes.sh` file and the scanning breaks.

### Expected behaviour
An (unhandled) exception like this should not stop a running scan. Report the issue (warning) and continue scanning.

### Actual behaviour
Scanning with `nextcloud.occ files:scan --all` results in a 'Exception during scan: Undefined index: permissions' when scanning the `dupes.sh` file and the scanning breaks.

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
Apache HTTP server

**Database:**
MySQL 5.7.31

**PHP version:**
7.3.21

**Nextcloud version:** (see Nextcloud admin page)
19.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
No

**Where did you install Nextcloud from:**
Snap package, 19.0.1snap3

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - drawio: 0.9.7
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_texteditor: 2.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - twofactor_backupcodes: 1.8.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - text
  - theming
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            " ... ",
            " ... "
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "http:\/\/ ... ",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwriteprotocol": "https",
        "maintenance": false,
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:**
No... I'm using a locally mounted FS (nfs), but for NC is a local file system

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Exception during scan: Undefined index: permissions
#0 /snap/nextcloud/22653/htdocs/lib/private/Files/Storage/Wrapper/PermissionsMask.php(160): OCA\Files\Command\Scan->exceptionErrorHandler(8, 'Undefined index...', '/snap/nextcloud...', 160, Array)
#1 [internal function]: OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent('studio48/Upload...')
#2 /snap/nextcloud/22653/htdocs/lib/private/Files/Cache/Scanner.php(408): iterator_to_array(Object(Generator))
#3 /snap/nextcloud/22653/htdocs/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('studio48/Upload...', true, 3, 321908, true, 0)
#4 /snap/nextcloud/22653/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('studio48/Upload...', true, 3, 321908, true)
#5 /snap/nextcloud/22653/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('studio48/Upload...', true, 3, 301510, true)
#6 /snap/nextcloud/22653/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('studio48/Upload', true, 3, 301500, true)
#7 /snap/nextcloud/22653/htdocs/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren('studio48', true, 3, 301493, true)
#8 /snap/nextcloud/22653/htdocs/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren('', true, 3, 200, true)
#9 /snap/nextcloud/22653/htdocs/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan('', true, 3)
#10 /snap/nextcloud/22653/htdocs/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan('/airell', true, NULL)
#11 /snap/nextcloud/22653/htdocs/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles('airell', '/airell', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#12 /snap/nextcloud/22653/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /snap/nextcloud/22653/htdocs/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /snap/nextcloud/22653/htdocs/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /snap/nextcloud/22653/htdocs/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /snap/nextcloud/22653/htdocs/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /snap/nextcloud/22653/htdocs/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /snap/nextcloud/22653/htdocs/console.php(100): OC\Console\Application->run()
#19 /snap/nextcloud/22653/htdocs/occ(11): require_once('/snap/nextcloud...')
#20 {main}
```
</details>

**Comment by therealbstern** [comment] 2021-05-29 21:13
This is a problem in 19.0.12 as well.

**Comment by szaimen** [comment] 2021-06-18 13:46
Duplicate of https://github.com/nextcloud/server/issues/22040

**Closed by szaimen** 2021-06-18 13:46 UTC
Labels: 0. Needs triage, bug
