### ISSUE TITLE
PHP Logging Error v13.0.6

### ISSUE THREAD

**Issue by aljawaid** [nextcloud/server#11424] opened 2018-09-27 20:50 UTC
### Steps to reproduce
1.  `Settings` > `Logging`

### Expected behaviour
No error

### Actual behaviour
Error as below:

| Level | App | Message | Time |
|-------|-----|------------------------------------------------------------------------------------|--------------------------|
| Error | PHP | `Undefined index: SCRIPT_FILENAME at /home/xxxxx/public_html/cloud/lib/base.php#144` | 2018-09-27T21:30:02+0100 |

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MySQL 5.5.60

**PHP version:** 7.0.32

**Nextcloud version:** 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since v9 originally I think, about a year back.

**Where did you install Nextcloud from:**  Nextcloud website

-----

I also tried changing the cron to `php-cli` in cPanel as suggested here https://github.com/nextcloud/server/issues/285#issuecomment-320952780 but it the cron kept failing after that.

**Comment by skjnldsv** [comment] 2020-04-10 07:16
As I cannot reproduce the original issue anymore and as the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen

**Closed by skjnldsv** 2020-04-10 07:16 UTC
Labels: 0. Needs triage, bug
