### ISSUE TITLE
activating maintenance mode cripples config.php

### ISSUE THREAD

**Issue by gbi39** [nextcloud/server#13068] opened 2018-12-14 09:09 UTC
Hi all,

I'm running a small, private nextcloud on a Raspi 2B, under a LEMP stack. I have configured APCu as local PHP cache. I'm doing regularly backups with a script inspired by the one in the nextcloud docs. Before doing the backup of Maria-DB a

sudo -u www-data php occ maintenance:mode --on

is done, when the backup of the DB is done a 

sudo -u www-data php occ maintenance:mode --off

Right after maintenance mode is switched on my config.php is crippled in the following way:

  'memcache.local' => '\\OC\\Memcache\\APCu',

which in turn leads to performance degradation and the following errors in nextcloud.log:

{"reqId":"5hPVLc9dMOtkffPRVRXq","level":1,"time":"2018-12-14T08:30:02+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"14.0.4.2"}

Switching off maintenace-mode after the backup does not "repair" the crippled statement.

I have configured "apc.enable_cli=1" in "/etc/php/7.0/mods-available/apcu". According to phpinfo() and apc.php APCu normally works.

If you need further infos doe not hesitate to contact me.

Thanks in advance

**Comment by kesselb** [comment] 2019-05-18 22:17
Did this error occur again?

**Comment by gbi39** [comment] 2019-05-19 07:18
At the moment I'm running 15.0.7

I did the following test: switching maintenance mode on/off

Before switching on:

`  'memcache.local' => '\OC\Memcache\APCu',`

I havn't manually touched the memcache.local statement since the update to 15.0.7, which I did maybe ~3 weeks ago.

After switching on:
`  'memcache.local' => '\\OC\\Memcache\\APCu',`

After switching off:
`  'memcache.local' => '\\OC\\Memcache\\APCu',`

The last 8 lines in the data/nextcloud.log are
`{"reqId":"PEEp6L5VUdWei7uczfrj","level":1,"time":"2019-04-16T18:29:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"14.0.7.1"}
{"reqId":"763binetpIx0yNe95ZIG","level":1,"time":"2019-04-16T18:30:02+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"14.0.7.1"}
{"reqId":"763binetpIx0yNe95ZIG","level":1,"time":"2019-04-16T18:30:02+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"14.0.7.1"}
{"reqId":"763binetpIx0yNe95ZIG","level":0,"time":"2019-04-16T18:30:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Update required, skipping cron","userAgent":"--","version":"14.0.7.1"}
{"reqId":"PEEp6L5VUdWei7uczfrj","level":1,"time":"2019-04-16T18:30:03+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"14.0.7.1"}
{"reqId":"PEEp6L5VUdWei7uczfrj","level":1,"time":"2019-04-16T18:30:03+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"15.0.7.0"}
{"reqId":"PEEp6L5VUdWei7uczfrj","level":1,"time":"2019-04-16T18:30:03+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"15.0.7.0"}
{"reqId":"PEEp6L5VUdWei7uczfrj","level":1,"time":"2019-04-16T18:30:03+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Fatal(4)","userAgent":"--","version":"15.0.7.0"}
`
So there are still "Memcache not available" lines in the log, but maybe this has to do with my on/off switching.
And there still seems to be code that alters the memcache.local line.

But in general it works better then at 14 Dec when I opened the issue

**Comment by skjnldsv** [comment] 2019-06-14 05:50
It's actually not supposed to be an issue.
Escaping the backslash is working fine on my setup: 

``` php
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
```

As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-14 05:50 UTC
Labels: 0. Needs triage, 14-feedback, bug
