### ISSUE TITLE
Errors logged in CalDAV provider

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/server#8341] opened 2018-02-13 22:12 UTC
### Steps to reproduce
1. Opening the calendar in the browser.
2. Sometimes (but not always) an error is logged, even though the calendar is always display correct.

### Expected behaviour

No errors occur in the log.

### Actual behaviour

The following errors are logged on the server:

```
Undefined offset: 1 at /var/www/clients/client1/web28/web/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php#232
Undefined offset: 0 at /var/www/clients/client1/web28/web/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php#231
Undefined offset: 1 at /var/www/clients/client1/web28/web/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php#232
Undefined offset: 0 at /var/www/clients/client1/web28/web/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php#231
```

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12.0.5

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - apporder: 0.4.1
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - deck: 0.3.0
  - defaultlinkopen: 1.0.0
  - external: 3.0.2
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 1.12.40
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - spreed: 3.0.1
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.0x0c.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.0x0c.de",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "knowledgebaseenabled": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Firefox 58.0.2 (x86-64)

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
xxx.xxx.xxx.xxx - - [13/Feb/2018:19:19:16 +0100] "GET /status.php HTTP/1.1" 200 4906 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
xxx.xxx.xxx.xxx - - [13/Feb/2018:19:19:16 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1246 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
xxx.xxx.xxx.xxx - - [13/Feb/2018:19:19:16 +0100] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 2384 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
xxx.xxx.xxx.xxx - - [13/Feb/2018:19:19:16 +0100] "GET /ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 1079 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
xxx.xxx.xxx.xxx - - [13/Feb/2018:19:19:16 +0100] "GET /ocs/v1.php/cloud/activity?page=0&pagesize=100&format=json HTTP/1.1" 200 3575 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
xxx.xxx.xxx.xxx - - [13/Feb/2018:19:19:16 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 948 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
xxx.xxx.xxx.xxx - - [13/Feb/2018:19:19:16 +0100] "PROPFIND /remote.php/dav/files/awelzel/ HTTP/1.1" 207 4880 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"PBG66EnNnQnsZs2gcrrV","level":3,"time":"2018-02-13T18:19:16+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxx","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/activity?page=0&pagesize=100&format=json","message":"Undefined offset: 0 at \/var\/www\/clients\/client1\/web28\/web\/apps\/dav\/lib\/CalDAV\/Activity\/Provider\/Calendar.php#231","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"PBG66EnNnQnsZs2gcrrV","level":3,"time":"2018-02-13T18:19:16+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxx","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/activity?page=0&pagesize=100&format=json","message":"Undefined offset: 1 at \/var\/www\/clients\/client1\/web28\/web\/apps\/dav\/lib\/CalDAV\/Activity\/Provider\/Calendar.php#232","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"PBG66EnNnQnsZs2gcrrV","level":3,"time":"2018-02-13T18:19:16+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxx","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/activity?page=0&pagesize=100&format=json","message":"Undefined offset: 0 at \/var\/www\/clients\/client1\/web28\/web\/apps\/dav\/lib\/CalDAV\/Activity\/Provider\/Calendar.php#231","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
{"reqId":"PBG66EnNnQnsZs2gcrrV","level":3,"time":"2018-02-13T18:19:16+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxx","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/activity?page=0&pagesize=100&format=json","message":"Undefined offset: 1 at \/var\/www\/clients\/client1\/web28\/web\/apps\/dav\/lib\/CalDAV\/Activity\/Provider\/Calendar.php#232","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}
```
</details>

**Comment by P-atrick-B** [comment] 2018-02-16 09:14
I can confirm this.

Server configuration
Operating system: Debian 9.3
Web server: Nginx 1.10.3
Database: MariaDB
PHP version: 7.0
Nextcloud version: 13.0.0
Updated from an older Nextcloud/ownCloud or fresh install: Fresh install
Where did you install Nextcloud from: nextcloud.com

**Comment by Fixel2012** [comment] 2018-04-26 08:27
I have currently the same problem with nextcloud 13 (up to date).

Is there already a fix for it?

**Comment by MoonshineSG** [comment] 2018-05-06 04:15
13.0.2 has the same problem on certain .ics files. Some work, some don't....

**Comment by albirs** [comment] 2018-05-10 13:29
+1 
I have currently the same problem with nextcloud 13.0.2

**Comment by MoonshineSG** [comment] 2018-05-20 07:53
Any of the developers read these messages? Some sort of reply or acknowledgement would be appreciated

**Comment by livier** [comment] 2018-05-21 13:33
+1

**Comment by zax-29** [comment] 2018-06-06 04:50
+1

**Comment by serbik** [comment] 2018-06-13 19:59
Also getting this on NC 13.0.2 , Calendar 1.6.1

Seems to log it it about 100x every 15 minutes (likely crown inducing it)

**Comment by MorrisJobke** [comment] 2018-07-03 09:45
@georgehrke @nickvergessen @rullzer Could you have a look at this?

**Comment by georgehrke** [comment] 2018-07-03 09:52
@nickvergessen Is `getSubjectParameters()` ever supposed to return an empty array? 

https://github.com/nextcloud/server/blob/v13.0.0/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php#L166
https://github.com/nextcloud/server/blob/v13.0.0/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php#L232

**Comment by nickvergessen** [comment] 2018-07-03 10:29
Ah, no that should be older.
But the array should never be empty.

Can you tell me the subject of the activity when this happens?
Add the following code before 218:
https://github.com/nextcloud/server/blob/v13.0.0/apps/dav/lib/CalDAV/Activity/Provider/Calendar.php#L218

```php
		if (empty($parameters[0])) {
			\OC::$server->getLogger()->error('$parameter is empty' . $event->getSubject());
		}
```

**Comment by kesselb** [comment] 2019-08-17 15:54
@arnowelzel @serbik @MoonshineSG @Fixel2012 @derpingit :ping_pong:

**Comment by arnowelzel** [comment] 2019-08-17 16:16
Sorry, I don't know, how to provide any further information. When I first noticed that I have just seen the log message but I could not reproduce it with any specific actions. At the moment with NC 16.0.3 it seems not to happen any longer. But meanwhile I also updated the CardDAV clients (Android DAVx5, Thundebird Cardbook) and I think my users did as well.

**Comment by kesselb** [comment] 2019-08-17 16:48
Thanks for your feedback. Perhaps someone else has more luck ;)

**Comment by georgehrke** [comment] 2019-09-14 14:17
Closing since original reporter could not reproduce the issue anymore and no one else spoke up to the questions.

**Closed by georgehrke** 2019-09-14 14:17 UTC
Labels: 0. Needs triage, bug, feature: activity and notification, feature: dav, needs info
