### ISSUE TITLE
Notification update for applications : add a link

### ISSUE THREAD

**Issue by spfmoby** [nextcloud/server#32896] opened 2022-06-16 07:34 UTC
Very simple addition: 

If we click on the notification bell in the web app and see that there are application updates, there is no link to go to the profile button, then the application page.

Adding a simple link could be useful and easy to implement. This behavior is already done when there is a nextcloud core update.

**Comment by ogasser** [comment] 2022-09-19 17:39
Duplicate of https://github.com/nextcloud/server/issues/30836 - let's continue there.

**Closed by ogasser** 2022-09-19 17:39 UTC
Labels: enhancement, 0. Needs triage
