### ISSUE TITLE
Make file dialog remember last location

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#20797] opened 2020-05-03 19:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When writing a blog and inserting a bunch of images, you'll often be navigating to a sub-sub-sub-sub folder multiple times... And sadly, this is quite slow. It would be quite amazing if this was not needed and the insert image file browser would just remember the last folder you were in. Of course, making it faster in the first place would also be helpful, but let's stick with one issue at a time 😎

**Describe the solution you'd like**
Remember the last visited folder.

**Describe alternatives you've considered**
* Make it faster (helps but doesn't solve it completely)
* Have a sidebar with favorites etc (should be done, but probably a lot more work and STILL doesn't solve the same problem)

**Comment by szaimen** [comment] 2021-05-31 14:46
Duplicate of https://github.com/nextcloud/server/issues/644

**Closed by szaimen** 2021-05-31 14:46 UTC
Labels: 0. Needs triage, enhancement
