### ISSUE TITLE
Shared folder link: Video files not showing immediately.

### ISSUE THREAD

**Issue by dennorske** [nextcloud/server#17664] opened 2019-10-24 09:06 UTC
### Steps to reproduce
1. Share a folder with .JPG and .MP4 as a link.
2. Enter link with a web-browser on a desktop. Reload the page until you see the mp4 files, or try to change from list-view to grid view, and then back again.

### Expected behaviour
Both types should show up immediately.

### Actual behaviour
I only see pictures at first load, and sometimes i see both. I can't find any consistent reproduction rate of it. I had several users reporting that they only saw pictures at first and wondered if i had shared the wrong link to them. I have about 17 videos in mp4 format totalling 28 gb in size, and 25 pictures.

### Server configuration

**Operating system**: 4.15.0-65-generic #74-Ubuntu 18.04

**Web server:** Apache/2.4.41 (Ubuntu)

**Database:** Mysql

**PHP version:** 7.3.10-1

**Nextcloud version:** 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded

**Where did you install Nextcloud from:** Official web directory download

**Signing status:**
<details>
<summary>Signing status</summary>
`No errors found.`
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - announcementcenter: 3.6.0
  - audioplayer: 2.8.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - deck: 0.7.0
  - external: 3.4.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_readmemd: 1.1.1
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trackdownloads: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocsms: 2.1.3
  - password_policy: 1.7.0
  - previewgenerator: 2.1.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - ransomware_protection: 1.5.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - socialsharing_email: 1.0.5
  - spreed: 7.0.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - suspicious_login: 2.3.0
  - systemtags: 1.7.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_nextcloud_notification: 2.1.1
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - afterlogic
  - encryption
  - mail
  - music
  - onlyoffice
  - rainloop
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ducky.rocks"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "CF-Connecting-IP",
            "HTTP_CF_CONNECTING_IP",
            "x-forwarded-for"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "overwrite.cli.url": "https:\/\/ducky.rocks",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstoreurl": "https:\/\/apps.nextcloud.com",
        "filesystem_check_changes": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "files_trackdownloads",
            "spreed",
            "afterlogic",
            "camerarawpreviews",
            "ocsms",
            "files_readmemd",
            "socialsharing_email"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** yes, several

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome 77.0.3865.90 and Chrome 77.0.3865.116 (mobile)

**Operating system:** Mac OS, Linux, Android

#### Browser log
<details>
<summary>Browser log</summary>

```
No logs
```
</details>

**Comment by szaimen** [comment] 2021-06-07 17:08
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-07 17:08 UTC
Labels: 0. Needs triage, bug
