### ISSUE TITLE
upgrade to 16.0.1 InvalidArgumentException: The given user id is invalid

### ISSUE THREAD

**Issue by gbelmm** [nextcloud/server#15607] opened 2019-05-17 19:38 UTC
#### Browser log
<details>
{"reqId":"Ob4AKiQC85boSY6ZY3RN","level":3,"time":"2019-05-17T15:48:58+00:00","remoteAddr":"192.168.0.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=EI1sPeyFpNJmPVvJmjvBn%2FiwlnaTRDFcAHvpGrGJzh0%3D%3ASt5fW6b3lLYISy%2BA0gqu5Y6B3E%2FDFlx3dCiNKPvN9zY%3D","message":"\\OC\\Updater::failure: InvalidArgumentException: The given user id is invalid","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"Ob4AKiQC85boSY6ZY3RN","level":3,"time":"2019-05-17T15:48:58+00:00","remoteAddr":"192.168.0.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=EI1sPeyFpNJmPVvJmjvBn%2FiwlnaTRDFcAHvpGrGJzh0%3D%3ASt5fW6b3lLYISy%2BA0gqu5Y6B3E%2FDFlx3dCiNKPvN9zY%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.7.0"}
{"reqId":"Ob4AKiQC85boSY6ZY3RN","level":1,"time":"2019-05-17T15:48:58+00:00","remoteAddr":"192.168.0.1","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=EI1sPeyFpNJmPVvJmjvBn%2FiwlnaTRDFcAHvpGrGJzh0%3D%3ASt5fW6b3lLYISy%2BA0gqu5Y6B3E%2FDFlx3dCiNKPvN9zY%3D","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.7.0"}
</details>

**Comment by propositionjoe** [comment] 2019-05-19 05:28
Same problem here.

**Comment by papenpa** [comment] 2019-05-21 20:32
Same problem here.

**Comment by karl-in-office** [comment] 2019-06-07 08:02
It might be same with #15677

**Comment by omysurya** [comment] 2019-06-09 07:00
same with me

**Comment by propositionjoe** [comment] 2019-06-10 04:59
> It might be same with #15677

That's true, the solution is here: https://github.com/nextcloud/server/issues/15677#issuecomment-500032350
I'm editing the file: lib/private/Notification/Notification.php
- suppr this line: if (!is_string($user) || $user === '' || isset($user[64])) {
- add this line: if ($user === '' || isset($user[64])) {

**Comment by kesselb** [comment] 2019-06-10 10:43
Duplicate of #15677

**Closed by kesselb** 2019-06-10 10:43 UTC
Labels: 0. Needs triage, bug
