### ISSUE TITLE
NextCloud 13 folder/file display bug

### ISSUE THREAD

**Issue by mlarchet** [nextcloud/server#8467] opened 2018-02-21 08:36 UTC
### Steps to reproduce
1. Connect to NextCloud and browse files

### Expected behaviour
Folder name should be on the same line as its icon and selection box : ![nextcloud-12](https://user-images.githubusercontent.com/1481387/36470243-761fcaf0-16ea-11e8-9007-6c9dcf48b1a6.png)

### Actual behaviour
Folder name, selection box and icon are displayed unaligned :![nextcloud-13](https://user-images.githubusercontent.com/1481387/36470244-763ce59a-16ea-11e8-8a3d-2acd7336289d.png)

### Server configuration

**Operating system**: RedHat EL 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** 5.6.32

**Nextcloud version:** (see Nextcloud admin page) 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 12.0.4

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - firstrunwizard: 2.2.1
  - lookup_server_connector: 1.1.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - twofactor_backupcodes: 1.2.3
  - user_ldap: 1.3.1
  - user_saml: 1.4.2
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_texteditor
  - files_videoplayer
  - gallery
  - logreader
  - nextcloud_announcements
  - password_policy
  - serverinfo
  - survey_client
  - systemtags
  - theming
  - updatenotification
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test-ec.univ-lorraine.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/test-ec.univ-lorraine.fr",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "logfile": "",
        "log_type": "syslog",
        "loglevel": "2",
        "syslog_tag": "dakeyras-test-ec",
        "log.condition": {
            "apps": [
                "admin_audit",
                "files_external"
            ]
        },
        "maintenance": false,
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+---------------------------------------------------------------+
| Configuration                 | s01                                                           |
+-------------------------------+---------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                             |
| hasPagedResultSupport         |                                                               |
| homeFolderNamingRule          |                                                               |
| lastJpegPhotoLookup           | 0                                                             |
| ldapAgentName                 | cn=app-ec,ou=system,dc=univ-lorraine,dc=fr                    |
| ldapAgentPassword             | ***                                                           |
| ldapAttributesForGroupSearch  |                                                               |
| ldapAttributesForUserSearch   |                                                               |
| ldapBackupHost                |                                                               |
| ldapBackupPort                |                                                               |
| ldapBase                      | dc=univ-lorraine,dc=fr                                        |
| ldapBaseGroups                | ou=grouper,dc=univ-lorraine,dc=fr                             |
| ldapBaseUsers                 | ou=people,dc=univ-lorraine,dc=fr                              |
| ldapCacheTTL                  | 600                                                           |
| ldapConfigurationActive       | 1                                                             |
| ldapDefaultPPolicyDN          |                                                               |
| ldapDynamicGroupMemberURL     |                                                               |
| ldapEmailAttribute            | mail                                                          |
| ldapExperiencedAdmin          | 1                                                             |
| ldapExpertUUIDGroupAttr       |                                                               |
| ldapExpertUUIDUserAttr        |                                                               |
| ldapExpertUsernameAttr        | uid                                                           |
| ldapGidNumber                 | gidNumber                                                     |
| ldapGroupDisplayName          | cn                                                            |
| ldapGroupFilter               | (&(objectclass=groupofnames)(cn=ec:*))                        |
| ldapGroupFilterGroups         |                                                               |
| ldapGroupFilterMode           | 0                                                             |
| ldapGroupFilterObjectclass    |                                                               |
| ldapGroupMemberAssocAttr      | member                                                        |
| ldapHost                      | ldaps://ldap-dev.infra.univ-lorraine.fr                       |
| ldapIgnoreNamingRules         |                                                               |
| ldapLoginFilter               | (&(!(BusinessCategory=E*))(!(BusinessCategory=X*))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                               |
| ldapLoginFilterEmail          | 0                                                             |
| ldapLoginFilterMode           | 0                                                             |
| ldapLoginFilterUsername       | 1                                                             |
| ldapNestedGroups              | 0                                                             |
| ldapOverrideMainServer        |                                                               |
| ldapPagingSize                | 500                                                           |
| ldapPort                      | 636                                                           |
| ldapQuotaAttribute            |                                                               |
| ldapQuotaDefault              |                                                               |
| ldapTLS                       | 0                                                             |
| ldapUserDisplayName           | cn                                                            |
| ldapUserDisplayName2          |                                                               |
| ldapUserFilter                | (&(!(BusinessCategory=E*))(!(BusinessCategory=X*)))           |
| ldapUserFilterGroups          |                                                               |
| ldapUserFilterMode            | 0                                                             |
| ldapUserFilterObjectclass     |                                                               |
| ldapUuidGroupAttribute        | auto                                                          |
| ldapUuidUserAttribute         | auto                                                          |
| turnOffCertCheck              | 0                                                             |
| turnOnPasswordChange          | 0                                                             |
| useMemberOfToDetectMembership | 1                                                             |
+-------------------------------+---------------------------------------------------------------+
</details>

### Client configuration
**Browser:** Firefox 58.0.2

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
</details>

#### Browser log
<details>
<summary>Browser log</summary>
</details>

**Comment by MorrisJobke** [comment] 2018-02-21 08:53
Looks like a duplicate of #8043 (we have a fix ready for 13.0.1)

And those steps should help as a workaround:

```
- rm -r data/appdata_*/css/* data/appdata_*/js/*
- occ files:scan-app-data
- reload the page
```

**Closed by MorrisJobke** 2018-02-21 08:53 UTC
