### ISSUE TITLE
Allow admin to view used quota for all users

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#1027] opened 2016-08-23 20:23 UTC
It would be nice if when logged in as admin, you could browse to the Users page and see how much space each user has used compared to their quota. Right now the only way I know of doing this is by running something like ncdu in the terminal on the server.

**Comment by tflidd** [comment] 2016-08-24 05:19
duplicate of https://github.com/nextcloud/server/issues/117

**Closed** 2016-08-24 10:11 UTC
