### ISSUE TITLE
Unified search : Sorting calendar events from the newest ones (top) to the oldest ones (bottom) would be better

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#39929] opened 2023-08-17 09:48 UTC
Hi,

When I search for an event in the unified search field in the top right-hand corner of the NC user interface, it's very difficult to find a specific event if many events contain the label I've entered in the search field; this is the case if the label is the name of a customer I've been working with for years. As well, I don't care about very old events, and there's a good chance that I search for an event among the most recent ones. 
In conclusion, I think it would be better to sort the list of events from the most recent (at the top of the list) to the oldest.

What do you think ?

Thanks

PS : I don't know if this issue is open in the right place ; don't hesitate to move it.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tcitworld** [comment] 2023-08-18 11:39
Duplicate of https://github.com/nextcloud/server/issues/27353

**Closed by tcitworld** 2023-08-18 11:39 UTC
Labels: enhancement, 0. Needs triage, feature: search
