### ISSUE TITLE
error update nextcloud from 16.04 to 16.05

### ISSUE THREAD

**Issue by lonestartexas** [nextcloud/server#17612] opened 2019-10-20 17:08 UTC
I am trying to update nextcloud via browser and get every time this error message.
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON c.constraint_name = k.constraint_name AND c.table_name = 'oc_collres_accesscache' */ WHERE k.table_name = 'oc_collres_accesscache' AND k.table_schema = 'nextcloud' /*!50116 AND c.constraint_schema = 'nextcloud' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON c.constraint_name = k.constraint_name AND c.table_name = 'oc_collres_accesscache' */ WHERE k.table_name = 'oc_collres_accesscache' AND k.table_schema = 'nextcloud' /*!50116 AND c.constraint_schema = 'nextcloud' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by szaimen** [comment] 2021-05-27 09:23
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 09:23 UTC
Labels: 0. Needs triage, bug
