### ISSUE TITLE
WebDav: fatal error when creating a new calendar entry

### ISSUE THREAD

**Issue by BenS89** [nextcloud/server#3281] opened 2017-01-26 14:50 UTC
**Steps to reproduce:**

 - Use calendar app 1.5.0 with Nextcloud 11.0.1
-  Create a new calendar entry with a mobile device using the /dav-Endpoint
- Take a look at the Nextcloud logs

**Expected behavior:**
The calendar entry is created without any errors in the logs.

**Actual behaviour:**
The calendar entry is created successfully but the logs show a fatal error:

`Sabre\DAV\Exception\BadRequest: HTTP/1.1 400 The {DAV:}property-search element must contain one {DAV:}match and one {DAV:}prop element [internal function] Sabre\DAVACL\Xml\Request\PrincipalPropertySearchReport xmlDeserialize(Object(Sabre\Xml\Reader)) /share/MD0_DATA/htdocs/cloud/3rdparty/sabre/xml/lib/Reader.php - line 246: call_user_func(Array, Object(Sabre\Xml\Reader)) /share/MD0_DATA/htdocs/cloud/3rdparty/sabre/xml/lib/Reader.php - line 71: Sabre\Xml\Reader->parseCurrentElement() /share/MD0_DATA/htdocs/cloud/3rdparty/sabre/xml/lib/Service.php - line 118: Sabre\Xml\Reader->parse() /share/MD0_DATA/htdocs/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 714: Sabre\Xml\Service->parse('<?xml version="...', '/cloud/remot...', NULL) [internal function] Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) /share/MD0_DATA/htdocs/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array) /share/MD0_DATA/htdocs/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method REPORT', Array) /share/MD0_DATA/htdocs/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response)) /share/MD0_DATA/htdocs/cloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec() /share/MD0_DATA/htdocs/cloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec() /share/MD0_DATA/htdocs/cloud/remote.php - line 165: require_once('/share/MD0_DATA...') {main}`

Enabled apps:
Calendar 	1.5.0

PHP-Version: 7.0.9
OS: Embedded QNAP-Linux

**Comment by wiswedel** [comment] 2019-06-12 20:34
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Closed by wiswedel** 2019-06-12 20:34 UTC
Labels: 0. Needs triage, bug, feature: dav, low

**Comment by loeffelpan** [comment] 2020-01-30 18:37
I can reproduce this with Nextcloud 17.0.2 and Calender 2.0.1.

**Comment by loeffelpan** [comment] 2020-02-01 10:58
OK sorry.
It's gone with 17.0.3 now.
