### ISSUE TITLE
Upload MB counter resets when uploading multiple files

### ISSUE THREAD

**Issue by ryan77627** [nextcloud/server#20479] opened 2020-04-14 17:06 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload a folder with multiple files
2. Look at the total displayed when hovering over the upload bar
3. Upload a second folder before the first one finishing uploading

### Expected behaviour
The total file size should be added to what was being uploaded perviously

### Actual behaviour
The total upload size resets to whatever the last thing you dragged in was, causing the bar to go to "A few more seconds" indefinitely and not knowing how much more is left to upload.

See issue here: https://ibb.co/xCrS0y1
In the picture I was bulk uploading some files and "of 5.5MB" happened to be the size of the last thing I dropped in.

### Server configuration

**Operating system:** OpenSUSE Tumbleweed

**Web server:** NGINX/1.17.9

**Database:** MariaDB 10.4.12

**PHP version:** 7.4.4

**Nextcloud version:** 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Download page from a tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - calendar
  - encryption
  - files_external
  - mail
  - spreed
  - survey_client
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nas.ryanserver.home"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "http:\/\/nas.ryanserver.home",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No
**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Ubuntu 19.10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing pertaining to this appears in the logs
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Just repeated entries of "You are using the fallback implementation of the intl extension", which I have since corrected. Nothing has shown up since then.
```
</details>

**Comment by wiswedel** [comment] 2020-11-19 08:37
Duplicate of #17279

**Closed by wiswedel** 2020-11-19 08:37 UTC
Labels: 0. Needs triage, bug
