### ISSUE TITLE
Do not save edited photos as a new filles 

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#44772] opened 2024-04-10 19:56 UTC
Every time when I use the embedded web app to edit images and click `Save` button the app it saves them as `<filename>_edited.jpg`, which is not convenient, as I am looking for the changes in the file I have changed.

I suggest changing the behaviour of how the edited images are saved:
1. When clicking `Save` button the existing image file is overwritten
2. Add a new button `Save as a new file` which will prompt the new name for the edited file.

![image](https://github.com/nextcloud/server/assets/5199030/63631673-7bea-437c-8d5c-96fed6c4ebec)

**Comment by joshtrichards** [comment] 2024-04-11 00:54
Duplicate of nextcloud/viewer#2289

**Closed by joshtrichards** 2024-04-11 00:54 UTC
Labels: enhancement, 0. Needs triage
