### ISSUE TITLE
Restoring file version gives incorrect filename and no extension

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#13239] opened 2018-12-23 11:38 UTC
### Steps to reproduce
1. Create file, make changes to create different versions
2. Go on file and show details, go to the versions tab
3. Download last version (click on the area marked in this screenshot):
![screenshot](https://user-images.githubusercontent.com/8111200/50383181-d9395480-06ae-11e9-979e-ff26ef995392.PNG)

This issues was reported by one of our users on the forum: https://help.nextcloud.com/t/nc15-restoring-file-version-gives-incorrect-filename-and-no-extension/43746

### Expected behaviour
Download file with correct extension and a file name which relates to the actual filename (either the real filename, or filename_timestamp.extension).

### Actual behaviour
You get a file without extension, and the filename is just a time stamp.

### Server configuration

see forum post. I reproduced it on a Debian/Apache/mod_php system.

**Comment by violoncelloCH** [comment] 2018-12-25 21:04
I can reproduce this with 15.0.0 however not with the current master.

**Comment by Beeez** [comment] 2019-01-30 18:58
Has there been much progress on this at all? I am seeing the same for my file downloads in versioning.

**Comment by violoncelloCH** [comment] 2019-01-31 15:14
I can't reproduce it with 15.0.3RC1
can you test it, if it works for you with 15.0.3(RC1)?

**Comment by Beeez** [comment] 2019-01-31 15:18
Is this not available yet in stable branch?

**Comment by Beeez** [comment] 2019-01-31 15:30
Is there anywhere I can see changes made in RC1 and can potentially apply them to my own instance? 

I had noticed this line and made changes however it did not affect the downloadUrl 
https://github.com/nextcloud/server/blob/530e39b0612b6abaa0a17b7fabb7daefb1201bd6/apps/files_versions/js/versionmodel.js#L64

**Comment by violoncelloCH** [comment] 2019-01-31 15:33
#13912 this PR mentions all merged PRs for 15.0.3RC1

**Comment by Beeez** [comment] 2019-01-31 18:49
Not seeing 13239 as part of those fixes?

**Comment by violoncelloCH** [comment] 2019-01-31 18:59
as I said, there are the merged PRs listed not the issues...

**Comment by Beeez** [comment] 2019-02-07 15:24
I have updated to 15.0.4 but file versioning still downloads without extensions.

**Comment by violoncelloCH** [comment] 2019-02-07 16:14
Okay, it depends on the setup... (Maybe on the webserver?)
I can reproduce it with a production 15.0.4 setup running on apache2 but not on a nginx testing setup ...
@Beeez what webserver do you use?
cc @nextcloud/server-triage 


> One last thing which i cant tell is part of 15.03RC1. When I am inside of a shared folder and check file versions, the download URL is using my own user folder for grabbing the versioned file (which does not exist) rather than pointing to the source of the actual file stored in `_groupfolders/versions/<folder Number>/<fileid>`

that's probably an other issue... @Beeez can you report it to the groupfolders repo?

**Comment by Beeez** [comment] 2019-02-07 16:30
I have two nextcloud servers, both running apache2, with haproxy loadbalancer in front. Redis memcache and two mysql servers.

**Comment by Beeez** [comment] 2019-02-08 15:32
@violoncelloCH It seems like all of the commits for 15.0.3RC1 files_versions had a nextcloud dependency version of 16 so even though I am updated to 15.0.4, it might have never updated files_versions to what was in RC1
https://github.com/nextcloud/server/blob/fda3f4fc4188cc95f18926f0601f3dd698be9c79/apps/files_versions/appinfo/info.xml#L27

**Comment by violoncelloCH** [comment] 2019-02-16 23:25
@Beeez the backported PRs/commits for NC 15 go into the stable15 branch, where the min-version is 15... so no reason to worry about that :)

**Comment by angry-tony** [comment] 2019-04-03 04:26
Hi all
is it fixed??
I have the same problem on Nextcloud 15.0.5 and hope that this bug will be solved soon.

**Comment by Beeez** [comment] 2019-04-10 19:24
> Hi all
> is it fixed??
> I have the same problem on Nextcloud 15.0.5 and hope that this bug will be solved soon.

I dont think so :(

**Comment by Beeez** [comment] 2019-04-26 14:54
Still an issue in NC16

**Comment by Beeez** [comment] 2019-05-29 13:18
Well for the time being I am just hiding the File Versioning completely from the UI in my own instance by commenting out a portion of OCA.Versions.VersionsTabView, at least until this is fixed.

**Comment by violoncelloCH** [comment] 2019-05-31 21:53
seems to depend on the setup, but couldn't find out what triggers it...
Just tested it again, and on a production setup with apache it still happens, but on a test setup with nginx I get the correct filename (both NC 16.0.1)... also on my dev setup with latest master on apache it's happening as well...
@nextcloud/server-triage could someone please take a closer look?

**Comment by pjrobertson** [comment] 2019-06-25 01:08
I'm also now experiencing this bug. Not sure when it started happening. I've started trying to debug, but am yet to find a reason. Things I've checked/confirmed aren't an issue (incase it helps others debugging down the line):

1. PHP version: PHP7.0 and PHP7.2 both experience the problem
2. File permissions on the files_version directory

If someone can point me to the code that picks up the requests to `example.com/remote.php/dav/versions/username/versions/123456/12345678901` then I can try and debug from that end. Right now I'm stabbing in the dark.

**Comment by Beeez** [comment] 2019-06-26 14:27
> Is there anywhere I can see changes made in RC1 and can potentially apply them to my own instance?
> 
> I had noticed this line and made changes however it did not affect the downloadUrl
> https://github.com/nextcloud/server/blob/530e39b0612b6abaa0a17b7fabb7daefb1201bd6/apps/files_versions/js/versionmodel.js#L64

@pjrobertson I had mentioned it here where it is being generated.

**Comment by pjrobertson** [comment] 2019-06-27 22:39
@Beeez that's the code that generates the download URL. I'm looking for the server-side code that deals with that request (i.e. deals with the request when my browser opens the file). The issue seems to be with the `Content-Disposition` response header, and more specifically the `filename` value in that header, so we need to understand why it's not getting set to the actual name of the file.

**Comment by pjrobertson** [comment] 2019-06-27 23:39
OK so upon further inspection I note that the request calls `httpGet` in `Sabre\\DAV\\CorePlugin` which is what actually serves the file to the client. I went down and drilled into `files_versions/Storage.php` and noted that `getVersions()` correctly sets the right `filename` for the Version. However in `httpGet` only the following `httpHeaders` are being set:

```[content-type] => Array
                (
                    [0] => Content-Type
                    [1] => Array
                        (
                            [0] => application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                        )

                )

            [last-modified] => Array
                (
                    [0] => Last-Modified
                    [1] => Array
                        (
                            [0] => Tue, 25 Jun 2019 06:32:54 GMT
                        )

                )

            [etag] => Array
                (
                    [0] => ETag
                    [1] => Array
                        (
                            [0] => 1561444374
                        )

                )
```

No headers relating to `filename` are being set. Perhaps this is where the issue is. Can somebody who has a working server (which provides file versions with the correct name) please perform the following:

1. Open up `3rdparty/sabre/dav/lib/DAV/CorePlugin.php`
2. At line ~122 (just after `$response->addHeaders($httpHeaders);`) add the lines:
     ```
     $logger = \OC::$server->getLogger()
     $logger->error(print_r($response, true));```

3. Paste the subsequent log info from the nextcloud.log file

If your response info has `filename` set, then this would be where the issue lies.

**Comment by skjnldsv** [comment] 2020-09-09 11:29
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen

**Closed by skjnldsv** 2020-09-09 11:29 UTC
Labels: 0. Needs triage, bug, feature: versions, regression
