### ISSUE TITLE
Resume chunked upload not working ? V 13.0.1

### ISSUE THREAD

**Issue by greinick** [nextcloud/server#8906] opened 2018-03-21 07:55 UTC
### Steps to reproduce
1. open a web browser like chrome, firefox or safari
2. switch to the upload folder
3. drop a large file (in that case 3.3GB ) to it and wait some time
4. interrupt the upload e.g. close the browser / disconnect from network
5. do step 1. to 3.

### Expected behaviour
The upload should continue not at the beginning. It should resume +- bytes at the point as the interruption happened.

### Actual behaviour
The upload starts from the beginning.

### Server configuration

**Operating system**:
Centos 7

**Web server:**
httpd 2.4

**Database:**
mysql 5.6

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from 12.0.6

**Where did you install Nextcloud from:**
your webpage / zip file and web updater.

As from the android repo issue https://github.com/nextcloud/android/issues/159 and the last comment from @MorrisJobke I hoped, in V13 this will work. May be I'm missing something?

Thanks and Regards

**Comment by MorrisJobke** [comment] 2018-03-21 08:01
Resuming chunked upload is not yet there on the web UI.

Duplicate of #673

**Closed by MorrisJobke** 2018-03-21 08:01 UTC
