### ISSUE TITLE
Whitelist for code signing check

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/server#10818] opened 2018-08-23 11:21 UTC
In Nextcloud 13 Administration Manual - Code signing (1) is defined the files and errors from code signing, shown in admin settings in the webview. Here we cannot set a whitelist for extra files or for invalid hash files.

Like .htaccess should be changed for internal configurations or stats folder for external statistic stuff should be configurable in a whitelist. Files which are core files should be excluded from these whitelist.
This should be configurable for files and folders.

The completely deactivation of code signing checks aren't necessary to get a clean config page.

(1)
https://docs.nextcloud.com/server/13/admin_manual/issues/code_signing.html

**Comment by TRILOS** [comment] 2018-12-20 17:03
Even a custom directory name where files should be save, which has been set in the web interface, is not being tolerated, therefore the update routine is blocked.
I think the user should decide, which files and directories should be whitelisted.

**Comment by danielkesselberg** [comment] 2018-12-20 17:36
> Even a custom name for the directory where files should be saved, which has been set in the web interface, is not being tolerated, therefore the update routine is blocked.
> I think the user should decide, which files and directories should be whitelisted.

Could you report this issue to [nextcloud/updater](https://github.com/nextcloud/updater/issues). `Code Signing` and `Expected Directories` are something different. I think another name for the `datadirectory` is supported and should work.

**Comment by TRILOS** [comment] 2019-01-09 17:06
Done, see https://github.com/nextcloud/updater/issues/201

 

 

Von: Daniel Kesselberg <notifications@github.com> 
Gesendet: Donnerstag, 20. Dezember 2018 18:36
An: nextcloud/server <server@noreply.github.com>
Cc: TRILOS new media <service@trilos.de>; Comment <comment@noreply.github.com>
Betreff: Re: [nextcloud/server] Whitelist for code signing check (#10818)

 

Even a custom name for the directory where files should be saved, which has been set in the web interface, is not being tolerated, therefore the update routine is blocked.
I think the user should decide, which files and directories should be whitelisted.

Could you report this issue to nextcloud/updater <https://github.com/nextcloud/updater/issues> . Code Signing and Expected Directories are something different. I think another name for the datadirectory is supported and should work.

**Comment by MorrisJobke** [comment] 2019-03-25 08:16
Duplicate of #1366

**Closed by MorrisJobke** 2019-03-25 08:16 UTC
