### ISSUE TITLE
Behaviour of "Show only busy or hidden" when Sharee can edit

### ISSUE THREAD

**Issue by EorlBruder** [nextcloud/server#10865] opened 2018-08-26 13:49 UTC
### Steps to reproduce
1. Create an Event with visibility of "When shared show only busy"
2. Share the calendar to a group and set the checkbox "can edit"
3. Now other members of that group shouldn't be able to see the details of the event, but only busy 
(Same goes for hidden)

### Expected behaviour
I am not quite sure what the real expected behaviour would be. In my eyes being able to edit a calendar should mean, that I can see all events of that calendar, as the owner would do. 
To elaborate a bit on my current use case: We want to use nextcloud for the calendar of our student council. We want to have one calendar to schedule organizational meetings. This calendar should be publicly visible, but not alle meetings should appear int he public share. For these events we'd like to use busy/hidden to hide the event in the public calendar, but still all members of the council should be able to see and edit the details of those events.

**Comment by georgehrke** [comment] 2019-09-11 08:12
Duplicate of https://github.com/nextcloud/server/issues/5551

**Closed by georgehrke** 2019-09-11 08:12 UTC
Labels: enhancement, feature: dav
