### ISSUE TITLE
Unexpected theme change 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/server#28562] opened 2021-08-23 11:01 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
This  is odd, today when I try to log in to my NC account, I saw default wallpaper and logo, every theme revert back to the default

### Expected behaviour
Everything should stay the same, my wallpaper and logo.

### Actual behaviour
Wallpaper and Logo revert back to default

### Server configuration

**Operating system:**
Fedora Server 33
**Web server:**
Apache
**Database:**
PostgreSQL
**PHP version:**
7.4.12
**Nextcloud version:** (see Nextcloud admin page)
21.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install 
**Where did you install Nextcloud from:**
Official website
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox
**Operating system:**
Fedora Workstation 34
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Mon Aug 23 08:38:11.408710 2021] [access_compat:error] [pid 2421:tid 2478] [client 192.168.29.10:51075] AH01797: client denied by server configuration: /var/www/html/nextcloud/config
[Mon Aug 23 08:43:31.322812 2021] [access_compat:error] [pid 2421:tid 2470] [client 192.168.21.3:49729] AH01797: client denied by server configuration: /var/www/html/nextcloud/config
[Mon Aug 23 09:13:36.116859 2021] [access_compat:error] [pid 1082:tid 1220] [client 192.168.22.39:50568] AH01797: client denied by server configuration: /var/www/html/nextcloud/config
[Mon Aug 23 09:15:24.032857 2021] [access_compat:error] [pid 1081:tid 1249] [client 192.168.29.6:50839] AH01797: client denied by server configuration: /var/www/html/nextcloud/config
[Mon Aug 23 11:40:14.317535 2021] [access_compat:error] [pid 1081:tid 1258] [client 192.168.22.39:59936] AH01797: client denied by server configuration: /var/www/html/nextcloud/config
[Mon Aug 23 13:04:28.286382 2021] [access_compat:error] [pid 78936:tid 78977] [client 192.168.29.10:55500] AH01797: client denied by server configuration: /var/www/html/nextcloud/config
[Mon Aug 23 13:40:13.725682 2021] [access_compat:error] [pid 1082:tid 1175] [client 192.168.22.39:32872] AH01797: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```{"reqId":"YSN9b3YgXHD4q8ZUu37TKwAATyE","level":3,"time":"2021-08-23T10:50:23+00:00","remoteAddr":"192.168.22.39","user":"administrator","app":"index","method":"GET","url":"/apps/theming/styles?v=8","message":{"Exception":"ScssPhp\\ScssPhp\\Exception\\CompilerException","Message":"Undefined variable $theming-cachebuster: apps/theming/css/theming.scss on line 96, at column 2\nCall Stack:\n#0 import apps/theming/css/theming.scss (unknown file) on line 1","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":4960,"function":"error","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":3354,"function":"get","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":3384,"function":"reduce","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":3377,"function":"reduce","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":3377,"function":"reduce","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":3434,"function":"reduce","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":3393,"function":"fncall","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":2843,"function":"reduce","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":2154,"function":"compileChild","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":1734,"function":"compileChildrenNoReturn","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":2704,"function":"compileBlock","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":2154,"function":"compileChild","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":5306,"function":"compileChildrenNoReturn","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":2477,"function":"importFile","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":2688,"function":"compileImport","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":2154,"function":"compileChild","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":570,"function":"compileChildrenNoReturn","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","line":401,"function":"compileRoot","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Template/SCSSCacher.php","line":343,"function":"compile","class":"ScssPhp\\ScssPhp\\Compiler","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Template/SCSSCacher.php","line":189,"function":"cache","class":"OC\\Template\\SCSSCacher","type":"->"},{"file":"/var/www/html/nextcloud/apps/theming/lib/Controller/ThemingController.php","line":353,"function":"process","class":"OC\\Template\\SCSSCacher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"getStylesheet","class":"OCA\\Theming\\Controller\\ThemingController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/3rdparty/scssphp/scssphp/src/Compiler.php","Line":5602,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0","version":"21.0.4.1","id":"61237d7126455"}\
```
</details>

**Comment by szaimen** [comment] 2021-08-23 11:10
Most likely a duplicate of https://github.com/nextcloud/guests/issues/719

**Closed by szaimen** 2021-08-23 11:10 UTC
Labels: bug, 0. Needs triage
