### ISSUE TITLE
Urgent help nextcloud 13 in index.php is white

### ISSUE THREAD

**Issue by gurussia** [nextcloud/server#8320] opened 2018-02-12 23:48 UTC
Hi guys.

I updated nextcloud to latest stable 13 version and it works. So yestaday i try to install php7.2 and from there it  comment white screen.

In developer mode in chrome it comment:

JQMIGRATE: Migrate is installed, version 1.4.0
window.controllers/Controllers is deprecated. Do not use it for UA detection.
SoundManager 2: No Flash detected. Trying HTML5-only mode.
SoundManager V2.97a.20170601 (HTML5-only mode)
SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true, flac = true
SoundManager 2: Ready. ✓
TypeError: OC.MimeTypeList is undefined
[Learn More]
merged-template-prepend.js:4631:10
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://yourwebsite.com/core/vendor/core.js?v=6f41fc1d-0
Source Map URL: purify.min.js.map
[Learn More]

How you see here in the photos:
https://ibb.co/jVuY0n
https://ibb.co/jNeBmS

Only white screen for Application file " files ", everything else is working, include in php7.2 nextcloud is working very fast in everything. Calendar is working and etc. From android file manager works, it only show white screen from web interface. Please guys help me , how you see on the photos i have more than 200 gb. of data.

Update 1:

Include when i try to download photo it comment me this: 

    Sorry, this file could not be found.

    Reasons might be:
        the wrong file ID was provided
        the file was removed
        the file is corrupt
        the encryption key is missing

    Here is the error message returned by the server: Could not locate node linked to ID: 241788 (404)

    For more information, please contact your friendly Nextcloud administrator.

**Comment by gurussia** [comment] 2018-02-13 06:18
update 2: in case someone comment php7.2 is not compatible i change to php7.1 and again nextcloud comment white screen. Include if i remember i try with php5 and it again comment white screen

**Comment by randomnickname1337** [comment] 2018-02-13 08:23
php not working as well ... after i clicked - Keep maintenance active - NO - for web browsers i get blank page ...

**Comment by randomnickname1337** [comment] 2018-02-13 08:35
1, disable files_accesscontrol 
2, upgrade nextcluod
3, go to deactivated apps , update to 1.3.0 - i got before update 1.2.5 -but it dont show, that update is avaliable

**Comment by triforce** [comment] 2018-02-13 08:59
I just moved my <nextcloud_home>/apps/files_accesscontrol directory and the upgrade continued normally. It looks like it recreates the app directory anyway but you may lose settings.

**Comment by MorrisJobke** [comment] 2018-02-13 10:18
> Only white screen for Application file " files ", everything else is working, include in php7.2 nextcloud is working very fast in everything. Calendar is working and etc. From android file manager works, it only show white screen from web interface. Please guys help me , how you see on the photos i have more than 200 gb. of data.

This looks like a JS error.



> TypeError: OC.MimeTypeList is undefined
> [Learn More]
> merged-template-prepend.js:4631:10

And there it is.


Looks like a duplicate of #8043 (we have a fix ready for 13.0.1)

And those steps should help as a workaround:

```
- rm -r data/appdata_*/css/* data/appdata_*/js/*
- occ files:scan-app-data
- reload the page
```

**Comment by MorrisJobke** [comment] 2018-02-13 10:19
I will close this ticket for now. If this does not solve the problem, we can reopen it.

cc @tflidd for your information - if people have problems with the style or behaviour they should clean the CSS and JS cache on the server with the above mentioned steps. fro 13.0.1 we introduce a repair step to do so.

**Closed by MorrisJobke** 2018-02-13 10:19 UTC

**Comment by gurussia** [comment] 2018-02-13 12:18
hi guys. i was thinking my post was deleted.

nextcloud why you didnt make solve when you knoe about white page. 

-" if people have problems with the style or behaviour they should clean the CSS and JS cache on the server with the above mentioned steps. fro 13.0.1 we introduce a repair step to do so. : this is out off respect. if i was developer i will fix it but im not developer. so your comment is out of respect. morris jonson thanks too for that you commemt solution.

**Comment by MorrisJobke** [comment] 2018-02-13 16:47
> this is out off respect. if i was developer i will fix it but im not developer. so your comment is out of respect. morris jonson thanks too for that you commemt solution.

What do you mean by this? We have a fix in place, which is not yet in a release but in an upcoming release. We can't do much more than fixing the issue, provide intermediate steps to work around it and ship it with the next release. I don't see any non respectful behaviour here. Maybe I missed something.
