### ISSUE TITLE
Can't remove user from group

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/server#23340] opened 2020-10-10 19:57 UTC
### Steps to reproduce
1. User is in "Users" group
2. Add user to new group
3. Try to remove user from "Users" group - > you can't

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
Apache

**Database:**
SQLite

**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
20.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgrade from 19.03

### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu 20.04

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Exception: Argument 2 passed to OCA\Provisioning_API\Controller\UsersController::removeFromGroup() must be of the type string, null given, called in /nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 169

    /nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main()

    /nextcloud/ocs/v1.php - line 88:

    OC\Route\Router->match()

    /nextcloud/ocs/v2.php - line 24:

    require_once("/n ... p")

</details>

**Comment by acsfer** [comment] 2020-10-11 12:31
Duplicate of https://github.com/nextcloud/server/issues/23237

**Closed by acsfer** 2020-10-11 12:31 UTC
Labels: 0. Needs triage, bug
