### ISSUE TITLE
Sharing a file adds (2) (2) (2) (2) to filename and breaks things

### ISSUE THREAD

**Issue by realitygaps** [nextcloud/server#2061] opened 2016-11-09 11:10 UTC
### Steps to reproduce
1. Create folder
2. Share folder with another nextcloud user
3. Folder gets (2) (2) (2) (2) (2) appended to its name
4. Folder can't be accessed/renamed/deleted by user it was shared to (with rights)

### Expected behaviour
Folder should be shared with its actual name

### Actual behaviour
Folder gets large numbers of (2) (2) (2) (2) added to filename and this stops it from being renamed/deleted/accessed.

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Nginx

**Database:** Mysql

**PHP version:** PHP 5.6.27-0+deb8u1

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.3.2
  - announcementcenter: 1.1.2
  - apporder: 0.3.2
  - audioplayer: 1.2.2
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - direct_menu: 0.9.2
  - documents: 0.13.1
  - external: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_opds: 0.6.16
  - files_pdfviewer: 0.8.1
  - files_reader: 0.7.2
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - gpxpod: 1.0.6
  - music: true
  - news: 9.0.4
  - notes: 2.0.2
  - notifications: 0.3.0
  - ownpad: 0.5.5
  - password_policy: 1.0.0
  - polls: 0.7.2
  - provisioning_api: 1.0.0
  - qownnotesapi: 16.09.0
  - rainloop: 4.27
  - serverinfo: 1.1.1
  - sharerenamer: 1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocvhnavirlha",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.weho.st"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "***REMOVED VALUE***",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "10.0.12.10",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 4,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "mail_from_address": "info",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED VALUE***",
        "maintenance": false,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\PDF"
        ]
    }
}

</details>

**Are you using external storage, if yes which one:**  no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+---------------------------------------------+
| Configuration                 |                                             |
+-------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport      |                                             |
| hasPagedResultSupport         |                                             |
| homeFolderNamingRule          | attr:uid                                    |
| lastJpegPhotoLookup           | 0                                           |
| ldapAgentName                 | cn=admin,dc=example,dc=com                      |
| ldapAgentPassword             | ***                                         |
| ldapAttributesForGroupSearch  |                                             |
| ldapAttributesForUserSearch   |                                             |
| ldapBackupHost                |                                             |
| ldapBackupPort                |                                             |
| ldapBase                      | dc=example,dc=com                               |
| ldapBaseGroups                | dc=example,dc=com                               |
| ldapBaseUsers                 | dc=example,dc=com                               |
| ldapCacheTTL                  | 600                                         |
| ldapConfigurationActive       | 1                                           |
| ldapDynamicGroupMemberURL     |                                             |
| ldapEmailAttribute            | mail                                        |
| ldapExperiencedAdmin          | 0                                           |
| ldapExpertUUIDGroupAttr       | cn                                          |
| ldapExpertUUIDUserAttr        | uid                                         |
| ldapExpertUsernameAttr        | uid                                         |
| ldapGroupDisplayName          | cn                                          |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))              |
| ldapGroupFilterGroups         |                                             |
| ldapGroupFilterMode           | 0                                           |
| ldapGroupFilterObjectclass    | posixGroup                                  |
| ldapGroupMemberAssocAttr      | memberUid                                   |
| ldapHost                      | 10.0.12.42                                  |
| ldapIgnoreNamingRules         |                                             |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                             |
| ldapLoginFilterEmail          | 0                                           |
| ldapLoginFilterMode           | 0                                           |
| ldapLoginFilterUsername       | 1                                           |
| ldapNestedGroups              | 0                                           |
| ldapOverrideMainServer        |                                             |
| ldapPagingSize                | 500                                         |
| ldapPort                      | 389                                         |
| ldapQuotaAttribute            | ownCloudQuota                               |
| ldapQuotaDefault              | 5368709120                                  |
| ldapTLS                       | 0                                           |
| ldapUserDisplayName           | uid                                         |
| ldapUserDisplayName2          |                                             |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))              |
| ldapUserFilterGroups          |                                             |
| ldapUserFilterMode            | 0                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                               |
| ldapUuidGroupAttribute        | auto                                        |
| ldapUuidUserAttribute         | auto                                        |
| turnOffCertCheck              | 0                                           |
| useMemberOfToDetectMembership | 1                                           |
+-------------------------------+---------------------------------------------+

</details>

### Client configuration
**Browser:**  Chromium and Firefox

**Operating system:**  Linux & OSX

#### Web server error log
<details>
<summary>Web server error log</summary>
Dont see errors in log
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
didnt see anything in the logs that seemed relevant
</details>

**Comment by nickvergessen** [comment] 2016-11-09 13:19
@MorrisJobke @rullzer this was fixed before or after 10.0.1?

**Comment by rullzer** [comment] 2016-11-09 18:21
mmm I think most of it was fixed in 10.0.1. But as it is obvious here not everything.

**Comment by MorrisJobke** [comment] 2016-11-10 15:28
issue: #1588
master fix: #1595
stable10 fix: #1645 (will be shipped with 10.0.2)

**Comment by realitygaps** [comment] 2016-11-12 12:33
I patched my 10.0.1 but am still seeing this issue

**Comment by MorrisJobke** [comment] 2016-11-12 12:46
> I patched my 10.0.1 but am still seeing this issue

You need to rename the file back - so it doesn't automatically repair the problem. It only avoids that it happens again.

**Comment by realitygaps** [comment] 2016-11-12 20:13
This seemed to happen on new shares also, I will check again and confirm

**Comment by realitygaps** [comment] 2016-11-12 22:08
Sharing files (including newly created folders) seems to cause the same issue still.

**Comment by realitygaps** [comment] 2016-11-13 17:38
I manually fixed the folder name in the database list of shares and it stays fixed, but new folders that are shared still get the (2) (2) (2) added.

**Comment by mattronix** [comment] 2016-11-13 18:17
Hi so i am on the same cloud with Realitygaps and we have been testing this. 

We have noticed that with the patch the following issues still occurs:

When all sync clients mobile or desktop are active and online or disabled and offline (mobile clients set to airport mode)  we see (2) (2) (2) in the title even after renaming the share targets in the database. 

When we then had no sync clients active and the web interface closed the (2) in the title is no longer present.

When i login then the share i made from me to realitygaps get s (2) (2) .... in the name and the share from realitygaps still has no (2) ...  in the name when realitygaps then logs into the web interface  the folder he shared to me from his account now has (2) (2) ... in the name when i had logged in just moments before it did not have (2) ... in the name.

We have confirmed that the bug is still present for us and it appears most likely the (2) ... is coming from the side of the created user and it seems to be regardless of using desktop client or web interface just the user has to be connected with something. 

Test Devices: 

two Android Mobiles running the Stable client of NextCloud
1 Mac Book pro running stable desktop client  (10.12.1)
1 Lenovo Think pad running stable desktop client (Arch Linux latest build and kernel) 


Test Cases: 
Both users active on 1 mobile and 1 desktop 
one User active on 1 mobile and 1 desktop
both users disconnected from web interface and mobile in airport mode
Both users connected to web interface only 
one user connected to web interface only 
Both users connected to desktop client only 

we see the same results in all cases, i hope this helps abit. 

Kind Regards, Matthew Frost

**Comment by realitygaps** [comment] 2016-11-21 14:45
This is still happening on our install. I assume the closed ticket is not being noticed.

**Comment by nickvergessen** [comment] 2016-11-22 10:16
@MorrisJobke @rullzer can you look at this again?

**Comment by hadrigan** [comment] 2017-01-13 10:20
we are running Nextcloud version 10.0.2. Since we use a special external storage hierarchical structure, this is a big problem for us. We use a hierarchy of external storages, where the manager is in all ldap groups of its subordinates. so double and even tripple sharing is happening very often.

**Comment by Skywalker-11** [comment] 2017-01-31 14:24
Still in Nextcloud 11.0.1

**Comment by realitygaps** [comment] 2017-01-31 14:25
I havent seen this issue recently (running 11.0.1)

**Comment by MorrisJobke** [comment] 2017-04-30 05:12
> Still in Nextcloud 11.0.1

@Skywalker-11 Could you try the update to 11.0.3 - we changed some stuff in there. I haven't seen this issue anymore after 11.0.0 on my own instances. And we also fail to reproduce this here. I will close this ticket for now, but we are will reopen if this still is a problem for you with a recent version.

Thanks

**Closed by MorrisJobke** 2017-04-30 05:12 UTC
Labels: feature: sharing

**Comment by Skywalker-11** [comment] 2017-05-05 08:23
Yes seems to be fixed
