### ISSUE TITLE
Clicking search results does nothing on Safari

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#36506] opened 2023-01-30 06:40 UTC
> I have noticed recently that while the Notes search feature still works as far a showing correct preview of what is found, I cannot click on the preview to get to the actual note. This may be restating this same problem, but in any event, if actual url links are provided, it would be one way of solving the problem. This problem occurs using Safari browser on macOS Ventura. Using Chrome browser on same system the linking process to the found notes items works.

_Originally posted by @aardquark in https://github.com/nextcloud/notes/issues/764#issuecomment-1407497549_

**Comment by Peachy74** [comment] 2023-02-10 09:31
Same error with me. 
Safari 16.2
Nextcloud 25.0.3
Can't open any search result. But with Edge Browser it works without any problem.

**Comment by joshtrichards** [comment] 2024-10-29 17:45
I can't reproduce this behavior today in WebKit-based browsers.

Are any of you still experiencing this?

**Comment by aardquark** [comment] 2024-10-31 01:14
Search in Notes now works correctly for me with the (old) Safari version 16.1 and Nextcloud 30.0.1.

**Comment by joshtrichards** [comment] 2024-10-31 12:41
Glad to hear it! And thanks for confirming. I'll close this Issue out.

**Closed by joshtrichards** 2024-10-31 12:41 UTC
Labels: bug, needs info, 0. Needs triage, feature: search, 26-feedback, needs review
