### ISSUE TITLE
Sidepanel doesn't update all fields

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/server#11969] opened 2018-10-22 02:32 UTC
### Steps to reproduce
1a. Select installed App that only available for groups
1b. Select App not available for groups
2a. Select file or folder to show details with activities
2b. Select other file or folder to show details with activities

### Expected behaviour
1) Checkbox should update
2) Activities from next selected file or folder should get shown

### Actual behaviour
1) Checkbox from previous selected App gets still shown
2) Activities from previous selected file or folder gets shown

Same behaviour with dysfunct Tags, making it impossible to set Tags in a reasonable fashion. #10774

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
nginx 1.10.3
**Database:**
mysql 5.7.23
**PHP version:**
php 7.2.11
**Nextcloud version:** (see Nextcloud admin page)
14.0.3.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated since owncloud 8
**Where did you install Nextcloud from:**
official download link

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - apporder: 0.5.0
  - audioplayer: 2.4.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.3.1
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - passwords: 2018.10.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - radio: 0.6.3
  - registration: 0.4.5
  - serverinfo: 1.4.0
  - spreed: 4.0.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - comments
  - encryption
  - federation
  - firstrunwizard
  - nextcloud_announcements
  - sharebymail
  - support
  - survey_client
  - systemtags
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to png                                                       --outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF"
        ],
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "xframe_restriction": true,
        "activity_expire_days": 30,
        "versions_retention_obligation": "disabled",
        "minimum.supported.desktop.version": "1.7.0",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "asset-pipeline.enabled": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "installed": true,
        "forcessl": true,
        "default_language": "de",
        "defaultapp": "",
        "maintenance": false,
        "filelocking.enabled": true,
        "loglevel": 2,
        "logfile": "\/media\/DATA\/data\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 10485760,
        "trusted_domains": [
            "steinibox.de",
            "www.steinibox.de",
            "192.168.2.11"
        ],
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "blacklisted_files": [
            "._*",
            ".DS_Store",
            ".DS_STORE",
            ".ds_store",
            "*.vvv",
            "*.cerber",
            "*.desktop",
            "*.tmp",
            "*.aesir",
            "*.odin"
        ],
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 30",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "session_lifetime": 10800,
        "session_keepalive": true,
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 0,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/steinibox.de",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "data-fingerprint": "0fde090144b8dadc7eafe99aeadc6828"
    }
}

</details>

**Are you using external storage, if yes which one:**
local
**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
N.A.

**Comment by RuudschMaHinda** [comment] 2018-10-22 09:30
Possibly related as well #11856

**Comment by MorrisJobke** [comment] 2018-10-24 11:35
Seems to be a duplicate of #10934

**Closed by MorrisJobke** 2018-10-24 11:35 UTC
Labels: 0. Needs triage, bug, feature: global scale, medium
