### ISSUE TITLE
Changing master password invalidates all client passwords: Add hint

### ISSUE THREAD

**Issue by ThomasLeister** [nextcloud/server#9774] opened 2018-06-07 06:56 UTC
### Steps to reproduce
1. Change master password ("normal" password) for your Nextcloud account
2. Check if clients with separate client password still sync
3. ... won't sync. All client specific passwords are expired.

### Expected behaviour
Expecting other clients to continue working

### Actual behaviour
All the client specific passwords e.g. for DavDroid, Sync clients, ... are not valid any more, but still existing in the web interface (and not marked as expired!). Nextcloud does not give a hint that they won't work any more, and doesn't tell the user that changing the master password will expire all the other passwords.

**If this is intended behavior, there should at least be hint for the user, which tells them that all client specific passwords will be reset.**

---

### Server configuration

**Operating system**: Debian 9 Stretch

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated over time.

**Where did you install Nextcloud from:** Manually.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - sharebymail: 1.3.0
  - spreed: 3.2.2
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_u2f: 1.5.5
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_external
  - files_videoplayer
  - password_policy
  - serverinfo
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.650thz.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.650thz.de",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "asset-pipeline.enabled": true,
        "activity_expire_days": 30
    }
}
```
</details>

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** No.

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Firefox 60.0.1

**Operating system:** Fedora Workstation 28

**Comment by MorrisJobke** [comment] 2018-06-07 09:19
Duplicate of #2581

**Closed by MorrisJobke** 2018-06-07 09:19 UTC
