### ISSUE TITLE
After update from 13 to 14, I get internal server error

### ISSUE THREAD

**Issue by cipriantudoran** [nextcloud/server#14267] opened 2019-02-18 11:35 UTC
Hello!

I updated via web, from 13.0.6 to 14.0.7. After the update, I get "Internal server error" and in the log I have these entries:

```
{"reqId":"9UfFU3n0JCgmtcoBbVVr","level":3,"time":"2019-02-18T11:14:19+00:00","remoteAddr":"91.206.82.5","user":"--","app":"index","method":"GET","url":"\/","message":{"Exception":"Error","Message":"Class 'OCP\\Config' not found","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/files_reader\/lib\/Hooks.php","line":41,"function":"get","class":"OCA\\Files_Reader\\Config","type":"::","args":["epub_enable","true"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/hook.php","line":106,"function":"announce_settings","class":"OCA\\Files_Reader\\Hooks","type":"::","args":[{"array":{"oc_debug":"false","oc_isadmin":"false","backendAllowsPasswordConfirmation":"true","oc_dataURL":"false","oc_webroot":"\"\"","oc_appswebroots":"{\"cloud_federation_api\":\"\/apps\/cloud_federation_api\",\"comments\":\"\/apps\/comments\",\"dav\":\"\/apps\/dav\",\"federatedfilesharing\":\"\/apps\/federatedfilesharing\",\"federation\":\"\/apps\/federation\",\"files\":\"\/apps\/files\",\"files_external\":\"\/apps\/files_external\",\"files_pdfviewer\":\"\/apps\/files_pdfviewer\",\"files_reader\":\"\/apps\/files_reader\",\"files_rightclick\":\"\/apps\/files_rightclick\",\"files_sharing\":\"\/apps\/files_sharing\",\"files_texteditor\":\"\/apps\/files_texteditor\",\"files_trashbin\":\"\/apps\/files_trashbin\",\"files_versions\":\"\/apps\/files_versions\",\"files_videoplayer\":\"\/apps\/files_videoplayer\",\"flowupload\":\"\/apps\/flowupload\",\"gallery\":\"\/apps\/gallery\",\"gpxedit\":\"\/apps\/gpxedit\",\"logreader\":\"\/apps\/logreader\",\"lookup_server_connector\":\"\/apps\/lookup_server_connector\",\"nextcloud_announcements\":\"\/apps\/nextcloud_announcements\",\"notifications\":\"\/apps\/notifications\",\"oauth2\":\"\/apps\/oauth2\",\"password_policy\":\"\/apps\/password_policy\",\"previewgenerator\":\"\/apps\/previewgenerator\",\"provisioning_api\":\"\/apps\/provisioning_api\",\"sharebymail\":\"\/apps\/sharebymail\",\"survey_client\":\"\/apps\/survey_client\",\"theming\":\"\/apps\/theming\",\"twofactor_backupcodes\":\"\/apps\/twofactor_backupcodes\",\"updatenotification\":\"\/apps\/updatenotification\",\"workflowengine\":\"\/apps\/workflowengine\"}","datepickerFormatDate":"\"M\\\/d\\\/yy\"","nc_lastLogin":0,"nc_pageLoad":1550488459,"dayNames":"[\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"]","dayNamesShort":"[\"Sun.\",\"Mon.\",\"Tue.\",\"Wed.\",\"Thu.\",\"Fri.\",\"Sat.\"]","dayNamesMin":"[\"Su\",\"Mo\",\"Tu\",\"We\",\"Th\",\"Fr\",\"Sa\"]","monthNames":"[\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"]","monthNamesShort":"[\"Jan.\",\"Feb.\",\"Mar.\",\"Apr.\",\"May.\",\"Jun.\",\"Jul.\",\"Aug.\",\"Sep.\",\"Oct.\",\"Nov.\",\"Dec.\"]","firstDay":"0","oc_config":"{\"session_lifetime\":1440,\"session_keepalive\":true,\"version\":\"14.0.7.1\",\"versionstring\":\"14.0.7\",\"enable_avatars\":true,\"lost_password_link\":null,\"modRewriteWorking\":false,\"sharing.maxAutocompleteResults\":0,\"sharing.minSearchStringLength\":0,\"blacklist_files_regex\":\"\\\\.(part|filepart)$\"}","oc_appconfig":"{\"core\":{\"defaultExpireDateEnabled\":false,\"defaultExpireDate\":null,\"defaultExpireDateEnforced\":null,\"enforcePasswordForPublicLink\":false,\"enableLinkPasswordByDefault\":false,\"sharingDisabledForUser\":false,\"resharingAllowed\":true,\"remoteShareAllowed\":true,\"federatedCloudShareDoc\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=user-sharing-federated\",\"allowGroupSharing\":true},\"files\":{\"max_chunk_size\":10485760}}","oc_defaults":"{\"entity\":\"Nextcloud\",\"name\":\"Nextcloud\",\"title\":\"Nextcloud\",\"baseUrl\":\"https:\\\/\\\/nextcloud.com\",\"syncClientUrl\":\"https:\\\/\\\/nextcloud.com\\\/install\\\/#install-clients\",\"docBaseUrl\":\"https:\\\/\\\/docs.nextcloud.com\",\"docPlaceholderUrl\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=PLACEHOLDER\",\"slogan\":\"a safe home for all your data\",\"logoClaim\":\"\",\"shortFooter\":\"<a href=\\\"https:\\\/\\\/nextcloud.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">Nextcloud<\\\/a> \\u2013 a safe home for all your data\",\"longFooter\":\"<a href=\\\"https:\\\/\\\/nextcloud.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">Nextcloud<\\\/a> \\u2013 a safe home for all your data\",\"folder\":\"\"}","oc_capabilities":"{\"core\":{\"pollinterval\":60,\"webdav-root\":\"remote.php\\\/webdav\"},\"bruteforce\":{\"delay\":0},\"dav\":{\"chunking\":\"1.0\"},\"files_sharing\":{\"api_enabled\":true,\"public\":{\"enabled\":true,\"password\":{\"enforced\":false},\"expire_date\":{\"enabled\":false},\"send_mail\":false,\"upload\":true,\"upload_files_drop\":true},\"resharing\":true,\"user\":{\"send_mail\":false,\"expire_date\":{\"enabled\":true}},\"group_sharing\":true,\"group\":{\"enabled\":true,\"expire_date\":{\"enabled\":true}},\"default_permissions\":31,\"federation\":{\"outgoing\":true,\"incoming\":true,\"expire_date\":{\"enabled\":true}},\"sharebymail\":{\"enabled\":true,\"upload_files_drop\":{\"enabled\":true},\"password\":{\"enabled\":true},\"expire_date\":{\"enabled\":true}}}}"}}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/JSConfigHelper.php","line":280,"function":"emit","class":"OC_Hook","type":"::","args":["\\OCP\\Config","js",{"array":{"oc_debug":"false","oc_isadmin":"false","backendAllowsPasswordConfirmation":"true","oc_dataURL":"false","oc_webroot":"\"\"","oc_appswebroots":"{\"cloud_federation_api\":\"\/apps\/cloud_federation_api\",\"comments\":\"\/apps\/comments\",\"dav\":\"\/apps\/dav\",\"federatedfilesharing\":\"\/apps\/federatedfilesharing\",\"federation\":\"\/apps\/federation\",\"files\":\"\/apps\/files\",\"files_external\":\"\/apps\/files_external\",\"files_pdfviewer\":\"\/apps\/files_pdfviewer\",\"files_reader\":\"\/apps\/files_reader\",\"files_rightclick\":\"\/apps\/files_rightclick\",\"files_sharing\":\"\/apps\/files_sharing\",\"files_texteditor\":\"\/apps\/files_texteditor\",\"files_trashbin\":\"\/apps\/files_trashbin\",\"files_versions\":\"\/apps\/files_versions\",\"files_videoplayer\":\"\/apps\/files_videoplayer\",\"flowupload\":\"\/apps\/flowupload\",\"gallery\":\"\/apps\/gallery\",\"gpxedit\":\"\/apps\/gpxedit\",\"logreader\":\"\/apps\/logreader\",\"lookup_server_connector\":\"\/apps\/lookup_server_connector\",\"nextcloud_announcements\":\"\/apps\/nextcloud_announcements\",\"notifications\":\"\/apps\/notifications\",\"oauth2\":\"\/apps\/oauth2\",\"password_policy\":\"\/apps\/password_policy\",\"previewgenerator\":\"\/apps\/previewgenerator\",\"provisioning_api\":\"\/apps\/provisioning_api\",\"sharebymail\":\"\/apps\/sharebymail\",\"survey_client\":\"\/apps\/survey_client\",\"theming\":\"\/apps\/theming\",\"twofactor_backupcodes\":\"\/apps\/twofactor_backupcodes\",\"updatenotification\":\"\/apps\/updatenotification\",\"workflowengine\":\"\/apps\/workflowengine\"}","datepickerFormatDate":"\"M\\\/d\\\/yy\"","nc_lastLogin":0,"nc_pageLoad":1550488459,"dayNames":"[\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"]","dayNamesShort":"[\"Sun.\",\"Mon.\",\"Tue.\",\"Wed.\",\"Thu.\",\"Fri.\",\"Sat.\"]","dayNamesMin":"[\"Su\",\"Mo\",\"Tu\",\"We\",\"Th\",\"Fr\",\"Sa\"]","monthNames":"[\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"]","monthNamesShort":"[\"Jan.\",\"Feb.\",\"Mar.\",\"Apr.\",\"May.\",\"Jun.\",\"Jul.\",\"Aug.\",\"Sep.\",\"Oct.\",\"Nov.\",\"Dec.\"]","firstDay":"0","oc_config":"{\"session_lifetime\":1440,\"session_keepalive\":true,\"version\":\"14.0.7.1\",\"versionstring\":\"14.0.7\",\"enable_avatars\":true,\"lost_password_link\":null,\"modRewriteWorking\":false,\"sharing.maxAutocompleteResults\":0,\"sharing.minSearchStringLength\":0,\"blacklist_files_regex\":\"\\\\.(part|filepart)$\"}","oc_appconfig":"{\"core\":{\"defaultExpireDateEnabled\":false,\"defaultExpireDate\":null,\"defaultExpireDateEnforced\":null,\"enforcePasswordForPublicLink\":false,\"enableLinkPasswordByDefault\":false,\"sharingDisabledForUser\":false,\"resharingAllowed\":true,\"remoteShareAllowed\":true,\"federatedCloudShareDoc\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=user-sharing-federated\",\"allowGroupSharing\":true},\"files\":{\"max_chunk_size\":10485760}}","oc_defaults":"{\"entity\":\"Nextcloud\",\"name\":\"Nextcloud\",\"title\":\"Nextcloud\",\"baseUrl\":\"https:\\\/\\\/nextcloud.com\",\"syncClientUrl\":\"https:\\\/\\\/nextcloud.com\\\/install\\\/#install-clients\",\"docBaseUrl\":\"https:\\\/\\\/docs.nextcloud.com\",\"docPlaceholderUrl\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/go.php?to=PLACEHOLDER\",\"slogan\":\"a safe home for all your data\",\"logoClaim\":\"\",\"shortFooter\":\"<a href=\\\"https:\\\/\\\/nextcloud.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">Nextcloud<\\\/a> \\u2013 a safe home for all your data\",\"longFooter\":\"<a href=\\\"https:\\\/\\\/nextcloud.com\\\" target=\\\"_blank\\\" rel=\\\"noreferrer noopener\\\" class=\\\"entity-name\\\">Nextcloud<\\\/a> \\u2013 a safe home for all your data\",\"folder\":\"\"}","oc_capabilities":"{\"core\":{\"pollinterval\":60,\"webdav-root\":\"remote.php\\\/webdav\"},\"bruteforce\":{\"delay\":0},\"dav\":{\"chunking\":\"1.0\"},\"files_sharing\":{\"api_enabled\":true,\"public\":{\"enabled\":true,\"password\":{\"enforced\":false},\"expire_date\":{\"enabled\":false},\"send_mail\":false,\"upload\":true,\"upload_files_drop\":true},\"resharing\":true,\"user\":{\"send_mail\":false,\"expire_date\":{\"enabled\":true}},\"group_sharing\":true,\"group\":{\"enabled\":true,\"expire_date\":{\"enabled\":true}},\"default_permissions\":31,\"federation\":{\"outgoing\":true,\"incoming\":true,\"expire_date\":{\"enabled\":true}},\"sharebymail\":{\"enabled\":true,\"upload_files_drop\":{\"enabled\":true},\"password\":{\"enabled\":true},\"expire_date\":{\"enabled\":true}}}}"}}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php","line":176,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":210,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["guest",""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":399,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":942,"function":"printUpgradePage","class":"OC","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/files_reader\/lib\/config.php","Line":28,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"13.0.6.1"}
{"reqId":"9UfFU3n0JCgmtcoBbVVr","level":3,"time":"2019-02-18T11:14:19+00:00","remoteAddr":"91.206.82.5","user":"--","app":"no app in context","method":"GET","url":"\/","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"theming.Theming.getImage\" as such route does not exist.","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":337,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"2"},1]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"2"},false]},{"file":"\/var\/www\/nextcloud\/lib\/private\/URLGenerator.php","line":79,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"2"}]},{"file":"\/var\/www\/nextcloud\/apps\/theming\/lib\/ThemingDefaults.php","line":227,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"2"}]},{"file":"\/var\/www\/nextcloud\/lib\/public\/Defaults.php","line":187,"function":"getLogo","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[true]},{"file":"\/var\/www\/nextcloud\/core\/templates\/layout.guest.php","line":34,"function":"getLogo","class":"OCP\\Defaults","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":179,"args":["\/var\/www\/nextcloud\/core\/templates\/layout.guest.php"],"function":"include"},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":151,"function":"load","class":"OC\\Template\\Base","type":"->","args":["\/var\/www\/nextcloud\/core\/templates\/layout.guest.php",null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":207,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":238,"function":"fetchPage","class":"OC_Template","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":359,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":83,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[{"__class__":"Error"},500]}],"File":"\/var\/www\/nextcloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":113,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"13.0.6.1"}
```

### Steps to reproduce
1. Perform the update
2. Access any nexcloud page
3.

### Expected behaviour
Normal running

### Actual behaviour
Internal server error

### Server configuration

**Operating system**: Ubuntu 16.04.4

**Web server:** Apache

**Database:** mySQL

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 14.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** update from 13.0.6

**Where did you install Nextcloud from:** via nextcloud admin page

**Signing status:**
<details>
<summary>Signing status</summary>
Internal server error
</details>

**List of activated apps:**
<details>
<summary>App list</summary>Enabled:
  - cloud_federation_api: true
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_reader: 1.2.3
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - flowupload: 0.0.8
  - gallery: 18.0.0
  - gpxedit: 0.0.8
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - accessibility
  - activity
  - admin_audit
  - drawio
  - encryption
  - files_external_gdrive
  - files_frommail
  - files_inotify
  - firstrunwizard
  - metadata
  - richdocuments
  - serverinfo
  - support
  - systemtags
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.doihoinari.ro",
            "storage.doihoinari.ro",
            "z.css3.ro"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/nextcloud.doihoinari.ro",
        "dbtype": "mysql",
        "version": "13.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379"
        },
        "activity_expire_days": 30,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\OpenDocument"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment] 2019-06-04 10:04
Caused by the files_reader app.
Closing as not related to nextcloud server

**Closed by skjnldsv** 2019-06-04 10:04 UTC
Labels: 0. Needs triage, bug, feature: install and update
