### ISSUE TITLE
Enhancement: Make updater more tolerant

### ISSUE THREAD

**Issue by rgr101** [nextcloud/server#8952] opened 2018-03-22 18:35 UTC
There are installations with a good reason for additional files in root - e.g. adding the OPcache settings in php.ini on shared hosts without access to Apache settings.

It's annoying that the php.ini has to be removed first before the updater is willing to work.
On the other hand, security restrictions are fully accepted. 

Maybe a config parameter could be a trade-off?
  
### Steps to reproduce
1. Place an additional file in the Nextcloud root directory
2. Start the updater

### Expected behaviour
Update process is running through

### Actual behaviour
The updater refuses working unless the additional file is removed

### Server version
Any <= 13.0.0

**Comment by MorrisJobke** [comment] 2018-04-18 22:36
Duplicate of https://github.com/nextcloud/updater/issues/68

**Closed by MorrisJobke** 2018-04-18 22:36 UTC
