### ISSUE TITLE
SSO (rocketchat) required to grant access to their Nextcloud account on each login

### ISSUE THREAD

**Issue by mbh-dev** [nextcloud/server#12377] opened 2018-11-09 13:29 UTC
### Steps to reproduce
1. Login to Rocket Chat via Nextcloud using  OAuth
2. Grant Access
3. Logout of Rocket Chat
4. Have to regrant access on logging into Rocket Chat via Nextcloud OAuth

### Expected behaviour
User should only be required to grant access to their Nextcloud account once

### Actual behaviour
Each time a user logs into Rocket chat they are required to grant access to their Nextcloud account each time

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 

**Database:** MySql

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Source

```
Login as admin user into your Nextcloud and access 
No Errors have been found
```
Operating system:** Windows 10

**Comment by Elfanar** [comment] 2019-01-30 10:52
No information how to authenticate nextcloud users on rocket chat seamlessly ?

**Comment by cjhille** [comment] 2020-02-10 02:28
Seeing the same issue. Nextcloud creates a new "app-password" for every login.

**Comment by skjnldsv** [comment] 2020-04-10 08:13
@ChristophWurst @rullzer for app token

**Comment by cjhille** [comment] 2020-05-10 09:55
Since #13182 was closed, it would be awesome if this remained open.

**Comment by cjhille** [comment] 2020-06-09 14:45
AFAIK still an issue with Nextcloud 19.

**Comment by rullzer** [comment] 2020-07-09 17:23
So this then most likely is an issue in rocket chat not reusing the token... other oauth providers work just fine. Let me close this unless somebody can provide more info.

**Comment by derspotter** [comment] 2021-01-14 09:36
The issue still persists...

**Comment by AlfredoCubitos** [comment] 2021-09-15 07:45
I can confirm that this issue still exists.
I have a plain clear installation, nothing special. Only few users.
This error is very annoying!
I do not understand why for every login session with the same login name a new entry is created instead of updating the existing session entries?
Please reopen this bug and fix it.

**Comment by ChristophWurst** [comment] 2021-09-15 09:48
I'm happy to reopen. But Nextcloud is a community project.

> reopen this bug and fix it

We're happy to help you with your fixes and getting them merged. Please feel free to dig into the code and fix the issue yourself if you can or hire someone who can do this for you :v:

**Comment by AlfredoCubitos** [comment] 2021-09-15 14:41
I have made some tests, and I came to the conclusion that this may not really a server problem, but rather a desktop/mobile client problem.
@ChristophWurst : do you know if  the cron.php cleans up  also the oc_authtoken table?
If this is so, this could also be cronjob problem.

**Comment by ChristophWurst** [comment] 2021-09-20 12:57
Yes, ``\OC\Authentication\Token\DefaultTokenCleanupJob`` takes care of old session tokens.

**Comment by AlfredoCubitos** [comment] 2021-09-20 17:30
Ok, it seems that the cronjob does not work correctly.
I made several changes to cronjob option but always I get an error message like this `Some jobs didn’t execute since x days ago. `
So I called cron.php manually and it returns `success` but the old sessions  in the `oc_authtoken ` were not deleted.

Know I am at the end with my wisdom. I do not know where to look for the error.
@ChristophWurst : do you have any idea?

**Comment by ChristophWurst** [comment] 2021-09-20 17:34
Let's put the cron problem/questions on https://help.nextcloud.com ;)

**Comment by AlfredoCubitos** [comment] 2021-10-02 12:44
@ChristophWurst I think you can close this issue here.
I found out that entries with set `remember` = 1 are expiring after 15 days, this may lead to huge entries in oc_authtoken on sites with heavy  traffic.

Do you know where this attribute remember=1 is set and why?

**Comment by ChristophWurst** [comment] 2021-11-02 09:50
> Do you know where this attribute remember=1 is set and why?

At `\OC\Authentication\Login\CreateSessionTokenCommand::process`

**Comment by cjhille** [comment] 2021-12-16 12:25
noooooooo @nextcloud-bot  bad bot ... still is still an issue :/

**Comment by szaimen** [comment] 2023-01-09 12:04
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:37 UTC
Labels: bug, needs info, 0. Needs triage
