### ISSUE TITLE
InvalidArgumentException while updating to Update to 18.0.11

### ISSUE THREAD

**Issue by tinosecolodge** [nextcloud/server#24427] opened 2020-11-28 07:59 UTC
Hi,
i get the below Error Message while updating to 18.0.11:
Preparing update:
_> Set log level to debug
> Turned on maintenance mode
> Repair step: Repair MySQL collation
> Repair info: All tables already have the correct collation -> nothing to do
> Repair step: Repair SQLite autoincrement
> Repair step: Copy data from accounts table when migrating from ownCloud
> Repair step: Drop account terms table when migrating from ownCloud
> Updating database schema
> Updated database
> InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.
> The update was unsuccessful. Please report this issue to the Nextcloud community._

Does any body know how to fix this? Or at least return to the last Version on the server (getting it out of maintenance mode)?

best regards 
Nico

**Comment by kesselb** [comment] 2020-11-28 10:53
Duplicate of https://github.com/nextcloud/server/issues/23174

**Closed by kesselb** 2020-11-28 10:53 UTC
