### ISSUE TITLE
Favorites are lost every time I update my instance

### ISSUE THREAD

**Issue by dienteperro** [nextcloud/server#7615] opened 2017-12-23 01:00 UTC
### Steps to reproduce
1. Install update, from the updater.
2. Click on the favorites link.
3. There is no Favorites in the list.

### Expected behaviour
Favorites should not disappear after an update.

### Actual behaviour
Favorites disappear after an update.

### Server configuration

**Operating system**: Linux hostname 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:** Apache 2.4.18-2ubuntu3.5 amd64

**Database:** PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.22

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.3. This issue had happen every time I updated, even in 11.*

**Where did you install Nextcloud from:** official Nextcloud .zip file

**Signing status:** No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.3
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_clipboard: 0.6.4
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.1
  - password_policy: 1.2.2
  - previewgenerator: 1.0.8
  - provisioning_api: 1.2.0
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - telephoneprovider: 1.0.1
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/data\/nc\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Havana",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "user_backends": [
            {
                "class": "OC_User_SMB",
                "arguments": [
                    "localhost",
                    "***REMOVED SENSITIVE VALUE***",
                    "***REMOVED SENSITIVE VALUE***"
                ]
            }
        ],
        "auth.bruteforce.protection.enabled": true,
        "enable_previews": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtptimeout": 60,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "log_rotate_size": 10485760,
        "updater.release.channel": "stable",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local, ftp

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Firefox 57.0.1 (64-bit)

**Operating system:** macOS 10.12.6

**Comment by MorrisJobke** [comment] 2018-01-02 10:48
cc @nickvergessen @rullzer @blizzz @icewind1991 Do you have an idea what happens here?

**Comment by blizzz** [comment] 2018-01-02 13:50
No, and didn't happen for me. Since the info is stored in the DB, it needs some manipulation to disappear.

@dienteperro are shares or comments, for instance, preserved?

**Comment by MorrisJobke** [comment] 2018-01-22 17:08
I'm closing this for now. Once you could provide more information we could reopen the ticket. Thanks

**Closed by MorrisJobke** 2018-01-22 17:08 UTC
Labels: needs info

**Comment by dienteperro** [comment] 2018-01-22 22:57
I'll try to reproduce the issue in a different VM/server and be back. Thanks

**Comment by lephisto** [comment] 2018-04-30 10:04
I also has this Issue today while upting from 11.0.5 to 12.0.7. It's reproduceable: Favorites of local users are transferred correctly, favorites of external Users (IMAP in my Case) have been lost. In this case it was easy to fix just by importing vcategory and vcategory_to_object table from the 11x into the 12x Database, since the DML hasn't changed. It would be cooler if the Updater would respect users_external. Someone should re-open this issue.

**Comment by nickvergessen** [comment] 2018-05-03 07:55
I guess the problem is, that your user backend is not registered when running the repair steps:
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Repair/CleanTags.php#L103-L105

The app type seems to be right:
https://github.com/nextcloud/apps/blob/master/user_external/appinfo/info.xml#L19-L22

So I guess the app is disabled, because the version doesn't match atm, in that case https://github.com/nextcloud/server/pull/8380 would help

**Comment by lephisto** [comment] 2020-01-13 02:30
Issue isn't fixed!

**Comment by tobyX** [comment] 2020-11-13 15:26
I'm also affected by this and I also use users_external.

**Comment by tiltroom** [comment] 2023-07-04 09:12
This issue still persists

**Comment by tiltroom** [comment] 2024-08-09 15:37
Issue still here, almost 7 years later.
