### ISSUE TITLE
problem for install with ionos shared hosting

### ISSUE THREAD

**Issue by macrofsky** [nextcloud/server#28891] opened 2021-09-19 15:45 UTC
Hi,
I have a problem with version > 22
when I try to install nextcloud on a shared hosting, I complete informations for mysql and all informations, as usual, but the page I rediriged to https://index.php/core/apps/recommended, without my domain.

it already did with v21, but by correcting the address bar it fell back on the installation page of recommended apps.
with the V22, I have the message : 

'Internal Server Error
The server is unable to perform your request.

If this happens again, please send the technical details below to the server administrator.

The server log file can provide more information.'

I've called IONOS but 0 solution...
thanks for advance

**Comment by szaimen** [comment] 2021-09-19 15:48
Duplicate of https://github.com/nextcloud/server/issues/27575

**Closed by szaimen** 2021-09-19 15:48 UTC
