### ISSUE TITLE
Update 15.0.4 -> 16.0 - admin cannot change user passwords

### ISSUE THREAD

**Issue by MikeZuluUSA** [nextcloud/server#15239] opened 2019-04-25 21:01 UTC
After upgrading to 16.0 I cannot change the user passwords through the admin - user page anymore.
Hint pops up: Changing the password is disabled because the master key is disabled.
I do NOT use server side encryption. Default encryption module app is enabled.

Creating a new user works well including the password field.
The existing user were displayed with their information but password field is not active, no click in or select field.

It worked before!
Aloha!

**Comment by pongraczi** [comment] 2019-06-12 22:15
+1
```
php  occ  encryption:status
  - enabled: false
  - defaultModule: OC_DEFAULT_MODULE
```
![Kijelölés_060](https://user-images.githubusercontent.com/5891983/59389970-28b03180-8d70-11e9-9cce-a2cdb4647e4f.png)

As I remember (and as my records contain) I have recovery key setup.

**Comment by the-sane** [comment] 2019-08-16 02:34
Some information in this discussion: https://github.com/nextcloud/server/issues/11212
and this pull: https://github.com/nextcloud/server/pull/13172

It looks like changes were made to v16 to resolve some other issues.  If you're **absolutely certain** that no files are currently encrypted and server-side encryption is not enabled, then disabling the default encryption module is supposed to get rid of that message.

**Comment by skjnldsv** [comment] 2020-09-09 11:52
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-09-09 11:52 UTC
Labels: 0. Needs triage, bug
