### ISSUE TITLE
The target user is not ready to accept files. The user has at least to be logged in once.

### ISSUE THREAD

**Issue by IamAliBaba** [nextcloud/server#9295] opened 2018-04-25 07:14 UTC
I'm trying to transfer files from one user to another and getting this.

**root@cloud:/var/www/html/nextcloud# sudo -u www-data php occ files:transfer-ownership d8c2aeb0-d68d-1037-8174-bd06cd63325f admin
The target user is not ready to accept files. The user has at least to be logged in once.**

In the case this 2 user are currently logged in.

Please advise .
Thanks,
Ali

**Comment by MorrisJobke** [comment] 2018-05-31 12:19
@rullzer @icewind1991 Should this be covered or is this a new feature?

**Comment by MorrisJobke** [comment] 2018-05-31 14:59
Let's close this as duplicate of #9601

**Closed by MorrisJobke** 2018-05-31 14:59 UTC
Labels: enhancement, feature: files, feature: filesystem
