### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by gregecslo** [nextcloud/server#16286] opened 2019-07-08 07:20 UTC
In 16.0.2 when you drag and drop file or folder you get permission denied.
With "+" sign it works as intended.

**Comment by Nils160988** [comment] 2019-07-08 07:40
Duplicate of #16238?

**Comment by gregecslo** [comment] 2019-07-08 07:45
Yes sorry for double post.

________________________________

**Closed** 2019-07-08 10:05 UTC
