### ISSUE TITLE
Deprecated event type for `OCP\IDBConnection::*`

### ISSUE THREAD

**Issue by BenS89** [nextcloud/server#24380] opened 2020-11-25 21:18 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Upgrade from Nexcloud 19.0.5 to 20.0.2
2. Take a look into the logs

**Expected behavior:** no deprecation logs on info level

**Current behavior:** Multiple deprecation logs on info level

`Deprecated event type for OCA\Files::loadAdditionalScripts: Symfony\Component\EventDispatcher\GenericEvent is used`

`Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[],"*logger":null}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null`

`Deprecated event type for OCP\IDBConnection::CHECK_MISSING_PRIMARY_KEYS: Symfony\Component\EventDispatcher\GenericEvent is used`

`Deprecated event type for OCP\IDBConnection::CHECK_MISSING_INDEXES: Symfony\Component\EventDispatcher\GenericEvent is used`

`Deprecated event type for OCP\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\Component\EventDispatcher\GenericEvent is used`

**Comment by kesselb** [comment] 2020-11-26 08:12
cc @ChristophWurst 

That's on purpose right? (https://github.com/nextcloud/server/pull/18966#issuecomment-575893571)

**Comment by ChristophWurst** [comment] 2020-11-26 08:26
yes

**Comment by ChristophWurst** [comment] 2020-11-26 08:26
the updater switches to debug level logs, hence this shows.

**Comment by kesselb** [comment] 2020-11-26 08:28
Log level for `Deprecated event type for {name}: {class} is used` is info.

**Comment by kesselb** [comment] 2020-11-26 08:30
I guess we are not done with migrating everything yet. Shall we lower the log level to debug for now? (as we already did for 18).

**Comment by ChristophWurst** [comment] 2020-11-26 08:47
ah. yeah, maybe. but also finally migrate those things :wink:

**Comment by BenS89** [comment] 2020-11-28 17:57
What´s the plan now? The log flooding on info level is indeed not optimal. Thanks for your feedback.

**Comment by stefanbenten** [comment] 2020-12-26 17:43
I would also like to push this further. This is quite distracting from actual interesting log lines.

**Comment by ChristophWurst** [comment] 2020-12-28 09:11
we have to migrate the code that uses the old events

> I would also like to push this further.

I can give you pointers on where to look. But just open your IDE and see where the constant is used. Then you can replace the emitting and listening parts with a new event.

**Comment by User65481** [comment] 2021-01-22 10:35
Any news on this? We're on 20.0.5.2 and have the same issue.

**Comment by ChristophWurst** [comment] 2021-01-22 10:57
It's not fixed yet.

**Comment by User65481** [comment] 2021-02-04 08:08
Any eta or any way on how we could help on this issue?
4 of our 5 most logged messages are caused by this bug:
![Bildschirmfoto 2021-02-04 um 09 02 16](https://user-images.githubusercontent.com/77266803/106862992-31cddf00-66c8-11eb-8e58-5211c7b47b99.png)

(Side note: the other message, bind failed, is caused by another bug already reported on the android repo. 5 of 5 top messages are caused by bugs right now, making it more and more difficult to check logs and thus ensuring a stable environment)

**Comment by b-pfl** [comment] 2021-02-11 19:14
> Any eta or any way on how we could help on this issue?
> 4 of our 5 most logged messages are caused by this bug:

I agree, monitoring the log file is quite annoying at the moment, given that these messages bloat the log file.

**Comment by User65481** [comment] 2021-03-01 09:48
Just a quick update, we're on 20.0.8.1 now and unfortunately the problem still exists.

**Comment by User65481** [comment] 2021-03-01 14:07
Just saw that a lot of comments got hidden. Usually comments get hidden because they are "off-topic, outdated, or resolved" - is there anything we can do to provide you with required help or support for this issue?

**Comment by kesselb** [comment] 2021-03-01 16:12
> is there anything we can do to provide you with required help or additional details (logfiles, config) for this issue?

No. I marked some comments as duplicate. Also added **how to use GitHub** to the first post.

> Just a quick update, we're on 20.0.8.1 now and unfortunately the problem still exists.

The problem is still there and the status of this issue is open. I think there could be a connection. 

> I agree, monitoring the log file is quite annoying at the moment, given that these messages bloat the log file.

True. Still the comment does not add any value to this issue. It only sends a notification to everyone subscribed. Your best option is to write a filter for your log management. And send a pull request of course ;)

**Comment by LordSimal** [comment] 2021-04-03 09:23
FYI: I get the same log entry when I try to remove a contact from a group inside the contacts app (on Nextcloud 20.0.8 and Contacts 3.5.1)
I will create an issue there later with the whole debug info I can give

**Comment by LordSimal** [comment] 2021-04-03 10:30
As far as I have debugged this log entry it comes down to the following:

- The message is being logged by `lib/private/EventDispatcher/GenericEventWrapper.php` function `log()`
https://github.com/nextcloud/server/blob/master/lib/private/EventDispatcher/GenericEventWrapper.php#L60

- So basically we only get in there when some code uses the `GenericEventWrapper` which I only found in `lib/private/EventDispatcher/SymfonyAdapter.php` and more specific in the `dispatch()` function
https://github.com/nextcloud/server/blob/master/lib/private/EventDispatcher/SymfonyAdapter.php#L106

- BUT in there the `GenericEventWrapper` is only used if the dispatched event is of the type `OC\EventDispatcher\GenericEvent` and not `OC\EventDispatcher\Event` which are checked before in the same function
https://github.com/nextcloud/server/blob/master/lib/private/EventDispatcher/SymfonyAdapter.php#L101

So now I looked for all occurrences where a `new GenericEvent(` is present in the code and oh boy, there are many.
https://github.com/nextcloud/server/search?q=new+GenericEvent%28

And this is just the the nextcloud core, not to mention all the apps that also need to adjust to the new event system.

**Comment by GAS85** [comment] 2021-04-22 06:37
Meanwhile my Log is full of similar entries and I "move" them to debug by command (from [Stackoverflow](https://stackoverflow.com/a/49433567)) in cron:
```
sed -i '/Deprecated event type/{s/"level":1/"level":0/}' nextcloud.log
```

**Comment by TheColin21** [comment] 2021-07-01 11:11
Deprecated event type for OCP\IPreview:PreviewRequested: Symfony\Component\EventDispatcher\GenericEvent is used
I get this info level log entry in my 21.0.3 installation

**Comment by kokotko1337** [comment] 2021-07-04 06:50
Upgraded to 20 form 19 and got those ...

<html>
<body>


Deprecated event type for OCA\Files::loadAdditionalScripts: Symfony\Component\EventDispatcher\GenericEvent is used |  
-- | --


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by idjmic** [comment] 2021-07-05 08:08
Want to add, this affects my log mostly when accessing the app on my device.

**Comment by szaimen** [comment] 2021-08-08 14:22
I suppose this is still happening on NC21.0.4?

**Comment by haghighi-ahmad** [comment] 2021-08-31 22:26
Same log message on NC22.1.1

**Comment by ChristophWurst** [comment] 2021-09-01 06:23
The ticket is still open -> nobody fixed this

Until then please just add your :+1: to the original report.

**Comment by gleanlux** [comment] 2021-09-04 22:01
Hello!
My Nextcloud server is crashed today, because the log file is growned up 9GB! :D
I delete the log, and restart fine, but i see the log and found same entry:

`Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/cloud/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*logger":null,"*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[]}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null`

and 

`Deprecated event type for OCP\IPreview:PreviewRequested: Symfony\Component\EventDispatcher\GenericEvent is used`

New entries are created each time the mobile app is updated.
Any ideas maybe?
Nextcloud 21.0.1

**Comment by ChristophWurst** [comment] 2021-09-05 06:04
This still hasn't been fixed. Just add your 👍 to the original post and don't comment.

**Comment by bkyceh** [comment] 2021-11-12 11:54
Nextcloud 22.2.1

Info | no app in context | Deprecated event type for OCA\Files::loadAdditionalScripts:Symfony\Component\EventDispatcher\GenericEvent is used

Any News ?

**Comment by ChristophWurst** [comment] 2021-11-12 15:31
Well, the issue is still open. So this hasn't been addressed :wink:

**Comment by elgorro** [comment] 2021-12-16 12:34
Workaround is to set `'loglevel' => 2,` in the `config.php`, which is default-value. (With previous setting "0"=Debug it slowed down like crazy!) #18331

**Comment by LordSimal** [comment] 2021-12-16 13:03
Indeed "old" installations of nextcloud have a default loglevel of 0 set in their auto-generated `config/config.php` (at least mine had)
Maybe setting this to 2 helps to mitigate that problem but I can also say that Nextcloud 23 doesn't have that issue anymore.

**Comment by Hudratronium** [comment] 2022-02-07 22:55
@LordSimal 

This is something i can not confirm at all. Was takeing a look into my setup here regarding audit logging. As soon as i lowered the loglevel to "1" - as advised in the docs - for usage of the admin audit log i got these in my logs....

**Comment by brianjmurrell** [comment] 2022-02-08 03:13
IMHO deprecation messages are completely inappropriate at INFO level.  These are developer targeted messages, not end-user targeted messages.  INFO is for end-users.

**Comment by johanvandegriff** [comment] 2022-03-11 07:54
As a quick hack to filter your logs, you can use some javascript in the browser console to remove elements you aren't interested in and/or only see the ones you care about.
Hit F12, select Console, and paste this in (after reviewing the code - never paste in unknown code from strangers on the internet, except me of course 😇):

```javascript
window.setInterval(() => {
  Array.from(document.getElementsByTagName("tr"))
    .filter(log => log.innerText.includes("Deprecated"))
    .forEach(log => log.parentElement.removeChild(log));
}, 1000);
```

Every second, it finds all the "tr" elements (table rows) and deletes the ones that contain "Deprecated" in the row's text. Modify as you please to filter in different ways, for example you can search for only logs that contain "http" by changing the "filter" condition:
```javascript
...
    .filter(log => !log.innerText.includes("http"))
...
```
You will have to reload the page to get the removed items back and turn off the filter. (clearInterval could be helpful here, but that's beyond the scope of this hacky script.)

**Comment by arnowelzel** [comment] 2022-05-17 12:21
JFTR: this message also appears in NC 24.0.0 which was upgraded from NC 23.0.4

**Comment by alireza-salehi** [comment] 2022-10-17 09:38
also in 24.0.6 ,

**Comment by rschoene** [comment] 2022-12-07 22:54
And 24.0.7

**Comment by ChristophWurst** [comment] 2023-04-18 06:59
This is not even a bug.

**Comment by LordSimal** [comment] 2023-04-19 09:19
As said in https://github.com/nextcloud/server/issues/24380#issuecomment-995796237 I haven't had this issue since upgrading to version 23+ (currently on 26 with PHP 8.1 and this is not a problem)
@remidebette can you specify which regression you detected? Which version did you use previously? What are you using now?

**Comment by remidebette** [comment] 2023-04-19 09:42
I will upgrade and check again

**Comment by ChristophWurst** [comment] 2023-04-19 09:57
Please test and review https://github.com/nextcloud/server/pull/37816

**Comment by joshtrichards** [comment] 2023-07-30 13:08
I think we can safely close this Issue out, no?

With the merging of #37816 (and its release in NC27) and the quietness of this issue thread since...

**Closed** 2023-08-24 16:28 UTC
Labels: needs info, 0. Needs triage, technical debt, feature: logging
