### ISSUE TITLE
Improvement - sharing files via public link: showing remote IP

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#9923] opened 2018-06-19 17:25 UTC
Could it be possible, as an improvement to sharing a file via a public link, to have the remote IP showing in the files/activities

as you can see, we have actually have `downloaded via public link x minutes ago`. Would be nice to have an IP too.
![shareimp1](https://user-images.githubusercontent.com/8655165/41613615-67373e92-73f6-11e8-982e-abd504fbe072.JPG)

**Comment by stratege1401** [comment] 2018-06-19 18:16
Sit tight, have a cigar, watch TV ... those "triage" robot are so bad, slow, illogic than i wonder why people continue to use them.

**Comment by MorrisJobke** [comment] 2018-06-19 19:15
> Sit tight, have a cigar, watch TV ... those "triage" robot are so bad, slow, illogic than i wonder why people continue to use them.

Sorry for the mess. We are in the process of setting it up.

**Comment by MorrisJobke** [comment] 2018-06-19 19:18
@nextcloud/security @nickvergessen Does it make sense to log this? I'm uncertain if this would maybe have security or privacy implications?

**Comment by MorrisJobke** [comment] 2018-06-19 19:18
cc @nextcloud/sharing @schiessle

**Comment by stratege1401** [comment] 2018-06-19 19:19
> Sorry for the mess. We are in the process of setting it up.
Don't worry, just kidding, but those robot IA will never do a correct job with your repo.
There is so many foreigners like me trying to "speak" a correct English ... how could a robot asses the idea behing a badly written statements ?!!

**Comment by MorrisJobke** [comment] 2018-06-19 19:21
> Don't worry, just kidding, but those robot IA will never do a correct job with your repo.
> There is so many foreigners like me trying to "speak" a correct English ... how could a robot asses the idea behing a badly written statements ?!!

We are trying it out and see if it help or not. Just want to give it some try. Having at least a rough categorization helps to triage the huge amount of incoming tickets being distributed across the team.

**Comment by go2sh** [comment] 2018-06-19 20:09
Be aware, that showing the IP means actually storing the IP and thus might conflict with the DSGVO/GDPR.

**Comment by stratege1401** [comment] 2018-06-20 22:49
European GDPR art 25, art 33, art 37 with concept of "Privacy by design" and " explicit and positive consent" cover the IP logging.
Art 22 with concept of "privacy by using" authorize any log if:
- data security is overseen by a DPO (Data Protection Officer) clearly identify with a direct contact.
- data deletion can be managed by user when deleting account
- In case a data breach, DPO action is pro-active and users are warned.

**Comment by go2sh** [comment] 2018-06-21 08:03
It's not about the user sharing the file. It's about the IP downloading the file, which will be stored and shown to other users. And thus prior to storing, you need to give the user the privacy information, depending on your reason to store, get the consent from the user, have a solution to transfer the stored data to the user and the delete the data, when requested or when then storing period is over.

Everything above (excluding the consent) should be supported by nextcloud in order to include this feature. Also this feature should be opt in.

**Comment by stratege1401** [comment] 2018-06-21 08:57
In my mind, the logging is admin reserved.
As the server admin is, most of the time the DPO, it respect the GDPR.
The only little thing needed also is a write or rewrite of the users disclaimer.

**Comment by nickvergessen** [comment] 2018-07-02 13:51
Yeah it's request from time to time, I don't feel like doing this, but I understand that people want to know if different people  downloaded, or just one.

However since GDPR I'm even more sceptical.
Anyway, duplicate of https://github.com/nextcloud/activity/issues/98

**Closed by nickvergessen** 2018-07-02 13:51 UTC
Labels: 0. Needs triage, enhancement, feature: activity and notification

**Comment by xg590** [comment] 2020-09-26 16:32
If you do want to dig out who has accessed a specific file, you certainly can without bothering nextcloud. You know nextcloud is just an app running on the webserver platform (apache2 for example) and the webserver retains file access log anyhow.  
So the procedures are: 
1) know the link to shared file, for example, https://your.domain.name/index.php/s/s0meRand0mHa5h5tring. 
2) grep s0meRand0mHa5h5tring in /var/log/apache2/access.log
