### ISSUE TITLE
Sabre\VObject\ParseException: Invalid Mimedir file

### ISSUE THREAD

**Issue by tapete** [nextcloud/server#8827] opened 2018-03-14 22:11 UTC
### Steps to reproduce
1. Fresh install nextcloud 13.0.0 
2. Install Desktop client 2.3.3 to desktop A
2. Sync Data From desktop A to nextcloud
3. Install Desktop client 2.3.3 to desktop B
4. Sync Data from nextcloud to desktop B

### Expected behaviour
Desktop A and desktop B should be synced.

### Actual behaviour
Server Error in step 4.

### Server configuration

**Operating system**: 
Ubuntu 16.04.3

**Web server:**
apache 2.4.18

**Database:**
MySQL 5.7.21

**PHP version:**
7.0.22

**Nextcloud version:** (see Nextcloud admin page)
13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
downloaded zip file from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - audioplayer: 2.2.5
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - radio: 0.6.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:REMOVED",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
not used

**Operating system:**
Windows 8

#### Web server error log
<details>
<summary>Web server error log</summary>
no errors in apache error log
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"OsxWLtSNyFjP2xvE8fuu","level":4,"time":"2018-03-14T20:52:59+00:00","remoteAddr":"88.130.91.85","user":"REMOVED","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/REMOVED\/Eigene%20Dateien\/Kontakte\/Busse%20Wbf.vcf","message":"Exception: {\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Message\":\"Invalid Mimedir file. Line starting at 7 did not follow iCalendar\\\/vCard conventions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(234): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('=C3=9Fe 3, 1906...')\\n#1 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(181): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('=C3=9Fe 3, 1906...')\\n#2 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(89): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#3 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(46): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCARD\\\\r\\\\nVE...', 0)\\n#4 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(857): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCARD\\\\r\\\\nVE...')\\n#5 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(782): Sabre\\\\CardDAV\\\\Plugin->convertVCard('BEGIN:VCARD\\\\r\\\\nVE...', 'vcard3')\\n#6 [internal function]: Sabre\\\\CardDAV\\\\Plugin->httpAfterGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(491): Sabre\\\\Event\\\\EventEmitter->emit('afterMethod:GET', Array)\\n#9 \\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/html\\\/ssl443\\\/apps\\\/dav\\\/lib\\\/Server.php(283): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/html\\\/ssl443\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/html\\\/ssl443\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/s...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/ssl443\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":391}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"13.0.0.14"}

</details>

**Comment by tapete** [comment] 2018-03-17 12:01
Seems to be the same as #https://github.com/nextcloud/server/issues/2258

I dont undestand why a vcf file needs to follow the "iCalendar/vCard conventions" to get synced?

**Comment by tapete** [comment] 2018-03-17 20:56
For any reason, a conversion of the vcard format of the vcf file is enforced in nextcloud\3rdparty\sabre\dav\lib\CardDAV\plugin.php on line 772 when the vcf file is requested by the windows client. If the file gets downloaded via the webinterface, no error occurs.

**Comment by MorrisJobke** [comment] 2018-04-23 15:53
Duplicate of #6711

**Closed by MorrisJobke** 2018-04-23 15:53 UTC
