### ISSUE TITLE
Updated to NC22.0 -> Images arent displayed anymore

### ISSUE THREAD

**Issue by morbificagent** [nextcloud/server#27918] opened 2021-07-12 08:38 UTC
Hi together,

updated to NC22 Beta yesterday and images cant be displayed anymore now:

![grafik](https://user-images.githubusercontent.com/50199132/125256856-22993000-e2fd-11eb-8ca1-69dfe8747ca8.png)

And the log is full of:

Verursacht durch Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'USERNAME') AND (`configkey` = 'read') AND (...' at line 1

Has anyone an idea?

**Comment by szaimen** [comment] 2021-07-12 18:31
Hi, does the same happen on NC22.0.0 final?
Could you please post the complete error log?
Thanks!

**Comment by morbificagent** [comment] 2021-07-12 18:41
Hi szaimen,

Its the nc version is the one that get installed if i switch to the beta channel.
On stable channel i was on nc 21 before.

Here is the full log:

{"reqId":"se7MRihBL4EARPMRp6GD","level":3,"time":"2021-07-12T18:17:41+00:00","remoteAddr":"46.114.153.72","user":"Alex","app":"no app in context","method":"PUT","url":"/apps/text/session/create","message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'Alex') AND (`configkey` = 'read') AND (...' at line 1","userAgent":"Mozilla/5.0 (Android 11; Mobile; rv:89.0) Gecko/89.0 Firefox/89.0","version":"22.0.0.11","exception":{"Exception":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","Message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'Alex') AND (`configkey` = 'read') AND (...' at line 1","Code":1064,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1146,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":82,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":64,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":106,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1292,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1154,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1005,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":114,"function":"fopen","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Service/DocumentService.php","line":164,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Service/ApiService.php","line":96,"function":"createDocument","class":"OCA\\Text\\Service\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Controller/SessionController.php","line":50,"function":"create","class":"OCA\\Text\\Service\\ApiService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"create","class":"OCA\\Text\\Controller\\SessionController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":84,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'Alex') AND (`configkey` = 'read') AND (...' at line 1","Code":1064,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":82,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":64,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":106,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1292,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1154,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1005,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":114,"function":"fopen","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Service/DocumentService.php","line":164,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Service/ApiService.php","line":96,"function":"createDocument","class":"OCA\\Text\\Service\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Controller/SessionController.php","line":50,"function":"create","class":"OCA\\Text\\Service\\ApiService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"create","class":"OCA\\Text\\Controller\\SessionController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'configvalue` + 1)` WHERE (`userid` = 'Alex') AND (`configkey` = 'read') AND (...' at line 1","Code":"42000","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":262,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":82,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/user_usage_report/lib/Listener.php","line":64,"function":"storeAction","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":106,"function":"fileRead","class":"OCA\\UserUsageReport\\Listener","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1292,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1154,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1005,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/File.php","line":114,"function":"fopen","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Service/DocumentService.php","line":164,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Service/ApiService.php","line":96,"function":"createDocument","class":"OCA\\Text\\Service\\DocumentService","type":"->"},{"file":"/var/www/nextcloud/apps/text/lib/Controller/SessionController.php","line":50,"function":"create","class":"OCA\\Text\\Service\\ApiService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"create","class":"OCA\\Text\\Controller\\SessionController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}},"CustomMessage":"--"},"id":"60ec8bb46e38b"}

**Comment by szaimen** [comment] 2021-07-12 19:16
Thanks, this is a duplicate of https://github.com/nextcloud/user_usage_report/issues/69

**Closed by szaimen** 2021-07-12 19:16 UTC
Labels: 0. Needs triage, bug, needs info
