### ISSUE TITLE
Can't upload files from mobile browser

### ISSUE THREAD

**Issue by MG2R** [nextcloud/server#3667] opened 2017-03-01 13:18 UTC
### Steps to reproduce
1. Open Nextcloud in a mobile browser (I'm trying both the built-in browser of BlackBerry OS 10, and the "Evolution" browser available through BlackBerry world).

### Expected behaviour
I want to see a button allowing me to create/upload a file, just as I do on a desktop browser.

### Actual behaviour
I see a message "You don't have permission to upload or create files here"

### Server configuration
**Operating system**: Arch Linux

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.21

**PHP version:** PHP 7.1.2

**Nextcloud version:** (see Nextcloud admin page) 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://nextcloud.com/install/#instructions-server

**Signing status:** 
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
# Can't do this from my current location

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
# Can't do this from my current location

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** BlackBerry OS 10 built-in browser, and "evolution browser" from BlackBerry world

**Operating system:** BlackBerry OS 10.3.3

#### Web server error log
<details>
<summary>Web server error log</summary>

```
# Can't do that from my current location

Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No log entries are created when trying to access the files app. 
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Can't access this
```
</details>

**Comment by MG2R** [comment] 2017-03-01 14:17
Asked a friend to test on his Android machine using Chrome. He can upload without issue, so this must be something BlackBerry-specific, I guess.

**Comment by WTFThatPerson** [comment] 2017-05-08 23:26
I have exactly the same problem. So, there are Apache logs for successful and unsuccessful logins:
1. Windows machine, permissions are OK
``Windows_IP - - [08/May/2017:11:14:33 +0300] "GET / HTTP/1.1" 302 -
Windows_IP  - - [08/May/2017:11:14:34 +0300] "GET /index.php/login HTTP/1.1" 200 17936
Windows_IP  - - [08/May/2017:11:14:35 +0300] "GET /index.php/core/js/oc.js?v=63c8ccaad8082eb37483b142c523d3e2 HTTP/1.1" 200 3419
Windows_IP  - - [08/May/2017:11:14:50 +0300] "POST /index.php/login HTTP/1.1" 303 -
Windows_IP  - - [08/May/2017:11:14:51 +0300] "GET /index.php/apps/files/ HTTP/1.1" 200 57530
Windows_IP  - - [08/May/2017:11:14:53 +0300] "GET /index.php/core/js/oc.js?v=63c8ccaad8082eb37483b142c523d3e2 HTTP/1.1" 200 3472
Windows_IP  - - [08/May/2017:11:14:54 +0300] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102
Windows_IP  - - [08/May/2017:11:14:54 +0300] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 509
Windows_IP  - - [08/May/2017:11:14:54 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4433
Windows_IP  - - [08/May/2017:11:14:55 +0300] "GET /index.php/apps/systemtags/lastused HTTP/1.1" 200 2
Windows_IP  - - [08/May/2017:11:14:57 +0300] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 283
Windows_IP  - - [08/May/2017:11:15:04 +0300] "GET /index.php/logout?requesttoken=uP2kwF4cg%2BLboFsaW4RqC%2BuQeVGCXEfH89wdADkldAE%3D%3A05neoi121ZWY0wN9DbUiSdLdPwbkNxCsprhKbGFIHFs%3D HTTP/1.1" 303 -
Windows_IP  - - [08/May/2017:11:15:06 +0300] "GET /index.php/login HTTP/1.1" 200 17936
Windows_IP  - - [08/May/2017:11:15:07 +0300] "GET /index.php/core/js/oc.js?v=63c8ccaad8082eb37483b142c523d3e2 HTTP/1.1" 200 3419
Windows_IP  - - [08/May/2017:11:15:10 +0300] "-" 408 –
``
2. Blackberry 10 device, "You haven't permission..."
``Blackberry_IP - - [08/May/2017:11:25:05 +0300] "GET / HTTP/1.1" 302 -
Blackberry_IP - - [08/May/2017:11:25:07 +0300] "GET /index.php/login HTTP/1.1" 200 17490
Blackberry_IP - - [08/May/2017:11:25:10 +0300] "GET /index.php/core/js/oc.js?v=63c8ccaad8082eb37483b142c523d3e2 HTTP/1.1" 200 3419
Blackberry_IP - - [08/May/2017:11:25:45 +0300] "POST /index.php/login HTTP/1.1" 303 -
Blackberry_IP - - [08/May/2017:11:25:46 +0300] "GET /index.php/apps/files/ HTTP/1.1" 200 57082
Blackberry_IP - - [08/May/2017:11:25:51 +0300] "GET /index.php/core/js/oc.js?v=63c8ccaad8082eb37483b142c523d3e2 HTTP/1.1" 200 3472
Blackberry_IP - - [08/May/2017:11:25:54 +0300] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 509
Blackberry_IP - - [08/May/2017:11:25:54 +0300] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 102
Blackberry_IP - - [08/May/2017:11:25:56 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2527
Blackberry_IP - - [08/May/2017:11:25:57 +0300] "GET /index.php/apps/systemtags/lastused HTTP/1.1" 200 2
Blackberry_IP - - [08/May/2017:11:25:57 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2527
Blackberry_IP - - [08/May/2017:11:25:58 +0300] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 283
Blackberry_IP - - [08/May/2017:11:25:59 +0300] "GET /index.php/core/preview.png?file=%2FNextcloud.mp4&c=2ef44c514d05146446e45234d5647029&x=72&y=72&forceIcon=0 HTTP/1.1" 404 2
Blackberry_IP - - [08/May/2017:11:25:59 +0300] "GET /index.php/core/preview.png?file=%2FNextcloud+Manual.pdf&c=40695854c66bda3be8408c0289a2f753&x=72&y=72&forceIcon=0 HTTP/1.1" 404 2
Blackberry_IP - - [08/May/2017:11:26:10 +0300] "GET /index.php/logout?requesttoken=RWiZ19Nktrkks600xF1bGw8NGH11K2i6HStusZZRV4k%3D%3AIy/77rhT2vtt8vxVnglqWVU%2BbTEhGFD1bEABgsw3Pu0%3D HTTP/1.1" 303 -
Blackberry_IP - - [08/May/2017:11:26:12 +0300] "GET /index.php/login HTTP/1.1" 200 17490
Blackberry_IP - - [08/May/2017:11:26:14 +0300] "GET /index.php/core/js/oc.js?v=63c8ccaad8082eb37483b142c523d3e2 HTTP/1.1" 200 3419
``
Both cases are simple login - logout.
BTW that bug presence at "app" mode only, but at "gallery" mode everything is OK with permissions

**Comment by WTFThatPerson** [comment] 2017-05-18 18:18
I see funny situation: despite of that message, I can open .txt file, modify it and save edited file back on server. So, it isn't problem with file permissions definitely.

**Comment by skjnldsv** [comment] 2020-03-10 09:30
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-03-10 09:30 UTC
Labels: 0. Needs triage, bug
