### ISSUE TITLE
Address in mailbox given [https:\/\/spreed.me\/picloud] does not comply with RFC 2822, 3.6.2

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#951] opened 2016-08-18 21:07 UTC
Another _fatal_ error in the server logs:

```
Exception: {"Message":"Address in mailbox given [https:\/\/spreed.me\/picloud] does not comply with RFC 2822, 3.6.2.","Exception":"Swift_RfcComplianceException","Code":0,"Trace":"#0 \/var\/www\/html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('https:\/\/spreed....')\n#1 \/var\/www\/html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)\n#2 \/var\/www\/html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)\n#3 \/var\/www\/html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)\n#4 \/var\/www\/html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleHeaderSet.php(68): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To', Array)\n#5 \/var\/www\/html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleMessage.php(323): Swift_Mime_SimpleHeaderSet->addMailboxHeader('To', Array)\n#6 \/var\/www\/html\/lib\/private\/Mail\/Message.php(128): Swift_Mime_SimpleMessage->setTo(Array)\n#7 \/var\/www\/html\/apps\/dav\/lib\/CalDAV\/Schedule\/IMipPlugin.php(113): OC\\Mail\\Message->setTo(Array)\n#8 [internal function]: OCA\\DAV\\CalDAV\\Schedule\\IMipPlugin->schedule(Object(Sabre\\VObject\\ITip\\Message))\n#9 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#10 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(306): Sabre\\Event\\EventEmitter->emit('schedule', Array)\n#11 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(528): Sabre\\CalDAV\\Schedule\\Plugin->deliver(Object(Sabre\\VObject\\ITip\\Message))\n#12 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(294): Sabre\\CalDAV\\Schedule\\Plugin->processICalendarChange(NULL, Object(Sabre\\VObject\\Component\\VCalendar), Array, Array, true)\n#13 [internal function]: Sabre\\CalDAV\\Schedule\\Plugin->calendarObjectChange(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), Object(Sabre\\VObject\\Component\\VCalendar), 'calendars\/olivi...', true, true)\n#14 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#15 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(889): Sabre\\Event\\EventEmitter->emit('calendarObjectC...', Array)\n#16 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(771): Sabre\\CalDAV\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\/olivi...', false, Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), true)\n#17 [internal function]: Sabre\\CalDAV\\Plugin->beforeCreateFile('calendars\/olivi...', 'BEGIN:VCALENDAR...', Object(OCA\\DAV\\CalDAV\\Calendar), false)\n#18 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#19 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#20 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('calendars\/olivi...', 'BEGIN:VCALENDAR...', NULL)\n#21 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#22 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#23 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#24 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#25 \/var\/www\/html\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#26 \/var\/www\/html\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#27 \/var\/www\/html\/remote.php(165): require_once('\/var\/www\/html\/a...')\n#28 {main}","File":"\/var\/www\/html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php","Line":348,"User":"olivier"}   
```

@oparoz Do you have any information on that event? That would be good to know to have this reproducible :)

**Comment by oparoz** [comment] 2016-08-18 21:51
It's quite easy to reproduce.

1. Create an event in the calendar
2. Add the URL as an attendee
3. Set that attendee to being a room and make it a non-attendant

This will probably also happen is you add a resource.

**Comment by MorrisJobke** [comment] 2016-09-14 09:50
Moved to 10.0.2

**Comment by MorrisJobke** [comment] 2017-08-07 10:08
Still an issue:

```
{"reqId":"CBPGSIYj0nz4YquM4nwH","level":4,"time":"2017-08-07T10:04:51+00:00","remoteAddr":"192.168.99.1","user":"admin","app":"webdav","method":"PUT","url":"\/server\/remote.php\/dav\/calendars\/admin\/personal\/Nextcloud-QSK29ZWS0JAMSCYJ9853.ics","message":"Exception: {\"Exception\":\"Swift_RfcComplianceException\",\"Message\":\"Address in mailbox given [https://spreed.me/picloud@] does not comply with RFC 2822, 3.6.2.\",\"Code\":0,\"Trace\":\"
#0 3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(263): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('https://spreed....')
#1 3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(68): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To', Array)
#5 3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(329): Swift_Mime_SimpleHeaderSet->addMailboxHeader('To', Array)
#6 lib/private/Mail/Message.php(128): Swift_Mime_SimpleMessage->setTo(Array)
#7 apps/dav/lib/CalDAV/Schedule/IMipPlugin.php(112): OC\\Mail\\Message->setTo(Array)
#8 [internal function]: OCA\\DAV\\CalDAV\\Schedule\\IMipPlugin->schedule(Object(Sabre\\VObject\\ITip\\Message))
#9 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#10 3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php(384): Sabre\\Event\\EventEmitter->emit('schedule', Array)
#11 3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php(665): Sabre\\CalDAV\\Schedule\\Plugin->deliver(Object(Sabre\\VObject\\ITip\\Message))
#12 3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php(367): Sabre\\CalDAV\\Schedule\\Plugin->processICalendarChange(Object(Sabre\\VObject\\Component\\VCalendar), Object(Sabre\\VObject\\Component\\VCalendar), Array, Array, true)
#13 [internal function]: Sabre\\CalDAV\\Schedule\\Plugin->calendarObjectChange(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), Object(Sabre\\VObject\\Component\\VCalendar), 'calendars/admin...', true, false)
#14 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#15 3rdparty/sabre/dav/lib/CalDAV/Plugin.php(943): Sabre\\Event\\EventEmitter->emit('calendarObjectC...', Array)
#16 3rdparty/sabre/dav/lib/CalDAV/Plugin.php(772): Sabre\\CalDAV\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars/admin...', false, Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), false)
#17 [internal function]: Sabre\\CalDAV\\Plugin->beforeWriteContent('calendars/admin...', Object(OCA\\DAV\\CalDAV\\CalendarObject), 'BEGIN:VCALENDAR...', false)
#18 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#19 3rdparty/sabre/dav/lib/DAV/Server.php(1128): Sabre\\Event\\EventEmitter->emit('beforeWriteCont...', Array)
#20 3rdparty/sabre/dav/lib/DAV/CorePlugin.php(513): Sabre\\DAV\\Server->updateFile('calendars/admin...', 'BEGIN:VCALENDAR...', NULL)
#21 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#22 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#23 3rdparty/sabre/dav/lib/DAV/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)
#24 3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))
#25 apps/dav/lib/Server.php(253): Sabre\\DAV\\Server->exec()
#26 apps/dav/appinfo/v2/remote.php(33): OCA\\DAV\\Server->exec()
#27 remote.php(162): require_once('/srv/projects/s...')
#28 {main}\",\"File\":\"3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php\",\"Line\":347}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit\/603.3.8 (KHTML, like Gecko) Version\/10.1.2 Safari\/603.3.8","version":"13.0.0.2"}
```

**Comment by MorrisJobke** [comment] 2017-08-07 10:09
I would say this is more a problem of the calendar, right? It should valide at least the input in JS and also show a proper error, because now it only closes the sidebar without any indication.

cc @georgehrke

**Comment by georgehrke** [comment] 2017-08-07 10:11
I will check the RFC 5545 for that, but the iTipPlugin should simply ignore anything that's not `mailto://` imho

**Comment by georgehrke** [comment] 2017-08-07 10:54
https://tools.ietf.org/html/rfc5545#section-3.8.4.1 defines value type as CAL-ADDRESS, which is defined in https://tools.ietf.org/html/rfc5545#section-3.3.3

> The value is a URI as defined by [RFC3986] or any other IANA-registered form for a URI.

**Comment by georgehrke** [comment] 2017-08-07 10:56
This error is actually supposed to be caught: 
https://github.com/nextcloud/server/blob/de911f6e5c394fc86f45edc58850fd2e7649913c/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L84

Needs some debugging

**Comment by enoch85** [comment] 2017-09-13 20:30
Not much help maybe, but I got this recently in 12.0.2:

```
Swift_RfcComplianceException: Address in mailbox given [Nextcloud@] does not comply with RFC 2822, 3.6.2.
```

**Comment by mc9625** [comment] 2017-11-17 09:22
I can't say if it's relevant or not, but I've experienced a similar issue (@localhost.localdomain were attached at the end of the real email address, so it became something like firstname.lastname@gmail.com@localhost.localdomain). The issue disappeared as soon as I've unchecked the "allow users to share via link" option. Strange.

**Comment by vasyugan** [comment] 2018-02-04 12:17
I see this error whenever I try to share a file via the desktop client 
![grafik](https://user-images.githubusercontent.com/3313208/35777416-cad95bdc-09ad-11e8-825c-8f0279278d0f.png)

**Comment by DanLeonelli** [comment] 2018-02-16 04:52
This is happening on the new version ever since updated to 13 whenever trying to share a file.

**Comment by stone212** [comment] 2018-05-08 04:25
@DanLeonelli This is happening for me also when I try to share a file with anyone.  Did you ever find a fix to it?  I assume I have to configure email defaults somewhere.

**Comment by oparoz** [comment] 2018-09-12 18:52
Still a problem with 14. The send test button generates the problem when setting up SMTP

**Comment by georgehrke** [comment] 2018-09-12 19:12
Then we are talking about different issues here ...

The original error reported by Lukas is triggered from inside `OCA\\DAV\\CalDAV\\Schedule\\IMipPlugin`. That class is responsible and only responsible for sending out Calendar Invitations.

Hitting the Test Button should not be related to that.

**Comment by georgehrke** [comment] 2018-09-12 19:16
@oparoz Any chance you can provide the stack trace for your error? thx

**Comment by oparoz** [comment] 2018-09-13 07:29
I'll open a separate report. It seems the class responsible to send emails never gets the domain name:
```
A problem occurred while sending the email. Please revise your settings. (Error: Address in mailbox given [admin@] does not comply with RFC 2822, 3.6.2.)
```

**Comment by georgehrke** [comment] 2018-10-14 18:59
I will close this issue, because the original issue is not reproducible and should be caught by https://github.com/nextcloud/server/blob/v13.0.7/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L133L139

**Closed by georgehrke** 2018-10-14 18:59 UTC
Labels: bug, feature: dav
