### ISSUE TITLE
AmazonS3.php repeatedly logs fclose() error in logs.

### ISSUE THREAD

**Issue by isaacgerg** [nextcloud/server#18851] opened 2020-01-12 23:37 UTC
Used a fresh install of nextcloud-snap on ubuntu with AWS. Hooked up to S3 bucket. Every file upload to the S3 bucket works but the following shows up repeatedly in the logs:

fclose(): supplied resource is not a valid stream resource at /snap/nextcloud/18019/htdocs/apps/files_external/lib/Lib/Storage/AmazonS3.php#641

**Comment by kesselb** [comment] 2020-01-13 13:15
Duplicate of https://github.com/nextcloud/server/issues/15486

**Closed by kesselb** 2020-01-13 13:15 UTC
Labels: 0. Needs triage, bug
