### ISSUE TITLE
WebDAV only: no write-protection message when open microsoft word/excel file that already open

### ISSUE THREAD

**Issue by nobe80** [nextcloud/server#25197] opened 2021-01-19 09:05 UTC
Hi kesselb,

the Temporarly File Lock App is not a solution for WebDAV Users because they have to lock every time in the webinterface each single file and unlock it again. We switched from Plesk Filesharing where we had a filelock if the file was already open by another user. It is possible to get another way to lock files if they are open by another user?

_Originally posted by @nobe80 in https://github.com/nextcloud/server/issues/25188#issuecomment-762702833_

**Comment by kesselb** [comment] 2021-01-19 09:16
Closing as duplicate of #25188.

**Closed by kesselb** 2021-01-19 09:16 UTC
