### ISSUE TITLE
Notify by email option not saving

### ISSUE THREAD

**Issue by ddulic** [nextcloud/server#1760] opened 2016-10-16 10:16 UTC
### Steps to reproduce
1. Select a file, got to sharing tab, share it with a group, check "notify by email"
2. Go to another file, click on the original file
3. The "notify by email" is unchecked.

### Expected behaviour
The option should remain checked.

### Actual behaviour
The option unchecks it self.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
DigitalOcean 10$ droplet.

**Database:**
Type: mysql
Version: 5.5.49
Size: 4.7 MB

**PHP version:**
Version: 5.5.9
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 513.0 MB

**Nextcloud version:** (see Nextcloud admin page)
10.0(stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Command Line

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
I don't have access at the moment. I will update tomorrow.
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
Updating tomorrow....

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Bug is present on all browsers.

**Operating system:**
Bug is present on all systems.

#### Web server error log
<details>
<summary>Web server error log. </summary>
```
I will update tomorrow.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log. **This is the error I get upon checking "notify by email"**</summary>
```
Error	index	
Exception: {"Exception":"Symfony\\Component\\Routing\\Exception\\MissingMandatoryParametersException","Message":"Some mandatory parameters are missing (\"fileid\") to generate a URL for route \"files.viewcontroller.showFile\".","Code":0,"Trace":"#0 \/var\/www\/projekt-raum\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php(136): Symfony\\Component\\Routing\\Generator\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'files.viewcontr...', 1, Array, Array)\n#1 \/var\/www\/projekt-raum\/lib\/private\/Route\/Router.php(333): Symfony\\Component\\Routing\\Generator\\UrlGenerator->generate('files.viewcontr...', Array, 1)\n#2 \/var\/www\/projekt-raum\/lib\/private\/Route\/CachingRouter.php(60): OC\\Route\\Router->generate('files.viewcontr...', Array, false)\n#3 \/var\/www\/projekt-raum\/lib\/private\/URLGenerator.php(69): OC\\Route\\CachingRouter->generate('files.viewcontr...', Array)\n#4 \/var\/www\/projekt-raum\/lib\/private\/URLGenerator.php(82): OC\\URLGenerator->linkToRoute('files.viewcontr...', Array)\n#5 \/var\/www\/projekt-raum\/lib\/private\/Share\/MailNotifications.php(127): OC\\URLGenerator->linkToRouteAbsolute('files.viewcontr...', Array)\n#6 \/var\/www\/projekt-raum\/core\/ajax\/share.php(77): OC\\Share\\MailNotifications->sendInternalShareMail(Array, '8', 'file')\n#7 \/var\/www\/projekt-raum\/lib\/private\/Route\/Route.php(155) : runtime-created function(1): require_once('\/var\/www\/projek...')\n#8 [internal function]: __lambda_func(Array)\n#9 \/var\/www\/projekt-raum\/lib\/private\/Route\/Router.php(293): call_user_func('?lambda_845', Array)\n#10 \/var\/www\/projekt-raum\/lib\/base.php(967): OC\\Route\\Router->match('\/core\/ajax\/shar...')\n#11 \/var\/www\/projekt-raum\/index.php(48): OC::handleRequest()\n#12 {main}","File":"\/var\/www\/projekt-raum\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":165}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Nothing unusual here.
```
</details>

**Comment by nickvergessen** [comment] 2016-10-17 09:21
Duplicate of https://github.com/nextcloud/server/issues/1277

**Closed by nickvergessen** 2016-10-17 09:21 UTC

**Comment by ddulic** [comment] 2016-10-19 14:17
Did not find it when searching. Thanks.
