### ISSUE TITLE
Error uploading packed file

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#29824] opened 2021-11-21 12:58 UTC
Steps:

1. Select the "Files" application.
2. Select "Upload file".
3. Select a zip or 7zip file to upload.

When uploading a packed file, eg. of the type: **Zip** or **7z**, the message "An unknown error has occurred" appears:

![obraz](https://user-images.githubusercontent.com/47037905/142762264-aabd5169-3e6d-45dc-8b2a-f8cffcda8fb6.png)

Uploading a packed file by Client Nextcloud also ends with an error:

![obraz](https://user-images.githubusercontent.com/47037905/142762405-b7f36623-2c56-4456-9df2-176214b5c55c.png)

The file is not uploading.

### Server configuration

**PHP version:**
7.3.25

**Nextcloud version:** (see Nextcloud admin page)
22.2.3

### Client configuration
**Browser:**
Firefox 94.0.1

**Nextcloud Desktop Client**
3.3.6 (Windows).

**Operating system:**
Win 10

### Logs
No log error.

**Comment by szaimen** [comment] 2021-11-21 13:34
I can't reproduce that. Uploading of zip and 7zip files works fine on my 22.2.3 instance

**Comment by Valdnet** [comment] 2021-11-21 14:59
@szaimen Thanks for checking 👍. I will leave this issue open for now to find the cause of the problem.

**Comment by Valdnet** [comment] 2021-11-21 15:25
For now, I exclude the problem on the server side because uploading the packed 7z file from another CMS is correct. Error 405 does not appear.

**Comment by Valdnet** [comment] 2021-11-21 15:32
In version Nextcloud 23.0.0 RC2 there is also an error uploading the packed 7z file.

**Comment by Valdnet** [comment] 2021-11-23 09:26
Uploading all zipped files (7z, Zip, Rar, tar.gz etc.) **is impossible** on proven systems:

1. Windows 10:
- Nextcloud Files 😬,
- Nextcloud Desktop Client 😬.

2. Linux
- Nextcloud Files 😬.

However, uploading is possible on the system:

1. Android:
- Nextcloud Files 👍,
- Nextcloud Android 👍.

I looked through the forum on this topic and found no solution.

I am asking for help in solving the problem.

**Comment by Valdnet** [comment] 2021-11-23 10:35
Problem solved with help from Simon.
I had to disable mod_security in the `.htaccess` file.

```
<IfModule mod_security.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
</IfModule>
```

**Comment by szaimen** [comment] 2021-11-23 10:38
You should probably rather disalbe mod_security in the apache config as the .htaccess file will get overwritten...

**Comment by Valdnet** [comment] 2021-11-23 10:45
I cannot access the apache configuration.

**Comment by szaimen** [comment] 2021-11-23 10:47
Feel free to create a PR then with your changes then but it is not likely that it will get merged.

**Comment by simonspa** [comment] 2021-11-23 11:03
I believe we can close this now?

**Closed by simonspa** 2021-11-23 11:03 UTC
Labels: help wanted, 0. Needs triage
