### ISSUE TITLE
Strange entry in shared with others

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4652] opened 2017-05-02 08:31 UTC
<img width="1468" alt="screen shot 2017-05-02 at 10 19 39" src="https://cloud.githubusercontent.com/assets/878997/25610164/742d7c20-2f22-11e7-9955-78d2d19f903b.png">

The JSON entries look like this:

```json
       {
            "id":"636",
            "share_type":4,
            "uid_owner":"lukas",
            "displayname_owner":"Lukas Reschke",
            "permissions":1,
            "stime":1491225987,
            "parent":null,
            "expiration":null,
            "token":"XXXX",
            "uid_file_owner":"lukas",
            "displayname_file_owner":"Lukas Reschke",
            "path":"\/",
            "item_type":"folder",
            "mimetype":"httpd\/unix-directory",
            "storage_id":"home::lukas",
            "storage":11,
            "item_source":561,
            "file_source":561,
            "file_parent":559,
            "file_target":"",
            "share_with":"harald.pfeifer@XXXX.com",
            "password":null,
            "share_with_displayname":"harald.pfeifer@XXXX.com",
            "mail_send":0
         },
```

**Comment by rullzer** [comment] 2017-05-02 10:47
What did you do?

**Comment by LukasReschke** [comment] 2017-05-02 15:05
@rullzer Open the "Shared with others" tab with a Nextcloud 12 😉

**Comment by MorrisJobke** [comment] 2017-05-09 05:09
cc @icewind1991 @schiessle

**Comment by MorrisJobke** [comment] 2017-05-15 04:12
Works for me fine, but I also only have shares with single persons.

**Comment by MorrisJobke** [comment] 2017-05-15 04:13
@LukasReschke What is strange about this? That it somehow used email addresses? Or that they are somehow shortened?

**Comment by LukasReschke** [comment] 2017-05-15 12:31
> @LukasReschke What is strange about this? That it somehow used email addresses? Or that they are somehow shortened?

That there is neither a file nor folder name for the first item. Happens for my account on c.nc.c.

**Comment by MorrisJobke** [comment] 2017-05-15 14:20
Ah ... Strange -.-

**Comment by MorrisJobke** [comment] 2017-05-15 14:20
Ah ... Strange -.-

**Comment by ddanielww** [comment] 2017-05-18 23:49
What's the fix ?

**Comment by ddanielww** [comment] 2017-05-18 23:51
Where can I find these entries to remove them from the web interface?

**Comment by MorrisJobke** [comment] 2018-02-14 21:46
Looks like #8353 could give some hints

**Comment by MorrisJobke** [comment] 2018-02-15 10:29
Seems that those are some valid steps for 13:

If you delete a shared folder without first deleting the share, an empty item remains visible in the "shared with others" menu.
It is not possible to delete this share.

### Steps to reproduce

1. Share a folder
2. Delete the folder
3. Go to "shared with other" and see the first folder blank


@nextcloud/sharing @nextcloud/javascript Does somebody of you want to look into this?

**Comment by rullzer** [comment] 2018-04-05 09:16
I think this is solved with https://github.com/nextcloud/server/pull/9070

**Comment by MorrisJobke** [comment] 2018-04-05 12:12
I could not reproduce anymore. Let's close this then.

**Closed by MorrisJobke** 2018-04-05 12:12 UTC
Labels: bug, feature: sharing
