### ISSUE TITLE
Federated shares do not work between two NC15 servers

### ISSUE THREAD

**Issue by buttle** [nextcloud/server#13442] opened 2019-01-09 12:20 UTC
### Steps to reproduce
1. Install NC15 on two different server
2. Share a folder on server_1 with a user on server_2

### Expected behaviour
1. Recieve a notification on server_2.
2. See the shared folder in Files. Shared with you.
3. See the folder in the Files app.

### Actual behaviour
1. The 'Bell' shows there is a notficiation, but the notification box is empty.
2. The activity is correctly reported in the Activity stream
3. The shared folder cannot be seen at all.
### Server configuration

**Operating system**:
Debian9 on the two servers.

**Web server:**
Apache

**Database:**
mariaDB

**PHP version:**
7.0.3

**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Shell.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - circles: 0.16.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - richdocuments: 3.1.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
None

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP (on the two servers)

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

Config is the same on both server except ldapBaseGroups, ldapLoginFilter, ldapUserFilter

```
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                         |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                           |
| homeFolderNamingRule          |                                                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                                                           |
| ldapAgentName                 | cn=nobody,dc=zzzz,dc=coop                                                                                           |
| ldapAgentPassword             | ***                                                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                                                             |
| ldapAttributesForUserSearch   |                                                                                                                             |
| ldapBackupHost                |                                                                                                                             |
| ldapBackupPort                |                                                                                                                             |
| ldapBase                      | dc=zzzz,dc=coop                                                                                                     |
| ldapBaseGroups                | cn=FKI,ou=collectives,o=xxxx,dc=zzzz,dc=coop                                                                |
| ldapBaseUsers                 | dc=zzzz,dc=coop                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                         |
| ldapConfigurationActive       | 1                                                                                                                           |
| ldapDefaultPPolicyDN          |                                                                                                                             |
| ldapDynamicGroupMemberURL     |                                                                                                                             |
| ldapEmailAttribute            | mail                                                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                                                           |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                          |
| ldapExpertUUIDUserAttr        | uid                                                                                                                         |
| ldapExpertUsernameAttr        |                                                                                                                             |
| ldapGidNumber                 | gidNumber                                                                                                                   |
| ldapGroupDisplayName          | cn                                                                                                                          |
| ldapGroupFilter               | (&(|(objectclass=groupOfNames)))                                                                                            |
| ldapGroupFilterGroups         |                                                                                                                             |
| ldapGroupFilterMode           | 1                                                                                                                           |
| ldapGroupFilterObjectclass    | groupOfNames                                                                                                                |
| ldapGroupMemberAssocAttr      | member                                                                                                                      |
| ldapHost                      | ldap://ldap.local                                                                                                           |
| ldapIgnoreNamingRules         |                                                                                                                             |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=oficina-t2,ou=serveis,o=xxxx,dc=zzzz,dc=coop)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                             |
| ldapLoginFilterEmail          | 0                                                                                                                           |
| ldapLoginFilterMode           | 0                                                                                                                           |
| ldapLoginFilterUsername       | 1                                                                                                                           |
| ldapNestedGroups              | 0                                                                                                                           |
| ldapOverrideMainServer        |                                                                                                                             |
| ldapPagingSize                | 500                                                                                                                         |
| ldapPort                      | 389                                                                                                                         |
| ldapQuotaAttribute            | pager                                                                                                                       |
| ldapQuotaDefault              | 512 MB                                                                                                                      |
| ldapTLS                       | 0                                                                                                                           |
| ldapUserAvatarRule            | default                                                                                                                     |
| ldapUserDisplayName           | displayname                                                                                                                 |
| ldapUserDisplayName2          |                                                                                                                             |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson))(|(memberof=cn=oficina-t2,ou=serveis,o=xxxx,dc=zzzz,dc=coop)))              |
| ldapUserFilterGroups          |                                                                                                                             |
| ldapUserFilterMode            | 0                                                                                                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                                                        |
| turnOffCertCheck              | 0                                                                                                                           |
| turnOnPasswordChange          | 0                                                                                                                           |
| useMemberOfToDetectMembership | 1 
```
</details>

### Client configuration
**Browser:**
We've tried this on different machines.

**Operating system:**
We've tried this on different machines.

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
tail -f nextcloud.log reports nothing on either server during the whole process.

Have seen this Error earlier
Exception":"Exception","Message":"Error 31 interacting with memcached : A TIMEOUT OCCURRED"
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by violoncelloCH** [comment] 2019-01-12 00:14
duplicate of nextcloud/notifications#232

**Closed by violoncelloCH** 2019-01-12 00:14 UTC
Labels: bug
