### ISSUE TITLE
Adding files and file actions not working

### ISSUE THREAD

**Issue by Perdex** [nextcloud/server#20709] opened 2020-04-28 18:15 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Likely one bug that manifests in two different ways.

### Steps to reproduce: 1
1. Enter a folder
2. Select plus -> "New folder" (or "New file")
3. Give it a name and press enter
4. Nothing happens.
5. Refresh page
6. The new folder(s)/file(s) are there (AKA action in step 3 did happen)
7. Now adding new folders(files) works normally.

### Steps to reproduce: 2
1. Enter a folder
2. Select a number of files (anything from 1 to many)
3. On the top, press "... Actions" ->select any option such as delete
4. Nothing happens.
5. Refresh page
6. Deleted files are still there (AKA action in step 3 did not happen)
7. Now actions work normally

Note: this does not affect the actions under the three dots of a single file. When deleting, the "loading" icon sometimes gets stuck so the interface doesn't update, but the file is removed when refreshing.

Both of these behaviours seem to always happen simultaneously, hence a single report.

### Expected behaviour
Case 1: When pressing enter in step 3, a new folder(file) should appear
Case 2: When selecting the action in step 3, the files should be deleted, or a dialog should pop up for move/copy

### Server configuration

**Operating system:** Ubuntu 18.04.4 LTS

**Web server:** Apache2

**Database:** mysql

**PHP version:** 7.2.24

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 17

**Where did you install Nextcloud from:** Snap

**Signing status:**
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - announcementcenter: 3.7.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - deck: 0.8.2
  - drawio: 0.9.5
  - external: 3.5.0
  - extract: 1.2.4
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_fulltextsearch: 1.4.2
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.7.0
  - files_readmemd: 1.1.4
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_texteditor: 2.11.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - fulltextsearch: 1.4.1
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quicknotes: 0.2.3
  - rainloop: 6.1.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - theming: 1.9.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.7.0
  - user_saml: 3.0.1
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - ldap_write_support
  - nextcloud_announcements
  - text
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
           "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "loglevel": 0,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "admin_resource_booking_database",
            "booking"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** SAML

### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Windows (Also observed on Manjaro Linux)

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"eB9u4GBJmVOtSnUKamdb","level":0,"time":"2020-04-28T18:06:11+00:00","remoteAddr":"127.0.0.1","user":"testuser7","app":"no app in context","method":"GET","url":"/remote.php/files/Media/live-preview-potato.png","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/remote.php/files/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2"}
{"reqId":"RbwRWvPeBkLgrWreI2de","level":0,"time":"2020-04-28T18:06:11+00:00","remoteAddr":"127.0.0.1","user":"testuser7","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=94118&x=32&y=32","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2"}
{"reqId":"VEtuiIWCNgy1HkmcI8SD","level":0,"time":"2020-04-28T18:06:11+00:00","remoteAddr":"127.0.0.1","user":"testuser7","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=94118&c=0cadf88255e8f83b6d2062202ed268df&x=200&y=200&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2"}
{"reqId":"YtlZUuCp1eXn6LkFz7zr","level":0,"time":"2020-04-28T18:06:11+00:00","remoteAddr":"127.0.0.1","user":"testuser7","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=94122&c=429206936c936ebdfb175739b57213f7&x=200&y=200&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2"}
{"reqId":"92B32Wk7HkX2GOMGAich","level":0,"time":"2020-04-28T18:06:11+00:00","remoteAddr":"127.0.0.1","user":"testuser7","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=94119&c=899e2142dd1fccad7b4af96024123b04&x=200&y=200&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2"}
{"reqId":"7APTZEPFTzhONvkcKxRK","level":0,"time":"2020-04-28T18:06:13+00:00","remoteAddr":"127.0.0.1","user":"laitinen","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=86959&c=97056a64cecbe09767d03359192296e7&x=250&y=250&forceIcon=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36","version":"18.0.4.2"
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Received when clicking action delete and it doesn't work:

```
TypeError: _.pluck is not a functionmerged-index.js:4923:15
    _onClickDeleteSelected merged-index.js:4923
    multiSelectMenuClick merged-index.js:4351
    _onClickAction merged-index.js:7748
    _onClickAction self-hosted:875
    jQuery 2
```

Received when trying to add new folder

```
TypeError: _.findWhere is not a function
```
</details>

**Comment by szaimen** [comment] 2021-05-31 13:41
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 13:41 UTC
Labels: 0. Needs triage, bug

**Comment by szaimen** [comment] 2021-09-15 14:19
Please refer for help to https://help.nextcloud.com
Thanks!
