### ISSUE TITLE
Preview generation fails for JPG > 1024KB

### ISSUE THREAD

**Issue by wdfee** [nextcloud/server#19022] opened 2020-01-20 17:14 UTC
There are no previews generated for JPGs bigger than 1024 KB. 
The issue appeared before I installed preview generator app, I now installed it for testing (and deleted old and generated all via occ), but it didn't help.
I already tried rising memory limit to 1024KB, and to 2048KB, it didn't help.
Then I tried configuring preview image sizes described in this article: https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/ - didn't help, too.

Maybe related to:
https://help.nextcloud.com/t/no-previews-for-jpg/52370
https://help.nextcloud.com/t/how-to-regenerate-previews/63246 (but in my case, I do not use encryption)
https://github.com/nextcloud/server/issues/3393
https://github.com/nextcloud/server/issues/12077
https://github.com/nextcloud/server/pull/16158

### Steps to reproduce
1. Upload JPG file bigger than 1024 KB
2. wait 10s, looking at files
3. open uploaded file

### Expected behaviour
A preview thumbnail should show up in row, a big preview should show up on click.

### Actual behaviour
No preview thumbnail in row (only default pic), error message for big view:

### Server configuration

**Operating system:** Ubuntu 18.04.3 LTS

**Web server:** Nginx

**Database:** mysql 10.1.43

**PHP version:** 7.3.13

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated continuosly since 15

**Where did you install Nextcloud from:** webinstaller

**Signing status:** No errors have been found.

**List of activated apps:**
<details>
<summary>Enabled apps</summary>
  - admin_audit: 1.7.0
  - cloud_federation_api: 1.0.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - oauth2: 1.5.0
  - previewgenerator: 2.2.0  – – tried with and without this app
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - twofactor_backupcodes: 1.6.0
  - workflowengine: 1.7.0
</details>

**Nextcloud configuration:**
<details>
<summary>Nextcloud configuration via occ</summary>
```
"instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ost.waldorfschule-groebenzell.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/var\/www\/vhosts\/[REMOVED]\/nx-skeleton\/skeleton-{lang}",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "https:\/\/[REMOVED]",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "465",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "logtimezone": "Europe\/Berlin",
        "loglevel": 0,
        "log_rotate_size": 10485760,
        "trashbin_retention_obligation": "auto, 14",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "preview_max_filesize_image": 1,
        "jpeg_quality": "60",
        "app_install_overwrite": [
            "apporder",
            "rssg_email_template",
            "rssgwizard"
        ],
        "debug": true,
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "updater.release.channel": "stable",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 72.0.1, Safari 13.0.1

**Operating system:** Mac OS X 10.14.6

#### Web server error log
<details>
<summary>nginx proxy_error_log</summary>
```
2020-01-20 17:49:05 | Error | ... | 7977#0: *64855 upstream timed out (110: Connection timed out) while reading response header from upstream
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"63RiGsB7735g267BpUlo","level":3,"time":"2020-01-20T17:49:17+01:00","remoteAddr":"87.147.207.44","user":"CloudMaster","app":"gallery","method":"GET","url":"\/index.php\/apps\/gallery\/preview\/2195?width=2900&height=2900&c=ec37d9578e94ec2aca16ffcd255466ad&requesttoken=wfSWkdROyIyT1xYzDy6xywR%2FmKkOb1Do67co2OfSBAA%3D%3AlMTkyL0Fprn1pXRbeGDpuHw08PxPLRmYj81YiNWiYFc%3D","message":{"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":[{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/Preview\/Generator.php","line":126,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"},{"__class__":"OC\\Files\\Node\\File"},"image\/jpeg",""]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/PreviewManager.php","line":210,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},2900,2900,false,"fill","image\/jpeg"]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/apps\/gallery\/lib\/Service\/PreviewService.php","line":106,"function":"getPreview","class":"OC\\PreviewManager","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},2900,2900,false]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/apps\/gallery\/lib\/Controller\/Preview.php","line":167,"function":"createPreview","class":"OCA\\Gallery\\Service\\PreviewService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},2900,2900,true,false]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/apps\/gallery\/lib\/Controller\/Preview.php","line":117,"function":"getPreviewData","class":"OCA\\Gallery\\Controller\\PreviewController","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},true,2900,2900,true,false]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/apps\/gallery\/lib\/Controller\/PreviewController.php","line":134,"function":"getData","class":"OCA\\Gallery\\Controller\\PreviewController","type":"->","args":[2195,2900,2900]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"getPreview","class":"OCA\\Gallery\\Controller\\PreviewController","type":"->","args":[2195,2900,2900]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Gallery\\Controller\\PreviewController"},"getPreview"]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Gallery\\Controller\\PreviewController"},"getPreview"]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["PreviewController","getPreview",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"fileId":"2195","_route":"gallery.preview.get_preview"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"fileId":"2195","_route":"gallery.preview.get_preview"}]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"fileId":"2195","_route":"gallery.preview.get_preview"}]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/base.php","line":997,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/gallery\/preview\/2195"]},{"file":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/vhosts\/[REMOVED]\/httpdocs\/lib\/private\/Preview\/Generator.php","Line":230,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
{"reqId":"63RiGsB7735g267BpUlo","level":3,"time":"2020-01-20T17:49:17+01:00","remoteAddr":"[REMOVED]","user":"[REMOVED]","app":"gallery","method":"GET","url":"\/index.php\/apps\/gallery\/preview\/2195?width=2900&height=2900&c=ec37d9578e94ec2aca16ffcd255466ad&requesttoken=wfSWkdROyIyT1xYzDy6xywR%2FmKkOb1Do67co2OfSBAA%3D%3AlMTkyL0Fprn1pXRbeGDpuHw08PxPLRmYj81YiNWiYFc%3D","message":"Exception: Preview generation has failed","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko\/20100101 Firefox\/72.0","version":"17.0.2.1"}
```
</details>

#### Browser log
<details>
<summary>Browser console log</summary>
```
GET https://[REMOVED]/index.php/core/preview?fileId=2195&c=ec37d9578e94ec2aca16ffcd255466ad&x=500&y=500&forceIcon=0
[HTTP/2 404 Not Found 823ms]

GET https://[REMOVED]/index.php/apps/gallery/preview/2195?width=2900&height=2900&c=ec37d9578e94ec2aca16ffcd255466ad&requesttoken=wfSWkdROyIyT1xYzDy6xywR%2FmKkOb1Do67co2OfSBAA%3D%3AlMTkyL0Fprn1pXRbeGDpuHw08PxPLRmYj81YiNWiYFc%3D
[HTTP/2 500 Internal Server Error 252ms]
```
</details>

**Comment by szaimen** [comment] 2021-05-28 11:22
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-28 11:22 UTC
Labels: 0. Needs triage, bug
