### ISSUE TITLE
Can't add configuration of LDAP/AD integration by browser

### ISSUE THREAD

**Issue by sttyru** [nextcloud/server#7594] opened 2017-12-21 10:34 UTC
### Steps to reproduce
1. Install NextCloud 12 at CentOS 7 und plugin for LDAP/
2. Setup of Nginx.
3. Try to add / modify of LDAP/AD configuration

### Expected behaviour
Can't to add or modify mine LDAP/AD configuration by web-intreface (Chrome or FF). In the webserver log no one warning. 

### Actual behaviour
Another function is ok.

### Server configuration

**Operating system**: CentOS 7.3 x86_64

**Web server:** tengine (is a fork of Nginx)

**Database:** MySQL by Oracle

**PHP version:** PHP 5.6.32 (cli) (built: Oct 29 2017 14:02:30)

**Nextcloud version:** (see Nextcloud admin page) 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** official repository

**Comment by sttyru** [comment] 2017-12-21 12:34
Sorry for double!
**https://github.com/nextcloud/server/issues/3074** <-- that bug

**Comment by MorrisJobke** [comment] 2017-12-22 10:37
Closing as duplicate of #3074

**Closed by MorrisJobke** 2017-12-22 10:37 UTC
