### ISSUE TITLE
[Bug]: App toolbar invisible on dashboard app when background image is white

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#32313] opened 2022-05-09 14:41 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The app header is invisible in the dashboard app when using a white background:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/277525/167434011-51befedd-6254-4ecc-8fa0-156f78baf2b1.png">

### Steps to reproduce

1. Go to the theming section
2. Set the theme color to #C96C42
3. Upload this unsplash image as login page image: https://unsplash.com/photos/25gENtMQcxk
4. Log in and go to dashboard

### Expected behavior

It seems the top bar is supposed to adjust itself to the colors somehow but failed to do so.

### Installation method

Other

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.16.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.23.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_automatedtagging: 1.14.0
  - files_external: 1.17.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.13.0
  - photos: 1.6.0
  - provisioning_api: 1.15.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - survey_client: 1.12.0
  - systemtags: 1.15.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.8.0
  - weather_status: 1.5.0
  - workflow_script: 1.6.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - calendar
  - contacts
  - email_template_example-0.0.1
  - encryption
  - files_3d
  - files_accesscontrol
  - files_antivirus
  - files_downloadlimit
  - files_retention
  - files_texteditor
  - files_versions_s3
  - groupfolders
  - guests
  - mail
  - music
  - officeonline
  - password_policy: 1.14.0
  - previewgenerator
  - ransomware_protection
  - registration
  - richdocuments
  - shareimporter
  - sharepermissions
  - spreed
  - support: 1.7.0
  - suspicious_login
  - terms_of_service
  - testing
  - twofactor_totp
  - user_ldap
  - user_migration
  - user_saml
```

### Additional info

Observed on git master 4f55ba2a8895995649306911e3efa92904906836

**Comment by joshtrichards** [comment] 2023-09-19 14:21
Duplicate of #28649

**Closed by joshtrichards** 2023-09-19 14:21 UTC
Labels: bug, design, 1. to develop, feature: theming, feature: dashboard, 25-feedback
