### ISSUE TITLE
Share receivers should be able to get permission to see all other users of the share 

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/server#3392] opened 2017-02-07 08:29 UTC
First activity in github please forgive me if i make any mistakes.

**This is a feature request.**

Yesterday two coworkers have started a collaboration project where internal users as well as external users should get access to files. So files will be shared to different users.

When user "A" shares a file to user "B" and "C" only user "A" sees with whom he had shared the file.
But users "B"  and "C" also want to see the users who received the share so they don't have to share the file twice or triple.

I suggest an enhancement where you can give users the permission to see all users of a share on files/folders they receive.

edit: this would also affect activity stream/email notifications of all users who receive the share so they can see if anyone new gets the share

### Steps to reproduce
1. Click on file or folder
2. Click on share
3. Share with local users
4. View file or folder with one of the users that received the share -> click on share

### Expected behaviour
Share receiver should see all other users with whom the folder/file was shared

### Actual behaviour
Share receiver sees only the share creator

**Comment by JaredBoone** [comment] 2017-06-21 23:47
I agree that this feature would be very valuable and one of my users has specifically requested it. 

If someone shares a folder with me, I may want to add something confidential to that folder, only visible to a select group of other users. Before doing that I would want to know who else currently has permission to view the folder.

**Comment by MorrisJobke** [comment] 2017-12-19 16:37
Let's close this as duplicate of #6480

**Closed by MorrisJobke** 2017-12-19 16:37 UTC
Labels: enhancement, feature: sharing
