### ISSUE TITLE
[Bug]: "Details" is missing in the files app contextual menu

### ISSUE THREAD

**Issue by Kurgan-** [nextcloud/server#40337] opened 2023-09-07 19:06 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [ ] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Context menu (the three dots, or right click) of a file on the "files" app is missing the "details" menu item. It's present if I click on "recents" or "favourites", but it's missing from the root folder of the files app and also from any other folders when I navigate into them by browsing the folder structure in the Files app.

This installation is a very old Nextcloud installation that has been updated multiple times (without any visible issue) using the web updater. I have a twin installation, that has undergone more or less the same installation and update process, and that one works.

This is an example of the context menu without the "Details" menu item, I was in the root folder of the Files app:
![image](https://github.com/nextcloud/server/assets/10371854/7ba17299-cfbf-4873-9ceb-db7254873212)

This is an example of the context menu with the Details menu item, which is working because I have selected "Recent" instead of just navigating the folders in the files app:
![image](https://github.com/nextcloud/server/assets/10371854/9d45faa3-00f3-4f64-a2b4-1d29d9741a53)

### Steps to reproduce

1. open nextcloud in your browser (tested Firefox and Chrome)
2. navigate to "files" app
3. Right click on any file in any folder (or use the three dots menu)
4. The "Details" menu item is missing from the pop-up menu.

### Expected behavior

I expect the "details" menu item being present in the pop-up menu for all files in all folders in the "files" app.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.kurgan.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.kurgan.org",
        "dbtype": "mysql",
        "version": "27.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "updater.release.channel": "stable",
        "has_rebuilt_cache": true,
        "default_phone_region": "IT",
        "mail_sendmailmode": "smtp"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.4.5
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - end_to_end_encryption: 1.13.1
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - encryption: 2.15.0
  - files_external: 1.19.0
  - files_mindmap: 0.0.28 (installed 0.0.28)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
The log is full of these, I don't think they are related:

{"reqId":"ZXAaN5crTkTqfuqDpNF4","level":1,"time":"2023-09-07T18:33:44+00:00","remoteAddr":"151.42.3.60","user":"kurgan","app":"text","method":"PUT","url":"/index.php/apps/text/session/create","message":"Keep previous document of 26575","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"27.0.2.1","data":{"app":"text"}}
{"reqId":"VPZPvv33Mi1UJWmBpNbx","level":1,"time":"2023-09-07T18:47:43+00:00","remoteAddr":"151.42.3.60","user":"kurgan","app":"text","method":"PUT","url":"/index.php/apps/text/session/create","message":"Keep previous document of 26575","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"27.0.2.1","data":{"app":"text"}}
{"reqId":"V0cFDCHreNwkrWwzN8Xx","level":1,"time":"2023-09-07T18:49:15+00:00","remoteAddr":"151.42.3.60","user":"kurgan","app":"text","method":"PUT","url":"/index.php/apps/text/session/create","message":"Keep previous document of 26575","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"27.0.2.1","data":{"app":"text"}}
{"reqId":"Sc0ez6Hip80k2CYH97Ei","level":1,"time":"2023-09-07T18:50:52+00:00","remoteAddr":"151.42.3.60","user":"kurgan","app":"text","method":"PUT","url":"/index.php/apps/text/session/create","message":"Keep previous document of 26575","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"27.0.2.1","data":{"app":"text"}}
{"reqId":"l1rrgq9i82Vp7Xsb9S5L","level":1,"time":"2023-09-07T18:52:51+00:00","remoteAddr":"151.42.3.60","user":"kurgan","app":"text","method":"PUT","url":"/index.php/apps/text/session/create","message":"Keep previous document of 26575","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"27.0.2.1","data":{"app":"text"}}
{"reqId":"7kOFr8z5605QFwdwI991","level":1,"time":"2023-09-07T18:56:39+00:00","remoteAddr":"151.42.3.60","user":"kurgan","app":"text","method":"PUT","url":"/index.php/apps/text/session/create","message":"Keep previous document of 26575","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"27.0.2.1","data":{"app":"text"}}
{"reqId":"Ne1IHMFo6NRRwZp1vEOu","level":1,"time":"2023-09-07T18:58:00+00:00","remoteAddr":"151.42.3.60","user":"kurgan","app":"text","method":"PUT","url":"/index.php/apps/text/session/create","message":"Keep previous document of 26575","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0","version":"27.0.2.1","data":{"app":"text"}}
```

**Comment by Kurgan-** [comment] 2023-09-07 19:20
EDIT: Found an OLD post with the same issue, but no more information / solutions / answers here

https://help.nextcloud.com/t/am-i-going-mad-the-details-option-is-gone-from-the-file-context-menu/49232

**Comment by joshtrichards** [comment] 2023-09-09 15:42
Unable to reproduce this so far.

- If you click on the file size does the detail sidebar come up properly?
- **Note the three dots menu isn't the same as the right-click menu.** Your first screenshot looks like it's actually the right-click menu, not the three dots menu (despite the cursor position). Though *Details* should be an option under either access mode... Does *Details* appear in your first scenario if you do select the three dots (i.e. *not* by right-clicking)? Your second screenshot *is* from the three dots menu. So for that scenario I'd be curious what the opposite does: if you right click in the second situation do you see a similar menu as from your first screenshot? And does it have *Details*?
- Can you check your browser console for anything interesting while testing?
- You stated you're not using encryption, but I see the optional `end_to_end_encryption` app installed - is it active?

**Comment by Kurgan-** [comment] 2023-09-09 18:53
Yes, it's strange and it's repeatable on one installation and not on its twin one. The only difference is that the installation with the issue has E2EE enabled (but the issue is present in folders and files that are not encrypted. Only one folder is encrypted and it's currently empty, it was just a test. 

Anyway I'll answe your questions:
- I had answer "no" to the encryption question becase I supposed it was about file system, server side encryption. As I stated, I have E2EE enabled on a single folder that's empty and of course the issue is on non-encrypted files.

- In the first scenario, if I left click on the file size, nothing happens at all
- In the first scenario, if I right click, or if I click on the three dots, in both cases there is no "details" in the menu.
- In the second scenario (when I click on "recent") both right clicking on the file and left clicking on the three dots brings up the menu, complete with "details". Also in this scenario left clicking on the file size brings up the sidebar as it should. So this scenario works as intended.
- In the console, nothing happens at all (cleared it then tried everything in the first and then in the second scenario, there is nothing at all)

PS: If I left click on the "sharing" icon, that one works and opens the sidebar in both scenarios.

**Comment by Kurgan-** [comment] 2023-09-09 18:54
OK, I disabled E2EE and everything works as it should. I belive it's solved, and it's just one of the many many many issues of E2EE.

**Comment by nextcloud-command** [comment] 2023-10-10 00:13
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by joshtrichards** [comment] 2023-10-14 16:41
That at least confirms it's E2EE being enabled that triggers this. Unfortunately I'm still not able to reproduce this behavior even with the E2EE app enabled at the moment. But I've removed the "needs info" tag to keep this bug report open.

**Comment by olheem** [comment] 2024-02-02 18:13
I have the same problem after configuring a E2EE encrypted folder.

**Comment by skjnldsv** [comment] 2024-07-31 16:35
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-07-31 16:35 UTC
Labels: bug, 0. Needs triage, feature: files, feature: encryption (client-side), 27-feedback
