### ISSUE TITLE
check for app compatibility at start of occ upgrade, so upgrade doesn't disable apps

### ISSUE THREAD

**Issue by brad2014** [nextcloud/server#35001] opened 2022-11-07 10:41 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
My nextcloud server upgraded (automatically?) from nextcloud 24 to nextcloud 25, and all my users were locked out because user_external was disabled without my noticing, since it wasn't (yet) compatible with the new version.

**Describe the solution you'd like**
1. Before the upgrade is initiated, `occ upgrade` should check to make sure all enabled apps (at their latest available version) are compatible with the new version.
2. If not, it should fail with something like `ERROR: enabled app user_external is not compatible with new version. Use --force to override`
3. Then `occ upgrade` should never cause an app to be disabled - With the --force flag, it should force-enable all the previously enabled yet-incompatible apps.  Without the --force flag, it should gracefully reject the upgrade.

**Describe alternatives you've considered**
The admin, once they realize disaster has struck, can recover by manually running `occ app:enable --force users_external` after the upgrade.

**Comment by joshtrichards** [comment] 2024-04-24 15:28
Duplicate of nextcloud/updater#401

**Closed by joshtrichards** 2024-04-24 15:28 UTC
Labels: enhancement, 0. Needs triage, feature: install and update
