### ISSUE TITLE
Customize the name of the "share link"

### ISSUE THREAD

**Issue by alexbijma** [nextcloud/server#17657] opened 2019-10-23 10:50 UTC
Currently if you create a share link the name of the link in nextcloud is "share link". In case you add multiple links there is a list of multiple times "Share link". But which one did you share with who? With the "Share Renamer app" it is possible to rename the link itself, but the name which is displayed in the list of links is still default "share link".

It would be nice to have an option to rename that name or use the renamed link as the name(last part of the link). So you can identify which link it is about just viewing the list of links.
That way it is clear which link it is and if you want to delete one you don't have to verify the link etc.

**Comment by wiswedel** [comment] 2019-10-28 20:19
duplicate of https://github.com/nextcloud/server/issues/15500

**Closed by wiswedel** 2019-10-28 20:19 UTC
Labels: 0. Needs triage, enhancement
