### ISSUE TITLE
Share link: "Hide download" also hides notice icon

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/server#14629] opened 2019-03-11 15:05 UTC
### Steps to reproduce
1. Share a folder via link
2. Store a notice for the recipient and select "hide download" in the share link menu
3. Copy & Open the link

### Expected behaviour
The notice symbol in the title bar should by visible, even if the download option is removed

### Actual behaviour
The notice symbol is removed together with the download option (complete header-right <div> is removed)

### Server configuration
**Operating system**: Debian 9
**Web server:** Apache 2.4
**Database:** MariaDB
**PHP version:** 7.2
**Nextcloud version:** 15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:** updated
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 65.0.2, Chrome 72.0.3626.121
**Operating system:** Windows 7

**Comment by wiswedel** [comment] 2020-03-12 08:51
duplicate of https://github.com/nextcloud/server/issues/13617

**Closed by wiswedel** 2020-03-12 08:51 UTC
Labels: 0. Needs triage, bug
