### ISSUE TITLE
[Bug]: Cannot List or Search for Apps in Nextcloud Server

### ISSUE THREAD

**Issue by olaulau** [nextcloud/server#48964] opened 2024-10-29 09:45 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi ;

A while ago, it was possible to list all available apps and search for a specific app in the store to install if.
Since a few versions, neither is possible :
- to list all available apps (only some categories in the left menu
- to search for an app (search box seems totally broken

Am I missing something ?? or does it need a fix ?
thanks.

### Steps to reproduce

1. login as admin
2. go to  apps
3. try to search for an existing app
-> nothing happens

### Expected behavior

- find the app you are searching for
- being able to list all available apps (so we can at least use in-browser find function)

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-11-05 14:03
Duplicate of #45558

**Closed by joshtrichards** 2024-11-05 14:03 UTC
Labels: bug, 0. Needs triage, feature: apps management, feature: search, 30-feedback
