### ISSUE TITLE
[NC 21] An unhandled exception has been thrown - Error during upgrade process (integrity check)

### ISSUE THREAD

**Issue by freijon** [nextcloud/server#25746] opened 2021-02-22 13:53 UTC
### Issue

When trying to upgrade to Version 21.0.0 I get the following error at the integrity check:

```
Starting code integrity check...
An unhandled exception has been thrown:
TypeError: decbin(): Argument #1 ($num) must be of type int, float given in /usr/share/webapps/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Math/BigInteger.php:662
Stack trace:
#0 /usr/share/webapps/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Math/BigInteger.php(662): decbin()
#1 /usr/share/webapps/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/RSA.php(2848): phpseclib\Math\BigInteger->toBits()
#2 /usr/share/webapps/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/RSA.php(3177): phpseclib\Crypt\RSA->_rsassa_pss_verify()
#3 /usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php(371): phpseclib\Crypt\RSA->verify()
#4 /usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php(571): OC\IntegrityCheck\Checker->verify()
#5 /usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php(592): OC\IntegrityCheck\Checker->verifyCoreSignature()
#6 /usr/share/webapps/nextcloud/lib/private/Updater.php(288): OC\IntegrityCheck\Checker->runInstanceVerification()
#7 /usr/share/webapps/nextcloud/lib/private/Updater.php(132): OC\Updater->doUpgrade()
#8 /usr/share/webapps/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#9 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#10 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#11 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#12 /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#13 /usr/share/webapps/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#14 /usr/share/webapps/nextcloud/console.php(100): OC\Console\Application->run()
#15 /usr/share/webapps/nextcloud/occ(11): require_once('/usr/share/weba...')
```

### Steps to reproduce
1. Upgrade package community/nextcloud to version 21.0.0-7 on ArchLinux
2. Run `occ upgrade`

### Server configuration

**Operating system:** Archlinux

**Web server:** apache 2.4.46

**Database:** mariadb 10.5.8

**PHP version:** php 8.0.2

**Nextcloud version:** 21.0.0 (no access to Admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from Nextcloud 20.0.6

**Where did you install Nextcloud from:** Package manager

**List of activated apps:**
<details>
<summary>App list</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - calendar: 2.1.3
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.4.3
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_downloadactivity: 1.10.0
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.8
  - notes: 4.0.2
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - nextcloud_announcements
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud",
            "***REMOVED SENSITIVE VALUE***",
            "192.168.178.5"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/wapps",
                "writable": true
            }
        ],
        "dbtype": "mysql",
        "version": "20.0.6.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "twofactor_rcdevsopenotp",
            "files_retention",
            "files_markdown",
            "files_downloadactivity"
        ],
        "theme": "",
        "loglevel": 0,
        "maintenance": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

### Logs

I don't think logs are needed for this kind of error. If I'm mistaken, please let me know and I'll update the post

**Comment by AlexanderStein** [comment] 2021-02-22 20:12
This seems to be a PHP8 related bug. When executing occ upgrade using php7 all is fine.

**Comment by mrohnstock** [comment] 2021-02-23 09:54
well... dirty hack for this issue:

change `3rdparty/phpseclib/phpseclib/phpseclib/Math/BigInteger.php` line `662` from:

```
$bits = str_pad(decbin(hexdec(substr($hex, $i, 8))), 32, '0', STR_PAD_LEFT) . $bits;
```

to

```
$bits = str_pad(decbin(intval(hexdec(substr($hex, $i, 8)))), 32, '0', STR_PAD_LEFT) . $bits;
```

**Comment by terrafrost** [comment] 2021-02-23 18:22
This is an issue on 32-bit PHP 8 installations. On those systems integers are signed 32-bit integers and so hexdec('FFFFFFFF') returns a float because it's out of range for a signed 32-bit integer (who's largest positive value is 0x7FFFFFFF)

It'd be nice if PHP 8 could accept floats for this reason but I can look into a phpseclib fix as well as time permits!

**Comment by Schrekkorr** [comment] 2021-02-23 19:04
> well... dirty hack for this issue:
> 
> change `3rdparty/phpseclib/phpseclib/phpseclib/Math/BigInteger.php` line `662` from:
> 
> ```
> $bits = str_pad(decbin(hexdec(substr($hex, $i, 8))), 32, '0', STR_PAD_LEFT) . $bits;
> ```
> 
> to
> 
> ```
> $bits = str_pad(decbin(intval(hexdec(substr($hex, $i, 8)))), 32, '0', STR_PAD_LEFT) . $bits;
> ```
> 
> it at least made the `code integrity check` get executed successfully on my system.

This results in another error because the checksums don't match anymore.

**Comment by Terin** [comment] 2021-02-24 06:16
Issue is present on Arch Linux ARM for me as well, same package versions. Surprised that the PHP 8 installation is 32-bit, but glad the issue is identified.

**Comment by AlexanderStein** [comment] 2021-02-24 08:09
> Issue is present on Arch Linux ARM for me as well, same package versions. Surprised that the PHP 8 installation is 32-bit, but glad the issue is identified.

Yeah, in my case it's an Raspberry Pi 4 using Arch Linux ARM (32-Bit) as well.

> This is an issue on 32-bit PHP 8 installations. On those systems integers are signed 32-bit integers and so hexdec('FFFFFFFF') returns a float because it's out of range for a signed 32-bit integer (who's largest positive value is 0x7FFFFFFF)

While I do understand the technical background, this still baffles me. I didn't expect a newer PHP version to break like this.

**Comment by terrafrost** [comment] 2021-02-24 16:17
I can't reproduce it on 3v4l.org: https://3v4l.org/V92vk

Maybe it's only an issue on the ARM builds.

I have an older Raspberry Pi at my house. I'll have to play around with it.

**Comment by terrafrost** [comment] 2021-02-24 16:40
Actually, ignore my last post lol. I created a bug report on https://bugs.php.net/bug.php?id=80796 . I'll try to look into updating phpseclib's behavior in the mean time! Probably within the next few days

**Comment by terrafrost** [comment] 2021-02-26 21:15
I think https://github.com/phpseclib/phpseclib/commit/b2b867f032949fab435370061a2a00dc31b22d9a should fix the issue on the phpseclib end.

**Comment by Terin** [comment] 2021-02-27 04:36
That did the trick! Thank you so much for patching that up. Had to figure out that Arch Linux uses the 2.0 branch, but after copying that over and fixing up some php-fpm configuration, it's good to go on my end.

**Comment by rEnr3n** [comment] 2021-04-11 13:36
The fix has been released on phpseclib v2.0.31 which was included in NC v21.0.1.

**Comment by szaimen** [comment] 2021-07-02 12:45
Great! So I am closing this.

**Closed by szaimen** 2021-07-02 12:45 UTC
Labels: 0. Needs triage, bug

**Comment by jamesstanw** [comment] 2021-08-18 03:12
Perhaps not so fixed?
This is what I'm getting in my NC 21.0.4 logs:
Error: pack(): Type H: illegal hex digit Z at /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/RSA.php#1147
This is PHP v. 8.0.9
I ran php -m but I'm not seeing phpseclib:
`[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
ldap
libsmbclient
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
smbclient
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
`
Is this my problem?
