### ISSUE TITLE
[Bug]: Nextcloud 28.0.x does not support dragging and dropping files

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#42561] opened 2024-01-03 16:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 28.0.x does not support dragging files, in practice if you take any file and drag it into the folder via Google Chrome via the web it is not loaded in the case of PDF files it is opened in Chrome but not loaded

### Steps to reproduce

1. drag files to the nextcloud folder via web via chrome
2.
3.

### Expected behavior

I expect the file to be uploaded but instead it is opened

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-01-03 21:48
Duplicate of...various.
Already fixed in #42366 / #42409
It'll be in v28.0.2

**Closed by joshtrichards** 2024-01-03 21:48 UTC
Labels: bug, 0. Needs triage, feature: files, 28-feedback
