### ISSUE TITLE
[Regression in 25.0.2rc2] Dashboard contents flow out of their content boxes

### ISSUE THREAD

**Issue by cetcondor** [nextcloud/server#35585] opened 2022-12-04 12:10 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After an update from 25.0.1 to 25.0.2rc2 we realized that the dashboard contents are flowing out of their boxes. It occurs both in Firefox 107 and Chromium 108, both with cleared cache. Screenshot shows the problem (some info was blurred by me for privacy reasons).

![grafik](https://user-images.githubusercontent.com/40753639/205489553-5ce94018-428e-4fe4-bf39-0d2235b64d42.png)

### Steps to reproduce

1. Change to beta channel and update to 25.0.2rc2
2. Go to Nextcloud dashboard

### Expected behavior

No overflow should happen

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
probably not relevant because of CSS problem
```

### List of activated Apps

```shell
probably not relevant because of CSS problem
```

### Nextcloud Signing status

```shell
probably not relevant because of CSS problem
```

**Comment by szaimen** [comment] 2022-12-04 13:35
Sorry, I cannot reproduce this. Please clear you broser chache, run `occ maintenance:repair` and try again.

**Comment by XueSheng-GIT** [comment] 2022-12-05 11:54
@cetcondor Do you have polls installed? Then it most probably is https://github.com/nextcloud/polls/issues/2693

**Comment by szaimen** [comment] 2022-12-05 11:55
Thanks @XueSheng-GIT!
Duplicate of https://github.com/nextcloud/polls/issues/2693 then.

**Closed by szaimen** 2022-12-05 11:55 UTC
Labels: bug, needs info, 0. Needs triage
