### ISSUE TITLE
Issue when downloading ZIP-file bigger than 2 GB

### ISSUE THREAD

**Issue by nextUser2018** [nextcloud/server#11981] opened 2018-10-22 14:51 UTC
Downloading a ZIP-File with more than 2 GB in size directly from the nextcloud webinterface or the Windows Desktop Client results in an abort of the download. The downloaded size is always 1,9GB. The log shows the following error:

PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/nextcloud/lib/private/Files/Filesystem.php:797\nStack trace:\n#0 /var/www/nextcloud/lib/private/Files/View.php(2054): OC\\Files\\Filesystem::normalizePath('/path/toFile...')\n#1 /var/www/nextcloud/lib/private/Files/View.php(1180): OC\\Files\\View->unlockFile('/pathToFile...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 /var/www/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown in /var/www/nextcloud/lib/private/Files/Filesystem.php on line 797

The issue does not occure when using another file format.

### Steps to reproduce
1. Upload a ZIP-File bigger 2 GB (2,2GB was used for test purposes)
2. Download via nextcloud web interface

### Expected behaviour
The file should be downloaded with the correct size and content without errors in the log.

### Actual behaviour
see above

### Server configuration

**Operating system:** Debian 9 64 Bit (latest version)

**Web server:** Apache 2.4.25 (latest version)

**Database:** MySQL 10.1.26

**PHP version:** 7.0.30 as Apache module

**Nextcloud version:** 14.0.3.0

**Where did you install Nextcloud from:** Direct Download from nextCloud / installation through experienced Service Provider

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.0.1
  - admin_audit: 1.4.0
  - admin_notifications: 1.0.2
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - deck: 0.4.1
  - dicomviewer: 1.0.2
  - encryption: 2.2.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_antivirus: 1.3.2
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - firstrunwizard: 2.3.0
  - flowupload: 0.0.8
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
Disabled:
  - activity
  - announcementcenter
  - caniupdate
  - federation
  - files_automatedtagging
  - files_external
  - files_retention
  - files_videoplayer
  - gallery
  - ransomware_protection
  - survey_client
  - tasks
  - user_ldap
  - user_usage_report
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/ ***REMOVED SENSITIVE VALUE***",
",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***"
    }
}</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox 62.0.3 (64-Bit) & Edge 42.17134.1.0 & Internet Explorer 11.2312.14393.0

**Operating system:** Win 10 / Windows Server 2016

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/nextcloud/lib/private/Files/Filesystem.php:797\nStack trace:\n#0 /var/www/nextcloud/lib/private/Files/View.php(2054): OC\\Files\\Filesystem::normalizePath('/path/toFile...')\n#1 /var/www/nextcloud/lib/private/Files/View.php(1180): OC\\Files\\View->unlockFile('/pathToFile...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 /var/www/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown in /var/www/nextcloud/lib/private/Files/Filesystem.php on line 797
</details>

**Comment by CHazz** [comment] 2018-10-29 15:51
confirmed .. autocreated zip contain multiple big files never download complete .. NC13 lates.

**Comment by skjnldsv** [comment] 2019-04-30 08:33
Duplicate of #10893

**Closed by skjnldsv** 2019-04-30 08:34 UTC
Labels: bug, feature: files, feature: filesystem
