### ISSUE TITLE
Share links not working in group folders with advanced permissions

### ISSUE THREAD

**Issue by priethor** [nextcloud/server#17037] opened 2019-09-06 17:18 UTC
### Steps to reproduce
1. Create a group folder with Advanced Permissions enabled
2. Create a subfolder inside the group folder
3. Share the subfolder via link with "drop file" permissions

### Expected behaviour
Users with the link should be able to drop files and upload them

### Actual behaviour
Users with the link can drop files but after the upload, an error is shown and the file is not saved

### Server configuration

**Operating system**: 
Ubuntu Server 16.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.7
**PHP version:**
7.3
**Nextcloud version:**
Nextcloud 16.0.4, GroupFolders 4.1.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 16.0.3, etc, since owncloud 9 :)
**Where did you install Nextcloud from:**
Web Installer
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - apporder: 0.7.1
  - calendar: 1.7.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - deck: 0.6.6
  - drawio: 0.9.3
  - event_update_notification: 0.3.4
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_accesscontrol: 1.6.0
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_fulltextsearch: 1.3.6
  - files_linkeditor: 1.0.10
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.5.0
  - files_readmemd: 1.1.1
  - files_retention: 1.5.1
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trackdownloads: 1.5.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - fulltextsearch: 1.3.6
  - fulltextsearch_elasticsearch: 1.3.6
  - gallery: 18.3.0
  - groupfolders: 4.1.0
  - impersonate: 1.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.4.0
  - passman: 2.3.2
  - password_policy: 1.6.0
  - passwords: 2019.8.1
  - piwik: 0.5.3
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - recommendations: 0.4.0
  - sentry: 5.0.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - socialsharing_email: 1.0.5
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - w2g2: 2.2.8
  - workflowengine: 1.6.0
Disabled:
  - circles
  - encryption
  - external
  - files_automatedtagging
  - files_fulltextsearch_tesseract
  - mail
  - richdocuments
  - socialsharing_twitter

</details>

**Are you using external storage, if yes which one:** Main storage in S3 bucket

**Are you using encryption:**no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Chrome/Firefox/Safari latest versions
**Operating system:**
Windows 10 and OsX
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"ZpKG2HGVtfCo8nsFnsPD","level":3,"time":"2019-09-06T17:03:05+00:00","remoteAddr":"213.98.113.248","user":"--","app":"public","method":"PUT","url":"\/public.php\/webdav\/asdf.xlsx","message":{"Exception":"Error","Message":"Call to a member function getType() on bool","Code":0,"Trace":[{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/cloud\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/home\/cloud\/public_html\/apps\/dav\/appinfo\/v1\/publicwebdav.php","line":107,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/cloud\/public_html\/public.php","line":79,"args":["\/home\/cloud\/public_html\/apps\/dav\/appinfo\/v1\/publicwebdav.php"],"function":"require_once"}],"File":"\/home\/cloud\/public_html\/apps\/dav\/lib\/Connector\/Sabre\/ServerFactory.php","Line":147,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.4.1"}
{"reqId":"ZpKG2HGVtfCo8nsFnsPD","level":3,"time":"2019-09-06T17:03:05+00:00","remoteAddr":"213.98.113.248","user":"--","app":"core","method":"PUT","url":"\/public.php\/webdav\/asdf.xlsx","message":{"Exception":"Error","Message":"Call to a member function getType() on bool","Code":0,"Trace":[{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/cloud\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/home\/cloud\/public_html\/apps\/dav\/appinfo\/v1\/publicwebdav.php","line":107,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/cloud\/public_html\/public.php","line":79,"args":["\/home\/cloud\/public_html\/apps\/dav\/appinfo\/v1\/publicwebdav.php"],"function":"require_once"}],"File":"\/home\/cloud\/public_html\/apps\/dav\/lib\/Connector\/Sabre\/ServerFactory.php","Line":147,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.4.1"}
</details>

**Comment by tlinna** [comment] 2019-11-14 11:56
Found this out today the hard way, just like described. After removing advanced permissions from the group folder existing file drops work again.

Operating system:
Ubuntu Server 18.04 LTS
Web server:
Nginx 1.16.1
Database:
PostgreSQL 11.5
PHP version:
7.3
Nextcloud version:
Nextcloud 16.0.6, GroupFolders 4.1.4
Updated from an older Nextcloud/ownCloud or fresh install:
Updated from 15.x

**Comment by fschrempf** [comment] 2021-04-09 09:05
This looks like a duplicate of https://github.com/nextcloud/groupfolders/issues/923 and should be fixed in recent stable releases (see https://github.com/nextcloud/groupfolders/pull/1224). Can you confirm?

**Comment by szaimen** [comment] 2021-07-02 12:21
Seems like it was already fixed in https://github.com/nextcloud/groupfolders/pull/1224

**Closed by szaimen** 2021-07-02 12:21 UTC
Labels: 0. Needs triage, bug
