### ISSUE TITLE
[Bug]:  nextcloud becoming garbage after installing collabora build in app [is there any stable version in terms of upgrades ? +  reliable docs missing]

### ISSUE THREAD

**Issue by zh54tg234f** [nextcloud/server#35441] opened 2022-11-26 02:49 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Bug]:  nextcloud becoming garbage after installing collabora build in app
webserver is timing out, no way its my nginx config or what ever i tried it with the docker test image
even the installing recommended apps leads into death loop

why im here? guess why since version 19+ the updates are a mess and the new features are rendering nextcloud into unsuable gargabe. very sad to see a good project die like this.

i setup my collabora server separately, badibu 2 hours after the update my instance is trash.
i would have to do a reversal of the update. the given docs are complete trash, using collabora is just trouble (looks like design) and the updates are nice in terms of features but as i said it renders 90% of the time the server into being broken.

im done with it. stop pushing new features and work on stability. your reputation for me is finally gone. i won't fix next few hundred hours this mess. as soon as you have different data directory or want collabora (dammet even just install recommended apps) you turn a great product into a nightmare of maintenance.

### Steps to reproduce

1. download nextcloud
2. install recommend apps, see its not responding (at least for me, even the dumb testing docker images - no i dont try it on retarded hardware)
3. or how about trying to get collabora working?

### Expected behavior

good docs (up to date- or at least stop changing basic stuff) without moving the urls !
guides with simple copy and paste nginx, apache2 and caddy configs for regular and collabora

or just stop drop the support for it. i mean your basically just vaporizing peoples time with this.
no new features unless you made stable af updates , ez backups capabilities

i mean you ripped the new great 25 version with the following issues https://github.com/nextcloud/server/issues/35435 
https://github.com/nextcloud/server/issues/32310

i dont know what to say but, get your stuff together. everyone wants you to succeed. make a donation page and the funds will come but please stop this releasing for half finished products its hurting the brand, its hurting the user base and im honestly sick of it by now.

bye, i wont touch nextcloud for a year. im running nc servers since a couple of years (personal usage + setup for friends, voluntary support for local communities) so i suffered enough!

i mean it was a meme the first years and thinks got better, but nowadays it's just unacceptable for me. (im sorry, i would love to contribute but i have neither the time nor the trade to do so, that's why i mentioned opening up for community donations)

seriously stop moving docs and guides around, keep them sticky easy to find, let it become widespread, linked on the website, on the git repos and maybe one day it has good search engine ranking.

most the stuff i find when i  search for issues are other people crying , which is sad since nextcloud is great overall.
making it robust would be nothing anyone in the community could reject their support for it.

still have a great day, year, see ya.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
collabora / recommended
```

**Comment by szaimen** [comment] 2022-11-26 09:15
Duplicate of https://github.com/nextcloud/richdocuments/issues/1282

**Closed by szaimen** 2022-11-26 09:15 UTC
Labels: bug, 0. Needs triage
