### ISSUE TITLE
NC17 Cannot unshare folders

### ISSUE THREAD

**Issue by iniOr** [nextcloud/server#19293] opened 2020-02-04 10:58 UTC
Hi,

I can't remove a share to another user of my NC server.
This is applying to all shares, all users : none of them can be unshared.

### Steps to reproduce
1. Create a folder
2. Share it
3. Try to remove the share -> failure.

[https://cloud.octarine.io/s/iPwoppNm4QrBdX4/preview](url)

### Expected behaviour
The share should be removed.

### Actual behaviour
An error is shown and the share is not removed.

### Server configuration

**Operating system:** Debian 10 x64

**Web server:** ii apache2 2.4.38-3+deb10u3 amd64

**Database:** ii mariadb-server 1:10.3.18-0+deb10u1

**PHP version:** ii php7.3 7.3.14-5+0~20200202.52+debian10~1.gbpa71879

**Nextcloud version:** Nextcloud 17.0.3 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Previous stable release 17.0.2?

**Where did you install Nextcloud from:** official website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - analytics: 2.0.0
  - announcementcenter: 3.6.1
  - audioplayer: 2.9.0
  - bookmarks: 2.3.4
  - calendar: 2.0.1
  - camerarawpreviews: 0.7.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - cospend: 0.3.2
  - data_request: 1.4.0
  - dav: 1.13.0
  - deck: 0.8.0
  - encryption: 2.5.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_antivirus: 2.2.1
  - files_downloadactivity: 1.6.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trackdownloads: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - forms: 1.1.0
  - gallery: 18.4.0
  - gpxedit: 0.0.12
  - gpxmotion: 0.0.10
  - gpxpod: 4.1.1
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.2
  - maps: 0.1.4
  - news: 14.1.2
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.2
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocr: 5.0.7
  - ocsms: 2.1.6
  - password_policy: 1.7.0
  - piwik: 0.5.3
  - polls: 1.1.6
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quicknotes: 0.2.2
  - recommendations: 0.5.0
  - richdocuments: 3.5.2
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - socialsharing_diaspora: 1.0.5
  - socialsharing_email: 1.0.6
  - socialsharing_facebook: 1.0.5
  - socialsharing_twitter: 1.0.5
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - uploaddetails: 0.1.2
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_notifications
  - afterlogic
  - bruteforcesettings
  - circles
  - dashboard
  - dashboardcharts
  - drawio
  - drop_account
  - event_update_notification
  - files_retention
  - impersonate
  - jsloader
  - mindmaps
  - previewgenerator
  - radio
  - ransomware_detection
  - ransomware_protection
  - socialsharing_googleplus
  - twofactor_totp
  - user_ldap
  - weather
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.octarine.io"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.octarine.io\/",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "theme": "",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "",
        "updater.release.channel": "stable",
        "data-fingerprint": "1780097d5b25888d3ac0b8c81046473a",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "app_install_overwrite": [
            "calendar",
            "forms",
            "dashboard"
        ],
        "mysql.utf8mb4": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** ii  firefox 72.0.2+linuxmint1+tricia 

**Operating system:** Linux Mint 19.3 Tricia

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

https://cloud.octarine.io/s/596JZwES9zAn3dg/download

</details>

Thanks for your help,

Denis

**Comment by kesselb** [comment] 2020-02-04 11:03
Solution: Disable the maps app.

Closing as duplicate of: https://github.com/nextcloud/maps/issues/280

**Closed by kesselb** 2020-02-04 11:03 UTC
Labels: 0. Needs triage, bug

**Comment by ajm135x** [comment] 2020-02-23 16:42
I just deployed Nextcloud 17.0.3 without any maps app or social apps. I still cannot unshare.

**Comment by ajm135x** [comment] 2020-02-23 19:46
> I just deployed Nextcloud 17.0.3 without any maps app or social apps. I still cannot unshare.

I noticed that the issue does not occur in Edge or Mozilla. Just Chrome.

**Comment by ajm135x** [comment] 2020-02-23 19:47
> > I just deployed Nextcloud 17.0.3 without any maps app or social apps. I still cannot unshare.
> 
> I noticed that the issue does not occur in Edge or Mozilla. Just Chrome.

I found the issue. It was an Adblocker chrome plugin.
