### ISSUE TITLE
LDAP / AD integration UI: none of the buttons have any effect

### ISSUE THREAD

**Issue by jonasboettcher** [nextcloud/server#24314] opened 2020-11-23 18:09 UTC
### Steps to reproduce
1. Set up Nextcloud version 19.0.4
2. Enable LDAP user and group backend version 1.9.1
3. Try to set up the "LDAP / AD Integration"

### Expected behaviour
Should be able to use the mask and all buttons.

### Actual behaviour
None of the buttons have any effect. The continue button is greyed out and I am not able to get further in the wizard.

The issue is described on: https://help.nextcloud.com/t/ldap-ad-integration-nextcloud-18-0-1/73650

### Server configuration

**Operating system:** Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64

**Web server:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 8.0.21

**PHP version:** 7.4.3

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-19.0.3.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.internezzo.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 1,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                     |
| homeFolderNamingRule          |                                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                                     |
| ldapAgentName                 | CN=LDAP for Nextcloud,OU=services,OU=users,OU=example,DC=example,DC=local                       |
| ldapAgentPassword             | ***                                                                                                   |
| ldapAttributesForGroupSearch  |                                                                                                       |
| ldapAttributesForUserSearch   |                                                                                                       |
| ldapBackupHost                |                                                                                                       |
| ldapBackupPort                |                                                                                                       |
| ldapBase                      | DC=example,DC=local                                                                                |
| ldapBaseGroups                | DC=example,DC=local                                                                                |
| ldapBaseUsers                 | DC=example,DC=local                                                                                |
| ldapCacheTTL                  | 600                                                                                                   |
| ldapConfigurationActive       | 1                                                                                                     |
| ldapDefaultPPolicyDN          |                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                                                       |
| ldapExpertUUIDUserAttr        |                                                                                                       |
| ldapExpertUsernameAttr        |                                                                                                       |
| ldapExtStorageHomeAttribute   |                                                                                                       |
| ldapGidNumber                 | gidNumber                                                                                             |
| ldapGroupDisplayName          | cn                                                                                                    |
| ldapGroupFilter               | (|(cn=Ausbildungsverantwortliche)(cn=Leitende Angestellte)(cn=Alle Mitarbeiter)(cn=Mitarbeiter Stab)) |
| ldapGroupFilterGroups         | Ausbildungsverantwortliche;Leitende Angestellte;Alle Mitarbeiter;Mitarbeiter Stab                     |
| ldapGroupFilterMode           | 0                                                                                                     |
| ldapGroupFilterObjectclass    |                                                                                                       |
| ldapGroupMemberAssocAttr      |                                                                                                       |
| ldapHost                      | ldap://192.168.105.51                                                                                 |
| ldapIgnoreNamingRules         |                                                                                                       |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))          |
| ldapLoginFilterAttributes     |                                                                                                       |
| ldapLoginFilterEmail          | 1                                                                                                     |
| ldapLoginFilterMode           | 0                                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                                     |
| ldapMatchingRuleInChainState  | unknown                                                                                               |
| ldapNestedGroups              | 0                                                                                                     |
| ldapOverrideMainServer        |                                                                                                       |
| ldapPagingSize                | 500                                                                                                   |
| ldapPort                      | 389                                                                                                   |
| ldapQuotaAttribute            |                                                                                                       |
| ldapQuotaDefault              |                                                                                                       |
| ldapTLS                       | 0                                                                                                     |
| ldapUserAvatarRule            | default                                                                                               |
| ldapUserDisplayName           | displayname                                                                                           |
| ldapUserDisplayName2          |                                                                                                       |
| ldapUserFilter                | (&(|(objectclass=person)))                                                                            |
| ldapUserFilterGroups          |                                                                                                       |
| ldapUserFilterMode            | 0                                                                                                     |
| ldapUserFilterObjectclass     | person                                                                                                |
| ldapUuidGroupAttribute        | auto                                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                                  |
| turnOffCertCheck              | 0                                                                                                     |
| turnOnPasswordChange          | 0                                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                                     |
+-------------------------------+-------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Chromium Version 87.0.4280.66 (Official Build) snap (64-bit)

**Operating system:** Ubuntu 20.04.1 LTS

### Logs
The Logs doesn’t show any information about the AD integration.

#### Web server error log
<details>
<summary>Web server error log</summary>

```
The Logs doesn’t show any information about the AD integration.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
The Logs doesn’t show any information about the AD integration.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
2globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
globals.js:61 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
$ @ globals.js:61
4globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
globals.js:61 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
globals.js:61 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
3globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
globals.js:61 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
session-heartbeat.js:97 session heartbeat polling started
130globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
/apps/user_ldap/ajax/getConfiguration.php:1 Failed to load resource: the server responded with a status of 500 ()
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
configModel.js?v=7113bb86-0:166 will not save undefined key: ldap_host
set @ configModel.js?v=7113bb86-0:166
5globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
/apps/user_ldap/ajax/wizard.php:1 Failed to load resource: the server responded with a status of 500 ()
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
configModel.js?v=7113bb86-0:166 will not save undefined key: ldap_base
set @ configModel.js?v=7113bb86-0:166
```
</details>

**Comment by kesselb** [comment] 2020-11-23 18:59
Duplicate of https://github.com/nextcloud/server/issues/16194

**Closed by kesselb** 2020-11-23 18:59 UTC
Labels: 0. Needs triage, bug
