### ISSUE TITLE
"occ user:setting admin settings email" only handles oc_preferences, but not oc_accounts etc.

### ISSUE THREAD

**Issue by robert-scheck** [nextcloud/server#3554] opened 2017-02-20 22:34 UTC
### Steps to reproduce
1. Get Nextcloud 11.0.1
2. `./occ maintenance:install --data-dir=/var/www/html/data --database mysql --database-name nextcloud --database-user nextcloud --database-pass nextcloud --admin-user admin --admin-pass admin`
3. Logon at Nextcloud
4. Visit http://localhost/settings/personal and set your e-mail address, e.g. `root@example.net`
5. Logout from Nextcloud
6. `./occ user:setting admin settings email admin@example.net`
7. Logon at Nextcloud
8. Visit http://localhost/settings/personal again and still find `root@example.net` as e-mail address
9. `mysqldump --complete-insert nextcloud | grep admin@example.net` will return:
> ```INSERT INTO `oc_preferences` (`userid`, `appid`, `configkey`, `configvalue`) VALUES ('admin','core','lang','de_DE'),('admin','core','timezone','UTC'),('admin','firstrunwizard','show','0'),('admin','login','lastLogin','1487671252'),('admin','settings','email','admin@example.net');```
10. `mysqldump --complete-insert nextcloud | grep root@example.net` will return:
> ```INSERT INTO `oc_accounts` (`uid`, `data`) VALUES ('admin','{\"avatar\":{\"scope\":\"contacts\"},\"displayname\":{\"value\":\"admin\",\"scope\":\"contacts\"},\"email\":{\"value\":\"root@example.net\",\"scope\":\"contacts\"},\"website\":{\"value\":\"\",\"scope\":\"private\"},\"address\":{\"value\":\"\",\"scope\":\"private\"},\"phone\":{\"value\":\"\",\"scope\":\"private\"},\"twitter\":{\"value\":\"\",\"scope\":\"private\"}}');```
> ```INSERT INTO `oc_cards` (`id`, `addressbookid`, `carddata`, `uri`, `lastmodified`, `etag`, `size`) VALUES (1,2,'BEGIN:VCARD\r\nVERSION:4.0\r\nPRODID:-//Sabre//Sabre VObject 4.1.1//EN\r\nUID:sabre-vobject-59fdee93-4255-49b7-ac8e-cbc53d5535eb\r\nUID:admin\r\nFN:admin\r\nN:admin;;;;\r\nEMAIL;TYPE=OTHER:root@example.net\r\nCLOUD:admin@nextcloud.example.net\r\nEND:VCARD\r\n','Database:admin.vcf',1487671266,'48a609bd970f19bb7bafe4ebe2550b12',244);```
> ```INSERT INTO `oc_cards_properties` (`id`, `addressbookid`, `cardid`, `name`, `value`, `preferred`) VALUES (13,2,1,'UID','sabre-vobject-59fdee93-4255-49b7-ac8e-cbc53d5535eb',0),(14,2,1,'UID','admin',0),(15,2,1,'FN','admin',0),(16,2,1,'N','admin;;;;',0),(17,2,1,'EMAIL','root@example.net',0),(18,2,1,'CLOUD','admin@nextcloud.example.net',0);```
11. Ouch, nice inconsistency now :-(

### Expected behaviour
`occ user:setting admin settings email admin@example.net` should handle all, `oc_preferences` table and `oc_accounts` table etc.

Note, `occ user:setting admin settings email admin@example.net` only seems to work fine before the first login to Nextcloud, because with that login, the value from `oc_preferences` seems to be copied to the other database tables.

### Actual behaviour
`occ user:setting admin settings email admin@example.net` only handles `oc_preferences` table, but not `oc_accounts` table etc.

### Server configuration
**Operating system**: Red Hat Enterprise Linux 7.3, but doesn't matter here anyway.

**Web server:** Apache Webserver 2.4, but doesn't matter here anyway.

**Database:** MariaDB 5.5, but doesn't matter here anyway.

**PHP version:** 7.1 (via Remi Safe repository), but doesn't matter here anyway.

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh installation.

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-11.0.1.tar.bz2

**Signing status:** N/A

**List of activated apps:** N/A

**The content of config/config.php:** N/A

**Are you using external storage, if yes which one:** No external storage.

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**Comment by nickvergessen** [comment] 2017-02-21 19:46
Duplicate of #3312 fixed with #3407

**Closed by nickvergessen** 2017-02-21 19:46 UTC
