### ISSUE TITLE
New share icon in breadcrumb nav

### ISSUE THREAD

**Issue by te-online** [nextcloud/server#3564] opened 2017-02-21 15:25 UTC
The new share icon in the breadcrumb navigation was probably meant to speed up everyones workflow. As a user I have to say that I find it **very** confusing.

![bildschirmfoto 2017-02-21 um 16 12 17](https://cloud.githubusercontent.com/assets/4127167/23170812/e5056920-f850-11e6-9e4f-79de8f713c86.png)
*not shared folder*

![bildschirmfoto 2017-02-21 um 16 12 35](https://cloud.githubusercontent.com/assets/4127167/23170814/e662d6c2-f850-11e6-9fac-ce1d918bfa0d.png)
*shared folder*

My points of criticism being:
- The **difference** between the shared/not shared state is **not big enough**. The not-shared state looks like the shared state if no comparison is available. I panicked seeing this the first time, thinking the folder was shared.
- Why is the icon **only shown for the current folder**? This fact could support the confusion, because not every folder in the hierarchy has the icon, which could suggest that this particular folder is shared – while it's not (this scenario is not visible in the screenshots).
- When I click on the icon I get to the details panel of the folder I'm currently in. This icon is the only option to get there **from within** the folder. But there are other tabs in the panel (comment, activities). How should a user reach them from inside the folder? It seems inconsistent to provide an icon for one action, but not for all of them.

My suggestion:
Well, I don't have one at the moment. Personally, I see this as a big cause of confusion within the interface, because of the three inconsistencies mentioned. I'm interested, if anyone agrees to that – or if maybe someone might be able to come up with a solution (that is not removing the icon again).

**Comment by MorrisJobke** [comment] 2017-08-15 20:35
cc @nextcloud/designers

**Comment by jancborchardt** [comment] 2017-08-15 22:43
> The difference between the shared/not shared state is not big enough. The not-shared state looks like the shared state if no comparison is available. I panicked seeing this the first time, thinking the folder was shared.
Agree.
- We’re experimenting with adding avatars into the files list for shared elements: https://github.com/nextcloud/server/pull/6094 – we should add them to the top there too in the future.
- Another thing we could do is for non-shared folders, instead of the share icon, show the 3-dot icon. The 3-dot icon would also open the sidebar, but the icon would be less confusing. Might be a very good quick fix.

> Why is the icon only shown for the current folder? This fact could support the confusion, because not every folder in the hierarchy has the icon, which could suggest that this particular folder is shared – while it's not (this scenario is not visible in the screenshots).

Simply out of space reasons. But the spec was always that the breadcrumbs also show if a parent folder is indeed shared, as an indicator.

> When I click on the icon I get to the details panel of the folder I'm currently in. This icon is the only option to get there from within the folder. But there are other tabs in the panel (comment, activities). How should a user reach them from inside the folder? It seems inconsistent to provide an icon for one action, but not for all of them.

Ok, so we could change it to a 3-dot menu. But honestly that would just overcomplicate it, and sharing is the most important action as it is also a state indicator.

The not-enough-distinction between if it’s shared or not seems to be the biggest issue here, so let’s fix that and check if it’s better then.

**Comment by jancborchardt** [comment] 2017-08-15 22:56
Pull request to change the default icon to icon-more (3-dots) at https://github.com/nextcloud/server/pull/6143 :)

**Comment by skjnldsv** [comment] 2017-11-08 20:18
Actually I don't really mind the icon, I think the opacity is different enough to understand it.

>When I click on the icon I get to the details panel of the folder I'm currently in. This icon is the only option to get there from within the folder. But there are other tabs in the panel (comment, activities). How should a user reach them from inside the folder? It seems inconsistent to provide an icon for one action, but not for all of them.

But for this, I think this is a big issue.
We should indeed definitely add an icon or a way to open the right sidebar.
@nextcloud/designers

**Comment by jancborchardt** [comment] 2017-11-10 16:22
I am really hesitant to add a different icon here.

- The icon-more doesn’t work cause we use that so often already, it’s at a danger of overuse.
- The icon-info we could do, but we also want to use the share-indicator for other folders in the breadcrumb dropdown in the future
- Icon-activity we don’t really use anywhere there and it would duplicate the app icon

Unless the issue is more pressing or we come up with a really good solution, I would say we close this?

Also, the change to possibly show the sidebar by defaut on big screens will make this less of an issue: https://github.com/nextcloud/server/issues/7138

**Closed** 2017-11-12 19:55 UTC
Labels: design, enhancement, feature: files, feature: sharing, papercut
