### ISSUE TITLE
Trying to access array offset on value of type bool at /files_versions/lib/Storage.php#654

### ISSUE THREAD

**Issue by pixel8383** [nextcloud/server#19450] opened 2020-02-13 08:33 UTC
While browsing the web interface, the error log is generating the issue above
`
Trying to access array offset on value of type bool at /usr/local/www/nextcloud/apps/files_versions/lib/Storage.php#654`

Sometimes instead of 654, the involved line is the 653.

### Steps to reproduce
1. Browse the web interface
2. Check the error log

### Server configuration

**Operating system:** FreeBSD 12.3

**Web server:** nginx

**Database:** MySQL 8.0.19

**PHP version:** PHP 7.4.2

**Nextcloud version:** 18.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:**  https://download.nextcloud.com/server/releases/nextcloud-18.0.0.zip

**Are you using encryption:** no

**Comment by kesselb** [comment] 2020-02-13 09:14
Thanks for reporting :+1: 

Closing as duplicate of https://github.com/nextcloud/server/issues/19066

**Closed by kesselb** 2020-02-13 09:14 UTC
Labels: 0. Needs triage, bug
