### ISSUE TITLE
Lock Shared File via App

### ISSUE THREAD

**Issue by Arzerilla** [nextcloud/server#3730] opened 2017-03-06 15:33 UTC
### Steps to reproduce
1. Create a File and share it with a friend (in example a .doc file)
2. let friend opens up the local app synced file in editing
3. try to open up the file in the same moment (both with the local app sync or webdav)
4. you can open it and the situation is "last save wins"

### Expected behaviour
You should be warned that the file is locked in editing by another user
This works via WebDav share.

### Actual behaviour
You can open it and the situation is "last save wins"

### Server configuration
**Operating system**:
Client: Windows 7/8/10
Server: Ubuntu 16.04
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
10
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Nextcloud 10 Zip
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**Comment by nickvergessen** [comment] 2017-03-13 15:44
Duplicate of https://github.com/nextcloud/server/issues/1308

**Closed by nickvergessen** 2017-03-13 15:44 UTC

**Comment by klm46** [comment] 2017-04-10 08:44
this is NOT a duplicate! 1308 is about webdav, this about natice client! please reopen

**Comment by nickvergessen** [comment] 2017-04-10 08:47
Well also the native clients use webdav. So yes it's all about the availability of locking on webdav

**Comment by klm46** [comment] 2017-04-10 09:21
allright - so nothing to say ;)
