### ISSUE TITLE
{PHP} fopen(): Filename cannot be empty error when click on settings/admin/logging

### ISSUE THREAD

**Issue by tuxmaster** [nextcloud/server#8176] opened 2018-02-05 07:12 UTC
### Steps to reproduce
1. log in 
2. click on admin
3.select logging

### Expected behaviour
Open the nextcloud log

### Actual behaviour
Error in the php log

### Server configuration

**Operating system**: CentOS 7.4

**Web server:** Apache 

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:**  12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade from oc 

**Where did you install Nextcloud from:** via update script

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.3
  - comments: 1.2.0
  - dav: 1.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.3
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_texteditor
  - files_trashbin
  - files_versions
  - firstrunwizard
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "XXX",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXX"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "dbtype": "mysql",
        "version": "12.0.5.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 83886080,
        "allowZipDownload": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "log_type": "syslog",
        "loglevel": "1",
        "logfile": "",
        "logtimezone": "Europe\/Berlin",
        "log_authfailip": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "XXXX",
        "mail_from_address": "KeineAntwort",
        "forceSSLforSubdomains": true,
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/XXXX"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "signed": "true",
            "types": "filesystem"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
"backgroundjob": {
            "lastjob": "48"
        },
        "bruteforcesettings": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.0.3",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "0.7.1",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "no",
            "installed_version": "0.3",
            "types": ""
        },
"core": {
            "backgroundjobs_mode": "cron",
            "enable_external_storage": "yes",
            "global_cache_gc_lastrun": "1436274902",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1399568975.9594",
            "lastcron": "1517814022",
            "lastupdateResult": "[]",
            "lastupdatedat": "1517813343",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "9cef0f186a4dba69ed8a46e5c810fb1b",
            "shareapi_allow_links": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_default_expire_date": "no",
            "shareapi_enforce_links_password": "no",
            "shareapi_exclude_groups": "no",
            "shareapi_only_share_with_group_members": "yes",
            "shareapi_only_share_with_membership_groups": "yes",
            "shareapi_share_policy": "groups_only",
            "umgmt_show_backend": "false",
            "umgmt_show_email": "true",
            "umgmt_show_storage_location": "false",
            "updater.secret.created": "1517050985",
            "vendor": "nextcloud"
        },
"dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.8.1",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "52",
            "backgroundwatcher_previous_folder": "18",
            "cronjob_scan_files": "500",
            "default_quota": "100 MB",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "no",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,dropbox,googledrive,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "signed": "true",
            "types": ""
        },
"files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.4.0",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "0.3",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "no",
            "installed_version": "0.5",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "no",
            "installed_version": "1.0.3",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "signed": "true",
            "types": ""
        },
        "logreader": {
            "enabled": "[\"admin\"]",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
"market": {
            "enabled": "no",
            "installed_version": "0.2.3",
            "market": "0.2.3",
            "signed": "true",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "[\"admin\"]",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.2.2",
            "types": ""
        },
"provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.2",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "socialsharing_email": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "survey_client": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.0.0",
            "last_report": "{\"id\":\"oced6c1c3c6e\",\"items\":[[\"server\",\"version\",\"12.0.5.3\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"yes\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.1.13\"],[\"php\",\"memory_limit\",134217728],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.2.12\"],[\"database\",\"size\",2588672],[\"apps\",\"activity\",\"2.5.2\"],[\"apps\",\"admin_dependencies_chk\",\"disabled\"],[\"apps\",\"bruteforcesettings\",\"1.0.3\"],[\"apps\",\"calendar\",\"disabled\"],[\"apps\",\"comments\",\"1.2.0\"],[\"apps\",\"configreport\",\"0.1.1\"],[\"apps\",\"contacts\",\"disabled\"],[\"apps\",\"dav\",\"1.3.1\"],[\"apps\",\"documents\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.2.0\"],[\"apps\",\"federation\",\"1.2.0\"],[\"apps\",\"files\",\"1.7.2\"],[\"apps\",\"files_external\",\"1.3.0\"],[\"apps\",\"files_locking\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.1.1\"],[\"apps\",\"files_sharing\",\"1.4.0\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"disabled\"],[\"apps\",\"files_versions\",\"disabled\"],[\"apps\",\"files_videoplayer\",\"1.1.0\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"disabled\"],[\"apps\",\"gallery\",\"17.0.0\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"market\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.1\"],[\"apps\",\"notifications\",\"2.0.0\"],[\"apps\",\"oauth2\",\"1.0.5\"],[\"apps\",\"password_policy\",\"1.2.2\"],[\"apps\",\"provisioning_api\",\"1.2.0\"],[\"apps\",\"search_lucene\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.2.0\"],[\"apps\",\"sharebymail\",\"1.2.0\"],[\"apps\",\"survey_client\",\"1.0.0\"],[\"apps\",\"systemtags\",\"1.2.0\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"theming\",\"1.3.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.1.1\"],[\"apps\",\"updatenotification\",\"1.2.0\"],[\"apps\",\"updater\",\"disabled\"],[\"apps\",\"workflowengine\",\"1.2.0\"],[\"stats\",\"num_files\",3004],[\"stats\",\"num_users\",17],[\"stats\",\"num_storages\",37],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",17],[\"stats\",\"num_storages_other\",19],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",22],[\"files_sharing\",\"num_shares_user\",10],[\"files_sharing\",\"num_shares_groups\",6],[\"files_sharing\",\"num_shares_link\",6],[\"files_sharing\",\"num_shares_link_no_password\",6],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_1\",\"8\"],[\"files_sharing\",\"permissions_1_1\",\"5\"],[\"files_sharing\",\"permissions_3_1\",\"6\"],[\"files_sharing\",\"permissions_0_3\",\"1\"],[\"files_sharing\",\"permissions_1_5\",\"1\"],[\"files_sharing\",\"permissions_0_15\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1517051715",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
"templateeditor": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "core": "10.0.2",
            "enabled": "[\"admin\"]",
            "installed_version": "1.2.0",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        }
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**  Firefox

**Operating system:** CentOS 7.4

#### Web server error log
<details>
<summary>Web server error log</summary>
{PHP} fopen(): Filename cannot be empty at /var/www/html/owncloud/apps/logreader/lib/Controller/LogController.php#56
Feb 05 07:57:22 system.terrortux.de ownCloud[14622]: {index} Exception: {"Exception":"Exception","Message":"Error while opening ","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/logreader\/lib\/Controller\/LogController.php(73): OCA\\LogReader\\Controller\\LogController->getLogIterator()\n#1 [internal function]: OCA\\LogReader\\Controller\\LogController->get(50, 0)\n#2 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#3 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#4 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/App.php(114): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\LogReader\\Controller\\LogController), 'get')\n#5 \/var\/www\/html\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\LogReader\\\\C...', 'get', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#7 \/var\/www\/html\/owncloud\/lib\/private\/Route\/Router.php(299): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#8 \/var\/www\/html\/owncloud\/lib\/base.php(1004): OC\\Route\\Router->match('\/apps\/logreader...')\n#9 \/var\/www\/html\/owncloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/var\/www\/html\/owncloud\/apps\/logreader\/lib\/Controller\/LogController.php","Line":60}
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
'log_type' => 'syslog',
</details>

**Comment by MorrisJobke** [comment] 2018-02-05 11:10
Duplicate of #8140

**Comment by MorrisJobke** [comment] 2018-02-05 11:10
If you use syslog the build in log reader will not work, because there is no easy way to extract info from the sys log. We will enhance the view anyways to reflect this limitation properly.

**Closed by MorrisJobke** 2018-02-05 11:10 UTC
