### ISSUE TITLE
[Bug]: NC28 Cannot copy file to original folder (duplicate a file on the web interface no longer possible)

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/server#42838] opened 2024-01-16 10:49 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It was possible in nextcloud 27 to copy a file to its own folder, which would generate a duplicate on the server. As of nextcloud 28, there is no "copy or move" button shown for the origin folder.

### Steps to reproduce

1. Select a file
2. click on move/copy
3. try to copy it to the origin folder to create a duplicate

### Expected behavior

Either there should be a duplicate button/option or it should be possible to copy to the origin folder to achieve the same functionality.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment] 2024-01-17 15:27
Duplicate of https://github.com/nextcloud/server/issues/41768

**Closed by susnux** 2024-01-17 15:27 UTC
Labels: bug, 0. Needs triage, regression, 28-feedback
