### ISSUE TITLE
Moving files to external storage renders them unusable

### ISSUE THREAD

**Issue by neelusR** [nextcloud/server#14435] opened 2019-02-28 12:35 UTC
### Steps to reproduce
1. Move files from nextcloud storage to external storage, through web interface
2. Try to open the files by accessing the files directly on external storage
3. Copy the files back to nextcloud storage from external storage, through web interface (i copied to the same place I moved them away before)
4. try to download the files nextcloud via web interface --> error "secure connection failed"
5. try to download the files on external storage via nextcloud web interface --> error "File not found"
6. try to copy from external storage to another location --> could not copy

### Expected behaviour
I could have expected that the file cannot be accessed directly on the remote storage because of encryption
I would expect that I can access the files 

### Actual behaviour
The files are definitely present on the external storage. When I open them I see that they are encrypted. However I would not have expected they become 'lost'. I see them but I can not download them. Also after copying them back, the copies also become unusable.

When I try to access the files through DAV share on windows, I get a "cannot be found error" and the files are 8kb.
When I try to access the files on the external storage through nextcloud DAV share, I see the files are 116kb, which is ok, but I still get an error "cannot open".

### Server configuration
hosted nextcloud: disroot.org
nextcloud: 13 ( i think)

**Are you using external storage, if yes which one:** yes, Mailfence webdav

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox

**Operating system:** Windows

**Comment by skjnldsv** [comment] 2020-11-07 23:46
Most likely an unreliable ext storage.
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-11-07 23:46 UTC
Labels: 0. Needs triage, bug
