### ISSUE TITLE
[Bug]: Document URL does not change when the documents are closed/opened

### ISSUE THREAD

**Issue by rajmondburgaj** [nextcloud/server#46835] opened 2024-07-29 06:51 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

1. When opening a document for the first time in the URL, the URL of that document adjusts accordingly, so, we have the name of the document in the URL and also the `openfile` query parameter set to true. But if the document is closed, the URL never adjusts anymore, hence causing inconsistent behavior while navigation. For example, when I close the document and refresh the page, instead of showing the full list of the documents, it will simply open that which is not correct.
2. In addition, when opening other documents and refreshing the page instead of opening the same document, it will open the first one from the list because of the wrong URL, which never changes.

### Steps to reproduce

1. Open a document
2. Close it
3. Refresh the page and instead of showing the main list, it opens the previous document
4. Now, close it again, and open document 2
5. Refresh the page
6. instead of showing document 2, it will open document 1 due to the wrong URL

### Expected behavior

The expected behavior is: - The URL should always reflect the selected/opened document, and if none is opened it should point to the main list of documents instead. This would also prevent people from sharing the wrong URL with others.

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
The issue is applicable to all versions since version 27 if I remember correctly, so, no need to paste this information here.
```

### Additional info

[Screencast from 2024-07-29 08-39-09.webm](https://github.com/user-attachments/assets/3986214e-e5a7-4f1a-9eb7-58e8092ecaa0)

**Comment by susnux** [comment] 2024-07-29 10:34
Duplicate of https://github.com/nextcloud/server/issues/45731

**Closed by susnux** 2024-07-29 10:34 UTC
Labels: bug, 0. Needs triage, 29-feedback
