### ISSUE TITLE
Feature Request: Move AppStore/Fetcher/Fetcher.php timeout to config.php

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/server#40947] opened 2023-10-17 11:02 UTC
This is related to: https://github.com/nextcloud/server/pull/16972

In `lib/private/App/AppStore/Fetcher/Fetcher.php` there is a timeout setting. 

This should be a configuration available in config.php, to make it a) discoverable and b) tuneable. and c) not require an edit to site source.

On a fresh install in Tasmania, I found no app store. And no clue why. I had to drill into logs and then google to find the issue above. I upped the timeout and I have an app store. It is mentioned in the issue that: "If a job need specific longer time it should set that." in which the author of the PR is tacitly agreeing (admitting) that this may need site specific tuning. Further to which numerous punters on that PR report as do I that larger timeouts are needed in their context.

I will add to this request that if the timeout is exceeded a sensible message appears on the App store to convey that and a link to suggest how to tune it.

**Comment by joshtrichards** [comment] 2023-10-17 14:37
Hi @bernd-wechner - Thanks for your report. This is a duplicate of #40082 so let's consolidate tracking of this enhancement idea there. Feel free to subscribe to that issue and/or upvote it for prioritization and/or add your comments to the discussion.

**Closed by joshtrichards** 2023-10-17 14:37 UTC
Labels: enhancement, 0. Needs triage

**Comment by bernd-wechner** [comment] 2023-10-17 19:41
Thanks for that. I did some thorough searches first and failed to find that one alas. My apologies.

**Comment by joshtrichards** [comment] 2023-10-17 20:42
I changed the title of that one after I saw your report come in. So no apology necessary.. :-)
