### ISSUE TITLE
List entry is behind header

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#18719] opened 2020-01-07 15:25 UTC
![image](https://user-images.githubusercontent.com/5836855/71898033-8f57cb00-3158-11ea-82ac-da9cfdb4d6cf.png)

Behind "Name" is 123.txt, which is barely readable.

_Originally posted by @tobiasKaminsky in https://github.com/nextcloud/server/pull/18707#issuecomment-571581983_

**Comment by kesselb** [comment] 2020-01-07 15:36
Seems similar to https://github.com/nextcloud/server/issues/18414. It's probably helpful to add in which view you see this.

**Comment by tobiasKaminsky** [comment] 2020-01-08 08:13
It is in "pending share" view of https://github.com/nextcloud/server/pull/18707
Julius said in this PR that it is unrelated to this PR, so I opened up a new issue.

**Comment by juliushaertl** [comment] 2020-01-13 22:32
Closing as I cannot reproduce it on latest master anymore.

**Closed** 2020-01-13 22:32 UTC
Labels: 18-feedback, bug, design
