### ISSUE TITLE
Feature Request - File locking functionality - Web UI and Desktop Client.

### ISSUE THREAD

**Issue by JarbyDev** [nextcloud/server#5006] opened 2017-05-21 13:30 UTC
Will be Awesome if Nextcloud have file locking functionality like SeaFile.

Seafile supports file locking to prevent concurrent editing of files and generating of conflicts files. Users can lock files in web UI or desktop clients. Office files are automatically locked when they’re opened.

More about SeaFile File Locking is [below.]
(https://www.seafile.com/en/help/file_lock/)

**Comment by MariusBluem** [comment] 2017-05-21 13:47
Something like https://apps.nextcloud.com/apps/workin2gether? @patt92

**Comment by JarbyDev** [comment] 2017-05-21 14:12
Workin2gether - Only work in the Web UI, and not with the Desktop Client. See more about seafile file locking [https://www.seafile.com/en/help/file_lock/](url)

**Comment by Patt92** [comment] 2017-05-22 11:06
I was already planning to implement it. If someone knows, how to enable an app in the desktop client / remote endpoint, I'd be glad to add it.

**Comment by MorrisJobke** [comment] 2017-07-18 22:17
Duplicate of #1308

**Closed by MorrisJobke** 2017-07-18 22:17 UTC
