### ISSUE TITLE
Avatar menu broken in sidebar in Files

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#24299] opened 2020-11-23 09:05 UTC
So there is this ability to click an avatar and you get a nice popup so you can mail or chat with the person. In the files app, this is fairly broken - at least in the sidebar where I just tried it. So in sharing you get this:
![Screenshot_20201123_092628](https://user-images.githubusercontent.com/551757/99941926-2298ef80-2d6f-11eb-97e6-5069932f2212.png)

in the comments, it works great for the  mentioned name:
![Screenshot_20201123_092802](https://user-images.githubusercontent.com/551757/99941936-2593e000-2d6f-11eb-8f6d-460a2d1e4ec9.png)

But here the popup shows up about 20px too high so you get it overlapping the person's icon (and almost seeming like it belongs to my avatar):
![Screenshot_20201123_092817](https://user-images.githubusercontent.com/551757/99941949-27f63a00-2d6f-11eb-966c-67cca8d46b5d.png)

Might be vaguely related to https://github.com/nextcloud/spreed/issues/4147 ?

**Comment by wiswedel** [comment] 2020-11-24 07:51
Duplicate of #18634

**Closed by wiswedel** 2020-11-24 07:51 UTC
