### ISSUE TITLE
after updating from 13.0.1 to 13.0.2 I get: invalidsignatureexception:  theming: "  Signature data not found." 

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#9575] opened 2018-05-24 05:27 UTC
nextcloud 13.0.1 upgrade via the webclient to 13.0.2.
OS: Ubuntu 16.04 latest patches as of today.
Before at 13.0.1 I did had zero errors on the webconsole.

After 13.0.2 upgrade I get:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- theming
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [theming] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

How could I fix this as I can't find other references from others what I need to do to fix the integrity on the 'theming' app?
Or is there something else not right?
Thanks!

**Comment by xvybihal** [comment] 2018-05-24 07:33
I confirm, signature.json is missing after upgrade theming 1.4.1 to 1.4.2 via webapp. This happened on two separate Nextcloud instances.

**Comment by MorrisJobke** [comment] 2018-05-24 07:56
Duplicate of #9568

**Closed by MorrisJobke** 2018-05-24 07:56 UTC
