### ISSUE TITLE
Folder didn't Sync cause of name -> without Error

### ISSUE THREAD

**Issue by Rowtag** [nextcloud/server#11609] opened 2018-10-04 07:30 UTC
**Steps to reproduce**
Create a Folder names like: Alpha Betalab Co. Est.
This folder is not visible for the NextCloud Client and it doesn't give any Sync error.

**Actual behaviour**
When the Folder Name is Named like above the Client doesn't see this folder and it will not Sync / No Sync error. When i remove the dots in this Name it will work with the Sync.

**Server configuration**
#Docker Image:
14.0.1

**PHP 7.2**
Apache Webserver
Maria DB

**Nextcloud version: (see Nextcloud admin page)**
NextCloud 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Dockerized, so fresh Image.

**Where did you install Nextcloud from:**
Docker Repository

**Comment by skjnldsv** [comment] 2020-04-10 07:13
As I cannot reproduce the original issue anymore on latest docker images, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 07:13 UTC
Labels: 0. Needs triage, bug

**Comment by BastianBalthasarBux** [comment] 2023-11-20 07:37
I can reproduce with folder names containing a valid .com Domain name.
like: nextcloud.com
Results in a 404 not found error and not syncing that folder.
