### ISSUE TITLE
LDAP Error 

### ISSUE THREAD

**Issue by QuadGem** [nextcloud/server#27262] opened 2021-05-29 02:19 UTC
tail -f www-error.log
#0 {main}
  thrown in /var/www/html/nextcloud-21.0.2/apps/user_ldap/ajax/getConfiguration.php on line 30
[29-May-2021 01:45:50 UTC] PHP Fatal error:  Uncaught Error: Class 'OC_JSON' not found in /var/www/html/nextcloud-21.0.2/apps/user_ldap/ajax/getConfiguration.php:30
Stack trace:
#0 {main}
  thrown in /var/www/html/nextcloud-21.0.2/apps/user_ldap/ajax/getConfiguration.php on line 30
[29-May-2021 02:00:35 UTC] PHP Fatal error:  Uncaught Error: Class 'OC_JSON' not found in /var/www/html/nextcloud-21.0.2/apps/user_ldap/ajax/getConfiguration.php:3

**Comment by szaimen** [comment] 2021-05-29 09:02
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

**Comment by acsfer** [comment] 2021-05-29 11:28
Duplicate of https://github.com/nextcloud/server/issues/24022 ?

**Comment by szaimen** [comment] 2021-05-29 11:35
Looks like it 👍
@QuadGem please see https://github.com/nextcloud/server/issues/24022#issuecomment-724576207 for a solution. Thanks!

**Closed by szaimen** 2021-05-29 11:35 UTC
Labels: 0. Needs triage, bug, needs info
