### ISSUE TITLE
Allow copying into same folder, append " (2)"

### ISSUE THREAD

**Issue by dairaine** [nextcloud/server#9931] opened 2018-06-20 08:17 UTC
I often need to make a backup before file sharing in modification mode. A possibility to copy or move files is implemented in Nextcloud, but it seems not possible to duplicate a file in the same folder because a renaming is not allowed. It would be nice to have such a mechanism allowing a duplication in one click.

**Comment by MorrisJobke** [comment] 2018-06-20 10:01
cc @nextcloud/designers Does this make sense from an UX point of view? I would just add it to the context menu where we already have the copy and move operations.

**Comment by jancborchardt** [comment] 2018-06-21 08:01
The problem here is that

>  it seems not possible to duplicate a file in the same folder

Because in the case of copying it in the same folder, you get this technical notification:

> Could not copy "filename.txt", target exists


What should happen instead is that the copying simply works, and appends a " (2)" to the filename. So from "filename.txt" to "filename (2).txt". (Or a " (3)" if a 2 already exists etc – just like we do for files drop.)

**Comment by lightweight** [comment] 2018-07-03 21:28
Or use what most filemanagers do: "copy of filename" as the default filename, and then it can be renamed... I agree that the current behaviour (not being able to copy a file into the same directory) is a significant problem for me (e.g. if I create a template/example file that I want to replicate as a specifically named file and alter the filename, I have to copy it first to another folder/directory first, and then back, which is ponderous and seemingly unnecessary given the fairly standard behaviour of other file managers).

**Comment by jancborchardt** [comment] 2018-07-03 23:16
@lightweight ok, "Copy of filename.txt" seems good too! :) What Gnome does:
- filename (copy).txt
- filename (another copy).txt
- filename (3rd copy).txt
- filename (4th copy).txt
- etc

This is more obvious than just appending the number, which could also be a conflict or having uploaded the original file again.

**Comment by sunjam** [comment] 2018-07-29 19:32
I just encountered this issue when attempting to make a duplicate of a txt file in the Notes directory via the copy command.  It is not currently possible, but I'd love to be able to duplicate the text file + re-name it to .md at the same time while using the copy menu.  Something along the lines of:

> "Markdown Examples.txt" already exists; Do you want to Duplicate or Rename the copy?


instead of current

> Could not copy "Markdown Examples.txt"; target exists.

**Comment by greenido** [comment] 2018-08-23 17:26
I sent a PR with a fix: https://github.com/nextcloud/server/pull/10825

**Closed** 2018-11-22 16:37 UTC
Labels: Hacktoberfest, enhancement, feature: files, good first issue

**Comment by zeigerpuppy** [comment] 2020-01-06 02:22
This remains an issue when copying a whole folder, the error `target exists` prevents duplicating a folder

**Comment by jancborchardt** [comment] 2020-01-08 13:57
@zeigerpuppy could you open a separate issue for that? :) It should indeed work the same as for files.

**Comment by zeigerpuppy** [comment] 2020-01-12 03:40
sure @jancborchardt, I have created issue #18846
