### ISSUE TITLE
Updater: NC 10.0 (Stable and Beta) wants to upgrade to OC 9.1.1 instead of NC 10.0.1

### ISSUE THREAD

**Issue by Liantefaron** [nextcloud/server#1976] opened 2016-11-02 09:57 UTC
### Steps to reproduce
1. Open Administration > Server Settings tab > Version in NC 10.0

### Expected behaviour
An update to the relevant NC path (Stable or Beta) should be offered.

### Actual behaviour
Updater offers update to OwnCloud 9.1.1

![](https://help.nextcloud.com/uploads/default/original/2X/1/115dd3f6466f27b708eb8f1b53d913cde570e2ab.png)

Further Evidence:
https://help.nextcloud.com/t/wron-update-offered/4603 (for Stable)
https://help.nextcloud.com/t/nextcloud-will-install-owncloud-update/4616 (for Beta)

### Server configuration
**Operating system**: Most probably Linux
**Web server:** 1&1 shared server
**Database:** MySQL
**PHP version:** PHP 7
**Nextcloud version:** NC 10.0 Stable
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh
**Where did you install Nextcloud from:** Manual virgin install w/ new subdomain (instead of updating ye olde OC 8.2)

Since this is a problem that resides on the update server, not in my NC, I won't paste all the crunchy bits of my NC instance. Solution should be a simple correction of the update sources retrieved by  Updater Apps, right?

**Comment by LukasReschke** [comment] 2016-11-02 10:00
Dupe of https://github.com/nextcloud/server/issues/1931. Manually update to 10.0.1 for now.

**Comment by Liantefaron** [comment] 2016-11-02 10:01
Oh damn - "reading educates", as we Germans say. NC 10.0.1 will come with a new updater. Sorry for bothering you guys.

**Closed by LukasReschke** 2016-11-02 10:00 UTC
