### ISSUE TITLE
NC 20.0.1 Could not find resource core/js/files/client.js to load

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#23947] opened 2020-11-06 20:17 UTC
Nextcloud 20.0.1
PHP 7.4
MariaDB 10.3

<details>
<summary>Web server error logs</summary>

```
{"reqId":"jZR4nJhVpQF83d6xbTpK","level":3,"time":"2020-11-06T20:12:44+00:00","remoteAddr":"6.8.3.3","user":"user","app":"jsresourceloader","method":"GET","url":"/settings/user/workflow","message":"Could not find resource core/js/files/client.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","version":"20.0.1.1","id":"5fa5aeb50de60"}

{"reqId":"jZR4nJhVpQF83d6xbTpK","level":3,"time":"2020-11-06T20:12:44+00:00","remoteAddr":"6.8.3.3","user":"user","app":"jsresourceloader","method":"GET","url":"/settings/user/workflow","message":"Could not find resource core/js/files/fileinfo.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36","version":"20.0.1.1","id":"5fa5aeb50de7c"}

```

**Comment by kesselb** [comment] 2020-11-06 20:48
Duplicate of https://github.com/nextcloud/server/issues/23542

**Closed by kesselb** 2020-11-06 20:48 UTC
Labels: 0. Needs triage, bug
