### ISSUE TITLE
[Bug]: Missing hint of default expiration date on link shares

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/server#44220] opened 2024-03-15 13:10 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When in the settings a value for "Set default expiry date" is set and "Enforce expiry date" unchecked, there is no hint at creating a link share that an expiration date will be set.
The user thinks that the link share will be valid forever but when clicking on "Customize link" he sees that a expiration date was set automatically.
![grafik](https://github.com/nextcloud/server/assets/142410285/30c38de2-f9c4-4e3f-afe8-a5117d4e67a7)

### Steps to reproduce

1. Configure the Sharing settings like this
    - [x] Allow users to share via link and emails
    - [x] Allow public uploads
    - [x] Always ask for a password
    - [x] Enforce password protection
    - [x] Set default expiry date -> Expire after 30 day(s)
    - [ ] Enforce expiry date
2. Create a link share.
3. Click on "Customize link" and see that there was set an expiration date.

### Expected behavior

It should be like when the option "Enforce expiry date" is enabled, that the user sees in the pop-up when creating the link share that an expiration date is set.
He should be able to change the date or completely uncheck the option.
![grafik](https://github.com/nextcloud/server/assets/142410285/7d5c865e-4047-420f-8542-11049adeb2e6)

Or at least a notice should be displayed that an expiry date is set and that it can then be adjusted afterwards.

### Nextcloud Server version

27.1.7 28.0.3

**Comment by ElSi-DVT** [comment] 2024-04-29 14:38
Still no hint in 27.1.9

**Comment by ElSi-DVT** [comment] 2024-07-18 07:26
Still no hint in 28.0.7

**Comment by joshtrichards** [comment] 2024-11-06 19:10
Duplicate of #48860 (WIP)

**Closed by joshtrichards** 2024-11-06 19:10 UTC
Labels: bug, 1. to develop, feature: sharing, 28-feedback

**Comment by joshtrichards** [comment] 2024-11-06 19:12
FYI: Your Issue was the earlier one, but I kept the other one since @nfebe is already working on it. :)
