### ISSUE TITLE
Unable to delete a directory in the Files app

### ISSUE THREAD

**Issue by Wenzel** [nextcloud/server#3811] opened 2017-03-12 20:33 UTC
### Steps to reproduce
1. create a directory named `test` in the `Files` app, where you want
2. remove that `directory`

### Expected behaviour
The directory
 should have been removed

### Actual behaviour
I have an error message from `NextCloud` telling me that it is impossible to remove the directory,
which has been created 30 seconds ago.

![error](https://cloud.githubusercontent.com/assets/964610/23835672/453709e8-0774-11e7-9925-9a9b49663ccf.png)

Furthermore, the error message is wrong, because `test` is a directory here.
Creating and removing a file works.

### Server configuration
**Operating system:** `Debian Jessie` 

**Web server:** `nginx 1.10.3`

**Database:** `MySQL`

**PHP version:** `PHP 5.6.30`

**Nextcloud version:** `11.0.1`

**Updated from an older Nextcloud/ownCloud or fresh install:** `Updated from latest Owncloud`

**Where did you install Nextcloud from:** `tarball`

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - audioplayer: 1.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ownpad: 0.5.7
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - notes
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocz4cd3uoj2u",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/data\/owncloud",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "maintenance": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "13064"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168708",
            "signed": "true",
            "types": ""
        },
        "core": {
            "incoming_server2server_share_enabled": "yes",
            "installedat": "1436738166.1039",
            "lastcron": "1489350174",
            "lastupdateResult": "{\"version\":\"11.0.2.7\",\"versionstring\":\"Nextcloud 11.0.2\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-11.0.2.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/11\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"autoupdater\":\"1\"}",
            "lastupdatedat": "1489350090",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "outgoing_server2server_share_enabled": "yes",
            "previewsCleanedUp": "1",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_links": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_enabled": "yes",
            "shareapi_enforce_links_password": "no",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_markdown": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "1.1.1",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.0",
            "types": "logging"
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "168512",
            "types": ""
        },
        "ownpad": {
            "enabled": "yes",
            "installed_version": "0.5.7",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "1.1.17",
            "ocsid": "174727",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "apps": "no",
            "database": "no",
            "enabled": "yes",
            "encryption": "no",
            "files_sharing": "no",
            "installed_version": "0.1.5",
            "php": "no",
            "server": "no",
            "stats": "no",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.4",
            "ocsid": "164356",
            "signed": "true",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** `Chromium`

**Operating system:** `Fedora 24`

#### Web server error log
<details>
<summary>Web server error log</summary>

```
sensitive info
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"EPgJ7UgRbwhSI4Z1vP8n","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-07-12T21:55:23+00:00"}
{"reqId":"EPgJ7UgRbwhSI4Z1vP8n","remoteAddr":"127.0.0.1","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-07-12T21:55:23+00:00"}
{"reqId":"bSHbClB40RKh9\/2JzeWO","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#684","level":3,"time":"2015-07-12T21:56:04+00:00"}
```
</details>

Thank you for your support !

**Comment by nickvergessen** [comment] 2017-03-13 08:38
Anything useful in your servers error log related to the deletion?
Also I wonder about the logs, they seem to be from before the migration from owncloud? At least the file `lib\/private\/appframework\/http\/request.php` does not exist in Nextcloud 11?

**Comment by Wenzel** [comment] 2017-03-13 08:49
Hi @nickvergessen !
Actually yes, there was something in my `Nginx` `error.log` that i missed yesterday :

~~~
2017/03/13 09:42:59 [error] 1290#1290: *2622 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 77 bytes) in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 104" while reading response header from upstream, client: 193.110.108.33, server: example.com, request: "DELETE /remote.php/webdav/test HTTP/2.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "example.com"
~~~

A memory exhaustion ?
That's weird, because my RAM is almost completely free (`400M` / `3946`).
Also i monitored my RAM during the attempt of removing a directory, and it allocates `500MB` until it fails. (probably because one `PHP-FPM` worker is denied to allocate more memory.

Thanks !

**Comment by nickvergessen** [comment] 2017-03-13 09:31
Yeah sounds like your memory limit is 512MB, check your php.ini.
I had a similar issue last week, and needed to increase it to 1GB to delete an empty folder.

Not sure why but that sounds really like something is wrong. @rullzer @icewind1991

**Comment by rullzer** [comment] 2017-03-13 09:52
I just tested here and it works (even with 256MB of ram for php).
But this is strange. If any of you find more detailed reproduction steps I could look into it.

**Comment by Wenzel** [comment] 2017-03-13 09:54
I'm able to debug on my server if that helps.
I don't want to allocate 1G of RAM just to remove an empty file...

**Comment by oparoz** [comment] 2017-03-13 13:13
It's a duplicate. A solution has already been given to @icewind1991 for review

**Comment by nickvergessen** [comment] 2017-03-13 14:59
Duplicate of https://github.com/nextcloud/server/issues/3340

**Closed by nickvergessen** 2017-03-13 14:59 UTC
Labels: needs info
