### ISSUE TITLE
Creating shared link with password forced creats multiple links

### ISSUE THREAD

**Issue by mur-sp** [nextcloud/server#23589] opened 2020-10-20 12:01 UTC
Hello,
we have a newly installed Nextcloud 20.0.0 on an Ubuntu 20.04 Server and we got problems with shareing links. 
* We are useing the force passwort option. 
* When we create a link, for a folder or a file, to share and enter the password we want to use, two different links will get created and both use the same password. 
* If the password was entered and instead of pressing enter, the arrow gets pressed three links will be created. All three are useing the same password. 

Looking forward for an answer. If some more details are needed pls tell me and I will give them to you.
Best Regards

**Comment by szaimen** [comment] 2021-06-17 14:35
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-17 14:35 UTC
Labels: 0. Needs triage, bug
