### ISSUE TITLE
Change redirect target for integrity scan

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/server#15252] opened 2019-04-26 15:12 UTC
**Is your feature request related to a problem? Please describe.**
When triggering an integrity rescan from the Overview page `/settings/admin/overview`, I am redirected to the Basic Settings `/settings/admin`, which do not display the result of the scan.

**Describe the solution you'd like**
I would suggest redirecting to `/settings/admin/overview` instead.

**Describe alternatives you've considered**
None.

**Comment by Gatak** [comment] 2019-04-26 18:19
I only noticed this in NC16. I think it is a regression.

**Comment by szaimen** [comment] 2021-05-20 12:21
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by szaimen** 2021-05-20 12:21 UTC
Labels: 0. Needs triage, enhancement
