### ISSUE TITLE
Two display problems

### ISSUE THREAD

**Issue by charwavid** [nextcloud/server#14190] opened 2019-02-14 05:57 UTC
![_20190214134742](https://user-images.githubusercontent.com/7514841/52765889-6b7f2880-3060-11e9-961d-1f9ed6eeacd8.png)

Two display problems, the first one is that the html tag of selectedActionsList displays an error, and the second language in the red box on the left is Simplified Chinese and does not display the number of files.
Tested both versions 15.0.2 and 15.0.4 have these problems.

**Comment by charwavid** [comment] 2019-02-14 06:11
Another problem is that the 15.0.2 version of the installation application can be displayed in the navigation without refresh page, the 15.0.4 version needs to be manually refreshed.

**Comment by skjnldsv** [comment] 2019-03-03 18:43
Hello, I cannot reproduce your issue.
Before we continue, please do the following steps:
1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server

Thanks :wink:

![capture d ecran_2019-03-03_19-43-06](https://user-images.githubusercontent.com/14975046/53699821-a6b58180-3dec-11e9-85fd-c132d9ddbaf1.png)

**Comment by charwavid** [comment] 2019-03-04 03:57
Hello, Foxmail open today, find your reply. In fact, it is not difficult to reproduce what I said, as long as the setting - > personal info - > language into simplified Chinese. I found is the browser to load the file out of the question, leading to ID selectedActionsList span, less class hidden property is displayed, so; but also the display you give, not the same. Comparison of the English, Chinese, Japanese, Han Wen, it is English display like you, other languages are my kind of display.
![bug](https://user-images.githubusercontent.com/7514841/53709720-a8c32300-3e74-11e9-85b6-0e94d54b16e6.png)

**Comment by skjnldsv** [comment] 2019-06-05 12:41
![Capture d’écran_2019-06-05_14-41-00](https://user-images.githubusercontent.com/14975046/58956978-f5820700-879f-11e9-8fad-e4f063474263.png)
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-05 12:41 UTC
Labels: 0. Needs triage, bug, design, needs info
