### ISSUE TITLE
[Bug]: Update to 28.0.0 RC4 failed

### ISSUE THREAD

**Issue by fethomm** [nextcloud/server#42168] opened 2023-12-12 08:44 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Das Datenbankschema wird aktualisiert

Exception: Database error when running migration 28000Date20230906104802 for app core Index name "afoa" for table "oc_social_follow" collides with the constraint on table "oc_social_3_follow".

### Steps to reproduce

1.Run the updater 
2.Back in the Web-Interface run the update
3. Run into this error

### Expected behavior

Nextcloud updated to 28.0.0 RC4

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.berlinuxlab.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.5.0",
        "overwrite.cli.url": "https:\/\/nextcloud.berlinuxlab.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "logtimezone": "Europe\/Berlin",
        "maintenance": false,
        "app_install_overwrite": [
            "joplin",
            "end_to_end_encryption",
            "social"
        ],
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "7, 7",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - bookmarks: 13.1.1
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - integration_gitlab: 1.0.18
  - integration_reddit: 2.0.2
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recognize: 5.0.3
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.3
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.18.0
  - apporder: 0.15.0 (installed 0.15.0)
  - cookbook: 0.10.2 (installed 0.10.2)
  - deck: 1.11.0 (installed 1.11.0)
  - encryption: 2.16.0
  - end_to_end_encryption: 1.13.1 (installed 1.13.1)
  - files_external: 1.20.0
  - files_markdown: 2.4.1 (installed 2.4.1)
  - maps: 1.2.0 (installed 1.2.0)
  - onlyoffice: 8.2.4 (installed 8.2.4)
  - qownnotesapi: 23.6.0 (installed 23.6.0)
  - side_menu: 3.10.3 (installed 3.10.3)
  - social: 0.6.1 (installed 0.6.1)
  - spreed: 17.1.2 (installed 17.1.2)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
Nextcloud wird auf Version 28.0.0 RC4 aktualisiert
Folgende Apps werden aktualisiert:
Activity (activity)
Brute-force settings (bruteforcesettings)
Circles (circles)
Cloud Federation API (cloud_federation_api)
Comments (comments)
Contacts Interaction (contactsinteraction)
Dashboard (dashboard)
```

### Nextcloud Logs

```shell
{"reqId":"u9KO9uDKGQZiZEFT2d61","level":2,"time":"2021-01-24T08:40:43+00:00","remoteAddr":"91.64.59.76","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":""}
{"reqId":"u9KO9uDKGQZiZEFT2d61","level":2,"time":"2021-01-24T08:40:43+00:00","remoteAddr":"91.64.59.76","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":""}
{"reqId":"EAdDBxx1YiPD2GR2ItoK","level":2,"time":"2021-01-24T08:43:12+00:00","remoteAddr":"91.64.59.76","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":""}
{"reqId":"EAdDBxx1YiPD2GR2ItoK","level":2,"time":"2021-01-24T08:43:12+00:00","remoteAddr":"91.64.59.76","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":""}
{"reqId":"E537zE1J6hgv8OvgfamX","level":2,"time":"2021-01-24T08:45:53+00:00","remoteAddr":"91.64.59.76","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":""}
{"reqId":"E537zE1J6hgv8OvgfamX","level":2,"time":"2021-01-24T08:45:53+00:00","remoteAddr":"91.64.59.76","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":""}
```

**Comment by solracsf** [comment] 2023-12-12 08:45
Duplicate of https://github.com/nextcloud/server/issues/41253

**Closed by solracsf** 2023-12-12 08:45 UTC
Labels: bug, 0. Needs triage
