### ISSUE TITLE
Weblogin flow: login button shortly wrong color

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7105] opened 2017-11-08 08:33 UTC
Given a themed weblogin page, you can see for a very short time a wrong color when pressing the login button.

![screenshot_20171108_092427](https://user-images.githubusercontent.com/5836855/32538848-c231daee-c467-11e7-87e6-8ac47ffbd134.png) ![screenshot_20171108_092825](https://user-images.githubusercontent.com/5836855/32538849-c2b23234-c467-11e7-8eab-a75139dae8e4.png)

**Comment by MorrisJobke** [comment] 2017-11-08 09:16
@skjnldsv @juliushaertl

**Comment by skjnldsv** [comment] 2017-11-08 09:20
@tobiasKaminsky Can't reproduce. What version are you using?

**Comment by tobiasKaminsky** [comment] 2017-11-08 10:29
@skjnldsv latest master with android emulator (Android 7)

**Comment by skjnldsv** [comment] 2017-11-08 10:37
This is strange. There is an issue with ios though.
![img_20171108_113710](https://user-images.githubusercontent.com/14975046/32544603-332a060c-c479-11e7-8dca-36be545e645a.jpg)

**Comment by juliushaertl** [comment] 2017-11-08 12:15
@tobiasKaminsky I cannot reproduce this with master and current playstore version. Can this be a caching issue in your android simulator?

**Comment by tobiasKaminsky** [comment] 2017-11-08 13:10
I tried it with a samsung s5 and there was also for a very short time a blue button (previously it was themed to white).
I do not know if this can be a caching issue...

**Comment by rullzer** [comment] 2017-11-09 09:58
Should be fixed with https://github.com/nextcloud/server/pull/7110 and https://github.com/nextcloud/server/pull/7111

**Closed by rullzer** 2017-11-09 09:58 UTC
Labels: design, feature: theming, papercut

**Comment by tobiasKaminsky** [comment] 2017-11-09 12:31
Indeed I now cannot see the wrong color anymore 👍
