### ISSUE TITLE
Add "Prohibit to download" or like features to user share (not public share)

### ISSUE THREAD

**Issue by s8321414** [nextcloud/server#33666] opened 2022-08-24 06:57 UTC
Please add "Prohibit to download" or like features to user share (or internal share link, but not public share link). 
It is good to some use cases. :smiley:

**Comment by csware** [comment] 2022-08-24 11:38
Does this make any sense? When I use the sync client I already have the files and when I use the web UI I can just copy the files to some other folder.

**Comment by joshtrichards** [comment] 2024-01-31 22:22
Duplicate of #16413 
Closed by #32482

**Closed by joshtrichards** 2024-01-31 22:22 UTC
Labels: enhancement, feature: sharing, 0. Needs triage
