### ISSUE TITLE
[Bug]: Setup Checks try to access subfolder twice

### ISSUE THREAD

**Issue by BMerz** [nextcloud/server#48414] opened 2024-09-26 20:17 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since version 29 some update checks fail. At first this seemed to be a configuration issue.
But when searching the nginx logfiles I discovered that when opening the admin overview page these checks try to access the subdir twice.
I know that the checks now run from the server itself and I have tested the access works directly from the server.
It seems that the url generator for these checks doesn't work correct.
Even after udpate to 30 the problem persists

cat /var/log/nginx/access.log|grep nextcloud/nextcloud

*.*.*.* - - [26/Sep/2024:21:46:09 +0200] "GET **/nextcloud/nextcloud/**/mnt/daten/nextcloud_data/data/.ncdata HTTP/1.1" 404 1745 "-" "Nextcloud Server Crawler"
*.*.*.* - - [26/Sep/2024:21:46:09 +0200] "HEAD /nextcloud/nextcloud/apps/settings/js/map-test.js.map HTTP/1.1" 404 0 "-" "Nextcloud Server Crawler"
*.*.*.* - - [26/Sep/2024:21:46:09 +0200] "HEAD /nextcloud/nextcloud/apps/settings/js/esm-test.mjs HTTP/1.1" 404 0 "-" "Nextcloud Server Crawler"
*.*.*.* - - [26/Sep/2024:21:46:09 +0200] "GET /nextcloud/nextcloud/heartbeat HTTP/1.1" 404 1745 "-" "Nextcloud Server Crawler"
*.*.*.* - - [26/Sep/2024:21:46:10 +0200] "HEAD /nextcloud/nextcloud/core/fonts/NotoSans-Regular-latin.woff2 HTTP/1.1" 404 0 "-" "Nextcloud Server Crawler"
*.*.*.* - - [26/Sep/2024:21:46:10 +0200] "HEAD /nextcloud/nextcloud/apps/spreed/js/tflite.wasm HTTP/1.1" 404 0 "-" "Nextcloud Server Crawler"

During normal operation of the server I can't find any entry with "/nextcloud/nextcloud/"

### Steps to reproduce

Working instance updated to 29, then the bug occured. After updating to 30 it persists.

### Expected behavior

Setup-Checks try to access e. g. 
"HEAD /nextcloud/core/fonts/NotoSans-Regular-latin.woff2 HTTP/1.1"
instead of
"HEAD /nextcloud/nextcloud/core/fonts/NotoSans-Regular-latin.woff2 HTTP/1.1"

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "maintenance": false,
        "overwrite.cli.url": ""***REMOVED SENSITIVE VALUE***".de\/nextcloud",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "app.mail.verify-tls-peer": false,
        "allow_local_remote_servers": true,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "DE",
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.20.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.0
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - guests: 4.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - passwords: 2024.9.20
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.2
  - workflowengine: 2.12.0
Disabled:
  - activity: 3.0.0 (installed 2.8.2)
  - contactsinteraction: 1.11.0 (installed 1.4.0)
  - encryption: 2.18.0 (installed 1.6.0)
  - files_external: 1.22.0
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
  - weather_status: 1.10.0 (installed 1.3.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by kesselb** [comment] 2024-09-26 20:20
Thanks for your report :+1: 

Likely a duplicate of https://github.com/nextcloud/server/issues/47950.

It should be fixed with 30.0.1 (2024-10-10).

If you still see the issue with 30.0.1, please log a new issue.

**Closed by kesselb** 2024-09-26 20:20 UTC
Labels: bug, 0. Needs triage
