### ISSUE TITLE
pop up window scrollbar issue

### ISSUE THREAD

**Issue by bobblkabb** [nextcloud/server#11860] opened 2018-10-16 07:51 UTC
### Steps to reproduce
1. Mark folder or file 
2. Click 'copy/move' function
3. Windows pops up to select target folder

### Expected behaviour
If you have a larger list with many folders it should be possible to chose any folder

### Actual behaviour
The last folder on the bottom of the list can't be selected (Internet Explorer) or hardly be selected (Firefox) because the slider doesn't allow to scroll to the very bottom of the list.
Might be related to #11468 and/or #11624 which was fixed by 14.0.3.

### Server configuration

**Operating system**: Ubuntu 18.04.1

**Web server:** Apache 2.4.29

**Database:** mysql Ver 14.14 Distrib 5.7.23

**PHP version:** php 7.2

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** cli

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>

<summary>Config report</summary>
{         
    "system": {            
        "instanceid": "***REMOVED SENSITIVE VALUE***",   
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",    
        "trusted_domains": [
            "[internal ipv4 address]",
            "vmserver",          
            "[ipv4 adress]",
            "cloud.mycloud.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --noLOgo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "skeletondirectory": "\/var\/www\/nextcloud\/core\/skeleton\/",
        "maintenance": false,
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/data\/nextcloud.log",
        "log_rotate_size": 104857600,
        "log_authfailip": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "NTLM",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "auto",
        "default_language": "en_GB",
        "overwrite.cli.url": "https:\/\/cloud.mycloud.de",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
There are no commands defined in the "ldap" namespace.
</details>

### Client configuration
**Browser:** Internet Explorer 11 and Firefox 62.0.3 (64Bit)

**Operating system:** Solus 3.9999

#### Web server error log
<details>
<summary>Web server error log</summary>
[Tue Oct 16 06:25:52.494734 2018] [mpm_prefork:notice] [pid 27703] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Tue Oct 16 06:25:52.494760 2018] [core:notice] [pid 27703] AH00094: Command line: '/usr/sbin/apache2'

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

![bildschirmaufnahme vom 2018-10-16 08 42 06](https://user-images.githubusercontent.com/7815101/46999023-a90c8d00-d124-11e8-99f5-d2e60c043fc2.png)

**Comment by skjnldsv** [comment] 2020-04-10 08:00
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 08:00 UTC
Labels: 0. Needs triage, bug
