### ISSUE TITLE
Error (Sabre\DAV\Exception\BadRequest) for "dav:sync-birthday-calendar $USER"

### ISSUE THREAD

**Issue by sokai** [nextcloud/server#12754] opened 2018-11-30 08:44 UTC
### Background
A user at my NC installation had some birthdays twice in his birthday calendar and I (the admin) wanted to fix it. So I found #1854 (and the [forums thread "How can I create the birthdays calendar again?"](https://help.nextcloud.com/t/7020)).

Because I wouldn't interact with the user (and force him to remove his bday calendar) like mentioned in #1854 I only tried the occ command `dav:sync-birthday-calendar` for the users account and got the exception.
After looking around I found the same problem reported from @christian-weiss at https://github.com/nextcloud/contacts/issues/507#issuecomment-369721910 (and ff.) without a solution for that exception.

Also because I can't identify the (maybe) corrupted VCard (in the database?) or something else I opened this issue …

### Steps to reproduce
1. `/usr/bin/php occ -v dav:sync-birthday-calendar $user`

### Expected behaviour
* The bday calendar of the $user should be (re-)synced.
* People from the address book (with birthdays or anniversaries) are shown (only) one time in the bday calendar of the $user.

### Actual behaviour
Exception.

```
Start birthday calendar sync for $user

  [Sabre\DAV\Exception\BadRequest]
  Calendar object with uid already exists in this calendar collection.

Exception trace:
 () at /**path removed**/apps/dav/lib/CalDAV/CalDavBackend.php:988
 OCA\DAV\CalDAV\CalDavBackend->createCalendarObject() at /**path removed**/apps/dav/lib/CalDAV/BirthdayService.php:309
 OCA\DAV\CalDAV\BirthdayService->updateCalendar() at /**path removed**/apps/dav/lib/CalDAV/BirthdayService.php:99
 OCA\DAV\CalDAV\BirthdayService->onCardChanged() at /**path removed**/apps/dav/lib/CalDAV/BirthdayService.php:248
 OCA\DAV\CalDAV\BirthdayService->syncUser() at /**path removed**/apps/dav/lib/Command/SyncBirthdayCalendar.php:89
 OCA\DAV\Command\SyncBirthdayCalendar->execute() at /**path removed**/3rdparty/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /**path removed**/3rdparty/symfony/console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /**path removed**/3rdparty/symfony/console/Application.php:228
 Symfony\Component\Console\Application->doRun() at /**path removed**/3rdparty/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at /**path removed**/lib/private/Console/Application.php:173
 OC\Console\Application->run() at /**path removed**/console.php:90
 require_once() at /**path removed**/occ:11

dav:sync-birthday-calendar [<user>]
```

### Server configuration

**Operating system**: Linux (Debian GNU/Linux 9)

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 13.0.8 (update channel "production"; I never got a upgrade option to NC14)

**Updated from an older Nextcloud/ownCloud or fresh install:** came from OC (unknown version) years ago and upgraded step-by-step

Thanks in advance for any hints and/or fixing this bug …!

**Comment by nursoda** [comment] 2019-01-03 17:24
Same issue here. Have you had any insights on your issue?
VERY annoying that the error message doesn't contain the conflicting UID.

**Comment by sokai** [comment] 2019-02-12 08:05
FYI: same behaviour after upgrade to v15.0.4 (on upgrade channel „production“) :-|

**Comment by georgehrke** [comment] 2019-09-14 14:21
Duplicate of #8629 indeed

**Closed by georgehrke** 2019-09-14 14:21 UTC
Labels: 0. Needs triage
