### ISSUE TITLE
20.0.4 breaks with richdocuments enabled

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#24746] opened 2020-12-17 14:28 UTC
This is related to the bug 1282 on richdocuments but it is not the same bug.

Setup:
Nextcloud in it's own VM + Collabora on another VM.
Nextcloud is on a bare metal, no snap no docker.
Collabora is on debian 10 in a docker install using the latest docker version from the official docker repos.

With a completely fresh richdocuments install on 20.02 the install would freeze for 30-60 seconds every page load but would still let you to go to the settings page and configure collabora. Once configured the installation would work as normal with no delay unless the collabora server is down.

However with 20.04 with richdocuments not configured the **entire install will break** and will not load any pages unless you disable richdocuments from occ.

It would be great if this issue could get looked into.

Config:
PHP 7.4.13
Postgresql 13

**Comment by kesselb** [comment] 2020-12-17 19:18
Something in the logs?

**Comment by SimplyCorbett** [comment] 2020-12-25 19:13
Nothing in the logs.

**Comment by ealmonte32** [comment] 2020-12-30 20:03
Are you seeing this error as well as the original one you submitted?


![Screen Shot 2020-12-30 at 2 58 36 PM](https://user-images.githubusercontent.com/24350198/103378375-24fa1200-4ab0-11eb-8be3-6c36f84f3502.png)
![Screen Shot 2020-12-30 at 2 58 43 PM](https://user-images.githubusercontent.com/24350198/103378376-2592a880-4ab0-11eb-8c82-e998e5d4770e.png)

**Comment by SimplyCorbett** [comment] 2020-12-30 20:31
I don't know. Once richdocuments is enabled nextcloud does not load any further pages. This behavior only started after 20.0.4. 20.0.2 did load pages even if it took 45+ seconds until richdocuments was configured correctly.

There is a dozen or so other people having a similar problem over on richdocuments github. The only difference is their pages load in eventually whereas mine do not.

**Comment by SimplyCorbett** [comment] 2021-01-05 03:29
Installation is still broken.

@kesselb With debug level 0 enabled these are the only errors in the log.

`{"reqId":"iRDryosHLQdWlyhRP7sv","level":3,"time":"2021-01-05T03:16:13+00:00","remoteAddr":"22215412512512512","user":"simplycorbett","app":"core","method":"GET","url":"/core/preview?fileId=68814&c=fcba3db3b4cb820e8ea1348680ade787&x=250&y=250&forceIcon=0","message":{"Exception":"ImagickException","Message":"attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/422","Code":499,"Trace":[{"file":"/var/www/filerot/lib/private/Preview/Bitmap.php","line":87,"function":"readimage","class":"Imagick","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Bitmap.php","line":50,"function":"getResizedPreview","class":"OC\\Preview\\Bitmap","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/GeneratorHelper.php","line":63,"function":"getThumbnail","class":"OC\\Preview\\Bitmap","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Generator.php","line":244,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/filerot/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/filerot/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/filerot/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/filerot/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/filerot/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/filerot/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/filerot/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/filerot/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/filerot/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/filerot/lib/private/Preview/Bitmap.php","Line":87,"CustomMessage":"File: /simplycorbett/files/1000/Scan2020-12-09_092514.pdf Imagick says:"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"kBiZ8e1MQDLCH4ThcCNC","level":3,"time":"2021-01-05T03:18:33+00:00","remoteAddr":"50.123.68.140","user":"simplycorbett","app":"core","method":"GET","url":"/core/preview?fileId=68814&c=fcba3db3b4cb820e8ea1348680ade787&x=250&y=250&forceIcon=0","message":{"Exception":"ImagickException","Message":"attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/422","Code":499,"Trace":[{"file":"/var/www/filerot/lib/private/Preview/Bitmap.php","line":87,"function":"readimage","class":"Imagick","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Bitmap.php","line":50,"function":"getResizedPreview","class":"OC\\Preview\\Bitmap","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/GeneratorHelper.php","line":63,"function":"getThumbnail","class":"OC\\Preview\\Bitmap","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Generator.php","line":244,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Generator.php","line":140,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/filerot/lib/private/Preview/Generator.php","line":109,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/filerot/lib/private/PreviewManager.php","line":190,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/filerot/core/Controller/PreviewController.php","line":170,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/filerot/core/Controller/PreviewController.php","line":143,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/filerot/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/filerot/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/filerot/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/filerot/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/filerot/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/filerot/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/filerot/lib/private/Preview/Bitmap.php","Line":87,"CustomMessage":"File: /simplycorbett/files/1000/Scan2020-12-09_092514.pdf Imagick says:"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
ssssssssssssssssss
{"reqId":"kflrpBwF3XkCr57nEHtF","level":0,"time":"2021-01-05T03:26:45+00:00","remoteAddr":"12512512512","user":"dragon","app":"contacts","method":"GET","url":"/settings/apps/installed/richdocuments","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"kflrpBwF3XkCr57nEHtF","level":0,"time":"2021-01-05T03:26:45+00:00","remoteAddr":"12512512512","user":"dragon","app":"richdocuments","method":"GET","url":"/settings/apps/installed/richdocuments","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"kflrpBwF3XkCr57nEHtF","level":0,"time":"2021-01-05T03:26:45+00:00","remoteAddr":"512512512512","user":"dragon","app":"files_external","method":"GET","url":"/settings/apps/installed/richdocuments","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"kflrpBwF3XkCr57nEHtF","level":0,"time":"2021-01-05T03:26:45+00:00","remoteAddr":"125125125","user":"dragon","app":"files_sharing","method":"GET","url":"/settings/apps/installed/richdocuments","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"kflrpBwF3XkCr57nEHtF","level":0,"time":"2021-01-05T03:26:45+00:00","remoteAddr":"12512512512","user":"dragon","app":"twofactor_totp","method":"GET","url":"/settings/apps/installed/richdocuments","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}

`

**Comment by juliushaertl** [comment] 2021-01-05 11:35
Do you have memory caching enabled? Please try to fill out the issue template to provide as much information up front as possible next time ;)

**Comment by SimplyCorbett** [comment] 2021-01-05 13:35
> Do you have memory caching enabled?

No and redis is not installed. All I'm running is nginx mainline and php 7.4 fpm. Nextcloud 20.0.2 worked fine, so it's something that's changed between 20.0.2 and 20.0.4.

**Comment by SimplyCorbett** [comment] 2021-01-05 13:58
```
Drive /var/www/filerot # sudo -u nginx php ./occ richdocuments:activate-config       
Failed to activate any config changes
cURL error 28: Connection timed out after 45001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
#0 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
#3 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Client.php(361): GuzzleHttp\HandlerStack->__invoke()
#11 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Client.php(163): GuzzleHttp\Client->transfer()
#12 /var/www/filerot/3rdparty/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Client->requestAsync()
#13 /var/www/filerot/lib/private/Http/Client/Client.php(233): GuzzleHttp\Client->request()
#14 /var/www/filerot/apps/richdocuments/lib/WOPI/DiscoveryManager.php(84): OC\Http\Client\Client->get()
#15 /var/www/filerot/apps/richdocuments/lib/WOPI/DiscoveryManager.php(56): OCA\Richdocuments\WOPI\DiscoveryManager->fetchFromRemote()
#16 /var/www/filerot/apps/richdocuments/lib/WOPI/Parser.php(41): OCA\Richdocuments\WOPI\DiscoveryManager->get()
#17 /var/www/filerot/apps/richdocuments/lib/Command/ActivateConfig.php(70): OCA\Richdocuments\WOPI\Parser->getUrlSrc()
#18 /var/www/filerot/3rdparty/symfony/console/Command/Command.php(255): OCA\RichDocuments\Command\ActivateConfig->execute()
#19 /var/www/filerot/3rdparty/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#20 /var/www/filerot/3rdparty/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#21 /var/www/filerot/3rdparty/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#22 /var/www/filerot/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#23 /var/www/filerot/console.php(100): OC\Console\Application->run()
#24 /var/www/filerot/occ(11): require_once('/var/www/filero...')
#25 {main}
Drive /var/www/filerot # 
```

**Comment by juliushaertl** [comment] 2021-01-08 15:22
Closing as a duplicate of Duplicate of https://github.com/nextcloud/richdocuments/issues/1282

**Closed** 2021-01-08 15:22 UTC
Labels: 0. Needs triage, bug, needs info
