### ISSUE TITLE
LDAP wizard issue

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#10270] opened 2018-07-17 11:03 UTC
Hi,

With the latest master, an issue occurs in the LDAP wizard (see step 4):

1) Main server and backup server are reachable => "Configuration OK" is shown, clicking "Verify settings and count users" shows user count as expected
2) Main server becomes unreachable (to reproduce, set invalid port & refresh the page in the browser) => "Configuration OK" is shown, clicking "Verify settings and count users" shows user count as expected
3) Main server becomes reachable again (to reproduce, set correct port & refresh the page in the browser) => "Configuration OK" is shown, clicking "Verify settings and count users" shows user count as expected
4) Backup server becomes unreachable (to reproduce, set invalid port & refresh the page in the browser) => "Configuration incorrect" is shown, "The Base DN appears to be wrong" error is shown, clicking "Verify settings and count users" doesn't show user count

The issue seems to only impact the LDAP wizard. To reproduce it, please follow ALL these steps in the outlined order, thanks!

**Comment by MorrisJobke** [comment] 2018-07-17 18:10
@juliushaertl Mind to have a look at this as well?

**Comment by juliushaertl** [comment] 2018-07-31 10:54
@GitHubUser4234 Thanks for your report. Unfortunately I'm unable to reproduce the issue on current master. Are you sure that when you tested this every change of the port has been saved (by removing the focus from the input field)? 

Can you still reproduce this and if you reload after check 4 do both server settings have the correct port number set?

**Comment by MorrisJobke** [comment] 2018-08-24 15:04
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2018-08-24 15:04 UTC
Labels: feature: ldap, needs info

**Comment by MorrisJobke** [comment] 2018-08-24 15:05
@blizzz You also did quite some changes to the Wizard, right? And also there was the plan to improve the wizard heavily soon because it had some issues like the state of the wizard in the past. Is there a ticket with those plans?

**Comment by blizzz** [comment] 2018-08-24 15:13
@MorrisJobke i have some changes in the wizard, but nothing fundamentally. We've had some fixes with failed server handling, but they went in before @GitHubUser4234 opened this issue. A wizard fix is pending, but unrelated.

What could interfere is caching, if @GitHubUser4234 used for instance redis, as clearing is not necessarily reliable iirc. main server could have been cached as unreachable while it got back online and having the backup server down would cause those results. Although the messages presented would be misleading.
