### ISSUE TITLE
Deny *2 space for uploading file

### ISSUE THREAD

**Issue by dvolozhinok** [nextcloud/server#24755] opened 2020-12-18 08:52 UTC
Hello, dear Nextcloud developers!

On latest Nextcloud versions it uses temporary directory before putting files into proper directory.

For this reason, it takes *2 places to place the file. if it is a small document, then there is no problem. If it is a large file, but we have a lot of TB of space, then there is no problem. But if we have 30 GB and someone wants to download a movie file, they will get a download error.
As service provider, we are interested in both big and small installation, as we cover big businesses and personal projects. And we would like to give our best to make people feel happy and comfortable with Nextcloud as both business and personal solution.

Can you please try your best to review this mechanism to make small Nextcloud installations feel comfortable for users?

**To reproduce**

Create VM with 30 GB of space, install Nextcloud, try to upload file with 16+ filesize.

**Comment by acsfer** [comment] 2020-12-18 09:06
Duplicate of https://github.com/nextcloud/server/issues/7920?

**Comment by kesselb** [comment] 2020-12-18 09:33
Duplicate of #7920

**Closed by kesselb** 2020-12-18 09:33 UTC
Labels: 0. Needs triage, enhancement
