### ISSUE TITLE
In Contacts, for each contact the trash can icon tooltip says "Download" in Nextcloud 12

### ISSUE THREAD

**Issue by mlncn** [nextcloud/server#8691] opened 2018-03-06 14:16 UTC
As this is Nextcloud 12 it may have been fixed but i couldn't find an issue and it should be a very fun easy fix!

In Contacts app, the trash can icon has a "Download" tooltip, just like the down arrow icon next to it that does indeed download.  The trash can icon, as expected for sighted people, does delete the contact— and there's no warning or undo, incidentally, so anyone with images not loading or using a screenreader or unable to make out the small greyscale icons could lose the contact they were trying to download.

**Comment by ChristophWurst** [comment] 2018-03-06 15:31
Duplicate of https://github.com/nextcloud/contacts/issues/255

**Closed by ChristophWurst** 2018-03-06 15:31 UTC
