### ISSUE TITLE
[Bug]: Object store does not support multipart upload

### ISSUE THREAD

**Issue by cpuch** [nextcloud/server#39736] opened 2023-08-07 08:19 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's not possible to a upload a 530Mo ISO image from any web browsers though it's working from the NextCloud client. 

It used to work with Nextcloud 25.

The error message is : OCP\Files\GenericFileException: Object store does not support multipart upload

### Steps to reproduce

1. Install NextCloud 27
2. Configure Swift as a primary object storage

### Expected behavior

Being able to upload big files.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "debug": true,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "nc_",
        "mysql.utf8mb4": true,
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "autocreate": true,
                "user": {
                    "name": "***REMOVED SENSITIVE VALUE***",
                    "password": "***REMOVED SENSITIVE VALUE***",
                    "domain": {
                        "name": "Default"
                    }
                },
                "scope": {
                    "project": {
                        "name": "7714518278425330",
                        "domain": {
                            "name": "Default"
                        }
                    }
                },
                "tenantName": "service",
                "serviceName": "swift",
                "region": "GRA",
                "url": "https:\/\/auth.cloud.ovh.net\/v3\/",
                "bucket": "nextcloud"
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.season-of-mist.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "27.0.1.2",
        "overwrite.cli.url": "https:\/\/cloud.season-of-mist.com",
        "htaccess.RewriteBase": "\/",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_template_class": "OCA\\CustomEmailTemplate\\MyClass",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "filelocking.enabled": true,
        "enable_previews": false,
        "theme": "",
        "logtimezone": "Europe\/Paris",
        "simpleSignUpLink.shown": false,
        "maintenance": false,
        "loglevel": 0,
        "default_phone_region": "FR",
        "trashbin_retention_obligation": "60, 300",
        "session_keepalive": true,
        "check_for_working_htaccess": true,
        "app_install_overwrite": [
            "sharepoint"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - systemtags: 1.17.0
  - theming: 2.2.0
  - theming_customcss: 1.14.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0 (installed 2.4.0)
  - circles: 27.0.1 (installed 25.0.0)
  - contactsinteraction: 1.8.0 (installed 1.0.0)
  - dashboard: 7.7.0 (installed 7.0.0)
  - encryption: 2.15.0
  - files_accesscontrol: 1.17.0 (installed 1.17.0)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.19.0 (installed 1.19.0)
  - metadata: 0.19.0 (installed 0.19.0)
  - photos: 2.3.0 (installed 1.1.0)
  - recommendations: 1.6.0 (installed 0.7.0)
  - survey_client: 1.15.0 (installed 1.7.0)
  - suspicious_login: 5.0.0
  - text: 3.8.0 (installed 3.0.1)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0 (installed 1.0.1)
  - weather_status: 1.7.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
[webdav] Error: OCP\Files\GenericFileException: Object store does not support multipart upload at <<closure>>

 0. <<closure>>
    OC\Files\ObjectStore\ObjectStoreStorage->startChunkedWrite()
 1. /var/www/html/cloud.season-of-mist.com/lib/private/Files/Storage/Wrapper/Wrapper.php line 524
    call_user_func_array()
 2. <<closure>>
    OC\Files\Storage\Wrapper\Wrapper->__call()
 3. /var/www/html/cloud.season-of-mist.com/lib/private/Files/Storage/Wrapper/Wrapper.php line 524
    call_user_func_array()
 4. <<closure>>
    OC\Files\Storage\Wrapper\Wrapper->__call()
 5. /var/www/html/cloud.season-of-mist.com/lib/private/Files/Storage/Wrapper/Wrapper.php line 524
    call_user_func_array()
 6. /var/www/html/cloud.season-of-mist.com/apps/dav/lib/Upload/ChunkingV2Plugin.php line 133
    OC\Files\Storage\Wrapper\Wrapper->__call()
 7. /var/www/html/cloud.season-of-mist.com/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Upload\ChunkingV2Plugin->afterMkcol()
 8. /var/www/html/cloud.season-of-mist.com/3rdparty/sabre/dav/lib/DAV/Server.php line 482
    Sabre\DAV\Server->emit()
 9. /var/www/html/cloud.season-of-mist.com/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
10. /var/www/html/cloud.season-of-mist.com/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
11. /var/www/html/cloud.season-of-mist.com/apps/dav/lib/Server.php line 364
    Sabre\DAV\Server->exec()
12. /var/www/html/cloud.season-of-mist.com/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
13. /var/www/html/cloud.season-of-mist.com/remote.php line 172
    require_once("/var/www/html/c ... p")

MKCOL /remote.php/dav/uploads/admin/web-file-upload-d3f1d054d555ee74f198f348d4d7c0f2-1691395209901
from 178.16.171.35 by admin at 2023-08-07T10:00:10+02:00
```

**Comment by solracsf** [comment] 2023-08-07 09:56
Duplicate of https://github.com/nextcloud/server/issues/39088

**Closed** 2023-08-07 09:57 UTC
Labels: bug, 0. Needs triage
