### ISSUE TITLE
Share popover invisible (must scroll up to see it)

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/server#27505] opened 2021-06-15 08:57 UTC
### Steps to reproduce
1. On the Files app scroll to the bottom of a folder with many files (more than a page)
2. On a shared file near the bottom of this list, click on the share button 
3. On the "Share" tab, click the "..." button of a user to see the share option popover

### Expected behaviour
The popover should appear near the button just clicked and maybe should not be sensible to scrolling (fixed CSS property ?)

### Actual behaviour
The popover isn't displayed on screen because it appears on the top of the window, you need to scroll up to see it. 
![SharePopover](https://user-images.githubusercontent.com/6248852/122024146-72e9a480-cdc8-11eb-910b-de7b70ef3ae5.png)

### Server configuration

**Operating system:**
Linux 4.19.0-16-amd64 x86_64

**Web server:**
Apache 2.4

**Database:**
Mysql 10.3.27

**PHP version:**
Version : 7.3.27

**Nextcloud version:** (see Nextcloud admin page)
tested on Nextcloud 21.0.2 or 20.0.4 : same behaviour

<details>
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - calendar: 2.2.2
  - circles: 0.21.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - drawio: 1.0.0
  - emlviewer: 0.0.21
  - event_update_notification: 1.2.0
  - external: 3.8.1
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_downloadactivity: 1.10.0
  - files_external: 1.12.0
  - files_frommail: 0.4.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_texteditor: 2.14.0
  - files_trackdownloads: 1.10.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - flow_notifications: 1.1.0
  - group_everyone: 0.1.7
  - groupfolders: 9.0.1
  - impersonate: 1.8.0
  - integration_whiteboard: 0.0.14
  - issuetemplate: 0.7.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - metadata: 0.13.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.0.2
  - password_policy: 1.11.0
  - pdfdraw: 0.1.2
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - rainloop: 7.1.2
  - ransomware_protection: 1.10.1
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - sharingpath: 0.3.0
  - spreed: 11.2.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - talk_simple_poll: 1.3.1
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - welcome: 0.0.5
  - workflow_script: 1.6.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - announcementcenter
  - auto_groups
  - bruteforcesettings
  - collectives
  - encryption
  - ldap_contacts_backend
  - ldapcontacts
  - mail
  - nextcloud_announcements
  - quicknotes
  - recommendations
  - weather_status
  - workflow_pdf_converter

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "next.agglo-montbeliard.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "https:\/\/next.agglo-montbeliard.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 2,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "logfilemode": 416,
        "debug": false,
        "maintenance": false,
        "app.mail.verify-tls-peer": false,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "bruteforcesettings",
            "emlviewer",
            "files_frommail",
            "mindmap_app",
            "issuetemplate",
            "pdfdraw"
        ],
        "onlyoffice": {
            "verify_peer_off": true
        }
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
not relevant

### Client configuration
**Browser:**
Firefox 89.0 (64 bits), Chromium Version 91.0.4472.101 (Build officiel) snap (64 bits)

**Operating system:**
Linux Xubuntu, Windows 10
### Logs
 no relevant logs as it's a CSS issue.

#### Browser log
<details>
<summary>Browser log</summary>
no relevant JS log in the console
</details>

**Comment by steffen-moser** [comment] 2021-06-30 04:04
We see the same problem here. Our server configuration:

### Operating system:
Oracle Solaris 11.4 SRU 34

### Web server:
Apache 2.4.46

### Database:
MySQL 5.7.33

### PHP version:
Version : 7.4.15

### Nextcloud version:
Nextcloud 20.0.10

**Comment by thopico** [comment] 2021-07-02 12:39
Same here. Happened after upgrade from 19.0.10 up to 21.0.2 with docker installation.

**Comment by Mer0me** [comment] 2021-07-20 12:18
Always visible on NextCloud 22.0.0

**Comment by szaimen** [comment] 2021-08-08 15:51
Duplicate of https://github.com/nextcloud/server/issues/23872

**Closed by szaimen** 2021-08-08 15:51 UTC
Labels: bug, 0. Needs triage
