### ISSUE TITLE
a file name can not include a question mark

### ISSUE THREAD

**Issue by Marie-LouWeymann** [nextcloud/server#23911] opened 2020-11-05 15:15 UTC
![image](https://user-images.githubusercontent.com/58940117/98259104-f6fdc300-1f81-11eb-8ad2-83252633243d.png)
![Bildschirmfoto 2020-11-03 um 18 45 06](https://user-images.githubusercontent.com/58940117/98259153-08df6600-1f82-11eb-9811-48e760f4e4a6.png)

**Comment by ccoenen** [comment] 2020-11-05 19:42
We did encounter this too, but so far we were not able to connect the dots.

When someone uploads a PDF where the _file name_ includes a `?`, then this behaviour will be visible. Reproducing this was not easy for me, because I do not have a Mac, and Windows prohibits the question mark anyway. Now at least I have a reason _why_ the pdf viewer fails.

**Comment by wiswedel** [comment] 2020-11-06 12:18
duplicate of https://github.com/nextcloud/server/issues/20482

**Closed by wiswedel** 2020-11-06 12:18 UTC

**Comment by wiswedel** [comment] 2020-11-06 12:20
Don't be offended about the closing, @Marie-LouWeymann. 
Even though not actually a duplicate (this one is about the PDF viewer, the other one about the sync), it is the same root issue.
