### ISSUE TITLE
CSS of new theme is not being used

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#5276] opened 2017-06-06 16:22 UTC
### Steps to reproduce

1. create directories and file `./themes/test/core/css/styles.css`
2. insert the following in the file:

       #body-login {
           background-image: none;
       }

3. set `  'theme' => 'test',` in `config.php`
4. reload the login page

### Expected behaviour
there should not be a background image

### Actual behaviour
there is still the background image, which is loaded from `/core/img/background.jpg?v=1`

### Server configuration

Current v12.0.0, no theming app installed, no error log messages, write permissions set ready for web user.

**Comment by juliushaertl** [comment] 2017-06-06 20:29
Duplicate of https://github.com/nextcloud/server/issues/5036
Renaming the styles.css to server.css should fix this.

**Comment by juliushaertl** [comment] 2017-06-06 20:30
@mcnesium btw. the theming app has a button to just use the theming color as login background with Nextcloud 12. :wink:

**Closed by juliushaertl** 2017-06-06 20:29 UTC

**Comment by mcnesium** [comment] 2017-06-07 12:08
@juliushaertl thank you for pointing that out. My themes differ a little more than just the background-color from the default though (logos, favicons, folder icons, custom strings, custom css…) so the theming app is not an option. It works with renaming the file to `server.css`.
