### ISSUE TITLE
[regression] symlinked apps and CSS - ResourceLocator can not find a web root

### ISSUE THREAD

**Issue by Daryes** [nextcloud/server#13556] opened 2019-01-13 11:39 UTC
Seems to be the same problem as #5057 and others simlar.   
Given the logs, it seems this was fixed in 12.x, but a change somewhere later removed the fix partially. I can go back to at least v13.0.1.1, up to 15.0.2.0

Currently, the apps work fine, while stored in a different dir symlinked back to the nextcloud main directory. But each time a user access them in the UI, an entry is generated in the log with an access error to a css file.

### Steps to reproduce
1. store the non built-in application in another directory, which is a symlink
- nexcloud is under `/server/websites/nextcloud/nextcloud-<version>/`
- external app are under `/server/websites/nextcloud/conf/apps2/`
- create a symlink for nextcloud current version :  
 `ln -s /server/websites/nextcloud/nextcloud-<version> /server/websites/nextcloud/nextcloud`
- create the apps symlink :   
`ln -s /server/websites/nextcloud/conf/apps2 /server/websites/nextcloud/nextcloud/apps2`

2. change the config.php with the app2 path information :
````
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/server/websites/nextcloud/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/server/websites/nextcloud/nextcloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
````
3. use nextcloud, add some apps (like calendar, contacts,  ...)
4. click on the app bar at the top to show each of them, no need to do more. You can also see they appear correctly, and in fact they work correctly.
5. check the log. Multiply the number of line by the number of external apps, and the number of users.

### Expected behaviour
no warning in the logs

### Actual behaviour
these entries in the log, one for each application under a symlink in the path, each time a user selects the application panel in his browser. Given the filename, I suppose this is automatically generated, as nothing like this exists physically.
````
ResourceLocator can not find a web root (root: /server/websites/nextcloud/conf/apps2/contacts, file: index.php/css/contacts/3d4b-bdca-contacts.css?v=96f9b18ad190af3746726337d98b2100, webRoot: , throw: true)

ResourceLocator can not find a web root (root: /server/websites/nextcloud/conf/apps2/calendar, file: index.php/css/calendar/029b-bdca-app.min.css?v=96f9b18ad190af3746726337d98b2100, webRoot: , throw: true)

ResourceLocator can not find a web root (root: /server/websites/nextcloud/conf/apps2/notes, file: index.php/css/notes/21f4-bdca-notes.css?v=96f9b18ad190af3746726337d98b2100, webRoot: , throw: true)

(... continue for any application under the apps2 directory)
````

### Server configuration

**Operating system**: Ubuntu 18.04
**Web server:** Apache 2.4 
**Database:** Mariadb 10.3
**PHP version:** PHP 7.2.14

**Nextcloud version:** 15.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from 14.0.4
**Where did you install Nextcloud from:** : tar.gz from nextcloud.com

**Comment by danielkesselberg** [comment] 2019-01-15 23:38
Ref https://github.com/nextcloud/server/issues/10437

**Comment by nebulade** [comment] 2019-05-02 12:42
This also happens with the Cloudron app package with Nextcloud version 16.0.0
On Cloudron the apps folder is also symlinked. The files itself are publicly reachable just fine, still the ResourceLocator shows them missing in the error log.

**Comment by the-sane** [comment] 2019-07-15 18:27
Confirming that this remains an issue in the v16 release series.  It affects the new text app (https://github.com/nextcloud/text/issues/157)

I believe this is the same issue that's being discussed over on the snap here: https://github.com/nextcloud/nextcloud-snap/issues/902.  @juliushaertl stated in https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-510387708:
> This is most likely an issue of https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Template/ResourceLocator.php#L128 that doesn't detect the webroot properly if the apps directory is in a different place.

**Comment by szaimen** [comment] 2019-07-24 17:18
@all: Please fix this issue finally! That issue is very annoying and now also affects the usability (especially when enabling the dark mode through accessibility settings. If doing so there are a lot of icons missing in many apps (also in nextcloud_files).

**Comment by szaimen** [comment] 2019-07-24 17:32
I think that is also the same error:
https://github.com/nextcloud/nextcloud-snap/issues/402

**Comment by kesselb** [comment] 2019-07-24 22:49
https://github.com/nextcloud/server/blob/17d5e47937fc3149c7da5e5391586d8c0b26d72b/lib/private/Template/CSSResourceLocator.php#L82

Symlink is resolved to early. findWebRoot method tries to determinate the webroot from the path. Nextcloud is installed to /home/nextcloud and the apps are in /home/nextcloud-apps. /home/nextcloud/apps2 is a symlink to /home/nextcloud/apps2. Its possible to detect the webroot for /home/nextcloud/apps2 but not /home/nextcloud-apps.

This one is the faulty commit https://github.com/nextcloud/server/pull/7061/commits/b0d296639cfc5d0460987787cc9869c5e5473d85

cc @kyrofa @juliushaertl

**Comment by kyrofa** [comment] 2019-07-24 22:58
> This one is the faulty commit b0d2966

I'm not sure that's accurate given that the commit you reference is very old (it's what fixed things back in v12). Behavior around it must have changed in order to cause this regression.

**Comment by kesselb** [comment] 2019-07-24 23:14
> I'm not sure that's accurate given 

That's right! I'm sorry my statement was misleading. 

> Behavior around it might have changed in order to cause this regression

I think so. Could you check if it works for snap without realpath?

**Comment by georgehrke** [comment] 2019-08-05 09:59
Summoning our experts here: @skjnldsv @juliushaertl :) 

@skjnldsv suspects it's just a debug log accidentally logged as error.

**Comment by szaimen** [comment] 2019-08-05 10:34
> @skjnldsv suspects it's just a debug log accidentally logged as error.

I don't think so as i mentioned in https://github.com/nextcloud/text/issues/187

**Comment by georgehrke** [comment] 2019-08-05 10:43
@skjnldsv Could you specify what kind if info is missing here? :)

**Comment by the-sane** [comment] 2019-08-05 15:57
@skjnldsv I can also confirm the missing toolbar buttons as a result of this problem, and I also have Nextcloud installed via snap.  For me, it's a problem with both the light and dark themes though.  It is not just a logging mistake, and @juliushaertl has confirmed that (see below, or above).

---
As for the info requested, okay, I think this is everything we know about this issue so far, gathered from this and related issues:

@szaimen posted a screenshot of the missing buttons in the new text app here:
https://github.com/nextcloud/text/issues/187#issuecomment-514387337

@juliushaertl has said this server issue is the cause of the problem, also explaining why it's not just a bug in the logger:
https://github.com/nextcloud/text/issues/187#issuecomment-514518811
https://github.com/nextcloud/text/issues/187#issuecomment-514611359
https://github.com/nextcloud/text/issues/187#issuecomment-514616996
> This is most likely an issue of the server in combination with the snap: [nextcloud/server#13556](https://github.com/nextcloud/server/issues/13556)

> We cannot workaround that because the apps directory depends on the server configuration. You might have apps-extra where the text app is located but others might have it in the regular apps or an apps2 folder. The issue here is that the server cannot find the folder, since it is not inside of the nextcloud folder when using the snap.

> https://domain/index.php/svg/files/public is a dynamic endpoint (which is handled by the Nextcloud server code) that looks for the apps folder of the files app and returns the image. (this is what fails on your setup) https://domain/apps/files/img/recent.svg will be served by your webserver so Nextcloud is not involved there.

It is an issue with many apps for anyone using Nextcloud via snap, as is being discussed here: 
https://github.com/nextcloud/nextcloud-snap/issues/902

@kyrofa, the snap maintainer, has said it's not a problem that the snap can fix:
https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-472981857
> Nothing has changed in the snap to cause this (the config has always been the same), which leads me to suspect the apps themselves, unless something broke in Nextcloud itself again.

> I've tried to give guidance on how to fix it :man_shrugging: .

@Daryes ,the OP, has stated this was fixed in a previous version of Nextcloud but has re-presented itself.
@kyrofa has given some examples:
https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-472981857
> we've dealt with this issue in the past in upstream Nextcloud (and upstream apps), for example:
> 
>[nextcloud/server#7257](https://github.com/nextcloud/server/pull/7257) 
>[nextcloud/server#7061](https://github.com/nextcloud/server/pull/7061)
>[nextcloud/server#8463](https://github.com/nextcloud/server/pull/8463) (theming app)

Here are some examples of the apps that have problems:
https://github.com/nextcloud/calendar/issues/1348
https://github.com/nextcloud/spreed/issues/1615
https://github.com/nextcloud/text/issues/157
https://github.com/rullzer/dropit/issues/22
https://github.com/nextcloud/mail/issues/1066

@juliushaertl has given some guidance on where the problem may lie:
https://github.com/nextcloud/nextcloud-snap/issues/902#issuecomment-510387708
> This is most likely an issue of https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Template/ResourceLocator.php#L128 that doesn't detect the webroot properly if the apps directory is in a different place.

As for how many people are affected by this, @jospoortvliet noted the last time something similar was fixed in 2017 that many thousands use Nextcloud via snap:
https://github.com/nextcloud/server/issues/5057#issuecomment-310830027
> It might be a small patch but we have over 1500 people with a Nextcloud Box at home who can now get 12.0.1 and that's ignoring the many thousands who use the Snap on a normal Ubuntu or other Linux system!

**Comment by kyrofa** [comment] 2019-08-05 17:30
> As for how many people are affected by this [...]

It's around 30k today, ignoring folks using similar configurations outside the snap (like the OP).

**Comment by skjnldsv** [comment] 2019-08-05 19:59
@georgehrke Julius's input :)

**Comment by skjnldsv** [comment] 2019-08-05 19:59
> @skjnldsv Could you specify what kind if info is missing here? :)

@georgehrke Julius's input :)

**Comment by juliushaertl** [comment] 2019-08-05 20:13
Well currently the insight given in the text ticket which @the-sane has quoted is all I have. I didn't have time to look further into it or setup a test system with this special setup.

**Comment by the-sane** [comment] 2019-08-21 22:31
@juliushaertl I know you're all focused on the v17 beta right now, so please let me know if there's any information that I can provide from my own install that would help here.

**Comment by pricard32** [comment] 2019-11-08 22:59
Any news? I'm still having this issue.

**Comment by CorinthCom** [comment] 2019-11-13 18:24
Started getting the same issue in the log;

ResourceLocator can not find a web root (root: /var/snap/nextcloud/16739/nextcloud/extra-apps/spreed, file: index.php/css/spreed/41bb-1b6e-merged-files.css?v=xxxxxxxxxxx, webRoot: , throw: true)

a few previous errors in log on 15.0.11 (15910)
more errors after a Snap upgrade to 16.0.5 (16739)

**Comment by kyrofa** [comment] 2019-11-20 00:06
@juliushaertl could really use some help here, it's been a log annoyance for several major releases but it negatively impacts the text app (as mentioned by @the-sane [here](https://github.com/nextcloud/server/issues/13556#issuecomment-518293309)) which is default in v17, thus blocking the snap's update to v17.

**Comment by skjnldsv** [comment] 2019-11-20 06:35
@kyrofa why are we using symlink in the snap for the appdata files?

**Comment by kyrofa** [comment] 2019-11-23 18:14
> @kyrofa why are we using symlink in the snap for the appdata files?

@skjnldsv symlinks are inherent in how all snaps work. There are a lot of useless details here so I'll gloss over some of them, but essentially, each snap is a standalone squashfs image containing all the binaries/libraries it needs. When that image is put into the snap store it gets a unique revision number. When it's installed, it and its data are referenced by that revision. Let's say it's an initial install of revision 1, then the installation looks like this:

```
+-----------------------------+
|          Nextcloud          |
|                             |
|  +----+          +-------+  |
|  |Snap+----+     | Snaps |  |
|  +----+    |     |       |  |
|            |     |  +-+  |  |
|            |     |  |1|  |  |
|            |     |  +++  |  |
|            |     |   ^   |  |
|            |     +-------+  |
|            |         |      |
|            +---------+      |
|                             |
|  +----+          +-------+  |
|  |Data+----+     | Datas |  |
|  +----+    |     |       |  |
|            |     |  +-+  |  |
|            |     |  |1|  |  |
|            |     |  +++  |  |
|            |     |   ^   |  |
|            |     +-------+  |
|            |         |      |
|            +---------+      |
|                             |
+-----------------------------+

```

The robustness of the snap upgrade story is partly because multiple revisions are kept around (three total by default). This allows for a quick revert in case an upgrade went sideways. The currently-active revision is controlled by way of a symlink (the line between the snap/data that the user is interacting with and the actual revisioned snap and data that's being used). When an update happens (say to revision two) the data from 1 is copied and becomes the data for 2, so now things look like this:

```
+-----------------------------------+
|          Nextcloud                |
|                                   |
|  +----+          +-------------+  |
|  |Snap+----+     | Snaps       |  |
|  +----+    |     |             |  |
|            |     |  +-+   +-+  |  |
|            |     |  |1|   |2|  |  |
|            |     |  +-+   +++  |  |
|            |     |         ^   |  |
|            |     +-------------+  |
|            |               |      |
|            +---------------+      |
|                                   |
|  +----+          +-------------+  |
|  |Data+----+     | Datas       |  |
|  +----+    |     |             |  |
|            |     |  +-+   +-+  |  |
|            |     |  |1|   |2|  |  |
|            |     |  +-+   +++  |  |
|            |     |         ^   |  |
|            |     +-------------+  |
|            |               |      |
|            +---------------+      |
|                                   |
+-----------------------------------+
```

Then if something is wrong with revision two, even if it's a major upgrade, the user can just `snap revert nextcloud` and they're back to where they just were with revision 1 and revision 1's data (right before the copy was made for revision 2):

```
+-----------------------------------+
|          Nextcloud                |
|                                   |
|  +----+          +-------------+  |
|  |Snap+----+     | Snaps       |  |
|  +----+    |     |             |  |
|            |     |  +-+   +-+  |  |
|            |     |  |1|   |2|  |  |
|            |     |  +++   +-+  |  |
|            |     |   ^         |  |
|            |     +-------------+  |
|            |         |            |
|            +---------+            |
|                                   |
|  +----+          +-------------+  |
|  |Data+----+     | Datas       |  |
|  +----+    |     |             |  |
|            |     |  +-+   +-+  |  |
|            |     |  |1|   |2|  |  |
|            |     |  +++   +-+  |  |
|            |     |   ^         |  |
|            |     +-------------+  |
|            |         |            |
|            +---------+            |
|                                   |
+-----------------------------------+
```

When the user is interacting with the Nextcloud snap, which revision they're actually interacting with ends up being controlled by those symlinks (hidden behind some automated tooling, of course). All snaps work this way.

**Comment by kesselb** [comment] 2019-11-23 18:52
https://github.com/nextcloud/nextcloud-snap/blob/fdc14c52b9aecfb1555c064f18aeb302ce4e9cd0/src/nextcloud/config/config.php#L18-L22

https://github.com/nextcloud/nextcloud-snap/blob/fdc14c52b9aecfb1555c064f18aeb302ce4e9cd0/src/apache/conf/httpd.conf#L97

If `text` is shipped with Nextcloud 17 it should be installed to `'/snap/'.$snap_name.'/current/htdocs/apps',` right? If yes it should work because the current code is able to find the correct web root. But I'm probably wrong ;) Is there a Nextcloud 17 snap somewhere to test?

**Comment by kesselb** [comment] 2019-11-23 21:57
I wrote a [patch](https://gist.github.com/kesselb/d035c4a7334b155143686466370bc1eb) to fix the `ResourceLocator can not find a web root` message by adding the appsroots to mappings map but text app's icons still missing :disappointed: :angry:

**Comment by kyrofa** [comment] 2019-11-24 15:44
> If text is shipped with Nextcloud 17 it should be installed to '/snap/'.$snap_name.'/current/htdocs/apps', right?

@kesselb you're exactly correct.

> Is there a Nextcloud 17 snap somewhere to test?

Sure thing, `sudo snap install nextcloud --channel=17/edge` will get you a snap built daily off of the latest-stable17 tarball. However, snaps are read-only, so that's not particularly nice for poking around. if you want to do that, you can download the snap without installing like so:

    $ snap download nextcloud --channel=17/edge

Unpack it:

    $ unsquashfs -d unpacked nextcloud_<revision>.snap

And then you can "try" it instead of installing it, which is a developer tool for essentially installing it read/write from the "unpacked" directory you just created:

    $ sudo snap try unpacked/

Now the snap is installed and listening on localhost:80, but you can modify unpacked/htdocs to your hearts content.

**Comment by kesselb** [comment] 2019-11-24 17:07
https://github.com/nextcloud/server/blob/05381f00d25e380c557a3a1100dd83e75298f130/core/Controller/SvgController.php#L99-L105

Fails.

```
appRootPath: /snap/nextcloud/current/htdocs/apps/text
appPath: tdocs/apps/text
path: /snap/nextcloud/x1/htdocstdocs/apps/text/img/h1.svg
```

Hmm. I don't see the reason for `substr($appRootPath, strlen($this->serverRoot))`. Probably some security check like "don't read svg files outside the webroot". If `$appPath` should be the app path relative to `https://nextcloud.com/` (e.g. `/extra-apps/text`) `\OC_App::getAppWebPath($appId);` is the way to go. People will still see the ResourceLocator warning. 

```
Index: core/Controller/SvgController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/Controller/SvgController.php	(revision 4f2837017c95f063d99a05b6cd6a5e73ac388d75)
+++ core/Controller/SvgController.php	(date 1574613795696)
@@ -24,6 +24,7 @@
 
 namespace OC\Core\Controller;
 
+use OCP\App\AppPathNotFoundException;
 use OCP\AppFramework\Controller;
 use OCP\AppFramework\Http;
 use OCP\AppFramework\Http\DataDisplayResponse;
@@ -96,13 +97,13 @@
 			return $this->getSvg($path, $color, $fileName);
 		}
 
-		$appRootPath = $this->appManager->getAppPath($app);
-		$appPath = substr($appRootPath, strlen($this->serverRoot));
-
-		if (!$appPath) {
+		try {
+			$appPath = $this->appManager->getAppPath($app);
+		} catch (AppPathNotFoundException $e) {
 			return new NotFoundResponse();
 		}
-		$path = $this->serverRoot . $appPath ."/img/$fileName.svg";
+
+		$path = $appPath . "/img/$fileName.svg";
 		return $this->getSvg($path, $color, $fileName);
 	}
```

cc @juliushaertl @skjnldsv @rullzer does that make sense? :thinking: Smoke test looked good to me. I don't have time next week to create a pull request and look into the tests :see_no_evil:

**Comment by the-sane** [comment] 2019-11-24 17:36
A note as a user:  While fixing the actual problem is obviously more important, those ResourceLocator errors are extremely annoying and have made our logs entirely unreadable.  Nearly every app installed produces at least one of those errors every time a page is accessed.

**Comment by kyrofa** [comment] 2019-11-24 17:43
> ```
> appRootPath: /snap/nextcloud/current/htdocs/apps/text
> appPath: tdocs/apps/text
> path: /snap/nextcloud/x1/htdocstdocs/apps/text/img/h1.svg
> ```

That sounds [very familiar](https://github.com/nextcloud/server/issues/6028#issuecomment-341874234) to the issue in the JS and CSS resource locator back in the day (fix [here](https://github.com/nextcloud/server/pull/7061)).

**Comment by kesselb** [comment] 2019-11-24 18:25
> A note as a user: While fixing the actual problem is obviously more important, those ResourceLocator errors are extremely annoying and have made our logs entirely unreadable. 

Made the web root detection work with https://gist.github.com/kesselb/d035c4a7334b155143686466370bc1eb but the generated path for the resources is wrong. I assume that for scss files the webRoot is not relevant. SCSS file is compiled and served by `core.Css.getCss`. Could not see anything broken with the patch below:

```
Index: lib/private/Template/CSSResourceLocator.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Template/CSSResourceLocator.php	(revision 4f2837017c95f063d99a05b6cd6a5e73ac388d75)
+++ lib/private/Template/CSSResourceLocator.php	(date 1574619791911)
@@ -125,26 +125,7 @@
 		if (!$scss) {
 			parent::append($root, $file, $webRoot, $throw);
 		} else {
-			if (!$webRoot) {
-				$webRoot = $this->findWebRoot($root);
-
-				if ($webRoot === null) {
-					$webRoot = '';
-					$this->logger->error('ResourceLocator can not find a web root (root: {root}, file: {file}, webRoot: {webRoot}, throw: {throw})', [
-						'app' => 'lib',
-						'root' => $root,
-						'file' => $file,
-						'webRoot' => $webRoot,
-						'throw' => $throw ? 'true' : 'false'
-					]);
-
-					if ($throw && $root === '/') {
-						throw new ResourceNotFoundException($file, $webRoot);
-					}
-				}
-			}
-
-			$this->resources[] = array($webRoot? : \OC::$WEBROOT, $webRoot, $file);
+			$this->resources[] = array(\OC::$WEBROOT, \OC::$WEBROOT, $file);
 		}
 	}
 }
```

**Comment by skjnldsv** [comment] 2019-11-25 12:35
@kyrofa can you confirm @kesselb's patch fixes your issues?

**Comment by dtzWill** [comment] 2019-12-03 22:08
Thanks for working on this, all, been following this and related issues for some time.

Anyway, sorry for the dumb question but: 

> @kyrofa can you confirm @kesselb's patch fixes your issues?

I was interested in trying this as well, but... just wanted to clarify: is applying the inlined patch by itself intended to be what is tested, or should the gist patch be used as well?
(unsure if the latest inline patch is meant to be used in addition to the latest gist, or instead of it...?)

Thanks again and I'll of course report if I find anything useful but so far I've been quiet as I've only found ways to not solve my variant of the issue :smile_cat:  .

**Comment by kyrofa** [comment] 2019-12-03 22:12
Good question, I took a crack at applying the changes [here](https://github.com/kyrofa/server/tree/bugfix/13556/cannot_find_webroot), but at least at first blush it doesn't appear to work. I need to test some more.

**Comment by kesselb** [comment] 2019-12-04 21:08
> or should the gist patch be used as well?

No. Only the patches in this thread: https://github.com/nextcloud/server/issues/13556#issuecomment-557908015 & https://github.com/nextcloud/server/issues/13556#issuecomment-557914420

> least at first blush it doesn't appear to work.

More digging ;) 

> solve my variant of the issue 

I checked the setup from post 1 https://github.com/nextcloud/server/issues/13556#issue-398648843 and the snap package https://github.com/nextcloud/server/issues/13556#issuecomment-557900585

Feel free to use the original code and something like below. Change the loglevel in `config.php` to 0 and it will write the paths to the log.

```
Index: core/Controller/SvgController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/Controller/SvgController.php	(revision be54491ae15ce76c56549fc07d5cd810cdc49d62)
+++ core/Controller/SvgController.php	(date 1575493608385)
@@ -92,11 +92,15 @@
 	public function getSvgFromApp(string $app, string $fileName, string $color = 'ffffff') {
 		$appRootPath = $this->appManager->getAppPath($app);
 		$appPath = substr($appRootPath, strlen($this->serverRoot));
+		\OC::$server->getLogger()->debug('$appRootPath: "' . $appRootPath . '"');
+		\OC::$server->getLogger()->debug('$serverRoot: "' . $this->serverRoot . '"');
+		\OC::$server->getLogger()->debug('$appPath: "' . $appPath . '"');
 
 		if (!$appPath) {
 			return new NotFoundResponse();
 		}
 		$path = $this->serverRoot . $appPath ."/img/$fileName.svg";
+		\OC::$server->getLogger()->debug('$path: "' . $path . '"');
 		return $this->getSvg($path, $color, $fileName);
 	}
 

```

**Comment by janix82** [comment] 2019-12-30 10:31
> A note as a user: While fixing the actual problem is obviously more important, those ResourceLocator errors are extremely annoying and have made our logs entirely unreadable. Nearly every app installed produces at least one of those errors every time a page is accessed.

It was my soluition to get rid of this logs, after this my log is readable. You can make a cronjob to clear the nextcloud.log file.

Example: 
#Nextcloud log cleaner (in every hour)
30 *  *   *   * grep -v "webRoot: " /var/snap/nextcloud/common/nextcloud/data/nextcloud.log > /var/snap/nextcloud/common/nextcloud/data/nextcloud2.log; mv /var/snap/nextcloud/common/nextcloud/data/nextcloud2.log /var/snap/nextcloud/common/nextcloud/data/nextcloud.log

**Comment by kyrofa** [comment] 2020-01-14 03:59
> I took a crack at applying the changes [here](https://github.com/kyrofa/server/tree/bugfix/13556/cannot_find_webroot) (just the ones given here, not the gist), but at least at first blush it doesn't appear to work. I need to test some more.

I'm loathe to admit that I apparently didn't fully understand this issue and how it impacted the text app. I missed two key points:

1. The toolbar only shows up for .md files. For .txt files it doesn't, by design
2. The toolbar only fails to show up when editing .md files in dark mode

@the-sane finally hammered those two points home, and I realize now that these patches DO work @kesselb. Ship them!

**Comment by wiswedel** [comment] 2020-02-04 08:18
this is still happening in 18.0.0

**Comment by acs-ferreira** [comment] 2020-03-14 10:15
@wiswedel 18.0.2 and 17.0.4. So latest versions at this time are shipped with this bug.

**Comment by MorrisJobke** [comment] 2020-04-27 08:59
#19084 is merged

**Comment by ddoherty03** [comment] 2020-05-06 22:07
@kyrofa I have noticed that syncing my calendar with Emacs org-mode has stopped working.  I suspect this issue.  I'm using org-caldav, which has worked nicely for a long time, but lately am getting this:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name /calendars could not be located</s:message>
</d:error>
```
Using nextcloud snap on ubuntu 18.04:

```
# snap list
Name       Version      Rev    Tracking       Publisher   Notes
core       16-2.44.3    9066   latest/stable  canonical✓  core
nextcloud  18.0.4snap1  20498  latest/stable  nextcloud✓  -
```

Will this fix be coming soon to the snap?  Or is it already in, and I have a different problem?

Thanks for your work on this, BTW.  The snap is a hugely convenient way to get a nextcloud server up and running.

**Comment by kyrofa** [comment] 2020-05-06 22:15
@ddoherty03 looks like #19084 won't be backported to v18, so it's not in the snap you have installed. However, I'd be a bit surprised if that was your issue. This has been a problem for a long time, so if something suddenly stopped working I suspect you have unrelated issues.

**Comment by ddoherty03** [comment] 2020-05-07 15:25
Ok.  Thanks, @kyrofa .

**Comment by nickvergessen** [comment] 2020-09-02 15:15
can people please try if https://github.com/nextcloud/server/pull/22550/files solves the issue for them?

**Comment by Daryes** [comment] 2020-09-02 18:56
Just applied, seems good at first glance, no more log warnings, and no problem in the UI,
I'll check more later.

BTW, as I'm not using snap for Nexcloud, I can't speak for it.

**Closed** 2020-09-04 06:58 UTC
Labels: 1. to develop, bug

**Comment by Magicrafter13** [comment] 2021-05-25 22:36
This appears to still be an issue, or at least something related?
Taken from my `nextcloud.log`:
```
"Message": "`../../../core/css/whatsnew.scss` file not found for @import: /mnt/nc-data/apps/files/css/merged.scss on line 5, at column 1\nCall Stack:\n#0 import /mnt/nc-data/apps/files/css/merged.scss (unknown file) on line 1",
```
As you can see, I have my apps directory stored in `/mnt/nc-data` which is a separate partition from `/`. The web files however, are located in `/var/www/nextcloud`.
My "solution" to this problem was to symlink core on the data partition: `ln -s /var/www/nextcloud/core/ /mnt/nc-data/`, which seems to work fine, but is only a workaround.

Nextcloud 21.0.2 on Fedora 34 if it matters.
