### ISSUE TITLE
9.1.4.11/4.3 Media files marked as selected - The checkboxes do not meet the contrast requirements for graphical informative elements depending on the background, as the contrast ratio with the background is below 3:1. It is recommended to place these elements outside of images. The issue also affects unselected checkboxes (see screenshot).

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42218] opened 2023-12-13 13:47 UTC
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-3dbfb7615a-v4-n3

9.1.4.11/4.3 Media files marked as selected - The checkboxes do not meet the contrast requirements for graphical informative elements depending on the background, as the contrast ratio with the background is below 3:1. It is recommended to place these elements outside of images. The issue also affects unselected checkboxes (see screenshot).

![image](https://github.com/nextcloud/server/assets/42591237/1d357afc-7d65-4899-9752-acb7a8e551c6)
![image](https://github.com/nextcloud/server/assets/42591237/22c430fa-dee3-4a78-b571-f27e50be2308)

**Comment by JuliaKirschenheuter** [comment] 2023-12-14 10:20
duplicate of https://github.com/nextcloud/photos/issues/2160

**Closed by JuliaKirschenheuter** 2023-12-14 10:20 UTC
Labels: accessibility
