### ISSUE TITLE
[Bug]: Updating <dav> ... very slow with a lot of users

### ISSUE THREAD

**Issue by kaystrobach** [nextcloud/server#39769] opened 2023-08-09 07:35 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The <dav> Update step takes forever

the step is massively frustrating, as the logs do not display which entries are modified:

```{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:30:08+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
```

### Steps to reproduce

1. install NC Enterprise 26.0.4
2. update to NC Enterprise 27.0.1

### Expected behavior

Fast Update or background process

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "objectstore_multibucket": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "num_buckets": 1,
                "bucket": "nc-test-",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "obs.eu-de.otc.t-systems.com",
                "use_ssl": true,
                "region": "eu-de"
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***",
            "***",
            "***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "data\/skeleton\/",
        "dbtype": "mysql",
        "version": "26.0.4.3",
        "overwrite.cli.url": "https:\/\/wolke.schullogin.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "default_locale": "de_DE",
        "default_language": "de",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "theme": "",
        "loglevel": 0,
        "maintenance": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/customers\.../",
        "app_install_overwrite": [
            "circles",
            "documentserver_community"
        ],
        "updater.release.channel": "enterprise",
        "default_phone_region": "DE",
        "sentry.dsn": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files"
    }
}
```

### List of activated Apps

```shell
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.16.0
  - announcementcenter: 6.6.1
  - bruteforcesettings: 2.6.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.16.0
  - contacts: 5.3.2
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_antivirus: 5.2.1
  - files_pdfviewer: 2.7.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.8.1
  - notifications: 2.14.0
  - oauth2: 1.15.1
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - quota_warning: 1.17.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_saml: 5.2.1
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - approval: 1.1.0 (installed 1.1.0)
  - bbb: 2.5.0 (installed 2.5.0)
  - encryption: 2.15.0
  - external: 5.1.0 (installed 5.1.0)
  - files_accesscontrol: 1.16.0 (installed 1.16.0)
  - files_confidential: 1.0.3
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.19.0
  - files_lock: 27.0.0 (installed 27.0.0)
  - files_rightclick: 1.6.0 (installed 1.3.0)
  - globalsiteselector: 2.4.3
  - impersonate: 1.13.1 (installed 1.13.1)
  - onlyoffice: 7.8.0 (installed 7.8.0)
  - password_policy: 1.17.0 (installed 1.15.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
not possible due to maintenance mode
```

### Nextcloud Logs

```shell
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:12+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:13+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:13+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:13+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Activity generated for a changed card in addressbook 3","userAgent":"--","version":"26.0.4.3","data":{"app":"dav"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:14+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
{"reqId":"CvpSmDdyZsVDkPMhVqWb","level":0,"time":"2023-08-09T07:34:14+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Automatic conversion of false to array is deprecated at /export/htdocs/nextcloud/lib/private/Files/Stream/SeekableHttpStream.php#222","userAgent":"--","version":"26.0.4.3","data":{"app":"PHP"}}
```
```


### Additional info

Maybe related to 

* https://github.com/nextcloud/server/issues/39744

**Comment by ChristophWurst** [comment] 2023-08-09 09:32
Duplicate of https://github.com/nextcloud/server/issues/39744

Thanks for the report

**Comment by kaystrobach** [comment] 2023-08-09 09:59
No, we don’t use ldap here

**Comment by ChristophWurst** [comment] 2023-08-09 10:06
It is the same problem nevertheless

**Comment by kaystrobach** [comment] 2023-08-09 10:15
Maybe the source of the problem is the same, but the prerequisites are not similar.

**Comment by kaystrobach** [comment] 2023-08-09 10:16
if it's the same problem, maybe a relation is enough.

**Comment by miaulalala** [comment] 2023-08-16 13:20
Do you please have a user guesstimate for me @kaystrobach ? Just so we can adjust the workflow accordingly as described here https://github.com/nextcloud/server/issues/39744#issuecomment-1669288327

Don't want to do too little if it's not neccessary, but also don't want to be overconfident in my numbers.

**Closed** 2023-08-27 13:54 UTC
Labels: bug, 0. Needs triage, feature: install and update, performance 🚀, feature: carddav, 27-feedback

**Comment by hafiz-personal** [comment] 2024-07-20 16:53
I'm currently stuck at this issue while upgrading from version 26 to 27. Can I safely exit the update? what are the steps to safely solve it?

**Comment by kaystrobach** [comment] 2024-07-20 17:07
No, use tail to see progress in the logfiles in a second shell
