### ISSUE TITLE
Row height in user management doesn't fit

### ISSUE THREAD

**Issue by Jan-NiklasB** [nextcloud/server#19774] opened 2020-03-04 10:09 UTC
### Steps to reproduce
1. Install NC 18.0.1
2. Create an User with many Groups with longer names
3. Take a look at the user management and search for the created user

![Screenshot_2020-03-04 Benutzer - Cloud](https://user-images.githubusercontent.com/44967908/75868484-61b19a00-5e08-11ea-93c3-8b24695dca64.png)

### Expected behaviour
The height of the User-row should fit to the needed height to get all Groups shown in the row

### Actual behaviour
The height of the row doesn't respond to the amount / length / heigth of the ass

### Server configuration

**Operating system:** Debian Linux 10    Kernel: Linux 4.19.0-8-amd64 on x86_64

**Web server:** Apache 2.4.38 on Webmin

**Database:** MySQL 10.3.22

**PHP version:** 7.3.15

**Nextcloud version:** 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 17 on 03.03.2020

**Where did you install Nextcloud from:** zip file from nextcloud page

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
- accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.0
  - files_downloadactivity: 1.7.0
  - files_mindmap: 0.0.17
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trackdownloads: 1.7.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - flowupload: 0.1.8
  - groupfolders: 6.0.1
  - guests: 1.4.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.3
  - metadata: 0.11.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.5
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_email: 1.0.1
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - w2g2: 3.0.1
  - workflowengine: 2.0.0
Disabled:
  - cospend
  - encryption
  - files_antivirus
  - files_external
  - previewgenerator
  - printer
  - ransomware_detection
  - twofactor_gateway
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "192.168.13.162",
            "***Web-domain removed***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "overwrite.cli.url": "http:\/\/127.0.0.1\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "de",
        "default_locale": "de_DE",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "AkEzHK"
        ],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** -

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav/Nextcloud-App/CalDAV

### Client configuration
**Browser:** Firefox (bug persists on multiple versions)

**Operating system:** Linux Mint 19

**Comment by kesselb** [comment] 2020-03-04 10:18
Thanks 👍

Duplicate of https://github.com/nextcloud/server/issues/18920

Please use the search before submitting a new issue 🔎

**Closed** 2020-03-04 10:18 UTC
Labels: 0. Needs triage, 18-feedback, bug, feature: users and groups
