### ISSUE TITLE
Cannot configure caldav and carddav and fatal error

### ISSUE THREAD

**Issue by rmarzocchi84** [nextcloud/server#18922] opened 2020-01-16 09:00 UTC
In my admin page I read the 
```
Your web server is not properly set up to resolve “/.well-known/caldav”.
Your web server is not properly set up to resolve “/.well-known/carddav”.
```

I try to follow the user guide but I do not understand what is wrong.

- Ubuntu server 18.04
- Nextcloud 16.0.7
- apache 2.4 with the following configuration in the 000-default.conf file
```
Alias /nextcloud "/var/www/html/nextcloud/"

<Directory /var/www/html/nextcloud/>
   #Options Indexes FollowSymLinks MultiViews
  Options +FollowSymlinks
  AllowOverride All
  SSLRequireSSL
  #Require all granted
<IfModule mod_dav.c>
  Dav off
</IfModule>
 SetEnv HOME /var/www/html/nextcloud
 SetEnv HTTP_HOME /var/www/html/nextcloud
</Directory>
```

I try to put the .htaccess file in the root directory /var/www/html and I have also it in the /var/www/html/nextcloud directory

In the log this is my fatal error syncing a file in a nexctloud folder:

```
[webdav] Fatal: OCP\Lock\LockedException: "WebGIS_provinciaLatina/WebGIS.qgs.jpg" is locked at <<closure>>

 0. /var/www/html/nextcloud/lib/private/Files/View.php line 790
    OC\Files\View->changeLock("/WebGIS_provinciaLatina/WebGIS.qgs.jpg", 2, true)
 1. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Node.php line 141
    OC\Files\View->rename("/WebGIS_provinciaLatina/WebGIS.qgs.jpg", "/WebGIS_provinciaLatina/_WebGIS.qgs.jpg")
 2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 151
    OCA\DAV\Connector\Sabre\Node->setName("_WebGIS.qgs.jpg")
 3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("files/provincia ... g", "files/provincia ... g")
 4. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 5. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
 6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
 7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 8. /var/www/html/nextcloud/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
 9. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
10. /var/www/html/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/html/n ... p")

MOVE /nextcloud/remote.php/dav/files/provincialatina/WebGIS_provinciaLatina/WebGIS.qgs.jpg
from 151.31.91.113 by provincialatina at 2020-01-15T16:26:25+00:00
```

**Comment by kesselb** [comment] 2020-01-17 08:51
https://github.com/nextcloud/server/issues/11787#issuecomment-429239543
https://github.com/nextcloud/server/issues/11850#issuecomment-569310169

**Comment by rmarzocchi84** [comment] 2020-01-17 08:59
I already read the https://docs.nextcloud.com/server/16/admin_manual/issues/general_troubleshooting.html#service-discovery documentation, but IMHO it is not clear where place the .htaccess file. In the apache root directory or in the subfolder? 

Moreover I do not understand the fatal error. I do not know if it depends to the misconfiguration.

**Comment by kesselb** [comment] 2020-01-17 09:25
>  IMHO it is not clear where place the .htaccess file. In the apache root directory or in the subfolder?

It depends on your setup. Please check the comments. CalDAV and CardDAV will work even without the redirects. I don't think it's related to the fatal error.

**Comment by rmarzocchi84** [comment] 2020-01-22 23:06
Concerning the fatal error I do not understand how to solve it

**Comment by rmarzocchi84** [comment] 2020-01-29 07:20
> Concerning the fatal error I do not understand how to solve it

And file locked is frequents in my nextcloud instance

**Comment by kesselb** [comment] 2020-06-18 21:51
Closing as configuration issue / duplicate of other reports.

**Closed by kesselb** 2020-06-18 21:51 UTC
