### ISSUE TITLE
Sorting feature for users

### ISSUE THREAD

**Issue by ashcoft** [nextcloud/server#36695] opened 2023-02-14 05:18 UTC
![image](https://user-images.githubusercontent.com/1115854/218645936-c802b78c-7b5b-4893-94e7-a2ac946b3fd6.png)
 There is no sorting for users.

**Comment by joshtrichards** [comment] 2024-05-21 18:45
Duplicate of #3230

**Closed by joshtrichards** 2024-05-21 18:45 UTC
Labels: enhancement, 0. Needs triage, feature: users and groups
