### ISSUE TITLE
[Bug]: UI: Can't activate disabled users on mobile browsers

### ISSUE THREAD

**Issue by tzugen** [nextcloud/server#34753] opened 2022-10-23 16:42 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On both Firefox as well as Chromium in Android, I find it is impossible to activate a deactivated user.

### Steps to reproduce

 1. tap the dropdown menu icon
 2. the dropdown menu opens
 3. tap "Enable user"
 4. the dropdown menu closes

### Expected behavior

Instead it should enable the user

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Irrelevant
```

**Comment by szaimen** [comment] 2022-10-23 18:29
Which NC version?

**Comment by tzugen** [comment] 2022-10-23 20:06
The latest, 25.0.0. No idea if it worked before.

**Comment by VasilisThePikachu** [comment] 2022-10-30 15:01
Not sure if me and reporter have the same issue, but in the users menu, mobile browser seem to be unable to edit anything as the drop-down instantly disappears, mobile browsers also can't access all the user detail fields. If we have the same issue i can send a video for reproduction

**Comment by tzugen** [comment] 2022-10-30 19:41
Sounds very much the same

**Comment by rulzAT** [comment] 2023-04-06 15:05
> The latest, 25.0.0. No idea if it worked before.

It is still broken in Version 22 and following.

**Comment by rulzAT** [comment] 2023-04-07 09:02
This Popover Menu must be focus trapped like all other Menus

**Comment by joshtrichards** [comment] 2023-08-29 20:39
Duplicate of #21260
Consolidating tracking there.
Subscribe to that issue and/or give it a :+1: up if impacted.

**Closed by joshtrichards** 2023-08-29 20:39 UTC
Labels: bug, design, 0. Needs triage, feature: users and groups, 25-feedback
