### ISSUE TITLE
Activity Notifications for 'Favorite' folders is not recursive

### ISSUE THREAD

**Issue by scylla999** [nextcloud/server#27547] opened 2021-06-17 19:50 UTC
Hello,

We are running version 20.0.10, CentOS 8 Stream since last Friday and our activities/notification system seems to not work as before the update.

With this configuration, notifications are not sent for changes in the contents of a Favorite folder:

![Nextcloud_Parametres_Activites_Favoris](https://user-images.githubusercontent.com/24919069/122463275-6c535c80-cf83-11eb-9ea4-a4147f8be971.jpg)

To get notifications to work properly again, we have to select all other boxes:

![Nextcloud_Parametres_Activites_Recursif](https://user-images.githubusercontent.com/24919069/122463493-a9b7ea00-cf83-11eb-87e2-d6d9683cb996.jpg)

Thank You!

**Comment by scylla999** [comment] 2021-06-22 17:13
I upgraded to version 21.0.2.    This issue is still not resolved.

**Comment by szaimen** [comment] 2021-08-08 12:28
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

**Comment by scylla999** [comment] 2021-09-07 14:16
I will schedule an update this week and give you an update on this issue.

**Comment by scylla999** [comment] 2021-09-08 18:32
Ok, just checked.   This bug is still there with 21.0.4

**Comment by szaimen** [comment] 2021-09-15 12:58
cc @nickvergessen does this need fixing here or in the activity app?

**Comment by nickvergessen** [comment] 2021-09-15 15:06
https://github.com/nextcloud/server/blob/1162dcd1bccb4dbd2f9ac40692d62c70616a18d8/apps/files/lib/Activity/Helper.php#L49

**Comment by szaimen** [comment] 2021-09-15 15:09
@scylla999 do you think you might be able to create a PR with a fix from the feedback that you've got from nickvergessen? :)

**Comment by nickvergessen** [comment] 2021-09-15 15:14
The thing is it's already recursive as you can see in the second diff. If your favorite is a folder, we select all files where the path starts with `FAVORITE/%`

**Comment by nickvergessen** [comment] 2021-09-15 15:22
Ah, I didn't read it is about push.

I'm a bit confused. I'm pretty sure emails never worked for favorites and it was locked to not allow to enable it.
The same should be true for push. The problem is we would need to mount the filesystem of all users on the fly to see if we need to push for them, but that does not scale.

**Comment by nickvergessen** [comment] 2021-09-15 15:24
So it's broken since: https://github.com/nextcloud/server/commit/5f58cefbd7898ebc07da7a80b75c98e4350d0cb5 which combined some settings. As you can see in the red ` apps/files/lib/Activity/Settings/FileFavorite.php ` file emails were off and it is not possible to change it.

**Comment by szaimen** [comment] 2021-09-15 15:24
So then the best way would be locking those options again if they are not feasible performance wise? What do you think?

**Comment by szaimen** [comment] 2021-09-15 15:26
> So it's broken since: [5f58cef](https://github.com/nextcloud/server/commit/5f58cefbd7898ebc07da7a80b75c98e4350d0cb5) which combined some settings. As you can see in the red `apps/files/lib/Activity/Settings/FileFavorite.php` file emails were off and it is not possible to change it.

Okay, what would be the best way to solve this then?

**Comment by nickvergessen** [comment] 2021-09-15 15:28
https://github.com/nextcloud/server/pull/28853 `¯\_(ツ)_/¯`

**Comment by szaimen** [comment] 2021-09-15 15:31
> #28853 `¯\_(ツ)_/¯`

Great, will review it asap :)

**Closed** 2021-09-27 06:16 UTC
Labels: bug, 2. developing, feature: activity and notification

**Comment by burner-** [comment] 2023-04-14 12:21
So instead of fixing that issue you just remove whole feature? Thats quite sad way to resolve things.

**Comment by nickvergessen** [comment] 2023-04-14 12:48
> Thats quite sad way to resolve things.

That's not how we "resolve things" in general.
It is however the only scaling option this time around.
