### ISSUE TITLE
Quota external storage ignored in calculation with config rule 'quota_include_external_storage' => true, set in config.php

### ISSUE THREAD

**Issue by DevGoslinga** [nextcloud/server#3304] opened 2017-01-28 10:03 UTC
I have added SMB storage using External storage support 1.1.2 .
This should be the size if including external storage space:
You are using 215.6 MB of 5 GB

However, the personal page is displaying the following:
You are using 6.7 MB of 5 GB

In late 2016 changes have been made to the code concerning quota.

Ubuntu 16.04 
Apache 2
MariaDB
PHP 7.0
11.0.1.2

fresh installation

Visiting the link: 
/nextcloud/index.php/settings/integrity/failed

Gives me the following output: 
No errors have been found.

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_saml

{
    "system": {
        "instanceid": "ocla102rvrwz",
        "passwordsalt": "",
        "secret": "",
        "trusted_domains": [
            "removed",
            "removed"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/removed\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "",
        "dbpassword": "",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "quota_include_external_storage": true,
    }
}

**Comment by nickvergessen** [comment] 2017-01-30 11:42
@icewind1991 does `quota_include_external_storage` not work anymore? Then we should remove it from the docs.

**Comment by MorrisJobke** [comment] 2017-05-11 16:30
Fix is in #4357

**Comment by MorrisJobke** [comment] 2017-05-11 16:37
Duplicate of #4348

**Closed by MorrisJobke** 2017-05-11 16:37 UTC
Labels: bug, feature: filesystem
