### ISSUE TITLE
[Flow] "match" operator for file name check only accessible with a trick

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#19050] opened 2020-01-21 13:44 UTC
When defining criteria for a flow check on file name, the drop down only offers _is_ and _is not_. 
However when starting to enter a regex in the right field, the operator automatically switches to _matches_ - and then _matches not_ is also pickable (but not _is_ and _is not_ any more).

Request user agent by the way shows all four operators just fine.

![peek_flow](https://user-images.githubusercontent.com/1804221/72809659-56d9e600-3c5c-11ea-8579-5f8efdee7371.gif)

cc @blizzz

**Comment by szaimen** [comment] 2021-06-09 13:16
As I cannot reproduce the original issue anymore, I will close this ticket. 
Actually, I am not able to do so because I don't find the option `When File is accessed`
I only see `When File created` but for that all four operators get shown.

**Closed by szaimen** 2021-06-09 13:16 UTC
Labels: 0. Needs triage, bug, feature: workflows
