### ISSUE TITLE
Request thumbnail function of animated webp file

### ISSUE THREAD

**Issue by YTOAA** [nextcloud/server#37263] opened 2023-03-16 09:04 UTC
A typical single image webp file displays a normal thumbnail. However, the thumbnail display is not suitable for the animated webp file. The gif file is a moving file, but the first frame is displayed as a thumbnail.
When accessing the animation webp, the thumbnail is not displayed because of the error " PHP Fatal error: gd-webp cannot allocate temporary buffer in /var/www/html/lib/private/legacy/OC_Image.php on line 722 . "

**Comment by joshtrichards** [comment] 2023-05-05 12:55
This is an upstream matter:

https://github.com/libgd/libgd/issues/648
https://bugs.php.net/bug.php?id=79809
https://www.php.net/manual/en/function.imagecreatefromwebp.php

We could, perhaps, detect if it is an animated webp beforehand, but the end result in terms of user experience would be the same (no thumbnail).

If you think there's a reasonable spot for documenting this current situation in the official NC documentation, feel to post a suggestion (or even better a PR) over at https://github.com/nextcloud/documentation

Nothing to do here otherwise. When (or if) support is added upstream it'll probably start to "just work". :)

**Comment by joshtrichards** [comment] 2023-05-18 14:14
Duplicate of #30029. Suggest we close and consolidate tracking there.

**Comment by joshtrichards** [comment] 2023-09-04 14:11
Duplicate of #30029.

Please subscribe to #30029 if you wish to track progress.

**Closed by joshtrichards** 2023-09-04 14:11 UTC
Labels: enhancement, 0. Needs triage, feature: previews and thumbnails
