### ISSUE TITLE
copymove can not overwrite existing files

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/server#8908] opened 2018-03-21 08:17 UTC
### Steps to reproduce
1. have files with same name in 2 different folders
2. want to update the same file in the 2nd folder
3. see message: can't copy, target already exists

### Expected behaviour
display a dialogbox as in files_clipboard what to do (overwrite or not)

### Actual behaviour
aborted the copy process because the file exists.
![grafik](https://user-images.githubusercontent.com/13016719/37699639-bd46c3b6-2ce8-11e8-8d24-99f32a7373d5.png)

### Server configuration

**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mariadb 10

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** webupdater

**Comment by fhoefling** [comment] 2018-06-11 10:34
Same issue here. When uploading directly into a folder, there is a "conflict resolution" dialogue. I suggest that the same mechanism kicks in here.

**Comment by rabner** [comment] 2018-06-19 07:59
The same issue here, but in addition I've noticed that when coping/moving folder with files operation stops when destination folder is found, so files in that folder are not transferred over.

Server configuration
Operating system: ubuntu 16.04
Web server: apache 2.4
Database: mariadb 10
PHP version: 7.2
Nextcloud version: 13.0.4

**Comment by MorrisJobke** [comment] 2018-06-28 08:17
Very likely a duplicate of #1218 - let's continue over there.

**Closed by MorrisJobke** 2018-06-28 08:17 UTC
