### ISSUE TITLE
Nextcloud crash when dir is named with '%'

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#11900] opened 2018-10-18 11:52 UTC
### Expected behaviour

I created a dir named only by percent character (%)
### Actual behaviour
The explorer show no data and loader.gif is showned for ever.

### Server configuration

**Operating system**: Centos 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 14

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

Error:
![Transmission](https://i.imgur.com/CZCJMFG.png)

**EDIT:**
I add this line of code ( in core/js/files/client.js), it doesn't broke anymore the explorer but still can't see dir with '%' name in it :

`path = path.replace('%','');`

just before :

`path = decodeURIComponent(path);`

**Comment by MorrisJobke** [comment] 2018-10-18 12:06
Duplicate of #11695

**Comment by MorrisJobke** [comment] 2018-10-18 12:06
Fixed in #11744 and will be shipped in 14.0.4

**Closed by MorrisJobke** 2018-10-18 12:06 UTC
Labels: bug

**Comment by vipera7** [comment] 2018-10-18 12:08
Thanks, it's fixed !
