### ISSUE TITLE
Very first login is very slow, aka just how many database queries do we need?

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#12234] opened 2018-11-02 23:53 UTC
I've long wondered why logging into a new Nextcloud installation takes such a long time on the first time. (the slow "out-of-the-box experience".) Thanks to the mariadb query log, I know now and I would like to share. Here is what I did:

1. Brand-new Nextcloud installation (on [UBOS](https://ubos.net/) but this is hardly an OS-dependent issue)
1. No non-default apps installed. Admin user provisioned, and some config defaults changed from the command-line. (Here is the [script](https://github.com/uboslinux/ubos-nextcloud/blob/master/nextcloud/bin/install.pl) if you are so inclined; I guess if it's apparent what we do even if you don't know Perl or UBOS)
1. Now I do I two things with a browser:
    * Access the front page
    * Log in with the provisioned account
1. At the time the splash screen comes up, and the default set of files is displayed, I stop.

My query log reports (with the help of grep and sed):
* 72 distinct database "Connect" events
* 4493 database queries, which break down something like this:
    * 134: INSERT 
    * 1092: UPDATE 
    * 3063: SELECT 
    * 4: DELETE
    * 28: COMMIT
    * 144 SET SESSION
    *  28 START TRANSACTION

Note that at this time, none of the caches are warm yet. So my question: does the number of queries really have to be in the thousands before the first user is logged on?

To reproduce: get a database shell, then:
```
set global general_log_file = '/tmp/mysql.log';
set global general_log = 'ON';
```
Note that if you run `mariadb` through `systemd`, the actual location of the log file might be in a subdirectory. Try `find /tmp -name mysql.log` to find it.

**Comment by sherkhanz** [comment] 2019-01-09 07:40
Facing somewhat same issue but haven't debugged the issue yet. When a new user logins for the first time to NC, they don't get a response back though the user get logged in and opening the instance in a new windows loads the default files app. 

Any suggestions for a workaround?

Thanks

**Comment by bs-eng** [comment] 2019-03-05 17:45
Facing the same issue here.
I use OMV on odroid XU4 and installed nextcloud in docker container.
The first login to nextcloud takes so long that the http server runs into time out.
After a while the nextcloud website defaults to the normal login page.
From here different behaviours can be observed (I installed fresh out of the box 6 times by now):

BEHAVIOUR 1: The initial page that ask for creating the nextcloud admin loads, I enter the settings. Then the http server time out appears after quite some time. Coming back to the same page after approx 5min gets me directly to the welcome page in the admin account, without asking login data again. From there everything click takes so long that http server timeout appears. After reloading the page at least 2 minutes later gets me to where I wanted to go.

BEHAVIOUR 2: The initial page that ask for creating the nextcloud admin loads, I enter the settings. Then the http server times out. Reloading the page gets me to the login page. Entering the admin credentials leads to returning to the login page. Effectively I never get logged in.

Interesting is that those two behaviours appear after installation in the exact same way. Parameters and order of steps are the same. Boot device was completly wiped and new partitioned before new install. Software versions seem not to have change during these days of reinstalling.

I hope this helps to investigate further.
Contact me if mor einfo is needed.

Cheers!


Odroid XU4
Kernel Linux 4.14.94-odroidxu4 (Debian)
OMV 4.1.19-1 Arrakis
Docker 18.09.3
Nextcloud latest .... so I guess as fo 2019-03-05

**Comment by creopard** [comment] 2019-05-20 12:28
Here is a similar issue: https://github.com/nextcloud/server/issues/14632

**Comment by skjnldsv** [comment] 2019-06-17 09:42
@creopard thanks :)
Duplicate of #14632

**Closed by skjnldsv** 2019-06-17 09:42 UTC
Labels: enhancement
