### ISSUE TITLE
Improve ErrorDocument config in .htaccess

### ISSUE THREAD

**Issue by astehlik** [nextcloud/server#33048] opened 2022-06-28 13:02 UTC
The current ErrorDocument configuration that is written to the .htaccess causes problems in some environments:

```
ErrorDocument 403 /
ErrorDocument 404 /
```

When the Apache Webserver is configured with [`ProxyErrorOverride`](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyerroroverride) the HTTP error handling for 403 and 404 errors is broken. Users no longer get the correct error codes and error messages. Instead they are redirected to the dashboard.

When you are running Nextcloud on your own server the solution is simple: do not use `ProxyErrorOverride On`. But there are also hosters that use this setting and provide no possibility to disable it.

In most cases this is probably only a minor issue / nitpick but there is (at least) one concrete case where this leads to real problems: the contact images. The contacts apps makes a request for each contact visible in the list:

```
/remote.php/dav/addressbooks/users/<user>/<Addressbook>/<contact-uid>.vcf?photo=
```

When the user is now redirected to the dashboard for each requests where no image is found instead of just getting a 404 error the server can get overloaded.

## Possible solutions

Here are some suggestions to solve the issue:

### Remove ErrorDocument directives

I'm not sure what the rationale behind the current  `ErrorDocument` directives is. From my point of view they could just be removed without loosing anything.

### Add config options to customize ErrorDocument directives

If removing the the directives is not possible, allowing the configuration of custom error documents would be a good alternative, e.g in:

```
occ config:system:set htaccess.ErrorDocument.403 "/my/custom/error/403.php"
occ config:system:set htaccess.ErrorDocument.404 "/my/custom/error/404.php"
```

### Bring back error actions

There are templates left over at `/core/templates/403.php` and `/core/templates/404.php`. These templates could be made available again in controller actions that output the correct HTTP-Headers. Those actions could the be uses in the .htaccess file, e.g.

```
ErrorDocument 403 /index.php/errors/403
ErrorDocument 404 /index.php/errors/404
```

I would be happy to help out with a pull request.

**Comment by CarlSchwan** [comment] 2022-06-29 15:01
> Remove ErrorDocument directives

Sounds like the best solution and we should provide a nice 404 page instead of just redirecting to the homepage, this is pretty standard behavior for websites and I'm always a bit annoyed when Nextcloud redirects me to the homepage instead of telling me that I wrote the wrong URL/ I don't have access to the resource

What do you think @nextcloud/designers ?

**Comment by nimishavijay** [comment] 2022-06-29 17:06
Agreed that redirecting to dashboard makes no sense if the entered URL is wrong :)

**Comment by eppfel** [comment] 2022-07-20 14:54
I can confirm that my issue #33228 is another use case of this and from my understanding. Commenting out the two ErrorDocument lines fixes the problem.

I think this is non-standard behaviour for the DAV module because nextcloud returns the wrong error code in my case. So, I leave my issue open for now, as it is clearly a bug.

**Comment by MoritzGiessmann** [comment] 2023-07-27 21:01
This keeps happening every time I update nextcloud. Is it planned to fix this?

**Comment by juliushaertl** [comment] 2023-07-31 18:30
Has been addressed in https://github.com/nextcloud/server/pull/34662

**Closed by juliushaertl** 2023-07-31 18:30 UTC
Labels: enhancement, 0. Needs triage
