### ISSUE TITLE
occ files:scan does not index files with illegal names and does not warn about it

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/server#25825] opened 2021-02-27 15:51 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a file with a `\` in its name (this is legal on at least Ext4 and ZFS). Alternatively, create a file with `.part` extension.
2. Add to data folder
3. `occ files:scan`

### Expected behaviour

The file is added to the filecache and can be accessed via the interface.

### Actual behaviour

The file is not added to the filecache and `occ` does not output an error. 
*This can also lead to **data loss** - the user may delete the file's parent folder without knowing of the file.*
### Server configuration

**Operating system:** Ubuntu 20.04.2

**Web server:** Apache 2.4.41-4ubuntu3.1

**Database:** MariaDB 1:10.3.25-0ubuntu0.20.04.1

**PHP version:** 7.4.3-4ubuntu2.4

**Nextcloud version:** 20.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** Continuously updated since NC 13 (I think)

**Where did you install Nextcloud from:** tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - announcementcenter: 4.0.1
  - apporder: 0.11.0
  - audioplayer: 3.1.0
  - audioplayer_editor: 0.3.0
  - bookmarks: 4.1.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - camerarawpreviews: 0.7.10
  - checksum: 1.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - data_request: 1.7.0
  - dav: 1.16.2
  - drawio: 0.9.8
  - dropit: 0.4.0
  - event_update_notification: 1.2.0
  - external: 3.7.2
  - extract: 1.3.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_linkeditor: 1.1.3
  - files_markdown: 2.3.2
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_texteditor: 2.10.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - firstrunwizard: 2.9.0
  - flowupload: 1.1.2
  - gpxmotion: 0.1.0
  - groupfolders: 8.2.0
  - guests: 1.6.2
  - integration_mastodon: 0.0.13
  - issuetemplate: 0.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - metadata: 0.12.0
  - news: 15.3.2
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - ocdownloader: 1.7.10
  - password_policy: 1.10.1
  - phonetrack: 0.6.7
  - photos: 1.2.3
  - previewgenerator: 3.1.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - qownnotesapi: 20.9.0
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.15
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - side_menu: 1.22.2
  - socialsharing_email: 2.1.0
  - spreed: 10.1.2
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - telephoneprovider: 1.0.3
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_admin: 3.0.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.1.0
  - twofactor_totp: 5.0.0
  - twofactor_webauthn: 0.2.6
  - twofactor_yubikey: 0.4.1
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_script: 1.5.1
  - workflowengine: 2.2.0
Disabled:
  - cospend
  - encryption
  - files_videoplayer
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.teutsch.me",
            "ovp.gentile.cc",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.teutsch.me",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 1,
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "theme": "",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\BMP",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\PNG",
            "OC\\Preview\\TXT",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MSOffice2007"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "492f75b5a90a929e7bff3609193fb862",
        "app_install_overwrite": [
            "photosphereviewer",
            "twofactor_yubikey",
            "dropit",
            "files_texteditor",
            "telephoneprovider"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** samba

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** not relevant

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
not applicable
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

  Info    cli      Memcache \OC\Memcache\APCu not available for local cache         2021-02-27T15:39:40+00:00

  Info    cli      Memcache \OC\Memcache\APCu not available for distributed cache   2021-02-27T15:39:40+00:00

  Info    cli      Memcache \OC\Memcache\APCu not available for local cache         2021-02-27T15:41:41+00:00

  Info    cli      Memcache \OC\Memcache\APCu not available for distributed cache   2021-02-27T15:41:41+00:00

  Info    cli      Memcache \OC\Memcache\APCu not available for local cache         2021-02-27T15:41:43+00:00

  Info    cli      Memcache \OC\Memcache\APCu not available for distributed cache   2021-02-27T15:41:43+00:00

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
not applicable
```
</details>

**Comment by karottenbaum** [comment] 2021-03-19 20:09
This issue seems to apply to *all* illegal filenames. I just noticed that `*.part` files are not indexed either, and occ does not warn about them.

**Comment by szaimen** [comment] 2021-06-25 14:46
Duplicate of https://github.com/nextcloud/server/issues/7762

**Closed by szaimen** 2021-06-25 14:46 UTC
Labels: 0. Needs triage, bug
