### ISSUE TITLE
Theming - custom logo - lost password - logo not correct shown

### ISSUE THREAD

**Issue by herbetom** [nextcloud/server#8369] opened 2018-02-15 09:34 UTC
### Steps to reproduce
1. Go to Settings -> Theming
2. Upload a Logo (in my case a PNG, with transparent background)
3. Request a password reset and open the URL from the received mail

### Expected behaviour
the logo should be shown as normal

### Actual behaviour
logo is shown as following:
![bildschirmfoto 2018-02-15 um 10 14 54](https://user-images.githubusercontent.com/15121114/36248878-3da0bdb6-1239-11e8-8bcb-fa728bc96e39.png)

### Server configuration

**Operating system**:
Debian
**Web server:**
Apache
**Database:**
Mysql 10.1.26
**PHP version:**
7.0.27
**Nextcloud version:** (see Nextcloud admin page)
13.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - announcementcenter: 3.2.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - calendar
  - encryption
  - external
  - files_accesscontrol
  - socialsharing_email
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.org\/",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de_DE",
        "knowledgebaseenabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local, sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 64.0.3282.140

**Operating system:** Mac OS 10.13.3

#### Web server error log
<details>
<summary>Web server error log</summary>

```

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://cloud.example.org/core/vendor/purify.min.js.map
```
</details>

**Comment by MorrisJobke** [comment] 2018-02-15 09:39
Duplicate of #8035

**Comment by MorrisJobke** [comment] 2018-02-15 09:40
Will be fixed in 13.0.1 with #8286

**Closed by MorrisJobke** 2018-02-15 09:39 UTC

**Comment by herbetom** [comment] 2018-02-15 09:46
Thanks, I didn't found the issue because I haven't loocked for solved issues (only for currently open). 
Sorry for the duplicate

**Comment by MorrisJobke** [comment] 2018-02-15 11:08
Don't worry :)
