### ISSUE TITLE
class is deprecated since Symfony 4.2. at

### ISSUE THREAD

**Issue by ThorstenUm** [nextcloud/server#25987] opened 2021-03-07 16:30 UTC
Hey guys,

my nc is flooding log.

First my configuration System:
Nextcloud version : 21.0.0
Operating system and version : Debian 10.8
Webserver: Apache 2.4.38
PHP version : 8.0.3

Can anyone help me?

Error Log:
`{“reqId”:“xxxx”,“level”:3,“time”:“March 07, 2021 16:03:21”,“remoteAddr”:“xxxxxxx”,“user”:“xxxxxxx”,“app”:“PHP”,“method”:“GET”,“url”:"/index.php/settings/ajax/checksetup",“message”:{“Exception”:“Error”,“Message”:“The “Symfony\Component\Translation\PluralizationRules” class is deprecated since Symfony 4.2. at /var/www/html/nextcloud/3rdparty/symfony/translation/PluralizationRules.php#38”,“Code”:0,“Trace”:[{“function”:“onError”,“class”:“OC\Log\ErrorHandler”,“type”:"::"},{“file”:"/var/www/html/nextcloud/3rdparty/symfony/translation/PluralizationRules.php",“line”:38,“function”:“trigger_error”},{“file”:"/var/www/html/nextcloud/lib/private/L10N/L10N.php",“line”:226,“function”:“get”,“class”:“Symfony\Component\Translation\PluralizationRules”,“type”:"::"},{“file”:"/var/www/html/nextcloud/lib/private/L10N/L10NString.php",“line”:70,“function”:“OC\L10N\{closure}”,“class”:“OC\L10N\L10N”,“type”:"->",“args”:["*** sensitive parameters replaced ***"]},{“file”:"/var/www/html/nextcloud/lib/private/L10N/L10N.php",“line”:131,“function”:"__toString",“class”:“OC\L10N\L10NString”,“type”:"->"},{“file”:"/var/www/html/nextcloud/lib/private/L10N/LazyL10N.php",“line”:57,“function”:“n”,“class”:“OC\L10N\L10N”,“type”:"->"},{“file”:"/var/www/html/nextcloud/lib/private/DateTimeFormatter.php",“line”:257,“function”:“n”,“class”:“OC\L10N\LazyL10N”,“type”:"->"},{“file”:"/var/www/html/nextcloud/apps/settings/lib/Controller/CheckSetupController.php",“line”:534,“function”:“formatTimeSpan”,“class”:“OC\DateTimeFormatter”,“type”:"->"},{“file”:"/var/www/html/nextcloud/apps/settings/lib/Controller/CheckSetupController.php",“line”:732,“function”:“getLastCronInfo”,“class”:“OCA\Settings\Controller\CheckSetupController”,“type”:"->"},{“file”:"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",“line”:218,“function”:“check”,“class”:“OCA\Settings\Controller\CheckSetupController”,“type”:"->"},{“file”:"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",“line”:127,“function”:“executeController”,“class”:“OC\AppFramework\Http\Dispatcher”,“type”:"->"},{“file”:"/var/www/html/nextcloud/lib/private/AppFramework/App.php",“line”:157,“function”:“dispatch”,“class”:“OC\AppFramework\Http\Dispatcher”,“type”:"->"},{“file”:"/var/www/html/nextcloud/lib/private/Route/Router.php",“line”:302,“function”:“main”,“class”:“OC\AppFramework\App”,“type”:"::"},{“file”:"/var/www/html/nextcloud/lib/base.php",“line”:993,“function”:“match”,“class”:“OC\Route\Router”,“type”:"->"},{“file”:"/var/www/html/nextcloud/index.php",“line”:37,“function”:“handleRequest”,“class”:“OC”,“type”:"::"}],“File”:"/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php",“Line”:92,“CustomMessage”:"–"},“userAgent”:“Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0”,“version”:“21.0.0.18”}`

**Comment by acsfer** [comment] 2021-03-07 18:06
Duplicate of https://github.com/nextcloud/server/issues/25897

**Closed by acsfer** 2021-03-07 18:06 UTC
Labels: 0. Needs triage, bug
