### ISSUE TITLE
GuzzleHttp\Exception\RequestException: cURL error 18: transfer closed with 24712 bytes remaining to read

### ISSUE THREAD

**Issue by andreasjacobsen93** [nextcloud/server#5203] opened 2017-05-31 21:55 UTC
### Steps to reproduce
Setup a new install of NextCloud and saw the error in the log.

### Server configuration

**Operating system**: Ubuntu 17.04

**Web server:** Apache 2.4.25

**Database:** MySQL 5.7.18

**PHP version:** 7.0

**Nextcloud version:** 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Nextcloud configuration:**
**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/cloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/cloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/cloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/cloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/cloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/var/www/cloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('http //www.next...', Array)
/var/www/cloud/settings/Controller/CheckSetupController.php - line 125: OC\Http\Client\Client->get('http //www.next...')
/var/www/cloud/settings/Controller/CheckSetupController.php - line 108: OC\Settings\Controller\CheckSetupController->isSiteReachable('www.nextcloud.c...')
/var/www/cloud/settings/Controller/CheckSetupController.php - line 414: OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()
[internal function] OC\Settings\Controller\CheckSetupController->check()
/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\CheckSetupController), 'check')
/var/www/cloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\CheckSetupController), 'check')
/var/www/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'check', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/cloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/cloud/lib/base.php - line 1000: OC\Route\Router->match('/settings/ajax/...')
/var/www/cloud/index.php - line 40: OC handleRequest()
{main}
```
</details>

**Comment by patschi** [comment] 2017-06-01 07:26
Hi, like in #5204, please take some time providing more info by filling out the [issue template](https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md) when creating an new issue. Else no one will likely be able to reproduce or understand your exact problem and it may never get fixed.

**Comment by andreasjacobsen93** [comment] 2017-06-01 07:36
After setting up a completely new fresh instance of NC, I got the above error in the log.

Running Ubuntu 17.04, with LAMP and Redis.

**Comment by yodaphone** [comment] 2017-06-03 22:02
i have the same issue

Ubuntu 16.04 + Nextcloud 12.0

**Comment by MatthlK** [comment] 2017-06-15 08:32
Same log entry here.
Plesk 17.5.3 running on Debian 8.8, Nextcloud 12.0.0.29.

**Comment by Happyfeet01** [comment] 2017-06-28 16:32
Same here with Plesk 17.5.3 on Ubuntu 16.04 LTS and Nextcloud 12.0.0.29

**Comment by mayanksuman** [comment] 2017-07-11 02:34
Redis Version => 3.1.1
Apache Version => 2.4.25
Nextcloud => 12.0.0.29

Same problem exist. However, the workaround is to disable 'Transactional File Locking'.

**Comment by MorrisJobke** [comment] 2017-07-11 08:50
> Same problem exists. The workaround is to disable 'Transactional File Locking' for redis. However, the redis memcache works good.

Not really. The above error message is caused by the test of the internet connection on the admin page. Somehow the server https://www.nextcloud.com was not reachable.

**Comment by mayanksuman** [comment] 2017-07-12 09:24
I have solved the problem now. There are two reasons for that.
1. Check the permission of data folder. Data folder should be owned by www-data:www-data. Its parent should be owned by root:www-data and all parent should be owned by root:root.
2. If you behind a proxy server then add proxy option in config/config.php
'proxy' => 'proxy_server:proxy_port',

**Comment by alahwany** [comment] 2017-11-04 12:24
i have same problem with fresh installed and app store not shown !!!!

please help me

**Comment by MorrisJobke** [comment] 2017-11-06 14:39
The app store had some hiccups on the weekend and today. The issue should be resolved now.

I will close this ticket here then.

Thanks

**Closed by MorrisJobke** 2017-11-06 14:39 UTC
Labels: needs info
