### ISSUE TITLE
Sharing Folder with thousands files/subfolders via federated share doesn't work

### ISSUE THREAD

**Issue by t0mcat1337** [nextcloud/server#19483] opened 2020-02-14 14:20 UTC
### Steps to reproduce
1. Have a local NC 17.0.3 instance containing a folder with thousands files / subfolders
2. Share this folder to another NC 17.0.3 instance in the world via federated sharing
3. Log in to the remote NC instance with the user to who the folder was shared
4. Accept the share
5. Reload the Files App
6. Wait a few minutes, reload again the files app
7. Notice the column "Size" still has "Pending" for the shared folder
8. Click on the shared folder
9. Wait, watch the spinner rotating
10. The screen jumps back to the main folder, Error "Storage is temporarily not available" is shown in the upper right corner
11. Look at the NC Log, notice the SabreDAV Exception

### Expected behaviour
The folder should open on the remote side.

### Actual behaviour
Error "Storage is temporarily not available" is shown
SabreDAV Exception in NC Log of the remote cloud
No Error in NC Log of the NC instance from where the folder is shared

### Server configuration

**Operating system:**
Both Clouds: Ubuntu 18.04

**Web server:**
Both Clouds: Apache

**Database:**
Both Clouds: MySQL

**PHP version:**
Both Clouds: 7.2

**Nextcloud version:** (see Nextcloud admin page)
Both Clouds: 17.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Both Clouds: Updated

**Where did you install Nextcloud from:**
Both Clouds: Originally downloaded the tar.gz from your site, then Updated via NC Updated

This is the SabreDAV Exception:

```
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable:  at <<closure>>

 0. /var/www/clients/client9/web134/sub/cloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 76
    OCA\DAV\Connector\Sabre\Directory->getChild("sharedFolder")
 1. /var/www/clients/client9/web134/sub/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 967
    Sabre\DAV\Tree->getNodeForPath("files/user/sharedFolder")
 2. /var/www/clients/client9/web134/sub/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("files/user/sharedFolder", ["{DAV:}getlastm ... "], 1)
 3. /var/www/clients/client9/web134/sub/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
 4. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 5. /var/www/clients/client9/web134/sub/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
 6. /var/www/clients/client9/web134/sub/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
 7. /var/www/clients/client9/web134/sub/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 8. /var/www/clients/client9/web134/sub/cloud/apps/dav/lib/Server.php line 317
    Sabre\DAV\Server->exec()
 9. /var/www/clients/client9/web134/sub/cloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
10. /var/www/clients/client9/web134/sub/cloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/client ... p")

PROPFIND /remote.php/dav/files/user/sharedFolder
from 1.2.3.4 by user at 2020-02-14T13:50:46+00:00

```
Sharing another folder with just a few files/subfolders exact the same way works.

The issue also has been reported here:
https://help.nextcloud.com/t/federated-shares-showing-size-of-pending-storage-is-temporarily-unnavailable/57826

**Comment by t0mcat1337** [comment] 2020-02-14 15:16
BTW:
Accessing the mentioned folder of the source NC instance via the "/remote.php/webdav" URL with a standalone WebDAV client works without any problem.

So I assume this is a SabreDAV related issue...

**Comment by t0mcat1337** [comment] 2020-02-14 15:17
BTW2:
For testing purposes I updated the NC instance to which the folder is shared to NC 18.0.1. The error is exactly the same.

**Comment by Message0815** [comment] 2020-02-14 15:29
+1 same issue

**Comment by t0mcat1337** [comment] 2020-02-14 15:48
BTW3:
Just for Info.... The mentioned folder totally has:
8641  Files in
471 Sub-(Sub-)folders

**Comment by kesselb** [comment] 2020-02-14 16:11
BTW: it's possible to edit posts on GitHub. No need to add a new comment for every update 😉

**Comment by BugDeliverer** [comment] 2020-04-28 19:00
Same issue here. Federated share doesn't work with lots of files. Help appreciated

**Comment by BugDeliverer** [comment] 2020-06-02 16:30
This bug also affects all released versions of Nextcloud 18.

**Comment by Zocker1999NET** [comment] 2021-05-09 14:13
I found a good workaround, not user-friendly to setup but user-friendly to use afterwards:
- Install and enable the "External Storage Support" app and, if required, enable normal users to configure WebDAV shares
- "Extract" the share id from the shared url, e.g. `1234xyz` is the share id of
  - `https://cloud.example.com/index.php/s/1234xyz`
  - `https://cloud.example.com/s/1234xyz`
  - `https://example.com/nextcloud/index.php/s/1234xyz`
  - `https://example.com/nextcloud/s/1234xyz`
- Identify the public WebDAV endpoint of the foreign server, e.g.
  - `https://cloud.example.com/public.php/webdav`
  - `https://example.com/nextcloud/public.php/webdav`
- Configure a WebDAV share in your "External Storage" app with following values
  - Name as you like
  - `WebDAV` as type
  - Authentication is "Username/Password"
  - the WebDAV endpoint of the other server as url
  - leave remote subfolder empty, if you want to see the whole public share
  - use the share id as username
  - use anything for password as it will be ignored on passwordless shares, e.g. `j`

This works as long as the folder structure is complex but no folder you want to access contains too many files, as I see it now. Maybe this workaround can be used by the developers to fix the problem.

**Comment by szaimen** [comment] 2021-07-06 09:15
I think this is a duplicate of https://github.com/nextcloud/server/issues/4339

**Comment by szaimen** [comment] 2021-07-06 09:17
Lets track this https://github.com/nextcloud/server/issues/4339

**Closed by szaimen** 2021-07-06 09:17 UTC
Labels: 0. Needs triage, bug, feature: federation, feature: sharing, needs info
