### ISSUE TITLE
Folders and items ending with ~ are not synced to the server

### ISSUE THREAD

**Issue by dp87** [nextcloud/server#3072] opened 2017-01-14 13:09 UTC
### Steps to reproduce
1. Create a new folder, name it whatever you want and add a folder inside it with a name that ends with a tilde character (~)
2. Start a sync from the desktop client

### Expected behaviour
The folder should be synced to the server even if it ends with ~, or the desktop client should at least report that this folder has not been synced.

### Actual behaviour
The folder with the ~ in the name is not synced to the server, but the desktop client reports that it is synced instead. If you cd to the folder in your file manager it will show you that this folder is being synced.

Removing the ~ from the file name allows the sync to trigger and complete successfully.

Note that this does not happen if the ~ appears anywhere else in the file or folder name.

### Server configuration
**Operating system**: Ubuntu Server 16.04.1 LTS

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

**PHP version:** PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Nextcloud version:** 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** wget from download page

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc3aoqm9pcxd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.60"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "http:\/\/192.168.0.60",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

Browser information doesn't apply here so I didn't add it. Also, no NextCloud logs seem to mention this, as the sync client simply reports that sync has been successful.

**Comment by schiessle** [comment] 2017-01-16 13:57
That's because this is in the ignore list of the client. You can edit the list manually. Just open your sync client->general->edit ignore list

I close this because it is not a bug. Don't hesitate to ask if you have problems finding the settings or if it still fail to sync after you edited the ignore list.

**Closed by schiessle** 2017-01-16 13:57 UTC
