### ISSUE TITLE
Error: An exception occurred while executing 'INSERT INTO `oc_comments`

### ISSUE THREAD

**Issue by working-name** [nextcloud/server#24145] opened 2020-11-15 18:38 UTC
### Steps to reproduce
1. Don't know, but it seems it's a comment I left on a file? I was just playing around, blank install.
2.
3.

### Expected behaviour
Insert expected timestamp format into database, without the error.

### Actual behaviour
Log is flooded with the same error every few seconds.

### Server configuration

**Operating system:** Ubuntu 20.04.1 LTS 5.4.65-1-pve

**Web server:** Apache/2.4.41, behind nginx proxy

**Database:** mariadb 10.3.25

**PHP version:** 7.4.3

**Nextcloud version:** 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.2
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - deck: 1.1.2
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.7.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.1.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.1
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "dropbox.joke-of-a-server.com",
            "10.0.0.210",
            "office.joke-of-a-server.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "https:\/\/dropbox.joke-of-a-server.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "loglevel": "3"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
There are no commands defined in the "ldap" namespace.
```
</details>

### Client configuration
**Browser:**
Waterfox 2020.10, latest firefox for linux
**Operating system:**
macOS 10.14.4, linux Mint 20.something
#### Web server error log - N/A
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```json
{
  "reqId": "ektTkzHSYp1VGfYZDVQp",
  "level": 3,
  "time": "2020-11-15T18:05:29+00:00",
  "remoteAddr": "10.0.0.201",
  "user": "user",
  "app": "no app in context",
  "method": "GET",
  "url": "/ocs/v2.php/apps/spreed/api/v2/room",
  "message": {
    "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
    "Message": "An exception occurred while executing 'INSERT INTO `oc_comments` (`parent_id`, `topmost_parent_id`, `children_count`, `actor_type`, `actor_id`, `message`, `verb`, `creation_timestamp`, `latest_child_timestamp`, `object_type`, `object_id`, `reference_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"0\", \"0\", 0, \"guests\", \"changelog\", \"- Spice up your messages with emojis from the emoji picker \\ud83d\\ude0d\", \"comment\", \"2020-11-15 18:05:29\", null, \"chat\", \"1\", null]:\n\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x8D' for column `nextcloud`.`oc_comments`.`message` at row 1",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php",
        "line": 169,
        "function": "convertException",
        "class": "Doctrine\\DBAL\\Driver\\AbstractMySQLDriver",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php",
        "line": 149,
        "function": "wrapException",
        "class": "Doctrine\\DBAL\\DBALException",
        "type": "::"
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php",
        "line": 1071,
        "function": "driverExceptionDuringQuery",
        "class": "Doctrine\\DBAL\\DBALException",
        "type": "::"
      },
      {
        "file": "/var/www/html/lib/private/DB/Connection.php",
        "line": 214,
        "function": "executeUpdate",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php",
        "line": 209,
        "function": "executeUpdate",
        "class": "OC\\DB\\Connection",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 217,
        "function": "execute",
        "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Comments/Manager.php",
        "line": 786,
        "function": "execute",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Comments/Manager.php",
        "line": 749,
        "function": "insertQuery",
        "class": "OC\\Comments\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Comments/Manager.php",
        "line": 725,
        "function": "insert",
        "class": "OC\\Comments\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Chat/ChatManager.php",
        "line": 151,
        "function": "save",
        "class": "OC\\Comments\\Manager",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Manager.php",
        "line": 80,
        "function": "addChangelogMessage",
        "class": "OCA\\Talk\\Chat\\ChatManager",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Listener.php",
        "line": 53,
        "function": "updateChangelog",
        "class": "OCA\\Talk\\Chat\\Changelog\\Manager",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Listener.php",
        "line": 37,
        "function": "preGetRooms",
        "class": "OCA\\Talk\\Chat\\Changelog\\Listener",
        "type": "->"
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 251,
        "function": "OCA\\Talk\\Chat\\Changelog\\{closure}",
        "class": "OCA\\Talk\\Chat\\Changelog\\Listener",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
        "line": 73,
        "function": "callListeners",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
        "line": 86,
        "function": "dispatch",
        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/apps/spreed/lib/Controller/RoomController.php",
        "line": 164,
        "function": "dispatch",
        "class": "OC\\EventDispatcher\\EventDispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 169,
        "function": "getRooms",
        "class": "OCA\\Talk\\Controller\\RoomController",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 100,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 152,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 308,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/var/www/html/ocs/v1.php",
        "line": 88,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/var/www/html/ocs/v2.php",
        "line": 24,
        "args": [
          "/var/www/html/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php",
    "Line": 106,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Driver\\PDOException",
      "Message": "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x8D' for column `nextcloud`.`oc_comments`.`message` at row 1",
      "Code": "22007",
      "Trace": [
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php",
          "line": 1062,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Driver\\PDOStatement",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/DB/Connection.php",
          "line": 214,
          "function": "executeUpdate",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php",
          "line": 209,
          "function": "executeUpdate",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 217,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Comments/Manager.php",
          "line": 786,
          "function": "execute",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Comments/Manager.php",
          "line": 749,
          "function": "insertQuery",
          "class": "OC\\Comments\\Manager",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Comments/Manager.php",
          "line": 725,
          "function": "insert",
          "class": "OC\\Comments\\Manager",
          "type": "->"
        },
        {
          "file": "/var/www/html/apps/spreed/lib/Chat/ChatManager.php",
          "line": 151,
          "function": "save",
          "class": "OC\\Comments\\Manager",
          "type": "->"
        },
        {
          "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Manager.php",
          "line": 80,
          "function": "addChangelogMessage",
          "class": "OCA\\Talk\\Chat\\ChatManager",
          "type": "->"
        },
        {
          "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Listener.php",
          "line": 53,
          "function": "updateChangelog",
          "class": "OCA\\Talk\\Chat\\Changelog\\Manager",
          "type": "->",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Listener.php",
          "line": 37,
          "function": "preGetRooms",
          "class": "OCA\\Talk\\Chat\\Changelog\\Listener",
          "type": "->"
        },
        {
          "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
          "line": 251,
          "function": "OCA\\Talk\\Chat\\Changelog\\{closure}",
          "class": "OCA\\Talk\\Chat\\Changelog\\Listener",
          "type": "::",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
          "line": 73,
          "function": "callListeners",
          "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
          "line": 86,
          "function": "dispatch",
          "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/apps/spreed/lib/Controller/RoomController.php",
          "line": 164,
          "function": "dispatch",
          "class": "OC\\EventDispatcher\\EventDispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 169,
          "function": "getRooms",
          "class": "OCA\\Talk\\Controller\\RoomController",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 100,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/AppFramework/App.php",
          "line": 152,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/var/www/html/lib/private/Route/Router.php",
          "line": 308,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::"
        },
        {
          "file": "/var/www/html/ocs/v1.php",
          "line": 88,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->"
        },
        {
          "file": "/var/www/html/ocs/v2.php",
          "line": 24,
          "args": [
            "/var/www/html/ocs/v1.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php",
      "Line": 129,
      "Previous": {
        "Exception": "PDOException",
        "Message": "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xF0\\x9F\\x98\\x8D' for column `nextcloud`.`oc_comments`.`message` at row 1",
        "Code": "22007",
        "Trace": [
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php",
            "line": 127,
            "function": "execute",
            "class": "PDOStatement",
            "type": "->"
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php",
            "line": 1062,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Driver\\PDOStatement",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/DB/Connection.php",
            "line": 214,
            "function": "executeUpdate",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php",
            "line": 209,
            "function": "executeUpdate",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 217,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/Comments/Manager.php",
            "line": 786,
            "function": "execute",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/Comments/Manager.php",
            "line": 749,
            "function": "insertQuery",
            "class": "OC\\Comments\\Manager",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/Comments/Manager.php",
            "line": 725,
            "function": "insert",
            "class": "OC\\Comments\\Manager",
            "type": "->"
          },
          {
            "file": "/var/www/html/apps/spreed/lib/Chat/ChatManager.php",
            "line": 151,
            "function": "save",
            "class": "OC\\Comments\\Manager",
            "type": "->"
          },
          {
            "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Manager.php",
            "line": 80,
            "function": "addChangelogMessage",
            "class": "OCA\\Talk\\Chat\\ChatManager",
            "type": "->"
          },
          {
            "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Listener.php",
            "line": 53,
            "function": "updateChangelog",
            "class": "OCA\\Talk\\Chat\\Changelog\\Manager",
            "type": "->",
            "args": [
              "*** sensitive parameters replaced ***"
            ]
          },
          {
            "file": "/var/www/html/apps/spreed/lib/Chat/Changelog/Listener.php",
            "line": 37,
            "function": "preGetRooms",
            "class": "OCA\\Talk\\Chat\\Changelog\\Listener",
            "type": "->"
          },
          {
            "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
            "line": 251,
            "function": "OCA\\Talk\\Chat\\Changelog\\{closure}",
            "class": "OCA\\Talk\\Chat\\Changelog\\Listener",
            "type": "::",
            "args": [
              "*** sensitive parameters replaced ***"
            ]
          },
          {
            "file": "/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
            "line": 73,
            "function": "callListeners",
            "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/EventDispatcher/EventDispatcher.php",
            "line": 86,
            "function": "dispatch",
            "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
            "type": "->"
          },
          {
            "file": "/var/www/html/apps/spreed/lib/Controller/RoomController.php",
            "line": 164,
            "function": "dispatch",
            "class": "OC\\EventDispatcher\\EventDispatcher",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 169,
            "function": "getRooms",
            "class": "OCA\\Talk\\Controller\\RoomController",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
            "line": 100,
            "function": "executeController",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/AppFramework/App.php",
            "line": 152,
            "function": "dispatch",
            "class": "OC\\AppFramework\\Http\\Dispatcher",
            "type": "->"
          },
          {
            "file": "/var/www/html/lib/private/Route/Router.php",
            "line": 308,
            "function": "main",
            "class": "OC\\AppFramework\\App",
            "type": "::"
          },
          {
            "file": "/var/www/html/ocs/v1.php",
            "line": 88,
            "function": "match",
            "class": "OC\\Route\\Router",
            "type": "->"
          },
          {
            "file": "/var/www/html/ocs/v2.php",
            "line": 24,
            "args": [
              "/var/www/html/ocs/v1.php"
            ],
            "function": "require_once"
          }
        ],
        "File": "/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php",
        "Line": 127
      }
    },
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0",
  "version": "20.0.1.1",
  "id": "5fb16dea5b9ce"
}
```
</details>

#### Browser log - N/A
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2020-11-16 11:49
cc @nextcloud/talk

**Comment by nickvergessen** [comment] 2020-11-16 14:58
Duplicate of https://github.com/nextcloud/spreed/issues/4463

**Closed by nickvergessen** 2020-11-16 14:58 UTC
Labels: 0. Needs triage, bug
