### ISSUE TITLE
Users page looks broken

### ISSUE THREAD

**Issue by Luticus** [nextcloud/server#18968] opened 2020-01-18 06:06 UTC
### Steps to reproduce
1.  Upgrade to Nextcloud 18
2.  Click users in the menu
3.  users page is drawn badly with text running into each other/overlapping

### Expected behaviour
Tell us what should happen
users page should look normal as they did in nextcloud 17
### Actual behaviour
Tell us what happens instead
the page is broken with text overlapping.
### Server configuration

**Operating system:**
debian 10
**Web server:**
apache
**Database:**
mariadb
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
18
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 17.0.2
**Where did you install Nextcloud from:**
obtained from nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - calendar: 2.0.0
  - checksum: 0.4.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.6
  - dav: 1.14.0
  - event_update_notification: 1.0.1
  - external: 3.5.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_antivirus: 2.2.1
  - files_automatedtagging: 1.8.0
  - files_downloadactivity: 1.7.0
  - files_ebookreader: 0.0.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_readmemd: 1.1.3
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - groupfolders: 6.0.0
  - keeweb: 0.5.1
  - ldap_write_support: 1.1.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.10.0
  - news: 14.1.2
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ojsxc: 3.4.4
  - passman: 2.3.5
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - rainloop: 6.0.4
  - recommendations: 0.6.0
  - richdocuments: 3.5.1
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.0
  - suspicious_login: 3.0.1
  - systemtags: 1.8.0
  - talk_simple_poll: 1.1.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.2.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

{
    "system": {
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.example.com",
            "x.example.com",
            "y.example.com",
            "z.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files",
        "remember_login_cookie_lifetime": 3600,
        "session_lifetime": 86400,
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ####,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "###",
        "mail_smtptimeout": 30,
        "forcessl": true,
        "xframe_restriction": false,
        "logtimezone": "US\/Eastern",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 0,
        "log_authfailip": true,
        "appstoreenabled": true,
        "forceSSLforSubdomains": false,
        "enable_previews": true,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Image",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF"
        ],
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "auth.bruteforce.protection.enabled": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/www.example.com",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mysql.utf8mb4": true,
        "app.mail.accounts.default": {
            "email": "%USERID%@example.com",
            "imapHost": "mail.example.com",
            "imapPort": ###,
            "imapSslMode": "ssl",
            "smtpHost": "mail.example.com",
            "smtpPort": ###,
            "smtpSslMode": "ssl"
        },
        "updater.release.channel": "stable",
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

+-------------------------------+--------------------------------------------------------------+
| Configuration                 | s01                                                          |
+-------------------------------+--------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                              |
| homeFolderNamingRule          |                                                              |
| lastJpegPhotoLookup           | 0                                                            |
| ldapAgentName                 | cn=admin,dc=example,dc=com                                 |
| ldapAgentPassword             | ***                                                          |
| ldapAttributesForGroupSearch  |                                                              |
| ldapAttributesForUserSearch   |                                                              |
| ldapBackupHost                |                                                              |
| ldapBackupPort                |                                                              |
| ldapBase                      | dc=example,dc=com                                          |
| ldapBaseGroups                | ou=groups,dc=example,dc=com                                |
| ldapBaseUsers                 | dc=example,dc=com                                          |
| ldapCacheTTL                  | 600                                                          |
| ldapConfigurationActive       | 1                                                            |
| ldapDefaultPPolicyDN          |                                                              |
| ldapDynamicGroupMemberURL     |                                                              |
| ldapEmailAttribute            | mail                                                         |
| ldapExperiencedAdmin          | 0                                                            |
| ldapExpertUUIDGroupAttr       |                                                              |
| ldapExpertUUIDUserAttr        |                                                              |
| ldapExpertUsernameAttr        |                                                              |
| ldapExtStorageHomeAttribute   |                                                              |
| ldapGidNumber                 | gidNumber                                                    |
| ldapGroupDisplayName          | cn                                                           |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)(objectclass=top))(|(cn=users))) |
| ldapGroupFilterGroups         | users                                                        |
| ldapGroupFilterMode           | 0                                                            |
| ldapGroupFilterObjectclass    | posixGroup;top                                               |
| ldapGroupMemberAssocAttr      | uniqueMember                                                 |
| ldapHost                      | ldaps://ldap.example.com                                  |
| ldapIgnoreNamingRules         |                                                              |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid))                  |
| ldapLoginFilterAttributes     |                                                              |
| ldapLoginFilterEmail          | 0                                                            |
| ldapLoginFilterMode           | 1                                                            |
| ldapLoginFilterUsername       | 1                                                            |
| ldapNestedGroups              | 0                                                            |
| ldapOverrideMainServer        |                                                              |
| ldapPagingSize                | 500                                                          |
| ldapPort                      | 636                                                          |
| ldapQuotaAttribute            |                                                              |
| ldapQuotaDefault              |                                                              |
| ldapTLS                       | 0                                                            |
| ldapUserAvatarRule            | default                                                      |
| ldapUserDisplayName           | cn                                                           |
| ldapUserDisplayName2          |                                                              |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                               |
| ldapUserFilterGroups          |                                                              |
| ldapUserFilterMode            | 1                                                            |
| ldapUserFilterObjectclass     | inetOrgPerson                                                |
| ldapUuidGroupAttribute        | auto                                                         |
| ldapUuidUserAttribute         | auto                                                         |
| turnOffCertCheck              | 1                                                            |
| turnOnPasswordChange          | 1                                                            |
| useMemberOfToDetectMembership | 1                                                            |
+-------------------------------+--------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:**
firefox

**Operating system:**
debian 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
Nothing relevant looking in the webserver log
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Only relavent looking thing in the logs when I load the page:
{"reqId":"iyNXCXgqesdF1Qjlsboj","level":1,"time":"2020-01-18T00:55:28-05:00","remoteAddr":"x.x.x.x","user":"bob","app":"no app in context","method":"GET","url":"/index.php/avatar/fe155200-ac43-1036-82e2-454e9d3122eb/64?v=0","message":"Deprecated event type for OCA\\User_LDAP\\User\\User::postLDAPBackendAdded: null","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...

Only thing that stood out was:
oc_requesttoken is deprecated: use OC.requestToken instead



```
</details>

**Comment by Luticus** [comment] 2020-01-18 06:11
![bug in nextcloud18 users](https://user-images.githubusercontent.com/7807109/72659551-4a6d3900-398f-11ea-887e-3d2479040b6c.png)
Here is a screenshot between the email and groups columns.  It's taken this way to hide the names of the users/email/groups but hopefully it still gives an idea of what I'm talking about with the overlap.

**Comment by Luticus** [comment] 2020-01-18 06:15
I believe it's not handling the overflow correctly when there are lots of groups.

**Comment by bpcurse** [comment] 2020-01-18 08:55
Could this be a duplicate of #18920?

**Comment by Luticus** [comment] 2020-01-19 16:25
Yep, I think it is.

**Comment by nickvergessen** [comment] 2020-02-18 19:22
Duplicate of #18920

**Closed by nickvergessen** 2020-02-18 19:22 UTC
Labels: 0. Needs triage, bug
