### ISSUE TITLE
[Bug]: System config option "blacklisted_files" is deprecated

### ISSUE THREAD

**Issue by Markoise** [nextcloud/server#48260] opened 2024-09-21 09:11 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The following message appears several times a day in the log:
 
`System config option "blacklisted_files" is deprecated and will be removed in Nextcloud 34, use "forbidden_filenames" instead.`

### Steps to reproduce

If I replace blacklisted_files with forbidden_filenames. After a restart, blacklisted_files is probably automatically added back to the end of config.php

### Expected behavior

No message in log

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "cloud.kreksch.de",
            "192.168.178.50",
            "nextcloud.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.0.14",
        "overwrite.cli.url": "https:\/\/sub.domain.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "cloud.kreksch.de",
        "activity_expire_days": 14,
        "allow_local_remote_servers": true,
        "auth.bruteforce.protection.enabled": true,
        "forbidden_filenames": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db",
            "desktop.ini"
        ],
        "cron_log": true,
        "default_phone_region": "DE",
        "default_language": "de",
        "default_locale": "de",
        "default_timezone": "Europe\/Berlin",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "log_rotate_size": "104857600",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "profile.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0.5,
            "dbindex": 1
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Freigaben",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, 90",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-aarch64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-aarch64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "maintenance": false,
        "app_install_overwrite": [
            "news",
            "files_rightclick",
            "tasks",
            "groupfolders",
            "otpmanager"
        ],
        "theme": "",
        "debug": false,
        "memories.gis_type": 1,
        "updater.release.channel": "stable",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": false,
        "upgrade.disable-web": true,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "has_rebuilt_cache": true,
        "memories.db.triggers.fcu": true,
        "maintenance_window_start": 1,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.0.0
  - bookmarks: 15.0.1
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.0
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - collectives: 2.14.3
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - cookbook: 0.11.2
  - dashboard: 7.10.0
  - dav: 1.31.1
  - dav_push: 0.0.1
  - deck: 1.14.0
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_automatedtagging: 1.20.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - flow_notifications: 1.10.0
  - geoblocker: 0.5.15
  - gpoddersync: 3.9.0
  - gpxpod: 6.0.0
  - groupfolders: 18.0.1
  - integration_tmdb: 2.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.0
  - memories: 7.4.1
  - news: 25.0.0-alpha8
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - otpmanager: 0.5.4
  - password_policy: 2.0.0
  - passwords: 2024.9.20
  - photos: 3.0.2
  - previewgenerator: 5.6.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recognize: 8.1.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - repod: 3.2.0
  - richdocuments: 8.5.0
  - richdocumentscode_arm64: 24.4.702
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.0
  - survey_client: 2.0.0
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0
  - tables: 0.8.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.2
  - workflowengine: 2.12.0
Disabled:
  - encryption: 2.18.0
  - files_external: 1.22.0 (installed 1.21.0)
  - firstrunwizard: 3.0.0 (installed 2.17.0)
  - forms: 4.2.4 (installed 4.2.4)
  - maps: 1.4.0 (installed 1.4.0)
  - support: 2.0.0 (installed 1.11.0)
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by kesselb** [comment] 2024-09-21 13:24
A common reason for such "configuration option is reappearing" cases are multiple files in config/ ending with `.config.php`.

**Comment by joshtrichards** [comment] 2024-09-21 13:52
Yeah. Almost certainly sounds like a misnamed config backup file or forgotten about multi-config scenario. See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file

**Comment by leachimus** [comment] 2024-09-29 10:16
This is exactly the error. I have another tweaks.config.php, which is probably also read out. The old entry was still there. I still see it as a bug, because nextcloud should only read the config.php and ignore all others.

**Comment by joshtrichards** [comment] 2024-09-29 12:46
@leachimus It's not a bug; it's how Nextcloud's config works. Did you read the doc link? It's a config *directory*. If you want random files in there to **not** be used, just don't name them `*.config.php`. :-)

**Comment by joshtrichards** [comment] 2024-09-29 12:49
@Markoise Going to close this under the assumption the cause is what was previously mentioned. If you're somehow getting this for some other reason, don't hesitate to reply and I'll re-open.

**Closed by joshtrichards** 2024-09-29 12:49 UTC
Labels: bug, needs info, 0. Needs triage, 30-feedback

**Comment by Markoise** [comment] 2024-09-29 15:05
There was actually a tweaks.config.php. I have no idea where it came from. After deleting it, I no longer received an entry in the log. Thank you

**Comment by joshtrichards** [comment] 2024-09-29 15:46
I suspect there's a third-party tutorial out there somewhere that maybe provides or has people create a `tweaks.config.php`.

**Comment by BL-Git** [comment] 2024-10-23 05:56
I have the same error but there is no other config.php in the directory. What other reasons could there be?

**Comment by romarioZ1000** [comment] 2024-11-25 20:23
Nextcloud Server Administration Manual, Release latest
Nextcloud configuration
Changes to the available options in config.php.
• The option blacklisted_files is now deprecated and replaced with forbidden_filenames

[https://docs.nextcloud.com/server/latest/Nextcloud_Server_Administration_Manual.pdf](url)

**Comment by nicedevil007** [comment] 2025-05-10 05:42
I have the same issue. I only have one config.php in my config folder and there is only the entry about the forbidden_filenames, unfortunately ```sudo -u www-data php /var/www/nextcloud/occ config:list system``` shows entries about 

```json
"blacklisted_files": [
    ".htaccess",
    "Thumbs.db",
    "thumbs.db"
]
```

I also run the command the remove the config part for blacklisted_files with occ, it is still there after the command:

![Image](https://github.com/user-attachments/assets/cce5e7e8-dd87-47d2-8ea4-85b681d1e7b6)
