### ISSUE TITLE
Show contact avatars in »share by email« feature

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2514] opened 2016-12-05 16:31 UTC
I only see the avatar placeholders. The contact images are not loaded.

@schiessle does it work for you?

**Comment by schiessle** [comment] 2016-12-05 17:24
I will have a look

**Comment by schiessle** [comment] 2016-12-05 17:37
Yes, I can verify it... Let me see if I can find out how the avatars are loaded.

**Comment by rullzer** [comment] 2016-12-05 18:46
Won't work currently. Avatars are not fetched from the contacts but from the system. Won't get fixed for 11.

**Comment by jancborchardt** [comment] 2016-12-05 19:25
Hmm really? :\ That’s very strange as it feels like a bug. cc @nextcloud/contacts folks too.

**Comment by rullzer** [comment] 2016-12-05 21:40
Not a bug. Just not where we load them from. We never did (or had to before) because we always only could share with local users (federated/group have no avatar) and link shares were not even displayed in the list.

**Comment by schiessle** [comment] 2016-12-08 10:48
> because we always only could share with local users (federated/group have no avatar)

Federated users have a avatar if you do a federated share with someone in your address book (same as for mail shares now) or if you share with someone from a trusted servers (trusted servers sync display name, email, federated cloud id and avatar).

But I agree let's look into this for Nextcloud 12

**Comment by rullzer** [comment] 2016-12-08 12:16
It doesn't display for federated users either. Because the avatar endpoint only knows about avatars for local users. But we'll need to think how to do this properly because the avatar endpoint has to be fast else stuff like the activity page get crazy slow.

**Comment by MorrisJobke** [comment] 2017-05-15 03:35
Nothing for 12.

**Comment by jancborchardt** [comment] 2017-09-22 15:15
@schiessle @rullzer any update here? We should show avatars consistently.

**Comment by rullzer** [comment] 2017-09-25 14:37
Nope I have not touched this at all recently.

**Comment by skjnldsv** [comment] 2018-04-10 07:08
@rullzer is your avatar server generation pr a fix for this?

**Comment by rullzer** [comment] 2018-04-10 08:49
No. Basically somebody needs to port some of the logic from the contacts menu to the share input etc. But my JS fu is not enough.

**Comment by MorrisJobke** [comment] 2018-11-15 09:43
Moved to 16.

**Comment by szaimen** [comment] 2022-11-26 14:18
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:34 UTC
Labels: bug, design, needs info, feature: sharing, 0. Needs triage, papercut
