### ISSUE TITLE
"occ files:scan --all" produces exceptions

### ISSUE THREAD

**Issue by Bodenseematze** [nextcloud/server#23433] opened 2020-10-14 09:06 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. open command line at server
2. execute "occ files:scan --all"

### Expected behaviour
Should run flawless without exceptions

### Actual behaviour
throws exceptions during run - but keeps runnig...

`Exception during scan: Trying to access array offset on value of type null`
`#0 /home/www/nextcloud-19/lib/private/Files/Cache/Scanner.php(418): OCA\Files\Command\Scan->exceptionErrorHandler()`
`#1 /home/www/nextcloud-19/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren()`
`#2 /home/www/nextcloud-19/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren()`
`#3 /home/www/nextcloud-19/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren()`
`#4 /home/www/nextcloud-19/lib/private/Files/Cache/Scanner.php(391): OC\Files\Cache\Scanner->scanChildren()`
`#5 /home/www/nextcloud-19/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren()`
`#6 /home/www/nextcloud-19/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan()`
`#7 /home/www/nextcloud-19/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan()`
`#8 /home/www/nextcloud-19/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles()`
`#9 /home/www/nextcloud-19/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute()`
`#10 /home/www/nextcloud-19/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()`
`#11 /home/www/nextcloud-19/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run()`
`#12 /home/www/nextcloud-19/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console``\Application->doRunCommand()`
`#13 /home/www/nextcloud-19/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()`
`#14 /home/www/nextcloud-19/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()`
`#15 /home/www/nextcloud-19/console.php(100): OC\Console\Application->run()`
`#16 /home/www/nextcloud-19/occ(11): require_once('/home/www/nextc...')`
`#17 {main}`

It scans certain users without problems but when it comes to the "main" user (myself) it runs a while and then the exception occurs (and then it switches to the next user)
So the exception also occurs when I do a "occ files:scan <ProblemUser>"

### Server configuration

**Operating system:**
Shared hoster with Debian 9 (?)

**Web server:**
Apache 

**Database:**
MariaDB 10.2.25

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from 17.0.10 (with interim update to 18.0.10)

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

### Logs
see above...

**Comment by kesselb** [comment] 2020-10-14 09:56
Duplicate of https://github.com/nextcloud/server/issues/22846

**Closed by kesselb** 2020-10-14 09:56 UTC
Labels: 0. Needs triage, bug
