### ISSUE TITLE
Nextcloud locking .PPTX files

### ISSUE THREAD

**Issue by Phoara** [nextcloud/server#9910] opened 2018-06-19 08:08 UTC
### Steps to reproduce
1. Create a .pptx-file and save it (syncs fine)
2. Continue working on the file (won't sync anymore)

### Expected behaviour
Nextcloud should sync the .pptx-files like it does with all other files.

### Actual behaviour
After saving the file and closing PowerPoint on my Mac, Nextcloud tells me that the .pptx file has been locked. Happens mostly to very big PPT-files >20 MB.

### Server configuration

**Operating system:** Shared Webhosting

**Web server:** Shared

**Database:** MySQL 5.7.21

**PHP version:** 7.1

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** My webhoster offers the installation. Then I updated via the admin panel within Nextcloud.

**Signing status:**

No errors have been found.

**List of activated apps:**

no access to the command line

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => 'XXXXXX',
  'passwordsalt' => 'XXXXXX',
  'secret' => 'XXXXXX',
  'trusted_domains' => 
  array (
    0 => 'XXXXXX',
	1 => 'https://',
	2 => 'localhost',
	3 => 'http://',
  ),
  'datadirectory' => '/www/htdocs/XXXXXX/nextcloud/data',
  'overwrite.cli.url' => 'XXXXXX',
  'dbtype' => 'mysql',
  'version' => '13.0.1.1',
  'dbname' => 'XXXXXX',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'QyT8L_',
  'mysql.utf8mb4' => false,
  'dbuser' => 'XXXXXX',
  'dbpassword' => 'XXXXXX',
  'installed' => true,
  'tempdirectory' => '/www/htdocs/XXXXXX/nextcloud/tmp',
  'updater.secret' => 'XXXXXX',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
);

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav/ but not for this folder

#### LDAP configuration (delete this part if not used)

no access

### Client configuration
**Browser:** Official Nextcloud Application

**Operating system:** Mac OS 10.13.2

#### Web server error log
<details>
<summary>Web server error log</summary>

Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\FileLocked: "XXXXXX/XXXXXX/XXXXXX/XXXXXX/XXXXXX/00_XXXXXX.pptx" is locked | 2018-06-19T09:57:49+0200

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tapete** [comment] 2018-06-19 21:08
I noticed the same behaviour. This is also discussed here: https://github.com/nextcloud/server/issues/8239#issuecomment-398294991

**Comment by MorrisJobke** [comment] 2018-06-28 08:44
> OCA\DAV\Connector\Sabre\Exception\FileLocked

A possible workaround: use Redis as locking backend. There seem to be still some race conditions we are currently try to find:

SQL issue: #9305 
Redis issue: #8239

Closing as duplicate of the two mentioned ones.

**Closed by MorrisJobke** 2018-06-28 08:44 UTC
