### ISSUE TITLE
Disappearing text on MouseOver

### ISSUE THREAD

**Issue by kekePower** [nextcloud/server#13440] opened 2019-01-09 12:18 UTC
### Steps to reproduce
1. Hover mouse over the top menu. Text is showing.
2. Click the 3 dots menu and keep it open.
3. Hover over the top menu. Text is missing.

Video showing what I mean.
https://www.youtube.com/watch?v=Ir3uTLD8wok

### Expected behaviour
I would expect the text to show.

### Server configuration

**Operating system**:
Mageia 7, x86_64

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.3.0

**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.x

**Where did you install Nextcloud from:**
RPM package proved by my distro

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.8.2
  - audioplayer: 2.5.1
  - bookmarks: 0.15.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - carnet: 0.12.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - end_to_end_encryption: 1.1.0
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - passman: 2.2.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.2
  - spreed: 5.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - admin_audit
  - circles
  - encryption
  - files_external
  - groupfolders
  - nextcloud_announcements
  - scanner
  - support
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "integrity.check.disabled": true,
        "log_type": "syslog",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "check_for_working_htaccess": false,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/lib\/nextcloud",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
        "apps_paths": [
            {
                "path": "\/usr\/share\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "monster",
            "kekecloud.loginto.me"
        ],
        "overwrite.cli.url": "https:\/\/kekecloud.loginto.me\/nextcloud",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Firefox

**Operating system:**
Linux

**Comment by juliusstoerrle** [comment] 2019-01-24 12:45
Can reproduce this accross Safari, Firefox and Chrome on multiple devices

**Comment by juliushaertl** [comment] 2019-02-19 10:55
Duplicate of https://github.com/nextcloud/server/issues/14220

**Closed by juliushaertl** 2019-02-19 10:55 UTC
Labels: 1. to develop, bug, design, regression
