### ISSUE TITLE
File move fails silently (but makes copy of files)

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#5022] opened 2017-05-22 05:48 UTC
### Steps to reproduce
1. Connect legacy DMS as external storage via webdav (read-only for safety)
2. select folder and choose move, with destination somewhere within "normal" NC
3. click move

### Expected behaviour
Files appear in NC, but get error on final step of deletion (i.e. forcing move to be copy)

### Actual behaviour
Files don't appear in NC, no error reported. Files are found to have been copied anyway and an occ files:scan makes them appear

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 11.03

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** download

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
 - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
  - workin2gether: 0.9.3

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oc6x7spezyjz",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "trustnobody.com"
        ],
        "datadirectory": "\/var\/ncstorage\/data",
        "overwrite.cli.url": "http:\/\/example.com\/nextcloud",
        "dbtype": "pgsql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "an.ip.addr.ess",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "email",
        "mail_smtpmode": "php",
        "mail_domain": "example.com",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "default_language": "en_GB",
        "maintenance": false,
        "loglevel": 2,
        "updater.release.channel": "production",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "timeout": 0,
            "dbindex": 0,
            "port": 6379
        }
    },
    "apps": {
        "activity": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "2.4.1"
        },
        "admin_audit": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.1.0"
        },
        "backgroundjob": {
            "lastjob": "448"
        },
        "comments": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.1.0"
        },
        "core": {
            "installedat": "1477938697.7946",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "umgmt_show_last_login": "true",
            "shareapi_exclude_groups_list": "[\"\"]",
            "shareapi_exclude_groups": "no",
            "umgmt_show_storage_location": "false",
            "shareapi_default_expire_date": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_enforce_expire_date": "no",
            "shareapi_expire_after_n_days": "3",
            "shareapi_allow_mail_notification": "yes",
            "oc.integritycheck.checker": "[]",
            "shareapi_enforce_links_password": "yes",
            "shareapi_allow_resharing": "no",
            "repairlegacystoragesdone": "yes",
            "vendor": "nextcloud",
            "updater.secret.created": "1494650847",
            "umgmt_send_email": "false",
            "OC_Channel": "production",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "lastcron": "1495409614",
            "umgmt_show_email": "false",
            "lastupdatedat": "1495429083",
            "lastupdateResult": "[]"
        },
        "dav": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true"
        },
        "deck": {
            "installed_version": "0.1.4",
            "types": "",
            "enabled": "no"
        },
        "external": {
            "installed_version": "",
            "ocsid": "166046",
            "types": "",
            "enabled": "yes",
            "sites": "[[\"Time\",\"https:\\\/\\\/time.example.com\",\"external.png\"]]"
        },
        "federatedfilesharing": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.1.1"
        },
        "federation": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.1.1"
        },
        "files": {
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500",
            "installed_version": "1.6.1"
        },
        "files_accesscontrol": {
            "installed_version": "1.1.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_external": {
            "ocsid": "166048",
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "1.1.2"
        },
        "files_pdfviewer": {
            "ocsid": "166049",
            "types": "",
            "enabled": "yes",
            "installed_version": "1.0.1"
        },
        "files_sharing": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.1.1"
        },
        "files_texteditor": {
            "ocsid": "166051",
            "types": "",
            "enabled": "yes",
            "installed_version": "2.2"
        },
        "files_trashbin": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.1.0"
        },
        "files_versions": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.4.0"
        },
        "files_videoplayer": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.0.0"
        },
        "firstrunwizard": {
            "enabled": "yes",
            "types": "logging",
            "installed_version": "2.0"
        },
        "gallery": {
            "types": "",
            "enabled": "yes",
            "installed_version": "16.0.0"
        },
        "logreader": {
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.0.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "installed_version": "1.0",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100"
        },
        "notifications": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.0.1"
        },
        "ownnote": {
            "installed_version": "1.08",
            "types": "",
            "ocsid": "168512",
            "folder": "",
            "enabled": "no"
        },
        "password_policy": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.1.0"
        },
        "provisioning_api": {
            "types": "prevent_group_restriction",
            "enabled": "yes",
            "installed_version": "1.1.0"
        },
        "serverinfo": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.0.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "survey_client": {
            "installed_version": "0.1.5",
            "types": "",
            "enabled": "yes"
        },
        "systemtags": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.1.3"
        },
        "templateeditor": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.2"
        },
        "theming": {
            "types": "logging",
            "enabled": "yes",
            "url": "https:\/\/nextcloud.example.com",
            "logoMime": "image\/png",
            "slogan": "a slogan",
            "cachebuster": "10",
            "color": "#3e305d",
            "name": "A Cloud",
            "installed_version": "1.1.1"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "workin2gether": "0.9.3",
            "types": "",
            "enabled": "yes",
            "installed_version": "1.1.1",
            "core": "11.0.3.2"
        },
        "user_cas": {
            "enabled": "no",
            "installed_version": "1.3",
            "types": "prelogin,authentication"
        },
        "user_ldap": {
            "installed_version": "1.1.2",
            "s02ldap_host": "",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "types": "authentication",
            "enabled": "yes",
            "s02ldap_port": "",
            "ldap_base_users": "dc=example,dc=local",
            "ldap_groupfilter_objectclass": "group",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_user_filter_mode": "0",
            "ldap_user_display_name_2": "",
            "ldap_group_display_name": "cn",
            "ldap_port": "389",
            "ldap_base": "dc=example,dc=local",
            "ldap_userfilter_groups": "Domain Users",
            "ldap_userfilter_objectclass": "user",
            "ldap_base_groups": "dc=example,dc=local",
            "ldap_groupfilter_groups": "Domain Users",
            "ldap_group_filter_mode": "1",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_loginfilter_attributes": "",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_cache_ttl": "600",
            "ldap_attributes_for_user_search": "",
            "ldap_attributes_for_group_search": "",
            "ldap_experienced_admin": "0",
            "home_folder_naming_rule": "",
            "use_memberof_to_detect_membership": "1",
            "ldap_expert_username_attr": "",
            "ldap_expert_uuid_user_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "last_jpegPhoto_lookup": "0",
            "ldap_nested_groups": "0",
            "ldap_paging_size": "500",
            "ldap_dynamic_group_member_url": "",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_user_display_name_2": "",
            "ldap_host": "an.ip.addr.ess",
            "s01ldap_user_filter_mode": "0",
            "ldap_dn": "cn=a.user,cn=users,dc=example,dc=local",
            "has_memberof_filter_support": "1",
            "s01ldap_group_filter": "",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_group_display_name": "cn",
            "ldap_userlist_filter": "(&(|(objectclass=user))(|(|(memberof=CN=Domain Users,CN=Users,DC=example,DC=local)(primaryGroupID=513))))",
            "ldap_login_filter": "(&(&(|(objectclass=user))(|(|(memberof=CN=Domain Users,CN=Users,DC=example,DC=local)(primaryGroupID=513))))(samaccountname=%uid))",
            "ldap_display_name": "displayname",
            "s01ldap_group_member_assoc_attribute": "uniqueMember",
            "ldap_override_main_server": "0",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_cache_ttl": "600",
            "s01ldap_override_main_server": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_experienced_admin": "0",
            "s01home_folder_naming_rule": "",
            "s01use_memberof_to_detect_membership": "1",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_nested_groups": "0",
            "s01ldap_paging_size": "500",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_host": "an.ip.add.ress",
            "ldap_group_member_assoc_attribute": "uniqueMember",
            "ldap_group_filter": "(&(|(objectclass=group))(|(cn=Domain Users)))",
            "s01ldap_dn": "cn=a.user,cn=users,dc=example,dc=local",
            "s01ldap_port": "389",
            "s01ldap_userlist_filter": "(&(|(objectclass=person))(|(|(memberof=CN=Domain Users,CN=Users,DC=example,DC=local)(primaryGroupID=513))))",
            "s01ldap_agent_password": "cGc5YjEzcWdpdkotMjI=",
            "s01ldap_base": "dc=example,dc=local",
            "s01ldap_userfilter_objectclass": "person",
            "s01has_memberof_filter_support": "1",
            "s01ldap_userfilter_groups": "Domain Users",
            "s01ldap_configuration_active": "1",
            "s01ldap_base_users": "dc=example,dc=local",
            "s01ldap_base_groups": "dc=example,dc=local",
            "ldap_email_attr": "mail",
            "s01ldap_email_attr": "",
            "s01ldap_display_name": "displayName",
            "s01ldap_login_filter": "(&(&(|(objectclass=person))(|(|(memberof=CN=Domain Users,CN=Users,DC=example,DC=local)(primaryGroupID=513))))(samaccountname=%uid))",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s02ldap_backup_host": "",
            "ldap_configuration_active": "1",
            "s01ldap_tls": "0",
            "cleanUpJobOffset": "100",
            "s02ldap_backup_port": "",
            "s02ldap_base": "",
            "s02ldap_base_users": "",
            "s02ldap_base_groups": "",
            "s02ldap_dn": "",
            "ldap_turn_on_pwd_change": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s02home_folder_naming_rule": "",
            "s02has_memberof_filter_support": "0",
            "s02use_memberof_to_detect_membership": "1",
            "s02ldap_expert_username_attr": "",
            "s02ldap_expert_uuid_user_attr": "",
            "s02ldap_expert_uuid_group_attr": "",
            "s02last_jpegPhoto_lookup": "0",
            "s02ldap_nested_groups": "0",
            "s02ldap_paging_size": "500",
            "s02ldap_turn_on_pwd_change": "0",
            "s02ldap_dynamic_group_member_url": "",
            "s03ldap_host": "",
            "s03ldap_port": "",
            "s03ldap_backup_host": "",
            "s03ldap_backup_port": "",
            "s03ldap_base": "",
            "s03ldap_base_users": "",
            "s03ldap_base_groups": "",
            "s03ldap_dn": "",
            "s03ldap_agent_password": "",
            "s03ldap_tls": "0",
            "s03ldap_turn_off_cert_check": "0",
            "s03ldap_display_name": "displayName",
            "s03ldap_user_display_name_2": "",
            "s03ldap_userfilter_objectclass": "",
            "s03ldap_userfilter_groups": "",
            "s03ldap_userlist_filter": "",
            "s03ldap_user_filter_mode": "0",
            "s03ldap_group_filter": "",
            "s03ldap_group_filter_mode": "0",
            "s03ldap_groupfilter_objectclass": "",
            "s03ldap_groupfilter_groups": "",
            "s03ldap_group_display_name": "cn",
            "s03ldap_group_member_assoc_attribute": "uniqueMember",
            "s03ldap_login_filter": "",
            "s03ldap_login_filter_mode": "0",
            "s03ldap_loginfilter_email": "0",
            "s03ldap_loginfilter_username": "1",
            "s03ldap_loginfilter_attributes": "",
            "s03ldap_quota_attr": "",
            "s03ldap_quota_def": "",
            "s03ldap_email_attr": "",
            "s03ldap_cache_ttl": "600",
            "s03ldap_override_main_server": "",
            "s03ldap_configuration_active": "0",
            "s03ldap_attributes_for_user_search": "",
            "s03ldap_attributes_for_group_search": "",
            "s03ldap_experienced_admin": "0",
            "s03home_folder_naming_rule": "",
            "s03has_memberof_filter_support": "0",
            "s03use_memberof_to_detect_membership": "1",
            "s03ldap_expert_username_attr": "",
            "s03ldap_expert_uuid_user_attr": "",
            "s03ldap_expert_uuid_group_attr": "",
            "s03last_jpegPhoto_lookup": "0",
            "s03ldap_nested_groups": "0",
            "s03ldap_paging_size": "500",
            "s02ldap_agent_password": "",
            "s02ldap_tls": "0",
            "s02ldap_turn_off_cert_check": "0",
            "s02ldap_display_name": "displayName",
            "s02ldap_user_display_name_2": "",
            "s02ldap_userfilter_objectclass": "",
            "s02ldap_userfilter_groups": "",
            "s02ldap_userlist_filter": "",
            "s02ldap_user_filter_mode": "0",
            "s02ldap_group_filter": "",
            "s02ldap_group_filter_mode": "0",
            "s02ldap_groupfilter_objectclass": "",
            "s02ldap_groupfilter_groups": "",
            "s02ldap_group_display_name": "cn",
            "s02ldap_group_member_assoc_attribute": "uniqueMember",
            "s02ldap_login_filter": "",
            "s02ldap_login_filter_mode": "0",
            "s02ldap_loginfilter_email": "0",
            "s02ldap_loginfilter_username": "1",
            "s02ldap_loginfilter_attributes": "",
            "s02ldap_quota_attr": "",
            "s02ldap_quota_def": "",
            "s02ldap_email_attr": "",
            "s02ldap_cache_ttl": "600",
            "s02ldap_override_main_server": "",
            "s02ldap_configuration_active": "0",
            "s02ldap_attributes_for_user_search": "",
            "s02ldap_attributes_for_group_search": "",
            "s02ldap_experienced_admin": "0",
            "s03ldap_turn_on_pwd_change": "0",
            "s03ldap_dynamic_group_member_url": ""
        },
        "workflowengine": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.1.1"
        },
        "workin2gether": {
            "ocsid": "164016",
            "suffix": "rule_displayname",
            "extended": "1",
            "installed_version": "0.9.3",
            "enabled": "yes",
            "types": ""
        }
    }
}
</details>

**Are you using external storage, if yes which one:** webdav to legacy KnowledgeTree installation

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP to Samba 4

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
LDAP as above
</details>

### Client configuration
**Browser:** FF52.02

**Operating system:**Tumbleweed

#### Web server error log
<details>
<summary>Web server error log</summary>
No errors logged during operation
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Items logged during operation:

{"reqId":"AmypqSAhgedVxl7baOaR","remoteAddr":"","app":"no app in context","message":"Storage failedstorage not available","level":3,"time":"2017-05-21T15:48:13+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"AmypqSAhgedVxl7baOaR","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"No session credentials saved\",\"Code\":2,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(316): OC\\\\Files\\\\Storage\\\\FailedStorage->acquireLock('scanner::', 2, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(196): OC\\\\Files\\\\Cache\\\\Scanner->scan('', true, 3)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Command\\\/Scan.php(159): OC\\\\Files\\\\Utils\\\\Scanner->scan('\\\/chris.puttick...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Command\\\/Scan.php(227): OCA\\\\Files\\\\Command\\\\Scan->scanFiles('chris.puttick...', '\\\/chris.puttick...', false, Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput), false)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(256): OCA\\\\Files\\\\Command\\\\Scan->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/core\\\/Command\\\/Base.php(161): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(818): OC\\\\Core\\\\Command\\\\Base->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(186): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OCA\\\\Files\\\\Command\\\\Scan), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(117): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(169): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/www\\\/nextcl...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/FailedStorage.php\",\"Line\":195}","level":3,"time":"2017-05-21T15:48:13+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"vcWDF7haHhSPc+hju2gV","remoteAddr":"an.ip.addr.ess","app":"PHP","message":"Undefined index: {DAV:}getlastmodified at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/DAV.php#583","level":3,"time":"2017-05-21T15:48:35+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/files_external\/userglobalstorages\/1?testOnly=false","user":"chris.puttick","version":"11.0.3.2"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>
No errors logged
</details>

**Comment by jospoortvliet** [comment] 2017-06-24 10:05
Isn't this the same issue as the move-between-external-storage issue we're debugging @MorrisJobke @icewind1991 ?

**Comment by MorrisJobke** [comment] 2017-07-04 16:57
I guess you mean #5424

**Comment by oparoz** [comment] 2017-07-06 11:47
Duplicate of #3502

**Closed by oparoz** 2017-07-06 11:47 UTC
