### ISSUE TITLE
No e-mail notification - event update only aceppted

### ISSUE THREAD

**Issue by PittRo** [nextcloud/server#17057] opened 2019-09-09 09:15 UTC
Steps to reproduce
1. Calendar event invitation
2. invitation aceppted without change of day and time

Expected behaviour
no notification by email

Actual behaviour
notification by email

Server configuration
not significant, general
Nextcloud Version 16

I understand the necessary notification if there are any changes or the event is declined.
But there is no need for email notification if the event is only acepted, the email text is more confucing than productive.
Nextcloud notifications are really enough.

**Comment by georgehrke** [comment] 2019-09-30 09:25
Duplicate of https://github.com/nextcloud/server/issues/13130

In the future please check for existing issues before creating a new one. Thx!

**Closed by georgehrke** 2019-09-30 09:25 UTC
Labels: 0. Needs triage, bug
