### ISSUE TITLE
Admin cannot edit own groups

### ISSUE THREAD

**Issue by burner-** [nextcloud/server#20079] opened 2020-03-21 12:52 UTC
### Expected behaviour
Earlier versions admin can add groups to itsef. 

### Actual behaviour
Admin cannot see groups editor in user edit

### Version
18.0.2

**Comment by kesselb** [comment] 2020-03-21 19:20
Duplicate of https://github.com/nextcloud/server/issues/19760

**Closed by kesselb** 2020-03-21 19:20 UTC
Labels: 0. Needs triage, bug
