### ISSUE TITLE
External (SMB/CIFS) storage app: always shows hidden files / does not scan subfolders

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/server#22032] opened 2020-07-28 13:27 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Navigate to Settings -> External storages and mount a new SMB / CIFS storage 
2. Check "enable previews", do **NOT** check "Show hidden files"
3. Navigate to the newly mounted folder 

### Expected behaviour
a) Folder content should NOT show hidden files 
b) After some time "Pending" should change to display the Size

### Actual behaviour
a) Folder External storages show all files including hidden files 
b) Pending is shown forever. Except when I manually naviagte to EVERY subfolder, sub-sub folder and sub-sub-sub folder - what is nearly impossible on a larger storage. It apperently is also not possible to trigger the file scan via OCC comand - that does scan all natively stored files, but apprently not the external SMB / CIFS storages.

### Server configuration
NC 19.0.1
Ext. stoarge app v 1.10.0
Ubuntu 20

**Web server:**
Apache

**Database:**
PostgreSQL 12.2 

**PHP version:**
7.4.3

**Comment by steve-s-71** [comment] 2020-07-28 13:33
@icewind1991 @MTGap and @PVince81 might be interested into this

**Comment by szaimen** [comment] 2021-06-09 12:51
You need to run `occ files:scan --all` to scan all your files.

**Comment by szaimen** [comment] 2021-06-09 12:52
Otherwise is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by j3l11234** [comment] 2021-07-01 07:53
> Otherwise is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

NC21.0.2 still has this problem, hidden files will still be displayed.  Even if do NOT check "Show hidden files"

**Comment by steve-s-71** [comment] 2021-07-01 11:36
@j3l11234 I can't repoduce the scan issue anymore. But the issue with the hidden files still exists in 21.0.0 and so likely also in 21.0.2 what I have not yet installed. 

The issue is, the External Files app only recognise files as hidden, that start with a dot. But if an SMB share is on a Windows Server a hidden file does not start with a dot.

**Comment by j3l11234** [comment] 2021-07-01 17:58
@steve-s-71 @szaimen 
 Hi, I am proud to announce that I have found the cause and solution.
The root cause is that icewind/smb(External Files app) can't recognize whether the file is hidden.
Here is the detail reason: 
1. before: icewind/smb read dos permissions mask from smbclient(query `system.dos_attr.mode`) to determine whether it is a hidden file
2. In Dec 19,2019, smbclient changed the `system.dos_attr.mode` result from dos permissions mask(which contain hidden/archive/system attributes) to unix permission mask. (https://gitlab.com/samba-team/samba/-/commit/0fe9dc521#64c7de226f297840d2892b1c3d76cc68a56fbc72)
2. icewind/smb use starting with a dot to determine whether it is a hidden file. (https://github.com/icewind1991/SMB/blob/9dba42ab2a3990de29e18cc62b0a8270aceb74e3/src/Native/NativeFileInfo.php#L78)

---

I found a way to get these properties. I have already submit a pull request to icewind/smb and waiting for merge and release new version.
https://github.com/icewind1991/SMB/pull/107


Dos permissions mask refer: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb/65e0c225-5925-44b0-8104-6b91339c709f

**Comment by steve-s-71** [comment] 2021-07-01 20:58
@j3l11234 this is awesome. You made my day - thank you!

Is there a way for me as a "non-developer" to know if a new version of the External Storage App with this fix included is released?

**Comment by j3l11234** [comment] 2021-07-04 03:23
@steve-s-71  I'm still waiting for mr to be merged. I can compile a libsmbclient package on ubuntu to solve this problem.

**Comment by steve-s-71** [comment] 2021-09-05 16:58
@jospoortvliet can you please ask a developer to make this fix available in NC release?

**Comment by szaimen** [comment] 2023-01-23 10:06
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:41 UTC
Labels: bug, needs info, feature: external storage, 0. Needs triage
