### ISSUE TITLE
[Bug]: Dates where moment.js is used seem to take locale instead of language

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#44355] opened 2024-03-20 12:41 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dates where moment.js is used seem to take locale instead of language.

Date in German in link previews:
![image](https://github.com/nextcloud/server/assets/925062/d1384146-9f55-4a05-9f51-d91251318dfa)

Mixed English and German in Talk chat:
![image](https://github.com/nextcloud/server/assets/925062/802d209a-f3d4-4610-8f59-73b68d9e0e06)

### Steps to reproduce

1. Have English as language but German as locale
2. Add a link in Talk or Text, or look at a relative date
3. It will be German

### Expected behavior

The date should consider the language for its _language_, and the locale only for the format.
Is this possible with Moment.js? cc @juliushaertl @nickvergessen 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by nickvergessen** [comment] 2024-03-20 15:50
I had a fix attempt back in 2019
https://github.com/nextcloud/server/pull/14784

Duplicate of https://github.com/nextcloud/server/issues/15457

**Comment by nickvergessen** [comment] 2024-03-20 15:51
Adding that one to your board for tracking

**Closed by nickvergessen** 2024-03-20 15:50 UTC
Labels: bug, design, 0. Needs triage, 29-feedback
