### ISSUE TITLE
Client error: "Host nextcloud.domain.tldstatus.php not found"

### ISSUE THREAD

**Issue by rtdegraaf** [nextcloud/server#2589] opened 2016-12-09 14:21 UTC
### Steps to reproduce
1. Open Nextcloud Mac OSX client version 2.2.4 (Latest Stable)
2. Connect to the nextcloud server

Expected behaviour
Get username and password prompt for connect to the Nextcloud server.

Actual behaviour
When I fill in the servername in the Nextcloud client on a Mac (Sierra 10.12) I get the following error:

"Could not connect to https://nextcloud.domain.tldstatus.php: Host nextcloud.domain.tldstatus.php not found"

When I do the same thing with the Owncloud client, same version 2.2.4, I can connect with no issues. On a Windows PC this problem does not exist with the Nextcloud client. I get the option to connect without SSL, but this also does not work when I get this error.

I am using a SSL certificatie generated with an Elliptic curve private key. When I'm replacing the certificate for a SHA-2 SSL certificate the error does not exists on my Nextcloud Mac client. The other clients on my iPhone en Windows PC can connect flawless with both certificates. So I gues the issue is related to the SSL certificate generated with an Elliptic curve private key.

### Server configuration
Operating system: Debian Jessie 

Web server: Apache 2.4

Database: MariaDB 10

PHP version: 5.6

Nextcloud version: 10.0.1

Nextcloud fresh install

Where did you install Nextcloud from: downloaded from nextcloud.com

**Comment by schiessle** [comment] 2016-12-09 15:20
seems like a slash is missing in the URL. @rullzer can you have a look? Thanks!

**Comment by rullzer** [comment] 2016-12-09 19:46
Yes looks like a missing slash. But I can't reproduce this issue. If I enter a host without a trailing slash (or with) it all works.

@LukasReschke can you check OS X?

**Comment by rtdegraaf** [comment] 2016-12-09 20:06
Like I mentioned, I get this error only on my Mac and with a certain ssl certificate. Only with a ssl certificate that has an eliptic curve private key. Perhaps the missing slash in the link is only echoëd tot the UI.

**Comment by rtdegraaf** [comment] 2016-12-10 19:45
FYI, I can reproduce this issue on a MacBook of a friend of mine, but only with the Eliptic curve SSL. With the other RSA key generated SSL certificate it works fine.

**Comment by rullzer** [comment] 2016-12-11 19:18
Aaah. Mmmm then it might be just a faulty error message (With a forgotten slash). Basically https://github.com/nextcloud/client_theming/issues/13

**Comment by MorrisJobke** [comment] 2018-03-06 21:39
Fixed in 2.3.3

**Closed by MorrisJobke** 2018-03-06 21:39 UTC
Labels: bug
