### ISSUE TITLE
Disable Log refresh

### ISSUE THREAD

**Issue by cal940** [nextcloud/server#4265] opened 2017-04-09 14:29 UTC
I use the app ”Log Reader v2.0.0“ for Nextcloud 11.0.2 (Stable).

- Expected: No Log refreshing when scrolling

- Actual: Log start to refresh when I scroll down after some time and I have to start from the bottom of the log.

![](http://i.imgur.com/TY8GJBb.jpg)

Note: I disabled my wifi on my iPad so I can take this screenshot. With wifi connection it's doing the same.

**Comment by MorrisJobke** [comment] 2017-04-10 02:25
Should be fixed in 11.0.3

**Comment by MorrisJobke** [comment] 2017-04-10 02:25
Duplicate of #3644

**Closed by MorrisJobke** 2017-04-10 02:25 UTC
