### ISSUE TITLE
NC 20 failed with errno=21 Is a directory at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#862

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#23079] opened 2020-09-28 15:35 UTC
Keep getting this error every time a folder is being deleted. Looks like this started happening PHP 7.4 its not happing on PHP 7.3 

![image](https://user-images.githubusercontent.com/59488153/94453328-298ff100-0176-11eb-8d82-7a2d3939a9f2.png)
![image](https://user-images.githubusercontent.com/59488153/94453363-3280c280-0176-11eb-90fb-ca351449034c.png)
![image](https://user-images.githubusercontent.com/59488153/94453284-1bda6b80-0176-11eb-9a71-8aaa9728feca.png)

#21578

**Comment by kesselb** [comment] 2020-09-29 09:04
Duplicate of #21578

**Closed by kesselb** 2020-09-29 09:05 UTC
Labels: 0. Needs triage, bug
