### ISSUE TITLE
continous added/deleted sync loop

### ISSUE THREAD

**Issue by RangerRick** [nextcloud/server#2169] opened 2016-11-16 17:28 UTC
I'm really not sure how many moving parts are related to this, but we are mostly Mac users with an internal nextcloud server.  We are using a mix of the nextcloud and owncloud sync clients.

### Steps to reproduce
1. User A configures the ownCloud client for Mac
2. User B configures the nextcloud client for Mac
3. User A pastes a directory full of files into the synced folder (CMD+C, CMD+V)
4. User A "shares" the directory to a group (`TOG`)
5. Every 5 minutes on User B's computer, the folder and files are synced, and then immediately deleted

### Expected behaviour
The files should sync once, and stay there.

### Actual behaviour
The files are continuously synced and then deleted.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MariaDB 10.0.27

**PHP version:** 7.0.8

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** zip file download from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - documents
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oczqfqizvq5x",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.20.1.18",
            "drive01.internal.opennms.com",
            "drive.opennms.com"
        ],
        "datadirectory": "\/var\/nextcloud",
        "overwrite.cli.url": "http:\/\/172.20.1.18",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "mdb01.internal.opennms.com",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "opennms.com",
        "mail_smtphost": "mail.opennms.com",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN"
    }
}
```
</details>

**Are you using external storage, if yes which one:** nfs-mounted onto the local nextcloud directory

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP (FreeIPA)

### NextCloud Client Log

<details>
<summary>nextcloud client log</summary>

```
11/16/16 12:14:13 PM,                                                           Logos,                     Nextcloud,        Deleted,
11/16/16 12:14:13 PM,                                        Upcoming Conferences.txt,                     Nextcloud,        Deleted,
11/16/16 12:09:50 PM,                                    Logos/two color whiteNMS.svg,                     Nextcloud,     Downloaded,      5 KB
11/16/16 12:09:49 PM,                                        Upcoming Conferences.txt,                     Nextcloud,     Downloaded,     171 B
11/16/16 12:09:48 PM,                                    Logos/two color whiteNMS.png,                     Nextcloud,     Downloaded,    168 KB
11/16/16 12:09:47 PM,                   Logos/opennnms connect meridian blue flat.svg,                     Nextcloud,     Downloaded,      8 KB
11/16/16 12:09:46 PM,                                     Logos/two color whiteNMS.ai,                     Nextcloud,     Downloaded,    204 KB
11/16/16 12:09:44 PM,                    Logos/opennnms connect meridian blue flat.ai,                     Nextcloud,     Downloaded,    365 KB
11/16/16 12:09:43 PM,                                     Logos/opennms white flat.ai,                     Nextcloud,     Downloaded,    207 KB
11/16/16 12:09:42 PM,                                    Logos/opennms black flat.svg,                     Nextcloud,     Downloaded,      5 KB
11/16/16 12:09:41 PM,                                     Logos/opennms black flat.ai,                     Nextcloud,     Downloaded,    209 KB
11/16/16 12:09:40 PM,                                Logos/opennms black flat RGB.png,                     Nextcloud,     Downloaded,    177 KB
11/16/16 12:09:39 PM,                                 Logos/opennms black flat RGB.ai,                     Nextcloud,     Downloaded,    210 KB
11/16/16 12:09:36 PM,                                       Logos/compass favicon.svg,                     Nextcloud,     Downloaded,     760 B
11/16/16 12:09:35 PM,                                    Logos/openNMSo flat green.ai,                     Nextcloud,     Downloaded,      1 MB
11/16/16 12:09:34 PM,                          Logos/opennms black flat RGB small.png,                     Nextcloud,     Downloaded,     21 KB
11/16/16 12:09:33 PM,                                    Logos/openNMSo flat blue.svg,                     Nextcloud,     Downloaded,     937 B
11/16/16 12:09:31 PM,                                       Logos/compass favicon.png,                     Nextcloud,     Downloaded,     60 KB
11/16/16 12:09:30 PM,                              Logos/openNMSo flat blue 140px.png,                     Nextcloud,     Downloaded,      4 KB
11/16/16 12:09:29 PM,                                     Logos/openNMSo flat blue.ai,                     Nextcloud,     Downloaded,      1 MB
11/16/16 12:09:28 PM,                                        Logos/compass favicon.ai,                     Nextcloud,     Downloaded,      2 MB
11/16/16 12:09:24 PM,                                                           Logos,                     Nextcloud,     Downloaded,
11/16/16 12:04:13 PM,                                                           Logos,                     Nextcloud,        Deleted,
11/16/16 12:04:13 PM,                                        Upcoming Conferences.txt,                     Nextcloud,        Deleted,
11/16/16 11:59:51 AM,                                        Upcoming Conferences.txt,                     Nextcloud,     Downloaded,     171 B
11/16/16 11:59:50 AM,                                    Logos/two color whiteNMS.svg,                     Nextcloud,     Downloaded,      5 KB
11/16/16 11:59:48 AM,                                     Logos/two color whiteNMS.ai,                     Nextcloud,     Downloaded,    204 KB
11/16/16 11:59:47 AM,                                    Logos/two color whiteNMS.png,                     Nextcloud,     Downloaded,    168 KB
11/16/16 11:59:46 AM,                   Logos/opennnms connect meridian blue flat.svg,                     Nextcloud,     Downloaded,      8 KB
11/16/16 11:59:45 AM,                    Logos/opennnms connect meridian blue flat.ai,                     Nextcloud,     Downloaded,    365 KB
11/16/16 11:59:44 AM,                                     Logos/opennms white flat.ai,                     Nextcloud,     Downloaded,    207 KB
11/16/16 11:59:42 AM,                                    Logos/opennms black flat.svg,                     Nextcloud,     Downloaded,      5 KB
11/16/16 11:59:41 AM,                                     Logos/opennms black flat.ai,                     Nextcloud,     Downloaded,    209 KB
11/16/16 11:59:40 AM,                                 Logos/opennms black flat RGB.ai,                     Nextcloud,     Downloaded,    210 KB
11/16/16 11:59:39 AM,                                Logos/opennms black flat RGB.png,                     Nextcloud,     Downloaded,    177 KB
11/16/16 11:59:38 AM,                          Logos/opennms black flat RGB small.png,                     Nextcloud,     Downloaded,     21 KB
11/16/16 11:59:36 AM,                                    Logos/openNMSo flat blue.svg,                     Nextcloud,     Downloaded,     937 B
11/16/16 11:59:34 AM,                                     Logos/openNMSo flat blue.ai,                     Nextcloud,     Downloaded,      1 MB
11/16/16 11:59:33 AM,                                    Logos/openNMSo flat green.ai,                     Nextcloud,     Downloaded,      1 MB
11/16/16 11:59:31 AM,                              Logos/openNMSo flat blue 140px.png,                     Nextcloud,     Downloaded,      4 KB
11/16/16 11:59:30 AM,                                       Logos/compass favicon.png,                     Nextcloud,     Downloaded,     60 KB
11/16/16 11:59:29 AM,                                       Logos/compass favicon.svg,                     Nextcloud,     Downloaded,     760 B
11/16/16 11:59:28 AM,                                        Logos/compass favicon.ai,                     Nextcloud,     Downloaded,      2 MB
11/16/16 11:59:25 AM,                                                           Logos,                     Nextcloud,     Downloaded,
```
</details>

**Comment by RangerRick** [comment] 2016-12-14 16:07
Hey, saw this hasn't been triaged yet and it's rolled off the list that anyone seems to have looked at.  Any ideas?  This is still happening for multiple users of our nextcloud instance.

**Comment by MorrisJobke** [comment] 2016-12-21 05:52
Maybe a duplicate of #2700

@RangerRick Are the affected users on different time zones?

**Comment by RangerRick** [comment] 2016-12-21 14:17
@MorrisJobke In this particular case no, the server, the person adding the files, and I are all in EST.

**Comment by skjnldsv** [comment] 2020-03-10 09:32
As I cannot reproduce the original issue anymore, I will close this ticket.
And as the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen

**Closed by skjnldsv** 2020-03-10 09:32 UTC
Labels: 0. Needs triage, bug, feature: filesystem
