### ISSUE TITLE
Problem with calendar invitation functionality

### ISSUE THREAD

**Issue by FoEE** [nextcloud/server#18750] opened 2020-01-08 13:53 UTC
### Steps to reproduce
1. User A is creating an event in his/her calendar and inviting B user. An event is added in A and B calendars.
2. User B is receiving an email with "Accept" and "Decline" buttons.
3. User B is clicking on "Decline" button. Nextcloud webpage is opening with a message "Your attendance was updated successfully".

### Expected behaviour
Event in user B calendar should be greyed out or event name strike-through. Also under event "More" menu, event should have "Cancelled" and not "Confirmed" status.

### Actual behaviour
Declined event in user B calendar remains confirmed with "Confirmed" status under "More", "Details". Cancelled event in user B calendar looks the same as all other events.

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
2.0.0-beta3

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
None.

### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 71

**Operating system:** (e.g. Arch Linux)
Windows 7

### Server configuration

**Operating system**: (e.g. Debian 8)
Centos 7.7.1908

**Web server:** (e.g. Apache, Nginx,...)
Apache

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
7.0.1

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
17.0.2

**Updated from an older installed version or fresh install:**
Updated from an older installed version

**List of activated apps:**
- accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - apporder: 0.9.0
  - bruteforcesettings: 1.4.0
  - calendar: 2.0.0-beta3
  - cloud_federation_api: 1.0.0
  - cms_pico: 1.0.4
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - deck: 0.7.0
  - drawio: 0.9.4
  - external: 3.4.1
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - onlyoffice: 4.0.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 3,
        "enable_previews": true,
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/REMOVED",
        "logtimezone": "Europe\/Berlin",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "lost_password_link": "disabled",
        "app_install_overwrite": [
            "apporder",
            "calendar",
            "deck",
            "drawio",
            "external",
            "files_markdown",
            "onlyoffice",
            "cms_pico",
            "spreed",
            "tasks"
        ],
        "data-fingerprint": "fd295acd8d5ba9f07aacc987e4345077"
    }
}

#### Web server error log (e.g. /var/log/apache)
No errors in Apache log

#### Log file (data/nextcloud.log)
No errors in nextcloud.log

#### Browser log
-
=======
It looks to me that similar issue had been reported for calendar v.1.x.x 
It is not clear to me is this the right place for reporting issues for both calendar versions 1.x and 2.x or just for v1.x

**Comment by joern45219** [comment] 2020-11-05 18:39
Was anyone yet able to solve this? 
Would be such great if it would be possible that 
a) the links in the HTML mail copy the event to the recipients calendar
b) the sender receives an email of acceptance / decline of the recipient 
c) in case of decline the event becomes marked in the senders calender. 

Thankful for any help / update
Joern

**Comment by skjnldsv** [comment] 2020-11-07 22:19
duplicate of https://github.com/nextcloud/server/issues/17915

**Closed by skjnldsv** 2020-11-07 22:19 UTC
Labels: 0. Needs triage, bug, feature: dav
