### ISSUE TITLE
Dark theme: not all text displaying

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/server#14071] opened 2019-02-06 18:32 UTC
When enabling the dark theme, some of the text does not display as the font colour is set to black, and not white. For instance, the `Modified` column. The heading displays because the font colour is white, but the details in the column is in black ,so you cannot see what it is.

**Comment by hanserasmus** [comment] 2019-02-07 07:55
![image](https://user-images.githubusercontent.com/24249616/52397380-f8087480-2abd-11e9-87c1-17e13590d91d.png)
There is an example of it.

Also I realised that some other little buttons also disappears on dark theme. For instance, when selecting folders, the following happens:

![image](https://user-images.githubusercontent.com/24249616/52397441-4584e180-2abe-11e9-8abf-cf51532aca51.png)

See how the `...` is "missing" next to Actions. I know this has all to do with colours etc, unfortunately I do not possess the ability to fix this and submit a PR.

**Comment by Lartza** [comment] 2019-02-09 08:33
First part at least is duplicate of https://github.com/nextcloud/server/issues/14003

**Comment by BornToBeRoot** [comment] 2019-03-02 01:34
Same issue on Nextcloud 15.0.5
![image](https://user-images.githubusercontent.com/16019165/53675009-b15c0380-3c92-11e9-9813-fbacb84d8f9c.png)

Sometimes the color is white, sometimes black (not readable).

There is also a difference between the gray accent:

![image](https://user-images.githubusercontent.com/16019165/53675028-ee27fa80-3c92-11e9-9020-b4b736b3f20f.png)

**Comment by skjnldsv** [comment] 2020-11-07 23:45
Actually this is fixed

**Closed by skjnldsv** 2020-11-07 23:45 UTC
Labels: 1. to develop, bug, design, good first issue
