### ISSUE TITLE
User Quota Dropdown Options and Groups Option Clips Through User List

### ISSUE THREAD

**Issue by SalmonSays** [nextcloud/server#19887] opened 2020-03-11 09:45 UTC
### Steps to reproduce
As an admin, go to the Users menu. When multiple users are added, choose the "Edit User" pencil icon on a user in the upper part of the list. Click on the "Quota" field and attempt to select any of the size presets.

### Expected behaviour
The dropdown menu should appear and allow selection of a size preset.

### Actual behaviour
The dropdown menu appears, but obscured by elements on the forefront of the webpage in a way that prevents clicking/selecting of options. Using arrow keys is a temporary workaround, and the bottom most user in a list of users doesn't appear to suffer from this problem. A sample image is supplied here demonstrating the issue: https://i.imgur.com/qfZ56kx.png

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, json, igbinary, apcu, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, redis, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from v18

**Where did you install Nextcloud from:** https://www.hanssonit.se/nextcloud-vm/

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - announcementcenter: 3.7.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - cookbook: 0.5.7
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_downloadactivity: 1.7.0
 - files_external: 1.9.0
 - files_fulltextsearch: 1.4.1
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.7.0
 - files_photospheres: 1.0.7
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - fulltextsearch: 1.4.1
 - fulltextsearch_elasticsearch: 1.5.0
 - groupfolders: 6.0.1
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - audioplayer
 - encryption
 - files_trashbin
 - files_versions
 - mail
 - notes
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.55.57",
        "cloud.smisc.net",
        "cloud.smisc.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "18.0.1.3",
    "overwrite.cli.url": "https:\/\/cloud.smisc.net\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "upgrade.disable-web": "true",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": "2",
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "43200",
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 180",
    "versions_retention_obligation": "auto, 365",
    "simpleSignUpLink.shown": "false",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "logtimezone": "US\/Central",
    "htaccess.RewriteBase": "\/",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\SVG",
        "OC\\Preview\\TIFF"
    ],
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "maintenance": false,
    "app_install_overwrite": [
        "files_reader"
    ],
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Chrome 80.0.3987.132 (Official Build) (64-bit)

**Operating system:** Windows 10 Pro v1909

## Logs

<details><summary>Web server error log</summary>

```
N/A
```
</details>

<details><summary>Nextcloud log</summary>

```
N/A
```
</details>

<details><summary>Browser log</summary>

N/A
</details>

**Comment by kesselb** [comment] 2020-03-11 10:04
Duplicate of #19881

**Closed by kesselb** 2020-03-11 10:04 UTC
Labels: 0. Needs triage, bug
