### ISSUE TITLE
Can't create user without password if minimal lenght is >8 – NC 17.0.1 Regression?

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#18127] opened 2019-11-27 00:51 UTC
### Steps to reproduce
1. set password policy to 8 characters (default)
2. create a new user leaving Password empty
3. set password policy to 9 characters
4. create a new user leaving Password empty

### Expected behaviour
In both cases, the user should be created and get a welcome email telling him to set his password.

### Actual behaviour
While this works for up to "8", minimal password length >8 leads to a "password must be at least … characters" warning. But this used to work in NV 16.0.5 – with >8 being set!

### Remarks
- The password policy should be enforced when actually SETTING the password. It should be possible to create a user even if more restrictions are set!
- The password policy seems to be enforced at different places since it's possible to create a user without setting his password in the Web UI if "enforce caps and small letters" is active, but fails with the same setting when using the API or OCC.
- It should be possible to create a user in OCC without setting his password. It seems as if OCC requires a password. Not 100% sure though.

**Comment by szaimen** [comment] 2021-05-27 11:48
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 11:48 UTC
Labels: 0. Needs triage, bug

**Comment by nursoda** [comment] 2021-05-27 12:27
Interesting – I just had the issue yesterday evening again, in NC 21.0.2: I could not create a new user without entering a password.

However, I'd rather re-test and proof / trail – how?

**Comment by szaimen** [comment] 2021-05-27 12:29
What you are refering to is this issue: https://github.com/nextcloud/server/issues/16465

**Comment by nursoda** [comment] 2021-05-27 12:46
No. I also just commented there. My issue was that if I leave all security policies set to default and create a user, I did not have to enter an password for that user. Instead, the new user received an welcome email that asked him to set up his password. If I modified the security settings, this didn't work any more – the password policy was enforced.

However, as I said, I needed to reproduce that, and I just did. Turns out the issue I just described in fact does NOT happen (any more). Maybe it never did: I might be that I forgot to enter an e-mail address when I first encountered the issue and posted it here. Anyway: If there's no e-mail address, the system obviously cannot tell the user to set up a password, so it's fair that the admin should enter one. Only the wording of the warning might be improved (UI enhancement): Today, it just says "Please fill in this field." Better would be "Please provide a password or an email address." IF I provide username, name and email, then the user is created although I have a custom password policy.
