### ISSUE TITLE
Dashboard Recent Bug

### ISSUE THREAD

**Issue by BBGamingNL** [nextcloud/server#27106] opened 2021-05-25 19:51 UTC
At my dashboard and then statuses recent, when I press the 3 dots. The text comes below the wrap-up

**Comment by gary-kim** [comment] 2021-05-27 04:38
This seems to have been fixed by https://github.com/nextcloud/nextcloud-vue/pull/831. Could you try again on master?

**Comment by BBGamingNL** [comment] 2021-05-27 07:09
> This seems to have been fixed by https://github.com/nextcloud/nextcloud-vue/pull/831. Could you try again on master?

what do you mean by master. the admin account?

**Comment by gary-kim** [comment] 2021-05-27 16:45
The latest development version. If you don't have a dev instance set up, you can try out one of the master dailies on here: https://download.nextcloud.com/server/daily/

**Comment by PVince81** [comment] 2021-06-30 15:53
The issue is likely fixed, please try again with NC 21.0.2.
If the issue persists, feel free to reopen and use the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) to provide more details.

**Closed by PVince81** 2021-06-30 15:53 UTC

**Comment by BBGamingNL** [comment] 2021-08-18 18:22
I did an update and got the problem again

![Status bug](https://user-images.githubusercontent.com/84809109/129951597-b4b50034-ccb9-445a-9fe1-6e4973f5095f.png)
