### ISSUE TITLE
Is there any file chooser for nextcloud

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/server#6911] opened 2017-10-23 10:59 UTC
### Expected behaviour
There should be a button like ``Choose from Nextcloud`` that when a user clicks that, another window is promoted to the user and she can select 1 or more files.  
This feature is already enabled on Dropbox & Google drive but can't find any documentation for Nextcloud.
For clarification screenshot from drive is included.
Is this feature implemented for nextcloud? any roadmap? 
![picker-2015](https://user-images.githubusercontent.com/13661520/31885745-72ff23a2-b7fe-11e7-834c-45c124075e41.png)

**Operating system**:
Windows

**Web server:**
Centos7

**Database:**
Sqlite

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Comment by leonklingele-work** [comment] 2017-10-23 11:08
> This feature is already enabled on Dropbox & Google drive

Where is such a "Choose from Google Drive" button currently shown?
Where would you expect a "Choose from Nextcloud" button to be shown?

**Comment by mehrdaad** [comment] 2017-10-23 11:17
> Where is such a "Choose from Google Drive" button currently shown?  
    Any web application that has enabled uploading file from Google drive.
> Where would you expect a "Choose from Nextcloud" button to be shown?  
   Currently trying to attach a file from Nextcloud in the rainloop app.

**Comment by leonklingele-work** [comment] 2017-10-23 11:22
Given that Nextcloud is self-hosted, how would your app know which Nextcloud service (= domain) to call? Why not create an individual browser extension / Tampermonkey script?

**Comment by mehrdaad** [comment] 2017-10-23 11:32
> Given that Nextcloud is self-hosted, how would your app know which Nextcloud service (= domain) to call? 

Just as Dropbox, Google drive handles it. There's nothing special about Nextclou(At least I think this way).  
If Dropbox & Google drive supports a file chooser, then I think it won't be a hard thing for nextcloud developers to add this feature too.
> Why not create an individual browser extension / Tampermonkey script?  
Can you describe how would that script communicate with Nextcloud and get a list of files?  
How would it handle file downloads from Nextcloud after choosing this file?  
I do believe that this kinda communication is handled through WebDAV protocol.  
Further information is appreciated.

**Comment by mehrdaad** [comment] 2017-10-23 11:48
Or Nextcloud could provide OAuth2 authentication just as other services do.  
Clients register by Client id, Client secret, API Key.

**Comment by juliusstoerrle** [comment] 2017-10-23 16:11
One use case I have is actually for other company internal services. In such a case we also don't have the problem @leonklingele-work mentioned, as we can configure other services with our data.

What i have been thinking about was just creating a Javascript WebDav File Client, which can connect to any WebDav Server but can be configured to only allow a given instance. But that wouldn't be in the scope of nextcloud/server. But some SSO Solution would be interesting too.

i don't have enough technical insights in how Google API is displaying that picker, but just for ref i'm linking the API Doc: https://developers.google.com/picker/docs/

**Comment by blizzz** [comment] 2017-10-24 10:46
> Or Nextcloud could provide OAuth2 authentication just as other services do.
Clients register by Client id, Client secret, API Key.

It does. Implemented as core app since 12, I believe.

**Comment by mehrdaad** [comment] 2017-10-24 10:58
@blizzz so it doesn't provide any native file chooser for external apps, right?

**Comment by blizzz** [comment] 2017-10-24 11:16
No, there isn't any I know about. The moodle integration for instances takes the OAuth2 approach.

**Comment by MorrisJobke** [comment] 2017-10-27 10:58
Duplicate of #2028

**Closed by MorrisJobke** 2017-10-27 10:58 UTC
Labels: enhancement

**Comment by mehrdaad** [comment] 2017-10-27 11:09
@MorrisJobke I opened this issues since the references issue hasn't got any remarkable answer.  
I see this act of closing issues without providing any meaningful solution and referencing an unsolved issue so carelessly.

**Comment by MorrisJobke** [comment] 2017-10-27 11:17
> @MorrisJobke I opened this issues since the references issue hasn't got any remarkable answer.
> I see this act of closing issues without providing any meaningful solution and referencing an unsolved issue so carelessly.

Why is this carelessly? We actually care a lot about a good to use bug tracker. Why should we keep 5 discussions about one specific topic open? We should join discussions and closing a ticket as duplicate is such.

We can not implement every single feature request immediately. Just because nothing is happening in a ticket does not mean we don't care about it. We just don't have time now to work on it, but everybody is welcome to propose a possible solution and then we can give feedback.

So please continue the discussion in #2028 - but avoid to just say "I want this too", because this does not drive the discussion forward (use github reactions for this).

**Comment by mehrdaad** [comment] 2017-10-28 08:02
@MorrisJobke sure there shouldn't be duplicate for a feature request but as I didn't see any reaction by Nextcloud core maintainers on that issue, I decided to open another one.  
Maybe providing a roadmap for implmenting such features would be great.  
Also I think this feature is a top wanted since many companies who provide self hosted cloud service also have other products which they wish to integrate them with nextcloud.  
Nextcloud provides WebDAV but for me I couldn't find any way to integrate WebDAV with a file chooser to select multiple files to upload or select.  
Maybe I can help with developing this feature if you list requirement and a high level overview of how such feature works.  
Regards.

**Comment by MorrisJobke** [comment] 2017-10-28 10:18
> Maybe providing a roadmap for implmenting such features would be great.

We put it on our roadmap once we plan to implement it.

> Also I think this feature is a top wanted since many companies who provide self hosted cloud service also have other products which they wish to integrate them with nextcloud.
> Nextcloud provides WebDAV but for me I couldn't find any way to integrate WebDAV with a file chooser to select multiple files to upload or select.
> Maybe I can help with developing this feature if you list requirement and a high level overview of how such feature works.
> Regards.

Then please comment like this in that ticket. That helps to triage.
