### ISSUE TITLE
Overlapping fonts on Group list

### ISSUE THREAD

**Issue by TechnoWolfEver** [nextcloud/server#35601] opened 2022-12-03 17:22 UTC
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating to update 25.0.1 the list of groups started glitching with overlapping Fonts.
https://gyazo.com/eb82ee49ffa2a3cc26fe2bc55b8e03ac

### Steps to reproduce

Have alot of groups
click on group list

### Expected behavior

List correctly

### Which files are affected by this bug

Group list

### Operating system

Windows

### Which version of the operating system you are running.

Brave Browser - MacOs Ventura 13.01

### Package

Other

### Nextcloud Server version

25.0.1

### Nextcloud Desktop Client version

/

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by bbx-github** [comment] 2022-12-06 23:14
This is probably a duplicate of #34784

**Comment by joshtrichards** [comment] 2023-09-03 20:15
Duplicate of #34784 (and also since fixed). Closing.

**Closed by joshtrichards** 2023-09-03 20:15 UTC
Labels: 0. Needs triage
