### ISSUE TITLE
Cannot view images stored in sftp external storage. Downloading results in empty/tiny files. 

### ISSUE THREAD

**Issue by severus-tux** [nextcloud/server#22223] opened 2020-08-12 18:53 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Enable server side encryption with default encryption module
2. Go to External storage under Administration tools
3. Add a new sftp server
   - authentication method as "public key".
   - Generate a new key in the same page using the button <kbd>Generate</kbd>
   - Add it to the sftp server to allow nextcloud. 
   - Enable encryption
![Screenshot from 2020-08-12 23-21-45](https://user-images.githubusercontent.com/21301040/90050162-72d5cf80-dcf3-11ea-9f7f-d22853d8e944.png)
![Screenshot from 2020-08-12 23-21-55](https://user-images.githubusercontent.com/21301040/90050193-7c5f3780-dcf3-11ea-844e-5d983e63ae2f.png)

### Expected behaviour
When files are uploaded from nextcloud, it should be viewable on nextcloud. How ever it should be encrypted if accessed directly (bypassing nextcloud). Normal file version control too.

### Actual behaviour
When I upload anything, say couple of images, it gets uploaded. But, when tried to view on nextcloud, it cant view it. It shows
![Screenshot from 2020-08-12 23-30-09](https://user-images.githubusercontent.com/21301040/90050845-69993280-dcf4-11ea-8ed3-7a1f086fa7b6.png)

Thumnails are not loaded either. Also, as you can see in the following screenshot, file size of an image is 104KB. But when I try to download the same image, what gets downloaded is a 4.5KB file with the same name. 
![Screenshot from 2020-08-12 23-33-06](https://user-images.githubusercontent.com/21301040/90051265-0cea4780-dcf5-11ea-803d-2279f4e3c3bf.png)
![Screenshot from 2020-08-12 23-34-11](https://user-images.githubusercontent.com/21301040/90051398-428f3080-dcf5-11ea-9895-acb1286b162f.png)

With text files, it shows
![Screenshot from 2020-08-13 01-22-55](https://user-images.githubusercontent.com/21301040/90062235-fba93700-dd04-11ea-9761-8860b37f5308.png)
But I haven't even touched it outside of nextcloud.

### To be noted
The exact same thing happns when encryption is disabled. That is, images are not viewable, downloading results in small/empty files downloaded. But, the files uploaded via nextcloud are accessable and images are viewable on the sftp server when accessed directly.

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache/2.4.41

**Database:** mysql  Ver 15.1 Distrib 10.3.22-MariaDB 

**PHP version:** 7.4.3

**Nextcloud version:** 19.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_audit: 1.9.0
  - bookmarks: 3.3.3
  - breezedark: 19.0.4
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - cospend: 1.0.5
  - dav: 1.15.0
  - deck: 1.0.5
  - encryption: 2.7.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - guests: 1.4.6
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - news: 14.1.11
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.1
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.3
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.3
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - accessibility
  - activity
  - announcementcenter
  - end_to_end_encryption
  - forms
  - richdocuments
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "139.180.144.78",
            "cloud.morty.us.to"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/"
    }
}

```
</details>

**Are you using external storage, if yes which one:** SFTP

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser :** Mozilla Firefox 79.0

**Operating system:**  5.4.52-1-MANJARO

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Wed Aug 12 00:00:03.195154 2020] [ssl:warn] [pid 77407] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server n>
[Wed Aug 12 00:00:03.196646 2020] [mpm_prefork:notice] [pid 77407] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operat>
[Wed Aug 12 00:00:03.196658 2020] [core:notice] [pid 77407] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 12 01:07:45.480966 2020] [access_compat:error] [pid 96934] [client 172.93.xxx.xxx:43282] AH01797: client denied by server configuration: /var/ww>
[Wed Aug 12 05:39:08.312752 2020] [access_compat:error] [pid 97962] [client 172.93.xxx.xxx:49008] AH01797: client denied by server configuration: /var/ww>
[Wed Aug 12 06:16:26.632524 2020] [access_compat:error] [pid 100011] [client 157.49.xxx.xxx:31077] AH01797: client denied by server configuration: /var>
[Wed Aug 12 12:19:01.943331 2020] [access_compat:error] [pid 103369] [client 157.49.xxx.xxx:13412] AH01797: client denied by server configuration: /va>
[Wed Aug 12 16:45:47.345847 2020] [access_compat:error] [pid 104391] [client 185.39.xxx.xxx:58602] AH01797: client denied by server configuration: /var>
[Wed Aug 12 18:20:01.032304 2020] [access_compat:error] [pid 109337] [client 157.49.xxx.xxx:32754] AH01797: client denied by server configuration: /va>


```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"IBSMGlF3ymMs6I8lxYkO","level":3,"time":"2020-08-12T18:06:42+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&c=5f342faf8a46a&x=250&y=250&forceIcon=0","message":"fopen(sftpread://home/xxx/vishwa/nextcloud_data//rmback.jpg): failed to open stream: &quot;OCA\\Files_External\\Lib\\Storage\\SFTPReadStream::stream_open&quot; call failed at /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php#378","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"IBSMGlF3ymMs6I8lxYkO","level":3,"time":"2020-08-12T18:06:42+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&c=5f342faf8a46a&x=250&y=250&forceIcon=0","message":"fread() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#861","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"IBSMGlF3ymMs6I8lxYkO","level":3,"time":"2020-08-12T18:06:42+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&c=5f342faf8a46a&x=250&y=250&forceIcon=0","message":"fclose() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#862","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"IBSMGlF3ymMs6I8lxYkO","level":3,"time":"2020-08-12T18:06:42+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&c=5f342faf8a46a&x=250&y=250&forceIcon=0","message":"fread(): Length parameter must be greater than 0 at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#91","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"zL6IzsvPK9FH6FnW8rP7","level":3,"time":"2020-08-12T18:06:47+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2FCMI&files=rmback.jpg&downloadStartSecret=09i3v6l82bdm","message":"Expected SSH_FXP_STATUS at /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php#2123","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"zL6IzsvPK9FH6FnW8rP7","level":3,"time":"2020-08-12T18:06:48+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2FCMI&files=rmback.jpg&downloadStartSecret=09i3v6l82bdm","message":"fopen(sftpread://home/xxx/vishwa/nextcloud_data//rmback.jpg): failed to open stream: &quot;OCA\\Files_External\\Lib\\Storage\\SFTPReadStream::stream_open&quot; call failed at /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php#378","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"zL6IzsvPK9FH6FnW8rP7","level":3,"time":"2020-08-12T18:06:48+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2FCMI&files=rmback.jpg&downloadStartSecret=09i3v6l82bdm","message":"fread() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#861","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"zL6IzsvPK9FH6FnW8rP7","level":3,"time":"2020-08-12T18:06:48+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2FCMI&files=rmback.jpg&downloadStartSecret=09i3v6l82bdm","message":"fclose() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#862","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"zL6IzsvPK9FH6FnW8rP7","level":3,"time":"2020-08-12T18:06:48+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2FCMI&files=rmback.jpg&downloadStartSecret=09i3v6l82bdm","message":"fread(): Length parameter must be greater than 0 at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#91","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"zL6IzsvPK9FH6FnW8rP7","level":3,"time":"2020-08-12T18:06:48+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"no app in context","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2FCMI&files=rmback.jpg&downloadStartSecret=09i3v6l82bdm","message":{"Exception":"OCP\\Encryption\\Exceptions\\GenericEncryptionException","Message":"Missing Signature","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php","line":532,"function":"hasSignature","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->"},{"file":"/var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php","line":460,"function":"splitMetaData","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->"},{"file":"/var/www/nextcloud/apps/encryption/lib/Crypto/Encryption.php","line":375,"function":"symmetricDecryptFileContent","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Stream/Encryption.php","line":501,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/Encryption.php","line":299,"function":"readCache","class":"OC\\Files\\Stream\\Encryption","type":"->"},{"function":"stream_read","class":"OC\\Files\\Stream\\Encryption","type":"->"},{"file":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php","line":91,"function":"fread"},{"file":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php","line":98,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->"},{"function":"stream_read","class":"Icewind\\Streams\\CallbackWrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":429,"function":"fread"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Files.php","line":352,"function":"readfile","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Files.php","line":122,"function":"getSingleFile","class":"OC_Files","type":"::"},{"file":"/var/www/nextcloud/apps/files/ajax/download.php","line":64,"function":"get","class":"OC_Files","type":"::"},{"file":"/var/www/nextcloud/lib/private/Route/Route.php","line":156,"args":["/var/www/nextcloud/apps/files/ajax/download.php"],"function":"require_once"},{"function":"OC\\Route\\{closure}","class":"OC\\Route\\Route","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/encryption/lib/Crypto/Crypt.php","Line":569,"Hint":"Missing Signature","CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"1Yw4TorhZ2KMwEYWUgDU","level":3,"time":"2020-08-12T18:34:28+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&x=32&y=32","message":"Expected SSH_FXP_STATUS at /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php#2123","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"1Yw4TorhZ2KMwEYWUgDU","level":3,"time":"2020-08-12T18:34:28+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&x=32&y=32","message":"fopen(sftpread://home/xxx/vishwa/nextcloud_data//rmback.jpg): failed to open stream: &quot;OCA\\Files_External\\Lib\\Storage\\SFTPReadStream::stream_open&quot; call failed at /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php#378","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"1Yw4TorhZ2KMwEYWUgDU","level":3,"time":"2020-08-12T18:34:28+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&x=32&y=32","message":"fread() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#861","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"1Yw4TorhZ2KMwEYWUgDU","level":3,"time":"2020-08-12T18:34:28+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&x=32&y=32","message":"fclose() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#862","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}
{"reqId":"1Yw4TorhZ2KMwEYWUgDU","level":3,"time":"2020-08-12T18:34:28+00:00","remoteAddr":"157.49.xxx.xxx","user":"vishwa","app":"PHP","method":"GET","url":"/core/preview?fileId=20659&x=32&y=32","message":"fread(): Length parameter must be greater than 0 at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#91","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"19.0.1.1"}


Formatted version:

[PHP] Error: fread(): Length parameter must be greater than 0 at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#91

GET /core/preview?fileId=20659&x=32&y=32
from 157.49.xxx.xxx by vishwa at 2020-08-12T18:34:28+00:00

[PHP] Error: fclose() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#862

GET /core/preview?fileId=20659&x=32&y=32
from 157.49.xxx.xxx by vishwa at 2020-08-12T18:34:28+00:00

[PHP] Error: fread() expects parameter 1 to be resource, bool given at /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#861

GET /core/preview?fileId=20659&x=32&y=32
from 157.49.xxx.xxx by vishwa at 2020-08-12T18:34:28+00:00

[PHP] Error: fopen(sftpread://home/students/vishwa/nextcloud_data//rmback.jpg): failed to open stream: &quot;OCA\Files_External\Lib\Storage\SFTPReadStream::stream_open&quot; call failed at /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php#378

GET /core/preview?fileId=20659&x=32&y=32
from 157.49.xxx.xxx by vishwa at 2020-08-12T18:34:28+00:00

[PHP] Error: Expected SSH_FXP_STATUS at /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php#2123

GET /core/preview?fileId=20659&x=32&y=32
from 157.49.xxx.xxx by vishwa at 2020-08-12T18:34:28+00:00

[PHP] Error: Expected SSH_FXP_STATUS at /var/www/nextcloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php#2123

GET /core/preview?fileId=20659&x=32&y=32
from 157.49.xxx.xxx by vishwa at 2020-08-12T18:34:28+00:00


[PHP] Error: Trying to access array offset on value of type bool at /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php#334

PUT /remote.php/webdav/CMI/rmback.jpg
from 157.49.xxx.xxx by vishwa at 2020-08-12T18:06:38+00:00
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
I don't think this is need. The issues happens on all clients - desktop, android etc.. Let me know if it is needed
```
</details>

**Comment by kesselb** [comment] 2020-08-12 19:37
cc @icewind1991 @rullzer

**Comment by Bables55** [comment] 2020-08-31 00:53
I have a similar problem. I can browse files when I connect with SFTP, but I can't open them. This has been occurring since NC 19.0.0.

> fopen(sftpread://EXTERNAL-STORAGE-PATH/NC-USER-NAME//sample.jpg): failed to open stream:
I think the problem is that when I look at the NC error log, I see two consecutive slashes after the NC username.

**Comment by szaimen** [comment] 2021-06-09 13:45
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by Chr157i4n** [comment] 2021-07-21 01:31
This issue is still valid in NC22.0.0.11.
encryption on local storage works fine. Encryption on sftp storage fails with the error:

Error: fopen(sftpread://mnt/WD_Elements/Nextcloud/encrypted//test.txt): Failed to open stream

Replacing the double slash before the file name with a single one (as mentioned here https://github.com/nextcloud/server/issues/22223#issuecomment-683497335), didnt fix it.

**Comment by szaimen** [comment] 2023-01-23 10:08
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Closed** 2023-03-06 13:41 UTC
Labels: bug, needs info, feature: encryption (server-side), feature: external storage, 0. Needs triage
