### ISSUE TITLE
Nextcloud 16.0.2 Update: File Integrity Warning, .htaccess

### ISSUE THREAD

**Issue by kneiser** [nextcloud/server#16294] opened 2019-07-08 13:31 UTC
### Steps to reproduce
Did an in place update. Then had this occur: "some users reported file integrity warnings related to cypress which can be resolved by deleting the cypress.json and the cypress folder in the /apps/viewer/ folder."
I removed as recommended.
Did apache2 restart.
Checked Overview in Settings, and has a file integretiy error.
Did some research, obtained the .htaccess file from the 16.0.2 update and replaced the existing one. I had not modified the .htaccess in anyway after the update.

### Expected behaviour
No Errors

### Actual behaviour

The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f30494d88fc2d7caf0be8b27629cb246483cea0203696e44fd376bff19db51bb89c9f4076b1f849627ef3cb011f4a20088116e7b0d10ce467a3dde5db71e108b
                            [current] => f4761be41a972d398ac291245e48660cc2edaaa1b31cacbe319b0896e91794c73a4ee0cc7b1784b5b00c968c5f2874f458f7f610602ebf5700107de9d27b2eac
                        )

                )

        )

## Server configuration detail

**Operating system:** Linux 4.9.0-9-686-pae #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) i686

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.38

**PHP version:** 

7.2.19-1+0~20190531112637.22+stretch~1.gbp75765b
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 16.0.2 - 16.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 16.0.0

**Where did you install Nextcloud from:** Nexcloud GUI Updater

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [x.htaccess] => Array
                        (
                            [expected] => 
                            [current] => 99efefd58017eea16fbbb060ac54abc366123f33aeceeb42b24ae98846dd56c5fc5cbf2b1be80f166c20c174fc07bcb98c73a52e2e13ea784281c54525bb0625
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - admin_audit: 1.6.0
 - apporder: 0.7.1
 - audioplayer: 2.7.2
 - bookmarks: 1.0.6
 - bruteforcesettings: 1.3.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - deck: 0.6.4
 - drawio: 0.9.3
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_ebookreader: 0.0.1
 - files_external: 1.7.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.5.0
 - files_readmemd: 1.1.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_videoplayer: 1.5.0
 - flowupload: 0.1.2
 - gallery: 18.3.0
 - groupfolders: 4.0.3
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - text: 1.0.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - weather: 1.6.1
 - workflowengine: 1.6.0
Disabled:
 - activity
 - encryption
 - files_versions
 - firstrunwizard
 - nextcloud_announcements
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.0.244",
        "192.168.0.240"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/192.168.0.240:443",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "16.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "log_rotate_size": "100 MiB",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "maintenance": false,
    "trashbin_retention_obligation": "auto, 7",
    "defaultapp": "apporder",
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "groupfolders",
        "weather"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0

**Operating system:** Debian GNU/Linux 9.9 (stretch)

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by georgehrke** [comment] 2019-07-08 14:05
Duplicate of https://github.com/nextcloud/server/issues/16229

Please search for existing issues before creating new ones!

**Closed by georgehrke** 2019-07-08 14:05 UTC
