### ISSUE TITLE
Errors on relatively new install

### ISSUE THREAD

**Issue by Germs2004** [nextcloud/server#10301] opened 2018-07-19 19:57 UTC
I'm a new user, just started with a fresh appliance from "Tech and Me", and did a few little changes to settings and apps.  When browsing the settings, I found these in settings/admin/logging already.  Being a new user, I'm not motivated to provide much more help yet, so I hope these errors are enough to point you in the right direction.

I have dozens of these errors:
`PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20170718/redis.so (/usr/lib/php/20170718/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20170718/redis.so.so (/usr/lib/php/20170718/redis.so.so: cannot open shared object file: No such file or directory)) at Unknown#0`

I have two of these errors, which may be related to me trying to delete the two default folders and failing (Documents and Photos):
`Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache" ("mimepart","mimetype","mtime","size","etag","storage_mtime","permissions","checksum","path_hash","path","parent","name","storage") SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM "oc_filecache" WHERE "storage" = ? AND "path_hash" = ? HAVING COUNT(*) = 0' with params [1, 2, 1532029376, -1, "5b50e9c031a07", 1532029376, 31, "", "fb66dca5f27af6f15c1d1d81e6f8d28b", "files_trashbin", 222, "files_trashbin", 5, 5, "fb66dca5f27af6f15c1d1d81e6f8d28b"]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "fs_storage_path_hash" DETAIL: Key (storage, path_hash)=(5, fb66dca5f27af6f15c1d1d81e6f8d28b) already exists.`

I have one of these errors:
`Error: Call to a member function addUser() on boolean`

**Comment by MorrisJobke** [comment] 2018-07-24 12:11
> PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20170718/redis.so (/usr/lib/php/20170718/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20170718/redis.so.so (/usr/lib/php/20170718/redis.so.so: cannot open shared object file: No such file or directory)) at Unknown#0

Setup issue - needs to be fixed on the server.



> Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO "oc_filecache"

Duplicate of #6160



> Error: Call to a member function addUser() on boolean

Too little information. Looks like the cron error output that we fixed in a recent version (13.0.5 AFAIK but could also be the upcoming 14.0.0)

**Closed by MorrisJobke** 2018-07-24 12:11 UTC
Labels: bug

**Comment by enoch85** [comment] 2018-08-08 21:18
> PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/lib/php/20170718/redis.so (/usr/lib/php/20170718/redis.so: undefined symbol: igbinary_serialize), /usr/lib/php/20170718/redis.so.so (/usr/lib/php/20170718/redis.so.so: cannot open shared object file: No such file or directory)) at Unknown#0

Hey @Germs2004, sorry for the late reply. 

That's because the package from Ubuntu needs to be updated. It works but gives the mentioned output.

We used PECL to install Redis before in the VM, but chose to revert back to the package provided by the OS because of several reasons. One was common setup errors by users when Redis gave people options to upgrade it (build it again) with different settings, so stuff got wrong and resulted in issue reports.

If the package doesn't get upgraded and it becomes an error, then of course we will fix it. Already thinking of reverting to PECL because of issue reports like these.

And please report errors regarding the VM [here](https://github.com/nextcloud/vm) instead. Thanks! :+1:
