### ISSUE TITLE
Search filter not removed after navigating to a new folder

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#30756] opened 2022-01-19 09:46 UTC
Tested in c.nc.com (version 23.0.0)

1. Go to a random folder, here is an example:

![grafik](https://user-images.githubusercontent.com/1589737/150104885-778ff3b8-7a92-49a3-8c2b-1962517a0ab0.png)

2. In this case I search for "demo" and the file listing gets filtered as expected:

![grafik](https://user-images.githubusercontent.com/1589737/150105015-6810ad51-fb6f-4a94-b3c8-f6600a934d73.png)

3. Now I found my search result, the "demo"-folder, I click on it to navigate to the folder, and see the following:

![grafik](https://user-images.githubusercontent.com/1589737/150105153-dc4f87b5-df32-4f4a-a1fb-01a6321c7ac5.png)

As you can see, the filter for "demo" is still applied. In this case I see the file where the filename matches. If there wouldn't be a match the listing would be completely empty. Which is quite irritating

What I would expect is, that navigating to a folder clears the filter so that I see the whole listing without having to re-load the view:

![grafik](https://user-images.githubusercontent.com/1589737/150105449-b7da7154-1037-4ec9-9b23-8e63fc25c27a.png)

**Comment by felag** [comment] 2022-02-23 09:25
Same here: I second this bug report. :-)

**Comment by felag** [comment] 2022-02-23 09:50
@schiessle Please note: if you clic on Demo folder **on search result pane**, then your search filter is removed.

As long as you clic on "main" files pane, then your search filter stay present.

For me it is now a feature, not a bug (both behavior are possible: keep or remove search filter depending where I clic on folder). :)

**Comment by th0ger** [comment] 2022-06-28 08:26
It's quite problematic that the unified search bar can have an active filter - but it's not directly visible that is does.

**Comment by maximelehericy** [comment] 2022-07-04 12:58
smae here

**Comment by szaimen** [comment] 2023-01-23 12:56
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by skjnldsv** [comment] 2024-07-31 16:38
Fixed now iirc

**Closed by skjnldsv** 2024-07-31 16:38 UTC
Labels: bug, 1. to develop, feature: files, feature: search, 25-feedback
