### ISSUE TITLE
[Bug]: Unable to load text application CSS files ("apps/text/css/")

### ISSUE THREAD

**Issue by admike82** [nextcloud/server#49083] opened 2024-11-04 19:39 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading Nextcloud to version 30.0.1, the description of the card description is broken.

I suspect a problem loading the CSS.

![Image](https://github.com/user-attachments/assets/e5b7505a-2071-430d-907b-4f52716a0069)

Refreshing the browser cache doesn't change anything. 

However, I noticed that nextcloud couldn't load the files from the "apps/text/css/" folder. (You get a 404 error in the console)

So I disabled the text application in the application management page. 

The problem didn't reappear, but I no longer have the "text" formatting buttons. I'll try to reactivate "text" at the next Nextcloud update.

### Steps to reproduce

1.Activate "text" in the application management page.
2.Open or create a card in deck
3.Files in the "app/text/css" folder are not loading. You get a 404 error in the console.

### Expected behavior

You get a 404 error in the console and card description is broken.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-11-04 21:10
I can't reproduce this problem. UI looks as expected to me.

> However, I noticed that nextcloud couldn't load the files from the "apps/text/css/" folder. (You get a 404 error in the console)

These load for me.

I suspect a configuration matter. Unfortunately you didn't fill out the template so there's not much to go on. I'd encourage you to troubleshoot further on the help forum: https://help.nextcloud.com

I'm closing this issue for those reasons and because you posted a duplicate issue in the Deck repository without referencing it here (nextcloud/deck#6472). Please don't post duplicates... at least not without at least cross-referencing them. It creates duplicate work. Thanks!

**Closed by joshtrichards** 2024-11-04 21:10 UTC
Labels: bug, 0. Needs triage, 30-feedback
