### ISSUE TITLE
[Bug]: Core Error

### ISSUE THREAD

**Issue by jet438** [nextcloud/server#48133] opened 2024-09-17 11:38 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I’m experiencing a core driver exception error to my new AIO installation. The error occurs every 10min (almost exactly). I was asked by @szaimen on the Nextcloud forums to post it here. 
Help is much appreciated.

### Steps to reproduce

New installation. 
Occurs every 10 minutes

### Expected behavior

The nice green check mark

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "www.cloud1.mywire.org",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "www.cloud1.mywire.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "30.0.0.14",
        "overwrite.cli.url": "https:\/\/www.cloud1.mywire.org\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updatedirectory": "\/nc-updater",
        "loglevel": 2,
        "app_install_overwrite": [
            "nextcloud-aio",
            "deck"
        ],
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": 10485760,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "jpeg_quality": 60,
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": 30,
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "maintenance_window_start": 100,
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 3600,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "files_external_allow_create_new_local": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_key": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "US",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 3.2.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.0
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - cookbook: 0.11.2
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.0
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_fulltextsearch: 30.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - fulltextsearch: 30.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - music: 2.0.1
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - notify_push: 0.7.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.1
  - workflowengine: 2.12.0
Disabled:
  - encryption: 2.18.0
  - fulltextsearch_elasticsearch: 29.0.1
  - suspicious_login: 8.0.0
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
Didn't work for me. Sorry
```

### Nextcloud Logs

```shell
|Error|core|DriverExceptionAn exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR: column “cr.id” must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT “cr”.*, “co”.“calendardata”, “c”.“displayname”, “c”."… ^

Error while running background job OCA\DAV\BackgroundJob\EventReminderJob (id: 10, arguments: null) | Sep 16, 2024, 3:01:41 PM -- | --
/var/www/html/3rdparty/doctrine/dbal/src/Connection.phpLine 1943
Doctrine\DBAL\Driver\API\PostgreSQL\ExceptionConverter->convert
(
  [
    "Doctrine\\DBAL\\Driver\\PDO\\Exception"
  ],
  [
    "Doctrine\\DBAL\\Query"
  ]
)
/var/www/html/3rdparty/doctrine/dbal/src/Connection.phpLine 1885
Doctrine\DBAL\Connection->handleDriverException
(
  [
    "Doctrine\\DBAL\\Driver\\PDO\\Exception"
  ],
  [
    "Doctrine\\DBAL\\Query"
  ]
)
/var/www/html/3rdparty/doctrine/dbal/src/Connection.phpLine 1106
Doctrine\DBAL\Connection->convertExceptionDuringQuery
(
  [
    "Doctrine\\DBAL\\Driver\\PDO\\Exception"
  ],
  "SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= ? GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",
  [
    1726513301
  ],
  [
    2
  ]
)
/var/www/html/lib/private/DB/Connection.phpLine 415
Doctrine\DBAL\Connection->executeQuery
(
  "SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= ? GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",
  [
    1726513301
  ],
  [
    2
  ],
  null
)
/var/www/html/lib/private/DB/ConnectionAdapter.phpLine 50
OC\DB\Connection->executeQuery
(
  "SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= :dcValue1 GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",
  [
    1726513301
  ],
  [
    2
  ]
)
/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.phpLine 272
OC\DB\ConnectionAdapter->executeQuery
(
  "SELECT `cr`.*, `co`.`calendardata`, `c`.`displayname`, `c`.`principaluri`, `cr`.`notification_date`, `cr`.`event_hash`, `cr`.`type` FROM `*PREFIX*calendar_reminders` `cr` INNER JOIN `*PREFIX*calendarobjects` `co` ON `cr`.`object_id` = `co`.`id` INNER JOIN `*PREFIX*calendars` `c` ON `cr`.`calendar_id` = `c`.`id` WHERE `cr`.`notification_date` <= :dcValue1 GROUP BY `cr`.`event_hash`, `cr`.`notification_date`, `cr`.`type`",
  [
    1726513301
  ],
  [
    2
  ]
)
/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.phpLine 249
OC\DB\QueryBuilder\QueryBuilder->executeQuery
(
  [
    "OC\\DB\\ConnectionAdapter"
  ]
)
/var/www/html/apps/dav/lib/CalDAV/Reminder/Backend.phpLine 53
OC\DB\QueryBuilder\QueryBuilder->execute
()
/var/www/html/apps/dav/lib/CalDAV/Reminder/ReminderService.phpLine 104
OCA\DAV\CalDAV\Reminder\Backend->getRemindersToProcess
()
/var/www/html/apps/dav/lib/BackgroundJob/EventReminderJob.phpLine 50
OCA\DAV\CalDAV\Reminder\ReminderService->processReminders
()
/var/www/html/lib/public/BackgroundJob/Job.phpLine 61
OCA\DAV\BackgroundJob\EventReminderJob->run
(
  null
)
/var/www/html/lib/public/BackgroundJob/TimedJob.phpLine 83
OCP\BackgroundJob\Job->start
(
  [
    "OC\\BackgroundJob\\JobList"
  ]
)
/var/www/html/lib/public/BackgroundJob/TimedJob.phpLine 73
OCP\BackgroundJob\TimedJob->start
(
  [
    "OC\\BackgroundJob\\JobList"
  ]
)
/var/www/html/cron.phpLine 162
OCP\BackgroundJob\TimedJob->execute
(
  [
    "OC\\BackgroundJob\\JobList"
  ]
)
Caused by ExceptionSQLSTATE[42803]: Grouping error: 7 ERROR: column “cr.id” must appear in the GROUP BY clause or be used in an aggregate function LINE 1: SELECT “cr”.*, “co”.“calendardata”, “c”.“displayname”, “c”."… ^

Raw log entry

{
  "reqId": "L1kZsE4dzXKO6uO7pb4a",
  "level": 3,
  "time": "2024-09-16T19:01:41+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job OCA\\DAV\\BackgroundJob\\EventReminderJob (id: 10, arguments: null)",
  "userAgent": "--",
  "version": "30.0.0.14",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
    "Message": "An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"cr.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"...\n               ^",
    "Code": 7,
    "Trace": [
      {
        "file": "/var/www/html/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1943,
        "function": "convert",
```

**Comment by solracsf** [comment] 2024-09-17 14:10
Duplicate of https://github.com/nextcloud/server/issues/47977

**Closed by solracsf** 2024-09-17 14:10 UTC
Labels: bug, 0. Needs triage, 30-feedback
