### ISSUE TITLE
ldap_control_paged_result() is deprecated spam

### ISSUE THREAD

**Issue by p5n** [nextcloud/server#19127] opened 2020-01-24 18:47 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Enable user_ldap authentication
2. See the log

### Expected behaviour
LDAP works

### Actual behaviour
LDAP works but it spams hundreds of such error messages.

`[PHP] Error: Function ldap_control_paged_result() is deprecated at /usr/share/webapps/nextcloud/apps/user_ldap/lib/LDAP.php#310`

### Server configuration

**PHP version:**
7.4.1

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Comment by kesselb** [comment] 2020-01-24 19:39
cc @nextcloud/ldap

**Comment by blizzz** [comment] 2020-01-27 12:52
This method were deprecated in 7.4  and for some reason the PHP LDAP module is always too talkative. We need to switch to `ldap_exop`, can be used starting PHP 7.3 where server controls support was added.

**Comment by yodatak** [comment] 2020-02-20 19:33
Any news on this nextcloud is not ready to PHP 7.4 if the ldap fonction spam a lot , i try to set the error_reporting but i can"t find where do i have to set it for

**Comment by Dennis1993** [comment] 2020-02-22 12:26
I have the same problem and switched back to PHP 7.3.15 on Ubuntu 18 with PHP 7.4.2

**Comment by chrissi55** [comment] 2020-02-22 16:40
I'm back to php 7.3.14 because there were no little chance to get rid of those messages under php 7.4.x

Never the less my ubuntu 18.04.4 updates each time there are php updates 7.3.x AND 7.4.x
So i let them installed parallel for the day nextcloud becomes compatible with php 7.4.x

Any other affected functions of nextcloud that "dislike" php 7.4 at the moment (nc 18.0.1) ?

**Comment by chrissi55** [comment] 2020-03-15 04:58
So need an update.
You launched the Nextcloud 18.0.2 shortly. Is this error still an open issue or has it been solved under the latest version?

**Comment by Bubbelb** [comment] 2020-03-15 07:30
The issue is still here. It seems like nothing in the LDAP app is changed.
f.w.i.w.: The app is at version 1.8.0. Nextcloud is at version 1.8.0.2

**Comment by kesselb** [comment] 2020-03-15 11:16
![image](https://user-images.githubusercontent.com/3902676/76700303-74ed2100-66b6-11ea-8bd5-0d54cc377c96.png)

If this issue is open than it's not fixed yet. Please subscribe to this issue and you will be notified on status change.

**Comment by dahammo** [comment] 2020-03-28 18:53
I really need a fix for this. Having the exact same issue on nextcloud 18. It's eating up processor cycles on the AD and the AD is freezing up with 100% CPU. I did a packet capture and its flooded with ldap requests from nextcloud to AD. The nextcloud log is currently 220 GB and filled with these errors.

The LDAP configuration is causing the entire AD infrastructure to fail, so this is critical. I'm having 250+ users working on the cloud.

**Comment by Lenezir** [comment] 2020-03-30 14:01
> I really need a fix for this. Having the exact same issue on nextcloud 18. It's eating up processor cycles on the AD and the AD is freezing up with 100% CPU. I did a packet capture and its flooded with ldap requests from nextcloud to AD. The nextcloud log is currently 220 GB and filled with these errors.
> 
> The LDAP configuration is causing the entire AD infrastructure to fail, so this is critical. I'm having 250+ users working on the cloud.

Exact same situation here.
I've PHP 7.4.3 and Nextcloud 18.0.3.

**Comment by pcolmer** [comment] 2020-03-30 14:03
@Lenezir for what its worth, I worked around this by degrading to PHP 7.3.

**Comment by Lenezir** [comment] 2020-03-30 15:07
@pcolmer Thanks. :)

**Comment by blizzz** [comment] 2020-03-30 16:11
> It's eating up processor cycles on the AD and the AD is freezing up with 100% CPU.

That's got nothing to do with Nextcloud logging PHP deprecation messages.

**Comment by Lenezir** [comment] 2020-03-30 16:46
@blizzz I just fixed the problem (maybe it will not work for everyone).
I downgraded to PHP 7.3 AND I installed the php7.3-smbclient module (and some others modules presented on the doc), I forgot it. Now it works like a charm.

**Comment by blizzz** [comment] 2020-04-02 14:56
Who's affected can try https://github.com/nextcloud/server/pull/20274

**Closed** 2020-04-15 13:02 UTC
Labels: 1. to develop, 18-feedback, bug, feature: ldap
