### ISSUE TITLE
file/folder name corrupt after rename with "." 

### ISSUE THREAD

**Issue by kyhuynhduc** [nextcloud/server#16140] opened 2019-06-28 04:44 UTC
step 1: folder name : "PAYMENT QLYCHT (Phase3) - BongTeam"
step 2: rename to:  "PAYMENT.**QLYCHT** (Phase3) - BongTeam"

nextcloud recognize .**QLYCHT (Phase3) - BongTeam** is file extension
=> folder coruppted => nolonger access (even though rename)

**Comment by palto42** [comment] 2019-07-05 17:11
Can't reproduce this bug on Ubuntu 18.04 server with Nextcloud 15.0.9

**Comment by kyhuynhduc** [comment] 2019-07-15 04:16
> Can't reproduce this bug on Ubuntu 18.04 server with Nextcloud 15.0.9
FYI
#16393

**Comment by Mululu** [comment] 2019-07-30 07:32
#https://github.com/nextcloud/server/issues/16468

**Comment by juliushaertl** [comment] 2019-07-30 08:19
Duplicate of https://github.com/nextcloud/groupfolders/issues/518

**Closed by juliushaertl** 2019-07-30 08:19 UTC
Labels: 0. Needs triage, bug
