### ISSUE TITLE
Analytics App Icon visible for all users although App is limited to group

### ISSUE THREAD

**Issue by benks-io** [nextcloud/server#25958] opened 2021-03-05 14:01 UTC
### Steps to reproduce
1. Install Analytics App
2. Limit to Group
3. Login as user not member of the group

### Expected behaviour
The Icon should not be visible.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:** Debian Buster

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 20.0.8

**Comment by acsfer** [comment] 2021-03-05 16:39
Duplicate of https://github.com/Rello/analytics/issues/73

**Closed by acsfer** 2021-03-05 16:39 UTC
Labels: 0. Needs triage, bug
