### ISSUE TITLE
[Bug]: After Rename The Folder, Renamed Folder Does Not Appear Without Reload

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/server#46735] opened 2024-07-25 08:13 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is a message that the renaming was correct. However, it's not appearing without refresh.

https://github.com/user-attachments/assets/72bc3225-41fd-45b1-bcb6-6c1e0225c441

### Steps to reproduce

1. Have fresh instance
2. Rename any folder

### Expected behavior

Renamed folder must appear without refresh

### Installation method

Community Docker image - docker pull nextcloud:29.0.4

### Nextcloud Server version

29.0.4

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

**Comment by susnux** [comment] 2024-07-25 09:28
Duplicate of https://github.com/nextcloud/server/issues/46604

Already fixed https://github.com/nextcloud/server/pull/46690

**Closed by susnux** 2024-07-25 09:28 UTC
Labels: bug, 0. Needs triage, 29-feedback
