### ISSUE TITLE
[Bug]: Adding and removing additional e-mail adress

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#31164] opened 2022-02-14 10:02 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

1. When deleting the secondary email address added first, the edit menu for the second email address is not shown. To delete the second e-mail address you need a page refresh.

Screenshot:

- Adding two email addresses:

![obraz](https://user-images.githubusercontent.com/47037905/153838765-99d9d75e-d71c-4390-9695-4fb62cdc1f72.png)

- Gray inactive menu button for editing the email address added as the second:

![obraz](https://user-images.githubusercontent.com/47037905/153838984-4d7cf779-40ca-47d1-bfb2-f46adde1ee54.png)

- The email address menu is only active after refreshing the page:

![obraz](https://user-images.githubusercontent.com/47037905/153839083-da4ad6c8-9603-4855-9119-e569eabdfaff.png)

2. When adding an additional email address, the description "Primary email for password reset and notifications" appears. In my opinion, it is unnecessarily duplicated.

Screenshot:

![obraz](https://user-images.githubusercontent.com/47037905/153839247-679d15da-bbc6-4362-a2fe-367c61816e19.png)

### Steps to reproduce

1. Select "Personal info".
2. Add an additional email address.
3. Add a second additional email address.
4. Delete the first additional email address.
5. Try to delete the second email address.

### Expected behavior

1. While deleting email addresses, every email address editing menu should be active, no matter which one you delete first.
2. Deletion of duplicate email description "Primary email for password reset and notifications" when adding an additional email address.

@blizzz Can you fix it?

### Installation method

Manual installation

### PHP engine version

PHP 7.3

### Database engine version

MySQL

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Accessibility 1.9.0
Activity 2.15.0
Circles 23.0.1
Collaborative tags 1.13.0
Comments 1.13.0
Contacts Interaction 1.4.0
Dashboard 7.3.0
Deleted files 1.13.0
Federation 1.13.0
File sharing 1.15.0
First run wizard 2.12.0
Gestion 2.0.4
Log Reader 2.8.0
Monitoring 1.13.0
Nextcloud announcements 1.12.0
Notes 4.3.0
Notifications 2.11.1
Password policy 1.13.0
PDF viewer 2.4.0
Photos 1.5.0
Privacy 1.7.0
Recommendations 1.2.0
Right click 1.2.0
Share by mail 1.13.0
Support 1.6.0
Text 3.4.0
Theming 1.14.0
Update notification 1.13.0
Usage survey 1.11.0
User status 1.3.1
Versions 1.16.0
Video player 1.12.0
Weather status 1.3.0
Auditing / Logging 1.13.0
Default encryption module 2.11.0
External storage support 1.15.0
LDAP user and group backend 1.13.1
```

**Comment by Pytal** [comment] 2022-02-24 20:59
Fixed in https://github.com/nextcloud/server/pull/31345

**Comment by Pytal** [comment] 2022-02-24 21:00
> 2. Deletion of duplicate email description "Primary email for password reset and notifications" when adding an additional email address.

I believe this is working as intended @blizzz ?

**Comment by Pytal** [comment] 2022-02-24 21:01
Regarding expected behavior

> 2. Deletion of duplicate email description "Primary email for password reset and notifications" when adding an additional email address.

I believe this is working as intended @blizzz ?

**Comment by blizzz** [comment] 2022-02-24 22:17
> Regarding expected behavior
> 
> > 2. Deletion of duplicate email description "Primary email for password reset and notifications" when adding an additional email address.
> 
> I believe this is working as intended @blizzz ?

I think he means the duplication of the label as seen in the screenshot

**Comment by Pytal** [comment] 2022-02-25 02:42
> I think he means the duplication of the label as seen in the screenshot

Roger, fixed in https://github.com/nextcloud/server/pull/31347

**Comment by Pytal** [comment] 2022-03-02 02:16
Reopening pending https://github.com/nextcloud/server/pull/31345

**Closed** 2022-06-13 07:14 UTC
Labels: bug, 0. Needs triage, feature: settings
