### ISSUE TITLE
After updating to Nextcloud 22.2.3, no event in dashboard

### ISSUE THREAD

**Issue by EVOTk** [nextcloud/server#29753] opened 2021-11-17 18:09 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to 22.2.3
2. Go to Dashboard
3. Nothing is displayed, despite I have scheduled events
4. 
![2021-11-17 18_53_54-Window](https://user-images.githubusercontent.com/45015615/142256053-db87b1e4-b9e0-4a4c-bffc-feab31231240.png)
![2021-11-17 18_54_11-Window](https://user-images.githubusercontent.com/45015615/142256072-6559e7c5-32b8-4cce-9812-3d07a973c7bf.png)

### Expected behaviour
It should display the next events

### Actual behaviour
It does not display anything

### Server configuration

**Operating system:**

**Web server:** nginx
**Database:** mariadb10
**PHP version:** 8
**Nextcloud version:** 22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update 22.2.1 to 22.2.3

**Comment by szaimen** [comment] 2021-11-17 18:34
Duplicate of https://github.com/nextcloud/calendar/issues/3649

**Closed by szaimen** 2021-11-17 18:34 UTC
Labels: bug, 0. Needs triage

**Comment by EVOTk** [comment] 2021-11-17 18:37
Thx @szaimen
