### ISSUE TITLE
LDAP: can not find user when name and surname are empty on AD-user-object

### ISSUE THREAD

**Issue by victorbw** [nextcloud/server#12582] opened 2018-11-22 09:30 UTC
Sometimes it happens or is mandatory that some LDAP users (Microsoft Server 2016 in this case), like admins or other technical accounts, do NOT have any name or surname in the object listed.

![grafik](https://user-images.githubusercontent.com/8447071/48893835-8d8e5380-ee41-11e8-91ba-018b7753c802.png)

Nextcloud version (eg, 12.0.2): 14.0.3
Operating system and version (eg, Ubuntu 17.04): ubuntu 16.04LTS
Apache or nginx version (eg, Apache 2.4.25): apache 2.4.18
PHP version (eg, 7.1): 7.0

The issue you are facing: nc-ldap is not showing any user who has empty name & surname fields.

Is this the first time you’ve seen this error? (Y/N): Y

Steps to replicate it:

    create AD-User
    remove users name/surname
    rescan AD
    users without name/surname wont be listed at all and therefore cannot log in

So the questions are:

    Is this a behaviour by design or simply got forgotten to cover? Haven't found any information about this so far.
    Anyone else seen the same issue?
    Is there a workaround for this, except for filling name and surname into AD-Object?

thanks in advance! :wink:

**Comment by blizzz** [comment] 2018-11-29 22:59
> The issue you are facing: nc-ldap is not showing any user who has empty name & surname fields.

To be precise, it does not import any user with a missing displayname attribute (as configured).

So, yes, this is by design, to (reliably…) avoid pulling in various system accounts.

**Comment by ChristophWurst** [comment] 2018-11-29 23:16
Sooo … wontfix?

**Comment by blizzz** [comment] 2018-11-29 23:25
Yeah, essentially, yes.

**Closed by blizzz** 2018-11-29 23:25 UTC
Labels: bug, feature: ldap, needs info

**Comment by victorbw** [comment] 2018-11-30 11:48
Maybe this should be mentioned in the documentation as a side-note - just in case?

**Comment by blizzz** [comment] 2018-11-30 22:18
@victorbw i thought it was, but apparently it is not, indeed. Would you like to try to bring it in? → https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_user/user_auth_ldap.rst

**Comment by victorbw** [comment] 2018-12-05 08:22
> 
> 
> @victorbw i thought it was, but apparently it is not, indeed. Would you like to try to bring it in? → https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_user/user_auth_ldap.rst

If there's no stress to be done within a few days, sure, why not :)

**Comment by ChristophWurst** [comment] 2018-12-05 08:29
> Hope I'll do it right - just planting a new pull-request should do it, right?

Yes! Thank you!

**Comment by victorbw** [comment] 2018-12-05 12:52
moved to [#1010](https://github.com/nextcloud/documentation/issues/1010)
