### ISSUE TITLE
Update to 15.0: SQL column missing

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/server#13280] opened 2018-12-27 21:49 UTC
Upgrading two Nextcloud installations from version 14.0.4 to 15.0 using the web updater went well, however, with the third one a problem occured:

```
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `calendarid`, `uri` FROM `oc_calendarobjects` WHERE `calendardata` LIKE ?' with params ["%;VALUE=:%"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'calendardata' in 'where clause'
Update failed
```
This occurs when the updater (also when using `occ upgrade`) tries to update ‹dav› as well as (similar) when trying to run `occ maintenance:repair`.

Is there a way to solve this without doing a complete reinstall?

### Server configuration

**Operating system**: Newest NextCloudPi

**Web server:**

**Database:**

**PHP version:** 7.2

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.4.0
  - apporder: 0.6.0
  - audioplayer: 2.5.1
  - bookmarks: 0.15.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.4.0
  - contacts: 2.1.8
  - dav: 1.6.0
  - deck: 0.5.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.7.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.3.0
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - metadata: 0.8.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.1
  - notifications: 2.2.1
  - oauth2: 1.3.0
  - ownbackup: 18.11.0
  - password_policy: 1.5.0
  - polls: 0.9.5
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.4.0
Disabled:
  - admin_notifications
  - announcementcenter
  - calendar
  - caniupdate
  - encryption
  - external
  - files_rightclick
  - impersonate
  - mindmaps
  - quota_warning
  - ransomware_protection
  - spreed
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "***REMOVED SENSITIVE VALUE***",
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/media\/dataDrive\/ncdata\/skeleton\/",
        "default_language": "de",
        "default_locale": "de",
        "knowledgebaseenabled": "false",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": true,
        "logfile": "\/media\/dataDrive\/ncdata\/nextcloud.log",
        "loglevel": "2",
        "log_type": "file",
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Comment by TomTurnschuh** [comment] 2018-12-27 21:53
Reference to #9911, nextcloud/calendar#873 and #12410

**Comment by flixman** [comment] 2019-01-28 20:24
Hi: I am experiencing the same issue when updating from 14.0.3 to 15.0.2.

**Comment by skjnldsv** [comment] 2020-04-10 08:45
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2020-04-10 08:45 UTC
Labels: 0. Needs triage, bug
