### ISSUE TITLE
WebDAV in NC14

### ISSUE THREAD

**Issue by plyaskin** [nextcloud/server#10612] opened 2018-08-09 11:57 UTC
1. Upload file (167 mb and 457 mb) to WebDAV folder via desktop sync

Error
"Error transferring http://www.test.nextcloud.com/remote.php/dav/uploads/admin_test/4143300923/.file - server replied: Service Unavailable (Failed to check file size: Sabre\HTTP\ClientException: PROPPATCH failed. The following properties errored: {DAV:}lastmodified (403))"

The files are uploaded but the sync tries to upload it again, but as result, the sync downloaded this file from the server and replaced the source file...

2. Speed upload/download via WebDAV is reduced x2 (minimum)

**Comment by rullzer** [comment] 2018-08-11 06:58
Can you give me a bit more detailed steps? As my sync client uploads just fine.

**Comment by plyaskin** [comment] 2018-08-11 07:18
Thanks @rullzer for your implication!

1. Just connected External storage WebDAV in NC and sync via Desktop app without any additional manipulations after installation of NC. Results in the first message.
2. Mounted the WebDAV folder via davfs2 to Ubuntu and installed data directory to this folder (when set up the NC). In result, I have a lot of freezes (when surfing in NC and sync), errors of uploading (in the first message and with MYSQL) and slow speed of upload/download.

I can try to replay the second problem with davfs2 and send the errors which I will have if this will help, just let me know what I need to do.

**Comment by plyaskin** [comment] 2018-08-12 07:08
Hi @rullzer,

Do you have any news? I hope I will can use NC14, when it will be released.

**Comment by plyaskin** [comment] 2018-08-15 15:32
Hi @rullzer @tflidd @ruphy @canadaduane 

Will be work correctly WebDAV in NC14?

**Comment by skjnldsv** [comment] 2019-06-14 05:16
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-06-14 05:16 UTC
Labels: 0. Needs triage, 14-feedback, bug
