### ISSUE TITLE
Customize reminder type for automatically generated birthday events

### ISSUE THREAD

**Issue by gbmaster** [nextcloud/server#1753] opened 2016-10-14 13:55 UTC
As requested in https://github.com/nextcloud/calendar/issues/130 , I create this issue here.

Is it possible to add a way to customize the reminders (or, as I'd like to, totally disable them) for the birthday events automatically generated from the contacts?

**Comment by nickvergessen** [comment] 2016-10-17 09:26
Duplicate of https://github.com/nextcloud/server/issues/1505

**Closed by nickvergessen** 2016-10-17 09:26 UTC
