### ISSUE TITLE
Integrity check failure when using apps directories

### ISSUE THREAD

**Issue by albinou** [nextcloud/server#12541] opened 2018-11-19 22:19 UTC
### Steps to reproduce
1. Configure an additional apps directory
2. Run the integrity check (`sudo -u www-data php occ integrity:check-core`)

Step 1 is performed as mentioned on [this page](https://docs.nextcloud.com/server/14/admin_manual/installation/apps_management_installation.html#using-custom-app-directories).
In my case, I have the following configuration:

```
  'apps_paths' =>
  array (
    0 => 
    array (
      'path' => '/srv/cloud.example.org/www/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/srv/cloud.example.org/www/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
```

### Expected behaviour

Core integrity check should return no error caused by the additional `extra-apps` directory.

### Actual behaviour

Core integrity check returns the following:

```bash
shell> sudo -u www-data php occ integrity:check-core
  - EXTRA_FILE:
    - extra-apps/mail/l10n/nb.js:
      - expected: 
      - current: 015b7a2d0bd5737c3285efb8b9a03265bb57a9b30df8e9575004d8e42b8e76d70890b366891ad8fe86f98db296853cb069079b2a8b535e4b12cbac2acbbe3bae
    - extra-apps/mail/l10n/zh_TW.json:
      - expected: 
      - current: 8fcae90f69fcc9cc8a4c05e6f526a3a599ca62f59230d06e9aa11bd8c7613550a2f9233c95ff7d075857836d550d273da3313cd0508bf9f0da83ec8c95d7a48c
    - extra-apps/mail/l10n/sv.js:
      - expected: 
      - current: c296d714e8748a2b257f28885341f5d93822ed4d9702673b15662b564b9f6449b1b5fe62168f26f6d5d017252213bc8c2bb414d03476d61bc2aeddd7958eb595
[...]
```

Note that apps from the `extra-apps` directory are working without any problem.

### Server configuration

**Operating system**: Debian Linux 9.6

**Web server:** nginx/1.15.6

**Database:** mariadb

**PHP version:** 7.0.30

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 12

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-14.0.3.tar.bz2

**Signing status:**
<details>
<summary>Signing status (truncated because too long)</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- extra-apps/mail/l10n/nb.js
		- extra-apps/mail/l10n/zh_TW.json
		- extra-apps/mail/l10n/sv.js
		- extra-apps/mail/l10n/es.js
		- extra-apps/mail/l10n/es_MX.json
		- extra-apps/mail/l10n/pt_BR.json
		- extra-apps/mail/l10n/es_GT.js
		- extra-apps/mail/l10n/hr.js
		- extra-apps/mail/l10n/is.js
		- extra-apps/mail/l10n/es_AR.js
		- extra-apps/mail/l10n/sr.js
		- extra-apps/mail/l10n/eu.json
		- extra-apps/mail/l10n/it.js
[...]

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [extra-apps/mail/l10n/nb.js] => Array
                        (
                            [expected] => 
                            [current] => 015b7a2d0bd5737c3285efb8b9a03265bb57a9b30df8e9575004d8e42b8e76d70890b366891ad8fe86f98db296853cb069079b2a8b535e4b12cbac2acbbe3bae
                        )

                    [extra-apps/mail/l10n/zh_TW.json] => Array
                        (
                            [expected] => 
                            [current] => 8fcae90f69fcc9cc8a4c05e6f526a3a599ca62f59230d06e9aa11bd8c7613550a2f9233c95ff7d075857836d550d273da3313cd0508bf9f0da83ec8c95d7a48c
                        )

                    [extra-apps/mail/l10n/sv.js] => Array
                        (
                            [expected] => 
                            [current] => c296d714e8748a2b257f28885341f5d93822ed4d9702673b15662b564b9f6449b1b5fe62168f26f6d5d017252213bc8c2bb414d03476d61bc2aeddd7958eb595
                        )

                    [extra-apps/mail/l10n/es.js] => Array
                        (
                            [expected] => 
                            [current] => 7be2bff8ab7bafeaa40969a0a3d9939caf61b09aa7e7159f66876b296a17e71ba1cd5339d8cb070d2117822d9ad6500d36df675b0263d255b7525ad6972c13be
                        )

                    [extra-apps/mail/l10n/es_MX.json] => Array
                        (
                            [expected] => 
                            [current] => f69433301f893f40dfaf47ae10ebe59e18c0f6c165cd6df9ab10503eeff6764e139c29d8a3f72121e2641f3c7e13ed3dc7b6dd671c206145e4ebf5133aa2aa6a
                        )

                    [extra-apps/mail/l10n/pt_BR.json] => Array
                        (
                            [expected] => 
                            [current] => 561727c394b4c7545de206afe722bdd0857cf4876f52ed63ca96edd269ae8dbe4445bee6c4ae2fef3861dd9d37086f7fce19bb78775102bc3d33740fd77fc00c
                        )

                    [extra-apps/mail/l10n/es_GT.js] => Array
                        (
                            [expected] => 
                            [current] => 8e832b3168b55a2b52e352c543136c86260689d7c795fd9a478b8564bf5a70cbd46ef893ad195da6505bef26f2484e22aef3cfd7b8450cc35451edbf9b16aef2
                        )

                    [extra-apps/mail/l10n/hr.js] => Array
                        (
                            [expected] => 
                            [current] => 7bea7a329c216bfcea7d7817980186f3e17eca39389fb000ebb6e6b3730a241ecb4e581f946b1598214328b6f7a1c13d434abd56056ecde20d444213bd619fbb
                        )

[...]

        )

)

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:                               
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.7
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - news: 13.0.3
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.org",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "apps_paths": [
            {
                "path": "\/srv\/cloud.example.org\/www\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/srv\/cloud.example.org\/www\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "loglevel": 0,
        "mysql.utf8mb4": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

**Comment by ChristophWurst** [comment] 2018-11-29 23:24
Looks like you have either missing or extra files from a previous version of the app. Are you sure it was cleanly installed/updated? Maybe try replacing the app files with a clean snapshot from the github releases of that specific version.

**Comment by MorrisJobke** [comment] 2019-03-25 12:41
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.

**Closed by MorrisJobke** 2019-03-25 12:41 UTC
Labels: bug, needs info
