### ISSUE TITLE
Disappeared App Icons in webclient when browser too narrow (tiled to the side)

### ISSUE THREAD

**Issue by rarealphacat** [nextcloud/server#17795] opened 2019-11-04 07:33 UTC
### Steps to reproduce
1. Tile browser to the right or left on monitor 1920x1080
2. Please see this gif to see what I meant [https://imgur.com/a/OnlF88U](https://imgur.com/a/OnlF88U)
3.

### Expected behaviour
Icons appears but stretched to fit in.

### Actual behaviour
All icons disappeared until wider browser

### Server configuration

**Operating system**:Ubuntu 19.10
**Web server:** Apache2.4
**Nextcloud version:** 17.0
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Comment by szaimen** [comment] 2021-05-27 10:20
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-27 10:20 UTC
Labels: 0. Needs triage, bug
