### ISSUE TITLE
404 error on previews in trashbin only with txt files

### ISSUE THREAD

**Issue by thrynir** [nextcloud/server#28978] opened 2021-09-28 10:32 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create an txt file, an xml in my case
2. delete it
3. go to trashbin

### Expected behaviour
Should generate preview or use cache as it works for other format like mp3 or video

### Actual behaviour
I get an 404 for all text files in the trash, which provoke a ban for crowdsec

### Server configuration

**Operating system:**
Debian 11

**Web server:**
Nginx

**Database:**
Postgresql

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
22.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated form 21

**Where did you install Nextcloud from:**
Form official website

**Signing status:**
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - bruteforcesettings: 2.2.0
  - camerarawpreviews: 0.7.12
  - circles: 22.1.1
  - cloud_federation_api: 1.4.0
  - cookbook: 0.9.3
  - dav: 1.18.0
  - extract: 1.3.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - imageconverter: 1.3.1
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - metadata: 0.14.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - occweb: 0.0.7
  - ocdownloader: 1.7.12
  - photos: 1.4.0
  - previewgenerator: 3.1.1
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - survey_client: 1.10.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - viewer: 1.6.0
  - workflowengine: 2.3.1
Disabled:
  - accessibility
  - activity
  - admin_audit
  - comments
  - contactsinteraction
  - dashboard
  - encryption
  - files_external
  - nextcloud_announcements
  - password_policy
  - recommendations
  - support
  - systemtags
  - user_status
  - weather_status
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.thrynir.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.1.1.2",
        "overwrite.cli.url": "https:\/\/cloud.thrynir.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "default_phone_region": "FR",
        "app_install_overwrite": [
            "occweb",
            "ldaporg",
            "flowupload",
            "caniupdate",
            "cookbook",
            "previewgenerator",
            "imageconverter"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\CR2"
        ],
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Ldap

#### Web server error log
<details>
<summary>Web server error log</summary>

ip - - [28/Sep/2021:12:15:47 +0200] "GET /apps/files_trashbin/preview?fileId=887602&file=Android%2FSMS%2Fsms-20210902000044.xml%2Fsms-20210902000044.xml.d1630626850&c=1630626850 HTTP/2.0" 404 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
ip - - [28/Sep/2021:12:15:47 +0200] "GET /apps/files_trashbin/preview?fileId=887057&file=Android%2FSMS%2Fsms-20210830000042.xml%2Fsms-20210830000042.xml.d1630449424&c=1630449424 HTTP/2.0" 404 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
ip - - [28/Sep/2021:12:15:47 +0200] "GET /apps/files_trashbin/preview?fileId=886826&file=Android%2FSMS%2Fcalls-20210829000041.xml%2Fcalls-20210829000041.xml.d1630449418&c=1630449418 HTTP/2.0" 404 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
ip - - [28/Sep/2021:12:15:47 +0200] "GET /apps/files_trashbin/preview?fileId=887363&file=Android%2FSMS%2Fsms-20210901000043.xml%2Fsms-20210901000043.xml.d1630539494&c=1630539494 HTTP/2.0" 404 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
ip - - [28/Sep/2021:12:15:47 +0200] "GET /apps/files_trashbin/preview?fileId=886487&file=Android%2FSMS%2Fsms-20210828000039.xml%2Fsms-20210828000039.xml.d1630242616&c=1630242616 HTTP/2.0" 404 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
ip - - [28/Sep/2021:12:15:47 +0200] "GET /apps/files_trashbin/preview?fileId=887601&file=Android%2FSMS%2Fcalls-20210902000044.xml%2Fcalls-20210902000044.xml.d1630714875&c=1630714875 HTTP/2.0" 404 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
</details>

**Comment by szaimen** [comment] 2021-09-28 11:13
duplicate of https://github.com/nextcloud/server/issues/26793#issuecomment-874048839

**Closed by szaimen** 2021-09-28 11:13 UTC
Labels: bug, 0. Needs triage
