### ISSUE TITLE
S3 primary storage issues when upload file is bigger than 3+GB 

### ISSUE THREAD

**Issue by azazzel** [nextcloud/server#30429] opened 2021-12-28 23:39 UTC
I see the chunks on S3, 10MB each ,but getting an error after the upload is done, all the php settings are ok in regards the max_upload, time and so on.

Sabre\DAV\Exception: An exception occurred while uploading parts to a multipart upload. The following parts had errors: - Part 1: Error executing "UploadPart" on "https://xxxxx-nc.s3.us-east-1.amazonaws.com/urn%3Aoid%3A2006?partNumber=1&uploadId=l.dtof.dW.UPEUTKoT.r3QfP5UhWt949gZv3DSltIbopaIOWRdBP0udllGhX2BRrd96J_SoVlIbZrC8z6x2sQIiZ6IJXCUK4h3t0YtqKlgR9exzkH66dto1mmgGW24Cq"; AWS HTTP error: Client error: `PUT https://xxxxx-nc.s3.us-east-1.amazonaws.com/urn%3Aoid%3A2006?partNumber=1&uploadId=l.dtof.dW.UPEUTKoT.r3QfP5UhWt949gZv3DSltIbopaIOWRdBP0udllGhX2BRrd96J_SoVlIbZrC8z6x2sQIiZ6IJXCUK4h3t0YtqKlgR9exzkH66dto1mmgGW24Cq` resulted in a `400 Bad Request` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>RequestTimeout</Code><Message>Your socket connection to the server w (truncated...) RequestTimeout (client): Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message><RequestId>0H6F74H0XV255ZKS</RequestId>
--

**Comment by azazzel** [comment] 2021-12-28 23:42
also it's a bummer that every time I'm uploading something and doest work, the S3 bucket is getting bigger and bigger

**Comment by acsfer** [comment] 2021-12-29 09:27
Duplicate of https://github.com/nextcloud/server/issues/20519

**Closed by acsfer** 2021-12-29 09:27 UTC
Labels: bug, 0. Needs triage
