### ISSUE TITLE
Add a thumbnail/grid view to the Files app

### ISSUE THREAD

**Issue by maprambo** [nextcloud/server#6] opened 2016-06-04 14:20 UTC
EDIT by @jancborchardt, todo for grid view:

### Essential

- [ ] **HTML structure:** Current table structure makes it difficult to change the CSS. We need to change to a div-based layout. Only changing table elements to divs, _not_ changing any look or functionality!
- [ ] **CSS:** Introduce grid view style and hook the switch <img width="30" alt="bildschirmfoto 2016-06-04 um 16 05 05" src="https://cloud.githubusercontent.com/assets/7558730/15800002/e1b1fed8-2a6e-11e6-8a2f-61257f1c57fc.png"> on the top right to switch between the views

### Non-essential

- [ ] **HTML:** Simplify structure as there are probably a few elements to cut. Keep in mind what we need for Vue.js, and for standardization across apps
- [ ] **Documentation:** Document the structure for the new list view and grid view. Put them into the currently empty "Main content": https://docs.nextcloud.com/server/14/developer_manual/design/content.html
- [ ] **Vue.js:** Switch Files app to Vue.js part by part. (Is becoming standard for apps, more maintainable, enables us to use animations easier, etc.)

The essential parts we have to do for Nextcloud 15, and considering the short time-frame we should really focus on that before doing the non-essentials.

----------------------

(Original post by @maprambo)

When pressing that button, the gallery opens. It would make much more sense to show all the files and folders as symbols, like native file browsers do:
![bildschirmfoto 2016-06-04 um 16 09 26](https://cloud.githubusercontent.com/assets/7558730/15800016/26c9a4da-2a6f-11e6-811b-848bc09d4d8a.png)

Don't get me wrong - I love the gallery and also that button. But it leads to confusion, so a real symbol view should be opened. The gallery button could just get the gallery's app icon.

**Comment by mar1u5** [comment] 2016-06-04 15:08
I absolutely agree with you 😉 

cc @jancborchardt

**Comment by Bugsbane** [comment] 2016-06-05 17:10
I'm not sure if I understand exactly what @maprambo is requesting, but what I do know is that I'm constantly wishing that we had an app that displayed photos visually like the gallery app, but let us do file operations like delete, copy, raname, share etc as the file app does.

**Comment by mar1u5** [comment] 2016-06-05 17:43
@Bugsbane Not really. @maprambo is requesting a symbol view as an option beside the classical file grid. He (and some other users) are confused about the icon he mentioned above which redirects to the gallery - but looks like it would redirect to an symbol view of the files 😉

**Comment by Bugsbane** [comment] 2016-06-05 18:20
Ok. I guess I just don't understand what a "symbol view" is, possibly because I use KDE+Linux rather than Macos (and possibly Gnome). I'm assuming this is equivalent of Dolphin's Icon view?

**Comment by jancborchardt** [comment] 2016-06-06 21:38
Yeah, we should definitely have a grid view in the Files app. More and more this actually becomes the standard over a bland list view, and Google Drive for example uses it normally.

cc @oparoz because we talked about this in the past. :)

So @MorrisJobke @schiessle @BernhardPosselt @Henni how difficult do you think is it to pull this off?

**Comment by oparoz** [comment] 2016-06-06 23:28
This would make a lot of users happy.
All I had to say was listed [in the thread I started](https://github.com/owncloud/core/issues/17357).

I'll summarize:

1. I'm sure the JS magicians can get a PoC running really quickly. Instead of rendering rows, render boxes and make the icons smaller
2. There were some interesting discussions at the end of the thread regarding turning the view into a system which accepts plugins, in case apps want to introduce different views

**Comment by Bugsbane** [comment] 2016-06-07 00:37
Possibly this should be in a separate ticket (if so, let me know and I'll create it), but personally, when I go browsing a folder full of pictures, I would rather have a view similar to that in the Gallery app, where picture previews aren't cropped arbitrarily into squares, but it's still possible to carry out file operations.

Of course, there's always the possibility of having both view modes. Personally though, I suspect that both cater to basically the same use case (let the user easily see the image files to choose which file operations to apply to which files).

**Comment by Spacefish** [comment] 2016-06-07 19:06
Would be nice if Gallery and a Media Player just got merged into the file app (HTML5 Videoplayer + Audioplayer), as it is such a common functionality that everybody wants to use it / uses it.
So the whole gallery and mediaplayer thing just becomes core functionality.

**Comment by oparoz** [comment] 2016-06-07 20:50
>Possibly this should be in a separate ticket (if so, let me know and I'll create it), but personally, when I go browsing a folder full of pictures, I would rather have a view similar to that in the Gallery app, where picture previews aren't cropped arbitrarily into squares, but it's still possible to carry out file operations.

Maybe this could be solved by letting you chose the size of the thumbnails in files, like via a slider. Windows has a few different presets per example.

But one day, the file operation menu may be available in Gallery since it has a less distracting interface.

>Would be nice if Gallery and a Media Player just got merged into the file app (HTML5 Videoplayer + Audioplayer), as it is such a common functionality that everybody wants to use it / uses it.
So the whole gallery and mediaplayer thing just becomes core functionality.

The viewers could be extracted to different apps, which could be added to core, yes. The problem is that you can be certain that some people will want to disable them and if you need to ship them disabled, then you may as well just keep the viewers in the original apps.

**Comment by Bugsbane** [comment] 2016-06-08 07:54
> Maybe this could be solved by letting you chose the size of the thumbnails

To me, what I love about the Gallery view isn't so much about the size of the preview, it's that a) It shows a preview of the whole image rather than arbitrarily cropping the previews to become a square and b) it shows a large number of image previews with minimal wastage of screenspace. To me at least, the Gallery view is far more useful and beautiful than the scalable preview size view in Windows (or KDE's Dolphin for that matter)

> But one day, the file operation menu may be available in Gallery since it has a less distracting interface.

Glad to hear it! I already previously opened a feature request on owncloud/gallery requesting exactly that. :wink:

**Comment by jancborchardt** [comment] 2016-06-08 08:26
Just one important comment on things which have been said above:

> Maybe this could be solved by letting you chose the size of the thumbnails in files, like via a slider. Windows has a few different presets per example.

and 

> Would be nice if Gallery and a Media Player just got merged into the file app (HTML5 Videoplayer + Audioplayer), as it is such a common functionality that everybody wants to use it / uses it.
So the whole gallery and mediaplayer thing just becomes core functionality.

Please please please keep in mind that every added thing will
- Need to be developed in the first place
- Introduce added complexity to the interface
- Take resources to be maintained

And that is not to be underestimated. Video playing and image viewing already works in files so there’s not really a reason to formally merge them into core, it just increases code complexity.
Also, adding more and more configuration options for thumbnail sizing that we _think_ are needed is a bad approach to handle this.

We should do it like any normal startup: Start small, with an MVP (minimum viable product) and stay agile that way, not developing things which end up not being used. In this case that’s a simple grid view for the files app which makes a lot of sense as I said above. Anything else is for future discussions.

**Comment by Bugsbane** [comment] 2016-06-08 14:09
> Video playing and image viewing already works in files so there’s not really a reason to formally merge them into core

Agreed.

> adding more and more configuration options for thumbnail sizing that we think are needed is a bad approach to handle this

Agreed again.

Using the gallery view in files is largely just reusing existing code from the gallery app, which has already been developed and maintained. The only part where these points become issues that I can see, is more the consideration about how file operations would be applied from a UX point of view, eg we can no longer have a 3 dot menu to the right of every image for file operations. That also has to be developed / maintained for a grid view though. In fact, more than likely, whatever solution was found optimal for grid view, would likely be the same ideal option for a gallery view.

In fact, it could even be argued that a grid view may take *more* coding and maintenance, as it isn't using code that's already in use to display the images.

As far as I can see, the advantages of gallery view would be:

* Less new code to develop/maintain than grid view
* Doesn't either arbitrarily crop images or leave blank space around previews
* Code sharing with Gallery app
* Using image UI conventions people are already used to from Google Images, Flicker etc.
* Provides the largest previews possible within the screenspace given, with the least amount of space wasted

The main downside I see in interaction, is that this style of presentation has traditionally been used in modern webapps, but not in traditional file managers, and a grid view is more familiar to people who are only used to file managers. Given that Nextcloud *is* a webapp though, the relative merit of this seems questionable to me.

I do completely agree though, that we should avoid the ever present temptation to turn everything into "one more option". I certainly don't think that both grid and gallery view options being available at the same time helps anyone at the end of the day.

If we do go with grid view though, the fundamental question, is do we crop off the parts of the image that fall outside the square aspect ratio (like Android's image browser view), or do we scale the entire image to be smaller, so it all fits inside the square shape, leaving empty spaces to the sides on portrait orientation images, or at the top and bottom, for landscape orientation images (like in Dolphin)? To me it seems we have a more modern option than either.

**Comment by oparoz** [comment] 2016-06-08 14:32
>In fact, more than likely, whatever solution was found optimal for grid view, would likely be the same ideal option for a gallery view.

In terms of design, for things like where to put the menu, its colour, etc., yes

>In fact, it could even be argued that a grid view may take more coding and maintenance, as it isn't using code that's already in use to display the images.

Not if you don't go with a plugin system. It's purely a job for UI architects. Kind of what's happening with a responsive design.

>Code sharing with Gallery app

That's actually more work since that piece of code in Files is not designed to be shared. It' was quite problematic to implement uploading for the same reason. The core team doesn't want to create such components and prefers it if each app comes with everything it needs.

> I certainly don't think that both grid and gallery view options being available at the same time helps anyone at the end of the day.

It's a good thing that Gallery is an app which can be disabled then ;)
From my pov, Gallery is just an app, with its own goals, views, features. It shouldn't be a crutch for Files.
A files manager needs a thumbnails view. If the team wants to design it so that it shows images like in Gallery, then it's only slightly more difficult than building a grid, but I think it might confuse users.
Also, switching view in Files is much faster than loading Gallery.

**Comment by MorrisJobke** [comment] 2017-01-24 21:30
@jancborchardt any reason you added the "needs info" label? What is missing here?

**Comment by MorrisJobke** [comment] 2017-04-26 01:55
@jancborchardt I would say we move this to 13

**Comment by jancborchardt** [comment] 2017-04-26 13:20
For sure to 13, thanks.

**Comment by rebeccaformfx** [comment] 2017-08-03 19:04
+1 in 2017!  I hope to see this feature in 13 :) It is very confusing to me that the behavior is to launch to the gallery.  Gallery already has an entry point from the picture frame icon in the navigation bar.  The expected behavior from me as end user was to see a grid view of my files, so seeing the gallery seemed like a bug.

**Comment by olantrust** [comment] 2017-09-11 08:33
Great enhancement.
Will this view be scalable, with perhaps a slide scaler?
That would make it significantly more useful (including for those with different sight or different screen sizes).

**Comment by jancborchardt** [comment] 2017-09-12 11:44
@olantrust scaling via a slide will be out of scope at least for now. Let's focus on the first implementation - where we still look for someone to contribute. ;)

**Comment by jancborchardt** [comment] 2018-09-04 13:15
Added the breakdown of steps in the original post above: https://github.com/nextcloud/server/issues/6#issue-158506798

Please check @nextcloud/designers  :)

**Closed** 2018-10-24 13:31 UTC
Labels: 1. to develop, design, enhancement, feature: files, high
