### ISSUE TITLE
File sharing does not work via public link.

### ISSUE THREAD

**Issue by MRFU510N88** [nextcloud/server#28778] opened 2021-09-09 19:39 UTC
File sharing does not work via public link. This seems to have started since my update to the latest build of NC V22.

If I share to another user, it works fine. When sharing any file via public link I get the following error and associated log entry:

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
Exception: Argument 1 passed to OCA\Cospend\Service\ProjectService::getProjectNames() must be of the type string, null given, called in /var/www/html/nextcloud/apps/cospend/lib/Activity/CospendProvider.php on line 84
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 156:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/html/nextcloud/lib/private/Route/Router.php - line 301:

OC\AppFramework\App::main()

/var/www/html/nextcloud/lib/base.php - line 1000:

OC\Route\Router->match()

/var/www/html/nextcloud/index.php - line 36:

OC::handleRequest()

Caused by TypeError: Argument 1 passed to OCA\Cospend\Service\ProjectService::getProjectNames() must be of the type string, null given, called in /var/www/html/nextcloud/apps/cospend/lib/Activity/CospendProvider.php on line 84
/var/www/html/nextcloud/apps/cospend/lib/Activity/CospendProvider.php - line 84:

OCA\Cospend\Service\ProjectService->getProjectNames()

<<closure>>

OCA\Cospend\Activity\CospendProvider->__construct()

/var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 106:

ReflectionClass->newInstanceArgs()

/var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:

OC\AppFramework\Utility\SimpleContainer->buildClass()

/var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:

OC\AppFramework\Utility\SimpleContainer->resolve()

/var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 460:

OC\AppFramework\Utility\SimpleContainer->query()

/var/www/html/nextcloud/lib/private/ServerContainer.php - line 145:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()

/var/www/html/nextcloud/lib/private/Activity/Manager.php - line 245:

OC\ServerContainer->query()

/var/www/html/nextcloud/apps/activity/lib/NotificationGenerator.php - line 82:

OC\Activity\Manager->getProviders()

/var/www/html/nextcloud/apps/activity/lib/NotificationGenerator.php - line 111:

OCA\Activity\NotificationGenerator->populateEvent()

/var/www/html/nextcloud/lib/private/Notification/Manager.php - line 333:

OCA\Activity\NotificationGenerator->prepare()

/var/www/html/nextcloud/apps/notifications/lib/Push.php - line 192:

OC\Notification\Manager->prepare()

/var/www/html/nextcloud/apps/notifications/lib/App.php - line 58:

OCA\Notifications\Push->pushToDevice()

/var/www/html/nextcloud/lib/private/Notification/Manager.php - line 294:

OCA\Notifications\App->notify()

/var/www/html/nextcloud/apps/activity/lib/NotificationGenerator.php - line 53:

OC\Notification\Manager->notify()

/var/www/html/nextcloud/apps/activity/lib/Consumer.php - line 72:

OCA\Activity\NotificationGenerator->sendNotificationForEvent()

/var/www/html/nextcloud/lib/private/Activity/Manager.php - line 157:

OCA\Activity\Consumer->receive()

/var/www/html/nextcloud/apps/files_sharing/lib/Controller/ShareController.php - line 748:

OC\Activity\Manager->publish()

/var/www/html/nextcloud/apps/files_sharing/lib/Controller/ShareController.php - line 720:

OCA\Files_Sharing\Controller\ShareController->publishActivity()

/var/www/html/nextcloud/apps/files_sharing/lib/Controller/ShareController.php - line 586:

OCA\Files_Sharing\Controller\ShareController->singleFileDownloaded()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:

OCA\Files_Sharing\Controller\ShareController->downloadShare()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 156:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/html/nextcloud/lib/private/Route/Router.php - line 301:

OC\AppFramework\App::main()

/var/www/html/nextcloud/lib/base.php - line 1000:

OC\Route\Router->match()

/var/www/html/nextcloud/index.php - line 36:

OC::handleRequest()

```
Insert your browser log here:

Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

Technical details
Remote Address: ########
Request ID: ###################

```
</details>

**Comment by szaimen** [comment] 2021-09-09 20:17
Looks like a duplicate of https://github.com/nextcloud/deck/issues/3308 but not sure. 
Please fill out the issue template, thanks!

**Comment by MRFU510N88** [comment] 2021-09-09 20:22
> Looks like a duplicate of [nextcloud/deck#3308](https://github.com/nextcloud/deck/issues/3308) but not sure.
> Please fill out the issue template, thanks!

This is completely different. As per the title, file sharing does not work via public link. This has nothing to do with 'deck' or uploading files.

**Comment by szaimen** [comment] 2021-09-09 23:38
Please still fill out the issue template so that we are able to help you. Thank you!

**Comment by MRFU510N88** [comment] 2021-09-09 23:58
Nextcloud issue template does not support v22. https://apps.nextcloud.com/apps/issuetemplate.

My outlined issue is above, edited which makes it significantly less clear.

**Comment by szaimen** [comment] 2021-09-10 00:39
Do you mind adding the installed apps and your anonymized config.php content to the description?

**Comment by szaimen** [comment] 2021-09-10 00:40
And is your issue possibly fixed if you disable the cospend app?

**Comment by acsfer** [comment] 2021-09-10 05:35
@MRFU510N88 issue template is not the App you mentioned, it is about when you create any issue like this on Githubn here is already a template (wording) you must fill that apparently, you messed arround with 😝 

The error on your Nextcloud error is about Cospend app. As @szaimen said, try disable it in the first place; you should also report that error to the Cospend developer at https://github.com/eneiluj/cospend-nc

Otherwise, you must report any other error once the Cospend app is disabled.

**Comment by hj-beckers** [comment] 2021-09-10 07:38
> 
> 
> > Looks like a duplicate of [nextcloud/deck#3308](https://github.com/nextcloud/deck/issues/3308) but not sure.
> > Please fill out the issue template, thanks!
> 
> This is completely different. As per the title, file sharing does not work via public link. This has nothing to do with 'deck' or uploading files.

I'm the creator of #3308. My thought was as well that it should belong to files(_sharing). But as stated in the thread, disabling deck or updating to the latest version solved my file sharing problems.

**Comment by MRFU510N88** [comment] 2021-09-10 10:16
> And is your issue possibly fixed if you disable the cospend app?

Cospend app disabled. Problem solved. 

How can apps breaks core firmware features like public file sharing? As you rightly stated there are references  to Cospend in the logs could NC just suspend the app if its experiencing conflicts, or a warning/prompt.

**Comment by szaimen** [comment] 2021-09-10 11:10
Thanks for confirming

**Closed by szaimen** 2021-09-10 11:10 UTC
Labels: bug, needs info, 0. Needs triage
