### ISSUE TITLE
[Bug]: NC24 + PHP8.1 break UTF-8 compatibility

### ISSUE THREAD

**Issue by ambraspace** [nextcloud/server#31212] opened 2022-02-16 13:15 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Due to changes introduced in PHP8.1 creating files or directories with non-ascii characters result with problems such as:
- not displaying file/directory name correctly
- not being able to edit file
- not being able to delete file

I'm guessing it's this change from [PHP change log](https://www.php.net/manual/en/migration81.incompatible.php):

> [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php), [htmlentities()](https://www.php.net/manual/en/function.htmlentities.php), [htmlspecialchars_decode()](https://www.php.net/manual/en/function.htmlspecialchars-decode.php), [html_entity_decode()](https://www.php.net/manual/en/function.html-entity-decode.php), and [get_html_translation_table()](https://www.php.net/manual/en/function.get-html-translation-table.php) now use ENT_QUOTES | ENT_SUBSTITUTE rather than ENT_COMPAT by default. This means that ' is escaped to ' while previously nothing was done. Additionally, malformed UTF-8 will be replaced by a Unicode substitution character, instead of resulting in an empty string.

Actually, not being able to edit or delete files have been problem with Arch patched version of NC23 and PHP8.1. With NC24+PHP8.1 I am able to edit or delete text file, but the file name is not properly displayed.

I also noticed that a few contact names with non-ascii characters in name have not been displayed correctly.

### Steps to reproduce

1. Install NC24 from master branch (I tested with last commit 9026455dac6d48ee5ac5899bdb5f00b09c107824)
2. Create admin user and install Plain text editor.
3. Go to Files and create a directory named "šđčćž". The directory created will be displayed as "Å¡ÄÄÄÅ¾".
4. Create new text file named "šđčćž". An error ("An internal server error occurred") will be displayed, but the file will be created, although it will be displayed as "Å¡ÄÄÄÅ¾.txt".

### Expected behavior

The file which has non-ascii characters in file name should be displayed as entered by a user (i.e. to fully support UTF-8 character set).

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.4",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "files_texteditor"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_sharing: 1.16.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - lookup_server_connector: 1.12.0
  - oauth2: 1.12.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - calendar
  - contacts
  - encryption
  - files_external
  - files_markdown
  - testing
  - user_ldap
```

### Nextcloud Signing status

```shell
Integrity checker has been disabled. Integrity cannot be verified.
```

### Nextcloud Logs

```shell
{"reqId":"wTxxhMBMjGnH9YtVcnrT","level":2,"time":"2022-02-15T20:59:58+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"GET","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"wTxxhMBMjGnH9YtVcnrT","level":2,"time":"2022-02-15T20:59:58+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"GET","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"YJdOQ0murWuS3PsCAWUL","level":2,"time":"2022-02-15T21:01:05+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"YJdOQ0murWuS3PsCAWUL","level":2,"time":"2022-02-15T21:01:05+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"k5RFMVQsebjj9ibhgVwg","level":2,"time":"2022-02-16T12:26:41+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"k5RFMVQsebjj9ibhgVwg","level":2,"time":"2022-02-16T12:26:41+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"10v48tQUEdbrkeM8owOE","level":2,"time":"2022-02-16T12:27:06+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"10v48tQUEdbrkeM8owOE","level":2,"time":"2022-02-16T12:27:06+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":""}
{"reqId":"j4SGoponDpUMKbocZOqh","level":2,"time":"2022-02-16T12:27:32+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"24.0.0.4"}
{"reqId":"j4SGoponDpUMKbocZOqh","level":2,"time":"2022-02-16T12:27:32+00:00","remoteAddr":"10.0.2.2","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Host localhost was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"24.0.0.4"}
```

**Comment by PVince81** [comment] 2022-03-24 13:47
there was a similar issue earlier, not sure if related: https://github.com/nextcloud/server/issues/29296

**Comment by come-nc** [comment] 2022-03-30 13:01
https://github.com/sabre-io/http/issues/181

**Comment by come-nc** [comment] 2022-03-31 09:30
@ambraspace So after looking into it this comes from a change in PHP itself which tried to get _better_ at autodetecting encodings.
In this case the accentuated letter you used making no sense PHP consider it unlikely to be UTF-8.
Did you encounter this in a reallife usecase with a file name or was it only from testing with gibberish?

We are looking into not autodetecting encoding if it is valid UTF-8 but it is not clear yet if this is the right path.

**Comment by ambraspace** [comment] 2022-03-31 09:55
@come-nc I encountered this in real life use case. Letters šđčćž are quite common in Slavic languages (Serbian, Croatian, Slovenian, Slovak, Czech and such). Probably more then 90% names in Serbian language end with "ić".

I thought everything is UTF-8 by default these days...

**Comment by come-nc** [comment] 2022-03-31 10:01
> @come-nc I encountered this in real life use case. Letters šđčćž are quite common in Slavic languages (Serbian, Croatian, Slovenian, Slovak, Czech and such). Probably more then 90% names in Serbian language end with "ić".
> 
> I thought everything is UTF-8 by default these days...

Then can you state so and give real life examples in https://github.com/php/php-src/issues/8279 ?
Maybe in https://github.com/sabre-io/http/issues/181 also.

**Comment by CapSel** [comment] 2022-05-04 20:01
When I try to enter Files section all I have is empty screen - no files or directories, just sidebar.
Logs are full of:
```
html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated at /srv/http/ne
xtcloud/apps/news/lib/Db/Item.php#176
```

I don't have any diacritic characters in any of files or directories in root directory (/index.php/apps/files/)

Same problem when I try to open logging section via Settings.

**Comment by come-nc** [comment] 2022-05-05 13:37
> When I try to enter Files section all I have is empty screen - no files or directories, just sidebar. Logs are full of:
> 
> ```
> html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated at /srv/http/ne
> xtcloud/apps/news/lib/Db/Item.php#176
> ```

Please open an issue at https://github.com/nextcloud/news then. But this is just a deprecation warning it should not cause any bug.

> News section works fine.
> 
> I don't have any diacritic characters in any of files or directories in root directory (/index.php/apps/files/)
> 
> Same problem when I try to open logging section via Settings.

Please open an other issue for this blank page problem as it does not seem to be related to this issue. Please provide as many information as possible, including screenshots if possible.

**Comment by alerque** [comment] 2022-05-25 09:08
This issue has practically borked my entire NC installation: it affects Turkish undotted-i (ı) as well. I initially reported it as a [client issue here](https://github.com/nextcloud/desktop/issues/4585) but it turns out just the server by itself is also problematic. The UI sometimes shows these directories as scrambled, sometimes crashes on trying to open them (click on folder, UI jumps back to default login page), etc.

**Comment by alerque** [comment] 2022-05-25 10:37
Also note this isn't NC24, NC23 is broken too, the key is PHP 8.1. I just fired up a dedicated PHP 7.4 FPM socket for Nextcloud 23 and got my instance unborked with it.

**Comment by PaulosV** [comment] 2022-06-03 13:33
Confirming that setting PHP back to 8.0 (and running `occ files:scan --all`) is a good workaround. Ubuntu 22.04.

**Comment by greksak** [comment] 2022-06-06 15:49
I also can confirm, that PHP 8.1 not works for my installation. I am on Arch linux, NC24, names of files are mainly in Slovak. I did downgrade PHP to 7.4 scan the files like PaulosV and I am OK.

**Comment by roberthr74** [comment] 2022-06-07 08:17
Confirming on Ubuntu 22.04 with default install of PHP 8.1. After installing PHP 8.0 everything seems to be ok.

**Comment by nursoda** [comment] 2022-06-07 23:00
The [mail app](https://apps.nextcloud.com/apps/mail) bug [Add PHP 8.1 support](https://github.com/nextcloud/mail/pull/6131) also addresses this issue.

The proposal in [PHP bug #32481](https://github.com/php/php-src/issues/8279) is:

> If you really, really just want to know "which is the first text encoding in this list which is valid for this string", it would be better to call mb_check_encoding in a loop.

Note that as of today, the [PHP manual page on mb-detect-encoding](https://www.php.net/manual/de/function.mb-detect-encoding.php) does not honor the behavior change from PHP 8.0 to 8.1 yet.

**Comment by come-nc** [comment] 2022-06-09 09:56
@nursoda Yes we are going to switch to mb_check_encoding but that needs to be done in sabredav and not Nextcloud.
See #31758 and https://github.com/sabre-io/http/pull/182

**Comment by roberthr74** [comment] 2022-07-20 10:37
Newest NC 24.0.3 includes sabre/dav 4.4.0. Can someone confirm if it's working properly now?

**Comment by mculibrk** [comment] 2022-07-22 10:48
I just updated nextCloud to 24.0.3.2 and can **confirm the issue still persists**

It seems the "problematic" character is lowercase "š" (for Slavic languages)

All other combinations seems to work ok (ŠĐČĆŽ đčćž)

Immediately after renaming a file/folder so that it contains "š" the whole file (if containing any other ŠĐČĆ... characters) gets screwed

Folder before adding "š":
![image](https://user-images.githubusercontent.com/755366/180421679-66cd8996-d51b-4568-86f2-759136706181.png)

Adding "š" at the end of the foldername:
![image](https://user-images.githubusercontent.com/755366/180421749-2e17b81b-ae6a-4940-8c20-3f4ed0e47395.png)

but... at least, the folder/files are still accessible (even if awfully named)
![image](https://user-images.githubusercontent.com/755366/180422007-709cca8f-eac5-4a0f-9b10-2293b21a7080.png)



I have an issue with **MIGRATED** content, which is correctly encoded in utf8 and in console and also in the "view" of files app all seems OK, but when you try to access the folder/file it gets errors like "file not found" and the users get "redirected" to "home" folder

![image](https://user-images.githubusercontent.com/755366/180423694-d19225ab-94eb-43b5-88f0-55774e9df363.png)

**Comment by Japaanc** [comment] 2022-07-23 20:44
Same problem with baltic characters.
Āā,Čč,Ēē,Ģģ,Īī,Ķķ,Ļļ,Ņņ,Šš,Ūū,Žž 

migrated to nc 24.0.3 and PHP 8.1.2 from nc 22.2.0, PHP 7.4.3

**Comment by PVince81** [comment] 2022-07-25 11:57
as far as I can see the fix is only on master / NC 25.

the backport for NC 24 with the library update is still open: https://github.com/nextcloud/3rdparty/pull/1109

**Comment by Japaanc** [comment] 2022-08-12 09:28
It seems that the problem is fixed in 24.0.4!
Thanks!

**Comment by PVince81** [comment] 2022-08-12 10:04
glad to hear!

please upgrade to 24.0.4 as it contains the required library update

**Closed by PVince81** 2022-08-12 10:04 UTC
Labels: bug, 1. to develop, 24-feedback

**Comment by alerque** [comment] 2022-08-12 10:12
@Japaanc As in PHP 8.1 support now? Nothing about that in the changelog, seems like something that should be news if so ;-)

**Comment by Japaanc** [comment] 2022-08-12 10:24
@alerque I,m at this moment using "PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)". no problems at this moment.
just tested in real life, do not know what's in changelog.

**Comment by PVince81** [comment] 2022-08-12 10:28
PHP 8.1 support was already in place for NC 24 and this ticket was the last issue that popped up, so in the changelog it might appear as bumping the sabre lib (the changelogs of patch versions are automated)
