### ISSUE TITLE
Feature Request: User can accept or refuse sharing request

### ISSUE THREAD

**Issue by GioInside** [nextcloud/server#8066] opened 2018-01-26 09:29 UTC
### Steps to reproduce
1.Start a sharing typing a username

### Expected behaviour
User can accept or refuse shared file, depending on fileame, filetype, sender (a friend or a stranger)

### Actual behaviour
sharing start without User acknowledge, and file is downloaded automatically (desktop app)

### Server configuration

**Operating system**:Ubuntu

**Nextcloud version:** 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**List of activated apps:** only default apps

**Are you using encryption**: no

**Are you using an external user-backend, if yes which one:** no

**Comment by MorrisJobke** [comment] 2018-01-26 13:31
Duplicate of #2192

**Closed by MorrisJobke** 2018-01-26 13:31 UTC
