### ISSUE TITLE
Trash bin does not cleaned up

### ISSUE THREAD

**Issue by intervisionlord** [nextcloud/server#24957] opened 2021-01-04 22:07 UTC
### Steps to reproduce
1. Open trash bin for user via web interface
2. Select all files and select option to completly delete them
3. Open trash bin again and files would be there
4. Try to cleanup trash bin via OCC command `php occ trashbin:cleanup username`
5. Open trash bin in web-interface again
6. Files would be there anyway

### Expected behaviour
All files should be deleted

### Actual behaviour
All deleted files are present in trash bin still

### Server configuration

**Operating system:**
Debian 9

**Web server:**
Apache+Nginx
Apache/2.4.25
nginx/1.16.1

**Database:**
MariaDB-10.2.29

**PHP version:**
PHP 7.4.13

**Nextcloud version:** (see Nextcloud admin page)
20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated (this issue was in previous versions too)

**Where did you install Nextcloud from:**
from github

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - announcementcenter: 4.0.0
  - apporder: 0.11.0
  - bookmarks: 4.0.5
  - breezedark: 20.0.2
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - extract: 1.3.0
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - metadata: 0.12.0
  - music: 0.17.3
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - passwords: 2020.12.1
  - phonetrack: 0.6.5
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - qownnotesapi: 20.9.0
  - settings: 1.2.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflow_script: 1.5.0
  - workflowengine: 2.2.0
Disabled:
  - accessibility
  - dashboard
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - recommendations
  - serverinfo
  - sharebymail
  - support
  - survey_client
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "calendar"
        ],
        "mysql.utf8mb4": true,
        "simpleSignUpLink.shown": false,
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 84.0.1 (x64)

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
***REMOVED SENSITIVE VALUE*** - - [05/Jan/2021:01:04:17 +0300] "DELETE /remote.php/dav/trashbin/***REMOVED SENSITIVE VALUE***/trash HTTP/1.0" 204 525 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"L9EsjqHji9lUaqP9Njrz","level":0,"time":"2021-01-04T22:01:37+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"contacts","method":"DELETE","url":"/remote.php/dav/trashbin/***REMOVED SENSITIVE VALUE***/trash","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"L9EsjqHji9lUaqP9Njrz","level":0,"time":"2021-01-04T22:01:37+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"groupfolders","method":"DELETE","url":"/remote.php/dav/trashbin/***REMOVED SENSITIVE VALUE***/trash","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"L9EsjqHji9lUaqP9Njrz","level":0,"time":"2021-01-04T22:01:37+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"files_sharing","method":"DELETE","url":"/remote.php/dav/trashbin/***REMOVED SENSITIVE VALUE***/trash","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"L9EsjqHji9lUaqP9Njrz","level":0,"time":"2021-01-04T22:01:37+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"music","method":"DELETE","url":"/remote.php/dav/trashbin/***REMOVED SENSITIVE VALUE***/trash","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"z0HGmbFY7laWnXtV3Ykl","level":0,"time":"2021-01-04T22:01:38+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"contacts","method":"PROPFIND","url":"/remote.php/dav/files/***REMOVED SENSITIVE VALUE***/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.1.1stable-Win64 (build 20201222) (Nextcloud)","version":"20.0.4.0"}
{"reqId":"z0HGmbFY7laWnXtV3Ykl","level":0,"time":"2021-01-04T22:01:38+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"groupfolders","method":"PROPFIND","url":"/remote.php/dav/files/***REMOVED SENSITIVE VALUE***/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.1.1stable-Win64 (build 20201222) (Nextcloud)","version":"20.0.4.0"}
{"reqId":"z0HGmbFY7laWnXtV3Ykl","level":0,"time":"2021-01-04T22:01:38+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"files_sharing","method":"PROPFIND","url":"/remote.php/dav/files/***REMOVED SENSITIVE VALUE***/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.1.1stable-Win64 (build 20201222) (Nextcloud)","version":"20.0.4.0"}
{"reqId":"z0HGmbFY7laWnXtV3Ykl","level":0,"time":"2021-01-04T22:01:38+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"music","method":"PROPFIND","url":"/remote.php/dav/files/***REMOVED SENSITIVE VALUE***/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows) mirall/3.1.1stable-Win64 (build 20201222) (Nextcloud)","version":"20.0.4.0"}
{"reqId":"ABJEpBbs0KMHbtf1DuJU","level":0,"time":"2021-01-04T22:01:39+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"apporder","method":"POST","url":"/apps/text/session/sync","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"ABJEpBbs0KMHbtf1DuJU","level":0,"time":"2021-01-04T22:01:39+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"contacts","method":"POST","url":"/apps/text/session/sync","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
{"reqId":"ABJEpBbs0KMHbtf1DuJU","level":0,"time":"2021-01-04T22:01:39+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"groupfolders","method":"POST","url":"/apps/text/session/sync","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
a) The javascript console log
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 34 globals.js:60:15
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 17 util.js:130:10
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 18 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
```
</details>

**Comment by elgorro** [comment] 2021-01-06 10:12
Workarround: I switched to auto,D because it was not working either! https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin

**Comment by intervisionlord** [comment] 2021-01-06 18:54
i noticed that if i delete files or folders one by one it works. So, the problem as i think in multiple deletion.

**Comment by elgorro** [comment] 2021-01-06 20:11
Yes, I can confirm that. Thought with the workaround apperantly it works like a charm. Now I hardly remember I run some commands:  "occ" commands in maintenance mode with db repair and cleanup (https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html). May it helps!

**Comment by kurn77** [comment] 2021-01-11 21:43
Hello, I reproduce it also on web version of nextcloud (V 20.0.4).  

Initially, I though it was only impacting files from a group shared folder that were trashed. Multiple deletion is not working, but one by one does. I had about 500 files to delete, I almost broke my mouse ;-)

**Comment by hul51u** [comment] 2021-03-05 13:45
I get an error if I try to delete multiple files, not all files. Delete only 1 file works well, also deleting all files. My nextcloud is 20.0.8 but my instance was affected by this bug for many previous version (18? i dont remember...).

**Comment by Mannshoch** [comment] 2021-03-26 09:07
Have the same problem on my side. It  seems some users are only able to randomly remove files permanent. Others are locked. It's strange the Error message in the trash directory do not contain any value information like the files affected or kind of error.
I did not try to clean up with OCC because many users have this problem and I do not remove data for other users except they wish it.

**Comment by Mannshoch** [comment] 2021-03-26 09:18
For the record. If I remove the file one by one It works. It starts failing if I remove to many files in a short time. After every remove of a file I have to wait around a second until I remove the next one.

**Comment by szaimen** [comment] 2021-07-02 10:10
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-07-02 10:10 UTC
Labels: 0. Needs triage, bug

**Comment by VVD** [comment] 2022-09-18 02:41
Nextcloud 24.0.5: the bug is still here on 2 different hosts - with php 7.4.30 and 8.1.10.
After removing several files in short time can't remove files for 5-10-15 minutes. Then can remove again 20-30 files. Then can't again…

**Comment by thekk1** [comment] 2022-12-13 12:56
> As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking https://nextcloud.com/install/#install-clients and https://nextcloud.com/install/#instructions-server respectively.

For sure this is not the proper way to solve problems in software development (or any other project types).
For some reason, it's not possible to change to the newest version.
In NC-cases most times a depended feature is not supported anymore (i.e. restrict login to ip or share permissions based on group membership).
And last but not least, the bug is not fixed in the current version.

**Comment by petroffcomm** [comment] 2023-05-13 22:50
I confirm this issue in Nextcloud 26.0.1 =(((
php 8.1.19
mariaDB 10.6.13

**Comment by punkyard** [comment] 2023-07-26 17:01
Hi
I cant delete all files neither one by one

![Capture d’écran 2023-07-26 à 16 11 22](https://github.com/nextcloud/server/assets/59349105/37456505-62f7-4778-98ad-aab2164007ff)

NC 26.0.3
AIO 6.3

**Comment by punkyard** [comment] 2024-02-21 16:57
occ help trashbin:cleanup is not helping either

**Comment by punkyard** [comment] 2024-02-21 17:08
this command is helpful to empty all files, but not those in GroupFolder

`sudo -u www-data php occ trashbin:cleanup --all-users`

**Comment by intervisionlord** [comment] 2024-02-23 09:51
@szaimen Hello,
Almost 3 years have passed and I already have version 28.0.2 and PHP 8.2 but the problem has not been fixed. Despite the fact that the problem is reproduced by other users too. It's a pity.

Are you sure that if you couldn't reproduce the problem, then it doesn't exist?

Is it possible to ask to reopen this case and still find some time to analyze the problem? Or at least just keep it open so that other people in the community understand that the problem exists and try to help find a solution?

```
> /opt/php82/bin/php occ trashbin:cleanup --all-users
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see https://www.php.net/manual/en/book.pcntl.php
Additionally the function 'pcntl_signal' and 'pcntl_signal_dispatch' need to be enabled in your php.ini.
Remove deleted files for all users
Remove deleted files for users on backend Database
   <user> (i have removed usernames here)
   <user>
   <user>
```
But all the contents that were in the trash bin are still there.

If you cannot reproduce this yourself, please tell me why the problem has been reproducing for 3 years now on different versions for me and other users and we will try to figure it out ourselves with your help.

**Comment by punkyard** [comment] 2024-02-23 14:43
I finally encountered the occ command to clean all the groupfolder bins
`sudo -u www-data php /var/www/html/occ groupfolders:trashbin:cleanup`
which should only be a workaround

Now all my bins are finally empty - we'll see if we get blocked again ..
I hope this subject will evolve though

**Comment by intervisionlord** [comment] 2024-02-24 07:23
> I finally encountered the occ command to clean all the groupfolder bins `sudo -u www-data php /var/www/html/occ groupfolders:trashbin:cleanup` which should only be a workaround
> 
> Now all my bins are finally empty - we'll see if we get blocked again .. I hope this subject will evolve though

I also tried to empty the trash bin itself and group folders through the OCC, but by now the trash bin has become too large and my server is simply restarts due to lack of RAM. After that, errors appear in the server logs after launching the OCC about the timeout. It seems to me that there should be a delay in emptying the trash bin, which the user must set himself depending on the server resources, since the OCC command does not work optimally with a large number of files.

Since the developers do not want to deal with this bug, I will most likely have to study the API documentation and write something in Python that will empty the trash bin via the API not in batches, but in portions at intervals. Little by little.

In this way, it will be possible to gradually release the basket without overloading the server with requests and without completely using up its resources, as the OCC is doing now.

**Comment by punkyard** [comment] 2024-03-05 16:48
I'm really glad to hear it helped you, @intervisionlord!
