### ISSUE TITLE
Add a collapse button on the left sidebar

### ISSUE THREAD

**Issue by LouisGirones** [nextcloud/server#15896] opened 2019-06-07 18:59 UTC
**Is your feature request related to a problem? Please describe.**
Nop, everything is fine

**Describe the solution you'd like**
I would like to be able to collapse the left sidebar, like it is done on gitlab. Or on other website I guess.

Exemple : 

collapsed lesft sidebar :
![coll](https://user-images.githubusercontent.com/9936642/59126734-14ca9100-8966-11e9-8096-eab5243a61ce.png)

not collapsed left sidebar :
![no_coll](https://user-images.githubusercontent.com/9936642/59126735-15632780-8966-11e9-96e0-91b97bd2473c.png)

**Additional context**
From what I saw, users rarely use this menu except for the admin(s) for whom there is a lot more of options. So a collapse button would just be nice for everyone.
Additionaly (but out of the scope of this feature request), it would be nice to be able to have a file tree in this left sidebar.

**Comment by wiswedel** [comment] 2019-06-07 21:31
@Nextcloud/designers

**Comment by skjnldsv** [comment] 2019-06-08 08:33
@jancborchardt, I think we had a talk about that years ago and we decided against it?

**Comment by jancborchardt** [comment] 2019-06-11 12:43
This is basically a duplicate of https://github.com/nextcloud/server/issues/15831

- We could show the toggle button for the left sidebar always – which is discussed at https://github.com/nextcloud/server/issues/15831
- The "Collapse" function you mention from GitLab is not something we will implement as it makes the navigation quite difficult to use – showing only icons as [mystery meat navigation](https://en.wikipedia.org/wiki/Mystery_meat_navigation). I regularly have issues with it, don’t even want to imagine regular users.

**Closed by jancborchardt** 2019-06-11 12:43 UTC
Labels: 0. Needs triage, enhancement
