### ISSUE TITLE
UI Bug with Roboto Font for Linux User

### ISSUE THREAD

**Issue by RobinDev** [nextcloud/server#18023] opened 2019-11-20 06:17 UTC
Since I update to 17.0.1, the interface looks like every thing is in bold.

The issue come from the usage of Roboto in the default font : 

![issue b156dbcb99e9](https://user-images.githubusercontent.com/3944894/69213628-ed0e6480-0b64-11ea-912b-a8adc518ef63.jpg)

It was an issue `github` had. They fixed it by removing the Roboto from the default font-family. I can't found again the docs about it (i read something a few months about it). We can see in the stylesheet : 
```
font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
```

What do you think about removing `Roboto` from the defaut font-family in the nextcloud stylesheets ?

Thank you,

**Comment by brunob** [comment] 2019-11-20 10:21
FTR here what news looks like since update to nextcloud 17.x, a bit too **BOLD** ^^

![Screenshot_2019-11-20 News (111) - Nextcloud](https://user-images.githubusercontent.com/418064/69230596-ddecde00-0b87-11ea-9e7e-15fcfb49c131.png)

**Comment by brunob** [comment] 2019-11-20 13:22
Surely related to #16055

**Comment by kesselb** [comment] 2019-11-20 13:47
![image](https://user-images.githubusercontent.com/3902676/69243132-accdd700-0ba2-11ea-9153-a9b3c630914f.png)

Looks good with the Ubuntu font. I guess the font is there for android devices? Do you think we could move "Roboto" at the end? Is there any font from the list available on your linux? https://fonts.google.com/specimen/Roboto probably Roboto Light would work.

cc @nextcloud/designers :art:

**Comment by skjnldsv** [comment] 2019-11-20 14:01
@brunob can you provide a pull request to remove roboto then? :)

**Comment by brunob** [comment] 2019-11-20 14:07
Files panel seems not so bad, cf :

![Screenshot_2019-11-20 Fichiers - Nextcloud](https://user-images.githubusercontent.com/418064/69245104-7eea9180-0ba6-11ea-980b-06f505c9e21b.png)

@skjnldsv sure, but as i said : "From my side, the font used is not Roboto, but Ubuntu bold."

@kesselb if i move Ubuntu at the end of `--font-face` declaration i swtich on Arial by default, which seems bit too bold on news module cf : 

![Screenshot_2019-11-20 News (137) - Nextcloud](https://user-images.githubusercontent.com/418064/69245495-367fa380-0ba7-11ea-911a-cee61656d2c8.png)

The main problem is with bold font, not normal ones.

**Comment by skjnldsv** [comment] 2019-11-20 14:20
> @skjnldsv sure, but as i said : "From my side, the font used is not Roboto, but Ubuntu bold."

sorry, I misread, do you have regular Ubuntu font installed as well?
Did you manually installed it?

**Comment by jancborchardt** [comment] 2019-11-20 14:22
- Why does the error appear? Do you have Roboto installed but only bold?
- Could you find a link for the issue Github had? Cause Bootstrap still uses Roboto?
- We should not completely remove Roboto as it is a nice font. It will be used on Android devices for example. So if anything, moving it behind Cantarell and Ubuntu should work?

**Comment by brunob** [comment] 2019-11-20 14:34
@skjnldsv i use ubuntu fonts from system default provided by package, cf : 

```
apt-cache policy ttf-ubuntu-font-family 
ttf-ubuntu-font-family:
  Installé : 1:0.83-0ubuntu2
  Candidat : 1:0.83-0ubuntu2
 Table de version :
 *** 1:0.83-0ubuntu2 500
        500 http://fr.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
        500 http://fr.archive.ubuntu.com/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
```

@jancborchardt : 


> Why does the error appear? Do you have Roboto installed but only bold? What is your OS, does it happen in all browsers, etc?

I don't have Roboto installed, i use Ubuntu 16.04, i only use Firefox (70.0.1) and i observe the same hugeness with bold font on chromium 78.0.3904.97.

**Comment by kesselb** [comment] 2019-11-20 14:43
@brunob please don't hijack issues it's confusing :confused: From the initial report I would assume that the user has the roboto font available and the interface looks to bold. You're reporting an issue with the news app but with the ubuntu font. I would report that to https://github.com/nextcloud/news first but probably i'm too confused now.

**Comment by brunob** [comment] 2019-11-20 14:46
Sorry for the noise, deleting my comments, good luck with that one :)

**Comment by RobinDev** [comment] 2019-11-22 06:44
> * Why does the error appear? Do you have Roboto installed but only bold? What is your OS, does it happen in all browsers, etc?
I have Roboto installed and all the sub-Roboto fonts (Medium, Light, Regulard, Bold, Italic, etc.)

> Could you find a link for the issue Github had? Cause Bootstrap still uses Roboto?
I can't find it again. May @mdo can tell us why Github stop use `Roboto`.

> We should not completely remove Roboto as it is a nice font. It will be used on Android devices for example. So if anything, moving it behind Cantarell and Ubuntu should work?

Yes, if I move Roboto behind Cantarell, it fixes the problem for me.

**Comment by kesselb** [comment] 2019-12-31 16:05
Would you mind to open a pull request and move robot behind ubuntu? ;)

**Comment by jancborchardt** [comment] 2020-01-01 03:30
I can't reproduce this issue (Ubuntu with Firefox and Chrome) – can anyone else?

I'd prefer to keep it like it is, since if you have Roboto installed you get the better and more universal font displayed.

**Comment by kesselb** [comment] 2020-01-01 19:34
I'm able to reproduce this with Ubuntu (Firefox and Chrome). 

`sudo apt install fonts-roboto` will install the font. Chromium needed a restart to pickup the font. 

**Screenshot: Roboto font**
![image](https://user-images.githubusercontent.com/3902676/71645223-67d6ad80-2cd5-11ea-9147-a8dbeb4a0a0b.png)

**Screenshot: Ubuntu font**
![image](https://user-images.githubusercontent.com/3902676/71645246-acfadf80-2cd5-11ea-8951-7d1cc85bf25e.png)


Roboto font should have less priority than Ubuntu font.

**Comment by jancborchardt** [comment] 2020-01-02 05:27
@kesselb the issue that @RobinDev reported is:

> the interface looks like every thing is in bold.

Which is not visible in your first screenshot – everything looks absolutely fine, with only the current folder (in the breadcrumbs bar) in bold. :)

-------------------

And regarding whether we prefer Roboto or Ubuntu, here’s my stance:
- The default Ubuntu install does not ship Roboto, so people will see the Nextcloud interface in Ubuntu font and all is fine.
- If you have Roboto installed you see the Nextcloud interface in Roboto – which is an objectively better interface font than the Ubuntu font.

So the way it is right now works very well.

**Comment by kesselb** [comment] 2020-01-02 13:35
I'm not able to reproduce the "bold" text either.

**Closed by kesselb** 2020-01-02 13:35 UTC
Labels: 0. Needs triage, bug, design, needs info
