### ISSUE TITLE
[index] Error: TypeError: Argument 3 passed to OC\AppFramework\Middleware\MiddlewareDispatcher::beforeOutput() must be of the type string, null given, called in /var/www/html/nxc/lib/private/AppFramework/Http/Dispatcher.php on line 124

### ISSUE THREAD

**Issue by js-d-coder** [nextcloud/server#22931] opened 2020-09-18 06:29 UTC
### Steps to reproduce
(don't know)

### Expected behaviour
No such logs

### Actual behaviour
Logs from Logging app:

```
[index] Error: TypeError: Argument 3 passed to OC\AppFramework\Middleware\MiddlewareDispatcher::beforeOutput() must be of the type string, null given, called in /var/www/html/nxc/lib/private/AppFramework/Http/Dispatcher.php on line 124 at <<closure>>

0. /var/www/html/nxc/lib/private/AppFramework/Http/Dispatcher.php line 124
   OC\AppFramework\Middleware\MiddlewareDispatcher->beforeOutput(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon", null)
1. /var/www/html/nxc/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon")
2. /var/www/html/nxc/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Bookmarks\ ... r", "getBookmarkFavicon", OC\AppFramework\ ... {}, {id: "58",_route ... "})
3. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "58",_route ... "})
4. /var/www/html/nxc/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {id: "58",_route ... "})
5. /var/www/html/nxc/lib/base.php line 1012
   OC\Route\Router->match("/apps/bookmarks/bookmark/58/favicon")
6. /var/www/html/nxc/index.php line 37
   OC::handleRequest()

GET /nxc/apps/bookmarks/bookmark/58/favicon
from 103.77.21.104 by jibran at 2020-09-17T16:08:18+00:00
```

## Server configuration detail

**Operating system:** Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** pgsql PostgreSQL 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, amqp, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, apc, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

**Nextcloud version:** 19.0.3 - 19.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - admin_audit: 1.9.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.5
 - federatedfilesharing: 1.9.0
 - files: 1.14.0
 - files_pdfviewer: 1.8.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - metadata: 0.12.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.6.4
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.13.3
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - activity
 - encryption
 - federation
 - files_external
 - files_rightclick
 - files_versions
 - sharebymail
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "therifleman.name"
    ],
    "enable_previews": "false",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "19.0.3.1",
    "overwrite.cli.url": "https:\/\/therifleman.name\/nxc",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "5432",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "log_type": "file",
    "logfile": "\/var\/www\/nextcloud-data\/nextcloud.log",
    "logfilemode": 416,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "updater.release.channel": "stable",
    "filelocking.enabled": "true",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "has_rebuilt_cache": true,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Operating system:** Ubuntu 20

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
(added above)
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by js-d-coder** [comment] 2020-09-18 06:29
Please let me know if I can add some more info. This error I got 14 hours ago. I tried the best to collect logs. Thanks!

**Comment by kesselb** [comment] 2020-09-18 06:30
cc @marcelklehr

**Comment by marcelklehr** [comment] 2020-09-18 07:09
see https://github.com/nextcloud/bookmarks/issues/1154

**Comment by acsfer** [comment] 2020-09-18 09:26
Closing as duplicate of https://github.com/nextcloud/bookmarks/issues/1154
@js-d-coder follow that topic please.

**Closed by acsfer** 2020-09-18 09:26 UTC
Labels: 0. Needs triage, bug
