### ISSUE TITLE
[FEATURE REQUEST] LAN Sync

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#8331] opened 2018-02-13 19:21 UTC
I found the Dropbox LAN sync pretty useful and was wondering as to why it hasn't been introduced into Nextcloud as an option to be enabled by the user. Is there a plan to add it in the future? if not, why not?

**Comment by MorrisJobke** [comment] 2018-02-14 21:42
Duplicate of #7092 and should be handled in the client - so I refer here to the client repo: owncloud/client#230

**Closed by MorrisJobke** 2018-02-14 21:42 UTC
