### ISSUE TITLE
enabling external storage

### ISSUE THREAD

**Issue by obsidiannonparity** [nextcloud/server#8363] opened 2018-02-15 01:48 UTC
I am trying to enable external storage. The external storage settings page just loads a blank/white page.
![ext_storage](https://user-images.githubusercontent.com/7458716/36237190-a4650322-11b7-11e8-8ed9-9f16289c5898.png)

 
### Steps to reproduce
1. enable external storage
2. go to external storage settings

### Expected behaviour
load settings for external storage
### Actual behaviour
blank / white page
### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** Mysql 5.7.21

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 13

**Updated from an older Nextcloud/ownCloud or fresh install:** Recently updated from Nextcloud 12

**Where did you install Nextcloud from:** Nextcloud official download

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Full list and versions in the occ app:list below
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - contacts: 2.1.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.0
  - files_reader: 1.2.2
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.7.9
  - news: 12.0.1
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_diaspora: 1.0.2
  - socialsharing_email: 1.0.3
  - socialsharing_facebook: 1.0.2
  - socialsharing_googleplus: 1.0.2
  - socialsharing_twitter: 1.0.2
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - firstrunwizard
  - newsbak
  - spreed
  - user_ldap
  - weather

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tristarcreations.com",
            "www.cloud.tristarcreations.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.tristarcreations.com",
        "dbtype": "mysql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Denver",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** yes/no no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.   
</details>

### Client configuration
**Browser:** Firefox 58.0.2 and Google Chrome 64.0.3282.140

**Operating system:** Ubuntu 17.10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
empty (and set to log all)
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2018-02-15 09:41
Looks like a duplicate of #8043 (we have a fix ready for 13.0.1)

And those steps should help as a workaround:

```
- rm -r data/appdata_*/css/* data/appdata_*/js/*
- occ files:scan-app-data
- reload the page
```

Could you check if this helps?

**Comment by sowoi** [comment] 2018-02-15 11:08
I am having the same issue and I followed the above steps but still the external storage screen remains white.
![screenshot-2018-2-15 nextcloud](https://user-images.githubusercontent.com/10256263/36253820-f7fb7368-1248-11e8-86cc-0ab6cd72c1f3.png)

**Comment by MorrisJobke** [comment] 2018-02-15 14:39
cc @icewind1991 

@obsidiannonparity @sowoi Could you open the web developer tools in your browser and check if there are errors in the console?

**Comment by sowoi** [comment] 2018-02-15 14:44
When you call the settings with Microsoft Edge, everything is back to normal. After configuring the external memory with MS Edge, it is now also displayed in Firefox. Previously I had the bug with Firefox 58.02 and Chrome 64.0.3282. It seems to be a browser error.

**Comment by ylefevrevrns** [comment] 2018-02-18 14:40
Hello Everyone,
i have the same issue on a brand new install (OVF Appliance downloaded on the website)
the issue remain even on edge (also tested on chrome, internet explorer & firefox)

also tried the workaround :  
- rm -r data/appdata_*/css/* data/appdata_*/js/*
- occ files:scan-app-data
- reload the page

no more luck :(

**Comment by obsidiannonparity** [comment] 2018-02-18 16:53
I followed those steps @MorrisJobke  but that did not correct the issue and it still is not loading.

**Comment by MorrisJobke** [comment] 2018-02-20 11:49
@juliushaertl @skjnldsv Yet another issue with the styles :/

**Comment by juliushaertl** [comment] 2018-02-20 11:56
@obsidiannonparity @ylefevrevrns Can you post the log files from your Nextcloud and check the browser console for errors when loading that page?

**Comment by obsidiannonparity** [comment] 2018-02-20 21:38
log is empty and console is clear.

just the expected :
JQMIGRATE: Migrate is installed, version 1.4.0

**Comment by skjnldsv** [comment] 2018-02-20 21:41
Nextcloud log?

**Comment by skjnldsv** [comment] 2018-02-20 21:49
Actually, I have the same issue on master. I's not a style issue @MorrisJobke 
It briefly load the page but after a server request to https://dev.xxxxxxxx/apps/files_external/userglobalstorages?testOnly=true the page is left blank

The json return of this request is an empty array 
@obsidiannonparity Do you also briefly see the page?

![kazam](https://user-images.githubusercontent.com/14975046/36451152-564c0aea-1690-11e8-91a3-628e85fbe7d7.gif)

**Comment by ylefevrevrns** [comment] 2018-02-20 21:55
My 2 cents contribution,
I deleted my instance in 13.0 to go on 12.0 (working great)
But when i was in 13.0 i got a briefly view on the page before going to blank.
(Only the headers) 
Best,

**Comment by obsidiannonparity** [comment] 2018-02-20 23:07
Yes I do see the page briefly before it goes to the white page.

**Comment by g-a-c** [comment] 2018-02-22 16:52
I had this issue today with the NextCloud 13 Docker image after enabling the "External storage support" app. For me, the fix was to go to the _Administration_ External Storages page, and enable the "Allow users to mount external storage" option. Any time this option is disabled, my _Personal_ External Storages page is blank, but while this option is enabled, my _Personal_ page is fine.

**Closed** 2018-02-26 14:36 UTC
Labels: 3. to review, feature: external storage, high
