### ISSUE TITLE
Bulk move files

### ISSUE THREAD

**Issue by vip9** [nextcloud/server#7045] opened 2017-11-02 10:21 UTC
**Nextcloud version:** 
12.0.3

Some feature requests for web interface:
- it should allow move all selected files at once,
- it should allow copy/cut/paste, 
- when drag and drop and select folder in breadcrumbs, web interface should "jump" to that folder.

**Comment by tflidd** [comment] 2017-11-03 09:47
Duplicate of https://github.com/nextcloud/server/issues/2779 https://github.com/nextcloud/server/issues/4994 https://github.com/nextcloud/server/issues/6330 https://github.com/nextcloud/server/issues/6404 https://github.com/nextcloud/server/issues/6215 and probably a couple more

And there is something for NC 13:
https://github.com/nextcloud/server/pull/6014
https://github.com/nextcloud/server/pull/6273

**Closed** 2017-11-03 09:49 UTC
