### ISSUE TITLE
Infinite scrolling in users is really infinite :)

### ISSUE THREAD

**Issue by Nyco** [nextcloud/server#21250] opened 2020-06-05 08:44 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to /settings/users
2. Scroll down to the bottom
3. Scroll down
4. Scroll down
5. Scroll down :)

### Expected behaviour
The list of users should stop at some point, since we have a finite number of users

### Actual behaviour
The list goes on, repeating the same set of last users, making the window even bigger at each scroll down

### Server configuration

**Operating system:**
Operating System: | Linux 3.10.0-693.21.1.el7.x86_64 x86_64

**Web server:**

**Database:**
Type: mysql
Version: 5.5.56

**PHP version:**
Version: 7.3.18

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by dst21** [comment] 2020-06-08 11:11
Same here with NC 19.

**Comment by keslerm** [comment] 2020-06-08 13:38
Yep opening this just keeps loading the same handful of users over and over.

**Comment by tqjason** [comment] 2020-06-09 04:17
Same issue with nc19.0 php7.4 httpd2.4 mysql 5.7

**Comment by kirys** [comment] 2020-06-11 13:10
Same issue with an ldap synced server

**Comment by Padl3xx** [comment] 2020-06-12 05:35
Same here :-)

**Comment by jpbraun** [comment] 2020-06-12 16:39
Same here

**Comment by tqjason** [comment] 2020-06-15 02:19
btw, It's about LDAP issue.

**Comment by RenWal** [comment] 2020-06-15 11:27
Same on our LDAP-backed instance. Here's one interesting thing we found (PHP 7.3.18, NC 19, OpenLDAP 2.4.50):

When running `occ user:list`, the options `offset` and `limit` don't behave quite as intended. Especially, `--offset` is ignored for all LDAP users, meaning if you set `--offset 1`, then the first user in the local authentication backend disappears from the list, but the first user from LDAP is still there. You can increase that offset as much as you like, the LDAP results never change.

(Also `--limit` seems to be per-backend, so if you specify `--limit 2` and you have users in LDAP and locally, then you will get 4 results.)

We're unsure if that is related or a different issue, but it would explain why the user list never ends.

**Comment by johkoenig** [comment] 2020-06-16 21:59
I can confirm this behaviour for NC 19.0.0.2 with an ubuntu 20.04 server with php7.4.
The ldap server is a univention corporate server.
@nextcloud/ldap can you please have a look at this. This is pretty annoying :-)

**Comment by blizzz** [comment] 2020-06-16 22:26
Closing as dup of https://github.com/nextcloud/server/issues/20745, is #21111 as @johkoenig pointed out

**Closed by blizzz** 2020-06-16 22:26 UTC
Labels: 0. Needs triage, bug, feature: ldap
