### ISSUE TITLE
wrong version number displayed in notifiyer and updater

### ISSUE THREAD

**Issue by haching** [nextcloud/server#6007] opened 2017-08-07 13:12 UTC
### Steps to reproduce
1. when I open the admin panel I see now, a new Nextcloud version is available. (11.0.4):
![grafik](https://user-images.githubusercontent.com/25200223/29027800-77e06b00-7b82-11e7-8a3d-c5c2bc17f4aa.png)

2. when I click to "updater öffnen" I can see it refers to 12.0.1:
![grafik](https://user-images.githubusercontent.com/25200223/29027828-96b2813a-7b82-11e7-9248-38767076cdd1.png)

3.

### Expected behaviour
I would expect the version numbers match.

### Actual behaviour
see screenshots above

I guess, in this case, all other requested details are not relevant., so I remove it.

**Comment by MorrisJobke** [comment] 2017-08-08 12:41
Duplicate of https://github.com/nextcloud/updater/issues/122

**Closed by MorrisJobke** 2017-08-08 12:41 UTC
