### ISSUE TITLE
Add Pre-filter capabilties in Unified Search 

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/server#29989] opened 2021-11-30 17:03 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem?**

Sometimes the user knows the search scope in terms of where he/she wants to search (e.g the App) and when (e.g the time period, for example a file created in the last week). Currently the App (or Apps) can be selected once the search has been already launched and no possibilities are given to the user to select the period. 

The ability to pre-filter the search before launching it, would lead to a generally shorter search time and less load on the server, ultimately bringing an improved user experience.

This pre-filtering capabilty is already present in other mainstream collaboration platforms and can be also enriched with other items atributes, for example the owner.

**Describe the solution you'd like**
- Make the three-dots menu available before launching the search
- Add to the three-dots menu the option to pre-filter based on last modification date and creation date.

**Describe alternatives you've considered**

**Additional context**

**Comment by acsfer** [comment] 2021-12-01 08:21
Closing as duplicate of https://github.com/nextcloud/server/issues/29614
Please keep the discussion centralized there. Thanks for understanding 👍

**Closed by acsfer** 2021-12-01 08:21 UTC
Labels: enhancement, 0. Needs triage

**Comment by pmarini-nc** [comment] 2021-12-01 08:33
Hi @acsfer , this is not duplicate, but related. What I'm proposing is a different solution and also something that is not included anywhere in #29614, that is time-based filtering.

I'm fine with keeping the discussion in the other ticket, but I think this ticket it shouldn't marked as duplicate.

**Comment by acsfer** [comment] 2021-12-01 08:46
Duplicate in terms of "**improve search experience**" 😉 
Decisions will be made and centralized discussion/debate is a good thing, instead of different issues for the same goal.
