### ISSUE TITLE
[Bug]: Can't open the context menu inside a folder

### ISSUE THREAD

**Issue by SKB-CGN** [nextcloud/server#35106] opened 2022-11-11 14:53 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If trying to open the context menu inside a folder, the throws this exception and no menu is opened.

![2022-11-11 15_49_45-Window](https://user-images.githubusercontent.com/58603329/201364991-20a95301-a044-4595-9e5f-74dbb66ff03a.png)

![2022-11-11 15_49_32-Window](https://user-images.githubusercontent.com/58603329/201365258-2db51c70-faf3-4917-af41-e34cc4695fe6.png)

### Steps to reproduce

Open a folder and click the context menu

### Expected behavior

open context menu

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
----
```

**Comment by szaimen** [comment] 2022-11-11 15:34
Which nc version?

**Comment by SKB-CGN** [comment] 2022-11-11 16:13
Current Version. 25.0.0

**Comment by SKB-CGN** [comment] 2022-11-11 16:16
Also the contact icons are not showing up.

Most of the time the NC updates result it such problems. Why?

**Comment by solracsf** [comment] 2022-11-14 08:19
Run `occ maintance:repair` followed by `systemctl reload php8.1-fpm` (or similar) and `redis-cli FLUSHALL` (or similar) and see if it helps. Most of the time, this is your browser/server/cache trying to load old assets.

**Comment by SKB-CGN** [comment] 2022-11-14 12:18
Thanks for letting me know, but this didnt help.

`redis-cli -s /var/run/redis/redis.sock FLUSHALL`
`OK`
and
`service php-fpm restart`
`Performing sanity check on php-fpm configuration:
[14-Nov-2022 13:11:41] NOTICE: configuration file /usr/local/etc/php-fpm.conf test is successful`

As you can see:
![2022-11-14 13_12_29-CN=Microsoft Windows, O=Microsoft Corporation, L=Redmond, S=Washington, C=US](https://user-images.githubusercontent.com/58603329/201657613-4783cd43-ee80-4ccc-80e0-d41b1247bc3e.png)

Furthermore, all the contact icons are not dispplaying:

![2022-11-14 13_17_03-Dateien - Kreyenborg koeln - Cloud – Mozilla Firefox](https://user-images.githubusercontent.com/58603329/201658159-75fcd515-3b70-4c06-86b3-83644921dd86.png)
![2022-11-14 13_17_53-Dateien - Kreyenborg koeln - Cloud – Mozilla Firefox](https://user-images.githubusercontent.com/58603329/201658164-7129cf3f-b895-4486-ae9f-4d389335ba1f.png)

**Comment by kesselb** [comment] 2022-11-14 19:53
I cannot reproduce. It looks like a caching issue to me, or an incomplete update.

**Comment by SKB-CGN** [comment] 2022-11-14 21:00
This one can be closed.

Maintenance:repair helped here.

**Comment by SKB-CGN** [comment] 2022-11-14 21:01
Context menu is working after maintenance:repair but the other erros remain.

**Comment by nextcloud-command** [comment] 2022-12-15 00:15
This issue has been automatically marked as stale because it has not had recent activity and seems to be missing some essential information. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by kesselb** [comment] 2022-12-17 15:41
It could be an incompatible app or so. Please double-check `app_install_overwrite` in config.php and try to disable incompatible apps. If an app is listed in `app_install_overwrite` the app is enabled even when appinfo.xml does not declare compatibility with the given Nextcloud version.

**Comment by joshtrichards** [comment] 2023-08-29 19:41
Hi @SKB-CGN - Please see the last comment https://github.com/nextcloud/server/issues/35106#issuecomment-1356313680. I'm going to close this out due never being reproduced and not having enough information to isolate it as a bug. Feel free to respond if you're still experiencing the issue and can provide the the additional information. We can always re-open.

**Closed by joshtrichards** 2023-08-29 19:41 UTC
Labels: bug, 0. Needs triage, feature: files, 25-feedback
