### ISSUE TITLE
Bug: Full Screen Image Viewer doesn't always follow the current file order

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/server#28430] opened 2021-08-14 17:23 UTC
When I view photos in a folder I noticed Full Screen Viewer doesn't always match up to the order of the files when clicking next and previous arrows this usually happens when I re-sort items in the folder by name, size or modified.

**Comment by szaimen** [comment] 2021-09-15 14:45
duplicate of https://github.com/nextcloud/viewer/issues/390

**Closed by szaimen** 2021-09-15 14:45 UTC
Labels: bug, 0. Needs triage
