### ISSUE TITLE
PHP Stacktrace updating to 22

### ISSUE THREAD

**Issue by xev-pcjc** [nextcloud/server#27873] opened 2021-07-08 11:28 UTC
Web updater failed, occ udpate gives:
root@nextcloud-3:~ # occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Updated database
Checking for update of app accessibility in appstore
An unhandled exception has been thrown:
TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /usr/local/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php:68
Stack trace:
#0 /usr/local/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php(68): count()
#1 /usr/local/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php(113): OC\Http\Client\DnsPinMiddleware->dnsResolve()
#2 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}()
#3 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#4 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#5 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke()
#6 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#7 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke()
#8 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()
#9 /usr/local/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync()
#10 /usr/local/www/nextcloud/lib/private/Http/Client/Client.php(223): GuzzleHttp\Client->request()
#11 /usr/local/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(108): OC\Http\Client\Client->get()
#12 /usr/local/www/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php(79): OC\App\AppStore\Fetcher\Fetcher->fetch()
#13 /usr/local/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(180): OC\App\AppStore\Fetcher\AppFetcher->fetch()
#14 /usr/local/www/nextcloud/lib/private/Installer.php(434): OC\App\AppStore\Fetcher\Fetcher->get()
#15 /usr/local/www/nextcloud/lib/private/Updater.php(420): OC\Installer->isUpdateAvailable()
#16 /usr/local/www/nextcloud/lib/private/Updater.php(268): OC\Updater->upgradeAppStoreApps()
#17 /usr/local/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#18 /usr/local/www/nextcloud/core/Command/Upgrade.php(241): OC\Updater->upgrade()
#19 /usr/local/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#20 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#21 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#22 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#23 /usr/local/www/nextcloud/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#24 /usr/local/www/nextcloud/console.php(99): OC\Console\Application->run()
#25 /usr/local/www/nextcloud/occ(11): require_once('/usr/local/www/...')
#26 {main}root@nextcloud-3:~ # TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /usr/local/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php:68

Fixed temporarily by changing line 68 of /usr/local/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php to read:

**Comment by kesselb** [comment] 2021-07-09 07:46
Duplicate of https://github.com/nextcloud/server/issues/27870

**Closed by kesselb** 2021-07-09 07:46 UTC
Labels: 0. Needs triage, bug
