### ISSUE TITLE
NC 20.0.4 / PHP Error, maybe related with groupfolders

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/server#24785] opened 2020-12-20 12:17 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install App `groupfolders`
2. Make folders

### Expected behaviour
No PHP-Error

### Actual behaviour
See report below

`{"reqId":"SlryvtGVLMM6xdZymgXU","level":3,"time":"2020-12-20T13:00:25+01:00","remoteAddr":""**REMOVED SENSITIVE VALUE***","user":"**REMOVED SENSITIVE VALUE***","app":"PHP","method":"POST","url":"/apps/groupfolders/folders/191/groups","message":{"Exception":"Error","Message":"Trying to access array offset on value of type int at /var/www/nextcloud/lib/private/Files/Node/Node.php#328","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php","line":328,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":62,"function":"isValidPath","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":163,"function":"getFullPath","class":"OC\\Files\\Node\\Folder","type":"->"},{"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php","line":66,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php","line":146,"function":"__call","class":"OCA\\GroupFolders\\Helper\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":185,"function":"newFolder","class":"OCA\\GroupFolders\\Helper\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":122,"function":"getFolder","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":88,"function":"getMount","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->"},{"function":"OCA\\GroupFolders\\Mount\\{closure}","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":86,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":109,"function":"getMountsForUser","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.60","version":"20.0.4.0","id":"5fdf3e824da5f"}{"reqId":"SlryvtGVLMM6xdZymgXU","level":3,"time":"2020-12-20T13:00:25+01:00","remoteAddr":"**REMOVED SENSITIVE VALUE***","user":"**REMOVED SENSITIVE VALUE***","app":"PHP","method":"POST","url":"/apps/groupfolders/folders/191/groups","message":{"Exception":"Error","Message":"Trying to access array offset on value of type int at /var/www/nextcloud/lib/private/Files/Node/Node.php#328","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php","line":328,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":62,"function":"isValidPath","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":163,"function":"getFullPath","class":"OC\\Files\\Node\\Folder","type":"->"},{"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php","line":66,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php","line":146,"function":"__call","class":"OCA\\GroupFolders\\Helper\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":185,"function":"newFolder","class":"OCA\\GroupFolders\\Helper\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":122,"function":"getFolder","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":88,"function":"getMount","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->"},{"function":"OCA\\GroupFolders\\Mount\\{closure}","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":86,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":109,"function":"getMountsForUser","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.60","version":"20.0.4.0","id":"5fdf3e824da5f"}`

### Server configuration

**Operating system:**
Debian 10.6

**Web server:**
NGINX 1.19

**Database:**
MariaDB 10,5

**PHP version:**
PHP 7.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud 

**Signing status:**
<details>
<summary>no errors have been found.</summary>
</details>

**List of activated apps:**
<details>
<summary>Enabled: - accessibility: 1.6.0  - activity: 2.13.4  - admin_audit: 1.10.0  - apporder: 0.11.0  - bookmarks: 4.0.5  - bruteforcesettings: 2.0.1  - cloud_federation_api: 1.3.0  - comments: 1.10.0  - contacts: 3.4.2  - contactsinteraction: 1.1.0  - dashboard: 7.0.0  - dav: 1.16.2  - duplicatefinder: 0.0.4  - federatedfilesharing: 1.10.2  - federation: 1.10.1  - files: 1.15.0  - files_antivirus: 3.1.0  - files_external: 1.11.1  - files_pdfviewer: 2.0.1  - files_rightclick: 0.17.0  - files_sharing: 1.12.1  - files_trashbin: 1.10.1  - files_versions: 1.13.0  - files_videoplayer: 1.9.0  - groupfolders: 8.2.0  - impersonate: 1.7.0  - logreader: 2.5.0  - lookup_server_connector: 1.8.0  - mail: 1.7.2  - nextcloud_announcements: 1.9.0  - notifications: 2.8.0  - oauth2: 1.8.0  - occweb: 0.0.7  - password_policy: 1.10.1  - photos: 1.2.1  - privacy: 1.4.0  - provisioning_api: 1.10.0  - quota_warning: 1.9.1  - recommendations: 0.8.0  - serverinfo: 1.10.0  - settings: 1.2.0  - sharebymail: 1.10.0  - support: 1.3.0  - systemtags: 1.10.0  - text: 3.1.0  - theming: 1.11.0  - twofactor_backupcodes: 1.9.0  - updatenotification: 1.10.0  - viewer: 1.4.0  - workflowengine: 2.2.0

Disabled: - encryption  - firstrunwizard  - survey_client  - user_ldap  - user_status  - weather_status</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "localhost",            "therapiecenter.org"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "skeletondirectory": "\/var\/data\/nexcloud\/skeleton",        "share_folder": "\/09 - Geteilte Dateien",        "version": "20.0.4.0",        "dbtype": "mysql",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "3306",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "dbtableprefix": "oc_",        "mysql.utf8mb4": true,        "installed": true,        "maintenance": false,        "default_language": "de",        "default_locale": "de",        "default_phone_region": "DE",        "defaultapp": "files",        "knowledgebaseenabled": true,        "allow_user_to_change_display_name": false,        "enable_previews": true,        "enabledPreviewProviders": [            "OC\\Preview\\BMP",            "OC\\Preview\\GIF",            "OC\\Preview\\ICO",            "OC\\Preview\\JPEG",            "OC\\Preview\\PNG"        ],        "preview_max_x": 1024,        "preview_max_y": 768,        "preview_max_scale_factor": 1,        "auth.bruteforce.protection.enabled": true,        "quota_include_external_storage": false,        "trashbin_retention_obligation": "auto, 7",        "versions_retention_obligation": "auto, 7",        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_smtpdebug": false,        "mail_smtpmode": "smtp",        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",        "mail_smtpsecure": "ssl",        "mail_smtpport": "465",        "mail_smtptimeout": 15,        "mail_smtpauthtype": "LOGIN",        "mail_smtpauth": 1,        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",        "mail_template_class": "\\OC\\Mail\\EMailTemplate",        "mail_send_plaintext_only": false,        "overwritehost": "therapiecenter.org",        "overwriteprotocol": "https",        "overwrite.cli.url": "https:\/\/therapiecenter.org",        "htaccess.RewriteBase": "\/",        "log_type": "file",        "logfile": "\/var\/data\/nextcloud\/nextcloud.log",        "loglevel": 2,        "logtimezone": "Europe\/Berlin",        "log_rotate_size": 5242880,        "cron_log": true,        "filesystem_cache_readonly": false,        "filesystem_check_changes": 0,        "filelocking.enabled": "true",        "cache_chunk_gc_ttl": 86400,        "memcache.local": "\\OC\\Memcache\\APCu",        "memcache.distributed": "\\OC\\Memcache\\Redis",        "memcache.locking": "\\OC\\Memcache\\Redis",        "redis": {            "host": "***REMOVED SENSITIVE VALUE***",            "port": 0,            "timeout": 0        },        "activity_expire_days": 14,        "secret": "***REMOVED SENSITIVE VALUE***",        "blacklisted_files": [            ".htaccess",            "Thumbs.db",            "thumbs.db"        ],        "minimum.supported.desktop.version": "3.0.0",        "updatechecker": true,        "updater.release.channel": "stable",        "upgrade.disable-web": false,        "appstoreenabled": true,        "appcodechecker": true,        "integrity.check.disabled": false,        "login_form_autocomplete": false,        "remember_login_cookie_lifetime": 0,        "session_lifetime": 1800,        "session_keepalive": true,        "app_install_overwrite": [            "occweb"        ]    }}</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
 MS Edge

**Operating system:** 
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2020-12-20 13:38
Duplicate of https://github.com/nextcloud/groupfolders/issues/907

**Closed by kesselb** 2020-12-20 13:38 UTC
Labels: 0. Needs triage, bug
