### ISSUE TITLE
General error: 11 database disk image is malformed

### ISSUE THREAD

**Issue by ganasubrgit** [nextcloud/server#10661] opened 2018-08-12 16:25 UTC
### Steps to reproduce
1. web console upgrade from setting

### Expected behaviour
Get upgraded to 13.0.5

### Actual behaviour
Upgrade failed with the following error on web index.php/login

Preparing update

Set log level to debug
Turned on maintenance mode
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX fs_storage_mimepart': SQLSTATE[HY000]: General error: 11 database disk image is malformed

### Server configuration

**Operating system**: 
Linux debian_version 9.4

**Web server:**
apache2 -v
Server version: Apache/2.4.25 (Raspbian)
Server built:   2018-03-31T08:47:16

**Database:**
SQLite3

**PHP version:**
php -v
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Nextcloud  13.0.2

**Where did you install Nextcloud from:**
Nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

<details>
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.100"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.0.100\/nextcloud",
        "dbtype": "sqlite3",
        "version": "13.0.2.1",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:**
 local

**Are you using encryption:** 
yes

**Are you using an external user-backend, if yes which one:** 
No

### Client configuration
**Browser:** Chrome

**Operating system:**
Mac

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment] 2019-08-17 18:41
Closing as duplicate of https://github.com/nextcloud/server/issues/2958

**Comment by kesselb** [comment] 2019-08-17 18:42
Closing as duplicate of https://github.com/nextcloud/server/issues/2958

**Closed by kesselb** 2019-08-17 18:41 UTC
Labels: 0. Needs triage, bug
