### ISSUE TITLE
"Email address changed" email

### ISSUE THREAD

**Issue by lbischof** [nextcloud/server#6517] opened 2017-09-15 09:53 UTC
### Steps to reproduce
1. Unknown
2.
3.

### Expected behaviour
No email notification should arrive if the email stays the same. Notifications should go to the correct users.

### Actual behaviour
Users get email notifications regarding email changes of a different user. See related issue: #5169 Even though the email is the same and hasn't changed!

It seems $oldMailAddress is an email of a different user, because users get emails with `<OtherName> theiremail@domain.com` and the whole email is about OtherName (OtherNames email is the new email).

### Server configuration

**Operating system**:
Ubuntu 16.04.3

**Web server:**
Nginx 1.10.3

**Database:**
Mysql 5.7.19

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0.0 fresh install, then updated through 12.0.1

**Where did you install Nextcloud from:**
downloaded from nextcloud server

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Activity	2.5.2	
Collaborative tags	1.2.0	
Comments	1.2.0	
Deleted files	1.2.0	
Federation	1.2.0	
File sharing	1.4.0	
First run wizard	2.1	
Gallery	17.0.0		
LDAP user and group backend	1.2.1	
Log Reader	2.0.0		
Monitoring	1.2.0		
Nextcloud announcements	1.1	
Notifications	2.0.0	
Password policy	1.2.2		
PDF viewer	1.1.1		
Share by mail	1.2.0	
Text editor	2.4.1		
Theming	1.3.0	
Update notification	1.2.0		
Usage survey	1.0.0		
Versions	1.5.0	
Video player	1.1.0		
Brute-force settings	1.0.2
Markdown Editor	1.0.1
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'datadirectory' => '/var/www/domain/public_html/data',
  'appstoreenabled' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.domain.ch',
    1 => 'files.domain.ch',
  ),
  'overwrite.cli.url' => 'https://nextcloud.domain.ch',
  'dbtype' => 'mysql',
  'version' => '12.0.2.0',
  'dbname' => 'domain',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'nc_',
  'dbuser' => 'domain',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'skeletondirectory' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => '30, auto',
  'loglevel' => 2,
);
```
</details>

**Are you using external storage, if yes which one:** 
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** 
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-----------+--------------------------------------+----------------------------------------------------------------------------------------+
| appid     | configkey                            | configvalue                                                                            |
+-----------+--------------------------------------+----------------------------------------------------------------------------------------+
| user_ldap | cleanUpJobOffset                     | 0                                                                                      |
| user_ldap | enabled                              | yes                                                                                    |
| user_ldap | installed_version                    | 1.2.1                                                                                  |
| user_ldap | s01has_memberof_filter_support       | 0                                                                                      |
| user_ldap | s01home_folder_naming_rule           |                                                                                        |
| user_ldap | s01last_jpegPhoto_lookup             | 0                                                                                      |
| user_ldap | s01ldap_agent_password               |                                                                                        |
| user_ldap | s01ldap_attributes_for_group_search  |                                                                                        |
| user_ldap | s01ldap_attributes_for_user_search   |                                                                                        |
| user_ldap | s01ldap_backup_host                  |                                                                                        |
| user_ldap | s01ldap_backup_port                  |                                                                                        |
| user_ldap | s01ldap_base                         | ou=users,dc=domain,dc=itc                                                              |
| user_ldap | s01ldap_base_groups                  | ou=groups,dc=domain,dc=itc                                                             |
| user_ldap | s01ldap_base_users                   | ou=users,dc=domain,dc=itc                                                              |
| user_ldap | s01ldap_cache_ttl                    | 600                                                                                    |
| user_ldap | s01ldap_configuration_active         | 1                                                                                      |
| user_ldap | s01ldap_default_ppolicy_dn           |                                                                                        |
| user_ldap | s01ldap_display_name                 | cn                                                                                     |
| user_ldap | s01ldap_dn                           |                                                                                        |
| user_ldap | s01ldap_dynamic_group_member_url     |                                                                                        |
| user_ldap | s01ldap_email_attr                   | mail                                                                                   |
| user_ldap | s01ldap_experienced_admin            | 1                                                                                      |
| user_ldap | s01ldap_expert_username_attr         | uid                                                                                    |
| user_ldap | s01ldap_expert_uuid_group_attr       |                                                                                        |
| user_ldap | s01ldap_expert_uuid_user_attr        |                                                                                        |
| user_ldap | s01ldap_gid_number                   | gidNumber                                                                              |
| user_ldap | s01ldap_group_display_name           | cn                                                                                     |
| user_ldap | s01ldap_group_filter                 | (&(objectClass=posixGroup)(cn=smb_*))                                                  |
| user_ldap | s01ldap_group_filter_mode            | 1                                                                                      |
| user_ldap | s01ldap_group_member_assoc_attribute | memberUid                                                                              |
| user_ldap | s01ldap_groupfilter_groups           |                                                                                        |
| user_ldap | s01ldap_groupfilter_objectclass      | inetorgperson                                                                          |
| user_ldap | s01ldap_host                         | localhost                                                                              |
| user_ldap | s01ldap_login_filter                 | (uid=%uid)                                                                             |
| user_ldap | s01ldap_login_filter_mode            | 1                                                                                      |
| user_ldap | s01ldap_loginfilter_attributes       |                                                                                        |
| user_ldap | s01ldap_loginfilter_email            | 0                                                                                      |
| user_ldap | s01ldap_loginfilter_username         | 1                                                                                      |
| user_ldap | s01ldap_nested_groups                | 0                                                                                      |
| user_ldap | s01ldap_override_main_server         |                                                                                        |
| user_ldap | s01ldap_paging_size                  | 500                                                                                    |
| user_ldap | s01ldap_port                         | 389                                                                                    |
| user_ldap | s01ldap_quota_attr                   |                                                                                        |
| user_ldap | s01ldap_quota_def                    |                                                                                        |
| user_ldap | s01ldap_tls                          | 0                                                                                      |
| user_ldap | s01ldap_turn_off_cert_check          | 0                                                                                      |
| user_ldap | s01ldap_turn_on_pwd_change           | 0                                                                                      |
| user_ldap | s01ldap_user_display_name_2          |                                                                                        |
| user_ldap | s01ldap_user_filter_mode             | 1                                                                                      |
| user_ldap | s01ldap_userfilter_groups            |                                                                                        |
| user_ldap | s01ldap_userfilter_objectclass       | inetorgperson                                                                          |
| user_ldap | s01ldap_userlist_filter              | (|(objectclass=inetOrgPerson)(objectclass=sambaSamAccount)(objectclass=shadowAccount)) |
| user_ldap | s01use_memberof_to_detect_membership | 1                                                                                      |
| user_ldap | types                                | authentication                                                                         |
+-----------+--------------------------------------+----------------------------------------------------------------------------------------+
```
</details>

**Comment by MorrisJobke** [comment] 2017-09-15 12:25
cc @nickvergessen @blizzz 

Looks like an interference with LDAP and the user manager.

**Comment by nickvergessen** [comment] 2017-09-15 12:55
Same email address is checked in master:
https://github.com/nextcloud/server/blob/1f843e6c3f8f8fee6f572b52140727811ad2d02c/settings/Hooks.php#L148-L153

This is also the case in 12.0.1 and later:
https://github.com/nextcloud/server/pull/5186

**Comment by lbischof** [comment] 2017-09-15 13:16
Yes, but it seems that $oldMailAddress is wrongly filled with someone elses email because the email doesn't get sent to the correct recipient

**Comment by lbischof** [comment] 2017-09-20 09:33
Is there any way I can change the code to log $oldMailAddress to the logfile? Just so I can check my suspicion...

**Comment by nickvergessen** [comment] 2017-09-20 09:41
In file `server/settings/Hooks.php`
find:
```php
if ($oldMailAddress === $user->getEMailAddress() ||
```
before add:
```php
\OC::$server->getLogger()->debug('Changing email from ' . $oldMailAddress . ' to ' . $user->getEMailAddress());
```

**Comment by alexfauss** [comment] 2017-11-13 13:10
Hello.

We have got the exact same behavior in NC 12.03.3, except using a different server OS and a different LDAP-Server.

Is there something new about this?

**Comment by blizzz** [comment] 2017-11-13 13:41
LDAP delegates setting the email address to the core user object. There was a bug when an event was always triggered, however that has been fixed in 12.0.1 https://github.com/nextcloud/server/pull/5216. Nevertheless, the settings handler (which would send the mail) had had the check already.

What might be possible: some whitespace got included and changed in their. But to really know what happens, get debug output as described by @nickvergessen in https://github.com/nextcloud/server/issues/6517#issuecomment-330801071

**Comment by alexfauss** [comment] 2017-11-13 14:28
@blizzz 

Thx will debug ...

**Comment by alexfauss** [comment] 2017-11-22 09:07
Hello.

Here is the part from the LOG

{"reqId":"n0FhYrETcnYC1ZGcxF2C","level":0,"time":"November 13, 2017 22:17:04","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Changing email from s8ru***@xxx.de to s8okb***@xxx.de","userAgent":"--","version":"12.0.3.3"}

{"reqId":"F2vxTdk5So46Q5hIMAkZ","level":0,"time":"November 13, 2017 22:30:21","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Changing email from s8okb***@xxx.de to s8ru***@xxx.de","userAgent":"--","version":"12.0.3.3"}

Also I have noticed that the mail is being sent to more than one recipients.
I have checked the database tables and the ldap entries for any anomalies.
Nothing found.

What else can be checked?

**Comment by blizzz** [comment] 2017-11-23 10:42
@alexfauss so the email is changed to one address and then to the other. So, the behaviour is correct. From LDAP, only the first address is read and returned. What else could trigger applying the second address?

**Comment by alexfauss** [comment] 2017-11-24 09:41
@blizzz thats true. Sometimes the mail is sent to 3 or 4 different User.

**Comment by blizzz** [comment] 2017-11-24 11:15
But where do they come from?

**Comment by alexfauss** [comment] 2017-11-24 14:04
Hmmh.

The only suspicious entries in the log are

{"reqId":"C6De3km9Gb7FtSWJRZCK","level":0,"time":"November 14, 2017 13:15:01","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"Ready for a paged search","userAgent":"--","version":"12.0.3.3"}
{"reqId":"C6De3km9Gb7FtSWJRZCK","level":0,"time":"November 14, 2017 13:15:01","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"Ready for a paged search","userAgent":"--","version":"12.0.3.3"}
{"reqId":"C6De3km9Gb7FtSWJRZCK","level":0,"time":"November 14, 2017 13:15:01","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"Ready for a paged search","userAgent":"--","version":"12.0.3.3"}
{"reqId":"C6De3km9Gb7FtSWJRZCK","level":0,"time":"November 14, 2017 13:15:01","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"Ready for a paged search","userAgent":"--","version":"12.0.3.3"}
{"reqId":"C6De3km9Gb7FtSWJRZCK","level":0,"time":"November 14, 2017 13:15:01","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"Ready for a paged search","userAgent":"--","version":"12.0.3.3"}
{"reqId":"C6De3km9Gb7FtSWJRZCK","level":0,"time":"November 14, 2017 13:15:05","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"No DN found for appdata_ocwffxf7zyov on ldap.***.de","userAgent":"--","version":"12.0.3.3"}

**Comment by blizzz** [comment] 2017-11-24 15:06
@alexfauss no, not really. Rather I wonder, in which data source is the other email address saved? From LDAP only the first should be retrieved.

**Comment by alexfauss** [comment] 2017-11-27 11:05
@blizz All mail addresses are stored in ldap except my admin account.

**Comment by blizzz** [comment] 2017-11-27 12:21
@alexfauss can you name steps to reproduce this behaviour?

**Comment by alexfauss** [comment] 2017-11-27 14:06
@blizz not really. The problem first occur after upgrading from owncloud to nextcloud. And after every upgrade other users (3-6) are affected by the problem. Right now I have set e smtp filter which is piping all mails regarding that problem to /dev/null. So the user are not bothered.

**Comment by blizzz** [comment] 2017-12-15 15:28
@alexfauss I wasn't able to to reproduce the issue. From LDAP we always take the first email that is returned. It's unlikely but not impossible that a server implementation may send it in varying order… Which LDAP server are you using? Or the values often updated at that place?

Also, can you change the debug output from https://github.com/nextcloud/server/issues/6517#issuecomment-330801071 and replace it with following line? This will enricht the output with a stack trace.

```
\OC::$server->getLogger()->logException(new \Exception('Changing email from ' . $oldMailAddress . ' to ' . $user->getEMailAddress()));
```

**Comment by blizzz** [comment] 2018-09-27 14:01
@alexfauss it's been a while… is this still an issue?

**Comment by lbischof** [comment] 2018-10-01 11:40
@blizzz It seems this has been fixed, because we haven't received such emails lately

**Comment by blizzz** [comment] 2018-10-08 09:04
K, thx. Then let me close it. If it appears, we can reopen.

**Closed by blizzz** 2018-10-08 09:04 UTC
Labels: bug, feature: ldap, feature: users and groups
