### ISSUE TITLE
[Bug]: NC 23.0.3 is not compatible with latest versions of PHP 8.0/8.1 anymore

### ISSUE THREAD

**Issue by toxpal** [nextcloud/server#31714] opened 2022-03-25 14:40 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading PHP to latest versions (8.0.17 or 8.1.4), NC stops working and these problems occur:

1. Client app can't sync files because of "data corrupted" errors
2. Files can not be viewed/downloaded via browser
3. Overview section displays error "Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken"
4. NC log file does not add a single entry regarding these errors.

### Steps to reproduce

1. Upgrade to PHP 8.0.17 or 8.1.4

### Expected behavior

It should work as with older versions of PHP 8.0/8.1.

### PHP engine version

8.0.17 / 8.1.4

### Web server

Apache 2

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Does not change anything, each installation has different apps, and all installations stopped working.
```

### Additional info

The same problem happens to all users running different operating systems as soon as they upgrade PHP packages to the latest versions. Happened to me as well (ALL installations of NC stopped working after PHP upgrade). The oldest PHP release I can get it working again is 8.0.14

https://help.nextcloud.com/t/data-corrupted-on-download-from-server-error/136236
https://help.nextcloud.com/t/the-webdav-interface-seems-not-to-work/136265

**Comment by szaimen** [comment] 2022-03-25 15:09
I cannot reproduce. Aio runs fine with 8.0.17.
See https://github.com/nextcloud/all-in-one/blob/3eede90e867e2967ea971d6ed0259445f7d18ab7/Containers/nextcloud/Dockerfile#L2

**Comment by solracsf** [comment] 2022-03-25 16:17
This surely is a setup issue, I have several v23.0.3 instances running on PHP 8.

```
# php -v
PHP 8.0.17 (cli) (built: Mar 20 2022 17:04:09) ( NTS )
```

**Comment by szaimen** [comment] 2022-03-25 16:23
lets close this then. Help can be asked for at https://help.nextcloud.com

**Closed by szaimen** 2022-03-25 16:23 UTC
Labels: bug, needs info, 0. Needs triage

**Comment by alexskynet** [comment] 2022-04-08 08:06
I have the exact same problem on CentOS Linux release 7.9.2009 and NC 23.0.3
PHP 8.0.17 breaks everything (files look damaged, DAV broken and so on)
Downgrading PHP to 8.0.16 fixes everything
No changes in configuration

**Comment by toxpal** [comment] 2022-04-27 09:26
The same issue still exists with NC 23.0.4

**Comment by unalignedcoder** [comment] 2022-04-28 14:10
Same problem, when switching to PHP 8.0.18 - everything works on 7.4 with the same settings and modules,

**Comment by toxpal** [comment] 2022-10-18 12:17
Can devs finally take a lok at this issue? Running CentOS 7 and I can’t upgrade to PHP 8.0 or 8.1 because of this bug with NC. Happens with all releases of NC 23.x and 24.x, while PHP 8.0 worked fine in the past.

I realize not all people experience the same issue, so maybe devs can’t reproduce it on their systems, but I’ll be more than happy to provide all the logs/information needed.

The forum is also full of complaints about the same issue, usually when running Arch or CentOS.

**Comment by jet438** [comment] 2023-04-10 14:24
I too "seem" to having the same issue. I just upgraded to php 8.1 from 7.4 over the weekend. The base platform is NC25.0.5. I say "seem" because I don't see anything in the log and sometimes I get the error sometimes  and other times I don't. I plan on going to NC26 as soon two apps I use are updated to be compatible with it. Hopefully that corrects it. Don't know what this error is or why it's not consistent.....but it's there by god.
