### ISSUE TITLE
Sabre\DAV\Exception\UnsupportedMediaType: Validation error in iCalendar: ATTACH MUST NOT appear more than once in a VALARM component

### ISSUE THREAD

**Issue by improvethings** [nextcloud/server#10107] opened 2018-07-04 18:20 UTC
### Steps to reproduce
1. Installed calendar (caldav) on a new install
2. Imported events from an owncloud installation
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
$ uname -srm
Linux 3.16.0-4-amd64 x86_64

**Web server:**
apache2                        2.4.10-10+deb8u12                  amd64 
**Database:**

**PHP version:**
PHP 5.6.36-0+deb8u1 (cli) (built: Jun 26 2018 17:31:29) 

**Nextcloud version:** (see Nextcloud admin page)
13 (fresh install) 
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
source tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_pdfviewer
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Sabre\DAV\Exception\UnsupportedMediaType: Validation error in iCalendar: ATTACH MUST NOT appear more than once in a VALARM component/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 802: Sabre\CalDAV\Plugin->validateICalendar('BEGIN VCALENDAR...', 'calendars/simon/...', false, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), true)[internal function] Sabre\CalDAV\Plugin->beforeCreateFile('calendars/simon/...', 'BEGIN VCALENDAR...', Object(OCA\DAV\CalDAV\Calendar), false)/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1094: Sabre\Event\EventEmitter->emit('beforeCreateFil...', Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529: Sabre\DAV\Server->createFile('calendars/simon/...', Resource id #79, NULL)[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/apps/dav/lib/Server.php - line 287: Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 164: require_once('/var/www/nextcl...'){main}
--



```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment] 2018-07-05 08:53
@georgehrke Anything we can do here? I guess not much, right?

**Comment by MorrisJobke** [comment] 2018-07-05 08:54
Duplicate of #4874

**Closed by MorrisJobke** 2018-07-05 08:54 UTC
Labels: bug, feature: dav
