### ISSUE TITLE
[Bug]: Update Centos 9 Stream External Storage SMB/CIF not working

### ISSUE THREAD

**Issue by usertini** [nextcloud/server#36827] opened 2023-02-23 09:28 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

OS Centos 9 Stream.
web server Apache/2.4.53 (CentOS Stream)
Maria DB 10.5.16-MariaDB MariaDB Server
PHP 8.0.27
Nextcloud 25.0.3
The last OS updates carry SAMBA updates. These updates cause SMB/CIF external storage to fail.
The only way to get external storage working again is to perform a downgrade of the SAMBA client (smbclient). With the last update you have to do three downgrades.
Nextcloud throws the following errors in the log:
Error: Undefined array key 1 at /var/www/nubecentos9.lan/htdocs/apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php#46
Icewind\SMB\Exception\Exception: Invalid attribute response

### Steps to reproduce

1.Have SAMBA external storage configured
2.Update Centos 9 Stream OS
3.The update updates the SAMBA client

### Expected behavior

The expected result is that the SMB/CIF external storage would continue to work

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.3
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_antivirus: 4.0.2
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quicknotes: 0.8.5
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - backup: 1.2.0
  - backup-master
  - encryption
  - photos: 1.5.0
  - ransomware_protection: 1.14.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

**Comment by usertini** [comment] 2023-02-23 09:32
I have seen that there is a reference to this problem but with OS Fedora (#36773)

**Comment by remicollet** [comment] 2023-04-04 07:07
@usertini as your report is about CentOS Stream 9, which have samba 4.17.5, this seems really a duplicate of #36773 

If you are using official packages from CentOS and EPEL, you can try [php-smbclient-1.1.0-1.el9 ](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2023-44cbffd1a4)

**Comment by joshtrichards** [comment] 2023-06-15 23:25
Duplicate of #36773

Let's consolidate further follow-up there.

**Closed** 2024-09-08 13:24 UTC
Labels: bug, feature: external storage, 0. Needs triage, 25-feedback
