### ISSUE TITLE
Reminders from shared, but readonly, calendars popping up on due date (IMHO shouldnt)

### ISSUE THREAD

**Issue by juliangieseke** [nextcloud/server#726] opened 2016-08-04 06:56 UTC
### Steps to reproduce
1. A shares calendar with B (readonly)
2. B uses caldav on iPhone/Mac (probably any caldav client)
3. A adds an reminder with due date

### Expected behaviour
IMHO, if the calendar is read only, then also the reminders should be. And as the user B then shouldnt be able to mark reminders as done, there is no reason to remind him…

### Actual behaviour
B gets the reminders AND is able to mark it as done…
BUT the corresponding tasklist isnt viible in the reminders app… 

### Server configuration
nextCloud 9.0.53, but i dont think its an config-issue.
als no logs or other strange things.

---
should i also report this at owncloud or do you still have some kind of code exchange with them?

**Comment by nickvergessen** [comment] 2016-08-04 07:33
Duplicate of https://github.com/nextcloud/server/issues/679

**Closed by nickvergessen** 2016-08-04 07:33 UTC
