### ISSUE TITLE
 External SMB/CIFS Secondary sharing function failure on 16.0.1

### ISSUE THREAD

**Issue by wscxz** [nextcloud/server#18244] opened 2019-12-05 09:34 UTC
### Steps to reproduce
1. Mount External Storage With SMB/CIFS
2. Enable preview and sharing on the right side of the entry
### SMB / CIFS configuration key parameters
- Authentication：**Log-in credentials, save in session**
### Expected behaviour
At this time, the external storage directory will appear in the user interface, and the share button will appear to realize the secondary share function
### Actual behaviour
The external storage directory does appear in the user interface, but the share button does not appear, indicating that secondary sharing is not supported
> If the authentication mode is changed to "**username and password**", the failure will not occur
### Server configuration
- Operating system: **Centos 7.2**
- Web Server:**Apache 2.4.27**
- Dtabase:**MariaDB 10.1.23**
- PHP:**7.1.7**
- Nextcloud version:**16.0.1**

**Comment by kesselb** [comment] 2020-01-14 15:44
Seems to be a duplicate of #18238

**Closed by kesselb** 2020-01-14 15:44 UTC
Labels: 0. Needs triage, bug
