### ISSUE TITLE
"Error while copying file to target location (copied bytes: 0, expected filesize: -1 )"

### ISSUE THREAD

**Issue by thrubovc** [nextcloud/server#18720] opened 2020-01-07 15:40 UTC
**My setup:**
Raspberry 4 running raspbian buster
nextcloud:17.0.2-apache
db: postgres:12.1
php: 7.3.13

**My issue:**
when uploading files >4GB, I get an error message:
`Error while copying file to target location (copied bytes: 0, expected filesize: -1 )`

**nextcloud log:**
```
[webdav] Fatal: Sabre\DAV\Exception: Error while copying file to target location (copied bytes: 0, expected filesize: -1 ) at <<closure>>

 0. /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php line 156
    OCA\DAV\Connector\Sabre\File->put(null)
 1. /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php line 316
    OCA\DAV\Connector\Sabre\Directory->createFile("Furious_Love_1080p.mp4", null)
 2. /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php line 130
    Sabre\DAV\Tree->copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Files\FilesHome {}, "Furious_Love_1080p.mp4")
 3. /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php line 161
    Sabre\DAV\Tree->copy("uploads/tomasko ... e", "files/tomasko/Furious_Love_1080p.mp4")
 4. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("uploads/tomasko ... e", "files/tomasko/Furious_Love_1080p.mp4")
 5. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 6. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
 7. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 9. /var/www/html/apps/dav/lib/Server.php line 317
    Sabre\DAV\Server->exec()
10. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
11. /var/www/html/remote.php line 163
    undefinedundefinedrequire_once("/var/www/html/a ... p")

MOVE /remote.php/dav/uploads/tomasko/web-file-upload-922fd9fc099424860b5c8e1ba03a93bb-1578406027956/.file
from 192.168.0.100 by tomasko at 2020-01-07T14:13:13+00:00
```

Could this possibly relate to #17485?

**Comment by kesselb** [comment] 2020-01-07 15:46
Thank you for reporting this issue :+1: 

I'm closing this report as duplicate of https://github.com/nextcloud/server/issues/16431.

**Closed by kesselb** 2020-01-07 15:46 UTC
Labels: 0. Needs triage, bug

**Comment by StableNarwhal** [comment] 2020-03-16 21:00
Same here, this issue shouldn't be closed. 


NextCloudPi version: v1.23.1
Nextcloud version: 18.0.2.2

on a Raspberry Pi 4

**Comment by kesselb** [comment] 2020-03-16 21:06
> Same here, this issue shouldn't be closed.

> I'm closing this report as duplicate of #16431. 

You will figure it out.

**Comment by StableNarwhal** [comment] 2020-03-16 21:13
> > Same here, this issue shouldn't be closed.
> 
> > I'm closing this report as duplicate of #16431.
> 
> You will figure it out.

I read ticket #16431, I also looked around for possible solutions. If I understood everything correctly this issue should have been fixed by https://github.com/docker-library/php/pull/901.

I'm still very new to docker though, my apologies for that. Doesn't updating my NextcloudPi docker from within (NextCloudPi_docker_07-20-19) include this merge?

**Comment by kesselb** [comment] 2020-03-16 21:24
You said "this issue shouldn't be closed". I quoted my earlier response that this issue has been closed as duplicate. There are only a few reasons to have more than one issue for the same problem. Please ask the friendly people at https://help.nextcloud.com/ for advice or the other issue.
