### ISSUE TITLE
Abort X is missing when deleting multiple files

### ISSUE THREAD

**Issue by Noodlesalat** [nextcloud/server#18008] opened 2019-11-19 14:23 UTC
### Steps to reproduce
1. Delete multiple files

### Expected behaviour
An abort "X" should appear or the status bar should be complete at least.

### Actual behaviour
No "X" appears and the status bar is not complete.
Screenshot:
![Bildschirmfoto von 2019-11-19 15-10-45](https://user-images.githubusercontent.com/12748782/69154515-6dd74d00-0ae0-11ea-8d7b-4bffe147cef9.png)

### Server configuration

**Operating system**: Debian 10.2

**Web server:** Apache/2.4.38 (Debian) Server

**Database:** SQLite

**PHP version:** 7.3.11

**Nextcloud version:** Nextcloud 18.0.0 Alpha

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** github (clone)

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.0
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - lookup_server_connector: 1.6.0
  - oauth2: 1.6.0
  - provisioning_api: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - systemtags: 1.8.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "18.0.0.1",
        "overwrite.cli.url": "http:\/\/example.com\/server",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

**Comment by szaimen** [comment] 2021-05-27 11:30
I don't agree on this topic since the trashbin is there for excaclty this purpose: restoring by mistake deleted files/folders.

---

But cc @nextcloud/designers was there a cancel button someday to cancel this process and is this a regression?

**Comment by stefan-niedermann** [comment] 2021-05-27 11:45
More notes: A cancel button will lead to an unknown state for the user:
- Are the files deleted?
- Are they restored?
- Are some files deleted and other restored? How can i restore the deleted files? Which of them *are* deleted?
- [Schrödingers files](https://en.wikipedia.org/wiki/Schr%C3%B6dinger%27s_cat)?

**Comment by szaimen** [comment] 2021-05-27 11:50
Based on @stefan-niedermann answer I am going to close this issue because it doesn't make sense to implement this because of the mentioned problems.

**Closed by szaimen** 2021-05-27 11:50 UTC
Labels: 0. Needs triage, bug, needs info
