### ISSUE TITLE
Can't access files after snap updated to 16.0.5snap1

### ISSUE THREAD

**Issue by ducemollari** [nextcloud/server#17331] opened 2019-09-30 09:26 UTC
Got "This directory is unavailable, please check the logs or contact the administrator" after logon.

In logs have this:

index | TypeError: basename() expects parameter 1 to be string, null given/snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Check/FileName.php - line 62: basename(null)
/snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Check/AbstractStringCheck.php - line 63: OCA\WorkflowEngine\Check\FileName->getActualValue()
/snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Manager.php - line 123: OCA\WorkflowEngine\Check\AbstractStringCheck->executeCheck("matches", "/.(\\.pyc\|\ ... i")
/snap/nextcloud/16232/htdocs/apps/workflowengine/lib/Manager.php - line 94: OCA\WorkflowEngine\Manager->check({ id: "13",c ... "})
/var/snap/nextcloud/16232/nextcloud/extra-apps/files_accesscontrol/lib/Operation.php - line 67: OCA\WorkflowEngine\Manager->getMatchingOperations("OCA\\FilesA ... n")
/var/snap/nextcloud/16232/nextcloud/extra-apps/files_accesscontrol/lib/CacheWrapper.php - line 63: OCA\FilesAccessControl\Operation->checkFileAccess(OCA\FilesAcc ... l}, "xxxxxxx")
/snap/nextcloud/16232/htdocs/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 71: OCA\FilesAccessControl\CacheWrapper->formatCacheEntry(OC\Files\Cache\CacheEntry {})
/snap/nextcloud/16232/htdocs/lib/private/Files/Node/Folder.php - line 445: OC\Files\Cache\Wrapper\CacheWrapper->get(20851)<<closure>>OC\Files\Node\Folder->OC\Files\Node\{closure}("*** sensiti ... *")
/snap/nextcloud/16232/htdocs/lib/private/Files/Node/Folder.php - line 452: array_filter({ 30: "*** s ... }}, Closure {})
/snap/nextcloud/16232/htdocs/lib/private/Files/Node/Folder.php - line 398: OC\Files\Node\Folder->recentParse([ { fileid:  ... }], { 1: OC\File ... }}, OC\Files\Type\Loader {})
/snap/nextcloud/16232/htdocs/apps/recommendations/lib/Service/RecentlyEditedFilesSource.php - line 60: OC\Files\Node\Folder->getRecent(6)
/snap/nextcloud/16232/htdocs/apps/recommendations/lib/Service/RecommendationService.php - line 91: OCA\Recommendations\Service\RecentlyEditedFilesSource->getMostRecentRecommendation(OC\User\User {}, 6)<<closure>>OCA\Recommendations\Service\RecommendationService->OCA\Recommendations\Service\{closure}("*** sensiti ... *")
/snap/nextcloud/16232/htdocs/apps/recommendations/lib/Service/RecommendationService.php - line 92: array_reduce([ OCA\Recomm ... }], Closure {}, "*** sensiti ... *")
/snap/nextcloud/16232/htdocs/apps/recommendations/lib/Controller/RecommendationController.php - line 63: OCA\Recommendations\Service\RecommendationService->getRecommendations(OC\User\User {})
/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Recommendations\Controller\RecommendationController->index()
/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Recommen ... {}, "index")
/snap/nextcloud/16232/htdocs/lib/private/AppFramework/App.php - line 126: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Recommen ... {}, "index")
/snap/nextcloud/16232/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OCA\\Recomm ... r", "index", OC\AppFramew ... {}, { _route: "r ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "r ... "})
/snap/nextcloud/16232/htdocs/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "r ... "})
/snap/nextcloud/16232/htdocs/lib/base.php - line 975: OC\Route\Router->match("/apps/recom ... s")
/snap/nextcloud/16232/htdocs/index.php - line 42: OC::handleRequest()
-- | --

Have tryed this: files:cleanup, files:scan, maintaince:repair.

**Comment by ducemollari** [comment] 2019-09-30 09:42
Just found it's files_accesscontrol app problem. After disabling app I can use NC as "normally".

**Comment by kesselb** [comment] 2019-09-30 10:33
Could you try to disable the recommendation app and enable files_accesscontrol again?

This could be a regression from https://github.com/nextcloud/server/commit/b5f407e02d03e19ef820135347a69619b863538f because it returns null for some paths but the workflow engine expects a string. 

cc @rullzer :sos:

**Comment by ducemollari** [comment] 2019-09-30 13:27
Already. No, still the same error when accessing files.

**Comment by ducemollari** [comment] 2019-10-04 09:35
I found it's depending of having access to Group folders. Without any GP I have no error and just after adding me to some GP (specially created new GP) I have problem with accessing to my files.
GP app updated to 4.1.3 this morning.

**Comment by kesselb** [comment] 2019-10-05 14:14
Should be fixed by https://github.com/nextcloud/server/pull/17359

**Comment by ducemollari** [comment] 2019-10-10 09:17
Refreshed my installation to 16/edge. All seems working as expected, turned on files_accesscontrol app and here no erorrs with groupfolders.
Also got yesterday some errors on uploading files that looks alike basename(null). Now it's clear too.

**Closed** 2019-10-11 08:13 UTC
Labels: 0. Needs triage, bug
