### ISSUE TITLE
[feature] Allow admin users to monitor quota usage of every users

### ISSUE THREAD

**Issue by virtnix** [nextcloud/server#3277] opened 2017-01-26 11:09 UTC
Hello,

It could be really useful to be able via occ command and Web GUI (obviously only admin users) to list the quota usage of every users. This is for monitoring purpose, users can then be warned in case they are close to reach their quota.

Thanks !!

**Comment by MorrisJobke** [comment] 2017-01-28 01:08
Duplicate of #117

**Closed by MorrisJobke** 2017-01-28 01:09 UTC
