### ISSUE TITLE
Can't rename users full name - Authentication error

### ISSUE THREAD

**Issue by camoflash** [nextcloud/server#11057] opened 2018-09-05 07:38 UTC
### Steps to reproduce
0. Open any browser, log into nextcloud as an Administrator and go to page where you can edit all users
1. Open browser's Inspector tool -> Network tab
2. Edit user's 'Full Name' field
3. Look for POST Request named displayName in Inspector tool
4. Look at the POST Request response
5. Reload page to see if 'Full Name' field is changed

### Expected behaviour
- Dialog box asking for password confirmation before changes to user's 'Full Name' field is commited
- POST Request "displayName" getting a good response
- Reloading page should have shown changes to user's 'Full Name' field

### Actual behaviour
Tell us what happens instead
- No password confirmation dialog appearing
- POST Request is returning the response: {"status":"error","data":{"message":"Authentication error"}}
- Reloading page does not show any change to user's 'Full Name' field

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Nginx

**Database:**
mysql

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
13.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from ealier 13 version only

**Where did you install Nextcloud from:**
Nextcloud docker: https://github.com/nextcloud/docker

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox 61.0.2, Chrome 68.0.3440.106
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MartB** [comment] 2018-09-06 18:42
Can not reproduce on 14.0.0 RC 2 so i would assume it has been fixed since then.
Will try to find the fix so it can be backported.

**Comment by MorrisJobke** [comment] 2018-10-02 21:53
> I did not know that the entire js stuff was rewritten.
> Will leave this to someone that is more familiar with the codebase.

Not likely to be back ported as we moved to a completely new code basis. Sorry for that. I would close this for now.

If you have still problems: could you try the provisioning API to update the display name and check also the logs for suspicious entries? We then can reopen the issue.

**Closed by MorrisJobke** 2018-10-02 21:53 UTC
