### ISSUE TITLE
[Bug]: "Update all" apps button throws Javascript error TypeError: this.update is not a function

### ISSUE THREAD

**Issue by tryallthethings** [nextcloud/server#49378] opened 2024-11-19 14:33 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Clicking the "Update all" button to update all apps on https://cloud.domain.com/index.php/settings/apps/updates does not update anything and throws a JavaScript error instead. This issue was introduced in 30.0.1 or 30.0.2. The same error is thrown in Chrome and Firefox:

```
AppList.vue:321 Uncaught (in promise) TypeError: this.update is not a function
    at AppList.vue:321:1
```
![Image](https://github.com/user-attachments/assets/a460f3d5-69d0-4c7a-9258-f1e0fc30ef4d)

I'm currently running Nextcloud 30.0.2. Updating the apps individually does work.

### Steps to reproduce

1. Go to the app update page https://cloud.domain.com/index.php/settings/apps/updates
2. Click "Update all" button

### Expected behavior

Clicking the button should update all apps.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": false,
        "forbidden_filenames": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com",
            "domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "loglevel": 0,
        "log_rotate_size": 104857600,
        "logtimezone": "Europe\/Berlin",
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": false,
        "singleuser": false,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "debug": false,
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "calendar",
            "keeweb",
            "spreedme",
            "documentserver_community",
            "files_antivirus",
            "maps"
        ],
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "remember_login_cookie_lifetime": 2592000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "default_phone_region": "DE",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance_window_start": 1,
        "bulkupload.enabled": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - app_api: 4.0.0
  - audioplayer: 3.4.1
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - contacts: 6.1.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_antivirus: 5.6.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - forms: 4.3.3
  - impersonate: 1.17.0
  - keeweb: 0.6.20
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.2
  - maps: 1.5.0
  - metadata: 0.21.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - previewgenerator: 5.6.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.2
  - richdocumentscode: 24.4.902
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.2
  - suspicious_login: 8.0.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - assistant: 2.1.1 (installed 2.1.1)
  - camerarawpreviews: 0.8.6 (installed 0.8.6)
  - comments: 1.20.1 (installed 0.3.0)
  - encryption: 2.18.0 (installed 2.10.0)
  - extract: 1.3.6 (installed 1.3.6)
  - federation: 1.20.0 (installed 1.8.0)
  - files_linkeditor: 1.1.21 (installed 1.1.21)
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 3.0.0 (installed 1.1)
  - music: 2.0.1 (installed 2.0.1)
  - sharerenamer: 3.4.0 (installed 3.4.0)
  - support: 2.0.0 (installed 1.1.0)
  - survey_client: 2.0.0 (installed 1.6.0)
  - systemtags: 1.20.0 (installed 0.3.0)
  - twofactor_nextcloud_notification: 4.0.0
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
Nothing is in the logs related to this.
```

**Comment by skjnldsv** [comment] 2024-11-19 15:00
cc @andrey18106 https://github.com/nextcloud/server/pull/48665
You removed the mixin on `AppList.vue`

**Comment by joshtrichards** [comment] 2024-11-19 15:03
Duplicate of #49144

**Closed by joshtrichards** 2024-11-19 15:03 UTC
Labels: bug, 1. to develop, feature: apps management, regression, 30-feedback, 31-feedback
