### ISSUE TITLE
You can set an invalid date as expiration date for sharing if you preview an image

### ISSUE THREAD

**Issue by GiantCrocodile** [nextcloud/server#6595] opened 2017-09-20 22:17 UTC
Just preview an image in gallery and try to set an expiration date while preview is open. No calendar pops up and you have no clue which format for the date is expected as input. This happens with latest version of NextCloud.

If you set an expiration date outside of the preview, you can't see what's set as expiration date in preview mode.

**Comment by GiantCrocodile** [comment] 2017-09-20 22:21
Related error to this:
```
{
   "reqId":"<removed>",
   "level":3,
   "time":"<removed>",
   "remoteAddr":"<removed>",
   "user":"<removed>",
   "app":"PHP",
   "method":"PUT",
   "url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/1?format=json",
   "message":"DateTime::__construct(): Failed to parse time string (01012017) at position 7 (7): Unexpected character at \/var\/www\/nextcloud\/apps\/files_sharing\/lib\/Controller\/ShareAPIController.php#862",
   "userAgent":"<removed>",
   "version":"12.0.3.3"
}
```

**Comment by blizzz** [comment] 2017-09-25 14:20
Duplicate of https://github.com/nextcloud/gallery/issues/313 (anyway belongs to Gallery repo)

**Closed by blizzz** 2017-09-25 14:20 UTC
