### ISSUE TITLE
NC20beta3 : Logging page is empty

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#22568] opened 2020-09-03 18:59 UTC
### Steps to reproduce
1. Go to Settings->Administration
2. Click Logging
3. Observe emptiness

### Expected behaviour
The current log to be shown

### Actual behaviour
Nothing shown, just empty page

### Server configuration

**Operating system:** CentOS 6.10, x64

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.21

**Nextcloud version:** (see Nextcloud admin page) 20.0.3 beta

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** automatic update

**Comment by szaimen** [comment] 2021-06-09 14:10
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-09 14:10 UTC
Labels: 0. Needs triage, 20-feedback, bug
