### ISSUE TITLE
Nextcloud/Files should show copy/delete operation progress

### ISSUE THREAD

**Issue by tomasz-grobelny** [nextcloud/server#13807] opened 2019-01-24 22:07 UTC
**Is your feature request related to a problem? Please describe.**
When trying to copy/delete/move a lot of files (think photos from vacation) between folders it is hard to know what is the progress of the operation. Additionally all requests are sent to server at once so the server might get overloaded.

**Describe the solution you'd like**
A progress bar for copy/delete/move operation should be displayed.

**Describe alternatives you've considered**
A soft and calm voice describing how long I will need to wait :-)

**Additional context**
It is already implemented on https://github.com/nextcloud/server/pull/12652 - it just needs to be merged. Please note that first part of this feature (rate limiting for move operation) has already been merged.

**Comment by joshtrichards** [comment] 2023-05-30 13:20
This has since been merged into NC16 - seems we can close Issue this out, no?

**Comment by skjnldsv** [comment] 2023-06-20 15:32
> This has since been merged into NC16 - seems we can close Issue this out, no?

This was not fully part of 16.
I think there is still some room for improvements

**Comment by pipsen** [comment] 2024-07-26 13:21
I am using Nextcloud 28.0.4 and do not see any progress bar, when I copy big files. Should it be in place now? Do I need to configure something? Thank you!

**Comment by joshtrichards** [comment] 2024-09-23 14:20
@pipsen & @Kofl You'll note this issue is still open. ;)

**Comment by joshtrichards** [comment] 2024-09-23 14:23
Duplicate of #11322

**Closed by joshtrichards** 2024-09-23 14:23 UTC
Labels: enhancement, 1. to develop, feature: files
