### ISSUE TITLE
trash bin does not work (empty) [Bug]: 

### ISSUE THREAD

**Issue by ace02000** [nextcloud/server#43208] opened 2024-01-30 13:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,
I updated my nextcloud instance to version 27.1.6 recently.
Since this version the trash bin does not work anymore. I cannot see any file in the trash bin I deleted. The bin is empty all the time but the files exists on the storage.

### Steps to reproduce

1. delete any file
2. take a look at the trash bin
3. trash bin is empty, but files are present on the storage

### Expected behavior

deleted files are present in the trash bin

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-01-30 16:38
Duplicate of #43134
Fixed in #43136

**Closed by joshtrichards** 2024-01-30 16:38 UTC
Labels: bug, 0. Needs triage, 27-feedback

**Comment by sistemi-nv** [comment] 2024-02-06 20:36
Unexpert user: how can I apply this fix without updating the whole Nextcloud version (last v.28 has other more annoying bugs ...)
Many thanks.
g
