### ISSUE TITLE
Problems with the Editor and not-Markdown Files

### ISSUE THREAD

**Issue by Yasu-San** [nextcloud/server#20165] opened 2020-03-25 14:31 UTC
If I open any Text-File in the interface, that is not a Markdown-File, the Editor loads infinitely. A look into the Network-Traffic shows that the content of the file is sent to the Frontend.
*.txt-Files sometimes work but Files like *.java, *.xml or *.yaml won’t.

### Steps to reproduce
1. Upload any non Markdown-File
2. Open the Network-Tab of the Developer tools in your Browser (optional, can be skipped)
3. Try to open the file within the Web-Interface
4. Wait

### Expected behaviour
The content of the file is displayed

### Actual behaviour
Infinite loading animation

### Server configuration

**Operating system:**
Debian 10.3
**Web server:**
Apache 2.4.38
**Database:**
10.3.22-MariaDB
**PHP version:**
7.3.15
**Nextcloud version:** (see Nextcloud admin page)
since 18.0.2 (still exists in 18.0.3 and 18.0.4)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older NextCloud
**Where did you install Nextcloud from:**
https://nextcloud.com/install/
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - bruteforcesettings: 1.5.0
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - data_request: 1.5.0
  - dav: 1.14.0
  - deck: 0.8.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_antivirus: 2.2.1
  - files_automatedtagging: 1.8.2
  - files_downloadactivity: 1.7.0
  - files_mindmap: 0.0.20
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.3
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.2
  - settings: 1.0.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '[REMOVED]',
  'passwordsalt' => '[REMOVED]',
  'secret' => '[REMOVED]',
  'trusted_domains' =>
  array (
    0 => 'cloud.domain.tld',
  ),
  'datadirectory' => '/var/www/domain/cloud/data',
  'overwrite.cli.url' => 'https://cloud.domain.tld',
  'dbtype' => 'mysql',
  'version' => '18.0.3.0',
  'dbname' => '[REMOVED]',
  'dbhost' => '[REMOVED]',
  'dbport' => '',
  'dbtableprefix' => '[REMOVED]',
  'mysql.utf8mb4' => true,
  'dbuser' => '[REMOVED]',
  'dbpassword' => '[REMOVED]',
  'installed' => true,
  'htaccess.RewriteBase' => '/',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'cloud',
  'mail_domain' => '[REMOVED]',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '[REMOVED]',
  'mail_smtpport' => '[REMOVED]',
  'mail_smtpname' => '[REMOVED]',
  'mail_smtppassword' => '[REMOVED]',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_sendmailmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'updater.release.channel' => 'stable',
  'default_language' => 'de',
  'default_locale' => 'de',
  'allow_user_to_change_display_name' => false,
  'updater.secret' => '[REMOVED]',
);
```
</details>

**Are you using external storage, if yes which one:**
No
**Are you using encryption:**
No
**Are you using an external user-backend, if yes which one:**
No

### Client configuration
**Browser:**
Firefox and Chrome
**Operating system:**
Windows 10 and Ubuntu 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Console:
```
WARNING: Opening the viewer with a single string parameter is deprecated. Please use a destructuring object instead OCA.Viewer.open({ path: '/Discord/messages.yaml' }) Viewer.js:97:11
INFO: Opening viewer for file  /Discord/messages.yaml Viewer.vue:211
INFO: Fetching additional files... Viewer.vue:238
ERROR: TypeError: can't define property "compiled": Object is not extensible core.js:597:4
WARNING: moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
WARNING: moment is deprecated: please ship your own, this will be removed in Nextcloud 20 8 globals.js:66:15
```

Network:
```
207	PROPFIND	messages.yaml	xhr	xml	2,20 KB	1,11 KB
200	GET	vendors~editor~preview.js?v=72b18a706c3726bc1ff0	script	js	134,27 KB	440,57 KB
200	GET	vendors~editor~files-modal.js?v=51656dc998450b54a7cb	script	js	21,47 KB	65,74 KB
200	GET	vendors~editor.js?v=cc7933064dc2d2bcb3a8	script	js	25,55 KB	74,82 KB
200	GET	editor.js?v=f37f6f59ed03e030d5f2	script	js	19,59 KB	83,03 KB
200	GET	create?fileId=5033&filePath=/Discord/messages.yaml&guestName=null&forceRecreate=false	xhr	json	1,43 KB	359 B
200	GET	vendors~editor-collab~editor-guest~editor-rich~files-modal.js?v=5f4c5699d284b9a3c962	script	js	8,22 KB	19,23 KB
200	GET	vendors~editor-collab~editor-guest.js?v=b5a9460c5a2f943e7e14	script	js	23,33 KB	70,78 KB
200	GET	editor-collab.js?v=12f399c85539bb8b7bbe	script	js	7,26 KB	22,93 KB
200	GET	vendors~editor-rich.js?v=e8ad391a5038cb86f616	script	js	19,89 KB	69,70 KB
200	GET	editor-rich.js?v=2d34ed96375859e71bde	script	js	8,46 KB	23,92 KB
200	GET	fetch?documentId=5033&sessionId=319&sessionToken=SvZpARWkm5Dv1vO4t4+9MmXL26Fpl0TqSstCa9YwwruJBDnBQno58TaYrk0NLAuk	xhr	html	2,02 KB	1,85 KB
200	GET	yaml.js?v=27c9dc9bdd78a1056f98	script	js	1,53 KB	1,23 KB
200	GET	notifications	xhr	json	1,19 KB	74 B
```

</details>

**Comment by Axehaft** [comment] 2020-04-15 15:37
I have the same problem.  Cannot edit .txt files ... only .md files.  The editor opens and hangs.

**Comment by XSBen** [comment] 2020-04-20 20:27
Same for me:

Nextcloud version: (see Nextcloud admin page)
since 18.0.0 (still exists in 18.0.3)

Firefox 75.0 javascript log:
```
Opening viewer for file  /***** Viewer.vue:211
Fetching additional files... Viewer.vue:238
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:66:15
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
TypeError: can't define property "compiled": Object is not extensible
core.js:597:4
recommendations 
Array [ {…} ]
SharingInput.vue:292
```

Chromium 62.0:
```
Opening viewer for file  /LR-ID/test.php
core.js:597 Uncaught (in promise) TypeError: Cannot add property compiled, object is not extensible
    at e (core.js:597)
    at core.js:673
    at e (core.js:647)
    at core.js:589
    at S (core.js:198)
    at i.x [as highlightAuto] (core.js:82)
    at extensions.esm.js:414
    at Array.forEach (<anonymous>)
    at Z (extensions.esm.js:412)
    at _.init (extensions.esm.js:440)
    at Function.x.create (index.es.js:888)
    at e.value (tiptap.esm.js:1148)
    at e.value (tiptap.esm.js:1233)
    at e.value (tiptap.esm.js:1052)
    at new e (tiptap.esm.js:1026)
    at ne (EditorFactory.js:98)
    at EditorWrapper.vue:301
```

**Comment by ynuyasha** [comment] 2020-04-27 13:55
> 
> 
> Same for me:
> 
> Nextcloud version: (see Nextcloud admin page)
> since 18.0.0 (still exists in 18.0.3)
> 
> Firefox 75.0 javascript log:
> 
> ```
> Opening viewer for file  /***** Viewer.vue:211
> Fetching additional files... Viewer.vue:238
> The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
> The escapeHTML library is deprecated! It will be removed in nextcloud 19. globals.js:66:15
> The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
> The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
> TypeError: can't define property "compiled": Object is not extensible
> core.js:597:4
> recommendations 
> Array [ {…} ]
> SharingInput.vue:292
> ```
> 
> Chromium 62.0:
> 
> ```
> Opening viewer for file  /LR-ID/test.php
> core.js:597 Uncaught (in promise) TypeError: Cannot add property compiled, object is not extensible
>     at e (core.js:597)
>     at core.js:673
>     at e (core.js:647)
>     at core.js:589
>     at S (core.js:198)
>     at i.x [as highlightAuto] (core.js:82)
>     at extensions.esm.js:414
>     at Array.forEach (<anonymous>)
>     at Z (extensions.esm.js:412)
>     at _.init (extensions.esm.js:440)
>     at Function.x.create (index.es.js:888)
>     at e.value (tiptap.esm.js:1148)
>     at e.value (tiptap.esm.js:1233)
>     at e.value (tiptap.esm.js:1052)
>     at new e (tiptap.esm.js:1026)
>     at ne (EditorFactory.js:98)
>     at EditorWrapper.vue:301
> ```

Same for me same logs inside console of firefox

**Comment by noseshimself** [comment] 2020-04-29 20:16
Probably the wrong place for this issue report -- this should go to icewind1991/files_markdown, see https://github.com/icewind1991/files_markdown

**Comment by szaimen** [comment] 2021-05-31 14:02
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-05-31 14:02 UTC
Labels: 0. Needs triage, bug
