### ISSUE TITLE
Editing / Deleting one occurrence of a recurring calendar event →  2nd invitation IMIT mail is very confusing

### ISSUE THREAD

**Issue by kusmi** [nextcloud/server#21220] opened 2020-06-04 07:03 UTC
### Steps to reproduce
1. Set a new recurring calendar event (e.g. starting from June 1, 10:00, every week)
2. Add an external attendee and click save
3. Normal invitation email is sent out → all ok
4. Reschedule a single occurrence (e.g. move the June 22, 10:00 event to 15:00) and save
5. Another email notification is sent out, but the text is very confusing: "You have been invited to ... June 1, 10:00) - so the old date is still displayed in email, no mention of the rescheduling of the June 22 event.

### Expected behaviour
Second notification email should state, that the June 22 event has been rescheduled.

### Actual behaviour
Second notification email does not display the rescheduled date/time. Instead the same email is sent out as in original notification email (just without accept button)

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** It happens with Nextcloud webversion, as well if I reschedule on CalDAV-clients (e.g. macOS Calendar app)

### Client configuration
**Browser:** Safari 13.1.1 (15609.2.9.1.2)

**Operating system:** macOS 10.15.5 (19F101)

### Server configuration

**Operating system**: Hetzner NextCloud

**Web server:** Hetzner NextCloud

**Database:** mysql 10.3.23

**PHP version:** 7.3.17

**Nextcloud Version:** 18.0.4

**Updated from an older installed version or fresh install:** Updated from 17 - but long time ago
![Initial Email](https://user-images.githubusercontent.com/448222/83726487-e0a2b280-a643-11ea-8af3-d65f7bb8c34b.jpg)
![2nd Email](https://user-images.githubusercontent.com/448222/83726501-e39da300-a643-11ea-9a14-a5dc5b8883f9.jpg)

**Comment by nickvergessen** [comment] 2021-09-21 11:41
An attempt to fix this was done in https://github.com/nextcloud/server/pull/13892 already.
It improved the situation a bit, but still fails partly as:
* It would always show the next occurrence (✅  if all future occurrences are modified, ❌ when only some future occurrences are modified)
* It should should the one modified occurrence that when only one was changed instead of all future occurrences after X

**Comment by goodfrank** [comment] 2022-03-29 12:07
What's the status of this issue?

**Comment by szaimen** [comment] 2023-01-09 16:33
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by nickvergessen** [comment] 2023-01-09 17:38
Yes, every day

**Comment by SebastianKrupinski** [comment] 2024-07-17 20:35
Duplicate of #38686

**Closed** 2024-07-17 20:36 UTC
Labels: bug, 1. to develop, feature: dav, feature: caldav, 26-feedback
