### ISSUE TITLE
Force SSL via button 

### ISSUE THREAD

**Issue by wmcgit** [nextcloud/server#4171] opened 2017-03-31 09:34 UTC
Hi, 

I am running the version 11.0.2 on a webhosting server (Host Europe).

Remembereing the last versions of OwnCloud there´s been a switch to force SSL.

As I am not the most advanced devloper in terms of editing the htaccess file, I wanted to ask: Is there any way to bring this button back? 

How can I force my Nextcloud to use SSL?
I can still access it via http://

Kind regards,
Benedikt

**Comment by MorrisJobke** [comment] 2017-04-03 22:39
Duplicate of https://github.com/nextcloud/server/issues/132

**Closed by MorrisJobke** 2017-04-03 22:39 UTC
