### ISSUE TITLE
Hide certain Apps in App Store (as server admin)

### ISSUE THREAD

**Issue by benks-io** [nextcloud/server#24815] opened 2020-12-22 14:49 UTC
## Situation
As a provider of Nextcloud instances or the admin of one Instance on OS Level, you may want your users (the "owner" of the instance) to be as independent from you as possible. The owner should be able to add users, groups and also install apps. Right now that's only possible by providing an admin account to the owner. It's very easy now for the owner to install apps. But as admin of the nextcloud instance you may not want certain apps do be installed at all for different reasons.

## Problem
Right now admins of an instance have no easy opportunity to hide apps in the app store to prevent them from being installed.

## Proposal
There should be a way to hide certain apps in the app store or only show certain apps.
I am thinking of occ commands like:

  occ app:availability:hide $APPNAME
  occ app:availability:hide_all
  occ app:availability:show $APPNAME
  occ app:availability:show_all
  occ app:availability:default hide
  occ app:availability:default show

This would give the admin of the instance the possibility to organize available apps

- as a black list (certain apps cannot be installed, every new app can still be installed)
- as a white list (only marked apps can be installed at all, new apps will only become available when white listed)

**Comment by benks-io** [comment] 2020-12-22 14:56
In addition to that it would be worth discussing a feature like showing only featured apps

  occ app:availablity:default show_only_featured_apps

**Comment by kesselb** [comment] 2020-12-22 17:10
Duplicate of #21057

**Closed by kesselb** 2020-12-22 17:10 UTC
Labels: 0. Needs triage, enhancement
