### ISSUE TITLE
GPDR: Add Legal notice link and Privacy policy link when nextcloud is in maintenance mode

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#13641] opened 2019-01-17 09:36 UTC
**Is your feature request related to a problem? Please describe.**
Due to the GPDR, a legal notice link and link to privacy statement are necessary.
At the login page legal notice link and link to privacy statement can be added, but if nextcloud is in maintenance mode, these links are not displayed.

**Describe the solution you'd like**
Also in maintenance mode, legal notice link and link to privacy policy should be displayed.
In addition, the individual slogan could also be displayed as well.

**Additional context**
Current page in maintenance mode without necessary links to legal notice and privacy statement:
![nextcloud](https://user-images.githubusercontent.com/34692335/51308418-5a7fcf00-1a42-11e9-9a23-2dd73035591d.png)

**Comment by michag86** [comment] 2019-03-11 19:30
I think it would be nice, if maintenance page is themed is completely. But it seems that the problem is, that no apps are loaded, if maintenance mode is enabled. Maybe the theming app can create a static maintenance page on every theme change. And if such a static themed page exists, this is shown in maintenance mode.

cc @MorrisJobke

**Comment by MorrisJobke** [comment] 2019-03-11 21:39
> I think it would be nice, if maintenance page is themed completely. The problem seems to be that no apps are loaded when maintenance mode is enabled. Maybe the theming app can create a static maintenance page on every theme change. And if such a static themed page exists, this is shown in maintenance mode.

Completely different issue - this is about #5789

**Comment by joshtrichards** [comment] 2023-06-16 16:39
Appears to have been addressed:

<img width="649" alt="image" src="https://github.com/nextcloud/server/assets/1731941/cf3cb4b6-e128-481f-86cc-994b36d31ae3">

I think we can close this out.

**Comment by susnux** [comment] 2024-07-11 14:04
Resolved in all supported Nextcloud versions (28+)

**Closed by susnux** 2024-07-11 14:04 UTC
Labels: enhancement, 1. to develop
