### ISSUE TITLE
Can You Add File Support for .tib and .tibx file extensions 

### ISSUE THREAD

**Issue by Daddyoftwins1** [nextcloud/server#36545] opened 2023-02-05 15:21 UTC
I Have been running in to a problem. I thought it was my config. After extensive research and going to the community for help. 
I have determined that the problem is that nextcloud just doesn't support the file extension I'm trying to upload. it doesn't mater if I use the desktop client or webdav the end result is the same. when i try to upload one of my files that's a .tib or .tibx the system gives me errors and it doesn't upload the file to the server. so if you can please add support for .tib and .tibx file extension. i use them a lot for my system backups. 

here are the errors I have been getting when I try to upload these files.

error I get when I try to use the desktop client
[no app in context] Error: Computed md5 hash is incorrect.

POST /remote.php/dav/bulk
from 192.168.1.1 by work at 2023-02-05T14:33:53+00:00

{"reqId":"Q4dUC0BytQHK9roQeTOn","level":3,"time":"2023-02-05T14:34:22+00:00","remoteAddr":"192.168.1.1","user":"work","app":"no app in context","method":"POST","url":"/remote.php/dav/bulk","message":"Computed md5 hash is incorrect.","userAgent":"Mozilla/5.0 (Windows) mirall/3.6.6stable-Win64 (build 20230119) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"25.0.3.2","data":[],"id":"63dfbe6f3be4d"}

error I get when I use the webdav
[PHP] Error: Error: exif_read_data(): File not supported at /var/www/nextcloud/lib/private/Metadata/Provider/ExifProvider.php#59 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /var/www/nextcloud/lib/private/Metadata/Provider/ExifProvider.php line 59
    exif_read_data()
 2. /var/www/nextcloud/lib/private/Metadata/MetadataManager.php line 68
    OC\Metadata\Provider\ExifProvider->execute()
 3. /var/www/nextcloud/lib/private/Metadata/FileEventListener.php line 101
    OC\Metadata\MetadataManager->generateMetadata()
 4. /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php line 87
    OC\Metadata\FileEventListener->handle()
 5. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke()
 6. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 7. /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 88
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
 8. /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 100
    OC\EventDispatcher\EventDispatcher->dispatch()
 9. /var/www/nextcloud/lib/private/Files/Node/HookConnector.php line 118
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
10. /var/www/nextcloud/lib/private/legacy/OC_Hook.php line 106
    OC\Files\Node\HookConnector->postWrite()
11. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 471
    OC_Hook::emit()
12. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 398
    OCA\DAV\Connector\Sabre\File->emitPostHooks()
13. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 151
    OCA\DAV\Connector\Sabre\File->put()
14. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1098
    OCA\DAV\Connector\Sabre\Directory->createFile()
15. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 504
    Sabre\DAV\Server->createFile()
16. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut()
17. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
18. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
19. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
20. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
21. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
22. /var/www/nextcloud/remote.php line 171
    require_once("/var/www/nextcl ... p")

PUT /remote.php/dav/files/work/JOSHDRIVE%204/TOWER%20SOUTH%20BACKUP/DICOMService/DICOMService_WindowService/jre1.8.0_72/lib/images/cursors/win32_CopyDrop32x32.gif
from 192.168.1.1 by work at 2023-02-05T07:09:34+00:00

**Comment by Daddyoftwins1** [comment] 2023-02-18 22:34
is there any way nextcloud could add support for .tib and .tibx file extensions?

**Comment by joshtrichards** [comment] 2023-09-04 12:56
Duplicate of #34958

This was a regression and has since been fixed in #36420.

**Closed by joshtrichards** 2023-09-04 12:56 UTC
Labels: enhancement, 0. Needs triage
