### ISSUE TITLE
An error occured during the request. Unable to proceed in "Users" as admin.

### ISSUE THREAD

**Issue by Bevito** [nextcloud/server#26696] opened 2021-04-22 12:16 UTC
### Steps to reproduce
1. Log in as administrator
2. Go to Users

### Expected behaviour
Tell us what should happen

We shoud see the list of users

### Actual behaviour
Tell us what happens instead

All the groups display "No Users in here" and a window pop-up show "An error occured during the request. Unable to proceed."

### Server configuration

**Operating system:**
Debian 10.9

**Web server:**
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29

**Database:**
Server version: 10.3.27-MariaDB-0+deb10u1 Debian 10

**PHP version:**
PHP 7.3.27-1~deb10u1 (fpm-fcgi) (built: Feb 13 2021 16:31:40)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 21.0.0

**Where did you install Nextcloud from:**
Install / update from auto-updater.
Try reinstalling from tar.bz2 from official website.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 6.3.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maxZipInputSize": 1073741824,
        "allowZipDownload": true,
        "theme": "",
        "overwrite.cli.url": "https:\/\/cloud.iut-orsay.fr",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "default_language": "fr",
        "default_phone_region": "FR",
        "defaultapp": "files,dashboard",
        "auto_logout": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "trusted_domains": [
            "cloud.iut-orsay.fr"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "15, auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 0,
            "timeout": 0
        },
        "onlyoffice": {
            "jwt_secret": "REMOVED SENSITIVE VALUE",
            "jwt_header": "REMOVED SENSITIVE VALUEt"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": "60",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
+-------------------------------+-------------------------------------------------------------------+
| Configuration                 | s01                                                               |
+-------------------------------+-------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                 |
| homeFolderNamingRule          |                                                                   |
| lastJpegPhotoLookup           | 0                                                                 |
| ldapAgentName                 | cn=nextcloud,ou=security,dc=iut-orsay,dc=fr                             |
| ldapAgentPassword             | ***                                                               |
| ldapAttributesForGroupSearch  |                                                                   |
| ldapAttributesForUserSearch   |                                                                   |
| ldapBackupHost                |                                                                   |
| ldapBackupPort                |                                                                   |
| ldapBase                      | dc=iut-orsay,dc=fr                                                |
| ldapBaseGroups                | ou=groups,dc=iut-orsay,dc=fr                                      |
| ldapBaseUsers                 | ou=people,dc=iut-orsay,dc=fr                                      |
| ldapCacheTTL                  | 600                                                               |
| ldapConfigurationActive       | 1                                                                 |
| ldapDefaultPPolicyDN          |                                                                   |
| ldapDynamicGroupMemberURL     |                                                                   |
| ldapEmailAttribute            | mail                                                              |
| ldapExperiencedAdmin          | 1                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                   |
| ldapExpertUUIDUserAttr        |                                                                   |
| ldapExpertUsernameAttr        |                                                                   |
| ldapExtStorageHomeAttribute   | supannAliasLogin                                                  |
| ldapGidNumber                 | gidNumber                                                         |
| ldapGroupDisplayName          | cn                                                                |
| ldapGroupFilter               | objectClass=posixGroup                                            |
| ldapGroupFilterGroups         |                                                                   |
| ldapGroupFilterMode           | 0                                                                 |
| ldapGroupFilterObjectclass    |                                                                   |
| ldapGroupMemberAssocAttr      | memberUid                                                         |
| ldapHost                      | ldaps://ldaps.iut-orsay.fr                                        |
| ldapIgnoreNamingRules         |                                                                   |
| ldapLoginFilter               | (&(objectclass=*)(|(uid=%uid)(mail=%uid)(supannAliasLogin=%uid))) |
| ldapLoginFilterAttributes     |                                                                   |
| ldapLoginFilterEmail          | 0                                                                 |
| ldapLoginFilterMode           | 0                                                                 |
| ldapLoginFilterUsername       | 1                                                                 |
| ldapMatchingRuleInChainState  | unknown                                                           |
| ldapNestedGroups              | 0                                                                 |
| ldapOverrideMainServer        |                                                                   |
| ldapPagingSize                | 500                                                               |
| ldapPort                      | 636                                                               |
| ldapQuotaAttribute            | NextcloudQuota                                                    |
| ldapQuotaDefault              | 10 GB                                                             |
| ldapTLS                       | 0                                                                 |
| ldapUserAvatarRule            | default                                                           |
| ldapUserDisplayName           | displayname                                                       |
| ldapUserDisplayName2          |                                                                   |
| ldapUserFilter                | (objectclass=*)                                                   |
| ldapUserFilterGroups          |                                                                   |
| ldapUserFilterMode            | 0                                                                 |
| ldapUserFilterObjectclass     |                                                                   |
| ldapUuidGroupAttribute        | auto                                                              |
| ldapUuidUserAttribute         | auto                                                              |
| turnOffCertCheck              | 0                                                                 |
| turnOnPasswordChange          | 0                                                                 |
| useMemberOfToDetectMembership | 1                                                                 |
+-------------------------------+-------------------------------------------------------------------+

### Client configuration
**Browser:**
Mozilla Firefox ESR 78.9.0esr (64 bits)

**Operating system:**
Debian 11

#### Browser log

When i open the browser console's : 

XHR GET https://cloud.iut-orsay.fr/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=
[HTTP/1.1 404 Not Found 96ms]

**Comment by acsfer** [comment] 2021-04-23 09:01
Without logs of any sort (Nextcloud, webserver) it is impossible to guess what could be wrong.

**Comment by Bevito** [comment] 2021-04-23 11:54
I don't know If It can helps you, but in browser console's log, I get : 

XHR GET https://cloud.iut-orsay.fr/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=
[HTTP/1.1 404 Not Found 96ms]

Each time I try to access Users list.

In /var/log/apache2/access.log I get : 
ip.address - - [23/Apr/2021:13:48:28 +0200] "GET /ocs/v2.php/cloud/users/details?offset=0&limit=25&search= HTTP/1.1" 404 1285 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"

In /var/log/nextcloud/nextcloud.log I get : 

{"reqId":"iSW3rYqPNwdVm5rbfJ6L","level":3,"time":"2021-04-23T11:49:43+00:00","remoteAddr":"ip.address","user":"42de26f0-dd0b-1034-8d5d-fbe9e42d9fc5","app":"no app in context","method":"GET","url":"/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=","message":{"Exception":"Exception","Message":"Argument 1 passed to Icewind\\SMB\\BasicAuth::__construct() must be of the type string, null given, called in /var/www/html/nextcloud/apps/files_external/lib/Lib/Backend/SMB.php on line 82","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"getUsersDetails"]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","getUsersDetails",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"file":"/var/www/html/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/details"]},{"file":"/var/www/html/nextcloud/ocs/v2.php","line":24,"args":["/var/www/html/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to Icewind\\SMB\\BasicAuth::__construct() must be of the type string, null given, called in /var/www/html/nextcloud/apps/files_external/lib/Lib/Backend/SMB.php on line 82","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/files_external/lib/Lib/Backend/SMB.php","line":82,"function":"__construct","class":"Icewind\\SMB\\BasicAuth","type":"->","args":[null,"ETUD",null]},{"file":"/var/www/html/nextcloud/apps/files_external/lib/Config/ConfigAdapter.php","line":95,"function":"manipulateStorageConfig","class":"OCA\\Files_External\\Lib\\Backend\\SMB","type":"->","args":["*** sensitive parameter replaced ***",{"__class__":"OC\\User\\User"}]},{"file":"/var/www/html/nextcloud/apps/files_external/lib/Config/ConfigAdapter.php","line":132,"function":"prepareStorageConfig","class":"OCA\\Files_External\\Config\\ConfigAdapter","type":"->","args":["*** sensitive parameter replaced ***",{"__class__":"OC\\User\\User"}]},{"function":"OCA\\Files_External\\Config\\{closure}","class":"OCA\\Files_External\\Config\\ConfigAdapter","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/apps/files_external/lib/Config/ConfigAdapter.php","line":130,"function":"array_map","args":[{"__class__":"Closure"},{"1802":{"__class__":"OCA\\Files_External\\Lib\\StorageConfig"},"1803":{"__class__":"OCA\\Files_External\\Lib\\StorageConfig"},"1822":{"__class__":"OCA\\Files_External\\Lib\\StorageConfig"},"1894":{"__class__":"OCA\\Files_External\\Lib\\StorageConfig"}}]},{"file":"/var/www/html/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":109,"function":"getMountsForUser","class":"OCA\\Files_External\\Config\\ConfigAdapter","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Storage\\StorageFactory"}]},{"file":"/var/www/html/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Mount\\Manager"}]},{"file":"/var/www/html/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["0aba7566-8496-1035-9f95-c31b0976acaa"]},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_Util.php","line":324,"function":"init","class":"OC\\Files\\Filesystem","type":"::","args":["0aba7566-8496-1035-9f95-c31b0976acaa","/0aba7566-8496-1035-9f95-c31b0976acaa/files"]},{"file":"/var/www/html/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php","line":213,"function":"setupFS","class":"OC_Util","type":"::","args":["0aba7566-8496-1035-9f95-c31b0976acaa"]},{"file":"/var/www/html/nextcloud/apps/provisioning_api/lib/Controller/AUserData.php","line":140,"function":"fillStorageInfo","class":"OCA\\Provisioning_API\\Controller\\AUserData","type":"->","args":["0aba7566-8496-1035-9f95-c31b0976acaa"]},{"file":"/var/www/html/nextcloud/apps/provisioning_api/lib/Controller/UsersController.php","line":200,"function":"getUserData","class":"OCA\\Provisioning_API\\Controller\\AUserData","type":"->","args":["0aba7566-8496-1035-9f95-c31b0976acaa"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"getUsersDetails","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["",25,0]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"getUsersDetails"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"getUsersDetails"]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","getUsersDetails",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.getUsersDetails"}]},{"file":"/var/www/html/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/details"]},{"file":"/var/www/html/nextcloud/ocs/v2.php","line":24,"args":["/var/www/html/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/apps/files_external/3rdparty/icewind/smb/src/BasicAuth.php","Line":32},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"21.0.1.1"}

I hope this can help.

Thanks a lot.

**Comment by acsfer** [comment] 2021-04-23 12:33
Duplicate of https://github.com/nextcloud/server/issues/26697 (same error).

**Closed by acsfer** 2021-04-23 12:33 UTC
Labels: 0. Needs triage, bug, needs info
