### ISSUE TITLE
Upgrade to 17.0.2

### ISSUE THREAD

**Issue by sunstar100** [nextcloud/server#18658] opened 2020-01-04 20:47 UTC
### Steps to reproduce
1. Upgrade via Web interface
2. Upgrade via CLI (sudo -u www-data php updater.phar)
3.

### Expected behaviour
The upgrade runs as normal and the server is accessible and ready for use, outside of maintenance mode

### Actual behaviour
The upgrade begins and runs fine until there is a database error.  Instead the CLI tells me there is an error and it asks if I want to leave the nextcloud server in maintenance mode.  This is the error that is returned

Repair step: Add preview background cleanup job

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `id` FROM `oc_jobs` WHERE (`class` = ?) AND (`argument` = ?) LIMIT 1' with params ["OC\\Preview\\BackgroundCleanupJob", "null"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### Server configuration

**Operating system:**
Ubuntu  18.04.3

**Web server:**
Apache

**Database:**
mysql  Ver 15.1 Distrib 10.1.43-MariaDB

**PHP version:**
7.2.26

**Nextcloud version:** (see Nextcloud admin page)
17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
cd /var/www/nextcloud/updater/;sudo -u www-data php updater.phar

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 

Not found
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
 - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - checksum
  - dashboard
  - encryption
  - files_antivirus
  - files_external
  - keeporsweep
  - ocdownloader
  - phonetrack
  - ransomware_detection
  - unsplash
  - user_ldap
  - weather

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.102",
            "bradwalsh.ddns.net",
            "100.10.48.178",
            "walshman.biz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "overwrite.cli.url": "http:\/\/192.168.1.102\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No


### Client configuration
Chrome 79.0.3945.88

**Operating system:**
Windows 10
[access.log](https://github.com/nextcloud/server/files/4022415/access.log)

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
I am getting an access denied.  It is owned by www-data user and I used sudo -i to no avail.  If this is critical to get this log (and I believe that it will be) I will keep working to get around it.
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by t-markmann** [comment] 2020-01-09 10:18
Related to CLI install bug https://github.com/nextcloud/server/issues/18569 ?

**Comment by kesselb** [comment] 2020-01-09 10:26
Looks like https://github.com/nextcloud/server/issues/18513

**Comment by sunstar100** [comment] 2020-01-09 20:38
I looked at both of those bugs, and #18513 looks similar, but still a bit different.  I couldn't find what the actual fix was for #18513

**Comment by HLFH** [comment] 2020-01-17 13:55
The other issue you can have after upgrading to 17.0.2 is they still offer you to upgrade to 17.0.2 even if you have already upgraded Nextcloud to 17.0.2!

<img width="1044" alt="Screenshot 2020-01-17 at 13 54 28" src="https://user-images.githubusercontent.com/2359059/72617524-05b2b500-3931-11ea-9ebd-b5ed07799ebb.png">

**Comment by kesselb** [comment] 2020-01-17 14:30
@HLFH how is that related to the first report? Please open a new issue if you are able to reproduce it somehow. Sorry I don't see how "General error: 2006 MySQL server has gone away" and "I still see the Update notification" are related. Except the same version but a big issue with all problems for one specific version is not how an bug tracker works :smile:

**Comment by HLFH** [comment] 2020-01-17 16:12
@kesselb The upgrade system of Nextcloud has always been messed up. And the issue title "Upgrade to 17.0.2" is implying you can group bugs in one issue page related to the 17.0.2 upgrade. Otherwise, precise the title.

**Comment by kesselb** [comment] 2020-01-17 16:37
@HLFH I'm sorry. "how is that related to the first report" was probably a bit rude. For general questions https://help.nextcloud.com/ or to report a new issue https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md (those information are required).

**Comment by kesselb** [comment] 2021-05-29 14:54
Closing as 17 is EOL

**Closed** 2021-05-29 14:53 UTC
Labels: 0. Needs triage, bug, needs info
