### ISSUE TITLE
Issue with QueryBuilder and Postgres 10.X

### ISSUE THREAD

**Issue by protheusfr** [nextcloud/server#8953] opened 2018-03-22 18:37 UTC
### Steps to reproduce
1. Install Nextcloud V13.0.1 with PostgreSQL 10.3
2. Add Calendar plugin
3. Connect any CalDav Device

### Expected behaviour
Ability to sync remote device through CalDav

### Actual behaviour
HTTP 500 on remote with this kind of message on event logger : 
```
Fatal	webdav	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "schedulingobjects" ("principaluri", "calendardata", "uri", "lastmodified", "etag", "size") VALUES(?, ?, ?, ?, ?, ?)' with params ["principals\/users\/bastien", "BEGIN:VCALENDAR\r\nV...\nEND:VCALENDAR\r\n", "sabredav-7af52ab3-57f0-4cb4-b7e7-39ca028a6ee5.ics", 1521743120, "cfd6e3a665541f094c641fadd0fda611", 2036]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bytea
/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1015: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO "sc...', Array)
/var/www/html/lib/private/DB/Connection.php - line 216: Doctrine\DBAL\Connection->executeUpdate('INSERT INTO "sc...', Array, Array)
/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 208: OC\DB\Connection->executeUpdate('INSERT INTO "sc...', Array, Array)
/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214: Doctrine\DBAL\Query\QueryBuilder->execute()
/var/www/html/apps/dav/lib/CalDAV/CalDavBackend.php - line 1994: OC\DB\QueryBuilder\QueryBuilder->execute()
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Inbox.php - line 106: OCA\DAV\CalDAV\CalDavBackend->createSchedulingObject('principals/user...', 'sabredav-7af52a...', 'BEGIN VCALENDAR...')
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php - line 538: Sabre\CalDAV\Schedule\Inbox->createFile('sabredav-7af52a...', 'BEGIN VCALENDAR...')
[internal function] Sabre\CalDAV\Schedule\Plugin->scheduleLocalDelivery(Object(Sabre\VObject\ITip\Message))
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php - line 384: Sabre\Event\EventEmitter->emit('schedule', Array)
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php - line 665: Sabre\CalDAV\Schedule\Plugin->deliver(Object(Sabre\VObject\ITip\Message))
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php - line 367: Sabre\CalDAV\Schedule\Plugin->processICalendarChange(Object(Sabre\VObject\Component\VCalendar), Object(Sabre\VObject\Component\VCalendar), Array, Array, true)
[internal function] Sabre\CalDAV\Schedule\Plugin->calendarObjectChange(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), Object(Sabre\VObject\Component\VCalendar), 'calendars/charl...', true, false)
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 943: Sabre\Event\EventEmitter->emit('calendarObjectC...', Array)
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 772: Sabre\CalDAV\Plugin->validateICalendar('BEGIN VCALENDAR...', 'calendars/charl...', false, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), false)
[internal function] Sabre\CalDAV\Plugin->beforeWriteContent('calendars/charl...', Object(OCA\DAV\CalDAV\CalendarObject), 'BEGIN VCALENDAR...', false)
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1128: Sabre\Event\EventEmitter->emit('beforeWriteCont...', Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 513: Sabre\DAV\Server->updateFile('calendars/charl...', 'BEGIN VCALENDAR...', NULL)
[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
/var/www/html/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
/var/www/html/remote.php - line 164: require_once('/var/www/html/a...')
{main}
```

### Server configuration

**Operating system**:
Docker / Linux
**Web server:**
Official docker image
**Database:**
Postgresql 10.3
**PHP version:**
Official docker image
**Nextcloud version:** (see Nextcloud admin page)
13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Official docker image
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.1.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - weather: 1.5.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.43.0.4",
            "cloud.libmed.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/10.43.0.4",
        "dbtype": "pgsql",
        "version": "13.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Only mounted volume

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Any
**Operating system:**
Any

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no log
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
contain personal data.
```
</details>

**Comment by protheusfr** [comment] 2018-03-27 07:04
Hello,
Any updates on that?

**Comment by go2sh** [comment] 2018-03-27 07:57
Duplicate of #8825. See my answer their and the comment above for a workaround. (Remove non ASCII chars from the event.)

**Comment by protheusfr** [comment] 2018-03-27 08:19
Thank you @go2sh , anyway force user to remove all non ascii chars from the event will no be really easy.
Any idea for a fix delay ?

**Comment by MorrisJobke** [comment] 2018-04-16 22:19
> Duplicate of #8825.

Let's close this then.

**Closed by MorrisJobke** 2018-04-16 22:19 UTC
