### ISSUE TITLE
PHP 7.3 / NC 15: PHP Fatal error:  Interface 'OCP\\User\\Backend\\IGetHomeBackend' not found

### ISSUE THREAD

**Issue by himpierre** [nextcloud/server#12972] opened 2018-12-10 13:53 UTC
Hi Devs.

After Upgrading my NC 14 Installation to 15 i get:

`
[Mon Dec 10 14:46:55.699672 2018] [php7:error] [pid 1726:tid 140365008979712] [client xxx.xxx.xxx.xxx:55876] PHP Fatal error:  Interface 'OCP\\User\\Backend\\IGetHomeBackend' not found in /var/www/cloud.domainreplaced.de/htdocs/lib/private/User/Database.php on line 78
`

After downgrading PHP to 7.2 everything works as expected.

### Steps to reproduce
1. Install PHP 7.3
2. Upgrade NC 14 to NC 15
3. PHP Fatal error

### Expected behaviour

Working NC Installation.

### Actual behaviour

White Page.

### Server configuration

Apache 2.4
PHP 7.3

**Comment by skjnldsv** [comment] 2019-08-15 06:01
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-08-15 06:01 UTC
Labels: 0. Needs triage, bug, needs info
