### ISSUE TITLE
External Storage settings not visible when using LDAP authenticated account

### ISSUE THREAD

**Issue by bitJericho** [nextcloud/server#1710] opened 2016-10-12 00:28 UTC
### Steps to reproduce
1. Setup LDAP authentication
2. Setup external storage, and set "Allow users to mount external storage"
3. Login with LDAP account
4. Go to Personal settings
5. Option to mount external storage is not visible.

### Expected behaviour
External storage settings should be available for all accounts.

### Actual behaviour
External storage in personal settings is not visible.

### Server configuration
Ubuntu 16.04 LTS (and Windows 2016 AD for LDAP database)

**Web server:**
Apache2 & PHP7.0-FPM

**Database:**
Mysql

**PHP version:**
PHP7

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0.1 (beta)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Archive File

**Signing status:**
<details>
<summary>Integrity checker has been disabled. Integrity cannot be verified.</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - apporder: 0.3.2
  - audioplayer: 1.2.2.3
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.5.3
  - news: 9.0.4
  - notifications: 0.3.0
  - ojsxc: 3.0.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - passwords: 19
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - richdocuments
  - templateeditor
  - user_external
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config</summary>
```json
{
    "system": {
        "instanceid": "ocod8wix8ydo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/nextcloud_data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "beta",
        "loglevel": 1
    }
}
```

</details>

**Are you using external storage, if yes which one:** None yet configured

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP configuration</summary>
```
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                                                    |
| homeFolderNamingRule          |                                                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                                                  |
| ldapAgentName                 | cn=nextcloud,cn=Users,dc=Example,dc=com                                                                                                                             |
| ldapAgentPassword             | ***                                                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                                                                                    |
| ldapBackupHost                |                                                                                                                                                                    |
| ldapBackupPort                |                                                                                                                                                                    |
| ldapBase                      | dc=Example,dc=com                                                                                                                                                   |
| ldapBaseGroups                | dc=Example,dc=com                                                                                                                                                   |
| ldapBaseUsers                 | dc=Example,dc=com                                                                                                                                                   |
| ldapCacheTTL                  | 600                                                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                    |
| ldapEmailAttribute            |                                                                                                                                                                    |
| ldapExperiencedAdmin          | 0                                                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                    |
| ldapExpertUsernameAttr        |                                                                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                                                                 |
| ldapGroupFilter               | (|(cn=NextCloudUsers))                                                                                                                                             |
| ldapGroupFilterGroups         | NextCloudUsers                                                                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                                                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                       |
| ldapHost                      | hostname.example.com                                                                                                                                              |
| ldapIgnoreNamingRules         |                                                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=NextCloudUsers,DC=Example,DC=com)(primaryGroupID=1107))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                                                    |
| ldapLoginFilterEmail          | 1                                                                                                                                                                  |
| ldapLoginFilterMode           | 0                                                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                                                |
| ldapPort                      | 389                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                                                  |
| ldapUserDisplayName           | displayName                                                                                                                                                        |
| ldapUserDisplayName2          |                                                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=NextCloudUsers,DC=Example,DC=com)(primaryGroupID=1107))))                                                                   |
| ldapUserFilterGroups          | NextCloudUsers                                                                                                                                                     |
| ldapUserFilterMode            | 0                                                                                                                                                                  |
| ldapUserFilterObjectclass     | user                                                                                                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                                                  |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
IE 11 and FF 49

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>No relevant entries found</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>No relevant entries found</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>No relevant entries found</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment] 2016-10-12 08:11
Fix in progress https://github.com/nextcloud/server/pull/1709

**Comment by blizzz** [comment] 2016-10-12 10:27
And duplicate of #1251

**Closed by blizzz** 2016-10-12 10:27 UTC
Labels: bug, feature: external storage, feature: ldap
