### ISSUE TITLE
the file list is disappear.

### ISSUE THREAD

**Issue by HelloLemon1992** [nextcloud/server#13046] opened 2018-12-13 08:46 UTC
![image](https://user-images.githubusercontent.com/10297287/49926202-04c17f80-fef6-11e8-9646-b024690cdfb5.png)

![image](https://user-images.githubusercontent.com/10297287/49926424-7ef20400-fef6-11e8-98db-25e2c15a4269.png)

### Steps to reproduce
1. click in orber from the example image;
2. the files list is disapper;

### Client configuration
**Browser:** chrome

**Operating system:** windows 10

**Comment by violoncelloch** [comment] 2018-12-15 13:47
duplicate of #10770?

**Comment by violoncelloCH** [comment] 2018-12-21 21:23
can you check in your browser console > Network:
on click of "recent" there should come in a new GET request for `recent`
click on `recent` and go to RESPONSE and copy this JSON response

**Comment by HelloLemon1992** [comment] 2018-12-24 01:36
in this case, when I go step 5, the 'recent' request is not send;
and I resolved it, but I don't know if anything will happen;

apps/files/js/filelist.js

```
		_onShow: function(e) {
			if (this.shown) {
			//if (this.shown) {
			if (true) {
				this._setCurrentDir('/', false);
				this.reload();
			}

```

**Comment by violoncelloCH** [comment] 2018-12-25 22:08
what do you mean with 
> but I don't know if anything will happen;

?

If you have an idea how to fix this, your very welcome to create a Pull Request for it, so it can be properly tested...

**Comment by skjnldsv** [comment] 2019-08-15 06:06
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2019-08-15 06:06 UTC
Labels: 0. Needs triage, bug
