### ISSUE TITLE
file sizes are bad readable in dark theme

### ISSUE THREAD

**Issue by fabianfrz** [nextcloud/server#14003] opened 2019-02-03 11:26 UTC
### Steps to reproduce
1. choose the dark theme beta in the user settings
2. go back to files

### Expected behaviour
* file size should be gray or white to have a good contrast to the background

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/3713914/52176074-131d7080-27ae-11e9-89cb-95aa27ca710a.png)

### Server configuration

**Operating system**: Arch Linux

**Web server:** nginx

**Database:** sqlite

**PHP version:** 7.x

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** tar.gz

**Comment by violoncelloCH** [comment] 2019-02-05 11:15
cc @nextcloud/designers 
it does not only happen in dark theme mode... I've the same in the light theme, there it is white font on white backgound...
the strange thing is not for all files/folders... maybe it depends on the actually displayed filesize? I see it for files/folders with more than ~20MB

**Comment by juliushaertl** [comment] 2019-02-05 12:30
Yes, we should probably move this from a fixed color calclulation to just the main textcolor and setting the opacity depending on the size/modification date.

**Comment by skjnldsv** [comment] 2019-02-05 13:59
There is a duplicate of this issue somewhere I think :)

**Comment by Lartza** [comment] 2019-02-09 08:30
It was supposedly fixed in https://github.com/nextcloud/server/pull/11823 so I think all previous issues are closed.

**Comment by juliushaertl** [comment] 2019-02-11 15:23
Closing since I cannot reproduce this on latest Nextcloud 15.

**Closed by juliushaertl** 2019-02-11 15:23 UTC
Labels: 1. to develop, bug, design, good first issue
