### ISSUE TITLE
[Bug]: Stuck on "Processing Files" after folder upload

### ISSUE THREAD

**Issue by rainbob5** [nextcloud/server#41066] opened 2023-10-23 14:47 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I'm trying to upload a 459MB folder containing 178 files, the upload is quite fast, less than a minute but it's stuck at "Processing Files" on the progress bar. If I reload the page and re-download the uploaded data, I can see there's only 177 files in the folder. Upload of big single files (600MB) works well, I don't even see a "Processing File" step, 

There's no errors on logs, Nextcloud is on Docker, up to date (27.1.2).

Thanks for your help.

### Steps to reproduce

1. Try to upload a folder with lots of files ( >100)
2. Progress bar goes to 100% then displays "Processing files..."
3. It's stuck, upload is incomplete if your reload the page

### Expected behavior

Upload of folders with >100 files should work

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwriteprotocol": "https",
        "skeletondirectory": "",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "default_language": "fr",
        "default_phone_region": "FR",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "admin"
        ],
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.10.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_versions: 1.20.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - activity: 2.19.0 (installed 2.19.0)
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1 (installed 27.0.1)
  - comments: 1.17.0 (installed 1.17.0)
  - contactsinteraction: 1.8.0 (installed 1.8.0)
  - dashboard: 7.7.0 (installed 7.7.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.17.0)
  - files_trashbin: 1.17.0 (installed 1.17.0)
  - firstrunwizard: 2.16.0 (installed 2.16.0)
  - nextcloud_announcements: 1.16.0 (installed 1.16.0)
  - password_policy: 1.17.0 (installed 1.17.0)
  - recommendations: 1.6.0 (installed 1.6.0)
  - related_resources: 1.2.0 (installed 1.2.0)
  - support: 1.10.0 (installed 1.10.0)
  - survey_client: 1.15.0 (installed 1.15.0)
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0 (installed 1.17.0)
  - updatenotification: 1.17.0 (installed 1.17.0)
  - user_status: 1.7.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing today during my tests
```

**Comment by skjnldsv** [comment] 2024-07-31 16:36
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Closed by skjnldsv** 2024-07-31 16:36 UTC
Labels: bug, 0. Needs triage, feature: files, 27-feedback
