### ISSUE TITLE
Internal Server Error with Swift v3

### ISSUE THREAD

**Issue by charliemaiors** [nextcloud/server#12893] opened 2018-12-06 16:58 UTC
I've installed Nextcloud on a VM running CentOS (I've also tried using Ubuntu), after first installation I've added the Object Storage (for swift  v3) configuration, restarted httpd (or apache2 on ubuntu), relogged in and got a 500 (see attachment below)

### Steps to reproduce
1. Install Nextcloud and basic configuration
2. Add a Swift v3 Object Storage to Configuration
3. Restart httpd (or apache2)

### Expected behaviour
Work as after first configuration

### Actual behaviour
After login got internal server error 
![image](https://user-images.githubusercontent.com/4567810/49662189-722f6500-fa4b-11e8-9820-a1b4eef76e3d.png)

### Server configuration

**Operating system**:

**Web server:**

**Database:**
Mariadb 10.3
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**

**Signing status:**

fail
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
no app
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.lab2.ovh"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "overwrite.cli.url": "http:\/\/owncloud.lab2.ovh\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "autocreate": false,
                "user": {
                    "name": "admin",
                    "password": "password",
                    "domain": {
                        "name": "default"
                    }
                },
                "scope": {
                    "project": {
                        "name": "admin",
                        "domain": {
                            "name": "default"
                        }
                    }
                },
                "tenantName": "admin",
                "serviceName": "swift",
                "region": "RegionOne",
                "url": "http:\/\/url:5000\/v3",
                "bucket": "nextcloud"
            }
        },
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** swift v3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Archlinux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nothing

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```json
{
    "app": "index",
    "level": 3,
    "message": {
        "Code": 0,
        "CustomMessage": "--",
        "Exception": "OCP\\Files\\NotFoundException",
        "File": "/var/www/html/nextcloud/lib/private/legacy/helper.php",
        "Line": 544,
        "Message": "",
        "Trace": [
            {
                "args": [
                    "/",
                    false
                ],
                "class": "OC_Helper",
                "file": "/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php",
                "function": "getStorageInfo",
                "line": 128,
                "type": "::"
            },
            {
                "args": [],
                "class": "OCA\\Files\\Controller\\ViewController",
                "file": "/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php",
                "function": "getStorageInfo",
                "line": 157,
                "type": "->"
            },
            {
                "args": [
                    "",
                    "",
                    null,
                    false
                ],
                "class": "OCA\\Files\\Controller\\ViewController",
                "file": "/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "function": "index",
                "line": 166,
                "type": "->"
            },
            {
                "args": [
                    {
                        "__class__": "OCA\\Files\\Controller\\ViewController"
                    },
                    "index"
                ],
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "file": "/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "function": "executeController",
                "line": 99,
                "type": "->"
            },
            {
                "args": [
                    {
                        "__class__": "OCA\\Files\\Controller\\ViewController"
                    },
                    "index"
                ],
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "file": "/var/www/html/nextcloud/lib/private/AppFramework/App.php",
                "function": "dispatch",
                "line": 118,
                "type": "->"
            },
            {
                "args": [
                    "ViewController",
                    "index",
                    {
                        "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    },
                    {
                        "_route": "files.view.index"
                    }
                ],
                "class": "OC\\AppFramework\\App",
                "file": "/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
                "function": "main",
                "line": 47,
                "type": "::"
            },
            {
                "args": [
                    {
                        "_route": "files.view.index"
                    }
                ],
                "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
                "function": "__invoke",
                "type": "->"
            },
            {
                "args": [
                    {
                        "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
                    },
                    {
                        "_route": "files.view.index"
                    }
                ],
                "file": "/var/www/html/nextcloud/lib/private/Route/Router.php",
                "function": "call_user_func",
                "line": 297
            },
            {
                "args": [
                    "/apps/files/"
                ],
                "class": "OC\\Route\\Router",
                "file": "/var/www/html/nextcloud/lib/base.php",
                "function": "match",
                "line": 987,
                "type": "->"
            },
            {
                "args": [],
                "class": "OC",
                "file": "/var/www/html/nextcloud/index.php",
                "function": "handleRequest",
                "line": 42,
                "type": "::"
            }
        ]
    },
    "method": "GET",
    "remoteAddr": "xxxx",
    "reqId": "XAlTA3HdGsSnyRAaoRZH8AAAAAY",
    "time": "2018-12-06T16:49:07+00:00",
    "url": "/nextcloud/index.php/apps/files/",
    "user": "admin",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36",
    "version": "14.0.4.2"
}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

500 on /nextcloud/index.php/apps/files
```
</details>

**Comment by charliemaiors** [comment] 2018-12-11 14:55
This bug is present also on v15.0.0.10

**Comment by mlanner** [comment] 2019-01-02 23:40
Seems to be the same problem as described in:

https://github.com/nextcloud/server/issues/11264

**Comment by vpecinka** [comment] 2019-01-23 16:04
@charliemaiors just guessing: does the `nextcloud` bucket exists? If not, create it, or change `"autocreate": true` in objectstore setup.

**Comment by charliemaiors** [comment] 2019-01-23 16:11
The nextcloud bucket was created and populated by the server. But after
that the server shows the error and is unusable.

Il giorno mer 23 gen 2019, 17:05 Vlastimil Pečínka <notifications@github.com>
ha scritto:

**Comment by lubo** [comment] 2019-05-06 13:21
I'm experiencing the same issue with Nextcloud 15.0.7 and AWS S3 as primary object storage.

**Comment by lubo** [comment] 2019-05-24 12:41
So, today I've tried with 16.0.1 and AWS S3 as primary object storage. After logging in with admin, I received the same error as before. However, this time I've tried navigating to `/settings/admin/overview`, which worked. Then I tried navigating back to `/apps/files/` and it worked too! After that I tried logging out and in a couple of times, creating a new user and log in/out with him too and everything seems to be working.

@charliemaiors Does this work for you too?

**Comment by leo-lb** [comment] 2019-07-09 23:45
I got the same error on Nextcloud 15.0.10, I really need this for my current deployment.

**Comment by kesselb** [comment] 2019-07-10 11:33
Please share your logs :+1: (+ nextcloud version, which primary storage)

**Comment by leo-lb** [comment] 2019-07-10 13:57
@kesselb It throws this exception: https://github.com/nextcloud/server/blob/v15.0.10/lib/private/legacy/helper.php#L514

when visiting `app/files/`

Config:

```
  'objectstore' => 
    array (
      'class' => '\\OC\\Files\\ObjectStore\\Swift',
      'arguments' => 
        array (
          'username' => 'x',
          'password' => 'x',
          'bucket' => 'x',
          'autocreate' => false,
          'region' => 'x',
          'url' => 'https://auth.cloud.ovh.net/v2.0',
          'tenantName' => 'x',
          'serviceName' => 'swift',
        ),
    ),
```

**Comment by leo-lb** [comment] 2019-07-10 17:02
@kesselb The problem solved itself after I let Nextcloud create the bucket on its own and try visiting another page like logging page in administration BEFORE trying to access `app/files` else it would run into an error and never recover.

**Comment by acs-ferreira** [comment] 2020-01-04 18:06
I can confirm that visiting another page than `app/files` **before** access that one is the only solution. Otherwise, **error 500**. NC 17.0.2.

**Comment by skjnldsv** [comment] 2020-04-10 09:01
> Please share your logs  (+ nextcloud version, which primary storage)

**Comment by leo-lb** [comment] 2020-05-10 20:25
> > Please share your logs  (+ nextcloud version, which primary storage)

@skjnldsv This issue has all the information you are asking for already

**Comment by acsfer** [comment] 2021-02-25 17:15
Can someone reproduces this in recent versions? I can't reproduce either on S3 or SWIFT.

**Comment by szaimen** [comment] 2021-06-23 15:33
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by Jaeminz** [comment] 2021-07-22 15:05
Issue still here with S3 and fresh installation on Nextcloud 22 and minIO in docker-compose.

**Comment by szaimen** [comment] 2023-01-09 12:14
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Closed** 2023-03-06 13:37 UTC
Labels: bug, needs info, 0. Needs triage, feature: object storage
