### ISSUE TITLE
[Bug]: /settings/apps/ broken in Safari 17.3

### ISSUE THREAD

**Issue by jameskimmel** [nextcloud/server#43398] opened 2024-02-06 16:31 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Safari 17.3, you can't click stuff under https://domain/settings/apps/enabled.
Navigation is totally broken. 
No matter which app you click, it will always click on one app, ant that app only. 
Like for me, /settings/apps/enabled will always open the "versions" app, no matter what app I click. 

### Steps to reproduce

1. Go to /settings/apps/enabled
2. click any app
3.

### Expected behavior

normal navigation like before the upgrade to nc 28

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment] 2024-02-06 19:24
Duplicate of #42249

**Closed by joshtrichards** 2024-02-06 19:24 UTC
Labels: bug, 0. Needs triage, 28-feedback
