### ISSUE TITLE
[Bug]: Only group name can be added

### ISSUE THREAD

**Issue by hongtring** [nextcloud/server#37636] opened 2023-04-07 08:20 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Only group name can be added

### Steps to reproduce

1. Sign in
2. Profile Admin > Users
3. Add new user group

### Expected behavior

Adding a new user group can add the following information:
- Group name
- User belongs to group
- Status
- DS access rights

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

**Comment by joshtrichards** [comment] 2023-04-10 16:05
Can you clarify what you mean, specifically, by `Status` and `DS access rights`?

Also, I'm unclear on what you mean by "User belongs to group" unless you're suggesting one should be able to specify the users to include in the group at the same time the group gets created.

In any case, this seems an enhancement request not a bug but I don't have the permissions to change the label on the issue.

**Comment by mejo-** [comment] 2023-05-17 10:37
I also think this is rather a feature request. Given that there was no further feedback, I'm closing this issue.

**Closed by mejo-** 2023-05-17 10:37 UTC
Labels: bug, 0. Needs triage, 25-feedback
