### ISSUE TITLE
Files: listed items do not show names on narrow screen in favour of less usefull info

### ISSUE THREAD

**Issue by archont00** [nextcloud/server#17886] opened 2019-11-10 12:27 UTC
### Steps to reproduce
1. Open Firefox for Android on Samsung Galaxy S 7 in portrait mode.
2. Look-up and log-in to your Nexctloud server.
3. Switch to Files.
4. Switch view from Grid to List.

### Expected behaviour
A usable list of files should be displayed showing mainly the name of the item (or its part).

### Actual behaviour
The user can see only:
- Selection box
- Icon
- Part of the file extension or empty space (if folder)
- Share icon
- "three dot" icon
- File size
- Last modification column

See: [https://imgur.com/E7f8N8n](https://imgur.com/E7f8N8n)

### Work-around

Switch to Grid view.

### Server configuration

**Operating system**: Linux 4.14.82-1-lts #1 SMP Wed Nov 21 14:23:34 CET 2018 x86_64

**Web server:** nginx/1.17.4 (fpm-fcgi)

**Database:** mysql 10.3.15

**PHP version:** 7.3.11

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated.

**Where did you install Nextcloud from:** https://hub.docker.com/r/hoellen/nextcloud

- files: 1.12.0

**Comment by kesselb** [comment] 2019-11-10 20:02
Duplicate of https://github.com/nextcloud/server/issues/17364. Fix is part of 17.0.1.

**Closed by kesselb** 2019-11-10 20:02 UTC
Labels: 0. Needs triage, bug
