### ISSUE TITLE
Cannot disable "Allow resharing"

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#22073] opened 2020-07-31 10:35 UTC
Hi,

On a fresh install of NC 18.0.7, settings are like this:

1. "Allow resharing" is disabled in the admin settings:

![image](https://user-images.githubusercontent.com/16538178/89026331-1bcb1480-d35b-11ea-8497-318221454f98.png)

2. And under "Default share permissions", the "Reshare" checkbox is unchecked also:

![image](https://user-images.githubusercontent.com/16538178/89026516-6fd5f900-d35b-11ea-91c8-afe6ee30daab.png)

Now, when a user tries to share a file, the "Allow resharing" checkbox still shows and is enabled _(should be hidden completely according to setting 1)_ and is also checked by default _(should be unchecked according to setting 2)_:
![image](https://user-images.githubusercontent.com/16538178/89026420-44eba500-d35b-11ea-9b82-530750315bbb.png)

Supposedly these finding are not expected? At least on older versions like NC 13, everything was in order.

**Comment by GitHubUser4234** [comment] 2020-08-03 07:10
Moreover, the one with whom the file was shared with, can enter a user to reshare the file with:

![image](https://user-images.githubusercontent.com/16538178/89155136-d72dbc00-d59a-11ea-9b4f-16e41abfe68b.png)

But it should look like this (from NC 13):

![image](https://user-images.githubusercontent.com/16538178/89155211-fc222f00-d59a-11ea-8125-009df04f6893.png)

However, resharing is then not successful and an error pops up:
![image](https://user-images.githubusercontent.com/16538178/89155413-5b803f00-d59b-11ea-85c9-e7b1fc7ecfa2.png)

**Comment by GitHubUser4234** [comment] 2020-08-06 05:50
Had to hack _files_sharing_tab.js_ for a quick solution. In fact, the `isResharingAllowed `config key is defined but never used.

**Comment by jolly-jump** [comment] 2020-09-07 17:04
the underlying issue might here be the same:  #22173

**Comment by GitHubUser4234** [comment] 2020-09-08 07:05
Yes, #22173 is describing part 2. of this issue. But not sure whether a fix for it would also fix part 1, hm...

**Comment by szaimen** [comment] 2021-06-11 09:05
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-11 09:05 UTC
Labels: 0. Needs triage, bug
