### ISSUE TITLE
Deleted Files

### ISSUE THREAD

**Issue by LordEhlegant** [nextcloud/server#21223] opened 2020-06-04 08:41 UTC
### Expected behaviour
list and show deleted files

### Actual behaviour
error (cause of DAV?), see log file below

**Operating system:**
Raspberry Pi 4, nextcloudpi, debian

** PHP Version 7.3.11

** Database Type: mysql, Version: 10.3.17

**Nextcloud version: Nextcloud 18.0.5

Logging Message:
[remote] Error: TypeError: Return value of OCA\Files_Trashbin\Sabre\AbstractTrash::getSize() must be of the type int, float returned at <<closure>>

 0. /var/www/nextcloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php line 86
    OCA\Files_Trashbin\Sabre\AbstractTrash->getSize()
 1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 98
    OCA\Files_Trashbin\Sabre\PropfindPlugin->OCA\Files_Trashbin\Sabre\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/nextcloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php line 87
    Sabre\DAV\PropFind->handle("{http://owncloud.org/ns}size", Closure {})
 3. <<closure>>
    OCA\Files_Trashbin\Sabre\PropfindPlugin->propFind(Sabre\DAV\PropFind {}, OCA\Files_Trashbin\Sabre\TrashFolder {})
 4. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\Files_Trash ... "], [Sabre\DAV\PropF ... }])
 5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1059
    Sabre\Event\EventEmitter->emit("propFind", [Sabre\DAV\PropF ... }])
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 981
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\Files_Trashbin\Sabre\TrashFolder {})
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("trashbin/Florian/trash", ["{http://nextcl ... "], 1)
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
 9. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
10. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
11. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
12. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
13. /var/www/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
14. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
15. /var/www/nextcloud/remote.php line 165
    require_once("/var/www/nextcl ... p")

PROPFIND /remote.php/dav/trashbin/Florian/trash
from 80.133.120.133 by Florian at 2020-06-04T08:26:40+00:00

** End

Any Idea, do I have to change DAV settings?

**Comment by kesselb** [comment] 2020-06-04 12:07
Closing as duplicate of https://github.com/nextcloud/server/issues/13160

**Closed by kesselb** 2020-06-04 12:07 UTC
Labels: 0. Needs triage, bug
