### ISSUE TITLE
[Bug]: Docker image 28.0.0 reports missing PHP module BZ2.

### ISSUE THREAD

**Issue by francescop75** [nextcloud/server#42341] opened 2023-12-17 18:16 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On the nextcloud:28 and nextcloud:28-fpm-alpine docker image, the "Security & setup warnings" page reports:

`This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them: bz2. For more details see the [documentation ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-php-modules).`

### Steps to reproduce

1. Login as an administrator
2. Goto /settings/admin/overview page

### Expected behavior

The PHP BZ2 module should be installed into the image.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "_REDACTED_"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.oscr.it",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 2,
        "maintenance": false,
        "default_phone_region": "IT",
        "auth.webauthn.enabled": false,
        "trashbin_retention_obligation": "auto, 90"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - survey_client: 1.16.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev (installed 26.0.0)
  - comments: 1.18.0 (installed 1.11.0)
  - contactsinteraction: 1.9.0 (installed 1.2.0)
  - dashboard: 7.8.0 (installed 7.1.0)
  - deck: 1.9.0 (installed 1.9.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.11.0)
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0 (installed 2.1.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.10.0)
  - nextcloud_announcements: 1.17.0 (installed 1.15.0)
  - recommendations: 2.0.0 (installed 1.0.0)
  - support: 1.11.0 (installed 1.4.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.11.0)
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.1.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by MaxWaldorf** [comment] 2023-12-17 20:03
confirmed here as well...

**Comment by joshtrichards** [comment] 2023-12-17 20:40
Duplicate of nextcloud/docker#2118 and/or #42342

**Closed by joshtrichards** 2023-12-17 20:40 UTC
Labels: bug, 0. Needs triage
