### ISSUE TITLE
[Bug]: Background Job Expire Files exception when original file was moved

### ISSUE THREAD

**Issue by iljur** [nextcloud/server#39041] opened 2023-06-28 12:03 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a file that has versions in the background is moved (to an external storage folder) the versions file(s) remain at the old location. The file was moved in Windows Explorer via the NC Desktop client.

When the background job tries to expire/delete these versions it fails claiming "file not found".

`occ versions:expire -vvv ` also throws an error.

The expired version file(s) can be manually deleted at the old location and the error is gone.

### Steps to reproduce

1. Alter a file to automatically generate a version file *.vxxxxxxxxx
2. Move the file (to a location on an external storage)
3. Wait for the background job to delete the old versions when they are expired.

### Expected behavior

Version files of files that do not exist any longer at the location should simply be deleted by the background job.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Other

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "activity_expire_days": 14,
        "app_install_overwrite": [
            "spreed",
            "files_lock"
        ],
        "auth.bruteforce.protection.enabled": false,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "check_for_working_htaccess": true,
        "cron_log": true,
        "data-fingerprint": "16d80d5bb24cab72978d3b8b7335bd17",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_phone_region": "DE",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "forcessl": true,
        "htaccess.RewriteBase": "\/",
        "installed": true,
        "knowledgebaseenabled": false,
        "logtimezone": "Europe\/Berlin",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "log_authfailip": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mysql.utf8mb4": true,
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "remember_login_cookie_lifetime": "1800",
        "share_folder": "\/Freigaben",
        "simpleSignUpLink.shown": false,
        "skeletondirectory": "",
        "theme": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "upgrade.disable-web": "true",
        "version": "26.0.3.2",
        "versions_retention_obligation": "auto, 14"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - calendar: 4.4.2
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - collectives: 2.5.0
  - comments: 1.16.0
  - contacts: 5.3.2
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.2
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_downloadactivity: 1.16.0
  - files_external: 1.18.0
  - files_lock: 27.0.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - forms: 3.3.1
  - groupfolders: 14.0.2
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - notes: 4.8.0
  - notifications: 2.14.0
  - notify_push: 0.6.3
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - sharerenamer: 3.2.0
  - support: 1.9.0
  - systemtags: 1.16.0
  - tables: 0.5.1
  - tasks: 0.15.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0
  - unroundedcorners: 1.0.9
  - unsplash: 2.2.1
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - bruteforcesettings: 2.6.0 (installed 2.0.1)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.1.1)
  - firstrunwizard: 2.15.0 (installed 2.9.0)
  - nextcloud_announcements: 1.15.0 (installed 1.14.0)
  - recommendations: 1.5.0 (installed 0.8.0)
  - survey_client: 1.14.0 (installed 1.9.0)
  - suspicious_login: 4.4.0
  - user_ldap: 1.16.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"yuCaJGOq03pZjohhSINa","level":3,"time":"2023-06-27T01:35:02+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Files_Versions\\BackgroundJob\\ExpireVersions, arguments: )","userAgent":"--","version":"26.0.3.2","exception":{"Exception":"OCP\\Files\\NotFoundException","Message":"/sn/files/Projekte/*** sensitive parameters replaced ***/05_Beschaffung/05.3_BSK_St\u00fcrzl/02_Auftrag/Anlage1_Angebot_Stuerzl_230615.pdf","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":138,"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":595,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->"},{"function":"OCA\\Files_Versions\\{closure}","class":"OCA\\Files_Versions\\Storage","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage
 .php","line":610,"function":"array_filter"},{"file":"/var/www/nextcloud/apps/files_versions/lib/BackgroundJob/ExpireVersions.php","line":69,"function":"expireOlderThanMaxForUser","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/lib/private/User/Manager.php","line":639,"function":"OCA\\Files_Versions\\BackgroundJob\\{closure}","class":"OCA\\Files_Versions\\BackgroundJob\\ExpireVersions","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/files_versions/lib/BackgroundJob/ExpireVersions.php","line":70,"function":"callForSeenUsers","class":"OC\\User\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Files_Versions\\BackgroundJob\\ExpireVersions","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/Ba
 ckgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Files/Node/Root.php","Line":209,"message":"Error while running background job (class: OCA\\Files_Versions\\BackgroundJob\\ExpireVersions, arguments: )","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Files_Versions\\BackgroundJob\\ExpireVersions, arguments: )"}}
```

**Comment by arnowelzel** [comment] 2023-09-16 08:40
Seems to be the same issue as https://github.com/nextcloud/server/issues/40450

**Comment by joshtrichards** [comment] 2023-09-17 13:10
>         "trashbin_retention_obligation": "auto, 7",
>         "versions_retention_obligation": "auto, 14"

I wonder if this an interaction between overriding the default retention policies for both trash and versions. And, in particular, setting the trashbin retention *lower* than for versions. Usually they match: 30 days. Similar configuration in-use in the reported config of #40450:

>        "trashbin_retention_obligation": "auto, 30",
>        "versions_retention_obligation": "auto, 180",

**Comment by arnowelzel** [comment] 2023-09-17 13:13
Indeed the time when the expiration will happen, does not matter. The problem is, that the original file is deleted and the version expiration expects the file still to be present if there is a version for a file.

A fix for this should just treat versions which refer to a non-existing file as "expired" and delete all of them since there is no way in the UI to restore them anyway.

**Comment by solracsf** [comment] 2023-09-18 06:14
Cc @artonge maybe you can take a look here?

**Closed** 2023-11-06 08:50 UTC
Labels: bug, 0. Needs triage, feature: versions, 26-feedback
