### ISSUE TITLE
files locked for no obvious reason

### ISSUE THREAD

**Issue by Floflobel** [nextcloud/server#8723] opened 2018-03-07 23:51 UTC
### Steps to reproduce
1. Make files into synchronisation directory
2. Synchronisation has launch
3. Failed 

### Expected behaviour
Files synchronise

### Actual behaviour
Files not synchronise

### Server configuration

**Operating system**: Ubuntu 16.04.4 LTS

**Web server:** apache2 2.4.18

**Database:** postgres 9.6

**PHP version:** 7.0.25

**Nextcloud version:** (see Nextcloud admin page) 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.0
  - comments: 1.3.0
  - contacts: 2.1.2
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 1.2.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - user_usage_report: 1.0.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_clipboard
  - files_reader
  - keeweb
  - mail
  - ojsxc
  - spreed
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "box.home.floheberg.xyz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/box.home.floheberg.xyz",
        "dbtype": "pgsql",
        "version": "13.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5,
            "dbindex": 0
        },
        "logtimezone": "Europe\/Paris",
        "loglevel": 2,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logdateformat": "Y-m-d H:i:s T",
        "log_query": false,
        "log_authfailip": false,
        "log_rotate_size": 104857600,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes local storage

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Just nextcloud client

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
-rw-r--r--   1 www-data www-data    0 Oct 28 00:36 nextcloud.log

```
</details>

![screenshot from 2018-03-08 00-51-07](https://user-images.githubusercontent.com/13889750/37125047-14dc8bb6-226b-11e8-9e89-848230af9b86.png)

**Comment by Floflobel** [comment] 2018-03-08 00:13
When I try to upload files with web browser it's return:
`Error when assembling chunks, status code 403
Forbidden`

**Comment by enoch85** [comment] 2018-03-08 12:15
Releated: https://github.com/nextcloud/server/issues/6655

Still get file locks from time to time without any reason. Just by downloading the file (I think) it get's locked which is kind of stupid.

**Comment by Floflobel** [comment] 2018-03-08 13:28
I can download any files but I can not upload files on my nextcloud. 
The table "files_lock" are empty and I tried to put "filelocking.enabled' => 'false'" into the config.php and it's does not work.

**Comment by enoch85** [comment] 2018-03-08 13:40
@Floflobel Yes I understand that, but what I was meaning is that it gets locked when someone downloads and therefore you can't upload or download, that's what I think at least.

Strange thing is that it happens randomly, and I have no clue how to debug it.

My log is filled with "file is locked" with this file: https://cloud.techandme.se/s/whxC00V1I0l4CY8 and it's been like that forever. Just giving my input on this matter. :)

**Comment by Floflobel** [comment] 2018-03-08 13:53
@enoch85 Ok, I understand better. I do not think it's the fact that it's downloading it locks it because I'm the only user ..
Unlike you I do not have a single file to lock but thousands.

Hoping that we will find something to debug the problem. ;)

**Comment by enoch85** [comment] 2018-03-08 14:50
@Floflobel Feel free to debug it, if you find the cause then we can fix it. :)

**Comment by Wenzel** [comment] 2018-04-11 13:47
Hi,
i just have the same situation here.

i cannot synchronize my files, because i file has been "locked" on the server.
I cannot even remove this file anymore on the server, my sync is broken !

What can i do to remove it ?

**Comment by enoch85** [comment] 2018-04-11 14:03
@Wenzel Do you have any shared folders which syncs with the client? Like federated shares or similar.

**Comment by Wenzel** [comment] 2018-04-11 14:07
@enoch85 not at all.

I tried to remove the file on the filesystem, and i'm now rescanning the filesystem with `./occ files:scan`

**Comment by enoch85** [comment] 2018-04-11 14:17
@Wenzel OK, please post the output.

**Comment by Wenzel** [comment] 2018-04-11 15:13
Now i have new files being locked for no reasons:
![locked](https://user-images.githubusercontent.com/964610/38625805-f080d916-3db3-11e8-8095-d2f4e2cea350.png)

Please help, we have a bug here.

**Comment by Wenzel** [comment] 2018-04-11 15:17
And i can't delete the file:
![error](https://user-images.githubusercontent.com/964610/38626123-9a1dd938-3db4-11e8-8182-f1baf0fa9fe0.png)

**Comment by enoch85** [comment] 2018-04-11 16:15
@Wenzel You should always use  `./occ files:scan` with caution. In your case I would remove all files locally, turn of the webserver (Apache or whatever) and then wait for 20 minutes. When you've done that, turn on the webserver again and resync all the files.

Do it with caution though, and I'm no expert just so you know.

**Comment by Wenzel** [comment] 2018-05-02 09:59
hello,

It happened again today
![sync error](https://user-images.githubusercontent.com/964610/39517466-96b02008-4e08-11e8-9536-a645955963ff.png)
![locked](https://user-images.githubusercontent.com/964610/39517468-98f94600-4e08-11e8-8332-984cb2189cba.png)

This is definitely a bug in Nextcloud server, we need to investigate.

**Comment by enoch85** [comment] 2018-05-02 10:03
Ping @MorrisJobke and others (don't know who this belongs to).

**Comment by vbspam** [comment] 2018-05-23 08:07
I just want to confirm it is happening also to me. I run two NC servers, one 12.0.0 the other  13.0.2. Both suffers of this "server replied: Locked (''/path/to/filename/" is locked).

My NC desktop client is "Version 2.3.3", it however from the response it looks it is probably server issue.

My observation is that this is happening on files which changes frequently. Could it be something with the timestamp resoluttion?

Just to note, I do not believe it may cause the issue, my server runs UTC time, my client runs CEST time, both auto synced through NTP. 

Server runs on Ubuntu 16.04, nginx version: nginx/1.13.6, PHP 7.0.28-0ubuntu0.16.04.1 (fpm-fcgi).
Client runs Ubuntu 16.04 Neon flavour.

**Comment by warnerbryce** [comment] 2018-06-26 16:38
I have the same kind of problem... but the files syncs well after waiting a while. It occures when uploading a folder with a lot of files. 

I have write a topic on help nextcloud https://help.nextcloud.com/t/sync-some-files-are-blocked-error-during-sync-and-then-synced-after-a-second-third-try-no-app-in-context/30986

**Comment by ConorIA** [comment] 2018-07-03 12:20
Same issue here. Typically it happens when a file is edited both on my server and on my laptop. (I think). 

The errors seem to come in pairs. On `no-app-in-context` error, followed by the file lock error.

```
Fatal | webdav            | OCA\DAV\Connector\Sabre\Exception\FileLocked: "Documents/Extra-Curricular/TF 2018/book" is locked                     | a minute ago
Error | no app in context | OCP\Lock\LockedException: "files/485fa3ae591d79ba0220864f977e1b2e" is locked, existing lock on file: -1 shared locks  | a minute ago
Fatal | webdav            | OCA\DAV\Connector\Sabre\Exception\FileLocked: "Documents/Extra-Curricular/TF 2018/mdbook" is locked                   | a minute ago
Error | no app in context | OCP\Lock\LockedException: "files/42e92d9acbfd2f1d7edfa2a953a5bc68" is locked, existing lock on file: -10 shared locks | a minute ago
```
Negative numbers of shared locks seems suspect to me, but I really don't know much about this. Redis is active, _but_ this issue was much more prevalent before turning on Redis.

**Comment by JamesBream** [comment] 2018-07-05 09:42
Have also experienced the same issue as @ConorIA with the logs showing negative numbers of file locks when using redis as a result of syncing via the Mac desktop client. There were no locks in the MySQL database as expected.

Didn’t know about the redis flush command but the issue resolved itself after a few hours, through did persist through restarts.

**Comment by enoch85** [comment] 2018-07-05 10:23
This has been an issue for quite some time I'm afraid. Maybe NC 14 will be more stable, let's hope for that anyway.

**Comment by vbspam** [comment] 2018-07-05 12:37
I understand it may be here for some time, it however does not solve the issue and leave the Nextcloud unusable (due to the lack of trust) for everyday syncing of multiple devices.

Is there test case which always fails and can be reproduced?

**Comment by icewind1991** [comment] 2018-07-05 12:43
> OCP\Lock\LockedException: "files/42e92d9acbfd2f1d7edfa2a953a5bc68" is locked, existing lock on file: -10 shared locks

Lock values getting negative should-not-happend™ and is a likely cause of files being persistently locked.

https://github.com/nextcloud/server/pull/10116 should prevent this from happening.

**Comment by simonspa** [comment] 2018-07-06 14:48
I do have the same issue with NC 13.0.3, but strangely mostly one with one user. As far as I understand, that user places files in the NC sync folder via `backintime` automatically once a day. They should then get uploaded by the NC client and never be touched/read/written again. In the NC log I see many messages like

```
OCA\DAV\Connector\Sabre\Exception\FileLocked: "backups/backintime/some/folder/of/the/user" is locked
```

but no ERROR messages with negative lock counts.

**Comment by Wenzel** [comment] 2018-08-06 13:49
This bug happened again to me, and it's really annoying, i can't get rid of it this time.

I give up on Nextcloud and have to switch on another file sync solution... :-1:

**Comment by JamesBream** [comment] 2018-08-06 14:27
@wenzel Are you running 13.0.5?

**Comment by Wenzel** [comment] 2018-08-06 14:42
@JamesBream , not i'm still running the `13.0.0` because the web updater fails :man_shrugging: 
![screenshot from 2018-08-06 17-37-35](https://user-images.githubusercontent.com/964610/43723344-1497669c-99a0-11e8-9409-74dd7d319f3a.png)

**Comment by warnerbryce** [comment] 2018-08-06 14:44
You should have permission problem on your nextcloud WWW folder. 
Follow the documentation about folder permissions and start the update process again

**Comment by Wenzel** [comment] 2018-08-06 14:58
@warnerbryce i `chown www-data -R /var/www/nextcloud`, and it solved my issue.
But the webupdater should have a more precise check on permissions beforehand, because my Nextcloud instance was broken :)

I will open a ticket for that.
Thanks.

I tested again, and apparently `13.0.5` solved my file locked issue. :pray:

**Comment by enoch85** [comment] 2018-08-06 15:50
> I tested again, and apparently 13.0.5 solved my file locked issue

Close this ticket then?

**Comment by vbspam** [comment] 2018-08-07 14:25
I did update to from 12.0 to 13.0.5. and it did not fix the issue.

**Comment by holzfelix** [comment] 2018-08-07 16:18
Issue is still pending and not solved.

**Comment by mgladman** [comment] 2018-08-20 09:32
Can confirm. I can resolve it by logging in to mysql(mariadb), using the nextcloud DB ``use cloud`` and typing ``DELETE FROM oc_file_locks WHERE 1;`` but I'm sure that's probably not the best option. I'm trying it without redis to see if redis was actually the cause. I'm using 13.0.5 on FreeBSD 11.2.

**Comment by Redsandro** [comment] 2018-08-22 09:03
When I added `redis` for `memcache.locking` in an attempt to fix the slow upload on many small files, I stasrted getting these errors.

> Error downloading xxx - server replied: Locked (“file” is locked)

**Comment by Wenzel** [comment] 2018-08-23 23:05
Hello again,
I just had the bug, problem not solved.

**Comment by Wenzel** [comment] 2018-09-02 01:32
I upgraded to Nextcloud `13.0.6`via the web updater, problem is still here..

**Comment by Charburner** [comment] 2018-09-17 11:39
Any chance you guys are using the files_automatedtagging app?
https://github.com/nextcloud/files_automatedtagging/issues/41

**Comment by warnerbryce** [comment] 2018-09-17 11:41
For my part no. I’m not using this app

**Comment by Wenzel** [comment] 2018-09-19 22:18
If that helps, i learned that you can have files being locked without using the desktop app.

Just trying to remove a folder with the Nextcloud web interface leads to **"error while removing the XXX"**

And looking at the logs:
![capture d ecran de 2018-09-20 01-15-47](https://user-images.githubusercontent.com/964610/45784869-fb1bd900-bc72-11e8-94d4-289230818426.png)

**Comment by dulinux** [comment] 2018-10-02 21:38
I can confirm this on a clean 14.0.1 install. Not using memcache nor redis.

Not using desktop client. Just using smartphone app.

When I try to delete a file from an external smb storage, I get this:

```
OCA\DAV\Connector\Sabre\Exception\FileLocked: "documentos/Clientes/Acqua_Vita/substabelecimento.doc" is locked

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179:

    OCA\DAV\Connector\Sabre\File->delete()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 291:

    Sabre\DAV\Tree->delete("files/felip ... c")

    Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

    call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:

    Sabre\Event\EventEmitter->emit("method:DELETE", [ Sabre\HTTP ... }])

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /var/www/nextcloud/apps/dav/lib/Server.php - line 293:

    Sabre\DAV\Server->exec()

    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /var/www/nextcloud/remote.php - line 163:

    require_once("/var/www/ne ... p")
```

**Comment by ak1n** [comment] 2018-10-30 22:17
I have confirmed this bug with clean installs of Nextcloud 14 using docker and scripted install with a standardized dataset of a large number of images on a first sync. Occurs with both mysql & postgres. I built a testing install/configuration script with details on test dataset here: https://gitlab.com/deepthought/nextcloud-docker/tree/latest

**Comment by optimistic5** [comment] 2018-11-18 10:45
I can also confirm the bug. It is happens from time to time. I'm using desktop app.
![default](https://user-images.githubusercontent.com/25054050/48671374-a213d880-eb2f-11e8-9d9f-18af93b20e9d.png)

> Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\FileLocked: "Изображения/Фото/2018.11.11 Поход Эсхар/vkpic-565476" is locked | 9 minutes ago
> -- | -- | -- | --
> Error | no app in context | OCP\Lock\LockedException: "files/62c9ee54a18cfa7ab9ea381e6702bbfc" is locked | 9 minutes ago
> Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\FileLocked: "Изображения/Фото/2018.11.11 Поход Эсхар/vkpic-565476/Мохнач Эсхар" is locked | 9 minutes ago
> Error | no app in context | OCP\Lock\LockedException: "files/8e5b6854bebb1c16909ecd8f5185e6d6" is locked | 9 minutes ago
[https://paste.debian.net/1052205/](https://paste.debian.net/1052205/)

NC 13.0.6
**This bug BLOCKING normal work of Nextcloud, please fix it**

**Comment by optimistic5** [comment] 2018-12-14 19:33
After upgrade to 14.04 issue is still active
https://paste.debian.net/1055885/
https://i.imgur.com/SDKzGHc.png

**Comment by vbspam** [comment] 2018-12-14 19:58
And there is another new bug [here](https://github.com/nextcloud/desktop/issues/943) which looks related to this one.

**Comment by optimistic5** [comment] 2018-12-26 18:40
I have more and more locked files.
![default](https://user-images.githubusercontent.com/25054050/50454172-6ea64400-094e-11e9-9e77-9614ed2e005e.png)
https://i.imgur.com/sc2vgEX.png
https://i.imgur.com/MC3W7Gn.png
https://paste.debian.net/1057467/

**Comment by vbspam** [comment] 2018-12-26 18:45
Me too

**Comment by danielkesselberg** [comment] 2018-12-28 16:32
@optimistic5 @vbspam Could you open a new issue? Without the information from the issue template its hard to reproduce your problem. There were many improvments to locking with nextcloud 15 (a few already landed in nextcloud 14.0.4). Thank you!

**Comment by vbspam** [comment] 2018-12-28 22:43
It is simple to reproduce: Just synchronize Thunderbird data folder (or
anything what changes frequently).

It fails with any recent version of Nextcloud server and Linux desktop
client.

Actually the new client added new horror (and insane) message:
"Conflict: Server version downloaded, local copy renamed and not
uploaded.". The local copy should be always honored!! Who cares about
server files if they introduce conflict!!! Imagine you rename wallet.dat :-)

**Comment by vbspam** [comment] 2018-12-28 23:57
If I will find a time in next day or two I will create new issue as asked. I however believe the issue can be replicated by the same procedure as in [this](https://github.com/nextcloud/desktop/issues/943) issue.
Looks like the server triggers the crazy need to lock and/or newly conflict.

**Comment by Tott3** [comment] 2019-01-21 08:37
I got this problem as well. Only occurs with my .MP4 files (The bigger files in other words)

https://imgur.com/a/oG1w8z4

**Comment by enoch85** [comment] 2019-01-21 09:08
@Tott3 From your status.php I can see that you are using NC 14.0.6. Please update to latest version (15.0.2) and try again.

```

installed | true
-- | --
maintenance | false
needsDbUpgrade | false
version | "14.0.6.0"
versionstring | "14.0.6"
edition | ""
productname | "Nextcloud"
```

**Comment by Tott3** [comment] 2019-01-21 09:20
> @Tott3 From your status.php I can see that you are using NC 14.0.6. Please update to latest version (15.0.2) and try again.
> 
> ```
> 
> installed | true
> -- | --
> maintenance | false
> needsDbUpgrade | false
> version | "14.0.6.0"
> versionstring | "14.0.6"
> edition | ""
> productname | "Nextcloud"
> ```

This is what is says.

> $values=array(
> 		'installed'=>$installed,
> 		'maintenance' => $maintenance,
> 		'needsDbUpgrade' => \OCP\Util::needUpgrade(),
> 		'version'=>implode('.', \OCP\Util::getVersion()),
> 		'versionstring'=>OC_Util::getVersionString(),
> 		'edition'=> '',
> 		'productname'=>$defaults->getName());

**Comment by enoch85** [comment] 2019-01-21 12:57
@Tott3 So you mean you can't upgrade? Please open another issue for that. Thanks!

What I mean is upgrade your Nextcloud to the latest version which currently is 15.0.2.

**Comment by Tott3** [comment] 2019-01-21 14:00
> @Tott3 So you mean you can't upgrade? Please open another issue for that. Thanks!
> 
> What I mean is upgrade your Nextcloud to the latest version which currently is 15.0.2.

Oh, I misread your post. I missed the update part :P I'm running 15.0.2 now, however the problem persists. However I believe they went away when I added  `'filelocking.enabled' => false,` to the config file.

**Comment by enoch85** [comment] 2019-01-21 16:05
> However I believe they went away when I added 'filelocking.enabled' => false, to the config file.

Yeah, because you disabled file locking. :D Great to see en svensk with Nextcloud btw. :)

**Comment by icewind1991** [comment] 2019-01-22 14:39
Please see if https://github.com/nextcloud/server/pull/13739 fixes the issue for you

**Comment by optimistic5** [comment] 2019-01-22 18:02
> 
> 
> Please see if #13739 fixes the issue for you

I edited file lib/private/Files/View.php
I deleted 1140 line and added this lines above
```
try {
						$this->changeLock($path, ILockingProvider::LOCK_EXCLUSIVE);
					} catch (LockedException $e) {
						// release the shared lock we acquired before quiting
						$this->unlockFile($path, ILockingProvider::LOCK_SHARED);
						throw $e;
					}
```
I rebooted my OS and I still have this error:
https://pastebin.com/QJXLDGgm
https://i.imgur.com/zxx6aLZ.png

Netxcloud 15.0.2

**Comment by MorrisJobke** [comment] 2019-01-23 09:36
> I rebooted my OS and I still have this error:

A reboot does not clear potential stray locks. You also need to wait long enough so that the locks are not there from before the patch was applied. The locks have a TTL of 1 hour. So either clear them (with the risk of running into a concurrent request) or wait for at least 1 hour.

**Comment by MorrisJobke** [comment] 2019-01-30 14:33
> I also have this bug with a totally clean install of the latest NC

The fix will be shipped with the next maintenance releases 15.0.3, 14.0.7 and 13.0.11 next week

**Comment by nhadsall** [comment] 2019-01-30 14:35
Thanks @MorrisJobke Is this a simple fix I could apply myself? This is causing real issues. Our previous server crashed and we are re-uploading thousands of files.

**Comment by nhadsall** [comment] 2019-01-30 14:55
I applied the fix mentioned above to lib/private/Files/View.php and still have issues. Thanks!

**Comment by MorrisJobke** [comment] 2019-01-30 14:59
> I applied the fix mentioned above to lib/private/Files/View.php and still have issues. Thanks!

Correct - those: https://github.com/nextcloud/server/pull/13739/files#diff-4cff562ef27dea645f123b1a19eceaf0


Then also keep this in mind:

> A reboot/restart does not clear potential stray locks. You also need to wait long enough so that the locks are not there from before the patch was applied. The locks have a TTL of 1 hour. So either clear them (with the risk of running into a concurrent request) or wait for at least 1 hour.

**Comment by danielkesselberg** [comment] 2019-01-30 15:09
There a different options for the file locking. Which one are you currently using (Redis or DB?). You could try to disable it (and enabled it again after you restored the files) like suggested here https://github.com/nextcloud/server/issues/8723#issuecomment-456083434.

It's easier for us to help you if you provide the information from the issue template: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md

**Comment by MorrisJobke** [comment] 2019-01-30 15:09
> I stopped apache, applied the patch, cleared the locks table, then started apache. Still getting dozens of "OCP\Lock\LockedException"

Then it's something else. Could you enable the debug log of the file locking? 

See https://github.com/nextcloud/server/blob/e6333c8fe389aca4e1e8349f276de0058c20c6bb/config/config.sample.php#L1621-L1630

**Comment by nhadsall** [comment] 2019-01-30 15:21
> 
> Then it's something else. Could you enable the debug log of the file locking?
> 

Set 'filelocking.debug' to false to enable it or set it to true? Should I open new bug report?

**Comment by MorrisJobke** [comment] 2019-01-30 15:26
> Set 'filelocking.debug' to false to enable it or set it to true? Should I open new bug report?

set it to `true`. And yes a new ticket that has a link to this one here is maybe best.

**Comment by optimistic5** [comment] 2019-04-08 12:12
Looks like on 15.0.2 and now on 15.0.6 everything is fine. No locks. Thanks.

**Closed** 2019-04-08 20:52 UTC
Labels: bug, feature: filesystem, feature: locking

**Comment by vbspam** [comment] 2019-04-25 08:58
Looks like desktop client version 2.5.2git with server from 13.x to 15.0.7 still has the issue.

**Comment by enoch85** [comment] 2019-04-25 09:02
> Looks like desktop client version 2.5.2git with server from 13.x to 15.0.7 still has the issue.

Just as a reference, since Nextcloud 15.0.3 + desktop client 2.5.1 I didn't have any issues at all. Before this got fixed I had issues every time I uploaded the Nextcloud VM using the client.

So for me this is totally fixed, and I'm a pretty heavy user / tester.

**Comment by kesselb** [comment] 2019-04-25 09:53
Please open a new issue (https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md) if you still observe locking problems. Let us know if you use redis or db for locking.

**Comment by vbspam** [comment] 2019-04-25 17:01
Opened here: #15235; I do not know if my instance is using Redis; when checked for 'redis' process through ps auws |grep redis did not find any process.

**Comment by Wenzel** [comment] 2020-03-26 19:43
2 years later, and the same bug is still lurking around in Nextcloud code.

Some of my files have been locked again, and I can't remove them anymore.
I'm unable to run the `occ` command because I'm on a hosted service, without SSH access.

Why this bug is still here ? :(

**Comment by bpcurse** [comment] 2020-03-26 23:16
@Wenzel Can you use occ web app for this task?
https://apps.nextcloud.com/apps/occweb

**Comment by Wenzel** [comment] 2020-03-26 23:58
hey @bpcurse, thank you so much for the quick reply !
I totally missed `occweb` in the app store.

I just installed it.
What command should I run to remove the file locks ?

**Comment by warnerbryce** [comment] 2020-03-27 02:26
@Wenzel you can try a 
occ files:scan yourusername

**Comment by Wenzel** [comment] 2020-03-27 10:20
@warnerbryce I tried that, and there is a locked folder that I still can't remove.
It didn't solve my problem

**Comment by warnerbryce** [comment] 2020-03-27 10:38
Okay so you have to interact with the database of your nextcloud. Do you have access to your mysql database with phpmyadmin or something like that ?

**Comment by bpcurse** [comment] 2020-03-27 10:44
@Wenzel I suppose you have database access?

What you could try is occ files:cleanup and if that doesn't help delete all entries in the table file_locks.

WARNING: **Make sure to have a backup files/database and no user/no sync client connected to your cloud!** Manipulating the database is always a risk and I am not a developer.

If you need further support, please use https://help.nextcloud.com.

**Comment by Wenzel** [comment] 2020-03-27 10:48
@warnerbryce @bpcurse I will try `occ files:cleanup`.

however, I'm using a hosted solution, and I don't have SSH access, so no database either.

**Comment by warnerbryce** [comment] 2020-03-27 11:09
@Wenzel you must have access to a phpmyadmin or other page to manipulate your database. It can’t be other way. 
Go on the help.nextcloud.com discourse. My name is Nemskiller PM me and i will help you.

**Comment by stagg54** [comment] 2020-05-06 02:35
This issue is still here. None of the fixes I have found anywhere work. I am using redis. tried flushing it. did not work.

**Comment by krusta4711** [comment] 2020-05-24 10:27
I can reproduce this issue every time I use the following workflow (NC 18.04., encrypted enabled, shared hosting with 128MB RAM):

1.) On Win10 PC: Create a new folder 'test' and copy at least 6 JPEGs to it (each 5MB)
2.) On IOS or Android App: Go to the new folder and wait until it is synchronized.
3.) Move up to the parent folder and delete the 'test' folder (the same seems also to happen from )

The deletion ALWAYS fails for me in this setup. I get the message, that the data is locked. Trying to delete the JPEGs file by file after that does work for some images, for others not (with locked message). 

I do NOT get errors, when I delete the folder from Android/IOS App without going into it before.

**Comment by warnerbryce** [comment] 2020-05-24 10:30
@krusta4711 encryption with a 128MB ram on shared hosting is really low specs for having a good working nextcloud server.

**Comment by krusta4711** [comment] 2020-05-24 10:40
Yes you are right @warnerbryce 
But in general it works well. We are just two users and there is no heavy usage. Just a few files that are shared. The locking issue is the only one I observed until now. I think I will deactivate the locking in future ('filelocking.enabled' => false,). I do not expect a lot issues with two users. 

So I wrote down my workflow to help the other users in this thread with this issue. Nobody could state a workflow the reproduce it until now. Maybe someone with a bigger server can try to reproduce my workflow. If it fails too that might help to solve the issue.

**Comment by beatrfrm** [comment] 2020-05-30 11:57
Hello the same here. 
I uploaded a 260 MB .mp4 video. I can delete it.
If I open this video and then want to delete it, I get the Error deleting File massage.
If I restart Apache then I can delete the video again.
I uploaded a 200MB file without extension, wich I can't open therefore I can delete it.
APCu, Redis makes the same result.
Thank you.

**Comment by warnerbryce** [comment] 2020-05-31 06:00
@beatrfrm and you have encryption enabled or not ?

**Comment by beatrfrm** [comment] 2020-05-31 10:49
> @beatrfrm and you have encryption enabled or not ?

@warnerbryce as I know I didn't enabled any encryption. Actually is a new installation, with some apps. But if I disable all (the basic apps to) apps the problem is still here. It is a LAMP Server. filelocking is disabled.

**Comment by p6002** [comment] 2021-04-26 11:29
I see that the problem has been around for 3 years and has not been resolved in any way.
This is the opensource world.
If you have any ideas on how I can remove MY files from MY cloud please write.

**Comment by stefan123t** [comment] 2021-05-13 11:12
@p6002 in my case it was caused by a mis-configuration of the basic setting for Cron instead of AJAX Cron.

So if you go to Settings > Administration > Basic Settings it will tell you when it last ran the Background Jobs
That wrong setting prevented to run the BackgroundJob/CleanupFileLocks.php for more than five months in my case.

I found something along the following SQL quite useful for debugging that cause:
`SELECT FROM_UNIXTIME( file_locks.ttl, '%Y-%m-%d %h' ) AS DATE, file_locks.lock, COUNT(*) AS LOCKS FROM file_locks GROUP BY DATE, file_locks.lock ORDER BY LOCKS DESC `

See #15235 for more details

Kind regards,
Stefan
