### ISSUE TITLE
HTTP 1.1 404  - Exception: Sabre\DAV\Exception\NotFound

### ISSUE THREAD

**Issue by plrunner** [nextcloud/server#2783] opened 2016-12-20 15:34 UTC
### Steps to reproduce
1. _some not clear circumstances_ 
2. folder shared among users
2. a subfolder is renamed by a user through the windows client
3. that subfolder is pretty simultaneously accessed by another user through his windows client (e.g. he updates a file in there)

### Expected behaviour
sync would be expected to work smoothly

### Actual behaviour
Several windows clients get RED complaining about CSYNC non able to find the folder (with the old name)

The DAV layer complains about the folder not being found (see **Interesting log portion** below).

In the web UI I see the folder just renamed containing all files as expected and also a zombie spurious folder having the old name. Trying to enter the latter brings me to the root folder. Deleting it just removes it from the view, but the zombie is back there when I refresh the page content.

**workaround** in order to get back to a stable state I have to make a backup of the renamed folder's parent folder, delete the entire parent folder via web UI, wait for everyone to get synced and then restore the folder again.

### Server configuration
Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
Mysql 5.7

**PHP version:**
5.7

**Nextcloud version:**
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 10.0.0

**Where did you install Nextcloud from:**
nextcloud website

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocq05beinini",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "removed.by.me"
        ],
        "datadirectory": "\/var\/www\/nextcloud-data",
        "overwrite.cli.url": "http:\/\/removed.by.me",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "maintenance": false,
        "updater.release.channel": "stable"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

**Operating system:**
Ubuntu 16.04

**Interesting log portion**
```
{
   "app": "admin_audit",
   "level": 1,
   "message": "File renamed: \"/aaa/bbb\" to \"/aaa/ccc\"",
   "method": "MOVE",
   "remoteAddr": "removed",
   "reqId": "vg74pcutcutcutS9tP+",
   "time": "2016-12-20T09:06:19+00:00",  
   "url": "/remote.php/webdav/aaa/bbb",
   "user": "user1"
}
{
   "app": "webdav",
   "level": 0,
   "message": "Exception: {\"Message\":\"HTTP\/1.1 404 File with name aaa/bbb could not be located\",\"Exception\":\"Sabre\\DAV\\Exception\\NotFound\",\"Code\":0,\"Trace\":\"#0 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(903): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('aaa\/bbb...')\n#1 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(334): Sabre\\DAV\\Server->getPropertiesForPath('aaa\/bbb...', Array, 1)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#5 \/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/nextcloud\/remote.php(165): require_once('\/var\/www\/nextcl...')\n#8 {main}\",\"File\":\"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php\",\"Line\":173,\"User\":\"user2\"}",
   "method": "PROPFIND",
   "remoteAddr": "removed",
   "reqId": "fjDmcutcutcutpmYpC",
   "time": "2016-12-20T09:06:39+00:00",
   "url": "/remote.php/webdav/aaa/bbb",
   "user": "user2"
}

```

**Comment by nickvergessen** [comment] 2017-01-30 14:10
Duplicate of https://github.com/nextcloud/server/issues/2887

**Closed by nickvergessen** 2017-01-30 14:10 UTC
