### ISSUE TITLE
removed LDAP user still displayed and notified

### ISSUE THREAD

**Issue by thejulian** [nextcloud/server#5497] opened 2017-06-21 09:22 UTC
### Steps to reproduce
1. remove LDAP user
2. share something with the group the user was in
3. mail will be send to user (even if he isn't avaible in LDAP tree)

### Expected behaviour
User should not be shown in Contacts and should not be notified

### Actual behaviour
When I click on the Contact Symbol next to the search filed and my profile picture in the right corner the user is listed. If I count users in the LDAP Config Section it shows me the correct number. Also the the Person is not listed in the Users section. 

I'm not talking about the APP "contacts" this one is not in use & disabled.

### Server configuration

**Operating system**: CENTOS 7

**Web server:** Apache 2.4.6

**Database:** 5.5.52-MariaDB

**PHP version:** 7.0.19

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from latest 11

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0                                                                                                                                                                  
  - oauth2: 1.0.5                                                                                                                                                                         
  - password_policy: 1.2.2                                                                                                                                                                
  - provisioning_api: 1.2.0                                                                                                                                                               
  - serverinfo: 1.2.0                                                                                                                                                                     
  - sharebymail: 1.2.0                                                                                                                                                                    
  - survey_client: 1.0.0                                                                                                                                                                  
  - systemtags: 1.2.0                                                                                                                                                                     
  - theming: 1.3.0                                                                                                                                                                        
  - twofactor_backupcodes: 1.1.1                                                                                                                                                          
  - updatenotification: 1.2.0                                                                                                                                                             
  - user_ldap: 1.2.1                                                                                                                                                                      
  - workflowengine: 1.2.0                                                                                                                                                                 
Disabled:                                                                                                                                                                                 
  - contacts
  - encryption
  - files_external
  - spreed
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocla6eei09l6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "\/shared\/nextcloud_data",
        "skeletondirectory": "\/shared\/nextcloud\/core\/skeleton",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud_db",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***
        "mail_domain": "***REMOVED SENSITIVE VALUE***,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto,14",
        "filesystem_check_changes": 1,
        "maintenance": false,
        "theme": "",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** nope

**Are you using an external user-backend, if yes which one:** OpenLDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                         |
+-------------------------------+-------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                           |
| hasPagedResultSupport         |                                                                                                             |
| homeFolderNamingRule          | attr:uid                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                           |
| ldapAgentName                 | cn=Manager,dc=company,dc=work                                                                                  |
| ldapAgentPassword             | ***                                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                                             |
| ldapAttributesForUserSearch   |                                                                                                             |
| ldapBackupHost                | ldap://OpenLDAP-02.company.work                                                                                |
| ldapBackupPort                | 389                                                                                                         |
| ldapBase                      | dc=company,dc=work                                                                                             |
| ldapBaseGroups                | dc=company,dc=work                                                                                             |
| ldapBaseUsers                 | dc=company,dc=work                                                                                             |
| ldapCacheTTL                  | 600                                                                                                         |
| ldapConfigurationActive       | 1                                                                                                           |
| ldapDefaultPPolicyDN          |                                                                                                             |
| ldapDynamicGroupMemberURL     |                                                                                                             |
| ldapEmailAttribute            | mail                                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                                           |
| ldapExpertUUIDGroupAttr       |                                                                                                             |
| ldapExpertUUIDUserAttr        |                                                                                                             |
| ldapExpertUsernameAttr        |                                                                                                             |
| ldapGidNumber                 | gidNumber                                                                                                   |
| ldapGroupDisplayName          | cn                                                                                                          |
| ldapGroupFilter               |                                                                                                             |
| ldapGroupFilterGroups         |                                                                                                             |
| ldapGroupFilterMode           | 0                                                                                                           |
| ldapGroupFilterObjectclass    |                                                                                                             |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                |
| ldapHost                      | ldap://OpenLDAP-01.company.work                                                                                |
| ldapIgnoreNamingRules         |                                                                                                             |
| ldapLoginFilter               | (&(|(memberof=cn=Nextcloud,ou=Groups,dc=company,dc=work))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                             |
| ldapLoginFilterEmail          | 1                                                                                                           |
| ldapLoginFilterMode           | 0                                                                                                           |
| ldapLoginFilterUsername       | 1                                                                                                           |
| ldapNestedGroups              | 0                                                                                                           |
| ldapOverrideMainServer        |                                                                                                             |
| ldapPagingSize                | 500                                                                                                         |
| ldapPort                      | 389                                                                                                         |
| ldapQuotaAttribute            |                                                                                                             |
| ldapQuotaDefault              |                                                                                                             |
| ldapTLS                       | 0                                                                                                           |
| ldapUserDisplayName           | displayname                                                                                                 |
| ldapUserDisplayName2          |                                                                                                             |
| ldapUserFilter                | (|(memberof=cn=Nextcloud,ou=Groups,dc=company,dc=work))                                                        |
| ldapUserFilterGroups          | Nextcloud                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                           |
| ldapUserFilterObjectclass     |                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                                        |
| turnOffCertCheck              | 0                                                                                                           |
| turnOnPasswordChange          | 0                                                                                                           |
| useMemberOfToDetectMembership | 1                                                                                                           |
+-------------------------------+-------------------------------------------------------------------------------------------------------------+
```
</details>

### Client configuration
**Browser:** Firefox/Chrome/Safari

**Operating system:** Windows/Linux/Mac

### Logs
Could not find anything related to this in the logs.

**Comment by TheMrApostel** [comment] 2017-06-24 09:35
Please check you LDAP remnants with sudo -u www-data php occ ldap:show-remnants and delete all listed user with sudo -u www-data php occ user:delete [user] from your command line within the nextcloud folder.

You also want to delete the users completly by using occ user:delete [user] (This will remove the local Nextcloud user + the data stored in your data folder)

**Comment by thejulian** [comment] 2017-06-26 09:00
Doesn't work ..

+--------------------------------------+------------------+------------------+------------------------------------------------+-------------------+-----------------------------------------+--------+
| Nextcloud name                       | Display Name     | LDAP UID         | LDAP DN                                        | Last Login        | Dir                                     | Sharer |
+--------------------------------------+------------------+------------------+------------------------------------------------+-------------------+-----------------------------------------+--------+
```
| 0e645c9c-9780-1036-89eb-6b894c8d6283 | Jenkins Checkout | jenkins.checkout | uid=jenkins.checkout,ou=people,dc=company,dc=work | -                 | /shared/nextcloud_data/jenkins.checkout | N      |
| 48a2d45e-9c37-1036-89f9-6b894c8d6283 | Ned Flanders     | ned.flanders     | uid=ned.flanders,ou=people,dc=company,dc=work  | May 19, 2017      | /shared/nextcloud_data/ned.flanders  | N      |
| 4c9d6786-8d46-1036-8995-633447d0665b | homer.simpson    | homer.simpson    | cn=homer.simpson,ou=employees,dc=company,dc=work  | -                 |                                         | N      |
| 5acf960c-a32c-1036-8a01-6b894c8d6283 | Jenkins Uploader | jenkins.uploader | uid=jenkins.uploader,ou=people,dc=company,dc=work | March 22, 2017    | /shared/nextcloud_data/jenkins.uploader | N      |
| a04b7afe-8d3b-1036-908d-d508e61cfdbc | lisa.simpson     | lisa.simpson     | cn=lisa.simpson,ou=people,dc=company,dc=work      | February 24, 2017 |                                         | N      |
| a93ea726-8d45-1036-8992-633447d0665b | bart.simpson     | bart.simpson     | cn=bart.simpson,ou=people,dc=company,dc=work      | February 24, 2017 |                                         | N      |
+--------------------------------------+------------------+------------------+------------------------------------------------+-------------------+-----------------------------------------+--------+

```
```

cd /shared/nextcloud/ && sudo -u apache php -d memory_limit=16384M occ user:delete 0e645c9c-9780-1036-89eb-6b894c8d6283

                                                                    
  [OC\User\NoUserException]                                         
  0e645c9c-9780-1036-89eb-6b894c8d6283 is not a valid user anymore  
                                                                    

user:delete <uid>
```

I deleted them before in the WebUI like a normal user .. Maybe I should delete the entries from the database manually ? :s

**Comment by TheMrApostel** [comment] 2017-06-26 18:40
Could you please try the LDAP UID?
cd /shared/nextcloud/ && sudo -u apache php -d memory_limit=16384M occ user:delete jenkins.checkout

**Comment by thejulian** [comment] 2017-06-27 05:44
```
cd /shared/nextcloud/ && sudo -u apache php -d memory_limit=16384M occ user:delete jenkins.checkout
User does not exist

```
Still not working ...

**Comment by MorrisJobke** [comment] 2017-08-30 18:48
Duplicate of #4117

**Closed by MorrisJobke** 2017-08-30 18:48 UTC
