### ISSUE TITLE
[Bug]: Cannot preview photos with thumbnails

### ISSUE THREAD

**Issue by CamZie** [nextcloud/server#31202] opened 2022-02-16 09:12 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Viewing different photos (under 4MB) result to the following.

- Old photo (from more than a year ago) **WITH** thumbnail - **preview does not work**
- Old photo (from more than a year ago) and **NO** thumbnail - **preview works**
- New uploaded photo **WITH** thumbnail - **preview works**

### Steps to reproduce

Photo WITH thumbnail

1. Open old photo with thumbnail
2. Cannot view photo: `"Error loading <PHOTO>.jpg"`

Photo WITHOUT thumbnail

1. Open old photo without thumbnail
2. Preview works

### Expected behavior

All photos should have a thumbnail and preview should work without problems

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.7.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Zurich",
        "installed": true,
        "enable_previews": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_avatars": false,
        "logdateformat": "Y-m-d_H:i:s",
        "updatechecker": false,
        "log_type": "errorlog",
        "logfile": "",
        "loglevel": 2,
        "customclient_desktop": "https:\/\/***REMOVED SENSITIVE VALUE***\/en\/downloads",
        "maintenance": false,
        "trashbin_retention_obligation": "auto,90",
        "activity_expire_days": 90,
        "preview_max_scale_factor": 1,
        "preview_max_filesize_image": 5,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "skeletondir": "\/var\/www\/nextcloud\/themes\/skeleton",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "encryption.legacy_format_support": true,
        "encryption.key_storage_migrated": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - apporder: 0.14.0
  - bookmarks: 10.0.3
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.5
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.7
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - data_request: 1.8.0
  - dav: 1.17.1
  - deck: 1.4.7
  - encryption: 2.9.0
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.11.6
  - news: 17.0.1
  - notes: 4.3.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - passman: 2.4.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - provisioning_api: 1.11.0
  - qownnotesapi: 21.12.0
  - quota_warning: 1.13.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - tasks: 0.14.2
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
There are no error logs but here is the access log if this would help:

PHOTO WITH THUMBNAIL - PREVIEW DOES NOT WORK

***REMOVED*** - - [15/Feb/2022:17:33:52 +0100] "PROPFIND /remote.php/dav/files/***REMOVED***/photos/mens-gloves-touch-screen.jpg HTTP/2.0" 207 581 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.88 Safari/537.36"
***REMOVED*** - - [15/Feb/2022:17:33:52 +0100] "PROPFIND /remote.php/dav/files/***REMOVED***/photos/ HTTP/2.0" 207 4263 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.88 Safari/537.36"

PHOTO WITHOUT THUMBNAIL - PREVIEW WORKS

***REMOVED*** - - [15/Feb/2022:17:33:01 +0100] "PROPFIND /remote.php/dav/files/***REMOVED***/photos/EazyCapture20201203120637_7176321587722464039.jpg HTTP/2.0" 207 602 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.88 Safari/537.36"
***REMOVED*** - - [15/Feb/2022:17:33:02 +0100] "PROPFIND /remote.php/dav/files/***REMOVED***/photos/ HTTP/2.0" 207 4263 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.88 Safari/537.36"
```

**Comment by Slartibartfast27** [comment] 2022-02-20 19:51
eventually this could be related to the bug I just posted: https://github.com/nextcloud/server/issues/31284

**Comment by pierreozoux** [comment] 2022-10-28 16:32
closing as duplicate of https://github.com/nextcloud/server/issues/31284

**Closed by pierreozoux** 2022-10-28 16:32 UTC
Labels: bug, 0. Needs triage
