### ISSUE TITLE
Dark theme opposite color for last modification

### ISSUE THREAD

**Issue by Aerosmite** [nextcloud/server#21372] opened 2020-06-11 09:33 UTC
The dark theme should have the opposite color gradient for last modifications: white when it's recent, black when it's old.

**Comment by szaimen** [comment] 2021-06-02 12:31
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Closed by szaimen** 2021-06-02 12:31 UTC
Labels: 0. Needs triage, enhancement
