### ISSUE TITLE
occ comand dont work

### ISSUE THREAD

**Issue by Tim-Knoth** [nextcloud/server#24780] opened 2020-12-19 15:05 UTC
php occ throws the folowing exception
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\Analytics\Command\Load::__construct(), 0 passed in /var/www/nextcloud/lib/private/Console/Application.php on line 224 and exactly 1 expected in /var/www/nextcloud/apps/analytics/lib/Command/Load.php:25
Stack trace:
#0 /var/www/nextcloud/lib/private/Console/Application.php(224): OCA\Analytics\Command\Load->__construct()
#1 /var/www/nextcloud/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml()
#2 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands()
#3 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

**Comment by kesselb** [comment] 2020-12-19 18:01
Duplicate of https://github.com/nextcloud/server/issues/24680

**Closed by kesselb** 2020-12-19 18:01 UTC

**Comment by Rello** [comment] 2021-01-03 07:49
solved with Analytics 3.2.0
