### ISSUE TITLE
Add app settings links to Details menu in appstore

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22612] opened 2020-09-05 16:49 UTC
This is a papercut feature request to add links to an app's specific settings, where ever those might be within Nextcloud, to the details menu of that particular app in the appstore.

See this example and note there is no link of where to find the app's particular settings:
![image](https://user-images.githubusercontent.com/1787238/92309736-026e4700-ef5d-11ea-9240-c72facadf3f1.png)

**Comment by szaimen** [comment] 2021-06-09 14:11
Duplicate of https://github.com/nextcloud/server/issues/1062

**Closed by szaimen** 2021-06-09 14:11 UTC
Labels: 0. Needs triage, enhancement
