### ISSUE TITLE
[Bug]: Links to other nextcloud instances (ocm_provider) which are not reachable (connection timeout) slow down webdav

### ISSUE THREAD

**Issue by suchwerk** [nextcloud/server#42027] opened 2023-12-05 09:26 UTC
### Bug description

Opening a shared link (not related to the ocm-provider that's connection is broken) is very slow (took 10s to open a directory).  After  investigating i saw in the logs that there are timeouts on a ocm-provider in the (exactly) same time range. After removing this link the webdav's behavior was normal again.
```
GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 10000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cloud.xxxxx.xx/ocm-provider/
```
In the UI there is no information that this ocm-provider is not working correctly. Only if you look at the detail pages. Maybe a hint on link level would be good. 

### Steps to reproduce

1. Create link to a ocm-provider that produces a timeout
2. Generate a shared link
3. Open that link

### Expected behavior

Normal reactivity of webdav access on broken ocm-providers

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
php occ config:list system
php occ config:list system
./occ config:list system
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.suchwerk.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "https:\/\/cloud.suchwerk.de",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.suchwerk.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "https:\/\/cloud.suchwerk.de",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.suchwerk.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.3.2",
        "overwrite.cli.url": "https:\/\/cloud.suchwerk.de",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
```

### List of activated Apps

```shell
- dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.1.1
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0 (installed 2.4.0)
  - encryption: 2.15.0
  - socialsharing_diaspora: 2.6.0 (installed 2.6.0)
  - socialsharing_email: 2.6.0 (installed 2.6.0)
  - socialsharing_facebook: 2.6.0 (installed 2.6.0)
  - socialsharing_twitter: 2.6.0 (installed 2.6.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - calendar: 4.5.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.1.1
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0 (installed 2.4.0)
  - encryption: 2.15.0
  - socialsharing_diaspora: 2.6.0 (installed 2.6.0)
  - socialsharing_email: 2.6.0 (installed 2.6.0)
  - socialsharing_facebook: 2.6.0 (installed 2.6.0)
  - socialsharing_twitter: 2.6.0 (installed 2.6.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - calendar: 4.5.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.1.1
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0 (installed 2.4.0)
  - encryption: 2.15.0
  - socialsharing_diaspora: 2.6.0 (installed 2.6.0)
  - socialsharing_email: 2.6.0 (installed 2.6.0)
  - socialsharing_facebook: 2.6.0 (installed 2.6.0)
  - socialsharing_twitter: 2.6.0 (installed 2.6.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"FosdYDFmAiFzbdf4MawH","level":2,"time":"2023-12-05T08:58:19+00:00","remoteAddr":"172.24.0.7","user":"xxxx","app":"no app in context","method":"PROPFIND","url":"/remote.php/dav/files/xxxx/","message":"error while discovering ocm provider","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.10.1git (build 18409) (Nextcloud, osx-23.1.0 ClientArchitecture: arm64 OsArchitecture: arm64)","version":"27.1.3.2","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Connection timed out after 10001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://cloud.xxxxx-xxxxxxn.de/ocm-provider/","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[["GuzzleHttp\\Handler\\CurlHandler"],"*** sensitive parameters replaced ***",["GuzzleHttp\\Handler\\CurlFactory"]]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[["GuzzleHttp\\Handler\\CurlHandler"],"*** sensitive parameters replaced ***",["GuzzleHttp\\Handler\\CurlFactory"]]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":137,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Http/Client/DnsPinMiddleware.php","line":154,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Http/Client/Client.php","line":230,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***","https://cloud.xxxxx-xxxxxxn.de/ocm-provider/",[true,10,[["Closure"]],10,[false],"And 2 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/private/OCM/OCMDiscoveryService.php","line":87,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https://cloud.xxxxx-xxxxxxn.de/ocm-provider/",[10,true,10]]},{"file":"/var/www/html/apps/files_sharing/lib/External/Storage.php","line":84,"function":"discover","class":"OC\\OCM\\OCMDiscoveryService","type":"->","args":["https://cloud.xxxxx-xxxxxxn.de"]},{"file":"/var/www/html/lib/private/Files/Mount/MountPoint.php","line":168,"function":"__construct","class":"OCA\\Files_Sharing\\External\\Storage","type":"->","args":[["https://cloud.xxxxx-xxxxxxn.de/","xxxxx","","/xxxx/files/Limpia 625X","xxxx.xxxx","And 5 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/private/Files/Mount/MountPoint.php","line":193,"function":"createStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Files/Config/UserMountCache.php","line":83,"function":"getStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->","args":[]},{"function":"OC\\Files\\Config\\{closure}","class":"OC\\Files\\Config\\UserMountCache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Files/Config/UserMountCache.php","line":82,"function":"array_filter","args":[["*** sensitive parameters replaced ***",["OCA\\Files_Sharing\\SharedMount"],["OCA\\Files_Sharing\\SharedMount"]],["Closure"]]},{"file":"/var/www/html/lib/private/Files/SetupManager.php","line":299,"function":"registerMounts","class":"OC\\Files\\Config\\UserMountCache","type":"->","args":[["OC\\User\\User"],["*** sensitive parameters replaced ***",["OCA\\Files_Sharing\\SharedMount"],["OCA\\Files_Sharing\\SharedMount"]],["OC\\Files\\Mount\\CacheMountProvider","OCA\\Files_External\\Config\\ConfigAdapter","OCA\\Files_Sharing\\MountProvider","OCA\\Files_Sharing\\External\\MountProvider"]]},{"file":"/var/www/html/lib/private/Files/SetupManager.php","line":223,"function":"afterUserFullySetup","class":"OC\\Files\\SetupManager","type":"->","args":[["OC\\User\\User"],["OC\\Files\\Mount\\LocalHomeMountProvider"]]},{"file":"/var/www/html/lib/private/Files/SetupManager.php","line":399,"function":"setupForUser","class":"OC\\Files\\SetupManager","type":"->","args":[["OC\\User\\User"]]},{"file":"/var/www/html/lib/private/Files/Mount/Manager.php","line":128,"function":"setupForPath","class":"OC\\Files\\SetupManager","type":"->","args":["/xxxx/files",true]},{"file":"/var/www/html/lib/private/Files/View.php","line":1411,"function":"findIn","class":"OC\\Files\\Mount\\Manager","type":"->","args":["/xxxx/files"]},{"file":"/var/www/html/lib/private/Files/Node/Node.php","line":118,"function":"addSubMounts","class":"OC\\Files\\View","type":"->","args":[["OC\\Files\\FileInfo"]]},{"file":"/var/www/html/lib/private/Files/Node/Node.php","line":237,"function":"getFileInfo","class":"OC\\Files\\Node\\Node","type":"->","args":[]},{"function":"getEtag","class":"OC\\Files\\Node\\Node","type":"->","args":[]},{"file":"/var/www/html/lib/private/Files/Node/LazyFolder.php","line":74,"function":"call_user_func_array","args":[[["OC\\Files\\Node\\Folder"],"getEtag"],[]]},{"file":"/var/www/html/lib/private/Files/Node/LazyFolder.php","line":238,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->","args":["getEtag",[]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Node.php","line":208,"function":"getEtag","class":"OC\\Files\\Node\\LazyFolder","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/FilesPlugin.php","line":341,"function":"getETag","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\FilesPlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/FilesPlugin.php","line":340,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{DAV:}getetag",["Closure"]]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\FilesPlugin","type":"->","args":[["Sabre\\DAV\\PropFind"],["OCA\\DAV\\Files\\FilesHome"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["propFind",[["Sabre\\DAV\\PropFind"],["OCA\\DAV\\Files\\FilesHome"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\DAV\\PropFind"],["OCA\\DAV\\Files\\FilesHome"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files/xxxx",["{DAV:}getetag"],0]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\Xml\\Writer",[],"/remote.php/dav/",["d","s","oc","nc"],[]],["Generator"],false]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[["Generator"],false]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PROPFIND",[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[["Sabre\\HTTP\\Request"],["Sabre\\HTTP\\Response"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":365,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":172,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"message":"error while discovering ocm provider","exception":[],"remote":"https://cloud.xxxxx-xxxxxxn.de","CustomMessage":"error while discovering ocm provider"},"id":"656eeb6ce2d3e"}
```

**Comment by szaimen** [comment] 2023-12-05 09:33
cc @ArtificialOwl

**Comment by tim427** [comment] 2023-12-15 12:49
I experience the same behaviour, resulting in WebDAV-enabled clients timing out, etc.

Figured out I've one federated share, which is currently down. For your situation that would be the `"remote":"https://cloud.xxxxx-xxxxxxn.de"`.

Could you verify if this "remote nextcloud" instance is still accessible?

Besides this cause, it would be nice if this error is reflected somewhere, or temporarily disable the remote/federated share after some attempts.

Why is this causing a delay for a WebDAV call directly to a specific file, which is just locally in the root dir?

`curl --user '<USER>:<APP-PASSWORD>' 'https://nextcloud.<DOMAIN>/remote.php/dav/files/<USERNAME>/<FILE>' took around 11 seconds.

**Comment by apoger** [comment] 2023-12-27 12:08
I am also affected. The message "OCMProviderException" stays after deleting that specific OCM share from the admin sharing panel. Strange!

**Comment by zulf10** [comment] 2024-01-31 16:52
Same issue. 

Also on users pages on url: `/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=` with message `"cURL error 28: Connection timed out after 10000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://nextcloud/ocm-provider/"`

I have a Caddy proxy (On Proxmox LXC) that refers to a Nginx+php-fpm (On Proxmox Debian VM) in same local network.
All supply chain can ping an curl nextcloud address

All apps are slow (10s to 15s per actions).

I have increase timeout on Nginx and php-fpm but same issue.

Is anything to do ?

**Comment by juergen852** [comment] 2024-02-11 16:53
Same problem here.
xxxxxxx.dyndns.info is down now and I could not find a way to unconfigure the nc instance that was at xxxxxxx.dyndns.info in my main nextcloud....


Warnung no app in context
ConnectException cURL error 28: Failed to connect to xxxxxxx.dyndns.info port 4431 after 5202 ms: Connection timed out (see [libcurl - Error Codes](https://curl.haxx.se/libcurl/c/libcurl-errors.html)) for https://xxxxxx.dyndns.info:4431/ocm-provider/
error while discovering ocm provider

StorageNotAvailableException Sabre\HTTP\ClientException: Failed to connect to xxxxxxxxx.dyndns.info port 4431 after 130047 ms: Connection timed out
External storage not available: Sabre\HTTP\ClientException: Failed to connect to xxxxxxxxxx.dyndns.info port 4431 after 130047 ms: Connection timed out

Currently running Nextcloud Hub 7 (28.0.2), but it has been like this since NC20.

**Comment by zulf10** [comment] 2024-02-12 20:57
Fix with new rule LAN to LAN into top firewall. Nextcloud can look into itself

**Comment by juergen852** [comment] 2024-02-21 17:13
"Fix with new rule LAN to LAN into top firewall. Nextcloud can look into itself"
Can you please explain a little bit more?

**Comment by zulf10** [comment] 2024-03-08 22:32
In my case, a physical firewall is present upstream of the host server (in addition to the host and VM firewalls).
It was the physical firewall that prevented the VM's Nextcloud from polling itself. 
By adding a LAN => LAN rule, the Nextcloud is able to resolve its own domain.

Is it any clearer?

**Comment by gerion0** [comment] 2024-08-18 14:35
I have the same problem:
1. I once made a federated share to a nextcloud instance behind a dyndns domain.
2. The domain is long gone.
3. My nextcloud tries to keep to connect to that instance (slows down and spams the log).

My questions here:
1. Is there a way to "unshare" the folder in the webinterface? I'm not even knowing anymore the shared folder's name. Is it possible to find out the local path in my instance to the respective shared folder?
2. Is there a workaround by deleting the required database rows? Which table stores the information for federed shares?

**Comment by joshtrichards** [comment] 2024-09-02 13:36
Related: #30552

**Comment by joshtrichards** [comment] 2024-11-09 14:53
Error reporting in the Web UI improved via #48625
Otherwise this is a duplicate of #30552

**Closed by joshtrichards** 2024-11-09 14:53 UTC
Labels: bug, feature: sharing, feature: federation, 0. Needs triage, 27-feedback
