### ISSUE TITLE
[Bug]: Confusing "Add remote share" dialog popup in Files App

### ISSUE THREAD

**Issue by SergeyMosin** [nextcloud/server#38589] opened 2023-06-01 16:47 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This (see image) pops up in files App when there are pending shares

I think the "Add remote share" button should say "Cancel" and CSS fixes are needed for the top [x] button

![image](https://github.com/nextcloud/server/assets/10747559/09f8fa21-fe68-4c5f-9e0e-2f3fba729153)

### Steps to reproduce

1. Ask someone to send you a Federated Share
2. Do NOT accept it via "Bell" notification  
3. Got to the Files App or reload the page if you are already there
4. :boom: the "confusing" dialog pops up

![image](https://github.com/nextcloud/server/assets/10747559/967c489c-ed3d-48d7-94f9-c6aa6f9c8a76)

### Expected behavior

The dialog should Not be confusing

### Installation method

Community Docker image

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
fresh/standard
```

### List of activated Apps

```shell
fresh/standard
```

### Nextcloud Signing status

```shell
NA
```

### Nextcloud Logs

```shell
NA
```

### Additional info

NA

**Comment by danxuliu** [comment] 2024-04-15 04:33
Fixed in https://github.com/nextcloud/server/pull/37697.

Note that the dialog should not have been shown if the Notifications app was enabled, but it was due to a regression. See #44823.

**Closed by danxuliu** 2024-04-15 04:33 UTC
Labels: bug, feature: federation, 0. Needs triage, 25-feedback
