### ISSUE TITLE
I transferred the ownership of a file or folder, everything is normal and no error is reported, but the receiving user did not receive a prompt whether to accept or reject the incoming, why?

### ISSUE THREAD

**Issue by fan4905** [nextcloud/server#26354] opened 2021-03-29 08:13 UTC
I transferred the ownership of a file or folder, everything is normal and no error is reported, but the receiving user did not receive a prompt whether to accept or reject the incoming, why?

**Comment by fan4905** [comment] 2021-03-29 08:14
The 20.0.8 version I use

**Comment by szaimen** [comment] 2021-07-02 11:19
Duplicate of https://github.com/nextcloud/server/issues/21856

**Closed by szaimen** 2021-07-02 11:19 UTC
Labels: 0. Needs triage, bug
