### ISSUE TITLE
Group Folders break Favorites on Clients

### ISSUE THREAD

**Issue by stalinCCCP415** [nextcloud/server#17918] opened 2019-11-12 19:01 UTC
Please take a look at this thread:

https://help.nextcloud.com/t/cant-favorite-file-on-mobile-client-ios/62591

Nextcloud 16 and 17 - when turning on group folders, clients (iOS for sure, maybe others) cannot favorite items.

**Comment by j-ed** [comment] 2019-11-12 19:15
I would assume that this problem should be raised in the [groupfolders repository](https://github.com/nextcloud/groupfolders/issues/674) where a [related issue report](https://github.com/nextcloud/groupfolders/issues/674) already exists.

**Comment by juliushaertl** [comment] 2019-11-12 19:42
Duplicate of https://github.com/nextcloud/groupfolders/issues/674

**Closed by juliushaertl** 2019-11-12 19:42 UTC
