### ISSUE TITLE
Error opening file containing space in file name 

### ISSUE THREAD

**Issue by seyfeb** [nextcloud/server#27181] opened 2021-05-27 08:26 UTC
### Steps to reproduce
1. Add file containing a space in the file name, e.g., `space name.pdf`.
2. Navigate to directory in the files app and try to open
3. Observe error `Missing PDF file.`

### Expected behaviour
File should be opened.

### Actual behaviour
Error message opening file

```
PDF.js v2.5.207 (build: 0974d6052)
Message: Missing PDF "https://.../remote.php/dav/files/.../space%2520name.pdf".
```

The space seems to be converted to `%2520` instead of `%20`.

### Server configuration

The current nextcloud docker image `21.0.2-apache`.

**Database:** postgres

**Nextcloud version:** 21.0.2

**Signing status:** No errors have been found.

### Client configuration
**Browser:** Vivaldi, FF

### Browser log

```
GET https://.../remote.php/dav/files/.../space%2520name.pdf
Status 404
Not Found
```

**Comment by acsfer** [comment] 2021-05-27 08:27
Duplicate of https://github.com/nextcloud/files_pdfviewer/issues/381

**Closed by acsfer** 2021-05-27 08:27 UTC
Labels: 0. Needs triage, bug
