### ISSUE TITLE
FR: inclusive tag search

### ISSUE THREAD

**Issue by cvoges12** [nextcloud/server#31287] opened 2022-02-20 23:12 UTC
Currently tag search is only exclusive. Meaning, the tags are searched in an logical **AND** manner where the search results most be in both searched tags.

It would be useful for inclusive tag search which has a logical **OR** manner of search. Even if the results are not in both tags of the search query, this would allow search results to appear of any tag.

This could be beneficial for a more "fuzzy" style search pattern. This is beneficial to see results from more than one tag at once in a very UX friendly manner.

Results could be further optimized to list most "relevant" results. Meaning, the results with most tags can be filtered to the top.

**Comment by joshtrichards** [comment] 2023-09-15 16:03
Duplicate of #4851

Please subscribe to that issue to monitor progress and give it a thumbs up to express your interest.

**Closed by joshtrichards** 2023-09-15 16:03 UTC
Labels: enhancement, 0. Needs triage, feature: tags, feature: search
