### ISSUE TITLE
[Bug]: The "X-Robots-Tag" header is checked wrongly.

### ISSUE THREAD

**Issue by ozgurkazancci** [nextcloud/server#41001] opened 2023-10-19 21:35 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello. I'm running Nextcloud 27.1.2.1 on an OpenBSD box. Having the following header in my nginx.conf file, for even further privacy;

`add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive" always;`

However the "**Security & setup warnings**" reports;

_The "X-Robots-Tag" HTTP header is not set to "noindex, nofollow". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly._

I think that's because the add_header line has extra "nosnippet" and "noarchive", whenever I remove both (remaining only 'noindex' and 'nofollow'), I don't get the warning report above, but both tags bring a better privacy;

**noarchive** is to not show a cached link in search results. If you don't specify this rule, Google may generate a cached page and users may access it through the search results.

**nosnippet** is to not show a text snippet or video preview in the search results for this page.

Is it possible to include them to allow Nextcloud's system checking?

### Steps to reproduce

1. Have: `add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive" always;` in your nginx.conf
2. Check the "Security & setup warnings" page in dashboard

### Expected behavior

Recognizing and passing "noarchive" and "nosnippet" directives as well.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment] 2023-10-20 13:51
Duplicate of https://github.com/nextcloud/server/issues/37409

**Closed by solracsf** 2023-10-20 13:51 UTC
Labels: bug, 0. Needs triage, 27-feedback
